### ISSUE TITLE
Trouble installing ScyllaDB on Ubuntu 18

### ISSUE THREAD

**Issue by xphoniex** [scylladb/scylla#6698] opened 2020-06-23 06:44 UTC
Following the guide [here](https://www.scylladb.com/download/?platform=ubuntu-18.04&version=scylla-4.0):

```
$ sudo apt-get install scylla
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 scylla : Depends: scylla-jmx but it is not going to be installed
          Depends: scylla-tools but it is not going to be installed
          Depends: scylla-tools-core but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

In the installation guide (above link), java is configured after scylla is installed, so this is unexpected. 

Also when trying to install dependencies separately, for example `scylla-jmx`:

```
$ sudo apt-get install scylla-jmx
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages were automatically installed and are no longer required:
  …
Use 'sudo apt autoremove' to remove them.
The following additional packages will be installed:
  scylla-conf scylla-python3 scylla-server
The following packages will be REMOVED:
  cuda-9-2 cuda-nsight-9-2 cuda-nvvp-9-2 cuda-toolkit-9-2 cuda-tools-9-2
  cuda-visual-tools-9-2 default-jdk default-jdk-headless default-jre
  default-jre-headless openjdk-11-jdk openjdk-11-jdk-headless openjdk-11-jre
  openjdk-11-jre-headless
The following NEW packages will be installed:
  scylla-conf scylla-jmx scylla-python3 scylla-server
0 upgraded, 4 newly installed, 14 to remove and 376 not upgraded.
Need to get 61.7 MB of archives.
After this operation, 571 MB disk space will be freed.
Do you want to continue? [Y/n] n
Abort.
```
If `openjdk-11` is the problem here, why then is it trying to remove `cuda`? Also I'm sure I need `openjdk-11` to run some other softwares...

And what does scylla use java for?

**Comment by tzach** [comment] 2020-06-23 09:39
Hi @xphoniex 
I fail to reproduce on Ubuntu 18
Can you please add `lsb_release -a` info?
Are you using a minimalist Ubuntu?

**Comment by tzach** [comment] 2020-06-23 09:39
@syuu1228 does this look familiar ?

**Comment by xphoniex** [comment] 2020-06-23 09:49
```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.2 LTS
Release:	18.04
Codename:	bionic
```

**Comment by tzach** [comment] 2020-06-23 18:05
Might be similar to #4665

**Comment by syuu1228** [comment] 2020-06-23 18:06
> If `openjdk-11` is the problem here, why then is it trying to remove `cuda`? 

Because CUDA requires OpenJDK:
```
vagrant@ubuntu1804:~$ sudo apt show cuda-nsight-9-2
Package: cuda-nsight-9-2
Version: 9.2.148-1
Priority: optional
Section: multiverse/devel
Source: cuda
Maintainer: cudatools <cudatools@nvidia.com>
Installed-Size: 25.6 kB
Depends: cuda-license-9-2, default-jre (>= 1.7) | openjdk-7-jre, libcairo2
Download-Size: 2,582 B
APT-Manual-Installed: no
APT-Sources: http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1710/x86_64  Packages
Description: CUDA nsight
 NVIDIA Nsight Eclipse Edition is a unified CPU plus GPU integrated
 development environment (IDE) for developing CUDA applications for
 the x86, POWER and ARM platforms.

N: There is 1 additional record. Please use the '-a' switch to see it
vagrant@ubuntu1804:~$ sudo apt show cuda-nvvp-9-2
Package: cuda-nvvp-9-2
Version: 9.2.148-1
Priority: optional
Section: multiverse/devel
Source: cuda
Maintainer: cudatools <cudatools@nvidia.com>
Installed-Size: 25.6 kB
Depends: cuda-license-9-2, default-jre (>= 1.7) | openjdk-7-jre, libcairo2
Download-Size: 2,528 B
APT-Manual-Installed: no
APT-Sources: http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1710/x86_64  Packages
Description: CUDA nvvp
 NVIDIA Visual Profiler to visualize and optimize the performance of your
 application.

N: There is 1 additional record. Please use the '-a' switch to see it
```

> And what does scylla use java for?

It used for scylla-tools and scylla-jmx.
I suppose we will switch to OpenJDK-11 in future releases, but for now I think you'll need to use a container to use Scylla and OpenJDK-11 apps in same machine.

**Comment by syuu1228** [comment] 2020-06-23 20:14
> Might be similar to #4665

@tzach It also OpenJDK-8 vs OpenJDK-11 issue, but #4665 was about Debian 10 does not provide OpenJDK-8 on their official repo.
So we supported 3rdparty repo's OpenJDK-8 for the distribution at https://github.com/scylladb/scylla-jmx/commit/f2fc1b912c522664577b8879f7ed717141a4e73b
But this issue is about the user want install both Scylla and OpenJDK-11, instead of uninstall OpenJDK-11.
So it bit related but different.
I think we should just switch to OpenJDK-11, anyway.

**Comment by tzach** [comment] 2020-06-24 06:14
> I think we should just switch to OpenJDK-11, anyway.

+1

**Comment by xphoniex** [comment] 2020-06-26 12:35
@syuu1228 how hard would it be to bump it to OpenJDK-11 and build it from source?
if it involves just a few config files then I can do my own build in the meanwhile.

**Comment by xphoniex** [comment] 2020-06-27 13:38
Docker's also not smart enough to handle a 500mb(!) image download if your connection is not super fast...
```
$ docker pull scylladb/scylla
Using default tag: latest
latest: Pulling from scylladb/scylla
ab5ef0e58194: Downloading  5.184MB
9b0bf50e4413: Download complete 
c0705fcbdb82: Download complete 
44aa8a95537c: Download complete 
928c17737cec: Download complete 
b54663c83546: Download complete 
32d08302a47a: Download complete 
889b0aa90fd9: Download complete 
5ff634956c59: Download complete 
5f7a86c7acf6: Download complete 
978ac00ea1d4: Download complete 
23e5c7697c26: Download complete 
bb820de1c927: Download complete 
18fe237451f6: Download complete 
876977eac410: Download complete 
1d8d0842bb58: Download complete 
eab5b99dc96d: Download complete 
1cf0ac1878c8: Download complete 
e2d22c3c6f57: Download complete 
b5b834f964be: Download complete 
297aa0e872cd: Downloading [==================================================>]  23.36MB/23.36MB
unexpected EOF // <---
```

@avikivity I'm excited to try out ScyllaDB but I can't even get it installed.

**Comment by avikivity** [comment] 2020-06-28 09:32
I can't help with docker refusing to download something.

We'll soon support Java 11, until then you can try again with Docker or a virtual machine with Java 8.

Closing as duplicate of https://github.com/scylladb/scylla-tools-java/issues/177.

**Closed by avikivity** 2020-06-28 09:32 UTC
Labels: onboarding, ubuntu
