### ISSUE TITLE
No space left on device after restart_then_repair_node

### ISSUE THREAD

**Issue by ShlomiBalalis** [scylladb/scylla#4939] opened 2019-09-01 15:17 UTC
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [x] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash):3.1.0.rc4-0.20190828.d70c2db09
Cluster size:4
OS (RHEL/CentOS/Ubuntu/AWS AMI):ami-05f77d44238bc0bf4

After restart_then_repair nemesis, the target node ran out of disk space:
```
2019-08-29T11:17:59+00:00  ip-10-0-53-194 !WARNING | scylla: [shard 2] storage_service - Shutting down communications due to I/O errors until operator intervention
2019-08-29T11:17:59+00:00  ip-10-0-53-194 !WARNING | scylla: [shard 2] storage_service - Disk error: std::system_error (error system:28, No space left on device)
2019-08-29T11:17:59+00:00  ip-10-0-53-194 !INFO    | scylla: [shard 0] storage_service - Stop transport: starts
2019-08-29T11:17:59+00:00  ip-10-0-53-194 !INFO    | scylla: [shard 0] storage_service - Stop transport: shutdown rpc and cql server done
2019-08-29T11:17:59+00:00  ip-10-0-53-194 !INFO    | scylla: [shard 0] gossip - My status = hibernate
2019-08-29T11:17:59+00:00  ip-10-0-53-194 !WARNING | scylla: [shard 0] gossip - No local state or state is in silent shutdown, not announcing shutdown
2019-08-29T11:17:59+00:00  ip-10-0-53-194 !INFO    | scylla: [shard 0] storage_service - Stop transport: stop_gossiping done
2019-08-29T11:17:59+00:00  ip-10-0-53-194 !ERR     | scylla: [shard 2] sstable - writer failed to close file: storage_io_error (Storage I/O error: 28: No space left on device)
2019-08-29T11:17:59+00:00  ip-10-0-53-194 !ERR     | scylla: [shard 3] sstable - writer failed to close file: storage_io_error (Storage I/O error: 28: No space left on device)
2019-08-29T11:17:59+00:00  ip-10-0-53-194 !INFO    | scylla: [shard 0] storage_service - messaging_service stopped
2019-08-29T11:17:59+00:00  ip-10-0-53-194 !INFO    | scylla: [shard 0] storage_service - Stop transport: shutdown messaging_service done
2019-08-29T11:17:59+00:00  ip-10-0-53-194 !WARNING | scylla: [shard 0] stream_session - [Stream #83c00490-ca4e-11e9-b6e7-000000000002] Streaming plan for Bootstrap-scylla_bench-index-1 failed, peers={10.0.69.40}, tx=0 KiB, 0.00 KiB/s, rx=2788480 KiB, 45365.48 KiB/s
2019-08-29T11:17:59+00:00  ip-10-0-53-194 !WARNING | scylla: [shard 0] stream_session - [Stream #83b64090-ca4e-11e9-b6e7-000000000002] Streaming plan for Bootstrap-scylla_bench-index-1 failed, peers={10.0.152.107}, tx=0 KiB, 0.00 KiB/s, rx=2800538 KiB, 45517.23 KiB/s
2019-08-29T11:17:59+00:00  ip-10-0-53-194 !WARNING | scylla: [shard 0] stream_session - [Stream #83b15e90-ca4e-11e9-b6e7-000000000002] Streaming plan for Bootstrap-scylla_bench-index-0 failed, peers={10.0.252.116}, tx=0 KiB, 0.00 KiB/s, rx=2817443 KiB, 45769.67 KiB/s
2019-08-29T11:17:59+00:00  ip-10-0-53-194 !INFO    | scylla: [shard 0] storage_service - stream_manager stopped
2019-08-29T11:17:59+00:00  ip-10-0-53-194 !INFO    | scylla: [shard 0] storage_service - Stop transport: shutdown stream_manager done
2019-08-29T11:17:59+00:00  ip-10-0-53-194 !INFO    | scylla: [shard 0] storage_service - Stop transport: auth shutdown
2019-08-29T11:17:59+00:00  ip-10-0-53-194 !INFO    | scylla: [shard 0] storage_service - Stop transport: done
```
It seems that happened because scylla is writing too many messages to journalctl, by those log messages:
```
2019-08-29T11:25:14+00:00  ip-10-0-53-194 !INFO    | journal: Suppressed 21642 messages from /system.slice/scylla-server.service
2019-08-29T11:27:59+00:00  ip-10-0-53-194 !INFO    | journal: Suppressed 350 messages from /system.slice/scylla-server.service
2019-08-29T13:04:31+00:00  ip-10-0-53-194 !INFO    | journal: Suppressed 63054 messages from /system.slice/scylla-server.service
2019-08-29T13:05:01+00:00  ip-10-0-53-194 !INFO    | journal: Suppressed 64114 messages from /system.slice/scylla-server.service
2019-08-29T13:05:31+00:00  ip-10-0-53-194 !INFO    | journal: Suppressed 64166 messages from /system.slice/scylla-server.service
2019-08-29T13:06:01+00:00  ip-10-0-53-194 !INFO    | journal: Suppressed 64135 messages from /system.slice/scylla-server.service
2019-08-29T13:06:31+00:00  ip-10-0-53-194 !INFO    | journal: Suppressed 64124 messages from /system.slice/scylla-server.service
2019-08-29T13:07:01+00:00  ip-10-0-53-194 !INFO    | journal: Suppressed 64222 messages from /system.slice/scylla-server.service
2019-08-29T13:07:31+00:00  ip-10-0-53-194 !INFO    | journal: Suppressed 64160 messages from /system.slice/scylla-server.service
2019-08-29T13:09:14+00:00  ip-10-0-53-194 !INFO    | journal: Suppressed 28388 messages from /system.slice/scylla-server.service
2019-08-29T13:18:56+00:00  ip-10-0-53-194 !INFO    | journal: Suppressed 64126 messages from /system.slice/scylla-server.service
2019-08-29T13:19:26+00:00  ip-10-0-53-194 !INFO    | journal: Suppressed 64172 messages from /system.slice/scylla-server.service
2019-08-29T13:19:56+00:00  ip-10-0-53-194 !INFO    | journal: Suppressed 64253 messages from /system.slice/scylla-server.service
2019-08-29T13:20:26+00:00  ip-10-0-53-194 !INFO    | journal: Suppressed 64119 messages from /system.slice/scylla-server.service
2019-08-29T13:20:56+00:00  ip-10-0-53-194 !INFO    | journal: Suppressed 64164 messages from /system.slice/scylla-server.service
2019-08-29T13:21:26+00:00  ip-10-0-53-194 !INFO    | journal: Suppressed 64354 messages from /system.slice/scylla-server.service
2019-08-29T13:21:56+00:00  ip-10-0-53-194 !INFO    | journal: Suppressed 64423 messages from /system.slice/scylla-server.service
2019-08-29T13:33:18+00:00  ip-10-0-53-194 !INFO    | journal: Suppressed 64269 messages from /system.slice/scylla-server.service
2019-08-29T13:33:48+00:00  ip-10-0-53-194 !INFO    | journal: Suppressed 64243 messages from /system.slice/scylla-server.service
2019-08-29T13:34:18+00:00  ip-10-0-53-194 !INFO    | journal: Suppressed 64234 messages from /system.slice/scylla-server.service
2019-08-29T13:34:48+00:00  ip-10-0-53-194 !INFO    | journal: Suppressed 64302 messages from /system.slice/scylla-server.service
2019-08-29T13:35:18+00:00  ip-10-0-53-194 !INFO    | journal: Suppressed 64043 messages from /system.slice/scylla-server.service
2019-08-29T13:35:48+00:00  ip-10-0-53-194 !INFO    | journal: Suppressed 64281 messages from /system.slice/scylla-server.service
2019-08-29T13:36:18+00:00  ip-10-0-53-194 !INFO    | journal: Suppressed 64235 messages from /system.slice/scylla-server.service
2019-08-29T13:39:55+00:00  ip-10-0-53-194 !INFO    | journal: Suppressed 26758 messages from /system.slice/scylla-server.service
2019-08-29T13:47:42+00:00  ip-10-0-53-194 !INFO    | journal: Suppressed 64170 messages from /system.slice/scylla-server.service
2019-08-29T13:48:12+00:00  ip-10-0-53-194 !INFO    | journal: Suppressed 64246 messages from /system.slice/scylla-server.service
2019-08-29T13:48:42+00:00  ip-10-0-53-194 !INFO    | journal: Suppressed 64281 messages from /system.slice/scylla-server.service
2019-08-29T13:49:12+00:00  ip-10-0-53-194 !INFO    | journal: Suppressed 64319 messages from /system.slice/scylla-server.service
2019-08-29T13:49:42+00:00  ip-10-0-53-194 !INFO    | journal: Suppressed 64284 messages from /system.slice/scylla-server.service
2019-08-29T13:50:12+00:00  ip-10-0-53-194 !INFO    | journal: Suppressed 64206 messages from /system.slice/scylla-server.service
2019-08-29T13:50:42+00:00  ip-10-0-53-194 !INFO    | journal: Suppressed 64352 messages from /system.slice/scylla-server.service
2019-08-29T13:54:27+00:00  ip-10-0-53-194 !INFO    | journal: Suppressed 26515 messages from /system.slice/scylla-server.service
2019-08-29T14:02:04+00:00  ip-10-0-53-194 !INFO    | journal: Suppressed 41372 messages from /system.slice/scylla-server.service
2019-08-29T14:02:34+00:00  ip-10-0-53-194 !INFO    | journal: Suppressed 26287 messages from /system.slice/scylla-server.service
2019-08-29T14:03:04+00:00  ip-10-0-53-194 !INFO    | journal: Suppressed 30160 messages from /system.slice/scylla-server.service
2019-08-29T14:03:34+00:00  ip-10-0-53-194 !INFO    | journal: Suppressed 43600 messages from /system.slice/scylla-server.service
2019-08-29T14:04:04+00:00  ip-10-0-53-194 !INFO    | journal: Suppressed 49525 messages from /system.slice/scylla-server.service
2019-08-29T14:04:34+00:00  ip-10-0-53-194 !INFO    | journal: Suppressed 33706 messages from /system.slice/scylla-server.service
2019-08-29T14:05:04+00:00  ip-10-0-53-194 !INFO    | journal: Suppressed 32861 messages from /system.slice/scylla-server.service
2019-08-29T14:07:34+00:00  ip-10-0-53-194 !INFO    | journal: Suppressed 37825 messages from /system.slice/scylla-server.service
2019-08-29T14:10:52+00:00  ip-10-0-53-194 !INFO    | journal: Suppressed 2801 messages from /system.slice/scylla-server.service
2019-08-29T14:11:22+00:00  ip-10-0-53-194 !INFO    | journal: Suppressed 2798 messages from /system.slice/scylla-server.service
2019-08-29T14:11:52+00:00  ip-10-0-53-194 !INFO    | journal: Suppressed 2797 messages from /system.slice/scylla-server.service
2019-08-29T16:36:11+00:00  ip-10-0-53-194 !INFO    | journal: Suppressed 64068 messages from /system.slice/scylla-server.service
2019-08-29T16:36:41+00:00  ip-10-0-53-194 !INFO    | journal: Suppressed 64398 messages from /system.slice/scylla-server.service
2019-08-29T16:37:11+00:00  ip-10-0-53-194 !INFO    | journal: Suppressed 64377 messages from /system.slice/scylla-server.service
2019-08-29T16:37:41+00:00  ip-10-0-53-194 !INFO    | journal: Suppressed 64433 messages from /system.slice/scylla-server.service
2019-08-29T16:38:11+00:00  ip-10-0-53-194 !INFO    | journal: Suppressed 64465 messages from /system.slice/scylla-server.service
2019-08-29T16:38:41+00:00  ip-10-0-53-194 !INFO    | journal: Suppressed 64349 messages from /system.slice/scylla-server.service
2019-08-29T16:39:11+00:00  ip-10-0-53-194 !INFO    | journal: Suppressed 64397 messages from /system.slice/scylla-server.service
2019-08-29T14:05:04+00:00  ip-10-0-53-194 !INFO    | journal: Suppressed 32861 messages from /system.slice/scylla-server.service
2019-08-29T14:05:34+00:00  ip-10-0-53-194 !INFO    | journal: Suppressed 35482 messages from /system.slice/scylla-server.service
2019-08-29T14:06:04+00:00  ip-10-0-53-194 !INFO    | journal: Suppressed 32649 messages from /system.slice/scylla-server.service
2019-08-29T14:06:34+00:00  ip-10-0-53-194 !INFO    | journal: Suppressed 43609 messages from /system.slice/scylla-server.service
2019-08-29T16:50:00+00:00  ip-10-0-53-194 !INFO    | journal: Suppressed 25876 messages from /system.slice/scylla-server.service
2019-08-29T16:50:30+00:00  ip-10-0-53-194 !INFO    | journal: Suppressed 64357 messages from /system.slice/scylla-server.service
2019-08-29T16:51:00+00:00  ip-10-0-53-194 !INFO    | journal: Suppressed 63670 messages from /system.slice/scylla-server.service
2019-08-29T16:51:30+00:00  ip-10-0-53-194 !INFO    | journal: Suppressed 64346 messages from /system.slice/scylla-server.service
2019-08-29T16:52:00+00:00  ip-10-0-53-194 !INFO    | journal: Suppressed 64363 messages from /system.slice/scylla-server.service
2019-08-29T16:52:30+00:00  ip-10-0-53-194 !INFO    | journal: Suppressed 64441 messages from /system.slice/scylla-server.service
2019-08-29T16:53:00+00:00  ip-10-0-53-194 !INFO    | journal: Suppressed 64443 messages from /system.slice/scylla-server.service
2019-08-29T17:04:21+00:00  ip-10-0-53-194 !INFO    | journal: Suppressed 28258 messages from /system.slice/scylla-server.service
2019-08-29T17:04:51+00:00  ip-10-0-53-194 !INFO    | journal: Suppressed 64088 messages from /system.slice/scylla-server.service
2019-08-29T17:05:22+00:00  ip-10-0-53-194 !INFO    | journal: Suppressed 63825 messages from /system.slice/scylla-server.service
2019-08-29T17:05:52+00:00  ip-10-0-53-194 !INFO    | journal: Suppressed 64186 messages from /system.slice/scylla-server.service
2019-08-29T17:06:22+00:00  ip-10-0-53-194 !INFO    | journal: Suppressed 64265 messages from /system.slice/scylla-server.service
2019-08-29T17:06:52+00:00  ip-10-0-53-194 !INFO    | journal: Suppressed 64370 messages from /system.slice/scylla-server.service
2019-08-29T17:07:22+00:00  ip-10-0-53-194 !INFO    | journal: Suppressed 63810 messages from /system.slice/scylla-server.service
2019-08-29T17:18:44+00:00  ip-10-0-53-194 !INFO    | journal: Suppressed 27675 messages from /system.slice/scylla-server.service
2019-08-29T17:19:14+00:00  ip-10-0-53-194 !INFO    | journal: Suppressed 64281 messages from /system.slice/scylla-server.service
2019-08-29T17:19:44+00:00  ip-10-0-53-194 !INFO    | journal: Suppressed 64357 messages from /system.slice/scylla-server.service
2019-08-29T17:20:14+00:00  ip-10-0-53-194 !INFO    | journal: Suppressed 64508 messages from /system.slice/scylla-server.service
2019-08-29T17:20:44+00:00  ip-10-0-53-194 !INFO    | journal: Suppressed 64434 messages from /system.slice/scylla-server.service
2019-08-29T17:21:14+00:00  ip-10-0-53-194 !INFO    | journal: Suppressed 64623 messages from /system.slice/scylla-server.service
2019-08-29T17:21:44+00:00  ip-10-0-53-194 !INFO    | journal: Suppressed 64433 messages from /system.slice/scylla-server.service
2019-08-29T17:22:14+00:00  ip-10-0-53-194 !INFO    | journal: Suppressed 64357 messages from /system.slice/scylla-server.service
2019-08-29T17:33:01+00:00  ip-10-0-53-194 !INFO    | journal: Suppressed 25370 messages from /system.slice/scylla-server.service
2019-08-29T17:33:31+00:00  ip-10-0-53-194 !INFO    | journal: Suppressed 36201 messages from /system.slice/scylla-server.service
2019-08-29T17:34:01+00:00  ip-10-0-53-194 !INFO    | journal: Suppressed 10590 messages from /system.slice/scylla-server.service
2019-08-29T17:34:31+00:00  ip-10-0-53-194 !INFO    | journal: Suppressed 10050 messages from /system.slice/scylla-server.service
2019-08-29T17:35:01+00:00  ip-10-0-53-194 !INFO    | journal: Suppressed 10291 messages from /system.slice/scylla-server.service
2019-08-29T14:05:04+00:00  ip-10-0-53-194 !INFO    | journal: Suppressed 32861 messages from /system.slice/scylla-server.service
2019-08-29T14:05:34+00:00  ip-10-0-53-194 !INFO    | journal: Suppressed 35482 messages from /system.slice/scylla-server.service
2019-08-29T17:39:01+00:00  ip-10-0-53-194 !INFO    | journal: Suppressed 18702 messages from /system.slice/scylla-server.service
2019-08-29T17:39:31+00:00  ip-10-0-53-194 !INFO    | journal: Suppressed 32669 messages from /system.slice/scylla-server.service
2019-08-29T17:40:01+00:00  ip-10-0-53-194 !INFO    | journal: Suppressed 33270 messages from /system.slice/scylla-server.service
2019-08-29T17:40:31+00:00  ip-10-0-53-194 !INFO    | journal: Suppressed 25191 messages from /system.slice/scylla-server.service
2019-08-29T17:41:02+00:00  ip-10-0-53-194 !INFO    | journal: Suppressed 11186 messages from /system.slice/scylla-server.service
2019-08-29T17:41:32+00:00  ip-10-0-53-194 !INFO    | journal: Suppressed 13518 messages from /system.slice/scylla-server.service
2019-08-29T17:42:02+00:00  ip-10-0-53-194 !INFO    | journal: Suppressed 14621 messages from /system.slice/scylla-server.service
```
The node's log is available on gs://scratch.scylladb.com/shlomib/large_partition_29_8_node_2_journal.txt

**Comment by bentsi** [comment] 2019-09-02 17:22
@bhalevy

**Comment by slivne** [comment] 2019-09-03 11:10
if there are metrics we can try to correlate the time of this errors with the available space on the disks

**Comment by ShlomiBalalis** [comment] 2019-09-05 12:33
There seems to be an issue with uploading the metrics, so we don't have them. I'm about to rerun the longevity with rc5, so if it'll occur again, I'll supply the metrics

**Comment by bhalevy** [comment] 2019-09-05 17:48
The problem looks like that:
```
2019-08-29T14:04:34+00:00  ip-10-0-53-194 !ERR     | rsyslogd: imjournal: fopen() failed for path: '/var/lib/rsyslog/imjournal.state.tmp': No space left on device [v8.24.0-34.el7 try http://www.rsyslog.com/e/2013 ]
```

The log suppression messages look related to a system event, not necessarily from the scylla process.

For example:
```
2019-08-29T13:04:03+00:00  ip-10-0-53-194 !INFO    | scylla: [shard 3] repair - Repair 1 out of 1 ranges, id=74, shard=3, keyspace=system_auth, table={roles, role_members}, range=(-9004196854989411669, -90038215
55020464128]
2019-08-29T13:04:05+00:00  ip-10-0-53-194 !NOTICE  | sudo:  centos : TTY=unknown ; PWD=/home/centos ; USER=root ; COMMAND=/bin/coredumpctl --no-pager --no-legend
2019-08-29T13:04:05+00:00  ip-10-0-53-194 !INFO    | sudo: pam_unix(sudo:session): session opened for user root by (uid=0)
2019-08-29T13:04:05+00:00  ip-10-0-53-194 !INFO    | sudo: pam_unix(sudo:session): session closed for user root
2019-08-29T13:04:06+00:00  ip-10-0-53-194 !INFO    | sshd[15721]: ssh_dispatch_run_fatal: Connection from 10.0.0.56 port 39774: Broken pipe [preauth]
2019-08-29T13:04:06+00:00  ip-10-0-53-194 !INFO    | sshd[15723]: ssh_dispatch_run_fatal: Connection from 10.0.0.56 port 39776: Broken pipe [preauth]
2019-08-29T13:04:06+00:00  ip-10-0-53-194 !INFO    | sshd[15724]: ssh_dispatch_run_fatal: Connection from 10.0.0.56 port 39778: Broken pipe [preauth]
2019-08-29T13:04:06+00:00  ip-10-0-53-194 !INFO    | sshd[15727]: ssh_dispatch_run_fatal: Connection from 10.0.0.56 port 39780: Broken pipe [preauth]
2019-08-29T13:04:06+00:00  ip-10-0-53-194 !INFO    | sshd[15728]: ssh_dispatch_run_fatal: Connection from 10.0.0.56 port 39782: Broken pipe [preauth]
2019-08-29T13:04:07+00:00  ip-10-0-53-194 !INFO    | sshd[15732]: ssh_dispatch_run_fatal: Connection from 10.0.0.56 port 39786: Broken pipe [preauth]
2019-08-29T13:04:07+00:00  ip-10-0-53-194 !INFO    | sshd[15731]: ssh_dispatch_run_fatal: Connection from 10.0.0.56 port 39784: Broken pipe [preauth]
2019-08-29T13:04:07+00:00  ip-10-0-53-194 !INFO    | sshd[15735]: ssh_dispatch_run_fatal: Connection from 10.0.0.56 port 39788: Broken pipe [preauth]
2019-08-29T13:04:08+00:00  ip-10-0-53-194 !INFO    | sshd[15737]: ssh_dispatch_run_fatal: Connection from 10.0.0.56 port 39790: Broken pipe [preauth]
2019-08-29T13:04:20+00:00  ip-10-0-53-194 !NOTICE  | sudo:  centos : TTY=unknown ; PWD=/home/centos ; USER=root ; COMMAND=/bin/coredumpctl --no-pager --no-legend
2019-08-29T13:04:20+00:00  ip-10-0-53-194 !INFO    | sudo: pam_unix(sudo:session): session opened for user root by (uid=0)
2019-08-29T13:04:20+00:00  ip-10-0-53-194 !INFO    | sudo: pam_unix(sudo:session): session closed for user root
2019-08-29T13:04:31+00:00  ip-10-0-53-194 !INFO    | journal: Suppressed 63054 messages from /system.slice/scylla-server.service
2019-08-29T13:04:31+00:00  ip-10-0-53-194 !INFO    | scylla: [shard 3] repair - repair 1732 on shard 3 stats: ranges_nr=1, sub_ranges_nr=2, round_nr=2, round_nr_fast_path_already_synced=2, round_nr_fast_path_same_combined_hashes=0, round_nr_slow_path=0, rpc_call_nr=20, tx_hashes_nr=0, rx_hashes_nr=0, duration=0.02 seconds, tx_row_nr=0, rx_row_nr=0, tx_row_bytes=0, rx_row_bytes=0, row_from_disk_bytes={{10.0.53.194, 0}, {10.0.69.40, 0}, {10.0.152.107, 0}}, row_from_disk_nr={{10.0.53.194, 0}, {10.0.69.40, 0}, {10.0.152.107, 0}}, row_from_disk_bytes_per_sec={{10.0.53.194, 0}, {10.0.69.40, 0}, {10.0.152.107, 0}} MiB/s, row_from_disk_rows_per_sec={{10.0.53.194, 0}, {10.0.69.40, 0}, {10.0.152.107, 0}} Rows/s, tx_row_nr_peer={}, rx_row_nr_peer={}

and several similar cases like this later on.

2019-08-29T17:41:50+00:00  ip-10-0-53-194 !NOTICE  | sudo:  centos : TTY=unknown ; PWD=/home/centos ; USER=root ; COMMAND=/bin/coredumpctl --no-pager --no-legend
2019-08-29T17:41:50+00:00  ip-10-0-53-194 !INFO    | sudo: pam_unix(sudo:session): session opened for user root by (uid=0)
2019-08-29T17:41:50+00:00  ip-10-0-53-194 !INFO    | sudo: pam_unix(sudo:session): session closed for user root
```
I think that the proximity to repair stats messages could be just an unrelated coincidence....

@bentsi are these real coredumps from some process?

**Comment by slivne** [comment] 2019-09-09 16:02
@bentsi / @ShlomiBalalis closing this we do not have enough to work on - if this reproduces please provide information and if possible allow access to the machines

**Closed by slivne** 2019-09-09 16:02 UTC
