### ISSUE TITLE
Unable to locate package scylla, on Ubuntu 14.04

### ISSUE THREAD

**Issue by aniketdumbare** [scylladb/scylla#1361] opened 2016-06-17 06:41 UTC
*Installation details*
Scylla version (or git commit hash): NA
Cluster size: NA
OS (RHEL/CentOS/Ubuntu/AWS AMI): Ubuntu 14.04

Issue:
$ sudo apt-get install scylla
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package scylla

**Comment by tzach** [comment] 2016-06-17 06:48
Hi @aniketdumbare 
Did you set the repo `/etc/apt/sources.list.d/scylla.list` as explained here: 
http://www.scylladb.com/download/#fndtn-deb ?

Try follow the instructions Ubuntu 14.04
http://www.scylladb.com/doc/getting-started-ubuntu/#install

**Comment by tzach** [comment] 2016-07-21 11:07
@aniketdumbare since we failed to reproduce, I'm closing this issue for now.
We can reopen if you or other can provide more data.

**Closed by tzach** 2016-07-21 11:07 UTC

**Comment by juanc5ibanez** [comment] 2016-07-24 04:53
Hi. I have jsut got the same error. On a Ubuntu 16.04 host using docker. Followed the instructions to add the repo but still no luck.

**Comment by tzach** [comment] 2016-07-24 06:34
@juanc5ibanez thanks for the report
Can you please paste the commands you are using?
In particular, make sure you are indeed using the Ubuntu 16 repo:
```
sudo wget -O /etc/apt/sources.list.d/scylla.list http://downloads.scylladb.com/deb/ubuntu/scylla-1.2-xenial.list
```

**Comment by juanc5ibanez** [comment] 2016-07-24 08:57
I have just executed 
sudo wget -O /etc/apt/sources.list.d/scylla.list http://downloads.scylladb.com/deb/ubuntu/scylla-1.2-xenial.list

And then I executed 

sudo apt-get update

And that generated the following error:
The repository 'http://s3.amazonaws.com/downloads.scylladb.com/deb/ubuntu xenial Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by juanc5ibanez** [comment] 2016-07-24 09:05
oops. you were right, I had to run the add repo and then apt-get update in order for it to install everything. then the install worked. thanks!!

**Comment by tzach** [comment] 2016-07-24 09:39
@juanc5ibanez thanks for the update!
keeping this issue close.

**Comment by jewelzqiu** [comment] 2016-09-05 03:42
@juanc5ibanez Hi, I am trying to install scylla 1.3 on ubuntu 16.04, but I got "does not have a Release file." error. Can you share the solution to this?
What do you mean about "run the add repo"?
Thank you!

**Comment by slmcat2002** [comment] 2016-10-20 01:24
Issue: Unable to locate package scylla
I had add the Scylla APT repository to  system, but it still not works.

root@ubuntu:/# 
root@ubuntu:/# sudo wget -O /etc/apt/sources.list.d/scylla.list http://downloads.scylladb.com/deb/ubuntu/scylla-1.3-trusty.list
--2016-10-20 09:07:20--  http://downloads.scylladb.com/deb/ubuntu/scylla-1.3-trusty.list
Resolving downloads.scylladb.com (downloads.scylladb.com)... 52.216.32.18
Connecting to downloads.scylladb.com (downloads.scylladb.com)|52.216.32.18|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 107 [application/octet-stream]
Saving to: ‘/etc/apt/sources.list.d/scylla.list’

100%[=====================================================================================================>] 107         --.-K/s   in 0s      

2016-10-20 09:07:20 (5.73 MB/s) - ‘/etc/apt/sources.list.d/scylla.list’ saved [107/107]

root@ubuntu:/# sudo apt-get update
Hit http://archive.ubuntukylin.com:10006 trusty InRelease
Hit http://archive.ubuntukylin.com:10006 trusty/main i386 Packages             
Ign http://repo.mongodb.org trusty/mongodb-org/3.2 InRelease                   
Hit http://archive.ubuntukylin.com:10006 trusty/main Translation-en            
Hit http://repo.mongodb.org trusty/mongodb-org/3.2 Release.gpg                 
Hit http://repo.mysql.com trusty InRelease                                     
Hit http://repo.mongodb.org trusty/mongodb-org/3.2 Release                     
Hit http://repo.mongodb.org trusty/mongodb-org/3.2/multiverse i386 Packages    
Hit http://security.ubuntu.com trusty-security InRelease                       
Ign http://us.archive.ubuntu.com trusty InRelease                              
Ign http://s3.amazonaws.com trusty InRelease                                   
Hit http://repo.mysql.com trusty/mysql-apt-config i386 Packages                
Hit http://security.ubuntu.com trusty-security/main Sources                    
Hit http://us.archive.ubuntu.com trusty-updates InRelease                      
Ign http://s3.amazonaws.com trusty Release.gpg                                 
Hit http://repo.mysql.com trusty/workbench-6.2 i386 Packages                   
Hit http://security.ubuntu.com trusty-security/restricted Sources              
Get:1 https://dl.bintray.com  InRelease                                        
Ign https://dl.bintray.com  InRelease                                          
Hit http://us.archive.ubuntu.com trusty-backports InRelease                    
Ign http://s3.amazonaws.com trusty Release                                     
Hit http://repo.mysql.com trusty/workbench-6.3 i386 Packages                   
Ign http://repo.mongodb.org trusty/mongodb-org/3.2/multiverse Translation-en_US
Hit https://dl.bintray.com  Release.gpg                                        
Hit http://security.ubuntu.com trusty-security/universe Sources                
Ign http://repo.mongodb.org trusty/mongodb-org/3.2/multiverse Translation-en   
Hit http://us.archive.ubuntu.com trusty Release.gpg                            
Hit http://security.ubuntu.com trusty-security/multiverse Sources              
Hit http://repo.mysql.com trusty/connector-python-2.0 i386 Packages            
Hit http://us.archive.ubuntu.com trusty-updates/main Sources                   
Hit http://security.ubuntu.com trusty-security/main i386 Packages              
Ign http://s3.amazonaws.com trusty/scylladb-1.3/multiverse amd64 Packages/DiffIndex
Hit http://repo.mysql.com trusty/connector-python-2.1 i386 Packages            
Hit http://us.archive.ubuntu.com trusty-updates/restricted Sources             
Hit http://security.ubuntu.com trusty-security/restricted i386 Packages        
Hit https://dl.bintray.com  Release                                            
Hit http://repo.mysql.com trusty/router-2.0 i386 Packages                      
Hit http://us.archive.ubuntu.com trusty-updates/universe Sources               
Hit http://security.ubuntu.com trusty-security/universe i386 Packages          
Hit http://us.archive.ubuntu.com trusty-updates/multiverse Sources             
Hit http://security.ubuntu.com trusty-security/multiverse i386 Packages        
Hit http://repo.mysql.com trusty/mysql-utilities-1.5 i386 Packages             
Hit http://us.archive.ubuntu.com trusty-updates/main i386 Packages             
Hit http://security.ubuntu.com trusty-security/main Translation-en             
Hit https://dl.bintray.com  Packages                                           
Hit http://repo.mysql.com trusty/mysql-tools i386 Packages                     
Hit http://us.archive.ubuntu.com trusty-updates/restricted i386 Packages       
Hit http://security.ubuntu.com trusty-security/multiverse Translation-en       
Hit http://security.ubuntu.com trusty-security/restricted Translation-en       
Hit http://us.archive.ubuntu.com trusty-updates/universe i386 Packages         
Hit http://security.ubuntu.com trusty-security/universe Translation-en         
Hit http://us.archive.ubuntu.com trusty-updates/multiverse i386 Packages       
Get:2 https://dl.bintray.com  Translation-en_US                                
Hit http://us.archive.ubuntu.com trusty-updates/main Translation-en            
Get:3 https://dl.bintray.com  Translation-en                                   
Hit http://us.archive.ubuntu.com trusty-updates/multiverse Translation-en      
Get:4 https://dl.bintray.com  Translation-en_US                                
Hit http://us.archive.ubuntu.com trusty-updates/restricted Translation-en      
Hit http://us.archive.ubuntu.com trusty-updates/universe Translation-en        
Get:5 https://dl.bintray.com  Translation-en                                   
Hit http://us.archive.ubuntu.com trusty-backports/main Sources                 
Get:6 https://dl.bintray.com  Translation-en_US                                
Hit http://us.archive.ubuntu.com trusty-backports/restricted Sources           
Get:7 https://dl.bintray.com  Translation-en                                   
Get:8 https://dl.bintray.com  Translation-en_US                        
Get:9 https://dl.bintray.com  Translation-en                              
Hit http://us.archive.ubuntu.com trusty-backports/universe Sources        
Get:10 https://dl.bintray.com  Translation-en_US                               
Ign https://dl.bintray.com  Translation-en_US                                  
Hit http://us.archive.ubuntu.com trusty-backports/multiverse Sources           
Get:11 https://dl.bintray.com  Translation-en                                  
Ign https://dl.bintray.com  Translation-en                                     
Hit http://us.archive.ubuntu.com trusty-backports/main i386 Packages           
Hit http://s3.amazonaws.com trusty/scylladb-1.3/multiverse amd64 Packages      
Hit http://us.archive.ubuntu.com trusty-backports/restricted i386 Packages     
Ign http://s3.amazonaws.com trusty/scylladb-1.3/multiverse Translation-en_US   
Hit http://us.archive.ubuntu.com trusty-backports/universe i386 Packages
Hit http://us.archive.ubuntu.com trusty-backports/multiverse i386 Packages     
Hit http://us.archive.ubuntu.com trusty-backports/main Translation-en          
Ign http://s3.amazonaws.com trusty/scylladb-1.3/multiverse Translation-en      
Hit http://us.archive.ubuntu.com trusty-backports/multiverse Translation-en    
Hit http://us.archive.ubuntu.com trusty-backports/restricted Translation-en    
Hit http://us.archive.ubuntu.com trusty-backports/universe Translation-en      
Hit http://us.archive.ubuntu.com trusty Release                                
Hit http://us.archive.ubuntu.com trusty/main Sources                           
Hit http://us.archive.ubuntu.com trusty/restricted Sources                     
Hit http://us.archive.ubuntu.com trusty/universe Sources                       
Hit http://us.archive.ubuntu.com trusty/multiverse Sources                     
Hit http://us.archive.ubuntu.com trusty/main i386 Packages        
Hit http://us.archive.ubuntu.com trusty/restricted i386 Packages  
Hit http://us.archive.ubuntu.com trusty/universe i386 Packages                 
Hit http://us.archive.ubuntu.com trusty/multiverse i386 Packages               
Hit http://us.archive.ubuntu.com trusty/main Translation-en                    
Hit http://us.archive.ubuntu.com trusty/multiverse Translation-en              
Hit http://us.archive.ubuntu.com trusty/restricted Translation-en              
Hit http://us.archive.ubuntu.com trusty/universe Translation-en                
Ign http://us.archive.ubuntu.com trusty/main Translation-en_US                 
Ign http://us.archive.ubuntu.com trusty/multiverse Translation-en_US           
Ign http://us.archive.ubuntu.com trusty/restricted Translation-en_US           
Ign http://us.archive.ubuntu.com trusty/universe Translation-en_US             
Ign http://repo.mysql.com trusty/connector-python-2.0 Translation-en_US        
Ign http://repo.mysql.com trusty/connector-python-2.0 Translation-en
Ign http://repo.mysql.com trusty/connector-python-2.1 Translation-en_US
Ign http://repo.mysql.com trusty/connector-python-2.1 Translation-en
Ign http://repo.mysql.com trusty/mysql-apt-config Translation-en_US
Ign http://repo.mysql.com trusty/mysql-apt-config Translation-en
Ign http://repo.mysql.com trusty/mysql-tools Translation-en_US
Ign http://repo.mysql.com trusty/mysql-tools Translation-en
Ign http://repo.mysql.com trusty/mysql-utilities-1.5 Translation-en_US
Ign http://repo.mysql.com trusty/mysql-utilities-1.5 Translation-en
Ign http://repo.mysql.com trusty/router-2.0 Translation-en_US
Ign http://repo.mysql.com trusty/router-2.0 Translation-en
Ign http://repo.mysql.com trusty/workbench-6.2 Translation-en_US
Ign http://repo.mysql.com trusty/workbench-6.2 Translation-en
Ign http://repo.mysql.com trusty/workbench-6.3 Translation-en_US
Ign http://repo.mysql.com trusty/workbench-6.3 Translation-en
Reading package lists... Done
root@ubuntu:/# sudo apt-get install scylla
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package scylla
root@ubuntu:/#

**Comment by locked** [comment] 2017-05-28 20:53
Hello,

I have the same error on Ubuntu 16.04, using the 'apt' command:

# wget -O /etc/apt/sources.list.d/scylla.list http://downloads.scylladb.com/deb/ubuntu/scylla-1.7-xenial.list
# apt update

I am getting:
E: The repository 'http://s3.amazonaws.com/downloads.scylladb.com/deb/ubuntu xenial Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

Using 'apt-get' works, but I think 'apt' should be supported ?

**Comment by jonathanleang** [comment] 2017-07-18 07:59
I did the following but got error too.

```
sudo wget -O /etc/apt/sources.list.d/scylla.list http://downloads.scylladb.com/deb/ubuntu/scylla-1.7-xenial.list
sudo apt-get update
sudo apt-get install scylla
```
```

Do you want to continue? [Y/n] 
Setting up scylla-kernel-conf (1.7.2-0.20170706.a24dcf1-0ubuntu1) ...
sysctl: cannot stat /proc/sys/kernel/sched_tunable_scaling: No such file or directory
sysctl: cannot stat /proc/sys/kernel/sched_min_granularity_ns: No such file or directory
sysctl: cannot stat /proc/sys/kernel/sched_wakeup_granularity_ns: No such file or directory
sysctl: cannot stat /proc/sys/kernel/sched_latency_ns: No such file or directory
sysctl: cannot stat /proc/sys/kernel/sched_autogroup_enabled: No such file or directory
sysctl: cannot stat /proc/sys/kernel/numa_balancing: No such file or directory
dpkg: error processing package scylla-kernel-conf (--configure):
 subprocess installed post-installation script returned error exit status 255
dpkg: dependency problems prevent configuration of scylla:
 scylla depends on scylla-kernel-conf; however:
  Package scylla-kernel-conf is not configured yet.

dpkg: error processing package scylla (--configure):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 scylla-kernel-conf
 scylla

```

**Comment by tzach** [comment] 2017-07-18 08:03
@jonathanleang what Ubuntu version are you running?
If its Ubuntu 14 Trusty, you are using the wrong (Ubuntu 16) repo

**Comment by avikivity** [comment] 2017-07-18 08:05
@tzach @jonathanleang I think this is #1990

**Comment by jonathanleang** [comment] 2017-07-18 09:26
@tzach @avikivity 
I am using 16.04.2 LTS (Xenial Xerus)
