### ISSUE TITLE
Rebuild & Repair  fail with Streaming error (internode encryption enabled)

### ISSUE THREAD

**Issue by roydahan** [scylladb/scylla#3787] opened 2018-09-27 12:39 UTC
*Installation details*
Scylla version (or git commit hash): 666.development-0.20180916.9d27045c7
Cluster size: 4
OS (RHEL/CentOS/Ubuntu/AWS AMI): AWS AMI (ami-0d29bac8c368c8985)

During Longevity 1TB with TLS encryption enabled, all nemesis that involve repair/rebuild are failing with the following error:
`server connection dropped: An unexpected TLS packet was received.`

The rebuild operation is retried several times, but keep failing with the same error.

relevant part of the log:
```
 [shard 0] stream_session - [Stream #bc01be20-c216-11e8-9710-000000000007] Start sending ks=keyspace_Deflate, cf=standard1, estimated_partitions=896, with new rpc streaming
 [shard 12] stream_session - [Stream #bc01be20-c216-11e8-9710-000000000007] Start sending ks=keyspace_Deflate, cf=standard1, estimated_partitions=3, with new rpc streaming
 [shard 4] stream_session - [Stream #bc01be20-c216-11e8-9710-000000000007] Start sending ks=keyspace_Deflate, cf=standard1, estimated_partitions=3, with new rpc streaming
 [shard 11] stream_session - [Stream #bc01be20-c216-11e8-9710-000000000007] Start sending ks=keyspace_Deflate, cf=standard1, estimated_partitions=3, with new rpc streaming
 [shard 2] stream_session - [Stream #bc01be20-c216-11e8-9710-000000000007] Start sending ks=keyspace_Deflate, cf=standard1, estimated_partitions=642, with new rpc streaming
 [shard 7] stream_session - [Stream #bc01be20-c216-11e8-9710-000000000007] Start sending ks=keyspace_Deflate, cf=standard1, estimated_partitions=4, with new rpc streaming
[shard 11] rpc - client 172.16.99.159: server connection dropped: An unexpected TLS packet was received.
 [shard 10] rpc - client 172.16.99.22: client stream connection dropped: connection is closed
 [shard 4] rpc - client 172.16.99.22: client stream connection dropped: connection is closed
[shard 2] rpc - client 172.16.99.159: server connection dropped: An unexpected TLS packet was received.
[shard 0] rpc - client 172.16.99.159: server connection dropped: An unexpected TLS packet was received.
 [shard 9] rpc - client 172.16.99.22: client stream connection dropped: connection is closed
[shard 12] rpc - client 172.16.99.159: server connection dropped: An unexpected TLS packet was received.
 [shard 8] rpc - client 172.16.99.22: client stream connection dropped: connection is closed
[shard 13] rpc - client 172.16.99.159: server connection dropped: An unexpected TLS packet was received.
[shard 0] rpc - client 172.16.99.159: server connection dropped: An unexpected TLS packet was received.
 [shard 2] rpc - client 172.16.99.22: client stream connection dropped: connection is closed
[shard 13] rpc - client 172.16.99.226: server connection dropped: An unexpected TLS packet was received.
[shard 0] rpc - client 172.16.99.159: server connection dropped: An unexpected TLS packet was received.
 [shard 6] rpc - client 172.16.99.22: client stream connection dropped: connection is closed

[shard 10] stream_session - [Stream #bc019710-c216-11e8-9710-000000000007] 
stream_transfer_task: Fail to send to 172.16.99.22:0: seastar::rpc::closed_error (connection is closed)

[shard 10] stream_session - [Stream #bc019710-c216-11e8-9710-000000000007] Failed to send: seastar::rpc::closed_error (connection is closed)

stream_session - [Stream #bc019710-c216-11e8-9710-000000000007] Streaming plan for Rebuild-keyspace_Deflate-index-0 failed, peers={172.16.99.159}, tx=0 KiB, 0.00 KiB/s, rx=0 KiB, 0.00 KiB/s
range_streamer - Rebuild with 172.16.99.159 for keyspace=keyspace_Deflate failed, took 0.174 seconds: streaming::stream_exception (Stream failed)

```

**Comment by asias** [comment] 2018-09-27 22:56
This looks like a TLS issue not streaming, no?

Btw, what is hydra?

**Comment by roydahan** [comment] 2018-09-30 09:30
if TLS, who should help? @gleb-cloudius?

Hydra is a docker container for SCT to help reproducing issues without installing all SCT dependencies.
See Bentsi's demo video.

**Comment by gleb-cloudius** [comment] 2018-09-30 11:06
@elcallio

**Comment by slivne** [comment] 2018-09-30 19:59
@roydahan Is it only rebuild and repair - if so can you provide the profile
that has those nemesis only.

@elcallio can you please try and look at this.

**Comment by roydahan** [comment] 2018-10-02 07:53
It’s basically all types of streaming, even bootstrap of new node.

**Comment by elcallio** [comment] 2018-10-02 13:36
Is TLS activated on all nodes? And using the correct ports? 
One reason for the error would be non-tls sockets talking to tls sockets. 

Another reason might be too many (re-)handshakes, since gnutls limits the number of renegotiations. Might indicate a broked network or something. 

Could also be handshake state machine being broken or gnutls version on the machines once again having changed the handshake rules. Which gnutls is on the machines? 

Is there some sort of local reproducer for this?

**Comment by roydahan** [comment] 2018-10-02 22:30
TLS is activated on all nodes using the correct ports.

You can try reproduce with SCT and the “hydra” command above.
I don’t know if it reproduces by dtest.

**Comment by elcallio** [comment] 2018-10-09 15:00
So this actually reproduces in a two-node local setup, on the first auth-streaming. Streaming creates a new RPC client (which according to printf is a TLS wrapper one). However, the first data send is the (unencryped, unwrapped) rpc magic header. Which would indicate that somehow, for this RPC connection, we're transferring without TLS wrapping. The receiver expects a nice TLS packet, but gets "SSTARRPC", which is not quite it. 

Of course, gossiper japping away every second does not make it easier to try to track down what is going on with the connections.

**Comment by elcallio** [comment] 2018-10-10 00:04
Took way to long to find, managed to stare myself blind and miss the rather obvious (once seen) problem.

The problem is in messaging service. Creating streaming sink does not respect the rpc clients underlying transport. It instead always creates a plain socket. Which in turn still connects to a tls server on the other side -> bamm, invalid packet. 

Patch is coming.

**Closed** 2018-10-10 15:53 UTC
Labels: bug, high

**Comment by roydahan** [comment] 2018-10-22 11:57
I think the issue wasn't ported to branch-3.0.
I don't see the commit there and I hit the issue on 3.0.rc0-0.20181016.202913406
