### ISSUE TITLE
Node properties are null in system.peers in some cases

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/scylla#4652] opened 2019-07-04 12:58 UTC
Scylla version: 3.1.0.rc2-0.20190630.acff367ea

I observed a discrepancy between gossip info in memory and in system.peers for one of the nodes:

```
$ nodetool gossipinfo

/10.0.250.129
  SCHEMA:ac26e779-ea83-3001-8dcb-1cd43291d467
```

```
$ cqlsh -e "select peer         , data_center , host_id , preferred_ip , rack , release_version , rpc_address , schema_version , supported_features  from system.peers where peer = '10.0.250.129'"

 peer         | data_center | host_id | preferred_ip | rack | release_version | rpc_address | schema_version | supported_features
--------------+-------------+---------+--------------+------+-----------------+-------------+----------------+--------------------
 10.0.250.129 |        null |    null |         null | null |            null |        null |           null |               null

(1 rows)
```

```
$ cqlsh -e "select peer, schema_version from system.peers"

 peer         | schema_version
--------------+--------------------------------------
   10.0.2.228 | ac26e779-ea83-3001-8dcb-1cd43291d467
  10.0.13.243 | ac26e779-ea83-3001-8dcb-1cd43291d467
  10.0.105.70 | ac26e779-ea83-3001-8dcb-1cd43291d467
 10.0.226.255 | ac26e779-ea83-3001-8dcb-1cd43291d467
 10.0.250.129 |                                 null
   10.0.85.71 | ac26e779-ea83-3001-8dcb-1cd43291d467
```

Not sure what conditions led to this. Other nodes have full info for 10.0.250.129.

**Comment by slivne** [comment] 2019-07-07 08:46
@roydahan can we add this to SCT to check nodetool gossipinfo / select from system.peers and detect this.

**Comment by roydahan** [comment] 2019-07-07 10:52
Yes, we can add it as a nemesis that occasionally run both and compare.

**Comment by slivne** [comment] 2019-07-07 11:04
@roydahan can we do it more aggressively - we need to find the bug .... I know we have nodetool status from time to time - can we add this two checks nodetool gossipinfo + select from system.peers

**Comment by roydahan** [comment] 2019-07-07 11:35
We have nodetool status before and every after nemesis or cluster layout operation.
We can do that.
We also can do it in a fixed interval if we want...

**Comment by slivne** [comment] 2019-07-08 07:36
@roydahan so lets do this change - I need this deployed so we can find the bug

**Comment by roydahan** [comment] 2019-07-08 11:35
@juliayakovlev is trying to reproduce by adding these queries everytime we run nodetool status in a longevity.

**Comment by slivne** [comment] 2019-07-15 15:38
@roydahan / @juliayakovlev any luck ?

**Comment by juliayakovlev** [comment] 2019-07-16 04:24
@slivne 
I ran the test for 4 days - the problem was not recreated.
Yesterday I started new job. This is the [monitor](http://34.237.245.208:3000/d/nW45vCSZk/scylla-per-server-metrics-nemesis-3-1?refresh=30s&orgId=1&from=now-24h&to=now&var-by=instance&var-cluster=&var-dc=All&var-node=All&var-shard=All&var-sct_tags=ClusterHealthValidatorEvent)

There is the new event "ClusterHealthValidatorEvent". This event report with 2 severities NORMAL (start/end of the validation, marked by pink color on the graphs) and CRITICAL. In case the problem will be detected, you will see ClusterHealthValidatorEvent event with CRITICAL severity (marked by red color  on the Dashboard).

**Comment by slivne** [comment] 2019-08-01 08:51
@juliayakovlev any luck ?

**Comment by juliayakovlev** [comment] 2019-08-01 10:10
@slivne  
I added this validation to the SCT. So it's run in every SCT test. 
In the tests that I checked, the problem is not recreated.
Also did some improvment (PR is not merged yet https://github.com/scylladb/scylla-cluster-tests/pull/1205)

**Comment by slivne** [comment] 2019-08-14 12:06
@juliayakovlev / @roydahan any update on this - if we are not hitting this anymore - lets close

**Comment by roydahan** [comment] 2019-08-14 19:26
I think we can close for now.

**Closed** 2019-08-18 20:17 UTC
Labels: bug, gossip, high

**Comment by bentsi** [comment] 2020-05-13 00:04
Happened to me:
Scylla version (or git commit hash):  `4.0.0-0.20200505.d95aa77b62` with build-id c9cf14d33523aca01a1ba502a91eb9d400de9c34 
Cluster size: 6 (multidc, 3 nodes in each region)
OS (RHEL/CentOS/Ubuntu/AWS AMI): `ami-0ad095d521c760c3f ami-09ae7080d6e842625` [eu-west-1 us-east-1 ]

Scenario: alternator _mult-dc_
Node `3.250.164.60` was decommissioned and new node was added instead. After that:
```
04:43:57  < t:2020-05-10 01:43:50,241 f:sct_events.py   l:886  c:sdcm.sct_events      p:INFO  > 2020-05-10 01:43:50.227: (ClusterHealthValidatorEvent Severity.ERROR): type=error name=NodeSchemaVersion node=alternator-3h-multidc-alternat-db-node-254e8b33-7 error=Found nulls in system.peers on the node 3.250.164.60: 
peer           | data_center             | host_id                              | rack | release_version | rpc_address    | schema_version                       | supported_features
----------------+-------------------------+--------------------------------------+------+-----------------+----------------+--------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
34.238.255.203 | us-eastscylla_node_east | 3d169e94-2b81-4108-87e5-3f6bedadddd7 |   1b |           3.0.8 | 34.238.255.203 | a4820aaa-f29d-34d0-820a-79280d3ce8fa | CDC,COMPUTED_COLUMNS,CORRECT_COUNTER_ORDER,CORRECT_NON_COMPOUND_RANGE_TOMBSTONES,CORRECT_STATIC_COMPACT_IN_MC,COUNTERS,DIGEST_INSENSITIVE_TO_EXPIRY,DIGEST_MULTIPARTITION_READ,HINTED_HANDOFF_SEPARATE_CONNECTION,INDEXES,LARGE_PARTITIONS,LA_SSTABLE_FORMAT,LWT,MATERIALIZED_VIEWS,MC_SSTABLE_FORMAT,NONFROZEN_UDTS,PER_TABLE_PARTITIONERS,RANGE_TOMBSTONES,ROLES,ROW_LEVEL_REPAIR,SCHEMA_TABLES_V3,STREAM_WITH_RPC_STREAM,TRUNCATION_TABLE,UNBOUNDED_RANGE_TOMBSTONES,VIEW_VIRTUAL_COLUMNS,WRITE_FAILURE_REPLY,XXHASH
3.250.164.60 |                    null |                                 null | null |            null |           null |                                 null |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    null
54.84.32.156 | us-eastscylla_node_east | dda91827-9aee-476f-b361-184d101a6a94 |   1b |           3.0.8 |   54.84.32.156 | a4820aaa-f29d-34d0-820a-79280d3ce8fa | CDC,COMPUTED_COLUMNS,CORRECT_COUNTER_ORDER,CORRECT_NON_COMPOUND_RANGE_TOMBSTONES,CORRECT_STATIC_COMPACT_IN_MC,COUNTERS,DIGEST_INSENSITIVE_TO_EXPIRY,DIGEST_MULTIPARTITION_READ,HINTED_HANDOFF_SEPARATE_CONNECTION,INDEXES,LARGE_PARTITIONS,LA_SSTABLE_FORMAT,LWT,MATERIALIZED_VIEWS,MC_SSTABLE_FORMAT,NONFROZEN_UDTS,PER_TABLE_PARTITIONERS,RANGE_TOMBSTONES,ROLES,ROW_LEVEL_REPAIR,SCHEMA_TABLES_V3,STREAM_WITH_RPC_STREAM,TRUNCATION_TABLE,UNBOUNDED_RANGE_TOMBSTONES,VIEW_VIRTUAL_COLUMNS,WRITE_FAILURE_REPLY,XXHASH
52.214.126.130 | eu-westscylla_node_west | c772f640-082c-439d-a4b3-fb5117c2f2b3 |   1a |           3.0.8 | 52.214.126.130 | a4820aaa-f29d-34d0-820a-79280d3ce8fa | CDC,COMPUTED_COLUMNS,CORRECT_COUNTER_ORDER,CORRECT_NON_COMPOUND_RANGE_TOMBSTONES,CORRECT_STATIC_COMPACT_IN_MC,COUNTERS,DIGEST_INSENSITIVE_TO_EXPIRY,DIGEST_MULTIPARTITION_READ,HINTED_HANDOFF_SEPARATE_CONNECTION,INDEXES,LARGE_PARTITIONS,LA_SSTABLE_FORMAT,LWT,MATERIALIZED_VIEWS,MC_SSTABLE_FORMAT,NONFROZEN_UDTS,PER_TABLE_PARTITIONERS,RANGE_TOMBSTONES,ROLES,ROW_LEVEL_REPAIR,SCHEMA_TABLES_V3,STREAM_WITH_RPC_STREAM,TRUNCATION_TABLE,UNBOUNDED_RANGE_TOMBSTONES,VIEW_VIRTUAL_COLUMNS,WRITE_FAILURE_REPLY,XXHASH
3.87.190.12 | us-eastscylla_node_east | b247e656-b472-4c32-95b9-8f50f3e9cb11 |   1b |           3.0.8 |    3.87.190.12 | a4820aaa-f29d-34d0-820a-79280d3ce8fa | CDC,COMPUTED_COLUMNS,CORRECT_COUNTER_ORDER,CORRECT_NON_COMPOUND_RANGE_TOMBSTONES,CORRECT_STATIC_COMPACT_IN_MC,COUNTERS,DIGEST_INSENSITIVE_TO_EXPIRY,DIGEST_MULTIPARTITION_READ,HINTED_HANDOFF_SEPARATE_CONNECTION,INDEXES,LARGE_PARTITIONS,LA_SSTABLE_FORMAT,LWT,MATERIALIZED_VIEWS,MC_SSTABLE_FORMAT,NONFROZEN_UDTS,PER_TABLE_PARTITIONERS,RANGE_TOMBSTONES,ROLES,ROW_LEVEL_REPAIR,SCHEMA_TABLES_V3,STREAM_WITH_RPC_STREAM,TRUNCATION_TABLE,UNBOUNDED_RANGE_TOMBSTONES,VIEW_VIRTUAL_COLUMNS,WRITE_FAILURE_REPLY,XXHASH
54.75.85.211 | eu-westscylla_node_west | c29557d4-c73d-4948-ba38-efb6b41e0fa7 |   1a |           3.0.8 |   54.75.85.211 | a4820aaa-f29d-34d0-820a-79280d3ce8fa | CDC,COMPUTED_COLUMNS,CORRECT_COUNTER_ORDER,CORRECT_NON_COMPOUND_RANGE_TOMBSTONES,CORRECT_STATIC_COMPACT_IN_MC,COUNTERS,DIGEST_INSENSITIVE_TO_EXPIRY,DIGEST_MULTIPARTITION_READ,HINTED_HANDOFF_SEPARATE_CONNECTION,INDEXES,LARGE_PARTITIONS,LA_SSTABLE_FORMAT,LWT,MATERIALIZED_VIEWS,MC_SSTABLE_FORMAT,NONFROZEN_UDTS,PER_TABLE_PARTITIONERS,RANGE_TOMBSTONES,ROLES,ROW_LEVEL_REPAIR,SCHEMA_TABLES_V3,STREAM_WITH_RPC_STREAM,TRUNCATION_TABLE,UNBOUNDED_RANGE_TOMBSTONES,VIEW_VIRTUAL_COLUMNS,WRITE_FAILURE_REPLY,XXHASH

(6 rows)

```

Db logs: https://cloudius-jenkins-test.s3.amazonaws.com/254e8b33-ae59-4364-8370-837b56933e72/20200510_033103/db-cluster-254e8b33.zip
Job: https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/bentsi-staging/job/bentsi-alternator-3h-multidc/11/consoleFull
