### ISSUE TITLE
Stalls in memory-constrained i3.xlarge instance

### ISSUE THREAD

**Issue by veramine** [scylladb/scylla#3321] opened 2018-03-26 22:04 UTC
*Installation details*
Scylla version (or git commit hash):  2.1.0-0.20180216.58b90ceee
Cluster size: 1
OS (RHEL/CentOS/Ubuntu/AWS AMI): Official CentOS AMI (ami-9509d3ed)

*Hardware details (for performance issues)*          
Platform/Hardware:  AWS i3.xlarge
Disks: 1 x 0.95TB NVMe SSD 

We have been running Scylla 2.1 on an i3.xlarge instance with a steady load of 1K-8K requests per second.  Our schema has ~70 materialized views and our human-facing interfaces fetches most rows from the views.  Query times are very good.  Latency is very good. Throughput is very good.  System load is usually under 50% and rarely above 75% according to the grafana monitoring dashboard.  Everything has been great after we sorted through some initial troubles with materialized views prior to upgrading to 2.1.  

The only problem we have now are periodic stalls.  Every day, dozens of inserts fail due to reactor stalls.  Our data processing app uses gocql with SimpleRetryPolicy{NumRetries: 2} and we still have lots of timeouts and failed inserts.  We had been using too-large partitions (5+ GB sometimes) but most of those are gone now as we have been refactoring our schema.  Reducing the partition sizes seems to have helped but we still have a bunch of stalls.  Today I ran the @glommer scylla_extract_traces.py script to build a list.  

After reviewing some of the backtraces, I suspect that some of these are the result of running in a memory constrained environment.  i3.xlarge comes with 30.5 GB and we have further reduced the memory available to scylla by adding --reserve-memory 6G to the command line arguments.  I arrived at this conclusion after seeing std::function<seastar::memory::reclaiming_result ()>::operator()() in over half the traces.  

I've attached a file listing all the backtraces.  If any stand out as particularly interesting, please let me know and I can do further research into the state of the instance at the point in time when we saw that stall to let you know what else was in the journalctl log at the same time.  Or if there is any other way to support your investigation into stalls, please let me know.  Thank you!

Jonathan
[traces1.txt](https://github.com/scylladb/scylla/files/1849688/traces1.txt)

**Comment by tgrabiec** [comment] 2018-03-27 08:37
The stalls involving `~cache_entry` are probably caused by https://github.com/scylladb/scylla/issues/2576, which fixed in master (will land in 2.2).

**Comment by veramine** [comment] 2018-03-27 15:39
Awesome, thanks!  That would wipe out well over half these stalls.  We will eagerly try out any RC's as soon as they are available.  Thanks Tomasz!

**Closed** 2018-04-08 10:30 UTC
Labels: fixed, latency
