### ISSUE TITLE
multishard_streaming_reader hangs in repair

### ISSUE THREAD

**Issue by asias** [scylladb/scylla#4050] opened 2019-01-04 07:09 UTC
Start 2 nodes, 1 with --smp 2, 1 with --smp3
Insert some data: cassandra-stress write no-warmup n=1000 cl=ONE -schema 'replication(factor=2)' keyspace=myks2 -pop seq=10000000..20000000 -rate threads=100 -node 127.0.0.1

Repair node1
Node2 hangs on the make_multishard_streaming_reader.
Press Ctrl-C on node2,  backtrace was seen 
(Attached: [node2.backtrace.txt](https://github.com/scylladb/scylla/files/2726214/node2.backtrace.txt))

```
$ cat node2.log.txt |grep STARTS|wc -l
321
$ cat node2.log.txt |grep ENDS|wc -l                                                                                                                                                        
289
```
```
  0     future<std::list<repair_row>>
  1     read_rows_from_disk(size_t cur_size) {
  2         return do_with(cur_size, std::list<repair_row>(), [this] (size_t& cur_size, std::list<repair_row>& cur_rows) {
  3             return repeat([this, &cur_size, &cur_rows] () mutable {
  4                 if (cur_size >= _max_row_buf_size) {
  5                     return make_ready_future<stop_iteration>(stop_iteration::yes);
  6                 }
  7                 auto id = utils::make_random_uuid();
  8                 rlogger.info("READER_STARTS={}, cur_size={}", id, cur_size);
  9                 return _repair_reader.read_mutation_fragment().then([this, id, &cur_size, &cur_rows] (mutation_fragment_opt mfopt) mutable {
 10                     rlogger.info("READER_ENDS={}, cur_size={}", id, cur_size);
 11                     return handle_mutation_fragment(std::move(mfopt), cur_size, cur_rows);
 12                 });
 13             }).then([&cur_rows] () mutable {
 14                 return std::move(cur_rows);
 15             });
 16         });
 17     }

```

**Comment by slivne** [comment] 2019-01-04 22:44
@asias does this reproduce on 3.0 ?

**Comment by slivne** [comment] 2019-01-06 10:03
@asias  
I am not able to reproduce this on 3.0 ... I am marking this as 3.1 
please also double check me ...

**Comment by denesb** [comment] 2019-01-07 07:09
I could reproduce only with `experimental = true`.

**Comment by asias** [comment] 2019-01-07 07:13
On Mon, Jan 7, 2019 at 3:09 PM Botond Dénes <notifications@github.com>
wrote:

> I could reproduce only with experimental = true.
>
>
> Does --enable-sstables-mc-format matter?

I could see the hang with dtest which does not turn on experimental.

-- 
Asias

**Comment by denesb** [comment] 2019-01-07 07:56
So far I have tried the following combinations:
```
Configuration                                    | Reproduces                                                                                                                                                                                             
-------------------------------------------------+--------------------                                                                                                                                                                                    
- (default master install)                       | No                                                                                                                                                                                                     
experimental=true                                | Yes                                                                                                                                                                                                    
experimental=true, --enable-sstables-mc-format 0 | No                                                                                                                                                                                                     
--enable-sstables-mc-format 1                    | No 
```
Where omitted, options have their default value. Looks like some experimental stuff is causing the problems. But according to @asias `experimental = false` reproduces as well for him, so maybe `experimental=true` just makes it more likely.

**Comment by avikivity** [comment] 2019-01-07 08:30
experimental=true just makes it possible to use experimental features, it doesn't do anything by itself.

**Comment by denesb** [comment] 2019-01-07 08:57
Yes, I know, I thought that there is some interference with some experimental feature. But it looks like this is not the case, it just doesn't always reproduce. When it doesn't reproduce, I have to wipe and rewrite all my data to have a chance of reproducing. Running repair over-and-over on the same data doesn't help.

**Comment by denesb** [comment] 2019-01-24 10:49
Just for the record, to reproduce this (according to my experience anyway), one has to run the repair *on* the `-c2` node, not on the `-c3` node.

**Closed** 2019-02-12 20:13 UTC
Labels: bug, showstopper
