### ISSUE TITLE
Performance degradation (4.3.0 -> 4.3.1) and kernel perf degradation on GCE CentOS7

### ISSUE THREAD

**Issue by amoskong** [scylladb/scylla#8244] opened 2021-03-10 04:04 UTC
*Installation details*
Scylla version (or git commit hash): 
- 4.3.0-0.20210202.a7a979b79
- 4.3.1-0.20210210.46650adcd
- 4.3.2-0.20210301.5cdc1fa66

Cluster size: 4 
OS (RHEL/CentOS/Ubuntu/AWS AMI): CentOS7, CentOS8

### Summary
Performance degradation between 4.3.0 and 4.3.1
- it can be verified on upgrade jobs of CentOS7 and CentOS8

The kernel update on (GCE) CentOS7 also introduced performance degradation.
- 3.10.0-1160.11.1.el7.x86_64 to 3.10.0-1160.15.2.el7.x86_64

Currently we can only see the upgrade job fail of timeout (250 mins)
on CentOS7, because of the overlay of two degradations.The kernel degradation effect is bigger than the scylla itself.

Test time of CentOS8 upgrade also increased but didn't reach the timeout (250 mins)

### Test jobs

https://jenkins.scylladb.com/job/scylla-4.3/job/Reproducers/job/rolling-upgrade-centos7-test-clone/5/
- test id: 003e78b7-36fe-4284-a1c9-6a710a9c3543
- using old kernel (3.10.0-1160.11.1.el7.x86_64), src: 4.3.2

https://jenkins.scylladb.com/job/scylla-4.4/job/Reproducers/job/rolling-upgrade-centos7-test-clone-4.3.0/1
- test id: 2adba33f-6411-49d5-ac79-20ea4ca5513e
- using new kernel, src: 4.3.0- Job Failed for timeout (250 mins)

https://jenkins.scylladb.com/job/scylla-4.4/job/Reproducers/job/rolling-upgrade-centos7-test-clone-4.3.0-old-kernel/1
- test id: 34c94369-63ad-4824-91f2-6fba7e03c3d5
- using old kernel, src: 4.3.0

### Test time in different stages of upgrade test

Cluster init:
26: 45 mins
25: 46 mins
24: 46 mins
23: 45 mins
17: 45 mins (passed )
old-kernel-3.3.2: 43mins
4.3.0: 44 mins
old-kernel-4.3.0: 45 mins
CentOS8-Job#23: 39 mins
CentOS8-Job#22: 36mins

Prepare (after cluster init -> start Step1)
27: 47 mins
25: 49 mins
23: 50 mins
22: 48 mins (timeout) (4.3.1-0.20210210.46650adcd, 3.10.0-1160.15.2)
21: 39 mins (last passed) (old kernel, 4.3.0)
17: 28 mins (passed) (old kernel, 4.3.0)
old-kernel-4.3.2: 39mins
4.3.0: 47mins
old-kernel-4.3.0: 41 mins
CentOS8-Job#23: 37mins
CentOS8-Job#22: 36mins
CentOS8-Job#19-4.3.0: 33 mins

- Start entries cs in background -> start complex
27: 7 mins
23: 7 mins
21: 4 mins (last passed)
17: 4 mins (passed)
old-kernel-4.3.2: 7 mins
4.3.0: 7mins
old-kernel-4.3.0: 6 mins
CentOS8-Job#23: 6 mins
CentOS8-Job#22: 6 mins
CentOS8-Job#19-4.3.0: 4 mins

- complex
23: 20 mins
27: 18 mins
21: 15 mins (last passed)
17: 14 mins (passed)
old-kernel-4.3.2: 13 mins
4.3.0: 18 mins
old-kernel-4.3.0: 13 mins
CentOS8-Job#23: 13 mins
CentOS8-Job#22: 14 mins
CentOS8-Job#19-4.3.0: 11 mins

Step 4: 22mins, +11 mins 15mins
27: 33 mins
25: 25 mins
21: 21 mins (last passed)
17: 22 mins (passed)
old-kernel-4.3.2: 18 mins
4.3.0: 26 mins
old-kernel-4.3.0: 18 mins
CentOS8-Job#23: 13 mins
CentOS8-Job#22: 10 mins
CentOS8-Job#19-4.3.0: 12 mins

/Cc @roydahan @slivne

**Comment by roydahan** [comment] 2021-03-10 13:20
@amoskong this is not clear enough and cannot be used by anyone.
No one knows what the steps are exactly, what is step4, what is running there?
We need scylla metrics, not times.
Also, cluster init step, we don't know what affect it, is it scylla or general issue in GCP.
I suggest to concentrate on 2 things:
1. prepare stage (100% write) - Do we see a degradation? Is it due to the kernel change or due to scylla?
These tests are using the stock CentOS 7 & 8 provided by GCP, we don't control their kernel versions, right?

2. Verify stage (100% read) - same as above.

From running the performance regression test on 4.3.1 I see an 8% degradation on read.
I ran it again to make sure the results are consistent.

**Comment by amoskong** [comment] 2021-03-11 04:56
> @amoskong this is not clear enough and cannot be used by anyone.
> No one knows what the steps are exactly, what is step4, what is running there?

The Summary part is clean if someone don't know the detail of upgrade tests.

I can but I could not provide too much detail in the first comment (description).
I reduced many test result (time) and try show the significant factors, problems.

Cluster init: Job start ==> monitor is ready.
Prepare: monitor is ready ==> Step1 start
Step4: Step4 start ==> Step 5 start

In upgraded we have many kinds of operations mixed together, it's not just simple read/write workload.
In Step4 we have a background read (60mins) workload, and the entire_write workload might finish early (before Step4 starts)

> We need scylla metrics, not times.

> Also, cluster init step, we don't know what affect it, is it scylla or general issue in GCP.

The scylla version change and kernel version change didn't effect the cluster init time.

> I suggest to concentrate on 2 things:
> 
> 1. prepare stage (100% write) - Do we see a degradation? Is it due to the kernel change or due to scylla?

Check the summary.

>    These tests are using the stock CentOS 7 & 8 provided by GCP, we don't control their kernel versions, right?

We didn't control the kernel version, but I run some tests with my private branch to control the src version and kernel version.

> 2. Verify stage (100% read) - same as above.
> 
> From running the performance regression test on 4.3.1 I see an 8% degradation on read.
> I ran it again to make sure the results are consistent.

**Comment by roydahan** [comment] 2021-03-11 11:52
From looking at the perf regression tests on AWS where we use our AMI, it doesn't look like there is any regression between 4.3.0 to 4.3.1.
So, if the kernel we get in GCE is to blame, we need to measure it by perf tests and pinpoint the kernel patch that causes it.

**Comment by amoskong** [comment] 2021-04-06 14:55
> From looking at the perf regression tests on AWS where we use our AMI, it doesn't look like there is any regression between 4.3.0 to 4.3.1.
> So, if the kernel we get in GCE is to blame, we need to measure it by perf tests and pinpoint the kernel patch that causes it.

Which existing perf test (read/write/mixed) can be used? which step / stage of upgrade do we want to test?

**Comment by roydahan** [comment] 2021-04-07 20:21
test_write, test_read, test_mixed.

**Comment by roydahan** [comment] 2021-04-26 16:21
Closing this issue as I think the issue was temporary.

**Closed by roydahan** 2021-04-26 16:21 UTC
