### ISSUE TITLE
atomic_cell::make_live stalls 117ms

### ISSUE THREAD

**Issue by asias** [scylladb/scylla#8898] opened 2021-06-22 01:19 UTC
scylla:

846f0bd16e4958c88ec3a2f8c5bbc2a49b0eb997

binary:
http://downloads.scylladb.com/unstable/scylla/master/relocatable/2021-06-13T17:47:22Z/

job:
https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/RBNO/job/repair-based-operation/job/longevity-100gb-4h-ReplaceNode-test/11/

decode:

```
   1 longevity-100gb-4h-rbno-db-node-9604c43b-1/messages.log:2021-06-17T00:31:48+00:00  longevity-100gb-4h-rbno-db-node-9604c43b-1 !INFO    | scylla[18155]: Reactor stalled for 117 ms on shard 7. Backtrace:
   2 [Backtrace #0]
   3 void seastar::backtrace<seastar::backtrace_buffer::append_backtrace_oneline()::{lambda(seastar::frame)#1}>(seastar::backtrace_buffer::append_backtrace_oneline()::{lambda(seastar::frame)#1}&&) at ./build/release/seastar/./seast
   4  (inlined by) seastar::backtrace_buffer::append_backtrace_oneline() at ./build/release/seastar/./seastar/src/core/reactor.cc:768
   5  (inlined by) seastar::print_with_backtrace(seastar::backtrace_buffer&, bool) at ./build/release/seastar/./seastar/src/core/reactor.cc:787
   6 seastar::internal::cpu_stall_detector::generate_trace() at ./build/release/seastar/./seastar/src/core/reactor.cc:1219
   7 seastar::internal::cpu_stall_detector::maybe_report() at ./build/release/seastar/./seastar/src/core/reactor.cc:1100
   8  (inlined by) seastar::internal::cpu_stall_detector::on_signal() at ./build/release/seastar/./seastar/src/core/reactor.cc:1114
   9  (inlined by) seastar::reactor::block_notifier(int) at ./build/release/seastar/./seastar/src/core/reactor.cc:1202
  10 ?? ??:0
  11 logalloc::region_impl::object_descriptor::encode(char*&, unsigned long) const at ./utils/logalloc.cc:1186
  12  (inlined by) logalloc::region_impl::alloc_small(logalloc::region_impl::object_descriptor const&, unsigned int, unsigned long) at ./utils/logalloc.cc:1295
  13 logalloc::region_impl::alloc(migrate_fn_type const*, unsigned long, unsigned long) at ./utils/logalloc.cc:1517
  14 void* allocation_strategy::alloc<blob_storage>(unsigned long) at ././utils/allocation_strategy.hh:147
  15  (inlined by) managed_bytes at ././utils/managed_bytes.hh:153
  16  (inlined by) managed_bytes atomic_cell_type::make_live<ser::buffer_view<bytes_ostream::fragment_iterator> >(long, ser::buffer_view<bytes_ostream::fragment_iterator> const&) at ././atomic_cell.hh:167
  17 atomic_cell::make_live(abstract_type const&, long, ser::buffer_view<bytes_ostream::fragment_iterator>, seastar::bool_class<atomic_cell::collection_member_tag>) at ./atomic_cell.cc:40
  18 operator() at ./mutation_partition_view.cc:71
  19  (inlined by) _ZN5boost6detail7variant14invoke_visitorIKZN12_GLOBAL__N_116read_atomic_cellERK13abstract_typeNS_7variantIN3ser14live_cell_viewEJNS8_18expiring_cell_viewENS8_14dead_cell_viewENS8_17counter_cell_viewENS8_20unknown
  20  (inlined by) boost::detail::variant::invoke_visitor<(anonymous namespace)::read_atomic_cell(abstract_type const&, boost::variant<ser::live_cell_view, ser::expiring_cell_view, ser::dead_cell_view, ser::counter_cell_view, ser::
  21  (inlined by) boost::detail::variant::invoke_visitor<(anonymous namespace)::read_atomic_cell(abstract_type const&, boost::variant<ser::live_cell_view, ser::expiring_cell_view, ser::dead_cell_view, ser::counter_cell_view, ser::
  22  (inlined by) boost::detail::variant::invoke_visitor<(anonymous namespace)::read_atomic_cell(abstract_type const&, boost::variant<ser::live_cell_view, ser::expiring_cell_view, ser::dead_cell_view, ser::counter_cell_view, ser::
  23  (inlined by) boost::detail::variant::invoke_visitor<(anonymous namespace)::read_atomic_cell(abstract_type const&, boost::variant<ser::live_cell_view, ser::expiring_cell_view, ser::dead_cell_view, ser::counter_cell_view, ser::
  24  (inlined by) boost::detail::variant::invoke_visitor<(anonymous namespace)::read_atomic_cell(abstract_type const&, boost::variant<ser::live_cell_view, ser::expiring_cell_view, ser::dead_cell_view, ser::counter_cell_view, ser::
  25  (inlined by) (anonymous namespace)::read_atomic_cell(abstract_type const&, boost::variant<ser::live_cell_view, ser::expiring_cell_view, ser::dead_cell_view, ser::counter_cell_view, ser::unknown_variant_type>, seastar::bool_cl
  26 (anonymous namespace)::read_atomic_cell(abstract_type const&, boost::variant<ser::live_cell_view, ser::expiring_cell_view, ser::dead_cell_view, ser::counter_cell_view, ser::unknown_variant_type>, seastar::bool_class<atomic_cel
  27  (inlined by) (anonymous namespace)::read_atomic_cell(abstract_type const&, boost::variant<ser::live_cell_view, ser::expiring_cell_view, ser::dead_cell_view, ser::counter_cell_view, ser::unknown_variant_type>, seastar::bool_cl
  28  (inlined by) operator() at ./mutation_partition_view.cc:162
  29  (inlined by) _ZN5boost6detail7variant14invoke_visitorIKZN12_GLOBAL__N_118read_and_visit_rowIZNK23mutation_partition_view9do_acceptI17partition_builderEEvRK14column_mappingRT_E12cell_visitorEEvN3ser8row_viewESA_11column_kindOS
  30  (inlined by) _ZN5boost6detail7variant27visitation_impl_invoke_implINS1_14invoke_visitorIKZN12_GLOBAL__N_118read_and_visit_rowIZNK23mutation_partition_view9do_acceptI17partition_builderEEvRK14column_mappingRT_E12cell_visitorEE
  31  (inlined by) _ZN5boost6detail7variant22visitation_impl_invokeINS1_14invoke_visitorIKZN12_GLOBAL__N_118read_and_visit_rowIZNK23mutation_partition_view9do_acceptI17partition_builderEEvRK14column_mappingRT_E12cell_visitorEEvN3se
  32  (inlined by) boost::detail::variant::invoke_visitor<(anonymous namespace)::read_and_visit_row<mutation_partition_view::do_accept<partition_builder>(column_mapping const&, partition_builder&) const::cell_visitor>(ser::row_view
  33  (inlined by) _ZN5boost7variantINS0_IN3ser14live_cell_viewEJNS1_18expiring_cell_viewENS1_14dead_cell_viewENS1_17counter_cell_viewENS1_20unknown_variant_typeEEEEJNS1_20collection_cell_viewES6_EE27internal_apply_visitor_implINS_
  34  (inlined by) _ZN5boost7variantINS0_IN3ser14live_cell_viewEJNS1_18expiring_cell_viewENS1_14dead_cell_viewENS1_17counter_cell_viewENS1_20unknown_variant_typeEEEEJNS1_20collection_cell_viewES6_EE22internal_apply_visitorINS_6deta
  35  (inlined by) _ZNR5boost7variantINS0_IN3ser14live_cell_viewEJNS1_18expiring_cell_viewENS1_14dead_cell_viewENS1_17counter_cell_viewENS1_20unknown_variant_typeEEEEJNS1_20collection_cell_viewES6_EE13apply_visitorIKZN12_GLOBAL__N_
  36  (inlined by) _ZN5boost13apply_visitorIZN12_GLOBAL__N_118read_and_visit_rowIZNK23mutation_partition_view9do_acceptI17partition_builderEEvRK14column_mappingRT_E12cell_visitorEEvN3ser8row_viewES8_11column_kindOS9_E33atomic_cell_
  37  (inlined by) void (anonymous namespace)::read_and_visit_row<mutation_partition_view::do_accept<partition_builder>(column_mapping const&, partition_builder&) const::cell_visitor>(ser::row_view, column_mapping const&, column_ki
  38  (inlined by) void mutation_partition_view::do_accept<partition_builder>(column_mapping const&, partition_builder&) const at ./mutation_partition_view.cc:248
  39 operator() at ./memtable.cc:754
  40  (inlined by) decltype(auto) logalloc::allocating_section::with_reclaiming_disabled<memtable::apply(frozen_mutation const&, seastar::lw_shared_ptr<schema const> const&, db::rp_handle&&)::$_8::operator()() const::{lambda()#1}&>
  41  (inlined by) operator() at ././utils/logalloc.hh:775
  42  (inlined by) decltype(auto) logalloc::allocating_section::with_reserve<logalloc::allocating_section::operator()<memtable::apply(frozen_mutation const&, seastar::lw_shared_ptr<schema const> const&, db::rp_handle&&)::$_8::opera
  43  (inlined by) decltype(auto) logalloc::allocating_section::operator()<memtable::apply(frozen_mutation const&, seastar::lw_shared_ptr<schema const> const&, db::rp_handle&&)::$_8::operator()() const::{lambda()#1}>(logalloc::regi
  44  (inlined by) operator() at ./memtable.cc:750
  45  (inlined by) decltype(auto) with_allocator<memtable::apply(frozen_mutation const&, seastar::lw_shared_ptr<schema const> const&, db::rp_handle&&)::$_8>(allocation_strategy&, memtable::apply(frozen_mutation const&, seastar::lw_
  46  (inlined by) memtable::apply(frozen_mutation const&, seastar::lw_shared_ptr<schema const> const&, db::rp_handle&&) at ./memtable.cc:749
  47 void table::do_apply<frozen_mutation const&, seastar::lw_shared_ptr<schema const> const&>(db::rp_handle&&, frozen_mutation const&, seastar::lw_shared_ptr<schema const> const&) at ./table.cc:1861
  48  (inlined by) table::apply(frozen_mutation const&, seastar::lw_shared_ptr<schema const> const&, db::rp_handle&&) at ./table.cc:1880
  49 operator() at ./database.cc:1742

```

**Comment by avikivity** [comment] 2021-06-23 06:52
object_descriptor::encode, see #8828

**Comment by avikivity** [comment] 2021-06-27 10:02
Closing as duplicate of #8828.

**Closed by avikivity** 2021-06-27 10:02 UTC
Labels: latency
