### ISSUE TITLE
Scylla refused to boot in case the DB file is not found

### ISSUE THREAD

**Issue by juliayakovlev** [scylladb/scylla#4914] opened 2019-08-27 16:42 UTC
*Installation details*
Scylla version (or git commit hash): 3.1.0.rc3-0.20190727.bebfd7b26
Cluster size: 3 nodes
OS (RHEL/CentOS/Ubuntu/AWS AMI): ami-0e90f1a90d8bb3a4e

Scylla refused to boot in case the DB file is not found.

Received it in case the missed file was of both regular table and of MV.

CorruptThenRepair nemesis.

Cassandra-stress command:
```"cassandra-stress write cl=QUORUM duration=180m -schema 'replication(factor=3) compaction(strategy=SizeTieredCompactionStrategy)' -port jmx=6868 -mode cql3 native -rate threads=1000 -pop seq=1..10000000 -log interval=5"```

Scenario:
1. Stop Scylla
2. Remove DB file
3. Start Scylla

Result: Scylla refused to boot.

Chosen files are: ```/var/lib/scylla/data/mview/users_by_last_name-cd869210c87811e9a1c8000000000000/mc-4-big-Data.d```

Error during start:
```
Aug 27 03:28:54 ip-172-30-0-197.ec2.internal scylla.bin[8264]:  [shard 0] database - Unrecognized error while processing mc-7-big-TOC.txt: std::filesystem::__cxx11::filesystem_error (error system:2, filesystem error: open failed: No such file or directory [/var/lib/scylla/data/mview/users_by_last_name-cd869210c87811e9a1c8000000000000/mc-7-big-Data.db]). Refusing to boot
Aug 27 03:28:54 ip-172-30-0-197.ec2.internal scylla.bin[8264]:  [shard 0] database - Unrecognized error while processing mc-4-big-TOC.txt: std::filesystem::__cxx11::filesystem_error (error system:2, filesystem error: open failed: No such file or directory [/var/lib/scylla/data/mview/users_by_first_name-cd300da0c87811e9bd66000000000002/mc-4-big-Data.db]). Refusing to boot
Aug 27 03:28:54 ip-172-30-0-197.ec2.internal scylla.bin[8264]:  [shard 0] database - Unrecognized error while processing mc-4-big-TOC.txt: std::filesystem::__cxx11::filesystem_error (error system:2, filesystem error: open failed: No such file or directory [/var/lib/scylla/data/mview/users_by_last_name-cd869210c87811e9a1c8000000000000/mc-4-big-Data.db]). Refusing to boot
Aug 27 03:28:54 ip-172-30-0-197.ec2.internal scylla.bin[8264]:  [shard 0] database - Exception while populating keyspace 'mview' with column family 'users_by_last_name' from file '/var/lib/scylla/data/mview/users_by_last_name-cd869210c87811e9a1c8000000000000': std::filesystem::__cxx11::filesystem_error (error system:2, filesystem error: open failed: No such file or directory [/var/lib/scylla/data/mview/users_by_last_name-cd869210c87811e9a1c8000000000000/mc-4-big-Data.db])
Aug 27 03:28:54 ip-172-30-0-197.ec2.internal scylla.bin[8264]:  [shard 0] database - Exception while populating keyspace 'mview' with column family 'users_by_first_name' from file '/var/lib/scylla/data/mview/users_by_first_name-cd300da0c87811e9bd66000000000002': std::filesystem::__cxx11::filesystem_error (error system:2, filesystem error: open failed: No such file or directory [/var/lib/scylla/data/mview/users_by_first_name-cd300da0c87811e9bd66000000000002/mc-4-big-Data.db])
Aug 27 03:28:54 ip-172-30-0-197.ec2.internal scylla.bin[8264]:  [shard 0] init - Shutdown database started
Aug 27 03:28:54 ip-172-30-0-197.ec2.internal scylla.bin[8264]:  [shard 0] init - Shutdown database finished
Aug 27 03:28:54 ip-172-30-0-197.ec2.internal scylla.bin[8264]:  [shard 0] init - Startup failed: std::runtime_error (Exception while populating keyspace 'mview' with column family 'users_by_last_name' from file '/var/lib/scylla/data/mview/users_by_last_name-cd869210c87811e9a1c8000000000000': std::filesystem::__cxx11::filesystem_error (error system:2, filesystem error: open failed: No such file or directory [/var/lib/scylla/data/mview/users_by_last_name-cd869210c87811e9a1c8000000000000/mc-4-big-Data.db]))
Aug 27 03:28:54 ip-172-30-0-197.ec2.internal systemd[1]: scylla-server.service: main process exited, code=exited, status=1/FAILURE
Aug 27 03:28:54 ip-172-30-0-197.ec2.internal systemd[1]: Failed to start Scylla Server.
```

**Comment by tzach** [comment] 2019-08-27 18:06
@juliayakovlev is this a regression? new test?

**Comment by bhalevy** [comment] 2019-08-27 18:57
This is the expected behavior.
Why is it considered a bug?

**Comment by juliayakovlev** [comment] 2019-08-28 08:05
> @juliayakovlev is this a regression? new test?

@tzach It's not new test, but it was the bug in the test, so it was always succeeded. After fixing the bug found this issue

**Comment by bentsi** [comment] 2019-08-28 13:47
let's close this since it is an issue in the test

**Closed** 2019-08-28 15:05 UTC
