### ISSUE TITLE
coredump when stop scylla

### ISSUE THREAD

**Issue by infordb** [scylladb/scylla#2942] opened 2017-11-08 08:34 UTC
version info
scylla-1.7.4-0.20170726.ff643e3.el7.centos.x86_64
hector-core-1.1-4.jar
libthrift-0.7.0.jar
kairosdb 1.1.2

I am testing Kairosdb with Scylladb 
when I stop Scylla using systemctl stop scylla-server command  after write load through kairosdb
coredump occurs as shown below.

Is this phenomenon related to kairosdb or thrift ?

Nov  8 17:14:31 stgtest02 systemd: Stopping Scylla JMX...
Nov  8 17:14:31 stgtest02 systemd: Stopped Run Scylla Housekeeping restart mode.
Nov  8 17:14:31 stgtest02 systemd: Stopping Run Scylla Housekeeping restart mode.
Nov  8 17:14:31 stgtest02 systemd: Stopped Run Scylla Housekeeping daily mode.
Nov  8 17:14:31 stgtest02 systemd: Stopping Run Scylla Housekeeping daily mode.
Nov  8 17:14:32 stgtest02 systemd: scylla-jmx.service: main process exited, code=exited, status=143/n/a
Nov  8 17:14:32 stgtest02 systemd: Stopped Scylla JMX.
Nov  8 17:14:32 stgtest02 systemd: Unit scylla-jmx.service entered failed state.
Nov  8 17:14:32 stgtest02 systemd: scylla-jmx.service failed.
Nov  8 17:14:32 stgtest02 systemd: Stopping Scylla Server...
Nov  8 17:14:32 stgtest02 scylla: [shard 0] storage_service - Drain on shutdown: starts
Nov  8 17:14:32 stgtest02 scylla: [shard 0] storage_service - Stop transport: starts
Nov  8 17:14:32 stgtest02 scylla: [shard 0] gossip - My status = NORMAL
Nov  8 17:14:32 stgtest02 scylla: [shard 0] gossip - Announcing shutdown
Nov  8 17:14:32 stgtest02 scylla: [shard 0] storage_service - Node 70.60.31.155 state jump to normal
Nov  8 17:14:34 stgtest02 scylla: [shard 0] storage_service - Stop transport: stop_gossiping done
Nov  8 17:14:34 stgtest02 scylla: scylla: /opt/scylladb/include/boost/intrusive/list.hpp:1267: boost::intrusive::list_impl<ValueTraits, SizeType, ConstantTimeSize, HeaderHolder>::iterator boost::intrusive::list_impl<ValueTraits, SizeType, ConstantTimeSize, HeaderHolder>::iterator_to(boost::intrusive::list_impl<ValueTraits, SizeType, ConstantTimeSize, HeaderHolder>::reference) [with ValueTraits = boost::intrusive::bhtraits<thrift_server::connection, boost::intrusive::list_node_traits<void*>, (boost::intrusive::link_mode_type)1u, boost::intrusive::dft_tag, 1u>; SizeType = long unsigned int; bool ConstantTimeSize = true; HeaderHolder = void; boost::intrusive::list_impl<ValueTraits, SizeType, ConstantTimeSize, HeaderHolder>::iterator = boost::intrusive::list_iterator<boost::intrusive::bhtraits<thrift_server::connection, boost::intrusive::list_node_traits<void*>, (boost::intrusive::link_mode_type)1u, boost::intrusive::dft_tag, 1u>, false>; boost::intrusive::list_impl<ValueTraits, SizeType, ConstantTimeSize, HeaderHolder>::reference = thrift_server::connection&]: Assertion `!node_algorithms::inited(this->priv_value_traits().to_node_ptr(value))' failed.
Nov  8 17:14:34 stgtest02 scylla: [shard 0] storage_service - Thrift server stopped
Nov  8 17:14:34 stgtest02 scylla: scylla: /opt/scylladb/include/boost/intrusive/list.hpp:1267: boost::intrusive::list_impl<ValueTraits, SizeType, ConstantTimeSize, HeaderHolder>::iterator boost::intrusive::list_impl<ValueTraits, SizeType, ConstantTimeSize, HeaderHolder>::iterator_to(boost::intrusive::list_impl<ValueTraits, SizeType, ConstantTimeSize, HeaderHolder>::reference) [with ValueTraits = boost::intrusive::bhtraits<thrift_server::connection, boost::intrusive::list_node_traits<void*>, (boost::intrusive::link_mode_type)1u, boost::intrusive::dft_tag, 1u>; SizeType = long unsigned int; bool ConstantTimeSize = true; HeaderHolder = void; boost::intrusive::list_impl<ValueTraits, SizeType, ConstantTimeSize, HeaderHolder>::iterator = boost::intrusive::list_iterator<boost::intrusive::bhtraits<thrift_server::connection, boost::intrusive::list_node_traits<void*>, (boost::intrusive::link_mode_type)1u, boost::intrusive::dft_tag, 1u>, false>; boost::intrusive::list_impl<ValueTraits, SizeType, ConstantTimeSize, HeaderHolder>::reference = thrift_server::connection&]: Assertion `!node_algorithms::inited(this->priv_value_traits().to_node_ptr(value))' failed.
Nov  8 17:14:34 stgtest02 scylla: scylla: /opt/scylladb/include/boost/intrusive/list.hpp:1267: boost::intrusive::list_impl<ValueTraits, SizeType, ConstantTimeSize, HeaderHolder>::iterator boost::intrusive::list_impl<ValueTraits, SizeType, ConstantTimeSize, HeaderHolder>::iterator_to(boost::intrusive::list_impl<ValueTraits, SizeType, ConstantTimeSize, HeaderHolder>::reference) [with ValueTraits = boost::intrusive::bhtraits<thrift_server::connection, boost::intrusive::list_node_traits<void*>, (boost::intrusive::link_mode_type)1u, boost::intrusive::dft_tag, 1u>; SizeType = long unsigned int; bool ConstantTimeSize = true; HeaderHolder = void; boost::intrusive::list_impl<ValueTraits, SizeType, ConstantTimeSize, HeaderHolder>::iterator = boost::intrusive::list_iterator<boost::intrusive::bhtraits<thrift_server::connection, boost::intrusive::list_node_traits<void*>, (boost::intrusive::link_mode_type)1u, boost::intrusive::dft_tag, 1u>, false>; boost::intrusive::list_impl<ValueTraits, SizeType, ConstantTimeSize, HeaderHolder>::reference = thrift_server::connection&]: Assertion `!node_algorithms::inited(this->priv_value_traits().to_node_ptr(value))' failed.
Nov  8 17:14:34 stgtest02 scylla: Aborting on shard 1.
Nov  8 17:14:34 stgtest02 scylla: Backtrace:
Nov  8 17:14:34 stgtest02 scylla: scylla: /opt/scylladb/include/boost/intrusive/list.hpp:1267: boost::intrusive::list_impl<ValueTraits, SizeType, ConstantTimeSize, HeaderHolder>::iterator boost::intrusive::list_impl<ValueTraits, SizeType, ConstantTimeSize, HeaderHolder>::iterator_to(boost::intrusive::list_impl<ValueTraits, SizeType, ConstantTimeSize, HeaderHolder>::reference) [with ValueTraits = boost::intrusive::bhtraits<thrift_server::connection, boost::intrusive::list_node_traits<void*>, (boost::intrusive::link_mode_type)1u, boost::intrusive::dft_tag, 1u>; SizeType = long unsigned int; bool ConstantTimeSize = true; HeaderHolder = void; boost::intrusive::list_impl<ValueTraits, SizeType, ConstantTimeSize, HeaderHolder>::iterator = boost::intrusive::list_iterator<boost::intrusive::bhtraits<thrift_server::connection, boost::intrusive::list_node_traits<void*>, (boost::intrusive::link_mode_type)1u, boost::intrusive::dft_tag, 1u>, false>; boost::intrusive::list_impl<ValueTraits, SizeType, ConstantTimeSize, HeaderHolder>::reference = thrift_server::connection&]: Assertion `!node_algorithms::inited(this->priv_value_traits().to_node_ptr(value))' failed.
Nov  8 17:14:34 stgtest02 scylla: scylla: /opt/scylladb/include/boost/intrusive/list.hpp:1267: boost::intrusive::list_impl<ValueTraits, SizeType, ConstantTimeSize, HeaderHolder>::iterator boost::intrusive::list_impl<ValueTraits, SizeType, ConstantTimeSize, HeaderHolder>::iterator_to(boost::intrusive::list_impl<ValueTraits, SizeType, ConstantTimeSize, HeaderHolder>::reference) [with ValueTraits = boost::intrusive::bhtraits<thrift_server::connection, boost::intrusive::list_node_traits<void*>, (boost::intrusive::link_mode_type)1u, boost::intrusive::dft_tag, 1u>; SizeType = long unsigned int; bool ConstantTimeSize = true; HeaderHolder = void; boost::intrusive::list_impl<ValueTraits, SizeType, ConstantTimeSize, HeaderHolder>::iterator = boost::intrusive::list_iterator<boost::intrusive::bhtraits<thrift_server::connection, boost::intrusive::list_node_traits<void*>, (boost::intrusive::link_mode_type)1u, boost::intrusive::dft_tag, 1u>, false>; boost::intrusive::list_impl<ValueTraits, SizeType, ConstantTimeSize, HeaderHolder>::reference = thrift_server::connection&]: Assertion `!node_algorithms::inited(this->priv_value_traits().to_node_ptr(value))' failed.
Nov  8 17:14:34 stgtest02 scylla: scylla: /opt/scylladb/include/boost/intrusive/list.hpp:1267: boost::intrusive::list_impl<ValueTraits, SizeType, ConstantTimeSize, HeaderHolder>::iterator boost::intrusive::list_impl<ValueTraits, SizeType, ConstantTimeSize, HeaderHolder>::iterator_to(boost::intrusive::list_impl<ValueTraits, SizeType, ConstantTimeSize, HeaderHolder>::reference) [with ValueTraits = boost::intrusive::bhtraits<thrift_server::connection, boost::intrusive::list_node_traits<void*>, (boost::intrusive::link_mode_type)1u, boost::intrusive::dft_tag, 1u>; SizeType = long unsigned int; bool ConstantTimeSize = true; HeaderHolder = void; boost::intrusive::list_impl<ValueTraits, SizeType, ConstantTimeSize, HeaderHolder>::iterator = boost::intrusive::list_iterator<boost::intrusive::bhtraits<thrift_server::connection, boost::intrusive::list_node_traits<void*>, (boost::intrusive::link_mode_type)1u, boost::intrusive::dft_tag, 1u>, false>; boost::intrusive::list_impl<ValueTraits, SizeType, ConstantTimeSize, HeaderHolder>::reference = thrift_server::connection&]: Assertion `!node_algorithms::inited(this->priv_value_traits().to_node_ptr(value))' failed.
Nov  8 17:14:34 stgtest02 scylla: scylla: /opt/scylladb/include/boost/intrusive/list.hpp:1267: boost::intrusive::list_impl<ValueTraits, SizeType, ConstantTimeSize, HeaderHolder>::iterator boost::intrusive::list_impl<ValueTraits, SizeType, ConstantTimeSize, HeaderHolder>::iterator_to(boost::intrusive::list_impl<ValueTraits, SizeType, ConstantTimeSize, HeaderHolder>::reference) [with ValueTraits = boost::intrusive::bhtraits<thrift_server::connection, boost::intrusive::list_node_traits<void*>, (boost::intrusive::link_mode_type)1u, boost::intrusive::dft_tag, 1u>; SizeType = long unsigned int; bool ConstantTimeSize = true; HeaderHolder = void; boost::intrusive::list_impl<ValueTraits, SizeType, ConstantTimeSize, HeaderHolder>::iterator = boost::intrusive::list_iterator<boost::intrusive::bhtraits<thrift_server::connection, boost::intrusive::list_node_traits<void*>, (boost::intrusive::link_mode_type)1u, boost::intrusive::dft_tag, 1u>, false>; boost::intrusive::list_impl<ValueTraits, SizeType, ConstantTimeSize, HeaderHolder>::reference = thrift_server::connection&]: Assertion `!node_algorithms::inited(this->priv_value_traits().to_node_ptr(value))' failed.
Nov  8 17:14:34 stgtest02 scylla: scylla: /opt/scylladb/include/boost/intrusive/list.hpp:1267: boost::intrusive::list_impl<ValueTraits, SizeType, ConstantTimeSize, HeaderHolder>::iterator boost::intrusive::list_impl<ValueTraits, SizeType, ConstantTimeSize, HeaderHolder>::iterator_to(boost::intrusive::list_impl<ValueTraits, SizeType, ConstantTimeSize, HeaderHolder>::reference) [with ValueTraits = boost::intrusive::bhtraits<thrift_server::connection, boost::intrusive::list_node_traits<void*>, (boost::intrusive::link_mode_type)1u, boost::intrusive::dft_tag, 1u>; SizeType = long unsigned int; bool ConstantTimeSize = true; HeaderHolder = void; boost::intrusive::list_impl<ValueTraits, SizeType, ConstantTimeSize, HeaderHolder>::iterator = boost::intrusive::list_iterator<boost::intrusive::bhtraits<thrift_server::connection, boost::intrusive::list_node_traits<void*>, (boost::intrusive::link_mode_type)1u, boost::intrusive::dft_tag, 1u>, false>; boost::intrusive::list_impl<ValueTraits, SizeType, ConstantTimeSize, HeaderHolder>::reference = thrift_server::connection&]: Assertion `!node_algorithms::inited(this->priv_value_traits().to_node_ptr(value))' failed.
Nov  8 17:14:34 stgtest02 scylla: scylla: /opt/scylladb/include/boost/intrusive/list.hpp:1267: boost::intrusive::list_impl<ValueTraits, SizeType, ConstantTimeSize, HeaderHolder>::iterator boost::intrusive::list_impl<ValueTraits, SizeType, ConstantTimeSize, HeaderHolder>::iterator_to(boost::intrusive::list_impl<ValueTraits, SizeType, ConstantTimeSize, HeaderHolder>::reference) [with ValueTraits = boost::intrusive::bhtraits<thrift_server::connection, boost::intrusive::list_node_traits<void*>, (boost::intrusive::link_mode_type)1u, boost::intrusive::dft_tag, 1u>; SizeType = long unsigned int; bool ConstantTimeSize = true; HeaderHolder = void; boost::intrusive::list_impl<ValueTraits, SizeType, ConstantTimeSize, HeaderHolder>::iterator = boost::intrusive::list_iterator<boost::intrusive::bhtraits<thrift_server::connection, boost::intrusive::list_node_traits<void*>, (boost::intrusive::link_mode_type)1u, boost::intrusive::dft_tag, 1u>, false>; boost::intrusive::list_impl<ValueTraits, SizeType, ConstantTimeSize, HeaderHolder>::reference = thrift_server::connection&]: Assertion `!node_algorithms::inited(this->priv_value_traits().to_node_ptr(value))' failed.
Nov  8 17:14:34 stgtest02 scylla: scylla: /opt/scylladb/include/boost/intrusive/list.hpp:1267: boost::intrusive::list_impl<ValueTraits, SizeType, ConstantTimeSize, HeaderHolder>::iterator boost::intrusive::list_impl<ValueTraits, SizeType, ConstantTimeSize, HeaderHolder>::iterator_to(boost::intrusive::list_impl<ValueTraits, SizeType, ConstantTimeSize, HeaderHolder>::reference) [with ValueTraits = boost::intrusive::bhtraits<thrift_server::connection, boost::intrusive::list_node_traits<void*>, (boost::intrusive::link_mode_type)1u, boost::intrusive::dft_tag, 1u>; SizeType = long unsigned int; bool ConstantTimeSize = true; HeaderHolder = void; boost::intrusive::list_impl<ValueTraits, SizeType, ConstantTimeSize, HeaderHolder>::iterator = boost::intrusive::list_iterator<boost::intrusive::bhtraits<thrift_server::connection, boost::intrusive::list_node_traits<void*>, (boost::intrusive::link_mode_type)1u, boost::intrusive::dft_tag, 1u>, false>; boost::intrusive::list_impl<ValueTraits, SizeType, ConstantTimeSize, HeaderHolder>::reference = thrift_server::connection&]: Assertion `!node_algorithms::inited(this->priv_value_traits().to_node_ptr(value))' failed.
Nov  8 17:14:34 stgtest02 scylla: scylla: /opt/scylladb/include/boost/intrusive/list.hpp:1267: boost::intrusive::list_impl<ValueTraits, SizeType, ConstantTimeSize, HeaderHolder>::iterator boost::intrusive::list_impl<ValueTraits, SizeType, ConstantTimeSize, HeaderHolder>::iterator_to(boost::intrusive::list_impl<ValueTraits, SizeType, ConstantTimeSize, HeaderHolder>::reference) [with ValueTraits = boost::intrusive::bhtraits<thrift_server::connection, boost::intrusive::list_node_traits<void*>, (boost::intrusive::link_mode_type)1u, boost::intrusive::dft_tag, 1u>; SizeType = long unsigned int; bool ConstantTimeSize = true; HeaderHolder = void; boost::intrusive::list_impl<ValueTraits, SizeType, ConstantTimeSize, HeaderHolder>::iterator = boost::intrusive::list_iterator<boost::intrusive::bhtraits<thrift_server::connection, boost::intrusive::list_node_traits<void*>, (boost::intrusive::link_mode_type)1u, boost::intrusive::dft_tag, 1u>, false>; boost::intrusive::list_impl<ValueTraits, SizeType, ConstantTimeSize, HeaderHolder>::reference = thrift_server::connection&]: Assertion `!node_algorithms::inited(this->priv_value_traits().to_node_ptr(value))' failed.
Nov  8 17:14:34 stgtest02 scylla: scylla: /opt/scylladb/include/boost/intrusive/list.hpp:1267: boost::intrusive::list_impl<ValueTraits, SizeType, ConstantTimeSize, HeaderHolder>::iterator boost::intrusive::list_impl<ValueTraits, SizeType, ConstantTimeSize, HeaderHolder>::iterator_to(boost::intrusive::list_impl<ValueTraits, SizeType, ConstantTimeSize, HeaderHolder>::reference) [with ValueTraits = boost::intrusive::bhtraits<thrift_server::connection, boost::intrusive::list_node_traits<void*>, (boost::intrusive::link_mode_type)1u, boost::intrusive::dft_tag, 1u>; SizeType = long unsigned int; bool ConstantTimeSize = true; HeaderHolder = void; boost::intrusive::list_impl<ValueTraits, SizeType, ConstantTimeSize, HeaderHolder>::iterator = boost::intrusive::list_iterator<boost::intrusive::bhtraits<thrift_server::connection, boost::intrusive::list_node_traits<void*>, (boost::intrusive::link_mode_type)1u, boost::intrusive::dft_tag, 1u>, false>; boost::intrusive::list_impl<ValueTraits, SizeType, ConstantTimeSize, HeaderHolder>::reference = thrift_server::connection&]: Assertion `!node_algorithms::inited(this->priv_value_traits().to_node_ptr(value))' failed.
Nov  8 17:14:34 stgtest02 scylla: scylla: /opt/scylladb/include/boost/intrusive/list.hpp:1267: boost::intrusive::list_impl<ValueTraits, SizeType, ConstantTimeSize, HeaderHolder>::iterator boost::intrusive::list_impl<ValueTraits, SizeType, ConstantTimeSize, HeaderHolder>::iterator_to(boost::intrusive::list_impl<ValueTraits, SizeType, ConstantTimeSize, HeaderHolder>::reference) [with ValueTraits = boost::intrusive::bhtraits<thrift_server::connection, boost::intrusive::list_node_traits<void*>, (boost::intrusive::link_mode_type)1u, boost::intrusive::dft_tag, 1u>; SizeType = long unsigned int; bool ConstantTimeSize = true; HeaderHolder = void; boost::intrusive::list_impl<ValueTraits, SizeType, ConstantTimeSize, HeaderHolder>::iterator = boost::intrusive::list_iterator<boost::intrusive::bhtraits<thrift_server::connection, boost::intrusive::list_node_traits<void*>, (boost::intrusive::link_mode_type)1u, boost::intrusive::dft_tag, 1u>, false>; boost::intrusive::list_impl<ValueTraits, SizeType, ConstantTimeSize, HeaderHolder>::reference = thrift_server::connection&]: Assertion `!node_algorithms::inited(this->priv_value_traits().to_node_ptr(value))' failed.
Nov  8 17:14:34 stgtest02 scylla: scylla: /opt/scylladb/include/boost/intrusive/list.hpp:1267: boost::intrusive::list_impl<ValueTraits, SizeType, ConstantTimeSize, HeaderHolder>::iterator boost::intrusive::list_impl<ValueTraits, SizeType, ConstantTimeSize, HeaderHolder>::iterator_to(boost::intrusive::list_impl<ValueTraits, SizeType, ConstantTimeSize, HeaderHolder>::reference) [with ValueTraits = boost::intrusive::bhtraits<thrift_server::connection, boost::intrusive::list_node_traits<void*>, (boost::intrusive::link_mode_type)1u, boost::intrusive::dft_tag, 1u>; SizeType = long unsigned int; bool ConstantTimeSize = true; HeaderHolder = void; boost::intrusive::list_impl<ValueTraits, SizeType, ConstantTimeSize, HeaderHolder>::iterator = boost::intrusive::list_iterator<boost::intrusive::bhtraits<thrift_server::connection, boost::intrusive::list_node_traits<void*>, (boost::intrusive::link_mode_type)1u, boost::intrusive::dft_tag, 1u>, false>; boost::intrusive::list_impl<ValueTraits, SizeType, ConstantTimeSize, HeaderHolder>::reference = thrift_server::connection&]: Assertion `!node_algorithms::inited(this->priv_value_traits().to_node_ptr(value))' failed.
Nov  8 17:14:34 stgtest02 scylla: 0x00000000004e06ca
Nov  8 17:14:34 stgtest02 scylla: 0x00000000004e07d3
Nov  8 17:14:34 stgtest02 scylla: 0x00007f8a2e1d90ff
Nov  8 17:14:34 stgtest02 scylla: 0x00007f8a2de3e5f6
Nov  8 17:14:34 stgtest02 scylla: 0x00007f8a2de3fce7
Nov  8 17:14:34 stgtest02 scylla: 0x00007f8a2de37565
Nov  8 17:14:34 stgtest02 scylla: 0x00007f8a2de37611
...
Nov  8 17:15:42 stgtest02 systemd-coredump: Process 8628 (scylla) of user 597 dumped

**Comment by infordb** [comment] 2017-11-08 08:38
If I use scylla-2.0.0-0.20170929, I got the following message when I write test with Kairosdb
Nov  8 16:00:13 stgtest02 scylla: Reactor stalled for 2000 ms on shard 14.
Nov  8 16:01:20 stgtest02 scylla: Reactor stalled for 2000 ms on shard 7.
Nov  8 16:01:39 stgtest02 scylla: Reactor stalled for 2000 ms on shard 2.
Nov  8 16:02:02 stgtest02 scylla: Reactor stalled for 2000 ms on shard 5.

**Comment by tzach** [comment] 2017-11-08 08:47
@infordb any chance you can upload teh coredump file ?
http://docs.scylladb.com/operating-scylla/troubleshooting/report_scylla_problem/#send-the-core-dump

**Comment by gleb-cloudius** [comment] 2017-11-08 08:47
Looks like thrift related. c525331e60e379babe014d3753179c7a7c7be3f8 was supposed to fix it and it is in 1.7.4, but likely there some additional problems. /cc @duarten

**Comment by duarten** [comment] 2017-11-08 11:14
@gleb-cloudius I can't find c525331 on 1.7.4. How did you check it?

**Comment by infordb** [comment] 2017-11-08 11:27
kairosdb 1.2 supports CQL.
so I tested the same with kairosdb1.2 & CQL
But the result was the same. A coredump occurred when scylladb stop.

scylla-1.7.4 / kairosdb 1.2 & CQL

59:38 stgtest02 scylla: Aborting on shard 4scylla: /opt/scylladb/include/boost/intrusive/list.hpp:1267: boost::intrusive::list_impl<ValueTraits, SizeType, ConstantTimeSize, HeaderHolder>::iterator boost::intrusive::list_impl<ValueTraits, SizeType, ConstantTimeSize, HeaderHolder>::iterator_to(boost::intrusive::list_impl<ValueTraits, SizeType, ConstantTimeSize, HeaderHolder>::reference) [with ValueTraits = boost::intrusive::bhtraits<thrift_server::connection, boost::intrusive::list_node_traits<void*>, (boost::intrusive::link_mode_type)1u, boost::intrusive::dft_tag, 1u>; SizeType = long unsigned int; bool ConstantTimeSize = true; HeaderHolder = void; boost::intrusive::list_impl<ValueTraits, SizeType, ConstantTimeSize, HeaderHolder>::iterator = boost::intrusive::list_iterator<boost::intrusive::bhtraits<thrift_server::connection, boost::intrusive::list_node_traits<void*>, (boost::intrusive::link_mode_type)1u, boost::intrusive::dft_tag, 1u>, false>; boost::intrusive::list_impl<ValueTraits, SizeType, ConstantTimeSize, HeaderHolder>::reference = thrift_server::connection&]: Assertion `!node_algorithms::inited(this->priv_value_traits().to_node_ptr(value))' failed.
Nov  8 19:59:38 stgtest02 scylla: .

**Comment by gleb-cloudius** [comment] 2017-11-08 12:42
On Wed, Nov 08, 2017 at 11:14:06AM +0000, Duarte Nunes wrote:
> @gleb-cloudius I can't find c525331 on 1.7.4. How did you check it?
> 
Commit a95c045b48a78bac117827380286a68a9eea151a, no?

--
			Gleb.

**Comment by gleb-cloudius** [comment] 2017-11-08 12:44
On Wed, Nov 08, 2017 at 11:27:25AM +0000, Junghyun Park wrote:
> kairosdb 1.2 supports CQL.
> so I tested the same with kairosdb1.2 & CQL
> But the result was the same. A coredump occurred when scylladb stop.
> 
> scylla-1.7.4 / kairosdb 1.2 & CQL
> 
> 59:38 stgtest02 scylla: Aborting on shard 4scylla: /opt/scylladb/include/boost/intrusive/list.hpp:1267: boost::intrusive::list_impl<ValueTraits, SizeType, ConstantTimeSize, HeaderHolder>::iterator boost::intrusive::list_impl<ValueTraits, SizeType, ConstantTimeSize, HeaderHolder>::iterator_to(boost::intrusive::list_impl<ValueTraits, SizeType, ConstantTimeSize, HeaderHolder>::reference) [with ValueTraits = boost::intrusive::bhtraits<thrift_server::connection, boost::intrusive::list_node_traits<void*>, (boost::intrusive::link_mode_type)1u, boost::intrusive::dft_tag, 1u>; SizeType = long unsigned int; bool ConstantTimeSize = true; HeaderHolder = void; boost::intrusive::list_impl<ValueTraits, SizeType, ConstantTimeSize, HeaderHolder>::iterator = boost::intrusive::list_iterator<boost::intrusive::bhtraits<thrift_server::connection, boost::intrusive::list_node_traits<void*>, (boost::intrusive::link_mode_type)1u, boost::intrusive::dft_tag, 1u>, false>; boost::intrusive::list_impl<ValueTraits, SizeType, ConstantTimeSize, HeaderHolder>::reference = thrift_server::connection&]: Assertion `!node_algorithms::inited(this->priv_value_traits().to_node_ptr(value))' failed.
> Nov  8 19:59:38 stgtest02 scylla: .
> 
According to the trace there are still thrift_server::connection there.

--
			Gleb.

**Comment by duarten** [comment] 2017-11-08 12:49
Indeed, will fix.

**Comment by duarten** [comment] 2017-11-08 16:35
I think this is #2657.

**Comment by infordb** [comment] 2017-11-09 01:06
@duarten Testing with kairosdb1.2 & CQL had coredump. Thrift as well as CQL seems to have a problem

**Comment by duarten** [comment] 2017-11-09 10:06
@infordb The problem is in the thrift server, I have a fix for it.

**Comment by slivne** [comment] 2017-11-12 11:32
@duarten - is this fixed by your patches ?

**Comment by duarten** [comment] 2017-11-13 09:11
@slivne Yep.

**Closed** 2017-11-13 10:48 UTC
Labels: thrift-api
