### ISSUE TITLE
Steep drop in read-from-disk throughput when we run out of free LSA memory

### ISSUE THREAD

**Issue by vladzcloudius** [scylladb/scylla#3297] opened 2018-03-17 00:47 UTC
*Installation details*
Scylla version (or git commit hash): f5c32423b8824c77ce5642c580e26c7c5b313757 (master) and 6271f30716521694bc07532a8c783fff59d39412 + 596a9d0 (branch-2.1)
Cluster size: 1
OS (RHEL/CentOS/Ubuntu/AWS AMI): Fedora 26

*Test and HW setup*
The same as in #3250 and #3246
Test: read from disk test as in #3246 

*Description of the problem*
When we run out of free LSA memory and start compacting LSA segments we can observe a steep drop in the throughput. 
It's very clearly seen with 2.1 (drop is about 10% from ~104K to ~94K, the graph includes 1.5 iterations of the same read test (out of 3)):
![image](https://user-images.githubusercontent.com/6103981/37549710-35bf48c4-2959-11e8-8a18-10f3bfe228b8.png)

But master seems to behave a lot worse:
![image](https://user-images.githubusercontent.com/6103981/37549719-488c2e90-2959-11e8-8ffe-9a644a11ee31.png)

Note that the drop happens even before we run out of LSA and it's accompanied by a read timeout.

In addition there is a 2s stall on shard 8:
```
Reactor stalled for 2009 ms on shard 8.
Backtrace:
  0x00000000005a6dfc
  0x00000000005a72b6
  /usr/lib64/libpthread.so.0+0x000000000001241f
  0x00000000010fbb4f
  0x0000000001104939
  0x000000000110f547
  0x0000000001095da6
  0x000000000109a703
  0x000000000109cb17
  0x000000000109cdfa
  0x000000000128012f
  0x000000000104254f
  0x000000000106c2a1
  0x000000000106fb70
  0x0000000000589bf6
  0x0000000000589db1
  0x000000000064d8d7
  0x000000000065423b
  0x0000000000715b6d
  /usr/lib64/libpthread.so.0+0x000000000000736c
  /usr/lib64/libc.so.6+0x0000000000110b4e
```

Here is the decoding of the above:
```

logalloc::segment_zone::try_creating_zone() at /home/scylla/scylla/utils/logalloc.cc:530 (discriminator 2)
logalloc::segment_pool::allocate_segment() at /home/scylla/scylla/utils/logalloc.cc:770
logalloc::segment_pool::refill_emergency_reserve() at /home/scylla/scylla/utils/logalloc.cc:808
 (inlined by) logalloc::allocating_section::reserve() at /home/scylla/scylla/utils/logalloc.cc:2318
_ZN8logalloc18allocating_section12with_reserveIZNS0_clIZN5cache11lsa_manager21run_in_update_sectionIZZNS3_26cache_flat_mutation_reader20read_from_underlyingENSt6chrono10time_pointIN7seastar12lowres_clockENS7_8durationIlSt5ratioILl1ELl1000EEEEEEENKUlvE1_clEvEUlvE_EEDcRKT_EUlvE_EEDcRNS_6regionEOSI_EUlvE_EEDcSO_ at /home/scylla/scylla/utils/logalloc.hh:678
 (inlined by) _ZN8logalloc18allocating_sectionclIZN5cache11lsa_manager21run_in_update_sectionIZZNS2_26cache_flat_mutation_reader20read_from_underlyingENSt6chrono10time_pointIN7seastar12lowres_clockENS6_8durationIlSt5ratioILl1ELl1000EEEEEEENKUlvE1_clEvEUlvE_EEDcRKT_EUlvE_EEDcRNS_6regionEOSH_ at /home/scylla/scylla/utils/logalloc.hh:729
 (inlined by) _ZN5cache11lsa_manager21run_in_update_sectionIZZNS_26cache_flat_mutation_reader20read_from_underlyingENSt6chrono10time_pointIN7seastar12lowres_clockENS3_8durationIlSt5ratioILl1ELl1000EEEEEEENKUlvE1_clEvEUlvE_EEDcRKT_ at /home/scylla/scylla/row_cache.hh:572
 (inlined by) cache::cache_flat_mutation_reader::read_from_underlying(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda()#3}::operator()() const at /home/scylla/scylla/cache_flat_mutation_reader.hh:277
 (inlined by) seastar::future<> consume_mutation_fragments_until<cache::cache_flat_mutation_reader::read_from_underlying(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda()#1}, cache::cache_flat_mutation_reader::read_from_underlying(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda(mutation_fragment)#2}, cache::cache_flat_mutation_reader::read_from_underlying(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda()#3}>(flat_mutation_reader&, cache::cache_flat_mutation_reader::read_from_underlying(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda()#1}&&, cache::cache_flat_mutation_reader::read_from_underlying(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda(mutation_fragment)#2}&&, cache::cache_flat_mutation_reader::read_from_underlying(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda()#3}&&)::{lambda()#2}::operator()() const at /home/scylla/scylla/flat_mutation_reader.hh:440
std::enable_if<seastar::is_future<std::result_of<seastar::future<> ()>::type>::value, {lambda()#3}>::type seastar::do_void_futurize_apply<seastar::future<> consume_mutation_fragments_until<cache::cache_flat_mutation_reader::read_from_underlying(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda()#1}, cache::cache_flat_mutation_reader::read_from_underlying(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda(mutation_fragment)#2}, cache::cache_flat_mutation_reader::read_from_underlying(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda()#3}>(flat_mutation_reader&, cache::cache_flat_mutation_reader::read_from_underlying(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda()#1}&&, cache::cache_flat_mutation_reader::read_from_underlying(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda(mutation_fragment)#2}&&, cache::cache_flat_mutation_reader::read_from_underlying(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda()#3}&&)::{lambda()#2}&>(flat_mutation_reader, seastar::is_future) at /home/scylla/scylla/./seastar/core/future.hh:1319
 (inlined by) {lambda()#3} seastar::futurize<void>::apply<seastar::future<> consume_mutation_fragments_until<cache::cache_flat_mutation_reader::read_from_underlying(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda()#1}, cache::cache_flat_mutation_reader::read_from_underlying(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda(mutation_fragment)#2}, cache::cache_flat_mutation_reader::read_from_underlying(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda()#3}>(flat_mutation_reader&, cache::cache_flat_mutation_reader::read_from_underlying(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda()#1}&&, cache::cache_flat_mutation_reader::read_from_underlying(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda(mutation_fragment)#2}&&, cache::cache_flat_mutation_reader::read_from_underlying(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda()#3}&&)::{lambda()#2}&>(flat_mutation_reader) at /home/scylla/scylla/./seastar/core/future.hh:1355
 (inlined by) {lambda()#3} seastar::do_until<seastar::future<> consume_mutation_fragments_until<cache::cache_flat_mutation_reader::read_from_underlying(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda()#1}, cache::cache_flat_mutation_reader::read_from_underlying(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda(mutation_fragment)#2}, cache::cache_flat_mutation_reader::read_from_underlying(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda()#3}>(flat_mutation_reader&, cache::cache_flat_mutation_reader::read_from_underlying(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda()#1}&&, cache::cache_flat_mutation_reader::read_from_underlying(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda(mutation_fragment)#2}&&, cache::cache_flat_mutation_reader::read_from_underlying(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda()#3}&&)::{lambda()#2}, {lambda()#3} consume_mutation_fragments_until<{lambda()#1}, mutation_fragment, {lambda(mutation_fragment)#2}>(seastar::future, flat_mutation_reader, {lambda()#1}, mutation_fragment)::{lambda()#1}>(flat_mutation_reader&, seastar::future<>) at /home/scylla/scylla/./seastar/core/future-util.hh:503
 (inlined by) seastar::future<> consume_mutation_fragments_until<cache::cache_flat_mutation_reader::read_from_underlying(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda()#1}, cache::cache_flat_mutation_reader::read_from_underlying(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda(mutation_fragment)#2}, cache::cache_flat_mutation_reader::read_from_underlying(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda()#3}>(flat_mutation_reader&, cache::cache_flat_mutation_reader::read_from_underlying(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda()#1}&&, cache::cache_flat_mutation_reader::read_from_underlying(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda(mutation_fragment)#2}&&, cache::cache_flat_mutation_reader::read_from_underlying(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda()#3}&&) at /home/scylla/scylla/flat_mutation_reader.hh:443
 (inlined by) cache::cache_flat_mutation_reader::read_from_underlying(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >) at /home/scylla/scylla/cache_flat_mutation_reader.hh:349
 (inlined by) cache::cache_flat_mutation_reader::do_fill_buffer(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda()#1}::operator()() const at /home/scylla/scylla/cache_flat_mutation_reader.hh:233
 (inlined by) seastar::apply_helper<cache::cache_flat_mutation_reader::do_fill_buffer(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda()#1}, std::tuple<>&&, std::integer_sequence<unsigned long> >::apply({lambda()#1}&&, std::tuple<>) at /home/scylla/scylla/./seastar/core/apply.hh:36
 (inlined by) auto seastar::apply<cache::cache_flat_mutation_reader::do_fill_buffer(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda()#1}>(cache::cache_flat_mutation_reader::do_fill_buffer(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda()#1}&&, std::tuple<>&&) at /home/scylla/scylla/./seastar/core/apply.hh:44
 (inlined by) seastar::future<> seastar::futurize<seastar::future<> >::apply<cache::cache_flat_mutation_reader::do_fill_buffer(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda()#1}>(cache::cache_flat_mutation_reader::do_fill_buffer(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda()#1}&&, std::tuple<>&&) at /home/scylla/scylla/./seastar/core/future.hh:1362
 (inlined by) seastar::future<> seastar::future<>::then<cache::cache_flat_mutation_reader::do_fill_buffer(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda()#1}, seastar::future<> >(cache::cache_flat_mutation_reader::do_fill_buffer(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda()#1}&&) at /home/scylla/scylla/./seastar/core/future.hh:932
 (inlined by) cache::cache_flat_mutation_reader::do_fill_buffer(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >) at /home/scylla/scylla/cache_flat_mutation_reader.hh:233
cache::cache_flat_mutation_reader::fill_buffer(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda()#3}::operator()() const at /home/scylla/scylla/cache_flat_mutation_reader.hh:222
 (inlined by) _ZN7seastar22do_void_futurize_applyIRZN5cache26cache_flat_mutation_reader11fill_bufferENSt6chrono10time_pointINS_12lowres_clockENS3_8durationIlSt5ratioILl1ELl1000EEEEEEEUlvE1_JEEENSt9enable_ifIXsrNS_9is_futureIJNSt9result_ofIFT_DpOT0_EE4typeEEEE5valueENS_6futureIJEEEE4typeEOSG_SJ_ at /home/scylla/scylla/./seastar/core/future.hh:1319
 (inlined by) seastar::future<> seastar::futurize<void>::apply<cache::cache_flat_mutation_reader::fill_buffer(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda()#3}&>(cache::cache_flat_mutation_reader::fill_buffer(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda()#3}&) at /home/scylla/scylla/./seastar/core/future.hh:1355
 (inlined by) seastar::future<> seastar::do_until<cache::cache_flat_mutation_reader::fill_buffer(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda()#3}, cache::cache_flat_mutation_reader::fill_buffer(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda()#2}>(cache::cache_flat_mutation_reader::fill_buffer(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda()#2}, cache::cache_flat_mutation_reader::fill_buffer(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda()#3}) at /home/scylla/scylla/./seastar/core/future-util.hh:503
 (inlined by) cache::cache_flat_mutation_reader::fill_buffer(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >) at /home/scylla/scylla/cache_flat_mutation_reader.hh:222
cache::cache_flat_mutation_reader::fill_buffer(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda()#1}::operator()() const at /home/scylla/scylla/cache_flat_mutation_reader.hh:211
 (inlined by) cache::cache_flat_mutation_reader::fill_buffer(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >) at /home/scylla/scylla/cache_flat_mutation_reader.hh:216
flat_mutation_reader::fill_buffer(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >) at /home/scylla/scylla/flat_mutation_reader.hh:348
 (inlined by) seastar::future<bool> flat_mutation_reader::impl::fill_buffer_from<flat_mutation_reader>(flat_mutation_reader&, std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >) at /home/scylla/scylla/flat_mutation_reader.cc:164
single_partition_populating_reader::fill_buffer(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda()#3}::operator()() const at /home/scylla/scylla/row_cache.cc:433
 (inlined by) _ZN7seastar22do_void_futurize_applyIRZN34single_partition_populating_reader11fill_bufferENSt6chrono10time_pointINS_12lowres_clockENS2_8durationIlSt5ratioILl1ELl1000EEEEEEEUlvE1_JEEENSt9enable_ifIXsrNS_9is_futureIJNSt9result_ofIFT_DpOT0_EE4typeEEEE5valueENS_6futureIJEEEE4typeEOSF_SI_ at /home/scylla/scylla/./seastar/core/future.hh:1319
 (inlined by) seastar::future<> seastar::futurize<void>::apply<single_partition_populating_reader::fill_buffer(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda()#3}&>(single_partition_populating_reader::fill_buffer(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda()#3}&) at /home/scylla/scylla/./seastar/core/future.hh:1355
 (inlined by) seastar::future<> seastar::do_until<single_partition_populating_reader::fill_buffer(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda()#3}, single_partition_populating_reader::fill_buffer(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda()#2}>(single_partition_populating_reader::fill_buffer(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda()#2}, single_partition_populating_reader::fill_buffer(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda()#3}) at /home/scylla/scylla/./seastar/core/future-util.hh:503
single_partition_populating_reader::fill_buffer(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >) at /home/scylla/scylla/row_cache.cc:438
single_partition_populating_reader::fill_buffer(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda()#1}::operator()() const at /home/scylla/scylla/row_cache.cc:429
 (inlined by) seastar::apply_helper<single_partition_populating_reader::fill_buffer(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda()#1}, std::tuple<>&&, std::integer_sequence<unsigned long> >::apply({lambda()#1}&&, std::tuple<>) at /home/scylla/scylla/./seastar/core/apply.hh:36
 (inlined by) auto seastar::apply<single_partition_populating_reader::fill_buffer(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda()#1}>(single_partition_populating_reader::fill_buffer(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda()#1}&&, std::tuple<>&&) at /home/scylla/scylla/./seastar/core/apply.hh:44
 (inlined by) seastar::future<> seastar::futurize<seastar::future<> >::apply<single_partition_populating_reader::fill_buffer(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda()#1}>(single_partition_populating_reader::fill_buffer(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda()#1}&&, std::tuple<>&&) at /home/scylla/scylla/./seastar/core/future.hh:1362
 (inlined by) _ZZN7seastar6futureIJEE4thenIZN34single_partition_populating_reader11fill_bufferENSt6chrono10time_pointINS_12lowres_clockENS4_8durationIlSt5ratioILl1ELl1000EEEEEEEUlvE_S1_EET0_OT_ENUlSF_E_clINS_12future_stateIJEEEEEDaSF_ at /home/scylla/scylla/./seastar/core/future.hh:943
 (inlined by) _ZN7seastar12continuationIZNS_6futureIJEE4thenIZN34single_partition_populating_reader11fill_bufferENSt6chrono10time_pointINS_12lowres_clockENS5_8durationIlSt5ratioILl1ELl1000EEEEEEEUlvE_S2_EET0_OT_EUlSG_E_JEE15run_and_disposeEv at /home/scylla/scylla/./seastar/core/future.hh:413
seastar::reactor::run_tasks(seastar::reactor::task_queue&) at /home/scylla/scylla/seastar/core/reactor.cc:2500
seastar::reactor::run_some_tasks() at /home/scylla/scylla/seastar/core/reactor.cc:2910
seastar::reactor::run_some_tasks() at /usr/include/c++/7/chrono:377
 (inlined by) seastar::reactor::run() at /home/scylla/scylla/seastar/core/reactor.cc:3057
seastar::smp::configure(boost::program_options::variables_map)::{lambda()#3}::operator()() const at /home/scylla/scylla/seastar/core/reactor.cc:4002
std::function<void ()>::operator()() const at /usr/include/c++/7/bits/std_function.h:706
 (inlined by) seastar::posix_thread::start_routine(void*) at /home/scylla/scylla/seastar/core/posix.cc:52
```

I had a conversation with @pdziepak today and my original intention was to suggest reviving the "LSA compation on idle" code. Now when we have a CPU scheduler we can make sure that idle-freeing is not in a way of requests processing (on-demand freeing should stay of course).

This particular test case is a very good demonstration why it is needed - most of the shards in this test are not exhausted and could have used their free cycles for compacting LSA and thereby minimizing (if not eliminating completely) the rate drop.

However after running the test on the master tree it seems that the issue is a lot worse than not utilizing those idle cycles.

**Comment by glommer** [comment] 2018-03-17 01:23
The real problem that I see here is this 2s stall.

@pdziepak what is your take here?

**Comment by glommer** [comment] 2018-03-17 13:31
@tgrabiec is that a duplicate of your complexity-of-row-eviction issue ?

**Comment by tgrabiec** [comment] 2018-03-19 10:57
@glommer It could be contributing to the problem.

**Comment by vladzcloudius** [comment] 2018-03-19 14:11
@glommer @pdziepak In think the 2s stall is just a symptom. When you use hit-the-wall algorithm instead of elastic one - stalls are quite expected.

**Comment by glommer** [comment] 2018-03-19 14:17
Stalls are never expected.

**Comment by vladzcloudius** [comment] 2018-03-19 14:49
@glommer They are never *desired* but when you start freeing memory only when you run out of it in the middle of handling the request that needs this memory - it will technically stall your coordinator shard until the replica shard frees the required memory. I'd say you should not be too surprised when you see them considering the above. 

Note that in this particular test all shards are both coordinators and replicas, so the fact that you see the replica-flow code in the trace maybe just accidental and doesn't contradict what I said above.
This doesn't mean that I'm 100% sure that this is what actually had happen there - it needs a deeper investigation. But IMHO it's a very likely scenario.

**Comment by tgrabiec** [comment] 2018-03-19 16:30
2018-03-19 15:49 GMT+01:00 vladzcloudius <notifications@github.com>:

> @glommer <https://github.com/glommer> They are never *desired* but when
> you start freeing memory only when you run out of it in the middle of
> handling the request that needs this memory - it will technically stall
> your coordinator shard until the replica shard frees the required memory.
> I'd say you should not be too surprised when you see them considering the
> above.
>

Even if we evict on demand, the stall should be proportional to amount of
memory requested. It shouldn't stall the reactor for as long as 2 seconds,
unless we're trying to allocate many GB in one go.

**Comment by vladzcloudius** [comment] 2018-03-19 16:48
@tgrabiec You are absolutely right - in the context of a single request and the zero-length queue of pending requests in addition to the one that caused the stall. Unfortunately, it's not the case here.

Consider a queue of, say, 2000 pending requests that suddenly have to wait for LSA compaction. 
The implementation you describe (when we try to free the amount of memory close to the one that is being requested) makes it even worse - each and every pending request will have to wait for its own compaction. And now think of the request that is at the end of the pending queue - it'll have to wait A LOT.

To remind, in this particular test case I was using the default c-s schema, which is 1 key column, 5 (AFAIR) data columns, single row per partition and the partition size of about 300 bytes.

**Comment by avikivity** [comment] 2021-06-22 13:32
This is long since fixed.

**Closed by avikivity** 2021-06-22 13:32 UTC
