### ISSUE TITLE
Hinted handoff sends counter hints as counter updates when node targeted by the hint does not exist

### ISSUE THREAD

**Issue by haaawk** [scylladb/scylla#5833] opened 2020-02-18 11:04 UTC
Counter mutations have two flavors: counter update and the total state of the counter.

Hints for counters are mutations that store the total state of the counter and should be treated as normal mutations. There is a corner case when hinted handoff misinterprets the counter hint mutation and treats it as counter update. As a result, a counter is updated with a value that is his state. This means the value is corrupted.

The problematic case happens when a node that's a destination for a hint is no longer in the cluster. In such a case, the hint is sent to all the remaining replicas. This code path wrongly uses storage_proxy::mutate which expects counter update mutation.

This problem can cause corruption in any counter shard because storage_proxy::mutate picks a leader for the update and it can be any replica.

The problem was partially fixed on master by https://github.com/scylladb/scylla/commit/01084a79b8f47f63aeb54bd110135f3850ad3fc8
We need to fix it fully with an additional fix.

**Comment by haaawk** [comment] 2020-02-18 11:05
@slivne @avikivity

**Comment by tzach** [comment] 2020-02-18 12:08
@haaawk look like its the root cause for #4505

**Comment by haaawk** [comment] 2020-02-18 12:12
Indeed @tzach

**Comment by avikivity** [comment] 2020-02-18 21:26
@piodul please provide a backport for branch-3.3.

**Comment by haaawk** [comment] 2020-02-18 21:38
Backport for this is here @avikivity ->https://github.com/scylladb/scylla/pull/5835

**Comment by haaawk** [comment] 2020-02-18 21:39
It's already approved by Gleb and me and waits for you :)

**Comment by avikivity** [comment] 2020-02-19 13:38
Committed as 434347195416cc79211e4b7df001f90b0f1aded7

**Closed by avikivity** 2020-02-19 13:38 UTC
Labels: Backport 3.1, Backport 3.3, Backport candidate, backport 3.2, counters, hinted-handoff

**Comment by avikivity** [comment] 2020-08-27 08:51
Already backported everywhere.
