### ISSUE TITLE
Aborting on shard and coredump during shutting down after enospace

### ISSUE THREAD

**Issue by juliayakovlev** [scylladb/scylla#10853] opened 2022-06-22 08:38 UTC
## Installation details

Kernel Version: 5.13.0-1029-aws
Scylla version (or git commit hash): `5.0~rc8-20220612.f28542a71` with build-id `85cf87619b93155a574647ec252ce5a043c7fe77`
Cluster size: 5 nodes (i3.4xlarge)

Scylla Nodes used in this run:
- longevity-mv-si-4d-5-0-db-node-2bed6bc8-6 (54.194.99.144 | 10.0.0.69) (shards: 14)
- longevity-mv-si-4d-5-0-db-node-2bed6bc8-5 (54.75.200.152 | 10.0.0.73) (shards: 14)
- longevity-mv-si-4d-5-0-db-node-2bed6bc8-4 (54.246.19.113 | 10.0.0.125) (shards: 14)
- longevity-mv-si-4d-5-0-db-node-2bed6bc8-3 (34.245.184.229 | 10.0.3.124) (shards: 14)
- longevity-mv-si-4d-5-0-db-node-2bed6bc8-2 (52.31.163.214 | 10.0.3.86) (shards: 14)
- longevity-mv-si-4d-5-0-db-node-2bed6bc8-1 (54.216.113.167 | 10.0.3.69) (shards: 14)

OS / Image: `ami-088626a20ac6084a7` (aws: eu-west-1)

Test: `longevity-mv-si-4days-test`
Test id: `2bed6bc8-ab13-4f0c-85a9-8fb94a501ded`
Test name: `scylla-5.0/longevity/longevity-mv-si-4days-test`
Test config file(s):

- [longevity-mv-si-4days.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/34bc3e72aed3eb1988cfe635a01c59c719493602/test-cases/longevity/longevity-mv-si-4days.yaml)

## Issue description

Aborting on shard and coredump when no space left on device:
```
2022-06-22T02:24:08+00:00 longevity-mv-si-4d-5-0-db-node-2bed6bc8-4 !    INFO |  [shard 7] migration_manager - stopping migration service
2022-06-22T02:24:17+00:00 longevity-mv-si-4d-5-0-db-node-2bed6bc8-4 !     ERR |  [shard 0] init - Unexpected error shutting down local storage: storage_io_error (Storage I/O error: 28: No space left on device): aborting
2022-06-22T02:24:17+00:00 longevity-mv-si-4d-5-0-db-node-2bed6bc8-4 !    INFO | Aborting on shard 0.
2022-06-22T02:24:17+00:00 longevity-mv-si-4d-5-0-db-node-2bed6bc8-4 !    INFO | Backtrace:
0x42c8f58
0x42f9a92
0x7f1717d32a1f
/opt/scylladb/libreloc/libc.so.6+0x3d2a1
/opt/scylladb/libreloc/libc.so.6+0x268a3
0x111b5a0
0x111b693
0x1031192
0xffe505
0xffe4f5
0xffe4e5
0xffe3c3
0x4549911
```

Decoded:
```
void seastar::backtrace<seastar::backtrace_buffer::append_backtrace()::{lambda(seastar::frame)#1}>(seastar::backtrace_buffer::append_backtrace()::{lambda(seastar::frame)#1}&&) at ./build/release/seastar/./seastar/include/seastar/util/backtrace.hh:59
 (inlined by) seastar::backtrace_buffer::append_backtrace() at ./build/release/seastar/./seastar/src/core/reactor.cc:750
 (inlined by) seastar::print_with_backtrace(seastar::backtrace_buffer&, bool) at ./build/release/seastar/./seastar/src/core/reactor.cc:780
seastar::print_with_backtrace(char const*, bool) at ./build/release/seastar/./seastar/src/core/reactor.cc:792
 (inlined by) seastar::sigabrt_action() at ./build/release/seastar/./seastar/src/core/reactor.cc:3672
 (inlined by) operator() at ./build/release/seastar/./seastar/src/core/reactor.cc:3654
 (inlined by) __invoke at ./build/release/seastar/./seastar/src/core/reactor.cc:3650
?? ??:0
/data/scylla-s3-reloc.cache/by-build-id/85cf87619b93155a574647ec252ce5a043c7fe77/extracted/scylla/libexec/scylladb/libreloc/libc.so.6 0x3d2a1 
/data/scylla-s3-reloc.cache/by-build-id/85cf87619b93155a574647ec252ce5a043c7fe77/extracted/scylla/libexec/scylladb/libreloc/libc.so.6 0x268a3 
operator() at ./main.cc:391
 (inlined by) ~deferred_action at ././seastar/include/seastar/util/defer.hh:63
~shared_ptr_count_for at ././seastar/include/seastar/core/shared_ptr.hh:464
 (inlined by) ~shared_ptr_count_for at ././seastar/include/seastar/core/shared_ptr.hh:464
operator() at ./main.cc:1475
int std::__invoke_impl<int, scylla_main(int, char**)::$_2::operator()() const::{lambda()#2}>(std::__invoke_other, scylla_main(int, char**)::$_2::operator()() const::{lambda()#2}&&) at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/invoke.h:61
std::__invoke_result<scylla_main(int, char**)::$_2::operator()() const::{lambda()#2}>::type std::__invoke<scylla_main(int, char**)::$_2::operator()() const::{lambda()#2}>(std::__invoke_result&&, (scylla_main(int, char**)::$_2::operator()() const::{lambda()#2}&&)...) at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/invoke.h:96
decltype(auto) std::__apply_impl<scylla_main(int, char**)::$_2::operator()() const::{lambda()#2}, std::tuple<>>(scylla_main(int, char**)::$_2::operator()() const::{lambda()#2}&&, std::tuple<>&&, std::integer_sequence<unsigned long>) at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/tuple:1843
decltype(auto) std::apply<scylla_main(int, char**)::$_2::operator()() const::{lambda()#2}, std::tuple<> >(scylla_main(int, char**)::$_2::operator()() const::{lambda()#2}&&, std::tuple<>&&) at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/tuple:1854
 (inlined by) seastar::future<int> seastar::futurize<int>::apply<scylla_main(int, char**)::$_2::operator()() const::{lambda()#2}>(scylla_main(int, char**)::$_2::operator()() const::{lambda()#2}&&, std::tuple<>&&) at ././seastar/include/seastar/core/future.hh:2104
 (inlined by) operator() at ././seastar/include/seastar/core/thread.hh:258
 (inlined by) seastar::noncopyable_function<void ()>::direct_vtable_for<seastar::async<scylla_main(int, char**)::$_2::operator()() const::{lambda()#2}>(seastar::thread_attributes, std::invoke_result&&, (scylla_main(int, char**)::$_2::operator()() const::{lambda()#2}&&)...)::{lambda()#1}>::call(seastar::noncopyable_function<void ()> const*) at ././seastar/include/seastar/util/noncopyable_function.hh:124
seastar::noncopyable_function<void ()>::operator()() const at ./build/release/seastar/./seastar/include/seastar/util/noncopyable_function.hh:209
 (inlined by) seastar::thread_context::main() at ./build/release/seastar/./seastar/src/core/thread.cc:299
```

Coredump:
```
corefile_url=https://storage.cloud.google.com/upload.scylladb.com/core.scylla.113.966c8dc3268e4b72bf732348ab61d249.11850.1655864657000000000000/core.scylla.113.966c8dc3268e4b72bf732348ab61d249.11850.165586465700
0000000000.gz
backtrace=           PID: 11850 (scylla)
           UID: 113 (scylla)
           GID: 119 (scylla)
        Signal: 6 (ABRT)
     Timestamp: Wed 2022-06-22 02:24:17 UTC (4min 37s ago)
  Command Line: /usr/bin/scylla --blocked-reactor-notify-ms 100 --abort-on-lsa-bad-alloc 1 --abort-on-seastar-bad-alloc --abort-on-internal-error 1 --abort-on-ebadf 1 --enable-sstable-key-validation 1 --log-to-s
yslog 1 --log-to-stdout 0 --default-log-level info --network-stack posix --io-properties-file=/etc/scylla.d/io_properties.yaml --cpuset 1-7,9-15 --lock-memory=1
    Executable: /opt/scylladb/libexec/scylla
 Control Group: /scylla.slice/scylla-server.slice/scylla-server.service
          Unit: scylla-server.service
         Slice: scylla-server.slice
       Boot ID: 966c8dc3268e4b72bf732348ab61d249
    Machine ID: 5d2475573d394cdc83210b55935472f3
      Hostname: longevity-mv-si-4d-5-0-db-node-2bed6bc8-4
       Storage: /var/lib/systemd/coredump/core.scylla.113.966c8dc3268e4b72bf732348ab61d249.11850.1655864657000000000000
       Message: Process 11850 (scylla) of user 113 dumped core.
                
                Stack trace of thread 11850:
                #0  0x00007f17171772a2 raise (libc.so.6 + 0x3d2a2)
                #1  0x00007f1717160950 abort (libc.so.6 + 0x26950)
                #2  0x000000000111b5a1 _ZN7seastar15deferred_actionIZL22defer_verbose_shutdownIZZZL11scylla_mainiPPcENK3$_2clEvENKUlvE0_clEvEUlvE66_EDaPKcOT_EUlvE_ED2Ev (scylla + 0xf1b5a1)
                #3  0x000000000111b694 _ZN7seastar20shared_ptr_count_forINS_15deferred_actionIZL22defer_verbose_shutdownIZZZL11scylla_mainiPPcENK3$_2clEvENKUlvE0_clEvEUlvE66_EDaPKcOT_EUlvE_EEED0Ev (scylla + 0xf1
b694)
                #4  0x0000000001031193 _ZZZL11scylla_mainiPPcENK3$_2clEvENKUlvE0_clEv (scylla + 0xe31193)
                #5  0x0000000000ffe506 _ZSt13__invoke_implIiZZL11scylla_mainiPPcENK3$_2clEvEUlvE0_JEET_St14__invoke_otherOT0_DpOT1_ (scylla + 0xdfe506)
                #6  0x0000000000ffe4f6 _ZSt8__invokeIZZL11scylla_mainiPPcENK3$_2clEvEUlvE0_JEENSt15__invoke_resultIT_JDpT0_EE4typeEOS5_DpOS6_ (scylla + 0xdfe4f6)
                #7  0x0000000000ffe4e6 _ZSt12__apply_implIZZL11scylla_mainiPPcENK3$_2clEvEUlvE0_St5tupleIJEEJEEDcOT_OT0_St16integer_sequenceImJXspT1_EEE (scylla + 0xdfe4e6)
                #8  0x0000000000ffe3c4 _ZN7seastar20noncopyable_functionIFvvEE17direct_vtable_forIZNS_5asyncIZZL11scylla_mainiPPcENK3$_2clEvEUlvE0_JEEENS_8futurizeINSt13invoke_resultIT_JDpT0_EE4typeEE4typeENS_17thread_attributesEOSB_DpOSC_EUlvE_E4callEPKS2_ (scylla + 0xdfe3c4)
                #9  0x0000000004549912 _ZN7seastar14thread_context4mainEv (scylla + 0x4349912)
                
                Stack trace of thread 11866:
                #0  0x00007f1717d3194c read (libpthread.so.0 + 0x1294c)
                #1  0x000000000431c2e5 _ZN7seastar11thread_pool4workENS_13basic_sstringIcjLj15ELb1EEE (scylla + 0x411c2e5)
                #2  0x000000000431c650 _ZNSt17_Function_handlerIFvvEZN7seastar11thread_poolC1EPNS1_7reactorENS1_13basic_sstringIcjLj15ELb1EEEE3$_0E9_M_invokeERKSt9_Any_data (scylla + 0x411c650)
                #3  0x00000000042addeb _ZN7seastar12posix_thread13start_routineEPv (scylla + 0x40addeb)
                #4  0x00007f1717d28299 start_thread (libpthread.so.0 + 0x9299)
                #5  0x00007f171723a353 __clone (libc.so.6 + 0x100353)
```

download_instructions:
```
gsutil cp gs://upload.scylladb.com/core.scylla.113.966c8dc3268e4b72bf732348ab61d249.11850.1655864657000000000000/core.scylla.113.966c8dc3268e4b72bf732348ab61d249.11850.1655864657000000000000.gz .
gunzip /var/lib/systemd/coredump/core.scylla.113.966c8dc3268e4b72bf732348ab61d249.11850.1655864657000000000000.gz
```

Scenario:

enospace nemesis:
```
2022-06-22 02:21:21.216: (DisruptionEvent Severity.NORMAL) period_type=begin event_id=6494b0c5-5dd9-444d-a3fe-d8d0548b3519: nemesis_name=NodetoolEnospc target_node=Node longevity-mv-si-4d-5-0-db-node-2bed6bc8-4 [54.246.19.113 | 10.0.0.125] (seed: False)
```

During the nemesis were created  files that occuped 90% of space. Then the files are removed:
```
2022-06-22T02:23:52+00:00 longevity-mv-si-4d-5-0-db-node-2bed6bc8-4 !  NOTICE | scyllaadm : TTY=unknown ; PWD=/home/scyllaadm ; USER=root ; COMMAND=/usr/bin/rm -rf /var/lib/scylla/occupy_90percent.1655864482.1120672 /var/lib/scylla/occupy_90percent.1655864488.150746 /var/lib/scylla/occupy_90percent.1655864494.2231016 /var/lib/scylla/occupy_90percent.1655864500.2354429 /var/lib/scylla/occupy_90percent.1655864506.2511044 /var/lib/scylla/occupy_90percent.1655864512.2743645 /var/lib/scylla/occupy_90percent.1655864518.3543992 /var/lib/scylla/occupy_90percent.1655864524.3958392 /var/lib/scylla/occupy_90percent.1655864530.41146 /var/lib/scylla/occupy_90percent.1655864536.4817708 /var/lib/scylla/occupy_90percent.1655864542.5112574 /var/lib/scylla/occupy_90percent.1655864548.5393882 /var/lib/scylla/occupy_90percent.1655864554.6214187 /var/lib/scylla/occupy_90percent.1655864560.642862 /var/lib/scylla/occupy_90percent.1655864566.6579204 /var/lib/scylla/occupy_90percent.1655864572.7165709
```

And Scylla was restarted (`systemctl restart`):
```
2022-06-22T02:24:07+00:00 longevity-mv-si-4d-5-0-db-node-2bed6bc8-4 !    INFO | Stopping Scylla JMX...
2022-06-22T02:24:08+00:00 longevity-mv-si-4d-5-0-db-node-2bed6bc8-4 !  NOTICE | scylla-jmx.service: Main process exited, code=exited, status=143/n/a
2022-06-22T02:24:08+00:00 longevity-mv-si-4d-5-0-db-node-2bed6bc8-4 ! WARNING | scylla-jmx.service: Failed with result 'exit-code'.
2022-06-22T02:24:08+00:00 longevity-mv-si-4d-5-0-db-node-2bed6bc8-4 !    INFO | Stopped Scylla JMX.
2022-06-22T02:24:08+00:00 longevity-mv-si-4d-5-0-db-node-2bed6bc8-4 !    INFO |  [shard 0] compaction_manager - Asked to stop
2022-06-22T02:24:08+00:00 longevity-mv-si-4d-5-0-db-node-2bed6bc8-4 !    INFO | Stopping Scylla Server...
```

During shutdown (stopping migration service) received unexpected error, aborting on shard and coredump:
```
2022-06-22T02:24:08+00:00 longevity-mv-si-4d-5-0-db-node-2bed6bc8-4 !    INFO |  [shard 7] migration_manager - stopping migration service
2022-06-22T02:24:17+00:00 longevity-mv-si-4d-5-0-db-node-2bed6bc8-4 !     ERR |  [shard 0] init - Unexpected error shutting down local storage: storage_io_error (Storage I/O error: 28: No space left on device): aborting
```

Test still is running.
Monitor:
http://16.170.231.120:3000/d/manager-2-6/longevity-50gb-3days-aws-i4i-test-scylla-per-server-metrics-nemesis-master?orgId=1&from=1655808202000&to=now

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-5.0/job/longevity/job/longevity-mv-si-4days-test/3/)

**Comment by slivne** [comment] 2022-06-23 11:06
@bhalevy please check this out - I marked it as high - yet it will not block on master we fixed an issue related to shutdown and enospc as well.

**Comment by bhalevy** [comment] 2022-06-23 11:17
Duplicate of https://github.com/scylladb/scylla/issues/10205

**Closed by bhalevy** 2022-06-23 11:17 UTC
Labels: bug, high

**Comment by roydahan** [comment] 2022-06-27 13:52
@slivne / @bhalevy are we going to backport it to 5.0?

**Comment by juliayakovlev** [comment] 2022-06-30 08:59
@slivne @bhalevy are we going to backport it to 5.0?

**Comment by bhalevy** [comment] 2022-06-30 10:56
#9573 is a backport candidate and I don't see why not backport it.
it fixes an issue and is low risk.
