### ISSUE TITLE
Validate / Fix SSTable tools

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#1151] opened 2016-03-31 08:39 UTC
Cassandra include the following tools to handle SSTables:

- json2sstable
- sstable2json
- sstablelevelreset
- sstablemetadata
- sstableofflinerelevel
- sstablerepairedset
- sstablesplit

Since Scylla SSTable format is compatible, all tools *should* work, but some have known issues[1] 
We should test the tool, validate Scylla compatibility and fix the issues.

[1] https://issues.apache.org/jira/browse/CASSANDRA-8616

**Comment by slivne** [comment] 2016-04-04 06:07
I think that some of them are covered by dtest - need to enable (if a test exists) or create at least a single test for each of this tools in dtest for regression

**Comment by duarten** [comment] 2016-05-10 10:43
There are dtests covering these tools.

- json_tools_test.py covers sstable2json and json2sstable.
- offline_tools_test.py covers offline_tools_test.py, sstablemetadata and sstableofflinerelevel.
- incremental_repair_test.py covers sstablerepairedset.
- sstablesplit_test.py covers sstablesplit.

Working on enabling them.

**Comment by tzach** [comment] 2016-06-07 09:50
@duarten any update?

**Comment by duarten** [comment] 2016-06-07 10:03
@tzach No, I shifted to thrift. I had started looking into json_tools_test but didn't make much progress.

**Comment by duarten** [comment] 2016-07-29 10:34
I've enabled json_tools_test, offline_tools_test and sstablesplit_test. We apparently don't support incremental repair, so I didn't enable incremental_repair_test.

I think we should keep an eye on CASSANDRA-8616 because it seems some of these tools will be re-written.

**Comment by duarten** [comment] 2016-08-22 21:20
Can this one be closed?

**Comment by tzach** [comment] 2016-08-31 11:47
@duarten are the tool part of the scylla packages (scylla-tools?)

**Comment by duarten** [comment] 2016-08-31 11:49
@tzach Yep.

**Comment by penberg** [comment] 2016-09-07 15:21
`sstablelevelreset` dtest is still failing in master, so let's not close the issue just yet.

**Comment by duarten** [comment] 2016-09-16 16:25
Quoting myself:

> `sstableofflinerelevel_test` fails when smp > 1. This is because it estimates the number of levels in a set of sstables, like so:
> 
> ```java approxExpectedLevels = (int) Math.ceil(Math.log10(sstables.size()));```
> 
> This is broken when smp > 1. A fix would be to modify the tool to receive the number of smps Scylla was using when running, although this would make it kind of brittle.

@raphaelsc, do you know why they use log10 to estimate the number of sstable levels? Is this there a good way to get the estimate without passing in the number of smp Scylla was configures with when it ran?

The relevant code is in SSTableOfflineRelevel.java.

**Comment by raphaelsc** [comment] 2016-09-16 19:58
On Fri, Sep 16, 2016 at 1:25 PM, Duarte Nunes <notifications@github.com>
wrote:

> Quoting myself:
>
> sstableofflinerelevel_test fails when smp > 1. This is because it
> estimates the number of levels in a set of sstables, like so:
>
> java approxExpectedLevels = (int) Math.ceil(Math.log10(sstables.size()));
>
> This is broken when smp > 1. A fix would be to modify the tool to receive
> the number of smps Scylla was using when running, although this would make
> it kind of brittle.
>
> @raphaelsc <https://github.com/raphaelsc>, do you know why they use log10
> to estimate the number of sstable levels?
>
Each level N, where N > 0, is limited to 10^N sstables.


> Is this there a good way to get the estimate without passing in the number
> of smp Scylla was configures with when it ran?
>
I wonder why the calculation above doesn't work for smp > 1. If we had at
least one sstable on a given shard, approxExpectedLevels would be 1, right?
Are we choosing a random shard to get approximate levels from? I'll read
the relevant code soon.

**Comment by duarten** [comment] 2016-09-18 18:30
That's a C* tool, so it has no knowledge about the shards. I think that's the problem with the calculation above: levels are per shard and not global. Or is that not the case?

**Comment by raphaelsc** [comment] 2016-09-19 18:51
On Sun, Sep 18, 2016 at 3:30 PM, Duarte Nunes <notifications@github.com>
wrote:

> That's a C* tool, so it has no knowledge about the shards. I think that's
> the problem with the calculation above: levels are per shard and not
> global. Or is that not the case?
>
It's true. The tool will work as if all sstables are from the same shard,
but they aren't. There will be overlap in sstables of level N (where N > 0)
that belong to different shards. It's hard though to teach this tool about
our sharding mechanism.

**Comment by duarten** [comment] 2016-09-19 19:14
Right, that was what I thought. I don't think we can recover sharding information from the sstables, so the only option would be to pass the tool the number of shards Scylla ran with. Or we decide to not support this tool.

**Comment by slivne** [comment] 2016-09-26 06:02
Lets drop the sstableofflinerelevel tool for now and not ship it.

It seems to me that if the tool tries to updates the levels of the files without knowing sharding information then it can cause more grief then good.

**Comment by slivne** [comment] 2016-10-02 11:38
sstableofflinerelevel was removed - all the rest was added

**Comment by tzach** [comment] 2016-10-10 08:51
@slivne can we mark as fixed?

**Comment by slivne** [comment] 2016-10-10 09:24
Nope there are patches on the list that fix some issues - till they go in
the issue can not be closed.

**Comment by slivne** [comment] 2016-10-13 14:36
checked on 1.4-rc2

**Closed by slivne** 2016-10-13 14:36 UTC
Labels: enhancement, fixed
