### ISSUE TITLE
disrupt_nodetool_refresh fails with error sstables::malformed_sstable_exception on 3.1

### ISSUE THREAD

**Issue by fgelcer** [scylladb/scylla#4622] opened 2019-06-30 07:59 UTC
it was observed during longevity 4h (multiple times) for scylla 3.1.

latest seen on [job from June 26th](https://jenkins.scylladb.com/view/scylla-3.1/job/scylla-3.1/job/longevity/job/longevity-100gb-4h/25/)

tar ball with files to be loaded to the DB attached.

the nemesis executes those steps:

1. download the file from S3 [keyspace1.standard1.tar.gz](https://github.com/scylladb/scylla/files/3342644/keyspace1.standard1.tar.gz)
2. check if keyspace1.standard1 exists
3. find the latest "data" file on /var/lib/scylla/data/keyspace1/
4. untar file to data folder
5. run command "nodetool --host localhost refresh -- keyspace1 standard1"
6. check if content was loaded to the DB

the disruption fails on step 5 with following error:
```
2019-06-26 07:55:41,830 remote           L0682 INFO | RemoteCmdRunner [centos@172.30.0.71]: nodetool: Scylla API server HTTP POST to URL '/storage_service/sstables/keyspace1' failed: Failed to load new sstables: sstables::malformed_sstable_exception (/var/lib/scylla/data/keyspace1/standard1-4ec0213097e511e98877000000000000/mc-142-big-TOC.txt: file not found)
2019-06-26 07:55:41,831 remote           L0682 INFO | RemoteCmdRunner [centos@172.30.0.71]: See 'nodetool help' or 'nodetool help <command>'.
2019-06-26 07:55:41,870 remote           L0140 INFO | RemoteCmdRunner [centos@172.30.0.71]: Command "nodetool --host localhost refresh -- keyspace1 standard1" finished with status 1
2019-06-26 07:55:41,870 nemesis          L0177 ERROR| sdcm.nemesis.ChaosMonkey: nodetool command 'nodetool --host localhost refresh -- keyspace1 standard1' failed on node Node longevity-100gb-4h-3-1-db-node-837e847a-3 [3.89.215.22 | 172.30.0.71] (seed: False): Command exited with status 1.
=== stdout ===
nodetool: Scylla API server HTTP POST to URL '/storage_service/sstables/keyspace1' failed: Failed to load new sstables: sstables::malformed_sstable_exception (/var/lib/scylla/data/keyspace1/standard1-4ec0213097e511e98877000000000000/mc-142-big-TOC.txt: file not found)
See 'nodetool help' or 'nodetool help <command>'.
```

**Comment by bhalevy** [comment] 2019-07-08 10:46
Need more info to determine the cause.
Please leave cluster up once reproduced.

**Comment by slivne** [comment] 2019-07-08 10:54
@roydahan need more info

**Comment by roydahan** [comment] 2019-07-08 11:34
@fgelcer is trying to reproduce with the latest AMI running the 4h longevity with refresh nemesis only.

**Comment by bentsi** [comment] 2019-07-08 16:00
hit this on 3.0.8 with multiple nemesis run:

```
Jul 08 12:55:03 ip-10-0-77-167.eu-west-1.compute.internal scylla[8336]:  [shard 2] seastar - Exceptional 
future ignored: sstables::malformed_sstable_exception (/var/lib/scylla/data/keyspace1/standard1-65d44510a17011e993bf000000000005/la-24373-big-TOC.txt: file not found)
```
decoded backtrace
```
[root@ip-10-0-77-167 centos]# addr2line -Cpife /usr/bin/scylla
0x7cf328
0x5a4734
0x612b52
0x5a302e
0x5a31f1
0x671887
0x675ffa
0x75908d
/lib64/libpthread.so.0+0x7dd4
/lib64/libc.so.6+0xfdeac
backtrace<seastar::current_backtrace()::<lambda(seastar::frame)> > at /usr/src/debug/scylla-3.0.8/seastar/util/backtrace.hh:56
 (inlined by) seastar::current_backtrace() at /usr/src/debug/scylla-3.0.8/seastar/util/backtrace.cc:84
seastar::report_failed_future(std::__exception_ptr::exception_ptr) at /usr/src/debug/scylla-3.0.8/seastar/core/reactor.cc:4560
seastar::promise<>::abandoned() at /usr/src/debug/scylla-3.0.8/seastar/core/future.hh:1270
 (inlined by) seastar::promise<>::~promise() at /usr/src/debug/scylla-3.0.8/seastar/core/future.hh:459
 (inlined by) ~<lambda> at /usr/src/debug/scylla-3.0.8/seastar/core/future.hh:959
 (inlined by) ~continuation at /usr/src/debug/scylla-3.0.8/seastar/core/future.hh:410
 (inlined by) ~continuation at /usr/src/debug/scylla-3.0.8/seastar/core/future.hh:410
 (inlined by) run_and_dispose at /usr/src/debug/scylla-3.0.8/seastar/core/future.hh:415
seastar::reactor::run_tasks(seastar::reactor::task_queue&) at /usr/src/debug/scylla-3.0.8/seastar/core/reactor.cc:2695
seastar::reactor::run_some_tasks() at /usr/src/debug/scylla-3.0.8/seastar/core/reactor.cc:3118
seastar::reactor::run_some_tasks() at /usr/src/debug/scylla-3.0.8/seastar/util/log.hh:313
 (inlined by) seastar::reactor::run() at /usr/src/debug/scylla-3.0.8/seastar/core/reactor.cc:3265
operator() at /usr/src/debug/scylla-3.0.8/seastar/core/reactor.cc:4334
std::function<void ()>::operator()() const at /opt/scylladb/include/c++/7/bits/std_function.h:706
 (inlined by) seastar::posix_thread::start_routine(void*) at /usr/src/debug/scylla-3.0.8/seastar/core/posix.cc:52
?? ??:0
?? ??:0

```
Link to [monitor](http://34.249.131.95:3000/d/ZT4h5FIZz/scylla-per-server-metrics-nemesis-3-0?orgId=1&from=1562590125925&to=1562591033889&var-by=instance&var-cluster=&var-dc=All&var-node=All&var-shard=All). Cluster is currently alive

**Comment by fgelcer** [comment] 2019-07-08 18:17
i was able to reproduce it as well, my the cluster is still alive, and the link to the jenkins job can be found [here](http://jenkins.scylladb.com/job/scylla-staging/job/fabio/job/fabio-longevity-4h-nodetool-refresh-reproducer/2/), even though the jenkins job finished with success, there are many failures such as the one in this issue.

also, i have changed the original longevity 4h (in the link attached [here](http://jenkins.scylladb.com/job/scylla-staging/job/fabio/job/fabio-longevity-4h-nodetool-refresh-reproducer/2/)) to run for the same 4 hours, to keep the cluster after execution and to run only the nodetool_refresh nemesis.

**Comment by fgelcer** [comment] 2019-07-08 18:17
@bhalevy , what else do you need?

**Comment by roydahan** [comment] 2019-07-09 09:52
@fgelcer please provide the sstables also.
@bentsi, does it run on 3.0.8 with mc?

**Comment by bhalevy** [comment] 2019-07-09 13:40
[3.89.90.214.log](https://github.com/scylladb/scylla/files/3373186/3.89.90.214.log)
collected using journalctl. It looks like compaction keeps running while sstables are being loaded and it confuses `table::reshuffle_sstables` 

@raphaelsc please look into the log, does that make sense?
I'm not sure how that's supposed to work... although `storage_service::load_new_sstables` calls `cf.disable_sstable_write`, it doesn't stop compaction.

**Comment by fgelcer** [comment] 2019-07-09 13:52
@roydahan , i have terminated my cluster, as Benny has made some first investigation and mentioned he doesn't need it for now.
Maybe @bentsi could provide to Benny access to his cluster, to verify it is a similar/same issue, and then we can terminate the other cluster as well.

**Comment by bhalevy** [comment] 2019-07-09 14:09
cc @glommer

**Comment by glommer** [comment] 2019-07-09 14:27
My hunch is that this is related to file format changing in the middle.

The refresh process does a variety of links and maybe it expects the TOC as `mc` and it is there as `la`.

Could this be related?

**Comment by bhalevy** [comment] 2019-07-09 14:34
> My hunch is that this is related to file format changing in the middle.
> 
> The refresh process does a variety of links and maybe it expects the TOC as `mc` and it is there as `la`.
> 
> Could this be related?

@glommer we deduce the dir, sstable format, generation number, component type, etc. from the filename, and then load the toc using a sstable object we create based on the deduced sstable attributes.
I believe we fail here in `read_toc`:
https://github.com/scylladb/scylla/blob/c2940001132ce3d770d2cea7823e0d7bdf61de98/table.cc#L1032-L1054

**Comment by raphaelsc** [comment] 2019-07-10 06:23
@bhalevy we grab sstable lock for write, so all ongoing compactions are supposed to be waited on. I believe we actually fail in set_generation(), when creating links.

**Comment by raphaelsc** [comment] 2019-07-10 06:26
Those files in keyspace1.standard1.tar.gz use ka version, so I think @glommer is probably right.

**Comment by raphaelsc** [comment] 2019-07-10 08:25
So Benny and I found out that the problem was that we don't wait for compaction to actually remove files from disk because it's done in background. disable_sstable_write() needs to be patched to take into account _sstable_deletion_gate.

**Comment by bhalevy** [comment] 2019-07-10 08:37
@raphaelsc and I analysed the relevant code path and it seems like the problem is with lack of synchronization between sstable deletions done in the background, originated by `table::on_compaction_completion` and `table::reshuffle_sstables` that scans the data directory (called from `storage_service::load_new_sstables` after `disable_sstable_write()` on all shards.

The fix should be to also acquire `_sstable_deletion_sem` before `reshuffle_sstables`.

**Comment by slivne** [comment] 2019-07-16 10:13
Pull request waiting to be merged https://github.com/scylladb/scylla/pull/4691

**Closed** 2019-07-17 18:51 UTC
Labels: Backport candidate, bug, high
