### ISSUE TITLE
Scylla hanging on shutdown?

### ISSUE THREAD

**Issue by kbr-** [scylladb/scylla#7934] opened 2021-01-19 16:29 UTC
Observed in:

https://jenkins.scylladb.com/view/nexts/job/scylla-master/job/next/3072/consoleText
https://jenkins.scylladb.com/view/nexts/job/scylla-master/job/next/3072/artifact/testlog/debug/cdc_disallow_nested_cdc_logs_test.414.log

```
11:10:23  [458/459] boost/row_cache_test                                debug   [ PASS ] 1578.14s
14:18:36  [459/459] cql/cdc_disallow_nested_cdc_logs_test               debug   [ FAIL ]
```

The test was killed because Scylla hanged on shutdown:
```
INFO  2021-01-19 09:58:49,035 [shard 0] gossip - My status = NORMAL
INFO  2021-01-19 09:58:49,035 [shard 0] gossip - Announcing shutdown
INFO  2021-01-19 09:58:49,039 [shard 0] gossip - Disable and wait for gossip loop started
INFO  2021-01-19 09:58:49,040 [shard 0] gossip - Disable and wait for gossip loop finished
INFO  2021-01-19 09:58:49,041 [shard 0] gossip - Gossip is now stopped
INFO  2021-01-19 09:58:49,043 [shard 0] compaction - [Compact system_schema.scylla_tables ed0cd1b0-5a3c-11eb-8a11-000000000000] Compacted 2 sstables to [/jenkins/workspace/scylla-master/next/scylla/testlog/debug/scylla-883cf205-84a8-4947-838f-e0648c93533f/system_schema/scylla_tables-5d912ff1f7593665b2c88042ab5103dd/md-11-big-Data.db:level=0, ]. 11kB to 6kB (~53% of original) in 299ms = 20kB/s. ~256 total partitions merged to 3.
INFO  2021-01-19 09:58:49,058 [shard 0] compaction_manager - Asked to stop
INFO  2021-01-19 09:58:49,059 [shard 0] compaction_manager - Stopping 0 ongoing compactions
=== TEST.PY SUMMARY START ===
Test timed out
=== TEST.PY SUMMARY END ===
```

Not known if it's related to CDC or not.
Not known how to reproduce yet.

**Comment by piodul** [comment] 2021-01-20 09:15
I couldn't reproduce it locally. I compiled the test in debug mode and ran it on my machine overnight 20,000 times (2000 runs, 10 parallel executions each), but it passed every single time.

Scylla version used: 94749b01eb40b4f3e8ebf8a05673256806199b98 (this commit ID appears in logs of the Jenkins run)

**Comment by avikivity** [comment] 2021-01-20 09:47
Closing as not reproducible.

**Closed by avikivity** 2021-01-20 09:47 UTC
Labels: bug, shutdown
