### ISSUE TITLE
Scylla AMI wrong seed address in the cluster

### ISSUE THREAD

**Issue by nirmaayan** [scylladb/scylla#1523] opened 2016-07-31 12:43 UTC
Scylla version (or git commit hash): 1.3 RC!
Cluster size: 3 
EC2 AWS centos 7.2

Create 3 node cluster using AWS GUI
Add the 

> --clustername test-cluster
> --totalnodes 3

See - getting [started instructions](http://www.scylladb.com/doc/getting-started-amazon/) 

Checking under /etc/scylla/scylla/scylla.yaml 
For 2 nodes the seeding point was 172.31.23.48
For the other the seed was 172.31.23.46

This issue is inconsistent, happens 1 out of 10 times~

![seed](https://cloud.githubusercontent.com/assets/18263247/17276486/b689ba88-5733-11e6-88e0-3561f7999bbf.png)

**Comment by tzach** [comment] 2016-07-31 17:06
Look like the  reflector is working
```
~$ curl "http://reflector.scylladb.com/reflector.php?indexid=0&reservationid=171&internalip=100.100.100.100&externaldns=200.200.200.200&second_seed_index=1&third_seed_index=2"
{"number_of_returned_ips":1,"opscenter_dns":"200.200.200.200","seeds":["100.100.100.100"]}~$ 
~$ 
~$ curl "http://reflector.scylladb.com/reflector.php?indexid=1&reservationid=171&internalip=100.100.100.101&externaldns=200.200.200.201&second_seed_index=1&third_seed_index=2"
{"number_of_returned_ips":2,"opscenter_dns":"200.200.200.201","seeds":["100.100.100.100","100.100.100.101"]}
```

**Comment by tzach** [comment] 2016-08-01 07:59
@slivne can you take a look?

**Comment by tzach** [comment] 2016-08-02 16:54
@nirmaayan one reason might be micro t2.micro take so long to start, they are missing each other.
The reflector has 5 min window to correlate between server. Please try to reproduce, and from the logs, see if all server interacts with the reflector in the same 5 min window.

Make sure to use a different cluster name each time, making sure the cluster are not mixing with each other

**Comment by nirmaayan** [comment] 2016-08-03 12:50
Setup - all instances created manually using AWS GUI.
Some of them created using spot and other not.

Instances:
t2.micro
i2.8xlarge (only spot)
c4.8xlarge
c3.large
m3.medium


Steps - 1

1. Manually create the cluster
2. Add: --clustername test-cluster --totalnodes 3
3. Verify under 

> /etc/scylla/scylla/scylla.yaml that there is only one seed
Steps - 2

1. Manually create the cluster
2. Add: --clustername <randon_name> --totalnodes 3
3. Verify under 

> /etc/scylla/scylla/scylla.yaml that there is only one seed

Results are the same - there was always one seed
Need to continue and look for scenario

**Comment by tzach** [comment] 2016-08-03 17:49
@nirmaayan what is the difference between the steps? using or not using cluster name?

Since we failed to reproduce on many instance types, I'm closing this issue till we have a use case who do fail.

**Closed by tzach** 2016-08-03 17:49 UTC
Labels: showstopper

**Comment by nirmaayan** [comment] 2016-08-03 18:10
Yes, for some reason the (random name) diapered
