### ISSUE TITLE
dist: scylla_setup non-interactive mode always fails at ntp setup, even it's looks like succeed 

### ISSUE THREAD

**Issue by syuu1228** [scylladb/scylla#3479] opened 2018-06-01 20:35 UTC
Looks like this commit https://github.com/scylladb/scylla/commit/300af655554e9a50bf33e8271e188d715737bc88 is incorrect, need to fix.

```
syuu@takuya-xenial3:~$ sudo  scylla_setup --nic ens4 --no-cpuscaling-setup --no-raid-setup
Skip any of the following steps by answering 'no'
This is a supported kernel version.
Synchronizing state of collectd.service with SysV init with /lib/systemd/systemd-sysv-install...
Executing /lib/systemd/systemd-sysv-install enable collectd
Unable to retrieve version information
scylla_selinux_setup only supports Red Hat variants
Reading package lists... Done
Building dependency tree       
Reading state information... Done
ntp is already the newest version (1:4.2.8p4+dfsg-3ubuntu5.8).
ntpdate is already the newest version (1:4.2.8p4+dfsg-3ubuntu5.8).
The following packages were automatically installed and are no longer required:
  libaio1 libunwind8 libyaml-cpp0.5v5 linux-gcp-headers-4.13.0-1012
  linux-headers-4.13.0-1012-gcp linux-image-4.13.0-1012-gcp
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 19 not upgraded.
 1 Jun 20:31:18 ntpdate[16280]: adjust time server 169.254.169.254 offset 0.000016 sec
NTP setup failed.
```

**Comment by slivne** [comment] 2018-06-14 12:55
duplicate of #3485 

fixed

**Closed by slivne** 2018-06-14 12:55 UTC
