### ISSUE TITLE
No space left on device during nodetool cleanup with stuck up to 12 hours

### ISSUE THREAD

**Issue by aleksbykov** [scylladb/scylla#7140] opened 2020-08-28 12:47 UTC
*Installation details*
Scylla version (or git commit hash): 4.2.rc3-0.20200825.989d8fe63 with build-id e7d653bede6105c8264984a606cd5334967ca553
Cluster size: 4
OS (RHEL/CentOS/Ubuntu/AWS AMI): ami-030a65c1452a3ee91 (eu-north-1)

Job [longevity-large-collections-12h-test](https://jenkins.scylladb.com/view/scylla-4.2/job/scylla-4.2/job/longevity/job/longevity-large-collections-12h-test/6) was failed.
next c-s command was using for testing:
```
JVM_OPTION='-Xms8033M -Xmx8033M -Xmn400M' cassandra-stress user profile=/tmp/large_collections.yaml ops'(insert=3,read1=1,update1=1)' cl=QUORUM duration=720m -port jmx=6868 -mode cql3 native -rate threads=20
```
with next yaml
```
keyspace: large_collection_test

keyspace_definition: |

  CREATE KEYSPACE large_collection_test WITH replication = {'class': 'SimpleStrategy', 'replication_factor': '3'}  AND durable_writes = true;

table: table_with_large_collection

table_definition: |

  CREATE TABLE large_collection_test.table_with_large_collection (
    pk_id text PRIMARY KEY,
    init_time timestamp,
    user_name text,
    new_num int,
    weight decimal,
    nums_list list<int>,
    users_name list<text>,
    nums_set set<int>,
    names_set set<text>,
    books_set set<text>,
  ) WITH bloom_filter_fp_chance = 0.01
    AND caching = {'keys': 'ALL', 'rows_per_partition': 'ALL'}
    AND comment = 'Request for unit level UIs'
    AND compaction = {'class': 'SizeTieredCompactionStrategy'}
    AND compression = {'sstable_compression': 'org.apache.cassandra.io.compress.LZ4Compressor'}
    AND crc_check_chance = 1.0
    AND dclocal_read_repair_chance = 0.1
    AND default_time_to_live = 0
    AND gc_grace_seconds = 864000
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair_chance = 0.0
    AND speculative_retry = '99.0PERCENTILE';

columnspec:
  - name: pk_id
    population: seq(1..8000000)

# Need to populate the list field with big elements and many of them (about 40MB per list).
# >>> math.sqrt(40 * 1024 * 1024)
# 6476.344648024841
# large partition: 16M, large row: 4M, large cell: 1M
# >>> math.sqrt(16 * 1024 * 1024)
# 4096.0
# >>> math.sqrt(1024 * 1024 * 15.5 / 2)
# 2850.695353768971
# >>> math.sqrt(4 * 1024 * 1024)
# 2048.0
# >>> math.sqrt(1024 * 1024 * 4 / 2)
# 1448.1546878700494
# >>> math.sqrt(1 * 1024 * 1024)
# 1024.0

  - name: nums_list
    size: fixed(2)
    population: uniform(1..10000)

  - name: users_name
    size: fixed(5)

  - name: nums_set
    size: fixed(100)
    population: uniform(1..10000)

  - name: names_set
    size: fixed(1024)
    population: uniform(1..1024)

  - name: books_set
    size: fixed(1024)
    population: uniform(1..1024)

insert:
  batchtype: UNLOGGED

queries:
  read1:
    cql: select * from large_collection_test.table_with_large_collection where pk_id = ?
    fields: samerow
  update1:
    cql: update large_collection_test.table_with_large_collection set users_name=?,nums_list=?,nums_set=?,names_set=?,books_set=? where pk_id = ?
    fields: samerow
```

Next nemesis was run: RestartThenRepairNode ( which restart scylla and execute nodetool repair) on node 3. It finished without errors.
Then started next nemesis: NodetoolCleanup. Which execute nodetool cleanup on each node.
On first node command finished without errors.
But on second node it started, was running for 4 hours, then report in log:
```
2020-08-27T16:45:19+00:00  longevity-large-collections-12h-4-2-db-node-5787f1fa-2 !ERR     | scylla: [shard 3] sstable - writer failed to close file: storage_io_error (Storage I/O error: 28: No space left on device)
2020-08-27T16:45:19+00:00  longevity-large-collections-12h-4-2-db-node-5787f1fa-2 !ERR     | scylla: [shard 2] sstable - writer failed to close file: storage_io_error (Storage I/O error: 28: No space left on device)
2020-08-27T16:45:19+00:00  longevity-large-collections-12h-4-2-db-node-5787f1fa-2 !ERR     | scylla: [shard 3] compaction_manager - compaction failed due to storage io error: Storage I/O error: 28: No space left on device: stopping
2020-08-27T16:45:19+00:00  longevity-large-collections-12h-4-2-db-node-5787f1fa-2 !INFO    | scylla: [shard 3] compaction_manager - Asked to stop
2020-08-27T16:45:19+00:00  longevity-large-collections-12h-4-2-db-node-5787f1fa-2 !INFO    | scylla: [shard 3] compaction_manager - Stopping 1 ongoing compactions
2020-08-27T16:45:19+00:00  longevity-large-collections-12h-4-2-db-node-5787f1fa-2 !ERR     | scylla: [shard 2] compaction_manager - compaction failed due to storage io error: Storage I/O error: 28: No space left on device: stopping
2020-08-27T16:45:19+00:00  longevity-large-collections-12h-4-2-db-node-5787f1fa-2 !INFO    | scylla: [shard 2] compaction_manager - Asked to stop
2020-08-27T16:45:19+00:00  longevity-large-collections-12h-4-2-db-node-5787f1fa-2 !INFO    | scylla: [shard 2] compaction_manager - Stopping 3 ongoing compactions
2020-08-27T16:45:19+00:00  longevity-large-collections-12h-4-2-db-node-5787f1fa-2 !ERR     | scylla: [shard 1] compaction_manager - compaction failed due to storage io error: Storage I/O error: 28: No space left on device: stopping
2020-08-27T16:45:19+00:00  longevity-large-collections-12h-4-2-db-node-5787f1fa-2 !INFO    | scylla: [shard 1] compaction_manager - Asked to stop
2020-08-27T16:45:19+00:00  longevity-large-collections-12h-4-2-db-node-5787f1fa-2 !INFO    | scylla: [shard 1] compaction_manager - Stopping 2 ongoing compactions
2020-08-27T16:45:19+00:00  longevity-large-collections-12h-4-2-db-node-5787f1fa-2 !INFO    | scylla: [shard 13] compaction - Compacting [/var/lib/scylla/data/large_collection_test/table_with_large_collection-8da586f0e84e11ea8b10000000000001/mc-8147-big-Data.db:level=0, /var/lib/scylla/data/large_collection_test/table_with_large_collection-8da586f0e84e11ea8b10000000000001/mc-8245-big-Data.db:level=0, ]
2020-08-27T16:45:19+00:00  longevity-large-collections-12h-4-2-db-node-5787f1fa-2 !ERR     | scylla: [shard 0] compaction_manager - compaction failed due to storage io error: Storage I/O error: 28: No space left on device: stopping
2020-08-27T16:45:19+00:00  longevity-large-collections-12h-4-2-db-node-5787f1fa-2 !INFO    | scylla: [shard 0] compaction_manager - Asked to stop
2020-08-27T16:45:19+00:00  longevity-large-collections-12h-4-2-db-node-5787f1fa-2 !INFO    | scylla: [shard 0] compaction_manager - Stopping 3 ongoing compactions
2020-08-27T16:45:19+00:00  longevity-large-collections-12h-4-2-db-node-5787f1fa-2 !INFO    | scylla: [shard 13] compaction - Compacting [/var/lib/scylla/data/large_collection_test/table_with_large_collection-8da586f0e84e11ea8b10000000000001/mc-8833-big-Data.db:level=0, /var/lib/scylla/data/large_collection_test/table_with_large_collection-8da586f0e84e11ea8b10000000000001/mc-8777-big-Data.db:level=0, ]
2020-08-27T16:45:19+00:00  longevity-large-collections-12h-4-2-db-node-5787f1fa-2 !ERR     | scylla: [shard 13] compaction_manager - compaction failed due to storage io error: Storage I/O error: 28: No space left on device: stopping
2020-08-27T16:45:19+00:00  longevity-large-collections-12h-4-2-db-node-5787f1fa-2 !INFO    | scylla: [shard 13] compaction_manager - Asked to stop
2020-08-27T16:45:19+00:00  longevity-large-collections-12h-4-2-db-node-5787f1fa-2 !INFO    | scylla: [shard 13] compaction_manager - Stopping 4 ongoing compactions
2020-08-27T16:45:19+00:00  longevity-large-collections-12h-4-2-db-node-5787f1fa-2 !ERR     | scylla: [shard 3] sstable - writer failed to close file: storage_io_error (Storage I/O error: 28: No space left on device)
2020-08-27T16:45:19+00:00  longevity-large-collections-12h-4-2-db-node-5787f1fa-2 !INFO    | scylla: [shard 12] compaction - Compacting [/var/lib/scylla/data/large_collection_test/table_with_large_collection-8da586f0e84e11ea8b10000000000001/mc-8622-big-Data.db:level=0, /var/lib/scylla/data/large_collection_test/table_with_large_collection-8da586f0e84e11ea8b10000000000001/mc-8594-big-Data.db:level=0, ]
2020-08-27T16:45:19+00:00  longevity-large-collections-12h-4-2-db-node-5787f1fa-2 !ERR     | scylla: [shard 12] compaction_manager - compaction failed due to storage io error: Storage I/O error: 28: No space left on device: stopping
2020-08-27T16:45:19+00:00  longevity-large-collections-12h-4-2-db-node-5787f1fa-2 !INFO    | scylla: [shard 12] compaction_manager - Asked to stop
2020-08-27T16:45:19+00:00  longevity-large-collections-12h-4-2-db-node-5787f1fa-2 !INFO    | scylla: [shard 12] compaction_manager - Stopping 2 ongoing compactions
2020-08-27T16:45:19+00:00  longevity-large-collections-12h-4-2-db-node-5787f1fa-2 !INFO    | scylla: [shard 3] compaction_manager - compaction info: Compaction for large_collection_test/table_with_large_collection was stopped due to: shutdown: stopping
2020-08-27T16:45:19+00:00  longevity-large-collections-12h-4-2-db-node-5787f1fa-2 !ERR     | scylla: [shard 0] compaction_manager - compaction failed due to storage io error: Storage I/O error: 28: No space left on device: stopping
2020-08-27T16:45:19+00:00  longevity-large-collections-12h-4-2-db-node-5787f1fa-2 !ERR     | scylla: [shard 0] sstable - writer failed to close file: storage_io_error (Storage I/O error: 28: No space left on device)
2020-08-27T16:45:19+00:00  longevity-large-collections-12h-4-2-db-node-5787f1fa-2 !INFO    | scylla: [shard 0] compaction_manager - compaction info: Compaction for large_collection_test/table_with_large_collection was stopped due to: shutdown: stopping
2020-08-27T16:45:19+00:00  longevity-large-collections-12h-4-2-db-node-5787f1fa-2 !ERR     | scylla: [shard 0] compaction_manager - compaction failed due to storage io error: Storage I/O error: 28: No space left on device: stopping
2020-08-27T16:45:19+00:00  longevity-large-collections-12h-4-2-db-node-5787f1fa-2 !ERR     | scylla: [shard 9] compaction_manager - compaction failed due to storage io error: Storage I/O error: 28: No space left on device: stopping
2020-08-27T16:45:19+00:00  longevity-large-collections-12h-4-2-db-node-5787f1fa-2 !INFO    | scylla: [shard 9] compaction_manager - Asked to stop
2020-08-27T16:45:19+00:00  longevity-large-collections-12h-4-2-db-node-5787f1fa-2 !INFO    | scylla: [shard 9] compaction_manager - Stopping 2 ongoing compactions
2020-08-27T16:45:19+00:00  longevity-large-collections-12h-4-2-db-node-5787f1fa-2 !ERR     | scylla: [shard 9] compaction_manager - compaction failed due to storage io error: Storage I/O error: 28: No space left on device: stopping
2020-08-27T16:45:19+00:00  longevity-large-collections-12h-4-2-db-node-5787f1fa-2 !ERR     | scylla: [shard 1] sstable - writer failed to close file: storage_io_error (Storage I/O error: 28: No space left on device)
2020-08-27T16:45:19+00:00  longevity-large-collections-12h-4-2-db-node-5787f1fa-2 !ERR     | scylla: [shard 1] compaction_manager - compaction failed due to storage io error: Storage I/O error: 28: No space left on device: stopping
2020-08-27T16:45:19+00:00  longevity-large-collections-12h-4-2-db-node-5787f1fa-2 !INFO    | scylla: [shard 1] compaction_manager - compaction info: Compaction for large_collection_test/table_with_large_collection was stopped due to: shutdown: stopping
2020-08-27T16:45:19+00:00  longevity-large-collections-12h-4-2-db-node-5787f1fa-2 !INFO    | scylla: [shard 13] compaction_manager - compaction info: Compaction for large_collection_test/table_with_large_collection was stopped due to: shutdown: stopping
2020-08-27T16:45:19+00:00  longevity-large-collections-12h-4-2-db-node-5787f1fa-2 !INFO    | scylla: [shard 13] compaction_manager - compaction info: Compaction for large_collection_test/table_with_large_collection was stopped due to: shutdown: stopping
2020-08-27T16:45:19+00:00  longevity-large-collections-12h-4-2-db-node-5787f1fa-2 !ERR     | scylla: [shard 12] sstable - writer failed to close file: storage_io_error (Storage I/O error: 28: No space left on device)
2020-08-27T16:45:19+00:00  longevity-large-collections-12h-4-2-db-node-5787f1fa-2 !INFO    | scylla: [shard 12] compaction_manager - compaction info: Compaction for large_collection_test/table_with_large_collection was stopped due to: shutdown: stopping
2020-08-27T16:45:19+00:00  longevity-large-collections-12h-4-2-db-node-5787f1fa-2 !INFO    | scylla: [shard 8] compaction - Compacting [/var/lib/scylla/data/large_collection_test/table_with_large_collection-8da586f0e84e11ea8b10000000000001/mc-8226-big-Data.db:level=0, /var/lib/scylla/data/large_collection_test/table_with_large_collection-8da586f0e84e11ea8b10000000000001/mc-7624-big-Data.db:level=0, /var/lib/scylla/data/large_collection_test/table_with_large_collection-8da586f0e84e11ea8b10000000000001/mc-8436-big-Data.db:level=0, ]
2020-08-27T16:45:19+00:00  longevity-large-collections-12h-4-2-db-node-5787f1fa-2 !ERR     | scylla: [shard 8] compaction_manager - compaction failed due to storage io error: Storage I/O error: 28: No space left on device: stopping
2020-08-27T16:45:19+00:00  longevity-large-collections-12h-4-2-db-node-5787f1fa-2 !INFO    | scylla: [shard 8] compaction_manager - Asked to stop
2020-08-27T16:45:19+00:00  longevity-large-collections-12h-4-2-db-node-5787f1fa-2 !INFO    | scylla: [shard 8] compaction_manager - Stopping 3 ongoing compactions
2020-08-27T16:45:19+00:00  longevity-large-collections-12h-4-2-db-node-5787f1fa-2 !ERR     | scylla: [shard 8] compaction_manager - compaction failed due to storage io error: Storage I/O error: 28: No space left on device: stopping
2020-08-27T16:45:19+00:00  longevity-large-collections-12h-4-2-db-node-5787f1fa-2 !ERR     | scylla: [shard 8] compaction_manager - compaction failed due to storage io error: Storage I/O error: 28: No space left on device: stopping
2020-08-27T16:45:19+00:00  longevity-large-collections-12h-4-2-db-node-5787f1fa-2 !ERR     | scylla: [shard 2] sstable - writer failed to close file: storage_io_error (Storage I/O error: 28: No space left on device)
2020-08-27T16:45:19+00:00  longevity-large-collections-12h-4-2-db-node-5787f1fa-2 !INFO    | scylla: [shard 2] compaction_manager - compaction info: Compaction for large_collection_test/table_with_large_collection was stopped due to: shutdown: stopping
2020-08-27T16:45:19+00:00  longevity-large-collections-12h-4-2-db-node-5787f1fa-2 !ERR     | scylla: [shard 4] compaction_manager - compaction failed due to storage io error: Storage I/O error: 28: No space left on device: stopping
2020-08-27T16:45:19+00:00  longevity-large-collections-12h-4-2-db-node-5787f1fa-2 !INFO    | scylla: [shard 4] compaction_manager - Asked to stop
2020-08-27T16:45:19+00:00  longevity-large-collections-12h-4-2-db-node-5787f1fa-2 !INFO    | scylla: [shard 4] compaction_manager - Stopping 2 ongoing compactions
2020-08-27T16:45:19+00:00  longevity-large-collections-12h-4-2-db-node-5787f1fa-2 !ERR     | scylla: [shard 2] sstable - writer failed to close file: storage_io_error (Storage I/O error: 28: No space left on device)
2020-08-27T16:45:19+00:00  longevity-large-collections-12h-4-2-db-node-5787f1fa-2 !INFO    | scylla: [shard 2] compaction_manager - compaction info: Compaction for large_collection_test/table_with_large_collection was stopped due to: shutdown: stopping
2020-08-27T16:45:19+00:00  longevity-large-collections-12h-4-2-db-node-5787f1fa-2 !ERR     | scylla: [shard 2] sstable - writer failed to close file: storage_io_error (Storage I/O error: 28: No space left on device)
2020-08-27T16:45:19+00:00  longevity-large-collections-12h-4-2-db-node-5787f1fa-2 !INFO    | scylla: [shard 2] compaction_manager - compaction info: Compaction for large_collection_test/table_with_large_collection was stopped due to: shutdown: stopping
2020-08-27T16:45:19+00:00  longevity-large-collections-12h-4-2-db-node-5787f1fa-2 !ERR     | scylla: [shard 10] compaction_manager - compaction failed due to storage io error: Storage I/O error: 28: No space left on device: stopping
2020-08-27T16:45:19+00:00  longevity-large-collections-12h-4-2-db-node-5787f1fa-2 !INFO    | scylla: [shard 10] compaction_manager - Asked to stop
2020-08-27T16:45:19+00:00  longevity-large-collections-12h-4-2-db-node-5787f1fa-2 !INFO    | scylla: [shard 10] compaction_manager - Stopping 3 ongoing compactions
2020-08-27T16:45:19+00:00  longevity-large-collections-12h-4-2-db-node-5787f1fa-2 !ERR     | scylla: [shard 9] compaction_manager - compaction failed due to storage io error: Storage I/O error: 28: No space left on device: stopping
2020-08-27T16:45:19+00:00  longevity-large-collections-12h-4-2-db-node-5787f1fa-2 !INFO    | scylla: [shard 12] compaction_manager - compaction info: Compaction for large_collection_test/table_with_large_collection was stopped due to: shutdown: stopping
2020-08-27T16:45:19+00:00  longevity-large-collections-12h-4-2-db-node-5787f1fa-2 !INFO    | scylla: [shard 12] compaction_manager - Stopped
2020-08-27T16:45:19+00:00  longevity-large-collections-12h-4-2-db-node-5787f1fa-2 !ERR     | scylla: [shard 7] compaction_manager - compaction failed due to storage io error: Storage I/O error: 28: No space left on device: stopping
2020-08-27T16:45:19+00:00  longevity-large-collections-12h-4-2-db-node-5787f1fa-2 !INFO    | scylla: [shard 7] compaction_manager - Asked to stop
2020-08-27T16:45:19+00:00  longevity-large-collections-12h-4-2-db-node-5787f1fa-2 !INFO    | scylla: [shard 7] compaction_manager - Stopping 3 ongoing compactions
2020-08-27T16:45:19+00:00  longevity-large-collections-12h-4-2-db-node-5787f1fa-2 !INFO    | scylla: [shard 13] compaction_manager - compaction info: Compaction for large_collection_test/table_with_large_collection was stopped due to: shutdown: stopping
2020-08-27T16:45:19+00:00  longevity-large-collections-12h-4-2-db-node-5787f1fa-2 !INFO    | scylla: [shard 9] compaction_manager - compaction info: Compaction for large_collection_test/table_with_large_collection was stopped due to: shutdown: stopping
2020-08-27T16:45:19+00:00  longevity-large-collections-12h-4-2-db-node-5787f1fa-2 !ERR     | scylla: [shard 10] compaction_manager - compaction failed due to storage io error: Storage I/O error: 28: No space left on device: stopping
2020-08-27T16:45:19+00:00  longevity-large-collections-12h-4-2-db-node-5787f1fa-2 !INFO    | scylla: [shard 13] compaction_manager - compaction info: Compaction for large_collection_test/table_with_large_collection was stopped due to: shutdown: stopping
2020-08-27T16:45:19+00:00  longevity-large-collections-12h-4-2-db-node-5787f1fa-2 !INFO    | scylla: [shard 13] compaction_manager - Stopped
2020-08-27T16:45:19+00:00  longevity-large-collections-12h-4-2-db-node-5787f1fa-2 !INFO    | scylla: [shard 4] compaction_manager - compaction info: Compaction for large_collection_test/table_with_large_collection was stopped due to: shutdown: stopping
2020-08-27T16:45:19+00:00  longevity-large-collections-12h-4-2-db-node-5787f1fa-2 !INFO    | scylla: [shard 10] compaction_manager - compaction info: Compaction for large_collection_test/table_with_large_collection was stopped due to: shutdown: stopping
2020-08-27T16:45:19+00:00  longevity-large-collections-12h-4-2-db-node-5787f1fa-2 !INFO    | scylla: [shard 8] compaction_manager - compaction info: Compaction for large_collection_test/table_with_large_collection was stopped due to: shutdown: stopping
2020-08-27T16:45:19+00:00  longevity-large-collections-12h-4-2-db-node-5787f1fa-2 !INFO    | scylla: [shard 4] compaction_manager - compaction info: Compaction for large_collection_test/table_with_large_collection was stopped due to: shutdown: stopping
2020-08-27T16:45:19+00:00  longevity-large-collections-12h-4-2-db-node-5787f1fa-2 !INFO    | scylla: [shard 8] compaction_manager - compaction info: Compaction for large_collection_test/table_with_large_collection was stopped due to: shutdown: stopping
2020-08-27T16:45:19+00:00  longevity-large-collections-12h-4-2-db-node-5787f1fa-2 !INFO    | scylla: [shard 10] compaction_manager - compaction info: Compaction for large_collection_test/table_with_large_collection was stopped due to: shutdown: stopping
2020-08-27T16:45:19+00:00  longevity-large-collections-12h-4-2-db-node-5787f1fa-2 !INFO    | scylla: [shard 8] compaction_manager - compaction info: Compaction for large_collection_test/table_with_large_collection was stopped due to: shutdown: stopping
2020-08-27T16:45:19+00:00  longevity-large-collections-12h-4-2-db-node-5787f1fa-2 !INFO    | scylla: [shard 7] compaction_manager - compaction info: Compaction for large_collection_test/table_with_large_collection was stopped due to: shutdown: stopping
2020-08-27T16:45:19+00:00  longevity-large-collections-12h-4-2-db-node-5787f1fa-2 !INFO    | scylla: [shard 7] compaction_manager - compaction info: Compaction for large_collection_test/table_with_large_collection was stopped due to: shutdown: stopping
2020-08-27T16:45:19+00:00  longevity-large-collections-12h-4-2-db-node-5787f1fa-2 !INFO    | scylla: [shard 7] compaction_manager - compaction info: Compaction for large_collection_test/table_with_large_collection was stopped due to: shutdown: stopping
```

And looks like after that the command stucked and exited only in 6 hours with next error:
```
CRITICAL > Command: 'nodetool  cleanup large_collection_test'
CRITICAL > 
CRITICAL > Exit code: -1
CRITICAL > 
CRITICAL > Stdout:
CRITICAL > 
CRITICAL > 
CRITICAL > 
CRITICAL > Stderr:
CRITICAL > 
CRITICAL > WARN  12:34:28,398 Only 8.054GiB free across all data volumes. Consider adding more capacity to your cluster or removing obsolete snapshots
```

Also, scylla was stopped on node2 and node 1,3,4 reported that no connection to it.
```
2020-08-27T16:16:22+00:00  longevity-large-collections-12h-4-2-db-node-5787f1fa-3 !ERR     | scylla: [shard 0] rpc - client 10.0.3.37:7000: fail to connect: Connection refused
2020-08-27T18:47:42+00:00  longevity-large-collections-12h-4-2-db-node-5787f1fa-4 !ERR     | scylla: [shard 0] rpc - client 10.0.3.37:7000: fail to connect: Connection refused
```
Monitoring stack available : http://13.48.67.52:3000/
or by restoring: hydra investigate show-monitor 5787f1fa-1e58-46e0-8bf1-0287c3c9e671

Unfortunately, the log was not collected from nodes. they were restore from sct.log file:
[node1.log](https://github.com/scylladb/scylla/files/5142089/node1.log)
[node2.log](https://github.com/scylladb/scylla/files/5142090/node2.log)
[node3.log](https://github.com/scylladb/scylla/files/5142091/node3.log)
[node4.log](https://github.com/scylladb/scylla/files/5142092/node4.log)

**Comment by roydahan** [comment] 2020-08-30 11:33
@aleksbykov missing information:
1. What is the instacne type (and scylla disk size)
2. What was the disk space status before the cleanup?
3. Was there a jump in disk usage in a previous nemesis?

you shoule be able to take the information from the monitoring.

**Comment by bhalevy** [comment] 2020-08-31 05:20
@raphaelsc can you please investigate the logs to see if there was a problem stopping compaction promptly on node-2?

**Comment by raphaelsc** [comment] 2020-08-31 12:21
looks like the node run out of disk space, because of a bug recently fixed by me, where a given sstable can be selected for both cleanup and regular compaction, resulting in redundant data, which is the root cause for ENOSPC we faced here.

`< t:2020-08-27 12:15:52,391 f:cluster.py      l:1518 c:sdcm.cluster         p:DEBUG > 2020-08-27T12:15:51+00:00  longevity-large-collections-12h-4-2-db-node-5787f1fa-2 !INFO    | scylla: [shard 8] compaction - Compacting [..., /var/lib/scylla/data/large_collection_test/table_with_large_collection-8da586f0e84e11ea8b10000000000001/mc-7554-big-Data.db:level=0, ...]

...

collections-12h-4-2-db-node-5787f1fa-2 !INFO    | scylla: [shard 8] compaction - Cleaning [/var/lib/scylla/data/large_collection_test/table_with_large_collection-8da586f0e84e11ea8b10000000000001/mc-7554-big-Data.db:level=0, ]
...
`

`
 t:2020-08-27 15:35:53,906 f:cluster.py      l:1518 c:sdcm.cluster         p:DEBUG > 2020-08-27T15:35:51+00:00  longevity-large-collections-12h-4-2-db-node-5787f1fa-2 !WARNING | scylla: [shard 8] sstable - Unable to delete /var/lib/scylla/data/large_collection_test/table_with_large_collection-8da586f0e84e11ea8b10000000000001/mc-7554-big-TOC.txt because it doesn't exist.

`

**Comment by raphaelsc** [comment] 2020-08-31 12:24
This issue is fixed by https://github.com/scylladb/scylla/commit/11df96718a8ce59017ca3703fd8d5d55c99164b5, which was tracked here #6938. This bug also caused a reshape issue, as it can potentially produce several issues in the system.

**Comment by raphaelsc** [comment] 2020-08-31 13:16
i just asked for backporting of https://github.com/scylladb/scylla/commit/11df96718a8ce59017ca3703fd8d5d55c99164b5 to 4.2 branch

**Comment by aleksbykov** [comment] 2020-08-31 14:47
> @aleksbykov missing information:
> 
> 1. What is the instacne type (and scylla disk size)

Instance type: i3.4xlarge (2 disk by 2 GB), it seems has 4 GB per node
> 2. What was the disk space status before the cleanup?

The useage was about 1tb per node
> 3. Was there a jump in disk usage in a previous nemesis?

No, disk space jump happened during cleanup. During cleanup on node2 it jumped on node from ~1Tb -> 3,5TB
 
> you shoule be able to take the information from the monitoring.

![Screenshot from 2020-08-31 21-47-16](https://user-images.githubusercontent.com/44991177/91733334-9776e600-ebd3-11ea-952f-142d747401b7.png)

![Screenshot from 2020-08-31 21-46-30](https://user-images.githubusercontent.com/44991177/91733356-9e055d80-ebd3-11ea-9e85-dab66e1178f4.png)

**Comment by raphaelsc** [comment] 2020-09-01 18:31
once https://github.com/scylladb/scylla/commit/11df96718a8ce59017ca3703fd8d5d55c99164b5 is backport to branch 4.2, this issue can be closed.

**Comment by raphaelsc** [comment] 2020-09-02 19:16
fix merged to next-4.2, will likely make into branch-4.2 soon, so i am closing this branch

**Comment by raphaelsc** [comment] 2020-09-02 19:16
closing this issue*

**Closed by raphaelsc** 2020-09-02 19:16 UTC
Labels: bug

**Comment by aleksbykov** [comment] 2020-09-08 07:57
Issue again reproduced with Scylla version 4.2.rc3-0.20200905.e1b3d6d0a with build-id 60c56c88d11bb763492cbb8857c2ee9f3f9ad243
Will recheck with rc4.

**Comment by raphaelsc** [comment] 2020-09-09 13:54
> Issue again reproduced with Scylla version 4.2.rc3-0.20200905.e1b3d6d0a with build-id 60c56c88d11bb763492cbb8857c2ee9f3f9ad243
> Will recheck with rc4.

rc3 lacks https://github.com/scylladb/scylla/commit/11df96718a8ce59017ca3703fd8d5d55c99164b5 so this is expected.
