### ISSUE TITLE
Aborting on shard on the node duringe multiple schema changes

### ISSUE THREAD

**Issue by juliayakovlev** [scylladb/scylla#10212] opened 2022-03-14 16:56 UTC
*Installation details*
Kernel version: `5.11.0-1028-aws`
Scylla version (or git commit hash): `5.1.dev-0.20220303.0544973b15dd with build-id 3b69cb8b4d61d8190175613119fcc982a0b5eddb`
Cluster size: 4 nodes (i3en.2xlarge)
OS (RHEL/CentOS/Ubuntu/AWS AMI): `ami-050e5a4fbd1175aa3` (aws: eu-west-1)

Scylla running with shards number (live nodes):
   longevity-twcs-48h-master-db-node-d46ad8d2-1 (34.249.96.8 | 10.0.0.220): 8 shards
   longevity-twcs-48h-master-db-node-d46ad8d2-2 (54.247.63.50 | 10.0.1.234): 8 shards
   longevity-twcs-48h-master-db-node-d46ad8d2-4 (52.17.246.181 | 10.0.1.239): 8 shards
   longevity-twcs-48h-master-db-node-d46ad8d2-5 (18.203.234.45 | 10.0.2.66): 8 shards
Scylla running with shards number (terminated nodes):
   longevity-twcs-48h-master-db-node-d46ad8d2-3 (3.250.122.88 | 10.0.2.33): 8 shards

Test: `longevity-twcs-48h-test`
Test name: `longevity_twcs_test.TWCSLongevityTest.test_custom_time`
Test config file(s):
- [longevity-twcs-48h.yaml]([https://github.com/scylladb/scylla-cluster-tests/blob/214326a9d47e7b751489638d5dfaa781f68a7700/test-cases/longevity/longevity-twcs-48h.yaml](https://www.google.com/url?q=https://github.com/scylladb/scylla-cluster-tests/blob/214326a9d47e7b751489638d5dfaa781f68a7700/test-cases/longevity/longevity-twcs-48h.yaml&source=gmail-html&ust=1647363008800000&usg=AOvVaw0314gw2d2Xa7RCtj49Zv9b))

**Issue description**

AddDropColumn nemesis performed multiple schema changes on `longevity-twcs-48h-master-db-node-d46ad8d2-4 [52.17.246.181 | 10.0.1.239] ` node.
There are a lot of reactor stalls on this node and aborting on shard

```
Mar 11 10:39:27 longevity-twcs-48h-master-db-node-d46ad8d2-4 scylla[16582]: scylla: ./seastar/include/seastar/core/future.hh:634: void seastar::future_state<boost::outcome_v2::basic_result<service::digest_read_result, utils::exception_container<exceptions::mutation_write_timeout_exception, exceptions::read_timeout_exception, exceptions::read_failure_exception>, utils::exception_container_throw_policy>>::set(A &&...) [T = boost::outcome_v2::basic_result<service::digest_read_result, utils::exception_container<exceptions::mutation_write_timeout_exception, exceptions::read_timeout_exception, exceptions::read_failure_exception>, utils::exception_container_throw_policy>, A = <utils::exception_container<exceptions::mutation_write_timeout_exception, exceptions::read_timeout_exception, exceptions::read_failure_exception>>]: Assertion `_u.st == state::future' failed.
Mar 11 10:39:27 longevity-twcs-48h-master-db-node-d46ad8d2-4 scylla[16582]: Aborting on shard 3.
Mar 11 10:39:27 longevity-twcs-48h-master-db-node-d46ad8d2-4 scylla[16582]: Backtrace:
0x45cdf48
0x45fead2
0x7fa8b23eda1f
/opt/scylladb/libreloc/libc.so.6+0x3d2a1
/opt/scylladb/libreloc/libc.so.6+0x268a3
/opt/scylladb/libreloc/libc.so.6+0x26788
/opt/scylladb/libreloc/libc.so.6+0x35a15
0x24e1ec8
0x24e2054
0x45de2dd
0x45fe148
0x45e0351
0x45fefd5
0x45b2e2a
/opt/scylladb/libreloc/libpthread.so.0+0x92a4
/opt/scylladb/libreloc/libc.so.6+0x100322
```

The node shutted down. After the node was up again, it reported about kernel callstacks, reactor stalled and oversized allocation

Restore Monitor Stack command: `$ hydra investigate show-monitor d46ad8d2-7a79-4fdb-a81d-0622f2c13c54`
Restore monitor on AWS instance using [Jenkins job]([https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?sct_branch=master&test_id=d46ad8d2-7a79-4fdb-a81d-0622f2c13c54](https://www.google.com/url?q=https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?sct_branch%3Dmaster%26test_id%3Dd46ad8d2-7a79-4fdb-a81d-0622f2c13c54&source=gmail-html&ust=1647363008800000&usg=AOvVaw2gplxkXZ_CJo4V5VivO3ZX))
Show all stored logs command: `$ hydra investigate show-logs d46ad8d2-7a79-4fdb-a81d-0622f2c13c54`

Test id: `d46ad8d2-7a79-4fdb-a81d-0622f2c13c54`

Logs:
grafana - [[https://cloudius-jenkins-test.s3.amazonaws.com/d46ad8d2-7a79-4fdb-a81d-0622f2c13c54/20220311_105300/grafana-screenshot-longevity-twcs-48h-test-scylla-per-server-metrics-nemesis-20220311_105519-longevity-twcs-48h-master-monitor-node-d46ad8d2-1.png](https://cloudius-jenkins-test.s3.amazonaws.com/d46ad8d2-7a79-4fdb-a81d-0622f2c13c54/20220311_105300/grafana-screenshot-longevity-twcs-48h-test-scylla-per-server-metrics-nemesis-20220311_105519-longevity-twcs-48h-master-monitor-node-d46ad8d2-1.png)](https://www.google.com/url?q=https://cloudius-jenkins-test.s3.amazonaws.com/d46ad8d2-7a79-4fdb-a81d-0622f2c13c54/20220311_105300/grafana-screenshot-longevity-twcs-48h-test-scylla-per-server-metrics-nemesis-20220311_105519-longevity-twcs-48h-master-monitor-node-d46ad8d2-1.png%255D(https://cloudius-jenkins-test.s3.amazonaws.com/d46ad8d2-7a79-4fdb-a81d-0622f2c13c54/20220311_105300/grafana-screenshot-longevity-twcs-48h-test-scylla-per-server-metrics-nemesis-20220311_105519-longevity-twcs-48h-master-monitor-node-d46ad8d2-1.png)&source=gmail-html&ust=1647363008800000&usg=AOvVaw112aUrwwr3sGa9NOO9dOJ3)
grafana - [[https://cloudius-jenkins-test.s3.amazonaws.com/d46ad8d2-7a79-4fdb-a81d-0622f2c13c54/20220311_105300/grafana-screenshot-overview-20220311_105300-longevity-twcs-48h-master-monitor-node-d46ad8d2-1.png](https://cloudius-jenkins-test.s3.amazonaws.com/d46ad8d2-7a79-4fdb-a81d-0622f2c13c54/20220311_105300/grafana-screenshot-overview-20220311_105300-longevity-twcs-48h-master-monitor-node-d46ad8d2-1.png)](https://www.google.com/url?q=https://cloudius-jenkins-test.s3.amazonaws.com/d46ad8d2-7a79-4fdb-a81d-0622f2c13c54/20220311_105300/grafana-screenshot-overview-20220311_105300-longevity-twcs-48h-master-monitor-node-d46ad8d2-1.png%255D(https://cloudius-jenkins-test.s3.amazonaws.com/d46ad8d2-7a79-4fdb-a81d-0622f2c13c54/20220311_105300/grafana-screenshot-overview-20220311_105300-longevity-twcs-48h-master-monitor-node-d46ad8d2-1.png)&source=gmail-html&ust=1647363008801000&usg=AOvVaw1lCCVYobUn8EGI83WIVCHN)
db-cluster - [[https://cloudius-jenkins-test.s3.amazonaws.com/d46ad8d2-7a79-4fdb-a81d-0622f2c13c54/20220311_110835/db-cluster-d46ad8d2.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/d46ad8d2-7a79-4fdb-a81d-0622f2c13c54/20220311_110835/db-cluster-d46ad8d2.tar.gz)](https://www.google.com/url?q=https://cloudius-jenkins-test.s3.amazonaws.com/d46ad8d2-7a79-4fdb-a81d-0622f2c13c54/20220311_110835/db-cluster-d46ad8d2.tar.gz%255D(https://cloudius-jenkins-test.s3.amazonaws.com/d46ad8d2-7a79-4fdb-a81d-0622f2c13c54/20220311_110835/db-cluster-d46ad8d2.tar.gz)&source=gmail-html&ust=1647363008801000&usg=AOvVaw3h5AIR90sKsmDa-8YWwxWb)
loader-set - [[https://cloudius-jenkins-test.s3.amazonaws.com/d46ad8d2-7a79-4fdb-a81d-0622f2c13c54/20220311_110835/loader-set-d46ad8d2.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/d46ad8d2-7a79-4fdb-a81d-0622f2c13c54/20220311_110835/loader-set-d46ad8d2.tar.gz)](https://www.google.com/url?q=https://cloudius-jenkins-test.s3.amazonaws.com/d46ad8d2-7a79-4fdb-a81d-0622f2c13c54/20220311_110835/loader-set-d46ad8d2.tar.gz%255D(https://cloudius-jenkins-test.s3.amazonaws.com/d46ad8d2-7a79-4fdb-a81d-0622f2c13c54/20220311_110835/loader-set-d46ad8d2.tar.gz)&source=gmail-html&ust=1647363008801000&usg=AOvVaw09DY0Q3DmGuo_qNlbrCltH)
monitor-set - [[https://cloudius-jenkins-test.s3.amazonaws.com/d46ad8d2-7a79-4fdb-a81d-0622f2c13c54/20220311_110835/monitor-set-d46ad8d2.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/d46ad8d2-7a79-4fdb-a81d-0622f2c13c54/20220311_110835/monitor-set-d46ad8d2.tar.gz)](https://www.google.com/url?q=https://cloudius-jenkins-test.s3.amazonaws.com/d46ad8d2-7a79-4fdb-a81d-0622f2c13c54/20220311_110835/monitor-set-d46ad8d2.tar.gz%255D(https://cloudius-jenkins-test.s3.amazonaws.com/d46ad8d2-7a79-4fdb-a81d-0622f2c13c54/20220311_110835/monitor-set-d46ad8d2.tar.gz)&source=gmail-html&ust=1647363008801000&usg=AOvVaw11ZB6saZAeihf2-tUJ_A7Q)
sct - [[https://cloudius-jenkins-test.s3.amazonaws.com/d46ad8d2-7a79-4fdb-a81d-0622f2c13c54/20220311_110835/sct-runner-d46ad8d2.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/d46ad8d2-7a79-4fdb-a81d-0622f2c13c54/20220311_110835/sct-runner-d46ad8d2.tar.gz)](https://www.google.com/url?q=https://cloudius-jenkins-test.s3.amazonaws.com/d46ad8d2-7a79-4fdb-a81d-0622f2c13c54/20220311_110835/sct-runner-d46ad8d2.tar.gz%255D(https://cloudius-jenkins-test.s3.amazonaws.com/d46ad8d2-7a79-4fdb-a81d-0622f2c13c54/20220311_110835/sct-runner-d46ad8d2.tar.gz)&source=gmail-html&ust=1647363008801000&usg=AOvVaw2rlaSXL299VOtUGXzF1ebg)

[Jenkins job URL]([https://jenkins.scylladb.com/job/scylla-master/job/longevity/job/longevity-twcs-48h-test/23/](https://www.google.com/url?q=https://jenkins.scylladb.com/job/scylla-master/job/longevity/job/longevity-twcs-48h-test/23/&source=gmail-html&ust=1647363008801000&usg=AOvVaw3eT5BsxPyyKzLyPuSDopoW))

**Comment by bhalevy** [comment] 2022-03-17 05:33
@juliayakovlev the build-id mentioned above is not found.  I'm not sure where you got it...

There is http://downloads.scylladb.com.s3.amazonaws.com/unstable/scylla/master/relocatable/2022-03-03T09%3A12%3A28Z/00-Build.txt with build-id `50417b5f861f252373a1b082cf81d551a1775564`

That seems to produce a sensible decoded backtrace:
```
seastar::internal::future_base::detach_promise() at ./build/release/seastar/./seastar/include/seastar/core/future.hh:1170
 (inlined by) seastar::internal::future_base::clear() at ./build/release/seastar/./seastar/include/seastar/core/future.hh:1160
 (inlined by) ~future_base at ./build/release/seastar/./seastar/include/seastar/core/future.hh:1165
 (inlined by) ~future at ./build/release/seastar/./seastar/include/seastar/core/future.hh:1337
 (inlined by) seastar::reactor::configure(seastar::reactor_options const&) at ./build/release/seastar/./seastar/src/core/reactor.cc:1437
std::_Function_handler<void (), seastar::smp::configure(seastar::smp_options const&, seastar::reactor_options const&)::$_89>::_M_invoke(std::_Any_data const&) at reactor.cc:?
 (inlined by) operator() at ./build/release/seastar/./seastar/src/core/reactor.cc:4119
 (inlined by) void std::__invoke_impl<void, seastar::smp::configure(seastar::smp_options const&, seastar::reactor_options const&)::$_89&>(std::__invoke_other, seastar::smp::configure(seastar::smp_options const&, seastar::reactor_options const&)::$_89&) at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/invoke.h:61
 (inlined by) std::enable_if<is_invocable_r_v<void, seastar::smp::configure(seastar::smp_options const&, seastar::reactor_options const&)::$_89&>, void>::type std::__invoke_r<void, seastar::smp::configure(seastar::smp_options const&, seastar::reactor_options const&)::$_89&>(seastar::smp::configure(seastar::smp_options const&, seastar::reactor_options const&)::$_89&) at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/invoke.h:111
 (inlined by) std::_Function_handler<void (), seastar::smp::configure(seastar::smp_options const&, seastar::reactor_options const&)::$_89>::_M_invoke(std::_Any_data const&) at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/std_function.h:290
?? ??:0
/data/scylla-s3-reloc.cache/by-build-id/50417b5f861f252373a1b082cf81d551a1775564/extracted/scylla/libexec/scylladb/libreloc/libc.so.6 0x3d2a1 
/data/scylla-s3-reloc.cache/by-build-id/50417b5f861f252373a1b082cf81d551a1775564/extracted/scylla/libexec/scylladb/libreloc/libc.so.6 0x268a3 
/data/scylla-s3-reloc.cache/by-build-id/50417b5f861f252373a1b082cf81d551a1775564/extracted/scylla/libexec/scylladb/libreloc/libc.so.6 0x26788 
/data/scylla-s3-reloc.cache/by-build-id/50417b5f861f252373a1b082cf81d551a1775564/extracted/scylla/libexec/scylladb/libreloc/libc.so.6 0x35a15 
service::abstract_read_resolver::fail_request(utils::exception_container<exceptions::mutation_write_timeout_exception, exceptions::read_timeout_exception, exceptions::read_failure_exception>&&) at ./service/storage_proxy.cc:2861
 (inlined by) service::digest_read_resolver::on_timeout() at ./service/storage_proxy.cc:2922
service::digest_read_resolver::response_count() const at storage_proxy.cc:?
boost::intrusive::list_node_traits<void*>::get_next(boost::intrusive::list_node<void*>* const&) at /usr/include/boost/intrusive/detail/list_node.hpp:63
 (inlined by) boost::intrusive::list_impl<boost::intrusive::mhtraits<seastar::timer<seastar::manual_clock>, boost::intrusive::list_member_hook<>, &seastar::timer<seastar::manual_clock>::_link>, unsigned long, true, void>::begin() at /usr/include/boost/intrusive/list.hpp:398
 (inlined by) void boost::intrusive::list_impl<boost::intrusive::mhtraits<seastar::timer<seastar::manual_clock>, boost::intrusive::list_member_hook<>, &seastar::timer<seastar::manual_clock>::_link>, unsigned long, true, void>::clear_and_dispose<boost::intrusive::detail::null_disposer>(boost::intrusive::detail::null_disposer) at /usr/include/boost/intrusive/list.hpp:748
 (inlined by) boost::intrusive::list_impl<boost::intrusive::mhtraits<seastar::timer<seastar::manual_clock>, boost::intrusive::list_member_hook<>, &seastar::timer<seastar::manual_clock>::_link>, unsigned long, true, void>::clear() at /usr/include/boost/intrusive/list.hpp:726
 (inlined by) ~list_impl at /usr/include/boost/intrusive/list.hpp:253
 (inlined by) void seastar::reactor::complete_timers<seastar::timer_set<seastar::timer<seastar::manual_clock>, &seastar::timer<seastar::manual_clock>::_link>, boost::intrusive::list<seastar::timer<seastar::manual_clock>, boost::intrusive::member_hook<seastar::timer<seastar::manual_clock>, boost::intrusive::list_member_hook<>, &seastar::timer<seastar::manual_clock>::_link> >, seastar::reactor::expire_manual_timers()::$_76>(seastar::timer_set<seastar::timer<seastar::manual_clock>, &seastar::timer<seastar::manual_clock>::_link>&, boost::intrusive::list<seastar::timer<seastar::manual_clock>, boost::intrusive::member_hook<seastar::timer<seastar::manual_clock>, boost::intrusive::list_member_hook<>, &seastar::timer<seastar::manual_clock>::_link> >&, seastar::reactor::expire_manual_timers()::$_76&&) at ./build/release/seastar/./seastar/src/core/reactor.cc:1364
 (inlined by) seastar::reactor::expire_manual_timers() at ./build/release/seastar/./seastar/src/core/reactor.cc:2408
operator() at ./build/release/seastar/./seastar/src/core/reactor.cc:3153
 (inlined by) operator() at ./build/release/seastar/./seastar/include/seastar/core/future.hh:1668
 (inlined by) void seastar::futurize<void>::satisfy_with_result_of<seastar::future<void>::then_wrapped_nrvo<void, seastar::syscall_work_queue::submit_item(std::unique_ptr<seastar::syscall_work_queue::work_item, std::default_delete<seastar::syscall_work_queue::work_item> >)::$_45>(seastar::syscall_work_queue::submit_item(std::unique_ptr<seastar::syscall_work_queue::work_item, std::default_delete<seastar::syscall_work_queue::work_item> >)::$_45&&)::{lambda(seastar::internal::promise_base_with_type<void>&&, seastar::syscall_work_queue::submit_item(std::unique_ptr<seastar::syscall_work_queue::work_item, std::default_delete<seastar::syscall_work_queue::work_item> >)::$_45&, seastar::future_state<seastar::internal::monostate>&&)#1}::operator()(seastar::internal::promise_base_with_type<void>&&, seastar::syscall_work_queue::submit_item(std::unique_ptr<seastar::syscall_work_queue::work_item, std::default_delete<seastar::syscall_work_queue::work_item> >)::$_45&, seastar::future_state<seastar::internal::monostate>&&) const::{lambda()#1}>(seastar::internal::promise_base_with_type<void>&&, seastar::future<void>::then_wrapped_nrvo<void, seastar::syscall_work_queue::submit_item(std::unique_ptr<seastar::syscall_work_queue::work_item, std::default_delete<seastar::syscall_work_queue::work_item> >)::$_45>(seastar::syscall_work_queue::submit_item(std::unique_ptr<seastar::syscall_work_queue::work_item, std::default_delete<seastar::syscall_work_queue::work_item> >)::$_45&&)::{lambda(seastar::internal::promise_base_with_type<void>&&, seastar::syscall_work_queue::submit_item(std::unique_ptr<seastar::syscall_work_queue::work_item, std::default_delete<seastar::syscall_work_queue::work_item> >)::$_45&, seastar::future_state<seastar::internal::monostate>&&)#1}::operator()(seastar::internal::promise_base_with_type<void>&&, seastar::syscall_work_queue::submit_item(std::unique_ptr<seastar::syscall_work_queue::work_item, std::default_delete<seastar::syscall_work_queue::work_item> >)::$_45&, seastar::future_state<seastar::internal::monostate>&&) const::{lambda()#1}&&) at ./build/release/seastar/./seastar/include/seastar/core/future.hh:2117
 (inlined by) operator() at ./build/release/seastar/./seastar/include/seastar/core/future.hh:1667
 (inlined by) seastar::continuation<seastar::internal::promise_base_with_type<void>, seastar::syscall_work_queue::submit_item(std::unique_ptr<seastar::syscall_work_queue::work_item, std::default_delete<seastar::syscall_work_queue::work_item> >)::$_45, seastar::future<void>::then_wrapped_nrvo<void, seastar::syscall_work_queue::submit_item(std::unique_ptr<seastar::syscall_work_queue::work_item, std::default_delete<seastar::syscall_work_queue::work_item> >)::$_45>(seastar::syscall_work_queue::submit_item(std::unique_ptr<seastar::syscall_work_queue::work_item, std::default_delete<seastar::syscall_work_queue::work_item> >)::$_45&&)::{lambda(seastar::internal::promise_base_with_type<void>&&, seastar::syscall_work_queue::submit_item(std::unique_ptr<seastar::syscall_work_queue::work_item, std::default_delete<seastar::syscall_work_queue::work_item> >)::$_45&, seastar::future_state<seastar::internal::monostate>&&)#1}, void>::run_and_dispose() at ./build/release/seastar/./seastar/include/seastar/core/future.hh:767
~_Function_base at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/std_function.h:243
 (inlined by) function at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/std_function.h:395
 (inlined by) seastar::reactor::do_run() at ./build/release/seastar/./seastar/src/core/reactor.cc:2962
~_Vector_base at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/stl_vector.h:335
 (inlined by) ~vector at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/stl_vector.h:683
 (inlined by) operator() at ./build/release/seastar/./seastar/src/core/reactor.cc:4119
 (inlined by) void std::__invoke_impl<void, seastar::smp::configure(seastar::smp_options const&, seastar::reactor_options const&)::$_89&>(std::__invoke_other, seastar::smp::configure(seastar::smp_options const&, seastar::reactor_options const&)::$_89&) at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/invoke.h:61
 (inlined by) std::enable_if<is_invocable_r_v<void, seastar::smp::configure(seastar::smp_options const&, seastar::reactor_options const&)::$_89&>, void>::type std::__invoke_r<void, seastar::smp::configure(seastar::smp_options const&, seastar::reactor_options const&)::$_89&>(seastar::smp::configure(seastar::smp_options const&, seastar::reactor_options const&)::$_89&) at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/invoke.h:111
 (inlined by) std::_Function_handler<void (), seastar::smp::configure(seastar::smp_options const&, seastar::reactor_options const&)::$_89>::_M_invoke(std::_Any_data const&) at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/std_function.h:290
std::__uniq_ptr_impl<char, seastar::mmap_deleter>::operator=(std::__uniq_ptr_impl<char, seastar::mmap_deleter>&&) at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/unique_ptr.h:168
 (inlined by) std::__uniq_ptr_data<char, seastar::mmap_deleter, true, true>::operator=(std::__uniq_ptr_data<char, seastar::mmap_deleter, true, true>&&) at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/unique_ptr.h:212
 (inlined by) std::unique_ptr<char [], seastar::mmap_deleter>::operator=(std::unique_ptr<char [], seastar::mmap_deleter>&&) at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/unique_ptr.h:623
 (inlined by) posix_thread at ./build/release/seastar/./seastar/src/core/posix.cc:82
```

So it is apparently a duplicate of #10193

**Closed by bhalevy** 2022-03-17 05:33 UTC
