### ISSUE TITLE
Sstable can't be read: std::runtime_error (compressed chunk failed checksum)

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla#8871] opened 2021-06-16 15:56 UTC
Hi, I am touching exactly the same problem in scylla 4.4.2 on Debian buster, but I found out that scylla corrupts data on other nodes during a failed repair.
On my scylla cluster 4 + 4 nodes in 2 DC (AMD epyc 7402P, 256GB RAM 6x Micron 4TB NVMe in SW RAID0) after upgraded to version 4.4.2, two nodes not started, because they have corrupted data. In log, I found repeated message `[shard 11] compaction_manager - compaction failed: std::runtime_error (compressed chunk failed checksum): retrying`.  Some of corupted files is visible as pending compactions in grafana/prometheus.
Then after upgrade and restart, scylla is trying to reshape shard 11, but without success and scylla is going down.
So I check all db files on nodes and found, that around 10 from ~8000 files on each node is corrupted and crc32 file not correspond with computed crc32.
All corupted files is ending with zeroes:
```
scylla-omg2.ko(scylla-omg2.ko):~ # hexdump -v /www/scylla/data/data/user_history/ad_impression-42a280007cdb11eb9b26000000000000/md-1278109-big-Data.db |tail -n 10
00b67f0 0000 0000 0000 0000 0000 0000 0000 0000
00b6800 0000 0000 0000 0000 0000 0000 0000 0000
00b6810 0000 0000 0000 0000 0000 0000 0000 0000
00b6820 0000 0000 0000 0000 0000 0000 0000 0000
00b6830 0000 0000 0000 0000 0000 0000 0000 0000
00b6840 0000 0000 0000 0000 0000 0000 0000 0000
00b6850 0000 0000 0000 0000 0000 0000 0000 0000
00b6860 0000 0000 0000 0000 0000 0000 0000 0000
00b6870 0000                                   
00b6871
```
EDIT:
All zeros start at round addresses:
```
087bfe0 56df 9362 c3f5 6fdb 4f64 0895 c03f d91a
087bff0 408f cd91 72ba 3483 8123 66c8 8772 d8d1
087c000 0000 0000 0000 0000 0000 0000 0000 0000
087c010 0000 0000 0000 0000 0000 0000 0000 0000
```
```
089afe0 877d 6acf 8aca 5000 0aa7 c131 2804 1802
089aff0 2ea7 8c00 e5d2 08b2 6202 1ee4 002e a440
089b000 0000 0000 0000 0000 0000 0000 0000 0000
089b010 0000 0000 0000 0000 0000 0000 0000 0000
```
```
0976fe0 e129 8775 0f68 f1a9 0f00 00f3 5301 989c
0976ff0 f6b2 f39f 4000 63a9 55b2 00d8 f700 0c00
0977000 0000 0000 0000 0000 0000 0000 0000 0000
0977010 0000 0000 0000 0000 0000 0000 0000 0000
```

After this I stopping node, remove corrupted files and startting again on whole cluster. Everything looks good, 0 pending compactions. I again check crc on data files without error, so i run nodetool repair on node which have 100% of data: 
```UN  10.249.30.42   1.79 TB    256          100.0%            f4967d38-af26-4430-8e97-2066dfb73a57  rack30```
After few hours repair crashed:
```
scylla-omg4.ko(scylla-omg4.ko):~ # nodetool repair
Using /www/scylla/conf/scylla.yaml as the config file
[2021-06-15 13:53:29,834] Starting repair command #1, repairing 1 ranges for keyspace user_history (parallelism=SEQUENTIAL, full=true)
Exception occurred during clean-up. javax.management.ListenerNotFoundException: Listener not found
Cassandra has shutdown.
error: [2021-06-15 17:57:46,323] JMX connection closed. You should check server log for repair status of keyspace user_history(Subsequent keyspaces are not going to be repaired).
-- StackTrace --
java.io.IOException: [2021-06-15 17:57:46,323] JMX connection closed. You should check server log for repair status of keyspace user_history(Subsequent keyspaces are not going to be repaired).
        at org.apache.cassandra.tools.RepairRunner.handleConnectionFailed(RepairRunner.java:103)
        at org.apache.cassandra.utils.progress.jmx.JMXNotificationProgressListener.handleNotification(JMXNotificationProgressListener.java:86)
        at java.management/javax.management.NotificationBroadcasterSupport.handleNotification(NotificationBroadcasterSupport.java:275)
        at java.management/javax.management.NotificationBroadcasterSupport$SendNotifJob.run(NotificationBroadcasterSupport.java:352)
        at java.management/javax.management.NotificationBroadcasterSupport$1.execute(NotificationBroadcasterSupport.java:337)
        at java.management/javax.management.NotificationBroadcasterSupport.sendNotification(NotificationBroadcasterSupport.java:248)
        at java.management.rmi/javax.management.remote.rmi.RMIConnector.sendNotification(RMIConnector.java:442)
        at java.management.rmi/javax.management.remote.rmi.RMIConnector$RMIClientCommunicatorAdmin.gotIOException(RMIConnector.java:1528)
        at java.management.rmi/javax.management.remote.rmi.RMIConnector$RMINotifClient.fetchNotifs(RMIConnector.java:1354)
        at java.management/com.sun.jmx.remote.internal.ClientNotifForwarder$NotifFetcher.fetchOneNotif(ClientNotifForwarder.java:705)
        at java.management/com.sun.jmx.remote.internal.ClientNotifForwarder$NotifFetcher.fetchNotifs(ClientNotifForwarder.java:657)
        at java.management/com.sun.jmx.remote.internal.ClientNotifForwarder$NotifFetcher.doRun(ClientNotifForwarder.java:493)
        at java.management/com.sun.jmx.remote.internal.ClientNotifForwarder$NotifFetcher.run(ClientNotifForwarder.java:474)
        at java.management/com.sun.jmx.remote.internal.ClientNotifForwarder$LinearExecutor.lambda$execute$0(ClientNotifForwarder.java:108)
        at java.base/java.lang.Thread.run(Thread.java:834)
```
In log I found many `[shard 27] storage_proxy - Failed to apply mutation from 10.249.71.34#27: seastar::named_semaphore_timed_out (Semaphore timed out: smp_service_group#3 2->27 semaphore)`, failed repair and many others errors, min. 1GB of errors.
Pending compactions are back, so I am now checking all crc32 of db files. Until now I found around 20 corrupted data files ending with zeroes across cluster. Picture of repair and after that pending compactions visualize corrupted files:
![obrazek](https://user-images.githubusercontent.com/85985694/122177626-1482fb80-ce86-11eb-9328-773dec6ef2e9.png)

**Comment by slivne** [comment] 2021-06-16 15:57
@luboshynek this is the moved issue I'll try to coy Raphael's comments as well.

**Comment by slivne** [comment] 2021-06-16 15:58
@raphaelsc wrote

> @luboshynek what's your kernel version? please also share xfs_info on your fs.
> it's interesting that 087c000 isn't aligned to buffer size used for writing sstables. @luboshynek are there holes in the middle of the corrupted files or only at the end? how frequent is corruption happening to you?
> @luboshynek could you please send me logs when repair failed up to the moment which corruption was reported?
>it's said that corruption happened post failed repair, so perhaps producer failed to propagate exception to consumer (sstable writer) while a new sst was being written. Remember Gleb fixed something similar a long time ago, but perhaps we still do have a similar bug elsewhere.

**Comment by slivne** [comment] 2021-06-16 16:01
@luboshynek  additional requests/questions:

1. In the past we had an issue with mixed smp cluster,  nodes running with different smp core count - can you please provide us from all the nodes `ps -ef | grep scylla` so we can check the status on your end.
2. Did you run repair prior to the upgrade, and if so on which scylla version did you run it ?

**Comment by bhalevy** [comment] 2021-06-16 16:07
@raphaelsc 0x087c000 is a multiple of 16KB, which is the commitlog `buf_size`
https://github.com/scylladb/scylla/blob/2b29568bf4180f881ca6287b182cb166a720dae3/db/commitlog/commitlog.cc#L1331

**Comment by luboshynek** [comment] 2021-06-16 22:53
Hi, and thanks for answer.
Kernel is stock Debian kernel: `4.19.0-9-amd64 #1 SMP Debian 4.19.118-2+deb10u1 (2020-06-07) x86_64 GNU/Linux`
```
scylla-omg2.ng(scylla-omg2.ng):~ # xfs_info /dev/md1p4
meta-data=/dev/md1p4             isize=512    agcount=32, agsize=175697536 blks
         =                       sectsz=512   attr=2, projid32bit=1
         =                       crc=1        finobt=1, sparse=1, rmapbt=0
         =                       reflink=0
data     =                       bsize=4096   blocks=5622318843, imaxpct=5
         =                       sunit=128    swidth=768 blks
naming   =version 2              bsize=4096   ascii-ci=0, ftype=1
log      =internal log           bsize=4096   blocks=521728, version=2
         =                       sectsz=512   sunit=16 blks, lazy-count=1
realtime =none                   extsz=4096   blocks=0, rtextents=0
```
```
scylla-omg2.ng(scylla-omg2.ng):~ # mdadm --detail /dev/md1p4
/dev/md1p4:
           Version : 1.2
     Creation Time : Fri Mar  5 16:33:46 2021
        Raid Level : raid0
        Array Size : 22489275375 (21447.44 GiB 23029.02 GB)
      Raid Devices : 6
     Total Devices : 6
       Persistence : Superblock is persistent

       Update Time : Fri Mar  5 16:33:46 2021
             State : clean 
    Active Devices : 6
   Working Devices : 6
    Failed Devices : 0
     Spare Devices : 0

        Chunk Size : 512K

Consistency Policy : none

              Name : live-10-249-186-248:1
              UUID : b085ce0d:8ce0d58e:d94c3033:ee5f65ad
            Events : 0

    Number   Major   Minor   RaidDevice State
       0     259       14        0      active sync   /dev/nvme1n1p2
       1     259       22        1      active sync   /dev/nvme4n1p2
       2     259       11        2      active sync   /dev/nvme2n1p2
       3     259       19        3      active sync   /dev/nvme5n1p2
       4     259        2        4      active sync   /dev/nvme0n1p2
       5     259        8        5      active sync   /dev/nvme3n1p2
```
zeros is only at end of file, but not always same size:
```
0092fe0 e773 038b 8525 3f4d 5b98 12f3 9f12 d9bc
0092ff0 9ef1 cee3 834c 97b9 3fe3 4ce2 9253 e547
0093000 0000 0000 0000 0000 0000 0000 0000 0000
0093010 0000 0000 0000 0000 0000 0000 0000 0000
0093020 0000 0000 0000 0000 0000 0000 0000 0000
0093030 0000 0000 0000 0000 0000 0000 0000 0000
0093040 0000 0000 0000 0000 0000 0000 0000 0000
0093050 0000 0000 0000 0000 0000 0000 0000 0000
0093060 0000 0000 0000 0000 0000 0000 0000 0000
0093070 0000 0000 0000 0000 0000 0000 0000 0000
0093080 0000 0000 0000 0000 0000 0000 0000 0000
0093090 0000 0000 0000 0000 0000 0000 0000 0000
00930a0 0000 0000 0000 0000 0000 0000 0000 0000
00930b0 0000 0000 0000 0000 0000 0000 0000 0000
00930c0 0000 0000 0000 0000 0000 0000 0000 0000
00930d0 0000 0000 0000 0000 0000 0000 0000 0000
00930e0 0000 0000 0000 0000 0000 0000 0000 0000
00930f0 0000 0000 0000 0000 0000 0000 0000 0000
0093100 0000 0000 0000 0000 0000 0000 0000 0000
0093110 0000 0000 0000 0000 0000 0000 0000 0000
0093120 0000 0000 0000 0000 0000 0000 0000 0000
0093130 0000 0000 0000 0000 0000 0000 0000 0000
0093140 0000 0000 0000 0000 0000 0000 0000 0000
009314f
(END)
```
```
ps -ef | grep scylla from all nodes:
scylla   27346     1 99 13:56 ?        4-06:43:18 /usr/bin/scylla --log-to-syslog 1 --log-to-stdout 0 --default-log-level info --network-stack posix --io-properties-file=/etc/scylla.d/io_properties.yaml
scylla    8174     1 99 14:10 ?        5-21:15:08 /usr/bin/scylla --log-to-syslog 1 --log-to-stdout 0 --default-log-level info --network-stack posix --io-properties-file=/etc/scylla.d/io_properties.yaml
scylla   23242     1 99 Jun15 ?        22-22:30:33 /usr/bin/scylla --log-to-syslog 1 --log-to-stdout 0 --default-log-level info --network-stack posix --io-properties-file=/etc/scylla.d/io_properties.yaml
scylla   48805     1 99 14:41 ?        3-02:06:18 /usr/bin/scylla --log-to-syslog 1 --log-to-stdout 0 --default-log-level info --network-stack posix --io-properties-file=/etc/scylla.d/io_properties.yaml
scylla   49115     1 99 14:04 ?        4-03:56:46 /usr/bin/scylla --log-to-syslog 1 --log-to-stdout 0 --default-log-level info --network-stack posix --io-properties-file=/etc/scylla.d/io_properties.yaml
scylla   18935     1 99 14:21 ?        2-23:36:42 /usr/bin/scylla --log-to-syslog 1 --log-to-stdout 0 --default-log-level info --network-stack posix --io-properties-file=/etc/scylla.d/io_properties.yaml
scylla   14876     1 99 14:34 ?        3-00:25:10 /usr/bin/scylla --log-to-syslog 1 --log-to-stdout 0 --default-log-level info --network-stack posix --io-properties-file=/etc/scylla.d/io_properties.yaml
scylla    1448     1 99 22:57 ?        01:45:50 /usr/bin/scylla --log-to-syslog 1 --log-to-stdout 0 --default-log-level info --network-stack posix --io-properties-file=/etc/scylla.d/io_properties.yaml
```
It is scylla 4.4.2, 2 weeks ago upgraded from 4.4.1 and before from 4.4.rc1, which installed in march.  Before 4.4.2 version, scylla logs about 50GB per day, because this [bug](https://github.com/scylladb/scylla/issues/8411), so i dont know exactly when crc error ocured. Pending compactions exist on cluster at least last month.

**Comment by gleb-cloudius** [comment] 2021-06-17 07:23
Does he have nodes with different shard count. If yes it may be streaming bug that @psarna fixed. Not sure if the version they use here is affected.

**Comment by raphaelsc** [comment] 2021-06-17 15:11
@luboshynek please run "xfs_bmap -vvp /path/to/file" on corrupted data files. I would like to rule out unwritten extent as being the root cause.

**Comment by raphaelsc** [comment] 2021-06-17 15:20
> Does he have nodes with different shard count. If yes it may be streaming bug that @psarna fixed. Not sure if the version they use here is affected.

@gleb-cloudius could you please share the issue number?

**Comment by slivne** [comment] 2021-06-17 22:32
I think you meant botond:
https://github.com/scylladb/scylla/issues/7623, https://github.com/scylladb/scylla/issues/7552

AFAIK 4.4.0 should have this fixed.

**Comment by bhalevy** [comment] 2021-06-27 07:46
> > Does he have nodes with different shard count. If yes it may be streaming bug that @psarna fixed. Not sure if the version they use here is affected.
> 
> @gleb-cloudius could you please share the issue number?

@raphaelsc the symptoms look very different.
With #7552 and #7623 we ended up with logically corrupt sstables due to reordering of mutation_fragments over the smp queues.
Here's it's zeroed out blocks.

**Comment by avikivity** [comment] 2021-06-27 09:56
No update from reporter, closing.

**Closed by avikivity** 2021-06-27 09:56 UTC

**Comment by luboshynek** [comment] 2021-12-14 08:22
Final resolution:
The data corruption was caused by the firmware on the NVMe Micron 7300 8TB. After upgrading from version 95420100 to version 95420260 everything is fine now. Thanks for support.

**Comment by bhalevy** [comment] 2021-12-14 09:19
> Final resolution: The data corruption was caused by the firmware on the NVMe Micron 7300 8TB. After upgrading from version 95420100 to version 95420260 everything is fine now. Thanks for support.

@luboshynek thanks for the update!
