### ISSUE TITLE
REST API malfunction (code 404, no such file or directory)

### ISSUE THREAD

**Issue by user31459** [scylladb/scylla#2380] opened 2017-05-15 08:14 UTC
Scylla version: 1.6.4-20170425.65862c4
Cluster size: 3
OS: CentOS 7.3
Configuration: [scylla_yaml.txt](https://github.com/scylladb/scylla/files/1000463/scylla_yaml.txt)

The REST API is malfunctioning after a fresh installation:

The listener looks ok
```

# netstat -natp | grep 10000
tcp        0      0 10.10.10.109:10000      0.0.0.0:*               LISTEN      16763/scylla
```

Simple curl to the API fails
```
# curl 10.10.10.109:10000
{"message": "Not found", "code": 404}
```

In browser http://10.10.10.109:10000/ui
```
{"message": "No such file or directory", "code": 500}
```

[startup_log.txt](https://github.com/scylladb/scylla/files/1000461/startup_log.txt)

The housekeeping service also fails on startup because it cannot connect to the API. If the api_address in scylla.yaml is changed to 127.0.0.1 housekeeping starts, but fails to get any version information.
```
May 15 07:44:24 scy009 systemd: Started Scylla Housekeeping.
May 15 07:44:24 scy009 systemd: Starting Scylla Housekeeping...
May 15 07:44:24 scy009 scylla-housekeeping: Traceback (most recent call last):
May 15 07:44:24 scy009 scylla-housekeeping: File "/usr/lib/scylla/scylla-housekeeping", line 128, in <module>
May 15 07:44:24 scy009 scylla-housekeeping: args.func(args)
May 15 07:44:24 scy009 scylla-housekeeping: File "/usr/lib/scylla/scylla-housekeeping", line 78, in check_version
May 15 07:44:24 scy009 scylla-housekeeping: current_version = get_api('/storage_service/scylla_release_version')
May 15 07:44:24 scy009 scylla-housekeeping: File "/usr/lib/scylla/scylla-housekeeping", line 63, in get_api
May 15 07:44:24 scy009 scylla-housekeeping: return get_json_from_url("http://localhost:10000" + path)
May 15 07:44:24 scy009 scylla-housekeeping: File "/usr/lib/scylla/scylla-housekeeping", line 60, in get_json_from_url
May 15 07:44:24 scy009 scylla-housekeeping: return json.loads(data)
May 15 07:44:24 scy009 scylla-housekeeping: File "/usr/lib64/python2.7/json/__init__.py", line 338, in loads
May 15 07:44:24 scy009 scylla-housekeeping: return _default_decoder.decode(s)
May 15 07:44:24 scy009 scylla-housekeeping: File "/usr/lib64/python2.7/json/decoder.py", line 366, in decode
May 15 07:44:24 scy009 scylla-housekeeping: obj, end = self.raw_decode(s, idx=_w(s, 0).end())
May 15 07:44:24 scy009 scylla-housekeeping: File "/usr/lib64/python2.7/json/decoder.py", line 384, in raw_decode
May 15 07:44:24 scy009 scylla-housekeeping: raise ValueError("No JSON object could be decoded")
May 15 07:44:24 scy009 scylla-housekeeping: ValueError: No JSON object could be decoded
May 15 07:44:24 scy009 systemd: scylla-housekeeping.service: main process exited, code=exited, status=1/FAILURE
May 15 07:44:24 scy009 systemd: Unit scylla-housekeeping.service entered failed state.
May 15 07:44:24 scy009 systemd: scylla-housekeeping.service failed.
```

**Comment by amnonh** [comment] 2017-05-15 08:44
From the traces and logs you included, it seems that the Rest API works.
Try:

curl -X GET "http://10.10.10.109:10000/storage_service/scylla_release_version"


What you see is that Scylla can not find the Swagger UI files, those files
are used for the graphic interface.
Is it possible that you run scylla from a different location?
In the configuration there are two parameters:
api-ui-dir that points to the swagger-ui path
api-doc that points to the swagger definition files.

**Comment by user31459** [comment] 2017-05-15 10:40
Just verified the REST call, that seems to work ok (even though housekeeping breaks when using an address not resolving to localhost).

I run Scylla via systemd as provided in the CentOS RPM. The files mentioned reside in /lib/scylla/swagger-ui and /lib/scylla/api/api-doc, but these paths are not configured anywhere. Shall I set these paths in scylla.yaml?

**Comment by amnonh** [comment] 2017-05-15 11:22
On Mon, May 15, 2017 at 1:40 PM, user31459 <notifications@github.com> wrote:

> Just verified the REST call, that seems to work ok (even though
> housekeeping breaks when using an address not resolving to localhost).
>
> I run Scylla via systemd as provided in the CentOS RPM. The files
> mentioned reside in /lib/scylla/swagger-ui and /lib/scylla/api/api-doc, but
> these paths are not configured anywhere. Shall I set these paths in
> scylla.yaml?
>
By default scylla would look for a relevent path of swagger-ui/dist/ and
api/api-doc/
Make sure the directory are there with permissions that would allow the
scylla application to read the files from.

You can put the full path to the files in scylla.yaml, usually, it is not
needed.

**Comment by user31459** [comment] 2017-05-15 12:33
Just as side note: This is a plain RPM installation, I didn't do any funky path configuration. That said, if ich set api_ui_dir and api_doc I get an index.html served at /ui, but none of the css/js files make it to the browser (404). 

Additional info:
- selinux is switched off completely
- permissions are standard (from RPM) and the files are world readable

**Comment by slivne** [comment] 2017-07-24 14:44
need to look why the swagger files are not uploaded

**Comment by slivne** [comment] 2017-12-21 11:40
@amnonh ping

**Comment by slivne** [comment] 2017-12-21 11:43
@amnonh - how can we get the swagger files ?

**Comment by amnonh** [comment] 2017-12-21 11:53
http://localhost:10000/api-doc

**Comment by amnonh** [comment] 2017-12-24 13:57
I think we can close this

**Comment by slivne** [comment] 2017-12-24 14:40
please verify this on a real installation not your laptop

**Comment by tzach** [comment] 2017-12-31 10:39
@amnonh did you validate?

**Comment by amnonh** [comment] 2018-01-01 12:20
I've installed on centos with 2.0 and it works
I validate using:
curl http://localhost:10000/ui/

**Comment by slivne** [comment] 2018-01-02 08:10
@amnonh - just to clarify - it works out of the box - you did not need to setup any additional flagfor scylla to get the swagger ui working - is that correct ?

**Comment by amnonh** [comment] 2018-01-02 08:20
@slivne true, just did an installation run scylla and see that it works

**Comment by slivne** [comment] 2018-01-02 08:24
@user31459 - we are not able to reproduce this on 2.0 vanilla install - if following the upgrade to 2.0 you still face an issue we can reopen.

**Closed by slivne** 2018-01-02 08:24 UTC
