### ISSUE TITLE
DTEST TestConcurrentSchemaChanges tests fail with some index statements

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla#2529] opened 2017-06-26 12:27 UTC
*Installation details*
Scylla version (or git commit hash): 555621b5374d72bb993e21c0be6ede38dbbb1a1a

TestConcurrentSchemaChanges.changes_while_node_down_test
TestConcurrentSchemaChanges.create_lots_of_schema_churn_test
TestConcurrentSchemaChanges.changes_while_node_toggle_test

scylladb/scylla-dtest@bbb2db3208699c5f09134107f3eadf2bc6e50913 enabled the index statements 

I am going to comment out the index parts that are causing issues (not reverting everything) 

The tests do not fail in a regular run - you need to enable the virtual env that jenkins uses on monster to replicate the issue.

**Comment by nyh** [comment] 2018-10-10 07:04
Hi @slivne I can't reproduce this bug :-( I tried to set up the "virtual environment" as you explained to me, but it still seems to fail - can I make sure I'm using it correctly? What is the "virtual environment" supposed to be doing that I can verify with some "env" or "ps" or whatever commands?

Do you have any old logs or messages or anything that can give me a hint on what kind of failure we saw?

**Comment by duarten** [comment] 2018-10-10 09:27
These are the commits that should be reverted, right?

https://github.com/scylladb/scylla-dtest/commit/37749b455759bbebfbc139c8867e0ee6af1ba322#diff-07158c476ce98910fa683e5435e220c0

https://github.com/scylladb/scylla-dtest/commit/751a4b4bf58efd657329c085cddc5579e759b64e#diff-07158c476ce98910fa683e5435e220c0

I see no reason for index creation code to not work properly now. This issue is more than one year old :)

**Comment by slivne** [comment] 2018-10-10 09:31
@nyh https://stackoverflow.com/questions/1871549/determine-if-python-is-running-inside-virtualenv ...

I guess one of these will confirm.

@duarten / @nyh - if the tests pass for you with virtualenv we will revert the changes and enable the tests.

**Comment by slivne** [comment] 2018-10-10 12:32
tests enabled - closing the issue https://github.com/scylladb/scylla-dtest/commit/d7a746f90a4c7beaef4b9d65e5f4e027135dd1a9

**Comment by nyh** [comment] 2018-10-10 12:59
@duarte, I reverted https://github.com/scylladb/scylla-dtest/commit/37749b455759bbebfbc139c8867e0ee6af1ba322#diff-07158c476ce98910fa683e5435e220c0
I did NOT revert https://github.com/scylladb/scylla-dtest/commit/751a4b4bf58efd657329c085cddc5579e759b64e#diff-07158c476ce98910fa683e5435e220c0 - I didn't see it...  How did you find it?

I'll try to revert this too, test, and send another PR....

**Comment by duarten** [comment] 2018-10-10 13:01
I looked at the git history for concurrent_schema_test.py or whatever the file is called.

**Comment by nyh** [comment] 2018-10-10 20:33
@duarte, sorry about the wrong links :-( I'll try to make this the last time this happens.
@duarten, I sent another PR and I think Shlomi committed it, so I think we can reclose this issue.

**Comment by duarten** [comment] 2018-10-10 21:08
Oh! :)

**Closed by duarten** 2018-10-10 21:08 UTC
Labels: enhancement, sec-index
