### ISSUE TITLE
Scylla-server.service failed to stop when the node was drained

### ISSUE THREAD

**Issue by aleksbykov** [scylladb/scylla#7332] opened 2020-10-05 09:19 UTC
*Installation details*
Scylla version (or git commit hash): 4.2.rc5-0.20201001.5fcc1f205c
Cluster size: 5
OS (RHEL/CentOS/Ubuntu/AWS AMI): ami-01949a028ae2ee8a7(eu-north-1)
instance type: i3.4xlarge

During these 2 jobs:
https://jenkins.scylladb.com/job/scylla-4.2/job/longevity/job/longevity-mv-si-4days-test/6/

Drainer nemesis failed because scylla stucked during command execution: systemctl stop scylla-server on node7 after draining finished.
Nemesis executed command nodetool drain, then stop the scylla and start it again.
The node7 was drained successfully:
```
2020-10-02T20:51:21+00:00  longevity-mv-si-4d-4-2-db-node-21231adb-7 !INFO    | scylla: [shard 0] storage_service - DRAINING: starting drain process
2020-10-02T20:51:21+00:00  longevity-mv-si-4d-4-2-db-node-21231adb-7 !INFO    | scylla: [shard 0] storage_service - Shutting down native transport
2020-10-02T20:51:22+00:00  longevity-mv-si-4d-4-2-db-node-21231adb-7 !INFO    | sshd[72743]: Accepted publickey for centos from 10.0.1.141 port 39614 ssh2: RSA SHA256:g7OmDbWC8qLUZHxjMohQe3LsQHfcOJbG1ZHqodB6smc
2020-10-02T20:51:22+00:00  longevity-mv-si-4d-4-2-db-node-21231adb-7 !INFO    | systemd-logind: New session 1802 of user centos.
2020-10-02T20:51:22+00:00  longevity-mv-si-4d-4-2-db-node-21231adb-7 !INFO    | systemd: Started Session 1802 of user centos.
2020-10-02T20:51:22+00:00  longevity-mv-si-4d-4-2-db-node-21231adb-7 !INFO    | sshd[72743]: pam_unix(sshd:session): session opened for user centos by (uid=0)
2020-10-02T20:51:22+00:00  longevity-mv-si-4d-4-2-db-node-21231adb-7 !INFO    | sshd[72743]: pam_unix(sshd:session): session closed for user centos
2020-10-02T20:51:22+00:00  longevity-mv-si-4d-4-2-db-node-21231adb-7 !INFO    | systemd-logind: Removed session 1802.
2020-10-02T20:51:23+00:00  longevity-mv-si-4d-4-2-db-node-21231adb-7 !INFO    | scylla: [shard 0] cql_server_controller - CQL server stopped
2020-10-02T20:51:23+00:00  longevity-mv-si-4d-4-2-db-node-21231adb-7 !INFO    | scylla: [shard 0] storage_service - Shutting down native transport was successful
2020-10-02T20:51:23+00:00  longevity-mv-si-4d-4-2-db-node-21231adb-7 !INFO    | scylla: [shard 0] storage_service - Shutting down rpc server
2020-10-02T20:51:23+00:00  longevity-mv-si-4d-4-2-db-node-21231adb-7 !INFO    | scylla: [shard 0] thrift_controller - Thrift server stopped
2020-10-02T20:51:23+00:00  longevity-mv-si-4d-4-2-db-node-21231adb-7 !INFO    | scylla: [shard 0] storage_service - Shutting down rpc server was successful
2020-10-02T20:51:23+00:00  longevity-mv-si-4d-4-2-db-node-21231adb-7 !INFO    | scylla: [shard 0] gossip - My status = NORMAL
2020-10-02T20:51:23+00:00  longevity-mv-si-4d-4-2-db-node-21231adb-7 !INFO    | scylla: [shard 0] gossip - Announcing shutdown
2020-10-02T20:51:23+00:00  longevity-mv-si-4d-4-2-db-node-21231adb-7 !INFO    | scylla: [shard 0] storage_service - Node 10.0.1.151 state jump to normal
2020-10-02T20:51:23+00:00  longevity-mv-si-4d-4-2-db-node-21231adb-7 !INFO    | scylla: [shard 0] storage_service - Remove node 10.0.1.151 from pending replacing endpoint
2020-10-02T20:51:23+00:00  longevity-mv-si-4d-4-2-db-node-21231adb-7 !INFO    | scylla: [shard 0] compaction - Compacting [/var/lib/scylla/data/system/peers-37f71aca7dc2383ba70672528af04d4f/mc-434-big-Data.db:level=0, /var/lib/scylla/data/system/peers-37f71aca7dc2383ba70672528af04d4f/mc-420-big-Data.db:level=0, ]
2020-10-02T20:51:23+00:00  longevity-mv-si-4d-4-2-db-node-21231adb-7 !INFO    | scylla: [shard 0] compaction - Compacted 2 sstables to [/var/lib/scylla/data/system/peers-37f71aca7dc2383ba70672528af04d4f/mc-448-big-Data.db:level=0, ]. 16kB to 76kB (~457% of original) in 21ms = 3MB/s. ~256 total partitions merged to 2.
2020-10-02T20:51:25+00:00  longevity-mv-si-4d-4-2-db-node-21231adb-7 !INFO    | scylla: [shard 0] gossip - Disable and wait for gossip loop started
2020-10-02T20:51:25+00:00  longevity-mv-si-4d-4-2-db-node-21231adb-7 !INFO    | scylla: [shard 0] gossip - Disable and wait for gossip loop finished
2020-10-02T20:51:25+00:00  longevity-mv-si-4d-4-2-db-node-21231adb-7 !INFO    | scylla: [shard 0] gossip - Gossip is now stopped
2020-10-02T20:51:25+00:00  longevity-mv-si-4d-4-2-db-node-21231adb-7 !INFO    | scylla: [shard 0] storage_service - messaging_service stopped
2020-10-02T20:51:25+00:00  longevity-mv-si-4d-4-2-db-node-21231adb-7 !INFO    | scylla: [shard 0] compaction_manager - Stopping 0 ongoing compactions
2020-10-02T20:51:25+00:00  longevity-mv-si-4d-4-2-db-node-21231adb-7 !INFO    | scylla: [shard 1] compaction_manager - Stopping 0 ongoing compactions
2020-10-02T20:51:25+00:00  longevity-mv-si-4d-4-2-db-node-21231adb-7 !INFO    | scylla: [shard 8] compaction_manager - Stopping 0 ongoing compactions
2020-10-02T20:51:25+00:00  longevity-mv-si-4d-4-2-db-node-21231adb-7 !INFO    | scylla: [shard 9] compaction_manager - Stopping 0 ongoing compactions
2020-10-02T20:51:25+00:00  longevity-mv-si-4d-4-2-db-node-21231adb-7 !INFO    | scylla: [shard 5] compaction_manager - Stopping 0 ongoing compactions
2020-10-02T20:51:25+00:00  longevity-mv-si-4d-4-2-db-node-21231adb-7 !INFO    | scylla: [shard 4] compaction_manager - Stopping 0 ongoing compactions
2020-10-02T20:51:25+00:00  longevity-mv-si-4d-4-2-db-node-21231adb-7 !INFO    | scylla: [shard 13] compaction_manager - Stopping 0 ongoing compactions
2020-10-02T20:51:25+00:00  longevity-mv-si-4d-4-2-db-node-21231adb-7 !INFO    | scylla: [shard 11] compaction_manager - Stopping 0 ongoing compactions
2020-10-02T20:51:25+00:00  longevity-mv-si-4d-4-2-db-node-21231adb-7 !INFO    | scylla: [shard 10] compaction_manager - Stopping 0 ongoing compactions
2020-10-02T20:51:25+00:00  longevity-mv-si-4d-4-2-db-node-21231adb-7 !INFO    | scylla: [shard 3] compaction_manager - Stopping 0 ongoing compactions
2020-10-02T20:51:25+00:00  longevity-mv-si-4d-4-2-db-node-21231adb-7 !INFO    | scylla: [shard 2] compaction_manager - Stopping 0 ongoing compactions
2020-10-02T20:51:25+00:00  longevity-mv-si-4d-4-2-db-node-21231adb-7 !INFO    | scylla: [shard 6] compaction_manager - Stopping 0 ongoing compactions
2020-10-02T20:51:25+00:00  longevity-mv-si-4d-4-2-db-node-21231adb-7 !INFO    | scylla: [shard 12] compaction_manager - Stopping 0 ongoing compactions
2020-10-02T20:51:25+00:00  longevity-mv-si-4d-4-2-db-node-21231adb-7 !INFO    | scylla: [shard 7] compaction_manager - Stopping 0 ongoing compactions
2020-10-02T20:51:27+00:00  longevity-mv-si-4d-4-2-db-node-21231adb-7 !INFO    | sshd[72757]: Accepted publickey for centos from 10.0.1.141 port 39642 ssh2: RSA SHA256:g7OmDbWC8qLUZHxjMohQe3LsQHfcOJbG1ZHqodB6smc
2020-10-02T20:51:27+00:00  longevity-mv-si-4d-4-2-db-node-21231adb-7 !INFO    | systemd-logind: New session 1803 of user centos.
2020-10-02T20:51:27+00:00  longevity-mv-si-4d-4-2-db-node-21231adb-7 !INFO    | systemd: Started Session 1803 of user centos.
2020-10-02T20:51:27+00:00  longevity-mv-si-4d-4-2-db-node-21231adb-7 !INFO    | sshd[72757]: pam_unix(sshd:session): session opened for user centos by (uid=0)
2020-10-02T20:51:28+00:00  longevity-mv-si-4d-4-2-db-node-21231adb-7 !INFO    | sshd[72757]: pam_unix(sshd:session): session closed for user centos
2020-10-02T20:51:28+00:00  longevity-mv-si-4d-4-2-db-node-21231adb-7 !INFO    | systemd-logind: Removed session 1803.
2020-10-02T20:51:30+00:00  longevity-mv-si-4d-4-2-db-node-21231adb-7 !INFO    | scylla: [shard 0] migration_manager - stopping migration service
2020-10-02T20:51:30+00:00  longevity-mv-si-4d-4-2-db-node-21231adb-7 !INFO    | scylla: [shard 1] migration_manager - stopping migration service
2020-10-02T20:51:30+00:00  longevity-mv-si-4d-4-2-db-node-21231adb-7 !INFO    | scylla: [shard 5] migration_manager - stopping migration service
2020-10-02T20:51:30+00:00  longevity-mv-si-4d-4-2-db-node-21231adb-7 !INFO    | scylla: [shard 9] migration_manager - stopping migration service
2020-10-02T20:51:30+00:00  longevity-mv-si-4d-4-2-db-node-21231adb-7 !INFO    | scylla: [shard 6] migration_manager - stopping migration service
2020-10-02T20:51:30+00:00  longevity-mv-si-4d-4-2-db-node-21231adb-7 !INFO    | scylla: [shard 3] migration_manager - stopping migration service
2020-10-02T20:51:30+00:00  longevity-mv-si-4d-4-2-db-node-21231adb-7 !INFO    | scylla: [shard 7] migration_manager - stopping migration service
2020-10-02T20:51:30+00:00  longevity-mv-si-4d-4-2-db-node-21231adb-7 !INFO    | scylla: [shard 10] migration_manager - stopping migration service
2020-10-02T20:51:30+00:00  longevity-mv-si-4d-4-2-db-node-21231adb-7 !INFO    | scylla: [shard 8] migration_manager - stopping migration service
2020-10-02T20:51:30+00:00  longevity-mv-si-4d-4-2-db-node-21231adb-7 !INFO    | scylla: [shard 2] migration_manager - stopping migration service
2020-10-02T20:51:30+00:00  longevity-mv-si-4d-4-2-db-node-21231adb-7 !INFO    | scylla: [shard 13] migration_manager - stopping migration service
2020-10-02T20:51:30+00:00  longevity-mv-si-4d-4-2-db-node-21231adb-7 !INFO    | scylla: [shard 4] migration_manager - stopping migration service
2020-10-02T20:51:30+00:00  longevity-mv-si-4d-4-2-db-node-21231adb-7 !INFO    | scylla: [shard 11] migration_manager - stopping migration service
2020-10-02T20:51:30+00:00  longevity-mv-si-4d-4-2-db-node-21231adb-7 !INFO    | scylla: [shard 12] migration_manager - stopping migration service
2020-10-02T20:51:30+00:00  longevity-mv-si-4d-4-2-db-node-21231adb-7 !INFO    | scylla: [shard 0] storage_service - DRAINED:
```
after that scylla-server is going to stop:
"2020-10-02T20:51:32+00:00  longevity-mv-si-4d-4-2-db-node-21231adb-7 !NOTICE  | sudo:  centos : TTY=unknown ; PWD=/home/centos ; USER=root ; COMMAND=/bin/systemctl stop scylla-server.service":

```
2020-10-02T20:51:32+00:00  longevity-mv-si-4d-4-2-db-node-21231adb-7 !INFO    | systemd: Stopped Run Scylla Housekeeping daily mode.
2020-10-02T20:51:32+00:00  longevity-mv-si-4d-4-2-db-node-21231adb-7 !INFO    | systemd: Stopped Run Scylla Housekeeping restart mode.
2020-10-02T20:51:32+00:00  longevity-mv-si-4d-4-2-db-node-21231adb-7 !INFO    | systemd: Stopping Scylla JMX...
2020-10-02T20:51:32+00:00  longevity-mv-si-4d-4-2-db-node-21231adb-7 !INFO    | systemd: Stopped Run Scylla fstrim daily.
2020-10-02T20:51:32+00:00  longevity-mv-si-4d-4-2-db-node-21231adb-7 !NOTICE  | systemd: scylla-jmx.service: main process exited, code=exited, status=143/n/a
2020-10-02T20:51:32+00:00  longevity-mv-si-4d-4-2-db-node-21231adb-7 !INFO    | systemd: Stopped Scylla JMX.
2020-10-02T20:51:32+00:00  longevity-mv-si-4d-4-2-db-node-21231adb-7 !NOTICE  | systemd: Unit scylla-jmx.service entered failed state.
2020-10-02T20:51:32+00:00  longevity-mv-si-4d-4-2-db-node-21231adb-7 !WARNING | systemd: scylla-jmx.service failed.
2020-10-02T20:51:32+00:00  longevity-mv-si-4d-4-2-db-node-21231adb-7 !INFO    | systemd: Stopping Scylla Server...
2020-10-02T20:51:32+00:00  longevity-mv-si-4d-4-2-db-node-21231adb-7 !INFO    | scylla: [shard 0] compaction_manager - Asked to stop
2020-10-02T20:51:32+00:00  longevity-mv-si-4d-4-2-db-node-21231adb-7 !INFO    | scylla: [shard 0] compaction_manager - Stopping 0 ongoing compactions
2020-10-02T20:51:32+00:00  longevity-mv-si-4d-4-2-db-node-21231adb-7 !INFO    | scylla: [shard 0] init - Signal received; shutting down
2020-10-02T20:51:32+00:00  longevity-mv-si-4d-4-2-db-node-21231adb-7 !INFO    | scylla: [shard 0] init - Shutting down redis service
2020-10-02T20:51:32+00:00  longevity-mv-si-4d-4-2-db-node-21231adb-7 !INFO    | scylla: [shard 0] init - Shutting down redis service was successful
2020-10-02T20:51:32+00:00  longevity-mv-si-4d-4-2-db-node-21231adb-7 !INFO    | scylla: [shard 0] init - Shutting down view builder
2020-10-02T20:51:32+00:00  longevity-mv-si-4d-4-2-db-node-21231adb-7 !INFO    | scylla: [shard 0] view - Stopping view builder
2020-10-02T20:51:32+00:00  longevity-mv-si-4d-4-2-db-node-21231adb-7 !INFO    | scylla: [shard 0] compaction_manager - Stopped
2020-10-02T20:51:32+00:00  longevity-mv-si-4d-4-2-db-node-21231adb-7 !INFO    | scylla: [shard 1] compaction_manager - Asked to stop
2020-10-02T20:51:32+00:00  longevity-mv-si-4d-4-2-db-node-21231adb-7 !INFO    | scylla: [shard 2] compaction_manager - Asked to stop
2020-10-02T20:51:32+00:00  longevity-mv-si-4d-4-2-db-node-21231adb-7 !INFO    | scylla: [shard 1] compaction_manager - Stopping 0 ongoing compactions
2020-10-02T20:51:32+00:00  longevity-mv-si-4d-4-2-db-node-21231adb-7 !INFO    | scylla: [shard 1] view - Stopping view builder
2020-10-02T20:51:32+00:00  longevity-mv-si-4d-4-2-db-node-21231adb-7 !INFO    | scylla: [shard 4] compaction_manager - Asked to stop
2020-10-02T20:51:32+00:00  longevity-mv-si-4d-4-2-db-node-21231adb-7 !INFO    | scylla: [shard 3] compaction_manager - Asked to stop
2020-10-02T20:51:32+00:00  longevity-mv-si-4d-4-2-db-node-21231adb-7 !INFO    | scylla: [shard 5] compaction_manager - Asked to stop
2020-10-02T20:51:32+00:00  longevity-mv-si-4d-4-2-db-node-21231adb-7 !INFO    | scylla: [shard 9] compaction_manager - Asked to stop
2020-10-02T20:51:32+00:00  longevity-mv-si-4d-4-2-db-node-21231adb-7 !INFO    | scylla: [shard 1] compaction_manager - Stopped
2020-10-02T20:51:32+00:00  longevity-mv-si-4d-4-2-db-node-21231adb-7 !INFO    | scylla: [shard 7] compaction_manager - Asked to stop
2020-10-02T20:51:32+00:00  longevity-mv-si-4d-4-2-db-node-21231adb-7 !INFO    | scylla: [shard 8] compaction_manager - Asked to stop
2020-10-02T20:51:32+00:00  longevity-mv-si-4d-4-2-db-node-21231adb-7 !INFO    | scylla: [shard 9] compaction_manager - Stopping 0 ongoing compactions
2020-10-02T20:51:32+00:00  longevity-mv-si-4d-4-2-db-node-21231adb-7 !INFO    | scylla: [shard 12] compaction_manager - Asked to stop
2020-10-02T20:51:32+00:00  longevity-mv-si-4d-4-2-db-node-21231adb-7 !INFO    | scylla: [shard 13] compaction_manager - Asked to stop
2020-10-02T20:51:32+00:00  longevity-mv-si-4d-4-2-db-node-21231adb-7 !INFO    | scylla: [shard 8] compaction_manager - Stopping 0 ongoing compactions
2020-10-02T20:51:32+00:00  longevity-mv-si-4d-4-2-db-node-21231adb-7 !INFO    | scylla: [shard 2] compaction_manager - Stopping 0 ongoing compactions
2020-10-02T20:51:32+00:00  longevity-mv-si-4d-4-2-db-node-21231adb-7 !INFO    | scylla: [shard 13] compaction_manager - Stopping 0 ongoing compactions
2020-10-02T20:51:32+00:00  longevity-mv-si-4d-4-2-db-node-21231adb-7 !INFO    | scylla: [shard 2] view - Stopping view builder
2020-10-02T20:51:32+00:00  longevity-mv-si-4d-4-2-db-node-21231adb-7 !INFO    | scylla: [shard 2] compaction_manager - Stopped
2020-10-02T20:51:32+00:00  longevity-mv-si-4d-4-2-db-node-21231adb-7 !INFO    | scylla: [shard 13] view - Stopping view builder
2020-10-02T20:51:32+00:00  longevity-mv-si-4d-4-2-db-node-21231adb-7 !INFO    | scylla: [shard 13] compaction_manager - Stopped
2020-10-02T20:51:32+00:00  longevity-mv-si-4d-4-2-db-node-21231adb-7 !INFO    | scylla: [shard 4] compaction_manager - Stopping 0 ongoing compactions
2020-10-02T20:51:32+00:00  longevity-mv-si-4d-4-2-db-node-21231adb-7 !INFO    | scylla: [shard 7] compaction_manager - Stopping 0 ongoing compactions
2020-10-02T20:51:32+00:00  longevity-mv-si-4d-4-2-db-node-21231adb-7 !INFO    | scylla: [shard 10] compaction_manager - Asked to stop
2020-10-02T20:51:32+00:00  longevity-mv-si-4d-4-2-db-node-21231adb-7 !INFO    | scylla: [shard 4] view - Stopping view builder
2020-10-02T20:51:32+00:00  longevity-mv-si-4d-4-2-db-node-21231adb-7 !INFO    | scylla: [shard 4] compaction_manager - Stopped
2020-10-02T20:51:32+00:00  longevity-mv-si-4d-4-2-db-node-21231adb-7 !INFO    | scylla: [shard 11] compaction_manager - Asked to stop
2020-10-02T20:51:32+00:00  longevity-mv-si-4d-4-2-db-node-21231adb-7 !INFO    | scylla: [shard 5] compaction_manager - Stopping 0 ongoing compactions
2020-10-02T20:51:32+00:00  longevity-mv-si-4d-4-2-db-node-21231adb-7 !INFO    | scylla: [shard 10] compaction_manager - Stopping 0 ongoing compactions
2020-10-02T20:51:32+00:00  longevity-mv-si-4d-4-2-db-node-21231adb-7 !INFO    | scylla: [shard 11] compaction_manager - Stopping 0 ongoing compactions
2020-10-02T20:51:32+00:00  longevity-mv-si-4d-4-2-db-node-21231adb-7 !INFO    | scylla: [shard 8] view - Stopping view builder
2020-10-02T20:51:32+00:00  longevity-mv-si-4d-4-2-db-node-21231adb-7 !INFO    | scylla: [shard 5] view - Stopping view builder
2020-10-02T20:51:32+00:00  longevity-mv-si-4d-4-2-db-node-21231adb-7 !INFO    | scylla: [shard 8] compaction_manager - Stopped
2020-10-02T20:51:32+00:00  longevity-mv-si-4d-4-2-db-node-21231adb-7 !INFO    | scylla: [shard 6] compaction_manager - Asked to stop
2020-10-02T20:51:32+00:00  longevity-mv-si-4d-4-2-db-node-21231adb-7 !INFO    | scylla: [shard 9] view - Stopping view builder
2020-10-02T20:51:32+00:00  longevity-mv-si-4d-4-2-db-node-21231adb-7 !INFO    | scylla: [shard 6] compaction_manager - Stopping 0 ongoing compactions
2020-10-02T20:51:32+00:00  longevity-mv-si-4d-4-2-db-node-21231adb-7 !INFO    | scylla: [shard 11] view - Stopping view builder
2020-10-02T20:51:32+00:00  longevity-mv-si-4d-4-2-db-node-21231adb-7 !INFO    | scylla: [shard 6] view - Stopping view builder
2020-10-02T20:51:32+00:00  longevity-mv-si-4d-4-2-db-node-21231adb-7 !INFO    | scylla: [shard 6] compaction_manager - Stopped
2020-10-02T20:51:32+00:00  longevity-mv-si-4d-4-2-db-node-21231adb-7 !INFO    | scylla: [shard 12] compaction_manager - Stopping 0 ongoing compactions
2020-10-02T20:51:32+00:00  longevity-mv-si-4d-4-2-db-node-21231adb-7 !INFO    | scylla: [shard 10] view - Stopping view builder
2020-10-02T20:51:32+00:00  longevity-mv-si-4d-4-2-db-node-21231adb-7 !INFO    | scylla: [shard 3] compaction_manager - Stopping 0 ongoing compactions
2020-10-02T20:51:32+00:00  longevity-mv-si-4d-4-2-db-node-21231adb-7 !INFO    | scylla: [shard 7] view - Stopping view builder
2020-10-02T20:51:32+00:00  longevity-mv-si-4d-4-2-db-node-21231adb-7 !INFO    | scylla: [shard 9] compaction_manager - Stopped
2020-10-02T20:51:32+00:00  longevity-mv-si-4d-4-2-db-node-21231adb-7 !INFO    | scylla: [shard 5] compaction_manager - Stopped
2020-10-02T20:51:32+00:00  longevity-mv-si-4d-4-2-db-node-21231adb-7 !INFO    | scylla: [shard 11] compaction_manager - Stopped
2020-10-02T20:51:32+00:00  longevity-mv-si-4d-4-2-db-node-21231adb-7 !INFO    | scylla: [shard 12] view - Stopping view builder
2020-10-02T20:51:32+00:00  longevity-mv-si-4d-4-2-db-node-21231adb-7 !INFO    | scylla: [shard 10] compaction_manager - Stopped
2020-10-02T20:51:32+00:00  longevity-mv-si-4d-4-2-db-node-21231adb-7 !INFO    | scylla: [shard 3] view - Stopping view builder
2020-10-02T20:51:32+00:00  longevity-mv-si-4d-4-2-db-node-21231adb-7 !INFO    | scylla: [shard 7] compaction_manager - Stopped
2020-10-02T20:51:32+00:00  longevity-mv-si-4d-4-2-db-node-21231adb-7 !INFO    | scylla: [shard 12] compaction_manager - Stopped
2020-10-02T20:51:32+00:00  longevity-mv-si-4d-4-2-db-node-21231adb-7 !INFO    | scylla: [shard 3] compaction_manager - Stopped
```
this is the latest message in log regarding scylla stopping:

The scylla-server status on node is next:
```
[centos@longevity-mv-si-4d-4-2-db-node-21231adb-7 ~]$ sudo journalctl -f -u scylla-server
-- Logs begin at Пт 2020-10-02 17:49:26 UTC. --
окт 02 20:51:32 longevity-mv-si-4d-4-2-db-node-21231adb-7 scylla[1458]:  [shard 10] compaction_manager - Stopped
окт 02 20:51:32 longevity-mv-si-4d-4-2-db-node-21231adb-7 scylla[1458]:  [shard 3] view - Stopping view builder
окт 02 20:51:32 longevity-mv-si-4d-4-2-db-node-21231adb-7 scylla[1458]:  [shard 7] compaction_manager - Stopped
окт 02 20:51:32 longevity-mv-si-4d-4-2-db-node-21231adb-7 scylla[1458]:  [shard 12] compaction_manager - Stopped
окт 02 20:51:32 longevity-mv-si-4d-4-2-db-node-21231adb-7 scylla[1458]:  [shard 3] compaction_manager - Stopped
окт 02 21:06:32 longevity-mv-si-4d-4-2-db-node-21231adb-7 systemd[1]: scylla-server.service stop-sigterm timed out. Killing.
окт 02 21:07:36 longevity-mv-si-4d-4-2-db-node-21231adb-7 systemd[1]: scylla-server.service: main process exited, code=killed, status=9/KILL
окт 02 21:07:36 longevity-mv-si-4d-4-2-db-node-21231adb-7 systemd[1]: Stopped Scylla Server.
окт 02 21:07:36 longevity-mv-si-4d-4-2-db-node-21231adb-7 systemd[1]: Unit scylla-server.service entered failed state.
окт 02 21:07:36 longevity-mv-si-4d-4-2-db-node-21231adb-7 systemd[1]: scylla-server.service failed.
```
Nodes are available:
```
| longevity-mv-si-4d-4-2-db-node-21231adb-1      | eu-north-1a | 13.48.71.175  |
| longevity-mv-si-4d-4-2-monitor-node-21231adb-1 | eu-north-1a | 13.49.80.62   |
| longevity-mv-si-4d-4-2-db-node-21231adb-7      | eu-north-1a | 13.53.123.158 |
| longevity-mv-si-4d-4-2-db-node-21231adb-8      | eu-north-1a | 13.48.130.177 |
| longevity-mv-si-4d-4-2-db-node-21231adb-9      | eu-north-1a | 13.53.214.210 |
| longevity-mv-si-4d-4-2-db-node-21231adb-10     | eu-north-1a | 13.48.71.195  |
```
Node7 log: [system.log.tar.gz](https://github.com/scylladb/scylla/files/5326405/system.log.tar.gz)

all db logs: https://cloudius-jenkins-test.s3.amazonaws.com/21231adb-9a97-4b84-80b7-a6225af5e580/20201002_224742/db-cluster-21231adb.zip

The same happened on job: https://jenkins.scylladb.com/job/scylla-4.2/job/longevity/job/longevity-1tb-7days-test/14/ on node4

all db logs: https://cloudius-jenkins-test.s3.amazonaws.com/139a515a-e212-4fdc-b67e-979b56b3a730/20201003_231111/db-cluster-139a515a.zip

Nodes avialable:
```
longevity-tls-1tb-7d-4-2-db-node-139a515a-1         13.48.29.114
longevity-tls-1tb-7d-4-2-db-node-139a515a-4         13.49.0.234
longevity-tls-1tb-7d-4-2-db-node-139a515a-3         13.49.23.96
longevity-tls-1tb-7d-4-2-monitor-node-139a515a-1    13.48.24.28
longevity-tls-1tb-7d-4-2-db-node-139a515a-5         13.49.77.29
longevity-tls-1tb-7d-4-2-db-node-139a515a-6         13.53.190.18
```

**Comment by roydahan** [comment] 2020-10-05 12:29
We've seen it during tests 2 out of 3 times (different clusters where the drain nemesis was issued on).

I tried to reproduce it manually on the same node it happened on (13.49.0.234) and it happened on my second try.
What I did is running the followings one after another:

sudo systemctl start scylla-server
systemctl status scylla-server
nodetool drain
sudo systemctl stop scylla-server

Then, the stop command finished and this is the output:
```
[centos@longevity-tls-1tb-7d-4-2-db-node-139a515a-4 ~]$ systemctl status scylla-server
● scylla-server.service - Scylla Server
   Loaded: loaded (/usr/lib/systemd/system/scylla-server.service; enabled; vendor preset: disabled)
  Drop-In: /etc/systemd/system/scylla-server.service.d
           └─capabilities.conf, mounts.conf
   Active: failed (Result: exit-code) since Mon 2020-10-05 12:22:49 UTC; 2min 20s ago
  Process: 7664 ExecStopPost=/opt/scylladb/scripts/scylla_stop (code=exited, status=0/SUCCESS)
  Process: 7300 ExecStart=/usr/bin/scylla $SCYLLA_ARGS $SEASTAR_IO $DEV_MODE $CPUSET $MEM_CONF (code=exited, status=1/FAILURE)
  Process: 7243 ExecStartPre=/opt/scylladb/scripts/scylla_prepare (code=exited, status=0/SUCCESS)
 Main PID: 7300 (code=exited, status=1/FAILURE)
   Status: "starting view update backlog broker"

Oct 05 12:21:45 longevity-tls-1tb-7d-4-2-db-node-139a515a-4 scylla[7300]:  [shard 0] compaction_manager - Stopping 0 ongoing compactions
Oct 05 12:21:45 longevity-tls-1tb-7d-4-2-db-node-139a515a-4 scylla[7300]:  [shard 0] init - Shutting down view update backlog broker
Oct 05 12:21:45 longevity-tls-1tb-7d-4-2-db-node-139a515a-4 scylla[7300]:  [shard 0] compaction_manager - Stopped
Oct 05 12:21:45 longevity-tls-1tb-7d-4-2-db-node-139a515a-4 scylla[7300]:  [shard 1] compaction_manager - Asked to stop
Oct 05 12:21:45 longevity-tls-1tb-7d-4-2-db-node-139a515a-4 scylla[7300]:  [shard 2] compaction_manager - Asked to stop
Oct 05 12:21:45 longevity-tls-1tb-7d-4-2-db-node-139a515a-4 scylla[7300]:  [shard 1] compaction_manager - Stopping 0 ongoing compactions
Oct 05 12:22:49 longevity-tls-1tb-7d-4-2-db-node-139a515a-4 systemd[1]: scylla-server.service: main process exited, code=exited, status=1/FAILURE
Oct 05 12:22:49 longevity-tls-1tb-7d-4-2-db-node-139a515a-4 systemd[1]: Stopped Scylla Server.
Oct 05 12:22:49 longevity-tls-1tb-7d-4-2-db-node-139a515a-4 systemd[1]: Unit scylla-server.service entered failed state.
Oct 05 12:22:49 longevity-tls-1tb-7d-4-2-db-node-139a515a-4 systemd[1]: scylla-server.service failed.

```

I don't know how it's possible to trigger a coredump in this case.

**Comment by bhalevy** [comment] 2020-10-05 12:39
@xemul please look into this

**Comment by xemul** [comment] 2020-10-05 13:09
The log messages are exactly the same as in #7077, and the 5fcc1f205c doesn't have the fix (ca9422ca)

**Comment by slivne** [comment] 2020-10-06 11:02
@avikivity please review for backport - there is a fix in master

**Comment by avikivity** [comment] 2020-10-07 11:07
Closing as duplicate of #7077.

**Closed** 2020-10-08 11:06 UTC
Labels: bug, high
