### ISSUE TITLE
Scyllatop exits w/o a reason many times

### ISSUE THREAD

**Issue by dorlaor** [scylladb/scylla#1070] opened 2016-03-21 09:39 UTC
Running Scyllatop exits many times with this message:
AttributeError: 'NoneType' object has no attribute 'groupdict'

Nothing special is needed to achieve it, seems almost random.

**Comment by haarcuba** [comment] 2016-03-22 09:47
does this happen after a while? or is the time scyllatop is up also random?

**Comment by haarcuba** [comment] 2016-03-22 12:04
could you attach a scyllatop.log next time it happens? it should be in the directory you run scyllatop from.

**Comment by dorlaor** [comment] 2016-03-22 21:25
I wasn't aware there is such a log file. Will do. From what I remember it
happened randomly.

**Comment by haarcuba** [comment] 2016-03-23 00:02
it doesn't reproduce for me.

there are only a few places in the code that could be responsible - it's probably some specific metric that I don't see on my machines but you do - a metric whose text-pattern is different from expected.

once I have a log it'll be easy.

I can also defend against such events - probably a good idea, since we never know what collectd can come up with.

**Comment by lmr** [comment] 2016-03-24 17:15
Disclaimer: I haven't done much hacking on scylla top yet, but this should be easy to prevent against - just look for the places in the code that access said groupdict, and do a `if not None` test before doing whatever you will do with it.

    git grep groupdict
    tools/scyllatop/collectd.py:        howManyLines = int(match.groupdict()['lines'])
    tools/scyllatop/metric.py:            key = match.groupdict()['key']
    tools/scyllatop/metric.py:            value = match.groupdict()['value']
    tools/scyllatop/metric.py:            metric = match.groupdict()['metric']

**Comment by lmr** [comment] 2016-03-24 17:16
So instead of blindly trying to access keys on a match.groupdict() that might be None, check first before getting values.

**Comment by lmr** [comment] 2016-03-24 17:29
From the limited amount of time I looked into this, the patch seems straight forward:

    From 08d8236b01118c5e81c6c69138d2ddf3a8bdb99f Mon Sep 17 00:00:00 2001
    From: Lucas Meneghel Rodrigues <lmr@scylladb.com>
    Date: Thu, 24 Mar 2016 14:27:50 -0300
    Subject: [PATCH] scyllatop: Skip collectd output lines that don't match metric
     patterns

    Fixes #1070.

    Currently scyllatop doesn't defend against situations where a line
    on collectd's LISTVAL query doesn't match a metric pattern. Let's
    ignore such cases to avoid errors like:

    AttributeError: 'NoneType' object has no attribute 'groupdict'

    Signed-off-by: Lucas Meneghel Rodrigues <lmr@scylladb.com>
    ---
     tools/scyllatop/metric.py | 3 +++
     1 file changed, 3 insertions(+)

    diff --git a/tools/scyllatop/metric.py b/tools/scyllatop/metric.py
    index cde1fc9..6b02260 100644
    --- a/tools/scyllatop/metric.py
    +++ b/tools/scyllatop/metric.py
    @@ -44,6 +44,9 @@ class Metric(object):
             for line in response:
                 logging.debug('LISTVAL result: {0}'.format(line))
                 match = cls._METRIC_DISCOVER_PATTERN.search(line)
    +            if match is None:
    +                logging.debug('could not parse metric pattern from line: {0}'.format(line))
    +                continue
                 metric = match.groupdict()['metric']
                 results.append(Metric(metric, collectd))
     
    -- 
    2.5.5

So if this is indeed interesting, let me know. I can send it to the mailing list if @haarcuba thinks it's good enough.

**Comment by haarcuba** [comment] 2016-03-25 17:56
I've already submitted a fix - which more or less does what you suggested, thanks - d2cfb86dc801ba74084b937af7e05e5bc2539f70

it's already merged - but someone else who has seen this bug should confirm it fixes the issue, @dorlaor

**Comment by haarcuba** [comment] 2016-04-20 21:16
anybody check this? this issue should probably be closed.

**Closed** 2016-04-21 06:36 UTC
Labels: bug, high
