### ISSUE TITLE
row_merged is missing in db::system_keyspace::get_compaction_history()

### ISSUE THREAD

**Issue by amnonh** [scylladb/scylla#1097] opened 2016-03-24 23:04 UTC
The row merged should be propagate to the API.

Affected nodetool command:
nodetool compactionhistory

## Installation details
Scylla version (or git commit hash):
Cluster size:
OS (RHEL/CentOS/Ubuntu/AWS AMI):

## Hardware details (for performance issues)
Platform (physical/VM/cloud instance type/docker):
Hardware: sockets= cores= hyperthreading= memory=
Disks: (SSD/HDD, count)

**Comment by slivne** [comment] 2016-03-27 07:39
duplicate of #748

**Closed by slivne** 2016-03-27 07:39 UTC
Labels: bug, duplicate
