### ISSUE TITLE
Inserting null clustering column fails silently

### ISSUE THREAD

**Issue by racevedoo** [scylladb/scylla#8962] opened 2021-07-01 14:24 UTC
*Installation details*
Scylla version (or git commit hash): 4.4.3
Cluster size: 1
OS (RHEL/CentOS/Ubuntu/AWS AMI): docker on local ubuntu

When inserting a null clustering column, the insert statement returns no error (but does not insert data, as expected). It should return a error to the user, as cassandra does.

On scylla 4.4.3:
```
CREATE KEYSPACE ks WITH replication = {'class': 'SimpleStrategy', 'replication_factor' : 1};          
CREATE TABLE ks.t (id text, id2 text, name text, PRIMARY KEY (id,id2));                               
INSERT INTO ks.t (id,id2,name) VALUES ('1',null,'River');                                             
select * from ks.t;

 id | id2 | name
----+-----+------

(0 rows)
```

On cassandra 3.11:
```
CREATE KEYSPACE ks WITH replication = {'class': 'SimpleStrategy', 'replication_factor' : 1};
CREATE TABLE ks.t (id text, id2 text, name text, PRIMARY KEY (id,id2));
INSERT INTO ks.t (id,id2,name) VALUES ('1',null,'River');
InvalidRequest: Error from server: code=2200 [Invalid query] message="Invalid null value in condition for column id2"
```

**Comment by nyh** [comment] 2021-07-09 13:34
@racevedoo thanks for discovering this issue. We actually knew about this problem - it's a duplicate of issue  #7852, which was discovered as part of my project to translate Cassandra's unit tests, but unfortunately we haven't fixed it yet. That issue also points two reproducing test cases (one part of a bigger Cassandra test, the second is a minimal test in `test/cql-pytest/test_null.py`.
So I'm closing this duplicate issue and moving the assignment to @dekimir and tags to #7852.

**Closed by nyh** 2021-07-09 13:34 UTC
Labels: CQL, User Request, bug, cassandra 3.x compatibility
