### ISSUE TITLE
Reactor stalls when "Enabling encrypted CQL connections between client and server"

### ISSUE THREAD

**Issue by bentsi** [scylladb/scylla#5145] opened 2019-10-06 18:12 UTC
*Installation details*
Scylla version (or git commit hash): scylla-3.1.0.rc5-0.20190922.f469c2742
Cluster size: 4
OS (RHEL/CentOS/Ubuntu/AWS AMI): custom RPMs (gs://scratch.scylladb.com/espindola/rpms-issue-4971/) [@espindola]

Scenario (when client encryption enabled):
- decommission a node 
- add new node

when streaming finished got reactor stalls (max observed 3963ms)

```
Oct 06 16:37:05 ip-10-0-246-50.eu-west-1.compute.internal scylla[2323]:  [shard 0] storage_service - Enabling encrypted CQL connections between client and server
Oct 06 16:37:06 ip-10-0-246-50.eu-west-1.compute.internal scylla[2323]: Reactor stalled for 652 ms on shard 10.
Oct 06 16:37:06 ip-10-0-246-50.eu-west-1.compute.internal scylla[2323]: Backtrace:
Oct 06 16:37:06 ip-10-0-246-50.eu-west-1.compute.internal scylla[2323]: 0x0000000004180762
Oct 06 16:37:06 ip-10-0-246-50.eu-west-1.compute.internal scylla[2323]: 0x000000000406d7e5
Oct 06 16:37:06 ip-10-0-246-50.eu-west-1.compute.internal scylla[2323]: 0x000000000406dd25
Oct 06 16:37:06 ip-10-0-246-50.eu-west-1.compute.internal scylla[2323]: 0x000000000406e017
Oct 06 16:37:06 ip-10-0-246-50.eu-west-1.compute.internal scylla[2323]: 0x00007f637919902f
Oct 06 16:37:06 ip-10-0-246-50.eu-west-1.compute.internal scylla[2323]: 0x00007f6379854e00
Oct 06 16:37:06 ip-10-0-246-50.eu-west-1.compute.internal scylla[2323]: Reactor stalled for 654 ms on shard 1.
Oct 06 16:37:06 ip-10-0-246-50.eu-west-1.compute.internal scylla[2323]: Backtrace:
Oct 06 16:37:06 ip-10-0-246-50.eu-west-1.compute.internal scylla[2323]: 0x0000000004180762
Oct 06 16:37:06 ip-10-0-246-50.eu-west-1.compute.internal scylla[2323]: 0x000000000406d7e5
Oct 06 16:37:06 ip-10-0-246-50.eu-west-1.compute.internal scylla[2323]: 0x000000000406dd25
Oct 06 16:37:06 ip-10-0-246-50.eu-west-1.compute.internal scylla[2323]: 0x000000000406e017
Oct 06 16:37:06 ip-10-0-246-50.eu-west-1.compute.internal scylla[2323]: 0x00007f637919902f
Oct 06 16:37:06 ip-10-0-246-50.eu-west-1.compute.internal scylla[2323]: 0x00007f6379854dc4
Oct 06 16:37:06 ip-10-0-246-50.eu-west-1.compute.internal scylla[2323]: Reactor stalled for 654 ms on shard 12.
Oct 06 16:37:06 ip-10-0-246-50.eu-west-1.compute.internal scylla[2323]: Backtrace:
Oct 06 16:37:06 ip-10-0-246-50.eu-west-1.compute.internal scylla[2323]: 0x0000000004180762
Oct 06 16:37:06 ip-10-0-246-50.eu-west-1.compute.internal scylla[2323]: 0x000000000406d7e5
Oct 06 16:37:06 ip-10-0-246-50.eu-west-1.compute.internal scylla[2323]: 0x000000000406dd25
Oct 06 16:37:06 ip-10-0-246-50.eu-west-1.compute.internal scylla[2323]: 0x000000000406e017
Oct 06 16:37:06 ip-10-0-246-50.eu-west-1.compute.internal scylla[2323]: 0x00007f637919902f
Oct 06 16:37:06 ip-10-0-246-50.eu-west-1.compute.internal scylla[2323]: /opt/scylladb/libreloc/libgmp.so.10+0x0000000000030d8b
Oct 06 16:37:06 ip-10-0-246-50.eu-west-1.compute.internal scylla[2323]: Reactor stalled for 651 ms on shard 13.
Oct 06 16:37:06 ip-10-0-246-50.eu-west-1.compute.internal scylla[2323]: Backtrace:
Oct 06 16:37:06 ip-10-0-246-50.eu-west-1.compute.internal scylla[2323]: 0x0000000004180762
Oct 06 16:37:06 ip-10-0-246-50.eu-west-1.compute.internal scylla[2323]: 0x000000000406d7e5
Oct 06 16:37:06 ip-10-0-246-50.eu-west-1.compute.internal scylla[2323]: 0x000000000406dd25
Oct 06 16:37:06 ip-10-0-246-50.eu-west-1.compute.internal scylla[2323]: 0x000000000406e017
Oct 06 16:37:06 ip-10-0-246-50.eu-west-1.compute.internal scylla[2323]: 0x00007f637919902f
Oct 06 16:37:06 ip-10-0-246-50.eu-west-1.compute.internal scylla[2323]: 0x00007f6379854db3
Oct 06 16:37:06 ip-10-0-246-50.eu-west-1.compute.internal scylla[2323]: Reactor stalled for 651 ms on shard 5.
Oct 06 16:37:06 ip-10-0-246-50.eu-west-1.compute.internal scylla[2323]: Backtrace:
Oct 06 16:37:06 ip-10-0-246-50.eu-west-1.compute.internal scylla[2323]: 0x0000000004180762
Oct 06 16:37:06 ip-10-0-246-50.eu-west-1.compute.internal scylla[2323]: 0x000000000406d7e5
Oct 06 16:37:06 ip-10-0-246-50.eu-west-1.compute.internal scylla[2323]: 0x000000000406dd25
Oct 06 16:37:06 ip-10-0-246-50.eu-west-1.compute.internal scylla[2323]: 0x000000000406e017
Oct 06 16:37:06 ip-10-0-246-50.eu-west-1.compute.internal scylla[2323]: 0x00007f637919902f
Oct 06 16:37:06 ip-10-0-246-50.eu-west-1.compute.internal scylla[2323]: 0x00007f6379854e09
Oct 06 16:37:06 ip-10-0-246-50.eu-west-1.compute.internal scylla[2323]: Reactor stalled for 651 ms on shard 9.
Oct 06 16:37:06 ip-10-0-246-50.eu-west-1.compute.internal scylla[2323]: Backtrace:
Oct 06 16:37:06 ip-10-0-246-50.eu-west-1.compute.internal scylla[2323]: 0x0000000004180762
Oct 06 16:37:06 ip-10-0-246-50.eu-west-1.compute.internal scylla[2323]: 0x000000000406d7e5
Oct 06 16:37:06 ip-10-0-246-50.eu-west-1.compute.internal scylla[2323]: 0x000000000406dd25
Oct 06 16:37:06 ip-10-0-246-50.eu-west-1.compute.internal scylla[2323]: 0x000000000406e017
Oct 06 16:37:06 ip-10-0-246-50.eu-west-1.compute.internal scylla[2323]: 0x00007f637919902f
Oct 06 16:37:06 ip-10-0-246-50.eu-west-1.compute.internal scylla[2323]: 0x00007f6379854dc4
Oct 06 16:37:06 ip-10-0-246-50.eu-west-1.compute.internal scylla[2323]: Reactor stalled for 650 ms on shard 3.
Oct 06 16:37:06 ip-10-0-246-50.eu-west-1.compute.internal scylla[2323]: Backtrace:
Oct 06 16:37:06 ip-10-0-246-50.eu-west-1.compute.internal scylla[2323]: 0x0000000004180762
Oct 06 16:37:06 ip-10-0-246-50.eu-west-1.compute.internal scylla[2323]: 0x000000000406d7e5
Oct 06 16:37:06 ip-10-0-246-50.eu-west-1.compute.internal scylla[2323]: 0x000000000406dd25
Oct 06 16:37:06 ip-10-0-246-50.eu-west-1.compute.internal scylla[2323]: 0x000000000406e017
Oct 06 16:37:06 ip-10-0-246-50.eu-west-1.compute.internal scylla[2323]: 0x00007f637919902f
Oct 06 16:37:06 ip-10-0-246-50.eu-west-1.compute.internal scylla[2323]: /opt/scylladb/libreloc/libgmp.so.10+0x0000000000030621
Oct 06 16:37:06 ip-10-0-246-50.eu-west-1.compute.internal scylla[2323]: Reactor stalled for 654 ms on shard 6.
Oct 06 16:37:06 ip-10-0-246-50.eu-west-1.compute.internal scylla[2323]: Backtrace:
Oct 06 16:37:06 ip-10-0-246-50.eu-west-1.compute.internal scylla[2323]: 0x0000000004180762
Oct 06 16:37:06 ip-10-0-246-50.eu-west-1.compute.internal scylla[2323]: 0x000000000406d7e5
Oct 06 16:37:06 ip-10-0-246-50.eu-west-1.compute.internal scylla[2323]: 0x000000000406dd25
Oct 06 16:37:06 ip-10-0-246-50.eu-west-1.compute.internal scylla[2323]: 0x000000000406e017
Oct 06 16:37:06 ip-10-0-246-50.eu-west-1.compute.internal scylla[2323]: 0x00007f637919902f
Oct 06 16:37:06 ip-10-0-246-50.eu-west-1.compute.internal scylla[2323]: 0x00007f6379854dc9
Oct 06 16:37:06 ip-10-0-246-50.eu-west-1.compute.internal scylla[2323]:  [shard 11] compaction - Compacted 22 sstables to [/var/lib/scylla/data/keyspace1/standard1-00811400e81411e9a6b9000000000000/mc-6857-big-Data.db:level=1, 
Oct 06 16:37:06 ip-10-0-246-50.eu-west-1.compute.internal scylla[2323]:  [shard 11] compaction - Compacting [/var/lib/scylla/data/keyspace1/standard1-00811400e81411e9a6b9000000000000/mc-5121-big-Data.db:level=2, /var/lib/scyll
Oct 06 16:37:07 ip-10-0-246-50.eu-west-1.compute.internal scylla[2323]: Reactor stalled for 1805 ms on shard 10.
Oct 06 16:37:07 ip-10-0-246-50.eu-west-1.compute.internal scylla[2323]: Backtrace:
Oct 06 16:37:07 ip-10-0-246-50.eu-west-1.compute.internal scylla[2323]: 0x0000000004180762
Oct 06 16:37:07 ip-10-0-246-50.eu-west-1.compute.internal scylla[2323]: 0x000000000406d7e5
Oct 06 16:37:07 ip-10-0-246-50.eu-west-1.compute.internal scylla[2323]: 0x000000000406dd25
Oct 06 16:37:07 ip-10-0-246-50.eu-west-1.compute.internal scylla[2323]: 0x000000000406e017
Oct 06 16:37:07 ip-10-0-246-50.eu-west-1.compute.internal scylla[2323]: 0x00007f637919902f
Oct 06 16:37:07 ip-10-0-246-50.eu-west-1.compute.internal scylla[2323]: /opt/scylladb/libreloc/libgmp.so.10+0x0000000000030ccb
Oct 06 16:37:07 ip-10-0-246-50.eu-west-1.compute.internal scylla[2323]: Reactor stalled for 1810 ms on shard 12.
Oct 06 16:37:07 ip-10-0-246-50.eu-west-1.compute.internal scylla[2323]: Backtrace:
Oct 06 16:37:07 ip-10-0-246-50.eu-west-1.compute.internal scylla[2323]: 0x0000000004180762
Oct 06 16:37:07 ip-10-0-246-50.eu-west-1.compute.internal scylla[2323]: 0x000000000406d7e5
Oct 06 16:37:07 ip-10-0-246-50.eu-west-1.compute.internal scylla[2323]: 0x000000000406dd25
Oct 06 16:37:07 ip-10-0-246-50.eu-west-1.compute.internal scylla[2323]: 0x000000000406e017
Oct 06 16:37:07 ip-10-0-246-50.eu-west-1.compute.internal scylla[2323]: 0x00007f637919902f
Oct 06 16:37:07 ip-10-0-246-50.eu-west-1.compute.internal scylla[2323]: 0x00007f6379854de7
Oct 06 16:37:07 ip-10-0-246-50.eu-west-1.compute.internal scylla[2323]:  [shard 8] compaction - Compacted 8 sstables to [/var/lib/scylla/data/keyspace1/standard1-00811400e81411e9a6b9000000000000/mc-7540-big-Data.db:level=2, /v
Oct 06 16:37:07 ip-10-0-246-50.eu-west-1.compute.internal scylla[2323]:  [shard 8] compaction - Compacting [/var/lib/scylla/data/keyspace1/standard1-00811400e81411e9a6b9000000000000/mc-5370-big-Data.db:level=2, /var/lib/scylla
Oct 06 16:37:08 ip-10-0-246-50.eu-west-1.compute.internal scylla[2323]:  [shard 7] compaction - Compacted 2 sstables to [/var/lib/scylla/data/keyspace1/standard1-00811400e81411e9a6b9000000000000/mc-7399-big-Data.db:level=2, /v
Oct 06 16:37:08 ip-10-0-246-50.eu-west-1.compute.internal scylla[2323]:  [shard 7] compaction - Compacting [/var/lib/scylla/data/keyspace1/standard1-00811400e81411e9a6b9000000000000/mc-4921-big-Data.db:level=2, /var/lib/scylla
Oct 06 16:37:08 ip-10-0-246-50.eu-west-1.compute.internal scylla[2323]:  [shard 6] compaction - Compacted 2 sstables to [/var/lib/scylla/data/keyspace1/standard1-00811400e81411e9a6b9000000000000/mc-7370-big-Data.db:level=2, /v
Oct 06 16:37:08 ip-10-0-246-50.eu-west-1.compute.internal scylla[2323]:  [shard 6] compaction - Compacting [/var/lib/scylla/data/keyspace1/standard1-00811400e81411e9a6b9000000000000/mc-6544-big-Data.db:level=2, /var/lib/scylla
Oct 06 16:37:08 ip-10-0-246-50.eu-west-1.compute.internal scylla[2323]:  [shard 9] compaction - Compacted 22 sstables to [/var/lib/scylla/data/keyspace1/standard1-00811400e81411e9a6b9000000000000/mc-6911-big-Data.db:level=1, /
Oct 06 16:37:08 ip-10-0-246-50.eu-west-1.compute.internal scylla[2323]:  [shard 9] compaction - Compacting [/var/lib/scylla/data/keyspace1/standard1-00811400e81411e9a6b9000000000000/mc-6127-big-Data.db:level=2, /var/lib/scylla
Oct 06 16:37:09 ip-10-0-246-50.eu-west-1.compute.internal scylla[2323]: Reactor stalled for 3963 ms on shard 10.
Oct 06 16:37:09 ip-10-0-246-50.eu-west-1.compute.internal scylla[2323]: Backtrace:
Oct 06 16:37:09 ip-10-0-246-50.eu-west-1.compute.internal scylla[2323]: 0x0000000004180762
Oct 06 16:37:09 ip-10-0-246-50.eu-west-1.compute.internal scylla[2323]: 0x000000000406d7e5
Oct 06 16:37:09 ip-10-0-246-50.eu-west-1.compute.internal scylla[2323]: 0x000000000406dd25
Oct 06 16:37:09 ip-10-0-246-50.eu-west-1.compute.internal scylla[2323]: 0x000000000406e017
Oct 06 16:37:09 ip-10-0-246-50.eu-west-1.compute.internal scylla[2323]: 0x00007f637919902f
Oct 06 16:37:09 ip-10-0-246-50.eu-west-1.compute.internal scylla[2323]: /opt/scylladb/libreloc/libgmp.so.10+0x0000000000030dba
Oct 06 16:37:09 ip-10-0-246-50.eu-west-1.compute.internal scylla[2323]:  [shard 0] compaction - Compacted 6 sstables to [/var/lib/scylla/data/keyspace1/standard1-00811400e81411e9a6b9000000000000/mc-7140-big-Data.db:level=2, /v
Oct 06 16:37:09 ip-10-0-246-50.eu-west-1.compute.internal scylla[2323]:  [shard 0] compaction - Compacting [/var/lib/scylla/data/keyspace1/standard1-00811400e81411e9a6b9000000000000/mc-6398-big-Data.db:level=2, /var/lib/scylla
Oct 06 16:37:09 ip-10-0-246-50.eu-west-1.compute.internal scylla[2323]:  [shard 0] storage_service - Starting listening for CQL clients on 0.0.0.0:9042 (encrypted)
Oct 06 16:37:09 ip-10-0-246-50.eu-west-1.compute.internal scylla[2323]:  [shard 0] storage_service - Thrift server listening on 0.0.0.0:9160 ...
Oct 06 16:37:09 ip-10-0-246-50.eu-west-1.compute.internal scylla[2323]:  [shard 0] init - Scylla version 3.1.0.rc5-0.20190902.623ea5e3d initialization completed.
```

translated backtraces
```
0x0000000004180762
0x000000000406d7e5
0x000000000406dd25
0x000000000406e017
0x00007f637919902f
0x00007f6379854e00
std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_dispose() at /usr/include/boost/program_options/variables_map.hpp:146
 (inlined by) std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string() at /usr/include/c++/8/bits/basic_string.h:657
 (inlined by) seastar::mountpoint_params::~mountpoint_params() at /home/espindola/scylla/scylla/seastar/build/release/../../src/core/reactor.cc:127
 (inlined by) std::pair<unsigned long const, seastar::mountpoint_params>::~pair() at /usr/include/c++/8/bits/stl_pair.h:208
 (inlined by) void __gnu_cxx::new_allocator<std::__detail::_Hash_node<std::pair<unsigned long const, seastar::mountpoint_params>, false> >::destroy<std::pair<unsigned long const, seastar::mountpoint_params> >(std::pair<unsigned long const, seastar::mountpoint_params>*) at /usr/include/c++/8/ext/new_allocator.h:140
 (inlined by) void std::allocator_traits<std::allocator<std::__detail::_Hash_node<std::pair<unsigned long const, seastar::mountpoint_params>, false> > >::destroy<std::pair<unsigned long const, seastar::mountpoint_params> >(std::allocator<std::__detail::_Hash_node<std::pair<unsigned long const, seastar::mountpoint_params>, false> >&, std::pair<unsigned long const, seastar::mountpoint_params>*) at /usr/include/c++/8/bits/alloc_traits.h:487
 (inlined by) std::__detail::_Hashtable_alloc<std::allocator<std::__detail::_Hash_node<std::pair<unsigned long const, seastar::mountpoint_params>, false> > >::_M_deallocate_node(std::__detail::_Hash_node<std::pair<unsigned long const, seastar::mountpoint_params>, false>*) at /usr/include/c++/8/bits/hashtable_policy.h:2100
 (inlined by) std::__detail::_Hashtable_alloc<std::allocator<std::__detail::_Hash_node<std::pair<unsigned long const, seastar::mountpoint_params>, false> > >::_M_deallocate_nodes(std::__detail::_Hash_node<std::pair<unsigned long const, seastar::mountpoint_params>, false>*) at /usr/include/c++/8/bits/hashtable_policy.h:2113
 (inlined by) std::_Hashtable<unsigned long, std::pair<unsigned long const, seastar::mountpoint_params>, std::allocator<std::pair<unsigned long const, seastar::mountpoint_params> >, std::__detail::_Select1st, std::equal_to<unsigned long>, std::hash<unsigned long>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<false, false, true> >::clear() at /usr/include/c++/8/bits/hashtable.h:2050
 (inlined by) std::_Hashtable<unsigned long, std::pair<unsigned long const, seastar::mountpoint_params>, std::allocator<std::pair<unsigned long const, seastar::mountpoint_params> >, std::__detail::_Select1st, std::equal_to<unsigned long>, std::hash<unsigned long>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<false, false, true> >::~_Hashtable() at /usr/include/c++/8/bits/hashtable.h:1374
 (inlined by) std::unordered_map<unsigned long, seastar::mountpoint_params, std::hash<unsigned long>, std::equal_to<unsigned long>, std::allocator<std::pair<unsigned long const, seastar::mountpoint_params> > >::~unordered_map() at /usr/include/c++/8/bits/unordered_map.h:102
 (inlined by) seastar::disk_config_params::~disk_config_params() at /home/espindola/scylla/scylla/seastar/build/release/../../src/core/reactor.cc:5043
 (inlined by) seastar::smp::configure(boost::program_options::variables_map, seastar::reactor_config) at /home/espindola/scylla/scylla/seastar/build/release/../../src/core/reactor.cc:5316
seastar::future_state_base::set_exception(std::__exception_ptr::exception_ptr) at /usr/include/boost/program_options/variables_map.hpp:146
 (inlined by) seastar::future<unsigned long>::future(seastar::exception_future_marker, std::__exception_ptr::exception_ptr) at /home/espindola/scylla/scylla/seastar/build/release/../../include/seastar/core/future.hh:703
 (inlined by) seastar::future<unsigned long> seastar::make_exception_future<unsigned long>(std::__exception_ptr::exception_ptr) at /home/espindola/scylla/scylla/seastar/build/release/../../include/seastar/core/future.hh:1286
 (inlined by) seastar::future<unsigned long> seastar::make_exception_future<unsigned long, std::system_error>(std::system_error&&) at /home/espindola/scylla/scylla/seastar/build/release/../../include/seastar/core/future.hh:1301
 (inlined by) seastar::posix_file_impl::size() at /home/espindola/scylla/scylla/seastar/build/release/../../src/core/reactor.cc:3315
__gthread_mutex_unlock at /usr/include/boost/program_options/variables_map.hpp:146
 (inlined by) std::mutex::unlock() at /usr/include/c++/8/bits/std_mutex.h:121
 (inlined by) std::lock_guard<std::mutex>::~lock_guard() at /usr/include/c++/8/bits/std_mutex.h:168
 (inlined by) seastar::io_queue::register_one_priority_class(seastar::basic_sstring<char, unsigned int, 15u, true>, unsigned int) at /home/espindola/scylla/scylla/seastar/build/release/../../src/core/reactor.cc:2100
 (inlined by) seastar::reactor::register_one_priority_class(seastar::basic_sstring<char, unsigned int, 15u, true>, unsigned int) at /home/espindola/scylla/scylla/seastar/build/release/../../src/core/reactor.cc:157
seastar::reactor::signals::signal_handler::signal_handler(int, std::function<void ()>&&) at /usr/include/boost/program_options/variables_map.hpp:146
?? ??:0
?? ??:0
...
Reactor stalled for 3963 ms on shard 10.
Backtrace:
0x0000000004180762
0x000000000406d7e5
0x000000000406dd25
0x000000000406e017
0x00007f637919902f?? ??:0
seastar::future_state_base::set_exception(std::__exception_ptr::exception_ptr) at /usr/include/boost/program_options/variables_map.hpp:146
 (inlined by) seastar::future<unsigned long>::future(seastar::exception_future_marker, std::__exception_ptr::exception_ptr) at /home/espindola/scylla/scylla/seastar/build/release/../../include/seastar/core/future.hh:703
 (inlined by) seastar::future<unsigned long> seastar::make_exception_future<unsigned long>(std::__exception_ptr::exception_ptr) at /home/espindola/scylla/scylla/seastar/build/release/../../include/seastar/core/future.hh:1286
 (inlined by) seastar::future<unsigned long> seastar::make_exception_future<unsigned long, std::system_error>(std::system_error&&) at /home/espindola/scylla/scylla/seastar/build/release/../../include/seastar/core/future.hh:1301
 (inlined by) seastar::posix_file_impl::size() at /home/espindola/scylla/scylla/seastar/build/release/../../src/core/reactor.cc:3315
__gthread_mutex_unlock at /usr/include/boost/program_options/variables_map.hpp:146
 (inlined by) std::mutex::unlock() at /usr/include/c++/8/bits/std_mutex.h:121
 (inlined by) std::lock_guard<std::mutex>::~lock_guard() at /usr/include/c++/8/bits/std_mutex.h:168
 (inlined by) seastar::io_queue::register_one_priority_class(seastar::basic_sstring<char, unsigned int, 15u, true>, unsigned int) at /home/espindola/scylla/scylla/seastar/build/release/../../src/core/reactor.cc:2100
 (inlined by) seastar::reactor::register_one_priority_class(seastar::basic_sstring<char, unsigned int, 15u, true>, unsigned int) at /home/espindola/scylla/scylla/seastar/build/release/../../src/core/reactor.cc:157
seastar::reactor::signals::signal_handler::signal_handler(int, std::function<void ()>&&) at /usr/include/boost/program_options/variables_map.hpp:146
```

Performance drop observed
![image](https://user-images.githubusercontent.com/5269241/66273457-dfcf3c00-e87c-11e9-98ce-e1669a3d5fb7.png)

Write timeouts
![image](https://user-images.githubusercontent.com/5269241/66273526-6f74ea80-e87d-11e9-8513-53d4933fa585.png)

Test configuration: [longevity-200GB-48h-verifier-LimitedMonkey-tls.yaml](https://github.com/bentsi/scylla-cluster-tests/blob/decommision-repr/test-cases/longevity/longevity-200GB-48h-verifier-LimitedMonkey-tls.yaml)

**Comment by tzach** [comment] 2019-10-07 06:04
@bentsi is it a regression vs 3.0.x?

**Comment by bhalevy** [comment] 2019-10-07 10:47
@espindola can you please decode the backtraces from your binary?
The ones that @bentsi posted above were decoded using the debug-info package and they seem invalid.

**Comment by bentsi** [comment] 2019-10-07 10:47
@tzach we didn't run this test before, it's a new feature

**Comment by slivne** [comment] 2019-12-12 10:21
@bentsi if we are getting this on an updated version - can you please post backtraces so we can have a look (all the tooling has changed with relocatable packages)

**Comment by espindola** [comment] 2019-12-12 18:36
Sorry, I missed this somehow.
I am confused, how is this related to #4971 and why were those rpms used?
@bhalevy not sure what you want me to do differently for decoding the binaries. All that I have (hopefully in a backup) are the rpms.

**Comment by espindola** [comment] 2019-12-12 19:06
This is the backtrace I got with 

seastar-addr2line -e  usr/lib/debug/opt/scylladb/libexec/scylla-3.1.0.rc5-0.20190922.f469c2742.el7.x86_64.debug < log  > decoded

[decoded.txt](https://github.com/scylladb/scylla/files/3957402/decoded.txt)

**Comment by avikivity** [comment] 2019-12-15 14:08
Looks like the debuginfo and the trace do not match.

**Comment by slivne** [comment] 2020-03-26 23:28
@bentsi when we run this on 4.0 , if there are still stalls - please create a new issue.

Closing this for now as we can't do anything wih the info provided

**Closed by slivne** 2020-03-26 23:28 UTC
Labels: stability
