### ISSUE TITLE
reactor stall,semaphore timeout followed by IO stop

### ISSUE THREAD

**Issue by shoshan** [scylladb/scylla#7841] opened 2020-12-28 12:01 UTC
*Installation details*
Scylla version (or git commit hash): `4.4.dev-0.20201223.fd5f0c303 with build-id 53f07cc93abe27b5cbeea8d47f067a09c793d6a5`
Cluster size: 3 nodes (i3.4xlarge)
OS (RHEL/CentOS/Ubuntu/AWS AMI): `ami-0677ef04b8820d949` (aws: eu-north-1)

Gemini command:
`N/A`
Gemini version: `1.7.3`

Test: `gemini-1tb-10h`
Test name: `gemini_test.GeminiTest.test_random_load`
Test config file(s):
- [gemini-1tb-10h.yaml] (https://github.com/scylladb/scylla-cluster-tests/blob/6644dddd1e3074911f9e8046d37b0cbd217559ac/test-cases/gemini/gemini-1tb-10h.yaml)

**Issue description**

====================================
reactor stall,semaphore timeout followed by IO stop.

```
2020-12-27T14:35:21+00:00  gemini-1tb-10h-master-db-node-422dd4c9-1 !INFO    | scylla: Reactor stalled for 656 ms on shard 11.
2020-12-27T14:35:21+00:00  gemini-1tb-10h-master-db-node-422dd4c9-1 !INFO    | scylla: Backtrace:
2020-12-27T14:35:21+00:00  gemini-1tb-10h-master-db-node-422dd4c9-1 !INFO    | scylla: 0x00000000038d6263
2020-12-27T14:35:21+00:00  gemini-1tb-10h-master-db-node-422dd4c9-1 !INFO    | scylla: 0x00000000038d6f5f
2020-12-27T14:35:21+00:00  gemini-1tb-10h-master-db-node-422dd4c9-1 !INFO    | scylla: 0x00007fe8219371df
2020-12-27T14:35:21+00:00  gemini-1tb-10h-master-db-node-422dd4c9-1 !INFO    | scylla: 0x00000000012868c0
2020-12-27T14:35:21+00:00  gemini-1tb-10h-master-db-node-422dd4c9-1 !INFO    | scylla: 0x00000000011440c2
2020-12-27T14:35:21+00:00  gemini-1tb-10h-master-db-node-422dd4c9-1 !INFO    | scylla: 0x0000000001219ead
2020-12-27T14:35:21+00:00  gemini-1tb-10h-master-db-node-422dd4c9-1 !INFO    | scylla: 0x00000000011ff5a2
2020-12-27T14:35:21+00:00  gemini-1tb-10h-master-db-node-422dd4c9-1 !INFO    | scylla: 0x00000000012007c1
2020-12-27T14:35:21+00:00  gemini-1tb-10h-master-db-node-422dd4c9-1 !INFO    | scylla: 0x00000000011f40bd
2020-12-27T14:35:21+00:00  gemini-1tb-10h-master-db-node-422dd4c9-1 !INFO    | scylla: 0x000000000121ed8d
2020-12-27T14:35:21+00:00  gemini-1tb-10h-master-db-node-422dd4c9-1 !INFO    | scylla: 0x00000000038a2942
2020-12-27T14:35:21+00:00  gemini-1tb-10h-master-db-node-422dd4c9-1 !INFO    | scylla: 0x00000000038a2c40
2020-12-27T14:35:21+00:00  gemini-1tb-10h-master-db-node-422dd4c9-1 !INFO    | scylla: 0x00000000038a45ab
2020-12-27T14:35:21+00:00  gemini-1tb-10h-master-db-node-422dd4c9-1 !INFO    | scylla: 0x00000000038a7415
2020-12-27T14:35:21+00:00  gemini-1tb-10h-master-db-node-422dd4c9-1 !INFO    | scylla: 0x0000000001091131
2020-12-27T14:35:21+00:00  gemini-1tb-10h-master-db-node-422dd4c9-1 !INFO    | scylla: 0x0000000001672a89
2020-12-27T14:35:21+00:00  gemini-1tb-10h-master-db-node-422dd4c9-1 !INFO    | scylla: 0x0000000001675317
2020-12-27T14:35:21+00:00  gemini-1tb-10h-master-db-node-422dd4c9-1 !INFO    | scylla: 0x000000000175c67c
2020-12-27T14:35:21+00:00  gemini-1tb-10h-master-db-node-422dd4c9-1 !INFO    | scylla: 0x000000000175b29b
2020-12-27T14:35:21+00:00  gemini-1tb-10h-master-db-node-422dd4c9-1 !INFO    | scylla: 0x000000000175a9e9
2020-12-27T14:35:21+00:00  gemini-1tb-10h-master-db-node-422dd4c9-1 !INFO    | scylla: 0x000000000175a286
2020-12-27T14:35:21+00:00  gemini-1tb-10h-master-db-node-422dd4c9-1 !INFO    | scylla: 0x0000000001759b27
2020-12-27T14:35:21+00:00  gemini-1tb-10h-master-db-node-422dd4c9-1 !INFO    | scylla: 0x00000000017599f3
2020-12-27T14:35:21+00:00  gemini-1tb-10h-master-db-node-422dd4c9-1 !INFO    | scylla: 0x0000000003b67661
2020-12-27T14:36:30+00:00  gemini-1tb-10h-master-db-node-422dd4c9-1 !INFO    | scylla: [shard 1] reader_concurrency_semaphore - Semaphore _read_concurrency_sem: timed out, dumping permit diagnostics:#012Permits with state admitted, sorted by memory#012memory#011count#011name#012140M#01110
2020-12-27T14:36:30+00:00  gemini-1tb-10h-master-db-node-422dd4c9-1 !ERR     | scylla: [shard 1] storage_proxy - Exception when communicating with 10.0.1.151, to read from ks1.table1_col2_idx_index: seastar::named_semaphore_timed_out (Semaphore timed out: _read_concurrency_sem)
2020-12-27T14:36:30+00:00  gemini-1tb-10h-master-db-node-422dd4c9-1 !ERR     | scylla: [shard 9] storage_proxy - Exception when communicating with 10.0.1.151, to read from ks1.table1_col2_idx_index: seastar::named_semaphore_timed_out (Semaphore timed out: _read_concurrency_sem)
2020-12-27T14:
```

**Decoded backtrace**

```
void seastar::backtrace<seastar::backtrace_buffer::append_backtrace()::{lambda(seastar::frame)#1}>(seastar::backtrace_buffer::append_backtrace()::{lambda(seastar::frame)#1}&&) at ./build/release/seastar/./seastar/include/seastar/util/backtrace.hh:59
 (inlined by) seastar::backtrace_buffer::append_backtrace() at ./build/release/seastar/./seastar/src/core/reactor.cc:731
 (inlined by) seastar::print_with_backtrace(seastar::backtrace_buffer&) at ./build/release/seastar/./seastar/src/core/reactor.cc:752
 (inlined by) seastar::internal::cpu_stall_detector::generate_trace() at ./build/release/seastar/./seastar/src/core/reactor.cc:1210
seastar::internal::cpu_stall_detector::maybe_report() at ./build/release/seastar/./seastar/src/core/reactor.cc:1056
 (inlined by) seastar::internal::cpu_stall_detector::on_signal() at ./build/release/seastar/./seastar/src/core/reactor.cc:1070
 (inlined by) seastar::reactor::block_notifier(int) at ./build/release/seastar/./seastar/src/core/reactor.cc:1193
?? ??:0
~row at ./mutation_partition.cc:1634
~deletable_row at ././mutation_partition.hh:952
 (inlined by) ~rows_entry at ././mutation_partition.hh:1026
 (inlined by) standard_migrator<rows_entry>::migrate(void*, void*, unsigned long) const at ././utils/allocation_strategy.hh:76
operator() at ./utils/logalloc.cc:1277
 (inlined by) void logalloc::region_impl::for_each_live<logalloc::region_impl::compact_segment_locked(logalloc::segment*, logalloc::segment_descriptor&)::{lambda(logalloc::region_impl::object_descriptor const*, void*, unsigned long)#1}>(logalloc::segment*, logalloc::region_impl::compact_segment_locked(logalloc::segment*, logalloc::segment_descriptor&)::{lambda(logalloc::region_impl::object_descriptor const*, void*, unsigned long)#1}&&) at ./utils/logalloc.cc:1218
 (inlined by) logalloc::region_impl::compact_segment_locked(logalloc::segment*, logalloc::segment_descriptor&) at ./utils/logalloc.cc:1274
logalloc::region_impl::compact() at ./utils/logalloc.cc:1563
logalloc::tracker::impl::compact_and_evict_locked(unsigned long, unsigned long) at ./utils/logalloc.cc:2015
logalloc::tracker::impl::reclaim(unsigned long) at ./utils/logalloc.cc:1931
logalloc::tracker::reclaim(unsigned long) at ./utils/logalloc.cc:432
 (inlined by) logalloc::tracker::reclaim(seastar::memory::reclaimer::request) at ./utils/logalloc.cc:1679
 (inlined by) operator() at ./utils/logalloc.cc:425
 (inlined by) seastar::memory::reclaiming_result std::__invoke_impl<seastar::memory::reclaiming_result, logalloc::tracker::tracker()::$_1&, seastar::memory::reclaimer::request>(std::__invoke_other, logalloc::tracker::tracker()::$_1&, seastar::memory::reclaimer::request&&) at /usr/lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/bits/invoke.h:60
 (inlined by) std::enable_if<is_invocable_r_v<seastar::memory::reclaiming_result, logalloc::tracker::tracker()::$_1&, seastar::memory::reclaimer::request>, seastar::memory::reclaiming_result>::type std::__invoke_r<seastar::memory::reclaiming_result, logalloc::tracker::tracker()::$_1&, seastar::memory::reclaimer::request>(logalloc::tracker::tracker()::$_1&, seastar::memory::reclaimer::request&&) at /usr/lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/bits/invoke.h:113
 (inlined by) std::_Function_handler<seastar::memory::reclaiming_result (seastar::memory::reclaimer::request), logalloc::tracker::tracker()::$_1>::_M_invoke(std::_Any_data const&, seastar::memory::reclaimer::request&&) at /usr/lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/bits/std_function.h:291
std::function<seastar::memory::reclaiming_result (seastar::memory::reclaimer::request)>::operator()(seastar::memory::reclaimer::request) const at /usr/lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/bits/std_function.h:622
 (inlined by) seastar::memory::reclaimer::do_reclaim(unsigned long) at ./build/release/seastar/./seastar/include/seastar/core/memory.hh:199
 (inlined by) seastar::memory::cpu_pages::run_reclaimers(seastar::memory::reclaimer_scope, unsigned long) at ./build/release/seastar/./seastar/src/core/memory.cc:1123
seastar::memory::cpu_pages::maybe_reclaim() at ./build/release/seastar/./seastar/src/core/memory.cc:706
 (inlined by) seastar::memory::cpu_pages::allocate_large_and_trim(unsigned int) at ./build/release/seastar/./seastar/src/core/memory.cc:745
seastar::memory::cpu_pages::allocate_large(unsigned int) at ./build/release/seastar/./seastar/src/core/memory.cc:767
 (inlined by) seastar::memory::allocate_large(unsigned long) at ./build/release/seastar/./seastar/src/core/memory.cc:1318
 (inlined by) seastar::memory::allocate(unsigned long) at ./build/release/seastar/./seastar/src/core/memory.cc:1380
malloc at ./build/release/seastar/./seastar/src/core/memory.cc:1806
bytes_ostream::alloc_new(unsigned int) at ././bytes_ostream.hh:164
bytes_ostream::write(std::basic_string_view<signed char, std::char_traits<signed char> >) at ././bytes_ostream.hh:265
 (inlined by) bytes_ostream::append(bytes_ostream const&) at ././bytes_ostream.hh:338
 (inlined by) bytes_ostream at ././bytes_ostream.hh:207
 (inlined by) sstables::mc::writer::write_promoted_index() at ./sstables/mx/writer.cc:1405
sstables::mc::writer::consume_end_of_partition() at ./sstables/mx/writer.cc:1461
sstables::compacting_sstable_writer::consume_end_of_partition() at ./sstables/compaction.cc:778
 (inlined by) seastar::bool_class<seastar::stop_iteration_tag> compact_mutation_state<(emit_only_live_rows)0, (compact_for_sstables)1>::consume_end_of_partition<sstables::compacting_sstable_writer, noop_compacted_fragments_consumer>(sstables::compacting_sstable_writer&, noop_compacted_fragments_consumer&) at ././mutation_compactor.hh:392
 (inlined by) compact_mutation<(emit_only_live_rows)0, (compact_for_sstables)1, sstables::compacting_sstable_writer, noop_compacted_fragments_consumer>::consume_end_of_partition() at ././mutation_compactor.hh:517
 (inlined by) stable_flattened_mutations_consumer<compact_for_compaction<sstables::compacting_sstable_writer, noop_compacted_fragments_consumer> >::consume_end_of_partition() at ././mutation_reader.hh:336
 (inlined by) flat_mutation_reader::impl::consumer_adapter<stable_flattened_mutations_consumer<compact_for_compaction<sstables::compacting_sstable_writer, noop_compacted_fragments_consumer> > >::consume(partition_end&&) at ././flat_mutation_reader.hh:230
 (inlined by) _ZNO17mutation_fragment7consumeIN20flat_mutation_reader4impl16consumer_adapterI35stable_flattened_mutations_consumerI22compact_for_compactionIN8sstables25compacting_sstable_writerE33noop_compacted_fragments_consumerEEEEEEDcRT_ at ././mutation_fragment.hh:433
flat_mutation_reader::impl::consumer_adapter<stable_flattened_mutations_consumer<compact_for_compaction<sstables::compacting_sstable_writer, noop_compacted_fragments_consumer> > >::operator()(mutation_fragment&&) at ././flat_mutation_reader.hh:210
 (inlined by) seastar::bool_class<seastar::stop_iteration_tag> std::__invoke_impl<seastar::bool_class<seastar::stop_iteration_tag>, flat_mutation_reader::impl::consumer_adapter<stable_flattened_mutations_consumer<compact_for_compaction<sstables::compacting_sstable_writer, noop_compacted_fragments_consumer> > >&, mutation_fragment>(std::__invoke_other, flat_mutation_reader::impl::consumer_adapter<stable_flattened_mutations_consumer<compact_for_compaction<sstables::compacting_sstable_writer, noop_compacted_fragments_consumer> > >&, mutation_fragment&&) at /usr/lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/bits/invoke.h:60
 (inlined by) std::__invoke_result<flat_mutation_reader::impl::consumer_adapter<stable_flattened_mutations_consumer<compact_for_compaction<sstables::compacting_sstable_writer, noop_compacted_fragments_consumer> > >&, mutation_fragment>::type std::__invoke<flat_mutation_reader::impl::consumer_adapter<stable_flattened_mutations_consumer<compact_for_compaction<sstables::compacting_sstable_writer, noop_compacted_fragments_consumer> > >&, mutation_fragment>(flat_mutation_reader::impl::consumer_adapter<stable_flattened_mutations_consumer<compact_for_compaction<sstables::compacting_sstable_writer, noop_compacted_fragments_consumer> > >&, mutation_fragment&&) at /usr/lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/bits/invoke.h:95
 (inlined by) std::result_of<flat_mutation_reader::impl::consumer_adapter<stable_flattened_mutations_consumer<compact_for_compaction<sstables::compacting_sstable_writer, noop_compacted_fragments_consumer> > >& (mutation_fragment&&)>::type std::reference_wrapper<flat_mutation_reader::impl::consumer_adapter<stable_flattened_mutations_consumer<compact_for_compaction<sstables::compacting_sstable_writer, noop_compacted_fragments_consumer> > > >::operator()<mutation_fragment>(mutation_fragment&&) const at /usr/lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/bits/refwrap.h:349
 (inlined by) void flat_mutation_reader::impl::consume_pausable_in_thread<std::reference_wrapper<flat_mutation_reader::impl::consumer_adapter<stable_flattened_mutations_consumer<compact_for_compaction<sstables::compacting_sstable_writer, noop_compacted_fragments_consumer> > > >, flat_mutation_reader::no_filter>(std::reference_wrapper<flat_mutation_reader::impl::consumer_adapter<stable_flattened_mutations_consumer<compact_for_compaction<sstables::compacting_sstable_writer, noop_compacted_fragments_consumer> > > >, flat_mutation_reader::no_filter, std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >) at ././flat_mutation_reader.hh:193
 (inlined by) auto flat_mutation_reader::impl::consume_in_thread<stable_flattened_mutations_consumer<compact_for_compaction<sstables::compacting_sstable_writer, noop_compacted_fragments_consumer> >, flat_mutation_reader::no_filter>(stable_flattened_mutations_consumer<compact_for_compaction<sstables::compacting_sstable_writer, noop_compacted_fragments_consumer> >, flat_mutation_reader::no_filter, std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >) at ././flat_mutation_reader.hh:273
auto flat_mutation_reader::consume_in_thread<stable_flattened_mutations_consumer<compact_for_compaction<sstables::compacting_sstable_writer, noop_compacted_fragments_consumer> >, flat_mutation_reader::no_filter>(stable_flattened_mutations_consumer<compact_for_compaction<sstables::compacting_sstable_writer, noop_compacted_fragments_consumer> >, flat_mutation_reader::no_filter, std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >) at ././flat_mutation_reader.hh:383
auto flat_mutation_reader::consume_in_thread<stable_flattened_mutations_consumer<compact_for_compaction<sstables::compacting_sstable_writer, noop_compacted_fragments_consumer> > >(stable_flattened_mutations_consumer<compact_for_compaction<sstables::compacting_sstable_writer, noop_compacted_fragments_consumer> >, std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >) at ././flat_mutation_reader.hh:389
operator() at ./sstables/compaction.cc:612
void std::__invoke_impl<void, seastar::future<void> sstables::compaction::setup<noop_compacted_fragments_consumer>(noop_compacted_fragments_consumer)::{lambda(flat_mutation_reader)#1}::operator()(flat_mutation_reader)::{lambda()#1}>(std::__invoke_other, seastar::future<void> sstables::compaction::setup<noop_compacted_fragments_consumer>(noop_compacted_fragments_consumer)::{lambda(flat_mutation_reader)#1}::operator()(flat_mutation_reader)::{lambda()#1}&&) at /usr/lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/bits/invoke.h:60
 (inlined by) std::__invoke_result<seastar::future<void> sstables::compaction::setup<noop_compacted_fragments_consumer>(noop_compacted_fragments_consumer)::{lambda(flat_mutation_reader)#1}::operator()(flat_mutation_reader)::{lambda()#1}>::type std::__invoke<seastar::future<void> sstables::compaction::setup<noop_compacted_fragments_consumer>(noop_compacted_fragments_consumer)::{lambda(flat_mutation_reader)#1}::operator()(flat_mutation_reader)::{lambda()#1}>(seastar::future<void> sstables::compaction::setup<noop_compacted_fragments_consumer>(noop_compacted_fragments_consumer)::{lambda(flat_mutation_reader)#1}::operator()(flat_mutation_reader)::{lambda()#1}&&, (seastar::future<void> sstables::compaction::setup<noop_compacted_fragments_consumer>(noop_compacted_fragments_consumer)::{lambda(flat_mutation_reader)#1}::operator()(flat_mutation_reader)::{lambda()#1}&&)...) at /usr/lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/bits/invoke.h:95
 (inlined by) _ZSt12__apply_implIZZN8sstables10compaction5setupI33noop_compacted_fragments_consumerEEN7seastar6futureIvEET_ENUl20flat_mutation_readerE_clES8_EUlvE_St5tupleIJEEJEEDcOS7_OT0_St16integer_sequenceImJXspT1_EEE at /usr/lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/tuple:1723
 (inlined by) _ZSt5applyIZZN8sstables10compaction5setupI33noop_compacted_fragments_consumerEEN7seastar6futureIvEET_ENUl20flat_mutation_readerE_clES8_EUlvE_St5tupleIJEEEDcOS7_OT0_ at /usr/lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/tuple:1734
 (inlined by) seastar::future<void> seastar::futurize<void>::apply<seastar::future<void> sstables::compaction::setup<noop_compacted_fragments_consumer>(noop_compacted_fragments_consumer)::{lambda(flat_mutation_reader)#1}::operator()(flat_mutation_reader)::{lambda()#1}>(seastar::future<void> sstables::compaction::setup<noop_compacted_fragments_consumer>(noop_compacted_fragments_consumer)::{lambda(flat_mutation_reader)#1}::operator()(flat_mutation_reader)::{lambda()#1}&&, std::tuple<>&&) at ././seastar/include/seastar/core/future.hh:2099
 (inlined by) operator() at ././seastar/include/seastar/core/thread.hh:258
 (inlined by) seastar::noncopyable_function<void ()>::direct_vtable_for<seastar::futurize<std::result_of<std::decay<seastar::future<void> sstables::compaction::setup<noop_compacted_fragments_consumer>(noop_compacted_fragments_consumer)::{lambda(flat_mutation_reader)#1}::operator()(flat_mutation_reader)::{lambda()#1}>::type ()>::type>::type seastar::async<seastar::future<void> sstables::compaction::setup<noop_compacted_fragments_consumer>(noop_compacted_fragments_consumer)::{lambda(flat_mutation_reader)#1}::operator()(flat_mutation_reader)::{lambda()#1}>(seastar::thread_attributes, seastar::future<void> sstables::compaction::setup<noop_compacted_fragments_consumer>(noop_compacted_fragments_consumer)::{lambda(flat_mutation_reader)#1}::operator()(flat_mutation_reader)::{lambda()#1}&&, (std::decay<seastar::future<void> sstables::compaction::setup<noop_compacted_fragments_consumer>(noop_compacted_fragments_consumer)::{lambda(flat_mutation_reader)#1}::operator()(flat_mutation_reader)::{lambda()#1}>&&)...)::{lambda()#1}>::call(seastar::noncopyable_function<void ()> const*) at ././seastar/include/seastar/util/noncopyable_function.hh:124
seastar::noncopyable_function<void ()>::operator()() const at ./build/release/seastar/./seastar/include/seastar/util/noncopyable_function.hh:209
 (inlined by) seastar::thread_context::main() at ./build/release/seastar/./seastar/src/core/thread.cc:297
```
![gemini10H#72_reactor_stall_io_stop](https://user-images.githubusercontent.com/99000/103213059-30fd9c80-4915-11eb-970a-bf35b0cca698.png)

====================================

Restore Monitor Stack command: `$ hydra investigate show-monitor 422dd4c9-fa14-42b2-89e1-af1087a4cbf5`
Show all stored logs command: `$ hydra investigate show-logs 422dd4c9-fa14-42b2-89e1-af1087a4cbf5`

Test id: `422dd4c9-fa14-42b2-89e1-af1087a4cbf5`

Logs:
db-cluster - [https://cloudius-jenkins-test.s3.amazonaws.com/422dd4c9-fa14-42b2-89e1-af1087a4cbf5/20201228_014612/db-cluster-422dd4c9.zip](https://cloudius-jenkins-test.s3.amazonaws.com/422dd4c9-fa14-42b2-89e1-af1087a4cbf5/20201228_014612/db-cluster-422dd4c9.zip)
loader-set - [https://cloudius-jenkins-test.s3.amazonaws.com/422dd4c9-fa14-42b2-89e1-af1087a4cbf5/20201228_014612/loader-set-422dd4c9.zip](https://cloudius-jenkins-test.s3.amazonaws.com/422dd4c9-fa14-42b2-89e1-af1087a4cbf5/20201228_014612/loader-set-422dd4c9.zip)
sct-runner - [https://cloudius-jenkins-test.s3.amazonaws.com/422dd4c9-fa14-42b2-89e1-af1087a4cbf5/20201228_014612/sct-runner-422dd4c9.zip](https://cloudius-jenkins-test.s3.amazonaws.com/422dd4c9-fa14-42b2-89e1-af1087a4cbf5/20201228_014612/sct-runner-422dd4c9.zip)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/gemini-/job/gemini-1tb-10h/72/)

**Comment by raphaelsc** [comment] 2020-12-28 12:07
looks like a large allocation case.

**Comment by raphaelsc** [comment] 2020-12-28 12:33
```
2020-12-27T14:58:34+00:00  gemini-1tb-10h-master-db-node-422dd4c9-1 !WARNING | scylla: [shard 11] large_data - Writing large partition ks1/table1_col2_idx_index: -50 (1060852339 bytes)
2020-12-27T14:58:34+00:00  gemini-1tb-10h-master-db-node-422dd4c9-1 !WARNING | scylla: [shard 11] large_data - Writing a partition with too many rows [ks1/table1_col2_idx_index:-50] (106152 rows)
```

figured out the problem is that too many rows will result in large allocation when serializing all blocks of promoted index.

**Comment by raphaelsc** [comment] 2020-12-28 12:43
however, bytes_ostream used to store promotex index blocks will use 128k chunks, perhaps the fragmented blocks are serialized somewhere in the path before the data reaches the index file causing a large allocation?

**Comment by bhalevy** [comment] 2021-01-14 14:00
@denesb please look into this

**Comment by raphaelsc** [comment] 2021-01-14 14:22
On Thu, Jan 14, 2021 at 11:00 AM Benny Halevy <notifications@github.com>
wrote:

> @denesb <https://github.com/denesb> please look into this
>

that's foreground reclaim causing stalls, a known issue, it will only be
fixed once we implement background reclaim, a solution was outlined by Avi
here:
https://groups.google.com/u/1/g/scylladb-dev/c/5u9Qi2Al43k/m/9vsNCNORAQAJ

**Comment by slivne** [comment] 2022-02-08 22:36
we added background reclaim 935378fa53bf4ad27806aad735d4add9c63e7f85 - closing if this reproduces please open an issue

**Closed by slivne** 2022-02-08 22:36 UTC
Labels: bug, large partitions
