### ISSUE TITLE
Aggregation of counters

### ISSUE THREAD

**Issue by tkozybski** [scylladb/scylla#3174] opened 2018-02-01 08:54 UTC
*Installation details*
Scylla version (or git commit hash): 2.1-rc2

Hello. I noticed that aggregation functions doesn't work on counters. I don't see any reason this shouldn't be possible.

How to reproduce:
```
CREATE TABLE test (
        key INT,
        ctr COUNTER,
        PRIMARY KEY (
                key
        )
);

UPDATE test SET ctr = ctr + 1 WHERE key = 1;
SELECT SUM(ctr) FROM test;
```

Result
> InvalidRequest: Error from server: code=2200 [Invalid query] message="Invalid call to function sum, none of its type signatures match (known type signatures: system.sum : (org.apache.cassandra.db.marshal.DecimalType) -> org.apache.cassandra.db.marshal.DecimalType, system.sum : (org.apache.cassandra.db.marshal.IntegerType) -> org.apache.cassandra.db.marshal.IntegerType, system.sum : (org.apache.cassandra.db.marshal.DoubleType) -> org.apache.cassandra.db.marshal.DoubleType, system.sum : (org.apache.cassandra.db.marshal.FloatType) -> org.apache.cassandra.db.marshal.FloatType, system.sum : (org.apache.cassandra.db.marshal.LongType) -> org.apache.cassandra.db.marshal.LongType, system.sum : (org.apache.cassandra.db.marshal.Int32Type) -> org.apache.cassandra.db.marshal.Int32Type, system.sum : (org.apache.cassandra.db.marshal.ShortType) -> org.apache.cassandra.db.marshal.ShortType, system.sum : (org.apache.cassandra.db.marshal.ByteType) -> org.apache.cassandra.db.marshal.ByteType)"

I also tried casting
`SELECT SUM(CAST(ctr as bigint)) FROM test`
but it's not working either

> Error from server: code=2200 [Invalid query] message="org.apache.cassandra.db.marshal.CounterColumnType cannot be cast to org.apache.cassandra.db.marshal.LongType"

**Comment by tzach** [comment] 2018-02-01 11:08
@pdziepak ?

**Comment by slivne** [comment] 2018-02-04 11:45
@penberg  / @pdziepak ?

**Comment by pdziepak** [comment] 2018-02-05 17:04
Looks like it was added in [1]. No reason not to implement this in Scylla as well. If I remember correctly at this stage counters are already treated as `bigint` values (and not sets of counter shards) so supporting aggregating them shouldn't be very difficult.

[1] https://issues.apache.org/jira/browse/CASSANDRA-9977

**Comment by antsmc2** [comment] 2018-08-23 17:43
Was issue fixed in the latest release (2.3.rc1)? I'm using 2.2.0 and still facing this issue.

**Comment by tzach** [comment] 2018-08-25 08:32
@antsmc2 issue is not fixed yet. Once it does, you should see a commit link in the comments

**Comment by noamguy** [comment] 2019-05-22 11:02
Any news regarding **sum** on counter fields?

**Comment by jimmykuo** [comment] 2019-06-10 07:22
@pdziepak 

Try to `cast`, but it doesn´t work either
https://docs.scylladb.com/getting-started/functions/#cast

```
InvalidRequest: Error from server: code=2200 [Invalid query] message="org.apache.cassandra.db.marshal.CounterColumnType cannot be cast to org.apache.cassandra.db.marshal.Int32Type"

InvalidRequest: Error from server: code=2200 [Invalid query] message="org.apache.cassandra.db.marshal.CounterColumnType cannot be cast to org.apache.cassandra.db.marshal.LongType"
```

**Comment by jimmykuo** [comment] 2019-07-29 13:01
Any updates on this ? 🙏

**Comment by tzach** [comment] 2019-07-29 17:49
@jimmykuo no news yet. Waiting for a brave volunteer to send a PR

**Comment by mrsinham** [comment] 2020-01-08 14:03
Need this one as well

**Comment by slivne** [comment] 2020-01-08 14:06
@haaawk / @jul-stas - its a feature related to counters - so queue this up for you guys.

**Comment by gnumoreno** [comment] 2020-03-09 12:37
Reproducer:

```
CREATE KEYSPACE test WITH REPLICATION = { 'class' : 'SimpleStrategy', 'replication_factor' : 1 };
CREATE TABLE test.wsgcounter ( countername text PRIMARY KEY, counterval counter );
UPDATE wsgcounter SET counterval = counterval + 1 WHERE countername = 'bla';
UPDATE wsgcounter SET counterval = counterval + 10 WHERE countername = 'ble';
UPDATE wsgcounter SET counterval = counterval + 100 WHERE countername = 'bli';
select cast(counterval as varchar) from wsgcounter where countername='bla';
```

**Comment by slivne** [comment] 2020-03-09 13:33
@gnumoreno  its casting not a sum function, why do you need to cast the value (in this case it was an attempt to make the value an int that can be summed.

**Comment by gnumoreno** [comment] 2020-03-09 17:31
@slivne the original poster also mentioned casting, please check the first post on the thread.

**Comment by jul-stas** [comment] 2020-03-10 12:01
Aggregation is already solved and merged to master: https://github.com/scylladb/scylla/pull/5632 . (GH somehow didn't close this issue...)
Rearding casts: currently only **implicit** cast to long is supported. If we need other casts let's open a new issue and talk about it.

**Comment by slivne** [comment] 2020-03-24 21:48
fixed by https://github.com/scylladb/scylla/commit/127e258adeb044873d20606b82fc1f1d7e62d34b

**Closed by slivne** 2020-03-24 21:48 UTC
Labels: User Request, bug, cassandra 2.2 compatibility, counters
