### ISSUE TITLE
Unexpected node restart during adding new DC

### ISSUE THREAD

**Issue by p-osipo-v** [scylladb/scylla#7982] opened 2021-01-28 13:40 UTC
Hi, Scylla team!
We are have 5-nodes scylla cluster in one DC and adding second DC, 5 nodes too.
After altering keyspaces with parameter

`replication = { 'class' : 'NetworkTopologyStrategy', '<exiting_dc>' : 3, <new_dc> : 3};`

we ran nodetool rebuild -- <existing_dc> on one node in new DC. During this command work nodes in existing DC are unexpectedly restarting in random order. Logs before restart contains records like this:

Jan 28 15:55:24 p2087 scylla[76444]: scylla: ./interval.hh:129: bool wrapping_interval<T>::before(const T&, Comparator&&) const [with Comparator = const dht::ring_position_comparator&; T = dht::ring_position]: Assertion `!is_wrap_around(
Jan 28 15:55:24 p2087 scylla[76444]: Aborting on shard 4.
Jan 28 15:55:24 p2087 scylla[76444]: Backtrace:
Jan 28 15:55:24 p2087 scylla[76444]: 0x0000000002efb912
Jan 28 15:55:24 p2087 scylla[76444]: 0x0000000002e9fe90
Jan 28 15:55:24 p2087 scylla[76444]: 0x0000000002ea0135
Jan 28 15:55:24 p2087 scylla[76444]: 0x0000000002ea0180
Jan 28 15:55:24 p2087 scylla[76444]: 0x00007fb5e853aa8f
Jan 28 15:55:24 p2087 scylla[76444]: /opt/scylladb/libreloc/libc.so.6+0x000000000003c9e4
Jan 28 15:55:24 p2087 scylla[76444]: /opt/scylladb/libreloc/libc.so.6+0x0000000000025894
Jan 28 15:55:24 p2087 scylla[76444]: /opt/scylladb/libreloc/libc.so.6+0x0000000000025768
Jan 28 15:55:24 p2087 scylla[76444]: /opt/scylladb/libreloc/libc.so.6+0x0000000000034e75
Jan 28 15:55:24 p2087 scylla[76444]: 0x0000000001175795
Jan 28 15:55:24 p2087 scylla[76444]: 0x0000000001179882
Jan 28 15:55:24 p2087 scylla[76444]: 0x0000000002e9d237
Jan 28 15:55:24 p2087 scylla[76444]: 0x0000000002e9d5ae
Jan 28 15:55:24 p2087 scylla[76444]: 0x0000000002ed468d
Jan 28 15:55:24 p2087 scylla[76444]: 0x0000000002ee408a
Jan 28 15:55:24 p2087 scylla[76444]: 0x0000000002e6830d
Jan 28 15:55:24 p2087 scylla[76444]: /opt/scylladb/libreloc/libpthread.so.0+0x0000000000009431
Jan 28 15:55:24 p2087 scylla[76444]: /opt/scylladb/libreloc/libc.so.6+0x0000000000101912

No more records in log at that time.
Scylla version 4.2.2
What kind of information we can also provide for diagnostics?

**Comment by p-osipo-v** [comment] 2021-02-08 13:26
New info about this issue.
In Scylla Opensource 4.3 this behavior is present too, and not during rebuild only, but during nodes repair nodes in other DC are unexpectedly restarting.

**Comment by slivne** [comment] 2021-02-08 14:41
If you have a coredump generated can you please upload the core using the instructions in https://docs.scylladb.com/troubleshooting/report_scylla_problem/

Can you please provide info as to what is the setup of the cluster

If you an also upload the health_check it will help to extract the info from each machine with regards to its setup.
- if not please at least provide the number of machines their type and ``` ps -ef | grep scylla ``` on each machine.

**Comment by asias** [comment] 2021-02-09 00:21
> New info about this issue.
> In Scylla Opensource 4.3 this behavior is present too, and not during rebuild only, but during nodes repair nodes in other DC are unexpectedly restarting.

Can you share the exact nodetool cmd you used to run repair?

**Comment by asias** [comment] 2021-02-09 00:43
```
seastar-addr2line -e scylla/libexec/scylla
Jan 28 15:55:24 p2087 scylla[76444]: Backtrace:
Jan 28 15:55:24 p2087 scylla[76444]: 0x0000000002efb912
Jan 28 15:55:24 p2087 scylla[76444]: 0x0000000002e9fe90
Jan 28 15:55:24 p2087 scylla[76444]: 0x0000000002ea0135
Jan 28 15:55:24 p2087 scylla[76444]: 0x0000000002ea0180
Jan 28 15:55:24 p2087 scylla[76444]: 0x00007fb5e853aa8f
Jan 28 15:55:24 p2087 scylla[76444]: /opt/scylladb/libreloc/libc.so.6+0x000000000003c9e4
Jan 28 15:55:24 p2087 scylla[76444]: /opt/scylladb/libreloc/libc.so.6+0x0000000000025894
Jan 28 15:55:24 p2087 scylla[76444]: /opt/scylladb/libreloc/libc.so.6+0x0000000000025768
Jan 28 15:55:24 p2087 scylla[76444]: /opt/scylladb/libreloc/libc.so.6+0x0000000000034e75
Jan 28 15:55:24 p2087 scylla[76444]: 0x0000000001175795
Jan 28 15:55:24 p2087 scylla[76444]: 0x0000000001179882
Jan 28 15:55:24 p2087 scylla[76444]: 0x0000000002e9d237
Jan 28 15:55:24 p2087 scylla[76444]: 0x0000000002e9d5ae
Jan 28 15:55:24 p2087 scylla[76444]: 0x0000000002ed468d
Jan 28 15:55:24 p2087 scylla[76444]: 0x0000000002ee408a
Jan 28 15:55:24 p2087 scylla[76444]: 0x0000000002e6830d
Jan 28 15:55:24 p2087 scylla[76444]: /opt/scylladb/libreloc/libpthread.so.0+0x0000000000009431
Jan 28 15:55:24 p2087 scylla[76444]: /opt/scylladb/libreloc/libc.so.6+0x0000000000101912

Jan 28 15:55:24 p2087 scylla[76444]: Backtrace:Jan 28 15:55:24 p2087 scylla[76444]:
[Backtrace #0]
void seastar::backtrace<seastar::backtrace_buffer::append_backtrace()::{lambda(seastar::frame)#1}>(seastar::backtrace_buffer::append_backtrace()::{lambda(seastar::frame)#1}&&) at /data/jenkins/workspace/scylla-4.2/build/scylla/seastar/include/seastar/util/backtrace.hh:59
seastar::backtrace_buffer::append_backtrace() at /data/jenkins/workspace/scylla-4.2/build/scylla/seastar/src/core/reactor.cc:730
 (inlined by) print_with_backtrace at /data/jenkins/workspace/scylla-4.2/build/scylla/seastar/src/core/reactor.cc:751
seastar::print_with_backtrace(char const*) at /data/jenkins/workspace/scylla-4.2/build/scylla/seastar/src/core/reactor.cc:758
seastar::install_oneshot_signal_handler<6, &seastar::sigabrt_action>()::{lambda(int, siginfo_t*, void*)#1}::_FUN(int, siginfo_t*, void*) at /data/jenkins/workspace/scylla-4.2/build/scylla/seastar/src/core/reactor.cc:3469
 (inlined by) operator() at /data/jenkins/workspace/scylla-4.2/build/scylla/seastar/src/core/reactor.cc:3451
 (inlined by) _FUN at /data/jenkins/workspace/scylla-4.2/build/scylla/seastar/src/core/reactor.cc:3447
?? ??:0
/opt/scylladb/libreloc/libc.so.6: ELF 64-bit LSB shared object, x86-64, version 1 (GNU/Linux), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=7ca24d4dc3de9d62d9ad6bb25e5b70a3e57a342f, for GNU/Linux 3.2.0, not stripped

__GI_raise at :?
__GI_abort at :?
__assert_fail_base.cold at assert.c:?
__GI___assert_fail at :?
bool wrapping_interval<dht::ring_position>::before<dht::ring_position_comparator const&>(dht::ring_position const&, dht::ring_position_comparator const&) const at /data/jenkins/workspace/scylla-4.2/build/scylla/./interval.hh:129
 (inlined by) bool nonwrapping_interval<dht::ring_position>::before<dht::ring_position_comparator const&>(dht::ring_position const&, dht::ring_position_comparator const&) const at /data/jenkins/workspace/scylla-4.2/build/scylla/./interval.hh:469
 (inlined by) bool nonwrapping_interval<dht::ring_position>::contains<dht::ring_position_comparator const&>(dht::ring_position const&, dht::ring_position_comparator const&) const at /data/jenkins/workspace/scylla-4.2/build/scylla/./interval.hh:520
 (inlined by) evictable_reader::maybe_validate_partition_start(seastar::circular_buffer<mutation_fragment, std::allocator<mutation_fragment> > const&) at /data/jenkins/workspace/scylla-4.2/build/scylla/mutation_reader.cc:1270
seastar::continuation<seastar::internal::promise_base_with_type<seastar::bool_class<seastar::stop_iteration_tag> >, evictable_reader::do_fill_buffer(flat_mutation_reader&, std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda()#2}::operator()() const::{lambda()#1}, seastar::future<>::then_impl_nrvo<{lambda()#2}, {lambda()#1}<seastar::bool_class<seastar::stop_iteration_tag> > >({lambda()#2}&&)::{lambda()#1}::operator()() const::{lambda(seastar::internal::promise_base_with_type<seastar::bool_class<seastar::stop_iteration_tag> >&, {lambda()#2}&, seastar::future_state<>&&)#1}>::run_and_dispose() at /data/jenkins/workspace/scylla-4.2/build/scylla/mutation_reader.cc:1358
 (inlined by) __invoke_impl<seastar::bool_class<seastar::stop_iteration_tag>, evictable_reader::do_fill_buffer(flat_mutation_reader&, seastar::lowres_clock::time_point)::<lambda()>::<lambda()>&> at /usr/include/c++/10/bits/invoke.h:60
 (inlined by) __invoke<evictable_reader::do_fill_buffer(flat_mutation_reader&, seastar::lowres_clock::time_point)::<lambda()>::<lambda()>&> at /usr/include/c++/10/bits/invoke.h:95
 (inlined by) __apply_impl<evictable_reader::do_fill_buffer(flat_mutation_reader&, seastar::lowres_clock::time_point)::<lambda()>::<lambda()>&, std::tuple<> > at /usr/include/c++/10/tuple:1723
 (inlined by) apply<evictable_reader::do_fill_buffer(flat_mutation_reader&, seastar::lowres_clock::time_point)::<lambda()>::<lambda()>&, std::tuple<> > at /usr/include/c++/10/tuple:1734
 (inlined by) operator() at /data/jenkins/workspace/scylla-4.2/build/scylla/seastar/include/seastar/core/future.hh:1525
 (inlined by) satisfy_with_result_of<seastar::future<T>::then_impl_nrvo<evictable_reader::do_fill_buffer(flat_mutation_reader&, seastar::lowres_clock::time_point)::<lambda()>::<lambda()>, seastar::future<seastar::bool_class<seastar::stop_iteration_tag> > >::<lambda()>::<lambda(pr_type&, evictable_reader::do_fill_buffer(flat_mutation_reader&, seastar::lowres_clock::time_point)::<lambda()>::<lambda()>&, seastar::future_state<>&&)> mutable::<lambda()> > at /data/jenkins/workspace/scylla-4.2/build/scylla/seastar/include/seastar/core/future.hh:1954
 (inlined by) operator() at /data/jenkins/workspace/scylla-4.2/build/scylla/seastar/include/seastar/core/future.hh:1524
 (inlined by) run_and_dispose at /data/jenkins/workspace/scylla-4.2/build/scylla/seastar/include/seastar/core/future.hh:647
seastar::reactor::run_tasks(seastar::reactor::task_queue&) at /data/jenkins/workspace/scylla-4.2/build/scylla/seastar/src/core/reactor.cc:2144
seastar::reactor::run_some_tasks() at /data/jenkins/workspace/scylla-4.2/build/scylla/seastar/src/core/reactor.cc:2560
seastar::reactor::run_some_tasks() at /data/jenkins/workspace/scylla-4.2/build/scylla/seastar/src/core/reactor.cc:2543
 (inlined by) seastar::reactor::run() at /data/jenkins/workspace/scylla-4.2/build/scylla/seastar/src/core/reactor.cc:2715
seastar::smp::configure(boost::program_options::variables_map, seastar::reactor_config)::{lambda()#3}::operator()() const at /data/jenkins/workspace/scylla-4.2/build/scylla/seastar/src/core/reactor.cc:3890
std::function<void ()>::operator()() const at /usr/include/c++/10/bits/std_function.h:622
 (inlined by) seastar::posix_thread::start_routine(void*) at /data/jenkins/workspace/scylla-4.2/build/scylla/seastar/src/core/posix.cc:60
/opt/scylladb/libreloc/libpthread.so.0: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=d75253191e7d61f6945c8268759ab2afbabf2bc1, for GNU/Linux 3.2.0, not stripped

start_thread at pthread_create.c:?
__sysctl at ??:?
```

**Comment by p-osipo-v** [comment] 2021-02-09 14:22
I just uploaded health-check-report.txt and output_files.tgz from last restarted node during other node repair running. UUID 22831046-d230-4444-bf07-6aa835212eed
Restart was at 15:57 MSK and health-check-report script ran at 18:31 MSK
Shall I upload report files from other nodes? And shall I run health-check-report script immediately after unexpected restart?

Nodes in DC named 'ds' are unexpectedly restarting during nodes in DC named 'nord' are running command
nodetool rebuild -- ds
or
nodetool repair -pr

**Comment by slivne** [comment] 2021-02-14 08:47
maybe related to https://github.com/scylladb/scylla/issues/8059

**Comment by denesb** [comment] 2021-02-15 10:22
#8059 can create a wrapping range if the reader is not evicted after fast forwarding. In this case the `_range_override` will have a partition from the post-fast-forwarded range, while its end bound will remain the pre-fast-forward-to range's end. As fast-forwarding requires strictly increasing ranges, this will produce a wrapping range. Closing as duplicate of #8059.

**Closed by denesb** 2021-02-15 10:22 UTC
Labels: User Request, bug
