### ISSUE TITLE
[dtest] sstableloader: Unknown property 'scylla_tags'

### ISSUE THREAD

**Issue by fruch** [scylladb/scylla#10856] opened 2022-06-22 09:50 UTC
```
AssertionError: The stderr of sstableloader is not empty: org.apache.cassandra.exceptions.SyntaxException: Unknown property 'scylla_tags'
  	at org.apache.cassandra.cql3.statements.PropertyDefinitions.validate(PropertyDefinitions.java:58)
  	at org.apache.cassandra.cql3.statements.TableAttributes.validate(TableAttributes.java:54)
  	at org.apache.cassandra.cql3.statements.CFProperties.validate(CFProperties.java:35)
  	at org.apache.cassandra.cql3.statements.CreateTableStatement$RawStatement.prepare(CreateTableStatement.java:216)
  	at com.scylladb.tools.BulkLoader$CQLClient.getCFMetaData(BulkLoader.java:700)
  	at com.scylladb.tools.BulkLoader.process(BulkLoader.java:1569)
  	at com.scylladb.tools.BulkLoader.lambda$main$1(BulkLoader.java:1367)
  	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
  	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  	at java.lang.Thread.run(Thread.java:748)
  org.apache.cassandra.exceptions.SyntaxException: Unknown property 'scylla_tags'
  	at org.apache.cassandra.cql3.statements.PropertyDefinitions.validate(PropertyDefinitions.java:58)
  	at org.apache.cassandra.cql3.statements.TableAttributes.validate(TableAttributes.java:54)
  	at org.apache.cassandra.cql3.statements.CFProperties.validate(CFProperties.java:35)
  	at org.apache.cassandra.cql3.statements.CreateTableStatement$RawStatement.prepare(CreateTableStatement.java:216)
  	at com.scylladb.tools.BulkLoader$CQLClient.getCFMetaData(BulkLoader.java:700)
  	at com.scylladb.tools.BulkLoader.process(BulkLoader.java:1569)
  	at com.scylladb.tools.BulkLoader.lambda$main$1(BulkLoader.java:1367)
  	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
  	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  	at java.lang.Thread.run(Thread.java:748)
  
assert not "org.apache.cassandra.exceptions.SyntaxException: Unknown property 'scylla_tags'\n\tat org.apache.cassandra.cql3.state...il.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)\n\tat java.lang.Thread.run(Thread.java:748)\n"
```

Started happening today, in 3 alternator dtest:
https://jenkins.scylladb.com/job/scylla-master/job/dtest-daily-release/37/testReport/alternator_tests/TesterAlternator/Run_Dtest_Parallel_Cloud_Machines___FullDtest___full_split001___test_sstableloder_scenario_nb_flag_/
https://jenkins.scylladb.com/job/scylla-master/job/dtest-daily-release/37/testReport/alternator_tests/TesterAlternator/Run_Dtest_Parallel_Cloud_Machines___FullDtest___full_split001___test_sstableloder_scenario_v_flag_/
https://jenkins.scylladb.com/job/scylla-master/job/dtest-daily-release/37/testReport/alternator_tests/TesterAlternator/Run_Dtest_Parallel_Cloud_Machines___FullDtest___full_split001___test_sstableloder_scenario_without_flag_/

**Comment by fruch** [comment] 2022-06-22 10:00
I assume that 
https://github.com/scylladb/scylla-tools-java/commit/de8289690e12ba3b96168dfb201d01380a9292c3

is the cause, 

I'm guessing it might be specifically cause of moving between those two versions of the scylla driver 

```
          <dependency groupId="com.scylladb" artifactId="scylla-driver-core" version="3.7.1-scylla-2" classifier="shaded" />
          <dependency groupId="com.scylladb" artifactId="scylla-driver-core" version="3.11.2.0" classifier="shaded" />
```

**Comment by avelanarius** [comment] 2022-06-22 10:32
Yes, unfortunately, this is caused by driver change.

https://github.com/scylladb/scylla-tools-java/blob/de8289690e12ba3b96168dfb201d01380a9292c3/src/java/com/scylladb/tools/BulkLoader.java#L697

`asCQLQuery()` in this line (linked above) behaves differently in the newer driver. In the old driver, it wouldn't print `scylla_tags`, while in the new driver it prints it.

Question about those tests:
https://jenkins.scylladb.com/job/scylla-master/job/dtest-daily-release/37/testReport/alternator_tests/TesterAlternator/Run_Dtest_Parallel_Cloud_Machines___FullDtest___full_split001___test_sstableloder_scenario_nb_flag_/
https://jenkins.scylladb.com/job/scylla-master/job/dtest-daily-release/37/testReport/alternator_tests/TesterAlternator/Run_Dtest_Parallel_Cloud_Machines___FullDtest___full_split001___test_sstableloder_scenario_v_flag_/
https://jenkins.scylladb.com/job/scylla-master/job/dtest-daily-release/37/testReport/alternator_tests/TesterAlternator/Run_Dtest_Parallel_Cloud_Machines___FullDtest___full_split001___test_sstableloder_scenario_without_flag_/

I assume those tests do not run on PR continuous integration? If I make a fix, how should I make sure that there aren't any other failing tests? - I assumed PR CI would do them all (except longevity).

**Comment by fruch** [comment] 2022-06-22 10:53
> Yes, unfortunately, this is caused by driver change.
> 
> https://github.com/scylladb/scylla-tools-java/blob/de8289690e12ba3b96168dfb201d01380a9292c3/src/java/com/scylladb/tools/BulkLoader.java#L697
> 
> `asCQLQuery()` in this line (linked above) behaves differently in the newer driver. In the old driver, it wouldn't print `scylla_tags`, while in the new driver it prints it.
> 
> Question about those tests: https://jenkins.scylladb.com/job/scylla-master/job/dtest-daily-release/37/testReport/alternator_tests/TesterAlternator/Run_Dtest_Parallel_Cloud_Machines___FullDtest___full_split001___test_sstableloder_scenario_nb_flag_/ https://jenkins.scylladb.com/job/scylla-master/job/dtest-daily-release/37/testReport/alternator_tests/TesterAlternator/Run_Dtest_Parallel_Cloud_Machines___FullDtest___full_split001___test_sstableloder_scenario_v_flag_/ https://jenkins.scylladb.com/job/scylla-master/job/dtest-daily-release/37/testReport/alternator_tests/TesterAlternator/Run_Dtest_Parallel_Cloud_Machines___FullDtest___full_split001___test_sstableloder_scenario_without_flag_/
> 
> I assume those tests do not run on PR continuous integration? If I make a fix, how should I make sure that there aren't any other failing tests? - I assumed PR CI would do them all (except longevity).

There is the daily run in this job:
https://jenkins.scylladb.com/job/scylla-master/job/dtest-daily-release/

you can look there, but some of the failures are not necessarily new.

as for the specific test, those are the only ones I know that mix alternator and sstableloader

**Comment by slivne** [comment] 2022-07-17 07:26
@avelanarius due to duration we run a subset of the tests (only gating) - but we add additional tests over time - whats the status of the fix for this - should we revert the change of the driver ?

**Comment by slivne** [comment] 2022-07-20 11:12
@avelanarius ping

**Comment by avelanarius** [comment] 2022-07-20 12:34
I am working on a fix in sstableloader, so reverting the driver change hopefully won't be necessary.

**Comment by slivne** [comment] 2022-07-25 11:18
@avelanarius was this fixed ?

**Comment by avikivity** [comment] 2022-07-27 18:42
Almost, I forgot to update the submodule.

**Closed** 2022-07-28 02:25 UTC
Labels: bug, test, dtest, sstableloader, master/high

**Comment by avikivity** [comment] 2023-01-02 13:46
Assuing 5.0 uses an old-enough driver so no backport is needed.
