### ISSUE TITLE
std::bad_alloc are thrown when cluster is overloaded

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla#1498] opened 2016-07-25 15:21 UTC
_Installation details_
Scylla version (or git commit hash): 1.2.1
OS (RHEL/CentOS/Ubuntu/AWS AMI): ami-dd46ffca
Cluster: 3 nodes c3.large

Loaded by 4 nodes of c3.xlarge each running

```
cassandra-stress write cl=QUORUM duration=240m -schema 'replication(factor=3)' -port jmx=6868 -mode cql3 native -rate threads=200 limit=5000/s -col 'size=FIXED(10240) n=FIXED(1)' -pop seq=1..100000000 
```

errors in logs

```
 [shard 0] storage_proxy - Failed to apply mutation from 172.30.0.65#0: std::bad_alloc (std::bad_alloc)
```

**Comment by lmr** [comment] 2016-07-25 18:18
@slivne I sent a Pull Request to scylla-cluster-tests that will make the test to return a WARNING instead of a PASS in case we see std::bad_alloc messages on node logs. I wanted to double check with you that this is a direction we want to move towards.

https://github.com/scylladb/scylla-cluster-tests/pull/143

**Comment by slivne** [comment] 2016-07-27 08:29
I commented on the pull request

**Comment by tgrabiec** [comment] 2016-08-09 09:07
Could be duplicate of https://github.com/scylladb/scylla/issues/1395

**Comment by scottsauff** [comment] 2016-08-09 18:55
I'm encountering a similar error when bulk loading into a table. The error happens many hours into the multi-day loading and happens on all nodes eventually.

[shard 2] database - failed to write sstable: std::bad_alloc (std::bad_alloc)

Environment:
3 physical nodes (288 GB RAM, 2x6 cpu) running centos-release-7-2.1511.el7.centos.2.10.x86_64
scylla.x86_64                   1.2.3-20160731.e9b7352.el7.centos

Once the bad_alloc is seen, I see an endless stream of:
[shard 3] compaction - Compaction found an exception when writing sstable /var/lib/scylla/data/ra/getrecentbyemail-e86c7da05bf811e68bcf000000000003/ra-getrecentbyemail-ka-10851-Data.db : st
[shard 3] compaction_manager - compaction failed: read exception: seastar::broken_pipe_exception (Broken pipe), write_exception: std::bad_alloc (std::bad_alloc)

**Comment by avikivity** [comment] 2016-08-09 19:08
@scottsauff are you using wide partitions? what does `nodetool cfstats` say about the maximum compacted partition size?

If so you can try 1.3-rc2, which should fix bad_allocs within wide partition compaction.

288GB RAM -> 12GB/shard.  If it's a wide partition problem, they must be really large, you may have a data  modelling problem.

**Comment by scottsauff** [comment] 2016-08-09 20:07
@avikivity  Here's the info you requested.    I'll try the upgrade, it may take a day or two.  
table 1 - email
Compacted partition maximum bytes: 186,563,160  177M
table 2 - name
Compacted partition maximum bytes: 52,066,354  49M
table 3 - phone
Compacted partition maximum bytes: 2,395,318,855  2.2G
table 4 - ssn
Compacted partition maximum bytes: 155,469,300   148M
table 5 - zip
Compacted partition maximum bytes: 74,975,550   71M

I'm curious about the wide partition problem if that's the case.  I attempted to model this correctly using wide row best practices...    :/

**Comment by scottsauff** [comment] 2016-08-09 20:33
@avikivity   My sys admins need RPMs.  Is the 1.3 RC on your download page the RC 2 you specify above?

**Comment by avikivity** [comment] 2016-08-10 08:40
Those are very wide partitions, esp. table 3.

If there are just a few of them then scylla 1.3 will cope, but if most partitions are so large then read performance will suffer.  You can check by looking at `nodetool cfstats` "mean compacted partition size" ; if it's a few megabytes or less (can even go to tens of megabytes) it's okay, but if it's hundreds of megabytes or more you are not going to get good read performance.

1.3-rc2 RPMs are available on the download page.

**Comment by keef-cognitiv** [comment] 2018-07-14 18:29
fwiw I see the same thing on 2.1.6 - not just under high load but specifically sustained high write-heavy load for many hours.
![screencapture-10-1-2-214-d-b-jn-mdik-scylla-per-server-metrics-2-0-2018-07-14-11_27_50](https://user-images.githubusercontent.com/34460527/42727302-13f563b4-8759-11e8-937b-d2202e4dab24.png)
It started where the write errors spiked, then I restarted the server... that seems to more or less fix it

**Comment by gleb-cloudius** [comment] 2018-07-15 07:43
@keef-cognitiv can you show disk I/O dashboard around the same time? How many CPUs and memory each node has? What CL are you using for writing?

**Comment by gleb-cloudius** [comment] 2018-07-15 08:06
Also can you look at yelow's node (the one you restarted) cpu utilization per shard?

**Comment by keef-cognitiv** [comment] 2018-07-15 17:39
![screencapture-10-1-2-214-d-mpjhamvmk-scylla-per-server-disk-i-o-2-0-2018-07-15-10_18_18](https://user-images.githubusercontent.com/34460527/42736264-88f1ceea-8818-11e8-95a2-cc67bd82c215.png)

![screencapture-10-1-2-214-d-mpjhamvmk-scylla-per-server-disk-i-o-2-0-2018-07-15-10_38_40](https://user-images.githubusercontent.com/34460527/42736411-4f79d1be-881b-11e8-90b4-acbece3bb46f.png)

**Comment by keef-cognitiv** [comment] 2018-07-15 17:57
Oh sorry... the CL was LOCAL_ONE... But there's only one DC/Rack so the LOCAL is just for good measure

**Comment by keef-cognitiv** [comment] 2018-07-15 18:01
And then that same server is getting:
``` [shard 17] seastar_memory - oversized allocation: 1335296 bytes, please report: at   0x556629#012  0x5571c0#012  0x558b34#012  0x558b74#012  0xdbedf6#012  0xd89e62#012  0xdc40ec#012  0xd867d6#012  0xd8a0d2#012  0xdab806#012  0x49f51a#012  0x49f7fc#012  0x4ee6a4#012  0x4f3a4e#012  0x5557fd#012  /lib/x86_64-linux-gnu/libpthread.so.0+0x76b9#012  /lib/x86_64-linux-gnu/libc.so.6+0x10741c```
In the logs then a bunch of semaphore timed out in storage_proxy, which crushes the perf of the whole cluster.

**Comment by keef-cognitiv** [comment] 2018-07-16 05:08
Here's another... this one is a little more obvious as it was using 100% system CPU to do compactions while still getting a bunch of updates.
![screencapture-10-1-2-214-d-mpjhamvmk-scylla-per-server-disk-i-o-2-0-2018-07-15-22_03_46](https://user-images.githubusercontent.com/34460527/42743707-17578c44-887b-11e8-8cd3-1a256e6dfad8.png)

It took a while for the bad_allocs to start under this load but once they do, even after draining the node there's a bunch of bad_alloc errors while trying to run the compaction post-drain. For example
```
Jul 16 05:07:07 ip-10-1-2-59 scylla:  [shard 48] database - failed to write sstable /var/lib/scylla/data/lynx/cuid2iid-7a03e2c084a711e8bf72000000000029/lynx-cuid2iid-ka-71968-Data.db: std::bad_alloc (std::bad_alloc)
Jul 16 05:07:09 ip-10-1-2-59 scylla:  [shard 23] storage_proxy - Exception when communicating with 10.1.2.59: std::bad_alloc
```
And the drain just hangs while these keep happening

**Comment by avikivity** [comment] 2018-07-16 06:56
@keef-cognitiv do you have large blobs in your data model? what sizes? can you post your schema?

**Comment by gleb-cloudius** [comment] 2018-07-16 07:30
Can you upload entire Prometheus db as described in http://docs.scylladb.com/operating-scylla/troubleshooting/report_scylla_problem/#server-metrics-with-prometheus

**Comment by keef-cognitiv** [comment] 2018-07-16 19:10
describe lynx.cuid2iid;

CREATE TABLE lynx.cuid2iid (
    cuid bigint PRIMARY KEY,
    iid set<text>
) WITH bloom_filter_fp_chance = 0.01
    AND caching = {'keys': 'ALL', 'rows_per_partition': 'ALL'}
    AND comment = ''
    AND compaction = {'class': 'SizeTieredCompactionStrategy'}
    AND compression = {'sstable_compression': 'org.apache.cassandra.io.compress.LZ4Compressor'}
    AND crc_check_chance = 1.0
    AND dclocal_read_repair_chance = 0.1
    AND default_time_to_live = 0
    AND gc_grace_seconds = 864000
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair_chance = 0.0
    AND speculative_retry = '99.0PERCENTILE';

The sets are usually pretty small - 5 items or so. There are a few outliers though that'll be up to 30 or 40. Each value in the set is about 30 characters.

I can't upload the prometheus database, unfortunately. It has all of our metrics for our normal business production workloads as well. Not just this scylla cluster. I was able to get the bad allocs to stop happening all all by tuning max-io-requests way down on 2 out of 6 servers. Oddly, it's just on those two. Perhaps it has something to do with non-trivial performance difference between identical instance (i3.16xlarge) types in AWS.

**Comment by avikivity** [comment] 2021-07-01 08:31
Stale, closing. Many bugs were fixed in this area.

**Closed by avikivity** 2021-07-01 08:31 UTC
Labels: bug, large partitions, stability
