### ISSUE TITLE
Performance regression of 2.0.rc0 & 2.0.rc1 comparing to previous releases

### ISSUE THREAD

**Issue by roydahan** [scylladb/scylla#2645] opened 2017-07-27 15:06 UTC
*Installation details*
Scylla version (or git commit hash): e1a3052
Cluster size: 3
OS (RHEL/CentOS/Ubuntu/AWS AMI): AWS AMI (ami-29035f52)

During the week we ran our performance regression suite with 2.0.rc0 and 2.0.rc1.
Starting July 23rd build, we started seeing a severe performance degradation (~43% less ops than 1.7.3 and ~37% less than best result of 2.0.rc0 (July 10th AMI).

At first we believed the degradation is caused by issue #2608, but with last night run with the latest AMI that fixes the issue, results are still the same.

Below are the details of the test and results.
I'll focus here on test_write scenario, but degradation is relevant for test_read and test_mixed scenarios as well.

Prometheus Metrics are available here: https://cloudius-jenkins-test.s3.amazonaws.com/scylla-ami-perf-regression/sub_test=test_write/job-2017-07-27T00.15-f0da7bc.zip

Metrics Snapshot is available here: https://cloudius-jenkins-test.s3.amazonaws.com/scylla-ami-perf-regression/sub_test=test_write/job-2017-07-27T00.15-f0da7bc.png

Results

Scylla Version | versions.scylla-server.commit_id.keyword: Descending | Total op rate (op/s)
-- | -- | --
1.6.0 | 7e1b245 | 69,344
1.6.6 | dd70520 | 72,064
1.7.0 | 25607ab | 66,783.5
1.7.3 | 41b4055 | 70,841
2.0.rc0 | a619b97 | 63,148
2.0.rc0 | 83cc640 | 39,770.333
2.0.rc1 | f5bb363 | 41,340
2.0.rc1 | e1a3052 | 43,877

Test and Setup Details:

 {
     "setup_details": {         
         "cluster_backend": "aws",                                      
         "ami_id_db_scylla": "ami-29035f52",                   
         "n_db_nodes": 3,          
         "instance_type_db": "i2.2xlarge", 
         "instance_type_loader": "c4.large", 
         "n_loaders": 4,
         "n_monitor_nodes": 1,          
     }, 
     "versions": {
         "scylla-jmx": {
             "date": "20170726", 
             "commit_id": "3451d25", 
             "version": "2.0.rc1"
         }, 
         "scylla-tools": {
             "date": "20170726", 
             "commit_id": "8e1ef86", 
             "version": "core-2.0.rc1"
         }, 
         "scylla-server": {
             "date": "20170726", 
             "commit_id": "e1a3052", 
             "version": "2.0.rc1"
         }
     }, 
     "test_details": {         
         "test_duration": 70, 
         "job_url": "http://jenkins.cloudius-systems.com:8080/job/scylla-ami-perf-regression/sub_test=test_write/93/", 
         "grafana_snapshot": "https://cloudius-jenkins-test.s3.amazonaws.com/scylla-ami-perf-regression/sub_test=test_write/job-2017-07-27T00.15-f0da7bc.png", 
         "prometheus_report": "https://cloudius-jenkins-test.s3.amazonaws.com/scylla-ami-perf-regression/sub_test=test_write/job-2017-07-27T00.15-f0da7bc.zip", 
         "sct_git_commit": "697384bcbc8b5514b31c7c614835282fb4394a58", 
         "test_name": "performance_regression_test.py:PerformanceRegressionTest.test_write",                   
         "cassandra-stress": {
             "errors": "ignore", 
             "cl": "QUORUM", 
             "rate threads": "100", 
             "pop": "seq=1..10000000", 
             "command": "write", 
             "mode": "cql3", 
             "no-warmup": true, 
             "port": "jmx=6868", 
             "schema": "'replication(factor=3)'"
         }
     "results": {
         "stats_average": {
             "latency 99th percentile": 146.4, 
             "latency max": 328.8, 
             "keyspace_idx": 1.0, 
             "latency median": 2.0, 
             "stdev gc time(ms)": 0.0, 
             "op rate": 5211.0, 
             "Total partitions": 18759532.8, 
             "partition rate": 5211.0, 
             "latency 99.9th percentile": 181.6, 
             "row rate": 5211.0, 
             "total gc count": 0.0, 
             "loader_idx": 1.5, 
             "latency mean": 19.2, 
             "total gc mb": 0.0, 
             "Total errors": 0.0, 
             "Total operation time": "00:59:59", 
             "latency 95th percentile": 108.5, 
             "cpu_idx": 0.5, 
             "total gc time (s)": 0.0, 
             "avg gc time(ms)": null
         }, 
         "stats": [
             {
                 "latency max": "450.3", 
                 "keyspace_idx": "1", 
                 "latency median": "2.2", 
                 "stdev gc time(ms)": "0", 
                 "op rate": "5180", 
                 "Total errors": "0", 
                 "total gc count": "0", 
                 "partition rate": "5180", 
                 "latency 99.9th percentile": "180.6", 
                 "row rate": "5180", 
                 "loader_idx": "0", 
                 "total gc time (s)": "0", 
                 "latency mean": "19.3", 
                 "total gc mb": "0", 
                 "Total partitions": "18646953", 
                 "Total operation time": "00:59:59", 
                 "latency 95th percentile": "108.4", 
                 "cpu_idx": "0", 
                 "latency 99th percentile": "146.4", 
                 "avg gc time(ms)": "NaN"
             }, 
             {
                 "latency max": "315.0", 
                 "keyspace_idx": "1", 
                 "latency median": "2.2", 
                 "stdev gc time(ms)": "0", 
                 "op rate": "5357", 
                 "Total errors": "0", 
                 "total gc count": "0", 
                 "partition rate": "5357", 
                 "latency 99.9th percentile": "182.0", 
                 "row rate": "5357", 
                 "loader_idx": "0", 
                 "total gc time (s)": "0", 
                 "latency mean": "18.7", 
                 "total gc mb": "0", 
                 "Total partitions": "19283538", 
                 "Total operation time": "01:00:00", 
                 "latency 95th percentile": "101.9", 
                 "cpu_idx": "1", 
                 "latency 99th percentile": "145.8", 
                 "avg gc time(ms)": "NaN"
             }, 
             {
                 "latency max": "310.3", 
                 "keyspace_idx": "1", 
                 "latency median": "2.0", 
                 "stdev gc time(ms)": "0", 
                 "op rate": "5111", 
                 "Total errors": "0", 
                 "total gc count": "0", 
                 "partition rate": "5111", 
                 "latency 99.9th percentile": "177.5", 
                 "row rate": "5111", 
                 "loader_idx": "1", 
                 "total gc time (s)": "0", 
                 "latency mean": "19.5", 
                 "total gc mb": "0", 
                 "Total partitions": "18401283", 
                 "Total operation time": "01:00:00", 
                 "latency 95th percentile": "110.6", 
                 "cpu_idx": "0", 
                 "latency 99th percentile": "145.7", 
                 "avg gc time(ms)": "NaN"
             }, 
             {
                 "latency max": "312.6", 
                 "keyspace_idx": "1", 
                 "latency median": "1.8", 
                 "stdev gc time(ms)": "0", 
                 "op rate": "5147", 
                 "Total errors": "0", 
                 "total gc count": "0", 
                 "partition rate": "5147", 
                 "latency 99.9th percentile": "180.7", 
                 "row rate": "5147", 
                 "loader_idx": "1", 
                 "total gc time (s)": "0", 
                 "latency mean": "19.4", 
                 "total gc mb": "0", 
                 "Total partitions": "18527922", 
                 "Total operation time": "01:00:00", 
                 "latency 95th percentile": "108.5", 
                 "cpu_idx": "1", 
                 "latency 99th percentile": "147.3", 
                 "avg gc time(ms)": "NaN"
             }, 
             {
                 "latency max": "309.3", 
                 "keyspace_idx": "1", 
                 "latency median": "1.8", 
                 "stdev gc time(ms)": "0", 
                 "op rate": "5119", 
                 "Total errors": "0", 
                 "total gc count": "0", 
                 "partition rate": "5119", 
                 "latency 99.9th percentile": "185.6", 
                 "row rate": "5119", 
                 "loader_idx": "2", 
                 "total gc time (s)": "0", 
                 "latency mean": "19.5", 
                 "total gc mb": "0", 
                 "Total partitions": "18429840", 
                 "Total operation time": "01:00:00", 
                 "latency 95th percentile": "111.3", 
                 "cpu_idx": "0", 
                 "latency 99th percentile": "148.1", 
                 "avg gc time(ms)": "NaN"
             }, 
             {
                 "latency max": "310.3", 
                 "keyspace_idx": "1", 
                 "latency median": "1.7", 
                 "stdev gc time(ms)": "0", 
                 "op rate": "5181", 
                 "Total errors": "0", 
                 "total gc count": "0", 
                 "partition rate": "5181", 
                 "latency 99.9th percentile": "180.8", 
                 "row rate": "5181", 
                 "loader_idx": "2", 
                 "total gc time (s)": "0", 
                 "latency mean": "19.3", 
                 "total gc mb": "0", 
                 "Total partitions": "18652327", 
                 "Total operation time": "01:00:00", 
                 "latency 95th percentile": "110.6", 
                 "cpu_idx": "1", 
                 "latency 99th percentile": "146.2", 
                 "avg gc time(ms)": "NaN"
             }, 
             {
                 "latency max": "311.8", 
                 "keyspace_idx": "1", 
                 "latency median": "2.1", 
                 "stdev gc time(ms)": "0", 
                 "op rate": "5172", 
                 "Total errors": "0", 
                 "total gc count": "0", 
                 "partition rate": "5172", 
                 "latency 99.9th percentile": "180.5", 
                 "row rate": "5172", 
                 "loader_idx": "3", 
                 "total gc time (s)": "0", 
                 "latency mean": "19.3", 
                 "total gc mb": "0", 
                 "Total partitions": "18619813", 
                 "Total operation time": "01:00:00", 
                 "latency 95th percentile": "110.0", 
                 "cpu_idx": "0", 
                 "latency 99th percentile": "146.1", 
                 "avg gc time(ms)": "NaN"
             }, 
             {
                 "latency max": "311.1", 
                 "keyspace_idx": "1", 
                 "latency median": "2.0", 
                 "stdev gc time(ms)": "0", 
                 "op rate": "5421", 
                 "Total errors": "0", 
                 "total gc count": "0", 
                 "partition rate": "5421", 
                 "latency 99.9th percentile": "185.2", 
                 "row rate": "5421", 
                 "loader_idx": "3", 
                 "total gc time (s)": "0", 
                 "latency mean": "18.4", 
                 "total gc mb": "0", 
                 "Total partitions": "19514586", 
                 "Total operation time": "00:59:59", 
                 "latency 95th percentile": "106.4", 
                 "cpu_idx": "1", 
                 "latency 99th percentile": "145.6", 
                 "avg gc time(ms)": "NaN"
             }
         ], 
         "stats_total": {
             "op rate": 41688.0, 
             "Total errors": 0.0
         }
     },      
     }
 }

**Comment by roydahan** [comment] 2017-07-27 15:09
Scylla Version | Latency 99th (ms) | Latency mean (ms)
-- | -- | --
1.6.0 | 50.2 | 11.5
1.6.6 | 53.3 | 11.1
1.7.0 | 76 | 12
1.7.3 | 61.8 | 11.3
2.0.rc0 | 135.75 | 18.25
2.0.rc1 | 143.333 | 18.633

**Comment by slivne** [comment] 2017-07-31 23:27
unfortunately it does not seem to be a single source of degradation - there are multiple contributors.

using a single instance i2.2x

single loader c3.8x

```
cassandra-stress write -pop seq=1..10000000 -node 172.30.0.228 -rate threads=1000
```
 commit | total-ops (multiple runs) | comments  
-- | -- | --
 83cc640 | 74885,75707,75871| (ami-0c38281a) 
 2f06c54 | 81083,81082,81574 | 

using a cluster of 3 servers i2.2x

load c3.8x
```
cassandra-stress write CL=QUORUM -pop seq=1..10000000 -node 172.30.0.228 -rate threads=1000
```

 commit | total-ops | comments  
-- | -- | --
 83cc640 | 289067,286932,298265 | (ami-0c38281a) 
 2f06c54 | 339213,338914,340385 | 

So that acounts to ~10% - ~15% of degradation - the others on a single server were not as deterministic - so I'll need to chekc them on the 3 node cluster.
 
@duarten / @pdziepak we can start from this,

**Comment by slivne** [comment] 2017-08-01 14:30
so after changing the load to more resembles QA loads the task quota commit seems to be at fault

commit | task-quota-ms | total-ops
-- | -- | --
a371b8a | not set | 51966, 51676, 54162
a371b8a | set to 2.0 | 98863, 104052, 109557

reproducer 
cluster 3 nodes on i2.2x
single loader c3.8x

```
 cassandra-stress write CL=QUORUM -pop seq=1..10000000 -node 172.30.0.228 -rate threads=800 -schema "replication(factor=3)"
```

**Comment by glommer** [comment] 2017-08-01 16:48
It seems I can reproduce with a single node - which is even simpler. I am on it.

**Comment by glommer** [comment] 2017-08-01 16:53
server is still i2.2xlarge, but just a single node.

```
[centos@ip-172-30-0-173 ~]$ cat 2ms.txt 
Results:
op rate                   : 122711 [WRITE:122711]
partition rate            : 122711 [WRITE:122711]
row rate                  : 122711 [WRITE:122711]
latency mean              : 6.5 [WRITE:6.5]
latency median            : 5.2 [WRITE:5.2]
latency 95th percentile   : 16.0 [WRITE:16.0]
latency 99th percentile   : 22.0 [WRITE:22.0]
latency 99.9th percentile : 44.6 [WRITE:44.6]
latency max               : 126.9 [WRITE:126.9]
Total partitions          : 10000000 [WRITE:10000000]
Total errors              : 0 [WRITE:0]
total gc count            : 0
total gc mb               : 0
total gc time (s)         : 0
avg gc time(ms)           : NaN
stdev gc time(ms)         : 0
Total operation time      : 00:01:21
END

[centos@ip-172-30-0-173 ~]$ cat 1ms.txt 
Results:
op rate                   : 119706 [WRITE:119706]
partition rate            : 119706 [WRITE:119706]
row rate                  : 119706 [WRITE:119706]
latency mean              : 6.7 [WRITE:6.7]
latency median            : 5.5 [WRITE:5.5]
latency 95th percentile   : 11.1 [WRITE:11.1]
latency 99th percentile   : 18.0 [WRITE:18.0]
latency 99.9th percentile : 45.1 [WRITE:45.1]
latency max               : 138.3 [WRITE:138.3]
Total partitions          : 10000000 [WRITE:10000000]
Total errors              : 0 [WRITE:0]
total gc count            : 0
total gc mb               : 0
total gc time (s)         : 0
avg gc time(ms)           : NaN
stdev gc time(ms)         : 0
Total operation time      : 00:01:23
END

[centos@ip-172-30-0-173 ~]$ cat 500us.txt 
Results:
op rate                   : 93398 [WRITE:93398]
partition rate            : 93398 [WRITE:93398]
row rate                  : 93398 [WRITE:93398]
latency mean              : 8.6 [WRITE:8.6]
latency median            : 5.0 [WRITE:5.0]
latency 95th percentile   : 29.6 [WRITE:29.6]
latency 99th percentile   : 71.1 [WRITE:71.1]
latency 99.9th percentile : 91.4 [WRITE:91.4]
latency max               : 158.7 [WRITE:158.7]
Total partitions          : 10000000 [WRITE:10000000]
Total errors              : 0 [WRITE:0]
total gc count            : 0
total gc mb               : 0
total gc time (s)         : 0
avg gc time(ms)           : NaN
stdev gc time(ms)         : 0
Total operation time      : 00:01:47
END
```

**Comment by glommer** [comment] 2017-08-01 18:10
@avikivity I have patched seastar to receive ticks at every 0.5ms , but only set `_local_need_preempt` to true every 4 ticks. Performance went back to `115074` writes/sec.

So it seems to me that both waking up the threads and breaking the run_tasks loop are detrimental to performance here. But the latter is a lot more.

**Comment by glommer** [comment] 2017-08-01 18:21
i2.2xlarge uses mq mode.

I have moved it to SQ and tested again - isolating CPU0.

results are:

2ms : `119329` writes/sec
500us: `117672` writes/sec

So there is a small degradation - but in line with what I measured before, and a fair price to pay for less nosedives in the graph.

Real problem here seems to be bad interaction between the lower task quota and MQ mode for 2xlarge.

To be clear, i2.2xlarge doesn't have nr_queues = nr_shards. See #2611 please: I really don't think we should run MQ unless nr_queues = nr_shards.

I will test an i3 that has nr_queues = nr_shards now to see how we fare there.

**Comment by glommer** [comment] 2017-08-01 18:25
BTW, i3.16xlarge runs on SQ, and that explains why I saw no regression there.

**Comment by glommer** [comment] 2017-08-01 18:38
Results for i3.2xlarge (mq mode, but nr_shards = nr_queues)

0.5ms: `171381` writes/sec
2ms: `173173` writes/sec

**Comment by avikivity** [comment] 2017-08-02 15:02
I don't understand how MQ interacts with task_quota.

**Comment by glommer** [comment] 2017-08-02 17:31
@avikivity I don't have a good theory either, but the results all point in this direction.

Note: It's not MQ. It's MQ when nr_shards != nr_queues

**Comment by glommer** [comment] 2017-08-02 17:44
@avikivity could it be that we'll poll more often, therefore get packets to process more often - which leads to even higher sysrq time in the poor CPUs that are handling interrupts?

The other shards will be fine but will be slowed down to the speed of the shards with higher sysirq

**Comment by vladzcloudius** [comment] 2017-08-08 15:25
@avikivity 

So, for `i2.2xlarge` we have data points for:
* SQ: 
  * 0.5ms
  * 2ms 
* MQ: 
  * 0.5ms 
  * 1ms 
  * 2ms.

For i3.2xlarge: 
* MQ 
  * 0.5ms 
  * 2ms

Which data points do we miss in order to get to the decision? `i3.2xlarge` + SQ + {0.5ms, 2ms}?

**Comment by avikivity** [comment] 2017-08-08 17:17
Can you also summarize the results for these data points?

i3.2xlarge + SQ  + 0.5/2.0 will help

Is the behaviour (for i2) a regression?

**Comment by vladzcloudius** [comment] 2017-08-08 19:20
c-s write test as above on a single node`cluster:

For i2.2xlarge:
* SQ:
  * 2ms: 119329 writes/sec
  * 0.5ms: 117672 writes/sec (-1.3%)
* MQ:
  * 2ms: 122711 writes/sec
  * 1ms: 119706 writes/sec
  * 0.5ms: 93398 writes/sec (-23%)

For i3.2xlarge:
* MQ:
  * 2ms: 173173 writes/sec 
  * 0.5ms: 171381 writes/sec (-1%)

If the i2.2xlarge is a regression? I have no idea - I never tested different task quota values before. I also have no writes/sec numbers for SQ/MQ configurations with the default task quota for i2.2xlarge for different versions as well.
You may see, that with the default 2ms value MQ outperforms the SQ in terms of throughput. However the difference is rather small.

**Comment by avikivity** [comment] 2017-08-09 09:18
All right, let's go to MQ. We should retest when we consolidate timer threads.

**Comment by vladzcloudius** [comment] 2017-08-09 14:07
@avikivity What do you mean "let's go to MQ"? The numbers above show that SQ is a lot more stable and predictable configuration when the number of HW queues is not equal to the number of shards...

**Comment by slivne** [comment] 2017-08-10 10:21
@vladzcloudius after discussing it with avi - we will go with the proposed solution that you and glauber had:

* MQ will be enabled when the # of queues is equal to # of shards
* SQ will be used every where else

**one item that is left to clarify is when do we force using a dedicated HT (e.g. a 4 hyperthread system to we use one hyperthread for interrupts only ?) **

**Comment by glommer** [comment] 2017-08-10 11:32
On Aug 10, 2017 6:21 AM, "Shlomi Livne" <notifications@github.com> wrote:

@vladzcloudius <https://github.com/vladzcloudius> after discussing it with
avi - we will go with the proposed solution that you and glauber had:

   - MQ will be enabled when the # of queues is equal to # of shards


Even then we need a way to override disable it for cases like the optane
box. But the disable part can be deferred to 2.1.


   - SQ will be used every where else

**one item that is left to clarify is when do we force using a dedicated HT
(e.g. a 4 hyperthread system to we use one hyperthread for interrupts only
?) **

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/scylladb/scylla/issues/2645#issuecomment-321512585>,
or mute
the thread

**Comment by vladzcloudius** [comment] 2017-08-10 14:01
@slivne The SQ logic is described on #2611:

*Proposal*
Implement the following heuristics:

    1) Don't allow SQ mode if it takes less than 25% of the compute power.
    2) Prefer SQ-split, when (1) allows it.
    3) Use MQ only when number of queues == number of CPUs or when (1) doesn't allow SQ.

**Comment by slivne** [comment] 2017-08-19 20:16
based on "[dev-int] Performance regression test results - 2.0.rc2" we can close this

**Closed by slivne** 2017-08-19 20:16 UTC
Labels: bug, high, performance

**Comment by vladzcloudius** [comment] 2017-08-21 13:46
@slivne The i3.2xlarge should be retested since it was configured differently than we agreed upon due to a bug in a `perftune.py` script.
