### ISSUE TITLE
filesystem_error: No such file or directory during leveled compaction

### ISSUE THREAD

**Issue by bentsi** [scylladb/scylla#4941] opened 2019-09-02 10:08 UTC
*Installation details*
Scylla version (or git commit hash): 3.0.10-0.20190815.b3bfd8c08
Cluster size: 4
OS (RHEL/CentOS/Ubuntu/AWS AMI): ami-0b88175d56d413224

- During decommission nemesis on another node (172.30.0.91)
- mc format enabled

```
Sep 02 01:28:30 ip-172-30-0-33.ec2.internal scylla[2311]:  [shard 1] LeveledManifest - Adding high-level (L3) /var/lib/scylla/data/keyspace1/standard1-0b49fc20ccd111e99a8b000000000003/mc-100591-big-Data.db to candidates
Sep 02 01:28:31 ip-172-30-0-33.ec2.internal scylla[2311]:  [shard 1] LeveledManifest - Adding high-level (L3) /var/lib/scylla/data/keyspace1/standard1-0b49fc20ccd111e99a8b000000000003/mc-100591-big-Data.db to candidates
Sep 02 01:28:31 ip-172-30-0-33.ec2.internal scylla[2311]:  [shard 1] LeveledManifest - Adding high-level (L3) /var/lib/scylla/data/keyspace1/standard1-0b49fc20ccd111e99a8b000000000003/mc-100591-big-Data.db to candidates
Sep 02 01:28:31 ip-172-30-0-33.ec2.internal scylla[2311]:  [shard 1] LeveledManifest - Adding high-level (L3) /var/lib/scylla/data/keyspace1/standard1-0b49fc20ccd111e99a8b000000000003/mc-100591-big-Data.db to candidates
Sep 02 01:28:31 ip-172-30-0-33.ec2.internal scylla[2311]:  [shard 1] LeveledManifest - Adding high-level (L3) /var/lib/scylla/data/keyspace1/standard1-0b49fc20ccd111e99a8b000000000003/mc-100591-big-Data.db to candidates
Sep 02 01:28:31 ip-172-30-0-33.ec2.internal scylla[2311]:  [shard 1] LeveledManifest - Adding high-level (L3) /var/lib/scylla/data/keyspace1/standard1-0b49fc20ccd111e99a8b000000000003/mc-100591-big-Data.db to candidates
Sep 02 01:28:31 ip-172-30-0-33.ec2.internal scylla[2311]:  [shard 1] LeveledManifest - Adding high-level (L3) /var/lib/scylla/data/keyspace1/standard1-0b49fc20ccd111e99a8b000000000003/mc-100591-big-Data.db to candidates
Sep 02 01:28:31 ip-172-30-0-33.ec2.internal scylla[2311]:  [shard 1] LeveledManifest - Adding high-level (L3) /var/lib/scylla/data/keyspace1/standard1-0b49fc20ccd111e99a8b000000000003/mc-100591-big-Data.db to candidates
Sep 02 01:28:31 ip-172-30-0-33.ec2.internal scylla[2311]:  [shard 1] compaction - Compacting [/var/lib/scylla/data/keyspace1/standard1-0b49fc20ccd111e99a8b000000000003/mc-109719-big-Data.db:level=2, ]
Sep 02 01:28:31 ip-172-30-0-33.ec2.internal sudo[71375]:   centos : TTY=unknown ; PWD=/home/centos ; USER=root ; COMMAND=/bin/coredumpctl --no-pager --no-legend
Sep 02 01:28:31 ip-172-30-0-33.ec2.internal sudo[71375]: pam_unix(sudo:session): session opened for user root by (uid=0)
Sep 02 01:28:31 ip-172-30-0-33.ec2.internal sudo[71375]: pam_unix(sudo:session): session closed for user root
Sep 02 01:28:31 ip-172-30-0-33.ec2.internal scylla[2311]:  [shard 2] seastar - Exceptional future ignored: std::experimental::filesystem::v1::filesystem_error (error system:2, No such file or directory), backtrace:   0x7d0358
                                                            0x5a5744
                                                            0x613992
                                                            0x5a403e
                                                            0x5a4201
                                                            0x6728a7
                                                            0x67705a
                                                            0x75a0bd
                                                            /lib64/libpthread.so.0+0x7dd4
                                                            /lib64/libc.so.6+0xfe02c
Sep 02 01:28:32 ip-172-30-0-33.ec2.internal scylla[2311]:  [shard 7] LeveledManifest - Adding high-level (L3) /var/lib/scylla/data/keyspace1/standard1-0b49fc20ccd111e99a8b000000000003/mc-104559-big-Data.db to candidates
Sep 02 01:28:32 ip-172-30-0-33.ec2.internal scylla[2311]:  [shard 7] LeveledManifest - Adding high-level (L3) /var/lib/scylla/data/keyspace1/standard1-0b49fc20ccd111e99a8b000000000003/mc-104559-big-Data.db to candidates
Sep 02 01:28:32 ip-172-30-0-33.ec2.internal scylla[2311]:  [shard 7] LeveledManifest - Adding high-level (L3) /var/lib/scylla/data/keyspace1/standard1-0b49fc20ccd111e99a8b000000000003/mc-104559-big-Data.db to candidates
Sep 02 01:28:32 ip-172-30-0-33.ec2.internal scylla[2311]:  [shard 7] LeveledManifest - Adding high-level (L3) /var/lib/scylla/data/keyspace1/standard1-0b49fc20ccd111e99a8b000000000003/mc-104559-big-Data.db to candidates
Sep 02 01:28:32 ip-172-30-0-33.ec2.internal scylla[2311]:  [shard 7] LeveledManifest - Adding high-level (L3) /var/lib/scylla/data/keyspace1/standard1-0b49fc20ccd111e99a8b000000000003/mc-104559-big-Data.db to candidates
Sep 02 01:28:32 ip-172-30-0-33.ec2.internal scylla[2311]:  [shard 7] LeveledManifest - Adding high-level (L3) /var/lib/scylla/data/keyspace1/standard1-0b49fc20ccd111e99a8b000000000003/mc-104559-big-Data.db to candidates
Sep 02 01:28:32 ip-172-30-0-33.ec2.internal scylla[2311]:  [shard 7] LeveledManifest - Adding high-level (L3) /var/lib/scylla/data/keyspace1/standard1-0b49fc20ccd111e99a8b000000000003/mc-104559-big-Data.db to candidates
```
translated backtrace
```
backtrace<seastar::current_backtrace()::<lambda(seastar::frame)> > at /usr/src/debug/scylla-3.0.10/seastar/util/backtrace.hh:56
 (inlined by) seastar::current_backtrace() at /usr/src/debug/scylla-3.0.10/seastar/util/backtrace.cc:84
seastar::report_failed_future(std::__exception_ptr::exception_ptr) at /usr/src/debug/scylla-3.0.10/seastar/core/reactor.cc:4566
seastar::promise<>::abandoned() at /usr/src/debug/scylla-3.0.10/seastar/core/future.hh:1270
 (inlined by) seastar::promise<>::~promise() at /usr/src/debug/scylla-3.0.10/seastar/core/future.hh:459
 (inlined by) ~<lambda> at /usr/src/debug/scylla-3.0.10/seastar/core/future.hh:959
 (inlined by) ~continuation at /usr/src/debug/scylla-3.0.10/seastar/core/future.hh:410
 (inlined by) ~continuation at /usr/src/debug/scylla-3.0.10/seastar/core/future.hh:410
 (inlined by) run_and_dispose at /usr/src/debug/scylla-3.0.10/seastar/core/future.hh:415
seastar::reactor::run_tasks(seastar::reactor::task_queue&) at /usr/src/debug/scylla-3.0.10/seastar/core/reactor.cc:2701
seastar::reactor::run_some_tasks() at /usr/src/debug/scylla-3.0.10/seastar/core/reactor.cc:3124
seastar::reactor::run_some_tasks() at /usr/src/debug/scylla-3.0.10/seastar/util/log.hh:313
 (inlined by) seastar::reactor::run() at /usr/src/debug/scylla-3.0.10/seastar/core/reactor.cc:3271
operator() at /usr/src/debug/scylla-3.0.10/seastar/core/reactor.cc:4340
std::function<void ()>::operator()() const at /opt/scylladb/include/c++/7/bits/std_function.h:706
 (inlined by) seastar::posix_thread::start_routine(void*) at /usr/src/debug/scylla-3.0.10/seastar/core/posix.cc:52
?? ??:0
?? ??:0
```

Tens of reactor stalls happened before:
```
2019-09-02T00:45:15+00:00  ip-172-30-0-33 !INFO    | scylla: Reactor stalled for 1000 ms on shard 0.

0x00000000006ab5a2
0x00000000005c2c8c
0x00000000005c3146
/lib64/libpthread.so.0+0x000000000000f5cf
0x00000000014d2f30
0x00000000014d374a
0x00000000014d5746
0x00000000014dcfe5
0x00000000014df676
0x00000000014dfbe1
0x00000000010dace5
0x000000000383ed25
0x00000000005a403e
0x00000000005a4201
0x00000000006728a7
0x00000000007b0603
0x0000000000537548
/lib64/libc.so.6+0x0000000000022494
0x000000000059df3d

```
translate reactor stall backtrace
```
void seastar::backtrace<seastar::backtrace_buffer::append_backtrace()::{lambda(seastar::frame)#1}>(seastar::backtrace_buffer::append_backtrace()::{lambda(seastar::frame)#1}&&) at /usr/src/debug/scylla-3.0.10/seastar/util/backtrace.hh:56
seastar::backtrace_buffer::append_backtrace() at /usr/src/debug/scylla-3.0.10/seastar/core/reactor.cc:410
 (inlined by) print_with_backtrace at /usr/src/debug/scylla-3.0.10/seastar/core/reactor.cc:431
seastar::reactor::block_notifier(int) at /usr/src/debug/scylla-3.0.10/seastar/core/reactor.cc:755
?? ??:0
boost::intrusive::rbtree_algorithms<boost::intrusive::rbtree_node_traits<void*, false> >::rebalance_after_erasure_restore_invariants(boost::intrusive::rbtree_node<void*>* const&, boost::intrusive::rbtree_node<void*>*, boost::intrusive::rbtree_node<void*>*) at /opt/scylladb/include/boost/intrusive/rbtree_algorithms.hpp:485
 (inlined by) boost::intrusive::rbtree_algorithms<boost::intrusive::rbtree_node_traits<void*, false> >::rebalance_after_erasure(boost::intrusive::rbtree_node<void*>* const&, boost::intrusive::rbtree_node<void*>* const&, boost::intrusive::data_for_rebalance_t<boost::intrusive::rbtree_node<void*>*> const&) at /opt/scylladb/include/boost/intrusive/rbtree_algorithms.hpp:460
 (inlined by) boost::intrusive::rbtree_algorithms<boost::intrusive::rbtree_node_traits<void*, false> >::erase(boost::intrusive::rbtree_node<void*>* const&, boost::intrusive::rbtree_node<void*>* const&) at /opt/scylladb/include/boost/intrusive/rbtree_algorithms.hpp:287
 (inlined by) boost::intrusive::bstree_impl<boost::intrusive::mhtraits<cache_entry, boost::intrusive::set_member_hook<boost::intrusive::link_mode<(boost::intrusive::link_mode_type)2>, void, void, void>, &cache_entry::_cache_link>, void, cache_entry::compare, unsigned long, false, (boost::intrusive::algo_types)5, void>::erase(boost::intrusive::tree_iterator<boost::intrusive::mhtraits<cache_entry, boost::intrusive::set_member_hook<boost::intrusive::link_mode<(boost::intrusive::link_mode_type)2>, void, void, void>, &cache_entry::_cache_link>, true>) at /opt/scylladb/include/boost/intrusive/bstree.hpp:1418
 (inlined by) erase_and_dispose<row_cache::invalidate_unwrapped(const partition_range&)::<lambda()>::<lambda(auto:110&&)> > at /opt/scylladb/include/boost/intrusive/bstree.hpp:1491
 (inlined by) private_erase<row_cache::invalidate_unwrapped(const partition_range&)::<lambda()>::<lambda(auto:110&&)> > at /opt/scylladb/include/boost/intrusive/bstree.hpp:2103
 (inlined by) erase_and_dispose<row_cache::invalidate_unwrapped(const partition_range&)::<lambda()>::<lambda(auto:110&&)> > at /opt/scylladb/include/boost/intrusive/bstree.hpp:1532
 (inlined by) operator() at /usr/src/debug/scylla-3.0.10/row_cache.cc:1154
 (inlined by) with_allocator<row_cache::invalidate_unwrapped(const partition_range&)::<lambda()> > at /usr/src/debug/scylla-3.0.10/utils/allocation_strategy.hh:307
 (inlined by) row_cache::invalidate_unwrapped(nonwrapping_range<dht::ring_position> const&) at /usr/src/debug/scylla-3.0.10/row_cache.cc:1149
operator() at /usr/src/debug/scylla-3.0.10/row_cache.cc:1131
 (inlined by) with_linearized_managed_bytes<row_cache::invalidate(row_cache::external_updater, dht::partition_range_vector&&)::<lambda()>::<lambda()> > at /usr/src/debug/scylla-3.0.10/utils/managed_bytes.hh:424
 (inlined by) operator() at /usr/src/debug/scylla-3.0.10/row_cache.cc:1129
 (inlined by) _M_invoke at /opt/scylladb/include/c++/7/bits/std_function.h:302
std::function<seastar::future<> ()>::operator()() const at /opt/scylladb/include/c++/7/bits/std_function.h:706
 (inlined by) operator() at /usr/src/debug/scylla-3.0.10/row_cache.cc:1295
 (inlined by) apply<row_cache::do_update(row_cache::external_updater, row_cache::internal_updater)::<lambda(auto:111)> mutable [with auto:111 = seastar::semaphore_units<>]::<lambda()> > at /usr/src/debug/scylla-3.0.10/seastar/core/future.hh:1399
 (inlined by) futurize_apply<row_cache::do_update(row_cache::external_updater, row_cache::internal_updater)::<lambda(auto:111)> mutable [with auto:111 = seastar::semaphore_units<>]::<lambda()> > at /usr/src/debug/scylla-3.0.10/seastar/core/future.hh:1471
 (inlined by) operator()<seastar::semaphore_units<> > at /usr/src/debug/scylla-3.0.10/row_cache.cc:1301
 (inlined by) apply at /usr/src/debug/scylla-3.0.10/seastar/core/apply.hh:35
 (inlined by) apply<row_cache::do_update(row_cache::external_updater, row_cache::internal_updater)::<lambda(auto:111)>, seastar::semaphore_units<seastar::semaphore_default_exception_factory, std::chrono::_V2::steady_clock> > at /usr/src/debug/scylla-3.0.10/seastar/core/apply.hh:43
 (inlined by) apply<row_cache::do_update(row_cache::external_updater, row_cache::internal_updater)::<lambda(auto:111)>, seastar::semaphore_units<seastar::semaphore_default_exception_factory, std::chrono::_V2::steady_clock> > at /usr/src/debug/scylla-3.0.10/seastar/core/future.hh:1389
then<row_cache::do_update(row_cache::external_updater, row_cache::internal_updater)::<lambda(auto:111)> > at /usr/src/debug/scylla-3.0.10/seastar/core/future.hh:952
 (inlined by) row_cache::do_update(seastar::noncopyable_function<void ()>, std::function<seastar::future<> ()>) at /usr/src/debug/scylla-3.0.10/row_cache.cc:1302
row_cache::invalidate(seastar::noncopyable_function<void ()>, std::vector<nonwrapping_range<dht::ring_position>, std::allocator<nonwrapping_range<dht::ring_position> > >&&) at /usr/src/debug/scylla-3.0.10/row_cache.cc:1136
row_cache::invalidate(seastar::noncopyable_function<void ()>, nonwrapping_range<dht::ring_position> const&) at /usr/src/debug/scylla-3.0.10/row_cache.cc:1123
table::add_sstable_and_update_cache(seastar::lw_shared_ptr<sstables::sstable>) at /usr/src/debug/scylla-3.0.10/database.cc:859
operator() at /usr/src/debug/scylla-3.0.10/streaming/stream_session.cc:283
 (inlined by) apply at /usr/src/debug/scylla-3.0.10/seastar/core/apply.hh:35
 (inlined by) apply<streaming::stream_session::init_messaging_service_handler()::<lambda(const seastar::rpc::client_info&, streaming::stream_session::UUID, streaming::stream_session::UUID, streaming::stream_session::UUID, uint64_t, seastar::rpc::optional<streaming::stream_reason>, seastar::rpc::source<frozen_mutation_fragment, seastar::rpc::optional<streaming::stream_mutation_fragments_cmd> >)>::<lambda()> mutable::<lambda(schema_ptr)> mutable::<lambda(flat_mutation_reader)>::<lambda(bool)> mutable::<lambda()> > at /usr/src/debug/scylla-3.0.10/seastar/core/apply.hh:43
 (inlined by) apply<streaming::stream_session::init_messaging_service_handler()::<lambda(const seastar::rpc::client_info&, streaming::stream_session::UUID, streaming::stream_session::UUID, streaming::stream_session::UUID, uint64_t, seastar::rpc::optional<streaming::stream_reason>, seastar::rpc::source<frozen_mutation_fragment, seastar::rpc::optional<streaming::stream_mutation_fragments_cmd> >)>::<lambda()> mutable::<lambda(schema_ptr)> mutable::<lambda(flat_mutation_reader)>::<lambda(bool)> mutable::<lambda()> > at /usr/src/debug/scylla-3.0.10/seastar/core/future.hh:1389
 (inlined by) operator()<seastar::future_state<> > at /usr/src/debug/scylla-3.0.10/seastar/core/future.hh:963
 (inlined by) run_and_dispose at /usr/src/debug/scylla-3.0.10/seastar/core/future.hh:414
seastar::reactor::run_tasks(seastar::reactor::task_queue&) at /usr/src/debug/scylla-3.0.10/seastar/core/reactor.cc:2701
seastar::reactor::run_some_tasks() at /usr/src/debug/scylla-3.0.10/seastar/core/reactor.cc:3124
seastar::reactor::run_some_tasks() at /usr/src/debug/scylla-3.0.10/seastar/util/log.hh:313
 (inlined by) seastar::reactor::run() at /usr/src/debug/scylla-3.0.10/seastar/core/reactor.cc:3271
seastar::app_template::run_deprecated(int, char**, std::function<void ()>&&) at /usr/src/debug/scylla-3.0.10/seastar/core/app-template.cc:185
main at /usr/src/debug/scylla-3.0.10/main.cc:873
?? ??:0
?? ??:0

```

job [url](https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/longevity-200gb-48h-3.0.10-test/3/consoleFull)

**Comment by slivne** [comment] 2019-09-03 11:14
happen on 3.0 without MC

**Comment by slivne** [comment] 2019-12-12 10:49
@bhalevy / @raphaelsc was this fixed ?

**Comment by slivne** [comment] 2020-02-09 11:21
@bhalevy / @raphaelsc was this fixed ?

**Comment by raphaelsc** [comment] 2020-02-10 13:03
looking into this...

**Comment by raphaelsc** [comment] 2020-02-10 16:16
Ran LCS workload which triggers SSTable demotion and the problem is apparently gone. I think we can close this issue.

**Closed** 2020-02-13 10:13 UTC
Labels: Backport 3.0, Backport 3.1, bug, compaction, sstable 3 format
