### ISSUE TITLE
Assertion `_promise' failed in compaction_manager

### ISSUE THREAD

**Issue by gleb-cloudius** [scylladb/scylla#567] opened 2015-11-17 13:33 UTC
Got this while stopping scylla:

scylla: /home/fedora/scylla/seastar/core/future.hh:643: void future<T>::schedule(Func&&) [with Func = future<T>::then(Func&&) [with Func = compaction_manager::task_stop(lw_shared_ptr<compaction_manager::task>&)::<lambda()>::<lambda()>; Result = future<>; T = {}]::<lambda(auto:1&&)>; T = {}]: Assertion `_promise' failed.

**Comment by raphaelsc** [comment] 2015-11-23 20:40
@gleb-cloudius: Could you please describe the scenario? How did you stop Scylla? Thanks.

**Comment by gleb-cloudius** [comment] 2015-11-24 05:28
On Mon, Nov 23, 2015 at 12:41:03PM -0800, Raphael Carvalho wrote:
> @gleb-cloudius: Could you please describe the scenario? How did you stop Scylla? Thanks.
> 
Was running 3 cluster node. Pressed ^C on one of them.

--
			Gleb.

**Comment by slivne** [comment] 2016-02-17 09:43
noam will try to reproduce this with branch-0.18 sending sigterm to them

**Comment by raphaelsc** [comment] 2016-02-17 10:40
@slivne: Compaction manager changed a lot since this issue, so this problem may not exist anymore. Anyway, it's good to check.

**Comment by slivne** [comment] 2016-02-17 10:57
Thats why I want to check and if it does not reproduce close it

On Wed, Feb 17, 2016 at 12:40 PM, Raphael Carvalho <notifications@github.com

**Comment by noamha** [comment] 2016-02-17 15:26
Couldn't reproduce the issue.

Configuration:
- 1 node at Rackspace 15 GB I/O v1 CentOS
Build: https://s3.amazonaws.com/downloads.scylladb.com/rpm/unstable/centos/branch-0.18/13/scylla.repo

1. Ran the following stress:
time cassandra-stress write cl=ONE n=30000000 -mode native cql3 -rate threads=700 -node $SERVERS -pop seq=1..30000000 -col 'size=FIXED(2048) n=FIXED(5)'
2. made sure scylla is running compaction with nodetool compactionstats
3. sent a sigterm signal:
kill -15 10532
4. shutdown seems to be clean:
```
Feb 17 14:53:15 noam-server-04 scylla[10532]:  [shard 0] storage_service - Drain on shutdown: shutdown commitlog done
Feb 17 14:53:15 noam-server-04 scylla[10532]:  [shard 0] storage_service - Drain on shutdown: done
Feb 17 14:53:15 noam-server-04 scylla[10532]:  [shard 0] compaction_manager - Asked to stop
Feb 17 14:53:15 noam-server-04 scylla[10532]:  [shard 1] compaction_manager - Asked to stop
Feb 17 14:53:15 noam-server-04 scylla[10532]:  [shard 2] compaction_manager - Asked to stop
Feb 17 14:53:16 noam-server-04 scylla[10532]:  [shard 3] compaction_manager - Asked to stop
Feb 17 14:53:16 noam-server-04 scylla[10532]:  [shard 2] compaction_manager - compaction info: Compaction for keyspace1/standard1 was stopped due to shutdown.
Feb 17 14:53:16 noam-server-04 scylla[10532]:  [shard 2] compaction_manager - compaction task handler stopped due to shutdown
Feb 17 14:53:16 noam-server-04 scylla[10532]:  [shard 2] compaction_manager - compaction task handler stopped due to shutdown
Feb 17 14:53:16 noam-server-04 scylla[10532]:  [shard 1] compaction_manager - compaction info: Compaction for keyspace1/standard1 was stopped due to shutdown.
Feb 17 14:53:16 noam-server-04 scylla[10532]:  [shard 1] compaction_manager - compaction task handler stopped due to shutdown
Feb 17 14:53:16 noam-server-04 scylla[10532]:  [shard 1] compaction_manager - compaction task handler stopped due to shutdown
Feb 17 14:53:16 noam-server-04 scylla[10532]:  [shard 3] compaction_manager - compaction info: Compaction for keyspace1/standard1 was stopped due to shutdown.
Feb 17 14:53:16 noam-server-04 scylla[10532]:  [shard 3] compaction_manager - compaction task handler stopped due to shutdown
Feb 17 14:53:16 noam-server-04 scylla[10532]:  [shard 3] compaction_manager - compaction task handler stopped due to shutdown
Feb 17 14:53:16 noam-server-04 scylla[10532]:  [shard 0] compaction_manager - compaction info: Compaction for keyspace1/standard1 was stopped due to shutdown.
Feb 17 14:53:16 noam-server-04 scylla[10532]:  [shard 0] compaction_manager - compaction task handler stopped due to shutdown
Feb 17 14:53:16 noam-server-04 scylla[10532]:  [shard 0] compaction_manager - compaction task handler stopped due to shutdown
```

**Comment by noamha** [comment] 2016-02-17 15:31
Tried the same procedure as above several times, and got the same result

**Comment by raphaelsc** [comment] 2016-02-17 15:35
On Wed, Feb 17, 2016 at 1:31 PM, noamha <notifications@github.com> wrote:

> Tried the same procedure as above several times, and got the same result
>

Cool. I suppose this issue can be closed then. Thanks for testing it.


> —
> Reply to this email directly or view it on GitHub
> <https://github.com/scylladb/scylla/issues/567#issuecomment-185255896>.
>



-- 
Raphael S. Carvalho

**Closed** 2016-02-17 15:39 UTC
Labels: bug
