### ISSUE TITLE
Node decommission failure during longevity test

### ISSUE THREAD

**Issue by roydahan** [scylladb/scylla#2040] opened 2017-01-25 18:42 UTC
*Installation details*
Scylla version (or git commit hash):1.6.rc1
Cluster size: 6 (and changing)
OS (RHEL/CentOS/Ubuntu/AWS AMI): AWS AMI

Platform (physical/VM/cloud instance type/docker): i2.4xlarge

During longevity testing, after 12+ hours of run, node decommission failed with the following error:
```
2017-01-25 04:50:30,584 remote           L0194 DEBUG| [52.91.201.225] [stdout] total,    1792468845,   35736,   35736,   35736,    27.7,    13.2,   128.3,   180.9,   256.0,   313.1,47912.9,  0.00015,      0,      0,       0,       0,       0,       0
2017-01-25 04:50:31,251 remote           L0194 DEBUG| [54.173.41.155] [stdout] Jan 25 04:50:31 info   |  [shard 2] compaction - Compacted 4 sstables to [/var/lib/scylla/data/keyspace1/standard1-19e20940e24a11e6b2b4000000000001/keyspace1-standard1-ka-1402-Data.db:level=
0, ]. 427210482 bytes to 130103000 (~30% of original) in 16445ms = 7.5449MB/s. ~1521024 total partitions merged to 463000.
2017-01-25 04:50:31,767 remote           L0194 DEBUG| [52.91.201.225] [stdout] total,    1792513669,   36237,   36237,   36237,    27.4,    12.5,   132.9,   173.0,   220.3,   251.1,47914.2,  0.00015,      0,      0,       0,       0,       0,       0
2017-01-25 04:50:32,861 remote           L0194 DEBUG| [52.91.201.225] [stdout] total,    1792558244,   37651,   37651,   37651,    27.8,    10.4,   129.2,   157.6,   191.0,   271.0,47915.4,  0.00015,      0,      0,       0,       0,       0,       0
2017-01-25 04:50:33,965 remote           L0194 DEBUG| [52.91.201.225] [stdout] total,    1792598610,   36904,   36904,   36904,    27.1,    23.5,    61.5,    83.9,   100.2,   129.1,47916.4,  0.00015,      0,      0,       0,       0,       0,       0
2017-01-25 04:50:34,799 remote           L0194 DEBUG| [52.204.101.17] [stdout] Jan 25 04:50:34 info   |  [shard 0] messaging_service - Retry verb=18 to 172.30.0.184:7, retry=10: timeout in 600 seconds
2017-01-25 04:50:34,799 remote           L0194 DEBUG| [52.204.101.17] [stdout] Jan 25 04:50:34 warning|  [shard 0] stream_session - [Stream #4c4b9360-e2b8-11e6-b95c-000000000005] stream_transfer_task: Fail to send STREAM_MUTATION_DONE to 172.30.0.184:7: rpc::timeout_er
ror (rpc call timed out)
2017-01-25 04:50:34,800 remote           L0194 DEBUG| [52.204.101.17] [stdout] Jan 25 04:50:34 warning|  [shard 0] stream_session - [Stream #4c4b9360-e2b8-11e6-b95c-000000000005] stream_transfer_task: Fail to send to 172.30.0.184:7: rpc::timeout_error (rpc call timed o
ut)
2017-01-25 04:50:34,800 remote           L0194 DEBUG| [52.204.101.17] [stdout] Jan 25 04:50:34 warning|  [shard 0] stream_session - [Stream #4c4b9360-e2b8-11e6-b95c-000000000005] Streaming error occurred
2017-01-25 04:50:34,800 remote           L0194 DEBUG| [52.204.101.17] [stdout] Jan 25 04:50:34 info   |  [shard 0] stream_session - [Stream #4c4b9360-e2b8-11e6-b95c-000000000005] Session with 172.30.0.184 is complete, state=FAILED
2017-01-25 04:50:34,800 remote           L0194 DEBUG| [52.204.101.17] [stdout] Jan 25 04:50:34 info   |  [shard 0] stream_session - [Stream #4c4b9360-e2b8-11e6-b95c-000000000005] bytes_sent = 2611793856, bytes_received = 0, tx_bandwidth = 3.841 MiB/s, rx_bandwidth = 0.
000 MiB/s
2017-01-25 04:50:34,801 remote           L0194 DEBUG| [52.204.101.17] [stdout] Jan 25 04:50:34 warning|  [shard 0] stream_session - [Stream #4c4b9360-e2b8-11e6-b95c-000000000005] Stream failed for streaming plan Unbootstrap, peers={172.30.0.49, 172.30.0.65, 172.30.0.10
9, 172.30.0.184, 172.30.0.199}
2017-01-25 04:50:34,804 remote           L0194 DEBUG| [52.204.101.17] [stdout] Jan 25 04:50:34 info   |  [shard 0] storage_service - stream_ranges failed: streaming::stream_exception (Stream failed)
2017-01-25 04:50:34,805 remote           L0194 DEBUG| [52.204.101.17] [stdout] Jan 25 04:50:34 warning|  [shard 0] storage_service - unbootstrap fails to stream : std::runtime_error (stream_ranges failed)
2017-01-25 04:50:34,816 remote           L0194 DEBUG| [52.204.101.17] [stdout] nodetool: Scylla API server HTTP POST to URL '/storage_service/decommission' failed: stream_ranges failed
2017-01-25 04:50:34,816 remote           L0194 DEBUG| [52.204.101.17] [stdout] See 'nodetool help' or 'nodetool help <command>'.
2017-01-25 04:50:34,840 nemesis          L0109 ERROR| sdcm.nemesis.ChaosMonkey: nodetool command 'nodetool --host localhost decommission' failed on node Node longevity-1-6-scylla-db-node-02f299c5-16 [52.204.101.17 | 172.30.0.55] (seed: False): Command: /bin/ssh  -a -x  -o ControlPath=/var/tmp/ssh-masterAq9FIb/socket -o StrictHostKeyChecking=no -o UserKnownHostsFile=/var/tmp/tmpXNitQG -o BatchMode=yes -o ConnectTimeout=300 -o ServerAliveInterval=300 -l centos -p 22 -i /var/tmp/longevity-1-6-sct-db6b8640.pem 52.204.101.17 "nodetool --host localhost decommission"
Exit status: 1
Duration: 680.534250975
Stdout:
nodetool: Scylla API server HTTP POST to URL '/storage_service/decommission' failed: stream_ranges failed
See 'nodetool help' or 'nodetool help <command>'.

Stderr:


2017-01-25 04:50:34,841 nemesis          L0274 DEBUG| sdcm.nemesis.ChaosMonkey: Decommission Node longevity-1-6-scylla-db-node-02f299c5-16 [52.204.101.17 | 172.30.0.55] (seed: False) duration -> 680 s
2017-01-25 04:50:35,135 remote           L0194 DEBUG| [52.91.201.225] [stdout] total,    1792640330,   37793,   37793,   37793,    25.4,    14.5,   113.5,   151.5,   189.5,   237.0,47917.6,  0.00015,      0,      0,       0,       0,       0,       0
2017-01-25 04:50:36,323 remote           L0194 DEBUG| [52.91.201.225] [stdout] total,    1792680994,   34754,   34754,   34754,    28.1,     9.0,   142.3,   217.5,   260.6,   304.1,47918.7,  0.00015,      0,      0,       0,       0,       0,       0
2017-01-25 04:50:37,406 remote           L0194 DEBUG| [52.91.201.225] [stdout] total,    1792724445,   36838,   36838,   36838,    28.7,    19.3,   112.8,   168.4,   284.9,   320.8,47919.9,  0.00015,      0,      0,       0,       0,       0,       0
2017-01-25 04:50:38,758 remote           L0194 DEBUG| [52.91.201.225] [stdout] total,    1792764828,   37281,   37281,   37281,    26.5,    20.3,    73.8,   142.4,   176.3,   211.2,47921.0,  0.00015,      0,      0,       0,       0,       0,       0
2017-01-25 04:50:40,003 remote           L0194 DEBUG| [52.91.201.225] [stdout] total,    1792797773,   24364,   24364,   24364,    36.9,     2.6,   248.6,   318.5,   398.0,   467.0,47922.3,  0.00015,      0,      0,       0,       0,       0,       0
2017-01-25 04:50:41,190 remote           L0194 DEBUG| [52.91.201.225] [stdout] total,    1792834000,   29107,   29107,   29107,    37.7,     7.0,   238.8,   317.4,   543.1,   647.9,47923.6,  0.00015,      0,      0,       0,       0,       0,       0
2017-01-25 04:50:42,382 remote           L0194 DEBUG| [52.91.201.225] [stdout] total,    1792876892,   36108,   36108,   36108,    26.6,    14.3,   113.1,   185.8,   228.3,   309.0,47924.8,  0.00015,      0,      0,       0,       0,       0,       0
2017-01-25 04:50:43,483 remote           L0194 DEBUG| [52.91.201.225] [stdout] total,    1792920582,   36664,   36664,   36664,    28.9,    23.5,    91.3,   159.5,   310.9,   354.8,47926.0,  0.00015,      0,      0,       0,       0,       0,       0
2017-01-25 04:50:44,597 remote           L0194 DEBUG| [52.91.201.225] [stdout] total,    1792961935,   37586,   37586,   37586,    26.5,    23.4,    56.9,    84.7,   120.8,   134.6,47927.1,  0.00015,      0,      0,       0,       0,       0,       0
2017-01-25 04:50:45,751 remote           L0194 DEBUG| [52.91.201.225] [stdout] total,    1793003517,   37300,   37300,   37300,    25.8,    10.5,   128.1,   161.2,   204.6,   236.3,47928.2,  0.00015,      0,      0,       0,       0,       0,       0
2017-01-25 04:50:46,516 remote           L0194 DEBUG| [54.162.107.7] [stdout] Jan 25 04:50:46 info   |  [shard 7] stream_session - [Stream #4c4b9360-e2b8-11e6-b95c-000000000005] The session 0x607105fd1400 is idle for 600 seconds, the peer 172.30.0.55 is probably gone, close it
2017-01-25 04:50:46,530 remote           L0194 DEBUG| [54.162.107.7] [stdout] Jan 25 04:50:46 warning|  [shard 7] stream_session - [Stream #4c4b9360-e2b8-11e6-b95c-000000000005] Streaming error occurred
2017-01-25 04:50:46,530 remote           L0194 DEBUG| [54.162.107.7] [stdout] Jan 25 04:50:46 info   |  [shard 7] stream_session - [Stream #4c4b9360-e2b8-11e6-b95c-000000000005] Session with 172.30.0.55 is complete, state=FAILED
2017-01-25 04:50:46,530 remote           L0194 DEBUG| [54.162.107.7] [stdout] Jan 25 04:50:46 info   |  [shard 7] stream_session - [Stream #4c4b9360-e2b8-11e6-b95c-000000000005] bytes_sent = 0, bytes_received = 400118784, tx_bandwidth = 0.000 MiB/s, rx_bandwidth = 0.578 MiB/s
2017-01-25 04:50:46,531 remote           L0194 DEBUG| [54.162.107.7] [stdout] Jan 25 04:50:46 warning|  [shard 7] stream_session - [Stream #4c4b9360-e2b8-11e6-b95c-000000000005] Stream failed for streaming plan Unbootstrap, peers={172.30.0.55}
2017-01-25 04:50:46,952 remote           L0194 DEBUG| [52.91.201.225] [stdout] total,    1793046295,   37070,   37070,   37070,    27.4,    20.7,    85.3,   129.4,   181.5,   229.3,47929.3,  0.00015,      0,      0,       0,       0,       0,       0
```

The streaming failed for node: 172.30.0.184 (54.162.107.7)
```
L0194 DEBUG| [52.204.101.17] [stdout] Jan 25 04:50:34 warning|  [shard 0] stream_session - [Stream #4c4b9360-e2b8-11e6-b95c-000000000005] stream_transfer_task: Fail to send STREAM_MUTATION_DONE to 172.30.0.184:7: rpc::timeout_er
ror (rpc call timed out)
```
However, it seems like the node was up and running during that time and reported the failure from its side as well:
```
2017-01-25 04:50:46,516 remote           L0194 DEBUG| [54.162.107.7] [stdout] Jan 25 04:50:46 info   |  [shard 7] stream_session - [Stream #4c4b9360-e2b8-11e6-b95c-000000000005] The session 0x607105fd1400 is idle for 600 seconds, the peer 172.30.0.55 is probably gone,
close it
2017-01-25 04:50:46,530 remote           L0194 DEBUG| [54.162.107.7] [stdout] Jan 25 04:50:46 warning|  [shard 7] stream_session - [Stream #4c4b9360-e2b8-11e6-b95c-000000000005] Streaming error occurred
2017-01-25 04:50:46,530 remote           L0194 DEBUG| [54.162.107.7] [stdout] Jan 25 04:50:46 info   |  [shard 7] stream_session - [Stream #4c4b9360-e2b8-11e6-b95c-000000000005] Session with 172.30.0.55 is complete, state=FAILED
2017-01-25 04:50:46,530 remote           L0194 DEBUG| [54.162.107.7] [stdout] Jan 25 04:50:46 info   |  [shard 7] stream_session - [Stream #4c4b9360-e2b8-11e6-b95c-000000000005] bytes_sent = 0, bytes_received = 400118784, tx_bandwidth = 0.000 MiB/s, rx_bandwidth = 0.57
8 MiB/s
2017-01-25 04:50:46,531 remote           L0194 DEBUG| [54.162.107.7] [stdout] Jan 25 04:50:46 warning|  [shard 7] stream_session - [Stream #4c4b9360-e2b8-11e6-b95c-000000000005] Stream failed for streaming plan Unbootstrap, peers={172.30.0.55}
```

From the Prometheus DB, it also looks like both nodes continue to serve CQL and RPC requests.

We saw some strange and hight metrics for queue delay, but @gleb-cloudius might explain better than me (screenshot attached).
![screen shot 2017-01-25 at 20 39 57](https://cloud.githubusercontent.com/assets/20959584/22304088/b7ae9086-e33e-11e6-8f97-a1492bdd144f.png)

**Comment by roydahan** [comment] 2017-01-25 18:47
Jog log:
[job.log.gz](https://github.com/scylladb/scylla/files/730653/job.log.gz)

**Comment by slivne** [comment] 2017-01-26 13:47
in the job.log we had 28 decommissions ... so its not that ever decommission fails.

I was not able to easily reproduce this - maybe its "simply a bad AWS instance"

![screenshot from 2017-01-26 15-44-43](https://cloud.githubusercontent.com/assets/3465480/22333361/80e67622-e3de-11e6-80c9-e9a7e5e9957d.png)

doing the same query on other instances ``` collectd_reactor_gauge{type="gauge_queued-io-requests",instance!="54.162.107.7:9103"}``` there are a few spikes on other instances but nothing close to what we are getting here.

**Comment by tzach** [comment] 2017-08-21 07:34
@harelassayag @amoskong can we close this issue? as far as I know the test pass with 2.0 RC2
Is it the case?

**Comment by tzach** [comment] 2017-08-21 08:14
We have approval the problem is now fix

**Closed by tzach** 2017-08-21 08:14 UTC
Labels: bug
