### ISSUE TITLE
reclaim_from_evictable stalls for 27ms

### ISSUE THREAD

**Issue by asias** [scylladb/scylla#8937] opened 2021-06-29 06:27 UTC
Scylla: 
https://github.com/asias/scylla/tree/for-sct-test-repair_meta-clear_gently (custom build)

Job:
https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/RBNO/job/repair-based-operation/job/longevity-100gb-4h-ReplaceNode-test/23/

Decode:
```
longevity-100gb-4h-rbno-db-node-2185bd3e-1/messages.log:2021-06-29T00:23:20+00:00  longevity-100gb-4h-rbno-db-node-2185bd3e-1 !INFO    | scylla: Reactor stalled for 27 ms on shard 3. Backtrace:
[Backtrace #0]
void seastar::backtrace<seastar::backtrace_buffer::append_backtrace_oneline()::{lambda(seastar::frame)#1}>(seastar::backtrace_buffer::append_backtrace_oneline()::{lambda(seastar::frame)#1}&&) at ./build/release/seastar/./seastar/include/seastar/util/backtrace.hh:59
 (inlined by) seastar::backtrace_buffer::append_backtrace_oneline() at ./build/release/seastar/./seastar/src/core/reactor.cc:768
 (inlined by) seastar::print_with_backtrace(seastar::backtrace_buffer&, bool) at ./build/release/seastar/./seastar/src/core/reactor.cc:787
seastar::internal::cpu_stall_detector::generate_trace() at ./build/release/seastar/./seastar/src/core/reactor.cc:1221
seastar::internal::cpu_stall_detector::maybe_report() at ./build/release/seastar/./seastar/src/core/reactor.cc:1102
 (inlined by) seastar::internal::cpu_stall_detector::on_signal() at ./build/release/seastar/./seastar/src/core/reactor.cc:1116
 (inlined by) seastar::reactor::block_notifier(int) at ./build/release/seastar/./seastar/src/core/reactor.cc:1204
?? ??:0
bplus::node<long, intrusive_array<cache_entry>, dht::raw_token_less_comparator, 16ul, (bplus::key_search)0, (bplus::with_debug)0>::is_leaf() const at ././utils/bptree.hh:991
 (inlined by) bplus::node<long, intrusive_array<cache_entry>, dht::raw_token_less_comparator, 16ul, (bplus::key_search)0, (bplus::with_debug)0>::set_prev(bplus::node<long, intrusive_array<cache_entry>, dht::raw_token_less_comparator, 16ul, (bplus::key_search)0, (bplus::with_debug)0>*) at ././utils/bptree.hh:1065
 (inlined by) node at ././utils/bptree.hh:1809
 (inlined by) standard_migrator<bplus::node<long, intrusive_array<cache_entry>, dht::raw_token_less_comparator, 16ul, (bplus::key_search)0, (bplus::with_debug)0> >::migrate(void*, void*, unsigned long) const at ././utils/allocation_strategy.hh:87
operator() at ./utils/logalloc.cc:1328
 (inlined by) void logalloc::region_impl::for_each_live<logalloc::region_impl::compact_segment_locked(logalloc::segment*, logalloc::segment_descriptor&)::{lambda(logalloc::region_impl::object_descriptor const*, void*, unsigned long)#1}>(logalloc::segment*, logalloc::region_impl::compact_segment_locked(logalloc::segment*, logalloc::segment_descriptor&)::{lambda(logalloc::region_impl::object_descriptor const*, void*, unsigned long)#1}&&) at ./utils/logalloc.cc:1269
 (inlined by) logalloc::region_impl::compact_segment_locked(logalloc::segment*, logalloc::segment_descriptor&) at ./utils/logalloc.cc:1325
logalloc::region_impl::compact() at ./utils/logalloc.cc:1614
logalloc::reclaim_from_evictable(logalloc::region_impl&, unsigned long, seastar::bool_class<is_preemptible_tag>) at ./utils/logalloc.cc:1911
logalloc::tracker::impl::compact_and_evict_locked(unsigned long, unsigned long, seastar::bool_class<is_preemptible_tag>) at ./utils/logalloc.cc:2087
logalloc::tracker::impl::compact_and_evict(unsigned long, unsigned long, seastar::bool_class<is_preemptible_tag>) at ./utils/logalloc.cc:2020
 (inlined by) logalloc::segment_pool::allocate_segment(unsigned long) at ./utils/logalloc.cc:924
logalloc::segment_pool::refill_emergency_reserve() at ./utils/logalloc.cc:937
 (inlined by) logalloc::allocating_section::reserve() at ./utils/logalloc.cc:2377
decltype(auto) logalloc::allocating_section::with_reserve<logalloc::allocating_section::operator()<row_cache::do_update<row_cache::update(row_cache::external_updater, memtable&)::$_20>(row_cache::external_updater, memtable&, row_cache::update(row_cache::external_updater, memtable&)::$_20)::{lambda()#1}::operator()() const::{lambda()#2}::operator()()::{lambda()#2}::operator()() const::{lambda()#1}>(logalloc::region&, row_cache::do_update<row_cache::update(row_cache::external_updater, memtable&)::$_20>(row_cache::external_updater, memtable&, row_cache::update(row_cache::external_updater, memtable&)::$_20)::{lambda()#1}::operator()() const::{lambda()#2}::operator()()::{lambda()#2}::operator()() const::{lambda()#1}&&)::{lambda()#1}>({lambda()#1}) at ././utils/logalloc.hh:711
 (inlined by) decltype(auto) logalloc::allocating_section::operator()<row_cache::do_update<row_cache::update(row_cache::external_updater, memtable&)::$_20>(row_cache::external_updater, memtable&, row_cache::update(row_cache::external_updater, memtable&)::$_20)::{lambda()#1}::operator()() const::{lambda()#2}::operator()()::{lambda()#2}::operator()() const::{lambda()#1}>(logalloc::region&, row_cache::do_update<row_cache::update(row_cache::external_updater, memtable&)::$_20>(row_cache::external_updater, memtable&, row_cache::update(row_cache::external_updater, memtable&)::$_20)::{lambda()#1}::operator()() const::{lambda()#2}::operator()()::{lambda()#2}::operator()() const::{lambda()#1}&&) at ././utils/logalloc.hh:762
 (inlined by) operator() at ./row_cache.cc:972
 (inlined by) decltype(auto) with_allocator<row_cache::do_update<row_cache::update(row_cache::external_updater, memtable&)::$_20>(row_cache::external_updater, memtable&, row_cache::update(row_cache::external_updater, memtable&)::$_20)::{lambda()#1}::operator()() const::{lambda()#2}::operator()()::{lambda()#2}>(allocation_strategy&, row_cache::do_update<row_cache::update(row_cache::external_updater, memtable&)::$_20>(row_cache::external_updater, memtable&, row_cache::update(row_cache::external_updater, memtable&)::$_20)::{lambda()#1}::operator()() const::{lambda()#2}::operator()()::{lambda()#2}&&) at ././utils/allocation_strategy.hh:328
 (inlined by) operator() at ./row_cache.cc:959
 (inlined by) void std::__invoke_impl<void, row_cache::do_update<row_cache::update(row_cache::external_updater, memtable&)::$_20>(row_cache::external_updater, memtable&, row_cache::update(row_cache::external_updater, memtable&)::$_20)::{lambda()#1}::operator()() const::{lambda()#2}>(std::__invoke_other, row_cache::do_update<row_cache::update(row_cache::external_updater, memtable&)::$_20>(row_cache::external_updater, memtable&, row_cache::update(row_cache::external_updater, memtable&)::$_20)::{lambda()#1}::operator()() const::{lambda()#2}&&) at /usr/lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/bits/invoke.h:60
 (inlined by) std::__invoke_result<row_cache::do_update<row_cache::update(row_cache::external_updater, memtable&)::$_20>(row_cache::external_updater, memtable&, row_cache::update(row_cache::external_updater, memtable&)::$_20)::{lambda()#1}::operator()() const::{lambda()#2}>::type std::__invoke<row_cache::do_update<row_cache::update(row_cache::external_updater, memtable&)::$_20>(row_cache::external_updater, memtable&, row_cache::update(row_cache::external_updater, memtable&)::$_20)::{lambda()#1}::operator()() const::{lambda()#2}>(row_cache::do_update<row_cache::update(row_cache::external_updater, memtable&)::$_20>(row_cache::external_updater, memtable&, row_cache::update(row_cache::external_updater, memtable&)::$_20)::{lambda()#1}::operator()() const::{lambda()#2}&&, (row_cache::do_update<row_cache::update(row_cache::external_updater, memtable&)::$_20>(row_cache::external_updater, memtable&, row_cache::update(row_cache::external_updater, memtable&)::$_20)::{lambda()#1}::operator()() const::{lambda()#2}&&)...) at /usr/lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/bits/invoke.h:95
 (inlined by) decltype(auto) std::__apply_impl<row_cache::do_update<row_cache::update(row_cache::external_updater, memtable&)::$_20>(row_cache::external_updater, memtable&, row_cache::update(row_cache::external_updater, memtable&)::$_20)::{lambda()#1}::operator()() const::{lambda()#2}, std::tuple<>>(row_cache::do_update<row_cache::update(row_cache::external_updater, memtable&)::$_20>(row_cache::external_updater, memtable&, row_cache::update(row_cache::external_updater, memtable&)::$_20)::{lambda()#1}::operator()() const::{lambda()#2}&&, std::tuple<>&&, std::integer_sequence<unsigned long>) at /usr/lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/tuple:1723
 (inlined by) decltype(auto) std::apply<row_cache::do_update<row_cache::update(row_cache::external_updater, memtable&)::$_20>(row_cache::external_updater, memtable&, row_cache::update(row_cache::external_updater, memtable&)::$_20)::{lambda()#1}::operator()() const::{lambda()#2}, std::tuple<> >(row_cache::do_update<row_cache::update(row_cache::external_updater, memtable&)::$_20>(row_cache::external_updater, memtable&, row_cache::update(row_cache::external_updater, memtable&)::$_20)::{lambda()#1}::operator()() const::{lambda()#2}&&, std::tuple<>&&) at /usr/lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/tuple:1734
 (inlined by) seastar::future<void> seastar::futurize<void>::apply<row_cache::do_update<row_cache::update(row_cache::external_updater, memtable&)::$_20>(row_cache::external_updater, memtable&, row_cache::update(row_cache::external_updater, memtable&)::$_20)::{lambda()#1}::operator()() const::{lambda()#2}>(row_cache::do_update<row_cache::update(row_cache::external_updater, memtable&)::$_20>(row_cache::external_updater, memtable&, row_cache::update(row_cache::external_updater, memtable&)::$_20)::{lambda()#1}::operator()() const::{lambda()#2}&&, std::tuple<>&&) at ././seastar/include/seastar/core/future.hh:2099
 (inlined by) operator() at ././seastar/include/seastar/core/thread.hh:258
 (inlined by) seastar::noncopyable_function<void ()>::direct_vtable_for<seastar::async<row_cache::do_update<row_cache::update(row_cache::external_updater, memtable&)::$_20>(row_cache::external_updater, memtable&, row_cache::update(row_cache::external_updater, memtable&)::$_20)::{lambda()#1}::operator()() const::{lambda()#2}>(seastar::thread_attributes, row_cache::do_update<row_cache::update(row_cache::external_updater, memtable&)::$_20>(row_cache::external_updater, memtable&, row_cache::update(row_cache::external_updater, memtable&)::$_20)::{lambda()#1}::operator()() const::{lambda()#2}&&, (std::decay<row_cache::do_update<row_cache::update(row_cache::external_updater, memtable&)::$_20>(row_cache::external_updater, memtable&, row_cache::update(row_cache::external_updater, memtable&)::$_20)::{lambda()#1}::operator()() const::{lambda()#2}>&&)...)::{lambda()#1}>::call(seastar::noncopyable_function<void ()> const*) at ././seastar/include/seastar/util/noncopyable_function.hh:124
seastar::noncopyable_function<void ()>::operator()() const at ./build/release/seastar/./seastar/include/seastar/util/noncopyable_function.hh:209
 (inlined by) seastar::thread_context::main() at ./build/release/seastar/./seastar/src/core/thread.cc:299
```

**Comment by avikivity** [comment] 2021-06-29 10:20
Closing as duplicate of #8938. Both are refill_emergency_reserve().

**Closed by avikivity** 2021-06-29 10:20 UTC
