### ISSUE TITLE
Many 2000ms reactor stalls in 3.0 working with large rows/partitions

### ISSUE THREAD

**Issue by veramine** [scylladb/scylla#4020] opened 2018-12-25 08:43 UTC
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [X] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash):  3.0.rc3-0.20181224.5558fa8
Cluster size: 3
OS (RHEL/CentOS/Ubuntu/AWS AMI): AWS CentOS AMI + fresh build

*Hardware details (for performance issues)*          Delete if unneeded
Platform (physical/VM/cloud instance type/docker): AWS i3.xlarge 

We are seeing timeouts in our 3.0 stress testing.  They come in clumps and I believe are due to a bunch of 2000ms Reactor stalls.  I've pasted in two examples below from today.  I've also attached a file with back traces of a bunch more we have seen:

```
Seen 3 occurrences taking up to 2000 ms in shards {1, 2}:
void seastar::backtrace<seastar::backtrace_buffer::append_backtrace()::{lambda(seastar::frame)#1}>(seastar::backtrace_buffer::append_backtrace()::{lambda(seastar::frame)#1}&&) at crtstuff.c:?
seastar::print_with_backtrace(seastar::backtrace_buffer&) at reactor.cc:?
seastar::reactor::block_notifier(int) at crtstuff.c:?
?? ??:0
rows_entry::rows_entry(rows_entry&&) at crtstuff.c:?
standard_migrator<rows_entry>::migrate(void*, void*, unsigned long) const at crtstuff.c:?
logalloc::segment_pool::migrate_segment(logalloc::segment*, logalloc::segment*) at crtstuff.c:?
logalloc::segment_pool::reclaim_segments(unsigned long) at crtstuff.c:?
std::_Function_handler<seastar::memory::reclaiming_result (), logalloc::tracker::tracker()::{lambda()#1}>::_M_invoke(std::_Any_data const&) at logalloc.cc:?
seastar::memory::cpu_pages::allocate_large_and_trim(unsigned int) at crtstuff.c:?
seastar::memory::allocate(unsigned long) at crtstuff.c:?
seastar::input_stream<char>::read_exactly(unsigned long) at crtstuff.c:?
seastar::future<> seastar::futurize<seastar::future<> >::apply<db::commitlog::read_log_file(seastar::basic_sstring<char, unsigned int, 15u, true> const&, seastar::io_priority_class, std::function<seastar::future<> (seastar::temporary_buffer<char>, db::replay_position)>, unsigned int, db::extensions const*)::work::read_entry()::{lambda(seastar::temporary_buffer<char>)#1}, seastar::temporary_buffer<char> >(db::commitlog::read_log_file(seastar::basic_sstring<char, unsigned int, 15u, true> const&, seastar::io_priority_class, std::function<seastar::future<> (seastar::temporary_buffer<char>, db::replay_position)>, unsigned int, db::extensions const*)::work::read_entry()::{lambda(seastar::temporary_buffer<char>)#1}&&, std::tuple<seastar::temporary_buffer<char> >&&) at commitlog.cc:?
db::commitlog::read_log_file(seastar::basic_sstring<char, unsigned int, 15u, true> const&, seastar::io_priority_class, std::function<seastar::future<> (seastar::temporary_buffer<char>, db::replay_position)>, unsigned int, db::extensions const*)::work::read_entry() at commitlog.cc:?
seastar::future<> seastar::do_until<std::_Bind<seastar::future<> (db::commitlog::read_log_file(seastar::basic_sstring<char, unsigned int, 15u, true> const&, seastar::io_priority_class, std::function<seastar::future<> (seastar::temporary_buffer<char>, db::replay_position)>, unsigned int, db::extensions const*)::work::*(db::commitlog::read_log_file(seastar::basic_sstring<char, unsigned int, 15u, true> const&, seastar::io_priority_class, std::function<seastar::future<> (seastar::temporary_buffer<char>, db::replay_position)>, unsigned int, db::extensions const*)::work*))()>, std::_Bind<bool (db::commitlog::read_log_file(seastar::basic_sstring<char, unsigned int, 15u, true> const&, seastar::io_priority_class, std::function<seastar::future<> (seastar::temporary_buffer<char>, db::replay_position)>, unsigned int, db::extensions const*)::work::*(db::commitlog::read_log_file(seastar::basic_sstring<char, unsigned int, 15u, true> const&, seastar::io_priority_class, std::function<seastar::future<> (seastar::temporary_buffer<char>, db::replay_position)>, unsigned int, db::extensions const*)::work*))() const> >(std::_Bind<bool (db::commitlog::read_log_file(seastar::basic_sstring<char, unsigned int, 15u, true> const&, seastar::io_priority_class, std::function<seastar::future<> (seastar::temporary_buffer<char>, db::replay_position)>, unsigned int, db::extensions const*)::work::*(db::commitlog::read_log_file(seastar::basic_sstring<char, unsigned int, 15u, true> const&, seastar::io_priority_class, std::function<seastar::future<> (seastar::temporary_buffer<char>, db::replay_position)>, unsigned int, db::extensions const*)::work*))() const>, std::_Bind<seastar::future<> (db::commitlog::read_log_file(seastar::basic_sstring<char, unsigned int, 15u, true> const&, seastar::io_priority_class, std::function<seastar::future<> (seastar::temporary_buffer<char>, db::replay_position)>, unsigned int, db::extensions const*)::work::*(db::commitlog::read_log_file(seastar::basic_sstring<char, unsigned int, 15u, true> const&, seastar::io_priority_class, std::function<seastar::future<> (seastar::temporary_buffer<char>, db::replay_position)>, unsigned int, db::extensions const*)::work*))()>) at commitlog.cc:?
db::commitlog::read_log_file(seastar::basic_sstring<char, unsigned int, 15u, true> const&, seastar::io_priority_class, std::function<seastar::future<> (seastar::temporary_buffer<char>, db::replay_position)>, unsigned int, db::extensions const*)::work::read_chunk() at commitlog.cc:?
seastar::internal::do_until_state<std::_Bind<bool (db::commitlog::read_log_file(seastar::basic_sstring<char, unsigned int, 15u, true> const&, seastar::io_priority_class, std::function<seastar::future<> (seastar::temporary_buffer<char>, db::replay_position)>, unsigned int, db::extensions const*)::work::*(db::commitlog::read_log_file(seastar::basic_sstring<char, unsigned int, 15u, true> const&, seastar::io_priority_class, std::function<seastar::future<> (seastar::temporary_buffer<char>, db::replay_position)>, unsigned int, db::extensions const*)::work*))() const>, std::_Bind<seastar::future<> (db::commitlog::read_log_file(seastar::basic_sstring<char, unsigned int, 15u, true> const&, seastar::io_priority_class, std::function<seastar::future<> (seastar::temporary_buffer<char>, db::replay_position)>, unsigned int, db::extensions const*)::work::*(db::commitlog::read_log_file(seastar::basic_sstring<char, unsigned int, 15u, true> const&, seastar::io_priority_class, std::function<seastar::future<> (seastar::temporary_buffer<char>, db::replay_position)>, unsigned int, db::extensions const*)::work*))()> >::run_and_dispose() at commitlog.cc:?
seastar::reactor::run_tasks(seastar::reactor::task_queue&) at crtstuff.c:?
seastar::reactor::run_some_tasks() [clone .part.2743] at reactor.cc:?
seastar::reactor::run() at crtstuff.c:?
seastar::smp::configure(boost::program_options::variables_map)::{lambda()#3}::operator()() const at reactor.cc:?
seastar::posix_thread::start_routine(void*) at crtstuff.c:?
?? ??:0
?? ??:0


Seen 6 occurrences taking up to 2000 ms in shards {1, 2}:
void seastar::backtrace<seastar::backtrace_buffer::append_backtrace()::{lambda(seastar::frame)#1}>(seastar::backtrace_buffer::append_backtrace()::{lambda(seastar::frame)#1}&&) at crtstuff.c:?
seastar::print_with_backtrace(seastar::backtrace_buffer&) at reactor.cc:?
seastar::reactor::block_notifier(int) at crtstuff.c:?
?? ??:0
logalloc::region_impl::compact_single_segment_locked() at crtstuff.c:?
logalloc::tracker::impl::compact_and_evict_locked(unsigned long) at crtstuff.c:?
std::_Function_handler<seastar::memory::reclaiming_result (), logalloc::tracker::tracker()::{lambda()#1}>::_M_invoke(std::_Any_data const&) at logalloc.cc:?
seastar::memory::cpu_pages::allocate_large_and_trim(unsigned int) at crtstuff.c:?
seastar::memory::allocate(unsigned long) at crtstuff.c:?
seastar::input_stream<char>::read_exactly(unsigned long) at crtstuff.c:?
seastar::future<> seastar::futurize<seastar::future<> >::apply<db::commitlog::read_log_file(seastar::basic_sstring<char, unsigned int, 15u, true> const&, seastar::io_priority_class, std::function<seastar::future<> (seastar::temporary_buffer<char>, db::replay_position)>, unsigned int, db::extensions const*)::work::read_entry()::{lambda(seastar::temporary_buffer<char>)#1}, seastar::temporary_buffer<char> >(db::commitlog::read_log_file(seastar::basic_sstring<char, unsigned int, 15u, true> const&, seastar::io_priority_class, std::function<seastar::future<> (seastar::temporary_buffer<char>, db::replay_position)>, unsigned int, db::extensions const*)::work::read_entry()::{lambda(seastar::temporary_buffer<char>)#1}&&, std::tuple<seastar::temporary_buffer<char> >&&) at commitlog.cc:?
db::commitlog::read_log_file(seastar::basic_sstring<char, unsigned int, 15u, true> const&, seastar::io_priority_class, std::function<seastar::future<> (seastar::temporary_buffer<char>, db::replay_position)>, unsigned int, db::extensions const*)::work::read_entry() at commitlog.cc:?
seastar::future<> seastar::do_until<std::_Bind<seastar::future<> (db::commitlog::read_log_file(seastar::basic_sstring<char, unsigned int, 15u, true> const&, seastar::io_priority_class, std::function<seastar::future<> (seastar::temporary_buffer<char>, db::replay_position)>, unsigned int, db::extensions const*)::work::*(db::commitlog::read_log_file(seastar::basic_sstring<char, unsigned int, 15u, true> const&, seastar::io_priority_class, std::function<seastar::future<> (seastar::temporary_buffer<char>, db::replay_position)>, unsigned int, db::extensions const*)::work*))()>, std::_Bind<bool (db::commitlog::read_log_file(seastar::basic_sstring<char, unsigned int, 15u, true> const&, seastar::io_priority_class, std::function<seastar::future<> (seastar::temporary_buffer<char>, db::replay_position)>, unsigned int, db::extensions const*)::work::*(db::commitlog::read_log_file(seastar::basic_sstring<char, unsigned int, 15u, true> const&, seastar::io_priority_class, std::function<seastar::future<> (seastar::temporary_buffer<char>, db::replay_position)>, unsigned int, db::extensions const*)::work*))() const> >(std::_Bind<bool (db::commitlog::read_log_file(seastar::basic_sstring<char, unsigned int, 15u, true> const&, seastar::io_priority_class, std::function<seastar::future<> (seastar::temporary_buffer<char>, db::replay_position)>, unsigned int, db::extensions const*)::work::*(db::commitlog::read_log_file(seastar::basic_sstring<char, unsigned int, 15u, true> const&, seastar::io_priority_class, std::function<seastar::future<> (seastar::temporary_buffer<char>, db::replay_position)>, unsigned int, db::extensions const*)::work*))() const>, std::_Bind<seastar::future<> (db::commitlog::read_log_file(seastar::basic_sstring<char, unsigned int, 15u, true> const&, seastar::io_priority_class, std::function<seastar::future<> (seastar::temporary_buffer<char>, db::replay_position)>, unsigned int, db::extensions const*)::work::*(db::commitlog::read_log_file(seastar::basic_sstring<char, unsigned int, 15u, true> const&, seastar::io_priority_class, std::function<seastar::future<> (seastar::temporary_buffer<char>, db::replay_position)>, unsigned int, db::extensions const*)::work*))()>) at commitlog.cc:?
db::commitlog::read_log_file(seastar::basic_sstring<char, unsigned int, 15u, true> const&, seastar::io_priority_class, std::function<seastar::future<> (seastar::temporary_buffer<char>, db::replay_position)>, unsigned int, db::extensions const*)::work::read_chunk() at commitlog.cc:?
seastar::internal::do_until_state<std::_Bind<bool (db::commitlog::read_log_file(seastar::basic_sstring<char, unsigned int, 15u, true> const&, seastar::io_priority_class, std::function<seastar::future<> (seastar::temporary_buffer<char>, db::replay_position)>, unsigned int, db::extensions const*)::work::*(db::commitlog::read_log_file(seastar::basic_sstring<char, unsigned int, 15u, true> const&, seastar::io_priority_class, std::function<seastar::future<> (seastar::temporary_buffer<char>, db::replay_position)>, unsigned int, db::extensions const*)::work*))() const>, std::_Bind<seastar::future<> (db::commitlog::read_log_file(seastar::basic_sstring<char, unsigned int, 15u, true> const&, seastar::io_priority_class, std::function<seastar::future<> (seastar::temporary_buffer<char>, db::replay_position)>, unsigned int, db::extensions const*)::work::*(db::commitlog::read_log_file(seastar::basic_sstring<char, unsigned int, 15u, true> const&, seastar::io_priority_class, std::function<seastar::future<> (seastar::temporary_buffer<char>, db::replay_position)>, unsigned int, db::extensions const*)::work*))()> >::run_and_dispose() at commitlog.cc:?
seastar::reactor::run_tasks(seastar::reactor::task_queue&) at crtstuff.c:?
seastar::reactor::run_some_tasks() [clone .part.2743] at reactor.cc:?
seastar::reactor::run() at crtstuff.c:?
seastar::smp::configure(boost::program_options::variables_map)::{lambda()#3}::operator()() const at reactor.cc:?
seastar::posix_thread::start_routine(void*) at crtstuff.c:?
?? ??:0
?? ??:0

```

I've attached the current day's journalctl output from one node of a 3-node cluster.  You are also welcome to connect directly to our grafana dashboard with the prometheus stats at http://ec2-52-32-60-163.us-west-2.compute.amazonaws.com:3000/dashboard/db/scylla-per-server-disk-i-o-2-3?refresh=30s&orgId=1.  Thanks.

Jonathan

[backtrace.txt](https://github.com/scylladb/scylla/files/2708453/backtrace.txt)

[stall.txt](https://github.com/scylladb/scylla/files/2708449/stall.txt)

**Comment by avikivity** [comment] 2018-12-25 08:58
@elcallio this is at commitlog's `read_entry()` funciton. Are we reading super-large entries? Under what conditions can this happen?

**Comment by slivne** [comment] 2018-12-25 09:53
I tried to check the metrics for view hints and there are things that seem odd ...
![veramine_view_hints](https://user-images.githubusercontent.com/3465480/50419804-71644480-083b-11e9-8747-c96f8a40d200.png)

metrics used is this
```
sum(scylla_hints_for_views_manager_written{instance=~"[[node]]",cluster=~"$cluster|$^", dc=~"$dc", shard=~"[[shard]]"})  by ([[by]])  - sum(scylla_hints_for_views_manager_sent {instance=~"[[node]]",cluster=~"$cluster|$^", dc=~"$dc", shard=~"[[shard]]"})  by ([[by]])  
```

it seems that we are on specific node (green one) keep on sending? while we are not accumulating additional writes - does this make any sense ?

**Comment by veramine** [comment] 2018-12-25 18:05
We have some large partitions in this test.  We also add to sets or maps that previously might have had a lot of entries.  Also, this stress test does not distribute well across all partitions so one node or one shard might be getting more load than the others.  I saw at one point from the node exporter stats that one node was trying to read from disk sustained 1GB/s - that doesn't seem good.  I was also testing with an exponential backoff retry policies that tries 20 times so that could lead to amplification on a single core.

**Comment by duarten** [comment] 2018-12-26 13:59
@slivne Those metrics seem off, since they are decreasing below zero.

@avi The issue is probably that we are writing big view updates as hints, because some view replica is unavailable, which we then have read in order to send.

**Comment by slivne** [comment] 2018-12-26 14:06
they are decreasing because I am decreasing one from the other - 

how many hints written - hints sent

**Comment by avikivity** [comment] 2018-12-26 14:31
@duarten big updates, or many updates?

If the former, how big?

If the later, why are we allocating them in huge contiguous buffers?

Note that 4469f76e7c95041702de6a22f4260dcec03225 is in 3.0rc1, but maybe it doesn't extend to replay. @pdziepak ?

**Comment by duarten** [comment] 2018-12-26 14:32
@avikivity big updates, I think. @veramine mentioned some collections with many elements.

**Comment by avikivity** [comment] 2018-12-26 14:36
@veramine how big? do you have oversize allocation warnings?

**Comment by veramine** [comment] 2018-12-26 21:18
@avikivity yes, here on one of the nodes:

```
Dec 23 07:08:39 ip-172-31-42-219.us-west-2.compute.internal scylla[2518]:  [shard 2] seastar_memory - oversized allocation: 2531328 bytes, please report: at   0x7cc4e8
Dec 23 07:19:23 ip-172-31-42-219.us-west-2.compute.internal scylla[2518]:  [shard 2] seastar_memory - oversized allocation: 4173824 bytes, please report: at   0x7cc4e8
Dec 23 08:00:48 ip-172-31-42-219.us-west-2.compute.internal scylla[2518]:  [shard 0] seastar_memory - oversized allocation: 1437696 bytes, please report: at   0x7cc4e8
Dec 24 09:18:00 ip-172-31-42-219.us-west-2.compute.internal scylla[8355]:  [shard 3] seastar_memory - oversized allocation: 1572864 bytes, please report: at   0x7cc4e8
Dec 24 09:18:00 ip-172-31-42-219.us-west-2.compute.internal scylla[8355]:  [shard 3] seastar_memory - oversized allocation: 1835008 bytes, please report: at   0x7cc4e8
Dec 24 09:18:36 ip-172-31-42-219.us-west-2.compute.internal scylla[8355]:  [shard 0] seastar_memory - oversized allocation: 1572864 bytes, please report: at   0x7cc4e8
Dec 24 09:18:36 ip-172-31-42-219.us-west-2.compute.internal scylla[8355]:  [shard 0] seastar_memory - oversized allocation: 1835008 bytes, please report: at   0x7cc4e8
Dec 24 09:19:22 ip-172-31-42-219.us-west-2.compute.internal scylla[8355]:  [shard 2] seastar_memory - oversized allocation: 1572864 bytes, please report: at   0x7cc4e8
Dec 24 09:19:22 ip-172-31-42-219.us-west-2.compute.internal scylla[8355]:  [shard 2] seastar_memory - oversized allocation: 1835008 bytes, please report: at   0x7cc4e8
Dec 24 09:19:32 ip-172-31-42-219.us-west-2.compute.internal scylla[8355]:  [shard 1] seastar_memory - oversized allocation: 1572864 bytes, please report: at   0x7cc4e8
Dec 24 09:19:32 ip-172-31-42-219.us-west-2.compute.internal scylla[8355]:  [shard 1] seastar_memory - oversized allocation: 1835008 bytes, please report: at   0x7cc4e8
Dec 24 19:10:46 ip-172-31-42-219.us-west-2.compute.internal scylla[8355]:  [shard 3] seastar_memory - oversized allocation: 4194304 bytes, please report: at   0x7cc4e8
Dec 24 19:10:46 ip-172-31-42-219.us-west-2.compute.internal scylla[8355]:  [shard 2] seastar_memory - oversized allocation: 4194304 bytes, please report: at   0x7cc4e8
Dec 24 21:00:03 ip-172-31-42-219.us-west-2.compute.internal scylla[10672]:  [shard 3] seastar_memory - oversized allocation: 1081344 bytes, please report: at   0x7cc4e8
Dec 24 21:00:04 ip-172-31-42-219.us-west-2.compute.internal scylla[10672]:  [shard 3] seastar_memory - oversized allocation: 1728512 bytes, please report: at   0x7cc4e8
Dec 24 21:01:53 ip-172-31-42-219.us-west-2.compute.internal scylla[10672]:  [shard 1] seastar_memory - oversized allocation: 1572864 bytes, please report: at   0x7cc4e8
Dec 24 21:01:53 ip-172-31-42-219.us-west-2.compute.internal scylla[10672]:  [shard 1] seastar_memory - oversized allocation: 1835008 bytes, please report: at   0x7cc4e8
Dec 24 21:02:14 ip-172-31-42-219.us-west-2.compute.internal scylla[10672]:  [shard 0] seastar_memory - oversized allocation: 1572864 bytes, please report: at   0x7cc4e8
Dec 24 21:02:14 ip-172-31-42-219.us-west-2.compute.internal scylla[10672]:  [shard 0] seastar_memory - oversized allocation: 1835008 bytes, please report: at   0x7cc4e8
Dec 24 21:04:39 ip-172-31-42-219.us-west-2.compute.internal scylla[10672]:  [shard 2] seastar_memory - oversized allocation: 1572864 bytes, please report: at   0x7cc4e8
Dec 24 21:04:39 ip-172-31-42-219.us-west-2.compute.internal scylla[10672]:  [shard 2] seastar_memory - oversized allocation: 1835008 bytes, please report: at   0x7cc4e8
Dec 24 22:56:00 ip-172-31-42-219.us-west-2.compute.internal scylla[10672]:  [shard 3] seastar_memory - oversized allocation: 3559424 bytes, please report: at   0x7cc4e8
Dec 24 22:56:35 ip-172-31-42-219.us-west-2.compute.internal scylla[10672]:  [shard 2] seastar_memory - oversized allocation: 3559424 bytes, please report: at   0x7cc4e8
Dec 24 22:58:06 ip-172-31-42-219.us-west-2.compute.internal scylla[10672]:  [shard 3] seastar_memory - oversized allocation: 7221248 bytes, please report: at   0x7cc4e8
Dec 25 12:06:41 ip-172-31-42-219.us-west-2.compute.internal scylla[10672]:  [shard 1] seastar_memory - oversized allocation: 4194304 bytes, please report: at   0x7cc4e8
```

I tried decoding the stack trace reported there but I am not sure I did it right:

```
seastar::current_backtrace() at crtstuff.c:?
seastar::memory::cpu_pages::warn_large_allocation(unsigned long) at crtstuff.c:?
addr2line: Dwarf Error: found dwarf version '51205', this reader only handles version 2, 3 and 4 information.
seastar::memory::allocate(unsigned long) at crtstuff.c:?
addr2line: Dwarf Error: found dwarf version '1024', this reader only handles version 2, 3 and 4 information.
operator new(unsigned long) at ??:?
addr2line: Dwarf Error: found dwarf version '86', this reader only handles version 2, 3 and 4 information.
std::vector<ser::deletable_row_view, std::allocator<ser::deletable_row_view> >::reserve(unsigned long) at crtstuff.c:?
addr2line: Dwarf Error: found dwarf version '13', this reader only handles version 2, 3 and 4 information.
ser::mutation_partition_view::rows() const at crtstuff.c:?
addr2line: Dwarf Error: found dwarf version '36', this reader only handles version 2, 3 and 4 information.
void mutation_partition_view::do_accept<partition_builder>(column_mapping const&, partition_builder&) const at crtstuff.c:?
memtable::apply(frozen_mutation const&, seastar::lw_shared_ptr<schema const> const&, db::rp_handle&&) at crtstuff.c:?
addr2line: Dwarf Error: found dwarf version '1032', this reader only handles version 2, 3 and 4 information.
void table::do_apply<frozen_mutation const&, seastar::lw_shared_ptr<schema const> const&>(db::rp_handle&&, frozen_mutation const&, seastar::lw_shared_ptr<schema const> const&) at crtstuff.c:?
addr2line: Dwarf Error: found dwarf version '15', this reader only handles version 2, 3 and 4 information.
database::apply_in_memory(frozen_mutation const&, seastar::lw_shared_ptr<schema const>, db::rp_handle&&, std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >) at crtstuff.c:?
addr2line: Dwarf Error: found dwarf version '1800', this reader only handles version 2, 3 and 4 information.
_ZN7seastar12continuationIZNS_6futureIJN2db9rp_handleEEE4thenIZN8database20apply_with_commitlogENS_13lw_shared_ptrIK6schemaEER5tableN5utils4UUIDERK15frozen_mutationNSt6chrono10time_pointINS_12lowres_clockENSI_8durationIlSt5ratioILl1ELl1000EEEEEEEUlS3_E_NS1_IJEEEEET0_OT_EUlSU_E_JS3_EE15run_and_disposeEv at database.cc:?
addr2line: Dwarf Error: found address size '176', this reader can not handle sizes greater than '8'.
seastar::reactor::run_tasks(seastar::reactor::task_queue&) at crtstuff.c:?
addr2line: Dwarf Error: found dwarf version '1796', this reader only handles version 2, 3 and 4 information.
seastar::reactor::run_some_tasks() [clone .part.2743] at reactor.cc:?
addr2line: Dwarf Error: found dwarf version '87', this reader only handles version 2, 3 and 4 information.
seastar::reactor::run() at crtstuff.c:?
addr2line: Dwarf Error: found dwarf version '1028', this reader only handles version 2, 3 and 4 information.
seastar::smp::configure(boost::program_options::variables_map)::{lambda()#3}::operator()() const at reactor.cc:?
addr2line: Dwarf Error: found dwarf version '66', this reader only handles version 2, 3 and 4 information.
seastar::posix_thread::start_routine(void*) at crtstuff.c:?
?? ??:0
?? ??:0
```

**Comment by veramine** [comment] 2018-12-28 19:17
With a new partition scheme, we were able to resolve the oversized allocations, the 1gb+ partitions, and the stalls.  Unless any stack traces in that backtrace.txt attachment are super interesting, you can probably close this.  And we will keep an eye out for too large partitions and allocation warnings.

**Comment by slivne** [comment] 2018-12-30 11:37
thanks @veramine for the update

@duarten any luck looking at the hints for view update

**Comment by avikivity** [comment] 2018-12-30 11:42
@duarten those 4MB updates shouldn'd cause 2000 ms stalls. So something else (probably commitlog_replayer, just because it's so new) is doing something wrong. Maybe it has the regular "we limit concurrency but not memory" bug.

**Comment by duarten** [comment] 2018-12-30 11:45
@AviKivity I have a patch series to make reading commit log entries use fragmented buffers, which I'll send today. The traces point to hint replaying.

**Comment by duarten** [comment] 2018-12-30 11:46
@shlomi You mean why we send more hints than we write? I forgot to check, but there's no difference in behaviour between normal hints and view hints.

**Comment by avikivity** [comment] 2018-12-30 12:11
Looking at commitlog code, if anything it has too little concurrency - everything is serialized. This is usually okay since read-ahead and memtables can generate their own concurrency. It's only bad if we're resharding since nothing will hide the cross-shard latency.

**Comment by duarten** [comment] 2019-01-02 10:39
Oh, right. That's a lot of copying. I wonder if we could reuse the buffer where we store the commitlog entries, for the span of a commitlog file.

**Comment by avikivity** [comment] 2019-01-02 16:41
@duarten you mean freeze the mutations into a reusable buffer? probably we could, we some non-trivial work.  We could also unfreeze from a reusable buffer, with temporary_buffer::share(), but the reusability is limited (because we don't know the lifetime of the consumers).

**Comment by duarten** [comment] 2019-01-02 20:46
@avikivity I meant that instead of reading from the commitlog file into a newly allocated temporary buffer, then deserializing that into a `commitlog_entry` (which contains the `frozen_mutation`), we could reuse the same temporary buffer. `read_log_file()` could specify that the buffer is up for grabs when the future returned by the caller-supplied callback is resolved, by passing the buffer by reference instead of by value.

**Comment by duarten** [comment] 2019-01-29 14:18
I opened https://github.com/scylladb/scylla/issues/4163.

I think we can close this issue for now.

**Closed by duarten** 2019-01-29 14:18 UTC
Labels: materialized-views
