### ISSUE TITLE
large collections: Load/Throughput of each db node isn't balanced

### ISSUE THREAD

**Issue by amoskong** [scylladb/scylla#6166] opened 2020-04-09 08:01 UTC
*Installation details*
Scylla version (or git commit hash): 666.development-0.20200405.df48b5ec9d5
Cluster size: 4 * i3.4xlarge
loader: 1 * c5.xlarge
OS (RHEL/CentOS/Ubuntu/AWS AMI): ami-0d8e83b5352fe4da7 (eu-west-1)

### Description:

Load and Throughput of one db node (`longevity-large-collections-12h-lar-db-node-13892b84-3` [34.244.231.87 | 10.0.229.225]) is very low, but the numbers of other 3 db nodes are very similar.

Seed node: `longevity-large-collections-12h-lar-db-node-13892b84-1` [34.250.63.9 | 10.0.139.95] (seed: True)

Grafana snapshot: https://snapshot.raintank.io/dashboard/snapshot/yiZcEXyo4AU33T9kjPuF6z67Qn0tnqZe

![image](https://user-images.githubusercontent.com/309708/78870298-783ab900-7a78-11ea-8aa3-5535d30981e8.png)

### Test info
Job: https://jenkins.scylladb.com/job/scylla-staging/job/amos/job/longevity-large-collections-12h-clone/14/
SCT test id: 13892b84-bf1d-47d7-9110-d82dea9bc5b5

Test log:
  - Restore Monitor Stack command: $ hydra investigate show-monitor 13892b84-bf1d-47d7-9110-d82dea9bc5b5
  - Show all stored logs command: $ hydra investigate show-logs 13892b84-bf1d-47d7-9110-d82dea9bc5b5

### Workload
Profile: https://github.com/scylladb/scylla-cluster-tests/blob/master/data_dir/large_collections.yaml

- JVM_OPTION='-Xms8033M -Xmx8033M -Xmn400M' cassandra-stress user profile=/tmp/large_collections.yaml ops'(insert=3,read1=1,update1=1)' cl=QUORUM duration=720m -port jmx=6868 -mode cql3 native -rate threads=20 -node 10.0.139.95

### SCT configure:
https://github.com/scylladb/scylla-cluster-tests/blob/master/test-cases/longevity/longevity-large-collections-12h.yaml

### Special conf of Scylla:
hinted_handoff is disabled in this job for avoiding known issue : https://github.com/scylladb/scylla/issues/4935
But the unbalanced issue also exist when hinted_handoff isn't disabled.
- test id: 38696de6-ea19-4efe-93eb-dd21b5355925
- job: https://jenkins.scylladb.com/job/scylla-staging/job/amos/job/longevity-large-collections-12h-clone/13/
- grafana snapshot: https://snapshot.raintank.io/dashboard/snapshot/56eQxtJ1Ka8Y0hPuc0LONU0rGUAuCI35
  
![image](https://user-images.githubusercontent.com/309708/78872050-3e1ee680-7a7b-11ea-809c-e66e7825a215.png)

@slivne @roydahan

**Comment by slivne** [comment] 2020-04-13 23:16
Is this with experimental set true  ?

if so please disable and lets see what we get

simillar to https://github.com/scylladb/scylla/issues/6193

**Comment by slivne** [comment] 2020-04-13 23:16
Is this on 4.0 or master ?

**Comment by amoskong** [comment] 2020-04-14 02:35
> Is this with experimental set true ?

Yes.

> if so please disable and lets see what we get
> 
> simillar to #6193

I will retest by disabling cdc.

**Comment by amoskong** [comment] 2020-04-14 02:40
> Is this on 4.0 or master ?

Both.
The issue is found with master (666.development-0.20200405.df48b5ec9d5)
It also exists with `scylla-4.0.rc1-0.20200412.a8ef820f27c.x86_64`

Scylla 4.0.rc1 job:
- https://jenkins.scylladb.com/job/scylla-4.0/job/longevity/job/longevity-cdc-100gb-4h/6/
- test id: ebcc5a46-175e-4add-864e-41f4eb3fe59b
- version: scylla-4.0.rc1-0.20200412.a8ef820f27c.x86_64
- DB log: https://cloudius-jenkins-test.s3.amazonaws.com/ebcc5a46-175e-4add-864e-41f4eb3fe59b/20200413_141513/db-cluster-ebcc5a46.zip
- SCT log: https://cloudius-jenkins-test.s3.amazonaws.com/ebcc5a46-175e-4add-864e-41f4eb3fe59b/20200413_141513/sct-runner-ebcc5a46.zip

![image](https://user-images.githubusercontent.com/309708/79180303-32953c00-7e3c-11ea-998f-01f0da29efc4.png)

**Comment by roydahan** [comment] 2020-04-16 19:05
It's exactly as #6193 , data is not distributed evenly on the seed node.

**Comment by avikivity** [comment] 2020-04-19 17:23
Closing, duplicate of #6193.

**Closed by avikivity** 2020-04-19 17:23 UTC
