### ISSUE TITLE
storage_proxy::query_partition_key_range_concurrent() expects connected partition ranges

### ISSUE THREAD

**Issue by havaker** [scylladb/scylla#9167] opened 2021-08-09 11:56 UTC
`storage_proxy::query_partition_key_range_concurrent()` iterates through vnodes produced by its argument `query_ranges_to_vnodes_generator&& ranges_to_vnodes` and tries to merge them. It does so without checking if subsequent vnodes are connected to each other (`end_token(range) == start_token(next_range)`). This creates an assumption, that vnodes produced by `ranges_to_vnodes` are connected, which should be documented (by adding a comment) or checked in runtime.

**Comment by haaawk** [comment] 2021-08-09 13:14
@havaker please sent a PR ;)

**Comment by nyh** [comment] 2021-11-21 08:27
Issue #9659 is a duplicate of this issue. In that issue I wrote yet another piece code (for Alternator TTL) which ran a query with a a `partition_range_vector` having multiple disconnected token ranges, and it silently gave wrong results because the gaps between the ranges were queried as well.

I consider this a very serious issue. Our internal APIs are very complicated to use, and very sparsely documented - which means that developers (like me) cannot fully understand how these APIs work - and expect them to at least work as expected. When you see that the query API takes a `dht::partition_range_vector`, you fully expect to be able to pass any vector of partition ranges - who can guess that you are actually allowed to only have one range in that vector otherwise you'll silently get wrong results? (It's actually possible to have multiple **adjacent** ranges, but why would anyone do a query with a contiguous range split into several parts?)

Please note that although the title of this issue mentions `storage_proxy::query_partition_key_range_concurrent()`, you can have this bug without explicitly using this function: All internal query APIs - `query()`, `pager`, etc. - suffer from the same problem of incorrect results when multiple disconnected ranges are passed to them - because they all end up calling the function `query_partition_key_range_concurrent()`.

I added the "internals" tag to this issue because it affects how other Scylla developers work and how these APIs can be used internally, but it does not affect user-initiated CQL requests because those can only contain a single range (there is no "OR" in CQL).

I think there are two ways to solve this issue:
1. The best option is to lift the ban of disjoint ranges - and make the code work correctly in that case. PR #9175 by @havaker suggests that the *only* problem was the incorrect range merging, but we need to make sure that was the only bug. Because CQL doesn't exercise this case, we need to write unit tests that use disconnected ranges and make sure this case works correctly.
2. A worse option, but still better than what we have now, is to clearly document in all **upper-level** API functions that take a `partition_range_vector`, what are the limitations of that vector, and that a general vector of disconnected ranges are not allowed. We need to understand what the limitations are. Is a single range a must? Is a wrapping-range-split-into-two-ranges (as happens in Thrift) allowed? Multiple ranges if their union is connected (also, can there be an overlap)? Also if we we keep this limitation, `query_partition_key_range_concurrent()` should probably verify that this limitation is not violated, and on_internal_error. We should also have a unit test on which combinations are allowed, and which aren't allowed.

**Comment by avikivity** [comment] 2021-11-23 13:44
Is it correct that the bug is not visible in current code?

**Closed** 2021-11-23 19:46 UTC
Labels: bug, internals

**Comment by avikivity** [comment] 2022-09-08 15:11
Bug did not cause a problem for existing code (only new code), so not backporting.
