### ISSUE TITLE
commitlog_total_space_in_mb is not respected

### ISSUE THREAD

**Issue by kostja** [scylladb/scylla#6314] opened 2020-04-28 17:29 UTC
Scylla hash: 09e4f3b9173f0b976283cd616cb13da93623219b

I run a single scylla instance with --smp=1 --developer-mode=true
I have commitlog_total_space_in_mb: 256 in scylla.yaml.
I run `./cassandra-stress user profile=../cqlstress-lwt-example.yaml n=100000 n
o-warmup  ops\(insert=1\)  -node 127.0.0.1 -rate threads=10 -mode native cql3  -log file=./3.3-30-10k.log` 

I also run `truncate cqlstress_lwt_example.blogposts ;`
manually once in a while, using cqlsh console. I watch commitlog/ directory and its size:
```
kostja@hulk:~/scylla/db/commitlog$ du -sh .
609M    .
kostja@hulk:~/scylla/db/commitlog$ ls -al | wc -l
23
kostja@hulk:~/scylla/db/commitlog$ ls -a 
CommitLog-1-312411357.log
CommitLog-1-312411363.log
.lock
CommitLog-1-312411358.log
CommitLog-1-312411364.log
Recycled-CommitLog-1-312411345.log
CommitLog-1-312411337.log
CommitLog-1-312411359.log  
CommitLog-1-312411365.log  
Recycled-CommitLog-1-312411346.log
CommitLog-1-312411338.log  
CommitLog-1-312411360.log  
CommitLog-1-312411366.log  
Recycled-CommitLog-1-312411347.log
CommitLog-1-312411339.log
CommitLog-1-312411361.log
CommitLog-1-312411367.log 
Recycled-CommitLog-1-312411348.log
CommitLog-1-312411340.log  
CommitLog-1-312411362.log  
CommitLog-1-312411368.log
```

**Comment by kostja** [comment] 2020-04-28 17:35
If I increase the stress test parallelism the directory size gets even more out of hand:
kostja@hulk:~/scylla/db/commitlog$ du -sh .
1,1G    .
kostja@hulk:~/scylla/db/commitlog$ du -sh .
1,1G    .

**Comment by slivne** [comment] 2020-05-06 08:00
duplicate of #6148

**Closed by slivne** 2020-05-06 08:00 UTC
