### ISSUE TITLE
Failure to start (after stopping) a scylla node in a cluster with 1000 keyspaces & tables - commitlog_replayer - bad_alloc

### ISSUE THREAD

**Issue by roydahan** [scylladb/scylla#3155] opened 2018-01-25 23:58 UTC
*Installation details*
Scylla version (or git commit hash): 2.0.2
Cluster size: 4
OS (RHEL/CentOS/Ubuntu/AWS AMI): CentOS
Instance-type: n1-highmem-16 (16 vCPUs, 104 GB memory)

After populating 4TB into a cluster with 1000 keyspaces and each keyspace has one table, a restart to one of scylla nodes resulted in failure and not refuse to start.

The following errors and warnings appears in the logs:
```
Jan 25 13:21:51 warning|  [shard 11] commitlog_replayer - error replaying: std::bad_alloc (std::bad_alloc)
Jan 25 13:21:51 warning|  [shard 11] commitlog_replayer - error replaying: std::bad_alloc (std::bad_alloc)
Jan 25 13:21:51 warning|  [shard 11] commitlog_replayer - error replaying: std::bad_alloc (std::bad_alloc)
Jan 25 13:21:51 warning|  [shard 11] commitlog_replayer - error replaying: std::bad_alloc (std::bad_alloc)
Jan 25 13:21:51 warning|  [shard 11] commitlog_replayer - error replaying: std::bad_alloc (std::bad_alloc)
Jan 25 13:21:51 warning|  [shard 11] commitlog_replayer - error replaying: std::bad_alloc (std::bad_alloc)
Jan 25 13:21:51 warning|  [shard 11] commitlog_replayer - error replaying: std::bad_alloc (std::bad_alloc)
Jan 25 13:21:51 warning|  [shard 11] commitlog_replayer - error replaying: std::bad_alloc (std::bad_alloc)
Jan 25 13:21:51 warning|  [shard 11] commitlog_replayer - error replaying: std::bad_alloc (std::bad_alloc)
Jan 25 13:21:51 warning|  [shard 11] commitlog_replayer - error replaying: std::bad_alloc (std::bad_alloc)
Jan 25 13:21:51 warning|  [shard 11] commitlog_replayer - error replaying: std::bad_alloc (std::bad_alloc)
Jan 25 13:21:51 warning|  [shard 11] commitlog_replayer - error replaying: std::bad_alloc (std::bad_alloc)
Jan 25 13:21:51 warning|  [shard 11] commitlog_replayer - error replaying: std::bad_alloc (std::bad_alloc)
Jan 25 13:21:51 warning|  [shard 11] commitlog_replayer - error replaying: std::bad_alloc (std::bad_alloc)
Jan 25 13:21:51 warning|  [shard 11] commitlog_replayer - error replaying: std::bad_alloc (std::bad_alloc)
Jan 25 13:21:51 warning|  [shard 11] commitlog_replayer - error replaying: std::bad_alloc (std::bad_alloc)
Jan 25 13:21:51 warning|  [shard 11] commitlog_replayer - error replaying: std::bad_alloc (std::bad_alloc)
Jan 25 13:21:51 warning|  [shard 11] commitlog_replayer - error replaying: std::bad_alloc (std::bad_alloc)
Jan 25 13:21:51 warning|  [shard 11] commitlog_replayer - error replaying: std::bad_alloc (std::bad_alloc)

Jan 25 13:21:51 err    |  [shard 11] database - failed to move memtable for /var/lib/scylla/data/keyspace198/standard1-c3619bf0012211e8b1eb000000000003/keyspace198-standard1-ka-2107-Data.db to
cache: std::bad_alloc (std::bad_alloc)

Jan 25 13:22:21 warning|  [shard 6] commitlog_replayer - error replaying: std::bad_alloc (std::bad_alloc)
Jan 25 13:22:21 warning|  [shard 8] commitlog_replayer - error replaying: std::bad_alloc (std::bad_alloc)
Jan 25 13:22:21 warning|  [shard 9] commitlog_replayer - error replaying: std::bad_alloc (std::bad_alloc)
Jan 25 13:22:21 warning|  [shard 2] commitlog_replayer - error replaying: std::bad_alloc (std::bad_alloc)
Jan 25 13:22:21 warning|  [shard 1] commitlog_replayer - error replaying: std::bad_alloc (std::bad_alloc)
Jan 25 13:22:21 warning|  [shard 11] commitlog_replayer - error replaying: std::bad_alloc (std::bad_alloc)
Jan 25 13:22:21 warning|  [shard 13] commitlog_replayer - error replaying: std::bad_alloc (std::bad_alloc)
Jan 25 13:22:21 warning|  [shard 14] commitlog_replayer - error replaying: std::bad_alloc (std::bad_alloc)
Jan 25 13:22:21 warning|  [shard 6] commitlog_replayer - error replaying: std::bad_alloc (std::bad_alloc)


Jan 25 13:29:30 warning|  [shard 0] sstable - Exception when deleting sstable file: std::bad_alloc (std::bad_alloc)
Jan 25 13:29:30 warning|  [shard 0] sstable - Exception when deleting sstable file: std::bad_alloc (std::bad_alloc)
Jan 25 13:29:30 warning|  [shard 0] sstable - Exception when deleting sstable file: std::bad_alloc (std::bad_alloc)
Jan 25 13:29:30 warning|  [shard 13] sstable - Exception when deleting sstable file: std::bad_alloc (std::bad_alloc)
Jan 25 13:29:30 warning|  [shard 1] sstable - Exception when deleting sstable file: std::bad_alloc (std::bad_alloc)
Jan 25 13:29:30 warning|  [shard 15] sstable - Exception when deleting sstable file: std::bad_alloc (std::bad_alloc)
Jan 25 13:29:30 warning|  [shard 13] sstable - Exception when deleting sstable file: std::bad_alloc (std::bad_alloc)
Jan 25 13:29:30 warning|  [shard 5] sstable - Exception when deleting sstable file: std::bad_alloc (std::bad_alloc)
Jan 25 13:29:30 warning|  [shard 9] sstable - Exception when deleting sstable file: std::bad_alloc (std::bad_alloc)
Jan 25 13:29:30 warning|  [shard 15] sstable - Exception when deleting sstable file: std::bad_alloc (std::bad_alloc)
Jan 25 13:29:30 warning|  [shard 9] sstable - Exception when deleting sstable file: std::bad_alloc (std::bad_alloc)
Jan 25 13:29:30 warning|  [shard 1] sstable - Exception when deleting sstable file: std::bad_alloc (std::bad_alloc)
Jan 25 13:29:30 warning|  [shard 4] sstable - Exception when deleting sstable file: std::bad_alloc (std::bad_alloc)
Jan 25 13:29:30 warning|  [shard 9] sstable - Exception when deleting sstable file: std::bad_alloc (std::bad_alloc)
Jan 25 13:29:30 warning|  [shard 13] sstable - Exception when deleting sstable file: std::bad_alloc (std::bad_alloc)
Jan 25 13:29:30 warning|  [shard 15] sstable - Exception when deleting sstable file: std::bad_alloc (std::bad_alloc)

Jan 25 13:29:30 warning|  [shard 10] seastar - Exceptional future ignored: std::bad_alloc (std::bad_alloc), backtrace: 0x4f0173, 0x4f01d1, 0x55c22a, 0x961c74, 0x4ecda9, 0x5408ca, 0x542170, 0x59
adfd, 0x7efd598e8e24, 0x7efd5961634c
2018-01-25 13:29:30,933 remote           L0197 DEBUG| [10.142.0.12] [stdout] Jan 25 13:29:30 warning|  [shard 10] seastar - Exceptional future ignored: std::bad_alloc (std::bad_alloc), backtrace: 0x4f0173, 0x4f01d1, 0x55c22a, 0x961c74, 0x4ecda9, 0x5408ca, 0x542170, 0x59
adfd, 0x7efd598e8e24, 0x7efd5961634c
2018-01-25 13:29:30,933 remote           L0197 DEBUG| [10.142.0.12] [stdout] Jan 25 13:29:30 warning|  [shard 10] seastar - Exceptional future ignored: std::bad_alloc (std::bad_alloc), backtrace: 0x4f0173, 0x4f01d1, 0x55c22a, 0x961c74, 0x4ecda9, 0x5408ca, 0x542170, 0x59
adfd, 0x7efd598e8e24, 0x7efd5961634c
2018-01-25 13:29:30,933 remote           L0197 DEBUG| [10.142.0.12] [stdout] Jan 25 13:29:30 warning|  [shard 10] seastar - Exceptional future ignored: std::bad_alloc (std::bad_alloc), backtrace: 0x4f0173, 0x4f01d1, 0x55c22a, 0x961c74, 0x4ecda9, 0x5408ca, 0x542170, 0x59
adfd, 0x7efd598e8e24, 0x7efd5961634c
2018-01-25 13:29:30,933 remote           L0197 DEBUG| [10.142.0.12] [stdout] Jan 25 13:29:30 warning|  [shard 10] seastar - Exceptional future ignored: std::bad_alloc (std::bad_alloc), backtrace: 0x4f0173, 0x4f01d1, 0x55c22a, 0x961c74, 0x4ecda9, 0x5408ca, 0x542170, 0x59
adfd, 0x7efd598e8e24, 0x7efd5961634c


Jan 25 13:34:37 warning|  [shard 0] seastar - Exceptional future ignored: std::bad_alloc (std::bad_alloc), backtrace: 0x4f0173, 0x4f01d1, 0x55c22a, 0x4f2524, 0x4ecda9, 0x5408ca, 0x5c5834, 0x475
1ff, 0x7efd5953fc04, 0x4e8e2e
2018-01-25 13:34:37,126 remote           L0197 DEBUG| [10.142.0.12] [stdout] Jan 25 13:34:37 warning|  [shard 0] seastar - Exceptional future ignored: std::bad_alloc (std::bad_alloc), backtrace: 0x4f0173, 0x4f01d1, 0x55c22a, 0x4f2524, 0x4ecda9, 0x5408ca, 0x5c5834, 0x475
1ff, 0x7efd5953fc04, 0x4e8e2e
2018-01-25 13:34:37,126 remote           L0197 DEBUG| [10.142.0.12] [stdout] Jan 25 13:34:37 warning|  [shard 0] seastar - Exceptional future ignored: std::bad_alloc (std::bad_alloc), backtrace: 0x4f0173, 0x4f01d1, 0x55c22a, 0x4f2524, 0x4ecda9, 0x5408ca, 0x5c5834, 0x475
1ff, 0x7efd5953fc04, 0x4e8e2e
2018-01-25 13:34:37,126 remote           L0197 DEBUG| [10.142.0.12] [stdout] Jan 25 13:34:37 warning|  [shard 0] seastar - Exceptional future ignored: std::bad_alloc (std::bad_alloc), backtrace: 0x4f0173, 0x4f01d1, 0x55c22a, 0x4f2524, 0x4ecda9, 0x5408ca, 0x5c5834, 0x475
1ff, 0x7efd5953fc04, 0x4e8e2e
2018-01-25 13:34:37,127 remote           L0197 DEBUG| [10.142.0.12] [stdout] Jan 25 13:34:37 warning|  [shard 0] seastar - Exceptional future ignored: std::bad_alloc (std::bad_alloc), backtrace: 0x4f0173, 0x4f01d1, 0x55c22a, 0x4f2524, 0x4ecda9, 0x5408ca, 0x5c5834, 0x475
1ff, 0x7efd5953fc04, 0x4e8e2e
2018-01-25 13:34:37,127 remote           L0197 DEBUG| [10.142.0.12] [stdout] Jan 25 13:34:37 warning|  [shard 0] seastar - Exceptional future ignored: std::bad_alloc (std::bad_alloc), backtrace: 0x4f0173, 0x4f01d1, 0x55c22a, 0x4f2524, 0x4ecda9, 0x5408ca, 0x5c5834, 0x475
1ff, 0x7efd5953fc04, 0x4e8e2e
```

**Comment by roydahan** [comment] 2018-01-26 00:16
Full log: https://s3.amazonaws.com/scylladb-users-upload/3155/job.log.tar.gz
Prometheus Data: https://s3.amazonaws.com/scylladb-users-upload/3155/prometheus-date.tar.gz

**Comment by roydahan** [comment] 2018-01-29 12:56
Do we want to extract anything else from this cluster or I can stop it?

**Comment by roydahan** [comment] 2018-01-29 18:31
Decoded stack traces:

```
[scylla-test@longevity-1000-keyspaces-staging-db-node-9d469287-0-3 commitlog]$ addr2line -Cpife /usr/lib/debug/.build-id/01/d9880734bf6d75aa6f96bafe8b8d0f27cd9d48.debug

?? ??:0
0x4f0173
0x4f01d1
0x55c22a
0x961c74
0x4ecda9
0x5408ca
0x542170
0x59adfd
0x7efd598e8e24
0x7efd5961634c
seastar::current_backtrace() at /usr/src/debug/scylla-2.0.2/seastar/core/reactor.cc:3935
seastar::report_failed_future(std::__exception_ptr::exception_ptr) at /usr/src/debug/scylla-2.0.2/seastar/core/reactor.cc:3960
seastar::promise<>::abandoned() at /usr/src/debug/scylla-2.0.2/seastar/core/future.hh:1196
seastar::promise<>::~promise() at /usr/src/debug/scylla-2.0.2/seastar/core/future.hh:434
 (inlined by) ~<lambda> at /usr/src/debug/scylla-2.0.2/seastar/core/future.hh:945
 (inlined by) ~continuation at /usr/src/debug/scylla-2.0.2/seastar/core/future.hh:392
 (inlined by) ~continuation at /usr/src/debug/scylla-2.0.2/seastar/core/future.hh:392
std::default_delete<seastar::task>::operator()(seastar::task*) const at /opt/scylladb/include/c++/5.3.1/bits/unique_ptr.h:76
 (inlined by) std::unique_ptr<seastar::task, std::default_delete<seastar::task> >::reset(seastar::task*) at /opt/scylladb/include/c++/5.3.1/bits/unique_ptr.h:344
 (inlined by) seastar::reactor::run_tasks(seastar::circular_buffer<std::unique_ptr<seastar::task, std::default_delete<seastar::task> >, std::allocator<std::unique_ptr<seastar::task, std::default_delete<seastar::task> > > >&) at /usr/src/debug/scylla-2.0.2/seastar/core/reactor.cc:2317
seastar::reactor::run() at /usr/src/debug/scylla-2.0.2/seastar/core/reactor.cc:2774
seastar::smp::configure(boost::program_options::variables_map)::{lambda()#3}::operator()() const [clone .constprop.4244] at /usr/src/debug/scylla-2.0.2/seastar/core/reactor.cc:3707
std::function<void ()>::operator()() const at /opt/scylladb/include/c++/5.3.1/functional:2271
 (inlined by) seastar::posix_thread::start_routine(void*) at /usr/src/debug/scylla-2.0.2/seastar/core/posix.cc:52
?? ??:0
```

```
[scylla-test@longevity-1000-keyspaces-staging-db-node-9d469287-0-3 commitlog]$ addr2line -Cpife /usr/lib/debug/.build-id/01/d9880734bf6d75aa6f96bafe8b8d0f27cd9d48.debug

?? ??:0
0x4f0173,
0x4f01d1
0x55c22a
0x4f2524
0x4ecda9
0x5408ca
0x5c5834
0x4751ff
0x7efd5953fc04
0x4e8e2eseastar::current_backtrace() at /usr/src/debug/scylla-2.0.2/seastar/core/reactor.cc:3935
seastar::report_failed_future(std::__exception_ptr::exception_ptr) at /usr/src/debug/scylla-2.0.2/seastar/core/reactor.cc:3960
seastar::promise<>::abandoned() at /usr/src/debug/scylla-2.0.2/seastar/core/future.hh:1196
seastar::promise<>::~promise() at /usr/src/debug/scylla-2.0.2/seastar/core/future.hh:434
 (inlined by) ~<lambda> at /usr/src/debug/scylla-2.0.2/seastar/core/future.hh:901
 (inlined by) ~continuation at /usr/src/debug/scylla-2.0.2/seastar/core/future.hh:392
 (inlined by) ~continuation at /usr/src/debug/scylla-2.0.2/seastar/core/future.hh:392
std::default_delete<seastar::task>::operator()(seastar::task*) const at /opt/scylladb/include/c++/5.3.1/bits/unique_ptr.h:76
 (inlined by) std::unique_ptr<seastar::task, std::default_delete<seastar::task> >::reset(seastar::task*) at /opt/scylladb/include/c++/5.3.1/bits/unique_ptr.h:344
 (inlined by) seastar::reactor::run_tasks(seastar::circular_buffer<std::unique_ptr<seastar::task, std::default_delete<seastar::task> >, std::allocator<std::unique_ptr<seastar::task, std::default_delete<seastar::task> > > >&) at /usr/src/debug/scylla-2.0.2/seastar/core/reactor.cc:2317
seastar::reactor::run() at /usr/src/debug/scylla-2.0.2/seastar/core/reactor.cc:2774
seastar::app_template::run_deprecated(int, char**, std::function<void ()>&&) at /usr/src/debug/scylla-2.0.2/seastar/core/app-template.cc:142
main at /usr/src/debug/scylla-2.0.2/main.cc:682
?? ??:0
```

**Comment by roydahan** [comment] 2018-01-29 18:33
Commit log dir  on this host is 84G:

```
[scylla-test@longevity-1000-keyspaces-staging-db-node-9d469287-0-3 commitlog]$ ls -lhtr
total 84G
-rw-r--r-- 1 scylla scylla 32M Jan 25 12:22 CommitLog-1-14204.log
-rw-r--r-- 1 scylla scylla 32M Jan 25 12:22 CommitLog-1-14205.log
-rw-r--r-- 1 scylla scylla 32M Jan 25 12:22 CommitLog-1-14206.log
-rw-r--r-- 1 scylla scylla 32M Jan 25 12:23 CommitLog-1-14207.log
-rw-r--r-- 1 scylla scylla 32M Jan 25 12:23 CommitLog-1-14208.log
-rw-r--r-- 1 scylla scylla 32M Jan 25 12:23 CommitLog-1-14210.log
-rw-r--r-- 1 scylla scylla 32M Jan 25 12:24 CommitLog-1-36028797018978141.log
-rw-r--r-- 1 scylla scylla 32M Jan 25 12:24 CommitLog-1-14211.log
-rw-r--r-- 1 scylla scylla 32M Jan 25 12:24 CommitLog-1-36028797018978142.log
-rw-r--r-- 1 scylla scylla 32M Jan 25 12:24 CommitLog-1-162129586585352031.log
...
...
...
```

**Comment by roydahan** [comment] 2018-01-29 18:36
Scehma:
[desc_schema.txt](https://github.com/scylladb/scylla/files/1674793/desc_schema.txt)

**Comment by roydahan** [comment] 2018-01-30 14:34
Log from host:
[scylla-journal.log.gz](https://github.com/scylladb/scylla/files/1678063/scylla-journal.log.gz)

**Comment by elcallio** [comment] 2018-01-30 15:35
The log does not even say "now we're gonna replay", which makes me think we're somehow so badly out of memory we cannot even set up the replayer itself - i.e. build the low watermark positions mappings for tables and shards. We have no even started to parse the segments yet...

Given that there is something like 16 shards and ~1000 tables (?) the replayer itself would still just use 16 * 16k * ~100bytes or so, so it seems unlikely this is the culprit.  

The traces are unfortunately from way later in the event chain. Results of, but not the source of, the problem. I'm kinda stumped...

**Comment by roydahan** [comment] 2018-01-30 17:36
Will it help you connect the cluster?

**Comment by elcallio** [comment] 2018-02-13 12:45
Is it possible to run just the schema generation part of the test (on a single node) to try to isolate this problem a bit? Is there a repo with the test code?

**Comment by elcallio** [comment] 2018-02-13 12:46
Sorry, I meant schema + minimal data generation. Since I'm guessing it is not the commitlog data itself causing the issue.

**Comment by elcallio** [comment] 2018-02-13 13:28
Not surprisingly, just creating the above tables and inserting trivial data + kill -9 replays just fine.

**Comment by elcallio** [comment] 2018-02-13 13:31
If the problem is huge blobs in the mutations (how large is each row in the data set?), it might be we need to move the reader to use a segmented approach to avoid loading large data rows and duplicating the data several times (each mutation is read into a single buffer). 

But otoh, there should have been issues creating the data set if we have problems with the mutation sizes...

**Comment by slivne** [comment] 2018-02-20 09:13
@roydahan
 - calle tried to reproduce this on his end and failed
 - can we  reproduce this on a single server and hand over that server to calle (on AWS/GCE) - so he can look at it

**Comment by roydahan** [comment] 2018-02-20 16:16
Running the test, trying to reproduce

**Comment by roydahan** [comment] 2018-02-27 13:43
reproduced again:
(sending details)

commitlog_replayer - error replaying: std::bad_alloc (std::bad_alloc)
commitlog_replayer - error replaying: std::bad_alloc (std::bad_alloc)
commitlog_replayer - error replaying: std::bad_alloc (std::bad_alloc)
commitlog_replayer - error replaying: std::bad_alloc (std::bad_alloc)
commitlog_replayer - error replaying: std::bad_alloc (std::bad_alloc)
commitlog_replayer - error replaying: std::bad_alloc (std::bad_alloc)
commitlog_replayer - error replaying: std::bad_alloc (std::bad_alloc)
commitlog_replayer - error replaying: std::bad_alloc (std::bad_alloc)

**Comment by roydahan** [comment] 2018-03-18 09:09
Further investigating it with @slivne, we could noticed that when "emptying" the commitlog directory the issue doesn't reproduce and the node starts successfully.

In addition, when having commitlog in place, but setting the commitlog_replayer log level to DEBUG, the bad_alloc doesn't happen, but the node startup takes more than 15 mins, so it eventually fails to start due to timeout.

Looking on parallel compactions number at the time of startup, we couldn't see any suspicious number of parallel compactions at the same time.

**Comment by elcallio** [comment] 2018-03-19 09:12
As I said in another thread; You are most likely getting the OOM:s due 
to simple overload. Replay manages to generate enough in-flight 
mutations, coupled with compactions, that we (temporarily) run out of 
(contiguous) memory. Setting log level DEBUG most likely acts as a 
natural throttle on the replay speed.

Changing the replayer to run single-core or at least #cpus/x cores, x < 
#cpus, would probably "fix" the problem as well.

/C

**Comment by slivne** [comment] 2018-04-22 11:44
@roydahan lets retest this on master / 2.3

**Comment by roydahan** [comment] 2018-07-23 16:49
When retesting this on 2.3, I don't see this failure anymore.
However, after starting the "stopped" node, a different node crashed with coredump.
I'll report a different issue for that.

**Comment by elcallio** [comment] 2018-08-06 11:50
@slivne, suggest closing this issue.

**Closed** 2020-01-12 19:11 UTC
Labels: bug
