### ISSUE TITLE
Linearization of large (fragmented) keys may cause undefined behavior

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/scylla#6637] opened 2020-06-12 19:37 UTC
This is relevant only when using partition or clustering keys which have a representation in memory which is larger than 12.8 KB (10% of LSA segment size).

See https://github.com/scylladb/scylla/issues/6108 for description of linearization.

There are several places in code (cache, background garbage collection) which may need to linearize keys because of performing key comparison, but it's not done safely:
 1) the code does not run with the LSA region locked, so pointers may get invalidated on linearization if it needs to reclaim memory
 2) LSA region is locked, but the scope of `with_linearized_managed_bytes()` encloses the allocating section. It allocating section needs to reclaim, linearization context is invalidated.

Example of 1 can be found in `range_populating_reader::handle_end_of_stream()` where it performs a lookup:
```
                    auto prev = std::prev(it);
                    if (prev->key().equal(*_cache._schema, *_last_key->_key)) {
                        it->set_continuous(true);
```

but `handle_end_of_stream()` is not invoked under allocating section.

One way this can manifest is that cache may mis-populate and return wrong results as was seen in one of our unit tests with manual failure injection: https://github.com/scylladb/scylla/issues/5642#issuecomment-641656535

Example of 2 can be found in `mutation_cleaner_impl::merge_some()` where is does:

```
return with_linearized_managed_bytes([&] {
...
                return _worker_state->alloc_section(region, [&] {
```

No issue in the field has been linked to this yet.

**Comment by avikivity** [comment] 2020-06-14 07:55
I think we should drop with_linearized_managed_bytes and replace it with dual-compilation of any code that uses managed_bytes using fat pointers and int8_t* (and remove managed_bytes::data()). This is a big hammer, but allows us to avoid linearizing managed_bytes outside lsa as well, which reduces latency caused by defragmentation (std storage can use 128k as the fragment size).

Perhaps we should use a smaller hammer first, and make managed_bytes::data() call on_internal_error() if we're not in a linearization context.

**Comment by nyh** [comment] 2020-06-14 08:41
On Sun, Jun 14, 2020 at 10:55 AM Avi Kivity <notifications@github.com>
wrote:

> I think we should drop with_linearized_managed_bytes and replace it with
> dual-compilation of any code that uses managed_bytes using fat pointers and
> int8_t* (and remove managed_bytes::data()). This is a big hammer, but
> allows us to avoid linearizing managed_bytes outside lsa as well, which
> reduces latency caused by defragmentation (std storage can use 128k as the
> fragment size).
>
I wish we had docs/lsa.md, so I can read about what this means.

Perhaps we should use a smaller hammer first, and make
> managed_bytes::data() call on_internal_error() if we're not in a
> linearization context.
>
By the way, if these checks are not trivial, you can add them to debug mode
only. This might have allowed us to spot these bugs in development or
testing time, when we (sometimes) happen to run debug mode.

**Comment by avikivity** [comment] 2020-06-14 09:59
These checks are relatively cheap, but indeed they are triggered in many, many places, so perhaps debug mode is a better place.

**Comment by denesb** [comment] 2020-06-15 07:15
We already have an assert in place: https://github.com/scylladb/scylla/blob/4220ed849bebe02de5838b1e779c2b5099fe3a50/utils/managed_bytes.cc#L37

**Comment by avikivity** [comment] 2020-06-15 08:34
This assert is only triggered if you have large keys. So you only hit it in a tiny subset of workloads. 

Moving it to managed_bytes::data() will catch it much earlier, in small-key workloads.

**Comment by denesb** [comment] 2020-06-15 08:48
I think moving it to `managed_bytes::data()` would make scylla unbootable. We just have some many places where we implicitly linearise keys. One example is [validation::is_cql_key_invalid()](https://github.com/scylladb/scylla/blob/4220ed849bebe02de5838b1e779c2b5099fe3a50/validation.cc#L52), so even if scylla did start you'd only have to wait until the first query to trigger the assert.

**Comment by avikivity** [comment] 2020-06-15 09:08
We could assert only if in lsa context.

Long term we should remove data() and replace it with something that doesn't require linearization. This is quite a project though.

**Comment by denesb** [comment] 2020-06-15 11:34
> Long term we should remove data() and replace it with something that doesn't require linearization. This is quite a project though.

I wish we could do away with linearization in our code-base for good. A pre-requisite to that is our types to support de/serializing, validating and comparing directly from fragmented storage. The vast majority of types works with smallish values that could be safely linearized on-the-fly as needed. For string comparison we could use magic bytes iterators that know how to stitch together fragments. I almost started working on this once, but it then got cancelled because we made more code work with fragmented buffers better and delayed fixing the rest of the code indefinitely.

**Comment by avikivity** [comment] 2020-06-15 11:46
Serialization/deserialization isn't hard, especially if we can guarantee a minimum fragment length so the fixed-size types can assume a single fragment.

For comparison the trick isn't to use byte iterators, but to iterate on fragments and compare longest common fragment sizes.

**Comment by denesb** [comment] 2020-06-15 11:50
> Serialization/deserialization isn't hard, especially if we can guarantee a minimum fragment length so the fixed-size types can assume a single fragment.

Regardless of how large a single fragment is, an `int` in the middle might be split into two fragments. Consider a partition key that contains a frozen collection.
> 
> For comparison the trick isn't to use byte iterators, but to iterate on fragments and compare longest common fragment sizes.

Yes, this could work.

**Comment by avikivity** [comment] 2020-06-15 12:09
> > Serialization/deserialization isn't hard, especially if we can guarantee a minimum fragment length so the fixed-size types can assume a single fragment.
> 
> Regardless of how large a single fragment is, an `int` in the middle might be split into two fragments. Consider a partition key that contains a frozen collection.
> 

We could linearize those when exploding or iterating.

**Comment by denesb** [comment] 2020-06-15 12:21
> > > Serialization/deserialization isn't hard, especially if we can guarantee a minimum fragment length so the fixed-size types can assume a single fragment.
> > 
> > 
> > Regardless of how large a single fragment is, an `int` in the middle might be split into two fragments. Consider a partition key that contains a frozen collection.
> 
> We could linearize those when exploding or iterating.

Yes, that's what I meant above.

We can even have allocation-safe linearization with stack-buffers:
```c++
// Returns a view on the buffer directly, or linearizes into the linearization_buffer
typename <size_t N, FragmentedRange Buffer>
bytes_view read(const Buffer& buf, std::array<byte, N>& linearization_buffer) noexcept;

int deserialize(fragmented_temporary_buffer<char>& buf) noexcept {
    std::array<byte, sizeof(int)> linearization_buf;
    auto view = read<4>(buf, linearization_buf);
    // 
}
```

**Comment by tgrabiec** [comment] 2020-06-15 13:20
The problem in `handle_end_of_stream()` should never cause undefined behavior in production but rather trigger the assert in `managed_bytes::do_linearize()` due to absence of linearization context. The unit test is more eager to inject memory reclamation, it does so even for keys which don't require linearization, that's why it triggers undefined behavior and not the assert.

This means that we either have no customers which have fragmented partition keys, or they don't do scans.

**Closed** 2020-06-15 23:20 UTC
Labels: Backport candidate, Correctness, bug

**Comment by avikivity** [comment] 2020-06-21 09:12
Backported to 3.3, 4.0, 4.1.
