### ISSUE TITLE
Cannot compile on Arch Linux

### ISSUE THREAD

**Issue by xero-lib** [scylladb/scylla#7974] opened 2021-01-27 19:37 UTC
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [*] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash): Latest
Cluster size: N/A
OS (RHEL/CentOS/Ubuntu/AWS AMI): Arch Linux

makepkg from the AUR:
![image](https://user-images.githubusercontent.com/54485853/106043586-41d03800-60a4-11eb-81ea-7e449e5fce7a.png)
([full log](https://github.com/scylladb/scylla/files/5882645/makepkg.log))

Cannot compile as directed on website due to ninja-build not being a thing on Arch Linux, the only command is Ninja, which outputs [this](https://github.com/scylladb/scylla/files/5882597/output.log)

**Comment by psarna** [comment] 2021-01-28 07:30
I can confirm that current master does not build on arch, for several reasons:
1. Outdated rapidjson in the repository - fixable by installing rapidjson-git from AUR
2. Outdated antlr3 - I didn't manage to find a fixed package anywhere, so perhaps one should build antlr3 from the latest source - I haven't tried that yet
3. A couple of warnings treated as errors, both with g++ and clang++ - can be worked around by removing `-Werror` from configure.py manually
4. A couple of actual errors, like missing headers - can be fixed in the source code by adding appropriate include directives

Right now the biggest showstopper is antlr3, because the code it generates does not conform to C++20 requirements and thus does not compile. Since Scylla already relies on several C++20 features, it's not possible to just use C++17.

Given that and the fact that Arch Linux is not on our official support list, the only quick way of compiling Scylla would be to use our frozen toolchain (dbuild), which is docker-based and contains all needed dependencies. The instructions are here: https://github.com/scylladb/scylla/blob/master/README.md#building-scylla

**Comment by nyh** [comment] 2021-01-28 08:30
> Right now the biggest showstopper is antlr3, because the code it generates does not conform to C++20 requirements and thus does not compile. Since Scylla already relies on several C++20 features, it's not possible to just use C++17.

Can't we compile just the Antlr3 output with C++17 parameters? It's ugly, but I think could be a simple workaround - if we weren't so pleased with that other workaround we invented (and you described) - dbuild.

**Comment by psarna** [comment] 2021-01-28 08:55
Yeah, there's a good chance it will work. I privately still prefer to be able to compile in a docker-free environment, but in this case dtest is probably the best solution, at least until the repository catches up with more recent dependencies - especially that the things I listed might not be the only issues, they were just first to occur during a compilation attempt.

**Comment by xero-lib** [comment] 2021-02-03 05:57
So I thought the point of production was to not use a docker. Does this compile to the host somehow? And if so, how do I use it afterwards?

**Comment by xero-lib** [comment] 2021-02-03 06:27
As well, when compiling from those instructions, I get this error: 
![image](https://user-images.githubusercontent.com/54485853/106707261-8bde7f80-65b6-11eb-9a2b-2c268556c577.png)

**Comment by xero-lib** [comment] 2021-02-03 06:31
And I don't have SELinux enabled.

**Comment by psarna** [comment] 2021-02-03 06:36
> So I thought the point of production was to not use a docker. Does this compile to the host somehow? And if so, how do I use it afterwards?

Building a relocatable package ( https://github.com/scylladb/scylla/blob/9eed26ca3d82dadef4cf7c4034cc39bfe5d94c70/docs/guides/building.md#packaging ) will let you create a package with all dependencies needed to run scylla, along with matching libraries.

**Comment by xero-lib** [comment] 2021-02-03 06:38
> > So I thought the point of production was to not use a docker. Does this compile to the host somehow? And if so, how do I use it afterwards?
> 
> Building a relocatable package ( https://github.com/scylladb/scylla/blob/9eed26ca3d82dadef4cf7c4034cc39bfe5d94c70/docs/guides/building.md#packaging ) will let you create a package with all dependencies needed to run scylla, along with matching libraries.

I see... And what of it not compiling? Also, if you have discord, it would be easier to do a closer debug of some of this stuff (as well as I think you're just a genuinely good person). I realize it's rather unprofessional, but if you wanted to add me, my handle is Silence#6134

**Comment by psarna** [comment] 2021-02-03 06:49
> > > So I thought the point of production was to not use a docker. Does this compile to the host somehow? And if so, how do I use it afterwards?
> > 
> > 
> > Building a relocatable package ( https://github.com/scylladb/scylla/blob/9eed26ca3d82dadef4cf7c4034cc39bfe5d94c70/docs/guides/building.md#packaging ) will let you create a package with all dependencies needed to run scylla, along with matching libraries.
> 
> I see... And what of it not compiling?

If Scylla does not compile with frozen toolchain then it's a bug which should be fixed. Can you attach a log of the failed build (preferably in text form)? The error message you sent a couple of messages above was actually from not being able to **run** Scylla due to the kernel configuration, so I assume that the compilation itself succeeded, otherwise there wouldn't be a binary (build/release/scylla) to run.

> Also, if you have discord, 

I don't :) For quick communication we use our official slack channel ( https://scylladb-users.slack.com/ ), but in case of Scylla issues it's actually better to use github in order to let other people with similar issues find a solution.

> it would be easier to do a closer debug of some of this stuff (as well as I think you're just a genuinely good person). I realize it's rather unprofessional, but if you wanted to add me, my handle is Silence#6134

**Comment by xero-lib** [comment] 2021-02-03 07:02
> > > > So I thought the point of production was to not use a docker. Does this compile to the host somehow? And if so, how do I use it afterwards?
> > > 
> > > 
> > > Building a relocatable package ( https://github.com/scylladb/scylla/blob/9eed26ca3d82dadef4cf7c4034cc39bfe5d94c70/docs/guides/building.md#packaging ) will let you create a package with all dependencies needed to run scylla, along with matching libraries.
> > 
> > 
> > I see... And what of it not compiling?
> 
> If Scylla does not compile with frozen toolchain then it's a bug which should be fixed. Can you attach a log of the failed build (preferably in text form)? The error message you sent a couple of messages above was actually from not being able to **run** Scylla due to the kernel configuration, so I assume that the compilation itself succeeded, otherwise there wouldn't be a binary (build/release/scylla) to run.
> 
> > Also, if you have discord,
> 
> I don't :) For quick communication we use our official slack channel ( https://scylladb-users.slack.com/ ), but in case of Scylla issues it's actually better to use github in order to let other people with similar issues find a solution.
> 
> > it would be easier to do a closer debug of some of this stuff (as well as I think you're just a genuinely good person). I realize it's rather unprofessional, but if you wanted to add me, my handle is [REDACTED]

I see. Well then it compiled but will not run. What might be done about this?
Also, please remove my discord handle from your message for potential harassment reasons.

**Comment by avikivity** [comment] 2021-02-03 07:58
> > Right now the biggest showstopper is antlr3, because the code it generates does not conform to C++20 requirements and thus does not compile. Since Scylla already relies on several C++20 features, it's not possible to just use C++17.
> 
> Can't we compile just the Antlr3 output with C++17 parameters? It's ugly, but I think could be a simple workaround - if we weren't so pleased with that other workaround we invented (and you described) - dbuild.

The antlr3 output includes our headers, so it likely won't work.

Why not patch the arch sources? That's what I do with Fedora packages that have bugs.

**Comment by xero-lib** [comment] 2021-02-03 08:23
> > > Right now the biggest showstopper is antlr3, because the code it generates does not conform to C++20 requirements and thus does not compile. Since Scylla already relies on several C++20 features, it's not possible to just use C++17.
> > 
> > 
> > Can't we compile just the Antlr3 output with C++17 parameters? It's ugly, but I think could be a simple workaround - if we weren't so pleased with that other workaround we invented (and you described) - dbuild.
> 
> The antlr3 output includes our headers, so it likely won't work.
> 
> Why not patch the arch sources? That's what I do with Fedora packages that have bugs.

what headers are used and where can I download them.

**Comment by avikivity** [comment] 2021-02-03 09:07
https://src.fedoraproject.org/rpms/antlr3/c/f1bb8d639678047935e1761c3bf3c1c7da8d0f1d?branch=master

**Comment by avikivity** [comment] 2021-02-03 09:10
> > > > Right now the biggest showstopper is antlr3, because the code it generates does not conform to C++20 requirements and thus does not compile. Since Scylla already relies on several C++20 features, it's not possible to just use C++17.
> > > 
> > > 
> > > Can't we compile just the Antlr3 output with C++17 parameters? It's ugly, but I think could be a simple workaround - if we weren't so pleased with that other workaround we invented (and you described) - dbuild.
> > 
> > 
> > The antlr3 output includes our headers, so it likely won't work.
> > Why not patch the arch sources? That's what I do with Fedora packages that have bugs.
> 
> what headers are used and where can I download them.

I meant that the output of antlr3 contains #include "scylla-header-files.hh", so you can't compile that output in C++17 mode like @nyh suggested.

**Comment by avikivity** [comment] 2021-02-03 09:11
I'm closing this bug as too generic. To build on arch, fix arch dependencies (rapidjson, antlr3) to work with C++20. If problems remain, open a specific bug for each problem, not "Cannot compile".

**Closed by avikivity** 2021-02-03 09:11 UTC
