### ISSUE TITLE
Unsupported operation

### ISSUE THREAD

**Issue by mbiamont** [scylladb/scylla#3231] opened 2018-02-24 22:54 UTC
## Installation details
|   |   |
|---|---|
|  Scylla version |   2.1.0-0.20180216.58b90ceee |
| OS  | Docker |
| Experimental enabled  | Yes |

## Issue

While I try to perform a very simple `WHERE column > value`; I get an error `unsupported operation`.
Like in : ` SELECT * FROM mykeyspace.mycolumn WHERE note > 3;`

## How to reproduce

```cql
CREATE KEYSPACE mykeyspace WITH replication = {'class': 'SimpleStrategy', 'replication_factor': '1'}  AND durable_writes = true;

CREATE TABLE IF NOT EXISTS mykeyspace.mycolumn (
	uuid text PRIMARY KEY,
	owner text,
	note double);
CREATE INDEX mycolumn_note ON mykeyspace.mycolumn (note);

INSERT INTO mykeyspace.mycolumn (uuid, owner, note) VALUES ( 'xx', 'Scylla', 18.6);
SELECT * FROM mykeyspace.mycolumn WHERE note > 3 ;

```

**Comment by tzach** [comment] 2018-02-25 07:48
Thanks for reporting
A better error message will be (From Apache Cassandra 3.11)
```
InvalidRequest: Error from server: code=2200 [Invalid query] message="Cannot execute this query as it might involve data filtering and thus may have unpredictable performance. If you want to execute this query despite the performance unpredictability, use ALLOW FILTERING"
```
Apache Cassandra does return an answer when ` ALLOW FILTERING` is used, Scylla 2.1 does not.

@mbiamont, please note that this is probably a wrong data modeling. Partitions keys in Scylla (and Apache Cassandra) are not ordered so a range query on a partition key cannot work in a reasonable time. Same is true for the secondary index.

**Comment by tzach** [comment] 2018-02-26 09:52
> ALLOW_FILTERING didn't change the result.

This is indeed a gap. @penberg ?

>  which data modeling should I use? I only must select the rows where the note are above a certain value.

You can only order (sort) by value using clustering key inside a partition. Ordering across partitions will require reads from all nodes and will not scale[1]. It is possible to run such queries using external tools like Presto or Spark, but they will load most of the data to order it.

[1] This is why ordered partitions is not recommended

**Comment by mbiamont** [comment] 2018-02-28 15:38
Hello, still no answer ?

(PS : I saw in my previous answer I said `ALLOW_FILTERING`, but of course I wanted to say `ALLOW FILTERING`, see my CQL request).

**Comment by penberg** [comment] 2018-03-01 14:51
Secondary indexes in Scylla are currently limited to equals operator and unfortunately Scylla doesn't support `ALLOW FILTERING` at the moment: https://github.com/scylladb/scylla/issues/2200

**Comment by mbiamont** [comment] 2018-03-02 14:44
OK, thanks for the information.
But, in your documentation, you use filters (like `>` or `<=`) and you use `ALLOW FILTERING`

http://docs.scylladb.com/getting-started/dml/#select-statement
http://docs.scylladb.com/getting-started/dml/#allow-filtering


Also, do you know when the `>` operator will be implemented ? 
It doesn't seem complicated if you already have the `=` (or maybe I'm wrong).

**Comment by nyh** [comment] 2018-04-22 13:11
@slivne  I think you should remove the "sec index" tag from this issue. It is an "ALLOW FILTERING" issue, but not a secondary index issue, and a secondary index would not have helped as far as I can tell (an implementation like SASI could, but this is not what we have planned now).

**Comment by tzach** [comment] 2018-04-24 10:17
@nyh so this is not a bug, and not Apache Cassandra compatibility issue (C* does not support it either) rather a possible enhancement. Is it the case?

**Comment by nyh** [comment] 2018-04-24 10:24
@tzach maybe I'm misunderstanding something, but this is a bug - first that without "ALLOW FILTERING" the user doesn't get an informative message, and second, that with "ALLOW FILTERING" it doesn't work but apparently (?) it does work in Cassandra. Maybe the second part is a dup of #2200 - @penberg ?

**Comment by ndelvalle** [comment] 2018-08-01 21:31
Is this supported on 2.2 (Current) version?

**Comment by penberg** [comment] 2018-12-27 14:55
I tested @mbiamont's CQL query and it works with 3.0-rc3. @psarna can you please point us to the git commit that implements the functionality so that we can close the issue?

/cc @tzach

**Comment by psarna** [comment] 2019-01-02 11:11
c126b0079

**Closed** 2019-01-15 23:16 UTC
Labels: bug, cassandra 2.2 compatibility
