### ISSUE TITLE
core dump when selecting system.views_builds_in_progress

### ISSUE THREAD

**Issue by wangxuanyue** [scylladb/scylla#5565] opened 2020-01-08 07:45 UTC
Installation details
Scylla version (or git commit hash): 3.1.2-0.20191127.9d78d848e
Cluster size: 3
OS : CentOS7.4
Platform : physical

I'm sorry, my English is not good.

When creating a MV(Global Secondary Index，1 billion data) and run :
 select * from system.views_builds_in_progress;

Scylla server is core dump(all node):

```
Jan 08 09:47:56 sdb1 scylla[2844]: scylla: mutation_partition.cc:1230: void row::append_cell(column_id, atomic_cell_or_collection): Assertion `_storage.vector.v.size() <= id' failed.
Jan 08 09:47:56 sdb1 scylla[2844]: Aborting on shard 1.
Jan 08 09:47:56 sdb1 scylla[2844]: Backtrace:
Jan 08 09:47:56 sdb1 scylla[2844]: 0x00000000041df5e2
Jan 08 09:47:56 sdb1 scylla[2844]: 0x00000000040cc8f5
Jan 08 09:47:56 sdb1 scylla[2844]: 0x00000000040ccbf5
Jan 08 09:47:56 sdb1 scylla[2844]: 0x00000000040ccca3
Jan 08 09:47:56 sdb1 scylla[2844]: 0x00007f82a634102f
Jan 08 09:47:56 sdb1 scylla[2844]: /opt/scylladb/libreloc/libc.so.6+0x000000000003853e
Jan 08 09:47:56 sdb1 scylla[2844]: /opt/scylladb/libreloc/libc.so.6+0x0000000000022894
Jan 08 09:47:56 sdb1 scylla[2844]: /opt/scylladb/libreloc/libc.so.6+0x0000000000022768
Jan 08 09:47:56 sdb1 scylla[2844]: /opt/scylladb/libreloc/libc.so.6+0x00000000000309f5
Jan 08 09:47:56 sdb1 scylla[2844]: 0x0000000000ee4dad
Jan 08 09:47:56 sdb1 scylla[2844]: 0x0000000000fe559c
Jan 08 09:47:56 sdb1 scylla[2844]: 0x0000000000fe7d45
Jan 08 09:47:56 sdb1 scylla[2844]: 0x0000000000e49e81
Jan 08 09:47:56 sdb1 scylla[2844]: 0x000000000111ef41
Jan 08 09:47:56 sdb1 scylla[2844]: 0x0000000001d667da
Jan 08 09:47:56 sdb1 scylla[2844]: 0x00000000040c9dc1
Jan 08 09:47:56 sdb1 scylla[2844]: 0x00000000040c9fde
Jan 08 09:47:56 sdb1 scylla[2844]: 0x00000000041abd6d
Jan 08 09:47:56 sdb1 scylla[2844]: 0x00000000041d63db
Jan 08 09:47:56 sdb1 scylla[2844]: 0x000000000409809d
Jan 08 09:47:56 sdb1 scylla[2844]: /opt/scylladb/libreloc/libpthread.so.0+0x000000000000858d
Jan 08 09:47:56 sdb1 scylla[2844]: /opt/scylladb/libreloc/libc.so.6+0x00000000000fd6a2
```

**Comment by bhalevy** [comment] 2020-01-08 08:37
@wangxuanyue Do you have the core dump and can you share the sstable that triggers this? (if you can identify it from the nodes log)

```
$ awk '{print $6}' | addr2line -Cfpie libexec/scylla 
Jan 08 09:47:56 sdb1 scylla[2844]: 0x0000000000ee4dad
Jan 08 09:47:56 sdb1 scylla[2844]: 0x0000000000fe559c
Jan 08 09:47:56 sdb1 scylla[2844]: 0x0000000000fe7d45
Jan 08 09:47:56 sdb1 scylla[2844]: 0x0000000000e49e81
Jan 08 09:47:56 sdb1 scylla[2844]: 0x000000000111ef41
Jan 08 09:47:56 sdb1 scylla[2844]: 0x0000000001d667da
Jan 08 09:47:56 sdb1 scylla[2844]: 0x00000000040c9dc1
Jan 08 09:47:56 sdb1 scylla[2844]: 0x00000000040c9fde
Jan 08 09:47:56 sdb1 scylla[2844]: 0x00000000041abd6d
Jan 08 09:47:56 sdb1 scylla[2844]: 0x00000000041d63db
Jan 08 09:47:56 sdb1 scylla[2844]: 0x000000000409809d
row::append_cell(unsigned int, atomic_cell_or_collection) at crtstuff.c:?
void (anonymous namespace)::read_and_visit_row<void mutation_partition_view::do_accept<partition_builder>(column_mapping const&, partition_builder&) const::cell_visitor>(ser::row_view, column_mapping const&, column_kind, partition_builder&&) [clone .constprop.1667] at mutation_partition_view.cc:?
void mutation_partition_view::do_accept<partition_builder>(column_mapping const&, partition_builder&) const at crtstuff.c:?
frozen_mutation::unfreeze(seastar::lw_shared_ptr<schema const>) const at crtstuff.c:?
to_data_query_result(reconcilable_result const&, seastar::lw_shared_ptr<schema const>, query::partition_slice const&, unsigned int, unsigned int, query::result_options) at crtstuff.c:?
_ZN7seastar12continuationIZZNS_6futureIJNS_11foreign_ptrINS_13lw_shared_ptrI19reconcilable_resultEEEE17cache_temperatureEE9then_implIZN7service13storage_proxy18query_result_localENS3_IK6schemaEENS3_IN5query12read_commandEEERK17nonwrapping_rangeIN3dht13ring_positionEENSF_14result_optionsEN7tracing15trace_state_ptrENSt6chrono10time_pointINS_12lowres_clockENSR_8durationIlSt5ratioILl1ELl1000EEEEEEmEUlOS6_OS7_E0_NS1_IJNS2_INS3_INSF_6resultEEEEES7_EEEEET0_OT_ENKUlvE_clEvEUlS18_E_JS6_S7_EE15run_and_disposeEv at storage_proxy.cc:?
seastar::reactor::run_tasks(seastar::reactor::task_queue&) at crtstuff.c:?
seastar::reactor::run_some_tasks() [clone .part.2860] at reactor.cc:?
seastar::reactor::run() at crtstuff.c:?
seastar::smp::configure(boost::program_options::variables_map, seastar::reactor_config)::{lambda()#3}::operator()() const at reactor.cc:?
seastar::posix_thread::start_routine(void*) at crtstuff.c:?
```

Cc @denesb

**Comment by bhalevy** [comment] 2020-01-08 08:39
Did this happen following a (failed) repair?

**Comment by denesb** [comment] 2020-01-08 09:54
@bhalevy the crash happens while scanning `system.views_builds_in_progress` which is a system table, written and updated by the view building code.
@wangxuanyue can you please share all sstables for the `system.views_builds_in_progress` table? They should be few and relatively small.

**Comment by wangxuanyue** [comment] 2020-01-08 11:09
@denesb @bhalevy 

This problem can be reproduced, the steps are as follows:

step1 : create keyspace and table
```
CREATE KEYSPACE keyspace1 WITH replication = {'class': 'NetworkTopologyStrategy', 'dc_zrr' : 3}  AND durable_writes = true;

CREATE TABLE keyspace1.standard1 (
    key blob PRIMARY KEY,
    "C0" blob,
    "C1" blob,
    "C2" blob,
    "C3" blob,
    "C4" blob
) WITH COMPACT STORAGE
    AND bloom_filter_fp_chance = 0.01
    AND caching = {'keys': 'ALL', 'rows_per_partition': 'ALL'}
    AND comment = 'zrr benchmark'
    AND compaction = {'class': 'LeveledCompactionStrategy'}
    AND compression = {'sstable_compression': 'org.apache.cassandra.io.compress.LZ4Compressor'}
    AND crc_check_chance = 1.0
    AND dclocal_read_repair_chance = 0.1
    AND default_time_to_live = 0
    AND gc_grace_seconds = 864000
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair_chance = 0.0
    AND speculative_retry = '99.0PERCENTILE';
```
step2 : run cassandra-stress write data into 
```
cassandra-stress write duration=10m no-warmup cl=QUORUM -pop seq=0..1000000000 -node 10.128.202.11,10.128.202.12,10.128.202.13 -port native=9042 -rate threads=500 -mode native cql3
```

step3 : after cassandra-stress finished, create index
```
CREATE INDEX ON keyspace1.standard1 ("C0")
```
step4 : Don't wait for background index creation to complete，run select
```
select * from system.views_builds_in_progress;
```

then scylla coordination node core dump

**Comment by denesb** [comment] 2020-01-10 09:25
@wangxuanyue I managed to reproduce with your steps. Thanks for the reproducer!

**Comment by denesb** [comment] 2020-01-10 09:25
I used `SimpleStrategy` instead of `NetworkTopologyStrategy`.

**Comment by denesb** [comment] 2020-01-15 14:49
The issue is caused by `db::view::build_progress_virtual_reader`, which strips a postfix (`cpu_id`) of the clustering key of the underlying `scylla_views_builds_in_progress` table, causing all shard-specific entries to share the same clustering key. This violates the monotonicity requirements w.r.t. the fragment stream, tripping the assert in `row::append_cell`. I seem to remember this problem being discussed in the past but can't find any issues related to it now.

See https://github.com/scylladb/scylla/blob/c8a5a27bd9c25db423673edf77e0b0d991df8fc2/db/view/build_progress_virtual_reader.hh#L40-L52.

**Comment by denesb** [comment] 2020-01-15 14:53
With a little digging I found this: https://github.com/scylladb/scylla/issues/4524, fixed in 85a3a4b4584e723b54370320463df25ff7fa3327.

**Comment by denesb** [comment] 2020-01-15 14:54
```
$ git branch --all --contains 85a3a4b4584e723b54370320463df25ff7fa3327 | grep branch
  remotes/origin/branch-3.2
```
The fix was not backported to 3.1.

**Comment by bhalevy** [comment] 2020-01-19 08:16
@scylladb/scylla-maint please consider backporting 85a3a4b4584e723b54370320463df25ff7fa3327 to 3.1

**Comment by bhalevy** [comment] 2020-01-20 14:09
871d1ebdd59ec241da7280bdb292cfe515e32fc8 is queued in next-3.1

**Comment by avikivity** [comment] 2020-01-20 15:11
So, is this a duplicate of #4524 ?

**Comment by denesb** [comment] 2020-01-20 15:17
Yes.

**Comment by avikivity** [comment] 2020-01-20 16:09
Closing as dupicate of #4524.

**Closed by avikivity** 2020-01-20 16:09 UTC
Labels: Backport 3.1, Backport candidate, bug
