### ISSUE TITLE
Scylla 3.0 AMI fails to start on i3.metal - Assertion `r >= 0' failed

### ISSUE THREAD

**Issue by roydahan** [scylladb/scylla#3842] opened 2018-10-11 22:08 UTC
*Installation details*
Scylla version (or git commit hash): 3.0.rc0-0.20181010.eb2814067
Cluster size: 1 i3.metal
OS (RHEL/CentOS/Ubuntu/AWS AMI): AWS AMI (ami-005df5afd263dc997)

Errors when starting scylla:

```
[centos@ip-172-30-0-109 ~]$ addr2line -Cpife /usr/lib/debug/.build-id/a1/8811da2e9e91ed0c85a99540601485700860fa.debug

?? ??:0
0x00000000006a7442
0x00000000005beb6c
0x00000000005bee15
0x00000000005beec3
/lib64/libpthread.so.0+0x000000000000f6cf
/lib64/libc.so.6+0x0000000000036276
/lib64/libc.so.6+0x0000000000037967
/lib64/libc.so.6+0x000000000002f095
/lib64/libc.so.6+0x000000000002f141
0x0000000000670f30
0x00000000006720a5
0x00000000006725a1
0x0000000000755d5d
/lib64/libpthread.so.0+0x0000000000007e24
/lib64/libc.so.6+0x00000000000febacstd::string::_Rep::_S_create(unsigned long, unsigned long, std::allocator<char> const&) at /opt/scylladb/include/c++/7/bits/basic_string.tcc:1036
 (inlined by) std::string::_Rep::_M_clone(std::allocator<char> const&, unsigned long) at /opt/scylladb/include/c++/7/bits/basic_string.tcc:1078
 (inlined by) std::string::_Rep::_M_grab(std::allocator<char> const&, std::allocator<char> const&) at /opt/scylladb/include/c++/7/bits/basic_string.h:3223
 (inlined by) std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(std::string const&) at /opt/scylladb/include/c++/7/bits/basic_string.tcc:613
 (inlined by) boost::any::holder<std::string>::clone() const at /opt/scylladb/include/boost/any.hpp:173
 (inlined by) boost::any::any(boost::any const&) at /opt/scylladb/include/boost/any.hpp:54
 (inlined by) boost::program_options::variable_value::variable_value(boost::any const&, bool) at /opt/scylladb/include/boost/program_options/variables_map.hpp:62
 (inlined by) seastar::app_template::run_deprecated(int, char**, std::function<void ()>&&) at /usr/src/debug/scylla-3.0.rc0/seastar/core/app-template.cc:161
__atomic_add_single at /opt/scylladb/include/c++/7/ext/atomicity.h:74
 (inlined by) __atomic_add_dispatch at /opt/scylladb/include/c++/7/ext/atomicity.h:98
 (inlined by) std::string::_Rep::_M_refcopy() at /opt/scylladb/include/c++/7/bits/basic_string.h:3265
 (inlined by) std::string::_Rep::_M_grab(std::allocator<char> const&, std::allocator<char> const&) at /opt/scylladb/include/c++/7/bits/basic_string.h:3223
 (inlined by) std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(std::string const&) at /opt/scylladb/include/c++/7/bits/basic_string.tcc:613
 (inlined by) boost::system::system_error::system_error(boost::system::system_error const&) at /opt/scylladb/include/boost/system/system_error.hpp:22
 (inlined by) boost::thread_exception::thread_exception(boost::thread_exception const&) at /opt/scylladb/include/boost/thread/exceptions.hpp:36
 (inlined by) boost::exception_detail::error_info_injector<boost::thread_exception>::error_info_injector(boost::exception_detail::error_info_injector<boost::thread_exception> const&) at /opt/scylladb/include/boost/exception/exception.hpp:348
 (inlined by) boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::thread_exception> >::clone_impl(boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::thread_exception> > const&, boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::thread_exception> >::clone_tag) at /opt/scylladb/include/boost/exception/exception.hpp:470
 (inlined by) boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::thread_exception> >::clone() const at /opt/scylladb/include/boost/exception/exception.hpp:493
virtual thunk to boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::lock_error> >::clone() const at ??:?
virtual thunk to boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::lock_error> >::clone() const at ??:?
?? ??:0
?? ??:0
?? ??:0
?? ??:0
?? ??:0
seastar::scollectd::type_instance_id::truncate(seastar::basic_sstring<char, unsigned int, 15u, true>&, char const*) at /usr/src/debug/scylla-3.0.rc0/seastar/core/scollectd.hh:309
 (inlined by) seastar::scollectd::type_instance_id::type_instance_id(seastar::basic_sstring<char, unsigned int, 15u, true>, seastar::basic_sstring<char, unsigned int, 15u, true>, seastar::basic_sstring<char, unsigned int, 15u, true>, seastar::basic_sstring<char, unsigned int, 15u, true>) at /usr/src/debug/scylla-3.0.rc0/seastar/core/scollectd.hh:325
 (inlined by) seastar::scollectd::plugin_instance_metrics::add_impl(seastar::scollectd::typed_value const&) at /usr/src/debug/scylla-3.0.rc0/seastar/core/scollectd.cc:569
 (inlined by) seastar::scollectd::plugin_instance_metrics::add(seastar::scollectd::typed_value const&) at /usr/src/debug/scylla-3.0.rc0/seastar/core/scollectd.cc:575
seastar::scollectd::impl::start(seastar::basic_sstring<char, unsigned int, 15u, true> const&, seastar::ipv4_addr const&, std::chrono::duration<long, std::ratio<1l, 1000l> >) at /usr/src/debug/scylla-3.0.rc0/seastar/core/scollectd.cc:342
seastar::basic_sstring<char, unsigned int, 15u, true>::~basic_sstring() at /usr/src/debug/scylla-3.0.rc0/seastar/core/sstring.hh:255
 (inlined by) make_gauge<seastar::scollectd::impl::start(const sstring&, const seastar::ipv4_addr&, seastar::scollectd::duration)::<lambda()> > at /usr/src/debug/scylla-3.0.rc0/seastar/core/metrics.hh:399
 (inlined by) seastar::scollectd::impl::start(seastar::basic_sstring<char, unsigned int, 15u, true> const&, seastar::ipv4_addr const&, std::chrono::duration<long, std::ratio<1l, 1000l> >) at /usr/src/debug/scylla-3.0.rc0/seastar/core/scollectd.cc:362
seastar::future<>::~future() at /usr/src/debug/scylla-3.0.rc0/seastar/core/future.hh:837
 (inlined by) seastar::rpc::connection::send_negotiation_frame(std::map<seastar::rpc::protocol_features, seastar::basic_sstring<char, unsigned int, 15u, true>, std::less<seastar::rpc::protocol_features>, std::allocator<std::pair<seastar::rpc::protocol_features const, seastar::basic_sstring<char, unsigned int, 15u, true> > > >) at /usr/src/debug/scylla-3.0.rc0/seastar/rpc/rpc.cc:172
?? ??:0
```

**Comment by amnonh** [comment] 2018-10-21 12:10
I've just try to run on bare metal, I see that the error is:
Oct 21 11:34:28 ip-172-30-0-150.ec2.internal scylla[2463]: scylla: core/reactor.cc:561: seastar::reactor::reactor(unsigned int): Assertion `r >= 0' failed.

This is an assert that is caused by a call to io_setup failure.
and is part of the reactor initialization (my guess probably number of io queues).

@slivne please let me know if you want me to keep looking at this issue, or reassign.

**Comment by slivne** [comment] 2018-10-22 08:18
github is not working ...

@glommer / @vladzcloudius - can one of you look at this it seems the AMI is not booting because io settings.

**Comment by gleb-cloudius** [comment] 2018-10-22 16:41
On Mon, Oct 22, 2018 at 01:25:00AM -0700, Shlomi Livne wrote:
> Assigned #3842 to @gleb-cloudius.
> 
Did you mean to assign it to @glommer?

--
			Gleb.

**Comment by glommer** [comment] 2018-10-22 16:47
@gleb-cloudius , @glommer what's the difference?? It's all gl-something

**Comment by glommer** [comment] 2018-10-22 17:17
io_setup is returning `EAGAIN`, which according to the man page:

```
       EAGAIN The specified nr_events exceeds the user's limit of available events, as defined in /proc/sys/fs/aio-max-nr.
```

This is set to `65536` in the system. That is 936 per shard.
We are requiring for a while 1024 requests per shard, so that's the problem

My local systems all have that file set to a way higher number, and old AMI (probably using a different CentOS base) did work.

If I set that manually to `1048576`, which is what I have in my local system, Scylla boots again

@syuu1228 I think all we need is to set that number explicitly

**Comment by amoskong** [comment] 2018-10-22 23:44
This problem always happens at boot stage, it blocked all our tests uses AMI.

**Comment by syuu1228** [comment] 2018-10-23 00:19
I'll send a fix for this very soon.

We are getting the error only on AMI (CentOS7) for now, but I guess it's
safer to change the parameter on all supported distribution, not just AMI.
I found at least Ubuntu 16/18 are set to fs.aio-max-nr = 65536.

**Comment by syuu1228** [comment] 2018-10-23 03:05
Patch sent: [PATCH scylla] dist/common/sysctl.d: add new conf file to set fs.aio-max-nr

**Closed** 2018-10-23 20:42 UTC
Labels: AWS, bug

**Comment by amoskong** [comment] 2018-10-29 01:16
This problem is fixed in 3.0.rc0-0.20181028.c27443093
Test job: [3.0-test/job/scylla-ami-test/label=muninn/11/](http://jenkins.cloudius-systems.com:8080/job/scylla-3.0/job/3.0-test/job/scylla-ami-test/label=muninn/11/) (PASS)

**Comment by dyasny** [comment] 2018-11-14 16:58
Ran into the same issue with docker tag 3.0.rc1:

```
2018-11-14 16:29:16,713 INFO spawned: 'scylla' with pid 1595
Traceback (most recent call last):
  File "/usr/lib64/python3.4/configparser.py", line 761, in get
    value = d[option]
  File "/usr/lib64/python3.4/collections/__init__.py", line 805, in __getitem__
    return self.__missing__(key)            # support subclasses that define __missing__
  File "/usr/lib64/python3.4/collections/__init__.py", line 797, in __missing__
    raise KeyError(key)
KeyError: 'SET_NIC'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/scylla/scylla_prepare", line 65, in <module>
    set_nic = cfg.get('SET_NIC')
  File "/usr/lib/scylla/scylla_util.py", line 484, in get
    return self._cfg.get('global', key).strip('"')
  File "/usr/lib64/python3.4/configparser.py", line 764, in get
    raise NoOptionError(option, section)
configparser.NoOptionError: No option 'SET_NIC' in section: 'global'
2018-11-14 16:29:18,708 INFO success: scylla entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
scylla: core/reactor.cc:561: seastar::reactor::reactor(unsigned int): Assertion `r >= 0' failed.
Aborting on shard 63.
Backtrace:
  0x00000000006a6d02
  0x00000000005be42c
  0x00000000005be6d5
  0x00000000005be783
  /lib64/libpthread.so.0+0x000000000000f6cf
  /lib64/libc.so.6+0x0000000000036276
  /lib64/libc.so.6+0x0000000000037967
  /lib64/libc.so.6+0x000000000002f095
  /lib64/libc.so.6+0x000000000002f141
  0x00000000006707f0
  0x0000000000671965
  0x0000000000671e61
  0x000000000075561d
  /lib64/libpthread.so.0+0x0000000000007e24
  /lib64/libc.so.6+0x00000000000febac
```

Setting `fs.aio-max-nr = 1048576` on the host solves the problem, but it cannot be done inside docker and if we have no control over the host (GKE for example) this is not going to be possible to set.

**Comment by lustefaniak** [comment] 2019-03-14 17:39
This happens to me when using `scylladb/scylla:3.0.3` docker image on CI

**Comment by glommer** [comment] 2019-03-14 17:41
@lustefaniak there isn't really much to do about it but to increase the kernel limits.

**Comment by lustefaniak** [comment] 2019-03-14 17:46
Well, it sometimes works and I'm not sure why is that. Does it mean this limit is shared by multiple processes running at the same time on the node?

Is there maybe some configuration setting which I could change inside the container to not use that many events per shard?

**Comment by glommer** [comment] 2019-03-14 17:49
Yes, this is a global Linux limit. If it there is anything using aio in your box you could see this behavior.

Those limits are not configurable in Scylla, but they are per-shard. So if you use less shards (`--smp`) that could be a way too.

**Comment by lustefaniak** [comment] 2019-03-14 17:55
Thanks for the explanation!
