### ISSUE TITLE
Remove the MIN and MAX tokens use MIN_INT64 and MAX_INT64 instead

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla#7967] opened 2021-01-26 14:24 UTC
@haaawk please add info

**Comment by slivne** [comment] 2021-02-02 13:56
duplicate of https://github.com/scylladb/scylla/issues/1580 ?

**Comment by avikivity** [comment] 2021-02-02 14:58
Closed as duplicate of #1580.

**Closed by avikivity** 2021-02-02 14:58 UTC
Labels: Eng-3, enhancement, internals
