### ISSUE TITLE
Support limiting the number of concurrent requests in alternator

### ISSUE THREAD

**Issue by psarna** [scylladb/scylla#7294] opened 2020-09-29 08:26 UTC
DynamoDB has a `RequestLimitExceeded` error type which can be returned if the number of concurrent requests is too high. A similar mechanism is going to be introduced for CQL soon (#7279), so we can piggy-back on it and use the same config variable to shed excessive requests.

semi-related: there's also `LimitExceededException`, but this one only applies to "concurrent control plane operations", quoting the docs, which means creating, deleting or updating tables/indexes, and this limit is hardcoded in DynamoDB to `50`.

**Comment by psarna** [comment] 2020-09-29 10:24
Hm, there's also `ThrottlingException` which has a very similar description... Theoretically, `RequestLimitExceeded` is described to be related to throughput limits, while `ThrottlingException` is about the rate of requests, but it also relates to control plane requests *unless* you're in on-demand mode. Quite complicated, but I guess it doesn't matter that much, since sensible driver implementations should treat both in a similar fashion.

The main difference from boto3's side (source: https://github.com/boto/botocore/blob/64827efe118f44b42e8b75e9c45052cd5e77d5aa/botocore/data/_retry.json) seems to be that ThrottlingException results in http error 400, while RequestLimitExceeded returns 503. Aside from that, both errors are retriable.

I think I'll go with `ThrottlingException`, since it specifically mentions the **rate** of requests is too high, which matches the description of the Scylla parameter slightly better.

**Comment by nyh** [comment] 2020-09-29 11:55
If we look at a specific request type, e.g, `GetItem`, https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_GetItem.html, or `PutItem`, Amazon specifies that it is only expected to return two exception types, not the ones you specified:

1. There is `ProvisionedThroughputExceededException` - this is the normal error that happens in normal cases - when you have provisioned throughput, and have exceeded it, and DynamoDB wants to slow you down. DynamoDB clients will normally be able to deal with this exception well. It's just that they may not expect this exception to happen in the pay-per-request (non-provisioned) billing mode.

2. There is `RequestLimitExceeded`, apparently DynamoDB allows administrators to set quotas (see https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) even when there is no physical limit, to avoid run-away-train applications from consuming huge amounts of work (and money). Even in on-demand (pey-par-request) billing mode, a user may pass this configured quota and get this exception.

I think both exceptions are useful for us in the case you described, but `RequestLimitExceeded` is better, because when a user reads about it, he gets the impression that this is an externally-configured quota, not something that can be configured through the DynamoDB API (which the documentation of `ProvisionedThroughputExceededException` refers to).
Please note that despite the name "RequestLimitExceeded" not mentioning the words throughput or rate, its documentation clearly explains that it is, indeed, related to **throughput**:

>  **RequestLimitExceeded**: Throughput exceeds the current throughput quota for your account. Please contact AWS Support at AWS Support to request a quota increase. 

You also mentioned `ThrottlingException`. This one is really wierd: `GetItem` or `PutItem` is not mentioned to return it at all, and as I explained above, both mention two different exceptions for the same thing. To add to the confusion, https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Programming.Errors.html suggests that it may be returned, and boto documentation also mentions it - https://botocore.amazonaws.com/v1/documentation/api/latest/reference/services/dynamodb.html says that "_ReadCapacityUnits - The maximum number of strongly consistent reads consumed per second before DynamoDB returns a ThrottlingException_". But these two sources are inconsistent - the first one suggests this errror is used only in on-demand billing mode, but the second suggests it is only used in provisioned mode. One of these two sources - or both - must be wrong.

The `LimitExceededException` you also mentioned is documented as happening in a closed list of control-plane operations (like creating or modying tables) who concurrency is limited - I don't think we should use that.

Given all this, my favorite exception for us to use is `RequestLimitExceeded`.
The `ThrottlingException` which you prefer is not my favorite because its documentation is confusing and inconsistent, and may lead users to think that it can be fixed in ways in which it can't (e.g., increasing the provisioned throughput via UpdateTable).

**Comment by psarna** [comment] 2020-09-29 12:01
Makes sense. I don't have a strong preference and my first iteration indeed used `RequestLimitExceeded` instead of `ThrottlingException`, which I found later, so I'll just restore the original code.

**Comment by nyh** [comment] 2020-09-29 12:57
@psarna there's another thing troubling me a bit, and I'd like your opinion about it:

As we already mentioned above, there are two very different types of requests - there is data-plain requests (`GetItem`, `PutItem`, `Query`, etc.) and there is control-plain requests - `CreateTable`, `UpdateTable`, `TagResource`, and so on.

Are we planning to rate-limit both these requests types with the same limit, and same error message? The proposal above and your implementaiton in https://github.com/scylladb/scylla/pull/7297 suggests this is indeed your intention: If you limit the number of requests per second to 10,000 (per shard), and you get 20,000, half of the requests will be dropped. This means that a `CreateTable` also has a 50% chance of being dropped. I guess this is not the intention, but on the other hand, maybe it's not a big problem (boto3 et al. will retry the request).

Furthermore, I think eventually we'll need a separate, much lower, limit for control operations, like DynamoDB has. Especially if they are free on a shared setup (like they are on DynamoDB). Just because we can do 10,000 reads per second doesn't mean it makes sense to send 10,000 `CreateTable` and `DeleteTable` operations concurrently. Those can easily overwhelm Scylla and perhaps even DoS it. This can be considered a separate issue, but on the other hand, if you're already creating a limit for requests, maybe it makes sense to start right away with two different limits?

**Comment by psarna** [comment] 2020-09-29 13:37
Sure, we can also go that way and have alternator-specific limits from the start. Then we need a decision if `max_concurrent_requests_per_shard` should be ignored by alternator, should it act as a limiter for data plane queries only, or perhaps work as an independent threshold for all requests, because alternator-specific thresholds and this one need not be mutually exclusive. From the comment above I assume that you're in favor of option 3, to leave this limit as is and add another one for control plane only, which returns `LimitExceededException` if it's reached -- sounds reasonable, I can do that.

**Comment by nyh** [comment] 2020-09-29 14:01
I am fine with doing what you did here, and **later** adding a separate limit (as you suggested now) for control operations.
Should be very easy - we just need a counter (not even a gate, strictly) of ongoing control operations, and refuse new ones if the counter is over the limit. 
Note that this approach of a "separate limit" still has the problem that control-plane operations can be shed because the data-plane is very busy. But maybe this is not a problem (control-plane operations can also be retried).

**Comment by slivne** [comment] 2020-10-04 10:10
@nyh did you merge this ?

**Comment by nyh** [comment] 2020-10-04 10:12
Yes I did, but I think @psarna later dequeued it when he discovered a bug with "updatable_value".

**Comment by nyh** [comment] 2021-02-04 15:36
Hi @psarna can you please check what is the status of this fix that you already sent many months ago - was it ever committed? If not, how difficult is it to fix what was broken and commit?

**Comment by psarna** [comment] 2021-02-04 16:08
Fixing the `updateable_value` problem is close to impossible. The whole point was to make this value convenient to use by being cross-shard-safe, and seems it's only achievable by making the whole interface based on futures, which makes it inconvenient to use, which was the whole point for its creation :)

But, regardless of this problem above, adding this limiter to alternator is simple if we just assume that `updateable_value` is not cross-shard-safe, as was done for CQL. I think it would require <1h of coding, which I can schedule for tomorrow.

**Comment by psarna** [comment] 2021-02-04 16:26
Hm, if I parse the code correctly, it actually requires a <1min of coding, so maybe I'll just push a pull request soon.

**Closed** 2021-02-09 23:56 UTC
Labels: Alternator

**Comment by nyh** [comment] 2021-02-21 07:21
This is a new feature, not a bug fix, so not backporting.
