### ISSUE TITLE
If repair process is run on view, the data in the MV is not fixed.

### ISSUE THREAD

**Issue by juliayakovlev** [scylladb/scylla#3253] opened 2018-03-04 14:47 UTC
If repair process is run on base table or view, the data in the MV is not fixed.
Scenario:
1. Create a base table and a view on it where one of the base's non-key columns (let's call it "b") becomes a clustering key in the view table (the partition key, "a", remains the same).
N=3, RF=3. (BTW, This, and also the fact of same partition key, means each node is paired with itself).
2. Add a single base row with b=2.
3. Now killed one of the nodes (for example, node2)
4. Update the base partition setting b=3.
This should, one the two living view replicas, delete the row with clustering key b=2, and add a new row with b=3.
4. Now restore the killed node.
5. Repair MV
6. Stop other nodes (node1 and node3)
7. Now query the view from non-updated node
Result - old (not updated data) is returned

If run repair of all data (not specify the entity), the data is repaired.

Dtests for reproduce the problem (not merged yet, still in the my repo):
materialized_views_test.py/TestMaterializedViews#repair_mv_test

**Comment by nyh** [comment] 2018-03-04 15:10
This issue should probably be limited to the question of why the repair of the **view** didn't help - while we think it should have.

We should probably open a separate issue about what the repair of the base table is supposed to do. Right now it probably doesn't do what people expect it to (it only repairs the base table, it doesn't touch the view table).

**Comment by juliayakovlev** [comment] 2018-03-05 14:07
Opened: https://github.com/scylladb/scylla/issues/3255

**Comment by nyh** [comment] 2018-03-19 10:33
@juliayakovlev do you have the dtest which failed in this way already committed, or if not can you can attach the code here so I can try it or point me to where I can find it? Thanks.

**Comment by duarten** [comment] 2018-03-19 10:40
I think it's here: https://github.com/scylladb/scylla-dtest/pull/574

**Comment by juliayakovlev** [comment] 2018-03-19 11:16
@nyh  Yes, @duarten is right. It's materialized_views_test.py/TestMaterializedViews#repair_mv_test in the pull request scylladb/scylla-dtest#574

**Comment by nyh** [comment] 2018-03-19 13:17
This is not a Scylla bug - repair of the MV **does** work (as we can see in the test's debug output), and as we expect repairs only the view (not the base). 

Rather, it is the test itself which is buggy, and @juliayakovlev will fix:

1. The test ensures one of the nodes has outdated data (in both base and view) and then repairs only the view. After this repair, **only** the view will be updated, the base will not. So what this test checks - that the base and view data on this node are equal - is the wrong thing to check. Of course it should fail. Rather, the test should verify that all the view table has are new (column=3) data.

2. I think the test intended to modify all the 100 partitions to new values, but in fact because has a "where_filter" in the tm.update_table() call, it modifies only partition id=0. This is not strictly a bug - it is fine to modify only id=0 (and repair would fix only that single id), so we can leave it like it is. But it seems to me this was not the intended behavior so maybe you want to remove the where_filter.

I think we should close this issue (unfortunately I don't have permission to do it myself).

**Comment by duarten** [comment] 2018-03-19 13:23
Thanks for investigating, @nyh!

**Closed by duarten** 2018-03-19 13:23 UTC
Labels: materialized-views
