### ISSUE TITLE
Serialize access to migration_manager._listeners

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#5600] opened 2020-01-16 05:12 UTC
Following up the d3d37319877074b17916477ce9abf9f6593a8104 that fixes #5541,
this fix would not allow the node to start if there's a schema disagreement (like in rolling upgrade when the schema hash is changed across versions), a better fix would be to protect the migration manager listeners listeners list with a rwlock so that registration and unregistration would wait while the list is traversed.  This is not trivial since, e.g. `register_listener` listener is called from `cdc::cdc_service::impl` constructor.

With that, revert d3d37319877074b17916477ce9abf9f6593a8104 and reinstate 17917e12ce86c5c97b2352a6a6507457919fa000.

**Comment by avikivity** [comment] 2020-01-20 20:14
Closing as duplicate of #5541.

**Closed by avikivity** 2020-01-20 20:14 UTC
Labels: bug
