### ISSUE TITLE
scylla-kernel-conf doesn't install when user tries to install scylla-server only

### ISSUE THREAD

**Issue by syuu1228** [scylladb/scylla#2313] opened 2017-04-25 22:56 UTC
Since scylla-kernel-conf is requires from scylla metapackage instead of scylla-server package, when user tries to "yum install scylla-server" or "apt-get install scylla-server" scylla-kernel-conf won't install.
However, all kernel tuneup on scylla-kernel-conf is for scylla-server.

So I suppose we need to move dependency from scylla to scylla-server.
```
ubuntu@ip-10-228-103-55:~$ sudo apt install scylla-server
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following extra packages will be installed:
  at-spi2-core ca-certificates-java collectd collectd-core colord
  dconf-gsettings-backend dconf-service default-jre-headless fontconfig
  fontconfig-config fonts-dejavu fonts-dejavu-core fonts-dejavu-extra
  hicolor-icon-theme hugepages hwloc-nox java-common libaio1 libasound2
  libasound2-data libasyncns0 libatk-bridge2.0-0 libatk1.0-0 libatk1.0-data
  libatspi2.0-0 libavahi-client3 libavahi-common-data libavahi-common3
  libboost-date-time1.55.0 libboost-filesystem1.55.0
  libboost-program-options1.55.0 libboost-system1.55.0 libboost-thread1.55.0
  libcairo-gobject2 libcairo2 libcanberra-gtk3-0 libcanberra-gtk3-module
  libcanberra0 libcolord1 libcolorhug1 libcrypto++9 libcups2 libdatrie1
  libdbi1 libdconf1 libdevmapper-event1.02.1 libesmtp6 libexif12 libflac8
  libfontconfig1 libgd3 libgdk-pixbuf2.0-0 libgdk-pixbuf2.0-common libgmp10
  libgnutls28 libgnutlsxx28 libgphoto2-6 libgphoto2-l10n libgphoto2-port10
  libgraphite2-3 libgtk-3-0 libgtk-3-bin libgtk-3-common libgudev-1.0-0
  libgusb2 libharfbuzz0b libhogweed2 libhugetlbfs0 libhwloc-plugins libhwloc5
  libieee1284-3 libjasper1 libjbig0 libjpeg-turbo8 libjpeg8 libjsoncpp0
  liblcms2-2 libltdl7 liblvm2app2.2 liblz4-1 libmemcached10 libmnl0 libmodbus5
  libmysqlclient18 libnettle4 libnl-3-200 libnotify4 libnspr4 libnss3
  libnss3-nssdb libogg0 libopenipmi0 liboping0 libpango-1.0-0
  libpangocairo-1.0-0 libpangoft2-1.0-0 libpciaccess0 libperl5.18
  libpixman-1-0 libpq5 libprotobuf-c0 libprotobuf8 libpulse0 librabbitmq1
  librrd4 libsane libsane-common libsctp1 libsensors4 libsnappy1 libsndfile1
  libsnmp-base libsnmp30 libtdb1 libthai-data libthai0 libtiff5
  libtokyocabinet9 libtokyotyrant3 libunwind8 libupsclient3 libv4l-0
  libv4lconvert0 libvarnishapi1 libvirt0 libvorbis0a libvorbisenc2
  libvorbisfile3 libvpx1 libwayland-client0 libwayland-cursor0 libxcb-render0
  libxcb-shm0 libxcomposite1 libxcursor1 libxdamage1 libxfixes3 libxi6
  libxinerama1 libxkbcommon0 libxpm4 libxrandr2 libxrender1 libxtst6 libyajl2
  libyaml-cpp0.5 lksctp-tools mysql-common notification-daemon
  ocl-icd-libopencl1 openjdk-7-jre-headless python-urwid python3-yaml realpath
  rrdtool scylla-conf sound-theme-freedesktop ttf-dejavu ttf-dejavu-core
  ttf-dejavu-extra tzdata-java x11-common
Suggested packages:
  collectd-dev librrds-perl liburi-perl libhtml-parser-perl
  libregexp-common-perl libconfig-general-perl httpd-cgi apache2 apcupsd bind9
  hddtemp ipvsadm lm-sensors mbmon memcached mysql-server nginx nut openvpn
  olsrd pdns-server postgresql time-daemon default-jre libhugetlbfs-tests
  equivs libasound2-plugins alsa-utils libcanberra-gtk0 libcanberra-pulse
  cups-common libgd-tools gnutls-bin gphoto2 gtkam librsvg2-common gvfs
  libhwloc-contrib-plugins libjasper-runtime liblcms2-utils ttf-baekmuk
  ttf-arphic-gbsn00lp ttf-arphic-bsmi00lp ttf-arphic-gkai00mp
  ttf-arphic-bkai00mp pulseaudio avahi-daemon hplip hpoj libsane-extras
  sane-utils snmp-mibs-downloader lvm2 opencl-icd icedtea-7-jre-jamvm
  libnss-mdns sun-java6-fonts fonts-ipafont-gothic fonts-ipafont-mincho
  ttf-wqy-microhei ttf-wqy-zenhei ttf-indic-fonts-core ttf-telugu-fonts
  ttf-oriya-fonts ttf-kannada-fonts ttf-bengali-fonts
The following NEW packages will be installed:
  at-spi2-core ca-certificates-java collectd collectd-core colord
  dconf-gsettings-backend dconf-service default-jre-headless fontconfig
  fontconfig-config fonts-dejavu fonts-dejavu-core fonts-dejavu-extra
  hicolor-icon-theme hugepages hwloc-nox java-common libaio1 libasound2
  libasound2-data libasyncns0 libatk-bridge2.0-0 libatk1.0-0 libatk1.0-data
  libatspi2.0-0 libavahi-client3 libavahi-common-data libavahi-common3
  libboost-date-time1.55.0 libboost-filesystem1.55.0
  libboost-program-options1.55.0 libboost-system1.55.0 libboost-thread1.55.0
  libcairo-gobject2 libcairo2 libcanberra-gtk3-0 libcanberra-gtk3-module
  libcanberra0 libcolord1 libcolorhug1 libcrypto++9 libcups2 libdatrie1
  libdbi1 libdconf1 libdevmapper-event1.02.1 libesmtp6 libexif12 libflac8
  libfontconfig1 libgd3 libgdk-pixbuf2.0-0 libgdk-pixbuf2.0-common libgmp10
  libgnutls28 libgnutlsxx28 libgphoto2-6 libgphoto2-l10n libgphoto2-port10
  libgraphite2-3 libgtk-3-0 libgtk-3-bin libgtk-3-common libgudev-1.0-0
  libgusb2 libharfbuzz0b libhogweed2 libhugetlbfs0 libhwloc-plugins libhwloc5
  libieee1284-3 libjasper1 libjbig0 libjpeg-turbo8 libjpeg8 libjsoncpp0
  liblcms2-2 libltdl7 liblvm2app2.2 liblz4-1 libmemcached10 libmnl0 libmodbus5
  libmysqlclient18 libnettle4 libnl-3-200 libnotify4 libnspr4 libnss3
  libnss3-nssdb libogg0 libopenipmi0 liboping0 libpango-1.0-0
  libpangocairo-1.0-0 libpangoft2-1.0-0 libpciaccess0 libperl5.18
  libpixman-1-0 libpq5 libprotobuf-c0 libprotobuf8 libpulse0 librabbitmq1
  librrd4 libsane libsane-common libsctp1 libsensors4 libsnappy1 libsndfile1
  libsnmp-base libsnmp30 libtdb1 libthai-data libthai0 libtiff5
  libtokyocabinet9 libtokyotyrant3 libunwind8 libupsclient3 libv4l-0
  libv4lconvert0 libvarnishapi1 libvirt0 libvorbis0a libvorbisenc2
  libvorbisfile3 libvpx1 libwayland-client0 libwayland-cursor0 libxcb-render0
  libxcb-shm0 libxcomposite1 libxcursor1 libxdamage1 libxfixes3 libxi6
  libxinerama1 libxkbcommon0 libxpm4 libxrandr2 libxrender1 libxtst6 libyajl2
  libyaml-cpp0.5 lksctp-tools mysql-common notification-daemon
  ocl-icd-libopencl1 openjdk-7-jre-headless python-urwid python3-yaml realpath
  rrdtool scylla-conf scylla-server sound-theme-freedesktop ttf-dejavu
  ttf-dejavu-core ttf-dejavu-extra tzdata-java x11-common
0 upgraded, 163 newly installed, 0 to remove and 113 not upgraded.
Need to get 8,404 kB/72.3 MB of archives.
After this operation, 201 MB of additional disk space will be used.
Do you want to continue? [Y/n] 
WARNING: The following packages cannot be authenticated!
  scylla-conf scylla-server
Install these packages without verification? [y/N]
```

**Comment by avikivity** [comment] 2020-08-05 15:27
This is by design - for users that don't want scylla to take over the machine.

To install scylla-kernel-conf automatically, use the superpackage.

Closing as invalid.

**Closed by avikivity** 2020-08-05 15:27 UTC
