### ISSUE TITLE
storage_proxy - Failed to apply mutation occur while batch insert in ScyllaDB 2.02

### ISSUE THREAD

**Issue by ban4785** [scylladb/scylla#3100] opened 2017-12-26 02:32 UTC
*Installation details*
Scylla version (or git commit hash): 2.02
Cluster size: 3
OS (RHEL/CentOS/Ubuntu/AWS AMI): AWS ScyllaDB 2.02 - ami-9509d3ed

*Hardware details (for performance issues)*          Delete if unneeded
Platform (physical/VM/cloud instance type/docker): AWS VM i3.8xlarge
Hardware: sockets= cores= hyperthreading= memory=32vcore, 244G Memory
Disks: (SSD/HDD, count) : SSD 4*1900 Raid0

i was loading 10Tera data with 300,000 TPS in AWS Infra
schema is
CREATE TABLE sample (
    key1 text,
    key2 text,
    key3 text,
    ts timestamp,
    seq int,
    temp text,
    PRIMARY KEY ((key1, key2, key3), ts, seq)
) WITH CLUSTERING ORDER BY (ts ASC)
and max partition size was 10Mbytes. 

but one ScyllaDB Instance didn't work after 1days
and /var/log/messages was
_Dec 23 12:41:23 ip-172-31-13-50 scylla: [shard 0] storage_proxy - Failed to apply mutation from 172.31.1.122#15: std::bad_alloc (std::bad_alloc)
Dec 23 12:41:23 ip-172-31-13-50 scylla: [shard 4] storage_proxy - Failed to apply mutation from 172.31.1.122#1: std::bad_alloc (std::bad_alloc)
Dec 23 12:41:23 ip-172-31-13-50 scylla: [shard 11] storage_proxy - exception during mutation write to 172.31.13.50: std::bad_alloc (std::bad_alloc)
Dec 23 12:41:23 ip-172-31-13-50 scylla: [shard 12] storage_proxy - Failed to apply mutation from 172.31.1.122#4: std::bad_alloc (std::bad_alloc)
Dec 23 12:41:23 ip-172-31-13-50 scylla: [shard 12] storage_proxy - Failed to apply mutation from 172.31.1.122#4: std::bad_alloc (std::bad_alloc)
Dec 23 12:41:23 ip-172-31-13-50 scylla: [shard 9] storage_proxy - Failed to apply mutation from 172.31.1.122#12: std::bad_alloc (std::bad_alloc)
Dec 23 12:41:23 ip-172-31-13-50 scylla: [shard 10] storage_proxy - Failed to apply mutation from 172.31.15.164#8: std::bad_alloc (std::bad_alloc)
Dec 23 12:41:23 ip-172-31-13-50 scylla: [shard 14] storage_proxy - Failed to apply mutation from 172.31.15.164#15: std::bad_alloc (std::bad_alloc)
Dec 23 12:41:23 ip-172-31-13-50 scylla: [shard 14] storage_proxy - Failed to apply mutation from 172.31.15.164#15: std::bad_alloc (std::bad_alloc)
Dec 23 12:41:23 ip-172-31-13-50 scylla: [shard 14] storage_proxy - Failed to apply mutation from 172.31.15.164#15: std::bad_alloc (std::bad_alloc)
Dec 23 12:41:23 ip-172-31-13-50 scylla: [shard 14] storage_proxy - Failed to apply mutation from 172.31.15.164#15: std::bad_alloc (std::bad_alloc)
Dec 23 12:41:23 ip-172-31-13-50 scylla: [shard 14] storage_proxy - Failed to apply mutation from 172.31.15.164#15: std::bad_alloc (std::bad_alloc)
Dec 23 12:41:23 ip-172-31-13-50 scylla: [shard 1] storage_proxy - exception during mutation write to 172.31.13.50: std::bad_alloc (std::bad_alloc)
Dec 23 12:41:23 ip-172-31-13-50 scylla: [shard 14] storage_proxy - Failed to apply mutation from 172.31.15.164#15: std::bad_alloc (std::bad_alloc)
Dec 23 12:41:23 ip-172-31-13-50 scylla: [shard 15] storage_proxy - Failed to apply mutation from 172.31.1.122#14: std::bad_alloc (std::bad_alloc)_
that messages repeats util shutdown ScyllaDB Instance.

batch client shows 200,000 TPS(normal case was 300,000 TPS)
and problem instance was alive, but didn;t batch write operation.
below is grafana monitoring screenshot
![error](https://user-images.githubusercontent.com/20348151/34344013-791ff958-ea23-11e7-8945-4c92a229d32f.png)

**Comment by tzach** [comment] 2017-12-31 11:03
@ban4785 thanks for reporting
Can you share more details on how are you loading the system? In particular, what driver and how many threads and connections are you using?
Unbound concurrency from the client side might hint to an overload handling issue in Scylla.

**Comment by ban4785** [comment] 2018-01-02 04:18
@tzach i used datastax java driver 3.0.0, using 128 connections, lz4 compression,  200threads.
each thread generates 100 size batch, with sync insert function(session.execute(...)).
thread has unique partition, and one partition has 3,600 rows so partition size not over 10m bytes.

**Comment by tgrabiec** [comment] 2018-01-09 08:01
This could be https://github.com/scylladb/scylla/issues/2775, fixed in version `2.1` (>= rc1).

**Comment by slivne** [comment] 2018-01-25 11:16
@ban4785 -are you using c-s to load the data - if so can you share the profile and we will try to reproduce

**Comment by nasirali1** [comment] 2018-02-02 04:21
I am getting kinda similar error. If I try to stop Scylla it starts overloading the system to unusable state. We have 5 ScyllaDB nodes, under high writes some of the nodes crashes with similar error logs as below:

Redirecting to /bin/systemctl status scylla-server.service
* scylla-server.service - Scylla Server
   Loaded: loaded (/usr/lib/systemd/system/scylla-server.service; enabled; vendor preset: disabled)
   Active: deactivating (stop-sigterm) since Thu 2018-02-01 21:44:45 CST; 1min 13s ago
  Process: 15816 ExecStopPost=/usr/lib/scylla/scylla_stop (code=exited, status=0/SUCCESS)
  Process: 16017 ExecStartPre=/usr/lib/scylla/scylla_prepare (code=exited, status=0/SUCCESS)
 Main PID: 16043 (scylla)
   Status: "serving"
   Memory: 31.6G
   CGroup: /system.slice/scylla-server.service
           `-16043 /usr/bin/scylla --log-to-syslog 1 --log-to-stdout 0 --default-log-level info --collectd-address=127.0.0.1:25826 --collectd=1 --collectd-poll-period 3000 --network-stack posix --max-io-requests=144 --cpuset 1-15,17-31

Feb 01 21:45:28 kashyyyk10dot scylla[16043]:  [shard 0] batchlog_manager - Exception in batch replay: exceptions::read_timeout_exception (Operation timed out for system.batchlog - received only 0 responses from 1 CL=ONE.)
Feb 01 21:45:31 kashyyyk10dot scylla[16043]:  [shard 27] database - failed to write sstable /md2k/data1/cerebralcortex/data-7bcb34d0062d11e8a579000000000009/cerebralcortex-data-ka-42507-Data.db: std::bad_alloc (std::bad_alloc)
Feb 01 21:45:31 kashyyyk10dot scylla[16043]:  [shard 27] database - failed to write sstable /md2k/data1/cerebralcortex/data-7bcb34d0062d11e8a579000000000009/cerebralcortex-data-ka-42537-Data.db: std::bad_alloc (std::bad_alloc)
Feb 01 21:45:31 kashyyyk10dot scylla[16043]:  [shard 27] database - failed to write sstable /md2k/data1/cerebralcortex/data-7bcb34d0062d11e8a579000000000009/cerebralcortex-data-ka-42567-Data.db: std::bad_alloc (std::bad_alloc)
Feb 01 21:45:41 kashyyyk10dot scylla[16043]:  [shard 27] database - failed to write sstable /md2k/data1/cerebralcortex/data-7bcb34d0062d11e8a579000000000009/cerebralcortex-data-ka-42597-Data.db: std::bad_alloc (std::bad_alloc)
Feb 01 21:45:41 kashyyyk10dot scylla[16043]:  [shard 27] database - failed to write sstable /md2k/data1/cerebralcortex/data-7bcb34d0062d11e8a579000000000009/cerebralcortex-data-ka-42627-Data.db: std::bad_alloc (std::bad_alloc)
Feb 01 21:45:41 kashyyyk10dot scylla[16043]:  [shard 27] database - failed to write sstable /md2k/data1/cerebralcortex/data-7bcb34d0062d11e8a579000000000009/cerebralcortex-data-ka-42657-Data.db: std::bad_alloc (std::bad_alloc)
Feb 01 21:45:51 kashyyyk10dot scylla[16043]:  [shard 27] database - failed to write sstable /md2k/data1/cerebralcortex/data-7bcb34d0062d11e8a579000000000009/cerebralcortex-data-ka-42687-Data.db: std::bad_alloc (std::bad_alloc)
Feb 01 21:45:51 kashyyyk10dot scylla[16043]:  [shard 27] database - failed to write sstable /md2k/data1/cerebralcortex/data-7bcb34d0062d11e8a579000000000009/cerebralcortex-data-ka-42717-Data.db: std::bad_alloc (std::bad_alloc)
Feb 01 21:45:51 kashyyyk10dot scylla[16043]:  [shard 27] database - failed to write sstable /md2k/data1/cerebralcortex/data-7bcb34d0062d11e8a579000000000009/cerebralcortex-data-ka-42747-Data.db: std::bad_alloc (std::bad_alloc)

**Comment by slivne** [comment] 2018-02-11 11:33
@nasirali1 - are you writing in batches ?  please open a separate bug so we can track this and ask for clarification questions and solve your issue.

@ban4785 - can you please provide additional information so we can try and reproduce

**Comment by slivne** [comment] 2018-05-03 09:30
Closing this issue

if there is additional information please post and I'll reopen

**Closed by slivne** 2018-05-03 09:30 UTC
Labels: bug
