### ISSUE TITLE
Table scan excessive I/O bandwidth when using leveled compaction strategy

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylla#1861] opened 2016-11-20 08:05 UTC
*Installation details*
Scylla version (or git commit hash): ae0a2935b4183d86df96f81611ae68e79dc96845

A full table scan will create readers for sstables, even though we only need one sstable per level to be opened concurrently.  This wastes a lot of disk bandwidth to open those sstables, as well as cpu.

**Comment by nyh** [comment] 2016-11-20 08:38
Indeed. The combining reader doesn't need an idividual sstable reader until its first partition's key becomes current (the first one in the heap). Since we know this first partition key without opening the sstable (it's in the summary file, in memory) we can delay the actual opening of the sstable and reading its first partitions until we really need them. We can also close the reader once we reached its end (I hope we're already doing this - when getting an EOF when reading the sstable, but it's worth verifying).

One snag in delayed opening is that we lose read-ahead in this situation: When we reach an sstable's first partition, and only at that point open it, this will delay the scanning or compaction process, which will hang for a short while at that point. It would be nice to open the sstable a bit before we actually need it, i.e., read-ahead, without opening all the sstables up-front as we do now. I doubt though, that adding read-ahead here will be worth the effort, considering that the default LCS sstables are fairly large (160 MB) so the relative cost of waiting for the first partitions once every 160 MB of partitions is probably very small.

See also issue #1427, which is probably a duplicate of this one.

**Closed** 2016-11-20 08:42 UTC
Labels: performance
