### ISSUE TITLE
Docker images are broken

### ISSUE THREAD

**Issue by heitorPB** [scylladb/scylla#5638] opened 2020-01-23 18:22 UTC
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [ x ] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash): docker image: scylladb/scylla:3.2.0-202001200218
Cluster size: local machiine
OS (RHEL/CentOS/Ubuntu/AWS AMI): ArchLinux (dev environment)

I'm trying to setup Scylladb to replace our Cassandra, but so far I was unable to run a recent docker image. I tryied all 3.2 variants and all gave errors.

The command I used:
```
$ sudo docker run --name scylla -d scylladb/scylla:3.2.0
```

The full output is attached, here are the last lines:

```
ERROR 2020-01-23 18:15:50,431 [shard 0] seastar - Could not setup Async I/O: Resource temporarily unavailable. The most common cause is not enough request capacity in /proc/sys/fs/aio-max-nr. Try increasing that number or reducing the amount of logical CPUs available for your application
ERROR 2020-01-23 18:15:50,431 [shard 0] seastar - Could not setup Async I/O: Resource temporarily unavailable. The most common cause is not enough request capacity in /proc/sys/fs/aio-max-nr. Try increasing that number or reducing the amount of logical CPUs available for your application
2020-01-23 18:15:50,534 INFO exited: scylla (exit status 1; not expected)
2020-01-23 18:15:51,539 INFO spawned: 'scylla' with pid 86
Scylla version 3.2.0-0.20200115.f9b11c9b30 starting ...
command used: "/usr/bin/scylla --log-to-syslog 0 --log-to-stdout 1 --default-log-level info --network-stack posix --developer-mode=1 --overprovisioned --listen-address 172.17.0.2 --rpc-address 172.17.0.2 --seed-provider-parameters seeds=172.17.0.2 --blocked-reactor-notify-ms 999999999"
parsed command line options: [log-to-syslog: 0, log-to-stdout: 1, default-log-level: info, network-stack: posix, developer-mode: 1, overprovisioned, listen-address: 172.17.0.2, rpc-address: 172.17.0.2, seed-provider-parameters: seeds=172.17.0.2, blocked-reactor-notify-ms: 999999999]
ERROR 2020-01-23 18:15:51,908 [shard 0] seastar - Could not setup Async I/O: Resource temporarily unavailable. The most common cause is not enough request capacity in /proc/sys/fs/aio-max-nr. Try increasing that number or reducing the amount of logical CPUs available for your application
2020-01-23 18:15:52,003 INFO exited: scylla (exit status 1; not expected)
Connecting to http://localhost:10000
Starting the JMX server
2020-01-23 18:15:53,228 INFO spawned: 'scylla' with pid 117
Scylla version 3.2.0-0.20200115.f9b11c9b30 starting ...
command used: "/usr/bin/scylla --log-to-syslog 0 --log-to-stdout 1 --default-log-level info --network-stack posix --developer-mode=1 --overprovisioned --listen-address 172.17.0.2 --rpc-address 172.17.0.2 --seed-provider-parameters seeds=172.17.0.2 --blocked-reactor-notify-ms 999999999"
parsed command line options: [log-to-syslog: 0, log-to-stdout: 1, default-log-level: info, network-stack: posix, developer-mode: 1, overprovisioned, listen-address: 172.17.0.2, rpc-address: 172.17.0.2, seed-provider-parameters: seeds=172.17.0.2, blocked-reactor-notify-ms: 999999999]
ERROR 2020-01-23 18:15:53,571 [shard 0] seastar - Could not setup Async I/O: Resource temporarily unavailable. The most common cause is not enough request capacity in /proc/sys/fs/aio-max-nr. Try increasing that number or reducing the amount of logical CPUs available for your application
ERROR 2020-01-23 18:15:53,571 [shard 0] seastar - Could not setup Async I/O: Resource temporarily unavailable. The most common cause is not enough request capacity in /proc/sys/fs/aio-max-nr. Try increasing that number or reducing the amount of logical CPUs available for your application
2020-01-23 18:15:53,641 INFO exited: scylla (exit status 1; not expected)
JMX is enabled to receive remote connections on port: 7199
2020-01-23 18:15:55,683 INFO spawned: 'scylla' with pid 141
Scylla version 3.2.0-0.20200115.f9b11c9b30 starting ...
command used: "/usr/bin/scylla --log-to-syslog 0 --log-to-stdout 1 --default-log-level info --network-stack posix --developer-mode=1 --overprovisioned --listen-address 172.17.0.2 --rpc-address 172.17.0.2 --seed-provider-parameters seeds=172.17.0.2 --blocked-reactor-notify-ms 999999999"
parsed command line options: [log-to-syslog: 0, log-to-stdout: 1, default-log-level: info, network-stack: posix, developer-mode: 1, overprovisioned, listen-address: 172.17.0.2, rpc-address: 172.17.0.2, seed-provider-parameters: seeds=172.17.0.2, blocked-reactor-notify-ms: 999999999]
ERROR 2020-01-23 18:15:56,161 [shard 0] seastar - Could not setup Async I/O: Resource temporarily unavailable. The most common cause is not enough request capacity in /proc/sys/fs/aio-max-nr. Try increasing that number or reducing the amount of logical CPUs available for your application
2020-01-23 18:15:56,300 INFO exited: scylla (exit status 1; not expected)
2020-01-23 18:15:59,307 INFO spawned: 'scylla' with pid 165
Scylla version 3.2.0-0.20200115.f9b11c9b30 starting ...
command used: "/usr/bin/scylla --log-to-syslog 0 --log-to-stdout 1 --default-log-level info --network-stack posix --developer-mode=1 --overprovisioned --listen-address 172.17.0.2 --rpc-address 172.17.0.2 --seed-provider-parameters seeds=172.17.0.2 --blocked-reactor-notify-ms 999999999"
parsed command line options: [log-to-syslog: 0, log-to-stdout: 1, default-log-level: info, network-stack: posix, developer-mode: 1, overprovisioned, listen-address: 172.17.0.2, rpc-address: 172.17.0.2, seed-provider-parameters: seeds=172.17.0.2, blocked-reactor-notify-ms: 999999999]
ERROR 2020-01-23 18:15:59,755 [shard 0] seastar - Could not setup Async I/O: Resource temporarily unavailable. The most common cause is not enough request capacity in /proc/sys/fs/aio-max-nr. Try increasing that number or reducing the amount of logical CPUs available for your application
2020-01-23 18:15:59,824 INFO exited: scylla (exit status 1; not expected)
2020-01-23 18:16:00,825 INFO gave up: scylla entered FATAL state, too many start retries too quickly
```

There are also some python errors:

```
multiprocessing.pool.RemoteTraceback:
 """
 Traceback (most recent call last):
   File "/opt/scylladb/python3/lib64/python3.7/urllib/request.py", line 1317, in do_open
     encode_chunked=req.has_header('Transfer-encoding'))
   File "/opt/scylladb/python3/lib64/python3.7/http/client.py", line 1244, in request
     self._send_request(method, url, body, headers, encode_chunked)
   File "/opt/scylladb/python3/lib64/python3.7/http/client.py", line 1290, in _send_request
     self.endheaders(body, encode_chunked=encode_chunked)
   File "/opt/scylladb/python3/lib64/python3.7/http/client.py", line 1239, in endheaders
     self._send_output(message_body, encode_chunked=encode_chunked)
   File "/opt/scylladb/python3/lib64/python3.7/http/client.py", line 1026, in _send_output
     self.send(msg)
   File "/opt/scylladb/python3/lib64/python3.7/http/client.py", line 966, in send
     self.connect()
   File "/opt/scylladb/python3/lib64/python3.7/http/client.py", line 938, in connect
     (self.host,self.port), self.timeout, self.source_address)
   File "/opt/scylladb/python3/lib64/python3.7/socket.py", line 727, in create_connection
     raise err
   File "/opt/scylladb/python3/lib64/python3.7/socket.py", line 716, in create_connection
     sock.connect(sa)
 OSError: [Errno 99] Cannot assign requested address

 During handling of the above exception, another exception occurred:

 Traceback (most recent call last):
   File "/opt/scylladb/python3/lib64/python3.7/multiprocessing/pool.py", line 121, in worker
     result = (True, func(*args, **kwds))
   File "/opt/scylladb/scripts/libexec/scylla-housekeeping", line 64, in get_url
     return urllib.request.urlopen(path).read().decode('utf-8')
   File "/opt/scylladb/python3/lib64/python3.7/urllib/request.py", line 222, in urlopen
     return opener.open(url, data, timeout)
   File "/opt/scylladb/python3/lib64/python3.7/urllib/request.py", line 525, in open
     response = self._open(req, data)
   File "/opt/scylladb/python3/lib64/python3.7/urllib/request.py", line 543, in _open
     '_open', req)
   File "/opt/scylladb/python3/lib64/python3.7/urllib/request.py", line 503, in _call_chain
     result = func(*args)
   File "/opt/scylladb/python3/lib64/python3.7/urllib/request.py", line 1345, in http_open
     return self.do_open(http.client.HTTPConnection, req)
   File "/opt/scylladb/python3/lib64/python3.7/urllib/request.py", line 1319, in do_open
     raise URLError(err)
 urllib.error.URLError: <urlopen error [Errno 99] Cannot assign requested address>
 """

 The above exception was the direct cause of the following exception:

 Traceback (most recent call last):
   File "/opt/scylladb/scripts/libexec/scylla-housekeeping", line 197, in <module>
     args.func(args)
   File "/opt/scylladb/scripts/libexec/scylla-housekeeping", line 123, in check_version
     current_version = sanitize_version(get_api('/storage_service/scylla_release_version'))
   File "/opt/scylladb/scripts/libexec/scylla-housekeeping", line 82, in get_api
     return get_json_from_url("http://" + api_address + path)
   File "/opt/scylladb/scripts/libexec/scylla-housekeeping", line 74, in get_json_from_url
     retval = result.get(timeout=5)
   File "/opt/scylladb/python3/lib64/python3.7/multiprocessing/pool.py", line 657, in get
     raise self._value
 urllib.error.URLError: <urlopen error [Errno 99] Cannot assign requested address>
[errors.txt](https://github.com/scylladb/scylla/files/4104787/errors.txt)

```

**Comment by heitorPB** [comment] 2020-01-23 20:38
Some more info:

filesystem: ext4
AIO things:
$ cat /proc/sys/fs/aio-max-nr
65536

**Comment by fruch** [comment] 2020-01-23 22:15
which version of docker you are using ? can you supply more detail on the machine number of CPUs  which OS it is ?

**Comment by fruch** [comment] 2020-01-23 22:23
just for reference, I'm running with Ubuntu 19.10 with those version and /proc/sys/fs/aio-max-nr, and can run the docker image o.k.
```
$ docker version
Client: Docker Engine - Community
 Version:           19.03.3
 API version:       1.40
 Go version:        go1.12.10
 Git commit:        a872fc2f86
 Built:             Tue Oct  8 01:00:44 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.3
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.10
  Git commit:       a872fc2f86
  Built:            Tue Oct  8 00:59:17 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

$ cat /proc/sys/fs/aio-max-nr
1048576
```

**Comment by heitorPB** [comment] 2020-01-24 11:54
Running Docker on ArchLinux:

```
$ docker version
Client:
 Version:           19.03.5-ce
 API version:       1.40
 Go version:        go1.13.4
 Git commit:        633a0ea838
 Built:             Fri Nov 15 03:19:09 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.5-ce
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.4
  Git commit:       633a0ea838
  Built:            Fri Nov 15 03:17:51 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.3.2.m
  GitCommit:        d50db0a42053864a270f648048f9a8b4f24eced3.m
 runc:
  Version:          1.0.0-rc9
  GitCommit:        d736ef14f0288d6993a1845745d6756cfc9ddd5a
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

CPU is an i7-7700 CP with 4 cores (8 threads)

**Comment by dahankzter** [comment] 2020-01-24 13:38
I can confirm this happens for me as well on an up to date Arch. Running with `--smp 2` works fine. On my 8 core system I can at max have `--smp 5`. Anything higher triggers the error. I have around 65k in `/proc/sys/fs/aio-max-nr`.

**Comment by dahankzter** [comment] 2020-01-24 13:55
I can also confirm it starts to work applying this:
```bash
➜  ~ sudo emacs /etc/sysctl.conf
➜  ~ sudo sysctl -p           
fs.aio-max-nr = 1048576
➜  ~ cat /proc/sys/fs/aio-max-nr
1048576
```
After this change, no restart, it works fine.

**Comment by heitorPB** [comment] 2020-01-24 14:42
Changing `fs.aio-max-nr` worked for me also.

@dahankzter how did you run with different `--smp`? You made a custom image?

**Comment by dahankzter** [comment] 2020-01-24 16:30
No @heitorPB I did not build a special image. You can just append any scylla argument at the end of the docker run command. It will forward it to scylla automatically.

**Comment by heitorPB** [comment] 2020-01-24 18:31
Thanks @dahankzter !

I managed to do it inside a `docker-compose.yml`:

```
version: "3.4"

services:
  scylla:
    image: scylladb/scylla:3.2.0
    container_name: scylla
    command:
      - "--smp"
      - "2"
    ports:
      - "9042:9042"
```

**Comment by slivne** [comment] 2020-01-26 09:31
@avikivity we have ```--developer-mode=1``` set is this a check that's being applied although developer mode is set ?

**Comment by bhalevy** [comment] 2020-01-27 08:18
Ref https://github.com/scylladb/seastar/issues/640

**Comment by avikivity** [comment] 2020-01-27 09:56
@slivne I reopened and updated scylladb/seastar#640

**Comment by slivne** [comment] 2020-02-20 08:20
fixed by da00530464779bb1d3e6757e2e804ca909ee0e5d

**Closed by slivne** 2020-02-20 08:20 UTC
Labels: Backport 3.1, backport 3.2, bug, onboarding

**Comment by yckbilly1929** [comment] 2020-05-23 15:09
> I can also confirm it starts to work applying this:
> 
> ```shell
> ➜  ~ sudo emacs /etc/sysctl.conf
> ➜  ~ sudo sysctl -p           
> fs.aio-max-nr = 1048576
> ➜  ~ cat /proc/sys/fs/aio-max-nr
> 1048576
> ```
> 
> After this change, no restart, it works fine.

thanks a lot, it solved my problem after upgrading to Ubuntu 20.04 from 18, where /etc/sysctl.conf was replaced

**Comment by slivne** [comment] 2020-05-24 07:01
@yckbilly1929 which scylla version are you running - this was supposed to be fixed in 3.3 and 4.0 and work out of the box.

**Comment by yckbilly1929** [comment] 2020-05-24 07:15
> @yckbilly1929 which scylla version are you running - this was supposed to be fixed in 3.3 and 4.0 and work out of the box.

i am working on a local machine and installed through container image
version:
3.2.3-0.20200315.89deac77958

**Comment by slivne** [comment] 2020-05-24 07:46
@yckbilly1929 thanks, it is indeed not fixed in 3.2 (and will not be) so all is clear.

Please note 3.2 reached its End Of Life. We only support two latest releases (currently 3.3, 4.0).

**Comment by avikivity** [comment] 2020-06-21 09:53
Already backported; removing label.

**Comment by anancds** [comment] 2020-09-24 12:38
> I can also confirm it starts to work applying this:
> 
> ```shell
> ➜  ~ sudo emacs /etc/sysctl.conf
> ➜  ~ sudo sysctl -p           
> fs.aio-max-nr = 1048576
> ➜  ~ cat /proc/sys/fs/aio-max-nr
> 1048576
> ```
> 
> After this change, no restart, it works fine.

after applying this, my issue is fixed,thanks

**Comment by tnozicka** [comment] 2021-02-22 09:15
Looks like this still doesn't work by default:
```
# cat /proc/sys/fs/aio-max-nr   
65536
# docker run -it --rm scylladb/scylla:4.3.1
running: (['/opt/scylladb/scripts/scylla_dev_mode_setup', '--developer-mode', '1'],)
...
Scylla version 4.3.1-0.20210210.46650adcd with build-id bfaa518f22098de476b961b707925c71441bb81b starting ...
command used: "/usr/bin/scylla --log-to-syslog 0 --log-to-stdout 1 --default-log-level info --network-stack posix --developer-mode=1 --overprovisioned --listen-address 172.17.0.10 --rpc-address 172.17.0.10 --seed-provider-parameters seeds=172.17.0.10 --blocked-reactor-notify-ms 999999999"
parsed command line options: [log-to-syslog: 0, log-to-stdout: 1, default-log-level: info, network-stack: posix, developer-mode: 1, overprovisioned, listen-address: 172.17.0.10, rpc-address: 172.17.0.10, seed-provider-parameters: seeds=172.17.0.10, blocked-reactor-notify-ms: 999999999]
Connecting to http://localhost:10000
Starting the JMX server
ERROR 2021-02-22 09:09:38,501 [shard 2] seastar - Could not setup Async I/O: Resource temporarily unavailable. The most common cause is not enough request capacity in /proc/sys/fs/aio-max-nr. Try increasing that number or reducing the amount of logical CPUs available for your application
2021-02-22 09:09:38,566 INFO exited: scylla (exit status 1; not expected)
```
If I raise `aio-max-nr` with sysctl, it works fine.

Tested with `Ubuntu 20.04.2 LTS` in a VM, (8 cpus, passthrough)

**Comment by guy9** [comment] 2021-02-22 09:48
Thanks @tnozicka.
Since all of our U. examples use docker (version 4.1), I'd like to make sure our trainees don't get stuck. 
@slivne WDYT?

**Comment by kylerchin** [comment] 2021-05-14 05:13
It is still broken

**Comment by crispinkoech** [comment] 2021-05-26 16:18
Still broken on scylla `v4.4.0`

**Comment by dorlaor** [comment] 2021-05-26 23:40
It worked for me with podman (Fedora 32).
@penberg what's your take on it?

**Comment by avikivity** [comment] 2021-05-27 10:05
> Looks like this still doesn't work by default:
> 
> ```
> # cat /proc/sys/fs/aio-max-nr   
> 65536
> # docker run -it --rm scylladb/scylla:4.3.1
> running: (['/opt/scylladb/scripts/scylla_dev_mode_setup', '--developer-mode', '1'],)
> ...
> Scylla version 4.3.1-0.20210210.46650adcd with build-id bfaa518f22098de476b961b707925c71441bb81b starting ...
> command used: "/usr/bin/scylla --log-to-syslog 0 --log-to-stdout 1 --default-log-level info --network-stack posix --developer-mode=1 --overprovisioned --listen-address 172.17.0.10 --rpc-address 172.17.0.10 --seed-provider-parameters seeds=172.17.0.10 --blocked-reactor-notify-ms 999999999"
> parsed command line options: [log-to-syslog: 0, log-to-stdout: 1, default-log-level: info, network-stack: posix, developer-mode: 1, overprovisioned, listen-address: 172.17.0.10, rpc-address: 172.17.0.10, seed-provider-parameters: seeds=172.17.0.10, blocked-reactor-notify-ms: 999999999]
> Connecting to http://localhost:10000
> Starting the JMX server
> ERROR 2021-02-22 09:09:38,501 [shard 2] seastar - Could not setup Async I/O: Resource temporarily unavailable. The most common cause is not enough request capacity in /proc/sys/fs/aio-max-nr. Try increasing that number or reducing the amount of logical CPUs available for your application
> 2021-02-22 09:09:38,566 INFO exited: scylla (exit status 1; not expected)
> ```
> 
> If I raise `aio-max-nr` with sysctl, it works fine.
> 
> Tested with `Ubuntu 20.04.2 LTS` in a VM, (8 cpus, passthrough)


Perhaps we should have seastar fall back to epoll if there aren't enough aio slots configured.

**Comment by ducna-agile** [comment] 2021-07-22 02:52
I have run it in Macbook M1 and have error like this.

**Comment by alvisyahri97** [comment] 2021-08-20 05:05
me too, can't run it on Apple M1 ARM Architechture

**Comment by tzach** [comment] 2021-08-22 06:15
@alvisyahri97 is this true for later version of Scylla (e.g. 4.4.4) as well?

**Comment by avikivity** [comment] 2021-08-23 10:44
This issue is not related to Apple M1. I'm locking it. For M1, see [here](https://github.com/scylladb/scylla/issues/8642#issuecomment-896117797).

**Comment by avikivity** [comment] 2021-08-23 10:58
Actually, it could be that the same issue happens to hit M1 users, so unlocking.

**Comment by mslapek** [comment] 2023-11-17 08:51
When you use *Docker Desktop*, then you want to change sysctl parameters of the **Linux VM hosting the containers** (`--privileged` allows to do this):

```
docker run --rm -it --privileged ubuntu bash -c "echo \"fs.aio-max-nr = 1048576\" >> /etc/sysctl.conf && sysctl -p /etc/sysctl.conf"
```

This parameter will be visible in any container (because all containers share **the same** Linux kernel):

```
docker exec -it scylla-node1 cat /proc/sys/fs/aio-max-nr
```

Tested on MacBook ARM with M1 Max! ✨  (Scylla 5.2)

**Issues**

1. Looks like you need to run this on each restart of your computer.
2. Some Scylla containers can fail on start, then just restart them to retry.

CC https://github.com/scylladb/scylladb/issues/15072#issuecomment-1801070392

**Comment by fruch** [comment] 2023-12-04 23:18
> I can't get this to work on my Apple M2 Pro, what am I missing? using docker-compose, ran:
> 
> ```
> docker run --rm -it --privileged ubuntu bash -c "echo \"fs.aio-max-nr = 1048576\" >> /etc/sysctl.conf && sysctl -p /etc/sysctl.conf"
> ```
> 
> then run docker-compose up and it still fails, scylla 5.2.

you are commenting on an issue that is closed for 3 years now

I would recommend opening a new issue, with all the details.
i.e. which command you run, and what was the output and logs

**Comment by yngfoxx** [comment] 2024-06-11 22:23
> I can also confirm it starts to work applying this:
> 
> ```shell
> ➜  ~ sudo emacs /etc/sysctl.conf
> ➜  ~ sudo sysctl -p           
> fs.aio-max-nr = 1048576
> ➜  ~ cat /proc/sys/fs/aio-max-nr
> 1048576
> ```
> 
> After this change, no restart, it works fine.


Faced this issue recently, was really confused on how the above solution was meant to be,
adding this to improve clarity.

 ```shell
➜  ~ sudo nano /etc/sysctl.conf     # add or update "fs.aio-max-nr = 1048576" in file
➜  ~ sudo sysctl -p                 # change will be reflected
fs.aio-max-nr = 1048576
➜  ~ cat /proc/sys/fs/aio-max-nr
1048576
```

**Comment by BoringSoul** [comment] 2024-11-04 07:02
> I can also confirm it starts to work applying this:
> 
> ➜  ~ sudo emacs /etc/sysctl.conf
> ➜  ~ sudo sysctl -p           
> fs.aio-max-nr = 1048576
> ➜  ~ cat /proc/sys/fs/aio-max-nr
> 1048576
> After this change, no restart, it works fine.

it works!
