### ISSUE TITLE
node fails to start after service stop - seastar - Exiting on unhandled exception: exceptions::read_timeout_exception

### ISSUE THREAD

**Issue by harelassayag** [scylladb/scylla#3015] opened 2017-11-23 19:29 UTC
*Installation details*
Scylla version (or git commit hash): 2.1.rc0-0.20171122.91a5c9d
Cluster size: 4 nodes 1TB
OS (RHEL/CentOS/Ubuntu/AWS AMI): CentOS
node fails to start after stop service nemesis.
error message in log : **seastar - Exiting on unhandled exception: exceptions::read_timeout_exception (Operation timed out for system_schema.keyspaces - received only 0 responses from 1 CL=ONE.)** 
```
Nov 23 18:17:49 longevity-50gb-4d-2-0-db-node-487be86d-0-5 scylla[18159]:  [shard 0] database - Keyspace system: Reading CF schema_columnfamilies
Nov 23 18:17:49 longevity-50gb-4d-2-0-db-node-487be86d-0-5 scylla[18159]:  [shard 0] database - Keyspace system: Reading CF schema_columns
Nov 23 18:17:54 longevity-50gb-4d-2-0-db-node-487be86d-0-5 scylla[18159]:  [shard 0] init - Using default cluster name is not recommended. Using a unique cluster name will reduce the chance of adding nodes to th
Nov 23 18:17:54 longevity-50gb-4d-2-0-db-node-487be86d-0-5 scylla[18159]:  [shard 0] legacy_schema_migrator - Moving 0 keyspaces from legacy schema tables to the new schema keyspace (system_schema)
Nov 23 18:17:54 longevity-50gb-4d-2-0-db-node-487be86d-0-5 scylla[18159]:  [shard 0] legacy_schema_migrator - Dropping legacy schema tables
Nov 23 18:17:54 longevity-50gb-4d-2-0-db-node-487be86d-0-5 scylla[18159]:  [shard 0] legacy_schema_migrator - Completed migration of legacy schema tables
Nov 23 18:17:59 longevity-50gb-4d-2-0-db-node-487be86d-0-5 scylla[18159]:  [shard 0] seastar - Exiting on unhandled exception: exceptions::read_timeout_exception (Operation timed out for system_schema.keyspaces
Nov 23 18:17:59 longevity-50gb-4d-2-0-db-node-487be86d-0-5 scylla[18159]:  [shard 0] compaction_manager - Asked to stop
Nov 23 18:17:59 longevity-50gb-4d-2-0-db-node-487be86d-0-5 scylla[18159]:  [shard 7] compaction_manager - Asked to stop
Nov 23 18:17:59 longevity-50gb-4d-2-0-db-node-487be86d-0-5 scylla[18159]:  [shard 6] compaction_manager - Asked to stop
Nov 23 18:17:59 longevity-50gb-4d-2-0-db-node-487be86d-0-5 scylla[18159]:  [shard 14] compaction_manager - Asked to stop

...

Nov 23 18:17:49 longevity-50gb-4d-2-0-db-node-487be86d-0-5 scylla[18159]:  [shard 0] database - Keyspace system: Reading CF schema_columnfamilies
Nov 23 18:17:49 longevity-50gb-4d-2-0-db-node-487be86d-0-5 scylla[18159]:  [shard 0] database - Keyspace system: Reading CF schema_columns
Nov 23 18:17:54 longevity-50gb-4d-2-0-db-node-487be86d-0-5 scylla[18159]:  [shard 0] init - Using default cluster name is not recommended. Using a unique cluster name will reduce the chance of adding nodes to th
Nov 23 18:17:54 longevity-50gb-4d-2-0-db-node-487be86d-0-5 scylla[18159]:  [shard 0] legacy_schema_migrator - Moving 0 keyspaces from legacy schema tables to the new schema keyspace (system_schema)
Nov 23 18:17:54 longevity-50gb-4d-2-0-db-node-487be86d-0-5 scylla[18159]:  [shard 0] legacy_schema_migrator - Dropping legacy schema tables
Nov 23 18:17:54 longevity-50gb-4d-2-0-db-node-487be86d-0-5 scylla[18159]:  [shard 0] legacy_schema_migrator - Completed migration of legacy schema tables
Nov 23 18:17:59 longevity-50gb-4d-2-0-db-node-487be86d-0-5 scylla[18159]:  [shard 0] seastar - Exiting on unhandled exception: exceptions::read_timeout_exception (Operation timed out for system_schema.keyspaces - received only 0 responses from 1 CL=ONE.)
Nov 23 18:17:59 longevity-50gb-4d-2-0-db-node-487be86d-0-5 scylla[18159]:  [shard 0] compaction_manager - Asked to stop
Nov 23 18:17:59 longevity-50gb-4d-2-0-db-node-487be86d-0-5 scylla[18159]:  [shard 7] compaction_manager - Asked to stop
Nov 23 18:17:59 longevity-50gb-4d-2-0-db-node-487be86d-0-5 scylla[18159]:  [shard 6] compaction_manager - Asked to stop
Nov 23 18:17:59 longevity-50gb-4d-2-0-db-node-487be86d-0-5 scylla[18159]:  [shard 14] compaction_manager - Asked to stop

...

```
full log:[scylladb-users-upload.s3.amazonaws.com/3015/log.tar.gz](scylladb-users-upload.s3.amazonaws.com/3015/log.tar.gz)

**Comment by glommer** [comment] 2017-11-23 19:33
System timeout reads upon restart shouldn't have a timeout - I am working on it right now.

That is #2462

**Comment by slivne** [comment] 2017-11-26 05:15
I dont understand why thisnis.much slower then before ...

What are we doing in the background that takea so much time

Did we chnage the boot sequence

Gluabers change maybe correct but it still seems there is something else
that triggered this

**Comment by tgrabiec** [comment] 2018-01-02 08:17
@harelassayag Does it not timeout on 1.7?

**Comment by slivne** [comment] 2018-02-08 10:19
@tgrabiec we had a user report he is hitting the issue on boot on 1.7.5 - the user has found some correlation in replay commitlog.

**Comment by tgrabiec** [comment] 2018-02-08 10:48
@slivne What kind of correlation? Commit log replay starts after schema is loaded, so it shouldn't interfere with it. Here it's schema loading which times out.

This issue is probably fixed in master by 9c39197

**Comment by slivne** [comment] 2018-02-08 10:51
I am sure we will not see it anymore because of that- the issue is why is
it taking so long to begin with ?

**Comment by tgrabiec** [comment] 2018-02-08 11:02
Looking at the log, the restart happened after a crash. Maybe the disk was still overloaded with background core dump write-back to disk? If we had host metrics, we could tell.

**Comment by tzach** [comment] 2018-02-18 11:26
@harelassayag do you have the metrics (see tgrabiec request above)
Can you please test if scylla restarts while core dump is written?

**Comment by slivne** [comment] 2018-02-22 10:11
@harelassayag - ping

**Comment by slivne** [comment] 2018-04-29 10:55
@harelassayag / @roydahan - we are not supposed to hit timeout on system tables anymore - if we do hit the issue please create a new one with all the info

**Comment by glommer** [comment] 2018-04-30 13:42
@slivne then please close the issue.

**Closed** 2018-05-06 07:50 UTC
Labels: bug
