### ISSUE TITLE
Alternator: wrong ReturnValues=ALL_NEW results when update expression has both REMOVE and SET/ADD

### ISSUE THREAD

**Issue by dimaqq** [scylladb/scylla#9542] opened 2021-10-29 02:58 UTC
Reported in https://github.com/HENNGE/aiodynamo/issues/27#issuecomment-953555282

Code: https://github.com/HENNGE/aiodynamo/blob/5f5170c6d3e8bbda5bab3cbd1adb2a0a90cee00b/tests/integration/test_client.py#L187-L218

Adding bits to a set value: https://github.com/HENNGE/aiodynamo/blob/5f5170c6d3e8bbda5bab3cbd1adb2a0a90cee00b/tests/integration/test_client.py#L203

**Comment by nyh** [comment] 2021-10-31 07:36
Is this a duplicate of issue #5893?

That issue is about the `ADD` command indeed not yet being supported in the old-style `AttributeUpdates`. Note that we did implement same operation for the newer `UpdateExpression` syntax, so there is no real reason why this isn't implemented - it's just something we never got around to.

Can you please confirm that your test code is using `AttributeUpdates`, not `UpdateExpression`, in the requestion?

**Comment by dimaqq** [comment] 2021-11-01 04:42
I'm pretty sure the code uses `UpdateExpression`, thus yes, must be a dup.

**Comment by dimaqq** [comment] 2021-11-01 04:53
Maybe I got confused by which is new and which is old.
The referenced library does not use `AttributeUpdates`.

**Comment by nyh** [comment] 2021-11-01 07:17
Oh, so you're saying that the failing request is using `UpdateExpression`, not `AttributeUpdates`?
Can you please paste here the exact request that is being sent, and what sort of "failure" you are seeing? 

We do have tests that `ADD` operations in `UpdateExpression` do work in Alternator (https://github.com/scylladb/scylla/blob/master/test/alternator/test_update_expression.py#L729) but it's always possible we missed something and there's some corner case or way of using this operation that doesn't work.

**Comment by ojii** [comment] 2021-11-04 01:42
Using `Scylla version 4.6.dev-0.20211027.a21b1fbb2 with build-id d790046d27e128b2811fa63ef0ef0129b4ef561a` and dynalite.

I have a table with HASH being `h` (string) and RANGE being `r` (string).

First I create a item:

```
POST http://localhost:8087
Content-Type: application/x-amz-json-1.0
X-Amz-Date: 20211104T013532Z
X-Amz-Target: DynamoDB_20120810.PutItem
Authorization: AWS4-HMAC-SHA256 Credential=local/20211104/local-testing/dynamodb/aws4_request, SignedHeaders=content-type;host;x-amz-date;x-amz-target, Signature=91dc893a551ca858b989ccdf294bb0301355c0f14b6c051c71cb382b63a6e53a

{"TableName":"update-item-test","Item":{"h":{"S":"hkv"},"r":{"S":"rkv"},"string-key":{"S":"this is a string"},"number-key":{"N":"123"},"list-key":{"L":[{"S":"hello"},{"S":"world"}]},"set-key-one":{"SS":["hello","world"]},"set-key-two":{"SS":["hello","world"]},"dead-key":{"S":"foo"}},"ReturnValues":"NONE"}
```

Then I update an item using `ReturnValues=ALL_NEW`

Request:
```
POST http://localhost:8087
Content-Type: application/x-amz-json-1.0
X-Amz-Date: 20211104T013532Z
X-Amz-Target: DynamoDB_20120810.UpdateItem
Authorization: AWS4-HMAC-SHA256 Credential=local/20211104/local-testing/dynamodb/aws4_request, SignedHeaders=content-type;host;x-amz-date;x-amz-target, Signature=f4723c269b1a9be9b33790362496bde0ba4e6a921447198cea2ea1eaf5e68d89

{"TableName":"update-item-test","Key":{"h":{"S":"hkv"},"r":{"S":"rkv"}},"UpdateExpression":"SET #n0 = :v0, #n1 = #n1 - :v1, #n2 = list_append(#n2, :v2) REMOVE #n3 ADD #n4 :v3 DELETE #n5 :v4","ReturnValues":"ALL_NEW","ExpressionAttributeNames":{"#n0":"string-key","#n1":"number-key","#n2":"list-key","#n3":"dead-key","#n4":"set-key-one","#n5":"set-key-two"},"ExpressionAttributeValues":{":v0":{"S":"new value"},":v1":{"N":"12"},":v2":{"L":[{"S":"!"}]},":v3":{"SS":["hoge"]},":v4":{"SS":["hello"]}}}
```

Dynalite Response:
```
{"Attributes": {"h": {"S": "hkv"}, "r": {"S": "rkv"}, "string-key": {"S": "new value"}, "number-key": {"N": "111"}, "list-key": {"L": [{"S": "hello"}, {"S": "world"}, {"S": "!"}]}, "set-key-one": {"SS": ["hello", "world", "hoge"]}, "set-key-two": {"SS": ["world"]}}}
```

Scylla Response:

```
{"Attributes": {"h": {"S": "hkv"}, "r": {"S": "rkv"}, "set-key-one": {"SS": ["hello", "world"]}, "list-key": {"L": [{"S": "hello"}, {"S": "world"}, {"S": "!"}]}, "number-key": {"N": "111"}, "set-key-two": {"SS": ["world"]}, "string-key": {"S": "new value"}}}
```

If I do a separate GetItem afterwards, the value is correct (both dynalite & scylla):

```
{"Item": {"h": {"S": "hkv"}, "r": {"S": "rkv"}, "list-key": {"L": [{"S": "hello"}, {"S": "world"}, {"S": "!"}]}, "number-key": {"N": "111"}, "set-key-one": {"SS": ["world", "hello", "hoge"]}, "set-key-two": {"SS": ["world"]}, "string-key": {"S": "new value"}}}
```

So the issue seems to be `ReturnValues=ALL_NEW` rather than the `UpdateItem` itself.

**Comment by psarna** [comment] 2021-11-04 06:11
@ojii what's the issue though? Dynalite seems to return the fields in different order, but the returned JSON values correspond to each other - both Dynalite and Scylla returned the same document, didn't they? Their text representation is different, but both are correct and equivalent to each other (unless I missed some subtle detail while browsing this issue on my phone)

**Comment by ojii** [comment] 2021-11-04 06:27
@psarna sorry about all that extra stuff in the response, i just re-used the test from our existing suite.

The issue is `set-key-one` which gets updated via `ADD #n4 :v3` in were `:v3` is `{SS: ["hoge"]}`. Dynalite returns the new value as `"set-key-one": {"SS": ["hello", "world", "hoge"]}` but scylla returns `"set-key-one": {"SS": ["hello", "world"]}`.

**Comment by psarna** [comment] 2021-11-04 06:31
Ah, ok, got it. We'll prepare a reproducing test case and work on the problem, thanks for reporting

**Comment by nyh** [comment] 2021-11-04 08:45
I wrote a simple test for `ReturnValues = ALL_NEW` and `ADD`, and it actually worked correctly!
So it turns out that the problem is more subtle than just ADD being broken. It's not just the `ADD`, it's the combination of `ADD` for one column and `REMOVE` for a different column that for some reason breaks `ALL_NEW`. Your test case was a great help to figure out what's wrong, and here is greatly simplified test which shows the cause of the problem. The test passes on DynamoDB but fails on Scylla:
```
def test_update_item_returnvalues_9542(test_table_s):
    p = random_string()
    test_table_s.put_item(Item={'p': p, 's': set([1, 2]), 'd': 'foo'})
    ret=test_table_s.update_item(Key={'p': p}, ReturnValues='ALL_NEW',
        UpdateExpression='REMOVE d ADD s :v',
        ExpressionAttributeValues={':v': set([3])})
    assert ret['Attributes']['s'] == set([1, 2, 3])
```

Interestingly, if I change the "REMOVE d" to a "REMOVE x" (i.e., remove some column that never existed in the item), the test begins to pass. So apparently something in the logic of how `ALL_NEW` merges the old content of the item with newly set attributes is broken when one of the attributes gets deleted.

When I have a clearer understand of the cause, I'll retitle this bug again :-)

**Comment by nyh** [comment] 2021-11-04 09:12
By the way, the bug isn't even specific to `ADD`. The `REMOVE` breaks the `ALL_NEW` of any other attribute set in the same command. The following test also fails, and doesn't involve any sets:

```python
def test_update_item_returnvalues_all_new_remove_etc(test_table_s):
    p = random_string()
    test_table_s.put_item(Item={'p': p, 's': 'dog', 'd': 'foo'})
    ret=test_table_s.update_item(Key={'p': p}, ReturnValues='ALL_NEW',
        UpdateExpression='REMOVE d SET s = :v',
        ExpressionAttributeValues={':v': 'cat'})
    assert ret['Attributes']['s'] == 'cat'
```

**Comment by nyh** [comment] 2021-11-04 09:36
It appears we have a serious low-level bug in the JSON library's `rjson::set_with_string_name()` function..
Check this out - printing the `_return_attributes` variable before and after the `SET` operation shows:
before:
```
{"p":{"S":"XJPFK1K9RU"},"d":{"S":"foo"},"s":{"S":"dog"}}
```
after:
```
{"p":{"S":"XJPFK1K9RU"},"d":{"S":"foo"},"s":{"S":"dog"},"s":{"S":"cat"}}
```
Note how instead of the value for `s`, which was `dog`, being replaced by `cat`, we actually now have two values for the same key, which is an obvious bug in the JSON library that I would need to investigate. A map must not have two values for the same key...

Later removing "d" makes random changes to the _order_ of these silly double keys:
```
{"p":{"S":"XJPFK1K9RU"},"s":{"S":"cat"},"s":{"S":"dog"}}
```
Which explains why we got this bug only when also removing a key, but the remove itself was not the source of this bug, it just exposed it.

The scary thing is that maybe we have this bug in other places, if `rjson::set_with_string_name()` cannot be trusted :-(

**Comment by nyh** [comment] 2021-11-04 09:53
@psarna I can't believe we never noticed this before, but our `rjson::rjson::set()` and friends use RapidJson's `AddMember` method, which as its name suggests, only **adds** a member to a document - it does not check if one was already there. This is a low-level bug which we'll need to fix across the codebase (I'll open a new issue about it) and then we'll get this issue fixed.

**Comment by nyh** [comment] 2021-11-04 13:51
Sent to the mailing list a patch 'alternator: fix bug in ReturnValues=ALL_NEW" fixing (and testing) this bug.
It doesn't yet overhaul or review all the set()s - it is limited to fixing this bug, and introduces a replace() function that does what we thought set() does.

**Closed** 2021-11-05 00:03 UTC
Labels: bug, User Request, Alternator

**Comment by avikivity** [comment] 2021-11-08 10:48
@nyh please backport (note 4.6 was branched)

**Comment by nyh** [comment] 2021-11-08 12:39
4.6 already includes this patch (it was apparently branched after this patch, I wasn't aware of it).
Backported to next-4.5 (db66b62e80863e0eafb0d99b00553ee33b292604)
Backported to next-4.4 (c49cd5d9b664997e781de319f33520893c4fc897).

Not backporting to 4.3 according to our two-supported-release policy. This means that versions based on 4.3 will no longer get this and other bug fixes. @avikivity FYI.
