### ISSUE TITLE
Possible race condition between announcing a new node to clients and opening port 9042

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylla#5558] opened 2020-01-05 13:58 UTC
I see this when running cassandra-stress in parallel with starting a new node:

```
WARN  15:56:44,559 Error creating netty channel to /10.88.1.3:9042
com.datastax.shaded.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: /10.88.1.3:9042
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[na:1.8.0_232]
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) ~[na:1.8.0_232]
	at com.datastax.shaded.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:225) ~[scylla-driver-core-3.7.1-scylla-2-shaded.jar:na]
	at com.datastax.shaded.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:291) ~[scylla-driver-core-3.7.1-scylla-2-shaded.jar:na]
	at com.datastax.shaded.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:634) [scylla-driver-core-3.7.1-scylla-2-shaded.jar:na]
	at com.datastax.shaded.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:581) [scylla-driver-core-3.7.1-scylla-2-shaded.jar:na]
	at com.datastax.shaded.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:498) [scylla-driver-core-3.7.1-scylla-2-shaded.jar:na]
	at com.datastax.shaded.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:460) [scylla-driver-core-3.7.1-scylla-2-shaded.jar:na]
	at com.datastax.shaded.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:131) [scylla-driver-core-3.7.1-scylla-2-shaded.jar:na]
	at com.datastax.shaded.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [scylla-driver-core-3.7.1-scylla-2-shaded.jar:na]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_232]
Caused by: java.net.ConnectException: Connection refused
```

Looks like the new node was announced before it completed opening the native transport port.

**Comment by slivne** [comment] 2020-01-14 12:48
@asias I think we have a state RPC_READY in gossip - was it supposed to deal with this ?

**Comment by slivne** [comment] 2020-01-16 10:16
@asias ping

**Comment by asias** [comment] 2020-01-16 11:27
Yes, see a42b2895c2ac013a8ab1e37d253d26bd36093f7d.

**Comment by slivne** [comment] 2020-01-26 11:15
@avikivity which version had this issue - this should not happen

**Comment by asias** [comment] 2020-02-03 00:11
Another possibility is that cassandra-stress does not really respect the "Node UP event" correctly.

**Comment by slivne** [comment] 2020-03-26 23:57
I am closing this issue (since we did not get an answer on the version)

As Asias confirmed we have a new state in gossip RPC_READY marking that CQL is open and all clients should be notified only after that.

All versions higher than 3.1 should have this fixed. 

If this is not the case please reopen and specify the exact version tested and the scenario.

**Closed by slivne** 2020-03-26 23:57 UTC
Labels: bug, gossip, stability
