### ISSUE TITLE
1.1 EC2 AMI - i2.8xlarge utilize core 0 

### ISSUE THREAD

**Issue by nirmaayan** [scylladb/scylla#1301] opened 2016-05-31 09:15 UTC
## Installation details
Scylla version (or git commit hash): 1.1
Cluster size: 3 nodes vs 10 loaders 
Scylla - 2.8xlarge 
Loader - c4.4xlarge

/etc/sysconfig/scylla-server

## Version 1.0.1 scylla arguments (for posix mode)
SCYLLA_ARGS="--log-to-syslog 1 --log-to-stdout 0 --default-log-level info --collectd-address=127.0.0.1:25826 --collectd=1 --collectd-poll-period 3000 --network-stack posix **--cpuset 1-31  --smp 31 **"

## Version 1.1 scylla arguments (for posix mode)
SCYLLA_ARGS="--log-to-syslog 1 --log-to-stdout 0 --default-log-level info --collectd-address=127.0.0.1:25826 --collectd=1 --collectd-poll-period 3000 --network-stack posix"

ps -ef | grep scylla

Version 1.0.1
```
[centos@ip-10-152-77-69 ~]$ ps -ef | grep scylla
scylla     2701      1 99 07:10 ?        05:38:42 /usr/bin/scylla --log-to-syslog 1 --log-to-stdout 0 --default-log-level info --collectd-address=127.0.0.1:25826 --collectd=1 --collectd-poll-period 3000 --network-stack posix --cpuset 1-31 --smp 31 --num-io-queues 31 --max-io-requests 248
scylla     2765      1  2 07:10 ?        00:03:08 java -Dcassandra.jmx.local.port=7199 -Xmx256m -XX:+UseSerialGC -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -jar /usr/lib/scylla/jmx/scylla-jmx-1.0.jar
centos    31752  31716  0 09:12 pts/0    00:00:00 grep --color=auto scylla
```

Version 1.1
```
ps -ef | grep scylla
4 S scylla     2699      1 99  80   0 - 4295138113 ep_pol 04:48 ?   1-19:39:35 /usr/bin/scylla --log-to-syslog 1 --log-to-stdout 0 --default-log-level info --collectd-address=127.0.0.1:25826 --collectd=1 --collectd-poll-period 3000 --network-stack posix --num-io-queues 32 --max-io-requests 256
4 S scylla     2765      1  2  80   0 - 1083593 futex_ 04:48 ?      00:06:49 java -Dcassandra.jmx.local.port=7199 -Xmx256m -XX:+UseSerialGC -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -jar /usr/lib/scylla/jmx/scylla-jmx-1.0.jar
0 S centos    32631  29724  0  80   0 - 28162 pipe_w 08:51 pts/0    00:00:00 grep --color=auto scylla
```
[centos@ip-172-30-0-168 ~]$ ethtool -i eth0
driver: ixgbevf
version: 2.12.1-k-rh7.2
firmware-version:
bus-info: 0000:00:03.0
supports-statistics: yes
supports-test: yes
supports-eeprom-access: no
supports-register-dump: yes
supports-priv-flags: no

Attached 1.0.1 & 1.1 posix_net_conf.sh
[1.0.1_posix.txt](https://github.com/scylladb/scylla/files/290696/1.0.1_posix.txt)
[1.1_posix.txt](https://github.com/scylladb/scylla/files/290695/1.1_posix.txt)

**Comment by tzach** [comment] 2016-06-05 12:10
@slivne is this fix on 1.1.1 AMI? 
if not, let generate new AMI with this fix

**Comment by slivne** [comment] 2016-06-05 12:31
Its a bug we need first to fix it :( then only can we generate an AMI.

**Comment by slivne** [comment] 2016-06-06 09:50
there are patches on the mailing list from Takuya that should sort this out - @penberg can you please review
The issue is that we merged a patchset from Takuya for scylla but did not merge the scylla-ami patches
The scylla patches are "[PATCH scylla 0/6] Introduce SET_NIC for non-AMI environment"

The scylla ami patches are:
[PATCH scylla-ami 1/3] 'sh -x -e' is not valid since all scripts converted to bash script, so remove them"
[PATCH scylla-ami 2/3] convert scylla_install_ami to bash script
[PATCH scylla-ami 3/3] Move --cpuset/--smp parameter settings from scylla_sysconfig_setup to scylla_ami_setup

I am not sure if the 1.1 branch has the same issue or this is only true for branch-1.2 and 1.1 issue is different still searching

**Comment by slivne** [comment] 2016-06-06 10:01
the issue in 1.1 is different 

the patch 73fa36b41604d8ef5e006c2af97e95d42fffc151 fixed a bug in generic usage of the scylla_sysconfig_setup yet caused an issue for the ami case 

the script scylla/dist/ami/files/scylla-ami/scylla_ami_setup invokes scylla_sysconfig_setup with
```
    /usr/lib/scylla/scylla_sysconfig_setup --nic eth0 --setup-nic --ami
```

before the 73fa36b41604d8ef5e006c2af97e95d42fffc151 commit the --setup_nic did not have an effect so the script worked "correctly" - no it doesn't.

what we can do is invoke the scylla_sysconfig_setup without the setup_nic flag - it should correct things back 

@penberg can you also review this and comment - if its ok - lets create a patch.

**Comment by penberg** [comment] 2016-06-06 10:17
I think it's fine for the AMI to use ``--setup-nic`` but we should fix ``scylla_sysconfig_setup`` to always respect the AMI flag on large machines like this:

```
diff --git a/dist/common/scripts/scylla_sysconfig_setup b/dist/common/scripts/scylla_sysconfig_setup
index 4efe5eb..f9bd495 100755
--- a/dist/common/scripts/scylla_sysconfig_setup
+++ b/dist/common/scripts/scylla_sysconfig_setup
@@ -76,7 +76,7 @@ echo Setting parameters on $SYSCONFIG/scylla-server
 ETHDRV=`/usr/lib/scylla/dpdk_nic_bind.py --status | grep if=$NIC | sed -e "s/^.*drv=//" -e "s/ .*$//"`
 ETHPCIID=`/usr/lib/scylla/dpdk_nic_bind.py --status | grep if=$NIC | awk '{print $1}'`
 NR_CPU=`cat /proc/cpuinfo |grep processor|wc -l`
-if [ "$AMI" = "yes" ] && [ $NR_CPU -ge 8 ] && [ "$SET_NIC" = "no" ]; then
+if [ "$AMI" = "yes" ] && [ $NR_CPU -ge 8 ]; then
     NR=$((NR_CPU - 1))
     SET_NIC="yes"
     SCYLLA_ARGS="$SCYLLA_ARGS --cpuset 1-$NR  --smp $NR"
```

**Comment by slivne** [comment] 2016-06-06 12:49
1.1 - fixed by 32890109105345917b871d2cc95fb87f82155c85
(reverting commit)

1.2 - fixed by scylladb/scylla-ami@863cc4598a096de23058b0a2e2b14c490e05271c

**Closed** 2016-06-06 13:20 UTC
Labels: bug

**Comment by tzach** [comment] 2016-06-09 14:50
before the fix
![image](https://cloud.githubusercontent.com/assets/170200/15934001/95109bde-2e6a-11e6-8085-b2773f3e9d6e.png)

after the fix
![image](https://cloud.githubusercontent.com/assets/170200/15934030/ad561b56-2e6a-11e6-8100-77aced1afedc.png)

**Comment by avikivity** [comment] 2016-06-13 06:38
Without scale, you can't compare the two images.
