### ISSUE TITLE
coredump during node decommission 

### ISSUE THREAD

**Issue by yarongilor** [scylladb/scylla#5086] opened 2019-09-23 10:19 UTC
Installation details
Scylla version (or git commit hash): 3.1.0.rc7-0.20190915.024d1563a
Cluster size: 6
OS (RHEL/CentOS/Ubuntu/AWS AMI): ami-0a01b94dffe4bcc0d

scenario: 50GB longevity - during nodetool_decommission nemesis of 10.0.63.76 node, there was a core dump on 10.0.244.153 node.

failure scenario and error:
```
< t:2019-09-19 23:04:07,694 f:nemesis.py      l:585  c:sdcm.nemesis         p:INFO  > sdcm.nemesis.ChaosMonkey: >>>>>>>>>>>>>Started random_disrupt_method nodetool_decommission
< t:2019-09-19 23:04:08,458 f:nemesis.py      l:338  c:sdcm.nemesis         p:DEBUG > sdcm.nemesis.ChaosMonkey: Set current_disruption -> Decommission Node longevity-tls-50gb-4d-3-1-db-node-5979c9a0-5 [34.248.223.143 | 10.0.63.76] (seed: False)
[jenkins@aws-eu-builder3 latest]$ grep -v 'ChaosMonkey on target' sct20_9.log | grep -i 'found coredump\|Set current_disruption\|segmentation\|<<<<<<<<<\|>>>>>>>>>\|p:ERROR > Traceback'
< t:2019-09-20 01:36:48,942 f:cluster.py      l:833  c:sdcm.cluster         p:DEBUG > Node longevity-tls-50gb-4d-3-1-db-node-5979c9a0-8 [34.245.136.197 | 10.0.244.153] (seed: False): Found coredump file: /var/lib/systemd/coredump/core.scylla.996.c212eda51d7d40c1b68eb746938de6ae.1730.1568943298000000
< t:2019-09-20 04:41:18,886 f:nemesis.py      l:1071 c:sdcm.nemesis         p:ERROR > Traceback (most recent call last):
```

coredump details:
```
(CoreDumpEvent Severity.CRITICAL): node=Node longevity-tls-50gb-4d-3-1-db-node-5979c9a0-8 [34.245.136.197 | 10.0.244.153] (seed: False)
corefile_url=
https://storage.cloud.google.com/upload.scylladb.com/core.scylla.996.c212eda51d7d40c1b68eb746938de6ae.1730.1568943298000000/core.scylla.996.c212eda51d7d40c1b68eb746938de6ae.1730.1568943298000000.gz
backtrace= PID: 1730 (scylla)
UID: 996 (scylla)
GID: 1001 (scylla)
Signal: 11 (SEGV)
Timestamp: Fri 2019-09-20 01:34:58 UTC (1min 50s ago)
Command Line: /usr/bin/scylla --blocked-reactor-notify-ms 500 --abort-on-lsa-bad-alloc 1 --abort-on-seastar-bad-alloc --log-to-syslog 1 --log-to-stdout 0 --default-log-level info --network-stack posix --io-properties-file=/etc/scylla.d/io_properties.yaml --cpuset 1-7,9-15
Executable: /opt/scylladb/libexec/scylla
Control Group: /
Boot ID: c212eda51d7d40c1b68eb746938de6ae
Machine ID: df877a200226bc47d06f26dae0736ec9
Hostname: ip-10-0-244-153.eu-west-1.compute.internal
Coredump: /var/lib/systemd/coredump/core.scylla.996.c212eda51d7d40c1b68eb746938de6ae.1730.1568943298000000
Message: Process 1730 (scylla) of user 996 dumped core.

Stack trace of thread 1732:
#0 0x00000000024aca5a _ZN7seastar12shared_mutex4wakeEv (scylla)

download_instructions=
gsutil cp gs://upload.scylladb.com/core.scylla.996.c212eda51d7d40c1b68eb746938de6ae.1730.1568943298000000/core.scylla.996.c212eda51d7d40c1b68eb746938de6ae.1730.1568943298000000.gz .
gunzip /var/lib/systemd/coredump/core.scylla.996.c212eda51d7d40c1b68eb746938de6ae.1730.1568943298000000.gz
```
test logs:
job log: scratch.scylladb.com/qa_issues/sct_08_42_22_09_2019.log.gz
```
$ hydra investigate show-logs 5979c9a0-a1c1-4601-a2c3-63f1850766d9 | grep '|'
|                                            Log links for testrun with test id 5979c9a0-a1c1-4601-a2c3-63f1850766d9                                             |
| Log type              | Link                                                                                                                                   |
| events                | https://cloudius-jenkins-test.s3.amazonaws.com/5979c9a0-a1c1-4601-a2c3-63f1850766d9/events_log.zip                                     |
| db-cluster            | https://cloudius-jenkins-test.s3.amazonaws.com/5979c9a0-a1c1-4601-a2c3-63f1850766d9/longevity-tls-50gb-4d-3-1-db-cluster-5979c9a0.zip  |
| monitor-set           | https://cloudius-jenkins-test.s3.amazonaws.com/5979c9a0-a1c1-4601-a2c3-63f1850766d9/longevity-tls-50gb-4d-3-1-monitor-set-5979c9a0.zip |
| monitoring_data_stack | https://cloudius-jenkins-test.s3.amazonaws.com/5979c9a0-a1c1-4601-a2c3-63f1850766d9/monitoring_data_stack_branch-2.4_3.1.tar.gz        |
```

**Comment by bhalevy** [comment] 2019-09-23 12:12
marking all possible memory corruptions as showstoppers...

**Comment by bhalevy** [comment] 2019-09-26 17:07
@amoskong / @avikivity could toppartitions be involved here too? (#5104)

**Comment by amoskong** [comment] 2019-09-27 05:45
The coredump occurred after decommission is on `longevity-tls-50gb-4d-3-1-db-node-5979c9a0-8 [34.245.136.197 | 10.0.244.153]`

But 3 toppartitions nemesis were executed on `longevity-tls-50gb-4d-3-1-db-node-5979c9a0-6 [52.214.107.136 | 10.0.42.134]`, and there is a big time gap between coredump and toppartitions nemesis.

So it's unrelated.

-------------
Btw, I saw there is another coredump occurred around `t:2019-09-18 06:40:22,124` on node-6.
The first toppartitions nemesis executed at ` t:2019-09-16 23:28:37,794` (succeeded), the second  toppartitions nemesis executed at ` t:2019-09-17 15:04:29,732 ` (nodetool cmd failed).

It's also a big time gap. But those two toppartitions nemeis and the coredump are on same node (node-6)

----

```
< toppartitions 1>

t:2019-09-16 23:28:37,794 > Node longevity-tls-50gb-4d-3-1-db-node-5979c9a0-6 [52.214.107.136 | 10.0.42.134] (seed: False): Command 'nodetool -u cassandra -pw cassandra  toppartitions keyspace1 standard1 4064 -s 581 -k 7 -a writes' duration -> 29.2410111427 s

< toppartitions 2>

< t:2019-09-17 15:02:02,136 > sdcm.nemesis.ChaosMonkey: >>>>>>>>>>>>>Started random_disrupt_method show_toppartitions
< t:2019-09-17 15:04:29,732 > RemoteCmdRunner [centos@10.0.42.134]: Command "nodetool -u cassandra -pw cassandra  toppartitions mview users_by_last_name 5165 -s 803 -k 5 -a writes,reads" finished with status 2
                             > Exit code: 2
                             > 
                             > Stdout:
                             > 
                             > 
                             > 
                             > Stderr:
                             > 
                             >   at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
                             >   at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
                             >   at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
                             >   at java.io.ObjectOutputStream.defaultWriteObject(ObjectOutputStream.java:441)
                             >   at java.lang.Throwable.writeObject(Throwable.java:1014)
                             >   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                             >   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
                             >   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                             >   at java.lang.reflect.Method.invoke(Method.java:498)
                             >   at java.io.ObjectStreamClass.invokeWri

< t:2019-09-17 15:22:50,801  >>>>Started random_disrupt_method soft_reboot_node
< t:2019-09-17 16:42:46,715  >>>>Started random_disrupt_method truncate
< t:2019-09-17 17:02:18,540  >>>>Started random_disrupt_method major_compaction
< t:2019-09-17 22:48:38,894  <<<<Finished random_disrupt_method major_compaction
< t:2019-09-17 23:07:23,360  >>>>Started random_disrupt_method destroy_data_then_repair
< t:2019-09-18 02:55:23,098  <<<<Finished random_disrupt_method destroy_data_then_repair
< t:2019-09-18 03:15:01,944  >>>>Started random_disrupt_method nodetool_enospc
< t:2019-09-18 03:15:02,621  <<<<Finished random_disrupt_method nodetool_enospc
< t:2019-09-18 03:34:40,364  >>>>Started random_disrupt_method nodetool_enospc
< t:2019-09-18 03:34:41,668  <<<<Finished random_disrupt_method nodetool_enospc
< t:2019-09-18 03:53:38,228  >>>>Started random_disrupt_method modify_table
< t:2019-09-18 03:54:08,948  <<<<Finished random_disrupt_method modify_table
< t:2019-09-18 04:13:20,668  >>>>Started random_disrupt_method truncate
< t:2019-09-18 04:35:05,656  >>>>Started random_disrupt_method modify_table
< t:2019-09-18 04:35:34,818  <<<<Finished random_disrupt_method modify_table
< t:2019-09-18 04:54:57,590  >>>>Started random_disrupt_method terminate_and_replace_node

<coredump ....>

< t:2019-09-18 06:40:22,124  Node longevity-tls-50gb-4d-3-1-db-node-5979c9a0-6 [52.214.107.136 | 10.0.42.134] (seed: False): Found coredump file: /var/lib/systemd/coredump/core.scylla.996.fda02d2cfd394d57ad5130894d4813bc.64535.1568788699000000

< t:2019-09-18 07:02:22,589  >>>>Started random_disrupt_method restart_then_repair_node
< t:2019-09-18 12:07:47,684  <<<<Finished random_disrupt_method restart_then_repair_node
< t:2019-09-18 12:24:14,996  >>>>Started random_disrupt_method restart_with_resharding
< t:2019-09-18 12:44:32,996  >>>>Started random_disrupt_method restart_then_repair_node
< t:2019-09-19 00:05:05,992  <<<<Finished random_disrupt_method restart_then_repair_node
< t:2019-09-19 00:20:28,155  >>>>Started random_disrupt_method snapshot_operations
< t:2019-09-19 00:23:12,599  <<<<Finished random_disrupt_method snapshot_operations
< t:2019-09-19 00:39:10,356  >>>>Started random_disrupt_method terminate_and_replace_node
< t:2019-09-19 03:13:29,837  <<<<Finished random_disrupt_method terminate_and_replace_node
< t:2019-09-19 03:31:25,786  >>>>Started random_disrupt_method multiple_hard_reboot_node
< t:2019-09-19 03:37:36,993  <<<<Finished random_disrupt_method multiple_hard_reboot_node
< t:2019-09-19 03:54:44,165  >>>>Started random_disrupt_method hard_reboot_node
< t:2019-09-19 03:57:46,554  <<<<Finished random_disrupt_method hard_reboot_node
< t:2019-09-19 04:15:06,109  >>>>Started random_disrupt_method stop_start_scylla_server
< t:2019-09-19 04:16:54,348  <<<<Finished random_disrupt_method stop_start_scylla_server
< t:2019-09-19 04:34:06,236  >>>>Started random_disrupt_method destroy_data_then_rebuild
< t:2019-09-19 05:27:15,139  <<<<Finished random_disrupt_method destroy_data_then_rebuild
< t:2019-09-19 05:43:29,679  >>>>Started random_disrupt_method show_toppartitions

< toppartitions 3>

t:2019-09-19 06:06:11,870 f:ode longevity-tls-50gb-4d-3-1-db-node-5979c9a0-5 [34.244.194.166 | 10.0.63.76] (seed: False): Command 'nodetool -u cassandra -pw cassandra  toppartitions keyspace1 standard1 4151 -s 695 -k 8 -a reads' duration -> 29.4368951321 s

< t:2019-09-19 06:06:12,762  <<<<Finished random_disrupt_method show_toppartitions
< t:2019-09-19 06:22:34,757  >>>>Started random_disrupt_method restart_then_repair_node
< t:2019-09-19 16:06:19,678  <<<<Finished random_disrupt_method restart_then_repair_node
< t:2019-09-19 16:23:06,647  >>>>Started random_disrupt_method terminate_and_replace_node
< t:2019-09-19 18:55:58,591  <<<<Finished random_disrupt_method terminate_and_replace_node
< t:2019-09-19 19:12:24,329  >>>>Started random_disrupt_method stop_wait_start_scylla_server
< t:2019-09-19 19:19:18,348  <<<<Finished random_disrupt_method stop_wait_start_scylla_server
< t:2019-09-19 19:35:45,763  >>>>Started random_disrupt_method terminate_and_replace_node
< t:2019-09-19 21:45:45,596  <<<<Finished random_disrupt_method terminate_and_replace_node
< t:2019-09-19 22:02:27,666  >>>>Started random_disrupt_method nodetool_drain
< t:2019-09-19 22:08:52,868  <<<<Finished random_disrupt_method nodetool_drain
< t:2019-09-19 22:25:40,560  >>>>Started random_disrupt_method hard_reboot_node
< t:2019-09-19 22:28:53,515  <<<<Finished random_disrupt_method hard_reboot_node
< t:2019-09-19 22:46:05,533  >>>>Started random_disrupt_method stop_start_scylla_server
< t:2019-09-19 22:47:50,214  <<<<Finished random_disrupt_method stop_start_scylla_server
< t:2019-09-19 23:04:07,694  >>>>Started random_disrupt_method nodetool_decommission

<coredump ....>

< t:2019-09-20 01:36:48,942  Node longevity-tls-50gb-4d-3-1-db-node-5979c9a0-8 [34.245.136.197 | 10.0.244.153] (seed: False): Found coredump file: /var/lib/systemd/coredump/core.scylla.996.c212eda51d7d40c1b68eb746938de6ae.1730.1568943298000000
```

**Comment by eliransin** [comment] 2019-09-29 10:29
I think it is the same as #5089 . I wrote a guess there about the root cause.

**Comment by slivne** [comment] 2019-10-06 11:41
closing #5089 closed

**Closed by slivne** 2019-10-06 11:41 UTC
Labels: bug, high, showstopper
