### ISSUE TITLE
Repairs get stuck without any errors

### ISSUE THREAD

**Issue by gnumoreno** [scylladb/scylla#7142] opened 2020-08-28 20:18 UTC
*Installation details*
Scylla version (or git commit hash): 4.1.5-0.20200817.382dcb9d34f
Cluster size: 4 nodes
OS (RHEL/CentOS/Ubuntu/AWS AMI): 

*Hardware details (for performance issues)*
i3.metal

### Problem
Repairs get stuck after 5 min and nothing happens
```
Aug 28 05:17:29 us-west-production-scylla-10 scylla[1650915]:  [shard 0] repair - starting user-requested repair for keyspace ***}, { ranges -> 9080250114648216871:9123118243813566623}}
Aug 28 05:17:59 us-west-production-scylla-10 scylla[1650915]:  [shard 13] repair - repair id 1 on shard 13 completed successfully
Aug 28 05:18:01 us-west-production-scylla-10 scylla[1650915]:  [shard 11] repair - repair id 1 on shard 11 completed successfully
Aug 28 05:18:02 us-west-production-scylla-10 scylla[1650915]:  [shard 54] repair - repair id 1 on shard 54 completed successfully
Aug 28 05:18:02 us-west-production-scylla-10 scylla[1650915]:  [shard 10] repair - repair id 1 on shard 10 completed successfully
Aug 28 05:18:03 us-west-production-scylla-10 scylla[1650915]:  [shard 2] repair - repair id 1 on shard 2 completed successfully
Aug 28 05:18:06 us-west-production-scylla-10 scylla[1650915]:  [shard 4] repair - repair id 1 on shard 4 completed successfully
Aug 28 05:18:06 us-west-production-scylla-10 scylla[1650915]:  [shard 56] repair - repair id 1 on shard 56 completed successfully
Aug 28 05:18:06 us-west-production-scylla-10 scylla[1650915]:  [shard 66] repair - repair id 1 on shard 66 completed successfully
Aug 28 05:18:07 us-west-production-scylla-10 scylla[1650915]:  [shard 7] repair - repair id 1 on shard 7 completed successfully
Aug 28 05:18:07 us-west-production-scylla-10 scylla[1650915]:  [shard 49] repair - repair id 1 on shard 49 completed successfully
Aug 28 05:18:08 us-west-production-scylla-10 scylla[1650915]:  [shard 48] repair - repair id 1 on shard 48 completed successfully
Aug 28 05:18:08 us-west-production-scylla-10 scylla[1650915]:  [shard 6] repair - repair id 1 on shard 6 completed successfully
Aug 28 05:18:09 us-west-production-scylla-10 scylla[1650915]:  [shard 17] repair - repair id 1 on shard 17 completed successfully
Aug 28 05:18:09 us-west-production-scylla-10 scylla[1650915]:  [shard 52] repair - repair id 1 on shard 52 completed successfully
Aug 28 05:18:10 us-west-production-scylla-10 scylla[1650915]:  [shard 1] repair - repair id 1 on shard 1 completed successfully
Aug 28 05:18:10 us-west-production-scylla-10 scylla[1650915]:  [shard 51] repair - repair id 1 on shard 51 completed successfully
Aug 28 05:18:10 us-west-production-scylla-10 scylla[1650915]:  [shard 44] repair - repair id 1 on shard 44 completed successfully
Aug 28 05:18:11 us-west-production-scylla-10 scylla[1650915]:  [shard 21] repair - repair id 1 on shard 21 completed successfully
Aug 28 05:18:11 us-west-production-scylla-10 scylla[1650915]:  [shard 3] repair - repair id 1 on shard 3 completed successfully
Aug 28 05:18:11 us-west-production-scylla-10 scylla[1650915]:  [shard 67] repair - repair id 1 on shard 67 completed successfully
Aug 28 05:18:11 us-west-production-scylla-10 scylla[1650915]:  [shard 29] repair - repair id 1 on shard 29 completed successfully
Aug 28 05:18:11 us-west-production-scylla-10 scylla[1650915]:  [shard 64] repair - repair id 1 on shard 64 completed successfully
Aug 28 05:18:12 us-west-production-scylla-10 scylla[1650915]:  [shard 53] repair - repair id 1 on shard 53 completed successfully
Aug 28 05:18:12 us-west-production-scylla-10 scylla[1650915]:  [shard 27] repair - repair id 1 on shard 27 completed successfully
Aug 28 05:18:13 us-west-production-scylla-10 scylla[1650915]:  [shard 9] repair - repair id 1 on shard 9 completed successfully
Aug 28 05:18:13 us-west-production-scylla-10 scylla[1650915]:  [shard 42] repair - repair id 1 on shard 42 completed successfully
Aug 28 05:18:13 us-west-production-scylla-10 scylla[1650915]:  [shard 28] repair - repair id 1 on shard 28 completed successfully
Aug 28 05:18:14 us-west-production-scylla-10 scylla[1650915]:  [shard 38] repair - repair id 1 on shard 38 completed successfully
Aug 28 05:18:14 us-west-production-scylla-10 scylla[1650915]:  [shard 26] repair - repair id 1 on shard 26 completed successfully
Aug 28 05:18:14 us-west-production-scylla-10 scylla[1650915]:  [shard 39] repair - repair id 1 on shard 39 completed successfully
Aug 28 05:18:15 us-west-production-scylla-10 scylla[1650915]:  [shard 5] repair - repair id 1 on shard 5 completed successfully
Aug 28 05:18:15 us-west-production-scylla-10 scylla[1650915]:  [shard 47] repair - repair id 1 on shard 47 completed successfully
Aug 28 05:18:15 us-west-production-scylla-10 scylla[1650915]:  [shard 8] repair - repair id 1 on shard 8 completed successfully
Aug 28 05:18:16 us-west-production-scylla-10 scylla[1650915]:  [shard 46] repair - repair id 1 on shard 46 completed successfully
Aug 28 05:18:16 us-west-production-scylla-10 scylla[1650915]:  [shard 41] repair - repair id 1 on shard 41 completed successfully
Aug 28 05:18:16 us-west-production-scylla-10 scylla[1650915]:  [shard 40] repair - repair id 1 on shard 40 completed successfully
Aug 28 05:18:16 us-west-production-scylla-10 scylla[1650915]:  [shard 59] repair - repair id 1 on shard 59 completed successfully
Aug 28 05:18:17 us-west-production-scylla-10 scylla[1650915]:  [shard 37] repair - repair id 1 on shard 37 completed successfully
Aug 28 05:18:17 us-west-production-scylla-10 scylla[1650915]:  [shard 55] repair - repair id 1 on shard 55 completed successfully
Aug 28 05:18:17 us-west-production-scylla-10 scylla[1650915]:  [shard 14] repair - repair id 1 on shard 14 completed successfully
Aug 28 05:18:18 us-west-production-scylla-10 scylla[1650915]:  [shard 20] repair - repair id 1 on shard 20 completed successfully
Aug 28 05:18:18 us-west-production-scylla-10 scylla[1650915]:  [shard 15] repair - repair id 1 on shard 15 completed successfully
Aug 28 05:18:18 us-west-production-scylla-10 scylla[1650915]:  [shard 32] repair - repair id 1 on shard 32 completed successfully
Aug 28 05:18:18 us-west-production-scylla-10 scylla[1650915]:  [shard 36] repair - repair id 1 on shard 36 completed successfully
Aug 28 05:18:20 us-west-production-scylla-10 scylla[1650915]:  [shard 61] repair - repair id 1 on shard 61 completed successfully
Aug 28 05:18:20 us-west-production-scylla-10 scylla[1650915]:  [shard 60] repair - repair id 1 on shard 60 completed successfully
Aug 28 05:18:20 us-west-production-scylla-10 scylla[1650915]:  [shard 50] repair - repair id 1 on shard 50 completed successfully
Aug 28 05:18:21 us-west-production-scylla-10 scylla[1650915]:  [shard 22] repair - repair id 1 on shard 22 completed successfully
Aug 28 05:18:21 us-west-production-scylla-10 scylla[1650915]:  [shard 45] repair - repair id 1 on shard 45 completed successfully
Aug 28 05:18:22 us-west-production-scylla-10 scylla[1650915]:  [shard 0] repair - repair id 1 on shard 0 completed successfully
Aug 28 05:18:22 us-west-production-scylla-10 scylla[1650915]:  [shard 31] repair - repair id 1 on shard 31 completed successfully
Aug 28 05:18:23 us-west-production-scylla-10 scylla[1650915]:  [shard 24] repair - repair id 1 on shard 24 completed successfully
Aug 28 05:18:24 us-west-production-scylla-10 scylla[1650915]:  [shard 16] repair - repair id 1 on shard 16 completed successfully
Aug 28 05:18:24 us-west-production-scylla-10 scylla[1650915]:  [shard 43] repair - repair id 1 on shard 43 completed successfully
Aug 28 05:18:25 us-west-production-scylla-10 scylla[1650915]:  [shard 65] repair - repair id 1 on shard 65 completed successfully
Aug 28 05:18:26 us-west-production-scylla-10 scylla[1650915]:  [shard 18] repair - repair id 1 on shard 18 completed successfully
Aug 28 05:18:27 us-west-production-scylla-10 scylla[1650915]:  [shard 58] repair - repair id 1 on shard 58 completed successfully
Aug 28 05:18:28 us-west-production-scylla-10 scylla[1650915]:  [shard 35] repair - repair id 1 on shard 35 completed successfully
Aug 28 05:18:29 us-west-production-scylla-10 scylla[1650915]:  [shard 23] repair - repair id 1 on shard 23 completed successfully
Aug 28 05:18:29 us-west-production-scylla-10 scylla[1650915]:  [shard 68] repair - repair id 1 on shard 68 completed successfully
Aug 28 05:18:35 us-west-production-scylla-10 scylla[1650915]:  [shard 19] repair - repair id 1 on shard 19 completed successfully
Aug 28 05:18:36 us-west-production-scylla-10 scylla[1650915]:  [shard 25] repair - repair id 1 on shard 25 completed successfully
Aug 28 05:18:40 us-west-production-scylla-10 scylla[1650915]:  [shard 12] repair - repair id 1 on shard 12 completed successfully
Aug 28 05:18:40 us-west-production-scylla-10 scylla[1650915]:  [shard 30] repair - repair id 1 on shard 30 completed successfully
Aug 28 05:18:42 us-west-production-scylla-10 scylla[1650915]:  [shard 63] repair - repair id 1 on shard 63 completed successfully
Aug 28 05:18:42 us-west-production-scylla-10 scylla[1650915]:  [shard 33] repair - repair id 1 on shard 33 completed successfully
Aug 28 05:18:43 us-west-production-scylla-10 scylla[1650915]:  [shard 34] repair - repair id 1 on shard 34 completed successfully
Aug 28 05:18:44 us-west-production-scylla-10 scylla[1650915]:  [shard 57] repair - repair id 1 on shard 57 completed successfully
Aug 28 05:18:46 us-west-production-scylla-10 scylla[1650915]:  [shard 69] repair - repair id 1 on shard 69 completed successfully
Aug 28 05:18:51 us-west-production-scylla-10 scylla[1650915]:  [shard 62] repair - repair id 1 on shard 62 completed successfully
Aug 28 05:18:51 us-west-production-scylla-10 scylla[1650915]:  [shard 0] repair - starting user-requested repair for keyspace ***}, { ranges -> 9009939957667485249:9037241268368167035}}
Aug 28 05:19:12 us-west-production-scylla-10 scylla[1650915]:  [shard 64] repair - repair id 2 on shard 64 completed successfully
Aug 28 05:19:12 us-west-production-scylla-10 scylla[1650915]:  [shard 55] repair - repair id 2 on shard 55 completed successfully
Aug 28 05:19:14 us-west-production-scylla-10 scylla[1650915]:  [shard 52] repair - repair id 2 on shard 52 completed successfully
Aug 28 05:19:14 us-west-production-scylla-10 scylla[1650915]:  [shard 29] repair - repair id 2 on shard 29 completed successfully
Aug 28 05:19:15 us-west-production-scylla-10 scylla[1650915]:  [shard 9] repair - repair id 2 on shard 9 completed successfully
Aug 28 05:19:15 us-west-production-scylla-10 scylla[1650915]:  [shard 13] repair - repair id 2 on shard 13 completed successfully
Aug 28 05:19:15 us-west-production-scylla-10 scylla[1650915]:  [shard 49] repair - repair id 2 on shard 49 completed successfully
Aug 28 05:19:15 us-west-production-scylla-10 scylla[1650915]:  [shard 0] repair - repair id 2 on shard 0 completed successfully
Aug 28 05:19:16 us-west-production-scylla-10 scylla[1650915]:  [shard 38] repair - repair id 2 on shard 38 completed successfully
Aug 28 05:19:16 us-west-production-scylla-10 scylla[1650915]:  [shard 8] repair - repair id 2 on shard 8 completed successfully
Aug 28 05:19:16 us-west-production-scylla-10 scylla[1650915]:  [shard 53] repair - repair id 2 on shard 53 completed successfully
Aug 28 05:19:17 us-west-production-scylla-10 scylla[1650915]:  [shard 61] repair - repair id 2 on shard 61 completed successfully
Aug 28 05:19:17 us-west-production-scylla-10 scylla[1650915]:  [shard 18] repair - repair id 2 on shard 18 completed successfully
Aug 28 05:19:17 us-west-production-scylla-10 scylla[1650915]:  [shard 7] repair - repair id 2 on shard 7 completed successfully
Aug 28 05:19:17 us-west-production-scylla-10 scylla[1650915]:  [shard 14] repair - repair id 2 on shard 14 completed successfully
Aug 28 05:19:17 us-west-production-scylla-10 scylla[1650915]:  [shard 54] repair - repair id 2 on shard 54 completed successfully
Aug 28 05:19:17 us-west-production-scylla-10 scylla[1650915]:  [shard 51] repair - repair id 2 on shard 51 completed successfully
Aug 28 05:19:17 us-west-production-scylla-10 scylla[1650915]:  [shard 17] repair - repair id 2 on shard 17 completed successfully
Aug 28 05:19:18 us-west-production-scylla-10 scylla[1650915]:  [shard 5] repair - repair id 2 on shard 5 completed successfully
Aug 28 05:19:18 us-west-production-scylla-10 scylla[1650915]:  [shard 66] repair - repair id 2 on shard 66 completed successfully
Aug 28 05:19:19 us-west-production-scylla-10 scylla[1650915]:  [shard 50] repair - repair id 2 on shard 50 completed successfully
Aug 28 05:19:19 us-west-production-scylla-10 scylla[1650915]:  [shard 31] repair - repair id 2 on shard 31 completed successfully
Aug 28 05:19:19 us-west-production-scylla-10 scylla[1650915]:  [shard 10] repair - repair id 2 on shard 10 completed successfully
Aug 28 05:19:19 us-west-production-scylla-10 scylla[1650915]:  [shard 15] repair - repair id 2 on shard 15 completed successfully
Aug 28 05:19:19 us-west-production-scylla-10 scylla[1650915]:  [shard 20] repair - repair id 2 on shard 20 completed successfully
Aug 28 05:19:19 us-west-production-scylla-10 scylla[1650915]:  [shard 1] repair - repair id 2 on shard 1 completed successfully
Aug 28 05:19:19 us-west-production-scylla-10 scylla[1650915]:  [shard 65] repair - repair id 2 on shard 65 completed successfully
Aug 28 05:19:20 us-west-production-scylla-10 scylla[1650915]:  [shard 23] repair - repair id 2 on shard 23 completed successfully
Aug 28 05:19:20 us-west-production-scylla-10 scylla[1650915]:  [shard 56] repair - repair id 2 on shard 56 completed successfully
Aug 28 05:19:20 us-west-production-scylla-10 scylla[1650915]:  [shard 48] repair - repair id 2 on shard 48 completed successfully
Aug 28 05:19:20 us-west-production-scylla-10 scylla[1650915]:  [shard 43] repair - repair id 2 on shard 43 completed successfully
Aug 28 05:19:20 us-west-production-scylla-10 scylla[1650915]:  [shard 36] repair - repair id 2 on shard 36 completed successfully
Aug 28 05:19:20 us-west-production-scylla-10 scylla[1650915]:  [shard 40] repair - repair id 2 on shard 40 completed successfully
Aug 28 05:19:20 us-west-production-scylla-10 scylla[1650915]:  [shard 59] repair - repair id 2 on shard 59 completed successfully
Aug 28 05:19:20 us-west-production-scylla-10 scylla[1650915]:  [shard 68] repair - repair id 2 on shard 68 completed successfully
Aug 28 05:19:20 us-west-production-scylla-10 scylla[1650915]:  [shard 45] repair - repair id 2 on shard 45 completed successfully
Aug 28 05:19:21 us-west-production-scylla-10 scylla[1650915]:  [shard 37] repair - repair id 2 on shard 37 completed successfully
Aug 28 05:19:21 us-west-production-scylla-10 scylla[1650915]:  [shard 44] repair - repair id 2 on shard 44 completed successfully
Aug 28 05:19:21 us-west-production-scylla-10 scylla[1650915]:  [shard 4] repair - repair id 2 on shard 4 completed successfully
Aug 28 05:19:22 us-west-production-scylla-10 scylla[1650915]:  [shard 67] repair - repair id 2 on shard 67 completed successfully
Aug 28 05:19:22 us-west-production-scylla-10 scylla[1650915]:  [shard 28] repair - repair id 2 on shard 28 completed successfully
Aug 28 05:19:22 us-west-production-scylla-10 scylla[1650915]:  [shard 26] repair - repair id 2 on shard 26 completed successfully
Aug 28 05:19:22 us-west-production-scylla-10 scylla[1650915]:  [shard 11] repair - repair id 2 on shard 11 completed successfully
Aug 28 05:19:24 us-west-production-scylla-10 scylla[1650915]:  [shard 39] repair - repair id 2 on shard 39 completed successfully
Aug 28 05:19:24 us-west-production-scylla-10 scylla[1650915]:  [shard 2] repair - repair id 2 on shard 2 completed successfully
Aug 28 05:19:24 us-west-production-scylla-10 scylla[1650915]:  [shard 21] repair - repair id 2 on shard 21 completed successfully
Aug 28 05:19:25 us-west-production-scylla-10 scylla[1650915]:  [shard 42] repair - repair id 2 on shard 42 completed successfully
Aug 28 05:19:25 us-west-production-scylla-10 scylla[1650915]:  [shard 22] repair - repair id 2 on shard 22 completed successfully
Aug 28 05:19:26 us-west-production-scylla-10 scylla[1650915]:  [shard 27] repair - repair id 2 on shard 27 completed successfully
Aug 28 05:19:26 us-west-production-scylla-10 scylla[1650915]:  [shard 60] repair - repair id 2 on shard 60 completed successfully
Aug 28 05:19:26 us-west-production-scylla-10 scylla[1650915]:  [shard 30] repair - repair id 2 on shard 30 completed successfully
Aug 28 05:19:27 us-west-production-scylla-10 scylla[1650915]:  [shard 6] repair - repair id 2 on shard 6 completed successfully
Aug 28 05:19:27 us-west-production-scylla-10 scylla[1650915]:  [shard 58] repair - repair id 2 on shard 58 completed successfully
Aug 28 05:19:27 us-west-production-scylla-10 scylla[1650915]:  [shard 3] repair - repair id 2 on shard 3 completed successfully
Aug 28 05:19:28 us-west-production-scylla-10 scylla[1650915]:  [shard 19] repair - repair id 2 on shard 19 completed successfully
Aug 28 05:19:28 us-west-production-scylla-10 scylla[1650915]:  [shard 12] repair - repair id 2 on shard 12 completed successfully
Aug 28 05:19:29 us-west-production-scylla-10 scylla[1650915]:  [shard 46] repair - repair id 2 on shard 46 completed successfully
Aug 28 05:19:29 us-west-production-scylla-10 scylla[1650915]:  [shard 33] repair - repair id 2 on shard 33 completed successfully
Aug 28 05:19:30 us-west-production-scylla-10 scylla[1650915]:  [shard 41] repair - repair id 2 on shard 41 completed successfully
Aug 28 05:19:30 us-west-production-scylla-10 scylla[1650915]:  [shard 16] repair - repair id 2 on shard 16 completed successfully
Aug 28 05:19:30 us-west-production-scylla-10 scylla[1650915]:  [shard 47] repair - repair id 2 on shard 47 completed successfully
Aug 28 05:19:31 us-west-production-scylla-10 scylla[1650915]:  [shard 25] repair - repair id 2 on shard 25 completed successfully
Aug 28 05:19:31 us-west-production-scylla-10 scylla[1650915]:  [shard 69] repair - repair id 2 on shard 69 completed successfully
Aug 28 05:19:32 us-west-production-scylla-10 scylla[1650915]:  [shard 63] repair - repair id 2 on shard 63 completed successfully
Aug 28 05:19:33 us-west-production-scylla-10 scylla[1650915]:  [shard 57] repair - repair id 2 on shard 57 completed successfully
Aug 28 05:19:33 us-west-production-scylla-10 scylla[1650915]:  [shard 32] repair - repair id 2 on shard 32 completed successfully
Aug 28 05:19:35 us-west-production-scylla-10 scylla[1650915]:  [shard 24] repair - repair id 2 on shard 24 completed successfully
Aug 28 05:19:37 us-west-production-scylla-10 scylla[1650915]:  [shard 35] repair - repair id 2 on shard 35 completed successfully
Aug 28 05:19:42 us-west-production-scylla-10 scylla[1650915]:  [shard 62] repair - repair id 2 on shard 62 completed successfully
Aug 28 05:19:43 us-west-production-scylla-10 scylla[1650915]:  [shard 34] repair - repair id 2 on shard 34 completed successfully
Aug 28 05:19:44 us-west-production-scylla-10 scylla[1650915]:  [shard 0] repair - starting user-requested repair for keyspace ***}, { ranges -> 8902426021796594539:9007994700217029335}}
Aug 28 05:21:03 us-west-production-scylla-10 scylla[1650915]:  [shard 41] repair - repair id 3 on shard 41 completed successfully
Aug 28 05:21:04 us-west-production-scylla-10 scylla[1650915]:  [shard 16] repair - repair id 3 on shard 16 completed successfully
Aug 28 05:21:05 us-west-production-scylla-10 scylla[1650915]:  [shard 50] repair - repair id 3 on shard 50 completed successfully
Aug 28 05:21:05 us-west-production-scylla-10 scylla[1650915]:  [shard 0] repair - repair id 3 on shard 0 completed successfully
Aug 28 05:21:05 us-west-production-scylla-10 scylla[1650915]:  [shard 47] repair - repair id 3 on shard 47 completed successfully
Aug 28 05:21:09 us-west-production-scylla-10 scylla[1650915]:  [shard 22] repair - repair id 3 on shard 22 completed successfully
Aug 28 05:21:09 us-west-production-scylla-10 scylla[1650915]:  [shard 42] repair - repair id 3 on shard 42 completed successfully
Aug 28 05:21:09 us-west-production-scylla-10 scylla[1650915]:  [shard 33] repair - repair id 3 on shard 33 completed successfully
Aug 28 05:21:09 us-west-production-scylla-10 scylla[1650915]:  [shard 60] repair - repair id 3 on shard 60 completed successfully
Aug 28 05:21:10 us-west-production-scylla-10 scylla[1650915]:  [shard 49] repair - repair id 3 on shard 49 completed successfully
Aug 28 05:21:11 us-west-production-scylla-10 scylla[1650915]:  [shard 39] repair - repair id 3 on shard 39 completed successfully
Aug 28 05:21:11 us-west-production-scylla-10 scylla[1650915]:  [shard 40] repair - repair id 3 on shard 40 completed successfully
Aug 28 05:21:11 us-west-production-scylla-10 scylla[1650915]:  [shard 58] repair - repair id 3 on shard 58 completed successfully
Aug 28 05:21:11 us-west-production-scylla-10 scylla[1650915]:  [shard 65] repair - repair id 3 on shard 65 completed successfully
Aug 28 05:21:11 us-west-production-scylla-10 scylla[1650915]:  [shard 18] repair - repair id 3 on shard 18 completed successfully
Aug 28 05:21:11 us-west-production-scylla-10 scylla[1650915]:  [shard 3] repair - repair id 3 on shard 3 completed successfully
Aug 28 05:21:12 us-west-production-scylla-10 scylla[1650915]:  [shard 66] repair - repair id 3 on shard 66 completed successfully
Aug 28 05:21:12 us-west-production-scylla-10 scylla[1650915]:  [shard 38] repair - repair id 3 on shard 38 completed successfully
Aug 28 05:21:12 us-west-production-scylla-10 scylla[1650915]:  [shard 20] repair - repair id 3 on shard 20 completed successfully
Aug 28 05:21:13 us-west-production-scylla-10 scylla[1650915]:  [shard 14] repair - repair id 3 on shard 14 completed successfully
Aug 28 05:21:13 us-west-production-scylla-10 scylla[1650915]:  [shard 64] repair - repair id 3 on shard 64 completed successfully
Aug 28 05:21:13 us-west-production-scylla-10 scylla[1650915]:  [shard 9] repair - repair id 3 on shard 9 completed successfully
Aug 28 05:21:14 us-west-production-scylla-10 scylla[1650915]:  [shard 17] repair - repair id 3 on shard 17 completed successfully
Aug 28 05:21:14 us-west-production-scylla-10 scylla[1650915]:  [shard 11] repair - repair id 3 on shard 11 completed successfully
Aug 28 05:21:14 us-west-production-scylla-10 scylla[1650915]:  [shard 51] repair - repair id 3 on shard 51 completed successfully
Aug 28 05:21:14 us-west-production-scylla-10 scylla[1650915]:  [shard 26] repair - repair id 3 on shard 26 completed successfully
Aug 28 05:21:15 us-west-production-scylla-10 scylla[1650915]:  [shard 52] repair - repair id 3 on shard 52 completed successfully
Aug 28 05:21:15 us-west-production-scylla-10 scylla[1650915]:  [shard 48] repair - repair id 3 on shard 48 completed successfully
Aug 28 05:21:16 us-west-production-scylla-10 scylla[1650915]:  [shard 10] repair - repair id 3 on shard 10 completed successfully
Aug 28 05:21:16 us-west-production-scylla-10 scylla[1650915]:  [shard 30] repair - repair id 3 on shard 30 completed successfully
Aug 28 05:21:16 us-west-production-scylla-10 scylla[1650915]:  [shard 7] repair - repair id 3 on shard 7 completed successfully
Aug 28 05:21:16 us-west-production-scylla-10 scylla[1650915]:  [shard 35] repair - repair id 3 on shard 35 completed successfully
Aug 28 05:21:16 us-west-production-scylla-10 scylla[1650915]:  [shard 2] repair - repair id 3 on shard 2 completed successfully
Aug 28 05:21:17 us-west-production-scylla-10 scylla[1650915]:  [shard 59] repair - repair id 3 on shard 59 completed successfully
Aug 28 05:21:17 us-west-production-scylla-10 scylla[1650915]:  [shard 5] repair - repair id 3 on shard 5 completed successfully
Aug 28 05:21:17 us-west-production-scylla-10 scylla[1650915]:  [shard 19] repair - repair id 3 on shard 19 completed successfully
Aug 28 05:21:19 us-west-production-scylla-10 scylla[1650915]:  [shard 24] repair - repair id 3 on shard 24 completed successfully
Aug 28 05:21:19 us-west-production-scylla-10 scylla[1650915]:  [shard 37] repair - repair id 3 on shard 37 completed successfully
Aug 28 05:21:19 us-west-production-scylla-10 scylla[1650915]:  [shard 55] repair - repair id 3 on shard 55 completed successfully
Aug 28 05:21:19 us-west-production-scylla-10 scylla[1650915]:  [shard 8] repair - repair id 3 on shard 8 completed successfully
Aug 28 05:21:19 us-west-production-scylla-10 scylla[1650915]:  [shard 27] repair - repair id 3 on shard 27 completed successfully
Aug 28 05:21:20 us-west-production-scylla-10 scylla[1650915]:  [shard 6] repair - repair id 3 on shard 6 completed successfully
Aug 28 05:21:20 us-west-production-scylla-10 scylla[1650915]:  [shard 31] repair - repair id 3 on shard 31 completed successfully
Aug 28 05:21:20 us-west-production-scylla-10 scylla[1650915]:  [shard 45] repair - repair id 3 on shard 45 completed successfully
Aug 28 05:21:22 us-west-production-scylla-10 scylla[1650915]:  [shard 69] repair - repair id 3 on shard 69 completed successfully
Aug 28 05:21:23 us-west-production-scylla-10 scylla[1650915]:  [shard 23] repair - repair id 3 on shard 23 completed successfully
Aug 28 05:21:23 us-west-production-scylla-10 scylla[1650915]:  [shard 56] repair - repair id 3 on shard 56 completed successfully
Aug 28 05:21:23 us-west-production-scylla-10 scylla[1650915]:  [shard 29] repair - repair id 3 on shard 29 completed successfully
Aug 28 05:21:25 us-west-production-scylla-10 scylla[1650915]:  [shard 54] repair - repair id 3 on shard 54 completed successfully
Aug 28 05:21:25 us-west-production-scylla-10 scylla[1650915]:  [shard 21] repair - repair id 3 on shard 21 completed successfully
Aug 28 05:21:26 us-west-production-scylla-10 scylla[1650915]:  [shard 15] repair - repair id 3 on shard 15 completed successfully
Aug 28 05:21:28 us-west-production-scylla-10 scylla[1650915]:  [shard 13] repair - repair id 3 on shard 13 completed successfully
Aug 28 05:21:31 us-west-production-scylla-10 scylla[1650915]:  [shard 36] repair - repair id 3 on shard 36 completed successfully
Aug 28 05:21:32 us-west-production-scylla-10 scylla[1650915]:  [shard 4] repair - repair id 3 on shard 4 completed successfully
Aug 28 05:21:35 us-west-production-scylla-10 scylla[1650915]:  [shard 43] repair - repair id 3 on shard 43 completed successfully
Aug 28 05:21:36 us-west-production-scylla-10 scylla[1650915]:  [shard 28] repair - repair id 3 on shard 28 completed successfully
Aug 28 05:21:46 us-west-production-scylla-10 scylla[1650915]:  [shard 34] repair - repair id 3 on shard 34 completed successfully
Aug 28 05:22:10 us-west-production-scylla-10 scylla[1650915]:  [shard 57] repair - repair id 3 on shard 57 completed successfully
Aug 28 05:22:10 us-west-production-scylla-10 scylla[1650915]:  [shard 32] repair - repair id 3 on shard 32 completed successfully
Aug 28 05:22:44 us-west-production-scylla-10 scylla[1650915]:  [shard 62] repair - repair id 3 on shard 62 completed successfully
Aug 28 05:22:55 us-west-production-scylla-10 scylla[1650915]:  [shard 63] repair - repair id 3 on shard 63 completed successfully

Missing shards:
< 1
< 12
< 25
< 44
< 46
< 53
< 61
< 67
< 68
```

uuid=`55b1e406-6b8a-442f-af54-59459c80c839`

Report contains: 
nodetool status, clusterinfo, gossipinfo
scylla-manager logs
scylla-manager-agent logs from all nodes
scylla logs from all nodes
prometheus data

**Comment by avikivity** [comment] 2020-08-29 06:33
Likely a duplicate of #6272

**Comment by asias** [comment] 2020-09-03 07:29
4.1.6 with all the fixes are just released.

**Comment by slivne** [comment] 2020-09-06 07:33
closing this issue - if it happens again please report - we have reports from users that 4.1.6 fixed their issue

**Closed by slivne** 2020-09-06 07:33 UTC
