### ISSUE TITLE
hints_manager - Exception when draining 10.0.63.76: std::filesystem::__cxx11::filesystem_error (error system:39, filesystem error: remove failed: Directory not empty [/var/lib/scylla/hints/3/10.0.63.76]

### ISSUE THREAD

**Issue by yarongilor** [scylladb/scylla#5087] opened 2019-09-23 11:32 UTC
Installation details
Scylla version (or git commit hash): 3.1.0.rc7-0.20190915.024d1563a
Cluster size: 6
OS (RHEL/CentOS/Ubuntu/AWS AMI): ami-0a01b94dffe4bcc0d

scenario: 50GB longevity - during nodetool_decommission nemesis of 10.0.63.76 node, there was a core dump on 10.0.244.153 node. then 10.0.244.153 got hints_manager - Exception

failure scenario and error:
```
< t:2019-09-19 23:04:07,694 f:nemesis.py      l:585  c:sdcm.nemesis         p:INFO  > sdcm.nemesis.ChaosMonkey: >>>>>>>>>>>>>Started random_disrupt_method nodetool_decommission
< t:2019-09-19 23:04:08,458 f:nemesis.py      l:338  c:sdcm.nemesis         p:DEBUG > sdcm.nemesis.ChaosMonkey: Set current_disruption -> Decommission Node longevity-tls-50gb-4d-3-1-db-node-5979c9a0-5 [34.248.223.143 | 10.0.63.76] (seed: False)
[jenkins@aws-eu-builder3 latest]$ grep -v 'ChaosMonkey on target' sct20_9.log | grep -i 'found coredump\|Set current_disruption\|segmentation\|<<<<<<<<<\|>>>>>>>>>\|p:ERROR > Traceback\|filesystem error: remove failed: Directory not empty'
< t:2019-09-20 01:36:48,942 f:cluster.py      l:833  c:sdcm.cluster         p:DEBUG > Node longevity-tls-50gb-4d-3-1-db-node-5979c9a0-8 [34.245.136.197 | 10.0.244.153] (seed: False): Found coredump file: /var/lib/systemd/coredump/core.scylla.996.c212eda51d7d40c1b68eb746938de6ae.1730.1568943298000000
2019-09-20T01:37:05+00:00  ip-10-0-244-153 !ERR     | scylla: [shard 3] hints_manager - Exception when draining 10.0.63.76: std::filesystem::__cxx11::filesystem_error (error system:39, filesystem error: remove failed: Directory not empty [/var/lib/scylla/hints/3/10.0.63.76])
2019-09-20T01:37:05+00:00  ip-10-0-244-153 !ERR     | scylla: [shard 1] hints_manager - Exception when draining 10.0.63.76: std::filesystem::__cxx11::filesystem_error (error system:39, filesystem error: remove failed: Directory not empty [/var/lib/scylla/hints/1/10.0.63.76])
2019-09-20T01:37:05+00:00  ip-10-0-244-153 !ERR     | scylla: [shard 8] hints_manager - Exception when draining 10.0.63.76: std::filesystem::__cxx11::filesystem_error (error system:39, filesystem error: remove failed: Directory not empty [/var/lib/scylla/hints/8/10.0.63.76])
2019-09-20T01:37:05+00:00  ip-10-0-244-153 !ERR     | scylla: [shard 4] hints_manager - Exception when draining 10.0.63.76: std::filesystem::__cxx11::filesystem_error (error system:39, filesystem error: remove failed: Directory not empty [/var/lib/scylla/hints/4/10.0.63.76])
2019-09-20T01:37:05+00:00  ip-10-0-244-153 !ERR     | scylla: [shard 10] hints_manager - Exception when draining 10.0.63.76: std::filesystem::__cxx11::filesystem_error (error system:39, filesystem error: remove failed: Directory not empty [/var/lib/scylla/hints/10/10.0.63.76])
2019-09-20T01:37:05+00:00  ip-10-0-244-153 !ERR     | scylla: [shard 6] hints_manager - Exception when draining 10.0.63.76: std::filesystem::__cxx11::filesystem_error (error system:39, filesystem error: remove failed: Directory not empty [/var/lib/scylla/hints/6/10.0.63.76])
2019-09-20T01:37:05+00:00  ip-10-0-244-153 !ERR     | scylla: [shard 12] hints_manager - Exception when draining 10.0.63.76: std::filesystem::__cxx11::filesystem_error (error system:39, filesystem error: remove failed: Directory not empty [/var/lib/scylla/hints/12/10.0.63.76])
2019-09-20T01:37:05+00:00  ip-10-0-244-153 !ERR     | scylla: [shard 13] hints_manager - Exception when draining 10.0.63.76: std::filesystem::__cxx11::filesystem_error (error system:39, filesystem error: remove failed: Directory not empty [/var/lib/scylla/hints/13/10.0.63.76])
2019-09-20T01:37:05+00:00  ip-10-0-244-153 !ERR     | scylla: [shard 7] hints_manager - Exception when draining 10.0.63.76: std::filesystem::__cxx11::filesystem_error (error system:39, filesystem error: remove failed: Directory not empty [/var/lib/scylla/hints/7/10.0.63.76])
x11::filesystem_error (error system:39, filesystem error: remove failed: Directory not empty [/var/lib/scylla/hints/5/10.0.63.76])
2019-09-20T01:37:05+00:00  ip-10-0-244-153 !ERR     | scylla: [shard 0] hints_manager - Exception when draining 10.0.63.76: std::filesystem::__cxx11::filesystem_error (error system:39, filesystem error: remove failed: Directory not empty [/var/lib/scylla/view_hints/0/10.0.63.76])
2019-09-20T01:37:05+00:00  ip-10-0-244-153 !ERR     | scylla: [shard 9] hints_manager - Exception when draining 10.0.63.76: std::filesystem::__cxx11::filesystem_error (error system:39, filesystem error: remove failed: Directory not empty [/var/lib/scylla/hints/9/10.0.63.76])
2019-09-20T01:37:05+00:00  ip-10-0-244-153 !ERR     | scylla: [shard 11] hints_manager - Exception when draining 10.0.63.76: std::filesystem::__cxx11::filesystem_error (error system:39, filesystem error: remove failed: Directory not empty [/var/lib/scylla/hints/11/10.0.63.76])
2019-09-20T01:37:05+00:00  ip-10-0-244-153 !ERR     | scylla: [shard 0] hints_manager - Exception when draining 10.0.63.76: std::filesystem::__cxx11::filesystem_error (error system:39, filesystem error: remove failed: Directory not empty [/var/lib/scylla/hints/0/10.0.63.76])
2019-09-20T01:37:05+00:00  ip-10-0-244-153 !ERR     | scylla: [shard 1] hints_manager - Exception when draining 10.0.63.76: std::filesystem::__cxx11::filesystem_error (error system:39, filesystem error: remove failed: Directory not empty [/var/lib/scylla/view_hints/1/10.0.63.76])
2019-09-20T01:37:05+00:00  ip-10-0-244-153 !ERR     | scylla: [shard 2] hints_manager - Exception when draining 10.0.63.76: std::filesystem::__cxx11::filesystem_error (error system:39, filesystem error: remove failed: Directory not empty [/var/lib/scylla/hints/2/10.0.63.76])

```

coredump details: download_instructions=
gsutil cp gs://upload.scylladb.com/core.scylla.996.c212eda51d7d40c1b68eb746938de6ae.1730.1568943298000000/core.scylla.996.c212eda51d7d40c1b68eb746938de6ae.1730.1568943298000000.gz .

test logs:
job log: scratch.scylladb.com/qa_issues/sct_08_42_22_09_2019.log.gz
```
$ hydra investigate show-logs 5979c9a0-a1c1-4601-a2c3-63f1850766d9 | grep '|'
|                                            Log links for testrun with test id 5979c9a0-a1c1-4601-a2c3-63f1850766d9                                             |
| Log type              | Link                                                                                                                                   |
| events                | https://cloudius-jenkins-test.s3.amazonaws.com/5979c9a0-a1c1-4601-a2c3-63f1850766d9/events_log.zip                                     |
| db-cluster            | https://cloudius-jenkins-test.s3.amazonaws.com/5979c9a0-a1c1-4601-a2c3-63f1850766d9/longevity-tls-50gb-4d-3-1-db-cluster-5979c9a0.zip  |
| monitor-set           | https://cloudius-jenkins-test.s3.amazonaws.com/5979c9a0-a1c1-4601-a2c3-63f1850766d9/longevity-tls-50gb-4d-3-1-monitor-set-5979c9a0.zip |
| monitoring_data_stack | https://cloudius-jenkins-test.s3.amazonaws.com/5979c9a0-a1c1-4601-a2c3-63f1850766d9/monitoring_data_stack_branch-2.4_3.1.tar.gz        |
```
snapshot:
https://snapshot.raintank.io/dashboard/snapshot/I6ue7n0F4RQkowyEhHqc2p44NdxIZwT1

**Comment by slivne** [comment] 2019-10-24 09:38
pushing - consider for backports -@bhalevy ping

**Comment by bhalevy** [comment] 2019-10-31 10:12
@vladzcloudius, as the author of `manager::drain_for`, do you have a theory of how this could happen?

**Comment by vladzcloudius** [comment] 2019-10-31 22:46
@bhalevy I have a very good idea: #4685 + #4836

**Comment by bhalevy** [comment] 2019-11-07 22:23
> @bhalevy I have a very good idea: #4685 + #4836

OK, both are fixed and backported to 3.1 now so closing this issue correspondingly.

**Comment by dkropachev** [comment] 2021-01-08 18:00
Got this error on 4.4.dev-0.20201231.93a2c5233 with build-id 63738ab215ea91209c7488bf63b0556f6adf6c15 (ami-090e87c4cb2d0c2d5)
test-id: 64d3944c-e175-497c-a40d-c41b5f3e9a8c

Error:
```
2021-01-03 02:11:57.000: (DatabaseLogEvent Severity.ERROR): type=DATABASE_ERROR regex=Exception  line_number=64157 node=Node longevity-tls-50gb-4d-master-db-node-64d3944c-17 [13.48.105.92 | 10.0.1.180] (seed: False)
2021-01-03T02:11:57+00:00  longevity-tls-50gb-4d-master-db-node-64d3944c-17 !ERR     | scylla: [shard 10] hints_manager - Exception when draining 10.0.0.198: std::filesystem::__cxx11::filesystem_error (error system:39, filesystem error: remove failed: Directory not empty [/var/lib/scylla/view_hints/10/10.0.0.198])
```

List of nemesis:
longevity-tls-50gb-4d-master-db-node-64d3944c-17 [13.48.105.92 | 10.0.1.180]:

```
ModifyTablePropertiesMinIndexInterval (seed: False)	2021-01-03 01:30:23	2021-01-03 01:30:31	8
```

longevity-tls-50gb-4d-master-db-node-64d3944c-14 [13.53.118.139 | 10.0.0.198]

```
CorruptThenRebuild			2021-01-02 06:56:52	2021-01-02 07:29:46
ManagementBackup			2021-01-02 07:41:13	2021-01-02 07:41:13
MemoryStress				2021-01-02 07:47:56	2021-01-02 07:52:40
ServerSslHotReloadingNemesis		2021-01-02 09:12:08	2021-01-02 09:12:23
RejectNodeExporterNetwork		2021-01-02 09:25:40	2021-01-02 09:34:01
ManagementBackupWithSpecificKeyspaces	2021-01-02 09:48:50	2021-01-02 09:48:50
RebuildStreamingErr			2021-01-02 11:35:49	2021-01-02 12:24:22
MultipleHardRebootNode			2021-01-02 12:42:17	2021-01-02 13:11:10
NetworkRandomInterruption		2021-01-02 19:14:21	2021-01-02 19:14:21
NodetoolCleanupMonkey			2021-01-02 19:23:06	2021-01-02 23:11:47
ShrinkCluster				2021-01-03 00:22:43	2021-01-03 01:16:43
TerminateAndRemoveNodeMonkey		2021-01-03 01:43:51	2021-01-03 05:02:10
```

Links:
db-cluster - https://cloudius-jenkins-test.s3.amazonaws.com/64d3944c-e175-497c-a40d-c41b5f3e9a8c/20210104_074558/db-cluster-64d3944c.zip
loader-set - https://cloudius-jenkins-test.s3.amazonaws.com/64d3944c-e175-497c-a40d-c41b5f3e9a8c/20210104_074558/loader-set-64d3944c.zip
monitor-set - https://cloudius-jenkins-test.s3.amazonaws.com/64d3944c-e175-497c-a40d-c41b5f3e9a8c/20210104_074558/monitor-set-64d3944c.zip
sct-runner - https://cloudius-jenkins-test.s3.amazonaws.com/64d3944c-e175-497c-a40d-c41b5f3e9a8c/20210104_074558/sct-runner-64d3944c.zip

**Comment by vladzcloudius** [comment] 2021-01-12 01:27
@bhalevy @piodul I think the issue is 77a0f1a153d8d1f694847600e112d6bae38eba04 .
A quick fix is to make `can_send()` return `true` when we are in a `draining` state.

**Comment by bhalevy** [comment] 2021-01-12 07:39
@vladzcloudius can you please elaborate?

@piodul can you please take it from here?

**Comment by vladzcloudius** [comment] 2021-01-12 15:13
> @vladzcloudius can you please elaborate?
> 
> @piodul can you please take it from here?

This patch would prevent pending hints to be drained because `can_send` would return `false` for a node that is DOWN.
As a result hints directory for the leaving node is not going to be empty after sender::stop() and hence the error.

**Comment by bhalevy** [comment] 2021-01-12 17:14
> > @vladzcloudius can you please elaborate?
> > @piodul can you please take it from here?
> 
> @bhalevy
> This patch would prevent pending hints to be drained because `can_send` would return `false` for a node that is DOWN.
> As a result hints directory for the leaving node is not going to be empty after sender::stop() and hence the error.

If so, then I don't really like the quick-and-dirty approach of having `can_send` cheat and return `true` if we're draining.
I'd prefer to have the logic be visible, that we're draining the hints without sending them if the endpoint is DOWN.

**Comment by vladzcloudius** [comment] 2021-01-13 00:03
@bhalevy When we are draining hint we ARE sending them. It's just we don't stop if we failed to send a hint.

So, I think my proposal is pretty much what there should be.
What's needed is to go over the rest of the places where we use `can_send` make sure everything will remain safe after the change.

**Comment by piodul** [comment] 2021-02-09 14:28
It's a race condition. From `storage_service::removenode`:

https://github.com/scylladb/scylla/blob/4498bb0a48496c9cdff29364b8dea09d2ba828ee/service/storage_service.cc#L2278-L2279

`ss.excise` notifies lifecycle subscribers (this includes `hints_manager`) that the node is removed from cluster. Hints manager starts draining hints for that node. During that, the `send_hints_maybe` function is called twice. That function calls `send_one_file` in a loop, and stops if `can_send()` returns false:

https://github.com/scylladb/scylla/blob/c16e4a04239798c41fa140c14eabb250b5422983/db/hints/manager.cc#L874-L880

It's important that `send_one_file` is called for each hint file, because it also deletes the file it was called with - however, here `can_send()` returns false too early.

If you look at `can_send()`, it should theoretically return true - it does return [true](https://github.com/scylladb/scylla/blob/c16e4a04239798c41fa140c14eabb250b5422983/db/hints/manager.cc#L457) if the destination node is no longer in the cluster. However, `can_send()` determines that based on the gossiper state - but the gossiper state is updated by `advertise_token_removed` from the first snippet. If hints manager reaches the loop in `send_hints_maybe` too fast, some files will be left on disk, and later we will fail deleting the hints directory - which causes the error message in the bug report.

This error can be reproduced by inserting a 15 second sleep between the lines of the first snippet, and then running the `hintedhandoff_additional_test.py:TestHintedHandoff.hintedhandoff_removenode_test` dtest.

I sent a fix which causes the hint files to be correctly deleted when draining, regardless from what `can_send()` returns.

@asias Is it intentional that `excise` is called before `advertise_token_removed`? The first notifies all lifecycle subscribers that the node is leaving the cluster (on_leave_cluster), and the second updates the gossiper state. Should gossiper state be updated first?

**Comment by vladzcloudius** [comment] 2021-02-10 01:30
> @asias Is it intentional that `excise` is called before `advertise_token_removed`? The first notifies all lifecycle subscribers that the node is leaving the cluster (on_leave_cluster), and the second updates the gossiper state. Should gossiper state be updated first?

That's exactly the question that I'd ask and that's why I don't think that patches at https://github.com/scylladb/scylla/pull/8057 are good because they are working around the actual problem (which is a wrong order of lines above) instead of fixing it.

**Comment by piodul** [comment] 2021-02-18 15:48
@asias ping

Could you take a look at my question? I'm not familiar with storage_service nor gossiper, so I'd like to ask you first before coming up with a fix.

**Comment by piodul** [comment] 2021-03-15 08:27
This is a regression caused by 77a0f1a and unless we revert that commit or apply the workaround (#8057), it will be present in 4.4. Either one of them will prevent the error from happening (hint files will be removed for the endpoint being removed).

The problem with gossiper notifying lifetime subscribers before gossiper state is updated (described [here](https://github.com/scylladb/scylla/issues/5087#issuecomment-775980036)) won't be solved either by revert or application of the fix, but it's not a regression.

I just reminded myself of this issue. I apologize for not pushing on it faster.

cc: @bhalevy @avikivity @slivne @haaawk

**Comment by haaawk** [comment] 2021-03-15 08:32
> This is a regression caused by [77a0f1a](https://github.com/scylladb/scylla/commit/77a0f1a153d8d1f694847600e112d6bae38eba04) and unless we revert that commit or apply the workaround (#8057), it will be present in 4.4. Either one of them will prevent the error from happening (hint files will be removed for the endpoint being removed).
> 
> The problem with gossiper notifying lifetime subscribers before gossiper state is updated (described [here](https://github.com/scylladb/scylla/issues/5087#issuecomment-775980036)) won't be solved either by revert or application of the fix, but it's not a regression.
> 
> I just reminded myself of this issue. I apologize for not pushing on it faster.
> 
> cc: @bhalevy @avikivity @slivne @haaawk

Is the fix ready to be merged @piodul ? Are all the review comments addressed?

**Closed** 2021-04-02 11:53 UTC

**Comment by bhalevy** [comment] 2021-09-01 06:58
Seen in https://jenkins.scylladb.com/view/scylla-4.5/job/scylla-4.5/job/next/94/testReport/materialized_views_test/TestMaterializedViews/dtest___remove_node_during_mv_insert_3_nodes_test/
```
ERROR 2021-08-29 20:44:36,059 [shard 1] hints_manager - Exception when draining 127.0.68.2: std::filesystem::__cxx11::filesystem_error (error system:39, filesystem error: remove failed: Directory not empty [/jenkins/workspace/scylla-4.5/next/scylla/.dtest/dtest-1ioiadfr/test/node1/hints/1/127.0.68.2])
```

Requires backport to 4.5

**Comment by bhalevy** [comment] 2021-09-01 06:59
@scylladb/scylla-maint ping

**Comment by enaydanov** [comment] 2022-05-06 08:48
Got many of such errors again on 2022.1rc3:

```
2022-05-01 14:36:52.385 <2022-05-01 14:36:47.000>: (DatabaseLogEvent Severity.ERROR) period_type=one-time event_id=9b486877-800f-4176-b32a-dcad62d9db49: type=DATABASE_ERROR regex=Exception  line_number=367368 node=longevity-tls-50gb-3d-2022-1-db-node-d42bf9f0-11
2022-05-01T14:36:47+00:00 longevity-tls-50gb-3d-2022-1-db-node-d42bf9f0-11 !     ERR |  [shard 12] hints_manager - Exception when draining 10.0.2.80: std::filesystem::__cxx11::filesystem_error (error system:39, filesystem error: remove failed: Directory not empty [/var/lib/scylla/view_hints/12/10.0.2.80])
```

## Installation details

Kernel Version: 5.13.0-1021-aws
Scylla version (or git commit hash): `2022.1~rc3-20220406.5cc3b678c` with build-id `48dfae0735cd8efc4ae2f5c777beaee2a1e89f4a`
Cluster size: 6 nodes (i3.4xlarge)

Scylla Nodes used in this run:
- longevity-tls-50gb-3d-2022-1-db-node-d42bf9f0-9 (54.229.119.180 | 10.0.3.188) (shards: 14)
- longevity-tls-50gb-3d-2022-1-db-node-d42bf9f0-8 (52.212.30.67 | 10.0.0.210) (shards: 14)
- longevity-tls-50gb-3d-2022-1-db-node-d42bf9f0-7 (52.213.1.118 | 10.0.1.95) (shards: 14)
- longevity-tls-50gb-3d-2022-1-db-node-d42bf9f0-6 (34.245.204.111 | 10.0.2.238) (shards: 14)
- longevity-tls-50gb-3d-2022-1-db-node-d42bf9f0-5 (34.246.250.133 | 10.0.1.22) (shards: 14)
- longevity-tls-50gb-3d-2022-1-db-node-d42bf9f0-4 (3.250.105.37 | 10.0.0.249) (shards: 14)
- longevity-tls-50gb-3d-2022-1-db-node-d42bf9f0-36 (52.18.10.41 | 10.0.0.41) (shards: 14)
- longevity-tls-50gb-3d-2022-1-db-node-d42bf9f0-35 (54.246.213.205 | 10.0.2.152) (shards: 16)
- longevity-tls-50gb-3d-2022-1-db-node-d42bf9f0-34 (3.250.220.204 | 10.0.3.2) (shards: 14)
- longevity-tls-50gb-3d-2022-1-db-node-d42bf9f0-33 (54.171.106.191 | 10.0.0.10) (shards: 14)
- longevity-tls-50gb-3d-2022-1-db-node-d42bf9f0-32 (34.245.23.199 | 10.0.0.176) (shards: 14)
- longevity-tls-50gb-3d-2022-1-db-node-d42bf9f0-31 (34.253.205.11 | 10.0.3.63) (shards: 14)
- longevity-tls-50gb-3d-2022-1-db-node-d42bf9f0-30 (52.214.105.120 | 10.0.0.93) (shards: 14)
- longevity-tls-50gb-3d-2022-1-db-node-d42bf9f0-3 (3.250.26.107 | 10.0.1.216) (shards: 14)
- longevity-tls-50gb-3d-2022-1-db-node-d42bf9f0-29 (54.171.18.48 | 10.0.0.234) (shards: 14)
- longevity-tls-50gb-3d-2022-1-db-node-d42bf9f0-28 (34.241.159.155 | 10.0.1.245) (shards: 14)
- longevity-tls-50gb-3d-2022-1-db-node-d42bf9f0-27 (52.31.36.8 | 10.0.1.28) (shards: 14)
- longevity-tls-50gb-3d-2022-1-db-node-d42bf9f0-26 (54.171.163.160 | 10.0.0.241) (shards: 16)
- longevity-tls-50gb-3d-2022-1-db-node-d42bf9f0-25 (34.241.35.50 | 10.0.2.161) (shards: 14)
- longevity-tls-50gb-3d-2022-1-db-node-d42bf9f0-24 (54.75.100.174 | 10.0.3.108) (shards: 14)
- longevity-tls-50gb-3d-2022-1-db-node-d42bf9f0-23 (52.209.6.133 | 10.0.3.95) (shards: 14)
- longevity-tls-50gb-3d-2022-1-db-node-d42bf9f0-22 (54.155.103.122 | 10.0.3.233) (shards: 14)
- longevity-tls-50gb-3d-2022-1-db-node-d42bf9f0-21 (63.32.45.6 | 10.0.0.210) (shards: 14)
- longevity-tls-50gb-3d-2022-1-db-node-d42bf9f0-20 (34.244.145.186 | 10.0.1.236) (shards: 14)
- longevity-tls-50gb-3d-2022-1-db-node-d42bf9f0-2 (3.250.79.168 | 10.0.1.25) (shards: 14)
- longevity-tls-50gb-3d-2022-1-db-node-d42bf9f0-19 (34.240.133.141 | 10.0.2.232) (shards: 14)
- longevity-tls-50gb-3d-2022-1-db-node-d42bf9f0-18 (3.250.123.195 | 10.0.3.75) (shards: 14)
- longevity-tls-50gb-3d-2022-1-db-node-d42bf9f0-17 (34.244.150.95 | 10.0.2.41) (shards: 14)
- longevity-tls-50gb-3d-2022-1-db-node-d42bf9f0-16 (54.75.59.22 | 10.0.2.114) (shards: 14)
- longevity-tls-50gb-3d-2022-1-db-node-d42bf9f0-15 (52.212.90.162 | 10.0.3.0) (shards: 16)
- longevity-tls-50gb-3d-2022-1-db-node-d42bf9f0-14 (63.35.201.79 | 10.0.2.218) (shards: 14)
- longevity-tls-50gb-3d-2022-1-db-node-d42bf9f0-13 (52.213.168.12 | 10.0.2.80) (shards: 14)
- longevity-tls-50gb-3d-2022-1-db-node-d42bf9f0-12 (52.16.30.108 | 10.0.0.206) (shards: 14)
- longevity-tls-50gb-3d-2022-1-db-node-d42bf9f0-11 (3.250.146.18 | 10.0.0.75) (shards: 14)
- longevity-tls-50gb-3d-2022-1-db-node-d42bf9f0-10 (3.248.196.89 | 10.0.0.147) (shards: 14)
- longevity-tls-50gb-3d-2022-1-db-node-d42bf9f0-1 (34.240.32.204 | 10.0.3.104) (shards: 14)


OS / Image: `ami-071c70d20f0fdbb2c` (aws: eu-west-1)

Test: `EaR-longevity-kmip-50gb-4d-test`
Test id: `d42bf9f0-1497-4970-9c2b-c2de37571cc6`
Test name: `enterprise-2022.1/SCT_Enterprise_Features/EncryptionAtRest/EaR-longevity-kmip-50gb-4d-test`
Test config file(s):

- [longevity-50GB-3days-authorization-and-tls-ssl.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/819fb47d993a559a2437813022484d433e20c63f/test-cases/longevity/longevity-50GB-3days-authorization-and-tls-ssl.yaml)

- Restore Monitor Stack command: `$ hydra investigate show-monitor d42bf9f0-1497-4970-9c2b-c2de37571cc6`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=d42bf9f0-1497-4970-9c2b-c2de37571cc6)
- Show all stored logs command: `$ hydra investigate show-logs d42bf9f0-1497-4970-9c2b-c2de37571cc6`

## Logs:
- **db-cluster-d42bf9f0.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/d42bf9f0-1497-4970-9c2b-c2de37571cc6/20220503_141859/db-cluster-d42bf9f0.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/d42bf9f0-1497-4970-9c2b-c2de37571cc6/20220503_141859/db-cluster-d42bf9f0.tar.gz)
- **monitor-set-d42bf9f0.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/d42bf9f0-1497-4970-9c2b-c2de37571cc6/20220503_141859/monitor-set-d42bf9f0.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/d42bf9f0-1497-4970-9c2b-c2de37571cc6/20220503_141859/monitor-set-d42bf9f0.tar.gz)
- **loader-set-d42bf9f0.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/d42bf9f0-1497-4970-9c2b-c2de37571cc6/20220503_141859/loader-set-d42bf9f0.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/d42bf9f0-1497-4970-9c2b-c2de37571cc6/20220503_141859/loader-set-d42bf9f0.tar.gz)
- **normal-d42bf9f0.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/d42bf9f0-1497-4970-9c2b-c2de37571cc6/20220503_141859/normal-d42bf9f0.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/d42bf9f0-1497-4970-9c2b-c2de37571cc6/20220503_141859/normal-d42bf9f0.log.tar.gz)
- **summary-d42bf9f0.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/d42bf9f0-1497-4970-9c2b-c2de37571cc6/20220503_141859/summary-d42bf9f0.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/d42bf9f0-1497-4970-9c2b-c2de37571cc6/20220503_141859/summary-d42bf9f0.log.tar.gz)
- **events-d42bf9f0.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/d42bf9f0-1497-4970-9c2b-c2de37571cc6/20220503_141859/events-d42bf9f0.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/d42bf9f0-1497-4970-9c2b-c2de37571cc6/20220503_141859/events-d42bf9f0.log.tar.gz)
- **output-d42bf9f0.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/d42bf9f0-1497-4970-9c2b-c2de37571cc6/20220503_141859/output-d42bf9f0.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/d42bf9f0-1497-4970-9c2b-c2de37571cc6/20220503_141859/output-d42bf9f0.log.tar.gz)
- **debug-d42bf9f0.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/d42bf9f0-1497-4970-9c2b-c2de37571cc6/20220503_141859/debug-d42bf9f0.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/d42bf9f0-1497-4970-9c2b-c2de37571cc6/20220503_141859/debug-d42bf9f0.log.tar.gz)
- **sct-d42bf9f0.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/d42bf9f0-1497-4970-9c2b-c2de37571cc6/20220503_141859/sct-d42bf9f0.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/d42bf9f0-1497-4970-9c2b-c2de37571cc6/20220503_141859/sct-d42bf9f0.log.tar.gz)
- **error-d42bf9f0.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/d42bf9f0-1497-4970-9c2b-c2de37571cc6/20220503_141859/error-d42bf9f0.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/d42bf9f0-1497-4970-9c2b-c2de37571cc6/20220503_141859/error-d42bf9f0.log.tar.gz)
- **critical-d42bf9f0.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/d42bf9f0-1497-4970-9c2b-c2de37571cc6/20220503_141859/critical-d42bf9f0.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/d42bf9f0-1497-4970-9c2b-c2de37571cc6/20220503_141859/critical-d42bf9f0.log.tar.gz)
- **raw_events-d42bf9f0.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/d42bf9f0-1497-4970-9c2b-c2de37571cc6/20220503_141859/raw_events-d42bf9f0.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/d42bf9f0-1497-4970-9c2b-c2de37571cc6/20220503_141859/raw_events-d42bf9f0.log.tar.gz)
- **warning-d42bf9f0.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/d42bf9f0-1497-4970-9c2b-c2de37571cc6/20220503_141859/warning-d42bf9f0.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/d42bf9f0-1497-4970-9c2b-c2de37571cc6/20220503_141859/warning-d42bf9f0.log.tar.gz)
- **email_data-d42bf9f0.json.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/d42bf9f0-1497-4970-9c2b-c2de37571cc6/20220503_141859/email_data-d42bf9f0.json.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/d42bf9f0-1497-4970-9c2b-c2de37571cc6/20220503_141859/email_data-d42bf9f0.json.tar.gz)
- **argus-d42bf9f0.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/d42bf9f0-1497-4970-9c2b-c2de37571cc6/20220503_141859/argus-d42bf9f0.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/d42bf9f0-1497-4970-9c2b-c2de37571cc6/20220503_141859/argus-d42bf9f0.log.tar.gz)
- **left_processes-d42bf9f0.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/d42bf9f0-1497-4970-9c2b-c2de37571cc6/20220503_141859/left_processes-d42bf9f0.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/d42bf9f0-1497-4970-9c2b-c2de37571cc6/20220503_141859/left_processes-d42bf9f0.log.tar.gz)


[Jenkins job URL](https://jenkins.scylladb.com/job/enterprise-2022.1/job/SCT_Enterprise_Features/job/EncryptionAtRest/job/EaR-longevity-kmip-50gb-4d-test/3/)

**Comment by avikivity** [comment] 2022-09-01 17:50
Fix present on all active branches, not backporting.
