### ISSUE TITLE
row_cache_test::test_exception_safety_of_reads SIGSEGVs in some runs

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/scylla#3095] opened 2017-12-22 11:06 UTC
Scylla version (or git commit hash): tested with master (4dfddc97c7888e534a5348af43a70d59a6572711)

Not always fails, but fails quite often. I haven't investigated, but it could be related to flattening.

```
./configure.py --mode release --enable-alloc-failure-injector
build/release/tests/row_cache_test_g --run_test=test_exception_safety_of_reads
```

```
Running 1 test case...
WARN  2017-12-22 12:01:42,082 [shard 0] seastar - Unable to set SCHED_FIFO scheduling policy for timer thread; latency impact possible. Try adding CAP_SYS_NICE
Random seed: 4123549923
Segmentation fault on shard 0.
Backtrace:
  0x00000000004afa2b
  0x00000000004afafc
  0x00000000004afb53
  /lib64/libpthread.so.0+0x00000000000123af
  0x00000000009c305b
  0x00000000004acf96
  0x00000000004ad26c
  0x00000000004fcc74
  0x000000000059029e
  0x00000000019190c9
  0x000000000056414d
  /lib64/libpthread.so.0+0x000000000000736c
  /lib64/libc.so.6+0x0000000000110e1e
Segmentation fault (core dumped)
```
```
seastar::backtrace_buffer::append_backtrace() at /home/tgrabiec/src/scylla2/seastar/core/reactor.cc:294
 (inlined by) print_with_backtrace at /home/tgrabiec/src/scylla2/seastar/core/reactor.cc:315
seastar::print_with_backtrace(char const*) at /home/tgrabiec/src/scylla2/seastar/core/reactor.cc:322
sigsegv_action at /home/tgrabiec/src/scylla2/seastar/core/reactor.cc:3727
 (inlined by) operator() at /home/tgrabiec/src/scylla2/seastar/core/reactor.cc:3713
 (inlined by) _FUN at /home/tgrabiec/src/scylla2/seastar/core/reactor.cc:3709
?? ??:0
std::__uniq_ptr_impl<flat_mutation_reader::impl, std::default_delete<flat_mutation_reader::impl> >::_M_ptr() const at /usr/include/c++/7/bits/unique_ptr.h:147
 (inlined by) std::unique_ptr<flat_mutation_reader::impl, std::default_delete<flat_mutation_reader::impl> >::get() const at /usr/include/c++/7/bits/unique_ptr.h:337
 (inlined by) std::unique_ptr<flat_mutation_reader::impl, std::default_delete<flat_mutation_reader::impl> >::operator->() const at /usr/include/c++/7/bits/unique_ptr.h:331
 (inlined by) flat_mutation_reader::is_end_of_stream() const at /home/tgrabiec/src/scylla2/flat_mutation_reader.hh:372
 (inlined by) operator() at /home/tgrabiec/src/scylla2/mutation_reader.cc:737
 (inlined by) apply at /home/tgrabiec/src/scylla2/./seastar/core/apply.hh:36
 (inlined by) apply<mutation_reader_from_flat_mutation_reader(flat_mutation_reader&&)::converting_reader::operator()()::partition_reader::fill_buffer()::<lambda()> > at /home/tgrabiec/src/scylla2/./seastar/core/apply.hh:44
 (inlined by) do_void_futurize_apply_tuple<mutation_reader_from_flat_mutation_reader(flat_mutation_reader&&)::converting_reader::operator()()::partition_reader::fill_buffer()::<lambda()> > at /home/tgrabiec/src/scylla2/./seastar/core/future.hh:1320
 (inlined by) apply<mutation_reader_from_flat_mutation_reader(flat_mutation_reader&&)::converting_reader::operator()()::partition_reader::fill_buffer()::<lambda()> > at /home/tgrabiec/src/scylla2/./seastar/core/future.hh:1340
 (inlined by) operator()<seastar::future_state<> > at /home/tgrabiec/src/scylla2/./seastar/core/future.hh:933
 (inlined by) run_and_dispose at /home/tgrabiec/src/scylla2/./seastar/core/future.hh:413
seastar::reactor::run_tasks(seastar::reactor::task_queue&) at /home/tgrabiec/src/scylla2/seastar/core/reactor.cc:2443
seastar::reactor::run_some_tasks(std::chrono::time_point<std::chrono::_V2::steady_clock, std::chrono::duration<long, std::ratio<1l, 1000000000l> > >&) at /home/tgrabiec/src/scylla2/seastar/core/reactor.cc:2840
seastar::reactor::run_some_tasks(std::chrono::time_point<std::chrono::_V2::steady_clock, std::chrono::duration<long, std::ratio<1l, 1000000000l> > >&) at /usr/include/c++/7/chrono:377
 (inlined by) seastar::reactor::run() at /home/tgrabiec/src/scylla2/seastar/core/reactor.cc:2984
seastar::app_template::run_deprecated(int, char**, std::function<void ()>&&) at /home/tgrabiec/src/scylla2/seastar/core/app-template.cc:180
seastar::test_runner::start(int, char**)::{lambda()#1}::operator()() at /home/tgrabiec/src/scylla2/seastar/tests/test_runner.cc:63
std::function<void ()>::operator()() const at /usr/include/c++/7/bits/std_function.h:706
 (inlined by) seastar::posix_thread::start_routine(void*) at /home/tgrabiec/src/scylla2/seastar/core/posix.cc:52
```

**Comment by pdziepak** [comment] 2018-01-11 16:14
This is caused by scylladb/seastar#384.

**Comment by slivne** [comment] 2018-01-14 11:10
@tgrabiec - are we missing backborts to 2.1 ?

**Comment by slivne** [comment] 2018-01-22 09:17
> shlomi [11:46 AM] 
> @pdziepak - to be clearer - does the issue of #384 exist in the code base of 2.1 and can it be triggered ?
> 
> 
> pdziepak [11:52 AM] 
> Yes and yes, but it is very unlikely to happen in the real life (i.e. without failure injector) and when it does the fix is to abort (instead of proceeding and getting a random segfault).

pushing this out to 2.2 - the fix is already merged.

**Closed by slivne** 2018-01-22 09:17 UTC
Labels: Regression, bug
