### ISSUE TITLE
toDate() in cqlsh does not return the correct date

### ISSUE THREAD

**Issue by locke2833** [scylladb/scylla#5521] opened 2019-12-25 21:10 UTC
- [X] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash): 3.0.8
Cluster size:
OS (RHEL/CentOS/Ubuntu/AWS AMI): Ubuntu 18.04

Platform (physical/VM/cloud instance type/docker): docker

`toDate` function in cqlsh seems does not return the correct date.

```
cqlsh 5.0.1 | Cassandra 3.0.8 | CQL spec 3.3.1 | Native protocol v4

SELECT toDate(ts),  ts FROM identity;

 system.todate(ts) | ts
-------------------+---------------------------------
        1970-01-19 | 1970-01-19 06:08:23.156000+0000
        1970-01-19 | 1970-01-19 06:08:23.280000+0000

```
It does not consider the [.fff] in time HH:MM:SS[.fff].

**Comment by slivne** [comment] 2019-12-29 21:53
@locke2833 I don't understand whats the issue is, 

I ran the following on cassandra 3.11.3 and I got similar results 


```
describe schema;

CREATE KEYSPACE ks WITH replication = {'class': 'SimpleStrategy', 'replication_factor': '1'}  AND durable_writes = true;

CREATE TABLE ks.tb (
    ts timestamp PRIMARY KEY,
    v int
)

insert INTO ks.tb (ts, v) values (totimestamp(now()), 0);
insert INTO ks.tb (ts, v) values (totimestamp(now()), 0);

select toDate(ts),ts from ks.tb ;

select toDate(ts),ts from ks.tb ;

 system.todate(ts) | ts
-------------------+---------------------------------
        2019-12-29 | 2019-12-29 21:50:59.328000+0000
        2019-12-29 | 2019-12-29 21:52:27.865000+0000

(1 rows)
```

**Comment by slivne** [comment] 2020-01-02 10:16
@locke2833 hi 

I am closing this bug for now - if you have additional information please post and we can reopen.

**Closed by slivne** 2020-01-02 10:16 UTC
Labels: User Request
