### ISSUE TITLE
view_build_test: test_builder_with_concurrent_drop: Expected no rows, but got 1

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#4707] opened 2019-07-14 19:27 UTC
Scylla version 997a146c7fe372f7e8d28dbed395349f6af2957d
[next/987](https://jenkins.scylladb.com/view/master/job/scylla-master/job/next/987/consoleText):
```
[2019-07-14T15:36:34.315Z] Output of the failed tests:
[2019-07-14T15:36:34.315Z] Test build/debug/tests/view_build_test --report_level=no --logger=HRF,test_suite:XML,test_suite,jenkins_test.debug.view_build_test.boost.xml -- -c2 -m2G --overprovisioned --unsafe-bypass-fsync 1 --blocked-reactor-notify-ms 2000000 --collectd 0 failed:
[2019-07-14T15:36:34.315Z]   with error code 201
...
[2019-07-14T15:36:34.315Z] random-seed=181750317
...
[2019-07-14T15:36:34.338Z] unknown location(0): fatal error: in "test_builder_with_concurrent_drop": std::runtime_error: Expected no rows, but got 1. First row: [6b73, 766366, 00000001, 2d39323233333732303336383534373735383038, 00000000, 393136363436303038363638353632393539]
```

**Comment by slivne** [comment] 2019-07-18 09:58
@bhalevy is this consistent ?

**Comment by bhalevy** [comment] 2019-07-22 08:17
Happened again in [next/1005](https://jenkins.scylladb.com/view/master/job/scylla-master/job/next/1005/consoleText)
Scylla version db8d4a0cc649c74e30198dd83b082b0ad50b1314
```
[2019-07-21T12:47:16.157Z] INFO  2019-07-21 15:22:13,899 [shard 0] view - Stopping to build view ks.vcf
[2019-07-21T12:47:16.157Z] INFO  2019-07-21 15:22:14,497 [shard 0] database - Schema version changed to fe78cd1d-6785-3890-8501-55fa8c0906c0
[2019-07-21T12:47:16.157Z] INFO  2019-07-21 15:22:14,558 [shard 0] compaction - Compacted 2 sstables to [/tmp/scylla-747d96ab-2d2f-478e-adeb-65ef39a2baa1/system/truncated-38c19fd0fb863310a4b70d0cc66628aa/mc-6-big-Data.db:level=0, ]. 10466 bytes to 5549 (~53% of original) in 686ms =
 0.01MB/s. ~256 total partitions merged to 1.
[2019-07-21T12:47:16.157Z] INFO  2019-07-21 15:22:14,958 [shard 0] view - Building view ks.vcf, starting at token minimum token
[2019-07-21T12:47:16.157Z] INFO  2019-07-21 15:22:18,997 [shard 0] view - Stopping view builder
[2019-07-21T12:47:16.157Z] INFO  2019-07-21 15:22:18,997 [shard 1] view - Stopping view builder
[2019-07-21T12:47:16.157Z] INFO  2019-07-21 15:22:19,004 [shard 0] gossip - My status = NORMAL
[2019-07-21T12:47:16.157Z] INFO  2019-07-21 15:22:19,004 [shard 0] gossip - Announcing shutdown
[2019-07-21T12:47:16.157Z] INFO  2019-07-21 15:22:19,010 [shard 0] storage_service - Node 127.0.0.1 state jump to normal
[2019-07-21T12:47:16.157Z] INFO  2019-07-21 15:22:19,074 [shard 0] compaction - Compacting [/tmp/scylla-747d96ab-2d2f-478e-adeb-65ef39a2baa1/system/peers-37f71aca7dc2383ba70672528af04d4f/mc-4-big-Data.db:level=0, /tmp/scylla-747d96ab-2d2f-478e-adeb-65ef39a2baa1/system/peers-37f71ac
a7dc2383ba70672528af04d4f/mc-2-big-Data.db:level=0, ]
[2019-07-21T12:47:16.157Z] INFO  2019-07-21 15:22:19,092 [shard 0] compaction_manager - Asked to stop
[2019-07-21T12:47:16.157Z] INFO  2019-07-21 15:22:19,092 [shard 1] compaction_manager - Asked to stop
[2019-07-21T12:47:16.157Z] INFO  2019-07-21 15:22:19,093 [shard 1] compaction_manager - Stopped
[2019-07-21T12:47:16.157Z] INFO  2019-07-21 15:22:19,138 [shard 0] compaction - Compacted 2 sstables to [/tmp/scylla-747d96ab-2d2f-478e-adeb-65ef39a2baa1/system/peers-37f71aca7dc2383ba70672528af04d4f/mc-6-big-Data.db:level=0, ]. 10953 bytes to 5788 (~52% of original) in 62ms = 0.09
MB/s. ~256 total partitions merged to 1.
[2019-07-21T12:47:16.157Z] INFO  2019-07-21 15:22:19,150 [shard 0] compaction_manager - Stopped
[2019-07-21T12:47:16.157Z] unknown location(0): fatal error: in "test_builder_with_concurrent_drop": std::runtime_error: Expected no rows, but got 1. First row: [6b73, 766366, 00000001, 2d39323233333732303336383534373735383038, 00000000, 2d38343534353532363532313633363030343434]
```

Couldn't reproduce with the same random seed.  This seems to be timing related.
@nyh / @psarna test missing `eventually` maybe?

**Comment by bhalevy** [comment] 2019-11-04 23:25
Reproduced in [next/1291](https://jenkins.scylladb.com/job/scylla-master/job/next/1291/testReport/junit/tests_view_build_test.cc/_data_jenkins_workspace_scylla-master_next_scylla_seastar_src_testing_seastar_test/test_builder_with_concurrent_drop/)

**Comment by psarna** [comment] 2019-11-12 09:54
This test uses `eventually` in a proper place, but perhaps for this specific case the default number of retries is not enough... I just tried running the test with `--repeat 10000` and it hasn't failed a single time, so it doesn't seem easy to reproduce, but logs from [next/1291](https://jenkins.scylladb.com/job/scylla-master/job/next/1291/testReport/junit/tests_view_build_test.cc/_data_jenkins_workspace_scylla-master_next_scylla_seastar_src_testing_seastar_test/test_builder_with_concurrent_drop/) seem to show that the test lasted for more than 4 seconds, and that's more or less the time after `eventually` will give up and stop trying. We can try raising the number of retries a little bit and seeing what happens - if everything starts working properly then it was definitely just a timing issue, and if something is stuck for, say, 16 seconds, then it's definitely a sign of a deadlock.

P.S. I was also a little concerned with `no_sharded_instance_exception` happening in that test case (which I also can't reproduce), but it looks like it's common to many other test cases as well and seems harmless. Any chance that binaries for these test runs still exist, so we can try decoding the error and seeing which shared instance was missing? The exception is thrown with backtrace so it should be fairly easy to pinpoint.

**Comment by nyh** [comment] 2019-11-14 08:00
https://jenkins.scylladb.com/job/scylla-master/job/next/1291/testReport/tests_view_build_test.cc/_data_jenkins_workspace_scylla-master_next_scylla_seastar_src_testing_seastar_test/test_builder_with_concurrent_drop/ suggests that this test took a whopping 42 seconds to run. If this is actually true, it is not surprising that a 4 second timeout wasn't enough. The last time this test ran, for example, it only took less than a second: https://jenkins.scylladb.com/job/scylla-master/job/next/1304/testReport/tests_view_build_test/cc/test_builder_with_concurrent_drop/. So definitely the 42 second run is not normal.

We can continue to increase the timeout, but it's possible that even 16 seconds would not have been enough if the test really took 42 seconds. Also increasing this timeout is annoying for developers because a failed test (a common occurrence during development) needs to wait for this timeout before declaring a failure.

Alternatively, I think it's important we figure out why sometimes we get tests running 50 times slower than normal. Perhaps we're overcommitting the build machine **too** much?

**Comment by avikivity** [comment] 2020-01-27 16:01
I just saw this again. I reproduced on a 1s6c12t machine with:

```
$ for ((i = 0; i < 10; ++i)) do build/debug/test/boost/view_build_test  > /tmp/out.$i.log 2>&1 & done ; wait; tail -n2 /tmp/out.*.log
[1] 3547554
[2] 3547555
[3] 3547556
[4] 3547557
[5] 3547558
[6] 3547559
[7] 3547560
[8] 3547561
[9] 3547562
[10] 3547563
[1]   Exit 201                build/debug/test/boost/view_build_test > /tmp/out.$i.log 2>&1
[5]   Done                    build/debug/test/boost/view_build_test > /tmp/out.$i.log 2>&1
[6]   Done                    build/debug/test/boost/view_build_test > /tmp/out.$i.log 2>&1
[7]   Done                    build/debug/test/boost/view_build_test > /tmp/out.$i.log 2>&1
[8]   Done                    build/debug/test/boost/view_build_test > /tmp/out.$i.log 2>&1
[9]-  Done                    build/debug/test/boost/view_build_test > /tmp/out.$i.log 2>&1
[2]   Done                    build/debug/test/boost/view_build_test > /tmp/out.$i.log 2>&1
[3]   Done                    build/debug/test/boost/view_build_test > /tmp/out.$i.log 2>&1
[4]-  Done                    build/debug/test/boost/view_build_test > /tmp/out.$i.log 2>&1
[10]+  Done                    build/debug/test/boost/view_build_test > /tmp/out.$i.log 2>&1
==> /tmp/out.0.log <==
*** 1 failure is detected in the test module "test/boost/view_build_test.cc"

==> /tmp/out.1.log <==
*** No errors detected

==> /tmp/out.2.log <==
*** No errors detected

==> /tmp/out.3.log <==
*** No errors detected

==> /tmp/out.4.log <==
*** No errors detected

==> /tmp/out.5.log <==
*** No errors detected

==> /tmp/out.6.log <==
*** No errors detected

==> /tmp/out.7.log <==
*** No errors detected

==> /tmp/out.8.log <==
*** No errors detected

==> /tmp/out.9.log <==
*** No errors detected
```

**Comment by avikivity** [comment] 2020-01-27 16:02
The tests are run with at most 1 test per logical core. Since each test uses 2 shards, there is at most 2X overcommit, and usually a lot less.

**Comment by avikivity** [comment] 2020-01-27 16:02
(closed by mistake, reopening)

**Comment by avikivity** [comment] 2020-01-27 16:17
@nyh note that debug mode slows down things significantly.

**Comment by avikivity** [comment] 2020-01-27 16:18
Perhaps we can make the timeout depend on the build mode. If in debug mode, then timeout *= 10.

**Comment by avikivity** [comment] 2020-01-27 16:20
Another option is to replace the timeout by a test about whether all background work has been completed. This will result in earlier completion when things are fast, and no dependency on the runtime.

**Closed** 2020-01-31 16:11 UTC
Labels: Backport candidate, bug, materialized-views, unitest

**Comment by avikivity** [comment] 2020-02-01 11:25
Backported to 3.1, 3.2, 3.3.
