### ISSUE TITLE
[1.5 RC1 AMI] Longevity in > 1TB data cluster fails

### ISSUE THREAD

**Issue by lmr** [scylladb/scylla#1891] opened 2016-11-26 01:12 UTC
Installation details
Scylla version (or git commit hash): 1.5 RC1 AMI
Cluster size: 4 Nodes, i2.4xlarge
OS (RHEL/CentOS/Ubuntu/AWS AMI): AWS AMI

This is a bug report for an issue observed when running a longevity test on a 4 Node
cluster i2.2xlarge, with the intention of having a test on a cluster
holding more than 1 TB of data per node. 

We ran 2 loaders, both running the following c-s commands:

2016-11-18 14:09:03,501 job              L0430 INFO |       |    -> stress_cmd: cassandra-stress write cl=QUORUM duration=10080m -schema
'replication(factor=3)' -port jmx=6868 -mode cql3 native -rate
threads=200 -col 'size=FIXED(1000) n=FIXED(1)' -pop seq=1..1250000000

After about 26 hours, both c-s loads died:

    2016-11-24 15:51:33,962 remote           L0194 DEBUG| [54.87.188.189] [stdout] total,        121608,  121568,  121568,  121568,     1.7,     1.4,     2.3,     6.2,    24.4,    28.2, 
       1.0,  0.00000,      0,      0,       0,       0,       0,       0
    ...
    2016-11-25 17:03:48,831 remote           L0194 DEBUG| [52.23.159.229] [stdout] java.io.IOException: Operation x10 on key(s) [4d344f354d3250395030]: Error executing: (UnavailableException): Not enough replicas available for query at consistency QUORUM (2 required but only 2 alive)

Checking the last disruption that happened:

    2016-11-25 05:09:05,494 nemesis          L0160 INFO | sdcm.nemesis.ChaosMonkey: Decommission Node scylla-1-5-ld-chaos-scylla-db-node-fd89d149-3 [54.91.212.220 | 172.30.0.160] (seed: False)

The decommission process never finished, and then 12 hors later approximately, the load died.

We also found a coredump, generated about 3 hours after the load started. Its backtrace is not very helpful:

               PID: 2727 (scylla)
               UID: 994 (scylla)
               GID: 1001 (scylla)
            Signal: 6 (ABRT)
         Timestamp: Thu 2016-11-24 18:30:29 UTC (1min 34s ago)
      Command Line: /usr/bin/scylla --log-to-syslog 1 --log-to-stdout 0 --default-log-level info --collectd-address=127.0.0.1:25826 --collectd=1 --collectd-poll-period 3000 --network-stack posix --num-io-queues 16 --max-io-requests 128 --cpuset 1,2,3,4,5,6,7,9,10,11,12,13,14,15
        Executable: /usr/bin/scylla
     Control Group: /system.slice/scylla-server.service
              Unit: scylla-server.service
             Slice: system.slice
           Boot ID: 1e61023797154f96b2b04337cc25bdef
        Machine ID: 8ea3e6ea03b64d018847fcdf669935d4
          Hostname: ip-172-30-0-159
          Coredump: /var/lib/systemd/coredump/core.scylla.994.1e61023797154f96b2b04337cc25bdef.2727.1480012229000000
           Message: Process 2727 (scylla) of user 994 dumped core.
                    
                    Stack trace of thread 2730:
                    #0  0x00007f20e1f845f7 n/a (n/a)

And the generated coredump is pretty large. The compressed file has 63GB. I'll try to provide a way to access that file.

**Comment by lmr** [comment] 2016-11-26 03:11
OK, I've split the compressed core file in a bunch of places. I came up with a shell script to download the pieces and recompose it:

    #!/bin/bash
    for i in {a..m}
    do
        curl --user-agent [user-agent] scylladb-users-upload.s3.amazonaws.com/core.scylla.994.1e61023797154f96b2b04337cc25bdef.2727.1480012229000/xa$i > xa$i
    done
    cat xa{a..m} > core.scylla.994.1e61023797154f96b2b04337cc25bdef.2727.1480012229000000.bz2

**Comment by lmr** [comment] 2016-11-27 20:08
The full suite logs can be downloaded using:

    curl --user-agent [user-agent] scylladb-users-upload.s3.amazonaws.com/core.scylla.994.1e61023797154f96b2b04337cc25bdef.2727.1480012229000/job-2016-11-24T15.41-f6d8db5.tar.bz2 > job-2016-11-24T15.41-f6d8db5.tar.bz2

**Comment by tgrabiec** [comment] 2016-11-29 10:20
Which AMI is it exactly (name, region)? I can't find it.

**Comment by tgrabiec** [comment] 2016-11-29 10:57
It's `ami-38c2f22f` (`scylla_2016-11-23T19-42-06Z`) in Virginia, right?

**Comment by slivne** [comment] 2016-11-29 11:00
thats the one that pekka shared in his email 1.5 rc1 - so it should be that

**Comment by tgrabiec** [comment] 2016-11-29 11:13
The abort backtrace is:
```
void boost::intrusive::detail::destructor_impl<boost::intrusive::generic_hook<boost::intrusive::circular_list_algorithms<boost::intrusive::list_node_traits<void*> >, boost::intrusive::member_tag, (boost::intrusive::link_mode_type)1, (boost::intrusive::base_hook_type)0> >(boost::intrusive::generic_hook<boost::intrusive::circular_list_algorithms<boost::intrusive::list_node_traits<void*> >, boost::intrusive::member_tag, (boost::intrusive::link_mode_type)1, (boost::intrusive::base_hook_type)0>&, boost::intrusive::detail::link_dispatch<(boost::intrusive::link_mode_type)1>) at /opt/scylladb/include/boost/intrusive/detail/generic_hook.hpp:47
 (inlined by) _ZN5boost9intrusive12generic_hookINS0_24circular_list_algorithmsINS0_16list_node_traitsIPvEEEENS0_10member_tagELNS0_14link_mode_typeE1ELNS0_14base_hook_typeE0EED4Ev at /opt/scylladb/include/boost/intrusive/detail/generic_hook.hpp:190
 (inlined by) _ZN5boost9intrusive16list_member_hookIvvvED4Ev at /opt/scylladb/include/boost/intrusive/list_hook.hpp:205
 (inlined by) _ZN5timerINSt6chrono3_V212steady_clockEED4Ev at /usr/src/debug/scylla-1.5.rc1/seastar/core/reactor.hh:1330
 (inlined by) _ZN15basic_semaphoreI35semaphore_default_exception_factoryE5entryD4Ev at /usr/src/debug/scylla-1.5.rc1/seastar/core/semaphore.hh:92
 (inlined by) chunked_fifo<basic_semaphore<semaphore_default_exception_factory>::entry, 128ul>::pop_front() at /usr/src/debug/scylla-1.5.rc1/seastar/core/chunked_fifo.hh:433
 (inlined by) basic_semaphore<semaphore_default_exception_factory>::signal(unsigned long) at /usr/src/debug/scylla-1.5.rc1/seastar/core/semaphore.hh:234
basic_semaphore<semaphore_default_exception_factory>::signal(unsigned long) at /usr/src/debug/scylla-1.5.rc1/seastar/core/fstream.cc:314
 (inlined by) file_data_sink_impl::put(temporary_buffer<char>)::{lambda()#1}::operator()()::{lambda()#1}::operator()() const at /usr/src/debug/scylla-1.5.rc1/seastar/core/fstream.cc:314
 (inlined by) future<>::finally_body<file_data_sink_impl::put(temporary_buffer<char>)::{lambda()#1}::operator()()::{lambda()#1}, false>::operator()(future<>&&) at /usr/src/debug/scylla-1.5.rc1/seastar/core/future.hh:1001
 (inlined by) future<> futurize<future<> >::apply<future<>::finally_body<file_data_sink_impl::put(temporary_buffer<char>)::{lambda()#1}::operator()()::{lambda()#1}, false>, future<> >(future<>::finally_body<file_data_sink_impl::put(temporary_buffer<char>)::{lambda()#1}::operator()()::{lambda()#1}, false>&&, future<>&&) at /usr/src/debug/scylla-1.5.rc1/seastar/core/future.hh:1277
 (inlined by) _ZZN6futureIJEE12then_wrappedINS0_12finally_bodyIZZN19file_data_sink_impl3putE16temporary_bufferIcEENUlvE_clEvEUlvE_Lb0EEES0_EET0_OT_ENUlSB_E_clI12future_stateIJEEEEDaSB_ at /usr/src/debug/scylla-1.5.rc1/seastar/core/future.hh:911
 (inlined by) _ZN12continuationIZN6futureIJEE12then_wrappedINS1_12finally_bodyIZZN19file_data_sink_impl3putE16temporary_bufferIcEENUlvE_clEvEUlvE_Lb0EEES1_EET0_OT_EUlSC_E_JEE3runEv at /usr/src/debug/scylla-1.5.rc1/seastar/core/future.hh:390
reactor::run_tasks(circular_buffer<std::unique_ptr<task, std::default_delete<task> >, std::allocator<std::unique_ptr<task, std::default_delete<task> > > >&) at /usr/src/debug/scylla-1.5.rc1/seastar/core/reactor.cc:1971
reactor::run() at /usr/src/debug/scylla-1.5.rc1/seastar/core/reactor.cc:2404
operator() at /usr/src/debug/scylla-1.5.rc1/seastar/core/reactor.cc:3344
std::function<void ()>::operator()() const at /opt/scylladb/include/c++/5.3.1/functional:2271
 (inlined by) posix_thread::start_routine(void*) at /usr/src/debug/scylla-1.5.rc1/seastar/core/posix.cc:50
```

So it looks like the same problem as in #1874, caused by #990

**Comment by tgrabiec** [comment] 2016-11-29 11:22
@lmr Do you have prometheus database for this run?

**Comment by tgrabiec** [comment] 2016-11-29 11:58
The streaming on decomissioning was not able to make progress with one of the nodes:

```
[54.91.212.220] [stdout] Nov 25 05:09:37 info   |  [shard 0] stream_session - [Stream #5cfea190-b2cd-11e6-bcc7-000000000007] Executing streaming plan for Unbootstrap
[54.91.212.220] [stdout] Nov 25 05:09:37 info   |  [shard 0] stream_session - [Stream #5cfea190-b2cd-11e6-bcc7-000000000007] Starting streaming to 172.30.0.159
[54.91.212.220] [stdout] Nov 25 05:09:37 info   |  [shard 0] stream_session - [Stream #5cfea190-b2cd-11e6-bcc7-000000000007] Beginning stream session with 172.30.0.159
[54.91.212.220] [stdout] Nov 25 05:09:37 info   |  [shard 0] stream_session - [Stream #5cfea190-b2cd-11e6-bcc7-000000000007] Starting streaming to 172.30.0.161
[54.91.212.220] [stdout] Nov 25 05:09:37 info   |  [shard 0] stream_session - [Stream #5cfea190-b2cd-11e6-bcc7-000000000007] Beginning stream session with 172.30.0.161
[54.91.212.220] [stdout] Nov 25 05:09:37 info   |  [shard 0] stream_session - [Stream #5cfea190-b2cd-11e6-bcc7-000000000007] Starting streaming to 172.30.0.163
[54.91.212.220] [stdout] Nov 25 05:09:37 info   |  [shard 0] stream_session - [Stream #5cfea190-b2cd-11e6-bcc7-000000000007] Beginning stream session with 172.30.0.163
[54.91.212.220] [stdout] Nov 25 05:09:37 info   |  [shard 0] stream_session - [Stream #5cfea190-b2cd-11e6-bcc7-000000000007] Prepare completed with 172.30.0.163. Receiving 0, sending 4
[54.91.212.220] [stdout] Nov 25 05:09:37 info   |  [shard 0] stream_session - [Stream #5cfea190-b2cd-11e6-bcc7-000000000007] Prepare completed with 172.30.0.159. Receiving 0, sending 4
[54.91.212.220] [stdout] Nov 25 05:09:37 info   |  [shard 0] stream_session - [Stream #5cfea190-b2cd-11e6-bcc7-000000000007] Prepare completed with 172.30.0.161. Receiving 0, sending 4
[54.91.212.220] [stdout] Nov 25 11:02:41 info   |  [shard 0] stream_session - [Stream #5cfea190-b2cd-11e6-bcc7-000000000007] The session 0x60010aae2c00 made no progress with peer 172.30.0.159
[54.91.212.220] [stdout] Nov 25 11:03:41 info   |  [shard 0] stream_session - [Stream #5cfea190-b2cd-11e6-bcc7-000000000007] The session 0x60010aae2c00 made no progress with peer 172.30.0.159
[54.91.212.220] [stdout] Nov 25 11:04:41 info   |  [shard 0] stream_session - [Stream #5cfea190-b2cd-11e6-bcc7-000000000007] The session 0x60010aae2c00 made no progress with peer 172.30.0.159
[54.91.212.220] [stdout] Nov 25 11:05:36 warning|  [shard 5] stream_session - [Stream #5cfea190-b2cd-11e6-bcc7-000000000007] stream_transfer_task: Fail to send STREAM_MUTATION to 172.30.0.159:11: rpc::closed_error (connection is closed)
[54.91.212.220] [stdout] Nov 25 11:05:41 info   |  [shard 0] stream_session - [Stream #5cfea190-b2cd-11e6-bcc7-000000000007] The session 0x60010aae2c00 made no progress with peer 172.30.0.159
[54.91.212.220] [stdout] Nov 25 11:06:41 info   |  [shard 0] stream_session - [Stream #5cfea190-b2cd-11e6-bcc7-000000000007] The session 0x60010aae2c00 made no progress with peer 172.30.0.159
[54.91.212.220] [stdout] Nov 25 11:07:41 info   |  [shard 0] stream_session - [Stream #5cfea190-b2cd-11e6-bcc7-000000000007] The session 0x60010aae2c00 made no progress with peer 172.30.0.159
[54.91.212.220] [stdout] Nov 25 11:08:41 info   |  [shard 0] stream_session - [Stream #5cfea190-b2cd-11e6-bcc7-000000000007] The session 0x60010aae2c00 made no progress with peer 172.30.0.159
[54.91.212.220] [stdout] Nov 25 11:09:41 info   |  [shard 0] stream_session - [Stream #5cfea190-b2cd-11e6-bcc7-000000000007] The session 0x60010aae2c00 made no progress with peer 172.30.0.159
[54.91.212.220] [stdout] Nov 25 11:10:41 info   |  [shard 0] stream_session - [Stream #5cfea190-b2cd-11e6-bcc7-000000000007] The session 0x60010aae2c00 made no progress with peer 172.30.0.159
[54.91.212.220] [stdout] Nov 25 11:11:41 info   |  [shard 0] stream_session - [Stream #5cfea190-b2cd-11e6-bcc7-000000000007] The session 0x60010aae2c00 is idle for 600 seconds, the peer 172.30.0.159 is probably gone, close it
[54.91.212.220] [stdout] Nov 25 11:11:41 warning|  [shard 0] stream_session - [Stream #5cfea190-b2cd-11e6-bcc7-000000000007] Streaming error occurred
[54.91.212.220] [stdout] Nov 25 11:11:41 info   |  [shard 0] stream_session - [Stream #5cfea190-b2cd-11e6-bcc7-000000000007] Session with 172.30.0.159 is complete, state=FAILED

```

That node became unavailable because it ran out of space on disk:
```
[54.162.11.147] [stdout] Nov 25 11:00:31 warning|  [shard 10] storage_service - Shutting down communications due to I/O errors until operator intervention
[54.162.11.147] [stdout] Nov 25 11:00:31 err    |  [shard 10] compaction_manager - compaction failed: storage_io_error (Storage I/O error: 28: No space left on device)
```

**Comment by lmr** [comment] 2016-11-29 12:31
@tgrabiec The prometheus db wasn't downloaded since the test didn't end properly, and I forgot to download it manually, sorry.

**Comment by slivne** [comment] 2016-11-29 12:46
@tgrabiec <https://github.com/tgrabiec> with regards to the first issue -
is that related to out of disk space or something else ?

**Comment by tgrabiec** [comment] 2016-11-29 12:58
The crash happened when Scylla was stopped by chaos monkey:

```
18:30:28 INFO | sdcm.nemesis.ChaosMonkey: Current Target: Node scylla-1-5-ld-chaos-scylla-db-node-fd89d149-1 [54.162.11.147 | 172.30.0.159] (seed: False)
18:30:28 DEBUG| sdcm.nemesis.ChaosMonkey: Start -> CorruptThenRebuild Node scylla-1-5-ld-chaos-scylla-db-node-fd89d149-3 [54.91.212.220 | 172.30.0.160] (seed: False)
18:30:28 INFO | sdcm.nemesis.ChaosMonkey: StopWaitStartService Node scylla-1-5-ld-chaos-scylla-db-node-fd89d149-1 [54.162.11.147 | 172.30.0.159] (seed: False)
18:30:28 DEBUG| Remote [centos@54.162.11.147]: Running 'sudo systemctl stop scylla-server.service'
18:30:28 INFO | [54.162.11.147] Running '/bin/ssh -a -x  -o ControlPath=/var/tmp/ssh-master4pahXH/socket -o StrictHostKeyChecking=no -o UserKnownHostsFile=/var/tmp/tmpWiSIda -o BatchMode=yes
 -o ConnectTimeout=300 -o ServerAliveInterval=300 -l centos -p 22 -i /var/tmp/scylla-1-5-ld-chaos-longevity-test-a3c117c7.pem 54.162.11.147 "sudo systemctl stop scylla-server.service"'
18:30:28 DEBUG| [54.162.11.147] [stdout] Nov 24 18:30:28 info   | Stopping Scylla JMX...
18:30:29 DEBUG| [54.162.11.147] [stdout] Nov 24 18:30:29 notice | scylla-jmx.service: main process exited, code=exited, status=143/n/a
18:30:29 DEBUG| [54.162.11.147] [stdout] Nov 24 18:30:29 info   | Stopped Scylla JMX.
18:30:29 DEBUG| [54.162.11.147] [stdout] Nov 24 18:30:29 notice | Unit scylla-jmx.service entered failed state.
18:30:29 DEBUG| [54.162.11.147] [stdout] Nov 24 18:30:29 warning| scylla-jmx.service failed.
18:30:29 DEBUG| [54.162.11.147] [stdout] Nov 24 18:30:29 info   | Stopping Scylla Server...
18:30:29 DEBUG| [54.162.11.147] [stdout] Nov 24 18:30:29 info   |  [shard 0] compaction_manager - Asked to stop
18:30:29 DEBUG| [54.162.11.147] [stdout] Nov 24 18:30:29 info   |  [shard 4] compaction_manager - Asked to stop
18:30:29 DEBUG| [54.162.11.147] [stdout] Nov 24 18:30:29 info   |  [shard 4] compaction_manager - Stopped
18:30:29 DEBUG| [54.162.11.147] [stdout] Nov 24 18:30:29 info   |  [shard 7] compaction_manager - Asked to stop
18:30:29 DEBUG| [54.162.11.147] [stdout] Nov 24 18:30:29 info   |  [shard 10] compaction_manager - Asked to stop
18:30:29 DEBUG| [54.162.11.147] [stdout] Nov 24 18:30:29 info   |  [shard 7] compaction_manager - Stopped
18:30:29 DEBUG| [54.162.11.147] [stdout] Nov 24 18:30:29 info   |  [shard 6] compaction_manager - Asked to stop
18:30:29 DEBUG| [54.162.11.147] [stdout] Nov 24 18:30:29 info   |  [shard 5] compaction_manager - Asked to stop
18:30:29 DEBUG| [54.162.11.147] [stdout] Nov 24 18:30:29 info   |  [shard 11] compaction_manager - Asked to stop
18:30:29 DEBUG| [54.162.11.147] [stdout] Nov 24 18:30:29 info   |  [shard 8] compaction_manager - Asked to stop
18:30:29 DEBUG| [54.162.11.147] [stdout] Nov 24 18:30:29 info   |  [shard 5] compaction_manager - Stopped
18:30:29 DEBUG| [54.162.11.147] [stdout] Nov 24 18:30:29 info   |  [shard 11] compaction_manager - Stopped
18:30:29 DEBUG| [54.162.11.147] [stdout] Nov 24 18:30:29 info   |  [shard 2] compaction_manager - Asked to stop
18:30:29 DEBUG| [54.162.11.147] [stdout] Nov 24 18:30:29 info   |  [shard 2] compaction_manager - Stopped
18:30:29 DEBUG| [54.162.11.147] [stdout] Nov 24 18:30:29 info   |  [shard 3] compaction_manager - Asked to stop
18:30:29 DEBUG| [54.162.11.147] [stdout] Nov 24 18:30:29 info   |  [shard 13] compaction_manager - Asked to stop
18:30:29 DEBUG| [54.162.11.147] [stdout] Nov 24 18:30:29 info   |  [shard 6] compaction_manager - Stopped
18:30:29 DEBUG| [54.162.11.147] [stdout] Nov 24 18:30:29 info   |  [shard 8] compaction_manager - Stopped
18:30:29 DEBUG| [54.162.11.147] [stdout] Nov 24 18:30:29 info   |  [shard 10] compaction_manager - Stopped
18:30:29 DEBUG| [54.162.11.147] [stdout] Nov 24 18:30:29 info   |  [shard 9] compaction_manager - Asked to stop
18:30:29 DEBUG| [54.162.11.147] [stdout] Nov 24 18:30:29 info   |  [shard 13] compaction_manager - Stopped
18:30:29 DEBUG| [54.162.11.147] [stdout] Nov 24 18:30:29 info   |  [shard 1] compaction_manager - Asked to stop
18:30:29 DEBUG| [54.162.11.147] [stdout] Nov 24 18:30:29 info   |  [shard 12] compaction_manager - Asked to stop
18:30:29 DEBUG| [54.162.11.147] [stdout] Nov 24 18:30:29 info   |  [shard 12] compaction_manager - Stopped
18:30:29 DEBUG| [54.162.11.147] [stdout] Nov 24 18:30:29 info   | scylla: /opt/scylladb/include/boost/intrusive/detail/generic_hook.hpp:47: void boost::intrusive::detail::destructor_impl(Hoo
k&, boost::intrusive::detail::link_dispatch<(boost::intrusive::link_mode_type)1u>) [with Hook = boost::intrusive::generic_hook<boost::intrusive::circular_list_algorithms<boost::intrusive::li
st_node_traits<void*> >, boost::intrusive::member_tag, (boost::intrusive::link_mode_type)1u, (boost::intrusive::base_hook_type)0u>]: Assertion `!hook.is_linked()' failed.
18:30:29 DEBUG| [54.162.11.147] [stdout] Nov 24 18:30:29 info   | Aborting on shard 3.
18:30:29 DEBUG| [54.162.11.147] [stdout] Nov 24 18:30:29 info   | Backtrace:
18:30:29 DEBUG| [54.162.11.147] [stdout] Nov 24 18:30:29 info   | scylla: core/future.hh:335: void future_state<>::set(): Assertion `_u.st == state::future' failed.

```

I think the problem is with stopping concurrently with compaction in general. We saw the same problem in #1874.

**Comment by tgrabiec** [comment] 2016-12-01 15:28
The fix for #1856 was backported to branch-1.5

**Comment by lmr** [comment] 2016-12-09 03:20
@kongove asked for the scylla.yaml file used for this test. Here it comes:

    # Test duration (min). Parameter used to keep instances produced by tests that
    # are supposed to run longer than 24 hours from being killed
    test_duration: 10080
    stress_cmd: cassandra-stress write cl=QUORUM duration=10080m -schema 'replication(factor=3)' -port jmx=6868 -mode cql3 native -rate threads=200 -col 'size=FIXED(1000) n=FIXED(1)' -pop seq=1..1250000000
    # Number of database nodes
    n_db_nodes: 4
    # If you want to use more than 1 loader node, I recommend
    # increasing the size of the DB instance (instance_type_db parameter),
    # since 't2.micro' nodes tend to struggle with a lot of load.
    n_loaders: 2
    # Number of monitor nodes running prometheus
    n_monitor_nodes: 1
    # Nemesis class to use (possible types in sdcm.nemesis). Example: StopStartMonkey
    nemesis_class_name: 'ChaosMonkey'
    # Nemesis sleep interval to use if None provided specifically
    nemesis_interval: 15
    # Prefix for your AWS VMs (handy for telling instances from different
    # users apart). If you leave this empty, the prefix will be your unix username.
    user_prefix: scylla-1-5-ld-chaos
    # Failure/post test behavior
    # Default: Destroy AWS instances and credentials (destroy)
    # Keep AWS instances running and leave credentials alone (keep)
    # Stop AWS instances and leave credentials alone (stop)
    failure_post_behavior: keep
    # Space node threshold before starting nemesis (bytes)
    # The default value is 6GB (6x1024^3 bytes)
    # This value is supposed to reproduce
    # https://github.com/scylladb/scylla/issues/1140
    # Using 10GB as the threshold
    space_node_threshold: 10737418240

    # The new db binary will be uploaded to db instance to replace the one
    # provided by the ami. This is useful to test out a new scylla version
    # without making a new ami.
    # update_db_binary: $path_of_the_new_scylla_binary
    update_db_binary: ''

    backends: !mux
        libvirt: !mux
            cluster_backend: 'libvirt'
            libvirt_uri: 'qemu:///system'
            libvirt_bridge: 'virbr0'
            scylla_repo: 'http://downloads.scylladb.com/rpm/centos/scylla-1.2.repo'
            libvirt_loader_image: '/path/to/your/loader_base_image.qcow2'
            libvirt_loader_image_user: 'centos'
            libvirt_loader_image_password: '123456'
            libvirt_loader_os_type: 'linux'
            libvirt_loader_os_variant: 'centos7.0'
            libvirt_loader_memory: 2048
            libvirt_db_image: '/path/to/your/db_base_image.qcow2'
            libvirt_db_image_user: 'centos'
            libvirt_db_image_password: '123456'
            libvirt_db_os_type: 'linux'
            libvirt_db_os_variant: 'centos7.0'
            libvirt_db_memory: 2048
            libvirt_monitor_image: '/path/to/your/monitor_base_image.qcow2'
            libvirt_monitor_image_user: 'centos'
            libvirt_monitor_image_password: '123456'
            libvirt_monitor_os_type: 'linux'
            libvirt_monitor_os_variant: 'centos7.0'
            libvirt_monitor_memory: 2048
        aws: !mux
            # What is the backend that the suite will use to get machines from.
            cluster_backend: 'aws'
            # From 0.19 on, iotune will require bigger disk, so let's use a big
            # loader instance by default.
            instance_type_loader: 'c4.8xlarge'
            # Size of AWS monitor instance
            instance_type_monitor: t2.small
            us_west_1:
                region_name: 'us-west-1'
                security_group_ids: 'sg-dcd785b9'
                subnet_id: 'subnet-10a04c75'
                ami_id_db_scylla: 'ami-19eca679'
                ami_db_scylla_user: 'centos'
                ami_id_loader: 'ami-19eca679'
                ami_loader_user: 'centos'
                ami_id_db_cassandra: 'ami-3cf7c979'
                ami_db_cassandra_user: 'ubuntu'
                ami_id_monitor: 'ami-19eca679'
                ami_monitor_user: 'centos'
            us_west_2:
                region_name: 'us-west-2'
                security_group_ids: 'sg-81703ae4'
                subnet_id: 'subnet-5207ee37'
                ami_id_db_scylla: 'ami-ec3e9e8c'
                ami_db_scylla_user: 'centos'
                ami_id_loader: 'ami-ec3e9e8c'
                ami_loader_user: 'centos'
                ami_id_db_cassandra: 'ami-1cff962c'
                ami_db_cassandra_user: 'ubuntu'
                ami_id_monitor: 'ami-ec3e9e8c'
                ami_monitor_user: 'centos'
            us_east_1:
                region_name: 'us-east-1'
                security_group_ids: 'sg-c5e1f7a0'
                subnet_id: 'subnet-ec4a72c4'
                ami_id_db_scylla: 'ami-38c2f22f'
                ami_db_scylla_user: 'centos'
                ami_id_loader: 'ami-38c2f22f'
                ami_loader_user: 'centos'
                ami_id_db_cassandra: 'ami-ada2b6c4'
                ami_db_cassandra_user: 'ubuntu'
                ami_id_monitor: 'ami-38c2f22f'
                ami_monitor_user: 'centos'

    databases: !mux
        cassandra:
            db_type: cassandra
            instance_type_db: 'm3.large'
        scylla:
            db_type: scylla
            # Let's use c3.large since we're using iotune
            # and we'll stress the DB nodes more thoroughly
            instance_type_db: 'i2.4xlarge'

**Comment by slivne** [comment] 2017-08-13 13:12
1.7.4 1 TB runs are passing closing this issue

**Closed by slivne** 2017-08-13 13:12 UTC
Labels: bug, high
