### ISSUE TITLE
[java driver] BoundStatementCcmIT.should_set_all_occurrences_of_variable 

### ISSUE THREAD

**Issue by fruch** [scylladb/scylla#10956] opened 2022-07-04 08:02 UTC
Java driver integration test start failing, two weeks ago.
4.13.0.com.datastax.oss.driver.core.cql.BoundStatementCcmIT.should_set_all_occurrences_of_variable

```
Expecting:
  [0]
to contain exactly (and in same order):
  [0, 1, 2]
but could not find the following elements:
  [1, 2]
```

last passing at: `5.1.dev-0.20220615.5129280f4535`
started failing from: `5.1.dev-0.20220620.85263b2d0246`

the test:
```java
  @Test
  public void should_set_all_occurrences_of_variable() {
    CqlSession session = sessionRule.session();
    PreparedStatement ps = session.prepare("INSERT INTO test3 (pk1, pk2, v) VALUES (:i, :i, :i)");

    CqlIdentifier id = CqlIdentifier.fromCql("i");
    ColumnDefinitions variableDefinitions = ps.getVariableDefinitions();
    assertThat(variableDefinitions.allIndicesOf(id)).containsExactly(0, 1, 2);

    should_set_all_occurrences_of_variable(ps.bind().setInt(id, 12));
    should_set_all_occurrences_of_variable(ps.boundStatementBuilder().setInt(id, 12).build());
  }
```

this test introduce in:
https://github.com/datastax/java-driver/pull/1463

**Comment by fruch** [comment] 2022-07-05 08:29
running the test with 4.6.3, release is passing
```bash
mvn -pl integration-tests -Dtest='BoundStatementCcmIT#should_set_all_occurrences_of_variable' test -Dscylla.version=release:4.6.3
```

**Comment by fruch** [comment] 2022-07-05 08:49
5.1.dev.0.20220615.8f690fdd47ba - passing
5.1.dev.0.20220616.670b2562a169 - passing
5.1.dev.0.20220617.670b2562a169 - passing

5.1.dev.0.20220617.85263b2d0246 - failing
5.1.dev.0.20220619.85263b2d0246 - failing

https://github.com/scylladb/scylla/compare/670b2562a169...85263b2d0246

seem like 19a6e69001f26133a7f7a0a13e89935888884e1a is the cause of the breakage.

@psarna @avikivity seems like this improvement breaks/contradict the driver expected behavior in:
https://datastax-oss.atlassian.net/browse/JAVA-2431

we might consider not breaking user behavior for this case and returning multiple values from prepared statement (while still failing for wrong usage of parameters, which was the core of the fix)

**Comment by psarna** [comment] 2022-07-05 09:08
I'm pretty sure it's the other Piotr that should be notified about this: @avelanarius

**Comment by fruch** [comment] 2022-07-05 09:19
> I'm pretty sure it's the other Piotr that should be notified about this: @avelanarius

both, I believe you have introduced the change on server end (scylla)...

**Comment by psarna** [comment] 2022-07-05 09:27
oh I was a mere maintainer enqueuing a patch, but this commit looks related indeed

**Comment by fruch** [comment] 2022-07-05 09:41
> oh I was a mere maintainer enqueuing a patch, but this commit looks related indeed

sorry, I thought it was the other way around. that @avikivity merged your changes. 

> we might consider not breaking user behavior for this case and returning multiple values from prepared statement (while still failing for wrong usage of parameters, which was the core of the fix)

so @avikivity, the question from above is for you.

**Comment by fruch** [comment] 2022-07-12 17:33
@avelanarius what do you think ? (this is a failure from the java-driver 4.x versions)

**Comment by slivne** [comment] 2022-07-17 07:18
@avelanarius please ack  

this is a regression

By the end of the week we need either a fix or we will revert the patch  https://github.com/scylladb/scylla/commit/19a6e69001f26133a7f7a0a13e89935888884e1a -

**Comment by avelanarius** [comment] 2022-07-19 09:51
@avikivity Please note that your patch (19a6e69001f26133a7f7a0a13e89935888884e1a) disallows the following, previously valid, scenario:

1. `CREATE TABLE ks.t(a int, b text, PRIMARY KEY(a, b))`
2. Prepare `INSERT INTO ks.t(a, b) VALUES (:v, :v)`.
3. Add `INT <-> java.lang.String` codec to Java Driver (users can do it).
4. Execute `prepared.bind().setString("v", "123")`. The driver will send two different representations of `:v` - one as an original string, one as an int after the codec. After the 19a6e69001f26133a7f7a0a13e89935888884e1a the driver can't do that, because the prepared statement metadata has only a single "slot" for `:v` value - this is better for efficiency (don't need to send `:v` multiple times), but disallows different representations of `:v`.

If this is not a concern, I can send a patch that has the validation without doing the "deduplication". However, any validation will break the scenario above.

**Comment by fruch** [comment] 2022-07-19 12:57
@avelanarius when you say a patch, you mean to scylla-core ? or to our java-driver fork ?

**Comment by avelanarius** [comment] 2022-07-19 13:04
> patch

I mean patch to scylla-core in all cases.

**Comment by slivne** [comment] 2022-07-21 11:12
@avikivity ping on https://github.com/scylladb/scylla/issues/10956#issuecomment-1188845014

**Comment by avikivity** [comment] 2022-07-21 11:29
Ugh. The Java-driver behavior is workaround for a Cassandra [bug](https://issues.apache.org/jira/browse/CASSANDRA-17693). The workaround doesn't exist in all drivers (IIRC) and will fail if the statement uses different types for bind variables with conflicting types.

Note that the test verifies that the bug exists.

The scenario @avelanarius with conflicting types that can be resolved by adding codecs is too esoteric. It's just a Cassandra bug that triggers cascading problems. When people use a named variable twice, they expect it to be the same variable, not two variables.

I think we should just removes the failed assertion (that asserts a server bug rather than correct driver behavior).

**Comment by slivne** [comment] 2022-07-25 11:17
@fruch did you skip the test ?

I want to close the issue

**Closed as completed** 2022-07-27 07:16 UTC
Labels: area/test, area/cql, status/regression
