### ISSUE TITLE
Inconsistent data with cassandra-stress and cl=ONE

### ISSUE THREAD

**Issue by nyh** [scylladb/scylla#739] opened 2015-12-31 11:10 UTC
It appears that when using cassandra-stress to write 1 million partitions with consistency level ONE but replication factor 2, the data ending up on the two nodes is not identical (at least, this is what repair found). If we write fewer partitions (e.g., 100,000) this problem doesn't happen. Also if cassandra-stress is run with cl=ALL instead of ONE, this problem doesn't happen, and repair reports that the data on both nodes is identical.

I run two scylla nodes on the same machine, with
```
scylla --ring-delay-ms 4000 --collectd 0 --cpuset 0 -m 1G --api-address 127.0.0.1 --rpc-address 127.0.0.1 --listen-address 127.0.0.1 --seed-provider-parameters seeds=127.0.0.1 --datadir `pwd`/tmp/1 --commitlog-directory `pwd`/tmp/1 >/tmp/out1 2>&1 &
scylla --ring-delay-ms 4000 --collectd 0 --cpuset 2 -m 1G --api-address 127.0.0.2 --rpc-address 127.0.0.2 --listen-address 127.0.0.2 --seed-provider-parameters seeds=127.0.0.1 --datadir `pwd`/tmp/2 --commitlog-directory `pwd`/tmp/2 >/tmp/out2 2>&1 &
```

Then run cassandra-stress as
```
cassandra-stress write cl=ONE n=1000000 -schema "replication(strategy=org.apache.cassandra.locator.SimpleStrategy,factor=2)"
```

After running cassandra-stress, I waited for a long time (100 seconds) to let any in-flight updates between the two nodes be received.

This issue might be related to the cl=ONE problems of issue #457, but I don't see any timeouts mentioned in the log, so it's probably something different.

**Comment by gleb-cloudius** [comment] 2015-12-31 11:25
On Thu, Dec 31, 2015 at 03:10:22AM -0800, nyh wrote:
> It appears that when using cassandra-stress to write 1 million partitions with consistency level ONE but replication factor 2, the data ending up on the two nodes is not identical (at least, this is what repair found). If we write fewer partitions (e.g., 100,000) this problem doesn't happen. Also if cassandra-stress is run with cl=ALL instead of ONE, this problem doesn't happen, and repair reports that the data on both nodes is identical.
> 
> I run two scylla nodes on the same machine, with
> ```
> scylla --ring-delay-ms 4000 --collectd 0 --cpuset 0 -m 1G --api-address 127.0.0.1 --rpc-address 127.0.0.1 --listen-address 127.0.0.1 --seed-provider-parameters seeds=127.0.0.1 --datadir `pwd`/tmp/1 --commitlog-directory `pwd`/tmp/1 >/tmp/out1 2>&1 &
> scylla --ring-delay-ms 4000 --collectd 0 --cpuset 2 -m 1G --api-address 127.0.0.2 --rpc-address 127.0.0.2 --listen-address 127.0.0.2 --seed-provider-parameters seeds=127.0.0.1 --datadir `pwd`/tmp/2 --commitlog-directory `pwd`/tmp/2 >/tmp/out2 2>&1 &
> ```
> 
> Then run cassandra-stress as
> ```
> cassandra-stress write cl=ONE n=1000000 -schema "replication(strategy=org.apache.cassandra.locator.SimpleStrategy,factor=2)"
> ```
> 
> After running cassandra-stress, I waited for a long time (100 seconds) to let any in-flight updates between the two nodes be received.
> 
> This issue might be related to the cl=ONE problems of issue #457, but I don't see any timeouts mentioned in the log, so it's probably something different.
> 
CL=ONE is allowed to drop data.  We never drop local writes, so I guess
in your case we drops remote write because it took more then 2 seconds to
write them. We should have started throttle before we reach that point
though. The throttling limit is 10% (100M in your case) of memory or
send queue bigger then 6M. I wonder if running locally makes it so slow
that we cannot pass this much data in 2 seconds? Are you sure --cpuset
actually works for you and two processes run on separate cpus? Are you
using xfs? ext4 may insert sleeps that may cause very slow
communication.

--
			Gleb.

**Comment by nyh** [comment] 2015-12-31 11:36
On Thu, Dec 31, 2015 at 1:25 PM, Gleb Natapov <notifications@github.com>
wrote:

> >
> > This issue might be related to the cl=ONE problems of issue #457, but I
> don't see any timeouts mentioned in the log, so it's probably something
> different.
> >
> CL=ONE is allowed to drop data. We never drop local writes, so I guess
> in your case we drops remote write because it took more then 2 seconds to
> write them.


Wouldn't such timeouts be logged, as in issue #457?

We should have started throttle before we reach that point
> though. The throttling limit is 10% (100M in your case) of memory or
> send queue bigger then 6M. I wonder if running locally makes it so slow
> that we cannot pass this much data in 2 seconds? Are you sure --cpuset
> actually works for you and two processes run on separate cpus?


Yes, I think --cpuset works as expected (before I used it, I got extremely
bad performance):
/home/nyh/scylla-jmx$ taskset -p 1536
pid 1536's current affinity mask: 1
/home/nyh/scylla-jmx$ taskset -p 1537
pid 1537's current affinity mask: 4



> Are you
> using xfs? ext4 may insert sleeps that may cause very slow
> communication.
>

I am certainly *not* using xfs for development and testing.

I'm seeing Scylla taking 60%-100% CPU, so while some of this sleeping might
be related to ext4, it's not something that should have made a huge
difference, I think.

**Comment by gleb-cloudius** [comment] 2015-12-31 12:24
On Thu, Dec 31, 2015 at 03:36:57AM -0800, nyh wrote:
> On Thu, Dec 31, 2015 at 1:25 PM, Gleb Natapov <notifications@github.com>
> wrote:
> 
> > >
> > > This issue might be related to the cl=ONE problems of issue #457, but I
> > don't see any timeouts mentioned in the log, so it's probably something
> > different.
> > >
> > CL=ONE is allowed to drop data. We never drop local writes, so I guess
> > in your case we drops remote write because it took more then 2 seconds to
> > write them.
> 
> 
> Wouldn't such timeouts be logged, as in issue #457?
> 
No, timeouts in #457 are coming from the problem Glauber fixes with
throttling writes, not CL=ONE per se. If disk is fast you (as a user)
should never see timeout for CL=ONE (and native driver) since local
writes should complete in less then 2 seconds and this is all that is
needed to not have a timeout.

Timeouts here are happening after query is completed from user point of
view. If you enable storage_proxy tracing you should see message:

"Wrote hint to satisfy CL.ANY after no replicas acknowledged the write"

Which is incorrect message of course since it has nothing to do with
CL.ANY in this case, but still...

> We should have started throttle before we reach that point
> > though. The throttling limit is 10% (100M in your case) of memory or
> > send queue bigger then 6M. I wonder if running locally makes it so slow
> > that we cannot pass this much data in 2 seconds? Are you sure --cpuset
> > actually works for you and two processes run on separate cpus?
> 
> 
> Yes, I think --cpuset works as expected (before I used it, I got extremely
> bad performance):
> /home/nyh/scylla-jmx$ taskset -p 1536
> pid 1536's current affinity mask: 1
> /home/nyh/scylla-jmx$ taskset -p 1537
> pid 1537's current affinity mask: 4
> 
> 
> 
> > Are you
> > using xfs? ext4 may insert sleeps that may cause very slow
> > communication.
> >
> 
> I am certainly *not* using xfs for development and testing.
> 
> I'm seeing Scylla taking 60%-100% CPU, so while some of this sleeping might
> be related to ext4, it's not something that should have made a huge
> difference, I think.
> 
If it sleeps between sending each message it makes a huge difference.

--
			Gleb.

**Comment by nyh** [comment] 2015-12-31 13:10
On Thu, Dec 31, 2015 at 2:24 PM, Gleb Natapov <notifications@github.com>
wrote:

> On Thu, Dec 31, 2015 at 03:36:57AM -0800, nyh wrote:
> > On Thu, Dec 31, 2015 at 1:25 PM, Gleb Natapov <notifications@github.com>
> > wrote:
>
> Timeouts here are happening after query is completed from user point of
> view. If you enable storage_proxy tracing you should see message:
>
> "Wrote hint to satisfy CL.ANY after no replicas acknowledged the write"
>

I'll try checking this.


> Which is incorrect message of course since it has nothing to do with
> CL.ANY in this case, but still...
>
> >
> > I am certainly *not* using xfs for development and testing.
> >
> > I'm seeing Scylla taking 60%-100% CPU, so while some of this sleeping
> might
> > be related to ext4, it's not something that should have made a huge
> > difference, I think.
> >
> If it sleeps between sending each message it makes a huge difference.


I'm getting about 16,000 requests per second, and it's perfectly fine for
me (this wasn't supposed to be a performance test, and I wasn't looking for
higher performance). I don't understand what you're saying about "sleeping
between sending each message" - if we have 1000 outstanding messages not
yet sent (only this can explain a timeout of 2 seconds), why aren't all
these 1000 messages being sent once the sleep is over? Especially that I'm
seeing > 60% CPU use for each scylla process, so definitely scylla is not,
as a whole, starved of run time.

**Comment by gleb-cloudius** [comment] 2015-12-31 13:16
On Thu, Dec 31, 2015 at 05:10:54AM -0800, nyh wrote:
> On Thu, Dec 31, 2015 at 2:24 PM, Gleb Natapov <notifications@github.com>
> wrote:
> 
> > On Thu, Dec 31, 2015 at 03:36:57AM -0800, nyh wrote:
> > > On Thu, Dec 31, 2015 at 1:25 PM, Gleb Natapov <notifications@github.com>
> > > wrote:
> >
> > Timeouts here are happening after query is completed from user point of
> > view. If you enable storage_proxy tracing you should see message:
> >
> > "Wrote hint to satisfy CL.ANY after no replicas acknowledged the write"
> >
> 
> I'll try checking this.
> 
> 
> > Which is incorrect message of course since it has nothing to do with
> > CL.ANY in this case, but still...
> >
> > >
> > > I am certainly *not* using xfs for development and testing.
> > >
> > > I'm seeing Scylla taking 60%-100% CPU, so while some of this sleeping
> > might
> > > be related to ext4, it's not something that should have made a huge
> > > difference, I think.
> > >
> > If it sleeps between sending each message it makes a huge difference.
> 
> 
> I'm getting about 16,000 requests per second, and it's perfectly fine for
> me (this wasn't supposed to be a performance test, and I wasn't looking for
> higher performance). I don't understand what you're saying about "sleeping
> between sending each message" - if we have 1000 outstanding messages not
> yet sent (only this can explain a timeout of 2 seconds), why aren't all
> these 1000 messages being sent once the sleep is over? Especially that I'm
> seeing > 60% CPU use for each scylla process, so definitely scylla is not,
> as a whole, starved of run time.
They are send up until there is buffer space in output_buffer (2k IIRC)
and/or kernel. If you insert sleep after each burst you may not send
fast enough. About cpu time usage if you do not see 100% all of the time
it means you are sleeping on IO instead of sending things. To confirm
that sleep is due to IO and not lack of work to do you may run in poll
mode. If you still see lower then 100% utilization then you are sleeping
on IO.

--
			Gleb.

**Comment by nyh** [comment] 2016-01-04 15:31
@gleb-cloudius, I enabled the "Wrote hint to satisfy CL.ANY after no replicas acknowledged the write" logging in storage_proxy.cc, as you suggested. 

Indeed, when I use cassandra-stress with 400,000 partitions, I get around 50,000 of these errors on each of the two nodes, meaning that only around 300,000 partitions reached both nodes, and about 50,000 reached only one of the two (cassandra stress aproached both of these nodes with its writes). Repair confirms there are huge differences between the two nodes' data.

When I use cassandra-stress with 100,000 partitions, I get don't get any of these errors, and repair confirms the data on both nodes is identical.

I don't know what to do next... I think we need to:

1. Determine whether we need to log as a "WARNING" these failures. How about a rate-limited logging option, which counts some events and prints their count not more than once a second?

2. Determine why in my use case the inter-node messages are lost or slow. Does this also happen in more "production" use cases, with two different actual nodes? If not, what in my setup is causing this problem? The lack XFS (I still don't understand how)? Something else?

3. Even if there is a problem in my setup, shouldn't we throttle the new requests if we have too much replication backlog. I don't know, however, what to do in case of the other nodes actually failing - we don't want to throttle requests in that case.

**Comment by avikivity** [comment] 2016-01-04 15:42
With CL=ONE or CL=ANY Scylla is responding to the write from memory, and doing replication in the background.  But it should still get there eventually, even if the backlog is large (we can have a long queue on rpc, but we shouldn't drop messages).

We do throttle requests, but only after a very generous backlog.

**Comment by dorlaor** [comment] 2016-01-04 15:47
On Mon, Jan 4, 2016 at 5:42 PM, Avi Kivity <notifications@github.com> wrote:

> With CL=ONE or CL=ANY Scylla is responding to the write from memory, and
> doing replication in the background. But it should still get there
> eventually, even if the backlog is large (we can have a long queue on rpc,
> but we shouldn't drop messages).
>
> We do throttle requests, but only after a very generous backlog.
>

What about to add a throttle criteria on top of throttling RAM. We can
throttle
(by moving to the foreground) when the inter-node queue grows above certain
limit.
For instance, we take a timestamp of a message once we queue it for sending.
When the message is about to be transmitted on the wire we check if it spent
more than 100ms in the queue (ultra long time). If it did, we move CQL
request
to the foreground.

**Comment by nyh** [comment] 2016-01-04 15:58
On Mon, Jan 4, 2016 at 5:47 PM, Dor Laor <notifications@github.com> wrote:

> On Mon, Jan 4, 2016 at 5:42 PM, Avi Kivity <notifications@github.com>
> wrote:
>
> > With CL=ONE or CL=ANY Scylla is responding to the write from memory, and
> > doing replication in the background. But it should still get there
> > eventually, even if the backlog is large (we can have a long queue on
> rpc,
> > but we shouldn't drop messages).
> >
> > We do throttle requests, but only after a very generous backlog.
> >
>
> What about to add a throttle criteria on top of throttling RAM.


Another data point: if I change my scylla instances to get 2 GB of RAM each
(as I mentioned on the original issue, I gave each 1 GB), then the problem
disappears for 400,000 partitions.

So apparently, the problem is created (or exacerbated) by not having enough
memory to keep the backlog of replication messages. I'm not familiar enough
with the code, however, to understand how the amount of available RAM
influences the RPC backlog or timeouts, or something specific to the
replication of mutations.



> We can
> throttle
> (by moving to the foreground) when the inter-node queue grows above certain
> limit.
> For instance, we take a timestamp of a message once we queue it for
> sending.
> When the message is about to be transmitted on the wire we check if it
> spent
> more than 100ms in the queue (ultra long time). If it did, we move CQL
> request
> to the foreground.
>

What will we do when a node really goes down? Do we start to really slow
down the incoming request? I don't think we'll want to. I think the real
solution in that node-down case is to drop the messages (and write to the
hints file if we have one) - just like (apparently) the code we have now.
But the code we have now doesn't suite well the case that the remote node
is *not* down, it just can't process these messages quickly enough.

**Comment by dorlaor** [comment] 2016-01-04 16:09
On Mon, Jan 4, 2016 at 5:58 PM, nyh <notifications@github.com> wrote:

> On Mon, Jan 4, 2016 at 5:47 PM, Dor Laor <notifications@github.com> wrote:
>
> > On Mon, Jan 4, 2016 at 5:42 PM, Avi Kivity <notifications@github.com>
> > wrote:
> >
> > > With CL=ONE or CL=ANY Scylla is responding to the write from memory,
> and
> > > doing replication in the background. But it should still get there
> > > eventually, even if the backlog is large (we can have a long queue on
> > rpc,
> > > but we shouldn't drop messages).
> > >
> > > We do throttle requests, but only after a very generous backlog.
> > >
> >
> > What about to add a throttle criteria on top of throttling RAM.
>
>
> Another data point: if I change my scylla instances to get 2 GB of RAM each
> (as I mentioned on the original issue, I gave each 1 GB), then the problem
> disappears for 400,000 partitions.
>
> So apparently, the problem is created (or exacerbated) by not having enough
> memory to keep the backlog of replication messages. I'm not familiar enough
> with the code, however, to understand how the amount of available RAM
> influences the RPC backlog or timeouts, or something specific to the
> replication of mutations.


Look for Gleb's criteria  from commit
fe4bc741f47f181c241001aeb4764606518dd447 :

bool storage_proxy::need_throttle_writes() const {
    return _stats.background_write_bytes > memory::stats().total_memory() /
10 || _stats.queued_write_bytes > 6*1024*1024;
}

He does take into account the queue size and admit the numbers he picked
are bogus.
@nyh, can you throttle harder and re-test?

**Comment by tgrabiec** [comment] 2016-01-04 16:23
2016-01-04 16:58 GMT+01:00 nyh <notifications@github.com>:

> On Mon, Jan 4, 2016 at 5:47 PM, Dor Laor <notifications@github.com> wrote:
>
> > On Mon, Jan 4, 2016 at 5:42 PM, Avi Kivity <notifications@github.com>
> > wrote:
> >
> > > With CL=ONE or CL=ANY Scylla is responding to the write from memory,
> and
> > > doing replication in the background. But it should still get there
> > > eventually, even if the backlog is large (we can have a long queue on
> > rpc,
> > > but we shouldn't drop messages).
> > >
> > > We do throttle requests, but only after a very generous backlog.
> > >
> >
> > What about to add a throttle criteria on top of throttling RAM.
>
>
> Another data point: if I change my scylla instances to get 2 GB of RAM each
> (as I mentioned on the original issue, I gave each 1 GB), then the problem
> disappears for 400,000 partitions.
>
> So apparently, the problem is created (or exacerbated) by not having enough
> memory to keep the backlog of replication messages. I'm not familiar enough
> with the code, however, to understand how the amount of available RAM
> influences the RPC backlog or timeouts, or something specific to the
> replication of mutations.
>
>
>
> > We can
> > throttle
> > (by moving to the foreground) when the inter-node queue grows above
> certain
> > limit.
> > For instance, we take a timestamp of a message once we queue it for
> > sending.
> > When the message is about to be transmitted on the wire we check if it
> > spent
> > more than 100ms in the queue (ultra long time). If it did, we move CQL
> > request
> > to the foreground.
> >
>
> What will we do when a node really goes down? Do we start to really slow
> down the incoming request? I don't think we'll want to. I think the real
> solution in that node-down case is to drop the messages (and write to the
> hints file if we have one) - just like (apparently) the code we have now.
> But the code we have now doesn't suite well the case that the remote node
> is *not* down, it just can't process these messages quickly enough.


I think we should also hint replication timeout. In C* submitHint() seems
to be called from a timeout callback set on ExpringMap in
MessagingService.java

**Comment by nyh** [comment] 2016-01-04 16:24
On Mon, Jan 4, 2016 at 6:09 PM, Dor Laor <notifications@github.com> wrote:

>
>
> Look for Gleb's criteria from commit
> fe4bc741f47f181c241001aeb4764606518dd447 :
>
> bool storage_proxy::need_throttle_writes() const {
> return _stats.background_write_bytes > memory::stats().total_memory() /
> 10 || _stats.queued_write_bytes > 6*1024*1024;
> }
>

He does take into account the queue size and admit the numbers he picked
> are bogus.
>

Thanks for the pointer, I wasn't familiar with this code.
I am still not sure, though, why this could cause mutations to be "lost".
Once we start "throttling" as in that commit, doesn't this just mean we
start slowing the client down? Why would this cause us to abandon this
mutation?



> @nyh, can you throttle harder and re-test?
>

Sure, I can play with these parameters and see what happens. Although I'll
be happy if someone who actually is familiar with this code (Gleb? ) will
comment on what is supposed to happen in this case.

**Comment by avikivity** [comment] 2016-01-04 16:46
> I am still not sure, though, why this could cause mutations to be "lost".
> Once we start "throttling" as in that commit, doesn't this just mean we
> start slowing the client down? Why would this cause us to abandon this
> mutation?

It shouldn't.  The intent was that we do NOT lose mutations, unless the failure detector tells us to.

**Comment by dorlaor** [comment] 2016-01-05 15:54
On Mon, Jan 4, 2016 at 6:46 PM, Avi Kivity <notifications@github.com> wrote:

> I am still not sure, though, why this could cause mutations to be "lost".
> Once we start "throttling" as in that commit, doesn't this just mean we
> start slowing the client down? Why would this cause us to abandon this
> mutation?
>
> It shouldn't. The intent was that we do NOT lose mutations, unless the
> failure detector tells us to.
>

@nyh, did you play with the values or measured how many throttles happen?
The fact that once you enlarge the memory you no issues indicates that
something
drops messages or causes a timeout. Is the send queue size depends on the
amount of RAM each shard has? What happens when the queue is full?

**Comment by nyh** [comment] 2016-01-06 14:18
@dor, changing the constants in `storage_proxy::need_throttle_writes()` does not solve the problem (which increasing the RAM size did) which suggests this issue is probably not related to throttling.

Moreover, I added a printout in the place in storage_proxy.cc which enables throttling, and the first time it happens is several seconds after the first timeouts occurred. Which explains why throttling doesn't solve this problem.

Your suggestion that something is dropping packets makes sense, but I've yet to find why this is happening. I'm looking...

**Comment by gleb-cloudius** [comment] 2016-01-11 05:32
On Mon, Jan 04, 2016 at 07:59:01AM -0800, nyh wrote:
> On Mon, Jan 4, 2016 at 5:47 PM, Dor Laor <notifications@github.com> wrote:
> 
> > On Mon, Jan 4, 2016 at 5:42 PM, Avi Kivity <notifications@github.com>
> > wrote:
> >
> > > With CL=ONE or CL=ANY Scylla is responding to the write from memory, and
> > > doing replication in the background. But it should still get there
> > > eventually, even if the backlog is large (we can have a long queue on
> > rpc,
> > > but we shouldn't drop messages).
> > >
> > > We do throttle requests, but only after a very generous backlog.
> > >
> >
> > What about to add a throttle criteria on top of throttling RAM.
> 
> 
> Another data point: if I change my scylla instances to get 2 GB of RAM each
> (as I mentioned on the original issue, I gave each 1 GB), then the problem
> disappears for 400,000 partitions.
> 
> So apparently, the problem is created (or exacerbated) by not having enough
> memory to keep the backlog of replication messages. I'm not familiar enough
> with the code, however, to understand how the amount of available RAM
> influences the RPC backlog or timeouts, or something specific to the
> replication of mutations.
> 
> 
More memory means less writes by commit log means less sleeps in ext4
code means faster inter node communication. I do not think we should
spend time debugging your broken setup, so unless you can reproduce it
with xfs we should not spend any time on that.

--
			Gleb.

**Comment by gleb-cloudius** [comment] 2016-01-11 07:29
On Mon, Jan 04, 2016 at 08:24:27AM -0800, nyh wrote:
> > @nyh, can you throttle harder and re-test?
> >
> 
> Sure, I can play with these parameters and see what happens. Although I'll
> be happy if someone who actually is familiar with this code (Gleb? ) will
> comment on what is supposed to happen in this case.
> 
I already did, extensively, you just ignore my explanations :( Does your
processes 100% busy when you enable poll mode? If not there is nothing
to see here.

--
			Gleb.

**Comment by gleb-cloudius** [comment] 2016-01-11 07:31
On Mon, Jan 04, 2016 at 08:46:40AM -0800, Avi Kivity wrote:
> > I am still not sure, though, why this could cause mutations to be "lost".
> > Once we start "throttling" as in that commit, doesn't this just mean we
> > start slowing the client down? Why would this cause us to abandon this
> > mutation?
> 
> It shouldn't.  The intent was that we do NOT lose mutations, unless the failure detector tells us to.
> 
It should if sending times out.

--
			Gleb.

**Comment by slivne** [comment] 2016-01-18 07:15
@avikivity are your patches for rpc resource limiting fixing this as well ? if not who should handle this ?

**Comment by gleb-cloudius** [comment] 2016-01-18 08:22
On Sun, Jan 17, 2016 at 11:15:41PM -0800, slivne wrote:
> @avikivity are your patches for rpc resource limiting fixing this as well ? if not who should handle this ?
> 
There is nothing to handle here.

--
			Gleb.

**Closed** 2016-02-14 22:02 UTC
Labels: bug, showstopper
