### ISSUE TITLE
scylla-server.slice: Unknown lvalue ' in section 'Slice'

### ISSUE THREAD

**Issue by bentsi** [scylladb/scylla#7361] opened 2020-10-08 10:07 UTC
*Installation details*
Scylla version (or git commit hash): 666.development-0.20201007.f30e86395
Cluster size: 1
OS (RHEL/CentOS/Ubuntu/AWS AMI): ami-0b5be1c31eef174db [us-east-1]
OS verison: `Linux artifacts-ami-jenkins-db-node-88d47ae8-1 5.4.58-32.125.amzn2.x86_64 #1 SMP Thu Sep 3 19:06:32 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`

When using latest Scylla AMI journalctl has the following messages.:

```
Oct 07 18:58:23 ip-172-30-0-118.ec2.internal systemd[1]: Reloading.
Oct 07 18:58:23 ip-172-30-0-118.ec2.internal systemd[1]: [/usr/lib/systemd/system/scylla-server.slice:7] Unknown lvalue 'IOAccounting' in section 'Slice'
Oct 07 18:58:23 ip-172-30-0-118.ec2.internal systemd[1]: [/usr/lib/systemd/system/scylla-server.slice:14] Unknown lvalue 'IOWeight' in section 'Slice'
Oct 07 18:58:23 ip-172-30-0-118.ec2.internal systemd[1]: [/usr/lib/systemd/system/scylla-server.slice:16] Unknown lvalue 'MemorySwapMax' in section 'Slice'
Oct 07 18:58:23 ip-172-30-0-118.ec2.internal systemd[1]: [/usr/lib/systemd/system/scylla-server.slice:18] Unknown lvalue 'CPUWeight' in section 'Slice'
Oct 07 18:58:23 ip-172-30-0-118.ec2.internal systemd[1]: [/usr/lib/systemd/system/scylla-helper.slice:7] Unknown lvalue 'IOAccounting' in section 'Slice'
Oct 07 18:58:23 ip-172-30-0-118.ec2.internal systemd[1]: [/usr/lib/systemd/system/scylla-helper.slice:10] Unknown lvalue 'CPUWeight' in section 'Slice'
Oct 07 18:58:23 ip-172-30-0-118.ec2.internal systemd[1]: [/usr/lib/systemd/system/scylla-helper.slice:11] Unknown lvalue 'IOWeight' in section 'Slice'
Oct 07 18:58:23 ip-172-30-0-118.ec2.internal systemd[1]: [/usr/lib/systemd/system/scylla-helper.slice:14] Unknown lvalue 'MemoryHigh' in section 'Slice'
Oct 07 18:58:23 ip-172-30-0-118.ec2.internal systemd[1]: [/usr/lib/systemd/system/scylla-helper.slice:17] Unknown lvalue 'MemoryMax' in section 'Slice'
Oct 07 18:58:23 ip-172-30-0-118.ec2.internal systemd[1]: [/usr/lib/systemd/system/scylla-helper.slice:22] Memory limit '5%' invalid. Ignoring.
Oct 07 18:58:23 ip-172-30-0-118.ec2.internal systemd[1]: [/etc/systemd/system/scylla-helper.slice.d/memory.conf:2] Unknown lvalue 'MemoryHigh' in section 'Slice'
Oct 07 18:58:23 ip-172-30-0-118.ec2.internal systemd[1]: [/etc/systemd/system/scylla-helper.slice.d/memory.conf:3] Unknown lvalue 'MemoryMax' in section 'Slice'
Oct 07 18:58:23 ip-172-30-0-118.ec2.internal systemd[1]: [/usr/lib/systemd/system/scylla-server.slice:7] Unknown lvalue 'IOAccounting' in section 'Slice'
Oct 07 18:58:23 ip-172-30-0-118.ec2.internal systemd[1]: [/usr/lib/systemd/system/scylla-server.slice:14] Unknown lvalue 'IOWeight' in section 'Slice'
Oct 07 18:58:23 ip-172-30-0-118.ec2.internal systemd[1]: [/usr/lib/systemd/system/scylla-server.slice:16] Unknown lvalue 'MemorySwapMax' in section 'Slice'
Oct 07 18:58:23 ip-172-30-0-118.ec2.internal systemd[1]: [/usr/lib/systemd/system/scylla-server.slice:18] Unknown lvalue 'CPUWeight' in section 'Slice'
Oct 07 18:58:23 ip-172-30-0-118.ec2.internal systemd[1]: [/usr/lib/systemd/system/scylla-helper.slice:7] Unknown lvalue 'IOAccounting' in section 'Slice'
Oct 07 18:58:23 ip-172-30-0-118.ec2.internal systemd[1]: [/usr/lib/systemd/system/scylla-helper.slice:10] Unknown lvalue 'CPUWeight' in section 'Slice'
Oct 07 18:58:23 ip-172-30-0-118.ec2.internal systemd[1]: [/usr/lib/systemd/system/scylla-helper.slice:11] Unknown lvalue 'IOWeight' in section 'Slice'
Oct 07 18:58:23 ip-172-30-0-118.ec2.internal systemd[1]: [/usr/lib/systemd/system/scylla-helper.slice:14] Unknown lvalue 'MemoryHigh' in section 'Slice'
Oct 07 18:58:23 ip-172-30-0-118.ec2.internal systemd[1]: [/usr/lib/systemd/system/scylla-helper.slice:17] Unknown lvalue 'MemoryMax' in section 'Slice'
Oct 07 18:58:23 ip-172-30-0-118.ec2.internal systemd[1]: [/usr/lib/systemd/system/scylla-helper.slice:22] Memory limit '5%' invalid. Ignoring.
Oct 07 18:58:23 ip-172-30-0-118.ec2.internal systemd[1]: [/etc/systemd/system/scylla-helper.slice.d/memory.conf:2] Unknown lvalue 'MemoryHigh' in section 'Slice'
Oct 07 18:58:23 ip-172-30-0-118.ec2.internal systemd[1]: [/etc/systemd/system/scylla-helper.slice.d/memory.conf:3] Unknown lvalue 'MemoryMax' in section 'Slice'
Oct 07 18:58:23 ip-172-30-0-118.ec2.internal systemd[1]: Reloading.
Oct 07 18:58:23 ip-172-30-0-118.ec2.internal systemd[1]: [/usr/lib/systemd/system/scylla-server.slice:7] Unknown lvalue 'IOAccounting' in section 'Slice'
Oct 07 18:58:23 ip-172-30-0-118.ec2.internal systemd[1]: [/usr/lib/systemd/system/scylla-server.slice:14] Unknown lvalue 'IOWeight' in section 'Slice'
Oct 07 18:58:23 ip-172-30-0-118.ec2.internal systemd[1]: [/usr/lib/systemd/system/scylla-server.slice:16] Unknown lvalue 'MemorySwapMax' in section 'Slice'
Oct 07 18:58:23 ip-172-30-0-118.ec2.internal systemd[1]: [/usr/lib/systemd/system/scylla-server.slice:18] Unknown lvalue 'CPUWeight' in section 'Slice'
Oct 07 18:58:24 ip-172-30-0-118.ec2.internal systemd[1]: [/usr/lib/systemd/system/scylla-helper.slice:7] Unknown lvalue 'IOAccounting' in section 'Slice'
Oct 07 18:58:24 ip-172-30-0-118.ec2.internal systemd[1]: [/usr/lib/systemd/system/scylla-helper.slice:10] Unknown lvalue 'CPUWeight' in section 'Slice'
Oct 07 18:58:24 ip-172-30-0-118.ec2.internal systemd[1]: [/usr/lib/systemd/system/scylla-helper.slice:11] Unknown lvalue 'IOWeight' in section 'Slice'
Oct 07 18:58:24 ip-172-30-0-118.ec2.internal systemd[1]: [/usr/lib/systemd/system/scylla-helper.slice:14] Unknown lvalue 'MemoryHigh' in section 'Slice'
Oct 07 18:58:24 ip-172-30-0-118.ec2.internal systemd[1]: [/usr/lib/systemd/system/scylla-helper.slice:17] Unknown lvalue 'MemoryMax' in section 'Slice'
Oct 07 18:58:24 ip-172-30-0-118.ec2.internal systemd[1]: [/usr/lib/systemd/system/scylla-helper.slice:22] Memory limit '5%' invalid. Ignoring.
Oct 07 18:58:24 ip-172-30-0-118.ec2.internal systemd[1]: [/etc/systemd/system/scylla-helper.slice.d/memory.conf:2] Unknown lvalue 'MemoryHigh' in section 'Slice'
Oct 07 18:58:24 ip-172-30-0-118.ec2.internal systemd[1]: [/etc/systemd/system/scylla-helper.slice.d/memory.conf:3] Unknown lvalue 'MemoryMax' in section 'Slice'
```

**Comment by syuu1228** [comment] 2020-10-12 18:36
Seems like duplicate of #6783

**Comment by slivne** [comment] 2020-10-13 20:12
@syuu1228 well the fix for #6783 seems to be in the version tested -  unless I am missing something

**Comment by syuu1228** [comment] 2020-11-09 11:07
@slivne Commented on #6783  https://github.com/scylladb/scylla/issues/6783#issuecomment-723943176

**Comment by slivne** [comment] 2021-01-19 21:15
closing this issue - as the decision is to keep the error and make the service definitions the same across versions - the issue will stop appearing over time as newer systemd versions are used

**Closed by slivne** 2021-01-19 21:15 UTC
Labels: bug
