### ISSUE TITLE
none of the nodetool commands working when upgraded from version 3.1 to 3.2

### ISSUE THREAD

**Issue by gaurarpit12** [scylladb/scylla#7942] opened 2021-01-21 06:21 UTC
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash): 3.2
Cluster size: 5 nodes
OS (RHEL/CentOS/Ubuntu/AWS AMI): CentOS 7.6

Recently upgraded one node from version `3.1` to version `3.2` and found that node of the nodetool commands is working.
The error that is being shown is: `nodetool: Failed to connect to '127.0.0.1:7199' - ConnectException: 'Connection refused (Connection refused)'.`

**Comment by gaurarpit12** [comment] 2021-01-21 06:23
Some examples showing failure of the nodetool commands are:
`[agaur@eye0708 cassandra]$ nodetool describecluster
nodetool: Failed to connect to '127.0.0.1:7199' - ConnectException: 'Connection refused (Connection refused)'.
[agaur@eye0708 cassandra]$ nodetool info
nodetool: Failed to connect to '127.0.0.1:7199' - ConnectException: 'Connection refused (Connection refused)'.
[agaur@eye0708 cassandra]$ nodetool status
nodetool: Failed to connect to '127.0.0.1:7199' - ConnectException: 'Connection refused (Connection refused)'.`

**Comment by avikivity** [comment] 2021-01-21 08:08
It looks like the scylla process is down. Check with `systemctl status scylla-server` and look at the system logs.

**Comment by amnonh** [comment] 2021-01-21 08:17
another option, is that the scylla-jmx is down, maybe during the upgrade you took it down and didn't took it up again?

**Comment by gaurarpit12** [comment] 2021-01-21 08:21
The issue is w.r.t. `scylla-jmx`. During upgrade it went down and now it's not starting. The problem can be related to this issue: https://github.com/scylladb/scylla-jmx/issues/90

**Comment by gaurarpit12** [comment] 2021-01-21 08:22
The exact error log is:
`Jan 21 08:16:02 eye0708 polkitd[12631]: Unregistered Authentication Agent for unix-process:28326:1050948 (system bus name :1.112, object path /org/freedesktop/PolicyKit1/AuthenticationAgent
Jan 21 08:16:02 eye0708 sudo[28324]: pam_unix(sudo:session): session closed for user root
Jan 21 08:16:02 eye0708 scylla-jmx[28332]: Error: Unable to access jarfile /usr/lib/scylla/jmx/scylla-jmx-1.0.jar
Jan 21 08:16:02 eye0708 systemd[1]: scylla-jmx.service: main process exited, code=exited, status=1/FAILURE
Jan 21 08:16:02 eye0708 systemd[1]: Unit scylla-jmx.service entered failed state.
Jan 21 08:16:02 eye0708 systemd[1]: scylla-jmx.service failed.`

**Comment by avikivity** [comment] 2021-01-21 08:25
Is that file present? What does `rpm -q --verify scylla-jmx` show?

**Comment by gaurarpit12** [comment] 2021-01-21 08:26
`[agaur@eye0708 cassandra]$ rpm -q --verify scylla-jmx
..5....T.  c /etc/sysconfig/scylla-jmx`

**Comment by gaurarpit12** [comment] 2021-01-21 09:33
@avikivity , My upgrade has stuck in between because of this. How to move forward?
-cc @slivne

**Comment by gaurarpit12** [comment] 2021-01-21 09:46
As a temporary fix, I copied the required jar at the path using the command `sudo cp /opt/scylladb/jmx/scylla-jmx-1.0.jar /usr/lib/scylla/jmx/`. Able to get the desired result now. All the `nodetool` commands are running.

**Comment by gaurarpit12** [comment] 2021-01-21 10:00
One more step followed was creation of a symlink `/usr/lib/scylla/jmx/symlinks/scylla-jmx` to `/usr/bin/java` .
This step and the one described in https://github.com/scylladb/scylla/issues/7942#issuecomment-764512872 are to be performed after the upgrade

**Comment by avikivity** [comment] 2021-01-21 11:22
I guess we were missing a `systemctl daemon-reload` and systemd remembered the old .service file.

**Comment by avikivity** [comment] 2021-01-21 11:23
Closing as there is a workaround and the issue is against an obsolete release.

**Closed by avikivity** 2021-01-21 11:23 UTC
