### ISSUE TITLE
node failed to join cluster

### ISSUE THREAD

**Issue by larisau** [scylladb/scylla#2680] opened 2017-08-08 09:25 UTC
*Installation details*
Scylla version (or git commit hash): 1.7.4-0.20170726.ff643e3 
Cluster size: 126 nodes
OS (RHEL/CentOS/Ubuntu/AWS AMI): AWS AMI

Node failed to join cluster and stuck in UP-JOINING status.
Scylla restart solved the problem.

[journalctl_log.txt](https://github.com/scylladb/scylla/files/1207487/journalctl_log.txt)

**Comment by slivne** [comment] 2017-08-08 11:44
@larisau if we stumble on this by luck again - lets not restart the node and try to underatdn why its happening

I still hope that @asias can get something out of the log.

**Comment by asias** [comment] 2017-08-08 11:54
She already pulled the log out. Streaming failed.

**Comment by slivne** [comment] 2017-09-05 12:07
@asias - so do we have a fix for this ? was it a bug in the test ?

**Comment by asias** [comment] 2017-09-06 07:41
No, it is not a bug in the test. The root cause is not known yet.  It can be a stall somewhere prevented the streaming making progress which makes the streaming fail. 


1) block detector
blocked-reactor-notify-ms

2) large allocation detector
```
   memory: add detector for large allocations

    Since large allocations can fail or cause cache eviction in the face
    of memory fragmentation, applications should try to limit allocation sizes.
    This patch adds a detector to assist application developers in finding
    call sites of large allocations.

    A facility is provided to disable it temporarily when a large allocation
    failure can be tolerated.

    Message-Id: <20170819135006.24993-1-avi@scylladb.com>
```

would help. 

I recommend move to 2.0 and retest. 

The following

```
commit f38e4ff3f905d247d2e0bac11590d103db7f1819
Author: Avi Kivity <avi@scylladb.com>
Date:   Wed Aug 2 18:31:07 2017 +0300

    database: prevent streaming reads from blocking normal reads

    Streaming reads and normal reads share a semaphore, so if a bunch of
    streaming reads use all available slots, no normal reads can proceed.

    Fix by assigning streaming reads their own semaphore; they will compete
    with normal reads once issued, and the I/O scheduler will determine the
    winner.

    Fixes #2663.
    Message-Id: <20170802153107.939-1-avi@scylladb.com>

commit 911536960acd57d4be4561ff99853b74ce9172de
Author: Avi Kivity <avi@scylladb.com>
Date:   Wed Aug 2 17:34:48 2017 +0300

    database: remove streaming read queue length limit

    If we fail a streaming read due queue overload, we will fail the entire repair.
    Remove the limit for streaming, and trust the caller (repair) to have bounded
    concurrency.

    Fixes #2659.
    Message-Id: <20170802143448.28311-1-avi@scylladb.com>
```
two patches are fixes in this area.

**Comment by asias** [comment] 2017-09-06 07:42
@larisau Is tls enabled?

**Comment by slivne** [comment] 2017-09-07 07:40
@larisau - what is the background workload in parallel to trying to add nodes
- a mix of read / write
- only write
- none

if its only write/none - then f38e4ff3f905d247d2e0bac11590d103db7f1819 is  probably not related to this.

what could help is if we had metrics - we could check the io-queue metrics of the sender side - it will help to understand 911536960acd57d4be4561ff99853b74ce9172de is related (I doubt that as well).

if we do an additional run on 2.0 lets see if this reoccurs.

**Comment by larisau** [comment] 2017-09-07 09:48
it's write only

**Comment by slivne** [comment] 2018-01-02 08:19
@larisau - we had a cluster with 200 nodes running - can we close this / did we stumble on this with the 200 node cluster ?

**Comment by larisau** [comment] 2018-01-02 08:37
didn't see this in the 200-node cluster run, so we can close it

**Closed** 2018-01-02 08:39 UTC
Labels: bug
