### ISSUE TITLE
Scylla's DESCRIBE output is inconsistent with the CREATE TABLE command that was used.

### ISSUE THREAD

**Issue by haarcuba** [scylladb/scylla#1683] opened 2016-09-21 14:00 UTC
Scylla version: 666.development-20160727.17b45fa
Cluster size: 1
OS: Fedora 24

This bug was discovered using the [python-driver](https://github.com/datastax/python-driver) tests. Specifically, it is reproduced by this test: 

```
tests/integration/standard/test_metadata.py:SchemaMetadataTests.test_compound_primary_keys_more_columns_compact
```

Bug description: when a table is created `WITH COMPACT STORAGE`, and later a `DESCRIBE SCHEMA` command is used, the `COMPACT STORAGE` part is missing.

Here's a session on Scylla 666.development-20160727.17b45fa

```
fedora@ip-172-31-7-64 ~ $ ccm node1 cqlsh                                                                                                                                                                    [67/215]
Connected to haim at 127.0.0.1:9042.
[cqlsh 5.0.1 | Cassandra 2.1.8 | CQL spec 3.2.1 | Native protocol v3]
Use HELP for help.
cqlsh> CREATE KEYSPACE a WITH replication = {'class': 'SimpleStrategy', 'replication_factor': 1};
cqlsh> use a;
cqlsh:a> CREATE TABLE test_compound_primary_keys_more_columns_compact (a text, b text, c text, d text, PRIMARY KEY (a, b, c)) WITH COMPACT STORAGE AND CLUSTERING ORDER BY (b ASC, c ASC)  ;                         
cqlsh:a> DESCRIBE SCHEMA 

CREATE KEYSPACE a WITH replication = {'class': 'SimpleStrategy', 'replication_factor': '1'}  AND durable_writes = true;

CREATE TABLE a.test_compound_primary_keys_more_columns_compact (
    a text,
    b text,
    c text,
    d text,
    PRIMARY KEY (a, b, c)
) WITH CLUSTERING ORDER BY (b ASC, c ASC)
    AND bloom_filter_fp_chance = 0.01
    AND caching = '{"keys":"ALL","rows_per_partition":"ALL"}'
    AND comment = ''
    AND compaction = {'class': 'SizeTieredCompactionStrategy'}
    AND compression = {'sstable_compression': 'org.apache.cassandra.io.compress.LZ4Compressor'}
    AND dclocal_read_repair_chance = 0.1
    AND default_time_to_live = 0
    AND gc_grace_seconds = 864000
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair_chance = 0.0
    AND speculative_retry = '99.0PERCENTILE';
```

Note that the `DESCRIBE` output lacks `COMPACT STORAGE`.  Here's the same thing with Cassandra 3.0.9

```
fedora@ip-172-31-7-64 ~ $ ccm node1 cqlsh                                                                                                                                                                            
Connected to cassix at 127.0.0.1:9042.
[cqlsh 5.0.1 | Cassandra 3.0.9 | CQL spec 3.4.0 | Native protocol v4]
Use HELP for help.
cqlsh> 
cqlsh> CREATE KEYSPACE a WITH replication = {'class': 'SimpleStrategy', 'replication_factor': 1}  ;
cqlsh> use a;
cqlsh:a> CREATE TABLE test_compound_primary_keys_more_columns_compact (a text, b text, c text, d text, PRIMARY KEY (a, b, c)) WITH COMPACT STORAGE AND CLUSTERING ORDER BY (b ASC, c ASC)  ;
cqlsh:a> DESCRIBE SCHEMA                                                                                                                                                                                             

CREATE KEYSPACE a WITH replication = {'class': 'SimpleStrategy', 'replication_factor': '1'}  AND durable_writes = true;

CREATE TABLE a.test_compound_primary_keys_more_columns_compact (
    a text,
    b text,
    c text,
    d text,
    PRIMARY KEY (a, b, c)
) WITH COMPACT STORAGE
    AND CLUSTERING ORDER BY (b ASC, c ASC)
    AND bloom_filter_fp_chance = 0.01
    AND caching = {'keys': 'ALL', 'rows_per_partition': 'NONE'}
    AND comment = ''
    AND compaction = {'class': 'org.apache.cassandra.db.compaction.SizeTieredCompactionStrategy', 'max_threshold': '32', 'min_threshold': '4'}
    AND compression = {'chunk_length_in_kb': '64', 'class': 'org.apache.cassandra.io.compress.LZ4Compressor'}
    AND crc_check_chance = 1.0
    AND dclocal_read_repair_chance = 0.1
    AND default_time_to_live = 0
    AND gc_grace_seconds = 864000
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair_chance = 0.0
    AND speculative_retry = '99PERCENTILE';
```

**Comment by penberg** [comment] 2017-01-09 13:09
The bug is no longer present in latest HEAD. I suspect it was fixed in cc30da38f94d07cb892afa0cd0c5b9fa86a64e9e. Ping @pdziepak 

```
CREATE TABLE a.test_compound_primary_keys_more_columns_compact (
    a text,
    b text,
    c text,
    d text,
    PRIMARY KEY (a, b, c)
) WITH COMPACT STORAGE
    AND CLUSTERING ORDER BY (b ASC, c ASC)
    AND bloom_filter_fp_chance = 0.01
    AND caching = '{"keys":"ALL","rows_per_partition":"ALL"}'
    AND comment = ''
    AND compaction = {'class': 'SizeTieredCompactionStrategy'}
    AND compression = {'sstable_compression': 'org.apache.cassandra.io.compress.LZ4Compressor'}
    AND dclocal_read_repair_chance = 0.1
    AND default_time_to_live = 0
    AND gc_grace_seconds = 864000
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair_chance = 0.0
    AND speculative_retry = '99.0PERCENTILE';
```

**Comment by pdziepak** [comment] 2017-01-09 13:22
Unlikely. cc30da38f94d07cb892afa0cd0c5b9fa86a64e9e is mostly about adding additional validation to creation of compact storage tables and ability to write to them. It doesn't touch the actual logic responsible to create compact storage table and write its description to system tables.
Besides, that series was merged over a year before this bug was reported.

**Comment by penberg** [comment] 2017-01-09 13:49
Right, I can't believe I didn't read the _year_ of the commit... Another potential fixer is 3bb16fba7ebf54d60bdbc0a14f0a904daea57fa9, which happened after the commit 17b45fae9ebcdce4fb5d4b47687236f1d79bd0ab that's being tested here.

/cc @glommer

**Comment by avikivity** [comment] 2017-01-09 13:57
Dates are hard...

**Comment by slivne** [comment] 2017-03-06 10:35
@roydahan can we also check this

**Comment by roydahan** [comment] 2017-03-20 16:34
Didn't test through the python-driver tests (yet), but seems like the bug was fixed or at least can't reproduce manually with latest versions.

**Closed** 2017-04-02 10:19 UTC
Labels: bug, fixed

**Comment by glommer** [comment] 2019-01-28 14:31
Issues with Scylla Enterprise should be handled through the supported channels so we can understand your exact version and environment.

**Comment by markbosshard** [comment] 2019-01-28 15:26
We have seen that the cqlsh is not actually showing the in_memory option. @glommer has opened an interal issue and future versions will contain this fix.

If you need a proof that you activated in_memory, you can do:
select * from system_schema.scylla_tables;

you will see your table and the in_memory flag set to true. Not that this feature is Scylla Enterprise (paid version), as far as I know.
