### ISSUE TITLE
Compaction becomes extremely slow in the middle of a huge compaction

### ISSUE THREAD

**Issue by nyh** [scylladb/scylla#2874] opened 2017-10-09 15:31 UTC
*Installation details*
Scylla 2.0 on Centos 7 VM on GCE - from our official RPMs. Ran Scylla with just one shard (the host itself has 4 cores, 10GB of memory, 100GB of SSD disk). I ran Scylla directly, not through any init scripts, and without any special kernel configuration:
```
/usr/bin/scylla --developer-mode=1 --collectd 0 --cpuset 0 -m 2G --api-address 127.0.0.1 --rpc-address 127.0.0.1 --listen-address 127.0.0.1 --prometheus-address 127.0.0.1 --seed-provider-parameters seeds=127.0.0.1 --datadir `pwd`/tmp/1 --commitlog-directory `pwd`/tmp/1  >/tmp/out1 2>&1 &
```

I ran cassandra-stress write test of 150 million partitions, supposed to take 45 GB of disk space, at rate 10,000 requests per second (which Scylla can sustain most of the time):

```  
N=1500000000
$CASSANDRA_STRESS write n=$N -pop seq=1..$N -schema "replication(strategy=org.apache.cassandra.locator.SimpleStrategy,factor=1)" -rate threads=30 limit=10000/s
```

Everything worked well until about 80 million partitions. At this point, we were doing the largest compaction so far: Compact four 5.2-GB sstables into one 20.8 GB. As can be seen in the graph I hope to attach:
![image](https://user-images.githubusercontent.com/584227/31345495-99606690-ad1e-11e7-8023-c7a0e7fdb856.png) the huge compaction (the last very steep slow) starts at a very fast and constant pace, but after writing about 11 GB, something really strange happens: the compaction appears to hang. It doesn't actually hang - rather it just becomes ridiculously slow, but still consumes 100% CPU, but even worse: it causes cassandra-stress to timeout on all its threads and exit. So maybe it doesn't just consume a lot of CPU but also does a lot in one continuation. When the load stops, compaction still continues, very very slowly, much slower than the first 11GB, but continues (doesn't hang), and continues to use 100% CPU while doing this.

The logs show nothing interesting - it just shows the extremely slow compaction as having started and not yet finished (before the load stopped, we still got additional data so smaller compactions started and ended, while this huge compaction never ended).

**Comment by avikivity** [comment] 2017-10-09 15:34
What are the axes of the graph?

**Comment by nyh** [comment] 2017-10-09 15:57
X axis is time (in seconds), y axis is "du" of the keyspace (in bytes). You can see a constant underlying slope (in green) because a cassandra-stress load is running with a constant number of writes per second (10,000 per second). You can see the various small and large compactions as "spikes" of temporary disk usage. These compactions have a certain upward slope - the speed at which we can do the compaction (in parallel with the request load). 
As you can see at the end (right side) of the graph, we have another compaction, which starts going up at the usual pace (like previous smaller compactions) but after writing about 11 GB (out of the 20 GB), the slow "breaks" and becomes MUCH slower. Worse, something happens to Scylla which causes all the requests to timeout and cassandra-stress exits. When it exits, compaction continues at the same very very slow pace.

**Comment by raphaelsc** [comment] 2017-10-09 15:59
On Mon, Oct 9, 2017 at 12:32 PM, nyh <notifications@github.com> wrote:

> *Installation details*
> Scylla 2.0 on Centos 7 VM on GCE - from our official RPMs. Ran Scylla with
> just one shard (the host itself has 4 cores, 10GB of memory, 100GB of SSD
> disk). I ran Scylla directly, not through any init scripts, and without any
> special kernel configuration:
>
> /usr/bin/scylla --developer-mode=1 --collectd 0 --cpuset 0 -m 2G --api-address 127.0.0.1 --rpc-address 127.0.0.1 --listen-address 127.0.0.1 --prometheus-address 127.0.0.1 --seed-provider-parameters seeds=127.0.0.1 --datadir `pwd`/tmp/1 --commitlog-directory `pwd`/tmp/1  >/tmp/out1 2>&1 &
>
> I ran cassandra-stress write test of 150 million partitions, supposed to
> take 45 GB of disk space, at rate 10,000 requests per second (which Scylla
> can sustain most of the time):
>
> N=1500000000
> $CASSANDRA_STRESS write n=$N -pop seq=1..$N -schema "replication(strategy=org.apache.cassandra.locator.SimpleStrategy,factor=1)" -rate threads=30 limit=10000/s
>
> Everything worked well until about 80 million partitions. At this point,
> we were doing the largest compaction so far: Compact four 5.2-GB sstables
> into one 20.8 GB. As can be seen in the graph I hope to attach:
> [image: image]
> <https://user-images.githubusercontent.com/584227/31345495-99606690-ad1e-11e7-8023-c7a0e7fdb856.png>
> the huge compaction (the last very steep slow) starts at a very fast and
> constant pace, but after writing about 11 GB, something really strange
> happens: the compaction appears to hang. It doesn't actually hang - rather
> it just becomes ridiculously slow, but still consumes 100% CPU, but even
> worse: it causes cassandra-stress to timeout on all its threads and exit.
> So maybe it doesn't just consume a lot of CPU but also does a lot in one
> continuation. When the load stops, compaction still continues, very very
> slowly, much slower than the first 11GB, but continues (doesn't hang), and
> continues to use 100% CPU while doing this.
>
> The logs show nothing interesting - it just shows the extremely slow
> compaction as having started and not yet finished (before the load stopped,
> we still got additional data so smaller compactions started and ended,
> while this huge compaction never ended).
>

flamegraph may help here. I'd ask you to check out it's not a regression,
but just noticed you tested it on 2.0. May it be compaction is slowed down
by memory desfragmentation? That's why a flamegraph could be helpful here.
How is memory consumption during the compaction?

**Comment by avikivity** [comment] 2017-10-09 16:05
How slow is slow? What is it doing?

**Comment by nyh** [comment] 2017-10-09 16:10
A new graph to explain things:
![image](https://user-images.githubusercontent.com/584227/31347604-8382ece2-ad25-11e7-937d-14da803e6b51.png)

**Comment by nyh** [comment] 2017-10-09 16:14
@avikivity: "slow" is a relative term. You can see the upward slope of all the compactions is more-or-less the same - this is the rate of the compaction. Suddenly the slope breaks and becomes perhaps 10 times slower (I didn't calculate the exact rate, I can). In the graph, the second slower half of the compaction does exactly the same number of bytes as the first half (which wrote 11 GB) but finishes more than 10 times slower.
Moreover, if compaction was "just" slow but didn't effect the write load, I could have (barely) accepted it - but it also breaks the write load, for no clear reason. Also note that Scylla took 100% CPU during the slow part of the compaction. So it's not an XFS pause bug (this is the first thing I checked).

**Comment by nyh** [comment] 2017-10-09 16:16
@raphaelsc yes I'm testing official 2.0, not master.
Can you please give me a few pointers on how to produce Scylla flamegraph?
I'll try to reproduce this with whatever you'll ask me to do. I really need these runs for the Scylla summit, so either I get the results I need for the presentation (great) or if it breaks again, at least I'll help find a bug :-)

**Comment by raphaelsc** [comment] 2017-10-09 16:23
On Mon, Oct 9, 2017 at 1:16 PM, nyh <notifications@github.com> wrote:

> @raphaelsc <https://github.com/raphaelsc> yes I'm testing official 2.0,
> not master.
> Can you please give me a few pointers on how to produce Scylla flamegraph?
>

https://github.com/scylladb/scylla/wiki/Flame-graph-creation

> I'll try to reproduce this with whatever you'll ask me to do. I really
> need these runs for the Scylla summit, so either I get the results I need
> for the presentation (great) or if it breaks again, at least I'll help find
> a bug :-)
>
it would be nice to correlate slowness with memory usage. The 100% cpu
during huge compaction leads to me think it has something to do with memory
defrag. It's not merges because you used n=$N -pop seq=1..$N, so no
overwrites, right? No tombstones either.

**Comment by nyh** [comment] 2017-10-09 18:14
@raphaelsc yes, no overwrites. But no reads either, so I don't know what memory would be used for...
 Compaction should not use an amount of memory proportional to the size of the sstable - if it is, it's a bug. Fragmentation might be relevant - e.g., we do (or at least did until recently and probably still do in 2.0) holds several of the smaller files of the sstable in a contiguous vector.
I'll try to do the profiling as you suggested to figure out what's going on while it's slow (of course, I'll have to reproduce the problem first, and that takes several hours...).

**Comment by nyh** [comment] 2017-10-09 18:25
@raphaelsc thanks for the flamegraphs tips. But one question... Our official binaries are stripped. The flamegraph I generate just seems to call every function in Scylla "[scylla]". What do you do to fix that? Where do we have scylla RPMs with debug information?

**Comment by nyh** [comment] 2017-10-09 21:05
So it appears this is a reproducible bug (maybe should be in our stress tests suite?):
I ran the same run again, and got the same problem in a slightly earlier position - it started during a **small** compaction whose slop (bytes per second) suddenly become much lower than usual, and then persisted to following compactions which all add their very low slope - and to add insult to injury cassandra-stress soon quit because of too many timeouts (the compaction, of course, continues after cassandra-stress quit, but continues to be very slow).

I profiles scylla while the slowness was ongoing.  Sadly I can't attach an SVG to this crappy bug tracker! But it allows gz, so here is svg.gz...
[flame2.svg.gz](https://github.com/scylladb/scylla/files/1369802/flame2.svg.gz)

I'm not sure what to make of it, but it seems Scylla is mostly spending time on garbage: 28% on timerfd_settime(), and other stuff I can't make much sense of. It seems only 10% of the CPU time is being spent on actual compaction work. 

Here is a graph of the disk usage, as above, demonstrating (as above) the problem - compactions are the spikes, and all have the same slope going up (which is the speed at which we can compact in parallel with the cassandra-stress load). suddenly, near the end, one small compaction has a much lower slope, and then the compactions that follow it also have very low slopes (and of course finish very slowly). The last compaction, a huge one, only started - it will take more than an hour at this pace, I'm not waiting for it.
![image](https://user-images.githubusercontent.com/584227/31358464-643f67ba-ad4e-11e7-8d85-f0c6d56eeb85.png)

**Comment by nyh** [comment] 2017-10-09 21:12
Here is another - simpler - flame graph. It is simpler because I took *after* the cassandra-stress load died, but compaction is still going on (very very slowly). So there's no write workload here, just the compaction. We see only 6% of the time being used for compaction - the rest of polling overheads and similar.

[flame3.svg.gz](https://github.com/scylladb/scylla/files/1369828/flame3.svg.gz)

Could this be a bug in our I/O queing code which (?) leaks tokens causing us to reduce parallelism at the end (and spend all our CPU on silly polling)? I never configured the I/O queues at all, but everything worked fine in the beginning, so how did things stop working 3 hours into the run?

**Comment by nyh** [comment] 2017-10-09 21:33
@glommer is there some metric or other technique I can use if something in the I/O queue code is deciding to give the compaction queue fewer tokens (or whatever the appropriate terminology is) and slowing down the I/O?

This may be a red herring, though. I verified (using the scylla_io_queue_compaction_total_{bytes,operations} counters) that even while it is extremely slow, compaction writes almost only full 128 KB buffers. I would have thought we don't need much parallelism for such large buffers. But maybe we do?

By the way, the problem happens - in two runs I did - at roughly the point when the compaction queue did 1 million operations (each a write of almost exactly 128 KB). I don't suppose we have a self-destruct limit at 1 million operations or 128 GB? :-)

**Comment by avikivity** [comment] 2017-10-10 07:08
There is still some compaction going on, so it looks like the I/O rate is slow. Please check the reactor aio metrics and the I/O queue metrics (specifically compaction queue delay, but also all the others).

**Comment by nyh** [comment] 2017-10-10 08:51
Unfortunately my VM was killed automatically (does this happen on GCE??) so I can't look now, but I remember I looked at the scylla_io_queue_compaction_queue_length and it was 0.0 (I remember not understanding what this means, and why it is floating point...) and scylla_io_queue_compaction_delay was something very low with a lot of zeros before the first significant digit (again I didn't understand what this means or what unit it has).

**Comment by nyh** [comment] 2017-10-10 11:57
The good news is that this bug seems 100% reproducible, I ran the job (which I described at the top) a third time, and again got slow compaction at exactly the same spot as in the first run, in the middle of the 20 GB compaction job.
@avikivity I don't see anything interesting in the counters you asked about - 
scylla_io_queue_compaction_queue_length is 0.000000
scylla_io_queue_compaction_delay is 0.000001
scylla_reactor_io_queue_requests is 0.000000
scylla_reactor_timers_pending is 245 (does this make sense?)

I don't know what other counters may e useful.

**Comment by nyh** [comment] 2017-10-10 20:41
iotune does not seem to improve anything for this bug... It suggested I should use "--max-io-requests=36" and I added that to my command line. It also added it to /etc/scylla.d/io.conf, I don't know if that's actually used anywhere.

But I still get exactly the same dog-slow-performance at almost exactly the same place (during the 20 GB compaction - this time after about 5 GB of compaction - suddenly compaction grinds to a halt). It seems that with these parameters the cassandra-stress doesn't die from timeouts (although there ARE timeouts), but it doesn't help the compaction at all, and it still becomes ridiculously slow.

The disk-usage-by-time graph looks similar to the ones I already pasted above, so I won't paste another one.

**Comment by tgrabiec** [comment] 2017-10-11 06:00
2017-10-10 22:41 GMT+02:00 nyh <notifications@github.com>:

> iotune does not seem to improve anything for this bug... It suggested I
> should use "--max-io-requests=36" and I added that to my command line. It
> also added it to /etc/scylla.d/io.conf, I don't know if that's actually
> used anywhere.
>
> But I still get exactly the same dog-slow-performance at almost exactly
> the same place (during the 20 GB compaction - this time after about 5 GB of
> compaction - suddenly compaction grinds to a halt). It seems that with
> these parameters the cassandra-stress doesn't die from timeouts (although
> there ARE timeouts), but it doesn't help the compaction at all, and it
> still becomes ridiculously slow.
>
> The disk-usage-by-time graph looks similar to the ones I already pasted
> above, so I won't paste another one.
>

Does the disk get sower, or Scylla gets slower?

**Comment by nyh** [comment] 2017-10-11 11:11
@tgrabiec it's not the disk which is getting slower, because when I restart Scylla, it goes back to normal compaction rate. So something in Scylla starts to access the disk slower - it doesn't appear to be a disk bug.
Also, when the problems start to happen, the disk is still 60% free space, so it's not an issue of the disk becoming slower as it fills up (also, such slowdown would have been gradual and not sudden as you can see in the graphs above).

**Comment by tzach** [comment] 2017-11-13 09:17
@raphaelsc @nyh what is the next step?

**Comment by nyh** [comment] 2017-11-13 09:57
Tzach, I don't know... I didn't imagine this bug - I was able to reproduce it a dozen times - but only on GCE. I was never able to reproduce it on my own laptop, and it appears nobody else noticed it on their own setup. So I stopped working on this unless someone declares this issue a priority.

**Comment by slivne** [comment] 2017-11-23 10:54
@nyh - do you have code that reproduces this ? if so can you attach it 

if you do not have code and have th e scenario (running c-s with population X ... etc) - please provide that.

**Comment by glommer** [comment] 2020-05-15 18:43
Hi, this is the human version of our new closing bot.
@raphaelsc claims that this doesn't happen anymore in the last times we tried.
It was reported with 2.0, we have no indication that it is still a problem. Plus if you were using GCE , maybe you just got hit by their beautiful 13s stalls coming from the disk.

If we have complaints about this again, let's reopen

**Closed by glommer** 2020-05-15 18:43 UTC
Labels: bug, performance
