### ISSUE TITLE
Support for sub-second ttl expiration granularity

### ISSUE THREAD

**Issue by sjudeng** [scylladb/scylla#2497] opened 2017-06-17 17:20 UTC
*Installation details: Docker scylladb/scylla:1.7.1 (530791a3c80c)*

Currently [JanusGraph](http://janusgraph.org/) unit tests are almost all passing with ScyllaDB using CQL (see [summary](https://github.com/JanusGraph/janusgraph/issues/53#issuecomment-306068898)). I'm trying to track down the few remaining failures which all appear to be TTL-related.

One of the issues occurs in [JanusGraphTest#testEdgeTTLTiming](https://github.com/JanusGraph/janusgraph/blob/e17bbd17fc66f1ed05d8536444adb60bcb9c8d95/janusgraph-test/src/main/java/org/janusgraph/graphdb/JanusGraphTest.java#L4686). In the test there are 3 vertices (rows) as well as 3 edges (cells), two of which are subject to 1 and 4 second ttl limits, respectively. After committing and waiting 1.2 seconds it checks that the first edge with one second ttl is gone, but with ScyllaDB this check fails (the edge appears to still be present). If I update to instead wait 2 seconds then that assert passes. The behavior is duplicated in the second check, where the second edge is still present after 4.5 seconds but it is gone if the wait is 5 seconds.

Does this sound like it might be an issue with cell ttl in ScyllaDB? In case useful I have a branch where you can reproduce the issue as shown below.

```bash
# start scylladb
docker run --name jg-scylla --rm -p 9160:9160 -p 9042:9042 -d scylladb/scylla:1.7.1 --smp 2

# clone janusgraph and checkout test branch
git clone https://github.com/JanusGraph/janusgraph.git && cd janusgraph
git remote add sjudeng https://github.com/sjudeng/janusgraph.git && git fetch sjudeng
git checkout scylladb-test
# build
mvn clean install -DskipTests -pl janusgraph-cql -am
# test
mvn verify -pl janusgraph-cql -Dtest.skip.ordered=true -Dtest.skip.unordered=true -Dtest.skip.ssl=true -Dtest.skip.serial=true -Dstorage.hostname=0.0.0.0 -Dtest=CQLGraphTest#testEdgeTTLTiming
```

**Comment by avikivity** [comment] 2017-06-18 08:16
Sounds like a rounding error. It could even be the correct behavior, since expiration times have second granularity.

 In any case, I recommend not relying on sub-second expiration granularity. Is this something the application relies on, or a test artifact?

**Comment by sjudeng** [comment] 2017-06-18 13:17
Okay thanks for looking at it. For what it's worth I did confirm that the other four TTL test failures occurring when using ScyllaDB are related to the same issue (e.g. tests are assuming ttl is enforced within as little as a millisecond). I'll update the issue title to reflect this.

The tests are common across all JanusGraph storage backends (Cassandra CQL/Thrift/Astyanax/Embedded, HBase and BerkeleyDB). I'm not sure if sub-second expiration is required or just tested. At this point I'm just assessing whether ScyllaDB can be dropped in seamlessly for our Cassandra backend. Again the initial results are great, so kudos to your team! I think this issue would be a pretty trivial caveat for us to make regarding using JanusGraph with ScyllaDB, though of course ideally there would be no caveats.

**Comment by avikivity** [comment] 2017-06-18 13:23
atomic_cell.hh says:

```c++
    // Can be called on live and dead cells
    bool has_expired(gc_clock::time_point now) const {
        return is_live_and_has_ttl() && expiry() < now;
    }
```

Probably, changing `<` to `<=` would make the tests pass, though it's not clear if that's the real issue; perhaps it's a rounding error elsewhere.

**Comment by avikivity** [comment] 2017-06-18 13:34
@tgrabiec opinion?

**Comment by tgrabiec** [comment] 2017-06-18 16:47
The docs [1] say:

```
The TTL value for a column is a number of seconds. After the number of seconds since the column's creation exceeds the TTL value, TTL data is considered expired and is included in results. 
```

I would interpret that to mean that the cell should live for at least TTL seconds. That's what we implement. The expiry timestamps recorded in cells have resolution of 1 second, so a cell in Scylla can live anywhere between [TTL, TTL + 1s].

I checked cassandra 2.1.9 source code, and they seem to be rounding down:

```java
    @Override
    public boolean isLive(long now)
    {
        return (int) (now / 1000) < getLocalDeletionTime();
    }
```

It means the cell lives anywhere between [TTL - 1s, TTL]. A cell with TTL=1 can expire immediately.

I think our behavior makes more sense, but perhaps we should align to what Cassandra does for better compatibility.

[1] http://docs.datastax.com/en/cql/3.1/cql/cql_using/use_expire_c.html

**Comment by avikivity** [comment] 2017-06-18 16:59
Here is trunk:

```java
    public boolean isLive(int nowInSec)
    {
        return localDeletionTime() == NO_DELETION_TIME || (ttl() != NO_TTL && nowInSec < localDeletionTime());
    }
```

So it is unchanged.

**Comment by roydahan** [comment] 2017-06-22 17:34
It may be worth to add your tests to our regressions suite.
I see a you used a branch scylladb-test, is that the branch we should use or any other specific branch?
Also, any recommendations on which tests to run?

**Comment by sjudeng** [comment] 2017-06-22 18:53
@roydahan That branch has now been merged into janusgraph:master. Eventually it might be preferable to use a tagged release branch once JanusGraph releases v0.2.0, just so you know it's stable on that end. As far as which tests the simplest would be to run all the tests in the janusgraph-cql module but those might take an hour or more to run. If that's infeasible we can try to provide a minimal list of tests to run. If you just want to test out the plumbing you could use CQLGraphTest.

```bash
git clone https://github.com/JanusGraph/janusgraph.git && cd janusgraph
mvn clean install -DskipTests -pl janusgraph-cql -am
mvn verify -pl janusgraph-cql -Dstorage.hostname=0.0.0.0 -Dtest=CQLGraphTest
```

Note the above assumes ScyllaDB is running locally. The test suites themselves do not manage starting/stopping the ScyllaDB instance. For convenience there is a Maven profile, `scylladb-test`, that will start/stop a ScyllaDB Docker container as part of Maven Failsafe plugin (see [JanusGraph:TESTING.md](https://github.com/JanusGraph/janusgraph/blob/master/TESTING.md#running-thriftcql-tests-with-scylladb-requires-docker)).

**Comment by roydahan** [comment] 2017-06-25 20:13
Thanks @sjudeng for the info.
An hour should be fine I guess, so we'll try to run them all.

**Comment by slivne** [comment] 2017-07-03 12:06
@avikivity so should we align with cassandra here ?

**Comment by avikivity** [comment] 2017-07-03 12:07
I guess we can

**Comment by haaawk** [comment] 2017-08-01 12:48
Would this be an acceptable solution @avikivity:
https://github.com/scylladb/seastar-dev/commits/fix2497

**Comment by avikivity** [comment] 2017-08-01 12:58
Very verbose. Why not expiration <= now + 1s?

**Comment by haaawk** [comment] 2017-08-01 20:36
Fair enough. Here's an updated version:
https://github.com/scylladb/seastar-dev/commits/fix2497_v2

**Comment by haaawk** [comment] 2017-08-08 13:37
Would this new version be good enough to be merged @avikivity ?

**Comment by avikivity** [comment] 2017-08-08 13:54
Don't add `using namespace` in a header. Add it in the body. Does it match Origin now?

**Comment by haaawk** [comment] 2017-08-08 14:53
@avikivity I put some more thoughts into that and it seems that it is enough to change < to <= to make Scylla behave like Origin. Please find the new version here:
https://github.com/scylladb/seastar-dev/commits/fix2497_v3

**Comment by avikivity** [comment] 2017-08-14 08:16
Please post patches to the mailing list for review.

**Closed** 2017-08-21 12:51 UTC
Labels: bug, CQL
