### ISSUE TITLE
cql3: `uuid()` function is not marked as "pure" but timeuuid-related functions are

### ISSUE THREAD

**Issue by ManManson** [scylladb/scylla#8816] opened 2021-06-07 16:18 UTC
`uuid()` CQL function isn't marked as "pure" hence its execution is delayed until the actual execution of the function begins, even for prepared statements, which seems to be logically correct.

Some other functions related to timeuuid, e.g. `currenttimeuuid()`, are marked as "pure" so that they are executed when a statement is being prepared.

This can lead to unobvious behavior if used in partition keys with insert statement, for example.
The former case would create a new partition each time a prepared statement is executed, but the latter will not and could possibly cause overwriting data in the same partition.

The following functions are are marked with `is_pure()` at the moment:

- `currenttimestamp`
- `currenttime`
- `currentdate`
- `currenttimeuuid`

The test case to demonstrate the issue:
```c++
// `uuid()` CQL function isn't marked as "pure" hence
// its execution is delayed until the actual execution of the function begins,
// which seems to be logically correct.
// Some other functions, related to timeuuid, e.g. `currenttimeuuid()`, are
// marked as "pure" so that they are executed when a statement is being prepared.
//
// This can lead to unobvious behavior if used in partition keys with insert
// statement, for example.
// The former case would create a new partition each time a prepared statement
// is executed, but the latter will not and could possibly cause overwriting
// data in the same partition.
SEASTAR_TEST_CASE(test_uuid_timeuuid_is_pure_issue) {
    return do_with_cql_env_thread([] (cql_test_env& e) {
        {
            e.execute_cql("CREATE TABLE test_timeuuid (pk timeuuid PRIMARY KEY)").get();
            auto insert_stmt = e.prepare("INSERT INTO test_timeuuid (pk) VALUES (currenttimeuuid())").get();
            e.execute_prepared(insert_stmt, {}).get();
            sleep(1ms).get();
            // Check that the second execution of prepared insert statement
            // yields the same value for inserted `pk` and so doesn't produce
            // a different partition.
            e.execute_prepared(insert_stmt, {}).get();
            auto msg = e.execute_cql("SELECT * FROM test_timeuuid").get();
            assert_that(msg).is_rows().with_size(1);
        }
        {
            e.execute_cql("CREATE TABLE test_uuid (pk uuid PRIMARY KEY)").get();
            auto insert_stmt = e.prepare("INSERT INTO test_uuid (pk) VALUES (uuid())").get();
            e.execute_prepared(insert_stmt, {}).get();
            // Check that the second execution is evaluated again and yields a
            // different value for inserted `pk`.
            e.execute_prepared(insert_stmt, {}).get();
            auto msg = e.execute_cql("SELECT * FROM test_uuid").get();
            assert_that(msg).is_rows().with_size(2);
        }
    });
}
```
Also available at: https://github.com/scylladb/scylla/commit/d91cb0ce680e2b2b34d06084d8ea0ade6aa656cc#diff-ac69a1eecfe0031927e37810e13dc487a6cc907943cd5f7f0cf37a9eda374d31R4976

Is it a bug and these functions should not be marked pure or is it an intended behavior?

Cassandra always defer CQL function execution up to the last moment, acting like `is_pure() == false` in terms of our implementation:
https://github.com/apache/cassandra/blob/4fd21245727f4bd3b8a7cd6b8bf5a4a5cb14a328/src/java/org/apache/cassandra/cql3/functions/FunctionCall.java#L186

*Installation details*
Scylla version (or git commit hash): master (fa29b79c200d81de6e35685c5b70ff6ae278d12a)

**Comment by kostja** [comment] 2021-06-08 09:59
As soon as this is fixed, the impact of #8604 will be much higher, in fact a fix for this bug will regress client scenarios which use these (fixed) functions in LWT as primary keys.

**Comment by ManManson** [comment] 2021-06-08 12:48
@psarna Hi, you've added some time ago `current*()` functions mentioned above in https://github.com/scylladb/scylla/commit/087998b76879b00d515267cc8b17cd5c24b5956b.

Was there any particular reason why these functions were defined with `is_pure() == true`?

**Comment by psarna** [comment] 2021-06-08 12:51
I don't recall any particular reason, it simply looks like a bug.

**Closed** 2021-08-01 16:17 UTC
Labels: CQL, Correctness, bug, lwt

**Comment by avikivity** [comment] 2021-10-17 12:36
This is not a regression, in rarely used functionality, and quite complicated, so not backporting.
