### ISSUE TITLE
redis: parse error message is broken

### ISSUE THREAD

**Issue by syuu1228** [scylladb/scylla#7861] opened 2021-01-04 11:29 UTC
On test_ping_and_eof(), it seems like redis server returning strange message at broken message.
It is repeating same reply twice, instead of replying error message.
```
================================== FAILURES ===================================
______________________________ test_ping_and_eof ______________________________

redis_host = 'localhost', redis_port = 6379

    def test_ping_and_eof(redis_host, redis_port):
        # regular ping with shutdown
        verify_cmd_response(redis_host, redis_port, '*1\r\n$4\r\nping\r\n', '+PONG\r\n', shutdown=True)
    
        # a EOF char `\x04` should be triggered parse error
>       verify_cmd_response(redis_host, redis_port, "*1\r\n$4\r\nping\r\n\x04", "+PONG\r\n-ERR unknown command ''\r\n", shutdown=True)

test/redis/test_raw_cmd.py:74: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

host = 'localhost', port = 6379, cmd = '*1\r\n$4\r\nping\r\n\x04'
expect_ret = "+PONG\r\n-ERR unknown command ''\r\n", shutdown = True

    def verify_cmd_response(host, port, cmd, expect_ret, shutdown=False):
        rs = RedisSocket(host, port)
        rs.send(cmd.encode())
        if shutdown:
            rs.shutdown()
        ret = rs.recv().decode()
        logger.debug('Received content size: %s' % len(ret))
        logger.debug(ret)
>       assert ret == expect_ret
E       assert '+PONG\r\n+PONG\r\n' == "+PONG\r\n-ER...ommand ''\r\n"
E           +PONG
E         - -ERR unknown command ''
E         + +PONG

test/redis/test_raw_cmd.py:56: AssertionError
```

**Comment by nyh** [comment] 2021-01-04 12:35
I think this is a duplicate of  #7114

**Closed** 2021-01-07 15:10 UTC
Labels: Redis API

**Comment by avikivity** [comment] 2021-02-02 15:05
Redis is not production ready, so not backporting.
