### ISSUE TITLE
Unimplement grant/list/revoke does not return an explicit error message

### ISSUE THREAD

**Issue by benoit-canet** [scylladb/scylla#876] opened 2016-02-04 18:00 UTC
The CQL parse error returned can be confusing for the user a proper
message should be returned.

How to reproduce: Use the dtest cql_additional_test that will be merged soon

**Comment by slivne** [comment] 2018-02-01 08:12
@hakuch after we finish roles lets clear this one out

**Comment by hakuch** [comment] 2018-02-01 14:29
This may be fixed in the large roles series that will land soon, but I'm not sure because I don't understand the bug itself. @benoit-canet, would you plain explain exactly what the problem is?

**Comment by hakuch** [comment] 2018-03-30 15:15
@slivne, in the absence of additional information, can we close this?

**Comment by eliransin** [comment] 2020-03-17 07:17
cql_additional_test is running for a long time now. We also implemented the roles interface.
closing.

**Closed by eliransin** 2020-03-17 07:17 UTC
Labels: bug
