### ISSUE TITLE
(LOCAL_/EACH_)QUORUM consistency calculation is broken when RF=0

### ISSUE THREAD

**Issue by vladzcloudius** [scylladb/scylla#6905] opened 2020-07-22 16:29 UTC
*Installation details*
Scylla version: 5e1fa13d088c5fdea7c4626474e367f81d5d1f4d

*Description*
Our current implementation of `db::quorum_for(...)`, `db::local_quorum_for(...)` is going to return 1 when RF for the corresponding replication unit is 0.

One of the cases where this causes a problem is when there is DC in the replication list of a KS that uses `NetworkTopologyStrategy` with RF=0, this DC is not longer present in the cluster (e.g. has been decommissioned) and there comes a write with CL=EACH_QUORUM.

The bug will make every such write fail with `write unavailable` because `assure_sufficient_live_nodes_each_quorum(...)` would always return `false` and this is because `dc_live(0) < dc_block_for(1)` for the DC with RF=0 as described above.

**Comment by gleb-cloudius** [comment] 2020-07-23 09:23
@slivne The patch is trivial, but I do not have time for repro and testing, please find another victim.

**Comment by slivne** [comment] 2020-08-11 19:07
@eliransin can you please have someone help with this

**Comment by kostja** [comment] 2020-09-28 15:48
I believe this is a duplicate of https://github.com/scylladb/scylla/issues/5962

**Closed** 2020-09-29 20:39 UTC
Labels: Backport candidate, Correctness, Eng-2, Field-Tier2, bug, coordination, enterprise

**Comment by avikivity** [comment] 2020-11-29 14:47
Backported to 4.1, 4.2. 4.3 already had it.
