### ISSUE TITLE
no_cross_shard_ops_test failed assert after[name] - before[name] <= 16

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#8118] opened 2021-02-18 12:38 UTC
See in https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-debug-random/401/testReport/junit/lwt_test/LwtTest/no_cross_shard_ops_test/
Scylla version 2f3b265dac0acf3b2c243351bf466247ca9c7a0a
```
Traceback (most recent call last):
  File "/usr/lib64/python3.7/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/usr/lib64/python3.7/unittest/case.py", line 645, in run
    testMethod()
  File "/jenkins/workspace/scylla-master/dtest-debug-random/scylla-dtest/lwt_test.py", line 53, in no_cross_shard_ops_test
    assert after[name] - before[name] <= 16, "{}:{}".format(before, after)
AssertionError: {'scylla_storage_proxy_replica_cross_shard_ops': 131}:{'scylla_storage_proxy_replica_cross_shard_ops': 148}
```

**Comment by bhalevy** [comment] 2021-02-18 12:38
Cc @kostja

**Comment by kostja** [comment] 2021-02-18 12:52
Must be something new calling invoke_on()  on the write path, the test was added for LWT but is impacted by other changes on the write path.

**Comment by slivne** [comment] 2021-02-21 08:44
@kostja ok - so two options either find the source commit (via bisect and then we can have the owner fix it) - or have someone in your team find he source and fix it.

(@bhalevy can't chase all regressions on his own).

**Comment by kostja** [comment] 2021-02-22 08:02
@bhalevy afaiu the test is flaky, so bisect won't cut it.

**Comment by bhalevy** [comment] 2021-02-22 12:50
Can the test be fixed to be stable?
What makes it flaky?

**Comment by bhalevy** [comment] 2021-03-16 08:35
ping @kostja we need to fix this, still hitting this...
https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/757/testReport/lwt_test/LwtTest/no_cross_shard_ops_test/
https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/765/testReport/lwt_test/LwtTest/no_cross_shard_ops_test/

If the test is flaky let's fix it.
Let's start with opening an issue on scylla-dtest and provide an analysis of what's wrong in the test and how it should be fixed, if possible.

**Comment by kostja** [comment] 2021-04-06 18:26
The culprit of the extra cross shard op is a call to ```db::schema_tables::do_merge_schema(seastar::sharded<service::storage_proxy>&, std::vector<mutation, std::allocator<mutation> >, bool)::$_16>(seastar::thread_attributes, db::schema_tables::do_merge_schema(seastar::sharde
d<service::storage_proxy>&, std::vector<mutation, std::allocator<mutation> >, bool)```

Do understand why it's bad please consider what the test is doing. It starts a single instance of Scylla, creates a table, and performs 16 inserts into it, sequentially. Since when have we started doing shadow schema merges on the write path?

**Comment by kostja** [comment] 2021-04-06 19:31
Another piece of trace is `                std::vector<mutation, std::allocator<mutation>                                      
                > > > >(boost::iterator_range<__gnu_cxx::__normal_iterator<mutation*,               
                    std::vector<mutation, std::allocator<mutation>                                  
                    > > >, db::consistency_level, bool,                                             
                    tracing::trace_state_ptr, service_permit,                                       
                    std::optional<std::chrono::time_point<seastar::lowres_clock,                    
                    std::chrono::duration<long, std::ratio<1l,                                      
                    1000l> > > >,                                                                   
                    seastar::lw_shared_ptr<cdc::operation_result_tracker>)::{lambda(std::vector<service::storage_proxy::unique_response_handler,
                    std::allocator<service::storage_proxy::unique_response_handler>                 
                    >)#1}, seastar::future<void>                                     `
which is invoked from mutate_internal even if the table has no CDC.
Is it OK?

**Comment by kostja** [comment] 2021-04-07 14:26
https://github.com/scylladb/scylla-dtest/pull/2084

**Comment by slivne** [comment] 2022-04-14 08:41
the dtest patch was merged

closing this issue

**Closed by slivne** 2022-04-14 08:41 UTC
Labels: lwt, dtest
