### ISSUE TITLE
unable to restart scylla server on the last node after downgrade

### ISSUE THREAD

**Issue by abvgedeika** [scylladb/scylla#2635] opened 2017-07-25 21:43 UTC
steps:
3 nodes in 1.7.2 cluster

1) upgrade 1.7.2->2.0 latest
```
echo "[scylla]
name=Scylla for Centos $releasever - $basearch
baseurl=http://downloads.scylladb.com/rpm/unstable/centos/branch-2.0/latest/scylla/\$releasever/\$basearch/
enabled=1
gpgcheck=0

[scylla-generic]
name=Scylla for centos $releasever
baseurl=http://downloads.scylladb.com/rpm/unstable/centos/branch-2.0/latest/scylla/\$releasever/noarch/
enabled=1
gpgcheck=0

[scylla-3rdparty]
name=Scylla 3rdParty for Centos $releasever - $basearch
baseurl=http://downloads.scylladb.com/rpm/unstable/centos/branch-2.0/latest/3rdparty/\$releasever/\$basearch/
enabled=1
gpgcheck=0

[scylla-3rdparty-generic]
name=Scylla 3rdParty for Centos $releasever
baseurl=http://downloads.scylladb.com/rpm/unstable/centos/branch-2.0/latest/3rdparty/\$releasever\/noarch/
enabled=1
gpgcheck=0" > /tmp/scylla.repo

sudo cp /etc/yum.repos.d/scylla.repo ~/scylla.repo-backup
sudo cp /tmp/scylla.repo /etc/yum.repos.d/scylla.repo
            # backup the data
sudo cp /etc/scylla/scylla.yaml /etc/scylla/scylla.yaml-backup
sudo nodetool snapshot
sudo chown root.root /etc/yum.repos.d/scylla.repo
sudo chmod 644 /etc/yum.repos.d/scylla.repo
sudo yum clean all
sudo yum install scylla scylla-server scylla-jmx scylla-tools scylla-conf scylla-kernel-conf scylla-debuginfo -y
        # flush all memtables to SSTables
sudo nodetool drain
sudo systemctl restart scylla-server.service
#        node.wait_db_up(verbose=True)
rpm -qa scylla-server
```
2)  rollback 2.0->1.7.3 except scylla-tools package due to https://github.com/scylladb/scylla-tools-java/issues/44 on all 2 nodes successively
```
rpm -qa scylla-server
sudo cp ~/scylla.repo-backup /etc/yum.repos.d/scylla.repo
        # backup the data
nodetool snapshot
sudo chown root.root /etc/yum.repos.d/scylla.repo
sudo chmod 644 /etc/yum.repos.d/scylla.repo')
sudo yum clean all
sudo yum downgrade scylla scylla-server scylla-jmx scylla-conf scylla-kernel-conf scylla-debuginfo -y
        # flush all memtables to SSTables
nodetool drain
sudo cp /etc/scylla/scylla.yaml-backup /etc/scylla/scylla.yaml
sudo systemctl restart scylla-server.service

```

after I restart scylla I get error

```
Jul 25 21:13:58 ip-172-30-0-155 scylla[8676]:  [shard 0] messaging_service - Starting Messaging Service on port 7000
Jul 25 21:13:59 ip-172-30-0-155 scylla[8676]:  [shard 0] seastar - Exiting on unhandled exception: std::runtime_error (Feature check failed. This node can not join the cluster because it does not understand the feature. Local node 172.30.0.155 features = {LARGE_PARTITIONS, RANGE_TOMBSTONES}, Remote common_features = {COUNTERS, LARGE_PARTITIONS, RANGE_TOMBSTONES})
```

As a result all 3 scylla servers down.
Then I restarted them one by one. The last one where I performed downgrade( when another 2 was already down) was not able to start with:

**Jul 25 21:41:00 ip-172-30-0-49.ec2.internal scylla[3950]:  [shard 0] seastar - Exiting on unhandled exception: std::runtime_error (Feature check failed. This node can not join the cluster because it does not understand the feature. Local node 172.30.0.49 features = {LARGE_PARTITIONS, RANGE_TOMBSTONES}, Remote common_features = {COUNTERS, LARGE_PARTITIONS, RANGE_TOMBSTONES})
compaction_manager - compaction failed: seastar::gate_closed_exception** 

```
Jul 25 21:41:00 ip-172-30-0-49.ec2.internal scylla[3950]:  [shard 0] storage_service - load_peer_features: peer=172.30.0.155, supported_features=RANGE_TOMBSTONES,LARGE_PARTITIONS,COUNTERS
Jul 25 21:41:00 ip-172-30-0-49.ec2.internal scylla[3950]:  [shard 0] storage_service - load_peer_features: peer=172.30.0.249, supported_features=RANGE_TOMBSTONES,LARGE_PARTITIONS,COUNTERS
Jul 25 21:41:00 ip-172-30-0-49.ec2.internal scylla[3950]:  [shard 0] storage_service - Checking remote features with system table, since this node is the only seed node
Jul 25 21:41:00 ip-172-30-0-49.ec2.internal scylla[3950]:  [shard 0] seastar - Exiting on unhandled exception: std::runtime_error (Feature check failed. This node can not join the cluster because it does not understand the feature. Local node 172.30.0.49 features = {LARGE_PARTITIONS, RANGE_TOMBSTONES}, Remote common_features = {COUNTERS, LARGE_PARTITIONS, RANGE_TOMBSTONES})
Jul 25 21:41:00 ip-172-30-0-49.ec2.internal scylla[3950]:  [shard 0] compaction_manager - Asked to stop
Jul 25 21:41:00 ip-172-30-0-49.ec2.internal scylla[3950]:  [shard 2] compaction_manager - Asked to stop
Jul 25 21:41:00 ip-172-30-0-49.ec2.internal scylla[3950]:  [shard 7] compaction_manager - Asked to stop
Jul 25 21:41:00 ip-172-30-0-49.ec2.internal scylla[3950]:  [shard 1] compaction_manager - Asked to stop
Jul 25 21:41:00 ip-172-30-0-49.ec2.internal scylla[3950]:  [shard 6] compaction_manager - Asked to stop
Jul 25 21:41:00 ip-172-30-0-49.ec2.internal scylla[3950]:  [shard 4] compaction_manager - Asked to stop
Jul 25 21:41:00 ip-172-30-0-49.ec2.internal scylla[3950]:  [shard 6] compaction_manager - Stopped
Jul 25 21:41:00 ip-172-30-0-49.ec2.internal scylla[3950]:  [shard 1] compaction_manager - Stopped
Jul 25 21:41:00 ip-172-30-0-49.ec2.internal scylla[3950]:  [shard 4] compaction_manager - Stopped
Jul 25 21:41:00 ip-172-30-0-49.ec2.internal scylla[3950]:  [shard 5] compaction_manager - Asked to stop
Jul 25 21:41:00 ip-172-30-0-49.ec2.internal scylla[3950]:  [shard 5] compaction_manager - Stopped
Jul 25 21:41:00 ip-172-30-0-49.ec2.internal scylla[3950]:  [shard 3] compaction_manager - Asked to stop
Jul 25 21:41:00 ip-172-30-0-49.ec2.internal scylla[3950]:  [shard 3] compaction_manager - Stopped
Jul 25 21:41:00 ip-172-30-0-49.ec2.internal scylla[3950]:  [shard 0] compaction_manager - Stopped
Jul 25 21:41:00 ip-172-30-0-49.ec2.internal scylla[3950]:  [shard 2] compaction - Compacted 10 sstables to [/var/lib/scylla/data/system/local-7ad54392bcdd35a684174e047860b377/system-local-ka-186-Data.db:level=0, ]. 67429 bytes to 13293 (~19% of original) in 49ms = 0.258718MB/s. ~2560 total partitions merged to 1.
Jul 25 21:41:00 ip-172-30-0-49.ec2.internal scylla[3950]:  [shard 2] compaction_manager - compaction failed: seastar::gate_closed_exception (gate closed)
Jul 25 21:41:00 ip-172-30-0-49.ec2.internal scylla[3950]:  [shard 2] compaction_manager - Stopped
Jul 25 21:41:00 ip-172-30-0-49.ec2.internal scylla[3950]:  [shard 7] compaction - Compacted 4 sstables to [/var/lib/scylla/data/system/schema_keyspaces-b0f2235744583cdb9631c43e59ce3676/system-schema_keyspaces-ka-47-Data.db:level=0, ]. 624 bytes to 156 (~25% of original) in 155ms = 0.000959827MB/s. ~1024 total partitions merged to 1.
Jul 25 21:41:00 ip-172-30-0-49.ec2.internal scylla[3950]:  [shard 7] compaction - Compacted 4 sstables to [/var/lib/scylla/data/system/schema_functions-d1b675fe2b503ca48e49c0f81989dcad/system-schema_functions-ka-47-Data.db:level=0, ]. 88 bytes to 22 (~25% of original) in 155ms = 0.00013536MB/s. ~1024 total partitions merged to 1.
Jul 25 21:41:00 ip-172-30-0-49.ec2.internal scylla[3950]:  [shard 7] compaction - Compacted 4 sstables to [/var/lib/scylla/data/system/schema_columns-296e9c049bec3085827dc17d3df2122a/system-schema_columns-ka-47-Data.db:level=0, ]. 151884 bytes to 37971 (~25% of original) in 154ms = 0.235143MB/s. ~1024 total partitions merged to 1.
Jul 25 21:41:00 ip-172-30-0-49.ec2.internal scylla[3950]:  [shard 7] compaction - Compacted 4 sstables to [/var/lib/scylla/data/system/schema_usertypes-3aa752254f82350b8d5c430fa221fa0a/system-schema_usertypes-ka-47-Data.db:level=0, ]. 88 bytes to 22 (~25% of original) in 154ms = 0.000136239MB/s. ~1024 total partitions merged to 1.
Jul 25 21:41:00 ip-172-30-0-49.ec2.internal scylla[3950]:  [shard 7] compaction - Compacted 4 sstables to [/var/lib/scylla/data/system/schema_aggregates-a5fc57fc9d6c3bfda3fc01ad54686fea/system-schema_aggregates-ka-47-Data.db:level=0, ]. 88 bytes to 22 (~25% of original) in 156ms = 0.000134493MB/s. ~1024 total partitions merged to 1.
Jul 25 21:41:00 ip-172-30-0-49.ec2.internal scylla[3950]:  [shard 7] compaction - Compacted 4 sstables to [/var/lib/scylla/data/system/schema_triggers-0359bc7171233ee19a4ab9dfb11fc125/system-schema_triggers-ka-47-Data.db:level=0, ]. 88 bytes to 22 (~25% of original) in 156ms = 0.000134493MB/s. ~1024 total partitions merged to 1.
Jul 25 21:41:00 ip-172-30-0-49.ec2.internal scylla[3950]:  [shard 7] compaction - Compacted 6 sstables to [/var/lib/scylla/data/system/views-24649002082e352d9236b94d49769a37/system-views-ka-127-Data.db:level=0, ]. 132 bytes to 22 (~16% of original) in 156ms = 0.000134493MB/s. ~1536 total partitions merged to 1.
Jul 25 21:41:00 ip-172-30-0-49.ec2.internal scylla[3950]:  [shard 7] compaction_manager - compaction failed: seastar::gate_closed_exception (gate closed)
Jul 25 21:41:00 ip-172-30-0-49.ec2.internal scylla[3950]:  [shard 7] compaction_manager - compaction failed: seastar::gate_closed_exception (gate closed)
Jul 25 21:41:00 ip-172-30-0-49.ec2.internal scylla[3950]:  [shard 7] compaction_manager - compaction failed: seastar::gate_closed_exception (gate closed)
Jul 25 21:41:00 ip-172-30-0-49.ec2.internal scylla[3950]:  [shard 7] compaction - Compacted 4 sstables to [/var/lib/scylla/data/system/schema_columnfamilies-45f5b36024bc3f83a3631034ea4fa697/system-schema_columnfamilies-ka-47-Data.db:level=0, ]. 145532 bytes to 36383 (~25% of original) in 155ms = 0.223855MB/s. ~1024 total partitions merged to 1.
Jul 25 21:41:00 ip-172-30-0-49.ec2.internal scylla[3950]:  [shard 7] compaction_manager - compaction failed: seastar::gate_closed_exception (gate closed)
```

**Comment by slivne** [comment] 2017-08-19 20:24
@syuu1228 ping

**Comment by tzach** [comment] 2017-08-21 08:56
Currently, there is no way to do a rolling downgrade from 2.0 to 1.7, or from any release with a new feature.
Once a new feature is active, a node with an older release will not be able to join the cluster.

**Comment by syuu1228** [comment] 2017-08-21 12:58
I tried to reproduce the issue by referencing @abvgedeika report, but I haven't able to get the error on my test environment.
The error message seems 1.7 trying to connect 2.0 node as @tzach commented ("Once a new feature is active, a node with an older release will not be able to join the cluster"), so I guess the error occurs because the cluster accidently mixed up both 1.7 nodes and 2.0 nodes.
If so, probably the solution is stop mixing up two versions.

**Comment by tzach** [comment] 2017-08-21 17:30
mixing two version is currently allowed as part of the rolling upgrade, not rolling downgrade.
@abvgedeika did you had the issue on the way up or down?

**Comment by tzach** [comment] 2017-08-23 08:50
Closing as this is an expected behavior.

**Closed by tzach** 2017-08-23 08:50 UTC
Labels: bug, wontfix
