### ISSUE TITLE
CDC prevents +rolling upgrade from pre 4.0 to a newer version with experimental enabled

### ISSUE THREAD

**Issue by kostja** [scylladb/scylla#6537] opened 2020-05-29 16:57 UTC
Start Scylla single node, --developer-mode=true
Observe the following periodic messages every 5 seconds:
```
WARN  2020-05-29 19:57:23,022 [shard 0] cdc - Could not retrieve CDC streams with timestamp 2020/03/18 12:56:32: seastar::internal::backtraced<marshal_exception> (marshaling error: read_simple_exactly - size mismatch (expected 8, got 20) Backtrace:   0x301ef3d
  0xdc5be9
  0xdc5df6
  0xdc6041
  0x16f5c4a
  0x16f56b1
  0x16f5999
  0x16f7348
  0x16f5c67
  0x16f67f9
  0x1a370f3
  0x1a37860
  0x2d97030
  0x2d973ae
  0x2dd207d
  0x2d2d855
  0x2d2df4e
  0xc40490
  /lib64/libc.so.6+0x27041
  0xb555ed
```

**Comment by dorlaor** [comment] 2020-05-29 17:19
I saw this too, both on master yesterday and also two weeks ago.

**Comment by kostja** [comment] 2020-05-29 17:31
[Backtrace #0]                                                                                                                              
seastar::internal::backtraced<marshal_exception>::backtraced<seastar::internal::backtraced<marshal_exception>&>(seastar::internal::backtrace
d<marshal_exception>&) at /home/kostja/work/scylla/scylla/seastar/include/seastar/util/backtrace.hh:111                                     
std::__exception_ptr::exception_ptr std::make_exception_ptr<seastar::internal::backtraced<marshal_exception> >(seastar::internal::backtraced
<marshal_exception>) at /usr/include/c++/10/bits/exception_ptr.h:195 (discriminator 4)                                                      
 (inlined by) std::__exception_ptr::exception_ptr seastar::make_backtraced_exception_ptr<marshal_exception, seastar::basic_sstring<char, uns
igned int, 15u, true> >(seastar::basic_sstring<char, unsigned int, 15u, true>&&) at /home/kostja/work/scylla/scylla/seastar/include/seastar/
util/backtrace.hh:139 (discriminator 4)                                                                                                     
void seastar::throw_with_backtrace<marshal_exception, seastar::basic_sstring<char, unsigned int, 15u, true> >(seastar::basic_sstring<char, u
nsigned int, 15u, true>&&) at /home/kostja/work/scylla/scylla/seastar/include/seastar/util/backtrace.hh:155                                 
long read_simple_exactly<long>(std::basic_string_view<signed char, std::char_traits<signed char> >) at /home/kostja/work/scylla/scylla/./typ
es.hh:1130                                                                                                                                  
 (inlined by) deserialize_value<long int> at /home/kostja/work/scylla/scylla/types.cc:1858                                                  
 (inlined by) operator()<long_type_impl> at /home/kostja/work/scylla/scylla/types.cc:1874                                                   
 (inlined by) visit<(anonymous namespace)::deserialize_visitor> at /home/kostja/work/scylla/scylla/concrete_types.hh:221 
abstract_type::deserialize(std::basic_string_view<signed char, std::char_traits<signed char> >) const at /home/kostja/work/scylla/scylla/typ
es.cc:1904
 (inlined by) deserialize_aux at /home/kostja/work/scylla/scylla/types.cc:1761
std::invoke_result<(anonymous namespace)::deserialize_visitor, ascii_type_impl const&>::type visit<(anonymous namespace)::deserialize_visito
r>(abstract_type const&, (anonymous namespace)::deserialize_visitor&&) at /home/kostja/work/scylla/scylla/types.cc:1898
 (inlined by) visit<(anonymous namespace)::deserialize_visitor> at /home/kostja/work/scylla/scylla/concrete_types.hh:241
abstract_type::deserialize(std::basic_string_view<signed char, std::char_traits<signed char> >) const at /home/kostja/work/scylla/scylla/typ
es.cc:1904
 (inlined by) list_type_impl::deserialize(std::basic_string_view<signed char, std::char_traits<signed char> >, cql_serialization_format) con
st at /home/kostja/work/scylla/scylla/types.cc:1331
std::invoke_result<(anonymous namespace)::deserialize_visitor, ascii_type_impl const&>::type visit<(anonymous namespace)::deserialize_visito
r>(abstract_type const&, (anonymous namespace)::deserialize_visitor&&) at /home/kostja/work/scylla/scylla/types.cc:1889
 (inlined by) visit<(anonymous namespace)::deserialize_visitor> at /home/kostja/work/scylla/scylla/concrete_types.hh:219
abstract_type::deserialize(std::basic_string_view<signed char, std::char_traits<signed char> >) const at /home/kostja/work/scylla/scylla/typ
es.cc:1904
std::optional<cdc::topology_description> std::__invoke_impl<std::optional<cdc::topology_description>, db::system_distributed_keyspace::read_
cdc_topology_description(std::chrono::time_point<db_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >, db::system_distributed_key
space::context)::{lambda(seastar::shared_ptr<cql3::untyped_result_set>)#1}, seastar::shared_ptr<cql3::untyped_result_set> >(std::__invoke_ot
her, db::system_distributed_keyspace::read_cdc_topology_description(std::chrono::time_point<db_clock, std::chrono::duration<long, std::ratio
<1l, 1000l> > >, db::system_distributed_keyspace::context)::{lambda(seastar::shared_ptr<cql3::untyped_result_set>)#1}&&, seastar::shared_ptr
<cql3::untyped_result_set>&&) [clone .constprop.0] [clone .isra.0] at /home/kostja/work/scylla/scylla/db/system_distributed_keyspace.cc:303
 (inlined by) __invoke_impl<std::optional<cdc::topology_description>, db::system_distributed_keyspace::read_cdc_topology_description(db_cloc
k::time_point, db::system_distributed_keyspace::context)::<lambda(seastar::shared_ptr<cql3::untyped_result_set>)>, seastar::shared_ptr<cql3:
:untyped_result_set> > at /usr/include/c++/10/bits/invoke.h:60
seastar::continuation<seastar::internal::promise_base_with_type<std::optional<cdc::topology_description> >, seastar::future<seastar::shared_ptr<cql3::untyped_result_set> >::then_impl_nrvo<db::system_distributed_keyspace::read_cdc_topology_description(std::chrono::time_point<db_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >, db::system_distributed_keyspace::context)::{lambda(seastar::shared_ptr<cql3::untyped_result_set>)#1}, seastar::future<std::optional<cdc::topology_description> > >(db::system_distributed_keyspace::read_cdc_topology_description(std::chrono::time_point<db_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >, db::system_distributed_keyspace::context)::{lambda(seastar::shared_ptr<cql3::untyped_result_set>)#1}&&)::{lambda()#1}::operator()() const::{lambda(seastar::internal::promise_base_with_type<std::optional<cdc::topology_description> >&, seastar::future_state<seastar::shared_ptr<cql3::untyped_result_set> >&&)#1}, seastar::shared_ptr<cql3::untyped_result_set> >::run_and_dispose() at /usr/include/c++/10/bits/invoke.h:96
seastar::reactor::run_tasks(seastar::reactor::task_queue&) at /home/kostja/work/scylla/scylla/seastar/src/core/reactor.cc:2151
seastar::reactor::run_some_tasks() at /home/kostja/work/scylla/scylla/seastar/src/core/reactor.cc:2566
seastar::reactor::run_some_tasks() at /home/kostja/work/scylla/scylla/seastar/src/core/reactor.cc:2549
 (inlined by) seastar::reactor::run() at /home/kostja/work/scylla/scylla/seastar/src/core/reactor.cc:2721
seastar::app_template::run_deprecated(int, char**, std::function<void ()>&&) at /home/kostja/work/scylla/scylla/seastar/src/core/app-template.cc:202
seastar::app_template::run(int, char**, std::function<seastar::future<int> ()>&&) at /home/kostja/work/scylla/scylla/seastar/src/core/app-template.cc:115
main at /home/kostja/work/scylla/scylla/main.cc:485

**Comment by kbr-** [comment] 2020-05-29 17:31
Looks like some problem with deserialization of collection-type values, but
I can't reproduce it. Will investigate further on Monday.

pt., 29 maj 2020, 19:19 użytkownik Dor Laor <notifications@github.com>
napisał:

**Comment by slivne** [comment] 2020-05-31 07:22
@kostja did you have any table with cdc enabled - can you please share the schema / what test you ran ?

**Comment by kostja** [comment] 2020-05-31 07:33
@shlomi the bug is in the latest master. Start single node from scratch, no tables at all.

**Comment by kbr-** [comment] 2020-06-01 15:31
It turns out that @kostja was using an old data dir created on Scylla using a commit before PR https://github.com/scylladb/scylla/pull/5676 was merged.

This PR changed the representation of tokens to use int64_t internally. It also changed the way how tokens were serialized inside `system_distributed.cdc_topology_description`: instead of using `utf8_type`, they now use `long_type`.

We've confirmed that by running `describe table system_distributed.cdc_topology_description`. Output:
```
CREATE TABLE system_distributed.cdc_topology_description (
    time timestamp PRIMARY KEY,
    description frozen<list<frozen<tuple<text, frozen<list<blob>>, tinyint>>>>,
    expired timestamp
) WITH ...
```
notice the following line:
```
    description frozen<list<frozen<tuple<text, frozen<list<blob>>, tinyint>>>>,
```
today it would be:
```
    description frozen<list<frozen<tuple<text, frozen<list<blob>>, tinyint>>>>,
```

Although @kostja had experimental enabled when the old data dir was created, we still have a problem.

I investigated further and an even worse problem occurs even if experimental is off when a node is started using the old version of Scylla, then upgraded. The node then refuses to start on the new version, because it tries to insert data into `system_distributed.cdc_topology_description`, but it was created using a different schema.

https://github.com/scylladb/scylla/pull/5676 is a backwards-incompatible change, experimental or not, because `system_distributed.cdc_topology_description` is created regardless of "experimental" flag (it's just not populated if experimental=off).

**Comment by kbr-** [comment] 2020-06-01 15:40
If you:
1. create a cluster pre-4.0 with experimental disabled
2. upgrade to post-4.0 and enable experimental
your cluster will refuse to start :(

**Comment by haaawk** [comment] 2020-06-04 09:00
@kostja Could you please rename the issue to something which describes the real problem? For example "CDC prevents rolling upgrade from pre 4.0 to a newer version with experimental enabled"

**Comment by haaawk** [comment] 2020-06-08 09:30
@slivne @avikivity ping

**Comment by slivne** [comment] 2020-06-10 09:25
fixed by d89b7a0548a9ec60efc5bf456de2396f69341856

**Closed by slivne** 2020-06-10 09:25 UTC
Labels: CDC, bug, showstopper

**Comment by avikivity** [comment] 2020-06-11 15:07
Backported to 4.1.

**Comment by kbr-** [comment] 2020-06-12 08:47
Thanks!
