### ISSUE TITLE
Compaction is computing levels based on the existing sstables size - not based on a set of fixed sizes

### ISSUE THREAD

**Issue by roydahan** [scylladb/scylla#2093] opened 2017-02-19 14:06 UTC
*Installation details*
Scylla version (or git commit hash): 1.6 (with additional logs)

Using sizetiered compaction is supposed to allow multiple compactions to run in parallel given that they are in different levels.

The current code does not use a preset size of files in each level - it computes the levels based on the existing set of sstables. As such the limitation of assuring that we will allow multiple compactions in different sizes to progress is not really guaranteed.

**Comment by nyh** [comment] 2017-02-19 14:50
Can you please elaborate on what you think the problem is?

Parallel compaction is not "guaranteed" - we only do it if we see several compactions of wildly different sizes (e.g., a tiny compaction and a huge compaction). If we have two compactions of approximately the same size (here "approximately" can even up to a some ratio, say 1/10), we do them one after another. Why is this a problem?

If I remember correctly (@raphaelsc wrote that code), the decision of whether to run two compaction jobs in parallel is done using the "size" of the compaction (sum of size of sstables) that has nothing to do with the "levels" of the leveled compaction. Actually, the parallel compaction is only useful for size-tiered

**Comment by roydahan** [comment] 2017-02-19 15:04
Is it based on sizes or on level ?

consider the following sample showing while level computation can very.

We have the following setup:

Level 0 : 1,2,3
Level 1: 4,5
Level 2: 6

We add a single file to level 0 that causes Level 0 files to be compacted to a single file 7 into old level 1 (causing level 0 - to disappear) 

Level 0: 4,5,7
Level 1: 6


So all the file levels have changed.

**Comment by nyh** [comment] 2017-02-19 15:31
In size-tiered compaction, there is no inherent notion of "level" (it's not "leveled compaction").
Maybe you're thinking of leveled compaction?
But your example doesn't look like leveled compaction - in leveled compaction 1,2,3 would be merged with 4,5 to create several new sstables, replacing all of 1,2,3,4,5.

Also, in neither leveled-compaction-levels, nor parallel-compaction-sizes, the disappearance of sstables from one level does not change the higher levels (an sstable doesn't move from level 2 to 1 just because level 1 is empty). So I don't understand the last part of the example either.

I still don't understand what the problem is. Do you see a problem in an actual run? Or is this a  Gedankenexperiment?

**Comment by slivne** [comment] 2017-02-19 16:12
So how do we decide if we will run parallel compactions or not - based on size of files or based on bucket id ?

**Comment by raphaelsc** [comment] 2017-02-20 16:38
On Sun, Feb 19, 2017 at 1:12 PM, Shlomi Livne <notifications@github.com>
wrote:

> So how do we decide if we will run parallel compactions or not - based on
> size of files or based on bucket id ?
>

The former. A compaction job is allowed in parallel to the ongoing ones if
its weight (calculated using the job's sstables) isn't taken. That
heuristic is in the compaction manager.

**Comment by slivne** [comment] 2017-12-03 11:41
closing this

**Closed by slivne** 2017-12-03 11:41 UTC
