### ISSUE TITLE
multi_mvs_on_different_populated_base_tables_test failed: Infinite double value is not supported

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#4469] opened 2019-04-30 11:53 UTC
scylla ee9f3388f6b5e29e682bf78c085b8495ca839602
Seen in [dtest-release/109/testReport/materialized_views_test/TestMaterializedViews/multi_mvs_on_different_populated_base_tables_test](http://jenkins.cloudius-systems.com:8080/view/master/job/scylla-master/job/dtest-release/109/testReport/materialized_views_test/TestMaterializedViews/multi_mvs_on_different_populated_base_tables_test/):
```
Error Message
Nodetool command '/jenkins/workspace/scylla-master/dtest-release/scylla/resources/cassandra/bin/nodetool -h localhost -p 7488 cfstats' failed; exit status: 1; stdout: nodetool: Scylla API server HTTP GET to URL '/column_family/metrics/write_latency/moving_average_histogram/ks:tm_table0_mv_0' failed: Infinite double value is not supported

Stacktrace
  File "/usr/lib64/python2.7/unittest/case.py", line 367, in run
    testMethod()
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/materialized_views_test.py", line 742, in multi_mvs_on_different_populated_base_tables_test
    increase_rows=10, populated_table=True)
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/materialized_views_test.py", line 754, in _multi_mvs_on_different_base_tables_multi_ks
    run_in_parallel(proc_functions)
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/scylla_tools.py", line 846, in run_in_parallel
    results = [task.result() for task in tasks]
  File "/usr/lib/python2.7/site-packages/concurrent/futures/_base.py", line 455, in result
    return self.__get_result()
  File "/usr/lib/python2.7/site-packages/concurrent/futures/thread.py", line 63, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/materialized_views_test.py", line 780, in _multi_mvs_on_different_base_tables
    func()
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/materialized_views_test.py", line 760, in _prefill_base_tables
    base_table.prefill_table(prefill)
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/scylla_tools.py", line 389, in prefill_table
    flush_by_node(self.cluster)
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/scylla_tools.py", line 201, in flush_by_node
    node.flush()
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-ccm/ccmlib/scylla_node.py", line 840, in flush
    self._wait_no_pending_flushes()
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-ccm/ccmlib/scylla_node.py", line 833, in _wait_no_pending_flushes
    result = wait_for(no_pending_flushes, timeout=wait_timeout, step=1.0)
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-ccm/ccmlib/scylla_node.py", line 46, in wait_for
    output = func()
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-ccm/ccmlib/scylla_node.py", line 823, in no_pending_flushes
    stdout, _ = self.nodetool('cfstats')
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-ccm/ccmlib/node.py", line 714, in nodetool
    raise NodetoolError(" ".join(args), exit_status, stdout, stderr)
```

This exception is generated here:
```
sstring formatter::to_json(double d) {
    if (std::isinf(d)) {
        throw out_of_range("Infinite double value is not supported");
```

/cc @eliransin @psarna @nyh

**Comment by eliransin** [comment] 2019-11-28 15:14
Cassandra is outputing null for Infinity,-Infinity,NaN:
```
Connected to Test Cluster at 127.0.0.1:9042.
[cqlsh 5.0.1 | Cassandra 3.0.19 | CQL spec 3.4.0 | Native protocol v4]
...
cqlsh:cycling> select * from test;

 x | y
---+-----------
 1 |  Infinity
 0 |         2
 2 |       NaN
 3 | -Infinity

(4 rows)
cqlsh:cycling> select json * from test;

 [json]
---------------------
 {"x": 1, "y": null}
  {"x": 0, "y": 2.0}
 {"x": 2, "y": null}
 {"x": 3, "y": null}

(4 rows)

```
I will send a patch that does the same.

**Comment by eliransin** [comment] 2019-12-16 15:31
After a closer look, I found out that it is related to our rest API:
`Scylla API server HTTP GET to URL '/column_family/metrics/write_latency/moving_average_histogram/ks:tm_table0_mv_0' failed: Infinite double value is not supported`
I guess it has something to do with the histogram computation.
@amnonh I am starting to look in the to_json of a histogram type to see if it can produce infinite values. Let me know if it sounds familiar or if you already fixed it by any chance.

**Comment by eliransin** [comment] 2019-12-30 08:17
I have added a commit in Seastar that should help us to pinpoint the specific field that is computed to be infinite so we can decide if this value is acceptable. Chances are that we will need to change 
this value prior to generating the Json since changing the json generator itself will need to be 
done in Seastar which involves high risk. The commit that adds the debug information is:
scylladb/seastar@9612a94b8a55e27601d381fbf7837430f695077b

**Comment by bhalevy** [comment] 2020-01-12 08:27
Fix merged in 4b8e2f50030bff83124610e69a8f63dcfeb1d8a5

**Comment by eliransin** [comment] 2020-01-14 09:07
@bhalevy - are you sure it is fixed? If you closed it because of my commit (scylladb/seastar@9612a94

) ,  just be aware that this doesn't fix the issue but will give us more information when it happens again. I believe that this information will be enough for creating a fix.
Is there another commit there that should fix the problem?

**Comment by bhalevy** [comment] 2020-03-01 06:12
For the record, hit again on 3.3: https://jenkins.scylladb.com/view/scylla-3.3/job/scylla-3.3/job/dtest-release/26/testReport/materialized_views_test/TestMaterializedViews/multi_mvs_on_different_populated_base_tables_test/

**Comment by slivne** [comment] 2020-03-24 22:32
@amnonh please have a look its in the rest api metrics

**Comment by bhalevy** [comment] 2020-03-29 12:07
Hit again https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/442/testReport/materialized_views_test/TestMaterializedViews/multi_mvs_on_different_populated_base_tables_test/

**Comment by eliransin** [comment] 2020-03-29 13:52
It seams that only half of my patch-set went in. The part that nests the exceptions and adds field 
values didn't go it because I was expected to fix something. I will fix it and submit it so we will have
the info next time.

**Comment by amnonh** [comment] 2020-04-05 14:17
@slivne can we assign Eliran until it is clear?

**Comment by bhalevy** [comment] 2020-05-05 07:18
Still hitting this.
https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/474/testReport/materialized_views_test/TestMaterializedViews/multi_mvs_on_different_populated_base_tables_test/

ping @slivne @eliransin

**Comment by bhalevy** [comment] 2020-05-26 15:56
Still hit in 4.1
https://jenkins.scylladb.com/view/scylla-4.1/job/scylla-4.1/job/dtest-release/15/testReport/materialized_views_test/TestMaterializedViews/multi_mvs_on_different_populated_base_tables_test/

**Comment by eliransin** [comment] 2020-05-31 06:45
Ahhha, finally I have the field that caused it :smile: 
I will look into it.

**Comment by bhalevy** [comment] 2020-07-06 11:04
@eliransin 
Still fails in 4.1

https://jenkins.scylladb.com/view/scylla-4.1/job/scylla-4.1/job/dtest-release/45/testReport/materialized_views_test/TestMaterializedViews/multi_mvs_on_different_populated_base_tables_test/
```
Traceback (most recent call last):
  File "/usr/lib64/python3.7/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/usr/lib64/python3.7/unittest/case.py", line 645, in run
    testMethod()
  File "/jenkins/workspace/scylla-4.1/dtest-release/scylla-dtest/materialized_views_test.py", line 761, in multi_mvs_on_different_populated_base_tables_test
    increase_rows=10, populated_table=True)
  File "/jenkins/workspace/scylla-4.1/dtest-release/scylla-dtest/materialized_views_test.py", line 773, in _multi_mvs_on_different_base_tables_multi_ks
    run_in_parallel(proc_functions)
  File "/jenkins/workspace/scylla-4.1/dtest-release/scylla-dtest/scylla_tools.py", line 872, in run_in_parallel
    results = [task.result() for task in tasks]
  File "/jenkins/workspace/scylla-4.1/dtest-release/scylla-dtest/scylla_tools.py", line 872, in <listcomp>
    results = [task.result() for task in tasks]
  File "/usr/lib64/python3.7/concurrent/futures/_base.py", line 435, in result
    return self.__get_result()
  File "/usr/lib64/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/lib64/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/jenkins/workspace/scylla-4.1/dtest-release/scylla-dtest/materialized_views_test.py", line 799, in _multi_mvs_on_different_base_tables
    func()
  File "/jenkins/workspace/scylla-4.1/dtest-release/scylla-dtest/materialized_views_test.py", line 779, in _prefill_base_tables
    base_table.prefill_table(prefill)
  File "/jenkins/workspace/scylla-4.1/dtest-release/scylla-dtest/scylla_tools.py", line 415, in prefill_table
    flush_by_node(self.cluster)
  File "/jenkins/workspace/scylla-4.1/dtest-release/scylla-dtest/scylla_tools.py", line 227, in flush_by_node
    node.flush()
  File "/jenkins/workspace/scylla-4.1/dtest-release/scylla-ccm/ccmlib/scylla_node.py", line 1124, in flush
    self._wait_no_pending_flushes()
  File "/jenkins/workspace/scylla-4.1/dtest-release/scylla-ccm/ccmlib/scylla_node.py", line 1117, in _wait_no_pending_flushes
    result = wait_for(no_pending_flushes, timeout=wait_timeout, step=1.0)
  File "/jenkins/workspace/scylla-4.1/dtest-release/scylla-ccm/ccmlib/scylla_node.py", line 51, in wait_for
    output = func()
  File "/jenkins/workspace/scylla-4.1/dtest-release/scylla-ccm/ccmlib/scylla_node.py", line 1107, in no_pending_flushes
    stdout, _ = self.nodetool('cfstats')
  File "/jenkins/workspace/scylla-4.1/dtest-release/scylla-ccm/ccmlib/node.py", line 737, in nodetool
    raise NodetoolError(" ".join(args), exit_status, stdout, stderr)
ccmlib.node.NodetoolError: Nodetool command '/jenkins/workspace/scylla-4.1/dtest-release/scylla/.ccm/scylla-repository/1d9bbbc95771296e6bacb83db44c59ab27b52c80/scylla-tools-java/bin/nodetool -h 127.0.76.3 -p 7376 cfstats' failed; exit status: 1; stdout: nodetool: Scylla API server HTTP GET to URL '/column_family/metrics/write_latency/moving_average_histogram/multi1:tm_table0_mv_0' failed: std::_Nested_exception<std::runtime_error> (Json generation failed for field: meter): std::_Nested_exception<std::runtime_error> (Json generation failed for field: mean_rate): std::out_of_range (Infinite double value is not supported)
See 'nodetool help' or 'nodetool help <command>'.
```

**Comment by eliransin** [comment] 2020-07-12 11:41
@amnonh I would like your insight about that:
The exception reveals the location of the error mean_rate in rate_moving_average which became infinite.
It is generally not a problem, but when you convert this histogram to a json object it is a problem since the json standard don't
say how to convert INF and NAN to json so the library (justifiably) refuses to convert it.
The calculation of this rate is here:
https://github.com/scylladb/scylla/blob/133162346535dd2a6897da9b0e6a5609c369f9e9/utils/histogram.hh#L259-L262
I can think of 2 reasons why it happens:
1. ` _count` is huge - but this looks like the less likely option since if it is true this means there is a failure in the latency clock mechanism. since the test only takes ~1:50 (a little less than 2 minutes), it is almost impossible to accumulate so much time in `_count`.
2. The more likely IMO is the division by `elapsed`, if the value there is small enough it can happen that this causes the rate to skyrocket.

Besides trying to reproduce and print out the values in the calculation (when it becomes infinite) I have a proposed solution:
my proposed solution for that is to clamp the rate value from infinity to max_double.
What do you think?

**Comment by amnonh** [comment] 2020-07-13 06:55
I don't like this direction, from looking at the code I don't see how it can be truly infinite.

someone would need to call the API at a super early stage, but the count is greater than zero.

maybe the steady_clock precision is too low for this stage?

We are talking about the total mean_rate (the one from startup) 
If anything I would check that duration is greater then zero and return zero for these cases, logically, it means
we've looked at the mean rate just as the system started, so it should be zero at this point.

**Comment by bhalevy** [comment] 2020-08-10 07:24
Still happens: https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/575/testReport/materialized_views_test/TestMaterializedViews/multi_mvs_on_different_populated_base_tables_test/

**Comment by bhalevy** [comment] 2020-10-26 06:52
https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/618/testReport/materialized_views_test/TestMaterializedViews/multi_mvs_on_different_populated_base_tables_test/

**Comment by bhalevy** [comment] 2020-11-01 12:07
@eliransin ping, what's the plan for this issue?
It was just hit in https://jenkins.scylladb.com/view/scylla-4.3/job/scylla-4.3/job/dtest-release/1/testReport/materialized_views_test/TestMaterializedViews/multi_mvs_on_different_populated_base_tables_test/

**Closed** 2020-11-04 16:24 UTC
Labels: Backport 4.1, Backport candidate, dtest, materialized-views

**Comment by bhalevy** [comment] 2020-11-23 08:07
@scylladb/scylla-maint ping backport

**Comment by avikivity** [comment] 2022-08-16 13:03
Fix present on all active branches, not backporting.
