### ISSUE TITLE
select count(*) from table not working 

### ISSUE THREAD

**Issue by alokgogate** [scylladb/scylla#3378] opened 2018-04-23 13:38 UTC
Hello 

I have installed scylla db and when I do 
`select count(*) from abc`
or count(*) or count(1) from table I get timeout errors. Rest queries do seem to work

Any suggestion?

**Comment by dorlaor** [comment] 2018-04-23 17:26
Count goes over the entire table. You should increase your timeout in order
to wait for the answer which is
a function of the amount of data you have and cluster speed

**Comment by tzach** [comment] 2018-04-24 10:10
@alokgogate closing this since it's not a bug. Selecting over the entire DB and all nodes will take time.
As @dorlaor suggested, you can increase the client side timer, but it's a short-term solution. Running `select count` is an anti-pattern.
See #1385 for a possible enhancement to improve in this case.

**Closed by tzach** 2018-04-24 10:10 UTC

**Comment by tzach** [comment] 2018-04-24 11:55
The timeout you are getting is most likely from the client
If for example, you are using cqlsh, try using
```
cqlsh --request-timeout=2000
```

**Comment by LavishPatodi** [comment] 2018-04-24 12:45
@tzach  thanks for your quick response it really helped.

**Comment by cc32d9** [comment] 2019-05-08 08:20
But shouldn't it be quick if I specify the partition key in WHERE statement? So far it's timing out as well.

**Comment by avikivity** [comment] 2019-05-08 08:22
How large is your partition?

**Comment by cc32d9** [comment] 2019-05-08 08:41
@avikivity several gigabytes. I just opened #4484 for more details.

**Comment by avikivity** [comment] 2019-05-08 09:29
It's not possible to count 1.6GB worth of data in a few seconds on a single core. Increase your timeouts.
