### ISSUE TITLE
flag provided but not defined: -collector.interrupts

### ISSUE THREAD

**Issue by fggarcia** [scylladb/scylla#4195] opened 2019-02-05 21:42 UTC
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash): 3.0.2-0.20190131.5174b1cd1
Cluster size:
OS (RHEL/CentOS/Ubuntu/AWS AMI): Ubuntu 16.04.4 LTS

*Hardware details (for performance issues)*          Delete if unneeded
Platform (physical/VM/cloud instance type/docker):
Hardware: sockets= cores= hyperthreading= memory=
Disks: (SSD/HDD, count)

after upgrade from 3.0.1 to 3.0.2 and restart server. I don't see some metrics in scylla grafana monitoring.
@amnonh recommend me to see node_exporter service.
this is the output:
```
sudo service node-exporter status
● node-exporter.service - Node Exporter
   Loaded: loaded (/lib/systemd/system/node-exporter.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Tue 2019-02-05 16:10:35 EST; 23min ago
  Process: 1029 ExecStart=/usr/bin/node_exporter --collector.interrupts (code=exited, status=2)
 Main PID: 1029 (code=exited, status=2)

Feb 05 16:10:35 [1]: Started Node Exporter.
Feb 05 16:10:35 [1]: node-exporter.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Feb 05 16:10:35 systemd[1]: node-exporter.service: Unit entered failed state.
Feb 05 16:10:35 systemd[1]: node-exporter.service: Failed with result 'exit-code'.
```

I see this commit: https://github.com/scylladb/scylla/commit/a51878205accdf94f8f85fda8eb6f94f89d0e89c

**Comment by amnonh** [comment] 2019-02-06 06:47
It means you running node_exporter 0.14 with 0.17 flags.
Upgrade your node_exporter

**Comment by slivne** [comment] 2019-02-06 08:16
@amnonh did 3.0.2 force using node_exporter 0.17 while 3.0.1 was flexible and allowed both - I was not aware of this ?

**Comment by amnonh** [comment] 2019-02-06 08:21
there was no change that I know of between 3.0.1 and 3.0.2.

What I see is that the **service file** belongs to 0.17 and what is actually running is 0.14.

I don't know how did it come to this, maybe a machine with old node_exporter when upgrading

**Comment by amnonh** [comment] 2019-02-06 08:33
there are no such limitations.

And that is not the problem, the problem is that node_exporter 0.14 and 0.17 have different command line parameters.

So you cannot use node_exporter 0.14 service file with node_exporter 0.17.

By default, we are installing node_exporter 0.17, but if someone is using node_exporter 0.14, they should use the service file for node_exporter 0.14.

**Comment by slivne** [comment] 2019-02-06 08:41
Can you please try and see if you can reproduce ... start with 2.3 that has node_export 0.14 AFAIK and then upgrade to 3.0.2 and see what happens.

**Comment by amnonh** [comment] 2019-02-06 09:28
that could be an issue, but the error is upgrading from 3.0.1 to 3.0.2

**Comment by slivne** [comment] 2019-02-06 11:19
@amnonh please test it out - we need to understand whats going on even if its not the exact user story ...

He may have started from 2.3 --> 3.0 --> 3.0.1 --> 3.0.2.

**Comment by fggarcia** [comment] 2019-02-06 14:16
Hi @slivne @amnonh 
does scylla has an script to upgrade node_exporter? or do i have to install it manually?

I see here: https://github.com/scylladb/scylla/blob/904db433d9120dab6b7ba9f589a3544c62819fe0/dist/common/scripts/node_exporter_install

Only verify that exists node_exporter, not verify version.

Thanks

**Comment by amnonh** [comment] 2019-02-06 14:41
@fggarcia 
Scylla does not have an upgrade script for node_exporter.

Scylla 3.0 comes with an installation script for node_exporter 0.17.
You can delete the old directory and run the script again

**Comment by fggarcia** [comment] 2019-02-06 14:50
Yes, I will do that

**Comment by amnonh** [comment] 2019-02-06 15:10
I have opened #4197

**Comment by slivne** [comment] 2019-02-07 10:31
closing this issue we found the source - the user should upgrade to node_exporter 0.17

**Closed by slivne** 2019-02-07 10:31 UTC

**Comment by gnumoreno** [comment] 2019-04-25 19:11
Adding some troubleshooting steps for people coming from google with the same problem:

Check node_exporter version
`node_exporter --version`

Delete the files from old node_exporter including the symlinks: 
```
ls -l /usr/bin/node_exporter /usr/bin/prometheus-node_exporter
rm -rf /usr/bin/node_exporter /usr/bin/prometheus-node_exporter /usr/lib/scylla/Prometheus/node_exporter/node_exporter-0.14.0.linux-amd64/node_exporter
```

Use our script to reinstall node_exporter:
```
grep ^VERSION /usr/lib/scylla/node_exporter_install
/usr/lib/scylla/node_exporter_install
```

Start node-exporter service and check the logs:
```
sudo systemctl start node-exporter
journalctl -u node-exporter
```
