### ISSUE TITLE
Major Compaction cause Over Size SSTables and Merge into lv0 in LeveledCompaction

### ISSUE THREAD

**Issue by ban4785** [scylladb/scylla#3354] opened 2018-04-12 08:09 UTC
*Installation details*
Scylla version (or git commit hash): 2.1.1
Cluster size: 1
OS (RHEL/CentOS/Ubuntu/AWS AMI): CentOS 7.2

*Hardware details (for performance issues)*          Delete if unneeded
Platform (physical/VM/cloud instance type/docker): physical
Hardware: sockets= cores= hyperthreading= memory= 8vCore
Disks: (SSD/HDD, count) 440G SSD 

i know that Default LeveledCompaction SSTables not over 160M bytes and
Major Compaction doesn't set to All SSTables lv0.
below is SSTable list before Major Compaction
![leveled1](https://user-images.githubusercontent.com/20348151/38663488-714d0d18-3e26-11e8-9bb6-9076f2544b94.png)

commanded `nodetool compact {keyspace}` and got about 1G SSTables.
SSTable number is 8, it's eqaul to smp parameter
![leveled2](https://user-images.githubusercontent.com/20348151/38663545-9804e368-3e26-11e8-8bd4-c24fa57939ca.png)

this is /var/log/messages with Compaction info
_Apr 12 15:23:53 dbtest04 scylla: [shard 7] compaction - Compacted 7 sstables to [/data1/scylla/data/sems/sems_data-7dd745303e1711e8976e000000000003/sems-sems_data-ka-359-Data.db:level=0, ]. 948185146 bytes to 948015202 (~99% of original) in 45879ms = 19.71MB/s. ~5713 total partitions merged to 5609._

....

i found all SSTables Level set to 0.
below is information with sstablemetadata.
_SSTable: /data1/scylla/data/sems/sems_data-7dd745303e1711e8976e000000000003/sems-sems_data-ka-359
Partitioner: org.apache.cassandra.dht.Murmur3Partitioner
Bloom Filter FP chance: 0.010000
Minimum timestamp: 1523513190632682
Maximum timestamp: 1523514075262696
SSTable max local deletion time: 1526192475
Compression ratio: 0.1846553511565777
Estimated droppable tombstones: 0.0
SSTable Level: 0
Repaired at: 0_

after that, i generated Additional Data, One SSTable Seperated to Several SSTables and lv set to 1.
this is /var/log/messages with Compaction
_Apr 12 15:30:02 dbtest04 scylla: [shard 7] compaction - Compacted 2 sstables to [/data1/scylla/data/sems/sems_data-7dd745303e1711e8976e000000000003/sems-sems_data-ka-375-Data.db:level=1, /data1/scylla/data/sems/sems_data-7dd745303e1711e8976e000000000003/sems-sems_data-ka-383-Data.db:level=1, /data1/scylla/data/sems/sems_data-7dd745303e1711e8976e000000000003/sems-sems_data-ka-391-Data.db:level=1, /data1/scylla/data/sems/sems_data-7dd745303e1711e8976e000000000003/sems-sems_data-ka-399-Data.db:level=1, /data1/scylla/data/sems/sems_data-7dd745303e1711e8976e000000000003/sems-sems_data-ka-407-Data.db:level=1, /data1/scylla/data/sems/sems_data-7dd745303e1711e8976e000000000003/sems-sems_data-ka-415-Data.db:level=1, ]. 1007138642 bytes to 1007067118 (~99% of original) in 65128ms = 14.75MB/s. ~6027 total partitions merged to 6027._

i can't understand why Major Compaction in LeveledStrategy cause merging One SSTable like SizeStrategy.

**Comment by avikivity** [comment] 2018-04-12 08:25
Duplicate of #1431.

**Closed by avikivity** 2018-04-12 08:25 UTC
