### ISSUE TITLE
ScyllaDB 1.7 crash "Assertion `!_in_batch' failed."

### ISSUE THREAD

**Issue by rdzimmer** [scylladb/scylla#2437] opened 2017-06-01 17:47 UTC
*Installation details*
Scylla version (or git commit hash): 1.7.0-0.20170519.25607ab
Cluster size: 4 nodes, 50GB of test data each (so far)
OS (RHEL/CentOS/Ubuntu/AWS AMI): RHEL 7.3, running ScyllaDB inside docker 17.04.0-ce

*Hardware details (for performance issues)*
Platform (physical/VM/cloud instance type/docker): physical
Hardware: sockets= cores= hyperthreading= memory= 24 core 64GB
Disks: (SSD/HDD, count) 2 SSDs (also on a 12HDD RAID 10 system)

I am seeing ScyllaDB crash every 2~4 hours while testing a KairosDB TSDB workload.  The workload is ~2.4 million unique KairosDB metric datapoints per minute.  ScyllaDB restarts itself after the crash.  Here is the log output.  I can try to turn up logging if needed.

```
scylla: /jenkins/workspace/scylla-1.7-centos-rpm/scylla/build/rpmbuild/BUILD/scylla-1.7.0/seastar/core/iostream.hh:210: output_stream<CharType>::~output_stream() [with CharType = char]: Assertion `!_in_batch' failed.
Aborting on shard 10.
Backtrace:
  0x00000000004e05fa
  0x00000000004e0703
  0x00007f677626136f
  0x00007f6775ec61d6
  0x00007f6775ec78c7
  0x00007f6775ebf145
  0x00007f6775ebf1f1
  0x0000000000de1fad
  0x0000000000de2083
  0x00000000004e206f
  0x0000000000531bc2
  0x0000000000533400
  0x000000000058ed2d
  0x00007f6776259dc4
  0x00007f6775f8873c
2017-06-01 17:05:19,970 INFO exited: scylla (terminated by SIGABRT (core dumped); not expected)
2017-06-01 17:05:20,976 INFO spawned: 'scylla' with pid 127

```

**Comment by duarten** [comment] 2017-06-01 18:59
I got this backtrace:

```
output_stream<char>::~output_stream() at /usr/src/debug/scylla-1.7.0/seastar/core/iostream.hh:210
 (inlined by) thrift_server::connection::~connection() at /usr/src/debug/scylla-1.7.0/thrift/server.cc:110
 (inlined by) operator() at /usr/src/debug/scylla-1.7.0/thrift/server.cc:188
 (inlined by) do_void_futurize_apply<thrift_server::do_accepts(int, bool)::<lambda(connected_socket, socket_address)> mutable::<lambda(future<>)>, future<> > at /usr/src/debug/scylla-1.7.0/seastar/core/future.hh:1212
apply<thrift_server::do_accepts(int, bool)::<lambda(connected_socket, socket_address)> mutable::<lambda(future<>)>, future<> > at /usr/src/debug/scylla-1.7.0/seastar/core/future.hh:1260
 (inlined by) operator()<future_state<> > at /usr/src/debug/scylla-1.7.0/seastar/core/future.hh:911
 (inlined by) run at /usr/src/debug/scylla-1.7.0/seastar/core/future.hh:390
reactor::run_tasks(circular_buffer<std::unique_ptr<task, std::default_delete<task> >, std::allocator<std::unique_ptr<task, std::default_delete<task> > > >&) at /usr/src/debug/scylla-1.7.0/seastar/core/reactor.cc:2025
reactor::run() at /usr/src/debug/scylla-1.7.0/seastar/core/reactor.cc:2467
smp::configure(boost::program_options::variables_map)::{lambda()#3}::operator()() const [clone .constprop.4079] at /usr/src/debug/scylla-1.7.0/seastar/core/reactor.cc:3396
std::function<void ()>::operator()() const at /opt/scylladb/include/c++/5.3.1/functional:2271
 (inlined by) posix_thread::start_routine(void*) at /usr/src/debug/scylla-1.7.0/seastar/core/posix.cc:50
```

**Comment by duarten** [comment] 2017-06-01 19:07
I think this is a duplicate of #499.

**Closed** 2017-06-02 05:15 UTC

**Comment by duarten** [comment] 2017-06-02 15:03
@rdzimmer I've uploaded 1.7 packages containing the fixes. Please [try them out](https://s3.amazonaws.com/scylladb/scylla-1.7-thrift-fixes.tar.gz).

**Comment by rdzimmer** [comment] 2017-06-02 15:12
@duarten Thanks!  Would they also be in the docker scylladb/scylla-nightly image?  That's quicker for me to pull in.

**Comment by duarten** [comment] 2017-06-02 18:54
@rdzimmer Yes, they will be (in a few hours).

**Comment by rdzimmer** [comment] 2017-06-05 19:00
I've downloaded the latest scylladb-nightly:
```
REPOSITORY                                                                       TAG                 IMAGE ID            CREATED             SIZE
scylladb/scylla-nightly                                                          latest              060d4bff0411        32 hours ago        1.07GB
```
However, the version still shows as from May 21st.  Is this expected with the nightly docker image?
```
/usr/bin/scylla --version
666.development-0.20170521.c8cb3d6
```
I'm still seeing crashes/restarts.  My logs wrapped, but once I get an error message I'll post it.

**Comment by duarten** [comment] 2017-06-05 22:26
@rdzimmer We've made some changes to our rpm build pipeline and it's causing some grief; I'll let you know when that's fixed and the nightly docker image is updated.

**Comment by avikivity** [comment] 2017-06-05 22:37
The rpm did get built; but I have no idea how to trigger the docker build.

**Comment by duarten** [comment] 2017-06-05 22:56
Oh! According to @penberg, it's automatic?

**Comment by avikivity** [comment] 2017-06-06 05:16
According to docker, it hasn't run.

**Comment by duarten** [comment] 2017-06-06 09:26
@rdzimmer scylladb/scylla-nightly has been updated with an image containing the bug fix.

**Comment by avikivity** [comment] 2017-06-06 10:08
Oh, I was looking at the wrong repo.

**Comment by rdzimmer** [comment] 2017-06-06 11:39
Thanks!  Running the new level now.  Will let you know if I hit the issue again:
`666.development-0.20170605.f5679e0`

**Comment by rdzimmer** [comment] 2017-06-06 19:35
So far so good, 8 hours without a crash.  I'll close this out after running overnight.  Thanks!

**Comment by duarten** [comment] 2017-06-06 19:41
Great! Thanks for letting us know.
