### ISSUE TITLE
Verify conditional batch size

### ISSUE THREAD

**Issue by kostja** [scylladb/scylla#5810] opened 2020-02-14 11:00 UTC
[verify_batch_size()](https://github.com/scylladb/scylla/blob/master/cql3/statements/batch_statement.cc#L222) is not called for conditional batches, as a result scylla does not:
- print a warning for an ovresized batch (>5180 statements)
- print error for huge batches (>65535 statements)
- reserve memory for batch

Discovered by stress testing/code inspection.

**Comment by gleb-cloudius** [comment] 2020-02-14 11:34
verify_batch_size() warns only for multiple mutations, Conditional batch
always have one. I do not see the problem here.

--
			Gleb.

**Comment by slivne** [comment] 2020-02-20 10:36
@kostja can we close this

**Comment by kostja** [comment] 2020-02-20 13:40
No, we still need to warn if there are a lot of statements against the same partition.

**Comment by gleb-cloudius** [comment] 2020-02-20 13:43
On Thu, Feb 20, 2020 at 05:40:15AM -0800, Konstantin Osipov wrote:
> No, we still need to warn if there are a lot of statements against the same partition.
> 
Why? Does Cassandra do it?

--
			Gleb.

**Comment by kostja** [comment] 2020-02-20 14:12
No, but it may be a bug in Cassandra. There are two limits: soft and hard. Soft is ~5180 statements hard is 65535 statements. We're checking for neither.

**Comment by gleb-cloudius** [comment] 2020-02-20 15:55
On Thu, Feb 20, 2020 at 06:12:49AM -0800, Konstantin Osipov wrote:
> No, but it may be a bug in Cassandra. There are two limits: soft and hard. Soft is ~5180 statements hard is 65535 statements. We're checking for neither. 
> 
It is definitely not a bug, but a concious decision:
https://issues.apache.org/jira/browse/CASSANDRA-10876

--
			Gleb.

**Closed** 2020-03-10 08:40 UTC
Labels: lwt
