### ISSUE TITLE
mutation_partition::apply(tombstone) is lazy

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylla#652] opened 2015-12-13 15:36 UTC
It only applies the tombstone, but doesn't drop existing rows.  Doing so would make it conserve memory, at the expense of making it slower.

**Comment by tgrabiec** [comment] 2017-04-04 17:28
The deferral of compaction comes from the current trade-off of preferring fast writes over reads and memory conservation (typical for log-structured merge tree). The cost of compaction is deferred to reads and async compaction process. This applies to both memtables and sstables. Although for memtables the overhead of doing compaction is not as big as for on-disk storage, it still exists. When applying partition tombstone, in the general case we would have to walk through all data to compact it.

**Comment by duarten** [comment] 2017-04-04 18:28
A compromise would be to compact at the row level for deletable_row::apply_reversibly(), deletable_row::apply() and clustering_row::apply() (considering only what's in memory).

**Comment by avikivity** [comment] 2017-12-20 09:24
I think it's likely that a delete would actually delete the data, so performing it eagerly is worthwhile. We save memory, more work during reads, the memtable flush, and compaction.

We'd only be gaining something if someone wrote lots of older tombstones, but that's not common. In that case, walking over all of the cells performs no useful work.

**Comment by tgrabiec** [comment] 2017-12-20 09:36
For large partitions, compacting them eagerly would result in high latency. We could kick-off background compaction process, like for sstables. 

For cost-of-reads, we could do something weaker: https://github.com/scylladb/scylla/issues/2252

**Comment by tgrabiec** [comment] 2020-07-14 10:04
@kostja @avikivity @gleb-cloudius This could improve efficiency of the raft-log-in-system-table solution, where we have frequent deletes and the live set size is small.

**Comment by avikivity** [comment] 2020-07-14 10:50
Also Paxos

**Comment by avikivity** [comment] 2020-07-14 10:53
Perhaps `mutation_cleaner::compact_gently(partition_version, optional<clustering_range>)`

**Comment by vladzcloudius** [comment] 2020-12-28 16:08
@amihayday @eliransin FYI

**Comment by nyh** [comment] 2022-02-17 23:19
#777 is a duplicate of this issue, with another example.

**Comment by avikivity** [comment] 2022-06-08 13:41
Not backporting, significant change, and not a regression.

**Comment by avikivity** [comment] 2022-06-14 15:24
Reopened by 5129280f45358962f61a411bd1cf2e73d5c542fe

**Closed** 2022-06-16 00:33 UTC
Labels: performance

**Comment by avikivity** [comment] 2022-07-03 11:40
Not a regression, and quite a large change. So not backporting.
