### ISSUE TITLE
Frequent Restart of Scylla DB

### ISSUE THREAD

**Issue by virenderdubey** [scylladb/scylla#4530] opened 2019-06-07 11:49 UTC
We are getting frequent restart of the scylladb process, but unable to found the root cause. 
Below are the latest error trace:

**Error Trace**
Jun  7 15:19:02 m-core-scylladb-4 scylla: scylla: cache_flat_mutation_reader.hh:417: void cache::cache_flat_mutation_reader::maybe_add_to_cache(const mutation_fragment&): Assertion `mf.is_clustering_row()' failed.
Jun  7 15:19:02 m-core-scylladb-4 scylla: Aborting on shard 6.
Jun  7 15:19:02 m-core-scylladb-4 scylla: Backtrace:
Jun  7 15:19:02 m-core-scylladb-4 scylla: 0x00000000006887c2
Jun  7 15:19:02 m-core-scylladb-4 scylla: 0x00000000005a38bc
Jun  7 15:19:02 m-core-scylladb-4 scylla: 0x00000000005a3b65
Jun  7 15:19:02 m-core-scylladb-4 scylla: 0x00000000005a3c13
Jun  7 15:19:02 m-core-scylladb-4 scylla: /lib64/libpthread.so.0+0x000000000000f6cf
Jun  7 15:19:02 m-core-scylladb-4 scylla: /lib64/libc.so.6+0x0000000000036276
Jun  7 15:19:02 m-core-scylladb-4 scylla: /lib64/libc.so.6+0x0000000000037967
Jun  7 15:19:02 m-core-scylladb-4 scylla: /lib64/libc.so.6+0x000000000002f095
Jun  7 15:19:02 m-core-scylladb-4 scylla: /lib64/libc.so.6+0x000000000002f141
Jun  7 15:19:02 m-core-scylladb-4 scylla: 0x000000000148e580
Jun  7 15:19:02 m-core-scylladb-4 scylla: 0x00000000014910c6
Jun  7 15:19:02 m-core-scylladb-4 scylla: 0x000000000149361a
Jun  7 15:19:02 m-core-scylladb-4 scylla: 0x0000000001494ce2
Jun  7 15:19:02 m-core-scylladb-4 scylla: 0x0000000001493c85
Jun  7 15:19:02 m-core-scylladb-4 scylla: 0x0000000001706e47
Jun  7 15:19:02 m-core-scylladb-4 scylla: 0x00000000014373af
Jun  7 15:19:02 m-core-scylladb-4 scylla: 0x0000000001466a31
Jun  7 15:19:02 m-core-scylladb-4 scylla: 0x000000000146adf0
Jun  7 15:19:02 m-core-scylladb-4 scylla: 0x0000000000584c76
Jun  7 15:19:02 m-core-scylladb-4 scylla: 0x0000000000584e31
Jun  7 15:19:02 m-core-scylladb-4 scylla: 0x00000000006524bf
Jun  7 15:19:02 m-core-scylladb-4 scylla: 0x00000000006556a5
Jun  7 15:19:02 m-core-scylladb-4 scylla: 0x000000000073d54d
Jun  7 15:19:02 m-core-scylladb-4 scylla: /lib64/libpthread.so.0+0x0000000000007e24
Jun  7 15:19:02 m-core-scylladb-4 scylla: /lib64/libc.so.6+0x00000000000febac
Jun  7 15:19:05 m-core-scylladb-4 systemd-coredump: Removed old coredump core.scylla.993.420d63ae1030401eb868d2671df2e0e7.11263.1559893870000000.
Jun  7 15:22:35 m-core-scylladb-4 systemd: scylla-server.service: main process exited, code=killed, status=6/ABRT
Jun  7 15:22:35 m-core-scylladb-4 systemd: Stopped Run Scylla Housekeeping daily mode.
Jun  7 15:22:35 m-core-scylladb-4 systemd: Stopping Run Scylla Housekeeping daily mode.
Jun  7 15:22:35 m-core-scylladb-4 systemd: Stopped Run Scylla Housekeeping restart mode.
Jun  7 15:22:35 m-core-scylladb-4 systemd: Stopping Run Scylla Housekeeping restart mode.
Jun  7 15:22:37 m-core-scylladb-4 systemd: Unit scylla-server.service entered failed state.
Jun  7 15:22:37 m-core-scylladb-4 systemd: scylla-server.service failed.
Jun  7 15:22:37 m-core-scylladb-4 systemd: scylla-server.service holdoff time over, scheduling restart.
Jun  7 15:22:37 m-core-scylladb-4 systemd: Stopping Scylla JMX...
Jun  7 15:22:38 m-core-scylladb-4 systemd: scylla-jmx.service: main process exited, code=exited, status=143/n/a
Jun  7 15:22:38 m-core-scylladb-4 systemd: Unit scylla-jmx.service entered failed state.
Jun  7 15:22:38 m-core-scylladb-4 systemd: scylla-jmx.service failed.
Jun  7 15:22:38 m-core-scylladb-4 systemd: Starting Scylla Server...

**Installation details**
Scylla version: 2.3.0
Cluster size: 2 AZ, 3 node/AZ
OS (RHEL/CentOS/Ubuntu/AWS AMI): CentOS 7

* Core DUMP*
http://upload.scylladb.com/af76f9c5-55db-4761-bef8-032dc576f6d1/core.scylla.993.420d63ae1030401eb868d2671df2e0e7.11658.1559900942000000.xz

**Comment by dorlaor** [comment] 2019-06-07 16:36
Thanks for the report, it's a bug - we have an assert there.
Thanks for uploading the core, it should be enough for the developers,
however, getting
the table schema will be nice (you can rename the fields for privacy).

Note that 2.3.0 is old, almost end-of-life plus there were patch releases
for it, soon 3.1 will be released
and will make 2.3.x expire so I recommend an upgrade regardless.

**Comment by virenderdubey** [comment] 2019-06-08 17:12
We have some plan to upgrade the version, but it will still take some more time(3-4 months),till that we are running with same version only.

**Below is the Schema Detail:**
CREATE KEYSPACE <keyspace1> WITH replication = {'class': 'NetworkTopologyStrategy', 'ap-south-1a': '3', 'ap-south-1b': '3'}  AND durable_writes = true;

CREATE TABLE <keyspace_name>.<table_name> (
    persistence_id text,
    tag text,
    offset timeuuid,
    sequence_nr bigint,
    tag_pid_sequence_nr bigint,
    PRIMARY KEY (persistence_id, tag)
) WITH CLUSTERING ORDER BY (tag ASC)
    AND bloom_filter_fp_chance = 0.01
    AND caching = {'keys': 'ALL', 'rows_per_partition': 'ALL'}
    AND comment = ''
    AND compaction = {'class': 'SizeTieredCompactionStrategy'}
    AND compression = {}
    AND crc_check_chance = 1.0
    AND dclocal_read_repair_chance = 0.1
    AND default_time_to_live = 0
    AND gc_grace_seconds = 864000
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair_chance = 0.0
    AND speculative_retry = '99.0PERCENTILE';

CREATE TABLE <keyspace_name>.<table_name> (
    tag_name text,
    timebucket bigint,
    timestamp timeuuid,
    persistence_id text,
    tag_pid_sequence_nr bigint,
    event blob,
    event_manifest text,
    meta blob,
    meta_ser_id int,
    meta_ser_manifest text,
    sequence_nr bigint,
    ser_id int,
    ser_manifest text,
    writer_uuid text,
    PRIMARY KEY ((tag_name, timebucket), timestamp, persistence_id, tag_pid_sequence_nr)
) WITH CLUSTERING ORDER BY (timestamp ASC, persistence_id ASC, tag_pid_sequence_nr ASC)
    AND bloom_filter_fp_chance = 0.01
    AND caching = {'keys': 'ALL', 'rows_per_partition': 'ALL'}
    AND comment = ''
    AND compaction = {'bucket_high': '1.5', 'bucket_low': '0.5', 'class': 'SizeTieredCompactionStrategy', 'enabled': 'true', 'max_threshold': '32', 'min_sstable_size': '50', 'min_threshold': '4', 'tombstone_compaction_interval': '86400', 'tombstone_threshold': '0.2', 'unchecked_tombstone_compaction': 'false'}
    AND compression = {}
    AND crc_check_chance = 1.0
    AND dclocal_read_repair_chance = 0.1
    AND default_time_to_live = 0
    AND gc_grace_seconds = 864000
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair_chance = 0.0
    AND speculative_retry = '99.0PERCENTILE';

CREATE TABLE <keyspace_name>.<table_name> (
    persistence_id text,
    partition_nr bigint,
    sequence_nr bigint,
    timestamp timeuuid,
    timebucket text,
    event blob,
    event_manifest text,
    message blob,
    meta blob,
    meta_ser_id int,
    meta_ser_manifest text,
    ser_id int,
    ser_manifest text,
    tags set<text>,
    used boolean static,
    writer_uuid text,
    PRIMARY KEY ((persistence_id, partition_nr), sequence_nr, timestamp, timebucket)
) WITH CLUSTERING ORDER BY (sequence_nr ASC, timestamp ASC, timebucket ASC)
    AND bloom_filter_fp_chance = 0.01
    AND caching = {'keys': 'ALL', 'rows_per_partition': 'ALL'}
    AND comment = ''
    AND compaction = {'bucket_high': '1.5', 'bucket_low': '0.5', 'class': 'SizeTieredCompactionStrategy', 'enabled': 'true', 'max_threshold': '32', 'min_sstable_size': '50', 'min_threshold': '4', 'tombstone_compaction_interval': '86400', 'tombstone_threshold': '0.2', 'unchecked_tombstone_compaction': 'false'}
    AND compression = {}
    AND crc_check_chance = 1.0
    AND dclocal_read_repair_chance = 0.1
    AND default_time_to_live = 0
    AND gc_grace_seconds = 864000
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair_chance = 0.0
    AND speculative_retry = '99.0PERCENTILE';

CREATE TABLE <keyspace_name>.<table_name> (
    persistence_id text PRIMARY KEY,
    sequence_nr bigint
) WITH bloom_filter_fp_chance = 0.01
    AND caching = {'keys': 'ALL', 'rows_per_partition': 'ALL'}
    AND comment = ''
    AND compaction = {'class': 'SizeTieredCompactionStrategy'}
    AND compression = {}
    AND crc_check_chance = 1.0
    AND dclocal_read_repair_chance = 0.1
    AND default_time_to_live = 0
    AND gc_grace_seconds = 864000
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair_chance = 0.0
    AND speculative_retry = '99.0PERCENTILE';

CREATE TABLE <keyspace_name>.<table_name> (
    persistence_id text PRIMARY KEY,
    deleted_to bigint,
    properties map<text, text>
) WITH bloom_filter_fp_chance = 0.01
    AND caching = {'keys': 'ALL', 'rows_per_partition': 'ALL'}
    AND comment = ''
    AND compaction = {'class': 'SizeTieredCompactionStrategy'}
    AND compression = {}
    AND crc_check_chance = 1.0
    AND dclocal_read_repair_chance = 0.1
    AND default_time_to_live = 0
    AND gc_grace_seconds = 864000
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair_chance = 0.0
    AND speculative_retry = '99.0PERCENTILE';

CREATE KEYSPACE <keyspace2> WITH replication = {'class': 'NetworkTopologyStrategy', 'ap-south-1a': '3', 'ap-south-1b': '3'}  AND durable_writes = true;

CREATE TABLE <keyspace_name>.<table_name> (
    ip text,
    booking_id text,
    created_at timestamp,
    PRIMARY KEY (ip, booking_id)
) WITH CLUSTERING ORDER BY (booking_id ASC)
    AND bloom_filter_fp_chance = 0.01
    AND caching = {'keys': 'ALL', 'rows_per_partition': 'ALL'}
    AND comment = ''
    AND compaction = {'class': 'SizeTieredCompactionStrategy'}
    AND compression = {}
    AND crc_check_chance = 1.0
    AND dclocal_read_repair_chance = 0.1
    AND default_time_to_live = 0
    AND gc_grace_seconds = 864000
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair_chance = 0.0
    AND speculative_retry = '99.0PERCENTILE';

CREATE TABLE <keyspace_name>.<table_name> (
    tenant text,
    activity_name text,
    activity_version int,
    api text,
    booking_initials text,
    created_at timestamp,
    data_ref_script text,
    is_deleted boolean,
    is_suspended boolean,
    lobs text,
    max_rps int,
    states text,
    updated_at timestamp,
    validation_script text,
    PRIMARY KEY ((tenant, activity_name), activity_version)
) WITH CLUSTERING ORDER BY (activity_version ASC)
    AND bloom_filter_fp_chance = 0.01
    AND caching = {'keys': 'ALL', 'rows_per_partition': 'ALL'}
    AND comment = ''
    AND compaction = {'class': 'SizeTieredCompactionStrategy'}
    AND compression = {}
    AND crc_check_chance = 1.0
    AND dclocal_read_repair_chance = 0.1
    AND default_time_to_live = 0
    AND gc_grace_seconds = 864000
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair_chance = 0.0
    AND speculative_retry = '99.0PERCENTILE';

CREATE TABLE <keyspace_name>.<table_name> (
    year int,
    wakeup_time timestamp,
    booking_id text,
    tenant text,
    activity_name text,
    activity_state text,
    activity_version int,
    created_at timestamp,
    end_time timestamp,
    meta_data text,
    PRIMARY KEY (year, wakeup_time, booking_id, tenant, activity_name, activity_state, activity_version)
) WITH CLUSTERING ORDER BY (wakeup_time ASC, booking_id ASC, tenant ASC, activity_name ASC, activity_state ASC, activity_version ASC)
    AND bloom_filter_fp_chance = 0.01
    AND caching = {'keys': 'ALL', 'rows_per_partition': 'ALL'}
    AND comment = ''
    AND compaction = {'class': 'SizeTieredCompactionStrategy'}
    AND compression = {}
    AND crc_check_chance = 1.0
    AND dclocal_read_repair_chance = 0.1
    AND default_time_to_live = 0
    AND gc_grace_seconds = 864000
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair_chance = 0.0
    AND speculative_retry = '99.0PERCENTILE';

CREATE TABLE <keyspace_name>.<table_name> (
    booking_id text,
    tenant text,
    activity_name text,
    activity_state text,
    activity_version int,
    meta_data text,
    created_at timestamp,
    is_completed boolean,
    message text,
    PRIMARY KEY (booking_id, tenant, activity_name, activity_state, activity_version, meta_data, created_at)
) WITH CLUSTERING ORDER BY (tenant ASC, activity_name ASC, activity_state ASC, activity_version ASC, meta_data ASC, created_at ASC)
    AND bloom_filter_fp_chance = 0.01
    AND caching = {'keys': 'ALL', 'rows_per_partition': 'ALL'}
    AND comment = ''
    AND compaction = {'class': 'SizeTieredCompactionStrategy'}
    AND compression = {}
    AND crc_check_chance = 1.0
    AND dclocal_read_repair_chance = 0.1
    AND default_time_to_live = 0
    AND gc_grace_seconds = 864000
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair_chance = 0.0
    AND speculative_retry = '99.0PERCENTILE';

CREATE TABLE <keyspace_name>.<table_name> (
    booking_id text,
    tenant text,
    activity_name text,
    activity_state text,
    activity_version int,
    meta_data text,
    created_at timestamp,
    dependent_state text,
    end_time timestamp,
    event_status text,
    execution_type text,
    updated_at timestamp,
    wakeup_time timestamp,
    PRIMARY KEY (booking_id, tenant, activity_name, activity_state, activity_version, meta_data)
) WITH CLUSTERING ORDER BY (tenant ASC, activity_name ASC, activity_state ASC, activity_version ASC, meta_data ASC)
    AND bloom_filter_fp_chance = 0.01
    AND caching = {'keys': 'ALL', 'rows_per_partition': 'ALL'}
    AND comment = ''
    AND compaction = {'class': 'SizeTieredCompactionStrategy'}
    AND compression = {}
    AND crc_check_chance = 1.0
    AND dclocal_read_repair_chance = 0.1
    AND default_time_to_live = 0
    AND gc_grace_seconds = 864000
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair_chance = 0.0
    AND speculative_retry = '99.0PERCENTILE';

CREATE KEYSPACE <keyspace3> WITH replication = {'class': 'NetworkTopologyStrategy', 'ap-south-1a': '3', 'ap-south-1b': '3'}  AND durable_writes = true;

CREATE TABLE <keyspace_name>.<table_name> (
    persistence_id text,
    sequence_nr bigint,
    meta blob,
    meta_ser_id int,
    meta_ser_manifest text,
    ser_id int,
    ser_manifest text,
    snapshot blob,
    snapshot_data blob,
    timestamp bigint,
    PRIMARY KEY (persistence_id, sequence_nr)
) WITH CLUSTERING ORDER BY (sequence_nr DESC)
    AND bloom_filter_fp_chance = 0.01
    AND caching = {'keys': 'ALL', 'rows_per_partition': 'ALL'}
    AND comment = ''
    AND compaction = {'bucket_high': '1.5', 'bucket_low': '0.5', 'class': 'SizeTieredCompactionStrategy', 'enabled': 'true', 'max_threshold': '32', 'min_sstable_size': '50', 'min_threshold': '4', 'tombstone_compaction_interval': '86400', 'tombstone_threshold': '0.2', 'unchecked_tombstone_compaction': 'false'}
    AND compression = {}
    AND crc_check_chance = 1.0
    AND dclocal_read_repair_chance = 0.1
    AND default_time_to_live = 0
    AND gc_grace_seconds = 864000
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair_chance = 0.0
    AND speculative_retry = '99.0PERCENTILE';

**Comment by glommer** [comment] 2019-06-10 13:03
Seems like a dup of https://github.com/scylladb/scylla/issues/3782 , and to the best of my knowledge we don't yet have a fix. 

In that bug, @tgrabiec added some special builds that should catch the problem sooner, but the original reporter never tried. Would it be possible for you to try ?

**Comment by virenderdubey** [comment] 2019-06-11 06:44
We are using scylla since OCT-2018 on centos machine. However only facing this issue from last 15-20 days. I checked #[3782](https://github.com/scylladb/scylla/issues/3782), the package provided is for debian only, so will not be able to test on centos machine. Also not sure If we test the same on some staging environment, will be able to re-produce the error or not, as there is no fixed event on which this problem occurs.

We can also try with upgrading Scylla Server version if there are no other workarounds.

**Comment by glommer** [comment] 2019-06-11 11:47
Hello.

Since we don't know what causes the issue, it is hard to suggest a workaround. If you are willing to test new binaries, I am sure @tgrabiec would be happy to provide you with centos binaries.

Another alternative is indeed to move to newer 3.0.7 We can't guarantee that the bug is fixed (again, because we don't know the cause), but there is always a chance. If you choose to go this route, please report back!

**Comment by virenderdubey** [comment] 2019-06-27 04:54
HI Glommer,

We have upgraded the scylla to 3.0.7 successfully, but the issue is still persist. We monitor the same for few days and seen scylla is getting restarted with the same error and then core dump.
Now We have decided to test the centos binary as well. Please help to provided the same.

**Comment by dorlaor** [comment] 2019-06-27 05:02
It does look like the one in the issue Glauber mentioned,   @tgrabiec
<https://github.com/tgrabiec> , care to provide a centos binary and a
rebase over the latest 3.0.7 ?

**Comment by tgrabiec** [comment] 2019-06-27 12:37
@virenderdubey  Did you remove all sstables from disk when you upgraded?

You can find the RPMS for https://github.com/tgrabiec/scylla/tree/verify-monotonicity-3.0.7 here:
http://scratch.scylladb.com/tgrabiec/scylla-server-3.0.7-0.20190627.498bf01.el7.x86_64.rpm
http://scratch.scylladb.com/tgrabiec/scylla-debuginfo-3.0.7-0.20190627.498bf01.el7.x86_64.rpm

Scylla will abort sooner, when the bad sstable is written, rather than read.

**Comment by virenderdubey** [comment] 2019-06-28 06:03
@tgrabiec, nope, we didn't delete any sstable. We just drain the node and update the scylla via YUM.
For the schema migration if there is any, we rely on Compaction which write the new SSTable.

Will try with these RPMS and update you soon.

**Comment by slivne** [comment] 2019-07-11 09:51
@virenderdubey any update ?

**Comment by slivne** [comment] 2019-07-25 09:33
@virenderdubey closing this issue - if you can provide additional information we will reopen

**Comment by virenderdubey** [comment] 2019-09-26 10:01
@slivne/@tgrabiec, Was busy in other projects and so not able to test the same earlier. 

Tested the CentOS RPMs on CentOS 7.3 as well as CentOS 7.7 Machine, however not able to install them. The package have multiple dependencies, able to resolv some of them however few of the dependencies are still unresolved. Below are the unresolved dependency

error: Failed dependencies:
       libstdc++.so.6(CXXABI_1.3.11)(64bit) is needed by scylla-server-3.0.7-0.20190627.498bf01.el7.x86_64
       libstdc++.so.6(CXXABI_1.3.8)(64bit) is needed by scylla-server-3.0.7-0.20190627.498bf01.el7.x86_64
       libstdc++.so.6(GLIBCXX_3.4.20)(64bit) is needed by scylla-server-3.0.7-0.20190627.498bf01.el7.x86_64
       libstdc++.so.6(GLIBCXX_3.4.21)(64bit) is needed by scylla-server-3.0.7-0.20190627.498bf01.el7.x86_64
       libstdc++.so.6(GLIBCXX_3.4.22)(64bit) is needed by scylla-server-3.0.7-0.20190627.498bf01.el7.x86_64
       scylla-conf is needed by scylla-server-3.0.7-0.20190627.498bf01.el7.x86_64

**Comment by tgrabiec** [comment] 2019-09-26 10:15
Did you try to install the stock scylla 3.0.7 package first?

**Comment by virenderdubey** [comment] 2019-09-26 11:05
nope,  we didn't . We were trying to install these RPMS on a fresh machine.

**Comment by tgrabiec** [comment] 2019-09-26 14:03
You have to first follow the standard install procedure and then install
the patch RPM.

**Comment by virenderdubey** [comment] 2019-09-27 13:36
@tgrabiec, Have installed these RPMs however the cluster is still restarting with the below errors

Sep 27 13:27:19 ip-10-114-76-193 scylla: scylla: flat_mutation_reader.hh:118: void flat_mutation_reader::impl::push_mutation_fragment(Args&& ...) [with Args = {mutation_fragment}]: Assertion `less(_prev_pos, pos)' failed.
Sep 27 13:27:19 ip-10-114-76-193 scylla: Aborting on shard 0.
Sep 27 13:27:19 ip-10-114-76-193 scylla: Backtrace:
Sep 27 13:27:19 ip-10-114-76-193 scylla: 0x00000000006aa3a2
Sep 27 13:27:19 ip-10-114-76-193 scylla: 0x00000000005c1acc
Sep 27 13:27:19 ip-10-114-76-193 scylla: 0x00000000005c1d75
Sep 27 13:27:19 ip-10-114-76-193 scylla: 0x00000000005c1e23
Sep 27 13:27:19 ip-10-114-76-193 scylla: /lib64/libpthread.so.0+0x000000000000f67f
Sep 27 13:27:19 ip-10-114-76-193 scylla: /lib64/libc.so.6+0x0000000000036206
Sep 27 13:27:19 ip-10-114-76-193 scylla: /lib64/libc.so.6+0x00000000000378f7
Sep 27 13:27:19 ip-10-114-76-193 scylla: /lib64/libc.so.6+0x000000000002f025
Sep 27 13:27:19 ip-10-114-76-193 scylla: /lib64/libc.so.6+0x000000000002f0d1
Sep 27 13:27:19 ip-10-114-76-193 scylla: 0x0000000001545e52
Sep 27 13:27:19 ip-10-114-76-193 scylla: 0x0000000001bcb560
Sep 27 13:27:19 ip-10-114-76-193 scylla: 0x0000000001bcf9b9
Sep 27 13:27:19 ip-10-114-76-193 scylla: 0x0000000001c07c52
Sep 27 13:27:19 ip-10-114-76-193 scylla: 0x0000000001c0ac17
Sep 27 13:27:19 ip-10-114-76-193 scylla: 0x0000000001c0b4a6
Sep 27 13:27:19 ip-10-114-76-193 scylla: 0x0000000001c3347d
Sep 27 13:27:19 ip-10-114-76-193 scylla: 0x00000000005a2e7e
Sep 27 13:27:19 ip-10-114-76-193 scylla: 0x00000000005a3041
Sep 27 13:27:19 ip-10-114-76-193 scylla: 0x00000000006716d7
Sep 27 13:27:19 ip-10-114-76-193 scylla: 0x00000000007af423
Sep 27 13:27:19 ip-10-114-76-193 scylla: 0x0000000000536515
Sep 27 13:27:19 ip-10-114-76-193 scylla: /lib64/libc.so.6+0x00000000000223d4
Sep 27 13:27:19 ip-10-114-76-193 scylla: 0x000000000059cd7d

**Comment by tgrabiec** [comment] 2019-09-27 14:20
@virenderdubey This means that the patch caught the root of the problem. Please upload the resulting core dump for analysis. The upload procedure is described here: https://docs.scylladb.com/troubleshooting/report_scylla_problem/#core-dump

**Comment by virenderdubey** [comment] 2019-09-27 20:37
@tgrabiec Have Uploaded the Core Dump for the two dev servers. Below are the UUID for them:
Server 1: 
UUID:  f3cfb1c1-5263-42b6-b03c-c7a4faa75267
FILEPATH:  http://upload.scylladb.com/f3cfb1c1-5263-42b6-b03c-c7a4faa75267/scylladb_core_dump.xz
Server 2:
UUID: 0c4d42e7-780b-4e15-beee-892d85ae394e
http://upload.scylladb.com/0c4d42e7-780b-4e15-beee-892d85ae394e/scylladb_core_dump.xz

Also, one thing i want to be in notice, these are the dev servers which have very less dataset. They were earlier working fine. However as i upgraded to the mentioned rpms(stop scylla && rpm -Uvh <scylla-server rpms> && start scylla) the scylla server on these machines getting restarted.

Later i did the other procedue(stop scylla && remove old scylla rpms && install new scylla rpms && run scylla_setup && then start scylla). Currently scylla service is running fine on dev machines. Will monitor and then update the prod machines later. Will update you accordingly.

**Comment by virenderdubey** [comment] 2019-09-28 12:36
@tgrabiec,, We did the installation of the mentioned RPMs on one of the prod server, and post install when we start the service, scylla starts reading Keyspace and their column family. However it got stucked  on one of the column family and then after some time(10-15 mins) scylla service got auto restarted, with the mentioned core dump. Attaching the same:

http://upload.scylladb.com/0d81c5e2-6e17-407c-a8c9-9829700ac6ae/core.scylla.993.d1d878ebfcdf41ada848d19d3e7e7773.14402.1569665918000000.xz 
Could you please help to take it further.

**Comment by tgrabiec** [comment] 2019-09-30 10:37
On Fri, Sep 27, 2019 at 10:38 PM virenderdubey <notifications@github.com>
wrote:

> @tgrabiec <https://github.com/tgrabiec> Have Uploaded the Core Dump for
> the two dev servers. Below are the UUID for them:
> Server 1:
> UUID: f3cfb1c1-5263-42b6-b03c-c7a4faa75267
> FILEPATH:
> http://upload.scylladb.com/f3cfb1c1-5263-42b6-b03c-c7a4faa75267/scylladb_core_dump.xz
> Server 2:
> UUID: 0c4d42e7-780b-4e15-beee-892d85ae394e
>
> http://upload.scylladb.com/0c4d42e7-780b-4e15-beee-892d85ae394e/scylladb_core_dump.xz
>
> Also, one thing i want to be in notice, these are the dev servers which
> have very less dataset. They were earlier working fine. However as i
> upgraded to the mentioned rpms(stop scylla && rpm -Uvh && start scylla) the
> scylla server on these machines getting restarted.
>
That's expected. The patch RPM doesn't fix anything, just catches the
violation of invariants which may manifest as corrupted sstables later.

**Comment by tgrabiec** [comment] 2019-09-30 13:50
@virenderdubey I need you glibc to open the core dump. Please issue `sudo debuginfo-install glibc` on Server 1, zip the contents of `/usr/lib64/` and `/usr/lib/debug/lib64/`, and send it to us.

**Closed** 2019-10-24 09:43 UTC
Labels: User Request, bug
