### ISSUE TITLE
when scylla_setup in v4.4.3,scylla_setup failed

### ISSUE THREAD

**Issue by foxhunter72143** [scylladb/scylla#8922] opened 2021-06-24 06:50 UTC
Please select a NIC from the following list:
['bond0', 'bonding_masters', 'enp94s0f1', 'enp94s0f0']
> bond0
The clocksource is the physical device that Linux uses to take time measurements. In most cases Linux chooses the fastest available clocksource device as long as it is accurate. In some situations, however, Linux errs in the side of caution and does not choose the fastest available clocksource despite it being accurate enough. If you know your hardwares fast clocksource is stable enough, choose "yes" here. The safest is the choose "no" (the default)
Yes - enforce clocksource setting. No - keep current configuration.
[yes/NO]no
Traceback (most recent call last):
  File "/opt/scylladb/scripts/libexec/scylla_sysconfig_setup", line 80, in <module>
    rps_cpus = run('{} --tune net --nic {} --get-cpu-mask'.format(perftune_base_command(), ifname), shell=True, check=True, capture_output=True, encoding='utf-8').stdout.strip()
  File "/opt/scylladb/python3/lib64/python3.9/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '/opt/scylladb/scripts/perftune.py --tune disks --dir /var/lib/scylla/data --dir /var/lib/scylla/commitlog --dir /var/lib/scylla/hints --dir /var/lib/scylla/view_hints --tune net --nic bond0 --get-cpu-mask' returned non-zero exit status 1.
Performance Tuning setup failed. Press any key to continue...

> /opt/scylladb/scripts/perftune.py --tune disks --dir /var/lib/scylla/data --dir /var/lib/scylla/commitlog --dir /varib/scylla/hints --dir /var/lib/scylla/view_hints --tune net --nic bond0 --get-cpu-mask

>ERROR: 'bond0'. Your system can't be tuned until the issue is fixed.

In version v4.0.0 scylla_setup do well,now I try to install v4.4.3 server,scylla_setup error

**Comment by syuu1228** [comment] 2021-07-05 14:33
It's bonding device handling bug on perftune.py.
It is already fixed at https://github.com/scylladb/seastar/commit/5e6f9a8af2bf8549f567e0f67c35ff24d5e63e19, but looks like not backported yet.
@avikivity @penberg Please backport the commit to branch-4.4, branch-4.5

**Comment by syuu1228** [comment] 2021-07-14 10:58
ping

**Comment by syuu1228** [comment] 2021-07-26 11:53
ping

**Comment by syuu1228** [comment] 2021-08-04 11:50
@avikivity ping

**Comment by penberg** [comment] 2021-08-20 06:54
@syuu1228 The backports have been done, but they refer to a duplicate of this issue https://github.com/scylladb/scylla/issues/9225

**Closed by penberg** 2021-08-20 06:54 UTC
Labels: bug, User Request, onboarding, Backport candidate, fixed
