### ISSUE TITLE
Segfault after upgrading from 2.3.1 to 3.0-rc3 (with MV backpressure changes)

### ISSUE THREAD

**Issue by veramine** [scylladb/scylla#4012] opened 2018-12-24 06:37 UTC
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [X] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash):  3.0.rc3-0.20181223.dfb23f4 (branch-3.0)
Cluster size: 2
OS (RHEL/CentOS/Ubuntu/AWS AMI): AWS AMI

*Hardware details (for performance issues)*        
Platform (physical/VM/cloud instance type/docker):  AWS i3.xlarge

We have been eager to try out Duarte's view backpressure changes so we built our own copy of 3.0 RC3 and upgraded a test cluster from 2.3.1.  It worked fine to add a new (third) node, rpc streaming worked fine, cqlsh worked fine to query from base tables.  But as soon as we ran our application that makes use of secondary indexes and materialized views it segfaulted right away.   Potentially from the first instance of a bad query, not a result of load or timing issue or periodic failure.  It segfaults every time as soon as we run our regular application, 100% reproducible within a few seconds.  

Here's the stack trace from the segfault:

```
0x000000000059a12dvoid seastar::backtrace<seastar::backtrace_buffer::append_backtrace()::{lambda(seastar::frame)#1}>(seastar::backtrace_buffer::append_backtrace()::{lambda(seastar::frame)#1}&&) at /usr/src/debug/scylla-3.0.rc3/seastar/util/backtrace.hh:56
seastar::backtrace_buffer::append_backtrace() at /usr/src/debug/scylla-3.0.rc3/seastar/core/reactor.cc:410
 (inlined by) print_with_backtrace at /usr/src/debug/scylla-3.0.rc3/seastar/core/reactor.cc:431
seastar::print_with_backtrace(char const*) at /usr/src/debug/scylla-3.0.rc3/seastar/core/reactor.cc:438
sigsegv_action at /usr/src/debug/scylla-3.0.rc3/seastar/core/reactor.cc:4020
 (inlined by) operator() at /usr/src/debug/scylla-3.0.rc3/seastar/core/reactor.cc:4006
 (inlined by) _FUN at /usr/src/debug/scylla-3.0.rc3/seastar/core/reactor.cc:4002
?? ??:0
seastar::lw_shared_ptr_counter_base* std::__exchange<seastar::lw_shared_ptr_counter_base*, decltype(nullptr)>(seastar::lw_shared_ptr_counter_base*&, decltype(nullptr)&&) at /opt/scylladb/include/c++/7/bits/move.h:151
 (inlined by) seastar::lw_shared_ptr_counter_base* std::exchange<seastar::lw_shared_ptr_counter_base*, decltype(nullptr)>(seastar::lw_shared_ptr_counter_base*&, decltype(nullptr)&&) at /opt/scylladb/include/c++/7/utility:282
 (inlined by) seastar::lw_shared_ptr<frozen_mutation const>::release() at /usr/src/debug/scylla-3.0.rc3/seastar/core/shared_ptr.hh:345
 (inlined by) service::per_destination_mutation::release_mutation() at /usr/src/debug/scylla-3.0.rc3/service/storage_proxy.cc:168
service::abstract_write_response_handler::on_released() at /usr/src/debug/scylla-3.0.rc3/service/storage_proxy.cc:346
 (inlined by) service::storage_proxy::remove_response_handler(unsigned long) at /usr/src/debug/scylla-3.0.rc3/service/storage_proxy.cc:577
service::storage_proxy::got_response(unsigned long, gms::inet_address, std::experimental::fundamentals_v1::optional<db::view::update_backlog>) at /usr/src/debug/scylla-3.0.rc3/service/storage_proxy.cc:587
operator() at /usr/src/debug/scylla-3.0.rc3/service/storage_proxy.cc:1903
 (inlined by) apply at /usr/src/debug/scylla-3.0.rc3/seastar/core/apply.hh:35
 (inlined by) apply<service::storage_proxy::send_to_live_endpoints(service::storage_proxy::response_id_type, seastar::lowres_clock::time_point)::<lambda(seastar::lw_shared_ptr<const frozen_mutation>)> mutable::<lambda()> > at /usr/src/debug/scylla-3.0.rc3/seastar/core/apply.hh:43
 (inlined by) apply_tuple<service::storage_proxy::send_to_live_endpoints(service::storage_proxy::response_id_type, seastar::lowres_clock::time_point)::<lambda(seastar::lw_shared_ptr<const frozen_mutation>)> mutable::<lambda()> > at /usr/src/debug/scylla-3.0.rc3/seastar/core/future.hh:1343
 (inlined by) apply<service::storage_proxy::send_to_live_endpoints(service::storage_proxy::response_id_type, seastar::lowres_clock::time_point)::<lambda(seastar::lw_shared_ptr<const frozen_mutation>)> mutable::<lambda()> > at /usr/src/debug/scylla-3.0.rc3/seastar/core/future.hh:1377
 (inlined by) operator()<seastar::future_state<> > at /usr/src/debug/scylla-3.0.rc3/seastar/core/future.hh:963
 (inlined by) run_and_dispose at /usr/src/debug/scylla-3.0.rc3/seastar/core/future.hh:414
seastar::reactor::run_tasks(seastar::reactor::task_queue&) at /usr/src/debug/scylla-3.0.rc3/seastar/core/reactor.cc:2695
seastar::reactor::run_some_tasks() at /usr/src/debug/scylla-3.0.rc3/seastar/core/reactor.cc:3118
seastar::reactor::run_some_tasks() at /usr/src/debug/scylla-3.0.rc3/seastar/util/log.hh:313
 (inlined by) seastar::reactor::run() at /usr/src/debug/scylla-3.0.rc3/seastar/core/reactor.cc:3265
seastar::app_template::run_deprecated(int, char**, std::function<void ()>&&) at /usr/src/debug/scylla-3.0.rc3/seastar/core/app-template.cc:185
main at /usr/src/debug/scylla-3.0.rc3/main.cc:854
```

I've also attached a full journalctl output where you can see lots of compaction and streaming happening no problem.  I also have a huge coredump I can upload if you need it.  Thanks.

[segfault.txt](https://github.com/scylladb/scylla/files/2706729/segfault.txt)

**Comment by slivne** [comment] 2018-12-24 07:51
@nyh is this #4008 ?

**Comment by nyh** [comment] 2018-12-24 08:05
@slivne yes I think this is a duplicate of #4008 and solved by commit 6c4a34f37883fc22b90e9739122c1c48df92706e (also backported to branch-3.0).

**Comment by slivne** [comment] 2018-12-24 08:07
@veramine closing the issue - if it reproduces over the version with the fix we will reopen.

**Closed by slivne** 2018-12-24 08:07 UTC
Labels: bug, materialized-views, showstopper

**Comment by veramine** [comment] 2018-12-24 08:08
Okay thanks for the quick reply!  We will build with that fix and test.  Thanks.
