### ISSUE TITLE
A lot of reactor stalls from 650 to 1800 during cluster initialization from node has been added to cluster already

### ISSUE THREAD

**Issue by aleksbykov** [scylladb/scylla#6869] opened 2020-07-17 12:32 UTC
*Installation details*
Scylla version (or git commit hash):Scylla version 4.2.rc1-0.20200709.51d4efc3212 with build-id fe5f4c9282b21b22bbcc986f8c43836f6d6cf32d
Cluster size: 6
OS (RHEL/CentOS/Ubuntu/AWS AMI): ami-03396516d7bd6a5fa
instance_type_db: i3.4xlarge

During cluster initialization and add new node to cluster, there are a lot of Reactor stalls from nodes which are alreary in cluster
Reactor stalls duration from 650 up to 1800ms
```
2020-07-16 13:20:12.000: (DatabaseLogEvent Severity.NORMAL): type=REACTOR_STALLED regex=Reactor stalled line_number=1939 node=Node longevity-tls-50gb-4d-4-2-db-node-be967b52-1 [52.55.56.90 | 172.30.0.36] (seed: True)
2020-07-16T13:20:12+00:00  longevity-tls-50gb-4d-4-2-db-node-be967b52-1 !INFO    | scylla: Reactor stalled for 650 ms on shard 4.

void seastar::backtrace<seastar::backtrace_buffer::append_backtrace()::{lambda(seastar::frame)#1}>(seastar::backtrace_buffer::append_backtrace()::{lambda(seastar::frame)#1}&&) at /usr/include/fmt/format.h:2188
seastar::backtrace_buffer::append_backtrace() at /usr/include/fmt/format.h:2188
 (inlined by) print_with_backtrace at /jenkins/workspace/scylla-4.2/next/scylla/seastar/src/core/reactor.cc:751
seastar::internal::cpu_stall_detector::generate_trace() at /usr/include/fmt/format.h:2188
seastar::internal::cpu_stall_detector::maybe_report() at /usr/include/fmt/format.h:2188
 (inlined by) seastar::internal::cpu_stall_detector::on_signal() at /jenkins/workspace/scylla-4.2/next/scylla/seastar/src/core/reactor.cc:1060
 (inlined by) seastar::reactor::block_notifier(int) at /jenkins/workspace/scylla-4.2/next/scylla/seastar/src/core/reactor.cc:1183
?? ??:0
?? ??:0
2020-07-16 13:20:12.000: (DatabaseLogEvent Severity.NORMAL): type=REACTOR_STALLED regex=Reactor stalled line_number=1947 node=Node longevity-tls-50gb-4d-4-2-db-node-be967b52-1 [52.55.56.90 | 172.30.0.36] (seed: True)
2020-07-16T13:20:12+00:00  longevity-tls-50gb-4d-4-2-db-node-be967b52-1 !INFO    | scylla: Reactor stalled for 650 ms on shard 13.

void seastar::backtrace<seastar::backtrace_buffer::append_backtrace()::{lambda(seastar::frame)#1}>(seastar::backtrace_buffer::append_backtrace()::{lambda(seastar::frame)#1}&&) at /usr/include/fmt/format.h:2188
seastar::backtrace_buffer::append_backtrace() at /usr/include/fmt/format.h:2188
 (inlined by) print_with_backtrace at /jenkins/workspace/scylla-4.2/next/scylla/seastar/src/core/reactor.cc:751
seastar::internal::cpu_stall_detector::generate_trace() at /usr/include/fmt/format.h:2188
seastar::internal::cpu_stall_detector::maybe_report() at /usr/include/fmt/format.h:2188
 (inlined by) seastar::internal::cpu_stall_detector::on_signal() at /jenkins/workspace/scylla-4.2/next/scylla/seastar/src/core/reactor.cc:1060
 (inlined by) seastar::reactor::block_notifier(int) at /jenkins/workspace/scylla-4.2/next/scylla/seastar/src/core/reactor.cc:1183
?? ??:0
?? ??:0
```

```?? ??:0
2020-07-16 13:21:48.000: (DatabaseLogEvent Severity.NORMAL): type=REACTOR_STALLED regex=Reactor stalled line_number=1566 node=Node longevity-tls-50gb-4d-4-2-db-node-be967b52-2 [3.92.60.128 | 172.30.0.20] (seed: False)
2020-07-16T13:21:48+00:00  longevity-tls-50gb-4d-4-2-db-node-be967b52-2 !INFO    | scylla: Reactor stalled for 658 ms on shard 6.

void seastar::backtrace<seastar::backtrace_buffer::append_backtrace()::{lambda(seastar::frame)#1}>(seastar::backtrace_buffer::append_backtrace()::{lambda(seastar::frame)#1}&&) at /usr/include/fmt/format.h:2188
seastar::backtrace_buffer::append_backtrace() at /usr/include/fmt/format.h:2188
 (inlined by) print_with_backtrace at /jenkins/workspace/scylla-4.2/next/scylla/seastar/src/core/reactor.cc:751
seastar::internal::cpu_stall_detector::generate_trace() at /usr/include/fmt/format.h:2188
seastar::internal::cpu_stall_detector::maybe_report() at /usr/include/fmt/format.h:2188
 (inlined by) seastar::internal::cpu_stall_detector::on_signal() at /jenkins/workspace/scylla-4.2/next/scylla/seastar/src/core/reactor.cc:1060
 (inlined by) seastar::reactor::block_notifier(int) at /jenkins/workspace/scylla-4.2/next/scylla/seastar/src/core/reactor.cc:1183
?? ??:0
?? ??:0
2020-07-16 13:21:49.000: (DatabaseLogEvent Severity.NORMAL): type=REACTOR_STALLED regex=Reactor stalled line_number=1581 node=Node longevity-tls-50gb-4d-4-2-db-node-be967b52-2 [3.92.60.128 | 172.30.0.20] (seed: False)
2020-07-16T13:21:49+00:00  longevity-tls-50gb-4d-4-2-db-node-be967b52-2 !INFO    | scylla: Reactor stalled for 1804 ms on shard 7.

void seastar::backtrace<seastar::backtrace_buffer::append_backtrace()::{lambda(seastar::frame)#1}>(seastar::backtrace_buffer::append_backtrace()::{lambda(seastar::frame)#1}&&) at /usr/include/fmt/format.h:2188
seastar::backtrace_buffer::append_backtrace() at /usr/include/fmt/format.h:2188
 (inlined by) print_with_backtrace at /jenkins/workspace/scylla-4.2/next/scylla/seastar/src/core/reactor.cc:751
seastar::internal::cpu_stall_detector::generate_trace() at /usr/include/fmt/format.h:2188
seastar::internal::cpu_stall_detector::maybe_report() at /usr/include/fmt/format.h:2188
 (inlined by) seastar::internal::cpu_stall_detector::on_signal() at /jenkins/workspace/scylla-4.2/next/scylla/seastar/src/core/reactor.cc:1060
 (inlined by) seastar::reactor::block_notifier(int) at /jenkins/workspace/scylla-4.2/next/scylla/seastar/src/core/reactor.cc:1183
?? ??:0
?? ??:0
```

```
2020-07-16 13:31:52.000: (DatabaseLogEvent Severity.NORMAL): type=REACTOR_STALLED regex=Reactor stalled line_number=3181 node=Node longevity-tls-50gb-4d-4-2-db-node-be967b52-4 [35.171.162.92 | 172.30.0.201] (seed: False)
2020-07-16T13:31:52+00:00  longevity-tls-50gb-4d-4-2-db-node-be967b52-4 !INFO    | scylla: Reactor stalled for 651 ms on shard 10.

void seastar::backtrace<seastar::backtrace_buffer::append_backtrace()::{lambda(seastar::frame)#1}>(seastar::backtrace_buffer::append_backtrace()::{lambda(seastar::frame)#1}&&) at /usr/include/fmt/format.h:2188
seastar::backtrace_buffer::append_backtrace() at /usr/include/fmt/format.h:2188
 (inlined by) print_with_backtrace at /jenkins/workspace/scylla-4.2/next/scylla/seastar/src/core/reactor.cc:751
seastar::internal::cpu_stall_detector::generate_trace() at /usr/include/fmt/format.h:2188
seastar::internal::cpu_stall_detector::maybe_report() at /usr/include/fmt/format.h:2188
 (inlined by) seastar::internal::cpu_stall_detector::on_signal() at /jenkins/workspace/scylla-4.2/next/scylla/seastar/src/core/reactor.cc:1060
 (inlined by) seastar::reactor::block_notifier(int) at /jenkins/workspace/scylla-4.2/next/scylla/seastar/src/core/reactor.cc:1183
?? ??:0
?? ??:0
?? ??:0
?? ??:0
?? ??:0
?? ??:0
seastar::tls::credentials_builder::build_server_credentials() const at tls.cc:?
 (inlined by) std::_MakeUniq<seastar::tls::dh_params::impl>::__single_object std::make_unique<seastar::tls::dh_params::impl, seastar::tls::dh_params::level&>(seastar::tls::dh_params::level&) at /usr/include/c++/10/bits/unique_ptr.h:961
 (inlined by) seastar::tls::dh_params::dh_params(seastar::tls::dh_params::level) at /jenkins/workspace/scylla-4.2/next/scylla/seastar/src/net/tls.cc:199
 (inlined by) seastar::tls::credentials_builder::build_server_credentials() const at /jenkins/workspace/scylla-4.2/next/scylla/seastar/src/net/tls.cc:613
seastar::tls::credentials_builder::build_reloadable_server_credentials(std::function<void (std::unordered_set<seastar::basic_sstring<char, unsigned int, 15u, true>, std::hash<seastar::basic_sstring<char, unsigned int, 15u, true> >, std::equal_to<seastar::basic_sstring<char, unsigned int, 15u, true> >, std::allocator<seastar::basic_sstring<char, unsigned int, 15u, true> > > const&, std::__exception_ptr::exception_ptr)>) const at tls.cc:?
netw::messaging_service::start_listen() at /usr/include/c++/10/bits/stl_vector.h:1759
gms::gossiper::init_messaging_service_handler(seastar::bool_class<gms::bind_messaging_port_tag>) at /usr/include/fmt/format.h:2188
operator() at /usr/include/fmt/format.h:2188
 (inlined by) __invoke_impl<seastar::future<>, gms::gossiper::do_shadow_round()::<lambda()>::<lambda(gms::gossiper&)>&, gms::gossiper&> at /usr/include/c++/10/bits/invoke.h:60
 (inlined by) __invoke<gms::gossiper::do_shadow_round()::<lambda()>::<lambda(gms::gossiper&)>&, gms::gossiper&> at /usr/include/c++/10/bits/invoke.h:96
 (inlined by) __apply_impl<gms::gossiper::do_shadow_round()::<lambda()>::<lambda(gms::gossiper&)>&, std::tuple<gms::gossiper&>, 0> at /usr/include/c++/10/tuple:1724
 (inlined by) apply<gms::gossiper::do_shadow_round()::<lambda()>::<lambda(gms::gossiper&)>&, std::tuple<gms::gossiper&> > at /usr/include/c++/10/tuple:1736
 (inlined by) apply<gms::gossiper::do_shadow_round()::<lambda()>::<lambda(gms::gossiper&)>&, gms::gossiper&> at /jenkins/workspace/scylla-4.2/next/scylla/seastar/include/seastar/core/future.hh:2009
 (inlined by) futurize_apply<gms::gossiper::do_shadow_round()::<lambda()>::<lambda(gms::gossiper&)>&, gms::gossiper&> at /jenkins/workspace/scylla-4.2/next/scylla/seastar/include/seastar/core/future.hh:2122
 (inlined by) operator() at /jenkins/workspace/scylla-4.2/next/scylla/seastar/include/seastar/core/sharded.hh:688
 (inlined by) __invoke_impl<seastar::future<>, seastar::sharded<T>::invoke_on_all<gms::gossiper::do_shadow_round()::<lambda()>::<lambda(gms::gossiper&)>, {}>::<lambda(gms::gossiper&)>&, gms::gossiper&> at /usr/include/c++/10/bits/invoke.h:60
 (inlined by) __invoke_r<seastar::future<>, seastar::sharded<T>::invoke_on_all<gms::gossiper::do_shadow_round()::<lambda()>::<lambda(gms::gossiper&)>, {}>::<lambda(gms::gossiper&)>&, gms::gossiper&> at /usr/include/c++/10/bits/invoke.h:115
 (inlined by) _M_invoke at /usr/include/c++/10/bits/std_function.h:292
std::function<seastar::future<> (gms::gossiper&)>::operator()(gms::gossiper&) const at /usr/include/fmt/format.h:2188
 (inlined by) seastar::sharded<gms::gossiper>::invoke_on_all(seastar::smp_submit_to_options, std::function<seastar::future<> (gms::gossiper&)>)::{lambda(unsigned int)#1}::operator()(unsigned int) const::{lambda()#1}::operator()() const at /jenkins/workspace/scylla-4.2/next/scylla/seastar/include/seastar/core/sharded.hh:674
 (inlined by) seastar::future<> seastar::futurize<seastar::future<> >::invoke<seastar::sharded<gms::gossiper>::invoke_on_all(seastar::smp_submit_to_options, std::function<seastar::future<> (gms::gossiper&)>)::{lambda(unsigned int)#1}::operator()(unsigned int) const::{lambda()#1}&>(seastar::sharded<gms::gossiper>::invoke_on_all(seastar::smp_submit_to_options, std::function<seastar::future<> (gms::gossiper&)>)::{lambda(unsigned int)#1}::operator()(unsigned int) const::{lambda()#1}&) at /jenkins/workspace/scylla-4.2/next/scylla/seastar/include/seastar/core/future.hh:2026
 (inlined by) seastar::smp_message_queue::async_work_item<seastar::sharded<gms::gossiper>::invoke_on_all(seastar::smp_submit_to_options, std::function<seastar::future<> (gms::gossiper&)>)::{lambda(unsigned int)#1}::operator()(unsigned int) const::{lambda()#1}>::run_and_dispose() at /jenkins/workspace/scylla-4.2/next/scylla/seastar/include/seastar/core/smp.hh:219
seastar::reactor::run_tasks(seastar::reactor::task_queue&) at /usr/include/fmt/format.h:2188
seastar::reactor::run_some_tasks() at /usr/include/fmt/format.h:2188
seastar::reactor::run_some_tasks() at /usr/include/fmt/format.h:2188
 (inlined by) seastar::reactor::run() at /jenkins/workspace/scylla-4.2/next/scylla/seastar/src/core/reactor.cc:2712
seastar::smp::configure(boost::program_options::variables_map, seastar::reactor_config)::{lambda()#3}::operator()() const at /usr/include/fmt/format.h:2188
std::function<void ()>::operator()() const at /usr/include/c++/10/bits/basic_string.h:323
 (inlined by) seastar::posix_thread::start_routine(void*) at /jenkins/workspace/scylla-4.2/next/scylla/seastar/src/core/posix.cc:60
?? ??:0
?? ??:0
```

example of db logs:
https://jenkins.scylladb.com/view/scylla-4.2/job/scylla-4.2/job/longevity/job/longevity-50gb-4days-test/8/artifact/scylla-cluster-tests/latest/longevity-tls-50gb-4d-4-2-db-cluster-401b5b2b/*zip*/longevity-tls-50gb-4d-4-2-db-cluster-401b5b2b.zip

**Comment by avikivity** [comment] 2020-07-19 07:37
Duplicate of #6191

**Closed by avikivity** 2020-07-19 07:37 UTC
