### ISSUE TITLE
ubuntu 16.04: cqlsh failed to connect scylla-server

### ISSUE THREAD

**Issue by kongove** [scylladb/scylla#1515] opened 2016-07-28 10:14 UTC
*Installation details*
Scylla version (or git commit hash):
  can reproduce with 1.2.2-20160719.caab57b-ubuntu1  and 1.3~rc1-20160721.c84e030
Cluster size: single node
OS (RHEL/CentOS/Ubuntu/AWS AMI): ubuntu/images/hvm-ssd/ubuntu-xenial-16.04-amd64-server-20160516.1 (ami-13be557e)

### Description:

1. Install scylla-1.2, try to connect scylla-server by cqlsh

```
ubuntu@ip-10-13-192-236:~$ sudo service scylla-server status
● scylla-server.service - Scylla Server
   Loaded: loaded (/lib/systemd/system/scylla-server.service; disabled; vendor preset: enabled)
   Active: active (running) since Thu 2016-07-28 10:10:00 UTC; 2min 20s ago
  Process: 2243 ExecStartPre=/usr/lib/scylla/scylla_prepare (code=exited, status=0/SUCCESS)
 Main PID: 2308 (scylla)
   Status: "serving"
    Tasks: 9
   Memory: 4.1G
      CPU: 35.653s
   CGroup: /system.slice/scylla-server.service
           └─2308 /usr/bin/scylla --log-to-syslog 1 --log-to-stdout 0 --default-log-level info --collectd-address=127.0.0.1:25826 --collectd=1 --collectd-poll-perio

Jul 28 10:10:00 ip-10-13-192-236 scylla[2308]:  [shard 0] storage_service - Using saved tokens {967322756271637411, 9212261359140502493, 9191034721626599693, 914283
Jul 28 10:10:01 ip-10-13-192-236 scylla[2308]:  [shard 0] compaction - Compacting [/var/lib/scylla/data/system/local-7ad54392bcdd35a684174e047860b377/system-local-k
Jul 28 10:10:01 ip-10-13-192-236 scylla[2308]:  [shard 0] compaction - Compacted 4 sstables to [/var/lib/scylla/data/system/local-7ad54392bcdd35a684174e047860b377/s
Jul 28 10:10:01 ip-10-13-192-236 scylla[2308]:  [shard 0] storage_service - Node 127.0.0.1 state jump to normal
Jul 28 10:10:01 ip-10-13-192-236 scylla[2308]:  [shard 2] compaction - Compacting [/var/lib/scylla/data/system/peers-37f71aca7dc2383ba70672528af04d4f/system-peers-k
Jul 28 10:10:01 ip-10-13-192-236 scylla[2308]:  [shard 0] storage_service - NORMAL: node is now in normal status
Jul 28 10:10:01 ip-10-13-192-236 scylla[2308]:  [shard 0] gossip - Waiting for gossip to settle before accepting client requests...
Jul 28 10:10:01 ip-10-13-192-236 scylla[2308]:  [shard 2] compaction - Compacted 5 sstables to [/var/lib/scylla/data/system/peers-37f71aca7dc2383ba70672528af04d4f/s
Jul 28 10:10:09 ip-10-13-192-236 scylla[2308]:  [shard 0] gossip - No gossip backlog; proceeding
Jul 28 10:10:09 ip-10-13-192-236 scylla[2308]:  [shard 0] storage_service - Starting listening for CQL clients on localhost:9042...

ubuntu@ip-10-13-192-236:~$ cqlsh --debug
Using CQL driver: <module 'cassandra' from '/usr/share/scylla/cassandra/lib/cassandra-driver-internal-only-2.6.0c2.post.zip/cassandra-driver-2.6.0c2.post/cassandra/__init__.py'>
Connection error: ('Unable to connect to any servers', {'127.0.0.1': TypeError('ref() does not take keyword arguments',)})
```

2. upgrade scylla to 1.3~rc1-20160721.c84e030, then try to connect scylla-server by cqlsh

```
$ service scylla-server status
● scylla-server.service - Scylla Server
   Loaded: loaded (/lib/systemd/system/scylla-server.service; disabled; vendor preset: enabled)
   Active: active (running) since Thu 2016-07-28 09:42:53 UTC; 24min ago
  Process: 989 ExecStopPost=/usr/lib/scylla/scylla_stop (code=exited, status=0/SUCCESS)
  Process: 1032 ExecStartPre=/usr/lib/scylla/scylla_prepare (code=exited, status=0/SUCCESS)
 Main PID: 1097 (scylla)
   Status: "serving"
    Tasks: 8
   Memory: 4.1G
      CPU: 5min 54.342s
   CGroup: /system.slice/scylla-server.service
           └─1097 /usr/bin/scylla --log-to-syslog 1 --log-to-stdout 0 --default-log-level info --collectd-address=127.0.0.1:258

Jul 28 09:42:54 ip-10-13-192-236 scylla[1097]:  [shard 0] gossip - Checking if need_features {LARGE_PARTITIONS} in features {LA
Jul 28 09:42:54 ip-10-13-192-236 scylla[1097]:  [shard 1] gossip - Checking if need_features {RANGE_TOMBSTONES} in features {LA
Jul 28 09:42:54 ip-10-13-192-236 scylla[1097]:  [shard 3] gossip - Checking if need_features {RANGE_TOMBSTONES} in features {LA
Jul 28 09:42:54 ip-10-13-192-236 scylla[1097]:  [shard 1] gossip - Checking if need_features {LARGE_PARTITIONS} in features {LA
Jul 28 09:42:54 ip-10-13-192-236 scylla[1097]:  [shard 3] gossip - Checking if need_features {LARGE_PARTITIONS} in features {LA
Jul 28 09:42:54 ip-10-13-192-236 scylla[1097]:  [shard 2] gossip - Checking if need_features {RANGE_TOMBSTONES} in features {LA
Jul 28 09:42:54 ip-10-13-192-236 scylla[1097]:  [shard 2] gossip - Checking if need_features {LARGE_PARTITIONS} in features {LA
Jul 28 09:42:54 ip-10-13-192-236 scylla[1097]:  [shard 0] gossip - Waiting for gossip to settle before accepting client request
Jul 28 09:43:02 ip-10-13-192-236 scylla[1097]:  [shard 0] gossip - No gossip backlog; proceeding
Jul 28 09:43:02 ip-10-13-192-236 scylla[1097]:  [shard 0] storage_service - Starting listening for CQL clients on localhost:9042...

ubuntu@ip-10-13-192-236:~$ cqlsh --debug
Using CQL driver: <module 'cassandra' from '/usr/share/scylla/cassandra/lib/cassandra-driver-internal-only-2.6.0c2.post.zip/cassandra-driver-2.6.0c2.post/cassandra/__init__.py'>
Connection error: ('Unable to connect to any servers', {'127.0.0.1': TypeError('ref() does not take keyword arguments',)})
```

### Additional info:
It works in Ubuntu 14.04

**Comment by penberg** [comment] 2016-07-28 10:18
It's the same issue as this https://github.com/scylladb/scylla-tools-java/issues/8

**Comment by tzach** [comment] 2016-08-07 09:18
@tzach add to release 1.3 known issues

**Comment by slivne** [comment] 2016-08-30 19:10
@lmr - I think you fixed this no ?

its the cqlsh python 2.7.12 issue

**Comment by lmr** [comment] 2016-08-31 00:44
Yes, we can close this issue, although it'd be nice to confirm that our latest package contains the fix.

**Comment by tzach** [comment] 2016-08-31 10:41
@lmr please check

**Comment by penberg** [comment] 2016-08-31 11:21
It doesn't and the fix is not even backported.

**Comment by avikivity** [comment] 2016-08-31 11:21
Let's backport it then.

**Comment by penberg** [comment] 2016-09-01 18:30
The problem is fixed by https://github.com/scylladb/scylla-tools-java/commit/677d3609612355b323851824a39f43f26876684a and it's backported to 1.3.

**Closed by penberg** 2016-09-01 18:30 UTC
