### ISSUE TITLE
Expired row markers are compacted diffferently from Cassandra

### ISSUE THREAD

**Issue by nyh** [scylladb/scylla#4597] opened 2019-06-24 12:46 UTC
This is not really a bug, but rather a difference from what Cassandra does that I wanted to document somewhere, and consider whether we should change our behavior to match Cassandra's.

In the new MC sstable format, there is is no such thing as tombstone for the row-marker. Usually, this is not an issue: CQL doesn't have a way to explicitly delete only the row marker, and when deleting an entire row, the row's tombstone deletes the marker as well. But there is one other case to consider: a row-marker which expires because of a TTL set when "INSERT" created the row marker. Originally in Cassandra, when a row-marker expires, compaction does absolutely nothing to it: The expired row marker will simply remain untouched by compaction.

Because of esoteric needs of Materialized Views, which sometimes do need to delete row markers separately from the entire row on the view tables, a feature was added where if the row marker's TTL is set to EXPIRED_LIVENESS_TTL (2^32-1), it is considered to have been deleted.

As explained above, Cassandra doesn't use this EXPIRED_LIVENESS_TTL when just an ordinary row-marker expires, and just leaves the original expiration time intact. But for some reason, in Scylla we made compaction - when it recognizes an expired row marker - replace its TTL with expired_liveness_ttl. This is not incorrect, but unnecessary and results in a use of EXPIRED_LIVENESS_TTL in non-materialized-view sstables which Cassandra never had. This may confuse certain tools, which didn't consider this possibility of having 2^31-1 as a TTL (we have seen problems with sstableloader in this area).

**Comment by tgrabiec** [comment] 2019-06-24 13:50
I'll expand the hisorical background a bit. Back in Cassandra 2.x, row marker was treated like any other cell at the storage layer. So our logic worked the same for markers as it works for cells, and expired cells are replaced with tombstones. Later Cassandra changed their model and replaced markers with liveness info which cannot be deleted alone. Then they changed their mind back and added a way to delete the marker via EXPIRED_LIVESS_TTL. Our internal model compaction remained unchanged. When we translate from a dead marker, we don't know if it came from materialized views or not.

**Comment by slivne** [comment] 2019-07-07 09:38
To summarize this is not a bug - closing the issue

**Closed by slivne** 2019-07-07 09:38 UTC
