### ISSUE TITLE
compaction_manager - compaction failed: std::filesystem::__cxx11::filesystem_error (error system:2, filesystem error: mkdir failed: No such file or directory

### ISSUE THREAD

**Issue by yarongilor** [scylladb/scylla#4902] opened 2019-08-26 15:41 UTC
Installation details
Scylla version (or git commit hash): 3.1.0.rc3-0.20190816.d06bcef3b
Cluster size: 6
OS (RHEL/CentOS/Ubuntu/AWS AMI): ami-07f2007dc543eced5

scenario: 50GB longevity
error:
```
2019-08-22T23:41:23+00:00  ip-172-30-0-228 !ERR     | scylla.bin: [shard 3] sstable - Could not create SSTable component /var/lib/scylla/data/keyspace_snappy/standard1-fbed93f0c28911e9b393000000000009/0000000000000031.sstable/mc-31-big-Filter.db. Found exception: std::filesystem::__cxx11::filesystem_error (error system:2, filesystem error: open failed: No such file or directory [/var/lib/scylla/data/keyspace_snappy/standard1-fbed93f0c28911e9b393000000000009/0000000000000031.sstable/mc-31-big-Filter.db])
2019-08-23 14:30:28.823: (DatabaseLogEvent Severity.CRITICAL): type=FILESYSTEM_ERROR regex=filesystem_error line_number=643308 node=Node longevity-tls-50gb-4d-3-1-db-node-327565b4-7 [3.95.149.37 | 172.30.0.228] (seed: False)
2019-08-22T23:41:28+00:00  ip-172-30-0-228 !ERR     | scylla.bin: [shard 8] compaction_manager - compaction failed: std::filesystem::__cxx11::filesystem_error (error system:2, filesystem error: mkdir failed: No such file or directory [/var/lib/scylla/data/keyspace_snappy/standard1-fbed93f0c28911e9b393000000000009/0000000000000106.sstable]): retrying

```
logs:
```
[jenkins@aws-scylla-qa-builder latest]$ grep -i uploading ./sct.log 
< t:2019-08-24 03:22:21,843 f:common.py       l:328  c:utils                p:INFO  > Uploading '/sct/20190819-131620-166949/longevity-tls-50gb-4d-3-1-monitor-set-327565b4/longevity-tls-50gb-4d-3-1-monitor-node-327565b4-1/grafana-screenshot-per-server-metrics-nemesis-20190824_032210-0.png' to https://cloudius-jenkins-test.s3.amazonaws.com/327565b4-2837-45a5-9c5a-e02d7c6c0624/grafana-screenshot-per-server-metrics-nemesis-20190824_032210-0.png
< t:2019-08-24 03:23:34,656 f:common.py       l:328  c:utils                p:INFO  > Uploading '/sct/20190819-131620-166949/longevity-tls-50gb-4d-3-1-monitor-set-327565b4/longevity-tls-50gb-4d-3-1-monitor-node-327565b4-1/grafana-screenshot-overview-metrics-20190824_032323-0.png' to https://cloudius-jenkins-test.s3.amazonaws.com/327565b4-2837-45a5-9c5a-e02d7c6c0624/grafana-screenshot-overview-metrics-20190824_032323-0.png
< t:2019-08-24 03:24:35,961 f:cluster.py      l:3740 c:sdcm.cluster         p:INFO  > Uploading 'annotations.json' to https://cloudius-jenkins-test.s3.amazonaws.com/327565b4-2837-45a5-9c5a-e02d7c6c0624/annotations.json
< t:2019-08-24 03:24:39,222 f:common.py       l:328  c:utils                p:INFO  > Uploading '/sct/events_log.zip' to https://cloudius-jenkins-test.s3.amazonaws.com/327565b4-2837-45a5-9c5a-e02d7c6c0624/events_log.zip
< t:2019-08-24 03:25:56,959 f:common.py       l:328  c:utils                p:INFO  > Uploading '/sct/20190819-131620-166949/job_log.zip' to https://cloudius-jenkins-test.s3.amazonaws.com/327565b4-2837-45a5-9c5a-e02d7c6c0624/job_log.zip
```

**Comment by bentsi** [comment] 2019-08-28 14:18
unfortunately, logs are not available, need to close this issue

**Comment by yarongilor** [comment] 2019-09-01 15:01
Uploaded logs to gcloud in:
scratch.scylladb.com/issues/sct_4901.log.gz

**Comment by slivne** [comment] 2019-09-05 10:08
the logs prior to this are garbled a bit - many lines concatenated ... its hard to extract some 

@bhalevy the temp directories are something you worked on ...  
```
< t:2019-08-24 03:24:39,161 f:tester.py       l:1274 c:sdcm.tester          p:ERROR > 2019-08-23 14:30:27.625: (DatabaseLogEvent Severity.CRITICAL): type=SCHEMA_FAILURE regex=Failed to load schema version line_n
umber=642347 node=Node longevity-tls-50gb-4d-3-1-db-node-327565b4-7 [3.95.149.37 | 172.30.0.228] (seed: False)
< t:2019-08-24 03:24:39,161 f:tester.py       l:1274 c:sdcm.tester          p:ERROR > 2019-08-22T23:40:26+00:00  ip-172-30-0-228 !WARNING | scylla.bin: [shard 0] storage_proxy - Failed to apply mutation from 172
.30.0.154#0: std::_Nested_exception<schema_version_loading_failed> (Failed to load schema version c7d0c698-37fe-3a92-b2d8-ddc3f4619bd1): std::_Nested_exception<no_such_keyspace> (Can't find a keyspace keyspace_d
eflate): std::out_of_range (_Map_base::at)
< t:2019-08-24 03:24:39,161 f:tester.py       l:1274 c:sdcm.tester          p:ERROR > 2019-08-23 14:30:28.687: (DatabaseLogEvent Severity.CRITICAL): type=FILESYSTEM_ERROR regex=filesystem_error line_number=64320
2 node=Node longevity-tls-50gb-4d-3-1-db-node-327565b4-7 [3.95.149.37 | 172.30.0.228] (seed: False)
< t:2019-08-24 03:24:39,161 f:tester.py       l:1274 c:sdcm.tester          p:ERROR > 2019-08-22T23:41:23+00:00  ip-172-30-0-228 !ERR     | scylla.bin: [shard 3] sstable - Could not create SSTable component /var/lib/scylla/data/keyspace_snappy/standard1-fbed93f0c28911e9b393000000000009/0000000000000031.sstable/mc-31-big-Filter.db. Found exception: std::filesystem::__cxx11::filesystem_error (error system:2, filesystem error: open failed: No such file or directory [/var/lib/scylla/data/keyspace_snappy/standard1-fbed93f0c28911e9b393000000000009/0000000000000031.sstable/mc-31-big-Filter.db])
< t:2019-08-24 03:24:39,161 f:tester.py       l:1274 c:sdcm.tester          p:ERROR > 2019-08-23 14:30:28.823: (DatabaseLogEvent Severity.CRITICAL): type=FILESYSTEM_ERROR regex=filesystem_error line_number=643308 node=Node longevity-tls-50gb-4d-3-1-db-node-327565b4-7 [3.95.149.37 | 172.30.0.228] (seed: False)
< t:2019-08-24 03:24:39,161 f:tester.py       l:1274 c:sdcm.tester          p:ERROR > 2019-08-22T23:41:28+00:00  ip-172-30-0-228 !ERR     | scylla.bin: [shard 8] compaction_manager - compaction failed: std::filesystem::__cxx11::filesystem_error (error system:2, filesystem error: mkdir failed: No such file or directory [/var/lib/scylla/data/keyspace_snappy/standard1-fbed93f0c28911e9b393000000000009/0000000000000106.sstable]): retrying
```

**Comment by bhalevy** [comment] 2019-09-05 17:30
Here is the node's log: [172-30-0-228.log.gz](https://github.com/scylladb/scylla/files/3580327/172-30-0-228.log.gz))

This looks like some kind of human error, or could it be a problem with SCT automation?
@bentsi?

```
The node rebootted and apparently bootstrapped here:
< t:2019-08-23 14:30:26,501 f:cluster.py      l:1212 c:sdcm.cluster         p:DEBUG > 2019-08-22T23:40:13+00:00  ip-172-30-0-228 !NOTICE  | kernel: Linux version 5.2.9-1.el7.elrepo.x86_64 (mockbuild@Build64R7) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-39) (GCC)) #1 SMP Fri Aug 16 08:17:55 EDT 2019
...
< t:2019-08-23 14:30:28,646 f:cluster.py      l:1212 c:sdcm.cluster         p:DEBUG > 2019-08-22T23:41:19+00:00  ip-172-30-0-228 !INFO    | scylla.bin: [shard 3] stream_session - [Stream #51e9e664-c536-11e9-9d88-000000000000] Write to sstable for ks=keyspace_snappy, cf=standard1, estimated_partitions=87817, received_partitions=79917
< t:2019-08-23 14:30:28,647 f:cluster.py      l:1212 c:sdcm.cluster         p:DEBUG > 2019-08-22T23:41:19+00:00  ip-172-30-0-228 !INFO    | scylla.bin: [shard 3] compaction - Compacting [/var/lib/scylla/data/keyspace_snappy/standard1-fbed93f0c28911e9b393000000000009/mc-59-big-Data.db:level=0, /var/lib/scylla/data/keyspace_snappy/standard1-fbed93f0c28911e9b393000000000009/mc-17-big-Data.db:level=0, ]

Things look normal at this point

Then the ENOENT errors start as if something changed the directory structure externally so there's a missing component in the path of the sstable files.

< t:2019-08-23 14:30:28,685 f:cluster.py      l:1212 c:sdcm.cluster         p:DEBUG > 2019-08-22T23:41:23+00:00  ip-172-30-0-228 !ERR     | scylla.bin: [shard 3] sstable - Could not create SSTable component /var/lib/scylla/data/keyspace_snappy/standard1-fbed93f0c28911e9b393000000000009/0000000000000031.sstable/mc-31-big-Filter.db. Found exception: std::filesystem::__cxx11::filesystem_error (error system:2, filesystem error: open failed: No such file or directory [/var/lib/scylla/data/keyspace_snappy/standard1-fbed93f0c28911e9b393000000000009/0000000000000031.sstable/mc-31-big-Filter.db])
< t:2019-08-23 14:30:28,687 f:cluster.py      l:1212 c:sdcm.cluster         p:DEBUG > 2019-08-22T23:41:23+00:00  ip-172-30-0-228 !ERR     | scylla.bin: [shard 1] sstable - Could not remove temporary directory: std::filesystem::__cxx11::filesystem_error (error system:2, filesystem error: remove failed: No such file or directory [/var/lib/scylla/data/keyspace_snappy/standard1-fbed93f0c28911e9b393000000000009/0000000000000029.sstable])
...
< t:2019-08-23 14:30:28,694 f:cluster.py      l:1212 c:sdcm.cluster         p:DEBUG > 2019-08-22T23:41:23+00:00  ip-172-30-0-228 !WARNING | scylla.bin: [shard 0] range_streamer - Bootstrap with 172.30.0.32 for keyspace=keyspace_snappy failed, took 13.141 seconds: streaming::stream_exception (Stream failed)
...

Scylla service is then restarted:

< t:2019-08-23 14:30:29,179 f:cluster.py      l:1212 c:sdcm.cluster         p:DEBUG > 2019-08-22T23:42:58+00:00  ip-172-30-0-228 !WARNING | systemd: scylla-server.service stop-sigterm timed out. Killing.
< t:2019-08-23 14:30:29,181 f:cluster.py      l:1212 c:sdcm.cluster         p:DEBUG > 2019-08-22T23:42:58+00:00  ip-172-30-0-228 !NOTICE  | systemd: scylla-server.service: main process exited, code=killed, statu
s=9/KILL
< t:2019-08-23 14:30:29,182 f:cluster.py      l:1212 c:sdcm.cluster         p:DEBUG > 2019-08-22T23:42:58+00:00  ip-172-30-0-228 !INFO    | systemd: Stopped Scylla Server.
< t:2019-08-23 14:30:29,183 f:cluster.py      l:1212 c:sdcm.cluster         p:DEBUG > 2019-08-22T23:42:58+00:00  ip-172-30-0-228 !NOTICE  | systemd: Unit scylla-server.service entered failed state.
< t:2019-08-23 14:30:29,184 f:cluster.py      l:1212 c:sdcm.cluster         p:DEBUG > 2019-08-22T23:42:58+00:00  ip-172-30-0-228 !WARNING | systemd: scylla-server.service failed.
< t:2019-08-23 14:30:29,185 f:cluster.py      l:1212 c:sdcm.cluster         p:DEBUG > 2019-08-22T23:42:58+00:00  ip-172-30-0-228 !INFO    | sudo: pam_unix(sudo:session): session closed for user root
< t:2019-08-23 14:30:29,186 f:cluster.py      l:1212 c:sdcm.cluster         p:DEBUG > 2019-08-22T23:43:01+00:00  ip-172-30-0-228 !NOTICE  | sudo:  centos : TTY=unknown ; PWD=/home/centos ; USER=root ; COMMAND=/b
in/systemctl start scylla-server.service
...

and things go back to normal;
< t:2019-08-23 14:30:30,439 f:cluster.py      l:1212 c:sdcm.cluster         p:DEBUG > 2019-08-22T23:44:01+00:00  ip-172-30-0-228 !INFO    | scylla.bin: [shard 3] compaction - Compacting [/var/lib/scylla/data/keyspace_snappy/standard1-fbed93f0c28911e9b393000000000009/mc-31-big-Data.db:level=0, /var/lib/scylla/data/keyspace_snappy/standard1-fbed93f0c28911e9b393000000000009/mc-17-big-Data.db:level=0, ]
```

@bentsi there are also several coredumpctl messages in the above log, followed by massive journal suppression messages form scylla-server.service look like crashes, do we have those coredumps?

Also, @asias, it seems like gossip is spewing the log with `unknown endpoint` messages.  Can you please verify and open an issue?

```
< t:2019-08-19 14:37:17,897 f:cluster.py      l:1212 c:sdcm.cluster         p:DEBUG > 2019-08-19T14:37:10+00:00  ip-172-30-0-228 !INFO    | journal: Suppressed 235242 messages from /system.slice/scylla-server.service
< t:2019-08-19 14:37:17,897 f:cluster.py      l:1212 c:sdcm.cluster         p:DEBUG > 2019-08-19T14:37:10+00:00  ip-172-30-0-228 !WARNING | scylla.bin: [shard 0] gossip - unknown endpoint 172.30.0.164
< t:2019-08-19 14:37:17,897 f:cluster.py      l:1212 c:sdcm.cluster         p:DEBUG > 2019-08-19T14:37:10+00:00  ip-172-30-0-228 !WARNING | scylla.bin: [shard 6] gossip - unknown endpoint 172.30.0.164
< t:2019-08-19 14:37:17,897 f:cluster.py      l:1212 c:sdcm.cluster         p:DEBUG > 2019-08-19T14:37:10+00:00  ip-172-30-0-228 !WARNING | scylla.bin: [shard 8] gossip - unknown endpoint 172.30.0.164
... a burst of these
< t:2019-08-19 14:37:35,378 f:cluster.py      l:1212 c:sdcm.cluster         p:DEBUG > 2019-08-19T14:37:35+00:00  ip-172-30-0-228 !INFO    | scylla.bin: [shard 9] compaction - Compacted 2 sstables to [/var/lib/scylla/data/keyspace_snappy/standard1-fbed93f0c28911e9b393000000000009/mc-191-big-Data.db:level=0, ]. 166563324 bytes to 162201025 (~97% of original) in 40179ms = 3.85MB/s. ~724608 total partitions merged to 706148.
< t:2019-08-19 14:37:50,379 f:cluster.py      l:1212 c:sdcm.cluster         p:DEBUG > 019-08-19T14:37:40+00:00  ip-172-30-0-228 !INFO    | journal: Suppressed 271319 messages from /system.slice/scylla-server.service
< t:2019-08-19 14:37:50,380 f:cluster.py      l:1212 c:sdcm.cluster         p:DEBUG > 2019-08-19T14:37:40+00:00  ip-172-30-0-228 !WARNING | scylla.bin: [shard 0] gossip - unknown endpoint 172.30.0.164
... another burst of these
```

**Comment by slivne** [comment] 2019-09-09 07:21
@bentsi / @bhalevy - please look at this together and update the issue with the joint analysis

**Comment by bhalevy** [comment] 2019-09-09 15:57
@bentsi what nemesis were run here?
Can we rule out that the data directory wan't removed by mistake while the node was up?

**Comment by bentsi** [comment] 2019-09-09 16:24
Nemesis that ran during the time of the issu:
```
2019-08-22 18:13:24.257: (DisruptionEvent): type=start name=Refresh node=Node longevity-tls-50gb-4d-3-1-db-node-327565b4-9 [3.82.252.180 | 172.30.0.212] (seed: False) duration=None
2019-08-22 18:26:27.950: (DisruptionEvent): type=end name=Refresh node=Node longevity-tls-50gb-4d-3-1-db-node-327565b4-9 [3.82.252.180 | 172.30.0.212] (seed: False) duration=778
2019-08-22 18:48:07.678: (DisruptionEvent): type=start name=Refresh node=Node longevity-tls-50gb-4d-3-1-db-node-327565b4-7 [35.170.187.63 | 172.30.0.228] (seed: False) duration=None
2019-08-22 18:55:38.833: (DisruptionEvent): type=end name=Refresh node=Node longevity-tls-50gb-4d-3-1-db-node-327565b4-7 [35.170.187.63 | 172.30.0.228] (seed: False) duration=447
2019-08-22 19:17:07.744: (DisruptionEvent): type=start name=MajorCompaction node=Node longevity-tls-50gb-4d-3-1-db-node-327565b4-8 [34.201.37.233 | 172.30.0.32] (seed: False) duration=None
2019-08-22 19:55:48.767: (DisruptionEvent): type=end name=MajorCompaction node=Node longevity-tls-50gb-4d-3-1-db-node-327565b4-8 [34.201.37.233 | 172.30.0.32] (seed: False) duration=2315
2019-08-22 20:17:38.951: (DisruptionEvent): type=start name=ShowTopPartitions node=Node longevity-tls-50gb-4d-3-1-db-node-327565b4-4 [54.208.165.8 | 172.30.0.185] (seed: False) duration=None
2019-08-22 20:39:42.682: (DisruptionEvent): type=end name=ShowTopPartitions node=Node longevity-tls-50gb-4d-3-1-db-node-327565b4-4 [54.208.165.8 | 172.30.0.185] (seed: False) duration=1319
2019-08-22 21:02:07.451: (DisruptionEvent): type=start name=StopStartService node=Node longevity-tls-50gb-4d-3-1-db-node-327565b4-8 [34.201.37.233 | 172.30.0.32] (seed: False) duration=None
2019-08-22 21:04:02.986: (DisruptionEvent): type=end name=StopStartService node=Node longevity-tls-50gb-4d-3-1-db-node-327565b4-8 [34.201.37.233 | 172.30.0.32] (seed: False) duration=112
2019-08-22 21:26:23.187: (DisruptionEvent): type=start name=NoCorruptRepair node=Node longevity-tls-50gb-4d-3-1-db-node-327565b4-7 [35.170.187.63 | 172.30.0.228] (seed: False) duration=None
2019-08-22 23:17:33.137: (DisruptionEvent): type=end name=NoCorruptRepair node=Node longevity-tls-50gb-4d-3-1-db-node-327565b4-7 [35.170.187.63 | 172.30.0.228] (seed: False) duration=6662
2019-08-22 23:38:31.928: (DisruptionEvent): type=start name=RestartThenRepairNode node=Node longevity-tls-50gb-4d-3-1-db-node-327565b4-7 [35.170.187.63 | 172.30.0.228] (seed: False) duration=None
2019-08-23 02:06:22.927: (DisruptionEvent): type=end name=RestartThenRepairNode node=Node longevity-tls-50gb-4d-3-1-db-node-327565b4-7 [35.170.187.63 | 172.30.0.228] (seed: False) duration=8866
2019-08-23 02:27:16.247: (DisruptionEvent): type=start name=MajorCompaction node=Node longevity-tls-50gb-4d-3-1-db-node-327565b4-9 [3.82.252.180 | 172.30.0.212] (seed: False) duration=None
2019-08-23 09:10:44.629: (DisruptionEvent): type=end name=MajorCompaction node=Node longevity-tls-50gb-4d-3-1-db-node-327565b4-9 [3.82.252.180 | 172.30.0.212] (seed: False) duration=24202
2019-08-23 09:31:21.121: (DisruptionEvent): type=start name=AbortRepairMonkey node=Node longevity-tls-50gb-4d-3-1-db-node-327565b4-4 [54.208.165.8 | 172.30.0.185] (seed: False) duration=None
2019-08-23 10:24:13.370: (DisruptionEvent): type=end name=AbortRepairMonkey node=Node longevity-tls-50gb-4d-3-1-db-node-327565b4-4 [54.208.165.8 | 172.30.0.185] (seed: False) duration=3163

```

**Comment by bentsi** [comment] 2019-09-09 16:40
RestartThenRepairNode nemesis stated before the the issue happened, after looking on the node log we see that `scylla_create_devices` is called. So this explains lost files. This is a bug in SCT, not Scylla issue. You can close this issue.
```
2019-08-22T23:41:10+00:00  ip-172-30-0-228 !INFO    | scylla.bin: [shard 0] stream_session - [Stream #51e9e664-c536-11e9-9d88-000000000000] Executing streaming plan for Bootstrap-keyspace_snappy-index-0 with peers={172.30.0.208}, master
2019-08-22T23:41:15+00:00  ip-172-30-0-228 !NOTICE  | sudo:  centos : TTY=unknown ; PWD=/home/centos ; USER=root ; COMMAND=/usr/lib/scylla/scylla-ami/scylla_create_devices
2019-08-22T23:41:15+00:00  ip-172-30-0-228 !INFO    | sudo: pam_unix(sudo:session): session opened for user root by (uid=0)
2019-08-22T23:41:16+00:00  ip-172-30-0-228 !INFO    | scylla.bin: [shard 4] stream_session - [Stream #51e9e660-c536-11e9-9d88-000000000000] Write to sstable for ks=keyspace_snappy, cf=standard1, estimated_partitions=82821, received_partitions=68852
...
2019-08-22T23:41:22+00:00  ip-172-30-0-228 !INFO    | scylla.bin: [shard 5] stream_session - [Stream #51e9e664-c536-11e9-9d88-000000000000] Write to sstable for ks=keyspace_snappy, cf=standard1, estimated_partitions=96260, received_partitions=80674
2019-08-22T23:41:23+00:00  ip-172-30-0-228 !INFO    | scylla.bin: [shard 9] stream_session - [Stream #51e9e663-c536-11e9-9d88-000000000000] Write to sstable for ks=keyspace_snappy, cf=standard1, estimated_partitions=109712, received_partitions=83238
2019-08-22T23:41:23+00:00  ip-172-30-0-228 !NOTICE  | kernel: XFS (md0): Mounting V5 Filesystem
2019-08-22T23:41:23+00:00  ip-172-30-0-228 !INFO    | kernel: XFS (md0): Ending clean mount
2019-08-22T23:41:23+00:00  ip-172-30-0-228 !ERR     | scylla.bin: [shard 3] sstable - Could not create SSTable component /var/lib/scylla/data/keyspace_snappy/standard1-fbed93f0c28911e9b393000000000009/0000000000000031.sstable/mc-31-big-Filter.db. Found exception: std::filesystem::__cxx11::filesystem_error (error system:2, filesystem error: open failed: No such file or directory [/var/lib/scylla/data/keyspace_snappy/standard1-fbed93f0c28911e9b393000000000009/0000000000000031.sstable/mc-31-big-Filter.db])
2019-08-22T23:41:23+00:00  ip-172-30-0-228 !ERR     | scylla.bin: [shard 1] sstable - Could not remove temporary directory: std::filesystem::__cxx11::filesystem_error (error system:2, filesystem error: remove failed: No such file or directory [/var/lib/scylla/data/keyspace_snappy/standard1-fbed93f0c28911e9b393000000000009/0000000000000029.sstable])
```

**Comment by amoskong** [comment] 2019-09-10 08:44
This issue is known, but not a real scylla issue, we can close it.

**Closed by amoskong** 2019-09-10 08:44 UTC
Labels: bug

**Comment by slivne** [comment] 2019-09-10 08:47
@bentsi / @amoskong  please open an SCT issue about this and link to it - I want this fixed - this bugs are to scary to leave them existing in SCT :)

**Comment by fruch** [comment] 2019-09-10 08:58
scylladb/scylla-cluster-tests#1297 should address this in SCT

**Comment by amoskong** [comment] 2019-09-10 08:58
> @bentsi / @amoskong please open an SCT issue about this and link to it - I want this fixed - this bugs are to scary to leave them existing in SCT :)

Existing SCT issues:
- https://github.com/scylladb/scylla-cluster-tests/issues/1298
- https://github.com/scylladb/scylla-enterprise/issues/905  (closed)

PRs
- old fix: https://github.com/scylladb/scylla-cluster-tests/pull/1040  (closed, not merge)
- new fix: https://github.com/scylladb/scylla-cluster-tests/pull/1297

Possible fix for SCT:
- option 1: don't setup RAID when scylla is running
- option 2: ignore the db error in setup RAID when scylla is running

**Comment by roydahan** [comment] 2019-09-11 19:23
@yarongilor you already reported such an issue on the the enterprise release a month ago and I closed it because it's not a real issue.

@slivne The nemesis starts the server after it lost the FS of scylla, so we get these errors when trying to start.
It looks scary out of context, but one who see these messages should understand the context and the cause.
Even with @bentsi "fix" where it stops scylla after the restart, we may see these errors and it's normal. we should have a filter for them already so we won't see them as critical event.
