### ISSUE TITLE
Schema crash in schema::make_legacy_default_validator during hundred_mv_concurrent_test

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#4870] opened 2019-08-20 07:39 UTC
Seen in [dtest-release/210/artifact/logs-release.2/1566037540299_materialized_views_test.TestMaterializedViews.hundred_mv_concurrent_test/node3.log](https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/210/artifact/logs-release.2/1566037540299_materialized_views_test.TestMaterializedViews.hundred_mv_concurrent_test/node3.log)
```
INFO  2019-08-17 10:24:39,307 [shard 0] database - Schema version changed to 45ba0052-8b7d-3dd8-a2e1-da9aefa9d3d9
Segmentation fault on shard 1.
Backtrace:
  0x00000000030e89e2
  0x0000000002fe2f75
  0x0000000002fe3275
  0x0000000002fe32c3
  0x00007f89d9a2702f
  0x0000000000a55b1f
  0x00000000008e0d7e
  0x000000000090ce37
  0x000000000090c9eb
  0x00000000008e7c8d
  0x000000000169dd5f
  0x0000000001cadf38
  0x000000000096e1f9
  0x00000000009cc9a5
  0x00000000009cd28b
  0x00000000009d5d85
  0x00000000009d9153
  0x00000000009da240
  0x00000000008e0de3
  0x000000000090ce37
  0x000000000090c9eb
  0x00000000008e7c8d
  0x000000000169dd5f
  0x0000000001cadf38
  0x000000000096ebfe
  0x0000000002fe01f1
  0x0000000002fe040e
  0x00000000030c3475
  0x00000000030e14eb
  0x0000000002fbb79d
  /jenkins/workspace/scylla-master/dtest-release/scylla-dtest/../scylla/dynamic_libs/libpthread.so.0+0x000000000000858d
  /jenkins/workspace/scylla-master/dtest-release/scylla-dtest/../scylla/dynamic_libs/libc.so.6+0x00000000000fd6a2
```
Decoded backtrace:
```
void seastar::backtrace<seastar::backtrace_buffer::append_backtrace()::{lambda(seastar::frame)#1}>(seastar::backtrace_buffer::append_backtrace()::{lambda(seastar::frame)#1}&&) at /jenkins/workspace/scylla-master/dtest-release/scylla/seastar/build/release/../../include/seastar/util/backtrace.hh:55
seastar::print_with_backtrace(seastar::backtrace_buffer&) at /jenkins/workspace/scylla-master/dtest-release/scylla/seastar/build/release/../../src/core/reactor.cc:1199
 (inlined by) print_with_backtrace at /jenkins/workspace/scylla-master/dtest-release/scylla/seastar/build/release/../../src/core/reactor.cc:1220
seastar::print_with_backtrace(char const*) at /jenkins/workspace/scylla-master/dtest-release/scylla/seastar/build/release/../../src/core/reactor.cc:1227
seastar::install_oneshot_signal_handler<11, &seastar::sigsegv_action>()::{lambda(int, siginfo_t*, void*)#1}::_FUN(int, siginfo_t*, void*) at /jenkins/workspace/scylla-master/dtest-release/scylla/seastar/build/release/../../src/core/reactor.cc:5260
 (inlined by) operator() at /jenkins/workspace/scylla-master/dtest-release/scylla/seastar/build/release/../../src/core/reactor.cc:5246
 (inlined by) _FUN at /jenkins/workspace/scylla-master/dtest-release/scylla/seastar/build/release/../../src/core/reactor.cc:5242
?? ??:0
schema::make_legacy_default_validator() const at /jenkins/workspace/scylla-master/dtest-release/scylla/schema.cc:1248
database::do_apply(seastar::lw_shared_ptr<schema const>, frozen_mutation const&, std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >) at /jenkins/workspace/scylla-master/dtest-release/scylla/database.cc:1475
seastar::noncopyable_function<seastar::future<> (database*, seastar::lw_shared_ptr<schema const>, frozen_mutation const&, std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)>::direct_vtable_for<std::_Mem_fn<seastar::future<> (database::*)(seastar::lw_shared_ptr<schema const>, frozen_mutation const&, std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)> >::call(seastar::noncopyable_function<seastar::future<> (database*, seastar::lw_shared_ptr<schema const>, frozen_mutation const&, std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)> const*, database*, seastar::lw_shared_ptr<schema const>, frozen_mutation const&, std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >) at /usr/include/c++/8/bits/invoke.h:73
 (inlined by) ?? at /usr/include/c++/8/bits/invoke.h:96
 (inlined by) ?? at /usr/include/c++/8/functional:114
 (inlined by) seastar::noncopyable_function<seastar::future<> (database*, seastar::lw_shared_ptr<schema const>, frozen_mutation const&, std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)>::direct_vtable_for<std::_Mem_fn<seastar::future<> (database::*)(seastar::lw_shared_ptr<schema const>, frozen_mutation const&, std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)> >::call(seastar::noncopyable_function<seastar::future<> (database*, seastar::lw_shared_ptr<schema const>, frozen_mutation const&, std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)> const*, database*, seastar::lw_shared_ptr<schema const>, frozen_mutation const&, std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >) at /jenkins/workspace/scylla-master/dtest-release/scylla/seastar/include/seastar/util/noncopyable_function.hh:71
seastar::noncopyable_function<seastar::future<> (database*, seastar::lw_shared_ptr<schema const>, frozen_mutation const&, std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)>::direct_vtable_for<seastar::inheriting_concrete_execution_stage<seastar::future<>, database*, seastar::lw_shared_ptr<schema const>, frozen_mutation const&, std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > > >::make_stage_for_group(seastar::scheduling_group)::{lambda(database*, seastar::lw_shared_ptr<schema const>, frozen_mutation const&, std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)#1}>::call(seastar::noncopyable_function<seastar::future<> (database*, seastar::lw_shared_ptr<schema const>, frozen_mutation const&, std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)> const*, database*, seastar::lw_shared_ptr<schema const>, frozen_mutation const&, std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >) at /jenkins/workspace/scylla-master/dtest-release/scylla/seastar/include/seastar/util/noncopyable_function.hh:145
 (inlined by) seastar::inheriting_concrete_execution_stage<seastar::future<>, database*, seastar::lw_shared_ptr<schema const>, frozen_mutation const&, std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > > >::make_stage_for_group(seastar::scheduling_group)::{lambda(database*, seastar::lw_shared_ptr<schema const>, frozen_mutation const&, std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)#1}::operator()(database*, seastar::lw_shared_ptr<schema const>, frozen_mutation const&, std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >) const at /jenkins/workspace/scylla-master/dtest-release/scylla/seastar/include/seastar/core/execution_stage.hh:327
 (inlined by) seastar::noncopyable_function<seastar::future<> (database*, seastar::lw_shared_ptr<schema const>, frozen_mutation const&, std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)>::direct_vtable_for<seastar::inheriting_concrete_execution_stage<seastar::future<>, database*, seastar::lw_shared_ptr<schema const>, frozen_mutation const&, std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > > >::make_stage_for_group(seastar::scheduling_group)::{lambda(database*, seastar::lw_shared_ptr<schema const>, frozen_mutation const&, std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)#1}>::call(seastar::noncopyable_function<seastar::future<> (database*, seastar::lw_shared_ptr<schema const>, frozen_mutation const&, std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)> const*, database*, seastar::lw_shared_ptr<schema const>, frozen_mutation const&, std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >) at /jenkins/workspace/scylla-master/dtest-release/scylla/seastar/include/seastar/util/noncopyable_function.hh:71
database::apply(seastar::lw_shared_ptr<schema const>, frozen_mutation const&, std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >) at /jenkins/workspace/scylla-master/dtest-release/scylla/seastar/include/seastar/util/noncopyable_function.hh:145
 (inlined by) ?? at /jenkins/workspace/scylla-master/dtest-release/scylla/seastar/include/seastar/core/apply.hh:35
 (inlined by) ?? at /jenkins/workspace/scylla-master/dtest-release/scylla/seastar/include/seastar/core/apply.hh:43
 (inlined by) ?? at /jenkins/workspace/scylla-master/dtest-release/scylla/seastar/include/seastar/core/future.hh:1414
 (inlined by) ?? at /jenkins/workspace/scylla-master/dtest-release/scylla/seastar/include/seastar/core/execution_stage.hh:244
 (inlined by) ?? at /jenkins/workspace/scylla-master/dtest-release/scylla/seastar/include/seastar/core/execution_stage.hh:289
 (inlined by) ?? at /jenkins/workspace/scylla-master/dtest-release/scylla/seastar/include/seastar/core/execution_stage.hh:370
 (inlined by) database::apply(seastar::lw_shared_ptr<schema const>, frozen_mutation const&, std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >) at /jenkins/workspace/scylla-master/dtest-release/scylla/database.cc:1517
operator() at /jenkins/workspace/scylla-master/dtest-release/scylla/service/storage_proxy.cc:960
 (inlined by) operator() at /jenkins/workspace/scylla-master/dtest-release/scylla/seastar/include/seastar/core/sharded.hh:424
 (inlined by) ?? at /jenkins/workspace/scylla-master/dtest-release/scylla/seastar/include/seastar/core/future.hh:1424
 (inlined by) ?? at /jenkins/workspace/scylla-master/dtest-release/scylla/seastar/include/seastar/core/reactor.hh:978
 (inlined by) ?? at /jenkins/workspace/scylla-master/dtest-release/scylla/seastar/include/seastar/core/sharded.hh:425
 (inlined by) service::storage_proxy::mutate_locally(seastar::lw_shared_ptr<schema const> const&, frozen_mutation const&, std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >) at /jenkins/workspace/scylla-master/dtest-release/scylla/service/storage_proxy.cc:961
db::view::mutate_MV(dht::token const&, std::vector<frozen_mutation_and_schema, std::allocator<frozen_mutation_and_schema> >, db::view::stats&, cf_stats&, seastar::semaphore_units<seastar::default_timeout_exception_factory, seastar::lowres_clock>, seastar::bool_class<service::allow_hints_tag>) at /jenkins/workspace/scylla-master/dtest-release/scylla/db/view/view.cc:1071
operator() at /jenkins/workspace/scylla-master/dtest-release/scylla/table.cc:2086
 (inlined by) ?? at /jenkins/workspace/scylla-master/dtest-release/scylla/seastar/include/seastar/core/apply.hh:35
 (inlined by) ?? at /jenkins/workspace/scylla-master/dtest-release/scylla/seastar/include/seastar/core/apply.hh:43
 (inlined by) ?? at /jenkins/workspace/scylla-master/dtest-release/scylla/seastar/include/seastar/core/future.hh:1368
table::generate_and_propagate_view_updates(seastar::lw_shared_ptr<schema const> const&, std::vector<view_ptr, std::allocator<view_ptr> >&&, mutation&&, seastar::optimized_optional<flat_mutation_reader>) const at /jenkins/workspace/scylla-master/dtest-release/scylla/seastar/include/seastar/core/future.hh:1402
 (inlined by) ?? at /jenkins/workspace/scylla-master/dtest-release/scylla/seastar/include/seastar/core/future.hh:986
 (inlined by) ?? at /jenkins/workspace/scylla-master/dtest-release/scylla/seastar/include/seastar/core/future.hh:967
 (inlined by) table::generate_and_propagate_view_updates(seastar::lw_shared_ptr<schema const> const&, std::vector<view_ptr, std::allocator<view_ptr> >&&, mutation&&, seastar::optimized_optional<flat_mutation_reader>) const at /jenkins/workspace/scylla-master/dtest-release/scylla/table.cc:2087
operator()<nonwrapping_range<dht::ring_position>, query::partition_slice, mutation> at /jenkins/workspace/scylla-master/dtest-release/scylla/table.cc:2530
 (inlined by) ?? at /jenkins/workspace/scylla-master/dtest-release/scylla/seastar/include/seastar/core/apply.hh:35
 (inlined by) ?? at /jenkins/workspace/scylla-master/dtest-release/scylla/seastar/include/seastar/core/apply.hh:50
 (inlined by) do_with<nonwrapping_range<dht::ring_position>, const query::partition_slice, const mutation, table::do_push_view_replica_updates(const schema_ptr&, mutation&&, seastar::lowres_clock::time_point, mutation_source&&) const::<lambda(row_locker::lock_holder)>::<lambda(auto:171&, auto:172&, auto:173&)> > at /jenkins/workspace/scylla-master/dtest-release/scylla/seastar/include/seastar/core/do_with.hh:152
operator() at /jenkins/workspace/scylla-master/dtest-release/scylla/table.cc:2531
 (inlined by) ?? at /jenkins/workspace/scylla-master/dtest-release/scylla/seastar/include/seastar/core/apply.hh:35
 (inlined by) ?? at /jenkins/workspace/scylla-master/dtest-release/scylla/seastar/include/seastar/core/apply.hh:43
 (inlined by) ?? at /jenkins/workspace/scylla-master/dtest-release/scylla/seastar/include/seastar/core/future.hh:1414
 (inlined by) then_impl<table::do_push_view_replica_updates(const schema_ptr&, mutation&&, seastar::lowres_clock::time_point, mutation_source&&) const::<lambda(row_locker::lock_holder)> > at /jenkins/workspace/scylla-master/dtest-release/scylla/seastar/include/seastar/core/future.hh:986
table::do_push_view_replica_updates(seastar::lw_shared_ptr<schema const> const&, mutation&&, std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >, mutation_source&&) const [clone .constprop.5033] at /jenkins/workspace/scylla-master/dtest-release/scylla/seastar/include/seastar/core/future.hh:967
 (inlined by) ?? at /jenkins/workspace/scylla-master/dtest-release/scylla/table.cc:2532
table::push_view_replica_updates(seastar::lw_shared_ptr<schema const> const&, frozen_mutation const&, std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >) const at /jenkins/workspace/scylla-master/dtest-release/scylla/table.cc:2536
 (inlined by) table::push_view_replica_updates(seastar::lw_shared_ptr<schema const> const&, frozen_mutation const&, std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >) const at /jenkins/workspace/scylla-master/dtest-release/scylla/table.cc:2475
database::do_apply(seastar::lw_shared_ptr<schema const>, frozen_mutation const&, std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >) at /jenkins/workspace/scylla-master/dtest-release/scylla/database.cc:1486
seastar::noncopyable_function<seastar::future<> (database*, seastar::lw_shared_ptr<schema const>, frozen_mutation const&, std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)>::direct_vtable_for<std::_Mem_fn<seastar::future<> (database::*)(seastar::lw_shared_ptr<schema const>, frozen_mutation const&, std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)> >::call(seastar::noncopyable_function<seastar::future<> (database*, seastar::lw_shared_ptr<schema const>, frozen_mutation const&, std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)> const*, database*, seastar::lw_shared_ptr<schema const>, frozen_mutation const&, std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >) at /usr/include/c++/8/bits/invoke.h:73
 (inlined by) ?? at /usr/include/c++/8/bits/invoke.h:96
 (inlined by) ?? at /usr/include/c++/8/functional:114
 (inlined by) seastar::noncopyable_function<seastar::future<> (database*, seastar::lw_shared_ptr<schema const>, frozen_mutation const&, std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)>::direct_vtable_for<std::_Mem_fn<seastar::future<> (database::*)(seastar::lw_shared_ptr<schema const>, frozen_mutation const&, std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)> >::call(seastar::noncopyable_function<seastar::future<> (database*, seastar::lw_shared_ptr<schema const>, frozen_mutation const&, std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)> const*, database*, seastar::lw_shared_ptr<schema const>, frozen_mutation const&, std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >) at /jenkins/workspace/scylla-master/dtest-release/scylla/seastar/include/seastar/util/noncopyable_function.hh:71
seastar::noncopyable_function<seastar::future<> (database*, seastar::lw_shared_ptr<schema const>, frozen_mutation const&, std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)>::direct_vtable_for<seastar::inheriting_concrete_execution_stage<seastar::future<>, database*, seastar::lw_shared_ptr<schema const>, frozen_mutation const&, std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > > >::make_stage_for_group(seastar::scheduling_group)::{lambda(database*, seastar::lw_shared_ptr<schema const>, frozen_mutation const&, std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)#1}>::call(seastar::noncopyable_function<seastar::future<> (database*, seastar::lw_shared_ptr<schema const>, frozen_mutation const&, std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)> const*, database*, seastar::lw_shared_ptr<schema const>, frozen_mutation const&, std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >) at /jenkins/workspace/scylla-master/dtest-release/scylla/seastar/include/seastar/util/noncopyable_function.hh:145
 (inlined by) seastar::inheriting_concrete_execution_stage<seastar::future<>, database*, seastar::lw_shared_ptr<schema const>, frozen_mutation const&, std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > > >::make_stage_for_group(seastar::scheduling_group)::{lambda(database*, seastar::lw_shared_ptr<schema const>, frozen_mutation const&, std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)#1}::operator()(database*, seastar::lw_shared_ptr<schema const>, frozen_mutation const&, std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >) const at /jenkins/workspace/scylla-master/dtest-release/scylla/seastar/include/seastar/core/execution_stage.hh:327
 (inlined by) seastar::noncopyable_function<seastar::future<> (database*, seastar::lw_shared_ptr<schema const>, frozen_mutation const&, std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)>::direct_vtable_for<seastar::inheriting_concrete_execution_stage<seastar::future<>, database*, seastar::lw_shared_ptr<schema const>, frozen_mutation const&, std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > > >::make_stage_for_group(seastar::scheduling_group)::{lambda(database*, seastar::lw_shared_ptr<schema const>, frozen_mutation const&, std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)#1}>::call(seastar::noncopyable_function<seastar::future<> (database*, seastar::lw_shared_ptr<schema const>, frozen_mutation const&, std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)> const*, database*, seastar::lw_shared_ptr<schema const>, frozen_mutation const&, std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >) at /jenkins/workspace/scylla-master/dtest-release/scylla/seastar/include/seastar/util/noncopyable_function.hh:71
database::apply(seastar::lw_shared_ptr<schema const>, frozen_mutation const&, std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >) at /jenkins/workspace/scylla-master/dtest-release/scylla/seastar/include/seastar/util/noncopyable_function.hh:145
 (inlined by) ?? at /jenkins/workspace/scylla-master/dtest-release/scylla/seastar/include/seastar/core/apply.hh:35
 (inlined by) ?? at /jenkins/workspace/scylla-master/dtest-release/scylla/seastar/include/seastar/core/apply.hh:43
 (inlined by) ?? at /jenkins/workspace/scylla-master/dtest-release/scylla/seastar/include/seastar/core/future.hh:1414
 (inlined by) ?? at /jenkins/workspace/scylla-master/dtest-release/scylla/seastar/include/seastar/core/execution_stage.hh:244
 (inlined by) ?? at /jenkins/workspace/scylla-master/dtest-release/scylla/seastar/include/seastar/core/execution_stage.hh:289
 (inlined by) ?? at /jenkins/workspace/scylla-master/dtest-release/scylla/seastar/include/seastar/core/execution_stage.hh:370
 (inlined by) database::apply(seastar::lw_shared_ptr<schema const>, frozen_mutation const&, std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >) at /jenkins/workspace/scylla-master/dtest-release/scylla/database.cc:1517
operator() at /jenkins/workspace/scylla-master/dtest-release/scylla/service/storage_proxy.cc:960
 (inlined by) operator() at /jenkins/workspace/scylla-master/dtest-release/scylla/seastar/include/seastar/core/sharded.hh:424
 (inlined by) ?? at /jenkins/workspace/scylla-master/dtest-release/scylla/seastar/include/seastar/core/future.hh:1424
 (inlined by) ?? at /jenkins/workspace/scylla-master/dtest-release/scylla/seastar/include/seastar/core/reactor.hh:978
 (inlined by) ?? at /jenkins/workspace/scylla-master/dtest-release/scylla/seastar/include/seastar/core/sharded.hh:425
 (inlined by) service::storage_proxy::mutate_locally(seastar::lw_shared_ptr<schema const> const&, frozen_mutation const&, std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >) at /jenkins/workspace/scylla-master/dtest-release/scylla/service/storage_proxy.cc:961
db::view::mutate_MV(dht::token const&, std::vector<frozen_mutation_and_schema, std::allocator<frozen_mutation_and_schema> >, db::view::stats&, cf_stats&, seastar::semaphore_units<seastar::default_timeout_exception_factory, seastar::lowres_clock>, seastar::bool_class<service::allow_hints_tag>) at /jenkins/workspace/scylla-master/dtest-release/scylla/db/view/view.cc:1071
operator() at /jenkins/workspace/scylla-master/dtest-release/scylla/table.cc:2086
 (inlined by) ?? at /jenkins/workspace/scylla-master/dtest-release/scylla/seastar/include/seastar/core/apply.hh:35
 (inlined by) ?? at /jenkins/workspace/scylla-master/dtest-release/scylla/seastar/include/seastar/core/apply.hh:43
 (inlined by) ?? at /jenkins/workspace/scylla-master/dtest-release/scylla/seastar/include/seastar/core/future.hh:1368
 (inlined by) ?? at /jenkins/workspace/scylla-master/dtest-release/scylla/seastar/include/seastar/core/future.hh:1402
 (inlined by) operator() at /jenkins/workspace/scylla-master/dtest-release/scylla/seastar/include/seastar/core/future.hh:1000
 (inlined by) run_and_dispose at /jenkins/workspace/scylla-master/dtest-release/scylla/seastar/include/seastar/core/future.hh:400
seastar::reactor::run_tasks(seastar::reactor::task_queue&) at /jenkins/workspace/scylla-master/dtest-release/scylla/seastar/build/release/../../src/core/reactor.cc:3821
seastar::reactor::run_some_tasks() [clone .part.3053] at /jenkins/workspace/scylla-master/dtest-release/scylla/seastar/build/release/../../src/core/reactor.cc:4248
seastar::reactor::run() at /jenkins/workspace/scylla-master/dtest-release/scylla/seastar/build/release/../../src/core/reactor.cc:4231
 (inlined by) seastar::reactor::run() at /jenkins/workspace/scylla-master/dtest-release/scylla/seastar/build/release/../../src/core/reactor.cc:4392
seastar::smp::configure(boost::program_options::variables_map, seastar::reactor_config)::{lambda()#3}::operator()() const at /jenkins/workspace/scylla-master/dtest-release/scylla/seastar/build/release/../../src/core/reactor.cc:5657
seastar::posix_thread::start_routine(void*) at /usr/include/c++/8/bits/std_function.h:687
 (inlined by) seastar::posix_thread::start_routine(void*) at /jenkins/workspace/scylla-master/dtest-release/scylla/seastar/build/release/../../src/core/posix.cc:52
```

Core file: [node3-reactor-1.41405.1566037493.core.gz](https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/210/artifact/logs-release.2/1566037540299_materialized_views_test.TestMaterializedViews.hundred_mv_concurrent_test/node3-reactor-1.41405.1566037493.core.gz)
Binary: [scylla](https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/210/artifact/logs-release.2/scylla)

**Comment by bhalevy** [comment] 2019-08-20 07:40
@psarna can you please analyze this crash?

**Comment by psarna** [comment] 2019-08-20 07:54
@bhalevy it looks like a duplicate of https://github.com/scylladb/scylla/issues/4856 which I found a couple of days ago, but still haven't figured out what's wrong.
You can read my latest conclusions in the issue above.

**Comment by tzach** [comment] 2019-08-26 07:11
@bhalevy @psarna if this is dup with #4856 can we close this issue?

**Comment by psarna** [comment] 2019-08-26 09:42
@tzach yes we can

**Closed** 2019-08-26 12:28 UTC
Labels: bug, dtest
