### ISSUE TITLE
alternator: nodetool cannot work on table with a dot in its name

### ISSUE THREAD

**Issue by Felix-zhoux** [scylladb/scylla#6521] opened 2020-05-27 08:30 UTC
*Installation details*
Scylla version (or git commit hash): 4.0.0-0.20200514.d95aa77b6
Cluster size: 9
OS (RHEL/CentOS/Ubuntu/AWS AMI): CentOS

nodetool version: ReleaseVersion: 3.0.8

When I use the `nodetool tablestats` command to query some tables for information, I get an error for Unknown keyspace/Unknown table, which is the alternator table starting with '.'

```
[root@node13 scylla-tools-java]# ./bin/nodetool tablestats "alternator_.dir.424fb68d-46fa-4a35-ac54-e165bed8f2be.4170.1".".dir.424fb68d-46fa-4a35-ac54-e165bed8f2be.4170.1"
nodetool: Unknown keyspace: alternator_
See 'nodetool help' or 'nodetool help <command>'.
[root@node13 scylla-tools-java]# 
[root@node13 scylla-tools-java]# ./bin/nodetool tablestats "alternator_.dir.424fb68d-46fa-4a35-ac54-e165bed8f2be.4170.1" ".dir.424fb68d-46fa-4a35-ac54-e165bed8f2be.4170.1"
nodetool: Unknown keyspace: 
See 'nodetool help' or 'nodetool help <command>'.
[root@node13 scylla-tools-java]# 
[root@node13 scylla-tools-java]# ./bin/nodetool tablestats alternator_.dir.424fb68d-46fa-4a35-ac54-e165bed8f2be.4170.1 .dir.424fb68d-46fa-4a35-ac54-e165bed8f2be.4170.1
nodetool: Unknown keyspace: 
See 'nodetool help' or 'nodetool help <command>'.
```
I tested another table that didn't start with '. ' , and the command worked

```
[root@node13 scylla-tools-java]# ./bin/nodetool tablestats alternator_nodetoolks.nodetoolks
Total number of tables: 48
----------------
Keyspace : alternator_nodetoolks
	Read Count: 0
	Read Latency: NaN ms
	Write Count: 0
	Write Latency: NaN ms
	Pending Flushes: 0
		Table: nodetoolks
		SSTable count: 0
		Space used (live): 0
...
```

Can I name an alternator table starting with '. '?

**Comment by nyh** [comment] 2020-05-27 09:05
The problem is that Alternator (the DynamoDB API) and nodetool (assuming the CQL API) have different naming rules. In CQL table names and keyspace names can only contain letters, numerals, or underscore (see [here](https://docs.datastax.com/en/cql-oss/3.3/cql/cql_using/useCreateTable.html#Tablecharacteristics) and the first character must be a letter. In the DynamoDB API, a table name can contain in addition to letters, numerals and underscores also a dot or a dash (see [here](https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_TableDescription.html#DDB-Type-TableDescription-TableName)).

So nodetool, which expects CQL table names, uses the dot character to separate between the keyspace and table names as customary in CQL. This confuses it when the actual table name contains a dot.

An easy but temporary workaround for this problem is to simply not use dots in Alternator table names. Use dashes underscores, but not dots. However, we shouldn't make this a general recommendation because the DynamoDB API does allow dots.

An easy solution but that would require changing nodetool (@amnonh, what do you think?) will be to invent a new (additional) convention for specifying table names. For example, we can suggest to use the slash character, e.g., keyspacename/tablename. This would work for both Alternator and CQL names (and if there is no slash, the old dot will be tried for backward compatibility with CQL). 

A harder solution that would not require changing nodetool would be to "encode" Alternator table names with valid CQL names. One possible encoding is to encode "." as, say, "_dot_". For backward compatibility, when we look for a table with a given name, we would need to try both encoded and un-encoded names (or alternatively, rename tables during an upgrade).

If we need compatibility with not just nodetool but the actual CQL, then the dot will not be the only character that needs to be encoded - there is also the dash ("-"). Alternator also creates materialized views with ":" and "!" in their names (for GSIs and LSIs) and we may need to consider those too.

**Comment by slivne** [comment] 2020-05-27 11:57
@amnonh nodetool is one concern the other it hat it calls - rest api - does this work via the rest api ?

I am in favor of 

> An easy solution but that would require changing nodetool (@amnonh, what do you think?) will be to invent a new (additional) convention for specifying table names. For example, we can suggest to use the slash character, e.g., keyspacename/tablename. This would work for both Alternator and CQL names (and if there is no slash, the old dot will be tried for backward compatibility with CQL).

**Comment by nyh** [comment] 2021-01-24 11:37
Not only that `nodetool tablestats` can't be used on the specific table with a dot in its name, e.g., `a.b`, even `nodetool tablestats` without any parameters, which is supposed to list all tables, gets confused when such a table exists:
```
error: org.apache.cassandra.metrics:type=IndexTable,keyspace=alternator_a.b,scope=a.b,name=WriteLatency
-- StackTrace --
javax.management.InstanceNotFoundException: org.apache.cassandra.metrics:type=IndexTable,keyspace=alternator_a.b,scope=a.b,name=WriteLatency
        at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.getMBean(DefaultMBeanServerInterceptor.java:1095)
...
        at org.apache.cassandra.tools.nodetool.stats.StatsKeyspace.add(StatsKeyspace.java:49)
        at org.apache.cassandra.tools.nodetool.stats.TableStatsHolder.initializeKeyspaces(TableStatsHolder.java:140)
        at org.apache.cassandra.tools.nodetool.stats.TableStatsHolder.<init>(TableStatsHolder.java:41)
        at org.apache.cassandra.tools.nodetool.TableStats.execute(TableStats.java:56)
        at org.apache.cassandra.tools.NodeTool$NodeToolCmd.run(NodeTool.java:270)
        at org.apache.cassandra.tools.NodeTool.main(NodeTool.java:180)
``` 

For posterity, here is an easy way to add a table called "a.b" using the AWS CLI:
```
AWS_ACCESS_KEY_ID=alternator AWS_SECRET_ACCESS_KEY=secret_pass aws --endpoint-url=http://localhost:8000/ dynamodb create-table --table-name a.b --attribute-definitions AttributeName=p,AttributeType=S --key-schema AttributeName=p,KeyType=HASH --billing-mode PAY_PER_REQUEST
```

**Comment by nyh** [comment] 2021-01-24 13:04
I think I fell down a rabbit hole :-(
It turns out that in commit cef8eb07dfb4b81cd4e985bc86c5506602650c93 in 2013 (see issue https://issues.apache.org/jira/browse/CASSANDRA-4464), the Cassandra guys added to nodetool the feature that secondary indexes can be addressed using a "dot notation", which is not documented anywhere as far as I can see, moreover isn't even internally consistent (their code can retrieve a table name from the server, and then because it has a dot, be convinced this is an index name).

Scylla's secondary indexes are very different from Cassandra's, so I don't think this entire feature makes sense for Scylla, and maybe can be removed... Moreover, I can't find after a few minutes of Googling a single example of why or how exactly one uses nodetool on a secondary index, so I doubt anyone uses this feature even on Cassandra (but if you know otherwise, please let me know).

**Comment by nyh** [comment] 2021-01-24 17:46
@Felix-zhoux I just sent two patches to the mailing list, titled "nodetool: do no treat table name with dot as a secondary index" and "nodetool: alternate way to specify table name which includes a dot", which fixes this problem, so if you want to try it even before it gets committed, you can. Note that to enjoy this fix you'll have to use Scylla's version of nodetool (from git@github.com:scylladb/scylla-tools-java or one of our binary distributions which includes it), not the Cassandra version.

The first patch makes "nodetool tablestats" without parameters work - and not get confused by tables with dots in their name. The second patch allows to give a table name or keyspace name as a parameter to "nodetool tablestats", using the new convention `keyspacename/tablename` or `keyspacename/` - which allows both keyspacename and tablename to include dots.

**Comment by lauranovich** [comment] 2021-01-24 19:52
@nyh - we should document this as well, right?

**Comment by nyh** [comment] 2021-01-24 20:04
@lauranovich yes - I was planning on creating issues on https://docs.scylladb.com/operating-scylla/nodetool-commands/tablestats/ and a couple of other commands. But we'll need to decide if my patch actually goes in as-is, with the slash - before we document it.

As usual there is a problem that that page is _not_ attached to a specific version of Scylla, so the new information will be futuristic (describe a master feature that doesn't exist in any release version), and users of older versions won't understand why the new feature doesn't work for them.

**Comment by Felix-zhoux** [comment] 2021-01-25 02:05
> @Felix-zhoux I just sent two patches to the mailing list, titled "`nodetool: do no treat table name with dot as a secondary index`" and "`nodetool: alternate way to specify table name which includes a dot"`, which fixes this problem, so if you want to try it even before it gets committed, you can. Note that to enjoy this fix you'll have to use Scylla's version of nodetool (from github.com:scylladb/scylla-tools-java or one of our binary distributions which includes it), not the Cassandra version.
> 
> The first patch makes "nodetool tablestats" without parameters work - and not get confused by tables with dots in their name. The second patch allows to give a table name or keyspace name as a parameter to "nodetool tablestats", using the new convention `keyspacename/tablename` or `keyspacename/` - which allows both keyspacename and tablename to include dots.

@nyh  Okay, I got your message. By the way, will these two patches eventually be merged in a certain version?

**Comment by nyh** [comment] 2021-01-25 07:52
@Felix-zhoux I don't know how you consume Scylla so I can't give a pinpointed answer, so I'll give the general one: The usual Scylla development process is that after review the patch goes into the _master_ version, and into _future_ official releases. Bug fixes often get backported to existing release streams, enhancements and new features usually do not get backported. In this case it is not clear whether to label it a bug fix or a feature. For "enterprise" versions, we can also backport features which client needs (as a special version of a specific client or, preferably, to the main enterprise version).

Note that for this specific patch, the patch is in nodetool, not Scylla, so you can also build it yourself rather easily (git@github.com:scylladb/scylla-tools-java - but note that my patches were not yet committed there, I hope they will get reviewed today).

**Closed** 2021-01-28 18:10 UTC
Labels: Alternator, nodetool

**Comment by nyh** [comment] 2021-02-21 07:19
Hi @avikivity this is sort-of a bug (for specific users who try to use table names with dots in Alternator **and** use nodetool on them), so probably be backported, but I don't know what is the proper process to backport a patch (in this case, actually two patches) for tools/java because I have never done this before. Do I do things on the "next-4.2" branch of the tools/java submodule?  If I do that, will some automatic process promote it to branch-4.2 and then use this branch-4.2 in branch-4.2 of the top-level repository, or do I need to do some of this manually?
