### ISSUE TITLE
When Alternator creates a secondary index, is it compatible with the Projection parameter?

### ISSUE THREAD

**Issue by Felix-zhoux** [scylladb/scylla#7068] opened 2020-08-19 09:11 UTC
*Installation details*
Scylla version (or git commit hash): 4.1.3-0.20200729.9002592ee0c
Cluster size: 6
OS (RHEL/CentOS/Ubuntu/AWS AMI): CentOS

When I used the Alternator interface to create a table with a global secondary index, I used the following command
```
# aws dynamodb create-table --table-name test_gsi_table \
--attribute-definitions AttributeName=bi,AttributeType=S AttributeName=obj,AttributeType=S  \
AttributeName=head,AttributeType=S AttributeName=val,AttributeType=S AttributeName=onepar,AttributeType=S \
--key-schema AttributeName=bi,KeyType=HASH AttributeName=obj,KeyType=RANGE \
--provisioned-throughput ReadCapacityUnits=10,WriteCapacityUnits=5 \
--global-secondary-indexes \
"[ \
    { \
        \"IndexName\": \"test_gsi_index\", \
        \"KeySchema\": [ \
            {\"AttributeName\":\"onepar\",\"KeyType\":\"HASH\"}, \
            {\"AttributeName\":\"bi\",\"KeyType\":\"RANGE\"} \
        ], \
        \"Projection\": { \
            \"ProjectionType\":\"INCLUDE\", \
            \"NonKeyAttributes\":[\"val\"] \
        }, \
        \"ProvisionedThroughput\": { \
            \"ReadCapacityUnits\": 10, \
            \"WriteCapacityUnits\": 5 \
        } \
    } \
]" --endpoint-url http://10.181.159.70:8000
```

Then I got the response like this：
```
{
    "TableDescription": {
        "GlobalSecondaryIndexes": [
            {
                "KeySchema": [
                    {
                        "KeyType": "HASH", 
                        "AttributeName": "onepar"
                    }, 
                    {
                        "KeyType": "RANGE", 
                        "AttributeName": "bi"
                    }
                ], 
                "IndexName": "test_gsi_index", 
                "Projection": {
                    "ProjectionType": "INCLUDE", 
                    "NonKeyAttributes": [
                        "val"
                    ]
                }, 
                "ProvisionedThroughput": {
                    "WriteCapacityUnits": 5, 
                    "ReadCapacityUnits": 10
                }
            }
        ], 
        "AttributeDefinitions": [
            {
                "AttributeName": "bi", 
                "AttributeType": "S"
            }, 
            {
                "AttributeName": "obj", 
                "AttributeType": "S"
            }, 
            {
                "AttributeName": "head", 
                "AttributeType": "S"
            }, 
            {
                "AttributeName": "val", 
                "AttributeType": "S"
            }, 
            {
                "AttributeName": "onepar", 
                "AttributeType": "S"
            }
        ], 
        "ProvisionedThroughput": {
            "WriteCapacityUnits": 5, 
            "ReadCapacityUnits": 10
        }, 
        "TableName": "test_gsi_table", 
        "TableStatus": "ACTIVE", 
        "TableId": "3db9b800-e1f5-11ea-8537-00000000000f", 
        "KeySchema": [
            {
                "KeyType": "HASH", 
                "AttributeName": "bi"
            }, 
            {
                "KeyType": "RANGE", 
                "AttributeName": "obj"
            }
        ], 
        "CreationDateTime": 1597825402
    }
}
```

When I use cqlsh to query the table structure, I get the following output:
```
cqlsh> desc KEYSPACE alternator_test_gsi_table

CREATE KEYSPACE alternator_test_gsi_table WITH replication = {'class': 'NetworkTopologyStrategy', 'ZhengZhou_DC01': '3', 'ZhengZhou_DC02': '3', 'ZhengZhou_DC03': '3'}  AND durable_writes = true;

CREATE TABLE alternator_test_gsi_table.test_gsi_table (
    bi text,
    obj text,
    ":attrs" map<text, blob>,
    onepar text,
    PRIMARY KEY (bi, obj)
) WITH CLUSTERING ORDER BY (obj ASC)
    AND bloom_filter_fp_chance = 0.01
    AND caching = {'keys': 'ALL', 'rows_per_partition': 'ALL'}
    AND comment = ''
    AND compaction = {'class': 'SizeTieredCompactionStrategy'}
    AND compression = {'sstable_compression': 'org.apache.cassandra.io.compress.LZ4Compressor'}
    AND crc_check_chance = 1.0
    AND dclocal_read_repair_chance = 0.1
    AND default_time_to_live = 0
    AND gc_grace_seconds = 864000
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair_chance = 0.0
    AND speculative_retry = '99.0PERCENTILE';

CREATE MATERIALIZED VIEW alternator_test_gsi_table."test_gsi_table:test_gsi_index" AS
    SELECT *
    FROM alternator_test_gsi_table.test_gsi_table
    WHERE "onepar" IS NOT NULL AND "onepar" IS NOT NULL
    PRIMARY KEY (onepar, bi, obj)
    WITH CLUSTERING ORDER BY (bi ASC, obj ASC)
    AND bloom_filter_fp_chance = 0.01
    AND caching = {'keys': 'ALL', 'rows_per_partition': 'ALL'}
    AND comment = ''
    AND compaction = {'class': 'SizeTieredCompactionStrategy'}
    AND compression = {'sstable_compression': 'org.apache.cassandra.io.compress.LZ4Compressor'}
    AND crc_check_chance = 1.0
    AND dclocal_read_repair_chance = 0.1
    AND default_time_to_live = 0
    AND gc_grace_seconds = 864000
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair_chance = 0.0
    AND speculative_retry = '99.0PERCENTILE'

scylla_tags = {};

scylla_tags = {}
```

I have two points of confusion here:
1. In the GSI table "test_gsi_table:test_gsi_index", I did not specify ‘obj’ as the primary key, but it eventually became part of the primary key. ` PRIMARY KEY (onepar, bi, obj)`
2. When creating the GSI, I specified the Projection type as ‘INCLUDE’, and I hope to project and only the ‘val’ attribute into the GSI table. But in the end it seems that all attributes are included in GSI.

```
cqlsh> select * from alternator_test_gsi_table.test_gsi_table ;

 bi  | obj      | :attrs                                                        | onepar
-----+----------+---------------------------------------------------------------+--------
 zha | zhangsan | {'head': 0x00746573746865616430, 'val': 0x007465737476616c30} |     p1
 zha |  zhaoliu | {'head': 0x00746573746865616436, 'val': 0x007465737476616c36} |     p1
 lis |     lisi | {'head': 0x00746573746865616431, 'val': 0x007465737476616c31} |     p1
 lis |   lisier | {'head': 0x00746573746865616433, 'val': 0x007465737476616c33} |     p1
 wan |  wangliu | {'head': 0x00746573746865616435, 'val': 0x007465737476616c35} |     p1
 wan |   wangwu | {'head': 0x00746573746865616434, 'val': 0x007465737476616c34} |     p1
 qia |   qianba | {'head': 0x00746573746865616438, 'val': 0x007465737476616c38} |     p1
 qia |   qianqi | {'head': 0x00746573746865616437, 'val': 0x007465737476616c37} |     p1
 lib |     liba | {'head': 0x00746573746865616432, 'val': 0x007465737476616c32} |     p1

(9 rows)
cqlsh> 
cqlsh> select * from alternator_test_gsi_table."test_gsi_table:test_gsi_index";

 onepar | bi  | obj      | :attrs
--------+-----+----------+---------------------------------------------------------------
     p1 | lib |     liba | {'head': 0x00746573746865616432, 'val': 0x007465737476616c32}
     p1 | lis |     lisi | {'head': 0x00746573746865616431, 'val': 0x007465737476616c31}
     p1 | lis |   lisier | {'head': 0x00746573746865616433, 'val': 0x007465737476616c33}
     p1 | qia |   qianba | {'head': 0x00746573746865616438, 'val': 0x007465737476616c38}
     p1 | qia |   qianqi | {'head': 0x00746573746865616437, 'val': 0x007465737476616c37}
     p1 | wan |  wangliu | {'head': 0x00746573746865616435, 'val': 0x007465737476616c35}
     p1 | wan |   wangwu | {'head': 0x00746573746865616434, 'val': 0x007465737476616c34}
     p1 | zha | zhangsan | {'head': 0x00746573746865616430, 'val': 0x007465737476616c30}
     p1 | zha |  zhaoliu | {'head': 0x00746573746865616436, 'val': 0x007465737476616c36}

(9 rows)
```

**Comment by psarna** [comment] 2020-08-19 09:18
As for projections, here's a corresponding issue: https://github.com/scylladb/scylla/issues/5036

As for the underlying materialized view - that's an implementation detail of alternator, which in turn relies on an implementation detail of Scylla's views: the whole base primary key must be included in the view primary key in order to ensure correct row liveness. Still, the API exposed by alternator works fine without that knowledge and allows using `onepar` as hash key and `bi` as sort key.

**Comment by Felix-zhoux** [comment] 2020-08-19 09:39
> As for projections, here's a corresponding issue: #5036
Yes, I just noticed this.

> As for the underlying materialized view - that's an implementation detail of alternator, which in turn relies on an implementation detail of Scylla's views: the whole base primary key must be included in the view primary key in order to ensure correct row liveness. Still, the API exposed by alternator works fine without that knowledge and allows using `onepar` as hash key and `bi` as sort key.

The reason for raising this question is that there are two considerations
1. Storage space occupied by GSI. I don't know the underlying storage details of GSI, but what I saw is that it exists. Does reducing the projection of the attribute mean that the storage space can be reduced?
2. The number of items in a single partition. If 'obj' can **not** be part of the GSI primary key, and'bi' (sort key) can achieve deduplication (that is, in the original table, items with the same bi and different obj will exist as a row in the new GSI). Then the number of items in the same partition can be reduced a lot (from performance considerations, this is also what scylla hopes).

**Comment by psarna** [comment] 2020-08-19 09:50
1. Yes, generally, reducing the projection should reduce the storage overhead. It's not the case for alternator yet, until #5036 is resolved.
2. I get what your idea is, but keys are also used for ensuring uniqueness. If you removed `obj` from the view's primary key, then it also implies that there can only be up to one row with specific values of onepar, bi. E.g. these two rows:
```cql
     p1 | lis |     lisi | {'head': 0x00746573746865616431, 'val': 0x007465737476616c31}
     p1 | lis |   lisier | {'head': 0x00746573746865616433, 'val': 0x007465737476616c33}
```
could not be represented if `(p1, lis)` are the only key columns. Instead, inserting the second one would overwrite the first.

**Comment by Felix-zhoux** [comment] 2020-08-19 10:20
You are right, this situation does exist.

However, in fact, this scene will not affect me, because I only want to use GSI to get an orderly ‘bi’. I will not project any other attributes except ‘onepar’ and ‘bi’ to GSI. Therefore, there will be no overwriting.
Of course, if other people need to project some common attributes (such as head) to GSI, then all the original primary keys will be automatically added to the GSI primary key. This can avoid overwriting.

All in all, I hope that the configuration of Projection can be more flexible, so that it can adapt to more different business scenarios. I don’t know if my understanding is correct, thanks for the advice~

**Comment by nyh** [comment] 2020-08-19 13:40
I'm closing this issue - as @psarna noted your observation that "Projection" is not obeyed is correct, and is a duplicate of issue #5036. It's not that we don't want to implement "Projection" - we do want to implement it (hence the open issue 5036), but we just never got around to do it. It was never a priority and wasn't yet requested by a customer, so we did other things first...

As to the question why the base table's key "obj" can be observed in the underlying materialized view despite not being in the GSI's key, the bug tracker isn't the best way to explain this, but I'll try anyway. @psarna is correct that you shouldn't care about this (except in a bug we still have with DescribeTable, see #5320) because it's just an implementation detail. But if you're curious *why* it was implemented this way, first ask yourself the following question: Why do you use **GetItem** to read from a table, but must use **Query** to read from a GSI?
The answer is that when you read from a GSI, using (onepar, bi) you can never be sure that you'll get back just one item. You can get multiple items. What is the unique difference between those items? It's that they have a different base table key, i.e., different "obj". Even if the user doesn't want to get back this "obj" in the Query, what makes these different items unique is the (bi, obj) combination so the view's item key must include this unique key.  

If you want to continue discuss the theory of GSI keys, let's do it on the mailing list.

**Closed by nyh** 2020-08-19 13:40 UTC

**Comment by nyh** [comment] 2020-08-19 13:47
>     2. The number of items in a single partition. If 'obj' can **not** be part of the GSI primary key, and'bi' (sort key) can achieve deduplication (that is, in the original table, items with the same bi and different obj will exist as a row in the new GSI). Then the number of items in the same partition can be reduced a lot (from performance considerations, this is also what scylla hopes).

What you're asking for here is basically issue #3435. This "deduplication" is not a simple problem because when somebody **deletes** a row on the base table, it's not easy to know whether the view row (which in your case only lists partition keys of the base table) should be deleted or not. See issue #3435 for a longer discussion of the problems with this wish.

In any case, what you are wishing for is also not possible in DynamoDB: If you have 1000 items with the same partition key and project just this partition key into a GSI, when you read this GSI, you'll still read 1000 items. They will all look exactly the same (because you projected only the partition key), but you will read 1000 of them.

**Comment by Felix-zhoux** [comment] 2020-08-20 12:03
@nyh Okay, I understand what you mean. This matter is more complicated than I thought. You have considered it a long time ago. It just so happens that the issue in my hand is already pending, and we can wait to consider this issue later.
