### ISSUE TITLE
Ability to get Scylla version using CQL command

### ISSUE THREAD

**Issue by bentsi** [scylladb/scylla#8841] opened 2021-06-10 12:55 UTC
We need to have the ability to query a system table and get the current Scylla version that is used on each one of the nodes.
For example in Apache Cassandra we can run the following query:

```cql
cqlsh> select peer, release_version from system.peers;
```
that will show us the list of the nodes and the release version that is used. 

This is extremely useful when only CQL port accessible on the server, for example in Scylla Cloud.

**Comment by slivne** [comment] 2021-06-10 12:57
I think we should place the version in scylla_local in the local node

**Comment by slivne** [comment] 2021-06-10 12:59
please clarify why you need the peers version

**Comment by bentsi** [comment] 2021-06-10 12:59
Yes, we can do it for the local node too. In Cassandra it is queried as follows:
```cql
select release_version from system.local;
```

**Comment by avelanarius** [comment] 2021-06-10 17:18
Refs #8740

**Comment by nyh** [comment] 2021-06-10 19:33
Closing as a duplicate of #8740

**Closed by nyh** 2021-06-10 19:33 UTC
Labels: enhancement, n00b
