### ISSUE TITLE
Startup failed: std::runtime_error (Other bootstrapping/leaving/moving nodes detected, cannot bootstrap while consistent_rangemovement is true (check_for_endpoint_collision))

### ISSUE THREAD

**Issue by fruch** [scylladb/scylla#6354] opened 2020-05-03 13:32 UTC
*Installation details*
Scylla version (or git commit hash):  3.3.1-0.20200418.6f939ffe199
Cluster size: 4
OS (RHEL/CentOS/Ubuntu/AWS AMI):  Ubutnu16.04 
Scylla version: 3.3.1 (-)
Instance type: n1-highmem-8

## Summary

During setup for rolling-upgrade test on ubuntu 16.04
node4 failed to start with the following error:
```
- Startup failed: std::runtime_error (Other bootstrapping/leaving/moving nodes detected, cannot bootstrap while consistent_rangemovement is true (check_for_endpoint_collision))
```

## Logs
* **test-id**: d2051c7d-7344-42fd-881c-d93fe898c262
* **Jenkins Job** - https://jenkins.scylladb.com/job/scylla-master/job/rolling-upgrade/job/rolling-upgrade-ubuntu16.04/28/
* **db-cluster** - https://cloudius-jenkins-test.s3.amazonaws.com/d2051c7d-7344-42fd-881c-d93fe898c262/20200501_041459/db-cluster-d2051c7d.zip
* **loader-set** - https://cloudius-jenkins-test.s3.amazonaws.com/d2051c7d-7344-42fd-881c-d93fe898c262/20200501_041459/loader-set-d2051c7d.zip
* **monitor-set** - https://cloudius-jenkins-test.s3.amazonaws.com/d2051c7d-7344-42fd-881c-d93fe898c262/20200501_041459/monitor-set-d2051c7d.zip
* **sct-runner** - https://cloudius-jenkins-test.s3.amazonaws.com/d2051c7d-7344-42fd-881c-d93fe898c262/20200501_041459/sct-runner-d2051c7d.zip

**Comment by slivne** [comment] 2020-05-05 15:40
need to validate that we don't have multiple topology changes happening at the same time - need to validate it via the logs.

**Comment by ShlomiBalalis** [comment] 2020-05-11 11:55
@slivne It happens during the the setup, so I doubt that it happens at this point of the test. How can we validate this?
I encountered the error again in the latest ubuntu 16 rolling upgrade
Logs:
```
+--------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                                           Log links for testrun with test id 9bbcc4a3-20ba-4e45-b5c1-e2dfac55e7c8                                            |
+-----------------+-------------+------------------------------------------------------------------------------------------------------------------------------+
| Date            | Log type    | Link                                                                                                                         |
+-----------------+-------------+------------------------------------------------------------------------------------------------------------------------------+
| 20200510_131812 | db-cluster  | https://cloudius-jenkins-test.s3.amazonaws.com/9bbcc4a3-20ba-4e45-b5c1-e2dfac55e7c8/20200510_131812/db-cluster-9bbcc4a3.zip  |
| 20200510_131812 | loader-set  | https://cloudius-jenkins-test.s3.amazonaws.com/9bbcc4a3-20ba-4e45-b5c1-e2dfac55e7c8/20200510_131812/loader-set-9bbcc4a3.zip  |
| 20200510_131812 | monitor-set | https://cloudius-jenkins-test.s3.amazonaws.com/9bbcc4a3-20ba-4e45-b5c1-e2dfac55e7c8/20200510_131812/monitor-set-9bbcc4a3.zip |
| 20200510_131812 | sct-runner  | https://cloudius-jenkins-test.s3.amazonaws.com/9bbcc4a3-20ba-4e45-b5c1-e2dfac55e7c8/20200510_131812/sct-runner-9bbcc4a3.zip  |
+-----------------+-------------+------------------------------------------------------------------------------------------------------------------------------+
```

**Comment by slivne** [comment] 2020-05-11 20:04
you have in the log messages

```
HASH}
May 10 12:18:45 rolling-upgrade-master-ubuntu-xenia-db-node-9bbcc4a3-0-4 scylla[21284]:  [shard 0] storage_service - Checking bootstrapping/leaving/moving nodes: node=10.142.0.63, status=BOOT, sleep 1 second and check again (55 seconds el
apsed) (check_for_endpoint_collision)
```

checking node-1 

```
May 10 12:18:54 rolling-upgrade-master-ubuntu-xenia-db-node-9bbcc4a3-0-1 scylla[21680]:  [shard 0] stream_session - [Stream #6a69fc70-92b8-11ea-87ad-000000000001] Executing streaming plan for Bootstrap-system_traces-index-9 with peers=10.142.0.63, slave
May 10 12:18:54 rolling-upgrade-master-ubuntu-xenia-db-node-9bbcc4a3-0-1 scylla[21680]:  [shard 0] stream_session - [Stream #6a68c3f0-92b8-11ea-87ad-000000000001] Streaming plan for Bootstrap-system_traces-index-8 succeeded, peers={10.142.0.63}, tx=0 KiB, 0.00 KiB/s, rx=0 KiB, 0.00 KiB/s
May 10 12:18:54 rolling-upgrade-master-ubuntu-xenia-db-node-9bbcc4a3-0-1 scylla[21680]:  [shard 0] stream_session - [Stream #6a69fc70-92b8-11ea-87ad-000000000001] Streaming plan for Bootstrap-system_traces-index-9 succeeded, peers={10.142.0.63}, tx=0 KiB, 0 KiB/s, rx=0 KiB, 0 KiB/s
[shlomi@localhost rolling-upgrade-master-ubuntu-xenia-db-node-9bbcc4a3-0-1]$ 
```

so the node 10.142.0.63 finished streaming at "12:18:54"

and the node 

```
May 10 12:18:53 rolling-upgrade-master-ubuntu-xenia-db-node-9bbcc4a3-0-4 scylla[21284]:  [shard 0] init - Startup failed: std::runtime_error (Other bootstrapping/leaving/moving nodes detected, cannot bootstrap while consistent_rangemovement is true (check_for_endpoint_collision))
```

committed suicide at " 12:18:53"

So it seems correct 


It seems to me you start all the nodes at the same time and then sometimes it succeeds because of retries sometimes it doesn't.

Can you check it on your end.

@roydahan / @amoskong was this changed ? please note in AWS we had on the old AMI something guarding against this if I recall correctly.

**Comment by roydahan** [comment] 2020-05-11 20:22
@slivne this is on GCE and nothing has changed on our side for starting the cluster.

**Comment by fruch** [comment] 2020-05-11 20:27
> you have in the log messages
> 
> ```
> HASH}
> May 10 12:18:45 rolling-upgrade-master-ubuntu-xenia-db-node-9bbcc4a3-0-4 scylla[21284]:  [shard 0] storage_service - Checking bootstrapping/leaving/moving nodes: node=10.142.0.63, status=BOOT, sleep 1 second and check again (55 seconds el
> apsed) (check_for_endpoint_collision)
> ```
> 
> checking node-1
> 
> ```
> May 10 12:18:54 rolling-upgrade-master-ubuntu-xenia-db-node-9bbcc4a3-0-1 scylla[21680]:  [shard 0] stream_session - [Stream #6a69fc70-92b8-11ea-87ad-000000000001] Executing streaming plan for Bootstrap-system_traces-index-9 with peers=10.142.0.63, slave
> May 10 12:18:54 rolling-upgrade-master-ubuntu-xenia-db-node-9bbcc4a3-0-1 scylla[21680]:  [shard 0] stream_session - [Stream #6a68c3f0-92b8-11ea-87ad-000000000001] Streaming plan for Bootstrap-system_traces-index-8 succeeded, peers={10.142.0.63}, tx=0 KiB, 0.00 KiB/s, rx=0 KiB, 0.00 KiB/s
> May 10 12:18:54 rolling-upgrade-master-ubuntu-xenia-db-node-9bbcc4a3-0-1 scylla[21680]:  [shard 0] stream_session - [Stream #6a69fc70-92b8-11ea-87ad-000000000001] Streaming plan for Bootstrap-system_traces-index-9 succeeded, peers={10.142.0.63}, tx=0 KiB, 0 KiB/s, rx=0 KiB, 0 KiB/s
> [shlomi@localhost rolling-upgrade-master-ubuntu-xenia-db-node-9bbcc4a3-0-1]$ 
> ```
> 
> so the node 10.142.0.63 finished streaming at "12:18:54"
> 
> and the node
> 
> ```
> May 10 12:18:53 rolling-upgrade-master-ubuntu-xenia-db-node-9bbcc4a3-0-4 scylla[21284]:  [shard 0] init - Startup failed: std::runtime_error (Other bootstrapping/leaving/moving nodes detected, cannot bootstrap while consistent_rangemovement is true (check_for_endpoint_collision))
> ```
> 
> committed suicide at " 12:18:53"
> 
> So it seems correct
> 
> It seems to me you start all the nodes at the same time and then sometimes it succeeds because of retries sometimes it doesn't.
> 
> Can you check it on your end.
> 
> @roydahan / @amoskong was this changed ? please note in AWS we had on the old AMI something guarding against this if I recall correctly.

rolling upgrade tests are working only on GCE, and we are using RPMs, so AMI isn't the blame (not this time ;))

also this failure is a the install of 3.3.1, before most of the sequence of the test, and as far as I know we didn't radially change the sequence.

we are running the initial setup in parallel, but each node starts 30sec later, it's like as long as I can remember... 
https://github.com/scylladb/scylla-cluster-tests/blob/c60ce5d150348b829e7b77ab4e45d018f3c362a4/sdcm/cluster.py#L2818

**Comment by amoskong** [comment] 2020-05-12 08:50
Currently we start the seeds firstly, then start other non-seed nodes `in parallel`.
It's not recommended, we should start the non-seed nodes one by one to avoid this issue.

**Comment by roydahan** [comment] 2020-05-12 09:36
Why did it start happening on 3.3?
What has changed?

**Comment by ShlomiBalalis** [comment] 2020-05-18 01:08
The issue still can occur, it occurred on this week's debian9 rolling upgrade
Version: 3.3.1-0.20200418.6f939ffe199

Logs:
```
+--------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                                           Log links for testrun with test id e4af70f8-5d84-45fb-8218-35e700838de9                                            |
+-----------------+-------------+------------------------------------------------------------------------------------------------------------------------------+
| Date            | Log type    | Link                                                                                                                         |
+-----------------+-------------+------------------------------------------------------------------------------------------------------------------------------+
| 20200517_113224 | db-cluster  | https://cloudius-jenkins-test.s3.amazonaws.com/e4af70f8-5d84-45fb-8218-35e700838de9/20200517_113224/db-cluster-e4af70f8.zip  |
| 20200517_113224 | loader-set  | https://cloudius-jenkins-test.s3.amazonaws.com/e4af70f8-5d84-45fb-8218-35e700838de9/20200517_113224/loader-set-e4af70f8.zip  |
| 20200517_113224 | monitor-set | https://cloudius-jenkins-test.s3.amazonaws.com/e4af70f8-5d84-45fb-8218-35e700838de9/20200517_113224/monitor-set-e4af70f8.zip |
| 20200517_113224 | sct-runner  | https://cloudius-jenkins-test.s3.amazonaws.com/e4af70f8-5d84-45fb-8218-35e700838de9/20200517_113224/sct-runner-e4af70f8.zip  |
+-----------------+-------------+------------------------------------------------------------------------------------------------------------------------------+
```

**Comment by amoskong** [comment] 2020-05-21 22:45
We see this issue in rolling upgrade from 4.0 to 4.1
- https://jenkins.scylladb.com/job/scylla-4.1/job/rolling-upgrade/job/rolling-upgrade-centos7-test/12/

init cluster version: 4.0.0-0.20200505.d95aa77b62
sct test id: 13eb0811-4d0a-4cf2-9873-1ac7545d2567

**Comment by roydahan** [comment] 2020-05-24 12:47
Something is wrong with how we start the cluster.
We need to understand if it's started happening due to timing changes or issue in scylla.

@amoskong, IIRC we first start the seed and then start all the other nodes together.
They somehow should manage to start one by one, right?

**Comment by slivne** [comment] 2020-05-25 23:25
there is a pull request to fix this in master https://github.com/scylladb/scylla/pull/6484

**Comment by slivne** [comment] 2020-05-25 23:26
Lets see that this works on master

**Comment by slivne** [comment] 2020-05-25 23:27
@roydahan - do you enable experimental - if so please disable it.

**Comment by amoskong** [comment] 2020-05-27 03:59
experimental is enabled by default in SCT.
https://github.com/scylladb/scylla-cluster-tests/blob/master/defaults/test_default.yaml#L10

It's safe to disable `experimental` for upgrade tests.

**Comment by amoskong** [comment] 2020-05-27 04:00
> Something is wrong with how we start the cluster.
> We need to understand if it's started happening due to timing changes or issue in scylla.
> 
> @amoskong, IIRC we first start the seed and then start all the other nodes together.
> They somehow should manage to start one by one, right?

Yes. If we thought it's not a scylla issue, it's designed like this, we should fix SCT.

**Comment by roydahan** [comment] 2020-06-01 11:47
@slivne, we start scylla as follow, we first start the seed and then start all other nodes.
Till now, it worked without any issue (for few years).
Also, we don't see this issue in longevities or any other tests, just on rolling upgrades that are running on GCE.
Are we doing it wrong?
What is the recommended way to bootstrap a new cluster?

**Comment by amoskong** [comment] 2020-06-01 12:42
About SCT:

In the past we started all nodes of init cluster in parallel.

We changed this from 2018/10 by https://github.com/scylladb/scylla-cluster-tests/commit/777f82d9f3189704254433b369e416fe3bb58e12 for better support of multidc testing.  seeds will be started firstly, then non-seeds will be started in parallel.

**Comment by slivne** [comment] 2020-06-21 11:10
@roydahan please post updated logs and I'll check whats wrong

**Comment by ShlomiBalalis** [comment] 2020-06-21 14:08
Logs of the latest ubuntu 16 rolling upgrade that has experienced that issue:
```
+--------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                                           Log links for testrun with test id 12d4c66a-c43c-4efe-b3e3-fe3ac38c2a71                                            |
+-----------------+-------------+------------------------------------------------------------------------------------------------------------------------------+
| Date            | Log type    | Link                                                                                                                         |
+-----------------+-------------+------------------------------------------------------------------------------------------------------------------------------+
| 20200619_041608 | db-cluster  | https://cloudius-jenkins-test.s3.amazonaws.com/12d4c66a-c43c-4efe-b3e3-fe3ac38c2a71/20200619_041608/db-cluster-12d4c66a.zip  |
| 20200619_041608 | loader-set  | https://cloudius-jenkins-test.s3.amazonaws.com/12d4c66a-c43c-4efe-b3e3-fe3ac38c2a71/20200619_041608/loader-set-12d4c66a.zip  |
| 20200619_041608 | monitor-set | https://cloudius-jenkins-test.s3.amazonaws.com/12d4c66a-c43c-4efe-b3e3-fe3ac38c2a71/20200619_041608/monitor-set-12d4c66a.zip |
| 20200619_041608 | sct-runner  | https://cloudius-jenkins-test.s3.amazonaws.com/12d4c66a-c43c-4efe-b3e3-fe3ac38c2a71/20200619_041608/sct-runner-12d4c66a.zip  |
+-----------------+-------------+------------------------------------------------------------------------------------------------------------------------------+
```

**Comment by slivne** [comment] 2020-06-22 05:54
From the logs 
You are starting the seed node and then in a loop with delay of 30 seconds other nodes.

```
2020-06-19T03:10:02+00:00  rolling-upgrade-master-ubuntu-xenia-db-node-12d4c66a-0-1 !INFO    | scylla[18118]: Scylla version 4.0.2-0.20200615.ce57d0174d4 with build-id fff2c22c55eab7548c5fc60a12cb92bf85875e99 starting ...
2020-06-19T03:10:03+00:00  rolling-upgrade-master-ubuntu-xenia-db-node-12d4c66a-0-1 !INFO    | scylla:  [shard 0] init - Scylla version 4.0.2-0.20200615.ce57d0174d4 with build-id fff2c22c55eab7548c5fc60a12cb92bf85875e99 starting ...
2020-06-19T03:10:46+00:00  rolling-upgrade-master-ubuntu-xenia-db-node-12d4c66a-0-1 !INFO    | scylla:  [shard 0] init - Scylla version 4.0.2-0.20200615.ce57d0174d4 initialization completed.

2020-06-19T03:13:34+00:00  rolling-upgrade-master-ubuntu-xenia-db-node-12d4c66a-0-2 !INFO    | scylla[20299]: Scylla version 4.0.2-0.20200615.ce57d0174d4 with build-id fff2c22c55eab7548c5fc60a12cb92bf85875e99 starting ...
2020-06-19T03:13:34+00:00  rolling-upgrade-master-ubuntu-xenia-db-node-12d4c66a-0-2 !INFO    | scylla:  [shard 0] init - Scylla version 4.0.2-0.20200615.ce57d0174d4 with build-id fff2c22c55eab7548c5fc60a12cb92bf85875e99 starting ...
2020-06-19T03:14:05+00:00  rolling-upgrade-master-ubuntu-xenia-db-node-12d4c66a-0-3 !INFO    | scylla[20493]: Scylla version 4.0.2-0.20200615.ce57d0174d4 with build-id fff2c22c55eab7548c5fc60a12cb92bf85875e99 starting ...
2020-06-19T03:14:05+00:00  rolling-upgrade-master-ubuntu-xenia-db-node-12d4c66a-0-3 !INFO    | scylla:  [shard 0] init - Scylla version 4.0.2-0.20200615.ce57d0174d4 with build-id fff2c22c55eab7548c5fc60a12cb92bf85875e99 starting ...
2020-06-19T03:14:35+00:00  rolling-upgrade-master-ubuntu-xenia-db-node-12d4c66a-0-4 !INFO    | scylla[20708]: Scylla version 4.0.2-0.20200615.ce57d0174d4 with build-id fff2c22c55eab7548c5fc60a12cb92bf85875e99 starting ...
2020-06-19T03:14:35+00:00  rolling-upgrade-master-ubuntu-xenia-db-node-12d4c66a-0-4 !INFO    | scylla:  [shard 0] init - Scylla version 4.0.2-0.20200615.ce57d0174d4 with build-id fff2c22c55eab7548c5fc60a12cb92bf85875e99 starting ...
2020-06-19T03:15:29+00:00  rolling-upgrade-master-ubuntu-xenia-db-node-12d4c66a-0-2 !INFO    | scylla:  [shard 0] init - Scylla version 4.0.2-0.20200615.ce57d0174d4 initialization completed.
2020-06-19T03:16:03+00:00  rolling-upgrade-master-ubuntu-xenia-db-node-12d4c66a-0-3 !INFO    | scylla:  [shard 0] init - Scylla version 4.0.2-0.20200615.ce57d0174d4 initialization completed.
```

This doesn't work - as the nodes do not complete their bootstrap

```
2020-06-19T03:14:42+00:00  rolling-upgrade-master-ubuntu-xenia-db-node-12d4c66a-0-4 !INFO    | scylla:  [shard 0] gossip - Feature check passed. Local node 10.142.15.229 features = {CDC, COMPUTED_COLUMNS, CORRECT_COUNTER_ORDER, CORRECT_NON_COMPOUND_RANGE_TOMBSTONES, CORRECT_STATIC_COMPACT_IN_MC, COUNTERS, DIGEST_INSENSITIVE_TO_EXPIRY, DIGEST_MULTIPARTITION_READ, HINTED_HANDOFF_SEPARATE_CONNECTION, INDEXES, LARGE_PARTITIONS, LA_SSTABLE_FORMAT, LWT, MATERIALIZED_VIEWS, MC_SSTABLE_FORMAT, NONFROZEN_UDTS, PER_TABLE_PARTITIONERS, RANGE_TOMBSTONES, ROLES, ROW_LEVEL_REPAIR, SCHEMA_TABLES_V3, STREAM_WITH_RPC_STREAM, TRUNCATION_TABLE, UNBOUNDED_RANGE_TOMBSTONES, VIEW_VIRTUAL_COLUMNS, WRITE_FAILURE_REPLY, XXHASH}, Remote common_features = {CDC, COMPUTED_COLUMNS, CORRECT_COUNTER_ORDER, CORRECT_NON_COMPOUND_RANGE_TOMBSTONES, CORRECT_STATIC_COMPACT_IN_MC, COUNTERS, DIGEST_INSENSITIVE_TO_EXPIRY, DIGEST_MULTIPARTITION_READ, HINTED_HANDOFF_SEPARATE_CONNECTION, INDEXES, LARGE_PARTITIONS, LA_SSTABLE_FORMAT, LWT, MATERIALIZED_VIEWS, MC_SSTABLE_FORMAT, NONFROZEN_UDTS, PER_TABLE_PARTITIONERS, RANGE_TOMBSTONES, ROLES, ROW_LEVEL_REPAIR, SCHEMA_TABLES_V3, STREAM_WITH_RPC_STREAM, TRUNCATION_TABLE, UNBOUNDED_RANGE_TOMBSTONES, VIEW_VIRTUAL_COLUMNS, WRITE_FAILURE_REPLY, XXHASH}
2020-06-19T03:14:42+00:00  rolling-upgrade-master-ubuntu-xenia-db-node-12d4c66a-0-4 !INFO    | scylla:  [shard 0] storage_service - Checking bootstrapping/leaving/moving nodes: node=10.142.15.224, status=BOOT, sleep 1 second and check again (1 seconds elapsed) (check_for_endpoint_collision)
2020-06-19T03:14:42+00:00  rolling-upgrade-master-ubuntu-xenia-db-node-12d4c66a-0-4 !INFO    | scylla-jmx[20793]: JMX is enabled to receive remote connections on port: 7199
2020-06-19T03:14:43+00:00  rolling-upgrade-master-ubuntu-xenia-db-node-12d4c66a-0-4 !INFO    | scylla:  [shard 0] storage_service - Checking remote features with gossip
2020-06-19T03:14:44+00:00  rolling-upgrade-master-ubuntu-xenia-db-node-12d4c66a-0-4 !INFO    | sshd[20820]: Accepted publickey for scylla-test from 10.142.0.2 port 33464 ssh2: RSA SHA256:ORclW5uOPUGIzX/HqWCBo6YH8GIz8D8MPjTEd0njNms
2020-06-19T03:14:44+00:00  rolling-upgrade-master-ubuntu-xenia-db-node-12d4c66a-0-4 !INFO    | sshd[20820]: pam_unix(sshd:session): session opened for user scylla-test by (uid=0)
2020-06-19T03:14:44+00:00  rolling-upgrade-master-ubuntu-xenia-db-node-12d4c66a-0-4 !INFO    | systemd-logind[1626]: New session 145 of user scylla-test.
2020-06-19T03:14:44+00:00  rolling-upgrade-master-ubuntu-xenia-db-node-12d4c66a-0-4 !INFO    | systemd[1]: Started Session 145 of user scylla-test.
2020-06-19T03:14:44+00:00  rolling-upgrade-master-ubuntu-xenia-db-node-12d4c66a-0-4 !INFO    | scylla:  [shard 0] gossip - Feature check passed. Local node 10.142.15.229 features = {CDC, COMPUTED_COLUMNS, CORRECT_COUNTER_ORDER, CORRECT_NON_COMPOUND_RANGE_TOMBSTONES, CORRECT_STATIC_COMPACT_IN_MC, COUNTERS, DIGEST_INSENSITIVE_TO_EXPIRY, DIGEST_MULTIPARTITION_READ, HINTED_HANDOFF_SEPARATE_CONNECTION, INDEXES, LARGE_PARTITIONS, LA_SSTABLE_FORMAT, LWT, MATERIALIZED_VIEWS, MC_SSTABLE_FORMAT, NONFROZEN_UDTS, PER_TABLE_PARTITIONERS, RANGE_TOMBSTONES, ROLES, ROW_LEVEL_REPAIR, SCHEMA_TABLES_V3, STREAM_WITH_RPC_STREAM, TRUNCATION_TABLE, UNBOUNDED_RANGE_TOMBSTONES, VIEW_VIRTUAL_COLUMNS, WRITE_FAILURE_REPLY, XXHASH}, Remote common_features = {CDC, COMPUTED_COLUMNS, CORRECT_COUNTER_ORDER, CORRECT_NON_COMPOUND_RANGE_TOMBSTONES, CORRECT_STATIC_COMPACT_IN_MC, COUNTERS, DIGEST_INSENSITIVE_TO_EXPIRY, DIGEST_MULTIPARTITION_READ, HINTED_HANDOFF_SEPARATE_CONNECTION, INDEXES, LARGE_PARTITIONS, LA_SSTABLE_FORMAT, LWT, MATERIALIZED_VIEWS, MC_SSTABLE_FORMAT, NONFROZEN_UDTS, PER_TABLE_PARTITIONERS, RANGE_TOMBSTONES, ROLES, ROW_LEVEL_REPAIR, SCHEMA_TABLES_V3, STREAM_WITH_RPC_STREAM, TRUNCATION_TABLE, UNBOUNDED_RANGE_TOMBSTONES, VIEW_VIRTUAL_COLUMNS, WRITE_FAILURE_REPLY, XXHASH}
.
.
.
2020-06-19T03:15:44+00:00  rolling-upgrade-master-ubuntu-xenia-db-node-12d4c66a-0-4 !INFO    | scylla:  [shard 0] init - Shutting down sighup was successful
2020-06-19T03:15:44+00:00  rolling-upgrade-master-ubuntu-xenia-db-node-12d4c66a-0-4 !ERR     | scylla:  [shard 0] init - Startup failed: std::runtime_error (Other bootstrapping/leaving/moving nodes detected, cannot bootstrap while consistent_rangemovement is true (check_for_endpoint_collision))
```


There are two sources that could have caused this to be slower:
1. repair based operations
2. cdc generation 

Having said that starting all nodes at the same time is not the prepferred method - you should be adding node after node.

So we can do a quick change and instead of doing 30 seconds delay at the bootstrap change that to be 2 minutes - I expect that will work.

Or 

We can do a fix and have the other nodes started one by one. waiting till they complete the bootstrap and then moving to the next one.

**Comment by roydahan** [comment] 2020-07-29 13:22
I think this issue can be closed now.
We extended the time between each node boot and we don't face this issue anymore.

**Closed by roydahan** 2020-07-29 13:22 UTC

**Comment by aleksbykov** [comment] 2020-09-16 07:55
Issue was reproduced : https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/abykov/job/longevity-counters-multidc-test/6/ during this job. During setup cluster in 3 dc, this error happened on 2 nodes in different datacenters and cluster setup failed.
When cluster initialization switched to sequential bootstrap, error was not reproduced

**Comment by roydahan** [comment] 2020-09-16 08:56
Itjust means we need to use sequential bootstrap.
