### ISSUE TITLE
Nodes are still in cluster after removing

### ISSUE THREAD

**Issue by vladamir** [scylladb/scylla#4879] opened 2019-08-21 19:24 UTC
Hello! I have cluster of 15 nodes and use docker containers with 3.0.7 version. A few days ago I noticed that my two nodes had got slow (RAID of HDD disks was spoiled I suppose) and it caused problems with performance. And also I couldn't make decomission and I decided to stop nodes and remove them with `nodetool removenode` consistently. 

After when all streaming was done my `nodetool status` shows:
```
...
UN  xx.xx.xx.164  5.86 TB    256          11.8%             9012f39e-8549-46fc-b44d-23071ff27e31  rack1
DL  xx.xx.xx.166  ?          256          11.9%             83d61e57-88d0-4109-80fe-2d54804ee843  rack1
UN  xx.xx.xx.121  5.78 TB    256          11.8%             f8f25625-a17f-4733-bbf2-5d3dd11a207a  rack1
DL  xx.xx.xx.120  ?          256          12.4%             5557d4e7-a0b0-4a52-87d8-eab069b206cf  rack1
UN  xx.xx.xx.123  6.07 TB    256          11.8%             a84d453c-25e2-4577-8fd1-ab638e44fa4b  rack1
UN  xx.xx.xx.122  5.98 TB    256          11.5%             a4bf7405-1697-4caa-9bd1-b01f2566c5d3  rack1
...
```

And now I see the unavailable writes (also I writes by 300k per second in cluster and unavailable writes are only 1000 per sec in total): 
![2019-08-21_04-32-48](https://user-images.githubusercontent.com/6245972/63458281-36162600-c45b-11e9-8e23-24480f9e587a.png)

Also I see in all logs these ones: 
```
...
INFO  2019-08-21 18:38:44,430 [shard 0] rpc - client xx.xx.xx.120: fail to connect: Connection refused
INFO  2019-08-21 18:38:48,457 [shard 0] rpc - client xx.xx.xx.166: fail to connect: Connection refused
...
```
What is notably is that all logs only for `shard 0`. 

`gossipinfo` shows that the nodes in leaving state, like `STATUS:removing,83d61e57-88d0-4109-80fe-2d54804ee843`. I removed bad nodes from docker command `--seeds` as well. `nodetool ring` also shows that all tokens are `Down` and `Leaving` for the nodes:

```
...
xx.xx.xx.166  rack1       Down   Leaving ?               ?                   8774672615714952944
xx.xx.xx.166  rack1       Down   Leaving ?               ?                   8800082315674012015
xx.xx.xx.166  rack1       Down   Leaving ?               ?                   9005413896449824563
xx.xx.xx.166  rack1       Down   Leaving ?               ?                   9218701704409434219
...
``` 

I have only one table, RF=2, and following table's settings:
```
    PRIMARY KEY ((client_id, key_hash), id)
) WITH CLUSTERING ORDER BY (id ASC)
    AND bloom_filter_fp_chance = 0.01
    AND caching = {'keys': 'ALL', 'rows_per_partition': 'ALL'}
    AND comment = ''
    AND compaction = {'class': 'TimeWindowCompactionStrategy', 'compaction_window_size': '1', 'compaction_window_unit': 'HOURS'}
    AND compression = {'chunk_length_kb': '64', 'sstable_compression': 'org.apache.cassandra.io.compress.LZ4Compressor'}
    AND crc_check_chance = 1.0
    AND dclocal_read_repair_chance = 0.1
    AND default_time_to_live = 2592000
    AND gc_grace_seconds = 86400
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair_chance = 0.0
    AND speculative_retry = '99.0PERCENTILE';
```

Due to this I have some questions:

- Is there a way to remove the unavailable nodes from cluster at all?
- Where can I find more info about shard 0 and unavailable writes into it?
- Is it needed to provide any information else?

**Comment by tzach** [comment] 2019-08-26 07:04
@asias, please advise

**Comment by asias** [comment] 2019-08-26 07:15
Hello @vladamir, with the help from slack channel. I saw you reported the issue is gone. Can we close the issue now?

**Comment by slivne** [comment] 2019-09-05 10:21
@vladamir I am closing this issue - if there is additional help needed please post and we can work on it

@asias - we do need to fix the issue - he solved it with a workaround

**Closed** 2019-09-05 10:21 UTC
Labels: User Request, bug

**Comment by vladamir** [comment] 2019-09-05 10:56
Ok, thank you! Yes, I removed old nodes from `system.peers` and it worked. I didn't catch why it happened and why they didn't removed from `system.peers` by themselves. Maybe because my tokens relocating process took much time and it didn't finish properly.
