### ISSUE TITLE
CDC: backtrace for Exceptional future ignored: seastar::rpc::closed_error (connection is closed)

### ISSUE THREAD

**Issue by enaydanov** [scylladb/scylla#7601] opened 2020-11-12 17:47 UTC
Got backtrace on RepairStreamingErr nemesis target node (10.0.0.80).

*Installation details*

Cluster size: 6
Instance type: i3.4xlarge
AMI: ami-034b9d27312bbd929 (eu-north-1)
SCT test id: e0c4fd22-f973-46eb-805d-2f9b65af0cf3
Job link: https://jenkins.scylladb.com/job/scylla-4.3/job/longevity/job/longevity-cdc-100gb-4h-test/8/
Test name: longevity-cdc-100gb-4h-test
Test config: https://github.com/scylladb/scylla-cluster-tests/blob/branch-4.3/test-cases/longevity/longevity-cdc-100gb-4h.yaml
DB logs: https://cloudius-jenkins-test.s3.amazonaws.com/e0c4fd22-f973-46eb-805d-2f9b65af0cf3/20201112_123339/db-cluster-e0c4fd22.zip

```
(DatabaseLogEvent Severity.ERROR): type=BACKTRACE regex=backtrace line_number=46657 node=Node longevity-cdc-100gb-4h-4-3-db-node-e0c4fd22-4 [13.49.74.26 | 10.0.1.80] (seed: False)
2020-11-12T10:35:49+00:00  longevity-cdc-100gb-4h-4-3-db-node-e0c4fd22-4 !WARNING | scylla: [shard 6] seastar - Exceptional future ignored: seastar::rpc::closed_error (connection is closed), backtrace:    0x2fb7e0d#012   0x2fb8060#012   0x2fb84c9#012   0x2b03ad7#012   0x2b03c1c#012   0x1f07f37#012   0x2b59867#012   0x2b59b1e#012   0x2b99405#012   0x2baabba#012   0x2b2378d#012   /opt/scylladb/libreloc/libpthread.so.0+0x9431#012   /opt/scylladb/libreloc/libc.so.6+0x101912#012   --------#012   seastar::continuation, seastar::rpc::source > >, netw::do_make_sink_source(netw::messaging_verb, unsigned int, seastar::shared_ptr, std::unique_ptr >&)::{lambda(seastar::rpc::sink)#1}::operator()(seastar::rpc::sink)::{lambda(seastar::future >)#1}::operator()({lambda(seastar::rpc::sink)#1})::{lambda()#1}, seastar::future::then_impl_nrvo<{lambda(seastar::future >)#1}, seastar::future, seastar::rpc::source > > >({lambda(seastar::future >)#1}&&)::{lambda(seastar::internal::promise_base_with_type, seastar::rpc::source > >&&, {lambda(seastar::future >)#1}&, seastar::future_state&&)#1}, void>
backtrace > at /usr/include/c++/10/bits/basic_string.h:323
 (inlined by) seastar::current_backtrace_tasklocal() at ./build/release/seastar/./seastar/src/util/backtrace.cc:86
seastar::current_tasktrace() at /usr/include/c++/10/bits/basic_string.h:323
seastar::current_backtrace() at /usr/include/c++/10/bits/basic_string.h:323
seastar::report_failed_future(std::__exception_ptr::exception_ptr const&) at future.cc:?
seastar::report_failed_future(seastar::future_state_base::any&&) at future.cc:?
seastar::continuation, seastar::rpc::source > >, seastar::future, seastar::rpc::source > > netw::do_make_sink_source(netw::messaging_verb, unsigned int, seastar::shared_ptr, std::unique_ptr >&)::{lambda(seastar::rpc::sink)#1}::operator()(seastar::rpc::sink)::{lambda(seastar::future >)#1}::operator()({lambda(seastar::rpc::sink)#1})::{lambda()#1}, seastar::future, seastar::rpc::source > > seastar::future::then_impl_nrvo<{lambda(seastar::future >)#1}, seastar::future, seastar::rpc::source > > >({lambda(seastar::future >)#1}&&)::{lambda(seastar::internal::promise_base_with_type, seastar::rpc::source > >&&, {lambda(seastar::future >)#1}&, seastar::future_state&&)#1}, void>::run_and_dispose() at messaging_service.cc:?
 (inlined by) seastar::future_state >::clear() at ././seastar/include/seastar/core/future.hh:609
 (inlined by) seastar::future_state >::~future_state() at ././seastar/include/seastar/core/future.hh:614
 (inlined by) seastar::future >::~future() at ././seastar/include/seastar/core/future.hh:1337
 (inlined by) seastar::future, seastar::rpc::source > > netw::do_make_sink_source(netw::messaging_verb, unsigned int, seastar::shared_ptr, std::unique_ptr >&)::{lambda(seastar::rpc::sink)#1}::operator()(seastar::rpc::sink)::{lambda(seastar::future >)#1}::operator()(seastar::rpc::source)::{lambda()#1}::~unique_ptr() at ./message/messaging_service.cc:816
 (inlined by) seastar::continuation, seastar::rpc::source > >, seastar::future, seastar::rpc::source > > netw::do_make_sink_source(netw::messaging_verb, unsigned int, seastar::shared_ptr, std::unique_ptr >&)::{lambda(seastar::rpc::sink)#1}::operator()(seastar::rpc::sink)::{lambda(seastar::future >)#1}::operator()({lambda(seastar::rpc::sink)#1})::{lambda()#1}, seastar::future, seastar::rpc::source > > seastar::future::then_impl_nrvo<{lambda(seastar::future >)#1}, seastar::future, seastar::rpc::source > > >({lambda(seastar::future >)#1}&&)::{lambda(seastar::internal::promise_base_with_type, seastar::rpc::source > >&&, {lambda(seastar::future >)#1}&, seastar::future_state&&)#1}, void>::~continuation() at ././seastar/include/seastar/core/future.hh:750
 (inlined by) seastar::continuation, seastar::rpc::source > >, seastar::future, seastar::rpc::source > > netw::do_make_sink_source(netw::messaging_verb, unsigned int, seastar::shared_ptr, std::unique_ptr >&)::{lambda(seastar::rpc::sink)#1}::operator()(seastar::rpc::sink)::{lambda(seastar::future >)#1}::operator()({lambda(seastar::rpc::sink)#1})::{lambda()#1}, seastar::future, seastar::rpc::source > > seastar::future::then_impl_nrvo<{lambda(seastar::future >)#1}, seastar::future, seastar::rpc::source > > >({lambda(seastar::future >)#1}&&)::{lambda(seastar::internal::promise_base_with_type, seastar::rpc::source > >&&, {lambda(seastar::future >)#1}&, seastar::future_state&&)#1}, void>::run_and_dispose() at ././seastar/include/seastar/core/future.hh:771
seastar::reactor::run_tasks(seastar::reactor::task_queue&) at reactor.cc:?
seastar::reactor::run_some_tasks() [clone .part.0] at reactor.cc:?
seastar::reactor::run() at reactor.cc:?
 (inlined by) seastar::reactor::run() at ./build/release/seastar/./seastar/src/core/reactor.cc:2730
operator() at ./build/release/seastar/./seastar/src/core/reactor.cc:3906
std::function::operator()() const at /usr/include/c++/10/bits/basic_string.h:323
 (inlined by) seastar::posix_thread::start_routine(void*) at ./build/release/seastar/./seastar/src/core/posix.cc:60
?? ??:0
?? ??:0
```

![image](https://user-images.githubusercontent.com/63434/98972989-c13e7880-2545-11eb-847d-431c6ea30f72.png)

```
 $ hydra investigate show-monitor e0c4fd22-f973-46eb-805d-2f9b65af0cf3
```

**Comment by roydahan** [comment] 2020-11-12 18:11
@enaydanov if that's happen when we kill the the node in order to cause the streaming error, that's expected.
I can't tell from the info you shared, but please check the timings.
(You can also consult @aleksbykov that had something similar on master).

**Comment by enaydanov** [comment] 2020-11-15 09:34
@roydahan yes, we stop this instance, and it looks more like cosmetic issue: having backtraces in the log is not a good thing.

**Comment by slivne** [comment] 2020-11-15 10:09
To make it clear - this can happen when a node is lost - not when a node is drained / decommissioned. 

The reason to include the backtrace is the log is for the cases in which we did not kill a node and got an error and then the backtrace may help to understand what was the source.

I am closing this as having the additional information to understand what is the source of the issue is needed.

**Closed by slivne** 2020-11-15 10:09 UTC
