### ISSUE TITLE
alter table failed with timeouts (lack of schema agreement)

### ISSUE THREAD

**Issue by harelassayag** [scylladb/scylla#2820] opened 2017-09-19 17:08 UTC
*Installation details*
Scylla version (or git commit hash): 2.0.rc4-0.20170903.6e6de34
Cluster size: 4 nodes
OS (RHEL/CentOS/Ubuntu/AWS AMI): CentOS
```
2017-09-18 11:46:38,043 nemesis          L0429 DEBUG| sdcm.nemesis.ChaosMonkey: Start disruption at `2017-09-18 11:46:38.043905`
2017-09-18 11:46:38,045 nemesis          L0374 INFO | sdcm.nemesis.ChaosMonkey: >>>>>>>>>>>>>Started random_disrupt_method <bound method ChaosMonkey.disrupt_modify_table_gc_grace_time of <sdcm.nemesis.ChaosMonke
y object at 0x518ffd0>>
2017-09-18 11:46:38,566 nemesis          L0187 DEBUG| sdcm.nemesis.ChaosMonkey: Set current_disruption -> ModifyTableProperties Node longevity-1tb-7d-2-0-db-node-22c2eaea-0-6 [35.185.56.180 | 10.240.0.92] (seed:
 False)
2017-09-18 11:46:38,566 nemesis          L0189 INFO | sdcm.nemesis.ChaosMonkey: ModifyTableProperties Node longevity-1tb-7d-2-0-db-node-22c2eaea-0-6 [35.185.56.180 | 10.240.0.92] (seed: False)
2017-09-18 11:46:38,853 remote           L0894 DEBUG| Remote [scylla-test@35.185.56.180]: Running 'cqlsh -e "ALTER TABLE keyspace1.standard1 with comment = 'gc_grace_seconds changed' AND gc_grace_seconds = 32744
6;" 10.240.0.92'
2017-09-18 11:46:38,853 remote           L0097 INFO | [35.185.56.180] Running '/bin/ssh -tt -a -x   -o StrictHostKeyChecking=no -o UserKnownHostsFile=/var/tmp/tmp39cW_U -o BatchMode=yes -o ConnectTimeout=300 -o 
ServerAliveInterval=300 -l scylla-test -p 22 -i /jenkins/.ssh/scylla-test 35.185.56.180 "cqlsh -e \"ALTER TABLE keyspace1.standard1 with comment = 'gc_grace_seconds changed' AND gc_grace_seconds = 327446;\" 10.2
40.0.92"'
2017-09-18 11:46:40,398 remote           L0197 DEBUG| [35.196.213.154] [stdout] Sep 18 11:46:40 info   |  [shard 12] schema_tables - Altering keyspace1.standard1 id=a342c800-9bb8-11e7-87a9-000000000001 version=7
c300309-e69f-3503-89da-47bd57530883
2017-09-18 11:46:40,415 remote           L0197 DEBUG| [35.185.56.180] [stdout] Sep 18 11:46:40 info   |  [shard 12] schema_tables - Altering keyspace1.standard1 id=a342c800-9bb8-11e7-87a9-000000000001 version=7c300309-e69f-3503-89da-47bd57530883
2017-09-18 11:46:40,416 remote           L0197 DEBUG| [35.196.213.154] [stdout] Sep 18 11:46:40 info   |  [shard 13] query_processor - Column definitions for keyspace1.standard1 changed, invalidating related prepared statements
2017-09-18 11:46:40,417 remote           L0197 DEBUG| [35.196.213.154] [stdout] Sep 18 11:46:40 info   |  [shard 10] query_processor - Column definitions for keyspace1.standard1 changed, invalidating related prepared statements
...
17-09-18 11:46:40,418 asyncorereactor  L0383 DEBUG| Message pushed from server: <EventMessage(event_type=u'SCHEMA_CHANGE', trace_id=None, event_args={'keyspace': u'keyspace1', 'change_type': u'UPDATED', 'target_type': u'TABLE', u'table': u'standard1'}, stream_id=-1)>
2017-09-18 11:46:40,419 remote           L0197 DEBUG| [35.196.213.154] [stdout] Sep 18 11:46:40 info   |  [shard 12] query_processor - Column definitions for keyspace1.standard1 changed, invalidating related prepared statements
2017-09-18 11:46:40,419 remote           L0197 DEBUG| [35.196.213.154] [stdout] Sep 18 11:46:40 info   |  [shard 6] query_processor - Column definitions for keyspace1.standard1 changed, invalidating related prepared statements
...
2017-09-18 11:46:40,478 remote           L0197 DEBUG| [35.185.56.180] [stdout] Sep 18 11:46:40 info   |  [shard 12] database - Schema version changed to b9630c5d-eded-3f17-88fc-445279e1fc5a
2017-09-18 11:46:40,599 remote           L0197 DEBUG| [35.196.213.154] [stdout] Sep 18 11:46:40 info   |  [shard 12] database - Schema version changed to b9630c5d-eded-3f17-88fc-445279e1fc5a
2017-09-18 11:46:40,797 remote           L0197 DEBUG| [35.196.3.55] [stdout] Sep 18 11:46:40 info   |  [shard 4] schema_tables - Altering keyspace1.standard1 id=a342c800-9bb8-11e7-87a9-000000000001 version=7c300309-e69f-3503-89da-47bd57530883
2017-09-18 11:46:40,813 remote           L0197 DEBUG| [35.196.3.55] [stdout] Sep 18 11:46:40 info   |  [shard 4] query_processor - Column definitions for keyspace1.standard1 changed, invalidating related prepared statements
2017-09-18 11:46:40,814 remote           L0197 DEBUG| [35.196.3.55] [stdout] Sep 18 11:46:40 info   |  [shard 3] query_processor - Column definitions for keyspace1.standard1 changed, invalidating related prepared statements
...
2017-09-18 11:46:40,999 remote           L0197 DEBUG| [35.196.3.55] [stdout] Sep 18 11:46:40 info   |  [shard 4] database - Schema version changed to b9630c5d-eded-3f17-88fc-445279e1fc5a
2017-09-18 11:46:41,021 thread           L0062 DEBUG| [control connection] Waiting for schema agreement
2017-09-18 11:46:41,053 thread           L0062 DEBUG| [control connection] Schemas mismatched, trying again
2017-09-18 11:46:41,262 thread           L0062 DEBUG| [control connection] Schemas mismatched, trying again
...
2017-09-18 11:46:44,730 threading        L0811 DEBUG| Sending options message heartbeat on idle connection (87123600) 35.196.213.154
2017-09-18 11:46:44,732 asyncorereactor  L0383 DEBUG| Received options response on connection (87123600) from 35.196.213.154
2017-09-18 11:46:44,909 thread           L0062 DEBUG| [control connection] Schemas mismatched, trying again
2017-09-18 11:46:45,117 thread           L0062 DEBUG| [control connection] Schemas mismatched, trying again
...
017-09-18 11:46:49,487 remote           L0197 DEBUG| [35.185.56.180] [stdout] <stdin>:1:OperationTimedOut: errors={'10.240.0.92': 'Request timed out while waiting for schema agreement. See Session.execute[_async](timeout) and Cluster.max_schema_agreement_wait.'}, last_host=10.240.0.92
2017-09-18 11:46:49,495 thread           L0062 DEBUG| [control connection] Schemas mismatched, trying again
2017-09-18 11:46:49,728 thread           L0062 DEBUG| [control connection] Schemas mismatched, trying again
...
2017-09-18 11:46:51,090 thread           L0062 WARNI| Node 35.196.213.154 is reporting a schema disagreement: {UUID('b9630c5d-eded-3f17-88fc-445279e1fc5a'): ['10.240.0.94', '35.196.213.154', '10.240.0.92'], UUID('ae819f79-f4d1-34c5-a17e-ca0c1ad9b520'): ['10.240.0.90']}
2017-09-18 11:46:51,091 thread           L0062 DEBUG| Skipping schema refresh due to lack of schema agreement
2017-09-18 11:46:58,693 remote           L0197 DEBUG| [35.196.66.85] [stdout] Sep 18 11:46:58 info   |  [shard 4] schema_tables - Altering keyspace1.standard1 id=a342c800-9bb8-11e7-87a9-000000000001 version=7c300309-e69f-3503-89da-47bd57530883
2017-09-18 11:46:58,717 remote           L0197 DEBUG| [35.196.66.85] [stdout] Sep 18 11:46:58 info   |  [shard 4] query_processor - Column definitions for keyspace1.standard1 changed, invalidating related prepared statements
2017-09-18 11:46:58,738 remote           L0197 DEBUG| [35.196.66.85] [stdout] Sep 18 11:46:58 info   |  [shard 12] query_processor - Column definitions for keyspace1.standard1 changed, invalidating related prepared statements
...
2017-09-18 11:46:59,671 remote           L0197 DEBUG| [35.196.66.85] [stdout] Sep 18 11:46:59 info   |  [shard 4] database - Schema version changed to b9630c5d-eded-3f17-88fc-445279e1fc5a
2017-09-18 11:47:01,179 remote           L0197 DEBUG| [35.185.56.180] [stderr] Connection to 35.185.56.180 closed.
2017-09-18 11:47:01,180 nemesis          L0437 ERROR| sdcm.nemesis.ChaosMonkey: Unhandled exception in method <function disrupt at 0x5059848>
```
alter table failed. nodetool status and scylla --version also fails on nodes
```
[harel@longevity-1tb-7d-2-0-db-node-22c2eaea-0-6 ~]$ scylla --version
FATAL: Exception during startup, aborting: std::system_error (error system:12, Cannot allocate memory)
[harel@longevity-1tb-7d-2-0-db-node-22c2eaea-0-6 ~]$ nodetool status
Cassandra 3.0 and later require Java 8u40 or later.

```

**Comment by harelassayag** [comment] 2017-09-20 11:16
@slivne can we terminate the machines of this environment?

**Comment by tgrabiec** [comment] 2017-09-20 11:20
@harelassayag Please collect full logs. It looks like the propagation is just slow, it eventually happens.

**Comment by harelassayag** [comment] 2017-09-24 12:18
@tgrabiec 
The issue has reproduced in version 2.0.rc5-0.20170917.0b49cfc. Cluster size is identical, 4 nodes with 1TB data set. I uploaded the entire log (combined log from all the nodes and loader) to [http://scylladb-users-upload.s3.amazonaws.com/2820/log.tar.gz](http://scylladb-users-upload.s3.amazonaws.com/2820/log.tar.gz)
the 'OperationTimedOut' and 'Skipping schema refresh due to lack of schema agreement' appears at:
```
2017-09-20 20:28:19,255 thread           L0062 DEBUG| [control connection] Schemas mismatched, trying again
2017-09-20 20:28:19,488 thread           L0062 DEBUG| [control connection] Schemas mismatched, trying again
2017-09-20 20:28:19,540 remote           L0197 DEBUG| [35.196.139.72] [stdout] <stdin>:1:OperationTimedOut: errors={'10.240.0.30': 'Request timed out while waiting for schema agreement. See Session.execute[_asyn
c](timeout) and Cluster.max_schema_agreement_wait.'}, last_host=10.240.0.30
2017-09-20 20:28:19,721 thread           L0062 DEBUG| [control connection] Schemas mismatched, trying again
2017-09-20 20:28:19,954 thread           L0062 DEBUG| [control connection] Schemas mismatched, trying again
2017-09-20 20:28:20,186 thread           L0062 DEBUG| [control connection] Schemas mismatched, trying again
2017-09-20 20:28:20,419 thread           L0062 DEBUG| [control connection] Schemas mismatched, trying again
2017-09-20 20:28:20,651 thread           L0062 DEBUG| [control connection] Schemas mismatched, trying again
2017-09-20 20:28:20,884 thread           L0062 DEBUG| [control connection] Schemas mismatched, trying again
2017-09-20 20:28:21,117 thread           L0062 DEBUG| [control connection] Schemas mismatched, trying again
2017-09-20 20:28:21,317 thread           L0062 WARNI| Node 35.185.60.64 is reporting a schema disagreement: {UUID('ab6ae5b0-bdb5-3954-9dc8-aaea31faed45'): ['10.240.0.60'], UUID('80e24461-3c0a-3d1e-b5f2-dc965ba9b
9ce'): ['35.185.60.64', '10.240.0.30', '10.240.0.41']}

```

**Comment by tgrabiec** [comment] 2017-09-25 09:15
@harelassayag Do you have premethus metrics for the run?

**Comment by harelassayag** [comment] 2017-09-25 09:24
@tgrabiec yes, I'll upload it here and inform you when finish

**Comment by tgrabiec** [comment] 2017-09-25 13:19
Here are some relevant log events:
```
2017-09-20 20:28:08,727 remote           L0894 DEBUG| Remote [scylla-test@35.196.139.72]: Running 'cqlsh -e "ALTER TABLE keyspace1.standard1 with comment = 'jwxTSuJdClBsVdZKHxxEhgST';" 10.240.0.30'
2017-09-20 20:28:08,727 remote           L0097 INFO | [35.196.139.72] Running '/bin/ssh -tt -a -x   -o StrictHostKeyChecking=no -o UserKnownHostsFile=/var/tmp/tmpCOlEWf -o BatchMode=yes -o ConnectTimeout=300 -o ServerAliveInterval=300 -l scylla-test -p 22 -i /jenkins/.ssh/scylla-test 35.196.139.72 "cqlsh -e \"ALTER TABLE keyspace1.standard1 with comment = 'jwxTSuJdClBsVdZKHxxEhgST';\" 10.240.0.30"'
2017-09-20 20:28:09,453 remote           L0197 DEBUG| [35.196.139.72] [stdout] Sep 20 20:28:09 info   |  [shard 9] migration_manager - Update table 'keyspace1.standard1' From org.apache.cassandra.config.CFMetaData@0x6090044d4e00[cfId=6599a590-9d67-11e7-99f6-000000000003,ksName=keyspace1,cfName=standard1,cfType=Standard,comparator=org.apache.cassandra.db.marshal.UTF8Type,comment=REseOouwskpVZOJkbaEUXTey,readRepairChance=0,dcLocalReadRepairChance=0.1,gcGraceSeconds=498365,keyValidator=org.apache.cassandra.db.marshal.BytesType,minCompactionThreshold=4,maxCompactionThreshold=32,columnMetadata=[ColumnDefinition{name=key, type=org.apache.cassandra.db.marshal.BytesType, kind=PARTITION_KEY, componentIndex=0, droppedAt=-9223372036854775808}, ColumnDefinition{name=C0, type=org.apache.cassandra.db.marshal.BytesType, kind=REGULAR, componentIndex=null, droppedAt=-9223372036854775808}],compactionStrategyClass=class org.apache.cassandra.db.compaction.LeveledCompactionStrategy,compactionStrategyOptions={enabled=true},compressionParameters={},bloomFilterFpChance=0.01,memtableFlushPeriod=0,caching={"keys":"ALL","rows_per_partition":"ALL"},defaultTimeToLive=0,minIndexInterval=128,maxIndexInterval=2048,speculativeRetry=99.0PERCENTILE,triggers=[],isDense=false,version=c244410a-a957-31c0-bd9e-a733a3fc9200,droppedColumns={},collections={},indices={}] To org.apache.cassandra.config.CFMetaData@0x6090044d5500[cfId=6599a590-9d67-11e7-99f6-000000000003,ksName=keyspace1,cfName=standard1,cfType=Standard,comparator=org.apache.cassandra.db.marshal.UTF8Type,comment=jwxTSuJdClBsVdZKHxxEhgST,readRepairChance=0,dcLocalReadRepairChance=0.1,gcGraceSeconds=498365,keyValidator=org.apache.cassandra.db.marshal.BytesType,minCompactionThreshold=4,maxCompactionThreshold=32,columnMetadata=[ColumnDefinition{name=key, type=org.apache.cassandra.db.marshal.BytesType, kind=PARTITION_KEY, componentIndex=0, droppedAt=-9223372036854775808}, ColumnDefinition{name=C0, type=org.apache.cassandra.db.marshal.BytesType, kind=REGULAR, componentIndex=null, droppedAt=-9223372036854775808}],compactionStrategyClass=class org.apache.cassandra.db.compaction.LeveledCompactionStrategy,compactionStrategyOptions={enabled=true},compressionParameters={},bloomFilterFpChance=0.01,memtableFlushPeriod=0,caching={"keys":"ALL","rows_per_partition":"ALL"},defaultTimeToLive=0,minIndexInterval=128,maxIndexInterval=2048,speculativeRetry=99.0PERCENTILE,triggers=[],isDense=false,version=37836e80-9e42-11e7-9459-000000000009,droppedColumns={},collections={},indices={}]
2017-09-20 20:28:09,871 remote           L0197 DEBUG| [35.185.60.64] [stdout] Sep 20 20:28:09 info   |  [shard 1] schema_tables - Altering keyspace1.standard1 id=6599a590-9d67-11e7-99f6-000000000003 version=dd4fa92a-3ca0-3bf8-932f-96cac54aa61b
2017-09-20 20:28:09,875 remote           L0197 DEBUG| [35.196.139.72] [stdout] Sep 20 20:28:09 info   |  [shard 9] schema_tables - Altering keyspace1.standard1 id=6599a590-9d67-11e7-99f6-000000000003 version=dd4fa92a-3ca0-3bf8-932f-96cac54aa61b
2017-09-20 20:28:09,932 remote           L0197 DEBUG| [35.196.139.72] [stdout] Sep 20 20:28:09 info   |  [shard 9] database - Schema version changed to 80e24461-3c0a-3d1e-b5f2-dc965ba9b9ce
2017-09-20 20:28:09,953 remote           L0197 DEBUG| [35.185.60.64] [stdout] Sep 20 20:28:09 info   |  [shard 1] database - Schema version changed to 80e24461-3c0a-3d1e-b5f2-dc965ba9b9ce
2017-09-20 20:28:10,627 remote           L0197 DEBUG| [35.196.158.234] [stdout] Sep 20 20:28:10 info   |  [shard 15] schema_tables - Altering keyspace1.standard1 id=6599a590-9d67-11e7-99f6-000000000003 version=dd4fa92a-3ca0-3bf8-932f-96cac54aa61b
2017-09-20 20:28:10,944 remote           L0197 DEBUG| [35.196.158.234] [stdout] Sep 20 20:28:10 info   |  [shard 15] database - Schema version changed to 80e24461-3c0a-3d1e-b5f2-dc965ba9b9ce
2017-09-20 20:28:12,370 remote           L0197 DEBUG| [35.196.158.234] [stdout] Sep 20 20:28:12 info   |  [shard 0] database - Schema version changed to 80e24461-3c0a-3d1e-b5f2-dc965ba9b9ce
2017-09-20 20:28:23,822 remote           L0197 DEBUG| [104.196.117.12] [stdout] Sep 20 20:28:23 info   |  [shard 3] schema_tables - Altering keyspace1.standard1 id=6599a590-9d67-11e7-99f6-000000000003 version=dd4fa92a-3ca0-3bf8-932f-96cac54aa61b
2017-09-20 20:28:25,320 remote           L0197 DEBUG| [104.196.117.12] [stdout] Sep 20 20:28:25 info   |  [shard 3] database - Schema version changed to 80e24461-3c0a-3d1e-b5f2-dc965ba9b9ce
2017-09-20 20:28:39,061 remote           L0197 DEBUG| [104.196.117.12] [stdout] Sep 20 20:28:39 info   |  [shard 0] database - Schema version changed to 80e24461-3c0a-3d1e-b5f2-dc965ba9b9ce
```

3 nodes apply the schema change quickly (<2s), but one node (104.196.117.12, aka node 4) takes 16 seconds to do it:
```
35.196.139.72:  20:28:09,932 (+0.5s)
35.185.60.64:   20:28:09,953 (+0.5s)
35.196.158.234: 20:28:10,944 (+1.5s)
104.196.117.12: 20:28:25,320 (+16s)
```

From the compaction log I infer that it has flushed at least some of the schema tables, as part of applying the change, no later than at `20:28:11,210`, that is 14 seconds before the change was fully applied:
```
2017-09-20 20:28:11,210 remote           L0197 DEBUG| [104.196.117.12] [stdout] Sep 20 20:28:11 info   |  [shard 14] compaction - Compacting [/var/lib/scylla/data/system_schema/indexes-0feb57ac311f382fba6d9024d305702f/system_schema-indexes-ka-158-Data.db:level=0, /var/lib/scylla/data/system_schema/indexes-0feb57ac311f382fba6d9024d305702f/system_schema-indexes-ka-174-Data.db:leve
l=0, /var/lib/scylla/data/system_schema/indexes-0feb57ac311f382fba6d9024d305702f/system_schema-indexes-ka-190-Data.db:level=0, /var/lib/scylla/data/system_schema/indexes-0feb57ac311f382fba6d9024d305702f/system_schema-indexes-ka-222-Data.db:level=0, ]

017-09-20 20:28:18,927 remote           L0197 DEBUG| [104.196.117.12] [stdout] Sep 20 20:28:18 info   |  [shard 14] compaction - Compacting [/var/lib/scylla/data/system_schema/dropped_columns-5e7583b5f3f43af19a39b7e1d6f5f11f/system_schema-dropped_columns-ka-158-Data.db:level=0, /var/lib/scylla/data/system_schema/dropped_columns-5e7583b5f3f43af19a39b7e1d6f5f11f/system_schema-dropped_columns-ka-190-Data.db:level=0, /var/lib/scylla/data/system_schema/dropped_columns-5e7583b5f3f43af19a39b7e1d6f5f11f/system_schema-dropped_columns-ka-174-Data.db:level=0, /var/lib/scylla/data/system_schema/dropped_columns-5e7583b5f3f43af19a39b7e1d6f5f11f/system_schema-dropped_columns-ka-222-Data.db:level=0, ]
```

So the schema change is mostly delayed locally, at or after the flush of schema tables.

That node (orange line) happens to issue the largest volume of writes to disk (aio_bytes_write):

![screenshot from 2017-09-25 14-45-39](https://user-images.githubusercontent.com/283695/30808929-54276ebc-a200-11e7-96c5-f2269ff412c4.png)

Mostly from compaction.
IO queue delay for memtable flush is <1ms. 
There is no standing queue for memtable flushes. 
The CPU is <50% utilized. 

The flushes could still block on fdatasync, that is we hit those:
 https://github.com/scylladb/scylla/issues/2127
 https://github.com/scylladb/scylla/issues/1459

This node has ~27% of free space, while others have ~63%.

Action items:
* enable debug-level logging for the `database` logger
* enable trace-level logging for the `migration_manager` logger.
* enable `enable_keyspace_column_family_metrics: true` in the test, so that we have more visibility.
* reduce prometheus scrape period to 2s

**Comment by slivne** [comment] 2017-11-12 11:16
@tgrabiec is this a regression - we may have hit this because of the gossip changes - would 2.0.1 - return this to be similar to 1.7 ?

**Comment by tgrabiec** [comment] 2017-11-13 09:32
The core of the problem seems to be that local application of schema changes takes long, probably gossip changes are unrelated.

Probably fdatasync related. 

This could start timing out if load was increased.

**Comment by amoskong** [comment] 2017-11-22 08:01
Hi @harelassayag How long will you take to reproduce this issue? Can we directly reproduce it with disrupt_modify_table_comment or disrupt_modify_table_gc_grace_time?

**Comment by harelassayag** [comment] 2017-11-22 13:12
@amoskong 

> Hi @harelassayag How long will you take to reproduce this issue?
sorry, I'm not sure.
>  Can we directly reproduce it with disrupt_modify_table_comment or disrupt_modify_table_gc_grace_time?
it is probably a good place to start.

**Comment by amoskong** [comment] 2017-11-26 15:02
The `lack of schema agreement` was reproduced 3 times when the longevity-1tb-auth run 3 days, but they are not about modify table, but schema refresh

Scylla version: scylla-server-2.0.1-0.20171115.7b19167.el7.centos.x86_64.rpm 
Test job: longevity-1TB-7days-authorization-and-tls-ssl

```
$ cat latest/job.log |grep 'lack of'
2017-11-23 10:44:40,299 sysinfo L0104 DEBUG| Not logging /proc/slabinfo (lack of permissions)
2017-11-25 09:27:28,189 thread L0055 DEBUG| Skipping schema refresh due to lack of schema agreement
2017-11-25 14:22:52,080 thread L0055 DEBUG| Skipping schema refresh due to lack of schema agreement
2017-11-25 21:42:56,443 thread L0055 DEBUG| Skipping schema refresh due to lack of schema agreement
```

**Comment by amoskong** [comment] 2017-12-06 01:40
@tgrabiec can you help to check above result? I can provide the full datbase log (later)

**Comment by tgrabiec** [comment] 2017-12-06 07:20
@amoskong What do you want me to check?

**Comment by amoskong** [comment] 2017-12-12 03:35
I didn't reproduce this problem again.

**Comment by amoskong** [comment] 2017-12-13 03:25
@tgrabiec I touched this problem in  2.1 longevity:

Job: http://jenkins.cloudius-systems.com:8080/job/scylla-master-longevity-gce/label=gce3-qavpc/23/

Log backup: https://s3.amazonaws.com/scylladb-users-upload/scylla-qa-team/job-2017-12-12T23.27-c58f5c3.tar.gz

```
$ find job-2017-12-12T23.27-c58f5c3|grep database.log$
job-2017-12-12T23.27-c58f5c3/test-results/1-longevity_test.py:LongevityTest.test_custom_time/longevity-50gb-4d-master-db-cluster-568b6ef3/longevity-50gb-4d-master-db-node-568b6ef3-0-1/database.log
job-2017-12-12T23.27-c58f5c3/test-results/1-longevity_test.py:LongevityTest.test_custom_time/longevity-50gb-4d-master-db-cluster-568b6ef3/longevity-50gb-4d-master-db-node-568b6ef3-0-2/database.log
job-2017-12-12T23.27-c58f5c3/test-results/1-longevity_test.py:LongevityTest.test_custom_time/longevity-50gb-4d-master-db-cluster-568b6ef3/longevity-50gb-4d-master-db-node-568b6ef3-0-3/database.log
job-2017-12-12T23.27-c58f5c3/test-results/1-longevity_test.py:LongevityTest.test_custom_time/longevity-50gb-4d-master-db-cluster-568b6ef3/longevity-50gb-4d-master-db-node-568b6ef3-0-4/database.log
job-2017-12-12T23.27-c58f5c3/test-results/1-longevity_test.py:LongevityTest.test_custom_time/longevity-50gb-4d-master-db-cluster-568b6ef3/longevity-50gb-4d-master-db-node-568b6ef3-0-5/database.log
job-2017-12-12T23.27-c58f5c3/test-results/1-longevity_test.py:LongevityTest.test_custom_time/longevity-50gb-4d-master-db-cluster-568b6ef3/longevity-50gb-4d-master-db-node-568b6ef3-0-6/database.log
```

I will send you the live cluster info (instance name, ips, etc) by email.

**Comment by slivne** [comment] 2018-01-14 11:36
@tgrabiec / @amoskong - ping ...

**Comment by tgrabiec** [comment] 2018-01-18 12:46
@amoskong I tried to grep the log for the problem of failed alter, but couldn't. Can you point me to the exact error line of concern?

**Comment by slivne** [comment] 2018-02-08 10:25
@amoskong ping

**Comment by tzach** [comment] 2018-04-26 09:38
@amoskong please help

**Comment by amoskong** [comment] 2018-04-26 10:59
@harelassayag @roydahan It seems we didn't touch this problem in recent longevity testing of 2.1/2.2?

@tgrabiec I will recheck the log, and answer your question soon.

**Comment by amoskong** [comment] 2018-04-26 11:03
@roydahan @slivne  I failed to download the log by `https://s3.amazonaws.com/scylladb-users-upload/scylla-qa-team/job-2017-12-12T23.27-c58f5c3.tar.gz`  (Access denied).
I try to make it public in s3 console, but also failed.

Anyone can help to make it available for us?

**Comment by tgrabiec** [comment] 2018-04-26 11:52
@amoskong I'll work with you in private.

**Comment by tzach** [comment] 2018-09-13 10:10
@amoskong / @tgrabiec update ?
If not, we need to reproduce on a later version or close this issue

**Comment by slivne** [comment] 2018-10-04 10:16
closing this issue - we will be testing schema alters as part of 3.0 release.

**Closed by slivne** 2018-10-04 10:16 UTC
Labels: bug
