### ISSUE TITLE
Failed to apply mutation, named_semaphore_timed_out during bootstrapping

### ISSUE THREAD

**Issue by kbr-** [scylladb/scylla#7242] opened 2020-09-15 17:14 UTC
While investigating the failure of https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/abykov/job/feature-cdc-replication-longevity/3/ I noticed a lot of `named_semaphore_timed_out` errors in the log of one of the nodes, such as the following:
```
Sep 15 15:46:37 cdc-replication-longevity-fix-cdc--db-node-9e44e96d-4 scylla[8092]:  [shard 1] storage_proxy - Failed to apply mutation from 10.0.2.18#1: seastar::named_semaphore_timed_out (Semaphore timed out: smp_service_group#2 0->1 semaphore)
```

I noticed that the timing of the errors is kind of interesting. The node has actually finished the `bootstrap_with_repair` phase, i.e. all data was copied, before any error occurred:
```
Sep 15 15:46:01 cdc-replication-longevity-fix-cdc--db-node-9e44e96d-4 scylla[8092]:  [shard 0] repair - bootstrap_with_repair: finished with keyspace=system_traces, nr_ranges=500
Sep 15 15:46:01 cdc-replication-longevity-fix-cdc--db-node-9e44e96d-4 scylla[8092]:  [shard 0] repair - bootstrap_with_repair: finished with keyspaces={ks1, system_auth, system_distributed, system_traces}
Sep 15 15:46:01 cdc-replication-longevity-fix-cdc--db-node-9e44e96d-4 scylla[8092]:  [shard 0] storage_service - Bootstrap completed! for the tokens {5043827841703813806, -2682975273711312799, 7354509136152195856, 7807219823996019926, 5300311622690463165, 660583111698428772, 3943505425938689960, -4898839975680508617,
Sep 15 15:46:01 cdc-replication-longevity-fix-cdc--db-node-9e44e96d-4 scylla[8092]:  [shard 0] storage_service - Node 10.0.1.235 state jump to normal
Sep 15 15:46:01 cdc-replication-longevity-fix-cdc--db-node-9e44e96d-4 scylla[8092]:  [shard 0] storage_service - NORMAL: node is now in normal status
```

Then the node entered a `Waiting for gossip to settle` phase:
```
Sep 15 15:46:01 cdc-replication-longevity-fix-cdc--db-node-9e44e96d-4 scylla[8092]:  [shard 0] init - Waiting for gossip to settle before accepting client requests...
```
the phase would not finish for a long time for some reason; then the errors started happening:
```
Sep 15 15:46:32 cdc-replication-longevity-fix-cdc--db-node-9e44e96d-4 scylla[8092]:  [shard 0] gossip - Gossip not settled after 5 polls.
Sep 15 15:46:32 cdc-replication-longevity-fix-cdc--db-node-9e44e96d-4 scylla[8092]:  [shard 0] tracing - Dropped 1 sessions: open_sessions 1100, cached_records 1100 pending_for_write_records 0, flushing_records 6
Sep 15 15:46:33 cdc-replication-longevity-fix-cdc--db-node-9e44e96d-4 scylla[8092]:  [shard 0] compaction - [Compact ks1.table1 6c28aae0-f76a-11ea-8e24-000000000000] Compacted 32 sstables to [/var/lib/scylla/data/ks1/table1-a9fd8331f76611eab8e9000000000001/md-1514-big-Data.db:level=0, ]. 21MB to 21MB (~96% of origina
Sep 15 15:46:37 cdc-replication-longevity-fix-cdc--db-node-9e44e96d-4 scylla[8092]:  [shard 1] tracing - Dropped 1 sessions: open_sessions 1100, cached_records 1100 pending_for_write_records 0, flushing_records 6
Sep 15 15:46:37 cdc-replication-longevity-fix-cdc--db-node-9e44e96d-4 scylla[8092]:  [shard 1] storage_proxy - Failed to apply mutation from 10.0.2.18#1: seastar::named_semaphore_timed_out (Semaphore timed out: smp_service_group#2 0->1 semaphore)
Sep 15 15:46:37 cdc-replication-longevity-fix-cdc--db-node-9e44e96d-4 scylla[8092]:  [shard 1] storage_proxy - Failed to apply mutation from 10.0.2.18#1: seastar::named_semaphore_timed_out (Semaphore timed out: smp_service_group#2 0->1 semaphore)
Sep 15 15:46:37 cdc-replication-longevity-fix-cdc--db-node-9e44e96d-4 scylla[8092]:  [shard 1] storage_proxy - Failed to apply mutation from 10.0.2.18#1: seastar::named_semaphore_timed_out (Semaphore timed out: smp_service_group#2 0->1 semaphore)
Sep 15 15:46:37 cdc-replication-longevity-fix-cdc--db-node-9e44e96d-4 scylla[8092]:  [shard 1] storage_proxy - Failed to apply mutation from 10.0.2.18#1: seastar::named_semaphore_timed_out (Semaphore timed out: smp_service_group#2 0->1 semaphore)
Sep 15 15:46:37 cdc-replication-longevity-fix-cdc--db-node-9e44e96d-4 scylla[8092]:  [shard 1] storage_proxy - Failed to apply mutation from 10.0.2.18#1: seastar::named_semaphore_timed_out (Semaphore timed out: smp_service_group#2 0->1 semaphore)
```

Another type of error also occurred, `exception during mutation write to 10.0.1.235`, e.g.:
```
Sep 15 15:46:44 cdc-replication-longevity-fix-cdc--db-node-9e44e96d-4 scylla[8092]:  [shard 1] storage_proxy - exception during mutation write to 10.0.1.235: seastar::named_semaphore_timed_out (Semaphore timed out: smp_service_group#2 0->1 semaphore)
```
note that `10.0.1.235` is that node's local IP. It tried to coordinate a write to itself? AFAIK no client was connected to this node, so a hint maybe? I don't know.

Anyway, at 15:48:11 gemini, which was generating the workload, stopped:
```
17:48:20  < t:2020-09-15 15:48:11,749 f:gemini_thread.py l:121  c:sdcm.gemini_thread   p:ERROR > {"L":"INFO","T":"2020-09-15T15:48:11.630Z","M":"Test run completed. Exiting."}
```

soon after we can see that the errors stopped occuring:
```
Sep 15 15:48:21 cdc-replication-longevity-fix-cdc--db-node-9e44e96d-4 scylla[8092]:  [shard 1] storage_proxy - Failed to apply mutation from 10.0.2.18#1: seastar::named_semaphore_timed_out (Semaphore timed out: smp_service_group#2 0->1 semaphore)
Sep 15 15:48:22 cdc-replication-longevity-fix-cdc--db-node-9e44e96d-4 scylla[8092]:  [shard 1] compaction - [Compact ks1.table1_scylla_cdc_log e2348bf0-f76a-11ea-b40a-000000000001] Compacting [/var/lib/scylla/data/ks1/table1_scylla_cdc_log-a9fd8333f76611eab8e9000000000001/md-1771-big-Data.db:level=0, /var/lib/scylla/
Sep 15 15:48:24 cdc-replication-longevity-fix-cdc--db-node-9e44e96d-4 scylla[8092]:  [shard 0] gossip - Gossip not settled after 26 polls.
```

We can see *a lot* of compactions happening
```
Sep 15 15:49:06 cdc-replication-longevity-fix-cdc--db-node-9e44e96d-4 scylla[8092]:  [shard 1] compaction - [Compact ks1.table1_scylla_cdc_log cd9eec80-f76a-11ea-b40a-000000000001] Compacted 32 sstables to [/var/lib/scylla/data/ks1/table1_scylla_cdc_log-a9fd8333f76611eab8e9000000000001/md-5625-big-Data.db:level=0, ].
Sep 15 15:49:06 cdc-replication-longevity-fix-cdc--db-node-9e44e96d-4 scylla[8092]:  [shard 1] compaction - [Compact ks1.table1_scylla_cdc_log de4661d0-f76a-11ea-b40a-000000000001] Compacted 32 sstables to [/var/lib/scylla/data/ks1/table1_scylla_cdc_log-a9fd8333f76611eab8e9000000000001/md-5629-big-Data.db:level=0, ].
Sep 15 15:49:06 cdc-replication-longevity-fix-cdc--db-node-9e44e96d-4 scylla[8092]:  [shard 1] compaction - [Compact ks1.table1_scylla_cdc_log e2348bf0-f76a-11ea-b40a-000000000001] Compacted 32 sstables to [/var/lib/scylla/data/ks1/table1_scylla_cdc_log-a9fd8333f76611eab8e9000000000001/md-5631-big-Data.db:level=0, ].
```

a minute later, after 40 polls, gossip finally settles (no workload was running for the last minute):
```
Sep 15 15:49:47 cdc-replication-longevity-fix-cdc--db-node-9e44e96d-4 scylla[8092]:  [shard 0] gossip - Gossip settled after 40 extra polls; proceeding
```
and Scylla manages to finish booting:
```
Sep 15 15:49:47 cdc-replication-longevity-fix-cdc--db-node-9e44e96d-4 scylla[8092]:  [shard 0] init - Scylla version 666.development-0.20200914.5f541fbdc initialization completed.
```

Then SCT starts a `rebuild_with_repair`, which progresses smoothly for some time
```
Sep 15 15:50:18 cdc-replication-longevity-fix-cdc--db-node-9e44e96d-4 scylla[8092]:  [shard 0] repair - repair id [id=5, uuid=60e2a44c-41e1-46aa-ba9b-5c7974f9dacf] to sync data for keyspace=ks1, status=started
Sep 15 15:50:18 cdc-replication-longevity-fix-cdc--db-node-9e44e96d-4 scylla[8092]:  [shard 0] repair - Repair 1 out of 769 ranges, id=[id=5, uuid=60e2a44c-41e1-46aa-ba9b-5c7974f9dacf], shard=0, keyspace=ks1, table={table1, table1_scylla_cdc_log}, range=(-inf, -9214467662450906539]
Sep 15 15:50:18 cdc-replication-longevity-fix-cdc--db-node-9e44e96d-4 scylla[8092]:  [shard 0] repair - Repair 2 out of 769 ranges, id=[id=5, uuid=60e2a44c-41e1-46aa-ba9b-5c7974f9dacf], shard=0, keyspace=ks1, table={table1, table1_scylla_cdc_log}, range=(-9214467662450906539, -9213873371765511519]
```
but then...
```
Sep 15 15:54:16 cdc-replication-longevity-fix-cdc--db-node-9e44e96d-4 scylla[8092]:  [shard 1] repair - Repair 630 out of 769 ranges, id=[id=7, uuid=574e2c63-eb01-4d13-9256-833ade4ad508], shard=1, keyspace=system_distributed, table={cdc_streams_descriptions, cdc_generation_descriptions, view_build_status}, range=(584
Sep 15 15:54:16 cdc-replication-longevity-fix-cdc--db-node-9e44e96d-4 scylla[8092]:  [shard 1] repair - Repair 631 out of 769 ranges, id=[id=7, uuid=574e2c63-eb01-4d13-9256-833ade4ad508], shard=1, keyspace=system_distributed, table={cdc_streams_descriptions, cdc_generation_descriptions, view_build_status}, range=(587
Sep 15 15:54:16 cdc-replication-longevity-fix-cdc--db-node-9e44e96d-4 scylla[8092]:  [shard 0] storage_proxy - Exception when communicating with 10.0.1.235, to read from ks1.table1_scylla_cdc_log: seastar::named_semaphore_timed_out (Semaphore timed out: _read_concurrency_sem)
Sep 15 15:54:16 cdc-replication-longevity-fix-cdc--db-node-9e44e96d-4 scylla[8092]:  [shard 0] storage_proxy - Exception when communicating with 10.0.1.235, to read from ks1.table1_scylla_cdc_log: seastar::named_semaphore_timed_out (Semaphore timed out: _read_concurrency_sem)
```
note that no workload was running! Just repair.

The rebuild actually finishes successfully, although there were a lot of `named_semaphore_timed_out` errors:
```
Sep 15 15:55:36 cdc-replication-longevity-fix-cdc--db-node-9e44e96d-4 scylla[8092]:  [shard 0] repair - rebuild_with_repair: finished with keyspace=system_traces, source_dc=eu-central, nr_ranges=500
Sep 15 15:55:36 cdc-replication-longevity-fix-cdc--db-node-9e44e96d-4 scylla[8092]:  [shard 0] repair - rebuild_with_repair: finished with keyspaces={ks1, system_auth, system_distributed, system_traces}, source_dc=eu-central
```

but then compactions start happening like mad, and the errors happen again:
```
Sep 15 15:55:36 cdc-replication-longevity-fix-cdc--db-node-9e44e96d-4 scylla[8092]:  [shard 1] compaction - [Compact ks1.table1_scylla_cdc_log e5381280-f76b-11ea-b40a-000000000001] Compacting [/var/lib/scylla/data/ks1/table1_scylla_cdc_log-a9fd8333f76611eab8e9000000000001/md-6919-big-Data.db:level=0, /var/lib/scylla/
Sep 15 15:55:38 cdc-replication-longevity-fix-cdc--db-node-9e44e96d-4 scylla[8092]:  [shard 0] compaction - [Compact ks1.table1_scylla_cdc_log a8110330-f76b-11ea-8e24-000000000000] Compacted 32 sstables to [/var/lib/scylla/data/ks1/table1_scylla_cdc_log-a9fd8333f76611eab8e9000000000001/md-7046-big-Data.db:level=0, ].
Sep 15 15:55:38 cdc-replication-longevity-fix-cdc--db-node-9e44e96d-4 scylla[8092]:  [shard 0] compaction - [Compact system_traces.events e61b4690-f76b-11ea-8e24-000000000000] Compacting [/var/lib/scylla/data/system_traces/events-8826e8e9e16a372887533bc1fc713c25/md-1482-big-Data.db:level=0, /var/lib/scylla/data/syste
Sep 15 15:55:46 cdc-replication-longevity-fix-cdc--db-node-9e44e96d-4 scylla[8092]:  [shard 1] compaction - [Compact system_traces.sessions eacff500-f76b-11ea-b40a-000000000001] Compacting [/var/lib/scylla/data/system_traces/sessions-c5e99f1686773914b17e960613512345/md-593-big-Data.db:level=0, /var/lib/scylla/data/sy
Sep 15 15:55:56 cdc-replication-longevity-fix-cdc--db-node-9e44e96d-4 scylla[8092]:  [shard 1] compaction - [Compact system_traces.events bd1bab90-f76b-11ea-b40a-000000000001] Compacted 32 sstables to [/var/lib/scylla/data/system_traces/events-8826e8e9e16a372887533bc1fc713c25/md-1061-big-Data.db:level=0, ]. 187kB to 
Sep 15 15:56:02 cdc-replication-longevity-fix-cdc--db-node-9e44e96d-4 scylla[8092]:  [shard 0] compaction - [Compact system_traces.events cf8bd2f0-f76b-11ea-8e24-000000000000] Compacted 32 sstables to [/var/lib/scylla/data/system_traces/events-8826e8e9e16a372887533bc1fc713c25/md-1520-big-Data.db:level=0, ]. 180kB to 
Sep 15 15:56:06 cdc-replication-longevity-fix-cdc--db-node-9e44e96d-4 scylla[8092]:  [shard 1] compaction - [Compact ks1.table1_scylla_cdc_log b14630b0-f76b-11ea-b40a-000000000001] Compacted 32 sstables to [/var/lib/scylla/data/ks1/table1_scylla_cdc_log-a9fd8333f76611eab8e9000000000001/md-7005-big-Data.db:level=0, ].
Sep 15 15:56:14 cdc-replication-longevity-fix-cdc--db-node-9e44e96d-4 scylla[8092]:  [shard 1] storage_proxy - Exception when communicating with 10.0.1.235, to read from ks1.table1_scylla_cdc_log: seastar::named_semaphore_timed_out (Semaphore timed out: _read_concurrency_sem)
Sep 15 15:56:14 cdc-replication-longevity-fix-cdc--db-node-9e44e96d-4 scylla[8092]:  [shard 1] storage_proxy - Exception when communicating with 10.0.1.235, to read from ks1.table1_scylla_cdc_log: seastar::named_semaphore_timed_out (Semaphore timed out: _read_concurrency_sem)
Sep 15 15:56:14 cdc-replication-longevity-fix-cdc--db-node-9e44e96d-4 scylla[8092]:  [shard 1] storage_proxy - Exception when communicating with 10.0.1.235, to read from ks1.table1_scylla_cdc_log: seastar::named_semaphore_timed_out (Semaphore timed out: _read_concurrency_sem)
Sep 15 15:56:14 cdc-replication-longevity-fix-cdc--db-node-9e44e96d-4 scylla[8092]:  [shard 1] storage_proxy - Exception when communicating with 10.0.1.235, to read from ks1.table1_scylla_cdc_log: seastar::named_semaphore_timed_out (Semaphore timed out: _read_concurrency_sem)
```

and just look at all those compactions:
```
Sep 15 16:13:23 cdc-replication-longevity-fix-cdc--db-node-9e44e96d-4 scylla[8092]:  [shard 1] compaction - [Compact ks1.table1_scylla_cdc_log 6156c080-f76e-11ea-b40a-000000000001] Compacting [/var/lib/scylla/data/ks1/table1_scylla_cdc_log-a9fd8333f76611eab8e9000000000001/md-4169-big-Data.db:level=0, /var/lib/scylla/
Sep 15 16:13:24 cdc-replication-longevity-fix-cdc--db-node-9e44e96d-4 scylla[8092]:  [shard 0] compaction - [Compact ks1.table1_scylla_cdc_log 61ee1e80-f76e-11ea-8e24-000000000000] Compacting [/var/lib/scylla/data/ks1/table1_scylla_cdc_log-a9fd8333f76611eab8e9000000000001/md-4956-big-Data.db:level=0, /var/lib/scylla/
Sep 15 16:13:32 cdc-replication-longevity-fix-cdc--db-node-9e44e96d-4 scylla[8092]:  [shard 1] compaction - [Compact ks1.table1_scylla_cdc_log 6681b060-f76e-11ea-b40a-000000000001] Compacting [/var/lib/scylla/data/ks1/table1_scylla_cdc_log-a9fd8333f76611eab8e9000000000001/md-1031-big-Data.db:level=0, /var/lib/scylla/
Sep 15 16:13:32 cdc-replication-longevity-fix-cdc--db-node-9e44e96d-4 scylla[8092]:  [shard 1] compaction - [Compact ks1.table1_scylla_cdc_log 66824ca0-f76e-11ea-b40a-000000000001] Compacting [/var/lib/scylla/data/ks1/table1_scylla_cdc_log-a9fd8333f76611eab8e9000000000001/md-1993-big-Data.db:level=0, /var/lib/scylla/
Sep 15 16:13:33 cdc-replication-longevity-fix-cdc--db-node-9e44e96d-4 scylla[8092]:  [shard 0] compaction - [Compact ks1.table1_scylla_cdc_log 5451c650-f76e-11ea-8e24-000000000000] Compacted 32 sstables to [/var/lib/scylla/data/ks1/table1_scylla_cdc_log-a9fd8333f76611eab8e9000000000001/md-7098-big-Data.db:level=0, ].
Sep 15 16:13:36 cdc-replication-longevity-fix-cdc--db-node-9e44e96d-4 scylla[8092]:  [shard 1] compaction - [Compact ks1.table1 437bee00-f76e-11ea-b40a-000000000001] Compacted 9 sstables to [/var/lib/scylla/data/ks1/table1-a9fd8331f76611eab8e9000000000001/md-1549-big-Data.db:level=0, ]. 258MB to 258MB (~99% of origin
Sep 15 16:13:40 cdc-replication-longevity-fix-cdc--db-node-9e44e96d-4 scylla[8092]:  [shard 1] compaction - [Compact ks1.table1_scylla_cdc_log 6156c080-f76e-11ea-b40a-000000000001] Compacted 32 sstables to [/var/lib/scylla/data/ks1/table1_scylla_cdc_log-a9fd8333f76611eab8e9000000000001/md-7097-big-Data.db:level=0, ].
Sep 15 16:13:41 cdc-replication-longevity-fix-cdc--db-node-9e44e96d-4 scylla[8092]:  [shard 0] compaction - [Compact ks1.table1_scylla_cdc_log 6b94d280-f76e-11ea-8e24-000000000000] Compacting [/var/lib/scylla/data/ks1/table1_scylla_cdc_log-a9fd8333f76611eab8e9000000000001/md-1124-big-Data.db:level=0, /var/lib/scylla/
Sep 15 16:13:48 cdc-replication-longevity-fix-cdc--db-node-9e44e96d-4 scylla[8092]:  [shard 0] compaction - [Compact ks1.table1_scylla_cdc_log 61ee1e80-f76e-11ea-8e24-000000000000] Compacted 32 sstables to [/var/lib/scylla/data/ks1/table1_scylla_cdc_log-a9fd8333f76611eab8e9000000000001/md-7100-big-Data.db:level=0, ].
Sep 15 16:13:48 cdc-replication-longevity-fix-cdc--db-node-9e44e96d-4 scylla[8092]:  [shard 1] compaction - [Compact ks1.table1_scylla_cdc_log 6681b060-f76e-11ea-b40a-000000000001] Compacted 32 sstables to [/var/lib/scylla/data/ks1/table1_scylla_cdc_log-a9fd8333f76611eab8e9000000000001/md-7099-big-Data.db:level=0, ].
Sep 15 16:13:52 cdc-replication-longevity-fix-cdc--db-node-9e44e96d-4 scylla[8092]:  [shard 1] compaction - [Compact ks1.table1_scylla_cdc_log 72239820-f76e-11ea-b40a-000000000001] Compacting [/var/lib/scylla/data/ks1/table1_scylla_cdc_log-a9fd8333f76611eab8e9000000000001/md-3633-big-Data.db:level=0, /var/lib/scylla/
Sep 15 16:13:55 cdc-replication-longevity-fix-cdc--db-node-9e44e96d-4 scylla[8092]:  [shard 0] compaction - [Compact ks1.table1_scylla_cdc_log 7448c210-f76e-11ea-8e24-000000000000] Compacting [/var/lib/scylla/data/ks1/table1_scylla_cdc_log-a9fd8333f76611eab8e9000000000001/md-3490-big-Data.db:level=0, /var/lib/scylla/
Sep 15 16:13:55 cdc-replication-longevity-fix-cdc--db-node-9e44e96d-4 scylla[8092]:  [shard 1] compaction - [Compact ks1.table1_scylla_cdc_log 66824ca0-f76e-11ea-b40a-000000000001] Compacted 32 sstables to [/var/lib/scylla/data/ks1/table1_scylla_cdc_log-a9fd8333f76611eab8e9000000000001/md-7101-big-Data.db:level=0, ].
Sep 15 16:13:56 cdc-replication-longevity-fix-cdc--db-node-9e44e96d-4 scylla[8092]:  [shard 1] compaction - [Compact ks1.table1_scylla_cdc_log 74a56100-f76e-11ea-b40a-000000000001] Compacting [/var/lib/scylla/data/ks1/table1_scylla_cdc_log-a9fd8333f76611eab8e9000000000001/md-1999-big-Data.db:level=0, /var/lib/scylla/
Sep 15 16:13:59 cdc-replication-longevity-fix-cdc--db-node-9e44e96d-4 scylla[8092]:  [shard 1] compaction - [Compact ks1.table1_scylla_cdc_log 72239820-f76e-11ea-b40a-000000000001] Compacted 32 sstables to [/var/lib/scylla/data/ks1/table1_scylla_cdc_log-a9fd8333f76611eab8e9000000000001/md-7103-big-Data.db:level=0, ].
Sep 15 16:14:02 cdc-replication-longevity-fix-cdc--db-node-9e44e96d-4 scylla[8092]:  [shard 0] compaction - [Compact ks1.table1_scylla_cdc_log 6b94d280-f76e-11ea-8e24-000000000000] Compacted 32 sstables to [/var/lib/scylla/data/ks1/table1_scylla_cdc_log-a9fd8333f76611eab8e9000000000001/md-7102-big-Data.db:level=0, ].
Sep 15 16:14:07 cdc-replication-longevity-fix-cdc--db-node-9e44e96d-4 scylla[8092]:  [shard 1] compaction - [Compact ks1.table1_scylla_cdc_log 7b493540-f76e-11ea-b40a-000000000001] Compacting [/var/lib/scylla/data/ks1/table1_scylla_cdc_log-a9fd8333f76611eab8e9000000000001/md-4525-big-Data.db:level=0, /var/lib/scylla/
Sep 15 16:14:10 cdc-replication-longevity-fix-cdc--db-node-9e44e96d-4 scylla[8092]:  [shard 0] compaction - [Compact ks1.table1_scylla_cdc_log 7ccf6010-f76e-11ea-8e24-000000000000] Compacting [/var/lib/scylla/data/ks1/table1_scylla_cdc_log-a9fd8333f76611eab8e9000000000001/md-1578-big-Data.db:level=0, /var/lib/scylla/
```

This is madness.

BTW. The test failed due to a completely unrelated reason.
Anyway, I'm attaching the node's full logs:
[dump.log](https://github.com/scylladb/scylla/files/5226592/dump.log)

**Comment by kbr-** [comment] 2020-09-15 17:14
Also, all the other nodes didn't report any errors. Just the bootstrapping one.

**Comment by kbr-** [comment] 2020-09-15 17:21
May be caused by the same reason as
https://github.com/scylladb/scylla/issues/7104
https://github.com/scylladb/scylla/issues/6645

It is interesting that the bootstrap-repair phase actually finished, and only then the errors started occurring.
There were a lot of compactions happening, which might have caused the node to overload.

**Comment by raphaelsc** [comment] 2020-09-15 20:36
compaction goes mad because lots of small sstables are generated by repair (one per vtable), we even temporarily increase the min compaction threshold when bootstrapping to reduce the aggressiveness. we need off-strategy on repair (https://github.com/scylladb/scylla/issues/5226) to improve this further, as there's potentially a lot of disjoint SSTables, so partitioned_sstable_set can be used to reduce the impact on resource usage of those compaction jobs.

**Comment by slivne** [comment] 2020-09-16 06:10
We have seen this, client not using shard aware driver was the source

eliran fixed an issue we discovered because of that  hinted handoff was not really segregated  from regular workload in cross smp calls  (https://github.com/scylladb/scylla/issues/7177)

@kbr- can you double check both the client sending traffic and replicator are using shard aware drivers.

**Comment by kbr-** [comment] 2020-09-16 11:03
@slivne the test was executed on a version of Scylla that included Eliran's change, but it doesn't matter -- the timeouts happened on `smp_service_group#2`, which turns out to be the write group, no the hints group.

**Comment by kbr-** [comment] 2020-09-16 11:23
@slivne I just confirmed that the gemini version used cannot into shards

**Comment by kbr-** [comment] 2020-09-16 11:52
@piodul has checked that:
1. cassandra-stress with our driver correctly picks shards
2. scylla-bench picks shards incorrectly, which results in cross-shard ops
3. gemini picks shards incorrectly, which results in cross-shard ops

Gemini does not pick token-aware policy when configuring the driver (seems like a bug), but even when we modified it to do so, gocql still wrote to the wrong shard

**Comment by kbr-** [comment] 2020-09-16 12:03
actually, locally compiled newest version of scylla-bench picks shards correctly

**Comment by kbr-** [comment] 2020-09-16 16:58
I finally know what's happening... gemini does send the writes to the right shard, but it also sends other queries -- SELECTs from system_traces keyspace -- almost as often as the writes themselves, in parallel, and these queries use the control connection, which is sometimes right, sometimes wrong for the given partition key.

There are two things to be done:
1. disable these tracing queries in Gemini if requested (now it always enables them for some reason)
2. improve gocql driver to have a control connection per each shard? So that it can send those tracing queries to the right shards

**Comment by slivne** [comment] 2020-09-17 12:03
I know gemini enables tracing so we can check the system_traces when there are issues

@penberg any recollection why what we enable tracing for ?

I have no idea why the gocql or gemini query the system_traces so much 

@penberg the same

if its gemini querying it sound like a bug in gocql that sends queries to system_traces on control connection instead of regular conenctions 

if its gemini those queries should be prepared and then will be sent to the right shard - unless they are scans.

**Comment by kbr-** [comment] 2020-09-17 14:07
> @penberg any recollection why we enable tracing and for what - we added it at some point ?

@slivne A bug in gemini :D
https://github.com/scylladb/gemini/issues/247

**Comment by kbr-** [comment] 2020-09-17 14:25
> if its gemini querying it sound like a bug in gocql that sends queries to system_traces on control connection instead of regular conenctions

Yes, it's a problem with gocql. Seems like those queries were simply overlooked when shard-awareness was implemented in gocql.
I made an issue:
https://github.com/scylladb/gocql/issues/54

**Comment by slivne** [comment] 2020-09-20 19:14
@kbr- nice :)

**Comment by slivne** [comment] 2020-09-24 09:31
Gemin patch was merged - GoCQL change is still in review and discussion.

**Comment by kbr-** [comment] 2020-09-28 09:23
@slivne I only created an issue, did someone propose a patch?
In any case, in the test discussed in the issue we don't use tracing -- it was enabled due to the gemini bug (https://github.com/scylladb/gemini/issues/247) which is already fixed in the latest release, so the test doesn't make any tracing queries now, hence it doesn't really matter whether gocql supports shard awareness for tracing (for this test).

**Comment by aleksbykov** [comment] 2020-12-23 08:10
Seems that issue reproduced duringh the job: https://jenkins.scylladb.com/job/scylla-4.1/job/longevity/job/longevity-cdc-100gb-4h/83/ 
for scylla version: 4.1.10 (ami-06c6ece676d785bd2) 4.1.10-0.20201221.2a6a072857

all db logs: https://cloudius-jenkins-test.s3.amazonaws.com/26435a50-38e1-4c2a-9ecd-a8eccc2cbc86/20201223_022445/db-cluster-26435a50.zip

On node2 the nemesis CorruptThenRepair was started. This nemesis stop scylla, remove several sstables, start scylla and run nodetool repair.
During repair a lot of messages:
```
2020-12-22T23:43:01+00:00  longevity-cdc-100gb-4h-4-1-db-node-26435a50-2 !ERR     | scylla: [shard 1] storage_proxy - exception during mutation write to 10.0.71.217: seastar::named_semaphore_timed_out (Semaphore timed out: smp_service_group#2 12->1 semaphore)
2020-12-22T23:43:01+00:00  longevity-cdc-100gb-4h-4-1-db-node-26435a50-2 !ERR     | scylla: [shard 1] storage_proxy - exception during mutation write to 10.0.71.217: seastar::named_semaphore_timed_out (Semaphore timed out: smp_service_group#2 12->1 semaphore)
2020-12-22T23:43:01+00:00  longevity-cdc-100gb-4h-4-1-db-node-26435a50-2 !ERR     | scylla: [shard 2] storage_proxy - exception during mutation write to 10.0.71.217: seastar::named_semaphore_timed_out (Semaphore timed out: smp_service_group#2 12->2 semaphore)
2020-12-22T23:43:01+00:00  longevity-cdc-100gb-4h-4-1-db-node-26435a50-2 !ERR     | scylla: [shard 2] storage_proxy - exception during mutation write to 10.0.71.217: seastar::named_semaphore_timed_out (Semaphore timed out: smp_service_group#2 12->2 semaphore)
2020-12-22T23:43:01+00:00  longevity-cdc-100gb-4h-4-1-db-node-26435a50-2 !ERR     | scylla: [shard 9] storage_proxy - exception during mutation write to 10.0.71.217: seastar::named_semaphore_timed_out (Semaphore timed out: smp_service_group#2 12->9 semaphore)
2020-12-22T23:43:01+00:00  longevity-cdc-100gb-4h-4-1-db-node-26435a50-2 !ERR     | scylla: [shard 9] storage_proxy - exception during mutation write to 10.0.71.217: seastar::named_semaphore_timed_out (Semaphore timed out: smp_service_group#2 12->9 semaphore)
```
This cause that node stop to answer on cql requests and trigger next client issue:
```
< t:2020-12-22 23:55:52,580 f:remote.py       l:739  c:sdcm.remote          p:INFO  > RemoteCmdRunner [centos@10.0.151.169]: com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during UNLOGGED_BATCH write query at consistency QUORUM (2 replica were required but only 0 acknowledged the write)
< t:2020-12-22 23:55:52,580 f:remote.py       l:739  c:sdcm.remote          p:INFO  > RemoteCmdRunner [centos@10.0.151.169]: com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during UNLOGGED_BATCH write query at consistency QUORUM (2 replica were required but only 0 acknowledged the write)
< t:2020-12-22 23:55:52,581 f:remote.py       l:739  c:sdcm.remote          p:INFO  > RemoteCmdRunner [centos@10.0.151.169]: com.datastax.driver.core.
```
```
2020-12-22 23:55:49.818: (ClusterHealthValidatorEvent Severity.ERROR): type=error name=NodeSchemaVersion node=longevity-cdc-100gb-4h-4-1-db-node-26435a50-2 error=Validate schema version failed. Error: Encountered a bad command exit code!

Command: 'cqlsh --no-color   --request-timeout=120 --connect-timeout=60  -e "select peer, data_center, host_id, rack, release_version, rpc_address, schema_version, supported_features from system.peers" 10.0.71.217 9042'

Exit code: 1

Stdout:



Stderr:

Connection error: ('Unable to connect to any servers', {'10.0.71.217': ReadTimeout('Error from server: code=1200 [Coordinator node timed out waiting for replica nodes\' responses] message="Operation timed out for system.local - received only 0 responses from 1 CL=ONE." info={\'received_responses\': 0, \'required_responses\': 1, \'consistency\': \'ONE\'}',)})
```

also later other nodes detected that schema versions is differ:
```
2020-12-23 00:11:43.070: (ClusterHealthValidatorEvent Severity.ERROR): type=error name=GossipNodeSchemaVersion node=longevity-cdc-100gb-4h-4-1-db-node-26435a50-3 error=Schema version is not same on all nodes in gossip info: 10.0.71.217: cf9122b9-db38-3a71-823b-699365244fe7
10.0.140.113: 567aefc6-4162-30f3-89d2-ef5a561ac7fd
10.0.35.100: 567aefc6-4162-30f3-89d2-ef5a561ac7fd
10.0.133.82: 567aefc6-4162-30f3-89d2-ef5a561ac7fd
10.0.80.74: 567aefc6-4162-30f3-89d2-ef5a561ac7fd
10.0.187.73: 567aefc6-4162-30f3-89d2-ef5a561ac7fd
```

Job is running with c-s commands
```
cassandra-stress user no-warmup profile=/tmp/cdc_profile.yaml ops'(insert=2,read1=1,update_number=1,update_name=1,delete1=1)' cl=QUORUM duration=240m -port jmx=6868 -mode cql3 native -rate threads=100
cassandra-stress user no-warmup profile=/tmp/cdc_profile_preimage.yaml ops'(insert=2,read1=1,update_number=1,update_name=1,delete1=1)' cl=QUORUM duration=240m -port jmx=6868 -mode cql3 native -rate threads=100
cassandra-stress user no-warmup profile=/tmp/cdc_profile_postimage.yaml ops'(insert=2,read1=1,update_number=1,update_name=1,delete1=1)' cl=QUORUM duration=240m -port jmx=6868 -mode cql3 native -rate threads=100
cassandra-stress user no-warmup profile=/tmp/cdc_profile_preimage_postimage.yaml  ops'(insert=2,read1=1,update_number=1,update_name=1,delete1=1)' cl=QUORUM duration=240m
```

**Comment by slivne** [comment] 2021-01-19 21:07
@aleksbykov - gemini was fixed - how do you update gemini in your images ?
-  I am closing this issue - if this happens again please report exact scylla version and gemini used so we can verify that its using the fixed version

**Closed by slivne** 2021-01-19 21:07 UTC
Labels: CDC, bug, repair-based-operations
