### ISSUE TITLE
Some nodes repeatedly perform unnecessary compactions ad infinitum

### ISSUE THREAD

**Issue by erozycki** [scylladb/scylla#6092] opened 2020-03-27 23:23 UTC
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [x] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash): 3.2.3-0.20200304.48253eb1832
Cluster size: 5x r5.large (500 GB EBS per node, ~65% disk usage)
OS (RHEL/CentOS/Ubuntu/AWS AMI): Ubuntu 18.04.4 LTS (GNU/Linux 4.15.0-1048-aws x86_64)

Sometimes, on one or more nodes, a shard gets stuck in a state where it continuously recompacts the same data over and over again. Looking at the logs, the compactions appear to be successful (so it's not that Scylla is repeatedly retrying a failed compaction). I am pretty confident that this compaction is unnecessary, because most nodes/shards are normally not in this bad state, and because there is no increase in write volume that would justify this behavior.

This state can persist for many days, with the affected shards pegged at 100% CPU usage. The only way I am able to resolve this is by restarting Scylla on the affected nodes. After restarting, Scylla is no longer in this bad state and behaves normally. I think I first noticed this issue around 9 months ago, and have noticed it again occasionally.

I am using TWCS with a 2-day compaction window and a 9.8 day TTL. I do 50-400k small random (uniformly at random) writes per second.

Graph of CPU usage over time (broken down by shard) for one affected node:

![image](https://user-images.githubusercontent.com/16142788/77806290-8bde2c80-7041-11ea-81b7-817f07b3188d.png)

Graph of CPU usage over time (broken down by shard) for the other affected node:

![image](https://user-images.githubusercontent.com/16142788/77806335-9ef0fc80-7041-11ea-9451-3e60c59e55e3.png)

Graph of CPU usage over time (broken down by shard) for an unaffected node:

![image](https://user-images.githubusercontent.com/16142788/77806402-d8296c80-7041-11ea-9803-468546e55759.png)

**Comment by dorlaor** [comment] 2020-03-27 23:46
Can you please share the compaction logs?
@raphaelsc did we consider to add a 'compaction reason' or some other insight into the compaction backlog so users will have a better idea what's going on?

**Comment by erozycki** [comment] 2020-03-28 00:05
Attached it. This was generated with `nodetool setlogginglevel compaction debug`. The big unnecessary compactions are on shard 1 and take around 40m. I believe the following is an example (though it is somewhat difficult for me to accurately differentiate between necessary and unnecessary compactions, so maybe this particular compaction was actually justified).

```
Mar 27 23:27:07 ip-172-31-44-53 scylla[24984]:  [shard 1] compaction - Compacted 2 sstables to [/var/lib/scylla/data/nats/audio_hashes_cg-e3dbd8d0a50b11e98442000000000001/mc-418867-big-Data.db:level=0, ]. 14700033404 bytes to 14514813008 (~98% of original) in 2534415ms = 5.46MB/s. ~271709184 total partitions merged to 263045863.
```

[compaction_log.txt](https://github.com/scylladb/scylla/files/4396366/compaction_log.txt)

**Comment by bhalevy** [comment] 2020-04-07 11:25
@raphaelsc please look into this

**Comment by chued** [comment] 2020-05-12 15:43
@erozycki What's the setting for tombstone_compaction_interval? The default is 1 day, so with a 2 day compaction window, the memtable flushes to disk will fall within this 1 day window before they are merged into one sstable in the second twcs window.

https://docs.scylladb.com/troubleshooting/pointless_compactions/

**Comment by erozycki** [comment] 2020-05-12 17:04
@chued I have not explicitly set tombstone_compaction_interval, so I believe it should default to 1 day (per https://docs.scylladb.com/getting-started/compaction/).

**Comment by raphaelsc** [comment] 2020-05-15 21:04
This version already has data segregation feature enabled. TWCS was designed with an assumption that windows other than current window will not receive any data after it's closed, but that's not true anymore after data segregation. I'll investigate this further before proposing a proper solution. Something I have in mind is to decrease this write amplification with size-tiered, but we need to first know all the details of this problem.

**Comment by raphaelsc** [comment] 2020-05-15 21:04
@erozycki do you mind sharing the full schema? thanks.

**Comment by erozycki** [comment] 2020-05-15 21:14
@raphaelsc 

```
CREATE TABLE nats.audio_hashes_cg (
    f blob PRIMARY KEY,
    m set<frozen<tuple<blob, blob>>>
) WITH bloom_filter_fp_chance = 0.15
    AND caching = {'keys': 'ALL', 'rows_per_partition': 'ALL'}
    AND comment = ''
    AND compaction = {'class': 'TimeWindowCompactionStrategy', 'compaction_window_size': '2', 'compaction_window_unit': 'DAYS', 'max_threshold': '32', 'min_threshold': '4', 'tombstone_threshold': '0.6'}
    AND compression = {'chunk_length_in_kb': '8', 'compression_level': '1', 'sstable_compression': 'org.apache.cassandra.io.compress.ZstdCompressor'}
    AND crc_check_chance = 1.0
    AND dclocal_read_repair_chance = 0.0
    AND default_time_to_live = 676800
    AND gc_grace_seconds = 0
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair_chance = 0.0
    AND speculative_retry = 'NONE';
```

**Comment by raphaelsc** [comment] 2020-05-18 17:02
@glommer "This state can persist for many days, with the affected shards pegged at 100% CPU usage. The only way I am able to resolve this is by restarting Scylla on the affected nodes. After restarting, Scylla is no longer in this bad state and behaves normally." this looks like the backlog issue I am fixing (https://github.com/scylladb/scylla/issues/6054). Fully expired SSTables are not removed from the tracker, meaning those are leaked and backlog eventually reach the sky. As a result, controller goes crazy.

**Comment by glommer** [comment] 2020-05-19 16:11
I can't see how a bug in the controller can cause compactions to happen.
It can cause them to lag and go slowly, but it shouldn't trigger compactions that would not otherwise happen

**Comment by raphaelsc** [comment] 2020-05-19 17:15
Looks like tombstone compaction is *one of the sources* of many undesired compactions here, look:

Mar 27 04:17:10 ip-172-31-44-53 scylla[24984]:  [shard 0] compaction - Checking if candidate of generation 402158 and max_deletion_time 1585954876 is expired, gc_before is   1585282630

Here we can see that sstable with generation 402168 is not fully expired, max_deletion_time > gc_before

Mar 27 04:17:10 ip-172-31-44-53 scylla[24984]:  [shard 0] compaction - Compacting [/var/lib/scylla/data/nats/audio_hashes_cg-e3dbd8d0a50b11e98442000000000001/mc-402076-big-Data.db:level=0, /var/lib/scylla/data/nats/audio_hashes_cg-e3dbd8d0a50b11e98442000000000001/mc-402116-big-Data.db:level=0, /var/lib/scylla/data/nats/audio_hashes_cg-e3dbd8d0a50b11e98442000000000001/mc-402200-big-Data.db:level=0, /var/lib/scylla/data/nats/audio_hashes_cg-e3dbd8d0a50b11e98442000000000001/mc-402158-big-Data.db:level=0, ]

And here it's included even though it's not fully expired.

**Comment by raphaelsc** [comment] 2020-05-19 17:20
@erozycki I'd like to understand if you're doing anything that is causing out of order writes. Do you rely on USING TIMESTAMP for any of your writes? What about read repair?

**Comment by erozycki** [comment] 2020-05-19 19:39
@raphaelsc 

I update the table in the following two ways:
1. batch inserts: I execute unlogged batches of ~100 statements, where each statement has the form `UPDATE audio_hashes_cg SET m = m + ? WHERE f = ?;`
2. batch deletes: I execute unlogged batches of ~100 statements, where each statement has the form `UPDATE audio_hashes_cg SET m = m - ? WHERE f = ?;`
I probably delete about 35% of the values I insert. Due to race conditions I will sometimes delete a value before I insert it, and then insert it a bit later. Due to retries, I will sometimes insert the same value more than once.

I use RF=1 and avoid any form of read repair. I don't use USING TIMESTAMP. I can't think of anything else that might cause out-of-order writes.

The only other "unusual" thing about my setup that I can think of is that I have `enable_cache: false`.

**Comment by raphaelsc** [comment] 2020-06-02 16:23
@erozycki Reading the logs, it became clear that many of those unexpected compactions are related to tombstone compaction. From the logs, it looks like you aren't having issues with purge of fully expired SSTables, so I'd suggest disabling tombstone compaction by removing all of its properties from the compaction properties.

Something like this will help:
`ALTER TABLE nats.audio_hashes_cg with compaction = {'class': 'TimeWindowCompactionStrategy', 'compaction_window_size': '2', 'compaction_window_unit': 'DAYS', 'max_threshold': '32', 'min_threshold': '4'}`

**Comment by erozycki** [comment] 2020-06-02 18:10
@raphaelsc 

Thanks for looking into it. Originally, I configured my table with `tombstone_threshold: 1.0`, since it seemed pointless to compact tombstones for an sstable that was just going to fully expire soon after. However, I ran into an issue where old TWCS sstables were retained far, far longer than expected, causing my nodes to run out of disk space. (I posted that issue here: https://groups.google.com/forum/#!searchin/scylladb-users/erozycki%7Csort:date/scylladb-users/ZPCyzPClFK8/A3y1R5RNCAAJ). I resolved that issue by setting `tombstone_threshold < 1`.

So I am hesitant to disable tombstone compaction, unless I no longer need to worry about the issue I had previously. What do you think?

**Comment by erozycki** [comment] 2020-06-02 18:14
I am now running the latest release, 4.0.1.

**Comment by glommer** [comment] 2020-06-02 18:22
Note that 4.1 , when is out, will include working TWCS major compaction. This means that if you ever run into the problem of things not expiring correctly again, you'll be able to call a major compaction and fix it.

**Comment by erozycki** [comment] 2020-06-02 18:59
@glommer Good to know. This would be a manual operation that I could execute in response to seeing old sstables that haven't expired correctly, right?

**Comment by raphaelsc** [comment] 2020-06-02 22:03
> @glommer Good to know. This would be a manual operation that I could execute in response to seeing old sstables that haven't expired correctly, right?

Correct. TWCS' major compaction will be able to purge everything there's to be purged (a.k.a. expired data).

**Comment by raphaelsc** [comment] 2020-07-20 07:59
Found out this issue was about tombstone compaction continuously trying to purge data with no success, as there's overlapping among SSTables which prevent their data from being purged. This happened because TWCS is not segregating data by age on older versions, but now it's available in the recent versions, and TWCS is also available as a last resort. So closing this issue...

**Closed by raphaelsc** 2020-07-20 07:59 UTC
Labels: TWCS, User Request, compaction
