### ISSUE TITLE
ALL permissions

### ISSUE THREAD

**Issue by tarzanek** [scylladb/scylla#5043] opened 2019-09-16 12:21 UTC
Reporting a request for enhancement (and cassandra compatibility).

Cassandra compatibility wise scylla should support:

cassandra@cqlsh> GRANT ALL PERMISSIONS ON ALL FUNCTIONS TO administrator;
SyntaxException: line 1:25 no viable alternative at input 'ALL'

and same here:
GRANT ALL PERMISSIONS ON ALL ROLES TO administrator
GRANT ALL PERMISSIONS ON ALL KEYSPACES TO administrator
GRANT ALL PERMISSIONS ON ALL FUNCTIONS TO administrator

all fail with above error.
Is there an alternative to those commands?
Could scylla support them?

This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [X] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash):
Cluster size:
OS (RHEL/CentOS/Ubuntu/AWS AMI):

*Hardware details (for performance issues)*          Delete if unneeded
Platform (physical/VM/cloud instance type/docker):
Hardware: sockets= cores= hyperthreading= memory=
Disks: (SSD/HDD, count)

**Comment by nyh** [comment] 2021-06-14 09:19
For
```
GRANT ALL PERMISSIONS ON ALL FUNCTIONS TO administrator;
```
we get an error (but not a very useful one... See also #1703) because we apparently don't support "FUNCTIONS" in GRANT.

The other examples (ALL ROLES, ALL KEYSPACES) do seem to work.

**Comment by nyh** [comment] 2021-06-14 09:20
I'm closing as a duplicate of  #4276, which is on just the FUNCTIONS part.

**Closed by nyh** 2021-06-14 09:20 UTC
Labels: cassandra 3.x compatibility, enhancement, n00b
