### ISSUE TITLE
DateTiredCompaction for remove expired SSTable shows loop compaction

### ISSUE THREAD

**Issue by ban4785** [scylladb/scylla#2260] opened 2017-04-06 05:55 UTC
*Installation details*
Scylla version (or git commit hash): 1.6.1
Cluster size: 3 
OS (RHEL/CentOS/Ubuntu/AWS AMI): CentOS

Platform (physical/VM/cloud instance type/docker): physical
Hardware: sockets= cores= hyperthreading= memory= smp 8 m 20G
Disks: (SSD/HDD, count) SSD

i inserted data(about 70G size, time series data, non update&delete) using **TTL 3600 with DateTiredCompaction,**
one day after, expired data was remain.
1. i command `nodetool compact foms` but some expired sstables were not deleted. 
sstable size 72G -> 32G, i can't understand why full expired sstables not removed.
all sstables were fully expired sstables.

2. i command `nodetool compact foms` with some loading(about 20000 TPS).
node which i command compaction was not deleted all expired sstables.
**but other nodes removed all expired sstables automatically with loop compaction.**

below log shows ScyllaDB doing loop compaction.
[messages_compact.txt](https://github.com/scylladb/scylla/files/901594/messages_compact.txt)

but graphite show only one compaction operating...
![compaction](https://cloud.githubusercontent.com/assets/20348151/24739833/f79f80e8-1ad8-11e7-8fc1-0a817e8c790b.png)

test schema info
 CREATE TABLE foms.data (
 part_key text,
 param_index int,
 ts timestamp,
 lt text,
 product frozen,
 spec frozen,
 st text,
 vl text,
 PRIMARY KEY ((part_key, param_index), ts)
 ) WITH CLUSTERING ORDER BY (ts DESC)
 AND bloom_filter_fp_chance = 0.01
 AND caching = '{"keys":"ALL","rows_per_partition":"ALL"}'
 AND comment = ''
 **AND compaction = {'max_window_size_seconds': '864000', 'max_sstable_age_days': '10', 'base_time_seconds': '3600', 'class': 'DateTieredCompactionStrategy'}**
 AND compression = {'sstable_compression': 'org.apache.cassandra.io.compress.LZ4Compressor'}
 AND dclocal_read_repair_chance = 1.0
 AND default_time_to_live = 3600
 AND gc_grace_seconds = 0
 AND max_index_interval = 2048
 AND memtable_flush_period_in_ms = 0
 AND min_index_interval = 1
 AND read_repair_chance = 0.0
 AND speculative_retry = '99.0PERCENTILE';

**Comment by ban4785** [comment] 2017-04-06 05:56
https://github.com/scylladb/scylla/issues/2253

**Comment by raphaelsc** [comment] 2017-04-07 02:55
@ban4785 I was able to reproduce it. I still need to investigate. @slivne please assign it to me

**Comment by raphaelsc** [comment] 2017-04-09 18:07
This issue happens due to DTCS impl and also external factors. DTCS always look for at least one fully expired sstable to compact.

1) So let's say DTCS finds a sstable containing expired cells only. This sstable is compacted and a new one containing tombstone cells is created.
2) This new sstable with tombstone cells is also considered expired. So it's again compacted. 

The loop compaction happens because the compacted sstable which wasn't deleted yet prevents tombstone cells from being purged, so we will always have fully expired sstable at the end. Like C*, I think we should introduce an interval between checks for fully expired sstables. So we'll give Scylla time to delete compacted sstables.

**Comment by slivne** [comment] 2017-04-09 19:44
1. I am missing something If a table is fully expired and it does not need
to help "cover" any live data in other sstables - why aren't we dropping it
completely, why do we create tombstones. ?

2. Having an sstable full of only tombstones is something not that common
... can't we do an additional check at the end in such a case and see if we
can remove the new created sstable that contains only tombstones.

**Comment by raphaelsc** [comment] 2017-04-09 19:57
On Sun, Apr 9, 2017 at 4:44 PM, Shlomi Livne <notifications@github.com>
wrote:

> 1. I am missing something If a table is fully expired and it does not need
> to help "cover" any live data in other sstables - why aren't we dropping it
> completely, why do we create tombstones. ?
>

That's exactly my thought. So I sent patch 'compaction: do not write
expired cell as dead cell if it can be purged right away'. The lack of it
means we need two compactions to purge data. One to convert expired sstable
into sstable of tombstones, and another to purge tombstones. Assuming they
don't cover old data.


>
> 2. Having an sstable full of only tombstones is something not that common
> ... can't we do an additional check at the end in such a case and see if we
> can remove the new created sstable that contains only tombstones.
>

One option is the above, which is about purging expired cell which
satisfies gc before and max purgeable timestamp. Another option is to
simply ignore fully expired sstable, which also satisfies the conditions,
so the fully expired sstable will be simply be deleted at the end of
compaction. The latter one is dangerous, so we would need to implement it
very carefully.


And related to this issue specifically, we also need to introduce an
interval for fully expired sstable check, because we're not giving Scylla a
chance to get rid of 'compacted but not deleted yet' sstables, and those
are taken into account to calculate max purgeable timestamp. Consequently,
we would end up in a compaction loop because no data would be purged.
Cassandra introduced this interval in the latest versions, but because the
check for fully expired sstables is expensive.

**Comment by tzach** [comment] 2017-04-13 06:57
> That's exactly my thought. So I sent patch 'compaction: do not write
> expired cell as dead cell if it can be purged right away'. The lack of it
> means we need two compactions to purge data. One to convert expired sstable
> into sstable of tombstones, and another to purge tombstones. Assuming they
> don't cover old data.

Is C* doing the same?

**Comment by raphaelsc** [comment] 2017-04-28 22:03
@tzach: Apparently yes. Issued major compaction on a column family with one fully expired sstable, which results in an empty column family. I'll double check it. BTW, the patch mentioned is already merged.

**Closed** 2017-04-30 16:35 UTC
Labels: bug, User Request
