### ISSUE TITLE
idx_token of global secondary indexes is sorted incorrectly

### ISSUE THREAD

**Issue by avelanarius** [scylladb/scylla#7443] opened 2020-10-15 16:22 UTC
The first column of clustering key in global secondary indexes is a token of partition key (of base table). `idx_token` is of type `bytes`. However tokens on ring are represented as **signed** `int64_t`. It is a problem, because rows are sorted by `idx_token` - bytes, but the ordering of bytes is **unsigned** (-1 is larger than 1 when doing unsigned comparisons):

```
cqlsh> SELECT pk, ck, ck2, token(pk) FROM ks.t;

 pk | ck | ck2 | system.token(pk)
----+----+-----+----------------------
  1 |  1 |   1 | -4069959284402364209
  1 |  1 |   5 | -4069959284402364209
  2 |  1 |   3 | -3248873570005575792
  2 |  1 |   8 | -3248873570005575792
  4 |  1 |   5 | -2729420104000364805
  3 |  1 |   5 |  9010454139840013625

cqlsh> SELECT pk, ck, ck2, token(pk) FROM ks.t WHERE ck = 1;

 pk | ck | ck2 | system.token(pk)
----+----+-----+----------------------
  3 |  1 |   5 |  9010454139840013625
  1 |  1 |   1 | -4069959284402364209
  1 |  1 |   5 | -4069959284402364209
  2 |  1 |   3 | -3248873570005575792
  2 |  1 |   8 | -3248873570005575792
  4 |  1 |   5 | -2729420104000364805

cqlsh> select * from ks.t_ck_idx_index;

 ck | idx_token          | pk | ck2
----+--------------------+----+-----
  1 | 0x7d0b904cfe1ca539 |  3 |   5
  1 | 0xc78499982ae4e0cf |  1 |   1
  1 | 0xc78499982ae4e0cf |  1 |   5
  1 | 0xd2e9aeb38ba99790 |  2 |   3
  1 | 0xd2e9aeb38ba99790 |  2 |   8
  1 | 0xda1f26e0623f9efb |  4 |   5
```

When doing `SELECT` on the base table without any filtering (it is not using secondary index in that case), `token(pk)` is correctly "sorted". However looking at `SELECT` with filtering (using secondary index), the order is not correct (it is ordered according to unsigned comparison). The same fact is true for the index view.

**Comment by haaawk** [comment] 2020-10-15 16:41
One solution here would be to change the type of idx_token column to int but that would not be backwards compatible. Another would be to translate tokens to bytes for this column with a bias that makes every value positive.

**Comment by slivne** [comment] 2020-10-18 08:35
@psarna / @nyh please comment

**Comment by nyh** [comment] 2020-10-26 14:16
The `idx_token` column was added (by @psarna) in commit 4a9bf7ed5bf8fc00c2b19b4366d8cbc1bdec3c07 to fix #3423. I don't remember why bytes were chosen (maybe @psarna remembers), but at time, we still had multiple token implementations - as integers, byte arrays, I guess we got confused. Without having tests that compare ourselves to Cassandra (unfortunately), it's hard to know even if Scylla's token sorting behavior didn't changed, but I assume it didn't (Avi was very careful about those changes).

Before fixing this issue we should write a regression test that checks the order (we should have added such a test as part of #3423).

The question also becomes how to fix this.

@psarna's introduction of "computed columns partly made a **partial** solution very easy, I think: Today, we add a computed column with `token_column_computation` as the computation. We just need a new computation class, say `new_token_column_computation`, and in new tables use that. Old tables will continue to work with the old computation, and new tables will work with the new computation.

The reason why I called this a **partial** solution is that it will mean that old tables will continue to return the "wrong" sort order. I don't think there is any good way to fix that, unfortunately. We can easily "upgrade" an index view table by changing its schema from a bytes `idx_token` to integer, and automatically all the existing data will be read correctly as integers. However, such a "fix" would be wrong: after it, the sort order in the data itself will be wrong! The clustering rows on disk will be in the wrong order, and various assumptions in the code will break, and we can't really fix this data without some sort of rewrite of the entire data.

**Comment by psarna** [comment] 2020-10-26 14:28
As we, three Piotrs, discussed once, perhaps the most sensible solution is what @avelanarius suggested - to introduce the right order for *newly created* views and maintain the old, wrong order for old views. Then, users can trivially fix their order just by recreating the view, and we don't pay the price of trying to rewrite user's views ourselves.
That still involves introducing a cluster feature, but at least we won't be touching existing views, which makes the change quite safe.

**Comment by nyh** [comment] 2020-10-27 07:32
@psarna maybe this is finally a compelling case where we need a test framework like Alternator's: Something in the repository (not dtest), which allows us to run the same test against both Cassandra and Scylla. As much as it's "a shame" that the sort order change because of a index, it only really matters if Cassandra does not have the same problem. I think I'll prepare such a test framework (based on Alternator's). Should be very easy.

**Comment by avikivity** [comment] 2020-10-27 11:41
> As we, three Piotrs, discussed once, perhaps the most sensible solution is what @avelanarius suggested - to introduce the right order for _newly created_ views and maintain the old, wrong order for old views. Then, users can trivially fix their order just by recreating the view, and we don't pay the price of trying to rewrite user's views ourselves.
> That still involves introducing a cluster feature, but at least we won't be touching existing views, which makes the change quite safe.

Agree.

**Comment by nyh** [comment] 2020-10-28 17:22
Here is a pytest which reproduces this bug. It passes on Cassandra, fails on Scylla:

```python
def test_partition_order_with_si(cql, test_keyspace):
    schema = 'pk int, x int, PRIMARY KEY ((pk))'
    with new_test_table(cql, test_keyspace, schema) as table:
        # Insert 20 partitions, all of them with x=1 so that filtering by x=1
        # will yield the same 20 partitions:
        N = 20
        stmt = cql.prepare('INSERT INTO '+table+' (pk, x) VALUES (?, ?)')
        for i in range(N):
            cql.execute(stmt, [i, 1])
        # SELECT all the rows, and verify they are returned in increasing
        # partition token order (note that the token is a *signed* number):
        tokens = [row.system_token_pk for row in cql.execute('SELECT token(pk) FROM '+table)]
        assert len(tokens) == N
        assert sorted(tokens) == tokens
        # Now select all the partitions with filtering of x=1. Since all
        # rows have x=1, this shouldn't change the list of matching rows, and
        # also shouldn't check their order:
        tokens1 = [row.system_token_pk for row in cql.execute('SELECT token(pk) FROM '+table+' WHERE x=1 ALLOW FILTERING')]
        assert tokens1 == tokens
        # Now add an index on x, which allows implementing the "x=1"
        # restriction differently. With the index, "ALLOW FILTERING" is
        # no longer necessary. But the order of the results should
        # still not change:
        cql.execute('CREATE INDEX ON '+table+'(x)')
        # "CREATE INDEX" does not wait until the index is actually available
        # for use. In Cassandra, reads immediately after the CREATE INDEX
        # fail. So let's retry until reads resume working:
        tries = 100
        while tries > 0: 
            try:
                tokens2 = [row.system_token_pk for row in cql.execute('SELECT token(pk) FROM '+table+' WHERE x=1')]
                tries = 0
            except ReadFailure:
                time.sleep(0.1)
                tries -= 1
        assert tokens2 == tokens
```

**Closed** 2020-11-06 12:03 UTC
Labels: Backport candidate, sec-index

**Comment by avikivity** [comment] 2020-11-15 15:26
@avelanarius what's the user impact? incorrect results while paging?

**Comment by psarna** [comment] 2020-11-15 15:55
@avikivity the results are correct as in all rows are returned correctly, but the order of partitions was semi-arbitrary, while Cassandra maintains the token order of the base table and we prefer to stay compatible.

**Comment by avikivity** [comment] 2020-11-15 15:57
Ok, so backports not needed.

**Comment by nyh** [comment] 2021-03-07 10:46
The decision not to backport this fix to 4.3 should perhaps be reconsidered. The same bug was re-discovered independently by @Orenef11 in #8207, which admittingly is not an actual user but a QA user - but it was still a waste of time to debug a bug we already solved.

I'm re-adding the "backport needed" tag. Feel free to remove it again if we decide this again.

**Comment by avikivity** [comment] 2021-03-07 16:55
Well, it is a non-trivial change and includes a cluster feature. That doesn't make it non-backportable, but it needs justification.

**Comment by avikivity** [comment] 2021-11-15 11:30
All active branches have it, so not backporting.
