### ISSUE TITLE
The system.paxos table grows to tens of GBs if one or more nodes are down, due to write amplification on compaction

### ISSUE THREAD

**Issue by alecco** [scylladb/scylla#6375] opened 2020-05-05 14:25 UTC
[Kostja](https://groups.google.com/a/scylladb.com/forum/#!msg/rnd-internal/R9yre6pOwos/Go_tprFiAgAJ):

> The way Cassandra manages system.paxos table is that it always
> keeps the last mutation in system.paxos, in field called
> most_recent_commit. In case one of the nodes missed out from the
> quorum, the field is used to repair it before the next round.
> 
> The data is expired after TTL seconds, ~3 days by default.
> 
> Cassandra 4.0 ships with a standard LWT benchmark for blogposts.
> 
> The row for blogpost is ~5KB, the biggest part being the post
> itself. The benchmark is touching ~10 000 000 random rows using
> lightweight transactions.
> 
> Needless to say that the table can grow huge, and not only in the
> blogposts scenario.
> On a i8.xlarge*3 cluster, the table footprint on disk grows to 20G
> in just 20 minutes of intensive stress testing.
> 
> The issue is not the table size itself, it is the write
> amplification which is incurred by the compaction of this table.
> Since updated keys are random, compaction constantly reshuffles
> the entire data set, requiring tens of megabytes of extra
> bandwidth per second. This stupid and needless compaction also
> eats away quite significantly on CPU and is the main suspected
> contributor into latency spikes.
> 
> This is like keeping all of your commit log segments and also
> constantly re-sorting them.
> 
> Most of the time neither the fattest part - most_recent_commit,
> nor entire row are needed, since all nodes were alive at commit
> time, and we won't need the row for repair. We need to be taking
> this into account and pruning this data proactively, to save on
> compaction bandwidth.

**Comment by slivne** [comment] 2020-05-06 15:01
system.paxos should potentially move and use TWCS (unless you find a better solution).

**Comment by kostja** [comment] 2020-05-11 07:31
https://issues.apache.org/jira/browse/CASSANDRA-13508 is for configurable compaction strategy of system.paxos in upstream, patch provided, not committed.

**Comment by kostja** [comment] 2020-05-25 12:19
Closing as duplicate of #6330, this issue describes the problem, while #6330 revolves around the solution, but #6330 is patch pending.

**Closed by kostja** 2020-05-25 12:19 UTC
Labels: lwt
