### ISSUE TITLE
cqlsh: "LIMIT" not working on previous results

### ISSUE THREAD

**Issue by stijnsanders** [scylladb/scylla#3293] opened 2018-03-15 13:39 UTC
*Installation details*
Scylla version (or git commit hash): 2.1
Cluster size: 1
OS (RHEL/CentOS/Ubuntu/AWS AMI): Ubuntu (Linux Mint)

*Steps to reproduce*
* start `cqlsh`
* enter `select * from system_schema.columns;`
* enter `select * from system_schema.columns limit 5;`

*Result*
The full list of column data, again.
*Expected Result*
Only the first 5 rows.

*Comments*
May be due to the results of the first query getting cached somewhere, and the fetch-mechanic from this cache being unaware of the new `LIMIT` clause on the second query.

**Comment by duarten** [comment] 2018-03-16 21:54
Can you provide some test data (table creation statements)? Also, do you see this problem only when querying system tables, or is it pervasive?

**Comment by slivne** [comment] 2018-03-18 12:16
@stijnsanders 

I was not able to reproduce this running docker with 2.1.0 

(I ran the exact same statement sequence)

which platfor are you running this - can you please provide the output of ```scylla --version```

**Comment by stijnsanders** [comment] 2018-03-20 18:58
I installed linuxmint-18.3-cinnamon-64bit.iso in a local VirtualBox instance, `scylla --version` gives:

    2.1.0-0.20180214.58b90ce

**Comment by tzach** [comment] 2018-03-20 19:25
fail to reproduce on Ubuntu 16.04, with scylla 2.1
```
cqlsh> select * from system_schema.columns limit 5;
 keyspace_name | table_name | column_name    | clustering_order | column_name_bytes              | kind          | position | type
---------------+------------+----------------+------------------+--------------------------------+---------------+----------+--------------------
 system_schema | aggregates | aggregate_name |              ASC | 0x6167677265676174655f6e616d65 |    clustering |        0 |               text
 system_schema | aggregates | argument_types |              ASC | 0x617267756d656e745f7479706573 |    clustering |        1 | frozen<list<text>>
 system_schema | aggregates |     final_func |             NONE |         0x66696e616c5f66756e63 |       regular |       -1 |               text
 system_schema | aggregates |       initcond |             NONE |             0x696e6974636f6e64 |       regular |       -1 |               text
 system_schema | aggregates |  keyspace_name |             NONE |   0x6b657973706163655f6e616d65 | partition_key |        0 |               text
(5 rows)
cqlsh> exit
tzach@tzach-ubuntu16-test:~$ scylla --version
2.1.0-0.20180216.58b90ce
```

Probably not related, but your reported version is from 20180214, what I have is 20180216
Are you using installing Scylla from official packages or source?

**Comment by stijnsanders** [comment] 2018-03-20 19:39
I added the scylladb PPA to apt's sources per the install instructions...

**Comment by duarten** [comment] 2018-05-04 11:17
I can't repro this, and I'm not aware of any bug in 2.1 about `limit` not working, so I'm closing this. Please comment if you're still hitting the issue.

**Closed by duarten** 2018-05-04 11:17 UTC
Labels: User Request
