### ISSUE TITLE
Conflicting LWT transactions may be committed when prepares and accepts are using different quorums

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/scylla#6139] opened 2020-04-06 17:05 UTC
Scylla version (or git commit hash): 3.2+
Cluster size: 3+

Scenario:

CAS1 ballot (t0) < CAS2 ballot (t1)

1. nodes {A, B, C}
2. CAS1 prepares on A and B
3. CAS2 prepares on A and B
4. CAS2 accepts on B and C
5. CAS2 commits on B and is done
6. CAS1 is accepted on C
7. CAS3 uses A and C and doesn't see effects of CAS2, is not aware that CAS2 was accepted, so won't replay it

**Edit:** As Kamil pointed out, in step 7 CAS3 will see CAS2 as accepted because proposals are saved with ballot as the timestamp. The bug is still there though, new scenario:

1. nodes {A, B, C}
2. CAS1 prepares on A and B
3. CAS1 is accepted on A
4. CAS2 prepares on A and B
5. CAS2 is accepted on B and C
6. CAS2 commits on B and is done
7. CAS1 is accepted on C
8. CAS1 coordinator thinks it has a quorum of accepts and proceeds to commit

The problem is in step 7 where C accepts CAS1 because the proposal has a higher timestamp than any promised ballot. The relevant check in paxos_state.cc:

```
proposal.ballot == state._promised_ballot || proposal.ballot.timestamp() > state._promised_ballot.timestamp()
```

Could be fixed by refusing to accept ballots != promised ballots or by refusing to accept ballots <= last accepted ballot.

**Comment by tgrabiec** [comment] 2020-04-06 17:09
There is also a similar scenario which involves paxos-state pruning (4.0+):

0. x = 0
1. CAS1 is preparing set x = 1 if x = 0 using ballot t0
2. CAS1 is successfully prepared and got read results with x = 0 but hasn't moved to the accept phase yet
3. CAS2 is preparing set x = 2 if x = 0 using ballot t1
4. CAS2 also sees x = 0, is accepted, committed and prunes paxos_state
5. CAS1 attempts accept() and succeeds, because paxos state doesn't remember t1 from CAS2 anymore
6. CAS1 commits

Both CAS1 and CAS2 will succeed but they conflict.

**Comment by kostja** [comment] 2020-04-06 21:49
Initially I was thinking that a repair at step 7 should resolve this. 
In prepare response to CAS3 most_recent_commit will be empty, while accepted_proposal will be CAS1, as CAS1 is stored on C.  Since we have in_progress accepted proposal, but missing most_recent_commit (neither A nor C have committed CAS1 or CAS2), CAS3 will switch to committing CAS1 proposal with CAS3 ballot. 
Unfortunately, this will only make CAS3 commit CAS1, despite CAS2 having been already accepted by the majority.

It seems we should not accept CAS1 on C in step 6, after having accepted CAS2 already. By not looking at accepted proposal ballot number, and only looking at promised ballot we essentially make a promise to accept an older proposal. 
We could fix it by either updating promised_ballot along with accepted_proposal in save_paxos_proposal(), or by looking at accepted_proposal ballot along with promised_ballot in paxos_state::accept().

**Comment by kostja** [comment] 2020-04-06 22:55
An alternative fix is to keep accepting the proposal, but update system.paxos *only* if the proposal is greater than the currently accepted one, so that we don't forget the highest accepted proposal and return it to the next prepare request. This would perhaps be closer to spirit of Paxos Made Simple.

**Comment by tgrabiec** [comment] 2020-04-07 13:06
@kostja Because committing a proposal deletes information about the accept, I think we also need to take MRC ballot into account (or not delete the proposal ballot information).

Scenario:

CAS1 ballot < CAS2 ballot

1. nodes {A, B, C}
2. CAS1 prepares on A and B
3. CAS1 accepts on A
4. CAS2 prepares on A and B
5. CAS2 accepts on B and C
6. CAS2 commits on C and is done (this erases the information about CAS2 being accepted)
7. CAS1 accepts on C

Now both CAS1 and CAS2 are accepted by quorum, CAS1 coordinator may proceed to commit and both will end up being committed.

**Comment by kbr-** [comment] 2020-04-07 13:39
> CAS3 uses A and C and doesn't see effects of CAS2, is not aware that CAS2 was accepted, so won't replay it

that's not true. C accepted proposal numbered `t1`, and acceptors store the highest-numbered accepted proposal. So after step 6 C still stores `t1` (even though it accepted `t0`). So CAS3 will see CAS2 on node C.

**Comment by kbr-** [comment] 2020-04-07 13:41
You can see in the code that C will still store the proposal numbered `t1` even after accepting the proposal numbered `t0`, because in `save_paxos_proposal` it uses the proposal number as a timestamp.

**Comment by kbr-** [comment] 2020-04-07 14:07
> CAS1 ballot < CAS2 ballot
> 
>  1. nodes {A, B, C}
>  2. CAS1 prepares on A and B
>  3. CAS1 accepts on A
>  4. CAS2 prepares on A and B
>  5. CAS2 accepts on B and C
>  6. CAS2 commits on C and is done (this erases the information about CAS2 being accepted)
>  7. CAS1 accepts on C

The CAS1 proposer must learn either of the two things from C:
- either the highest-numbered accepted proposal in this round (accepted_proposal),
- or that the round has ended (most_recent_commit).

**Comment by tgrabiec** [comment] 2020-04-07 14:20
> > CAS3 uses A and C and doesn't see effects of CAS2, is not aware that CAS2 was accepted, so won't replay it
> 
> that's not true. C accepted proposal numbered `t1`, and acceptors store the **highest-numbered accepted proposal**. So after step 6 C still stores `t1` (even though it accepted `t0`). So CAS3 will see CAS2 on node C.

You're right. 

We still have a bug though, because the fact that C responds to accept with success even though it failed leads CAS1 coordinator to think that it has a quorum when it has not, and it will proceed to commit.

**Comment by kbr-** [comment] 2020-04-07 14:23
> We still have a bug though, because the fact that C responds to accept with success even though it failed leads CAS1 coordinator to think that it has a quorum when it has not, and it will proceed to commit.

C should send the highest-numbered accepted proposal to the CAS1 coordinator (in this case, the `t1` proposal). If it doesn't, then indeed we have a bug.
If it does, then CAS1 can safely commit the `t1` proposal. Committing should be idempotent.

**Comment by tgrabiec** [comment] 2020-04-07 14:52
@kbr- I'm not sure what you mean by "CAS1 can safely commit the t1 proposal". CAS1 should fail or restart when his proposal is not going to be accepted. We commit other proposal in the prepare phase,  not in the accept phase.

**Comment by kbr-** [comment] 2020-04-07 15:09
@tgrabiec 

forget that last post, I confused the prepare and accept phases.
You're right that CAS1 will fail in your old scenario. In this case CAS1 will fail because it didn't receive an accept from a quorum (only from C).

Also, your new scenario doesn't show any problem, at least I don't see one. In this scenario indeed both CAS1 and CAS2 had a quorum, but their proposals *used the same mutation* (when in step 4 CAS2 prepared on A and B, it learned about the highest-numbered proposal accepted by A, i.e. the one proposed by CAS1).

Paxos doesn't ensure that only a single proposal is chosen. It ensures that *if two proposals are chosen, they have the same value* (in our case, the mutation).

For us it's not a problem because learning = writing a mutation, and writing the same mutation twice is the same as writing it once.

**Comment by tgrabiec** [comment] 2020-04-07 19:05
It indeed seems like there is no problem as long as acceptors always keep the latest proposal. When we see CAS2 being accepted on C, it means that CAS2 was also prepared on a quorum. 
There are two possibilities, either (1) CAS2 prepares didn't see any of CAS1 accepts, then CAS1 will not be able to achieve a quorum of accepts and it doesn't matter how C (which doesn't belong to the CAS2 preparing quorum) responds, or (2) CAS2 prepares saw some of the CAS1 accepts, in which case CAS2 will be replaying CAS1 and will restart afterwards.

**Comment by kostja** [comment] 2020-04-08 12:00
To sum up: the updated (Edit:) scenario doesn't have a bug either, since CAS2 must switch to committing CAS1 proposal after seeing it on A. Thanks to timestamp-based proposal versioning, neither Cassandra nor Scylla have an issue here. 
I'm attaching a link to stackoverflow as a historical reference and closing as not a bug:
https://stackoverflow.com/questions/29880949/contradiction-in-lamports-paxos-made-simple-paper

**Closed by kostja** 2020-04-08 12:00 UTC
Labels: Backport 4.0, Correctness, bug, lwt

**Comment by kbr-** [comment] 2020-04-10 13:06
@kostja 

> It should be noted that accepting an older proposal is still contrary to Paxos specification

how so?

Accepting it doesn't break the invariants commonly used to prove Paxos' correctness, and it doesn't contradict e.g. the algorithm described in Paxos Made Simple.

(it does contradict the algorithm described in Part-time Parliament (the Synod protocol), but that algorithm is unnecessarily strict. For example, an acceptor (priest) in Synod accepts only if the proposal's ballot number is exactly equal to the promised ballot number, which means the proposer can only get accepts from the acceptors who have previously promised; this is an unnecessary constraint)

I agree we can/should decide to not accept it _as an optimization_ and maybe even send a NACK.

**Comment by kbr-** [comment] 2020-04-10 13:10
What we should focus on IMHO is the "commit"/"learn" phase, which was invented by Cassandra developers based on intuition and "I think it works" reasoning, without any formal spec or even sketch of a proof of correctness.

For example, making acceptors forget about their highest-numbered accepted proposals due to a learn seems very fishy. It might break the invariants if there's a proposer who's still "in the past" (sending proposals to the previous round).

**Comment by kostja** [comment] 2020-04-10 13:14
> @kostja
> 
> > It should be noted that accepting an older proposal is still contrary to Paxos specification
> 
> how so?

Here's a link to TLA+ specification:
https://github.com/tlaplus/DrTLAPlus/blob/master/Paxos/Paxos.tla#L109

maxBal is updated on accept, and you never accept anything older than maxBal

**Comment by kbr-** [comment] 2020-04-10 13:26
So this is a version where the acceptor, on accepting, also makes a promise.

Still, note that this is **a** version of Paxos, it isn't *the* Paxos (because there's no such thing). There are versions of Paxos which work but don't do this (e.g. the one in Paxos Made Simple).

But I won't argue, it's nice if we stick to some version that has a formal spec written down (and it even has a proof, which is nice). Maybe we should link to this spec somewhere in our comments.

**Comment by gleb-cloudius** [comment] 2020-04-18 07:28
Paxos Made Simple version is very confusing. It does not know by itself what variant of algorithm it describes. On one hand it has:

```
With this optimization, an acceptor needs to remember only the highest-numbered proposal
that it has ever accepted and the number of the highest numbered prepare request to which
it has responded.  Because P2c must be kept invariant regardless of failures, an acceptor
must remember  this information even if it fails and then restarts.
```
So here it says that highest accepted ballot have to be remembered implying that it can be different from highest promised.

But then it describes an algorithm it says:

```
If the proposer receives a response to its prepare requests (numbered n) from a majority of
acceptors, then it sends an accept request to each of **those** acceptors for a proposal
numbered n with a value v, where v is the value of the highest-numbered proposal among the
responses, or is any value if the responses reported no proposals
```
And here it says that accept is sent only to replicas that promise meaning that the situation above cannot arise.

**Comment by kostja** [comment] 2020-04-18 07:52
@gleb-cloudius we figured out with @kbr- that Part Time Parliament quite unambiguously says that the proposals are sent only to the respondents to prepare. Please check the formal specification part at the end of the paper. So not only Paxos Made Simple is ambiguous, it's different from Part Time Parliament and both are different from the TLA+ specification and the latest presentation made by Lesley in Saint-Petersbourg (2019) where he clarifies that acceptor set is not the same as promiser set. In the end we followed TLA+ version.
