### ISSUE TITLE
Alternator Docs - explain RF of new DC

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#6353] opened 2020-05-03 11:38 UTC
Alternator replication is set for RF=3 per each DC on *Cluster Creation*
https://github.com/scylladb/scylla/blob/master/docs/alternator/alternator.md#running-alternator

There is no way (via Alternator REST API, or nodetool) to add a new DC and extend the replication to it as well

**Comment by slivne** [comment] 2020-05-04 21:35
I think the "correct" form should be following the Dynamo API for creating global tables and not something else

https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/globaltables.tutorial.html

**Comment by slivne** [comment] 2020-05-11 19:53
@nyh ^^ do we have an issue for this ?

**Comment by nyh** [comment] 2020-05-12 21:49
Yes, the Global Tables issue is #5062.
Note that "Global Tables" doesn't mean the table exists on all DCs - it only exists on specific DCs and there is an API to assign this table to additional DCs. So the Global Tables API is exactly what Tzach was looking for.
So I'm tempted to close this issue as a duplicate of #5062, except that Tzach has a good point that maybe we should improve the documentation of the **current** implementation. That should be very easy - in alternator.md we currently have the sentence:

> Currently, *all* Alternator tables are created as "Global Tables", i.e., can be accessed from all of Scylla's DCs.

I think should just change it to something like this:

> ... can be accessed from all of Scylla's DCs at the time of table creation. Currently, if a DC is added after a table is created the table won't be visible from the new DC, and changing that requires CQL statements to modify the table's replication.

**Closed** 2020-05-14 19:52 UTC
Labels: Alternator, Backport 4.0, Backport candidate, Documentation

**Comment by nyh** [comment] 2020-05-31 10:14
Backported to 4.1. This is just a documentation improvement, but it has no risk so it will be a shame to make a new release with known errors in the documentation on the first day.
