### ISSUE TITLE
Missing row in the output of 'select * from table' query

### ISSUE THREAD

**Issue by ilya-rarov** [scylladb/scylla#10049] opened 2022-02-08 19:45 UTC
*Installation details*
Scylla version (or git commit hash): 5.0.rc0-0.20220204.da0cd2b10 with build-id cfe14388a81a0f203b14fd947caadf1f2a1e722f 
Instance type: i3.2xlarge
Number of ScyllaDB nodes: 4
Backend: aws: eu-west-1
AMI: ami-0b329e394eded2270
OS: Ubuntu 20.04

[This build](https://jenkins.scylladb.com/job/scylla-master/job/rolling-upgrade/job/rolling-upgrade-ami-test/84/) of the Rolling Upgrade test Job failed while trying to perform the test for paged query on the base version of Scylla (before upgrade).
The test basically does the following:
1. Creates table `CREATE TABLE IF NOT EXISTS paged_query_test (k int PRIMARY KEY, v1 int, v2 int)`
2. Inserts 1000 rows into the table, where `k` is in the range 0...999 and `v1` and `v2` are random numbers.
3. Runs the query `select * from paged_query_test;` using the session with CL="ONE". Let's call the output of this query `set_1`
4. Changes CL to "QUORUM" and runs the same query `select * from paged_query_test;` using the paging feature. Let's call the output of this query `set_2`
5. Compares `set_1` and `set_2` row by row - they should be the same.

But in the failed build we got the following error:
```
2022-02-07 19:34:34.377: (TestFrameworkEvent Severity.ERROR) period_type=one-time event_id=140b7c64-a171-4f7a-9f95-fcdc079235ca, source=UpgradeTest.test_rolling_upgrade (upgrade_test.UpgradeTest)() message=Traceback (most recent call last):
File "/home/ubuntu/scylla-cluster-tests/upgrade_test.py", line 547, in test_rolling_upgrade
self.paged_query()
File "/home/ubuntu/scylla-cluster-tests/sdcm/fill_db_data.py", line 3389, in paged_query
self.assertEqual(sorted(full_query_res), sorted(full_res), "Results should be identical")
AssertionError: Lists differ: [[0, [22274 chars], [982, 355106, 356088], [983, 403285, 404268][364 chars]343]] != [[0, [22274 chars], [981, 989885, 990866], [982, 355106, 356088][387 chars]343]]
First differing element 981:
[982, 355106, 356088]
[981, 989885, 990866]
Second list contains 1 additional elements.
First extra element 999:
[999, 908344, 909343]
Diff is 25717 characters long. Set self.maxDiff to None to see it. : Results should be identical
```
This means that the `set_1` and `set_2` were different. When the test was supposed to compare rows with `k=981` it got a row with `k=981` from the `set_2` and a row with `k=982` from the `set_1`. It also complained that `set_2` has one row more than `set_1`.
For an unknown reason, the row with `k=981` was missing from the `set_1`

_Logs_:

- Test-id: 40b1c93f-0427-4616-9e19-9879f7a2419f
- [grafana screenshot](https://cloudius-jenkins-test.s3.amazonaws.com/40b1c93f-0427-4616-9e19-9879f7a2419f/20220207_193435/grafana-screenshot-overview-20220207_193435-rolling-upgrade-master-centos-monitor-node-40b1c93f-1.png)
- [db-cluster](https://cloudius-jenkins-test.s3.amazonaws.com/40b1c93f-0427-4616-9e19-9879f7a2419f/20220207_194030/db-cluster-40b1c93f.tar.gz)
- [loader-set](https://cloudius-jenkins-test.s3.amazonaws.com/40b1c93f-0427-4616-9e19-9879f7a2419f/20220207_194030/loader-set-40b1c93f.tar.gz)
- [monitor-set](https://cloudius-jenkins-test.s3.amazonaws.com/40b1c93f-0427-4616-9e19-9879f7a2419f/20220207_194030/monitor-set-40b1c93f.tar.gz)
- [sct](https://cloudius-jenkins-test.s3.amazonaws.com/40b1c93f-0427-4616-9e19-9879f7a2419f/20220207_194030/sct-runner-40b1c93f.tar.gz)

- Restore Monitor Stack command: `$ hydra investigate show-monitor 40b1c93f-0427-4616-9e19-9879f7a2419f`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=40b1c93f-0427-4616-9e19-9879f7a2419f)
- Show all stored logs command: `$ hydra investigate show-logs 40b1c93f-0427-4616-9e19-9879f7a2419f`

**Comment by roydahan** [comment] 2022-02-08 20:33
@fgelcer this is a new test that you added (as part of a4c2beab40a00608112ca65c41009abd3111001d) , I don't see it in dtest and I don't know if it ever passed.

**Comment by fgelcer** [comment] 2022-02-08 20:49
> 9f37f14070019e51ff930c24f10d8deeacea831a

@roydahan , it was merged almost 1 year ago.. so need to find what has changed in Scylla.
i remember in the past some issue related to the ordering being different between Python and Scylla, and not always they will be the same?
maybe we have a new version of Python? or a new version of one of SCT dependency? or a change in Scylla related to ordering?

**Comment by fgelcer** [comment] 2022-02-08 20:50
ah, and it is running as part of our rolling upgrade tests since it was merged, almost 1 year ago

**Comment by avikivity** [comment] 2022-02-09 08:26
Did the table already exist before the CREATE ... IF NOT EXISTS?

What consistency level do you use to write to the table?

**Comment by fgelcer** [comment] 2022-02-09 09:22
> Did the table already exist before the CREATE ... IF NOT EXISTS?

following the log, it was the 1st time the test was called (so the table did not exist before it)

> 
> What consistency level do you use to write to the table?

in the logs i see multiple times this:
```
com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query at consistency QUORUM (2 replica were required but only 1 acknowledged the write)
com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query at consistency QUORUM (2 replica were required but only 1 acknowledged the write)
com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query at consistency QUORUM (2 replica were required but only 1 acknowledged the write)
com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query at consistency QUORUM (2 replica were required but only 1 acknowledged the write)
com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query at consistency QUORUM (2 replica were required but only 1 acknowledged the write)
com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query at consistency QUORUM (2 replica were required but only 1 acknowledged the write)
com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query at consistency QUORUM (2 replica were required but only 1 acknowledged the write)
com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query at consistency QUORUM (2 replica were required but only 1 acknowledged the write)
com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query at consistency QUORUM (2 replica were required but only 1 acknowledged the write)
com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query at consistency QUORUM (2 replica were required but only 1 acknowledged the write)
com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query at consistency QUORUM (2 replica were required but only 1 acknowledged the write)
com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query at consistency QUORUM (2 replica were required but only 1 acknowledged the write)
```

**Comment by fgelcer** [comment] 2022-02-09 09:26
@avikivity , could this be related to #9119?

**Comment by bentsi** [comment] 2022-02-09 09:39
@avikivity
![image](https://user-images.githubusercontent.com/5269241/153168427-0014b583-f748-4c54-895a-87d9c0a7f915.png)

**Comment by ilya-rarov** [comment] 2022-02-09 09:44
@avikivity `INSERT INTO` is performed with CL = "ONE" as well.

**Comment by bentsi** [comment] 2022-02-09 09:46
@avikivity also @fgelcer logs are probably not related since they are from Cassandra Stress and our code is Python code and uses Python driver.

**Comment by avikivity** [comment] 2022-02-09 09:53
If you write at CL=ONE, then you can't expect to read back correct data with CL=QUORUM unless you repair first (don't don't lose a node before repair).
If you receive a timeout during write, then you can't expect to read back the same data.

**Comment by fgelcer** [comment] 2022-02-09 10:01
i see it was "inserted":
```
Executing CQL 'INSERT INTO paged_query_test (k, v1, v2) VALUES (980, 200840, 201820)' ...
Executing CQL 'INSERT INTO paged_query_test (k, v1, v2) VALUES (981, 989885, 990866)' ...
Executing CQL 'INSERT INTO paged_query_test (k, v1, v2) VALUES (982, 355106, 356088)' ...
Executing CQL 'INSERT INTO paged_query_test (k, v1, v2) VALUES (983, 403285, 404268)' ...
Executing CQL 'INSERT INTO paged_query_test (k, v1, v2) VALUES (984, 861851, 862835)' ...
Executing CQL 'INSERT INTO paged_query_test (k, v1, v2) VALUES (985, 712684, 713669)' ...
Executing CQL 'INSERT INTO paged_query_test (k, v1, v2) VALUES (986, 534903, 535889)' ...
Executing CQL 'INSERT INTO paged_query_test (k, v1, v2) VALUES (987, 677712, 678699)' ...
Executing CQL 'INSERT INTO paged_query_test (k, v1, v2) VALUES (988, 877133, 878121)' ...
Executing CQL 'INSERT INTO paged_query_test (k, v1, v2) VALUES (989, 388079, 389068)' ...
Executing CQL 'INSERT INTO paged_query_test (k, v1, v2) VALUES (990, 217311, 218301)' ...
Executing CQL 'INSERT INTO paged_query_test (k, v1, v2) VALUES (991, 474399, 475390)' ...
Executing CQL 'INSERT INTO paged_query_test (k, v1, v2) VALUES (992, 401872, 402864)' ...
Executing CQL 'INSERT INTO paged_query_test (k, v1, v2) VALUES (993, 874590, 875583)' ...
Executing CQL 'INSERT INTO paged_query_test (k, v1, v2) VALUES (994, 843986, 844980)' ...
Executing CQL 'INSERT INTO paged_query_test (k, v1, v2) VALUES (995, 458668, 459663)' ...
Executing CQL 'INSERT INTO paged_query_test (k, v1, v2) VALUES (996, 892790, 893786)' ...
Executing CQL 'INSERT INTO paged_query_test (k, v1, v2) VALUES (997, 577101, 578098)' ...
Executing CQL 'INSERT INTO paged_query_test (k, v1, v2) VALUES (998, 539457, 540455)' ...
Executing CQL 'INSERT INTO paged_query_test (k, v1, v2) VALUES (999, 908344, 909343)' ...
```

but when it asserts, we don't see the full results... could it be because of this:
`Diff is 25717 characters long. Set self.maxDiff to None to see it. : Results should be identical`?

**Comment by avikivity** [comment] 2022-02-09 10:03
Do you insert with CL=ONE or CL=QUORUM?

**Comment by fgelcer** [comment] 2022-02-09 10:06
> Do you insert with CL=ONE or CL=QUORUM?

it is not set what CL it is using (what is supposed to be the default, when not set?)

**Comment by bentsi** [comment] 2022-02-09 10:41
![image](https://user-images.githubusercontent.com/5269241/153181774-bd03e51a-a30c-4b01-a032-a3b89d2de214.png)

**Comment by avikivity** [comment] 2022-02-13 15:41
Is you insert with CL=ONE, then overload can cause rows to be missing. If you want SELECT to reflect the outcome of INSERT, then you have to either insert with CL=QUROUM, or repair before SELECT.

**Comment by eliransin** [comment] 2022-02-15 09:12
Or reading with CL=ALL if you don't want to repair :slightly_smiling_face:

**Comment by fgelcer** [comment] 2022-02-15 09:22
we had this test running for ~11 months without problem... now we are porting it to dtest, and will be sure it is reproducible (before making one of the fixes suggested by Avi), and then fix it...
thank you.

**Comment by bentsi** [comment] 2022-02-20 12:08
@fgelcer 
Avi wrote: 
> If you insert with CL=ONE, then overload **can cause rows to be missing**

I don't understand what exactly do you want to reproduce here? If you write the data the way you do, under load, you don't have 
a guarantee that selecting with CL=ONE you will get all the data. The test queries with CL=ONE...

**Comment by fgelcer** [comment] 2022-02-20 12:46
> @fgelcer Avi wrote:
> 
> > If you insert with CL=ONE, then overload **can cause rows to be missing**
> 
> I don't understand what exactly do you want to reproduce here? If you write the data the way you do, under load, you don't have a guarantee that selecting with CL=ONE you will get all the data. The test queries with CL=ONE...

trying to reproduce, because that test is in place for 11 full months, and running without any problem, since this issue was reported... if so, need to understand why (maybe there is a performance regression with Scylla?), and the fix will be placed at some time soon, no doubt...
but if for 11 months the test worked perfectly, then we need to reproduce the issue, to understand:
1) how it passed for 11 months
2) why it started failing now
3) what is the "cheapest" way to fix the issue, as there are 3 suggestions of fixes, and I'm sure there will be one that is better than others...

**Comment by avikivity** [comment] 2022-02-20 17:22
If you think it is a regression, the easiest way is to bisect scylla to see where the regression started.

**Comment by fgelcer** [comment] 2022-02-20 18:14
> If you think it is a regression, the easiest way is to bisect scylla to see where the regression started.

of course, but let's first have this error reproduced, at least once more to understand if we should bisect Scylla, or not..

**Comment by bentsi** [comment] 2022-02-21 11:02
Per our conversation with Roy we decided as follows:
1) fix the test in SCT as  Avi & Eliran suggested
2) check if we have a funcional test in dtest that has the same scenario, if not add such test

Regarding performance regression, it shuold be checked in Permance Regression tests.
The failure happens during stress that uses: `compression=LZ4Compressor compaction(strategy=SizeTieredCompactionStrategy)'`. AFAIK, we don't have a test that checks perf regressions with such parameters. I suggest to add such tests. @roydahan

**Comment by roydahan** [comment] 2022-02-23 12:29
Invalid issue.

**Closed** 2022-02-23 12:29 UTC
