### ISSUE TITLE
Have been using 2 node (4core, 15GB) cluster for insertion of data. Used async insertion, after sometimes the scylla service becomes unresponsive on one of the node. Kindly Help.

### ISSUE THREAD

**Issue by rohitanurag** [scylladb/scylla#4383] opened 2019-04-02 05:24 UTC

**Comment by tzach** [comment] 2019-04-02 07:12
@rohitanurag thanks for reporting
please provide more details:
- What Scylla version are you using?
- Are there any errors in the logs?
- Can you please prvoide monitoring data

See the [Report a performance problem](https://docs.scylladb.com/troubleshooting/report_scylla_problem/#report-a-performance-problem) for relevant data to help us debug this issue.

**Comment by rohitanurag** [comment] 2019-06-28 10:30
Hi @tzach  I am using this version 3.0.7-0.20190528.4c16c1fe1.

Please find the logs

[shard 1] cql_server - request processing failed: std::runtime_error (Value too large, 131072 > 65535)
Jun 27 06:39:35 scylla-node1 scylla:  [shard 1] storage_proxy - Exception when communicating with 10.240.0.52: std::bad_alloc (std::bad_alloc)
Jun 27 06:39:35 scylla-node1 scylla:  [shard 0] batchlog_manager - Exception in batch replay: exceptions::read_failure_exception (Operation failed for system.batchlog - received 0 responses and 1 failures from 1 CL=ONE.)

**Comment by rohitanurag** [comment] 2019-07-09 05:19
@denesb @avikivity  Please help in resolving this issue.

**Comment by rohitanurag** [comment] 2019-07-09 05:43
Schema which I used


MAPPING = {
   'url': ['url', 'text'],
   '_id' : ['Innoplexus_id', 'text'],
   'response_url': ['response_url','text'],
   'html': ['html','text'],
   'tld': ['tld','text'],
   'link_text': ['link_text', 'text'],
   'referer_url': ['referer_url','text'],
   'status_code': ['Status_code','int'],
   'crawled_date': ['crawled_date', 'text'],
   'domain': ['Domain','text'],
   'subdomain': ['subdomain','text'],
   'registered_domain': ['registered_domain','text'],
   'suffix': ['suffix','text'],
   'depth': ['depth','int'],
   'download_latency': ['download_latency','double'],
   'download_slot': ['download_slot','text'],
   'download_timeout': ['download_timeout','double'],
   'headers': ['headers','text'],
   'title': ['Article_title','text'],
   'text': ['text', 'text'],
   'meta_content': ['meta_content', 'list<frozen<map<text,text>>>'],
   'file_urls': ['file_urls','list<text>'],
   'page_urls': ['page_urls','list<frozen<map<text,text>>>'],
   'is_pdf_file': ['is_pdf_file','boolean'],
   'pdf_meta_data': ['pdf_meta_data','list<frozen<map<text,text>>>'],
   'ClassifiedFlag': ['ClassifiedFlag','boolean'],
   'ExtractedFlag': ['ExtractedFlag','boolean'],
   'asset_class': ['asset_class','text'],
   'rule': ['rule','int'],
   'source': ['source','text'],
   'jobid': ['jobid','text'],
   'restrict': ['restrict','boolean'],
   'crawled_date_ts': ['crawled_date_ts','int'],
   'mongo': ['mongo','list<frozen<map<text,text>>>'],
}

This is the config file which we made
here .. the large blob can be html, page_urls, file_urls, text
html value is too large

**Comment by denesb** [comment] 2019-07-09 13:50
From @haaawk:
> from sstables perspective the limit is 2^64
> because the value of a cell has varint size:
> ```
> struct cell_value {
>   optional<varint> length;
>   byte value[];
>};
> ```
> the limit is there
> here's when it's enforced:
> ```
> T cast_if_fits(size_t v) {
>   size_t max = std::numeric_limits<T>::max();
>   if (v > max) {
>       throw std::runtime_error(format("Value too large, {:d} > {:d}", v, max));
>   }
>   return static_cast<T>(v);
>}
>
>void cql_server::response::write_string(const sstring& s)
>{
>   write_short(cast_if_fits<uint16_t>(s.size()));
>   _body.write(bytes_view(reinterpret_cast<const int8_t*>(s.data()), s.size()));
>}
>```
>that's transport/server.cc
> 
> it's actually a cql limitation: https://github.com/apache/cassandra/blob/trunk/doc/native_protocol_v4.spec#L203
> length of string is represented in 16 bits
> 
> maybe we should be using long string instead: https://github.com/apache/cassandra/blob/trunk/doc/native_protocol_v4.spec#L205

**Comment by haaawk** [comment] 2019-07-15 13:56
I made an experiment and tried putting very long string to text field. It works just fine so maybe the problem is with list<frozen<map<text,text>>>. I will check

**Comment by haaawk** [comment] 2019-07-15 14:24
What driver are you using @rohitanurag ?

**Comment by haaawk** [comment] 2019-07-15 14:30
Here's my suspicion is that you either somehow managed to create a list longer than 65535 or inserted a text key into a map with more than 65535 characters. Both cases are handled correctly (cqlsh rejected them) when I tried to do them in cqlsh. Maybe some driver do not respect those limits or maybe you were adding stuff to the list until in exceeded the 65535. I will check the second scenario and see whether this could be the case.

**Comment by tzach** [comment] 2019-08-26 07:54
Closing as we need more info. @rohitanurag please reopen once can provide the driver info. Thanks.

**Closed by tzach** 2019-08-26 07:54 UTC
Labels: User Request
