### ISSUE TITLE
bad_alloc during repair - node crash with coredump - load is suspended for ~2mins

### ISSUE THREAD

**Issue by harelassayag** [scylladb/scylla#3120] opened 2018-01-08 15:25 UTC
*Installation details*
Scylla version (or git commit hash): 2.1.rc1-0.20180104.d4c46afc5
Cluster size: 4
OS (RHEL/CentOS/Ubuntu/AWS AMI): CentOS
full log: [http://scylladb-users-upload.s3.amazonaws.com/3120/log.tar.gz
](scylladb-users-upload.s3.amazonaws.com/3120/log.tar.gz)
During repair nemesis longevity of 2.1-rc1, one node got bad_alloc errors and eventually crashed with coredump.
During the test, there was a c-s write workload running in the background and during the bad_alloc errors, the load went down to almost 0 ops.
(This happened on two different hosts in 2 different repairs out of 3 total repairs)

Errors:
```
Jan 07 13:01:53 warning|  [shard 0] storage_proxy - Failed to apply mutation from 10.142.0.25#7: std::bad_alloc (std::bad_alloc)
Jan 07 13:01:53 err    |  [shard 12] storage_proxy - exception during mutation write to 10.142.0.26: std::bad_alloc (std::bad_alloc)
Jan 07 13:01:53 warning|  [shard 2] storage_proxy - Failed to apply mutation from 10.142.0.27#6: std::bad_alloc (std::bad_alloc)
Jan 07 13:01:53 warning|  [shard 3] storage_proxy - Failed to apply mutation from 10.142.0.27#2: std::bad_alloc (std::bad_alloc)
Jan 07 13:01:53 warning|  [shard 15] storage_proxy - Failed to apply mutation from 10.142.0.24#8: std::bad_alloc (std::bad_alloc)
Jan 07 13:01:53 err    |  [shard 11] storage_proxy - exception during mutation write to 10.142.0.26: std::bad_alloc (std::bad_alloc)
Jan 07 13:01:53 warning|  [shard 0] storage_proxy - Failed to apply mutation from 10.142.0.24#13: std::bad_alloc (std::bad_alloc)
Jan 07 13:01:53 warning|  [shard 12] storage_proxy - Failed to apply mutation from 10.142.0.27#5: std::bad_alloc (std::bad_alloc)
Jan 07 13:01:53 err    |  [shard 13] storage_proxy - exception during mutation write to 10.142.0.26: std::bad_alloc (std::bad_alloc)
Jan 07 13:01:53 warning|  [shard 9] storage_proxy - Failed to apply mutation from 10.142.0.24#1: std::bad_alloc (std::bad_alloc)
Jan 07 13:01:53 warning|  [shard 9] storage_proxy - Failed to apply mutation from 10.142.0.24#1: std::bad_alloc (std::bad_alloc)
Jan 07 13:01:53 warning|  [shard 8] storage_proxy - Failed to apply mutation from 10.142.0.24#6: std::bad_alloc (std::bad_alloc)
Jan 07 13:01:53 warning|  [shard 14] storage_proxy - Failed to apply mutation from 10.142.0.24#12: std::bad_alloc (std::bad_alloc)
Jan 07 13:01:53 warning|  [shard 12] storage_proxy - Failed to apply mutation from 10.142.0.25#11: std::bad_alloc (std::bad_alloc)
.
.
.
2018-01-07 13:01:55,332 remote           L0197 DEBUG| [35.196.227.5] [stdout] Jan 07 13:01:55 warning|  [shard 7] repair - Checksum of range (-9113159465187672064, -9113159190309765120] on 10.142.0.26 failed: st
d::bad_alloc (std::bad_alloc)
2018-01-07 13:01:55,334 remote           L0197 DEBUG| [35.196.227.5] [stdout] Jan 07 13:01:55 warning|  [shard 7] repair - Checksum of range (-9113159190309765120, -9113158915431858176] on 10.142.0.26 failed: st
d::bad_alloc (std::bad_alloc)
2018-01-07 13:01:56,923 remote           L0197 DEBUG| [35.196.227.5] [stdout] Jan 07 13:01:56 warning|  [shard 7] repair - Checksum of range (-9113158640553951232, -9113158365676044288] on 10.142.0.26 failed: st
d::bad_alloc (std::bad_alloc)
2018-01-07 13:01:57,002 remote           L0197 DEBUG| [35.196.227.5] [stdout] Jan 07 13:01:57 warning|  [shard 7] repair - Checksum of range (-9113158915431858176, -9113158640553951232] on 10.142.0.26 failed: st
d::bad_alloc (std::bad_alloc)
2018-01-07 13:01:57,817 remote           L0197 DEBUG| [35.196.227.5] [stdout] Jan 07 13:01:57 warning|  [shard 7] repair - Checksum of range (-9113158365676044288, -9113158090798137344] on 10.142.0.26 failed: st
d::bad_alloc (std::bad_alloc)
2018-01-07 13:01:57,844 remote           L0197 DEBUG| [35.196.227.5] [stdout] Jan 07 13:01:57 warning|  [shard 7] repair - Checksum of range (-9113158090798137344, -9113157815920230400] on 10.142.0.26 failed: st
d::bad_alloc (std::bad_alloc)
2018-01-07 13:01:58,555 remote           L0197 DEBUG| [35.196.227.5] [stdout] Jan 07 13:01:58 warning|  [shard 7] repair - Checksum of range (-9113157815920230400, -9113157541042323456] on 10.142.0.26 failed: st
d::bad_alloc (std::bad_alloc)
2018-01-07 13:01:58,599 remote           L0197 DEBUG| [35.196.227.5] [stdout] Jan 07 13:01:58 warning|  [shard 7] repair - Checksum of range (-9113157541042323456, -9113157266164416512] on 10.142.0.26 failed: st
d::bad_alloc (std::bad_alloc)
2018-01-07 13:01:58,911 remote           L0197 DEBUG| [35.196.227.5] [stdout] Jan 07 13:01:58 err    |  [shard 7] database - failed to write sstable /var/lib/scylla/data/keyspace1/standard1-fdfa51d0f38511e791680
00000000001/keyspace1-standard1-ka-6663-Data.db: std::bad_alloc (std::bad_alloc)
2018-01-07 13:01:59,424 remote           L0197 DEBUG| [35.196.227.5] [stdout] Jan 07 13:01:59 warning|  [shard 7] repair - Checksum of range (-9113157266164416512, -9113156991286509568] on 10.142.0.26 failed: st
d::bad_alloc (std::bad_alloc)
2018-01-07 13:01:59,542 remote           L0197 DEBUG| [35.196.227.5] [stdout] Jan 07 13:01:59 warning|  [shard 7] repair - Checksum of range (-9113156991286509568, -9113156716408602624] on 10.142.0.26 failed: st
d::bad_alloc (std::bad_alloc)

```

From a basic analysis of the coredump we saw the following for task histogram:
```
(gdb) scylla task_histogram 
    343143: 0x1d413f8 _ZTVN7seastar12continuationIZNS_6futureIJEE4thenIZN5utils14phased_barrier17advance_and_awaitEvEUlvE_S2_EET0_OT_EUlS9_E_JEEE + 16 
    343141: 0x1d38090 _ZTVN7seastar12continuationIZNS_6futureIJEE12then_wrappedIZN20dirty_memory_manager9flush_oneER13memtable_listO12flush_permitEUlT_E_S2_EET0_OS9_EUlSC_E_JEEE + 16 
      1711: 0x1de4b20 _ZTVN7seastar12continuationIZNS_6futureIJEE12then_wrappedIZNS2_16handle_exceptionIZN8sstables7sstableD4EvEUlNSt15__exception_ptr13exception_ptrEE1_EES2_OT_EUlSB_E_S2_EET0_SB_EUlSB_E_JEEE + 

(gdb) scylla task_histogram 80
    364198: 0x1d38090 _ZTVN7seastar12continuationIZNS_6futureIJEE12then_wrappedIZN20dirty_memory_manager9flush_oneER13memtable_listO12flush_permitEUlT_E_S2_EET0_OS9_EUlSC_E_JEEE + 16 
    364197: 0x1d413f8 _ZTVN7seastar12continuationIZNS_6futureIJEE4thenIZN5utils14phased_barrier17advance_and_awaitEvEUlvE_S2_EET0_OT_EUlS9_E_JEEE + 16 

(gdb) scylla memory 
Used memory:    6373244928
Free memory:             0
Total memory:   6373244928

Small pools:
objsz spansz    usedobj       memory  wst%
    1   4096          0            0   0.0
    1   4096          0            0   0.0
    1   4096          0            0   0.0
    1   4096          0            0   0.0
    2   4096          0            0   0.0
    2   4096          0            0   0.0
    3   4096          0            0   0.0
    3   4096          0            0   0.0
    4   4096          0            0   0.0
    5   4096          0            0   0.0
    6   4096          0            0   0.0
    7   4096          0            0   0.0
    8   4096       1325        16384  35.3
   10   4096          0         8192  99.9
   12   4096       2049        32768  24.9
   14   4096          0            0   0.0
   16   4096       1387        28672  22.6
   20   4096       1284        28672  10.0
   24   4096       8899       221184   3.0
   28   4096        585        20480  19.8
   32   4096       3765       126976   5.1
   40   4096       2673       114688   6.4
   48   4096       2738       139264   5.2
   56   4096     367150     20602880   0.0
   64   4096      10666       688128   0.8
   80   4096     731544     58753024   0.0
   96   4096       3863       385024   2.1
  112   4096       3500       401408   0.8
  128   4096       1079       143360   3.7
  160   4096       1501       258048   4.6
  192   4096       1455       294912   3.7
  224   4096       1358       327680   5.6
  256   4096        303        94208  17.7
  320   8192        418       147456   6.9
  384   8192        250       131072  25.2
  448   4096         98        73728  38.9
  512   4096        539       299008   7.7
  640  12288        203       147456  10.9
  768  12288        618       503808   5.8
  896   8192         14        73728  81.4
 1024   4096        358       466944  21.5
 1280  20480       1130      1556480   7.1
 1536  12288        932      1572864   9.0
---Type <return> to continue, or q <return> to quit---
 1792  16384          8       147456  88.7
 2048   8192        247       581632  13.0
 2560  20480         53       204800  33.8
 3072  12288         81       466944  46.7
 3584  28672         15       286720  81.2
 4096  16384        111       786432  42.2
 5120  20480         17       389120  77.6
 6144  24576         25       466944  67.1
 7168  28672        117      1089536  23.0
 8192  32768        210      2031616  15.3
10240  40960          9       778240  88.2
12288  49152          9       933888  88.2
14336  57344          5      1089536  93.4
16384  65536         58      2359296  59.7
Page spans:
index      size [B] free [B]
    0          4096 0
    1          8192 0
    2         16384 0
    3         32768 0
    4         65536 0
    5        131072 0
    6        262144 0
    7        524288 0
    8       1048576 0
    9       2097152 0
   10       4194304 0
   11       8388608 0
   12      16777216 0
   13      33554432 0
   14      67108864 0
   15     134217728 0
   16     268435456 0
   17     536870912 0
   18    1073741824 0
   19    2147483648 0
   20    4294967296 0
   21    8589934592 0
   22   17179869184 0
   23   34359738368 0
   24   68719476736 0
   25  137438953472 0
   26  274877906944 0
   27  549755813888 0
   28 1099511627776 0
   29 2199023255552 0
   30 4398046511104 0
   31 8796093022208 0
```

Coredump (zipped and split): https://s3.amazonaws.com/scylladb-users-upload/bad_alloc_during_repair/

Load at issue:
![image](https://user-images.githubusercontent.com/15847218/34677432-c8ff6a60-f498-11e7-8b3e-62ddc7673e8c.png)

**Comment by slivne** [comment] 2018-01-14 11:48
We are going to try and minimize the "search" space - run specific reproducers on 2.0 and 2.1 and see what we get.

**Comment by roydahan** [comment] 2018-01-14 23:18
May be related to this reproducer:

```
0x4a1314
0x50fc2e
0x94b86a
0x4a00e4
0x4a03bc
0x4ef2b4
0x4f49a2
0x55765d
/lib64/libpthread.so.0+0x7e24
/lib64/libc.so.6+0xf834c
seastar::report_failed_future(std::__exception_ptr::exception_ptr) at /usr/src/debug/scylla-2.1.rc1/seastar/core/reactor.cc:4156
seastar::promise<>::abandoned() at /usr/src/debug/scylla-2.1.rc1/seastar/core/future.hh:1196
seastar::promise<>::~promise() at /usr/src/debug/scylla-2.1.rc1/seastar/core/future.hh:434
 (inlined by) ~<lambda> at /usr/src/debug/scylla-2.1.rc1/seastar/core/future.hh:945
 (inlined by) ~continuation at /usr/src/debug/scylla-2.1.rc1/seastar/core/future.hh:392
 (inlined by) ~continuation at /usr/src/debug/scylla-2.1.rc1/seastar/core/future.hh:392
std::default_delete<seastar::task>::operator()(seastar::task*) const at /opt/scylladb/include/c++/7/bits/unique_ptr.h:78
 (inlined by) std::unique_ptr<seastar::task, std::default_delete<seastar::task> >::reset(seastar::task*) at /opt/scylladb/include/c++/7/bits/unique_ptr.h:376
 (inlined by) seastar::reactor::run_tasks(seastar::reactor::task_queue&) at /usr/src/debug/scylla-2.1.rc1/seastar/core/reactor.cc:2432
seastar::reactor::run_some_tasks(std::chrono::time_point<std::chrono::_V2::steady_clock, std::chrono::duration<long, std::ratio<1l, 1000000000l> > >&) at /usr/src/debug/scylla-2.1.rc1/seastar/core/reactor.cc:2841
seastar::reactor::run_some_tasks(std::chrono::time_point<std::chrono::_V2::steady_clock, std::chrono::duration<long, std::ratio<1l, 1000000000l> > >&) at /opt/scylladb/include/c++/7/bits/unique_ptr.h:267
 (inlined by) seastar::reactor::run() at /usr/src/debug/scylla-2.1.rc1/seastar/core/reactor.cc:2985
seastar::smp::configure(boost::program_options::variables_map)::{lambda()#3}::operator()() const at /usr/src/debug/scylla-2.1.rc1/seastar/core/reactor.cc:3931 (discriminator 3)
std::function<void ()>::operator()() const at /opt/scylladb/include/c++/7/bits/std_function.h:706
 (inlined by) seastar::posix_thread::start_routine(void*) at /usr/src/debug/scylla-2.1.rc1/seastar/core/posix.cc:52
```

**Comment by slivne** [comment] 2018-01-16 07:47
@asias - @tgrabiec is checking a bad_alloc item (after fixing the reactor stalls) as well - in the second open ticket scenario #3119 - we can wait for his feedback maybe it will be related to this as well.

**Comment by tgrabiec** [comment] 2018-01-16 13:32
This could be caused by #3129, but I'm not certain.

**Comment by slivne** [comment] 2018-02-01 16:47
closing this issue - will reopen if we see it again

**Closed by slivne** 2018-02-01 16:47 UTC
Labels: bug, high
