### ISSUE TITLE
Feature request: Allow compaction on user defined list of sstables

### ISSUE THREAD

**Issue by codingcuisg** [scylladb/scylla#10276] opened 2022-03-25 14:04 UTC
This would be a feature request to allow compaction happened on user defined sstables. (similar stuff as cassandra compact command https://cassandra.apache.org/doc/latest/cassandra/tools/nodetool/compact.html)

Our current pain point:

We are using STWC for better write performance, and the data rotation is handled by TTL. Compacting all sstables together requires more additional resources. In fact we only want to run major compaction on those old sstables to clear the expired data.

Based on the code, looks like currently it will run on all available sstables, is it possible to take an intersection of available sstables and user defined sstables ?

**Comment by avikivity** [comment] 2022-03-27 15:50
TWCS restricts compaction to buckets, even in major compactions, on recent versions. What version are you using?

**Comment by codingcuisg** [comment] 2022-03-31 03:38
currently we are under 4.4.5 or 4.4.4. 

Using TWCS might not be the best option, the TTL is long 90days-1year depends on the user requests. TWCS creating too many sstables and tombstones especially the user update the value of the key. We tried TWCS but it caused mush higher query io queue and read latency.

However with STCS, the sstables will compact to bigger size sstables and it cannot be compacted(purge the tombstones as well) until find a similar size sstable per shard. So we wanna to check if possible to run compaction on sstables based on user input ?

**Comment by nyh** [comment] 2022-03-31 06:34
> This would be a feature request to allow compaction happened on user defined sstables. (similar stuff as cassandra compact command https://cassandra.apache.org/doc/latest/cassandra/tools/nodetool/compact.html)

In general I agree that if Cassandra supports a certain operation, we should consider supporting this operation. But in this case, I don't understand how users will use this feature in practice... How would users decide which sstables to list for compaction? If there is some "algorithm" that the user uses to decide which sstables to compact, this is basically a new compaction strategy, but the user probably doesn't have the same visibility into the contents of the sstables that the proper compaction strategies have.

> Our current pain point:
> 
> We are using STWC for better write performance, and the data rotation is handled by TTL. Compacting all sstables together requires more additional resources. In fact we only want to run major compaction on those old sstables to clear the expired data.

Reading your later comments, I understand you want to use STCS (not TWCS!), and do not want all the sstables to be compacted into one huge one. @raphaelsc I'm a bit out-of-sync, but don't we have a "cleanup" compaction (or whatever we called it?) which compacts each sstable individually (not combining different sstables)? Such an operation could remove expired data without merging sstables together. In theory such an operation could even gc tombstones (by looking into the other sstables, even if we don't combine them).

**Comment by raphaelsc** [comment] 2022-04-10 02:12
> currently we are under 4.4.5 or 4.4.4.
> 
> Using TWCS might not be the best option, the TTL is long 90days-1year depends on the user requests. TWCS creating too many sstables and tombstones especially the user update the value of the key. We tried TWCS but it caused mush higher query io queue and read latency.
> 
> However with STCS, the sstables will compact to bigger size sstables and it cannot be compacted(purge the tombstones as well) until find a similar size sstable per shard. So we wanna to check if possible to run compaction on sstables based on user input ?

Hi @codingcuisg 

did you play with tombstone compaction options? Tombstone compaction will allow a partially expired sstable to be included for compaction. It's enabled by default, but perhaps the default values are not good enough for you.

take a look at option details here: https://docs.scylladb.com/getting-started/compaction/#common-options

**Comment by raphaelsc** [comment] 2022-04-10 02:15
FWIW, user-defined compaction is tracked by this issue: https://github.com/scylladb/scylla/issues/4907

**Comment by raphaelsc** [comment] 2022-04-10 02:16
@codingcuisg If you have a problem with tombstone compaction not working for you, then please open another issue with all the details. I am closing this issue as duplicate of #4907

**Closed by raphaelsc** 2022-04-10 02:16 UTC
