### ISSUE TITLE
Listen address and RPC address options don't support interface names

### ISSUE THREAD

**Issue by penberg** [scylladb/scylla#1058] opened 2016-03-18 07:30 UTC
The `listen_address` and `rpc_address` configuration options don't support interface names (e.g. eth0) although comments in `scylla.yaml` say that they do.

**Comment by avikivity** [comment] 2016-03-18 11:59
Shouldn't be hard to fix by using the nice socket ioctls from sockios.h.

We should also add support for setting subnets there, e.g. `listen_address: 10.1.0.0/16`, telling the code to bind to any interface that is covered by those subnets.  The advantage is that a single setting works for the entire cluster, avoiding differences in interface naming and addresses.

**Comment by slivne** [comment] 2016-03-20 08:38
For GA I suggest we update the comments if at all

**Comment by glommer** [comment] 2019-01-10 19:36
Looks like duplicate of #456 to me.

**Closed** 2019-01-11 06:22 UTC
Labels: Field-Tier2, UX, enhancement

**Comment by amnonh** [comment] 2019-04-15 13:30
Isn't it solved by feffc2bbe1a219b31787e9ca275e00ab3cf8cbbf

**Comment by avikivity** [comment] 2019-04-15 13:49
no
