### ISSUE TITLE
mv_populating_from_existing_data_during_node_stop_test: View ks.tm_table_mv_2 not built

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#4730] opened 2019-07-17 08:24 UTC
This dtest seems to be flaky, apparently since [dtest-release/165](https://jenkins.scylladb.com/job/scylla-master/job/dtest-release/165/testReport/materialized_views_test/TestMaterializedViews/mv_populating_from_existing_data_during_node_stop_test/) (scylla version 28a514820d980adc7af068e951f24e762fd05681).

Most recent failure is [dtest-release/178/testReport/materialized_views_test/TestMaterializedViews/mv_populating_from_existing_data_during_node_stop_test_2](https://jenkins.scylladb.com/job/scylla-master/job/dtest-release/178/testReport/materialized_views_test/TestMaterializedViews/mv_populating_from_existing_data_during_node_stop_test_2/):
```
Error Message
View ks.tm_table_mv_2 not built
Stacktrace
Traceback (most recent call last):
  File "/usr/lib64/python2.7/unittest/case.py", line 367, in run
    testMethod()
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/materialized_views_test.py", line 610, in mv_populating_from_existing_data_during_node_stop_test
    self._mv_populating_from_existing_data_during_changes_test('stop node', nodes=4, rf=3, mvs=10, prefill=40000, fail=False)
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/materialized_views_test.py", line 676, in _mv_populating_from_existing_data_during_changes_test
    wait_for_view(cluster=self.cluster, session=session, ks=tm.keyspace, view=mv_name)
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/scylla_tools.py", line 907, in wait_for_view
    raise Exception(error_msg)
Exception: View ks.tm_table_mv_2 not built
```

Some of the node [logs](https://jenkins.scylladb.com/job/scylla-master/job/dtest-release/lastFailedBuild/artifact/logs-release.2/1563273063601_materialized_views_test.TestMaterializedViews.mv_populating_from_existing_data_during_node_stop_test/) indeed do not show `Finished building view ks.tm_table_mv_2`

**Comment by nyh** [comment] 2019-07-17 12:12
This is a duplicate of #4382 but I looked at the new logs:

In https://jenkins.scylladb.com/job/scylla-master/job/dtest-release/lastFailedBuild/artifact/logs-release.2/1563273063601_materialized_views_test.TestMaterializedViews.mv_populating_from_existing_data_during_node_stop_test/ it seems that log2 - with address**127.0.55.2** - is the one with the node that got stopped and then started, because it has two Scylla boots. According to this log, the time this node was down was just 1.2 seconds, but according to log1, this was enough for the other nodes to notice. So it's not a "5 minute hang during build" issue. It's something else.

Anyway, looking at log1, you can see that starting at 10:23:51,836,  we start seeing
```
ERROR 2019-07-16 10:23:51,836 [shard 0] view - Error applying view update to 127.0.55.1: std::_Nested_exception<no_such_column_family> (Can't find a column family with UUID ce56a440-a7b3-11e9-b00c-000000000000): std::out_of_range (_Map_base::at)
WARN  2019-07-16 10:23:51,836 [shard 0] view - Error executing build step for base ks.tm_table: std::_Nested_exception<no_such_column_family> (Can't find a column family with UUID ce56a440-a7b3-11e9-b00c-000000000000): std::out_of_range (_Map_base::at)
```

and this problem doesn't end until 5 minutes later, when the test times out. So this is why the build cannot complete.

But why can't 127.0.55.1, when it tells *itself* to build a table with this cf id, find it?
I think the answer is related to two lines just above in log1:
```
INFO  2019-07-16 10:23:51,835 [shard 0] schema_tables - Dropping ks.tm_table_mv_4 id=ce56a440-a7b3-11e9-b00c-000000000000 version=3fd46945-2492-3a67-890c-6d2afe0ea96c
INFO  2019-07-16 10:23:51,835 [shard 0] schema_tables - Creating ks.tm_table_mv_4 id=ce58ee30-a7b3-11e9-99fa-000000000000 version=3ee12eb9-32a2-34bd-9390-f5b1e4cc445a
```

Note how the view with id ce56a440-a7b3-11e9-b00c-000000000000 - the one the build is trying to build - gets dropped, and instead one with a different id is being created!

I have no idea why this happens (it it related to the other node going down around the same time?). But if it really should happen (?), the view build should probably adapt to this change - it should recalculate the schema id on every build step instead of trying and retrying with the now dead id...

**Comment by bhalevy** [comment] 2019-07-18 12:38
@slivne as @nyh mentioned above, this is a dup of #4382 so we can close this issue and use the previous one.

**Closed** 2019-07-18 12:42 UTC
Labels: bug, dtest, materialized-views
