### ISSUE TITLE
Alternator: UpdateItem with Attribute only in ConditionExpression fails

### ISSUE THREAD

**Issue by fruch** [scylladb/scylla#6572] opened 2020-06-02 15:11 UTC
doing this UpdateItem

```json
{
   "TableName": "Thread", 
   "Key": {
      "forum_name": {"S": "Some Forum"}, 
      "subject": {"S": "Some Subject"}
    },
    "ConditionExpression": "(#0 = :0 OR attribute_exists (#1))", 
    "ReturnValues": "ALL_NEW", 
    "UpdateExpression": "ADD #2 :1", 
    "ExpressionAttributeNames": {"#0": "forum_name", "#1": "subject", "#2": "views"}, 
    "ExpressionAttributeValues": {":0": {"S": "Some Forum"}, ":1": {"N": "1"}}, 
    "ReturnConsumedCapacity": "TOTAL"
}
```

causes the following failure:
```
(ValidationException) on request (None) on table (Thread) when calling the UpdateItem operation: ExpressionAttributeNames has spurious '#1', not used in UpdateExpression
```

I'm guessing the check validation check of `ExpressionAttributeNames` need a bit more logic...

**Comment by nyh** [comment] 2020-06-03 12:11
There's a problem in **when** we track which name references (`#xyz`) or value references (`:xyz`) were used: At the moment we do this while **evaluating** the expression. This causes the problem you saw here: when we evaluate the expression `#0 = :0 OR attribute_exists (#1)` , if the first case matches already, the first test is not evaluated at all (we use `boost::any_of` with its short-circuit evaluation), and we don't mark "`#1`" as having been used - and cause this problem.

One solution is to separate the evaluation and the used-reference-check steps. We can check for used references - and incorporate them into a (modified version) of the parse tree - right after parsing, not at evaluation time. We will notice that "`#1`"  is "used", even if during actual evaluation, we will not use the result of this reference.

Fixing this will be even more important for FilterExpression evaluation (issue #5038) - there we need to "dereference" the expression just once, and evaluate it many times (each evaluation may end up using a different subset of the referenced values).

**Comment by nyh** [comment] 2020-06-04 07:22
By the way, if we need a quick workaround for this issue, it can be done easily by ensuring that our evaluation of conditions doesn't short-circuit (i.e., doesn't use `boost::any_of`) but always evaluates all the sub-expressions before doing the "OR".

The performance loss by evaluating unnecessary parts of the condition will be negligible (and most of it would be offset anyway by our need to check which references are used even in unevaluated parts of the expression).

But the long-term solution should probably be what I described above, because it will also be needed it for `FilterExpression`.

**Comment by nyh** [comment] 2020-06-04 16:50
Interestingly, we already have one xfailing test that fails because the problem that the unused names are checked at the wrong time (at evaluation, instead of parse time): `test_condition_expression.py::test_update_condition_unused_entries_failed`. That case is the "opposite" of the case that you found - it is a case where there really is an unused name, but we don't know because we never even evaluate the UpdateExpression (because the ConditionExpression failed earlier). The case that you found now is worse, because it prevents a user from running a valid request, which is worse than not finding an error. I'll create a new test case for your case, and the same fix will fix both.

**Comment by nyh** [comment] 2020-06-04 17:21
Sent to the mailing list a patch with a test case reproducing this bug. Message titled "[PATCH] alternator test: reproducer for unjustly refused condition expression".

**Comment by psarna** [comment] 2020-06-08 11:39
The patch reached master - closing.

**Comment by nyh** [comment] 2020-06-08 11:46
Reopening. The patch was a test case, not a fix. I'm working on a fix.

**Comment by psarna** [comment] 2020-06-08 12:04
Oopsie :)

**Comment by nyh** [comment] 2020-06-09 21:55
I have a patch for this issue, which completely changes the way that name references ("#name") and value reference (":val") are handled in Alternator - instead of being resolved at evaluation time, it happens earlier, right after parsing, in a separate step called "resolving".

The patch is big, so I need to go over it again before sending, but it's mostly ready. This patch will fix the two xfailing tests described, and also a new test with additional combinations of different expressions like ProjectionExpression and KeyConditionExpression, which previously couldn't work together because both thought that any reference it didn't need was unneeded.

Importantly, this patch is also one of the last steps before finally integrating FilterExpression support - we can now "resolve" references filter expression just once, and not need to do it for every time, improving both performance and layering of the code (the filtering code didn't want to be aware of the request JSON at filtering time).

**Closed** 2020-06-15 15:43 UTC
Labels: Alternator, bug
