### ISSUE TITLE
AMI: scylla_raid_setup failed

### ISSUE THREAD

**Issue by amoskong** [scylladb/scylla#3783] opened 2018-09-26 00:15 UTC
*Installation details*
Scylla version (or git commit hash): master, ami-0b8b2660565438c49, scylla-666.development-0.20180925.05f8ed270.el7.x86_64
Cluster size: 1
OS (RHEL/CentOS/Ubuntu/AWS AMI): AWS ami-0b8b2660565438c49
Instance type: i3.large
CC: @syuu1228 

* Test job: http://jenkins.cloudius-systems.com:8080/job/scylla-master-ami-test/label=muninn/288/artifact/latest/job.log (FAILED)
http://jenkins.cloudius-systems.com:8080/job/scylla-master-ami-test/287/label=muninn/artifact/latest/job.log (FAILED)
http://jenkins.cloudius-systems.com:8080/job/scylla-master-ami-test/label=muninn/286/ (`PASS`, scylla-conf-666.development-0.20180916.9d27045c7.el7.x86_64, ami-0d29bac8c368c8985)

* Errors:
```
subprocess.CalledProcessError: Command '['mount', '-t', 'xfs', '-o', 'noatime,lazytime', '/dev/nvme0n1', '/var/lib/scylla']' returned non-zero exit status 32
[INFO] RAID Array containing ['nvme0n1'] not found. Creating...
subprocess.CalledProcessError: Command '['/usr/lib/scylla/scylla_raid_setup', '--raiddev', '/dev/md0', '--disks', '/dev/nvme0n1', '--root', '/var/lib/scylla', '--volume-role', 'all', '--update-fstab']' returned non-zero exit status 1
subprocess.CalledProcessError: Command '['/usr/lib/scylla/scylla-ami/scylla_create_devices']' returned non-zero exit status 1
```

* Scylla AMI Setup log:
```
2018-09-25 22:53:49,463 process          L0420 DEBUG| [stdout] Sep 25 22:49:48 ip-172-30-0-221.ec2.internal systemd[1]: Starting Scylla AMI Setup...
2018-09-25 22:53:49,463 process          L0420 DEBUG| [stdout] Sep 25 22:50:04 ip-172-30-0-195.ec2.internal scylla_ami_setup[1170]: Waiting for cloud-init to finish...
2018-09-25 22:53:49,463 process          L0420 DEBUG| [stdout] Sep 25 22:49:48 ip-172-30-0-221.ec2.internal systemd[1]: Starting Scylla AMI Setup...
2018-09-25 22:53:49,464 process          L0420 DEBUG| [stdout] Sep 25 22:50:04 ip-172-30-0-195.ec2.internal scylla_ami_setup[1170]: [INFO] No userdata found. Starting 1 node clusters, by default.
2018-09-25 22:53:49,464 process          L0420 DEBUG| [stdout] Sep 25 22:50:04 ip-172-30-0-195.ec2.internal scylla_ami_setup[1170]: [INFO] Using instance type: i3.large
2018-09-25 22:53:49,464 process          L0420 DEBUG| [stdout] Sep 25 22:50:04 ip-172-30-0-195.ec2.internal scylla_ami_setup[1170]: [INFO] meta-data:instance-type: i3.large
2018-09-25 22:53:49,464 process          L0420 DEBUG| [stdout] Sep 25 22:50:04 ip-172-30-0-195.ec2.internal scylla_ami_setup[1170]: [INFO] meta-data:local-ipv4: 172.30.0.195
2018-09-25 22:53:49,465 process          L0420 DEBUG| [stdout] Sep 25 22:50:04 ip-172-30-0-195.ec2.internal scylla_ami_setup[1170]: [INFO] meta-data:public-hostname: ec2-18-207-215-204.compute-1.amazonaws.com
2018-09-25 22:53:49,465 process          L0420 DEBUG| [stdout] Sep 25 22:50:04 ip-172-30-0-195.ec2.internal scylla_ami_setup[1170]: Waiting for cloud-init to finish...
2018-09-25 22:53:49,466 process          L0420 DEBUG| [stdout] Sep 25 22:50:04 ip-172-30-0-195.ec2.internal scylla_ami_setup[1170]: [INFO] meta-data:ami-launch-index: 0
2018-09-25 22:53:49,466 process          L0420 DEBUG| [stdout] Sep 25 22:50:04 ip-172-30-0-195.ec2.internal scylla_ami_setup[1170]: [INFO] No userdata found. Starting 1 node clusters, by default.
2018-09-25 22:53:49,466 process          L0420 DEBUG| [stdout] Sep 25 22:50:04 ip-172-30-0-195.ec2.internal scylla_ami_setup[1170]: [INFO] meta-data:reservation-id: r-0e07f78d8aedcf4f1
2018-09-25 22:53:49,466 process          L0420 DEBUG| [stdout] Sep 25 22:50:04 ip-172-30-0-195.ec2.internal scylla_ami_setup[1170]: [INFO] Using instance type: i3.large
2018-09-25 22:53:49,467 process          L0420 DEBUG| [stdout] Sep 25 22:50:04 ip-172-30-0-195.ec2.internal scylla_ami_setup[1170]: [INFO] Using cluster name: Test Cluster - No AMI Parameters
2018-09-25 22:53:49,467 process          L0420 DEBUG| [stdout] Sep 25 22:50:04 ip-172-30-0-195.ec2.internal scylla_ami_setup[1170]: [INFO] meta-data:instance-type: i3.large
2018-09-25 22:53:49,467 process          L0420 DEBUG| [stdout] Sep 25 22:50:04 ip-172-30-0-195.ec2.internal scylla_ami_setup[1170]: [INFO] Using cluster size: 1
2018-09-25 22:53:49,468 process          L0420 DEBUG| [stdout] Sep 25 22:50:04 ip-172-30-0-195.ec2.internal scylla_ami_setup[1170]: [INFO] meta-data:local-ipv4: 172.30.0.195
2018-09-25 22:53:49,468 process          L0420 DEBUG| [stdout] Sep 25 22:50:04 ip-172-30-0-195.ec2.internal scylla_ami_setup[1170]: [INFO] Using seed indexes: [0, 1, 1]
2018-09-25 22:53:49,468 process          L0420 DEBUG| [stdout] Sep 25 22:50:04 ip-172-30-0-195.ec2.internal scylla_ami_setup[1170]: [INFO] meta-data:public-hostname: ec2-18-207-215-204.compute-1.amazonaws.com
2018-09-25 22:53:49,468 process          L0420 DEBUG| [stdout] Sep 25 22:50:04 ip-172-30-0-195.ec2.internal scylla_ami_setup[1170]: [INFO] Reflector loop...
2018-09-25 22:53:49,469 process          L0420 DEBUG| [stdout] Sep 25 22:50:04 ip-172-30-0-195.ec2.internal scylla_ami_setup[1170]: [INFO] meta-data:ami-launch-index: 0
2018-09-25 22:53:49,469 process          L0420 DEBUG| [stdout] Sep 25 22:50:04 ip-172-30-0-195.ec2.internal scylla_ami_setup[1170]: [INFO] 09/25/18-22:50:04 Reflector: Received 1 of 1 responses from: [u'172.30.0.195']
2018-09-25 22:53:49,469 process          L0420 DEBUG| [stdout] Sep 25 22:50:04 ip-172-30-0-195.ec2.internal scylla_ami_setup[1170]: [INFO] meta-data:reservation-id: r-0e07f78d8aedcf4f1
2018-09-25 22:53:49,470 process          L0420 DEBUG| [stdout] Sep 25 22:50:04 ip-172-30-0-195.ec2.internal scylla_ami_setup[1170]: [INFO] scylla.yaml configured.
2018-09-25 22:53:49,470 process          L0420 DEBUG| [stdout] Sep 25 22:50:04 ip-172-30-0-195.ec2.internal scylla_ami_setup[1170]: [INFO] Using cluster name: Test Cluster - No AMI Parameters
2018-09-25 22:53:49,470 process          L0420 DEBUG| [stdout] Sep 25 22:50:05 ip-172-30-0-195.ec2.internal scylla_ami_setup[1170]: meta-data=/dev/nvme0n1           isize=512    agcount=4, agsize=28991699 blks
2018-09-25 22:53:49,470 process          L0420 DEBUG| [stdout] Sep 25 22:50:04 ip-172-30-0-195.ec2.internal scylla_ami_setup[1170]: [INFO] Using cluster size: 1
2018-09-25 22:53:49,471 process          L0420 DEBUG| [stdout] Sep 25 22:50:05 ip-172-30-0-195.ec2.internal scylla_ami_setup[1170]: =                       sectsz=512   attr=2, projid32bit=1
2018-09-25 22:53:49,471 process          L0420 DEBUG| [stdout] Sep 25 22:50:04 ip-172-30-0-195.ec2.internal scylla_ami_setup[1170]: [INFO] Using seed indexes: [0, 1, 1]
2018-09-25 22:53:49,471 process          L0420 DEBUG| [stdout] Sep 25 22:50:05 ip-172-30-0-195.ec2.internal scylla_ami_setup[1170]: =                       crc=1        finobt=0, sparse=0
2018-09-25 22:53:49,471 process          L0420 DEBUG| [stdout] Sep 25 22:50:04 ip-172-30-0-195.ec2.internal scylla_ami_setup[1170]: [INFO] Reflector loop...
2018-09-25 22:53:49,472 process          L0420 DEBUG| [stdout] Sep 25 22:50:05 ip-172-30-0-195.ec2.internal scylla_ami_setup[1170]: data     =                       bsize=4096   blocks=115966796, imaxpct=25
2018-09-25 22:53:49,472 process          L0420 DEBUG| [stdout] Sep 25 22:50:04 ip-172-30-0-195.ec2.internal scylla_ami_setup[1170]: [INFO] 09/25/18-22:50:04 Reflector: Received 1 of 1 responses from: [u'172.30.0.195']
2018-09-25 22:53:49,472 process          L0420 DEBUG| [stdout] Sep 25 22:50:05 ip-172-30-0-195.ec2.internal scylla_ami_setup[1170]: =                       sunit=0      swidth=0 blks
2018-09-25 22:53:49,472 process          L0420 DEBUG| [stdout] Sep 25 22:50:04 ip-172-30-0-195.ec2.internal scylla_ami_setup[1170]: [INFO] scylla.yaml configured.
2018-09-25 22:53:49,473 process          L0420 DEBUG| [stdout] Sep 25 22:50:05 ip-172-30-0-195.ec2.internal scylla_ami_setup[1170]: naming   =version 2              bsize=4096   ascii-ci=0 ftype=1
2018-09-25 22:53:49,473 process          L0420 DEBUG| [stdout] Sep 25 22:50:05 ip-172-30-0-195.ec2.internal scylla_ami_setup[1170]: meta-data=/dev/nvme0n1           isize=512    agcount=4, agsize=28991699 blks
2018-09-25 22:53:49,473 process          L0420 DEBUG| [stdout] Sep 25 22:50:05 ip-172-30-0-195.ec2.internal scylla_ami_setup[1170]: log      =internal log           bsize=4096   blocks=56624, version=2
2018-09-25 22:53:49,474 process          L0420 DEBUG| [stdout] Sep 25 22:50:05 ip-172-30-0-195.ec2.internal scylla_ami_setup[1170]: =                       sectsz=512   attr=2, projid32bit=1
2018-09-25 22:53:49,474 process          L0420 DEBUG| [stdout] Sep 25 22:50:05 ip-172-30-0-195.ec2.internal scylla_ami_setup[1170]: =                       sectsz=512   sunit=0 blks, lazy-count=1
2018-09-25 22:53:49,474 process          L0420 DEBUG| [stdout] Sep 25 22:50:05 ip-172-30-0-195.ec2.internal scylla_ami_setup[1170]: =                       crc=1        finobt=0, sparse=0
2018-09-25 22:53:49,474 process          L0420 DEBUG| [stdout] Sep 25 22:50:05 ip-172-30-0-195.ec2.internal scylla_ami_setup[1170]: realtime =none                   extsz=4096   blocks=0, rtextents=0
2018-09-25 22:53:49,475 process          L0420 DEBUG| [stdout] Sep 25 22:50:05 ip-172-30-0-195.ec2.internal scylla_ami_setup[1170]: data     =                       bsize=4096   blocks=115966796, imaxpct=25
2018-09-25 22:53:49,475 process          L0420 DEBUG| [stdout] Sep 25 22:50:05 ip-172-30-0-195.ec2.internal scylla_ami_setup[1170]: mount: wrong fs type, bad option, bad superblock on /dev/nvme0n1,
2018-09-25 22:53:49,475 process          L0420 DEBUG| [stdout] Sep 25 22:50:05 ip-172-30-0-195.ec2.internal scylla_ami_setup[1170]: =                       sunit=0      swidth=0 blks
2018-09-25 22:53:49,475 process          L0420 DEBUG| [stdout] Sep 25 22:50:05 ip-172-30-0-195.ec2.internal scylla_ami_setup[1170]: missing codepage or helper program, or other error
2018-09-25 22:53:49,476 process          L0420 DEBUG| [stdout] Sep 25 22:50:05 ip-172-30-0-195.ec2.internal scylla_ami_setup[1170]: naming   =version 2              bsize=4096   ascii-ci=0 ftype=1
2018-09-25 22:53:49,476 process          L0420 DEBUG| [stdout] Sep 25 22:50:05 ip-172-30-0-195.ec2.internal scylla_ami_setup[1170]: In some cases useful info is found in syslog - try
2018-09-25 22:53:49,476 process          L0420 DEBUG| [stdout] Sep 25 22:50:05 ip-172-30-0-195.ec2.internal scylla_ami_setup[1170]: log      =internal log           bsize=4096   blocks=56624, version=2
2018-09-25 22:53:49,476 process          L0420 DEBUG| [stdout] Sep 25 22:50:05 ip-172-30-0-195.ec2.internal scylla_ami_setup[1170]: dmesg | tail or so.
2018-09-25 22:53:49,477 process          L0420 DEBUG| [stdout] Sep 25 22:50:05 ip-172-30-0-195.ec2.internal scylla_ami_setup[1170]: =                       sectsz=512   sunit=0 blks, lazy-count=1
2018-09-25 22:53:49,477 process          L0420 DEBUG| [stdout] Sep 25 22:50:05 ip-172-30-0-195.ec2.internal scylla_ami_setup[1170]: Creating XFS volume for scylla using 1 disk(s): /dev/nvme0n1
2018-09-25 22:53:49,477 process          L0420 DEBUG| [stdout] Sep 25 22:50:05 ip-172-30-0-195.ec2.internal scylla_ami_setup[1170]: realtime =none                   extsz=4096   blocks=0, rtextents=0
2018-09-25 22:53:49,477 process          L0420 DEBUG| [stdout] Sep 25 22:50:05 ip-172-30-0-195.ec2.internal scylla_ami_setup[1170]: Traceback (most recent call last):
2018-09-25 22:53:49,478 process          L0420 DEBUG| [stdout] Sep 25 22:50:05 ip-172-30-0-195.ec2.internal scylla_ami_setup[1170]: mount: wrong fs type, bad option, bad superblock on /dev/nvme0n1,
2018-09-25 22:53:49,478 process          L0420 DEBUG| [stdout] Sep 25 22:50:05 ip-172-30-0-195.ec2.internal scylla_ami_setup[1170]: File "/usr/lib/scylla/scylla_raid_setup", line 131, in <module>
2018-09-25 22:53:49,478 process          L0420 DEBUG| [stdout] Sep 25 22:50:05 ip-172-30-0-195.ec2.internal scylla_ami_setup[1170]: missing codepage or helper program, or other error
2018-09-25 22:53:49,478 process          L0420 DEBUG| [stdout] Sep 25 22:50:05 ip-172-30-0-195.ec2.internal scylla_ami_setup[1170]: run('mount -t xfs -o noatime,lazytime {raid} "{mount_at}"'.format(raid=fsdev, mount_at=mount_at))
2018-09-25 22:53:49,479 process          L0420 DEBUG| [stdout] Sep 25 22:50:05 ip-172-30-0-195.ec2.internal scylla_ami_setup[1170]: In some cases useful info is found in syslog - try
2018-09-25 22:53:49,479 process          L0420 DEBUG| [stdout] Sep 25 22:50:05 ip-172-30-0-195.ec2.internal scylla_ami_setup[1170]: File "/usr/lib/scylla/scylla_util.py", line 263, in run
2018-09-25 22:53:49,479 process          L0420 DEBUG| [stdout] Sep 25 22:50:05 ip-172-30-0-195.ec2.internal scylla_ami_setup[1170]: dmesg | tail or so.
2018-09-25 22:53:49,479 process          L0420 DEBUG| [stdout] Sep 25 22:50:05 ip-172-30-0-195.ec2.internal scylla_ami_setup[1170]: return subprocess.check_call(cmd, shell=shell, stdout=stdout, stderr=stderr)
2018-09-25 22:53:49,480 process          L0420 DEBUG| [stdout] Sep 25 22:50:05 ip-172-30-0-195.ec2.internal scylla_ami_setup[1170]: Creating XFS volume for scylla using 1 disk(s): /dev/nvme0n1
2018-09-25 22:53:49,480 process          L0420 DEBUG| [stdout] Sep 25 22:50:05 ip-172-30-0-195.ec2.internal scylla_ami_setup[1170]: File "/usr/lib64/python3.4/subprocess.py", line 558, in check_call
2018-09-25 22:53:49,480 process          L0420 DEBUG| [stdout] Sep 25 22:50:05 ip-172-30-0-195.ec2.internal scylla_ami_setup[1170]: Traceback (most recent call last):
2018-09-25 22:53:49,480 process          L0420 DEBUG| [stdout] Sep 25 22:50:05 ip-172-30-0-195.ec2.internal scylla_ami_setup[1170]: raise CalledProcessError(retcode, cmd)
2018-09-25 22:53:49,481 process          L0420 DEBUG| [stdout] Sep 25 22:50:05 ip-172-30-0-195.ec2.internal scylla_ami_setup[1170]: File "/usr/lib/scylla/scylla_raid_setup", line 131, in <module>
2018-09-25 22:53:49,481 process          L0420 DEBUG| [stdout] Sep 25 22:50:05 ip-172-30-0-195.ec2.internal scylla_ami_setup[1170]: run('mount -t xfs -o noatime,lazytime {raid} "{mount_at}"'.format(raid=fsdev, mount_at=mount_at))
2018-09-25 22:53:49,481 process          L0420 DEBUG| [stdout] Sep 25 22:50:05 ip-172-30-0-195.ec2.internal scylla_ami_setup[1170]: subprocess.CalledProcessError: Command '['mount', '-t', 'xfs', '-o', 'noatime,lazytime', '/dev/nvme0n1', '/var/lib/scylla']' returned non-zero exit status 32
2018-09-25 22:53:49,481 process          L0420 DEBUG| [stdout] Sep 25 22:50:05 ip-172-30-0-195.ec2.internal scylla_ami_setup[1170]: File "/usr/lib/scylla/scylla_util.py", line 263, in run
2018-09-25 22:53:49,482 process          L0420 DEBUG| [stdout] Sep 25 22:50:05 ip-172-30-0-195.ec2.internal scylla_ami_setup[1170]: [INFO] RAID Array containing ['nvme0n1'] not found. Creating...
2018-09-25 22:53:49,482 process          L0420 DEBUG| [stdout] Sep 25 22:50:05 ip-172-30-0-195.ec2.internal scylla_ami_setup[1170]: return subprocess.check_call(cmd, shell=shell, stdout=stdout, stderr=stderr)
2018-09-25 22:53:49,482 process          L0420 DEBUG| [stdout] Sep 25 22:50:05 ip-172-30-0-195.ec2.internal scylla_ami_setup[1170]: Traceback (most recent call last):
2018-09-25 22:53:49,482 process          L0420 DEBUG| [stdout] Sep 25 22:50:05 ip-172-30-0-195.ec2.internal scylla_ami_setup[1170]: File "/usr/lib64/python3.4/subprocess.py", line 558, in check_call
2018-09-25 22:53:49,483 process          L0420 DEBUG| [stdout] Sep 25 22:50:05 ip-172-30-0-195.ec2.internal scylla_ami_setup[1170]: File "/usr/lib/scylla/scylla-ami/scylla_create_devices", line 175, in <module>
2018-09-25 22:53:49,483 process          L0420 DEBUG| [stdout] Sep 25 22:50:05 ip-172-30-0-195.ec2.internal scylla_ami_setup[1170]: raise CalledProcessError(retcode, cmd)
2018-09-25 22:53:49,483 process          L0420 DEBUG| [stdout] Sep 25 22:50:05 ip-172-30-0-195.ec2.internal scylla_ami_setup[1170]: get_disk_bundles()
2018-09-25 22:53:49,483 process          L0420 DEBUG| [stdout] Sep 25 22:50:05 ip-172-30-0-195.ec2.internal scylla_ami_setup[1170]: subprocess.CalledProcessError: Command '['mount', '-t', 'xfs', '-o', 'noatime,lazytime', '/dev/nvme0n1', '/var/lib/scylla']' returned non-zero exit status 32
2018-09-25 22:53:49,484 process          L0420 DEBUG| [stdout] Sep 25 22:50:05 ip-172-30-0-195.ec2.internal scylla_ami_setup[1170]: File "/usr/lib/scylla/scylla-ami/scylla_create_devices", line 171, in get_disk_bundles
2018-09-25 22:53:49,484 process          L0420 DEBUG| [stdout] Sep 25 22:50:05 ip-172-30-0-195.ec2.internal scylla_ami_setup[1170]: [INFO] RAID Array containing ['nvme0n1'] not found. Creating...
2018-09-25 22:53:49,484 process          L0420 DEBUG| [stdout] Sep 25 22:50:05 ip-172-30-0-195.ec2.internal scylla_ami_setup[1170]: config_array(t, typemap[t], role[t], mdidx)
2018-09-25 22:53:49,484 process          L0420 DEBUG| [stdout] Sep 25 22:50:05 ip-172-30-0-195.ec2.internal scylla_ami_setup[1170]: Traceback (most recent call last):
2018-09-25 22:53:49,484 process          L0420 DEBUG| [stdout] Sep 25 22:50:05 ip-172-30-0-195.ec2.internal scylla_ami_setup[1170]: File "/usr/lib/scylla/scylla-ami/scylla_create_devices", line 60, in config_array
2018-09-25 22:53:49,485 process          L0420 DEBUG| [stdout] Sep 25 22:50:05 ip-172-30-0-195.ec2.internal scylla_ami_setup[1170]: "--update-fstab"])
2018-09-25 22:53:49,485 process          L0420 DEBUG| [stdout] Sep 25 22:50:05 ip-172-30-0-195.ec2.internal scylla_ami_setup[1170]: File "/usr/lib64/python2.7/subprocess.py", line 542, in check_call
2018-09-25 22:53:49,485 process          L0420 DEBUG| [stdout] Sep 25 22:50:05 ip-172-30-0-195.ec2.internal scylla_ami_setup[1170]: File "/usr/lib/scylla/scylla-ami/scylla_create_devices", line 175, in <module>
2018-09-25 22:53:49,485 process          L0420 DEBUG| [stdout] Sep 25 22:50:05 ip-172-30-0-195.ec2.internal scylla_ami_setup[1170]: raise CalledProcessError(retcode, cmd)
2018-09-25 22:53:49,486 process          L0420 DEBUG| [stdout] Sep 25 22:50:05 ip-172-30-0-195.ec2.internal scylla_ami_setup[1170]: subprocess.CalledProcessError: Command '['/usr/lib/scylla/scylla_raid_setup', '--raiddev', '/dev/md0', '--disks', '/dev/nvme0n1', '--root', '/var/lib/scylla', '--volume-role', 'all', '--update-fstab']' returned non-zero exit status 1
2018-09-25 22:53:49,486 process          L0420 DEBUG| [stdout] Sep 25 22:50:05 ip-172-30-0-195.ec2.internal scylla_ami_setup[1170]: get_disk_bundles()
2018-09-25 22:53:49,486 process          L0420 DEBUG| [stdout] Sep 25 22:50:05 ip-172-30-0-195.ec2.internal scylla_ami_setup[1170]: File "/usr/lib/scylla/scylla-ami/scylla_create_devices", line 171, in get_disk_bundles
2018-09-25 22:53:49,487 process          L0420 DEBUG| [stdout] Sep 25 22:50:05 ip-172-30-0-195.ec2.internal scylla_ami_setup[1170]: config_array(t, typemap[t], role[t], mdidx)
2018-09-25 22:53:49,486 process          L0420 DEBUG| [stdout] Sep 25 22:50:05 ip-172-30-0-195.ec2.internal scylla_ami_setup[1170]: Traceback (most recent call last):
2018-09-25 22:53:49,487 process          L0420 DEBUG| [stdout] Sep 25 22:50:05 ip-172-30-0-195.ec2.internal scylla_ami_setup[1170]: File "/usr/lib/scylla/scylla-ami/scylla_create_devices", line 60, in config_array
2018-09-25 22:53:49,487 process          L0420 DEBUG| [stdout] Sep 25 22:50:05 ip-172-30-0-195.ec2.internal scylla_ami_setup[1170]: File "/usr/lib/scylla/scylla-ami/scylla_ami_setup", line 32, in <module>
2018-09-25 22:53:49,487 process          L0420 DEBUG| [stdout] Sep 25 22:50:05 ip-172-30-0-195.ec2.internal scylla_ami_setup[1170]: "--update-fstab"])
2018-09-25 22:53:49,488 process          L0420 DEBUG| [stdout] Sep 25 22:50:05 ip-172-30-0-195.ec2.internal scylla_ami_setup[1170]: run('/usr/lib/scylla/scylla-ami/scylla_create_devices')
2018-09-25 22:53:49,488 process          L0420 DEBUG| [stdout] Sep 25 22:50:05 ip-172-30-0-195.ec2.internal scylla_ami_setup[1170]: File "/usr/lib64/python2.7/subprocess.py", line 542, in check_call
2018-09-25 22:53:49,488 process          L0420 DEBUG| [stdout] Sep 25 22:50:05 ip-172-30-0-195.ec2.internal scylla_ami_setup[1170]: File "/usr/lib/scylla/scylla_util.py", line 263, in run
2018-09-25 22:53:49,489 process          L0420 DEBUG| [stdout] Sep 25 22:50:05 ip-172-30-0-195.ec2.internal scylla_ami_setup[1170]: raise CalledProcessError(retcode, cmd)
2018-09-25 22:53:49,489 process          L0420 DEBUG| [stdout] Sep 25 22:50:05 ip-172-30-0-195.ec2.internal scylla_ami_setup[1170]: return subprocess.check_call(cmd, shell=shell, stdout=stdout, stderr=stderr)
2018-09-25 22:53:49,489 process          L0420 DEBUG| [stdout] Sep 25 22:50:05 ip-172-30-0-195.ec2.internal scylla_ami_setup[1170]: subprocess.CalledProcessError: Command '['/usr/lib/scylla/scylla_raid_setup', '--raiddev', '/dev/md0', '--disks', '/dev/nvme0n1', '--root', '/var/lib/scylla', '--volume-role', 'all', '--update-fstab']' returned non-zero exit status 1
2018-09-25 22:53:49,489 process          L0420 DEBUG| [stdout] Sep 25 22:50:05 ip-172-30-0-195.ec2.internal scylla_ami_setup[1170]: File "/usr/lib64/python3.4/subprocess.py", line 558, in check_call
2018-09-25 22:53:49,490 process          L0420 DEBUG| [stdout] Sep 25 22:50:05 ip-172-30-0-195.ec2.internal scylla_ami_setup[1170]: raise CalledProcessError(retcode, cmd)
2018-09-25 22:53:49,490 process          L0420 DEBUG| [stdout] Sep 25 22:50:05 ip-172-30-0-195.ec2.internal scylla_ami_setup[1170]: Traceback (most recent call last):
2018-09-25 22:53:49,490 process          L0420 DEBUG| [stdout] Sep 25 22:50:05 ip-172-30-0-195.ec2.internal scylla_ami_setup[1170]: subprocess.CalledProcessError: Command '['/usr/lib/scylla/scylla-ami/scylla_create_devices']' returned non-zero exit status 1
2018-09-25 22:53:49,490 process          L0420 DEBUG| [stdout] Sep 25 22:50:05 ip-172-30-0-195.ec2.internal scylla_ami_setup[1170]: File "/usr/lib/scylla/scylla-ami/scylla_ami_setup", line 32, in <module>
2018-09-25 22:53:49,490 process          L0420 DEBUG| [stdout] Sep 25 22:50:05 ip-172-30-0-195.ec2.internal systemd[1]: scylla-ami-setup.service: main process exited, code=exited, status=1/FAILURE
2018-09-25 22:53:49,491 process          L0420 DEBUG| [stdout] Sep 25 22:50:05 ip-172-30-0-195.ec2.internal scylla_ami_setup[1170]: run('/usr/lib/scylla/scylla-ami/scylla_create_devices')
2018-09-25 22:53:49,491 process          L0420 DEBUG| [stdout] Sep 25 22:50:05 ip-172-30-0-195.ec2.internal systemd[1]: Failed to start Scylla AMI Setup.
2018-09-25 22:53:49,491 process          L0420 DEBUG| [stdout] Sep 25 22:50:05 ip-172-30-0-195.ec2.internal scylla_ami_setup[1170]: File "/usr/lib/scylla/scylla_util.py", line 263, in run
2018-09-25 22:53:49,492 process          L0420 DEBUG| [stdout] Sep 25 22:50:05 ip-172-30-0-195.ec2.internal systemd[1]: Dependency failed for Scylla Server.
2018-09-25 22:53:49,492 process          L0420 DEBUG| [stdout] Sep 25 22:50:05 ip-172-30-0-195.ec2.internal scylla_ami_setup[1170]: return subprocess.check_call(cmd, shell=shell, stdout=stdout, stderr=stderr)
2018-09-25 22:53:49,492 process          L0420 DEBUG| [stdout] Sep 25 22:50:05 ip-172-30-0-195.ec2.internal systemd[1]: Dependency failed for Scylla JMX.
2018-09-25 22:53:49,492 process          L0420 DEBUG| [stdout] Sep 25 22:50:05 ip-172-30-0-195.ec2.internal scylla_ami_setup[1170]: File "/usr/lib64/python3.4/subprocess.py", line 558, in check_call
2018-09-25 22:53:49,493 process          L0420 DEBUG| [stdout] Sep 25 22:50:05 ip-172-30-0-195.ec2.internal systemd[1]: Job scylla-jmx.service/start failed with result 'dependency'.
2018-09-25 22:53:49,493 process          L0420 DEBUG| [stdout] Sep 25 22:50:05 ip-172-30-0-195.ec2.internal scylla_ami_setup[1170]: raise CalledProcessError(retcode, cmd)
2018-09-25 22:53:49,493 process          L0420 DEBUG| [stdout] Sep 25 22:50:05 ip-172-30-0-195.ec2.internal systemd[1]: Job scylla-server.service/start failed with result 'dependency'.
2018-09-25 22:53:49,493 process          L0420 DEBUG| [stdout] Sep 25 22:50:05 ip-172-30-0-195.ec2.internal systemd[1]: Unit scylla-ami-setup.service entered failed state.
2018-09-25 22:53:49,493 process          L0420 DEBUG| [stdout] Sep 25 22:50:05 ip-172-30-0-195.ec2.internal scylla_ami_setup[1170]: subprocess.CalledProcessError: Command '['/usr/lib/scylla/scylla-ami/scylla_create_devices']' returned non-zero exit status 1
2018-09-25 22:53:49,494 process          L0420 DEBUG| [stdout] Sep 25 22:50:05 ip-172-30-0-195.ec2.internal systemd[1]: scylla-ami-setup.service failed.
2018-09-25 22:53:49,494 process          L0420 DEBUG| [stdout] Sep 25 22:50:05 ip-172-30-0-195.ec2.internal systemd[1]: scylla-ami-setup.service: main process exited, code=exited, status=1/FAILURE
2018-09-25 22:53:49,494 process          L0420 DEBUG| [stdout] Sep 25 22:50:05 ip-172-30-0-195.ec2.internal systemd[1]: Failed to start Scylla AMI Setup.
2018-09-25 22:53:49,494 process          L0420 DEBUG| [stdout] Sep 25 22:50:05 ip-172-30-0-195.ec2.internal systemd[1]: Dependency failed for Scylla Server.
2018-09-25 22:53:49,494 process          L0420 DEBUG| [stdout] Sep 25 22:50:05 ip-172-30-0-195.ec2.internal systemd[1]: Dependency failed for Scylla JMX.
2018-09-25 22:53:49,494 process          L0420 DEBUG| [stdout] Sep 25 22:50:05 ip-172-30-0-195.ec2.internal systemd[1]: Job scylla-jmx.service/start failed with result 'dependency'.
2018-09-25 22:53:49,495 process          L0420 DEBUG| [stdout] Sep 25 22:50:05 ip-172-30-0-195.ec2.internal systemd[1]: Job scylla-server.service/start failed with result 'dependency'.
2018-09-25 22:53:49,495 process          L0420 DEBUG| [stdout] Sep 25 22:50:05 ip-172-30-0-195.ec2.internal systemd[1]: Unit scylla-ami-setup.service entered failed state.
2018-09-25 22:53:49,495 process          L0420 DEBUG| [stdout] Sep 25 22:50:05 ip-172-30-0-195.ec2.internal systemd[1]: scylla-ami-setup.service failed.
2018-09-25 22:53:49,495 service          L0584 DEBUG| Setting ignore_status to True.
2018-09-25 22:53:49,495 process          L0333 INFO | Running 'systemctl status scylla-server.service'
2018-09-25 22:53:49,505 process          L0420 DEBUG| [stdout] â— scylla-server.service - Scylla Server
```

**Comment by syuu1228** [comment] 2018-09-26 15:15
```
$ dmesg|grep lazytime
[   43.396445] XFS (nvme0n1): unknown mount option [lazytime].
$ uname -r
4.18.9-1.el7.elrepo.x86_64
```

Looks like AMI's kernel does not supported lazytime mount option.
I suppose we have to optout the option by argument --no-lazytime or something.

@avikivity do you have any idea with this?

**Comment by denesb** [comment] 2018-09-27 07:27
Duplicate of https://github.com/scylladb/scylla/issues/3784 (although I'm not sure which was opened first).

**Comment by avikivity** [comment] 2018-09-27 07:49
Closing as duplicate (and fixed).

**Closed by avikivity** 2018-09-27 07:49 UTC
