### ISSUE TITLE
order of keys is not applied for multiget IN

### ISSUE THREAD

**Issue by abvgedeika** [scylladb/scylla#2574] opened 2017-07-11 19:51 UTC
*Installation details*
Scylla version (or git commit hash): https://github.com/scylladb/scylla/commit/d177ec05cb0c5a451a1a5b93646d3a35d2a6cc0b

tests: limit_multiget_test & in_order_by_without_selecting_test
https://github.com/scylladb/scylla-dtest/blob/master/cql_additional_tests.py#L411-L437
https://github.com/scylladb/scylla-dtest/blob/master/cql_additional_tests.py#L4187-L4208

```
        session.execute("""
            CREATE TABLE clicks (
                userid int,
                url text,
                time bigint,
                PRIMARY KEY (userid, url)
            ) WITH COMPACT STORAGE;
        """)

        # Inserts
        for id in xrange(0, 100):
            for tld in ['com', 'org', 'net']:
                session.execute("INSERT INTO clicks (userid, url, time) VALUES (%i, 'http://foo.%s', 42)" % (id, tld))

        # Check that we do limit the output to 1 *and* that we respect query
        # order of keys (even though 48 is after 2)
        res = session.execute("SELECT * FROM clicks WHERE userid IN (48, 2) LIMIT 1")
        if self.cluster.version() >= '2.2':  # Scylla reports 2.1, but has 2.2 behavior.
            assert rows_to_list(res) == [[2, 'http://foo.com', 42]], list(res)
        else:
            assert rows_to_list(res) == [[48, 'http://foo.com', 42]], list(res)
```
actual result:
[[48, 'http://foo.com', 42]]

expected behaviour for current 3.0 version:
[[2, 'http://foo.com', 42]]

**Comment by tgrabiec** [comment] 2017-07-12 07:17
Duplicate of #2029

**Closed by tgrabiec** 2017-07-12 07:17 UTC
