### ISSUE TITLE
Many timeouts starting during repair (alternator) 

### ISSUE THREAD

**Issue by shoshan** [scylladb/scylla#8808] opened 2021-06-06 11:32 UTC
*Installation details*
Kernel version: `5.4.0-1035-aws`
Scylla version (or git commit hash): `4.5.rc2-0.20210531.d92a26636`
Cluster size: 6 nodes (i3.4xlarge)
Scylla running with shards number (live nodes):
   alternator-3h-4-5-db-node-69bf85c8-1 (13.49.70.242 | 10.0.1.191): 14 shards
   alternator-3h-4-5-db-node-69bf85c8-2 (13.51.48.126 | 10.0.0.252): 14 shards
   alternator-3h-4-5-db-node-69bf85c8-3 (13.49.245.123 | 10.0.0.175): 14 shards
   alternator-3h-4-5-db-node-69bf85c8-4 (13.53.214.80 | 10.0.0.226): 14 shards
   alternator-3h-4-5-db-node-69bf85c8-5 (13.48.177.237 | 10.0.0.201): 14 shards
   alternator-3h-4-5-db-node-69bf85c8-7 (13.51.242.73 | 10.0.0.191): 14 shards
Scylla running with shards number (terminated nodes):
   alternator-3h-4-5-db-node-69bf85c8-6 (13.51.159.242 | 10.0.2.114): 14 shards
OS (RHEL/CentOS/Ubuntu/AWS AMI): `ami-0741e1533671810ef` (aws: eu-north-1)

Test: `longevity-alternator-3h-test`
Test name: `longevity_test.LongevityTest.test_custom_time`
Test config file(s):
- [longevity-alternator-3h.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/d1ae0d0636d6781d168fc6fc1a6932f0638c3827/test-cases/longevity/longevity-alternator-3h.yaml)

Many timeouts starting during repair (alternator)

====================================
Test did ManagementRepair Nemesis:
```
< t:2021-06-01 01:00:52,143 f:file_logger.py  l:80   c:sdcm.sct_events.file_logger p:INFO  > 2021-06-01 01:00:52.129: (DisruptionEvent Severity.NORMAL): type=ManagementRepair subtype=end target_node=Node alternator-3h-4-5-db-node-69bf85c8-5 [13.48.177.237 | 10.0.0.201] (seed: False) duration=389
< t:2021-06-01 00:54:21,925 f:file_logger.py  l:80   c:sdcm.sct_events.file_logger p:INFO  > 2021-06-01 00:54:21.921: (DisruptionEvent Severity.NORMAL): type=ManagementRepair subtype=start target_node=Node alternator-3h-4-5-db-node-69bf85c8-5 [13.48.177.237 | 10.0.0.201] (seed: False) duration=None
< t:2021-06-01 00:54:42,768 f:remote_base.py  l:520  c:RemoteCmdRunner      p:DEBUG > Running command "sudo sctool repair -c 9707f5ef-eb23-4bd9-a4c8-b8fae519d219"...

```

Screenshot of failing reads, writes:
![alternator_failing reads_writes](https://user-images.githubusercontent.com/99000/120922379-72b71e00-c6d1-11eb-8308-99a95e8ea499.png)

Link to  Graphana screen shot
https://cloudius-jenkins-test.s3.amazonaws.com/69bf85c8-048d-4416-b5e9-335d3971831a/20210601_011658/grafana-screenshot-longevity-alternator-3h-test-scylla-per-server-metrics-nemesis-20210601_012106-alternator-3h-4-5-monitor-node-69bf85c8-1.png

Failure notification:
```
2021-06-01 01:04:30.141: (CassandraStressLogEvent Severity.CRITICAL): type=OperationOnKey regex=Operation x10 on key\(s\) \[ line_number=2697 node=Node alternator-3h-4-5-loader-node-69bf85c8-3 [13.49.65.131 | 10.0.2.233] (seed: False)
java.io.IOException: Operation x10 on key(s) [4f3035394f304b353631]: Error executing: (WriteFailureException): Cassandra failure during write query at consistency QUORUM (2 responses were required but only 1 replica responded, 1 failed)
2021-06-01 01:04:45.997: (CassandraStressLogEvent Severity.CRITICAL): type=OperationOnKey regex=Operation x10 on key\(s\) \[ line_number=2763 node=Node alternator-3h-4-5-loader-node-69bf85c8-3 [13.49.65.131 | 10.0.2.233] (seed: False)
java.io.IOException: Operation x10 on key(s) [4f4e4c38394d50363330]: Error executing: (WriteFailureException): Cassandra failure during write query at consistency QUORUM (2 responses were required but only 1 replica responded, 1 failed)
2021-06-01 01:04:46.358: (CassandraStressLogEvent Severity.CRITICAL): type=OperationOnKey regex=Operation x10 on key\(s\) \[ line_number=2771 node=Node alternator-3h-4-5-loader-node-69bf85c8-3 [13.49.65.131 | 10.0.2.233] (seed: False)
java.io.IOException: Operation x10 on key(s) [503030343550394c4c30]: Error executing: (WriteFailureException): Cassandra failure during write query at consistency QUORUM (2 responses were required but only 1 replica responded, 1 failed)
```

====================================

Restore Monitor Stack command: `$ hydra investigate show-monitor 69bf85c8-048d-4416-b5e9-335d3971831a`
Show all stored logs command: `$ hydra investigate show-logs 69bf85c8-048d-4416-b5e9-335d3971831a`

Test id: `69bf85c8-048d-4416-b5e9-335d3971831a`

Logs:
grafana - [https://cloudius-jenkins-test.s3.amazonaws.com/69bf85c8-048d-4416-b5e9-335d3971831a/20210601_011658/grafana-screenshot-longevity-alternator-3h-test-scylla-per-server-metrics-nemesis-20210601_012106-alternator-3h-4-5-monitor-node-69bf85c8-1.png](https://cloudius-jenkins-test.s3.amazonaws.com/69bf85c8-048d-4416-b5e9-335d3971831a/20210601_011658/grafana-screenshot-longevity-alternator-3h-test-scylla-per-server-metrics-nemesis-20210601_012106-alternator-3h-4-5-monitor-node-69bf85c8-1.png)
db-cluster - [https://cloudius-jenkins-test.s3.amazonaws.com/69bf85c8-048d-4416-b5e9-335d3971831a/20210601_052030/db-cluster-69bf85c8.zip](https://cloudius-jenkins-test.s3.amazonaws.com/69bf85c8-048d-4416-b5e9-335d3971831a/20210601_052030/db-cluster-69bf85c8.zip)
loader-set - [https://cloudius-jenkins-test.s3.amazonaws.com/69bf85c8-048d-4416-b5e9-335d3971831a/20210601_052030/loader-set-69bf85c8.zip](https://cloudius-jenkins-test.s3.amazonaws.com/69bf85c8-048d-4416-b5e9-335d3971831a/20210601_052030/loader-set-69bf85c8.zip)
monitor-set - [https://cloudius-jenkins-test.s3.amazonaws.com/69bf85c8-048d-4416-b5e9-335d3971831a/20210601_052030/monitor-set-69bf85c8.zip](https://cloudius-jenkins-test.s3.amazonaws.com/69bf85c8-048d-4416-b5e9-335d3971831a/20210601_052030/monitor-set-69bf85c8.zip)
sct-runner - [https://cloudius-jenkins-test.s3.amazonaws.com/69bf85c8-048d-4416-b5e9-335d3971831a/20210601_052030/sct-runner-69bf85c8.zip](https://cloudius-jenkins-test.s3.amazonaws.com/69bf85c8-048d-4416-b5e9-335d3971831a/20210601_052030/sct-runner-69bf85c8.zip)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-4.5/job/longevity/job/longevity-alternator-3h-test/20/)

**Comment by roydahan** [comment] 2021-06-08 10:17
@nyh any additional info that we can add to this issue?
(@yarongilor FYI)

**Comment by nyh** [comment] 2021-06-08 10:46
I don't know what else to say about this except that it's probably not specific to Alternator - the writes are LWT writes (unless you chose some other write isolation option), but the reads are normal reads (with CL=LOCAL_ONE or LOCAL_QUORUM depending on the consistency option in the request).

What I don't like, and it looks the same as in #8809, is that instead of a timeout the internal Scylla code is reporting a "failure". Is failure different from a timeout? I am guessing from the metrics you showed that those were regular timeouts, but why is it reported as a failure - and if it's a failure, why don't we add a few words about what kind of failure this is?

**Comment by yarongilor** [comment] 2021-06-08 11:18
> I don't know what else to say about this except that it's probably not specific to Alternator - the writes are LWT writes (unless you chose some other write isolation option), but the reads are normal reads (with CL=LOCAL_ONE or LOCAL_QUORUM depending on the consistency option in the request).
> 
> What I don't like, and it looks the same as in #8809, is that instead of a timeout the internal Scylla code is reporting a "failure". Is failure different from a timeout? I am guessing from the metrics you showed that those were regular timeouts, but why is it reported as a failure - and if it's a failure, why don't we add a few words about what kind of failure this is?

i'm not sure what's the exact scenario here. i see c-s error but it's Alternator test. is it c-s run during a specific nemesis?
i see c-s failed for what looks like a retry failures exceeded:
```
java.io.IOException: Operation x10 on key(s) [503030343550394c4c30]: Error executing: (WriteFailureException): Cassandra failure
```
 in #8809   the number of timeouts might didn't get to such a threshold or it is just a different implementation of YCSB.

**Comment by roydahan** [comment] 2021-06-08 13:41
@yarongilor in the simple alternator longevity (3h) we have also a simple c-s workload to test cql in parallel to alternator.
It seems that when the ManagementRepair nemesis started, many timeouts have started causing the c-s stress to fail (otherwise we probably wouldn't even notice it).

@shoshan do you see also reactor stalls at that time?

**Comment by shoshan** [comment] 2021-06-14 11:26
@roydahan  There are no reactor stall reports during times of failures "regex=Operation x10 on key"

**Comment by roydahan** [comment] 2021-06-22 10:43
@yarongilor / @nyh This test is failing consistently, at some point during one of the nemesis (I don't think it's bound to repair, in the last run it happened during decommission), timeouts are starting to accumulate until the c-s fails.

**Comment by roydahan** [comment] 2021-06-22 10:53
I checked one run in 4.4 (maybe need to check more) and saw that this issue didn't happen, so considering this as a regression.

**Comment by nyh** [comment] 2021-06-22 11:02
@roydahan you said that "this test is failing consistently", so is it possible to try simplify the scenario and find what is relevant and what is not? Does it happen only during repair (or decommission, which if I understand correctly since recently uses the same repair code, right @asias ?) - or also without repair? Does it happen only when Alternator is involved or also when just the CQL cassandra-stress is running? Because right now this issue is so generic, I don't have any guess what to look at.

**Comment by asias** [comment] 2021-06-22 11:29
> @roydahan you said that "this test is failing consistently", so is it possible to try simplify the scenario and find what is relevant and what is not? Does it happen only during repair (or decommission, which if I understand correctly since recently uses the same repair code, right @asias ?) - or also without repair? Does it happen only when Alternator is involved or also when just the CQL cassandra-stress is running? Because right now this issue is so generic, I don't have any guess what to look at.

By default, node operations are not using repair yet.

**Comment by roydahan** [comment] 2021-06-22 15:48
> @roydahan you said that "this test is failing consistently", so is it possible to try simplify the scenario and find what is relevant and what is not? Does it happen only during repair (or decommission, which if I understand correctly since recently uses the same repair code, right @asias ?) - or also without repair? Does it happen only when Alternator is involved or also when just the CQL cassandra-stress is running? Because right now this issue is so generic, I don't have any guess what to look at.

I don't know hoe to simplfy the scenario more than "run this load + this nemesis".
It happens only in the alternator test.
It happens for c-s load that does CQL in parallel to the ycsb that runs the alternator load.

**Comment by bhalevy** [comment] 2021-07-05 14:32
@kostja I see bursts of timeout errors from CAS.
Is this a known issue by any chance?
This issue is blocking the 4.5 release, so please handle in high priority.  Thanks!

For example:
```
2021-06-01T00:33:45+00:00  alternator-3h-4-5-db-node-69bf85c8-1 !ERR     | scylla:  [shard 5] paxos - CAS[150390] prune: failed exceptions::mutation_write_timeout_exception (Operation timed out for system.paxos - received only 0 responses from 1 CL=ONE.)
2021-06-01T00:33:45+00:00  alternator-3h-4-5-db-node-69bf85c8-1 !ERR     | scylla:  [shard 5] paxos - CAS[150391] prune: failed exceptions::mutation_write_timeout_exception (Operation timed out for system.paxos - received only 0 responses from 1 CL=ONE.)
2021-06-01T00:33:45+00:00  alternator-3h-4-5-db-node-69bf85c8-1 !ERR     | scylla:  [shard 5] paxos - CAS[150392] prune: failed exceptions::mutation_write_timeout_exception (Operation timed out for system.paxos - received only 0 responses from 1 CL=ONE.)
2021-06-01T00:33:45+00:00  alternator-3h-4-5-db-node-69bf85c8-1 !ERR     | scylla:  [shard 5] paxos - CAS[150393] prune: failed exceptions::mutation_write_timeout_exception (Operation timed out for system.paxos - received only 0 responses from 1 CL=ONE.)
2021-06-01T00:33:45+00:00  alternator-3h-4-5-db-node-69bf85c8-1 !ERR     | scylla:  [shard 5] paxos - CAS[150394] prune: failed exceptions::mutation_write_timeout_exception (Operation timed out for system.paxos - received only 0 responses from 1 CL=ONE.)
2021-06-01T00:33:45+00:00  alternator-3h-4-5-db-node-69bf85c8-1 !INFO    | scylla:  [shard 5] rpc - client 10.0.0.175:62711 msg_id 716622:  exception "Operation timed out for system.paxos - received only 0 responses from 1 CL=ONE." in no_wait handler ignored
2021-06-01T00:33:45+00:00  alternator-3h-4-5-db-node-69bf85c8-1 !INFO    | scylla:  [shard 5] rpc - client 10.0.0.175:62711 msg_id 716629:  exception "Operation timed out for system.paxos - received only 0 responses from 1 CL=ONE." in no_wait handler ignored
2021-06-01T00:33:45+00:00  alternator-3h-4-5-db-node-69bf85c8-1 !INFO    | scylla:  [shard 5] rpc - client 10.0.0.175:62711 msg_id 716639:  exception "Operation timed out for system.paxos - received only 0 responses from 1 CL=ONE." in no_wait handler ignored
2021-06-01T00:33:45+00:00  alternator-3h-4-5-db-node-69bf85c8-1 !INFO    | scylla:  [shard 5] rpc - client 10.0.0.175:62711 msg_id 716640:  exception "Operation timed out for system.paxos - received only 0 responses from 1 CL=ONE." in no_wait handler ignored
2021-06-01T00:33:45+00:00  alternator-3h-4-5-db-node-69bf85c8-1 !INFO    | scylla:  [shard 5] rpc - client 10.0.0.175:62711 msg_id 716660:  exception "Operation timed out for system.paxos - received only 0 responses from 1 CL=ONE." in no_wait handler ignored
2021-06-01T00:33:45+00:00  alternator-3h-4-5-db-node-69bf85c8-1 !INFO    | scylla:  [shard 5] rpc - client 10.0.0.201:53275 msg_id 782978:  exception "Operation timed out for system.paxos - received only 0 responses from 1 CL=ONE." in no_wait handler ignored
...
2021-06-01T00:33:46+00:00  alternator-3h-4-5-db-node-69bf85c8-1 !INFO    | scylla:  [shard 5] rpc - client 10.0.0.175:62711 msg_id 716667:  exception "Operation timed out for system.paxos - received only 0 responses from 1 CL=ONE." in no_wait handler ignored
2021-06-01T00:33:46+00:00  alternator-3h-4-5-db-node-69bf85c8-1 !INFO    | scylla:  [shard 5] rpc - client 10.0.0.175:62711 msg_id 716674:  exception "Operation timed out for system.paxos - received only 0 responses from 1 CL=ONE." in no_wait handler ignored
2021-06-01T00:33:46+00:00  alternator-3h-4-5-db-node-69bf85c8-1 !INFO    | scylla:  [shard 5] rpc - client 10.0.0.175:62711 msg_id 716679:  exception "Operation timed out for system.paxos - received only 0 responses from 1 CL=ONE." in no_wait handler ignored
2021-06-01T00:33:46+00:00  alternator-3h-4-5-db-node-69bf85c8-1 !INFO    | scylla:  [shard 5] rpc - client 10.0.0.175:62711 msg_id 716687:  exception "Operation timed out for system.paxos - received only 0 responses from 1 CL=ONE." in no_wait handler ignored
2021-06-01T00:33:46+00:00  alternator-3h-4-5-db-node-69bf85c8-1 !INFO    | scylla:  [shard 5] rpc - client 10.0.0.175:62711 msg_id 716694:  exception "Operation timed out for system.paxos - received only 0 responses from 1 CL=ONE." in no_wait handler ignored
2021-06-01T00:33:46+00:00  alternator-3h-4-5-db-node-69bf85c8-1 !INFO    | scylla:  [shard 5] rpc - client 10.0.0.175:62711 msg_id 716712:  exception "Operation timed out for system.paxos - received only 0 responses from 1 CL=ONE." in no_wait handler ignored
2021-06-01T00:33:46+00:00  alternator-3h-4-5-db-node-69bf85c8-1 !INFO    | scylla:  [shard 5] rpc - client 10.0.0.175:62711 msg_id 716715:  exception "Operation timed out for system.paxos - received only 0 responses from 1 CL=ONE." in no_wait handler ignored
2021-06-01T00:33:46+00:00  alternator-3h-4-5-db-node-69bf85c8-1 !INFO    | scylla:  [shard 5] rpc - client 10.0.0.201:53275 msg_id 782998:  exception "Operation timed out for system.paxos - received only 0 responses from 1 CL=ONE." in no_wait handler ignored
2021-06-01T00:33:46+00:00  alternator-3h-4-5-db-node-69bf85c8-1 !INFO    | scylla:  [shard 5] rpc - client 10.0.0.201:53275 msg_id 783009:  exception "Operation timed out for system.paxos - received only 0 responses from 1 CL=ONE." in no_wait handler ignored
2021-06-01T00:33:46+00:00  alternator-3h-4-5-db-node-69bf85c8-1 !INFO    | scylla:  [shard 5] rpc - client 10.0.0.226:51287 msg_id 705918:  exception "Operation timed out for system.paxos - received only 0 responses from 1 CL=ONE." in no_wait handler ignored
2021-06-01T00:33:46+00:00  alternator-3h-4-5-db-node-69bf85c8-1 !INFO    | scylla:  [shard 5] rpc - client 10.0.0.226:51287 msg_id 705945:  exception "Operation timed out for system.paxos - received only 0 responses from 1 CL=ONE." in no_wait handler ignored
2021-06-01T00:33:46+00:00  alternator-3h-4-5-db-node-69bf85c8-1 !WARNING | scylla:  [shard 5] storage_proxy - Failed to apply mutation from 10.0.0.201#5: exceptions::mutation_write_timeout_exception (Operation timed out for system.paxos - received only 0 responses from 1 CL=ONE.)
2021-06-01T00:33:46+00:00  alternator-3h-4-5-db-node-69bf85c8-1 !WARNING | scylla:  [shard 5] storage_proxy - Failed to apply mutation from 10.0.0.252#5: exceptions::mutation_write_timeout_exception (Operation timed out for system.paxos - received only 0 responses from 1 CL=ONE.)
```

**Comment by kostja** [comment] 2021-07-05 14:44
Most likely coming from commit log patches, that's the only thing that changed in 4.5 AFAIU

**Comment by kostja** [comment] 2021-07-05 14:44
Most likely coming from commit log patches, that's the only thing that changed in 4.5 AFAIU

**Comment by bhalevy** [comment] 2021-07-05 14:49
> Most likely coming from commit log patches, that's the only thing that changed in 4.5 AFAIU

@elcallio please confirm.  Any known issue in 4.5 that can lead to this?

**Comment by kostja** [comment] 2021-07-06 09:35
@roydahan @shoshan Can we please re-test without this commit:
```
commit 4082f57edc3e7764e11e9e858a0a8059981c6309
Merge: af2d1fa0de 4be718ebfa
Author: Avi Kivity <avi@scylladb.com>
Date:   Mon Feb 8 16:44:05 2021 +0200

    Merge 'Make commitlog disk limit a hard limit.' from Calle Wilund
    
    Refs #6148
    
```
?

I am not claiming this commit is the culprit, but we need to start bi-secting somewhere, and it is our current working hypothesis.

**Comment by slivne** [comment] 2021-07-07 11:07
Please test with 4.5rc4

**Comment by bhalevy** [comment] 2021-07-07 11:07
Better try to reproduce with f89f4e69a0d209b0646e9804db281166fc679081
```
    Merge 'Commitlog: Handle disk usage and disk footprint discrepancies, ensuring we flush when needed (#8695)​ (v3)' from Calle Wilund
```

**Comment by slivne** [comment] 2021-07-12 11:05
Please retest with 4.5.rc5

**Comment by slivne** [comment] 2021-07-15 11:04
@roydahan / @bentsi  rc5 is being promoted - please retest

**Comment by slivne** [comment] 2021-07-18 11:05
In progress

**Comment by slivne** [comment] 2021-07-19 11:05
still in progress (saw that there are timeouts in other nemesis as well ...)

Need to think what todo here - e.g. there is a fix for the regression introduced by https://github.com/scylladb/scylla/issues/8808#issuecomment-874612507 in 4.5 (#8270) and this is part already of what's being tested - we may have a different source - we can try and double check that for and revert the comitlog log changes and see if the problem still remains

**Comment by yarongilor** [comment] 2021-07-19 14:34
It looks like the problem may be reproduced now live. using the same test configuration, just modifying to use manager-repair nemesis only.
monitor in: http://13.48.55.220:3000/
can send test details when it's done.

**Comment by bhalevy** [comment] 2021-09-19 11:10
@roydahan please retest with latest 4.5.rcX

**Comment by roydahan** [comment] 2021-09-22 10:52
I ran the reproducer again using 4.5.rc7 (https://jenkins.scylladb.com/job/scylla-4.5/job/Reproducers/job/longevity-alternator-3h-test-8808/3/) and it passed.
I see a drop in throughput but I didn't find any timeouts.
I don't think that the drop in throughput is related to the original issue and we can close this one.

**Closed by roydahan** 2021-09-22 10:52 UTC
Labels: test, Regression, repair, Alternator
