### ISSUE TITLE
invalid query with multi-column relation support: 'Clustering columns may not be skipped in multi-column relations...'

### ISSUE THREAD

**Issue by abvgedeika** [scylladb/scylla#2564] opened 2017-07-10 10:27 UTC
Scylla version (or git commit hash): https://github.com/scylladb/scylla/commit/d177ec05cb0c5a451a1a5b93646d3a35d2a6cc0b

steps:

```
create table simple_tuple_query_test (a int, b int, c int, d int , e int, PRIMARY KEY (a, b, c, d, e))
INSERT INTO simple_tuple_query_test (a, b, c, d, e) VALUES (0, 2, 0, 0, 0)
INSERT INTO simple_tuple_query_test (a, b, c, d, e) VALUES (0, 1, 0, 0, 0)
INSERT INTO simple_tuple_query_test (a, b, c, d, e) VALUES (0, 0, 0, 0, 0)
INSERT INTO simple_tuple_query_test (a, b, c, d, e) VALUES (0, 0, 1, 1, 1)
INSERT INTO simple_tuple_query_test (a, b, c, d, e) VALUES (0, 0, 2, 2, 2)
INSERT INTO simple_tuple_query_test (a, b, c, d, e) VALUES (0, 0, 3, 3, 3)
INSERT INTO simple_tuple_query_test (a, b, c, d, e) VALUES (0, 0, 1, 1, 1)

SELECT * FROM simple_tuple_query_test WHERE b=0 AND (c, d, e) > (1, 1, 1) ALLOW FILTERING
```

result:
code=2200 [Invalid query] message="Clustering columns may not be skipped in multi-column relations. They should appear in the PRIMARY KEY order. Got (c, d, e) > (1, 1, 1)"

expected result: [[0, 0, 2, 2, 2], [0, 0, 3, 3, 3]]

it works in c-3.0.9

**Comment by duarten** [comment] 2017-07-10 10:29
Seems like a duplicate of #64.

**Closed** 2017-07-12 08:18 UTC
