### ISSUE TITLE
Nodetool info times out

### ISSUE THREAD

**Issue by ShlomiBalalis** [scylladb/scylla#7314] opened 2020-10-01 09:35 UTC
*Installation details*
Scylla version (or git commit hash): 666.development-0.20200927.8366d2231 with build-id ce2d999679a623780ccea8bbb6e50cb8b124593e
Cluster size: 3
OS (RHEL/CentOS/Ubuntu/AWS AMI): ami-0f5133b6e7635dac2 (us-east-1)

During the manager upgrade test, we execute `nodetool info` on each node, twice.
In the first run, all of the executions went without issue:
```
< t:2020-09-30 21:11:08,018 f:cluster.py      l:2419 c:sdcm.cluster_aws     p:DEBUG > Node manager-upgrade-master-db-node-b3816bfe-1 [3.238.27.63 | 10.0.2.130] (seed: False): Command 'nodetool  info ' duration -> 2.932184032999885 s
...
< t:2020-09-30 21:11:51,135 f:cluster.py      l:2419 c:sdcm.cluster_aws     p:DEBUG > Node manager-upgrade-master-db-node-b3816bfe-2 [34.236.242.107 | 10.0.2.238] (seed: False): Command 'nodetool  info ' duration -> 3.147473138999885 s
...
< t:2020-09-30 21:12:39,907 f:cluster.py      l:2419 c:sdcm.cluster_aws     p:DEBUG > Node manager-upgrade-master-db-node-b3816bfe-3 [34.233.71.7 | 10.0.0.46] (seed: False): Command 'nodetool  info ' duration -> 3.4764430049999646 s
```
In the second run, the command ran fine on nodes 1 and 2, but when we ran the command on node#3 the execution froze until the test has reached timeout, hours later:
```
< t:2020-09-30 21:14:46,359 f:remote_base.py  l:519  c:RemoteCmdRunner      p:DEBUG > Running command "nodetool  info "...
< t:2020-09-30 21:14:46,380 f:base.py         l:243  c:RemoteCmdRunner      p:DEBUG > Using /etc/scylla/scylla.yaml as the config file
< t:2020-09-30 21:14:47,757 f:base.py         l:243  c:RemoteCmdRunner      p:DEBUG > ID                     : 71c56cad-781c-4968-9a7d-b6d857cee0ea
< t:2020-09-30 21:14:47,758 f:base.py         l:243  c:RemoteCmdRunner      p:DEBUG > Gossip active          : true
< t:2020-09-30 21:14:47,768 f:base.py         l:243  c:RemoteCmdRunner      p:DEBUG > Thrift active          : true
< t:2020-09-30 21:14:47,772 f:base.py         l:243  c:RemoteCmdRunner      p:DEBUG > Native Transport active: true
< t:2020-09-30 21:14:47,777 f:base.py         l:243  c:RemoteCmdRunner      p:DEBUG > Load                   : 284.41 MB
< t:2020-09-30 21:14:47,783 f:base.py         l:243  c:RemoteCmdRunner      p:DEBUG > Generation No          : 1601497993
< t:2020-09-30 21:14:47,786 f:base.py         l:243  c:RemoteCmdRunner      p:DEBUG > Uptime (seconds)       : 2492
< t:2020-09-30 21:14:47,809 f:base.py         l:243  c:RemoteCmdRunner      p:DEBUG > Heap Memory (MB)       : 13.41 / 247.50

...

< t:2020-10-01 02:15:43,597 f:base.py         l:167  c:RemoteCmdRunner      p:ERROR > Error executing command: "nodetool  info "; Exit status: -1

```

Logs:
```
+--------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                                           Log links for testrun with test id b3816bfe-1b71-453b-8bca-ddf55f80afa1                                            |
+-----------------+-------------+------------------------------------------------------------------------------------------------------------------------------+
| Date            | Log type    | Link                                                                                                                         |
+-----------------+-------------+------------------------------------------------------------------------------------------------------------------------------+
| 20201001_021442 | db-cluster  | https://cloudius-jenkins-test.s3.amazonaws.com/b3816bfe-1b71-453b-8bca-ddf55f80afa1/20201001_021442/db-cluster-b3816bfe.zip  |
| 20201001_021442 | loader-set  | https://cloudius-jenkins-test.s3.amazonaws.com/b3816bfe-1b71-453b-8bca-ddf55f80afa1/20201001_021442/loader-set-b3816bfe.zip  |
| 20201001_021442 | monitor-set | https://cloudius-jenkins-test.s3.amazonaws.com/b3816bfe-1b71-453b-8bca-ddf55f80afa1/20201001_021442/monitor-set-b3816bfe.zip |
| 20201001_021442 | sct-runner  | https://cloudius-jenkins-test.s3.amazonaws.com/b3816bfe-1b71-453b-8bca-ddf55f80afa1/20201001_021442/sct-runner-b3816bfe.zip  |
+-----------------+-------------+------------------------------------------------------------------------------------------------------------------------------+
```

**Comment by slivne** [comment] 2020-10-04 09:58
@amnonh could it be that the nodetool info is called to early at boot time and then gets stuck - do we validate in the api that the node / modeules are up before access ?

**Comment by amnonh** [comment] 2021-01-05 08:09
@slivne the API is dynamically registered, that means that trying to access an API when it is not ready will result in 404 error.

**Comment by slivne** [comment] 2021-01-27 08:20
@roydahan / @ShlomiBalalis can we try and reproduce this and get a server into a stuck state - so @amnonh can try and find the bug and figure out whats stuck

**Comment by elcallio** [comment] 2021-03-10 11:57
I think this is a dup of #7991

**Comment by avikivity** [comment] 2021-05-03 13:52
Closing as duplicate of #7991.

**Closed** 2021-05-03 13:52 UTC
Labels: bug, nodetool
