### ISSUE TITLE
Alter table add map type columns will make cluster nodes down

### ISSUE THREAD

**Issue by i-mine** [scylladb/scylla#4561] opened 2019-06-17 10:11 UTC
*Installation details*
Scylla version: 2.3.5-0.20190417.0e0f9143c
Cluster size: 5
OS (RHEL/CentOS/Ubuntu/AWS AMI): Alibaba Cloud Enterprise Linux Server release 17.01.2 (Golden Toad)

*Hardware details (for performance issues)* 
Platform (physical/VM/cloud instance type/docker): cloud instance
Hardware: ecs.i2.4xlarge 16vcore 128G 2*1.7TB SSD(raid0)

** I need add multi columns which contains types like map<text,text>**
Some  premise below:
1. KeySpace and Table 
```
CREATE KEYSPACE user_action WITH replication = {'class': 'SimpleStrategy', 'replication_factor': '2'}  AND durable_writes = true;

CREATE TABLE user_action.dsp_user_history_pkg_tag (
    device_id text PRIMARY KEY,
    pkg text
) WITH bloom_filter_fp_chance = 0.01
    AND caching = {'keys': 'ALL', 'rows_per_partition': 'ALL'}
    AND comment = 'dsp user history pkg records'
    AND compaction = {'class': 'LeveledCompactionStrategy'}
    AND compression = {'chunk_length_kb': '1', 'crc_check_chance': '0.000010', 'sstable_compression': 'org.apache.cassandra.io.compress.LZ4Compressor'}
    AND dclocal_read_repair_chance = 0.1
    AND default_time_to_live = 1296000
    AND gc_grace_seconds = 864000
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair_chance = 0.0
    AND speculative_retry = '99.0PERCENTILE';
```
2.Alter column
```
alter table user_action.dsp_user_history_pkg_tag  add appid_adtype_cc_cam map<text, text>;
```
When I add map columns, My cluster nodes will down(2 nodes at least, also suffered 4 nodes).
The cqlsh client will report: NoHostAvailable
And some errors in Scylla Server:
```
Jun 17 15:40:53 hk-dsp-cassandra scylla[4382]:  [shard 5] schema_tables - Altering user_action.dsp_user_history_pkg_tag id=10e05970-34ee-11e9-8ee8-000000000006 version=eec3c1c0-90c4-33d4-9eb9-483925462dcc
Jun 17 15:40:53 hk-dsp-cassandra scylla[4382]:  [shard 0] database - Setting compaction strategy of user_action.dsp_user_history_pkg_tag to LeveledCompactionStrategy
Jun 17 15:40:53 hk-dsp-cassandra scylla[4382]:  [shard 8] query_processor - Column definitions for user_action.dsp_user_history_pkg_tag changed, invalidating related prepared statements
Jun 17 15:40:53 hk-dsp-cassandra scylla[4382]:  [shard 10] query_processor - Column definitions for user_action.dsp_user_history_pkg_tag changed, invalidating related prepared statements
Jun 17 15:40:53 hk-dsp-cassandra scylla[4382]:  [shard 9] query_processor - Column definitions for user_action.dsp_user_history_pkg_tag changed, invalidating related prepared statements
Jun 17 15:40:53 hk-dsp-cassandra scylla[4382]:  [shard 5] query_processor - Column definitions for user_action.dsp_user_history_pkg_tag changed, invalidating related prepared statements
Jun 17 15:40:53 hk-dsp-cassandra scylla[4382]:  [shard 4] query_processor - Column definitions for user_action.dsp_user_history_pkg_tag changed, invalidating related prepared statements
Jun 17 15:40:53 hk-dsp-cassandra scylla[4382]:  [shard 3] query_processor - Column definitions for user_action.dsp_user_history_pkg_tag changed, invalidating related prepared statements
Jun 17 15:40:53 hk-dsp-cassandra scylla[4382]:  [shard 0] query_processor - Column definitions for user_action.dsp_user_history_pkg_tag changed, invalidating related prepared statements
Jun 17 15:40:53 hk-dsp-cassandra scylla[4382]:  [shard 2] query_processor - Column definitions for user_action.dsp_user_history_pkg_tag changed, invalidating related prepared statements
Jun 17 15:40:53 hk-dsp-cassandra scylla[4382]:  [shard 1] query_processor - Column definitions for user_action.dsp_user_history_pkg_tag changed, invalidating related prepared statements
Jun 17 15:40:53 hk-dsp-cassandra scylla[4382]:  [shard 13] query_processor - Column definitions for user_action.dsp_user_history_pkg_tag changed, invalidating related prepared statements
Jun 17 15:40:53 hk-dsp-cassandra scylla[4382]:  [shard 6] query_processor - Column definitions for user_action.dsp_user_history_pkg_tag changed, invalidating related prepared statements
Jun 17 15:40:53 hk-dsp-cassandra scylla[4382]:  [shard 7] query_processor - Column definitions for user_action.dsp_user_history_pkg_tag changed, invalidating related prepared statements
Jun 17 15:40:53 hk-dsp-cassandra scylla[4382]:  [shard 12] query_processor - Column definitions for user_action.dsp_user_history_pkg_tag changed, invalidating related prepared statements
Jun 17 15:40:53 hk-dsp-cassandra scylla[4382]:  [shard 4] seastar_memory - oversized allocation: 536875008 bytes, please report: at   0x7b4608
Jun 17 15:40:53 hk-dsp-cassandra scylla[4382]:  [shard 8] seastar_memory - oversized allocation: 536875008 bytes, please report: at   0x7b4608
Jun 17 15:40:53 hk-dsp-cassandra scylla[4382]:  [shard 11] query_processor - Column definitions for user_action.dsp_user_history_pkg_tag changed, invalidating related prepared statements
Jun 17 15:40:53 hk-dsp-cassandra scylla[4382]:  [shard 0] storage_proxy - Exception when communicating with 172.23.240.216: marshaling error: read_simple_bytes - not enough bytes (requested 1635349309, got 255412244) Backtrace:   0x7b4608

Jun 17 15:40:53 hk-dsp-cassandra scylla[4382]: scylla: types.cc:2507: collection_type_impl::mutation_view collection_type_impl::deserialize_mutation_form(bytes_view) const: Assertion `in.empty()' failed.
Jun 17 15:40:53 hk-dsp-cassandra scylla[4382]: Aborting on shard 4.
Jun 17 15:40:53 hk-dsp-cassandra scylla[4382]: Backtrace:
Jun 17 15:40:53 hk-dsp-cassandra scylla[4382]: 0x0000000000689832
Jun 17 15:40:53 hk-dsp-cassandra scylla[4382]: 0x00000000005a492c
Jun 17 15:40:53 hk-dsp-cassandra scylla[4382]: 0x00000000005a4bd5
Jun 17 15:40:53 hk-dsp-cassandra scylla[4382]: 0x00000000005a4c83
Jun 17 15:40:53 hk-dsp-cassandra scylla[4382]: /lib64/libpthread.so.0+0x000000000000f5df
Jun 17 15:40:53 hk-dsp-cassandra scylla[4382]: /lib64/libc.so.6+0x00000000000351f6
Jun 17 15:40:53 hk-dsp-cassandra scylla[4382]: /lib64/libc.so.6+0x00000000000368e7
Jun 17 15:40:53 hk-dsp-cassandra scylla[4382]: /lib64/libc.so.6+0x000000000002e265
Jun 17 15:40:53 hk-dsp-cassandra scylla[4382]: /lib64/libc.so.6+0x000000000002e311
Jun 17 15:40:53 hk-dsp-cassandra scylla[4382]: 0x00000000021d5059
Jun 17 15:40:53 hk-dsp-cassandra scylla[4382]: 0x00000000015bc5c2
Jun 17 15:40:53 hk-dsp-cassandra scylla[4382]: 0x0000000001556c11
Jun 17 15:40:53 hk-dsp-cassandra scylla[4382]: 0x000000000148944f
Jun 17 15:40:53 hk-dsp-cassandra scylla[4382]: 0x000000000148d096
Jun 17 15:40:53 hk-dsp-cassandra scylla[4382]: 0x000000000148f5ea
Jun 17 15:40:53 hk-dsp-cassandra scylla[4382]: 0x000000000148f8fa
Jun 17 15:40:53 hk-dsp-cassandra scylla[4382]: 0x0000000001461159
Jun 17 15:40:53 hk-dsp-cassandra scylla[4382]: 0x0000000001463e50
Jun 17 15:40:53 hk-dsp-cassandra scylla[4382]: 0x0000000001710f77
Jun 17 15:40:53 hk-dsp-cassandra scylla[4382]: 0x000000000144139f
Jun 17 15:40:53 hk-dsp-cassandra scylla[4382]: 0x0000000001470ba1
Jun 17 15:40:53 hk-dsp-cassandra scylla[4382]: 0x0000000001474f60
Jun 17 15:40:53 hk-dsp-cassandra scylla[4382]: 0x0000000000585ce6
Jun 17 15:40:53 hk-dsp-cassandra scylla[4382]: 0x0000000000585ea1
Jun 17 15:40:53 hk-dsp-cassandra scylla[4382]: 0x000000000065352f
Jun 17 15:40:53 hk-dsp-cassandra scylla[4382]: 0x0000000000656715
Jun 17 15:40:53 hk-dsp-cassandra scylla[4382]: 0x000000000073e5fd
Jun 17 15:40:53 hk-dsp-cassandra scylla[4382]: /lib64/libpthread.so.0+0x0000000000007e24
Jun 17 15:40:53 hk-dsp-cassandra scylla[4382]: /lib64/libc.so.6+0x00000000000f834c
```
When nodes down, I must restart almost all of nodes ,then the schema will add new map column successfully, which is dangerous for our service, by the words, that's no problem in version 2.2.1 .

**Comment by slivne** [comment] 2019-06-18 07:26
@denesb - as a started lets see if we can reproduce this on 3.0 ...

**Comment by i-mine** [comment] 2019-06-20 07:23
I have tried the options(add) again successfully when cluster load in low level（< 20%） , and it's ok on 3.0.5, maybe you can reproduce with high load(90%)。

**Comment by denesb** [comment] 2019-06-27 13:07
I have failed to reproduce this on 3.0.7. What I tried:
* Write some data into a keyspace (RF=2).
* Start reads, make sure load is high (>75%).
* Alter the table, add map column.

**Comment by slivne** [comment] 2019-07-11 09:55
@i-mine we are not able to reproduce - I am closing this issue, if you can provide a reproducer we can reopen

**Closed by slivne** 2019-07-11 09:55 UTC
Labels: bug
