### ISSUE TITLE
reactor stalled for 654 ms during abort repair nemesis (refill_emergency_reserve)

### ISSUE THREAD

**Issue by fgelcer** [scylladb/scylla#6188] opened 2020-04-13 19:19 UTC
*Installation details*
Scylla version (or git commit hash): 4.0.rc0-0.20200405.511773d4662 with build-id de88161d63d02e10ad1b3f2a761cb15aee71d8c9
Cluster size: 4 DB nodes
OS (RHEL/CentOS/Ubuntu/AWS AMI): ami-02ffbefa17e58c217

job running is 1TB 7 days longevity.

node that experienced issue is node-3
```
Reactor stalled for 654 ms on shard 3.
Backtrace:
0x0000000002ed97f2
0x0000000002e7f34b
0x0000000002e7f872
0x0000000002e7fba7
0x00007f7dc8cbdb1f
0x0000000000f12197
0x0000000000f12a50
0x0000000000f12eec
0x0000000000fa105b
0x0000000000fa1b96
0x0000000000fa1ff3
0x0000000000fa2107
0x0000000000fa2c19
0x0000000000f1ae8b
0x0000000000f1ca46
0x000000000313bf4c
```
decoded:
```
void seastar::backtrace<seastar::backtrace_buffer::append_backtrace()::{lambda(seastar::frame)#1}>(seastar::backtrace_buffer::append_backtrace()::{lambda(seastar::frame)#1}&&) at /usr/include/fmt/format.h:1158
seastar::backtrace_buffer::append_backtrace() at /usr/include/fmt/format.h:1158
 (inlined by) print_with_backtrace at ./build/release/seastar/./seastar/src/core/reactor.cc:755
seastar::internal::cpu_stall_detector::generate_trace() at /usr/include/fmt/format.h:1158
seastar::internal::cpu_stall_detector::maybe_report() at /usr/include/fmt/format.h:1158
 (inlined by) seastar::internal::cpu_stall_detector::on_signal() at ./build/release/seastar/./seastar/src/core/reactor.cc:1062
 (inlined by) seastar::reactor::block_notifier(int) at ./build/release/seastar/./seastar/src/core/reactor.cc:1185
?? ??:0
cache_entry::~cache_entry() at /usr/include/fmt/format.h:1158
void allocation_strategy::destroy<cache_entry>(cache_entry*) at /usr/include/fmt/format.h:1158
 (inlined by) auto current_deleter<cache_entry>()::{lambda(cache_entry*)#1}::operator()(cache_entry*) const at ././utils/allocation_strategy.hh:238
 (inlined by) cache_entry::on_evicted(cache_tracker&) at ./row_cache.cc:1233
operator() at /usr/include/fmt/format.h:1158
 (inlined by) with_linearized_managed_bytes<cache_tracker::cache_tracker(mutation_application_stats&)::<lambda()>::<lambda()>::<lambda()> > at ./utils/managed_bytes.hh:428
 (inlined by) operator() at ./row_cache.cc:69
 (inlined by) with_allocator<cache_tracker::cache_tracker(mutation_application_stats&)::<lambda()>::<lambda()> > at ././utils/allocation_strategy.hh:307
 (inlined by) operator() at ./row_cache.cc:66
 (inlined by) _M_invoke at /usr/include/c++/9/bits/std_function.h:285
std::function<seastar::memory::reclaiming_result ()>::operator()() const at /usr/include/fmt/format.h:1158
 (inlined by) logalloc::region_impl::evict_some() at ./utils/logalloc.cc:1613
 (inlined by) reclaim_from_evictable at ./utils/logalloc.cc:1828
logalloc::tracker::impl::compact_and_evict_locked(unsigned long, unsigned long) at /usr/include/fmt/format.h:1158
logalloc::tracker::impl::compact_and_evict(unsigned long, unsigned long) at /usr/include/fmt/format.h:1158
 (inlined by) logalloc::segment_pool::allocate_segment(unsigned long) at ./utils/logalloc.cc:801
logalloc::segment_pool::refill_emergency_reserve() at /usr/include/fmt/format.h:1158
logalloc::allocating_section::reserve() at /usr/include/fmt/format.h:1158
with_reserve<logalloc::allocating_section::operator()(logalloc::region&, Func&&) [with Func = row_cache::do_update(row_cache::external_updater, memtable&, Updater) [with Updater = row_cache::update(row_cache::external_updater, memtable&)::<lambda(logalloc::allocating_section&, boost::intrusive::set<cache_entry, boost::intrusive::member_hook<cache_entry, boost::intrusive::set_member_hook<boost::intrusive::link_mode<(boost::intrusive::link_mode_type)2> >, &cache_entry::_cache_link>, boost::intrusive::constant_time_size<false>, boost::intrusive::compare<cache_entry::compare> >::iterator, memtable_entry&, partition_presence_checker&, real_dirty_memory_accounter&)>]::<lambda()>::<lambda()> mutable::<lambda()>::<lambda()>::<lambda()>]::<lambda()> > at /usr/include/fmt/format.h:1158
 (inlined by) operator()<row_cache::do_update(row_cache::external_updater, memtable&, Updater) [with Updater = row_cache::update(row_cache::external_updater, memtable&)::<lambda(logalloc::allocating_section&, boost::intrusive::set<cache_entry, boost::intrusive::member_hook<cache_entry, boost::intrusive::set_member_hook<boost::intrusive::link_mode<(boost::intrusive::link_mode_type)2> >, &cache_entry::_cache_link>, boost::intrusive::constant_time_size<false>, boost::intrusive::compare<cache_entry::compare> >::iterator, memtable_entry&, partition_presence_checker&, real_dirty_memory_accounter&)>]::<lambda()>::<lambda()> mutable::<lambda()>::<lambda()>::<lambda()> > at ././utils/logalloc.hh:768
 (inlined by) operator() at ./row_cache.cc:957
 (inlined by) with_linearized_managed_bytes<row_cache::do_update(row_cache::external_updater, memtable&, Updater) [with Updater = row_cache::update(row_cache::external_updater, memtable&)::<lambda(logalloc::allocating_section&, boost::intrusive::set<cache_entry, boost::intrusive::member_hook<cache_entry, boost::intrusive::set_member_hook<boost::intrusive::link_mode<(boost::intrusive::link_mode_type)2> >, &cache_entry::_cache_link>, boost::intrusive::constant_time_size<false>, boost::intrusive::compare<cache_entry::compare> >::iterator, memtable_entry&, partition_presence_checker&, real_dirty_memory_accounter&)>]::<lambda()>::<lambda()> mutable::<lambda()>::<lambda()> > at ./utils/managed_bytes.hh:428
 (inlined by) operator() at ./row_cache.cc:955
 (inlined by) with_allocator<row_cache::do_update(row_cache::external_updater, memtable&, Updater) [with Updater = row_cache::update(row_cache::external_updater, memtable&)::<lambda(logalloc::allocating_section&, boost::intrusive::set<cache_entry, boost::intrusive::member_hook<cache_entry, boost::intrusive::set_member_hook<boost::intrusive::link_mode<(boost::intrusive::link_mode_type)2> >, &cache_entry::_cache_link>, boost::intrusive::constant_time_size<false>, boost::intrusive::compare<cache_entry::compare> >::iterator, memtable_entry&, partition_presence_checker&, real_dirty_memory_accounter&)>]::<lambda()>::<lambda()> mutable::<lambda()> > at ././utils/allocation_strategy.hh:307
 (inlined by) operator() at ./row_cache.cc:944
apply at /usr/include/fmt/format.h:1158
 (inlined by) apply<row_cache::do_update(row_cache::external_updater, memtable&, Updater) [with Updater = row_cache::update(row_cache::external_updater, memtable&)::<lambda(logalloc::allocating_section&, boost::intrusive::set<cache_entry, boost::intrusive::member_hook<cache_entry, boost::intrusive::set_member_hook<boost::intrusive::link_mode<(boost::intrusive::link_mode_type)2> >, &cache_entry::_cache_link>, boost::intrusive::constant_time_size<false>, boost::intrusive::compare<cache_entry::compare> >::iterator, memtable_entry&, partition_presence_checker&, real_dirty_memory_accounter&)>]::<lambda()>::<lambda()> > at ././seastar/include/seastar/core/apply.hh:44
 (inlined by) apply_tuple<row_cache::do_update(row_cache::external_updater, memtable&, Updater) [with Updater = row_cache::update(row_cache::external_updater, memtable&)::<lambda(logalloc::allocating_section&, boost::intrusive::set<cache_entry, boost::intrusive::member_hook<cache_entry, boost::intrusive::set_member_hook<boost::intrusive::link_mode<(boost::intrusive::link_mode_type)2> >, &cache_entry::_cache_link>, boost::intrusive::constant_time_size<false>, boost::intrusive::compare<cache_entry::compare> >::iterator, memtable_entry&, partition_presence_checker&, real_dirty_memory_accounter&)>]::<lambda()>::<lambda()> > at ././seastar/include/seastar/core/future.hh:1618
 (inlined by) apply<row_cache::do_update(row_cache::external_updater, memtable&, Updater) [with Updater = row_cache::update(row_cache::external_updater, memtable&)::<lambda(logalloc::allocating_section&, boost::intrusive::set<cache_entry, boost::intrusive::member_hook<cache_entry, boost::intrusive::set_member_hook<boost::intrusive::link_mode<(boost::intrusive::link_mode_type)2> >, &cache_entry::_cache_link>, boost::intrusive::constant_time_size<false>, boost::intrusive::compare<cache_entry::compare> >::iterator, memtable_entry&, partition_presence_checker&, real_dirty_memory_accounter&)>]::<lambda()>::<lambda()> > at ././seastar/include/seastar/core/future.hh:1652
 (inlined by) operator() at ././seastar/include/seastar/core/thread.hh:253
 (inlined by) call at ././seastar/include/seastar/util/noncopyable_function.hh:101
seastar::noncopyable_function<void ()>::operator()() const at ./build/release/seastar/./seastar/include/seastar/util/noncopyable_function.hh:184
 (inlined by) seastar::thread_context::main() at ./build/release/seastar/./seastar/src/core/thread.cc:286
```

full logs can be found here:
```
+--------------------------------------------------------------------------------------------------------------------------------------------+
|                                      Collected logs by test-id: bbc128f5-0097-4db4-9327-d46c7d8e73a2                                       |
+-------------+------------------------------------------------------------------------------------------------------------------------------+
| Cluster set | Link                                                                                                                         |
+-------------+------------------------------------------------------------------------------------------------------------------------------+
| db-cluster  | https://cloudius-jenkins-test.s3.amazonaws.com/bbc128f5-0097-4db4-9327-d46c7d8e73a2/20200412_105848/db-cluster-bbc128f5.zip  |
| monitor-set | https://cloudius-jenkins-test.s3.amazonaws.com/bbc128f5-0097-4db4-9327-d46c7d8e73a2/20200412_105848/monitor-set-bbc128f5.zip |
| loader-set  | None                                                                                                                         |
| sct-runner  | https://cloudius-jenkins-test.s3.amazonaws.com/bbc128f5-0097-4db4-9327-d46c7d8e73a2/20200412_105848/sct-runner-bbc128f5.zip  |
+-------------+------------------------------------------------------------------------------------------------------------------------------+
```

**Comment by asias** [comment] 2020-07-07 03:26
It is similar to #6189. The stall happens inside the row_cache eviction. It is not specific to repair.

**Comment by bhalevy** [comment] 2020-10-11 08:02
@xemul is this a duplicated of #6189?

**Comment by xemul** [comment] 2020-10-12 10:16
@bhalevy , I would say it is.

**Comment by bhalevy** [comment] 2021-02-24 07:18
Duplicate of #6189

**Closed by bhalevy** 2021-02-24 07:18 UTC
Labels: latency, repair, stability
