### ISSUE TITLE
Schema version on one of the nodes is different from other nodes

### ISSUE THREAD

**Issue by juliayakovlev** [scylladb/scylla#4878] opened 2019-08-21 14:34 UTC
*Installation details*
Scylla version (or git commit hash): 3.1.0.rc3-0.20190814.70f515410
Cluster size: 4 nodes (i3.4xlarge)
OS (RHEL/CentOS/Ubuntu/AWS AMI): ami-0022b737d8b787228

Schema version on one of the nodes is different from other nodes during few hours.

Test flow:

Restart Scylla server on **172.30.0.30**:
```
< t:2019-08-17 18:59:24,213 f:nemesis.py      l:283  c:sdcm.nemesis         p:DEBUG > sdcm.nemesis.LimitedChaosMonkey: Set current_disruption -> StopStartService Node longevity-200gb-48h-verify-limited--db-node-5f3e71cc-4 [54.236.77.85 | 172.30.0.30] (seed: False)
```
After the node **172.30.0.30** was restarted, the schema version on 3 other nodes is same, but on restarted node is different in the both: gossip and system.peers

This is how the schema has been changed and merged after restart:
```
< t:2019-08-17 19:02:11,379 f:cluster.py      l:1212 c:sdcm.cluster         p:DEBUG > 2019-08-17T19:02:02+00:00  ip-172-30-0-30 !INFO    | scylla.bin: [shard 0] database - Schema version changed to a06c0c09-c332-3a38-a11b-24fc1106419c
< t:2019-08-17 19:02:26,401 f:cluster.py      l:1212 c:sdcm.cluster         p:DEBUG > 2019-08-17T19:02:14+00:00  ip-172-30-0-30 !INFO    | scylla.bin: [shard 0] database - Schema version changed to 17e1c678-7b2d-3386-a5d7-8f5d1ae30081
< t:2019-08-17 19:02:26,401 f:cluster.py      l:1212 c:sdcm.cluster         p:DEBUG > 2019-08-17T19:02:14+00:00  ip-172-30-0-30 !INFO    | scylla.bin: [shard 8] database - Schema version changed to 17e1c678-7b2d-3386-a5d7-8f5d1ae30081
< t:2019-08-17 19:02:26,401 f:cluster.py      l:1212 c:sdcm.cluster         p:DEBUG > 2019-08-17T19:02:14+00:00  ip-172-30-0-30 !INFO    | scylla.bin: [shard 0] database - Schema version changed to 17e1c678-7b2d-3386-a5d7-8f5d1ae30081
< t:2019-08-17 19:02:26,401 f:cluster.py      l:1212 c:sdcm.cluster         p:DEBUG > 2019-08-17T19:02:14+00:00  ip-172-30-0-30 !INFO    | scylla.bin: [shard 6] database - Schema version changed to 17e1c678-7b2d-3386-a5d7-8f5d1ae30081
< t:2019-08-17 19:02:26,402 f:cluster.py      l:1212 c:sdcm.cluster         p:DEBUG > 2019-08-17T19:02:14+00:00  ip-172-30-0-30 !INFO    | scylla.bin: [shard 13] database - Schema version changed to 17e1c678-7b2d-3386-a5d7-8f5d1ae30081
< t:2019-08-17 19:02:26,402 f:cluster.py      l:1212 c:sdcm.cluster         p:DEBUG > 2019-08-17T19:02:14+00:00  ip-172-30-0-30 !INFO    | scylla.bin: [shard 11] database - Schema version changed to 17e1c678-7b2d-3386-a5d7-8f5d1ae30081
< t:2019-08-17 19:02:26,402 f:cluster.py      l:1212 c:sdcm.cluster         p:DEBUG > 2019-08-17T19:02:14+00:00  ip-172-30-0-30 !INFO    | scylla.bin: [shard 10] database - Schema version changed to 17e1c678-7b2d-3386-a5d7-8f5d1ae30081
< t:2019-08-17 19:02:26,402 f:cluster.py      l:1212 c:sdcm.cluster         p:DEBUG > 2019-08-17T19:02:14+00:00  ip-172-30-0-30 !INFO    | scylla.bin: [shard 8] database - Schema version changed to 17e1c678-7b2d-3386-a5d7-8f5d1ae30081
< t:2019-08-17 19:02:26,402 f:cluster.py      l:1212 c:sdcm.cluster         p:DEBUG > 2019-08-17T19:02:14+00:00  ip-172-30-0-30 !INFO    | scylla.bin: [shard 12] database - Schema version changed to 17e1c678-7b2d-3386-a5d7-8f5d1ae30081
< t:2019-08-17 19:02:26,402 f:cluster.py      l:1212 c:sdcm.cluster         p:DEBUG > 2019-08-17T19:02:14+00:00  ip-172-30-0-30 !INFO    | scylla.bin: [shard 10] database - Schema version changed to 17e1c678-7b2d-3386-a5d7-8f5d1ae30081
< t:2019-08-17 19:02:26,402 f:cluster.py      l:1212 c:sdcm.cluster         p:DEBUG > 2019-08-17T19:02:14+00:00  ip-172-30-0-30 !INFO    | scylla.bin: [shard 11] database - Schema version changed to 17e1c678-7b2d-3386-a5d7-8f5d1ae30081
< t:2019-08-17 19:02:26,402 f:cluster.py      l:1212 c:sdcm.cluster         p:DEBUG > 2019-08-17T19:02:14+00:00  ip-172-30-0-30 !INFO    | scylla.bin: [shard 7] database - Schema version changed to 17e1c678-7b2d-3386-a5d7-8f5d1ae30081
< t:2019-08-17 19:02:26,402 f:cluster.py      l:1212 c:sdcm.cluster         p:DEBUG > 2019-08-17T19:02:14+00:00  ip-172-30-0-30 !INFO    | scylla.bin: [shard 6] database - Schema version changed to 17e1c678-7b2d-3386-a5d7-8f5d1ae30081
< t:2019-08-17 19:02:26,403 f:cluster.py      l:1212 c:sdcm.cluster         p:DEBUG > 2019-08-17T19:02:14+00:00  ip-172-30-0-30 !INFO    | scylla.bin: [shard 12] database - Schema version changed to 17e1c678-7b2d-3386-a5d7-8f5d1ae30081
< t:2019-08-17 19:02:26,403 f:cluster.py      l:1212 c:sdcm.cluster         p:DEBUG > 2019-08-17T19:02:14+00:00  ip-172-30-0-30 !INFO    | scylla.bin: [shard 2] database - Schema version changed to 17e1c678-7b2d-3386-a5d7-8f5d1ae30081
< t:2019-08-17 19:02:26,403 f:cluster.py      l:1212 c:sdcm.cluster         p:DEBUG > 2019-08-17T19:02:14+00:00  ip-172-30-0-30 !INFO    | scylla.bin: [shard 9] database - Schema version changed to 17e1c678-7b2d-3386-a5d7-8f5d1ae30081
< t:2019-08-17 19:02:26,403 f:cluster.py      l:1212 c:sdcm.cluster         p:DEBUG > 2019-08-17T19:02:14+00:00  ip-172-30-0-30 !INFO    | scylla.bin: [shard 3] database - Schema version changed to 17e1c678-7b2d-3386-a5d7-8f5d1ae30081
< t:2019-08-17 19:02:26,403 f:cluster.py      l:1212 c:sdcm.cluster         p:DEBUG > 2019-08-17T19:02:14+00:00  ip-172-30-0-30 !INFO    | scylla.bin: [shard 5] database - Schema version changed to 17e1c678-7b2d-3386-a5d7-8f5d1ae30081
< t:2019-08-17 19:02:26,403 f:cluster.py      l:1212 c:sdcm.cluster         p:DEBUG > 2019-08-17T19:02:14+00:00  ip-172-30-0-30 !INFO    | scylla.bin: [shard 13] database - Schema version changed to 17e1c678-7b2d-3386-a5d7-8f5d1ae30081
< t:2019-08-17 19:02:26,403 f:cluster.py      l:1212 c:sdcm.cluster         p:DEBUG > 2019-08-17T19:02:14+00:00  ip-172-30-0-30 !INFO    | scylla.bin: [shard 1] database - Schema version changed to 17e1c678-7b2d-3386-a5d7-8f5d1ae30081
< t:2019-08-17 19:02:26,403 f:cluster.py      l:1212 c:sdcm.cluster         p:DEBUG > 2019-08-17T19:02:14+00:00  ip-172-30-0-30 !INFO    | scylla.bin: [shard 4] database - Schema version changed to 17e1c678-7b2d-3386-a5d7-8f5d1ae30081
< t:2019-08-17 19:02:26,404 f:cluster.py      l:1212 c:sdcm.cluster         p:DEBUG > 2019-08-17T19:02:14+00:00  ip-172-30-0-30 !INFO    | scylla.bin: [shard 2] database - Schema version changed to 17e1c678-7b2d-3386-a5d7-8f5d1ae30081
< t:2019-08-17 19:02:26,404 f:cluster.py      l:1212 c:sdcm.cluster         p:DEBUG > 2019-08-17T19:02:14+00:00  ip-172-30-0-30 !INFO    | scylla.bin: [shard 7] database - Schema version changed to 17e1c678-7b2d-3386-a5d7-8f5d1ae30081
< t:2019-08-17 19:02:26,404 f:cluster.py      l:1212 c:sdcm.cluster         p:DEBUG > 2019-08-17T19:02:14+00:00  ip-172-30-0-30 !INFO    | scylla.bin: [shard 5] database - Schema version changed to 17e1c678-7b2d-3386-a5d7-8f5d1ae30081
< t:2019-08-17 19:02:26,404 f:cluster.py      l:1212 c:sdcm.cluster         p:DEBUG > 2019-08-17T19:02:14+00:00  ip-172-30-0-30 !INFO    | scylla.bin: [shard 3] database - Schema version changed to 17e1c678-7b2d-3386-a5d7-8f5d1ae30081
< t:2019-08-17 19:02:26,404 f:cluster.py      l:1212 c:sdcm.cluster         p:DEBUG > 2019-08-17T19:02:14+00:00  ip-172-30-0-30 !INFO    | scylla.bin: [shard 9] database - Schema version changed to 17e1c678-7b2d-3386-a5d7-8f5d1ae30081
< t:2019-08-17 19:02:26,404 f:cluster.py      l:1212 c:sdcm.cluster         p:DEBUG > 2019-08-17T19:02:14+00:00  ip-172-30-0-30 !INFO    | scylla.bin: [shard 1] database - Schema version changed to 17e1c678-7b2d-3386-a5d7-8f5d1ae30081
< t:2019-08-17 19:02:26,404 f:cluster.py      l:1212 c:sdcm.cluster         p:DEBUG > 2019-08-17T19:02:14+00:00  ip-172-30-0-30 !INFO    | scylla.bin: [shard 4] database - Schema version changed to 17e1c678-7b2d-3386-a5d7-8f5d1ae30081
< t:2019-08-17 19:03:01,411 f:nemesis.py      l:530  c:sdcm.nemesis         p:INFO  > sdcm.nemesis.LimitedChaosMonkey: <<<<<<<<<<<<<Finished random_disrupt_method stop_start_scylla_server
< t:2019-08-17 19:03:04,486 f:cluster.py      l:1212 c:sdcm.cluster         p:DEBUG > 2019-08-17T19:03:03+00:00  ip-172-30-0-72 !INFO    | scylla.bin: [shard 0] migration_manager - Requesting schema pull from 172.30.0.30:0
< t:2019-08-17 19:03:04,487 f:cluster.py      l:1212 c:sdcm.cluster         p:DEBUG > 2019-08-17T19:03:03+00:00  ip-172-30-0-72 !INFO    | scylla.bin: [shard 0] migration_manager - Pulling schema from 172.30.0.30:0
< t:2019-08-17 19:03:04,487 f:cluster.py      l:1212 c:sdcm.cluster         p:DEBUG > 2019-08-17T19:03:03+00:00  ip-172-30-0-72 !INFO    | scylla.bin: [shard 0] migration_manager - Requesting schema pull from 172.30.0.30:0
< t:2019-08-17 19:03:04,487 f:cluster.py      l:1212 c:sdcm.cluster         p:DEBUG > 2019-08-17T19:03:03+00:00  ip-172-30-0-72 !INFO    | scylla.bin: [shard 0] migration_manager - Requesting schema pull from 172.30.0.30:0
< t:2019-08-17 19:03:04,502 f:cluster.py      l:1212 c:sdcm.cluster         p:DEBUG > 2019-08-17T19:03:03+00:00  ip-172-30-0-72 !INFO    | scylla.bin: [shard 0] database - Schema version changed to 17e1c678-7b2d-3386-a5d7-8f5d1ae30081
< t:2019-08-17 19:03:04,503 f:cluster.py      l:1212 c:sdcm.cluster         p:DEBUG > 2019-08-17T19:03:03+00:00  ip-172-30-0-72 !INFO    | scylla.bin: [shard 0] migration_manager - Schema merge with 172.30.0.30:0 completed
< t:2019-08-17 19:03:04,503 f:cluster.py      l:1212 c:sdcm.cluster         p:DEBUG > 2019-08-17T19:03:03+00:00  ip-172-30-0-72 !INFO    | scylla.bin: [shard 0] migration_manager - Pulling schema from 172.30.0.30:0
< t:2019-08-17 19:03:04,539 f:cluster.py      l:1212 c:sdcm.cluster         p:DEBUG > 2019-08-17T19:03:04+00:00  ip-172-30-0-72 !INFO    | scylla.bin: [shard 0] database - Schema version changed to 17e1c678-7b2d-3386-a5d7-8f5d1ae30081
< t:2019-08-17 19:03:04,539 f:cluster.py      l:1212 c:sdcm.cluster         p:DEBUG > 2019-08-17T19:03:04+00:00  ip-172-30-0-72 !INFO    | scylla.bin: [shard 0] migration_manager - Schema merge with 172.30.0.30:0 completed
< t:2019-08-17 19:03:05,010 f:cluster.py      l:1212 c:sdcm.cluster         p:DEBUG > 2019-08-17T19:03:04+00:00  ip-172-30-0-31 !INFO    | scylla.bin: [shard 0] migration_manager - Requesting schema pull from 172.30.0.30:0
< t:2019-08-17 19:03:05,010 f:cluster.py      l:1212 c:sdcm.cluster         p:DEBUG > 2019-08-17T19:03:04+00:00  ip-172-30-0-31 !INFO    | scylla.bin: [shard 0] migration_manager - Pulling schema from 172.30.0.30:0
< t:2019-08-17 19:03:05,010 f:cluster.py      l:1212 c:sdcm.cluster         p:DEBUG > 2019-08-17T19:03:04+00:00  ip-172-30-0-31 !INFO    | scylla.bin: [shard 0] migration_manager - Requesting schema pull from 172.30.0.30:0
< t:2019-08-17 19:03:05,014 f:cluster.py      l:1212 c:sdcm.cluster         p:DEBUG > 2019-08-17T19:03:04+00:00  ip-172-30-0-31 !INFO    | scylla.bin: [shard 0] database - Schema version changed to 17e1c678-7b2d-3386-a5d7-8f5d1ae30081
< t:2019-08-17 19:03:05,014 f:cluster.py      l:1212 c:sdcm.cluster         p:DEBUG > 2019-08-17T19:03:04+00:00  ip-172-30-0-31 !INFO    | scylla.bin: [shard 0] migration_manager - Schema merge with 172.30.0.30:0 completed
< t:2019-08-17 19:03:05,014 f:cluster.py      l:1212 c:sdcm.cluster         p:DEBUG > 2019-08-17T19:03:04+00:00  ip-172-30-0-31 !INFO    | scylla.bin: [shard 0] migration_manager - Pulling schema from 172.30.0.30:0
< t:2019-08-17 19:03:05,020 f:cluster.py      l:1212 c:sdcm.cluster         p:DEBUG > 2019-08-17T19:03:04+00:00  ip-172-30-0-31 !INFO    | scylla.bin: [shard 0] database - Schema version changed to 17e1c678-7b2d-3386-a5d7-8f5d1ae30081
< t:2019-08-17 19:03:05,020 f:cluster.py      l:1212 c:sdcm.cluster         p:DEBUG > 2019-08-17T19:03:04+00:00  ip-172-30-0-31 !INFO    | scylla.bin: [shard 0] migration_manager - Schema merge with 172.30.0.30:0 completed
< t:2019-08-17 19:03:11,440 f:cluster.py      l:1212 c:sdcm.cluster         p:DEBUG > 2019-08-17T19:03:03+00:00  ip-172-30-0-192 !INFO    | scylla.bin: [shard 0] migration_manager - Requesting schema pull from 172.30.0.30:0
< t:2019-08-17 19:03:11,440 f:cluster.py      l:1212 c:sdcm.cluster         p:DEBUG > 2019-08-17T19:03:03+00:00  ip-172-30-0-192 !INFO    | scylla.bin: [shard 0] migration_manager - Pulling schema from 172.30.0.30:0
< t:2019-08-17 19:03:11,440 f:cluster.py      l:1212 c:sdcm.cluster         p:DEBUG > 2019-08-17T19:03:03+00:00  ip-172-30-0-192 !INFO    | scylla.bin: [shard 0] migration_manager - Requesting schema pull from 172.30.0.30:0
< t:2019-08-17 19:03:11,440 f:cluster.py      l:1212 c:sdcm.cluster         p:DEBUG > 2019-08-17T19:03:03+00:00  ip-172-30-0-192 !INFO    | scylla.bin: [shard 0] migration_manager - Requesting schema pull from 172.30.0.30:0
< t:2019-08-17 19:03:11,444 f:cluster.py      l:1212 c:sdcm.cluster         p:DEBUG > 2019-08-17T19:03:03+00:00  ip-172-30-0-192 !INFO    | scylla.bin: [shard 0] database - Schema version changed to 17e1c678-7b2d-3386-a5d7-8f5d1ae30081
< t:2019-08-17 19:03:11,444 f:cluster.py      l:1212 c:sdcm.cluster         p:DEBUG > 2019-08-17T19:03:03+00:00  ip-172-30-0-192 !INFO    | scylla.bin: [shard 0] migration_manager - Schema merge with 172.30.0.30:0 completed
< t:2019-08-17 19:03:11,444 f:cluster.py      l:1212 c:sdcm.cluster         p:DEBUG > 2019-08-17T19:03:03+00:00  ip-172-30-0-192 !INFO    | scylla.bin: [shard 0] migration_manager - Pulling schema from 172.30.0.30:0
< t:2019-08-17 19:03:11,450 f:cluster.py      l:1212 c:sdcm.cluster         p:DEBUG > 2019-08-17T19:03:03+00:00  ip-172-30-0-192 !INFO    | scylla.bin: [shard 0] database - Schema version changed to 17e1c678-7b2d-3386-a5d7-8f5d1ae30081
< t:2019-08-17 19:03:11,450 f:cluster.py      l:1212 c:sdcm.cluster         p:DEBUG > 2019-08-17T19:03:03+00:00  ip-172-30-0-192 !INFO    | scylla.bin: [shard 0] migration_manager - Schema merge with 172.30.0.30:0 completed
< t:2019-08-17 19:03:20,021 f:cluster.py      l:1212 c:sdcm.cluster         p:DEBUG > 019-08-17T19:03:05+00:00  ip-172-30-0-31 !INFO    | scylla.bin: [shard 0] migration_manager - Requesting schema pull from 172.30.0.30:0
< t:2019-08-17 19:03:20,021 f:cluster.py      l:1212 c:sdcm.cluster         p:DEBUG > 2019-08-17T19:03:05+00:00  ip-172-30-0-31 !INFO    | scylla.bin: [shard 0] migration_manager - Pulling schema from 172.30.0.30:0
< t:2019-08-17 19:03:20,027 f:cluster.py      l:1212 c:sdcm.cluster         p:DEBUG > 2019-08-17T19:03:05+00:00  ip-172-30-0-31 !INFO    | scylla.bin: [shard 0] database - Schema version changed to 17e1c678-7b2d-3386-a5d7-8f5d1ae30081
< t:2019-08-17 19:03:20,027 f:cluster.py      l:1212 c:sdcm.cluster         p:DEBUG > 2019-08-17T19:03:05+00:00  ip-172-30-0-31 !INFO    | scylla.bin: [shard 0] migration_manager - Schema merge with 172.30.0.30:0 completed
```

Despite it was reported that schema version for node **172.30.0.30** has been changed to ```17e1c678-7b2d-3386-a5d7-8f5d1ae30081```, in the gossip and in the system.peers it remain 
```a06c0c09-c332-3a38-a11b-24fc1106419c```:
```
Gossipinfo schema version and status of all nodes:
 {'172.30.0.31': {'status': 'NORMAL', 'schema': '17e1c678-7b2d-3386-a5d7-8f5d1ae30081'},
 '172.30.0.192': {'status': 'NORMAL', 'schema': '17e1c678-7b2d-3386-a5d7-8f5d1ae30081'}, 
'172.30.0.72': {'status': 'NORMAL', 'schema': '17e1c678-7b2d-3386-a5d7-8f5d1ae30081'}, 
'172.30.0.30': {'status': 'NORMAL', 'schema': 'a06c0c09-c332-3a38-a11b-24fc1106419c'}}
```

The schema version on **172.30.0.30** was remained different during about 4 hours up to next stop_start_scylla_server nemesis. Next stop_start_scylla_server nemesis restared the node with IP **172.30.0.31**:
```
< t:2019-08-17 23:26:14,754 f:nemesis.py      l:283  c:sdcm.nemesis         p:DEBUG > sdcm.nemesis.LimitedChaosMonkey: Set current_disruption -> StopStartService Node longevity-200gb-48h-verify-limited--db-node-5f3e71cc-2 [34.205.125.76 | 172.30.0.31] (seed: False)
```

After **172.30.0.31** node was restart, it's version became the different from others nodes:
```
< t:2019-08-17 23:31:06,462 f:sct_events.py   l:455  c:sdcm.sct_events      p:INFO  > 2019-08-17 23:31:06.450: (ClusterHealthValidatorEvent Severity.CRITICAL): type=error name=GossipNodeSchemaVersion node=longevity-200gb-48h-verify-limited--db-node-5f3e71cc-1 error=Schema version is not same on all nodes in gossip info: 
172.30.0.31: a06c0c09-c332-3a38-a11b-24fc1106419c
172.30.0.192: 17e1c678-7b2d-3386-a5d7-8f5d1ae30081
172.30.0.72: 17e1c678-7b2d-3386-a5d7-8f5d1ae30081
 172.30.0.30: 17e1c678-7b2d-3386-a5d7-8f5d1ae30081
```

The version was different during next two nemesis but after truncate nemesis (truncate the table) it became synced.
And stays synced up to hard reboot node nemesis. 
After hard reboot again - wrong schema version is on restarted node.

Logs: 
```
https://cloudius-jenkins-test.s3.amazonaws.com/5f3e71cc-9ca0-4ed6-9896-6956145d4898/job_log.zip
```

**Comment by avikivity** [comment] 2019-08-26 14:57
@tgrabiec is the #4647 reproducer?

**Comment by tgrabiec** [comment] 2019-08-27 09:44
@avikivity There are some bits which don't fit. Like the fact that `system.peers` also contained a stale version, and that schema pull didn't fix this.

We update `system.peers` before printing `Schema version changed to `, so https://github.com/scylladb/scylla/commit/d70c2db09c4ea5d9960dbcade5954b2c1c988cde would not fix this.

**Comment by slivne** [comment] 2019-09-08 06:57
@roydahan / @bentsi - we need to reproduce this again - the machines have been lost - please try and get a reproducer today and have it for tomek for monday morning

**Comment by bhalevy** [comment] 2019-09-11 12:38
@tgrabiec said:
> I've found an explanation, it's #3760 still, but can happen without UDFs

**Comment by slivne** [comment] 2019-09-11 12:41
@tgrabiec if we revert 7f64a6e for 3.1 will this solve the issue and then work on doing the fixes on master for 3.2

**Comment by tgrabiec** [comment] 2019-09-11 14:57
It was not about this issue though.

**Comment by tgrabiec** [comment] 2019-09-11 14:57
Yes. But again, not this issue.

**Comment by slivne** [comment] 2019-09-11 15:47
@tgrabiec so its clear 

- the issue you mentioned in https://github.com/scylladb/scylla/issues/4878#issuecomment-525226423, was not introduced by  7f64a6e - and you still need a reproducer for this case to make progress
- in your view for 3.1 we should revert  7f64a6e to address a regression it introduced and you do not expect that would lead to side effects

**Comment by espindola** [comment] 2019-09-11 18:49
For what it is worth, I think it is possible to revert 7f64a6ec4bda96b53dc2f7fbc60b7ad5fd900c60, I still don't have an opinion on which issues that revert may hide.

**Comment by espindola** [comment] 2019-09-11 19:13
I have pushed a patch with the revert to https://github.com/espindola/scylla espindola/revert-my-patch

**Comment by tgrabiec** [comment] 2019-09-11 20:59
On Wed, Sep 11, 2019 at 5:47 PM Shlomi Livne <notifications@github.com>
wrote:

> @tgrabiec <https://github.com/tgrabiec> so its clear
>
>    - the issue you mentioned in #4878 (comment)
>    <https://github.com/scylladb/scylla/issues/4878#issuecomment-525226423>,
>    was not introduced by 7f64a6e
>    <https://github.com/scylladb/scylla/commit/7f64a6ec4bda96b53dc2f7fbc60b7ad5fd900c60>
>    - and you still need a reproducer for this case to make progress
>    - in your view for 3.1 we should revert 7f64a6e
>    <https://github.com/scylladb/scylla/commit/7f64a6ec4bda96b53dc2f7fbc60b7ad5fd900c60>
>    to address a regression it introduced and you do not expect that would lead
>    to side effects
>
> The last point is incorrect. I don't think reverting 7f64a6e would
actually help because even if we manage to deserialize the table's schema
definition, if the keyspace is missing we will fail to apply the write
anyway, just in a later phase. So the real problem is that we missed the
keyspace update. Perhaps we're more likely to run into the problem because
we're testing with more keyspaces now, and it's more likely that we added a
keyspace (kesypace_deflate) while some node is down? \cc @juliayakovlev Or
schema sync is slower than before, or nodes are quicker to notice that
restarted node is up.

In any case, I think the proper fix is to fix #3760 as described in the
comments there.

**Comment by slivne** [comment] 2019-09-12 06:53
@tgrabiec thanks - I understand that the keyspace part needs to be fixed - yet for the sake of getting 3.1.0 OUT I would like your help with clarifying the following scenario 

Scenario: 
1. 3 nodes cluster A,B,C
2. a keyspace is created ks with RF=3
3. node C shutdown
4. a table is created ks.tb without UDTs
5. a write workload CL=QUORUM is run with ks.tb
6. node C started

Can writes / mutation_write fail on node C when it starts in 3.0 ? (AFAICT - the answer is no)

Can writes / mutation_write fail on node C when it starts in 3.1 ? (AFAICT - the answer is yes)

In the scenario above if the keyspace was created after node C was sutdown (changing the order of 2. , 3.) writes / mutation writes can fail on node C both for 3.0 and 3.1 - right ?

**Comment by tgrabiec** [comment] 2019-09-12 07:45
My analysis misses one thing. Writes will do a full schema sync after
unfreezeing table schema definition. So reverting 7f64a6e will
actually help for writes.

For reads, we still need #3760.

On Thu, Sep 12, 2019 at 8:53 AM Shlomi Livne <notifications@github.com>
wrote:

> @tgrabiec <https://github.com/tgrabiec> thanks - I understand that the
> keyspace part needs to be fixed - yet for the sake of getting 3.1.0 OUT I
> would like your help with clarifying the following scenario
>
> Scenario:
>
>    1. 3 nodes cluster A,B,C
>    2. a keyspace is created ks with RF=3
>    3. node C shutdown
>    4. a table is created ks.tb without UDTs
>    5. a write workload CL=QUORUM is run with ks.tb
>    6. node C started
>
> Can writes / mutation_write fail on node C when it starts in 3.0 ? (AFAICT
> - the answer is no)
>
Can writes / mutation_write fail on node C when it starts in 3.1 ? (AFAICT
> - the answer is yes)
>
The answer is no for both.

In the scenario above if the keyspace was created after node C was sutdown
> (changing the order of 2. , 3.) writes / mutation writes can fail on node C
> both for 3.0 and 3.1 - right ?
>

Only on 3.1

>

**Comment by slivne** [comment] 2019-09-15 06:37
revert for 7f64a6e  was done in 3.1 024d1563ad61898bb4fe9dfd7219ad3f1d7f5a30 

leaving this issue open for the original case if this reproduces https://github.com/scylladb/scylla/issues/4878#issue-483460836

**Comment by bhalevy** [comment] 2019-09-19 10:53
@roydahan please verify that it wasn't reproduced and close if so

**Comment by bhalevy** [comment] 2019-10-02 10:37
According to @roydahan this doesn't reproduce. Closing...

**Closed by bhalevy** 2019-10-02 10:37 UTC
Labels: Regression, bug, high, schema changes
