### ISSUE TITLE
test_add_udt_to_another_data_types is flaky

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#5336] opened 2019-11-24 11:32 UTC
If this issue is with the test rather than with scylla please open an issue on scylla-dtest and close this one.

https://jenkins.scylladb.com/job/scylla-master/job/dtest-release/294/testReport/junit/user_types_test/TestUserTypes/test_add_udt_to_another_data_types/
Scylla 623071020e354e5cec0e4323dbc4a7b22bc27aca
```
Error from server: code=2200 [Invalid query] message="Invalid tuple literal for src_entity: component 5 is not of type frozen<user_refs>"
```
Same error in:
https://jenkins.scylladb.com/job/scylla-master/job/dtest-release/302/testReport/user_types_test/TestUserTypes/test_add_udt_to_another_data_types/
https://jenkins.scylladb.com/job/scylla-master/job/dtest-release/310/testReport/user_types_test/TestUserTypes/test_add_udt_to_another_data_types/

https://jenkins.scylladb.com/job/scylla-master/job/dtest-release/309/testReport/junit/user_types_test/TestUserTypes/test_add_udt_to_another_data_types/
Scylla ff567649fa34b10c18971b98a14985e84aafbce9
```
Expected a row count of 2000 in table 'entity', but got 1697
```

**Comment by bhalevy** [comment] 2019-12-01 07:30
Seen again in [dtest-release#309](https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/309/testReport/user_types_test/TestUserTypes/test_add_udt_to_another_data_types/)

**Comment by bhalevy** [comment] 2019-12-09 10:12
See in https://jenkins.scylladb.com/view/scylla-3.2/job/scylla-3.2/job/dtest-release/20/testReport/user_types_test/TestUserTypes/test_add_udt_to_another_data_types/

**Comment by juliayakovlev** [comment] 2019-12-11 16:47
To prevent "Expected a row count of 2000 in table 'entity', but got 1697" error I added sleep before validation. (issue #1184, PR #[1185](https://github.com/scylladb/scylla-dtest/pull/1185))

Error "```Error from server: code=2200 [Invalid query] message="Invalid tuple literal for src_entity: component 5 is not of type frozen<user_refs>""``` can't reproduce

**Comment by slivne** [comment] 2020-01-02 10:54
closing this issue as there was a pull request merged related to this test 

If this happens again lets reopen

**Closed by slivne** 2020-01-02 10:54 UTC
Labels: dtest

**Comment by bhalevy** [comment] 2020-01-16 13:02
For the record, seen in https://jenkins.scylladb.com/view/scylla-3.2/job/scylla-3.2/job/dtest-release/lastFailedBuild/testReport/user_types_test/TestUserTypes/test_add_udt_to_another_data_types/
aaa06e8ff6de3b6642c91dd0582b11cc90d355e7 is not backported to 3.2 yet.

**Comment by kbr-scylla** [comment] 2023-09-18 09:41
I've just got a very similar failure on https://github.com/scylladb/scylladb/pull/15331:

https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/3711/testReport/junit/user_types_test/TestUserTypes/Tests___Sanity_Tests___test_add_udt_to_another_data_types/
```
cassandra.InvalidRequest: Error from server: code=2200 [Invalid query] message="Invalid tuple literal for entity_info: component 5 is not of type frozen<user_refs>"
```
