### ISSUE TITLE
 Assertion `_sorted_tokens.size() > 0' failed

### ISSUE THREAD

**Issue by infordb** [scylladb/scylla#2741] opened 2017-08-30 01:07 UTC
*Installation details*
Scylla version (or git commit hash): 1.7.1

Scylla does not start with "Assertion `_sorted_tokens.size() > 0' failed"
Do you know how to start without losing data

related issue : https://github.com/scylladb/scylla/issues/2064

Aug 30 08:56:29 fomstap01 scylla: [shard 0] database - Schema version changed to 63842a27-5fd6-39b0-a617-f2f08c94bb29
Aug 30 08:56:29 fomstap01 scylla: [shard 0] storage_service - Using saved tokens {9113800366049820497, 9082109347525392062, 8788829840652193116, 8633585271944939460, 8550367765355704038, 8505829471400427219, 8472487349300109351, 8444233102453345215, 8175440151666907459, 8097708282512664494, 8053739722575119446, 7972209674596942294, 8920366324334432147, 786402186811633613, 7778761064238480792, 7727471840613739863, 7664539543847252518, 7597662817033497133, 747586113973788514, 7367247737322452114, 7220604988122729109, 71217417939679115, 7095043707553769751, 6806481855446012343, 6743900273421039399, 6611031201282616248, 6609935888004000451, 6587537153332768033, 6560080713641846080, 8163003465437720375, 6543201151772696973, 6351927557790674208, 631536061371743494, 629963751734975084, 6275229377242030946, 6107096084197702359, 6056251524164293675, 7434562899976226044, -7572825679349980733, 4439032166061760889, -6488731293144053066, 8369905304987368718, -6651994656460801985, -6435586732207841045, -6377959519628259729, 543419925858874512, -5718567113178703463, -5600007921047221989, -1003647264723484513, -5718776219592829785, -7528647151850627710, -5244062222778702352, -5149822678703774002, -4987338937509031262, -3541727657034009915, -1473228851419663900, -4975812361971875996, 3591609902787143699, -5729663677520134109, -7051243653386500906, 6160470663907468822, -4943102788277506537, -4663014217037665465, -4877592131599497995, -4861260764318503457, 308311303517474239, -4647395963789647696, 2809690262391340378, -4554458146441859790, -4549298359988120094, -6661568157645852417, -6266792618914066692, 4851239092674166732, 589196687620464561, 7576961906958009616, -1751026578698633227, 3288588111930790786, -7062866486336477797, -907987067493795419, -6621479164651909803, -2349228979121826867, -4107817950601415909, -225861539077470105, -7499639347094855456, -3729122981162703858, 2149052720146581123, -1011118128887364120, -9087054306623529749, -4139208774332520380, -4065133662507362934, 3944117313242679219, 4012179700826625370, -6211509871234184884, -2186925731045174677, -4817360419732847954, -4791194571979251253, 1755653905300289574, -1808253140708683339, 368659216633636110, 9164343760619683655, 8379169798037219268, 3950322543719498340, -3095979406179282731, -4252169943887785742, -1232060373644610341, -7085606250522164780, -1297213250304630918, -1668573820643266506, -3288472587143635950, -6050575669728890589, -5834263867596205929, -1721264732846267736, -4909432352012916317, 7133380947920591728, 6595334428975535440, -8586139904478499133, 7399228032747935073, -3787571668500619870, -1509601032234336044, -4014284828948035974, 7254966159318075385, -8941321219288243885, 1076937278300749525, 4078856806735772140, 1631031103904362970, -3490371888812731875, -8282105734663524830, 2444082981059190061, -2205485308288811956, -6363291855308312375, -2001805909134116247, 8247060625376625138, 6731178087744111424, 5976572428301679395, -1355135381268939983, -3331573642798136700, -2856063112295935713, -2223572136930209462, -4493164102608567932, 4493702362859912624, -3720524788783455130, -3684827941026273320, 2439155839772042020, -3964355922305328301, -1681202738228020238, -2993934047999785846, -7717521579801428957, -7682413973956077164, -8688706351495449627, -2603637608945603348, -476295914367653670, -4648411312741378779, -2756821148452979860, -3366643691008065976, -3437172566614951548, -440865399616669726, 1522554291107792973, -369031354839383938, 2026053652433253661, 309962587483401724, -6290641229926224278, 1724809266096932470, -377020625612668163, -4996322700709630228, -6674447001333343095, 8480471060194703953, -3943354804551514102, 3800947585528267153, -7737818491354145431, -8737077323869421272, -8810796936322071839, 5620293657007866752, -8225786394957414057, -8596548905747342804, 2667005972859361668, 1924631992810371984, -8657536041700877814, 5422493227176150880, -8753258424101201235, -4223804508057567078, 4497945207422662703, -8862571441361713055, 1334862614064068677, -969845268286125801, 1061220764022004288, 1423087842599966865, 1424042176768827312, 1443196970270571660, 7382211088832289391, 5383394826748733971, -8137244708607244530, 1494713721568324745, 8981287446124041937, 7394655984955708294, 692581081052505472, -6570022865491925474, 1700179317109923564, 1550958661121241333, 1951364029058435747, 1741701629216298716, 1997758650322892491, 2049136567863842773, -239529531198959664, 5850097128589863759, 2352591625526623860, -2541937831409191229, 267788562677001979, 2357427107199436955, 4968338955167712126, -8720424172973048761, 2607468805589271305, 2614150521319152031, 3062170896373302159, 8965177694447329252, 4861867469704286165, 3188601899593273764, 6694315492988456323, 3718144978174068590, 3173031241397795834, 3241952773045539560, 3430695013753423233, -4752327946980725728, -8153446467793382353, 3498401734459827171, -1244475939206842170, 3546619282958935137, 3631145592289337251, 3648414019245548304, 426649313839782172, -710002148045645964, 3063826337900106652, 4398665507701729928, 4432006225336768340, 4474216109105715473, 4596759099262802995, -2203055866796187238, -8716208653206045848, 4723945391277164643, 4895259254900096917, 607929203075598736, 5262616521466511858, 5416840288718367458, -7387937473952796971, 5432141691159530989, 6238438201908941266, 5527303752036608138, 2922910156358715433, 5532466375338446247, 2840498327514482439, 559589867678300687, 5697067889137552556, 5880638184244148453, -2628913491708917824, 5893824421146498357, 5917587761358168672, 6048337604886921120}
Aug 30 08:56:39 fomstap01 scylla: scylla: locator/token_metadata.cc:144: size_t **locator::token_metadata::first_token_index(const token&) const: Assertion `_sorted_tokens.size() > 0' failed.**
Aug 30 08:56:39 fomstap01 scylla: Aborting on shard 0.
Aug 30 08:56:39 fomstap01 scylla: Backtrace:
Aug 30 08:56:39 fomstap01 scylla: 0x00000000004e064a
Aug 30 08:56:39 fomstap01 scylla: 0x00000000004e0753
Aug 30 08:56:39 fomstap01 scylla: 0x00007f75eb1080ff
Aug 30 08:56:39 fomstap01 scylla: 0x00007f75ead6c5f6
Aug 30 08:56:39 fomstap01 scylla: 0x00007f75ead6dce7
Aug 30 08:56:39 fomstap01 scylla: 0x00007f75ead65565
Aug 30 08:56:39 fomstap01 scylla: 0x00007f75ead65611
Aug 30 08:56:39 fomstap01 scylla: 0x00000000011a7fb1
Aug 30 08:56:39 fomstap01 scylla: 0x00000000011a7fc8
Aug 30 08:56:39 fomstap01 scylla: 0x000000000119bc8c
Aug 30 08:56:39 fomstap01 scylla: 0x0000000000e7eacf
Aug 30 08:56:39 fomstap01 scylla: 0x0000000000e7eb9b
Aug 30 08:56:39 fomstap01 scylla: 0x0000000000ea3987
Aug 30 08:56:39 fomstap01 scylla: 0x0000000000ea46c7
Aug 30 08:56:39 fomstap01 scylla: 0x0000000000ea637b
Aug 30 08:56:39 fomstap01 scylla: 0x0000000000ea7837
Aug 30 08:56:39 fomstap01 scylla: 0x0000000000d171f4
Aug 30 08:56:39 fomstap01 scylla: 0x0000000000d18a81
Aug 30 08:56:39 fomstap01 scylla: 0x0000000000f0be54
Aug 30 08:56:39 fomstap01 scylla: 0x0000000000f0d03a
Aug 30 08:56:39 fomstap01 scylla: 0x0000000001550b04
Aug 30 08:56:39 fomstap01 scylla: 0x00000000015782ac
Aug 30 08:56:39 fomstap01 scylla: 0x00000000015475e0
Aug 30 08:56:39 fomstap01 scylla: 0x00000000004e20bf
Aug 30 08:56:39 fomstap01 scylla: 0x0000000000531c12
Aug 30 08:56:39 fomstap01 scylla: 0x00000000005b1c1c
Aug 30 08:56:39 fomstap01 scylla: 0x000000000047335d
Aug 30 08:56:39 fomstap01 scylla: 0x00007f75ead58b14
Aug 30 08:56:39 fomstap01 scylla: 0x00000000004de05e
Aug 30 08:56:40 fomstap01 systemd-coredump: Removed old coredump core.scylla.993.02e743f6ae7948d69b85d5e6e4be3d92.29867.1504050849000000.
Aug 30 08:57:21 fomstap01 systemd: scylla-server.service: main process exited, code=dumped, status=6/ABRT
Aug 30 08:57:21 fomstap01 systemd: Unit scylla-server.service entered failed state.
Aug 30 08:57:21 fomstap01 systemd: scylla-server.service failed.

**Comment by asias** [comment] 2017-08-30 07:13
Do you start scylla then systemctl stop scylla-server?

**Comment by tgrabiec** [comment] 2017-08-30 07:32
@infordb Does it consistently refuse to start? Refs #2273.

**Comment by asias** [comment] 2017-08-30 07:43
Refs #2721 @haaawk

**Comment by infordb** [comment] 2017-08-30 08:06
The systemctl command failed to start scylla after stop
After removing sstables, we could start scylla
Do you know how to start scylla without losing data in this case.

**Comment by tgrabiec** [comment] 2017-08-30 08:11
@asias It's not related to #2721, he didn't attempt to stop during boot.

**Comment by tgrabiec** [comment] 2017-08-30 08:21
@infordb If this is #2273 (likely, but not certain), then you could try starting the node again. The root cause was an initialization race, so it not always happens. Or, disable auth on that node, or drop local auth tables.

The fix for the race was backported, so it should find its way to future releases.

**Comment by slivne** [comment] 2017-12-21 11:32
closing this - we can reopen if needed

**Closed by slivne** 2017-12-21 11:32 UTC
Labels: bug, high
