### ISSUE TITLE
longevity-1.7: got warning (about IO error & rpc timeout) in draining db node

### ISSUE THREAD

**Issue by amoskong** [scylladb/scylla#2149] opened 2017-03-09 03:12 UTC
*Installation details*
Scylla version (or git commit hash): 1.7.rc0-0.20170207.0429e5d
Cluster size: 6
OS (RHEL/CentOS/Ubuntu/AWS AMI): CentOS7

[The jenkins job](http://jenkins.cloudius-systems.com/job/scylla-1.7-longevity-gce/label=gce/16/) was started at 14:37, got first issue after about `half hour`, and got second issue after about `2 hours`. 

Question:
Are those two warning/error serious?

Issue 1: The target node raised warning/error, and it failed to drain the node
```
2017-03-08 15:23:11,492 nemesis          L0161 INFO | sdcm.nemesis.ChaosMonkey: Drainer Node longevity-1-7-gce-amosbranch-scylla-db-node-aca161cb-5 [35
.185.99.153 | 10.240.0.42] (seed: False)
2017-03-08 15:23:25,242 remote           L0194 DEBUG| [10.240.0.42] [stdout] Mar 08 15:23:25 warning|  [shard 3] storage_service - Shutting down commun
ications due to I/O errors until operator intervention
2017-03-08 15:27:07,754 nemesis          L0109 ERROR| sdcm.nemesis.ChaosMonkey: nodetool command 'nodetool -h localhost drain' failed on node Node long
evity-1-7-gce-amosbranch-scylla-db-node-aca161cb-5 [35.185.99.153 | 10.240.0.42] (seed: False): Command: /bin/ssh -tt -a -x  -o ControlPath=/var/tmp/ss
h-mastereqLmtT/socket -o StrictHostKeyChecking=no -o UserKnownHostsFile=/var/tmp/tmpNkdzwT -o BatchMode=yes -o ConnectTimeout=300 -o ServerAliveInterva
l=300 -l scylla-test -p 22 -i ~/.ssh/scylla-test 10.240.0.42 "nodetool -h localhost drain"
```

Issue 2: Success to drain the target node, but another node raise warning/error about rpc timeout to content with target node

```
2017-03-08 16:40:08,543 nemesis          L0161 INFO | sdcm.nemesis.ChaosMonkey: Drainer Node longevity-1-7-gce-amosbranch-scylla-db-node-aca161cb-7 [10
4.196.149.29 | 10.240.0.19] (seed: False)
2017-03-08 16:40:20,194 nemesis          L0103 DEBUG| sdcm.nemesis.ChaosMonkey: Command '/bin/ssh -tt -a -x  -o ControlPath=/var/tmp/ssh-masterR5uX42/s
ocket -o StrictHostKeyChecking=no -o UserKnownHostsFile=/var/tmp/tmp4AhGrP -o BatchMode=yes -o ConnectTimeout=300 -o ServerAliveInterval=300 -l scylla-
test -p 22 -i ~/.ssh/scylla-test 10.240.0.19 "nodetool -h localhost drain"' duration -> 11.6391708851 s
....
...
2017-03-08 16:42:03,099 remote           L0194 DEBUG| [10.240.0.43] [stdout] Mar 08 16:42:03 warning|  [shard 0] gossip - Fail to send EchoMessage to 10.240.0.19:0: rpc::timeout_error (rpc call timed out)
2017-03-08 16:43:59,513 nemesis          L0274 DEBUG| sdcm.nemesis.ChaosMonkey: Drainer Node longevity-1-7-gce-amosbranch-scylla-db-node-aca161cb-7 [104.196.149.29 | 10.240.0.19] (seed: False) duration -> 231 s
```

[job.log.zip](https://github.com/scylladb/scylla/files/829624/job.log.zip)

Command to filter the log: `cat job.log |egrep "(error|ERROR|Error|nemesis)"|less|grep -v 'Start ->'|grep -v 'Bad file'|grep -v 'journal'|less`

**Comment by slivne** [comment] 2017-03-14 12:26
@kongove is the issue of drain reproducible the io error is bad - not clear why it happend (and yes we need better logging of such problems).

**Comment by kongove** [comment] 2017-03-15 13:30
I will try to reproduce the problem manually.

**Comment by slivne** [comment] 2017-03-29 12:33
@kongove ping ... any update on this ?

**Comment by slivne** [comment] 2017-04-02 10:10
@kongove ping

**Comment by kongove** [comment] 2017-04-02 14:43
update - Apr 2: I still didn't reproduce the issue with single drainer test
I will do more time stress test before drain one node.

**Comment by kongove** [comment] 2017-04-02 23:50
Another simple scenario to reproduce the error:
keep running c-stress in background, and repeatedly to execute Drainer nemesis (choose one non-seed node to drain, restart if it's fail to drain)

Result:
The rpc::timeout_error occurred after c-s run 6 hours.

----

I'm testing with another scenario, will update the result later.
1. keep running c-stress in background
2. wait 7 hours
3. start to repeatedly to execute Drainer nemesis (choose one non-seed node to drain, restart if it's fail to drain)

**Comment by kongove** [comment] 2017-04-05 07:51
Update: I didn't reproduce with above steps.

```
1. keep running c-stress in background
2. wait 7 hours
3. start to repeatedly to execute Drainer nemesis (choose one non-seed node to drain, restart if it's fail to drain)
```

**Comment by slivne** [comment] 2017-04-06 10:16
Amos

I am lost I admit
 - if there is a reproducer - can you repost it and make it clear that you
have been able to reproduce using it more then once.
- if there is no reproducer and you are still hitting this I guess we will
needsomehow to allow pawel access to a system that hits this and allow him
to chekc if he can find additional info.

**Comment by kongove** [comment] 2017-04-06 15:55
On Thu, Apr 6, 2017 at 6:16 PM, Shlomi Livne <notifications@github.com>
wrote:

> Amos
>
> I am lost I admit
> - if there is a reproducer - can you repost it and make it clear that you
> have been able to reproduce using it more then once.
>


> - if there is no reproducer and you are still hitting this I guess we will
> needsomehow to allow pawel access to a system that hits this and allow him
> to chekc if he can find additional info.
>

There is no reproducer, I will give pawel access to a system that hits the
issue.

**Comment by pdziepak** [comment] 2017-04-10 09:45
Those RPC do not look very worrying – a node shuts down and the others cannot reach it or don't get any response to requests that were in progress.
It looks like our drain implementation (`storage_service::drain()`) stops RPC server first and only then calls `stop_gossiping()`:
```c++
ss.set_mode(mode::DRAINING, "starting drain process", true);
ss.shutdown_client_servers().get();
gms::stop_gossiping().get();
```

@asias, wouldn't it be better to call `stop_gossiping()` before shutting down RPC servers?

**Comment by tzach** [comment] 2017-04-10 09:57
@pdziepak according to your (reasonable) explanation, we should have seen this issue before, but we didnt, and it is repeating in 1.7

**Comment by kongove** [comment] 2017-04-11 15:07
Reproduced the RPC::timeout_error in longevity test, the test stop at that time. I sent an email with detail info.

Mail Subject: About reproduce rpc_timeout issue in drain test

**Comment by slivne** [comment] 2017-04-12 10:11
the issue "storage_service - Shutting down communications due to I/O errors until operator intervention" could not be reproduced - if i happens again lets pen a new issue for that.

the issue here is about getting rpc warnings when running drain - this is not a regression - we need to fix it if possible but it should not block 1.7 pushing it out to 1.8

**Comment by slivne** [comment] 2017-05-07 13:17
@asias ping can you please review @pdziepak suggestion to change the order

**Comment by slivne** [comment] 2017-05-25 10:34
@asias ping can you please review @pdziepak suggestion to change the order

**Comment by slivne** [comment] 2017-06-29 12:17
@asias ping

**Comment by slivne** [comment] 2017-07-09 12:59
@asias ping

@roydahan  / @harelassayag  / @amoskong - are we still getting this errors / issues  ?

**Comment by slivne** [comment] 2017-07-27 09:23
@asias ping

@roydahan / @harelassayag / @amoskong - are we still getting this errors / issues ?

**Comment by asias** [comment] 2017-07-27 13:02
> Those RPC do not look very worrying – a node shuts down and the others cannot reach it or don't get any response to requests that were in progress.
> It looks like our drain implementation (storage_service::drain()) stops RPC server first and only then calls stop_gossiping():
> 
> ss.set_mode(mode::DRAINING, "starting drain process", true);
> ss.shutdown_client_servers().get();
> gms::stop_gossiping().get();
> @asias, wouldn't it be better to call stop_gossiping() before shutting down RPC servers?

ss.shutdown_client_servers().get() does not shutdown rpc server at all.  it shutdown the thrift and cql server.

See:

0 future<> storage_service::shutdown_client_servers() {
1     return do_stop_rpc_server().then([this] { return do_stop_native_transport(); });
2 }

So changing the order won't help.

**Comment by asias** [comment] 2017-07-27 13:05
The rpc warning is not a bug. it is expected that the peer will see this rpc timeout if local node shutdown itself.

I suggest closing this issue.

If we see the io error again, open a new issue.

**Closed** 2017-07-30 10:12 UTC
Labels: bug
