### ISSUE TITLE
reactor stalls peak during latency during ops test - synchronous reads

### ISSUE THREAD

**Issue by fgelcer** [scylladb/scylla#8878] opened 2021-06-17 12:03 UTC
*Installation details*
Scylla version (or git commit hash): 4.6.dev-0.20210531.b0c22f2e39 with build-id 6a2a6e52891ef3f81d9a844a9b84d45da27c6cbe
Cluster size: 3
OS (RHEL/CentOS/Ubuntu/AWS AMI): ami-03dd826dbbaa5a403

test name is `performance_regression_test.PerformanceRegressionTest.test_latency_read`

we ran the test with this same version 3 times, and we had the following results:
```
4.9 ms
3.1 ms
3.2 ms
```

so the 2 with ~3 ms we will call "good runs" and the one with 4.9 ms we will call it "bad run"

one of the good runs monitor show us c-s latency being around 2.5 ms, with few (and small peaks), resulting in ~3 ms:
![Screenshot from 2021-06-17 14-55-26](https://user-images.githubusercontent.com/32832995/122392015-2d6dd880-cf7c-11eb-96d9-35ee4446c6e2.png)

but the bad run is around 4ms but it has peaks that are reaching 60 and even 87 ms peaks:
![Screenshot from 2021-06-17 14-57-33](https://user-images.githubusercontent.com/32832995/122392305-6e65ed00-cf7c-11eb-84fe-5fd5f978db8c.png)

during this huge peak, there were clusters of reactor stalls, and they might be the cause of this peak, but there are for sure extra issues with this specific run, making the overall c-s p99th latency be higher than a good run's highest peak...

here is a log @bhalevy decoded with his own words in an email thread:
```
All stall here are bound at 8 ms
and most of them come from synchronous reads
(see attached for fuller report)


min=5 avg=5.5 median=5 p95=7 p99=8 p999=None max=8

This graph is printed in bottom-up order, where callees are printed first.
Use --direction=top-down to print callers first.

[level#index/out_of pct%] below denotes:
  level  - nesting level in the graph
  index  - index of node among to its siblings
  out_of - number of siblings
  pct    - percentage of total stall time of this call relative to its siblings

Command line options used: Namespace(address_threshold='0x100000000', executable='scylla', full_function_names=False, width=132, direction='bottom-up', minimum=0, branch_threshold=0.05,
file='read_bad_latency_20210531.log')

++[0#1/85 38%] addr=0x4123aea total=309 count=56 avg=6:
|              seastar::file_desc::read at ./build/release/seastar/./seastar/include/seastar/core/posix.hh:221
++           - addr=0x4101f14:
|              operator() at ./build/release/seastar/./seastar/src/core/reactor.cc:264
| ++[1#1/2 95%] addr=0x4102043 total=298 count=54 avg=6:
| |             std::__invoke_impl<seastar::fu... at /usr/lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/bits/invoke.h:60
| |             (inlined by) std::__invoke<sea... at /usr/lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/bits/invoke.h:95
| |             (inlined by) std::invoke<seastar:... at /usr/lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/functional:88
| |             (inlined by) seastar::internal::future_i... at ./build/release/seastar/./seastar/include/seastar/core/future.hh:1209
| |             (inlined by) operator() at ./build/release/seastar/./seastar/include/seastar/core/future.hh:1582
| |             (inlined by) seastar::futurize<seastar::... at ./build/release/seastar/./seastar/include/seastar/core/future.hh:2120
| |             (inlined by) operator() at ./build/release/seastar/./seastar/include/seastar/core/future.hh:1575
| |             (inlined by) seastar::continuation<seasta... at ./build/release/seastar/./seastar/include/seastar/core/future.hh:767
| | ++[2#1/1 100%] addr=0x40eb21f total=315 count=57 avg=6:
| | |              seastar::reactor::run_tasks at ./build/release/seastar/./seastar/src/core/reactor.cc:2228
| | |              (inlined by) seastar::reactor::run_some_tasks at ./build/release/seastar/./seastar/src/core/reactor.cc:2637
| |   ++[3#1/1 100%] addr=0x40ec4a7 total=731 count=134 avg=5:
| |   |              seastar::reactor::run at ./build/release/seastar/./seastar/src/core/reactor.cc:2796
| |     ++[4#1/2 93%] addr=0x410a2db total=699 count=128 avg=5:
| |     |             operator() at ./build/release/seastar/./seastar/src/core/reactor.cc:3992
| |     |             (inlined by) std::__invo... at /usr/lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/bits/invoke.h:60
| |     |             (inlined by) std::__inv... at /usr/lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/bits/invoke.h:110
| |     |             (inlined by) std:... at /usr/lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/bits/std_function.h:291
| |     ++          - addr=0x40b69ea:
| |     |             std::function<voi... at /usr/lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/bits/std_function.h:622
| |     |             (inlined by) seastar::posix_thread::start_routine at ./build/release/seastar/./seastar/src/core/posix.cc:60
| |     ++          - addr=0x93f8: ?? ??:0
| |     ++          - addr=0x101902: ?? ??:0
| |     ++[4#2/2 7%] addr=0x408aa45 total=49 count=9 avg=5:
| |     |            seastar::app_template::run_deprecated at ./build/release/seastar/./seastar/src/core/app-template.cc:207
| |     ++         - addr=0x4089e66:
| |     |            seastar::app_template::run at ./build/release/seastar/./seastar/src/core/app-template.cc:115
| |     ++         - addr=0xed3ba1:
| |     |            main at ./main.cc:500
| |     ++         - addr=0x281e1: ?? ??:0
| |     ++         - addr=0xed090d:
| |     |            _start at ??:?
| ++[1#2/2 5%] addr=0x40cf51c total=16 count=3 avg=5:
| |            seastar::futurize<seastar::future<seastar... at ./build/release/seastar/./seastar/include/seastar/core/future.hh:2135
| |            (inlined by) seastar::futurize<seastar::f... at ./build/release/seastar/./seastar/include/seastar/core/future.hh:1979
| |            (inlined by) seastar::future<void>::then_... at ./build/release/seastar/./seastar/include/seastar/core/future.hh:1601
| |            (inlined by) seastar::internal::call_then... at ./build/release/seastar/./seastar/include/seastar/core/future.hh:1234
| |            (inlined by) seastar::future<void>::then<... at ./build/release/seastar/./seastar/include/seastar/core/future.hh:1520
| |            (inlined by) seastar::reactor::do_read_some at ./build/release/seastar/./seastar/src/core/reactor.cc:262
| ++         - addr=0x412fcc3:
| |            seastar::reactor_backend_aio::read_some at ./build/release/seastar/./seastar/src/core/reactor_backend.cc:565
|   ++[2#1/1 100%] addr=0x40cffac total=26 count=5 avg=5:
|   |              seastar::pollable_fd_state::read_some at ./build/release/seastar/./seastar/src/core/reactor.cc:367
|   ++           - addr=0x4408ebe:
|   |              seastar::pollable_fd::re... at ./build/release/seastar/./seastar/include/seastar/core/internal/pollable_fd.hh:125
|   |              (inlined by) seastar::net::posix_data_source_i... at ./build/release/seastar/./seastar/src/net/posix-stack.cc:575
|     ++[3#1/2 62%] addr=0x25d7767 total=16 count=3 avg=5:
|     |             seastar::data_source::get at ././seastar/include/seastar/core/iostream.hh:69
|     |             (inlined by) seastar::input_stream<char>::read_up_to at ././seastar/include/seastar/core/iostream-impl.hh:257
|     | ++[4#1/2 69%] addr=0x44830f6 total=11 count=2 avg=6:
|     | |             seastar::rpc::read_rcv_buf at ./build/release/seastar/./seastar/src/rpc/rpc.cc:308
|     | |             (inlined by) operator() at ./build/release/seastar/./seastar/src/rpc/rpc.cc:356
|     | ++          - addr=0x4482fef:
|     | |             seastar::futurize<seastar::future<... at ./build/release/seastar/./seastar/include/seastar/core/future.hh:2135
|     | | ++[5#1/1 100%] addr=0x4482eb1 total=56 count=11 avg=5:
|     | | |              seastar::future<seastar::tempor... at ./build/release/seastar/./seastar/include/seastar/core/future.hh:1601
|     | | ++           - addr=0x445e291:
|     | | |              seastar::internal::call_then_im... at ./build/release/seastar/./seastar/include/seastar/core/future.hh:1234
|     | | |              (inlined by) seastar::future<se... at ./build/release/seastar/./seastar/include/seastar/core/future.hh:1520
|     | | |              (inlined by) seastar::rpc::connection::read_fram... at ./build/release/seastar/./seastar/src/rpc/rpc.cc:344
|     | | |              (inlined by) seastar::rpc::connection::read_fram... at ./build/release/seastar/./seastar/src/rpc/rpc.cc:404
|     | | |              (inlined by) seastar::rpc::server::connection::r... at ./build/release/seastar/./seastar/src/rpc/rpc.cc:875
|     | | ++           - addr=0x44698a3:
|     | | |              operator() at ./build/release/seastar/./seastar/src/rpc/rpc.cc:920
|     | |   ++[6#1/1 100%] addr=0x446ab44 total=66 count=13 avg=5:
|     | |   |              seastar::internal::do_until_stat... at ./build/release/seastar/./seastar/include/seastar/core/loop.hh:295
|     | |     ++[7#1/1 100%] addr=0x40eb21f total=112 count=22 avg=5:
|     | |     |              seastar::reactor::run_tasks at ./build/release/seastar/./seastar/src/core/reactor.cc:2228
|     | |     |              (inlined by) seastar::reactor::run_som... at ./build/release/seastar/./seastar/src/core/reactor.cc:2637
|     | |     -> continued at addr=0x40eb21f above
|     | ++[4#2/2 31%] addr=0x44736c0 total=5 count=1 avg=5:
|     | |             operator() at ./build/release/seastar/./seastar/src/rpc/rpc.cc:322
|     | |             (inlined by) seastar::futurize<sea... at ./build/release/seastar/./seastar/include/seastar/core/future.hh:2135
|     | |             (inlined by) seastar::repeat<seastar:... at ./build/release/seastar/./seastar/include/seastar/core/loop.hh:118
|     | ++          - addr=0x44730af:
|     | |             operator() at ./build/release/seastar/./seastar/src/rpc/rpc.cc:321
|     | |             (inlined by) std::__invo... at /usr/lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/bits/invoke.h:60
|     | |             (inlined by) std::__invo... at /usr/lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/bits/invoke.h:95
|     | |             (inlined by) std::__apply_impl... at /usr/lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/tuple:1723
|     | |             (inlined by) std::apply<seasta... at /usr/lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/tuple:1734
|     | |             (inlined by) seastar::internal::do_... at ./build/release/seastar/./seastar/include/seastar/core/do_with.hh:96
|     | ++          - addr=0x4472e08:
|     | |             seastar::futurize<seastar::future<... at ./build/release/seastar/./seastar/include/seastar/core/future.hh:2135
|     | |             (inlined by) seastar::futurize_inv... at ./build/release/seastar/./seastar/include/seastar/core/future.hh:2166
|     | |             (inlined by) seastar::do_with<seas... at ./build/release/seastar/./seastar/include/seastar/core/do_with.hh:131
|     | |             (inlined by) operator() at ./build/release/seastar/./seastar/src/rpc/rpc.cc:320
|     | ++          - addr=0x4472c5f:
|     | |             seastar::futurize<seastar::future<... at ./build/release/seastar/./seastar/include/seastar/core/future.hh:2135
|     |   ++[5#1/1 100%] addr=0x4472b21 total=20 count=4 avg=5:
|     |   |              seastar::future<seastar::tempor... at ./build/release/seastar/./seastar/include/seastar/core/future.hh:1601
|     |   ++           - addr=0x448311b:
|     |   |              seastar::internal::call_then_im... at ./build/release/seastar/./seastar/include/seastar/core/future.hh:1234
|     |   |              (inlined by) seastar::future<se... at ./build/release/seastar/./seastar/include/seastar/core/future.hh:1520
|     |   |              (inlined by) seastar::rpc::read_rcv_buf at ./build/release/seastar/./seastar/src/rpc/rpc.cc:308
|     |   |              (inlined by) operator() at ./build/release/seastar/./seastar/src/rpc/rpc.cc:356
|     |     ++[6#1/1 100%] addr=0x4482fef total=30 count=6 avg=5:
|     |     |              seastar::futurize<seastar::fu... at ./build/release/seastar/./seastar/include/seastar/core/future.hh:2135
|     |     -> continued at addr=0x4482fef above
|     ++[3#2/2 38%] addr=0x16615a4 total=10 count=2 avg=5:
|     |             seastar::data_source::get at ././seastar/include/seastar/core/iostream.hh:69
|     |             (inlined by) seastar::input_stream<char>::read_exactly at ././seastar/include/seastar/core/iostream-impl.hh:186
|     ++          - addr=0x445e254:
|     |             seastar::rpc::connection::read_frame<seastar::rpc::re... at ./build/release/seastar/./seastar/src/rpc/rpc.cc:344
|     |             (inlined by) seastar::rpc::connection::read_frame_com... at ./build/release/seastar/./seastar/src/rpc/rpc.cc:404
|     |             (inlined by) seastar::rpc::server::connection::read_r... at ./build/release/seastar/./seastar/src/rpc/rpc.cc:875
|     ++          - addr=0x44698a3:
|     |             operator() at ./build/release/seastar/./seastar/src/rpc/rpc.cc:920
|     -> continued at addr=0x44698a3 above
++[0#2/85 62%] 84 more branches total=502 count=91 avg=0
```

full report attached:
[read_bad_latency_20210531.stall-analyser.txt](https://github.com/scylladb/scylla/files/6669955/read_bad_latency_20210531.stall-analyser.txt)

it is very important to mention that, it is being challenging to check the regressions with the tests, because of lack of stability in many runs

test_id of the bad run is `4fa003df-1af6-4c22-b32c-4d0b327a8727`
test_id of the 2 good runs are `2b44fd3d-407f-40f1-8e12-84487924098d` and `e7f6da99-d769-4928-8195-d506ef1c3443`

**Comment by avikivity** [comment] 2021-06-17 17:10
Duplicate of #7882 . Unfortunately no solution in sight.

**Closed** 2021-06-17 17:10 UTC
Labels: latency
