### ISSUE TITLE
Malformed compaction part schema.cql is generated by nodetool snapshot

### ISSUE THREAD

**Issue by dkropachev** [scylladb/scylla#7980] opened 2021-01-28 11:37 UTC
Scylla generate malformed compaction part of schema.cql:
```
CREATE  TABLE ks.cf (
    key int,
    val text,
    PRIMARY KEY (key)
) WITH bloom_filter_fp_chance = 0.01
    AND caching = {'keys': 'ALL','rows_per_partition': 'ALL'}
    AND comment = 'test cf'
    AND compaction = {'class': 'SizeTieredCompactionStrategy''enabled': 'true'}
    AND compression = {}
    AND crc_check_chance = 1
    AND dclocal_read_repair_chance = 0
    AND default_time_to_live = 0
    AND gc_grace_seconds = 864000
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair_chance = 0
    AND speculative_retry = '99.0PERCENTILE';
```

*Installation details*
Scylla version (or git commit hash): 4.2.3, 4.3.0, issue is fixed on master

*Hardware details (for performance issues)*
Platform: docker

*Steps to reproduce*
```
[root@8829e9803a61 /]# cqlsh -e "CREATE KEYSPACE ks WITH replication={'class':'SimpleStrategy', 'replication_factor':1}; USE ks; CREATE COLUMNFAMILY cf (key int PRIMARY KEY, val text) WITH comment='test cf' AND compaction = {'class': 'SizeTieredCompactionStrategy', 'enabled': 'true'} AND compression = {};"
[root@8829e9803a61 /]# nodetool snapshot ks
Requested creating snapshot(s) for [ks] with snapshot name [1611832964337] and options {skipFlush=false}
Snapshot directory: 1611832964337
[root@8829e9803a61 /]# cat /var/lib/scylla/data/ks/cf-*/snapshots/*/schema.cql 
CREATE  TABLE ks.cf (
    key int,
    val text,
    PRIMARY KEY (key)
) WITH bloom_filter_fp_chance = 0.01
    AND caching = {'keys': 'ALL','rows_per_partition': 'ALL'}
    AND comment = 'test cf'
    AND compaction = {'class': 'SizeTieredCompactionStrategy''enabled': 'true'}
    AND compression = {}
    AND crc_check_chance = 1
    AND dclocal_read_repair_chance = 0
    AND default_time_to_live = 0
    AND gc_grace_seconds = 864000
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair_chance = 0
    AND speculative_retry = '99.0PERCENTILE';
```

**Comment by slivne** [comment] 2021-02-28 19:47
duplicate of #7741

**Closed by slivne** 2021-02-28 19:47 UTC
