### ISSUE TITLE
OverflowError: date value out of range

### ISSUE THREAD

**Issue by infordb** [scylladb/scylla#1694] opened 2016-09-23 04:27 UTC
_Installation details_
Scylla version (or git commit hash): 1.2.3-20160731
Cluster size: 3
OS (RHEL/CentOS/Ubuntu/AWS AMI): AWS Linux version 3.10.0-327.10.1.el7.x86_64 

We got an error when we run "select \* from raw_data limit 1;"
After truncating raw_data table We also got an error..
But another tables are no problem.

cqlsh:spatch> select \* from raw_data limit 1;
Traceback (most recent call last):
  File "/bin/cqlsh", line 1078, in perform_simple_statement
    rows = self.session.execute(statement, trace=self.tracing_enabled)
  File "/usr/share/scylla/cassandra/lib/cassandra-driver-internal-only-2.6.0c2.post.zip/cassandra-driver-2.6.0c2.post/cassandra/cluster.py", line 1594, in execute
    result = future.result(timeout)
  File "/usr/share/scylla/cassandra/lib/cassandra-driver-internal-only-2.6.0c2.post.zip/cassandra-driver-2.6.0c2.post/cassandra/cluster.py", line 3296, in result
    raise self._final_exception
OverflowError: date value out of range

**Comment by penberg** [comment] 2016-09-23 06:32
@infordb Can you describe what your `raw_data` table looks like?

**Comment by infordb** [comment] 2016-09-23 06:53
cqlsh:spatch> desc raw_data;

CREATE TABLE spatch.raw_data (
    test_id int,
    partition_key text,
    time timestamp,
    value double,
    PRIMARY KEY ((test_id, partition_key), time)
) WITH CLUSTERING ORDER BY (time ASC)
    AND bloom_filter_fp_chance = 0.01
    AND caching = '{"keys":"ALL","rows_per_partition":"ALL"}'
    AND comment = ''
    AND compaction = {'class': 'SizeTieredCompactionStrategy'}
    AND compression = {'sstable_compression': 'org.apache.cassandra.io.compress.                LZ4Compressor'}
    AND dclocal_read_repair_chance = 0.1
    AND default_time_to_live = 0
    AND gc_grace_seconds = 864000
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair_chance = 0.0
    AND speculative_retry = '99.0PERCENTILE';

**Comment by penberg** [comment] 2016-09-23 07:02
Looks like a `cqlsh` issue that's already fixed in Cassandra:

https://issues.apache.org/jira/browse/CASSANDRA-11274

https://github.com/apache/cassandra/commit/1de4a983b2b5dbc8a87d04e25124ad03f6133a1c

**Comment by penberg** [comment] 2016-09-23 07:05
Although we recommend people to use `cqlsh` from our packages, you might be able to use `cqlsh` from Cassandra 3.7 until we fix the problem in `scylla-tools`. Remember you pass ``--cqlversion=3.2.1`` as a command line argument to `cqlsh`, though.

**Comment by infordb** [comment] 2016-09-23 07:31
Is it no problem to use cassandra cqlsh at version 3.2.1
And how do i fix this in Java Client Case ?
We use  datastax java driver 2.1.7.1

**Comment by penberg** [comment] 2016-09-23 08:24
@infordb AFAICT, the problem is limited to `cqlsh` and the Java driver will work fine. Did you test it?

**Comment by infordb** [comment] 2016-09-26 03:06
@penberg I will share the results after testing

**Comment by slivne** [comment] 2016-09-27 19:58
once we rebase the scylla-tools-java on the 3.X branch (in progress) we should have that resolved

**Comment by slivne** [comment] 2017-03-06 10:33
@roydahan can you please have someone create atest for this so we will have regression testing for this (and know this is resolved)

**Comment by roydahan** [comment] 2017-03-06 11:00
@larisau, let's add a test in dtest for this one.

**Comment by roydahan** [comment] 2017-04-03 10:22
reassigned to @abvgedeika

**Closed** 2017-04-12 11:11 UTC
Labels: bug, fixed, User Request
