### ISSUE TITLE
Scylla initialization never finishes when built on Fedora 32

### ISSUE THREAD

**Issue by syuu1228** [scylladb/scylla#6462] opened 2020-05-15 15:35 UTC
Even a binary built on Fedora 31 works finely, a binary built on Fedora 32 does not start database server, it seems stopping on somewhere in initialization stage. 

```
[syuu@monster scylla.3]$ sudo -u scylla ./build/release/scylla --log-to-stdout 1 --default-log-level debug --network-stack posix $SEASTER_IO
Scylla version 666.development-0.20200515.b2c4d9fdb with build-id 79c4d389e3de97f1cf1c979468e99682147e8668 starting ...
command used: "./build/release/scylla --log-to-stdout 1 --default-log-level debug --network-stack posix"
parsed command line options: [log-to-stdout: 1, default-log-level: debug, network-stack: posix]
DEBUG 2020-05-16 00:23:00,484 seastar - Not a cgroups-v2-only system
DEBUG 2020-05-16 00:23:00,484 seastar - smp::count: 20
DEBUG 2020-05-16 00:23:00,484 seastar - latency_goal: 0.00075
DEBUG 2020-05-16 00:23:00,484 seastar - num_io_queues: 20
DEBUG 2020-05-16 00:23:00,488 seastar - Not a cgroups-v2-only system
DEBUG 2020-05-16 00:23:00,545 [shard 3] seastar - generate_config dev_id: 0
DEBUG 2020-05-16 00:23:00,545 [shard 0] seastar - generate_config dev_id: 0
DEBUG 2020-05-16 00:23:00,546 [shard 1] seastar - generate_config dev_id: 0
DEBUG 2020-05-16 00:23:00,546 [shard 2] seastar - generate_config dev_id: 0
DEBUG 2020-05-16 00:23:00,548 [shard 4] seastar - generate_config dev_id: 0
DEBUG 2020-05-16 00:23:00,548 [shard 11] seastar - generate_config dev_id: 0
DEBUG 2020-05-16 00:23:00,548 [shard 9] seastar - generate_config dev_id: 0
DEBUG 2020-05-16 00:23:00,549 [shard 5] seastar - generate_config dev_id: 0
DEBUG 2020-05-16 00:23:00,551 [shard 7] seastar - generate_config dev_id: 0
DEBUG 2020-05-16 00:23:00,551 [shard 6] seastar - generate_config dev_id: 0
DEBUG 2020-05-16 00:23:00,553 [shard 12] seastar - generate_config dev_id: 0
DEBUG 2020-05-16 00:23:00,554 [shard 8] seastar - generate_config dev_id: 0
DEBUG 2020-05-16 00:23:00,556 [shard 10] seastar - generate_config dev_id: 0
DEBUG 2020-05-16 00:23:00,557 [shard 13] seastar - generate_config dev_id: 0
DEBUG 2020-05-16 00:23:00,568 [shard 15] seastar - generate_config dev_id: 0
DEBUG 2020-05-16 00:23:00,568 [shard 14] seastar - generate_config dev_id: 0
DEBUG 2020-05-16 00:23:00,568 [shard 16] seastar - generate_config dev_id: 0
DEBUG 2020-05-16 00:23:00,568 [shard 17] seastar - generate_config dev_id: 0
DEBUG 2020-05-16 00:23:00,568 [shard 18] seastar - generate_config dev_id: 0
DEBUG 2020-05-16 00:23:00,568 [shard 19] seastar - generate_config dev_id: 0
INFO  2020-05-16 00:23:00,578 [shard 0] init - installing SIGHUP handler
DEBUG 2020-05-16 00:23:00,580 [shard 0] lsa - Compacting, requested 18446744070618873856 bytes, 0 bytes in use, target is 0
DEBUG 2020-05-16 00:23:00,580 [shard 0] lsa - Occupancy of regions:
DEBUG 2020-05-16 00:23:00,580 [shard 0] lsa - Released 0 bytes (wanted 18446744070618873856), 0 during compaction
DEBUG 2020-05-16 00:23:00,580 [shard 0] lsa-timing - Reclamation cycle took 24.239 us.
DEBUG 2020-05-16 00:23:00,580 [shard 0] lsa - Trying to reclaim 664 segments
DEBUG 2020-05-16 00:23:00,580 [shard 0] lsa - Reclaimed 664 segments (requested 664)
DEBUG 2020-05-16 00:23:00,583 [shard 1] lsa - Compacting, requested 18446744070615334912 bytes, 0 bytes in use, target is 0
DEBUG 2020-05-16 00:23:00,583 [shard 1] lsa - Occupancy of regions:
DEBUG 2020-05-16 00:23:00,584 [shard 1] lsa - Released 0 bytes (wanted 18446744070615334912), 0 during compaction
DEBUG 2020-05-16 00:23:00,584 [shard 1] lsa-timing - Reclamation cycle took 87.522 us.
DEBUG 2020-05-16 00:23:00,584 [shard 1] lsa - Trying to reclaim 664 segments
DEBUG 2020-05-16 00:23:00,584 [shard 1] lsa - Reclaimed 664 segments (requested 664)
DEBUG 2020-05-16 00:23:00,584 [shard 9] lsa - Compacting, requested 18446744070615334912 bytes, 0 bytes in use, target is 0
DEBUG 2020-05-16 00:23:00,584 [shard 18] lsa - Compacting, requested 18446744070615334912 bytes, 0 bytes in use, target is 0
DEBUG 2020-05-16 00:23:00,584 [shard 5] lsa - Compacting, requested 18446744070615334912 bytes, 0 bytes in use, target is 0
DEBUG 2020-05-16 00:23:00,584 [shard 10] lsa - Compacting, requested 18446744070615334912 bytes, 0 bytes in use, target is 0
DEBUG 2020-05-16 00:23:00,584 [shard 2] lsa - Compacting, requested 18446744070615334912 bytes, 0 bytes in use, target is 0
DEBUG 2020-05-16 00:23:00,584 [shard 11] lsa - Compacting, requested 18446744070615334912 bytes, 0 bytes in use, target is 0
DEBUG 2020-05-16 00:23:00,584 [shard 14] lsa - Compacting, requested 18446744070615334912 bytes, 0 bytes in use, target is 0
DEBUG 2020-05-16 00:23:00,584 [shard 7] lsa - Compacting, requested 18446744070615334912 bytes, 0 bytes in use, target is 0
DEBUG 2020-05-16 00:23:00,584 [shard 13] lsa - Compacting, requested 18446744070615334912 bytes, 0 bytes in use, target is 0
DEBUG 2020-05-16 00:23:00,584 [shard 18] lsa - Occupancy of regions:
DEBUG 2020-05-16 00:23:00,584 [shard 19] lsa - Compacting, requested 18446744070615334912 bytes, 0 bytes in use, target is 0
DEBUG 2020-05-16 00:23:00,584 [shard 18] lsa - Released 0 bytes (wanted 18446744070615334912), 0 during compaction
DEBUG 2020-05-16 00:23:00,584 [shard 3] lsa - Compacting, requested 18446744070615334912 bytes, 0 bytes in use, target is 0
DEBUG 2020-05-16 00:23:00,584 [shard 10] lsa - Occupancy of regions:
DEBUG 2020-05-16 00:23:00,584 [shard 16] lsa - Compacting, requested 18446744070615334912 bytes, 0 bytes in use, target is 0
DEBUG 2020-05-16 00:23:00,584 [shard 9] lsa - Occupancy of regions:
DEBUG 2020-05-16 00:23:00,584 [shard 2] lsa - Occupancy of regions:
DEBUG 2020-05-16 00:23:00,584 [shard 9] lsa - Released 0 bytes (wanted 18446744070615334912), 0 during compaction
DEBUG 2020-05-16 00:23:00,584 [shard 11] lsa - Occupancy of regions:
DEBUG 2020-05-16 00:23:00,584 [shard 12] lsa - Compacting, requested 18446744070615334912 bytes, 0 bytes in use, target is 0
DEBUG 2020-05-16 00:23:00,584 [shard 6] lsa - Compacting, requested 18446744070615334912 bytes, 0 bytes in use, target is 0
DEBUG 2020-05-16 00:23:00,584 [shard 7] lsa - Occupancy of regions:
DEBUG 2020-05-16 00:23:00,584 [shard 6] lsa - Occupancy of regions:
DEBUG 2020-05-16 00:23:00,584 [shard 13] lsa - Occupancy of regions:
DEBUG 2020-05-16 00:23:00,584 [shard 5] lsa - Occupancy of regions:
DEBUG 2020-05-16 00:23:00,584 [shard 5] lsa - Released 0 bytes (wanted 18446744070615334912), 0 during compaction
DEBUG 2020-05-16 00:23:00,584 [shard 18] lsa-timing - Reclamation cycle took 244.753 us.
DEBUG 2020-05-16 00:23:00,584 [shard 3] lsa - Occupancy of regions:
DEBUG 2020-05-16 00:23:00,584 [shard 4] lsa - Compacting, requested 18446744070615334912 bytes, 0 bytes in use, target is 0
DEBUG 2020-05-16 00:23:00,584 [shard 4] lsa - Occupancy of regions:
DEBUG 2020-05-16 00:23:00,584 [shard 2] lsa - Released 0 bytes (wanted 18446744070615334912), 0 during compaction
DEBUG 2020-05-16 00:23:00,584 [shard 2] lsa-timing - Reclamation cycle took 240.592 us.
DEBUG 2020-05-16 00:23:00,584 [shard 14] lsa - Occupancy of regions:
DEBUG 2020-05-16 00:23:00,584 [shard 14] lsa - Released 0 bytes (wanted 18446744070615334912), 0 during compaction
DEBUG 2020-05-16 00:23:00,584 [shard 7] lsa - Released 0 bytes (wanted 18446744070615334912), 0 during compaction
DEBUG 2020-05-16 00:23:00,584 [shard 8] lsa - Compacting, requested 18446744070615334912 bytes, 0 bytes in use, target is 0
DEBUG 2020-05-16 00:23:00,584 [shard 17] lsa - Compacting, requested 18446744070615334912 bytes, 0 bytes in use, target is 0
DEBUG 2020-05-16 00:23:00,584 [shard 17] lsa - Occupancy of regions:
DEBUG 2020-05-16 00:23:00,584 [shard 17] lsa - Released 0 bytes (wanted 18446744070615334912), 0 during compaction
DEBUG 2020-05-16 00:23:00,584 [shard 3] lsa - Released 0 bytes (wanted 18446744070615334912), 0 during compaction
DEBUG 2020-05-16 00:23:00,584 [shard 17] lsa-timing - Reclamation cycle took 161.681 us.
DEBUG 2020-05-16 00:23:00,584 [shard 16] lsa - Occupancy of regions:
DEBUG 2020-05-16 00:23:00,584 [shard 10] lsa - Released 0 bytes (wanted 18446744070615334912), 0 during compaction
DEBUG 2020-05-16 00:23:00,584 [shard 12] lsa - Occupancy of regions:
DEBUG 2020-05-16 00:23:00,584 [shard 6] lsa - Released 0 bytes (wanted 18446744070615334912), 0 during compaction
DEBUG 2020-05-16 00:23:00,584 [shard 19] lsa - Occupancy of regions:
DEBUG 2020-05-16 00:23:00,584 [shard 6] lsa-timing - Reclamation cycle took 236.091 us.
DEBUG 2020-05-16 00:23:00,584 [shard 5] lsa-timing - Reclamation cycle took 197.283 us.
DEBUG 2020-05-16 00:23:00,584 [shard 8] lsa - Occupancy of regions:
DEBUG 2020-05-16 00:23:00,584 [shard 8] lsa - Released 0 bytes (wanted 18446744070615334912), 0 during compaction
DEBUG 2020-05-16 00:23:00,584 [shard 5] lsa - Trying to reclaim 664 segments
DEBUG 2020-05-16 00:23:00,584 [shard 8] lsa-timing - Reclamation cycle took 381.749 us.
DEBUG 2020-05-16 00:23:00,584 [shard 4] lsa - Released 0 bytes (wanted 18446744070615334912), 0 during compaction
DEBUG 2020-05-16 00:23:00,584 [shard 17] lsa - Trying to reclaim 664 segments
DEBUG 2020-05-16 00:23:00,584 [shard 9] lsa-timing - Reclamation cycle took 365.69 us.
DEBUG 2020-05-16 00:23:00,584 [shard 11] lsa - Released 0 bytes (wanted 18446744070615334912), 0 during compaction
DEBUG 2020-05-16 00:23:00,584 [shard 10] lsa-timing - Reclamation cycle took 286.032 us.
DEBUG 2020-05-16 00:23:00,584 [shard 11] lsa-timing - Reclamation cycle took 329.589 us.
DEBUG 2020-05-16 00:23:00,584 [shard 13] lsa - Released 0 bytes (wanted 18446744070615334912), 0 during compaction
DEBUG 2020-05-16 00:23:00,584 [shard 14] lsa-timing - Reclamation cycle took 314.144 us.
DEBUG 2020-05-16 00:23:00,584 [shard 13] lsa-timing - Reclamation cycle took 385.217 us.
DEBUG 2020-05-16 00:23:00,584 [shard 11] lsa - Trying to reclaim 664 segments
DEBUG 2020-05-16 00:23:00,584 [shard 6] lsa - Trying to reclaim 664 segments
DEBUG 2020-05-16 00:23:00,584 [shard 14] lsa - Trying to reclaim 664 segments
DEBUG 2020-05-16 00:23:00,584 [shard 3] lsa-timing - Reclamation cycle took 238.548 us.
DEBUG 2020-05-16 00:23:00,584 [shard 4] lsa-timing - Reclamation cycle took 400.998 us.
DEBUG 2020-05-16 00:23:00,584 [shard 3] lsa - Trying to reclaim 664 segments
DEBUG 2020-05-16 00:23:00,584 [shard 9] lsa - Trying to reclaim 664 segments
DEBUG 2020-05-16 00:23:00,584 [shard 19] lsa - Released 0 bytes (wanted 18446744070615334912), 0 during compaction
DEBUG 2020-05-16 00:23:00,584 [shard 10] lsa - Trying to reclaim 664 segments
DEBUG 2020-05-16 00:23:00,584 [shard 19] lsa-timing - Reclamation cycle took 498.834 us.
DEBUG 2020-05-16 00:23:00,584 [shard 7] lsa-timing - Reclamation cycle took 267.421 us.
DEBUG 2020-05-16 00:23:00,584 [shard 16] lsa - Released 0 bytes (wanted 18446744070615334912), 0 during compaction
DEBUG 2020-05-16 00:23:00,584 [shard 8] lsa - Trying to reclaim 664 segments
DEBUG 2020-05-16 00:23:00,584 [shard 16] lsa-timing - Reclamation cycle took 381.719 us.
DEBUG 2020-05-16 00:23:00,584 [shard 2] lsa - Trying to reclaim 664 segments
DEBUG 2020-05-16 00:23:00,585 [shard 17] lsa - Reclaimed 664 segments (requested 664)
DEBUG 2020-05-16 00:23:00,585 [shard 16] lsa - Trying to reclaim 664 segments
DEBUG 2020-05-16 00:23:00,585 [shard 3] lsa - Reclaimed 664 segments (requested 664)
DEBUG 2020-05-16 00:23:00,584 [shard 18] lsa - Trying to reclaim 664 segments
DEBUG 2020-05-16 00:23:00,584 [shard 14] lsa - Reclaimed 664 segments (requested 664)
DEBUG 2020-05-16 00:23:00,584 [shard 19] lsa - Trying to reclaim 664 segments
DEBUG 2020-05-16 00:23:00,584 [shard 13] lsa - Trying to reclaim 664 segments
DEBUG 2020-05-16 00:23:00,584 [shard 7] lsa - Trying to reclaim 664 segments
DEBUG 2020-05-16 00:23:00,584 [shard 5] lsa - Reclaimed 664 segments (requested 664)
DEBUG 2020-05-16 00:23:00,584 [shard 12] lsa - Released 0 bytes (wanted 18446744070615334912), 0 during compaction
DEBUG 2020-05-16 00:23:00,584 [shard 15] lsa - Compacting, requested 18446744070615334912 bytes, 0 bytes in use, target is 0
DEBUG 2020-05-16 00:23:00,585 [shard 15] lsa - Occupancy of regions:
DEBUG 2020-05-16 00:23:00,585 [shard 2] lsa - Reclaimed 664 segments (requested 664)
DEBUG 2020-05-16 00:23:00,585 [shard 9] lsa - Reclaimed 664 segments (requested 664)
DEBUG 2020-05-16 00:23:00,585 [shard 12] lsa-timing - Reclamation cycle took 523.109 us.
DEBUG 2020-05-16 00:23:00,584 [shard 11] lsa - Reclaimed 664 segments (requested 664)
DEBUG 2020-05-16 00:23:00,585 [shard 10] lsa - Reclaimed 664 segments (requested 664)
DEBUG 2020-05-16 00:23:00,585 [shard 13] lsa - Reclaimed 664 segments (requested 664)
DEBUG 2020-05-16 00:23:00,585 [shard 8] lsa - Reclaimed 664 segments (requested 664)
DEBUG 2020-05-16 00:23:00,585 [shard 6] lsa - Reclaimed 664 segments (requested 664)
DEBUG 2020-05-16 00:23:00,585 [shard 18] lsa - Reclaimed 664 segments (requested 664)
DEBUG 2020-05-16 00:23:00,585 [shard 19] lsa - Reclaimed 664 segments (requested 664)
DEBUG 2020-05-16 00:23:00,585 [shard 4] lsa - Trying to reclaim 664 segments
DEBUG 2020-05-16 00:23:00,585 [shard 7] lsa - Reclaimed 664 segments (requested 664)
DEBUG 2020-05-16 00:23:00,585 [shard 16] lsa - Reclaimed 664 segments (requested 664)
DEBUG 2020-05-16 00:23:00,585 [shard 4] lsa - Reclaimed 664 segments (requested 664)
DEBUG 2020-05-16 00:23:00,585 [shard 12] lsa - Trying to reclaim 664 segments
DEBUG 2020-05-16 00:23:00,585 [shard 15] lsa - Released 0 bytes (wanted 18446744070615334912), 0 during compaction
DEBUG 2020-05-16 00:23:00,585 [shard 15] lsa-timing - Reclamation cycle took 795.243 us.
DEBUG 2020-05-16 00:23:00,585 [shard 15] lsa - Trying to reclaim 664 segments
DEBUG 2020-05-16 00:23:00,585 [shard 12] lsa - Reclaimed 664 segments (requested 664)
DEBUG 2020-05-16 00:23:00,585 [shard 15] lsa - Reclaimed 664 segments (requested 664)
INFO  2020-05-16 00:23:00,585 [shard 0] init - Scylla version 666.development-0.20200515.b2c4d9fdb with build-id 79c4d389e3de97f1cf1c979468e99682147e8668 starting ...

DEBUG 2020-05-16 00:23:00,585 [shard 0] dns_resolver - Query name 0.0.0.0 (INET)
DEBUG 2020-05-16 00:23:00,585 [shard 0] dns_resolver - Query success: 0.0.0.0/0.0.0.0
INFO  2020-05-16 00:23:00,585 [shard 0] init - starting prometheus API server
DEBUG 2020-05-16 00:23:00,586 [shard 0] dns_resolver - Query name localhost (INET)
DEBUG 2020-05-16 00:23:00,586 [shard 0] dns_resolver - Query success: localhost/127.0.0.1
DEBUG 2020-05-16 00:23:00,586 [shard 0] dns_resolver - Query name localhost (INET)
DEBUG 2020-05-16 00:23:00,586 [shard 0] dns_resolver - Query success: localhost/127.0.0.1
INFO  2020-05-16 00:23:00,586 [shard 0] init - starting tokens manager
INFO  2020-05-16 00:23:00,587 [shard 0] init - starting migration manager notifier
INFO  2020-05-16 00:23:00,587 [shard 0] init - creating tracing
INFO  2020-05-16 00:23:00,587 [shard 0] init - creating snitch
INFO  2020-05-16 00:23:00,588 [shard 0] init - determining DNS name
DEBUG 2020-05-16 00:23:00,588 [shard 0] dns_resolver - Query name 127.0.0.1 (INET)
DEBUG 2020-05-16 00:23:00,588 [shard 0] dns_resolver - Query success: 127.0.0.1/127.0.0.1
INFO  2020-05-16 00:23:00,588 [shard 0] init - starting API server
INFO  2020-05-16 00:23:00,588 [shard 0] init - Scylla API server listening on 127.0.0.1:10000 ...

(never shows up new log from here)
```

**Comment by avikivity** [comment] 2020-05-17 15:24
It works for me. Got port 9042 listening (on godzilla).

**Comment by avikivity** [comment] 2020-05-17 15:25
I used scylla-package to install (as nonroot).

**Comment by avikivity** [comment] 2020-05-17 15:26
Note you must use relocatable packages if crossing OS versions.

**Comment by slivne** [comment] 2020-05-20 06:16
@syuu1228 ping - can we close this as not a bug ?

**Comment by slivne** [comment] 2020-05-24 20:05
@syuu1228 ping

**Comment by slivne** [comment] 2020-05-26 14:47
@syuu1228 closing this - others have tried and succeeded, if there is still an issue please post with additional information

**Closed by slivne** 2020-05-26 14:47 UTC
Labels: showstopper
