### ISSUE TITLE
compaction failed: std::runtime_error (SSTables with Cassandra-style shadowable deletion cannot be read by Scylla)

### ISSUE THREAD

**Issue by luchenyuxx** [scylladb/scylla#4748] opened 2019-07-22 09:12 UTC
# Description

I’m having some weird errors on sstable compaction on one materialized view: `compaction failed: std::runtime_error (SSTables with Cassandra-style shadowable deletion cannot be read by Scylla)`, although I started from ScyllaDB, my data is all generated by ScyllaDB. And it happens only on one node.

# Facts

- Error only happens on one node. On other node, the same MV works fine.
- Scylla cluster is started clean. There is no Cassandra data import
- I tried a lot of way to fix it: `nodetool repair`, `nodetool rebuild` and `rm -f` the sstables on the disk then `nodetool repair`. The issue still exists.

# Installation details
Scylla version (or git commit hash):3 .0.3-0.20190211.c36c58c64
Cluster size: 10 TB
OS (RHEL/CentOS/Ubuntu/AWS AMI): CentOS

# Schema
```
CREATE TABLE btc.output_inputs (
    output_tx_id blob,
    output_index bigint,
    address text,
    input_block_height int,
    input_index bigint,
    input_tx_id blob,
    output_block_height int,
    req_sigs int,
    script_hex blob,
    script_sig blob,
    script_type text,
    sequence bigint,
    txinwitness frozen<list<blob>>,
    value varint,
    PRIMARY KEY ((output_tx_id, output_index))
) WITH bloom_filter_fp_chance = 0.01
    AND caching = {'keys': 'ALL', 'rows_per_partition': 'ALL'}
    AND comment = ''
    AND compaction = {'class': 'SizeTieredCompactionStrategy'}
    AND compression = {'sstable_compression': 'org.apache.cassandra.io.compress.LZ4Compressor'}
    AND crc_check_chance = 1.0
    AND dclocal_read_repair_chance = 0.1
    AND default_time_to_live = 0
    AND gc_grace_seconds = 864000
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair_chance = 0.0
    AND speculative_retry = '99.0PERCENTILE';
CREATE MATERIALIZED VIEW btc.outputs_by_tx_id AS
    SELECT output_tx_id, output_index, address, output_block_height, req_sigs, script_hex, script_type, value
    FROM btc.output_inputs
    WHERE output_tx_id IS NOT null AND output_index IS NOT null AND value IS NOT null
    PRIMARY KEY (output_tx_id, output_index)
    WITH CLUSTERING ORDER BY (output_index ASC)
    AND bloom_filter_fp_chance = 0.01
    AND caching = {'keys': 'ALL', 'rows_per_partition': 'ALL'}
    AND comment = ''
    AND compaction = {'class': 'SizeTieredCompactionStrategy'}
    AND compression = {'sstable_compression': 'org.apache.cassandra.io.compress.LZ4Compressor'}
    AND crc_check_chance = 1.0
    AND dclocal_read_repair_chance = 0.1
    AND default_time_to_live = 0
    AND gc_grace_seconds = 864000
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair_chance = 0.0
    AND speculative_retry = '99.0PERCENTILE';
```

# Logs
`journalctl _COMM=scylla -p warning`:
```
Jul 22 08:26:39 scylla3-explorers-i-0581195877945e0eb scylla[65326]:  [shard 0] storage_proxy - Exception when communicating with 10.2.2.227: sstables::malformed_sstable_exception (end of input, but not end of partition)
Jul 22 08:26:39 scylla3-explorers-i-0581195877945e0eb scylla[65326]:  [shard 4] storage_proxy - Exception when communicating with 10.2.2.227: sstables::malformed_sstable_exception (end of input, but not end of partition)
Jul 22 08:27:02 scylla3-explorers-i-0581195877945e0eb scylla[65326]:  [shard 10] compaction_manager - compaction failed: std::runtime_error (SSTables with Cassandra-style shadowable deletion cannot be read by Scylla)
Jul 22 08:27:02 scylla3-explorers-i-0581195877945e0eb scylla[65326]:  [shard 6] compaction_manager - compaction failed: std::runtime_error (SSTables with Cassandra-style shadowable deletion cannot be read by Scylla)
Jul 22 08:27:02 scylla3-explorers-i-0581195877945e0eb scylla[65326]:  [shard 0] compaction_manager - compaction failed: sstables::malformed_sstable_exception (Too big ttl: 1431775959 in sstable /var/lib/scylla/data/btc/outputs_by_tx_id-73b656a0a3d211e9a63000000000000d/mc-42-big-Data.db)
Jul 22 08:27:02 scylla3-explorers-i-0581195877945e0eb scylla[65326]:  [shard 3] compaction_manager - compaction failed: std::runtime_error (SSTables with Cassandra-style shadowable deletion cannot be read by Scylla)
Jul 22 08:27:02 scylla3-explorers-i-0581195877945e0eb scylla[65326]:  [shard 4] compaction_manager - compaction failed: std::runtime_error (SSTables with Cassandra-style shadowable deletion cannot be read by Scylla)
Jul 22 08:27:02 scylla3-explorers-i-0581195877945e0eb scylla[65326]:  [shard 9] compaction_manager - compaction failed: std::runtime_error (SSTables with Cassandra-style shadowable deletion cannot be read by Scylla)
Jul 22 08:27:02 scylla3-explorers-i-0581195877945e0eb scylla[65326]:  [shard 7] compaction_manager - compaction failed: sstables::malformed_sstable_exception (non-null component after null component in sstable /var/lib/scylla/data/btc/outputs_by_tx_id-73b656a0a3d211e9a63000000000000d/mc-21-big-Data.db)
Jul 22 08:27:02 scylla3-explorers-i-0581195877945e0eb scylla[65326]:  [shard 8] compaction_manager - compaction failed: std::runtime_error (SSTables with Cassandra-style shadowable deletion cannot be read by Scylla)
Jul 22 08:27:02 scylla3-explorers-i-0581195877945e0eb scylla[65326]:  [shard 11] compaction_manager - compaction failed: sstables::malformed_sstable_exception (non-null component after null component in sstable /var/lib/scylla/data/btc/outputs_by_tx_id-73b656a0a3d211e9a63000000000000d/mc-53-big-Data.db)
Jul 22 08:27:02 scylla3-explorers-i-0581195877945e0eb scylla[65326]:  [shard 1] compaction_manager - compaction failed: std::runtime_error (SSTables with Cassandra-style shadowable deletion cannot be read by Scylla)
Jul 22 08:27:02 scylla3-explorers-i-0581195877945e0eb scylla[65326]:  [shard 2] compaction_manager - compaction failed: std::runtime_error (SSTables with Cassandra-style shadowable deletion cannot be read by Scylla)
Jul 22 08:27:04 scylla3-explorers-i-0581195877945e0eb scylla[65326]:  [shard 13] compaction_manager - compaction failed: std::bad_alloc (std::bad_alloc)
Jul 22 08:27:04 scylla3-explorers-i-0581195877945e0eb scylla[65326]:  [shard 12] compaction_manager - compaction failed: std::bad_alloc (std::bad_alloc)
Jul 22 08:27:06 scylla3-explorers-i-0581195877945e0eb scylla[65326]:  [shard 5] compaction_manager - compaction failed: std::runtime_error (SSTables with Cassandra-style shadowable deletion cannot be read by Scylla)
Jul 22 08:27:07 scylla3-explorers-i-0581195877945e0eb scylla[65326]:  [shard 8] compaction_manager - compaction failed: std::runtime_error (SSTables with Cassandra-style shadowable deletion cannot be read by Scylla)
Jul 22 08:27:07 scylla3-explorers-i-0581195877945e0eb scylla[65326]:  [shard 6] compaction_manager - compaction failed: std::runtime_error (SSTables with Cassandra-style shadowable deletion cannot be read by Scylla)
Jul 22 08:27:07 scylla3-explorers-i-0581195877945e0eb scylla[65326]:  [shard 0] compaction_manager - compaction failed: sstables::malformed_sstable_exception (Too big ttl: 1431775959 in sstable /var/lib/scylla/data/btc/outputs_by_tx_id-73b656a0a3d211e9a63000000000000d/mc-42-big-Data.db)
Jul 22 08:27:08 scylla3-explorers-i-0581195877945e0eb scylla[65326]:  [shard 10] compaction_manager - compaction failed: std::runtime_error (SSTables with Cassandra-style shadowable deletion cannot be read by Scylla)
Jul 22 08:27:08 scylla3-explorers-i-0581195877945e0eb scylla[65326]:  [shard 9] compaction_manager - compaction failed: std::runtime_error (SSTables with Cassandra-style shadowable deletion cannot be read by Scylla)
Jul 22 08:27:09 scylla3-explorers-i-0581195877945e0eb scylla[65326]:  [shard 11] compaction_manager - compaction failed: sstables::malformed_sstable_exception (non-null component after null component in sstable /var/lib/scylla/data/btc/outputs_by_tx_id-73b656a0a3d211e9a63000000000000d/mc-53-big-Data.db)
Jul 22 08:27:09 scylla3-explorers-i-0581195877945e0eb scylla[65326]:  [shard 7] compaction_manager - compaction failed: sstables::malformed_sstable_exception (non-null component after null component in sstable /var/lib/scylla/data/btc/outputs_by_tx_id-73b656a0a3d211e9a63000000000000d/mc-21-big-Data.db)
Jul 22 08:27:09 scylla3-explorers-i-0581195877945e0eb scylla[65326]:  [shard 3] compaction_manager - compaction failed: std::runtime_error (SSTables with Cassandra-style shadowable deletion cannot be read by Scylla)
Jul 22 08:27:10 scylla3-explorers-i-0581195877945e0eb scylla[65326]:  [shard 1] compaction_manager - compaction failed: std::runtime_error (SSTables with Cassandra-style shadowable deletion cannot be read by Scylla)
Jul 22 08:27:11 scylla3-explorers-i-0581195877945e0eb scylla[65326]:  [shard 13] compaction_manager - compaction failed: std::bad_alloc (std::bad_alloc)
Jul 22 08:27:12 scylla3-explorers-i-0581195877945e0eb scylla[65326]:  [shard 2] compaction_manager - compaction failed: std::runtime_error (SSTables with Cassandra-style shadowable deletion cannot be read by Scylla)
Jul 22 08:27:14 scylla3-explorers-i-0581195877945e0eb scylla[65326]:  [shard 12] compaction_manager - compaction failed: std::bad_alloc (std::bad_alloc)
Jul 22 08:27:15 scylla3-explorers-i-0581195877945e0eb scylla[65326]:  [shard 5] compaction_manager - compaction failed: std::runtime_error (SSTables with Cassandra-style shadowable deletion cannot be read by Scylla)
Jul 22 08:27:15 scylla3-explorers-i-0581195877945e0eb scylla[65326]:  [shard 4] compaction_manager - compaction failed: std::runtime_error (SSTables with Cassandra-style shadowable deletion cannot be read by Scylla)
```

**Comment by luchenyuxx** [comment] 2019-07-22 13:45
# SSTables

Here you can find the related sstables listed in the log:
- 1.4G    /var/lib/scylla/data/btc/outputs_by_tx_id-73b656a0a3d211e9a63000000000000d/mc-21-big-Data.db
- 1.3G    /var/lib/scylla/data/btc/outputs_by_tx_id-73b656a0a3d211e9a63000000000000d/mc-48-big-Data.db
- 1.4G    /var/lib/scylla/data/btc/outputs_by_tx_id-73b656a0a3d211e9a63000000000000d/mc-51-big-Data.db
- 1.3G    /var/lib/scylla/data/btc/outputs_by_tx_id-73b656a0a3d211e9a63000000000000d/mc-53-big-Data.db
Please find the related sstables here: https://ledger-tmp-scylla.s3-eu-west-1.amazonaws.com/malformed_tables.tar.gz

**Comment by slivne** [comment] 2019-07-25 09:20
@bhalevy - I marked this as MC since the user is using MC (although it may be not MC only).

**Comment by bhalevy** [comment] 2019-07-25 10:44
@haaawk should be familiar with this area of the code

**Comment by haaawk** [comment] 2019-07-25 10:48
It's not related to MC but to MV and shadowable tombstones used for them. We realize the concept differently than cassandra and don't accept cassandras version at the moment.

**Comment by glommer** [comment] 2019-07-25 12:13
As Chenyu said, these files were generated by Scylla.

**Comment by bhalevy** [comment] 2019-08-07 13:23
The presence of `storage_proxy - Exception when communicating with 10.2.2.227: sstables::malformed_sstable_exception (end of input, but not end of partition)` in the log indicates missing `partition_end` mutation, a-la #4733 
@tgrabiec what do you think?

**Comment by haaawk** [comment] 2019-08-07 13:25
This is MC @bhalevy.

**Comment by bhalevy** [comment] 2019-08-07 13:30
Need to understand the root cause of the sstable corruption.
There are also reports of `Too big ttl` and `non-null component after null component` that may be red herrings (along with `SSTables with Cassandra-style shadowable deletion cannot be read by Scylla`)

**Comment by tgrabiec** [comment] 2019-08-12 14:38
@luchenyuxx We need all sstable component files (`mc-21-big-*`). Not just the `Data` component. Do you still have them around?

**Comment by slivne** [comment] 2019-09-03 10:39
no additional info closing the issue

@luchenyuxx if you have the files please post and we will reopen and analyze this

**Closed by slivne** 2019-09-03 10:39 UTC
Labels: Backport 3.0, Backport 3.1, User Request, bug, sstable 3 format
