### ISSUE TITLE
Alternator dtests: Startup failed: std::_Nested_exception<std::runtime_error> (Failed to set up Alternator HTTP server on 127.0.83.1 port 8080, TLS port OFF): std::system_error (error system:98, posix_listen failed for address 127.0.83.1:8080: Address already in use)

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#6335] opened 2020-04-30 08:07 UTC
Seen in https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/469/testReport/alternator_tests/AlternatorTest/test_decommission_during_dynamo_load_2/
and
https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/469/testReport/alternator_tests/AlternatorTest/test_drain_during_dynamo_load_2/

https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/469/artifact/logs-release.2/1588224401896_alternator_tests.AlternatorTest.test_decommission_during_dynamo_load/node1.log
```
ERROR 2020-04-30 05:26:13,963 [shard 0] alternator-server - Failed to set up Alternator HTTP server on 127.0.83.1 port 8080, TLS port OFF: std::system_error (error system:98, posix_listen failed for address 127.0.83.1:8080: Address already in use)
INFO  2020-04-30 05:26:13,963 [shard 1] alternator-server - Alternator HTTP server listening on 127.0.83.1 port 8080
...
ERROR 2020-04-30 05:26:16,178 [shard 0] init - Startup failed: std::_Nested_exception<std::runtime_error> (Failed to set up Alternator HTTP server on 127.0.83.1 port 8080, TLS port OFF): std::system_error (error system:98, posix_listen failed for address 127.0.83.1:8080: Address already in use)
```

It looks like both shards want to listen on port 8080 and one of them fails since the port is already in use by the other shard.

**Comment by nyh** [comment] 2020-04-30 18:18
main() calls server.init() on all shards, and listened on all shards. I think this was deliberate and always worked.

Seeing that the **first** message is about a failed connection, and the second one succeeded, there is also a slim possibility that the problem is something else - could it be we forgot to use SO_REUSEADD, and the port was taken from a previous run? I need to check if the HTTP server enables the reuseaddr option when it listens (see tutorial.md for my explanation on why this is needed).

**Comment by nyh** [comment] 2020-04-30 20:41
My guess about SO_REUSEADDR was wrong. In `alternator/server.c` we use
```c++
               _http_server.listen(socket_address{addr, *port}).get();
```
And `http_server::listen()` with one parameter does:
```c++
    future<> listen(socket_address addr) {
        listen_options lo;
        lo.reuse_address = true;
        return listen(addr, lo);
    }
```
So we correctly set the SO_REUSEADDR option.
So the problem is something else...

@fruch just to get another silly guess out of the way, where did we get the IP address 127.0.83.1? Is it possible that multiple parallel tests pick the same IP address?

**Comment by nyh** [comment] 2020-04-30 20:59
I confirmed that all of Scylla's servers `listen()` on all shard, and it's normal - in fact we have to do it -  `reactor::posix_listen()` uses SO_REUSEPORT so multiple threads can listen to the same port.

Also in normal Alternator runs, we see the all the shards successfully listening on the same port, e.g.,
```
INFO  2020-04-30 23:42:50,653 [shard 0] alternator-server - Alternator HTTP server listening on 0.0.0.0 port 8000
INFO  2020-04-30 23:42:50,857 [shard 3] alternator-server - Alternator HTTP server listening on 0.0.0.0 port 8000
INFO  2020-04-30 23:42:50,857 [shard 4] alternator-server - Alternator HTTP server listening on 0.0.0.0 port 8000
INFO  2020-04-30 23:42:50,857 [shard 1] alternator-server - Alternator HTTP server listening on 0.0.0.0 port 8000
INFO  2020-04-30 23:42:50,857 [shard 2] alternator-server - Alternator HTTP server listening on 0.0.0.0 port 8000
```

So a race between shards cannot explain this (unless the race exposes some Linux kernel bug in SO_REUSEPORT support)... So the only explanation (?) I remain with is that we have a different process which is using the same IP address. But how?

**Comment by fruch** [comment] 2020-04-30 21:21
this is very weird, cause last daily the 4 tests pass, and now two worked fine and two failed with this.

its the exact same code, and those addresses were used in other test but none that should hold this port.

I don't a clue what's  breaking those two...

**Comment by nyh** [comment] 2020-04-30 21:27
I was wrong in what I wrote about SO_REUSEPORT. Seastar doesn't actually use it! It has this:
```c++
bool
reactor::posix_reuseport_detect() {
    return false; // FIXME: reuseport currently leads to heavy load imbalance. Until we fix that, just
                  // disable it unconditionally.
```
So we don't actually use SO_REUSEPORT... It turns out Seastar does something completely different:

As far as I can tell, only one shard is supposed to use `posix_network_stack` and really call `engine().posix_listen()`, while the other shards should use  `posix_ap_network_stack` and do not actually call `posix_listen()` at all! 

So if I'm interpreting things correctly now (I'll need to double-check this on an example Seastar programm....) it's natural for the listen() to actually fail only on shard 0, while it will succeed - without doing anything - on the other shards. If this is true it strengthens my guess that this port was really just busy, which is why the only shard which really tried to listen, failed - and the success on the other shards means nothing.

If this explanation is correct, we should fix the Alternator server startup in `main.cc` to print the initialization error (or success) only once after alternator_server.invoke_on_all() finished- instead of printing a success or errror message once for every shard. This is what we do for the other services started by main (we don't see listening success messages for every shard).

**Comment by nyh** [comment] 2020-04-30 21:40
So @fruch is it possible that we had two concurrent dtests pick the same IP address? How is that IP address picked in the dtest? (thought it uses 127.0.0.<num> for node <num>, but clearly it doesn't, so I don't know what it uses, and how we ensure not to use the same IP address in multiple parallel tests).

**Comment by nyh** [comment] 2020-04-30 21:44
Sorry about the guess, but another wild guess:
Seeing that Scylla was able to take other ports on this IP address, but not 8080, leads me to guess that maybe something on that machine was simply taking 0.0.0.0:8080. The number 8080 is pretty popular for other things, could it be that we had some unrelated random process on this machine is taking this port on all interfaces?

**Comment by fruch** [comment] 2020-04-30 21:47
I'm sure we don't in this session, and even if we had only 4 tests, and
they were'nt running in the same time.

if we had same workerer running 2 sessions it might happen, but those tests
are only in master, so the no other job have them to run this in parallel..

**Comment by fruch** [comment] 2020-04-30 21:49
could be, but still weird, since it isn't running constantly.

**Comment by nyh** [comment] 2020-05-02 10:42
I unassigned myself. Other than the confusing messages from multiple shards (for which I opened issue #6347) I couldn't find anything in the source which might explain how the taken port 8080 can be anything besides another actual process which took port 8080, probably IADDR_ANY. I'll need either more evidence or more ideas to make progress on this issue.

**Comment by fruch** [comment] 2020-05-02 17:44
we could change the port being used, if this keep happening

**Comment by slivne** [comment] 2020-06-02 09:01
closing this issue for now - till we have more info

**Closed by slivne** 2020-06-02 09:01 UTC
Labels: Alternator, Backport 4.0, bug
