### ISSUE TITLE
large reactor stalls when recalculating TLS diffie-helman parameters

### ISSUE THREAD

**Issue by fgelcer** [scylladb/scylla#6191] opened 2020-04-13 19:33 UTC
Installation details
Scylla version (or git commit hash): 4.0.rc0-0.20200405.511773d4662 with build-id de88161d63d02e10ad1b3f2a761cb15aee71d8c9
Cluster size: 4 DB nodes
OS (RHEL/CentOS/Ubuntu/AWS AMI): ami-02ffbefa17e58c217

job running is 1TB 7 days longevity.

node that experienced issue is node-3
```
Reactor stalled for 658 ms on shard 7.
Backtrace:
0x0000000002ed97f2
0x0000000002e7f34b
0x0000000002e7f872
0x0000000002e7fba7
0x00007efe5f87fb1f
0x00007efe5ff728c2
/opt/scylladb/libreloc/libgmp.so.10+0x000000000001fe3c
/opt/scylladb/libreloc/libgmp.so.10+0x000000000001e02d
/opt/scylladb/libreloc/libgmp.so.10+0x0000000000021e7d
/opt/scylladb/libreloc/libhogweed.so.5+0x000000000000ae9c
/opt/scylladb/libreloc/libhogweed.so.5+0x000000000000f9eb
0x00007efe6014e61e
/opt/scylladb/libreloc/libgnutls.so.30+0x000000000004c668
0x000000000322a1c6
0x0000000001407197
0x0000000002342fd6
0x0000000002331fc8
0x0000000002e7b840
0x0000000002e7ba4f
0x0000000002eb39f5
0x0000000002ec201c
0x0000000002e4d70d
/opt/scylladb/libreloc/libpthread.so.0+0x00000000000094e1
/opt/scylladb/libreloc/libc.so.6+0x00000000001016d2
```

decoded:
```
void seastar::backtrace<seastar::backtrace_buffer::append_backtrace()::{lambda(seastar::frame)#1}>(seastar::backtrace_buffer::append_backtrace()::{lambda(seastar::frame)#1}&&) at /usr/include/fmt/format.h:1158
seastar::backtrace_buffer::append_backtrace() at /usr/include/fmt/format.h:1158
 (inlined by) print_with_backtrace at ./build/release/seastar/./seastar/src/core/reactor.cc:755
seastar::internal::cpu_stall_detector::generate_trace() at /usr/include/fmt/format.h:1158
seastar::internal::cpu_stall_detector::maybe_report() at /usr/include/fmt/format.h:1158
 (inlined by) seastar::internal::cpu_stall_detector::on_signal() at ./build/release/seastar/./seastar/src/core/reactor.cc:1062
 (inlined by) seastar::reactor::block_notifier(int) at ./build/release/seastar/./seastar/src/core/reactor.cc:1185
?? ??:0
?? ??:0
?? ??:0
seastar::tls::dh_params::impl::impl(seastar::tls::dh_params::level) at /usr/include/fmt/format.h:1158
 (inlined by) std::_MakeUniq<seastar::tls::dh_params::impl>::__single_object std::make_unique<seastar::tls::dh_params::impl, seastar::tls::dh_params::level&>(seastar::tls::dh_params::level&) at /usr/include/c++/9/bits/unique_ptr.h:849
 (inlined by) seastar::tls::dh_params::dh_params(seastar::tls::dh_params::level) at ./build/release/seastar/./seastar/src/net/tls.cc:179
 (inlined by) seastar::tls::credentials_builder::build_server_credentials() const at ./build/release/seastar/./seastar/src/net/tls.cc:540
cql_transport::cql_server::listen(seastar::socket_address, std::shared_ptr<seastar::tls::credentials_builder>, bool) at /usr/include/fmt/format.h:1158
seastar::future<> seastar::sharded<cql_transport::cql_server>::invoke_on_all<seastar::socket_address, std::shared_ptr<seastar::tls::credentials_builder>, bool>(seastar::smp_submit_to_options, seastar::future<> (cql_transport::cql_server::*)(seastar::socket_address, std::shared_ptr<seastar::tls::credentials_builder>, bool), seastar::socket_address, std::shared_ptr<seastar::tls::credentials_builder>, bool)::{lambda(cql_transport::cql_server&)#1}::operator()(cql_transport::cql_server&) at /usr/include/fmt/format.h:1158
 (inlined by) std::_Function_handler<seastar::future<> (cql_transport::cql_server&), seastar::future<> seastar::sharded<cql_transport::cql_server>::invoke_on_all<seastar::socket_address, std::shared_ptr<seastar::tls::credentials_builder>, bool>(seastar::smp_submit_to_options, seastar::future<> (cql_transport::cql_server::*)(seastar::socket_address, std::shared_ptr<seastar::tls::credentials_builder>, bool), seastar::socket_address, std::shared_ptr<seastar::tls::credentials_builder>, bool)::{lambda(cql_transport::cql_server&)#1}>::_M_invoke(std::_Any_data const&, cql_transport::cql_server&) at /usr/include/c++/9/bits/std_function.h:286
std::function<seastar::future<> (cql_transport::cql_server&)>::operator()(cql_transport::cql_server&) const at /usr/include/fmt/format.h:1158
 (inlined by) seastar::sharded<cql_transport::cql_server>::invoke_on_all(seastar::smp_submit_to_options, std::function<seastar::future<> (cql_transport::cql_server&)>)::{lambda(unsigned int)#1}::operator()(unsigned int) const::{lambda()#1}::operator()() const at ././seastar/include/seastar/core/sharded.hh:660
 (inlined by) seastar::future<> seastar::futurize<seastar::future<> >::apply<seastar::sharded<cql_transport::cql_server>::invoke_on_all(seastar::smp_submit_to_options, std::function<seastar::future<> (cql_transport::cql_server&)>)::{lambda(unsigned int)#1}::operator()(unsigned int) const::{lambda()#1}&>(seastar::sharded<cql_transport::cql_server>::invoke_on_all(seastar::smp_submit_to_options, std::function<seastar::future<> (cql_transport::cql_server&)>)::{lambda(unsigned int)#1}::operator()(unsigned int) const::{lambda()#1}&) at ././seastar/include/seastar/core/future.hh:1674
 (inlined by) seastar::smp_message_queue::async_work_item<seastar::sharded<cql_transport::cql_server>::invoke_on_all(seastar::smp_submit_to_options, std::function<seastar::future<> (cql_transport::cql_server&)>)::{lambda(unsigned int)#1}::operator()(unsigned int) const::{lambda()#1}>::run_and_dispose() at ././seastar/include/seastar/core/smp.hh:215
seastar::reactor::run_tasks(seastar::reactor::task_queue&) at /usr/include/fmt/format.h:1158
seastar::reactor::run_some_tasks() at /usr/include/fmt/format.h:1158
seastar::reactor::run_some_tasks() at /usr/include/fmt/format.h:1158
 (inlined by) seastar::reactor::run() at ./build/release/seastar/./seastar/src/core/reactor.cc:2693
seastar::smp::configure(boost::program_options::variables_map, seastar::reactor_config)::{lambda()#3}::operator()() const at /usr/include/fmt/format.h:1158
std::function<void ()>::operator()() const at /usr/include/c++/9/bits/std_function.h:690
 (inlined by) seastar::posix_thread::start_routine(void*) at ./build/release/seastar/./seastar/src/core/posix.cc:52
```

full logs can be found here:
```
+--------------------------------------------------------------------------------------------------------------------------------------------+
|                                      Collected logs by test-id: bbc128f5-0097-4db4-9327-d46c7d8e73a2                                       |
+-------------+------------------------------------------------------------------------------------------------------------------------------+
| Cluster set | Link                                                                                                                         |
+-------------+------------------------------------------------------------------------------------------------------------------------------+
| db-cluster  | https://cloudius-jenkins-test.s3.amazonaws.com/bbc128f5-0097-4db4-9327-d46c7d8e73a2/20200412_105848/db-cluster-bbc128f5.zip  |
| monitor-set | https://cloudius-jenkins-test.s3.amazonaws.com/bbc128f5-0097-4db4-9327-d46c7d8e73a2/20200412_105848/monitor-set-bbc128f5.zip |
| loader-set  | None                                                                                                                         |
| sct-runner  | https://cloudius-jenkins-test.s3.amazonaws.com/bbc128f5-0097-4db4-9327-d46c7d8e73a2/20200412_105848/sct-runner-bbc128f5.zip  |
+-------------+------------------------------------------------------------------------------------------------------------------------------+
```

**Comment by fgelcer** [comment] 2020-04-13 19:33
could be related to #6190 , #6189 or #6188

**Comment by asias** [comment] 2020-07-07 06:15
This one is different. The stall comes from tls. It looks like it is related to memory allocation as well.

**Comment by avikivity** [comment] 2020-07-07 08:30
I guess d-h calculations can be long. @elcallio can you confirm?

We could push it into a seastar::alien thread (but need to resurrect the patch that makes it work with the seastar allocator).

**Comment by avikivity** [comment] 2020-07-19 07:38
Copying comment from #6192 

/cc @elcallio 

```c++
    impl(level lvl)
            : impl() {
        auto bits = gnutls_sec_param_to_pk_bits(GNUTLS_PK_DH, to_gnutls_level(lvl));
        gtls_chk(gnutls_dh_params_generate2(*this, bits));
    }
```

These to look like they could take a long time. The only solution I can see is to offload it to an alien thread.


btw, the manual says:
>        It is no longer recommended for applications to generate parameters.
>        See the "Parameter generation" section in the manual.

**Comment by elcallio** [comment] 2020-07-21 08:26
Are we on gnutls 3.6+ on all platforms? If so, using `gnutls_certificate_set_known_dh_params` etc does seem much easier...

**Comment by avikivity** [comment] 2020-07-21 09:07
master is using 3.6, so let's start with that.

**Comment by avikivity** [comment] 2020-07-21 09:07
Of course, that's in seastar, so better make it conditional on what's available.

**Comment by elcallio** [comment] 2020-07-27 11:41
Note that /scylladb/seastar#769 was merged, which should make scylla not do any DH computation. We should still change scylla to not use DH settings as all, but instead wholly rely on init string and client negotiation. But that is a different issue. 
@fgelcer, do you have any good repro to see if the above stalls go away in a scylla build with the above seastar change?

**Comment by fgelcer** [comment] 2020-07-27 12:03
> Note that /[scylladb/seastar#769](https://github.com/scylladb/seastar/issues/769) was merged, which should make scylla not do any DH computation. We should still change scylla to not use DH settings as all, but instead wholly rely on init string and client negotiation. But that is a different issue.
> @fgelcer, do you have any good repro to see if the above stalls go away in a scylla build with the above seastar change?

Need to check on last 1TB jobs (either master or one of the releases, if they have this fix), and decode the stalls backtraces.

**Comment by avikivity** [comment] 2020-07-27 13:46
It's only in master for now. If you indicate it is fixed, I'll backport.

**Comment by slivne** [comment] 2020-08-25 08:26
@fgelcer / @roydahan - are the stalls gone, I am closing this issue, if you hit this again please report

**Closed by slivne** 2020-08-25 08:26 UTC
Labels: stability, tls

**Comment by avikivity** [comment] 2020-08-25 08:29
@fgelcer also let us know if it is fixed so we can consider backporting the fix.

**Comment by fgelcer** [comment] 2020-08-25 08:48
> @fgelcer also let us know if it is fixed so we can consider backporting the fix.

my test failed once again with an issue on SCT (that finally got merged), so I'm re-running the test, and will start decode stalls as soon as i get them to check all the stall issues were fixed.

**Comment by avikivity** [comment] 2020-08-25 09:01
@fgelcer it was merged a month ago! was no test run since then?

**Comment by fgelcer** [comment] 2020-08-25 09:23
> @fgelcer it was merged a month ago! was no test run since then?

tests are run manually so far, and in addition to other issues in Scylla and SCT prevented us from getting those results.

**Comment by fgelcer** [comment] 2020-08-25 20:09
> @fgelcer it was merged a month ago! was no test run since then?

just now i saw that it is related to 1TB longevity jobs, and yes, they are constantly running, but i didn't check for stalls on those jobs just yet.

once done with the other latency verification i will jump into this one

**Comment by fgelcer** [comment] 2020-08-27 14:52
running a job to check if this stall happens again or if it introduced regressions:
https://jenkins.scylladb.com/view/master/job/scylla-master/job/longevity/job/reproducers/job/reproduce_6191/

**Comment by roydahan** [comment] 2020-09-02 11:31
@avikivity we don't run this longevity on master on a regular basis.
It's a 7d job and I don't see a point to just run it and hope to reproduce it somehow.
If we know the exact scenario to reproduce it, we can run the specific scenario.

**Comment by avikivity** [comment] 2020-09-02 13:18
It's supposed to happen on every TLS connection. Perhaps you'll see it more with reduced stall detector threshold.

When is the next time you plan to run the test?

**Comment by fgelcer** [comment] 2020-09-06 11:36
@avikivity , i have results of a job similar to the one initially reported... what function should i look for in the stall backtrace?

**Comment by avikivity** [comment] 2020-09-06 13:44
Anything with `seastar::tls`

**Comment by fgelcer** [comment] 2020-09-06 14:08
on the latest run of 1TB longevity, this wasn't reproduced.
running with `666.development-0.20200901.b3f00685e with build-id 0de9edcca81c447d53c39dd1adc333f769f4e240`

**Comment by avikivity** [comment] 2020-09-06 14:36
Fixed in 098d24fd6d3495cb16a754da9c803d570b14d0b0.

**Comment by avikivity** [comment] 2020-09-06 14:38
Backported to 4.2. Will backport further after more feedback from the field.

**Comment by avikivity** [comment] 2020-11-29 12:37
Looks like there were no negative reports, backported to 4.1.
