### ISSUE TITLE
Automatically migrate `system_distributed` to use `NetworkTopologyStrategy`?

### ISSUE THREAD

**Issue by kbr-** [scylladb/scylla#9934] opened 2022-01-17 11:10 UTC
The `system_distributed` keyspace is using `SimpleStrategy, RF=3` replication strategy.

As observed by @avikivity, this means that (in a multi-DC setup - which is the recommended one for production use) the loss of a DC can mean loss of availability of tables in this keyspace.

On `master`, the keyspace currently contains the following tables:
- `view_build_status`
- `service_levels`
- `cdc_streams_descriptions_v2`
- `cdc_generation_timestamps`

The `cdc_*` tables are used during topology changes. They are updated after a topology change is performed using `QUORUM` consistency level (exception: when the first node is started, we use `ONE`). We should also assume that they are periodically read by clients (for example every one minute) - this is what our CDC libraries do; also using `QUORUM` (or `ONE` for single node). It's important that these reads succeed shortly after a topology change, otherwise the latency of observing changes by the clients increases (they won't see changes from a new CDC generation until they learn what the generation's streams are by reading this table).
Perhaps it's not a problem these tables use SimpleStrategy at this point, since we require all nodes to be up during topology changes right now. But what if we relax this assumption in the future?

I don't know when the other two tables are updated and read - could you explain @psarna? Or ping someone who knows? And how unavailability of these tables could affect the system?

---

There are some challenges with migrating internal tables to `NetworkTopologyStrategy`.
For example, do we know what the datacenters are? We would need to know this at the moment of creating the keyspace - which is when setting up the first node - do we?
Or we would have to `ALTER` it after the cluster is set-up - but when do we know when to `ALTER`? Also, changing keyspace's replication strategy after it already contains data is dangerous, since newly calculated replica sets may be disjoint from the old ones (?); can we assume that e.g. repair will correctly migrate the data? We currently don't have a dedicated method of consistent replication strategy changes that would automatically migrate data from old to new replica sets.

---

After writing the above, I started looking in Scylla documentation, because I remembered we also have similar problems for `system_auth` and we actually depend on the administrator to change the replication factor after the cluster is setup. And found that the docs already cover `system_distributed` as well:
https://docs.scylladb.com/operating-scylla/procedures/cluster-management/update-topology-strategy-from-simple-to-network/
https://docs.scylladb.com/operating-scylla/procedures/cluster-management/add-dc-to-existing-dc/#add-new-dc

So the docs recommend that the administrator changes the replication strategies to use `NetworkTopologyStrategy`.
And when adding a new DC, there is a complex manual procedure to include the DC to the set of replication factors and rebuild the data.

Perhaps we should keep relying on the manual procedures?

---

Assuming that `system_distributed` uses `NetworkTopologyStrategy` (whether the procedures are manual or automatic), changes should probably be made to how we manage these tables. For `cdc_*` we should:
- change our internal writes to use `EACH_QUORUM`, not `QUORUM`
- change our clients - and documentation - to query the tables with `LOCAL_QUORUM`, not `QUORUM`.

These changes would improve the availability in DC-loss scenarios.
It is debatable, however, if they are needed (see the first section of this post).

Perhaps similar changes could be recommended for the other two tables.

---

cc @avikivity @vladzcloudius @nyh

**Comment by avikivity** [comment] 2022-01-17 11:41
We should have some way of saying "all datacenters", and I think there is an extension to NetworkTopologyStrategy that does that.

**Comment by kbr-** [comment] 2022-01-17 11:59
The extension checks what the datacenters are at the moment of executing the `ALTER`/`CREATE` and does simple one-time string expansion. By the time DC configuration, the strings are already expanded in the existing keyspaces and there is no trace that the extension was even used.

**Comment by nyh** [comment] 2022-01-17 12:07
This looks like a duplicate of #8582: _Switch internal distributed keyspaces from SimpleStrategy to NetworkTopologyStrategy_.

By the way, @kbr- your observation on that the "auto expand" option means is correct. Last year I made the observation that the name "auto expand" is mis-named and misleading, and made some efforts to change its description in our documentation. It does NOT expand after the initial setting, even if new DCs are created.

**Comment by avikivity** [comment] 2022-01-17 12:21
Closed as duplicate of #8582

**Closed by avikivity** 2022-01-17 12:21 UTC
