### ISSUE TITLE
seastar_memory - oversized allocation ... on all nodes startup

### ISSUE THREAD

**Issue by piavka** [scylladb/scylla#9972] opened 2022-01-26 17:12 UTC
*Installation details*
Scylla version : 4.5.1-0.20211024.4c0eac049-1
Cluster size: issue appeared from few nodes even on empty data cluster up to over 20 nodes now
OS: Ubuntu 18.04.6 LTS

*Hardware details*
i3en.6xlarge aws instances

early on startup of nodes before it start joining we get `seastar_memory - oversized allocation:`

sample log

```
Jan 26 16:57:58 scylla-outcomesdb-i-04d25ca6e1c15158a.sonic-us scylla[16195]:  [shard 0] gossip - Waiting for pending range setup...
Jan 26 16:57:58 scylla-outcomesdb-i-04d25ca6e1c15158a.sonic-us scylla[16195]:  [shard 8] compaction - [Compact system.local 1cee7a80-7ec9-11ec-bd29-95fd9d63fc38] Compacted 4 sstables to [/var/lib/scylla/data/system/local-7ad54392bcdd35a684174e047860b377/md-128-big-Data.db:level=0, ]. 30kB to 12kB (~41% of original) in 25ms = 503kB/s. ~512 total partitions merged to 1.
Jan 26 16:58:35 scylla-outcomesdb-i-04d25ca6e1c15158a.sonic-us scylla[16195]:  [shard 0] gossip - No gossip backlog; proceeding
Jan 26 16:58:35 scylla-outcomesdb-i-04d25ca6e1c15158a.sonic-us scylla[16195]:  [shard 0] seastar_memory - oversized allocation: 2609152 bytes. This is non-fatal, but could lead to latency and/or fragmentation issues. Please report: at 0x431f4be 0x431f960 0x431fd08 0x3f41e3a 0x3f43643 0x3f46345 0x1f25a55 0x21cf900 0x21d6465 0x21d5787 0x23159ff 0x1ac2d12 0x2cbd752 0x2cba247 0x2d50feb 0x4205b21
                                                                                 --------
                                                                                 seastar::continuation<seastar::internal::promise_base_with_type<void>, seastar::async<service::storage_service::join_cluster()::$_79>(seastar::thread_attributes, service::storage_service::join_cluster()::$_79&&)::{lambda()#2}, seastar::future<void>::then_impl_nrvo<{lambda()#2}, seastar::future>(service::storage_service::join_cluster()::$_79&&)::{lambda(seastar::internal::promise_base_with_type<void>&&, {lambda()#2}&, seastar::future_state<seastar::internal::monostate>&&)#1}, void>
                                                                                 --------
                                                                                 seastar::continuation<seastar::internal::promise_base_with_type<void>, seastar::future<void>::finally_body<seastar::async<service::storage_service::join_cluster()::$_79>(seastar::thread_attributes, service::storage_service::join_cluster()::$_79&&)::{lambda()#3}, false>, seastar::future<void>::then_wrapped_nrvo<seastar::future<void>, seastar::async<service::storage_service::join_cluster()::$_79>(seastar::thread_attributes, service::storage_service::join_cluster()::$_79&&)::{lambda()#3}>(seastar::async<service::storage_service::join_cluster()::$_79>(seastar::thread_attributes, service::storage_service::join_cluster()::$_79&&)::{lambda()#3}&&)::{lambda(seastar::internal::promise_base_with_type<void>&&, seastar::async<service::storage_service::join_cluster()::$_79>(seastar::thread_attributes, auto:1&&)::{lambda()#3}&, seastar::future_state<seastar::internal::monostate>&&)#1}, void>
                                                                                 --------
                                                                                 seastar::(anonymous namespace)::thread_wake_task
                                                                                 --------
                                                                                 N7seastar12continuationINS_8internal22promise_base_with_typeIiEEZNS_5asyncIZZ4mainENK3$_2clEvEUlvE0_JEEENS_8futurizeINSt9result_ofIFNSt5decayIT_E4typeEDpNS9_IT0_E4typeEEE4typeEE4typeENS_17thread_attributesEOSA_DpOSD_EUlvE0_ZNS_6futureIvE14then_impl_nrvoISQ_NSR_IiEEEET0_SN_EUlOS3_RSQ_ONS_12future_stateINS1_9monostateEEEE_vEE
                                                                                 --------
                                                                                 seastar::continuation<seastar::internal::promise_base_with_type<int>, seastar::future<int>::finally_body<seastar::async<main::$_2::operator()() const::{lambda()#2}>(seastar::thread_attributes, std::decay&&, (std::decay<main::$_2::operator()() const::{lambda()#2}>::type&&)...)::{lambda()#3}, false>, seastar::future<int>::then_wrapped_nrvo<seastar::future<int>, {lambda()#3}>({lambda()#3}&&)::{lambda(seastar::internal::promise_base_with_type<int>&&, {lambda()#3}&, seastar::future_state<int>&&)#1}, int>
                                                                                 --------
                                                                                 seastar::continuation<seastar::internal::promise_base_with_type<int>, seastar::future<int>::finally_body<seastar::app_template::run(int, char**, std::function<seastar::future<int> ()>&&)::$_0::operator()()::{lambda()#2}, false>, seastar::future<int>::then_wrapped_nrvo<seastar::future<int>, seastar::app_template::run(int, char**, std::function<seastar::future<int> ()>&&)::$_0::operator()()::{lambda()#2}>(seastar::app_template::run(int, char**, std::function<seastar::future<int> ()>&&)::$_0::operator()()::{lambda()#2}&&)::{lambda(seastar::internal::promise_base_with_type<int>&&, seastar::app_template::run(int, char**, std::function<seastar::future<int> ()>&&)::$_0::operator()()::{lambda()#2}&, seastar::future_state<int>&&)#1}, int>
                                                                                 --------
                                                                                 seastar::continuation<seastar::internal::promise_base_with_type<void>, seastar::app_template::run(int, char**, std::function<seastar::future<int> ()>&&)::$_0::operator()()::{lambda(int)#1}, seastar::future<int>::then_impl_nrvo<{lambda(int)#1}, seastar::future<void> >({lambda(int)#1}&&)::{lambda(seastar::internal::promise_base_with_type<void>&&, {lambda(int)#1}&, seastar::future_state<int>&&)#1}, int>
                                                                                 --------
                                                                                 seastar::continuation<seastar::internal::promise_base_with_type<void>, seastar::future<void>::or_terminate()::{lambda(auto:1&&)#1}, seastar::future<void>::then_wrapped_nrvo<void, {lambda(auto:1&&)#1}>({lambda(auto:1&&)#1}&&)::{lambda(seastar::internal::promise_base_with_type<void>&&, {lambda(auto:1&&)#1}&, seastar::future_state<seastar::internal::monostate>&&)#1}, void>
Jan 26 16:58:35 scylla-outcomesdb-i-04d25ca6e1c15158a.sonic-us scylla[16195]:  [shard 0] seastar_memory - oversized allocation: 2609152 bytes. This is non-fatal, but could lead to latency and/or fragmentation issues. Please report: at 0x431f4be 0x431f960 0x431fd08 0x3f41e3a 0x3f43643 0x3f46345 0x19ea503 0x21d0253 0x21d6465 0x21d5787 0x23159ff 0x1ac2d12 0x2cbd752 0x2cba247 0x2d50feb 0x4205b21
                                                                                 --------
                                                                                 seastar::continuation<seastar::internal::promise_base_with_type<void>, seastar::async<service::storage_service::join_cluster()::$_79>(seastar::thread_attributes, service::storage_service::join_cluster()::$_79&&)::{lambda()#2}, seastar::future<void>::then_impl_nrvo<{lambda()#2}, seastar::future>(service::storage_service::join_cluster()::$_79&&)::{lambda(seastar::internal::promise_base_with_type<void>&&, {lambda()#2}&, seastar::future_state<seastar::internal::monostate>&&)#1}, void>
                                                                                 --------
                                                                                 seastar::continuation<seastar::internal::promise_base_with_type<void>, seastar::future<void>::finally_body<seastar::async<service::storage_service::join_cluster()::$_79>(seastar::thread_attributes, service::storage_service::join_cluster()::$_79&&)::{lambda()#3}, false>, seastar::future<void>::then_wrapped_nrvo<seastar::future<void>, seastar::async<service::storage_service::join_cluster()::$_79>(seastar::thread_attributes, service::storage_service::join_cluster()::$_79&&)::{lambda()#3}>(seastar::async<service::storage_service::join_cluster()::$_79>(seastar::thread_attributes, service::storage_service::join_cluster()::$_79&&)::{lambda()#3}&&)::{lambda(seastar::internal::promise_base_with_type<void>&&, seastar::async<service::storage_service::join_cluster()::$_79>(seastar::thread_attributes, auto:1&&)::{lambda()#3}&, seastar::future_state<seastar::internal::monostate>&&)#1}, void>
                                                                                 --------
                                                                                 seastar::(anonymous namespace)::thread_wake_task
                                                                                 --------
                                                                                 N7seastar12continuationINS_8internal22promise_base_with_typeIiEEZNS_5asyncIZZ4mainENK3$_2clEvEUlvE0_JEEENS_8futurizeINSt9result_ofIFNSt5decayIT_E4typeEDpNS9_IT0_E4typeEEE4typeEE4typeENS_17thread_attributesEOSA_DpOSD_EUlvE0_ZNS_6futureIvE14then_impl_nrvoISQ_NSR_IiEEEET0_SN_EUlOS3_RSQ_ONS_12future_stateINS1_9monostateEEEE_vEE
                                                                                 --------
                                                                                 seastar::continuation<seastar::internal::promise_base_with_type<int>, seastar::future<int>::finally_body<seastar::async<main::$_2::operator()() const::{lambda()#2}>(seastar::thread_attributes, std::decay&&, (std::decay<main::$_2::operator()() const::{lambda()#2}>::type&&)...)::{lambda()#3}, false>, seastar::future<int>::then_wrapped_nrvo<seastar::future<int>, {lambda()#3}>({lambda()#3}&&)::{lambda(seastar::internal::promise_base_with_type<int>&&, {lambda()#3}&, seastar::future_state<int>&&)#1}, int>
                                                                                 --------
                                                                                 seastar::continuation<seastar::internal::promise_base_with_type<int>, seastar::future<int>::finally_body<seastar::app_template::run(int, char**, std::function<seastar::future<int> ()>&&)::$_0::operator()()::{lambda()#2}, false>, seastar::future<int>::then_wrapped_nrvo<seastar::future<int>, seastar::app_template::run(int, char**, std::function<seastar::future<int> ()>&&)::$_0::operator()()::{lambda()#2}>(seastar::app_template::run(int, char**, std::function<seastar::future<int> ()>&&)::$_0::operator()()::{lambda()#2}&&)::{lambda(seastar::internal::promise_base_with_type<int>&&, seastar::app_template::run(int, char**, std::function<seastar::future<int> ()>&&)::$_0::operator()()::{lambda()#2}&, seastar::future_state<int>&&)#1}, int>
                                                                                 --------
                                                                                 seastar::continuation<seastar::internal::promise_base_with_type<void>, seastar::app_template::run(int, char**, std::function<seastar::future<int> ()>&&)::$_0::operator()()::{lambda(int)#1}, seastar::future<int>::then_impl_nrvo<{lambda(int)#1}, seastar::future<void> >({lambda(int)#1}&&)::{lambda(seastar::internal::promise_base_with_type<void>&&, {lambda(int)#1}&, seastar::future_state<int>&&)#1}, int>
                                                                                 --------
                                                                                 seastar::continuation<seastar::internal::promise_base_with_type<void>, seastar::future<void>::or_terminate()::{lambda(auto:1&&)#1}, seastar::future<void>::then_wrapped_nrvo<void, {lambda(auto:1&&)#1}>({lambda(auto:1&&)#1}&&)::{lambda(seastar::internal::promise_base_with_type<void>&&, {lambda(auto:1&&)#1}&, seastar::future_state<seastar::internal::monostate>&&)#1}, void>
Jan 26 16:58:35 scylla-outcomesdb-i-04d25ca6e1c15158a.sonic-us scylla[16195]:  [shard 0] storage_service - JOINING: sleeping 30000 ms for pending range setup
Jan 26 16:58:35 scylla-outcomesdb-i-04d25ca6e1c15158a.sonic-us scylla[16195]:  [shard 0] gossip - Waiting for pending range setup...
Jan 26 16:59:12 scylla-outcomesdb-i-04d25ca6e1c15158a.sonic-us scylla[16195]:  [shard 0] gossip - No gossip backlog; proceeding
Jan 26 16:59:12 scylla-outcomesdb-i-04d25ca6e1c15158a.sonic-us scylla[16195]:  [shard 0] storage_service - JOINING: Starting to bootstrap...
```

**Comment by avikivity** [comment] 2022-01-27 13:11
@bhalevy any ideas? lots of recent work in this area, but I didn't find a mention of a large allocation here (I think it's in replicate_to_all_cores).

**Comment by avikivity** [comment] 2022-01-27 13:12
@piavka do you happen to have many keyspaces?

In any case, there is no reason to worry here. There's even no impact on latency, since the node is not yet serving.

**Comment by bhalevy** [comment] 2022-01-27 13:29
The decoded backtrace points towards `db::system_distributed_keyspace::insert_cdc_topology_description -> cql3::query_processor::make_internal_options`

build-id: e0df888020bbfef43aee10264ff14c85581609f7
```
Jan 26 16:58:35 scylla-outcomesdb-i-04d25ca6e1c15158a.sonic-us scylla[16195]:  [shard 0] seastar_memory - oversized allocation: 2609152 bytes. This is non-fatal, but could lead to latency and/or fragmentation issues. Please report: at 0x431f4be 0x431f960 0x431fd08 0x3f41e3a 0x3f43643 0x3f46345 0x1f25a55 0x21cf900 0x21d6465 0x21d5787 0x23159ff 0x1ac2d12 0x2cbd752 0x2cba247 0x2d50feb 0x4205b21

[Backtrace #0]
void seastar::backtrace(seastar::current_backtrace_tasklocal()::$_3&&) at ./build/release/seastar/./seastar/include/seastar/util/backtrace.hh:59
 (inlined by) seastar::current_backtrace_tasklocal() at ./build/release/seastar/./seastar/src/util/backtrace.cc:86
seastar::current_tasktrace() at ./build/release/seastar/./seastar/src/util/backtrace.cc:137
seastar::current_backtrace() at ./build/release/seastar/./seastar/src/util/backtrace.cc:170
seastar::memory::cpu_pages::warn_large_allocation(unsigned long) at ./build/release/seastar/./seastar/src/core/memory.cc:752
seastar::memory::cpu_pages::check_large_allocation(unsigned long) at ./build/release/seastar/./seastar/src/core/memory.cc:760
 (inlined by) seastar::memory::cpu_pages::allocate_large(unsigned int) at ./build/release/seastar/./seastar/src/core/memory.cc:766
 (inlined by) seastar::memory::allocate_large(unsigned long) at ./build/release/seastar/./seastar/src/core/memory.cc:1318
 (inlined by) seastar::memory::allocate(unsigned long) at ./build/release/seastar/./seastar/src/core/memory.cc:1380
malloc at ./build/release/seastar/./seastar/src/core/memory.cc:1806
basic_sstring at ././seastar/include/seastar/core/sstring.hh:149
 (inlined by) abstract_type::decompose(data_value const&) const at ./types.cc:2907
cql3::query_processor::make_internal_options(seastar::checked_ptr, seastar::default_null_deref_action> const&, std::initializer_list const&, db::consistency_level, int) const at ./cql3/query_processor.cc:637
cql3::query_processor::execute_with_params(seastar::checked_ptr, seastar::default_null_deref_action>, db::consistency_level, service::query_state&, std::initializer_list const&) at ./cql3/query_processor.cc:827
cql3::query_processor::execute_internal(seastar::basic_sstring const&, db::consistency_level, service::query_state&, std::initializer_list const&, bool) at ./cql3/query_processor.cc:817
db::system_distributed_keyspace::insert_cdc_topology_description(std::chrono::time_point > >, cdc::topology_description const&, db::system_distributed_keyspace::context) at ./db/system_distributed_keyspace.cc:310
cdc::make_new_cdc_generation(db::config const&, std::unordered_set, std::equal_to, std::allocator > const&, seastar::lw_shared_ptr, gms::gossiper const&, db::system_distributed_keyspace&, std::chrono::duration >, bool) at ./cdc/generation.cc:371
service::storage_service::bootstrap() at ./service/storage_service.cc:666
service::storage_service::join_token_ring(int) at ./service/storage_service.cc:519
operator() at ./service/storage_service.cc:1418
 (inlined by) void std::__invoke_impl(std::__invoke_other, service::storage_service::join_cluster()::$_79&&) at /usr/lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/bits/invoke.h:60
 (inlined by) std::__invoke_result::type std::__invoke(service::storage_service::join_cluster()::$_79&&) at /usr/lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/bits/invoke.h:95
 (inlined by) decltype(auto) std::__apply_impl>(service::storage_service::join_cluster()::$_79&&, std::tuple<>&&, std::integer_sequence) at /usr/lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/tuple:1723
 (inlined by) decltype(auto) std::apply >(service::storage_service::join_cluster()::$_79&&, std::tuple<>&&) at /usr/lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/tuple:1734
 (inlined by) seastar::future seastar::futurize::apply(service::storage_service::join_cluster()::$_79&&, std::tuple<>&&) at ././seastar/include/seastar/core/future.hh:2099
 (inlined by) operator() at ././seastar/include/seastar/core/thread.hh:258
 (inlined by) seastar::noncopyable_function::direct_vtable_for(seastar::thread_attributes, service::storage_service::join_cluster()::$_79&&)::{lambda()#1}>::call(seastar::noncopyable_function const*) at ././seastar/include/seastar/util/noncopyable_function.hh:124
seastar::noncopyable_function::operator()() const at ./build/release/seastar/./seastar/include/seastar/util/noncopyable_function.hh:209
 (inlined by) seastar::thread_context::main() at ./build/release/seastar/./seastar/src/core/thread.cc:299
```

**Comment by piavka** [comment] 2022-01-27 19:03
> @piavka do you happen to have many keyspaces?
> 
> In any case, there is no reason to worry here. There's even no impact on latency, since the node is not yet serving.

@avikivity  no just one keyspace

**Comment by haaawk** [comment] 2022-01-28 14:41
@kbr- please have a look when you have some spare time

**Comment by bhalevy** [comment] 2022-01-30 07:07
Duplicate of #7961

**Closed by bhalevy** 2022-01-30 07:07 UTC
