### ISSUE TITLE
scylla-server failed to start: seastar Assertion `r >= 0' failed

### ISSUE THREAD

**Issue by amoskong** [scylladb/scylla#3849] opened 2018-10-15 01:43 UTC
*Installation details*
Scylla version (or git commit hash): scylla-3.0.rc0-0.20181010.eb2814067.el7.x86_64.rpm
Cluster size: 1
OS (RHEL/CentOS/Ubuntu/AWS AMI): ami-005df5afd263dc997

* Description
Scylla-server failed to start.

* Test job: http://jenkins.cloudius-systems.com:8080/view/scylla-3.0/job/scylla-3.0/job/3.0-test/job/scylla-ami-test/label=muninn/2/artifact/job-2018-10-11T12.56-d7381a0/job.log

* Test error:

```
Oct 11 10:02:05 ip-172-30-0-237.ec2.internal scylla_prepare[2627]: tuning /sys/devices/virtual/block/md0
Oct 11 10:02:14 ip-172-30-0-237.ec2.internal scylla[2694]: scylla: core/reactor.cc:561: seastar::reactor::reactor(unsigned int): Assertion `r >= 0' failed.
Oct 11 10:02:14 ip-172-30-0-237.ec2.internal scylla[2694]: scylla: core/reactor.cc:561: seastar::reactor::reactor(unsigned int): Assertion `r >= 0' failed.
Oct 11 10:02:14 ip-172-30-0-237.ec2.internal scylla[2694]: scylla: core/reactor.cc:561: seastar::reactor::reactor(unsigned int): Assertion `r >= 0' failed.
Oct 11 10:02:14 ip-172-30-0-237.ec2.internal scylla[2694]: scylla: core/reactor.cc:561: seastar::reactor::reactor(unsigned int): Assertion `r >= 0' failed.
Oct 11 10:02:14 ip-172-30-0-237.ec2.internal scylla[2694]: scylla: core/reactor.cc:561: seastar::reactor::reactor(unsigned int): Assertion `r >= 0' failed.
Oct 11 10:02:14 ip-172-30-0-237.ec2.internal scylla[2694]: scylla: core/reactor.cc:561: seastar::reactor::reactor(unsigned int): Assertion `r >= 0' failed.
Oct 11 10:08:50 ip-172-30-0-237.ec2.internal systemd[1]: scylla-server.service: main process exited, code=killed, status=6/ABRT
Oct 11 10:08:50 ip-172-30-0-237.ec2.internal systemd[1]: Failed to start Scylla Server.
```

* Full log:
[scylla-setup-start-full-log.txt](https://github.com/scylladb/scylla/files/2477130/scylla-setup-start-full-log.txt)

**Comment by roydahan** [comment] 2018-10-15 13:12
Duplicate of #3842

**Closed by roydahan** 2018-10-15 13:12 UTC
