### ISSUE TITLE
Upgrade from 3.1.1 to 3.2.4 corrupt an SStable with frozen UDT

### ISSUE THREAD

**Issue by santithorn** [scylladb/scylla#6130] opened 2020-04-03 22:46 UTC
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [x] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash): 3.2.4
Cluster size: 1
OS (RHEL/CentOS/Ubuntu/AWS AMI): CentOS

I upgrade ScyllaDB from 3.1.1 to 3.2.4. After restarting into 3.2.4, I found an error message indicating that the table "config" cannot be read from the SStable file, with the problem related to the serialization of a column with UDT:

Apr 04 05:35:32 uat-data1 scylla[2174]:  [shard 0] compaction_manager - compaction failed: sstables::malformed_sstable_exception (fee definition in serialization header does not match schema. Expected org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.UTF8Type,org.apache.cassandra.db.marshal.FrozenType(org.apache.cassandra.db.marshal.UserType(pacificdb,6665655f3032,6d6178:org.apache.cassandra.db.marshal.DoubleType,6d696e:org.apache.cassandra.db.marshal.DoubleType,74797065:org.apache.cassandra.db.marshal.UTF8Type,666565:org.apache.cassandra.db.marshal.FrozenType(org.apache.cassandra.db.marshal.ListType(org.apache.cassandra.db.marshal.FrozenType(org.apache.cassandra.db.marshal.UserType(pacificdb,6665655f30315f76616c7565,616d6f756e74:org.apache.cassandra.db.marshal.DoubleType,616d6f756e745f66726f6d:org.apache.cassandra.db.marshal.DoubleType,616d6f756e745f746f:org.apache.cassandra.db.marshal.DoubleType,666565:org.apache.cassandra.db.marshal.DoubleType,636f6465:org.apache.cassandra.db.marshal.UTF8Type))))))) but got org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.UTF8Type,org.apache.cassandra.db.marshal.UserType(pacificdb,6665655f3032,6d6178:org.apache.cassandra.db.marshal.DoubleType,6d696e:org.apache.cassandra.db.marshal.DoubleType,74797065:org.apache.cassandra.db.marshal.UTF8Type,666565:org.apache.cassandra.db.marshal.FrozenType(org.apache.cassandra.db.marshal.ListType(org.apache.cassandra.db.marshal.UserType(pacificdb,6665655f30315f76616c7565,616d6f756e74:org.apache.cassandra.db.marshal.DoubleType,616d6f756e745f66726f6d:org.apache.cassandra.db.marshal.DoubleType,616d6f756e745f746f:org.apache.cassandra.db.marshal.DoubleType,666565:org.apache.cassandra.db.marshal.DoubleType,636f6465:org.apache.cassandra.db.marshal.UTF8Type))))) in sstable /var/lib/scylla/data/pacificdb/config-16efe27091fe11e7ab87000000000000/mc-19-big-Data.db): retrying
Apr 04 05:35:32 uat-data1 scylla[2174]:  [shard 0] compaction_manager - compaction task handler sleeping for 300 seconds

The "config" table has the following structure:

CREATE TABLE pacificdb.config (
    name text PRIMARY KEY,
    apps text,
    fee map<text, frozen<fee_02>>,
    language text,
    mode map<text, text>,
    screen text,
    software map<text, text>,
    splash text,
    stuff map<text, text>,
    test text,
    type text
);

And the fee_02 is defined as:

CREATE TYPE pacificdb.fee_02 (
    max double,
    min double,
    type text,
    fee frozen<list<frozen<fee_01_value>>>
);

CREATE TYPE pacificdb.fee_01_value (
    amount double,
    amount_from double,
    amount_to double,
    fee double,
    code text
);

The result is I can no longer access this table.

It seems Scylla 3.2 cannot correctly interpret SStable from 3.1 with implied frozen type, or maybe it should migrate this SStable when upgrade.

Also is there a way I can migrate this SStable to the correct format for Scylla 3.2?

**Comment by slivne** [comment] 2020-04-04 21:31
@santithorn I am not able to reproduce this "easily"

I did the following:

Started an instance with 3.1.1

ran the following commands via cqlsh

```
CREATE KEYSPACE pacificdb WITH replication = {'class': 'SimpleStrategy', 'replication_factor': '1'}  AND durable_writes = true;

CREATE TYPE pacificdb.fee_01_value (
    amount double,
    amount_from double,
    amount_to double,
    fee double,
    code text
);

CREATE TYPE pacificdb.fee_02 (
    max double,
    min double,
    type text,
    fee frozen<list<frozen<fee_01_value>>>
);

CREATE TABLE pacificdb.config (
    name text PRIMARY KEY,
    apps text,
    fee map<text, frozen<fee_02>>,
    language text,
    mode map<text, text>,
    screen text,
    software map<text, text>,
    splash text,
    stuff map<text, text>,
    test text,
    type text
);

insert into config (name,apps,fee,language,mode,screen,software,splash,stuff,test,type) VALUES ( 'n','a',{'f': (1.0,1.0,'t',[(2.0,3.0,4.0,5.0,'fee_01_value'),(12.0,13.0,14.0,15.0,'fee_01_value_2')])},'l',{'m':'a'},'screen',{'s':'a'},'splash',{'stuff':'b'},'test','type');
insert into config (name,apps,fee,language,mode,screen,software,splash,stuff,test,type) VALUES ( 'n2','a',{'f': (1.0,1.0,'t',[(2.0,3.0,4.0,5.0,'fee_01_value'),(12.0,13.0,14.0,15.0,'fee_01_value_2')])},'l',{'m':'a'},'screen',{'s':'a'},'splash',{'stuff':'b'},'test','type');
insert into config (name,apps,fee,language,mode,screen,software,splash,stuff,test,type) VALUES ( 'n3','a',{'f': (1.0,1.0,'t',[(2.0,3.0,4.0,5.0,'fee_01_value'),(12.0,13.0,14.0,15.0,'fee_01_value_2')])},'l',{'m':'a'},'screen',{'s':'a'},'splash',{'stuff':'b'},'test','type');
```
ran  ```select * from pacificdb.config ;``` that shows the content

Upgraded to 3.2.4 using scylla docs: https://docs.scylladb.com/upgrade/upgrade-opensource/upgrade-guide-from-3.1-to-3.2/upgrade-guide-from-3.1-to-3.2-rpm/

ran  ```select * from pacificdb.config ;``` that shows the content

I need your help to reproduce this or some other info.


1. What was the first Scylla version installed on this cluster (3.1.1 or something else) ?
2. Were the User Defined Types  fee_01_value, fee_02 changed after some data was inserted already 
3. Can you provide your system_schema - its under /var/lib/scylla/data/system_schema (tar the whole directory and sub directories)
4. Can you provide sample sstables with your data for the config table

To upload the data please use the procedure documented at: https://docs.scylladb.com/troubleshooting/report_scylla_problem/#send-files-to-scylladb-support

With the additional info we will try to reproduce the issue and than resolve it.

**Comment by kbr-** [comment] 2020-04-06 11:29
@santithorn 

was this cluster previously upgraded from 3.0.x?
I have a hypothesis that the malformed sstables were created in 3.0 (they didn't add the FrozenType<...> tag), but I haven't been able to verify it yet (compiling 3.0 these days is not trivial).

**Comment by kbr-** [comment] 2020-04-06 12:01
Indeed. I compiled Scylla on branch-3.0 and created a table with map and frozen user type inside:
```
cqlsh> create keyspace ks with replication = {'class':'SimpleStrategy', 'replication_factor': 1};
cqlsh> create type ks.ut (a int, b int);
cqlsh> create table ks.t (a int primary key, b map<int, frozen<ut>>);
```

Scylla logs showed:
```
INFO  2020-04-06 13:59:21,544 [shard 1] migration_manager - Create new ColumnFamily: org.apache.cassandra.config.CFMetaData@0x6010006dca80[cfId=0d38b480-77fe-11ea-9a10-000000000000,ksName=ks,cfName=t,cfType=Standard,comparator=org.apache.cassandra.db.marshal.CompositeType(org.apache.cassandra.db.marshal.UTF8Type,org.
apache.cassandra.db.marshal.ColumnToCollectionType(62:org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.Int32Type,org.apache.cassandra.db.marshal.UserType(ks,7574,61:org.apache.cassandra.db.marshal.Int32Type,62:org.apache.cassandra.db.marshal.Int32Type)))),comment=,readRepairChance=0,dcLocalRead
RepairChance=0.1,gcGraceSeconds=864000,keyValidator=org.apache.cassandra.db.marshal.Int32Type,minCompactionThreshold=4,maxCompactionThreshold=32,columnMetadata=[ColumnDefinition{name=a, type=org.apache.cassandra.db.marshal.Int32Type, kind=PARTITION_KEY, componentIndex=0, droppedAt=-9223372036854775808}, ColumnDefinit
ion{name=b, type=org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.Int32Type,org.apache.cassandra.db.marshal.UserType(ks,7574,61:org.apache.cassandra.db.marshal.Int32Type,62:org.apache.cassandra.db.marshal.Int32Type)), kind=REGULAR, componentIndex=null, droppedAt=-9223372036854775808}],compactio
nStrategyClass=class org.apache.cassandra.db.compaction.SizeTieredCompactionStrategy,compactionStrategyOptions={enabled=true},compressionParameters={sstable_compression=org.apache.cassandra.io.compress.LZ4Compressor},bloomFilterFpChance=0.01,memtableFlushPeriod=0,caching={"keys":"ALL","rows_per_partition":"ALL"},defa
ultTimeToLive=0,minIndexInterval=128,maxIndexInterval=2048,speculativeRetry=99.0PERCENTILE,triggers=[],isDense=false,version=0d38b481-77fe-11ea-9a10-000000000000,droppedColumns={},collections={62 : org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.Int32Type,org.apache.cassandra.db.marshal.UserTy
pe(ks,7574,61:org.apache.cassandra.db.marshal.Int32Type,62:org.apache.cassandra.db.marshal.Int32Type))},indices={}]
```

Notice the lack of `FrozenType<...>` around `UserType<...>`.

Still need to investigate why this wasn't catched after upgrading to 3.1.

**Comment by kbr-** [comment] 2020-04-06 15:18
Ok, here's the problem:

there is an sstable which uses wrong serialization headers: it uses `UserType<...>` instead of `FrozenType<UserType<...>>`. One way to create such sstable is to use Scylla 3.0 with `enabled_sstables_mc_format: true`, then flush/compact your tables.

Scylla 3.1 fixed this bug, perhaps accidentally. When Scylla 3.1 saw `UserType<...>` without `FrozenType<...>` around it, it would still read the sstable, and when compacting it, it would correctly rewrite it into `FrozenType<UserType<...>>`.

However, Scylla 3.2 added non-frozen UDT support, so it cannot treat `UserType<...>` as `FrozenType<UserType<...>>`, because now these things are different. Well, there is a special case: `UserType<...>` inside a collection is actually a `FrozenType<UserType<...>>`, because we don't support multi-cell things inside collections yet. But Scylla 3.2 doesn't recognize that, it assumes that `UserType<...>` means non-frozen, always.
So Scylla 3.2 will report a mismatch between schema and sstable serialization headers.

---

@santithorn 

Your `pacificdb.config` sstables are still readable by Scylla 3.1. If you can start Scylla 3.1 with those sstables, you can then run `nodetool compact`, and after that should be able to upgrade to Scylla 3.2.

If this sounds like too much of a problem, we can provide a tool which will rewrite the sstables into the correct format.

**Comment by haaawk** [comment] 2020-04-06 15:22
We can also fix 3.2 to know that inside collection UDT is always frozen.

**Comment by kbr-** [comment] 2020-04-06 15:23
@haaawk 

maybe, but it would be a 3.2 specific fix, we certainly should not include it into future releases (if we plan to add non-frozen UDT/collection inside collection support).

**Comment by haaawk** [comment] 2020-04-06 15:24
I think we can assume we won't. As far as I know, non-frozen collections are also not allowed inside other collection.

**Comment by kbr-** [comment] 2020-04-06 15:27
Yes, today, but not necessarily in the future. See Cassandra:
https://issues.apache.org/jira/browse/CASSANDRA-7826

**Comment by haaawk** [comment] 2020-04-06 15:28
Fair point.

**Comment by slivne** [comment] 2020-04-06 15:31
@avikivity please provide input on how you want this solved

**Comment by avikivity** [comment] 2020-04-06 15:38
We can have a config flag that says udt_inside_collection_is_always_frozen, and a scylla metadata (Scyla.db) flag that says correct_udt_in_collection.

The rules will be:
 - new version always writes according to the specification, and also sets correct_udt_in_collection in new sstables
 - if correct_udt_in_collection is set, or if udt_inside_collection_is_always_frozen is clear, we read that sstable according to spec
 - otherwise, we read it in the way that 3.1 wrote it

To upgrade (or import from 3.1 or earlier)
 - set udt_inside_collection_is_always_frozen
 - scrub sstables
 - clear udt_inside_collection_is_always_frozen

**Comment by kbr-** [comment] 2020-04-06 15:47
The `correct_udt_in_collection` flag should be enough.

No flag inside sstable
 => the sstable was written before this flag was implemented
 => the sstable was written before non-frozen udt inside collection was implemented

thus, if we see sstable without this flag, we can be liberal in reading the sstable (i.e. read it even if it doesn't wrap `FrozenType` around `UserType`
if we see sstable with this flag, we are conservative.

**Comment by tarzanek** [comment] 2020-04-06 16:01
confirming reproduction steps, critical is the use of frozen UDT in a map and a switch to mc in 3.0 and lack of compaction in when upgrading from 3.1 to 3.2
(which is understandable, but at the same time if one can afford it, this is a _workaround_: If you have frozen UDTs in 3.0 with mc, then please _compact in 3.1_. )

**Comment by slivne** [comment] 2020-04-06 22:39
So cassandra had the same issue https://issues.apache.org/jira/browse/CASSANDRA-11613 - they fixed the schema during the upgrade. 

From what I understand their solution was to update the schema as well during the upgrade, are we doing that ?

**Comment by santithorn** [comment] 2020-04-07 17:59
> @santithorn
> 
> Your `pacificdb.config` sstables are still readable by Scylla 3.1. If you can start Scylla 3.1 with those sstables, you can then run `nodetool compact`, and after that should be able to upgrade to Scylla 3.2.
> 
> If this sounds like too much of a problem, we can provide a tool which will rewrite the sstables into the correct format.

@kbr- Thanks for tracking down the problem. If the tool you mentioned is readily available, I would love to try that. Otherwise, I can try compacting the sstables in 3.1 as you suggested.

**Comment by kbr-** [comment] 2020-04-08 14:50
@slivne 

In the proposed PR I'm reinterpreting the sstable's schema when reading data from it into memory. But I'm not changing the sstable itself.
But compaction the schema in new sstables will be fixed.

@santithorn 

We don't have a tool like that, but I opened a PR with a patch which will allow Scylla 3.2 to read these sstables. Hopefully it will be merged and backported soon.

**Closed** 2020-04-17 05:57 UTC
Labels: Backport 3.3, Backport 4.0, Backport candidate, User Request, backport 3.2, bug, high, upgrade

**Comment by avikivity** [comment] 2020-04-17 06:54
Backported to 3.2, 3.3, 4.0.

**Comment by avikivity** [comment] 2020-05-07 16:43
@penberg why did the bot re-add the Backport candidate label?
