### ISSUE TITLE
Failed to run scylla with charybdefs (Storage I/O error: 9: Bad file descriptor)

### ISSUE THREAD

**Issue by amoskong** [scylladb/scylla#2971] opened 2017-11-15 03:57 UTC
*Installation details*
Scylla version (or git commit hash): 666.development-0.20171112.f8af4f5
Cluster size: 1
OS (RHEL/CentOS/Ubuntu/AWS AMI): CentOS

I had cleared all faults conditions, but still touched fd error.

```
git clone https://github.com/scylladb/charybdefs
cd charybdefs/
yum install gcc-c++ cmake cmake thrift fuse-devel python-thrift thrift-devel
thrift -r --gen cpp server.thrift
cmake CMakeLists.txt
make

umount /var/lib/scylla
rm -rf /var/lib/scylla/*
rm -rf /var/lib/scylla/.pki
rm -rf /root/scylla
mkdir /root/scylla

./charybdefs /var/lib/scylla/ -omodules=subdir,subdir=/root/scylla
cd ./cookbook
./recipes --clear
cd -

mkdir /var/lib/scylla/commitlog
mkdir /var/lib/scylla/data

killall -9 scylla
scylla --developer-mode=1 --options-file=/etc/scylla/scylla.yaml > /root/scylla.log 2>&1
```

```
ERROR 2017-11-15 03:50:40,667 [shard 0] database - failed to write sstable /var/lib/scylla/data/system/local-7ad54392bcdd35a684174e047860b377/system-local-ka-4-Data.db: storage_io_error (Storage I/O error: 9: Bad file descriptor)
ERROR 2017-11-15 03:50:50,668 [shard 0] database - failed to write sstable /var/lib/scylla/data/system/local-7ad54392bcdd35a684174e047860b377/system-local-ka-6-Data.db: storage_io_error (Storage I/O error: 9: Bad file descriptor)
ERROR 2017-11-15 03:51:00,669 [shard 0] database - failed to write sstable /var/lib/scylla/data/system/local-7ad54392bcdd35a684174e047860b377/system-local-ka-8-Data.db: storage_io_error (Storage I/O error: 9: Bad file descriptor)
...
```
```
$ df
/dev/sda1       31443968 29491820   1952148  94% /
devtmpfs         3823040        0   3823040   0% /dev
tmpfs            3829672        0   3829672   0% /dev/shm
tmpfs            3829672     8544   3821128   1% /run
tmpfs            3829672        0   3829672   0% /sys/fs/cgroup
/dev/sdc        51606140 10287628  38697072  22% /home/amos/space
tmpfs             765936        0    765936   0% /run/user/1004
tmpfs             765936        0    765936   0% /run/user/0
charybdefs      31443968 29491820   1952148  94% /var/lib/scylla
```

[scylla.log](https://github.com/scylladb/scylla/files/1473369/scylla.log)

@raphaelsc @benoit-canet

**Comment by raphaelsc** [comment] 2017-11-15 04:35
On Wed, Nov 15, 2017 at 1:57 AM, Amos Kong <notifications@github.com> wrote:

> *Installation details*
> Scylla version (or git commit hash): 666.development-0.20171112.f8af4f5
> Cluster size: 1
> OS (RHEL/CentOS/Ubuntu/AWS AMI): CentOS
>
> I had cleared all faults conditions, but still touched fd error.
>
> git clone https://github.com/scylladb/charybdefs
> cd charybdefs/
> yum install gcc-c++ cmake cmake thrift fuse-devel python-thrift thrift-devel
> thrift -r --gen cpp server.thrift
> cmake CMakeLists.txt
> make
>
> umount /var/lib/scylla
> rm -rf /var/lib/scylla/*
> rm -rf /var/lib/scylla/.pki
> rm -rf /root/scylla
> mkdir /root/scylla
>
> ./charybdefs /var/lib/scylla/ -omodules=subdir,subdir=/root/scylla
> cd ./cookbook
> ./recipes --clear
> cd -
>
> mkdir /var/lib/scylla/commitlog
> mkdir /var/lib/scylla/data
>
> killall -9 scylla
> scylla --developer-mode=1 --options-file=/etc/scylla/scylla.yaml > /root/scylla.log 2>&1
>
> ERROR 2017-11-15 03:50:40,667 [shard 0] database - failed to write sstable /var/lib/scylla/data/system/local-7ad54392bcdd35a684174e047860b377/system-local-ka-4-Data.db: storage_io_error (Storage I/O error: 9: Bad file descriptor)
> ERROR 2017-11-15 03:50:50,668 [shard 0] database - failed to write sstable /var/lib/scylla/data/system/local-7ad54392bcdd35a684174e047860b377/system-local-ka-6-Data.db: storage_io_error (Storage I/O error: 9: Bad file descriptor)
> ERROR 2017-11-15 03:51:00,669 [shard 0] database - failed to write sstable /var/lib/scylla/data/system/local-7ad54392bcdd35a684174e047860b377/system-local-ka-8-Data.db: storage_io_error (Storage I/O error: 9: Bad file descriptor)
> ...
>
> $ df
> /dev/sda1       31443968 29491820   1952148  94% /
> devtmpfs         3823040        0   3823040   0% /dev
> tmpfs            3829672        0   3829672   0% /dev/shm
> tmpfs            3829672     8544   3821128   1% /run
> tmpfs            3829672        0   3829672   0% /sys/fs/cgroup
> /dev/sdc        51606140 10287628  38697072  22% /home/amos/space
> tmpfs             765936        0    765936   0% /run/user/1004
> tmpfs             765936        0    765936   0% /run/user/0
> charybdefs      31443968 29491820   1952148  94% /var/lib/scylla
>
> scylla.log <https://github.com/scylladb/scylla/files/1473369/scylla.log>
>
> @raphaelsc <https://github.com/raphaelsc> @benoit-canet
> <https://github.com/benoit-canet>
>

probably a integrity checker issue because the error doesn't happen with it
disabled. EBADF could be due to file opened without READ flag enabled but I
checked that's not the case. However, failure comes when reading after
write. Awkward, no? :-) i'll investigate it more.

**Comment by raphaelsc** [comment] 2017-11-15 04:46
On Wed, Nov 15, 2017 at 2:35 AM, Raphael S. Carvalho <raphaelsc@scylladb.com
> wrote:

>
>
> On Wed, Nov 15, 2017 at 1:57 AM, Amos Kong <notifications@github.com>
> wrote:
>
>> *Installation details*
>> Scylla version (or git commit hash): 666.development-0.20171112.f8af4f5
>> Cluster size: 1
>> OS (RHEL/CentOS/Ubuntu/AWS AMI): CentOS
>>
>> I had cleared all faults conditions, but still touched fd error.
>>
>> git clone https://github.com/scylladb/charybdefs
>> cd charybdefs/
>> yum install gcc-c++ cmake cmake thrift fuse-devel python-thrift thrift-devel
>> thrift -r --gen cpp server.thrift
>> cmake CMakeLists.txt
>> make
>>
>> umount /var/lib/scylla
>> rm -rf /var/lib/scylla/*
>> rm -rf /var/lib/scylla/.pki
>> rm -rf /root/scylla
>> mkdir /root/scylla
>>
>> ./charybdefs /var/lib/scylla/ -omodules=subdir,subdir=/root/scylla
>> cd ./cookbook
>> ./recipes --clear
>> cd -
>>
>> mkdir /var/lib/scylla/commitlog
>> mkdir /var/lib/scylla/data
>>
>> killall -9 scylla
>> scylla --developer-mode=1 --options-file=/etc/scylla/scylla.yaml > /root/scylla.log 2>&1
>>
>> ERROR 2017-11-15 03:50:40,667 [shard 0] database - failed to write sstable /var/lib/scylla/data/system/local-7ad54392bcdd35a684174e047860b377/system-local-ka-4-Data.db: storage_io_error (Storage I/O error: 9: Bad file descriptor)
>> ERROR 2017-11-15 03:50:50,668 [shard 0] database - failed to write sstable /var/lib/scylla/data/system/local-7ad54392bcdd35a684174e047860b377/system-local-ka-6-Data.db: storage_io_error (Storage I/O error: 9: Bad file descriptor)
>> ERROR 2017-11-15 03:51:00,669 [shard 0] database - failed to write sstable /var/lib/scylla/data/system/local-7ad54392bcdd35a684174e047860b377/system-local-ka-8-Data.db: storage_io_error (Storage I/O error: 9: Bad file descriptor)
>> ...
>>
>> $ df
>> /dev/sda1       31443968 29491820   1952148  94% /
>> devtmpfs         3823040        0   3823040   0% /dev
>> tmpfs            3829672        0   3829672   0% /dev/shm
>> tmpfs            3829672     8544   3821128   1% /run
>> tmpfs            3829672        0   3829672   0% /sys/fs/cgroup
>> /dev/sdc        51606140 10287628  38697072  22% /home/amos/space
>> tmpfs             765936        0    765936   0% /run/user/1004
>> tmpfs             765936        0    765936   0% /run/user/0
>> charybdefs      31443968 29491820   1952148  94% /var/lib/scylla
>>
>> scylla.log <https://github.com/scylladb/scylla/files/1473369/scylla.log>
>>
>> @raphaelsc <https://github.com/raphaelsc> @benoit-canet
>> <https://github.com/benoit-canet>
>>
>
> probably a integrity checker issue because the error doesn't happen with
> it disabled. EBADF could be due to file opened without READ flag enabled
> but I checked that's not the case. However, failure comes when reading
> after write. Awkward, no? :-) i'll investigate it more.
>

worth adding that this issue cannot be reproduced without fuse, which makes
me think some weakness of checker was exposed by it. don't know what
exactly yet

**Comment by amoskong** [comment] 2017-11-15 05:00
The problem only exists when I enable `enable_sstable_data_integrity_check: true`.

**Comment by raphaelsc** [comment] 2017-11-15 05:14
On Wed, Nov 15, 2017 at 3:01 AM, Amos Kong <notifications@github.com> wrote:

> The problem only exists when I enable enable_sstable_data_integrity_check:
> true.
>
yes, but not without fuse. problem turns out to be in fuse that doesn't
forward file flags in file creation.

**Comment by raphaelsc** [comment] 2017-11-15 05:50
amos, apply '[PATCH charybdefs 0/3] probability-based silent data
corruption' to charybdefs and be happy :-)

On Wed, Nov 15, 2017 at 3:14 AM, Raphael S. Carvalho <raphaelsc@scylladb.com

**Comment by amoskong** [comment] 2017-11-15 09:00
I never touched a bad fd error after applied your patches.

But I touched integrity check error during c-s writing and scylla stop, I didn't enable any faults conditions.

```
ERROR 2017-11-15 08:48:17,934 [shard 0] sstable - integrity check failed for /var/lib/scylla/data/keyspace1/standard1-116d2de0c9de11e78eb1000000000001/keyspace1-standard1-ka
-24-Data.db, stage: after write finished, write: 131072 bytes to offset 43646976, reason: only 49152 bytes were written.
ERROR 2017-11-15 08:48:17,936 [shard 1] sstable - integrity check failed for /var/lib/scylla/data/keyspace1/standard1-116d2de0c9de11e78eb1000000000001/keyspace1-standard1-ka-25-Data.db, stage: after write finished, write: 131072 bytes to offset 54657024, reason: only 20480 bytes were written.
WARN  2017-11-15 08:48:17,961 [shard 0] storage_service - Shutting down communications due to I/O errors until operator intervention
```

**Comment by raphaelsc** [comment] 2017-11-15 09:40
On Wed, Nov 15, 2017 at 7:00 AM, Amos Kong <notifications@github.com> wrote:

> I never touched a bad fd error after applied your patches.
>
> But I touched integrity check error during c-s writing and scylla stop, I
> didn't enable any faults conditions.
>
> ERROR 2017-11-15 08:48:17,934 [shard 0] sstable - integrity check failed for /var/lib/scylla/data/keyspace1/standard1-116d2de0c9de11e78eb1000000000001/keyspace1-standard1-ka
> -24-Data.db, stage: after write finished, write: 131072 bytes to offset 43646976, reason: only 49152 bytes were written.
> ERROR 2017-11-15 08:48:17,936 [shard 1] sstable - integrity check failed for /var/lib/scylla/data/keyspace1/standard1-116d2de0c9de11e78eb1000000000001/keyspace1-standard1-ka-25-Data.db, stage: after write finished, write: 131072 bytes to offset 54657024, reason: only 20480 bytes were written.
> WARN  2017-11-15 08:48:17,961 [shard 0] storage_service - Shutting down communications due to I/O errors until operator intervention
>
>
That's awkward.

Maybe, "It is not an error if this number is smaller than  the  number  of
 bytes
       requested; this may happen for example because the disk device was
filled."

I think the specific problem here (with charybde fs) is that write is
carried using pwrite(), so if we just ignore return value lower than size
(bytes to write), it will result in behavior Amos saw.

@avikivity: could that happen whatsoever with io_submit()? That could kind
of explain some of the "corruption" problem we're facing. Many of the
corruption-related problems we faced were reproduced when disk was (close
to) filled, IIRC. I see that we completely ignore return value of
write_dma() in file_data_sink_impl, so if turns out my theory is correct,
we may be silently leaving unwritten holes in files.

**Comment by amoskong** [comment] 2017-11-15 12:41
Another integrity check error in real disk ENOSPC condition:

```
WARN  2017-11-15 10:18:49,548 [shard 0] storage_service - Shutting down communications due to I/O errors until operator intervention
INFO  2017-11-15 10:18:49,548 [shard 0] storage_service - Stop transport: starts
INFO  2017-11-15 10:18:49,548 [shard 0] gossip - My status = NORMAL
INFO  2017-11-15 10:18:49,548 [shard 0] gossip - Announcing shutdown
ERROR 2017-11-15 10:18:49,579 [shard 0] sstable - components_writer failed to close file: storage_io_error (Storage I/O error: 28: No space left on device)
INFO  2017-11-15 10:18:49,580 [shard 0] storage_service - Node 127.0.0.1 state jump to normal
ERROR 2017-11-15 10:18:49,581 [shard 0] compaction_manager - compaction failed due to storage io error: Storage I/O error: 28: No space left on device
INFO  2017-11-15 10:18:49,581 [shard 0] compaction_manager - Asked to stop
INFO  2017-11-15 10:18:49,583 [shard 0] compaction_manager - Stopped
ERROR 2017-11-15 10:18:49,584 [shard 1] sstable - integrity check failed for /var/lib/scylla/data/keyspace1/standard1-4755cb10c9e811e7ac9e000000000001/keyspace1-standard1-ka-67-Data.db, stage: after write finished, write: 131072 bytes to offset 27262976, reason: only 4096 bytes were written.
ERROR 2017-11-15 10:18:49,585 [shard 1] commitlog - Failed to persist commits to disk for CommitLog-1-18014398533226014.log: storage_io_error (Storage I/O error: 28: No space left on device)
ERROR 2017-11-15 10:18:49,587 [shard 1] commitlog - Failed to flush commits to disk: storage_io_error (Storage I/O error: 28: No space left on device)
ERROR 2017-11-15 10:18:49,595 [shard 0] commitlog - Failed to persist commits to disk for CommitLog-1-23744028.log: storage_io_error (Storage I/O error: 28: No space left on device)
ERROR 2017-11-15 10:18:49,596 [shard 0] commitlog - Failed to flush commits to disk: storage_io_error (Storage I/O error: 28: No space left on device)
```

**Comment by nyh** [comment] 2017-11-15 12:46
@raphaelsc this really seems like it can cause the "blocks of zeros" problem we saw in the past.
By the way, this problem should probably be moved to the Seastar bug tracker?

do_put() in core/fstream.cc indeed calls dma_write() and gets a "size" from it, but doesn't verify that buf_size==size. It probably should!

The question is, though, what *should* we do when this happens. Are we supposed to retry the rest of the write? Or fail (through exception) immediately? I am guessing that despite the comment in core/file.hh saying that "A short write may happen due to an I/O error.", maybe there are other reasons for a short write? @vladzcloudius I vaguely remember that you handled this case in the past, do you remember anything about it?

**Comment by vladzcloudius** [comment] 2017-11-15 14:20
@nyh I don't remember it clearly myself :) but from reading the man pages it seems that short write may be resulted by both HW backend errors (bad disk, bad FS, etc.) and by logical errors like an attempt to write beyond the file boundary when it wasn't opened with O_APPEND.

**Comment by raphaelsc** [comment] 2017-11-16 03:45
On Wed, Nov 15, 2017 at 10:46 AM, nyh <notifications@github.com> wrote:

> @raphaelsc <https://github.com/raphaelsc> this really seems like it can
> cause the "blocks of zeros" problem we saw in the past.
> By the way, this problem should probably be moved to the Seastar bug
> tracker?
>
I think so.


> do_put() in core/fstream.cc indeed calls dma_write() and gets a "size"
> from it, but doesn't verify that buf_size==size. It probably should!
>
Exactly.


> The question is, though, what *should* we do when this happens. Are we
> supposed to retry the rest of the write? Or fail (through exception)
> immediately? I am guessing that despite the comment in core/file.hh saying
> that "A short write may happen due to an I/O error.", maybe there are other
> reasons for a short write? @vladzcloudius
> <https://github.com/vladzcloudius> I vaguely remember that you handled
> this case in the past, do you remember anything about it?
>
Possibly retry if this holds: "On success, the number of bytes written is
returned (zero indicates nothing was written).  It is not an error if  this
 number  is  smaller
       than the number of bytes requested; this may happen for example
because the disk device was filled.  See also NOTES."

But triggering an exception is also good because we won`t generate
corrupted tables and the user would be notified immediately about disk/fs
issues that led write to not work properly. Apparently less bytes will be
written than requested if disk is filled or close to. Exception trigger is
a good course of action for both, maybe one exception that will not lead
system to shutdown, so memtable flush can be retried, and we'll still have
some resilience there.

**Comment by nyh** [comment] 2017-11-16 08:45
On Thu, Nov 16, 2017 at 5:45 AM, Raphael Carvalho <notifications@github.com>
wrote:

> On Wed, Nov 15, 2017 at 10:46 AM, nyh <notifications@github.com> wrote:
>
> > @raphaelsc <https://github.com/raphaelsc> this really seems like it can
> > cause the "blocks of zeros" problem we saw in the past.
> > By the way, this problem should probably be moved to the Seastar bug
> > tracker?
> >
> I think so.
>
>
> > do_put() in core/fstream.cc indeed calls dma_write() and gets a "size"
> > from it, but doesn't verify that buf_size==size. It probably should!
> >
> Exactly.
>
>
> > The question is, though, what *should* we do when this happens. Are we
> > supposed to retry the rest of the write? Or fail (through exception)
> > immediately? I am guessing that despite the comment in core/file.hh
> saying
> > that "A short write may happen due to an I/O error.", maybe there are
> other
> > reasons for a short write? @vladzcloudius
> > <https://github.com/vladzcloudius> I vaguely remember that you handled
> > this case in the past, do you remember anything about it?
> >
> Possibly retry if this holds: "On success, the number of bytes written is
> returned (zero indicates nothing was written). It is not an error if this
> number is smaller
> than the number of bytes requested; this may happen for example
> because the disk device was filled. See also NOTES."
>

Where is this text written?
If indeed the only possible reasons for failure are long-term problems like
the
disk running out of space, there is not much point of retrying - we may have
to retry an unbounded number of times before it finally succeeds - I think
it
makes more sense to throw an exception immediately.

That being said, it's important to try to understand if this problem cannot
happen spontaneously without any real failure in the system. e.g., maybe
(and I'm just making this up) the filesystem knew it would need to block
the iosubmit
if it did the full write, so it prefered to do a partial write without
blocking. The reason I'm
asking this is that I think (but am not sure I'm remember correctly) that we
once saw this "block of zeros" bug in a system where we did not (we think)
run out of space. (but maybe I'm misremembering).

**Comment by slivne** [comment] 2017-11-20 15:16
created - scylladb/seastar#360 

@raphaelsc - please fix this

**Comment by raphaelsc** [comment] 2017-11-20 20:34
@slivne thanks for creating the issue.

I think yes, reproduced on real disk with integrity checker enabled, look at what @amoskong said: "Another integrity check error in real disk ENOSPC condition:"

**Comment by slivne** [comment] 2018-01-23 12:31
@amoskong  scylladb/seastar#360 was fixed - so we can retest....

**Comment by raphaelsc** [comment] 2018-01-23 13:29
On Tue, Jan 23, 2018 at 10:31 AM, Shlomi Livne <notifications@github.com>
wrote:

> @amoskong <https://github.com/amoskong> scylladb/seastar#360
> <https://github.com/scylladb/seastar/issues/360> was fixed - so we can
> retest....
>

I also fixed a related bug in charybdefs itself, but changes weren't
applied yet.

**Comment by amoskong** [comment] 2018-01-29 09:44
On Tue, Jan 23, 2018 at 9:29 PM, Raphael Carvalho <notifications@github.com>
wrote:

> On Tue, Jan 23, 2018 at 10:31 AM, Shlomi Livne <notifications@github.com>
> wrote:
>
> > @amoskong <https://github.com/amoskong> scylladb/seastar#360
> > <https://github.com/scylladb/seastar/issues/360> was fixed - so we can
> > retest....
> >
>
> I also fixed a related bug in charybdefs itself, but changes weren't
> applied yet.
>


Do you mean those patches?


commit f473a9c4a857b39d71aa2fd32d2031d5460f18f1

Author: Raphael S. Carvalho <raphaelsc@scylladb.com>

Date:   Wed Nov 15 03:47:55 2017 -0200


    add silent data corruption recipe to cookbook



    Signed-off-by: Raphael S. Carvalho <raphaelsc@scylladb.com>


commit 85f32e0b519a2bf85c4c1ff3e70521f45c31e350

Author: Raphael S. Carvalho <raphaelsc@scylladb.com>

Date:   Wed Nov 15 03:47:54 2017 -0200


    forward file flags to avoid EBADF on reads for newly created files



    Signed-off-by: Raphael S. Carvalho <raphaelsc@scylladb.com>


commit 6a20390a076d6dd1e41af2ec3b3655171f52e22f

Author: Raphael S. Carvalho <raphaelsc@scylladb.com>

Date:   Wed Nov 15 03:47:53 2017 -0200


    add probability-based silent data corruption option for write calls



    Signed-off-by: Raphael S. Carvalho <raphaelsc@scylladb.com>

**Comment by amoskong** [comment] 2018-01-29 10:19
I didn't reproduced this issue with 666.development-0.20180123.bf4a90fa5
I used both `current charybdefs master` and `current charybdefs master with 3 fixes` from @raphaelsc

**Comment by glommer** [comment] 2018-04-28 16:24
@amoskong or @duarten please close this.

**Closed** 2018-04-28 16:48 UTC
Labels: test
