### ISSUE TITLE
Not implemented using fromJson with comlex UDT column

### ISSUE THREAD

**Issue by juliayakovlev** [scylladb/scylla#3662] opened 2018-08-07 05:17 UTC
*Installation details*
Scylla version (or git commit hash): master, last commit 6b179b0183172518a23cb62144ea5da1217aca28

Scenario:
1. create UDT: CREATE TYPE t_person_name (first text, middle text, last text)
2. create table: CREATE TABLE person_info (name frozen<t_person_name> PRIMARY KEY, info text)
3. insert: INSERT INTO person_info (name, info) VALUES ({first: 'test', middle: 'guy', last: 'jones'}, 'enjoys bacon')
4. select: SELECT * FROM person_info WHERE name = fromJson('{"first":"test", "middle":"guy", "last":"jones"}')
It fails with error:
_virtual bytes tuple_type_impl::from_json_object(const Json::Value&, cql_serialization_format) const not implemented_

In Cassandra it works

Received same problem when defined the column type as "frozen<tuple<text, int, uuid, boolean>>" and tried to read from this column using "fromJson"

**Comment by juliayakovlev** [comment] 2018-08-07 05:34
Example when INSERT:
1. CREATE TYPE t_kitchen_sink (item1 ascii, item2 blob, item3 inet, item4 text, item5 timestamp, item6 timeuuid, item7 uuid, item8 varchar, item9 bigint, item10 decimal, item11 double, item12 float, item13 int, item14 varint, item15 boolean, item16 list<int> )

2. CREATE TABLE complex_types (key1 text PRIMARY KEY, named_sinks map<text, frozen<t_kitchen_sink>> )

3. INSERT INTO complex_types (key1,  named_sinks) values (fromJson('"row2"'), fromJson('{"namedsink1":{"item1": "asdf", "item2": "0x0012", "item3": "127.0.0.2", "item4": "whatev1", "item5": "2012-02-03 04:05+0000", "item6": "d05a10c8-7c12-11e4-949d-b4b6763e9d6f", "item7": "f90b04b1-f9ad-4ffa-b869-a7d894ce6003", "item8": "tyru", "item9": -9223372036854771111, "item10": 4321.45678, "item11": 10012312.1222, "item12": 40012312.5252, "item13": -1147483648, "item14": 2047483648, "item15": true, "item16": [1,1,2,3,5,8]},"namedsink2":{"item1": "fdsa", "item2": "0x0013", "item3": "127.0.0.3", "item4": "whatev2", "item5": "2013-02-03 04:05+0000", "item6": "d8ac38c8-7c12-11e4-8955-b4b6763e9d6f", "item7": "e3e84f21-f28c-4e0f-80e0-068a640ae53a", "item8": "uytr", "item9": -3333372036854775808, "item10": 1234.12321, "item11": 20012312.1222, "item12": 50012312.5252, "item13": -1547483648, "item14": 1947483648, "item15": false, "item16": [3,6,9,12,15]},"namedsink3":{"item1": "zxcv", "item2": "0x0014", "item3": "127.0.0.4", "item4": "whatev3", "item5": "2014-02-03 04:05+0000", "item6": "de30838a-7c12-11e4-a907-b4b6763e9d6f", "item7": "f9381f0e-9467-4d4c-9315-eb9f0232487b", "item8": "fghj", "item9": -2239372036854775808, "item10": 5555.55555, "item11": 30012312.1222, "item12": 60012312.5252, "item13": 2147483647, "item14": 1347483648, "item15": true, "item16": [0,1,0,1,2,0]}}'))

Error:
_ServerError: virtual bytes tuple_type_impl::from_json_object(const Json::Value&, cql_serialization_format) const not implemented_

**Comment by tzach** [comment] 2018-08-07 06:13
> In Cassandra it's works

Which version of Apache Cassandra?

**Comment by juliayakovlev** [comment] 2018-08-07 06:14
3.2.1

**Comment by avikivity** [comment] 2019-03-20 10:43
Closing as duplicate of #3708

**Closed by avikivity** 2019-03-20 10:43 UTC
Labels: bug, cassandra 3.x compatibility
