### ISSUE TITLE
nodetool scrub command failed  std::runtime_error (Keyspace ks_truncate_large_partition: snapshot pre-scrub-1616336377287 already exists

### ISSUE THREAD

**Issue by aleksbykov** [scylladb/scylla#8341] opened 2021-03-22 11:59 UTC
*Installation details*
Scylla version (or git commit hash): Scylla version 4.4.0-0.20210319.ff585e083 with build-id 1b90d793cab42650c023c0d33238e034b4a023ac
Cluster size: 6
OS (RHEL/CentOS/Ubuntu/AWS AMI): ami-0965bd7b71edd8c6d(eu-north-1) 

During job: [longevity-alternator-3h-test](https://jenkins.scylladb.com/view/scylla-4.4/job/scylla-4.4/job/longevity/job/longevity-alternator-3h-test/28) nemesis CorruptThenScrub(nemesis executed the nodetool scrub --skip-corrupted <ks> for each keyspace) failed with next error:
```
< t:2021-03-21 14:19:30,950 f:remote_base.py  l:520  c:RemoteCmdRunner      p:DEBUG > Running command "/usr/bin/nodetool  scrub --skip-corrupted ks_truncate_large_partition"...
< t:2021-03-21 14:19:31,058 f:base.py         l:220  c:RemoteCmdRunner      p:DEBUG > Using /etc/scylla/scylla.yaml as the config file
< t:2021-03-21 14:19:36,680 f:base.py         l:220  c:RemoteCmdRunner      p:DEBUG > WARN  14:19:36,658 Only 12.883GiB free across all data volumes. Consider adding more capacity to your cluster or removing obsolete snapshots
< t:2021-03-21 14:19:36,913 f:base.py         l:220  c:RemoteCmdRunner      p:DEBUG > WARN  14:19:36,909 Unable to read cassandra-rackdc.properties
< t:2021-03-21 14:19:37,386 f:base.py         l:220  c:RemoteCmdRunner      p:DEBUG > error: Scylla API server HTTP GET to URL '/storage_service/keyspace_scrub/ks_truncate_large_partition' failed: std::runtime_error (Keyspace ks_truncate_large_partition: snapshot pre-scrub-1616336377287 already exists.)
< t:2021-03-21 14:19:37,388 f:base.py         l:220  c:RemoteCmdRunner      p:DEBUG > -- StackTrace --
< t:2021-03-21 14:19:37,392 f:base.py         l:220  c:RemoteCmdRunner      p:DEBUG > java.lang.IllegalStateException: Scylla API server HTTP GET to URL '/storage_service/keyspace_scrub/ks_truncate_large_partition' failed: std::runtime_error (Keyspace ks_truncate_large_partition: snapshot pre-scrub-1616336377287 already exists.)
< t:2021-03-21 14:19:37,392 f:base.py         l:220  c:RemoteCmdRunner      p:DEBUG >   at com.scylladb.jmx.api.APIClient.getException(APIClient.java:140)
< t:2021-03-21 14:19:37,392 f:base.py         l:220  c:RemoteCmdRunner      p:DEBUG >   at com.scylladb.jmx.api.APIClient.getRawValue(APIClient.java:187)
< t:2021-03-21 14:19:37,392 f:base.py         l:220  c:RemoteCmdRunner      p:DEBUG >   at com.scylladb.jmx.api.APIClient.getRawValue(APIClient.java:201)
< t:2021-03-21 14:19:37,392 f:base.py         l:220  c:RemoteCmdRunner      p:DEBUG >   at com.scylladb.jmx.api.APIClient.getIntValue(APIClient.java:238)
< t:2021-03-21 14:19:37,392 f:base.py         l:220  c:RemoteCmdRunner      p:DEBUG >   at org.apache.cassandra.service.StorageService.scrub(StorageService.java:1750)
< t:2021-03-21 14:19:37,392 f:base.py         l:220  c:RemoteCmdRunner      p:DEBUG >   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
< t:2021-03-21 14:19:37,392 f:base.py         l:220  c:RemoteCmdRunner      p:DEBUG >   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
< t:2021-03-21 14:19:37,392 f:base.py         l:220  c:RemoteCmdRunner      p:DEBUG >   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
< t:2021-03-21 14:19:37,392 f:base.py         l:220  c:RemoteCmdRunner      p:DEBUG >   at java.lang.reflect.Method.invoke(Method.java:498)
< t:2021-03-21 14:19:37,392 f:base.py         l:220  c:RemoteCmdRunner      p:DEBUG >   at sun.reflect.misc.Trampoline.invoke(MethodUtil.java:72)
< t:2021-03-21 14:19:37,392 f:base.py         l:220  c:RemoteCmdRunner      p:DEBUG >   at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
< t:2021-03-21 14:19:37,392 f:base.py         l:220  c:RemoteCmdRunner      p:DEBUG >   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
< t:2021-03-21 14:19:37,392 f:base.py         l:220  c:RemoteCmdRunner      p:DEBUG >   at java.lang.reflect.Method.invoke(Method.java:498)
< t:2021-03-21 14:19:37,392 f:base.py         l:220  c:RemoteCmdRunner      p:DEBUG >   at sun.reflect.misc.MethodUtil.invoke(MethodUtil.java:276)
< t:2021-03-21 14:19:37,392 f:base.py         l:220  c:RemoteCmdRunner      p:DEBUG >   at com.sun.jmx.mbeanserver.StandardMBeanIntrospector.invokeM2(StandardMBeanIntrospector.java:112)
< t:2021-03-21 14:19:37,392 f:base.py         l:220  c:RemoteCmdRunner      p:DEBUG >   at com.sun.jmx.mbeanserver.StandardMBeanIntrospector.invokeM2(StandardMBeanIntrospector.java:46)
< t:2021-03-21 14:19:37,392 f:base.py         l:220  c:RemoteCmdRunner      p:DEBUG >   at com.sun.jmx.mbeanserver.MBeanIntrospector.invokeM(MBeanIntrospector.java:237)
< t:2021-03-21 14:19:37,392 f:base.py         l:220  c:RemoteCmdRunner      p:DEBUG >   at com.sun.jmx.mbeanserver.PerInterface.invoke(PerInterface.java:138)
< t:2021-03-21 14:19:37,393 f:base.py         l:220  c:RemoteCmdRunner      p:DEBUG >   at com.sun.jmx.mbeanserver.MBeanSupport.invoke(MBeanSupport.java:252)
< t:2021-03-21 14:19:37,393 f:base.py         l:220  c:RemoteCmdRunner      p:DEBUG >   at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.invoke(DefaultMBeanServerInterceptor.java:819)
< t:2021-03-21 14:19:37,393 f:base.py         l:220  c:RemoteCmdRunner      p:DEBUG >   at com.sun.jmx.mbeanserver.JmxMBeanServer.invoke(JmxMBeanServer.java:801)
< t:2021-03-21 14:19:37,393 f:base.py         l:220  c:RemoteCmdRunner      p:DEBUG >   at com.scylladb.jmx.utils.APIMBeanServer.invoke(APIMBeanServer.java:188)
< t:2021-03-21 14:19:37,393 f:base.py         l:220  c:RemoteCmdRunner      p:DEBUG >   at javax.management.remote.rmi.RMIConnectionImpl.doOperation(RMIConnectionImpl.java:1468)
< t:2021-03-21 14:19:37,393 f:base.py         l:220  c:RemoteCmdRunner      p:DEBUG >   at javax.management.remote.rmi.RMIConnectionImpl.access$300(RMIConnectionImpl.java:76)
< t:2021-03-21 14:19:37,393 f:base.py         l:220  c:RemoteCmdRunner      p:DEBUG >   at javax.management.remote.rmi.RMIConnectionImpl$PrivilegedOperation.run(RMIConnectionImpl.java:1309)
< t:2021-03-21 14:19:37,393 f:base.py         l:220  c:RemoteCmdRunner      p:DEBUG >   at javax.management.remote.rmi.RMIConnectionImpl.doPrivilegedOperation(RMIConnectionImpl.java:1401)
< t:2021-03-21 14:19:37,393 f:base.py         l:220  c:RemoteCmdRunner      p:DEBUG >   at javax.management.remote.rmi.RMIConnectionImpl.invoke(RMIConnectionImpl.java:829)
< t:2021-03-21 14:19:37,393 f:base.py         l:220  c:RemoteCmdRunner      p:DEBUG >   at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
< t:2021-03-21 14:19:37,393 f:base.py         l:220  c:RemoteCmdRunner      p:DEBUG >   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
< t:2021-03-21 14:19:37,393 f:base.py         l:220  c:RemoteCmdRunner      p:DEBUG >   at java.lang.reflect.Method.invoke(Method.java:498)
< t:2021-03-21 14:19:37,393 f:base.py         l:220  c:RemoteCmdRunner      p:DEBUG >   at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:357)
< t:2021-03-21 14:19:37,393 f:base.py         l:220  c:RemoteCmdRunner      p:DEBUG >   at sun.rmi.transport.Transport$1.run(Transport.java:200)
< t:2021-03-21 14:19:37,393 f:base.py         l:220  c:RemoteCmdRunner      p:DEBUG >   at sun.rmi.transport.Transport$1.run(Transport.java:197)
< t:2021-03-21 14:19:37,393 f:base.py         l:220  c:RemoteCmdRunner      p:DEBUG >   at java.security.AccessController.doPrivileged(Native Method)
< t:2021-03-21 14:19:37,393 f:base.py         l:220  c:RemoteCmdRunner      p:DEBUG >   at sun.rmi.transport.Transport.serviceCall(Transport.java:196)
< t:2021-03-21 14:19:37,393 f:base.py         l:220  c:RemoteCmdRunner      p:DEBUG >   at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:573)
< t:2021-03-21 14:19:37,393 f:base.py         l:220  c:RemoteCmdRunner      p:DEBUG >   at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:834)
< t:2021-03-21 14:19:37,393 f:base.py         l:220  c:RemoteCmdRunner      p:DEBUG >   at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:688)
< t:2021-03-21 14:19:37,393 f:base.py         l:220  c:RemoteCmdRunner      p:DEBUG >   at java.security.AccessController.doPrivileged(Native Method)
< t:2021-03-21 14:19:37,393 f:base.py         l:220  c:RemoteCmdRunner      p:DEBUG >   at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:687)
< t:2021-03-21 14:19:37,394 f:base.py         l:220  c:RemoteCmdRunner      p:DEBUG >   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
< t:2021-03-21 14:19:37,394 f:base.py         l:220  c:RemoteCmdRunner      p:DEBUG >   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
< t:2021-03-21 14:19:37,394 f:base.py         l:220  c:RemoteCmdRunner      p:DEBUG >   at java.lang.Thread.run(Thread.java:748)
< t:2021-03-21 14:19:37,394 f:base.py         l:220  c:RemoteCmdRunner      p:DEBUG > 
```

db logs: https://cloudius-jenkins-test.s3.amazonaws.com/60c039cf-6168-424f-b2a1-624c03212ca4/20210321_161146/db-cluster-60c039cf.zip

**Comment by slivne** [comment] 2021-03-22 12:14
duplicate of https://github.com/scylladb/scylla/issues/8212 ?

**Comment by elcallio** [comment] 2021-03-22 12:15
I think so. Afaict, 4.4 does not have 9df8900a985cdbe415e1cb5dc7e752d4008e4ca3

**Comment by aleksbykov** [comment] 2021-03-22 15:29
> duplicate of #8212 ?

Yes, the same issue

**Closed** 2021-04-06 12:23 UTC
