### ISSUE TITLE
"cdc" column in scylla_tables is added, even if --experimental cdc is not set

### ISSUE THREAD

**Issue by piodul** [scylladb/scylla#5894] opened 2020-02-24 17:06 UTC
A column named "cdc" is supposed to be added to `system_schema.scylla_tables` if and only if CDC experimental feature is enabled. Currently, this column is added even if CDC experimental feature is not enabled.

**Comment by haaawk** [comment] 2020-02-24 17:10
@slivne and @avikivity if this bug is confirmed then we absolutely need to backport the fix. We also have to check 3.2 because initial tests performed by @piodul showed that for 3.2 it's the problem as well.

**Comment by haaawk** [comment] 2020-02-24 17:34
Well. Maybe it's not such a big problem.

**Comment by slivne** [comment] 2020-03-05 10:16
@avikivity whats your view ?

**Comment by haaawk** [comment] 2020-03-05 10:22
I don't think we can do anything about it probably this issue should be closed.

**Comment by nyh** [comment] 2020-03-08 20:00
@haaawk,

We recently got a patch which deprecates that "cdc column" in favor of a "schema extension". Is this problem still relevant there, or not?

I'm afraid that this issue (or a similar one regarding the schema extension) might be serious in the following sense: Imagine that somebody is using 3.1, 3.2, etc., upgrading version by version, never even trying CDC because he's afraid of experimental stuff. Eventually in version 5.0, when CDC is super-stable, this user decides to use CDC. And it fails bizarrely, because his database has some antique "cdc" column (or schema extension) added back in Scylla 3.1 without enabling CDC.

**Comment by haaawk** [comment] 2020-03-08 20:22
We deprecated cdc column and stopped using it but we didn't remove it so upgrade is safe and shouldn't fail because old cluster has cdc column.

**Comment by slivne** [comment] 2020-03-11 09:31
@haaawk  can I close this

**Closed** 2020-03-11 09:35 UTC
Labels: CDC, bug
