### ISSUE TITLE
Yum dependency issues

### ISSUE THREAD

**Issue by arita37** [scylladb/scylla#6685] opened 2020-06-21 06:07 UTC
When installing 2019.1 ENT, current issues found :

some python packages since YUM deprecated
python36 , psutil in their latest repository.

—> We have to find the right version, right URL,
donwload and and install manually.

Save the dependency package inside scylla,
Reduces external deprecation issues over the years and more reproductible install...

- [] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash): 2019.1 ENt
Cluster size:
OS (RHEL/CentOS/Ubuntu/AWS AMI): CentOS

**Comment by avikivity** [comment] 2020-06-21 14:00
Can you explain? "yum install python36" works in centos 7 (but installs python3).

**Comment by slivne** [comment] 2020-07-02 08:03
@arita37 - hi can you share more details - so we can try and help

**Comment by arita37** [comment] 2020-07-02 09:23
When installing
scylladb-2019.1.repo

we have to installed MANUALLY find and install those ones because YUM removed them in the latest ones....


rpm -i https://dl.fedoraproject.org/pub/epel/7/x86_64/Packages/p/python36-psutil-5.6.7-1.el7.x86_64.rpm
rpm -i https://dl.fedoraproject.org/pub/epel/7/x86_64/Packages/p/python36-PyYAML-3.13-1.el7.x86_64.rpm
rpm -i https://dl.fedoraproject.org/pub/epel/7/x86_64/Packages/p/python3-pyudev-0.21.0-2.el7.noarch.rpm
rpm -i https://dl.fedoraproject.org/pub/epel/7/x86_64/Packages/p/python36-six-1.14.0-2.el7.noarch.rpm

**Comment by avikivity** [comment] 2020-07-09 11:09
You have to install the epel-release package first. Afterwards, it works.

```
# yum install python36-psutil python36-PyYAML python3-pyudev python36-six
Loaded plugins: fastestmirror, ovl
Loading mirror speeds from cached hostfile
 * base: mirrors.tripadvisor.com
 * epel: mirror.nonstop.co.il
 * extras: mirrors.rit.edu
 * updates: mirror.siena.edu
Resolving Dependencies
--> Running transaction check
---> Package python3-pyudev.noarch 0:0.21.0-2.el7 will be installed
--> Processing Dependency: python(abi) = 3.6 for package: python3-pyudev-0.21.0-2.el7.noarch
---> Package python36-PyYAML.x86_64 0:3.13-1.el7 will be installed
--> Processing Dependency: libpython3.6m.so.1.0()(64bit) for package: python36-PyYAML-3.13-1.el7.x86_64
--> Processing Dependency: libyaml-0.so.2()(64bit) for package: python36-PyYAML-3.13-1.el7.x86_64
---> Package python36-psutil.x86_64 0:5.6.7-1.el7 will be installed
---> Package python36-six.noarch 0:1.14.0-2.el7 will be installed
--> Running transaction check
---> Package libyaml.x86_64 0:0.1.4-11.el7_0 will be installed
---> Package python3.x86_64 0:3.6.8-13.el7 will be installed
--> Processing Dependency: python3-setuptools for package: python3-3.6.8-13.el7.x86_64
--> Processing Dependency: python3-pip for package: python3-3.6.8-13.el7.x86_64
---> Package python3-libs.x86_64 0:3.6.8-13.el7 will be installed
--> Processing Dependency: libtirpc.so.1()(64bit) for package: python3-libs-3.6.8-13.el7.x86_64
--> Running transaction check
---> Package libtirpc.x86_64 0:0.2.4-0.16.el7 will be installed
---> Package python3-pip.noarch 0:9.0.3-7.el7_7 will be installed
---> Package python3-setuptools.noarch 0:39.2.0-10.el7 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

=======================================================================================================================================================================================================================================================================
 Package                                                               Arch                                                      Version                                                              Repository                                                  Size
=======================================================================================================================================================================================================================================================================
Installing:
 python3-pyudev                                                        noarch                                                    0.21.0-2.el7                                                         epel                                                        77 k
 python36-PyYAML                                                       x86_64                                                    3.13-1.el7                                                           epel                                                       149 k
 python36-psutil                                                       x86_64                                                    5.6.7-1.el7                                                          epel                                                       395 k
 python36-six                                                          noarch                                                    1.14.0-2.el7                                                         epel                                                        34 k
Installing for dependencies:
 libtirpc                                                              x86_64                                                    0.2.4-0.16.el7                                                       base                                                        89 k
 libyaml                                                               x86_64                                                    0.1.4-11.el7_0                                                       base                                                        55 k
 python3                                                               x86_64                                                    3.6.8-13.el7                                                         base                                                        69 k
 python3-libs                                                          x86_64                                                    3.6.8-13.el7                                                         base                                                       7.0 M
 python3-pip                                                           noarch                                                    9.0.3-7.el7_7                                                        updates                                                    1.8 M
 python3-setuptools                                                    noarch                                                    39.2.0-10.el7                                                        base                                                       629 k

Transaction Summary
=======================================================================================================================================================================================================================================================================
Install  4 Packages (+6 Dependent packages)
```

**Comment by avikivity** [comment] 2020-07-09 11:09
Closing as not a bug (assuming we document that epel-release must be installed).

**Closed by avikivity** 2020-07-09 11:09 UTC
Labels: User Request, onboarding
