### ISSUE TITLE
Does Scylladb support Index?

### ISSUE THREAD

**Issue by zhiguoxu** [scylladb/scylla#2926] opened 2017-11-02 06:28 UTC
*Installation details*
Scylla version (or git commit hash): 2.0
Cluster size: 3
OS (RHEL/CentOS/Ubuntu/AWS AMI): centos

Does Scylladb support Index?
When I created Index like the document says, I got error return: InvalidRequest: Error from server: code=2200 [Invalid query] message="Index support is not enabled"

**Comment by avikivity** [comment] 2017-11-02 07:52
Duplicate of #401.

**Closed by avikivity** 2017-11-02 07:52 UTC
