### ISSUE TITLE
multishard queries unbounded memory use

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylla#7434] opened 2020-10-14 11:00 UTC
The attached reproducer creates a partition with logs of tombstones and one row. It then selects the partition, which fails (as expected) with no ill effects but also no exception in the log (why?). It then performs a range scan, which fails while consuming huge amounts of memory.

Run with `--smp 1 -m 1G` for best results (with --smp 2 the allocations can happen on an uused shard, so no ill effects).

[tombstone-prefix.py.gz](https://github.com/scylladb/scylla/files/5377595/tombstone-prefix.py.gz)

**Comment by avikivity** [comment] 2020-10-14 11:01
3451579d81293fb128e2fccbf7131d7456de1b55 + clang patches.

**Comment by denesb** [comment] 2020-10-21 04:29
Mutation queries (used for reconciliation) are also prone to this.

**Comment by denesb** [comment] 2021-02-10 13:29
https://github.com/scylladb/scylla/issues/8061 made me realize that building `query::result` instead of `reconcilable_result` directly would make this go away completely, while solving some other issues. I will take a closer look at how feasible this is. From first look it should be possible, see https://github.com/scylladb/scylla/issues/8061.

**Comment by denesb** [comment] 2021-03-02 10:01
With https://github.com/scylladb/scylla/commit/10364fca6ee41aa1697edfc80e67d08ce6c26137 merged, the problem is now limited to read-repair and is no longer specific to multishard queries, all queries suffer from this.

**Comment by denesb** [comment] 2021-03-05 15:07
I think we should close this as queries do not pose a problem anymore, I opened a new one for the read-repair issue: https://github.com/scylladb/scylla/issues/8223.
The multishard queries are fixed by https://github.com/scylladb/scylla/commit/10364fca6ee41aa1697edfc80e67d08ce6c26137.

**Closed by denesb** 2021-03-05 15:08 UTC
Labels: Eng-3, bad_alloc
