### ISSUE TITLE
node crash with coredump while restarting another node in the cluster (multi keyspace scenario with high load)

### ISSUE THREAD

**Issue by roydahan** [scylladb/scylla#3625] opened 2018-07-23 17:17 UTC
*Installation details*
Scylla version (or git commit hash): 2.3.rc0-0.20180722.a77bb1fe3
Cluster size: 6 nodes, 1000 keyspaces.
OS (RHEL/CentOS/Ubuntu/AWS AMI): AWS AMI (ami-905252ef) 

During a multi-keyspaces test (20 loaders writing concurrently to 1000 keyspaces), stopping scylla service and starting it after a minute on one node (172.16.99.246 in this case, "red" one on the Grafana screenshot) caused a crash with a coredump on a different node (172.16.99.115, "yelow", not seed).

Backtrace:
```
[centos@ip-172-16-99-115 ~]$ addr2line -Cpife /usr/lib/debug/.build-id/51/94d4ebc5cd3ebb0703a6c28cfd081fddeff8e2.debug

?? ??:0
0x00000000006882d2
0x00000000005a339c
0x00000000005a3645
0x00000000005a36f3
/lib64/libpthread.so.0+0x000000000000f6cf
/lib64/libc.so.6+0x0000000000036276
/lib64/libc.so.6+0x0000000000037967
/lib64/libc.so.6+0x000000000002f095
/lib64/libc.so.6+0x000000000002f141
0x00000000014caee5
0x000000000172d772
0x0000000000584756
0x0000000000584911
0x0000000000651ff7
0x00000000006551a5
0x000000000073d00d
/lib64/libpthread.so.0+0x0000000000007e24
/lib64/libc.so.6+0x00000000000febac
seastar::future_state<>::future_state(seastar::future_state<>&&) at /usr/src/debug/scylla-2.3.rc0/seastar/core/future.hh:307
 (inlined by) seastar::future_state<>::operator=(seastar::future_state<>&&) at /usr/src/debug/scylla-2.3.rc0/seastar/core/future.hh:326
 (inlined by) seastar::future<>::future(seastar::future<>&&) at /usr/src/debug/scylla-2.3.rc0/seastar/core/future.hh:806
 (inlined by) apply<seastar::smp_message_queue::async_work_item<Func>::process()::<lambda()> [with Func = seastar::metrics::configure(const boost::program_options::variables_map&)::<lambda()>]::<lambda(auto:28)>, seastar::future<> > at /usr/src/debug/scylla-2.3.rc0/seastar/core/future.hh:1324
 (inlined by) apply<seastar::smp_message_queue::async_work_item<Func>::process()::<lambda()> [with Func = seastar::metrics::configure(const boost::program_options::variables_map&)::<lambda()>]::<lambda(auto:28)>, seastar::future<> > at /usr/src/debug/scylla-2.3.rc0/seastar/core/future.hh:1373
 (inlined by) operator()<seastar::future_state<> > at /usr/src/debug/scylla-2.3.rc0/seastar/core/future.hh:995
 (inlined by) run_and_dispose at /usr/src/debug/scylla-2.3.rc0/seastar/core/future.hh:413
std::_Head_base<0ul, unsigned long, false>::_Head_base<unsigned long>(unsigned long&&) at /opt/scylladb/include/c++/7/tuple:133
 (inlined by) std::_Tuple_impl<0ul, unsigned long>::_Tuple_impl(std::_Tuple_impl<0ul, unsigned long>&&) at /opt/scylladb/include/c++/7/tuple:373
 (inlined by) std::tuple<unsigned long>::tuple(std::tuple<unsigned long>&&) at /opt/scylladb/include/c++/7/tuple:662
 (inlined by) seastar::future_state<unsigned long>::future_state(seastar::future_state<unsigned long>&&) at /usr/src/debug/scylla-2.3.rc0/seastar/core/future.hh:157
 (inlined by) seastar::future_state<unsigned long>::operator=(seastar::future_state<unsigned long>&&) at /usr/src/debug/scylla-2.3.rc0/seastar/core/future.hh:191
 (inlined by) seastar::promise<unsigned long>::abandoned() at /usr/src/debug/scylla-2.3.rc0/seastar/core/future.hh:1258
 (inlined by) seastar::promise<unsigned long>::~promise() at /usr/src/debug/scylla-2.3.rc0/seastar/core/future.hh:458
 (inlined by) seastar::shared_ptr_no_esft<seastar::promise<unsigned long> >::~shared_ptr_no_esft() at /usr/src/debug/scylla-2.3.rc0/seastar/core/shared_ptr.hh:158
 (inlined by) seastar::internal::lw_shared_ptr_accessors_no_esft<seastar::promise<unsigned long> >::dispose(seastar::lw_shared_ptr_counter_base*) at /usr/src/debug/scylla-2.3.rc0/seastar/core/shared_ptr.hh:214
 (inlined by) seastar::lw_shared_ptr<seastar::promise<unsigned long> >::~lw_shared_ptr() at /usr/src/debug/scylla-2.3.rc0/seastar/core/shared_ptr.hh:301
 (inlined by) ~<lambda> at /usr/src/debug/scylla-2.3.rc0/seastar/core/reactor.cc:1642
 (inlined by) operator() at /usr/src/debug/scylla-2.3.rc0/seastar/core/reactor.cc:1645
 (inlined by) _M_invoke at /opt/scylladb/include/c++/7/bits/std_function.h:302
seastar::promise<unsigned long>::abandoned() at /usr/src/debug/scylla-2.3.rc0/seastar/core/future.hh:1259
 (inlined by) seastar::promise<unsigned long>::~promise() at /usr/src/debug/scylla-2.3.rc0/seastar/core/future.hh:458
 (inlined by) seastar::shared_ptr_no_esft<seastar::promise<unsigned long> >::~shared_ptr_no_esft() at /usr/src/debug/scylla-2.3.rc0/seastar/core/shared_ptr.hh:158
 (inlined by) seastar::internal::lw_shared_ptr_accessors_no_esft<seastar::promise<unsigned long> >::dispose(seastar::lw_shared_ptr_counter_base*) at /usr/src/debug/scylla-2.3.rc0/seastar/core/shared_ptr.hh:214
 (inlined by) seastar::lw_shared_ptr<seastar::promise<unsigned long> >::~lw_shared_ptr() at /usr/src/debug/scylla-2.3.rc0/seastar/core/shared_ptr.hh:301
 (inlined by) ~<lambda> at /usr/src/debug/scylla-2.3.rc0/seastar/core/reactor.cc:1642
 (inlined by) ~<lambda> at /usr/src/debug/scylla-2.3.rc0/seastar/core/future.hh:994
 (inlined by) then_wrapped<seastar::append_challenged_posix_file_impl::read_dma(uint64_t, std::vector<iovec>, const seastar::io_priority_class&)::<lambda()> mutable::<lambda(seastar::future<long unsigned int>)> > at /usr/src/debug/scylla-2.3.rc0/seastar/core/future.hh:994
 (inlined by) operator() at /usr/src/debug/scylla-2.3.rc0/seastar/core/reactor.cc:1645
 (inlined by) _M_invoke at /opt/scylladb/include/c++/7/bits/std_function.h:302
std::_Head_base<0ul, unsigned long, false>::_Head_base<unsigned long>(unsigned long&&) at /opt/scylladb/include/c++/7/tuple:133
 (inlined by) std::_Tuple_impl<0ul, unsigned long>::_Tuple_impl(std::_Tuple_impl<0ul, unsigned long>&&) at /opt/scylladb/include/c++/7/tuple:373
 (inlined by) std::tuple<unsigned long>::tuple(std::tuple<unsigned long>&&) at /opt/scylladb/include/c++/7/tuple:662
 (inlined by) seastar::future_state<unsigned long>::future_state(seastar::future_state<unsigned long>&&) at /usr/src/debug/scylla-2.3.rc0/seastar/core/future.hh:157
 (inlined by) seastar::future_state<unsigned long>::operator=(seastar::future_state<unsigned long>&&) at /usr/src/debug/scylla-2.3.rc0/seastar/core/future.hh:191
 (inlined by) seastar::promise<unsigned long>::abandoned() at /usr/src/debug/scylla-2.3.rc0/seastar/core/future.hh:1258
 (inlined by) seastar::promise<unsigned long>::~promise() at /usr/src/debug/scylla-2.3.rc0/seastar/core/future.hh:458
 (inlined by) seastar::shared_ptr_no_esft<seastar::promise<unsigned long> >::~shared_ptr_no_esft() at /usr/src/debug/scylla-2.3.rc0/seastar/core/shared_ptr.hh:158
 (inlined by) seastar::internal::lw_shared_ptr_accessors_no_esft<seastar::promise<unsigned long> >::dispose(seastar::lw_shared_ptr_counter_base*) at /usr/src/debug/scylla-2.3.rc0/seastar/core/shared_ptr.hh:214
 (inlined by) seastar::lw_shared_ptr<seastar::promise<unsigned long> >::~lw_shared_ptr() at /usr/src/debug/scylla-2.3.rc0/seastar/core/shared_ptr.hh:301
 (inlined by) ~<lambda> at /usr/src/debug/scylla-2.3.rc0/seastar/core/reactor.cc:1642
 (inlined by) ~<lambda> at /usr/src/debug/scylla-2.3.rc0/seastar/core/future.hh:994
 (inlined by) then_wrapped<seastar::append_challenged_posix_file_impl::read_dma(uint64_t, std::vector<iovec>, const seastar::io_priority_class&)::<lambda()> mutable::<lambda(seastar::future<long unsigned int>)> > at /usr/src/debug/scylla-2.3.rc0/seastar/core/future.hh:994
 (inlined by) operator() at /usr/src/debug/scylla-2.3.rc0/seastar/core/reactor.cc:1645
 (inlined by) _M_invoke at /opt/scylladb/include/c++/7/bits/std_function.h:302
?? ??:0
?? ??:0
?? ??:0
?? ??:0
?? ??:0
?? ??:0
?? ??:0
seastar::basic_sstring<char, unsigned int, 15u, true>::~basic_sstring() at /usr/src/debug/scylla-2.3.rc0/seastar/core/sstring.hh:256
 (inlined by) seastar::metrics::label_instance::~label_instance() at /usr/src/debug/scylla-2.3.rc0/seastar/core/metrics.hh:144
 (inlined by) seastar::io_queue::priority_class_data::priority_class_data(seastar::basic_sstring<char, unsigned int, 15u, true>, seastar::lw_shared_ptr<seastar::priority_class>, unsigned int) at /usr/src/debug/scylla-2.3.rc0/seastar/core/reactor.cc:1197
seastar::basic_sstring<char, unsigned int, 15u, true>::~basic_sstring() at /usr/src/debug/scylla-2.3.rc0/seastar/core/sstring.hh:257
 (inlined by) seastar::metrics::impl::metric_type::~metric_type() at /usr/src/debug/scylla-2.3.rc0/seastar/core/metrics.hh:308
 (inlined by) seastar::metrics::impl::metric_definition_impl::~metric_definition_impl() at /usr/src/debug/scylla-2.3.rc0/seastar/core/metrics.hh:313
 (inlined by) seastar::io_queue::priority_class_data::priority_class_data(seastar::basic_sstring<char, unsigned int, 15u, true>, seastar::lw_shared_ptr<seastar::priority_class>, unsigned int) at /usr/src/debug/scylla-2.3.rc0/seastar/core/reactor.cc:1198
seastar::memory::small_pool::add_more_objects() at /usr/src/debug/scylla-2.3.rc0/seastar/core/memory.cc:1140
 (inlined by) seastar::memory::small_pool::allocate() at /usr/src/debug/scylla-2.3.rc0/seastar/core/memory.cc:1089
operator delete[](void*, seastar::with_alignment) at /usr/src/debug/scylla-2.3.rc0/seastar/core/memory.cc:720
seastar::promise<>::abandoned() at /usr/src/debug/scylla-2.3.rc0/seastar/core/future.hh:1260
 (inlined by) seastar::promise<>::~promise() at /usr/src/debug/scylla-2.3.rc0/seastar/core/future.hh:458
 (inlined by) ~<lambda> at /usr/src/debug/scylla-2.3.rc0/seastar/core/future-util.hh:85
 (inlined by) ~lambda_task at /usr/src/debug/scylla-2.3.rc0/seastar/core/task.hh:42
```

Coredump:
http://upload.scylladb.com/1efbe70f-b9f2-4a20-b730-e9e469183bd3/

relevant part of log from the crashed node:
```
Jul 23 16:24:20 ip-172-16-99-115.ec2.internal scylla[2570]:  [shard 0] rpc - client 172.16.99.246: fail to connect: Connection refused
Jul 23 16:24:41 ip-172-16-99-115.ec2.internal scylla[2570]:  [shard 0] gossip - InetAddress 172.16.99.246 is now UP, status =
Jul 23 16:24:42 ip-172-16-99-115.ec2.internal scylla[2570]:  [shard 0] gossip - Favor newly added node 172.16.99.246
Jul 23 16:24:42 ip-172-16-99-115.ec2.internal scylla[2570]:  [shard 0] storage_service - Node 172.16.99.246 state jump to normal
Jul 23 16:24:42 ip-172-16-99-115.ec2.internal scylla[2570]: scylla: memtable.cc:422: flush_memory_accounter::~flush_memory_accounter(): Assertion `_mt._flushed_memory <= _mt.occupancy().used_space()' failed.
Jul 23 16:24:42 ip-172-16-99-115.ec2.internal scylla[2570]: Aborting on shard 25.
Jul 23 16:24:42 ip-172-16-99-115.ec2.internal scylla[2570]: Backtrace:
Jul 23 16:24:42 ip-172-16-99-115.ec2.internal scylla[2570]: 0x00000000006882d2
Jul 23 16:24:42 ip-172-16-99-115.ec2.internal scylla[2570]: 0x00000000005a339c
Jul 23 16:24:42 ip-172-16-99-115.ec2.internal scylla[2570]: 0x00000000005a3645
Jul 23 16:24:42 ip-172-16-99-115.ec2.internal scylla[2570]: 0x00000000005a36f3
Jul 23 16:24:42 ip-172-16-99-115.ec2.internal scylla[2570]: /lib64/libpthread.so.0+0x000000000000f6cf
Jul 23 16:24:42 ip-172-16-99-115.ec2.internal scylla[2570]: /lib64/libc.so.6+0x0000000000036276
Jul 23 16:24:42 ip-172-16-99-115.ec2.internal scylla[2570]: /lib64/libc.so.6+0x0000000000037967
Jul 23 16:24:42 ip-172-16-99-115.ec2.internal scylla[2570]: /lib64/libc.so.6+0x000000000002f095
Jul 23 16:24:42 ip-172-16-99-115.ec2.internal scylla[2570]: /lib64/libc.so.6+0x000000000002f141
Jul 23 16:24:42 ip-172-16-99-115.ec2.internal scylla[2570]: 0x00000000014caee5
Jul 23 16:24:42 ip-172-16-99-115.ec2.internal scylla[2570]: 0x000000000172d772
Jul 23 16:24:42 ip-172-16-99-115.ec2.internal scylla[2570]: 0x0000000000584756
Jul 23 16:24:42 ip-172-16-99-115.ec2.internal scylla[2570]: 0x0000000000584911
Jul 23 16:24:42 ip-172-16-99-115.ec2.internal scylla[2570]: 0x0000000000651ff7
Jul 23 16:24:42 ip-172-16-99-115.ec2.internal scylla[2570]: 0x00000000006551a5
Jul 23 16:24:42 ip-172-16-99-115.ec2.internal scylla[2570]: 0x000000000073d00d
Jul 23 16:24:42 ip-172-16-99-115.ec2.internal scylla[2570]: /lib64/libpthread.so.0+0x0000000000007e24
Jul 23 16:24:42 ip-172-16-99-115.ec2.internal scylla[2570]: /lib64/libc.so.6+0x00000000000febac
Jul 23 16:28:08 ip-172-16-99-115.ec2.internal scylla[45085]: Scylla version 2.3.rc0-0.20180722.a77bb1fe3 starting ...
Jul 23 16:28:09 ip-172-16-99-115.ec2.internal scylla[45085]:  [shard 0] snitch_logger - Ec2Snitch using region: us-east, zone: 1d.
Jul 23 16:28:09 ip-172-16-99-115.ec2.internal scylla[45085]:  [shard 0] init - Scylla API server listening on 127.0.0.1:10000 ...
Jul 23 16:28:09 ip-172-16-99-115.ec2.internal scylla[45085]:  [shard 0] database - Row: max_vector_size: 32, internal_count: 5
Jul 23 16:28:09 ip-172-16-99-115.ec2.internal scylla[45085]:  [shard 1] database - Row: max_vector_size: 32, internal_count: 5
Jul 23 16:28:09 ip-172-16-99-115.ec2.internal scylla[45085]:  [shard 2] database - Row: max_vector_size: 32, internal_count: 5
```

Grafana Screenshot:
![screencapture-34-226-218-142-3000-dashboard-db-scylla-per-server-metrics-nemesis-2-2-2018-07-23-19_52_24](https://user-images.githubusercontent.com/20959584/43092254-3b9d58a0-8eb5-11e8-8160-5d8f133ecd1d.png)

**Comment by avikivity** [comment] 2018-08-01 13:47
@roydahan  where can I find the RPMs?

**Comment by avikivity** [comment] 2018-08-01 14:15
@roydahan please help, without the RPMs I can't debug this

**Comment by slivne** [comment] 2018-08-01 15:51
@avikivity you can use the ami mentioned ami-905252ef

or this ... (I need to check why the directories are that bad ...)
http://downloads.scylladb.com/rpm/unstable/centos/a77bb1fe341c99fdf7e9353de7957ef951901d62-1b1b31d9cf6f04a1477747514b4acf44a269bab4-branch-2.3/10/scylla/7/x86_64/

**Comment by avikivity** [comment] 2018-08-01 16:05
```
$4 = (memtable &) @0x619008795800: {
  <seastar::enable_lw_shared_from_this<memtable>> = {
    <seastar::lw_shared_ptr_counter_base> = {
      _count = 6
    }, <No data fields>}, 
  <logalloc::region> = {
    _impl = {
      _b = 0x619001312800, 
      _p = 0x619001312810
    }
  }, 
  members of memtable: 
  _dirty_mgr = @0x61900965bc58, 
  _memtable_cleaner = {
    _region = @0x619008795808, 
    _tracker = 0x0, 
    _versions = {
      _head = {
        _version = 0x0, 
        _unique_owner = false
      }, 
      _tail = {
        _version = 0x0, 
        _unique_owner = false
      }
    }
  }, 
  _cleaner = 0x619008795820, 
  _memtable_list = 0x6190001990c8, 
  _schema = {
    _p = 0x619009569c00
  }, 
  _read_section = {
    _lsa_reserve = 10, 
    _std_reserve = 1024, 
    _minimum_lsa_emergency_reserve = 30
  }, 
  _allocating_section = {
    _lsa_reserve = 10, 
    _std_reserve = 1024, 
    _minimum_lsa_emergency_reserve = 30
  }, 
  partitions = {
    <boost::intrusive::set_impl<boost::intrusive::mhtraits<memtable_entry, boost::intrusive::set_member_hook<void, void, void, void>, &memtable_entry::_link>, void, memtable_entry::compare, unsigned long, true, void>> = {
      <boost::intrusive::bstree_impl<boost::intrusive::mhtraits<memtable_entry, boost::intrusive::set_member_hook<void, void, void, void>, &memtable_entry::_link>, void, memtable_entry::compare, unsigned long, true, (boost::intrusive::algo_types)5, void>> = {
        <boost::intrusive::bstbase<boost::intrusive::mhtraits<memtable_entry, boost::intrusive::set_member_hook<void, void, void, void>, &memtable_entry::_link>, void, memtable_entry::compare, true, unsigned long, (boost::intrusive::algo_types)5, void>> = {
          <boost::intrusive::bstbase_hack<boost::intrusive::mhtraits<memtable_entry, boost::intrusive::set_member_hook<void, void, void, void>, &memtable_entry::_link>, void, memtable_entry::compare, true, unsigned long, (boost::intrusive::algo_types)5, void>> = {
            <boost::intrusive::detail::size_holder<true, unsigned long, void>> = {
              static constant_time_size = <optimized out>, 
              size_ = 1
            }, 
            <boost::intrusive::bstbase2<boost::intrusive::mhtraits<memtable_entry, boost::intrusive::set_member_hook<void, void, void, void>, &memtable_entry::_link>, void, memtable_entry::compare, (boost::intrusive::algo_types)5, void>> = {
              <boost::intrusive::detail::ebo_functor_holder<boost::intrusive::tree_value_compare<memtable_entry*, memtable_entry::compare, boost::move_detail::identity<memtable_entry>, true>, false>> = {
                <boost::intrusive::tree_value_compare<memtable_entry*, memtable_entry::compare, boost::move_detail::identity<memtable_entry>, true>> = {
                  <boost::intrusive::detail::ebo_functor_holder<memtable_entry::compare, false>> = {
                    <memtable_entry::compare> = {
                      _c = {
                        s = {
---Type <return> to continue, or q <return> to quit---
                          _p = 0x619009569c00
                        }
                      }
                    }, <No data fields>}, <No data fields>}, <No data fields>}, 
              <boost::intrusive::bstbase3<boost::intrusive::mhtraits<memtable_entry, boost::intrusive::set_member_hook<void, void, void, void>, &memtable_entry::_link>, (boost::intrusive::algo_types)5, void>> = {
                static safemode_or_autounlink = <optimized out>, 
                static stateful_value_traits = <optimized out>, 
                static has_container_from_iterator = <optimized out>, 
                holder = {
                  <boost::intrusive::mhtraits<memtable_entry, boost::intrusive::set_member_hook<void, void, void, void>, &memtable_entry::_link>> = {
                    static link_mode = boost::intrusive::safe_link
                  }, 
                  members of boost::intrusive::bstbase3<boost::intrusive::mhtraits<memtable_entry, boost::intrusive::set_member_hook<void, void, void, void>, &memtable_entry::_link>, (boost::intrusive::algo_types)5, void>::holder_t: 
                  root = {
                    <boost::intrusive::rbtree_node<void*>> = {
                      parent_ = 0x6190ed020008, 
                      left_ = 0x6190ed020008, 
                      right_ = 0x6190ed020008, 
                      color_ = boost::intrusive::rbtree_node<void*>::red_t
                    }, <No data fields>}
                }
              }, <No data fields>}, <No data fields>}, <No data fields>}, 
        members of boost::intrusive::bstree_impl<boost::intrusive::mhtraits<memtable_entry, boost::intrusive::set_member_hook<void, void, void, void>, &memtable_entry::_link>, void, memtable_entry::compare, unsigned long, true, (boost::intrusive::algo_types)5, void>: 
        static constant_time_size = true, 
        static stateful_value_traits = <optimized out>, 
        static safemode_or_autounlink = true
      }, 
      members of boost::intrusive::set_impl<boost::intrusive::mhtraits<memtable_entry, boost::intrusive::set_member_hook<void, void, void, void>, &memtable_entry::_link>, void, memtable_entry::compare, unsigned long, true, void>: 
      static constant_time_size = true
    }, <No data fields>}, 
  _replay_position = {
    static max_cpu_bits = 10, 
    static max_ts_bits = 54, 
    static ts_mask = 18014398509481983, 
    static cpu_mask = 18428729675200069632, 
    id = 450359962737147707, 
    pos = 13917940
  }, 
  _rp_set = {
    _usage = std::unordered_map with 1 element = {
      [450359962737147707] = 15
    }
  }, 
  _underlying = {
    _object = {
      _fn = {
        _p = 0x0
      }, 
      _presence_checker_factory = {
        _p = 0x0
      }
    }
  }, 
  _flushed_memory = 11645, 
  _stats_collector = {
    timestamp = {
      _min_tracker = {
        _default_value = 1442880000000000, 
        _is_set = true, 
        _value = 1532363081475565
---Type <return> to continue, or q <return> to quit---
      }, 
      _max_tracker = {
        _default_value = 0, 
        _is_set = true, 
        _value = 1532363082507898
      }
    }, 
    min_local_deletion_time = {
      _default_value = 1442880000, 
      _is_set = true, 
      _value = 1532363082
    }, 
    min_ttl = {
      _default_value = 0, 
      _is_set = false, 
      _value = 24976
    }
  }
}
```

**Comment by avikivity** [comment] 2018-08-01 16:08
```
 p _mt._flushed_memory  
$10 = 11645
```

**Comment by avikivity** [comment] 2018-08-01 16:18
Only one segment in the region, active:

```
(gdb) p logalloc::shard_segment_pool._segments[$idx]
$21 = {
  <log_heap_hook<logalloc::segment_descriptor_hist_options>> = {
    <boost::intrusive::list_base_hook<void, void, void>> = {
      <boost::intrusive::generic_hook<(boost::intrusive::algo_types)0, boost::intrusive::list_node_traits<void*>, boost::intrusive::dft_tag, (boost::intrusive::link_mode_type)1, (boost::intrusive::base_hook_type)1>> = {
        <boost::intrusive::node_holder<boost::intrusive::list_node<void*>, boost::intrusive::dft_tag, 1>> = {
          <boost::intrusive::list_node<void*>> = {
            next_ = 0x0, 
            prev_ = 0x0
          }, <No data fields>}, 
        <boost::intrusive::hook_tags_definer<boost::intrusive::generic_hook<(boost::intrusive::algo_types)0, boost::intrusive::list_node_traits<void*>, boost::intrusive::dft_tag, (boost::intrusive::link_mode_type)1, (boost::intrusive::base_hook_type)1>, 1>> = {<No data fields>}, <No data fields>}, <No data fields>}, 
    members of log_heap_hook<logalloc::segment_descriptor_hist_options>: 
    cached_bucket = 134 '\206'
  }, 
  members of logalloc::segment_descriptor: 
  _free_space = 119437, 
  _region = 0x619001312810
}
(gdb) p 128*1024 - 119437
$22 = 11635
(gdb) 
```

**Comment by avikivity** [comment] 2018-08-01 16:18
We flushed 11645 bytes, but only 11635 are in use!

**Comment by avikivity** [comment] 2018-08-01 16:27
```
(gdb) p $reg._active_offset 
$26 = 20312
```

So, some overwrites have taken place.

**Comment by avikivity** [comment] 2018-08-01 16:35
possibly imr external_memory_usage is overestimating. @pdziepak please audit.

**Comment by avikivity** [comment] 2018-08-01 16:37
The memtable being flushed is the peers table, so we know its schema.

**Comment by avikivity** [comment] 2018-08-01 16:38
```
        // partition key
        {{"peer", inet_addr_type}},
        // clustering key
        {},
        // regular columns
        {
                {"data_center", utf8_type},
                {"host_id", uuid_type},
                {"preferred_ip", inet_addr_type},
                {"rack", utf8_type},
                {"release_version", utf8_type},
                {"rpc_address", inet_addr_type},
                {"schema_version", uuid_type},
                {"tokens", set_type_impl::get_instance(utf8_type, true)},
                {"supported_features", utf8_type},
        },
        // static columns
        {},
        // regular column name type
        utf8_type,
        // comment
        "information about known peers in the cluster"
```

**Comment by pdziepak** [comment] 2018-08-01 16:43
We used to have bug that made `external_memory_usage()` return too small values for large cells, but that has been fixed. There is now test that verifies `external_memory_usage()` is consistent with what we have actually allocated. Obviously, there may be some other bugs hidden but `external_memory_usage()` doesn't seem to be an obvious suspect.

https://github.com/scylladb/scylla/blob/a77bb1fe341c99fdf7e9353de7957ef951901d62/tests/mutation_test.cc#L1626-L1718

**Comment by avikivity** [comment] 2018-08-01 16:46
Another option is that mvcc merged some versions, reducing the memtable size, but we while we flushed them they weren't merged yet. Don't know if mvcc merges versions in the background in 2.3.

**Comment by avikivity** [comment] 2018-08-01 16:48
btw, we do have large cells (or rather, large atomic_cells_or_collections). The tokens set should be pretty large, 256 atomic_cells each of which has ~17 bytes of data + ~9 bytes of flags+timestamps, so at least 6600 bytes, and likely even more.

**Comment by avikivity** [comment] 2018-08-01 16:50
It can't be 6600 bytes because there are two peers and only 11635 bytes in use. So around 5500 bytes per peer token set, and 21 bytes per token. Not sure how that works.

**Comment by avikivity** [comment] 2018-08-01 16:50
Or maybe we only updated one peer.

**Comment by avikivity** [comment] 2018-08-01 16:51
In fact, there's one partition in that memtable:

```
  partitions = {
    <boost::intrusive::set_impl<boost::intrusive::mhtraits<memtable_entry, boost::intrusive::set_member_hook<void, void, void, void>, &memtable_entry::_link>, void, memtable_entry::compare, unsigned long, true, void>> = {
      <boost::intrusive::bstree_impl<boost::intrusive::mhtraits<memtable_entry, boost::intrusive::set_member_hook<void, void, void, void>, &memtable_entry::_link>, void, memtable_entry::compare, unsigned long, true, (boost::intrusive::algo_types)5, void>> = {
        <boost::intrusive::bstbase<boost::intrusive::mhtraits<memtable_entry, boost::intrusive::set_member_hook<void, void, void, void>, &memtable_entry::_link>, void, memtable_entry::compare, true, unsigned long, (boost::intrusive::algo_types)5, void>> = {
          <boost::intrusive::bstbase_hack<boost::intrusive::mhtraits<memtable_entry, boost::intrusive::set_member_hook<void, void, void, void>, &memtable_entry::_link>, void, memtable_entry::compare, true, unsigned long, (boost::intrusive::algo_types)5, void>> = {
            <boost::intrusive::detail::size_holder<true, unsigned long, void>> = {
              static constant_time_size = <optimized out>, 
              size_ = 1
            }, 
```

**Comment by avikivity** [comment] 2018-08-01 16:54
The tokens set is in fact visible in the segment.

**Comment by avikivity** [comment] 2018-08-01 17:08
From my reading of the code, we call `partition_snapshot::squashed()`, which calls `merge_versions()`, which can cause memtable memory to be freed without equivalent accounting in the flusher. But need @tgrabiec to confirm and/or find a way to determine if merging in fact happened.

**Comment by avikivity** [comment] 2018-08-01 17:10
And from https://github.com/scylladb/scylla/issues/3625#issuecomment-409635272 we know overwrites did take place, so merging is at least not impossible.

**Comment by tgrabiec** [comment] 2018-08-03 16:43
Another explanation is that if `partition_snapshot_flat_reader::emplace_mutation_fragment()` fails to push the fragment, it will account for it twice when the enclosing section is retried.

@avikivity Where do you see `partition_snapshot::squashed()` called? The flush reader accounts through `partition_snapshot_flat_reader`, which is measuring fragments produced by the mutation reader, which is after MVCC versions are merged on the fly. This should not be greater than what we would get after MVCC versions are actually merged in the memtable, since on-the-fly merging should be consistent with actual version merging.

**Comment by pdziepak** [comment] 2018-08-06 08:35
`partition_snapshot_flat_reader::emplace_mutation_fragment()` isn't run in an allocating section. If it fails the whole read would fail.

**Comment by tgrabiec** [comment] 2018-08-10 14:32
I decoded contents of the memtable, and according to my calculations the flush reader accounter should have counted 11589 bytes instead of 11645:

```
sizeof(memtable_entry) = 104 + 2 for encoded_size() = 106
sizeof(partition_version) = 224 + 2 for encoded_size() = 226
sizeof(rows_entry) = 224

vector storage = 8 + (_capacity) 13 * 16 = 216

                {"data_center", utf8_type},   0x6190ed0215f1 + 9 + 8 + 4 + (data) 7 "us-east"
                {"host_id", uuid_type},  fixed-size 0x6190ed021f51 + 9 + 8 + 16
                {"preferred_ip", inet_addr_type}, 0 (not set)
                {"rack", utf8_type},  0x6190ed0217d9 + 9 + 8 + 4 + (data) 2 "1d"
                {"release_version", utf8_type}, 0x6190ed0219c1 + 9 + 8 + 4 + 5 ("3.0.0")
                {"rpc_address", inet_addr_type}, 0x6190ed021ba9 + 9 + 8 + 4 + 4
                {"schema_version", uuid_type},  fixed-size 0x6190ed021ba9 + 9 + 8 + 16
                {"supported_features", utf8_type}, 0x6190ed022141 + 9 + 8 + 4 + 224
                {"tokens", set_type_impl::get_instance(utf8_type, true)}, 0x6190ed0224e1 + 9 + 4 + (external) 10365 + 16 + 10

(gdb) p 226 + 106 + 224 + 216 + (9 + 8 + 4 + 7) + (9 + 8 + 16) + (9 + 8 + 4 + 2) + (9 + 8 + 4 + 5) + (9 + 8 + 4 + 4) + (9 + 8 + 16) + (9 + 8 + 4 + 224) + (9 + 4 + 10365 + 16 + 10)
$23 = 11589

```

**Comment by tgrabiec** [comment] 2018-08-16 11:40
According to @roydahan, reproduced with f8cec2f89 as well.

**Comment by bentsi** [comment] 2018-08-28 13:50
Was not able to reproduce with `scylla-server-2.3.rc0-0.20180814.6348a73.el7.x86_64.rpm` provided by @tgrabiec

**Comment by bentsi** [comment] 2018-08-29 09:27
Per @tgrabiec request trying to reproduce again

**Comment by bentsi** [comment] 2018-09-02 11:08
UPDATE
As I commented 4 days ago, I succeed to reproduce the issue with the RPMs provided by @tgrabiec (As far as I understand the RPM include modified version of Scylla) and by setting logging level of the new flush_logger to trace.
The issue was reproduced during write workload of 1000 c-s processes and while Scylla was 100 % loaded across all nodes. After stopping, waiting 1 minute and starting one of the nodes, other node crashed and dumped core. @tgrabiec analyzed the cored dump and the logs but was not able to get to the root cause. So he compiled another RPMs and asked me to try to reproduce issue when Scylla stated with logging level debug and new RPMs. Two attempts didn't reproduce the issue.
Per @tgrabiec  request I will try to run the test without debug level logging and see if it reproduces.

**Comment by bentsi** [comment] 2018-09-02 16:37
coredump and monitor data is available on instances (currently stopped them to save money)

**Comment by slivne** [comment] 2018-09-02 18:36
coredump is placed on /var/lib/scylla -

if the instances are using ephemeral drives on ec2 (i3 / i2) then the
content will be lost.

...

I hope that is not the case.

If needed offload the coredump follow what our customers do
http://docs.scylladb.com/operating-scylla/troubleshooting/report_scylla_problem/#core-dump

**Comment by bentsi** [comment] 2018-09-03 08:15
@slivne unfortunately as you mentioned in previous comment the coredump data is lost. 
@tgrabiec  can you understand from the back trace what the issue is or you still need the coredump?

**Closed** 2018-09-03 16:57 UTC
Labels: bug, high
