### ISSUE TITLE
system_concurrency_semaphore timeout

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylla#8306] opened 2021-03-17 19:06 UTC
In dtest:

```
21:01:16  FAIL: counter_consistency_node_repair_test (counter_tests.TestCountersOnMultipleNodes)
21:01:16  ----------------------------------------------------------------------
21:01:16  Traceback (most recent call last):
21:01:16    File "/jenkins/workspace/scylla-master/next/scylla-dtest/counter_tests.py", line 727, in tearDown
21:01:16      super(TestCountersOnMultipleNodes, self).tearDown()
21:01:16    File "/jenkins/workspace/scylla-master/next/scylla-dtest/dtest.py", line 1134, in tearDown
21:01:16      self.cleanUpCluster()
21:01:16    File "/jenkins/workspace/scylla-master/next/scylla-dtest/dtest.py", line 1188, in cleanUpCluster
21:01:16      raise AssertionError('Unexpected errors found: {}'.format(found_errors))
21:01:16  AssertionError: Unexpected errors found: [('node2', ['ERROR 2021-03-17 18:35:50,369 [shard 0] storage_proxy - Exception when communicating with 127.0.2.2, to read from system_auth.roles: seastar::named_semaphore_timed_out (Semaphore timed out: _system_read_concurrency_sem)', 'ERROR 2021-03-17 18:35:50,370 [shard 0] storage_proxy - Exception when communicating with 127.0.2.2, to read from system_auth.roles: seastar::named_semaphore_timed_out (Semaphore timed out: _system_read_concurrency_sem)', 'ERROR 2021-03-17 18:35:50,368 [shard 0] storage_proxy - Exception when communicating with 127.0.2.2, to read from system_auth.roles: seastar::named_semaphore_timed_out (Semaphore timed out: _system_read_concurrency_sem)', 'ERROR 2021-03-17 18:35:50,371 [shard 0] storage_proxy - Exception when communicating with 127.0.2.2, to read from system_auth.roles: seastar::named_semaphore_timed_out (Semaphore timed out: _system_read_concurrency_sem)'])]
```

This is an overcommitted environment, so elevated latency is expected. Perhaps we need to raise timeouts, or reduce the test write amount and concurrency.

Note it's a failure reading auth_roles. Which should be completely cached, and perhaps read with infinite timeouts.

**Comment by bhalevy** [comment] 2021-03-18 08:07
Duplicate of #7999

**Closed** 2021-03-18 10:34 UTC
