### ISSUE TITLE
pre-filter sstables during query

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylla#1176] opened 2016-04-11 13:04 UTC
Right now for a single row query we create a reader for each sstable, run them all, and merge the results.

If most sstables return an empty mutation (due to: filter, summary, or pkey range), this was wasted work.

**Comment by nyh** [comment] 2016-04-11 13:08
Probably a duplicate of issue #1056 ?

**Comment by nyh** [comment] 2016-04-11 13:09
(although not an exact duplicate, because we can also avoid the merging of those empty sstable readers)

**Closed** 2016-04-11 13:11 UTC
Labels: performance
