### ISSUE TITLE
scylla_storage_proxy_replica_cross_shard_ops isn't reduced after switched to shard-aware driver

### ISSUE THREAD

**Issue by amoskong** [scylladb/scylla#5406] opened 2019-12-03 04:30 UTC
*Installation details*
Scylla version (or git commit hash):
- scylla-tools-core-666.development-20191130.35906df2a0d.noarch
- scylla-666.development-0.20191130.96009881d8c.el7.x86_64
- scylla-tools-666.development-20191130.35906df2a0d.noarch
Cluster size: 1
OS (RHEL/CentOS/Ubuntu/AWS AMI): CentOS7

### Description

We just merged a PR from @haaawk to use shard-aware driver.
- Switch to shard aware driver #122
- https://github.com/scylladb/scylla-tools-java/pull/122

I tested both old and new driver, the scylla_storage_proxy_replica_cross_shard_ops metric almost didn't change after upgraded the driver.

### Old driver: (doesn't support shard aware):

- http://downloads.scylladb.com.s3.amazonaws.com/rpm/unstable/centos/master/201911172141/scylla.repo

```
laster commit before apply the support: c9cc08c5949

scylla-666.development-0.20191115.2195edb819b.el7.x86_64.rpm
scylla-ami-666.development-20191117.15bb0a7db7.fc27.noarch.rpm
scylla-conf-666.development-0.20191115.2195edb819b.el7.x86_64.rpm
scylla-debuginfo-666.development-0.20191115.2195edb819b.el7.x86_64.rpm
scylla-jmx-666.development-20191116.f45ae1833e0.noarch.rpm
scylla-kernel-conf-666.development-0.20191115.2195edb819b.el7.x86_64.rpm
scylla-python3-3.7.4-0.20191116.2195edb819b.el7.x86_64.rpm
scylla-server-666.development-0.20191115.2195edb819b.el7.x86_64.rpm
scylla-tools-666.development-20191116.c9cc08c5949.noarch.rpm
scylla-tools-core-666.development-20191116.c9cc08c5949.noarch.rpm
```

### New driver: (support shard aware)

- http://downloads.scylladb.com.s3.amazonaws.com/rpm/unstable/centos/master/201911241619/scylla.repo
- http://downloads.scylladb.com.s3.amazonaws.com/rpm/unstable/centos/master/201912011906/scylla.repo

New driver:
```
$ rpm -qa |grep scylla
scylla-kernel-conf-666.development-0.20191130.96009881d8c.el7.x86_64
scylla-jmx-666.development-20191130.d8c47603d9a.noarch
scylla-server-666.development-0.20191130.96009881d8c.el7.x86_64

>>> scylla-tools-core-666.development-20191130.35906df2a0d.noarch

scylla-666.development-0.20191130.96009881d8c.el7.x86_64
scylla-tools-666.development-20191130.35906df2a0d.noarch
scylla-conf-666.development-0.20191130.96009881d8c.el7.x86_64
scylla-python3-3.7.5-0.20191130.96009881d8c.el7.x86_64
```

### Workloads
- prepare-cs:
    - cassandra-stress write no-warmup n=10000000 -rate threads=500
- mixed cs:
    - cassandra-stress mixed no-warmup n=10000000 -rate threads=500

![image](https://user-images.githubusercontent.com/309708/70020673-7a6fa100-15c8-11ea-9d9f-99d3199940c0.png)

**Comment by amoskong** [comment] 2019-12-18 10:32
@haaawk any update?

**Comment by jul-stas** [comment] 2019-12-18 10:36
Hi @amoskong, I can't reproduce it on current master.
I ran your `cassandra-stress` commands while looking at the metrics `scylla_storage_proxy_replica_cross_shard_ops`:
1. with datastax driver these metrics grow as in your example
2. with shard-aware driver metrics don't even move. Not by a single increment.
Did you use any particular settings/topology? Did you see `===== Using optimized driver!!! =====` in logs when running shard-aware driver?

**Comment by haaawk** [comment] 2019-12-18 10:39
Maybe scylla-tools-java are not correctly switched to shard-aware driver

**Comment by haaawk** [comment] 2019-12-18 10:47
Juliusz and I have figured out that a cassandra driver jar in lib/ dir is overriding shard aware driver. Juliusz will fix it in PR.

**Comment by amoskong** [comment] 2019-12-18 10:50
> Juliusz and I have figured out that a cassandra driver jar in lib/ dir is overriding shard aware driver. Juliusz will fix it in PR.

Thanks. I will retest when the new packages are built.

**Comment by amoskong** [comment] 2020-01-21 09:30
Sure, I will update you later

**Comment by slivne** [comment] 2020-02-20 08:23
I think this was tracked to using protocol-v3 instead of protocol-v4 - we had a simillar issue with LWT. 

I am closing this.

**Closed by slivne** 2020-02-20 08:23 UTC
Labels: bug
