### ISSUE TITLE
Investigate little throughput drops caused by compaction/memtable flush

### ISSUE THREAD

**Issue by dorlaor** [scylladb/scylla#1101] opened 2016-03-26 20:37 UTC
Installation details
Scylla version (or git commit hash): RC1
Cluster size: 3 nodes, RF=3, CL=Q
OS (RHEL/CentOS/Ubuntu/AWS AMI): AWS, i8.2xl

Glauber provided these graphs. One can easily identify a pattern of a big drop of ~100k ops
every couple of seconds with two intermediate
![disk-usage](https://cloud.githubusercontent.com/assets/1735237/14062314/8c37340e-f3ab-11e5-8181-7d4d60eec9fe.png)
![results](https://cloud.githubusercontent.com/assets/1735237/14062313/8c36642a-f3ab-11e5-89a0-c10b10b038e1.png)

 small drops.

We need to smooth them up.

**Comment by tzach** [comment] 2016-03-27 06:55
Wild theory: compaction in different levels.
Small tables compaction - small drop
Bigger table - bigger drop

**Comment by tgrabiec** [comment] 2016-03-30 16:27
Looks like duplicate of #470

**Comment by glommer** [comment] 2016-04-20 22:49
Just posted a patch that smoothes this out. It has a bit of seastar infrastructure too.

Effects on the load:

![compactions-v2](https://cloud.githubusercontent.com/assets/331197/14692885/6e825688-0728-11e6-9f98-98a36f962fa1.png)

Effects on the disk:

![memtables-v2](https://cloud.githubusercontent.com/assets/331197/14692886/6e827672-0728-11e6-9a8c-f99a58a29368.png)

We can see that compactions are not made slower, but are smoothed out over time.

**Comment by nyh** [comment] 2016-04-21 04:24
On Thu, Apr 21, 2016 at 1:49 AM, Glauber Costa <notifications@github.com>
wrote:

> Just posted a patch that smoothes this out. It has a bit of seastar
> infrastructure too.
>
> Effects on the load:
>
> [image: compactions-v2]
> <https://cloud.githubusercontent.com/assets/331197/14692885/6e825688-0728-11e6-9f98-98a36f962fa1.png>
>
> Effects on the disk:
>
> [image: memtables-v2]
> <https://cloud.githubusercontent.com/assets/331197/14692886/6e827672-0728-11e6-9a8c-f99a58a29368.png>
>
> We can see that compactions are not made slower, but are smoothed out over
> time.
>

How do we see in this graph that "compactions are not made slower"?

When we really need a compaction to finish quickly (e.g., we have a lot of
sstables and reads
are becoming slower, or alternatively, the machine is almost idle),  can
it?

Nadav.

**Comment by glommer** [comment] 2016-04-21 12:22
@nyh you can see in the graph that instead of spikes they are now a constant load. So they are not conceptually slower, although they can still be a bit slower in practice.

After a 45 min run, however, there is no backlog.

I didn't mean to imply that in both runs, compactions are at the exactly same average speed. That's not only hard to measure, but also irrelevant. What truly matters is that we're not just neglecting compaction, so that after the load finishes, we now have 10 minutes worth of compaction backlog. It is in this sense that I meant they are not slower.

**Comment by nyh** [comment] 2016-04-21 12:36
On Thu, Apr 21, 2016 at 3:23 PM, Glauber Costa <notifications@github.com>
wrote:

> @nyh <https://github.com/nyh> you can see in the graph that instead of
> spikes they are now a constant load. So they are not conceptually slower,
> although they can still be a bit slower in practice.
>

I'm sorry, I don't understand which graph you're referring to... The last
one?
In the last graph I see that instead of very sharp spikes, suggesting that
compaction finished very quickly,
we now have low constant (actually somewhat wiggly) low activity. This
suggests to me that the compactions
were much slower than before. This is not necessarily a bad thing, but I
don't understand how you got that
to show that "compactions are not made slower". In what sense are they not
made slower?

What would be interesting to measure (I don't know if we can) is:

 1. The *cpu usage* of the compaction. If *that* increases, it means all
the overhead we added recently -
     in the form of Seastar threads (instead of continuations), timers,
etc., added up.

 2. The maximum rate compaction can proceed if we give it 1.0 "usage"
rights. If this slowed down from
     before it might be we are not pre-reading enough (as Avi already
pointed out).

After a 45 min run, however, there is no backlog.
>

This is great, but of course this is just an example workload - it doesn't
prove anything about other cases.


> I didn't mean to imply that in both runs, compactions are at the exactly
> same average speed. That's not only hard to measure, but also irrelevant.
> What truly matters is that we're not just neglecting compaction, so that
> after the load finishes, we now have 10 minutes worth of compaction
> backlog. It is in this sense that I meant they are not slower.
>

In your use case, the amount of time you devoted to compaction was indeed
enough.
But I'm guessing that in other use cases, it will *not* be enough and
you'll need to devote
more time to compaction. I know you're already thinking about this issue,
but I just wanted
to point out how this one graph you generated here doesn't really "prove"
much.

**Comment by glommer** [comment] 2016-04-21 12:40
Nadav, I am talking obviously over the course of the run.

Yes, of course in the first graph there is a big spike and compactions finish very fast. But they do that at the expense of the current load, which can't be served because of that. Instead of a big delta, you now have a more or less flat curve. If you integrate over time, you should see very similar results.

As for compactions falling behind, please look at my patches. The amount of CPU devoted to compaction grows as the backlog grows, so if we start seeing a backlog, we'll run more of compactions and less of the load.

**Comment by tgrabiec** [comment] 2016-12-02 10:05
Refs #1911

**Comment by glommer** [comment] 2018-04-28 15:46
Issue is well understood now and fixed by the Compaction controllers. @dorlaor please close (I don't have closing permissions)

**Closed** 2018-04-29 08:10 UTC
Labels: User Request, enhancement, performance, stability
