### ISSUE TITLE
Scylla mbind error during scylla_setup script execution

### ISSUE THREAD

**Issue by eyalgutkind** [scylladb/scylla#2227] opened 2017-03-28 02:25 UTC
*Installation details*
Scylla version (or git commit hash): 1.6.1-20170218.2ea4da2
Cluster size: 3 
OS (RHEL/CentOS/Ubuntu/AWS AMI): Ubuntu 16.04

Platform (physical/VM/cloud instance type/docker): Cloud, Joyent

When installing Scylla on a Joyent Infrastructure container, the scylla_setup script delivers an unexplained, repetitive message to the user screen. After answering the question whether to have scylla start at boot, the script prints to the screen multiple times "WARNING: unable to mbind shard memory; performance may suffer:" 

Does the warning has to do with the boot option of Scylla? Also, is it possible to limit the number of warning printing to a single one, and provide the reasoning of the warning trigger? It looks like it should not be related to the boot option.

Being picky for a second, also fix the typo in the question:
Do you want to setup bootloader options?
**Anwser** yes to enable hugepages at boot time; this improve performance. Answer no to skip this step.

scylla_setup
Skip any of the following steps by answering 'no'
Do you want to run kernel version check?
Answer yes to have this script verify that the currently installed kernel is qualified to run Scylla; answer no to skip this check.
[YES/no]no
Do you verify ScyllaDB packages installed?
Answer yes to have this script check that ScyllaDB is already installed; answer no to skip this check.
[YES/no]no
Do you want to enable ScyllaDB services?
Answer yes to automatically start Scylla when the node boots; answer no to skip this step.
[YES/no]yes
Created symlink from /etc/systemd/system/multi-user.target.wants/scylla-server.service to /lib/systemd/system/scylla-server.service.
Synchronizing state of collectd.service with SysV init with /lib/systemd/systemd-sysv-install...
Executing /lib/systemd/systemd-sysv-install enable collectd
WARNING: unable to mbind shard memory; performance may suffer:
WARNING: unable to mbind shard memory; performance may suffer:
WARNING: unable to mbind shard memory; performance may suffer:
WARNING: unable to mbind shard memory; performance may suffer:
WARNING: unable to mbind shard memory; performance may suffer:
WARNING: unable to mbind shard memory; performance may suffer:
WARNING: unable to mbind shard memory; performance may suffer:
WARNING: unable to mbind shard memory; performance may suffer:
WARNING: unable to mbind shard memory; performance may suffer:
WARNING: unable to mbind shard memory; performance may suffer:
WARNING: unable to mbind shard memory; performance may suffer:
WARNING: unable to mbind shard memory; performance may suffer:
WARNING: unable to mbind shard memory; performance may suffer:
WARNING: unable to mbind shard memory; performance may suffer:
WARNING: unable to mbind shard memory; performance may suffer:
WARNING: unable to mbind shard memory; performance may suffer:
WARNING: unable to mbind shard memory; performance may suffer:
WARNING: unable to mbind shard memory; performance may suffer:
WARNING: unable to mbind shard memory; performance may suffer:
WARNING: unable to mbind shard memory; performance may suffer:
WARNING: unable to mbind shard memory; performance may suffer:
WARNING: unable to mbind shard memory; performance may suffer:
WARNING: unable to mbind shard memory; performance may suffer:
WARNING: unable to mbind shard memory; performance may suffer:
WARNING: unable to mbind shard memory; performance may suffer:
WARNING: unable to mbind shard memory; performance may suffer:
WARNING: unable to mbind shard memory; performance may suffer:
WARNING: unable to mbind shard memory; performance may suffer:
WARNING: unable to mbind shard memory; performance may suffer:
WARNING: unable to mbind shard memory; performance may suffer:
WARNING: unable to mbind shard memory; performance may suffer:
WARNING: unable to mbind shard memory; performance may suffer:
WARNING: unable to mbind shard memory; performance may suffer:
WARNING: unable to mbind shard memory; performance may suffer:
WARNING: unable to mbind shard memory; performance may suffer:
WARNING: unable to mbind shard memory; performance may suffer:
WARNING: unable to mbind shard memory; performance may suffer:
WARNING: unable to mbind shard memory; performance may suffer:
WARNING: unable to mbind shard memory; performance may suffer:
WARNING: unable to mbind shard memory; performance may suffer:
WARNING: unable to mbind shard memory; performance may suffer:
WARNING: unable to mbind shard memory; performance may suffer:
WARNING: unable to mbind shard memory; performance may suffer:
WARNING: unable to mbind shard memory; performance may suffer:
WARNING: unable to mbind shard memory; performance may suffer:
WARNING: unable to mbind shard memory; performance may suffer:
WARNING: unable to mbind shard memory; performance may suffer:
WARNING: unable to mbind shard memory; performance may suffer:
WARNING: unable to mbind shard memory; performance may suffer:
WARNING: unable to mbind shard memory; performance may suffer:
Do you want to disable SELinux?
Answer yes to disable SELinux; this improves performance; answer no to keep it activated.
[YES/no]yes
Do you want to setup bootloader options?
Anwser yes to enable hugepages at boot time; this improve performance. Answer no to skip this step.
[YES/no]no

**Comment by syuu1228** [comment] 2017-04-11 22:56
@eyalgutkind I suppose this is platform dependent issue, could you explain how can we reproduce the issue? Including how to install Scylla on "Joyent".

**Comment by eyalgutkind** [comment] 2017-04-11 23:23
@syuu1228 I can provision a node for your usage on a Joyent system.
If you can provide me on the internal email your public ssh-id key, I can add it to a node I'll create for you.
I'll also provide the procedure used to install scylla

**Comment by syuu1228** [comment] 2017-04-14 15:11
@avikivity to suppress the warning message, I think we need to skip ::mbind() on seastar/core/memory.cc when we running scylla in container.
Something like 
```
bool in_container() { ... <container detector code> ... }

if (in_container()) {
    for (auto && x : m) {
...
        ::mbind(..)
...
    }
}
```
Or pass --container flag on the program argument, then 
```
if (has_container_flag)
```
In that case we need to detect container in our scripts.

Do you agree the change, or should we need to leave the warning?

related to scylladb/seastar#211

**Comment by slivne** [comment] 2017-05-25 10:31
@syuu1228 can we close the issue - or are there additional patches ?

**Comment by syuu1228** [comment] 2017-05-25 10:34
Requires additonal patch, will send it in today.

2017年5月25日(木) 午後7:31 Shlomi Livne <notifications@github.com>:

**Comment by slivne** [comment] 2017-06-29 12:10
@syuu1228 - was this fixed ?

**Comment by syuu1228** [comment] 2017-06-30 05:58
@slivne "[PATCH scylla] dist/common/scripts/scylla_setup: Support container setup" posted in May 29.

**Comment by penberg** [comment] 2018-09-20 05:40
This happens with our Docker image too. We ought to fix the warning because it's just terrible UX.

**Comment by avikivity** [comment] 2020-08-05 16:22
No real users on Joyent, closing.

**Closed by avikivity** 2020-08-05 16:22 UTC
Labels: UX, bug, joyent, onboarding
