### ISSUE TITLE
scylla vs cassandra compatibility issue (spark connector filtering on secondary index)

### ISSUE THREAD

**Issue by krisplazonic** [scylladb/scylla#7043] opened 2020-08-14 14:01 UTC
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [x] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash): 4.1.4-0.20200809.76f4bc4c6f0
Cluster size: 4
OS (RHEL/CentOS/Ubuntu/AWS AMI): DCOS on CensOS

## Issue

Spark-cassandra connector behaves differently on Scylla vs Cassandra. When Scylla table is queried for a unique row by a secondary-indexed column "email", spark-cassandra connector on Scylla produces: 
- a count of 0 (correct value 1)
- a dataframe of many repeated identical rows (correct value 1 row)
Observations:
- Identical data and queries on Cassandra produce correct results.
- cqlsh queries on Scylla produce correct results.
- Filtering on a *primary key* in Scylla produces correct results.

## Steps to reproduce:
1. create keyspace `dev` and table `device_email`
2. write data from spark-shell to scylla `dev.device_email`
3. create secondary index on email column in cqlsh
4. query data from spark, filtering on secondary index column via spark-cassandra connector

## Setup
scylla docker image: scylladb/scylla    (latest on week of Aug 8, 2020)
scylla version: 4.1.4-0.20200809.76f4bc4c6f0
scylla installed on DCOS on 4 nodes with 4cpu and 8Gb of RAM

Cassandra: - freshly installed from DCOS package running Cassandra 3.11.6 with default parameters on 3 nodes, 4cpus, 8G of RAM (docker image cassandra:3.11.6)

Spark - version 2.4.0 of spark and spark-cassandra connector versions 2.4.0 and 2.5.0

## Code to reproduce steps:

1. create keyspace dev and table `device_email`
```
CREATE  KEYSPACE IF NOT EXISTS dev
   WITH REPLICATION = {
      'class' : 'SimpleStrategy', 'replication_factor' : 3 } ;

use dev;

CREATE TABLE IF NOT EXISTS dev.device_email (
   device_type text,
   device_id text,
   email text,
   PRIMARY KEY ((device_type, device_id), email));
```
2. write data from spark-shell to scylla `dev.device_email`  (Spark version 2.4.0)
```
./spark-shell --packages com.datastax.spark:spark-cassandra-connector_2.11:2.5.0 --conf spark.cassandra.connection.host=10.0.100.134
val df = spark.read.option("header", "true").csv("device_email.csv")
import org.apache.spark.sql.cassandra._
df.write.cassandraFormat("device_email", "dev").save
```
the csv file is 1,000,000 rows with mock data like:
```
device_type,device_id,email
idfa,ahYu2uchuy-1,email-1@ahYu2uchuy.com
idfa,aimoh8IeNg-1,email-1@aimoh8IeNg.com
idfa,omaephei3E-1,email-1@omaephei3E.com
idfa,aeM7wiehoh-1,email-1@aeM7wiehoh.com
idfa,eevoh1ieSo-1,email-1@eevoh1ieSo.com
idfa,Ohloocai6c-1,email-1@Ohloocai6c.com
```
3. create secondary index on email column in cqlsh
```
CREATE INDEX byemail ON dev.device_email (email);
```
4. query data from spark, filtering on secondary index column via spark-cassandra connector
```
import org.apache.spark.sql.cassandra._
val df = spark.read.cassandraFormat( "device_email", "dev").load()
```

## Results
```
cqlsh:dev> select * from device_email where email = 'email-44@Oohouwu9ai.com' ALLOW FILTERING;
 device_type | device_id     | email
-------------+---------------+-------------------------
        idfa | Oohouwu9ai-44 | email-44@Oohouwu9ai.com
(1 rows)
```
and from spark with connector 2.5.0:
```
scala> val df = spark.read.cassandraFormat( "device_email", "dev").load()
df: org.apache.spark.sql.DataFrame = [device_type: string, device_id: string ... 1 more field]
scala> df.filter("email = 'email-44@Oohouwu9ai.com'").count
res0: Long = 0
scala> df.filter("email = 'email-44@Oohouwu9ai.com'").show(false)
+-----------+-------------+-----------------------+
|device_type|device_id    |email                  |
+-----------+-------------+-----------------------+
|idfa       |Oohouwu9ai-44|email-44@Oohouwu9ai.com|
|idfa       |Oohouwu9ai-44|email-44@Oohouwu9ai.com|
|idfa       |Oohouwu9ai-44|email-44@Oohouwu9ai.com|
|idfa       |Oohouwu9ai-44|email-44@Oohouwu9ai.com| (and other identical rows)
scala> df.filter("email = 'email-44@Oohouwu9ai.com'").count
res0: Long = 0
scala> df.filter("email = 'email-44@Oohouwu9ai.com'").distinct.count
res1: Long = 1
```
The only difference with connector version 2.4.0 seems to be that I get a count of 1025 instead of 0.

On cassandra I do get a count of 1 and showing the dataframe shows 1 row.

**Comment by avikivity** [comment] 2020-08-16 11:55
Can you extract the CQL queries generated by Spark? Perhaps with Scylla tracing, or with Spark logging.

**Comment by slivne** [comment] 2020-09-13 09:26
@haaawk / @avelanarius - we need to extract the CQL queries and then look if they return correct values without spark.

- If there is a difference at CQL level - I expect it will be clearer whats the source of the issue
- If there is no difference at CQL level  - we need to look at whats causing the spark connector to behave differently.

Please queue this

**Comment by slivne** [comment] 2020-10-15 09:48
@avelanarius since we have done the analysis and found the root cause - please write some update on this issue

**Comment by avelanarius** [comment] 2020-10-15 10:50
I have extracted the CQL queries that are sent from Spark to Cassandra/Scylla.

The query that Scylla returned incorrect results for was:
```
SELECT count(*)  FROM "dev"."device_email" WHERE token("device_type", "device_id") > ? AND token("device_type", "device_id") <= ? AND "email" = ? ALLOW FILTERING
```
(remainder: `email` is the column with index)

### First issue
After reducing (removing token restrictions) the query to:
```
SELECT count(*)  FROM "dev"."device_email" WHERE "email" = ? ALLOW FILTERING
```
Scylla returned invalid count, even though `SELECT *` returned correct rows. This issue is fixed in  https://github.com/scylladb/scylla/pull/7438, which is in review now.

### Second issue
In queries on tables with secondary indexes, `TOKEN` restrictions are not properly applied (returned results are as if the `TOKEN` restriction was always true). I am currently working on this issue.  

I believe that after fixing those issues (first fix in review, second one I am working on), the connector will return correct results.

**Closed** 2021-07-22 19:34 UTC
Labels: Spark, User Request, bug, sec-index

**Comment by avikivity** [comment] 2023-02-22 19:35
Fix present on all active branches, not backporting.
