### ISSUE TITLE
Full table scan: Reading from the disks ~200MB, while returning to the client ~2MB -> read ahead is very big but 99% is thrown away (1:100 ratio)

### ISSUE THREAD

**Issue by tomer-sandler** [scylladb/scylla#2175] opened 2017-03-20 07:52 UTC
Version: Scylla v1.6.1

Cluster details:
Scylla cluster:  3 x RHEL7.2 nodes deployed on Google Compute Engine (GCE), each has 8 vCPUs and 30GB memory.
Storage: each node has 2 x 375GB local SSDs (NVMe) disks  
Client: Centos7.2 node deployed on GCE (4 vCPU and 15GB memory) runs our golang code using gocql driver
Client prerequisites:
Install go 1.7: https://www.digitalocean.com/community/tutorials/how-to-install-go-1-7-on-centos-7
Install gocql driver: "go get github.com/gocql/gocql"
Install kingpin pkg: "go get gopkg.in/alecthomas/kingpin.v2"

Dataset:
Populated 475M rows from 10 loaders using Cassandra stress, each running the following on sequential range:
nohup cassandra-stress write n=47500000 cl=QUORUM -schema "replication(factor=3)" -mode native cql3 -pop seq=1..47500000 -node 10.240.0.29,10.240.0.30,10.240.0.35 -rate threads=500 -log file=output.txt

Code:
Using the golang code from to perform full table scan: https://github.com/tomer-sandler/scylla-code-samples/tree/master/efficient_full_table_scan_example_code

While analyzing the results with Avi, we noticed the following:
- As far as I understood it, it's a bug, or let's say as design, but needs to be improved sometime in the future. You can see it when looking at the "Query I/O queue bandwidth" metrics in the per-server disk I/O view VS. the "Interface Tx Bps" metrics in the per server metrics view.
- We read ~200MB from the disks, while returning to the client only ~2MB. Which means the read ahead is very big and 99% is thrown away. There are many SStables as during the injection attempts there were some overwrites.
- Worth noting that  when reducing the page size to 1000 (instead of 5000 = default), the ratio became more of 1:40, which is better than 1:100

**Comment by slivne** [comment] 2017-03-20 13:46
> Worth noting that when reducing the page size to 1000 (instead of 5000 = default), the ratio became more of 1:40, which is better than 1:100

Given that its a default cassandra-stress workload (single partition is ~300 bytes):
- using a page size of 1000 would need to read ~300K 
- using a page size of 5000 would need to read ~1.5M

Please note there is no compression in the default cassandra-stress workload

I don't understand how we are getting such bad ratios if we are reading 128K (is that the default size  ?) and doing read aheads of up to 4 or 8 blocks. 

I especially don't understand how the change to use larger page size caused a degradation in the ratio of used vs throw away given that the change should mostly be related to reading from the data file and should not add additional reads to any other element .

@avikivity , @pdziepak 

I don't think that throwing away the reader and recreating it for each next page can explain this - something else in play here

**Comment by pdziepak** [comment] 2017-03-20 13:53
5d66031b7a12341fab86c387c611570db1c08acc wasn't backported and without it read-ahead is not doing the slow start in order to keep the amount of unused data in check. I'm not sure if this can explain everything, but it is definitely the most obvious thing to verify.

**Comment by slivne** [comment] 2017-04-25 10:05
the issue is probably fixed - need to be validated as part of 1.8

**Comment by roydahan** [comment] 2018-03-18 13:52
@slivne new read amplification tests for scanning reads were added by @larisau, I think we can close this one. (all pass on master).

**Comment by avikivity** [comment] 2018-03-18 13:55
What's the read amplification now?

Note that #1865 will reduce it further.

**Comment by tzach** [comment] 2018-04-25 10:56
Thanks, @roydahan closing the issue.

**Closed by tzach** 2018-04-25 10:56 UTC
Labels: bug, fixed, performance
