### ISSUE TITLE
sstableloader fails on counter columns

### ISSUE THREAD

**Issue by gnumoreno** [scylladb/scylla#4199] opened 2019-02-06 21:29 UTC
During a migration from C* to Scylla using sstableloader (snapshots were moved to intermediary servers and sstableloader was run from there, using scylla 3 repository on ubuntu 14).

`sstableloader --username scylla -pw PASS --verbose -d 52.70.169.28 ad_performance/data_by_tracking_id-70c77e60660511e5853c37253ab0447b`

```
WARN  19:50:32,347 Only 38.467GiB free across all data volumes. Consider adding more capacity to your cluster or removing obsolete snapshots
WARN  19:50:33,450 dclocal_read_repair_chance and read_repair_chance table options have been deprecated and will be removed in version 4.0
Adding sstable ad_performance-data_by_tracking_id-ka-225321-Data.db
Adding sstable ad_performance-data_by_tracking_id-ka-225116-Data.db
Adding sstable ad_performance-data_by_tracking_id-ka-225322-Data.db
com.datastax.driver.core.exceptions.InvalidQueryException: Cannot provide custom timestamp for counter updates
com.datastax.driver.core.exceptions.InvalidQueryException: Cannot provide custom timestamp for counter updates
com.datastax.driver.core.exceptions.InvalidQueryException: Cannot provide custom timestamp for counter updates
com.datastax.driver.core.exceptions.InvalidQueryException: Cannot provide custom timestamp for counter updates
com.datastax.driver.core.exceptions.InvalidQueryException: Cannot provide custom timestamp for counter updates
com.datastax.driver.core.exceptions.InvalidQueryException: Cannot provide custom timestamp for counter updates
com.datastax.driver.core.exceptions.InvalidQueryException: Cannot provide custom timestamp for counter updates
com.datastax.driver.core.exceptions.InvalidQueryException: Cannot provide custom timestamp for counter updates
com.datastax.driver.core.exceptions.InvalidQueryException: Cannot provide custom timestamp for counter updates
com.datastax.driver.core.exceptions.InvalidQueryException: Cannot provide custom timestamp for counter updates
com.datastax.driver.core.exceptions.InvalidQueryException: Cannot provide custom timestamp for counter updates
44070229 statements sent (in       11 batches,       11 failed).
```

`sstableloader --username scylla -nx -pw PASS --verbose -d 52.70.169.28 ad_performance/data_by_tracking_id-70c77e60660511e5853c37253ab0447b`

and 

`sstableloader --username scylla -nb -nx -pw PASS --verbose -d 52.70.169.28 ad_performance/data_by_tracking_id-70c77e60660511e5853c37253ab0447b`

Yield the errors below:

```
com.datastax.driver.core.exceptions.InvalidQueryException: Invalid amount of bind variables
```

**Comment by elcallio** [comment] 2019-02-06 21:55
Can you provide schema and at least one of the failing sstables?
Counter updates should go through wormholing to bypass the timestamp restriction. Here this is somehow not working, and I am somewhat at a loss without more info.

**Comment by gnumoreno** [comment] 2019-02-06 22:12
### Schema

```
CREATE KEYSPACE ad_performance WITH replication = {'class': 'NetworkTopologyStrategy', 'AWS_US_EAST_1': '3'}  AND durable_writes = true;

CREATE TABLE ad_performance.data_by_tracking_id (
    ad_buy_id bigint,
    date timestamp,
    tracking_id text,
    apvplays counter,
    clicks counter,
    cost counter,
    oapvplays counter,
    oclicks counter,
    ocost counter,
    orevenue counter,
    ovcompletions counter,
    oviews counter,
    ovplays counter,
    revenue counter,
    vcompletions counter,
    views counter,
    vplays counter,
    PRIMARY KEY (ad_buy_id, date, tracking_id)
) WITH CLUSTERING ORDER BY (date ASC, tracking_id ASC)
    AND bloom_filter_fp_chance = 0.01
    AND caching = '{"keys":"ALL", "rows_per_partition":"NONE"}'
    AND comment = ''
    AND compaction = {'class': 'org.apache.cassandra.db.compaction.SizeTieredCompactionStrategy'}
    AND compression = {'sstable_compression': 'org.apache.cassandra.io.compress.LZ4Compressor'}
    AND dclocal_read_repair_chance = 0.1
    AND default_time_to_live = 0
    AND gc_grace_seconds = 864000
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair_chance = 0.0
    AND speculative_retry = '99.0PERCENTILE';

CREATE TABLE ad_performance.data_by_phase_id (
    phase_id bigint,
    date timestamp,
    apvplays counter,
    clicks counter,
    revenue counter,
    vcompletions counter,
    views counter,
    vplays counter,
    PRIMARY KEY (phase_id, date)
) WITH CLUSTERING ORDER BY (date ASC)
    AND bloom_filter_fp_chance = 0.01
    AND caching = '{"keys":"ALL", "rows_per_partition":"NONE"}'
    AND comment = ''
    AND compaction = {'class': 'org.apache.cassandra.db.compaction.SizeTieredCompactionStrategy'}
    AND compression = {'sstable_compression': 'org.apache.cassandra.io.compress.LZ4Compressor'}
    AND dclocal_read_repair_chance = 0.1
    AND default_time_to_live = 0
    AND gc_grace_seconds = 864000
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair_chance = 0.0
    AND speculative_retry = '99.0PERCENTILE';

CREATE TABLE ad_performance.data_by_package_id (
    package_id bigint,
    date timestamp,
    apvplays counter,
    clicks counter,
    revenue counter,
    vcompletions counter,
    views counter,
    vplays counter,
    PRIMARY KEY (package_id, date)
) WITH CLUSTERING ORDER BY (date ASC)
    AND bloom_filter_fp_chance = 0.01
    AND caching = '{"keys":"ALL", "rows_per_partition":"NONE"}'
    AND comment = ''
    AND compaction = {'class': 'org.apache.cassandra.db.compaction.SizeTieredCompactionStrategy'}
    AND compression = {'sstable_compression': 'org.apache.cassandra.io.compress.LZ4Compressor'}
    AND dclocal_read_repair_chance = 0.1
    AND default_time_to_live = 0
    AND gc_grace_seconds = 864000
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair_chance = 0.0
    AND speculative_retry = '99.0PERCENTILE';

CREATE TABLE ad_performance.data_by_ad_buy_id (
    ad_buy_id bigint,
    date timestamp,
    apvplays counter,
    clicks counter,
    revenue counter,
    vcompletions counter,
    views counter,
    vplays counter,
    PRIMARY KEY (ad_buy_id, date)
) WITH CLUSTERING ORDER BY (date ASC)
    AND bloom_filter_fp_chance = 0.01
    AND caching = '{"keys":"ALL", "rows_per_partition":"NONE"}'
    AND comment = ''
    AND compaction = {'class': 'org.apache.cassandra.db.compaction.SizeTieredCompactionStrategy'}
    AND compression = {'sstable_compression': 'org.apache.cassandra.io.compress.LZ4Compressor'}
    AND dclocal_read_repair_chance = 0.1
    AND default_time_to_live = 0
    AND gc_grace_seconds = 864000
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair_chance = 0.0
    AND speculative_retry = '99.0PERCENTILE';
```

**Comment by gnumoreno** [comment] 2019-02-06 22:24
I sent it through e-mail due to data sensitivity concerns.

**Comment by penberg** [comment] 2019-02-07 07:46
The problem is that `sstableloader` attempts to use `USING TIMESTAMP` for an update with the counter data type, which is not allowed by the server. I am not sure why Scylla and Cassandra have this limitation, but one way to fix this is to teach `writeUsingTimestamp` to not use `USING TIMESTAMP` if one of the columns has the counter type.

/cc @pdziepak @elcallio

**Comment by elcallio** [comment] 2019-02-07 08:31
sstableloader must include the timestamp, otherwise the update would be broken (from the standpoint of serializing an sstable). However, since the counter update is done via a SCYLLA_COUNTER_UPDATE special cql extension, the statement processing should end up in the "special" cql op that is tagged as "raw counter update", which should be exempt from the "no timestamp" requirement. So again, the question is what exactly was generated here and how it did not end up in the "raw" path.

**Comment by slivne** [comment] 2019-02-10 11:24
@elcallio we do have some samples ... of the failure please ping me and I'll find you how to get access.

**Comment by elcallio** [comment] 2019-02-11 09:13
Unless I missed something we still don't have a sample failing sstable. I can try to populate a fake one, but my guess is that I will not manage to repro any issue.

**Comment by elcallio** [comment] 2019-02-11 13:32
Exactly which sstableloader and scylla were you running? (which branch/tag is the said repro above)?

I seem to be able to import the sstables just fine using master sstableloader + scylla...
It is of course slow as drowsy snails since we cannot batch counter updates etc, but is is so far chugging along. 

To be fair, I am not sure which patches ever made in into actual master, so I might be running with a number of submitted fixes never merged...

**Comment by elcallio** [comment] 2019-02-11 13:35
Or maybe I lied. Finally got the above error, 73k statements into the run... Will investigate again.

**Comment by elcallio** [comment] 2019-02-11 13:58
Ok, problem finally found. Unfortunately it is not an easy one to fix. 
The problem is that the sstable contains a tombstone (delete) for a row in the counter table. sstableloader creates a delete statement as expected. However, since the table is a counter table, we are not allowed to have the time stamp in the delete as we usually do. 
So, says the audience, why not just skip timestamp for all ops on counter tables? Why that would be great. If we could guarantee that we process all sstables to be imported and all their mutations in the order they where applied. But we cannot. In fact, our whole approach is quite dependent on being able to use the time stamps to deal with out-of-order mutations. 

I don't have an immediate solution here, but at least we know the problem now. It is counters, which are a pain in the rear cluster.

**Comment by elcallio** [comment] 2019-02-11 16:27
See scylladb/scylla-tools-java#83

**Comment by avikivity** [comment] 2019-02-11 16:31
We should just allow USING TIMESTAMP for counter deletes, since the information is recorded in the sstable even though it's a counter sstable.

**Comment by slivne** [comment] 2019-02-13 16:24
issue solved

**Closed by slivne** 2019-02-13 16:24 UTC
Labels: bug, counters, sstableloader
