### ISSUE TITLE
An unfinished skip() on socket can prevent Scylla from shutting down

### ISSUE THREAD

**Issue by nyh** [scylladb/scylla#8812] opened 2021-06-07 09:48 UTC
In issue #8798, @psarna reported that a mistakenly-huge `skip()` call on a connection's socket caused Scylla to be unable to cleanly shut down, because we wait for the `skip()` and it never finished.

However, in general, any `skip()` call, even a small one, may never finish: Even if Scylla is doing just `skip(5)`, a malicious, buggy or just very slow client may send just 4 bytes and then stop sending.

What we **want** to happen is that when Scylla shuts down it should close the connection sockets, and that should lead a waiting `skip()` call to abort immediately. Evidently, from #8798, this doesn't happen and we need to figure out why.

We should also check whether this problem is specific to `skip()` or other methods like `read_exactly()` have the same problem.

**Comment by psarna** [comment] 2021-06-08 08:31
I'll create a corresponding seastar issue, since I made a fairly small seastar reproducer

**Comment by psarna** [comment] 2021-06-08 08:48
I'm pretty sure I found the root cause - skipping from sockets actually reads from the underlying descriptor and subtracts the number of read bytes from the total number that needs to be skipped. However, the special case for reading from closed sockets is not handled, as we receive 0 bytes and fall into an infinite loop. The solution is to return once we read 0 bytes, since it indicates eof.

**Comment by nyh** [comment] 2021-06-08 10:40
> I'm pretty sure I found the root cause - skipping from sockets actually reads from the underlying descriptor and subtracts the number of read bytes from the total number that needs to be skipped. However, the special case for reading from closed sockets is not handled, as we receive 0 bytes and fall into an infinite loop. The solution is to return once we read 0 bytes, since it indicates eof.

Interesting - so not only the `skip()` never finishes, it also consumes all the CPU in an infinite loop? Oops.

**Comment by psarna** [comment] 2021-06-08 10:59
> > I'm pretty sure I found the root cause - skipping from sockets actually reads from the underlying descriptor and subtracts the number of read bytes from the total number that needs to be skipped. However, the special case for reading from closed sockets is not handled, as we receive 0 bytes and fall into an infinite loop. The solution is to return once we read 0 bytes, since it indicates eof.
> 
> Interesting - so not only the `skip()` never finishes, it also consumes all the CPU in an infinite loop? Oops.

It's a yielding loop, so at least it also allows other tasks to run in-between. But yes, it becomes the main consumer of CPU when the rest is idle.

**Comment by slivne** [comment] 2021-06-15 06:37
@psarna the seastar fix was merged to scylla in 6a8441ef034cf3c49386aa5a90528ff6a8d2cbdf - is there anything else needed or can we close

**Comment by psarna** [comment] 2021-06-15 06:52
https://github.com/scylladb/seastar/issues/910 is closed, so this one can be closed too. I tried to find other seastar primitives that could have the same problem, but it looks like skip() was the only faulty one.

**Closed by psarna** 2021-06-15 06:52 UTC
Labels: bug

**Comment by avikivity** [comment] 2021-06-15 11:15
Fixed by 6a8441ef034cf3c49386aa5a90528ff6a8d2cbdf.
