### ISSUE TITLE
collection indexing issue (bug)

### ISSUE THREAD

**Issue by LuaiKamel** [scylladb/scylla#3725] opened 2018-08-26 22:59 UTC
- [] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash): 2.3 AUG 26
Cluster size: 1 development node 
OS (RHEL/CentOS/Ubuntu/AWS AMI): FEDORA 28 

it seems there is a bug in Scylla secondary index, 
I created an INDEX on map<text, text> column, and then when I try to select by a key or value or even entire map it gave me an **NoHostAvailable:** and then the whole scylla stop working and had to restart it.. I tried all the options  with no matter how I create the index( entires, keys, values, full). 
then I tried it on ubuntu 18.04 and it didn't gave me any error or result just the whole system got frozen within a min due to memory leaks or cpu heavy load,

what should I do? I am designing a data model for a graph library and this is so important,
is there any plans to support map indexing by materialized views? 

Thank you

**Comment by tzach** [comment] 2018-08-27 06:06
@duarten ?

**Comment by nyh** [comment] 2018-08-27 07:06
Lack of support for indexing a collection column is unfortunately a known issue, this is a duplicate of #2962.
I wasn't aware until now that it causes a crash if attempted.

**Comment by duarten** [comment] 2018-08-27 18:12
We should at least fail gracefully if users try to index a non-frozen collection, instead of crashing randomly.

**Comment by LuaiKamel** [comment] 2018-08-28 03:09
whats about the secondary custom index (SASI) ? in Cassandra there is multi modes(PREFIX, CONTAIN, SPARSE) which provide full text searching for index column, is there any plans to support this feature as well? [http://www.doanduyhai.com/blog/?p=2058#what_is_sasi](url)

**Comment by duarten** [comment] 2018-10-08 12:06
We don't have plans to support SASI in the short term.

Indexes can't be built on top of MV (because indexes are MVs), but it should be possible to index any partition key column.

**Comment by duarten** [comment] 2018-10-08 12:08
https://github.com/scylladb/scylla/commit/2d355bdf47b49820ef1c235ce3254fc15b5a354d fixed the crash and both #3654 and #2962 are being used to track support for indexing collections.

**Closed by duarten** 2018-10-08 12:08 UTC
Labels: sec-index
