### ISSUE TITLE
scyllatop stops when running c-s

### ISSUE THREAD

**Issue by nirmaayan** [scylladb/scylla#1287] opened 2016-05-24 14:08 UTC
## Installation details
Scylla version (or git commit hash): 1.1
Cluster size: 3 nodes
OS (RHEL/CentOS/Ubuntu/AWS AMI): centos 7.2

## Hardware details (for performance issues)
EC2
i2.8xlarge

Scenario:
Run C* stress
After 5-6 minutes the error message below appears

ip-172-30-0-20/transport-0/total_requests-requests_served(1)      avg[31.0] tot[31.0]
ip-172-30-0-20/transport-1/total_requests-requests_served(1)  avg[1267.7] tot[1267.7]
ip-172-30-0-20/transport-10/total_requests-requests_served(1) avg[1444.7] tot[1444.7]
ip-172-30-0-20/transport-11/total_requests-requests_served(1)   avg[587.0] tot[587.0]
ip-172-30-0-20/transport-12/total_requests-requests_served(1)       avg[0.0] tot[0.0]
ip-172-30-0-20/transport-13/total_requests-requests_served(1)   avg[463.7] tot[463.7]
ip-172-30-0-20/transport-14/total_requests-requests_served(1)       avg[0.0] tot[0.0]
ip-172-30-0-20/transport-15/total_requests-requests_served(1)       avg[0.0] tot[0.0]
ip-172-30-0-20/transport-16/total_requests-requests_served(1)       avg[0.0] tot[0.0]
ip-172-30-0-20/transport-17/total_requests-requests_served(1)       avg[0.0] tot[0.0]
ip-172-30-0-20/transport-18/total_requests-requests_served(1)       avg[0.0] tot[0.0]
ip-172-30-0-20/transport-19/total_requests-requests_served(1)       avg[0.0] tot[0.0]
ip-172-30-0-20/transport-2/total_requests-requests_served(1)  avg[1173.3] tot[1173.3]
ip-172-30-0-20/transport-20/total_requests-requests_served(1)   avg[948.0] tot[948.0]
ip-172-30-0-20/transport-21/total_requests-requests_served(1) avg[1204.0] tot[1204.0]
ip-172-30-0-20/transport-22/total_requests-requests_served(1) avg[1359.3] tot[1359.3]
ip-172-30-0-20/transport-23/total_requests-requests_served(1) avg[1008.7] tot[1008.7]
ip-172-30-0-20/transport-24/total_requests-requests_served(1) avg[1366.7] tot[1366.7]
ip-172-30-0-20/transport-25/total_requests-requests_served(1)     avg[10.7] tot[10.7]
ip-172-30-0-20/transport-26/total_requests-requests_served(1)   avg[417.3] tot[417.3]
ip-172-30-0-20/transport-27/total_requests-requests_served(1)   avg[424.7] tot[424.7]
ip-172-30-0-20/transport-28/total_requests-requests_served(1) avg[1855.0] tot[1855.0]
ip-172-30-0-20/transport-29/total_requests-requests_served(1)   avg[466.7] tot[466.7]
ip-172-30-0-20/transport-3/total_requests-requests_served(1)  avg[1148.3] tot[1148.3]
ip-172-30-0-20/transport-30/total_requests-requests_served(1)   avg[920.7] tot[920.7]
ip-172-30-0-20/transport-31/total_requests-requests_served(1) avg[1203.0] tot[1203.0]
ip-172-30-0-20/transport-4/total_requests-requests_served(1)  avg[1792.0] tot[1792.0]
ip-172-30-0-20/transport-5/total_requests-requests_served(1)  avg[1160.3] tot[1160.3]
ip-172-30-0-20/transport-6/total_requests-requests_served(1)  avg[1537.3] tot[1537.3]
ip-172-30-0-20/transport-7/total_requests-requests_served(1)  avg[1273.0] tot[1273.0]
ip-172-30-0-20/transport-8/total_requests-requests_served(1)  avg[1695.0] tot[1695.0]
ip-172-30-0-20/transport-9/total_requests-requests_served(1)  avg[1479.0] tot[1479.0]
ing metric ip-172-30-0-20/transport-0/total_requests-requests_served:{'value': 'NaN'}000e+00'}

Traceback (most recent call last):ll last):
File "/usr/lib/scylla/scyllatop/livedata.py", line 58, in _updaten _update
metric.update().update()
File "/usr/lib/scylla/scyllatop/metric.py", line 25, in updatein update
response = self._collectd.query('GETVAL "{metric}"'.format(metric=self._symbol))_symbol))
File "/usr/lib/scylla/scyllatop/collectd.py", line 37, in query in query
return self._readLines()adLines() File "/usr/lib/scylla/scyllatop/collectd.py", line 48, in _readLinesreadLines
raise parseexception.ParseException('could not parse first line of response from collectd: {0}'.format(line))at(line))
ParseException: could not parse first line of response from collectd: -1 No such valueuch value

**Comment by haarcuba** [comment] 2016-05-24 17:55
@slivne  what was the cassandra-stress command line exactly?
could you try to reproduce this with scyllatop -v DEBUG and attach scyllatop.log?

**Comment by slivne** [comment] 2016-05-24 20:07
*  @nirmaayan can you please provide the info**
<https://github.com/nirmaayan>*

**Comment by nirmaayan** [comment] 2016-05-25 05:10
@haarcuba 
[scyllatop.txt](https://github.com/scylladb/scylla/files/281022/scyllatop.txt)

**Comment by haarcuba** [comment] 2016-05-25 12:14
found the root cause: for some reason, collectd reports that it does not have this metric after a while, even though it did have this metric to begin with.
scyllatop assumes that if a metric is present once, it will always be present - but apparently this is wrong.
I'll write a patch to deal with absentee metrics.

**Comment by slivne** [comment] 2016-06-06 13:40
ping ? any update ?

**Comment by haarcuba** [comment] 2016-06-07 12:25
patch submitted

**Comment by slivne** [comment] 2016-06-07 12:30
can you check if its merged - and if so include the commit id - if not can
you ping on the patch

**Closed** 2016-06-08 13:36 UTC
Labels: bug
