### ISSUE TITLE
Asynchronous global read repair

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylla#1276] opened 2016-05-19 13:44 UTC
*Installation details*
Scylla version (or git commit hash): 4eff07d773da5f2924165550f3a400163696c823

When non-dclocal read_repair is enabled, a LOCAL_QUORUM read can return with global latencies, as data needs to be fetched and then rewritten to all replicas, including those in remote data centers.  This defeats the purpose of LOCAL_QUORUM reads -- low latency.

We can fix that by introducing an intermediate read repair mode.  In this mode, replicas in the local data center are repaired synchronously, preserving the monotonic read guarantee, while non-local replicas are repaired asynchronously.

Applications could see non-monotonic reads if they communicate across data centers, but we already can't guarantee this if they use LOCAL_QUORUM anyway.

**Comment by slivne** [comment] 2016-05-19 13:49
duplicate of #1250 ?

**Comment by avikivity** [comment] 2016-05-19 13:50
They do seem similar

**Closed** 2016-06-07 09:39 UTC
