### ISSUE TITLE
Even after large row/cell/partition is expired (TTL'ed), it still being shown in system.large_cell/row/partition

### ISSUE THREAD

**Issue by fgelcer** [scylladb/scylla#4805] opened 2019-08-05 13:52 UTC
my scenario is:

1. create a cluster
2. create a table
3. add data to the table, that will trigger large entity alerts (on log and on system.large_<entity> table)
4. run compaction by writing few data + flush few times
5. check the expected alerts were triggered
6. update one or few entities with TTL, and wait for its time to expire
7. run compaction by writing few data + flush few times
8. check the expected alerts

at step 8, i can observe that the table succeeded to remove the partition or cell/row, but the system.large_<entity> table still have the entries for the previous alert.
Shall i expect the system table to clean its entries when the data does not exist in the table itself?

**Comment by fgelcer** [comment] 2019-08-05 13:52
@roydahan

**Comment by fgelcer** [comment] 2019-08-05 13:53
@slivne

**Comment by roydahan** [comment] 2019-08-05 17:13
@fgelcer what happens in a similar scenario, but instead of TTL'ed row, you delete the row?
Is it still being shown in that table?

**Comment by fgelcer** [comment] 2019-08-06 13:14
Never tested it. I will test it manually, and shall add a test for it.

**Comment by bhalevy** [comment] 2019-08-06 13:26
The record is deleted from the system table only when the sstable holding the large cell/row/partition is deleted from storage.  How exactly do you trigger compaction?
It will be best to have a reproducer in the form of a dtest.

**Comment by slivne** [comment] 2019-08-08 09:52
We can mark the large partition/ cell info with TTL of the data - so if the user queries a partition / cell he will find them and not get they don't exist.

**Comment by bhalevy** [comment] 2019-08-08 12:17
On Thu, 2019-08-08 at 02:52 -0700, Shlomi Livne wrote:
> We can mark the large partition/ cell info with TTL of the data - so if the user queries a partition / cell he will find them and not get they don't exist.
> 

I think that's wrong since if the large data is still stored in a sstable somewhere it will still affect performance and we *do* want to know it's still there, not pretend it's not.
> [
> {
> "@context": "http://schema.org",
> "@type": "EmailMessage",
> "potentialAction": {
> "@type": "ViewAction",
> "target": "
> https://github.com/scylladb/scylla/issues/4805?email_source=notifications\u0026email_token=AE7RGODA2M3JDKLRQPJZC53QDPUGFA5CNFSM4IJLN7M2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD33DDQA#issuecomment-519451072
> ",
> "url": "
> https://github.com/scylladb/scylla/issues/4805?email_source=notifications\u0026email_token=AE7RGODA2M3JDKLRQPJZC53QDPUGFA5CNFSM4IJLN7M2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD33DDQA#issuecomment-519451072
> ",
> "name": "View Issue"
> },
> "description": "View this Issue on GitHub",
> "publisher": {
> "@type": "Organization",
> "name": "GitHub",
> "url": "https://github.com"
> }
> }
> ]

**Comment by glommer** [comment] 2019-08-08 13:04
Agreed with Benny.

Also think about the situation in which the user does an RMW and updates
just the TTL with a new write.

We would still have the partition on disk but it would no longer show up
until it is flushed out.

Of course, at this point it is technically a different partition, but it is
the same key. The way users use this table is by looking and saying "there
is something wrong with the data pointed to by this key, let me look into
it"

I view this as a bloom filter : I would rather have a false positive (data
is gone but table not yet updated) than a false negative

**Comment by espindola** [comment] 2019-08-16 20:46
I think we can guarantee no false positives with the definition Benny wrote: If the sstable is still on the disk, we should report it.

Note that the large_* tables include a sstable_name, so you can check if the table is still on disk (if it is gone, this is a real bug).

**Comment by bhalevy** [comment] 2019-10-31 12:10
Closing as invalid...

**Closed by bhalevy** 2019-10-31 12:10 UTC
Labels: enhancement
