### ISSUE TITLE
Scylla process refuses to exit: Network is unreachable

### ISSUE THREAD

**Issue by ShlomiBalalis** [scylladb/scylla#6972] opened 2020-08-04 11:25 UTC
*Installation details*
Scylla version (or git commit hash):666.development-0.20200727.a7df8486b with build-id ce64d8221eea00df25582ee16c87c0c0e8eed4e1
Cluster size: 4
OS (RHEL/CentOS/Ubuntu/AWS AMI): ami-0621715fb9a5e4fda (Ireland)
Instance Type: i3.4xlarge

Test ID: 0560b629-392e-48f8-a0ce-5a05f8f7f48a

During the 200gb-48h longevity, a soft reboot nemesis has started on node#5 at `2020-08-04 01:55:58.365`:
```
< t:2020-08-04 01:55:58,424 f:remote_base.py  l:510  c:RemoteCmdRunner      p:DEBUG > Running command "sudo reboot"...
```

At first, the shutdown process started normally, but when the scylla process started exiting, the process halted the shutdown process for almost 15 minutes, before systemd forcefully killed it after the timeout has been reached:
```
2020-08-04T01:55:58+00:00  longevity-200gb-48h-verify-limited--db-node-0560b629-5 !INFO    | scylla: [shard 0] compaction_manager - Asked to stop
2020-08-04T01:55:58+00:00  longevity-200gb-48h-verify-limited--db-node-0560b629-5 !NOTICE  | systemd: scylla-jmx.service: main process exited, code=exited, status=143/n/a
2020-08-04T01:55:58+00:00  longevity-200gb-48h-verify-limited--db-node-0560b629-5 !INFO    | scylla: [shard 0] compaction_manager - Stopping 0 ongoing compactions
2020-08-04T01:55:58+00:00  longevity-200gb-48h-verify-limited--db-node-0560b629-5 !INFO    | systemd: Stopped Scylla JMX.
2020-08-04T01:55:58+00:00  longevity-200gb-48h-verify-limited--db-node-0560b629-5 !INFO    | scylla: [shard 0] init - Signal received; shutting down
2020-08-04T01:55:58+00:00  longevity-200gb-48h-verify-limited--db-node-0560b629-5 !NOTICE  | systemd: Unit scylla-jmx.service entered failed state.
2020-08-04T01:55:58+00:00  longevity-200gb-48h-verify-limited--db-node-0560b629-5 !INFO    | scylla: [shard 0] init - Shutting down redis service
2020-08-04T01:55:58+00:00  longevity-200gb-48h-verify-limited--db-node-0560b629-5 !WARNING | systemd: scylla-jmx.service failed.
2020-08-04T01:55:58+00:00  longevity-200gb-48h-verify-limited--db-node-0560b629-5 !INFO    | scylla: [shard 0] init - Shutting down redis service was successful
2020-08-04T01:55:58+00:00  longevity-200gb-48h-verify-limited--db-node-0560b629-5 !INFO    | systemd: Stopping Scylla Server...
2020-08-04T01:55:58+00:00  longevity-200gb-48h-verify-limited--db-node-0560b629-5 !INFO    | scylla: [shard 0] init - Shutting down view builder
2020-08-04T01:55:58+00:00  longevity-200gb-48h-verify-limited--db-node-0560b629-5 !INFO    | scylla: [shard 0] view - Stopping view builder
2020-08-04T01:55:58+00:00  longevity-200gb-48h-verify-limited--db-node-0560b629-5 !INFO    | scylla: [shard 0] compaction_manager - Stopped
2020-08-04T01:55:58+00:00  longevity-200gb-48h-verify-limited--db-node-0560b629-5 !INFO    | scylla: [shard 1] compaction_manager - Asked to stop
2020-08-04T01:55:58+00:00  longevity-200gb-48h-verify-limited--db-node-0560b629-5 !INFO    | scylla: [shard 4] compaction_manager - Asked to stop
...
2020-08-04T01:56:20+00:00  longevity-200gb-48h-verify-limited--db-node-0560b629-5 !INFO    | scylla: [shard 0] gossip - InetAddress 10.0.1.118 is now DOWN, status = NORMAL
2020-08-04T01:56:21+00:00  longevity-200gb-48h-verify-limited--db-node-0560b629-5 !INFO    | scylla: [shard 0] gossip - InetAddress 10.0.0.220 is now DOWN, status = NORMAL
2020-08-04T01:56:22+00:00  longevity-200gb-48h-verify-limited--db-node-0560b629-5 !ERR     | scylla: [shard 0] rpc - client 10.0.0.220:7001: fail to connect: connect: Network is unreachable
2020-08-04T01:56:22+00:00  longevity-200gb-48h-verify-limited--db-node-0560b629-5 !INFO    | scylla: [shard 0] gossip - InetAddress 10.0.3.135 is now DOWN, status = NORMAL
2020-08-04T01:56:23+00:00  longevity-200gb-48h-verify-limited--db-node-0560b629-5 !ERR     | scylla: [shard 0] rpc - client 10.0.0.220:7001: fail to connect: connect: Network is unreachable
2020-08-04T01:56:23+00:00  longevity-200gb-48h-verify-limited--db-node-0560b629-5 !ERR     | scylla: [shard 0] rpc - client 10.0.0.220:7001: fail to connect: connect: Network is unreachable
2020-08-04T01:56:24+00:00  longevity-200gb-48h-verify-limited--db-node-0560b629-5 !ERR     | scylla: [shard 0] rpc - client 10.0.1.118:7001: fail to connect: connect: Network is unreachable
2020-08-04T01:56:24+00:00  longevity-200gb-48h-verify-limited--db-node-0560b629-5 !ERR     | scylla: [shard 0] rpc - client 10.0.0.220:7001: fail to connect: connect: Network is unreachable
2020-08-04T01:56:25+00:00  longevity-200gb-48h-verify-limited--db-node-0560b629-5 !ERR     | scylla: [shard 0] rpc - client 10.0.1.118:7001: fail to connect: connect: Network is unreachable
2020-08-04T01:56:25+00:00  longevity-200gb-48h-verify-limited--db-node-0560b629-5 !ERR     | scylla: [shard 0] rpc - client 10.0.0.220:7001: fail to connect: connect: Network is unreachable
2020-08-04T01:56:26+00:00  longevity-200gb-48h-verify-limited--db-node-0560b629-5 !ERR     | scylla: [shard 0] rpc - client 10.0.0.220:7001: fail to connect: connect: Network is unreachable
2020-08-04T01:56:26+00:00  longevity-200gb-48h-verify-limited--db-node-0560b629-5 !ERR     | scylla: [shard 0] rpc - client 10.0.0.220:7001: fail to connect: connect: Network is unreachable
2020-08-04T01:56:27+00:00  longevity-200gb-48h-verify-limited--db-node-0560b629-5 !ERR     | scylla: [shard 0] rpc - client 10.0.0.220:7001: fail to connect: connect: Network is unreachable
2020-08-04T01:56:27+00:00  longevity-200gb-48h-verify-limited--db-node-0560b629-5 !ERR     | scylla: [shard 0] rpc - client 10.0.0.220:7001: fail to connect: connect: Network is unreachable
2020-08-04T01:56:28+00:00  longevity-200gb-48h-verify-limited--db-node-0560b629-5 !ERR     | scylla: [shard 0] rpc - client 10.0.1.118:7001: fail to connect: connect: Network is unreachable
2020-08-04T01:56:28+00:00  longevity-200gb-48h-verify-limited--db-node-0560b629-5 !ERR     | scylla: [shard 0] rpc - client 10.0.0.220:7001: fail to connect: connect: Network is unreachable
2020-08-04T01:56:29+00:00  longevity-200gb-48h-verify-limited--db-node-0560b629-5 !ERR     | scylla: [shard 0] rpc - client 10.0.3.135:7001: fail to connect: connect: Network is unreachable
2020-08-04T01:56:29+00:00  longevity-200gb-48h-verify-limited--db-node-0560b629-5 !ERR     | scylla: [shard 0] rpc - client 10.0.0.220:7001: fail to connect: connect: Network is unreachable
2020-08-04T01:56:30+00:00  longevity-200gb-48h-verify-limited--db-node-0560b629-5 !ERR     | scylla: [shard 0] rpc - client 10.0.0.220:7001: fail to connect: connect: Network is unreachable
2020-08-04T01:56:30+00:00  longevity-200gb-48h-verify-limited--db-node-0560b629-5 !ERR     | scylla: [shard 0] rpc - client 10.0.0.220:7001: fail to connect: connect: Network is unreachable
2020-08-04T01:56:31+00:00  longevity-200gb-48h-verify-limited--db-node-0560b629-5 !ERR     | scylla: [shard 0] rpc - client 10.0.3.135:7001: fail to connect: connect: Network is unreachable
...
2020-08-04T02:10:57+00:00  longevity-200gb-48h-verify-limited--db-node-0560b629-5 !ERR     | scylla: [shard 0] rpc - client 10.0.3.135:7001: fail to connect: connect: Network is unreachable
2020-08-04T02:10:57+00:00  longevity-200gb-48h-verify-limited--db-node-0560b629-5 !ERR     | scylla: [shard 0] rpc - client 10.0.0.220:7001: fail to connect: connect: Network is unreachable
2020-08-04T02:10:58+00:00  longevity-200gb-48h-verify-limited--db-node-0560b629-5 !ERR     | scylla: [shard 0] rpc - client 10.0.1.118:7001: fail to connect: connect: Network is unreachable
2020-08-04T02:10:58+00:00  longevity-200gb-48h-verify-limited--db-node-0560b629-5 !ERR     | scylla: [shard 0] rpc - client 10.0.0.220:7001: fail to connect: connect: Network is unreachable
2020-08-04T02:10:59+00:00  longevity-200gb-48h-verify-limited--db-node-0560b629-5 !WARNING | systemd: scylla-server.service stop-sigterm timed out. Killing.
2020-08-04T02:11:52+00:00  longevity-200gb-48h-verify-limited--db-node-0560b629-5 !NOTICE  | systemd: scylla-server.service: main process exited, code=killed, status=9/KILL
2020-08-04T02:11:52+00:00  longevity-200gb-48h-verify-limited--db-node-0560b629-5 !INFO    | systemd: Stopped Scylla Server.
```

At first, it seems that node#5 assumes the other nodes have reached DN status, even though, when looking at the other nodes' logs, they all seem alive and well. Plus, nodetool status from `2020-08-04 02:05:19,053` confirms that only node#5 is in a problematic state:
```
Datacenter: eu-west
===================
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address     Load       Tokens       Owns    Host ID                               Rack
UN  10.0.1.118  316.86 GB  256          ?       b9849aae-16f3-416c-887e-961d2e290870  1a
UN  10.0.3.135  332.37 GB  256          ?       30ac90e7-f098-48c0-ab23-a797c2615179  1a
DN  10.0.3.123  314.42 GB  256          ?       2f7cebff-8f48-4774-94a5-2204d6cf30ca  1a
UN  10.0.0.220  349.28 GB  256          ?       0c83b02a-2644-48e5-ba27-5cfe4777d2f9  1a
```

After systemd forcefully shuts down the scylla process, and the instance finally restarts, scylla starts again with no issue:
```
2020-08-04T02:12:34+00:00  longevity-200gb-48h-verify-limited--db-node-0560b629-5 !INFO    | scylla: Scylla version 666.development-0.20200727.a7df8486b with build-id ce64d8221eea00df25582ee16c87c0c0e8eed4e1 starting ...
...
2020-08-04T02:14:25+00:00  longevity-200gb-48h-verify-limited--db-node-0560b629-5 !INFO    | scylla: [shard 0] init - Scylla version 666.development-0.20200727.a7df8486b initialization completed.
```

**Comment by avikivity** [comment] 2020-08-04 12:24
We need to change s-c-t to override scylla-server.service FinalKillSignal to SIGABRT so we can get a core in such cases. It won't be possible to debug it from the core.

It looks like a compaction_manager problem. /cc @bhalevy @raphaelsc

**Comment by ShlomiBalalis** [comment] 2020-08-04 12:27
@avikivity  I left the node alive - 54.217.46.170 - Is there any benefit to studying it or can I kill it?
There was a problem uploading the logs, I'll upload them shortly

**Comment by raphaelsc** [comment] 2020-08-04 12:33
> We need to change s-c-t to override scylla-server.service FinalKillSignal to SIGABRT so we can get a core in such cases. It won't be possible to debug it from the core.
> 
> It looks like a compaction_manager problem. /cc @bhalevy @raphaelsc

It may be a regression caused by https://github.com/scylladb/scylla/commit/b155eef72662363b5ab7badfb5aeed4b4e51776

**Comment by raphaelsc** [comment] 2020-08-04 12:39
> @avikivity I left the node alive - 54.217.46.170 - Is there any benefit to studying it or can I kill it?
> There was a problem uploading the logs, I'll upload them shortly

thanks I will really need the logs for investigating this.

**Comment by ShlomiBalalis** [comment] 2020-08-04 12:47
Logs:
```
+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                                                                                                 Log links for testrun with test id 0560b629-392e-48f8-a0ce-5a05f8f7f48a                                                                                                 |
+-----------------+------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Date            | Log type   | Link                                                                                                                                                                                                                                     |
+-----------------+------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 20190101_010101 | prometheus | https://cloudius-jenkins-test.s3.amazonaws.com/0560b629-392e-48f8-a0ce-5a05f8f7f48a/prometheus_snapshot_20200804_022656.tar.gz                                                                                                           |
| 20200804_021354 | grafana    | https://cloudius-jenkins-test.s3.amazonaws.com/0560b629-392e-48f8-a0ce-5a05f8f7f48a/20200804_021354/grafana-screenshot-overview-20200804_021354-longevity-200gb-48h-verify-limited--monitor-node-0560b629-1.png                          |
| 20200804_021354 | grafana    | https://cloudius-jenkins-test.s3.amazonaws.com/0560b629-392e-48f8-a0ce-5a05f8f7f48a/20200804_021354/grafana-screenshot-scylla-per-server-metrics-nemesis-20200804_021741-longevity-200gb-48h-verify-limited--monitor-node-0560b629-1.png |
+-----------------+------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
```

The rest of the logs, of c-s and logs, are uploaded to scratch.scylladb.com/200gb_0408

**Comment by ShlomiBalalis** [comment] 2020-08-04 12:47
> > @avikivity I left the node alive - 54.217.46.170 - Is there any benefit to studying it or can I kill it?
> > There was a problem uploading the logs, I'll upload them shortly
> 
> thanks I will really need the logs for investigating this.

What about the node itself? Would you need it?

**Comment by raphaelsc** [comment] 2020-08-04 12:48
> > > @avikivity I left the node alive - 54.217.46.170 - Is there any benefit to studying it or can I kill it?
> > > There was a problem uploading the logs, I'll upload them shortly
> > 
> > 
> > thanks I will really need the logs for investigating this.
> 
> What about the node itself? Would you need it?

as far as i can tell no.

**Comment by raphaelsc** [comment] 2020-08-04 13:07
@avikivity 

Compaction manager took no more than 1 second to stop, so I don't think it's compaction manager related.

```
$ cat node5_shutdown_log.txt | grep "compaction_manager"
2020-08-04T01:55:58+00:00  longevity-200gb-48h-verify-limited--db-node-0560b629-5 !INFO    | scylla: [shard 0] compaction_manager - Asked to stop
2020-08-04T01:55:58+00:00  longevity-200gb-48h-verify-limited--db-node-0560b629-5 !INFO    | scylla: [shard 0] compaction_manager - Stopping 0 ongoing compactions
2020-08-04T01:55:58+00:00  longevity-200gb-48h-verify-limited--db-node-0560b629-5 !INFO    | scylla: [shard 0] compaction_manager - Stopped
2020-08-04T01:55:58+00:00  longevity-200gb-48h-verify-limited--db-node-0560b629-5 !INFO    | scylla: [shard 1] compaction_manager - Asked to stop
2020-08-04T01:55:58+00:00  longevity-200gb-48h-verify-limited--db-node-0560b629-5 !INFO    | scylla: [shard 4] compaction_manager - Asked to stop
2020-08-04T01:55:58+00:00  longevity-200gb-48h-verify-limited--db-node-0560b629-5 !INFO    | scylla: [shard 5] compaction_manager - Asked to stop
2020-08-04T01:55:58+00:00  longevity-200gb-48h-verify-limited--db-node-0560b629-5 !INFO    | scylla: [shard 7] compaction_manager - Asked to stop
2020-08-04T01:55:58+00:00  longevity-200gb-48h-verify-limited--db-node-0560b629-5 !INFO    | scylla: [shard 9] compaction_manager - Asked to stop
2020-08-04T01:55:58+00:00  longevity-200gb-48h-verify-limited--db-node-0560b629-5 !INFO    | scylla: [shard 3] compaction_manager - Asked to stop
2020-08-04T01:55:58+00:00  longevity-200gb-48h-verify-limited--db-node-0560b629-5 !INFO    | scylla: [shard 10] compaction_manager - Asked to stop
2020-08-04T01:55:58+00:00  longevity-200gb-48h-verify-limited--db-node-0560b629-5 !INFO    | scylla: [shard 9] compaction_manager - Stopping 0 ongoing compactions
2020-08-04T01:55:58+00:00  longevity-200gb-48h-verify-limited--db-node-0560b629-5 !INFO    | scylla: [shard 8] compaction_manager - Asked to stop
2020-08-04T01:55:58+00:00  longevity-200gb-48h-verify-limited--db-node-0560b629-5 !INFO    | scylla: [shard 1] compaction_manager - Stopping 0 ongoing compactions
2020-08-04T01:55:58+00:00  longevity-200gb-48h-verify-limited--db-node-0560b629-5 !INFO    | scylla: [shard 3] compaction_manager - Stopping 0 ongoing compactions
2020-08-04T01:55:58+00:00  longevity-200gb-48h-verify-limited--db-node-0560b629-5 !INFO    | scylla: [shard 7] compaction_manager - Stopping 0 ongoing compactions
2020-08-04T01:55:58+00:00  longevity-200gb-48h-verify-limited--db-node-0560b629-5 !INFO    | scylla: [shard 6] compaction_manager - Asked to stop
2020-08-04T01:55:58+00:00  longevity-200gb-48h-verify-limited--db-node-0560b629-5 !INFO    | scylla: [shard 2] compaction_manager - Asked to stop
2020-08-04T01:55:58+00:00  longevity-200gb-48h-verify-limited--db-node-0560b629-5 !INFO    | scylla: [shard 10] compaction_manager - Stopping 0 ongoing compactions
2020-08-04T01:55:58+00:00  longevity-200gb-48h-verify-limited--db-node-0560b629-5 !INFO    | scylla: [shard 12] compaction_manager - Asked to stop
2020-08-04T01:55:58+00:00  longevity-200gb-48h-verify-limited--db-node-0560b629-5 !INFO    | scylla: [shard 6] compaction_manager - Stopping 0 ongoing compactions
2020-08-04T01:55:58+00:00  longevity-200gb-48h-verify-limited--db-node-0560b629-5 !INFO    | scylla: [shard 7] compaction_manager - Stopped
2020-08-04T01:55:58+00:00  longevity-200gb-48h-verify-limited--db-node-0560b629-5 !INFO    | scylla: [shard 10] compaction_manager - Stopped
2020-08-04T01:55:58+00:00  longevity-200gb-48h-verify-limited--db-node-0560b629-5 !INFO    | scylla: [shard 2] compaction_manager - Stopping 0 ongoing compactions
2020-08-04T01:55:58+00:00  longevity-200gb-48h-verify-limited--db-node-0560b629-5 !INFO    | scylla: [shard 1] compaction_manager - Stopped
2020-08-04T01:55:58+00:00  longevity-200gb-48h-verify-limited--db-node-0560b629-5 !INFO    | scylla: [shard 5] compaction_manager - Stopping 0 ongoing compactions
2020-08-04T01:55:58+00:00  longevity-200gb-48h-verify-limited--db-node-0560b629-5 !INFO    | scylla: [shard 3] compaction_manager - Stopped
2020-08-04T01:55:58+00:00  longevity-200gb-48h-verify-limited--db-node-0560b629-5 !INFO    | scylla: [shard 6] compaction_manager - Stopped
2020-08-04T01:55:58+00:00  longevity-200gb-48h-verify-limited--db-node-0560b629-5 !INFO    | scylla: [shard 8] compaction_manager - Stopping 0 ongoing compactions
2020-08-04T01:55:58+00:00  longevity-200gb-48h-verify-limited--db-node-0560b629-5 !INFO    | scylla: [shard 8] compaction_manager - Stopped
2020-08-04T01:55:58+00:00  longevity-200gb-48h-verify-limited--db-node-0560b629-5 !INFO    | scylla: [shard 12] compaction_manager - Stopping 0 ongoing compactions
2020-08-04T01:55:58+00:00  longevity-200gb-48h-verify-limited--db-node-0560b629-5 !INFO    | scylla: [shard 9] compaction_manager - Stopped
2020-08-04T01:55:58+00:00  longevity-200gb-48h-verify-limited--db-node-0560b629-5 !INFO    | scylla: [shard 12] compaction_manager - Stopped
2020-08-04T01:55:58+00:00  longevity-200gb-48h-verify-limited--db-node-0560b629-5 !INFO    | scylla: [shard 5] compaction_manager - Stopped
2020-08-04T01:55:58+00:00  longevity-200gb-48h-verify-limited--db-node-0560b629-5 !INFO    | scylla: [shard 4] compaction_manager - Stopping 0 ongoing compactions
2020-08-04T01:55:58+00:00  longevity-200gb-48h-verify-limited--db-node-0560b629-5 !INFO    | scylla: [shard 4] compaction_manager - Stopped
2020-08-04T01:55:58+00:00  longevity-200gb-48h-verify-limited--db-node-0560b629-5 !INFO    | scylla: [shard 2] compaction_manager - Stopped
2020-08-04T01:55:58+00:00  longevity-200gb-48h-verify-limited--db-node-0560b629-5 !INFO    | scylla: [shard 11] compaction_manager - Asked to stop
2020-08-04T01:55:58+00:00  longevity-200gb-48h-verify-limited--db-node-0560b629-5 !INFO    | scylla: [shard 11] compaction_manager - Stopping 0 ongoing compactions
2020-08-04T01:55:58+00:00  longevity-200gb-48h-verify-limited--db-node-0560b629-5 !INFO    | scylla: [shard 11] compaction_manager - Stopped
2020-08-04T01:55:58+00:00  longevity-200gb-48h-verify-limited--db-node-0560b629-5 !INFO    | scylla: [shard 13] compaction_manager - Asked to stop
2020-08-04T01:55:58+00:00  longevity-200gb-48h-verify-limited--db-node-0560b629-5 !INFO    | scylla: [shard 13] compaction_manager - Stopping 0 ongoing compactions
2020-08-04T01:55:58+00:00  longevity-200gb-48h-verify-limited--db-node-0560b629-5 !INFO    | scylla: [shard 13] compaction_manager - Stopped
[raphaelsc@localhost db-logs]$ cat node5_shutdown_log.txt | grep "compaction_manager - Asked" | wc -l
14
[raphaelsc@localhost db-logs]$ cat node5_shutdown_log.txt | grep "compaction_manager - Stopped" | wc -l
14

```

**Comment by raphaelsc** [comment] 2020-08-04 13:12
The problem seems that Scylla is repeatedly trying the following until the shutdown process times out:
2020-08-04T02:10:58+00:00  longevity-200gb-48h-verify-limited--db-node-0560b629-5 !ERR     | scylla: [shard 0] rpc - client 10.0.0.220:7001: fail to connect: connect: Network is unreachable

**Comment by avikivity** [comment] 2020-08-04 15:08
I don't know if that's the problem or just something that happens while waiting for something else to shut down.

**Comment by raphaelsc** [comment] 2020-08-04 17:44
@ShlomiBalalis please rename the issue, the problem is not compaction_manager related, as you can see in my comment above.

**Comment by slivne** [comment] 2020-08-06 09:47
@roydahan https://github.com/scylladb/scylla/issues/6972#issuecomment-668564001 we need this assigned we will not be able to figure this out without additional info.

**Comment by bhalevy** [comment] 2020-11-03 11:17
Wasn't reproduced for a long time, removing `high` label...

**Comment by slivne** [comment] 2021-03-29 07:52
closing this issue - if we hit this again - please provide the needed info and we can reopen and fix

**Closed by slivne** 2021-03-29 07:52 UTC
Labels: bug
