### ISSUE TITLE
Error applying view update (unstarted write cancelled) after soft reboot node

### ISSUE THREAD

**Issue by yarongilor** [scylladb/scylla#5085] opened 2019-09-23 09:45 UTC
Installation details
Scylla version (or git commit hash): 3.1.0.rc7-0.20190915.024d1563a
Cluster size: 6
OS (RHEL/CentOS/Ubuntu/AWS AMI): ami-0a01b94dffe4bcc0d

scenario: 50GB longevity. ran a nemesis of SoftRebootNode to 
10.0.159.212 . 2 minute later got error from node ip-10-0-69-237:
```
< t:2019-09-16 20:20:27,436 f:nemesis.py      l:338  c:sdcm.nemesis         p:DEBUG > sdcm.nemesis.ChaosMonkey: Set current_disruption -> SoftRebootNode Node longevity-tls-50gb-4d-3-1-db-node-5979c9a0-4 [34.240.105.72 | 10.0.159.212] (seed: False)
< t:2019-09-16 20:20:29,967 f:cluster.py      l:1231 c:sdcm.cluster         p:DEBUG > 2019-09-16T20:20:29+00:00  ip-10-0-69-237 !ERR     | scylla: [shard 1] view - Error applying view update to 10.0.159.212: std::runtime_error (unstarted write cancelled)
< t:2019-09-16 20:20:29,980 f:sct_events.py   l:473  c:sdcm.sct_events      p:INFO  > 2019-09-16T20:20:29+00:00  ip-10-0-69-237 !ERR     | scylla: [shard 1] view - Error applying view update to 10.0.159.212: std::runtime_error (unstarted write cancelled)
< t:2019-09-16 20:23:57,758 f:nemesis.py      l:595  c:sdcm.nemesis         p:INFO  > sdcm.nemesis.ChaosMonkey: <<<<<<<<<<<<<Finished random_disrupt_method soft_reboot_node
```
failure event:
```
(DatabaseLogEvent Severity.CRITICAL): type=RUNTIME_ERROR regex=std::runtime_error line_number=27822 node=Node longevity-tls-50gb-4d-3-1-db-node-5979c9a0-3 [52.213.136.181 | 10.0.69.237] (seed: False)
2019-09-16T20:20:29+00:00  ip-10-0-69-237 !ERR     | scylla: [shard 1] view - Error applying view update to 10.0.159.212: std::runtime_error (unstarted write cancelled)
```

logs:
https://cloudius-jenkins-test.s3.amazonaws.com/5979c9a0-a1c1-4601-a2c3-63f1850766d9/longevity-tls-50gb-4d-3-1-loader-set-5979c9a0.zip
https://cloudius-jenkins-test.s3.amazonaws.com/5979c9a0-a1c1-4601-a2c3-63f1850766d9/longevity-tls-50gb-4d-3-1-monitor-set-5979c9a0.zip
https://cloudius-jenkins-test.s3.amazonaws.com/5979c9a0-a1c1-4601-a2c3-63f1850766d9/monitoring_data_stack_branch-2.4_3.1.tar.gz

https://cloudius-jenkins-test.s3.amazonaws.com/5979c9a0-a1c1-4601-a2c3-63f1850766d9/longevity-tls-50gb-4d-3-1-db-cluster-5979c9a0.zip

job log: scratch.scylladb.com/qa_issues/sct_08_42_22_09_2019.log.gz
monitor: http://52.212.4.91:3000
snapshot:
https://snapshot.raintank.io/dashboard/snapshot/uCyjyRz4zS6KPDwMbqspGcpCoFKobY1t

**Comment by yarongilor** [comment] 2019-09-23 09:56
```
$ hydra investigate show-logs 5979c9a0-a1c1-4601-a2c3-63f1850766d9 | grep '|'
|                                            Log links for testrun with test id 5979c9a0-a1c1-4601-a2c3-63f1850766d9                                             |
| Log type              | Link                                                                                                                                   |
| events                | https://cloudius-jenkins-test.s3.amazonaws.com/5979c9a0-a1c1-4601-a2c3-63f1850766d9/events_log.zip                                     |
| db-cluster            | https://cloudius-jenkins-test.s3.amazonaws.com/5979c9a0-a1c1-4601-a2c3-63f1850766d9/longevity-tls-50gb-4d-3-1-db-cluster-5979c9a0.zip  |
| monitor-set           | https://cloudius-jenkins-test.s3.amazonaws.com/5979c9a0-a1c1-4601-a2c3-63f1850766d9/longevity-tls-50gb-4d-3-1-monitor-set-5979c9a0.zip |
| monitoring_data_stack | https://cloudius-jenkins-test.s3.amazonaws.com/5979c9a0-a1c1-4601-a2c3-63f1850766d9/monitoring_data_stack_branch-2.4_3.1.tar.gz        |
```

**Comment by slivne** [comment] 2019-09-25 09:34
@eliransin are you assigning someone else ?

**Comment by slivne** [comment] 2019-09-26 14:29
@psarna can you please also look at this

**Comment by psarna** [comment] 2019-09-26 14:58
Sure, I will. The comment around this error is rather explanatory:
~~~
            // Requests that time-out normally below after response_wait()
            // result in an exception (see ~abstract_write_response_handler())
            // However, here we no longer have the handler or its information
            // to put in the exception. The exception is not needed for
            // correctness (e.g., hints are written by timeout_cb(), not
            // because of an exception here).
            return make_exception_future<>(std::runtime_error("unstarted write cancelled"));
~~~
I'll try to reproduce it somehow (although according to the comment, it's a benign timeout that simply happened with a very specific timing).

**Comment by psarna** [comment] 2019-09-27 09:22
It looks like a harmless situation:

1. a view update is prepared to be sent, response id is already prepared, but `mutate_begin()` is not called yet because there are preemption points before it
2. another node is reported to be down (because of the planned soft reboot)
3. as a part of `on_down()` handling, which handles the event of another node being down, the response id generated in `1.` is immediately timed out and removed (ref: `storage_proxy::on_down`)
4. `mutate_begin()` is finally executed, but since the write was already cancelled, there's no response id to be handled anymore. So, the write path is cancelled by returning an exceptional future: `"unstarted write cancelled"`.

The whole issue is very thoroughly explained by Nadav in his commit mesage here: 6e87bca65d

Conclusion: when a node is rebooted during handling view updates, these exceptional futures are expected to happen and be reported.

**Comment by nyh** [comment] 2019-09-27 09:39
Indeed, this case is not an error - it's a fix for a rare, but valid, case.
If I remember correctly my first version of this patch didn't even throw in
this case, but I was asked by a reviewer to add an exception here! Should
we soften the words of this exception? Downgrade it to debug or something?

**Comment by psarna** [comment] 2019-09-27 09:50
It's either that or adding this error to a whitelist in the test, but I think that downgrading fits better. It's not an error after all, but an expected path that cancels the write. Returning an exceptional future still makes sense though, because after seeing that the response handler was already deleted, we shouldn't proceed with the mutation procedure as if `mutate_begin()` succeeded.

**Comment by yarongilor** [comment] 2019-10-07 11:53
Reproduced in version: 3.1.0.rc9-0.20191006.05272c53e
AMI: ami-09c8d17ff81a2773e
log error:
```
2019-10-06T23:45:48+00:00  ip-10-0-196-121 !ERR     | scylla: [shard 13] view - Error applying view update to 10.0.104.24: std::runtime_error (unstarted write cancelled)
```
log file: scratch.scylladb.com/qa_issues/sct_11_37_07_10_2019.log.gz

**Comment by eliransin** [comment] 2019-10-08 05:59
@psarna I saw that your commit that downgrades the exception is in and that it is only reffing this
issue. Can it be closed?
If not, what is missing?

**Comment by psarna** [comment] 2019-10-08 07:12
This issue can be closed. The patch removes only a symptom, not the cause, but the cause will also be solved later.

**Comment by slivne** [comment] 2019-10-24 09:37
@psarna was the cause solved ?

**Comment by psarna** [comment] 2019-10-24 14:03
The symptom is solved here: 36a1905e98b815e78241c52ced234e5943eb793d 
The cause is discussed here: https://github.com/scylladb/scylla/pull/5114 - the final assumption from Gleb was that it's written on top of a hack, but the fix itself is not *more* hacky than the previous solution, so it's acceptable for now.

**Comment by nyh** [comment] 2019-11-18 16:13
As @sarna explained above, this issue (just a spurious message) was already solved, so I'm closing the issue. I'm adding the Backport candidate label and @yarongilor which branches do you need this ported to?

**Closed by nyh** 2019-11-18 16:13 UTC
Labels: Backport candidate, materialized-views

**Comment by nyh** [comment] 2020-04-19 19:47
Removing backport-candidate tag on this antique issue that mainly has to do with spurious error messages during testing.
