### ISSUE TITLE
testNowToUUIDCompatibility is flaky

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#9300] opened 2021-09-07 06:03 UTC
Seen occasionally several times in next promotion tests:

https://jenkins.scylladb.com/view/master/job/scylla-master/job/next/3932/testReport/junit/cassandra_tests.validation.entities/type_test/Test___testNowToUUIDCompatibility/
```
    def testNowToUUIDCompatibility(cql, test_keyspace):
        with create_table(cql, test_keyspace, "(a int, b uuid, PRIMARY KEY (a, b))") as table:
            execute(cql, table, "INSERT INTO %s (a, b) VALUES (0, now())")
>           assert len(list(execute(cql, table, "SELECT * FROM %s WHERE a=0 AND b < now()"))) == 1
E           AssertionError: assert 0 == 1
E            +  where 0 = len([])
E            +    where [] = list(<cassandra.cluster.ResultSet object at 0x7f1ab5688790>)
E            +      where <cassandra.cluster.ResultSet object at 0x7f1ab5688790> = execute(<cassandra.cluster.Session object at 0x7f1ab8456430>, 'cql_test_1630617714501.cql_test_1630617752983', 'SELECT * FROM %s WHERE a=0 AND b < now()')
```

https://jenkins.scylladb.com/view/master/job/scylla-master/job/next/3938/testReport/junit/cassandra_tests.validation.entities/type_test/Test___testNowToUUIDCompatibility/
```
    def testNowToUUIDCompatibility(cql, test_keyspace):
        with create_table(cql, test_keyspace, "(a int, b uuid, PRIMARY KEY (a, b))") as table:
            execute(cql, table, "INSERT INTO %s (a, b) VALUES (0, now())")
>           assert len(list(execute(cql, table, "SELECT * FROM %s WHERE a=0 AND b < now()"))) == 1
E           AssertionError: assert 0 == 1
E            +  where 0 = len([])
E            +    where [] = list(<cassandra.cluster.ResultSet object at 0x7f6528138c40>)
E            +      where <cassandra.cluster.ResultSet object at 0x7f6528138c40> = execute(<cassandra.cluster.Session object at 0x7f652b47bc70>, 'cql_test_1630913707314.cql_test_1630913746632', 'SELECT * FROM %s WHERE a=0 AND b < now()')
```

https://jenkins.scylladb.com/view/master/job/scylla-master/job/next/3941/testReport/junit/cassandra_tests.validation.entities/type_test/Test___testNowToUUIDCompatibility/
```
    def testNowToUUIDCompatibility(cql, test_keyspace):
        with create_table(cql, test_keyspace, "(a int, b uuid, PRIMARY KEY (a, b))") as table:
            execute(cql, table, "INSERT INTO %s (a, b) VALUES (0, now())")
>           assert len(list(execute(cql, table, "SELECT * FROM %s WHERE a=0 AND b < now()"))) == 1
E           AssertionError: assert 0 == 1
E            +  where 0 = len([])
E            +    where [] = list(<cassandra.cluster.ResultSet object at 0x7ff2002c6040>)
E            +      where <cassandra.cluster.ResultSet object at 0x7ff2002c6040> = execute(<cassandra.cluster.Session object at 0x7ff202da10d0>, 'cql_test_1630942707419.cql_test_1630942747278', 'SELECT * FROM %s WHERE a=0 AND b < now()')
```

I guess that there's a chance that scylla is too fast and the 2 `now()` calls fall in the same millisecond and produce the same value, so the comparison in the SELECT statement should be `<=` rather than `<`.

See https://github.com/scylladb/scylla/blob/69275f02fd84db9fee3288cdf3d00b10d40c859e/utils/UUID_gen.hh#L125

**Comment by bhalevy** [comment] 2021-09-10 20:04
@nyh please look into this issue.
Those tests fail quite frequently in next promotion.

**Comment by nyh** [comment] 2021-09-12 05:56
@bhalevy you're absolutely right. I'll send a patch.

**Comment by nyh** [comment] 2021-09-12 07:08
@bhalevy on second thought, the issue is much less clear-cut than I thought and maybe we uncovered a real bug?

now() is documented to return a **unique** timeuuid (see https://docs.datastax.com/en/cql-oss/3.3/cql/cql_reference/timeuuid_functions_r.html). When called on the same coordinator twice in quick succession, it may indeed return the have millisecond portion, but still, the other parts should be different. This test clearly expects that the second call returns a "higher" uuid than the first call, and it doesn't happen in Scylla. In any case, the second call can't return an "equal" uuid, so changing the "<" to "<="  as you suggested is probably wrong.

So now we have several possibilities and I still don't know which is the right one

1. It is possible (?) that this test is wrong - that there is no reason why a second now() call in the same millisecond must be "higher" in uuid comparison. If that is true, maybe Cassandra was just two slow to notice their test was wrong (they never had two calls in the same millisecond).
2. It is possible our time uuid generation is wrong and while Cassandra's version increases when called during the same millisecond, ours doesn't.
3. Note that in this this specific test, `testNowToUUIDCompatibility`, the result of `now()` is saved in a `uuid`, not `timeuuid`. Maybe this makes a difference somehow? Maybe we have a different sort order for the two types? This may be combined with possiblity 1 above (if uuid has a different sort order, we shouldn't expect it to be increasing, but nobody noticed because Cassandra was too slow).

We have another potential problem: the same test file has additional tests assuming that `now()` is increasing - `testDateCompatibility` and `testDateCompatibility`. These might have a similar (or different...) problem with the same-millisecond `now()`.

**Comment by nyh** [comment] 2021-09-12 07:15
Issue #7729 suggests that `UUID::operator<` is an incorrect way of comparing timeuuids, so if we use that in `testNowToUUIDCompatibility`, it's not surprising we get unexpected results. But I am still not sure if or why Cassandra doesn't have the same problem (or maybe it does it's just too slow to catch).

CC @dekimir and @kostja who were interested in these timeuuid issues in the past.

**Comment by bhalevy** [comment] 2021-09-12 12:04
@nyh you're right. `now()` (calling `create_time_safe()`) does return a unique timeuuid, by incrementing the decimicroseconds count.
And we also had https://github.com/scylladb/scylla-dtest/issues/1963 which was solved by using Python `TimeUUID` class for comparison instead of straight UUID

**Comment by bhalevy** [comment] 2021-09-12 12:06
should the schema use `timeuuid` rather than `uuid`?

**Comment by nyh** [comment] 2021-09-12 12:29
> should the schema use `timeuuid` rather than `uuid`?

Unfortunately, the answer here is no: The test is called testNowToUUIDCompatibility specifically to test the UUID type, not TIMEUUID. Or at least, that's what I think it was trying to do. I'll try to review the history of this Cassandra unit test and why they thought it should pass. I also still don't know if the problem is really related to "same millisecond". In the past we had UUID ordering differences exposed when a particular byte was -128, which happened in 1/256 of the runs. I'll try to run this test many times to see if I can reproduce this issue on my machine.

**Comment by avikivity** [comment] 2021-09-12 14:00
The tested was added in July (8030461a2c2c8d2dc3fd4c30b945800528de4ef0) but only recently started being flaky. It's probably  a regression.

**Comment by avikivity** [comment] 2021-09-12 14:08
High fail rate:

```
Summary: 18 of the total 30 tests failed
```

**Comment by nyh** [comment] 2021-09-12 14:14
On my machine, it doesn't fail once in 1000 repeats:
```
test/cql-pytest/run --count=1000 cassandra_tests/validation/entities/type_test.py::testNowToUUIDCompatibility
```
So maybe it indeed has something to do with the machine's speed (maybe my laptop is to fast, or too slow, to reproduce this)?

**Comment by avikivity** [comment] 2021-09-12 14:16
What's --count? I used --repeat 30.

**Comment by bhalevy** [comment] 2021-09-12 14:18
Maybe https://github.com/scylladb/scylla/issues/8816 caused a regression?

**Comment by avikivity** [comment] 2021-09-12 14:21
I have 8/30 fails on the commit that introduced the test. I don't understand how we ever got next to pass, since with 3 test runs, the odds of passing are low. Maybe cql-pytest didn't get run and then we fixed it, introducing the failures.

**Comment by nyh** [comment] 2021-09-12 14:24
"--count" is a pytest plugin. Running this test 1000 times this way takes just 30 seconds ;-)
I guess "--repeat" is from `test.py`, not pytest (or test/cql-pytest/run)? How do you use it to repeat just one test (and not the entire cqlpytest suite)?

**Comment by avikivity** [comment] 2021-09-12 14:39
I ran the entire suite. Since I have >30 threads, this did not increase runtime.

**Comment by avikivity** [comment] 2021-09-12 14:41
> On my machine, it doesn't fail once in 1000 repeats:
> 
> ```
> test/cql-pytest/run --count=1000 cassandra_tests/validation/entities/type_test.py::testNowToUUIDCompatibility
> ```
> 
> So maybe it indeed has something to do with the machine's speed (maybe my laptop is to fast, or too slow, to reproduce this)?

Running this command line got me:

```
INFO  2021-09-12 17:40:14,688 [shard 0] init - serving
INFO  2021-09-12 17:40:14,688 [shard 0] init - Scylla version 4.6.dev-0.20210912.8030461a2c initialization completed.
Scylla tests failure
```

I have no idea if it didn't work at all, or if a test failed.

**Comment by avikivity** [comment] 2021-09-12 14:42
It fails with --count 1, so probably a systematic failure.

**Comment by nyh** [comment] 2021-09-12 14:43
> I have 8/30 fails on the commit that introduced the test. I don't understand how we ever got next to pass, since with 3 test runs, the odds of passing are low. Maybe cql-pytest didn't get run and then we fixed it, introducing the failures.

cql-pytest has been running for much longer than a month... Maybe it's really something like Benny guessed that it fails when two `now()` calls have exactly the same milliseconds (and then the sub-millisecond details aren't sorted as expected) and some recent improvement in your hardware or compiler or something changed the timing?

**Comment by nyh** [comment] 2021-09-12 14:44
> > On my machine, it doesn't fail once in 1000 repeats:
> > ```
> > test/cql-pytest/run --count=1000 cassandra_tests/validation/entities/type_test.py::testNowToUUIDCompatibility
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > So maybe it indeed has something to do with the machine's speed (maybe my laptop is to fast, or too slow, to reproduce this)?
> 
> Running this command line got me:
> 
> ```
> INFO  2021-09-12 17:40:14,688 [shard 0] init - serving
> INFO  2021-09-12 17:40:14,688 [shard 0] init - Scylla version 4.6.dev-0.20210912.8030461a2c initialization completed.
> Scylla tests failure
> ```
> 
> I have no idea if it didn't work at all, or if a test failed.

Sorry, you need to " pip install pytest-repeat" for the "--count" pytest plugin to work.
I see we have a bug that invalid options to pytest cause a mysterious test failure without any details. I'll open an issue about that.

**Comment by avikivity** [comment] 2021-09-12 14:46
Ah, also available in a Fedora package. Nice that the package is named correctly (vs. the flag).

I get about 10% failures (or at least the letter F vs .).

**Comment by avikivity** [comment] 2021-09-12 14:46
```
cql = <cassandra.cluster.Session object at 0x7f930f3f1790>, test_keyspace = 'cql_test_1631457925786'

    def testNowToUUIDCompatibility(cql, test_keyspace):
        with create_table(cql, test_keyspace, "(a int, b uuid, PRIMARY KEY (a, b))") as table:
            execute(cql, table, "INSERT INTO %s (a, b) VALUES (0, now())")
>           assert len(list(execute(cql, table, "SELECT * FROM %s WHERE a=0 AND b < now()"))) == 1
E           AssertionError: assert 0 == 1
E            +  where 0 = len([])
E            +    where [] = list(<cassandra.cluster.ResultSet object at 0x7f930ffd95b0>)
E            +      where <cassandra.cluster.ResultSet object at 0x7f930ffd95b0> = execute(<cassandra.cluster.Session object at 0x7f930f3f1790>, 'cql_test_1631457925786.cql_test_1631457925804', 'SELECT * FROM %s WHERE a=0 AND b < now()')

cassandra_tests/validation/entities/type_test.py:38: AssertionError
```

**Comment by nyh** [comment] 2021-09-12 14:47
> I see we have a bug that invalid options to pytest cause a mysterious test failure without any details. I'll open an issue about that.

It's not really a bug, more of a mixup of standard output and error... If you do 
```
test/cql-pytest/run --xxx cassandra_tests/validation/entities/type_test.py::testNowToUUIDCompatibility |& less
```
with xxx an invalid parameter and "|&" is a shortcut for "2>&1 |", you get
```
Scylla is: /home/nyh/scylla/build/dev/scylla.
Booting Scylla on 127.2.55.83 in /tmp/scylla-test-79699...
Boot successful (0.5 seconds).
ERROR: usage: pytest [options] [file_or_dir] [file_or_dir] [...]
pytest: error: unrecognized arguments: --xxx
  inifile: /home/nyh/scylla/test/cql-pytest/pytest.ini
  rootdir: /home/nyh/scylla/test/cql-pytest
Scylla is: /home/nyh/scylla/build/dev/scylla.
Booting Scylla on 127.2.55.83 in /tmp/scylla-test-79699...
Boot successful (0.5 seconds).
ERROR: usage: pytest [options] [file_or_dir] [file_or_dir] [...]
pytest: error: unrecognized arguments: --xxx
  inifile: /home/nyh/scylla/test/cql-pytest/pytest.ini
  rootdir: /home/nyh/scylla/test/cql-pytest
...
```

**Comment by avikivity** [comment] 2021-09-12 14:48
Yes, I only saw the tail of the log which had no relevant information, due to the huge amount of logging we do on startup.

**Comment by avikivity** [comment] 2021-09-12 14:49
If it's the millisecond thing, I thing we should make now() monotonically increasing.

**Comment by bhalevy** [comment] 2021-09-12 14:50
> If it's the millisecond thing, I thing we should make now() monotonically increasing.

It is.  We suspect the uuid less operator not understanding the timeuuid encoding (version 1 uuid)

**Comment by nyh** [comment] 2021-09-12 14:51
@avikivity If you can reproduce this issue, can you please try to modify this test and change "uuid" to "timeuuid"? If it will pass with "timeuuid", we will know it's a problem of different comparators for the two types (we know we have a "wrong" operator< for uuid).

**Comment by nyh** [comment] 2021-09-12 14:58
This test was added in Cassandra for https://issues.apache.org/jira/browse/CASSANDRA-6766 (Cassandra commit 9da742d5f83e1b2563be1c0d45a0e3d65a38ec44, from 2014). 
It appears that originally, they now() could only be assigned to type `timeuuid`, but in that issue they wanted to also be able to assign it to `uuid`. Which is fine, but they also wanted it to preserve the order and I'm not sure if that's possible given that we have an arguably (?) wrong `operator<` for `uuid`.

It is possible that Cassandra's implementation was never correct as well, it's just that this test passed because they never managed to get it called twice in the same millisecond...

**Comment by bhalevy** [comment] 2021-09-12 15:04
hmm, @nyh what happens if the SELECT query runs on a different node or shard than the INSERT query?

**Comment by nyh** [comment] 2021-09-12 15:07
> hmm, @nyh what happens if the SELECT query runs on a different node or shard than the INSERT query?

This is a unit test that normally runs on one node and one connection (so one coordinator shard). But I guess you're right that this test doesn't make much sense running against a cluster (which you can do, with pytest, but won't automatically happen in our run script).
We could drop these tests, but I'm worried maybe it caught a real bug in our `uuid` sort order and I want to understand it before just dropping the test.

**Comment by avikivity** [comment] 2021-09-12 15:09
Maybe the flakiness started with 729d0feef0f12a13644d8f7c887323df49f53527 where we started using the scylla python driver. Before, we'd have just one connection reused. Now, we pick a random connection if the query is not token-aware, so we have a chance to fall off to a different shard like @bhalevy mentions.

@nyh try reproducing with the scylla python driver installed.

**Comment by bhalevy** [comment] 2021-09-12 15:10
I just reproduced it under dbuild (but couldn't when running locally on my machine)

**Comment by bhalevy** [comment] 2021-09-12 15:10
> Maybe the flakiness started with [729d0fe](https://github.com/scylladb/scylla/commit/729d0feef0f12a13644d8f7c887323df49f53527) where we started using the scylla python driver. Before, we'd have just one connection reused. Now, we pick a random connection if the query is not token-aware, so we have a chance to fall off to a different shard like @bhalevy mentions.
> 
> @nyh try reproducing with the scylla python driver installed.

yes, this exactly what I think too.

**Comment by bhalevy** [comment] 2021-09-12 15:30
Reproduced with the following change:
```diff
diff --git a/cql3/functions/time_uuid_fcts.hh b/cql3/functions/time_uuid_fcts.hh
index 1d3052182..4bf3f0cfe 100644
--- a/cql3/functions/time_uuid_fcts.hh
+++ b/cql3/functions/time_uuid_fcts.hh
@@ -49,6 +49,8 @@ namespace cql3 {
 
 namespace functions {
 
+extern logging::logger log;
+
 namespace time_uuid_fcts {
 
 inline
@@ -56,7 +58,9 @@ shared_ptr<function>
 make_now_fct() {
     return make_native_scalar_function<false>("now", timeuuid_type, {},
             [] (cql_serialization_format sf, const std::vector<bytes_opt>& values) -> bytes_opt {
-        return {to_bytes(utils::UUID_gen::get_time_UUID())};
+        auto now = utils::UUID_gen::get_time_UUID();
+        log.info("now={}", now);
+        return {to_bytes(now)};
     });
 }
 
```

And got this on failure:
```
$ ./tools/toolchain/dbuild -- test/cql-pytest/run cassandra_tests/validation/entities/type_test.py::testNowToUUIDCompatibility |& egrep 'now=|(tests failure)'
INFO  2021-09-12 18:30:24,373 [shard 0] cql3_fuctions - now=59501250-13de-11ec-913b-0c6432f213b4
INFO  2021-09-12 18:30:24,373 [shard 0] cql3_fuctions - now=59501251-13de-11ec-913b-0c6432f213b4
INFO  2021-09-12 18:30:24,373 [shard 1] cql3_fuctions - now=59501250-13de-11ec-8e88-0c6532f213b4
Scylla tests failure
```

**Comment by bhalevy** [comment] 2021-09-12 16:23
@nyh, the following reproduces the issue:
```c++
SEASTAR_TEST_CASE(timeuuid_compare_across_shards) {
    return do_with_cql_env_thread([] (cql_test_env& e) {
        // We don't test the `currentdate()` function since we don't
        // have a way to supply a synthetic clock to query processor, hence
        // can't move one day forward to demonstrate the desired behavior.
        const std::vector<std::pair<std::string, std::string>> sub_tests = {
            {"now", "timeuuid"},
            {"now", "uuid"},
        };
        for (const auto& [func, type] : sub_tests) {
            auto table_name = format("test_{}_as_{}", func, type);
            auto create_query = format("CREATE TABLE {} (a int, b {}, PRIMARY KEY (a, b))", table_name, type);
            testlog.info("{}", create_query);
            e.execute_cql(create_query).get();
            auto drop_test_table = defer([&] { e.execute_cql(format("DROP TABLE {}", table_name)).get(); });
            auto insert_query = format("INSERT INTO {} (a, b) VALUES (0, {}())", table_name, func);
            testlog.info("{}", insert_query);
            auto insert_stmt = e.execute_cql(insert_query).get();
            auto select_query = format("SELECT * FROM {} WHERE a = 0 AND b < {}()", table_name, func);
            auto msg = smp::submit_to(1, [&e, select_query] {
                testlog.info("{}", select_query);
                return e.execute_cql(select_query);
            }).get0();
            assert_that(msg).is_rows().with_size(1);
        }
    });
}
```

A sleep of 1ms between INSERT and SELECT causes the (time)uuid values to differ also across shards.
Though it might not across nodes if their time skew is larger than 1 ms.

That aside, the data type should not matter, since we compare using the following logic if both uuid's are version 1 (timeuuid):
https://github.com/scylladb/scylla/blob/83113d866136cd291368140ca39536e4e7511c4f/types.cc#L2263-L2269

**Comment by nyh** [comment] 2021-09-12 19:15
I agree with @avikivity 's patch which disables those two tests because they are only guaranteed in a single-node single-shard cluster. We should consider closing this issue now - since our driver no longer has a single connection to a single cluster, this sort of test can never be re-enabled, and I think we don't need to consider any other solutions.

**Comment by bhalevy** [comment] 2021-09-13 05:46
@nyh although we can't guarantee monotonicity of the current time across nodes, and not required to across shards, a simple change can practically guarantee that on a single node, if `create_time_safe` just takes advantage of the system_clock nanoseconds resolution, like that::
```diff
diff --git a/utils/UUID_gen.hh b/utils/UUID_gen.hh
index 8e5e1f50c1..a4a72ba66f 100644
--- a/utils/UUID_gen.hh
+++ b/utils/UUID_gen.hh
@@ -122,8 +122,8 @@ class UUID_gen
     // shards and UUID code uses thread local state on each shard.
     int64_t create_time_safe() {
         using std::chrono::system_clock;
-        auto millis = duration_cast<milliseconds>(system_clock::now().time_since_epoch());
-        decimicroseconds when = from_unix_timestamp(millis);
+        auto unix_decimicros = duration_cast<decimicroseconds>(system_clock::now().time_since_epoch());
+        decimicroseconds when = from_unix_timestamp(unix_decimicros);
         if (when > _last_used_time) {
             _last_used_time = when;
         } else {
```

@kostja, in change c83cf1f965f2b2fdb55f308aa08e4d5fd3dd2115 `create_time_safe` is defined to "Return decimicrosecond time based on the system time, in milliseconds.".  What was the reason for basing it on milliseconds which artificially lowers the actual system_clock accuracy?

**Comment by nyh** [comment] 2021-09-13 19:25
We should consider closing this issue. https://github.com/scylladb/scylla/commit/1fd701e709e9fcfd608ae925634401ba3626614a fixes the flaky tests by skipping them, because they are invalid (the tests are only valid if all requests are made for a single connection to a single shard on a single node, but the test framework doesn't guarantee that).

**Comment by bhalevy** [comment] 2021-09-13 19:46
I have no objection to close the issue,
but I'd still like use to consider increasing `create_time_safe()` accuracy as per https://github.com/scylladb/scylla/issues/9300#issuecomment-917860461
We'd get cross-shard monotonicity of cql `now()` this way for free.

**Comment by nyh** [comment] 2021-09-14 06:42
That's an interesting question that I don't remember the answer to (maybe @kostja remembers, he was deep into this stuff a few months ago). On the other hand, it won't *guarantee* cross-shard monotonicity - it will only guarantee it if not called more than once in a decimicrosecond - i.e., the test will might work for now but start failing again in 10 years). It also won't be guaranteed across different coordinator *nodes*, so it's still not clear what's the purpose of this test.

**Comment by kostja** [comment] 2021-09-14 07:14
> ange [c83cf1f](https://github.com/scylladb/scylla/commit/c83cf1f965f2b2fdb55f308aa08e4d5fd3dd2115) `create_time_safe` is defined to "Return decimicrosecond time based on the system time, in milliseconds.". What was the reason for basing it on milliseconds which a

Compatibility with cassandra. We don't have to be compatible with it, but a few tests will fail if you make the change.

**Comment by kostja** [comment] 2021-09-14 07:15
I don't get how using decimicroseconds is going to give cross-shard monotonicity. What is cross-shard monotonicity anyway?

**Comment by kostja** [comment] 2021-09-14 07:16
(assigned to myself as well to see all notifications)

**Comment by kostja** [comment] 2021-09-14 07:29
Bottom line: we can change milliseconds to decimicroseconds in create_time_safe() and this will increase time resolution. There were some legacy tests checking the resolution is *milliseconds*, they will need to be updated, so this is more a feature request than a bug fix.

**Comment by avikivity** [comment] 2021-09-14 08:54
Closing per the conclusions in this thread. I agree we should improve time resolution, but it's a separate issue.

**Closed** 2021-09-14 08:54 UTC
Labels: test

**Comment by bhalevy** [comment] 2021-09-14 09:15
> Now, we pick a random connection if the query is not token-aware, so we have a chance to fall off to a different shard

@avikivity The queries here are:
```
INSERT INTO %s (a, b) VALUES (0, now())
SELECT * FROM %s WHERE a=0 AND b < now()
```

Why aren't they token-aware?  In both queries we specify the partition key a=0.
Could this be a bug in our python client?

**Comment by avikivity** [comment] 2021-09-14 16:31
Only prepared statements are token aware.
