### ISSUE TITLE
scylla_setup disobeys my request to not install node_exporter

### ISSUE THREAD

**Issue by nyh** [scylladb/scylla#2882] opened 2017-10-10 17:51 UTC
*Installation details*
Scylla version (or git commit hash): 2.0

I ran scylla_setup, one of the questions I answered no, but it seems it was still done:
```
Do you want to install node exporter and export Prometheus data from the node?
Answer yes to install it; answer no to skip this installation.
[YES/no]no
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   628    0   628    0     0   3031      0 --:--:-- --:--:-- --:--:--  3048
100 3925k  100 3925k    0     0  5456k      0 --:--:-- --:--:-- --:--:-- 5456k
node_exporter-0.14.0.linux-amd64/
node_exporter-0.14.0.linux-amd64/LICENSE
node_exporter-0.14.0.linux-amd64/NOTICE
node_exporter-0.14.0.linux-amd64/node_exporter
Created symlink from /etc/systemd/system/multi-user.target.wants/node-exporter.service to /usr/lib/systemd/system/node-exporter.service.
node_exporter successfully installed
```

**Comment by syuu1228** [comment] 2018-01-19 19:36
Tested, but not able to reproduce it on 2.0.
```
Do you want to install node exporter and export Prometheus data from the node?
Answer yes to install it; answer no to skip this installation.
[YES/no]no
```
And on the script, node_exporter_install doesn't invoked when answered 'no' on interactive prompt:
https://github.com/scylladb/scylla/blob/branch-2.0/dist/common/scripts/scylla_setup#L465

**Comment by slivne** [comment] 2018-04-29 10:43
I am not able to reproduce this - closing the issue

**Closed by slivne** 2018-04-29 10:43 UTC
Labels: UX, bug, onboarding
