### ISSUE TITLE
Clustering column cannot be restricted by IN relation

### ISSUE THREAD

**Issue by raphaelsc** [scylladb/scylla#1516] opened 2016-07-28 21:33 UTC
In Scylla, it's currently possible to query a clustering column using IN relation, but it seems not work quite well.

Query example: USE keyspace1; SELECT * FROM table1 WHERE p1 = 'key1' AND c1 IN ('a', 'z');

 C*, for example, returns the following error when executing the same query: 
InvalidRequest: code=2200 [Invalid query] message="Clustering column "c1" cannot be restricted by an IN relation"

**Comment by pdziepak** [comment] 2016-07-29 09:55
Isn't this a duplicate of #1437?

**Comment by raphaelsc** [comment] 2016-07-29 17:30
On Fri, Jul 29, 2016 at 6:55 AM, Paweł Dziepak <notifications@github.com>
wrote:

> Isn't this a duplicate of #1437
> <https://github.com/scylladb/scylla/issues/1437>?
>

Yes. Closing it.

**Closed** 2016-07-29 17:30 UTC
