### ISSUE TITLE
nodetool netstats - error

### ISSUE THREAD

**Issue by noamha** [scylladb/scylla#815] opened 2016-01-18 13:57 UTC
While running nodetool rubild on a server I tried running nodetool netstats and received the following message:
```
nodetool: Found unexpected parameters: [netstas]
See 'nodetool help' or 'nodetool help <command>'.
[root@noam-server-03 ~]# nodetool netstats
Mode: NORMAL
error: null
-- StackTrace --
java.lang.NullPointerException
        at org.glassfish.json.JsonObjectBuilderImpl$JsonObjectImpl.getString(JsonObjectBuilderImpl.java:199)
        at org.apache.cassandra.streaming.SessionInfo.fromJsonObject(SessionInfo.java:97)
        at org.apache.cassandra.streaming.SessionInfo.fromJsonArr(SessionInfo.java:108)
        at org.apache.cassandra.streaming.StreamManager.getState(StreamManager.java:63)
        at org.apache.cassandra.streaming.StreamManager.getCurrentStreams(StreamManager.java:73)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at sun.reflect.misc.Trampoline.invoke(MethodUtil.java:71)
        at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at sun.reflect.misc.MethodUtil.invoke(MethodUtil.java:275)
        at com.sun.jmx.mbeanserver.StandardMBeanIntrospector.invokeM2(StandardMBeanIntrospector.java:112)
        at com.sun.jmx.mbeanserver.StandardMBeanIntrospector.invokeM2(StandardMBeanIntrospector.java:46)
        at com.sun.jmx.mbeanserver.MBeanIntrospector.invokeM(MBeanIntrospector.java:237)
        at com.sun.jmx.mbeanserver.PerInterface.getAttribute(PerInterface.java:83)
        at com.sun.jmx.mbeanserver.MBeanSupport.getAttribute(MBeanSupport.java:206)
        at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.getAttribute(DefaultMBeanServerInterceptor.java:647)
        at com.sun.jmx.mbeanserver.JmxMBeanServer.getAttribute(JmxMBeanServer.java:678)
        at javax.management.remote.rmi.RMIConnectionImpl.doOperation(RMIConnectionImpl.java:1448)
        at javax.management.remote.rmi.RMIConnectionImpl.access$300(RMIConnectionImpl.java:76)
        at javax.management.remote.rmi.RMIConnectionImpl$PrivilegedOperation.run(RMIConnectionImpl.java:1312)
        at javax.management.remote.rmi.RMIConnectionImpl.doPrivilegedOperation(RMIConnectionImpl.java:1404)
        at javax.management.remote.rmi.RMIConnectionImpl.getAttribute(RMIConnectionImpl.java:641)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:323)
        at sun.rmi.transport.Transport$1.run(Transport.java:200)
        at sun.rmi.transport.Transport$1.run(Transport.java:197)
        at java.security.AccessController.doPrivileged(Native Method)
        at sun.rmi.transport.Transport.serviceCall(Transport.java:196)
        at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:568)
        at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:826)
        at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$93(TCPTransport.java:683)
        at java.security.AccessController.doPrivileged(Native Method)
        at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:682)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by tzach** [comment] 2016-02-16 10:14
related to #850 ?
The common factor is running two nodetool operations at the same time

**Comment by amnonh** [comment] 2016-02-22 15:36
It doesn't seem to be the same problem, is the problem reproducable?

**Comment by slivne** [comment] 2016-03-07 14:11
@amnonh can you run a test for this and see if it reproduces / closed

**Comment by amnonh** [comment] 2016-03-07 16:27
I have a test for netstats that passes.

**Comment by slivne** [comment] 2016-04-04 06:27
to be clear you have a test that does rebuild and in parallel does netstats - or something else ?

**Comment by amnonh** [comment] 2016-04-04 06:36
Run netstats and repair, I'm adding more concurrent tests. I'll add rebuild

**Comment by slivne** [comment] 2016-04-06 06:41
Thanks - closing since you have a netstats and repair running in parallel

**Closed by slivne** 2016-04-06 06:41 UTC
Labels: bug, high, nodetool
