### ISSUE TITLE
It is necessary for the Alternator to support configurable read and write consistency levels, isn't it?

### ISSUE THREAD

**Issue by Felix-zhoux** [scylladb/scylla#7694] opened 2020-11-25 07:23 UTC
When considering data consistency, users always want the returned data to be correct. If the copies on multiple nodes are the same, it often means that they are correct. The Consistency Level (CL) determines how many replicas in a cluster that must acknowledge read or write operations before it is considered successful.
The consistency level can be adjusted for each operation in CQL. However, configuration is not yet supported in the Alternator.

I know that Scylla provides read repair to ensure that replicas are updated with most recently updated data. Such repairs during read path run automatically, asynchronously, and in the background. In Alternator, the default consistency level of read is LOCAL_ONE, which means The coordinator node will only send the request to 1 replica node, and read repair will not occur.

**Comment by tzach** [comment] 2020-11-26 10:10
Supported, with RF=3 (unless running on a cluster of less than 3 nodes). 
Writes are done in LOCAL_QUORUM and reads in LOCAL_ONE (eventual consistency) or LOCAL_QUORUM (strong consistency).

https://docs.scylladb.com/using-scylla/alternator/alternator/#replication

**Comment by nyh** [comment] 2020-11-26 20:15
Alternator, aiming for compatibility with the DynamoDB API, uses that API's notions of consistency levels, and implements those fully. In the DynamoDB API, the consistency level of writes is not configurable, but for reads you can choose between two consistency levels: "_eventually consistent_" (which means that after a write you can read some old value but eventually will read the new value), and "_strongly consistent_" (which guarantees that reading after a successful write will give you the newly written value). These are the consistency-level options which the DynamoDB API gives you, and thus the ones we implemented in Alternator.

If you want to compare these consistency-level options with the one in CQL, then, exactly as Tzach said: Alternator writes are always done with LOCAL_QUORUM consistency level, and for reads you have two options: LOCAL_ONE (eventual consistency) or LOCAL_QUORUM (strong consistency). 

I'm closing this issue because 1. it is not a bug (if you think it is, you may need to explain better what you think the bug is), and 2. it is a duplicate of issue - #7428 - which is about how we may want to support more options when RF is **not** 3 and the two options we have right now (the two settings for the read consistency) may not be enough.

If you have concrete examples of how you'd like to configure RF and CL please comment about them in issue #7428. Making RF and CL more configuration is very easy technically, but the question is what exactly we want to provide, and how we can "extend" the DynamoDB API to provide these additional options.

**Closed by nyh** 2020-11-26 20:15 UTC
Labels: Alternator
