### ISSUE TITLE
Aggregation query should not run to completion if timed out

### ISSUE THREAD

**Issue by eliransin** [scylladb/scylla#7548] opened 2020-11-04 08:43 UTC
This issue highlights one of the issues that needs to be corrected for #1175
Today when we run a lengthy aggregation query, this query will run to completion even it timed out.
One of the problems is the fact that the aggregation part on the coordinator side of a query does not tests for 
neither timeout or disconnection so as long as new pages keeps coming from replicas it will keep computing the
aggregation.

**Comment by avikivity** [comment] 2020-11-04 09:36
It looks like an exact duplicate.

**Comment by gleb-cloudius** [comment] 2020-11-04 09:40
On Wed, Nov 04, 2020 at 01:37:03AM -0800, Avi Kivity wrote:
> It looks like an exact duplicate.
> 
I also fail to see the difference.

--
			Gleb.

**Comment by eliransin** [comment] 2020-11-04 13:10
Unless I am missing something, we should also clear/destroy the readers on the replicas and not only break the aggregation loop. Maybe this work has already been done and then it is correct that there is nothing to be done in order to clean the queries resources when it becomes irrelevant. 
Also, I guess there is some difference between just long query and an aggregation query.
I didn't check what happens with long queries (that are not aggregations), if we don't need to worry about them so yes,
it is the exact same thing and I will close this issue as a duplicate of the original one :slightly_smiling_face: 

@avikivity it was your request to take action only for the aggregation path:

>@denesb recent work of tying all subreaders together with reader_permit can help. But perhaps we can add a timeout in the aggregation path.

**Comment by avikivity** [comment] 2020-11-15 16:29
> Unless I am missing something, we should also clear/destroy the readers on the replicas and not only break the aggregation loop. Maybe this work has already been done and then it is correct that there is nothing to be done in order to clean the queries resources when it becomes irrelevant.

The readers on the replicas will disappear by themselves when the coordinator stops pulling more data (there is a querier cache timeout of 1s).

> Also, I guess there is some difference between just long query and an aggregation query.

Yes.

> I didn't check what happens with long queries (that are not aggregations), if we don't need to worry about them so yes,
> it is the exact same thing and I will close this issue as a duplicate of the original one 
> 
> @avikivity it was your request to take action only for the aggregation path:
> 
> > @denesb recent work of tying all subreaders together with reader_permit can help. But perhaps we can add a timeout in the aggregation path.


Why are we debating this on a duplicate?

**Comment by avikivity** [comment] 2020-11-15 16:30
Closing as duplicate of #1175.

**Closed by avikivity** 2020-11-15 16:30 UTC
Labels: enhancement, stability
