### ISSUE TITLE
Error : ConditionExpression is not yet implemented in alternator, when using latest Scylla DB docker image

### ISSUE THREAD

**Issue by debo93** [scylladb/scylla#5806] opened 2020-02-13 16:18 UTC
*Installation details*
Scylla version (or git commit hash): 666.development-0.20190906.d7c7927d3
Platform (physical/VM/cloud instance type/docker): Docker

Facing an error : ConditionExpression is not yet implemented in alternator, while updating a record in a table in Scylla DB Alternator, when using "ConditionExpression".

Steps to reporoduce the error : 

Running the latest docker Image enabling alternator : 
![image](https://user-images.githubusercontent.com/20627107/74451488-b6b35d80-4ea5-11ea-94a5-7db345d74cec.png)

![image](https://user-images.githubusercontent.com/20627107/74451346-7c49c080-4ea5-11ea-8971-5f5578713fe3.png)

Creating a table and inserting records with DynamoDB python SDK :
![image](https://user-images.githubusercontent.com/20627107/74453285-33473b80-4ea8-11ea-930e-09a12e6de867.png)
 
When trying to execute the below python code : 

table = dynamodb.Table('Dummy_Table')

query = dict()
query['Key'] = {'Primary_Key': '1', 'Range_Key': '1.1'}
query['UpdateExpression'] = "ADD column_1 :data"
expression_attribute_values = {
            ':data': "This is changed Data"
        }
query['ConditionExpression'] = "NOT (column_2 IN (:data_2)"
expression_attribute_values[':data_2'] = 'data3'
query['ExpressionAttributeValues'] = expression_attribute_values

response = table.update_item(**query)
print(response)

------------------------------------------------------------

Output : ClientError: An error occurred (ValidationException) when calling the UpdateItem operation: ConditionExpression is not yet implemented in alternator

**Comment by tzach** [comment] 2020-02-13 18:56
https://github.com/scylladb/scylla/issues/5035

**Comment by nyh** [comment] 2020-02-13 20:47
@tzach @penberg how old is this "latest Scylla docker" image? The version name 666.development-0.20190906.d7c7927d3 suggests it is from September? Is there a different way they should get the latest docker image?

The current master no longer has this message "ConditionExpression is not yet implemented" which they are reporting. It was implemented by commit b50274e8a7bdb2829e268c98fec4a2421e4f946c merged in January 23.

**Comment by fruch** [comment] 2020-02-13 21:29
Please take the version from the nightly dockerhub repo
https://hub.docker.com/layers/scylladb/scylla-nightly/666.development-202002131931/images/sha256-dd80d84cec51004a2d67f74d9397861bccf6d45243a6e874ea826e264caeb965?context=explore

Also can you confirm which docker image you are taking, and from which repo ?

latest on scylladb/scylla might be a candidate for 3.3-rc1

**Comment by nyh** [comment] 2020-02-13 21:33
I think (but I'm not the docker expert here, @hagitsegev and @penberg should know better), it should also be possible to look for the right docker image using named tags, something like "scylla-master:latest" should hopefully work and really be a nightly version, not a 4 month old version?

**Comment by fruch** [comment] 2020-02-13 21:46
That's true for the nightly repo, the main repo is formal releases only. 

Looking at the documentation on our site, seems like the part explaining about the nightly repo is missing.

Unfortunately we don't have a dockerhub repo per branch, and that's can make it a bit confusing, since we are pushing from different branches into the same repo.

**Comment by debo93** [comment] 2020-02-14 07:09
@nyh @fruch Thanks a lot for the quick resolution. 
The Docker image shared is supporting condition expression.
Just a thought, whether we should be able to consume the same functionalities when pulling the latest scylla db image or scylla db alternator image?

**Comment by debo93** [comment] 2020-02-15 18:15
The docker build suggested, doesnot allow to do cql shell inside it.
![image](https://user-images.githubusercontent.com/20627107/74593020-3e879c00-504d-11ea-926f-d78cb23a2e4e.png)

![image](https://user-images.githubusercontent.com/20627107/74593024-42b3b980-504d-11ea-8c80-baf7b91a4b38.png)

Please can you support us over the correct image name which we can use for our developement purpose for alternator.

**Comment by nyh** [comment] 2020-02-16 09:33
I can reproduce the problem with the following commands to to get and run the latest docker image:
```
docker pull scylladb/scylla-nightly:latest
docker run --name scylla -d -p 8000:8000 scylladb/scylla-nightly:latest --alternator-port=8000
```

Unfortunately the problem is this:
```
INFO  2020-02-16 09:27:15,410 [shard 0] init - Startup failed: std::runtime_error (Alternator enabled, but needs experimental LWT feature which wasn't enabled)
```
So Scylla doesn't start.
@pekka, we need the "--alternator-port" image option to also enable the LWT feature - can you please do that?

In the meantime, @debo93, you can enter the image with bash (as you did), edit `/etc/scylla/scylla.yaml`, and add:
```
experimental_features:
     - lwt
```
And run (again, in the container) `pkill -9 scylla`.

You can run (outside the container) `docker logs -f scylla` to see the progress of the restarted.
I checked, and with those two lines added to scylla.yaml, cqlsh starts to work as expected.

**Comment by nyh** [comment] 2020-02-16 09:59
Ok, I found how to create a docker image with the "experimental" option already set:
```
docker run --name scylla -d -p 8000:8000 scylladb/scylla-nightly:latest --alternator-port=8000 --experimental 1
```
Note the extra "--experimental 1".
Now cqlsh works (after about a minute of boot), without any changes in the container.

**Comment by nyh** [comment] 2020-02-16 11:02
@debo93 I'm closing this issue - the original ConditionExpression problem is gone if you use the latest build, and you can always fetch the most latest build with the "docker pull" command, and if you add the "--experimental 1" to the docker run command, it will actually work. Please reopen (or better yet, open a new issue) if you're facing more problems. Thanks.

**Closed by nyh** 2020-02-16 11:02 UTC
