### ISSUE TITLE
Nodetool Repair failing on keyspace with std::runtime_error (row_diff.size() != set_diff.size())

### ISSUE THREAD

**Issue by jtnagashima** [scylladb/scylla#6252] opened 2020-04-20 19:33 UTC
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [x] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

**Installation details**
Scylla version (or git commit hash): `scylla-3.3.0-0.20200319.7ae2cdf46c7.x86_64`
Cluster size: 5
OS (RHEL/CentOS/Ubuntu/AWS AMI): ScyllaDB 2.3.1 (ami-0402378ae7131b7a0)
Single Datacenter 

**Issue**
We recently ran through an exercise of upgrading a 5 node cluster from Scylla 2.3.6 to 3.3.0. During the upgrade process, we encountered one other issue https://github.com/scylladb/scylla/issues/6205, but it was an otherwise seamless upgrade process.  Disclaimer: during the debug process for the issue, we did end up dropping a node - node 4, and re-adding it to the cluster as a fresh node as a replacement for itself using the `replace_address_first_boot` parameter.

After the nodes were upgraded, we ran `nodetool repair` on the nodes, beginning with node-4 and ran into the following error:
`[shard 1] repair - Got error in row level repair: std::runtime_error (row_diff.size() != set_diff.size())`

**Scylla.yaml**
```
cluster_name: dev
num_tokens: 256
data_file_directories:
    - /var/lib/scylla/data
commitlog_directory: /var/lib/scylla/commitlog
commitlog_sync: periodic
commitlog_sync_period_in_ms: 10000
commitlog_segment_size_in_mb: 32
seed_provider:
    - class_name: org.apache.cassandra.locator.SimpleSeedProvider
      parameters:
          - seeds: "x.x.x.1"
listen_address: x.x.x.4
native_transport_port: 9042
read_request_timeout_in_ms: 5000
write_request_timeout_in_ms: 2000
endpoint_snitch: Ec2Snitch
rpc_address: 0.0.0.0
rpc_port: 9160
api_port: 10000
api_address: 127.0.0.1
batch_size_warn_threshold_in_kb: 5
batch_size_fail_threshold_in_kb: 50
broadcast_rpc_address: x.x.x.4
partitioner: org.apache.cassandra.dht.Murmur3Partitioner
commitlog_total_space_in_mb: -1
murmur3_partitioner_ignore_msb_bits: 12
auto_bootstrap: true
enable_sstables_mc_format: true
api_ui_dir: /opt/scylladb/swagger-ui/dist/
api_doc_dir: /opt/scylladb/api/api-doc/
```
**Logs**
```
[shard 0] repair - repair id 2 failed: std::runtime_error ({shard 0: std::runtime_error (Failed to repair for keyspace=test_keyspace, cf=test_keyspace_intervals, range=(-5370793244696977581, -5328668260210922544]), shard 1: std::runtime_error (Failed to repair for keyspace=test_keyspace, cf=test_keyspace_intervals, range=(-932048315410807253, -858081057500917632]), shard 2: std::runtime_error (Failed to repair for keyspace=test_keyspace, cf=test_keyspace_intervals, range=(-8207641162893696763, -8167358952841479574]), shard 3: std::runtime_error (Failed to repair for keyspace=test_keyspace, cf=test_keyspace_intervals, range=(-4216530378557687254, -4193096228690490921])})
```
With trace level logging:
```
[shard 1] repair - Got error in row level repair: std::runtime_error (row_diff.size() != set_diff.size())
```
**Stacktrace**
```
java.lang.RuntimeException: Repair job has failed with the error message: [2020-04-20 16:03:52,966] Repair session 2 failed
        at org.apache.cassandra.tools.RepairRunner.progress(RepairRunner.java:124)
        at org.apache.cassandra.utils.progress.jmx.JMXNotificationProgressListener.handleNotification(JMXNotificationProgressListener.java:77)
        at com.sun.jmx.remote.internal.ClientNotifForwarder$NotifFetcher.dispatchNotification(ClientNotifForwarder.java:583)
        at com.sun.jmx.remote.internal.ClientNotifForwarder$NotifFetcher.doRun(ClientNotifForwarder.java:533)
        at com.sun.jmx.remote.internal.ClientNotifForwarder$NotifFetcher.run(ClientNotifForwarder.java:452)
        at com.sun.jmx.remote.internal.ClientNotifForwarder$LinearExecutor$1.run(ClientNotifForwarder.java:108)
```

**Comment by asias** [comment] 2020-04-21 01:25
Hello @jtnagashima, thanks for reporting. Can you share the logs with tracing level `--logger-log-level repair=trace`?  How many nodes in the cluster? Can you do a rolling restart for all the nodes in the cluster in case node see different feature sets during the upgrade? If it is a test cluster, I would suggest a full cluster shutdown and  restart and run the repair.

**Comment by jtnagashima** [comment] 2020-04-22 06:50
Logs are gathering now. It takes a long time to run with trace level logging. 
As for the cluster size, I'm running a 5 node cluster.
I'll perform a rolling restart once the repair is done and logs collected.
Thank you for looking into this @asias!

**Comment by asias** [comment] 2020-04-22 07:03
How often do you see the  "row_diff.size() != set_diff.size() error? Does it happen on all the table  or only on a specific table?

**Comment by jtnagashima** [comment] 2020-04-22 18:51
We see the error `row_diff.size() != set_diff.size()` consistently for one of the keyspaces that's fails the repair process. It happens on a specific table.

**Comment by asias** [comment] 2020-04-23 02:50
> We see the error `row_diff.size() != set_diff.size()` consistently for one of the keyspaces that fails the repair process. It happens on a specific table.

It will be much better to debug and solve this issue if you could provide me a way to reproduce. For example, if it is possible give me a script to create similar data for the problematic table.  You can insert garbage data instead of real data of course, as long as it reproduces. I can use it to reproduce locally.

**Comment by jtnagashima** [comment] 2020-04-23 03:23
> solve this issue if you could provide me a way to reproduce. 
No doubt. I'll see what I can do! Thanks for looking into this for us Asias.

**Comment by zooptwo** [comment] 2020-05-05 03:30
I also seem to have run into this same issue.  1 table fails on all nodes to repair.  I see this same error message I think  when it is running a compaction on the table.  but either way the repair fails.  We also recently upgraded from 3.0 - > 3.3  but we upgraded like this.  3.0.7 -> 3.0.11 -> 3.1.x -> 3.2.x -> 3.3.1

**Comment by jtnagashima** [comment] 2020-05-05 23:19
Hi Asias, try as I might, I cannot seem to find a way to reproduce this issue - and the issue still persists with our existing cluster. We created a new debug keyspace and table using the same schema and a dump of the data contained in the problematic key range (as it was defined in logs):

`[shard 2] repair - repair id 18 on shard 2 failed: std::runtime_error (Failed to repair for keyspace=test_keyspace, cf= test_keyspace_intervals, range=(1974950939236351, 15955982054292879])`

However, a rebuild of that keyspace returned successfully. 🤷

**Comment by asias** [comment] 2020-05-06 00:35
Thanks @zooptwo @jtnagashima. It looks like the issue only triggers with keyspace created with older version.

@jtnagashima can you try `nodetool compact test_keyspace test_keyspace_intervals` on all nodes and run repair again for the range (1974950939236351, 15955982054292879] which triggered the issue.

**Comment by jtnagashima** [comment] 2020-05-06 18:32
The `nodetool compact` followed by the `nodetool repair` yielded the same results.  

However, I did manage to get the repairs working by performing a `nodetool flush test_keyspace test_keyspace_intervals` though!

**Comment by jtnagashima** [comment] 2020-05-06 19:15
Never mind, flushing the table is not working consistently. I attempted to flush another problematic keyspace table and it returned the same error as before.

**Comment by zooptwo** [comment] 2020-05-07 04:26
If I can provide more info that might be relative. In my case there are 3 partitions that are basically accessible.  pulling the specific token(primary_key) = ID generally always results in a timeout.  99% of the time otherwise the result is empty.    So some specific information here.  On this keyspace we have not be running repairs as they should be I have probably repaired the table 4 times over the course of 1+ years.   This is in part that I could never get scylla manager working right and that I never figured out how to get a repair running that would not just crush the database until it finished.  (Please give us incremental repairs or something. ;)  )    So that being  a failure on my part.  These particular partitions I know for one for one of them it was part of a large partition with about 700k rows.  which are all deleted.     problem is these rows have been delete for at least 6 months.  So I don't know why I still see the log entries about compacting a large partition.  I Have not caught anything about it failing, although I have not looked very hard.    My guess is that all data in the partition is marked as deleted and that compaction is somehow just skipping over it as it might have nothing to do, but selecting from this Partition suffers because of the large amount of tombstones.  Although I would expect it to be able to deal with 700k.    I am making a lot of assumptions here, but My best guess is these large fully deleted partitions that were not able to be compacted away for whatever reason is causing various problems.  1 repairs not able to finish and 2 queries not able to complete.   I am happy to provide more data.  I believe I started an issue about this about 6 months ago as well when I started having timeouts selecting data.  FYI I basically was using the efficient table scan example provided by Scylla.    Sorry not trying to go on a tangent here just trying to provide enough information on what I have observed to see if we can come to any reasons why this might be failing.  Thanks..  Let me know what else I can provide or test.

**Comment by asias** [comment] 2020-05-07 07:56
@jtnagashima I am preparing you a rpm (latest 3.3 branch + patches to workaround the issue and add more debug info).  In case you can try it, you can upgrade the node runs repair cmd only and rerun the repair.  Share the logs with me.

**Comment by jtnagashima** [comment] 2020-05-07 08:47
@asias Good news! The compaction on the keyspaces prior to repairing seems to be working.  My guess is that we upgraded too rapidly to version 3.3 so the natural compactions process wasn't given enough time to update all the tables?

**Comment by asias** [comment] 2020-05-07 08:52
> @asias Good news! The compaction on the keyspaces prior to repairing seems to be working. My guess is that we upgraded too rapidly to version 3.3 so the natural compactions process wasn't given enough time to update all the tables?

Thanks @JacobJohansen . I have a mixed feeling ;-) I am happy to see the issue is gone for you but the reproducer is gone too.  The above rpm is supposed to give us more insights on the issue.

**Comment by asias** [comment] 2020-05-07 09:01
@jtnagashima do you have a lots of deletes on the table with repair issue?

**Comment by jtnagashima** [comment] 2020-05-07 17:31
@asias quite the contrary, we actually never delete.

**Comment by zooptwo** [comment] 2020-05-07 18:12
Asias, I might be able to take a snapshot of my table and send it to you.  it is a 3 node cluster in this case should be a fairly small table. I would guess under 1GB

**Comment by asias** [comment] 2020-05-08 02:02
> @asias quite the contrary, we actually never delete.

OK. Do you have a lot of "updates"?

**Comment by asias** [comment] 2020-05-08 02:05
> Asias, I might be able to take a snapshot of my table and send it to you. it is a 3 node cluster in this case should be a fairly small table. I would guess under 1GB

That would be nice. It is easier if you send full content of /var/lib/scylla from all 3 nodes (I need the system tables. You can delete sstables of other user  tables and only  keep the problematic table).

**Comment by zooptwo** [comment] 2020-05-08 05:49
If I take a snapshot of the system tables with the problem table is that ok?  Seems like it would be easier for me.

**Comment by asias** [comment] 2020-05-08 06:03
> If I take a snapshot of the system tables with the problem table is that ok? Seems like it would be easier for me.

OK. I will try. Please also send me the schema of the table. 
 
cql > DESCRIBE KEYSPACE keyspace_contains_the_problematic_table

**Comment by jtnagashima** [comment] 2020-05-08 17:09
> OK. Do you have a lot of "updates"?

We store quite a bit of time series data so we almost entirely perform inserts on our tables.

**Comment by slivne** [comment] 2020-05-20 06:22
@jtnagashima any update - can you please provide the additional information requested.

**Comment by jtnagashima** [comment] 2020-05-20 19:50
Hi Shlomi! Our cluster is performing normally every since Asias recommended manually running  compactions on the problematic tables. Unfortunately, we're out of capacity to provide the data to replicate the scenario. We do believe the issue resulted from upgrading too quickly from one version to the next thereby preventing the compactions to throughly run on our cluster.

**Comment by avikivity** [comment] 2020-07-15 11:49
Backported to 4.0, 4.1, 4.2.

**Comment by asias** [comment] 2020-07-30 08:41
The patch "repair: Relax size check of get_row_diff and set_diff" is supposed to fix this specific issue. I am closing it.

**Closed by asias** 2020-07-30 08:41 UTC
Labels: User Request, bug, high, repair

**Comment by FlorianHockmann** [comment] 2021-05-25 11:30
We just ran into this issue with our cluster after updating the (3) nodes from 3.0 to 3.1. We also ran `nodetool compact` and then tried the repair again as it was suggested [above](https://github.com/scylladb/scylla/issues/6252#issuecomment-624379956), but we still see the error when we execute a repair.
Is there anything else we can try?

To give some more context, our cluster was still on 2.1 and we're now following the recommended upgrade path to get to the most recent version again.

**Comment by asias** [comment] 2021-05-25 11:33
The 3.1 release is way too old and not supported. Please consider upgrading your cluster.

**Comment by FlorianHockmann** [comment] 2021-05-25 11:37
What do you mean with upgrading? We are currently upgrading our cluster but the suggested upgrade path is to go through all minor version which is why we are currently on 3.1. Are you suggesting that we just upgrade immediately to 4.4 or that we ignore the error for now and just proceed with the upgrade path and then retry the repair later when we are on a supported version?

**Comment by asias** [comment] 2021-05-25 12:08
> What do you mean with upgrading? We are currently upgrading our cluster but the suggested upgrade path is to go through all minor versions which is why we are currently on 3.1. Are you suggesting that we just upgrade immediately to 4.4 or that we ignore the error for now and just proceed with the upgrade path and then retry the repair later when we are on a supported version?

Upgrade from 3.1, 3.2 ...4.0, ... 4.4 then run repair.

**Comment by FlorianHockmann** [comment] 2021-05-25 12:26
But don't we have to execute a repair still at least weekly (or more regularly than `gc_grace_seconds`) in order to not run into inconsistent data?
We only manage to update a minor version every one or two days as taking the snapshots and copying them to another location takes so long. So, it will definitely take more than a week for us to reach 4.4 if we continue with the upgrade like this.

Would it be an alternative maybe to stop all clients that can modify data and then upgrade through all minor versions til 4.4 as we then don't need to take any snapshots any more since the data won't change any way? Or could it lead to problems if we upgrade _too fast_ like it was speculated [in one of the comments earlier in this thread](https://github.com/scylladb/scylla/issues/6252#issuecomment-625119439)? (We have dedicated services for upserting the data which we could stop easily for a few days if it would make the upgrade much easier.)

**Comment by asias** [comment] 2021-05-26 01:34
> But don't we have to execute a repair still at least weekly (or more regularly than `gc_grace_seconds`) in order to not run into inconsistent data?
> We only manage to update a minor version every one or two days as taking the snapshots and copying them to another location takes so long. So, it will definitely take more than a week for us to reach 4.4 if we continue with the upgrade like this.
> 
> Would it be an alternative maybe to stop all clients that can modify data and then upgrade through all minor versions til 4.4 as we then don't need to take any snapshots any more since the data won't change any way? Or could it lead to problems if we upgrade _too fast_ like it was speculated [in one of the comments earlier in this thread](https://github.com/scylladb/scylla/issues/6252#issuecomment-625119439)? (We have dedicated services for upserting the data which we could stop easily for a few days if it would make the upgrade much easier.)

I see. If you could find a time window to stop the clients, you can speed up the upgrade. Even if you do not want to stop the clients, you can avoid do snapshots for each and every minor release upgrade.
