### ISSUE TITLE
UpdateItem does not yet support nested updates

### ISSUE THREAD

**Issue by Felix-zhoux** [scylladb/scylla#6732] opened 2020-06-30 02:39 UTC
*Installation details*
Scylla version (or git commit hash): 666.development-0.20200521.c29ccdea7
Cluster size: 1
OS (RHEL/CentOS/Ubuntu/AWS AMI): docker

When using the alterator table to perform the updateitem operation, the following error was reported. Check the introduction of the alterator and get the following information

```
DEBUG 2020-06-29 09:56:09,393 [shard 0] alternator-server - Skipping authorization
TRACE 2020-06-29 09:56:09,393 [shard 0] alternator-executor - update_item {"TableName":"bucket_stats","Key":{"bi":{"S":".dir.bucket1.1"},"uid":{"S":"liulan"}},"UpdateExpression":"SET sc.#sc.#total   = sc.#sc.#total + :size, sc.#sc.#total_r = sc.#sc.#total_r + :size, sc.#sc.#entries = sc.#sc.#entries + :num, sc.#sc.#actual  = sc.#sc.#actual + :size","ExpressionAttributeNames":{"#actual":"actual_size","#entries":"num_entries","#sc":"standard","#total":"total_size","#total_r":"total_size_rounded"},"ExpressionAttributeValues":{":num":{"N":"1"},":size":{"N":"1024"}}}
TRACE 2020-06-29 09:56:09,394 [shard 3] alternator-executor - update_item {"TableName":"bucket_stats","Key":{"bi":{"S":".dir.bucket1.1"},"uid":{"S":"liulan"}},"UpdateExpression":"SET sc.#sc.#total   = sc.#sc.#total + :size, sc.#sc.#total_r = sc.#sc.#total_r + :size, sc.#sc.#entries = sc.#sc.#entries + :num, sc.#sc.#actual  = sc.#sc.#actual + :size","ExpressionAttributeNames":{"#actual":"actual_size","#entries":"num_entries","#sc":"standard","#total":"total_size","#total_r":"total_size_rounded"},"ExpressionAttributeValues":{":num":{"N":"1"},":size":{"N":"1024"}}}
TRACE 2020-06-29 09:56:09,397 [shard 0] alternator-server - api_handler error case: {"__type":"com.amazonaws.dynamodb.v20120810#ValidationException","message":"UpdateItem does not yet support nested updates (FIXME)"}
```

`UpdateItem: Nested documents are supported but updates to nested attributes are not (e.g., SET a.b[3].c=val), and neither are nested attributes in condition expressions.`

Do we have plans to support updates to nested attributes and nested attributes in condition expressions? If so, when is it likely?

**Comment by nyh** [comment] 2020-06-30 07:45
This is a duplicate of issue #5024. 
We definitely have plans to support attribute paths (and not just top-level attributes), in the near future. I already finished writing all the relevant tests for it and hoping to start implementing the feature soon, probably starting with `ProjectionExpression` but `UpdateExpression`, `ConditionExpression` and `ReturnValues` will come next.
There are no major hurdles expected to implement this feature. Because Alternator stores top-level attributes as blobs, an expression like "SET a.b = :val" needs to be implemented as a read-modify-write operation: It needs to read the entire top-level attribute a, modify just a.b in it, and then write back the entire a. We already know how to do such read-modify-write operations safely (via LWT) so this is fine.

**Closed by nyh** 2020-06-30 07:45 UTC
Labels: Alternator

**Comment by nyh** [comment] 2021-02-14 10:39
@Felix-zhoux I added a pull request https://github.com/scylladb/scylla/pull/8066 which fully implements support for nested attribute paths - including in UpdateItem and in ConditionExpression which you asked above.

**Comment by Felix-zhoux** [comment] 2021-02-18 01:25
@nyh Thank you very much for your work!
