### ISSUE TITLE
scylla-jmx uses high CPU, possibly crashing

### ISSUE THREAD

**Issue by tvaillancourt** [scylladb/scylla#419] opened 2015-09-29 14:04 UTC
Hey guys,

I've noticed that at all times, Scylla-JMX is using a lot of CPU, a lot more than I would expected considering what this process does, but perhaps I am misunderstanding.

After looking bit closer at the high CPU, I have a suspicion that Java is crashing. Watching top, every few minutes all Java processes/threads for Scylla-JMX disappear and then come back as a new PID with high CPU, probably due to setting up Java, JIT, etc.

So far I haven't been able to grab a jstack from right before the crash. I was curious what details the Scylla team recommends I provide to assist with troubleshooting? Is it possible to enable debug logging under the Scylla-JMX process?

Here is a paste containing my environment, and also 2 process-lists (30 seconds apart) showing the the daemon is changing PIDs, and using 40-67% CPU.

EDIT: one missing detail I forgot is I've added the following to the JVM flags for the JMX process: "-Xms512M -Xmx512M -XX:NewSize=256M", to keep RAM in-check.

Paste: http://pastebin.com/ywFm5jxh

Thanks!

Tim

**Comment by avikivity** [comment] 2015-09-29 14:07
@amnonh please help

**Comment by amnonh** [comment] 2015-09-29 14:19
Hi Tim,
Can you please run journalctl and send me the output?
It might be a bit big so you can run it with the _PID of one of the dead
JMX process
Thanks,
Amnon

**Comment by tvaillancourt** [comment] 2015-09-29 14:26
Hi Amnon, found the error with journalctl. This is repeated over and over at the exact intervals I saw the original behavior. It looks like there may be a classpath (or similar) issue for SLF4J?

Paste: http://pastebin.com/59bwLEGx

Thanks again!

Tim

**Comment by amnonh** [comment] 2015-09-29 14:33
The issue is that the JMX proxy cannot connect to the scylla server and
after 30 seconds it will shutdown as can be seen by the line:
"API is not available, JMX is shuting down"

can you please send me the journalctl of the scylla server?

**Comment by tvaillancourt** [comment] 2015-09-29 14:40
Oh ok, this makes a lot of sense. In this case, this is not a bug.

I have recently changed my listen_address to use a non-localhost, 192.168.0.0/16 IP.

Is there a way to point Scylla-JMX to a different listen address? I checked /etc/sysconfig/scylla-jmx and only see the option to change the JMX_LOCAL_PORT. I think if a flag were to be added to modify this, /etc/sysconfig would be a fairly intuitive place.

Thanks again!

Tim

**Comment by amnonh** [comment] 2015-09-29 15:16
On Tue, Sep 29, 2015 at 5:40 PM, tvaillancourt <notifications@github.com>
wrote:

> Oh ok, this makes a lot of sense. In this case, this is not a bug.
>
> I have recently changed my listen_address to use a non-localhost,
> 192.168.0.0/16 IP.
>
> Is there a way to point Scylla-JMX to a different listen address? I
> checked /etc/sysconfig/scylla-jmx and only see the option to change the
> JMX_LOCAL_PORT. I think if a flag were to be added to modify this,
> /etc/sysconfig would be a fairly intuitive place.
>
> Thanks again!
>
The jmx_run script does not takes the listening address/port from config,
we will add this, but you can change it
currently so you can continue testing by editing the script.

Add to the beginning of the args list the flags for port and address
For example, if your API address is 192.168.1.5 and port 9991

Add inside the quotation:
-Dapiport=9991 -Dapiaddress=192.168.1.5

By default apiaddress is localhost so if it's only the port, you don't need
to change it

Tim

**Comment by tvaillancourt** [comment] 2015-09-29 15:37
Thank you!

"-Dapiaddress=<IPADDR>" is fixing my issue, the JMX daemon is no longer crashing.

Now that it is working fine, some feedback I'll provide is I've noticed the JMX daemon stil uses a fair amount of CPU, generally spiking to 40-50% CPU every 1-2 seconds. Is this daemon always doing work in the background, or does it only do work if there is a JMX request? In either case I am a bit surprised by the rate of CPU usage, but so far I don't think it is impacting me.

Cheers,

Tim

**Comment by slivne** [comment] 2015-10-07 12:15
@amnonh can you please respond

@tvaillancourt if there is no issue can you please close this item

**Comment by amnonh** [comment] 2015-10-07 13:14
There is a daemon that runs in the background and query the system, 50% seems high I'll check it again with our newer version and see what percentage I am getting.
Thanks,
Amnon

**Comment by penberg** [comment] 2015-10-29 13:49
@tvaillancourt @amnonh What's the status of this issue? Can we close it?

**Comment by slivne** [comment] 2015-12-15 13:20
@amnonh any update on this

**Comment by amnonh** [comment] 2015-12-15 13:26
I don't think there's an issue

**Comment by slivne** [comment] 2015-12-21 12:25
scylla-jmx by default find the address via scylla.yaml

**Closed by slivne** 2015-12-21 12:25 UTC
