### ISSUE TITLE
Scylla fails mysteriously when it doesn't have write permission to data directory

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/scylla#1563] opened 2016-08-09 15:06 UTC
The only clue is `Shutting down communications due to I/O errors ...`, but the we abort:

```
$  build/release/scylla -c2 --developer-mode=1 -m1G 
Scylla version 666.development-20160808.12b33de starting ...
WARN  2016-08-09 17:03:43,344 [shard 0] init - NOFILE rlimit too low (recommended setting 200000, minimum setting 10000; you may run out of file descriptors.
Scylla API server listening on 127.0.0.1:10000 ...
INFO  2016-08-09 17:03:43,348 [shard 0] database - Row: max_vector_size: 32, internal_count: 5
INFO  2016-08-09 17:03:43,348 [shard 1] database - Row: max_vector_size: 32, internal_count: 5
WARN  2016-08-09 17:03:43,352 [shard 0] storage_service - Shutting down communications due to I/O errors until operator intervention
INFO  2016-08-09 17:03:43,352 [shard 0] storage_service - Stop transport: starts
scylla: ./seastar/core/sharded.hh:439: Service& seastar::sharded<Service>::local() [with Service = gms::gossiper]: Assertion `local_is_initialized()' failed.
Aborted (core dumped)
```

**Comment by slivne** [comment] 2016-08-09 18:47
duplicate of #883

**Closed by slivne** 2016-08-09 18:47 UTC
Labels: bug, UX
