### ISSUE TITLE
Restarting causes an Unrecognized error: Refusing to boot

### ISSUE THREAD

**Issue by chb2mn** [scylladb/scylla#692] opened 2015-12-22 17:31 UTC
I'm running on a 5 node cluster, and after I have run cassandra-stress once, trying to restart a node causes a string of errors to appear: 

```
...
ERROR [shard 6] database - Unrecognized error while processing keyspace1-standard1-ka-65-TOC.txt: Refusing to boot
ERROR [shard 6] database - Unrecognized error while processing keyspace1-standard1-ka-73-TOC.txt: Refusing to boot
ERROR [shard 29] database - Unrecognized error while processing keyspace1-standard1-ka-59-TOC.txt: Refusing to boot
ERROR [shard 6] database - Unrecognized error while processing keyspace1-standard1-ka-61-TOC.txt: Refusing to boot
ERROR [shard 4] database - Unrecognized error while processing keyspace1-standard1-ka-61-TOC.txt: Refusing to boot
ERROR [shard 29] database - Unrecognized error while processing keyspace1-standard1-ka-74-TOC.txt: Refusing to boot
ERROR [shard 4] database - Unrecognized error while processing keyspace1-standard1-ka-58-TOC.txt: Refusing to boot
...
```

`$ sudo scylla -m32G`

I am running scylla in command line from $SCYLLA_HOME and using ctrl+C to exit.

Trying replicate with one node in a VM does not work

**Comment by slivne** [comment] 2015-12-22 20:32
@chb2mn  - can you please provide some additional information.


Which scylla version are you running  (the names of the installed packages / head if you have built from sources) ?

Which OS version is this running on 

What file system are you using ?

When you killed the node did it write anything to syslog - did it crash - can you copy paste the last messages of the node going down.

Can you please share the schema run cqlsh -e "describe schema" and provide the output

As you used cassandra-stress for the test - I assume the info is not confidential - can you please upload the files so we can download them and try to test this on our own.

Last is this reproducible - if you start from a clean cluster and do this again - will it happen - if there is a coredump can you please provide the backtrace.

**Comment by chb2mn** [comment] 2015-12-23 14:59
scylla version:

- scylla-server-0.13.2-20151217.37dfe9c.el7.centos.x86_64
- scylla-tools-0.13.2-20151217.19208f6.el7.centos.noarch
- scylla-jmx-0.13.2-20151217.7059795.el7.centos.noarch

OS:
- Centos 7

FS:
- XFS

C*-stress:
- I was using the default C*-stress schema, but I'll attach my redacted conf/scylla.yaml (just removing the seed ips, listen_address, and rpc_host)

Failure state:
- I was running scylla in command line and used ctrl+C, I was logging to stdout and nothing was printed, so I assume a clean exit
- When restarting scylla, attached is a dump of the output:

[scylla.yaml.txt](https://github.com/scylladb/scylla/files/70896/scylla.yaml.txt) *all IPs removed with [ip here] everything else is the same
[scylla_error_dump.txt](https://github.com/scylladb/scylla/files/70895/scylla_error_dump.txt)

Reproducability:
- I can't exactly clean the cluster, but starting from a fresh install of scylla 0.13.2 (same version as above) has the same results

Schema:
```
[user@node1 ~]$ cqlsh -e "describe schema"

CREATE KEYSPACE keyspace1 WITH replication = {'class': 'SimpleStrategy', 'replication_factor': '1'}  AND durable_writes = true;

CREATE TABLE keyspace1.standard1 (
    key blob PRIMARY KEY,
    "C0" blob,
    "C1" blob,
    "C2" blob,
    "C3" blob,
    "C4" blob
) WITH COMPACT STORAGE
    AND bloom_filter_fp_chance = 0.01
    AND caching = '{"keys":"ALL","rows_per_partition":"ALL"}'
    AND comment = ''
    AND compaction = {'class': 'SizeTieredCompactionStrategy'}
    AND compression = {}
    AND dclocal_read_repair_chance = 0.1
    AND default_time_to_live = 0
    AND gc_grace_seconds = 864000
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair_chance = 0.0
    AND speculative_retry = '99.0PERCENTILE';
```

**Comment by slivne** [comment] 2015-12-23 15:18
@chb2mn 

Thanks

can you please run ```uname -a``` - so we have the exact version of OS you are using and ```rpm -qa | grep xfs```

scylla may have not created a coredump because of an env setting can you please check ```ulimit -c```
if the value is < 32 G then it may have not created one because of this setting - can you please try and set
``` ulimit -c unlimited ``` and then try to reproduce.

If a core is created - it will allow us better to understand the issue

Can you please share a sstable file that scylla reports an error on "Unrecognized error while processing keyspace1-standard1-ka-1238-TOC.txt: Refusing to boot" (e.g. all the keyspace1-standard1-ka-1238.*)

With the above information (version, schema and a sample) we can reproduce at least the issue at reboot

**Comment by chb2mn** [comment] 2015-12-23 15:48
`uname -a`:
- Linux 3.10.0-123.el7.x86_64 #1 SMP Mon Jun 30 12:09:22 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

sstable file:
[keyspace1-standard1-ka-52-TOC.txt](https://github.com/scylladb/scylla/files/70957/keyspace1-standard1-ka-52-TOC.txt)

still working on getting a coredump...

**Comment by slivne** [comment] 2015-12-23 16:07
Christopher can you please provide the other files not only the TOC file (
keyspace1-standard1-ka-52-
<https://github.com/scylladb/scylla/files/70957/keyspace1-standard1-ka-52-TOC.txt>
*)

**Comment by chb2mn** [comment] 2015-12-23 16:18
schwoops:

[keyspace1-standard1-ka-52.zip](https://github.com/scylladb/scylla/files/70991/keyspace1-standard1-ka-52.zip)

**Comment by chb2mn** [comment] 2015-12-28 19:10
I believe the error occurs when more than one seed is present

**Comment by slivne** [comment] 2015-12-28 22:28
Christopher thanks

We are still investigating this.

I have been able to use the files you shared keyspace1-standard1-ka-52 and
validate that if I create the scehma and place the files you provided in
the zup - there is no issue in reading them (this was conducted on
Feadora22 using 0.13.2) so the raw files (including the TOC) seem to be in
correct format and readable.

Next step is to check this on CentOS 7.

Can you please check two more items

1. run ulimit -a (on the machine running scylla from the account you ran
scylla)

When I decreased the number of allowed open files (ulimit -n) I received an
error similar to yours - yet had others as well

```
ERROR [shard 0] database - Unrecognized error while processing
system-compaction_history-ka-1-TOC.txt: Refusing to boot
ERROR [shard 1] database - Unrecognized error while processing
system-schema_columnfamilies-ka-2-TOC.txt: Refusing to boot
WARNING: exceptional future ignored of type 'std::system_error': Error
system:24 (Too many open files)
WARNING: exceptional future ignored of type 'std::runtime_error': first key
of summary is empty
WARNING: exceptional future ignored of type 'std::runtime_error': first key
of summary is empty
Exiting on unhandled exception of type 'std::system_error': Error system:24
(Too many open files)
```

2. can you try and boot scylla with the "--default-log-level debug" this
will add additional logging during the boot that may help in analyzing the
issue

**Comment by chb2mn** [comment] 2015-12-29 17:07
Avast! @slivne, your are right. I believe we have cornered the issue:

root (because I'm running as sudo) didn't have enough file descriptors, and because I was running with sudo, I needed to add 
```
root    soft       nofile     100000
root    hard       nofile     100000
``` 
to /etc/security/limits.conf, not do `sudo su root` `ulimit -n 100000`

Changing the FD limit seems to solve the problem, but it's odd that all of the "unrecognized error" messages are printed and somewhere in the middle is the actual FD limit error.

Anyway, thank you all! I'm comfortable closing this issues if @slivne and @avikivity are.

**Comment by avikivity** [comment] 2015-12-29 17:15
I'd like to add a startup check of the limit, and refuse to boot unless the limit is sane (unless --developer-mode is provided).

**Comment by nyh** [comment] 2015-12-29 17:30
Shlomi, the messages you saw like
```
WARNING: exceptional future ignored of type 'std::system_error': Error system:24 (Too many open files)
WARNING: exceptional future ignored of type 'std::runtime_error': first key of summary is empty
``` 
warn us that some exceptions were ignored (which is usually a bug or omission in our code). This shouldn't have happened, and should be fixed.

The only interesting message is the final one: Exiting on unhandled exception of type 'std::system_error': Error system:24 (Too many open files). This points directly to the too-small open file limit, and if we didn't have a hundred other irrelevant messages, he would have seen this immediately.

**Comment by slivne** [comment] 2015-12-29 20:35
@nyh

Christopher shared all the logs the logs he got had

Start Storage service ...
ERROR [shard 8] database - Unrecognized error while processing
keyspace1-standard1-ka-1238-TOC.txt: Refusing to boot
ERROR [shard 12] database - Unrecognized error while processing
keyspace1-standard1-ka-1160-TOC.txt: Refusing to boot
ERROR [shard 16] database - Unrecognized error while processing
keyspace1-standard1-ka-1215-TOC.txt: Refusing to boot
....
[This repeats for many of the TOC files]
....
WARNING: exceptional future ignored of type 'std::runtime_error': first key
of summary is empty
WARNING: exceptional future ignored of type 'std::runtime_error': first key
of summary is empty
WARNING: exceptional future ignored of type 'std::runtime_error': first key
of summary is empty

So there was no indication that the "to many open files" is the issue -
this probably means that the limit in his case affected a different point
that either handled or converted the error differently.

Opened #730

Christopher thanks ... we will be happy to assist with any other
question/issue you find.

Shlomi

**Closed** 2015-12-29 20:35 UTC
Labels: bug
