### ISSUE TITLE
Exceptional future ignored: std::system_error (error system:22, accept4: Invalid argument) during shutdown in mc_sstables_case_sensitive_add_column_test

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#4927] opened 2019-08-29 12:57 UTC
Scylla version 036f51927ce4717bb8eee13c683afebd30b56809
Seen in [dtest-release/227/testReport/cql_additional_tests/TestCQL/mc_sstables_case_sensitive_add_column_test](https://jenkins.scylladb.com/job/scylla-master/job/dtest-release/227/testReport/cql_additional_tests/TestCQL/mc_sstables_case_sensitive_add_column_test/)

The tests fail with:
```
Nodetool command '/jenkins/workspace/scylla-master/dtest-release/scylla/.ccm/repository/3.11.3/bin/nodetool -h 127.0.45.1 -p 7145 refresh -- keyspace_for_mc_sstables columnfamily_for_mc_sstables' failed; exit status: 1; stderr: nodetool: Failed to connect to '127.0.45.1:7145' - ConnectException: 'Connection refused (Connection refused)'.
```

Node log: [dtest-release/227/artifact/logs-release.2/1567061062962_cql_additional_tests.TestCQL.mc_sstables_case_sensitive_add_column_test/node1.log](http://jenkins.scylladb.com/job/scylla-master/job/dtest-release/227/artifact/logs-release.2/1567061062962_cql_additional_tests.TestCQL.mc_sstables_case_sensitive_add_column_test/node1.log)
```
INFO  2019-08-29 06:43:35,760 [shard 0] init - Signal received; shutting down
INFO  2019-08-29 06:43:35,760 [shard 0] init - stopping compaction manager
INFO  2019-08-29 06:43:35,760 [shard 0] compaction_manager - Asked to stop
INFO  2019-08-29 06:43:35,760 [shard 0] compaction_manager - Stopped
INFO  2019-08-29 06:43:35,760 [shard 1] init - stopping compaction manager
INFO  2019-08-29 06:43:35,760 [shard 1] compaction_manager - Asked to stop
INFO  2019-08-29 06:43:35,760 [shard 1] compaction_manager - Stopped
INFO  2019-08-29 06:43:35,760 [shard 0] init - stopping view builder
INFO  2019-08-29 06:43:35,760 [shard 0] view - Stopping view builder
INFO  2019-08-29 06:43:35,760 [shard 1] view - Stopping view builder
INFO  2019-08-29 06:43:35,760 [shard 0] init - draining local storage
INFO  2019-08-29 06:43:35,760 [shard 0] storage_service - Drain on shutdown: starts
INFO  2019-08-29 06:43:35,760 [shard 0] storage_service - Stop transport: starts
INFO  2019-08-29 06:43:35,761 [shard 0] storage_service - Thrift server stopped
WARN  2019-08-29 06:43:35,761 [shard 0] seastar - Exceptional future ignored: std::system_error (error system:22, accept4: Invalid argument), backtrace:   0x30adeab
  0x2da62b4
  0x1101eb5
  0x110505b
  0x110537b
  0x2da47c1
  0x2da49de
  0x2e7aead
  0x2d4636d
  0x2d471e2
  0x6cedff
  /jenkins/workspace/scylla-master/dtest-release/scylla-dtest/../scylla/dynamic_libs/libc.so.6+0x24412
  0x72ffdd
seastar::report_failed_future(std::__exception_ptr::exception_ptr const&) at /jenkins/workspace/scylla-master/dtest-release/scylla/seastar/src/core/reactor.cc:5809
{lambda()#1}<seastar::bool_class<seastar::stop_iteration_tag> > seastar::futurize<seastar::bool_class<seastar::stop_iteration_tag> >::apply<cql_transport::cql_server::do_accepts(int, bool, seastar::socket_address)::{lambda()#1}::operator()() const::{lambda(seastar::future<seastar::accept_result>)#1}, seastar::accept_result>(cql_transport::cql_server::do_accepts(int, bool, seastar::socket_address)::{lambda()#1}::operator()() const::{lambda(seastar::future<seastar::accept_result>)#1}&&, seastar::accept_result&&) at /jenkins/workspace/scylla-master/dtest-release/scylla/seastar/include/seastar/core/future.hh:287
 (inlined by) ?? at /jenkins/workspace/scylla-master/dtest-release/scylla/seastar/include/seastar/core/future.hh:338
 (inlined by) ?? at /jenkins/workspace/scylla-master/dtest-release/scylla/seastar/include/seastar/core/future.hh:380
 (inlined by) ?? at /jenkins/workspace/scylla-master/dtest-release/scylla/seastar/include/seastar/core/future.hh:1306
 (inlined by) operator() at /jenkins/workspace/scylla-master/dtest-release/scylla/transport/server.cc:234
 (inlined by) apply<cql_transport::cql_server::do_accepts(int, bool, seastar::socket_address)::<lambda()>::<lambda(seastar::future<seastar::accept_result>)>, seastar::future<seastar::accept_result> > at /jenkins/workspace/scylla-master/dtest-release/scylla/seastar/include/seastar/core/future.hh:1426
seastar::future<seastar::accept_result>::then_wrapped_impl<cql_transport::cql_server::do_accepts(int, bool, seastar::socket_address)::{lambda()#1}::operator()() const::{lambda(seastar::future<seastar::accept_result>)#1}, seastar::future<seastar::bool_class<seastar::stop_iteration_tag> > >(cql_transport::cql_server::do_accepts(int, bool, seastar::socket_address)::{lambda()#1}::operator()() const::{lambda(seastar::future<seastar::accept_result>)#1}&&)::{lambda()#1}::operator()() const::{lambda(seastar::future_state<seastar::accept_result>&&)#1}::operator()({lambda()#1}) at /jenkins/workspace/scylla-master/dtest-release/scylla/seastar/include/seastar/core/future.hh:1116
seastar::continuation<seastar::future<seastar::accept_result>::then_wrapped_impl<cql_transport::cql_server::do_accepts(int, bool, seastar::socket_address)::{lambda()#1}::operator()() const::{lambda(seastar::future<seastar::accept_result>)#1}, seastar::future<seastar::bool_class<seastar::stop_iteration_tag> > >(cql_transport::cql_server::do_accepts(int, bool, seastar::socket_address)::{lambda()#1}::operator()() const::{lambda(seastar::future<seastar::accept_result>)#1}&&)::{lambda()#1}::operator()() const::{lambda(seastar::future_state<seastar::accept_result>&&)#1}, seastar::accept_result>::run_and_dispose() at /jenkins/workspace/scylla-master/dtest-release/scylla/seastar/include/seastar/core/future.hh:414
seastar::reactor::run_tasks(seastar::reactor::task_queue&) at /jenkins/workspace/scylla-master/dtest-release/scylla/seastar/src/core/reactor.cc:3825
seastar::reactor::run_some_tasks() [clone .part.3076] at /jenkins/workspace/scylla-master/dtest-release/scylla/seastar/src/core/reactor.cc:4252
seastar::reactor::run() at /jenkins/workspace/scylla-master/dtest-release/scylla/seastar/src/core/reactor.cc:4235
 (inlined by) seastar::reactor::run() at /jenkins/workspace/scylla-master/dtest-release/scylla/seastar/src/core/reactor.cc:4396
seastar::app_template::run_deprecated(int, char**, std::function<void ()>&&) at /jenkins/workspace/scylla-master/dtest-release/scylla/seastar/src/core/app-template.cc:199
seastar::app_template::run(int, char**, std::function<seastar::future<int> ()>&&) at /jenkins/workspace/scylla-master/dtest-release/scylla/seastar/src/core/app-template.cc:115
main at /jenkins/workspace/scylla-master/dtest-release/scylla/main.cc:506
```

Seen also with `mc_sstables_case_sensitive_delete_value_test`, `mc_sstables_case_sensitive_insert_test`, `mc_sstables_case_sensitive_update_value_test`

Seems to be reported from here:
https://github.com/scylladb/scylla/blob/036f51927ce4717bb8eee13c683afebd30b56809/transport/server.cc#L233-L237

**Comment by psarna** [comment] 2019-08-29 13:19
Am I assigned to this because it might be similar to https://github.com/scylladb/scylla/issues/4875? It looks like it might be a more generic problem, since it also spits out `terminate called without an active exception`, but aside from that I have no clue what might be the cause of it... It's beginning to look like a memory corruption somewhere else, since the backtraces from this issue and https://github.com/scylladb/scylla/issues/4875 sound absolutely unrelated, and yet both happen at shutdown and have similar symptoms.

**Comment by slivne** [comment] 2020-03-24 23:15
@xemul / @bhalevy did you handle this as part of the shutdown / startup rehawl ?

**Comment by xemul** [comment] 2020-03-25 04:11
No, AFAICS this is different

**Comment by slivne** [comment] 2020-04-15 20:44
seen here https://jenkins.scylladb.com/job/scylla-master/job/dtest-release/379/testReport/cql_additional_tests/TestCQL/mc_sstables_case_sensitive_add_column_test/

**Comment by slivne** [comment] 2021-01-24 21:09
the test has been passing for the last 200 builds on master - closing this issue - if it happens please reopen

**Closed by slivne** 2021-01-24 21:09 UTC
Labels: dtest
