### ISSUE TITLE
lwt_schema_modification_test: index_drop_add_test: schema_mismatch_error

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#6762] opened 2020-07-05 09:05 UTC
Regression seen in https://jenkins.scylladb.com//view/master/job/scylla-master/job/dtest-release/541//testReport/junit/lwt_schema_modification_test/LWTSchemaModificationTester/index_drop_add_test/
```
Traceback (most recent call last):
  File "/usr/lib64/python3.7/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/usr/lib64/python3.7/unittest/case.py", line 648, in run
    self.tearDown()
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/dtest.py", line 1085, in tearDown
    self.cleanUpCluster()
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/dtest.py", line 1129, in cleanUpCluster
    raise AssertionError('Unexpected errors found: {}'.format(found_errors))
AssertionError: Unexpected errors found: [('node4', ['ERROR 2020-07-05 01:30:29,239 [shard 3] storage_proxy - exception during mutation write to 127.0.72.4: seastar::internal::backtraced<schema_mismatch_error> (Attempted to deserialize schema-dependent object of version 85937175-d625-3900-8758-ddf27d73b99b using lwt_load_ks.table1 bde8d7bf-627c-39d8-82d1-eeb04493cde8 Backtrace:    0x32b6a7d'])]
```

Scylla version 8e3ecc30a9dbc6ff53e09fb671c2023aa0d21fa1
scylladb/scylla-dtest@4ef71b011743535bb494a7de0f8a7a0091241af6

@alecco @kostja please look into this

**Comment by bhalevy** [comment] 2020-07-05 09:08
https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/541/artifact/logs-release.2/1593913232001_lwt_schema_modification_test.LWTSchemaModificationTester.index_drop_add_test/node4.log
```
INFO  2020-07-05 01:30:29,194 [shard 0] schema_tables - Altering lwt_load_ks.table1 id=127e5060-be5f-11ea-a678-000000000000 version=bde8d7bf-627c-39d8-82d1-eeb04493cde8
INFO  2020-07-05 01:30:29,194 [shard 0] schema_tables - Creating lwt_load_ks.table1_v_idx_index id=1bbd9000-be5f-11ea-9d17-000000000003 version=80c6f05b-f159-3852-bc34-c3992bfb538d
INFO  2020-07-05 01:30:29,199 [shard 0] query_processor - Column definitions for lwt_load_ks.table1 changed, invalidating related prepared statements
INFO  2020-07-05 01:30:29,199 [shard 2] query_processor - Column definitions for lwt_load_ks.table1 changed, invalidating related prepared statements
INFO  2020-07-05 01:30:29,200 [shard 1] query_processor - Column definitions for lwt_load_ks.table1 changed, invalidating related prepared statements
INFO  2020-07-05 01:30:29,211 [shard 3] query_processor - Column definitions for lwt_load_ks.table1 changed, invalidating related prepared statements
ERROR 2020-07-05 01:30:29,239 [shard 3] storage_proxy - exception during mutation write to 127.0.72.4: seastar::internal::backtraced<schema_mismatch_error> (Attempted to deserialize schema-dependent object of version 85937175-d625-3900-8758-ddf27d73b99b using lwt_load_ks.table1 bde8d7bf-627c-39d8-82d1-eeb04493cde8 Backtrace:    0x32b6a7d
   0x32b6d90
   0x32b7219
   0xfdac83
   0xfdad96
   0xfd25a5
   0xe90c10
   0xdec1c7
   0xe1e79f
   0xe1edf8
   0xe20c92
   0x2d9a1c6
   0x2e03757
   0x2e03ace
   0x2e3abed
   0x2e4a5ea
   0x2dce88d
   /jenkins/workspace/scylla-master/dtest-release/scylla/.ccm/scylla-repository/8e3ecc30a9dbc6ff53e09fb671c2023aa0d21fa1/scylla//opt/scylladb/libreloc/libpthread.so.0+0x9431
   /jenkins/workspace/scylla-master/dtest-release/scylla/.ccm/scylla-repository/8e3ecc30a9dbc6ff53e09fb671c2023aa0d21fa1/scylla//opt/scylladb/libreloc/libc.so.6+0x1019d2
   --------
   seastar::lambda_task<seastar::execution_stage::flush()::{lambda()#1}>
)
INFO  2020-07-05 01:30:29,251 [shard 0] database - Schema version changed to ac9dbfc6-0704-3d67-a65e-6dd39cd6b7e4
```

Is this a benign error message?
If so, should it be in warning severity?
otherwise, it should be added to the test's `ignore_log_patterns`

**Comment by kostja** [comment] 2020-07-06 08:24
This looks like a duplicate of https://github.com/scylladb/scylla/issues/6074 
For now we should add it to ignore_log_patterns.

**Comment by kostja** [comment] 2020-07-06 08:25
@alecco could you please extend ignore_log_patterns until #6074 is fixed?

**Comment by slivne** [comment] 2020-07-16 15:41
dtest patch waiting to be merged

**Closed** 2020-07-19 22:22 UTC
Labels: dtest
