### ISSUE TITLE
Scylla Docker 4.6 failed to start by default

### ISSUE THREAD

**Issue by kokizzu** [scylladb/scylla#10239] opened 2022-03-17 19:52 UTC
- [x] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash): 4.6
Cluster size: 1
OS (RHEL/CentOS/Ubuntu/AWS AMI): Docker

detail here: https://github.com/scylladb/scylla-doc-issues/issues/843

**Comment by nyh** [comment] 2022-03-20 08:25
This looks like a duplicate of #10237. I'll close this one and comment there.

**Closed by nyh** 2022-03-20 08:25 UTC
