### ISSUE TITLE
scylla.yaml file missing the internode_compression default value

### ISSUE THREAD

**Issue by nirmaayan** [scylladb/scylla#3226] opened 2018-02-21 14:17 UTC
Current scylla.yaml internode_compression

```
# internode_compression controls whether traffic between nodes is
# compressed.
# can be:  all  - all traffic is compressed
#          dc   - traffic between different datacenters is compressed
#          none - nothing is compressed.
# internode_compression: none
```
Need to add default to none

**Comment by vladzcloudius** [comment] 2018-02-21 14:54
I think the better way to fix this is to make the `--help` output have default values for all parameters: https://github.com/scylladb/scylla/issues/3227

scylla.yaml is not supposed to have all possible parameters and their default values. Therefore even if we fix it for this particular one, tomorrow we'll have the same issue for a different one.

**Comment by slivne** [comment] 2018-02-22 10:29
The copy paste from above does exist in the scylla.yaml

https://github.com/scylladb/scylla/blob/master/conf/scylla.yaml#L745

not clear to me what is missing

**Comment by nirmaayan** [comment] 2018-02-22 10:32
Which Scylla version
I tested on 2.0

**Comment by tzach** [comment] 2018-02-22 12:32
@nirmaayan the issue is unclear
Look like `internode_compression` exists in the scylla.yaml file with a description
It was there in scylla 2.0 as well

> I tested on 2.0

What did you test? please elaborate

**Comment by nirmaayan** [comment] 2018-02-22 12:41
In the first message we have the yaml output. 
It doesn’t say what is the default value. 
We just need to add it next to none. 
So when user wants to set it in the yaml he will also knows what’s the default value. 

Not only by using  - - help

**Comment by tzach** [comment] 2018-02-25 12:10
Closing as `internode_compression` is in scylla.yaml

**Closed by tzach** 2018-02-25 12:10 UTC
