### ISSUE TITLE
Failed to create/update counter after deletion

### ISSUE THREAD

**Issue by rr32btg** [scylladb/scylla#4781] opened 2019-07-30 17:22 UTC
Hello. Sorry for bad English.

I found counters related bug:

1. I'm creating a counter by running an update query with counter value +1. 
2. Then I'm deleting this counter by running delete query.
3. Then I'm trying to run update query with +1 to value for counter with the same id, but counter not appear in DB until the whole table recreated.

how to reproduce this bug: 

```
# create container
$ docker run -tid --name scylla -p 9042:9042 scylladb/scylla:3.0.9
# wait for some time until the container fully starts
$ docker exec -ti scylla cqlsh
```

```
# create keyspace
cqlsh> CREATE KEYSPACE test WITH replication = {'class': 'SimpleStrategy', 'replication_factor': 1};
# select keyspace 
cqlsh> USE test;
# create table
cqlsh:test> CREATE TABLE counters (type ascii, id uuid, value counter, PRIMARY KEY(type, id));
# insert counter
cqlsh:test> UPDATE counters SET value = value + 1 WHERE type = 'some_type' AND id = uuid();

# check that counter creation was success
cqlsh:test> SELECT * FROM counters ;

 type      | id                                   | value
-----------+--------------------------------------+-------
 some_type | 09770c82-2ebe-4355-a7f9-9ac8744bc968 |     1

# delete counter record
cqlsh:test> DELETE FROM counters WHERE type = 'some_type' AND id = 09770c82-2ebe-4355-a7f9-9ac8744bc968;

# try to insert same counter
cqlsh:test> UPDATE counters SET value = value + 1 WHERE type = 'some_type' AND id = 09770c82-2ebe-4355-a7f9-9ac8744bc968;

# query return no errors

# look into counter table but there is no counter visible 
cqlsh:test> SELECT * FROM counters ;

 type | id | value
------+----+-------


# drop table 
cqlsh:test> DROP TABLE counters ;

# recreate table
cqlsh:test> CREATE TABLE counters (type ascii, id uuid, value counter, PRIMARY KEY(type, id));

# try to insert same counter
cqlsh:test> UPDATE counters SET value = value + 1 WHERE type = 'some_type' AND id = 09770c82-2ebe-4355-a7f9-9ac8744bc968;

# check insertion - now it works again
cqlsh:test> SELECT * FROM counters ;

 type      | id                                   | value
-----------+--------------------------------------+-------
 some_type | 09770c82-2ebe-4355-a7f9-9ac8744bc968 |     1
```

*Installation details*
Scylla version: 3.0.9-0.20190724.dea4489
Cluster size: 1 dev machine
OS: Mac OS

*Hardware details (for performance issues)* 
Platform: docker (docker engine v. 18.09.2)

**Comment by glommer** [comment] 2019-07-30 17:58
On Tue, Jul 30, 2019 at 1:22 PM Alexander Kusakin <notifications@github.com>
wrote:

> Hello. Sorry for bad English.
>
> I found counters related bug:
>
>    1. I'm creating a counter by running an update query with counter
>    value +1.
>    2. Then I'm deleting this counter by running delete query.
>    3. Then I'm trying to run update query with +1 to value for counter
>    with the same id, but counter not appear in DB until the whole table
>    recreated.
>
>
that's not a bug.
Counters that are deleted cannot be reused.

**Comment by tzach** [comment] 2019-07-30 18:41
Closing, this is a documented limitation.
https://docs.scylladb.com/getting-started/types/#counters

**Comment by rr32btg** [comment] 2019-07-30 20:05
Thank you for the explanation. I thought Scylla behaves like Cassandra in this case.

**Comment by glommer** [comment] 2019-07-30 20:07
It does:
https://stackoverflow.com/questions/13653681/apache-cassandra-delete-from-counter

**Comment by rr32btg** [comment] 2019-07-30 20:55
I'm sorry, but no it is not (at least in current dockerized version):


<img width="912" alt="screenshot 2019-07-30 at 23 52 35" src="https://user-images.githubusercontent.com/11302054/62164602-628bc600-b325-11e9-97b4-42132055b4c0.png">

**Comment by glommer** [comment] 2019-07-30 20:58
That's not their documented behavior and it's the first time I hear about
that.

We should have someone take a look at this in this case to validate.

**Comment by glommer** [comment] 2019-07-30 20:58
@slivne can we validate this behavior from Cassandra ?

**Comment by glommer** [comment] 2019-07-30 20:59
We will validate this, but in the mean time I can confirm that this is the behavior you should expect from Scylla - at least in the short term.

**Comment by tzach** [comment] 2019-08-01 13:42
@rr32btg the Apache Cassandra behavior you see is accidental.
If Cassandra restart after the delete and before the update, the counter value will not be saved

```
cqlsh:mykeyspace> UPDATE counters SET value = value + 1 WHERE type = 'some_type' AND id = b5641216-3626-4247-bc7b-7e3e925b873f;
cqlsh:mykeyspace> SELECT * FROM counters ;

 type      | id                                   | value
-----------+--------------------------------------+-------
 some_type | b5641216-3626-4247-bc7b-7e3e925b873f |     3

(1 rows)
cqlsh:mykeyspace> DELETE FROM counters WHERE type = 'some_type' AND id = b5641216-3626-4247-bc7b-7e3e925b873f;
cqlsh:mykeyspace> SELECT * FROM counters ;

 type | id | value
------+----+-------

root@0a214ec1f5e5:/# nodetool flush
root@0a214ec1f5e5:/# nodetool compact
docker restart some-cassandra

cqlsh:mykeyspace> UPDATE counters SET value = value + 1 WHERE type = 'some_type' AND id = b5641216-3626-4247-bc7b-7e3e925b873f;
cqlsh:mykeyspace> SELECT * FROM counters ;

 type      | id                                   | value
-----------+--------------------------------------+-------
 some_type | b5641216-3626-4247-bc7b-7e3e925b873f |     1
```

Tested with Cassandra 3.11.4
The counter is temporarily saved in memory (maybe on cache), but it is not guaranteed and not persistent.

 Closing again, feel free to reopen and continue the discussion :)

**Closed** 2019-08-01 16:30 UTC

**Comment by AttilaW-Keytiles** [comment] 2022-02-08 20:09
Actually with Cassandra the case is exactly the same in 2021-Nov, version 4.0.1 ...
Given the fact rebooting C* nodes is not a very often happening event compared to how many times we delete records during normal operation I think we can say that practically speaking: in Cassandra counters are recreated...
