### ISSUE TITLE
Scylla 2.3 cfstats reporting incorrect max partition size for views

### ISSUE THREAD

**Issue by veramine** [scylladb/scylla#3685] opened 2018-08-10 14:05 UTC
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [X] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash): 2.3.rc1-0.20180726.adad12ddc
Cluster size: 1
OS (RHEL/CentOS/Ubuntu/AWS AMI): CentOS 7.4

Nodetool cfstats is reporting incorrect max partition size for some views.  After running manual compaction, the values are correct again.  After restarting the database, the values are off again.  Here are two examples from our single node cluster:

```
Keyspace: veraminetest
	Read Count: 0
	Read Latency: NaN ms.
	Write Count: 479620
	Write Latency: 2.4838830741003297E-4 ms.
	Pending Flushes: 0
		Table: detections_by_systemguid
		SSTable count: 20
		SSTables in each level: [20/4]
		Space used (live): 14.07 GB
		Space used (total): 14.07 GB
		Space used by snapshots (total): 0 bytes
		Off heap memory used (total): 145.17 MB
		SSTable Compression Ratio: 0.347762
		Number of keys (estimate): 173166
		Memtable cell count: 1512
		Memtable data size: 93.27 MB
		Memtable off heap memory used: 141.25 MB
		Memtable switch count: 275
		Local read count: 0
		Local read latency: NaN ms
		Local write count: 479640
		Local write latency: 0.248 ms
		Pending flushes: 0
		Bloom filter false positives: 0
		Bloom filter false ratio: 0.00000
		Bloom filter space used: 87.72 KB
		Bloom filter off heap memory used: 87.7 KB
		Index summary off heap memory used: 3.84 MB
		Compression metadata off heap memory used: 0 bytes
		Compacted partition minimum bytes: 104 bytes
		Compacted partition maximum bytes: 8388608 TB
		Compacted partition mean bytes: 179.01 KB
		Average live cells per slice (last five minutes): 0.0
		Maximum live cells per slice (last five minutes): 0
		Average tombstones per slice (last five minutes): 0.0
		Maximum tombstones per slice (last five minutes): 0
```

```
Keyspace: veraminetest
    Read Count: 0
    Read Latency: NaN ms.
    Write Count: 47
    Write Latency: 4.2553191489361704E-5 ms.
    Pending Flushes: 0
        Table: smbshares_lastshareid
        SSTable count: 12
        SSTables in each level: [12/4]
        Space used (live): 612.87 MB
        Space used (total): 612.87 MB
        Space used by snapshots (total): 0 bytes
        Off heap memory used (total): 659.64 KB
        SSTable Compression Ratio: 0.207443
        Number of keys (estimate): 819
        Memtable cell count: 47
        Memtable data size: 448.99 KB
        Memtable off heap memory used: 640 KB
        Memtable switch count: 0
        Local read count: 0
        Local read latency: NaN ms
        Local write count: 47
        Local write latency: 0.046 ms
        Pending flushes: 0
        Bloom filter false positives: 0
        Bloom filter false ratio: 0.00000
        Bloom filter space used: 1 KB
        Bloom filter off heap memory used: 1008 bytes
        Index summary off heap memory used: 18.66 KB
        Compression metadata off heap memory used: 0 bytes
        Compacted partition minimum bytes: 0 bytes
        Compacted partition maximum bytes: 8388608 TB
        Compacted partition mean bytes: 192.54 KB
        Average live cells per slice (last five minutes): 0.0
        Maximum live cells per slice (last five minutes): 0
        Average tombstones per slice (last five minutes): 0.0
        Maximum tombstones per slice (last five minutes): 0
```

**Comment by tzach** [comment] 2018-08-12 07:59
@duarten please take a look

**Comment by duarten** [comment] 2018-08-12 08:29
@tzach I'll let someone take a look. It's not related to views since we don't have any special code for that.

**Comment by duarten** [comment] 2018-08-12 10:29
Related to #3586.

**Comment by slivne** [comment] 2018-10-07 08:33
@juliayakovlev / @roydahan when we run longevity for MV/SI lets look at the nodetool cfstats

**Comment by glommer** [comment] 2018-11-16 14:59
This seems like a duplicate of #3916 

I just sent a patch. Indeed it would be nice to add tests to make sure that the size estimates are not completely bogus.

**Comment by glommer** [comment] 2018-11-16 14:59
@veramine see, duarte is not the only one fixing bugs.

**Comment by slivne** [comment] 2018-11-25 11:50
@juliayakovlev - can you please try and run nodetool cfstats while we run the longevity tests on 3.0 - lets see if this shows up on 3.0

please provide the info on the exact version (git commit) you have tested this on

**Comment by slivne** [comment] 2018-11-27 09:41
thanks ...

closing this issue; followings glauber's fix we haven't been able to reproduce the issue.

**Closed by slivne** 2018-11-27 09:41 UTC
Labels: bug
