### ISSUE TITLE
Abort in artifact-test on ubuntu14: fail to start scylla-server

### ISSUE THREAD

**Issue by amoskong** [scylladb/scylla#2310] opened 2017-04-25 10:57 UTC
*Installation details*
Scylla version (or git commit hash): 1.7.rc2-0.20170328.9b26a57 
Cluster size: 1
OS (RHEL/CentOS/Ubuntu/AWS AMI): Ubuntu 14.04

Other OS:
1.7.rc2-0.20170328.9b26a57 works well on CentOS, [Jenkins artifact-test job](http://jenkins.cloudius-systems.com/job/scylla-1.7-centos-rpm-test-amostmp/label=muninn/4/artifact/latest/job.log)

Description: 
Failed to start scylla server, execute 'service scylla-server start' command for many times, then get the backtrace:

```
scylla: core/reactor.cc:479: void reactor_backend_epoll::abort_fd(pollable_fd_state&, std::__exception_ptr::exception_ptr, promise<> pollable_fd_state::*, int): Assertion `r == 0' failed.
Aborting on shard 0.
Backtrace:
  0x00000000004cbfba
  0x00000000004cc0d3
  0x00007f9ab252932f
  0x00007f9ab218ac36
  0x00007f9ab218e027
  0x00007f9ab2183bf5
  0x00007f9ab2183ca1
  0x00000000004e1c51
  0x00000000004e1cc4
  0x00000000005c2c5e
  0x00000000005c2e04
  0x00007f9ab2190825
  0x00007f9ab21900e6
  0x00007f9ab21901f4
  0x00007f9ab2175f4b
  0x00000000004c99c1
```

Full Upstart log:
```
root@ubuntu14:/var/log/upstart# cat scylla-server.log 
tuning /sys/devices/pci0000:00/0000:00:07.0/virtio2/block/vda/vda1
tuning /sys/devices/pci0000:00/0000:00:07.0/virtio2/block/vda
already tuned: /sys/devices/pci0000:00/0000:00:07.0/virtio2/block/vda/queue/scheduler
tuning: /sys/devices/pci0000:00/0000:00:07.0/virtio2/block/vda/queue/nomerges 2
tuning /sys/devices/pci0000:00/0000:00:07.0/virtio2/block/vda/vda1
Scylla version 1.7.rc0-0.20170219.2cd019e starting ...
hugeadm:WARNING: Directory /var/lib/hugetlbfs/pagesize-2MB is already mounted.
tuning /sys/devices/pci0000:00/0000:00:07.0/virtio2/block/vda/vda1
tuning /sys/devices/pci0000:00/0000:00:07.0/virtio2/block/vda
already tuned: /sys/devices/pci0000:00/0000:00:07.0/virtio2/block/vda/queue/scheduler
already tuned: /sys/devices/pci0000:00/0000:00:07.0/virtio2/block/vda/queue/nomerges
tuning /sys/devices/pci0000:00/0000:00:07.0/virtio2/block/vda/vda1
Scylla version 1.7.rc0-0.20170219.2cd019e starting ...
hugeadm:WARNING: Directory /var/lib/hugetlbfs/pagesize-2MB is already mounted.
tuning /sys/devices/pci0000:00/0000:00:07.0/virtio2/block/vda/vda1
tuning /sys/devices/pci0000:00/0000:00:07.0/virtio2/block/vda
already tuned: /sys/devices/pci0000:00/0000:00:07.0/virtio2/block/vda/queue/scheduler
already tuned: /sys/devices/pci0000:00/0000:00:07.0/virtio2/block/vda/queue/nomerges
tuning /sys/devices/pci0000:00/0000:00:07.0/virtio2/block/vda/vda1
Scylla version 1.7.rc0-0.20170219.2cd019e starting ...
tuning /sys/devices/pci0000:00/0000:00:07.0/virtio2/block/vda/vda1
tuning /sys/devices/pci0000:00/0000:00:07.0/virtio2/block/vda
already tuned: /sys/devices/pci0000:00/0000:00:07.0/virtio2/block/vda/queue/scheduler
tuning: /sys/devices/pci0000:00/0000:00:07.0/virtio2/block/vda/queue/nomerges 2
tuning /sys/devices/pci0000:00/0000:00:07.0/virtio2/block/vda/vda1
Scylla version 1.7.rc0-0.20170219.2cd019e starting ...
sudo: no tty present and no askpass program specified
sudo: no tty present and no askpass program specified
sudo: no tty present and no askpass program specified
tuning /sys/devices/virtual/block/md0
already tuned: /sys/devices/virtual/block/md0/queue/scheduler
tuning: /sys/devices/virtual/block/md0/queue/nomerges 2
tuning /sys/devices/pci0000:00/0000:00:09.0/virtio4/block/vdb
already tuned: /sys/devices/pci0000:00/0000:00:09.0/virtio4/block/vdb/queue/scheduler
tuning: /sys/devices/pci0000:00/0000:00:09.0/virtio4/block/vdb/queue/nomerges 2
tuning /sys/devices/virtual/block/md0
Scylla version 1.7.rc2-0.20170328.9b26a57 starting ...
hugeadm:WARNING: Directory /var/lib/hugetlbfs/pagesize-2MB is already mounted.
tuning /sys/devices/virtual/block/md0
already tuned: /sys/devices/virtual/block/md0/queue/scheduler
already tuned: /sys/devices/virtual/block/md0/queue/nomerges
tuning /sys/devices/pci0000:00/0000:00:09.0/virtio4/block/vdb
already tuned: /sys/devices/pci0000:00/0000:00:09.0/virtio4/block/vdb/queue/scheduler
already tuned: /sys/devices/pci0000:00/0000:00:09.0/virtio4/block/vdb/queue/nomerges
tuning /sys/devices/virtual/block/md0
Scylla version 1.7.rc2-0.20170328.9b26a57 starting ...
hugeadm:WARNING: Directory /var/lib/hugetlbfs/pagesize-2MB is already mounted.
tuning /sys/devices/virtual/block/md0
already tuned: /sys/devices/virtual/block/md0/queue/scheduler
already tuned: /sys/devices/virtual/block/md0/queue/nomerges
tuning /sys/devices/pci0000:00/0000:00:09.0/virtio4/block/vdb
already tuned: /sys/devices/pci0000:00/0000:00:09.0/virtio4/block/vdb/queue/scheduler
already tuned: /sys/devices/pci0000:00/0000:00:09.0/virtio4/block/vdb/queue/nomerges
tuning /sys/devices/virtual/block/md0
Scylla version 1.7.rc2-0.20170328.9b26a57 starting ...
scylla: core/reactor.cc:479: void reactor_backend_epoll::abort_fd(pollable_fd_state&, std::__exception_ptr::exception_ptr, promise<> pollable_fd_state::*, int): Assertion `r == 0' failed.
Aborting on shard 0.
Backtrace:
  0x00000000004cbfba
  0x00000000004cc0d3
  0x00007f9ab252932f
  0x00007f9ab218ac36
  0x00007f9ab218e027
  0x00007f9ab2183bf5
  0x00007f9ab2183ca1
  0x00000000004e1c51
  0x00000000004e1cc4
  0x00000000005c2c5e
  0x00000000005c2e04
  0x00007f9ab2190825
  0x00007f9ab21900e6
  0x00007f9ab21901f4
  0x00007f9ab2175f4b
  0x00000000004c99c1
```

**Comment by amoskong** [comment] 2017-04-25 11:00
```
root@ubuntu14:~# df
Filesystem     1K-blocks    Used Available Use% Mounted on
udev             2012196       8   2012188   1% /dev
tmpfs             404732     456    404276   1% /run
/dev/vda1       18864128 3241416  15622712  18% /
none                   4       0         4   0% /sys/fs/cgroup
none                5120       0      5120   0% /run/lock
none             2023656       0   2023656   0% /run/shm
none              102400       0    102400   0% /run/user
/dev/md0        15702016 2026944  13675072  13% /var/lib/scylla
```
Setup Log:
```
root@ubuntu14:~# sudo /usr/lib/scylla/scylla_setup --nic eth0 --disks /dev/vdb --no-cpuscaling-setup
Skip any of the following steps by answering 'no'
This is a supported kernel version.
Generating grub configuration file ...
Found linux image: /boot/vmlinuz-4.2.0-36-generic
Found initrd image: /boot/initrd.img-4.2.0-36-generic
Found linux image: /boot/vmlinuz-4.2.0-27-generic
Found initrd image: /boot/initrd.img-4.2.0-27-generic
Found memtest86+ image: /boot/memtest86+.elf
Found memtest86+ image: /boot/memtest86+.bin
done
Reading package lists... Done
Building dependency tree       
Reading state information... Done
ntp is already the newest version.
ntp set to manually installed.
ntpdate is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 41 not upgraded.
 * Stopping NTP server ntpd                                                               [ OK ] 
25 Apr 13:29:21 ntpdate[2357]: adjust time server 109.226.40.40 offset 0.010390 sec
 * Starting NTP server ntpd                                                               [ OK ] 
Creating RAID0 for scylla using 1 disk(s): /dev/vdb
Reading package lists... Done
Building dependency tree       
Reading state information... Done
xfsprogs is already the newest version.
The following extra packages will be installed:
  postfix ssl-cert
Suggested packages:
  procmail postfix-mysql postfix-pgsql postfix-ldap postfix-pcre sasl2-bin
  dovecot-common postfix-cdb mail-reader postfix-doc openssl-blacklist
Recommended packages:
  default-mta mail-transport-agent
The following NEW packages will be installed:
  mdadm postfix ssl-cert
0 upgraded, 3 newly installed, 0 to remove and 41 not upgraded.
Need to get 1,463 kB of archives.
After this operation, 4,904 kB of additional disk space will be used.
Get:1 http://us.archive.ubuntu.com/ubuntu/ trusty-updates/main mdadm amd64 3.2.5-5ubuntu4.3 [362 kB]
Get:2 http://us.archive.ubuntu.com/ubuntu/ trusty/main ssl-cert all 1.0.33 [16.6 kB]
Get:3 http://us.archive.ubuntu.com/ubuntu/ trusty-updates/main postfix amd64 2.11.0-1ubuntu1 [1,084 kB]
Fetched 1,463 kB in 1s (865 kB/s)  
Preconfiguring packages ...
Selecting previously unselected package mdadm.
(Reading database ... 99960 files and directories currently installed.)
Preparing to unpack .../mdadm_3.2.5-5ubuntu4.3_amd64.deb ...
Unpacking mdadm (3.2.5-5ubuntu4.3) ...
Selecting previously unselected package ssl-cert.
Preparing to unpack .../ssl-cert_1.0.33_all.deb ...
Unpacking ssl-cert (1.0.33) ...
Selecting previously unselected package postfix.
Preparing to unpack .../postfix_2.11.0-1ubuntu1_amd64.deb ...
Unpacking postfix (2.11.0-1ubuntu1) ...
Processing triggers for ureadahead (0.100.0-16) ...
Processing triggers for man-db (2.6.7.1-1ubuntu1) ...
Processing triggers for ufw (0.34~rc-0ubuntu2) ...
Setting up mdadm (3.2.5-5ubuntu4.3) ...
Generating mdadm.conf... done.
 Removing any system startup links for /etc/init.d/mdadm-raid ...
update-initramfs: deferring update (trigger activated)
Generating grub configuration file ...
Found linux image: /boot/vmlinuz-4.2.0-36-generic
Found initrd image: /boot/initrd.img-4.2.0-36-generic
Found linux image: /boot/vmlinuz-4.2.0-27-generic
Found initrd image: /boot/initrd.img-4.2.0-27-generic
Found memtest86+ image: /boot/memtest86+.elf
Found memtest86+ image: /boot/memtest86+.bin
done
 * Starting MD monitoring service mdadm --monitor                                         [ OK ] 
Setting up ssl-cert (1.0.33) ...
Setting up postfix (2.11.0-1ubuntu1) ...
Adding group `postfix' (GID 117) ...
Done.
Adding system user `postfix' (UID 108) ...
Adding new user `postfix' (UID 108) with group `postfix' ...
Not creating home directory `/var/spool/postfix'.
Creating /etc/postfix/dynamicmaps.cf
Adding tcp map entry to /etc/postfix/dynamicmaps.cf
Adding sqlite map entry to /etc/postfix/dynamicmaps.cf
Adding group `postdrop' (GID 118) ...
Done.
setting myhostname: ubuntu14
setting alias maps
setting alias database
mailname is not a fully qualified domain name.  Not changing /etc/mailname.
setting destinations: ubuntu14, localhost.localdomain, , localhost
setting relayhost: 
setting mynetworks: 127.0.0.0/8 [::ffff:127.0.0.0]/104 [::1]/128
setting mailbox_size_limit: 0
setting recipient_delimiter: +
setting inet_interfaces: all
setting inet_protocols: all
/etc/aliases does not exist, creating it.
WARNING: /etc/aliases exists, but does not have a root alias.

Postfix is now set up with a default configuration.  If you need to make 
changes, edit
/etc/postfix/main.cf (and others) as needed.  To view Postfix configuration
values, see postconf(1).

After modifying main.cf, be sure to run '/etc/init.d/postfix reload'.

Running newaliases
 * Stopping Postfix Mail Transport Agent postfix                                          [ OK ] 
 * Starting Postfix Mail Transport Agent postfix                                          [ OK ] 
Processing triggers for ureadahead (0.100.0-16) ...
Processing triggers for initramfs-tools (0.103ubuntu4.6) ...
update-initramfs: Generating /boot/initrd.img-4.2.0-36-generic
W: mdadm: /etc/mdadm/mdadm.conf defines no arrays.
Processing triggers for ufw (0.34~rc-0ubuntu2) ...
Processing triggers for libc-bin (2.19-0ubuntu6.9) ...
mdadm: Defaulting to version 1.2 metadata
mdadm: array /dev/md0 started.
log stripe unit (1048576 bytes) is too large (maximum is 256KiB)
log stripe unit adjusted to 32KiB
meta-data=/dev/md0               isize=256    agcount=16, agsize=245504 blks
         =                       sectsz=512   attr=2, projid32bit=0
data     =                       bsize=4096   blocks=3928064, imaxpct=25
         =                       sunit=256    swidth=256 blks
naming   =version 2              bsize=4096   ascii-ci=0
log      =internal log           bsize=4096   blocks=2560, version=2
         =                       sectsz=512   sunit=8 blks, lazy-count=1
realtime =none                   extsz=4096   blocks=0, rtextents=0
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package 'apport-noui' is not installed, so not removed
0 upgraded, 0 newly installed, 0 to remove and 41 not upgraded.
kernel.core_pattern = |/usr/lib/scylla/scylla_save_coredump %e %t %p
Setting parameters on /etc/default/scylla-server
Generating evaluation file sized 10GB...

10GB written in 89 seconds
Refining search for maximum. So far, 82012 IOPS
Maximum throughput: 82568 IOPS
Recommended --max-io-requests: 18
Written the above values to /etc/scylla.d/io.conf
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   614    0   614    0     0    761      0 --:--:-- --:--:-- --:--:--   760
100 3927k  100 3927k    0     0   638k      0  0:00:06  0:00:06 --:--:--  859k
node_exporter-0.12.0.linux-amd64/
node_exporter-0.12.0.linux-amd64/LICENSE
node_exporter-0.12.0.linux-amd64/NOTICE
node_exporter-0.12.0.linux-amd64/node_exporter
node_exporter start/running, process 10728
node_exporter successfully installed
ScyllaDB setup finished.
Please restart machine before using ScyllaDB, since you have changed 
boot parameters.
```

**Comment by amoskong** [comment] 2017-04-25 11:15
There is a coredump file, but I failed to get the backtrace from gdb:

```
root@ubuntu14:~# gdb /usr/bin/scylla gdb  /var/lib/scylla/coredump/core.scylla-2017-04-25-13:37:05-10829
Excess command line arguments ignored. (/var/lib/scylla/coredump/core.scylla-2017-04-25-13:37:05-10829)
GNU gdb (Ubuntu 7.7.1-0ubuntu5~14.04.2) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/bin/scylla...Reading symbols from /usr/lib/debug/.build-id/38/de525722e7d11c98ecf28295ad2145594ce312.debug...Segmentation fault (core dumped)
```

**Comment by amoskong** [comment] 2017-04-25 12:17
```
root@ubuntu14:~# addr2line -Cfpi -e /usr/lib/debug/.build-id/38/de525722e7d11c98ecf28295ad2145594ce312.debug  0x00000000004cbfba  0x00000000004cc0d3  0x00007f9ab252932f  0x00007f9ab218ac36  0x00007f9ab218e027  0x00007f9ab2183bf5  0x00007f9ab2183ca1  0x00000000004e1c51  0x00000000004e1cc4  0x00000000005c2c5e  0x00000000005c2e04  0x00007f9ab2190825  0x00007f9ab21900e6  0x00007f9ab21901f4  0x00007f9ab2175f4b  0x00000000004c99c1
print_backtrace_safe at /home/ubuntu/workspace/scylla-1.7-ubuntu-deb/scylla/seastar/core/reactor.cc:2374
 (inlined by) print_with_backtrace at /home/ubuntu/workspace/scylla-1.7-ubuntu-deb/scylla/seastar/core/reactor.cc:3198
sigabrt_action at /home/ubuntu/workspace/scylla-1.7-ubuntu-deb/scylla/seastar/core/reactor.cc:3206
 (inlined by) operator() at /home/ubuntu/workspace/scylla-1.7-ubuntu-deb/scylla/seastar/core/reactor.cc:3178
 (inlined by) _FUN at /home/ubuntu/workspace/scylla-1.7-ubuntu-deb/scylla/seastar/core/reactor.cc:3174
?? ??:0
?? ??:0
?? ??:0
?? ??:0
?? ??:0
reactor_backend_epoll::abort_fd(pollable_fd_state&, std::__exception_ptr::exception_ptr, promise<> pollable_fd_state::*, int) at /home/ubuntu/workspace/scylla-1.7-ubuntu-deb/scylla/seastar/core/reactor.cc:479 (discriminator 1)
reactor_backend_epoll::abort_writer(pollable_fd_state&, std::__exception_ptr::exception_ptr) at /home/ubuntu/workspace/scylla-1.7-ubuntu-deb/scylla/seastar/core/reactor.cc:501
reactor::abort_writer(pollable_fd_state&, std::__exception_ptr::exception_ptr) at /home/ubuntu/workspace/scylla-1.7-ubuntu-deb/scylla/seastar/./core/reactor.hh:963
 (inlined by) pollable_fd::abort_writer(std::__exception_ptr::exception_ptr) at /home/ubuntu/workspace/scylla-1.7-ubuntu-deb/scylla/seastar/./core/reactor.hh:1269
 (inlined by) net::posix_udp_channel::close() at /home/ubuntu/workspace/scylla-1.7-ubuntu-deb/scylla/seastar/net/posix-stack.cc:437
_ZN3net17posix_udp_channelD4Ev at /home/ubuntu/workspace/scylla-1.7-ubuntu-deb/scylla/seastar/net/posix-stack.cc:430
 (inlined by) net::posix_udp_channel::~posix_udp_channel() at /home/ubuntu/workspace/scylla-1.7-ubuntu-deb/scylla/seastar/net/posix-stack.cc:430
?? ??:0
?? ??:0
?? ??:0
?? ??:0
_start at ??:?
```

**Comment by syuu1228** [comment] 2017-04-25 13:02
@amoskong Have about to try scylla-gdb instead of distribution version of gdb?

**Comment by amoskong** [comment] 2017-04-25 13:21
@syuu1228 do we have scylla-gdb for ubuntu OS? I didn't find it.

**Comment by syuu1228** [comment] 2017-04-25 13:52
@amoskong It should available in 3rdparty https://s3.amazonaws.com/downloads.scylladb.com/deb/3rdparty/trusty/pool/scylladb/multiverse/s/scylla-gdb/scylla-gdb_7.11-0ubuntu1_amd64.deb
Is that inaccessible from apt?

**Comment by amoskong** [comment] 2017-04-25 15:19
```
root@ubuntu14:~# cat /etc/apt/sources.list.d/scylla.list
deb [arch=amd64] http://downloads.scylladb.com/deb/unstable/ubuntu/branch-1.7/17 trusty scylladb-1.7/multiverse
root@ubuntu14:~# apt-get install scylla-gdb
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package scylla-gdb
root@ubuntu14:~# apt-cache search scylla
scylla - Scylla database metapackage
scylla-conf - Scylla database main configuration file
scylla-jmx - Scylla JMX server binaries
scylla-kernel-conf - Scylla kernel tuning configuration
scylla-server - Scylla database server binaries
scylla-server-dbg - debugging symbols for scylla-server
scylla-tools - Scylla database tools
```
```
root@ubuntu14:~# dpkg -i scylla-gdb_7.11-0ubuntu1_amd64.deb 
(Reading database ... 102618 files and directories currently installed.)
Preparing to unpack scylla-gdb_7.11-0ubuntu1_amd64.deb ...
Unpacking scylla-gdb (7.11-0ubuntu1) over (7.11-0ubuntu1) ...
dpkg: dependency problems prevent configuration of scylla-gdb:
 scylla-gdb depends on libbabeltrace-ctf1 (>= 1.2.1); however:
  Package libbabeltrace-ctf1 is not installed.
 scylla-gdb depends on libbabeltrace1 (>= 1.2.1); however:
  Package libbabeltrace1 is not installed.
 scylla-gdb depends on scylla-env; however:
  Package scylla-env is not installed.

dpkg: error processing package scylla-gdb (--install):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 scylla-gdb

root@ubuntu14:~# sudo apt-get install
Reading package lists... Done
Building dependency tree       
Reading state information... Done
You might want to run 'apt-get -f install' to correct these.
The following packages have unmet dependencies:
 scylla-gdb : Depends: libbabeltrace-ctf1 (>= 1.2.1) but it is not installed
              Depends: libbabeltrace1 (>= 1.2.1) but it is not installed
              Depends: scylla-env but it is not installable
              Recommends: libcc1-0 but it is not installable
              Recommends: scylla-gdbserver but it is not installable
E: Unmet dependencies. Try using -f.
```

**Comment by syuu1228** [comment] 2017-04-25 15:36
@amoskong did you installed 3rdparty list?
https://s3.amazonaws.com/downloads.scylladb.com/deb/3rdparty/trusty/scylla-3rdparty.list

**Comment by slivne** [comment] 2017-04-30 10:06
@amoskong - this may block 1.7 - can you please provide the additional info

**Comment by amoskong** [comment] 2017-05-02 11:56
The scylla-server failed to start for issue #2236, it's already fixed in branch-1.7.

The coredump occurred when I try to directly start scylla from cmdline.
I had used a cmdline from another machine, then coredump occurred. I just changed the collectd port to a unexist port '25824', the coredump is reproduced.

`It seems the coredump is caused by collectd udb/net prepare setup.`

```
root@ubuntu14:/etc/apt/sources.list.d# /usr/bin/scylla --log-to-syslog 1 --log-to-stdout 0 --default-log-level info --collectd-address=127.0.0.1:25824 --collectd=1 --collectd-poll-period 3000 --network-stack posix --max-io-requests=21
Scylla version 1.7.rc2-0.20170328.9b26a57 starting ...
scylla: core/reactor.cc:479: void reactor_backend_epoll::abort_fd(pollable_fd_state&, std::__exception_ptr::exception_ptr, promise<> pollable_fd_state::*, int): Assertion `r == 0' failed.
Aborting on shard 0.
Backtrace:
  0x00000000004cbfba
...
  0x00000000004c99c1
Aborted (core dumped)
```

Failed to debug with gdb/scylla-gdb, another CoreDump occurred.
```
(gdb) add-auto-load-safe-path /usr/lib/scylla/scylla-gdb.py
(gdb) help scylla
Undefined command: "scylla".  Try "help".
(gdb) file /usr/bin/scylla
Reading symbols from /usr/bin/scylla...Reading symbols from /usr/lib/debug/.build-id/38/de525722e7d11c98ecf28295ad2145594ce312.debug...Segmentation fault (core dumped)
```

Fail to debug scylla process, another CoreDump occurred.
```
root@ubuntu14:/etc/apt/sources.list.d# ps aux|grep scylla
scylla   13943 13.1 27.2 17180008572 1102828 ? Ssl  14:26   0:00 /usr/bin/scylla --log-to-syslog 1 --log-to-stdout 0 --default-log-level info --collectd-address=127.0.0.1:25826 --collectd=1 --collectd-poll-period 3000 --network-stack posix --max-io-requests=21
root     13960  0.0  0.0  11760  2208 pts/0    S+   14:26   0:00 grep --color=auto scylla
root@ubuntu14:/etc/apt/sources.list.d# gdb 
(gdb) add-auto-load-safe-path /usr/lib/scylla/scylla-gdb.py
(gdb) attach 13943
Attaching to process 13943
Reading symbols from /usr/bin/scylla...Reading symbols from /usr/lib/debug/.build-id/38/de525722e7d11c98ecf28295ad2145594ce312.debug...Segmentation fault (core dumped)
```

**Comment by amoskong** [comment] 2017-05-02 13:05
I didn't reproduce the coredump (abort_fd/close/udp) with 1.7.rc3-0.20170501.e836964

Scylla Server can be started successfully.
```
#  ulimit -n 10000
#  /usr/bin/scylla --log-to-syslog 1 --log-to-stdout 1 --default-log-level info --collectd-address=127.0.0.1:25824 --collectd=1 --collectd-poll-period 3000 --network-stack posix --max-io-requests=21
```

**Comment by amoskong** [comment] 2017-05-03 16:35
I just reproduced this coredump (abort_fd/close/udp)  on latest 1.7.rc3-0.20170501.e836964 with a special method. `It should not occur in common usage, so not hight priority`

1. Start scylla cmdline from `/root`, it will touch an error:
/usr/bin/scylla --log-to-syslog 1 --log-to-stdout 1 --default-log-level info --collectd-address=127.0.0.1:25824 --collectd=1 --collectd-poll-period 3000 --network-stack posix --max-io-requests=21
seastar - Exiting on unhandled exception: std::invalid_argument (Could not open file at conf/scylla.yaml. Make sure it exists)

2. try to terminate scylla by `Ctrl-c` before invalid _argument error raises.  Can't reproduce the coredump (abort_fd/close/udp) all the time.

```
# /opt/scylladb/bin/gdb /usr/bin/scylla core.scylla-2017-05-03-19:28:20-13944
...
(gdb) info thread
  Id   Target Id         Frame 
* 1    Thread 0x7fda493ae440 (LWP 13944) 0x00007fda44e5dc37 in raise () from /lib/x86_64-linux-gnu/libc.so.6
(gdb) bt
#0  0x00007fda44e5dc37 in raise () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007fda44e61168 in abort () from /lib/x86_64-linux-gnu/libc.so.6
#2  0x00007fda44e56bf6 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#3  0x00007fda44e56ca2 in __assert_fail () from /lib/x86_64-linux-gnu/libc.so.6
#4  0x00000000004e2462 in ?? ()
#5  0x00000000004e24d5 in ?? ()
#6  0x00000000005c346f in ?? ()
#7  0x00000000005c3615 in ?? ()
#8  0x00007fda44e63826 in __call_tls_dtors () from /lib/x86_64-linux-gnu/libc.so.6
#9  0x00007fda44e630e7 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#10 0x00007fda44e631f5 in exit () from /lib/x86_64-linux-gnu/libc.so.6
#11 0x00007fda44e48f4c in __libc_start_main () from /lib/x86_64-linux-gnu/libc.so.6
#12 0x00000000004ca1d2 in ?? ()

root@ubuntu14:/var/lib/scylla/coredump# addr2line -Cfpi -e /usr/lib/debug/.build-id/7d/720cc6b1e5235a2be3d86c4c7c0544be29a88b.debug 0x00000000004cc7ca  0x00000000004cc8e3  0x00007f3c97d2d32f  0x00007f3c9798bc36  0x00007f3c9798f027  0x00007f3c97984bf5  0x00007f3c97984ca1  0x00000000004e2461  0x00000000004e24d4  0x00000000005c346e  0x00000000005c3614  0x00007f3c97991825  0x00007f3c979910e6  0x00007f3c979911f4  0x00007f3c97976f4b  0x00000000004ca1d1 
print_backtrace_safe at /home/ubuntu/workspace/scylla-1.7-ubuntu-deb/scylla/seastar/core/reactor.cc:2374
 (inlined by) print_with_backtrace at /home/ubuntu/workspace/scylla-1.7-ubuntu-deb/scylla/seastar/core/reactor.cc:3198
sigabrt_action at /home/ubuntu/workspace/scylla-1.7-ubuntu-deb/scylla/seastar/core/reactor.cc:3206
 (inlined by) operator() at /home/ubuntu/workspace/scylla-1.7-ubuntu-deb/scylla/seastar/core/reactor.cc:3178
 (inlined by) _FUN at /home/ubuntu/workspace/scylla-1.7-ubuntu-deb/scylla/seastar/core/reactor.cc:3174
?? ??:0
?? ??:0
?? ??:0
?? ??:0
?? ??:0
reactor_backend_epoll::abort_fd(pollable_fd_state&, std::__exception_ptr::exception_ptr, promise<> pollable_fd_state::*, int) at /home/ubuntu/workspace/scylla-1.7-ubuntu-deb/scylla/seastar/core/reactor.cc:479 (discriminator 1)
reactor_backend_epoll::abort_writer(pollable_fd_state&, std::__exception_ptr::exception_ptr) at /home/ubuntu/workspace/scylla-1.7-ubuntu-deb/scylla/seastar/core/reactor.cc:501
reactor::abort_writer(pollable_fd_state&, std::__exception_ptr::exception_ptr) at /home/ubuntu/workspace/scylla-1.7-ubuntu-deb/scylla/seastar/./core/reactor.hh:963
 (inlined by) pollable_fd::abort_writer(std::__exception_ptr::exception_ptr) at /home/ubuntu/workspace/scylla-1.7-ubuntu-deb/scylla/seastar/./core/reactor.hh:1269
 (inlined by) net::posix_udp_channel::close() at /home/ubuntu/workspace/scylla-1.7-ubuntu-deb/scylla/seastar/net/posix-stack.cc:437
_ZN3net17posix_udp_channelD4Ev at /home/ubuntu/workspace/scylla-1.7-ubuntu-deb/scylla/seastar/net/posix-stack.cc:430
 (inlined by) net::posix_udp_channel::~posix_udp_channel() at /home/ubuntu/workspace/scylla-1.7-ubuntu-deb/scylla/seastar/net/posix-stack.cc:430
?? ??:0
?? ??:0
?? ??:0
?? ??:0
_start at ??:?
```

**Comment by syuu1228** [comment] 2017-05-08 09:56
@amoskong did you set SCYLLA_CONF and SCYLLA_HOME environment variables when you run scylla from cmdline? If not, it should causes the error.

**Comment by amoskong** [comment] 2017-05-08 16:57
@syuu1228 I didn't set the env variables.
Coredump isn't acceptable.

**Comment by syuu1228** [comment] 2017-05-10 04:15
@amoskong Ah.. right. It should shows up error but shoudn't produce coredump.

**Comment by slivne** [comment] 2017-07-05 08:27
@amoskong - so the issue is that if you start this manually / scylla does not find the scylla.yaml config it will crash and not spit out an error ?

**Comment by avikivity** [comment] 2020-08-05 15:25
Ubuntu 14 is EOL, closing.

**Closed by avikivity** 2020-08-05 15:25 UTC
Labels: UX, bug
