### ISSUE TITLE
Network scheduler support

### ISSUE THREAD

**Issue by asias** [scylladb/scylla#6262] opened 2020-04-22 06:25 UTC
Scylla uses both cpu and disk io scheduler to allocate cpu and disk resources to different components in the system. A network scheduler is needed to allocate network bandwidth to different components  too. For example, it is desirable to allocate say 10% of the network bandwidth to maintenance work like repair or bootstrap operations, so that the cql traffic is not affected.

**Comment by gleb-cloudius** [comment] 2020-04-22 06:29
This suppose to be open against seastar. All the schedulers are there.

--
			Gleb.

**Comment by asias** [comment] 2020-04-22 06:33
Yes, the hard work should be done in seastar. This issue is used to track the scylla part.

**Comment by slivne** [comment] 2020-05-11 15:56
@asias did we hit this issue in testing / customer issue - if so can you share more info on how

**Comment by slivne** [comment] 2020-05-17 19:53
@asias ^^

**Comment by asias** [comment] 2020-05-18 01:14
> @asias did we hit this issue in testing / customer issue - if so can you share more info on how

As far as I know, we do not hear direct complaint that cql and streaming/repair network competing has caused the cql latency spike. It is a possible cause of maintenance work having impact cql. 
I created the issue so we do not forget it.

**Comment by avikivity** [comment] 2020-05-27 05:06
Duplicate of #1454

**Closed by avikivity** 2020-05-27 05:06 UTC
