### ISSUE TITLE
seastar - Exiting on unhandled exception: std::out_of_range (_Map_base::at))

### ISSUE THREAD

**Issue by kongove** [scylladb/scylla#2195] opened 2017-03-22 10:30 UTC
Moving from https://github.com/scylladb/seastar/issues/265

*Installation details*
Scylla version (or git commit hash): 1.7.rc1-0.20170320.87de77a
Cluster size: 6
OS (RHEL/CentOS/Ubuntu/AWS AMI): CentOS

Setup:
> version: 1.7.rc1-0.20170320.87de77a
> total test duration: 7 days
> 6 db nodes (n1-highmem-16 (16 cpu, 104G mem))
> 1 loader (n1-standard-2 (2 cpu, 7.5G mem))
> 1 monitor (n1-standard-2 (2 cpu, 7.5G mem))

* Job:
http://jenkins.cloudius-systems.com/job/scylla-1.7-longevity-gce/label=gce/36

* Monitor:
http://104.196.153.176:3000/dashboard/db/scylla-per-server-metrics-master?from=1490086200000&to=now

* Job Status:

    - Job run 3 hours, then one db node failed to start after been killed.

2017-03-21 11:55:05,671 remote           L0197 DEBUG| [104.196.192.141] [stdout] Mar 21 11:55:05 err    |  [shard 0] seastar - Exiting on unhandled exception: std::out_of_range (_Map_base::at)

    - I tried to restart the scylla-server just now, but it still failed for same reason.
Mar 21 20:44:07 longevity-1-7-gce-amosbranch-scylla-db-node-30ee1450-001 scylla[23239]:  [shard 0] seastar - Exiting on unhandled exception: std::out_of_range (_Map_base::at)

* Db node info
ip: 104.196.192.141
[gce page](https://console.cloud.google.com/compute/instancesDetail/zones/us-east1-b/instances/longevity-1-7-gce-amosbranch-scylla-db-node-30ee1450-001?project=skilled-adapter-452&graph=GCE_CPU&duration=P2D)
You can login it with your own ssh key (The whole cluster + loader + monitor are living)

The seastar out_of_range error also occurred on another db node in second [longevity test 37](http://jenkins.cloudius-systems.com/job/scylla-1.7-longevity-gce/label=gce/37/console).
IP: 35.185.49.204
[GCE page](https://console.cloud.google.com/compute/instancesDetail/zones/us-east1-b/instances/longevity-1-7-gce-amosbranch-scylla-db-node-dcd3bf34-002?project=skilled-adapter-452)

More details: 
=============

[failed_to_restart_seastar_OutOfRange.txt](https://github.com/scylladb/seastar/files/859672/failed_to_restart_seastar_OutOfRange.txt)

```
Mar 21 20:42:46 longevity-1-7-gce-amosbranch-scylla-db-node-30ee1450-001 sudo[23216]: scylla-test : TTY=pts/2 ; PWD=/home/scylla-test ; USER=root ; COMMAND=/sbin/service scylla-server restart
Mar 21 20:42:46 longevity-1-7-gce-amosbranch-scylla-db-node-30ee1450-001 systemd[1]: Starting Scylla Server...
....
....
Mar 21 20:44:07 longevity-1-7-gce-amosbranch-scylla-db-node-30ee1450-001 scylla[23239]:  [shard 7] compaction - Compacting [/var/lib/scylla/data/keyspace1/standard1-503a43e00e1411e78576000000000005/keyspace1-standard1-ka-231-Data.db:level=0, /var/lib/scylla/data/keyspace1/standard1-503a43e00e1411e78576000000000005/keyspace1-standard1-ka-215-Data.db:level=0, /var/lib/scylla/data/keyspace1/standard1-503a43e00e1411e78576000000000005/keyspace1-standard1-ka-183-Data.db:level=0, /var/lib/scylla/data/keyspace1/standard1-503a43e00e1411e78576000000000005/keyspace1-standard1-ka-199-Data.db:level=0, ]
Mar 21 20:44:07 longevity-1-7-gce-amosbranch-scylla-db-node-30ee1450-001 scylla[23239]:  [shard 0] seastar - Exiting on unhandled exception: std::out_of_range (_Map_base::at)
Mar 21 20:44:07 longevity-1-7-gce-amosbranch-scylla-db-node-30ee1450-001 scylla[23239]:  [shard 0] compaction_manager - Asked to stop
Mar 21 20:44:07 longevity-1-7-gce-amosbranch-scylla-db-node-30ee1450-001 scylla[23239]:  [shard 2] compaction_manager - Asked to stop
Mar 21 20:44:07 longevity-1-7-gce-amosbranch-scylla-db-node-30ee1450-001 scylla[23239]:  [shard 8] compaction_manager - Asked to stop
Mar 21 20:44:07 longevity-1-7-gce-amosbranch-scylla-db-node-30ee1450-001 scylla[23239]:  [shard 1] compaction_manager - Asked to stop
Mar 21 20:44:07 longevity-1-7-gce-amosbranch-scylla-db-node-30ee1450-001 scylla[23239]:  [shard 6] compaction_manager - Asked to stop
Mar 21 20:44:07 longevity-1-7-gce-amosbranch-scylla-db-node-30ee1450-001 scylla[23239]:  [shard 2] compaction_manager - Stopped
Mar 21 20:44:07 longevity-1-7-gce-amosbranch-scylla-db-node-30ee1450-001 scylla[23239]:  [shard 8] compaction_manager - Stopped
Mar 21 20:44:07 longevity-1-7-gce-amosbranch-scylla-db-node-30ee1450-001 scylla[23239]:  [shard 1] compaction_manager - Stopped
Mar 21 20:44:07 longevity-1-7-gce-amosbranch-scylla-db-node-30ee1450-001 scylla[23239]:  [shard 14] compaction_manager - Asked to stop
Mar 21 20:44:07 longevity-1-7-gce-amosbranch-scylla-db-node-30ee1450-001 scylla[23239]:  [shard 9] compaction_manager - Asked to stop
Mar 21 20:44:07 longevity-1-7-gce-amosbranch-scylla-db-node-30ee1450-001 scylla[23239]:  [shard 6] compaction_manager - Stopped
Mar 21 20:44:07 longevity-1-7-gce-amosbranch-scylla-db-node-30ee1450-001 scylla[23239]:  [shard 15] compaction_manager - Asked to stop
Mar 21 20:44:07 longevity-1-7-gce-amosbranch-scylla-db-node-30ee1450-001 scylla[23239]:  [shard 14] compaction_manager - Stopped
Mar 21 20:44:07 longevity-1-7-gce-amosbranch-scylla-db-node-30ee1450-001 scylla[23239]:  [shard 9] compaction_manager - Stopped
Mar 21 20:44:07 longevity-1-7-gce-amosbranch-scylla-db-node-30ee1450-001 scylla[23239]:  [shard 5] compaction_manager - Asked to stop
Mar 21 20:44:07 longevity-1-7-gce-amosbranch-scylla-db-node-30ee1450-001 scylla[23239]:  [shard 13] compaction_manager - Asked to stop
Mar 21 20:44:07 longevity-1-7-gce-amosbranch-scylla-db-node-30ee1450-001 scylla[23239]:  [shard 4] compaction_manager - Asked to stop
Mar 21 20:44:07 longevity-1-7-gce-amosbranch-scylla-db-node-30ee1450-001 scylla[23239]:  [shard 13] compaction_manager - Stopped
Mar 21 20:44:07 longevity-1-7-gce-amosbranch-scylla-db-node-30ee1450-001 scylla[23239]:  [shard 15] compaction_manager - Stopped
Mar 21 20:44:07 longevity-1-7-gce-amosbranch-scylla-db-node-30ee1450-001 scylla[23239]:  [shard 4] compaction_manager - Stopped
Mar 21 20:44:07 longevity-1-7-gce-amosbranch-scylla-db-node-30ee1450-001 scylla[23239]:  [shard 5] compaction_manager - Stopped
Mar 21 20:44:07 longevity-1-7-gce-amosbranch-scylla-db-node-30ee1450-001 scylla[23239]:  [shard 12] compaction_manager - Asked to stop
Mar 21 20:44:07 longevity-1-7-gce-amosbranch-scylla-db-node-30ee1450-001 scylla[23239]:  [shard 10] compaction_manager - Asked to stop
Mar 21 20:44:07 longevity-1-7-gce-amosbranch-scylla-db-node-30ee1450-001 scylla[23239]:  [shard 12] compaction_manager - Stopped
Mar 21 20:44:07 longevity-1-7-gce-amosbranch-scylla-db-node-30ee1450-001 scylla[23239]:  [shard 10] compaction_manager - Stopped
Mar 21 20:44:07 longevity-1-7-gce-amosbranch-scylla-db-node-30ee1450-001 scylla[23239]:  [shard 11] compaction_manager - Asked to stop
Mar 21 20:44:07 longevity-1-7-gce-amosbranch-scylla-db-node-30ee1450-001 scylla[23239]:  [shard 11] compaction_manager - Stopped
Mar 21 20:44:07 longevity-1-7-gce-amosbranch-scylla-db-node-30ee1450-001 scylla[23239]:  [shard 3] compaction_manager - Asked to stop
Mar 21 20:44:07 longevity-1-7-gce-amosbranch-scylla-db-node-30ee1450-001 scylla[23239]:  [shard 3] compaction_manager - Stopped
Mar 21 20:44:07 longevity-1-7-gce-amosbranch-scylla-db-node-30ee1450-001 scylla[23239]:  [shard 7] compaction_manager - Asked to stop
Mar 21 20:44:07 longevity-1-7-gce-amosbranch-scylla-db-node-30ee1450-001 scylla[23239]:  [shard 0] compaction_manager - Stopped
Mar 21 20:44:07 longevity-1-7-gce-amosbranch-scylla-db-node-30ee1450-001 scylla[23239]:  [shard 7] compaction_manager - compaction info: Compaction for keyspace1/standard1 was stopped due to shutdown.
Mar 21 20:44:07 longevity-1-7-gce-amosbranch-scylla-db-node-30ee1450-001 scylla[23239]:  [shard 7] compaction_manager - Stopped
Mar 21 20:44:12 longevity-1-7-gce-amosbranch-scylla-db-node-30ee1450-001 systemd[1]: scylla-server.service: main process exited, code=exited, status=1/FAILURE
Mar 21 20:44:12 longevity-1-7-gce-amosbranch-scylla-db-node-30ee1450-001 systemd[1]: Failed to start Scylla Server.
Mar 21 20:44:12 longevity-1-7-gce-amosbranch-scylla-db-node-30ee1450-001 systemd[1]: Dependency failed for Scylla JMX.
Mar 21 20:44:12 longevity-1-7-gce-amosbranch-scylla-db-node-30ee1450-001 systemd[1]: Job scylla-jmx.service/start failed with result 'dependency'.
Mar 21 20:44:12 longevity-1-7-gce-amosbranch-scylla-db-node-30ee1450-001 systemd[1]: Dependency failed for Run Scylla Housekeeping daily mode.
Mar 21 20:44:12 longevity-1-7-gce-amosbranch-scylla-db-node-30ee1450-001 systemd[1]: Job scylla-housekeeping-daily.timer/start failed with result 'dependency'.
Mar 21 20:44:12 longevity-1-7-gce-amosbranch-scylla-db-node-30ee1450-001 systemd[1]: Dependency failed for Run Scylla Housekeeping restart mode.
Mar 21 20:44:12 longevity-1-7-gce-amosbranch-scylla-db-node-30ee1450-001 systemd[1]: Job scylla-housekeeping-restart.timer/start failed with result 'dependency'.
Mar 21 20:44:12 longevity-1-7-gce-amosbranch-scylla-db-node-30ee1450-001 systemd[1]: Unit scylla-server.service entered failed state.
Mar 21 20:44:12 longevity-1-7-gce-amosbranch-scylla-db-node-30ee1450-001 systemd[1]: scylla-server.service failed.
```

**Comment by kongove** [comment] 2017-03-22 10:34
I try to debug it by scylla-gdb, it seems same issue as #2173 .
@raphaelsc @elcallio can you help to confirm?

```
sudo /opt/scylladb/bin/gdb --args /usr/bin/scylla --log-to-syslog 1 --log-to-stdout 0 --default-log-level info --collectd-address=127.0.0.1:25826 --collectd=1 --collectd-poll-period 3000 --network-stack posix --max-io-requests=123 --options-file /etc/scylla/scylla.yaml --developer-mode=1
(gdb) handle SIG34 SIGUSR1 nostop noprint pass
(gdb) catch throw
(gdb) r
......
(gdb) bt 
#0  db::commitlog_replayer::impl::recover (this=0x6000012be180, file=...)               |
    at db/commitlog/commitlog_replayer.cc:206                                           |
#1  0x0000000001096aeb in db::commitlog_replayer::<lambda()>::<lambda(unsigned int)>::<l|
ambda()>::<lambda(const std::pair<unsigned int, basic_sstring<char, unsigned int, 15u> >|
&)>::operator() (p=..., __closure=0x7fd2eadf6590)                                       |
    at db/commitlog/commitlog_replayer.cc:365                                           |
#2  do_for_each<std::__detail::_Local_iterator<unsigned int, std::pair<unsigned int cons|
t, basic_sstring<char, unsigned int, 15u> >, std::__detail::_Select1st, std::hash<unsign|
ed int>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, false, |
false>, db::commitlog_replayer::recover(std::vector<basic_sstring<char, unsigned int, 15|
u> >)::<lambda()>::<lambda(unsigned int)>::<lambda()>::<lambda(const std::pair<unsigned |
int, basic_sstring<char, unsigned int, 15u> >&)> >(std::__detail::_Local_iterator<unsign|
ed int, std::pair<unsigned int const, basic_sstring<char, unsigned int, 15u> >, std::__d|
etail::_Select1st, std::hash<unsigned int>, std::__detail::_Mod_range_hashing, std::__de|
tail::_Default_ranged_hash, false, false>, std::__detail::_Local_iterator<unsigned int, |
std::pair<unsigned int const, basic_sstring<char, unsigned int, 15u> >, std::__detail::_|
Select1st, std::hash<unsigned int>, std::__detail::_Mod_range_hashing, std::__detail::_D|
efault_ranged_hash, false, false>, <unknown type in /usr/lib/debug/usr/bin/scylla.debug,|
 CU 0x1305413c, DIE 0x1330b41e>) (begin=..., end=...,                                   |
    action=action@entry=<unknown type in /usr/lib/debug/usr/bin/scylla.debug, CU 0x13054|
13c, DIE 0x1330b41e>) at /usr/src/debug/scylla-1.7.rc1/seastar/core/future-util.hh:360  |
#3  0x00000000010982a6 in db::commitlog_replayer::<lambda()>::<lambda(unsigned int)>::<l|
ambda()>::operator() (__closure=0x600000e81688)                                         |
    at db/commitlog/commitlog_replayer.cc:362                                           |
#4  futurize<future<db::commitlog_replayer::impl::stats> >::apply<db::commitlog_replayer|
::recover(std::vector<basic_sstring<char, unsigned int, 15u> >)::<lambda()>::<lambda(uns
igned int)>::<lambda()>&>(db::commitlog_replayer::<lambda()>::<lambda(unsigned int)>::<l
ambda()> &) (func=...) at /usr/src/debug/scylla-1.7.rc1/seastar/core/future.hh:1277     
#5  0x00000000010a1942 in smp_message_queue::async_work_item<db::commitlog_replayer::rec
over(std::vector<basic_sstring<char, unsigned int, 15u> >)::<lambda()>::<lambda(unsigned
 int)>::<lambda()> >::process(void) (this=<optimized out>)                              
    at /usr/src/debug/scylla-1.7.rc1/seastar/core/reactor.hh:334   
#6  0x0000000000506f40 in smp_message_queue::<lambda(smp_message_queue::work_item*)>::op
erator() (wi=0x600000e81680, __closure=<synthetic pointer>) at core/reactor.cc:2851     
#7  smp_message_queue::process_queue<2ul, smp_message_queue::process_incoming()::<lambda
(smp_message_queue::work_item*)> >(smp_message_queue::lf_queue &, smp_message_queue::<la
mbda(smp_message_queue::work_item*)>) (q=..., process=..., process@entry=...,           
    this=0x6000003c4000) at core/reactor.cc:2824                                        
#8  0x0000000000507a68 in smp_message_queue::process_incoming (this=0x6000003c4000)     
    at core/reactor.cc:2854                                                             
#9  smp::poll_queues () at core/reactor.cc:3437                                         
#10 0x00000000004ded15 in reactor::poll_once (this=<optimized out>)                     
    at core/reactor.cc:2562                                                             
#11 reactor::<lambda()>::operator() (__closure=0x7fd2eadf6ea0) at core/reactor.cc:2461  
#12 std::_Function_handler<bool(), reactor::run()::<lambda()> >::_M_invoke(const std::_A
ny_data &) (__functor=...) at /opt/scylladb/include/c++/5.3.1/functional:1857           
#13 0x00000000005318e6 in std::function<bool ()>::operator()() const (
    this=0x7fd2eadf6ea0) at /opt/scylladb/include/c++/5.3.1/functional:2271
#14 reactor::run (this=0x60f0001c1000) at core/reactor.cc:2486
#15 0x00000000005330f1 in smp::<lambda()>::operator()(void) const (
---Type <return> to continue, or q <return> to quit---
    __closure=0x6000000cb500) at core/reactor.cc:3396
#16 0x000000000058e9fe in std::function<void ()>::operator()() const (
    this=<optimized out>) at /opt/scylladb/include/c++/5.3.1/functional:2271
#17 posix_thread::start_routine (arg=<optimized out>) at core/posix.cc:50
#18 0x00007fd2f904bdc5 in start_thread (arg=0x7fd2eadff700) at pthread_create.c:308
#19 0x00007fd2f8d7a73d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:113
```

More details:  https://gist.github.com/kongove/70f1a742cff9decc557f8c35deac1141

**Comment by elcallio** [comment] 2017-03-22 16:04
duplicate of #2173

**Comment by kongove** [comment] 2017-03-22 21:20
Thanks for the confirm. Do you need my environment to trouble shooting? otherwise I will release the gce machines.
@elcallio @raphaelsc

**Closed** 2017-03-29 07:46 UTC
