### ISSUE TITLE
nodetool toppartitions not working if not using nodetool cfstats before

### ISSUE THREAD

**Issue by nirmaayan** [scylladb/scylla#4519] opened 2019-06-03 08:57 UTC
Scylla version: 3.1.0.rc0-0.20190516.d568270d7

``nodetool toppartitions`` command not working if not using ``nodetool cfstats`` before.

The error message is:
```
[centos@ip-10-0-0-215 ~]$ nodetool toppartitions nba team_roster 1000
ColumnFamilyStore for nba/team_roster not found.
```
Steps to reproduce 

1. Create keyspace
```
CREATE KEYSPACE nba WITH replication = {'class': 'SimpleStrategy', 'replication_factor' : '3'};
```
2. Create table
```
CREATE TABLE nba.team_roster (
player_name text,
player_jersy_number int,
player_position text,
team text,
PRIMARY KEY (player_name));
```
3. Write data
```
INSERT INTO nba.team_roster (player_name, player_jersy_number, player_position, team ) VALUES ('Russell Westbrook', 0, 'Guard','Oklahoma City Thunder');
INSERT INTO nba.team_roster (player_name, player_jersy_number, player_position, team ) VALUES ('Andre Roberson', 21, 'Forward','Oklahoma City Thunder');
INSERT INTO nba.team_roster (player_name, player_jersy_number, player_position, team ) VALUES ('Steven Adams', 12, 'Center','Oklahoma City Thunder');
INSERT INTO nba.team_roster (player_name, player_jersy_number, player_position, team ) VALUES ('Victor Oladipo ', 5, 'Forward','Oklahoma City Thunder');
INSERT INTO nba.team_roster (player_name, player_jersy_number, player_position, team ) VALUES ('Jermi Grant ', 9, 'Forward','Oklahoma City Thunder');
```
4. Run ``nodetool toppartitions nba team_roster 10000``
Error message will appear.

Workaround:
1. Run ``nodetool cfstats``
2. Run ``nodetool toppartitions nba team_roster 10000``

**Comment by amnonh** [comment] 2019-06-05 08:39
@elcallio I think you already solved this one, right?

**Comment by slivne** [comment] 2019-06-11 07:40
@amnonh - please have a look - @elcallio has a huge queue

**Comment by amnonh** [comment] 2019-06-23 09:48
@elcallio Can you please confirm if that's the issue you solved?

**Comment by elcallio** [comment] 2019-06-24 08:19
@amnonh Since it happens, I don't think I solved it. :-)
Did you mean the patch "APIMBeanServer: Handle nodeprobe wildcard queries in CF refresh"? It is merged since forever, so this might be different. From what I can see, the query made by nodetool should be handled by the refresh-on-wildcard match. 
Which version was toppartitions added in? I can't find it in my scylla build?

**Comment by amnonh** [comment] 2019-06-24 08:24
@elcallio it seems like the same problem (cannot find CF), I'll try to reproduce with master and see

**Comment by amnonh** [comment] 2019-06-24 08:29
@slivne @nirmaayan I have tested it with master and the issue is solved, I believe it was the solved by 512638ed6e4ee2b50835483e532cdb4f6283e2a6

**Comment by slivne** [comment] 2019-06-24 08:37
thanks @amnonh 

@tzach this is not part of 3.1 - do you want this backported ?

**Comment by slivne** [comment] 2019-06-30 09:38
pushed to next-3.1

**Closed** 2019-06-30 09:39 UTC
Labels: bug
