### ISSUE TITLE
Load_and_stream process did not report that loading is done

### ISSUE THREAD

**Issue by juliayakovlev** [scylladb/scylla#9902] opened 2022-01-12 07:38 UTC
*Installation details*
Kernel version: `5.11.0-1022-aws`
Scylla version (or git commit hash): `4.7.dev-0.20211230.12fa68fe6 with build-id 938d162cf1be1483853bf5b5417f5daf11e5ac24`
Cluster size: 6 nodes (i3.4xlarge)
OS (RHEL/CentOS/Ubuntu/AWS AMI): `ami-0668e251eb4f0f394` (aws: eu-west-1)

Scylla running with shards number (live nodes):
   alternator-3h-master-db-node-22e4d0ea-1 (3.251.89.77 | 10.0.3.82): 14 shards
   alternator-3h-master-db-node-22e4d0ea-3 (54.195.184.59 | 10.0.2.237): 14 shards
   alternator-3h-master-db-node-22e4d0ea-4 (34.244.180.206 | 10.0.2.245): 14 shards
   alternator-3h-master-db-node-22e4d0ea-5 (52.210.166.125 | 10.0.2.12): 14 shards
   alternator-3h-master-db-node-22e4d0ea-7 (54.154.151.148 | 10.0.2.79): 14 shards
   alternator-3h-master-db-node-22e4d0ea-8 (3.250.146.36 | 10.0.3.211): 14 shards
Scylla running with shards number (terminated nodes):
   alternator-3h-master-db-node-22e4d0ea-6 (54.195.83.107 | 10.0.0.135): 14 shards
   alternator-3h-master-db-node-22e4d0ea-2 (34.252.36.51 | 10.0.3.251): 14 shards

Test: `longevity-alternator-3h-test`
Test name: `longevity_test.LongevityTest.test_custom_time`
Test config file(s):
- [longevity-alternator-3h.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/8584390cb25ea782b18acef4a6d77099be58b0bc/test-cases/longevity/longevity-alternator-3h.yaml)

**Issue description**

Ran `load_and_stream` for prepared sstables. 

First sstables were loaded into `/var/lib/scylla/data/keyspace1/standard1-bed9f3e0710611ecb83025e199e61611/upload/` folder on the `alternator-3h-master-db-node-22e4d0ea-7` node. In the node log found messages that load_and_stream starts for 5 sstables:

```
2022-01-09T07:29:06+00:00 alternator-3h-master-db-node-22e4d0ea-7 !    INFO |  [shard 2] sstables_loader - Loading new SSTables for keyspace=keyspace1, table=standard1, load_and_stream=true, primary_replica_only=false
2022-01-09T07:29:06+00:00 alternator-3h-master-db-node-22e4d0ea-7 !    INFO |  [shard 10] sstables_loader - load_and_stream: started ops_uuid=1887add9-359e-4ffc-9bc5-ea9356147f8f, process [0-1] out of 1 sstables={/var/lib/scylla/data/keyspace1/standard1-bed9f3e0710611ecb83025e199e61611/upload/md-10-big-Data.db}
2022-01-09T07:29:06+00:00 alternator-3h-master-db-node-22e4d0ea-7 !    INFO |  [shard 8] sstables_loader - load_and_stream: started ops_uuid=571bc786-59e3-4201-9df1-c1519edd9f97, process [0-1] out of 1 sstables={/var/lib/scylla/data/keyspace1/standard1-bed9f3e0710611ecb83025e199e61611/upload/md-8-big-Data.db}
2022-01-09T07:29:06+00:00 alternator-3h-master-db-node-22e4d0ea-7 !    INFO |  [shard 12] sstables_loader - load_and_stream: started ops_uuid=73c3e87b-c07b-42c4-9653-a81736481653, process [0-1] out of 1 sstables={/var/lib/scylla/data/keyspace1/standard1-bed9f3e0710611ecb83025e199e61611/upload/md-12-big-Data.db}
2022-01-09T07:29:06+00:00 alternator-3h-master-db-node-22e4d0ea-7 !    INFO |  [shard 0] sstables_loader - load_and_stream: started ops_uuid=b9d30361-47a8-4841-acfb-1149f14de5cd, process [0-1] out of 1 sstables={/var/lib/scylla/data/keyspace1/standard1-bed9f3e0710611ecb83025e199e61611/upload/md-14-big-Data.db}
2022-01-09T07:29:06+00:00 alternator-3h-master-db-node-22e4d0ea-7 !    INFO |  [shard 1] sstables_loader - load_and_stream: started ops_uuid=cc9f6c0d-dafc-475b-a0a1-e29b8585262a, process [0-1] out of 1 sstables={/var/lib/scylla/data/keyspace1/standard1-bed9f3e0710611ecb83025e199e61611/upload/md-15-big-Data.db}
```

According to https://github.com/scylladb/scylla/blame/0f60cc84f4a259dc3b11cea2c2aa7a848cbcd839/sstables_loader.cc this is messaged from this line:
https://github.com/scylladb/scylla/blob/0f60cc84f4a259dc3b11cea2c2aa7a848cbcd839/sstables_loader.cc#L156 

Next info messages are expected according to code:
https://github.com/scylladb/scylla/blob/0f60cc84f4a259dc3b11cea2c2aa7a848cbcd839/sstables_loader.cc#L234

AND

https://github.com/scylladb/scylla/blob/0f60cc84f4a259dc3b11cea2c2aa7a848cbcd839/sstables_loader.cc#L240

Maybe warnings:
https://github.com/scylladb/scylla/blob/0f60cc84f4a259dc3b11cea2c2aa7a848cbcd839/sstables_loader.cc#L215
https://github.com/scylladb/scylla/blob/0f60cc84f4a259dc3b11cea2c2aa7a848cbcd839/sstables_loader.cc#L228

And in the end of process we expect to find:
https://github.com/scylladb/scylla/blob/0f60cc84f4a259dc3b11cea2c2aa7a848cbcd839/sstables_loader.cc#L278

OR

https://github.com/scylladb/scylla/blob/0f60cc84f4a259dc3b11cea2c2aa7a848cbcd839/sstables_loader.cc#L273

But any of those messages were not found in the log.
No errors or failures on this node or other nodes

Restore Monitor Stack command: `$ hydra investigate show-monitor 22e4d0ea-04c6-49de-99cb-bf4dc84f8842`
Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=22e4d0ea-04c6-49de-99cb-bf4dc84f8842)
Show all stored logs command: `$ hydra investigate show-logs 22e4d0ea-04c6-49de-99cb-bf4dc84f8842`

Test id: `22e4d0ea-04c6-49de-99cb-bf4dc84f8842`

Logs:
db-cluster - [https://cloudius-jenkins-test.s3.amazonaws.com/22e4d0ea-04c6-49de-99cb-bf4dc84f8842/20220109_081354/db-cluster-22e4d0ea.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/22e4d0ea-04c6-49de-99cb-bf4dc84f8842/20220109_081354/db-cluster-22e4d0ea.tar.gz)
sct - [https://cloudius-jenkins-test.s3.amazonaws.com/22e4d0ea-04c6-49de-99cb-bf4dc84f8842/20220109_081354/sct-runner-22e4d0ea.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/22e4d0ea-04c6-49de-99cb-bf4dc84f8842/20220109_081354/sct-runner-22e4d0ea.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/longevity/job/longevity-alternator-3h-test/335/)

**Comment by avikivity** [comment] 2022-01-12 10:40
Note, it's better to rely on the REST API return code for completion information rather than logs.

@asias does the REST API return on completion, or earlier?

**Comment by asias** [comment] 2022-01-12 11:08
The api returns only after the load and stream is done.

**Comment by asias** [comment] 2022-01-12 11:09
> But any of those messages were not found in the log.
> No errors or failures on this node or other nodes

I suspect logs were lost for some reason. This is not the first time I saw some logs were missed with sct.

**Comment by juliayakovlev** [comment] 2022-01-12 13:05
> > But any of those messages were not found in the log.
> > No errors or failures on this node or other nodes
> 
> I suspect logs were lost for some reason. This is not the first time I saw some logs were missed with sct.

@asias to check your suspection I re-run the test (with keeping of db nodes). The test is running now.
I connected to the node (not sct. logs, but directly node log) and still don't find that load_and_stream is finished.

Connect to `52.212.210.219` (node 6) and run grep:
```
journalctl -t scylla | egrep "load_and_stream|Done loading new" | less
```

Output:
```
Jan 12 12:29:40 alternator-3h-repr-loa-db-node-69800868-6 scylla[20852]:  [shard 2] sstables_loader - Loading new SSTables for keyspace=keyspace1, table=standard1, load_and_stream=true, primary_replica_only=false
Jan 12 12:29:40 alternator-3h-repr-loa-db-node-69800868-6 scylla[20852]:  [shard 13] sstables_loader - load_and_stream: started ops_uuid=5d567696-65c1-489f-b2da-f972471af751, process [0-1] out of 1 sstables={/var/lib/scylla/data/keyspace1/standard1-64eb8bd073a111ec87eea4f419ea8cf7/upload/md-13-big-Data.db}
Jan 12 12:29:40 alternator-3h-repr-loa-db-node-69800868-6 scylla[20852]:  [shard 10] sstables_loader - load_and_stream: started ops_uuid=a7b83125-8b9d-4af8-8584-c2e86b7011b8, process [0-1] out of 1 sstables={/var/lib/scylla/data/keyspace1/standard1-64eb8bd073a111ec87eea4f419ea8cf7/upload/md-10-big-Data.db}
Jan 12 12:29:40 alternator-3h-repr-loa-db-node-69800868-6 scylla[20852]:  [shard 11] sstables_loader - load_and_stream: started ops_uuid=c1652044-bcfd-48e6-95f0-aa5a46164564, process [0-1] out of 1 sstables={/var/lib/scylla/data/keyspace1/standard1-64eb8bd073a111ec87eea4f419ea8cf7/upload/md-11-big-Data.db}
```

Same in the `/var/log/messages`

I still don't see that the load has been finished.

**Comment by asias** [comment] 2022-01-13 06:59
@juliayakovlev Thanks. I think there is a real issue. The code probably hit a dead lock somewhere. It could be the reader dead lock where we saw with repair. I know you have some dtest for load and stream. It would be very helpful if you could reproduce with a dtest.

**Comment by slivne** [comment] 2022-01-14 20:16
@asias I was expecting the issue related to repair and reads to be localized for repair - AFAIK we do not have a generic issue with readers in any other place - why do you suspect that ?

If we create a coredump from the process can you (with the help of botond maybe check if its a reader issue or something else) - dtest can't scale to the same level of large nodes runs - so I am not sure it will reproduce with dtest.

**Comment by avikivity** [comment] 2022-01-16 15:45
> @juliayakovlev Thanks. I think there is a real issue. The code probably hit a dead lock somewhere. It could be the reader dead lock where we saw with repair. I know you have some dtest for load and stream. It would be very helpful if you could reproduce with a dtest.

If there was a deadlock, shouldn't the API not have returned?

**Comment by asias** [comment] 2022-01-17 01:40
> > @juliayakovlev Thanks. I think there is a real issue. The code probably hit a dead lock somewhere. It could be the reader dead lock where we saw with repair. I know you have some dtest for load and stream. It would be very helpful if you could reproduce with a dtest.
> 
> If there was a deadlock, shouldn't the API not have returned?

Avi, I think @juliayakovlev did not report the API returned. For some reason you thought the API returned though. 

@juliayakovlev please confirm what was the real issue you want to report. 

api did not finish,  log of finish did not show in the log
api finished, log of finish did not show in the log

**Comment by asias** [comment] 2022-01-17 02:36
> @asias I was expecting the issue related to repair and reads to be localized for repair - AFAIK we do not have a generic issue with readers in any other place - why do you suspect that ?

First, I think the issue was the api did not finish. We need @juliayakovlev to confirm. 

The code that could possibly dead lock are:  

```
auto permit = co_await _db.local().obtain_reader_permit(table, "sstables_loader::load_and_stream()", db::no_timeout);
while (auto mf = co_await reader()) {
```

We recently saw the reader deadlock: https://github.com/scylladb/scylla/issues/9751, despite we were very confident we fixed all the reader deadlock issues. We even hesitated to merge the patch below. 

```
ommit 1f86d5a87091d8b372df792f3251f327c2aa31e1
Author: Asias He <asias@scylladb.com>
Date:   Tue Jul 27 08:52:24 2021 +0800

    repair: Use a timeout for reading fragments

```

so, I suspected we might have more such dead lock issues.

I propose to add such timeout to the load and stream reader too.  A failed load and stream is much better than a hang. 

> If we create a coredump from the process can you (with the help of botond maybe) check if its a reader issue or something else - dtest can't scale to the same level of large nodes runs - so I am not sure it will reproduce with dtest.

Yes, we need Botond to take a look, if it is reader deadlock issue. If we could not reproduce with existing dtests or a small change to them, we can stick to sct test. I was just hoping we have luck to reproduce with dtest.

**Comment by juliayakovlev** [comment] 2022-01-17 06:43
> > > @juliayakovlev Thanks. I think there is a real issue. The code probably hit a dead lock somewhere. It could be the reader dead lock where we saw with repair. I know you have some dtest for load and stream. It would be very helpful if you could reproduce with a dtest.
> > 
> > 
> > If there was a deadlock, shouldn't the API not have returned?
> 
> Avi, I think @juliayakovlev did not report the API returned. For some reason you thought the API returned though.
> 
> @juliayakovlev please confirm what was the real issue you want to report.
> 
> api did not finish, log of finish did not show in the log api finished, log of finish did not show in the log

API finished, no errors. Log of finish did not show in the log

**Comment by asias** [comment] 2022-01-17 06:53
> > > > @juliayakovlev Thanks. I think there is a real issue. The code probably hit a dead lock somewhere. It could be the reader dead lock where we saw with repair. I know you have some dtest for load and stream. It would be very helpful if you could reproduce with a dtest.
> > > 
> > > 
> > > If there was a deadlock, shouldn't the API not have returned?
> > 
> > 
> > Avi, I think @juliayakovlev did not report the API returned. For some reason you thought the API returned though.
> > @juliayakovlev please confirm what was the real issue you want to report.
> > api did not finish, log of finish did not show in the log api finished, log of finish did not show in the log
> 
> API finished, no errors. Log of finish did not show in the log

OK. So was the data actually loaded into the cluster? We should check this as part of the test.

**Comment by slivne** [comment] 2022-01-31 07:45
@juliayakovlev / @asias ping - please get on a chat and align

**Comment by juliayakovlev** [comment] 2022-01-31 08:48
@slivne @asias I tried to reproduce it a few time, didn't received it again

**Comment by asias** [comment] 2022-02-22 06:49
It is possible the log messages are just missing due to https://github.com/scylladb/seastar/issues/1012

**Comment by asias** [comment] 2022-02-23 06:28
The seastar log fix is mereged and Julia could not reproduce. I am closing this issue.

**Closed by asias** 2022-02-23 06:28 UTC
Labels: bug, high, load_and_stream
