### ISSUE TITLE
CDC: a write can be recorded twice in cdc log

### ISSUE THREAD

**Issue by piodul** [scylladb/scylla#5900] opened 2020-02-25 15:07 UTC
In `cdc_tests.py:TestCdc` (PR: https://github.com/scylladb/scylla-dtest/pull/1330), the `cluster_reduction_with_cdc_test` sometimes fails and reports that the number of writes performed by the test does not match the number of log rows:

```
======================================================================
FAIL: cluster_reduction_with_cdc_test (cdc_tests.TestCdc)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/piodul/code/scylla-dtest/cdc_tests.py", line 216, in cluster_reduction_with_cdc_test
    self.cluster_reduction_with_cdc_template(with_preimage=False)
  File "/home/piodul/code/scylla-dtest/cdc_tests.py", line 206, in cluster_reduction_with_cdc_template
    self.check_that_all_writes_were_recorded(session, write_count, update_rows)
  File "/home/piodul/code/scylla-dtest/cdc_tests.py", line 370, in check_that_all_writes_were_recorded
    self.assertEqual(len(update_rows), write_count)
AssertionError: 199644 != 199639
```

In this test, preimage is not turned on, so there should be 1-1 correspondence between the number of writes and log row count. Instead, the number of cdc log rows is actually __greater__ than the number of writes performed by the test.

----

The test works by spawning 10 Python threads and writing to a 4-node cluster, to a table with the following schema:

```cql
CREATE TABLE ks.cf (a int, b text, PRIMARY KEY(a));
```

While continuously writing, one node is decommissioned and removed.

Each worker does each write with sequentially increasing partition key (`a`), setting `b` to their worker id (a number from range 0-9). Therefore, each log row should have a different combination of values in columns (_a, _b), but sometimes this property does not hold. Some examples:

```cql
cqlsh> select * from ks.cf_scylla_cdc_log where "_a" = 8266 and "_b" = (0, '3') allow filtering;

 stream_id_1        | stream_id_2         | time                                 | batch_seq_no | _a   | _b       | operation | ttl
--------------------+---------------------+--------------------------------------+--------------+------+----------+-----------+------
 518278407721352945 | -858789270981905598 | f31eff86-57d3-11ea-dbc1-c01c79bd7925 |            0 | 8266 | (0, '3') |         1 | null
 518278407721352945 | -858789270981905598 | f31eff86-57d3-11ea-68f6-51cfd649dbe5 |            0 | 8266 | (0, '3') |         1 | null

(2 rows)
cqlsh> select * from ks.cf_scylla_cdc_log where "_a" = 8267 and "_b" = (0, '8') allow filtering;

 stream_id_1         | stream_id_2         | time                                 | batch_seq_no | _a   | _b       | operation | ttl
---------------------+---------------------+--------------------------------------+--------------+------+----------+-----------+------
 2964271445341801990 | 5189319318448717638 | f31e83bc-57d3-11ea-e319-2e6c44eab9c8 |            0 | 8267 | (0, '8') |         1 | null
 2964271445341801990 | 5189319318448717638 | f31e83bc-57d3-11ea-1069-db169d9d3df4 |            0 | 8267 | (0, '8') |         1 | null

(2 rows)
```

In this test run, there were 5 pairs of (_a, _b) that had a duplicated record: `(8266, (0, '3')), (8267, (0, '8')), (8271, (0, '1')), (8293, (0, '9')), (8322, (0, '5'))`

----

Some more observations:

- Each duplicate pair of log records always share the first half of the `time` column.
- The fact that sequence number of all duplicated log rows are close to each other suggest that all duplications were caused by a singular event.
- This does not happen in other test cases of `cdc_test.py`. There is a similar test case `cluster_reduction_with_cdc_test` which runs only one worker thread, and I did not observe this problem there. I also did not observe this problem while running tests that add a node or do nothing while writing to the base table.
- I disabled retries and client timestamps in the Python driver (`cluster.default_retry_policy = RetryPolicy.RETHROW`, `session.use_client_timestamp = False`), and the issue still happens.

**Comment by slivne** [comment] 2020-03-01 11:18
what is the size of cluster you start with and after decomission.

e.g. 

did  started from 3 nodes with RF=3 and decommissioned one node, or from 4 nodes with RF=3 ?

do you have hintted_handoff enabled ?

although you have attempted to disable retries, lets double check that - e.g. maybe we can count the number of requests scylla received.

who produces these timestamps, is it client or server generated ?

**Comment by piodul** [comment] 2020-03-02 19:57
Some more details:

- Test started with a cluster with 4 nodes, then it was downsized to 3,
- Replication factor was 3,
- Hinted handoff was explicitly disabled.

For testing purposes, I added some code that prints mutations that come from CQL requests (to be more specific, I printed every mutation [from that vector](https://github.com/scylladb/scylla/blob/ba536dbc9530960a6132a0dc575fd31dee5365b2/cql3/statements/modification_statement.cc#L189)). I counted all mutations that were printed in the log and were destined for the base table used in the test, and it turns out that their number was equal to the number of cdc log rows. Moreover, I observed that if a write was done more than once, each time it was written to a different node.

Based on the observations above, now I suspect that this is an issue with Python driver. I thought I have properly disabled client timestamps and retry logic, but now I'm not so sure. I will confirm tomorrow that timestamps and retrying is set up properly, and if the problem persists, then it probably is a bug in the driver.

**Comment by piodul** [comment] 2020-03-06 06:14
Duplicate writes are caused by the following sequence of events:

- A write is attempted to be executed on a node,
- The node receives write request and does it, but closes the connection to the client before it has a chance to send write response,
- The python driver sees that the connection was closed, and retries the request on another host. This retry cannot be disabled at all in the driver version that we are using in dtests (3.15.0).

In the end, this __is__ a bug in Scylla, but not in the logic related to CDC. Until now, this did not do any harm, because of the idempotent nature of mutations.

I see two options:

1. Update the driver version in dtests to at least 3.18.0 and use `FallthroughRetryPolicy`, which prevents repeating the write,
1. Fix Scylla to reject new writes and wait for the old ones to complete when shutting down, instead of just closing all connections and allowing such race to happen.

I think 2) is the correct way to handle this issue. Choosing 1) will make the problem go away only in the tests, but will not fix it for anyone else that would wish to use an older driver or would want to retain the retry behavior.

@slivne @haaawk

**Comment by haaawk** [comment] 2020-03-06 07:26
I would go for updating the driver to 3.18.0 in dtests @roydahan @fruch what do you think?

**Comment by kbr-** [comment] 2020-03-06 08:15
> Fix Scylla to reject new writes and wait for the old ones to complete when shutting down, instead of just closing all connections and allowing such race to happen.

What do you mean "when shutting down"?

> Until now, this did not do any harm, because of the idempotent nature of mutations

What if "client timestamps" were disabled? Wouldn't the second mutation have a different timestamp?

---

My opinion: this is not a problem and we should just live with it.

The CDC client must merge changes which have the same timestamp anyway. That is, if the client sees two entries in the CDC log with different values in the `cdc$time` column, say `tuuid1` and `tuuid2`, but those values have the same timestamp underneath (i.e. `tounixtimestamp(tuuid1) == tounixtimestamp(tuuid2)`), the client must recognize this situation and perform any necessary merging. For example, say there's a column `v` of type `int`, and one of these changes set `v = 1`, and the other set `v = 2`. The client will have to recognize `v = 2` as the final value, even though in the log table the `v = 2` change could have appeared first due to the randomly generated part of `cdc$time`.

In the situation above, the client will have two changes that have the exact same data and timestamp, only the randomly generated part of `cdc$time` is different. The client would just perform the logic above and merge them into one.

**Comment by piodul** [comment] 2020-03-06 08:59
@kbr-

> What do you mean "when shutting down"?

More precisely speaking, when cql server is shutting down. It can happen e.g. when a node is being shut down completely, or being decommissioned. CQL server is shut down in such way that it just closes sockets, but does not wait for currently processed requests to be served before doing that. Because of that, it may happen that the server receives a write operation, performs it, but it fails to send it because the socket is closed - I observed in the log output that this happens.

Now that I think of it, a similar scenario may happen if the connection is closed by network issues. We won't be able to prevent it, so maybe fixing that race Scylla does not make a big difference, after all...

> What if "client timestamps" were disabled? Wouldn't the second mutation have a different timestamp?

It would have a different timestamp. I just meant that if the second mutation succeeded, then it would "overwrite" the previous one, and the effect would be the same as if only the second mutation was applied. If CDC is enabled for that table, then it will be problematic as they will produce two different events in the cdc log.

> In the situation described in this issue, the client will have two changes that have the exact same data and timestamp, only the randomly generated part of cdc$time is different. The client would just perform the logic above and merge them into one.

Yes, but only if client timestamps are used.

**Comment by kbr-** [comment] 2020-03-06 09:12
> It would have a different timestamp. I just meant that if the second mutation succeeded, then it would "overwrite" the previous one, and the effect would be the same as if only the second mutation was applied. If CDC is enabled for that table, then it will be problematic as they will produce two different events in the cdc log.

I'd argue that two writes actually did happen in that case, so we should log both of them.

Maybe it will even help catch application developers client misconfiguration problems :)

**Comment by haaawk** [comment] 2020-03-06 09:15
I wouldn't change Scylla. This is the expected behavior. Let's switch driver version in dtests and close this issue.

**Comment by haaawk** [comment] 2020-03-16 10:56
Behavior is expected and tests are fixed to handle it.

**Closed by haaawk** 2020-03-16 10:56 UTC
Labels: CDC, bug
