### ISSUE TITLE
Move to  node_exporter 0.14 or later

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#2452] opened 2017-06-07 06:44 UTC
*Installation details*
Scylla version (or git commit hash): 1.7

Current version of node_exporter installed in scylla_setup is 0.12
https://github.com/scylladb/scylla/blob/branch-1.7/dist/common/scripts/node_exporter_install#L30

Version 0.12 have an issue with reporting on disk with RAID0 and md_blocks_synced of 10
https://github.com/prometheus/node_exporter/issues/219

This issue was later fixed in 0.14
https://github.com/prometheus/node_exporter/commit/344fe2c4c540e4559b1c5b115e348974b5560bb0

Moving to 0.14 should solve this issue

**Comment by slivne** [comment] 2017-06-07 06:46
duplicate of #2097

**Closed** 2017-06-07 06:46 UTC
Labels: bug, duplicate, User Request
