### ISSUE TITLE
Reactor stalled for 9 ms during "Steady State" on latency during operations test

### ISSUE THREAD

**Issue by fgelcer** [scylladb/scylla#7890] opened 2021-01-07 20:00 UTC
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash): 4.4.dev-0.20201231.93a2c5233 with build-id 63738ab215ea91209c7488bf63b0556f6adf6c15
Cluster size: 3
OS (RHEL/CentOS/Ubuntu/AWS AMI): ami-047c88faadef0dbc6

`2021-01-01T07:03:53+00:00  perf-latency-nemesis-perf-v10-db-node-236aac08-3 !INFO    | scylla: Reactor stalled for 9 ms on shard 6.`

```
void seastar::backtrace<seastar::backtrace_buffer::append_backtrace()::{lambda(seastar::frame)#1}>(seastar::backtrace_buffer::append_backtrace()::{lambda(seastar::frame)#1}&&) at ./build/release/seastar/./seastar/include/seastar/util/backtrace.hh:59
 (inlined by) seastar::backtrace_buffer::append_backtrace() at ./build/release/seastar/./seastar/src/core/reactor.cc:731
 (inlined by) seastar::print_with_backtrace(seastar::backtrace_buffer&) at ./build/release/seastar/./seastar/src/core/reactor.cc:752
 (inlined by) seastar::internal::cpu_stall_detector::generate_trace() at ./build/release/seastar/./seastar/src/core/reactor.cc:1210
seastar::internal::cpu_stall_detector::maybe_report() at ./build/release/seastar/./seastar/src/core/reactor.cc:1056
 (inlined by) seastar::internal::cpu_stall_detector::on_signal() at ./build/release/seastar/./seastar/src/core/reactor.cc:1070
 (inlined by) seastar::reactor::block_notifier(int) at ./build/release/seastar/./seastar/src/core/reactor.cc:1193
?? ??:0
seastar::internal::promise_base::clear() at ./build/release/seastar/./seastar/src/core/future.cc:83
~promise_base at ./build/release/seastar/./seastar/include/seastar/core/future.hh:829
 (inlined by) ~continuation_base_with_promise at ./build/release/seastar/./seastar/include/seastar/core/future.hh:735
 (inlined by) seastar::continuation<seastar::internal::promise_base_with_type<seastar::temporary_buffer<char> >, seastar::reactor::do_read_some(seastar::pollable_fd_state&, seastar::internal::buffer_allocator*)::$_5, seastar::future<seastar::temporary_buffer<char> > seastar::future<void>::then_impl_nrvo<seastar::reactor::do_read_some(seastar::pollable_fd_state&, seastar::internal::buffer_allocator*)::$_5, seastar::future<seastar::temporary_buffer<char> > >(seastar::reactor::do_read_some(seastar::pollable_fd_state&, seastar::internal::buffer_allocator*)::$_5&&)::{lambda(seastar::internal::promise_base_with_type<seastar::temporary_buffer<char> >&&, seastar::reactor::do_read_some(seastar::pollable_fd_state&, seastar::internal::buffer_allocator*)::$_5&, seastar::future_state<seastar::internal::monostate>&&)#1}, void>::run_and_dispose() at ./build/release/seastar/./seastar/include/seastar/core/future.hh:771
seastar::reactor::run_tasks(seastar::reactor::task_queue&) at ./build/release/seastar/./seastar/src/core/reactor.cc:2220
 (inlined by) seastar::reactor::run_some_tasks() at ./build/release/seastar/./seastar/src/core/reactor.cc:2629
seastar::reactor::run() at ./build/release/seastar/./seastar/src/core/reactor.cc:2788
operator() at ./build/release/seastar/./seastar/src/core/reactor.cc:3979
 (inlined by) void std::__invoke_impl<void, seastar::smp::configure(boost::program_options::variables_map, seastar::reactor_config)::$_97&>(std::__invoke_other, seastar::smp::configure(boost::program_options::variables_map, seastar::reactor_config)::$_97&) at /usr/lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/bits/invoke.h:60
 (inlined by) std::enable_if<is_invocable_r_v<void, seastar::smp::configure(boost::program_options::variables_map, seastar::reactor_config)::$_97&>, void>::type std::__invoke_r<void, seastar::smp::configure(boost::program_options::variables_map, seastar::reactor_config)::$_97&>(seastar::smp::configure(boost::program_options::variables_map, seastar::reactor_config)::$_97&) at /usr/lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/bits/invoke.h:110
 (inlined by) std::_Function_handler<void (), seastar::smp::configure(boost::program_options::variables_map, seastar::reactor_config)::$_97>::_M_invoke(std::_Any_data const&) at /usr/lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/bits/std_function.h:291
std::function<void ()>::operator()() const at /usr/lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/bits/std_function.h:622
 (inlined by) seastar::posix_thread::start_routine(void*) at ./build/release/seastar/./seastar/src/core/posix.cc:60
```

all the nodes logs can be found [here](https://cloudius-jenkins-test.s3.amazonaws.com/236aac08-9e84-45d6-a707-35c201bbae18/20210101_111802/db-cluster-236aac08.zip)

**Comment by raphaelsc** [comment] 2021-01-07 20:11
Duplicate of #7882.

**Comment by fgelcer** [comment] 2021-01-07 20:13
> Duplicate of #7882.

if you are sure about it, you can close this one, although I don't see in this trace here `seastar::file_desc::read`

**Comment by raphaelsc** [comment] 2021-01-07 20:16
i see this though: reactor::do_read_some(seastar::pollable_fd_state) 

very likely same context switch issue, so i am closing

**Closed by raphaelsc** 2021-01-07 20:16 UTC

**Comment by avikivity** [comment] 2021-01-10 12:37
It's not the same thing.

**Comment by raphaelsc** [comment] 2021-01-10 12:42
On Sun, Jan 10, 2021 at 9:37 AM Avi Kivity <notifications@github.com> wrote:

> It's not the same thing.
>
The backtraces aren't equal, but I think they're both false positives due
to context switch, don't think we need to keep both issues opened.
