### ISSUE TITLE
"Too many files open" when joining new node to an existing cluster

### ISSUE THREAD

**Issue by brycejlowe** [scylladb/scylla#7094] opened 2020-08-24 15:44 UTC
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [X] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash): 4.1.3-0.20200729.9002592ee0c
Cluster size: 3
OS (RHEL/CentOS/Ubuntu/AWS AMI): Debian 9

I am in the process of joining 3 new nodes to our Scylla cluster in production (this will be doubling the current node count from 3 to 6).  I have gone through the document on adding a new node to a Scylla cluster (https://docs.scylladb.com/operating-scylla/procedures/cluster-management/add_node_to_cluster/) and attempted to do the join.  The process was moving along and i was seeing the node attempting to join the cluster using nodetool:

```
nodetool status
Datacenter: us-west-2
=====================
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address       Load       Tokens       Owns    Host ID                               Rack
UN  10.X.X.X  1.14 TB    256          ?       b0da9c9c-6fc1-466d-900e-ab58636e2a6b  2b
UJ  10.X.X.X    ?          256          ?       15d4d09c-4265-4080-9759-7d709e4113ea  2a
UN  10.X.X.X   1.03 TB    256          ?       d20ae8d3-6e85-49e4-bdf6-beb30ecbb400  2a
UN  10.X.X.X  1.03 TB    256          ?       0e9a1fc8-e34e-447b-8c1b-acded0fe34d1  2c
Note: Non-system keyspaces don't have the same replication settings, effective ownership information is meaningless
``` 

The process eventually error'd out with the following error: 

```
ERROR 2020-08-20 23:29:45,929 [shard 0] init - Startup failed: storage_io_error (Storage I/O error: 24: filesystem error: open failed: Too many open files [<install path>/tracing-log-scylladb/hints])
```

We currently have the per-process open file limit set very high for these nodes (~32,000) vs the typical 1024.  The existing nodes are running fine with the current limit, why is a new node trying to open so many files?

**Comment by slivne** [comment] 2020-08-24 19:03
@brycejlowe can you please share larger part of the logs prior to this error.

I expect the cause to be that during bootstrap in 4.1.X we are generating many small sstables - we have ongoing work on off-strategy compaction (https://github.com/scylladb/scylla/issues/5226) that is supposed to run a compaction before moving the created files. I expect this will solve the issue - once its out in a version you can use.

If you share the logs we can try and verify that.

Please note that by default we set scylla to run with much higher limits 200k files (https://github.com/scylladb/scylla/blob/master/dist/common/limits.d/scylla.conf)

**Comment by avikivity** [comment] 2020-08-25 08:12
Do you not have the scylla-kernel-conf package installed?

**Comment by slivne** [comment] 2020-09-06 10:03
@brycejlowe I am closing this, hope you increased the limit and it resolved. if not post the additional information we requested and we will be happy to help

**Closed by slivne** 2020-09-06 10:03 UTC
Labels: User Request
