### ISSUE TITLE
Segmentation fault and coredump during decommission termination and rebuild command failed

### ISSUE THREAD

**Issue by aleksbykov** [scylladb/scylla#6959] opened 2020-07-31 08:15 UTC
*Installation details*
Scylla version (or git commit hash): 666.development-0.20200727.a7df8486b with build-id ce64d8221eea00df25582ee16c87c0c0e8eed4e1
Cluster size: 4
OS (RHEL/CentOS/Ubuntu/AWS AMI): ami-0621715fb9a5e4fda (Detected Linux distribution: AMAZON2)

Decommission process started on node3:
```
020-07-31T01:13:31+00:00  longevity-tls-50gb-4d-hydra-gi-db-node-6edc3dfe-3 !INFO    | systemd-logind: Removed session 2017.
2020-07-31T01:13:35+00:00  longevity-tls-50gb-4d-hydra-gi-db-node-6edc3dfe-3 !INFO    | scylla: [shard 0] storage_service - DECOMMISSIONING: starts
2020-07-31T01:13:36+00:00  longevity-tls-50gb-4d-hydra-gi-db-node-6edc3dfe-3 !INFO    | scylla: [shard 0] storage_service - LEAVING: sleeping 30000 ms for batch processing and pending range setup
```
```
2020-07-31T01:14:06+00:00  longevity-tls-50gb-4d-hydra-gi-db-node-6edc3dfe-3 !INFO    | scylla: [shard 0] storage_service - DECOMMISSIONING: unbootstrap starts
2020-07-31T01:14:06+00:00  longevity-tls-50gb-4d-hydra-gi-db-node-6edc3dfe-3 !INFO    | scylla: [shard 0] repair - decommission_with_repair: started with keyspaces={system_distributed, keyspace_deflate, system_traces, mview, keyspace1, system_auth, keyspace_zstd, keyspace_snappy, keyspace_lz4}, leaving_node=10.0.1.238
2020-07-31T01:14:06+00:00  longevity-tls-50gb-4d-hydra-gi-db-node-6edc3dfe-3 !INFO    | scylla: [shard 0] repair - decommission_with_repair: started with keyspace=system_distributed, leaving_node=10.0.1.238, nr_ranges=774
2020-07-31T01:14:06+00:00  longevity-tls-50gb-4d-hydra-gi-db-node-6edc3dfe-3 !INFO    | scylla: [shard 0] repair - repair id [id=10, uuid=8d2d5525-2fbc-4475-853b-6eb77e4f56fd] to sync data for keyspace=system_distributed, status=started
```
During repair process on node3, node is rebooted:
```
2020-07-31T01:18:53+00:00  longevity-tls-50gb-4d-hydra-gi-db-node-6edc3dfe-3 !INFO    | systemd: Received SIGINT.
2020-07-31T01:18:53+00:00  longevity-tls-50gb-4d-hydra-gi-db-node-6edc3dfe-3 !INFO    | systemd: Stopped Dump dmesg to /var/log/dmesg.
2020-07-31T01:18:53+00:00  longevity-tls-50gb-4d-hydra-gi-db-node-6edc3dfe-3 !INFO    | systemd: Stopping Dump dmesg to /var/log/dmesg...
2020-07-31T01:18:53+00:00  longevity-tls-50gb-4d-hydra-gi-db-node-6edc3dfe-3 !INFO    | systemd: Stopping Session 189 of user scyllaadm.
2020-07-31T01:18:53+00:00  longevity-tls-50gb-4d-hydra-gi-db-node-6edc3dfe-3 !INFO    | systemd: Removed slice system-selinux\x2dpolicy\x2dmigrate\x2dlocal\x2dchanges.slice.
2020-07-31T01:18:53+00:00  longevity-tls-50gb-4d-hydra-gi-db-node-6edc3dfe-3 !INFO    | systemd: Stopping system-selinux\x2dpolicy\x2dmigrate\x2dlocal\x2dchanges.slice.
2020-07-31T01:18:53+00:00  longevity-tls-50gb-4d-hydra-gi-db-node-6edc3dfe-3 !INFO    | systemd: Stopped target Graphical Interface.
2020-07-31T01:18:53+00:00  longevity-tls-50gb-4d-hydra-gi-db-node-6edc3dfe-3 !INFO    | systemd: Stopping Graphical Interface.
2020-07-31T01:18:53+00:00  longevity-tls-50gb-4d-hydra-gi-db-node-6edc3dfe-3 !INFO    | systemd: Stopped target Timers.
2020-07-31T01:18:53+00:00  longevity-tls-50gb-4d-hydra-gi-db-node-6edc3dfe-3 !INFO    | systemd: Stopping Timers.
2020-07-31T01:18:53+00:00  longevity-tls-50gb-4d-hydra-gi-db-node-6edc3dfe-3 !INFO    | systemd: Stopped Daily Cleanup of Temporary Directories.
2020-07-31T01:18:53+00:00  longevity-tls-50gb-4d-hydra-gi-db-node-6edc3dfe-3 !INFO    | systemd: Stopping Daily Cleanup of Temporary Directories.
```
```
2020-07-31T01:18:54+00:00  longevity-tls-50gb-4d-hydra-gi-db-node-6edc3dfe-3 !INFO    | scylla: [shard 0] compaction_manager - Asked to stop
2020-07-31T01:18:54+00:00  longevity-tls-50gb-4d-hydra-gi-db-node-6edc3dfe-3 !NOTICE  | systemd: scylla-jmx.service: main process exited, code=exited, status=143/n/a
2020-07-31T01:18:54+00:00  longevity-tls-50gb-4d-hydra-gi-db-node-6edc3dfe-3 !INFO    | scylla: [shard 0] compaction_manager - Stopping 4 ongoing compactions
2020-07-31T01:18:54+00:00  longevity-tls-50gb-4d-hydra-gi-db-node-6edc3dfe-3 !INFO    | systemd: Stopped Scylla JMX.
2020-07-31T01:18:54+00:00  longevity-tls-50gb-4d-hydra-gi-db-node-6edc3dfe-3 !INFO    | scylla: [shard 0] init - Signal received; shutting down
2020-07-31T01:18:54+00:00  longevity-tls-50gb-4d-hydra-gi-db-node-6edc3dfe-3 !NOTICE  | systemd: Unit scylla-jmx.service entered failed state.
2020-07-31T01:18:54+00:00  longevity-tls-50gb-4d-hydra-gi-db-node-6edc3dfe-3 !INFO    | scylla: [shard 0] init - Shutting down redis service
2020-07-31T01:18:54+00:00  longevity-tls-50gb-4d-hydra-gi-db-node-6edc3dfe-3 !WARNING | systemd: scylla-jmx.service failed.
2020-07-31T01:18:54+00:00  longevity-tls-50gb-4d-hydra-gi-db-node-6edc3dfe-3 !INFO    | scylla: [shard 0] init - Shutting down redis service was successful
2020-07-31T01:18:54+00:00  longevity-tls-50gb-4d-hydra-gi-db-node-6edc3dfe-3 !INFO    | systemd: Stopping Scylla Server...
2020-07-31T01:18:54+00:00  longevity-tls-50gb-4d-hydra-gi-db-node-6edc3dfe-3 !INFO    | scylla: [shard 0] init - Shutting down view builder
2020-07-31T01:18:54+00:00  longevity-tls-50gb-4d-hydra-gi-db-node-6edc3dfe-3 !INFO    | scylla: [shard 0] view - Stopping view builder
2020-07-31T01:18:54+00:00  longevity-tls-50gb-4d-hydra-gi-db-node-6edc3dfe-3 !INFO    | scylla: [shard 8] compaction_manager - Asked to stop
```
During node rebooting and scylla processes stopping, on node 4 segmentation fault happened:
```
INFO    | scylla: Segmentation fault on shard 7.
INFO    | scylla: Backtrace:
INFO    | scylla: 0x0000000002cc9562
INFO    | scylla: 0x0000000002c78210
INFO    | scylla: 0x0000000002c784b5
INFO    | scylla: 0x0000000002c78550
INFO    | scylla: 0x00007f7011b8ca8f
INFO    | scylla: /opt/scylladb/libreloc/libstdc++.so.6+0x00000000000aa1fb
INFO    | scylla: 0x00000000010f7876
INFO    | scylla: 0x00000000023f40e9
INFO    | scylla: 0x0000000002c75887
INFO    | scylla: 0x0000000002c75bfe
INFO    | scylla: 0x0000000002ca6395
INFO    | scylla: 0x0000000002cb37aa
INFO    | scylla: 0x0000000002c4334d
INFO    | scylla: /opt/scylladb/libreloc/libpthread.so.0+0x0000000000009431
INFO    | scylla: /opt/scylladb/libreloc/libc.so.6+0x00000000001019d2
INFO    | kernel: reactor-7[43648]: segfault at 4a049a ip 00007f70113a11fc sp 00007f700c7e60d8 error 7 in libstdc++.so.6[7f701138d000+f8000]
INFO    | kernel: Code: 1e fa 48 89 37 e9 d4 ff ff ff 0f 1f 40 00 f3 0f 1e fa 48 8b 06 48 89 07 e9 c1 ff ff ff 90 f3 0f 1e fa 48 8b 07 48 85 c0 74 34 <f0> 83 68 80 01 75 2d 53 
ERR     | sshd[109942]: error: AuthorizedKeysCommand /opt/aws/bin/eic_run_authorized_keys centos SHA256:g7OmDbWC8qLUZHxjMohQe3LsQHfcOJbG1ZHqodB6smc failed, status 22
```
coredump unfortunately was not uploaded:
```
backtrace=           PID: 43641 (scylla)
           UID: 996 (scylla)
           GID: 1001 (scylla)
        Signal: 11 (SEGV)
     Timestamp: Fri 2020-07-31 01:18:54 UTC (5min ago)
  Command Line: /usr/bin/scylla --blocked-reactor-notify-ms 500 --abort-on-lsa-bad-alloc 1 --abort-on-seastar-bad-alloc --abort-on-internal-error 1 --abort-on-ebadf 1 --enable-sstable-key-validation 1 --log-to-syslog 1 --log-to-stdout 0 --default-log-level info --network-stack posix --io-properties-file=/etc/scylla.d/io_properties.yaml --cpuset 1-7,9-15 --lock-memory=1
    Executable: /opt/scylladb/libexec/scylla
 Control Group: /
       Boot ID: 8697d6ec6e6c43de9a39a7bc0f5807c1
    Machine ID: ec214dee1f497e5a0c3f972da49e4684
      Hostname: longevity-tls-50gb-4d-hydra-gi-db-node-6edc3dfe-4
      Coredump: /var/lib/systemd/coredump/core.scylla.996.8697d6ec6e6c43de9a39a7bc0f5807c1.43641.1596158334000000
       Message: Process 43641 (scylla) of user 996 dumped core.
                
                Stack trace of thread 43648:
                #0  0x00007f70113a11fc _ZNSt15__exception_ptr13exception_ptr10_M_releaseEv (libstdc++.so.6)
                #1  0x00000000010f7877 _ZNSt15__exception_ptr13exception_ptraSEOS0_ (scylla)
                #2  0x00000000023f40ea _ZN7seastar12continuationINS_8internal22promise_base_with_typeIJEEEZNS_6futureIJEE16handle_exceptionIZN13repair_writer13create_writerERNS_7shardedI8databaseEEjEUlNSt15__exception_ptr13exception_ptrEE1_EES5_OT_EUlSG_E_ZZNS5_17then_wrapped_nrvoIS5_SH_EENS_8futurizeISF_E4typeEOT0_ENKUlvE_clEvEUlRS3_RSH_ONS_12future_stateIJEEEE_JEE15run_and_disposeEv (scylla)
                #3  0x0000000002c75888 _ZN7seastar7reactor9run_tasksERNS0_10task_queueE (scylla)
                #4  0x0000000002c75bff _ZN7seastar7reactor14run_some_tasksEv (scylla)
                #5  0x0000000002ca6396 _ZN7seastar7reactor14run_some_tasksEv (scylla)
                #6  0x0000000002cb37ab _ZZN7seastar3smp9configureEN5boost15program_options13variables_mapENS_14reactor_configEENKUlvE1_clEv (scylla)
                #7  0x0000000002c4334e _ZNKSt8functionIFvvEEclEv (scylla)
                #8  0x00007f7011b81432 start_thread (libpthread.so.0)
                #9  0x00007f70112139d3 __clone (libc.so.6)
                
                Stack trace of thread 43668:
                #0  0x00007f7011b8b9ac read (libpthread.so.0)
                #1  0x0000000002ef9057 _ZN7seastar11thread_pool4workENS_13basic_sstringIcjLj15ELb1EEE (scylla)
                #2  0x0000000002ef92b8 operator() (scylla)
                #3  0x0000000002c4334e _ZNKSt8functionIFvvEEclEv (scylla)
                #4  0x00007f7011b81432 start_thread (libpthread.so.0)
                #5  0x00007f70112139d3 __clone (libc.so.6)
                
                Stack trace of thread 43659:
                #0  0x00007f7011b8b9ac read (libpthread.so.0)
                #1  0x0000000002ef9057 _ZN7seastar11thread_pool4workENS_13basic_sstringIcjLj15ELb1EEE (scylla)
                #2  0x0000000002ef92b8 operator() (scylla)
                #3  0x0000000002c4334e _ZNKSt8functionIFvvEEclEv (scylla)
                #4  0x00007f7011b81432 start_thread (libpthread.so.0)
                #5  0x00007f70112139d3 __clone (libc.so.6)
                
                Stack trace of thread 43667:
                #0  0x00007f7011b8b9ac read (libpthread.so.0)
                #1  0x0000000002ef9057 _ZN7seastar11thread_pool4workENS_13basic_sstringIcjLj15ELb1EEE (scylla)
                #2  0x0000000002ef92b8 operator() (scylla)
                #3  0x0000000002c4334e _ZNKSt8functionIFvvEEclEv (scylla)
                #4  0x00007f7011b81432 start_thread (libpthread.so.0)
                #5  0x00007f70112139d3 __clone (libc.so.6)
                
                Stack trace of thread 43666:
                #0  0x00007f7011b8b9ac read (libpthread.so.0)
                #1  0x0000000002ef9057 _ZN7seastar11thread_pool4workENS_13basic_sstringIcjLj15ELb1EEE (scylla)
                #2  0x0000000002ef92b8 operator() (scylla)
                #3  0x0000000002c4334e _ZNKSt8functionIFvvEEclEv (scylla)
                #4  0x00007f7011b81432 start_thread (libpthread.so.0)
                #5  0x00007f70112139d3 __clone (libc.so.6)
                
                Stack trace of thread 43658:
                #0  0x00007f7011b8b9ac read (libpthread.so.0)
                #1  0x0000000002ef9057 _ZN7seastar11thread_pool4workENS_13basic_sstringIcjLj15ELb1EEE (scylla)
                #2  0x0000000002ef92b8 operator() (scylla)
                #3  0x0000000002c4334e _ZNKSt8functionIFvvEEclEv (scylla)
                #4  0x00007f7011b81432 start_thread (libpthread.so.0)
                #5  0x00007f70112139d3 __clone (libc.so.6)
                
                Stack trace of thread 43664:
                #0  0x00007f7011b8b9ac read (libpthread.so.0)
                #1  0x0000000002ef9057 _ZN7seastar11thread_pool4workENS_13basic_sstringIcjLj15ELb1EEE (scylla)
                #2  0x0000000002ef92b8 operator() (scylla)
                #3  0x0000000002c4334e _ZNKSt8functionIFvvEEclEv (scylla)
                #4  0x00007f7011b81432 start_thread (libpthread.so.0)
                #5  0x00007f70112139d3 __clone (libc.so.6)
                
                Stack trace of thread 43645:
                #0  0x00007f701120e43d syscall (libc.so.6)
                #1  0x0000000002effc29 _ZN7seastar8internal9io_submitEmlPPNS0_9linux_abi4iocbE (scylla)
                #2  0x0000000002efc8d8 _ZN7seastar19aio_storage_context11submit_workEv (scylla)
                #3  0x0000000002efcb70 _ZN7seastar19reactor_backend_aio18kernel_submit_workEv (scylla)
                #4  0x0000000002c69c2d _ZN7seastar7reactor9poll_onceEv (scylla)
                #5  0x0000000002ca63c9 _ZNKSt8functionIFbvEEclEv (scylla)
                #6  0x0000000002cb37ab _ZZN7seastar3smp9configureEN5boost15program_options13variables_mapENS_14reactor_configEENKUlvE1_clEv (scylla)
                #7  0x0000000002c4334e _ZNKSt8functionIFvvEEclEv (scylla)
                #8  0x00007f7011b81432 start_thread (libpthread.so.0)
                #9  0x00007f70112139d3 __clone (libc.so.6)
```

After node3 was started again, and scylla was up, on node3 the nodetool rebuild was executed
```
2020-07-31T01:21:33+00:00  longevity-tls-50gb-4d-hydra-gi-db-node-6edc3dfe-3 !INFO    | scylla: [shard 0] storage_service - rebuild from dc: (any dc)
2020-07-31T01:21:33+00:00  longevity-tls-50gb-4d-hydra-gi-db-node-6edc3dfe-3 !INFO    | scylla: [shard 0] repair - rebuild_with_repair: started with keyspaces={system_auth, system_traces, keyspace_lz4, mview, keyspace1, keyspace_zstd, keyspace_deflate, keyspace_snappy, system_distributed}, source_dc=eu-west
2020-07-31T01:21:33+00:00  longevity-tls-50gb-4d-hydra-gi-db-node-6edc3dfe-3 !INFO    | scylla: [shard 0] repair - rebuild_with_repair: started with keyspace=system_auth, source_dc=eu-west, nr_ranges=774
```
but command failed:
```
Command: 'nodetool -u cassandra -pw cassandra  rebuild '

Exit code: 1

Stdout:

Using /etc/scylla/scylla.yaml as the config file
nodetool: Scylla API server HTTP POST to URL '/storage_service/rebuild' failed: std::runtime_error ({shard 0: std::runtime_error (repair id [id=1, uuid=3200fa9f-2758-4bc0-bee1-39abdbcd8f16] on shard 0 failed to repair 295 sub ranges), shard 1: std::runtime_error (repair id [id=1, uuid=3200fa9f-2758-4bc0-bee1-39abdbcd8f16] on shard 1 failed to repair 295 sub ranges), shard 2: std::runtime_error (repair id [id=1, uuid=3200fa9f-2758-4bc0-bee1-39abdbcd8f16] on shard 2 failed to repair 295 sub ranges), shard 3: std::runtime_error (repair id [id=1, uuid=3200fa9f-2758-4bc0-bee1-39abdbcd8f16] on shard 3 failed to repair 295 sub ranges), shard 4: std::runtime_error (repair id [id=1, uuid=3200fa9f-2758-4bc0-bee1-39abdbcd8f16] on shard 4 failed to repair 295 sub ranges), shard 5: std::runtime_error (repair id [id=1, uuid=3200fa9f-2758-4bc0-bee1-39abdbcd8f16] on shard 5 failed to repair 295 sub ranges), shard 6: std::runtime_error (repair id [id=1, uuid=3200fa9f-2758-4bc0-bee1-39abdbcd8f16] on shard 6 failed to repair 295 sub ranges), shard 7: std::runtime_error (repair id [id=1, uuid=3200fa9f-2758-4bc0-bee1-39abdbcd8f16] on shard 7 failed to repair 295 sub ranges), shard 8: std::runtime_error (repair id [id=1, uuid=3200fa9f-2758-4bc0-bee1-39abdbcd8f16] on shard 8 failed to repair 295 sub ranges), shard 9: std::runtime_error (repair id [id=1, uuid=3200fa9f-2758-4bc0-bee1-39abdbcd8f16] on shard 9 failed to repair 295 sub ranges), shard 10: std::runtime_error (repair id [id=1, uuid=3200fa9f-2758-4bc0-bee1-39abdbcd8f16] on shard 10 failed to repair 295 sub ranges), shard 11: std::runtime_error (repair id [id=1, uuid=3200fa9f-2758-4bc0-bee1-39abdbcd8f16] on shard 11 failed to repair 295 sub ranges), shard 12: std::runtime_error (repair id [id=1, uuid=3200fa9f-2758-4bc0-bee1-39abdbcd8f16] on shard 12 failed to repair 295 sub ranges), shard 13: std::runtime_error (repair id [id=1, uuid=3200fa9f-2758-4bc0-bee1-39abdbcd8f16] on shard 13 failed to repair 295 sub ranges)})
See 'nodetool help' or 'nodetool help <command>'.

Stderr:
```
DB logs: https://cloudius-jenkins-test.s3.amazonaws.com/6edc3dfe-db0d-45b1-a637-278ca4d6b20a/20200731_020501/db-cluster-6edc3dfe.zip

**Comment by aleksbykov** [comment] 2020-07-31 08:15
Job link: https://jenkins.scylladb.com/view/master/job/scylla-master/view/master-test/job/longevity/job/longevity-50gb-4days/20/

**Comment by slivne** [comment] 2020-08-02 09:39
@asias / @denesb / @bhalevy - its an exception fro the repair_writer (I am not sure who should handle).

Please clarify if this exists in 4.2 as well

**Comment by asias** [comment] 2020-08-03 01:09
$ c++filt 
_ZN7seastar12continuationINS_8internal22promise_base_with_typeIJEEEZNS_6futureIJEE16handle_exceptionIZN13repair_writer13create_writerERNS_7shardedI8databaseEEjEUlNSt15__exception_ptr13exception_ptrEE1_EES5_OT_EUlSG_E_ZZNS5_17then_wrapped_nrvoIS5_SH_EENS_8futurizeISF_E4typeEOT0_ENKUlvE_clEvEUlRS3_RSH_ONS_12future_stateIJEEEE_JEE15run_and_disposeEv
seastar::continuation<seastar::internal::promise_base_with_type<>, seastar::future<>::handle_exception<repair_writer::create_writer(seastar::sharded<database>&, unsigned int)::{lambda(std::__exception_ptr::exception_ptr)#3}>(repair_writer::create_writer(seastar::sharded<database>&, unsigned int)::{lambda(std::__exception_ptr::exception_ptr)#3}&&)::{lambda(auto:1)#1}, seastar::future<>::then_wrapped_nrvo<seastar::future<>, repair_writer::create_writer(seastar::sharded<database>&, unsigned int)::{lambda(std::__exception_ptr::exception_ptr)#3}&&>(seastar::future<>&&)::{lambda()#1}::operator()() const::{lambda(seastar::internal::promise_base_with_type<>&, auto:1&, seastar::future_state<>&&)#1}>::run_and_dispose()


The issue is fixed by

```
commit e6f640441a726c9b6f9ccfb2a482d809ad962041
Author: Asias He <asias@scylladb.com>
Date:   Tue Jul 28 08:50:17 2020 +0800

    repair: Fix race between create_writer and wait_for_writer_done

```

It has been backported to 4.0,  4.1 and 4.2 already.

**Closed by asias** 2020-08-03 01:09 UTC
Labels: high, repair-based-operations
