### ISSUE TITLE
Docker Image doesn't work on Mac M1 architecture

### ISSUE THREAD

**Issue by robertczupiol** [scylladb/scylla#8642] opened 2021-05-12 10:22 UTC
For development part it's a critical mission to start local Scylla cluster on developers Mac (for example - local integration tests).

Command:
```
docker run --name some-scylla --hostname some-scylla -d scylladb/scylla
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
```

Scylla didn't get up:
```
docker exec -it some-scylla nodetool status 
Using /etc/scylla/scylla.yaml as the config file
nodetool: Unable to connect to Scylla API server: java.net.ConnectException: Connection refused (Connection refused)
See 'nodetool help' or 'nodetool help <command>'.
```

journalctl and /var/log/scylla are empty

**Comment by syuu1228** [comment] 2021-05-19 10:14
@robertczupiol Our Docker image is only supported x86_64 architecture, you need to specify option to force using x86_64 like this:
`docker run --platform linux/amd64 --name some-scylla --hostname some-scylla -ti scylladb/scylla`

**Comment by robertczupiol** [comment] 2021-05-20 15:39
@syuu1228 thx for Your suggestion but that kind of command also didn't work :(

```
Could not load host key: /etc/ssh/ssh_host_ecdsa_key
Connecting to http://localhost:10000
Starting the JMX server
JMX is enabled to receive remote connections on port: 7199
Traceback (most recent call last):
  File "/opt/scylladb/scripts/libexec/scylla-housekeeping", line 208, in <module>
    args.func(args)
  File "/opt/scylladb/scripts/libexec/scylla-housekeeping", line 134, in check_version
    current_version = sanitize_version(get_api('/storage_service/scylla_release_version'))
  File "/opt/scylladb/scripts/libexec/scylla-housekeeping", line 93, in get_api
    return get_json_from_url("http://" + api_address + path)
  File "/opt/scylladb/scripts/libexec/scylla-housekeeping", line 88, in get_json_from_url
    raise RuntimeError(f'Failed to get "{path}" due to the following error: {retval}')
RuntimeError: Failed to get "http://localhost:10000/storage_service/scylla_release_version" due to the following error: <urlopen error [Errno 99] Cannot assign requested address>

```

**Comment by avelanarius** [comment] 2021-05-29 14:42
@robertczupiol Could you post the entire Scylla log when running with `docker run --platform linux/amd64 --name some-scylla --hostname some-scylla -ti scylladb/scylla`? (Does it even begin to start up? You previously said that the log folder was empty, but I'm not sure if it is true also for the second `docker run` command)

As far as I am aware, running x64 containers on Docker on M1 works by QEMU user-space emulation. (There aren't many resources describing this, but some context here: https://stackoverflow.com/a/66435150). 

I tried running Scylla through such emulation: `qemu-x86_64-static ./build/dev/scylla ...` on my x64 laptop and with my own Scylla build. It fails to start because `qemu-x86_64-static` quickly fills up entire RAM (>32GB), suggesting that there is some issue with the QEMU emulation.

**Comment by robertczupiol** [comment] 2021-05-30 20:54
yeap, on /var/log/scylla is nothin' but normally docker logs gave me that:

```
running: (['/opt/scylladb/scripts/scylla_dev_mode_setup', '--developer-mode', '1'],)
running: (['/opt/scylladb/scripts/scylla_io_setup'],)
2021-05-30 20:45:31,302 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
2021-05-30 20:45:31,304 INFO Included extra file "/etc/supervisord.conf.d/node-exporter.conf" during parsing
2021-05-30 20:45:31,304 INFO Included extra file "/etc/supervisord.conf.d/rsyslog.conf" during parsing
2021-05-30 20:45:31,304 INFO Included extra file "/etc/supervisord.conf.d/scylla-housekeeping.conf" during parsing
2021-05-30 20:45:31,304 INFO Included extra file "/etc/supervisord.conf.d/scylla-jmx.conf" during parsing
2021-05-30 20:45:31,305 INFO Included extra file "/etc/supervisord.conf.d/scylla-server.conf" during parsing
2021-05-30 20:45:31,305 INFO Included extra file "/etc/supervisord.conf.d/sshd-server.conf" during parsing
2021-05-30 20:45:31,391 INFO RPC interface 'supervisor' initialized
2021-05-30 20:45:31,391 CRIT Server 'inet_http_server' running without any HTTP authentication checking
2021-05-30 20:45:31,392 INFO supervisord started with pid 76
2021-05-30 20:45:32,412 INFO spawned: 'scylla' with pid 85
2021-05-30 20:45:32,421 INFO spawned: 'scylla-housekeeping' with pid 87
2021-05-30 20:45:32,425 INFO spawned: 'sshd' with pid 89
2021-05-30 20:45:32,428 INFO spawned: 'scylla-jmx' with pid 91
2021-05-30 20:45:32,431 INFO spawned: 'rsyslog' with pid 93
2021-05-30 20:45:32,435 INFO spawned: 'node-exporter' with pid 94
Generating public/private ed25519 key pair.
Your identification has been saved in /etc/ssh/ssh_host_ed25519_key.
Your public key has been saved in /etc/ssh/ssh_host_ed25519_key.pub.
The key fingerprint is:
SHA256:VUnq4GLbkhmhCDDjTYAGJfgYbo2R9IASaycDCttmELQ root@some-scylla
The key's randomart image is:
+--[ED25519 256]--+
|^O+.       .o.   |
|%%*        o.    |
|OEB+  . . o      |
|oB=o . o +       |
|. . . + S .      |
|     . B         |
|      = .        |
|       .         |
|                 |
+----[SHA256]-----+
time="2021-05-30T20:45:32Z" level=info msg="Starting node_exporter (version=0.17.0, branch=HEAD, revision=f6f6194a436b9a63d0439abc585c76b19a206b21)" source="node_exporter.go:82"
time="2021-05-30T20:45:32Z" level=info msg="Build context (go=go1.11.2, user=root@322511e06ced, date=20181130-15:51:33)" source="node_exporter.go:83"
time="2021-05-30T20:45:32Z" level=info msg="Enabled collectors:" source="node_exporter.go:90"
time="2021-05-30T20:45:32Z" level=info msg=" - arp" source="node_exporter.go:97"
time="2021-05-30T20:45:32Z" level=info msg=" - bcache" source="node_exporter.go:97"
time="2021-05-30T20:45:32Z" level=info msg=" - bonding" source="node_exporter.go:97"
time="2021-05-30T20:45:32Z" level=info msg=" - conntrack" source="node_exporter.go:97"
time="2021-05-30T20:45:32Z" level=info msg=" - cpu" source="node_exporter.go:97"
time="2021-05-30T20:45:32Z" level=info msg=" - diskstats" source="node_exporter.go:97"
time="2021-05-30T20:45:32Z" level=info msg=" - edac" source="node_exporter.go:97"
time="2021-05-30T20:45:32Z" level=info msg=" - entropy" source="node_exporter.go:97"
time="2021-05-30T20:45:32Z" level=info msg=" - filefd" source="node_exporter.go:97"
time="2021-05-30T20:45:32Z" level=info msg=" - filesystem" source="node_exporter.go:97"
time="2021-05-30T20:45:32Z" level=info msg=" - hwmon" source="node_exporter.go:97"
time="2021-05-30T20:45:32Z" level=info msg=" - infiniband" source="node_exporter.go:97"
time="2021-05-30T20:45:32Z" level=info msg=" - interrupts" source="node_exporter.go:97"
time="2021-05-30T20:45:32Z" level=info msg=" - ipvs" source="node_exporter.go:97"
time="2021-05-30T20:45:32Z" level=info msg=" - loadavg" source="node_exporter.go:97"
time="2021-05-30T20:45:32Z" level=info msg=" - mdadm" source="node_exporter.go:97"
time="2021-05-30T20:45:32Z" level=info msg=" - meminfo" source="node_exporter.go:97"
time="2021-05-30T20:45:32Z" level=info msg=" - netclass" source="node_exporter.go:97"
time="2021-05-30T20:45:32Z" level=info msg=" - netdev" source="node_exporter.go:97"
time="2021-05-30T20:45:32Z" level=info msg=" - netstat" source="node_exporter.go:97"
time="2021-05-30T20:45:32Z" level=info msg=" - nfs" source="node_exporter.go:97"
time="2021-05-30T20:45:32Z" level=info msg=" - nfsd" source="node_exporter.go:97"
time="2021-05-30T20:45:32Z" level=info msg=" - sockstat" source="node_exporter.go:97"
time="2021-05-30T20:45:32Z" level=info msg=" - stat" source="node_exporter.go:97"
time="2021-05-30T20:45:32Z" level=info msg=" - textfile" source="node_exporter.go:97"
time="2021-05-30T20:45:32Z" level=info msg=" - time" source="node_exporter.go:97"
time="2021-05-30T20:45:32Z" level=info msg=" - timex" source="node_exporter.go:97"
time="2021-05-30T20:45:32Z" level=info msg=" - uname" source="node_exporter.go:97"
time="2021-05-30T20:45:32Z" level=info msg=" - vmstat" source="node_exporter.go:97"
time="2021-05-30T20:45:32Z" level=info msg=" - xfs" source="node_exporter.go:97"
time="2021-05-30T20:45:32Z" level=info msg=" - zfs" source="node_exporter.go:97"
time="2021-05-30T20:45:32Z" level=info msg="Listening on :9100" source="node_exporter.go:111"
Generating public/private rsa key pair.
Your identification has been saved in /etc/ssh/ssh_host_rsa_key.
Your public key has been saved in /etc/ssh/ssh_host_rsa_key.pub.
The key fingerprint is:
SHA256:+lbI0QWsnOkdU52bb5VTfcybdgOzKJ4981TNmvAkAOM root@some-scylla
The key's randomart image is:
+---[RSA 4096]----+
|        oo.. . +.|
|       . .o ooo *|
|       .E= +. ++B|
|        *.+.o.+O=|
|       oS++o =o+=|
|       .+oo+ .+ o|
|      .  .  =  . |
|       ..    .   |
|       ..        |
+----[SHA256]-----+
2021-05-30 20:45:33,548 INFO success: scylla entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2021-05-30 20:45:33,548 INFO success: scylla-housekeeping entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2021-05-30 20:45:33,548 INFO success: sshd entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2021-05-30 20:45:33,548 INFO success: scylla-jmx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2021-05-30 20:45:33,548 INFO success: rsyslog entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2021-05-30 20:45:33,549 INFO success: node-exporter entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
Could not load host key: /etc/ssh/ssh_host_ecdsa_key
Connecting to http://localhost:10000
Starting the JMX server
Traceback (most recent call last):
  File "/opt/scylladb/scripts/libexec/scylla-housekeeping", line 208, in <module>
    args.func(args)
  File "/opt/scylladb/scripts/libexec/scylla-housekeeping", line 134, in check_version
    current_version = sanitize_version(get_api('/storage_service/scylla_release_version'))
  File "/opt/scylladb/scripts/libexec/scylla-housekeeping", line 93, in get_api
    return get_json_from_url("http://" + api_address + path)
  File "/opt/scylladb/scripts/libexec/scylla-housekeeping", line 88, in get_json_from_url
    raise RuntimeError(f'Failed to get "{path}" due to the following error: {retval}')
RuntimeError: Failed to get "http://localhost:10000/storage_service/scylla_release_version" due to the following error: <urlopen error [Errno 99] Cannot assign requested address>
2021-05-30 20:45:46,685 INFO exited: scylla (terminated by SIGKILL; not expected)
2021-05-30 20:45:47,755 INFO spawned: 'scylla' with pid 204
2021-05-30 20:45:48,760 INFO success: scylla entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2021-05-30 20:46:01,442 INFO exited: scylla (terminated by SIGKILL; not expected)
2021-05-30 20:46:02,602 INFO spawned: 'scylla' with pid 234
2021-05-30 20:46:03,606 INFO success: scylla entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2021-05-30 20:46:16,393 INFO exited: scylla (terminated by SIGKILL; not expected)
2021-05-30 20:46:17,438 INFO spawned: 'scylla' with pid 264

```

**Comment by avelanarius** [comment] 2021-05-30 23:11
The only solution to this problem is a release of an ARM Scylla Docker instance (no ETA at the moment...). The Docker x64 virtualization probably won't work:

I have investigated the underlying QEMU emulation problem (as this is what I suspect Docker is doing). At startup, Scylla performs the following syscall: `mmap(NULL, size_t(1) << 45, PROT_NONE, MAP_PRIVATE | MAP_ANONYMOUS | MAP_NORESERVE, -1, 0)` ([`mem_base()`](https://github.com/scylladb/seastar/blob/4506b8784a6300ec86e3a3d0145723f851ca6b11/src/core/memory.cc#L283-L286)).

This syscall is normally performed lazily by the kernel (it obviously does not reserve 32TB of memory). However, QEMU does not perform it lazily, filling out information for each page in that 32TBs of memory ([`set_page_flags()`](https://github.com/qemu/qemu/blob/52848929b70dcf92a68aedcfd90207be81ba3274/accel/tcg/translate-all.c#L2715)). That many pages causes QEMU to use a lot of memory, and ultimately QEMU/Scylla is killed by the OOM killer (that would explain `scylla (terminated by SIGKILL; not expected)` in logs). This issue was already [reported here](https://gitlab.com/qemu-project/qemu/-/issues/290), but it doesn't seem it will be fixed soon in QEMU.

**Comment by AnatoliyValeev** [comment] 2021-06-14 16:09
Hi guys! Is there any news on this issue? Is there any way to solve this problem other than waiting for the QEMU fix?
Thank you!

**Comment by sfroment** [comment] 2021-08-10 15:17
@AnatoliyValeev taken from the scylla [slack](https://scylladb-users.slack.com/archives/C5RBUC0ES/p1627909513001400): ```docker run --name some-scylla -d scylladb/scylla:4.6.dev-0.20210801.3089558f8```

**Comment by AnatoliyValeev** [comment] 2021-09-10 11:02
@sfroment seems it works for me. Thank you!

**Comment by nikontr** [comment] 2021-11-02 11:37
> @AnatoliyValeev taken from the scylla [slack](https://scylladb-users.slack.com/archives/C5RBUC0ES/p1627909513001400): `docker run --name some-scylla -d scylladb/scylla:4.6.dev-0.20210801.3089558f8`

Works for me too! I hope it gets compiled for arm64 soon

**Comment by cjbottaro** [comment] 2021-11-26 18:06
Any updated builds? The aforementioned build `scylladb/scylla:4.6.dev-0.20210801.3089558f8` segfaults when I run certain CQL statements.

```
Segmentation fault on shard 2.
Backtrace:
  0x2622a23
  0x264e7c3
  linux-vdso.so.1+0x79b
  0x140ce3f
  0x140d207
  0x16e93df
  0x26329c3
  0x2633a6b
  0x264ed17
  0x260f9ff
  /opt/scylladb/libreloc/libpthread.so.0+0x8007
  /opt/scylladb/libreloc/libc.so.6+0xda59b
2021-11-26 18:02:54,399 INFO exited: scylla (terminated by SIGSEGV; not expected)
2021-11-26 18:02:55,407 INFO spawned: 'scylla' with pid 1789
```

**Comment by yaronkaikov** [comment] 2021-11-29 20:17
@cjbottaro our latest nightly docker image support both `arm` and `x86` - `docker pull scylladb/scylla-nightly:4.7.dev-0.20211129.1e2ecd282`

**Comment by slivne** [comment] 2021-11-30 07:30
@yaronkaikov - 4.6 supports arm - once we have 4.6.rcX out - please update this info here - it will be more stable then nightly.

**Comment by slivne** [comment] 2022-01-14 20:31
4.6.rc2 is already out - you can use it - it should have support for ARM out of the box

**Comment by rueian** [comment] 2022-01-26 14:26
Hi @slivne, It seems that the 4.6.rc2 image on dockerbuild is not built for ARM.

**Comment by dewey** [comment] 2022-01-26 14:37
I also didn't have luck getting 4.6.rc2 to run. I thought it's something on my end but maybe not after all.

**Comment by rueian** [comment] 2022-01-26 14:40
The `scylladb/scylla:4.6.dev-0.20210802.0eb2eb1b4` image successfully run on my M1, but `4.6.rc2` doesn't.

**Comment by dewey** [comment] 2022-01-26 15:01
I can confirm that `:4.6.dev-0.20210801.3089558f8` works for me but `4.6.rc2` doesn't.

**Comment by cjbottaro** [comment] 2022-02-09 05:04
`4.6.rc5` doesn't work for me either. Just looking at the image on Docker Hub, it looks to not be a multi arch build, but amd64 only...
![](https://storage.cjbotta.ro/2022-02-08-23-02-00.png)

**Comment by slivne** [comment] 2022-02-09 06:20
@Yaron Kaikov ***@***.***> ?

**Comment by tzach** [comment] 2022-02-09 07:06
AWS offer M1 instances so we can automate this test
https://aws.amazon.com/about-aws/whats-new/2021/12/amazon-ec2-m1-mac-instances-macos/

**Comment by avikivity** [comment] 2022-02-09 07:41
Why do you need M1 instances?

**Comment by yaronkaikov** [comment] 2022-02-09 09:52
> `4.6.rc5` doesn't work for me either. Just looking at the image on Docker Hub, it looks to not be a multi arch build, but amd64 only... ![](https://camo.githubusercontent.com/2039123c6ae20d6ac8e0a7a9ad427817560b4107a3c83894d1110d2b2d11322a/68747470733a2f2f73746f726167652e636a626f7474612e726f2f323032322d30322d30382d32332d30322d30302e706e67)

@cjbottaro 4.6.rc5 should work now, fixed i manually. 

```
[yaronkaikov@london]~/git/scylla-pkg (branch-4.6)$ podman manifest inspect docker.io/scylladb/scylla:4.6.rc5
{
    "schemaVersion": 2,
    "mediaType": "application/vnd.docker.distribution.manifest.list.v2+json",
    "manifests": [
        {
            "mediaType": "application/vnd.oci.image.manifest.v1+json",
            "size": 708,
            "digest": "sha256:7bdc96fa130a555e0d7c14120239b278d025dae4a7eac3260f6411b65a247fd2",
            "platform": {
                "architecture": "arm64",
                "os": "linux"
            }
        },
        {
            "mediaType": "application/vnd.oci.image.manifest.v1+json",
            "size": 708,
            "digest": "sha256:67293806504e33cbf637d503f92021f5c13a0362234ec34141a2e6367382c392",
            "platform": {
                "architecture": "amd64",
                "os": "linux"
            }
        }
    ]
}
```

@slivne I am opening this issue, and will send a patch with a proper fix

**Comment by dewey** [comment] 2022-02-22 09:57
@yaronkaikov I this closed because of this commit? https://github.com/scylladb/scylla/commit/23bb0761bfa34eddcd2367d18f75fa883cdda840

Will this be affecting the upcoming 4.6.rc6 or what's the Arm compatible image to use at the moment?

**Comment by yaronkaikov** [comment] 2022-02-22 09:59
@dewey This commit is not related to this issue. The related commit just got merged and will probably be fixed in master by tomorrow. currently 4.6.rc5 is working and should also work for later releases

let's leave it open until i will verify the solution is fixed in nightly

**Comment by yaronkaikov** [comment] 2022-02-24 12:46
Fixed in https://github.com/scylladb/scylla-pkg/pull/2745

**Closed by yaronkaikov** 2022-02-24 12:46 UTC

**Comment by basicobject** [comment] 2022-03-03 07:18
> Fixed in https://github.com/scylladb/scylla-pkg/pull/2745

I think the link is this one ? https://github.com/scylladb/scylla/pull/2745

Tried the 4.6.rc5 but didn't work for me but scylladb/scylla:4.6.dev-0.20210802.0eb2eb1b4 is working fine for me

**Comment by yaronkaikov** [comment] 2022-03-03 07:42
@basicobject Can you please verify if scylla-nightly:5.1.dev-0.20220303.3b5ba5c1a998 is working for you ?

**Comment by zllak** [comment] 2023-02-27 14:09
For users on Apple M1, I have successfully made it work by deleting all of my scylladb/scylla images, then running `docker run --platform linux/arm64/v8 --name some-scylla --hostname some-scylla -ti scylladb/scylla:latest`. It seems that otherwise, the wrong image gets pulled.
Hope that helps.

**Comment by avikivity** [comment] 2023-02-27 14:21
That's really odd. I compared the platform information between the Ubuntu images and the scylladb image, and they appear the same.
