### ISSUE TITLE
smp_affinity: No such file or directory

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#2804] opened 2017-09-14 09:59 UTC
*Installation details*
Scylla version (or git commit hash): 1.7.4
Cluster size: 1
OS (RHEL/CentOS/Ubuntu/AWS AMI): g1-small (1 vCPU, 1.7 GB memory), Ubunut 16

after scylla_setup, I see the following error in the log

```
/usr/lib/scylla/posix_net_conf.sh: line 33: /proc/irq///smp_affinity: No such file or directory
```

full scylla_setup run:
```
$ sudo scylla_setup
Skip any of the following steps by answering 'no'
Do you want to run kernel version check?
Answer yes to have this script verify that the currently installed kernel is qualified to run Scylla; answer no to skip this check.
[YES/no]
This is a supported kernel version.
Do you want to verify ScyllaDB packages installed?
Answer yes to have this script check that ScyllaDB is already installed; answer no to skip this check.
[YES/no]
Do you want to enable ScyllaDB services?
Answer yes to automatically start Scylla when the node boots; answer no to skip this step.
[YES/no]
Created symlink from /etc/systemd/system/multi-user.target.wants/scylla-server.service to /lib/systemd/system/scylla-server.service.
Synchronizing state of collectd.service with SysV init with /lib/systemd/systemd-sysv-install...
Executing /lib/systemd/systemd-sysv-install enable collectd
A new version was found, current version=1.7.4-0.20170726.ff643e3 latest version=1.7.2
Do you want to disable SELinux?
Answer yes to disable SELinux and improve performance; answer no to keep it activated.
[YES/no]
Do you want to setup bootloader options?
Answer yes to enable hugepages at boot time and improve performance. Answer no to skip this step.
[YES/no]
Generating grub configuration file ...
Found linux image: /boot/vmlinuz-4.10.0-32-generic
Found initrd image: /boot/initrd.img-4.10.0-32-generic
done
Do you want to setup NTP?
Answer yes to enable time synchronization at boot time. This keeps time right on the node. Answer no to do nothing.
[YES/no]
Reading package lists... Done
Building dependency tree       
Reading state information... Done
ntp is already the newest version (1:4.2.8p4+dfsg-3ubuntu5.6).
ntp set to manually installed.
The following NEW packages will be installed:
  ntpdate
0 upgraded, 1 newly installed, 0 to remove and 21 not upgraded.
Need to get 48.6 kB of archives.
After this operation, 173 kB of additional disk space will be used.
Get:1 http://us-east1.gce.archive.ubuntu.com/ubuntu xenial-updates/main amd64 ntpdate amd64 1:4.2.8p4+dfsg-3ubuntu5.6 [48.6 kB]
Fetched 48.6 kB in 0s (1,309 kB/s)  
Selecting previously unselected package ntpdate.
(Reading database ... 80999 files and directories currently installed.)
Preparing to unpack .../ntpdate_1%3a4.2.8p4+dfsg-3ubuntu5.6_amd64.deb ...
Unpacking ntpdate (1:4.2.8p4+dfsg-3ubuntu5.6) ...
Processing triggers for man-db (2.7.5-1) ...
Setting up ntpdate (1:4.2.8p4+dfsg-3ubuntu5.6) ...
14 Sep 09:17:16 ntpdate[10116]: adjust time server 169.254.169.254 offset -0.000042 sec
Do you want to setup RAID and XFS?
It is recommended to use RAID0 and XFS for Scylla data. If you select yes, you will be prompt to choose which unmounted disks to use for Scylla data. Selected disks will be formatted in the process.
[YES/no]
No free disks detected, abort RAID/XFS setup.

Do you want to setup coredump?
Answer yes to enable core dumps; this allows to do post-mortem analysis of Scylla state after a crash. Answer no to do nothing.
[YES/no]
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  libdw1
The following packages will be REMOVED:
  apport
The following NEW packages will be installed:
  libdw1 systemd-coredump
0 upgraded, 2 newly installed, 1 to remove and 21 not upgraded.
Need to get 298 kB of archives.
After this operation, 348 kB of additional disk space will be used.
Get:1 http://us-east1.gce.archive.ubuntu.com/ubuntu xenial/main amd64 libdw1 amd64 0.165-3ubuntu1 [191 kB]
Get:2 http://us-east1.gce.archive.ubuntu.com/ubuntu xenial-updates/universe amd64 systemd-coredump amd64 229-4ubuntu19 [107 kB]
Fetched 298 kB in 0s (1,111 kB/s)          
(Reading database ... 81013 files and directories currently installed.)
Removing apport (2.20.1-0ubuntu2.10) ...
Processing triggers for man-db (2.7.5-1) ...
Processing triggers for hicolor-icon-theme (0.15-0ubuntu1) ...
Selecting previously unselected package libdw1:amd64.
(Reading database ... 80938 files and directories currently installed.)
Preparing to unpack .../libdw1_0.165-3ubuntu1_amd64.deb ...
Unpacking libdw1:amd64 (0.165-3ubuntu1) ...
Selecting previously unselected package systemd-coredump.
Preparing to unpack .../systemd-coredump_229-4ubuntu19_amd64.deb ...
Unpacking systemd-coredump (229-4ubuntu19) ...
Processing triggers for libc-bin (2.23-0ubuntu9) ...
Processing triggers for man-db (2.7.5-1) ...
Setting up libdw1:amd64 (0.165-3ubuntu1) ...
Setting up systemd-coredump (229-4ubuntu19) ...
Processing triggers for libc-bin (2.23-0ubuntu9) ...
kernel.core_pattern = |/lib/systemd/systemd-coredump %P %u %g %s %t 9223372036854775808 %e
Do you want to setup sysconfig?
Answer yes to do system wide configuration customized for Scylla. Answer no to do nothing.
[YES/no]
Do you want to optimize NIC queue settings?
Answer yes to enable network card optimization and improve performance. Answer no to skip this optimization.
[YES/no]
Setting parameters on /etc/default/scylla-server
Do you want to setup IO configuration?
Answer yes to let iotune study what are your disks IO profile and adapt Scylla to it. Answer no to skip this action.
[YES/no]
Generating evaluation file sized 10GB... timed out before we could write the entire file. Will continue but accuracy may suffer.
4.91614GB written in 144 seconds
Refining search for maximum. So far, 244 IOPS
Maximum throughput: 244 IOPS
IOtune timed out before it could finish. An estimate will be provided but accuracy may suffer
Recommended --max-io-requests: 45
Written the above values to /etc/scylla.d/io.conf
Do you want to install node exporter and export Prometheus data from the node?
Answer yes to install it; answer no to skip this installation.
[YES/no]
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   628    0   628    0     0   1427      0 --:--:-- --:--:-- --:--:--  1427
100 3925k  100 3925k    0     0  3574k      0  0:00:01  0:00:01 --:--:-- 3574k
node_exporter-0.14.0.linux-amd64/
node_exporter-0.14.0.linux-amd64/LICENSE
node_exporter-0.14.0.linux-amd64/NOTICE
node_exporter-0.14.0.linux-amd64/node_exporter
Created symlink from /etc/systemd/system/multi-user.target.wants/node-exporter.service to /lib/systemd/system/node-exporter.service.
node_exporter successfully installed
Do you want to setup CPU scalling governor?
Answer yes to set CPU scalling governor to performance at boot time. Answer no to do nothing.
[YES/no]
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  libcpufreq0
The following NEW packages will be installed:
  cpufrequtils libcpufreq0
0 upgraded, 2 newly installed, 0 to remove and 21 not upgraded.
Need to get 52.9 kB of archives.
After this operation, 300 kB of additional disk space will be used.
Get:1 http://us-east1.gce.archive.ubuntu.com/ubuntu xenial/universe amd64 libcpufreq0 amd64 008-1 [13.7 kB]
Get:2 http://us-east1.gce.archive.ubuntu.com/ubuntu xenial/universe amd64 cpufrequtils amd64 008-1 [39.2 kB]
Fetched 52.9 kB in 0s (147 kB/s)         
Preconfiguring packages ...
Selecting previously unselected package libcpufreq0.
(Reading database ... 80991 files and directories currently installed.)
Preparing to unpack .../libcpufreq0_008-1_amd64.deb ...
Unpacking libcpufreq0 (008-1) ...
Selecting previously unselected package cpufrequtils.
Preparing to unpack .../cpufrequtils_008-1_amd64.deb ...
Unpacking cpufrequtils (008-1) ...
Processing triggers for man-db (2.7.5-1) ...
Processing triggers for systemd (229-4ubuntu19) ...
Processing triggers for ureadahead (0.100.0-19) ...
Setting up libcpufreq0 (008-1) ...
Setting up cpufrequtils (008-1) ...
update-rc.d: warning: start and stop actions are no longer supported; falling back to defaults
update-rc.d: warning: start and stop actions are no longer supported; falling back to defaults
Processing triggers for libc-bin (2.23-0ubuntu9) ...
Processing triggers for systemd (229-4ubuntu19) ...
Processing triggers for ureadahead (0.100.0-19) ...
cpufrequtils.service is not a native service, redirecting to systemd-sysv-install
Executing /lib/systemd/systemd-sysv-install enable cpufrequtils
ScyllaDB setup finished.
Please restart machine before using ScyllaDB, since you have changed 
boot parameters.
tzach@tzachinstance-1-test:~$ sudo init 6
```

**Comment by tzach** [comment] 2017-09-26 11:45
@syuu1228 ?

**Comment by slivne** [comment] 2018-04-23 20:28
@roydahan we had a fix in 1.7 - but since then we have moved code from posix_net_conf.sh to perftune.py  need to retest and see if this is not resolved

**Comment by tzach** [comment] 2018-04-26 09:33
@roydahan can you please validate the fix?

**Comment by avikivity** [comment] 2018-04-26 09:41
Fixed in 1.7 by f6f91a49cb8beef9dd9078696d84cb3922ada645

**Closed by avikivity** 2018-04-26 09:41 UTC
Labels: bug, onboarding

**Comment by amoskong** [comment] 2018-05-09 08:34
Can't reproduce on both 1.7 & 2.2

**Comment by amoskong** [comment] 2018-05-09 08:52
Strictly, we should check if the configure file exists before writing.

* 1.7
```
diff --git a/scripts/posix_net_conf.sh b/scripts/posix_net_conf.sh
index 164aeedc..d22ce9d8 100755
--- a/scripts/posix_net_conf.sh
+++ b/scripts/posix_net_conf.sh
@@ -284,6 +284,7 @@ setup_one_hw_iface()
         for irq in `get_irqs $iface`
         do
             echo "Binding IRQ $irq to CPU0"
+            test -e /proc/irq/$irq/smp_affinity || exit 1
             echo 1 > /proc/irq/$irq/smp_affinity
         done
 
```

* 2.2/master:
```
diff --git a/scripts/perftune.py b/scripts/perftune.py
index 0a8bfbc6..813c921f 100755
--- a/scripts/perftune.py
+++ b/scripts/perftune.py
@@ -57,6 +57,7 @@ def set_one_mask(conf_file, mask):
         mask = double_commas_pattern.sub(',0,', mask)
 
     print("Setting mask {} in {}".format(mask, conf_file))
+    assert os.path.exists(config_file)
     fwriteln(conf_file, mask)
 
 def distribute_irqs(irqs, cpu_mask):
```
