### ISSUE TITLE
init - Startup failed: std::runtime_error (Could not find tokens for 10.0.0.155 to replace) during large-partition-4d test

### ISSUE THREAD

**Issue by aleksbykov** [scylladb/scylla#7166] opened 2020-09-04 11:25 UTC
*Installation details*
Scylla version (or git commit hash): Scylla version 4.2.rc3-0.20200825.989d8fe63 with build-id e7d653bede6105c8264984a606cd5334967ca553
Cluster size: 4 nodes
OS (RHEL/CentOS/Ubuntu/AWS AMI): ami-0637c7ab2b923d84e(en-central-1)

*Hardware details (for performance issues)*          Delete if unneeded
Platform (physical/VM/cloud instance type/docker): AWS
instance type: i3en.3xlarge 

During job [longevity-large-partition-4d](https://jenkins.scylladb.com/view/scylla-4.2/job/scylla-4.2/job/longevity/job/longevity-large-partition-4days-test/5/) Scylla on node4 during nemesis: RestartThenRepairNode failed to start with error:
```
2020-09-01T23:02:55+00:00  longevity-large-partitions-4d-4-2-db-node-7a748b66-6 !ERR     | scylla: [shard 0] init - Startup failed: std::runtime_error (Could not find tokens for 10.0.0.155 to replace)
```
It is similar to issue https://github.com/scylladb/scylla/issues/6648

Next nemesises(actions) were run before failed RestartThenRepairNode nemesis:
```
2020-09-01 14:44:19.768: (DisruptionEvent Severity.NORMAL): type=start name=NoCorruptRepair node=Node longevity-large-partitions-4d-4-2-db-node-7a748b66-3 [3.120.147.241 | 10.0.2.223] (seed: False) duration=None
2020-09-01 15:11:26.153: (DisruptionEvent Severity.NORMAL): type=end name=NoCorruptRepair node=Node longevity-large-partitions-4d-4-2-db-node-7a748b66-3 [3.120.147.241 | 10.0.2.223] (seed: False) duration=1626
2020-09-01 15:41:47.367: (DisruptionEvent Severity.NORMAL): type=start name=ManagementRepair node=Node longevity-large-partitions-4d-4-2-db-node-7a748b66-2 [3.120.179.232 | 10.0.3.165] (seed: False) duration=None
2020-09-01 16:42:38.294: (DisruptionEvent Severity.NORMAL): type=end name=ManagementRepair node=Node longevity-large-partitions-4d-4-2-db-node-7a748b66-2 [3.120.179.232 | 10.0.3.165] (seed: False) duration=3650
2020-09-01 17:12:59.488: (DisruptionEvent Severity.NORMAL): type=start name=ManagementBackup node=Node longevity-large-partitions-4d-4-2-db-node-7a748b66-3 [3.120.147.241 | 10.0.2.223] (seed: False) duration=None
2020-09-01 17:12:59.875: (DisruptionEvent Severity.NORMAL): type=skipped name=ManagementBackup node=Node longevity-large-partitions-4d-4-2-db-node-7a748b66-3 [3.120.147.241 | 10.0.2.223] (seed: False) duration=0
2020-09-01 17:13:21.040: (DisruptionEvent Severity.NORMAL): type=start name=StopStartNetworkInterfaces node=Node longevity-large-partitions-4d-4-2-db-node-7a748b66-2 [3.120.179.232 | 10.0.3.165] (seed: False) duration=None
2020-09-01 17:13:21.152: (DisruptionEvent Severity.NORMAL): type=skipped name=StopStartNetworkInterfaces node=Node longevity-large-partitions-4d-4-2-db-node-7a748b66-2 [3.120.179.232 | 10.0.3.165] (seed: False) duration=0
2020-09-01 17:13:42.729: (DisruptionEvent Severity.NORMAL): type=skipped name=ChaosMonkey node=Node longevity-large-partitions-4d-4-2-db-node-7a748b66-2 [3.120.179.232 | 10.0.3.165] (seed: False) duration=0
2020-09-01 17:14:04.230: (DisruptionEvent Severity.NORMAL): type=skipped name=ChaosMonkey node=Node longevity-large-partitions-4d-4-2-db-node-7a748b66-3 [3.120.147.241 | 10.0.2.223] (seed: False) duration=0
2020-09-01 17:14:24.987: (DisruptionEvent Severity.NORMAL): type=start name=StopStartService node=Node longevity-large-partitions-4d-4-2-db-node-7a748b66-4 [35.157.72.19 | 10.0.1.37] (seed: False) duration=None
2020-09-01 17:16:38.435: (DisruptionEvent Severity.NORMAL): type=end name=StopStartService node=Node longevity-large-partitions-4d-4-2-db-node-7a748b66-4 [35.157.72.19 | 10.0.1.37] (seed: False) duration=133
2020-09-01 17:47:00.168: (DisruptionEvent Severity.NORMAL): type=skipped name=ChaosMonkey node=Node longevity-large-partitions-4d-4-2-db-node-7a748b66-2 [3.120.179.232 | 10.0.3.165] (seed: False) duration=0
2020-09-01 17:47:21.152: (DisruptionEvent Severity.NORMAL): type=start name=GrowCluster node=Node longevity-large-partitions-4d-4-2-db-node-7a748b66-2 [3.120.179.232 | 10.0.3.165] (seed: False) duration=None
2020-09-01 18:34:54.239: (DisruptionEvent Severity.NORMAL): type=start name=ShrinkCLuster node=Node longevity-large-partitions-4d-4-2-db-node-7a748b66-2 [3.120.179.232 | 10.0.3.165] (seed: False) duration=None
2020-09-01 18:51:37.990: (DisruptionEvent Severity.NORMAL): type=end name=ShrinkCLuster node=Node longevity-large-partitions-4d-4-2-db-node-7a748b66-2 [3.120.179.232 | 10.0.3.165] (seed: False) duration=3856
2020-09-01 19:22:03.738: (DisruptionEvent Severity.NORMAL): type=skipped name=ChaosMonkey node=Node longevity-large-partitions-4d-4-2-db-node-7a748b66-3 [3.120.147.241 | 10.0.2.223] (seed: False) duration=0
2020-09-01 19:22:23.712: (DisruptionEvent Severity.NORMAL): type=start name=RepairStreamingErr node=Node longevity-large-partitions-4d-4-2-db-node-7a748b66-5 [18.185.113.189 | 10.0.0.204] (seed: False) duration=None
2020-09-01 20:02:36.563: (DisruptionEvent Severity.NORMAL): type=end name=RepairStreamingErr node=Node longevity-large-partitions-4d-4-2-db-node-7a748b66-5 [18.185.113.189 | 10.0.0.204] (seed: False) duration=2412
2020-09-01 20:32:56.824: (DisruptionEvent Severity.NORMAL): type=start name=GrowCluster node=Node longevity-large-partitions-4d-4-2-db-node-7a748b66-2 [3.120.179.232 | 10.0.3.165] (seed: False) duration=None
2020-09-01 21:23:34.469: (DisruptionEvent Severity.NORMAL): type=start name=ShrinkCLuster node=Node longevity-large-partitions-4d-4-2-db-node-7a748b66-2 [3.120.179.232 | 10.0.3.165] (seed: False) duration=None
2020-09-01 21:54:39.441: (DisruptionEvent Severity.NORMAL): type=end name=ShrinkCLuster node=Node longevity-large-partitions-4d-4-2-db-node-7a748b66-2 [3.120.179.232 | 10.0.3.165] (seed: False) duration=4902
2020-09-01 22:25:01.944: (DisruptionEvent Severity.NORMAL): type=start name=Refresh node=Node longevity-large-partitions-4d-4-2-db-node-7a748b66-6 [18.197.174.194 | 10.0.0.155] (seed: False) duration=None
2020-09-01 22:26:48.922: (DisruptionEvent Severity.NORMAL): type=end name=Refresh node=Node longevity-large-partitions-4d-4-2-db-node-7a748b66-6 [18.197.174.194 | 10.0.0.155] (seed: False) duration=106
```
The nemesis RestartThenRepairNode stop instance. When using storage optimized instances like i2 or i3, the data on disk is deleted upon STOP. therefore, we need to setup the instance and treat it as a new instance.
After instance was started new data disk was created and scylla is going to be started:
```
< t:2020-09-01 23:02:52,641 f:base.py         l:107  c:RemoteCmdRunner      p:DEBUG > Command "sudo /opt/scylladb/scylla-machine-image/scylla_create_devices" finished with status 0
< t:2020-09-01 23:02:52,641 f:remote_base.py  l:519  c:RemoteCmdRunner      p:DEBUG > Running command "sudo systemctl start scylla-server.service"...
```
But it failed with error:
```
2020-09-01T23:02:54+00:00  longevity-large-partitions-4d-4-2-db-node-7a748b66-6 !INFO    | scylla: [shard 0] storage_service - Checking remote features with gossip
2020-09-01T23:02:54+00:00  longevity-large-partitions-4d-4-2-db-node-7a748b66-6 !INFO    | scylla: [shard 0] messaging_service - Starting Messaging Service on port 7000
2020-09-01T23:02:54+00:00  longevity-large-partitions-4d-4-2-db-node-7a748b66-6 !INFO    | scylla-jmx: Picked up JAVA_TOOL_OPTIONS:
2020-09-01T23:02:54+00:00  longevity-large-partitions-4d-4-2-db-node-7a748b66-6 !NOTICE  | sudo:  centos : TTY=unknown ; PWD=/home/centos ; USER=root ; COMMAND=/bin/sed -i -e s/^replace_address_first_boot:/# replace_address_first_boot:/g /etc/scylla/scylla.yaml
2020-09-01T23:02:54+00:00  longevity-large-partitions-4d-4-2-db-node-7a748b66-6 !INFO    | sudo: pam_unix(sudo:session): session opened for user root by (uid=0)
2020-09-01T23:02:54+00:00  longevity-large-partitions-4d-4-2-db-node-7a748b66-6 !INFO    | sudo: pam_unix(sudo:session): session closed for user root
2020-09-01T23:02:54+00:00  longevity-large-partitions-4d-4-2-db-node-7a748b66-6 !INFO    | scylla: [shard 4] compaction - Compacted 4 sstables to [/var/lib/scylla/data/system/local-7ad54392bcdd35a684174e047860b377/mc-64-big-Data.db:level=0, ]. 24kB to 6kB (~28% of original) in 59ms = 116kB/s. ~512 total partitions merged to 1.
2020-09-01T23:02:54+00:00  longevity-large-partitions-4d-4-2-db-node-7a748b66-6 !NOTICE  | sudo:  centos : TTY=unknown ; PWD=/home/centos ; USER=root ; COMMAND=/bin/sed -e /auto_bootstrap:.*/s/true/false/g -i /etc/scylla/scylla.yaml
2020-09-01T23:02:54+00:00  longevity-large-partitions-4d-4-2-db-node-7a748b66-6 !INFO    | sudo: pam_unix(sudo:session): session opened for user root by (uid=0)
2020-09-01T23:02:54+00:00  longevity-large-partitions-4d-4-2-db-node-7a748b66-6 !INFO    | sudo: pam_unix(sudo:session): session closed for user root
2020-09-01T23:02:54+00:00  longevity-large-partitions-4d-4-2-db-node-7a748b66-6 !INFO    | scylla-jmx: Using config file: /etc/scylla/scylla.yaml
2020-09-01T23:02:54+00:00  longevity-large-partitions-4d-4-2-db-node-7a748b66-6 !INFO    | scylla-jmx: Connecting to http://127.0.0.1:10000
2020-09-01T23:02:54+00:00  longevity-large-partitions-4d-4-2-db-node-7a748b66-6 !INFO    | scylla-jmx: Starting the JMX server
2020-09-01T23:02:55+00:00  longevity-large-partitions-4d-4-2-db-node-7a748b66-6 !INFO    | scylla-jmx: JMX is enabled to receive remote connections on port: 7199
2020-09-01T23:02:55+00:00  longevity-large-partitions-4d-4-2-db-node-7a748b66-6 !INFO    | scylla: [shard 0] gossip - Feature check passed. Local node 10.0.0.155 features = {CDC, COMPUTED_COLUMNS, CORRECT_COUNTER_ORDER, CORRECT_NON_COMPOUND_RANGE_TOMBSTONES, CORRECT_STATIC_COMPACT_IN_MC, COUNTERS, DIGEST_INSENSITIVE_TO_EXPIRY, DIGEST_MULTIPARTITION_READ, HINTED_HANDOFF_SEPARATE_CONNECTION, INDEXES, LARGE_PARTITIONS, LA_SSTABLE_FORMAT, LWT, MATERIALIZED_VIEWS, MC_SSTABLE_FORMAT, NONFROZEN_UDTS, PER_TABLE_CACHING, PER_TABLE_PARTITIONERS, RANGE_TOMBSTONES, ROLES, ROW_LEVEL_REPAIR, SCHEMA_TABLES_V3, STREAM_WITH_RPC_STREAM, TRUNCATION_TABLE, UNBOUNDED_RANGE_TOMBSTONES, VIEW_VIRTUAL_COLUMNS, WRITE_FAILURE_REPLY, XXHASH}, Remote common_features = {CDC, COMPUTED_COLUMNS, CORRECT_COUNTER_ORDER, CORRECT_NON_COMPOUND_RANGE_TOMBSTONES, CORRECT_STATIC_COMPACT_IN_MC, COUNTERS, DIGEST_INSENSITIVE_TO_EXPIRY, DIGEST_MULTIPARTITION_READ, HINTED_HANDOFF_SEPARATE_CONNECTION, INDEXES, LARGE_PARTITIONS, LA_SSTABLE_FORMAT, LWT, MATERIALIZED_VIEWS, MC_SSTABLE_FORMAT, NONFROZEN_UDTS, PER_TABLE_CACHING, PER_TABLE_PARTITIONERS, RANGE_TOMBSTONES, ROLES, ROW_LEVEL_REPAIR, SCHEMA_TABLES_V3, STREAM_WITH_RPC_STREAM, TRUNCATION_TABLE, UNBOUNDED_RANGE_TOMBSTONES, VIEW_VIRTUAL_COLUMNS, WRITE_FAILURE_REPLY, XXHASH}
2020-09-01T23:02:55+00:00  longevity-large-partitions-4d-4-2-db-node-7a748b66-6 !INFO    | scylla: [shard 0] init - Shutting down gossiping
2020-09-01T23:02:55+00:00  longevity-large-partitions-4d-4-2-db-node-7a748b66-6 !INFO    | scylla: [shard 0] gossip - gossip is already stopped
2020-09-01T23:02:55+00:00  longevity-large-partitions-4d-4-2-db-node-7a748b66-6 !INFO    | scylla: [shard 0] init - Shutting down gossiping was successful
2020-09-01T23:02:55+00:00  longevity-large-partitions-4d-4-2-db-node-7a748b66-6 !INFO    | scylla: [shard 0] init - Shutting down storage service notifications
2020-09-01T23:02:55+00:00  longevity-large-partitions-4d-4-2-db-node-7a748b66-6 !INFO    | scylla: [shard 0] init - Shutting down storage service notifications was successful
2020-09-01T23:02:55+00:00  longevity-large-partitions-4d-4-2-db-node-7a748b66-6 !INFO    | scylla: [shard 0] init - Shutting down repair service
2020-09-01T23:02:55+00:00  longevity-large-partitions-4d-4-2-db-node-7a748b66-6 !INFO    | scylla: [shard 0] init - Shutting down repair service was successful
2020-09-01T23:02:55+00:00  longevity-large-partitions-4d-4-2-db-node-7a748b66-6 !INFO    | scylla: [shard 0] init - Shutting down cdc
2020-09-01T23:02:55+00:00  longevity-large-partitions-4d-4-2-db-node-7a748b66-6 !INFO    | scylla: [shard 0] init - Shutting down cdc was successful
2020-09-01T23:02:55+00:00  longevity-large-partitions-4d-4-2-db-node-7a748b66-6 !INFO    | scylla: [shard 0] init - Shutting down sstables format selector
2020-09-01T23:02:55+00:00  longevity-large-partitions-4d-4-2-db-node-7a748b66-6 !INFO    | scylla: [shard 0] init - Shutting down sstables format selector was successful
2020-09-01T23:02:55+00:00  longevity-large-partitions-4d-4-2-db-node-7a748b66-6 !INFO    | scylla: [shard 0] init - Shutting down migration manager
2020-09-01T23:02:55+00:00  longevity-large-partitions-4d-4-2-db-node-7a748b66-6 !INFO    | scylla: [shard 0] migration_manager - stopping migration service
2020-09-01T23:02:55+00:00  longevity-large-partitions-4d-4-2-db-node-7a748b66-6 !INFO    | scylla: [shard 1] migration_manager - stopping migration service
2020-09-01T23:02:55+00:00  longevity-large-partitions-4d-4-2-db-node-7a748b66-6 !INFO    | scylla: [shard 7] migration_manager - stopping migration service
2020-09-01T23:02:55+00:00  longevity-large-partitions-4d-4-2-db-node-7a748b66-6 !INFO    | scylla: [shard 11] migration_manager - stopping migration service
2020-09-01T23:02:55+00:00  longevity-large-partitions-4d-4-2-db-node-7a748b66-6 !INFO    | scylla: [shard 4] migration_manager - stopping migration service
2020-09-01T23:02:55+00:00  longevity-large-partitions-4d-4-2-db-node-7a748b66-6 !INFO    | scylla: [shard 9] migration_manager - stopping migration service
2020-09-01T23:02:55+00:00  longevity-large-partitions-4d-4-2-db-node-7a748b66-6 !INFO    | scylla: [shard 5] migration_manager - stopping migration service
2020-09-01T23:02:55+00:00  longevity-large-partitions-4d-4-2-db-node-7a748b66-6 !INFO    | scylla: [shard 6] migration_manager - stopping migration service
2020-09-01T23:02:55+00:00  longevity-large-partitions-4d-4-2-db-node-7a748b66-6 !INFO    | scylla: [shard 10] migration_manager - stopping migration service
2020-09-01T23:02:55+00:00  longevity-large-partitions-4d-4-2-db-node-7a748b66-6 !INFO    | scylla: [shard 8] migration_manager - stopping migration service
2020-09-01T23:02:55+00:00  longevity-large-partitions-4d-4-2-db-node-7a748b66-6 !INFO    | scylla: [shard 3] migration_manager - stopping migration service
2020-09-01T23:02:55+00:00  longevity-large-partitions-4d-4-2-db-node-7a748b66-6 !INFO    | scylla: [shard 2] migration_manager - stopping migration service
2020-09-01T23:02:55+00:00  longevity-large-partitions-4d-4-2-db-node-7a748b66-6 !INFO    | scylla: [shard 0] init - Shutting down migration manager was successful
2020-09-01T23:02:55+00:00  longevity-large-partitions-4d-4-2-db-node-7a748b66-6 !INFO    | scylla: [shard 0] init - Shutting down database
2020-09-01T23:02:55+00:00  longevity-large-partitions-4d-4-2-db-node-7a748b66-6 !INFO    | scylla: [shard 0] compaction_manager - Asked to stop
2020-09-01T23:02:55+00:00  longevity-large-partitions-4d-4-2-db-node-7a748b66-6 !INFO    | scylla: [shard 0] compaction_manager - Stopping 0 ongoing compactions
2020-09-01T23:02:55+00:00  longevity-large-partitions-4d-4-2-db-node-7a748b66-6 !INFO    | scylla: [shard 0] compaction_manager - Stopped
2020-09-01T23:02:55+00:00  longevity-large-partitions-4d-4-2-db-node-7a748b66-6 !INFO    | scylla: [shard 1] compaction_manager - Asked to stop
2020-09-01T23:02:55+00:00  longevity-large-partitions-4d-4-2-db-node-7a748b66-6 !INFO    | scylla: [shard 3] compaction_manager - Asked to stop
2020-09-01T23:02:55+00:00  longevity-large-partitions-4d-4-2-db-node-7a748b66-6 !INFO    | scylla: [shard 4] compaction_manager - Asked to stop
2020-09-01T23:02:55+00:00  longevity-large-partitions-4d-4-2-db-node-7a748b66-6 !INFO    | scylla: [shard 10] compaction_manager - Asked to stop
2020-09-01T23:02:55+00:00  longevity-large-partitions-4d-4-2-db-node-7a748b66-6 !INFO    | scylla: [shard 7] compaction_manager - Asked to stop
2020-09-01T23:02:55+00:00  longevity-large-partitions-4d-4-2-db-node-7a748b66-6 !INFO    | scylla: [shard 8] compaction_manager - Asked to stop
2020-09-01T23:02:55+00:00  longevity-large-partitions-4d-4-2-db-node-7a748b66-6 !INFO    | scylla: [shard 6] compaction_manager - Asked to stop
2020-09-01T23:02:55+00:00  longevity-large-partitions-4d-4-2-db-node-7a748b66-6 !INFO    | scylla: [shard 3] compaction_manager - Stopping 0 ongoing compactions
2020-09-01T23:02:55+00:00  longevity-large-partitions-4d-4-2-db-node-7a748b66-6 !INFO    | scylla: [shard 1] compaction_manager - Stopping 0 ongoing compactions
2020-09-01T23:02:55+00:00  longevity-large-partitions-4d-4-2-db-node-7a748b66-6 !INFO    | scylla: [shard 9] compaction_manager - Asked to stop
2020-09-01T23:02:55+00:00  longevity-large-partitions-4d-4-2-db-node-7a748b66-6 !INFO    | scylla: [shard 4] compaction_manager - Stopping 0 ongoing compactions
2020-09-01T23:02:55+00:00  longevity-large-partitions-4d-4-2-db-node-7a748b66-6 !INFO    | scylla: [shard 5] compaction_manager - Asked to stop
2020-09-01T23:02:55+00:00  longevity-large-partitions-4d-4-2-db-node-7a748b66-6 !INFO    | scylla: [shard 1] compaction_manager - Stopped
2020-09-01T23:02:55+00:00  longevity-large-partitions-4d-4-2-db-node-7a748b66-6 !INFO    | scylla: [shard 8] compaction_manager - Stopping 0 ongoing compactions
2020-09-01T23:02:55+00:00  longevity-large-partitions-4d-4-2-db-node-7a748b66-6 !INFO    | scylla: [shard 4] compaction_manager - Stopped
2020-09-01T23:02:55+00:00  longevity-large-partitions-4d-4-2-db-node-7a748b66-6 !INFO    | scylla: [shard 3] compaction_manager - Stopped
2020-09-01T23:02:55+00:00  longevity-large-partitions-4d-4-2-db-node-7a748b66-6 !INFO    | scylla: [shard 10] compaction_manager - Stopping 0 ongoing compactions
2020-09-01T23:02:55+00:00  longevity-large-partitions-4d-4-2-db-node-7a748b66-6 !INFO    | scylla: [shard 8] compaction_manager - Stopped
2020-09-01T23:02:55+00:00  longevity-large-partitions-4d-4-2-db-node-7a748b66-6 !INFO    | scylla: [shard 6] compaction_manager - Stopping 0 ongoing compactions
2020-09-01T23:02:55+00:00  longevity-large-partitions-4d-4-2-db-node-7a748b66-6 !INFO    | scylla: [shard 11] compaction_manager - Asked to stop
2020-09-01T23:02:55+00:00  longevity-large-partitions-4d-4-2-db-node-7a748b66-6 !INFO    | scylla: [shard 5] compaction_manager - Stopping 0 ongoing compactions
2020-09-01T23:02:55+00:00  longevity-large-partitions-4d-4-2-db-node-7a748b66-6 !INFO    | scylla: [shard 7] compaction_manager - Stopping 0 ongoing compactions
2020-09-01T23:02:55+00:00  longevity-large-partitions-4d-4-2-db-node-7a748b66-6 !INFO    | scylla: [shard 9] compaction_manager - Stopping 0 ongoing compactions
2020-09-01T23:02:55+00:00  longevity-large-partitions-4d-4-2-db-node-7a748b66-6 !INFO    | scylla: [shard 7] compaction_manager - Stopped
2020-09-01T23:02:55+00:00  longevity-large-partitions-4d-4-2-db-node-7a748b66-6 !INFO    | scylla: [shard 5] compaction_manager - Stopped
2020-09-01T23:02:55+00:00  longevity-large-partitions-4d-4-2-db-node-7a748b66-6 !INFO    | scylla: [shard 11] compaction_manager - Stopping 0 ongoing compactions
2020-09-01T23:02:55+00:00  longevity-large-partitions-4d-4-2-db-node-7a748b66-6 !INFO    | scylla: [shard 10] compaction_manager - Stopped
2020-09-01T23:02:55+00:00  longevity-large-partitions-4d-4-2-db-node-7a748b66-6 !INFO    | scylla: [shard 6] compaction_manager - Stopped
2020-09-01T23:02:55+00:00  longevity-large-partitions-4d-4-2-db-node-7a748b66-6 !INFO    | scylla: [shard 9] compaction_manager - Stopped
2020-09-01T23:02:55+00:00  longevity-large-partitions-4d-4-2-db-node-7a748b66-6 !INFO    | scylla: [shard 11] compaction_manager - Stopped
2020-09-01T23:02:55+00:00  longevity-large-partitions-4d-4-2-db-node-7a748b66-6 !INFO    | scylla: [shard 2] compaction_manager - Asked to stop
2020-09-01T23:02:55+00:00  longevity-large-partitions-4d-4-2-db-node-7a748b66-6 !INFO    | scylla: [shard 2] compaction_manager - Stopping 0 ongoing compactions
2020-09-01T23:02:55+00:00  longevity-large-partitions-4d-4-2-db-node-7a748b66-6 !INFO    | scylla: [shard 2] compaction_manager - Stopped
2020-09-01T23:02:55+00:00  longevity-large-partitions-4d-4-2-db-node-7a748b66-6 !INFO    | scylla: [shard 0] init - Shutting down database: waiting for background jobs...
2020-09-01T23:02:55+00:00  longevity-large-partitions-4d-4-2-db-node-7a748b66-6 !INFO    | scylla: [shard 0] init - Shutting down database was successful
2020-09-01T23:02:55+00:00  longevity-large-partitions-4d-4-2-db-node-7a748b66-6 !INFO    | scylla: [shard 0] init - Shutting down migration manager notifier
2020-09-01T23:02:55+00:00  longevity-large-partitions-4d-4-2-db-node-7a748b66-6 !INFO    | scylla: [shard 0] init - Shutting down migration manager notifier was successful
2020-09-01T23:02:55+00:00  longevity-large-partitions-4d-4-2-db-node-7a748b66-6 !INFO    | scylla: [shard 0] init - Shutting down prometheus API server
2020-09-01T23:02:55+00:00  longevity-large-partitions-4d-4-2-db-node-7a748b66-6 !INFO    | scylla: [shard 0] init - Shutting down prometheus API server was successful
2020-09-01T23:02:55+00:00  longevity-large-partitions-4d-4-2-db-node-7a748b66-6 !INFO    | scylla: [shard 0] init - Shutting down sighup
2020-09-01T23:02:55+00:00  longevity-large-partitions-4d-4-2-db-node-7a748b66-6 !INFO    | scylla: [shard 0] init - Shutting down sighup was successful
2020-09-01T23:02:55+00:00  longevity-large-partitions-4d-4-2-db-node-7a748b66-6 !ERR     | scylla: [shard 0] init - Startup failed: std::runtime_error (Could not find tokens for 10.0.0.155 to replace)
```
cluster is available:
```
| longevity-large-partitions-4d-4-2-db-node-7a748b66-1      | eu-central-1a | 18.185.86.246  | 7a748b66-5622-4384-8bfb-e95b5ee67bd4
| longevity-large-partitions-4d-4-2-db-node-7a748b66-2      | eu-central-1a | 3.120.179.232  | 7a748b66-5622-4384-8bfb-e95b5ee67bd4
| longevity-large-partitions-4d-4-2-monitor-node-7a748b66-1 | eu-central-1a | 18.159.103.130 | 7a748b66-5622-4384-8bfb-e95b5ee67bd4
| longevity-large-partitions-4d-4-2-db-node-7a748b66-5      | eu-central-1a | 18.185.113.189 | 7a748b66-5622-4384-8bfb-e95b5ee67bd4
| longevity-large-partitions-4d-4-2-db-node-7a748b66-6      | eu-central-1a | 3.121.213.134  | 7a748b66-5622-4384-8bfb-e95b5ee67bd4
```

db logs: https://cloudius-jenkins-test.s3.amazonaws.com/7a748b66-5622-4384-8bfb-e95b5ee67bd4/20200902_073321/db-cluster-7a748b66.zip
node6 log: [system.log.tar.gz](https://github.com/scylladb/scylla/files/5174488/system.log.tar.gz)

**Comment by slivne** [comment] 2020-09-06 09:43
@aleksbykov just to verify is this with CDC ?

**Comment by aleksbykov** [comment] 2020-09-07 09:08
@slivne , no, it is without CDC at all. Just large partition

**Comment by asias** [comment] 2020-09-09 02:09
I saw node 6 started 3 times in the test. Node 6 was replacing itself with the same ip address.  Looks like the second boot was stopped by the sct test for some reason during boot up (why?). Second boot left gossip status for node 6 in a incomplete state (It is a theory, I will dig more). During the third boot, tokens for node6 was not present in the cluster because the failed second boot. 


```
1) First boot
2020-09-01T20:39:08+00:00  longevity-large-partitions-4d-4-2-db-node-7a748b66-6 !INFO    | scylla: Scylla version 4.2.rc3-0.20200825.989d8fe63 with build-id e7d653bede6105c8264984a606cd5334967ca553 starting ...
...

2020-09-01T22:26:48+00:00  longevity-large-partitions-4d-4-2-db-node-7a748b66-6 !INFO    | scylla: [shard 0] database - Resharded 115MB in 2.85 seconds, 40MB/s
2020-09-01T22:26:48+00:00  longevity-large-partitions-4d-4-2-db-node-7a748b66-6 !INFO    | scylla: [shard 0] database - Loaded 24 SSTables into /var/lib/scylla/data/keyspace1/standard1-fedbaa00eca111ea966a000000000007
2020-09-01T22:26:48+00:00  longevity-large-partitions-4d-4-2-db-node-7a748b66-6 !INFO    | scylla: [shard 0] storage_service - Done loading new SSTables for keyspace1.standard1
2020-09-01T22:43:06+00:00  longevity-large-partitions-4d-4-2-db-node-7a748b66-6 !ERR     | scylla: [shard 0] rpc - client 167.71.79.245:33480: server connection dropped: connection is closed
```

2) Second boot
```
2020-09-01T23:00:45+00:00  longevity-large-partitions-4d-4-2-db-node-7a748b66-6 !INFO    | scylla: Scylla version 4.2.rc3-0.20200825.989d8fe63 with build-id e7d653bede6105c8264984a606cd5334967ca553 starting ...

...

2020-09-01T23:00:57+00:00  longevity-large-partitions-4d-4-2-db-node-7a748b66-6 !ERR     | scylla: [shard 0] init - Startup failed: seastar::sleep_aborted (Sleep is aborted)
```

3) Third boot
```

2020-09-01T23:02:53+00:00  longevity-large-partitions-4d-4-2-db-node-7a748b66-6 !INFO    | scylla: Scylla version 4.2.rc3-0.20200825.989d8fe63 with build-id e7d653bede6105c8264984a606cd5334967ca553 starting ...

...

2020-09-01T23:02:55+00:00  longevity-large-partitions-4d-4-2-db-node-7a748b66-6 !ERR     | scylla: [shard 0] init - Startup failed: std::runtime_error (Could not find tokens for 10.0.0.155 to replace)
```

**Comment by slivne** [comment] 2020-09-09 05:31
@asias thanks - is this a regression ?

**Comment by asias** [comment] 2020-09-09 06:58
Yes, it is a regression introduced in commit 7d86a3b208659e92489216e71df13fb33b1a4c3a (storage_service:
    Make replacing node take writes). I will send a fix.

**Comment by asias** [comment] 2020-09-09 08:49
Patch sent: https://github.com/scylladb/scylla/pull/7202

**Comment by asias** [comment] 2020-09-10 00:29
Fixed in commit 3ba6e3d26485c508f39c064585eed48c3d88065b.

**Comment by avikivity** [comment] 2020-09-10 09:21
Backported to 4.1, 4.2.

**Comment by aleksbykov** [comment] 2020-09-14 07:57
Issue reproduced on scylla version 4.2.rc4-0.20200907.bf0c493c28 with build-id 49cc32b091e40433f7006467b50f2e6722d6074b.
On node 11 RestartThenRepairNode nemesis reproduced same issue:
```
2020-09-11T10:30:49+00:00  alternator-48h-4-2-db-node-4f0eff37-11 !INFO    | scylla: [shard 4] compaction_manager - Stopped
2020-09-11T10:30:49+00:00  alternator-48h-4-2-db-node-4f0eff37-11 !INFO    | scylla: [shard 0] init - Shutting down database: waiting for background jobs...
2020-09-11T10:30:49+00:00  alternator-48h-4-2-db-node-4f0eff37-11 !INFO    | scylla: [shard 0] init - Shutting down database was successful
2020-09-11T10:30:49+00:00  alternator-48h-4-2-db-node-4f0eff37-11 !INFO    | scylla: [shard 0] init - Shutting down migration manager notifier
2020-09-11T10:30:49+00:00  alternator-48h-4-2-db-node-4f0eff37-11 !INFO    | scylla: [shard 0] init - Shutting down migration manager notifier was successful
2020-09-11T10:30:49+00:00  alternator-48h-4-2-db-node-4f0eff37-11 !INFO    | scylla: [shard 0] init - Shutting down prometheus API server
2020-09-11T10:30:49+00:00  alternator-48h-4-2-db-node-4f0eff37-11 !INFO    | scylla: [shard 0] init - Shutting down prometheus API server was successful
2020-09-11T10:30:49+00:00  alternator-48h-4-2-db-node-4f0eff37-11 !INFO    | scylla: [shard 0] init - Shutting down sighup
2020-09-11T10:30:49+00:00  alternator-48h-4-2-db-node-4f0eff37-11 !INFO    | scylla: [shard 0] init - Shutting down sighup was successful
2020-09-11T10:30:49+00:00  alternator-48h-4-2-db-node-4f0eff37-11 !ERR     | scylla: [shard 0] init - Startup failed: std::runtime_error (Could not find tokens for 10.0.0.248 to replace)
```

[system.log.tar.gz](https://github.com/scylladb/scylla/files/5216926/system.log.tar.gz)

**Comment by slivne** [comment] 2020-09-14 10:45
4.2.rc4-0.20200907.bf0c493c28 doesn't contain the fix

it's part of 4.2 from 71cbec966b7ec3c1fbb257a15673247beeb55983

closing this issue, @aleksbykov  if you can run a version that has 71cbec966b7ec3c1fbb257a15673247beeb55983 and report it would be great

**Closed by slivne** 2020-09-14 10:45 UTC
Labels: bug, high
