### ISSUE TITLE
sstableloader limited 65535 rows

### ISSUE THREAD

**Issue by ban4785** [scylladb/scylla#2073] opened 2017-02-10 04:21 UTC
*Installation details*
Scylla version (or git commit hash): 1.5.0
Cluster size: 3
OS (RHEL/CentOS/Ubuntu/AWS AMI): CentOS 7.2

*Hardware details (for performance issues)*          Delete if unneeded
Platform (physical/VM/cloud instance type/docker): physical
Hardware: sockets= cores= hyperthreading= memory=32core hyperthreading, 64G mem
Disks: (SSD/HDD, count) : raid0 SSD

i made sstables which have 10,000,000 rows(sstable ver is cassandra 2.1.8)
bulkloaded with sstableloader.
but i got below message and failed.
![bulkload](https://cloud.githubusercontent.com/assets/20348151/22814022/8646025c-ef93-11e6-9da9-8360e72f01bb.png)

does scylladb have plan to fix sstableload limited rows?

**Comment by ban4785** [comment] 2017-02-10 04:22
and sstableloader(scylladb) only support 9042 default port?

**Comment by slivne** [comment] 2017-02-10 20:47
@ban4785 thanks, can you please calrify if the 10M rows are on a single partition ? just so we will have a correct reproducer.

**Comment by ban4785** [comment] 2017-02-13 02:18
10M rows have each partitions per row.
Schema was
CREATE TABLE testcase(
    key text primary key,
    value text
);
non clustering key schema.

**Comment by elcallio** [comment] 2017-02-13 09:53
Older sstableloader does not limit batch statement sizes, other than per routing. 1.7 version both limit the number of statements, and has the option to turn them off completely. 
Do we want a fix for <= 1.6?

**Comment by avikivity** [comment] 2017-02-13 11:22
I think 1.7 loader will work with Scylla 1.6 and older, yes?  If so we can give @ban4785 a 1.7 package.

**Comment by elcallio** [comment] 2017-02-13 14:05
1.7 sstableloader should work, yes, but using 1.7 scylla-tools-java with 
pre-c3 scylla might run into issues with the other tools (esp. 
nodetool). So if so it should be used side-by-side. At most.

**Comment by avikivity** [comment] 2017-02-13 14:07
It should be run on a host outside the cluster.

**Comment by slivne** [comment] 2017-03-30 11:50
@larisau do we have a dtest for this - if so is it passing on master/1.7 - so we can close this

**Comment by roydahan** [comment] 2017-03-30 12:14
It's currently SKIPPED  on 1.7 and master due to (require https://github.com/scylladb/scylla-tools-java/issues/24).

If we aren't going to fix that soon, we can change the test to create the data not using c-s.

**Comment by slivne** [comment] 2017-04-18 08:02
@roydahan / @larisau - lets change the test and create the schema in a different manner (you can still use c-s).

**Comment by slivne** [comment] 2017-04-30 10:26
@roydahan - @larisau - ping

**Comment by larisau** [comment] 2017-04-30 10:56
the test was changed:  https://github.com/scylladb/scylla-dtest/pull/483

**Closed** 2017-04-30 11:49 UTC
Labels: bug, User Request
