### ISSUE TITLE
Cannot alter Keyspace - no viable alternative at input 'ALTER'

### ISSUE THREAD

**Issue by Freeaqingme** [scylladb/scylla#1241] opened 2016-05-08 22:28 UTC
## Installation details
Scylla version (or git commit hash): 666.development-20160504.f1cd52f-ubuntu1
Cluster size: 4 UN, 1 UL
OS (RHEL/CentOS/Ubuntu/AWS AMI): Linux db0 4.4.0-21-generic #37~14.04.1-Ubuntu SMP Wed Apr 20 16:33:38 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

I'm attempting to change the replication factor of a keyspace. However, I can't fathom how I should accomplish this. Possibly related to #429, but it doesn't provide any description, so who knows :)

```
cqlsh> select * from system.schema_keyspaces;

 keyspace_name | durable_writes | strategy_class                             | strategy_options
---------------+----------------+--------------------------------------------+----------------------------
      kairosdb |           True |                             SimpleStrategy | {"replication_factor":"1"}
        system |           True | org.apache.cassandra.locator.LocalStrategy |                         {}

(2 rows)
cqlsh> 
cqlsh> ALTER KEYSPACE 'kairosdb' WITH REPLICATION = { 'class' : 'SimpleStrategy', 'replication_factor' : 3 };
SyntaxException: <ErrorMessage code=2000 [Syntax error in CQL query] message="line 1:0 no viable alternative at input 'ALTER'">
cqlsh> 
```

**Comment by penberg** [comment] 2016-05-09 05:23
``ALTER KEYSPACE`` is unfortunately not supported yet: http://www.scylladb.com/technology/status/#cassandra-compatibility

The issue is a duplicate of https://github.com/scylladb/scylla/issues/429

**Comment by dorlaor** [comment] 2016-05-09 05:25
Our plan is to complete it in the upcoming 1.2

**Comment by Freeaqingme** [comment] 2016-05-09 05:43
Thanks. Sort of what I was afraid of. Is it possible to alter the replication factor through some workaround, or am I to delete my keyspace and recreate it again with different settings - losing my data in the process?

**Comment by Freeaqingme** [comment] 2016-05-09 05:46
Oh, fwiw, on that status page ALTER KEYSPACE support is listed for 1.1. Guess it could use an update.

**Comment by tzach** [comment] 2016-05-09 11:15
> Oh, fwiw, on that status page ALTER KEYSPACE support is listed for 1.1. Guess it could use an update.

It does, thanks for pointing me to it

**Comment by tzach** [comment] 2016-05-10 15:37
Site if now up to date
http://www.scylladb.com/technology/status/

closing this issue as its is duplicate with #429 
Thanks @Freeaqingme

**Closed by tzach** 2016-05-10 15:37 UTC
Labels: duplicate
