### ISSUE TITLE
restart_node_with_resharding nemesis seastar::semaphore_timed_out (Semaphore timedout)

### ISSUE THREAD

**Issue by ShlomiBalalis** [scylladb/scylla#4615] opened 2019-06-27 08:12 UTC
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [x] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash): 3.1.0.rc2-0.20190624.433cb93f7
Cluster size: 5
OS (RHEL/CentOS/Ubuntu/AWS AMI): ami-0ac07c9630d9e4eea
(Ireland)

Platform (physical/VM/cloud instance type/docker): i3.4xlarge

During the nemesis restart_node_with_resharding, the target node, all of the shards returned the error "semaphore_timed_out" from all of its shards.
```
Jun 26 13:36:25 ip-10-0-167-66.eu-west-1.compute.internal scylla.bin[17945]:  [shard 6] storage_proxy - Failed to apply mutation from 10.0.132.172#6: seastar::semaphore_timed_out (Semaphore timedout)
```
[journal.log](https://github.com/scylladb/scylla/files/3330726/journal.log)

**Comment by juliayakovlev** [comment] 2019-06-27 09:03
Same error got during longevity-mv-si-4days while destroy_data_then_rebuild nemesis. Reported from the node where data was rebuilt. The error happens during the destroying/rebuilding and after the node has been up.
Logs: [https://cloudius-jenkins-test.s3.amazonaws.com/90f89887-310f-482f-9e1e-e132a493cc66/job-2019-06-26T12.18-ae93006.zip]

**Comment by bentsi** [comment] 2019-06-27 10:19
Same issue happened in 2 parallel nemesis longevity, when starting CS threads with different compressions. The nemesis that were run during the issue ran "nodetool repair"

![image](https://user-images.githubusercontent.com/5269241/60258310-936b7c00-98dd-11e9-8607-206a1df4e978.png)
Events:
```

2019-06-26 21:38:30.991 | (CassandraStressEvent Severity.NORMAL): type=start node=Node longevity-tls-1tb-7d-1dis-2nondis-1-loader-node-7bc14f28-1 [34.245.1.134 \| 10.0.38.18] (seed: False) stress_cmd=cassandra-stress mixed         cl=QUORUM duration=10080m -schema keyspace=keyspace1 'replication(factor=3)                               compaction(strategy=LeveledCompactionStrategy)'    -port jmx=6868 -mode cql3 native   user=cassandra password=cassandra -rate threads=20 -pop seq=1..1100200300  -log interval=5 -col 'size=FIXED(1024) n=FIXED(1)' -node 10.0.184.222 | CassandraStressEvent, NORMAL, events, start
-- | -- | --
2019-06-26 21:39:01.151 | (CassandraStressEvent Severity.NORMAL): type=start node=Node longevity-tls-1tb-7d-1dis-2nondis-1-loader-node-7bc14f28-2 [34.241.106.112 \| 10.0.189.132] (seed: False) stress_cmd=cassandra-stress mixed         cl=QUORUM duration=10080m -schema keyspace=keyspace1 'replication(factor=3)                               compaction(strategy=LeveledCompactionStrategy)'    -port jmx=6868 -mode cql3 native   user=cassandra password=cassandra -rate threads=20 -pop seq=1..1100200300  -log interval=5 -col 'size=FIXED(1024) n=FIXED(1)' -node 10.0.184.222 | CassandraStressEvent, NORMAL, events, start
2019-06-26 21:39:11.169 | (CassandraStressEvent Severity.NORMAL): type=start node=Node longevity-tls-1tb-7d-1dis-2nondis-1-loader-node-7bc14f28-1 [34.245.1.134 \| 10.0.38.18] (seed: False) stress_cmd=cassandra-stress write         cl=QUORUM duration=10010m -schema keyspace=keyspace1 'replication(factor=3) compression=LZ4Compressor     compaction(strategy=SizeTieredCompactionStrategy)' -port jmx=6868 -mode cql3 native compression=lz4                    user=cassandra password=cassandra -rate threads=50 -pop seq=1..50000000    -log interval=5 -node 10.0.184.222 | CassandraStressEvent, NORMAL, events, start
2019-06-26 21:39:41.200 | (CassandraStressEvent Severity.NORMAL): type=start node=Node longevity-tls-1tb-7d-1dis-2nondis-1-loader-node-7bc14f28-2 [34.241.106.112 \| 10.0.189.132] (seed: False) stress_cmd=cassandra-stress write         cl=QUORUM duration=10010m -schema keyspace=keyspace1 'replication(factor=3) compression=LZ4Compressor     compaction(strategy=SizeTieredCompactionStrategy)' -port jmx=6868 -mode cql3 native compression=lz4                    user=cassandra password=cassandra -rate threads=50 -pop seq=1..50000000    -log interval=5 -node 10.0.184.222 | CassandraStressEvent, NORMAL, events, start
2019-06-26 21:39:51.978 | (CassandraStressEvent Severity.NORMAL): type=start node=Node longevity-tls-1tb-7d-1dis-2nondis-1-loader-node-7bc14f28-1 [34.245.1.134 \| 10.0.38.18] (seed: False) stress_cmd=cassandra-stress write         cl=QUORUM duration=10020m -schema keyspace=keyspace1 'replication(factor=3) compression=SnappyCompressor  compaction(strategy=SizeTieredCompactionStrategy)' -port jmx=6868 -mode cql3 native compression=snappy                 user=cassandra password=cassandra -rate threads=50 -pop seq=1..50000000    -log interval=5 -node 10.0.184.222 | CassandraStressEvent, NORMAL, events, start
2019-06-26 21:40:21.981 | (CassandraStressEvent Severity.NORMAL): type=start node=Node longevity-tls-1tb-7d-1dis-2nondis-1-loader-node-7bc14f28-2 [34.241.106.112 \| 10.0.189.132] (seed: False) stress_cmd=cassandra-stress write         cl=QUORUM duration=10020m -schema keyspace=keyspace1 'replication(factor=3) compression=SnappyCompressor  compaction(strategy=SizeTieredCompactionStrategy)' -port jmx=6868 -mode cql3 native compression=snappy                 user=cassandra password=cassandra -rate threads=50 -pop seq=1..50000000    -log interval=5 -node 10.0.184.222 | CassandraStressEvent, NORMAL, events, start
2019-06-26 21:40:32.328 | (CassandraStressEvent Severity.NORMAL): type=start node=Node longevity-tls-1tb-7d-1dis-2nondis-1-loader-node-7bc14f28-1 [34.245.1.134 \| 10.0.38.18] (seed: False) stress_cmd=cassandra-stress write         cl=QUORUM duration=10030m -schema keyspace=keyspace1 'replication(factor=3) compression=DeflateCompressor compaction(strategy=SizeTieredCompactionStrategy)' -port jmx=6868 -mode cql3 native compression=none                   user=cassandra password=cassandra -rate threads=50 -pop seq=1..50000000    -log interval=5 -node 10.0.184.222 | CassandraStressEvent, NORMAL, events, start
2019-06-26 21:40:45.902 | (DatabaseLogEvent Severity.CRITICAL): type=DATABASE_ERROR regex=Exception  line_number=45618 node=Node longevity-tls-1tb-7d-1dis-2nondis-1-db-node-7bc14f28-5 [54.171.151.159 \| 10.0.135.12] (seed: False) Jun 26 21:40:24 ip-10-0-135-12.eu-west-1.compute.internal scylla.bin[6507]:  [shard 7] storage_proxy - Exception when communicating with 10.0.135.12: seastar::semaphore_timed_out (Semaphore timedout) | DatabaseLogEvent, CRITICAL, events, DATABASE_ERROR
2019-06-26 21:41:02.390 | (CassandraStressEvent Severity.NORMAL): type=start node=Node longevity-tls-1tb-7d-1dis-2nondis-1-loader-node-7bc14f28-2 [34.241.106.112 \| 10.0.189.132] (seed: False) stress_cmd=cassandra-stress write         cl=QUORUM duration=10030m -schema keyspace=keyspace1 'replication(factor=3) compression=DeflateCompressor compaction(strategy=SizeTieredCompactionStrategy)' -port jmx=6868 -mode cql3 native compression=none                   user=cassandra password=cassandra -rate threads=50 -pop seq=1..50000000    -log interval=5 -node 10.0.184.222
21:41:48.831 | (DatabaseLogEvent Severity.CRITICAL): type=DATABASE_ERROR regex=Exception  line_number=47567 node=Node longevity-tls-1tb-7d-1dis-2nondis-1-db-node-7bc14f28-5 [54.171.151.159 \| 10.0.135.12] (seed: False) Jun 26 21:41:10 ip-10-0-135-12.eu-west-1.compute.internal scylla.bin[6507]:  [shard 7] storage_proxy - Exception when communicating with 10.0.135.12: seastar::semaphore_timed_out (Semaphore timedout) | DatabaseLogEvent, CRITICAL, events, DATABASE_ERROR
2019-06-26 21:41:48.841 | (DatabaseLogEvent Severity.CRITICAL): type=DATABASE_ERROR regex=Exception  line_number=47651 node=Node longevity-tls-1tb-7d-1dis-2nondis-1-db-node-7bc14f28-5 [54.171.151.159 \| 10.0.135.12] (seed: False) Jun 26 21:41:15 ip-10-0-135-12.eu-west-1.compute.internal scylla.bin[6507]:  [shard 8] storage_proxy - Exception when communicating with 10.0.135.12: seastar::semaphore_timed_out (Semaphore timedout) | DatabaseLogEvent, CRITICAL, events, DATABASE_ERROR
2019-06-26 21:41:48.850 | (DatabaseLogEvent Severity.CRITICAL): type=DATABASE_ERROR regex=Exception  line_number=47733 node=Node longevity-tls-1tb-7d-1dis-2nondis-1-db-node-7bc14f28-5 [54.171.151.159 \| 10.0.135.12] (seed: False) Jun 26 21:41:18 ip-10-0-135-12.eu-west-1.compute.internal scylla.bin[6507]:  [shard 12] storage_proxy - Exception when communicating with 10.0.135.12: seastar::semaphore_timed_out (Semaphore timedout) | DatabaseLogEvent, CRITICAL, events, DATABASE_ERROR
```

**Comment by slivne** [comment] 2019-06-30 07:07
@bentsi any reproducer so we can check whats going on ?

**Comment by juliayakovlev** [comment] 2019-06-30 14:39
It happened again during MV-SI test.
The "semaphore_timed_out" messages started during hard reboot nemesis.
Later found also a lot of " std::runtime_error (**sstable read queue overloaded**)" errors:
```
[shard 10] storage_proxy - Exception when communicating with 10.0.179.136: std::runtime_error (sstable read queue overloaded)
```
Jenkins job: [job log](https://jenkins.scylladb.com/view/scylla-3.1/job/scylla-3.1/job/longevity/job/longevity-mv-si-4days/7/console)

**Comment by fruch** [comment] 2019-07-01 05:40
This is happening also in the 200gb longevity,  after major_compaction or restart_and_repair nemesis.

**Comment by slivne** [comment] 2019-07-08 07:30
@roydahan / @bentsi / @fruch  - AFAIK you have run 3.0.8 longevities as well - did this reproduce - if not please provide Avi access and lets have him look at the two runs side by side to see if he can extract more info from a comparison.

**Comment by slivne** [comment] 2019-07-08 10:55
@bentsi please work with Avi on this

**Comment by roydahan** [comment] 2019-07-08 11:37
We don't have the monitoring of 3.0 anymore, @bentsi is running in parallel longevities that should easily reproduce it, one with 3.1 and one 3.0.

**Comment by slivne** [comment] 2019-07-09 10:52
@bentsi find Avi with the info

**Comment by bentsi** [comment] 2019-07-09 12:50
3.0.8: The run unable to finish till the end, stress fails due to issue #4668
3.1:  longevity is still running but the issue didn't reproduce

**Comment by slivne** [comment] 2019-07-15 15:34
@bentsi any update if not lets close - we can allways reopen if you hit this again

**Comment by bentsi** [comment] 2019-07-15 17:41
I am running another longevity with parallel Nemesis, will update tomorrow if it happened

**Comment by bentsi** [comment] 2019-07-17 16:00
the issue wasn't reproduced in the last run of multiple Nemesis longevity on `3.1.0.rc2-0.20190713.92bf92817` so I think we can close this.

**Comment by juliayakovlev** [comment] 2019-08-19 10:46
The issue is reproduced in the MV-SI longevity. 
Scylla version ```3.1.0.rc3-0.20190816.d06bcef3b```
Jenkins job:
```
https://jenkins.scylladb.com/view/scylla-3.1/job/scylla-3.1/view/scylla-3.1-test/job/longevity/job/longevity-mv-si-4days/8/consoleFull
```

Monitor IP: ```34.201.51.128```

**Comment by juliayakovlev** [comment] 2019-08-20 09:40
@bhalevy  Benny, the issue is reprodused in 3.1. Please, see my comment above

**Comment by yarongilor** [comment] 2019-08-20 10:33
reproduced in 3.1.0.rc3-0.20190816.d06bcef3b 50GB longevity as well.
received error of:
```
[35.175.151.33 | 172.30.0.154] (seed: True)
2019-08-19T19:54:19+00:00 ip-172-30-0-154 !WARNING | scylla.bin: [shard 1] storage_proxy - Failed to apply mutation from 172.30.0.74#1: seastar::semaphore_timed_out (Semaphore timedout)
```

**Comment by bentsi** [comment] 2019-08-22 13:02
happened to me during parallel nemesis run (3.1.0.rc3-0.20190818.d06bcef3b):
Grafana dashboards:

- [scylla-per-server-metrics-nemesis-3-1](https://snapshot.raintank.io/dashboard/snapshot/7Hnh2TY7pjzcxLwztT8ASFl15BhChcH4)
- [scylla-per-server-disk-i-o](https://snapshot.raintank.io/dashboard/snapshot/CLgKKhTKW6rb67rQ3JdKNs06e7fOvRUN)
- [monitor](http://34.250.14.180:3000)

**Comment by avikivity** [comment] 2019-08-22 13:20
Fixed by 2c7435418affb70f18fdce6c7dd7762a5b2bcd64

**Closed by avikivity** 2019-08-22 13:20 UTC
Labels: bug, high

**Comment by avikivity** [comment] 2019-08-22 13:42
The issue also exists in 3.0. Why didn't 3.0 testing catch it?

**Comment by bentsi** [comment] 2019-08-22 14:58
in 3.0 we didn't have SCT events and so it was very hard to analyze the logs... (especially when the issue didn't cause Scylla to produce coredump or C-S crash)

**Comment by avikivity** [comment] 2019-12-05 20:40
Backported to 3.0, 3.1, 3.2.
