### ISSUE TITLE
ScyllaDB with golang driver

### ISSUE THREAD

**Issue by indykish** [scylladb/scylla#912] opened 2016-02-16 14:02 UTC
I tried the gocassa driver(https://github.com/megamsys/gocassa) built on top of  github.com/gocql/gocql with scylladb.

**Cassandra 2.1.8**

In cassandra a query is performed on  inside the code `github.com/gocql/gocql` for this query.

SELECT data_center, rack, host_id, tokens, release_version FROM system.local WHERE key='local'

I received  the results

```
Enter code here...&gocql.Iter{err:error(nil), pos:0, meta:gocql.resultMetadata{flags:1, pagingState:[]uint8(nil), columns:[]gocql.ColumnInfo{gocql.ColumnInfo{Keyspace:"system", Table:"local", Name:"data_center", TypeInfo:gocql.NativeType{proto:0x3, typ:13, custom:""}}, gocql.ColumnInfo{Keyspace:"system", Table:"local", Name:"rack", TypeInfo:gocql.NativeType{proto:0x3, typ:13, custom:""}}, gocql.ColumnInfo{Keyspace:"system", Table:"local", Name:"host_id", TypeInfo:gocql.NativeType{proto:0x3, typ:12, custom:""}}, gocql.ColumnInfo{Keyspace:"system", Table:"local", Name:"tokens", TypeInfo:gocql.CollectionType{NativeType:gocql.NativeType{proto:0x3, typ:34, custom:""}, Key:gocql.TypeInfo(nil), Elem:gocql.NativeType{proto:0x3, typ:13, custom:""}}}, gocql.ColumnInfo{Keyspace:"system", Table:"local", Name:"release_version", TypeInfo:gocql.NativeType{proto:0x3, typ:13, custom:""}}}, colCount:5, actualColCount:5}, numRows:1, next:(*gocql.nextIter)(nil), host:(*gocql.HostInfo)(nil), framer:(*gocql.framer)(0xc8200d80b0), once:sync.Once{m:sync.Mutex{state:0, sema:0x0}, done:0x0}}
```
and it works

**In ScyllaDB 0.17**

The same query returns back with no info from `github.com/gocql/gocql`

```
&gocql.Iter{err:error(nil), pos:0, meta:gocql.resultMetadata{flags:4, pagingState:[]uint8(nil), columns:[]gocql.ColumnInfo(nil), colCount:0, actualColCount:0}, numRows:1, next:(*gocql.nextIter)(nil), host:(*gocql.HostInfo)(nil), framer:(*gocql.framer)(0xc820094370), once:sync.Once{m:sync.Mutex{state:0, sema:0x0}, done:0x0}}

```

`unable to fetch host info for 127.0.0.1: gocql: not enough columns to scan into: have 5 want 0`

I tried using `cqlsh to scylladb` and ran the same query, but it works.

Can somebody throw light on what i can do in `github.com/gocql/gocql` to fix this problem ?

**Comment by glommer** [comment] 2016-02-16 14:56
I am sorry: I am not really familiar with go at all. Can you send me some example code that would execute that query ?

**Comment by indykish** [comment] 2016-02-16 15:04
The example file is under [https://github.com/megamsys/libgo/blob/master/db/scylladb_test.go](https://github.com/megamsys/libgo/blob/master/db/scylladb_test.go)

You need to have http://golang/dl (1.6 rc2) , mercurial(hg), bzr packages installed.

1. Create a directory =  `src/github.com/megamsys`
2. cd `src/github.com/megamsys`
3. git clone https://github.com/megamsys/libgo
4. cd libgo
5. Change the `nopis`  in [https://github.com/megamsys/libgo/blob/master/db/scylladb_test.go](https://github.com/megamsys/libgo/blob/master/db/scylladb_test.go)  to your cluster before you run.
```go
var noips = []string{"127.0.0.1"}
```
6. make test

**Comment by glommer** [comment] 2016-02-16 15:51
Hi. I get this:

# github.com/megamsys/libgo/action
action/action_test.go:23:2: cannot find package "gopkg.in/check.v1" in any of:
	/usr/local/go/src/gopkg.in/check.v1 (from $GOROOT)
	/home/glauber/go/src/gopkg.in/check.v1 (from $GOPATH)
	/home/glauber/go/src/gopkg.in/check.v1
FAIL	github.com/megamsys/libgo/action [setup failed]
Can you advise?

**Comment by indykish** [comment] 2016-02-16 16:19
go get gopkg.in/check.v1

**Comment by indykish** [comment] 2016-02-16 16:19
run that command

**Comment by indykish** [comment] 2016-02-16 16:19
also 
`go get github.com/tsuru/commandmocker`

**Comment by glommer** [comment] 2016-02-16 18:55
Hi. Sorry it took me a bit longer to get to this.

There is another line where the IP address needs to be changed: 

```
cluster := gocql.NewCluster("172.17.0.2")
```

I've changed that to the correct address and then got this:

```
ok  	github.com/megamsys/libgo/action	0.003s
ok  	github.com/megamsys/libgo/cmd	0.019s
2016/02/16 13:52:02 error setting connection keyspace. Keyspace 'testing' does not exist
```

I went back to your original messages and I can see no trace of the description of this keyspace.

Would you mind sharing it?

**Comment by indykish** [comment] 2016-02-17 02:03
In your scylla cluster, you can create a keyspace named `testing`
```
cqlsh 172,17.0.2 create keyspace testing with replication =  { 'class' : 'SimpleStrategy', 'replication_factor': 1};
```

**Comment by glommer** [comment] 2016-02-17 02:13
From what I can see, I was supposed to have a "customer" table as well, no?

After that, Scylla reports the following message:
```
WARNING: exceptional future ignored of type 'exceptions::invalid_request_exception': unconfigured table customer
```

And from reading the code, it does seem such a table has to exist. Please include that as well.

**Comment by glommer** [comment] 2016-02-17 02:15
Also, skimming through the code, it seems to expect certain data to be present as well. Like this:

```
func (s *S) TestReadWhereRowFound(c *check.C) {
    rand.Seed(time.Now().Unix())
    t := s.sy.Table("customer", []string{"Id", "Name"}, []string{}, &Customer{})
    err := t.T.(gocassa.TableChanger).CreateIfNotExist()
    c.Assert(err, check.IsNil)
    err = t.Upsert(&Customer{
        Id:   "1001",
        Name: "Joe",
    })
    c.Assert(err, check.IsNil)
    res := Customer{}
    err = t.ReadWhere(ScyllaWhere{clauses: map[string]string{"Id": "1001", "Name": "Joe"}}, &res)
    c.Assert(err, check.IsNil)
}
```

I understand from the above that you will expect the table to be populated in a certain way. Please include a statement that will allow me to have the full test scenario, so I can make sure I have the same as you do. This way we can avoid false alarms.

**Comment by indykish** [comment] 2016-02-17 08:09
`use keyspace testing;
create table customer (Id text, Name text, PRIMARY KEY (Id, Name));`

**Comment by indykish** [comment] 2016-02-17 08:15
Actually you try running `make test` again. It will create a table.

**Comment by indykish** [comment] 2016-02-17 08:17
May i know what version of scylla you are using ? Since in my case with no keyspace, it shows an error.

`
go clean  ./...
go test  ./...
ok  	github.com/megamsys/libgo/action	0.023s
ok  	github.com/megamsys/libgo/cmd	0.054s
2016/02/17 13:45:57 gocql: events: unable to fetch host info for 103.56.92.24: gocql: not enough columns to scan into: have 5 want 0
-- ks <nil>
`

So clearly you have gone past the error i had.  
**What version of scylla ?**

**Comment by indykish** [comment] 2016-02-17 08:20
Are you running scylla 0.16 with --development on ext4 fs, ubuntu 14.04. ? 

I did a test using scylla 0.17 (docker)

Does your test cluster run using xfs  ?  

I believe xfs or ext4 shouldn't matter as the performance will be lower in ext4.

**Comment by glommer** [comment] 2016-02-17 14:47
I am running our current git master. It is probably closer to the upcoming 0.18
I always run XFS, but if it matters, my "cluster" is comprised of a single node (since I was just testing anyway).

How many nodes are you running? If more than one, I would recommend you run a single node for a quick test. Maybe our bug comes from inter-node synchronization.

**Comment by indykish** [comment] 2016-02-17 14:57
I am running a single node.

So the code works for you ?

**Comment by glommer** [comment] 2016-02-17 15:31
yeah, it proceeds until it fails due to the missing table. If you are comfortable compiling Scylla from source, I would say you could try our current master branch and see if the problem does disappear for you as well. If it doesn't, then we'll have to dig to see what is the difference in our setups (besides that) that makes it work for me and not for you.

In the mean time I can revert my tree to 0.16 and 0.17 as well and see how it behaves.

**Comment by indykish** [comment] 2016-02-17 15:42
Ok, will try scylla 0.18.

**Comment by glommer** [comment] 2016-02-17 16:01
Ok, both 0.16 and 0.17 works for me as well (up to the table query).
So I would say the problem is another one. Let's try to narrow it down: what are your command line options for Scylla?

**Comment by indykish** [comment] 2016-02-17 16:26
**In local archlinux**
'sudo docker run -p 9042:9042 -i -t scylladb/scylla`

**In our remote 1 node (103.56.92.24)**
- Installed the debian package for 0.16 
- `scylla-server start`
Changed the `rpc, listening ipaddress` in conf file to  `103.56.92.24`

**Comment by indykish** [comment] 2016-02-17 17:13
Anything i need to do different in the start command  installed via the deb package in ubuntu 14.04  ?

**Comment by glommer** [comment] 2016-02-17 17:32
It is not about need, it was supposed to work (unless I am missing something). I am just trying to understand if a particular option can be to blame.

**Comment by indykish** [comment] 2016-02-18 02:13
What options have you used to start the `scylla-server` ?

**Comment by glommer** [comment] 2016-02-18 02:17
I have just used the defaults from my conf/scylla.yaml that we ship by
default.

I am running this from my development tree and just wanted to see if it was
something easy to reproduce (i.e., if it is present in all setups).
Apparently this is being triggered by some options so we'll have to dig a
bit deeper to find out which.

**Comment by indykish** [comment] 2016-02-18 02:51
I connected to scylla in  different ips than 127.0.0.1. 

Did you run connecting to scylla 127.0.0.1 ? 

Let me create a ubuntu vm and try testing there.

**Comment by glommer** [comment] 2016-02-18 04:36
On Wed, Feb 17, 2016 at 9:51 PM, Kishorekumar Neelamegam <
notifications@github.com> wrote:

> I connected to scylla in different ips than 127.0.0.1.
>
> Did you run connecting to scylla 127.0.0.1 ?
>
> Let me create a ubuntu vm and try testing there.
>

Yes, I did connect at 127.0.0.1

**Comment by indykish** [comment] 2016-02-18 15:59
@glommer Our team mate @morpheyesh debugged this problem and fixed it. Its a bug in https://github.com/hailocab/gocassa driver.

**Comment by indykish** [comment] 2016-02-18 15:59
@glommer  Thanks a lot for your swift help.

**Comment by penberg** [comment] 2016-02-20 11:36
@indykish @morpheyesh, is the issue fixed in the gocassa driver upstream? Can you point us to the commit?

**Comment by indykish** [comment] 2016-02-20 11:48
Pekka,

@morpheyesh found the the problem in https://github.com/gocql/gocql and not
in gocassa. He is fixing it up and has a temporary hack to get around it.

@morpheyesh, Can you respond please ?

@morpheysh will post the link in here after we have tested it fully next
week.

On Sat, Feb 20, 2016 at 5:06 PM, Pekka Enberg <notifications@github.com>
wrote:

> @indykish <https://github.com/indykish> @morpheyesh
> <https://github.com/morpheyesh>, is the issue fixed in the gocassa driver
> upstream? Can you point us to the commit?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/scylladb/scylla/issues/912#issuecomment-186576577>.
>



-- 
*Kishorekumar Neelamegam,*
Founder & CEO, Megam Systems
mail : nkishore@megam.io, cell: +91 9840559300
web : https://www.megam.io | twitter : @indykish
<https://twitter.com/#%21/indykish>

**Comment by tzach** [comment] 2016-02-23 05:58
@morpheyesh that will be much appreciated
I know of at least one more person with the same issue

**Comment by morpheyesh** [comment] 2016-02-23 06:36
Yes.  Fixing it up. :)

**Comment by akxs14** [comment] 2016-02-23 20:33
Hi @morpheyesh , any estimation when we'll see the solution?

**Comment by penberg** [comment] 2016-02-24 11:15
The issue can be reproduced by running the ``TestRingDiscovery`` integration test in gocql. I'm reopening the issue.

**Closed** 2016-02-24 12:43 UTC
Labels: User Request
