### ISSUE TITLE
scylladb 1.2 makes vm die

### ISSUE THREAD

**Issue by ycui1984** [scylladb/scylla#1493] opened 2016-07-22 18:38 UTC
*Installation details*
Scylla version (or git commit hash):1.2
Cluster size: single node
OS (RHEL/CentOS/Ubuntu/AWS AMI): ubuntu 14.04 vm

after installing scylladb 1.2, the vm dies. 
Tried twice and the same results. Rebooting the vm does not help

**Comment by dorlaor** [comment] 2016-07-22 21:28
Can you provide the logs?
Was it a fresh install (no data)?
Please provide the core dump (we have a wiki which explains how to upload
it).
Also, 1.2.2 is out, please make sure you have it.

**Comment by ycui1984** [comment] 2016-07-22 21:59
yes, it is a fresh install, and no changes to get logs. 
I will see how to generate the core dump.

Thanks

**Comment by dorlaor** [comment] 2016-07-22 22:06
Here's how to upload cores:
https://github.com/scylladb/scylla/wiki/How-to-report-a-Scylla-problem#send-the-core-dump

**Comment by avikivity** [comment] 2016-07-23 14:46
What was the VM RAM size?
Was it running anything else (a GUI?)
What do you mean by "dies"?

**Comment by ycui1984** [comment] 2016-07-25 04:21
no gui, just command line. 
Dies means there is no response when using keyboard. 
Rebooting also does not help.
I will find my RAM size later.

**Comment by kongove** [comment] 2016-07-25 04:26
@ycui1984 You can try to upgrade the vm kernel,  reference issue #1486

**Comment by dorlaor** [comment] 2016-07-25 07:34
@ycui1984 it's possible to get the Xen boot log from the AWS console even
when the VM is dead.

On Mon, Jul 25, 2016 at 7:26 AM, Amos Jianjun Kong <notifications@github.com

**Comment by ycui1984** [comment] 2016-07-25 17:25
@kongove
Even if the problem is kernel support, scylla should not die when running a kernel that it does not support. It should promote its user in some way.  Make sense?

**Comment by avikivity** [comment] 2016-07-25 17:29
The problem is that if the kernel crashed, there is nothing Scylla can do.
We haven't proved that this is the case, though.

**Comment by ycui1984** [comment] 2016-07-25 19:56
one thing we can do is to detect kernel version first, if a invalid kernel version is found, did not install any scylla packages, instead of the current best effect way (try to install scylla on an invalid kernel.)

**Comment by dorlaor** [comment] 2016-07-25 21:40
We actually do recommend to stay away certain kernels. So far we haven't
received
a crash report about 14.04.

Do you have the specific kernel version and the kernel log?
There is a low latency kernel you can install on top of 14.04. It's a newer
Ubuntu kernel package. How about trying it?

**Comment by ycui1984** [comment] 2016-07-26 17:30
this our ubuntu release,

lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.4 LTS
Release:	14.04
Codename:	trusty

**Comment by ycui1984** [comment] 2016-07-26 17:32
uname -a
Linux elsrocks002 3.13.0-79-generic #123-Ubuntu SMP Fri Feb 19 14:27:58 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

because the vm is dead, we cannot issue uname on it, but should be similar with the above one.

**Comment by dorlaor** [comment] 2016-07-27 15:50
According to our Ubuntu page, we need a > 3.15 and above:
*http://www.scylladb.com/doc/getting-started-ubuntu/
<http://www.scylladb.com/doc/getting-started-ubuntu/>*

**Comment by tzach** [comment] 2016-08-07 09:29
Closing this issue, as it uses a non-supported kernel version
@ycui1984 can you please test with a newer version? thanks

**Closed by tzach** 2016-08-07 09:29 UTC
