### ISSUE TITLE
nodetool cfstats: Space used (total) is not accurate

### ISSUE THREAD

**Issue by asias** [scylladb/scylla#1252] opened 2016-05-10 01:39 UTC
On a 5 node cluster, the  Space used (total) says it is 31GB while the cluster's load is 11GB from nodetool status. 

 Data is written with
               cassandra-stress write cl=QUORUM duration=%sm "
                "-schema 'replication(factor=3)' -port jmx=6868 "
                "-mode cql3 native -rate threads=%s "
                "-pop seq=1..10000000 -node %s

$ nodetool status
UN  172.30.0.42   3.22 GB    256     ?       08ae6f65-c339-420a-b1f4-5e5ee0d69ff4  rack1
UN  172.30.0.43   3.39 GB    256     ?       dbc2bff3-af30-4a8c-b32f-c7becb347993  rack1
UN  172.30.0.136  1.91 GB    256     ?       8580213c-5a3a-4083-8109-9a625cade68b  rack1
UN  172.30.0.41   2.81 GB    256     ?       e21b68bd-1b9b-40c4-b832-7c4754c3858a  rack1

$ nodetool cfstats  keyspace1
        Space used (live): 2 048 938 195
        Space used (total): 31 997 017 045

$ pwd
/var/lib/scylla/data

$ sudo du -h keyspace1/
2.1G    keyspace1/standard1-6ab64560164a11e6a4d0000000000001
2.1G    keyspace1/

**Comment by amnonh** [comment] 2016-05-10 06:00
duplicate of #1042?

**Comment by asias** [comment] 2016-05-10 06:14
It is not related to migration. It is a completely new scylla cluster.

On Tue, May 10, 2016 at 2:00 PM, Amnon Heiman <notifications@github.com>
wrote:

> duplicate of #1042?
>
> On Tue, May 10, 2016 at 4:39 AM, Asias He <notifications@github.com>
> wrote:
>
> > On a 5 node cluster, the Space used (total) says it is 31GB while the
> > cluster's load is 11GB from nodetool status.
> >
> > Data is written with
> > cassandra-stress write cl=QUORUM duration=%sm "
> > "-schema 'replication(factor=3)' -port jmx=6868 "
> > "-mode cql3 native -rate threads=%s "
> > "-pop seq=1..10000000 -node %s
> >
> > $ nodetool status
> > UN 172.30.0.42 3.22 GB 256 ? 08ae6f65-c339-420a-b1f4-5e5ee0d69ff4 rack1
> > UN 172.30.0.43 3.39 GB 256 ? dbc2bff3-af30-4a8c-b32f-c7becb347993 rack1
> > UN 172.30.0.136 1.91 GB 256 ? 8580213c-5a3a-4083-8109-9a625cade68b rack1
> > UN 172.30.0.41 2.81 GB 256 ? e21b68bd-1b9b-40c4-b832-7c4754c3858a rack1
> >
> > $ nodetool cfstats keyspace1
> > Space used (live): 2 048 938 195
> > Space used (total): 31 997 017 045
> >
> > $ pwd
> > /var/lib/scylla/data
> >
> > $ sudo du -h keyspace1/
> > 2.1G keyspace1/standard1-6ab64560164a11e6a4d0000000000001
> > 2.1G keyspace1/
> >
> > —
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly or view it on GitHub
> > <https://github.com/scylladb/scylla/issues/1252>
> >
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/scylladb/scylla/issues/1252#issuecomment-218066376>
>



-- 
Asias

**Comment by amnonh** [comment] 2016-05-10 06:20
yes, that was Shlomi's last comment.

**Closed** 2016-05-16 11:08 UTC
Labels: bug, duplicate
