### ISSUE TITLE
3s stalls in cache_streamed_mutation::read_from_underlying

### ISSUE THREAD

**Issue by pdziepak** [scylladb/scylla#2698] opened 2017-08-15 20:08 UTC
*Installation details*
Scylla version (or git commit hash): 2.0-rc1

Read workload:
```
scylla-bench -duration 15m -partition-count 1000000 -clustering-row-count 1000 -clustering-row-size 128 -connection-count 32 -measure-latency=false -replication-factor 3 -concurrency=256 -workload=uniform -mode=read
```

Once the cache warms up and partitions stored inside it get larger frequent stalls around 3 seconds each are observed. First round of eviction makes the stalls disappear (at least temporarily).

Points of interests in backtraces include: `cache_streamed_mutation::read_from_underlying`, `consume_mutation_fragments_until` and `cache_streamed_mutation::maybe_add_to_cache`.

One of the backtraces:
```
Reactor stalled for 3347 ms on shard 24.
Backtrace:
0x00000000004eef98
0x00000000004ef279
0x00007f6e7483f0ff
0x00000000004e99ef
0x00007f6e7483f0ff
0x0000000000b38c75
0x0000000000b3e448
0x0000000000b43dfc
0x0000000000b442ce
0x0000000000b44381
0x0000000000b47543
0x00000000004ecd4f
0x000000000054087a
0x0000000000542120
0x000000000059a58d
0x00007f6e74837dc4
0x00007f6e74564cecseastar::backtrace_buffer::append_backtrace() at /usr/src/debug/scylla-2.0.rc2/seastar/core/reactor.cc:277
 (inlined by) print_with_backtrace at /usr/src/debug/scylla-2.0.rc2/seastar/core/reactor.cc:288
seastar::reactor::block_notifier(int) at /usr/src/debug/scylla-2.0.rc2/seastar/core/reactor.cc:514
?? ??:0
std::_Function_handler<seastar::metrics::impl::metric_value (), std::function<seastar::metrics::impl::metric_value ()> seastar::metrics::impl::make_function<seastar::reactor::register_metrics()::{lambda()#2}, void>(seastar::reactor::register_metrics()::{lambda()#2}, seastar::metrics::impl::data_type)::{lambda()#1}>::_M_invoke(std::_Any_data const&) at /opt/scylladb/include/c++/5.3.1/functional:1858
?? ??:0
_ZN13deletable_rowC4E13row_tombstoneRK10row_markerRK3row at /usr/src/debug/scylla-2.0.rc2/mutation_partition.hh:603
 (inlined by) _ZN10rows_entryC4ERK21clustering_key_prefix13row_tombstoneRK10row_markerRK3row at /usr/src/debug/scylla-2.0.rc2/mutation_partition.hh:693
 (inlined by) rows_entry* allocation_strategy::construct<rows_entry, clustering_key_prefix const&, row_tombstone, row_marker const&, row const&>(clustering_key_prefix const&, row_tombstone&&, row_marker const&, row const&) at /usr/src/debug/scylla-2.0.rc2/utils/allocation_strategy.hh:138
 (inlined by) cache::cache_streamed_mutation::maybe_add_to_cache(clustering_row const&)::{lambda()#1}::operator()() const at /usr/src/debug/scylla-2.0.rc2/cache_streamed_mutation.hh:296
void cache::lsa_manager::run_in_update_section_with_allocator<cache::cache_streamed_mutation::maybe_add_to_cache(clustering_row const&)::{lambda()#1}>(cache::cache_streamed_mutation::maybe_add_to_cache(clustering_row const&)::{lambda()#1}&&)::{lambda()#1}::operator()() const::{lambda()#1}::operator()() const::{lambda()#1}::operator()() at /usr/src/debug/scylla-2.0.rc2/cache_streamed_mutation.hh:63
 (inlined by) _Z14with_allocatorIZZZN5cache11lsa_manager36run_in_update_section_with_allocatorIZNS0_23cache_streamed_mutation18maybe_add_to_cacheERK14clustering_rowEUlvE_EEvOT_ENKUlvE_clEvENKUlvE_clEvEUlvE_EDcR19allocation_strategyS9_ at /usr/src/debug/scylla-2.0.rc2/utils/allocation_strategy.hh:271
 (inlined by) void cache::lsa_manager::run_in_update_section_with_allocator<cache::cache_streamed_mutation::maybe_add_to_cache(clustering_row const&)::{lambda()#1}>(cache::cache_streamed_mutation::maybe_add_to_cache(clustering_row const&)::{lambda()#1}&&)::{lambda()#1}::operator()() const::{lambda()#1}::operator()() const at /usr/src/debug/scylla-2.0.rc2/cache_streamed_mutation.hh:64
 (inlined by) std::result_of<cache::cache_streamed_mutation::maybe_add_to_cache(clustering_row const&)::{lambda()#1} ()>::type with_linearized_managed_bytes<void cache::lsa_manager::run_in_update_section_with_allocator<cache::cache_streamed_mutation::maybe_add_to_cache(clustering_row const&)::{lambda()#1}>(cache::cache_streamed_mutation::maybe_add_to_cache(clustering_row const&)::{lambda()#1}&&)::{lambda()#1}::operator()() const::{lambda()#1}>(void cache::lsa_manager::run_in_update_section_with_allocator<cache::cache_streamed_mutation::maybe_add_to_cache(clustering_row const&)::{lambda()#1}>(cache::cache_streamed_mutation::maybe_add_to_cache(clustering_row const&)::{lambda()#1}&&)::{lambda()#1}::operator()() const::{lambda()#1}) at /usr/src/debug/scylla-2.0.rc2/utils/managed_bytes.hh:417
 (inlined by) void cache::lsa_manager::run_in_update_section_with_allocator<cache::cache_streamed_mutation::maybe_add_to_cache(clustering_row const&)::{lambda()#1}>(cache::cache_streamed_mutation::maybe_add_to_cache(clustering_row const&)::{lambda()#1}&&)::{lambda()#1}::operator()() const at /usr/src/debug/scylla-2.0.rc2/cache_streamed_mutation.hh:65
 (inlined by) _ZN8logalloc18allocating_sectionclIZN5cache11lsa_manager36run_in_update_section_with_allocatorIZNS2_23cache_streamed_mutation18maybe_add_to_cacheERK14clustering_rowEUlvE_EEvOT_EUlvE_EEDcRNS_6regionESB_ at /usr/src/debug/scylla-2.0.rc2/utils/logalloc.hh:656
 (inlined by) void cache::lsa_manager::run_in_update_section_with_allocator<cache::cache_streamed_mutation::maybe_add_to_cache(clustering_row const&)::{lambda()#1}>(cache::cache_streamed_mutation::maybe_add_to_cache(clustering_row const&)::{lambda()#1}&&) at /usr/src/debug/scylla-2.0.rc2/cache_streamed_mutation.hh:65
 (inlined by) cache::cache_streamed_mutation::maybe_add_to_cache(clustering_row const&) at /usr/src/debug/scylla-2.0.rc2/cache_streamed_mutation.hh:327
 (inlined by) cache::cache_streamed_mutation::maybe_add_to_cache(mutation_fragment const&) at /usr/src/debug/scylla-2.0.rc2/cache_streamed_mutation.hh:275
 (inlined by) cache::cache_streamed_mutation::read_from_underlying()::{lambda(mutation_fragment)#2}::operator()(mutation_fragment) const at /usr/src/debug/scylla-2.0.rc2/cache_streamed_mutation.hh:228
 (inlined by) seastar::future<> consume_mutation_fragments_until<cache::cache_streamed_mutation::read_from_underlying()::{lambda()#1}, cache::cache_streamed_mutation::read_from_underlying()::{lambda(mutation_fragment)#2}, cache::cache_streamed_mutation::read_from_underlying()::{lambda()#3}>(streamed_mutation&, cache::cache_streamed_mutation::read_from_underlying()::{lambda()#1}&&, cache::cache_streamed_mutation::read_from_underlying()::{lambda(mutation_fragment)#2}&&, cache::cache_streamed_mutation::read_from_underlying()::{lambda()#3}&&)::{lambda()#2}::operator()() const at /usr/src/debug/scylla-2.0.rc2/streamed_mutation.hh:734
void seastar::do_until_continued<seastar::future<> consume_mutation_fragments_until<cache::cache_streamed_mutation::read_from_underlying()::{lambda()#1}, cache::cache_streamed_mutation::read_from_underlying()::{lambda(mutation_fragment)#2}, cache::cache_streamed_mutation::read_from_underlying()::{lambda()#3}>(streamed_mutation&, cache::cache_streamed_mutation::read_from_underlying()::{lambda()#1}&&, cache::cache_streamed_mutation::read_from_underlying()::{lambda(mutation_fragment)#2}&&, cache::cache_streamed_mutation::read_from_underlying()::{lambda()#3}&&)::{lambda()#2}, {lambda()#3} consume_mutation_fragments_until<{lambda()#1}, mutation_fragment, {lambda(mutation_fragment)#2}>(seastar::future, streamed_mutation, {lambda()#1}, mutation_fragment)::{lambda()#1}&>(seastar::future<> consume_mutation_fragments_until<cache::cache_streamed_mutation::read_from_underlying()::{lambda()#1}, cache::cache_streamed_mutation::read_from_underlying()::{lambda(mutation_fragment)#2}, cache::cache_streamed_mutation::read_from_underlying()::{lambda()#3}>(streamed_mutation&, cache::cache_streamed_mutation::read_from_underlying()::{lambda()#1}&&, cache::cache_streamed_mutation::read_from_underlying()::{lambda(mutation_fragment)#2}&&, cache::cache_streamed_mutation::read_from_underlying()::{lambda()#3}&&)::{lambda()#2}, streamed_mutation, seastar::promise<>) at /usr/src/debug/scylla-2.0.rc2/seastar/core/future-util.hh:155
void seastar::do_until_continued<seastar::future<> consume_mutation_fragments_until<cache::cache_streamed_mutation::read_from_underlying()::{lambda()#1}, cache::cache_streamed_mutation::read_from_underlying()::{lambda(mutation_fragment)#2}, cache::cache_streamed_mutation::read_from_underlying()::{lambda()#3}>(streamed_mutation&, cache::cache_streamed_mutation::read_from_underlying()::{lambda()#1}&&, cache::cache_streamed_mutation::read_from_underlying()::{lambda(mutation_fragment)#2}&&, cache::cache_streamed_mutation::read_from_underlying()::{lambda()#3}&&)::{lambda()#2}, {lambda()#3} consume_mutation_fragments_until<{lambda()#1}, mutation_fragment, {lambda(mutation_fragment)#2}>(seastar::future, streamed_mutation, {lambda()#1}, mutation_fragment)::{lambda()#1}>(seastar::future<> consume_mutation_fragments_until<cache::cache_streamed_mutation::read_from_underlying()::{lambda()#1}, cache::cache_streamed_mutation::read_from_underlying()::{lambda(mutation_fragment)#2}, cache::cache_streamed_mutation::read_from_underlying()::{lambda()#3}>(streamed_mutation&, cache::cache_streamed_mutation::read_from_underlying()::{lambda()#1}&&, cache::cache_streamed_mutation::read_from_underlying()::{lambda(mutation_fragment)#2}&&, cache::cache_streamed_mutation::read_from_underlying()::{lambda()#3}&&)::{lambda()#2}, streamed_mutation, seastar::promise<>)::{lambda({lambda()#3})#1}::operator()({lambda()#3}) at /usr/src/debug/scylla-2.0.rc2/seastar/core/future-util.hh:160
std::enable_if<!seastar::is_future<std::result_of<seastar::future<> ({lambda()#3}&&)>::type>::value, {lambda()#3}>::type seastar::do_void_futurize_apply<void seastar::do_until_continued<seastar::future<> consume_mutation_fragments_until<cache::cache_streamed_mutation::read_from_underlying()::{lambda()#1}, cache::cache_streamed_mutation::read_from_underlying()::{lambda(mutation_fragment)#2}, cache::cache_streamed_mutation::read_from_underlying()::{lambda()#3}>(streamed_mutation&, cache::cache_streamed_mutation::read_from_underlying()::{lambda()#1}&&, cache::cache_streamed_mutation::read_from_underlying()::{lambda(mutation_fragment)#2}&&, cache::cache_streamed_mutation::read_from_underlying()::{lambda()#3}&&)::{lambda()#2}, {lambda()#3} consume_mutation_fragments_until<{lambda()#1}, mutation_fragment, {lambda(mutation_fragment)#2}>(seastar::future, streamed_mutation, {lambda()#1}, mutation_fragment)::{lambda()#1}>(seastar::future<> consume_mutation_fragments_until<cache::cache_streamed_mutation::read_from_underlying()::{lambda()#1}, cache::cache_streamed_mutation::read_from_underlying()::{lambda(mutation_fragment)#2}, cache::cache_streamed_mutation::read_from_underlying()::{lambda()#3}>(streamed_mutation&, cache::cache_streamed_mutation::read_from_underlying()::{lambda()#1}&&, cache::cache_streamed_mutation::read_from_underlying()::{lambda(mutation_fragment)#2}&&, cache::cache_streamed_mutation::read_from_underlying()::{lambda()#3}&&)::{lambda()#2}, streamed_mutation, seastar::promise<>)::{lambda({lambda()#3})#1}, {lambda()#3}>(streamed_mutation, void seastar::do_until_continued<seastar::future<> consume_mutation_fragments_until<cache::cache_streamed_mutation::read_from_underlying()::{lambda()#1}, cache::cache_streamed_mutation::read_from_underlying()::{lambda(mutation_fragment)#2}, cache::cache_streamed_mutation::read_from_underlying()::{lambda()#3}>(streamed_mutation&, cache::cache_streamed_mutation::read_from_underlying()::{lambda()#1}&&, cache::cache_streamed_mutation::read_from_underlying()::{lambda(mutation_fragment)#2}&&, cache::cache_streamed_mutation::read_from_underlying()::{lambda()#3}&&)::{lambda()#2}, {lambda()#3} consume_mutation_fragments_until<{lambda()#1}, mutation_fragment, {lambda(mutation_fragment)#2}>(seastar::future, streamed_mutation, {lambda()#1}, mutation_fragment)::{lambda()#1}>(seastar::future<> consume_mutation_fragments_until<cache::cache_streamed_mutation::read_from_underlying()::{lambda()#1}, cache::cache_streamed_mutation::read_from_underlying()::{lambda(mutation_fragment)#2}, cache::cache_streamed_mutation::read_from_underlying()::{lambda()#3}>(streamed_mutation&, cache::cache_streamed_mutation::read_from_underlying()::{lambda()#1}&&, cache::cache_streamed_mutation::read_from_underlying()::{lambda(mutation_fragment)#2}&&, cache::cache_streamed_mutation::read_from_underlying()::{lambda()#3}&&)::{lambda()#2}, streamed_mutation, seastar::promise<>)::{lambda({lambda()#3})#1}) at /usr/src/debug/scylla-2.0.rc2/seastar/core/future.hh:1247
{lambda()#3} seastar::futurize<void>::apply<void seastar::do_until_continued<seastar::future<> consume_mutation_fragments_until<cache::cache_streamed_mutation::read_from_underlying()::{lambda()#1}, cache::cache_streamed_mutation::read_from_underlying()::{lambda(mutation_fragment)#2}, cache::cache_streamed_mutation::read_from_underlying()::{lambda()#3}>(streamed_mutation&, cache::cache_streamed_mutation::read_from_underlying()::{lambda()#1}&&, cache::cache_streamed_mutation::read_from_underlying()::{lambda(mutation_fragment)#2}&&, cache::cache_streamed_mutation::read_from_underlying()::{lambda()#3}&&)::{lambda()#2}, {lambda()#3} consume_mutation_fragments_until<{lambda()#1}, mutation_fragment, {lambda(mutation_fragment)#2}>(seastar::future, streamed_mutation, {lambda()#1}, mutation_fragment)::{lambda()#1}>(seastar::future<> consume_mutation_fragments_until<cache::cache_streamed_mutation::read_from_underlying()::{lambda()#1}, cache::cache_streamed_mutation::read_from_underlying()::{lambda(mutation_fragment)#2}, cache::cache_streamed_mutation::read_from_underlying()::{lambda()#3}>(streamed_mutation&, cache::cache_streamed_mutation::read_from_underlying()::{lambda()#1}&&, cache::cache_streamed_mutation::read_from_underlying()::{lambda(mutation_fragment)#2}&&, cache::cache_streamed_mutation::read_from_underlying()::{lambda()#3}&&)::{lambda()#2}, streamed_mutation, seastar::promise<>)::{lambda({lambda()#3})#1}, {lambda()#3}>(streamed_mutation, {lambda()#3}&&) at /usr/src/debug/scylla-2.0.rc2/seastar/core/future.hh:1295
 (inlined by) streamed_mutation& seastar::future<>::then_wrapped<void seastar::do_until_continued<seastar::future<> consume_mutation_fragments_until<cache::cache_streamed_mutation::read_from_underlying()::{lambda()#1}, cache::cache_streamed_mutation::read_from_underlying()::{lambda(mutation_fragment)#2}, cache::cache_streamed_mutation::read_from_underlying()::{lambda()#3}>(streamed_mutation&, cache::cache_streamed_mutation::read_from_underlying()::{lambda()#1}&&, cache::cache_streamed_mutation::read_from_underlying()::{lambda(mutation_fragment)#2}&&, cache::cache_streamed_mutation::read_from_underlying()::{lambda()#3}&&)::{lambda()#2}, seastar::future<> consume_mutation_fragments_until<{lambda()#1}, mutation_fragment, {lambda(mutation_fragment)#2}>({lambda()#3}, streamed_mutation, {lambda()#1}, mutation_fragment)::{lambda()#1}>(seastar::future<> consume_mutation_fragments_until<cache::cache_streamed_mutation::read_from_underlying()::{lambda()#1}, cache::cache_streamed_mutation::read_from_underlying()::{lambda(mutation_fragment)#2}, cache::cache_streamed_mutation::read_from_underlying()::{lambda()#3}>(streamed_mutation&, cache::cache_streamed_mutation::read_from_underlying()::{lambda()#1}&&, cache::cache_streamed_mutation::read_from_underlying()::{lambda(mutation_fragment)#2}&&, cache::cache_streamed_mutation::read_from_underlying()::{lambda()#3}&&)::{lambda()#2}, streamed_mutation, seastar::promise<>)::{lambda(seastar::future<>)#1}, seastar::future<> >(streamed_mutation)::{lambda(streamed_mutation)#1}::operator()<seastar::future_state<> >(auto, streamed_mutation) at /usr/src/debug/scylla-2.0.rc2/seastar/core/future.hh:940
 (inlined by) seastar::continuation<streamed_mutation& seastar::future<>::then_wrapped<void seastar::do_until_continued<seastar::future<> consume_mutation_fragments_until<cache::cache_streamed_mutation::read_from_underlying()::{lambda()#1}, cache::cache_streamed_mutation::read_from_underlying()::{lambda(mutation_fragment)#2}, cache::cache_streamed_mutation::read_from_underlying()::{lambda()#3}>(streamed_mutation&, cache::cache_streamed_mutation::read_from_underlying()::{lambda()#1}&&, cache::cache_streamed_mutation::read_from_underlying()::{lambda(mutation_fragment)#2}&&, cache::cache_streamed_mutation::read_from_underlying()::{lambda()#3}&&)::{lambda()#2}, seastar::future<> consume_mutation_fragments_until<{lambda()#1}, mutation_fragment, {lambda(mutation_fragment)#2}>({lambda()#3}, streamed_mutation, {lambda()#1}, mutation_fragment)::{lambda()#1}>(seastar::future<> consume_mutation_fragments_until<cache::cache_streamed_mutation::read_from_underlying()::{lambda()#1}, cache::cache_streamed_mutation::read_from_underlying()::{lambda(mutation_fragment)#2}, cache::cache_streamed_mutation::read_from_underlying()::{lambda()#3}>(streamed_mutation&, cache::cache_streamed_mutation::read_from_underlying()::{lambda()#1}&&, cache::cache_streamed_mutation::read_from_underlying()::{lambda(mutation_fragment)#2}&&, cache::cache_streamed_mutation::read_from_underlying()::{lambda()#3}&&)::{lambda()#2}, streamed_mutation, seastar::promise<>)::{lambda(seastar::future<>)#1}, seastar::future<> >(streamed_mutation)::{lambda(streamed_mutation)#1}>::run() at /usr/src/debug/scylla-2.0.rc2/seastar/core/future.hh:395
seastar::reactor::run_tasks(seastar::circular_buffer<std::unique_ptr<seastar::task, std::default_delete<seastar::task> >, std::allocator<std::unique_ptr<seastar::task, std::default_delete<seastar::task> > > >&) at /usr/src/debug/scylla-2.0.rc2/seastar/core/reactor.cc:2316
seastar::reactor::run() at /usr/src/debug/scylla-2.0.rc2/seastar/core/reactor.cc:2774
operator() at /usr/src/debug/scylla-2.0.rc2/seastar/core/reactor.cc:3707
std::function<void ()>::operator()() const at /opt/scylladb/include/c++/5.3.1/functional:2271
 (inlined by) seastar::posix_thread::start_routine(void*) at /usr/src/debug/scylla-2.0.rc2/seastar/core/posix.cc:52
?? ??:0

```

![read_stalls](https://user-images.githubusercontent.com/6995/29333851-3ec4a062-81fd-11e7-9999-e6a45a871ae9.png)

**Comment by tgrabiec** [comment] 2017-08-18 09:59
@pdziepak What kind of reads is scylla-bench issuing for this config?

**Comment by pdziepak** [comment] 2017-08-18 10:02
```
SELECT * FROM scylla_bench.test WHERE pk = ? AND ck >= ? LIMIT ?
```

The default limit is 1.

**Comment by tzach** [comment] 2017-08-21 07:30
@pdziepak is this a regression from 1.7?

**Comment by pdziepak** [comment] 2017-08-21 16:57
I don't know really what was going on. Note that at the backtrace doesn't really make sense since there is `std::_Function_handler<seastar::metrics::impl::metric_value (),...` near the top and then some cache-related stuff. Other captured backtraces look very similar (i.e. one metrics-related frame and then cache). I've double-checked that they were resolved against the correct binary.

What's even worse I couldn't reproduce it (and I followed exactly the same commands from zsh history). Most that I could get is one node acting weird, but no reported stalls even with the threshold reduced to 200ms.

The only thing that does happens is one node being different than the rest. It reports every few seconds the following error:
```
Aug 16 17:42:03 ip-172-30-0-39 scylla[42419]:  [shard 0] seastar - Exceptional future ignored: std::system_error (error system:32, Broken pipe), backtrace: 0x4f0123, 0x4f0181, 0x58a3af, 0x90f989, 0x4ecd4f, 0x54087a, 0x5c4fb4, 0x47524f, 0x7f5a8810eb14, 0x4e8dde
```
The backtrace translates to:
```
0x4f0123
0x4f0181
0x58a3af
0x90f989
0x4ecd4f
0x54087a
0x5c4fb4
0x47524f
0x7f6b9a983b14
0x4e8dde
seastar::current_backtrace() at /usr/src/debug/scylla-2.0.rc2/seastar/core/reactor.cc:3935
seastar::report_failed_future(std::__exception_ptr::exception_ptr) at ??:?
seastar::future<>::~future() at /usr/src/debug/scylla-2.0.rc2/seastar/core/future.hh:799
 (inlined by) std::_Head_base<1ul, seastar::future<>, false>::~_Head_base() at /opt/scylladb/include/c++/5.3.1/tuple:102
_ZN7seastar12continuationIZNS_6futureIISt5tupleIINS1_IIEEES3_EEEE4thenIZNS_5httpd10connection7processEvEUlS4_E_S3_EET0_OT_EUlSC_E_IS4_EE3runEv at ??:?
seastar::reactor::run_tasks(seastar::circular_buffer<std::unique_ptr<seastar::task, std::default_delete<seastar::task> >, std::allocator<std::unique_ptr<seastar::task, std::default_delete<seastar::task> > > >&) at ??:?
seastar::reactor::run() at ??:?
seastar::app_template::run_deprecated(int, char**, std::function<void ()>&&) at /usr/src/debug/scylla-2.0.rc2/seastar/core/app-template.cc:142
main at ??:?
?? ??:0
_start at ??:?
```

In this ran this is the yellow, noisy node:
![noisy_yellow_node](https://user-images.githubusercontent.com/6995/29530059-0fa17908-869a-11e7-9306-4b62113d2abb.png)

**Comment by avikivity** [comment] 2017-08-21 17:26
That's Prometheus. Looks like the response was so slow the prometheus server gave up and dropped the connection.

**Comment by avikivity** [comment] 2017-08-21 17:27
Try rc2, it has the Prometheus response split across many continuations.

**Comment by tgrabiec** [comment] 2017-08-21 20:32
@pdziepak Note that stall detector reports only 5 backtraces per minute, after which it silently stops reporting. I've been beaten by this.

**Comment by pdziepak** [comment] 2017-08-22 14:04
I'm running rc2 + my exception safety patches right now and I already see that broken pipes are still there. In this run they happen on all nodes (that's probably not rc1 vs. rc2 thing, but just non-determinism of these runs).

**Comment by tzach** [comment] 2017-08-27 11:04
@pdziepak  please open a new issue for the broken pipe problem

**Comment by slivne** [comment] 2017-08-28 07:40
@pdziepak did you open an issue - is the reproducer the same info you included above - how do we populate the data (the command has ```-mode=read```)

**Comment by pdziepak** [comment] 2017-08-29 10:36
I've opened #2738 with the description how the cluster was populated. The same workload was run when this problem first (and the only time so far) appeared.

**Comment by tzach** [comment] 2017-09-04 08:56
> I've opened #2738 with the description how the cluster was populated. The same workload was run when this problem first (and the only time so far) appeared.

So can we close this issue (#2698)? do we need more testing?

**Comment by slivne** [comment] 2017-09-13 07:36
in amnon's attempts to reproduce #2738 he did not hit this as well - closing this issue - we can reopen if we trigger it again.

**Closed by slivne** 2017-09-13 07:36 UTC
Labels: bug, high
