### ISSUE TITLE
test_query_failed_when_node_is_killed fails with: NoHostAvailable

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#10083] opened 2022-02-15 12:27 UTC
Starting from https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/1100/testReport/junit/cql_tests/TestMiscellaneousCQL/test_query_failed_when_node_is_killed/
Scylla version 755cec1199edbb50b81b03c97f5578bd0595e293

The test_query_failed_when_node_is_killed started failing when the the a query with cl=ONE, right after a node has been forcibly killed, fails with NoHostAvailable.

I tried adding `wait_for_others=True' for node.stop:
```python
diff --git a/cql_tests.py b/cql_tests.py
index ca9020d8..253b853e 100644
--- a/cql_tests.py
+++ b/cql_tests.py
@@ -631,7 +631,7 @@ class TestMiscellaneousCQL(CQLTester):
         cluster.flush()
 
         logger.debug(f"Stopping node (gently={stop_gently})")
-        node2.stop(gently=stop_gently)
+        node2.stop(gently=stop_gently, wait_other_notice=True)
 
         with self.patient_cql_cluster_session(node1, ks, exclusive=True) as session:
             logger.debug("Selecting with CL=ONE")
```

which didn't help.

And nodetool status at this stage shows:
```
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address     Load       Tokens       Owns    Host ID                               Rack
UN  127.0.87.1  768 KB     256          ?       ae98de0b-3bf3-4f31-8649-72ad47c84754  rack1
DN  127.0.87.2  836 KB     256          ?       502501e0-87c0-4246-9123-b235e31669bd  rack1
```

but still the query fails.

Apparently, adding a short, 1 second sleep, does help and the query passes,
so it seems that the advertised node status doesn't reflect its internal state.

**Comment by bhalevy** [comment] 2022-02-15 12:28
Since the query the test issues is `SELECT count(*)` I suspect this could be related to fe65122ccd40a2a3577121aebdb9a5b50deb4a90.

@havaker can you please look into this?

**Comment by bhalevy** [comment] 2022-02-15 14:35
The test passes reliably when changing `select count(*)` to `select *` as follows:
```python
diff --git a/cql_tests.py b/cql_tests.py
index ca9020d8..3a600f2a 100644
--- a/cql_tests.py
+++ b/cql_tests.py
@@ -623,21 +623,23 @@ class TestMiscellaneousCQL(CQLTester):
             f"CREATE TABLE {cf} (pk int, ck int, v text, PRIMARY KEY (pk, ck))")
 
         logger.debug("Inserting data...")
+        values = []
         for pk in range(10):
             for ck in range(100):
                 q = SimpleStatement(f"INSERT INTO {ks}.{cf} (pk, ck, v) VALUES ({pk}, {ck}, 'foo')",
                                     consistency_level=ConsistencyLevel.ALL)
+                values.append([pk, ck, 'foo'])
                 session.execute(q)
         cluster.flush()
 
         logger.debug(f"Stopping node (gently={stop_gently})")
-        node2.stop(gently=stop_gently)
+        node2.stop(gently=stop_gently, wait_other_notice=True)
 
         with self.patient_cql_cluster_session(node1, ks, exclusive=True) as session:
             logger.debug("Selecting with CL=ONE")
-            assert_one(session,
-                       f"SELECT count(*) from {ks}.{cf} BYPASS CACHE",
-                       [1000], cl=ConsistencyLevel.ONE)
+            assert_all(session,
+                       f"SELECT * from {ks}.{cf} BYPASS CACHE",
+                       cl=ConsistencyLevel.ONE, expected=values, ignore_order=True)
 
             logger.debug("Selecting with CL=QUORUM (expected to fail)")
```

This strengthen the theory that the root cause is fe65122.

**Comment by havaker** [comment] 2022-02-18 17:12
The fact that this test does not pass is definitely https://github.com/scylladb/scylla/commit/fe65122ccd40a2a3577121aebdb9a5b50deb4a90 's fault.

 In a `test_query_failed_when_node_is_killed` there is a `select count(*)` query with cl=ONE. Right after a node has been forcibly killed, this query was send. On the Scylla side, `count(*)` coordination layer chose to distribute received query execution to all nodes in the cluster. Since one node has been killed, query distribution has failed and the error was propagated to the client (error propagation is not incidental, [it's by-design](https://github.com/scylladb/scylla/pull/9209#issuecomment-1025161294)).

I don't know if it's better to change `count(*)` coordination logic, or to match the tests to the present behavior.

@psarna @avikivity any suggestions?

**Comment by nyh** [comment] 2022-02-20 08:25
> The fact that this test does not pass is definitely [fe65122](https://github.com/scylladb/scylla/commit/fe65122ccd40a2a3577121aebdb9a5b50deb4a90) 's fault.
> 
> In a `test_query_failed_when_node_is_killed` there is a `select count(*)` query with cl=ONE. Right after a node has been forcibly killed, this query was send to Scylla. On the server side, `count(*)` coordination layer chose to distribute received query execution to all nodes in the cluster. Since one node has been killed, query distribution has failed and the error was propagated to the client (error propagation is not incidental, [it's by-design](https://github.com/scylladb/scylla/pull/9209#issuecomment-1025161294)).

I think it depends whether the query failed because while of the nodes failed **while** it was being processed - of the query failed when started after one of the nodes had already gone down.

If it's the first case (node died in the middle of the query), I agree with Avi's sentiment in the comment you linked to, that it's a minor bug. However, I'd still consider it a bug, I would open an issue for it and fix it in the future - and importantly (in my view), I would like to have an xfailing/requiring (whatever terminology we use in dtest) test that consistently reproduces this bug.

However, if a `count(*)` doesn't work if a node has already, in the past, died - I think this is a bigger problem. It will mean that you can't run `count(*)` at all on a node where any one node is down, which isn't great for our high-availability story. Again, I think that we should have a test for this.

My recommendation regarding the tests is to split this test into two, or even three:

1. Since the original goal of this test was, to quote its comment, "Test that a select query with consistency_level=QUOROM        returns an Unavailable error properly when one out of two nodes is DOWN." I would change the test to use the simplest form of query we have - a point query (query a single row).
2. Then, we can have another test that does this with `SELECT count(*)`, aiming to test the special features of SELECT(*). As I noted above this test should perhaps even have different variants.
3. Finally do the same thing with a full scan (`SELECT *`), which is yet another code path.

If we do this split, we can find ourselves with some of the tests passing and some failing because of bugs (even if it's a know, acceptable, bug, we should still remember it exists).

By the way, I think we may have similar issues issues with normal scans (`SELECT *` instead of `SELECT count(*)`). I'm sure that `SELECT *` works if one of the nodes is down when it starts, but I'm not convinced that a running `SELECT *` can actually recover if one of the nodes go down **in the middle** of the scan. I had a chat about this with @eliransin once, and if I remember correctly (but please correct me if I'm wrong), we discovered that "speculative retry" is disabled for scans, so if Scylla sends a part of the scan to two nodes it thinks are alive - and then one of them dies - it won't try to send it to the third replica until a timeout occurs and kills the scan. But of course, we should test this case (this would be one of the tests I suggested above).
 
> I don't know if it's better to change `count(*)` coordination logic, or to match the tests to the present behavior.

If we're lucky enough to have a test that found a bug (even if we consider this bug very-low-severity and even acceptable), I don't think it's write to change the test to circumvent the bug :-) What I suggested above is to duplicate the test - one marked failing with the bug, and the other - without `count(*)` - passing.

**Comment by gleb-cloudius** [comment] 2022-02-20 08:29
I do not understand how the logic is different with regular select. It will also suppose to fail if a node the coordinator sends read command to dies before returning the result. May be the driver retries the page read internally so the failure is hidden from the user, but then how old count(*) implementation worked? It did not have the retry.

**Comment by havaker** [comment] 2022-02-22 15:48
> If you add 20s sleep after stopping node2 but before running the query, the test should pass.

I added the 20s sleep and re-ran the test. It passed.

**Comment by bhalevy** [comment] 2022-02-22 15:54
How did it pass before your change?

**Comment by bhalevy** [comment] 2022-02-22 15:54
Cc @asias

**Comment by havaker** [comment] 2022-02-22 16:05
> How did it pass before your change?

Perhaps the node to which the `count(*)` request was sent with `cl=ONE` did not need to communicate with the other - it read everything locally.

**Comment by haaawk** [comment] 2022-02-23 11:07
It's a nature of @havaker's change that now count(*) uses all nodes in the cluster that are alive and if any of them fails then the query fails. Before count(*) was like a regular query and with CL=ONE it required only one replica to be up.

**Comment by haaawk** [comment] 2022-02-23 11:07
@bhalevy

**Comment by bhalevy** [comment] 2022-02-23 13:04
> It's a nature of @havaker's change that now count(_) uses all nodes in the cluster that are alive and if any of them fails then the query fails. Before count(_) was like a regular query and with CL=ONE it required only one replica to be up.

I don't see how this fits the consistency level model.
We should be able to sustain node failures as long as we get enough replies to satisfy the query's consistency_level.
If the app wants `cl=ALL` it should explicit say so, otherwise I think that implying it just because it's a `count(*)` query is problematic.

**Comment by haaawk** [comment] 2022-02-23 13:09
> > It's a nature of @havaker's change that now count(_) uses all nodes in the cluster that are alive and if any of them fails then the query fails. Before count(_) was like a regular query and with CL=ONE it required only one replica to be up.
> 
> I don't see how this fits the consistency level model. We should be able to sustain node failures as long as we get enough replies to satisfy the query's consistency_level. If the app wants `cl=ALL` it should explicit say so, otherwise I think that implying it just because it's a `count(*)` query is problematic.

Please see @avikivity comment that @havaker has already linked above https://github.com/scylladb/scylla/pull/9209#issuecomment-1025161294

**Comment by gleb-cloudius** [comment] 2022-02-23 13:16
On Wed, Feb 23, 2022 at 05:04:25AM -0800, Benny Halevy wrote:
> > It's a nature of @havaker's change that now count(_) uses all nodes in the cluster that are alive and if any of them fails then the query fails. Before count(_) was like a regular query and with CL=ONE it required only one replica to be up.
> 
> I don't see how this fits the consistency level model.
> We should be able to sustain node failures as long as we get enough replies to satisfy the query's consistency_level.
Impossible without speculative retry even without the patch. The test
worked only because all nodes have all the data.

--
			Gleb.

**Comment by avikivity** [comment] 2022-02-23 20:23
> The fact that this test does not pass is definitely https://github.com/scylladb/scylla/commit/fe65122ccd40a2a3577121aebdb9a5b50deb4a90 's fault.
> 
>  In a `test_query_failed_when_node_is_killed` there is a `select count(*)` query with cl=ONE. Right after a node has been forcibly killed, this query was send to Scylla. On the server side, `count(*)` coordination layer chose to distribute received query execution to all nodes in the cluster. Since one node has been killed, query distribution has failed and the error was propagated to the client (error propagation is not incidental, [it's by-design](https://github.com/scylladb/scylla/pull/9209#issuecomment-1025161294)).
> 
> I don't know if it's better to change `count(*)` coordination logic, or to match the tests to the present behavior.
> 
> @psarna @avikivity any suggestions?

We could retry a failed forwarder call by targeting another owner of the vnode.

Note, SELECT count(*) is an OLAP query and so can be retried by the user too, it has no hard deadline. It's an edge case but we can add this retry to avoid an apparent (but not important) regression.

**Comment by havaker** [comment] 2022-02-23 23:13
I will follow @nyh's recommendation and split the failing test into two separate ones. They will differ in the type of query being executed - the first one will use a point query and the second will use `count(*)`.

I will also open an issue regarding the present behavior of `count(*)`. This will make it possible to add a `@pytest.mark.require` decorator to the failing test.

Then, following @avikivity's idea, I'll add retries to the `count(*)` coordination layer (as a fix for this future issue).

**Comment by bhalevy** [comment] 2022-04-27 06:56
@havaker anything else to be done or can this issue be closed with https://github.com/scylladb/scylla/issues/10131?

**Comment by havaker** [comment] 2022-04-29 13:22
@bhalevy I think it should be closed.

**Closed** 2022-04-29 16:43 UTC
Labels: dtest

**Comment by bhalevy** [comment] 2022-05-01 06:17
fe65122ccd40a2a3577121aebdb9a5b50deb4a90 is in maser (5.1.dev) only so no backport is needed at the moment.
