### ISSUE TITLE
JSON support to tuples and UDT

### ISSUE THREAD

**Issue by MMairajuddin** [scylladb/scylla#4512] opened 2019-05-28 20:38 UTC
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash): 3.0.6-0.20190503.bf68fae01
Cluster size: 5 nodes
OS (RHEL/CentOS/Ubuntu/AWS AMI): Centos 7.5

*Hardware details (for performance issues)*          Dell R640
Platform (physical/VM/cloud instance type/docker): Physical
Disks: SSD

Has this been fixed in the version of Scylla we are currently using? https://github.com/amoskong/scylla/commit/7a0408ad04c8b90b9363dffe756390122cf7f725

Error:

tuple_type_impl::from_json_object(const Json::Value&, cql_serialization_format) const not implemented 
^ error when we insert json

**Comment by MMairajuddin** [comment] 2019-06-12 20:58
any word on this?

**Comment by psarna** [comment] 2019-06-12 21:34
It's a duplicate of https://github.com/scylladb/scylla/issues/3708 - json support for tuples and udts is already merged.

**Comment by slivne** [comment] 2019-06-16 10:34
@MMairajuddin the fix will be part of 3.1 

Its hard for us to track private versions with private backports (it seems you are using one). 

while 3.1 is not yet out 3.1.0.rc1 has been announced and you can download it and check if 3.1 solves your issue - if not please provide schema and operation to reproduce and we will validate it 

closing this issue for now (assuming 3.1 solves your issue)

**Closed by slivne** 2019-06-16 10:34 UTC
