### ISSUE TITLE
New views not being populated after creation, not appearing in views_builds_in_progress (3.1RC2)

### ISSUE THREAD

**Issue by veramine** [scylladb/scylla#4795] opened 2019-08-02 22:40 UTC
Scylla version (or git commit hash): 3.1.0.rc2-0.20190616.7d14514b8
Cluster size: 1  
OS (RHEL/CentOS/Ubuntu/AWS AMI): Ubuntu 16.04.5 LTS

I have been testing 3.1 RC2 and it has been working fine.  But I created a new view today and it is not being populated.  I went to check its status in the system.views_builds_in_progress table and I don't see it at all.  It does appear in the journalctl log.  I'm not sure the best way to debug.

Here is the table definition:

```
CREATE TABLE veraminetest.triggerinstances_bytriggerlabel (
    customerid int,
    triggerlabel text,
    eventtimeuuid timeuuid,
    hostid int,
    hostname text,
    matchstrings set<text>,
    pid int,
    processbasename text,
    processguid uuid,
    triggerlevel text,
    usersid text,
    userstring text,
    PRIMARY KEY ((customerid, triggerlabel), eventtimeuuid)
) WITH CLUSTERING ORDER BY (eventtimeuuid DESC)
    AND bloom_filter_fp_chance = 0.01
    AND caching = {'keys': 'ALL', 'rows_per_partition': 'ALL'}
    AND comment = ''
    AND compaction = {'class': 'SizeTieredCompactionStrategy'}
    AND compression = {'sstable_compression': 'org.apache.cassandra.io.compress.LZ4Compressor'}
    AND crc_check_chance = 1.0
    AND dclocal_read_repair_chance = 0.1
    AND default_time_to_live = 0
    AND gc_grace_seconds = 864000
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair_chance = 0.0
    AND speculative_retry = '99.0PERCENTILE';

CREATE MATERIALIZED VIEW veraminetest.triggerinstances_byhostid AS
    SELECT *
    FROM veraminetest.triggerinstances_bytriggerlabel
    WHERE customerid IS NOT null AND triggerlabel IS NOT null AND eventtimeuuid IS NOT null AND hostid IS NOT null
    PRIMARY KEY ((customerid, hostid, triggerlabel), eventtimeuuid)
    WITH CLUSTERING ORDER BY (eventtimeuuid ASC)
    AND bloom_filter_fp_chance = 0.01
    AND caching = {'keys': 'ALL', 'rows_per_partition': 'ALL'}
    AND comment = ''
    AND compaction = {'class': 'SizeTieredCompactionStrategy'}
    AND compression = {'sstable_compression': 'org.apache.cassandra.io.compress.LZ4Compressor'}
    AND crc_check_chance = 1.0
    AND dclocal_read_repair_chance = 0.1
    AND default_time_to_live = 0
    AND gc_grace_seconds = 864000
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair_chance = 0.0
    AND speculative_retry = '99.0PERCENTILE';

CREATE MATERIALIZED VIEW veraminetest.triggerinstances_byusersid AS
    SELECT *
    FROM veraminetest.triggerinstances_bytriggerlabel
    WHERE customerid IS NOT null AND triggerlabel IS NOT null AND eventtimeuuid IS NOT null AND usersid IS NOT null
    PRIMARY KEY ((customerid, usersid, triggerlabel), eventtimeuuid)
    WITH CLUSTERING ORDER BY (eventtimeuuid ASC)
    AND bloom_filter_fp_chance = 0.01
    AND caching = {'keys': 'ALL', 'rows_per_partition': 'ALL'}
    AND comment = ''
    AND compaction = {'class': 'SizeTieredCompactionStrategy'}
    AND compression = {'sstable_compression': 'org.apache.cassandra.io.compress.LZ4Compressor'}
    AND crc_check_chance = 1.0
    AND dclocal_read_repair_chance = 0.1
    AND default_time_to_live = 0
    AND gc_grace_seconds = 864000
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair_chance = 0.0
    AND speculative_retry = '99.0PERCENTILE';
```

Here is the initial view that I built prior to inserting any data:

```
cqlsh:veraminetest> select customerid, triggerlabel, eventtimeuuid, usersid from triggerinstances_byusersid;

 customerid | triggerlabel                   | eventtimeuuid                        | usersid
------------+--------------------------------+--------------------------------------+------------------------------------------------
          1 | Grievance | Motivational cause | ff973080-b31e-11e9-9073-d050996434d1 | S-1-5-21-3146450648-2696432051-1050068965-1000
          1 | Grievance | Motivational cause | ff973080-b31e-11e9-9074-d050996434d1 | S-1-5-21-3146450648-2696432051-1050068965-1000
          1 | Grievance | Motivational cause | ff973080-b31e-11e9-9075-d050996434d1 | S-1-5-21-3146450648-2696432051-1050068965-1000
          1 | Grievance | Motivational cause | ff973080-b31e-11e9-9076-d050996434d1 | S-1-5-21-3146450648-2696432051-1050068965-1000

(4 rows)
```

Here are the applicable columns from the base table for the new view:
```
cqlsh:veraminetest> select customerid, hostid, triggerlabel, eventtimeuuid from triggerinstances_bytriggerlabel;

 customerid | hostid | triggerlabel                   | eventtimeuuid
------------+--------+--------------------------------+--------------------------------------
          1 |  54677 | Grievance | Motivational cause | ff973080-b31e-11e9-9076-d050996434d1
          1 |  54677 | Grievance | Motivational cause | ff973080-b31e-11e9-9075-d050996434d1
          1 |  54677 | Grievance | Motivational cause | ff973080-b31e-11e9-9074-d050996434d1
          1 |  54677 | Grievance | Motivational cause | ff973080-b31e-11e9-9073-d050996434d1

(4 rows)
```

But notice there are no rows in the view:
```
cqlsh:veraminetest> select customerid, hostid, triggerlabel, eventtimeuuid from triggerinstances_byhostid;

 customerid | hostid | triggerlabel | eventtimeuuid
------------+--------+--------------+---------------

(0 rows)
```

I then wrote three more rows to the base table and all three of those rows showed up in the view but the four previous rows haven't yet:
```
cqlsh:veraminetest> select customerid, hostid, triggerlabel, eventtimeuuid from triggerinstances_bytriggerlabel;

 customerid | hostid | triggerlabel                   | eventtimeuuid
------------+--------+--------------------------------+--------------------------------------
          1 |  54677 | Grievance | Motivational cause | 8fceb300-b575-11e9-9079-d050996434d1
          1 |  54677 | Grievance | Motivational cause | 8fceb300-b575-11e9-9078-d050996434d1
          1 |  54677 | Grievance | Motivational cause | 8fceb300-b575-11e9-9077-d050996434d1
          1 |  54677 | Grievance | Motivational cause | ff973080-b31e-11e9-9076-d050996434d1
          1 |  54677 | Grievance | Motivational cause | ff973080-b31e-11e9-9075-d050996434d1
          1 |  54677 | Grievance | Motivational cause | ff973080-b31e-11e9-9074-d050996434d1
          1 |  54677 | Grievance | Motivational cause | ff973080-b31e-11e9-9073-d050996434d1

(7 rows)
cqlsh:veraminetest> select customerid, hostid, triggerlabel, eventtimeuuid from triggerinstances_byhostid;

 customerid | hostid | triggerlabel                   | eventtimeuuid
------------+--------+--------------------------------+--------------------------------------
          1 |  54677 | Grievance | Motivational cause | 8fceb300-b575-11e9-9077-d050996434d1
          1 |  54677 | Grievance | Motivational cause | 8fceb300-b575-11e9-9078-d050996434d1
          1 |  54677 | Grievance | Motivational cause | 8fceb300-b575-11e9-9079-d050996434d1

(3 rows)
```

I see some old views in the views_builds_in_progress table but I don't see this new view, which makes me think Scylla believes the view is already built.  (understandably, it was likely quick since there were only 4 rows in the base table at the time of view creation.
```
cqlsh:veraminetest> select * from system.views_builds_in_progress ;

 keyspace_name | view_name                      | generation_number | last_token
---------------+--------------------------------+-------------------+--------------------
  veraminetest | processes_by_parentprocessguid |                 0 | 869180472474624860
  veraminetest |          processes_by_protopid |                 0 | 869180472474624860
  veraminetest |   processes_protopid_idx_index |                 0 | 869180472474624860
  veraminetest | processexittime_by_processguid |                 0 | 869180472474624860

(4 rows)
```

Here is the recent output from journalctl.  I had originally deployed 3.1 RC1 to this table which corrupted one of the tables explaining the error there but otherwise it seems ok.

```
Aug 02 15:05:12 services scylla.bin[20862]:  [shard 1] migration_manager - Create new ColumnFamily: org.apache.cassandra.config.CFMetaData@0x601035d74e00[cfId=9969f220-b571-11e9-a6a1-000000000001,ksName=veraminetest,cfName=triggerbuckets_byhostid,cfType=Standard,comparator=org.apache.cassandra.db.marshal.CompositeType(org.apache.cassandra.db.marshal.UTF8Type,org.apache.cassandra.db.marshal.UTF8Type,org.apache.cassandra.db.marshal.UTF8Type),comment=,readRepairChance=0,dcLocalReadRepairChance=0.1,gcGraceSeconds=864000,keyValidator=org.apache.cassandra.db.marshal.CompositeType(org.apache.cassandra.db.marshal.Int32Type, org.apache.cassandra.db.marshal.Int32Type),minCompactionThreshold=4,maxCompactionThreshold=32,columnMetadata=[ColumnDefinition{name=customerid, type=org.apache.cassandra.db.marshal.Int32Type, kind=PARTITION_KEY, componentIndex=0, droppedAt=-9223372036854775808}, ColumnDefinition{name=hostid, type=org.apache.cassandra.db.marshal.Int32Type, kind=PARTITION_KEY, componentIndex=1, droppedAt=-9223372036854775808}, ColumnDefinition{name=triggerlabel, type=org.apache.cassandra.db.marshal.UTF8Type, kind=CLUSTERING_COLUMN, componentIndex=0, droppedAt=-9223372036854775808}, ColumnDefinition{name=triggerlevel, type=org.apache.cassandra.db.marshal.UTF8Type, kind=CLUSTERING_COLUMN, componentIndex=1, droppedAt=-9223372036854775808}, ColumnDefinition{name=firstseen, type=org.apache.cassandra.db.marshal.TimestampType, kind=REGULAR, componentIndex=null, droppedAt=-9223372036854775808}, ColumnDefinition{name=lastseen, type=org.apache.cassandra.db.marshal.TimestampType, kind=REGULAR, componentIndex=null, droppedAt=-9223372036854775808}, ColumnDefinition{name=portalstate1, type=org.apache.cassandra.db.marshal.UTF8Type, kind=REGULAR, componentIndex=null, droppedAt=-9223372036854775808}, ColumnDefinition{name=portalstate2, type=org.apache.cassandra.db.marshal.UTF8Type, kind=REGULAR, componentIndex=null, droppedAt=-9223372036854775808}, ColumnDefinition{name=triggerdescription, type=org.apache.cassandra.db.marshal.UTF8Type, kind=REGULAR, componentIndex=null, droppedAt=-9223372036854775808}],compactionStrategyClass=class org.apache.cassandra.db.compaction.SizeTieredCompactionStrategy,compactionStrategyOptions={enabled=true},compressionParameters={sstable_compression=org.apache.cassandra.io.compress.LZ4Compressor},bloomFilterFpChance=0.01,memtableFlushPeriod=0,caching={"keys":"ALL","rows_per_partition":"ALL"},defaultTimeToLive=0,minIndexInterval=128,maxIndexInterval=2048,speculativeRetry=99.0PERCENTILE,triggers=[],isDense=false,version=9969f221-b571-11e9-a6a1-000000000001,droppedColumns={},collections={},indices={}]
Aug 02 15:05:12 services scylla.bin[20862]:  [shard 4] compaction - Compacting [/var/lib/scylla/data/system_schema/indexes-0feb57ac311f382fba6d9024d305702f/mc-5692-big-Data.db:level=0, /var/lib/scylla/data/system_schema/indexes-0feb57ac311f382fba6d9024d305702f/mc-5686-big-Data.db:level=0, ]
Aug 02 15:05:12 services scylla.bin[20862]:  [shard 4] compaction - Compacting [/var/lib/scylla/data/system_schema/columns-24101c25a2ae3af787c1b40ee1aca33f/mc-9220-big-Data.db:level=0, /var/lib/scylla/data/system_schema/columns-24101c25a2ae3af787c1b40ee1aca33f/mc-9214-big-Data.db:level=0, ]
Aug 02 15:05:12 services scylla.bin[20862]:  [shard 4] compaction - Compacting [/var/lib/scylla/data/system_schema/scylla_tables-5d912ff1f7593665b2c88042ab5103dd/mc-412-big-Data.db:level=0, /var/lib/scylla/data/system_schema/scylla_tables-5d912ff1f7593665b2c88042ab5103dd/mc-406-big-Data.db:level=0, ]
Aug 02 15:05:12 services scylla.bin[20862]:  [shard 4] compaction - Compacting [/var/lib/scylla/data/system_schema/dropped_columns-5e7583b5f3f43af19a39b7e1d6f5f11f/mc-7612-big-Data.db:level=0, /var/lib/scylla/data/system_schema/dropped_columns-5e7583b5f3f43af19a39b7e1d6f5f11f/mc-7606-big-Data.db:level=0, ]
Aug 02 15:05:12 services scylla.bin[20862]:  [shard 4] compaction - Compacting [/var/lib/scylla/data/system_schema/keyspaces-abac5682dea631c5b535b3d6cffd0fb6/mc-9430-big-Data.db:level=0, /var/lib/scylla/data/system_schema/keyspaces-abac5682dea631c5b535b3d6cffd0fb6/mc-9424-big-Data.db:level=0, ]
Aug 02 15:05:12 services scylla.bin[20862]:  [shard 4] compaction - Compacting [/var/lib/scylla/data/system_schema/tables-afddfb9dbc1e30688056eed6c302ba09/mc-8374-big-Data.db:level=0, /var/lib/scylla/data/system_schema/tables-afddfb9dbc1e30688056eed6c302ba09/mc-8368-big-Data.db:level=0, ]
Aug 02 15:05:12 services scylla.bin[20862]:  [shard 1] schema_tables - Creating veraminetest.triggerbuckets_byhostid id=9969f220-b571-11e9-a6a1-000000000001 version=55327260-8e96-3bfc-8188-9116c43798de
Aug 02 15:05:13 services scylla.bin[20862]:  [shard 4] compaction - Compacted 2 sstables to [/var/lib/scylla/data/system_schema/indexes-0feb57ac311f382fba6d9024d305702f/mc-5698-big-Data.db:level=0, ]. 11945 bytes to 6671 (~55% of original) in 483ms = 0.01MB/s. ~256 total partitions merged to 1.
Aug 02 15:05:13 services scylla.bin[20862]:  [shard 1] database - Schema version changed to 928f2f2c-a56c-3d24-8318-18ef047c5e74
Aug 02 15:05:13 services scylla.bin[20862]:  [shard 4] compaction - Compacted 2 sstables to [/var/lib/scylla/data/system_schema/columns-24101c25a2ae3af787c1b40ee1aca33f/mc-9226-big-Data.db:level=0, ]. 215816 bytes to 210312 (~97% of original) in 539ms = 0.37MB/s. ~256 total partitions merged to 3.
Aug 02 15:05:13 services scylla.bin[20862]:  [shard 4] compaction - Compacted 2 sstables to [/var/lib/scylla/data/system_schema/scylla_tables-5d912ff1f7593665b2c88042ab5103dd/mc-418-big-Data.db:level=0, ]. 10939 bytes to 5832 (~53% of original) in 522ms = 0.01MB/s. ~256 total partitions merged to 1.
Aug 02 15:05:13 services scylla.bin[20862]:  [shard 4] compaction - Compacted 2 sstables to [/var/lib/scylla/data/system_schema/dropped_columns-5e7583b5f3f43af19a39b7e1d6f5f11f/mc-7618-big-Data.db:level=0, ]. 11009 bytes to 5852 (~53% of original) in 529ms = 0.01MB/s. ~256 total partitions merged to 1.
Aug 02 15:05:13 services scylla.bin[20862]:  [shard 4] compaction - Compacted 2 sstables to [/var/lib/scylla/data/system_schema/keyspaces-abac5682dea631c5b535b3d6cffd0fb6/mc-9436-big-Data.db:level=0, ]. 63989 bytes to 58718 (~91% of original) in 490ms = 0.11MB/s. ~256 total partitions merged to 3.
Aug 02 15:05:13 services scylla.bin[20862]:  [shard 4] compaction - Compacted 2 sstables to [/var/lib/scylla/data/system_schema/tables-afddfb9dbc1e30688056eed6c302ba09/mc-8380-big-Data.db:level=0, ]. 100959 bytes to 94188 (~93% of original) in 448ms = 0.20MB/s. ~256 total partitions merged to 3.
Aug 02 15:05:18 services scylla.bin[20862]:  [shard 1] migration_manager - Create new view: org.apache.cassandra.config.CFMetaData@0x601035d74e00[cfId=9d70d460-b571-11e9-a6a1-000000000001,ksName=veraminetest,cfName=triggerinstances_byhostid,cfType=Standard,comparator=org.apache.cassandra.db.marshal.CompositeType(org.apache.cassandra.db.marshal.TimeUUIDType,org.apache.cassandra.db.marshal.UTF8Type,org.apache.cassandra.db.marshal.ColumnToCollectionType(6d61746368737472696e6773:org.apache.cassandra.db.marshal.SetType(org.apache.cassandra.db.marshal.UTF8Type))),comment=,readRepairChance=0,dcLocalReadRepairChance=0.1,gcGraceSeconds=864000,keyValidator=org.apache.cassandra.db.marshal.CompositeType(org.apache.cassandra.db.marshal.Int32Type, org.apache.cassandra.db.marshal.Int32Type, org.apache.cassandra.db.marshal.UTF8Type),minCompactionThreshold=4,maxCompactionThreshold=32,columnMetadata=[ColumnDefinition{name=customerid, type=org.apache.cassandra.db.marshal.Int32Type, kind=PARTITION_KEY, componentIndex=0, droppedAt=-9223372036854775808}, ColumnDefinition{name=hostid, type=org.apache.cassandra.db.marshal.Int32Type, kind=PARTITION_KEY, componentIndex=1, droppedAt=-9223372036854775808}, ColumnDefinition{name=triggerlabel, type=org.apache.cassandra.db.marshal.UTF8Type, kind=PARTITION_KEY, componentIndex=2, droppedAt=-9223372036854775808}, ColumnDefinition{name=eventtimeuuid, type=org.apache.cassandra.db.marshal.TimeUUIDType, kind=CLUSTERING_COLUMN, componentIndex=0, droppedAt=-9223372036854775808}, ColumnDefinition{name=hostname, type=org.apache.cassandra.db.marshal.UTF8Type, kind=REGULAR, componentIndex=null, droppedAt=-9223372036854775808}, ColumnDefinition{name=matchstrings, type=org.apache.cassandra.db.marshal.SetType(org.apache.cassandra.db.marshal.UTF8Type), kind=REGULAR, componentIndex=null, droppedAt=-9223372036854775808}, ColumnDefinition{name=pid, type=org.apache.cassandra.db.marshal.Int32Type, kind=REGULAR, componentIndex=null, droppedAt=-9223372036854775808}, ColumnDefinition{name=processbasename, type=org.apache.cassandra.db.marshal.UTF8Type, kind=REGULAR, componentIndex=null, droppedAt=-9223372036854775808}, ColumnDefinition{name=processguid, type=org.apache.cassandra.db.marshal.UUIDType, kind=REGULAR, componentIndex=null, droppedAt=-9223372036854775808}, ColumnDefinition{name=triggerlevel, type=org.apache.cassandra.db.marshal.UTF8Type, kind=REGULAR, componentIndex=null, droppedAt=-9223372036854775808}, ColumnDefinition{name=usersid, type=org.apache.cassandra.db.marshal.UTF8Type, kind=REGULAR, componentIndex=null, droppedAt=-9223372036854775808}, ColumnDefinition{name=userstring, type=org.apache.cassandra.db.marshal.UTF8Type, kind=REGULAR, componentIndex=null, droppedAt=-9223372036854775808}],compactionStrategyClass=class org.apache.cassandra.db.compaction.SizeTieredCompactionStrategy,compactionStrategyOptions={enabled=true},compressionParameters={sstable_compression=org.apache.cassandra.io.compress.LZ4Compressor},bloomFilterFpChance=0.01,memtableFlushPeriod=0,caching={"keys":"ALL","rows_per_partition":"ALL"},defaultTimeToLive=0,minIndexInterval=128,maxIndexInterval=2048,speculativeRetry=99.0PERCENTILE,triggers=[],isDense=false,version=9d70d461-b571-11e9-a6a1-000000000001,droppedColumns={},collections={6d61746368737472696e6773 : org.apache.cassandra.db.marshal.SetType(org.apache.cassandra.db.marshal.UTF8Type)},indices={}, viewInfo=ViewInfo{baseTableId=245b6bc0-b31f-11e9-b486-000000000003, baseTableName=triggerinstances_bytriggerlabel, includeAllColumns=true, whereClause=customerid IS NOT null AND triggerlabel IS NOT null AND eventtimeuuid IS NOT null AND hostid IS NOT null}]
Aug 02 15:05:19 services scylla.bin[20862]:  [shard 4] compaction - Compacting [/var/lib/scylla/data/system_schema/view_virtual_columns-08843b6345dc3be29798a0418295cfaa/mc-712-big-Data.db:level=0, /var/lib/scylla/data/system_schema/view_virtual_columns-08843b6345dc3be29798a0418295cfaa/mc-706-big-Data.db:level=0, ]
Aug 02 15:05:19 services scylla.bin[20862]:  [shard 4] compaction - Compacting [/var/lib/scylla/data/system_schema/indexes-0feb57ac311f382fba6d9024d305702f/mc-5704-big-Data.db:level=0, /var/lib/scylla/data/system_schema/indexes-0feb57ac311f382fba6d9024d305702f/mc-5698-big-Data.db:level=0, ]
Aug 02 15:05:19 services scylla.bin[20862]:  [shard 4] compaction - Compacting [/var/lib/scylla/data/system_schema/columns-24101c25a2ae3af787c1b40ee1aca33f/mc-9232-big-Data.db:level=0, /var/lib/scylla/data/system_schema/columns-24101c25a2ae3af787c1b40ee1aca33f/mc-9226-big-Data.db:level=0, ]
Aug 02 15:05:19 services scylla.bin[20862]:  [shard 4] compaction - Compacting [/var/lib/scylla/data/system_schema/scylla_tables-5d912ff1f7593665b2c88042ab5103dd/mc-424-big-Data.db:level=0, /var/lib/scylla/data/system_schema/scylla_tables-5d912ff1f7593665b2c88042ab5103dd/mc-418-big-Data.db:level=0, ]
Aug 02 15:05:19 services scylla.bin[20862]:  [shard 4] compaction - Compacting [/var/lib/scylla/data/system_schema/dropped_columns-5e7583b5f3f43af19a39b7e1d6f5f11f/mc-7624-big-Data.db:level=0, /var/lib/scylla/data/system_schema/dropped_columns-5e7583b5f3f43af19a39b7e1d6f5f11f/mc-7618-big-Data.db:level=0, ]
Aug 02 15:05:19 services scylla.bin[20862]:  [shard 4] compaction - Compacting [/var/lib/scylla/data/system_schema/views-9786ac1cdd583201a7cdad556410c985/mc-3994-big-Data.db:level=0, /var/lib/scylla/data/system_schema/views-9786ac1cdd583201a7cdad556410c985/mc-3988-big-Data.db:level=0, ]
Aug 02 15:05:20 services scylla.bin[20862]:  [shard 4] compaction - Compacting [/var/lib/scylla/data/system_schema/keyspaces-abac5682dea631c5b535b3d6cffd0fb6/mc-9442-big-Data.db:level=0, /var/lib/scylla/data/system_schema/keyspaces-abac5682dea631c5b535b3d6cffd0fb6/mc-9436-big-Data.db:level=0, ]
Aug 02 15:05:20 services scylla.bin[20862]:  [shard 4] compaction - Compacted 2 sstables to [/var/lib/scylla/data/system_schema/view_virtual_columns-08843b6345dc3be29798a0418295cfaa/mc-718-big-Data.db:level=0, ]. 11303 bytes to 5990 (~52% of original) in 664ms = 0.01MB/s. ~256 total partitions merged to 1.
Aug 02 15:05:20 services scylla.bin[20862]:  [shard 4] compaction - Compacting [/var/lib/scylla/data/system_schema/tables-afddfb9dbc1e30688056eed6c302ba09/mc-8386-big-Data.db:level=0, /var/lib/scylla/data/system_schema/tables-afddfb9dbc1e30688056eed6c302ba09/mc-8380-big-Data.db:level=0, ]
Aug 02 15:05:20 services scylla.bin[20862]:  [shard 4] compaction - Compacted 2 sstables to [/var/lib/scylla/data/system_schema/indexes-0feb57ac311f382fba6d9024d305702f/mc-5710-big-Data.db:level=0, ]. 11945 bytes to 6671 (~55% of original) in 710ms = 0.01MB/s. ~256 total partitions merged to 1.
Aug 02 15:05:20 services scylla.bin[20862]:  [shard 1] schema_tables - Altering veraminetest.triggerinstances_bytriggerlabel id=245b6bc0-b31f-11e9-b486-000000000003 version=9e124347-ed9e-3d73-ae73-ed1af41c782e
Aug 02 15:05:20 services scylla.bin[20862]:  [shard 1] schema_tables - Creating veraminetest.triggerinstances_byhostid id=9d70d460-b571-11e9-a6a1-000000000001 version=3faba8ee-46df-33fc-9d6c-c342129dbd75
Aug 02 15:05:20 services scylla.bin[20862]:  [shard 1] query_processor - Column definitions for veraminetest.triggerinstances_bytriggerlabel changed, invalidating related prepared statements
Aug 02 15:05:20 services scylla.bin[20862]:  [shard 5] query_processor - Column definitions for veraminetest.triggerinstances_bytriggerlabel changed, invalidating related prepared statements
Aug 02 15:05:20 services scylla.bin[20862]:  [shard 3] query_processor - Column definitions for veraminetest.triggerinstances_bytriggerlabel changed, invalidating related prepared statements
Aug 02 15:05:20 services scylla.bin[20862]:  [shard 2] query_processor - Column definitions for veraminetest.triggerinstances_bytriggerlabel changed, invalidating related prepared statements
Aug 02 15:05:20 services scylla.bin[20862]:  [shard 0] query_processor - Column definitions for veraminetest.triggerinstances_bytriggerlabel changed, invalidating related prepared statements
Aug 02 15:05:20 services scylla.bin[20862]:  [shard 4] compaction - Compacted 2 sstables to [/var/lib/scylla/data/system_schema/columns-24101c25a2ae3af787c1b40ee1aca33f/mc-9238-big-Data.db:level=0, ]. 216351 bytes to 210952 (~97% of original) in 762ms = 0.26MB/s. ~256 total partitions merged to 3.
Aug 02 15:05:20 services scylla.bin[20862]:  [shard 4] query_processor - Column definitions for veraminetest.triggerinstances_bytriggerlabel changed, invalidating related prepared statements
Aug 02 15:05:20 services scylla.bin[20862]:  [shard 4] compaction - Compacted 2 sstables to [/var/lib/scylla/data/system_schema/scylla_tables-5d912ff1f7593665b2c88042ab5103dd/mc-430-big-Data.db:level=0, ]. 11012 bytes to 5871 (~53% of original) in 651ms = 0.01MB/s. ~256 total partitions merged to 1.
Aug 02 15:05:20 services scylla.bin[20862]:  [shard 1] database - Schema version changed to d62623d3-3830-3ba4-b168-39d0c26a40c7
Aug 02 15:05:20 services scylla.bin[20862]:  [shard 4] compaction - Compacted 2 sstables to [/var/lib/scylla/data/system_schema/dropped_columns-5e7583b5f3f43af19a39b7e1d6f5f11f/mc-7630-big-Data.db:level=0, ]. 11009 bytes to 5852 (~53% of original) in 638ms = 0.01MB/s. ~256 total partitions merged to 1.
Aug 02 15:05:20 services scylla.bin[20862]:  [shard 4] compaction - Compacted 2 sstables to [/var/lib/scylla/data/system_schema/views-9786ac1cdd583201a7cdad556410c985/mc-4000-big-Data.db:level=0, ]. 31671 bytes to 24729 (~78% of original) in 604ms = 0.04MB/s. ~256 total partitions merged to 1.
Aug 02 15:05:20 services scylla.bin[20862]:  [shard 4] compaction - Compacted 2 sstables to [/var/lib/scylla/data/system_schema/keyspaces-abac5682dea631c5b535b3d6cffd0fb6/mc-9448-big-Data.db:level=0, ]. 63989 bytes to 58718 (~91% of original) in 541ms = 0.10MB/s. ~256 total partitions merged to 3.
Aug 02 15:05:20 services scylla.bin[20862]:  [shard 4] compaction - Compacted 2 sstables to [/var/lib/scylla/data/system_schema/tables-afddfb9dbc1e30688056eed6c302ba09/mc-8392-big-Data.db:level=0, ]. 101136 bytes to 94187 (~93% of original) in 500ms = 0.18MB/s. ~256 total partitions merged to 3.
Aug 02 15:09:22 services scylla.bin[20862]:  [shard 0] storage_proxy - Exception when communicating with 127.0.0.1: std::runtime_error (SSTable reader found an exception when reading sstable /var/lib/scylla/data/veraminetest/detectionbuckets-0147b5d004fb11e9a668000000000002/mc-3807-big-Data.db : sstables::malformed_sstable_exception (end of input, but not end of partition))
```

**Comment by bhalevy** [comment] 2019-08-04 06:40
Cc @eliransin

**Comment by bhalevy** [comment] 2019-08-04 06:54
@veramine can you please upload the complete node log to help understand the issue with mc-3807-big-Data.db?

@tgrabiec could the malformed sstable have been caused by #4789?

**Comment by nyh** [comment] 2019-08-04 10:23
I'm starting to look at this issue. @veramine if I understand correctly, this issue happened once and not a situation you could easily recreate (i.e., normally view builds do work for you, right?)
@veramine, can you please `system.built_views` to see if Scylla thinks it already completed the build?

Could the triggerinstances_bytriggerlabel table also have some corrupted sstables, or was this problem specific just to "detectionbucket"? If this table has problems too, it may explain why the view build process, which needs to read all the data from the base table, could fail and never complete.

You may also see in the log file messages (if the default log level "info" is in effect) messages about "Resuming to build view", "Building view", or warnings about "Error executing build", "Failed to update materialized view bookkeeping", etc. If you use `--loger-log-level view=debug` you'll get additional messages about individual buiild steps ("Completed build step", "Shard finished building view"). It will be interesting to know if Scylla thinks it completely built the view, or knows it failed somewhere.

**Comment by slivne** [comment] 2019-08-14 12:13
@veramine anyway you can help with this one - or is the history info long gone :)

**Comment by veramine** [comment] 2019-08-18 06:15
Hey guys, we found disk corruption and I/O errors on this node.  We ended up destroying the RAID0 configuration and rebuilding it with one fewer physical drive due to the pervasive I/O errors.  Its very possible that the data was not showing up because the data could not be read from disk.  Its probably not actual issue.

**Comment by slivne** [comment] 2019-08-18 06:56
@veramine thanks - closing this

**Closed by slivne** 2019-08-18 06:56 UTC
Labels: bug, high
