### ISSUE TITLE
Allow to SELECT NULL values

### ISSUE THREAD

**Issue by ultrabug** [scylladb/scylla#10180] opened 2022-03-08 08:31 UTC
Hello,

As discussed with @tzach I'd like to fill a feature request for ScyllaDB CQL.

Feature : allow queries to select columns with a NULL values

```
scylla@cqlsh:test> SELECT * FROM table ;

 id | up
----+------
  2 | null

(1 rows)
```

I'd like to be able to add WHERE conditions on `up IS NULL` (or whatever the syntax)

Use case : we often have tables where we need to both be able to filter from a field and at the same time check for it being initialized or not.

Maybe it's not the best use case but think of a table where you want to select rows of things that "have not been updated", you could have a "updated_at" timestamp which could be null until the row has been updated. Selecting those rows with IS NULL would be handy.

That's our experience in developing web apps backed by Scylla.

Thanks for considering it

**Comment by nyh** [comment] 2022-03-08 09:41
This turns out to be a frequent request - I opened #8517 last year, which also lists 3 other older issues, and explains why indeed "IS NULL" is a better syntax than "= NULL" that some users requested.

So closing as a duplicate of #8517, and will add your request there.

**Closed by nyh** 2022-03-08 09:41 UTC
Labels: enhancement, User Request, CQL
