### ISSUE TITLE
Executing lots of schema alters concurrently can lead to dropped alters

### ISSUE THREAD

**Issue by alecco** [scylladb/scylla#10655] opened 2022-05-24 20:21 UTC
When executing concurrent alter tables and indexing of a different table, some dropped columns show up afterwards even after waiting for 20 seconds to let schema changes settle.

This only happens without Raft enabled. Once Raft is enabled the issue goes away.

[Cassandra: Executing lots of schema alters concurrently can lead to dropped alters
 #10250](https://issues.apache.org/jira/browse/CASSANDRA-10250)

**Comment by avikivity** [comment] 2022-05-24 20:42
Duplicate of #1207

**Closed by avikivity** 2022-05-24 20:42 UTC
Labels: raft
