### ISSUE TITLE
'nodetool refresh'  has been running for 2 days on one node

### ISSUE THREAD

**Issue by aleksbykov** [scylladb/scylla#8599] opened 2021-05-06 17:40 UTC
Test: `longevity-200gb-48h`
Test name: `longevity_test.LongevityTest.test_custom_time`
Test id: `69f71bbe-3617-4bf3-bc73-7ff028645a74`
Test config file(s):
- [longevity-200GB-48h-verifier-LimitedMonkey-tls.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/162e8df658f9f31dbfac1463d9bf6e74dde3b88f/test-cases/longevity/longevity-200GB-48h-verifier-LimitedMonkey-tls.yaml)

*Installation details*
Kernel version: `5.4.0-1035-aws`
Scylla version (or git commit hash): `4.6.dev-0.20210429.0e8818f6a`
Cluster size: 4 nodes (i3.4xlarge)
Scylla running with shards number (live nodes):
   longevity-200gb-48h-verify-limited--db-node-69f71bbe-1 (13.51.156.167 | 10.0.2.11): 14 shards
   longevity-200gb-48h-verify-limited--db-node-69f71bbe-2 (13.51.48.4 | 10.0.0.93): 14 shards
   longevity-200gb-48h-verify-limited--db-node-69f71bbe-3 (13.51.171.233 | 10.0.3.163): 14 shards
   longevity-200gb-48h-verify-limited--db-node-69f71bbe-4 (13.48.70.127 | 10.0.2.69): 14 shards
OS (RHEL/CentOS/Ubuntu/AWS AMI): `ami-030b85e78a28f3d3e` (aws: eu-north-1)

**Issue description**

Test should run for 2 days with dataset size 200GB with server and client encryption and authentication.
Several nemesises were run without any errors: 

- TruncateMonkey 
- ManagementBackup 
- Drainer 
- NodetoolCleanupMonkey 
- MajorCompaction 
- SoftRebootNode 
- ModifyTablePropertiesComment 
- NodetoolCleanupMonkey 
- Drainer 
- AddDropColumnMonkey 
- ManagementBackup 
- ManagementRepair 

After that next nemesis Refresh was started. The nemesis creatse keyspaces and table using cassandra command, then download the sstables from aws storage, put them to upload/ dir and run `nodetool refresh for keyspace table`

Next command were executed on node1:
```
Command "curl -L https://s3.amazonaws.com/scylla-qa-team/refresh_nemesis_c0/keyspace1.standard1.tar.gz -o /tmp/keyspace1.standard1.tar.gz --user-agent e7a0f973-fa9a-47f4-8cbf-c90d86ddc38a" finished with status 0
Running command "md5sum /tmp/keyspace1.standard1.tar.gz"...
c4aee10691fa6343a786f52663e7f758  /tmp/keyspace1.standard1.tar.gz
Command "md5sum /tmp/keyspace1.standard1.tar.gz" finished with status 0
Running command "md5sum /tmp/keyspace1.standard1.tar.gz"...
c4aee10691fa6343a786f52663e7f758  /tmp/keyspace1.standard1.tar.gz
Command "md5sum /tmp/keyspace1.standard1.tar.gz" finished with status 0
Running command "sudo ls -t /var/lib/scylla/data/keyspace1/"...
standard1-40c6b9e0a97711ebaecd664e23d1ad3a
Command "sudo ls -t /var/lib/scylla/data/keyspace1/" finished with status 0
Running command "sudo -u scylla tar xvfz /tmp/keyspace1.standard1.tar.gz -C /var/lib/scylla/data/keyspace1/standard1-40c6b9e0a97711ebaecd664e23d1ad3a/upload/"...
 mc-1-big-CRC.db
 mc-1-big-Data.db
 mc-1-big-Digest.crc32
 mc-1-big-Filter.db
 mc-1-big-Index.db
 mc-1-big-Scylla.db
 mc-1-big-Statistics.db
 mc-1-big-Summary.db
 mc-1-big-TOC.txt
Command "sudo -u scylla tar xvfz /tmp/keyspace1.standard1.tar.gz -C /var/lib/scylla/data/keyspace1/standard1-40c6b9e0a97711ebaecd664e23d1ad3a/upload/" finished with status 0
Running command "sudo rm -f /var/lib/scylla/data/keyspace1/standard1-40c6b9e0a97711ebaecd664e23d1ad3a/upload/schema.cql"...
Command "sudo rm -f /var/lib/scylla/data/keyspace1/standard1-40c6b9e0a97711ebaecd664e23d1ad3a/upload/schema.cql" finished with status 0
Running command "sudo rm -f /var/lib/scylla/data/keyspace1/standard1-40c6b9e0a97711ebaecd664e23d1ad3a/upload/manifest.json"...
Command "sudo rm -f /var/lib/scylla/data/keyspace1/standard1-40c6b9e0a97711ebaecd664e23d1ad3a/upload/manifest.json" finished with status 0
Running command "/usr/bin/nodetool -u cassandra -pw cassandra  refresh -- keyspace1 standard1"...
```
Node 1 start refreshing:
```
2021-04-30T14:48:14+00:00  longevity-200gb-48h-verify-limited--db-node-69f71bbe-1 !INFO    | scylla:  [shard 2] storage_service - Loading new SSTables for keyspace=keyspace1, table=standard1, load_and_stream=false, primary_replica_only=false
2021-04-30T14:48:14+00:00  longevity-200gb-48h-verify-limited--db-node-69f71bbe-1 !INFO    | scylla:  [shard 2] database - Resharding 66kB for keyspace1.standard1
2021-04-30T14:48:14+00:00  longevity-200gb-48h-verify-limited--db-node-69f71bbe-1 !INFO    | scylla:  [shard 0] compaction - [Reshard keyspace1.standard1 175e1250-a9c3-11eb-8ef2-e9f6772f34eb] Resharding [/var/lib/scylla/data/keyspace1/standard1-40c6b9e0a97711ebaecd664e23d1ad3a/upload/mc-1-big-Data.db:level=0:origin=, ]
2021-04-30T14:48:14+00:00  longevity-200gb-48h-verify-limited--db-node-69f71bbe-1 !INFO    | scylla:  [shard 0] compaction - [Reshard keyspace1.standard1 175e1250-a9c3-11eb-8ef2-e9f6772f34eb] Resharded 1 sstables to [/var/lib/scylla/data/keyspace1/standard1-40c6b9e0a97711ebaecd664e23d1ad3a/upload/md-23-big-Data.db:level=0, /var/lib/scylla/data/keyspace1/standard1-40c6b9e0a97711ebaecd664e23d1ad3a/upload/md-14-big-Data.db:level=0, /var/lib/scylla/data/keyspace1/standard1-40c6b9e0a97711ebaecd664e23d1ad3a/upload/md-27-big-Data.db:level=0, /var/lib/scylla/data/keyspace1/standard1-40c6b9e0a97711ebaecd664e23d1ad3a/upload/md-20-big-Data.db:level=0, /var/lib/scylla/data/keyspace1/standard1-40c6b9e0a97711ebaecd664e23d1ad3a/upload/md-16-big-Data.db:level=0, /var/lib/scylla/data/keyspace1/standard1-40c6b9e0a97711ebaecd664e23d1ad3a/upload/md-21-big-Data.db:level=0, /var/lib/scylla/data/keyspace1/standard1-40c6b9e0a97711ebaecd664e23d1ad3a/upload/md-18-big-Data.db:level=0, /var/lib/scylla/data/keyspace1/standard1-40c6b9e0a97711ebaecd664e23d1ad3a/upload/md-22-big-Data.db:level=0, /var/lib/scylla/data/keyspace1/standard1-40c6b9e0a97711ebaecd664e23d1ad3a/upload/md-26-big-Data.db:level=0, /var/lib/scylla/data/keyspace1/standard1-40c6b9e0a97711ebaecd664e23d1ad3a/upload/md-17-big-Data.db:level=0, /var/lib/scylla/data/keyspace1/standard1-40c6b9e0a97711ebaecd664e23d1ad3a/upload/md-24-big-Data.db:level=0, /var/lib/scylla/data/keyspace1/standard1-40c6b9e0a97711ebaecd664e23d1ad3a/upload/md-15-big-Data.db:level=0, /var/lib/scylla/data/keyspace1/standard1-40c6b9e0a97711ebaecd664e23d1ad3a/upload/md-19-big-Data.db:level=0, /var/lib/scylla/data/keyspace1/standard1-40c6b9e0a97711ebaecd664e23d1ad3a/upload/md-25-big-Data.db:level=0, ]. 88kB to 1MB (~1564% of original) in 356ms = 3MB/s. ~1024 total partitions merged to 1000.
2021-04-30T14:48:14+00:00  longevity-200gb-48h-verify-limited--db-node-69f71bbe-1 !INFO    | scylla:  [shard 2] database - Resharded 66kB for keyspace1.standard1 in 0.38 seconds, 176kB/s
2021-04-30T14:48:14+00:00  longevity-200gb-48h-verify-limited--db-node-69f71bbe-1 !INFO    | scylla:  [shard 2] LeveledManifest - Reshaping 1 disjoint sstables in level 0 into level 0
2021-04-30T14:48:14+00:00  longevity-200gb-48h-verify-limited--db-node-69f71bbe-1 !INFO    | scylla:  [shard 2] sstable_directory - Table keyspace1.standard1 with compaction strategy LeveledCompactionStrategy found SSTables that need reshape. Starting reshape process
```
Nodetool refresh was been running during 2days on one node1 and never stopped until job was not terminated

```
2021-05-01T09:11:34+00:00  longevity-200gb-48h-verify-limited--db-node-69f71bbe-1 !INFO    | scylla:  [shard 9] LeveledManifest - Reshaping 1 disjoint sstables in level 0 into level 0
2021-05-01T09:11:34+00:00  longevity-200gb-48h-verify-limited--db-node-69f71bbe-1 !INFO    | scylla:  [shard 9] compaction - [Reshape keyspace1.standard1 39bf4950-aa5d-11eb-97fb-e9f2772f34eb] Reshaping [/var/lib/scylla/data/keyspace1/standard1-40c6b9e0a97711ebaecd664e23d1ad3a/upload/md-23400673-big-Data.db:level=0:origin=reshape, ]
2021-05-01T09:11:34+00:00  longevity-200gb-48h-verify-limited--db-node-69f71bbe-1 !INFO    | scylla:  [shard 0] LeveledManifest - Reshaping 1 disjoint sstables in level 0 into level 0
2021-05-01T09:11:34+00:00  longevity-200gb-48h-verify-limited--db-node-69f71bbe-1 !INFO    | scylla:  [shard 0] compaction - [Reshape keyspace1.standard1 39bf7060-aa5d-11eb-8ef2-e9f6772f34eb] Reshaping [/var/lib/scylla/data/keyspace1/standard1-40c6b9e0a97711ebaecd664e23d1ad3a/upload/md-22384894-big-Data.db:level=0:origin=reshape, ]
2021-05-01T09:11:34+00:00  longevity-200gb-48h-verify-limited--db-node-69f71bbe-1 !INFO    | scylla:  [shard 13] LeveledManifest - Reshaping 1 disjoint sstables in level 0 into level 0
2021-05-01T09:11:34+00:00  longevity-200gb-48h-verify-limited--db-node-69f71bbe-1 !INFO    | scylla:  [shard 13] compaction - [Reshape keyspace1.standard1 39bf9770-aa5d-11eb-bf22-e9fe772f34eb] Reshaping [/var/lib/scylla/data/keyspace1/standard1-40c6b9e0a97711ebaecd664e23d1ad3a/upload/md-22155195-big-Data.db:level=0:origin=reshape, ]
2021-05-01T09:11:34+00:00  longevity-200gb-48h-verify-limited--db-node-69f71bbe-1 !INFO    | scylla:  [shard 4] LeveledManifest - Reshaping 1 disjoint sstables in level 0 into level 0
2021-05-01T09:11:34+00:00  longevity-200gb-48h-verify-limited--db-node-69f71bbe-1 !INFO    | scylla:  [shard 4] compaction - [Reshape keyspace1.standard1 39c11e10-aa5d-11eb-a492-e9f5772f34eb] Reshaping [/var/lib/scylla/data/keyspace1/standard1-40c6b9e0a97711ebaecd664e23d1ad3a/upload/md-22114642-big-Data.db:level=0:origin=reshape, ]
2021-05-01T09:11:34+00:00  longevity-200gb-48h-verify-limited--db-node-69f71bbe-1 !INFO    | scylla:  [shard 3] LeveledManifest - Reshaping 1 disjoint sstables in level 0 into level 0
2021-05-01T09:11:34+00:00  longevity-200gb-48h-verify-limited--db-node-69f71bbe-1 !INFO    | scylla:  [shard 3] compaction - [Reshape keyspace1.standard1 39c11e10-aa5d-11eb-9048-e9f8772f34eb] Reshaping [/var/lib/scylla/data/keyspace1/standard1-40c6b9e0a97711ebaecd664e23d1ad3a/upload/md-22143635-big-Data.db:level=0:origin=reshape, ]
2021-05-01T09:11:34+00:00  longevity-200gb-48h-verify-limited--db-node-69f71bbe-1 !INFO    | scylla:  [shard 10] LeveledManifest - Reshaping 1 disjoint sstables in level 0 into level 0
2021-05-01T09:11:34+00:00  longevity-200gb-48h-verify-limited--db-node-69f71bbe-1 !INFO    | scylla:  [shard 10] compaction - [Reshape keyspace1.standard1 39c16c30-aa5d-11eb-9257-e9fb772f34eb] Reshaping [/var/lib/scylla/data/keyspace1/standard1-40c6b9e0a97711ebaecd664e23d1ad3a/upload/md-22541928-big-Data.db:level=0:origin=reshape, ]
2021-05-01T09:11:34+00:00  longevity-200gb-48h-verify-limited--db-node-69f71bbe-1 !INFO    | scylla:  [shard 8] compaction - [Reshape keyspace1.standard1 39be10d0-aa5d-11eb-af51-e9fa772f34eb] Reshaped 1 sstables to [/var/lib/scylla/data/keyspace1/standard1-40c6b9e0a97711ebaecd664e23d1ad3a/upload/md-21860420-big-Data.db:level=0, ]. 96kB to 96kB (~100% of original) in 24ms = 4MB/s. ~128 total partitions merged to 77.
2021-05-01T09:11:34+00:00  longevity-200gb-48h-verify-limited--db-node-69f71bbe-1 !INFO    | scylla:  [shard 2] compaction - [Reshape keyspace1.standard1 39be37e0-aa5d-11eb-8efa-e9f9772f34eb] Reshaped 1 sstables to [/var/lib/scylla/data/keyspace1/standard1-40c6b9e0a97711ebaecd664e23d1ad3a/upload/md-23568708-big-Data.db:level=0, ]. 97kB to 97kB (~100% of original) in 26ms = 3MB/s. ~128 total partitions merged to 69.
2021-05-01T09:11:34+00:00  longevity-200gb-48h-verify-limited--db-node-69f71bbe-1 !INFO    | scylla:  [shard 1] compaction - [Reshape keyspace1.standard1 39bc8a30-aa5d-11eb-b992-e9f7772f34eb] Reshaped 1 sstables to [/var/lib/scylla/data/keyspace1/standard1-40c6b9e0a97711ebaecd664e23d1ad3a/upload/md-21846427-big-Data.db:level=0, ]. 100kB to 100kB (~100% of original) in 38ms = 2MB/s. ~128 total partitions merged to 67.
2021-05-01T09:11:34+00:00  longevity-200gb-48h-verify-limited--db-node-69f71bbe-1 !INFO    | scylla:  [shard 5] compaction - [Reshape keyspace1.standard1 39be10d0-aa5d-11eb-b03d-e9fd772f34eb] Reshaped 1 sstables to [/var/lib/scylla/data/keyspace1/standard1-40c6b9e0a97711ebaecd664e23d1ad3a/upload/md-22747387-big-Data.db:level=0, ]. 97kB to 97kB (~100% of original) in 29ms = 3MB/s. ~128 total partitions merged to 69.
...
2021-05-02T03:48:10+00:00  longevity-200gb-48h-verify-limited--db-node-69f71bbe-1 !INFO    | scylla:  [shard 7] compaction - [Reshape keyspace1.standard1 36c87ea0-aaf9-11eb-b4fb-e9f3772f34eb] Reshaped 1 sstables to [/var/lib/scylla/data/keyspace1/standard1-40c6b9e0a97711ebaecd664e23d1ad3a/upload/md-47768049-big-Data.db:level=0, ]. 99kB to 99kB (~100% of original) in 67ms = 1MB/s. ~128 total partitions merged to 77.
2021-05-02T03:48:12+00:00  longevity-200gb-48h-verify-limited--db-node-69f71bbe-1 !INFO    | scylla:  [shard 6] LeveledManifest - Reshaping 1 disjoint sstables in level 0 into level 0
2021-05-02T03:48:14+00:00  longevity-200gb-48h-verify-limited--db-node-69f71bbe-1 !INFO    | scylla:  [shard 3] LeveledManifest - Reshaping 1 disjoint sstables in level 0 into level 0
2021-05-02T03:48:16+00:00  longevity-200gb-48h-verify-limited--db-node-69f71bbe-1 !INFO    | scylla:  [shard 6] LeveledManifest - Reshaping 1 disjoint sstables in level 0 into level 0
2021-05-02T03:48:18+00:00  longevity-200gb-48h-verify-limited--db-node-69f71bbe-1 !INFO    | scylla:  [shard 11] compaction - [Reshape keyspace1.standard1 3b937430-aaf9-11eb-bb3f-e9ff772f34eb] Reshaped 1 sstables to [/var/lib/scylla/data/keyspace1/standard1-40c6b9e0a97711ebaecd664e23d1ad3a/upload/md-45333047-big-Data.db:level=0, ]. 98kB to 98kB (~100% of original) in 33ms = 2MB/s. ~128 total partitions merged to 65.
2021-05-02T03:48:20+00:00  longevity-200gb-48h-verify-limited--db-node-69f71bbe-1 !INFO    | scylla:  [shard 6] LeveledManifest - Reshaping 1 disjoint sstables in level 0 into level 0
2021-05-02T03:48:22+00:00  longevity-200gb-48h-verify-limited--db-node-69f71bbe-1 !INFO    | scylla:  [shard 10] compaction - [Reshape keyspace1.standard1 3df4bcc0-aaf9-11eb-9257-e9fb772f34eb] Reshaped 1 sstables to [/var/lib/scylla/data/keyspace1/standard1-40c6b9e0a97711ebaecd664e23d1ad3a/upload/md-45800618-big-Data.db:level=0, ]. 97kB to 97kB (~100% of original) in 35ms = 2MB/s. ~128 total partitions merged to 70.
2021-05-02T03:48:24+00:00  longevity-200gb-48h-verify-limited--db-node-69f71bbe-1 !INFO    | scylla:  [shard 10] LeveledManifest - Reshaping 1 disjoint sstables in level 0 into level 0
2021-05-02T03:48:26+00:00  longevity-200gb-48h-verify-limited--db-node-69f71bbe-1 !INFO    | scylla:  [shard 9] LeveledManifest - Reshaping 1 disjoint sstables in level 0 into level 0
2021-05-02T03:48:28+00:00  longevity-200gb-48h-verify-limited--db-node-69f71bbe-1 !INFO    | scylla:  [shard 4] compaction - [Reshape keyspace1.standard1 4189a350-aaf9-11eb-a492-e9f5772f34eb] Reshaped 1 sstables to [/var/lib/scylla/data/keyspace1/standard1-40c6b9e0a97711ebaecd664e23d1ad3a/upload/md-45465578-big-Data.db:level=0, ]. 100kB to 100kB (~100% of original) in 28ms = 3MB/s. ~128 total partitions merged to 71.
2021-05-02T03:48:30+00:00  longevity-200gb-48h-verify-limited--db-node-69f71bbe-1 !INFO    | scylla:  [shard 11] compaction - [Reshape keyspace1.standard1 42bea0e0-aaf9-11eb-bb3f-e9ff772f34eb] Reshaping [/var/lib/scylla/data/keyspace1/standard1-40c6b9e0a97711ebaecd664e23d1ad3a/upload/md-45338325-big-Data.db:level=0:origin=reshape, ]
2021-05-02T03:48:32+00:00  longevity-200gb-48h-verify-limited--db-node-69f71bbe-1 !INFO    | scylla:  [shard 13] compaction - [Reshape keyspace1.standard1 43efcde0-aaf9-11eb-bf22-e9fe772f34eb] Reshaping [/var/lib/scylla/data/keyspace1/standard1-40c6b9e0a97711ebaecd664e23d1ad3a/upload/md-45631739-big-Data.db:level=0:origin=reshape, ]
2021-05-02T03:48:34+00:00  longevity-200gb-48h-verify-limited--db-node-69f71bbe-1 !INFO    | scylla:  [shard 6] compaction - [Reshape keyspace1.standard1 451d7870-aaf9-11eb-90d7-e9fc772f34eb] Reshaped 1 sstables to [/var/lib/scylla/data/keyspace1/standard1-40c6b9e0a97711ebaecd664e23d1ad3a/upload/md-48425222-big-Data.db:level=0, ]. 99kB to 99kB (~100% of original) in 26ms = 3MB/s. ~128 total partitions merged to 71.
2021-05-02T03:48:36+00:00  longevity-200gb-48h-verify-limited--db-node-69f71bbe-1 !INFO    | scylla:  [shard 5] compaction - [Reshape keyspace1.standard1 464ea570-aaf9-11eb-b03d-e9fd772f34eb] Reshaped 1 sstables to [/var/lib/scylla/data/keyspace1/standard1-40c6b9e0a97711ebaecd664e23d1ad3a/upload/md-46281961-big-Data.db:level=0, ]. 97kB to 97kB (~100% of original) in 24ms = 4MB/s. ~128 total partitions merged to 69.
2021-05-02T03:48:38+00:00  longevity-200gb-48h-verify-limited--db-node-69f71bbe-1 !INFO    | scylla:  [shard 10] LeveledManifest - Reshaping 1 disjoint sstables in level 0 into level 0
2021-05-02T03:48:40+00:00  longevity-200gb-48h-verify-limited--db-node-69f71bbe-1 !INFO    | scylla:  [shard 6] compaction - [Reshape keyspace1.standard1 48b4d000-aaf9-11eb-90d7-e9fc772f34eb] Reshaping [/var/lib/scylla/data/keyspace1/standard1-40c6b9e0a97711ebaecd664e23d1ad3a/upload/md-48428162-big-Data.db:level=0:origin=reshape, ]
2021-05-02T03:48:42+00:00  longevity-200gb-48h-verify-limited--db-node-69f71bbe-1 !INFO    | scylla:  [shard 12] LeveledManifest - Reshaping 1 disjoint sstables in level 0 into level 0
2021-05-02T03:48:44+00:00  longevity-200gb-48h-verify-limited--db-node-69f71bbe-1 !INFO    | scylla:  [shard 8] LeveledManifest - Reshaping 1 disjoint sstables in level 0 into level 0
2021-05-02T03:48:46+00:00  longevity-200gb-48h-verify-limited--db-node-69f71bbe-1 !INFO    | scylla:  [shard 1] LeveledManifest - Reshaping 1 disjoint sstables in level 0 into level 0
2021-05-02T03:48:48+00:00  longevity-200gb-48h-verify-limited--db-node-69f71bbe-1 !INFO    | scylla:  [shard 6] LeveledManifest - Reshaping 1 disjoint sstables in level 0 into level 0
2021-05-02T03:48:50+00:00  longevity-200gb-48h-verify-limited--db-node-69f71bbe-1 !INFO    | scylla:  [shard 11] compaction - [Reshape keyspace1.standard1 4ea818f0-aaf9-11eb-bb3f-e9ff772f34eb] Reshaped 1 sstables to [/var/lib/scylla/data/keyspace1/standard1-40c6b9e0a97711ebaecd664e23d1ad3a/upload/md-45347397-big-Data.db:level=0, ]. 98kB to 98kB (~100% of original) in 18ms = 5MB/s. ~128 total partitions merged to 65.
```

![Screenshot from 2021-05-07 00-16-06](https://user-images.githubusercontent.com/44991177/117339049-7c2e4a00-aec9-11eb-8ee0-9b48abf410ab.png)

Logs:
grafana - [https://cloudius-jenkins-test.s3.amazonaws.com/69f71bbe-3617-4bf3-bc73-7ff028645a74/20210502_070607/grafana-screenshot-longevity-200gb-48h-scylla-per-server-metrics-nemesis-20210502_071018-longevity-200gb-48h-verify-limited--monitor-node-69f71bbe-1.png](https://cloudius-jenkins-test.s3.amazonaws.com/69f71bbe-3617-4bf3-bc73-7ff028645a74/20210502_070607/grafana-screenshot-longevity-200gb-48h-scylla-per-server-metrics-nemesis-20210502_071018-longevity-200gb-48h-verify-limited--monitor-node-69f71bbe-1.png)
db-cluster - [https://cloudius-jenkins-test.s3.amazonaws.com/69f71bbe-3617-4bf3-bc73-7ff028645a74/20210502_071452/db-cluster-69f71bbe.zip](https://cloudius-jenkins-test.s3.amazonaws.com/69f71bbe-3617-4bf3-bc73-7ff028645a74/20210502_071452/db-cluster-69f71bbe.zip)
monitor-set - [https://cloudius-jenkins-test.s3.amazonaws.com/69f71bbe-3617-4bf3-bc73-7ff028645a74/20210502_071452/monitor-set-69f71bbe.zip](https://cloudius-jenkins-test.s3.amazonaws.com/69f71bbe-3617-4bf3-bc73-7ff028645a74/20210502_071452/monitor-set-69f71bbe.zip)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/longevity/job/longevity-200gb-48h/115/)

**Comment by bhalevy** [comment] 2021-05-09 11:48
Duplicate of https://github.com/scylladb/scylla/issues/8573

**Closed by bhalevy** 2021-05-09 11:48 UTC
Labels: bug, compaction, high
