### ISSUE TITLE
Safe Mode: Restrict replication factor to be at least 3

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla#9032] opened 2021-07-13 20:56 UTC
Replication Factor = 3 is the most commonly used replication factor.

It assures that LOCAL_QUORUM WRITE / LOCAL_QUORUM READ operations can be done and strong consistency can be achieved even in case of a single replica failure.

Restrict keyspace creation to at least 3 replicas following scylla best practices https://docs.scylladb.com/scylla-cloud/cloud-setup/scylla-best-practices/

**Comment by nyh** [comment] 2021-07-14 12:16
Closing as a duplicate of #8891.

**Closed by nyh** 2021-07-14 12:16 UTC
Labels: enhancement, safe-mode
