### ISSUE TITLE
Duplicate SSTable Compaction and Remains old sstables after Compaction

### ISSUE THREAD

**Issue by ban4785** [scylladb/scylla#2376] opened 2017-05-11 01:43 UTC
version : scylla-1.6.1-20170218.2ea4da2.el7.centos.x86_64

#2359 
for non lsa memory, we changed compress chunk_length_kb and major compaction.

1. after load 1.7 T data, alter table compression with 'chunk_length_kb': '64'(before default value, 4kb).

2. restart ScyllaDB Instance, minor compaction start Immediatly.

3. command nodetool compact 'table'  with no load.

it takes about 10 hours and found CompressionInfo file size decreased 1/16.
_but some old sstables remain after major compaction with no load._
i think this issue related #2253 
![oldsstables](https://cloud.githubusercontent.com/assets/20348151/25927941/5b3ef36a-3634-11e7-9c04-ddbd164a73da.png)
in capture may 10 data files were old sstables, new sstables were created 11 may 2017.

_minor and major Compaction includes same sstables._
this is /var/log/messages log. 11000, 21920, 32800, 44080 SSTables were duplicated in Minor and Major Compaction

**Minor Compaction log**
> May 10 20:17:04 swfosldb01 scylla: [shard 0] compaction - Compacting [
> /scylla/data/foms/fdc_unit_param_data2-2325ba102ba611e792a1000000000006/foms-fdc_unit_param_data2-ka-**21920**-Data.db:level=0, 
> /scylla/data/foms/fdc_unit_param_data2-2325ba102ba611e792a1000000000006/foms-fdc_unit_param_data2-ka-**11000**-Data.db:level=0, 
> /scylla/data/foms/fdc_unit_param_data2-2325ba102ba611e792a1000000000006/foms-fdc_unit_param_data2-ka-**32800**-Data.db:level=0, 
> /scylla/data/foms/fdc_unit_param_data2-2325ba102ba611e792a1000000000006/foms-fdc_unit_param_data2-ka-**44080**-Data.db:level=0, ]

_Major Compaction log_
> May 10 20:18:37 swfosldb01 scylla: [shard 0] compaction - Compacting [
> /scylla/data/foms/fdc_unit_param_data2-2325ba102ba611e792a1000000000006/foms-fdc_unit_param_data2-ka-**4408**0-Data.db:level=0, 
> /scylla/data/foms/fdc_unit_param_data2-2325ba102ba611e792a1000000000006/foms-fdc_unit_param_data2-ka-**32800**-Data.db:level=0, 
> /scylla/data/foms/fdc_unit_param_data2-2325ba102ba611e792a1000000000006/foms-fdc_unit_param_data2-ka-**21920**-Data.db:level=0, 
> /scylla/data/foms/fdc_unit_param_data2-2325ba102ba611e792a1000000000006/foms-fdc_unit_param_data2-ka-**11000**-Data.db:level=0, 
> /scylla/data/foms/fdc_unit_param_data2-2325ba102ba611e792a1000000000006/foms-fdc_unit_param_data2-ka-44152-Data.db:level=0, 
> /scylla/data/foms/fdc_unit_param_data2-2325ba102ba611e792a1000000000006/foms-fdc_unit_param_data2-ka-44176-Data.db:level=0, 
> /scylla/data/foms/fdc_unit_param_data2-2325ba102ba611e792a1000000000006/foms-fdc_unit_param_data2-ka-44160-Data.db:level=0, 
> /scylla/data/foms/fdc_unit_param_data2-2325ba102ba611e792a1000000000006/foms-fdc_unit_param_data2-ka-44328-Data.db:level=0, ]

after all, there are 2 sstables that almost data is same.

> May 11 05:44:55 swfosldb01 scylla: [shard 0] compaction - Compacted 4 sstables to [/scylla/data/foms/fdc_unit_param_data2-2325ba102ba611e792a1000000000006/foms-fdc_unit_param_data2-ka-**44496**-Data.db:level=0, ]. 884025758049 bytes to 884025609051 (~99% of original) in 34070964ms = 24.7446MB/s. ~30117 total partitions merged to 26192.
> May 11 05:48:11 swfosldb01 scylla: [shard 0] compaction - Compacted 8 sstables to [/scylla/data/foms/fdc_unit_param_data2-2325ba102ba611e792a1000000000006/foms-fdc_unit_param_data2-ka-**44504**-Data.db:level=0, ]. 887770119504 bytes to 887769773400 (~99% of original) in 34173736ms = 24.7747MB/s. ~36598 total partitions merged to 27482.

44496,(minor) 44504(major) sstables.
![duplicatecompaction](https://cloud.githubusercontent.com/assets/20348151/25928216/fd8b86d2-3635-11e7-9134-974887f1371c.png)

below is major compaction metric.
![2tcompaction1](https://cloud.githubusercontent.com/assets/20348151/25927704/bd1eb40a-3632-11e7-99b8-85968512803b.png)

![2tcompaction2](https://cloud.githubusercontent.com/assets/20348151/25927708/c8578cf2-3632-11e7-9198-719d19fbea8d.png)

**Comment by raphaelsc** [comment] 2017-05-11 02:04
On Wed, May 10, 2017 at 10:43 PM, ban4785 <notifications@github.com> wrote:

> version : scylla-1.6.1-20170218.2ea4da2.el7.centos.x86_64
>
> #2359 <https://github.com/scylladb/scylla/issues/2359>
> for non lsa memory, we changed compress chunk_length_kb and major
> compaction.
>
>    1.
>
>    after load 1.7 T data, alter table compression with 'chunk_length_kb':
>    '64'(before default value, 4kb).
>    2.
>
>    restart ScyllaDB Instance, minor compaction start Immediatly.
>    3.
>
>    command nodetool compact 'table' with no load.
>
> it takes about 10 hours and found CompressionInfo file size decreased 1/16.
> *but some old sstables remain after major compaction with no load.*
> i think this issue related #2253
> <https://github.com/scylladb/scylla/issues/2253>
>
Thanks for the detailed report. It's related to #2253, and the exact
problem is major compaction not going through compaction manager. The
problem is already fixed on master, and the fix should be backported too.

**Comment by infordb** [comment] 2017-05-11 05:26
@raphaelsc 
Could you check that  minor and major Compaction includes same sstables.
As a result, almost identical files are created in duplicate.

**Comment by raphaelsc** [comment] 2017-05-11 05:48
On Thu, May 11, 2017 at 2:26 AM, Junghyun Park <notifications@github.com>
wrote:

> @raphaelsc <https://github.com/raphaelsc>
> Could you check that minor and major Compaction includes same sstables.
> As a result, almost identical files are created in duplicate.
>
That's a symptom of major compaction not going through compaction manager.
The fix will be available for 1.8 and eventually backported to older
versions. More details can be found here:
https://github.com/scylladb/scylla/issues/1156. Thanks.

**Comment by slivne** [comment] 2017-07-24 14:46
@ban4785 we solved this AFAIK - closing this issue - if there is still a problem please post the specific version you are using and I'll reopen and we will investigate what the issue is

**Closed by slivne** 2017-07-24 14:46 UTC
