### ISSUE TITLE
`INSERT JSON` disallows integers in scientific notation

### ISSUE THREAD

**Issue by avelanarius** [scylladb/scylla#10100] opened 2022-02-18 14:15 UTC
The following example query, which used to work correctly under old JsonCpp `INSERT JSON` implementation, fails to execute with the new RapidJSON implementation:

```
CREATE TABLE t(pk int PRIMARY KEY, v int);

INSERT INTO t JSON '{"pk": 1, "v": 1e6}';
```

The success of the `INSERT INTO` statement relied on a fact that JsonCpp implicitly cast from a floating-point value to an integer value.

A user relied on that old behavior: https://github.com/scylladb/scylla-enterprise/issues/2119

**Comment by nyh** [comment] 2022-02-20 12:16
Please that JSON doesn't have the distinction between integer and floats - both are just **numbers**. It is only the RapidJSON library which tries to make this distinction while parsing, saving the number is "1234" into an integer and "1e6" into a double - perhaps because that's the C convention (that "1e6" is a floating-point constant, not an integer constant), without checking whether 1e6 is a valid integer (it's a whole number and fits into an integer's range).

So I agree that the JSON number "1e6" should be assignable into an integer: When RapidJson gives as a IsDouble() value, we can check whether fits the desired integer's range, and whether it is a whole number, and if so, allow the conversion.

But I think it's a mistake to allow conversion of any floating-point number, such as 2.5, silently into an integer. If the user did not explicitly want **that**, and since Cassandra doesn't allow it (we have a cql-pytest test that verified that!), let's not allow it. It's not the same thing as allowing "1e6".

 With that said, "1e7" is a valid JSON number, and arguably it is an integer, so Scylla should allow an integer to be assigned "1e7" which is as much as integer as "100" - even if C (and apparently RapidJSON) conventions suggest that 1e7 is considered "floating point".

This is why I asked what was the actual user complaint. If the user complained about not being able to set an integer to 1e7, we can fix that, without allowing an integer to be set to 2.5 (with accuracy lost) in the process!

I personally think it's a mistake to allow assigning 2.5 into an integer without any sort of warning, especially if Cassandra doesn't allow it. But assigning 1e7 into an integer should can be allowed (if that's what the user needs), and if Cassandra doesn't support it we can argue it's a Cassandra bug.

Your series also deals with a second kind of assignment - assigning a number into a string. This is a completely separate issue, is this also something the user complained about? I think the result is not pretty (why would an application want to assign a number into a string and not write the number as a string in the first place? why does this work only on numbers and not other things like lists or objects?), but I'm less opposed to it - but I'd still like to see a bit more motivation on why this sort of converting assignments are useful, desirable, Cassandra-compatible (?), or what.

**Comment by nyh** [comment] 2022-02-20 12:33
The following test reproduces what I consider a bug in both Scylla and Cassandra - that the JSON number constant "1e6" is not accepted as an integer although arguably it is. Today Cassandra reports on 1e6 that:
```
[User Defined Function failure] message="execution of 'system.fromjson[text]' failed: org.apache.cassandra.serializers.MarshalException: Expected an int value, but got a Double: 1000000.0"
```
and Scylla reports the mysterious:
```
[User Defined Function failure] message="execution of fromJson failed: Failed parsing fromJson parameter: JSON error: condition not met: data_.f.flags & kUint64Flag"
```
Here is the test (both prepared and unprepared fail):
```python
# In test_fromjson_nonint_*() we noted that the floating point number 1.2
# cannot be assigned into an integer column v. The number 1e6, although to
# C programmers looks like a floating-point constant, is actually a perfectly
# valid integer (it fits the integer's range, and is a whole number), so
# should be accepted.
# Reproduces issue #10100.
def test_fromjson_int_scientific_notation_unprepared(cql, table1):
    p = unique_key_int()
    cql.execute(f"INSERT INTO {table1} (p, v) VALUES ({p}, fromJson('1e6'))")
    assert list(cql.execute(f"SELECT p, v from {table1} where p = {p}")) == [(p, 1e6)]
def test_fromjson_int_scientific_notation_prepared(cql, table1):
    p = unique_key_int()
    stmt = cql.prepare(f"INSERT INTO {table1} (p, v) VALUES (?, fromJson(?))")
    cql.execute(stmt, [p, '1e6'])
    assert list(cql.execute(f"SELECT p, v from {table1} where p = {p}")) == [(p, 1e6)]
```

The remaining question is whether this case I outlined here (whole number with scientific notation) was the only case which bothered the user or did they also want to assign non-whole numbers like 2.5, into an integer?

**Comment by nyh** [comment] 2022-02-20 12:55
By the way, @avelanarius please note that the test file `test/cql-pytest/test_json.py` has 17 (!) known-failing (xfail) tests because of 11 (!) different open issues. There are many edge cases where Scylla, Cassandra, or both, do the wrong thing in JSON conversion. So this issue is just the tip of the iceberg :-(

**Comment by nyh** [comment] 2022-02-20 13:18
I sent the above tests for 1e6 that needs to be assignable into an integer to the mailing list (titled `[PATCH] test/cql-pytest: reproducer for JSON scientific-notation integer problem`). 

I'm still waiting for input on whether 1e6 is the only type of number that this user wanted to insert into integers, or did they also need to insert non-whole numbers (like 2.5) and counted of being truncated.

**Comment by nyh** [comment] 2022-02-20 13:26
It turns out that yes - the user was using integers in scientific notation - like 1.23456789E+9 - and was not attempting to set non-whole numbers like 1.2 into an integer. I'll send a v2 of my test patch to also check this case.

**Comment by avikivity** [comment] 2022-02-20 14:16
I agree with @nyh ideas here. As another data point, 1234567801234567890 also shouldn't be accepted into a bigint, since it cannot be represented. So we can refine the solution: we should accept a json number type into an CQL integer type iff the input is exactly representable. Note there is no such restriction on floats, there you expect precision loss.

**Comment by nyh** [comment] 2022-02-20 14:27
> I agree with @nyh ideas here. As another data point, 1234567801234567890 also shouldn't be accepted into a bigint, since it cannot be represented.

This is another known bug in Scylla's implementation - see `test/cql-pytest/run test_json.py::test_fromjson_int_overflow_unprepared`. As I noted above we have 11 (!) different open issues on JSON bugs that I opened while translating Cassandra's unit tests.  In that test, I tried to insert 2147483648 into an "int", and got a silent wrap-around to -2147483648 in Scylla, and the appropriate error in Cassandra.

> So we can refine the solution: we should accept a json number type into an CQL integer type iff the input is exactly representable. Note there is no such restriction on floats, there you expect precision loss.

Yes, and by the way this is why the DynamoDB API represents numbers as JSON strings, not JSON numbers - they correctly say that the accuracy of the number parser in the various JSON libraries out there cannot be trusted.

**Comment by nyh** [comment] 2022-02-21 10:13
My new tests for trying to assign a whole number with scientific-notation like 1e6 or 1.23456789E+9 are now in master, you can run it with
```
test/cql-pytest/run --runxfail test_json.py::test_fromjson_int_scientific_notation_unprepared
```
(this one is using unprepared statements, there's also a second test with prepared statements).

I think that a fix for this issue should make this test pass, but **not** require changing the existing `test_fromjson_nonint_unprepared` which checks that a non-integer like 1.2 cannot be assigned to an integer. I don't see why any reasonable user might want to try to assign a non-integer into an integer, and want it to succeed.

**Comment by avelanarius** [comment] 2022-02-21 18:54
Changed the title to reflect more precisely the problem of the user: unable to use scientific notation for integer values.

Having thought more about the problem, I would NOT consider other cases:
1. Passing a number to text column (RapidJSON transition disallowed it)
2. Passing a bool to integer column (RapidJSON transition disallowed it)

as bugs, therefore not creating issues for them at this moment.

**Comment by nyh** [comment] 2022-02-22 10:29
> > Having thought more about the problem, I would NOT consider other cases:
>     1. Passing a number to text column (RapidJSON transition disallowed it)
>     2. Passing a bool to integer column (RapidJSON transition disallowed it)

Since JSON officially has distinct number, text and bool types, I agree that allowing the user to confuse them doesn't sound very useful. However, I think we need to test what Cassandra supports and be careful not to support less. If I remember correctly, Cassandra does allow passing a text to an int column - IIRC it parses the string and if it's not an integer produces an error. I hope we have a test for this but didn't check. If this direction is supported, it's not absurd to also support conversion the other way - from number to string, and I simply don't remember if I checked if Cassandra allows such a conversion. It's just a separate issue that should be considered separately.

**Closed** 2022-02-22 22:48 UTC
Labels: User Request, CQL

**Comment by avikivity** [comment] 2022-09-01 12:31
Debating whether to backport. On the one hand, science and javascript are mutually exclusive, and this is esoteric. On the other hand, maybe a library can generate it.

@nyh opinion?

**Comment by avikivity** [comment] 2022-09-01 13:03
Minimally to 5.0.

**Comment by avikivity** [comment] 2022-09-01 13:04
Backported to 5.0 only (as it's not a regression and not an incompatibility, but does affect users).

**Comment by avikivity** [comment] 2022-09-01 13:04
5.1 has it, 4.6 left broken.
