### ISSUE TITLE
duplicate gossip messages

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylla#2068] opened 2017-02-08 15:14 UTC
I stopped a node with the debugger, when I released it this is what its friends had to say:

```
Feb 08 10:10:32 n1.sahara.cloudius-systems.com scylla[109277]:  [shard 0] gossip - InetAddress 10.0.4.131 is now UP, status = NORMAL
Feb 08 10:10:32 n1.sahara.cloudius-systems.com scylla[109277]:  [shard 0] gossip - InetAddress 10.0.4.131 is now UP, status = NORMAL
Feb 08 10:10:32 n1.sahara.cloudius-systems.com scylla[109277]:  [shard 0] gossip - InetAddress 10.0.4.131 is now UP, status = NORMAL
Feb 08 10:10:32 n1.sahara.cloudius-systems.com scylla[109277]:  [shard 0] gossip - InetAddress 10.0.4.131 is now UP, status = NORMAL
Feb 08 10:10:32 n1.sahara.cloudius-systems.com scylla[109277]:  [shard 0] gossip - InetAddress 10.0.4.131 is now UP, status = NORMAL
Feb 08 10:10:32 n1.sahara.cloudius-systems.com scylla[109277]:  [shard 0] gossip - InetAddress 10.0.4.131 is now UP, status = NORMAL
Feb 08 10:10:32 n1.sahara.cloudius-systems.com scylla[109277]:  [shard 0] gossip - InetAddress 10.0.4.131 is now UP, status = NORMAL
Feb 08 10:10:32 n1.sahara.cloudius-systems.com scylla[109277]:  [shard 0] gossip - InetAddress 10.0.4.131 is now UP, status = NORMAL
Feb 08 10:10:32 n1.sahara.cloudius-systems.com scylla[109277]:  [shard 0] gossip - InetAddress 10.0.4.131 is now UP, status = NORMAL
Feb 08 10:10:32 n1.sahara.cloudius-systems.com scylla[109277]:  [shard 0] gossip - InetAddress 10.0.4.131 is now UP, status = NORMAL
Feb 08 10:10:32 n1.sahara.cloudius-systems.com scylla[109277]:  [shard 0] gossip - InetAddress 10.0.4.131 is now UP, status = NORMAL
Feb 08 10:10:32 n1.sahara.cloudius-systems.com scylla[109277]:  [shard 0] gossip - InetAddress 10.0.4.131 is now UP, status = NORMAL
Feb 08 10:10:32 n1.sahara.cloudius-systems.com scylla[109277]:  [shard 0] gossip - InetAddress 10.0.4.131 is now UP, status = NORMAL
Feb 08 10:10:32 n1.sahara.cloudius-systems.com scylla[109277]:  [shard 0] gossip - InetAddress 10.0.4.131 is now UP, status = NORMAL
Feb 08 10:10:32 n1.sahara.cloudius-systems.com scylla[109277]:  [shard 0] gossip - InetAddress 10.0.4.131 is now UP, status = NORMAL
Feb 08 10:10:32 n1.sahara.cloudius-systems.com scylla[109277]:  [shard 0] gossip - InetAddress 10.0.4.131 is now UP, status = NORMAL
Feb 08 10:10:32 n1.sahara.cloudius-systems.com scylla[109277]:  [shard 0] gossip - InetAddress 10.0.4.131 is now UP, status = NORMAL
Feb 08 10:10:32 n1.sahara.cloudius-systems.com scylla[109277]:  [shard 0] gossip - InetAddress 10.0.4.131 is now UP, status = NORMAL
Feb 08 10:10:32 n1.sahara.cloudius-systems.com scylla[109277]:  [shard 0] gossip - InetAddress 10.0.4.131 is now UP, status = NORMAL
Feb 08 10:10:32 n1.sahara.cloudius-systems.com scylla[109277]:  [shard 0] gossip - InetAddress 10.0.4.131 is now UP, status = NORMAL
Feb 08 10:10:32 n1.sahara.cloudius-systems.com scylla[109277]:  [shard 0] gossip - InetAddress 10.0.4.131 is now UP, status = NORMAL
Feb 08 10:10:32 n1.sahara.cloudius-systems.com scylla[109277]:  [shard 0] gossip - InetAddress 10.0.4.131 is now UP, status = NORMAL
Feb 08 10:10:32 n1.sahara.cloudius-systems.com scylla[109277]:  [shard 0] gossip - InetAddress 10.0.4.131 is now UP, status = NORMAL
Feb 08 10:10:32 n1.sahara.cloudius-systems.com scylla[109277]:  [shard 0] gossip - InetAddress 10.0.4.131 is now UP, status = NORMAL
Feb 08 10:10:32 n1.sahara.cloudius-systems.com scylla[109277]:  [shard 0] gossip - InetAddress 10.0.4.131 is now UP, status = NORMAL
Feb 08 10:10:32 n1.sahara.cloudius-systems.com scylla[109277]:  [shard 0] gossip - InetAddress 10.0.4.131 is now UP, status = NORMAL
Feb 08 10:10:32 n1.sahara.cloudius-systems.com scylla[109277]:  [shard 0] gossip - InetAddress 10.0.4.131 is now UP, status = NORMAL
Feb 08 10:10:32 n1.sahara.cloudius-systems.com scylla[109277]:  [shard 0] gossip - InetAddress 10.0.4.131 is now UP, status = NORMAL
Feb 08 10:10:32 n1.sahara.cloudius-systems.com scylla[109277]:  [shard 0] gossip - InetAddress 10.0.4.131 is now UP, status = NORMAL
Feb 08 10:10:32 n1.sahara.cloudius-systems.com scylla[109277]:  [shard 0] gossip - InetAddress 10.0.4.131 is now UP, status = NORMAL
Feb 08 10:10:32 n1.sahara.cloudius-systems.com scylla[109277]:  [shard 0] gossip - InetAddress 10.0.4.131 is now UP, status = NORMAL
Feb 08 10:10:32 n1.sahara.cloudius-systems.com scylla[109277]:  [shard 0] gossip - InetAddress 10.0.4.131 is now UP, status = NORMAL
Feb 08 10:10:32 n1.sahara.cloudius-systems.com scylla[109277]:  [shard 0] gossip - InetAddress 10.0.4.131 is now UP, status = NORMAL
Feb 08 10:10:32 n1.sahara.cloudius-systems.com scylla[109277]:  [shard 0] gossip - InetAddress 10.0.4.131 is now UP, status = NORMAL
Feb 08 10:10:32 n1.sahara.cloudius-systems.com scylla[109277]:  [shard 0] gossip - InetAddress 10.0.4.131 is now UP, status = NORMAL
Feb 08 10:10:32 n1.sahara.cloudius-systems.com scylla[109277]:  [shard 0] gossip - InetAddress 10.0.4.131 is now UP, status = NORMAL
Feb 08 10:10:32 n1.sahara.cloudius-systems.com scylla[109277]:  [shard 0] gossip - InetAddress 10.0.4.131 is now UP, status = NORMAL
Feb 08 10:10:32 n1.sahara.cloudius-systems.com scylla[109277]:  [shard 0] gossip - InetAddress 10.0.4.131 is now UP, status = NORMAL
Feb 08 10:10:32 n1.sahara.cloudius-systems.com scylla[109277]:  [shard 0] gossip - InetAddress 10.0.4.131 is now UP, status = NORMAL
Feb 08 10:10:32 n1.sahara.cloudius-systems.com scylla[109277]:  [shard 0] gossip - InetAddress 10.0.4.131 is now UP, status = NORMAL
Feb 08 10:10:32 n1.sahara.cloudius-systems.com scylla[109277]:  [shard 0] gossip - InetAddress 10.0.4.131 is now UP, status = NORMAL
Feb 08 10:10:32 n1.sahara.cloudius-systems.com scylla[109277]:  [shard 0] gossip - InetAddress 10.0.4.131 is now UP, status = NORMAL
Feb 08 10:10:32 n1.sahara.cloudius-systems.com scylla[109277]:  [shard 0] gossip - InetAddress 10.0.4.131 is now UP, status = NORMAL
Feb 08 10:10:32 n1.sahara.cloudius-systems.com scylla[109277]:  [shard 0] gossip - InetAddress 10.0.4.131 is now UP, status = NORMAL
Feb 08 10:10:32 n1.sahara.cloudius-systems.com scylla[109277]:  [shard 0] gossip - InetAddress 10.0.4.131 is now UP, status = NORMAL
Feb 08 10:10:32 n1.sahara.cloudius-systems.com scylla[109277]:  [shard 0] gossip - InetAddress 10.0.4.131 is now UP, status = NORMAL
Feb 08 10:10:32 n1.sahara.cloudius-systems.com scylla[109277]:  [shard 0] gossip - InetAddress 10.0.4.131 is now UP, status = NORMAL
Feb 08 10:10:32 n1.sahara.cloudius-systems.com scylla[109277]:  [shard 0] gossip - InetAddress 10.0.4.131 is now UP, status = NORMAL
```

I guess all the messages were queued up, then processed by .131, then responses were sent, all printed at the same time.  We should print just one message for each transition.

**Comment by avikivity** [comment] 2017-02-08 15:15
This could happen during a short network partition, not just due to the debugger.

**Comment by tzach** [comment] 2017-02-08 18:44
duplicate with #1184 ?

**Comment by duarten** [comment] 2018-04-28 17:09
Closing as duplicate of #1184.

**Closed by duarten** 2018-04-28 17:09 UTC
Labels: bug, low
