### ISSUE TITLE
Scylla 4.1.8 crash when dropping table

### ISSUE THREAD

**Issue by CatTail** [scylladb/scylla#7715] opened 2020-11-27 09:51 UTC
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [x] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash): 4.1.8-0.20201002.6c43a0dc29
Cluster size: 6
OS (RHEL/CentOS/Ubuntu/AWS AMI): Ubuntu 16.04

```
Nov 27 08:36:24 localhost scylla:  [shard 2] schema_tables - Dropping some-keyspace.some-table id=4dff3630-1a27-11eb-afc5-000000000006 version=4f8742db-f29c-3ea1-b1bd-5f49e7d33013
...
Nov 27 08:36:25 localhost scylla[13907]: scylla: database.cc:1830: database::truncate(const keyspace&, column_family&, database::timestamp_func, bool)::<lambda()>::<lambda()> mutable::<lambda()>::<lambda(db_clock::time_point)>::<lambda()>::<lambda(db::replay_position)>: Assertion `!should_flush || low_mark <= rp || rp == db::replay_position()' failed.
Nov 27 08:36:25 localhost scylla[13907]: Aborting on shard 1.
Nov 27 08:36:25 localhost scylla[13907]: Backtrace:
Nov 27 08:36:25 localhost scylla[13907]:   0x0000000002e36072
Nov 27 08:36:25 localhost scylla[13907]:   0x0000000002ddf6a4
Nov 27 08:36:25 localhost scylla[13907]:   0x0000000002ddf9a5
Nov 27 08:36:25 localhost scylla[13907]:   0x0000000002ddfa40
Nov 27 08:36:25 localhost scylla[13907]:   0x00007fc8cccaeb1f
Nov 27 08:36:25 localhost scylla[13907]:   /opt/scylladb/libreloc/libc.so.6+0x000000000003c624
Nov 27 08:36:25 localhost scylla[13907]:   /opt/scylladb/libreloc/libc.so.6+0x00000000000258d8
Nov 27 08:36:25 localhost scylla[13907]:   /opt/scylladb/libreloc/libc.so.6+0x00000000000257a8
Nov 27 08:36:25 localhost scylla[13907]:   /opt/scylladb/libreloc/libc.so.6+0x0000000000034a65
Nov 27 08:36:25 localhost scylla[13907]:   0x0000000000d3bbaa
Nov 27 08:36:25 localhost scylla[13907]:   0x0000000002ddbbd0
Nov 27 08:36:25 localhost scylla[13907]:   0x0000000002ddbddf
Nov 27 08:36:25 localhost scylla[13907]:   0x0000000002e10c55
Nov 27 08:36:25 localhost scylla[13907]:   0x0000000002e1f38c
Nov 27 08:36:25 localhost scylla[13907]:   0x0000000002dae4cd
Nov 27 08:36:25 localhost scylla[13907]:   /opt/scylladb/libreloc/libpthread.so.0+0x00000000000094e1
Nov 27 08:36:25 localhost scylla[13907]:   /opt/scylladb/libreloc/libc.so.6+0x00000000001016a2
Nov 27 08:36:25 localhost systemd-coredump[19692]: Failed to send coredump datagram: Message too long
Nov 27 08:36:25 localhost systemd[1]: Started Process Core Dump (PID 19692/UID 0).
Nov 27 08:36:25 localhost systemd-coredump[19694]: Coredump file descriptor missing.
```

I understand there is a similar issue in https://github.com/scylladb/scylla/issues/6419, but that issue is caused by configure auto_snapshot disabled, I have configure Scylla to enable auto_snapshot option.

**Comment by tzach** [comment] 2020-11-29 08:01
@nyh is the fix in https://github.com/scylladb/scylla/commit/d70cab044484810cf08d5d0785d491fcce70bbb5 related to auto_snapshot ?

**Comment by piavka** [comment] 2020-11-29 15:55
btw we are also seeing something similar
originally we stopped a scylla POC due to a bug  which has been recently fixed d70cab0, so we decided to give another chance to scylla with auto_snapshot = false and now we hit the following every several hours (we drop a table once an hour) on a 6 node cluster , usually then below happens it happens on 1 or 2 nodes and it's always exact same Backtrace
we are running `Scylla version 4.1.9-0.20201026.b80dab6d58 with build-id 5dfdfb459e7cf1cead8ae668cf081612f5a84ae5`
```
# journalctl  -u scylla-server.service  --since "45 min ago" | grep -v compaction
-- Logs begin at Wed 2020-11-18 12:56:36 UTC, end at Sun 2020-11-29 15:43:23 UTC. --
Nov 29 15:00:08 outcomesdb-i-03b28b5b9d5acd0fe.sonic-us scylla[125329]:  [shard 13] schema_tables - Creating outcomes_db.raw_requests_2020_11_30_15 id=914589a0-3253-11eb-8c8c-00000000000b version=a86b08ce-1d09-394b-a4f9-84de75020c7c
Nov 29 15:00:08 outcomesdb-i-03b28b5b9d5acd0fe.sonic-us scylla[125329]:  [shard 13] database - Schema version changed to 5be62948-8910-3083-aebc-f6f4cdffb1dd
Nov 29 15:00:16 outcomesdb-i-03b28b5b9d5acd0fe.sonic-us scylla[125329]:  [shard 12] schema_tables - Dropping outcomes_db.raw_requests_2020_11_29_08 id=b87ab900-314f-11eb-9530-000000000001 version=b83473cc-bd31-3541-8c3d-d845992a07a1
Nov 29 15:00:19 outcomesdb-i-03b28b5b9d5acd0fe.sonic-us scylla[125329]:  [shard 12] database - Schema version changed to fcc509f3-155a-3da8-a826-df7eaac71b9c
Nov 29 15:00:37 outcomesdb-i-03b28b5b9d5acd0fe.sonic-us scylla[125329]: Segmentation fault on shard 6.
Nov 29 15:00:37 outcomesdb-i-03b28b5b9d5acd0fe.sonic-us scylla[125329]: Backtrace:
Nov 29 15:00:37 outcomesdb-i-03b28b5b9d5acd0fe.sonic-us scylla[125329]:   0x0000000002e3e6d2
Nov 29 15:00:37 outcomesdb-i-03b28b5b9d5acd0fe.sonic-us scylla[125329]:   0x0000000002de7d04
Nov 29 15:00:37 outcomesdb-i-03b28b5b9d5acd0fe.sonic-us scylla[125329]:   0x0000000002de8005
Nov 29 15:00:37 outcomesdb-i-03b28b5b9d5acd0fe.sonic-us scylla[125329]:   0x0000000002de8050
Nov 29 15:00:37 outcomesdb-i-03b28b5b9d5acd0fe.sonic-us scylla[125329]:   0x00007f9afb279b1f
Nov 29 15:00:37 outcomesdb-i-03b28b5b9d5acd0fe.sonic-us scylla[125329]:   0x0000000002d9ad36
Nov 29 15:00:37 outcomesdb-i-03b28b5b9d5acd0fe.sonic-us scylla[125329]:   0x0000000000cbe1b0
Nov 29 15:00:37 outcomesdb-i-03b28b5b9d5acd0fe.sonic-us scylla[125329]:   0x0000000000d4df8a
Nov 29 15:00:37 outcomesdb-i-03b28b5b9d5acd0fe.sonic-us scylla[125329]:   0x0000000000d4fac1
Nov 29 15:00:37 outcomesdb-i-03b28b5b9d5acd0fe.sonic-us scylla[125329]:   0x0000000002de4230
Nov 29 15:00:37 outcomesdb-i-03b28b5b9d5acd0fe.sonic-us scylla[125329]:   0x0000000002de443f
Nov 29 15:00:37 outcomesdb-i-03b28b5b9d5acd0fe.sonic-us scylla[125329]:   0x0000000002e192b5
Nov 29 15:00:37 outcomesdb-i-03b28b5b9d5acd0fe.sonic-us scylla[125329]:   0x0000000002e279ec
Nov 29 15:00:37 outcomesdb-i-03b28b5b9d5acd0fe.sonic-us scylla[125329]:   0x0000000002db6b2d
Nov 29 15:00:37 outcomesdb-i-03b28b5b9d5acd0fe.sonic-us scylla[125329]:   /opt/scylladb/libreloc/libpthread.so.0+0x00000000000094e1
Nov 29 15:00:37 outcomesdb-i-03b28b5b9d5acd0fe.sonic-us scylla[125329]:   /opt/scylladb/libreloc/libc.so.6+0x00000000001016a2
Nov 29 15:00:38 outcomesdb-i-03b28b5b9d5acd0fe.sonic-us systemd[1]: scylla-server.service: Main process exited, code=killed, status=11/SEGV
Nov 29 15:00:38 outcomesdb-i-03b28b5b9d5acd0fe.sonic-us systemd[1]: scylla-server.service: Failed with result 'signal'.
Nov 29 15:00:38 outcomesdb-i-03b28b5b9d5acd0fe.sonic-us systemd[1]: scylla-server.service: Service hold-off time over, scheduling restart.
Nov 29 15:00:38 outcomesdb-i-03b28b5b9d5acd0fe.sonic-us systemd[1]: scylla-server.service: Scheduled restart job, restart counter is at 2.
Nov 29 15:00:39 outcomesdb-i-03b28b5b9d5acd0fe.sonic-us systemd[1]: Stopped Scylla Server.
Nov 29 15:00:39 outcomesdb-i-03b28b5b9d5acd0fe.sonic-us systemd[1]: Starting Scylla Server...
```

**Comment by avikivity** [comment] 2020-11-29 17:22
decoded:

```
void seastar::backtrace<seastar::backtrace_buffer::append_backtrace()::{lambda(seastar::frame)#1}>(seastar::backtrace_buffer::append_backtrace()::{lambda(seastar::frame)#1}&&)
./build/release/seastar/./seastar/include/seastar/util/backtrace.hh:56
seastar::backtrace_buffer::append_backtrace()
./build/release/seastar/./seastar/src/core/reactor.cc:741
print_with_backtrace
./build/release/seastar/./seastar/src/core/reactor.cc:762
seastar::print_with_backtrace(char const*)
./build/release/seastar/./seastar/src/core/reactor.cc:769
seastar::install_oneshot_signal_handler<11, &seastar::sigsegv_action>()::{lambda(int, siginfo_t*, void*)#1}::_FUN(int, siginfo_t*, void*)
./build/release/seastar/./seastar/src/core/reactor.cc:3472
operator()
./build/release/seastar/./seastar/src/core/reactor.cc:3458
_FUN
./build/release/seastar/./seastar/src/core/reactor.cc:3454
seastar::internal::promise_base::promise_base(seastar::internal::promise_base&&)
./build/release/seastar/./seastar/src/core/future.cc:52
seastar::internal::promise_base_with_type<>::promise_base_with_type(seastar::internal::promise_base_with_type<>&&)
././seastar/include/seastar/core/future.hh:604
seastar::promise<>::promise(seastar::promise<>&&)
././seastar/include/seastar/core/future.hh:1613
seastar::shared_promise<>::shared_promise(seastar::shared_promise<>&&)
././seastar/include/seastar/core/shared_future.hh:246
operator()<flush_permit>
./database.cc:1360
apply
././seastar/include/seastar/core/apply.hh:36
seastar::continuation<seastar::internal::promise_base_with_type<>, seastar::future<flush_permit>::then_impl_nrvo<memtable_list::request_flush()::{lambda(auto:1)#2}, seastar::future<> >(memtable_list::request_flush()::{lambda(auto:1)#2}&&)::{lambda()#1}::operator()() const::{lambda(seastar::internal::promise_base_with_type<>&, seastar::future_state<flush_permit>&&)#1}, flush_permit>::run_and_dispose()
././seastar/include/seastar/core/apply.hh:44
operator()
././seastar/include/seastar/core/future.hh:1258
satisfy_with_result_of<seastar::future<T>::then_impl_nrvo(Func&&) [with Func = memtable_list::request_flush()::<lambda(auto:182)>; Result = seastar::future<>; T = {flush_permit}]::<lambda()>::<lambda(pr_type&, seastar::future_state<flush_permit>&&)> mutable::<lambda()> >
././seastar/include/seastar/core/future.hh:1741
operator()
././seastar/include/seastar/core/future.hh:1257
run_and_dispose
././seastar/include/seastar/core/future.hh:504
seastar::reactor::run_tasks(seastar::reactor::task_queue&)
./build/release/seastar/./seastar/src/core/reactor.cc:2154
seastar::reactor::run_some_tasks()
./build/release/seastar/./seastar/src/core/reactor.cc:2569
seastar::reactor::run_some_tasks()
./build/release/seastar/./seastar/src/core/reactor.cc:2552
seastar::reactor::run()
./build/release/seastar/./seastar/src/core/reactor.cc:2724
seastar::smp::configure(boost::program_options::variables_map, seastar::reactor_config)::{lambda()#3}::operator()() const
./build/release/seastar/./seastar/src/core/reactor.cc:3898
std::function<void ()>::operator()() const
/usr/include/c++/9/bits/std_function.h:688
seastar::posix_thread::start_routine(void*)
./build/release/seastar/./seastar/src/core/posix.cc:60
```

**Comment by avikivity** [comment] 2020-11-29 17:28
This is the line after get_flush_permit().

```c++

future<> memtable_list::request_flush() {
    if (empty() || !may_flush()) {
        return make_ready_future<>();
    } else if (!_flush_coalescing) {
        _flush_coalescing = shared_promise<>();
        _dirty_memory_manager->start_extraneous_flush();
        auto ef = defer([this] { _dirty_memory_manager->finish_extraneous_flush(); });
        return _dirty_memory_manager->get_flush_permit().then([this, ef = std::move(ef)] (auto permit) mutable {
            auto current_flush = std::move(*_flush_coalescing);
            _flush_coalescing = {};
            return _dirty_memory_manager->flush_one(*this, std::move(permit)).then_wrapped([this, ef = std::move(ef),
                                                                                            current_flush = std::move(current_flush)] (auto f) mutable {
                if (f.failed()) {
                    current_flush.set_exception(f.get_exception());
                } else {
                    current_flush.set_value();
                }
            });
        });
    } else {
        return _flush_coalescing->get_shared_future();
    }
}
```

**Comment by avikivity** [comment] 2020-11-29 17:33
Very strange, this code hasn't changed for the past two years.

**Comment by avikivity** [comment] 2020-11-29 17:51
@piavka please double check 4.1.9 was what you we running at the time of the crash.

**Comment by nyh** [comment] 2020-11-29 19:04
@avikivity the cause of this crash is just an assertion failure - 
```
Nov 27 08:36:25 localhost scylla[13907]: scylla: database.cc:1830: database::truncate(const keyspace&, column_family&, database::timestamp_func, bool)::<lambda()>::<lambda()> mutable::<lambda()>::<lambda(db_clock::time_point)>::<lambda()>::<lambda(db::replay_position)>: Assertion `!should_flush || low_mark <= rp || rp == db::replay_position()' failed.
```
This indeed looks **exactly** like https://github.com/scylladb/scylla/issues/6995, and looking at the different branches it appears I made a backporting error, and forgot to backport it to 4.1 (the link there to the backported issue in 4.1 is actually in 4.0...), and you are running. Ooops.

So should be trivial to fix with a backport.

**Comment by nyh** [comment] 2020-11-29 19:37
So, it turns out that I **did** backport the issue to 4.1 - see commit df8d4482c5fef0c75e26e430169342feb39b1704, and it already exists in Scylla 4.1.8 and 4.1.9 mentioned in the issue. So my guess of a missing backport was a red herring.

@elcallio one of the reports above was that **with** snapshots, when after this commit the assertion is still done, the assertion fails. Do you have any more guesses why this might happen?

**Comment by svloginov** [comment] 2020-11-30 08:29
> @piavka please double check 4.1.9 was what you we running at the time of the crash.

We are using 4.1.9-0.20201026.b80dab6d58-1. I work at the same company as @piavka.

**Comment by elcallio** [comment] 2020-12-15 12:50
@amoskong found an issue with doing truncate after loading sstables via "upload" dir (nodetool refresh), then doing truncate without having any data in memtable - #7732. The same should probably apply if a node is started with data existing in sstables, but nothing written to memtable, and then is truncated. 
I am starting to wonder if we should never read RP:s from sstables being opened - only those written... Or at least keep track of whether the flush in truncate actually creates any sstables...

**Comment by psarna** [comment] 2020-12-22 18:50
Perhaps this issue shares a root cause with https://github.com/scylladb/scylla/issues/7792 (fixed)?

**Comment by elcallio** [comment] 2021-01-04 15:52
I think this is a dup of #7732, but it would be nice if OP verified it. The fix is in master.

**Comment by slivne** [comment] 2021-05-18 15:53
slosing this issue - the (assumed) fix is in all supported OSS releases - if this is hit again please post and we can reopen

**Closed by slivne** 2021-05-18 15:53 UTC
Labels: User Request, bug
