### ISSUE TITLE
WHERE clause in SELECT DISTINCT can be ignored

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#2241] opened 2017-03-30 12:48 UTC
```
CREATE TABLE t (id int, s int, name text, PRIMARY KEY(id,s));
insert into t (id,s,name) values (1,1,'tzach');
insert into t (id,s,name) values (1,2,'chatz');
insert into t (id,s,name) values (2,1,'tomer');
insert into t (id,s,name) values (2,1,'rotem');
insert into t (id,s,name) values (6,3,'zzz');
SELECT DISTINCT id from t WHERE s<=2 ALLOW FILTERING;

 id
----
  1
  2
  6
```

6 should not be included in the results
Similar to
https://issues.apache.org/jira/browse/CASSANDRA-11339

**Comment by tgrabiec** [comment] 2017-03-31 07:23
Duplicate of #2049

**Closed by tgrabiec** 2017-03-31 07:23 UTC
Labels: bug, cassandra 3.x compatability, CQL
