### ISSUE TITLE
Dropping and recreating a keyspace causes unrecoverable error

### ISSUE THREAD

**Issue by veramine** [scylladb/scylla#3073] opened 2017-12-19 06:35 UTC
Scylla version 2.0.2
Single node cluster
AWS ami-10a09a70 (us-west-1)
VM size i3.xlarge
scylla.yaml experimental=true (for MV support)

We have lots of tables in our schema (attached) and encountered a situation today where we dropped the keyspace and attempted to recreate it shortly after installing a new single node cluster using the AWS AMI.  The drop keyspace initially failed (due to the UDT issue https://github.com/scylladb/scylla/issues/3068) but then worked.  However, when I attempted to re-create the keyspace using cqlsh -f, it ran for a while with no errors but it doesn't seem like it was created.  And I don't see any errors in the log.  When I attempted 'systemctl restart scylla-server', it failed to restart and now is stuck.

```
[centos@ip-172-31-14-179 ~]$ cqlsh -f /tmp/schema.cql 
[centos@ip-172-31-14-179 ~]$ cqlsh
Connected to Test Cluster - No AMI Parameters at 127.0.0.1:9042.
[cqlsh 5.0.1 | Cassandra 3.0.8 | CQL spec 3.3.1 | Native protocol v4]
Use HELP for help.
cqlsh> use veraminetest ;
cqlsh:veraminetest> select * from hosts;

 key | customerguid | systemguid | hostid | bitlockervolumesdisabled | bitlockervolumesenabled | bytesrecved | createdat | customerid | diskinformation | eventscount | groups | hostname | ipstr | lastcontact | lastdiagnosticsjson | lastdiagnosticstime | lastsessiondisconnecttime | lastsessionendtime | lastsessionstarttime | lastsystemuptime | lockconsoleonwake | osver | protocolbytecount | quarantined | sensorversion | sessionguid | uploadbytes | uploadcount | windowsfirewallstatus | wusummary
-----+--------------+------------+--------+--------------------------+-------------------------+-------------+-----------+------------+-----------------+-------------+--------+----------+-------+-------------+---------------------+---------------------+---------------------------+--------------------+----------------------+------------------+-------------------+-------+-------------------+-------------+---------------+-------------+-------------+-------------+-----------------------+-----------

cqlsh:veraminetest> use system ;
cqlsh:system> drop KEYSPACE veraminetest ;
InvalidRequest: Error from server: code=2200 [Invalid query] message="Unknown type veraminetest.disk"
cqlsh:system> drop TYPE veraminetest.disk;
InvalidRequest: Error from server: code=2200 [Invalid query] message="No user type named veraminetest.disk exists."
cqlsh:system> drop KEYSPACE veraminetest ;
cqlsh:system> quit
[centos@ip-172-31-14-179 ~]$ cqlsh -f /tmp/schema.cql 
[centos@ip-172-31-14-179 ~]$ cqlsh
Connected to Test Cluster - No AMI Parameters at 127.0.0.1:9042.
[cqlsh 5.0.1 | Cassandra 3.0.8 | CQL spec 3.3.1 | Native protocol v4]
Use HELP for help.
cqlsh> use ver
   ... ;
InvalidRequest: Error from server: code=2200 [Invalid query] message="Keyspace 'ver' does not exist"
cqlsh> use veraminetest;
cqlsh:veraminetest> describe table hosts;

Keyspace 'veraminetest' not found.
cqlsh:veraminetest> describe table hosts;

Keyspace 'veraminetest' not found.
cqlsh:veraminetest> quit
[centos@ip-172-31-14-179 ~]$ cqlsh
Connected to Test Cluster - No AMI Parameters at 127.0.0.1:9042.
[cqlsh 5.0.1 | Cassandra 3.0.8 | CQL spec 3.3.1 | Native protocol v4]
Use HELP for help.
cqlsh> use veraminetest;
cqlsh:veraminetest> describe table hsots;

Keyspace 'veraminetest' not found.
cqlsh:veraminetest> describe table hosts;

Keyspace 'veraminetest' not found.
cqlsh:veraminetest> quit
[centos@ip-172-31-14-179 ~]$ sudo systemctl restart scylla-server
Job for scylla-server.service failed because the control process exited with error code. See "systemctl status scylla-server.service" and "journalctl -xe" for details.
[centos@ip-172-31-14-179 ~]$ journalctl -xe
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit scylla-server.service has failed.
-- 
-- The result is failed.
Dec 19 06:15:00 ip-172-31-14-179 systemd[1]: Dependency failed for Scylla JMX.
-- Subject: Unit scylla-jmx.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit scylla-jmx.service has failed.
-- 
-- The result is dependency.
Dec 19 06:15:00 ip-172-31-14-179 systemd[1]: Job scylla-jmx.service/start failed with result 'dependency'.
Dec 19 06:15:00 ip-172-31-14-179 systemd[1]: Dependency failed for Run Scylla Housekeeping daily mode.
-- Subject: Unit scylla-housekeeping-daily.timer has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit scylla-housekeeping-daily.timer has failed.
-- 
-- The result is dependency.
Dec 19 06:15:00 ip-172-31-14-179 systemd[1]: Job scylla-housekeeping-daily.timer/start failed with result 'dependency'.
Dec 19 06:15:00 ip-172-31-14-179 systemd[1]: Dependency failed for Run Scylla Housekeeping restart mode.
-- Subject: Unit scylla-housekeeping-restart.timer has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit scylla-housekeeping-restart.timer has failed.
-- 
-- The result is dependency.
Dec 19 06:15:00 ip-172-31-14-179 systemd[1]: Job scylla-housekeeping-restart.timer/start failed with result 'dependency'.
Dec 19 06:15:00 ip-172-31-14-179 systemd[1]: Unit scylla-server.service entered failed state.
Dec 19 06:15:00 ip-172-31-14-179 systemd[1]: scylla-server.service failed.
Dec 19 06:15:00 ip-172-31-14-179 polkitd[12175]: Unregistered Authentication Agent for unix-process:12344:76845 (system bus name :1.15, object path /org/freedesktop/PolicyKit1/Aut
[centos@ip-172-31-14-179 ~]$ 
```

[schema.txt](https://github.com/scylladb/scylla/files/1570590/schema.txt)

**Comment by tzach** [comment] 2017-12-19 09:20
@duarten is it the same as https://github.com/scylladb/scylla/issues/3068 ?

**Comment by duarten** [comment] 2017-12-19 10:11
Might be caused by #3068, yes.

**Comment by veramine** [comment] 2017-12-19 16:34
We will try without the UDT.

**Comment by veramine** [comment] 2017-12-20 00:47
I removed the UDT's from our schema.cql file and then was unable to reproduce this bug.  You're probably right that it is caused by https://github.com/scylladb/scylla/issues/3068.  Can't hit it without the UDT.

**Comment by tzach** [comment] 2017-12-20 07:21
Thanks for testing @veramine. Closing this as duplication of #3068

**Closed by tzach** 2017-12-20 07:21 UTC
Labels: bug, duplicate
