### ISSUE TITLE
Comman "nodetool decommission" failed with failed: streaming::stream_exception on large partition

### ISSUE THREAD

**Issue by aleksbykov** [scylladb/scylla#7335] opened 2020-10-05 15:51 UTC
*Installation details*
Scylla version (or git commit hash): 4.2.rc5-0.20201001.5fcc1f205c with build-id aa799d0de128964d6f55cce9d42934ea6c3b8dd5
Cluster size: 5
OS (RHEL/CentOS/Ubuntu/AWS AMI): ami-01949a028ae2ee8a7(eu-north-1)
instance type: i3en.3xlarge

Look like issue #7104, but this happened during another job, with disabled cdc and large partitions.

For writing used next scylla bench commands:
```
scylla-bench -workload=sequential -mode=write -replication-factor=3 -partition-count=300 -clustering-row-count=200000 -clustering-row-size=uniform:10..10240 -partition-offset=1001 -concurrency=10 -connection-count=10 -consistency-level=quorum -rows-per-request=10 -timeout=90s",
             "scylla-bench -workload=sequential -mode=write -replication-factor=3 -partition-count=300 -clustering-row-count=200000 -clustering-row-size=uniform:10..10240 -partition-offset=1301 -concurrency=10 -connection-count=10 -consistency-level=quorum -rows-per-request=10 -timeout=90s",
             "scylla-bench -workload=sequential -mode=write -replication-factor=3 -partition-count=400 -clustering-row-count=200000 -clustering-row-size=uniform:10..10240 -partition-offset=1601 -concurrency=10 -connection-count=10 -consistency-level=quorum -rows-per-request=10 -timeout=90s",
```

Issue detected during job https://jenkins.scylladb.com/job/scylla-4.2/job/longevity/job/longevity-large-partition-200k-pks-4days-test/5/ and scylla version 4.2.rc5-0.20201001.5fcc1f205c with build-id aa799d0de128964d6f55cce9d42934ea6c3b8dd5

Decommission was running for node3. And command failed with next output:
```
Command: 'nodetool  decommission '

Exit code: 1

Stdout:

nodetool: Scylla API server HTTP POST to URL '/storage_service/decommission' failed: streaming::stream_exception (Stream failed)
See 'nodetool help' or 'nodetool help <command>'.

Stderr:

```

messages from node3 log:
```
2020-10-02T15:44:09+00:00  longevity-large-partitions-200k-pks-db-node-f60ae5a6-3 !WARNING | scylla: [shard 2] large_data - Writing a partition with too many rows [scylla_bench/test:1130] (167920 rows)
2020-10-02T15:44:09+00:00  longevity-large-partitions-200k-pks-db-node-f60ae5a6-3 !WARNING | scylla: [shard 2] large_data - Writing a partition with too many rows [scylla_bench/test:1633] (200000 rows)
2020-10-02T15:44:11+00:00  longevity-large-partitions-200k-pks-db-node-f60ae5a6-3 !WARNING | scylla: [shard 0] large_data - Writing a partition with too many rows [scylla_bench/test:1715] (171740 rows)
2020-10-02T15:44:11+00:00  longevity-large-partitions-200k-pks-db-node-f60ae5a6-3 !INFO    | scylla: [shard 2] compaction - Compacted 2 sstables to [/var/lib/scylla/data/scylla_bench/test-e3293b60047f11eb9871000000000004/mc-5030-big-Data.db:level=0, ]. 47GB to 32GB (~67% of original) in 293115ms = 109MB/s. ~256 total partitions merged to 33.
2020-10-02T15:44:12+00:00  longevity-large-partitions-200k-pks-db-node-f60ae5a6-3 !WARNING | scylla: [shard 0] storage_service - stream_ranges failed: streaming::stream_exception (Stream failed)
2020-10-02T15:44:12+00:00  longevity-large-partitions-200k-pks-db-node-f60ae5a6-3 !WARNING | scylla: [shard 0] storage_service - unbootstrap fails to stream : streaming::stream_exception (Stream failed)
```

node3 log:  
[system.log.tar.gz](https://github.com/scylladb/scylla/files/5325954/system.log.tar.gz)

all logs available:
https://cloudius-jenkins-test.s3.amazonaws.com/f60ae5a6-78c0-4ce9-8ddd-569e1ec69552/20201002_161012/db-cluster-f60ae5a6.zip

**Comment by aleksbykov** [comment] 2020-10-05 15:52
Nodes are avialable:
```
| longevity-large-partitions-200k-pks-db-node-f60ae5a6-1      | eu-north-1a | 13.49.69.123  |
| longevity-large-partitions-200k-pks-db-node-f60ae5a6-2      | eu-north-1a | 13.49.69.58   |
| longevity-large-partitions-200k-pks-db-node-f60ae5a6-3      | eu-north-1a | 13.48.190.206 |
| longevity-large-partitions-200k-pks-db-node-f60ae5a6-4      | eu-north-1a | 13.53.173.134 |
| longevity-large-partitions-200k-pks-monitor-node-f60ae5a6-1 | eu-north-1a | 13.49.74.74   |
| longevity-large-partitions-200k-pks-db-node-f60ae5a6-6      | eu-north-1a | 13.48.29.116  |
```

**Comment by slivne** [comment] 2020-10-06 07:27
@roydahan / @aleksbykov regular question - did this work with 4.1 ?

**Comment by slivne** [comment] 2020-10-06 07:30
@aleksbykov / @roydahan are the cluster details correct - the monitor is empty !!!

**Comment by slivne** [comment] 2020-10-06 08:15
I guess it did - there seems to be a clash with replace node and with the following decomissions we have 

```
Oct 02 14:52:21 longevity-large-partitions-200k-pks-db-node-f60ae5a6-3 scylla[27539]:  [shard 0] gossip - InetAddress 10.0.1.84 is now UP, status = UNKNOWN
Oct 02 14:54:09 longevity-large-partitions-200k-pks-db-node-f60ae5a6-3 scylla[27539]:  [shard 0] storage_service - Node 10.0.1.84 is replacing existing node 10.0.1.132 with host_id=f741b346-f859-4ec6-a255-61bacca3f28b, existing_tokens={8194042127012139572, -2263766793389092288, 7947663332097687227, 1101890700986160976, 8525435248587471440, 3559137290735427680, 2970062263310643281, -6236723016919399865, -2581960640586807283, 5781900056220124450, -7100238659327292874, 3579463154889268306, -8255946256396406174, -54797532837377922, -627177908919518779, -301126321056281709, -7887358439857831408, -5249164022425344589, 6897748743493846362, 2744189509985555521, 5781529260201890852, 5331204342281462486, 6982307299691050724, -5866414865685331852, -6602125229138292306, 9032329138109185464, -4278166502033306447, 1458557205634280028, -6474095353848449134, 4960588179352404783, 3139927996510518676, -4304871739623217223, -5363576131334276160, 170891662886489664, -2376391022270765597, -459500768593945987, 2185035945679323550, -4950150081599654518, -3459048754296057217, -1374061605560086917, 1596669365769014745, 6049242432727989813, -4818272345062897004, -8915651433401939172, 6902580048278278372, 7055496971309380416, 4968878755176747173, 6023923608545600343, 3014154205739214991, 4496436599091966081, -8609535173850128348, -3639561513420002703, 1791785540294354731, -4489709856719835213, -3350294400688425147, 4731262578161244760, 7693387946087034390, -208860478075309258, 3761061965122358994, 5739690498871229367, 4887090957751682796, -3610570046847676873, -8385540538521333910, 450210958661523917, 1906186836538488641, -6769935183776881336, -8489701805274801160, 852522241840875285, 1548491623338320393, -4207272059571790332, -2919226042021207893, -2501205245414588068, 2361827037125474333, 661092380693389069, -8978566221597216402, 2892891005592174131, 3075909625012364340, 1532205896884470270, 1087213046494123072, -9023909632799877416, 6427209214828045488, 2092005298329470620, 2696962268435396205, -7539338100601597457, 3690560465851265072, -1329856498447627113, -2525801710574550604, -5963183725056469397, 200341612215562794, -7246791151230476742, 7372290349709092414, 963285060279796418, -1032066836892774107, -446502225378705542, -5416027910771817222, 755368397916011171, 8653781680476606789, 8154669628216886749, -215715651711779700, 9114032480783934710, 3589634580330480234, 7697951979407553767, 6300149279592871520, 3684740662313249032, 5908708512709733953, -4128330847012360917, -4876129484073496477, -8275806450109483309, 4003109228000353266, -5373272480282740457, -2059048553775193323, -6908004088957491727, -2256292770252029512, -7049433838789766955, -8309432001467122182, -1977482900239488625, -818822296772291495, 874872434411868091, -4480274680333980223, 5187453558926947239, -5079832499290690633, -7670927432122501171, 7585886839383849902, 186895096110792031, 1367282829252500847, -2844455797184383453, 1876913744609255938, -460235052686388430, 754801953868990202, 5467553224154145315, 2349629292534207100, 6144432052478380311, 24170355972695466, -8913410864574172610, -2972751779992876926, 3585819844278053417, 7911142847049214550, -7196416640391238410, 315393225284426847, -8359861690182983090, 5250090776246156054, 1574168953393834136, 8907649921876358550, 677256874304165983, -784285125029802345, 2887618065192065412, -4243851590145218244, 3157457525161824087, -5553176088018156163, -5719073332723154947, 5823681928116285512, 3349659165759662126, -8367289022365196740, -3102866309135080695, 1896561421677487387, 6491960712915881294, 4956247082348912242, 5697568984745923184, -4132401573708803952, 7233429392673853880, 1673876005704947523, -6206605581499491663, -5341257088257354119, -6151323220369691395, 8659260585497679091, 4107335514625019191, -5759078663394449587, 783488389476955106, 3678630682071522273, -5914457094394940545, 3707289485791141620, -921580498399691265, -7572305973502953303, 6861325641148415876, 6986054629999258777, -3640707361679278496, 3434165395960828690, 8017010872000311181, -7428434101187895198, 6069871850365879701, 6946430313153353109, -8038885384630660166, 156395708407780090, -3122176695487146252, 6433959195302326178, -1781876436328208762, -5661137648883486999, 8900188096541885620, -3407218070644565521, -4977279392546554175, 6792551576209312819, 5007467042641542562, 8930275531380448606, -4134420413114781458, 2182781787468690404, 7280116398272503833, -2164804131307553162, -3304200309227379841, 6566003214946659935, -1761433591382191867, -820386598379853862, 7907198258086896182, 8055715760149702658, -1300354964010189276, 6633747538385995903, 4926335729662492538, -8531043523330564471, 977834805349852736, 2771874128042110083, -415227514849611134, -2581200558571439757, -5717187208845172841, 2189770174853261342, 1123549035483660807, 7256396441865001830, -4652948787923947158, -2372999979467747480, 7237344352572439013, 3032512628762920213, 190689905506498655, 4264470682601199005, 1477384788786984866, 5240155593034794556, 1403380748489319455, -8505132706288281497, -1437752264194078935, 2384476694339653889, 4854275553087505850, -4901314123837563889, -8504362984143363648, -6078723686170880621, -2358575798749178072, -5730774055514562148, -7648857958663240878, -1788628879985509043, 5177096402614039894, -3246677540332346986, -1773167377090573456, 2657239531643746353, 464297767058910219, -8193939049137627128, 3130495394977690027, -8394917045194812940, -6295186820513004544, -8479280636268390791, -7597771944416382333, -6618990353361895894, -1259959831941635182, -8705185518347755884, 6785966648324865609, 4671290713849441331, -1446393361484894956, -86048992379067699, -5426356372183671581, 4715043065588861986, -3774507703831696874}, replacing_tokens={-3774507703831696874, 4715043065588861986, -5426356372183671581, -86048992379067699, -1446393361484894956, 4671290713849441331, 6785966648324865609, -8705185518347755884, -1259959831941635182, -6618990353361895894, -7597771944416382333, -8479280636268390791, -6295186820513004544, -8394917045194812940, 3130495394977690027, -8193939049137627128, 464297767058910219, 2657239531643746353, -1773167377090573456, -3246677540332346986, 5177096402614039894, -1788628879985509043, -7648857958663240878, -5730774055514562148, -2358575798749178072, -6078723686170880621, -8504362984143363648, -4901314123837563889, 4854275553087505850, 2384476694339653889, -1437752264194078935, -8505132706288281497, 1403380748489319455, 5240155593034794556, 1477384788786984866, 4264470682601199005, 190689905506498655, 3032512628762920213, 7237344352572439013, -2372999979467747480, -4652948787923947158, 7256396441865001830, 1123549035483660807, 2189770174853261342, -5717187208845172841, -2581200558571439757, -415227514849611134, 2771874128042110083, 977834805349852736, -8531043523330564471, 4926335729662492538, 6633747538385995903, -1300354964010189276, 8055715760149702658, 7907198258086896182, -820386598379853862, -1761433591382191867, 6566003214946659935, -3304200309227379841, -2164804131307553162, 7280116398272503833, 2182781787468690404, -4134420413114781458, 8930275531380448606, 5007467042641542562, 6792551576209312819, -4977279392546554175, -3407218070644565521, 8900188096541885620, -5661137648883486999, -1781876436328208762, 6433959195302326178, -3122176695487146252, 156395708407780090, -8038885384630660166, 6946430313153353109, 6069871850365879701, -7428434101187895198, 8017010872000311181, 3434165395960828690, -3640707361679278496, 6986054629999258777, 6861325641148415876, -7572305973502953303, -921580498399691265, 3707289485791141620, -5914457094394940545, 3678630682071522273, 783488389476955106, -5759078663394449587, 4107335514625019191, 8659260585497679091, -6151323220369691395, -5341257088257354119, -6206605581499491663, 1673876005704947523, 7233429392673853880, -4132401573708803952, 5697568984745923184, 4956247082348912242, 6491960712915881294, 1896561421677487387, -3102866309135080695, -8367289022365196740, 3349659165759662126, 5823681928116285512, -5719073332723154947, -5553176088018156163, 3157457525161824087, -4243851590145218244, 2887618065192065412, -784285125029802345, 677256874304165983, 8907649921876358550, 1574168953393834136, 5250090776246156054, -8359861690182983090, 315393225284426847, -7196416640391238410, 7911142847049214550, 3585819844278053417, -2972751779992876926, -8913410864574172610, 24170355972695466, 6144432052478380311, 2349629292534207100, 5467553224154145315, 754801953868990202, -460235052686388430, -4489709856719835213, -3639561513420002703, 1791785540294354731, 3014154205739214991, 4968878755176747173, 6023923608545600343, 1596669365769014745, -1374061605560086917, -3459048754296057217, -8915651433401939172, 6049242432727989813, -4818272345062897004, -459500768593945987, -2376391022270765597, -208860478075309258, 3761061965122358994, 4496436599091966081, -8609535173850128348, 170891662886489664, -4304871739623217223, -5363576131334276160, -5866414865685331852, -6474095353848449134, 4960588179352404783, 3139927996510518676, 3579463154889268306, -7100238659327292874, -8255946256396406174, -54797532837377922, -8978566221597216402, 5781900056220124450, 8194042127012139572, -4278166502033306447, 1458557205634280028, 7947663332097687227, 1101890700986160976, -2263766793389092288, 6902580048278278372, 7055496971309380416, 1367282829252500847, 3559137290735427680, 8525435248587471440, 2185035945679323550, -4950150081599654518, -7887358439857831408, -5249164022425344589, -301126321056281709, -627177908919518779, 4731262578161244760, -3350294400688425147, 7693387946087034390, 2970062263310643281, 6897748743493846362, -6236723016919399865, -2581960640586807283, 5781529260201890852, 5331204342281462486, 2744189509985555521, 6982307299691050724, -6602125229138292306, 9032329138109185464, 5739690498871229367, 4887090957751682796, -2919226042021207893, -3610570046847676873, -8385540538521333910, 450210958661523917, 1906186836538488641, -6769935183776881336, -8489701805274801160, -2844455797184383453, 852522241840875285, 1548491623338320393, -4207272059571790332, -2501205245414588068, 2361827037125474333, 661092380693389069, 3075909625012364340, 2892891005592174131, -9023909632799877416, 1532205896884470270, 1087213046494123072, 186895096110792031, 7585886839383849902, 6427209214828045488, 2092005298329470620, -7539338100601597457, 2696962268435396205, 3690560465851265072, -1329856498447627113, -2525801710574550604, 5187453558926947239, -4480274680333980223, -7246791151230476742, -5963183725056469397, 200341612215562794, 963285060279796418, 7372290349709092414, 755368397916011171, -1032066836892774107, -446502225378705542, -5416027910771817222, 8653781680476606789, 8154669628216886749, 9114032480783934710, -215715651711779700, 6300149279592871520, 3589634580330480234, 7697951979407553767, 5908708512709733953, 3684740662313249032, -4128330847012360917, -4876129484073496477, -7049433838789766955, -8309432001467122182, -5373272480282740457, -8275806450109483309, 4003109228000353266, -2059048553775193323, -2256292770252029512, -6908004088957491727, -1977482900239488625, -818822296772291495, 874872434411868091, -5079832499290690633, -7670927432122501171, 1876913744609255938}
.
```
Not sure if replace succeeded or not need if it didn't the decomission should have been toward the new node 10.0.1.84 and not the old one 10.0.1.132


```
Oct 02 15:30:50 longevity-large-partitions-200k-pks-db-node-f60ae5a6-3 scylla[27539]:  [shard 0] range_streamer - Unbootstrap with [10.0.1.132, 10.0.3.108, 10.0.0.120, 10.0.3.252] for keyspace=system_distributed started, nodes_to_stream=4
.
Oct 02 15:30:50 longevity-large-partitions-200k-pks-db-node-f60ae5a6-3 scylla[27539]:  [shard 0] stream_session - [Stream #40736ea1-04c4-11eb-a07b-000000000003] Executing streaming plan for Unbootstrap-system_distributed-index-0 with peers={10.0.1.132}, master

.
.
.
Oct 02 15:30:50 longevity-large-partitions-200k-pks-db-node-f60ae5a6-3 scylla[27539]:  [shard 0] range_streamer - Unbootstrap starts, nr_ranges_remaining=2825
Oct 02 15:30:50 longevity-large-partitions-200k-pks-db-node-f60ae5a6-3 scylla[27539]:  [shard 0] range_streamer - Unbootstrap with [10.0.1.132, 10.0.3.108, 10.0.0.120, 10.0.3.252] for keyspace=system_distributed started, nodes_to_stream=4
Oct 02 15:30:50 longevity-large-partitions-200k-pks-db-node-f60ae5a6-3 scylla[27539]:  [shard 0] range_streamer - Unbootstrap with 10.0.1.132 for keyspace=system_distributed, streaming [0, 20) out of 207 ranges
```

I don't this the previous replace ended - looking for the info

**Comment by slivne** [comment] 2020-10-06 08:26
@aleksbykov / @roydahan I do not think the replace ended and you started a decommission - can you check the sct logs as to why you thought the operation ended 

I need nodetool status output from sct prior after the replace ended and before running the decommission 

I don't think we saw this bug ever:
- we may have an issue with allowing topology changes while replacing a node need to be checked
- we may have a bug allowing decomission to start although one of the replicas is down - it should not be allowed

**Comment by aleksbykov** [comment] 2020-10-06 08:32
> @aleksbykov / @roydahan are the cluster details correct - the monitor is empty !!!

Filter for 7days.

**Comment by aleksbykov** [comment] 2020-10-06 08:56
@slivne 

I didn't move this comment from #7104, but before this nemesis TerminateAndReplace was run on node5. But due to sct issue, the new node was not replace old one properly.
After it the cluster status was:
```
Datacenter: eu-north
====================
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address     Load       Tokens       Owns    Host ID                               Rack
DN  10.0.1.132  875.69 GB  256          ?       f741b346-f859-4ec6-a255-61bacca3f28b  1a
UN  10.0.0.120  1.04 TB    256          ?       5a2a4fe9-dd74-45bb-9e9c-c70b6f4db31b  1a
UN  10.0.1.200  932.4 GB   256          ?       d489cf27-c028-4ee3-925c-64a0864fbcb7  1a
UN  10.0.3.108  1.07 TB    256          ?       5abe351c-21d4-42b3-a87d-1cd4f50f0656  1a
UN  10.0.3.252  1.17 TB    256          ?       b8f92a84-4ebf-493e-a87e-8add555ffc20  1a


Datacenter: eu-north
====================
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address     Load       Tokens       Owns    Host ID                               Rack
DN  10.0.1.132  875.69 GB  256          ?       f741b346-f859-4ec6-a255-61bacca3f28b  1a
UN  10.0.0.120  1.04 TB    256          ?       5a2a4fe9-dd74-45bb-9e9c-c70b6f4db31b  1a
UN  10.0.1.200  932.4 GB   256          ?       d489cf27-c028-4ee3-925c-64a0864fbcb7  1a
UN  10.0.3.108  1.07 TB    256          ?       5abe351c-21d4-42b3-a87d-1cd4f50f0656  1a
UN  10.0.3.252  1.17 TB    256          ?       b8f92a84-4ebf-493e-a87e-8add555ffc20  1a



Datacenter: eu-north
====================
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address     Load       Tokens       Owns    Host ID                               Rack
DN  10.0.1.132  875.69 GB  256          ?       f741b346-f859-4ec6-a255-61bacca3f28b  1a
UN  10.0.0.120  1.05 TB    256          ?       5a2a4fe9-dd74-45bb-9e9c-c70b6f4db31b  1a
UN  10.0.1.200  932.4 GB   256          ?       d489cf27-c028-4ee3-925c-64a0864fbcb7  1a
UN  10.0.3.108  1.07 TB    256          ?       5abe351c-21d4-42b3-a87d-1cd4f50f0656  1a
UN  10.0.3.252  1.17 TB    256          ?       b8f92a84-4ebf-493e-a87e-8add555ffc20  1a
```
Before next nemesis Decommission was run on node3 cluster status was:
```
Datacenter: eu-north
====================
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address     Load       Tokens       Owns    Host ID                               Rack
DN  10.0.1.132  ?          256          ?       f741b346-f859-4ec6-a255-61bacca3f28b  1a
UN  10.0.0.120  ?          256          ?       5a2a4fe9-dd74-45bb-9e9c-c70b6f4db31b  1a
UN  10.0.1.200  ?          256          ?       d489cf27-c028-4ee3-925c-64a0864fbcb7  1a
UN  10.0.3.108  ?          256          ?       5abe351c-21d4-42b3-a87d-1cd4f50f0656  1a
UN  10.0.3.252  ?          256          ?       b8f92a84-4ebf-493e-a87e-8add555ffc20  1a
```
after the Decommission nemesis cluster status:
```
Datacenter: eu-north
====================
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address     Load       Tokens       Owns    Host ID                               Rack
DN  10.0.1.132  875.69 GB  256          ?       f741b346-f859-4ec6-a255-61bacca3f28b  1a
UN  10.0.0.120  933.17 GB  256          ?       5a2a4fe9-dd74-45bb-9e9c-c70b6f4db31b  1a
UL  10.0.1.200  900.04 GB  256          ?       d489cf27-c028-4ee3-925c-64a0864fbcb7  1a
UN  10.0.3.108  1022.26 GB  256          ?       5abe351c-21d4-42b3-a87d-1cd4f50f0656  1a
UN  10.0.3.252  1.23 TB    256          ?       b8f92a84-4ebf-493e-a87e-8add555ffc20  1a
```

**Comment by slivne** [comment] 2020-10-06 09:35
Thanks for conforming that replace did not succeed and you have node 10.0.1.132 Down Normal when you try todo a decommission I'll try to reproduce this locally and see if we have a bug in decommission.

Once I reproduce I'll try on previous versions and see if this is a regression.

**Comment by slivne** [comment] 2020-10-06 21:26
- we may have an issue with allowing topology changes while replacing a node need to be checked

https://github.com/scylladb/scylla/issues/7351

- we may have a bug allowing decommission to start although one of the replicas is down - it should not be allowed

I think this is by design and not a bug  - what happens is that we retry the failed streaming - cassandra does the same.

**Comment by slivne** [comment] 2020-10-06 21:26
I am closing this issue as we have a specific issue for replace + decomission

**Closed by slivne** 2020-10-06 21:26 UTC
