### ISSUE TITLE
resharding_mv_test fails: Expected [[1]] from select count(*) from ks.tm_table_mv_0 where id=1601, but got [[0]]

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#8108] opened 2021-02-17 08:51 UTC
Seen in https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/745/testReport/resharding_test/ReshardingTest_nodes4_with_TimeWindowCompactionStrategy/resharding_mv_test/
With scylla version 495b7b5596ab5f2bd1f1149f5b56c0e550716f79
```
Traceback (most recent call last):
  File "/usr/lib64/python3.7/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/usr/lib64/python3.7/unittest/case.py", line 645, in run
    testMethod()
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/resharding_test.py", line 466, in resharding_mv_test
    assert_one(session, query.format(tm.keyspace, mv.mv_name, i), [1])
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/dtest.py", line 1643, in inner
    return func(*args, **kwargs)
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/assertions.py", line 68, in assert_one
    assert list_res == [expected], "Expected %s from %s, but got %s" % ([expected], query, list_res)
AssertionError: Expected [[1]] from select count(*) from ks.tm_table_mv_0 where id=1601, but got [[0]]
```

I'm not sure when exactly the regression happened because it looks like the tests hasn't run on master for awhile now.
It is passing for me against 4.4 at e11ae8c58 so the regression apparently happened after 4.4 was forked.

**Comment by bhalevy** [comment] 2021-02-17 08:51
@raphaelsc please look into this.

**Comment by bhalevy** [comment] 2021-02-23 11:55
Bisected down to aec231ba2eb70ce3eedd4fea0acf1ef9ff833641

**Comment by denesb** [comment] 2021-03-04 14:40
@bhalevy this is passing for me on local master. Is it still failing in jenkins?

**Comment by bhalevy** [comment] 2021-03-04 15:50
@denesb it's passing since https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/755/testReport/resharding_test/ReshardingTest_nodes4_with_TimeWindowCompactionStrategy/resharding_mv_test/
scylla version 1d9b5911fe554a4dd4baeed5d156813026042b5b
Can you tell what fixed it?
I'd like to make sure the issue is understood.

**Comment by denesb** [comment] 2021-03-04 16:05
This is very likely the same as https://github.com/scylladb/scylla/issues/8138, we have a point query which returns no data due to the sstable reader using a dangling range.

Duplicate of https://github.com/scylladb/scylla/issues/8138.

**Closed by denesb** 2021-03-04 16:05 UTC
Labels: bug, resharding
