### ISSUE TITLE
compactionstats pending tasks information seems broken

### ISSUE THREAD

**Issue by glommer** [scylladb/scylla#4444] opened 2019-04-18 14:06 UTC
HEAD: 134b59a425da71f6dfa86332322cc63d47a88cd7

```
nodetool compactionstats
pending tasks: 858255
- keyspace1.standard1: 858255

id     compaction type keyspace  table     completed total   unit progress
<none> COMPACTION      keyspace1 standard1 189342    439936  keys 43.04%  
<none> COMPACTION      keyspace1 standard1 1070363   1843584 keys 58.06%  
<none> COMPACTION      keyspace1 standard1 2764672   2821632 keys 97.98%  
<none> COMPACTION      keyspace1 standard1 1160640   1838720 keys 63.12%  
<none> COMPACTION      keyspace1 standard1 17778     2125952 keys 0.84%   
<none> COMPACTION      keyspace1 standard1 2370353   3228160 keys 73.43%  
<none> COMPACTION      keyspace1 standard1 162358    2119168 keys 7.66%   
<none> COMPACTION      keyspace1 standard1 808445    2696704 keys 29.98%  
Active compaction remaining time :   0h00m00s
```

**Comment by slivne** [comment] 2019-04-18 14:25
Reproducer ?

**Comment by slivne** [comment] 2019-04-18 14:27
Duplicate of https://github.com/scylladb/scylla/issues/4228

But a reprducer will help

**Comment by glommer** [comment] 2019-04-18 14:29
I ingested data with cassandra stress, stopped ingesting, and called nodetool compactionstats in a loop. Nothing special

**Comment by slivne** [comment] 2019-04-18 15:05
Ok thaks closing as duplicate

**Closed by slivne** 2019-04-18 15:05 UTC
