### ISSUE TITLE
SizeTieredCompactionStrategy not bringing the system down to zero backlog

### ISSUE THREAD

**Issue by glommer** [scylladb/scylla#4588] opened 2019-06-21 20:19 UTC
@avikivity while trying to understand some weird behavior I am seeing in the field with the compaction controller, I realized that we never really correctly implemented the drive to bring the system down to zero backlog.

The code reads:

```
    // If we are not enforcing min_threshold explicitly, try any pair of SStables in the same tier.
    if (!cfs.compaction_enforce_min_threshold() && is_any_bucket_interesting(buckets, 2)) {
        std::vector<sstables::shared_sstable> most_interesting = most_interesting_bucket(std::move(buckets), 2, max_threshold);
        return sstables::compaction_descriptor(std::move(most_interesting));
    }
```

This works well in our examples, where all data is well behaved and the tiers are more or less of the same size. But in practice because this will only compact things at the same tier, we can still be left with quite a bit of backlog, since we won't compact cross-tier. I believe this is what is behind recent reports of latency with the controller shares being too high.

There are many ways to pick the best two cross-tiers to compact: 
- the smallest tiers
- the biggest tiers
- the closest in size (keep increasing the threshold for group pertinence until we find a match)

Please let me know which one you prefer and I'll code it (it will be more time efficient if we agree beforehand)

**Comment by bhalevy** [comment] 2019-06-22 03:08
Cc @raphaelsc

**Comment by avikivity** [comment] 2019-06-25 16:16
The closest in size is I think the best choice. But we have to consider multiple tables too. We should only do cross-tier compactions if there are no same-tier compaction remaining globally. This is because cross-tier compactions have higher write amplification (closest in size minimizes write amplification, but still). If we wait until all same-tier compactions are done, we do efficient work first, and the less-efficient work can be deferred to a point where there is more efficient work to do (because new sstables were written).

**Comment by glommer** [comment] 2019-06-25 16:26
For the record my preference is closest in size as well. I also intend to enhance the compaction descriptor with an idle flag (Some of the existing compactions can be moved to idle state: LCS pushing to highest levels, and some of the SizeTiered existing ones like tombstone compaction)

I will cook a patch as soon as possible

**Comment by glommer** [comment] 2019-06-26 13:17
I took a slightly different, and simpler approach: just compact everything we find on idle.
It can look like a hammer at first, but I'll note that if we reached that point in the code, we already know there are no other better alternatives, and in particular that there are no other two SSTables in the same level that can be compacted together, and there are at most nr_tier SSTables.

I think this is justified and simplifies our lives and reasoning a lot, without being inefficient.

I will send the PR as is, and if you feel otherwise let me know and we'll look again

**Comment by avikivity** [comment] 2019-06-26 16:16
You mean a major compaction? That means that as soon as we idle we'll start compacting eveything within sight. The first memtable flush in a previously idle shard can start a multi-terabyte compaction.

Granted, closest-size compaction will eventually do the same, but it will start with more worthwhile compactions that will leave room for a better compaction to take over when they finish, instead of starting a really large compaction.

**Comment by glommer** [comment] 2019-06-26 16:22
Yes, it is essentially a major compaction.
But as you noted yourself, that multi-TB compaction will happen anyway if we're idle and those are the only two SSTables available.

If we are at this point (and idle), we already know that there aren't many SStables of similar size. The threshold for size turns out to be quite large, around 50% for similarity. We haven't found two that are similar up until this point.

**Comment by glommer** [comment] 2019-06-27 12:55
@avikivity there is another way I thought that we could do this:

sort the existing tables with idle work according to their backlog.
Compact the table with the lowest backlog.

This way we guarantee that in case we're idle, we do the least amount of work possible

**Comment by glommer** [comment] 2019-07-08 11:37
PR for this is already sent for a week.

**Comment by glommer** [comment] 2019-07-11 15:26
@avikivity @slivne since this ended up being harder than expected, I put together a document identifying the problems we have so far, and what would be a good redesign-friendly way of solving them.

https://docs.google.com/document/d/17IS2e0aOB9WgP2bYAjy2cxphM89s5ruI16oA6ka22ME/edit

Let's get some agreement first and then move to an implementation.

**Comment by glommer** [comment] 2019-07-11 17:00
@raphaelsc and @bhalevy please comment on the above too

**Comment by glommer** [comment] 2019-07-15 18:50
Any comments on my solution sketch? I'd like to get started on this.

**Comment by dorlaor** [comment] 2019-09-06 06:06
@raphaelsc @bhalevy although you're busy with ICS you need to review this one too

**Comment by glommer** [comment] 2019-09-07 02:11
Here's some more ideas that I had recently on how to fix this:

I believe we should rework the sstable set selection entirely:
- Define the maximum amount of disk writes per day we are willing to do.
- Avoid parallel compactions (so that a single compaction has more bandwidth)
- Select the compaction out of the compaction set that reduces the backlog the most
- Use maximum amount of disk writes to decide whether a compaction is merited. Any compaction, not just the idle ones: If we're doing too much already best to make min_threshold = 4 than 2 in practice and wait.
- Only allow parallel compactions on tiers lower than the current tier, and if the total amount of bytes written in the last 24h is lower than a threshold, and if the amount of shares is higher than a threshold.

**Comment by avikivity** [comment] 2019-09-07 14:12
You can't do STCS without parallel compactions. Say we have N tiers and use base B (typically 2 or 4). Then write amplification is N. In order to keep constant shares for compaction, compaction rate is N*WR (where WR is the write rate). The size of the highest tier is S*B^N (where S is the L0 sstable size). The time to compact the highest tier is therefore (S*B^N)/(N*WR). The time to generate an L0 sstble is S/WR. Dividing the last two numbers gives us the number of L0 sstables generated during compaction; this is (B^N)/N.

For B=4, N=4 this is 64, so by the time the highest tier compaction completes, we'll have 64 L0 sstables, destroying read amplification.

**Comment by avikivity** [comment] 2019-09-11 17:36
I thought of redefining backlog so that one sstable per tier is zero backlog, but that doesn't work well because sometimes we'll end up with a tier with zero sstables. It's not reasonable to have both zero sstables in a tier and one sstable in a tier count as the same backlog, and negative backlog also doesn't make sense.

**Comment by avikivity** [comment] 2019-09-11 17:38
Another option is to remove a tier's backlog if that tier isn't compacting. This makes some sense because if the tier isn't compacting, then the shares we get for that tier will go towards some other tier's compaction.

**Comment by bhalevy** [comment] 2019-10-23 08:43
@glommer is the patch series "Try harder to move STCS towards zero-backlog" merged in f0fc888381d7264d1b49b6395051bc1170fe1f94 sufficient to resolve this issue?

**Comment by slivne** [comment] 2020-03-24 22:43
@glommer ping

**Comment by glommer** [comment] 2020-03-24 22:58
not even close

**Comment by raphaelsc** [comment] 2022-01-24 20:15
![shares_out (another copy)](https://user-images.githubusercontent.com/1409139/150856568-687264f2-1196-47c4-a9a8-d89b66cdff53.png)

simple test easily demonstrates that compaction shares will take the steep slope once the normalized backlog (backlog in bytes / shard_memory) is higher than normalization_factor (30). Example, with 1G of memory per shard, this would happen as soon as disk usage for size-tiered tables sum up to 30G per shard. which can happen easily in production.

The main problem with controller implementation, as we know it, is that it was based on the idea that it should bring the system to a state of zero amplification, but that's clearly wrong as each strategy has its own intent on what optimal amplification should be, size-tiered for example allows extra space amplification to achieve faster write rates on steady state.

**Comment by raphaelsc** [comment] 2022-02-12 00:12
![results_backlog_changes](https://user-images.githubusercontent.com/1409139/153687219-32368a35-ac63-461b-a362-64dbe8449a00.png)

**Closed** 2022-02-25 12:34 UTC
Labels: compaction

**Comment by avikivity** [comment] 2022-08-16 13:04
Major change, and not a regression, not backporting.
