### ISSUE TITLE
Can not start Scylla servers after yum update to RHEL 7.2

### ISSUE THREAD

**Issue by eyalgutkind** [scylladb/scylla#1818] opened 2016-11-07 20:02 UTC
*Installation details*
Scylla version (or git commit hash):1.3
[ec2-user@ip-172-31-46-121 ~]$ scylla --version
1.3.4-20161103.ef4332a
Cluster size:1 node
OS (RHEL/CentOS/Ubuntu/AWS AMI): RHEL 7.2, RHEL-7.2_HVM_GA-20151112-x86_64-1-Hourly2-GP2 (ami-775e4f16)

*Hardware details (for performance issues)*      c3.8xlarge

When installing Scylla on a RHEL 7.2 system without updating it  (sudo yum update -y) the installation and starting of Scylla following the scylla_setup script is working.
However, if doing the same on a node that was yum updated the following is the message received when starting Scylla.

[ec2-user@ip-172-31-46-121 ~]$ sudo systemctl start scylla-server.service
[ec2-user@ip-172-31-46-121 ~]$
Broadcast message from systemd-journald@ip-172-31-46-121.us-west-2.compute.internal (Mon 2016-11-07 14:51:21 EST):

systemd[1]: Caught <ABRT>, dumped core as pid 9600.

Broadcast message from systemd-journald@ip-172-31-46-121.us-west-2.compute.internal (Mon 2016-11-07 14:51:21 EST):

systemd[1]: Freezing execution.

Message from syslogd@ip-172-31-46-121 at Nov  7 14:51:21 ...
 systemd:Caught <ABRT>, dumped core as pid 9600.

Message from syslogd@ip-172-31-46-121 at Nov  7 14:51:21 ...
 systemd:Freezing execution.

And the error when trying again is a bit different:
[ec2-user@ip-172-31-46-121 ~]$ sudo systemctl start scylla-server.service
Failed to start scylla-server.service: Activation of org.freedesktop.systemd1 timed out
See system logs and 'systemctl status scylla-server.service' for details.

here is the journalctl information 
Nov 07 14:58:03 ip-172-31-46-121.us-west-2.compute.internal sudo[9866]: ec2-user : TTY=pts/0 ; PWD=/home/ec2-user ; USER=root ; COMMAND=/bin/systemctl start scylla-server.ser
Nov 07 14:58:03 ip-172-31-46-121.us-west-2.compute.internal polkitd[742]: Registered Authentication Agent for unix-process:9867:88997 (system bus name :1.22 [/usr/bin/pkttyag
Nov 07 14:58:28 ip-172-31-46-121.us-west-2.compute.internal dbus-daemon[743]: dbus[743]: [system] Failed to activate service 'org.freedesktop.systemd1': timed out
Nov 07 14:58:28 ip-172-31-46-121.us-west-2.compute.internal dbus[743]: [system] Failed to activate service 'org.freedesktop.systemd1': timed out
Nov 07 14:58:28 ip-172-31-46-121.us-west-2.compute.internal polkitd[742]: Unregistered Authentication Agent for unix-process:9867:88997 (system bus name :1.22, object path /o
lines 1219-1251/1251 (END)

**Comment by dorlaor** [comment] 2016-11-07 21:45
There was a core dump so you should retrieve the trace.
The logs doesn't show any valuable data other than a bad auth

**Comment by tzach** [comment] 2016-11-08 07:02
> systemd[1]: Caught <ABRT>, dumped core as pid 9600.

Its not the source issue, but one of the [REHL prerequisite](http://www.scylladb.com/doc/getting-started-rpm/#prerequisites) is to remove ARBT. 

My guess the problem is related to permission to one of Scylla directories, either to read or write, or maybe related to SELinux. Did you disable it as part of scylla_setup?

**Comment by slivne** [comment] 2016-11-14 12:29
@syuu1228 any insight ?

**Comment by slivne** [comment] 2016-11-24 14:47
I think that what happend is that you ended up with an unsupported systemd version (that has a bug)

#1846 

closing this issue

**Closed by slivne** 2016-11-24 14:47 UTC
