### ISSUE TITLE
sstabledump with Unknown type Exception

### ISSUE THREAD

**Issue by infordb** [scylladb/scylla#2450] opened 2017-06-07 03:43 UTC
*Installation details*
Scylla version (or git commit hash): 1.7.1

Exception occurs when compiling a sstable using udt type with sstabledump.

[root]fomstap02:/home/scylla/data/cycling/cyclist_stats-1d7245a04b2911e7945c000000000001>sstabledump cycling-cyclist_stats-ka-9-Data.db
Exception in thread "main" org.apache.cassandra.exceptions.InvalidRequestException: Unknown type cycling.basic_info
        at org.apache.cassandra.cql3.CQL3Type$Raw$RawUT.prepare(CQL3Type.java:745)
        at org.apache.cassandra.cql3.CQL3Type$Raw.prepareInternal(CQL3Type.java:533)
        at org.apache.cassandra.schema.CQLTypeParser.parse(CQLTypeParser.java:53)
        at org.apache.cassandra.schema.SchemaKeyspace.createColumnFromRow(SchemaKeyspace.java:1011)
        at org.apache.cassandra.schema.SchemaKeyspace.lambda$fetchColumns$12(SchemaKeyspace.java:995)
        at java.lang.Iterable.forEach(Iterable.java:75)
        at org.apache.cassandra.schema.SchemaKeyspace.fetchColumns(SchemaKeyspace.java:995)
        at org.apache.cassandra.schema.SchemaKeyspace.fetchTable(SchemaKeyspace.java:949)
        at org.apache.cassandra.schema.SchemaKeyspace.fetchTables(SchemaKeyspace.java:928)
        at org.apache.cassandra.schema.SchemaKeyspace.fetchKeyspace(SchemaKeyspace.java:891)
        at org.apache.cassandra.schema.SchemaKeyspace.fetchKeyspacesWithout(SchemaKeyspace.java:868)
        at org.apache.cassandra.schema.SchemaKeyspace.fetchNonSystemKeyspaces(SchemaKeyspace.java:856)
        at org.apache.cassandra.config.Schema.loadFromDisk(Schema.java:136)
        at org.apache.cassandra.config.Schema.loadFromDiskForTool(Schema.java:145)
        at com.scylladb.tools.SSTableExport.metadataFromSSTable(SSTableExport.java:26)
        at org.apache.cassandra.tools.SSTableExport.run(SSTableExport.java:192)
        at com.scylladb.tools.SSTableExport.main(SSTableExport.java:37)

----- test script -----
CREATE KEYSPACE cycling WITH replication = {'class': 'SimpleStrategy', 'replication_factor': '1'}  AND durable_writes = true;

CREATE TYPE cycling.basic_info (
  birthday timestamp,
  nationality text,
  weight text,
  height text
);

CREATE TABLE cycling.cyclist_stats ( id uuid PRIMARY KEY, lastname text, basics FROZEN<basic_info>);  

INSERT INTO cycling.cyclist_stats (id, lastname, basics) VALUES (
  e7ae5cf3-d358-4d99-b900-85902fda9bb0, 
  'FRAME', 
  { birthday : '1993-06-18', nationality : 'New Zealand', weight : null, height : null }
);

**Comment by slivne** [comment] 2017-06-07 06:48
duplicate of scylladb/scylla-tools-java#27

calle can you please find the missing backport and test using the released artifacts - I expect you do have something on top of what the official 1.7 branch has.

**Comment by elcallio** [comment] 2017-06-07 08:03
According to both git add plain diff, there is nothing related differing between 1.8 and 1.7. (Nor my local repo for that matter). 
The best I can come up with is that we somehow don't provide the correct config to sstableexport, thus is does not find the right schemas, but one would think that should fail earlier.
I'm not sure how the packaging sets things up, but it is imperative that a "cassandra.yaml" exists in the classpath of the running tool, and that "datadirs" in that config point to the scylla data dir. For schema loading.

**Comment by elcallio** [comment] 2017-06-12 12:56
So there is a nasty bug, in either origin, scylla or both. And it only really applies to pre-1.8 scylla, i.e. when we need to run the legacy schema migrator to load schemas. 
For user types, there is no regular columns from which the migrator can get a timestamp using regular CQL (we currently ignore this in 1.8, which is also a bug/missing feature). 
It instead opens a row iterator into the partition of the user type entry it is reading, and tries to get the timestamp from the "primary key liveness info". 
However, more often than not, in a table generated by scylla, this info will not be set (but neither is deletion, thus rows are live and fine and dandy), so the code picks up "NO_TIMESTAMP", which, when used in generating new mutations for the (3.x) user types table will cause all data to be skipped, due to deletion shadowing. I.e. the intended flow breaks badly, and we get no data. 
A quick workaround fix (avoiding scylla changes) is to simply check if we don't have a valid liveness info (but are still  reading the data), and are in the "tool" mode, simply give back "now" as timestamp, and we should be ok.

**Comment by slivne** [comment] 2017-07-03 12:43
fixed by scylladb/scylla-tools-java@d0782ccd243fff40c6d8c4a41036fc591f5c8abc

will be part of 1.7.2

**Closed by slivne** 2017-07-03 12:43 UTC
Labels: bug
