### ISSUE TITLE
system.clients is missing information with regards to connected clients

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla#6946] opened 2020-07-28 15:58 UTC
Scylla 4.0.X

```
cat /etc/scylla/scylla.yaml  | grep ^auth
authenticator: PasswordAuthenticator
authorizer: CassandraAuthorizer
```

```
[root@e40a07114766 /]# cqlsh -u cassandra -p cassandra
Connected to  at 172.17.0.3:9042.
[cqlsh 5.0.1 | Cassandra 3.0.8 | CQL spec 3.3.1 | Native protocol v4]
Use HELP for help.
cassandra@cqlsh> select * from system.clients ;

 address    | port  | client_type | connection_stage | driver_name | driver_version | hostname | protocol_version | shard_id | ssl_cipher_suite | ssl_enabled | ssl_protocol | username
------------+-------+-------------+------------------+-------------+----------------+----------+------------------+----------+------------------+-------------+--------------+-----------
 172.17.0.3 | 60618 |         cql |             null |        null |           null |     null |                0 |        0 |             null |        null |         null | anonymous
 172.17.0.3 | 60620 |         cql |             null |        null |           null |     null |                0 |        1 |             null |        null |         null | anonymous
```

- too many fields are null all of them should have values.
- username is incorrect its anonymous it should be cassandra 
- protocol version is incorrect its not version 0

**Comment by tzach** [comment] 2021-01-19 13:49
@amnonh we can include this info in the connect table in the monitoring dashboard

**Comment by haaawk** [comment] 2021-02-03 17:34
Can we close this already @jul-stas ?

**Comment by jul-stas** [comment] 2021-02-03 20:46
The encryption info is missing and the last time I talked to @elcallio (> year ago) I learned that it's not trivial to get this info. We can give it a try, but I'm not proficient with crypto unless I'll have to be.

**Comment by slivne** [comment] 2021-03-29 06:26
Aside of encryption and hostname all should be populated if this is not the case open a bug. 

pushing these based on requests

**Comment by jul-stas** [comment] 2021-08-17 13:04
I'm closing this in favor of this: #9216

**Closed by jul-stas** 2021-08-17 13:04 UTC
Labels: bug, monitoring-tracing

**Comment by avikivity** [comment] 2021-08-17 15:10
Usually it's better to close the new bugs, to preserve the historical record.

**Comment by avikivity** [comment] 2021-08-17 15:11
And it's not possible to backport issues that have no commits attached.

**Comment by jul-stas** [comment] 2021-08-17 15:35
I edited #7349 by adding "Fixes #6946", but apparently it didn't work (too late?)
What can I do instead?

**Comment by avikivity** [comment] 2021-08-17 15:49
Ah, then add "Fixed by <commit_hash> here, and add the backport candidate label (mimicking what the robots would do if you added the Fixes # thing in time).

**Comment by jul-stas** [comment] 2021-08-17 16:05
Fixed by fb24bccf046d319e6f27ed6a6dc0f9079d19d741
Note: needs backporting to 2020 and 2021

**Comment by avikivity** [comment] 2022-07-07 17:14
Not a bug, not backporting.
