### ISSUE TITLE
Stalls coming from flush_pending_io() on a slow disk setup

### ISSUE THREAD

**Issue by vladzcloudius** [scylladb/scylla#3941] opened 2018-11-27 02:06 UTC
*Installation details*
HEAD: 51afb1d8bdbe740465c7b9686e69129a8dc3a6c7 (tested with ScyllaDB 3.0-rc1 (ami-00955c887a32a4201))
Cluster size: 1

*Hardware details (for performance issues)*
Platform: AWS
Hardware: i3.2xlarge
Disks: EBS

*Description*
1) Create an instance.
2) Change the data and commitlog directories to reside on an EBS drive.
3) Set the io_properties.yaml to:
```
disks:
- mountpoint: /var/lib/scylla1
  read_bandwidth: 122000000
  read_iops: 3480
  write_bandwidth: 63000000
  write_iops: 1976
```
4) Runc-s with a default schema and 4K row size (from external machine/instance)
```
cassandra-stress write n=120000000 no-warmup  -node <IP> -rate threads=1000 throttle=3000/s -mode native cql3 connectionsPerHost=48 -schema keyspace="ks1" "replication(strategy=NetworkTopologyStrategy, us-east=3)" -col "size=FIXED(4000)" -pop seq=1..120000000
```
for a short time.
5) Set the compression parameters of the KS:
```
cqlsh> ALTER TABLE ks1.standard1 with compression = {'sstable_compression': 'DeflateCompressor', 'chunk_length_kb' : '64' };
```
6) Run the c-s again.
7) While c-s is running run `nodetool compaction`.

In the syslog you see a lot of these:

```
Nov 27 00:30:11 ip-172-16-12-101.ec2.internal scylla[15555]: Backtrace:
Nov 27 00:30:11 ip-172-16-12-101.ec2.internal scylla[15555]: 0x00000000006a6d02
Nov 27 00:30:11 ip-172-16-12-101.ec2.internal scylla[15555]: 0x00000000005be42c
Nov 27 00:30:11 ip-172-16-12-101.ec2.internal scylla[15555]: 0x00000000005be8e6
Nov 27 00:30:11 ip-172-16-12-101.ec2.internal scylla[15555]: /lib64/libpthread.so.0+0x000000000000f6cf
Nov 27 00:30:11 ip-172-16-12-101.ec2.internal scylla[15555]: 0x000000000059bf9f
Nov 27 00:30:11 ip-172-16-12-101.ec2.internal scylla[15555]: /lib64/libpthread.so.0+0x000000000000f6cf
Nov 27 00:30:11 ip-172-16-12-101.ec2.internal scylla[15555]: /lib64/libc.so.6+0x00000000000f8ec8
Nov 27 00:30:11 ip-172-16-12-101.ec2.internal scylla[15555]: 0x00000000007b94f8
Nov 27 00:30:11 ip-172-16-12-101.ec2.internal scylla[15555]: 0x000000000063982b
Nov 27 00:30:11 ip-172-16-12-101.ec2.internal scylla[15555]: 0x000000000059b014
Nov 27 00:30:11 ip-172-16-12-101.ec2.internal scylla[15555]: 0x000000000066df66
Nov 27 00:30:11 ip-172-16-12-101.ec2.internal scylla[15555]: 0x00000000006727aa
Nov 27 00:30:11 ip-172-16-12-101.ec2.internal scylla[15555]: 0x000000000075561d

```

This decodes into 
```
?? at /usr/src/debug/scylla-3.0.rc1/seastar/core/reactor.cc:1369
seastar::internal::io_submit(unsigned long, long, iocb**) at /usr/src/debug/scylla-3.0.rc1/seastar/core/linux-aio.cc:61
seastar::reactor::flush_pending_aio() at /usr/src/debug/scylla-3.0.rc1/seastar/core/reactor.cc:1106
seastar::reactor::poll_once() at /usr/src/debug/scylla-3.0.rc1/seastar/core/reactor.cc:3363
 (inlined by) operator() at /usr/src/debug/scylla-3.0.rc1/seastar/core/reactor.cc:3258
 (inlined by) _M_invoke at /opt/scylladb/include/c++/7/bits/std_function.h:302
std::function<bool ()>::operator()() const at /opt/scylladb/include/c++/7/bits/std_function.h:706
 (inlined by) seastar::reactor::run() at /usr/src/debug/scylla-3.0.rc1/seastar/core/reactor.cc:3283
operator() at /usr/src/debug/scylla-3.0.rc1/seastar/core/reactor.cc:4333
std::function<void ()>::operator()() const at /opt/scylladb/include/c++/7/bits/std_function.h:706
 (inlined by) seastar::posix_thread::start_routine(void*) at /usr/src/debug/scylla-3.0.rc1/seastar/core/posix.cc:52
?? ??:0
```

In the reactor.cc at the line 1369 is the last line in the `~posix_file_impl()`.

This may be related to https://github.com/scylladb/seastar/issues/538

**Comment by gibsn** [comment] 2018-11-27 18:00
Version: 3.0.rc1

io_properties.yaml:
```
disks:
  - mountpoint: /storage
    read_iops: 4178
    read_bandwidth: 1062918272
    write_iops: 1587
    write_bandwidth: 435770624
  - mountpoint: /clogs
    read_iops: 137396
    read_bandwidth: 536862368
    write_iops: 59180
    write_bandwidth: 439493568
```

Stalls occurred during compaction on one node, which led to growth of background queues on other nodes, causing foreground queues being throttled and latencies turning up.

```
2018-11-23T05:50:26.383810+03:00 beccasc1 scylla: Reactor stalled for 3230 ms on shard 27.
2018-11-23T05:50:26.384447+03:00 beccasc1 scylla: Backtrace:
2018-11-23T05:50:26.385204+03:00 beccasc1 scylla: 0x00000000006a6d02
2018-11-23T05:50:26.385598+03:00 beccasc1 scylla: 0x00000000005be42c
2018-11-23T05:50:26.385976+03:00 beccasc1 scylla: 0x00000000005be8e6
2018-11-23T05:50:26.386380+03:00 beccasc1 scylla: /lib64/libpthread.so.0+0x000000000000f6cf
2018-11-23T05:50:26.386775+03:00 beccasc1 scylla: 0x000000000059bf9f
2018-11-23T05:50:26.387155+03:00 beccasc1 scylla: /lib64/libpthread.so.0+0x000000000000f6cf
2018-11-23T05:50:26.387553+03:00 beccasc1 scylla: /lib64/libc.so.6+0x00000000000f8ec8
2018-11-23T05:50:26.387914+03:00 beccasc1 scylla: 0x00000000007b94f8
2018-11-23T05:50:26.388331+03:00 beccasc1 scylla: 0x000000000063982b
2018-11-23T05:50:26.388733+03:00 beccasc1 scylla: 0x000000000059b014
2018-11-23T05:50:26.389133+03:00 beccasc1 scylla: 0x000000000066df66
2018-11-23T05:50:26.389443+03:00 beccasc1 scylla: 0x00000000006727aa
2018-11-23T05:50:26.389879+03:00 beccasc1 scylla: 0x000000000075561d
2018-11-23T05:50:26.390328+03:00 beccasc1 scylla: /lib64/libpthread.so.0+0x0000000000007e24
2018-11-23T05:50:26.390807+03:00 beccasc1 scylla: /lib64/libc.so.6+0x00000000000febac
```

<img src="https://user-images.githubusercontent.com/11294101/49101018-401d4680-f286-11e8-918f-15a06ec23e43.png" width="200">

<img src="https://user-images.githubusercontent.com/11294101/49101028-46132780-f286-11e8-965a-f4a5f3e8509c.png" width="200">

**Comment by vladzcloudius** [comment] 2018-11-27 21:38
I tried to reproduce this today and was only able to do that with `DeflateCompressor, 64kb` and `nodetool compaction` during the test.
Updating the opening message.

**Comment by gibsn** [comment] 2018-11-28 10:55
@vladzcloudius 
CPU: 2x Intel Xeon E5-2620 v4
RAM: 8x16Gb
HDD: 10x4TB RAID10
SSD: 2x960GB RAID1 
NET: 1x10Gb/s

We have `LZ4Compressor, 64kb`

In our case these stalls happened twice:
1) during `nodetool compact` on one node
2) during compactions at night on the same node we had run `nodetool compact` before (screenshots provided above)

**Comment by vladzcloudius** [comment] 2018-11-30 21:36
I was able to reproduce these stalls - all it takes is using a bigger instance (i3.8xlarge) in order to increase the level of parallelism.
Stalls are coming from `io_submit()` call itself (I see stalls longer than 500ms) just as @glommer suspected.

**Comment by juliayakovlev** [comment] 2018-12-02 08:51
I received same during MV&SI longevity test. 
The stalls are also longer than 500 ms.
It happened during populating of keyspace in time Scylla server starting.
Test runs on AWS, i3.4xlarge instance
Scylla version 3.0.rc1-0.20181125.6e7e7f382

**Comment by avikivity** [comment] 2018-12-02 09:47
What's the kernel version for those stalls?

I had a kernel-side tracer for stalls, I need to dust it off and make it easier to use.

Probably, this is a duplicate of #3167, but will need kernel-side trace to confirm.

**Comment by avikivity** [comment] 2018-12-02 10:30
Well, can't complain about the kernel being too old.

**Comment by juliayakovlev** [comment] 2018-12-02 11:44
[stalls.txt](https://github.com/scylladb/scylla/files/2636879/stalls.txt)
Decoded
```
void seastar::backtrace<seastar::backtrace_buffer::append_backtrace()::{lambda(seastar::frame)#1}>(seastar::backtrace_buffer::append_backtrace()::{lambda(seastar::frame)#1}&&) at /usr/src/debug/scylla-3.0.rc1/seastar/util/backtrace.hh:56
seastar::backtrace_buffer::append_backtrace() at /usr/src/debug/scylla-3.0.rc1/seastar/core/reactor.cc:410
 (inlined by) print_with_backtrace at /usr/src/debug/scylla-3.0.rc1/seastar/core/reactor.cc:431
seastar::reactor::block_notifier(int) at /usr/src/debug/scylla-3.0.rc1/seastar/core/reactor.cc:749
?? ??:0
seastar::posix_file_impl::~posix_file_impl() at /usr/src/debug/scylla-3.0.rc1/seastar/core/reactor.cc:1369
?? ??:0
?? ??:0
seastar::internal::io_submit(unsigned long, long, iocb**) at /usr/src/debug/scylla-3.0.rc1/seastar/core/linux-aio.cc:61
seastar::reactor::flush_pending_aio() at /usr/src/debug/scylla-3.0.rc1/seastar/core/reactor.cc:1106
seastar::reactor::poll_once() at /usr/src/debug/scylla-3.0.rc1/seastar/core/reactor.cc:3363
 (inlined by) operator() at /usr/src/debug/scylla-3.0.rc1/seastar/core/reactor.cc:3258
 (inlined by) _M_invoke at /opt/scylladb/include/c++/7/bits/std_function.h:302
std::function<bool ()>::operator()() const at /opt/scylladb/include/c++/7/bits/std_function.h:706
 (inlined by) seastar::reactor::run() at /usr/src/debug/scylla-3.0.rc1/seastar/core/reactor.cc:3283
seastar::smp::configure(boost::program_options::variables_map)::{lambda()#3}::operator()() const at /usr/src/debug/scylla-3.0.rc1/seastar/core/reactor.cc:4333
std::function<void ()>::operator()() const at /opt/scylladb/include/c++/7/bits/std_function.h:706
 (inlined by) seastar::posix_thread::start_routine(void*) at /usr/src/debug/scylla-3.0.rc1/seastar/core/posix.cc:52
?? ??:0

?? ??:0
```

**Comment by slivne** [comment] 2020-06-01 06:54
@bhalevy is this familiar to you - I don't recall we hit this recently and if we haven't I want to close the issue

**Comment by avikivity** [comment] 2020-06-01 12:11
I haven't seen it in a long while.

**Closed** 2020-06-01 12:13 UTC
Labels: performance
