### ISSUE TITLE
cleanup executed 5 hours and failed after decommission and re-adding a new node

### ISSUE THREAD

**Issue by amoskong** [scylladb/scylla#8016] opened 2021-02-02 11:25 UTC
*Installation details*
Scylla version (or git commit hash): `4.4.rc1-0.20210131.fd868722d`
Cluster size: 4 nodes (i3en.3xlarge)
OS (RHEL/CentOS/Ubuntu/AWS AMI):  ami-06dcc54e2d1c77000 (eu-north-1)

Test: `longevity-large-collections-12h`
Job link: https://jenkins.scylladb.com/job/scylla-master/job/longevity/job/longevity-large-collections-12h/4/
Test config file(s): 
- https://github.com/scylladb/scylla-cluster-tests/blob/3200d2643b71b64fd240d4724fd1f8911d3d2e21/test-cases/longevity/longevity-large-collections-12h.yaml
- https://github.com/scylladb/scylla-cluster-tests/blob/3200d2643b71b64fd240d4724fd1f8911d3d2e21/data_dir/large_collections.yaml

**Issue description**

====================================

The `longevity-large-collections-12h` executed 13 hours. Only successfully executed one nemesis (grow_shrink_cluster).
Another decommission nemesis didn't finished. The target node was successfully removed, and new node was added successfully.  In the end of this nemesis, all test keyspaces will be cleanup one by one.

#### Problem

Cleanup all test keyspaces failed after decommission.
- /usr/bin/nodetool cleanup large_collection_test
  - WARN 16:58:14,990 Only 12.973GiB free across all data volumes. Consider adding more capacity to your cluster or removing obsolete snapshots
  - WARN 16:58:15,073 Unable to read cassandra-rackdc.properties

The cleanup command `failed` after executed `5 hours`
2021-02-01 22:01:29,310 Error executing command: "/usr/bin/nodetool  cleanup large_collection_test"; Exit status: -1

#### Nemesis

2021-02-01 09:57:35,994 >>Started random_disrupt_method grow_shrink_cluster
2021-02-01 11:21:28,444 <<Finished random_disrupt_method grow_shrink_cluster
2021-02-01 11:37:04,162 >>Started random_disrupt_method toggle_table_ics
^^^ Unsupported 

2021-02-01 11:37:41,946 >>Started random_disrupt_method nodetool_decommission
* target: longevity-large-collections-12h-mas-db-node-c6a4e04e-2 [13.49.80.212 | 10.0.2.230]
* < t:2021-02-01 14:11:52,685 f:cluster.py      l:2577 c:sdcm.cluster_aws     p:DEBUG > Node longevity-large-collections-12h-mas-db-node-c6a4e04e-2 [13.49.80.212 | 10.0.2.230] (seed: False): Command '/usr/bin/nodetool  decommission ' duration -> 9250.738369175997 s
*  t:2021-02-01 14:11:59,722 f:cluster.py      l:1103 c:sdcm.cluster         p:INFO  > Node longevity-large-collections-12h-mas-db-node-c6a4e04e-2 [13.49.80.212 | 10.0.2.230] (seed: False) destroyed
* 2021-02-01 14:12:01,042 INFO  > sdcm.nemesis.ChaosMonkey: Adding new node to cluster...
* < t:2021-02-01 14:12:23,669 f:cluster.py      l:471  c:sdcm.cluster_aws     p:DEBUG > Node longevity-large-collections-12h-mas-db-node-c6a4e04e-6 [13.49.245.72 | 10.0.3.4]
* 2021-02-01 16:58:11,609 INFO  > 2021-02-01 16:58:11.608: Severity.NORMAL): message=FinishEvent - New Node is up and normal
* 2021-02-01 21:56:22,575 f:tester.py       l:2029 c:LongevityTest        p:INFO  > TearDown is starting...

```
    2021-02-01 16:58:12,624DEBUG > Running command "/usr/bin/nodetool  cleanup large_collection_test"...
    2021-02-01 22:01:29.916: (DisruptionEvent Severity.ERROR): type=Decommission subtype=end 
    target_node=Node longevity-large-collections-12h-mas-db-node-c6a4e04e-2
     [13.49.80.212 | 10.0.2.230] (seed: False) duration=37427 error=Encountered a bad command exit code!
    Command: '/usr/bin/nodetool  cleanup large_collection_test'
    | Exit code: -1
    | Stdout:
    | Using /etc/scylla/scylla.yaml as the config file
    |
    | Stderr:
    | WARN  16:58:14,990 Only 12.973GiB free across all data volumes. Consider adding more capacity to your cluster or removing obsolete snapshots
    | WARN  16:58:15,073 Unable to read cassandra-rackdc.properties
```

====================================

Restore Monitor Stack command: `$ hydra investigate show-monitor c6a4e04e-20d4-40e3-a820-843037316734`
Show all stored logs command: `$ hydra investigate show-logs c6a4e04e-20d4-40e3-a820-843037316734`

Test id: `c6a4e04e-20d4-40e3-a820-843037316734`

Logs:
db-cluster - [https://cloudius-jenkins-test.s3.amazonaws.com/c6a4e04e-20d4-40e3-a820-843037316734/20210201_224144/db-cluster-c6a4e04e.zip](https://cloudius-jenkins-test.s3.amazonaws.com/c6a4e04e-20d4-40e3-a820-843037316734/20210201_224144/db-cluster-c6a4e04e.zip)
loader-set - [https://cloudius-jenkins-test.s3.amazonaws.com/c6a4e04e-20d4-40e3-a820-843037316734/20210201_224144/loader-set-c6a4e04e.zip](https://cloudius-jenkins-test.s3.amazonaws.com/c6a4e04e-20d4-40e3-a820-843037316734/20210201_224144/loader-set-c6a4e04e.zip)
sct-runner - [https://cloudius-jenkins-test.s3.amazonaws.com/c6a4e04e-20d4-40e3-a820-843037316734/20210201_224144/sct-runner-c6a4e04e.zip](https://cloudius-jenkins-test.s3.amazonaws.com/c6a4e04e-20d4-40e3-a820-843037316734/20210201_224144/sct-runner-c6a4e04e.zip)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/longevity/job/longevity-large-collections-12h/4/)

**Comment by slivne** [comment] 2021-02-02 12:07
collecting more info - once we have it - @bhalevy / @raphaelsc can have a look

**Comment by raphaelsc** [comment] 2021-02-02 15:49
cleanup runs against node1, and node1 log shows no failure on cleanup.

it may be the node1 ran out of space, but that should have been reported in the log. i'll try looking at the monitoring

**Comment by amoskong** [comment] 2021-02-02 15:58
> cleanup runs against node1, and node1 log shows no failure on cleanup.
> 
> it may be the node1 ran out of space, but that should have been reported in the log. i'll try looking at the monitoring

There is no ENOSPC error in logs of all db nodes.

**Comment by raphaelsc** [comment] 2021-02-02 16:32
last log in node1 was:
`2021-02-01T22:01:03+00:00  longevity-large-collections-12h-mas-db-node-c6a4e04e-1 !INFO    | scylla: [shard 8] compaction - [Cleanup large_collection_test.table_with_large_collection fa1c3c00-64d8-11eb-afba-000000000007] Cleaning [/var/lib/scylla/data/large_collection_test/table_with_large_collection-b75c53b0647311eb8d04000000000000/md-3608-big-Data.db:level=0, ]`

~25 min later node1 was turned off.

if the problem wasn't on the scylla side, something happened in the client side. did nodetool output provide more info about why it failed?

**Comment by amoskong** [comment] 2021-02-05 06:13
> last log in node1 was:
> `2021-02-01T22:01:03+00:00 longevity-large-collections-12h-mas-db-node-c6a4e04e-1 !INFO | scylla: [shard 8] compaction - [Cleanup large_collection_test.table_with_large_collection fa1c3c00-64d8-11eb-afba-000000000007] Cleaning [/var/lib/scylla/data/large_collection_test/table_with_large_collection-b75c53b0647311eb8d04000000000000/md-3608-big-Data.db:level=0, ]`
> 
> ~25 min later node1 was turned off.
> 
> if the problem wasn't on the scylla side, something happened in the client side. did nodetool output provide more info about why it failed?

Nothing more was outputted.

**Comment by slivne** [comment] 2021-02-07 10:55
@amoskong / @raphaelsc how come cleanup took 5 hours and did not end - how much data do we have on the nodes that 5 hours are not enough - thats  strange (tzach asked and I did not have an answer).

Lets look at the monitoring - something is off here

**Comment by roydahan** [comment] 2021-02-10 17:51
Monitor can be restored using hydra.

**Comment by slivne** [comment] 2021-02-14 11:24
@raphaelsc / @bhalevy ping

**Comment by raphaelsc** [comment] 2021-02-14 12:21
On Sun, Feb 14, 2021 at 8:24 AM Shlomi Livne <notifications@github.com>
wrote:

> @raphaelsc <https://github.com/raphaelsc> / @bhalevy
> <https://github.com/bhalevy> ping
>
will investigate it tomorrow.

**Comment by slivne** [comment] 2021-02-23 12:11
@raphaelsc / @bhalevy ping

**Comment by raphaelsc** [comment] 2021-02-24 15:55
digging node1 logs, all cleanup compaction jobs prior to failure are all successful. no cleanup failure. no ENOSPC.

i can see the the node was powered off at the moment cleanup was running:
```
2021-02-01T22:01:29+00:00  longevity-large-collections-12h-mas-db-node-c6a4e04e-1 !INFO    | systemd-logind: Power key pressed.
2021-02-01T22:01:29+00:00  longevity-large-collections-12h-mas-db-node-c6a4e04e-1 !INFO    | systemd-logind: Powering Off...
2021-02-01T22:01:29+00:00  longevity-large-collections-12h-mas-db-node-c6a4e04e-1 !NOTICE  | systemd-logind: System is powering down.
```

so it seems to me it's a testing issue, perhaps we're not waiting for cleanup before removing node1 (looks like node1 is killed aggressively on purpose to simulate a lost node), so that's why cleanup will fail. so we either wait for cleanup to finish or ignore the cleanup failure given that the node1 is lost anyway. /CC @roydahan @amoskong

**Comment by raphaelsc** [comment] 2021-02-24 16:34
found terrible bug where sstables selected for a rewrite operation (cleanup, scrub, upgrade) can also be selected for regular compaction, meaning that same data will be compacted twice, hurting write amplification, space requirement, operation time, etc. regression probably introduced by 463d0ab37c

i think i know the exact code change introduced this bug, i'll cook a fix and a unit test to make sure this will not happen ever again. we need to backport the fix for all affected versions (from 4.1 on). /CC @slivne @bhalevy

**Comment by raphaelsc** [comment] 2021-02-24 16:43
figured out from $ grep -r 'Unable to delete' | wc -l
148

and double checking that the individual generations were picked twice for compaction operations.

deletion failed on those sstables because they were compacted by both cleanup and regular, meaning that whichever finishes last would bump into the deletion failure

**Comment by bhalevy** [comment] 2021-02-28 12:23
> i can see that the node1 was powered off at the moment cleanup compaction was running and the cleanup command failed:

@roydahan asks when did the that happen?
Did it happen after the cleanup nemesis timed out?
Need to verify the timeline in the logs.

**Comment by amoskong** [comment] 2021-03-01 03:45
> > i can see that the node1 was powered off at the moment cleanup compaction was running and the cleanup command failed:
> 
> @roydahan asks when did the that happen?
> Did it happen after the cleanup nemesis timed out?
> Need to verify the timeline in the logs.

It seems caused by spot termination, not a real scylla issue. I'm fine to close this issue.

### instance_provision: spot_low_price
- spot is used, so the instance might be terminated during the test.
- sct failed (timeout) to check spot termination notification. `But it _seems_ the instance was terminated for spot.`

```
### Node1  power off

2021-02-01T22:01:29+00:00  longevity-large-collections-12h-mas-db-node-c6a4e04e-1 !INFO    | systemd-logind: Power key pressed.
2021-02-01T22:01:29+00:00  longevity-large-collections-12h-mas-db-node-c6a4e04e-1 !INFO    | systemd-logind: Powering Off...
2021-02-01T22:01:29+00:00  longevity-large-collections-12h-mas-db-node-c6a4e04e-1 !NOTICE  | systemd-logind: System is powering down.

### Timeout to get spot termination notification
< t:2021-02-01 22:01:29,884 f:cluster_aws.py  l:551  c:sdcm.cluster_aws     p:WARNING
> Node longevity-large-collections-12h-mas-loader-node-c6a4e04e-1 [13.49.75.35 | 10.0.0.73]
 (seed: False): Error during getting spot termination notification timed out

### Cleanup failed _immediately_
2021-02-01 22:01:29.916: (DisruptionEvent Severity.ERROR): type=Decommission subtype=end 
    node=Node longevity-large-collections-12h-mas-db-node-c6a4e04e-2
     [13.49.80.212 | 10.0.2.230] (seed: False) duration=37427 error=Encountered a bad command exit code!
    Command: '/usr/bin/nodetool  cleanup large_collection_test'
    | Exit code: -1
```

We can add power off event in SCT.

**Comment by bhalevy** [comment] 2021-03-01 09:11
> We can add power off event in SCT.

I'm not sure exactly was that entails, but the bottom line is we should detect spot terminations and possibly terminate the current nemesis and/or tolerate its consequent failure.  It's not only cleanup that may fail, it could be other node operations as well, like (safe) removenode.

**Comment by amoskong** [comment] 2021-03-01 09:56
> > We can add power off event in SCT.
> 
> I'm not sure exactly was that entails, but the bottom line is we should detect spot terminations and possibly terminate the current nemesis and/or tolerate its consequent failure. It's not only cleanup that may fail, it could be other node operations as well, like (safe) removenode.

SCT has a background thread to check spot termination notification circularly for all instances, it won't be effected by the nemesis operations. The default interval is 5 seconds. and the checking is executed inside the instance by curl.

If the instance powered off before the checking, then the checking will fail for timeout (network is already down).

@bentsi can we run a process inside the instance with shorter interval to check the spot notification?
Or can we treat the `Power key pressed.` log as SpotTermination event?

----


In the failed nodetool_decommission nemesis, the target node is `longevity-large-collections-12h-mas-db-node-c6a4e04e-2 [13.49.80.212 | 10.0.2.230]`,  the power off node is `db-node-c6a4e04e-1`

**Comment by roydahan** [comment] 2021-03-01 11:12
Leave aside the spot termination and the cleanup eventually failed.

The issue should concentrate on the cleanup taking 5 hours and if it's
valid or not.

**Comment by slivne** [comment] 2021-03-01 11:16
We are fixing the cleanup issue - there is a patch on the ML related to
that

**Comment by slivne** [comment] 2021-03-01 12:11
@raphaelsc / @bhalevy - according to benny we still don;t understand why cleanup did not finish

**Comment by amoskong** [comment] 2021-03-01 13:06
> Leave aside the spot termination and the cleanup eventually failed. The issue should concentrate on the cleanup taking 5 hours and if it's valid or not.

`nodetool cleanup` command was executed on node1 by ssh, and the command returned (failed) WHEN the node powered off.

**Comment by raphaelsc** [comment] 2021-03-01 14:05
> @raphaelsc / @bhalevy - according to benny we still don;t understand why cleanup did not finish

https://github.com/scylladb/scylla/issues/8016#issuecomment-785203880

**Comment by raphaelsc** [comment] 2021-03-01 14:06
> > @raphaelsc / @bhalevy - according to benny we still don;t understand why cleanup did not finish
> 
> [#8016 (comment)](https://github.com/scylladb/scylla/issues/8016#issuecomment-785203880)

sorry, wrong link, follow this one instead: https://github.com/scylladb/scylla/issues/8016#issuecomment-785176594

**Comment by raphaelsc** [comment] 2021-03-01 14:08
> @raphaelsc / @bhalevy - according to benny we still don;t understand why cleanup did not finish

cleanup was still running, no issue, just a matter of time for it to complete. so the perf issue is potentially explained by https://github.com/scylladb/scylla/issues/8155 because that causes cleanup to slow down.

**Comment by bhalevy** [comment] 2021-03-01 16:55
> > @raphaelsc / @bhalevy - according to benny we still don;t understand why cleanup did not finish
> 
> cleanup was still running, no issue, just a matter of time for it to complete. so the perf issue is potentially explained by #8155 because that causes cleanup to slow down.

@raphaelsc why would #8155 cause cleanup to slow down?
Just the fact the regular compaction is running in parallel over the same sstables?

**Comment by bhalevy** [comment] 2021-03-02 12:33
I can understand some slowdown from regular and cleanup compaction both compacting the same sstables, so maybe that explain a factor of 2, but the question is whether that explains the 5 hours we see here?

**Comment by raphaelsc** [comment] 2021-03-02 15:40
> I can understand some slowdown from regular and cleanup compaction both compacting the same sstables, so maybe that explain a factor of 2, but the question is whether that explains the 5 hours we see here?

cleanup and regular use the same scheduling group. when they compact same sstable, table will end up with two sstables storing redundant data. so all sstables that end up being compacted in parallel by both, will be additional backlog which causes both regular and cleanup to slowdown as they compete with one another for the same bandwidth. i do think we potentially need to move cleanup to a different group in the future, which will be controlled by a space controller.

**Comment by raphaelsc** [comment] 2021-03-18 18:15
https://github.com/scylladb/scylla/commit/71712448444989f0ecbd017e335338e2f5dc478c potentially helps this. with 71712448444989f0ecbd017e335338e2f5dc478c and #8155 fixed, I think this issue is likely fixed. @slivne Please assign somebody to redo this test on latest master.

**Comment by slivne** [comment] 2021-06-23 11:13
@roydahan / @shoshan this should be fixed in 4.5.rc3

**Comment by roydahan** [comment] 2021-08-24 12:23
@yarongilor please comment here with your findings on testing with 4.5.rc6.

**Comment by yarongilor** [comment] 2021-08-24 14:45
The error is not reproduced in a reproduction test, running decommission nemesis.
The decommission nemesis only ran once in this ~ 12 hour long run.
on the cleanup step - 3 nodes completed pretty fast and the 4th node ran a cleanup for more than 5 hours until stress ended and then test ended.
yet, no nodetool error reported.
cleanup logs are:
```
< t:2021-08-23 13:06:49,830 f:file_logger.py  l:80   c:sdcm.sct_events.file_logger p:INFO  > 2021-08-23 13:06:49.828: (InfoEvent Severity.NORMAL): message=FinishEvent - New Node is up and normal
< t:2021-08-23 13:06:50,490 f:file_logger.py  l:80   c:sdcm.sct_events.file_logger p:INFO  > 2021-08-23 13:06:50.489: (NodetoolEvent Severity.NORMAL): type=cleanup subtype=start node=longevity-large-collections-12h-4-5-db-node-6944fc29-1
< t:2021-08-23 14:12:41,141 f:file_logger.py  l:80   c:sdcm.sct_events.file_logger p:INFO  > 2021-08-23 14:12:41.140: (NodetoolEvent Severity.NORMAL): type=cleanup subtype=end node=longevity-large-collections-12h-4-5-db-node-6944fc29-1 duration=3950.6498198679997s
< t:2021-08-23 14:12:41,143 f:file_logger.py  l:80   c:sdcm.sct_events.file_logger p:INFO  > 2021-08-23 14:12:41.140: (NodetoolEvent Severity.NORMAL): type=cleanup subtype=start node=longevity-large-collections-12h-4-5-db-node-6944fc29-3
< t:2021-08-23 15:18:30,542 f:file_logger.py  l:80   c:sdcm.sct_events.file_logger p:INFO  > 2021-08-23 15:18:30.537: (NodetoolEvent Severity.NORMAL): type=cleanup subtype=end node=longevity-large-collections-12h-4-5-db-node-6944fc29-3 duration=3949.3943501150006s
< t:2021-08-23 15:18:30,545 f:file_logger.py  l:80   c:sdcm.sct_events.file_logger p:INFO  > 2021-08-23 15:18:30.540: (NodetoolEvent Severity.NORMAL): type=cleanup subtype=start node=longevity-large-collections-12h-4-5-db-node-6944fc29-4
< t:2021-08-23 18:47:09,251 f:file_logger.py  l:80   c:sdcm.sct_events.file_logger p:INFO  > 2021-08-23 18:47:09.249: (NodetoolEvent Severity.NORMAL): type=cleanup subtype=end node=longevity-large-collections-12h-4-5-db-node-6944fc29-4 duration=12518.707223786s
< t:2021-08-23 18:47:09,253 f:file_logger.py  l:80   c:sdcm.sct_events.file_logger p:INFO  > 2021-08-23 18:47:09.250: (NodetoolEvent Severity.NORMAL): type=cleanup subtype=start node=longevity-large-collections-12h-4-5-db-node-6944fc29-5
< t:2021-08-24 00:48:18,243 f:file_logger.py  l:80   c:sdcm.sct_events.file_logger p:INFO  > 2021-08-24 00:48:18.236: (CassandraStressEvent Severity.NORMAL): type=finish node=Node longevity-large-collections-12h-4-5-loader-node-6944fc29-1 [52.213.84.91 | 10.0.0.90] (seed: False)
< t:2021-08-24 00:48:18,402 f:file_logger.py  l:80   c:sdcm.sct_events.file_logger p:INFO  > 2021-08-24 00:48:18.399: (InfoEvent Severity.NORMAL): message=TEST_END
```

*Installation details*
Kernel version: `5.4.0-1035-aws`
Scylla version (or git commit hash): `4.5.rc6-0.20210817.88314fedf`
Cluster size: 4 nodes (i3en.3xlarge)
Scylla running with shards number (live nodes):
   longevity-large-collections-12h-4-5-db-node-6944fc29-1 (18.202.225.108 | 10.0.1.82): 12 shards
   longevity-large-collections-12h-4-5-db-node-6944fc29-3 (34.243.26.19 | 10.0.0.208): 12 shards
   longevity-large-collections-12h-4-5-db-node-6944fc29-4 (34.248.173.132 | 10.0.0.79): 12 shards
   longevity-large-collections-12h-4-5-db-node-6944fc29-5 (63.32.112.28 | 10.0.2.74): 12 shards
Scylla running with shards number (terminated nodes):
   longevity-large-collections-12h-4-5-db-node-6944fc29-2 (34.252.150.20 | 10.0.0.172): 12 shards
OS (RHEL/CentOS/Ubuntu/AWS AMI): `ami-011f02dc29a254fd4` (aws: eu-west-1)


Test: `longevity-large-collections-12h-test_8016`
Test name: `longevity_test.LongevityTest.test_custom_time`
Test config file(s):
- [longevity-large-collections-12h.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/55f29e60093f114d4270c5fc6a7389005ce83551/test-cases/longevity/longevity-large-collections-12h.yaml)


**Issue description**

====================================

PUT ISSUE DESCRIPTION HERE


====================================






Restore Monitor Stack command: `$ hydra investigate show-monitor 6944fc29-a76a-4a7a-9734-eb5e7b65078f`
Show all stored logs command: `$ hydra investigate show-logs 6944fc29-a76a-4a7a-9734-eb5e7b65078f`

Test id: `6944fc29-a76a-4a7a-9734-eb5e7b65078f`


Logs:
grafana - [https://cloudius-jenkins-test.s3.amazonaws.com/6944fc29-a76a-4a7a-9734-eb5e7b65078f/20210824_011835/grafana-screenshot-longevity-large-collections-12h-test_8016-scylla-per-server-metrics-nemesis-20210824_012312-longevity-large-collections-12h-4-5-monitor-node-6944fc29-1.png](https://cloudius-jenkins-test.s3.amazonaws.com/6944fc29-a76a-4a7a-9734-eb5e7b65078f/20210824_011835/grafana-screenshot-longevity-large-collections-12h-test_8016-scylla-per-server-metrics-nemesis-20210824_012312-longevity-large-collections-12h-4-5-monitor-node-6944fc29-1.png)
db-cluster - [https://cloudius-jenkins-test.s3.amazonaws.com/6944fc29-a76a-4a7a-9734-eb5e7b65078f/20210824_012756/db-cluster-6944fc29.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/6944fc29-a76a-4a7a-9734-eb5e7b65078f/20210824_012756/db-cluster-6944fc29.tar.gz)
loader-set - [https://cloudius-jenkins-test.s3.amazonaws.com/6944fc29-a76a-4a7a-9734-eb5e7b65078f/20210824_012756/loader-set-6944fc29.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/6944fc29-a76a-4a7a-9734-eb5e7b65078f/20210824_012756/loader-set-6944fc29.tar.gz)
monitor-set - [https://cloudius-jenkins-test.s3.amazonaws.com/6944fc29-a76a-4a7a-9734-eb5e7b65078f/20210824_012756/monitor-set-6944fc29.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/6944fc29-a76a-4a7a-9734-eb5e7b65078f/20210824_012756/monitor-set-6944fc29.tar.gz)
sct-runner - [https://cloudius-jenkins-test.s3.amazonaws.com/6944fc29-a76a-4a7a-9734-eb5e7b65078f/20210824_012756/sct-runner-6944fc29.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/6944fc29-a76a-4a7a-9734-eb5e7b65078f/20210824_012756/sct-runner-6944fc29.tar.gz)


[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-4.5/job/Reproducers/job/longevity-large-collections-12h-test_8016/2/)

**Comment by slivne** [comment] 2021-11-10 16:18
great closing

**Closed by slivne** 2021-11-10 16:18 UTC
Labels: high, compaction, fixed
