### ISSUE TITLE
panic with 200MB large partition test

### ISSUE THREAD

**Issue by asias** [scylladb/scylla#1653] opened 2016-09-07 06:25 UTC
ami: ami-6c21427b (scylla 1.3 release)
1 loader node: c4.8xlarge 
3 scylla db:  i2.2xlarge

Running the following c-s on c4.8xlarge loader

$ cassandra-stress user no-warmup duration=5m  cl=ONE profile=./$PROFILES ops\(insert=3,query1=1,query2=1,query3=1\) -rate threads=100 -node 172.30.0.109

[c-s-large-partition-mixed-200MB.yaml.zip](https://github.com/scylladb/scylla/files/458407/c-s-large-partition-mixed-200MB.yaml.zip)

I got core dumps. 

```
[centos@ip-172-30-0-110 ~]$ rpm -qa|grep scylla
scylla-boost-thread-1.58.0-11.el7.centos.x86_64
scylla-boost-date-time-1.58.0-11.el7.centos.x86_64
scylla-tools-1.3.0-20160824.9a9cc39.el7.centos.noarch
scylla-boost-system-1.58.0-11.el7.centos.x86_64
scylla-conf-1.3.0-20160824.ec3ace5.el7.centos.x86_64
scylla-boost-filesystem-1.58.0-11.el7.centos.x86_64
scylla-boost-program-options-1.58.0-11.el7.centos.x86_64
scylla-server-1.3.0-20160824.ec3ace5.el7.centos.x86_64
scylla-jmx-1.3.0-20160824.7d2646d.el7.centos.noarch
scylla-debuginfo-1.3.0-20160824.ec3ace5.el7.centos.x86_64
scylla-env-1.0-1.el7.centos.noarch
scylla-boost-test-1.58.0-11.el7.centos.x86_64
scylla-kernel-conf-1.3.0-20160824.ec3ace5.el7.centos.x86_64
```

```
[centos@ip-172-30-0-109 ~]$ coredumpctl info -1
           PID: 2363 (scylla)
           UID: 994 (scylla)
           GID: 1001 (scylla)
        Signal: 11 (SEGV)
     Timestamp: Wed 2016-09-07 06:11:58 UTC (9min ago)
  Command Line: /usr/bin/scylla --log-to-syslog 1 --log-to-stdout 0 --default-log-level info --collectd-address=127.0.0.1:25826 --collectd=1 --collectd-poll-period 3000 --network-stack posix --num-io-queues 7 --max-io-request
    Executable: /usr/bin/scylla
 Control Group: /system.slice/scylla-server.service
          Unit: scylla-server.service
         Slice: system.slice
       Boot ID: b759cb72c11948be9fdba3b8dbba5fcc
    Machine ID: 8ea3e6ea03b64d018847fcdf669935d4
      Hostname: ip-172-30-0-109
      Coredump: /var/lib/systemd/coredump/core.scylla.994.b759cb72c11948be9fdba3b8dbba5fcc.2363.1473228718000000
       Message: Process 2363 (scylla) of user 994 dumped core.

                Stack trace of thread 2363:
                #0  0x000000000086deb3 _ZNK13managed_bytes4sizeEv (scylla)
                #1  0x000000000093384e _ZN25atomic_cell_or_collectionC4ERKS_ (scylla)
                #2  0x000000000093635b _ZN19allocation_strategy9constructIN3row10cell_entryEJRKS2_EEEPT_DpOT0_ (scylla)
                #3  0x00000000008e1ec4 _ZN14clustering_rowC4ERK10rows_entry (scylla)
                #4  0x00000000008e303e _ZN25partition_snapshot_reader14do_fill_bufferEv (scylla)
                #5  0x00000000008e34d7 _ZN25partition_snapshot_readerC2E13lw_shared_ptrIK6schemaEN3dht13decorated_keyES0_I18partition_snapshotEN5query32clustering_key_filtering_contextERKSt6vectorI5rangeI21clustering_key_pref
                #6  0x00000000008e38f5 _ZSt11make_uniqueI25partition_snapshot_readerJR13lw_shared_ptrIK6schemaEN3dht13decorated_keyERS1_I18partition_snapshotERN5query32clustering_key_filtering_contextERKSt6vectorI5rangeI21clu
                #7  0x00000000009113c3 _ZN14memtable_entry4readE13lw_shared_ptrI8memtableERKS0_IK6schemaERKN5query32clustering_key_filtering_contextE (scylla)
                #8  0x000000000091201c operator() (scylla)
                #9  0x000000000081208c _ZNK13column_family11make_readerE13lw_shared_ptrIK6schemaERK5rangeIN3dht13ring_positionEERKN5query32clustering_key_filtering_contextERK17io_priority_class (scylla)
                #10 0x0000000000812537 operator() (scylla)
                #11 0x00000000008f1fb3 _ZNKSt8functionIF15mutation_reader13lw_shared_ptrIK6schemaERK5rangeIN3dht13ring_positionEEN5query32clustering_key_filtering_contextERK17io_priority_classEEclES4_SA_SC_SF_ (scylla)
                #12 0x00000000009470a0 _Z10data_query13lw_shared_ptrIK6schemaERK15mutation_sourceRK5rangeIN3dht13ring_positionEERKN5query15partition_sliceEjjNSt6chrono10time_pointI8gc_clockNSG_8durationIiSt5ratioILl1ELl1EEEEE
                #13 0x00000000007c17aa _ZZN13column_family5queryE13lw_shared_ptrIK6schemaERKN5query12read_commandENS4_14result_requestERKSt6vectorI5rangeIN3dht13ring_positionEESaISD_EEENKUlvE_clEv (scylla)
                #14 0x0000000000830d48 do_until_continued<column_family::query(schema_ptr, const query::read_command&, query::result_request, const std::vector<range<dht::ring_position>, std::allocator<range<dht::ring_positio
                #15 0x0000000000832729 _ZN8database5queryE13lw_shared_ptrIK6schemaERKN5query12read_commandENS4_14result_requestERKSt6vectorI5rangeIN3dht13ring_positionEESaISD_EE (scylla)
                #16 0x0000000000cdc5ae operator() (scylla)
                #17 0x0000000000ced853 process (scylla)
                #18 0x0000000000508580 operator() (scylla)
                #19 0x00000000005090f8 _ZN17smp_message_queue16process_incomingEv (scylla)
                #20 0x00000000004d2f45 _ZN7reactor9poll_onceEv (scylla)
                #21 0x00000000005046f4 _ZNKSt8functionIFbvEEclEv (scylla)
                #22 0x000000000057c205 _ZN12app_template14run_deprecatedEiPPcOSt8functionIFvvEE (scylla)
                #23 0x000000000047357a main (scylla)
                #24 0x00007f21bebccb15 __libc_start_main (libc.so.6)
                #25 0x00000000004d1d95 _start (scylla)

                Stack trace of thread 2365:
                #0  0x00007f21becf8f46 __memmove_ssse3_back (libc.so.6)
                #1  0x00000000010bc5be _ZNSt11__copy_moveILb0ELb1ESt26random_access_iterator_tagE8__copy_mIcEEPT_PKS3_S6_S4_ (scylla)
                #2  0x00000000010bc5f4 _ZN3ser10serializerI15frozen_mutationE5writeIN7seastar20simple_output_streamEEEvRT_RKS1_ (scylla)
                #3  0x00000000010bf0a3 _ZZN3rpc11send_helperIN3net10serializerENS1_14messaging_verbENS_12no_wait_typeEIRK15frozen_mutationSt6vectorIN3gms12inet_addressESaISA_EESA_jmNSt12experimental15fundamentals_v18optionalI
                #4  0x00000000010cfc26 _ZZN3rpc11send_helperIN3net10serializerENS1_14messaging_verbENS_12no_wait_typeEJRK15frozen_mutationSt6vectorIN3gms12inet

[centos@ip-172-30-0-110 ~]$ coredumpctl info -1
           PID: 3391 (scylla)
           UID: 994 (scylla)
           GID: 1001 (scylla)
        Signal: 11 (SEGV)
     Timestamp: Wed 2016-09-07 06:11:58 UTC (10min ago)
  Command Line: /usr/bin/scylla --log-to-syslog 1 --log-to-stdout 0 --default-log-level info --collectd-address=127.0.0.1:25826 --collectd=1 --collectd-poll-period 3000 --network-stack posix --num-io-queues 7 --max-io-request
    Executable: /usr/bin/scylla
 Control Group: /system.slice/scylla-server.service
          Unit: scylla-server.service
         Slice: system.slice
       Boot ID: 573acc47d0274b8684640ee86c32594a
    Machine ID: 8ea3e6ea03b64d018847fcdf669935d4
      Hostname: ip-172-30-0-110
      Coredump: /var/lib/systemd/coredump/core.scylla.994.573acc47d0274b8684640ee86c32594a.3391.1473228718000000
       Message: Process 3391 (scylla) of user 994 dumped core.

                Stack trace of thread 3391:
                #0  0x000000000086deb3 _ZNK13managed_bytes4sizeEv (scylla)
                #1  0x000000000093384e _ZN25atomic_cell_or_collectionC4ERKS_ (scylla)
                #2  0x000000000093635b _ZN19allocation_strategy9constructIN3row10cell_entryEJRKS2_EEEPT_DpOT0_ (scylla)
                #3  0x00000000008e1ec4 _ZN14clustering_rowC4ERK10rows_entry (scylla)
                #4  0x00000000008e303e _ZN25partition_snapshot_reader14do_fill_bufferEv (scylla)
                #5  0x00000000008e34d7 _ZN25partition_snapshot_readerC2E13lw_shared_ptrIK6schemaEN3dht13decorated_keyES0_I18partition_snapshotEN5query32clustering_key_filtering_contextERKSt6vectorI5rangeI21clustering_key_pref
                #6  0x00000000008e38f5 _ZSt11make_uniqueI25partition_snapshot_readerJR13lw_shared_ptrIK6schemaEN3dht13decorated_keyERS1_I18partition_snapshotERN5query32clustering_key_filtering_contextERKSt6vectorI5rangeI21clu
                #7  0x00000000009113c3 _ZN14memtable_entry4readE13lw_shared_ptrI8memtableERKS0_IK6schemaERKN5query32clustering_key_filtering_contextE (scylla)
                #8  0x000000000091201c operator() (scylla)
                #9  0x000000000081208c _ZNK13column_family11make_readerE13lw_shared_ptrIK6schemaERK5rangeIN3dht13ring_positionEERKN5query32clustering_key_filtering_contextERK17io_priority_class (scylla)
                #10 0x0000000000812537 operator() (scylla)
                #11 0x00000000008f1fb3 _ZNKSt8functionIF15mutation_reader13lw_shared_ptrIK6schemaERK5rangeIN3dht13ring_positionEEN5query32clustering_key_filtering_contextERK17io_priority_classEEclES4_SA_SC_SF_ (scylla)
                #12 0x00000000009470a0 _Z10data_query13lw_shared_ptrIK6schemaERK15mutation_sourceRK5rangeIN3dht13ring_positionEERKN5query15partition_sliceEjjNSt6chrono10time_pointI8gc_clockNSG_8durationIiSt5ratioILl1ELl1EEEEE
                #13 0x00000000007c17aa _ZZN13column_family5queryE13lw_shared_ptrIK6schemaERKN5query12read_commandENS4_14result_requestERKSt6vectorI5rangeIN3dht13ring_positionEESaISD_EEENKUlvE_clEv (scylla)
                #14 0x0000000000830d48 do_until_continued<column_family::query(schema_ptr, const query::read_command&, query::result_request, const std::vector<range<dht::ring_position>, std::allocator<range<dht::ring_positio
                #15 0x0000000000832729 _ZN8database5queryE13lw_shared_ptrIK6schemaERKN5query12read_commandENS4_14result_requestERKSt6vectorI5rangeIN3dht13ring_positionEESaISD_EE (scylla)
                #16 0x0000000000cdc5ae operator() (scylla)
                #17 0x0000000000ced853 process (scylla)
                #18 0x0000000000508580 operator() (scylla)
                #19 0x00000000005090f8 _ZN17smp_message_queue16process_incomingEv (scylla)
                #20 0x00000000004d2f45 _ZN7reactor9poll_onceEv (scylla)
                #21 0x00000000005046f4 _ZNKSt8functionIFbvEEclEv (scylla)
                #22 0x000000000057c205 _ZN12app_template14run_deprecatedEiPPcOSt8functionIFvvEE (scylla)
                #23 0x000000000047357a main (scylla)
                #24 0x00007ff1beaa5b15 __libc_start_main (libc.so.6)
                #25 0x00000000004d1d95 _start (scylla)

                Stack trace of thread 3392:
                #0  0x00000000009289ce _ZNK8logalloc15occupancy_stats13used_fractionEv (scylla)
                #1  0x0000000000929df6 __make_heap<__gnu_cxx::__normal_iterator<logalloc::region_impl**, std::vector<logalloc::region_impl*> >, __gnu_cxx::__ops::_Iter_comp_iter<logalloc::tracker::impl::compact_on_idle(reacto
                #2  0x00000000005046ce _ZNKSt8functionIFN7reactor23idle_cpu_handler_resultERKS_IFbvEEEEclES5_ (scylla)
                #3  0x00000000005215cd _ZZN3smp9configureEN5boost15program_options13variables_mapEENKUlvE1_clEv.constprop.3077 (scylla)
                #4  0x00000000005537de _ZNKSt8functionIFvvEEclEv (scylla)
                #5  0x00007ff1bee4cdc5 start_thread (libpthread.so.0)
                #6  0x00007ff1beb7a21d __clone (libc.so.6)

                Stack trace of thread 3395:
                #0  0x00007ff1bee516ca pthread_sigmask (libpthread.so.0)
                #1  0x0000000000528145 _ZN7reactor13signal_poll

**Comment by asias** [comment] 2016-09-07 16:55
Coredump on node 172-30-0-110
[core.gdb.1000.573acc47d0274b8684640ee86c32594a.30347.1473229890000000.172-30-0-110.xz.zip](https://github.com/scylladb/scylla/files/459797/core.gdb.1000.573acc47d0274b8684640ee86c32594a.30347.1473229890000000.172-30-0-110.xz.zip)

**Comment by pdziepak** [comment] 2016-09-14 12:32
This appears to be a coredump of gdb debugging a coredump of scylla. The actual coredump of crashed scylla would be much more useful.

**Comment by pdziepak** [comment] 2016-09-14 15:48
I tried to reproduce the problem locally with no much luck. I am yet to tried AWS, but perhaps that won't be necessary.

The stack trace makes it look very much like our problem with cql restrictions in the form of:

```
SELECT * FROM table WHERE pk=0 AND ck > 5 AND ck < 8
```

(the fact that `5 < 8` is the interesting part here), which is defenitely something that can happen here since `query2` is:

```
select * from keyspace1.standard1 where key = ? and key2 > ? and key2 < ? LIMIT 50
```

**Comment by tgrabiec** [comment] 2016-09-14 16:03
@pdziepak Try `SELECT * FROM table WHERE pk=0 AND ck > 8 AND ck < 5`

**Comment by pdziepak** [comment] 2016-09-14 16:05
Ah, I meant restrictions with start smaller than the end. The example is fixed now.

**Comment by tgrabiec** [comment] 2016-09-14 17:47
Refs https://github.com/scylladb/scylla/issues/1670

**Comment by slivne** [comment] 2016-09-20 19:13
verified with the candidate ami of 1.3.1 ami-b63947a1- this is fixed - closing issue

**Closed by slivne** 2016-09-20 19:13 UTC
Labels: bug
