### ISSUE TITLE
Different token calculation functions for "empty" partition keys cause sstable reader to use index incorrectly

### ISSUE THREAD

**Issue by kbr-** [scylladb/scylla#9352] opened 2021-09-17 11:10 UTC
I'm not sure if this causes an actual bug in production code because I don't know if "empty" partition keys can occur naturally (couldn't create them from CQL), but posting this just in case.

I have a schema with `blob` partition key type:
```
CREATE TABLE ... (
        pk0 blob,
        ....,
        PRIMARY KEY (pk0))
```

I have a value of this key in `dht::decorated_key` format:
```
dht::decorated_key k{...};
std::cout << k << std::endl;
```
it prints as follows:
```
{key: pk{0000}, token:0}
```

When I `explode` it, I get a vector of size `1` containing an empty `bytes`:
```
auto vec = k.explode(s);
std::cout << vec.size() << " " << vec << " " << vec[0].size() << std::endl;
```
result:
```
1 {} 0
```

So apparently this is a key with a single column whose value is an empty blob; the key is represented as `0000` in serialized form. I'm guessing this `0000` denotes the blob's size. I got this key from a mutation that was generated by `generate_random_mutations` in test/lib/random_schema.hh.

In a test, I created an sstable using this and some other mutations. This sstable's partition key index contains a single page, and among the entries in this page is an entry with this key:
```
TRACE 2021-09-17 12:17:49,781 [shard 0] sstable - index 0x60100001e000 bound 0x60100001e070: page:
TRACE 2021-09-17 12:17:49,781 [shard 0] sstable -   {key: pk{0010fffe81a2d0a483b760eba3bfa395e5d8}, token:-7666695272245969689} -> 0
TRACE 2021-09-17 12:17:49,781 [shard 0] sstable -   {key: pk{0011ac795b361b3218b7a479b98132c067ef22}, token:-7047076813233896397} -> 4016
TRACE 2021-09-17 12:17:49,781 [shard 0] sstable -   {key: pk{00075c536477ad7842}, token:-6422108399605007642} -> 10431
TRACE 2021-09-17 12:17:49,781 [shard 0] sstable -   {key: pk{001ebd5ee00751bbec821cee44e7e6055ffa6d0ea50b3342e736511e85eddaca}, token:-5731315764860802051} -> 15622
TRACE 2021-09-17 12:17:49,781 [shard 0] sstable -   {key: pk{00175fc396083983d96b8866cb88957439a3dfc82d1b7b71fb}, token:-5080536638769575688} -> 21953
TRACE 2021-09-17 12:17:49,781 [shard 0] sstable -   {key: pk{001b54b4dd6b7afd961ce544da04fccb7db04e94263d51f0bea843619c}, token:-2826028800328955929} -> 34517
TRACE 2021-09-17 12:17:49,781 [shard 0] sstable -   {key: pk{0016581a5b0b58ec1f25e2f0cc648e76c5e2fa4a4f07fa11}, token:-2358308865434803126} -> 39082
TRACE 2021-09-17 12:17:49,781 [shard 0] sstable -   {key: pk{001657ca9f021164ef6584a08ab5bf8d97f03187a5f4f426}, token:-1618278504687846796} -> 45934
TRACE 2021-09-17 12:17:49,781 [shard 0] sstable -   {key: pk{0000}, token:0} -> 50158
```

When looking for a partition, the index reader algorithm uses a different class (not `dht::decorated_key`) to interpret the keys: `sstables::decorated_key_view`. While `dht::decorated_key` (which is a key, token pair) uses `partition_key` to store the key internally, `sstables::decorated_key_view` (which is also a key, token pair) uses `sstables::key_view`. The index calculates the tokens on the fly:
```
class index_entry {
private:
    managed_bytes _key;
    mutable std::optional<dht::token> _token;
    ....
    key_view get_key() const {
        return key_view{_key};
    }

    // May allocate so must be called under allocating_section.
    decorated_key_view get_decorated_key(const schema& s) const {
        if (!_token) {
            _token.emplace(s.get_partitioner().get_token(get_key()));
        }
        return decorated_key_view(*_token, get_key());
    }
```

There are two `i_partitioner::get_token` functions, one for `partition_key`s and one for `sstables:key_view`s:
```
    virtual token get_token(const schema& s, partition_key_view key) const = 0;
    virtual token get_token(const sstables::key_view& key) const = 0;
```

The first version obtains token `0` for our key:
```
token murmur3_partitioner::get_token(const schema& s, partition_key_view key) const {
    std::array<uint64_t, 2> hash;
    auto&& legacy = key.legacy_form(s);
    utils::murmur_hash::hash3_x64_128(legacy.begin(), legacy.size(), 0, hash);
    return get_token(hash[0]);
}
```

but the second obtains `minimum_token()`:
```
token murmur3_partitioner::get_token(const sstables::key_view& key) const {
    return key.with_linearized([&] (bytes_view v) {
        return get_token(v);
    });
}

token murmur3_partitioner::get_token(bytes_view key) const {
    if (key.empty()) {
        return minimum_token();
    }
    std::array<uint64_t, 2> hash;
    utils::murmur_hash::hash3_x64_128(key, 0, hash);
    return get_token(hash[0]);
}
```
because it enters the `key.empty()` case.

The index uses `index_entry::get_decorated_key`, hence the second version of `get_token` when performing a binary search when looking for a partition in the index page (sstables/index_reader.hh):
```
        return advance_to_page(bound, summary_idx).then([this, &bound, pos, summary_idx] {
            auto i = _alloc_section(_region, [&] {
                return std::lower_bound(std::begin(entries) + bound.current_index_idx, std::end(entries), pos,
                    index_comparator(*_sstable->_schema));
            });
```

with the page printed above, this is a binary search performed on a non-monotonic vector. This is because the last entry is considered to have the token `minimum_token()`, which compares before all other entries, but it is placed at the end!

This may cause the sstable reader to consider a partition missing even when it's there.

---

Two questions:
- is this even a "real" problem? Can such keys occur in production?
- how to fix this? Which token calculation function is wrong? Should we perform additional validation to detect this stuff?

Ad. second bullet, I tried to catch the `minimum_token()` at the sstable writer level (in `mutation_fragment_stream_validator`). However it doesn't work, because at that point we're using the `dht::decorated_key` format, so the token of this key here is calculated as `0`.

cc @tgrabiec @denesb

**Comment by tgrabiec** [comment] 2021-09-17 11:33
According to https://issues.apache.org/jira/browse/CASSANDRA-5965, you can run into this when indexing an empty column.

Cassandra has this, so the variant with the empty check is compatible with Cassandra:

```
 private LongToken getToken(ByteBuffer key, long[] hash)
    {
        if (key.remaining() == 0)
            return MINIMUM;

        return new LongToken(normalize(hash[0]));
    }
```

**Comment by tgrabiec** [comment] 2021-09-17 11:36
But it contradicts itself below, where it says no key should have MINIMUM token:
```
    /**
     * Generate the token of a key.
     * Note that we need to ensure all generated token are strictly bigger than MINIMUM.
     * In particular we don't want MINIMUM to correspond to any key because the range (MINIMUM, X] doesn't
     * include MINIMUM but we use such range to select all data whose token is smaller than X.
     */
    public LongToken getToken(ByteBuffer key)
    {
        return getToken(key, getHash(key));
    }

```

**Comment by tgrabiec** [comment] 2021-09-17 11:46
I vaguely remember that empty keys used to be banned, but maybe they can get into the system via indexing now. 

Empty value indexing is broken:

```
cqlsh:ks> select * from cf;

 name    | val1    | val2
---------+---------+------
  dmeyer | testval |     


(1 row)

cqlsh:ks> select * from cf where val2 = '' allow filtering;

 name | val1 | val2
------+------+------

(0 rows)


cqlsh:ks> drop index cf_val2_idx ;


cqlsh:ks> select * from cf where val2 = '' allow filtering;

 name   | val1    | val2
--------+---------+------
 dmeyer | testval |     


```

But it's not due to this bug, since sstable reader is not involved.

**Comment by denesb** [comment] 2021-09-17 11:57
We had problems in the past with empty partition keys getting into the system (cause still unknown) and the sstable writer refusing to write the sstable, causing a spin on memtable flush and later on commitlog replay.

**Comment by denesb** [comment] 2021-09-17 11:57
CQL rejects empty partition keys.

**Comment by haaawk** [comment] 2021-09-17 11:59
> CQL rejects empty partition keys.

What about Thrift?

**Comment by psarna** [comment] 2021-09-17 17:53
> I vaguely remember that empty keys used to be banned, but maybe they can get into the system via indexing now.
> 
> Empty value indexing is broken:
> 
> ```
> cqlsh:ks> select * from cf;
> 
>  name    | val1    | val2
> ---------+---------+------
>   dmeyer | testval |     
> 
> 
> (1 row)
> 
> cqlsh:ks> select * from cf where val2 = '' allow filtering;
> 
>  name | val1 | val2
> ------+------+------
> 
> (0 rows)
> 
> 
> cqlsh:ks> drop index cf_val2_idx ;
> 
> 
> cqlsh:ks> select * from cf where val2 = '' allow filtering;
> 
>  name   | val1    | val2
> --------+---------+------
>  dmeyer | testval |     
> ```
> 

That's a known issue, and we're currently leaning toward a statement that it's a feature, not a bug, since we simply don't index nulls. Cassandra also doesn't seem to work, even though their indexes are local - below is the output from Cassandra 4:
```cql
cassandra@cqlsh:ks> select * from cf;

 name   | val1    | val2
--------+---------+------
 dmeyer | testval |     


cassandra@cqlsh:ks> select * from cf where val2 = '';

 name | val1 | val2
------+------+------

(0 rows)
cassandra@cqlsh:ks> drop index cf_val2_idx ;
cassandra@cqlsh:ks> select * from cf where val2 = '' allow filtering;

 name   | val1    | val2
--------+---------+------
 dmeyer | testval |     
(1 rows)
```
Ref: https://github.com/scylladb/scylla/issues/8489, https://github.com/scylladb/scylla/issues/8517

**Comment by psarna** [comment] 2021-09-17 17:55
Oh wait, I might have tested on Scylla by mistake, let me recheck

**Comment by psarna** [comment] 2021-09-17 17:56
Yup, my bad, it works on Cassandra.

**Comment by tgrabiec** [comment] 2021-09-17 21:25
@psarna Here we don't have a case of unset value (null), but a value which contains a string of length 0. There is a row with such a column. A query or a row with such a value makes sense to me, and it works if there is no index.

**Comment by psarna** [comment] 2021-09-18 06:16
Ah, right, it's an empty string. You're right that we should generally support it, but we don't because empty keys are disallowed - and our indexes are based on materialized views which uses the indexed column as a key. So the behavior is known, but we don't have any immediate plans to fix it.

**Comment by avikivity** [comment] 2021-09-19 12:18
Thrift can inject empty keys (including empty fixed-sized cells just as `int`).

**Comment by tgrabiec** [comment] 2021-09-20 13:03
Looks like all mutations are prepared by the thrift server with partition key created with `key_from_thrift()`, which calls `validate_key()`, which rejects empty keys:
```
void validate_key(const schema& s, const bytes_view& k) {
    if (k.empty()) {
        throw make_exception<InvalidRequestException>("Key may not be empty");
    }
```

**Comment by kbr-** [comment] 2021-09-20 13:17
Anyway it does seem that empty partition keys can appear at least in index.
So the question is what the correct token should be?
IIRC the token we use almost everywhere and even save in sstables is token 0, which makes sense: it's a hash function calculated on an empty string. The problem occurs during index read, where the token is recalculated in memory using a different algorithm.
Btw. `minimum_token()` seems to be a bad idea anyway, it's basically an artificially created edge case.

**Comment by tgrabiec** [comment] 2021-09-21 11:51
I would say that assigning token 0 to empty keys is the way to go, but the problem is what to do with get_token(). Clearly, in some cases it is expected to return minimum_token for empty keys, (what for?). Those cases have to be distinguished from the cases where it is passed a real key. If we allow empty keys into the system, we should review those places.

**Comment by tgrabiec** [comment] 2021-09-21 11:53
If Cassandra allows empty keys in sstables, we should be compatible with its choice of the token.

**Comment by nyh** [comment] 2021-09-22 08:32
> CQL rejects empty partition keys.

This is apparently true true, though I never saw this documented anywhere or an explanation why this is the case. I don't remember the sstable encoding, maybe this was caused by an attempt to save a byte or two in encoding the partition key (so only one size, not two)? 

The following write, with an empty string for the partition key `p`, fails in both Scylla and Cassandra, stating that "Key may not be empty":
```CQL
INSERT INTO {table1} (p,c,v) VALUES ('', 's', 'dog')
```
However empty strings _are allowed_ for the clustering key - the following works:
```CQL
INSERT INTO {table1} (p,c,v) VALUES ('s', '', 'dog')
```

By the way, the "minimum token" choice is mentioned in a Cassandra issue:  https://issues.apache.org/jira/browse/CASSANDRA-11487

**Comment by avikivity** [comment] 2021-09-22 11:53
> I would say that assigning token 0 to empty keys is the way to go, but the problem is what to do with get_token(). Clearly, in some cases it is expected to return minimum_token for empty keys, (what for?).

Maybe it's for the "key not supplied" case (rather than empty key). e.g. disengaged optional<key>. Those should take completely different paths (full scan vs partition scan) but maybe in the distant past there was shared code handling it.


> Those cases have to be distinguished from the cases where it is passed a real key. If we allow empty keys into the system, we should review those places.

**Comment by nyh** [comment] 2021-09-22 13:48
> I would say that assigning token 0 to empty keys is the way to go, but the problem is what to do with get_token(). Clearly, in some cases it is expected to return minimum_token for empty keys, (what for?).

I agree. I'm trying such a trivial patch right now and will see where it brings us.
I can't find any code which actually checks if the result of the token is minimum_token, but maybe I'm missing something.

One thing that this change will cause is incompatibility with old Cassandra and Scylla generated sstables which had empty strings. But the good news that the tests I just wrote for this issue and the two related issues #9375 and #9364 confirmed that Cassandra doesn't allow empty strings in base tables and we are not compatible with their sstable format for views and SI anyway, and also the tests confirmed that empty string partition keys were broken for current versions of Scylla - so we can't break backward compatibility with something that didn't work.

> Those cases have to be distinguished from the cases where it is passed a real key. If we allow empty keys into the system, we should review those places.

I can't find any such places yet that use an empty string as a signal that there isn't a real key. Maybe I'm missing something, I'll have to dig deeper.

**Comment by tgrabiec** [comment] 2021-09-22 14:10
On Wed, Sep 22, 2021 at 3:48 PM nyh ***@***.***> wrote:

> I would say that assigning token 0 to empty keys is the way to go, but the
> problem is what to do with get_token(). Clearly, in some cases it is
> expected to return minimum_token for empty keys, (what for?).
>
> I agree. I'm trying such a trivial patch right now and will see where it
> brings us.
> I can't find any code which actually checks if the result of the token is
> minimum_token, but maybe I'm missing something.
>

One theoretical use case which comes to mind is to express [-inf, x]
partition key range using key values only. You'd put an empty key to
represent the -inf bound. Maybe some legacy internal interface in Cassandra
worked this way at some point. I don't think we rely on it.

**Comment by nyh** [comment] 2021-09-22 15:10
Surprisingly, issues #9375 and #9364 (about empty strings in materialized views and secondary indexes) stemmed from a different bug, not this one. I'm sending a patch for it right now, but we should consider whether we want to commit a patch for **this** issue in the same series. 

The reason I'm saying this that before fixing #9375 and #9364, there was no way to get an empty partition key with any mechanism - not even using an index or materialized views. After fixing those issues, empty partitions will be possible. So if we don't want their token to just change one day in the future when we reconsider this issue, we should decide the right token for the empty partition key right now. I think it should be hash('') (I guess that's zero) - not "MINIMUM".

**Comment by nyh** [comment] 2021-09-30 11:33
> One theoretical use case which comes to mind is to express [-inf, x] partition key range using key values only. You'd put an empty key to represent the -inf bound. Maybe some legacy internal interface in Cassandra worked this way at some point. I don't think we rely on it.

@tgrabiec unfortunately it seems that in multiple places (I found already the view builder, flat_mutation_reader.cc, mutation_reader.cc, etc.) that we use the convention that the "first possible partition" is the pair `(dht::minimum_token(), partition_key::make_empty())`.

**Comment by nyh** [comment] 2021-09-30 12:01
Yes, I can confirm that fixing murmur3_partitioner::get_token(const schema& s, partition_key_view key) to return minimum_token() for the empty key is necessary to be able to find an empty key in the sstable index file (reproduced by my test for empty strings in a materialized view). I'll send a patch for this for review.

**Closed** 2022-03-08 22:10 UTC
Labels: bug, internals
