### ISSUE TITLE
Compaction-strategy aware major compaction

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylla#1431] opened 2016-07-06 13:20 UTC
_Installation details_
Scylla version (or git commit hash): 1.2

Creating one huge sstable is only suitable for size tiered compaction.  For level tiered, it is better to guess the level and compact all files into 160MB-sized sstables at that level.  For date tiered, it is better to segregate data  by time.

This allows changing the compaction strategy, and issuing a major compaction to get the sstable layout aligned with the strategy.

**Comment by avikivity** [comment] 2016-07-06 13:21
@raphaelsc

**Comment by raphaelsc** [comment] 2016-07-06 19:38
@avikivity I think C* implements a notion of major compaction for each strategy. Each strategy will return a maximum task. I think that's the way to go. I will get more details by reading the code in C*.

**Comment by tzach** [comment] 2016-08-07 09:53
@avikivity with the new "always compact" feature in 1.3, is this still relevant?

**Comment by raphaelsc** [comment] 2016-08-07 11:37
@tzach Yes, that's for user initiated compaction. User may disable compaction for example and initiate a major compaction on its own. The current implementation of user initiated compaction is very fragile, and I think we should either let the user know about the fragility or disable it until we provide users with a solid implementation.

**Comment by tzach** [comment] 2016-08-07 17:33
Agree major compaction are dangerous and I know of at least one user who used with Scylla base on an out of date Cassandra guide.
But this issue does not suggest disabling it.

**Comment by raphaelsc** [comment] 2016-11-03 22:52
"This allows changing the compaction strategy, and issuing a major compaction to get the sstable layout aligned with the strategy." That happens naturally after multiple compactions, starting from point user changed strategy. Major compaction, at least from C*'s perspective, is about getting all tables and inserting into one. For leveled strategy, it's about compaction all sstables into L0, still respecting max sstable size. I dislike major compaction for other strategies and I think it's completely unnecessary after changing strategy. But we need to compatible...

**Comment by nyh** [comment] 2018-07-15 12:34
For the question of what "major compaciton" does on LCS in Cassandra today, see https://issues.apache.org/jira/browse/CASSANDRA-7272. and their plan to improve it: https://issues.apache.org/jira/browse/CASSANDRA-11817

**Comment by slivne** [comment] 2018-08-08 15:26
@bhalevy - lets start with LCS and make that work

**Comment by nyh** [comment] 2018-11-18 10:49
Hi @raphaelsc, @gleb-cloudius just encountered a problem with major compaction on LCS causing disk usage to grow significantly - it appears around double. I am guessing this happens because during the compaction we have both the one huge sstable that major compaction always used to generate - and the normal leveled small sstables. I see that above, you have an uncomitted patch which may improve this situation. What is the status of this patch?

**Comment by raphaelsc** [comment] 2018-11-21 18:08
On Sun, Nov 18, 2018 at 8:49 AM nyh <notifications@github.com> wrote:

> Hi @raphaelsc <https://github.com/raphaelsc>, @gleb-cloudius
> <https://github.com/gleb-cloudius> just encountered a problem with major
> compaction on LCS causing disk usage to grow significantly - it appears
> around double. I am guessing this happens because during the compaction we
> have both the one huge sstable that major compaction always used to
> generate - and the normal leveled small sstables. I see that above, you
> have an uncomitted patch which may improve this situation. What is the
> status of this patch?
>
I thought the work for LCS was committed, but it is not. I need to rebase
and there's a nitpick to be addressed.

**Comment by bhalevy** [comment] 2019-03-27 13:10
@raphaelsc what else needs to be done here?
Can we close this issue?

**Comment by raphaelsc** [comment] 2019-03-27 13:11
On Wed, Mar 27, 2019 at 10:10 AM Benny Halevy <notifications@github.com>
wrote:

> @raphaelsc <https://github.com/raphaelsc> what else needs to be done here?
> Can we close this issue?
>

We need to make it work for TWCS. that's the only thing left to do!

**Closed** 2020-04-07 12:39 UTC
Labels: enhancement

**Comment by vladzcloudius** [comment] 2021-07-16 17:17
@raphaelsc Could you, please, tell if as a result of this change TWCS `major` disk space requirement is no longer x2? If yes, what's the estimate of the upper bound of the needed free disk space?

**Comment by vladzcloudius** [comment] 2021-09-20 14:42
> @raphaelsc Could you, please, tell if as a result of this change TWCS `major` disk space requirement is no longer x2? If yes, what's the estimate of the upper bound of the needed free disk space?

@raphaelsc ping. Could you, please, clarify the point above?

**Comment by raphaelsc** [comment] 2021-09-20 14:48
> > @raphaelsc Could you, please, tell if as a result of this change TWCS `major` disk space requirement is no longer x2? If yes, what's the estimate of the upper bound of the needed free disk space?
> 
> @raphaelsc ping. Could you, please, clarify the point above?

the space requirement is 2x as all windows are compacted together. so apply same rule as for STCS.

**Comment by vladzcloudius** [comment] 2021-09-20 15:47
> > > @raphaelsc Could you, please, tell if as a result of this change TWCS `major` disk space requirement is no longer x2? If yes, what's the estimate of the upper bound of the needed free disk space?
> > 
> > 
> > @raphaelsc ping. Could you, please, clarify the point above?
> 
> the space requirement is 2x as all windows are compacted together. so apply same rule as for STCS.

Thanks, @raphaelsc.
I'd suggest to consider compacting one window at a time.
This would allow us keep the same free disk space requirement during the major as during the regular operation. 
AFAIR this invariant holds for other compaction strategies, right?

**Comment by raphaelsc** [comment] 2021-09-20 16:53
> > > > @raphaelsc Could you, please, tell if as a result of this change TWCS `major` disk space requirement is no longer x2? If yes, what's the estimate of the upper bound of the needed free disk space?
> > > 
> > > 
> > > @raphaelsc ping. Could you, please, clarify the point above?
> > 
> > 
> > the space requirement is 2x as all windows are compacted together. so apply same rule as for STCS.
> 
> Thanks, @raphaelsc.
> I'd suggest to consider compacting one window at a time.
> This would allow us keep the same free disk space requirement during the major as during the regular operation.
> AFAIR this invariant holds for other compaction strategies, right?

Pros:
low space requirement, bounded by size of each window

Cons:
no longer compact across windows, so user which relied on major to get rid of tombstones, etc, can no longer count on it. tombstone is, however, an anti-pattern for TWCS.

@vladzcloudius I am interested in knowing why someone needs major for TWCS. By design, TWCS should work to limit each window to 1 sstable[1]. And drop the window once it gets expired. 

[1] after data segregation, now windows may have more than 1 sstable, but number should be small.

**Comment by vladzcloudius** [comment] 2021-09-20 18:19
@raphaelsc 
Right. We DO need to compact them all together if we want to make major "re-shape" data according to (possibly new) time window configuration - and we DO want it.

However sometimes people would want to reshape their when they don't have 50% free disk space. ICS would allow addressing this but unfortunately it's an enterprise-only feature.

On a second thought however you only need to compact 3 (old) time windows at the same time during reshaping.

As for tombstones - do you really need extra disk space to handle them?

**Comment by raphaelsc** [comment] 2021-09-20 18:29
> @raphaelsc
> Right. We DO need to compact them all together if we want to make major "re-shape" data according to (possibly new) time window configuration - and we DO want it.
> 
> However sometimes people would want to reshape their when they don't have 50% free disk space. ICS would allow addressing this but unfortunately it's an enterprise-only feature.

with space controller, we'll be able to limit major concurrency across shards based on amount of space available. our shared-nothing arch allows us to do that :-) 

> 
> On a second thought however you only need to compact 3 (old) time windows at the same time during reshaping.
> 
> As for tombstones - do you really need extra disk space to handle them?

if user for example deleted data in past windows, then we need to compact across windows for shadowed data to be purged.

**Comment by vladzcloudius** [comment] 2021-09-20 22:25
> if user for example deleted data in past windows, then we need to compact across windows for shadowed data to be purged.

I understand why you need to read them all (time windows) to do that - but it's not clear to me why you'd need to write them all at the same time, @raphaelsc
