### ISSUE TITLE
/var directory disk full

### ISSUE THREAD

**Issue by infordb** [scylladb/scylla#2174] opened 2017-03-19 23:46 UTC
*Installation details*
Scylla version (or git commit hash): scylla-server-1.6.1-20170218.2ea4da2.el7.centos.x86_64

**ScyllaDB became a jombie after /var directory disk full**

<< /var/log/messages >>
Mar 18 16:17:06 swfosldb01 scylla: [shard 0] storage_proxy - Failed to apply mutation from 10.40.74.103#7: std::bad_alloc (std::bad_alloc)
Mar 18 16:17:06 swfosldb01 scylla: [shard 0] storage_proxy - Failed to apply mutation from 10.40.74.103#7: std::bad_alloc (std::bad_alloc)
Mar 18 16:17:06 swfosldb01 scylla: [shard 7] storage_proxy - Failed to apply mutation from 10.40.74.102#1: std::bad_alloc (std::bad_alloc)Mar 18 16:17:06 swfosldb01 scylla: [shard 7] storage_proxy - exception during mutation write to 10.40.74.101: std::bad_alloc (std::bad_alloc)
Mar 18 16:17:06 swfosldb01 scylla: [shard 7] storage_proxy - exception during mutation write to 10.40.74.101: std::bad_alloc (std::bad_alloc)
Mar 18 16:17:06 swfosldb01 scylla: [shard 7] storage_proxy - exception during mutation write to 10.40.74.101: std::bad_alloc (std::bad_alloc)

**so I restarted scylladb 
but Scyladb can not start with the following message
Do you know how to start normally without deleting the data ??**

Mar 20 08:37:42 swfosldb01 scylla: [shard 0] commitlog_replayer - error replaying: std::bad_alloc (std::bad_alloc)
Mar 20 08:37:42 swfosldb01 scylla: [shard 0] commitlog_replayer - error replaying: std::bad_alloc (std::bad_alloc)
Mar 20 08:37:42 swfosldb01 scylla: [shard 0] commitlog_replayer - error replaying: std::bad_alloc (std::bad_alloc)
Mar 20 08:37:42 swfosldb01 scylla: [shard 0] commitlog_replayer - error replaying: std::bad_alloc (std::bad_alloc)
Mar 20 08:37:44 swfosldb01 scylla: [shard 0] database - failed to move memtable for /scylla/data/foms/fdc_unit_param_data-d296dba00ae511e7850c000000000000/foms-fdc_unit_param_data-ka-45208-Data.db to cache: std::bad_alloc (std::bad_alloc)
Mar 20 08:37:45 swfosldb01 scylla: [shard 0] database - failed to write sstable /scylla/data/foms/fdc_unit_param_data-d296dba00ae511e7850c000000000000/foms-fdc_unit_param_data-ka-45224-Data.db: std::bad_alloc (std::bad_alloc)
Mar 20 08:37:46 swfosldb01 scylla: [shard 0] database - failed to move memtable for /scylla/data/foms/fdc_unit_param_data-d296dba00ae511e7850c000000000000/foms-fdc_unit_param_data-ka-45216-Data.db to cache: std::bad_alloc (std::bad_alloc)

**Comment by avikivity** [comment] 2017-03-20 10:37
Duplicate of #2098.

**Closed by avikivity** 2017-03-20 10:37 UTC
