### ISSUE TITLE
cqlsh C* 4.0 compatibility with python3 and DESC SCHEMA

### ISSUE THREAD

**Issue by tarzanek** [scylladb/scylla#8570] opened 2021-04-30 07:02 UTC
cassandra 4.0 python3 cqlsh from https://github.com/apache/cassandra/tree/trunk/bin does not support DESC SCHEMA on scylla

it can likely translate to https://github.com/scylladb/scylla-tools-java repo only, but I wanted to file here first so we can check compatibility from scylla / cql protocol first

**Comment by slivne** [comment] 2021-05-10 08:42
Cassandra 4.0.0 is not yet out - there is only an rc1 now ... once its out we can revisit this

**Comment by tomer-sandler** [comment] 2022-03-08 17:07
Multiple Scylla users hit this issue (`DESCRIBE` commands no longer supported) while using C* 4.0 `cqlsh`
Note C* `cqlsh 6.0.0`, while Scylla uses `cqlsh 5.0.1`

```
cqlsh> SHOW VERSION
[cqlsh 6.0.0 | Cassandra 3.0.8 | CQL spec 3.3.1 | Native protocol v4]
cqlsh> DESCRIBE KEYSPACES;
WARN: DESCRIBE|DESC was moved to server side in Cassandra 4.0. As a consequence DESRIBE|DESC will not work in cqlsh '6.0.0' connected to Cassandra '3.0.8', the version that you are connected to. DESCRIBE does not exist server side prior Cassandra 4.0.
```

**Comment by yuriy-yarosh** [comment] 2022-03-21 20:03
@tomer-sandler I'm working on Cassandra/ScyllaDB connector for Typelevel Scala (similar to [skunk](https://github.com/tpolecat/skunk/)). Are there any plans for cassandra [NativeProtocol 5](https://github.com/apache/cassandra/blob/cassandra-4.0/doc/native_protocol_v5.spec) (aka "beta C* 4.0 proto") and CQL 3.4.5 support ?

**Comment by tomer-sandler** [comment] 2022-03-23 18:00
> @tomer-sandler I'm working on Cassandra/ScyllaDB connector for Typelevel Scala (similar to [skunk](https://github.com/tpolecat/skunk/), but without any java deps whatsoever). Are there any plans for cassandra [NativeProtocol 5](https://github.com/apache/cassandra/blob/cassandra-4.0/doc/native_protocol_v5.spec) (aka "beta C* 4.0 proto") and CQL 3.4.5 support ?

Hello @yuriy-yarosh, that's a question for our Engineering @slivne  and/or Product Mgmt @tzach

**Comment by eliransin** [comment] 2022-05-08 05:53
It is a duplicate of #9571 I will sync with @psarna about what are we doing with that.

**Comment by nyh** [comment] 2022-05-08 09:52
This is indeed a duplicate of #9571. It is customary to close the newer duplicate, but in this case, the newer duplicate has slightly more information so I'll close this one - I hope nobody minds.

**Closed by nyh** 2022-05-08 09:52 UTC
Labels: cassandra 4.x compatibility
