### ISSUE TITLE
scylla 1.3 performance is less than scylla 1.01

### ISSUE THREAD

**Issue by infordb** [scylladb/scylla#1649] opened 2016-09-05 23:42 UTC
_Installation details_
Scylla version (or git commit hash):1.3
Cluster size:3
OS (CentOS):

_Hardware details (for performance issues)_  
Server Spec is 
32Core
64G memory
300G SSD raid.

ScyllaDB configuration info is
8core, 32G memory  

Hi
we have a question that scylladb performance when upgrading version up.
we tested ScyllaDB with cassandra-stress tool and got result.

Stress-tool result : 
![image](https://cloud.githubusercontent.com/assets/10610884/18258248/14aa4a60-740d-11e6-90db-b2e9abd407ab.png)

**_we want to know that scylla 1.3 performance is less than scylla 1.01._**

schema is 10 column table and size is default(4~8 bytes).
added 3 files.(first is cassandra-tool yaml file, second and third is scylladb config file.)

cassandra-stress command is 
cassandra-stress user duration=10m cl=QUORUM profile=/home/cassandra/case2.yaml ops(insert=1) -pop 'dist=gauss(1..10000000,5000000,5000000)' -port native=50006 -rate threads=400 -node 70.60.31.157,70.60.31.158,70.60.31.159
cassandra-stress user duration=10m cl=QUORUM profile=/home/cassandra/case2.yaml ops(insert=1) -pop 'dist=gauss(10000001..20000000,15000000,1500000)' -port native=50006 -rate threads=400 -node 70.60.31.157,70.60.31.158,70.60.31.159
cassandra-stress user duration=10m cl=QUORUM profile=/home/cassandra/case2.yaml ops(insert=1) -pop 'dist=gauss(20000001..30000000,25000000,2500000)' -port native=50006 -rate threads=400 -node 70.60.31.157,70.60.31.158,70.60.31.159
cassandra-stress user duration=10m cl=QUORUM profile=/home/cassandra/case2.yaml ops(insert=1) -pop 'dist=gauss(30000001..40000000,35000000,3500000)' -port native=50006 -rate threads=400 -node 70.60.31.157,70.60.31.158,70.60.31.159
cassandra-stress user duration=10m cl=QUORUM profile=/home/cassandra/case2.yaml ops(insert=1) -pop 'dist=gauss(40000001..50000000,45000000,4500000)' -port native=50006 -rate threads=400 -node 70.60.31.157,70.60.31.158,70.60.31.159
cassandra-stress user duration=10m cl=QUORUM profile=/home/cassandra/case2.yaml ops(insert=1) -pop 'dist=gauss(50000001..60000000,55000000,5500000)' -port native=50006 -rate threads=400 -node 70.60.31.157,70.60.31.158,70.60.31.159
cassandra-stress user duration=10m cl=QUORUM profile=/home/cassandra/case2.yaml ops(insert=1) -pop 'dist=gauss(60000001..70000000,65000000,6500000)' -port native=50006 -rate threads=400 -node 70.60.31.157,70.60.31.158,70.60.31.159
cassandra-stress user duration=10m cl=QUORUM profile=/home/cassandra/case2.yaml ops(insert=1) -pop 'dist=gauss(70000001..80000000,75000000,7500000)' -port native=50006 -rate threads=400 -node 70.60.31.157,70.60.31.158,70.60.31.159
cassandra-stress user duration=10m cl=QUORUM profile=/home/cassandra/case2.yaml ops(insert=1) -pop 'dist=gauss(80000001..90000000,85000000,8500000)' -port native=50006 -rate threads=400 -node 70.60.31.157,70.60.31.158,70.60.31.159
at 3 another server.

thank you.

**Comment by dorlaor** [comment] 2016-09-06 04:31
On Mon, Sep 5, 2016 at 4:42 PM, infordb <notifications@github.com> wrote:

> *Installation details*
> Scylla version (or git commit hash):1.3
> Cluster size:3
> OS (CentOS):
>
> *Hardware details (for performance issues)*
>
> Server Spec is
> 32Core
> 64G memory
> 300G SSD raid.
>
> ScyllaDB configuration info is
> 8core, 32G memory
>
> Hi
> we have a question that scylladb performance when upgrading version up.
> we tested ScyllaDB with cassandra-stress tool and got result.
>
> Stress-tool result :
> [image: image]
> <https://cloud.githubusercontent.com/assets/10610884/18258248/14aa4a60-740d-11e6-90db-b2e9abd407ab.png>
>
> *we want to know that scylla 1.3 performance is less than scylla 1.01.*
>

Thanks for sharing these details.
Can you please verify that on the same hardware and the same dataset you get
such performance diff? Please also monitor timeouts and errors, at least
0.17 may
have omitted those.

In addition, can we get the disk utilization data from iostat, and the load
gauge from
collectd? We'll need also to figure out whether all cores are busy with sar
-P ALL to make sure no single core is overwhelmed

**Comment by penberg** [comment] 2016-09-06 04:36
@syuu1228 @slivne Is this the IRQ inbalance issue in Scylla 1.3?

**Comment by ban4785** [comment] 2016-09-07 06:37
hello i worked scylla 1.3 performace test with infordb.

there was no timeouts and erros in same hardware while testing scylla 1.3.

irqbalance was
IRQBALANCE_ARGS=" --banirq=118 --banirq=119 --banirq=120 --banirq=121 --banirq=122 --banirq=123 --banirq=124 --banirq=125 --banirq=126 --banirq=127 --banirq=128 --banirq=129 --banirq=130 --banirq=131 --banirq=132 --banirq=133 --banirq=134 --banirq=135 --banirq=136 --banirq=137 --banirq=138 --banirq=139 --banirq=140 --banirq=141 --banirq=142 --banirq=143 --banirq=144 --banirq=145 --banirq=146 --banirq=147 --banirq=148 --banirq=149 --banirq=150"

monitoring by tessera(collectd data)
cpu load was almost 99% each 3 nodes and  CQL requests servered per second was total 100k.

disk io/s using iostat was average 30mb read/s and 150mb write/s per node.

i think we tested scylladb max performance because cpu load was 99%.

**Comment by penberg** [comment] 2016-09-07 15:25
I am under the impression that commit https://github.com/scylladb/scylla/commit/0c3bb2ee63c28046d1e11069bc670ec250c03a67 and commit https://github.com/scylladb/scylla/commit/533dc0485d5568fdc3f738428aa655e4553d80c1 are supposed to fix the regression, but I am looking for confirmation from @syuu1228 and @avikivity before I can backport them to 1.3.

**Comment by syuu1228** [comment] 2016-09-07 17:34
@ban4785 Witch NIC are you using? Could you provide your /etc/sysconfig/scylla-server
Have you tried to run scylla_setup? if yes, what did you configure on it?

**Comment by dorlaor** [comment] 2016-09-07 17:55
On Tue, Sep 6, 2016 at 11:37 PM, ban4785 <notifications@github.com> wrote:

> hello i worked scylla 1.3 performace test with infordb.
>
> there was no timeouts and erros in same hardware while testing scylla 1.3.
>
> irqbalance was
> IRQBALANCE_ARGS=" --banirq=118 --banirq=119 --banirq=120 --banirq=121
> --banirq=122 --banirq=123 --banirq=124 --banirq=125 --banirq=126
> --banirq=127 --banirq=128 --banirq=129 --banirq=130 --banirq=131
> --banirq=132 --banirq=133 --banirq=134 --banirq=135 --banirq=136
> --banirq=137 --banirq=138 --banirq=139 --banirq=140 --banirq=141
> --banirq=142 --banirq=143 --banirq=144 --banirq=145 --banirq=146
> --banirq=147 --banirq=148 --banirq=149 --banirq=150"
>
> monitoring by tessera(collectd data)
> cpu load was almost 99% each 3 nodes and CQL requests servered per second
> was total 100k.
>

Is that take from 'top' or from the load gauge?

**Comment by ban4785** [comment] 2016-09-08 00:03
we used /usr/lib/scylla/posix_net_conf.sh enp4s0f0 -mq  commasnd before testing and /usr/lib/scylla/scylla_io_setup(for /etc/scylla.d/io.conf).

our /etc/sysconfig/scylla-server is
(
# choose following mode: virtio, dpdk, posix
NETWORK_MODE=posix

# tap device name(virtio)
TAP=tap0

# bridge device name (virtio)
BRIDGE=virbr0

# ethernet device name
IFNAME=eth0

# setup NIC's interrupts, RPS, XPS (posix)
SET_NIC=no

# ethernet device driver (dpdk)
ETHDRV=

# ethernet device PCI ID (dpdk)
ETHPCIID=

# number of hugepages
NR_HUGEPAGES=64

# user for process (must be root for dpdk)
USER=scylla

# group for process
GROUP=scylla

# scylla home dir
SCYLLA_HOME=/var/lib/scylla

# scylla config dir
SCYLLA_CONF=/etc/scylla

# scylla arguments (for posix mode)
SCYLLA_ARGS="--log-to-syslog 1 --log-to-stdout 0 --default-log-level info --collectd-address=(mornitoringIP):25826 --collectd=1 --collectd-poll-period 3000 --network-stack posix --smp 8 -m 32G"

## scylla arguments (for dpdk mode)
#SCYLLA_ARGS="--log-to-syslog 1 --log-to-stdout 0 --default-log-level info --collectd-address=127.0.0.1:25826 --collectd=1 --collectd-poll-period 3000 --network-stack native --dpdk-pmd"

# setup as AMI instance
AMI=no
)

disk io/s using iostat was average 30mb read/s and 150mb write/s per node. => we got `iostat 1` command and  cpu load information was tessera load percent.

**Comment by dorlaor** [comment] 2016-09-23 06:24
Can you please send the output of all the metrics in https://github.com/scylladb/scylla/wiki/How-to-report-a-Scylla-performance-problem
Especially the iostat output, the perf record for _each_ of the cores which run scylla (please install the debug symbol rpms before). The best is to send the output of sudo ./collect-runtime-info.sh

Lastly, do you run anything else in the other cores? What's the iotune output?

**Comment by dorlaor** [comment] 2017-06-20 21:50
We're at 1.7 now, closing

**Closed by dorlaor** 2017-06-20 21:50 UTC
Labels: User Request
