### ISSUE TITLE
perf_fast_forward: Populating small_part with 1000000 partitions fails

### ISSUE THREAD

**Issue by bentsi** [scylladb/scylla#3558] opened 2018-06-28 13:22 UTC
Version: e1efda8b0c10aa71a425e1854e1e8e3d5f0f1efe (master build)
```
[scylla-build] $ /bin/sh -xe /tmp/jenkins1756393386356491725.sh
+ rm -rf perf_fast_forward_output
+ build/release/tests/perf/perf_fast_forward --populate
Reactor stalled for 2380 ms on shard 3.
Reactor stalled for 2380 ms on shard 3.
Backtrace:
  0x0000000000624862
  0x00000000005446ac
  0x0000000000544b66
  /lib64/libpthread.so.0+0x00000000000121af
  0x0000000000520fbf
  /lib64/libpthread.so.0+0x00000000000121af
  0x0000000001141d43
  0x0000000000ff299f
  0x00000000010fb500
  0x00000000010e56cf
  0x00000000010e707a
  0x00000000010e900f
  0x0000000000ed5915
  0x0000000000d5f42c
  0x0000000000d60074
  0x0000000000dc665d
  0x0000000000dc8229
  0x0000000000f127f7
  0x0000000000f128ce
  0x0000000000688a1c
  0x0000000000525a86
  0x0000000000525c41
  0x00000000005f0ad7
  0x0000000000612c22
  0x00000000006ce51d
  /lib64/libpthread.so.0+0x000000000000750a
  /lib64/libc.so.6+0x00000000000f516e
WARN  2018-06-28 03:07:27,395 [shard 0] seastar - Unable to set SCHED_FIFO scheduling policy for timer thread; latency impact possible. Try adding CAP_SYS_NICE
Data directory: {./perf_large_partition_data}
Dropping keyspace...
Saving test config...
Creating test tables...
Populating ks.test with 1000000 rows...flushing...
compacting...
Populating small_part with 1000000 partitions...ERROR 2018-06-28 03:08:14,855 [shard 0] seastar - Exiting on unhandled exception: exceptions::mutation_write_timeout_exception (Operation timed out for ks.small_part - received only 0 responses from 1 CL=ONE.)
Build step 'Execute shell' marked build as failure
```
http://jenkins.cloudius-systems.com:8080/job/scylla-master-build/compiler=g++,label=scylla-build/847/console

**Comment by tgrabiec** [comment] 2018-06-29 09:13
Probably duplicate of https://github.com/scylladb/scylla/issues/2127

**Closed by tgrabiec** 2018-06-29 09:13 UTC

**Comment by avikivity** [comment] 2018-07-01 13:21
You can use `--unsafe-bypass-fsync` on consumer disks for testing purposes.
