### ISSUE TITLE
get_random_number should not return std::numeric_limits<int64_t>::min()

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#6270] opened 2020-04-22 15:19 UTC
Extracted from https://github.com/scylladb/scylla/issues/6193#issuecomment-616058815
and https://github.com/scylladb/scylla/issues/6193#issuecomment-616228534
Following c563234f407acefaef3684efe54c1f89bfc35a50

@espindola:
> @avikivity:
> > @haaawk the problem is not `signed long long`, it's the constructor. get_random_number uses the default constructor, which constructs from 0 to numeric_limits::max(). So we lost all the negative numbers.
> > Note that get_random_token() has a bug - it can generate std::numeric_limits<int64_t>::min(), which is not a legal token. Please fix.
> 
> We are now calling normalize which maps min to max. Since we are using uniform_int_distribution int distribution it would probably be better to exclude min directly, no?

**Comment by espindola** [comment] 2020-04-22 17:44
Fixed by @haaawk in 2aaf81bf7c288eb1292a9c06b3d7a122e7ab4f06, no?

**Comment by haaawk** [comment] 2020-04-22 17:48
Yes

**Comment by haaawk** [comment] 2020-04-22 17:49
@bhalevy I think we can close this.

**Comment by haaawk** [comment] 2020-04-23 10:12
Duplicate of already closed issue https://github.com/scylladb/scylla/issues/6237

**Closed by haaawk** 2020-04-23 10:12 UTC
