### ISSUE TITLE
c-s fail to write data to nodes when the seed is removed

### ISSUE THREAD

**Issue by amoskong** [scylladb/scylla#2090] opened 2017-02-17 10:01 UTC
*Installation details*
Scylla version (or git commit hash): scylla-1.6.0-20170202.7e1b245.el7.centos.x86_64
Cluster size: 6
OS (RHEL/CentOS/Ubuntu/AWS AMI): centos7

*Description:*

1. Create a cluster with 6 db nodes, set the first node as seed.
2. start c-stress loader
/usr/bin/cassandra-stress write cl=QUORUM duration=100m -schema keyspace=keyspace1 "replication(factor=3)" -port jmx=6868 -mode cql3 native -rate threads=1000 -pop seq=1..10000000 -node $seed_ip
3. wait for some times (10 mins, 1 hour)
4. try to remove seed node
5. check `nodetool status` in other nodes 
6. check c-s cmdline output
7. check scyllatop in other nodes

Expected Result:
c-s can still write to existed non-seed nodes after the seed is removed. c-s client has ips of all nodes in cluster.

In my [longevity-gce test](http://jenkins.cloudius-systems.com/job/scylla-1.6-longevity-gce/label=gce/63/console), seed node is removed, and there are some breaking testing after that.

```
[scylla-test@longevity-1-6-gce-scylla-db-node-56c8b40b-000 ~]$ nodetool status
Datacenter: datacenter1
=======================
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address      Load       Tokens  Owns    Host ID                               Rack
UN  10.240.0.17  2.43 GB    256     ?       a13547bd-07b9-40c8-b742-c86421077517  rack1
UN  10.240.0.18  1.91 GB    256     ?       ef61b1e7-9223-4d77-b7c4-cb1245b6e891  rack1
UN  10.240.0.19  1.32 GB    256     ?       3f2f8f75-38ca-4963-b289-b956488e09b7  rack1
UN  10.240.0.36  4.23 GB    256     ?       c9c99661-30a3-4b89-9e45-db731ab8056e  rack1
UN  10.240.0.37  4.71 GB    256     ?       d079abde-a6b0-44f0-93b3-5a3b03442392  rack1
UN  10.240.0.30  4.41 GB    256     ?       018f761e-39be-4ba0-9c83-1aec59d1b5ee  rack1
```

There is no `Served Requests` in grafana monitor (checking attached grafana snapshot). I tried to re-run a c-s cmdline with an existed node ip, we can still see some `Served Requests`.

![fireshot capture 102 - grafana - scylla per server metrics 1_ - http___35 185 9 191_3000_dashboard](https://cloud.githubusercontent.com/assets/309708/23060938/7044c740-f4c5-11e6-9b13-155e259a4d79.png)

```
/usr/bin/cassandra-stress write cl=QUORUM duration=100m -schema keyspace=keyspace1 "replication(factor=3)" -port jmx=6868 -mode cql3 native -rate threads=1000 -pop seq=1..10000000 -node 10.240.0.30
```

Original seed ip is `10.240.0.29`

**Comment by slivne** [comment] 2017-02-19 09:45
Ok its a good thing to know - yet for the longevity run - lets make sure we do not remove the seed and leave it running all the time - once the seed is removed it requires updating all the cluster configuration and making another node a seed - lets not handle this now (+ the fact that we have a node running all the time is a good thing to find issues of a long running node - while others are restarted).

**Comment by slivne** [comment] 2017-05-28 13:16
@amoskong I was not able to reproduce this with ccm - are you able to reproduce this on a small system ? if so can you provide the instructions

**Comment by slivne** [comment] 2017-12-03 11:41
@amoskong ping

**Comment by amoskong** [comment] 2017-12-04 08:28
I will test with latest release and update result to here.
BTW, this scenario wasn't covered by SCT longevity, we never remove seed node during the test.

**Comment by amoskong** [comment] 2017-12-04 11:37
The problem can't be reproduced on `2.1.rc0-0.20171203.370a648`

- config: 3 db nodes (`n1-highmem-16`), 1 loader(`n1-standard-4`)
- cassandra-stress cmdline: `cassandra-stress write cl=QUORUM n=100000000 -schema keyspace=keyspace1 'replication(factor=3) compaction(strategy=SizeTieredCompactionStrategy)' -port jmx=6868 -mode cql3 native -rate threads=500 -pop seq=1..100000000 -node 10.240.0.101`

Steps:
- start cluster with 3 db nodes
- run c-s load
- kill scylla process in seed node

Result (2.1.rc0-0.20171203.370a648): c-s process works well, the load is distributed to other two nodes.

![image](https://user-images.githubusercontent.com/309708/33550482-15a9977c-d929-11e7-9efc-5782958a3fc5.png)

**Comment by amoskong** [comment] 2017-12-04 14:06
But I can reproduce the issue with large cluster (more workload).

2.1.rc0-0.20171203.370a648
config: 6 db nodes (`n1-highmem-16`), 3 loader(`n1-standard-4`)

![image](https://user-images.githubusercontent.com/309708/33556341-8691f488-d93e-11e7-884e-3f006735ca2e.png)

```
2017-12-04 13:47:11,281 remote           L0197 DEBUG| [35.196.71.181] [stdout] total,      47054284,   30125,   30125,   30125,     0.6,
     0.6,     1.1,     1.5,     5.3,    13.8, 2161.7,  0.01343,      0,      0,       0,       0,       0,       0
2017-12-04 13:47:12,445 remote           L0197 DEBUG| [35.227.111.53] [stdout] total,      36336773,   29198,   29198,   29198,     0.7,
     0.6,     1.1,     1.5,     4.3,    12.3, 1800.3,  0.02299,      0,      0,       0,       0,       0,       0
2017-12-04 13:47:12,710 remote           L0197 DEBUG| [35.227.57.244] [stdout] total,      37299321,   29431,   29431,   29431,     0.7,
     0.6,     1.1,     1.6,     6.4,    13.1, 1980.8,  0.02211,      0,      0,       0,       0,       0,       0
2017-12-04 13:47:21,474 remote           L0197 DEBUG| [35.227.111.53] [stdout] com.datastax.driver.core.exceptions.ReadTimeoutException:
 Cassandra timeout during read query at consistency LOCAL_ONE (1 responses were required but only 0 replica responded)
2017-12-04 13:47:21,474 remote           L0197 DEBUG| [35.227.57.244] [stdout] com.datastax.driver.core.exceptions.ReadTimeoutException:
 Cassandra timeout during read query at consistency LOCAL_ONE (1 responses were required but only 0 replica responded)
2017-12-04 13:47:21,475 remote           L0197 DEBUG| [35.196.71.181] [stdout] com.datastax.driver.core.exceptions.ReadTimeoutException:
 Cassandra timeout during read query at consistency LOCAL_ONE (1 responses were required but only 0 replica responded)
...
2017-12-04 13:47:41,490 remote           L0197 DEBUG| [35.196.71.181] [stdout] java.io.IOException: Operation x10 on key(s) [3339304e364e31363630]: Error executing: (UnavailableException): Not enough replicas available for query at consistency LOCAL_ONE (1 required but only 0 alive)
2017-12-04 13:47:41,491 remote           L0197 DEBUG| [35.196.71.181] [stdout] 
2017-12-04 13:47:41,491 remote           L0197 DEBUG| [35.196.71.181] [stdout]  at org.apache.cassandra.stress.Operation.error(Operation.java:135)
2017-12-04 13:47:41,492 remote           L0197 DEBUG| [35.196.71.181] [stdout]  at org.apache.cassandra.stress.Operation.timeWithRetry(Operation.java:113)

2017-12-04 13:47:41,650 remote           L0197 DEBUG| [35.196.71.181] [stdout] java.io.IOException: Operation x10 on key(s) [394e4f304f3136384d30]: Error executing: (UnavailableException): Not enough replicas available for query at consistency LOCAL_ONE (1 required but only 0 alive)
2017-12-04 13:47:41,650 remote           L0197 DEBUG| [35.196.71.181] [stdout] 
2017-12-04 13:47:41,650 remote           L0197 DEBUG| [35.196.71.181] [stdout]  at org.apache.cassandra.stress.Operation.error(Operation.java:135)
2017-12-04 13:47:41,650 remote           L0197 DEBUG| [35.196.71.181] [stdout]  at org.apache.cassandra.stress.Operation.timeWithRetry(Operation.java:113)
2017-12-04 13:47:41,654 remote           L0197 DEBUG| [35.196.71.181] [stdout]  at org.apache.cassandra.stress.operations.predefined.CqlOperation.run(CqlOperation.java:98)
2017-12-04 13:47:41,655 remote           L0197 DEBUG| [35.196.71.181] [stdout]  at org.apache.cassandra.stress.operations.predefined.CqlOperation.run(CqlOperation.java:106)
2017-12-04 13:47:41,655 remote           L0197 DEBUG| [35.196.71.181] [stdout]  at org.apache.cassandra.stress.operations.predefined.CqlOperation.run(CqlOperation.java:261)
2017-12-04 13:47:41,655 remote           L0197 DEBUG| [35.196.71.181] [stdout]  at org.apache.cassandra.stress.StressAction$Consumer.run(StressAction.java:321)
2017-12-04 13:47:41,655 remote           L0197 DEBUG| [35.196.71.181] [stdout] com.datastax.driver.core.exceptions.UnavailableException: Not enough replicas available for query at consistency LOCAL_ONE (1 required but only 0 alive)
...
```

**Comment by asias** [comment] 2018-02-05 07:14
@amoskong how did you remove the seed node, decommission?

I saw the graph in the "config: 6 db nodes (n1-highmem-16), 3 loader(n1-standard-4)" comments, Requests served/second get recovered some time later. Did it get recovered automatically?

**Comment by amoskong** [comment] 2018-02-05 07:25
On Mon, Feb 5, 2018 at 3:14 PM, Asias He <notifications@github.com> wrote:

> @amoskong <https://github.com/amoskong> how did you remove the seed node,
> decommission?
>

@asias In regular decommission, we only remove non-seed node. I touched
this problem when sct wrongly removed seed node.


> I saw the graph in the "config: 6 db nodes (n1-highmem-16), 3
> loader(n1-standard-4)" comments, Requests served/second get recovered some
> time later. Did it get recovered automatically?
>

Not really get recovered.

**Comment by tzach** [comment] 2018-09-13 09:58
@amoskong can we create dtest to reproduce?

**Comment by amoskong** [comment] 2018-09-13 11:11
@tzach I will try and update result to you.

**Comment by slivne** [comment] 2019-02-12 11:19
@amoskong do you have a simpler reproducer

We did change in 3.1 the way we drain a node - so that may have helped here as well.

Lets try to rerun this with 3.1 and see if it fails - we need to clear this as its an issue customers may face.

**Comment by slivne** [comment] 2019-03-26 09:31
@amoskong / @roydahan ping .. lets retest with 3.1 and see if this still exists or not

**Comment by amoskong** [comment] 2019-03-28 15:14
I will try to reproduce with a simple dtest or sct

**Comment by amoskong** [comment] 2019-04-04 05:11
I didn't reproduce this issue with 3.0.4-0.20190322.27cf758f1 by a dtest.

[reproduce_issue_2090.py.txt](https://github.com/scylladb/scylla/files/3041853/reproduce_issue_2090.py.txt)

I will send a PR to dtest.

**Comment by slivne** [comment] 2019-04-16 07:40
@amoskong just so its clear previously you reproduced this with SCT - are we running those tests in SCT now ?

**Comment by slivne** [comment] 2019-04-16 07:42
Alternatively we can try to run this dtest on the old version that had the bug and see if it reproduces ... (trying to be a bit more sure we are not seeping this under the rug) ....

Just to be clear: If the answer is yes in SCT we are running the test and not seeing it - its good enough and we can close this and reopen if we do hit it again.

**Comment by amoskong** [comment] 2019-04-16 07:55
We didn't run test in SCT. I will try to reproduce with old (even it didn't
occur all the time) with dtest.
And retest latest 3.1

**Comment by amoskong** [comment] 2019-04-17 06:07
I found a way to reproduce this problem, by referenced https://github.com/scylladb/scylla/issues/2090#issuecomment-348937534

Just replace decommission in scenario with killing scylla process on of seed nodes un-gracefully.

```
node1.stop(gently=False)
```

Results:
- scylla-1.6.0-20170202.7e1b245.el7.centos.x86_64.rpm
  - `FAIL`: can be reproduced 100%, [c-s output details](https://gist.github.com/amoskong/f46102d92aba686237b48947d5727db0)
- 3.0.5-0.20190414.403f66eca
  - `PASS`: can't reproduce, c-s works well when seed process is killed.

**Comment by asias** [comment] 2019-04-17 06:20
> I found a way to reproduce this problem, by referenced [#2090 (comment)](https://github.com/scylladb/scylla/issues/2090#issuecomment-348937534)
> 
> Just replace decommission in scenario with killing scylla process on of seed nodes un-gracefully.
> 
> ```
> node1.stop(gently=False)
> ```

So, you can reproduce using dtest (https://github.com/scylladb/scylla-dtest/pull/932) on scylla1.6 but can not reproduce on scylla 3.0.5, correct?


> 
> Results:
> 
>     * scylla-1.6.0-20170202.7e1b245.el7.centos.x86_64.rpm
>       
>       * `FAIL`: can be reproduced 100%, [c-s output details](https://gist.github.com/amoskong/f46102d92aba686237b48947d5727db0)
> 
>     * 3.0.5-0.20190414.403f66eca
>       
>       * `PASS`: can't reproduce, c-s works well when seed process is killed.

**Comment by amoskong** [comment] 2019-04-17 06:40
On Wed, Apr 17, 2019 at 2:20 PM Asias He <notifications@github.com> wrote:

> I found a way to reproduce this problem, by referenced #2090 (comment)
> <https://github.com/scylladb/scylla/issues/2090#issuecomment-348937534>
>
> Just replace decommission in scenario with killing scylla process on of
> seed nodes un-gracefully.
>
> node1.stop(gently=False)
>
> So, you can reproduce using dtest (scylladb/scylla-dtest#932
> <https://github.com/scylladb/scylla-dtest/pull/932>) on scylla1.6 but can
> not reproduce on scylla 3.0.5, correct?
>
Yes.

**Comment by asias** [comment] 2019-04-17 06:43
Thanks. @slivne I think we can close this issue now. We have a reproducer and it does not reproduce now.

**Closed** 2019-06-18 10:33 UTC
