### ISSUE TITLE
REST API /ui/ transfer closed with outstanding read data remaining

### ISSUE THREAD

**Issue by zwopir** [scylladb/scylla#4227] opened 2019-02-14 11:27 UTC
- [x] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash): 3.03
Cluster size: 3
OS (RHEL/CentOS/Ubuntu/AWS AMI): ubunut 18.4

When I do a `curl -v "http://localhost:10000/ui/"` the httpd seastar responds with
```
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 10000 (#0)
> GET /ui/ HTTP/1.1
> Host: localhost:10000
> User-Agent: curl/7.58.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Transfer-Encoding: chunked
< Content-Type: text/html
< Server: Seastar httpd
< Date: 14 Feb 2019 11:19:49 GMT
< 
* transfer closed with outstanding read data remaining
* stopped the pause stream!
* Closing connection 0
curl: (18) transfer closed with outstanding read data remaining
```

works on scylla 3.0.2, but not on 3.0.3. . Calling the rest routes works on both versions

Any help is very much appreciated, let me know if you need further information about the setup.

**Comment by tzach** [comment] 2019-02-14 13:47
I fail to reproduce with docker:
```
docker run --name some-scylla-3.0.2 -d scylladb/scylla:3.0.2 --smp 1 --memory 1G --overprovisioned 1
docker run --name some-scylla-3.0.3 -d scylladb/scylla:3.0.3 --smp 1 --memory 1G --overprovisioned 1
docker exec -it some-scylla-3.0.2 curl -v "http://localhost:10000/ui/"
docker exec -it some-scylla-3.0.3 curl -v "http://localhost:10000/ui/"
```
Both curls works:
```
< Transfer-Encoding: chunked
< Content-Type: text/html
< Server: Seastar httpd
< Date: 14 Feb 2019 13:46:36 GMT
< 
<!DOCTYPE html>
               <html>
                     <head>
                             <title>Swagger UI</title>
...
```

**Comment by zwopir** [comment] 2019-02-14 14:13
I'll investigate on this and let you know if I find anything useful to you

**Comment by slivne** [comment] 2019-02-21 10:50
@zwopir any update ... 

closing this issue - if you have an update please post and we can reopen

**Closed by slivne** 2019-02-21 10:50 UTC

**Comment by alienth** [comment] 2019-11-06 07:02
I hit this myself and found the root cause:

I removed everything in `scylla.yaml` from the `Not currently supported, reserved for future use` section. It turns out that something is appending the swagger UI settings at the end of the file. If you remove those settings, this curl error will reproduce.

Might be helpful to fail more gracefully in this scenario, and perhaps get those config items inserted elsewhere in `scylla.yaml`?
