### ISSUE TITLE
oversized allocation warning from storage_proxy::query_partition_key_range

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#4180] opened 2019-02-03 10:11 UTC
Scylla version 4537ec7426b3fe13d94f59b8c3dabd4f2179ea58

Seen in [update_cluster_layout_tests.TestLargeScaleCluster.add_50_nodes_test/node32.log #1005](http://jenkins.cloudius-systems.com:8080/job/scylla-master/job/dtest/label=scylla-dtest,mode=release,smp=2/1005/artifact/urchin-dtest/logs-release.2/1547865657196_update_cluster_layout_tests.TestLargeScaleCluster.add_50_nodes_test/node32.log):
```
WARN  2019-01-19 04:40:49,218 [shard 0] seastar_memory - oversized allocation: 1638400 bytes, please report: at   0x7e6178

$ ~/dev/scylla/seastar/scripts/seastar-addr2line -e 1005-release/scylla 
  0x777533
  0x77cd36
  0x77d284
  0x221600c
  0x20ed1a7
  0x217779a
  0x21dff7e
  0x21e3116
  0x1cc9ced
  0x1ccc8e1
  0x1cea45e
  0x1cea4bc
  0x1d0f95b
  0x7376bc
  0x5bd04e
  0x5bd211
  0x68eef7
  0x7cafd7
  0x54ff1e
  /lib64/libc.so.6+0x20f29
  0x5b73f9

[Backtrace #0]
seastar::memory::cpu_pages::warn_large_allocation(unsigned long) at /jenkins/workspace/scylla-master/dtest/label/scylla-dtest/mode/release/smp/2/scylla/seastar/src/core/memory.cc:609
seastar::memory::allocate(unsigned long) at /jenkins/workspace/scylla-master/dtest/label/scylla-dtest/mode/release/smp/2/scylla/seastar/src/core/memory.cc:617
 (inlined by) ?? at /jenkins/workspace/scylla-master/dtest/label/scylla-dtest/mode/release/smp/2/scylla/seastar/src/core/memory.cc:623
 (inlined by) ?? at /jenkins/workspace/scylla-master/dtest/label/scylla-dtest/mode/release/smp/2/scylla/seastar/src/core/memory.cc:1194
 (inlined by) seastar::memory::allocate(unsigned long) at /jenkins/workspace/scylla-master/dtest/label/scylla-dtest/mode/release/smp/2/scylla/seastar/src/core/memory.cc:1244
operator new(unsigned long) at /jenkins/workspace/scylla-master/dtest/label/scylla-dtest/mode/release/smp/2/scylla/seastar/src/core/memory.cc:1647
nonwrapping_range<dht::ring_position>& std::vector<nonwrapping_range<dht::ring_position>, std::allocator<nonwrapping_range<dht::ring_position> > >::emplace_back<nonwrapping_range<dht::ring_position> >(nonwrapping_range<dht::ring_position>&&) at /usr/include/c++/7/ext/new_allocator.h:111
 (inlined by) ?? at /usr/include/c++/7/bits/alloc_traits.h:436
 (inlined by) ?? at /usr/include/c++/7/bits/stl_vector.h:172
 (inlined by) ?? at /usr/include/c++/7/bits/vector.tcc:406
 (inlined by) nonwrapping_range<dht::ring_position>& std::vector<nonwrapping_range<dht::ring_position>, std::allocator<nonwrapping_range<dht::ring_position> > >::emplace_back<nonwrapping_range<dht::ring_position> >(nonwrapping_range<dht::ring_position>&&) at /usr/include/c++/7/bits/vector.tcc:105
operator() at /jenkins/workspace/scylla-master/dtest/label/scylla-dtest/mode/release/smp/2/scylla/service/storage_proxy.cc:3399
 (inlined by) service::get_restricted_ranges(locator::token_metadata&, schema const&, nonwrapping_range<dht::ring_position>) at /jenkins/workspace/scylla-master/dtest/label/scylla-dtest/mode/release/smp/2/scylla/service/storage_proxy.cc:3437
service::storage_proxy::query_partition_key_range(seastar::lw_shared_ptr<query::read_command>, std::vector<nonwrapping_range<dht::ring_position>, std::allocator<nonwrapping_range<dht::ring_position> > >, db::consistency_level, service::storage_proxy::coordinator_query_options) at /jenkins/workspace/scylla-master/dtest/label/scylla-dtest/mode/release/smp/2/scylla/service/storage_proxy.cc:3381
 (inlined by) service::storage_proxy::query_partition_key_range(seastar::lw_shared_ptr<query::read_command>, std::vector<nonwrapping_range<dht::ring_position>, std::allocator<nonwrapping_range<dht::ring_position> > >, db::consistency_level, service::storage_proxy::coordinator_query_options) at /jenkins/workspace/scylla-master/dtest/label/scylla-dtest/mode/release/smp/2/scylla/service/storage_proxy.cc:3140
service::storage_proxy::do_query(seastar::lw_shared_ptr<schema const>, seastar::lw_shared_ptr<query::read_command>, std::vector<nonwrapping_range<dht::ring_position>, std::allocator<nonwrapping_range<dht::ring_position> > >&&, db::consistency_level, service::storage_proxy::coordinator_query_options) at /jenkins/workspace/scylla-master/dtest/label/scylla-dtest/mode/release/smp/2/scylla/service/storage_proxy.cc:3266
service::storage_proxy::query(seastar::lw_shared_ptr<schema const>, seastar::lw_shared_ptr<query::read_command>, std::vector<nonwrapping_range<dht::ring_position>, std::allocator<nonwrapping_range<dht::ring_position> > >&&, db::consistency_level, service::storage_proxy::coordinator_query_options) at /jenkins/workspace/scylla-master/dtest/label/scylla-dtest/mode/release/smp/2/scylla/service/storage_proxy.cc:3226
cql3::statements::select_statement::execute(service::storage_proxy&, seastar::lw_shared_ptr<query::read_command>, std::vector<nonwrapping_range<dht::ring_position>, std::allocator<nonwrapping_range<dht::ring_position> > >&&, service::query_state&, cql3::query_options const&, std::chrono::time_point<gc_clock, std::chrono::duration<int, std::ratio<1l, 1l> > >) at /jenkins/workspace/scylla-master/dtest/label/scylla-dtest/mode/release/smp/2/scylla/cql3/statements/select_statement.cc:602
cql3::statements::select_statement::do_execute(service::storage_proxy&, service::query_state&, cql3::query_options const&) at /jenkins/workspace/scylla-master/dtest/label/scylla-dtest/mode/release/smp/2/scylla/cql3/statements/select_statement.cc:320
seastar::noncopyable_function<seastar::future<seastar::shared_ptr<cql_transport::messages::result_message> > (cql3::statements::select_statement*, service::storage_proxy&, service::query_state&, cql3::query_options const&)>::direct_vtable_for<std::_Mem_fn<seastar::future<seastar::shared_ptr<cql_transport::messages::result_message> > (cql3::statements::select_statement::*)(service::storage_proxy&, service::query_state&, cql3::query_options const&)> >::call(seastar::noncopyable_function<seastar::future<seastar::shared_ptr<cql_transport::messages::result_message> > (cql3::statements::select_statement*, service::storage_proxy&, service::query_state&, cql3::query_options const&)> const*, cql3::statements::select_statement*, service::storage_proxy&, service::query_state&, cql3::query_options const&) at /usr/include/c++/7/bits/invoke.h:73
 (inlined by) ?? at /usr/include/c++/7/bits/invoke.h:96
 (inlined by) ?? at /usr/include/c++/7/functional:175
 (inlined by) seastar::noncopyable_function<seastar::future<seastar::shared_ptr<cql_transport::messages::result_message> > (cql3::statements::select_statement*, service::storage_proxy&, service::query_state&, cql3::query_options const&)>::direct_vtable_for<std::_Mem_fn<seastar::future<seastar::shared_ptr<cql_transport::messages::result_message> > (cql3::statements::select_statement::*)(service::storage_proxy&, service::query_state&, cql3::query_options const&)> >::call(seastar::noncopyable_function<seastar::future<seastar::shared_ptr<cql_transport::messages::result_message> > (cql3::statements::select_statement*, service::storage_proxy&, service::query_state&, cql3::query_options const&)> const*, cql3::statements::select_statement*, service::storage_proxy&, service::query_state&, cql3::query_options const&) at /jenkins/workspace/scylla-master/dtest/label/scylla-dtest/mode/release/smp/2/scylla/seastar/include/seastar/util/noncopyable_function.hh:71
seastar::noncopyable_function<seastar::future<seastar::shared_ptr<cql_transport::messages::result_message> > (cql3::statements::select_statement*, service::storage_proxy&, service::query_state&, cql3::query_options const&)>::direct_vtable_for<seastar::inheriting_concrete_execution_stage<seastar::future<seastar::shared_ptr<cql_transport::messages::result_message> >, cql3::statements::select_statement*, service::storage_proxy&, service::query_state&, cql3::query_options const&>::make_stage_for_group(seastar::scheduling_group)::{lambda(cql3::statements::select_statement*, service::storage_proxy&, service::query_state&, cql3::query_options const&)#1}>::call(seastar::noncopyable_function<seastar::future<seastar::shared_ptr<cql_transport::messages::result_message> > (cql3::statements::select_statement*, service::storage_proxy&, service::query_state&, cql3::query_options const&)> const*, cql3::statements::select_statement*, service::storage_proxy&, service::query_state&, cql3::query_options const&) at /jenkins/workspace/scylla-master/dtest/label/scylla-dtest/mode/release/smp/2/scylla/seastar/include/seastar/util/noncopyable_function.hh:145
 (inlined by) seastar::inheriting_concrete_execution_stage<seastar::future<seastar::shared_ptr<cql_transport::messages::result_message> >, cql3::statements::select_statement*, service::storage_proxy&, service::query_state&, cql3::query_options const&>::make_stage_for_group(seastar::scheduling_group)::{lambda(cql3::statements::select_statement*, service::storage_proxy&, service::query_state&, cql3::query_options const&)#1}::operator()(cql3::statements::select_statement*, service::storage_proxy&, service::query_state&, cql3::query_options const&) const at /jenkins/workspace/scylla-master/dtest/label/scylla-dtest/mode/release/smp/2/scylla/seastar/include/seastar/core/execution_stage.hh:323
 (inlined by) seastar::noncopyable_function<seastar::future<seastar::shared_ptr<cql_transport::messages::result_message> > (cql3::statements::select_statement*, service::storage_proxy&, service::query_state&, cql3::query_options const&)>::direct_vtable_for<seastar::inheriting_concrete_execution_stage<seastar::future<seastar::shared_ptr<cql_transport::messages::result_message> >, cql3::statements::select_statement*, service::storage_proxy&, service::query_state&, cql3::query_options const&>::make_stage_for_group(seastar::scheduling_group)::{lambda(cql3::statements::select_statement*, service::storage_proxy&, service::query_state&, cql3::query_options const&)#1}>::call(seastar::noncopyable_function<seastar::future<seastar::shared_ptr<cql_transport::messages::result_message> > (cql3::statements::select_statement*, service::storage_proxy&, service::query_state&, cql3::query_options const&)> const*, cql3::statements::select_statement*, service::storage_proxy&, service::query_state&, cql3::query_options const&) at /jenkins/workspace/scylla-master/dtest/label/scylla-dtest/mode/release/smp/2/scylla/seastar/include/seastar/util/noncopyable_function.hh:71
seastar::concrete_execution_stage<seastar::future<seastar::shared_ptr<cql_transport::messages::result_message> >, cql3::statements::select_statement*, service::storage_proxy&, service::query_state&, cql3::query_options const&>::do_flush() at /jenkins/workspace/scylla-master/dtest/label/scylla-dtest/mode/release/smp/2/scylla/seastar/include/seastar/util/noncopyable_function.hh:145
 (inlined by) ?? at /jenkins/workspace/scylla-master/dtest/label/scylla-dtest/mode/release/smp/2/scylla/seastar/include/seastar/core/apply.hh:35
 (inlined by) ?? at /jenkins/workspace/scylla-master/dtest/label/scylla-dtest/mode/release/smp/2/scylla/seastar/include/seastar/core/apply.hh:43
 (inlined by) ?? at /jenkins/workspace/scylla-master/dtest/label/scylla-dtest/mode/release/smp/2/scylla/seastar/include/seastar/core/future.hh:1389
 (inlined by) seastar::concrete_execution_stage<seastar::future<seastar::shared_ptr<cql_transport::messages::result_message> >, cql3::statements::select_statement*, service::storage_proxy&, service::query_state&, cql3::query_options const&>::do_flush() at /jenkins/workspace/scylla-master/dtest/label/scylla-dtest/mode/release/smp/2/scylla/seastar/include/seastar/core/execution_stage.hh:242
operator() at /jenkins/workspace/scylla-master/dtest/label/scylla-dtest/mode/release/smp/2/scylla/seastar/src/core/execution_stage.cc:140
 (inlined by) run_and_dispose at /jenkins/workspace/scylla-master/dtest/label/scylla-dtest/mode/release/smp/2/scylla/seastar/include/seastar/core/task.hh:48
seastar::reactor::run_tasks(seastar::reactor::task_queue&) at /jenkins/workspace/scylla-master/dtest/label/scylla-dtest/mode/release/smp/2/scylla/seastar/src/core/reactor.cc:2700
seastar::reactor::run_some_tasks() [clone .part.2663] at /jenkins/workspace/scylla-master/dtest/label/scylla-dtest/mode/release/smp/2/scylla/seastar/src/core/reactor.cc:3123
seastar::reactor::run() at /jenkins/workspace/scylla-master/dtest/label/scylla-dtest/mode/release/smp/2/scylla/seastar/include/seastar/util/log.hh:313
 (inlined by) seastar::reactor::run() at /jenkins/workspace/scylla-master/dtest/label/scylla-dtest/mode/release/smp/2/scylla/seastar/src/core/reactor.cc:3270
seastar::app_template::run_deprecated(int, char**, std::function<void ()>&&) at /jenkins/workspace/scylla-master/dtest/label/scylla-dtest/mode/release/smp/2/scylla/seastar/src/core/app-template.cc:185
main at /jenkins/workspace/scylla-master/dtest/label/scylla-dtest/mode/release/smp/2/scylla/main.cc:882
```

**Comment by slivne** [comment] 2019-02-03 11:15
duplicate of https://github.com/scylladb/scylla/issues/3767

**Closed by slivne** 2019-02-03 11:15 UTC
