### ISSUE TITLE
Content manager server not able to connect with scylla

### ISSUE THREAD

**Issue by himanshuk359** [scylladb/scylla#3309] opened 2018-03-22 08:17 UTC
Hi Team,
We are using Scylla 2.1 version ON RHEL 7.4 OS.Our machine running on AWS cloud.We have created a 2 node scylla cluster setup in replacement of Apache Cassandra but when we put the entry of scylla cluster in our content manager server we are getting below error.
Scylla nodetool status:-
root@scylla-db: /: nodetool status
Datacenter: datacenter1
=======================
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
-- Address Load Tokens Owns Host ID Rack
UN 172.28.49.4 826.18 KB 256 ? a71c1e32-92fe-4bc1-b056-aaf7692f1727 rack1
UN 172.28.53.34 1.38 MB 256 ? a8fe1192-6bea-4b9c-92cc-0653f3c2f299 rack1
Note: Non-system keyspaces don't have the same replication settings, effective ownership information is meaningless
Content manager server shiro file entry..We are using adobe CQ for content manager.
cassandraCluster.contactPoints=172.28.53.34,172.28.49.4
cassandraCluster.port=9042
Note :- we tried connection on both port 9160 and 9042 but getting same error.
Caused by: org.apache.shiro.ShiroException: com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: scylla-db-2.eservice.tmobile.com/172.28.49.4 (com.datastax.driver.core.exceptions.InvalidQueryException: unconfigured table schema_keyspaces), scylla-db1.eservice.tmobile.com/172.28.53.34 (com.datastax.driver.core.exceptions.InvalidQueryException: unconfigured table schema_keyspaces))
at com.tmobile.web.platform.common.security.shiro.cassandra.ClusterFactory.init(ClusterFactory.java:100)
at com.tmobile.web.platform.common.security.shiro.cassandra.ClusterFactory.getInstance(ClusterFactory.java:90)
at com.tmobile.web.platform.common.security.shiro.cassandra.ClusterFactory.getInstance(ClusterFactory.java:17)
at org.apache.shiro.config.ReflectionBuilder.resolveReference(ReflectionBuilder.java:241)
at org.apache.shiro.config.ReflectionBuilder.resolveValue(ReflectionBuilder.java:397)
at org.apache.shiro.config.ReflectionBuilder.applyProperty(ReflectionBuilder.java:559)
at org.apache.shiro.config.ReflectionBuilder.applySingleProperty(ReflectionBuilder.java:206)
at org.apache.shiro.config.ReflectionBuilder.applyProperty(ReflectionBuilder.java:167)
at org.apache.shiro.config.ReflectionBuilder.buildObjects(ReflectionBuilder.java:124)
at org.apache.shiro.config.IniSecurityManagerFactory.buildInstances(IniSecurityManagerFactory.java:161)
at org.apache.shiro.config.IniSecurityManagerFactory.createSecurityManager(IniSecurityManagerFactory.java:124)
at org.apache.shiro.config.IniSecurityManagerFactory.createSecurityManager(IniSecurityManagerFactory.java:102)
at org.apache.shiro.config.IniSecurityManagerFactory.createInstance(IniSecurityManagerFactory.java:88)
at org.apache.shiro.config.IniSecurityManagerFactory.createInstance(IniSecurityManagerFactory.java:46)
at org.apache.shiro.config.IniFactorySupport.createInstance(IniFactorySupport.java:123)
at org.apache.shiro.util.AbstractFactory.getInstance(AbstractFactory.java:47)
at org.apache.shiro.web.env.IniWebEnvironment.createWebSecurityManager(IniWebEnvironment.java:203)
at org.apache.shiro.web.env.IniWebEnvironment.configure(IniWebEnvironment.java:99)
at org.apache.shiro.web.env.IniWebEnvironment.init(IniWebEnvironment.java:92)
at org.apache.shiro.util.LifecycleUtils.init(LifecycleUtils.java:45)
at org.apache.shiro.util.LifecycleUtils.init(LifecycleUtils.java:40)
at com.tmobile.web.platform.common.security.shiro.filter.ShiroBootFilter$EnvironmentLoaderExt.createEnvironment(ShiroBootFilter.java:82)
at org.apache.shiro.web.env.EnvironmentLoader.initEnvironment(EnvironmentLoader.java:133)
at com.tmobile.web.platform.common.security.shiro.filter.ShiroBootFilter.init(ShiroBootFilter.java:37)
at org.apache.shiro.web.servlet.AbstractShiroFilter.onFilterConfigSet(AbstractShiroFilter.java:152)
at org.apache.shiro.web.servlet.AbstractFilter.init(AbstractFilter.java:97)
... 17 more
Caused by: com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: scylla-db-2.eservice.tmobile.com/172.28.49.4 (com.datastax.driver.core.exceptions.InvalidQueryException: unconfigured table schema_keyspaces), scylla-db1.eservice.tmobile.com/172.28.53.34 (com.datastax.driver.core.exceptions.InvalidQueryException: unconfigured table schema_keyspaces))
at com.datastax.driver.core.ControlConnection.reconnectInternal(ControlConnection.java:185)
at com.datastax.driver.core.ControlConnection.connect(ControlConnection.java:80)
at com.datastax.driver.core.Cluster$Manager.init(Cluster.java:812)
at com.datastax.driver.core.Cluster$Manager.access$100(Cluster.java:736)
at com.datastax.driver.core.Cluster.<init>(Cluster.java:92)
at com.datastax.driver.core.Cluster$Builder.build(Cluster.java:705)
at com.tmobile.web.platform.common.security.shiro.cassandra.ClusterFactory.createCluster(ClusterFactory.java:121)
at com.tmobile.web.platform.common.security.shiro.cassandra.ClusterFactory.doInit(ClusterFactory.java:107)
at com.tmobile.web.platform.common.security.shiro.cassandra.ClusterFactory.init(ClusterFactory.java:98)
... 42 more
Startup time:57 seconds
http://localhost:4503/
Quickstart started

**Comment by avikivity** [comment] 2018-03-22 14:17
As discussed on slack, the problem is that scylla 2.0 and above requires updated drivers. See Driver Support section in the [release announcement](https://www.scylladb.com/2017/10/06/scylla-release-2-0/). Upgrade your drivers to at least the required version.

Alternatively, you can use Scylla 1.7, but be aware that this version is no longer supported. You can also try scylla enterprise 2017.1, which is compatible with the older drivers.

**Comment by tzach** [comment] 2018-04-08 09:50
@himanshuk359 please let us know if upgrading the driver solved the problem.

**Comment by tzach** [comment] 2018-04-24 10:12
@himanshuk359 any updates?

**Comment by slivne** [comment] 2018-06-28 09:20
closing the issue @himanshuk359 if there is an update we can reopen

**Closed** 2018-06-28 09:20 UTC
