### ISSUE TITLE
Scylla node start throwing 'cql_server - exception while processing connection: std::nested_exception' whenever it is stopped

### ISSUE THREAD

**Issue by dkropachev** [scylladb/scylla#7540] opened 2020-11-03 09:31 UTC
Test-id: 24cda039-7c14-42bd-9b4c-ce5b6a465a91

Somehow node got into state when it is throwing empty exceptions whenever it is stopped (via supervisorctl stop scylla)

Errors:

```
[shard 0] cql_server - exception while processing connection: std::nested_exception
[shard 0] cql_server - exception while processing connection: std::nested_exception
[shard 0] cql_server - exception while processing connection: std::nested_exception
[shard 0] cql_server - exception while processing connection: std::nested_exception

```

*Installation details*
Scylla version (or git commit hash): 4.1.7
Cluster size: 3
OS (RHEL/CentOS/Ubuntu/AWS AMI): Docker

Db-logs:
https://cloudius-jenkins-test.s3.amazonaws.com/24cda039-7c14-42bd-9b4c-ce5b6a465a91/20201101_075458/db-cluster-24cda039.zip

**Comment by kbr-** [comment] 2021-01-04 13:55
@dkropachev do you remember which test this was? The logs seem to be gone already (`sct.py collect-logs` doesn't collect anything)

**Comment by dkropachev** [comment] 2021-01-04 13:58
> @dkropachev do you remember which test this was? The logs seem to be gone already (`sct.py collect-logs` doesn't collect anything)

It is upgrade tests, i'am addressing it here - https://github.com/scylladb/scylla-cluster-tests/pull/3103

**Comment by kbr-** [comment] 2021-01-04 14:02
Are you sure? The logs say that the Scylla version is the same on every restart. Did the test run fail before any upgrade was done?

**Comment by dkropachev** [comment] 2021-01-04 14:21
> Are you sure? The logs say that the Scylla version is the same on every restart. Did the test run fail before any upgrade was done?
> also, the linked pull request is related not related to this issue I think... or maybe it is, I don't understand, I don't see `invalid_request_exception` here in the logs you provided

Sorry I thought you was referring to another issue.

Yea are right, it is not a upgrade test.
By strange reason we see these errors only when scylla is running on kubernetes.
Take a look at any of these - https://jenkins.scylladb.com/view/scylla-operator/job/operator-master/

**Comment by kbr-** [comment] 2021-01-04 14:23
Ok, thanks

**Comment by kbr-** [comment] 2021-01-04 14:31
@fruch I see that SCT ignores this error since recently:
https://github.com/scylladb/scylla-cluster-tests/pull/3040
Did you determine the cause of this error? Why is it being ignored now?

Btw. a "recent" change in seastar improves printing of `nested_exception`, so debugging this issue should be easier if it reproduces on a newer version of Scylla:
```
commit 6dda4dedefa4261ee99af0c49a615a0e38d77175
Author: Avi Kivity <avi@scylladb.com>
Date:   Sat Sep 5 20:37:24 2020 +0300

    future: improved printing of seastar::nested_exception
    
    nested_exception is thrown when a finally clause throws
    after processing an exception from the continuation it
    protects. Since we have two in-flight exceptions, we combine
    them into a nested_exception.
    
    The problem is printing a nested_exception's (with
    operator<<(std::ostream&, std::exception_ptr) gives no indication
    about either of its components, making understanding what happened
    difficult.
    
    Fix this by teaching operator<<() about seastar::nested_exception.
    
    The unit test is adjusted; in order to protect from details
    of how the C++ standard library prints out exceptions, a
    test_exception class is introduced. We use handle_exception()
    instead of handle_exception_type() since we need to capture
    an std::exception_ptr for operator<<.
    Message-Id: <20200905173724.137480-1-avi@scylladb.com>
```

**Comment by fruch** [comment] 2021-01-04 14:50
It's a known issue, a cluster of error happening when client disconnects, I was lowered from error to info, and then filtered, just to have a different on appear

**Comment by kbr-** [comment] 2021-01-11 14:48
I opened a new issue which explains the root cause, closing this one.

**Closed by kbr-** 2021-01-11 14:48 UTC
Labels: bug
