### ISSUE TITLE
storage_proxy - Exception when communicating with ... (sstable inactive read queue overloaded)

### ISSUE THREAD

**Issue by aleksbykov** [scylladb/scylla#4770] opened 2019-07-29 12:51 UTC
Run gemini on AWS.
Next command was used 
` /$HOME/gemini -d --duration 60m --warmup 10m -c 100 -m mixed -f --non-interactive --cql-features normal --max-columns 100 --min-columns 60 --max-clustering-keys 16 --max-partition-keys 8 --max-mutation-retries 5 --max-mutation-retries-backoff 100ms --test-cluster=172.30.0.66 --oracle-cluster=172.30.0.117 --outfile /tmp/gemini-l0-15a17746-fd5a-4058-8d24-460c5bcdfa3c.log --seed 86`

Rerun on rc2. Test failed again. Got next error:
scylla[9964]: [shard 7] storage_proxy - Exception when communicating with 172.30.0.247: std::runtime_error (sstable inactive read queue overloaded)
[shard 9] storage_proxy - Exception when communicating with 172.30.0.247: std::runtime_error (sstable inactive read queue overloaded)

The same gemini command with same seed was run on same cluster configuration:
monitor node link
instances available:

logs for compaction errors are here: https://cloudius-jenkins-test.s3.amazonaws.com/ae637a44-dcbd-42ce-ae38-cf3e32d0e087/2019_07_19_09_37_23/db-cluster-ae637a44.zip

**Comment by denesb** [comment] 2019-07-29 13:44
> Rerun on rc2. Test failed again. Got next error:
> scylla[9964]: [shard 7] storage_proxy - Exception when communicating with 172.30.0.247: std::runtime_error (sstable inactive read queue overloaded)
> [shard 9] storage_proxy - Exception when communicating with 172.30.0.247: std::runtime_error (sstable inactive read queue overloaded)

This error has nothing to do with compaction. This error means the node could not keep up with the amount of read requests and the read concurrency semaphore has such a huge queue that it starts rejecting reads outright. The root cause for this error might be interesting but most likely the node was simply overloaded, in which case this is the desired behaviour.

**Comment by slivne** [comment] 2019-07-29 14:09
The title is incorrect ... 

Its not "compaction_manager - compaction failed: sstables::malformed_sstable_exception" Its "storage_proxy - Exception when communicating with 172.30.0.247: std::runtime_error (sstable inactive read queue overloaded)"

To be clear @aleksbykov - did you hit the "compaction_manager - compaction failed: sstables::malformed_sstable_exception:" in this run on this version or not ?

**Comment by aleksbykov** [comment] 2019-07-31 07:26
@slivne i saw the error for compaction manager in logs, but for latest run, i can't to reproduced it anymore

**Comment by slivne** [comment] 2019-08-08 10:03
when you can reproduce the issue lets capture it and allow analysis - closing the issue 

the ```sstable inactive read queue overloaded``` was explained above

**Closed by slivne** 2019-08-08 10:03 UTC
Labels: gemini
