### ISSUE TITLE
Scylla crash

### ISSUE THREAD

**Issue by alliktm** [scylladb/scylla#7640] opened 2020-11-18 10:21 UTC
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [x] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash): 4.1.6-0.20200831.6d9ff622df
Cluster size: 7
OS (RHEL/CentOS/Ubuntu/AWS AMI): Ubuntu 18.04.5 LTS (GNU/Linux 4.15.0-112-generic x86_64)

We encountered a problem with a crash of one of the nodes in the cluster and an infinite reboot every 2-3 minutes. However, there is no such behavior on other nodes.

```
[Backtrace #0]
void seastar::backtrace<seastar::backtrace_buffer::append_backtrace()::{lambda(seastar::frame)#1}>(seastar::backtrace_buffer::append_backtrace()::{lambda(seastar::frame)#1}&&) at /usr/include/fmt/format.h:1158
seastar::backtrace_buffer::append_backtrace() at /usr/include/fmt/format.h:1158
 (inlined by) print_with_backtrace at ./build/release/seastar/./seastar/src/core/reactor.cc:762
seastar::print_with_backtrace(char const*) at /usr/include/fmt/format.h:1158
sigabrt_action at /usr/include/fmt/format.h:1158
 (inlined by) operator() at ./build/release/seastar/./seastar/src/core/reactor.cc:3455
 (inlined by) _FUN at ./build/release/seastar/./seastar/src/core/reactor.cc:3451
?? ??:0
/opt/scylladb/libreloc/libc.so.6: ELF 64-bit LSB shared object, x86-64, version 1 (GNU/Linux), dynamically linked (uses shared libs), BuildID[sha1]=7cad4f745bde5c52c2da346d8b5e5b57008d896c, for GNU/Linux 3.2.0, stripped
gsignal at ??:?
abort at ??:?
?? ??:0
__assert_fail at ??:?
sstables::index_reader::read_partition_data() at ./sstables/index_reader.hh:663
 (inlined by) sstables::index_reader::advance_to(position_in_partition_view) at ./sstables/index_reader.hh:721
sstables::sstable_mutation_reader<sstables::data_consume_rows_context_m, sstables::mp_row_consumer_m>::advance_context(std::optional<position_in_partition_view>)::{lambda()#2}::operator()() const at ./sstables/partition.cc:367
 (inlined by) seastar::apply_helper<sstables::sstable_mutation_reader<sstables::data_consume_rows_context_m, sstables::mp_row_consumer_m>::advance_context(std::optional<position_in_partition_view>)::{lambda()#2}, std::tuple<>&&, std::integer_sequence<unsigned long> >::apply({lambda()#2}&&, std::tuple<>) at ././seastar/include/seastar/core/apply.hh:36
 (inlined by) auto seastar::apply<sstables::sstable_mutation_reader<sstables::data_consume_rows_context_m, sstables::mp_row_consumer_m>::advance_context(std::optional<position_in_partition_view>)::{lambda()#2}>(sstables::sstable_mutation_reader<sstables::data_consume_rows_context_m, sstables::mp_row_consumer_m>::advance_context(std::optional<position_in_partition_view>)::{lambda()#2}&&, std::tuple<>&&) at ././seastar/include/seastar/core/apply.hh:44
 (inlined by) seastar::future<> seastar::futurize<seastar::future<> >::apply<sstables::sstable_mutation_reader<sstables::data_consume_rows_context_m, sstables::mp_row_consumer_m>::advance_context(std::optional<position_in_partition_view>)::{lambda()#2}>(sstables::sstable_mutation_reader<sstables::data_consume_rows_context_m, sstables::mp_row_consumer_m>::advance_context(std::optional<position_in_partition_view>)::{lambda()#2}&&, std::tuple<>&&) at ././seastar/include/seastar/core/future.hh:1731
 (inlined by) seastar::future<> seastar::future<>::then_impl<sstables::sstable_mutation_reader<sstables::data_consume_rows_context_m, sstables::mp_row_consumer_m>::advance_context(std::optional<position_in_partition_view>)::{lambda()#2}, seastar::future<> >(sstables::sstable_mutation_reader<sstables::data_consume_rows_context_m, sstables::mp_row_consumer_m>::advance_context(std::optional<position_in_partition_view>)::{lambda()#2}&&) at ././seastar/include/seastar/core/future.hh:1277
 (inlined by) seastar::future<> seastar::future<>::then<sstables::sstable_mutation_reader<sstables::data_consume_rows_context_m, sstables::mp_row_consumer_m>::advance_context(std::optional<position_in_partition_view>)::{lambda()#2}, seastar::future<> >(sstables::sstable_mutation_reader<sstables::data_consume_rows_context_m, sstables::mp_row_consumer_m>::advance_context(std::optional<position_in_partition_view>)::{lambda()#2}&&) at ././seastar/include/seastar/core/future.hh:1231
 (inlined by) sstables::sstable_mutation_reader<sstables::data_consume_rows_context_m, sstables::mp_row_consumer_m>::advance_context(std::optional<position_in_partition_view>) at ./sstables/partition.cc:368
sstables::sstable_mutation_reader<sstables::data_consume_rows_context_m, sstables::mp_row_consumer_m>::fill_buffer(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda()#3}::operator()() const::{lambda()#2}::operator()() const at ./sstables/partition.cc:444
seastar::future<> seastar::futurize<seastar::future<> >::invoke<sstables::sstable_mutation_reader<sstables::data_consume_rows_context_m, sstables::mp_row_consumer_m>::fill_buffer(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda()#3}::operator()() const::{lambda()#2}&>(sstables::sstable_mutation_reader<sstables::data_consume_rows_context_m, sstables::mp_row_consumer_m>::fill_buffer(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda()#3}::operator()() const::{lambda()#2}&) at ././sstables/index_entry.hh:457
 (inlined by) auto seastar::futurize_invoke<sstables::sstable_mutation_reader<sstables::data_consume_rows_context_m, sstables::mp_row_consumer_m>::fill_buffer(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda()#3}::operator()() const::{lambda()#2}&>(sstables::sstable_mutation_reader<sstables::data_consume_rows_context_m, sstables::mp_row_consumer_m>::fill_buffer(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda()#3}::operator()() const::{lambda()#2}&) at ././seastar/include/seastar/core/future.hh:1832
 (inlined by) seastar::future<> seastar::do_until<sstables::sstable_mutation_reader<sstables::data_consume_rows_context_m, sstables::mp_row_consumer_m>::fill_buffer(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda()#3}::operator()() const::{lambda()#2}, sstables::sstable_mutation_reader<sstables::data_consume_rows_context_m, sstables::mp_row_consumer_m>::fill_buffer(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda()#3}::operator()() const::{lambda()#1}>(sstables::sstable_mutation_reader<sstables::data_consume_rows_context_m, sstables::mp_row_consumer_m>::fill_buffer(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda()#3}::operator()() const::{lambda()#1}, sstables::sstable_mutation_reader<sstables::data_consume_rows_context_m, sstables::mp_row_consumer_m>::fill_buffer(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda()#3}::operator()() const::{lambda()#2}) at ././seastar/include/seastar/core/future-util.hh:521
 (inlined by) sstables::sstable_mutation_reader<sstables::data_consume_rows_context_m, sstables::mp_row_consumer_m>::fill_buffer(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda()#3}::operator()() const at ./sstables/partition.cc:445
seastar::future<> seastar::futurize<seastar::future<> >::invoke<sstables::sstable_mutation_reader<sstables::data_consume_rows_context_m, sstables::mp_row_consumer_m>::fill_buffer(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda()#3}&>(sstables::sstable_mutation_reader<sstables::data_consume_rows_context_m, sstables::mp_row_consumer_m>::fill_buffer(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda()#3}&) at ././seastar/include/seastar/core/future.hh:1748
 (inlined by) auto seastar::futurize_invoke<sstables::sstable_mutation_reader<sstables::data_consume_rows_context_m, sstables::mp_row_consumer_m>::fill_buffer(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda()#3}&>(sstables::sstable_mutation_reader<sstables::data_consume_rows_context_m, sstables::mp_row_consumer_m>::fill_buffer(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda()#3}&) at ././seastar/include/seastar/core/future.hh:1832
 (inlined by) seastar::future<> seastar::do_until<sstables::sstable_mutation_reader<sstables::data_consume_rows_context_m, sstables::mp_row_consumer_m>::fill_buffer(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda()#3}, sstables::sstable_mutation_reader<sstables::data_consume_rows_context_m, sstables::mp_row_consumer_m>::fill_buffer(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda()#2}>(sstables::sstable_mutation_reader<sstables::data_consume_rows_context_m, sstables::mp_row_consumer_m>::fill_buffer(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda()#2}, sstables::sstable_mutation_reader<sstables::data_consume_rows_context_m, sstables::mp_row_consumer_m>::fill_buffer(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda()#3}) at ././seastar/include/seastar/core/future-util.hh:521
 (inlined by) sstables::sstable_mutation_reader<sstables::data_consume_rows_context_m, sstables::mp_row_consumer_m>::fill_buffer(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >) at ./sstables/partition.cc:447
mutation_reader_merger::operator()(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >) at mutation_reader.cc:?
 (inlined by) mutation_reader_merger::operator()(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >) at ./mutation_reader.cc:453
seastar::future<seastar::bool_class<seastar::stop_iteration_tag> > seastar::futurize<seastar::future<seastar::bool_class<seastar::stop_iteration_tag> > >::invoke<combined_mutation_reader::fill_buffer(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda()#1}&>(combined_mutation_reader::fill_buffer(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda()#1}&) at mutation_reader.cc:?
 (inlined by) mutation_fragment_merger<mutation_reader_merger>::operator()(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >) at ./mutation_reader.cc:121
 (inlined by) operator() at ./mutation_reader.cc:582
 (inlined by) invoke<combined_mutation_reader::fill_buffer(seastar::lowres_clock::time_point)::<lambda()>&> at ././seastar/include/seastar/core/future.hh:1748
combined_mutation_reader::fill_buffer(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >) at mutation_reader.cc:?
 (inlined by) combined_mutation_reader::fill_buffer(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >) at ./mutation_reader.cc:593
void flat_mutation_reader::impl::consume_pausable_in_thread<std::reference_wrapper<flat_mutation_reader::impl::consumer_adapter<db::view::view_updating_consumer> >, flat_mutation_reader::no_filter>(std::reference_wrapper<flat_mutation_reader::impl::consumer_adapter<db::view::view_updating_consumer> >, flat_mutation_reader::no_filter, std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >) at ././seastar/include/seastar/core/future.hh:424
 (inlined by) auto flat_mutation_reader::impl::consume_in_thread<db::view::view_updating_consumer, flat_mutation_reader::no_filter>(db::view::view_updating_consumer, flat_mutation_reader::no_filter, std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >) at ././flat_mutation_reader.hh:280
 (inlined by) auto flat_mutation_reader::consume_in_thread<db::view::view_updating_consumer, flat_mutation_reader::no_filter>(db::view::view_updating_consumer, flat_mutation_reader::no_filter, std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >) at ././flat_mutation_reader.hh:400
 (inlined by) auto flat_mutation_reader::consume_in_thread<db::view::view_updating_consumer>(db::view::view_updating_consumer, std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >) at ././flat_mutation_reader.hh:408
 (inlined by) operator() at ./db/view/view_update_generator.cc:72
apply at ././seastar/include/seastar/core/future.hh:424
 (inlined by) apply<db::view::view_update_generator::start()::<lambda()> > at ././seastar/include/seastar/core/apply.hh:44
 (inlined by) apply<db::view::view_update_generator::start()::<lambda()> > at ././seastar/include/seastar/core/future.hh:1698
 (inlined by) operator() at ././seastar/include/seastar/core/thread.hh:253
 (inlined by) call at ././seastar/include/seastar/util/noncopyable_function.hh:101
seastar::noncopyable_function<void ()>::operator()() const at ./build/release/seastar/./seastar/include/seastar/util/noncopyable_function.hh:184
 (inlined by) seastar::thread_context::main() at ./build/release/seastar/./seastar/src/core/thread.cc:286

```

**Comment by alliktm** [comment] 2020-11-18 10:46
[crash.txt](https://github.com/scylladb/scylla/files/5559456/crash.txt)

**Comment by bhalevy** [comment] 2020-11-18 11:48
According to the backtrace the assert is in `index_reader::read_partition_data()`
https://github.com/scylladb/scylla/blob/6d9ff622dfe1119f0e59bdbd1b909f4952181c37/sstables/index_reader.hh#L663

**Comment by bhalevy** [comment] 2020-11-18 11:54
@alliktm we suspect that this could be caused by a corrupt sstable.
Is it possible for you to upload a coredump?
It will hopefully allow us to determine which sstable was read that hit the assert,
and then if we could get he sstable too, we could analyze it to see whether it's corrupt.

**Comment by alliktm** [comment] 2020-11-18 13:10
I uploaded the coredump. 
report_uuid: dca64fc7-eb01-438e-a6d1-9a2e2f51ef1b

**Comment by Flamefork** [comment] 2020-12-11 06:56
Have to admit, I accidentally deleted corrupted sstables instead of moving them after looking into the coredump. So sadly we won't be able to upload them for debugging. Sorry.

**Comment by denesb** [comment] 2021-01-13 09:58
With reasonable confidence, this is caused by the same bug (missing partition-end fragment) which causes #7623. The consequently missing `consume_end_of_partition()` call in the sstable writer corrupts the index too, causing misinterpreting partition entries as something else. This can cause parsing to be thrown off-track, possibly leading to the crash seen here.
Closing as duplicate.

**Closed by denesb** 2021-01-13 09:58 UTC
Labels: User Request
