### ISSUE TITLE
Segfault in sstables::mx::mx_sstable_mutation_reader::close

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#9385] opened 2021-09-24 15:40 UTC
Seen in https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/938/artifact/logs-all.release.2/1632437579952_compaction_additional_test.CompactionAdditionalTest.refresh_and_restart_after_compaction_strategy_change_test/node1.log

Scylla version f41c1aee6a4353d17d3cb701f05b6debb329d306
```
INFO  2021-09-23 22:37:56,445 [shard 0] compaction - [Compact keyspace1.standard1 e5aee0d0-1cbe-11ec-a374-67cf4a9059a6] Compacting [/jenkins/workspace/scylla-master/dtest-release/scylla/.dtest/dtest-33f9zotq/test/node1/data/keyspace1/standard1-d4ae9d201cbe11eca37467cf4a9059a6/md-16-big-Data.db:level=0:origin=memtable,/jenkins/workspace/scylla-master/dtest-release/scylla/.dtest/dtest-33f9zotq/test/node1/data/keyspace1/standard1-d4ae9d201cbe11eca37467cf4a9059a6/md-14-big-Data.db:level=1:origin=compaction,/jenkins/workspace/scylla-master/dtest-release/scylla/.dtest/dtest-33f9zotq/test/node1/data/keyspace1/standard1-d4ae9d201cbe11eca37467cf4a9059a6/md-12-big-Data.db:level=1:origin=compaction,/jenkins/workspace/scylla-master/dtest-release/scylla/.dtest/dtest-33f9zotq/test/node1/data/keyspace1/standard1-d4ae9d201cbe11eca37467cf4a9059a6/md-10-big-Data.db:level=1:origin=compaction]
Segmentation fault on shard 0.
Backtrace:
  0x3d81f38
  0x3db2a06
  0x4401ad1
  0x7f3a1f85fa1f
  0x186e146
  0x18700cc
  0x15f9373
  0x1574918
  0x1541218
  0x15420ae
  0x15793d0
  0x157853a
  0x1951883
  0x19515b3
  0x4005531
```

```
(gdb) bt
#0  0x000000000186e147 in sstables::mx::mx_sstable_mutation_reader::close (this=0x60000429b000) at sstables/mx/reader.cc:1554
#1  0x00000000018700cd in non-virtual thunk to sstables::mx::mx_sstable_mutation_reader::close() ()
#2  0x00000000015f9374 in flat_mutation_reader_v2::close (this=<optimized out>) at ./flat_mutation_reader_v2.hh:605
#3  downgrade_to_v1(flat_mutation_reader_v2)::transforming_reader::close() (this=<optimized out>) at flat_mutation_reader.cc:1491
#4  0x0000000001574919 in flat_mutation_reader::close (this=<optimized out>) at ./flat_mutation_reader.hh:564
#5  mutation_reader_merger::prepare_one(mutation_reader_merger::reader_and_last_fragment_kind, seastar::bool_class<mutation_reader_merger::reader_galloping_tag>)::$_3::operator()(seastar::optimized_optional<mutation_fragment>) const::{lambda(flat_mutation_reader&)#1}::operator()(flat_mutation_reader&) const (this=<optimized out>, r=...) at mutation_reader.cc:422
#6  seastar::futurize<seastar::future<void> >::invoke<mutation_reader_merger::prepare_one(mutation_reader_merger::reader_and_last_fragment_kind, seastar::bool_class<mutation_reader_merger::reader_galloping_tag>)::$_3::operator()(seastar::optimized_optional<mutation_fragment>) const::{lambda(flat_mutation_reader&)#1}, flat_mutation_reader&>(mutation_reader_merger::prepare_one(mutation_reader_merger::reader_and_last_fragment_kind, seastar::bool_class<mutation_reader_merger::reader_galloping_tag>)::$_3::operator()(seastar::optimized_optional<mutation_fragment>) const::{lambda(flat_mutation_reader&)#1}&&, flat_mutation_reader&) (func=..., args=...) at ./seastar/include/seastar/core/future.hh:2135
#7  seastar::futurize_invoke<mutation_reader_merger::prepare_one(mutation_reader_merger::reader_and_last_fragment_kind, seastar::bool_class<mutation_reader_merger::reader_galloping_tag>)::$_3::operator()(seastar::optimized_optional<mutation_fragment>) const::{lambda(flat_mutation_reader&)#1}, flat_mutation_reader&>(mutation_reader_merger::prepare_one(mutation_reader_merger::reader_and_last_fragment_kind, seastar::bool_class<mutation_reader_merger::reader_galloping_tag>)::$_3::operator()(seastar::optimized_optional<mutation_fragment>) const::{lambda(flat_mutation_reader&)#1}&&, flat_mutation_reader&) (func=..., args=...) at ./seastar/include/seastar/core/future.hh:2166
#8  seastar::parallel_for_each<std::_List_iterator<flat_mutation_reader>, mutation_reader_merger::prepare_one(mutation_reader_merger::reader_and_last_fragment_kind, seastar::bool_class<mutation_reader_merger::reader_galloping_tag>)::$_3::operator()(seastar::optimized_optional<mutation_fragment>) const::{lambda(flat_mutation_reader&)#1}>(std::_List_iterator<flat_mutation_reader>, std::_List_iterator<flat_mutation_reader>, mutation_reader_merger::prepare_one(mutation_reader_merger::reader_and_last_fragment_kind, seastar::bool_class<mutation_reader_merger::reader_galloping_tag>)::$_3::operator()(seastar::optimized_optional<mutation_fragment>) const::{lambda(flat_mutation_reader&)#1}&&) (begin=..., end=..., func=...) at ./seastar/include/seastar/core/loop.hh:554
#9  seastar::internal::parallel_for_each_impl<std::__cxx11::list<flat_mutation_reader, std::allocator<flat_mutation_reader> >&, mutation_reader_merger::prepare_one(mutation_reader_merger::reader_and_last_fragment_kind, seastar::bool_class<mutation_reader_merger::reader_galloping_tag>)::$_3::operator()(seastar::optimized_optional<mutation_fragment>) const::{lambda(flat_mutation_reader&)#1}>(std::__cxx11::list<flat_mutation_reader, std::allocator<flat_mutation_reader> >&, mutation_reader_merger::prepare_one(mutation_reader_merger::reader_and_last_fragment_kind, seastar::bool_class<mutation_reader_merger::reader_galloping_tag>)::$_3::operator()(seastar::optimized_optional<mutation_fragment>) const::{lambda(flat_mutation_reader&)#1}&&) (range=..., func=...) at ./seastar/include/seastar/core/loop.hh:598
#10 seastar::futurize<seastar::future<void> >::invoke<seastar::future<void> (*&)(std::__cxx11::list<flat_mutation_reader, std::allocator<flat_mutation_reader> >&, mutation_reader_merger::prepare_one(mutation_reader_merger::reader_and_last_fragment_kind, seastar::bool_class<mutation_reader_merger::reader_galloping_tag>)::$_3::operator()(seastar::optimized_optional<mutation_fragment>) const::{lambda(flat_mutation_reader&)#1}&&), std::__cxx11::list<flat_mutation_reader, std::allocator<flat_mutation_reader> >&, mutation_reader_merger::prepare_one(mutation_reader_merger::reader_and_last_fragment_kind, seastar::bool_class<mutation_reader_merger::reader_galloping_tag>)::$_3::operator()(seastar::optimized_optional<mutation_fragment>) const::{lambda(flat_mutation_reader&)#1}>(seastar::future<void> (*&)(std::__cxx11::list<flat_mutation_reader, std::allocator<flat_mutation_reader> >&, mutation_reader_merger::prepare_one(mutation_reader_merger::reader_and_last_fragment_kind, seastar::bool_class<mutation_reader_merger::reader_galloping_tag>)::$_3::operator()(seastar::optimized_optional<mutation_fragment>) const::{lambda(flat_mutation_reader&)#1}&&), std::__cxx11::list<flat_mutation_reader, std::allocator<flat_mutation_reader> >&, mutation_reader_merger::prepare_one(mutation_reader_merger::reader_and_last_fragment_kind, seastar::bool_class<mutation_reader_merger::reader_galloping_tag>)::$_3::operator()(seastar::optimized_optional<mutation_fragment>) const::{lambda(flat_mutation_reader&)#1}&&) (func=<optimized out>, args=..., args=...) at ./seastar/include/seastar/core/future.hh:2135
#11 seastar::futurize_invoke<seastar::future<void> (*&)(std::__cxx11::list<flat_mutation_reader, std::allocator<flat_mutation_reader> >&, mutation_reader_merger::prepare_one(mutation_reader_merger::reader_and_last_fragment_kind, seastar::bool_class<mutation_reader_merger::reader_galloping_tag>)::$_3::operator()(seastar::optimized_optional<mutation_fragment>) const::{lambda(flat_mutation_reader&)#1}&&), std::__cxx11::list<flat_mutation_reader, std::allocator<flat_mutation_reader> >&, mutation_reader_merger::prepare_one(mutation_reader_merger::reader_and_last_fragment_kind, seastar::bool_class<mutation_reader_merger::reader_galloping_tag>)::$_3::operator()(seastar::optimized_optional<mutation_fragment>) const::{lambda(flat_mutation_reader&)#1}>(seastar::future<void> (*&)(std::__cxx11::list<flat_mutation_reader, std::allocator<flat_mutation_reader> >&, mutation_reader_merger::prepare_one(mutation_reader_merger::reader_and_last_fragment_kind, seastar::bool_class<mutation_reader_merger::reader_galloping_tag>)::$_3::operator()(seastar::optimized_optional<mutation_fragment>) const::{lambda(flat_mutation_reader&)#1}&&), std::__cxx11::list<flat_mutation_reader, std::allocator<flat_mutation_reader> >&, mutation_reader_merger::prepare_one(mutation_reader_merger::reader_and_last_fragment_kind, seastar::bool_class<mutation_reader_merger::reader_galloping_tag>)::$_3::operator()(seastar::optimized_optional<mutation_fragment>) const::{lambda(flat_mutation_reader&)#1}&&) (func=<optimized out>, args=..., args=...) at ./seastar/include/seastar/core/future.hh:2166
#12 seastar::parallel_for_each<std::__cxx11::list<flat_mutation_reader, std::allocator<flat_mutation_reader> >&, mutation_reader_merger::prepare_one(mutation_reader_merger::reader_and_last_fragment_kind, seastar::bool_class<mutation_reader_merger::reader_galloping_tag>)::$_3::operator()(seastar::optimized_optional<mutation_fragment>) const::{lambda(flat_mutation_reader&)#1}>(std::__cxx11::list<flat_mutation_reader, std::allocator<flat_mutation_reader> >&, mutation_reader_merger::prepare_one(mutation_reader_merger::reader_and_last_fragment_kind, seastar::bool_class<mutation_reader_merger::reader_galloping_tag>)::$_3::operator()(seastar::optimized_optional<mutation_fragment>) const::{lambda(flat_mutation_reader&)#1}&&) (range=..., func=...) at ./seastar/include/seastar/core/loop.hh:610
#13 mutation_reader_merger::prepare_one(mutation_reader_merger::reader_and_last_fragment_kind, seastar::bool_class<mutation_reader_merger::reader_galloping_tag>)::$_3::operator()(seastar::optimized_optional<mutation_fragment>) const (this=0x60000517fc50, mfo=...) at mutation_reader.cc:421
#14 0x0000000001541219 in seastar::futurize<seastar::future<seastar::bool_class<mutation_reader_merger::needs_merge_tag> > >::invoke<mutation_reader_merger::prepare_one(mutation_reader_merger::reader_and_last_fragment_kind, seastar::bool_class<mutation_reader_merger::reader_galloping_tag>)::$_3, seastar::optimized_optional<mutation_fragment> >(mutation_reader_merger::prepare_one(mutation_reader_merger::reader_and_last_fragment_kind, seastar::bool_class<mutation_reader_merger::reader_galloping_tag>)::$_3&&, seastar::optimized_optional<mutation_fragment>&&) (func=..., args=...) at ./seastar/include/seastar/core/future.hh:2135
#15 seastar::future<seastar::optimized_optional<mutation_fragment> >::then_impl<mutation_reader_merger::prepare_one(mutation_reader_merger::reader_and_last_fragment_kind, seastar::bool_class<mutation_reader_merger::reader_galloping_tag>)::$_3, seastar::future<seastar::bool_class<mutation_reader_merger::needs_merge_tag> > >(mutation_reader_merger::prepare_one(mutation_reader_merger::reader_and_last_fragment_kind, seastar::bool_class<mutation_reader_merger::reader_galloping_tag>)::$_3&&) (this=0x60000517fc08, func=...) at ./seastar/include/seastar/core/future.hh:1601
#16 seastar::internal::call_then_impl<seastar::future<seastar::optimized_optional<mutation_fragment> > >::run<mutation_reader_merger::prepare_one(mutation_reader_merger::reader_and_last_fragment_kind, seastar::bool_class<mutation_reader_merger::reader_galloping_tag>)::$_3>(seastar::future<seastar::optimized_optional<mutation_fragment> >&, mutation_reader_merger::prepare_one(mutation_reader_merger::reader_and_last_fragment_kind, seastar::bool_class<mutation_reader_merger::reader_galloping_tag>)::$_3&&) (fut=..., func=...) at ./seastar/include/seastar/core/future.hh:1234
#17 seastar::future<seastar::optimized_optional<mutation_fragment> >::then<mutation_reader_merger::prepare_one(mutation_reader_merger::reader_and_last_fragment_kind, seastar::bool_class<mutation_reader_merger::reader_galloping_tag>)::$_3, seastar::future<seastar::bool_class<mutation_reader_merger::needs_merge_tag> > >(mutation_reader_merger::prepare_one(mutation_reader_merger::reader_and_last_fragment_kind, seastar::bool_class<mutation_reader_merger::reader_galloping_tag>)::$_3&&) (this=0x60000517fc08, func=...) at ./seastar/include/seastar/core/future.hh:1520
#18 mutation_reader_merger::prepare_one (this=0x60000429b678, rk=..., reader_galloping=...) at mutation_reader.cc:385
#19 mutation_reader_merger::prepare_next()::$_2::operator()(mutation_reader_merger::reader_and_last_fragment_kind) const (this=<optimized out>, rk=...) at mutation_reader.cc:376
#20 seastar::futurize<seastar::future<void> >::invoke<mutation_reader_merger::prepare_next()::$_2, mutation_reader_merger::reader_and_last_fragment_kind&>(mutation_reader_merger::prepare_next()::$_2&&, mutation_reader_merger::reader_and_last_fragment_kind&) (func=..., args=...) at ./seastar/include/seastar/core/future.hh:2135
#21 seastar::futurize_invoke<mutation_reader_merger::prepare_next()::$_2, mutation_reader_merger::reader_and_last_fragment_kind&>(mutation_reader_merger::prepare_next()::$_2&&, mutation_reader_merger::reader_and_last_fragment_kind&) (func=..., args=...) at ./seastar/include/seastar/core/future.hh:2166
#22 seastar::parallel_for_each<mutation_reader_merger::reader_and_last_fragment_kind*, mutation_reader_merger::prepare_next()::$_2>(mutation_reader_merger::reader_and_last_fragment_kind*, mutation_reader_merger::reader_and_last_fragment_kind*, mutation_reader_merger::prepare_next()::$_2&&) (begin=0x60000517fca0, end=0x60000429b7c8, func=...) at ./seastar/include/seastar/core/loop.hh:554
#23 seastar::internal::parallel_for_each_impl<utils::small_vector<mutation_reader_merger::reader_and_last_fragment_kind, 4ul>&, mutation_reader_merger::prepare_next()::$_2>(utils::small_vector<mutation_reader_merger::reader_and_last_fragment_kind, 4ul>&, mutation_reader_merger::prepare_next()::$_2&&) (range=..., func=...) at ./seastar/include/seastar/core/loop.hh:598
#24 seastar::futurize<seastar::future<void> >::invoke<seastar::future<void> (*&)(utils::small_vector<mutation_reader_merger::reader_and_last_fragment_kind, 4ul>&, mutation_reader_merger::prepare_next()::$_2&&), utils::small_vector<mutation_reader_merger::reader_and_last_fragment_kind, 4ul>&, mutation_reader_merger::prepare_next()::$_2>(seastar::future<void> (*&)(utils::small_vector<mutation_reader_merger::reader_and_last_fragment_kind, 4ul>&, mutation_reader_merger::prepare_next()::$_2&&), utils::small_vector<mutation_reader_merger::reader_and_last_fragment_kind, 4ul>&, mutation_reader_merger::prepare_next()::$_2&&) (func=<optimized out>, args=..., args=...) at ./seastar/include/seastar/core/future.hh:2135
#25 seastar::futurize_invoke<seastar::future<void> (*&)(utils::small_vector<mutation_reader_merger::reader_and_last_fragment_kind, 4ul>&, mutation_reader_merger::prepare_next()::$_2&&), utils::small_vector<mutation_reader_merger::reader_and_last_fragment_kind, 4ul>&, mutation_reader_merger::prepare_next()::$_2>(seastar::future<void> (*&)(utils::small_vector<mutation_reader_merger::reader_and_last_fragment_kind, 4ul>&, mutation_reader_merger::prepare_next()::$_2&&), utils::small_vector<mutation_reader_merger::reader_and_last_fragment_kind, 4ul>&, mutation_reader_merger::prepare_next()::$_2&&) (func=<optimized out>, args=..., args=...) at ./seastar/include/seastar/core/future.hh:2166
#26 seastar::parallel_for_each<utils::small_vector<mutation_reader_merger::reader_and_last_fragment_kind, 4ul>&, mutation_reader_merger::prepare_next()::$_2>(utils::small_vector<mutation_reader_merger::reader_and_last_fragment_kind, 4ul>&, mutation_reader_merger::prepare_next()::$_2&&) (range=..., func=...) at ./seastar/include/seastar/core/loop.hh:610
#27 mutation_reader_merger::prepare_next (this=this@entry=0x60000429b678) at mutation_reader.cc:375
#28 0x00000000015420af in mutation_reader_merger::operator() (this=this@entry=0x60000429b678) at mutation_reader.cc:505
#29 0x00000000015793d1 in mutation_fragment_merger<mutation_reader_merger>::fetch (this=0x60000429b670) at mutation_reader.cc:100
#30 mutation_fragment_merger<mutation_reader_merger>::operator() (this=0x60000429b670) at mutation_reader.cc:125
#31 merging_reader<mutation_reader_merger>::fill_buffer()::{lambda()#1}::operator()() const (this=this@entry=0x60000517fe78) at mutation_reader.cc:621
#32 0x000000000157853b in seastar::futurize<seastar::future<seastar::bool_class<seastar::stop_iteration_tag> > >::invoke<merging_reader<mutation_reader_merger>::fill_buffer()::{lambda()#1}&>(merging_reader<mutation_reader_merger>::fill_buffer()::{lambda()#1}&) (func=...) at ./seastar/include/seastar/core/future.hh:2135
#33 seastar::repeat<merging_reader<mutation_reader_merger>::fill_buffer()::{lambda()#1}>(merging_reader<mutation_reader_merger>::fill_buffer()::{lambda()#1}&&) (action=...) at ./seastar/include/seastar/core/loop.hh:118
#34 merging_reader<mutation_reader_merger>::fill_buffer (this=<optimized out>) at mutation_reader.cc:620
#35 0x0000000001951884 in flat_mutation_reader::impl::consume_pausable_in_thread<std::reference_wrapper<flat_mutation_reader::impl::consumer_adapter<stable_flattened_mutations_consumer<compact_for_compaction<sstables::compacting_sstable_writer, sstables::garbage_collected_sstable_writer> > > >, flat_mutation_reader::no_filter> (this=0x60000429b600, consumer=..., filter=...) at ./flat_mutation_reader.hh:249
#36 flat_mutation_reader::impl::consume_in_thread<stable_flattened_mutations_consumer<compact_for_compaction<sstables::compacting_sstable_writer, sstables::garbage_collected_sstable_writer> >, flat_mutation_reader::no_filter> (this=0x60000429b600, consumer=..., filter=...) at ./flat_mutation_reader.hh:347
#37 flat_mutation_reader::consume_in_thread<stable_flattened_mutations_consumer<compact_for_compaction<sstables::compacting_sstable_writer, sstables::garbage_collected_sstable_writer> >, flat_mutation_reader::no_filter> (this=0x600001252eb8, consumer=..., filter=...) at ./flat_mutation_reader.hh:490
#38 flat_mutation_reader::consume_in_thread<stable_flattened_mutations_consumer<compact_for_compaction<sstables::compacting_sstable_writer, sstables::garbage_collected_sstable_writer> > > (this=0x600001252eb8, consumer=...) at ./flat_mutation_reader.hh:496
#39 sstables::compaction::setup<sstables::garbage_collected_sstable_writer>(sstables::garbage_collected_sstable_writer)::{lambda(flat_mutation_reader)#1}::operator()(flat_mutation_reader)::{lambda()#1}::operator()() (this=<optimized out>) at compaction/compaction.cc:694
#40 0x00000000019515b4 in std::__invoke_impl<void, sstables::compaction::setup<sstables::garbage_collected_sstable_writer>(sstables::garbage_collected_sstable_writer)::{lambda(flat_mutation_reader)#1}::operator()(flat_mutation_reader)::{lambda()#1}>(std::__invoke_other, sstables::compaction::setup<sstables::garbage_collected_sstable_writer>(sstables::garbage_collected_sstable_writer)::{lambda(flat_mutation_reader)#1}::operator()(flat_mutation_reader)::{lambda()#1}&&) (__f=...) at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/invoke.h:61
#41 std::__invoke<sstables::compaction::setup<sstables::garbage_collected_sstable_writer>(sstables::garbage_collected_sstable_writer)::{lambda(flat_mutation_reader)#1}::operator()(flat_mutation_reader)::{lambda()#1}>(sstables::compaction::setup<sstables::garbage_collected_sstable_writer>(sstables::garbage_collected_sstable_writer)::{lambda(flat_mutation_reader)#1}::operator()(flat_mutation_reader)::{lambda()#1}&&) (__fn=...) at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/invoke.h:96
#42 std::__apply_impl<sstables::compaction::setup<sstables::garbage_collected_sstable_writer>(sstables::garbage_collected_sstable_writer)::{lambda(flat_mutation_reader)#1}::operator()(flat_mutation_reader)::{lambda()#1}, std::tuple<>>(sstables::compaction::setup<sstables::garbage_collected_sstable_writer>(sstables::garbage_collected_sstable_writer)::{lambda(flat_mutation_reader)#1}::operator()(flat_mutation_reader)::{lambda()#1}&&, std::tuple<>&&, std::integer_sequence<unsigned long>) (__f=..., __t=...) at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/tuple:1843
#43 std::apply<sstables::compaction::setup<sstables::garbage_collected_sstable_writer>(sstables::garbage_collected_sstable_writer)::{lambda(flat_mutation_reader)#1}::operator()(flat_mutation_reader)::{lambda()#1}, std::tuple<> >(sstables::compaction::setup<sstables::garbage_collected_sstable_writer>(sstables::garbage_collected_sstable_writer)::{lambda(flat_mutation_reader)#1}::operator()(flat_mutation_reader)::{lambda()#1}&&, std::tuple<>&&) (__f=..., __t=...) at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/tuple:1854
#44 seastar::futurize<void>::apply<sstables::compaction::setup<sstables::garbage_collected_sstable_writer>(sstables::garbage_collected_sstable_writer)::{lambda(flat_mutation_reader)#1}::operator()(flat_mutation_reader)::{lambda()#1}>(sstables::compaction::setup<sstables::garbage_collected_sstable_writer>(sstables::garbage_collected_sstable_writer)::{lambda(flat_mutation_reader)#1}::operator()(flat_mutation_reader)::{lambda()#1}&&, std::tuple<>&&) (func=..., args=...) at ./seastar/include/seastar/core/future.hh:2099
#45 seastar::async<sstables::compaction::setup<sstables::garbage_collected_sstable_writer>(sstables::garbage_collected_sstable_writer)::{lambda(flat_mutation_reader)#1}::operator()(flat_mutation_reader)::{lambda()#1}>(seastar::thread_attributes, sstables::compaction::setup<sstables::garbage_collected_sstable_writer>(sstables::garbage_collected_sstable_writer)::{lambda(flat_mutation_reader)#1}::operator()(flat_mutation_reader)::{lambda()#1}&&)::{lambda()#1}::operator()() const (this=0x60000019af20) at ./seastar/include/seastar/core/thread.hh:258
#46 seastar::noncopyable_function<void ()>::direct_vtable_for<seastar::async<sstables::compaction::setup<sstables::garbage_collected_sstable_writer>(sstables::garbage_collected_sstable_writer)::{lambda(flat_mutation_reader)#1}::operator()(flat_mutation_reader)::{lambda()#1}>(seastar::thread_attributes, sstables::compaction::setup<sstables::garbage_collected_sstable_writer>(sstables::garbage_collected_sstable_writer)::{lambda(flat_mutation_reader)#1}::operator()(flat_mutation_reader)::{lambda()#1}&&)::{lambda()#1}>::call(seastar::noncopyable_function<void ()> const*) (func=0x60000019af20) at ./seastar/include/seastar/util/noncopyable_function.hh:124
#47 0x0000000004005532 in seastar::noncopyable_function<void ()>::operator()() const (this=0x600004f7c880) at ./seastar/include/seastar/util/noncopyable_function.hh:209
#48 seastar::thread_context::main (this=0x60000019af00) at ./seastar/src/core/thread.cc:299
(gdb) p _monitor
$1 = (sstables::read_monitor &) @0x600004f7c880: {
  _vptr$read_monitor = 0x0
}
(gdb) p _context
$2 = {
  _M_t = {
    <std::__uniq_ptr_impl<sstables::mx::data_consume_rows_context_m, std::default_delete<sstables::mx::data_consume_rows_context_m> >> = {
      _M_t = {
        <std::_Tuple_impl<0, sstables::mx::data_consume_rows_context_m*, std::default_delete<sstables::mx::data_consume_rows_context_m> >> = {
          <std::_Tuple_impl<1, std::default_delete<sstables::mx::data_consume_rows_context_m> >> = {
            <std::_Head_base<1, std::default_delete<sstables::mx::data_consume_rows_context_m>, true>> = {
              _M_head_impl = {<No data fields>}
            }, <No data fields>}, 
          <std::_Head_base<0, sstables::mx::data_consume_rows_context_m*, false>> = {
            _M_head_impl = 0x60000429a700
          }, <No data fields>}, <No data fields>}
    }, <No data fields>}
}
```

Core dump is here: https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/938/artifact/logs-all.release.2/1632437579952_compaction_additional_test.CompactionAdditionalTest.refresh_and_restart_after_compaction_strategy_change_test/node1-scylla.71751.1632436676.core.gz

Reloc package: http://downloads.scylladb.com.s3.amazonaws.com/unstable/scylla/master/relocatable/2021-09-23T17%3A49%3A15Z/scylla-package.tar.gz

**Comment by bhalevy** [comment] 2021-09-24 15:40
Cc @tgrabiec @denesb

**Comment by avikivity** [comment] 2021-09-26 15:54
Closing as duplicate of #9388.

**Closed by avikivity** 2021-09-26 15:54 UTC
