### ISSUE TITLE
stress failed during double_node_failure_during_mv_insert_3_nodes_test

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#4450] opened 2019-04-21 13:10 UTC
scylla version d485facea2b930371db2001cfa20969ed1b9cf20
scylla-dtest version scylladb/scylla-dtest@3546cc4efd07c5c638a5ed7f17935908394d48b8

Seen in [dtest-release/100/testReport/materialized_views_test/TestMaterializedViews/double_node_failure_during_mv_insert_3_nodes_test](http://jenkins.cloudius-systems.com:8080/view/master/job/scylla-master/job/dtest-release/100/testReport/materialized_views_test/TestMaterializedViews/double_node_failure_during_mv_insert_3_nodes_test/):
```
Error Message
Stress command exited with error code: 1

com.datastax.driver.core.exceptions.OverloadedException: Queried host (127.0.45.1/127.0.45.1:9042) was overloaded: Too many in flight hints: 10485909
...
WARN  04:49:50,081 Host 127.0.45.1/127.0.45.1:9042 is overloaded.
com.datastax.driver.core.exceptions.OverloadedException: Queried host (127.0.45.1/127.0.45.1:9042) was overloaded: Too many in flight hints: 10485909
java.lang.RuntimeException: Failed to execute stress action
	at org.apache.cassandra.stress.StressAction.run(StressAction.java:100)
	at org.apache.cassandra.stress.Stress.run(Stress.java:143)
	at org.apache.cassandra.stress.Stress.main(Stress.java:62)
```

I'm not sure if this is an issue with scylla or a test bug.

**Comment by psarna** [comment] 2019-05-06 11:01
Looks like this behaviour was implemented intentionally - eventually we reach the limit of in-flight hints, so we return an exceptional future for the next write request that might need to store hints. That means c-s was expected to receive an error.

Still, I wonder if it is at all desirable to return an error when we can't store hints. Since hints are by definition not reliable, maybe we should just not store them? They do not count for the consistency level unless it's ANY, so perhaps only cl::ANY writes should actually fail if our hints manager is overloaded, while the other writes should simply succeed if they reached their consistency level?

/cc @vladzcloudius

**Comment by bhalevy** [comment] 2019-05-06 12:28
> Looks like this behaviour was implemented intentionally - eventually we reach the limit of in-flight hints, so we return an exceptional future for the next write request that might need to store hints. That means c-s was expected to receive an error.
> 
> Still, I wonder if it is at all desirable to return an error when we can't store hints. Since hints are by definition not reliable, maybe we should just not store them? They do not count for the consistency level unless it's ANY, so perhaps only cl::ANY writes should actually fail if our hints manager is overloaded, while the other writes should simply succeed if they reached their consistency level?
> 
> /cc @vladzcloudius

@psarna that sounds reasonable to me.  Let's take the discussion to the mailing list to make sure we haven't missed anything.

**Comment by vladzcloudius** [comment] 2019-05-06 16:20
@bhalevy Please, refer me to the corresponding thread if needed.
The returning of Overloaded exception is indeed by-design and it is only partially related to HH. There is a rather big comment at the corresponding place in the code:

https://github.com/scylladb/scylla/blob/d9136f96f3909112cf3aa374dcb473a80f7a9140/service/storage_proxy.cc#L1024

In short, the idea behind this heuristic is to apply a back pressure on the client when replica nodes are overloaded and this in particular creates an excessive HH queuing.
Therefore it's not only about preventing HH consume too much memory of the coordinator but also about regular requests that are likely queuing up both on the coordinator and/or on the replica node(s).

**Comment by bhalevy** [comment] 2019-05-06 16:37
@vladzcloudius see discussion thread [here](https://groups.google.com/a/scylladb.com/forum/#!topic/rnd-internal/vPvr03zlT8k)

**Comment by psarna** [comment] 2019-05-07 14:21
The conclusion seems to be that `OverloadedException` is how admission control works by design - it's based on the number of hints present in the system and once we hit a limit, we consciously start returning errors to clients. Under these assumptions, it just *can* happen.

We may want to revise this decision and base admission control on something else than hints, since these can hit the limit even if the node is not overloaded at all, it can happen naturally when a node is down for a long time.

**Comment by vladzcloudius** [comment] 2019-05-07 21:15
@psarna Could you, please, clarify how exactly this may happen when "node is down for a long time"?

**Comment by juliayakovlev** [comment] 2019-08-21 07:39
This issue is recreated by SCT (longevity-50gb-4days test).
Cluster setup:
- 6 nodes (i3.4xlarge)
- 3 loaders (c5.2xlarge)
- Scylla version: 

The scenario:
- HH is enabled
- stop one node
- 10 sec sleep
- start the node
- reported in the log that ```Hints are sent too slow```
- on the same node run ```nodetool repair```
- Received the "Too many in flight hints" errors:
```
< t:2019-08-21 06:07:49,991 f:remote.py       l:662  c:sdcm.remote          p:INFO  > RemoteCmdRunner [centos@172.30.0.93]: com.datastax.driver.core.exceptions.OverloadedException: Queried host (ip-172-30-0-228.ec2.internal/172.30.0.228:9042) was overloaded: Too many in flight hints: 10486005
```

**Comment by haaawk** [comment] 2020-11-12 17:21
It seems that this test was already problematic before. https://github.com/scylladb/scylla-dtest/commit/faf879e22b47c865535244252c022f016d196a4a is making the test ignore mutation_write_timeout_exception which can lead us to the suspicion that the cluster is stressed beyond its limits. If mutation_write_timeout_exception happens but QUORUM can be achieved, the write request will be acknowledged to the client as successful but a hint will also be created to the replica that has timed out.

Now the question is whether the test sends too many requests to the cluster or is this a performance regression.
Having mutation_write_timeout_exception excluded in the test suggests that the cluster must be at its limits.

In general, we can't rely on this test because it does not control the strength of the cluster it runs on. On a strong machine, the test works just fine but on a weak one like Jenkins it may fail. My point is that the number of requests sent to the cluster by the test has to be small enough to be ok for a cluster running on a weak machine.

It's a wrong test because it works fine on a fast machine and fails on a slow one. We can't use the same load no matter what's the machine.

**Comment by kbr-** [comment] 2020-11-12 17:28
2 months before this issue was reported there was a change which potentially reduced the amount of MV backpressure, which could result in more writes being performed, which could result in more hints being generated, which could lead to this issue.
https://github.com/scylladb/scylla/commit/66a48746b86b5e8563a0c47938d779e405e35dda
We could try measuring how often this issue reproduces with that change vs without (we could try using a recent version of Scylla with this change reverted).

**Comment by haaawk** [comment] 2020-11-12 17:37
> 2 months before this issue was reported there was a change which potentially reduced the amount of MV backpressure, which could result in more writes being performed, which could result in more hints being generated, which could lead to this issue.
> [66a4874](https://github.com/scylladb/scylla/commit/66a48746b86b5e8563a0c47938d779e405e35dda)
> We could try measuring how often this issue reproduces with that change vs without (we could try using a recent version of Scylla with this change reverted).

This could be it. If backpressure was making requests longer then maybe that was causing c-s sending fewer requests and the cluster wasn't stressed that much.

One way or the other, this is a dtest not a performance test and we really don't have to push the cluster to its limits when we're bringing a node down anyway. In my opinion, this test should check correctness not performance.

**Comment by haaawk** [comment] 2020-11-12 17:46
On second thought, views backpressure was reduced so hints backpressure kicked in. This sounds reasonable to me.

**Comment by haaawk** [comment] 2020-11-12 17:47
We're having one out of 3 nodes handling all the requests and every write generating 2 hints. No wonder the number of hints grows quickly.

**Comment by haaawk** [comment] 2020-11-12 18:06
Actually, every write generates 4 hints: 2 for the base table and 2 for the view.

**Comment by haaawk** [comment] 2020-11-13 08:51
In my opinion, the overloaded exception is expected to happen occasionally in this test and we should just exclude it the same way `mutation_write_timeout_exception` is excluded. @slivne @roydahan what do you think?

**Comment by roydahan** [comment] 2020-11-16 15:16
I'm fine with what @slivne decides to do with it.

**Comment by haaawk** [comment] 2020-11-16 18:28
@slivne do we have your approval?

**Comment by slivne** [comment] 2021-01-24 20:31
@haaawk / @roydahan / @piodul can we change the test so it will not throw such exceptions - this is a functional dtest - not an SCT test failure. At the end the goal of the functional tests it to make sure that we are testing some logic in Scylla - mutation_write_timeout_exception can be thrown on the first write as well. How do we differentiate between a state in which its thrown when to many hints have been accumulated to the act its thrown on the first write before any hint has been written.

So lets try and change the test so it will not reach a point it needs to throw such exceptions (e.g. reduce the rate  / limit the number of writes after the 2 nodes fail etc.)

**Comment by roydahan** [comment] 2021-01-26 00:14
We can change the dtest but this behaviour also happen in various SCT tests.
Sometimes we just hit the overload exception when HH is enabled.

**Comment by haaawk** [comment] 2021-03-21 09:24
If we don't have to fix anything then let's close this issue.

**Closed by haaawk** 2021-03-21 09:24 UTC
Labels: dtest, hinted-handoff, materialized-views
