### ISSUE TITLE
Slower than Cassandra

### ISSUE THREAD

**Issue by ratcashdev** [scylladb/scylla#5297] opened 2019-11-18 11:53 UTC
Scylla version (or git commit hash): 3.1.1
Cluster size: 5
OS (RHEL/CentOS/Ubuntu/AWS AMI): CentOS 7.7

Hardware details (for performance issues)
Platform (physical/VM/cloud instance type/docker): L16s_v2 on Azure
Hardware: vCpu=16, memory=128GB
Disks: (SSD/HDD, count): 2 x NVMe 1.8TB in RAID0 on XFS
```
[user@DB-10 ~]$ cat /etc/scylla.d/io_properties.yaml
disks:
  - mountpoint: /var/lib/scylla
    read_iops: 805665
    read_bandwidth: 6067062784
    write_iops: 564755
    write_bandwidth: 2845452800
```

We have set of recorded (write-only) statements that we use as a performance benchmark both against Cassandra, and against Scylla.
Cassandra with a less performant HW [5x DS5v2 (16vcpu / 56GB RAM, and P15 disks with only 1.1k IOPS)] is outperforming Scylla in terms of overall time needed ( 3:30 for Cass, 4:00 for Scylla), yet Scylla is giving somewhat better MEAN write latency.
The workload creates lots of tombstones (basically INSERT + UPDATE + DELETE statements). No batches.

The client-side driver is Cassandra v 4.2.x.
For Scylla, it is set to use 16 connections / hosts and 100 requests / connection.
Replication factor: 3.
Inter-node ping latency: between 0.5ms - 0.8ms.

CPU load in the DBs is uniform, between 50-80%.
The logs contain compaction infos like this:
```

Nov 18 11:28:39 DB-10 scylla[3705]:  [shard 13] compaction - Compacting [/var/lib/scylla/data/keyspace1/table2-1e5302f009ec11ea8eb500000000000a/mc-181-big-Data.db:level=0, /var/lib/scylla/data/keyspace1/table2-1e5302f009ec11ea8eb500000000000a/mc-167-big-Data.db:level=0, ]
Nov 18 11:28:54 DB-10 scylla[3705]:  [shard 0] compaction - Compacting [/var/lib/scylla/data/keyspace1/table3-1e64dd4009ec11ea8eb500000000000a/mc-112-big-Data.db:level=0, /var/lib/scylla/data/keyspace1/table3-1e64dd4009ec11ea8eb500000000000a/mc-98-big-Data.db:level=0, ]
Nov 18 11:29:09 DB-10 scylla[3705]:  [shard 0] compaction - Compacted 2 sstables to [/var/lib/scylla/data/keyspace1/table3-1e64dd4009ec11ea8eb500000000000a/mc-126-big-Data.db:level=0, ]. 28070812 bytes to 17287294 (~61% of original) in 15134ms = 1.09MB/s. ~384 total partitions merged to 235.
Nov 18 11:29:16 DB-10 scylla[3705]:  [shard 13] compaction - Compacted 2 sstables to [/var/lib/scylla/data/keyspace1/table2-1e5302f009ec11ea8eb500000000000a/mc-195-big-Data.db:level=0, ]. 23780515 bytes to 23708826 (~99% of original) in 36795ms = 0.61MB/s. ~256 total partitions merged to 4.
Nov 18 11:29:16 DB-10 scylla[3705]:  [shard 13] compaction - Compacting [/var/lib/scylla/data/keyspace1/table2-1e5302f009ec11ea8eb500000000000a/mc-209-big-Data.db:level=0, /var/lib/scylla/data/keyspace1/table2-1e5302f009ec11ea8eb500000000000a/mc-195-big-Data.db:level=0, ]
Nov 18 11:30:02 DB-10 scylla[3705]:  [shard 13] compaction - Compacted 2 sstables to [/var/lib/scylla/data/keyspace1/table2-1e5302f009ec11ea8eb500000000000a/mc-223-big-Data.db:level=0, ]. 30369308 bytes to 29715805 (~97% of original) in **45588ms** = 0.62MB/s. ~256 total partitions merged to 4.
Nov 18 11:30:02 DB-10 scylla[3705]:  [shard 13] compaction - Compacting [/var/lib/scylla/data/keyspace1/table2-1e5302f009ec11ea8eb500000000000a/mc-153-big-Data.db:level=0, /var/lib/scylla/data/keyspace1/table2-1e5302f009ec11ea8eb500000000000a/mc-223-big-Data.db:level=0, /var/lib/scylla/data/keyspace1/table2-1e5302f009ec11ea8eb500000000000a/mc-83-big-Data.db:level=0, ]
Nov 18 11:30:12 DB-10 scylla[3705]:  [shard 0] compaction - Compacting [/var/lib/scylla/data/keyspace1/table1-1e3ff02009ec11ea8eb500000000000a/mc-56-big-Data.db:level=0, /var/lib/scylla/data/keyspace1/table1-1e3ff02009ec11ea8eb500000000000a/mc-42-big-Data.db:level=0, ]
Nov 18 11:30:15 DB-10 scylla[3705]:  [shard 0] compaction - Compacted 2 sstables to [/var/lib/scylla/data/keyspace1/table1-1e3ff02009ec11ea8eb500000000000a/mc-70-big-Data.db:level=0, ]. 9445954 bytes to 5690941 (~60% of original) in 3838ms = 1.41MB/s. ~256 total partitions merged to 42.
Nov 18 11:30:56 DB-10 scylla[3705]:  [shard 1] compaction - Compacting [/var/lib/scylla/data/keyspace1/table1-1e3ff02009ec11ea8eb500000000000a/mc-239-big-Data.db:level=0, /var/lib/scylla/data/keyspace1/table1-1e3ff02009ec11ea8eb500000000000a/mc-253-big-Data.db:level=0, ]
Nov 18 11:31:05 DB-10 scylla[3705]:  [shard 13] compaction - Compacted 3 sstables to [/var/lib/scylla/data/keyspace1/table2-1e5302f009ec11ea8eb500000000000a/mc-251-big-Data.db:level=0, ]. 95649724 bytes to 39438726 (~41% of original) in **63378ms** = 0.59MB/s. ~384 total partitions merged to 41.
Nov 18 11:31:22 DB-10 scylla[3705]:  [shard 0] compaction - Compacting [/var/lib/scylla/data/keyspace1/table1-1e3ff02009ec11ea8eb500000000000a/mc-70-big-Data.db:level=0, /var/lib/scylla/data/keyspace1/table1-1e3ff02009ec11ea8eb500000000000a/mc-84-big-Data.db:level=0, ]
Nov 18 11:31:36 DB-10 scylla[3705]:  [shard 0] compaction - Compacted 2 sstables to [/var/lib/scylla/data/keyspace1/table1-1e3ff02009ec11ea8eb500000000000a/mc-98-big-Data.db:level=0, ]. 12964909 bytes to 5710077 (~44% of original) in 14709ms = 0.37MB/s. ~256 total partitions merged to 42.
Nov 18 11:33:05 DB-10 scylla[3705]:  [shard 1] compaction - Compacting [/var/lib/scylla/data/keyspace1/table1-1e3ff02009ec11ea8eb500000000000a/mc-267-big-Data.db:level=0, /var/lib/scylla/data/keyspace1/table1-1e3ff02009ec11ea8eb500000000000a/mc-295-big-Data.db:level=0, ]
Nov 18 11:33:05 DB-10 scylla[3705]:  [shard 1] compaction - Compacted 2 sstables to [/var/lib/scylla/data/keyspace1/table1-1e3ff02009ec11ea8eb500000000000a/mc-281-big-Data.db:level=0, ]. 73288750 bytes to 39763798 (~54% of original) in **128590ms** = 0.29MB/s. ~256 total partitions merged to 30.
Nov 18 11:33:12 DB-10 scylla[3705]:  [shard 1] compaction - Compacting [/var/lib/scylla/data/keyspace1/table1-1e3ff02009ec11ea8eb500000000000a/mc-309-big-Data.db:level=0, /var/lib/scylla/data/keyspace1/table1-1e3ff02009ec11ea8eb500000000000a/mc-281-big-Data.db:level=0, ]
Nov 18 11:33:12 DB-10 scylla[3705]:  [shard 1] compaction - Compacted 2 sstables to [/var/lib/scylla/data/keyspace1/table1-1e3ff02009ec11ea8eb500000000000a/mc-323-big-Data.db:level=0, ]. 84387113 bytes to 29079769 (~34% of original) in 7560ms = 3.67MB/s. ~256 total partitions merged to 30.
Nov 18 11:33:17 DB-10 scylla[3705]:  [shard 1] compaction - Compacted 2 sstables to [/var/lib/scylla/data/keyspace1/table1-1e3ff02009ec11ea8eb500000000000a/mc-337-big-Data.db:level=0, ]. 60707331 bytes to 46170495 (~76% of original) in 5137ms = 8.57MB/s. ~256 total partitions merged to 30.
```
Lots of compactions (as it is expected), but they seem to be quite slow (>128 secs)
Monitoring shows this: 
![timeouts](https://user-images.githubusercontent.com/2928922/69050295-fe8b2b80-0a01-11ea-9989-df44081bf96f.PNG)

**Comment by avikivity** [comment] 2019-11-18 11:58
Please provide a shard-level view.

What's the workload concurrency?

Are you using the shard-aware driver?

**Comment by ratcashdev** [comment] 2019-11-18 12:03
Using the stock Cassandra v4.2 driver (whether that is 'shard-aware', I don't know). For compatibility reasons the 3.x driver branch (and thus native Scylla driver) can't be used without major changes.
Where will I find the shared-level view in Prometeus? Only have IO/OS/Overview/Detailed/CPU/SQL/Errors views.
The workload concurrency: a single thread/server is doing the replay and utilizing the connection pool with the settings already mentioned.

**Comment by tarzanek** [comment] 2019-11-18 12:03
cassandra driver is used, this is pure write workload
STCS default is used, from where I stand(and based on talk on channel) I think some tuning of compaction strategy might be needed

from basic data check - large rows/cells: empty
scylla_setup: IO tuning was done (could Azure need some more?)

**Comment by ratcashdev** [comment] 2019-11-18 12:25
Shard level view for one of the hosts in the cluster: 
![shard-view](https://user-images.githubusercontent.com/2928922/69052252-e5d14480-0a06-11ea-9a79-d0408812532a.PNG)

**Comment by avikivity** [comment] 2019-11-18 12:32
@haaawk do we have a 4.x version of the shard-aware driver?

**Comment by avikivity** [comment] 2019-11-18 12:33
For concurrency, I need to know how many client threads the loader is using, and whether you are using async requests or not.

**Comment by ratcashdev** [comment] 2019-11-18 12:36
10 threads configured for netty-io in Cassandra's driver. The host producing the workload is utilized around 50%.
All requests are async.

**Comment by avikivity** [comment] 2019-11-18 12:40
What is a typical insert/update row size?

**Comment by ratcashdev** [comment] 2019-11-18 12:41
not sure exactly, but the select to uncover large rows/cells returns an empty set.

**Comment by avikivity** [comment] 2019-11-18 12:45
Can you estimate it? Perhaps by dividing port 9042 bandwidth by requets/sec. Or perhaps commit log bandwidth (available in the per-server I/O dashboard) by the request rate (and again by RF).

So far it looks like the problem is shard imbalance and that is most easily fixed with the shard-aware driver, let's see if @haaawk has a version that's suitable for you.

**Comment by ratcashdev** [comment] 2019-11-18 12:45
We may have big partitions, though:
![image](https://user-images.githubusercontent.com/2928922/69053425-af48f900-0a09-11ea-8116-d58328394c83.png)

**Comment by haaawk** [comment] 2019-11-18 12:47
> @haaawk do we have a 4.x version of the shard-aware driver?

It's not released yet. We would need to put some work to release it but the core functionality is there.

**Comment by ratcashdev** [comment] 2019-11-18 12:49
The total load is ~23M statements. The biggest table contains 1.8 million rows.

**Comment by avikivity** [comment] 2019-11-18 12:51
@haaawk they must use 4.x it seems. Can you provide a preview version for testing?

**Comment by haaawk** [comment] 2019-11-18 12:53
Yes. I will prepare one.

**Comment by ratcashdev** [comment] 2019-11-18 13:01
this is a complete shard view of the latencies:
![image](https://user-images.githubusercontent.com/2928922/69054456-e6200e80-0a0b-11ea-83fc-40d80ed81390.png)

**Comment by ratcashdev** [comment] 2019-11-18 13:04
Anther shard view of bytes/rows/partitions created/removed:
![image](https://user-images.githubusercontent.com/2928922/69054618-49aa3c00-0a0c-11ea-988d-6e5853d21627.png)

**Comment by tarzanek** [comment] 2019-11-18 13:10
re large partition - check https://docs.scylladb.com/troubleshooting/large_partition_table/

**Comment by ratcashdev** [comment] 2019-11-18 13:14
```
[cqlsh 5.0.1 | Cassandra 3.0.8 | CQL spec 3.3.1 | Native protocol v4]
Use HELP for help.
cqlsh> SELECT * FROM system.large_partitions;

 keyspace_name | table_name | sstable_name | partition_size | partition_key | compaction_time
---------------+------------+--------------+----------------+---------------+-----------------

(0 rows)
```

**Comment by tarzanek** [comment] 2019-11-18 13:17
could you share your schema @ratcashdev ? ev. the workload data?
also what CL is used for the write queries?

**Comment by ratcashdev** [comment] 2019-11-18 13:19
@tarzanek schema not publicly. Workload: that would be difficult.
ConsistencyLevel = LOCAL_QUORUM

**Comment by tarzanek** [comment] 2019-11-18 13:20
also first thing that came to my mind is: https://docs.scylladb.com/troubleshooting/pointless_compactions/  you could try to apply this to your schema, but I think more changes will be needed, since your workload is obviously triggering some weird behaviour

**Comment by ratcashdev** [comment] 2019-11-18 13:21
I guess pointless compactions is not our case - initial post.

**Comment by tarzanek** [comment] 2019-11-18 13:21
if you don't mind sharing schema privately, check https://docs.scylladb.com/troubleshooting/report_scylla_problem/#send-files-to-scylladb-support and let us know the UUID so we can check it

**Comment by ratcashdev** [comment] 2019-11-18 13:26
Uploaded: 12e12012-8dcc-4314-b7e2-69b8d697288a

**Comment by tarzanek** [comment] 2019-11-18 13:40
do you insert with TTLs? if yes, what are they?
resp. do you need to delete the data after some time?

**Comment by avikivity** [comment] 2019-11-18 13:45
Slow compactions is a red herring. Because the data set is so small, Scylla assigns few resources for compactions and devotes most CPU and I/O resources to normal writes.

As the data set size will increase, Scylla will assign more resources for compactions (at the expense of writes).

**Comment by ratcashdev** [comment] 2019-11-18 13:47
No TTLs. We delte the data explicitly.

**Comment by ratcashdev** [comment] 2019-11-18 14:19
Note: the scylla.yaml contains 
`concurrent_writes: 128`
 according to the recommendations to have 8 writes / core.

**Comment by avikivity** [comment] 2019-11-18 14:44
Scylla ignores this configuration parameter, it's only valid for Cassandra. It's a bug that it's present in the template scylla.yaml.

**Comment by ratcashdev** [comment] 2019-11-18 14:45
heh, good to know! At least this one was ruled out.

**Comment by tarzanek** [comment] 2019-11-18 14:51
@ratcashdev what do you configure on the driver that is not default besides connection #?
(I am interested in all values and also in https://docs.datastax.com/en/developer/java-driver/4.2/manual/core/throttling/ )

**Comment by ratcashdev** [comment] 2019-11-18 14:57
there's no throttling.
```
datastax-java-driver {

    basic {
        contact-points = [ "127.0.0.1:9042" ]
        request.consistency = LOCAL_QUORUM
        request.timeout = 10 seconds
        request.default-idempotence = true
        load-balancing-policy.local-datacenter = datacenter1
    }


    advanced {
        # code requires V4
        protocol.version = V4
        # protocol.compression = lz4
        #auth-provider.class = PlainTextAuthProvider
        #auth-provider.username = ""
        #auth-provider.password = ""
        timestamp-generator.class = AtomicTimestampGenerator
        retry-policy.class = com.protonchains.tradingengine.persistence.CustomRetryPolicy

#        connection {
            max-requests-per-connection = 100
            pool {
                local.size = 16
#                remote.size = 1
            }
#        }
#        metrics {
#            session.enabled = [cql-requests]
#            node.enabled = [pool.open-connections, pool.in-flight, pool.available-streams, pool.orphaned-streams]
#        }
    }
}

```

**Comment by avikivity** [comment] 2019-11-18 15:05
I filed https://github.com/scylladb/scylla/pull/5299 to avoid future confusion.

**Comment by tarzanek** [comment] 2019-11-18 15:20
hmm, can you disable request.default-idempotence  and rerun?
what are the conditions for CustomRetryPolicy ? (e.g. retry after X amount of time?)
can you also try without the retry policy?
(and I know above will result in lost writes, I am just curious about the # of OPS and pressure on the cluster)

**Comment by haaawk** [comment] 2019-11-18 15:26
Here's a shard aware driver based on 4.2.2. I had to add .txt suffix to get it accepted by github so please remove the suffix before usage.
[java-driver-core-4.2.2.jar.txt](https://github.com/scylladb/scylla/files/3859305/java-driver-core-4.2.2.jar.txt)

**Comment by ratcashdev** [comment] 2019-11-18 17:16
@tarzanek The CustomRetryPolicy does nothing else, just retries on the next node. Does not wait, retries immediately. I can tell you that disabling it does not change a thing in the cluster's load :( Fortunately there's no that much retries necessary for the majority of the shard writes.
@haaawk I will incorporate it. Do you perhaps also some maven.pom (does not have to be on central, just the pom itself, so gradle will be able to pick it up from the local repo).

**Comment by ratcashdev** [comment] 2019-11-18 17:25
@haaawk never mind, found the pom inside the jar.

**Comment by tarzanek** [comment] 2019-11-18 20:12
@ratcashdev so basically where I was coming from - I am trying to see whether there is an artificial amplification and rule it out
anyway curious about the shard aware driver change, if it will work for your UC, it might give you a 5-10% improvement on cpu load
I'd like to also know the distribution and size of the data, looking at the schema it really seems like the rows shouldn't be that big(unless the text cell is too long) - and you confirmed it won't be big above, so could it be you always target one token range (shard) belonging to the same node - so the distribution is zipfian and creating a hot partition? (for some of shards the graphs it really looks like a hot partition) - do you have any stats on same PK upsert/delete per second?

**Comment by tarzanek** [comment] 2019-11-18 20:25
also just a side note, so L-series used for scylla is  AMD EPYC 7551 processor 
and D-series used for cassandra is Intel Xeon® E5-2673 v3 or v4

**Comment by ratcashdev** [comment] 2019-11-18 20:35
@tarzanek there are definitely some hot partitions/shards, that for sure and also visible from the graphs. We know some of the load in the recorded set targets single partitions. Rows are small. The text field is max 20 chars and mostly not used at all.
> PK upsert/delete per second?
well, this is a rough guess... but from the app's perspective, with the current HW (using Scylla), we're able to do 15k ops / sec, which can be roughly translated to 100-120k PK inserts and deletes / sec. Needless to say, the app is heavily back-pressured by the DB. Without the DB it is able to do 400k ops / sec.

**Comment by ratcashdev** [comment] 2019-11-19 14:11
Tested the optimized driver. At first sight, it game the expected lower cpu load through Prometeus (nor around 50%). The overall time to execute the test was still bad.
And then I checked `htop` directly on one of the servers, and got this:
![htop](https://user-images.githubusercontent.com/2928922/69153331-54cd9c80-0ade-11ea-8b90-bf93eccca9a5.PNG)
All cores 100%, constantly!

We tested having Cassandra on those very same servers with fast disks. The results were surprising. While before (5x DS4) the CPU load was 20%, on the 5x L16s_v2 cluster the cpu load was close to 80% (again, through monitoring/grafana, not `htop`) and the overall time was just slightly better than on the DS4 (but, yeah, still better than with Scylla).

**Comment by tarzanek** [comment] 2019-11-19 14:12
ok, one more thing - can you decrease 100 requests per connection to ~20-30 ?

**Comment by tarzanek** [comment] 2019-11-19 14:12
btw. disregard htop - scylla does active polling, so the only usable cpu load comes from prometheus

**Comment by ratcashdev** [comment] 2019-11-19 14:14
still 50% times are in RED, i.e. kernel times.

**Comment by ratcashdev** [comment] 2019-11-19 14:15
@tarzanek this last test was with 
```
datastax-java-driver.advanced.netty.io-group.size = 10
datastax-java-driver.advanced.connection.pool.local.size = 16
datastax-java-driver.advanced.connection.max-requests-per-connection = 50
```

**Comment by tarzanek** [comment] 2019-11-19 14:34
can we try with:
```
datastax-java-driver.advanced.connection.pool.local.size = 32
datastax-java-driver.advanced.connection.max-requests-per-connection = 20
```
two more things
- tuning of NIC on azure needs to be improved:
`/usr/lib/scylla/perftune.py --tune net --nic <NIC> --mode `

- in scylla.yaml add:
`compaction_enforce_min_threshold: true`
to ease on compactions

also - can you check the dashboards with Optimizations in monitoring?
(I am mainly curious if you use prepared statements)

hot partitions and lots of tombstones are generally a problem (for cassandra too, which might even require major compactions ) and ideally if they could be avoided (some talks on this:
https://www.scylladb.com/2019/03/27/best-practices-for-scylla-applications/
https://www.scylladb.com/tech-talk/keeping-your-latency-slas-no-matter-what/
https://www.scylladb.com/tech-talk/make-scylla-fast-again/
https://www.slideshare.net/ScyllaDB/scylla-summit-2018-how-scylla-helps-you-to-be-a-better-application-developer
)

**Comment by tarzanek** [comment] 2019-11-19 14:38
also if possible could you share (make a .tgz) of your prometheus data with us (use the same upload channel as you reported your schema with)  ? this will avoid a lot of Qs from our side and we will get a holistic view on your situation

**Comment by ratcashdev** [comment] 2019-11-19 14:58
@tarzanek  32/20 gave already worse results.
NIC: IRQs were nicely balanced in /proc/interrupts.  `/usr/lib/scylla/perftune.py --tune net --nic <NIC>` did not help, even though that at least on one of the systems `hwloc` package was missing.
All of the statements we use are prepared.

**Comment by avikivity** [comment] 2019-11-19 15:02
> still 50% times are in RED, i.e. kernel times.

For all cpus, or all except one? If the former, then the system is underloaded. If the latter, then interrupt imbalance is indicated.

Make sure you run nothing else on that machine.

**Comment by ratcashdev** [comment] 2019-11-19 15:05
@avikivity all cpus. You can see that in the screenshot of htop a couple of posts above.

**Comment by ratcashdev** [comment] 2019-11-19 15:06
@tarzanek can you please explain (link) how to export the data from prometeus to tgz?

**Comment by avikivity** [comment] 2019-11-19 15:10
Then it means the server is underloaded. Check that the client isn't the bottleneck. Even if overall CPU utilization is 50%, perhaps some thread reaches 100% utilization and everything else is blocked on it, or perhaps you have lock contention.

**Comment by tarzanek** [comment] 2019-11-19 15:13
- the perftune nic stuff - you need run it for ALL cards in Azure (it's some special virtualization stuff they do, where it won't properly tune if only run on the only NIC with IP)

the game with 32/20 is about getting to a state without timeouts (decrease parallelism to actually perform OK with the system, not to push it above its limits or too high queues) - so let's try 16/20 - just trying to find a sweet spot
the idea is that all shards should be able to work in parallel(and recieve requests in sane manner), however hot shards/tokens will affect the overall experience (but with shard driver we will see it in metrics) - based on Avi if this is a prob, we will see it in per shard metrics

the prometheus stuff - the data dir you provided to monitoring - you can .tgz it and send back to us using https://docs.scylladb.com/troubleshooting/report_scylla_problem/#send-files-to-scylladb-support

**Comment by ratcashdev** [comment] 2019-11-19 15:39
@avikivity the client is (except for the driver) lock-free. Able to replay the whole job in couple of seconds if not backpressured by Cassandra. In fact, with a single-node cluster with RF:1 the times were fractional, compared to the 5 node cluster with RF3.
@tarzanek I have already tried lots of combinations. 16/50 was giving me a stable, yet the fastest results. I have also read somewhere that as soon as foreground write queue starts to rise, it means the system is overloaded.
32/20 results: 99th latency immediately jumps to 4s right in the beginning. Overal times: worse than before.

**Comment by avikivity** [comment] 2019-11-19 15:41
Then maybe there isn't enough concurrency.

**Comment by tarzanek** [comment] 2019-11-19 15:46
you're right with foreground queues, so let's stick with 16/50 then
how about  compaction_enforce_min_threshold, did it influence the test?

**Comment by avikivity** [comment] 2019-11-19 15:52
@tarzanek the server is underutilized, these small games won't help

**Comment by ratcashdev** [comment] 2019-11-19 16:06
@avi if I went to configs like 48/100 or 48/50 I was facing severe timeouts and the benchmark never finished. That's how I settled with 16/50. 
If it's underutilized, why are we getting 4s 99th latency and countless write timeouts (check the first post)?
> compaction_enforce_min_threshold: true
did not help in any meaningful way.

**Comment by avikivity** [comment] 2019-11-19 16:09
Maybe you're stressing one shard at a time, leaving the others idle. Is the data well distributed at the time you push it?

Can you make the monitor (prometheus/grafana) publicly available?

**Comment by ratcashdev** [comment] 2019-11-19 16:13
> Can you make the monitor (prometheus/grafana) publicly available?
publicly not, working on getting the data to you.

I though that this image clarified shard distribution:
https://user-images.githubusercontent.com/2928922/69054456-e6200e80-0a0b-11ea-83fc-40d80ed81390.png

**Comment by avikivity** [comment] 2019-11-19 16:18
There are plenty more metrics that can be looked at.

**Comment by tarzanek** [comment] 2019-11-19 16:27
I agree on getting the prometheus data, especially since you have the shard aware driver now.
I also expect overloaded shard(s) which would point out to a hot partition.
You can trace slow queries in scylla - https://docs.scylladb.com/using-scylla/tracing/#slow-query-logging - which might give us an idea what type of queries (ev. PKs) are getting queued, since you have 3 keyspaces and 9 tables, we will be able to go down to the ones that take a long time (yes, we might get red herrings, but I don't expect them in the case of not fully loaded server)

**Comment by ratcashdev** [comment] 2019-11-21 15:42
@tarzanek data uploaded: b32d33b9-9d7a-4380-95d6-508914e58ed8

**Comment by ratcashdev** [comment] 2019-11-26 09:46
@tarzanek Hi! Have you managed to dig something of value out of the prometeus data?

**Comment by tarzanek** [comment] 2019-11-26 12:48
hi @ratcashdev not yet, I still suspect a hot partition though and that means you are overloading one(or more) shards (which is partially visible from the graphs you pasted)
I am wondering if you could make the PK for open* tables a bit more distributed - or add a clustering key - but then I don't know what value from all your columns in open* tables could make the distribution even better - would you be able to add one(two?) more value(s) to the PK?

since you have the shard driver, you can already target proper shards (so first it goes by token to proper machine, then it goes by shard to proper shard), it means that the only thing left is to distribute the data in a better way, this should save you time compared to cassandra, which has to assign a shard once the request arrives, while you should be able to write to all proper shards directly from client

**Comment by tarzanek** [comment] 2019-11-26 12:50
above hypothesis would kinda cover Avis comments too about client not going full speed, since if client sends all data for some shards and then just sits ducks on leftover shard or two that has hot partition, then it's obviously not optimal (where cassandra leverages the freed up coordinators at the same time)

**Comment by ratcashdev** [comment] 2019-11-26 13:45
The PK is kind of a difficult topic. We need to return ranges (e.g. 'Last N'), which would become almost impossible to do if we made the PK more complex.
We discussed the possibility to do synthetic shards (https://medium.com/@foundev/synthetic-sharding-in-cassandra-to-deal-with-large-partitions-2124b2fd788b, approach No1) but that would mean that the client would have to track every single shard, its count and the exact way how the data-model and the DB maps PK to shards. This way it would get exposed too much to implementation details.

**Comment by ratcashdev** [comment] 2019-11-26 13:47
Also interesting to see the network bandwidth utilized by Scylla and C* (same HW setup in both cases), yet the overall time to complete the load is pretty much the same (or slightly worse for Scylla):
![image](https://user-images.githubusercontent.com/2928922/69638779-a8e6fc80-105b-11ea-88a1-32dfbdba5044.png)

**Comment by avikivity** [comment] 2019-11-26 13:50
I don't recomment synthetic sharding, it usually creates trouble down the road.

**Comment by ratcashdev** [comment] 2019-11-26 13:54
If synthetic sharding is not recommended, I wonder what solution could be used to keep partition sizes down and avoid hotspots, yet still able to deliver `Last N` types of queries in real-time?

**Comment by avikivity** [comment] 2019-11-26 14:43
It looks like shards 0, 14, and 15 are hot. What's the total number of partitions you have? Looks like quite a small number.

I can't make data model recommendations without understanding the problem you are trying to solve.

**Comment by ratcashdev** [comment] 2019-11-26 15:32
Context:
* Orders (open as well as closed, historical) stored in C*.
  * open orders are updated heavily, involve lots of tombstones
* Single source (app or server) of all the modify operations
  * Retail clients do 1 operation / month. Maybe even less.
  * Corporate clients may do hundreds of NewOrder/CancelOrder operations / sec on selected markets based on market conditions. Some are more active than others
* Lots of sources for read operations
  * We need to be able to efficiently do 'Last N' or 'Range' or 'Paged' types of queries based in real time for any (or combination) of the following: market, account, time-frame

It seems it is difficult to pick a universal partition size (and PK). It's either too big for Corporate (e.g. > 100MB) or too small for Retail (would require reading several dozens of partitions to return the required range of data). Also we're hitting hotspots, as you pointed out with the Corporates.

**Comment by avikivity** [comment] 2019-11-26 19:31
You can safely exceed 100MB partitions.

Make sure your clustering keys are sorted in the direction that makes your LIMIT queries pick the front of the partition (reverse the sort order so that last N is really first N).

How many partitions do you have?

**Comment by ratcashdev** [comment] 2019-11-28 08:24
@avikivity 100MB is (used to be?) quoted as a magical limit for partition size in C* beyond which one will start getting performance issues. Not sure if still applies, and apparently you say it does not apply to Scylla. Is there a different limit in Scylla?

**Comment by ratcashdev** [comment] 2019-11-28 08:41
BTW: seems interesting that a single Scylla node (RF:1, same HW, using Logged Batches, std C* driver) was able to finish the data-set 2.5x faster, than a 5 node Scylla cluster (identical HW for nodes, RF:3, scylla driver, no batches)

**Comment by avikivity** [comment] 2019-11-28 10:13
> @avikivity 100MB is (used to be?) quoted as a magical limit for partition size in C* beyond which one will start getting performance issues. Not sure if still applies, and apparently you say it does not apply to Scylla. Is there a different limit in Scylla?

There is no one limit (I know this isn't a good answer), it really depends on what you are doing. We routinely test >10GB partitions. What's important is that we never read an entire partition into memory (so long as you don't do silly things like disable paging).

> PS: it seems we have approx 900 partitions in this data-set.

That is way too few. Your 5-node system has 5*16 shards = 80 shards, so ~11 partitions/shard. Together with vnodes, you're bound to have bad distribution.

Is this an artifact of your test data, or is it representative of real life workloads?

**Comment by avikivity** [comment] 2019-11-28 10:14
> BTW: seems interesting that a single Scylla node (RF:1, same HW, using Logged Batches, std C* driver) was able to finish the data-set 2.5x faster, than a 5 node Scylla cluster (identical HW for nodes, RF:3, scylla driver, no batches)

That's an indication that the workload doesn't have enough concurrency. RF=3 has higher latency than single-node.

Also, don't use batches unless you really have to. They negate the functionality of the token and shard aware driver, and impose extra work on the server.

**Comment by avikivity** [comment] 2019-11-28 10:15
Anyway, I'm closing this as it's clear now this isn't a bug. If you need assistance with data modeling, please use the user mailing list or slack channel.

**Closed by avikivity** 2019-11-28 10:15 UTC

**Comment by ratcashdev** [comment] 2019-11-28 11:10
> Is this an artifact of your test data, or is it representative of real life workloads?

This is a limited data set. I expect the number of partitions to grow by orders of magnitude over time, but that should happen proportional to the number of clients.

**Comment by ratcashdev** [comment] 2019-11-28 11:15
> Anyway, I'm closing this as it's clear now this isn't a bug. If you need assistance with data modeling, please use the user mailing list or slack channel.

I am fine with that. However, I don't think anyone said it's a bug. The central point was that with the same data-set and model, like for like HW, C* was, in this specific case, faster. What more, it's even faster on cheaper HW.
My only conclusion is that Scylla is more sensitive to certain modelling deficiencies (or real-world data distributions), than Cassandra. Blindly replacing C* may not yield the advertised benefits.

**Comment by avikivity** [comment] 2019-11-28 11:26
> > Anyway, I'm closing this as it's clear now this isn't a bug. If you need assistance with data modeling, please use the user mailing list or slack channel.
> 
> I am fine with that and thank you for all the provided insight.
> Bug or not, the central point was that with the same data-set and model, like for like HW, C* was, in this specific case, faster. What more, it's even faster on cheaper HW.
> My only conclusion is that Scylla is more sensitive to certain modelling deficiencies (or real-world data distributions), than Cassandra. Blindly replacing C* may not yield the advertised benefits. YMMV.

The conclusion is correct, it's impossible to be better in every single case. We try to be better in the cases that matter: where you have lots of partitions and where you have reasonable good distribution (if you don't, Cassandra will fail too, just at a larger number of nodes).

**Comment by paulpaul1076** [comment] 2024-06-02 21:11
I also ran a benchmark which inserted data into this table:

```
CREATE TABLE IF NOT EXISTS test_keyspace.table_name (
          id bigint,
          artistvec frozen<list<bigint>>,
          artistvec2 frozen<list<bigint>>,
          PRIMARY KEY (id)
        ) with compression = {'sstable_compression': 'LZ4Compressor', 'chunk_length_in_kb': 4}
```

which is in this keyspace:

```
create keyspace if not exists test_keyspace with replication = {'class': 'SimpleStrategy', 'replication_factor': '3'}
```

I was using LOCAL_QUORUM.

And Cassandra was 2.5 times faster than scylla. On scylla's website when you read different comparison articles where scylla is compared to cassandra, they make it seem like scylla will blow cassandra out of the water, but I guess it's all marketing.

**Comment by dorlaor** [comment] 2024-06-02 21:36
On Mon, Jun 3, 2024 at 12:11 AM Perfect Stranger ***@***.***>
wrote:

> I also ran a benchmark which inserted data into this table:
>
> CREATE TABLE IF NOT EXISTS test_keyspace.table_name (
>           id bigint,
>           artistvec frozen<list<bigint>>,
>           artistvec2 frozen<list<bigint>>,
>           PRIMARY KEY (id)
>         ) with compression = {'sstable_compression': 'LZ4Compressor', 'chunk_length_in_kb': 4}
>
> which is in this keyspace:
>
> create keyspace if not exists test_keyspace with replication = {'class': 'SimpleStrategy', 'replication_factor': '3'}
>
> I was using LOCAL_QUORUM.
>
> And Cassandra was 2.5 times faster than scylla. On scylla's website when
> you read different comparison articles where scylla is compared to
> cassandra, they make it seem like scylla will blow cassandra out of the
> water, but I guess it's all marketing.
>

It should. Good benchmarking should also provide details and identify a
bottleneck.
Scylla assumes it will own all of the cores it runs on, don't share them.
There
are special instructions if you run in a container.

We also have a scylla_setup script, that tests the host and calculates the
disk
performance in order not to queue in the disk (but in the DB itself). Make
sure
you run it. You can then share the results of it - io.conf.

Lastly, make sure you use uniform distribution and you don't load a single
shard
while the others are idle. Scylla has a good monitoring stack, use it.

Let's work to max out the perf and identify the bottleneck

**Comment by paulpaul1076** [comment] 2024-06-02 22:02
@dorlaor 

I ran scylla on the same hosts as cassandra. I literally uninstalled cassandra via `apt remove` and installed scylla on the same machines.

I ran the aforementioned `scylla_setup` script. I didn everyting that was mentioned here: https://opensource.docs.scylladb.com/stable/getting-started/install-scylla/install-on-linux.html

The bottleneck was the CPU, for some reason it was maxed out on each host. When I ran the same benchmark against cassandra CPU load was at 40%.

**Comment by dorlaor** [comment] 2024-06-02 22:12
On Mon, Jun 3, 2024 at 1:03 AM Perfect Stranger ***@***.***>
wrote:

> @dorlaor <https://github.com/dorlaor>
>
> I ran scylla on the same hosts as cassandra. I literally uninstalled
> cassandra via apt remove and installed scylla on the same machines.
>
> I ran the aforementioned scylla_setup script. I didn everyting that was
> mentioned here:
> https://opensource.docs.scylladb.com/stable/getting-started/install-scylla/install-on-linux.html
>
> The bottleneck was the CPU, for some reason it was maxed out on each host.
> When I ran the same benchmark against cassandra CPU load was at 40%.
>

Were all cores equally loaded?
What's the size of the list and the sizes of the objects? Is it reads or
writes?
It's pretty unusual, worth to get to the bottom of it
If you can share the perf -C one-of-the-cores-at-100% dump it would be
helpful

**Comment by paulpaul1076** [comment] 2024-06-02 22:23
@dorlaor 

Yes, they were almost all equally loaded.

Each list contains 100 bigints.

I am sorry I don't have the time to investigate this. 

What I can do is send you the gatling project I used to benchmark both cassandra and scylla if you want to investigate on your own.

**Comment by paulpaul1076** [comment] 2024-06-03 00:55
Interestingly, after reinstalling cassandra again, now it's 4 times faster than scylla. It seems like scylla_setup configured very optimal settings.

**Comment by dorlaor** [comment] 2024-06-03 09:31
> Interestingly, after reinstalling cassandra again, now it's 4 times faster than scylla. It seems like scylla_setup configured very optimal settings.

:) Scylla configures the nics, the kernel and some other items. We cancel read ahead, so it's not necessary
good for Cassandra but nice it helped it..

Please share with me the links to run the benchmark, we'll try to see what's the issue. Could be
that frozen list isn't optimized. I wonder too whether there are batches that may slow us down, weird. It's considered a bug

**Comment by paulpaul1076** [comment] 2024-06-06 21:36
@dorlaor I will send you the archive with code in slack, can't send it here, the file is too large.
