### ISSUE TITLE
Infinite paging while querying secondary index

### ISSUE THREAD

**Issue by matkam** [scylladb/scylla#4127] opened 2019-01-22 19:47 UTC
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [x] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash): 3.0
Cluster size: 3
OS (RHEL/CentOS/Ubuntu/AWS AMI): Ubuntu 16.04

I had experimental features enabled on Scylla 2.3. Since upgrading to Scylla 3.0 from 2.3, querying an indexed column (through materialized view) causes infinite paged results:
```
cqlsh> SELECT count(*) FROM my.users  WHERE indexed_column = 'xxxx' ;

count
-------
    1

---MORE---
count
-------
    1

---MORE---
count
-------
    1

---MORE---
```
The workaround was to drop and recreate the secondary index:
```
DROP INDEX my.users_indexed_column_idx ;
CREATE INDEX users_indexed_column_idx ON my.users (indexed_column);
```

**Comment by duarten** [comment] 2019-01-22 20:20
It's puzzling how re-creating the index made the issue go away, since the data will be the same, and so will the code that performs the read.

As for the original issue, I also don't understand how that could happen. 

@psarna @nyh any thoughts?

**Comment by nyh** [comment] 2019-01-22 21:58
What I find really strange here is that the top-level query is a "SELECT COUNT(*)", and that should only result in one count, and that's it. I can understand how bugs in secondary-indexes might cause this count to be wrong, but how could it cause the count itself to be repeated? Why would Scylla report to cqlsh that the single count it sent was only a partial page, and there are more pages to be read, and how does reading more pages produce the same count over and over? Really odd....

@matkam is this error something you can reproduce, or something which only happened once and now (after you recreated the index) can't be reproduced?

**Comment by matkam** [comment] 2019-01-22 22:41
@nyh I tested maybe 3 or 4 different indices. Most would page forever, though I saw one with only 2 pages for a count:
```
cqlsh> select count(*) from keyspace.table where indexed_column = 'xxx';

 count
-------
     1

---MORE---
 count
-------
     0

(2 rows)
```

Since recreating the indices a few hours ago, I'm not seeing the problem. But it might be possible to reproduce this bug by creating an index on Scylla version earlier than 2.3, then upgrading to 3.0.

**Comment by psarna** [comment] 2019-01-23 08:07
I tried various combinations of indexing and paging on master (dbc1894bd59cf50239ad97bf06c51ce47efe1257) and couldn't reproduce either.

**Comment by duarten** [comment] 2019-01-23 11:07
We should try to repro by going the upgrade path, and take a core dump to understand what's going on. I have no idea what could cause this, though.

**Comment by slivne** [comment] 2019-01-24 10:56
We have done an upgrade of a single node with MV's and some data  using docker from 2.3.2 to 3.0.1 and where not able to reproduce the issue 

```
create keyspace ks WITH replication = {'class': 'SimpleStrategy', 'replication_factor' : 1};
use ks;
CREATE TABLE buildings (     name text,     city text,     built int,     meters int,     PRIMARY KEY (name) );
CREATE MATERIALIZED VIEW building_by_city AS         SELECT * FROM buildings         WHERE city IS NOT NULL         PRIMARY KEY(city, name);
insert INTO buildings (name, city, built, meters) values ('a','a',1,1);
insert INTO buildings (name, city, built, meters) values ('b','b',1,1);
insert INTO buildings (name, city, built, meters) values ('aa','a',2,2);
insert INTO buildings (name, city, built, meters) values ('bb','b',2,2);
insert INTO buildings (name, city, built, meters) values ('c','c',1,1);
```

**Comment by slivne** [comment] 2019-01-24 10:58
@matkam 
- did you have the issue during the rolling upgrade (some nodes on 2.3 and some on 3.0) or after all have been upgraded to 3.0 ?
- are you using the cqlsh shipped with scylla ?

**Comment by nyh** [comment] 2019-01-24 12:45
@slivne please note that the original report involved a secondary index, not a materialized view like you tried. And he counted the number of rows matching a particular index query - not all the rows.

**Comment by slivne** [comment] 2019-01-24 12:47
you are right ... missed that. will retry.

**Comment by slivne** [comment] 2019-01-24 12:56
I did the same drill with docker 2.3.2 --> 3.0.1

with
```
create keyspace ks WITH replication = {'class': 'SimpleStrategy', 'replication_factor' : 1};
use ks;
CREATE TABLE buildings (     name text,     city text,     built int,     meters int,     PRIMARY KEY (name) );
create index buildins_by_city on buildings (city);

insert INTO buildings (name, city, built, meters) values ('a','a',1,1);
insert INTO buildings (name, city, built, meters) values ('b','b',1,1);
insert INTO buildings (name, city, built, meters) values ('aa','a',2,2);
insert INTO buildings (name, city, built, meters) values ('bb','b',2,2);
insert INTO buildings (name, city, built, meters) values ('c','c',1,1);

select count(*) from buildings where city='a';

```

and it worked ok ... so still I can't reproduce

**Comment by matkam** [comment] 2019-01-24 17:31
Sounds like this might be a more elusive issue, involving more than just an upgrade. So here are some more details:

Started with 3 nodes of Scylla 2.3 configured with GossipPropertyFileSnitch in data center "datacenter1", and a replication factor of 2 for my keyspaces:
```
ALTER KEYSPACE my_keyspace WITH replication = {'class': 'NetworkTopologyStrategy', 'datacenter1': '2', 'datacenter2': '0'} AND durable_writes = true;
```

I had added another Scylla 2.3 data center with 3 nodes. I upgraded all the nodes successfully to Scylla 3.0. I then set replication factor to 2 for both data centers:
```
ALTER KEYSPACE my_keyspace WITH replication = {'class': 'NetworkTopologyStrategy', 'datacenter1': '2', 'datacenter2': '2'} AND durable_writes = true;
```

I ran `nodetool repair` on one of the new nodes and noticed some network issues. The VPN bridge could not handle the bandwidth between my two cloud data centers, and the connection between the two Scylla data centers would intermittently disconnect and reconnect.

So, I brought down all the nodes in the new data center, then force removed them using `nodetool removenode`, then changed the replication factor to 0 for the removed data center:
```
ALTER KEYSPACE my_keyspace WITH replication = {'class': 'NetworkTopologyStrategy', 'datacenter1': '2', 'datacenter2': '0'} AND durable_writes = true;
```

I started noticing problems querying the secondary index after this whole ordeal. Unfortunately I didn't test things right after the upgrade to 3.0.

To answer your questions above, @slivne I did not have any trouble during the upgrade itself. I did use cqlsh that came with Scylla, along with cqlsh from Cassandra, and gocql.

Thanks for looking into this!

**Comment by nyh** [comment] 2019-06-19 14:04
Another issue which might be related: #4569 ?

**Comment by vladzcloudius** [comment] 2020-02-03 20:47
@nyh @eliransin ping

**Comment by vladzcloudius** [comment] 2020-02-13 00:11
@eliransin ping

**Comment by slivne** [comment] 2020-03-24 22:01
The read path for scans has changed a lot since this issue was created. 

We cache the readers (and have fixed multiple issues around this).

I am closing this issue - if there is another issue like this - please open a new issue and provide the relevant information

**Closed by slivne** 2020-03-24 22:01 UTC
Labels: Backport 3.0, bug, sec-index
