### ISSUE TITLE
base_table_name='users' FROM system_schema.views:  [Server error] message="Not implemented: INDEXES">

### ISSUE THREAD

**Issue by abvgedeika** [scylladb/scylla#2429] opened 2017-05-29 15:02 UTC
*Installation details*
Scylla version (or git commit hash):https://github.com/scylladb/scylla/commit/de70d942a914e2f8c846604124c160ca1e385dd5

with experimental = True the following query works fine:
"SELECT * FROM system_schema.views WHERE keyspace_name='ks' ALLOW FILTERING"
but doesn't work with  base_table_name='users'
```
"SELECT * FROM system_schema.views WHERE keyspace_name='ks' AND base_table_name='users' ALLOW FILTERING"

ServerError: <Error from server: code=0000 [Server error] message="Not implemented: INDEXES">
```
In C* the last query is OK

**Comment by duarten** [comment] 2017-05-29 16:51
This is a duplicate of #2025.

**Closed by duarten** 2017-05-29 16:51 UTC
