### ISSUE TITLE
min/max/count on primary index field times out within a partition

### ISSUE THREAD

**Issue by cc32d9** [scylladb/scylla#4484] opened 2019-05-08 08:26 UTC
in the following schema,

```
CREATE TABLE actions
 (
 block_num         BIGINT,
 block_time        TIMESTAMP,
 trx_id            ASCII,
 global_action_seq BIGINT,
 parent            BIGINT,
 contract          ASCII,
 action_name       ASCII,
 receiver          ASCII,
 PRIMARY KEY (block_num, global_action_seq, receiver)
 );


CREATE INDEX actions_trx_id ON actions (trx_id);

CREATE MATERIALIZED VIEW receiver_bloks AS
    SELECT receiver, block_num, block_time, trx_id, global_action_seq, parent, contract, action_name
    FROM actions
    WHERE receiver IS NOT NULL AND global_action_seq IS NOT NULL AND block_num IS NOT NULL
    PRIMARY KEY (receiver, block_num, global_action_seq)
    WITH CLUSTERING ORDER BY (block_num DESC);
```

some receivers have huge number of rows, so some partitions in `receiver_blocks` are multiple gigabytes.

But I'm expecting simple Btree operations within a partition to work well, especially min and max are quick operations on a Btree index.

However, they timeout:

```
cqlsh:eosidx> select count(*) from receiver_bloks where receiver='eosbetdice11';
OperationTimedOut: errors={'127.0.0.1': 'Client request timeout. See Session.execute[_async](timeout)'}, last_host=127.0.0.1
cqlsh:eosidx> select min(block_num)  from receiver_bloks where receiver='eosbetdice11';
OperationTimedOut: errors={'127.0.0.1': 'Client request timeout. See Session.execute[_async](timeout)'}, last_host=127.0.0.1
cqlsh:eosidx> select max(block_num)  from receiver_bloks where receiver='eosbetdice11';
OperationTimedOut: errors={'127.0.0.1': 'Client request timeout. See Session.execute[_async](timeout)'}, last_host=127.0.0.1
```
Simple select works fine, and it starts from the highest block as specified in view definition:

```
cqlsh:eosidx> select * from receiver_bloks where receiver='eosbetdice11' limit 5;

 receiver     | block_num | global_action_seq | action_name | block_time                      | contract     | parent     | trx_id
--------------+-----------+-------------------+-------------+---------------------------------+--------------+------------+------------------------------------------------------------------
 eosbetdice11 |  28245166 |        1925810663 |  resolvebet | 2018-11-22 08:54:33.000000+0000 | eosbetdice11 |          0 | 524d3e444b1a6f2828072b91c9f4329713bde3811ab5967fd00af4cae190e24e
 eosbetdice11 |  28245166 |        1925810664 |    transfer | 2018-11-22 08:54:33.000000+0000 |  eosio.token | 1925810663 | 524d3e444b1a6f2828072b91c9f4329713bde3811ab5967fd00af4cae190e24e
 eosbetdice11 |  28245166 |        1925810665 |    transfer | 2018-11-22 08:54:33.000000+0000 |  eosio.token | 1925810664 | 524d3e444b1a6f2828072b91c9f4329713bde3811ab5967fd00af4cae190e24e
 eosbetdice11 |  28245166 |        1925810666 |    transfer | 2018-11-22 08:54:33.000000+0000 |  eosio.token | 1925810664 | 524d3e444b1a6f2828072b91c9f4329713bde3811ab5967fd00af4cae190e24e
 eosbetdice11 |  28245166 |        1925810667 |    transfer | 2018-11-22 08:54:33.000000+0000 | betdividends | 1925810663 | 524d3e444b1a6f2828072b91c9f4329713bde3811ab5967fd00af4cae190e24e
```

**Comment by cc32d9** [comment] 2019-05-08 08:33
Changing the order times out as well:
```
cqlsh:eosidx> select * from receiver_bloks where receiver='eosbetdice11' order by block_num asc limit 5;
ReadTimeout: Error from server: code=1200 [Coordinator node timed out waiting for replica nodes' responses] message="Operation timed out for eosidx.receiver_bloks - received only 0 responses from 1 CL=ONE." info={'received_responses': 0, 'required_responses': 1, 'consistency': 'ONE'}
```

**Comment by cc32d9** [comment] 2019-05-08 08:33
Scylla version 3.0.6

**Comment by cc32d9** [comment] 2019-05-08 08:42
Partition size is 1.6GB, and growing:
```
May 08 03:11:19 x21 scylla[48427]:  [shard 7] large_partition - Writing large row eosidx/receiver_bloks:eosbetdice11 (1624120188 bytes)
```

**Comment by nyh** [comment] 2019-05-08 09:15
There is no way to implement a `count(*)` operation without reading the entire partition. Note that Scylla doesn't use a B-Tree it uses LSM, i.e., the partition's data may come from multiple separate SSTables, which may have the same or different rows for this partition, and we can't know all of this without reading all the data.

But I think that you're right about `min()` and `max()` of a clustering key (as in your use case) - these indeed could be done more efficiently. But it would NOT be trivial: The partition's promoted index (see https://github.com/scylladb/scylla/wiki/SSTables-Index-File) indeed holds the first and last clustering key for each of the sstables. We *could* take the minimum and maximum of those from all SSTables. But the result will not necessarily be correct, because the first or last clustering key may actually be deleted rows (tombstones), so this will not be the first or last live row. So we will need to read a bit from the beginning of the partition, as well as one or more chunks of its end - before we can figure out the correct first and last clustering key. But you're right that in the common case, we wouldn't need to read the entire partition.

**Comment by denesb** [comment] 2019-05-08 09:17
Also note that flipping the clustering order is not recommended. As per the current implementation this necessitates reading the entire partition into memory, which, for 1 multi GB partition is problematic.

**Comment by cc32d9** [comment] 2019-05-08 09:27
Thanks. So basically I need a new table that keeps first occurrences of data for each recipient, then I will have the min values.

**Comment by avikivity** [comment] 2019-05-08 09:30
Closing, expected behavior.

**Closed by avikivity** 2019-05-08 09:30 UTC

**Comment by nyh** [comment] 2019-05-08 10:32
@avikivity I'm not sure that "expected behavior" is the right conclusion here. As I pointed out above, we could have implemented min() and max() of a clustering key more efficiently (it wouldn't be a trivial implementation, but it could be done, I believe).
