### ISSUE TITLE
scylladb - query fails for secondary index keys with "varchar" types

### ISSUE THREAD

**Issue by senthilrag** [scylladb/scylla#3839] opened 2018-10-10 15:36 UTC
Please answer these questions before submitting your issue. Thanks!

What version of Cassandra are you using?
cqlsh> SHOW VERSION
[cqlsh 5.0.1 | Cassandra 3.0.8 | CQL spec 3.3.1 | Native protocol v4]

What version of Gocql are you using?
Latest from the github. Did a go get on github path.

What did you do?
Create secondary index table of which one key is "varchar".

What did you expect to see?
Select to go through

What did you see instead?
&{{{132 0 192 0 344 []} 0 marshaling error: read_simple_exactly - size mismatch (expected 8, got 12) Backtrace: 0x7a31e8
0x13463e4
0x1346f20
0x223ca29
0x25f6958
0x2601d1f
0x25efad1
0x1eb666c
0x1ee5f19
0x5873a6
0x587561
0x652447
0x673fc2
0x72f96d
/lib/x86_64-linux-gnu/libpthread.so.0+0x76b9
/lib/x86_64-linux-gnu/libc.so.6+0x10741c
} 0 {0 [] [] 0 0} 0 0xc42029c160 0xc420212420 0}
running query...
panic: failed to load block
Describe your Cassandra cluster
3 node single datacenter cluster

please provide the following information

output of nodetool status
ubuntu@labs39:~$ nodetool status
Datacenter: datacenter1
=======================
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
-- Address Load Tokens Owns Host ID Rack
UN 172.25.236.37 752.13 KB 256 ? 1d289622-eada-4869-9bcf-77612d33eac6 rack1
UN 172.25.236.39 3.35 MB 256 ? dffa2d47-0ca3-4dd1-938e-82bc7360669b rack1
UN 172.25.236.38 688.93 KB 256 ? 69732bae-5305-4bbe-afd0-e5e149544e7b rack1

output of SELECT peer, rpc_address FROM system.peers
172.25.236.39
cqlsh> SELECT peer, rpc_address FROM system.peers
... ;

peer | rpc_address
---------------+---------------
172.25.236.38 | 172.25.236.38
172.25.236.37 | 172.25.236.37

(2 rows)
cqlsh>

rebuild your application with the gocql_debug tag and post the output
scylla_sec_idx.txt

notice if clustering key(in attached scylla_sec_idx.txt/go file) limited from
PRIMARY KEY (mkey,mid, mhash)
to
PRIMARY KEY (mkey, mhash)
the problem goes away. just thought to share in case it helps.
[scylla_sec_idx.txt](https://github.com/scylladb/scylla/files/2465380/scylla_sec_idx.txt)

**Comment by denesb** [comment] 2018-10-11 06:09
Can you please resolve the backtrace? See instructions [here](https://github.com/scylladb/scylla/wiki/How-to-resolve-backtrace#resolve-backtraces-for-scylla--21).

**Comment by senthilrag** [comment] 2018-10-11 14:39
scylla --version
2.3.0-0.20180917.178f870a0

cloned the bug from gocql over here. Please find the attachment which you can rename to .go and reproduce the issue.

**Comment by duarten** [comment] 2018-10-11 14:55
I can't repro it on master. Secondary indexes are experimental and still
under development, and there have been many fixes since 2.3.

The good news is that they will be GA in 2
3.0, which is just around the corner.

**Comment by senthilrag** [comment] 2018-10-11 15:48
here is the backtrace resolved:

ubuntu@labs39:~$ /home/ubuntu/seastar-addr2line -e /usr/bin/scylla -f backtrace.txt
[Backtrace #0]
std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(char const*, std::allocator<char> const&) at ??:?
std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::operator=(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&&) at ??:?
std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::operator=(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&&) at ??:?
std::istreambuf_iterator<char, std::char_traits<char> >::operator++() at ??:?
std::istreambuf_iterator<char, std::char_traits<char> >::operator++() at ??:?
std::istreambuf_iterator<char, std::char_traits<char> >::operator++() at ??:?
std::istreambuf_iterator<char, std::char_traits<char> >::operator++() at ??:?
std::_Rb_tree<int, int, std::_Identity<int>, std::less<int>, std::allocator<int> >::_M_erase(std::_Rb_tree_node<int>*) at ??:?
std::_Rb_tree<int, int, std::_Identity<int>, std::less<int>, std::allocator<int> >::_M_erase(std::_Rb_tree_node<int>*) at ??:?
?? ??:0
?? ??:0
?? ??:0
?? ??:0
std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > std::operator+<char, std::char_traits<char>, std::allocator<char> >(char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) at ??:?
start_thread at ??:?
clone at /build/glibc-Cl5G7W/glibc-2.23/misc/../sysdeps/unix/sysv/linux/x86_64/clone.S:109

**Comment by slivne** [comment] 2018-10-14 10:11
we will soon have an 3.0.rc1 with which you can test this out

**Comment by slivne** [comment] 2018-11-15 10:47
@senthilrag we have released 3.0.rc1 - where you able to retest this , if not - can you please paste the schema its a bit easier then trying to modify your application

**Comment by slivne** [comment] 2018-11-25 11:46
@senthilrag ping

**Comment by senthilrag** [comment] 2018-11-26 15:30
Waiting to pick up another version of scylla before retesting this. Will keep posted.

**Comment by slivne** [comment] 2019-01-06 10:52
@senthilrag we have released 3.0.rc3 and and about to release 3.0.rc4 - can you please retests - I am pushing this out of 3.0 release - if there will not be any update I'll close

**Comment by slivne** [comment] 2019-02-05 13:21
closing this issue as there is no update

@senthilrag if you reproduce on 3.0.X - please comment and we will reopen.

**Closed by slivne** 2019-02-05 13:21 UTC
Labels: User Request, sec-index

**Comment by kharmabum** [comment] 2020-07-02 01:36
@senthilrag any tips on removing the index or restoring the cluster when this happens would be greatly appreciated. We added an index in our 3.3.0 dev cluster and are having trouble restoring the service.
