### ISSUE TITLE
CommitLog Not Honoring its Input Size

### ISSUE THREAD

**Issue by STRATZ-Ken** [scylladb/scylla#6148] opened 2020-04-07 11:48 UTC
It seems like my cluster is not honoring the limit sizes enforced by the config file.    

Example 1 : I left the default commit log size at `-1` upon investigation, I gave the commitlog disk 75GB of space.  I later found after a small bit of time, my commit log file drive size was at 100%.  How is it possible if my max RAM size is 35GB, that the commit log got over 75GB.

Example 2 : I set in the config a max commit log disk size of 30GB.  I am now seeing the same thing as example 1.

I do find, that if I `nodetool drain` and then restart `scylla-server` the entire drive free's up in space back to nearly nothing.

I did some debugging on the drive and there is commitlog files and recycled-commitlog files in the drive that consume 99% of the drive.

I reported this in slack and was informed to make a ticket here.

*Installation details*
Scylla version (or git commit hash): 3.3 Latest 
Cluster size: 1TB
OS (RHEL/CentOS/Ubuntu/AWS AMI): CentOS

*Hardware details (for performance issues)*          Delete if unneeded
Platform (physical/VM/cloud instance type/docker): VM - Centos 8.2
Hardware: vCPU: 14 memory=35000MB
Disks: (SSD/HDD, count) : 1 x SSD Commit Log, 4 x 6 TB HDD data storage

**Comment by STRATZ-Ken** [comment] 2020-04-15 11:47
Would anyone on the team have a suggestion on how to handle this temporary?  I am using Scylla in a production environment, but I just have two servers crash over night due to the commitlog/hints file directory usage.  I expanded to 250GB hard drives, in attempt to give it more time, but seems that still is not enough.

**Comment by elcallio** [comment] 2020-04-15 12:01
You can try disabling recycling of segments, which I suspect are not correctly respecting the disk limits, by setting the option:
`commitlog_reuse_segments: False`
in scylla.yaml.

**Comment by STRATZ-Ken** [comment] 2020-04-15 12:08
Thanks, I will give it a try, but is there anything I should worry about in backlash for setting this command?

**Comment by elcallio** [comment] 2020-04-15 12:18
It will cause all commitlog segments to be created new, instead of reused. This in turn will make writes slightly less performant. So, yes, you will get overall less commitlog throughput. 

However, I find it very strange that you should get recycled segment in any large excess over the set disk limit. While it is possible that you would get one or two segment extra, it should in general keep to the set max size. 

Can you provide the relevant parts of your scylla.yaml for the node? I.e. the commitlog settings.

**Comment by STRATZ-Ken** [comment] 2020-04-15 12:29
The only changes I make in the config file is basic settings.  Cluster Name, Data File Log Path, Password, etc.

**Comment by elcallio** [comment] 2020-04-15 12:36
I was under the impression that you had actively limited the commit log size? 
If no, then using recycling or not will probably not help at all. But you definitely have a problem somewhere, because it would seem that the machine is not managing to flush written data to actual sstables fast enough, and you instead get an ever increasing commit log size. 

I would then suggest setting something like: 
`commitlog_total_space_in_mb=10240`
for a max of 10GB commit log. (Feel free to vary the size)
This should instead put back pressure on the system, and probably make write respond slower, but it will most likely ensure data is in fact written to sstables. 

Again, really weird that you get such an imbalance in CL and sstable disk usage. Can you detail your workload etc, so we can maybe figure out why the system is not balancing better by itself?

**Comment by STRATZ-Ken** [comment] 2020-04-15 12:37
You are correct.

I do have `commitlog_total_space_in_mb=10240` set to 30GB.

**Comment by STRATZ-Ken** [comment] 2020-04-15 12:41
The workload consists of two tables.  

```
CREATE TABLE IF NOT EXISTS cjd_match.data (
	match_id bigint,
	pick_ban blob,
	networth blob,
	experience blob,
	radiant_kills blob,
	dire_kills blob,
	tower_status blob,
	lane blob,
	winrates blob,
	predicted_winrates blob,
	PRIMARY KEY (match_id)
) WITH 
    bloom_filter_fp_chance = 0.01
    AND caching = {'keys':'ALL', 'rows_per_partition':'NONE'}
    AND compaction = {'compaction_window_size': '14', 
    				  'compaction_window_unit': 'DAYS', 
    				  'class': 'org.apache.cassandra.db.compaction.TimeWindowCompactionStrategy'};

CREATE TABLE cjd_match.player (
    match_id bigint,
	steam_id bigint,
	level blob,
	kills blob,
	kill int,
	deaths blob,
	death int,
	assists blob,
	assist int,
	last_hit_min blob,
	last_hit int,
	gold_earn_min blob,
	gold_earn int,
	exp_earn_min blob,
	exp_earn int,
	heal_min blob,
	heal int,
	hero_damage_min blob,
	hero_damage int,
	tower_damage_min blob,
	tower_damage int,
	tower_damage_report blob,
	courier_kill blob,
	ward blob,
	item_purchase blob,
	item_used blob,
	all_talk blob,
	actions_min blob,
	action_report blob,
	invisible_sec int,
	location_report blob,
	farm_dis_report blob,
	rune blob,
	ability_cast_report blob,
	hero_damage_report blob,
	player_abilities blob,
	inventory_report blob,
	networth_per_min blob,
	campstack_per_min blob,
	buffs blob,
	deny_per_min blob,
	imp_per_min blob,
	trips_foun_per_min blob,
	spirit_bear_inventory blob,
    dota_plus_hero_xp int,
	PRIMARY KEY (match_id, steam_id)
) WITH 
    bloom_filter_fp_chance = 0.01
    AND caching = {'keys':'ALL', 'rows_per_partition':'NONE'}
    AND compaction = {'compaction_window_size': '14', 
    				  'compaction_window_unit': 'DAYS', 
    				  'class': 'org.apache.cassandra.db.compaction.TimeWindowCompactionStrategy'};
```

There is about 500 Million rows in `data` and about 5 billion rows in `player`

**Comment by elcallio** [comment] 2020-04-15 13:06
Then I am somewhat at a loss. Can you attach your full config (scylla.yaml - feel free to redact any sensitive info), and do a run with added `--logger-log-level commitlog=debug` and attach the logs as well? It might provide some insights.

**Comment by STRATZ-Ken** [comment] 2020-04-15 13:40
```

cluster_name: 'STRATZ'

num_tokens: 256


# Directory where Scylla should store data on disk.
data_file_directories:
   - /media/slot00/data

commitlog_sync: periodic
commitlog_sync_period_in_ms: 10000

commitlog_segment_size_in_mb: 32

# seed_provider class_name is saved for future use.
# seeds address(es) are mandatory!
seed_provider:
    # Addresses of hosts that are deemed contact points. 
    # Scylla nodes use this list of hosts to find each other and learn
    # the topology of the ring.  You must change this if you are running
    # multiple nodes!
    - class_name: org.apache.cassandra.locator.SimpleSeedProvider
      parameters:
          # seeds is actually a comma-delimited list of addresses.
          # Ex: "<ip1>,<ip2>,<ip3>"
          - seeds: "IP1,IP2"

listen_address: IP ADDRESS



native_transport_port: 9042


# How long the coordinator should wait for read operations to complete
read_request_timeout_in_ms: 5000

# How long the coordinator should wait for writes to complete
write_request_timeout_in_ms: 2000
# how long a coordinator should continue to retry a CAS operation
# that contends with other proposals for the same row
cas_contention_timeout_in_ms: 1000

endpoint_snitch: GossipingPropertyFileSnitch

rpc_address: IP ADDRESS
# rpc_interface: eth1
# rpc_interface_prefer_ipv6: false

# port for Thrift to listen for clients on
rpc_port: 9160

# port for REST API server
api_port: 10000

# IP for the REST API server
api_address: IP ADDRESS

# Log WARN on any batch size exceeding this value. 5kb per batch by default.
# Caution should be taken on increasing the size of this threshold as it can lead to node instability.
batch_size_warn_threshold_in_kb: 5

# Fail any multiple-partition batch exceeding this value. 50kb (10x warn threshold) by default.
batch_size_fail_threshold_in_kb: 50

experimental_features:
#     - cdc
    - lwt
#     - udf

partitioner: org.apache.cassandra.dht.Murmur3Partitioner

commitlog_total_space_in_mb: 30000
murmur3_partitioner_ignore_msb_bits: 12
api_ui_dir: /opt/scylladb/swagger-ui/dist/
api_doc_dir: /opt/scylladb/api/api-doc/

```

Attached is my YAML file. I removed anything that was commented out.

**Comment by eliransin** [comment] 2020-08-18 07:46
@elcallio I am guessing your commit doesn't close the issue because the commitlog can still exceed the limit, right?
@elcallio / @avikivity perhaps we should have a soft and hard limits. One is the target disk space and the other is the one which
waits for some space to be freed before writing to the commitlog. Is it easily doable?

**Comment by elcallio** [comment] 2020-08-18 07:51
@eliransin No, the limits are not hard limits. This is simply because I am not confident that imposing a hard commitlog limit will not freeze the system. Partially because all segments taking space are shared between column families, thus to remove one you might need to flush several CF:s, and there could be deadlocks hiding somewhere in that path. 
The patch sent encourages flushing "earlier" in cases where we are near the limits, but will not stop accepting incoming data.

**Comment by slivne** [comment] 2020-08-25 08:30
@avikivity / @tzach - we don't have code to make this a hard limit, I think that current setting of trying to meet the limit is good enough and the  configuration / metrics should be documented as such. If you are ok with that - we can update the wording around the config and also close this issue as wontfix

**Comment by avikivity** [comment] 2020-08-25 08:34
35GB -> 75GB is not a small overflow.

**Comment by slivne** [comment] 2020-08-25 09:04
thats without calle code ...

**Comment by eliransin** [comment] 2020-08-25 09:09
@slivne do we have some stats about how it is with calles code? IIUC once a node lags behind, you can get to any number of
an overflow the question is how fast you'll get there, no?
Maybe it is yet another kind of overload (space/memory) that we should consider? :slightly_smiling_face:

**Comment by avikivity** [comment] 2020-08-25 09:54
So then we should mark it as fixed, not won'tfix.

**Comment by slivne** [comment] 2020-09-03 10:56
After talking to calle - it seems we are expected to be aligned to what origin tries and do as well. 

So I am closing this as fixed.

**Comment by avikivity** [comment] 2020-11-29 12:59
Not sure if we need to backport this or not. @elcallio please advise.

@xemul has been tracking commitlog size overruns, maybe this is related.

**Comment by elcallio** [comment] 2020-11-30 09:16
No real opinion. Should not hurt, so maybe? But it makes (memtable->sstable) flushing somewhat more eager, so can change IO behaviour slightly.

**Comment by avikivity** [comment] 2020-11-30 14:52
I have a sudden fear of this commit, maybe it's responsible for #7575.

**Comment by elcallio** [comment] 2020-11-30 15:04
While I am ready to assume responsibility for most of the worlds evil, I am somewhat unsure to the correlation? The patch will try to force memtable flush potentially more often, at the expense of disk size growth, so it could potentially cause more sstable cpu+io usage. Which I guess could lead to more compactions. But from what I could see in the graphs in #7575 (probably wrong), the memtable IO did not seem to correlate to any drop in CL IO? 
Or do you mean that we simply moved data to disk and this causes queries to be inherently slower?

**Comment by elcallio** [comment] 2020-11-30 15:05
But the issue is about writes, no?

**Comment by avikivity** [comment] 2020-12-13 14:21
@elcallio I suspect that we stopped recycling or switched to append mode. Append + O_DSYNC = slow.

@kostja also say this (not 100% sure) implicated in LWT performance drop.

**Comment by avikivity** [comment] 2021-01-04 11:54
Reopening. We should make the limit a hard limit, not "try harder". This is because extending the commitlog requires double writes (prezero and the actual write), and therefore steals disk throughput from useful work. See #7794.

**Comment by elcallio** [comment] 2021-01-05 10:21
@avikivity making the limit hard has some naughty side-effects. potential high latency and/or write failures being the most obvious one. If the CL refuses to add a write because no segments are available we could potentially hit the write timeout while waiting for memtable flushes to complete and give us more space. Is this ok?

**Comment by avikivity** [comment] 2021-01-05 12:46
We have exactly the same problem when allocating memtable memory. We solved this by making memtable writes wait until memtable flush retired an equivalent amount of memory, so writes are self-pacing.

```c++
future<> database::apply_in_memory(const mutation& m, column_family& cf, db::rp_handle&& h, db::timeout_clock::time_point timeout) {
    return cf.dirty_memory_region_group().run_when_memory_available([this, &m, &cf, h = std::move(h)]() mutable {
        cf.apply(m, std::move(h));
    }, timeout);
}
```

what happens is that the throughput of apply_in_memory becomes equal to the throughput of the memtable flush.

This doesn't work for commitlog-triggered flushes (since there is no memory pressure, run_when_memory_available() returns immediately), but on the other hand, it also means the memtable is small compared to appending workloads. So I think we'll be fine. If it turns out to hurt, we can add the same feedback from memtable flush to commitlog.

**Comment by elcallio** [comment] 2021-01-05 13:14
Yeah, I get that. I am just saying that it is a behaviour change and that we might find that due to things like compaction etc hogging sstable IO you might see unexpected timeouts if CL size is strictly enforced.

**Comment by avikivity** [comment] 2021-01-06 11:11
Yes, we might need an explicit controller that connects admit rate into commitlog with retire rate from memtable flush.

**Comment by slivne** [comment] 2021-03-29 06:56
@elcallio your fix in 4082f57edc3e7764e11e9e858a0a8059981c6309 - placed a hard limit - what is missing to close this ?

**Comment by elcallio** [comment] 2021-03-29 08:12
Probably user or appropriate use case testing verifying that it now _does_ honour the size limit. I've verified it locally, but one should not trust dev. processes.

**Comment by slivne** [comment] 2021-04-04 15:36
QA will double check you - closing this

**Closed by slivne** 2021-04-04 15:36 UTC
Labels: Backport candidate, User Request, bug, commit-log, fixed

**Comment by mykaul** [comment] 2023-03-12 15:47
This issue perhaps should be reopened, as the commit was reverted, but for the time being I just removed the backport candidate label, as I don't think it's relevant anymore.
