### ISSUE TITLE
Segmentation fault during read/write workflow

### ISSUE THREAD

**Issue by juliayakovlev** [scylladb/scylla#3829] opened 2018-10-08 15:02 UTC
*Installation details*
Scylla version (or git commit hash): 666.development-0.20181007.b839f551c
Cluster size: 5 nodes
OS (RHEL/CentOS/Ubuntu/AWS AMI): ami-0b705281b4cd52622

Run longevity test using user profiles that creates materialized views and secondary indexes.
I found segmentation fault on the node 4. It happened before nemesis .

```
0x00000000006a79d2
0x00000000005bec5c
0x00000000005bef05
0x00000000005bef53
/lib64/libpthread.so.0+0x000000000000f6cf
/lib64/libc.so.6+0x0000000000155dd5
0x00000000036ce18c
0x0000000001f0b0ad
0x000000000059ffce
0x00000000005a0191
0x000000000066eac7
0x00000000006734ba
0x0000000000756b6d
/lib64/libpthread.so.0+0x0000000000007e24
/lib64/libc.so.6+0x00000000000febac
```

Decoded
```
void seastar::backtrace<seastar::backtrace_buffer::append_backtrace()::{lambda(seastar::frame)#1}>(seastar::backtrace_buffer::append_backtrace()::{lambda(seastar::frame)#1}&&) at /usr/src/debug/scylla-666.development/seastar/util/backtrace.hh:56
seastar::backtrace_buffer::append_backtrace() at /usr/src/debug/scylla-666.development/seastar/core/reactor.cc:410
 (inlined by) print_with_backtrace at /usr/src/debug/scylla-666.development/seastar/core/reactor.cc:431
seastar::print_with_backtrace(char const*) at /usr/src/debug/scylla-666.development/seastar/core/reactor.cc:438
sigsegv_action at /usr/src/debug/scylla-666.development/seastar/core/reactor.cc:4022
 (inlined by) operator() at /usr/src/debug/scylla-666.development/seastar/core/reactor.cc:4008
 (inlined by) _FUN at /usr/src/debug/scylla-666.development/seastar/core/reactor.cc:4004
?? ??:0
?? ??:0
managed_bytes::managed_bytes(managed_bytes const&) at /usr/src/debug/scylla-666.development/utils/managed_bytes.hh:257
 (inlined by) compound_wrapper<partition_key, partition_key_view>::compound_wrapper(compound_wrapper<partition_key, partition_key_view> const&) at /usr/src/debug/scylla-666.development/./keys.hh:165
 (inlined by) partition_key::partition_key(partition_key const&) at /usr/src/debug/scylla-666.development/./keys.hh:680
 (inlined by) seastar::shared_ptr_count_for<service::pager::paging_state>::shared_ptr_count_for<partition_key const&, std::experimental::fundamentals_v1::optional<clustering_key_prefix> const&, unsigned int, utils::UUID&, std::unordered_map<nonwrapping_range<dht::token>, std::vector<utils::UUID, std::allocator<utils::UUID> >, std::hash<nonwrapping_range<dht::token> >, std::equal_to<nonwrapping_range<dht::token> >, std::allocator<std::pair<nonwrapping_range<dht::token> const, std::vector<utils::UUID, std::allocator<utils::UUID> > > > > const&, std::experimental::fundamentals_v1::optional<db::read_repair_decision> const&>(partition_key const&, std::experimental::fundamentals_v1::optional<clustering_key_prefix> const&, unsigned int&&, utils::UUID&, std::unordered_map<nonwrapping_range<dht::token>, std::vector<utils::UUID, std::allocator<utils::UUID> >, std::hash<nonwrapping_range<dht::token> >, std::equal_to<nonwrapping_range<dht::token> >, std::allocator<std::pair<nonwrapping_range<dht::token> const, std::vector<utils::UUID, std::allocator<utils::UUID> > > > > const&, std::experimental::fundamentals_v1::optional<db::read_repair_decision> const&) at /usr/src/debug/scylla-666.development/seastar/core/shared_ptr.hh:466
 (inlined by) seastar::shared_ptr<service::pager::paging_state> seastar::shared_ptr_make_helper<service::pager::paging_state, false>::make<partition_key const&, std::experimental::fundamentals_v1::optional<clustering_key_prefix> const&, unsigned int, utils::UUID&, std::unordered_map<nonwrapping_range<dht::token>, std::vector<utils::UUID, std::allocator<utils::UUID> >, std::hash<nonwrapping_range<dht::token> >, std::equal_to<nonwrapping_range<dht::token> >, std::allocator<std::pair<nonwrapping_range<dht::token> const, std::vector<utils::UUID, std::allocator<utils::UUID> > > > > const&, std::experimental::fundamentals_v1::optional<db::read_repair_decision> const&>(partition_key const&, std::experimental::fundamentals_v1::optional<clustering_key_prefix> const&, unsigned int&&, utils::UUID&, std::unordered_map<nonwrapping_range<dht::token>, std::vector<utils::UUID, std::allocator<utils::UUID> >, std::hash<nonwrapping_range<dht::token> >, std::equal_to<nonwrapping_range<dht::token> >, std::allocator<std::pair<nonwrapping_range<dht::token> const, std::vector<utils::UUID, std::allocator<utils::UUID> > > > > const&, std::experimental::fundamentals_v1::optional<db::read_repair_decision> const&) at /usr/src/debug/scylla-666.development/seastar/core/shared_ptr.hh:629
 (inlined by) seastar::shared_ptr<service::pager::paging_state> seastar::make_shared<service::pager::paging_state, partition_key const&, std::experimental::fundamentals_v1::optional<clustering_key_prefix> const&, unsigned int, utils::UUID&, std::unordered_map<nonwrapping_range<dht::token>, std::vector<utils::UUID, std::allocator<utils::UUID> >, std::hash<nonwrapping_range<dht::token> >, std::equal_to<nonwrapping_range<dht::token> >, std::allocator<std::pair<nonwrapping_range<dht::token> const, std::vector<utils::UUID, std::allocator<utils::UUID> > > > > const&, std::experimental::fundamentals_v1::optional<db::read_repair_decision> const&>(partition_key const&, std::experimental::fundamentals_v1::optional<clustering_key_prefix> const&, unsigned int&&, utils::UUID&, std::unordered_map<nonwrapping_range<dht::token>, std::vector<utils::UUID, std::allocator<utils::UUID> >, std::hash<nonwrapping_range<dht::token> >, std::equal_to<nonwrapping_range<dht::token> >, std::allocator<std::pair<nonwrapping_range<dht::token> const, std::vector<utils::UUID, std::allocator<utils::UUID> > > > > const&, std::experimental::fundamentals_v1::optional<db::read_repair_decision> const&) at /usr/src/debug/scylla-666.development/seastar/core/shared_ptr.hh:647
 (inlined by) service::pager::query_pager::state() const at /usr/src/debug/scylla-666.development/service/pager/query_pagers.cc:382
operator() at /usr/src/debug/scylla-666.development/cql3/statements/select_statement.cc:962
 (inlined by) apply at /usr/src/debug/scylla-666.development/seastar/core/apply.hh:35
 (inlined by) apply<cql3::statements::read_posting_list(service::storage_proxy&, schema_ptr, schema_ptr, const secondary_index::index&, seastar::shared_ptr<cql3::restrictions::statement_restrictions>, const cql3::query_options&, int32_t, service::query_state&, gc_clock::time_point, seastar::lowres_clock::time_point, cql3::cql_stats&) [with KeyType = partition_key]::<lambda(std::unique_ptr<cql3::result_set>)>, std::unique_ptr<cql3::result_set, std::default_delete<cql3::result_set> > > at /usr/src/debug/scylla-666.development/seastar/core/apply.hh:43
 (inlined by) apply<cql3::statements::read_posting_list(service::storage_proxy&, schema_ptr, schema_ptr, const secondary_index::index&, seastar::shared_ptr<cql3::restrictions::statement_restrictions>, const cql3::query_options&, int32_t, service::query_state&, gc_clock::time_point, seastar::lowres_clock::time_point, cql3::cql_stats&) [with KeyType = partition_key]::<lambda(std::unique_ptr<cql3::result_set>)>, std::unique_ptr<cql3::result_set, std::default_delete<cql3::result_set> > > at /usr/src/debug/scylla-666.development/seastar/core/future.hh:1309
 (inlined by) operator()<seastar::future_state<std::unique_ptr<cql3::result_set, std::default_delete<cql3::result_set> > > > at /usr/src/debug/scylla-666.development/seastar/core/future.hh:963
 (inlined by) run_and_dispose at /usr/src/debug/scylla-666.development/seastar/core/future.hh:414
seastar::reactor::run_tasks(seastar::reactor::task_queue&) at /usr/src/debug/scylla-666.development/seastar/core/reactor.cc:2697
seastar::reactor::run_some_tasks() at /usr/src/debug/scylla-666.development/seastar/core/reactor.cc:3120
seastar::reactor::run_some_tasks() at /usr/src/debug/scylla-666.development/seastar/util/log.hh:313
 (inlined by) seastar::reactor::run() at /usr/src/debug/scylla-666.development/seastar/core/reactor.cc:3267
seastar::smp::configure(boost::program_options::variables_map)::{lambda()#3}::operator()() const at /usr/src/debug/scylla-666.development/seastar/core/reactor.cc:4336
std::function<void ()>::operator()() const at /opt/scylladb/include/c++/7/bits/std_function.h:706
 (inlined by) seastar::posix_thread::start_routine(void*) at /usr/src/debug/scylla-666.development/seastar/core/posix.cc:52
```
Info from coredumpctl:
```
           PID: 2116 (scylla)
           UID: 996 (scylla)
           GID: 1001 (scylla)
        Signal: 11 (SEGV)
     Timestamp: Mon 2018-10-08 10:01:01 UTC (4h 57min ago)
  Command Line: /usr/bin/scylla --blocked-reactor-notify-ms 1000 --log-to-syslog 1 --log-to-stdout 0 --default-log-level info --network-stack posix --io-properties-file=/etc/scylla.d/io_properties.yaml --cpuset 1-7,9-15
    Executable: /usr/bin/scylla
 Control Group: /
       Boot ID: c8bead6cd6684e05b525a43ad8683581
    Machine ID: df877a200226bc47d06f26dae0736ec9
      Hostname: ip-172-30-0-167.ec2.internal
       Message: Process 2116 (scylla) of user 996 dumped core.
                
                Stack trace of thread 2121:
                #0  0x00007f36edd9edd6 __memcpy_ssse3_back (libc.so.6)
                #1  0x00000000036ce18d _ZN13managed_bytesC4ERKS_ (scylla)
                #2  0x0000000001f0b0ae operator() (scylla)
                #3  0x000000000059ffcf _ZN7seastar7reactor9run_tasksERNS0_10task_queueE (scylla)
                #4  0x00000000005a0192 _ZN7seastar7reactor14run_some_tasksEv (scylla)
                #5  0x000000000066eac8 _ZN7seastar7reactor14run_some_tasksEv (scylla)
                #6  0x00000000006734bb _ZZN7seastar3smp9configureEN5boost15program_options13variables_mapEENKUlvE1_clEv (scylla)
                #7  0x0000000000756b6e _ZNKSt8functionIFvvEEclEv (scylla)
                #8  0x00007f36ee01de25 start_thread (libpthread.so.0)
                #9  0x00007f36edd47bad __clone (libc.so.6)
                
```

**Comment by psarna** [comment] 2018-10-09 08:42
I hope https://github.com/psarna/scylla/commit/4f78b47a6b317e88802761f31e25c3f30370e6da is the solution for this problem too, but I couldn't reproduce this failure locally, so the tests will verify.

**Comment by juliayakovlev** [comment] 2018-10-09 08:50
@psarna  Is the test log and access to the cluster may help you?

**Comment by psarna** [comment] 2018-10-09 08:52
@juliayakovlev yeah, it would help too. But the final verification would be running the test again when the fix is merged, and then seeing logs.

**Closed** 2018-10-09 17:37 UTC
Labels: bug, high, sec-index
