### ISSUE TITLE
scylla-jmx and scylla-tools-java are kept back when upgrading to 3.2

### ISSUE THREAD

**Issue by penberg** [scylladb/scylla#5933] opened 2020-03-02 10:49 UTC
I first installed Scylla 2.3 on Ubuntu 18.04, and then upgraded 2.3 → 3.0 → 3.1 → 3.2, but `scylla-jmx` and `scylla-tools-java` are kept at 3.1. However, when I _first_ install Scylla 3.1, the upgrade works fine.

```
root@1798369567a7:/# dpkg -l | grep scylla
ii  scylla                        3.2.2-0.20200222.0b23e7145d0-1      amd64        Scylla database metapackage
ii  scylla-conf                   3.2.2-0.20200222.0b23e7145d0-1      amd64        Scylla database main configuration file
ii  scylla-env                    1.3-ubuntu1~bionicppa1              all          language tool for constructing recognizers, compilers etc
ii  scylla-gcc73-gcc-7-base:amd64 7.3.0-3ubuntu2~bionicppa1           amd64        GCC, the GNU Compiler Collection (base package)
ii  scylla-gcc73-libatomic1       7.3.0-3ubuntu2~bionicppa1           amd64        support library providing __atomic built-in functions
ii  scylla-gcc73-libgcc1          1:7.3.0-3ubuntu2~bionicppa1         amd64        GCC support library
ii  scylla-gcc73-libstdc++6       7.3.0-3ubuntu2~bionicppa1           amd64        GNU Standard C++ Library v3
ii  scylla-jmx                    3.1.3-20200128.cc44686-1            all          Scylla JMX server binaries
ii  scylla-kernel-conf            3.2.2-0.20200222.0b23e7145d0-1      amd64        Scylla kernel tuning configuration
ii  scylla-python3                3.7.4-0.20200222.0b23e7145d0-1      amd64        A standalone python3 interpreter that can be moved around different Linux machines
ii  scylla-server                 3.2.2-0.20200222.0b23e7145d0-1      amd64        Scylla database server binaries
ii  scylla-tools                  3.2.2-20200222.725f25026ea-1        all          Scylla database tools
ii  scylla-tools-core             3.1.3-20200128.afb663faef-1         all          Scylla database tools core files
```

Upgrade log here:

```
root@1798369567a7:/# apt-get dist-upgrade scylla
Reading package lists... Done
Building dependency tree
Reading state information... Done
Calculating upgrade... Done
The following packages were automatically installed and are no longer required:
  hugepages libcrypto++6 libgnutlsxx28 libhugetlbfs0 libjsoncpp1 libmpdec2 libprotobuf10 libpython3-stdlib libpython3.6-minimal libpython3.6-stdlib
  libsnappy1v5 python-asn1crypto python-certifi python-cffi-backend python-chardet python-cryptography python-enum34 python-idna python-ipaddress
  python-openssl python-pkg-resources python-requests python-six python-urllib3 python-urwid python3 python3-minimal python3-pyudev python3-six
  python3-yaml python3.6 python3.6-minimal scylla-gcc73-libatomic1 scylla-gcc73-libstdc++6
Use 'apt autoremove' to remove them.
The following packages have been kept back:
  scylla-jmx scylla-tools-core
The following packages will be upgraded:
  scylla scylla-conf scylla-kernel-conf scylla-python3 scylla-server scylla-tools
6 upgraded, 0 newly installed, 0 to remove and 2 not upgraded.
Need to get 53.9 MB of archives.
After this operation, 39.6 MB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 https://s3.amazonaws.com/downloads.scylladb.com/downloads/scylla/deb/ubuntu/scylladb-3.2 bionic/multiverse amd64 scylla-conf amd64 3.2.2-0.20200222.0b23e7145d0-1 [26.0 kB]
Get:2 https://s3.amazonaws.com/downloads.scylladb.com/downloads/scylla/deb/ubuntu/scylladb-3.2 bionic/multiverse amd64 scylla-python3 amd64 3.7.4-0.20200222.0b23e7145d0-1 [19.5 MB]
Get:3 https://s3.amazonaws.com/downloads.scylladb.com/downloads/scylla/deb/ubuntu/scylladb-3.2 bionic/multiverse amd64 scylla-server amd64 3.2.2-0.20200222.0b23e7145d0-1 [34.1 MB]
Get:4 https://s3.amazonaws.com/downloads.scylladb.com/downloads/scylla/deb/ubuntu/scylladb-3.2 bionic/multiverse amd64 scylla-tools all 3.2.2-20200222.725f25026ea-1 [275 kB]
Get:5 https://s3.amazonaws.com/downloads.scylladb.com/downloads/scylla/deb/ubuntu/scylladb-3.2 bionic/multiverse amd64 scylla-kernel-conf amd64 3.2.2-0.20200222.0b23e7145d0-1 [14.6 kB]
Get:6 https://s3.amazonaws.com/downloads.scylladb.com/downloads/scylla/deb/ubuntu/scylladb-3.2 bionic/multiverse amd64 scylla amd64 3.2.2-0.20200222.0b23e7145d0-1 [14.1 kB]
Fetched 53.9 MB in 28s (1923 kB/s)
debconf: delaying package configuration, since apt-utils is not installed
(Reading database ... 17097 files and directories currently installed.)
Preparing to unpack .../0-scylla-conf_3.2.2-0.20200222.0b23e7145d0-1_amd64.deb ...
Unpacking scylla-conf (3.2.2-0.20200222.0b23e7145d0-1) over (3.1.3-0.20200128.b0d122f9c-1) ...
Preparing to unpack .../1-scylla-python3_3.7.4-0.20200222.0b23e7145d0-1_amd64.deb ...
Unpacking scylla-python3 (3.7.4-0.20200222.0b23e7145d0-1) over (3.7.2-0.20200128.b0d122f9c-1) ...
Preparing to unpack .../2-scylla-server_3.2.2-0.20200222.0b23e7145d0-1_amd64.deb ...
Unpacking scylla-server (3.2.2-0.20200222.0b23e7145d0-1) over (3.1.3-0.20200128.b0d122f9c-1) ...
Preparing to unpack .../3-scylla-tools_3.2.2-20200222.725f25026ea-1_all.deb ...
Unpacking scylla-tools (3.2.2-20200222.725f25026ea-1) over (3.1.3-20200128.afb663faef-1) ...
Preparing to unpack .../4-scylla-kernel-conf_3.2.2-0.20200222.0b23e7145d0-1_amd64.deb ...
Unpacking scylla-kernel-conf (3.2.2-0.20200222.0b23e7145d0-1) over (3.1.3-0.20200128.b0d122f9c-1) ...
Preparing to unpack .../5-scylla_3.2.2-0.20200222.0b23e7145d0-1_amd64.deb ...
Unpacking scylla (3.2.2-0.20200222.0b23e7145d0-1) over (3.1.3-0.20200128.b0d122f9c-1) ...
Setting up scylla-conf (3.2.2-0.20200222.0b23e7145d0-1) ...

Configuration file '/etc/scylla/scylla.yaml'
 ==> Modified (by you or by a script) since installation.
 ==> Package distributor has shipped an updated version.
   What would you like to do about it ?  Your options are:
    Y or I  : install the package maintainer's version
    N or O  : keep your currently-installed version
      D     : show the differences between the versions
      Z     : start a shell to examine the situation
 The default action is to keep your current version.
*** scylla.yaml (Y/I/N/O/D/Z) [default=N] ? y
Installing new version of config file /etc/scylla/scylla.yaml ...
Setting up scylla-python3 (3.7.4-0.20200222.0b23e7145d0-1) ...
Setting up scylla-server (3.2.2-0.20200222.0b23e7145d0-1) ...
Installing new version of config file /etc/init/scylla-fstrim.conf ...
Installing new version of config file /etc/init/scylla-housekeeping-daily.conf ...
Installing new version of config file /etc/init/scylla-housekeeping-restart.conf ...
Installing new version of config file /etc/init/scylla-server.conf ...
scylla:x:104:104::/var/lib/scylla:/usr/sbin/nologin
scylla:x:104:
Setting up scylla-tools (3.2.2-20200222.725f25026ea-1) ...
Setting up scylla-kernel-conf (3.2.2-0.20200222.0b23e7145d0-1) ...
sysctl: setting key "kernel.sched_tunable_scaling": Read-only file system
sysctl: setting key "kernel.sched_min_granularity_ns": Read-only file system
sysctl: setting key "kernel.sched_wakeup_granularity_ns": Read-only file system
sysctl: setting key "kernel.sched_latency_ns": Read-only file system
sysctl: setting key "kernel.sched_autogroup_enabled": Read-only file system
sysctl: setting key "kernel.numa_balancing": Read-only file system
sysctl: setting key "fs.aio-max-nr": Read-only file system
Setting up scylla (3.2.2-0.20200222.0b23e7145d0-1) ...
```

**Comment by syuu1228** [comment] 2020-03-02 13:51
@penberg Reproduced on my side too, and I found it because previous version mistakenly installed with openjdk-11-jre, and we added Conflicts: openjdk-11-jre on new version:
https://github.com/scylladb/scylla-jmx/commit/236ffa6c9868cecf992bd471201d7fbe54d25ce4#diff-63756a56e8b5199f204f75a3bc11094a

After I removed openjdk-11-jre, it does not kept back -jmx and -tools anymore.
I suppose adding Conflicts is correct since -jmx/-tools does not works correctly on openjdk-11, but we probably better to advice users not to install openjdk-11-jre and -jmx/-tools together.
```
root@10038aae7e4a:/etc/apt/sources.list.d# apt purge openjdk-11-jre-headless                                                                                               Reading package lists... Done
Building dependency tree
Reading state information... Done
The following packages were automatically installed and are no longer required:                                                                                              hugepages libasound2 libasound2-data libcrypto++6 libgnutlsxx28
  libhugetlbfs0 libjsoncpp1 libprotobuf10 libsnappy1v5 python-asn1crypto                                                                                                     python-certifi python-cffi-backend python-chardet python-cryptography                                                                                                      python-enum34 python-idna python-ipaddress python-openssl
  python-pkg-resources python-requests python-six python-urllib3 python-urwid                                                                                                python3-pyudev python3-six python3-yaml scylla-gcc73-libatomic1
  scylla-gcc73-libstdc++6
Use 'apt autoremove' to remove them.
The following packages will be REMOVED:
  default-jre-headless* openjdk-11-jre-headless*
0 upgraded, 0 newly installed, 2 to remove and 8 not upgraded.
After this operation, 171 MB disk space will be freed.
Do you want to continue? [Y/n] y
(Reading database ... 20856 files and directories currently installed.)
Removing default-jre-headless (2:1.11-68ubuntu1~18.04.1) ...
Removing openjdk-11-jre-headless:amd64 (11.0.6+10-1ubuntu1~18.04.1) ...
update-alternatives: using /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/rmid to provide /usr/bin/rmid (rmid) in auto mode
update-alternatives: using /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java to provide /usr/bin/java (java) in auto mode
update-alternatives: using /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/keytool to provide /usr/bin/keytool (keytool) in auto mode
update-alternatives: using /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/jjs to provide /usr/bin/jjs (jjs) in auto mode
update-alternatives: using /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/pack200 to provide /usr/bin/pack200 (pack200) in auto mode
update-alternatives: using /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/rmiregistry to provide /usr/bin/rmiregistry (rmiregistry) in auto mode
update-alternatives: using /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/unpack200 to provide /usr/bin/unpack200 (unpack200) in auto mode
update-alternatives: using /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/jexec to provide /usr/bin/jexec (jexec) in auto mode
(Reading database ... 20546 files and directories currently installed.)
Purging configuration files for openjdk-11-jre-headless:amd64 (11.0.6+10-1ubuntu1~18.04.1) ...
root@10038aae7e4a:/etc/apt/sources.list.d# apt-get dist-upgrade
Reading package lists... Done
Building dependency tree
Reading state information... Done
Calculating upgrade... Done
The following packages were automatically installed and are no longer required:  hugepages libasound2 libasound2-data libcrypto++6 libgnutlsxx28
  libhugetlbfs0 libjsoncpp1 libprotobuf10 libsnappy1v5 python-asn1crypto
  python-certifi python-cffi-backend python-chardet python-cryptography
  python-enum34 python-idna python-ipaddress python-openssl
  python-pkg-resources python-requests python-six python-urllib3 python-urwid
  python3-pyudev python3-six python3-yaml scylla-gcc73-libatomic1
  scylla-gcc73-libstdc++6
Use 'apt autoremove' to remove them.
The following packages will be upgraded:
  scylla scylla-conf scylla-jmx scylla-kernel-conf scylla-python3
  scylla-server scylla-tools scylla-tools-core
8 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 90.2 MB of archives.
After this operation, 43.8 MB of additional disk space will be used.
Do you want to continue? [Y/n]
```

**Comment by Solvik** [comment] 2020-03-02 16:28
For anyone having this problem and finding this issue, a manual fix is to `apt-get install scylla-jmx scylla-tools-core`

It will upgrade the packages without any problem

**Comment by syuu1228** [comment] 2020-03-02 18:40
> For anyone having this problem and finding this issue, a manual fix is to `apt-get install scylla-jmx scylla-tools-core`
> 
> It will upgrade the packages without any problem

Seems like because it removes openjdk-11-jre:
```
root@10038aae7e4a:/etc/apt/sources.list.d# apt-get install scylla-jmx scylla-tools-core
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following packages were automatically installed and are no longer required:
  hugepages libasound2 libasound2-data libcrypto++6 libgnutlsxx28 libhugetlbfs0 libjsoncpp1 libprotobuf10 libsnappy1v5 python-asn1crypto python-certifi
  python-cffi-backend python-chardet python-cryptography python-enum34 python-idna python-ipaddress python-openssl python-pkg-resources python-requests python-six
  python-urllib3 python-urwid python3-pyudev python3-six python3-yaml scylla-gcc73-libatomic1 scylla-gcc73-libstdc++6
Use 'apt autoremove' to remove them.
The following packages will be REMOVED:
  openjdk-11-jre-headless
The following packages will be upgraded:
  scylla-jmx scylla-tools-core
2 upgraded, 0 newly installed, 1 to remove and 6 not upgraded.
Need to get 36.3 MB of archives.
After this operation, 167 MB disk space will be freed.
Do you want to continue? [Y/n]
```

**Comment by penberg** [comment] 2020-03-04 11:50
We could fix this with documenting that users must remove `openjdk-11-jre` before upgrading to Scylla 3.2. /cc @tzach @avikivity @slivne

**Comment by syuu1228** [comment] 2020-03-05 08:11
We actually need to remove openjdk-11-jre on install time, not just upgrade time.
I think we should add it on the document, too.

**Comment by roydahan** [comment] 2020-03-05 13:20
@amoskong we can add a simple test for this, no need all the stages of the current rolling upgrade test.

**Comment by amoskong** [comment] 2020-03-06 00:04
> @amoskong we can add a simple test for this, no need all the stages of the current rolling upgrade test.

We didn't test multiple versions upgrade now, how many versions do you want to test in the new test?

2.3->3.0->3.1->3.2 ? or just 3.0 -> 3.1 -> 3.2?

**Comment by eliransin** [comment] 2020-03-10 12:38
@penberg ping

**Comment by penberg** [comment] 2020-03-11 10:51
@amoskong I would start with 3.0 -> 3.1 -> 3.2 just to keep it simple, and perhaps when 3.3 comes out, move forward so that it becomes 3.1 -> 3.2 -> 3.3.

Of course, if that does not trigger this bug, making the chain longer is needed.

**Comment by penberg** [comment] 2020-03-11 10:52
@syuu1228 Did you already send a packaging somewhere?

**Comment by syuu1228** [comment] 2020-04-27 09:22
@penberg well I suggested to add description to remove openjdk-11 on doc, not fixing the packaging.

**Comment by syuu1228** [comment] 2020-04-28 06:35
I think I found a solution:
Add ```Conflicts: openjdk-11-jre-headless, openjdk-11-jre, oracle-java11-set-default``` on scylla metapackage.
Then we apt will try to remove openjdk-11-jre, no "kept-back":
```
# apt-get dist-upgrade scylla
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
The following packages were automatically installed and are no longer required:
  at-spi2-core fonts-dejavu-extra hugepages libasound2 libasound2-data
  libatk-bridge2.0-0 libatk-wrapper-java libatk-wrapper-java-jni libatk1.0-0
  libatk1.0-data libatspi2.0-0 libcrypto++6 libdrm-amdgpu1 libdrm-common
  libdrm-intel1 libdrm-nouveau2 libdrm-radeon1 libdrm2 libelf1 libfontenc1
  libgif7 libgl1 libgl1-mesa-dri libglapi-mesa libglvnd0 libglx-mesa0 libglx0
  libgnutlsxx28 libhugetlbfs0 libice6 libjsoncpp1 libllvm9 libprotobuf10
  libsensors4 libsm6 libsnappy1v5 libx11-xcb1 libxaw7 libxcb-dri2-0
  libxcb-dri3-0 libxcb-glx0 libxcb-present0 libxcb-shape0 libxcb-sync1
  libxcomposite1 libxdamage1 libxfixes3 libxft2 libxinerama1 libxmu6 libxmuu1
  libxpm4 libxrandr2 libxshmfence1 libxt6 libxv1 libxxf86dga1 libxxf86vm1
  python-asn1crypto python-certifi python-cffi-backend python-chardet
  python-cryptography python-enum34 python-idna python-ipaddress
  python-openssl python-pkg-resources python-requests python-six
  python-urllib3 python-urwid python3-pyudev python3-six python3-yaml
  x11-utils
Use 'apt autoremove' to remove them.
The following packages will be REMOVED:
  openjdk-11-jre-headless
The following packages will be upgraded:
  bsdutils fdisk gcc-8-base libasound2 libasound2-data libblkid1 libcups2
  libfdisk1 libgcc1 libglib2.0-0 libglib2.0-data libicu60 libkmod2 libmount1
  libpython2.7-minimal libpython2.7-stdlib libpython3.6 libpython3.6-minimal
  libpython3.6-stdlib libsmartcols1 libsqlite3-0 libstdc++6 libuuid1 mount
  openjdk-8-jre-headless python2.7 python2.7-minimal python3.6
  python3.6-minimal scylla scylla-conf scylla-jmx scylla-kernel-conf
  scylla-python3 scylla-server scylla-tools scylla-tools-core util-linux
  uuid-runtime vim vim-common vim-runtime xxd
43 upgraded, 0 newly installed, 1 to remove and 0 not upgraded.
Need to get 146 MB of archives.
After this operation, 127 MB disk space will be freed.
Do you want to continue? [Y/n] 
```
Strangely, when we install both openjdk-11-jre and openjdk-11-jre-headless we will get "Conflicts" error instead of automatically remove the package.
But still there is no "kept-back":
```
# apt-get dist-upgrade scylla      
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Error!
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 scylla : Conflicts: openjdk-11-jre-headless but 11.0.7+10-2ubuntu2~18.04 is to be installed
E: Error, pkgProblemResolver::Resolve generated breaks, this may be caused by held packages.

```

**Comment by avikivity** [comment] 2020-11-11 09:45
I think this is fixed. @syuu1228 @penberg is this so?

**Comment by slivne** [comment] 2021-01-24 21:53
closing this issue - AFAIK this is fixed

**Closed by slivne** 2021-01-24 21:53 UTC
Labels: bug, ubuntu
