### ISSUE TITLE
add option to completely disable compaction only on single node

### ISSUE THREAD

**Issue by tarzanek** [scylladb/scylla#6101] opened 2020-03-30 15:58 UTC
Sometimes support needs a way how to stop compactions on a single node only.

E.g. when you have problems when starting the node with commit log files and you want to load them by batches (to pinpoint the faulty log file).
I know we list corrupted log files, but we don't list files which have corrupted data in them already.

Can this be supported? (implemented?)
I know we can disable compaction cluster wide with changing to NullCS, but this is just one single node where the problems are and affecting whole cluster won't do any good

seems similar to https://github.com/scylladb/scylla/issues/2722

**Comment by tarzanek** [comment] 2020-03-30 15:59
fwiw we spoke with @glommer  about setting the compaction shares to 0
but this also won't disable compactions (but perhaps it should, since it is on one node only)

**Comment by denesb** [comment] 2020-03-30 16:02
@tarzanek also see https://github.com/scylladb/scylla/issues/5489.

**Comment by raphaelsc** [comment] 2020-03-31 15:46
I think the following can be used to achieve this: https://github.com/scylladb/scylla/pull/5877

**Comment by slivne** [comment] 2020-04-14 00:07
fixed by 1c444b7e1ed1e77cac2004d1f5600e8e666bfc34

**Closed by slivne** 2020-04-14 00:07 UTC

**Comment by avikivity** [comment] 2021-02-10 17:36
Not a bug, so not backporting.
