### ISSUE TITLE
Error: managed_bytes::managed_bytes(const managed_bytes&): Assertion `size_src == 0 && size_dst == 0' failed.

### ISSUE THREAD

**Issue by aleksbykov** [scylladb/scylla#6898] opened 2020-07-22 03:32 UTC
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash): 666.development-0.20200607.a1e235b1a with build-id f71dfc93f549d44c958d52d11ffc78757e085386
Cluster size: 4
OS (RHEL/CentOS/Ubuntu/AWS AMI): ami-0b53d2c2e5f6eb7d6

Issue #1272 was reproduced during job [link](https://jenkins.scylladb.com/view/scylla-4.2/job/scylla-4.2/job/Reproducers/job/reproduce_issue_6613/1/) in attempt to reproduce issue #6613.

Scylla was restarted on node2 and the repair process was started. At this time on node 3 next error and coredump was reported:
```
2020-07-21T18:08:18+00:00  longevity-lwt-3h-master-db-node-fc6e9eba-3 !ERR     | scylla: [shard 0] rpc - client 10.0.78.188:7000: fail to connect: Connection refused
2020-07-21T18:08:19+00:00  longevity-lwt-3h-master-db-node-fc6e9eba-3 !INFO    | scylla: scylla: ./utils/managed_bytes.hh:266: managed_bytes::managed_bytes(const managed_bytes&): Assertion `size_src == 0 && size_dst == 0' failed.
2020-07-21T18:08:19+00:00  longevity-lwt-3h-master-db-node-fc6e9eba-3 !INFO    | scylla: Aborting on shard 5.
2020-07-21T18:08:19+00:00  longevity-lwt-3h-master-db-node-fc6e9eba-3 !INFO    | scylla: Backtrace:
2020-07-21T18:08:19+00:00  longevity-lwt-3h-master-db-node-fc6e9eba-3 !INFO    | scylla: 0x0000000002f27312
2020-07-21T18:08:19+00:00  longevity-lwt-3h-master-db-node-fc6e9eba-3 !INFO    | scylla: 0x0000000002eca930
2020-07-21T18:08:19+00:00  longevity-lwt-3h-master-db-node-fc6e9eba-3 !INFO    | scylla: 0x0000000002ecabd5
2020-07-21T18:08:19+00:00  longevity-lwt-3h-master-db-node-fc6e9eba-3 !INFO    | scylla: 0x0000000002ecac20
2020-07-21T18:08:19+00:00  longevity-lwt-3h-master-db-node-fc6e9eba-3 !INFO    | scylla: 0x00007f71309c5a8f
2020-07-21T18:08:19+00:00  longevity-lwt-3h-master-db-node-fc6e9eba-3 !INFO    | scylla: /opt/scylladb/libreloc/libc.so.6+0x000000000003ca24
2020-07-21T18:08:19+00:00  longevity-lwt-3h-master-db-node-fc6e9eba-3 !INFO    | scylla: /opt/scylladb/libreloc/libc.so.6+0x0000000000025894
2020-07-21T18:08:19+00:00  longevity-lwt-3h-master-db-node-fc6e9eba-3 !INFO    | scylla: /opt/scylladb/libreloc/libc.so.6+0x0000000000025768
2020-07-21T18:08:19+00:00  longevity-lwt-3h-master-db-node-fc6e9eba-3 !INFO    | scylla: /opt/scylladb/libreloc/libc.so.6+0x0000000000034e85
2020-07-21T18:08:19+00:00  longevity-lwt-3h-master-db-node-fc6e9eba-3 !INFO    | scylla: 0x0000000000de1aa8
2020-07-21T18:08:19+00:00  longevity-lwt-3h-master-db-node-fc6e9eba-3 !INFO    | scylla: 0x0000000000fc543f
2020-07-21T18:08:19+00:00  longevity-lwt-3h-master-db-node-fc6e9eba-3 !INFO    | scylla: 0x0000000000fd0150
2020-07-21T18:08:19+00:00  longevity-lwt-3h-master-db-node-fc6e9eba-3 !INFO    | scylla: 0x0000000000fcfa7c
2020-07-21T18:08:19+00:00  longevity-lwt-3h-master-db-node-fc6e9eba-3 !INFO    | scylla: 0x000000000116fb77
2020-07-21T18:08:19+00:00  longevity-lwt-3h-master-db-node-fc6e9eba-3 !INFO    | scylla: 0x0000000000fbf208
2020-07-21T18:08:19+00:00  longevity-lwt-3h-master-db-node-fc6e9eba-3 !INFO    | scylla: 0x0000000000fbf7cd
2020-07-21T18:08:19+00:00  longevity-lwt-3h-master-db-node-fc6e9eba-3 !INFO    | scylla: 0x000000000113a761
2020-07-21T18:08:19+00:00  longevity-lwt-3h-master-db-node-fc6e9eba-3 !INFO    | scylla: 0x000000000113cbfd
2020-07-21T18:08:19+00:00  longevity-lwt-3h-master-db-node-fc6e9eba-3 !INFO    | scylla: 0x000000000113d110
2020-07-21T18:08:19+00:00  longevity-lwt-3h-master-db-node-fc6e9eba-3 !INFO    | scylla: 0x000000000110a5dc
2020-07-21T18:08:19+00:00  longevity-lwt-3h-master-db-node-fc6e9eba-3 !INFO    | scylla: 0x0000000001131490
2020-07-21T18:08:19+00:00  longevity-lwt-3h-master-db-node-fc6e9eba-3 !INFO    | scylla: 0x0000000001132628
2020-07-21T18:08:19+00:00  longevity-lwt-3h-master-db-node-fc6e9eba-3 !INFO    | scylla: 0x0000000001134d9d
2020-07-21T18:08:19+00:00  longevity-lwt-3h-master-db-node-fc6e9eba-3 !INFO    | scylla: 0x0000000001138b7d
2020-07-21T18:08:19+00:00  longevity-lwt-3h-master-db-node-fc6e9eba-3 !INFO    | scylla: 0x0000000002ec7ee7
2020-07-21T18:08:19+00:00  longevity-lwt-3h-master-db-node-fc6e9eba-3 !INFO    | scylla: 0x0000000002ec826e
2020-07-21T18:08:19+00:00  longevity-lwt-3h-master-db-node-fc6e9eba-3 !INFO    | scylla: 0x0000000002f0280d
2020-07-21T18:08:19+00:00  longevity-lwt-3h-master-db-node-fc6e9eba-3 !INFO    | scylla: 0x0000000002f0f87a
2020-07-21T18:08:19+00:00  longevity-lwt-3h-master-db-node-fc6e9eba-3 !INFO    | scylla: 0x0000000002e9473d
2020-07-21T18:08:19+00:00  longevity-lwt-3h-master-db-node-fc6e9eba-3 !INFO    | scylla: /opt/scylladb/libreloc/libpthread.so.0+0x0000000000009431
2020-07-21T18:08:19+00:00  longevity-lwt-3h-master-db-node-fc6e9eba-3 !INFO    | scylla: /opt/scylladb/libreloc/libc.so.6+0x00000000001019d2
```

decoded backtrace
```
void seastar::backtrace<seastar::backtrace_buffer::append_backtrace()::{lambda(seastar::frame)#1}>(seastar::backtrace_buffer::append_backtrace()::{lambda(seastar::frame)#1}&&) at /usr/include/fmt/format.h:2188
seastar::backtrace_buffer::append_backtrace() at /usr/include/fmt/format.h:2188
 (inlined by) print_with_backtrace at ./build/release/seastar/./seastar/src/core/reactor.cc:763
seastar::print_with_backtrace(char const*) at /usr/include/fmt/format.h:2188
sigabrt_action at /usr/include/fmt/format.h:2188
 (inlined by) operator() at ./build/release/seastar/./seastar/src/core/reactor.cc:3460
 (inlined by) _FUN at ./build/release/seastar/./seastar/src/core/reactor.cc:3456
?? ??:0
?? ??:0
?? ??:0
?? ??:0
?? ??:0
managed_bytes::managed_bytes(managed_bytes const&) at /usr/include/fmt/core.h:606
compound_wrapper<clustering_key_prefix, clustering_key_prefix_view>::compound_wrapper(compound_wrapper<clustering_key_prefix, clustering_key_prefix_view> const&) at ./keys.hh:165
 (inlined by) prefix_compound_wrapper<clustering_key_prefix, clustering_key_prefix_view, clustering_key_prefix>::prefix_compound_wrapper(prefix_compound_wrapper<clustering_key_prefix, clustering_key_prefix_view, clustering_key_prefix> const&) at ./keys.hh:558
 (inlined by) clustering_key_prefix::clustering_key_prefix(clustering_key_prefix const&) at ./keys.hh:788
 (inlined by) std::_Optional_payload_base<clustering_key_prefix>::_Storage<clustering_key_prefix, false>::_Storage<clustering_key_prefix const&>(std::in_place_t, clustering_key_prefix const&) at /usr/include/c++/10/optional:226
 (inlined by) std::_Optional_payload_base<clustering_key_prefix>::_Optional_payload_base<clustering_key_prefix const&>(std::in_place_t, clustering_key_prefix const&) at /usr/include/c++/10/optional:118
 (inlined by) _ZNSt17_Optional_payloadI21clustering_key_prefixLb1ELb0ELb0EECI4St22_Optional_payload_baseIS0_EIJRKS0_EEESt10in_place_tDpOT_ at /usr/include/c++/10/optional:359
 (inlined by) _ZNSt17_Optional_payloadI21clustering_key_prefixLb0ELb0ELb0EECI4St22_Optional_payload_baseIS0_EIJRKS0_EEESt10in_place_tDpOT_ at /usr/include/c++/10/optional:393
 (inlined by) std::_Optional_base<clustering_key_prefix, false, false>::_Optional_base<clustering_key_prefix const&, false>(std::in_place_t, clustering_key_prefix const&) at /usr/include/c++/10/optional:485
 (inlined by) std::optional<clustering_key_prefix>::optional<clustering_key_prefix const&, true>(clustering_key_prefix const&) at /usr/include/c++/10/optional:702
 (inlined by) position_in_partition::position_in_partition(position_in_partition::range_tag_t, bound_view) at ././position_in_partition.hh:249
 (inlined by) position_in_partition::for_range_start(nonwrapping_range<clustering_key_prefix> const&) at ././position_in_partition.hh:516
 (inlined by) cache::cache_flat_mutation_reader::move_to_range(__gnu_cxx::__normal_iterator<nonwrapping_range<clustering_key_prefix> const*, std::vector<nonwrapping_range<clustering_key_prefix>, std::allocator<nonwrapping_range<clustering_key_prefix> > > >) at ./cache_flat_mutation_reader.hh:552
cache::cache_flat_mutation_reader::fill_buffer(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda()#1}::operator()() const::{lambda()#1}::operator()() const at ./cache_flat_mutation_reader.hh:225
 (inlined by) _ZZZN5cache11lsa_manager19run_in_read_sectionIZZNS_26cache_flat_mutation_reader11fill_bufferENSt6chrono10time_pointIN7seastar12lowres_clockENS3_8durationIlSt5ratioILl1ELl1000EEEEEEENKUlvE_clEvEUlvE_EEDcRKT_ENKUlvE_clEvENKUlvE_clEv at ./row_cache.hh:590
 (inlined by) _Z29with_linearized_managed_bytesIZZN5cache11lsa_manager19run_in_read_sectionIZZNS0_26cache_flat_mutation_reader11fill_bufferENSt6chrono10time_pointIN7seastar12lowres_clockENS4_8durationIlSt5ratioILl1ELl1000EEEEEEENKUlvE_clEvEUlvE_EEDcRKT_ENKUlvE_clEvEUlvE_ENSt9result_ofIFSF_vEE4typeEOSF_ at ./utils/managed_bytes.hh:428
 (inlined by) _ZZN5cache11lsa_manager19run_in_read_sectionIZZNS_26cache_flat_mutation_reader11fill_bufferENSt6chrono10time_pointIN7seastar12lowres_clockENS3_8durationIlSt5ratioILl1ELl1000EEEEEEENKUlvE_clEvEUlvE_EEDcRKT_ENKUlvE_clEv at ./row_cache.hh:589
 (inlined by) _ZN8logalloc18allocating_section24with_reclaiming_disabledIRZN5cache11lsa_manager19run_in_read_sectionIZZNS2_26cache_flat_mutation_reader11fill_bufferENSt6chrono10time_pointIN7seastar12lowres_clockENS6_8durationIlSt5ratioILl1ELl1000EEEEEEENKUlvE_clEvEUlvE_EEDcRKT_EUlvE_EEDcRNS_6regionEOSH_ at ././utils/logalloc.hh:746
 (inlined by) _ZZN8logalloc18allocating_sectionclIZN5cache11lsa_manager19run_in_read_sectionIZZNS2_26cache_flat_mutation_reader11fill_bufferENSt6chrono10time_pointIN7seastar12lowres_clockENS6_8durationIlSt5ratioILl1ELl1000EEEEEEENKUlvE_clEvEUlvE_EEDcRKT_EUlvE_EEDcRNS_6regionEOSH_ENKUlvE_clEv at ././utils/logalloc.hh:768
 (inlined by) _ZN8logalloc18allocating_section12with_reserveIZNS0_clIZN5cache11lsa_manager19run_in_read_sectionIZZNS3_26cache_flat_mutation_reader11fill_bufferENSt6chrono10time_pointIN7seastar12lowres_clockENS7_8durationIlSt5ratioILl1ELl1000EEEEEEENKUlvE_clEvEUlvE_EEDcRKT_EUlvE_EEDcRNS_6regionEOSI_EUlvE_EEDcSO_ at ././utils/logalloc.hh:718
 (inlined by) _ZN8logalloc18allocating_sectionclIZN5cache11lsa_manager19run_in_read_sectionIZZNS2_26cache_flat_mutation_reader11fill_bufferENSt6chrono10time_pointIN7seastar12lowres_clockENS6_8durationIlSt5ratioILl1ELl1000EEEEEEENKUlvE_clEvEUlvE_EEDcRKT_EUlvE_EEDcRNS_6regionEOSH_ at ././utils/logalloc.hh:767
 (inlined by) _ZN5cache11lsa_manager19run_in_read_sectionIZZNS_26cache_flat_mutation_reader11fill_bufferENSt6chrono10time_pointIN7seastar12lowres_clockENS3_8durationIlSt5ratioILl1ELl1000EEEEEEENKUlvE_clEvEUlvE_EEDcRKT_ at ./row_cache.hh:588
 (inlined by) cache::cache_flat_mutation_reader::fill_buffer(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda()#1}::operator()() const at ./cache_flat_mutation_reader.hh:224
cache::cache_flat_mutation_reader::fill_buffer(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >) at ./cache_flat_mutation_reader.hh:232
flat_mutation_reader::fill_buffer(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >) at /usr/include/fmt/format.h:2188
 (inlined by) seastar::future<bool> flat_mutation_reader::impl::fill_buffer_from<flat_mutation_reader>(flat_mutation_reader&, std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >) at ./flat_mutation_reader.cc:196
scanning_and_populating_reader::fill_buffer(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda()#2}::operator()() const at ./row_cache.cc:697
seastar::future<> seastar::futurize<seastar::future<> >::invoke<scanning_and_populating_reader::fill_buffer(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda()#2}&>(scanning_and_populating_reader::fill_buffer(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda()#2}&) at ././seastar/include/seastar/core/future.hh:1861
 (inlined by) auto seastar::futurize_invoke<scanning_and_populating_reader::fill_buffer(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda()#2}&>(scanning_and_populating_reader::fill_buffer(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda()#2}&) at ././seastar/include/seastar/core/future.hh:1945
 (inlined by) seastar::future<> seastar::do_until<scanning_and_populating_reader::fill_buffer(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda()#2}, scanning_and_populating_reader::fill_buffer(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda()#1}>(scanning_and_populating_reader::fill_buffer(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda()#1}, scanning_and_populating_reader::fill_buffer(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda()#2}) at ././seastar/include/seastar/core/future-util.hh:525
 (inlined by) scanning_and_populating_reader::fill_buffer(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >) at ./row_cache.cc:703
mutation_reader_merger::operator()(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >) at mutation_reader.cc:?
 (inlined by) mutation_reader_merger::operator()(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >) at ./mutation_reader.cc:449
seastar::future<seastar::bool_class<seastar::stop_iteration_tag> > seastar::futurize<seastar::future<seastar::bool_class<seastar::stop_iteration_tag> > >::invoke<combined_mutation_reader::fill_buffer(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda()#1}&>(combined_mutation_reader::fill_buffer(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda()#1}&) at mutation_reader.cc:?
 (inlined by) mutation_fragment_merger<mutation_reader_merger>::operator()(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >) at ./mutation_reader.cc:108
 (inlined by) operator() at ./mutation_reader.cc:578
 (inlined by) invoke<combined_mutation_reader::fill_buffer(seastar::lowres_clock::time_point)::<lambda()>&> at ././seastar/include/seastar/core/future.hh:1861
combined_mutation_reader::fill_buffer(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >) at mutation_reader.cc:?
 (inlined by) combined_mutation_reader::fill_buffer(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >) at ./mutation_reader.cc:589
(anonymous namespace)::shard_reader::remote_reader::do_fill_buffer(flat_mutation_reader&, std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >) at mutation_reader.cc:?
 (inlined by) do_fill_buffer at ./mutation_reader.cc:1258
auto seastar::internal::do_with_impl<flat_mutation_reader, seastar::circular_buffer<mutation_fragment, std::allocator<mutation_fragment> >, (anonymous namespace)::shard_reader::remote_reader::fill_buffer(nonwrapping_range<dht::ring_position> const&, bool, std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda(flat_mutation_reader&, seastar::circular_buffer<mutation_fragment, std::allocator<mutation_fragment> >&)#1}>(flat_mutation_reader&&, seastar::circular_buffer<mutation_fragment, std::allocator<mutation_fragment> >&&, (anonymous namespace)::shard_reader::remote_reader::fill_buffer(nonwrapping_range<dht::ring_position> const&, bool, std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda(flat_mutation_reader&, seastar::circular_buffer<mutation_fragment, std::allocator<mutation_fragment> >&)#1}&&) at mutation_reader.cc:?
 (inlined by) operator() at ./mutation_reader.cc:1355
 (inlined by) __invoke_impl<seastar::future<(anonymous namespace)::shard_reader::fill_buffer_result>, (anonymous namespace)::shard_reader::remote_reader::fill_buffer(const partition_range&, bool, seastar::lowres_clock::time_point)::<lambda(flat_mutation_reader&, seastar::circular_buffer<mutation_fragment>&)>&, flat_mutation_reader&, seastar::circular_buffer<mutation_fragment, std::allocator<mutation_fragment> >&> at /usr/include/c++/10/bits/invoke.h:60
 (inlined by) __invoke<(anonymous namespace)::shard_reader::remote_reader::fill_buffer(const partition_range&, bool, seastar::lowres_clock::time_point)::<lambda(flat_mutation_reader&, seastar::circular_buffer<mutation_fragment>&)>&, flat_mutation_reader&, seastar::circular_buffer<mutation_fragment, std::allocator<mutation_fragment> >&> at /usr/include/c++/10/bits/invoke.h:96
 (inlined by) __apply_impl<(anonymous namespace)::shard_reader::remote_reader::fill_buffer(const partition_range&, bool, seastar::lowres_clock::time_point)::<lambda(flat_mutation_reader&, seastar::circular_buffer<mutation_fragment>&)>&, std::tuple<flat_mutation_reader, seastar::circular_buffer<mutation_fragment, std::allocator<mutation_fragment> > >&, 0, 1> at /usr/include/c++/10/tuple:1724
 (inlined by) apply<(anonymous namespace)::shard_reader::remote_reader::fill_buffer(const partition_range&, bool, seastar::lowres_clock::time_point)::<lambda(flat_mutation_reader&, seastar::circular_buffer<mutation_fragment>&)>&, std::tuple<flat_mutation_reader, seastar::circular_buffer<mutation_fragment, std::allocator<mutation_fragment> > >&> at /usr/include/c++/10/tuple:1736
 (inlined by) do_with_impl<flat_mutation_reader, seastar::circular_buffer<mutation_fragment>, (anonymous namespace)::shard_reader::remote_reader::fill_buffer(const partition_range&, bool, seastar::lowres_clock::time_point)::<lambda(flat_mutation_reader&, seastar::circular_buffer<mutation_fragment, std::allocator<mutation_fragment> >&)> > at ././seastar/include/seastar/core/do_with.hh:106
(anonymous namespace)::shard_reader::remote_reader::fill_buffer(nonwrapping_range<dht::ring_position> const&, bool, std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >) at mutation_reader.cc:?
 (inlined by) futurize_invoke<seastar::future<(anonymous namespace)::shard_reader::fill_buffer_result> (*&)(flat_mutation_reader&&, seastar::circular_buffer<mutation_fragment>&&, (anonymous namespace)::shard_reader::remote_reader::fill_buffer(const partition_range&, bool, seastar::lowres_clock::time_point)::<lambda(flat_mutation_reader&, seastar::circular_buffer<mutation_fragment>&)>&&), flat_mutation_reader, seastar::circular_buffer<mutation_fragment, std::allocator<mutation_fragment> >, (anonymous namespace)::shard_reader::remote_reader::fill_buffer(const partition_range&, bool, seastar::lowres_clock::time_point)::<lambda(flat_mutation_reader&, seastar::circular_buffer<mutation_fragment, std::allocator<mutation_fragment> >&)> > at ././seastar/include/seastar/core/future.hh:1945
 (inlined by) do_with<flat_mutation_reader, seastar::circular_buffer<mutation_fragment>, (anonymous namespace)::shard_reader::remote_reader::fill_buffer(const partition_range&, bool, seastar::lowres_clock::time_point)::<lambda(flat_mutation_reader&, seastar::circular_buffer<mutation_fragment, std::allocator<mutation_fragment> >&)> > at ././seastar/include/seastar/core/do_with.hh:141
 (inlined by) fill_buffer at ./mutation_reader.cc:1360
(anonymous namespace)::shard_reader::do_fill_buffer(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda()#1}::operator()() const at mutation_reader.cc:?
seastar::smp_message_queue::async_work_item<(anonymous namespace)::shard_reader::do_fill_buffer(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda()#1}>::run_and_dispose() at mutation_reader.cc:?
 (inlined by) run_and_dispose at ././seastar/include/seastar/core/smp.hh:219
seastar::reactor::run_tasks(seastar::reactor::task_queue&) at /usr/include/fmt/format.h:2188
seastar::reactor::run_some_tasks() at /usr/include/fmt/format.h:2188
seastar::reactor::run_some_tasks() at /usr/include/fmt/format.h:2188
 (inlined by) seastar::reactor::run() at ./build/release/seastar/./seastar/src/core/reactor.cc:2724
seastar::smp::configure(boost::program_options::variables_map, seastar::reactor_config)::{lambda()#3}::operator()() const at /usr/include/fmt/format.h:2188
std::function<void ()>::operator()() const at /usr/include/c++/10/bits/basic_string.h:323
 (inlined by) seastar::posix_thread::start_routine(void*) at ./build/release/seastar/./seastar/src/core/posix.cc:60
?? ??:0
?? ??:0

```

Coredump info:
```
corefile_url=
https://storage.cloud.google.com/upload.scylladb.com/core.scylla.996.613d86f4789245a89dcbe722c33f87b4.3629.1595354899000000/core.scylla.996.613d86f4789245a89dcbe722c33f87b4.3629.1595354899000000.gz
backtrace=           PID: 3629 (scylla)
           UID: 996 (scylla)
           GID: 1001 (scylla)
        Signal: 6 (ABRT)
     Timestamp: Tue 2020-07-21 18:08:19 UTC (1min 24s ago)
  Command Line: /usr/bin/scylla --blocked-reactor-notify-ms 500 --abort-on-lsa-bad-alloc 1 --abort-on-seastar-bad-alloc --abort-on-internal-error 1 --abort-on-ebadf 1 --enable-sstable-key-validation 1 --log-to-syslog 1 --log-to-stdout 0 --default-log-level info --network-stack posix --io-properties-file=/etc/scylla.d/io_properties.yaml --cpuset 0-7 --lock-memory=1
    Executable: /opt/scylladb/libexec/scylla
 Control Group: /
       Boot ID: 613d86f4789245a89dcbe722c33f87b4
    Machine ID: df877a200226bc47d06f26dae0736ec9
      Hostname: longevity-lwt-3h-master-db-node-fc6e9eba-3
      Coredump: /var/lib/systemd/coredump/core.scylla.996.613d86f4789245a89dcbe722c33f87b4.3629.1595354899000000
       Message: Process 3629 (scylla) of user 996 dumped core.
                
                Stack trace of thread 3635:
                #0  0x00007f712ff87a25 raise (libc.so.6)
                #1  0x00007f712ff7094d abort (libc.so.6)
                #2  0x00007f712ff70769 __assert_fail_base.cold (libc.so.6)
                #3  0x00007f712ff7fe86 __assert_fail (libc.so.6)
                #4  0x0000000000de1aa9 _ZN13managed_bytesC2ERKS_ (scylla)
                #5  0x0000000000fc5440 _ZN16compound_wrapperI21clustering_key_prefix26clustering_key_prefix_viewEC4ERKS2_ (scylla)
                #6  0x0000000000fd0151 _ZZN5cache26cache_flat_mutation_reader11fill_bufferENSt6chrono10time_pointIN7seastar12lowres_clockENS1_8durationIlSt5ratioILl1ELl1000EEEEEEENKUlvE_clEv (scylla)
                #7  0x0000000000fcfa7d _ZN5cache26cache_flat_mutation_reader11fill_bufferENSt6chrono10time_pointIN7seastar12lowres_clockENS1_8durationIlSt5ratioILl1ELl1000EEEEEE (scylla)
                #8  0x000000000116fb78 _ZN20flat_mutation_reader11fill_bufferENSt6chrono10time_pointIN7seastar12lowres_clockENS0_8durationIlSt5ratioILl1ELl1000EEEEEE (scylla)
                #9  0x0000000000fbf209 _ZZN30scanning_and_populating_reader11fill_bufferENSt6chrono10time_pointIN7seastar12lowres_clockENS0_8durationIlSt5ratioILl1ELl1000EEEEEEENKUlvE0_clEv (scylla)
                #10 0x0000000000fbf7ce _ZN7seastar8futurizeINS_6futureIJEEEE6invokeIRZN30scanning_and_populating_reader11fill_bufferENSt6chrono10time_pointINS_12lowres_clockENS6_8durationIlSt5ratioILl1ELl1000EEEEEEEUlvE0_JEEES2_OT_DpOT0_ (scylla)
                #11 0x000000000113a762 _ZN20flat_mutation_reader11fill_bufferENSt6chrono10time_pointIN7seastar12lowres_clockENS0_8durationIlSt5ratioILl1ELl1000EEEEEE (scylla)
                #12 0x000000000113cbfe _ZN24mutation_fragment_mergerI22mutation_reader_mergerE5fetchENSt6chrono10time_pointIN7seastar12lowres_clockENS2_8durationIlSt5ratioILl1ELl1000EEEEEE (scylla)
                #13 0x000000000113d111 repeat<combined_mutation_reader::fill_buffer(seastar::lowres_clock::time_point)::<lambda()> > (scylla)
                #14 0x000000000110a5dd _ZN20flat_mutation_reader11fill_bufferENSt6chrono10time_pointIN7seastar12lowres_clockENS0_8durationIlSt5ratioILl1ELl1000EEEEEE (scylla)
                #15 0x0000000001131491 fill_buffer (scylla)
                #16 0x0000000001132629 invoke<seastar::future<(anonymous namespace)::shard_reader::fill_buffer_result> (*&)(flat_mutation_reader&&, seastar::circular_buffer<mutation_fragment>&&, (anonymous namespace)::shard_reader::remote_reader::fill_buffer(const partition_range&, bool, seastar::lowres_clock::time_point)::<lambda(flat_mutation_reader&, seastar::circular_buffer<mutation_fragment>&)>&&), flat_mutation_reader, seastar::circular_buffer<mutation_fragment, std::allocator<mutation_fragment> >, (anonymous namespace)::shard_reader::remote_reader::fill_buffer(const partition_range&, bool, seastar::lowres_clock::time_point)::<lambda(flat_mutation_reader&, seastar::circular_buffer<mutation_fragment, std::allocator<mutation_fragment> >&)> > (scylla)
                #17 0x0000000001134d9e _ZZN12_GLOBAL__N_112shard_reader14do_fill_bufferENSt6chrono10time_pointIN7seastar12lowres_clockENS1_8durationIlSt5ratioILl1ELl1000EEEEEEENKUlvE_clEv (scylla)
                #18 0x0000000001138b7e invoke<(anonymous namespace)::shard_reader::do_fill_buffer(seastar::lowres_clock::time_point)::<lambda()>&> (scylla)
                #19 0x0000000002ec7ee8 _ZN7seastar7reactor9run_tasksERNS0_10task_queueE (scylla)
                #20 0x0000000002ec826f _ZN7seastar7reactor14run_some_tasksEv (scylla)
                #21 0x0000000002f0280e _ZN7seastar7reactor14run_some_tasksEv (scylla)
                #22 0x0000000002f0f87b _ZZN7seastar3smp9configureEN5boost15program_options13variables_mapENS_14reactor_configEENKUlvE1_clEv (scylla)
                #23 0x0000000002e9473e _ZNKSt8functionIFvvEEclEv (scylla)
                #24 0x00007f71309ba432 start_thread (libpthread.so.0)
                #25 0x00007f713004c9d3 __clone (libc.so.6)
                
                Stack trace of thread 3639:
                #0  0x00007f71309c49ac read (libpthread.so.0)
                #1  0x00000000031579b7 _ZN7seastar11thread_pool4workENS_13basic_sstringIcjLj15ELb1EEE (scylla)
                #2  0x0000000003157c18 operator() (scylla)
                #3  0x0000000002e9473e _ZNKSt8functionIFvvEEclEv (scylla)
                #4  0x00007f71309ba432 start_thread (libpthread.so.0)
                #5  0x00007f713004c9d3 __clone (libc.so.6)
                
                Stack trace of thread 3640:
                #0  0x00007f71309c49ac read (libpthread.so.0)
                #1  0x00000000031579b7 _ZN7se

download_instructions=
gsutil cp gs://upload.scylladb.com/core.scylla.996.613d86f4789245a89dcbe722c33f87b4.3629.1595354899000000/core.scylla.996.613d86f4789245a89dcbe722c33f87b4.3629.1595354899000000.gz .
gunzip /var/lib/systemd/coredump/core.scylla.996.613d86f4789245a89dcbe722c33f87b4.3629.1595354899000000.gz
```

**Comment by denesb** [comment] 2020-07-22 07:30
Likely the same as https://github.com/scylladb/scylla/issues/6613.

**Comment by denesb** [comment] 2020-07-28 04:17
@slivne based on the stacktrace this is a duplicate of #6613, which was fixed in https://github.com/scylladb/scylla/commit/3f84d41880eced9b3ef7564bef05ddc1b76c5a2e. We should close this and open new issues if we see it again.

**Comment by avikivity** [comment] 2020-07-28 08:55
Closing as duplicate of #6613.

**Closed by avikivity** 2020-07-28 08:55 UTC
Labels: bug
