### ISSUE TITLE
database_metrics_test total_reads_user_test: scylla_database_total_reads did not increase as expected

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#7998] opened 2021-01-31 16:42 UTC
Regression detected in https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/730/testReport/database_metrics_test/DatabaseMetricsTester/total_reads_user_test/
Scylla version b32ece6975425f566be78419c027fbb073be62b0
```
Error Message

scylla_database_total_reads did not increase as expected. initial={'scylla_database_total_reads{class="user",shard="0"}': '1', 'scylla_database_total_reads{class="user",shard="1"}': '0'}; final={'scylla_database_total_reads{class="user",shard="0"}': '45', 'scylla_database_total_reads{class="user",shard="1"}': '0'}

Stacktrace

Traceback (most recent call last):
  File "/usr/lib64/python3.7/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/usr/lib64/python3.7/unittest/case.py", line 645, in run
    testMethod()
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/database_metrics_test.py", line 55, in total_reads_user_test
    f'{metrics[0]} did not increase as expected. initial={initial_reads}; final={final_reads}'
AssertionError: scylla_database_total_reads did not increase as expected. initial={'scylla_database_total_reads{class="user",shard="0"}': '1', 'scylla_database_total_reads{class="user",shard="1"}': '0'}; final={'scylla_database_total_reads{class="user",shard="0"}': '45', 'scylla_database_total_reads{class="user",shard="1"}': '0'}
```

I bisected the issue to bf115e7d69b12f4ed4f208646b3eb9c02c966ec2

**Comment by kbr-** [comment] 2021-02-01 11:21
```
        initial_reads = self.get_metrics(self.get_ip_from_node(node), metrics=metrics, metric_class=metric_class)

        self.create_ks(session=session, name=keyspace_name, rf=1)
        tools.create_c1c2_table(self, session)
        tools.insert_c1c2(session, n=100)
        res = session.execute('SELECT * FROM cf LIMIT 20')

        final_reads = self.get_metrics(self.get_ip_from_node(node), metrics=metrics, metric_class=metric_class)
```

The increase in `scylla_database_total_reads` didn't come from the `SELECT`, it came from `create_ks` - I'm guessing the reason is that the node checks if the keyspace already exists by reading the schema tables.

After bf115e7, schema tables reside on shard 0. Thus accessing them should not produce operations on other shards. Hence the test fails, because `create_ks` does not increase shard 1 reads any more (as expected).
I confirmed that without bf115e7, the keyspace `database_metrics` created by the test indeed resides on shard 1 (using the test's settings, i.e. 2 shards and default value of `ignore_msb`). Hence creating it increased shard 1 ops.

Now this means there are two problems:
1. With the test: it performs the measurement incorrectly. `initial_reads` should be measured **after** creating the keyspace and the table, so these operations aren't taken into account when checking if the metric increased.
2. With Scylla: range scan `SELECT`s like the one in the test don't increase the `scylla_database_total_reads` metric. I don't know if this is intended or a bug. Therefore, after problem 1 is fixed, the test will fail (both before and after bf115e7).

If 2 is intended, i.e. we want to increase the metric only for single-partition queries, then the test should be fixed to perform that kind of queries.

cc @fgelcer author of the test
cc @denesb, I saw in `git blame` you modified the metric recently, so maybe you know: should `scylla_database_total_reads` count range scans too? Because right now it looks like doesn't.

**Comment by denesb** [comment] 2021-02-01 11:56
> cc @denesb, I saw in `git blame` you modified the metric recently, so maybe you know: should `scylla_database_total_reads` count range scans too? Because right now it looks like doesn't.

Indeed it appears range scans are not accounted for in this metric. They used to do before the stateful range scan era.

**Comment by bhalevy** [comment] 2021-03-09 15:52
ping @kbr- @denesb 
what's the next step?

**Comment by denesb** [comment] 2021-03-11 14:36
> I would propose:
> 
>     1. modify this test to measure `initial_reads` after creating keyspace and table, and also to use single-partition query instead of a range scan
> 
>     2. write another test that is disabled  for now, which measures the metric for range scans
> 
>     3. create an issue in scylla for the fact that we don't increment `scylla_database_total_reads` for range scans; in this issue it should be determined whether we want this metric to count in range scans or not. If so, fix the metric and enable the second test; if not, remove the second test

Sounds good to me.

**Closed** 2021-05-02 11:01 UTC
Labels: bug, dtest
