### ISSUE TITLE
crash at startup in  allocate_io_queues

### ISSUE THREAD

**Issue by benoit-canet** [scylladb/scylla#1157] opened 2016-03-31 18:22 UTC
## Installation details
Scylla version (or git commit hash):
Cluster size: 3
OS (RHEL/CentOS/Ubuntu/AWS AMI): ami-f90a0e93

## Hardware details (for performance issues)
Platform (physical/VM/cloud instance type/docker): vm
Hardware: sockets= cores= hyperthreading= memory= c3.4xlarge
Disks: (SSD/HDD, count)

with the following patch in order to reproduce #1144

    diff --git a/data_dir/scylla.yaml b/data_dir/scylla.yaml
    index 3bf390f..ca015b5 100644
    --- a/data_dir/scylla.yaml
    +++ b/data_dir/scylla.yaml
    @@ -63,4 +63,4 @@ databases: !mux
             db_type: scylla
             # Let's use c3.large since we're using iotune
             # and we'll stress the DB nodes more thoroughly
    -        instance_type_db: 'c3.large'
    +        instance_type_db: 'c3.4xlarge'
    diff --git a/grow_cluster_test.py b/grow_cluster_test.py
    index 5b7b873..6ba6306 100644
    --- a/grow_cluster_test.py
    +++ b/grow_cluster_test.py
    @@ -14,6 +14,7 @@
     # Copyright (c) 2016 ScyllaDB
  
     import logging
    +import time
  
     from avocado import main
  
    @@ -68,6 +69,20 @@ class GrowClusterTest(ClusterTester):
             """
             self.grow_cluster(cluster_target_size=5)
  
    +    def test_grow_3_to_4_while_filled(self):
    +        """
    +        Grow an already filled clusterShorter version of the cluster growth test.
    +
    +        1) Start a 1 node cluster
    +        2) Start cassandra-stress on the loader node
    +        3) wait 10 minutes some data fill the cluster
    +        3) Add a new node
    +        """
    +
    +        time.sleep(10 * 60)
    +        self.grow_cluster(cluster_target_size=1)
    +        time.sleep(10 * 60)
    +
         def test_grow_3_to_30(self):
             """
             1) Start a 1 node cluster

I get some:

    -collectd-poll-period 3000 --network-stack posix --cpuset 1-15 --smp 15 --num-io-queues 16 --max-io-requests 128
    18:02:58 cluster          L0269 ERROR| Node root-scylla-db-node-a9cce63a-1 [54.210.95.144 | 172.30.0.221] (seed: None):     Executable: /usr/bin/scylla
    18:02:58 cluster          L0269 ERROR| Node root-scylla-db-node-a9cce63a-1 [54.210.95.144 | 172.30.0.221] (seed: None):  Control Group: /system.slice/scylla-server.service
    18:02:58 cluster          L0269 ERROR| Node root-scylla-db-node-a9cce63a-1 [54.210.95.144 | 172.30.0.221] (seed: None):           Unit: scylla-server.service
    18:02:58 cluster          L0269 ERROR| Node root-scylla-db-node-a9cce63a-1 [54.210.95.144 | 172.30.0.221] (seed: None):          Slice: system.slice
    18:02:58 cluster          L0269 ERROR| Node root-scylla-db-node-a9cce63a-1 [54.210.95.144 | 172.30.0.221] (seed: None):        Boot ID: ed25b07ba2db4973a7b59cb1f44999c0
    18:02:58 cluster          L0269 ERROR| Node root-scylla-db-node-a9cce63a-1 [54.210.95.144 | 172.30.0.221] (seed: None):     Machine ID: 8ea3e6ea03b64d018847fcdf669935d4
    18:02:58 cluster          L0269 ERROR| Node root-scylla-db-node-a9cce63a-1 [54.210.95.144 | 172.30.0.221] (seed: None):       Hostname: ip-172-30-0-221
    18:02:58 cluster          L0269 ERROR| Node root-scylla-db-node-a9cce63a-1 [54.210.95.144 | 172.30.0.221] (seed: None):       Coredump: /var/lib/systemd/coredump/core.scylla.994.ed25b07ba2db4973a7b59cb1f44999c0.2543.1459447274000000.xz
    18:02:58 cluster          L0269 ERROR| Node root-scylla-db-node-a9cce63a-1 [54.210.95.144 | 172.30.0.221] (seed: None):        Message: Process 2543 (scylla) of user 994 dumped core.
    18:02:58 cluster          L0269 ERROR| Node root-scylla-db-node-a9cce63a-1 [54.210.95.144 | 172.30.0.221] (seed: None):              
    18:02:58 cluster          L0269 ERROR| Node root-scylla-db-node-a9cce63a-1 [54.210.95.144 | 172.30.0.221] (seed: None):                 Stack trace of thread 2543:
    18:02:58 cluster          L0269 ERROR| Node root-scylla-db-node-a9cce63a-1 [54.210.95.144 | 172.30.0.221] (seed: None):                 #0  0x00007faeee8675f7 raise (libc.so.6)
    18:02:58 cluster          L0269 ERROR| Node root-scylla-db-node-a9cce63a-1 [54.210.95.144 | 172.30.0.221] (seed: None):                 #1  0x00007faeee868ce8 abort (libc.so.6)
    18:02:58 cluster          L0269 ERROR| Node root-scylla-db-node-a9cce63a-1 [54.210.95.144 | 172.30.0.221] (seed: None):                 #2  0x00000000014d58fd _ZN9__gnu_cxx27__verbose_terminate_handlerEv (scylla)
    18:02:58 cluster          L0269 ERROR| Node root-scylla-db-node-a9cce63a-1 [54.210.95.144 | 172.30.0.221] (seed: None):                 #3  0x00000000014402f6 _ZN10__cxxabiv111__terminateEPFvvE (scylla)
    18:02:58 cluster          L0269 ERROR| Node root-scylla-db-node-a9cce63a-1 [54.210.95.144 | 172.30.0.221] (seed: None):                 #4  0x0000000001440341 _ZSt9terminatev (scylla)
    18:02:58 cluster          L0269 ERROR| Node root-scylla-db-node-a9cce63a-1 [54.210.95.144 | 172.30.0.221] (seed: None):                 #5  0x0000000001440449 __cxa_throw (scylla)
    18:02:58 cluster          L0269 ERROR| Node root-scylla-db-node-a9cce63a-1 [54.210.95.144 | 172.30.0.221] (seed: None):                 #6  0x000000000054a305 allocate_io_queues (scylla)
    18:02:58 cluster          L0269 ERROR| Node root-scylla-db-node-a9cce63a-1 [54.210.95.144 | 172.30.0.221] (seed: None):                 #7  0x0000000000516ebc _ZN3smp9configureEN5boost15program_options13variables_mapE (scylla)
    18:02:58 cluster          L0269 ERROR| Node root-scylla-db-node-a9cce63a-1 [54.210.95.144 | 172.30.0.221] (seed: None):                 #8  0x000000000056bc4c _ZN12app_template14run_deprecatedEiPPcOSt8functionIFvvEE (scylla)
    18:02:58 cluster          L0269 ERROR| Node root-scylla-db-node-a9cce63a-1 [54.210.95.144 | 172.30.0.221] (seed: None):                 #9  0x00000000004708d8 main (scylla)
    18:02:58 cluster          L0269 ERROR| Node root-scylla-db-node-a9cce63a-1 [54.210.95.144 | 172.30.0.221] (seed: None):                 #10 0x00007faeee853b15 __libc_start_main (libc.so.6)
    18:02:58 cluster          L0269 ERROR| Node root-scylla-db-node-a9cce63a-1 [54.210.95.144 | 172.30.0.221] (seed: None):                 #11 0x00000000004c74f5 _start (scylla)
    18:02:58 cluster          L0269 ERROR| Node root-scylla-db-node-a9cce63a-1 [54.210.95.144 | 172.30.0.221] (seed: None):
    18:02:58 cluster          L0269 ERROR| Node root-scylla-db-node-a9cce63a-1 [54.210.95.144 | 172.30.0.221] (seed: None):            PID: 2697 (scylla)
    18:02:58 cluster          L0269 ERROR| Node root-scylla-db-node-a9cce63a-1 [54.210.95.144 | 172.30.0.221] (seed: None):            UID: 994 (scylla)
    18:02:58 cluster          L0269 ERROR| Node root-scylla-db-node-a9cce63a-1 [54.210.95.144 | 172.30.0.221] (seed: None):            GID: 1001 (scylla)
    18:02:58 cluster          L0269 ERROR| Node root-scylla-db-node-a9cce63a-1 [54.210.95.144 | 172.30.0.221] (seed: None):         Signal: 6 (ABRT)
    18:02:58 cluster          L0269 ERROR| Node root-scylla-db-node-a9cce63a-1 [54.210.95.144 | 172.30.0.221] (seed: None):      Timestamp: jeu. 2016-03-31 18:01:15 UTC (1min 41s ago)

sample core can be found here:

    8:02:55 cluster          L0265 INFO | Node root-scylla-db-node-a9cce63a-2 [52.87.205.164 | 172.30.0.222] (seed: None): To download it, you may use 'curl --user-agent [user-agent] scylladb-users-upload.s3.amazonaws.com/core.scylla.994.a8bebdb074474805a2828792097e13f5.2797.1459447277000000/core.scylla.994.a8bebdb074474805a2828792097e13f5.2797.1459447277000000.xz > core.scylla.994.a8bebdb074474805a2828792097e13f5.2797.1459447277000000.xz'
    18:02:55 cluster          L0261 INFO | Node root-scylla-db-node-a9cce63a-2 [52.87.205.164 | 172.30.0.222] (seed: None): Uploading coredump /var/lib/systemd/coredump/core.scylla.994.a8bebdb074474805a2828792097e13f5.2572.1459447274000000.xz to scylladb-users-upload.s3.amazonaws.com/core.scylla.994.a8bebdb074474805a2828792097e13f5.2572.1459447274000000/core.scylla.994.a8bebdb074474805a2828792097e13f5.2572.1459447274000000.xz
    18:02:55 remote           L0773 DEBUG| Remote [centos@52.87.205.164]: Running 'sudo curl --request PUT --upload-file '/var/lib/systemd/coredump/core.scylla.994.a8bebdb074474805a2828792097e13f5.2572.1459447274000000.xz' 'scylladb-users-upload.s3.amazonaws.com/core.scylla.994.a8bebdb074474805a2828792097e13f5.2572.1459447274000000/core.scylla.994.a8bebdb074474805a2828792097e13f5.2572.1459447274000000.xz''
    18:02:55 remote           L0090 INFO | [52.87.205.164] Running '/bin/ssh -a -x  -o ControlPath=/var/tmp/ssh-masterw615u_/socket -o StrictHostKeyChecking=no -o UserKnownHostsFile=/var/tmp/tmpUiD76w -o BatchMode=yes -o ConnectTimeout=300 -o ServerAliveInterval=300 -l centos -p 22 -i /var/tmp/root-longevity-test-f64b3259.pem 52.87.205.164 "sudo curl --request PUT --upload-file '/var/lib/systemd/coredump/core.scylla.994.a8bebdb074474805a2828792097e13f5.2572.1459447274000000.xz' 'scylladb-users-upload.s3.amazonaws.com/core.scylla.994.a8bebdb074474805a2828792097e13f5.2572.1459447274000000/core.scylla.994.a8bebdb074474805a2828792097e13f5.2572.1459447274000000.xz'"'
    18:02:56 remote           L0182 DEBUG| [52.87.205.164] [stderr]   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
    18:02:56 remote           L0182 DEBUG| [52.87.205.164] [stderr]                                  Dload  Upload   Total   Spent    Left  Speed
    18:02:56 remote           L0182 DEBUG| [52.87.205.164] [stderr]
    18:02:56 remote           L0182 DEBUG| [52.87.205.164] [stderr]   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

**Comment by dorlaor** [comment] 2016-04-01 19:50
I bet @glommer will quickly know what's the issue.
Next time please load the stacktrace from the core using gdb.

**Comment by glommer** [comment] 2016-04-01 19:54
I don't see any kind of failures with I/O queue setup for a very long time,
and don't know what could have caused it.

With a backtrace I can take a look

**Comment by slivne** [comment] 2016-04-04 06:06
@benoit-canet - thanks for saving the core - user-agent id needs to be generated - you did not have one - so this ended up generating many directories at the root of the s3 scylladb-users-upload  bucket.

@tzach has instructions on how to download users samples of the s3 bucket.

**Comment by benoit-canet** [comment] 2016-04-04 11:55
@glauber: the backtrace is in the systemd log

**Comment by glommer** [comment] 2016-04-04 15:11
@benoit-canet the backtrace as print in the system log doesn't help much. All I can see is that it threw during allocation. If I could peak at the variables, maybe I could see something relevant - not necessarily, though, because most of the time they are just optimized away =(

I saw you have uploaded somewhere, but I don't see what's the user visible URL for that. How can I download it ?

**Comment by glommer** [comment] 2016-04-04 15:19
BTW, this is invalid:

```
-collectd-poll-period 3000 --network-stack posix --cpuset 1-15 --smp 15 --num-io-queues 16 --max-io-requests 128
```

We can't have 15 processors and 16 I/O queues. We should have caught this earlier and failed in some other way. But this is certainly not valid.

**Comment by glommer** [comment] 2016-04-04 15:23
Booting that same AMI into c3.4xlarge, the default command line is:
```
           └─2485 /usr/bin/scylla --log-to-syslog 1 --log-to-stdout 0 --default-log-level info --collectd-address=127.0.0.1:25826 --collectd=1 --collectd-poll-period 3000 --network-stack posix --cpuset 1-15 --smp 15 --num-io-queues 8 --max-io-requests 32
```

You didn't describe any changes to that, so I am wondering how is it that those I/O queue configurations came to be?

**Comment by glommer** [comment] 2016-04-04 15:41
I do see the following message when I try to start a system with the wrong # of queues:

```
terminate called after throwing an instance of 'std::runtime_error'
  what():  Invalid number of IO queues. Asked for 13. Minimum value is 1, maximum 12
```

**Comment by glommer** [comment] 2016-04-04 15:44
That error, though, will only be seen if the binaries are compiled with HWLOC support. Are we by any chance not doing that?

**Comment by glommer** [comment] 2016-04-04 15:52
Also note: this AMI is running 0.19 by default. Have you updated?

@benoit-canet , please be more specific about what changes have you made to the AMI. If it's running 0.19, then this is too old.

**Comment by lmr** [comment] 2016-04-06 20:32
@benoit-canet I have tried the reproducer you pasted with the GA AMI and couldn't reproduce it. The new node is added just fine.

**Comment by asias** [comment] 2016-04-14 07:48
I tested with '1.0.1' ami-d2f0e3b8. longevity commit 072d11b073aefdfd58e7267a401491fd268c4ada

avocado run grow_cluster_test.py:GrowClusterTest.test_grow_3_to_4_while_filled --multiplex data_dir/scylla.yaml --filter-only /run/regions/us_east_1 /run/databases/scylla

The test failed. I think it is due to streaming hang issue which Glauber's patch will fix. 

btw, it seems avocado will never complete if scylla hangs.  



```
2016-04-14 07:40:55,871 remote           L0182 DEBUG| [54.175.148.223] [stdout] Apr 14 07:40:56 ip-172-30-0-135 scylla[2213]:  [shard 0] messaging_service - Retry verb=17 to 172.30.0.25:0, retry=10: timeout in 600 seconds
2016-04-14 07:40:55,872 remote           L0182 DEBUG| [54.175.148.223] [stdout] Apr 14 07:40:56 ip-172-30-0-135 scylla[2213]:  [shard 0] messaging_service - Retry verb=17 to 172.30.0.25:0, retry=10: timeout in 600 seconds
2016-04-14 07:40:55,876 remote           L0182 DEBUG| [54.175.148.223] [stdout] Apr 14 07:40:56 ip-172-30-0-135 scylla[2213]:  [shard 0] messaging_service - Retry verb=17 to 172.30.0.25:0, retry=10: timeout in 600 seconds
```

**Comment by benoit-canet** [comment] 2016-04-18 18:23
@glommer sorry for the late response:  I didn't changed anything in the AMI.

**Comment by glommer** [comment] 2016-05-04 15:53
Can we close this? There is no reason to believe this bug still exists. Even when it was reported it was already using an outdated version.

**Closed** 2016-05-18 12:22 UTC
Labels: bug, high
