### ISSUE TITLE
DTEST consistency_test.py:TestConsistency.short_read_quorum_delete_test short_read_quorum_delete_test  failing

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla#479] opened 2015-10-21 06:55 UTC
using commit cf734132e7c2a925d784a276fd49f30969d36ddb
Merge: 93c1035 02732f1
Author: Avi Kivity avi@scylladb.com
Date:   Tue Oct 20 17:36:57 2015 +0300

```
Merge "Flusing of CF:s without replay positions" from Calle

"Fixes: #469

We occasionally generate memtables that are not empty, yet have no
high replay_position set. (Typical case is CL replay, but apparently
there are others).

Moreover, we can do this repeatedly, and thus get caught in the flush
queue ordering restrictions.

Solve this by treating a flush without replay_position as a flush at the
highest running position, i.e. "last" in queue. Note that this will not
affect the actual flush operation, nor CL callbacks, only anyone waiting
for the operation(s) to complete.

To do this, the flush_queue had its restrictions eased, and some introspection
methods added."
```

```
pkill -9 scylla;  rm -Rf ~/.dtest/*;KEEP_TEST_DIR=true nosetests -v -s consistency_test.py:TestConsistency.short_read_quorum_delete_test
short_read_quorum_delete_test (consistency_test.TestConsistency) ... FAIL

======================================================================
FAIL: short_read_quorum_delete_test (consistency_test.TestConsistency)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/shlomi/urchin-dtest/consistency_test.py", line 697, in short_read_quorum_delete_test
    assert_none(session, "SELECT * FROM t WHERE id = 0 LIMIT 1", cl=ConsistencyLevel.QUORUM)
  File "/home/shlomi/urchin-dtest/assertions.py", line 40, in assert_none
    assert list_res == [], "Expected nothing from %s, but got %s" % (query, list_res)
AssertionError: Expected nothing from SELECT * FROM t WHERE id = 0 LIMIT 1, but got [[0, 1]]
-------------------- >> begin captured logging << --------------------
dtest: DEBUG: cluster ccm directory: /home/shlomi/.dtest/dtest-Hk2FCF
cassandra.cluster: WARNING: Host 127.0.0.2 has been marked down
cassandra.pool: WARNING: Error attempting to reconnect to 127.0.0.2, scheduling retry in 2.0 seconds: [Errno 111] Tried connecting to [('127.0.0.2', 9042)]. Last error: Connection refused
cassandra.cluster: WARNING: Host 127.0.0.1 has been marked down
cassandra.pool: WARNING: Error attempting to reconnect to 127.0.0.1, scheduling retry in 2.0 seconds: [Errno 111] Tried connecting to [('127.0.0.1', 9042)]. Last error: Connection refused
cassandra.pool: WARNING: Error attempting to reconnect to 127.0.0.1, scheduling retry in 4.0 seconds: [Errno 111] Tried connecting to [('127.0.0.1', 9042)]. Last error: Connection refused
cassandra.cluster: WARNING: Failed to create connection pool for new host 127.0.0.1:
Traceback (most recent call last):
  File "cassandra/cluster.py", line 1831, in cassandra.cluster.Session.add_or_renew_pool.run_add_or_renew_pool (cassandra/cluster.c:31324)
    new_pool = HostConnection(host, distance, self)
  File "cassandra/pool.py", line 295, in cassandra.pool.HostConnection.__init__ (cassandra/pool.c:6160)
    self._connection = session.cluster.connection_factory(host.address)
  File "cassandra/cluster.py", line 785, in cassandra.cluster.Cluster.connection_factory (cassandra/cluster.c:9335)
    return self.connection_class.factory(address, self.connect_timeout, *args, **kwargs)
  File "cassandra/connection.py", line 304, in cassandra.connection.Connection.factory (cassandra/connection.c:5114)
    conn = cls(host, *args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/cassandra/io/libevreactor.py", line 264, in __init__
    self._connect_socket()
  File "cassandra/connection.py", line 338, in cassandra.connection.Connection._connect_socket (cassandra/connection.c:6246)
    raise socket.error(sockerr.errno, "Tried connecting to %s. Last error: %s" % ([a[4] for a in addresses], sockerr.strerror or sockerr))
error: [Errno 111] Tried connecting to [('127.0.0.1', 9042)]. Last error: Connection refused
cassandra.cluster: WARNING: Host 127.0.0.1 has been marked down
--------------------- >> end captured logging << ---------------------

----------------------------------------------------------------------
Ran 1 test in 87.272s

FAILED (failures=1)
```

**Comment by gleb-cloudius** [comment] 2015-10-21 14:22
I cannot reproduce this by running these steps manually:

start cluster of three nodes 1 2 3.

CREATE KEYSPACE ks WITH replication={'class': 'SimpleStrategy', 'replication_factor': '3'};
CREATE TABLE t (id int, v int, PRIMARY KEY(id, v)) WITH read_repair_chance = 0.0;

consistency all;
INSERT INTO t (id, v) VALUES (0, 1);
INSERT INTO t (id, v) VALUES (0, 2)

stop 2

consistency QUORUM;
DELETE FROM t WHERE id = 0 AND v = 1;

start 2

stop 1

consistency QUORUM;
DELETE FROM t WHERE id = 0 AND v = 2;

start 1

stop 3
SELECT * FROM t WHERE id = 0 LIMIT 1;

I get empty reply.

--
			Gleb.

**Comment by slivne** [comment] 2015-10-29 10:46
I think I found the issue and it means that we have a bug.

If I change the test in this manner 

```
shlomi@localhost~/urchin-dtest (master)$ git diff
diff --git a/consistency_test.py b/consistency_test.py
index 1190ae6..5916fb9 100644
--- a/consistency_test.py
+++ b/consistency_test.py
@@ -693,7 +693,7 @@ class TestConsistency(Tester):
         session = self.patient_cql_connection(node1, 'ks')
 
         # we read the first row in the partition (so with a LIMIT 1) and A and B answer first.
-        node3.stop()
+        node3.stop(wait_other_notice=True)
         assert_none(session, "SELECT * FROM t WHERE id = 0 LIMIT 1", cl=ConsistencyLevel.QUORUM)
```

it will pass

The change waits after killing node3 to verify that both node1,node2 have seen that node3 is down - by checking their log files.

So the issue seems to be that we count no responses from failed nodes in some manner instead of not counting them

I'll try to create a simple test for this to prove it and close this isse for now and apply the above patch

**Comment by slivne** [comment] 2015-10-31 00:09
@gleb-cloudius  was right, I was not able to find a simpler scenario that has this issue ... so the above is incorrect.

After doing some printf debugging the issue is in digest_read_resolver::digest_match

```
        auto& first = *_digest_results.begin();
        return std::find_if(_digest_results.begin() + 1, _digest_results.end(), [&first] (query::result_digest digest) { return digest != first; }) == _digest_results.begin();
```

this is incorrect:

Example:
Two Items that do not match A,B
first = A
std::find_if ... will return B - as  they do not match
comparing this to B would return true,

the fix is to compare to first.

sending a patch

**Comment by gleb-cloudius** [comment] 2015-10-31 06:24
On Fri, Oct 30, 2015 at 05:09:33PM -0700, slivne wrote:
> @gleb-cloudius  was right, I was not able to find a simpler scenario that has this issue ... so the above is incorrect.
> 
> After doing some printf debugging the issue is in digest_read_resolver::digest_match
> 
> ```
>         auto& first = *_digest_results.begin();
>         return std::find_if(_digest_results.begin() + 1, _digest_results.end(), [&first] (query::result_digest digest) { return digest != first; }) == _digest_results.begin();
> ```
> 
> this is incorrect:
> 
> Example:
> Two Items that do not match A,B
> first = A
> std::find_if ... will return B - as  they do not match
> comparing this to B would return true,
> 
Why would it be compared to B? _digest_results.end() is not B.

> the fix is to compare to first.
> 
That will make all digests always mismatch since the result will never
be _digest_results.begin().

> sending a patch
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/scylladb/scylla/issues/479#issuecomment-152676983

--
			Gleb.

**Comment by duarten** [comment] 2018-04-28 16:57
Closing, as this is working now.

**Closed by duarten** 2018-04-28 16:57 UTC
Labels: bug
