### ISSUE TITLE
Support Cassandra 3.0 disk storage format

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#1271] opened 2016-05-18 12:27 UTC
Cassandra 3.0 [introduce new storage format](http://www.datastax.com/2015/12/storage-engine-30) with reduce space.
Scylla will have similar benefits from the new format

**Comment by tzach** [comment] 2016-05-18 12:28
related Cassandra issue: [New sstable format with support for columnar layout](https://issues.apache.org/jira/browse/CASSANDRA-7447)

**Comment by duarten** [comment] 2018-04-28 16:52
Closing as duplicate of #1969.

**Closed by duarten** 2018-04-28 16:52 UTC
Labels: enhancement
