### ISSUE TITLE
CDC: Generation has too few streams

### ISSUE THREAD

**Issue by piodul** [scylladb/scylla#5812] opened 2020-02-14 16:03 UTC
When setting up a new cluster with ccm, sometimes the last generation has fewer streams then the total number of vnodes in the cluster. The following script:

```python
from cassandra.cluster import Cluster

c = Cluster()
s = c.connect()

desc = s.execute("SELECT * FROM system_distributed.cdc_description")
topo_desc = s.execute("SELECT * FROM system_distributed.cdc_topology_description")

print("Generations:")
for d, td in zip(desc, topo_desc):
    print("  description:          {} | {}".format(d.time, len(d.streams)))
    print("  topology_description: {} | {}".format(td.time, len(td.description)))
    print("")
```

generated the following output:

```
[piodul@localhost cdc-tests]$ python streams.py 
Generations:
  description:          2020-02-14 13:41:58.113000 | 256
  topology_description: 2020-02-14 13:41:58.113000 | 256

  description:          2020-02-14 13:42:01.838000 | 511
  topology_description: 2020-02-14 13:42:01.838000 | 512

  description:          2020-02-14 13:42:02.028000 | 512
  topology_description: 2020-02-14 13:42:02.028000 | 512
```

The cluster was configured to have 256 tokens per node, and had 3 nodes, so the last generation should have 768 streams.
Please note that the discrepancy between 511 and 512 in the second generation comes from the fact that the cluster failed to generate a stream for one of the vnodes - this happens sometimes and is normal.

**Comment by slivne** [comment] 2020-02-16 19:12
@piodul the following comment 

> Please note that the discrepancy between 511 and 512 in the second generation comes from the fact that the cluster failed to generate a stream for one of the vnodes - this happens sometimes and is normal.

makes it hard o understand if there is a bug or not

**Comment by slivne** [comment] 2020-02-16 19:13
I am currently marking for 3.4 - assuming this is a bug

**Comment by haaawk** [comment] 2020-02-17 06:41
This will be fixed by custom partitioner I'm working on. One of the steps is waiting for @avikivity and @nyh re-reviews. Then I will be able to do the final step which is using custom partitioner for CDC and that would guarantee the success and good performance of stream generation.

**Comment by haaawk** [comment] 2020-02-28 09:34
Actually this problem is caused by tests starting multiple nodes at the same time. CDC assumes nodes will be added to the cluster one by one. To avoid this problem we need to make sure tests start nodes sequentially.

**Comment by denesb** [comment] 2020-02-28 10:01
@haaawk AFAIK this also happens sometimes in production clusters, to spin up a new DC. Add a bunch of new nodes with `auto_bootstrap=false`, then rebuild the DC. Someone with more operations experience (@glommer) will be able to confirm/dismiss.

**Comment by asias** [comment] 2020-03-12 06:31
> @haaawk AFAIK this also happens sometimes in production clusters, to spin up a new DC. Add a bunch of new nodes with `auto_bootstrap=false`, then rebuild the DC. Someone with more operations experience (@glommer) will be able to confirm/dismiss.

No need to set `auto_bootstrap=false` when adding new DC.  

Say we have dc1, now we want to add dc2. 

1. Before we have RF = {dc1:3}, the new dc2 is not in the RF
2. Bootstrap nodes in dc2 with auto_boostrap = true
3. Set RF = {dc1:3, dc2:3}
4. Run rebuild on all nodes 

Since we have zero replica in dc2 when bootstrap nodes in dc2, nodes will bootstrap fast without streaming data for that keyspace. There is no point to set auto_bootstrap=false to reduce possible restream if we add more nodes in dc2.

**Comment by asias** [comment] 2020-03-12 06:34
IIUC, the root cause is that nodes join the cluster in parallel without knowing all other nodes and having wrong view about tokens in the ring when generating cdc streams.

**Comment by haaawk** [comment] 2020-06-01 10:42
Joining multiple nodes at the same time is not allowed.

**Closed by haaawk** 2020-06-01 10:42 UTC
Labels: CDC, bug
