### ISSUE TITLE
lost connection when execute cql "select * from table where secindex_field= null"

### ISSUE THREAD

**Issue by TDtianzhenjiu** [scylladb/scylla#8489] opened 2021-04-15 03:04 UTC
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (Scylla version 4.3.2):
OS (CentOSI):

**Comment by raphaelsc** [comment] 2021-04-15 13:49
We can't really debug this unless more info is provided. Please share logs, schema, error messages, whatever else you find may be useful for debugging this.

**Comment by psarna** [comment] 2021-04-15 14:09
Actually, we used to just disallow comparisons against NULL until 37ebe521e3d6b7809eb88f9f05db937ccfe7ad6e .
With indexes the case is more interesting. I think that queries which wants to compare an indexed value to NULL should still need filtering, because the index will not store values for NULL - due to the fact that the indexed column is part of the index key and we don't allow NULL keys. Still, the base table can contain rows with this column equal to NULL. Another option is to somehow index NULL as well, but that seems overly complex.

/cc @dekimir

**Comment by nyh** [comment] 2021-04-15 18:02
> We can't really investigate this unless more info is provided. Please share logs, schema, error messages, whatever else you find may be useful for debugging this.

Actually, while the original report is extremely terse (just the title line...), I think it is pretty clear, and the right thing to do now is to write a test (cql-pytest) for exactly the situation he describes (if we don't already have a test convering it), and seeing exactly what happens. We can also check the same thing on a non-indexed column, and check if/how it differs - and of course run the same tests also in Cassandra whether we forgot to implement a feature we should implement.

**Comment by nyh** [comment] 2021-04-18 08:28
> Actually, we used to just disallow comparisons against NULL until [37ebe52](https://github.com/scylladb/scylla/commit/37ebe521e3d6b7809eb88f9f05db937ccfe7ad6e) .

That case (ALLOW FILTERING, without an index) now appears to work, but return a wrong (i.e., non-useful) result - it always returns nothing. This is issue #4776. The implementation for filtering and indexing is different, but we need to at least decide what is the **correct** behavior, and both implementations should implement the same correct behavior. I'm now in the process of writing tests for both.

**Comment by nyh** [comment] 2021-04-18 12:55
I wrote a test for this case, and it doesn't reproduce the problem which @TDtianzhenjiu reported. I expected to see some sort of error or broken connection causing a lost connection, but instead it just successfully returned an empty result set. This is consistent with the behavior documented in #4776 for the no-index case (the "where v=null" doesn't match anything because nothing is equal null - not even null)).

So my current guess (@dekimir can you confirm or deny?) is that @TDtianzhenjiu 's problem is a combination of the following issues:
1. The "where v=NULL" restriction done with filtering, even though there is no "ALLOW FILTERING" in the request.
2. This filtering doesn't match anything (this is #4776).
3. When filtering doesn't match anything and there is a huge amount of data, the request can timeout.

If this guess is the real explanation, this issue should be closed in favor of three smaller issues (some of whom already exist).

**Comment by dekimir** [comment] 2021-04-18 15:29
> So my current guess (@dekimir can you confirm or deny?) is that @TDtianzhenjiu 's problem is a combination of the following issues

I'm not sure how I can confirm this.  We need more details from the OP.

**Comment by nyh** [comment] 2021-04-18 15:53
> I'm not sure how I can confirm this. We need more details from the OP.

What I wanted a confirmation for was mainly for point 1 above - that when a do "where v=NULL", even though there is an index on v, it is not used and filtering is done instead - even when there is no "ALLOW FILTERING"... If this is the case, then this is a bug - because filtering should not be allowed without ALLOW FILTERING... but I'm not 100% sure why it explains the broken connection... I thought that a paged request should return an empty page, and not timeout. Maybe @TDtianzhenjiu disabled paging for this query?

Yes, it would be useful if @TDtianzhenjiu could respond with a few details on what query he tried exactly, how much data does the query need to filter, and what error he got exactly.

**Comment by nyh** [comment] 2021-04-18 18:02
Another old issue which might be relevant here if the query uses filtering: #4147 (scylla crashes when select * with secondary index on large datase).

**Comment by nyh** [comment] 2021-04-19 21:50
@TDtianzhenjiu we need more information to understand exactly which query you run, how, and what you mean by a "lost connection". Without this information, we will need to close this issue.

But in any case, as explained in #4776, the restriction `WHERE field = NULL` is not a useful one - it will not match any rows, and this is by design. So in any case it should be pointless for you to send such a request. 

In issue #8517 we propose to add a new syntax `WHERE field IS NULL` to do what you wanted, but this new syntax is not yet implemented, and moreover - even when we do implement it, it is unlikely to be supported for secondary indexes. The problem is how Scylla's secondary indexes are based on materialized views - and materialized views ignore rows whose partition is unset (NULL) - rather than creating a partition with a NULL key.

**Comment by nyh** [comment] 2021-08-02 15:28
I'm closing this issue, lacking response from the submitter.

@dekimir before I do I have one last question maybe you can help me:

I verified in a test that the restriction "WHERE v=NULL" when v is an indexed column does **not** require ALLOW FILTERING. This is fine - this silly restriction will never match anything (nothing equals NULL) so it doesn't need to read any data at all. However, I wanted to verify  what exactly happens in the low level in this case. Do we try to look for a "null" parttiton in the index table and find  nothing? That would be good. What would be bad is if we saw that null is suspicious so stopped using the index for this query and reverted to using filtering. I want to know that nothing like that is happening, but I don't know how to test this - so I was hoping you're familiar with the code and can answer off-hand.

**Closed** 2021-08-02 15:28 UTC
Labels: CQL, sec-index

**Comment by dekimir** [comment] 2021-08-02 21:37
When deciding to use an index, we generally don't look at the RHS of restrictions.  But when we form a global-index query, a NULL RHS will result in an empty partition_range_vector:
https://github.com/scylladb/scylla/blob/0eb2eb1b446de4a3f0200b2a495df969fdd30f32/cql3/statements/select_statement.cc#L1142-L1150

And an empty partition_range_vector results in no storage access:
https://github.com/scylladb/scylla/blob/0eb2eb1b446de4a3f0200b2a495df969fdd30f32/service/storage_proxy.cc#L4341-L4343
