### ISSUE TITLE
Reactor stalls following suppressed 4294967292 backtraces

### ISSUE THREAD

**Issue by bentsi** [scylladb/scylla#4945] opened 2019-09-02 17:38 UTC
*Installation details*
Scylla version (or git commit hash): 3.1.0.rc4-0.20190830.d70c2db09
Cluster size: 4
OS (RHEL/CentOS/Ubuntu/AWS AMI): ami-04b9560705a3975d1

```
2019-09-02T14:52:19+00:00  ip-10-0-102-110 !INFO    | scylla: [shard 3] stream_session - [Stream #f3276220-cd90-11e9-9ec7-000000000004] Write to sstable for ks=keyspace
1, cf=standard1, estimated_partitions=5712819, received_partitions=774771
2019-09-02T14:52:20+00:00  ip-10-0-102-110 !INFO    | scylla: [shard 0] compaction - Compacted 1 sstables to [/var/lib/scylla/data/keyspace1/standard1-fd01ae50cc9511e99
c5d00000000000a/mc-364588-big-Data.db:level=2, ]. 170750490 bytes to 170662274 (~99% of original) in 3888ms = 41.86MB/s. ~157952 total partitions merged to 157899.
2019-09-02T14:52:20+00:00  ip-10-0-102-110 !INFO    | scylla: [shard 0] compaction - Compacting [/var/lib/scylla/data/keyspace1/standard1-fd01ae50cc9511e99c5d0000000000
0a/mc-364574-big-Data.db:level=1, ]
2019-09-02T14:52:21+00:00  ip-10-0-102-110 !INFO    | scylla: [shard 0] compaction - Compacted 1 sstables to [/var/lib/scylla/data/keyspace1/standard1-fd01ae50cc9511e99
c5d00000000000a/mc-364602-big-Data.db:level=2, ]. 34211919 bytes to 34064669 (~99% of original) in 951ms = 34.16MB/s. ~31744 total partitions merged to 31491.
2019-09-02T14:52:21+00:00  ip-10-0-102-110 !INFO    | scylla: [shard 0] compaction - Compacting [/var/lib/scylla/data/keyspace1/standard1-fd01ae50cc9511e99c5d0000000000
0a/mc-364392-big-Data.db:level=1, ]
2019-09-02T14:52:22+00:00  ip-10-0-102-110 !INFO    | scylla: [shard 12] compaction - Compacted 1 sstables to [/var/lib/scylla/data/keyspace1/standard1-fd01ae50cc9511e9
9c5d00000000000a/mc-370900-big-Data.db:level=2, ]. 170758449 bytes to 170469856 (~99% of original) in 3708ms = 43.84MB/s. ~157952 total partitions merged to 157829.
2019-09-02T14:52:22+00:00  ip-10-0-102-110 !INFO    | scylla: [shard 12] compaction - Compacting [/var/lib/scylla/data/keyspace1/standard1-fd01ae50cc9511e99c5d00000000000a/mc-370746-big-Data.db:level=1, ]
2019-09-02T14:52:23+00:00  ip-10-0-102-110 !INFO    | scylla: Rate-limit: supressed 4294967292 backtraces on shard 10
2019-09-02T14:52:24+00:00  ip-10-0-102-110 !INFO    | scylla: Reactor stalled for 658 ms on shard 4.
2019-09-02T14:52:24+00:00  ip-10-0-102-110 !INFO    | scylla: Backtrace:
2019-09-02T14:52:24+00:00  ip-10-0-102-110 !INFO    | scylla: 0x0000000004180372
2019-09-02T14:52:24+00:00  ip-10-0-102-110 !INFO    | scylla: 0x000000000406d3f5
2019-09-02T14:52:24+00:00  ip-10-0-102-110 !INFO    | scylla: 0x000000000406d935
2019-09-02T14:52:24+00:00  ip-10-0-102-110 !INFO    | scylla: 0x000000000406dc27
2019-09-02T14:52:24+00:00  ip-10-0-102-110 !INFO    | scylla: 0x00007fb1c447f02f
2019-09-02T14:52:24+00:00  ip-10-0-102-110 !INFO    | scylla: 0x0000000000ec4188
2019-09-02T14:52:24+00:00  ip-10-0-102-110 !INFO    | scylla: 0x0000000000efbf4c
2019-09-02T14:52:24+00:00  ip-10-0-102-110 !INFO    | scylla: 0x0000000000d78655
2019-09-02T14:52:24+00:00  ip-10-0-102-110 !INFO    | scylla: 0x0000000000d95f4b
2019-09-02T14:52:24+00:00  ip-10-0-102-110 !INFO    | scylla: 0x0000000000d9687a
2019-09-02T14:52:24+00:00  ip-10-0-102-110 !INFO    | scylla: 0x0000000000daecef
2019-09-02T14:52:24+00:00  ip-10-0-102-110 !INFO    | scylla: 0x0000000000dbefde
2019-09-02T14:52:24+00:00  ip-10-0-102-110 !INFO    | scylla: 0x0000000000dbfe73
2019-09-02T14:52:24+00:00  ip-10-0-102-110 !INFO    | scylla: 0x0000000000dc02d4
2019-09-02T14:52:24+00:00  ip-10-0-102-110 !INFO    | scylla: 0x0000000000b714dd
2019-09-02T14:52:24+00:00  ip-10-0-102-110 !INFO    | scylla: 0x00000000031251e5
2019-09-02T14:52:24+00:00  ip-10-0-102-110 !INFO    | scylla: 0x000000000406a8e1
2019-09-02T14:52:24+00:00  ip-10-0-102-110 !INFO    | scylla: 0x000000000406aade
2019-09-02T14:52:24+00:00  ip-10-0-102-110 !INFO    | scylla: 0x000000000414cb2d
2019-09-02T14:52:24+00:00  ip-10-0-102-110 !INFO    | scylla: 0x000000000417716b
2019-09-02T14:52:24+00:00  ip-10-0-102-110 !INFO    | scylla: 0x0000000004038b9d
2019-09-02T14:52:24+00:00  ip-10-0-102-110 !INFO    | scylla: /opt/scylladb/libreloc/libpthread.so.0+0x000000000000858d
2019-09-02T14:52:24+00:00  ip-10-0-102-110 !INFO    | scylla: /opt/scylladb/libreloc/libc.so.6+0x00000000000fd6a2
2019-09-02T14:52:24+00:00  ip-10-0-102-110 !INFO    | scylla: [shard 4] stream_session - [Stream #f3276220-cd90-11e9-9ec7-000000000004] Write to sstable for ks=keyspace1, cf=standard1, estimated_partitions=5651617, received_partitions=778945
2019-09-02T14:52:25+00:00  ip-10-0-102-110 !INFO    | scylla: [shard 0] compaction - Compacted 1 sstables to [/var/lib/scylla/data/keyspace1/standard1-fd01ae50cc9511e99c5d00000000000a/mc-364616-big-Data.db:level=2, ]. 170753076 bytes to 170463608 (~99% of original) in 4349ms = 37.38MB/s. ~157952 total partitions merged to 157829.
```
translated backtrace:
```
	void seastar::backtrace<seastar::backtrace_buffer::append_backtrace()::{lambda(seastar::frame)#1}>(seastar::backtrace_buffer::append_backtrace()::{lambda(seastar::frame)#1}&&) at /usr/include/boost/program_options/variables_map.hpp:146
seastar::backtrace_buffer::append_backtrace() at /usr/include/boost/program_options/variables_map.hpp:146
 (inlined by) print_with_backtrace at /jenkins/workspace/scylla-3.1/relocatable-pkg/scylla/seastar/build/release/../../src/core/reactor.cc:1104
seastar::internal::cpu_stall_detector::generate_trace() at /usr/include/boost/program_options/variables_map.hpp:146
seastar::internal::cpu_stall_detector::maybe_report() at /usr/include/boost/program_options/variables_map.hpp:146
 (inlined by) seastar::internal::cpu_stall_detector::on_signal() at /jenkins/workspace/scylla-3.1/relocatable-pkg/scylla/seastar/build/release/../../src/core/reactor.cc:1476
 (inlined by) seastar::internal::cpu_stall_detector::on_signal() at /jenkins/workspace/scylla-3.1/relocatable-pkg/scylla/seastar/build/release/../../src/core/reactor.cc:1474
 (inlined by) seastar::reactor::block_notifier(int) at /jenkins/workspace/scylla-3.1/relocatable-pkg/scylla/seastar/build/release/../../src/core/reactor.cc:1597
?? ??:0
logalloc::occupancy_stats::operator+=(logalloc::occupancy_stats const&) at /jenkins/workspace/scylla-3.1/relocatable-pkg/scylla/./utils/logalloc.hh:518
 (inlined by) logalloc::region_impl::free(void*, unsigned long) at /jenkins/workspace/scylla-3.1/relocatable-pkg/scylla/utils/logalloc.cc:1460
mutation_partition::clear_gently(cache_tracker*) at crtstuff.c:?
 (inlined by) auto current_deleter<rows_entry>()::{lambda(rows_entry*)#1}::operator()(rows_entry*) const at /jenkins/workspace/scylla-3.1/relocatable-pkg/scylla/./utils/allocation_strategy.hh:238
 (inlined by) intrusive_set_external_comparator<rows_entry, &rows_entry::_link>::iterator intrusive_set_external_comparator<rows_entry, &rows_entry::_link>::erase_and_dispose<auto current_deleter<rows_entry>()::{lambda(rows_entry*)#1}>(intrusive_set_external_comparator<rows_entry, &rows_entry::_link>::const_iterator, auto current_deleter<rows_entry>()::{lambda(rows_entry*)#1}) at /jenkins/workspace/scylla-3.1/relocatable-pkg/scylla/intrusive_set_external_comparator.hh:211
 (inlined by) mutation_partition::clear_gently(cache_tracker*) at /jenkins/workspace/scylla-3.1/relocatable-pkg/scylla/mutation_partition.cc:2303
remove_or_mark_as_unique_owner(partition_version*, mutation_cleaner*) at partition_version.cc:?
 (inlined by) mutation_cleaner_impl::destroy_gently(partition_version&) at /jenkins/workspace/scylla-3.1/relocatable-pkg/scylla/mutation_cleaner.hh:84
 (inlined by) mutation_cleaner::destroy_gently(partition_version&) at /jenkins/workspace/scylla-3.1/relocatable-pkg/scylla/mutation_cleaner.hh:156
 (inlined by) remove_or_mark_as_unique_owner at /jenkins/workspace/scylla-3.1/relocatable-pkg/scylla/partition_version.cc:38
row_cache::invalidate_unwrapped(nonwrapping_range<dht::ring_position> const&) at crtstuff.c:?
 (inlined by) operator()<cache_entry*> at /jenkins/workspace/scylla-3.1/relocatable-pkg/scylla/row_cache.cc:1133
 (inlined by) erase_and_dispose<row_cache::invalidate_unwrapped(const partition_range&)::<lambda()>::<lambda(auto:108&&)> > at /usr/include/boost/intrusive/bstree.hpp:1500
 (inlined by) private_erase<row_cache::invalidate_unwrapped(const partition_range&)::<lambda()>::<lambda(auto:108&&)> > at /usr/include/boost/intrusive/bstree.hpp:2111
 (inlined by) erase_and_dispose<row_cache::invalidate_unwrapped(const partition_range&)::<lambda()>::<lambda(auto:108&&)> > at /usr/include/boost/intrusive/bstree.hpp:1540
 (inlined by) operator() at /jenkins/workspace/scylla-3.1/relocatable-pkg/scylla/row_cache.cc:1135
 (inlined by) with_allocator<row_cache::invalidate_unwrapped(const partition_range&)::<lambda()> > at /jenkins/workspace/scylla-3.1/relocatable-pkg/scylla/./utils/allocation_strategy.hh:307
 (inlined by) row_cache::invalidate_unwrapped(nonwrapping_range<dht::ring_position> const&) at /jenkins/workspace/scylla-3.1/relocatable-pkg/scylla/row_cache.cc:1130
std::_Function_handler<seastar::future<> (), row_cache::invalidate(seastar::noncopyable_function<void ()>, std::vector<nonwrapping_range<dht::ring_position>, std::allocator<nonwrapping_range<dht::ring_position> > >&&)::{lambda()#1}>::_M_invoke(std::_Any_data const&) at row_cache.cc:?
 (inlined by) with_linearized_managed_bytes<row_cache::invalidate(row_cache::external_updater, dht::partition_range_vector&&)::<lambda()>::<lambda()> > at /jenkins/workspace/scylla-3.1/relocatable-pkg/scylla/./utils/managed_bytes.hh:428
 (inlined by) operator() at /jenkins/workspace/scylla-3.1/relocatable-pkg/scylla/row_cache.cc:1110
 (inlined by) _M_invoke at /usr/include/c++/8/bits/std_function.h:283
_ZZN9row_cache9do_updateEN7seastar20noncopyable_functionIFvvEEESt8functionIFNS0_6futureIJEEEvEEENUlT_E0_clINS0_15semaphore_unitsINS0_35semaphore_default_exception_factoryENSt6chrono3_V212steady_clockEEEEEDaS9_ at row_cache.cc:?
 (inlined by) operator() at /jenkins/workspace/scylla-3.1/relocatable-pkg/scylla/row_cache.cc:1272
 (inlined by) apply<row_cache::do_update(row_cache::external_updater, row_cache::internal_updater)::<lambda(auto:109)> mutable [with auto:109 = seastar::semaphore_units<>]::<lambda()> > at /jenkins/workspace/scylla-3.1/relocatable-pkg/scylla/seastar/include/seastar/core/future.hh:1402
 (inlined by) futurize_apply<row_cache::do_update(row_cache::external_updater, row_cache::internal_updater)::<lambda(auto:109)> mutable [with auto:109 = seastar::semaphore_units<>]::<lambda()> > at /jenkins/workspace/scylla-3.1/relocatable-pkg/scylla/seastar/include/seastar/core/future.hh:1474
 (inlined by) operator()<seastar::semaphore_units<> > at /jenkins/workspace/scylla-3.1/relocatable-pkg/scylla/row_cache.cc:1279
row_cache::do_update(seastar::noncopyable_function<void ()>, std::function<seastar::future<> ()>) at crtstuff.c:?
 (inlined by) apply<row_cache::do_update(row_cache::external_updater, row_cache::internal_updater)::<lambda(auto:109)>, seastar::semaphore_units<seastar::semaphore_default_exception_factory, std::chrono::_V2::steady_clock> > at /jenkins/workspace/scylla-3.1/relocatable-pkg/scylla/seastar/include/seastar/core/apply.hh:43
 (inlined by) apply<row_cache::do_update(row_cache::external_updater, row_cache::internal_updater)::<lambda(auto:109)>, seastar::semaphore_units<seastar::semaphore_default_exception_factory, std::chrono::_V2::steady_clock> > at /jenkins/workspace/scylla-3.1/relocatable-pkg/scylla/seastar/include/seastar/core/future.hh:1392
 (inlined by) then_impl<row_cache::do_update(row_cache::external_updater, row_cache::internal_updater)::<lambda(auto:109)> > at /jenkins/workspace/scylla-3.1/relocatable-pkg/scylla/seastar/include/seastar/core/future.hh:936
 (inlined by) then<row_cache::do_update(row_cache::external_updater, row_cache::internal_updater)::<lambda(auto:109)> > at /jenkins/workspace/scylla-3.1/relocatable-pkg/scylla/seastar/include/seastar/core/future.hh:917
 (inlined by) row_cache::do_update(seastar::noncopyable_function<void ()>, std::function<seastar::future<> ()>) at /jenkins/workspace/scylla-3.1/relocatable-pkg/scylla/row_cache.cc:1280
row_cache::invalidate(seastar::noncopyable_function<void ()>, std::vector<nonwrapping_range<dht::ring_position>, std::allocator<nonwrapping_range<dht::ring_position> > >&&) at crtstuff.c:?
row_cache::invalidate(seastar::noncopyable_function<void ()>, nonwrapping_range<dht::ring_position> const&) at crtstuff.c:?
table::add_sstable_and_update_cache(seastar::lw_shared_ptr<sstables::sstable>) at crtstuff.c:?
seastar::continuation<seastar::future<> seastar::future<>::then_impl<streaming::stream_session::init_messaging_service_handler()::{lambda(seastar::rpc::client_info const&, utils::UUID, utils::UUID, utils::UUID, unsigned long, seastar::rpc::optional<streaming::stream_reason>, seastar::rpc::source<frozen_mutation_fragment, seastar::rpc::optional<streaming::stream_mutation_fragments_cmd> >)#4}::operator()(seastar::rpc::client_info const&, utils::UUID, utils::UUID, utils::UUID, unsigned long, seastar::rpc::optional<streaming::stream_reason>, seastar::rpc::source<frozen_mutation_fragment, seastar::rpc::optional<streaming::stream_mutation_fragments_cmd> >) const::{lambda()#1}::operator()()::{lambda(seastar::lw_shared_ptr<schema const>)#1}::operator()(schema)::{lambda(flat_mutation_reader)#2}::operator()(seastar::lw_shared_ptr<schema const>) const::{lambda(bool)#1}::operator()(bool)::{lambda()#2}, seastar::future<> >(streaming::stream_session::init_messaging_service_handler()::{lambda(seastar::rpc::client_info const&, utils::UUID, utils::UUID, utils::UUID, unsigned long, seastar::rpc::optional<streaming::stream_reason>, seastar::rpc::source<frozen_mutation_fragment, seastar::rpc::optional<streaming::stream_mutation_fragments_cmd> >)#4}::operator()(seastar::rpc::client_info const&, utils::UUID, utils::UUID, utils::UUID, unsigned long, seastar::rpc::optional<streaming::stream_reason>, seastar::rpc::source<frozen_mutation_fragment, seastar::rpc::optional<streaming::stream_mutation_fragments_cmd> >) const::{lambda()#1}::operator()()::{lambda(seastar::lw_shared_ptr<schema const>)#1}::operator()(schema)::{lambda(flat_mutation_reader)#2}::operator()(seastar::lw_shared_ptr<schema const>) const::{lambda(bool)#1}::operator()(bool)::{lambda()#2}&&)::{lambda()#1}::operator()() const::{lambda({lambda(bool)#1})#1}>::run_and_dispose() at stream_session.cc:?
 (inlined by) apply at /jenkins/workspace/scylla-3.1/relocatable-pkg/scylla/seastar/include/seastar/core/apply.hh:35
 (inlined by) apply<streaming::stream_session::init_messaging_service_handler()::<lambda(const seastar::rpc::client_info&, streaming::stream_session::UUID, streaming::stream_session::UUID, streaming::stream_session::UUID, uint64_t, seastar::rpc::optional<streaming::stream_reason>, seastar::rpc::source<frozen_mutation_fragment, seastar::rpc::optional<streaming::stream_mutation_fragments_cmd> >)>::<lambda()> mutable::<lambda(schema_ptr)> mutable::<lambda(flat_mutation_reader)>::<lambda(bool)> mutable::<lambda()> > at /jenkins/workspace/scylla-3.1/relocatable-pkg/scylla/seastar/include/seastar/core/apply.hh:43
 (inlined by) apply<streaming::stream_session::init_messaging_service_handler()::<lambda(const seastar::rpc::client_info&, streaming::stream_session::UUID, streaming::stream_session::UUID, streaming::stream_session::UUID, uint64_t, seastar::rpc::optional<streaming::stream_reason>, seastar::rpc::source<frozen_mutation_fragment, seastar::rpc::optional<streaming::stream_mutation_fragments_cmd> >)>::<lambda()> mutable::<lambda(schema_ptr)> mutable::<lambda(flat_mutation_reader)>::<lambda(bool)> mutable::<lambda()> > at /jenkins/workspace/scylla-3.1/relocatable-pkg/scylla/seastar/include/seastar/core/future.hh:1392
 (inlined by) operator()<seastar::future_state<> > at /jenkins/workspace/scylla-3.1/relocatable-pkg/scylla/seastar/include/seastar/core/future.hh:950
 (inlined by) run_and_dispose at /jenkins/workspace/scylla-3.1/relocatable-pkg/scylla/seastar/include/seastar/core/future.hh:377
seastar::reactor::run_tasks(seastar::reactor::task_queue&) at /usr/include/boost/program_options/variables_map.hpp:146
seastar::reactor::run_some_tasks() at /usr/include/boost/program_options/variables_map.hpp:146
seastar::reactor::run_some_tasks() at /usr/include/boost/program_options/variables_map.hpp:146
 (inlined by) seastar::reactor::run() at /jenkins/workspace/scylla-3.1/relocatable-pkg/scylla/seastar/build/release/../../src/core/reactor.cc:4243
seastar::smp::configure(boost::program_options::variables_map, seastar::reactor_config)::{lambda()#3}::operator()() const at /usr/include/boost/program_options/variables_map.hpp:146
std::function<void ()>::operator()() const at /usr/include/c++/8/bits/std_function.h:687
 (inlined by) seastar::posix_thread::start_routine(void*) at /jenkins/workspace/scylla-3.1/relocatable-pkg/scylla/seastar/build/release/../../src/core/posix.cc:52
?? ??:0
?? ??:0
```

cc: @bhalevy

**Comment by avikivity** [comment] 2019-09-03 06:49
Duplicate of #4898

**Closed by avikivity** 2019-09-03 06:49 UTC
