### ISSUE TITLE
CQL query duration takes much longer than the CQL TIMEOUT parameter value specified

### ISSUE THREAD

**Issue by yarongilor** [scylladb/scylla#8601] opened 2021-05-06 19:28 UTC
The new CQL TIMEOUT parameter was added to SCT fullscan thread.
(in https://github.com/scylladb/scylla-cluster-tests/pull/3491 )

it now can get a randomize timeout duration between 2 minutes to 3 hours for the select query.

as can be seen in the log below, the command actually takes much longer than the timeout many times.

log:
```
ubuntu@ip-10-0-3-6:~/sct-results/latest$ grep -v 'ChaosMonkey on target' sct.log | grep -i 'using timeout\|fullscanevent\|found coredump\|Set current_disruption\|segmentation\|<<<<<<<<<\|>>>>>>>>>\|p:ERROR > Traceback'
< t:2021-05-03 19:39:33,219 f:nemesis.py      l:1127 c:sdcm.nemesis         p:INFO  > sdcm.nemesis.ChaosMonkey: >>>>>>>>>>>>>Started random_disrupt_method no_corrupt_repair
< t:2021-05-03 19:39:33,221 f:nemesis.py      l:617  c:sdcm.nemesis         p:DEBUG > sdcm.nemesis.ChaosMonkey: Set current_disruption -> NoCorruptRepair Node longevity-tls-50gb-3d-fullscan-db-node-ab5a4ac2-2 [13.51.159.191 | 10.0.2.202] (seed: False)
< t:2021-05-03 19:41:54,661 f:file_logger.py  l:80   c:sdcm.sct_events.file_logger p:INFO  > 2021-05-03 19:41:54.660: (FullScanEvent Severity.NORMAL): type=start select_from=keyspace1.standard1 on db_node=10.0.0.196
< t:2021-05-03 19:41:54,705 f:tester.py       l:1536 c:LongevityTest        p:INFO  > Will run command "select * from keyspace1.standard1 USING TIMEOUT 4m"
< t:2021-05-03 19:41:54,705 f:common.py       l:1259 c:utils                p:DEBUG > Executing CQL '<SimpleStatement query="select * from keyspace1.standard1 USING TIMEOUT 4m", consistency=ONE>'...
< t:2021-05-03 19:45:54,106 f:file_logger.py  l:80   c:sdcm.sct_events.file_logger p:INFO  > 2021-05-03 19:45:54.104: (FullScanEvent Severity.NORMAL): type=finish select_from=keyspace1.standard1 on db_node=10.0.0.196 message=finished successfully
< t:2021-05-03 19:49:54,689 f:file_logger.py  l:80   c:sdcm.sct_events.file_logger p:INFO  > 2021-05-03 19:49:54.688: (FullScanEvent Severity.NORMAL): type=start select_from=keyspace1.standard1 on db_node=10.0.1.190
< t:2021-05-03 19:49:54,765 f:tester.py       l:1536 c:LongevityTest        p:INFO  > Will run command "select * from keyspace1.standard1 bypass cache USING TIMEOUT 30m"
< t:2021-05-03 19:49:54,766 f:common.py       l:1259 c:utils                p:DEBUG > Executing CQL '<SimpleStatement query="select * from keyspace1.standard1 bypass cache USING TIMEOUT 30m", consistency=ONE>'...
< t:2021-05-03 19:56:56,024 f:file_logger.py  l:80   c:sdcm.sct_events.file_logger p:INFO  > 2021-05-03 19:56:56.023: (FullScanEvent Severity.NORMAL): type=finish select_from=keyspace1.standard1 on db_node=10.0.1.190 message=finished successfully
< t:2021-05-03 20:00:57,120 f:file_logger.py  l:80   c:sdcm.sct_events.file_logger p:INFO  > 2021-05-03 20:00:57.119: (FullScanEvent Severity.NORMAL): type=start select_from=keyspace1.standard1 on db_node=10.0.3.166
< t:2021-05-03 20:00:57,213 f:tester.py       l:1536 c:LongevityTest        p:INFO  > Will run command "select * from keyspace1.standard1 bypass cache USING TIMEOUT 30m"
< t:2021-05-03 20:00:57,214 f:common.py       l:1259 c:utils                p:DEBUG > Executing CQL '<SimpleStatement query="select * from keyspace1.standard1 bypass cache USING TIMEOUT 30m", consistency=ONE>'...
< t:2021-05-03 20:22:29,943 f:nemesis.py      l:1137 c:sdcm.nemesis         p:INFO  > sdcm.nemesis.ChaosMonkey: <<<<<<<<<<<<<Finished random_disrupt_method no_corrupt_repair
< t:2021-05-03 20:47:34,960 f:nemesis.py      l:1127 c:sdcm.nemesis         p:INFO  > sdcm.nemesis.ChaosMonkey: >>>>>>>>>>>>>Started random_disrupt_method network_block
< t:2021-05-03 20:47:34,963 f:nemesis.py      l:617  c:sdcm.nemesis         p:DEBUG > sdcm.nemesis.ChaosMonkey: Set current_disruption -> BlockNetwork
< t:2021-05-03 20:52:08,817 f:nemesis.py      l:1127 c:sdcm.nemesis         p:INFO  > sdcm.nemesis.ChaosMonkey: >>>>>>>>>>>>>Started random_disrupt_method run_unique_sequence
< t:2021-05-03 21:12:08,921 f:nemesis.py      l:617  c:sdcm.nemesis         p:DEBUG > sdcm.nemesis.ChaosMonkey: Set current_disruption -> ManagementRepair
< t:2021-05-03 21:16:09,806 f:nemesis.py      l:1127 c:sdcm.nemesis         p:INFO  > sdcm.nemesis.ChaosMonkey: >>>>>>>>>>>>>Started random_disrupt_method terminate_and_replace_node
< t:2021-05-03 21:16:09,812 f:nemesis.py      l:617  c:sdcm.nemesis         p:DEBUG > sdcm.nemesis.ChaosMonkey: Set current_disruption -> TerminateAndReplaceNode Node longevity-tls-50gb-3d-fullscan-db-node-ab5a4ac2-2 [13.51.159.191 | 10.0.2.202] (seed: False)
< t:2021-05-03 22:05:34,200 f:nemesis.py      l:1137 c:sdcm.nemesis         p:INFO  > sdcm.nemesis.ChaosMonkey: <<<<<<<<<<<<<Finished random_disrupt_method terminate_and_replace_node
< t:2021-05-03 22:29:18,647 f:nemesis.py      l:1127 c:sdcm.nemesis         p:INFO  > sdcm.nemesis.ChaosMonkey: >>>>>>>>>>>>>Started random_disrupt_method truncate_large_partition
< t:2021-05-03 22:29:18,651 f:nemesis.py      l:617  c:sdcm.nemesis         p:DEBUG > sdcm.nemesis.ChaosMonkey: Set current_disruption -> TruncateMonkeyLargePartition Node longevity-tls-50gb-3d-fullscan-db-node-ab5a4ac2-5 [13.48.70.15 | 10.0.2.182] (seed: False)
< t:2021-05-03 22:32:48,700 f:nemesis.py      l:1137 c:sdcm.nemesis         p:INFO  > sdcm.nemesis.ChaosMonkey: <<<<<<<<<<<<<Finished random_disrupt_method truncate_large_partition
< t:2021-05-03 22:56:12,254 f:nemesis.py      l:1127 c:sdcm.nemesis         p:INFO  > sdcm.nemesis.ChaosMonkey: >>>>>>>>>>>>>Started random_disrupt_method toggle_cdc_feature_properties_on_table
< t:2021-05-03 22:56:12,255 f:nemesis.py      l:617  c:sdcm.nemesis         p:DEBUG > sdcm.nemesis.ChaosMonkey: Set current_disruption -> ToggleCDCProperties
< t:2021-05-03 22:56:14,716 f:nemesis.py      l:1137 c:sdcm.nemesis         p:INFO  > sdcm.nemesis.ChaosMonkey: <<<<<<<<<<<<<Finished random_disrupt_method toggle_cdc_feature_properties_on_table
< t:2021-05-03 23:19:16,962 f:nemesis.py      l:1127 c:sdcm.nemesis         p:INFO  > sdcm.nemesis.ChaosMonkey: >>>>>>>>>>>>>Started random_disrupt_method destroy_data_then_rebuild
< t:2021-05-03 23:19:16,962 f:nemesis.py      l:617  c:sdcm.nemesis         p:DEBUG > sdcm.nemesis.ChaosMonkey: Set current_disruption -> CorruptThenRebuild Node longevity-tls-50gb-3d-fullscan-db-node-ab5a4ac2-5 [13.48.70.15 | 10.0.2.182] (seed: False)
< t:2021-05-03 23:57:26,531 f:nemesis.py      l:1137 c:sdcm.nemesis         p:INFO  > sdcm.nemesis.ChaosMonkey: <<<<<<<<<<<<<Finished random_disrupt_method destroy_data_then_rebuild
< t:2021-05-04 00:22:05,032 f:nemesis.py      l:1127 c:sdcm.nemesis         p:INFO  > sdcm.nemesis.ChaosMonkey: >>>>>>>>>>>>>Started random_disrupt_method no_corrupt_repair
< t:2021-05-04 00:22:05,033 f:nemesis.py      l:617  c:sdcm.nemesis         p:DEBUG > sdcm.nemesis.ChaosMonkey: Set current_disruption -> NoCorruptRepair Node longevity-tls-50gb-3d-fullscan-db-node-ab5a4ac2-3 [13.48.130.193 | 10.0.3.166] (seed: False)
< t:2021-05-04 01:00:27,688 f:nemesis.py      l:1137 c:sdcm.nemesis         p:INFO  > sdcm.nemesis.ChaosMonkey: <<<<<<<<<<<<<Finished random_disrupt_method no_corrupt_repair
< t:2021-05-04 01:24:01,806 f:nemesis.py      l:1127 c:sdcm.nemesis         p:INFO  > sdcm.nemesis.ChaosMonkey: >>>>>>>>>>>>>Started random_disrupt_method repair_streaming_err
< t:2021-05-04 01:24:01,810 f:nemesis.py      l:617  c:sdcm.nemesis         p:DEBUG > sdcm.nemesis.ChaosMonkey: Set current_disruption -> RepairStreamingErr
< t:2021-05-04 02:37:50,387 f:nemesis.py      l:1137 c:sdcm.nemesis         p:INFO  > sdcm.nemesis.ChaosMonkey: <<<<<<<<<<<<<Finished random_disrupt_method repair_streaming_err
< t:2021-05-04 03:02:15,285 f:nemesis.py      l:1127 c:sdcm.nemesis         p:INFO  > sdcm.nemesis.ChaosMonkey: >>>>>>>>>>>>>Started random_disrupt_method run_cdcstressor_tool
< t:2021-05-04 03:02:15,285 f:nemesis.py      l:617  c:sdcm.nemesis         p:DEBUG > sdcm.nemesis.ChaosMonkey: Set current_disruption -> RunCDCStressorTool
< t:2021-05-04 03:02:17,803 f:nemesis.py      l:1137 c:sdcm.nemesis         p:INFO  > sdcm.nemesis.ChaosMonkey: <<<<<<<<<<<<<Finished random_disrupt_method run_cdcstressor_tool
< t:2021-05-04 03:25:37,831 f:nemesis.py      l:1127 c:sdcm.nemesis         p:INFO  > sdcm.nemesis.ChaosMonkey: >>>>>>>>>>>>>Started random_disrupt_method disable_enable_ldap_authorization
< t:2021-05-04 03:25:37,832 f:nemesis.py      l:617  c:sdcm.nemesis         p:DEBUG > sdcm.nemesis.ChaosMonkey: Set current_disruption -> LDAP_Toggle_authorization_configuration
< t:2021-05-04 03:28:53,194 f:nemesis.py      l:1127 c:sdcm.nemesis         p:INFO  > sdcm.nemesis.ChaosMonkey: >>>>>>>>>>>>>Started random_disrupt_method nodetool_seed_decommission
< t:2021-05-04 03:31:50,063 f:nemesis.py      l:1127 c:sdcm.nemesis         p:INFO  > sdcm.nemesis.ChaosMonkey: >>>>>>>>>>>>>Started random_disrupt_method repair_streaming_err
< t:2021-05-04 03:31:50,063 f:nemesis.py      l:617  c:sdcm.nemesis         p:DEBUG > sdcm.nemesis.ChaosMonkey: Set current_disruption -> RepairStreamingErr
< t:2021-05-04 04:36:16,987 f:nemesis.py      l:1137 c:sdcm.nemesis         p:INFO  > sdcm.nemesis.ChaosMonkey: <<<<<<<<<<<<<Finished random_disrupt_method repair_streaming_err
< t:2021-05-04 05:00:17,387 f:nemesis.py      l:1127 c:sdcm.nemesis         p:INFO  > sdcm.nemesis.ChaosMonkey: >>>>>>>>>>>>>Started random_disrupt_method kill_scylla
< t:2021-05-04 05:00:17,391 f:nemesis.py      l:617  c:sdcm.nemesis         p:DEBUG > sdcm.nemesis.ChaosMonkey: Set current_disruption -> ScyllaKillMonkey Node longevity-tls-50gb-3d-fullscan-db-node-ab5a4ac2-5 [13.48.70.15 | 10.0.2.182] (seed: False)
< t:2021-05-04 05:04:30,295 f:nemesis.py      l:1137 c:sdcm.nemesis         p:INFO  > sdcm.nemesis.ChaosMonkey: <<<<<<<<<<<<<Finished random_disrupt_method kill_scylla
< t:2021-05-04 05:28:53,158 f:nemesis.py      l:1127 c:sdcm.nemesis         p:INFO  > sdcm.nemesis.ChaosMonkey: >>>>>>>>>>>>>Started random_disrupt_method nodetool_seed_decommission
< t:2021-05-04 05:30:17,088 f:file_logger.py  l:80   c:sdcm.sct_events.file_logger p:INFO  > 2021-05-04 05:30:17.086: (FullScanEvent Severity.WARNING): type=finish select_from=keyspace1.standard1 on db_node=10.0.3.166 message=Error from server: code=1200 [Coordinator node timed out waiting for replica nodes' responses] message="Operation timed out for keyspace1.standard1 - received only 0 responses from 1 CL=ONE." info={'consistency': 'ONE', 'required_responses': 1, 'received_responses': 0}
< t:2021-05-04 05:32:31,652 f:nemesis.py      l:1127 c:sdcm.nemesis         p:INFO  > sdcm.nemesis.ChaosMonkey: >>>>>>>>>>>>>Started random_disrupt_method run_cdcstressor_tool
< t:2021-05-04 05:32:31,656 f:nemesis.py      l:617  c:sdcm.nemesis         p:DEBUG > sdcm.nemesis.ChaosMonkey: Set current_disruption -> RunCDCStressorTool
< t:2021-05-04 05:32:33,843 f:nemesis.py      l:1137 c:sdcm.nemesis         p:INFO  > sdcm.nemesis.ChaosMonkey: <<<<<<<<<<<<<Finished random_disrupt_method run_cdcstressor_tool
< t:2021-05-04 05:34:19,095 f:file_logger.py  l:80   c:sdcm.sct_events.file_logger p:INFO  > 2021-05-04 05:34:19.094: (FullScanEvent Severity.NORMAL): type=start select_from=keyspace1.standard1 on db_node=10.0.1.190
< t:2021-05-04 05:34:19,270 f:tester.py       l:1536 c:LongevityTest        p:INFO  > Will run command "select * from keyspace1.standard1 USING TIMEOUT 2m"
< t:2021-05-04 05:34:19,271 f:common.py       l:1259 c:utils                p:DEBUG > Executing CQL '<SimpleStatement query="select * from keyspace1.standard1 USING TIMEOUT 2m", consistency=ONE>'...
< t:2021-05-04 05:55:57,313 f:nemesis.py      l:1127 c:sdcm.nemesis         p:INFO  > sdcm.nemesis.ChaosMonkey: >>>>>>>>>>>>>Started random_disrupt_method show_toppartitions
< t:2021-05-04 05:55:57,313 f:nemesis.py      l:617  c:sdcm.nemesis         p:DEBUG > sdcm.nemesis.ChaosMonkey: Set current_disruption -> ShowTopPartitions
< t:2021-05-04 07:02:25,943 f:file_logger.py  l:80   c:sdcm.sct_events.file_logger p:INFO  > 2021-05-04 07:02:25.942: (FullScanEvent Severity.NORMAL): type=finish select_from=keyspace1.standard1 on db_node=10.0.1.190 message=finished successfully
< t:2021-05-04 07:06:27,967 f:file_logger.py  l:80   c:sdcm.sct_events.file_logger p:INFO  > 2021-05-04 07:06:27.965: (FullScanEvent Severity.NORMAL): type=start select_from=keyspace1.standard1 on db_node=10.0.1.190
< t:2021-05-04 07:06:28,207 f:tester.py       l:1536 c:LongevityTest        p:INFO  > Will run command "select * from keyspace1.standard1 USING TIMEOUT 300m"
< t:2021-05-04 07:06:28,207 f:common.py       l:1259 c:utils                p:DEBUG > Executing CQL '<SimpleStatement query="select * from keyspace1.standard1 USING TIMEOUT 300m", consistency=ONE>'...
< t:2021-05-04 07:15:00,742 f:file_logger.py  l:80   c:sdcm.sct_events.file_logger p:INFO  > 2021-05-04 07:15:00.741: (FullScanEvent Severity.NORMAL): type=finish select_from=keyspace1.standard1 on db_node=10.0.1.190 message=finished successfully
< t:2021-05-04 07:19:03,395 f:file_logger.py  l:80   c:sdcm.sct_events.file_logger p:INFO  > 2021-05-04 07:19:03.394: (FullScanEvent Severity.NORMAL): type=start select_from=keyspace1.standard1 on db_node=10.0.3.166
< t:2021-05-04 07:19:03,506 f:tester.py       l:1536 c:LongevityTest        p:INFO  > Will run command "select * from keyspace1.standard1 bypass cache USING TIMEOUT 4m"
< t:2021-05-04 07:19:03,506 f:common.py       l:1259 c:utils                p:DEBUG > Executing CQL '<SimpleStatement query="select * from keyspace1.standard1 bypass cache USING TIMEOUT 4m", consistency=ONE>'...
< t:2021-05-04 08:35:17,445 f:file_logger.py  l:80   c:sdcm.sct_events.file_logger p:INFO  > 2021-05-04 08:35:17.442: (FullScanEvent Severity.NORMAL): type=finish select_from=keyspace1.standard1 on db_node=10.0.3.166 message=finished successfully
< t:2021-05-04 08:39:19,365 f:file_logger.py  l:80   c:sdcm.sct_events.file_logger p:INFO  > 2021-05-04 08:39:19.363: (FullScanEvent Severity.NORMAL): type=start select_from=keyspace1.standard1 on db_node=10.0.0.196
< t:2021-05-04 08:39:19,457 f:tester.py       l:1536 c:LongevityTest        p:INFO  > Will run command "select * from keyspace1.standard1 bypass cache USING TIMEOUT 8m"
< t:2021-05-04 08:39:19,457 f:common.py       l:1259 c:utils                p:DEBUG > Executing CQL '<SimpleStatement query="select * from keyspace1.standard1 bypass cache USING TIMEOUT 8m", consistency=ONE>'...
< t:2021-05-04 09:54:47,142 f:file_logger.py  l:80   c:sdcm.sct_events.file_logger p:INFO  > 2021-05-04 09:54:47.140: (FullScanEvent Severity.NORMAL): type=finish select_from=keyspace1.standard1 on db_node=10.0.0.196 message=finished successfully
< t:2021-05-04 09:58:49,164 f:file_logger.py  l:80   c:sdcm.sct_events.file_logger p:INFO  > 2021-05-04 09:58:49.163: (FullScanEvent Severity.NORMAL): type=start select_from=keyspace1.standard1 on db_node=10.0.1.190
< t:2021-05-04 09:58:49,264 f:tester.py       l:1536 c:LongevityTest        p:INFO  > Will run command "select * from keyspace1.standard1 bypass cache USING TIMEOUT 2m"
< t:2021-05-04 09:58:49,264 f:common.py       l:1259 c:utils                p:DEBUG > Executing CQL '<SimpleStatement query="select * from keyspace1.standard1 bypass cache USING TIMEOUT 2m", consistency=ONE>'...
< t:2021-05-04 11:15:51,203 f:file_logger.py  l:80   c:sdcm.sct_events.file_logger p:INFO  > 2021-05-04 11:15:51.201: (FullScanEvent Severity.NORMAL): type=finish select_from=keyspace1.standard1 on db_node=10.0.1.190 message=finished successfully
< t:2021-05-04 11:19:53,156 f:file_logger.py  l:80   c:sdcm.sct_events.file_logger p:INFO  > 2021-05-04 11:19:53.154: (FullScanEvent Severity.NORMAL): type=start select_from=keyspace1.standard1 on db_node=10.0.2.182
< t:2021-05-04 11:19:53,248 f:tester.py       l:1536 c:LongevityTest        p:INFO  > Will run command "select * from keyspace1.standard1 USING TIMEOUT 4m"
< t:2021-05-04 11:19:53,249 f:common.py       l:1259 c:utils                p:DEBUG > Executing CQL '<SimpleStatement query="select * from keyspace1.standard1 USING TIMEOUT 4m", consistency=ONE>'...
< t:2021-05-04 11:28:11,993 f:file_logger.py  l:80   c:sdcm.sct_events.file_logger p:INFO  > 2021-05-04 11:28:11.992: (FullScanEvent Severity.NORMAL): type=finish select_from=keyspace1.standard1 on db_node=10.0.2.182 message=finished successfully
< t:2021-05-04 11:32:13,717 f:file_logger.py  l:80   c:sdcm.sct_events.file_logger p:INFO  > 2021-05-04 11:32:13.715: (FullScanEvent Severity.NORMAL): type=start select_from=keyspace1.standard1 on db_node=10.0.2.182
< t:2021-05-04 11:32:13,794 f:tester.py       l:1536 c:LongevityTest        p:INFO  > Will run command "select * from keyspace1.standard1 USING TIMEOUT 2m"
< t:2021-05-04 11:32:13,795 f:common.py       l:1259 c:utils                p:DEBUG > Executing CQL '<SimpleStatement query="select * from keyspace1.standard1 USING TIMEOUT 2m", consistency=ONE>'...
< t:2021-05-04 12:49:54,248 f:file_logger.py  l:80   c:sdcm.sct_events.file_logger p:INFO  > 2021-05-04 12:49:54.247: (FullScanEvent Severity.NORMAL): type=finish select_from=keyspace1.standard1 on db_node=10.0.2.182 message=finished successfully
< t:2021-05-04 12:53:55,732 f:file_logger.py  l:80   c:sdcm.sct_events.file_logger p:INFO  > 2021-05-04 12:53:55.731: (FullScanEvent Severity.NORMAL): type=start select_from=keyspace1.standard1 on db_node=10.0.0.196
< t:2021-05-04 12:53:55,839 f:tester.py       l:1536 c:LongevityTest        p:INFO  > Will run command "select * from keyspace1.standard1 USING TIMEOUT 120m"
< t:2021-05-04 12:53:55,840 f:common.py       l:1259 c:utils                p:DEBUG > Executing CQL '<SimpleStatement query="select * from keyspace1.standard1 USING TIMEOUT 120m", consistency=ONE>'...
< t:2021-05-04 14:08:54,836 f:file_logger.py  l:80   c:sdcm.sct_events.file_logger p:INFO  > 2021-05-04 14:08:54.834: (FullScanEvent Severity.NORMAL): type=finish select_from=keyspace1.standard1 on db_node=10.0.0.196 message=finished successfully
< t:2021-05-04 14:12:56,776 f:file_logger.py  l:80   c:sdcm.sct_events.file_logger p:INFO  > 2021-05-04 14:12:56.775: (FullScanEvent Severity.NORMAL): type=start select_from=keyspace1.standard1 on db_node=10.0.1.190
< t:2021-05-04 14:12:56,864 f:tester.py       l:1536 c:LongevityTest        p:INFO  > Will run command "select * from keyspace1.standard1 USING TIMEOUT 300m"
< t:2021-05-04 14:12:56,864 f:common.py       l:1259 c:utils                p:DEBUG > Executing CQL '<SimpleStatement query="select * from keyspace1.standard1 USING TIMEOUT 300m", consistency=ONE>'...
```
the test job URL is:
https://jenkins.scylladb.com/job/scylla-staging/job/Longevity_yaron/job/longevity-50gb-3days-test_yaron/
(test is about to end soon and send all test details in email)

see attached files with the slow log tables info from db nodes.
[select_from_node_slow_log_time_idx_all_nodes.txt](https://github.com/scylladb/scylla/files/6437147/select_from_node_slow_log_time_idx_all_nodes.txt)
[select_from_sessions_time_idx_all_nodes.txt](https://github.com/scylladb/scylla/files/6437148/select_from_sessions_time_idx_all_nodes.txt)
[desc_schema_all_nodes.txt](https://github.com/scylladb/scylla/files/6437149/desc_schema_all_nodes.txt)

*Installation details*
Scylla version (or git commit hash): `4.5.dev-0.20210124.825855683 with build-id aebba9e222487deec03be5ac66c4a8491b6e2219`
Cluster size: 4 nodes (i3.xlarge)
OS (RHEL/CentOS/Ubuntu/AWS AMI): `ami-0aff84951dca5b7c4` (aws: eu-north-1)

Test: `longevity-50gb-3days`
Test name: `longevity_test.LongevityTest.test_custom_time`
Test config file(s): TBD

**Comment by psarna** [comment] 2021-05-07 09:39
Is the node still alive? The output in this issue includes inputs from `system_traces.node_slow_log_time_idx` and `system_traces.sessions`, but these do not really contain any context. The most valuable information will be in `system_traces.node_slow_log` and `system_traces.events` - only from there we can deduce which operation took longer than expected (that's what stored in `system_traces.node_slow_log`) and which step of the operation took longer than expected (that's from `system_traces.events`.

It would be most convenient to just keep the node alive for a while for live examination, but if that's not possible for any reason, the output from the tables above would also help. In order to be extra safe, it's best to just collect all rows from each table from the `system_traces` keyspace - then we'll have all available context.

**Comment by yarongilor** [comment] 2021-05-11 08:48
@psarna , the test is now rerunning and has slow query traces enabled. please be welcome to look at it.
nodes traces status is:
```
yarongilor@yaron-pc:~/Downloads/logs$ for ip in 13.49.226.66 13.49.72.110 13.53.198.222 13.49.0.96; do echo ip: ${ip}; ssh  -i ~/.ssh/scylla-qa-ec2 centos@${ip} 'curl -X GET --header "Content-Type: application/json" --header "Accept: application/json" "http://127.0.0.1:10000/storage_service/slow_query" | grep enable'; echo; done
ip: 13.49.226.66
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    51  100   {"enable": true, "ttl": 8600, "threshold": 1800000}-:--     0
 51    0     0  62500      0 --:--:-- --:--:-- --:--:-- 51000

ip: 13.49.72.110
{"enable": true, "ttl": 8600, "threshold": 1800000}
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    51  100    51    0     0  43147      0 --:--:-- --:--:-- --:--:-- 51000

ip: 13.53.198.222
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:-{"enable": true, "ttl": 8600, "threshold": 1800000}
100    51  100    51    0     0  50000      0 --:--:-- --:--:-- --:--:-- 51000

ip: 13.49.0.96
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0{"enable": true, "ttl": 8600, "threshold": 1800000}
100    51  100    51    0     0  49514      0 --:--:-- --:--:-- --:--:-- 51000
```
![Screenshot from 2021-05-11 11-46-58](https://user-images.githubusercontent.com/9427929/117787129-d5420900-b24e-11eb-9709-765cc403b179.png)

**Comment by avikivity** [comment] 2021-05-11 09:29
The timeout is refreshed each time a new page is generated, so it doesn't apply to a full scan (just to individual pages with a scan).

**Comment by psarna** [comment] 2021-05-11 13:16
@yarongilor It can be terminated now, Avi found out the cause - the timeout applies to fetching individual pages, so that's why the whole operation may take much longer time than the timeout declared with `USING TIMEOUT`

**Comment by psarna** [comment] 2021-05-12 14:47
To clarify - this behavior is not a Scylla bug, it's how timeouts work: the test performs a paged full scan, and uses a timeout parameter which applies to fetching a single page. The timeout is per-query, and a single query fetches a single page of results. Here's the place in SCT code which makes this query paged:
https://github.com/scylladb/scylla-cluster-tests/blob/9d02b357cc82b6a2bc20b65e3b5a8262243f0af0/sdcm/tester.py#L1535

What you can consider doing to actually test a single query with a long timeout is e.g. issuing a **unpaged** full scan with filtering which filters out **most** of the results - e.g. `SELECT * FROM t WHERE v = 715 ALLOW FILTERING`, assuming that `v` is a regular column and only a single row has `v = 715`. It's important to both make the query unpaged (by not providing the page size) and provide a filtering restriction which discards most of the values (e.g. all but one).

It will be a better candidate for testing the timeout parameter, because:
1. It would be a single query, which means that it will have a single timeout
2. It would be unpaged, which is normally an out-of-memory risk, **but** aggregation queries and unpaged filtering queries are paged internally by Scylla, and each page is processed individually; combined with the fact that we discard most of the rows, it should not cause an out-of-memory situation

**Closed** 2021-05-18 16:06 UTC
Labels: not a bug
