### ISSUE TITLE
Scylla 4.2.2 governor dropped from 'performance' to 'schedutil'

### ISSUE THREAD

**Issue by pveentjer** [scylladb/scylla#9273] opened 2021-08-31 17:00 UTC
The governor has dropped from 'performance' to 'schedutil'.  In one of my benchmarks I saw 10% throughput increase by upgrading the governor from 'schedutil' to 'performance'.

After doing a binary search over the Scylla versions, the Scylla 4.2.2 tag is the first one that suffering from this problem.

In 4.2.1 there is a tuned.service enabled and in 4.2.2 there is not.

After disabling the tuned.service on 4.2.1 and rebooting, the instance also is running with the 'schedutil' governor.  So it seems that the 'tuned' part is responsible for starting the performance governor.

One of the changes in 4.2.2 is in the file `dist/redhat/scylla.spec` which has the following 2 extra lines:

```
scylla.spec:# tuned overwrites our sysctl settings
scylla.spec:Obsoletes:  tuned
```
So here the tuned functionality is disabled.

This problem is confirmed on the centos AWS images;  the Ubuntu based images like 2021.1 and 4.5 rc do not suffer from this problem.

Since the problem doesn't seem to depend on the cloud provider, I guess that redhat based instances in other cloud providers  could suffer from the same problem.

# Workarounds

Either call:
```
sudo cpupower frequency-set -g governor
```

Or if you want to make it durable:
```
sudo systemctl enable cpupower.service
```

# Update
The scylla_cpuscaling_setup script should take care of setting the governor to performance. Either it doesn't get called, or somehow there is a failure when it is called. The /etc/sysconfig/cpupower file exists with the following content:
```
# See 'cpupower help' and cpupower(1) for more info
CPUPOWER_START_OPTS="frequency-set -g performance"
CPUPOWER_STOP_OPTS="frequency-set -g ondemand"
```
The problem is that the `cpupower.service` isn't started.

In the journalctl I do not see the following call being made:
```
Created symlink from /etc/systemd/system/multi-user.target.wants/cpupower.service to /usr/lib/systemd/system/cpupower.service.
```

 When calling the scylla_cpuscaling_setup script manually, the cpupower.service is created and the performance governor mode is set. It seems that the script is working fine, so the plausible explanation is that the script isn't called. Another indication that the script has not run is that the 'kernel-tools' package isn't installed.

**Comment by penberg** [comment] 2021-09-01 06:18
@pveentjer So commit 615b8e81844e47fd54e6043d1ef0a746aa9348d3 caused a regression of CPU governor not being set to performance on RPM-based systems. Did I understand this correctly? You don't see the issue with the current AMI because it's Ubuntu-based, but the regression still exists in RPM systems?

/cc @avikivity @syuu1228

**Comment by pveentjer** [comment] 2021-09-01 06:26
Your understanding is correct.

The Ubuntu based images like Scylla 4.5 release candidates and the 2021.1 are fine.

But everything from 4.2.2 till 4.4.x is broken (CentOS based).

**Comment by pveentjer** [comment] 2021-09-01 08:18
My guess is that the problem of not correctly configuring the governor was already there; but it got hidden because the 'tuned' functionality eventually did configure it correctly. But by removing the tuned functionality, the problem got exposed.

**Comment by syuu1228** [comment] 2021-09-01 09:36
@pveentjer Could you tell me more detail of the environment, which instance type are you using, and which AMI image?
Most important thing is, is it baremetal instance or normal VM instance?
And did you run CPU scaling setup in scylla_setup, and does it succeed or failed?
If you never run CPU scaling setup, it just removes tuned and does not configures /etc/sysconfig/cpupower, may causes performance degradation you described here.

Or, if it's VM instance, even you run the setup script it probably causes "This computer doesn\'t supported CPU scaling configuration" error and does nothing.
Because the script detected the environment does not supported CPU scaling configuration.
Here's a code:
```
    if not os.path.exists('/sys/devices/system/cpu/cpu0/cpufreq/scaling_governor'):
        print('This computer doesn\'t supported CPU scaling configuration.')
        sys.exit(0)
```
https://github.com/scylladb/scylla/blob/master/dist/common/scripts/scylla_cpuscaling_setup#L49
Maybe this can be the reason of the performance degradation, because even it removed tuned but does nothing.
But it's strange you able to change CPU scaling governor, even the script saying it can't.
Maybe there is a bug on the script to detect CPU scaling configuration support.

Note that we recently fixed a bug that related detecting CPU scaling configuration, it can be related with this:  #9191

**Comment by pveentjer** [comment] 2021-09-01 09:57
Hi @syuu1228 if you want I can give you a reproducer so you can play with it.

Region: us-east-2
 #  4.2.2
ami-05e2aa6cb51bef7fa

instance-type: i3.2xlarge and i3en.metal. I noticed it on the i3en.metal and downgraded to a cheaper instance for debugging. So it is a problem with bare metal and virtualization.

"And did you run CPU scaling setup in scylla_setup, and does it succeed or failed?"
This is the trick part.

When I run scylla_cpuscaling_setup directly; all works perfectly fine.

When I call scylla_setup with the the following flags:
```
scylla_setup --ntp-domain amazon --no-coredump-setup --no-sysconfig-setup --no-raid-setup --no-io-setup --no-bootparam-setup --no-ec2-check --no-swap-setup
```

It will fail because the node exporter is already is installed. So I need to pass '--no-node-exporter' on top of the other parameters, and then scylla_setup works perfectly fine. So perhaps the node_exporter_install script is running into a duplicate installation problem.

```
If you never run CPU scaling setup, it just removes tuned and does not configures /etc/sysconfig/cpupower, may causes performance degradation you described here.
```
I should not need to execute it at all. It should be done automatically by the AMI.

```
Or, if it's VM instance, even you run the setup script it probably causes "This computer doesn't supported CPU scaling configuration" error and does nothing.
```
That is not the situation in this case. Setting the cpu governor by hand works perfectly fine
```
sudo cpupower frequency-set -g performance
```

And when cpupower frequency-info, it will show 'performance'. This is not a problem of the instance not supporting the governors.

**Comment by syuu1228** [comment] 2021-09-01 10:01
Hmm, I actually able to configure CPU scaling governor on i3.2xlarge instance, which is running in Xen hypervisor:
```
[centos@ip-10-0-0-81 ~]$ sudo cpupower frequency-set --governor performance
Setting cpu: 0
Setting cpu: 1
Setting cpu: 2
Setting cpu: 3
Setting cpu: 4
Setting cpu: 5
Setting cpu: 6
Setting cpu: 7
[centos@ip-10-0-0-81 ~]$ sudo cpupower frequency-set --governor powersave
Setting cpu: 0
Setting cpu: 1
Setting cpu: 2
Setting cpu: 3
Setting cpu: 4
Setting cpu: 5
Setting cpu: 6
Setting cpu: 7
$ ls /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
/sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
```

scylla_cpuscaling_setup also succeed to run, but it is latest version which include fix for #9191:
```
[centos@ip-10-0-0-81 ~]$ sudo /opt/scylladb/scripts/scylla_cpuscaling_setup 
Created symlink from /etc/systemd/system/multi-user.target.wants/cpupower.service to /usr/lib/systemd/system/cpupower.service.
[centos@ip-10-0-0-81 ~]$
```

Maybe why I misunderstood that these VM environments does not supported CPU scaling governor configuration is because of #9191, it possibly keep failing to detect scaling governor configuration support.

**Comment by pveentjer** [comment] 2021-09-01 10:01
It isn't a scaling problem. I believe the script doesn't get called.

**Comment by syuu1228** [comment] 2021-09-01 10:03
```
I do not believe there is a problem with 'scylla_cpuscaling_setup' script. My guess it that it doesn't get called because the scylla_setup script quits with an error before it calls the cpuscaling script.

```
Ah, make sense. In that case CPU scaling configuration leave not optimal.

**Comment by pveentjer** [comment] 2021-09-01 10:05
Yes. So if something in front of the scylla_cpuscaling_setup call in the scylla_setup fails, the scylla_cpuscaling_setup won't run. And my current candidate is the node exporter functionality. Perhaps duplicate installation problems.

**Comment by syuu1228** [comment] 2021-09-01 10:10
@pveentjer So I suppose it similar (or same) problem as #8017, correct?

**Comment by pveentjer** [comment] 2021-09-01 10:13
I could be. But perhaps something else is the cause. 

scylla-machine-image/aws/ami/files/scylla_install_ami 

You can find a call:

```
   run('/opt/scylladb/scripts/scylla_setup --ntp-domain amazon --no-coredump-setup --no-sysconfig-setup --no-raid-setup --no-io-setup --no-bootparam-setup --no-ec2-check --no-swap-setup')
```

My guess is that the script fails with an error, but the error is ignored.

**Comment by syuu1228** [comment] 2021-09-01 10:39
@pveentjer I just succeed reproduce the governor issue on 4.2.2 AMI, will try to investigate more detail of the problem.

```
[centos@ip-10-0-0-93 ~]$ cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
schedutil
[centos@ip-10-0-0-93 ~]$ cat /etc/sysconfig/cpupower 
# See 'cpupower help' and cpupower(1) for more info
CPUPOWER_START_OPTS="frequency-set -g performance"
CPUPOWER_STOP_OPTS="frequency-set -g ondemand"
[centos@ip-10-0-0-93 ~]$ systemctl status cpupower
● cpupower.service - Configure CPU power related settings
   Loaded: loaded (/usr/lib/systemd/system/cpupower.service; disabled; vendor preset: disabled)
   Active: inactive (dead)
```

**Comment by syuu1228** [comment] 2021-09-01 11:08
Okay I understood what is happening.
It is not only 4.2.2 problem but unexpectedly fixed by e5bb88b (#9191), so I confirmed it fixed on latest 4.5.rc6 AMI (it should also on latest versions of 4.3, 4.4 since we backported the patch).

On EC2 instance startup, we don't run scylla_setup nor scylla_cpuscaling_setup:
```
    cloud_instance = get_cloud_instance()
    run('/opt/scylladb/scylla-machine-image/scylla_configure.py', shell=True, check=True)
    if not os.path.ismount('/var/lib/scylla'):
        print('Failed to initialize RAID volume, exiting setup')
        sys.exit(1)
I think 
    run('/opt/scylladb/scripts/scylla_sysconfig_setup --nic eth0 --setup-nic --ami', shell=True, check=True)
    if cloud_instance.is_supported_instance_class():
        cloud_instance.io_setup()
    if os.path.ismount('/var/lib/scylla'):
        run('/opt/scylladb/scripts/scylla_coredump_setup --dump-to-raiddir', shell=True, check=True)
    else:
        run('/opt/scylladb/scripts/scylla_coredump_setup', shell=True, check=True)
    run('/opt/scylladb/scripts/scylla_swap_setup --swap-directory /', shell=True, check=True)
    pathlib.Path('/etc/scylla/machine_image_configured').touch()
```
https://github.com/scylladb/scylla-machine-image/blob/branch-4.5/common/scylla_image_setup
e5bb88b (#9191)
But we run CPU scalling setup on AMI building time, on temporary instance just for Packer, on this line:
```
 run('/opt/scylladb/scripts/scylla_setup --ntp-domain amazon --no-coredump-setup --no-sysconfig-setup --no-raid-setup --no-io-setup --no-bootparam-setup --no-ec2-check --no-swap-setup')
```
https://github.com/scylladb/scylla-machine-image/blob/branch-4.5/aws/ami/files/scylla_install_ami#L110

On previous AMI builds, we get following message (on jenkins):
```
14:55:29  [0;32m    amazon-ebs: This computer doesn't supported CPU scaling configuration.[0m
```
I misunderstood it is because on VM, but it was actually because of the bug #9191.
So after e5bb88b (#9191) scylla_cpuscaling_setup becomes able to configure the parameter, so latest 4.5.rc6 AMI has correct governor:
```
scyllaadm@ip-10-0-0-88:~$ cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
performance
```

However, it is not correct to run CPU scaling setup during AMI build, we should run it on instance startup time (on scylla_image_setup instead of scylla_install_ami).
I will send a PR to fix this.

**Comment by pveentjer** [comment] 2021-09-01 11:35
Scylla 4.3 and 4.4 are broken as well btw. I checked them yesterday. 

Here is a document where I verified a whole bunch of Scylla versions:
https://docs.google.com/document/d/1GuW7LP8LIzGS-4Z-EFIGPsGFSaM4nDPexAYkE557QFg/edit?usp=sharing

**Comment by pveentjer** [comment] 2021-09-02 07:25
Is there a way to start the above imagine and prevent any of the logic from running automatically? I would like to be able to trigger it by hand so I can see what is going on.

**Closed** 2021-09-06 06:20 UTC
Labels: bug
