### ISSUE TITLE
cluster nodes number

### ISSUE THREAD

**Issue by pechstony** [scylladb/scylla#2108] opened 2017-02-23 09:10 UTC
Is ScyllaDB support a cluster with 1000+ nodes?

**Comment by penberg** [comment] 2017-02-23 11:25
IIRC, the largest cluster we've tested is 50-60 nodes.

/cc @slivne @dorlaor @avikivity

**Comment by dorlaor** [comment] 2017-02-23 21:45
We have 50 node cluster in production by couple of users/customers.
Scylla can scale to 1000 nodes as well. I'm closing this issue since it's not a bug/feature

**Closed by dorlaor** 2017-02-23 21:45 UTC
