### ISSUE TITLE
CDC: error during deleting rows by range, if range is empty "ServerError: cdc: could not find timestamp of mutation"

### ISSUE THREAD

**Issue by aleksbykov** [scylladb/scylla#5920] opened 2020-02-28 10:34 UTC
*Installation details*
Scylla version (or git commit hash): 666.development-0.20200224.25a763a187a
Cluster size: 3 nodes
OS (RHEL/CentOS/Ubuntu/AWS AMI): ami-0cd7696b2bfc87cc7

Gemini tool is running vs 3 nodes test cluster over table with cdc enabled(reproduced for both modes preimage enabled/disabled) . Next command is 
```
./gemini -d --duration 3h -c 50 -m write -f --cql-features all --non-interactive --level debug --replication-strategy "{'class': 'SimpleStrategy', 'replication_factor': '3'}" --table-options "cdc={'enabled': true}" --test-cluster=10.0.91.69 --outfile /home/centos/gemini_result_fe5de991-5871-447f-9ae7-fc8a1ba16baf.log --seed 100
```

Next schema was generated:
```
CREATE KEYSPACE ks1 WITH replication = {'class': 'SimpleStrategy', 'replication_factor': '3'}  AND durable_writes = true;

CREATE TABLE ks1.table1 (
    pk0 varint,
    pk1 smallint,
    pk2 varint,
    pk3 int,
    pk4 int,
    ck0 date,
    ck1 timeuuid,
    col0 frozen<list<ascii>>,
    col1 text,
    col2 varint,
    col3 bigint,
    col4 boolean,
    col5 tinyint,
    col6 timestamp,
    col7 uuid,
    col8 duration,
    col9 text,
    PRIMARY KEY ((pk0, pk1, pk2, pk3, pk4), ck0, ck1)
) WITH CLUSTERING ORDER BY (ck0 ASC, ck1 ASC)
    AND bloom_filter_fp_chance = 0.01
    AND caching = {'keys': 'ALL', 'rows_per_partition': 'ALL'}
    AND comment = ''
    AND compaction = {'class': 'SizeTieredCompactionStrategy'}
    AND compression = {'sstable_compression': 'org.apache.cassandra.io.compress.LZ4Compressor'}
    AND crc_check_chance = 1.0
    AND dclocal_read_repair_chance = 0.1
    AND default_time_to_live = 0
    AND gc_grace_seconds = 864000
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair_chance = 0.0
    AND speculative_retry = '99.0PERCENTILE';
CREATE INDEX col2_idx ON ks1.table1 (col2);
CREATE INDEX col5_idx ON ks1.table1 (col5);

CREATE MATERIALIZED VIEW ks1.table1_mv_0 AS
    SELECT *
    FROM ks1.table1
    WHERE col9 IS NOT null AND pk0 IS NOT null AND pk1 IS NOT null AND pk2 IS NOT null AND pk3 IS NOT null AND pk4 IS NOT null AND ck0 IS NOT null AND ck1 IS NOT null
    PRIMARY KEY ((col9, pk0, pk1, pk2, pk3, pk4), ck0, ck1)
    WITH CLUSTERING ORDER BY (ck0 ASC, ck1 ASC)
    AND bloom_filter_fp_chance = 0.01
    AND caching = {'keys': 'ALL', 'rows_per_partition': 'ALL'}
    AND comment = ''
    AND compaction = {'class': 'SizeTieredCompactionStrategy'}
    AND compression = {'sstable_compression': 'org.apache.cassandra.io.compress.LZ4Compressor'}
    AND crc_check_chance = 1.0
    AND dclocal_read_repair_chance = 0.1
    AND default_time_to_live = 0
    AND gc_grace_seconds = 864000
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair_chance = 0.0
    AND speculative_retry = '99.0PERCENTILE';

CREATE MATERIALIZED VIEW ks1.col5_idx_index AS
    SELECT col5, idx_token, pk0, pk1, pk2, pk3, pk4, ck0, ck1
    FROM ks1.table1
    WHERE col5 IS NOT NULL
    PRIMARY KEY (col5, idx_token, pk0, pk1, pk2, pk3, pk4, ck0, ck1)
    WITH CLUSTERING ORDER BY (idx_token ASC, pk0 ASC, pk1 ASC, pk2 ASC, pk3 ASC, pk4 ASC, ck0 ASC, ck1 ASC)
    AND bloom_filter_fp_chance = 0.01
    AND caching = {'keys': 'ALL', 'rows_per_partition': 'ALL'}
    AND comment = ''
    AND compaction = {'class': 'SizeTieredCompactionStrategy'}
    AND compression = {'sstable_compression': 'org.apache.cassandra.io.compress.LZ4Compressor'}
    AND crc_check_chance = 1.0
    AND dclocal_read_repair_chance = 0.1
    AND default_time_to_live = 0
    AND gc_grace_seconds = 864000
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair_chance = 0.0
    AND speculative_retry = '99.0PERCENTILE';

CREATE MATERIALIZED VIEW ks1.col2_idx_index AS
    SELECT col2, idx_token, pk0, pk1, pk2, pk3, pk4, ck0, ck1
    FROM ks1.table1
    WHERE col2 IS NOT NULL
    PRIMARY KEY (col2, idx_token, pk0, pk1, pk2, pk3, pk4, ck0, ck1)
    WITH CLUSTERING ORDER BY (idx_token ASC, pk0 ASC, pk1 ASC, pk2 ASC, pk3 ASC, pk4 ASC, ck0 ASC, ck1 ASC)
    AND bloom_filter_fp_chance = 0.01
    AND caching = {'keys': 'ALL', 'rows_per_partition': 'ALL'}
    AND comment = ''
    AND compaction = {'class': 'SizeTieredCompactionStrategy'}
    AND compression = {'sstable_compression': 'org.apache.cassandra.io.compress.LZ4Compressor'}
    AND crc_check_chance = 1.0
    AND dclocal_read_repair_chance = 0.1
    AND default_time_to_live = 0
    AND gc_grace_seconds = 864000
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair_chance = 0.0
    AND speculative_retry = '99.0PERCENTILE';

cdc = {'enabled': 'true'}

CREATE TABLE ks1.table1_scylla_cdc_log (
    stream_id_1 bigint,
    stream_id_2 bigint,
    time timeuuid,
    batch_seq_no int,
    "_ck0" date,
    "_ck1" timeuuid,
    "_col0" frozen<tuple<tinyint, frozen<list<ascii>>>>,
    "_col1" frozen<tuple<tinyint, text>>,
    "_col2" frozen<tuple<tinyint, varint>>,
    "_col3" frozen<tuple<tinyint, bigint>>,
    "_col4" frozen<tuple<tinyint, boolean>>,
    "_col5" frozen<tuple<tinyint, tinyint>>,
    "_col6" frozen<tuple<tinyint, timestamp>>,
    "_col7" frozen<tuple<tinyint, uuid>>,
    "_col8" frozen<tuple<tinyint, duration>>,
    "_col9" frozen<tuple<tinyint, text>>,
    "_pk0" varint,
    "_pk1" smallint,
    "_pk2" varint,
    "_pk3" int,
    "_pk4" int,
    operation tinyint,
    ttl bigint,
    PRIMARY KEY ((stream_id_1, stream_id_2), time, batch_seq_no)
) WITH CLUSTERING ORDER BY (time ASC, batch_seq_no ASC)
    AND bloom_filter_fp_chance = 0.01
    AND caching = {'keys': 'ALL', 'rows_per_partition': 'ALL'}
    AND comment = 'CDC log for ks1.table1'
    AND compaction = {'class': 'SizeTieredCompactionStrategy'}
    AND compression = {'sstable_compression': 'org.apache.cassandra.io.compress.LZ4Compressor'}
    AND crc_check_chance = 1.0
    AND dclocal_read_repair_chance = 0.1
    AND default_time_to_live = 0
    AND gc_grace_seconds = 864000
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair_chance = 0.0
    AND speculative_retry = '99.0PERCENTILE';

```

While gemini apply mutation INSERTS, nothing happened. But once gemini apply mutation DELETE rows by range, gemini terminated with error:
```
{"L":"DEBUG","T":"2020-02-28T10:05:44.314Z","N":"mutation_job","M":"validation statement","pretty_cql":"INSERT INTO ks1.table1 (pk0,pk1,pk2,pk3,pk4,ck0,ck1,col0,col1,col2,col3,col4,col5,col6,col7,col8,col9) VALUES (8882828053388454902,-2549,5236546369630458152,989172929,2139516788,'1992-09-20',ead29980-878d-11cb-a463-0a1894d1b77e,{'RuIk105u9Chixy2jMia0nWwOioC/ZcKm/DSIz9UgUJbAvJAb16wrQCXLbaWN/Sx25xx78LPyYdcwZhdgCK/Ly5hXJ5BdCmVoNHbR0n8boJe4YPPal','03upAaM58av36AZyD7aRUfKQBzu71WrkIOxxKgWe5h1PFizsWa0g8NcbrTj5ZZmapSexEqL/b49ZKdt4UnnGmTajkSxnj3ENBc0P/I2aOyb77KYv8BAohVjZhbfH0Ri4rhqQ0XGBSkwWhq0rUr0YYI4EymdTkLvSeFrnfdwD4zFYDoSap0n3CW0JN+TWcwfbpowbTP4IbGknJIectfarJDh/7F7p5y264gX9xcAWLfPli2F5CUyFF/pdMe5XrAlRDSwmJcvrWOAPHenHi8PlUZpF42PVc8D8Nj4evptCjCtto7gRndlltlGADnwpZXJbuSCzjgK0PCNK/LA/EKAwsezNUGwcydckMARP1TGzCnOriDvCoHtFvlnni9f5qHagVRKVykssS9UepQ3MG+c9IpXans4m3ooFrvwiCPiffewI2iIOgnDizE7DafG6Or6aFD03NHcLDdF+Fq/BqAPTtYJWwRU4XfHGD9X+tP7PRs9ZBU4S96bUfTHW/+NM3DDAyM4a9xnpKz+dgcbqmZDgwQhuO2a3GmgstdHqT2PFpb0OzXN5mufQy0SNYSQ6+fkJr+RqbSpnOQHPUAgL5kGQh/uZILCYjeRH','OnFvY7zkPF0zohbtTlguu1C742kUFu0HvSBNCdoI2/NTRquniPZnTlPcgCagVY26wp9LtrcRYEgKaSSJNJEbm8ZaNihyZg5YlXgTmyVdvjVW9Vy7QDIths6VwoFJpZqEYJpWpk0v3r13BqPhEvfewqF3CqUUL7JQ8+XlIXJKSpZEus/fp0unqjGVB2rVUDH+kn7ccJiV09uIiI/0xOmttHI9+cht4aFbpgnLd5wb/WTRxYE3vrfjsPSi+W44l5OuQ4XnCqxfBfehC5N5Vfl9dybUvknOBaajklV0hWnQ+e7ZUwWSBgUWd+sD87ZZ9yCEcyiqFdr06AbW2zzJoCToDyfm40y7FbtKNshp42VkFsSlj1oyV1PSA0SMuf3EnuVvOfrsAyOKhLZBM1loJBMqT8yTnEEB4rjrP93oIWP0Xwv6LbhAj5/tfucKMVNgHWCKXNTIj5GBiNDqPoVX8582EMj2WrVanTc0XCm9wRdxJbgQIFVTjkYjqYuF1h4yslYeZI88c5/hawX+CZI3rP9K0v2WhJ5h9iIFFGmxtXgiQ3fUAdD+0WWGf8W+7a1n8qdtjmxw7UVozAlNrt1vvA2bdjrjKFfOg+LLZe3JdPbaG97GcjtCvcKPYTvDywwft0D4gzDxMHu6RbcBLFKtJmMRUBwFox6ny00xo8WURex0DPuT18nyKZeXGm6P6XX9ZPrSnWgHIcQLW1UHhJkBETjgWyO+TLBEARcncyGTKGpgx1uimNvSUeAxLY3yKyzUzdmrPjci0yURe2c1B/sFTERiwRcMLuqYIAqrEo7A9R5pSCSgSgpL//B3fuRfP/tSlGlosUFq8xT/PgAAPuzRey8G1fDezo/hCMvMBq0UCtwD9ZG51YZ3I7/AkcZAY8+wqigxQaFmHSFqojx','Q0R7pSICGcpXAuNnqKOfZsjh5VHw6GWm2KTeNO+BOvEu/e7J3AlgAEr/T6SKV4FnqglTFjGcTO9MHAlVMpvphCUJQjKycAIKtlbz30JTsteIptW++W+wn4IX8iQja+3yNp1viDoDqUeEPijx/I6puT+JqvBVpFzhDiWO/JSMjOdb9IPPlypbyjGC8RMk3DFESfnBwe8wDmhEYRWGC9tTk6P+lVa1uZpDAFo2eEllqBAQjBfAtNtR1IOXJwSbwkY20bEtic+nIMk6uCcnR5MGYlTyalw1cOem6I4H8WamyvjnACavnAJQ5FOTdyOHx9JjaXh7a4pqUHjJ1miEKGPdmjjAXmfI4W/kaO5OThhJdj2TXO9SiCAagY/AjHZqM5Ez5UWmNNhnHT5C0giHVJ2qSdH/Yv4mvn5SnynpP8n8jPTF0KQ7TRrgoh2e+5w3owFq4scczmbjYT8B5wlZOPnvrL0fNTZMF2hXb4ykBDB90gcwJbqozc+sKSX7XYlB+KInTkUv1+GxVpNg5rNzkEg8YOb/QO4vRBEef4bs4+2tNfRb9t1QD3RYTx34VLxSvKvCIe/1BN6136dMc8Hl4RkjwPggRjDgOzDJFedYtlnXxrp3TGbjT2YuEVcebQyehe7N05FC6N5vOh2ORA9VACgrVd8N1pgZJNIlDgk2V0/vvMiRd3+Fn1kuqT4G1y8e80vMZM6W3Md69ucm65IbUenLQz5af1r9XxR0jfkEKoR76or7QeqTa9UOafE7G6Lj8ZN9SXK','2Kur3Q9LcScpNlmuj2m00RKPPcG7x7xXMhDQwsonlLvUMao0cfrKn6q/7bA1EXgWY7f+kJSEfKEKJOYUPjei15IG8XTamey+Tx+UmMdUl5lmhAs0iUgCev2qaCbm1zi0eJe7Mbq90N39l6EYFLQbkLaMes3BweQTh96zZ/WbknpGQRcuR7KfVGxei/SxfUIOiyBL/aqh0+tAGGQ2WiyXf4/6t8cN9jUr2eDT6NSgXiFeJ7xIHnKQKGanGJFds7q7o2M0pTa+xw5bV8JFQm2jFosxan6U2hXUUJgy0UuhHNzI3bYpFZwZbf74xm5kZVwGJVmxDzpqhWQnaGWCNYTaFWPg8Mpte8vPvX3bXFJB00oaO+u0P2dFFuzWF+HgYmAjTF6KuPLDLEyxuNSh0fEAqk6oWTatppkzRlbQCUrn7tjMn2hzVDX7H2','UvyAR84z6HfAAFB00dq66WpohCOd/WLaBtOKmNxqvdmzCPIIS3k5vTi4h4HHltmeY5br0AFIyvuABGFM/M55neAFV3Vtkd17r2UdYv1qLpqDN5Fe0CkNrjuYx7y3zMsJ/VfCy4q6VrDP8FU+JjqGwqu1D5Qdq0Ew9Q4PGWz9YEp6jzCFz+FX+L3uWvKy3VKVvcZnpVb3MXR6KRcyZdsnAgoxbWKS57FJXDX7Q1mq3vF8/Q7NTuT/MvZawEJQm4uaPVCQOHot8Toe35k67WkvjKFxdpwozFpPLW/FqqWHgjrSBbGNDOwSGzM4+0e00vSHV5fDGb2HlgNCsLOfHtAZ6ZPfkQUR0HfpmWAX65szSDAgfB8Reelswao0A0It5Dr2ev9w3S7QRINYQC6QdLEhrQO4cL9xAIcT3xXS/In2+jStW3z3U+XMdRB1BgDVsuWWTObsMGCF5W5CS3ea7QQ36ijAVvYPdbRmuKtn6XEFixHWw2ATllM56QZkkXuFFWw7CJpDbLmByF/syjaPpobjVJUQFMhFEULYCB3Cd5v7vLXrzK+7tUa9TKmKGpHgk4po4840q46gRMG404xOUd+MNxTo0fDTnjQcuD5bXpHusIgpsqDoXbzUC+q3ntzIxgONVcIzNvYu8Kn78D9zRAlG0zn4NGst9RETU9','OjjwlxrIpgcBCnUaiECDXjxHWvCdJaEVZ8oIybV1kU3+U6XREcmHnvWKUnd6IcJIKp+2lxrNJ/Ldal19jkI9sdKwkIlkRE+o6behnTy9BT8fna/88Eb0lEh+O2irRPqLCvAkfZu48FlV8P90udaeZzKy86Ho8AAtpsIgfMxTd/NpV0vblgMzq+3wcID2riXVsetw7WYlU6EPI/hpYvmAjm4QAXRZ5dhicKYBn+LLG25CgH8YAa0jwVvOBt7LiTJzdAxzbsvHsXozYu7DJvaxw7liyXJ2CTq2JYF4Em8b9ZjYT9gGm9ffS9lpQIj9KYRLOyTto+PjJpPeeySJU1ixEm9kqa7pq44UF/bsSfQbbPPgu9ZwrccYfSR/Fucsk7n6q4klx2miLOA4ux+XIpkqSYG0T8uJfmlbVKrO2ZdKFLzcIIH63pNDgbANuUYH92HonNxn5RGDnYFHZmxmaPdNDrNE+FbfJT4GIZsPHb5GK6djB1wgFsKLKYAOVCvhao+sYy2CAFseuVQllQp5rRtm2JItCiHccO6qD/n3iKsKpHNAwjCQ/sfaLGqNx+mJjUqyvDA0VblWtGldK4QnfasyhgVuFMBCg5lJZMIvDK38pN6i8bb4y64M3fBP+e4JmdHeeKuVyYtMSMuofK7s6zlKjVQ2VahReQ0b6uPYW1YN/OKW4ONV10Xs47eqituL9qnngu0GPPyCS0PiOTtf9354+ZUE/qfnQsZXmyiYJ5X5mhRmGRgo4Zvhrvr/MM+8RqEMSk4m5oAQ8lVzjMwH25j0ed+J1A3SyYQxD7dXOfkiUYPoTgpPqI6zqSWrsYweKAbMzhM5tJmzLDdVqBEZLXDdXtmVKRg79jJqCBOjnFA3JZYijBEgbbDVJciRaFMdsYh2Mjsb+aAK40bDykWwXaaeVoExxCXqqqGKKJO9rIHitj75JDUhrjMnkMAUkTpmYPppswKVodCaMm1SuruBE5lQjsQQZ2','P83N7yLSJSkVuivA7MzJ69TjT81KlkNV3PrefmnXTfyga/UQLi52iH5sprzFM24AL6WmwirQo4TgjXY1zgiL+9IzP/vdktR9IIt0/s9bmJbG8XssmFnOsiBK5DEZFB7/9cVsx9FX84BDDhFJv5diUUgPcjm9NErAkZ96DOjcQLnAibAHIvv12twa2KoxpBUtyAXNhlmAGTlmIWehBF/wTdMz8QKT+WkE6vXk7oI+qjKhZR+O4po4Q0OFFtmzWy4LtINkViC6qIhORgf0hgQDxUhKf1yDoYuKWtEDtaQUb1ftKObMf9eun1H71GX3y7FvUcIEMGwi3BTdGCeO4iaVs5WWRKYcsh1NvZCK3uHB93RZfBI32tjsD+dt8Nx0wVZwQ5u4VPAheMJNIQjSvu1cuyirnjY7qoOkjagj2ufG3JXFBAoyI1n6jYd3KZdDnwvjbntcrD62VKwpqH9BhKo/fyh7HuO2BI+x2rQb9+JaGK5npXRvL89g0QvA7vYqiHXY78C8ylnBa6PSVEMtLKijPnKZuQOyxAAFNlqaqnNMg1k2M8T7to1KId1A3'},'2IKi8m5h0KIoGpzFkSYxmkjTAK0dZ5uIjJCzkvc7zcETUNcbeInCCuuCoSbrxpRAbGzfm2XovUw4eb4Yku3d10596RfSUNmhYi/qTe4JQPzLMxxrknb3dAjvxUtJeEeyLoNyZoGHgT5hfFlTk24dgb8ungbhzfiVuw3VN9o63J6rYvnaMga7woM6Mirh5mWg7zGHlNoDmyFoTLr6+kw56XMMn7hypycStJBP4t+El93TnZoGm/Msz3OHl7pQGBD0y3JyTJdc4Ebsvjg5CkNUqElyIBuILn29hjDa3m1xdfQiTgbJAJhe33iXgcMTyyghMCaGlU4GsZ32sKrMeKrFGDYgu2T1NcV5rQ6oZCjQKUnbbT0PBWqZoT7I6SNKzcgQtDExxsJWUTgKFq7uxg7FudXSixx0L9icbz0z52DSTAnnesl3RhDGIwVhtXL+6OHZM/MbPogzb4W66l5X+uMpVFWSnmAixSW5RwayS/L0qxuxXpbHlv724+BipotYHoZ/CT4j1pbdWvooyF8uQ9mBFxRiJJ2uol9nbd7iBz7bhc/YINI/A3ExdLtyOFJ4fN5s+KaxKeMQmVhcseoYGyyHL7DAn/n2Dt7vxDlmdoRcinkLwi66VDdD4K8/alH',1150479873291146187,3449477402685548171,true,-64,'1972-07-05T20:22:22Z',8165ba00-793a-11d6-a464-0a1894d1b77e,47m0s,'RlWtvGaTJsnQcKMT6vvSJV5jbAD+hrTfRorsctkKYsIolZqoigz7xR+ZlUgOaEp7lM0v65qitU1j8Bsq5R47CQddq7tNWKwV+5qh9PiNoMXT57MxUIh1S8zQRswfuprif4YfDpyuW64jeySDHAnrCQWNVPQoGfIvpJDELpb2MT/alQpHEUXDxFqlG9hRVQZm75dnB/lGhYuQweiVTCm6lHbs7958qMiM+YMeyzq7v3C8GfQUvcFaHBg4UkqdmbjbbUskvYR5BERivY1m2FQ9Y6Y+l/HZc4mhz6MT9pb6O4Jbmc8J6HChiz/XkvQa9Sac+xglENRZ0dYU5wbVcaT+pm5NvQHSWhfqyBWgMX+re61QSP2vq9CcNpman51K+E/AY23XbOBqWVBZ3hMUUJLb5+hqT3SqoDLQ5YehmB3VlHV0TtW') "}
{"L":"DEBUG","T":"2020-02-28T10:05:44.317Z","N":"mutation_job","M":"validation statement","pretty_cql":"DELETE FROM ks1.table1 WHERE pk0=2368128322514051181 AND pk1=-15308 AND pk2=3296134330061835062 AND pk3=1884117836 AND pk4=587258770 AND ck0>='2017-08-24' AND ck0<='2000-12-26' "}
{"L":"INFO","T":"2020-02-28T10:05:58.377Z","M":"failed to apply mutation","attempts":2,"error":"[cluster = test, query = 'DELETE FROM ks1.table1 WHERE pk0=? AND pk1=? AND pk2=? AND pk3=? AND pk4=? AND ck0>=? AND ck0<=? ']: cdc: could not find timestamp of mutation","errorVerbose":"cdc: could not find timestamp of mutation\n[cluster = test, query = 'DELETE FROM ks1.table1 WHERE pk0=? AND pk1=? AND pk2=? AND pk3=? AND pk4=? AND ck0>=? AND ck0<=? ']\ngithub.com/scylladb/gemini/store.(*cqlStore).doMutate\n\t/home/henrik/dev/gemini/store/cqlstore.go:87\ngithub.com/scylladb/gemini/store.(*cqlStore).mutate\n\t/home/henrik/dev/gemini/store/cqlstore.go:49\ngithub.com/scylladb/gemini/store.mutate\n\t/home/henrik/dev/gemini/store/store.go:162\ngithub.com/scylladb/gemini/store.delegatingStore.Mutate\n\t/home/henrik/dev/gemini/store/store.go:158\nmain.mutation\n\t/home/henrik/dev/gemini/cmd/gemini/jobs.go:205\nmain.MutationJob\n\t/home/henrik/dev/gemini/cmd/gemini/jobs.go:47\nmain.job.func1\n\t/home/henrik/dev/gemini/cmd/gemini/jobs.go:130\ngopkg.in/tomb%2ev2.(*Tomb).run\n\t/home/henrik/go/pkg/mod/gopkg.in/tomb.v2@v2.0.0-20161208151619-d5d1b5820637/tomb.go:163\nruntime.goexit\n\t/usr/lib/go/src/runtime/asm_amd64.s:1357"}
```

Manually runing same queries  give an error in cqlsh:
```
cqlsh> select *  FROM ks1.table1 WHERE pk0=2368128322514051181 AND pk1=-15308 AND pk2=3296134330061835062 AND pk3=1884117836 AND pk4=587258770 AND ck0>='2017-08-24' AND ck0<='2000-12-26' ;

 pk0 | pk1 | pk2 | pk3 | pk4 | ck0 | ck1 | col0 | col1 | col2 | col3 | col4 | col5 | col6 | col7 | col8 | col9
-----+-----+-----+-----+-----+-----+-----+------+------+------+------+------+------+------+------+------+------

(0 rows)
cqlsh> delete FROM ks1.table1 WHERE pk0=2368128322514051181 AND pk1=-15308 AND pk2=3296134330061835062 AND pk3=1884117836 AND pk4=587258770 AND ck0>='2017-08-24' AND ck0<='2000-12-26' ;
ServerError: cdc: could not find timestamp of mutation
```

scylla db logs:
https://cloudius-jenkins-test.s3.amazonaws.com/0ef26a75-33cd-41ad-b365-de52713e6bc6/20200228_102732/db-cluster-0ef26a75.zip

**Comment by kbr-** [comment] 2020-03-06 10:30
Should we close this issue now since the fix is merged? @piodul 
or should we wait for gemini to run for a while and see if the problem is not reproduced? @aleksbykov

**Comment by haaawk** [comment] 2020-03-06 10:32
Is the fix in master already? If so we can close.

**Comment by haaawk** [comment] 2020-03-09 08:14
This was fixed with https://github.com/scylladb/scylla/pull/5923

**Closed by haaawk** 2020-03-09 08:14 UTC
Labels: CDC, bug
