### ISSUE TITLE
feature request: need clearer error message (at least like clang)

### ISSUE THREAD

**Issue by kokizzu** [scylladb/scylla#5546] opened 2020-01-02 06:23 UTC
- [x] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash): 3.1.2
Cluster size: 1
OS (RHEL/CentOS/Ubuntu/AWS AMI): Ubuntu 18.04

```
SELECT * FROM users WHERE id IN (children) ALLLOW FILTERING;
```

causes a bit cryptic error:
```
SyntaxException: line 1:47  : syntax error...
```

should be at least, please make it beautiful like clang or any other human-oriented compiler

![image](https://user-images.githubusercontent.com/1061610/71654195-fd6c4e80-2d62-11ea-897e-f0004b235656.png)

**Comment by nyh** [comment] 2021-06-14 09:03
This is a duplicate of #1703, I copied the examples here to that issue.

**Closed by nyh** 2021-06-14 09:03 UTC
Labels: CQL, UX, User Request
