### ISSUE TITLE
Can not add a new node to an existing cluster

### ISSUE THREAD

**Issue by Abouzeid** [scylladb/scylla#3157] opened 2018-01-26 06:11 UTC
*Installation details*
Scylla version (or git commit hash):  2.0.2-0.20171201.07b039f
Cluster size: 2 nodes
OS : CentOS 7

I'm totally new to Scylla. I want to have a cluster of three Scylla nodes.
I've two nodes running Scylla. 

**nodetool status**
Datacenter: datacenter1

Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address         Load       Tokens       Owns (effective)  Host ID                               Rack
UN  192.168.12.212  664.33 KB  256          100.0%            18edb4f6-e7b0-4707-977b-4ad5361b5a66  rack1
UN  192.168.12.213  427.49 KB  256          100.0%            6fe570d1-f239-4648-83d2-75257f862763  rack1

My problem is that the third node scylla service is not starting. I am getting that error
$ journalctl _COMM=scylla
'-- Logs begin at Fri 2018-01-26 13:43:55 CST, end at Fri 2018-01-26 13:52:29 CST. --
Jan 26 13:44:31 localhost.localdomain scylla[2644]: Scylla version 2.0.2-0.20171201.07b039f starting ...
Jan 26 13:44:31 localhost.localdomain scylla[2644]:  [shard 0] init - **Could not read configuration file /etc/scylla/scylla.yaml: YAML::TypedBadConversion**<seastar::basic_sstring<char, unsigned int, 15u> > (yaml-cpp: error at line 0
Jan 26 13:44:31 localhost.localdomain scylla[2644]:  [shard 0] seastar - Exiting on unhandled exception: YAML::TypedBadConversion<seastar::basic_sstring<char, unsigned int, 15u> > (yaml-cpp: error at line 0, column 0: bad conversi`

I have set only one seed node which is "192.168.12.212"

**Comment by dorlaor** [comment] 2018-01-26 06:21
Looks like you have a damaged line #0 in your config scylla yaml file.
Can you compare the 3rd node with the others?

**Comment by glommer** [comment] 2018-01-26 06:22
He sent me his file and I started up scylla just fine with his file as is.
Likely we have an issue here.

**Comment by Abouzeid** [comment] 2018-01-26 07:43
I did compare the scylla.yaml file with the other two nodes, they are the same only the Ip addresses are different.

**Comment by Abouzeid** [comment] 2018-01-26 08:01
After copying and pasting the yaml file from one of the running nodes to the new one, still the same error.


Jan 26 15:56:27 localhost.localdomain polkitd[1176]: Unregistered Authentication Agent for unix-process:2757:136523 (system bus name :1.17, object path /org/freedesktop/PolicyKit1/AuthenticationAgent, locale en_US.UTF-8) (disconn
Jan 26 15:56:31 localhost.localdomain sudo[2762]:     root : TTY=pts/0 ; PWD=/root ; USER=root ; COMMAND=/bin/systemctl start scylla-server
Jan 26 15:56:31 localhost.localdomain polkitd[1176]: Registered Authentication Agent for unix-process:2763:136975 (system bus name :1.18 [/usr/bin/pkttyagent --notify-fd 5 --fallback], object path /org/freedesktop/PolicyKit1/Auth
Jan 26 15:56:31 localhost.localdomain systemd[1]: Starting Scylla Server...
-- Subject: Unit scylla-server.service has begun start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit scylla-server.service has begun starting up.
Jan 26 15:56:31 localhost.localdomain scylla_prepare[2768]: tuning /sys/devices/virtual/block/dm-0
Jan 26 15:56:31 localhost.localdomain scylla_prepare[2768]: already tuned: /sys/devices/virtual/block/dm-0/queue/scheduler
Jan 26 15:56:31 localhost.localdomain scylla_prepare[2768]: already tuned: /sys/devices/virtual/block/dm-0/queue/nomerges
Jan 26 15:56:31 localhost.localdomain scylla_prepare[2768]: tuning /sys/devices/LNXSYSTM:00/device:00/PNP0A03:00/device:08/VMBUS:01/vmbus_1/host2/target2:0:0/2:0:0:0/block/sda/sda2
Jan 26 15:56:31 localhost.localdomain scylla_prepare[2768]: tuning /sys/devices/LNXSYSTM:00/device:00/PNP0A03:00/device:08/VMBUS:01/vmbus_1/host2/target2:0:0/2:0:0:0/block/sda
Jan 26 15:56:31 localhost.localdomain scylla_prepare[2768]: already tuned: /sys/devices/LNXSYSTM:00/device:00/PNP0A03:00/device:08/VMBUS:01/vmbus_1/host2/target2:0:0/2:0:0:0/block/sda/queue/scheduler
Jan 26 15:56:31 localhost.localdomain scylla_prepare[2768]: already tuned: /sys/devices/LNXSYSTM:00/device:00/PNP0A03:00/device:08/VMBUS:01/vmbus_1/host2/target2:0:0/2:0:0:0/block/sda/queue/nomerges
Jan 26 15:56:31 localhost.localdomain scylla_prepare[2768]: tuning /sys/devices/virtual/block/dm-0
Jan 26 15:56:31 localhost.localdomain scylla[2773]: Scylla version 2.0.2-0.20171201.07b039f starting ...
Jan 26 15:56:31 localhost.localdomain collectd[1503]: network plugin: Ignoring notification with unknown severity 0.
Jan 26 15:56:31 localhost.localdomain collectd[1503]: network plugin: Ignoring notification with unknown severity 0.
Jan 26 15:56:31 localhost.localdomain collectd[1503]: network plugin: Ignoring notification with unknown severity 0.
Jan 26 15:56:31 localhost.localdomain collectd[1503]: network plugin: Ignoring notification with unknown severity 0.
Jan 26 15:56:31 localhost.localdomain scylla[2773]:  **[shard 0] init - Could not read configuration file /etc/scylla/scylla.yaml: YAML::TypedBadConversion<seastar::basic_sstring<char, unsigned int, 15u> > (yaml-cpp: error at line
Jan 26 15:56:31 localhost.localdomain scylla[2773]:  [shard 0] seastar - Exiting on unhandled exception: YAML::TypedBadConversion<seastar::basic_sstring<char, unsigned int, 15u> > (yaml-cpp: error at line 0, column 0: bad convers
Jan 26 15:56:31 localhost.localdomain systemd[1]: scylla-server.service: main process exited, code=exited, status=1/FAILURE**
Jan 26 15:56:31 localhost.localdomain systemd[1]: Failed to start Scylla Server.
-- Subject: Unit scylla-server.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit scylla-server.service has failed.
--
-- The result is failed.
Jan 26 15:56:31 localhost.localdomain systemd[1]: Dependency failed for Scylla JMX.
-- Subject: Unit scylla-jmx.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit scylla-jmx.service has failed.
--
-- The result is dependency.
Jan 26 15:56:31 localhost.localdomain systemd[1]: Job scylla-jmx.service/start failed with result 'dependency'.
Jan 26 15:56:31 localhost.localdomain systemd[1]: Dependency failed for Run Scylla Housekeeping daily mode.
-- Subject: Unit scylla-housekeeping-daily.timer has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit scylla-housekeeping-daily.timer has failed.
--
-- The result is dependency.
Jan 26 15:56:31 localhost.localdomain systemd[1]: Job scylla-housekeeping-daily.timer/start failed with result 'dependency'.
Jan 26 15:56:31 localhost.localdomain systemd[1]: Dependency failed for Run Scylla Housekeeping restart mode.
-- Subject: Unit scylla-housekeeping-restart.timer has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit scylla-housekeeping-restart.timer has failed.
--
-- The result is dependency.
Jan 26 15:56:31 localhost.localdomain systemd[1]: Job scylla-housekeeping-restart.timer/start failed with result 'dependency'.
Jan 26 15:56:31 localhost.localdomain systemd[1]: Unit scylla-server.service entered failed state.
Jan 26 15:56:31 localhost.localdomain systemd[1]: scylla-server.service failed.
Jan 26 15:56:31 localhost.localdomain polkitd[1176]: Unregistered Authentication Agent for unix-process:2763:136975 (system bus name :1.18, object path /org/freedesktop/PolicyKit1/AuthenticationAgent, locale en_US.UTF-8) (disconn

**Comment by gleb-cloudius** [comment] 2018-01-26 10:30
May be different locale for scylla user?

--
			Gleb.

**Comment by glommer** [comment] 2018-01-27 03:35
@gleb-cloudius good theory. @Abouzeid what is your LOCALE ?

**Comment by gleb-cloudius** [comment] 2018-01-27 14:08
issue #3161 seams to be a dup and there are some finding there.

--
			Gleb.

**Comment by JvGinkel** [comment] 2018-01-27 14:22
Indeed see my latest comment in #3161. The problem is in the package `yaml-cpp-0.5.3-7.el7.x86_64` (or at least the problems started when I updated this package). If you downgrade the package on Centos7 you can start scylladb again. (My cluster is now back online)

**Comment by slivne** [comment] 2018-01-28 09:20
@Abouzeid - I am closing this issue and leaving #3161 open as it has more info - you can use the suggested procedure - we are working on a solution.

**Closed by slivne** 2018-01-28 09:20 UTC

**Comment by Abouzeid** [comment] 2018-01-29 03:25
Thank you all.
Now, I am running the cluster on Ubuntu 16.04. 
It works fine.
