### ISSUE TITLE
Huge timeouts after updating 3.1.1 => 3.2.2

### ISSUE THREAD

**Issue by gibsn** [scylladb/scylla#5922] opened 2020-02-28 12:59 UTC
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [*] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash): 3.2.2
Cluster size: 9 nodes
OS (RHEL/CentOS/Ubuntu/AWS AMI): C7.5

Platform (physical/VM/cloud instance type/docker): bare metal
Hardware: sockets=2 x Intel(R) Xeon(R) Gold 6230 CPU @ 2.10GHz cores=40 hyperthreading=yes memory= 6x32GB DDR4 2666MHz
Disks: RAID 10 of 10HDDs 14TB each for data, RAID 1 SSD 1TB for clogs

We have a cluster of 8 nodes, 4 nodes in each DC, RF = 1, 20TBs of compressed time series data, TWCS.
We decided to update one node to 3.2.2 in order to get more precise timings in tracing to investigate reads timeouts. After update the new version suddenly started consuming lots of CPU, lots of write timeouts appeared:
![Снимок экрана 2020-02-28 в 15 10 40](https://user-images.githubusercontent.com/11294101/75550182-63fba900-5a42-11ea-963d-bbbfe93c7a2a.png)

Logs on that node were full of lines like "[shard 7] tracing - Maximum records limit is hit 2420001 times".

Then both lines in logs and timeouts disappeared, the same time CPU usage on the last shard went to normal:
![Снимок экрана 2020-02-28 в 15 18 02](https://user-images.githubusercontent.com/11294101/75550558-35320280-5a43-11ea-8e49-63a61f62d252.png)

We have ~240k rps writes and ~10 rps reads per cluster. We do record tracing for reads, but not for writes. The affected node was under heavy compaction (see #5921) 

Per Server dashboard with per shard view for the affected node:
![FireShot Capture 025 - Scylla Overview Metrics - Grafana - grafana corp mail ru](https://user-images.githubusercontent.com/11294101/75550502-1b90bb00-5a43-11ea-8a6a-ade7187a096e.png)

**Comment by slivne** [comment] 2020-03-01 10:37
@gibsn 
- can you please share the schema
- can you please share your scylla.yaml

Can you clarify a bit what requests are traced and how:
- do you use probabilistic tracing
- do you use client side tracing 
- ?

**Comment by gibsn** [comment] 2020-03-01 13:06
@slivne 
> can you please share the schema

https://pastebin.com/VCXM2H18

> can you please share your scylla.yaml
Will do tomorrow

> do you use probabilistic tracing
do you use client side tracing

We use client side tracing with gocql. We trace only select requests, somewhat like:
`SELECT id4, id6, id7, id8 FROM ks.cf WHERE id1 = ? AND id2 = ? AND id3 = ? AND id5 = ? AND id4 > ? AND id4 < ? ORDER BY id4 DESC LIMIT ?`

**Comment by gibsn** [comment] 2020-03-01 13:26
BTW I have just grepped client's logs and could not find any tracings from the affected node (with `source: $new_node_ip`)

**Comment by gibsn** [comment] 2020-03-02 14:00
@slivne 
>Will do tomorrow

Sent to shlomi@scylladb.com

**Comment by gibsn** [comment] 2020-03-03 12:38
Tried updating one node to 3.2.0, same problem

**Comment by vladzcloudius** [comment] 2020-03-04 14:45
@gibsn "Logs on that node were full of lines like "[shard 7] tracing - Maximum records limit is hit 2420001 times".
Means that CQL Tracing is enabled and a lot of Traces are generated.
Tracing in particular creates a lot of write pressure on the cluster.
You should be careful when you enable CQL Tracing in order not to kill cluster's performance (e.g. not enable Tracing for each CQL request when you use probabilistic tracing).

**Comment by gibsn** [comment] 2020-03-04 17:59
We disabled tracings on client side, but the problem persists. Lots of "tracing - Maximum records limit is hit" in logs though tracing is disabled

**Comment by gibsn** [comment] 2020-03-10 17:03
> We disabled tracings on client side, but the problem persists. Lots of "tracing - Maximum records limit is hit" in logs though tracing is disabled

Found a bug in client, client would set the tracing bit even though tracing is disabled in app config. Will deploy the fix and report

**Comment by slivne** [comment] 2020-03-16 22:53
I think this was resolved in 3.3 I updated #6014 - the change was not backported as it was not trivial

**Comment by slivne** [comment] 2020-03-23 22:08
@gibsn since we know the issue is related to tracing #6014 - can we close this issue ?

**Comment by gibsn** [comment] 2020-03-24 12:53
@slivne could you please elaborate on how #6014 would lead to huge timeouts? Am I right that after one read query (since we trace only read queries) is traced, all the write queries (which we have 10000 times more) on the same connection start being traced as well?

Also we are planning to update next week, so we will be able to confirm whether our exact problem is solved in 3.3

**Comment by slivne** [comment] 2020-04-14 00:39
@gibsn yes you are correct

the tracing issue is fixed in 3.2 by a092f5d1f4f1b39c3e3734df00bd30e91b6d4282

closing the issue

**Closed by slivne** 2020-04-14 00:39 UTC
Labels: User Request
