### ISSUE TITLE
hintedhandoff_removenode_test Missing: ['hints_manager - Draining for 127.0.9.3: end']

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#5354] opened 2019-11-26 16:51 UTC
Seen in [dtest-debug/314](https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-debug/314/testReport/hintedhandoff_additional_test/TestHintedHandoff/hintedhandoff_removenode_test)
```
tacktrace
Traceback (most recent call last):
  File "/usr/lib64/python2.7/unittest/case.py", line 367, in run
    testMethod()
  File "/jenkins/workspace/scylla-master/dtest-debug/scylla-dtest/hintedhandoff_additional_test.py", line 127, in hintedhandoff_removenode_test
    node1.watch_log_for(msg, from_mark=from_mark, timeout=timeout)
  File "/jenkins/workspace/scylla-master/dtest-debug/scylla-ccm/ccmlib/node.py", line 435, in watch_log_for
    [e.pattern for e in tofind]) + ":\n" + reads[:50] + ".....\nSee {} for remainder".format(filename))
TimeoutError: 21 Nov 2019 05:04:14 [node1] Missing: ['hints_manager - Draining for 127.0.9.3: end']:
```

Scylla version 9a686ac55193f0df4fc923b267b7b36684565a9d
Scylla-dtest version 78c93908540fcf5f05ed48d1845005a027b4c904
(That is scylladb/scylla-dtest#1134 fixing #5244)

[node1.log](https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-debug/314/artifact/logs-debug.2/1574312654267_hintedhandoff_additional_test.TestHintedHandoff.hintedhandoff_removenode_test/node1.log) contains only:
```
TRACE 2019-11-21 05:03:41,849 [shard 0] hints_manager - on_leave_cluster: 127.0.9.3 is removed/decommissioned
TRACE 2019-11-21 05:03:41,849 [shard 0] hints_manager - on_leave_cluster: 127.0.9.3 is removed/decommissioned
TRACE 2019-11-21 05:03:41,853 [shard 1] hints_manager - on_leave_cluster: 127.0.9.3 is removed/decommissioned
TRACE 2019-11-21 05:03:41,853 [shard 1] hints_manager - on_leave_cluster: 127.0.9.3 is removed/decommissioned
INFO  2019-11-21 05:03:41,873 [shard 0] gossip - Completing removal of 127.0.9.3
INFO  2019-11-21 05:03:41,874 [shard 0] gossip - Node 127.0.9.3 will be removed from gossip at [2019-11-24 05:03:41]: (expire = 1574571821871, now = 1574312621871, diff = 259200 seconds)
```

While [node2.log](https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-debug/314/artifact/logs-debug.2/1574312654267_hintedhandoff_additional_test.TestHintedHandoff.hintedhandoff_removenode_test/node2.log):
```
TRACE 2019-11-21 05:03:42,691 [shard 0] hints_manager - Endpoints set has changed and 127.0.9.3 is no longer a replica. Mutating from scratch...
TRACE 2019-11-21 05:03:42,695 [shard 0] hints_manager - on_leave_cluster: 127.0.9.3 is removed/decommissioned
TRACE 2019-11-21 05:03:42,695 [shard 0] hints_manager - on_leave_cluster: 127.0.9.3 is removed/decommissioned
TRACE 2019-11-21 05:03:42,700 [shard 1] hints_manager - on_leave_cluster: 127.0.9.3 is removed/decommissioned
TRACE 2019-11-21 05:03:42,700 [shard 1] hints_manager - on_leave_cluster: 127.0.9.3 is removed/decommissioned
TRACE 2019-11-21 05:03:42,711 [shard 0] hints_manager - send_one_file(): error while sending hints from /jenkins/workspace/scylla-master/dtest-debug/scylla/.dtest/dtest-H2TyrE/test/node2/hints/0/127.0.9.3/HintsLog-1-331420519.log, last RP is {0, 331420519, 28}
TRACE 2019-11-21 05:03:42,711 [shard 0] hints_manager - send_hints(): we handled 0 segments
INFO  2019-11-21 05:03:42,837 [shard 1] compaction - Compacted 2 sstables to [/jenkins/workspace/scylla-master/dtest-debug/scylla/.dtest/dtest-H2TyrE/test/node2/data/system/peers-37f71aca7dc2383ba70672528af04d4f/mc-15-big-Data.db:level=0, ]. 28613 bytes to 17642 (~61% of original) in 145ms = 0.12MB/s. ~256 total partitions merged to 2.
TRACE 2019-11-21 05:03:43,712 [shard 0] hints_manager - Draining for 127.0.9.3: start
TRACE 2019-11-21 05:03:43,713 [shard 0] hints_manager - send_hints(): going to send hints to 127.0.9.3, we have 1 segment to replay
TRACE 2019-11-21 05:03:43,725 [shard 0] hints_manager - Endpoints set has changed and 127.0.9.3 is no longer a replica. Mutating from scratch...
TRACE 2019-11-21 05:03:43,728 [shard 0] hints_manager - Endpoints set has changed and 127.0.9.3 is no longer a replica. Mutating from scratch...
TRACE 2019-11-21 05:03:43,731 [shard 0] hints_manager - Endpoints set has changed and 127.0.9.3 is no longer a replica. Mutating from scratch...
TRACE 2019-11-21 05:03:43,734 [shard 0] hints_manager - Endpoints set has changed and 127.0.9.3 is no longer a replica. Mutating from scratch...
TRACE 2019-11-21 05:03:43,736 [shard 0] hints_manager - Endpoints set has changed and 127.0.9.3 is no longer a replica. Mutating from scratch...
TRACE 2019-11-21 05:03:43,738 [shard 0] hints_manager - Endpoints set has changed and 127.0.9.3 is no longer a replica. Mutating from scratch...
TRACE 2019-11-21 05:03:43,741 [shard 0] hints_manager - Endpoints set has changed and 127.0.9.3 is no longer a replica. Mutating from scratch...
TRACE 2019-11-21 05:03:43,744 [shard 0] hints_manager - Endpoints set has changed and 127.0.9.3 is no longer a replica. Mutating from scratch...
TRACE 2019-11-21 05:03:43,746 [shard 0] hints_manager - Endpoints set has changed and 127.0.9.3 is no longer a replica. Mutating from scratch...
TRACE 2019-11-21 05:03:43,749 [shard 0] hints_manager - Endpoints set has changed and 127.0.9.3 is no longer a replica. Mutating from scratch...
TRACE 2019-11-21 05:03:43,752 [shard 0] hints_manager - Endpoints set has changed and 127.0.9.3 is no longer a replica. Mutating from scratch...
TRACE 2019-11-21 05:03:43,758 [shard 0] hints_manager - Endpoints set has changed and 127.0.9.3 is no longer a replica. Mutating from scratch...
TRACE 2019-11-21 05:03:43,762 [shard 0] hints_manager - Endpoints set has changed and 127.0.9.3 is no longer a replica. Mutating from scratch...
TRACE 2019-11-21 05:03:43,765 [shard 0] hints_manager - Endpoints set has changed and 127.0.9.3 is no longer a replica. Mutating from scratch...
TRACE 2019-11-21 05:03:43,767 [shard 0] hints_manager - Endpoints set has changed and 127.0.9.3 is no longer a replica. Mutating from scratch...
TRACE 2019-11-21 05:03:43,769 [shard 0] hints_manager - Endpoints set has changed and 127.0.9.3 is no longer a replica. Mutating from scratch...
TRACE 2019-11-21 05:03:43,772 [shard 0] hints_manager - Endpoints set has changed and 127.0.9.3 is no longer a replica. Mutating from scratch...
TRACE 2019-11-21 05:03:43,776 [shard 0] hints_manager - send_one_file(): segment /jenkins/workspace/scylla-master/dtest-debug/scylla/.dtest/dtest-H2TyrE/test/node2/hints/0/127.0.9.3/HintsLog-1-331420519.log was sent in full and deleted
TRACE 2019-11-21 05:03:43,776 [shard 0] hints_manager - send_hints(): we handled 1 segments
TRACE 2019-11-21 05:03:43,778 [shard 0] hints_manager - Going to add a store to /jenkins/workspace/scylla-master/dtest-debug/scylla/.dtest/dtest-H2TyrE/test/node2/hints/0/127.0.9.3
TRACE 2019-11-21 05:03:43,786 [shard 0] hints_manager - send_hints(): going to send hints to 127.0.9.3, we have 0 segment to replay
TRACE 2019-11-21 05:03:43,786 [shard 0] hints_manager - send_hints(): we handled 0 segments
TRACE 2019-11-21 05:03:43,786 [shard 0] hints_manager - Draining for 127.0.9.3: end
TRACE 2019-11-21 05:03:43,786 [shard 0] hints_manager - ep_manager(127.0.9.3)::sender: exiting
```

Now, even if node1 had no hints to send, we should still see `ep_manager(127.0.9.3)::sender: exiting` (maybe the test needs to wait for that in the log instead, but this is a different issue)

**Comment by vladzcloudius** [comment] 2019-11-27 21:08
@bhalevy Could you, please, clarify what is the setup and what was the exact command line you were using in order to run the test?

**Comment by vladzcloudius** [comment] 2019-11-27 22:32
@bhalevy I have reproduced (I think) the issue and I think I know what the issue is
The following commit has removed the sleep(30) that was there before:

```
commit 78c93908540fcf5f05ed48d1845005a027b4c904
Author: Benny Halevy <bhalevy@scylladb.com>
Date:   Thu Nov 14 08:15:58 2019 +0200

    hintedhandoff_additional_test: hintedhandoff_removenode_test: watch_log_for 'hints_manager - Draining'

    hintedhandoff_removenode_test fails consistently on jenkins with the following pattern:
      Stacktrace
      Traceback (most recent call last):
        File "/usr/lib64/python2.7/unittest/case.py", line 367, in run
          testMethod()
        File "/jenkins/workspace/scylla-master/dtest-debug/scylla-dtest/hintedhandoff_additional_test.py", line 127, in hintedhandoff_removenode_test
          query_c1c2(session, x, ConsistencyLevel.ONE)
        File "/jenkins/workspace/scylla-master/dtest-debug/scylla-dtest/tools.py", line 60, in query_c1c2
          assert len(rows) == 1
      AssertionError

    Although waiting for 15 seconds after removenode completes seems safe
    this change turns trace logging for the hints manger and explicitly waits
    for indication in the log that draining is complete.

    Fixes https://github.com/scylladb/scylla/issues/5244

    Signed-off-by: Benny Halevy <bhalevy@scylladb.com>
```

...and instead it added tracking after `node1` only, while it should have tracked both `node1` and `node2`.

Here is what I see in the dtest log:
```
2019-11-27 16:21:11.563982 Removing node3...
2019-11-27 16:21:50.269968 Waiting 30s for hints to be sent...
2019-11-27 16:21:50.296373 Reading the data...
2019-11-27 16:21:51.035222 Check that the directories have been cleaned up...
2019-11-27 16:21:51.035309 Check that the directory /home/vladz/.dtest/dtest-69qazA/test/node1/hints/*/127.0.0.3 is not present...
2019-11-27 16:21:51.035545 Check that the directory /home/vladz/.dtest/dtest-69qazA/test/node2/hints/*/127.0.0.3 is not present...
FAIL
```

And this is what I see in the corresponding `node2` log:
```
TRACE 2019-11-27 16:21:51,469 [shard 0] hints_manager - Draining for 127.0.0.3: start
TRACE 2019-11-27 16:21:51,469 [shard 0] hints_manager - send_hints(): going to send hints to 127.0.0.3, we have 0 segment to replay
TRACE 2019-11-27 16:21:51,469 [shard 0] hints_manager - send_hints(): we handled 0 segments
DEBUG 2019-11-27 16:21:51,469 [shard 0] commitlog - Issuing sync for all segments (active)
DEBUG 2019-11-27 16:21:51,470 [shard 0] commitlog - Issuing sync for all segments (shutdown)
DEBUG 2019-11-27 16:21:51,470 [shard 0] commitlog - Segment HintsLog-1-173920193.log is no longer active and will submitted for delete now
DEBUG 2019-11-27 16:21:51,470 [shard 0] commitlog - Deleting segment file /home/vladz/.dtest/dtest-69qazA/test/node2/hints/0/127.0.0.3/HintsLog-1-173920193.log
TRACE 2019-11-27 16:21:51,471 [shard 0] hints_manager - Going to add a store to /home/vladz/.dtest/dtest-69qazA/test/node2/hints/0/127.0.0.3
TRACE 2019-11-27 16:21:51,475 [shard 0] hints_manager - send_hints(): going to send hints to 127.0.0.3, we have 0 segment to replay
TRACE 2019-11-27 16:21:51,475 [shard 0] hints_manager - send_hints(): we handled 0 segments
TRACE 2019-11-27 16:21:51,475 [shard 0] hints_manager - Draining for 127.0.0.3: end
TRACE 2019-11-27 16:21:51,475 [shard 0] hints_manager - ep_manager(127.0.0.3)::sender: exiting
DEBUG 2019-11-27 16:21:51,475 [shard 0] commitlog - Issuing sync for all segments (active)
DEBUG 2019-11-27 16:21:51,475 [shard 0] commitlog - Created new reserve segment HintsLog-1-173920192.log
DEBUG 2019-11-27 16:21:51,475 [shard 0] commitlog - Issuing sync for all segments (shutdown)
DEBUG 2019-11-27 16:21:51,476 [shard 0] commitlog - Segment HintsLog-1-173920192.log is no longer active and will submitted for delete now
DEBUG 2019-11-27 16:21:51,476 [shard 0] commitlog - Deleting segment file /home/vladz/.dtest/dtest-69qazA/test/node2/hints/0/127.0.0.3/HintsLog-1-173920192.log
```

You can clearly see that `hints_manager@node1` is still draining when dtest has already concluded about the failure.

**Comment by vladzcloudius** [comment] 2019-11-27 22:38
Also the dtest patch I mentioned above is not good enough because the message it checks for doesn't guarantee that the directories in question are already deleted - not even that they are empty.

Another debug message needs to be added to the HH code.

**Comment by bhalevy** [comment] 2019-11-28 07:16
@vladzcloudius previously there was an unconditional sleep for 15 seconds that indeed may have allowed node2 to drain hints too, so we can also add a `watch_log_for` on node2 as well.

That said, this doesn't explain this issue since here node1 didn't seem to drain at all, otherwise we should have seen at least `Draining for 127.0.9.3: start` or `hints_manager - ep_manager(127.0.9.3)::sender: exiting`

**Comment by bhalevy** [comment] 2019-11-28 08:31
@vladzcloudius In addition to #5354 see https://github.com/bhalevy/scylla-dtest/commits/hintedhandoff_removenode_test

**Comment by piodul** [comment] 2019-11-28 11:29
@bhalevy Are you working on this issue right now, or can I take it over? I can see you already pushed some commits related to this issue (on the `hints-manager-remove-file-message` branch).

**Comment by bhalevy** [comment] 2019-12-01 11:03
> @bhalevy Are you working on this issue right now, or can I take it over? I can see you already pushed some commits related to this issue (on the `hints-manager-remove-file-message` branch).

@piodul Yes, I pushed some commits to help debug this issue
But I'm not currently working on this particular issue where draining of hints seems to hang, at least in debug mode.  @vladzcloudius speculated it might be related to differences between release and debug with respect to seastar yielding between continuations.

**Comment by bhalevy** [comment] 2019-12-02 16:52
https://jenkins.scylladb.com/view/scylla-3.2/job/scylla-3.2/job/next/25/testReport/junit/hintedhandoff_additional_test/TestHintedHandoff/hintedhandoff_removenode_test/
demonstrates draining issues on node2.
Without #1165 it fails to verify that the hints directory is empty and the failure looks like this:
```
Stacktrace
Traceback (most recent call last):
  File "/usr/lib64/python2.7/unittest/case.py", line 367, in run
    testMethod()
  File "/jenkins/workspace/scylla-3.2/next/scylla-dtest/hintedhandoff_additional_test.py", line 135, in hintedhandoff_removenode_test
    self.__check_hints_dir_present(node_from=node2, node_to=node3, must_be_present=False)
AssertionError
```

**Comment by vladzcloudius** [comment] 2019-12-07 00:07
> https://jenkins.scylladb.com/view/scylla-3.2/job/scylla-3.2/job/next/25/testReport/junit/hintedhandoff_additional_test/TestHintedHandoff/hintedhandoff_removenode_test/
> demonstrates draining issues on node2.
> Without #1165 it fails to verify that the hints directory is empty and the failure looks like this:

@bhalevy I really don't understand how #1165 can be possibly related to this issue.

Let me address all your previous questions:

Like I've already mentioned the subject of this issue is misleading since waiting for `['hints_manager - Draining for 127.0.9.3: end']` would not make this test to pass.

> That said, this doesn't explain this issue since here node1 didn't seem to drain at all, otherwise we should have seen at least Draining for 127.0.9.3: start or hints_manager - ep_manager(127.0.9.3)::sender: exiting

The node/shard is only going to shut down a sender if the corresponding `end_point_manager` has been created, which means there was at least one incident of hint generation on that shard for that specific destination. Apparently in that case where were no hints generated on `node1` and this totally normal.

Now let me get to the issue with this test and why it was failing: this was a combination of issues:

1) There wasn't a log message in the scylla code that would properly denote the termination of hints draining for a particular destination: this is covered by the 2-liner I sent to you before and I see you sent a PR for that: https://github.com/scylladb/scylla/pull/5372 
2) The test was teribly broken since we switched from a time waiting to log parsing: 
  * It waited for a wrong log message.
  * It didn't wait for this message to appear on all nodes.
  * It didn't wait for the message on all shards.
  * It didn't wait for that message to be printed by all hints managers and we have 2: one for regular hints and one for view hints.

And to add to the insult:
3) After you address all these above and start waiting for a proper message to appear 4 times (for SMP=2) by calling a watch_for_log(<list of 4 messages>) you'd hit https://github.com/scylladb/scylla-ccm/issues/197.

I've create PR for (2) and (3). (2) Obviously depends on (1).

**Comment by bhalevy** [comment] 2019-12-15 17:37
Not sure this was entirely a bug in scylla-dtest, or whether hh draining is really hung.
Will reopen if hit again...

**Comment by bhalevy** [comment] 2019-12-19 17:18
Still seeing this. Most recently in https://jenkins.scylladb.com/view/master/job/scylla-master/job/next/1414/testReport/hintedhandoff_additional_test/TestHintedHandoff/hintedhandoff_removenode_test/

**Comment by vladzcloudius** [comment] 2019-12-19 17:22
@bhalevy This is caused by a bug in a corresponding dtest (see [here](https://github.com/scylladb/scylla-dtest/blob/next/hintedhandoff_additional_test.py#L134)) where a "min" is used instead of "max".

**Comment by bhalevy** [comment] 2019-12-20 11:54
> @bhalevy This is caused by a bug in a corresponding dtest (see [here](https://github.com/scylladb/scylla-dtest/blob/next/hintedhandoff_additional_test.py#L134)) where a "min" is used instead of "max".

Good catch! sending a fix...

**Comment by bhalevy** [comment] 2019-12-24 11:59
Reproduced in debug build with scylladb/scylla-dtest@58ca4e191129a850c4f5a4e21e28552227b55aa7 (including scylladb/scylla-dtest@01e21031d02d2662e00573f0ce7d6fb2172c992d)
https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-debug/351/testReport/hintedhandoff_additional_test/TestHintedHandoff/hintedhandoff_removenode_test/
```
Stacktrace
Traceback (most recent call last):
  File "/usr/lib64/python2.7/unittest/case.py", line 367, in run
    testMethod()
  File "/jenkins/workspace/scylla-master/dtest-debug/scylla-dtest/hintedhandoff_additional_test.py", line 135, in hintedhandoff_removenode_test
    node.watch_log_for(msgs, from_mark=from_mark, timeout=node_timeout)
  File "/jenkins/workspace/scylla-master/dtest-debug/scylla-ccm/ccmlib/node.py", line 443, in watch_log_for
    [e.pattern for e in tofind]) + ":\n" + reads[:50] + ".....\nSee {} for remainder".format(filename))
TimeoutError: 24 Dec 2019 04:55:39 [node1] Missing: ['hints_manager - drain_for: finished draining 127.0.65.3']:
```

https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-debug/351/artifact/logs-debug.2/1577163339427_hintedhandoff_additional_test.TestHintedHandoff.hintedhandoff_removenode_test/node1.log indeed missing one of the expected instances of the log message (has 3 out of 4):
```
TRACE 2019-12-24 04:55:06,982 [shard 0] hints_manager - on_leave_cluster: 127.0.65.3 is removed/decommissioned
TRACE 2019-12-24 04:55:06,982 [shard 0] hints_manager - on_leave_cluster: 127.0.65.3 is removed/decommissioned
TRACE 2019-12-24 04:55:06,985 [shard 0] hints_manager - drain_for: finished draining 127.0.65.3
TRACE 2019-12-24 04:55:06,986 [shard 0] hints_manager - drain_for: finished draining 127.0.65.3
TRACE 2019-12-24 04:55:06,986 [shard 1] hints_manager - on_leave_cluster: 127.0.65.3 is removed/decommissioned
TRACE 2019-12-24 04:55:06,986 [shard 1] hints_manager - on_leave_cluster: 127.0.65.3 is removed/decommissioned
TRACE 2019-12-24 04:55:07,003 [shard 1] hints_manager - drain_for: finished draining 127.0.65.3
```

**Comment by piodul** [comment] 2019-12-24 14:55
Not a complete analysis, but a (hopefully) helpful observation:

It looks like the periodic job spawned in `manager::end_point_hints_manager::sender::start` got stuck - there should be more logs from the calls to `send_hints_maybe`. The draining operation probably got stuck waiting for this job to finish.

I don't know yet why that job could get stuck. Initially I suspected that `_next_flush_tp` and `_next_send_retry_tp` are not initialized on construction which would cause infinite wait, but I checked that they have proper default constructors.

**Comment by vladzcloudius** [comment] 2019-12-26 18:10
@piodul Yes, the loop in the thread spawned from the sender::start() is supposed to print a few messages every second and it clearly stops after the first iteration. 

This looks like a regression and doesn't seem to be related to the original issue.

@bhalevy I'd recommend to close this issue and open a new one because symptoms are completely different.

**Comment by vladzcloudius** [comment] 2019-12-26 23:10
@piodul @bhalevy I ran the test for ~4h 45m (100 iterations) on my laptop and it passed (I used the latest master of scylla) and it didn't reproduce.

Like I mentioned, I think it's a regression and if it reproduces, `git bisect` should be used to catch the offending patch.

**Comment by bhalevy** [comment] 2020-04-22 13:46
We didn't hit this for a long while.  We can (re)close the issue IMO.

**Closed** 2020-04-22 14:32 UTC
Labels: bug, dtest, hinted-handoff
