### ISSUE TITLE
mv_populating_from_existing_data_during_inserts_test failed: [Errno 11] Resource temporarily unavailable

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#4283] opened 2019-02-25 13:26 UTC
scylla version [a3a7bea](https://github.com/scylladb/scylla/commit/a3a7bea12f44a3315493469c2d4c028eb7ec5e56)
scylladb/scylla-dtest version [8126bd1](https://github.com/scylladb/scylla-dtest/commit/8126bd12f144afa6084f85c14a976e4c3f420297)

Seen in [dtest-release/41/testReport/materialized_views_test/TestMaterializedViews/mv_populating_from_existing_data_during_inserts_test](http://jenkins.cloudius-systems.com:8080/view/master/job/scylla-master/job/dtest-release/41/testReport/materialized_views_test/TestMaterializedViews/mv_populating_from_existing_data_during_inserts_test/):
```
Error Message
[Errno 11] Resource temporarily unavailable
...
cassandra.cluster: DEBUG: Refreshing schema in response to schema change. {'keyspace': u'ks', 'change_type': u'CREATED', 'target_type': u'TABLE', u'table': u'tm_table_mv_8'}
dtest: DEBUG: materialized_views_test.TestMaterializedViews.mv_populating_from_existing_data_during_inserts_testmv_populating_from_existing_data_during_inserts_test - Materialized view tm_table_mv_8 has been created
dtest: DEBUG: materialized_views_test.TestMaterializedViews.mv_populating_from_existing_data_during_inserts_testmv_populating_from_existing_data_during_inserts_test - CREATE MATERIALIZED VIEW ks.tm_table_mv_9 AS SELECT clmn_int9 FROM ks.tm_table WHERE id IS NOT NULL and clmn_int9 IS NOT NULL PRIMARY KEY (id, clmn_int9);
cassandra.connection: DEBUG: Message pushed from server: <EventMessage(event_type=u'SCHEMA_CHANGE', trace_id=None, event_args={'keyspace': u'ks', 'change_type': u'UPDATED', 'target_type': u'TABLE', u'table': u'tm_table'}, stream_id=-1)>
cassandra.connection: DEBUG: Message pushed from server: <EventMessage(event_type=u'SCHEMA_CHANGE', trace_id=None, event_args={'keyspace': u'ks', 'change_type': u'CREATED', 'target_type': u'TABLE', u'table': u'tm_table_mv_9'}, stream_id=-1)>
...
cassandra.cluster: DEBUG: Re-preparing unrecognized prepared statement against host 127.0.40.3: INSERT INTO ks.tm_table (id, clmn_int0, clmn_int1, clmn_int2, clmn_int3, clmn_int4, clmn_int5, clmn_int6, clmn_int7, clmn_int8, clmn_int9) VALUES (?,?,?,?,?,?,?,?,?,?,?)
dtest: DEBUG: materialized_views_test.TestMaterializedViews.mv_populating_from_existing_data_during_inserts_testmv_populating_from_existing_data_during_inserts_test - Materialized view tm_table_mv_9 has been created
...
dtest: DEBUG: materialized_views_test.TestMaterializedViews.mv_populating_from_existing_data_during_inserts_testmv_populating_from_existing_data_during_inserts_test - Finish prefill
dtest: DEBUG: materialized_views_test.TestMaterializedViews.mv_populating_from_existing_data_during_inserts_testmv_populating_from_existing_data_during_inserts_test - '2' threads finished at 2019-02-25 06:40:14.763776
dtest: DEBUG: materialized_views_test.TestMaterializedViews.mv_populating_from_existing_data_during_inserts_testmv_populating_from_existing_data_during_inserts_test - Waiting for view ks.tm_table_mv_2 to finish building...
...
dtest: DEBUG: materialized_views_test.TestMaterializedViews.mv_populating_from_existing_data_during_inserts_testmv_populating_from_existing_data_during_inserts_test - Waiting for view ks.tm_table_mv_3 to finish building...
dtest: DEBUG: materialized_views_test.TestMaterializedViews.mv_populating_from_existing_data_during_inserts_testmv_populating_from_existing_data_during_inserts_test - Waiting for view ks.tm_table_mv_0 to finish building...
...
dtest: DEBUG: materialized_views_test.TestMaterializedViews.mv_populating_from_existing_data_during_inserts_testmv_populating_from_existing_data_during_inserts_test - Waiting for view ks.tm_table_mv_9 to finish building...
--------------------- >> end captured logging << ---------------------
Stacktrace
  File "/usr/lib64/python2.7/unittest/case.py", line 367, in run
    testMethod()
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/materialized_views_test.py", line 564, in mv_populating_from_existing_data_during_inserts_test
    self._mv_populating_from_existing_data_during_changes_test('insert', nodes=4, rf=3, mvs=10, prefill=40000, fail=False)
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/materialized_views_test.py", line 641, in _mv_populating_from_existing_data_during_changes_test
    wait_for_view(cluster=self.cluster, session=session, ks=tm.keyspace, view=mv_name)
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/scylla_tools.py", line 898, in wait_for_view
    if _view_build_finished_on_live_nodes():
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/scylla_tools.py", line 885, in _view_build_finished_on_live_nodes
    if node.is_live() and not (UUID(node.hostid()) in done):
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-ccm/ccmlib/node.py", line 1230, in hostid
    info = self.nodetool('info', capture_output=True)[0]
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-ccm/ccmlib/node.py", line 702, in nodetool
    p = subprocess.Popen(args, env=env, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/usr/lib64/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 938, in _execute_child
    self.pid = os.fork()
```

Have we run out of processes?

```
$ man 2 fork

ERRORS
       EAGAIN A system-imposed limit on the number of threads was encountered.  There are a number of limits that may trigger this error:

              *  the RLIMIT_NPROC soft resource limit (set via setrlimit(2)), which limits the number of processes and threads for a real user ID, was reached;

              *  the kernel's system-wide limit on the number of processes and threads, /proc/sys/kernel/threads-max, was reached (see proc(5));

              *  the maximum number of PIDs, /proc/sys/kernel/pid_max, was reached (see proc(5)); or

              *  the PID limit (pids.max) imposed by the cgroup "process number" (PIDs) controller was reached.

       EAGAIN The caller is operating under the SCHED_DEADLINE scheduling policy and does not have the reset-on-fork flag set.  See sched(7).
```

**Comment by bentsi** [comment] 2019-02-26 14:13
it looks like we hit hit the nproc limit

**Comment by bentsi** [comment] 2019-03-03 16:24
The test passed during last 3 builds. The issue is probably in the environment that the test ran in.
![image](https://user-images.githubusercontent.com/5269241/53698150-72889380-3de1-11e9-81bc-d8d6b28df3e2.png)
Let's close this and reopen if it happens again.

**Closed** 2019-03-03 17:24 UTC
Labels: dtest
