### ISSUE TITLE
coredumps not fully generated on i2.8xlarge

### ISSUE THREAD

**Issue by glommer** [scylladb/scylla#1864] opened 2016-11-20 18:35 UTC
The bug in issue #1860 was fixed, but one issue remains:
systemd will timeout the stop procedure during coredump generation, and the result coredump file will be truncated.

That renders it useless for future analysis.

**Comment by slivne** [comment] 2016-11-24 13:22
@avikivity should we increase the timeout ?

should we move and disable timeout for stop

use systemd
```
TimeoutStopSec=infinity
```

**Comment by syuu1228** [comment] 2016-12-05 21:37
Is systemd really stops coredump handler?
A coredump handler is called from kernel when the process crashed, probably it's not part of scylla-server.service.

I tested scylla-1.4.2 on i2.8xlarge, I couldn't open coredump in gdb, so maybe it's because coredump is truncated, but TimeoutStopSec=infinity doesn't change the result.
It causes segmentation fault when starting up:
```
GNU gdb (GDB) Red Hat Enterprise Linux 7.6.1-80.el7
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /usr/bin/scylla...Reading symbols from /usr/lib/debug/usr/bin/scylla.debug...[root@ip-172-30-0-214 coredump]#
[root@ip-172-30-0-214 coredump]# coredumpctl list
TIME                            PID   UID   GID SIG PRESENT EXE

Mon 2016-12-05 21:09:54 UTC    3772   994  1001   6   /usr/bin/scylla
Mon 2016-12-05 21:11:41 UTC    4140     0     0  11 * /usr/bin/gdb
```

I also test with sysctl -w "kernel.core_pattern=|/usr/lib/scylla/scylla_save_coredump %e %t %p", so it doesn't uses systemd-coredump, result was same.
With both handler I got 220GB of coredump, the file size sounds like not too small (means truncated) since i2.8xlarge's memory size is 239GB.

Here's backtrace result of gdb coredump:
```
GNU gdb (GDB) Red Hat Enterprise Linux 7.6.1-80.el7
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /usr/bin/gdb...Reading symbols from /usr/lib/debug/usr/bin/gdb.debug...done.
done.
[New LWP 4140]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `gdb /usr/bin/scylla core.scylla-2016-12-05-20:41:05-3294'.
Program terminated with signal 11, Segmentation fault.
#0  0x00007fc80e381577 in _IO_vfprintf_internal (s=s@entry=0x7ffc698491d0, format=format@entry=0x84d7ae "%ld", ap=ap@entry=0x7ffc69849308)
    at vfprintf.c:257
257	  int save_errno = errno;
Missing separate debuginfos, use: debuginfo-install pcre-8.32-15.el7_2.1.x86_64
(gdb) bt
#0  0x00007fc80e381577 in _IO_vfprintf_internal (s=s@entry=0x7ffc698491d0, format=format@entry=0x84d7ae "%ld", ap=ap@entry=0x7ffc69849308)
    at vfprintf.c:257
#1  0x00007fc80e445ce8 in ___vsprintf_chk (s=0x7ffc69849490 "", flags=1, slen=25, format=0x84d7ae "%ld", args=args@entry=0x7ffc69849308)
    at vsprintf_chk.c:85
#2  0x00007fc80e445c3d in ___sprintf_chk (s=s@entry=0x7ffc69849490 "", flags=flags@entry=1, slen=slen@entry=25, format=format@entry=0x84d7ae "%ld")
    at sprintf_chk.c:32
#3  0x000000000079485d in sprintf (__fmt=0x84d7ae "%ld", __s=0x7ffc69849490 "") at /usr/include/bits/stdio2.h:33
#4  d_append_num (l=<optimized out>, dpi=0x7ffc6a043fd0) at ../../libiberty/cp-demangle.c:3650
#5  d_print_comp (dpi=0x7ffc6a043fd0, options=<optimized out>, dc=0x7ffc6a044a68) at ../../libiberty/cp-demangle.c:4818
#6  0x000000000079332a in d_print_comp (dpi=0x7ffc6a043fd0, options=259, dc=0x7ffc6a044a98) at ../../libiberty/cp-demangle.c:3876
#7  0x0000000000796a14 in d_print_mod_list (dpi=dpi@entry=0x7ffc6a043fd0, options=options@entry=259, mods=mods@entry=0x7ffc69849840, 
    suffix=suffix@entry=0) at ../../libiberty/cp-demangle.c:4967
#8  0x0000000000796fb1 in d_print_function_type (dpi=dpi@entry=0x7ffc6a043fd0, options=options@entry=259, mods=0x7ffc69849840, dc=0x7ffc6a044b10)
    at ../../libiberty/cp-demangle.c:5107
#9  0x0000000000793cfd in d_print_comp (dpi=0x7ffc6a043fd0, options=259, dc=0x7ffc6a044b10) at ../../libiberty/cp-demangle.c:4318
```

**Comment by syuu1228** [comment] 2017-01-05 10:32
ping

**Comment by tzach** [comment] 2017-02-12 12:02
@glommer @avikivity 
@syuu1228 ruled out the system timeout, how should we progress on this issue?

**Comment by slivne** [comment] 2017-05-25 10:50
@syuu1228 can we test withe 1.7 AMI on i2.8x - if it works lets close this.

**Comment by syuu1228** [comment] 2017-05-25 12:24
Okay will try.

2017年5月25日(木) 午後7:50 Shlomi Livne <notifications@github.com>:

**Comment by slivne** [comment] 2017-06-29 12:28
@syuu1228 ping

**Comment by syuu1228** [comment] 2017-07-05 12:29
@slivne Not able to reproduce on 1.7AMI/i2.8x.

```
[centos@ip-10-33-224-184 ~]$ sudo /opt/scylladb/bin/gdb /var/lib/systemd/coredump/core.scylla.994.a1d435ea7b904710a1828fc50da2f0ba.2848.1499247294000000
GNU gdb (GDB) Red Hat Enterprise Linux 7.10.1-30.el7.centos
Copyright (C) 2015 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
[New LWP 2848]
[New LWP 2849]
[New LWP 2913]
[New LWP 2874]
[New LWP 2877]
[New LWP 2868]
[New LWP 2886]
[New LWP 2876]
[New LWP 2880]
[New LWP 2892]
[New LWP 2891]
[New LWP 2901]
[New LWP 2896]
[New LWP 2882]
[New LWP 2867]
[New LWP 2865]
[New LWP 2905]
[New LWP 2911]
[New LWP 2907]
[New LWP 2910]
[New LWP 2916]
[New LWP 2924]
[New LWP 2921]
[New LWP 2927]
[New LWP 2920]
[New LWP 2932]
[New LWP 2925]
[New LWP 2933]
[New LWP 2937]
[New LWP 2935]
[New LWP 2869]
[New LWP 2917]
[New LWP 2883]
[New LWP 2878]
[New LWP 2872]
[New LWP 2889]
[New LWP 2879]
[New LWP 2884]
[New LWP 2894]
[New LWP 2895]
[New LWP 2897]
[New LWP 2903]
[New LWP 2888]
[New LWP 2871]
[New LWP 2909]
[New LWP 2914]
[New LWP 2902]
[New LWP 2904]
[New LWP 2908]
[New LWP 2915]
[New LWP 2923]
[New LWP 2919]
[New LWP 2926]
[New LWP 2918]
[New LWP 2929]
[New LWP 2922]
[New LWP 2931]
[New LWP 2936]
[New LWP 2934]
[New LWP 2853]
[New LWP 2850]
[New LWP 2852]
[New LWP 2854]
[New LWP 2856]
[New LWP 2857]
[New LWP 2858]
[New LWP 2859]
[New LWP 2861]
[New LWP 2930]
[New LWP 2860]
[New LWP 2855]
[New LWP 2851]
[New LWP 2862]
[New LWP 2863]
[New LWP 2873]
[New LWP 2870]
[New LWP 2866]
[New LWP 2864]
[New LWP 2875]
[New LWP 2881]
[New LWP 2887]
[New LWP 2885]
[New LWP 2893]
[New LWP 2890]
[New LWP 2898]
[New LWP 2906]
[New LWP 2900]
[New LWP 2912]
[New LWP 2928]
[New LWP 2899]
Reading symbols from /usr/bin/scylla...Reading symbols from /usr/lib/debug/usr/bin/scylla.debug...../../gdb/cp-support.c:1595: demangler-warning: unable to demangle '_ZN8futurizeI13frozen_schemaE5applyIRZN7seastar7shardedIN7service13storage_proxyEE9invoke_onIZZNS6_22init_messaging_serviceEvENKUljN5utils4UUIDEE6_clEjSA_EUlOT_E_6futureIJS0_EEEET0_jSD_EUlvE_JEEESG_SD_DpOT0_' (demangler failed with signal 11)
Unable to dump core, use `ulimit -c unlimited' before executing GDB next time.
../../gdb/cp-support.c:1608: demangler-warning: unable to demangle '_ZN8futurizeI13frozen_schemaE5applyIRZN7seastar7shardedIN7service13storage_proxyEE9invoke_onIZZNS6_22init_messaging_serviceEvENKUljN5utils4UUIDEE6_clEjSA_EUlOT_E_6futureIJS0_EEEET0_jSD_EUlvE_JEEESG_SD_DpOT0_' (demangler failed with signal 11)
A problem internal to GDB has been detected,
further debugging may prove unreliable.
Quit this debugging session? (y or n) n

This is a bug, please report it.  For instructions, see:
<http://www.gnu.org/software/gdb/bugs/>.

done.
done.
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `/usr/bin/scylla --log-to-syslog 1 --log-to-stdout 0 --default-log-level info --'.
Program terminated with signal SIGABRT, Aborted.
#0  0x00007f0c419aef27 in epoll_pwait () from /lib64/libc.so.6
[Current thread is 1 (Thread 0x7f0c456b1540 (LWP 2848))]
Missing separate debuginfos, use: debuginfo-install bzip2-libs-1.0.6-13.el7.x86_64 cryptopp-5.6.2-10.el7.x86_64 elfutils-libelf-0.163-3.el7.x86_64 elfutils-libs-0.163-3.el7.x86_64 glibc-2.17-106.el7_2.8.x86_64 gmp-6.0.0-12.el7_1.x86_64 gnutls-3.3.24-1.el7.x86_64 gnutls-c++-3.3.24-1.el7.x86_64 hwloc-libs-1.11.2-1.el7.x86_64 jsoncpp-0.10.5-2.el7.x86_64 keyutils-libs-1.5.8-3.el7.x86_64 krb5-libs-1.13.2-12.el7_2.x86_64 libaio-0.3.109-13.el7.x86_64 libattr-2.4.46-12.el7.x86_64 libcap-2.22-8.el7.x86_64 libcom_err-1.42.9-7.el7.x86_64 libffi-3.0.13-16.el7.x86_64 libgcc-4.8.5-4.el7.x86_64 libgcrypt-1.5.3-12.el7_1.1.x86_64 libgpg-error-1.12-3.el7.x86_64 libpciaccess-0.13.4-2.el7.x86_64 libselinux-2.2.2-6.el7.x86_64 libstdc++-4.8.5-4.el7.x86_64 libtasn1-3.8-2.el7.x86_64 libtool-ltdl-2.4.2-22.el7_3.x86_64 libunwind-1.1-5.el7_2.2.x86_64 libxml2-2.9.1-6.el7_2.3.x86_64 lz4-1.7.3-1.el7.x86_64 nettle-2.7.1-8.el7.x86_64 nss-softokn-freebl-3.16.2.3-14.2.el7_2.x86_64 numactl-libs-2.0.9-6.el7_2.x86_64 openssl-libs-1.0.1e-51.el7_2.7.x86_64 p11-kit-0.20.7-3.el7.x86_64 pcre-8.32-15.el7_2.1.x86_64 protobuf-2.5.0-8.el7.x86_64 snappy-1.1.0-3.el7.x86_64 systemd-libs-219-19.el7_2.13.x86_64 thrift-0.9.1-15.el7.x86_64 trousers-0.3.13-1.el7.x86_64 xz-libs-5.1.2-12alpha.el7.x86_64 yaml-cpp-0.5.1-6.el7.x86_64 zlib-1.2.7-15.el7.x86_64
(gdb) bt
#0  0x00007f0c419aef27 in epoll_pwait () from /lib64/libc.so.6
#1  0x00000000004f640b in reactor_backend_epoll::wait_and_process (this=this@entry=0x600000432000,
    timeout=timeout@entry=-1, active_sigmask=active_sigmask@entry=0x600000432010) at core/reactor.cc:2673
#2  0x00000000004f6581 in reactor::wait_and_process (active_sigmask=0x600000432010, timeout=-1,
    this=0x600000432000) at core/reactor.hh:944
#3  reactor::sleep (this=0x600000432000) at core/reactor.cc:2545
#4  0x000000000053215b in reactor::run (this=0x600000432000) at core/reactor.cc:2514
#5  0x00000000005b1c4d in app_template::run_deprecated(int, char**, std::function<void ()>&&) (
    this=this@entry=0x7ffffb5b3860, ac=ac@entry=19, av=av@entry=0x7ffffb5b3aa8,
    func=func@entry=<unknown type in /usr/lib/debug/usr/bin/scylla.debug, CU 0x9b2d3e, DIE 0xaaa127>)
    at core/app-template.cc:131
#6  0x000000000047338e in main (ac=19, av=0x7ffffb5b3aa8) at main.cc:659
(gdb)
```

**Closed** 2017-07-05 14:24 UTC
