### ISSUE TITLE
need support for old expired sstables remain(ttl bug)

### ISSUE THREAD

**Issue by ban4785** [scylladb/scylla#3233] opened 2018-02-26 01:18 UTC
*Installation details*
Scylla version (or git commit hash): 1.7.1
Cluster size: 3
OS (RHEL/CentOS/Ubuntu/AWS AMI): RHEL 7.2

*Hardware details (for performance issues)*          Delete if unneeded
Platform (physical/VM/cloud instance type/docker): physical
Hardware: sockets= cores= hyperthreading= memory= 
Disks: (SSD/HDD, count) 2SSD, raid0, 7T

hi 
we deployed scylladb 2017 july,
main log gathering table was setting 31days ttl, **but some old expired sstable files are remain.**
expired sstable files are about 1,260 and 1T size per node.

 

remain expired sstables sample : 
-rw-r--r-- 1 scylla scylla  1.4G Jul  9  2017 table-ka-7468-Data.db
-rw-r--r-- 1 scylla scylla  1.8G Jul 11  2017 table-ka-8214-Data.db                             
-rw-r--r-- 1 scylla scylla  1.4G Aug  5  2017 table-ka-19481-Data.db
-rw-r--r-- 1 scylla scylla  1.3G Aug  5  2017 table-ka-19468-Data.db                                       
-rw-r--r-- 1 scylla scylla  1.4G Aug 25 09:17 table-ka-28305-Data.db
-rw-r--r-- 1 scylla scylla  1.4G Aug 26 17:20 table-ka-28640-Data.db                                      
-rw-r--r-- 1 scylla scylla  1.3G Sep  2 09:17 table-ka-31015-Data.db
-rw-r--r-- 1 scylla scylla  1.3G Sep  3 17:12 table-ka-31705-Data.db                                       
-rw-r--r-- 1 scylla scylla  682M Oct 12 09:15 table-ka-40454-Data.db
-rw-r--r-- 1 scylla scylla  1.5G Dec 15 09:39 table-ka-60796-Data.db
-rw-r--r-- 1 scylla scylla   32M Dec 26 01:53 table-ka-63967-Data.db

and analyzed that sstables with sstable2json & sstablemetadata,
but we could see all datas were expired.
this is sample data result by sstable2json : 

{"key": "2017122413:3589",
 "cells": [["2017-12-24 13\\:00+0900:",1514088000,1514088000611000,"d"],
           ["2017-12-24 13\\:00+0900:lt",1514088000,1514088000611000,"d"],
           ["2017-12-24 13\\:00+0900:product",1514088000,1514088000611000,"d"],
           ["2017-12-24 13\\:00+0900:spec",1514088000,1514088000611000,"d"],
           ["2017-12-24 13\\:00+0900:st",1514088000,1514088000611000,"d"],
           ["2017-12-24 13\\:00+0900:vl",1514088000,1514088000611000,"d"],
           ["2017-12-24 13\\:00+0900:",1514088004,1514088001907000,"d"],
           ["2017-12-24 13\\:00+0900:lt",1514088004,1514088001907000,"d"],
           ["2017-12-24 13\\:00+0900:product",1514088004,1514088001907000,"d"],
           ["2017-12-24 13\\:00+0900:spec",1514088004,1514088001907000,"d"],
           ["2017-12-24 13\\:00+0900:st",1514088004,1514088001907000,"d"],
           ["2017-12-24 13\\:00+0900:vl",1514088004,1514088001907000,"d"],
           ["2017-12-24 13\\:00+0900:",1514088003,1514088002909000,"d"],

this is sample data result by sstablemetadata : 

SSTable: ./table-ka-63967
Partitioner: org.apache.cassandra.dht.Murmur3Partitioner
Bloom Filter FP chance: 0.010000
Minimum timestamp: 1514025606249000
Maximum timestamp: 1514220828254000
SSTable max local deletion time: 1516899228

 

we checked /var/log/messages and found some of expired sstables are removed by compaction.

expired sstable compaction log(2days, 2018 2/21 ~ 2/22) : 

Feb 22 11:46:50 swfosldb03 scylla: [shard 1] compaction - Compacted 1 sstables to []. 418249557 bytes to 0 (~0% of original) in 3718ms = 0MB/s. ~100 total partitions merged to 0.
Feb 22 10:31:09 swfosldb03 scylla: [shard 6] compaction - Compacted 1 sstables to []. 336840105 bytes to 0 (~0% of original) in 3055ms = 0MB/s. ~97 total partitions merged to 0.
Feb 22 10:27:56 swfosldb03 scylla: [shard 0] compaction - Compacted 1 sstables to []. 338937801 bytes to 0 (~0% of original) in 2973ms = 0MB/s. ~93 total partitions merged to 0.
Feb 22 03:11:21 swfosldb03 scylla: [shard 6] compaction - Compacted 1 sstables to []. 606890539 bytes to 0 (~0% of original) in 5198ms = 0MB/s. ~174 total partitions merged to 0.
Feb 22 02:47:22 swfosldb03 scylla: [shard 7] compaction - Compacted 1 sstables to []. 567792580 bytes to 0 (~0% of original) in 4829ms = 0MB/s. ~157 total partitions merged to 0.
Feb 22 02:32:34 swfosldb03 scylla: [shard 1] compaction - Compacted 1 sstables to []. 594555877 bytes to 0 (~0% of original) in 5251ms = 0MB/s. ~181 total partitions merged to 0.
Feb 22 02:19:32 swfosldb03 scylla: [shard 2] compaction - Compacted 1 sstables to []. 678557112 bytes to 0 (~0% of original) in 5761ms = 0MB/s. ~176 total partitions merged to 0.
Feb 22 01:45:45 swfosldb03 scylla: [shard 4] compaction - Compacted 1 sstables to []. 680704946 bytes to 0 (~0% of original) in 5719ms = 0MB/s. ~192 total partitions merged to 0.

Feb 21 17:28:10 swfosldb03 scylla: [shard 0] compaction - Compacted 1 sstables to []. 93503271 bytes to 0 (~0% of original) in 1182ms = 0MB/s. ~13 total partitions merged to 0.
Feb 21 15:49:27 swfosldb03 scylla: [shard 7] compaction - Compacted 1 sstables to []. 128414165 bytes to 0 (~0% of original) in 1658ms = 0MB/s. ~16 total partitions merged to 0.
Feb 21 03:20:10 swfosldb03 scylla: [shard 2] compaction - Compacted 1 sstables to []. 422974127 bytes to 0 (~0% of original) in 3775ms = 0MB/s. ~204 total partitions merged to 0.
Feb 21 03:06:58 swfosldb03 scylla: [shard 3] compaction - Compacted 1 sstables to []. 253745066 bytes to 0 (~0% of original) in 2345ms = 0MB/s. ~161 total partitions merged to 0.
Feb 21 02:45:47 swfosldb03 scylla: [shard 1] compaction - Compacted 1 sstables to []. 363398779 bytes to 0 (~0% of original) in 3246ms = 0MB/s. ~167 total partitions merged to 0.

 

but 1T expired sstables were not compacted any more and remained in filesystem.
expired files time range is between 2017 july and 2017 dec.
below is git link about same issue last april. 

https://github.com/scylladb/scylla/issues/2253
we updated scylladb from 1,6v to 1.7v because same issue,
but some of old sstables are remain again.

 

we want to find a way to remove old expired sstables without affects to System, so we need support about this issue .
attached table script and cfstats, grafana info.

table script : 

CREATE TABLE foms.table (
    part_key text,
    param_index bigint,
    ts timestamp,
    lt text,
    product frozen<udt1>,
    spec frozen<udt2>,
    st text,
    vl text,
    PRIMARY KEY ((part_key, param_index), ts)
) WITH CLUSTERING ORDER BY (ts ASC)
    AND bloom_filter_fp_chance = 0.01
    AND caching = '{"keys":"ALL","rows_per_partition":"ALL"}'
    AND comment = ''
    AND compaction = {'class': 'DateTieredCompactionStrategy', 'base_time_seconds': '7200', 'max_sstable_age_days':'2'}
    AND compression = {'chunk_length_kb': '64', 'sstable_compression': 'org.apache.cassandra.io.compress.LZ4Compressor'}
    AND dclocal_read_repair_chance = 0.1
    AND default_time_to_live = 2678400
    AND gc_grace_seconds = 0
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 1
    AND read_repair_chance = 0.0
    AND speculative_retry = '99.0PERCENTILE';

current cfstats result : 

Table: table
SSTable count: 1621
SSTables in each level: [1621/4]
Space used (live): 1592633189040
Space used (total): 1592633189040
Space used by snapshots (total): 57764507
Off heap memory used (total): 1288367972
SSTable Compression Ratio: 0.2247
Number of keys (estimate): 8065417
Memtable cell count: 2774
Memtable data size: 1200774049
Memtable off heap memory used: 1285292032
Memtable switch count: 8
Local read count: 330687823
Local read latency: 0.442 ms
Local write count: 10634935357
Local write latency: 0.008 ms
Pending flushes: 0
Bloom filter false positives: 212384354
Bloom filter false ratio: 1597.63000
Bloom filter space used: 0
Bloom filter off heap memory used: 1048672
Index summary off heap memory used: 2027268
Compression metadata off heap memory used: 0
Compacted partition minimum bytes: 216
Compacted partition maximum bytes: 4866323
Compacted partition mean bytes: 959936
Average live cells per slice (last five minutes): 0.0
Maximum live cells per slice (last five minutes): 0
Average tombstones per slice (last five minutes): 0.0
Maximum tombstones per slice (last five minutes): 0

**Comment by raphaelsc** [comment] 2018-02-26 19:26
We need to backport 0d21129cc70b659b4e5aa3bd675e95ec35f201f9 and a few other patches I think. @slivne: Are we still supporting 1.7.1? If not, I'd recommend @ban4785 to upgrade to 2.1.

**Comment by glommer** [comment] 2018-02-26 19:33
The 1.7 series is not supported anymore.

**Comment by tzach** [comment] 2018-03-01 08:32
Closing this as open source 1.7 is not supported, and the problem is fix in later releases.
@ban4785 please carefully read http://docs.scylladb.com/upgrade/upgrade-guide-from-1.7-to-2.0-rpm/ before upgrading. In particular, you need to upgrade to 1.7.5 first, then upgrade to 2.0, then 2.1

**Closed by tzach** 2018-03-01 08:32 UTC
