### ISSUE TITLE
Scylla4.3 rolling upgrade failed - Could not retrieve CDC streams with timestamp {2020/12/17 20:57:28} upon gossip event. Reason: "std::runtime_error"

### ISSUE THREAD

**Issue by Orenef11** [scylladb/scylla#7817] opened 2020-12-20 19:09 UTC
## Details
Curent Scylla version: `4.2`
Upgrade Scylla version: `4.3rc3`
JOB: https://jenkins.scylladb.com/job/scylla-4.3/job/rolling-upgrade/job/rolling-upgrade-ubuntu16.04-test/16/consoleFull

## Logs:
* **prometheus** - https://cloudius-jenkins-test.s3.amazonaws.com/7c38b6da-cc79-47e1-942b-5211650a3d1f/prometheus_snapshot_20201218_000019.tar.gz
* **grafana** - https://cloudius-jenkins-test.s3.amazonaws.com/7c38b6da-cc79-47e1-942b-5211650a3d1f/20201217_234941/grafana-screenshot-overview-20201217_234942-rolling-upgrade-4-3-ubuntu-xenial-monitor-node-7c38b6da-0-1.png
* **grafana** - https://cloudius-jenkins-test.s3.amazonaws.com/7c38b6da-cc79-47e1-942b-5211650a3d1f/20201217_234941/grafana-screenshot-scylla-per-server-metrics-nemesis-20201217_235359-rolling-upgrade-4-3-ubuntu-xenial-monitor-node-7c38b6da-0-1.png
* **grafana** - https://cloudius-jenkins-test.s3.amazonaws.com/7c38b6da-cc79-47e1-942b-5211650a3d1f/20201218_000033/grafana-screenshot-overview-20201218_000034-rolling-upgrade-4-3-ubuntu-xenial-monitor-node-7c38b6da-0-1.png
* **grafana** - https://cloudius-jenkins-test.s3.amazonaws.com/7c38b6da-cc79-47e1-942b-5211650a3d1f/20201218_000033/grafana-screenshot-scylla-per-server-metrics-nemesis-20201218_000359-rolling-upgrade-4-3-ubuntu-xenial-monitor-node-7c38b6da-0-1.png
* **db-cluster** - https://cloudius-jenkins-test.s3.amazonaws.com/7c38b6da-cc79-47e1-942b-5211650a3d1f/20201218_001302/db-cluster-7c38b6da.zip
* **loader-set** - https://cloudius-jenkins-test.s3.amazonaws.com/7c38b6da-cc79-47e1-942b-5211650a3d1f/20201218_001302/loader-set-7c38b6da.zip
* **monitor-set** - https://cloudius-jenkins-test.s3.amazonaws.com/7c38b6da-cc79-47e1-942b-5211650a3d1f/20201218_001302/monitor-set-7c38b6da.zip
* **sct-runner** - https://cloudius-jenkins-test.s3.amazonaws.com/7c38b6da-cc79-47e1-942b-5211650a3d1f/20201218_001302/sct-runner-7c38b6da.zip

Two comments:
1. Maybe this [bug](https://github.com/scylladb/scylla/issues/7610) is related?
2. All rolling upgrade JOBs are failed because of this error.
[rolling-upgrade-centos7](https://jenkins.scylladb.com/view/scylla-4.3/job/scylla-4.3/job/rolling-upgrade/job/rolling-upgrade-centos7-test/31/execution/node/38/log/) (test id `44556cb8-8450-4312-b805-523021625442`)
[rolling-upgrade-centos8](https://jenkins.scylladb.com/job/scylla-4.3/job/rolling-upgrade/job/rolling-upgrade-centos8-test/32/execution/node/38/log/)  (test id `4d0f3161-5035-49cb-aba0-e8e002baf470`)
[rolling-upgrade-debian10](https://jenkins.scylladb.com/job/scylla-4.3/job/rolling-upgrade/job/rolling-upgrade-debian10-test/15/execution/node/38/log/)  (test id `1d525cc9-b63f-4f1b-8518-efbbb34b8446`)
[rolling-upgrade-ubuntu16.04](https://jenkins.scylladb.com/view/scylla-4.3/job/scylla-4.3/job/rolling-upgrade/job/rolling-upgrade-ubuntu16.04-test/16/execution/node/38/log/)  (test id `7c38b6da-cc79-47e1-942b-5211650a3d1f`)
[rolling-upgrade-ubuntu18.04](https://jenkins.scylladb.com/view/scylla-4.3/job/scylla-4.3/job/rolling-upgrade/job/rolling-upgrade-ubuntu18.04-test/14/execution/node/38/log/)  (test id `b5fb7c37-eb13-452c-8534-b3d8b5d6a601`)

**Comment by slivne** [comment] 2020-12-20 20:12
@Orenef11 CDC is incompatible between the releases - we do not support upgrades from 4.2 --> 4.3 retaining CDC (@haaawk / @avikivity - corretc me if I'm wrong).

@tzach how do you want to handle this case - user using CDC in 4.2 trying to upgrade to 4.3 ? - simply comment in the installation / release notes.

**Comment by Orenef11** [comment] 2020-12-20 20:41
> @Orenef11 CDC is incompatible between the releases - we do not support upgrades from 4.2 --> 4.3 retaining CDC (@haaawk / @avikivity - corretc me if I'm wrong).
> 
> @tzach how do you want to handle this case - user using CDC in 4.2 trying to upgrade to 4.3 ? - simply comment in the installation / release notes.

All upgrades until 17.12, from `4.2` to `4.3` (`RC1` and `RC2`) have passed (Those who failed, did not fail because of this problem).
Has there been a big change in the CDC in the last week?

**Comment by slivne** [comment] 2020-12-20 21:13
@Orenef11 thanks

@kbr- please check - I can't find anything that would cause 4.3.rc2...4.3.rc3 to regress in supporting non supporting this.

4.3 made cdc enabled by default so maybe this change caused this somehow ?

**Comment by kbr-** [comment] 2020-12-21 12:57
The cluster was initially started with experimental enabled (before upgrade):
```
Dec 17 20:55:19 rolling-upgrade-4-3-ubuntu-xenial-db-node-7c38b6da-0-4 scylla[25300]:  [shard 0] init - Scylla version 4.2.2-0.20201213.696ef24226 with build-id e82d9155c2a9f57c71b5de5575f2ae89e411863a starting ...
...
Dec 17 20:55:30 rolling-upgrade-4-3-ubuntu-xenial-db-node-7c38b6da-0-4 scylla[25300]:  [shard 0] gossip - Feature check passed. Local node 10.142.0.115 features = {CDC, COMPUTED_COLUMNS, CORRECT_COUNTER_ORDER, CORRECT_NON_COMPOUND_RANGE_TOMBSTONES,
...
Dec 17 20:55:44 rolling-upgrade-4-3-ubuntu-xenial-db-node-7c38b6da-0-4 scylla[25300]:  [shard 0] features - Feature CDC is enabled
```

Each node creates a CDC generation and inserts it to the `system_distributed.cdc_generations` table, because CDC is enabled.
```
Dec 17 20:57:02 rolling-upgrade-4-3-ubuntu-xenial-db-node-7c38b6da-0-4 scylla[25300]:  [shard 0] cdc - Latest generation seen during startup: 2020/12/17 20:57:28
```

This table's name was changed in 4.3, now it's named `system_distributed.cdc_generation_descriptions`.
The upgraded nodes try to read the CDC generation from the new table, but it's in the old table, hence the error (`Could not retrieve CDC streams...`).

This is **expected** when you upgrade from experimental 4.2 to 4.3. It's not a bug.

Note that the only reason the jobs failed was that the nodes reported an "ERROR" level log message. It doesn't mean that the cluster won't work. It will, but CDC won't be available until you run `nodetool checkAndRepairCdcStreams` (expected). 

Possible "fixes":
1. ignore the error
2. upgrade from 4.2 with experimental disabled

I wonder why the `rc1` and `rc2` tests were executed with experimental disabled, and now we're going with experimental enabled.

**Comment by Orenef11** [comment] 2020-12-21 13:11
@kbr- 
Thank you so much for the detailed answer!
I will check which of the offers is an offer we would like to use.

@fruch 
What do you think?

**Comment by fruch** [comment] 2020-12-21 13:25
> I wonder why the `rc1` and `rc2` tests were executed with experimental disabled, and now we're going with experimental enabled.

experimental was enabled all along, you can see the long of the last working job: 
https://jenkins.scylladb.com/view/scylla-4.3/job/scylla-4.3/job/rolling-upgrade/job/rolling-upgrade-centos7-test/28

**Comment by kbr-** [comment] 2020-12-21 13:30
Ok. Indeed it was, and you can see the same error:
```
Dec 13 12:50:47 rolling-upgrade-4-3-centos-db-node-7b006b68-0-4 scylla[3972]:  [shard 0] cdc - Could not retrieve CDC streams with timestamp {2020/12/13 11:20:58} upon gossip event. Reason: "std::runtime_error (Could not find CDC generation with timestamp 2020/12/13 11:20:58 in distributed system tables (current time: 2020/12/13 12:50:47), even though some node gossiped about it.)". Action: not retrying.
```
but the job passed, so looks like we ignored the error.

Maybe a recent change in SCT started looking for `runtime_error` inside nodes' logs:
```
22:48:11  < t:2020-12-17 21:47:57,830 f:sct_events.py   l:976  c:sdcm.sct_events      p:INFO  > 2020-12-17 21:47:53.000: (DatabaseLogEvent Severity.ERROR): type=RUNTIME_ERROR regex=std::runtime_error line_number=13100 node=Node rolling-upgrade-4-3-ubuntu-xenial-db-node-7c38b6da-0-3 [34.74.19.46 | 10.142.0.109] (seed: False)
```

**Comment by kbr-** [comment] 2020-12-21 13:34
Maybe
```
commit bc31fae56db2f28ca14b579ba86641c780a4d38f
Author: Evgeniy Naydanov <evgeniy.naydanov@scylladb.com>
Date:   Mon Nov 2 18:27:53 2020 +0000

    improvement(sct_events): rework database events
```

**Comment by fruch** [comment] 2020-12-21 13:39
> Maybe
> 
> ```
> commit bc31fae56db2f28ca14b579ba86641c780a4d38f
> Author: Evgeniy Naydanov <evgeniy.naydanov@scylladb.com>
> Date:   Mon Nov 2 18:27:53 2020 +0000
> 
>     improvement(sct_events): rework database events
> ```
> 
> but that's quite old

it's merged/backported a week or two ago.
we did had a filter that was probably catching it (wrongly), and this filter might be fixed now.

**Comment by kbr-** [comment] 2020-12-21 13:41
I guess we could also change the exception type from `std::runtime_error` to  a new type (specifically for this error), @slivne what do you think?

**Comment by kbr-** [comment] 2020-12-21 14:00
I talked with Shlomi, `runtime_error` is fine, so I guess we could just modify the upgrade test to configure SCT to ignore the error if it contains "Could not retrieve CDC" - or something like that

**Comment by enaydanov** [comment] 2020-12-21 14:01
It was a bug in SCT (1y old) I fixed it recently in https://github.com/scylladb/scylla-cluster-tests/pull/3003

**Comment by fruch** [comment] 2020-12-21 14:09
So a SCT bug was masking it all along.

@Orenef11 please open have a PR to ignore this error in rolling upgrade tests

**Comment by kbr-** [comment] 2020-12-21 14:17
Also opened issue in scylla-docs for documenting that this is expected:
https://github.com/scylladb/scylla-docs/issues/3291

**Closed** 2020-12-22 08:53 UTC
Labels: CDC, not a bug
