### ISSUE TITLE
query result with secondary index is wrong

### ISSUE THREAD

**Issue by infordb** [scylladb/scylla#3543] opened 2018-06-25 07:10 UTC
*Installation details*
Scylla version (or git commit hash): scylla-server-2.1.1-0.20180325.cce455b1f.el7.centos.x86_64

I  tested basic work of secondary index in Scylla 2.1
There is a strange case in the query result. 
the result data is duplicated  or the query result is wrong.
Refer to the test results below 

####### basic test ##############

CREATE KEYSPACE ks WITH replication = {'class': 'SimpleStrategy', 'replication_factor': '1'}  AND durable_writes = true;

CREATE TABLE ks.idx (
    id int,
    time int, 
    status text,    
    PRIMARY KEY (id, time)
);
CREATE INDEX idx_code ON ks.idx (status);

insert into ks.idx (id,time,status) values(1,11,'1');
insert into ks.idx (id,time,status) values(1,12,'1');
insert into ks.idx (id,time,status) values(2,21,'1');

 
cqlsh:ks> select * from ks.idx;

 id | time | status
----+------+--------
  1 |   11 |      1
  1 |   12 |      1
  2 |   21 |      1

 
cqlsh:ks> SELECT * FROM ks.idx WHERE id = 1 AND time >= 10 and status = '1';

 id | time | status
----+------+--------
  1 |   11 |      1
  1 |   12 |      1
  1 |   11 |      1
  1 |   12 |      1
  2 |   21 |      1

(5 rows)
cqlsh:ks> SELECT * FROM ks.idx WHERE id = 1 AND status = '1';

 id | time | status
----+------+--------
  1 |   11 |      1
  1 |   12 |      1
  1 |   11 |      1
  1 |   12 |      1
  2 |   21 |      1

**Comment by nyh** [comment] 2018-06-25 07:29
The bizarre duplicate rows in the last two searches have already been solved in commit f5536d607ed345dca6013edac3f701aa12c8fee9 which will be in Scylla 2.3. Issue #3405 included a test that confirmed that (and other cases).
However, we still have an open bug - issue #3539 - concerning **intersection** of a secondary-index restriction and another restriction, e.g., on the partition key. This is exactly what you tried to do here. So this is a duplicate of issue #3539.

**Comment by duarten** [comment] 2018-06-25 08:41
Duplicates https://github.com/scylladb/scylla/issues/3539.

**Closed by duarten** 2018-06-25 08:41 UTC
Labels: bug, sec index
