### ISSUE TITLE
nodetool gossipinfo show negative load value

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#687] opened 2015-12-22 10:45 UTC
Testing nodetool gossipinfo with scylla 0.13.2, I get the following
Notice the negative load value
```
127.0.0.1
  generation:1450772353
  heartbeat:572
  STATUS:NORMAL,9108654381581492232
  LOAD:-1.99025e+09
  NET_VERSION:0
  RELEASE_VERSION:2.1.8
  RPC_ADDRESS:127.0.0.1
  RACK:rack1
  DC:datacenter1
  SCHEMA:a622bc53-3f54-3416-bfd2-538086a57eb0
  HOST_ID:37b3d89b-fca2-42b7-a15c-d3237a3f2bcc
```

**Comment by tzach** [comment] 2015-12-22 10:54
The same nodetool command is missing a "SEVERITY" value which exist on Cassandra.
@asias @amnonh do you know whats it stands for?

**Comment by amnonh** [comment] 2015-12-22 11:19
Both values are taken from the get_application_state_map() method in
the endpoint_state
and passed without any formatting.

It seems that there is an integer wrap around for the load.

**Comment by tzach** [comment] 2016-01-11 15:46
@amnonh is this fixed?

**Comment by amnonh** [comment] 2016-01-12 07:04
not tested yet

**Comment by amnonh** [comment] 2016-01-26 08:42
#842 address the SEVERITY issue

**Comment by slivne** [comment] 2016-02-18 01:19
tested on 0.18 does not reproduce

fixed by

commit 0aa105c9cf95fb6310c5f556ebdd5cf2db6ad1b6
Merge: f0b2767 7190508
Author: Pekka Enberg <penberg@scylladb.com>
Date:   Wed Dec 30 10:21:55 2015 +0200

    Merge "load report a negative value" from Amnon
    
    "This series solve an issue with the load broadcaster that reports negative
     values due to an integer wrap around.  While fixing this issue an additional
     change was made so that the load_map would return doubles and not formatted
     string.  This is a better API, safer and better documented."

**Closed by slivne** 2016-02-18 01:19 UTC
Labels: bug, high, nodetool
