### ISSUE TITLE
Not closing file descriptors of sstable files before deletion

### ISSUE THREAD

**Issue by mdevan** [scylladb/scylla#1840] opened 2016-11-14 09:52 UTC
Scylla 1.4.1 on an Ubuntu 16.04, single node with 1 core.

After successfully doing a "nodetool compact" on a keyspace containing one DTCS table and lots of expired-because-of-table-level-TTL rows, I find that the scylla-server process still has the file descriptors open for the sstable files that it deleted during compaction.

The filesystem space is unusable until a restart of scylla-server.

```
$ df -h /var/lib/scylla
Filesystem      Size  Used Avail Use% Mounted on
/dev/sdb1       500G   22G  479G   5% /var/lib/scylla

$ sudo du -sh /var/lib/scylla
8.2G    /var/lib/scylla

$ sudo lsof +L1 /var/lib/scylla | grep deleted
systemd-j  627   root  txt    REG    8,1     326224     0      2742 /lib/systemd/systemd-journald (deleted)
systemd-l 1016   root  txt    REG    8,1     618520     0      2757 /lib/systemd/systemd-logind (deleted)
scylla    4065 scylla   40r   REG   8,17 6855255257     0 268435950 /var/lib/scylla/data/tsdb/datapoints-13933bd0a26d11e6bccc000000000000/tsdb-datapoints-ka-2667-Data.db (deleted)
scylla    4065 scylla   43r   REG   8,17   13756596     0 268435951 /var/lib/scylla/data/tsdb/datapoints-13933bd0a26d11e6bccc000000000000/tsdb-datapoints-ka-2667-Index.db (deleted)
scylla    4065 scylla   45r   REG   8,17 2710911453     0 268435582 /var/lib/scylla/data/tsdb/datapoints-13933bd0a26d11e6bccc000000000000/tsdb-datapoints-ka-3450-Data.db (deleted)
scylla    4065 scylla   47r   REG   8,17    7727313     0 268435591 /var/lib/scylla/data/tsdb/datapoints-13933bd0a26d11e6bccc000000000000/tsdb-datapoints-ka-3450-Index.db (deleted)
scylla    4065 scylla   82r   REG   8,17  387238224     0 268435953 /var/lib/scylla/data/tsdb/datapoints-13933bd0a26d11e6bccc000000000000/tsdb-datapoints-ka-3710-Data.db (deleted)
scylla    4065 scylla   83r   REG   8,17  396146270     0 268435936 /var/lib/scylla/data/tsdb/datapoints-13933bd0a26d11e6bccc000000000000/tsdb-datapoints-ka-3842-Data.db (deleted)
scylla    4065 scylla   87r   REG   8,17     982542     0 268435956 /var/lib/scylla/data/tsdb/datapoints-13933bd0a26d11e6bccc000000000000/tsdb-datapoints-ka-3710-Index.db (deleted)
scylla    4065 scylla   91r   REG   8,17  387069962     0 268435695 /var/lib/scylla/data/tsdb/datapoints-13933bd0a26d11e6bccc000000000000/tsdb-datapoints-ka-3776-Data.db (deleted)
scylla    4065 scylla   93r   REG   8,17  388053217     0 268435964 /var/lib/scylla/data/tsdb/datapoints-13933bd0a26d11e6bccc000000000000/tsdb-datapoints-ka-3907-Data.db (deleted)
scylla    4065 scylla   95r   REG   8,17     982542     0 268435937 /var/lib/scylla/data/tsdb/datapoints-13933bd0a26d11e6bccc000000000000/tsdb-datapoints-ka-3842-Index.db (deleted)
scylla    4065 scylla   99r   REG   8,17     982542     0 268435696 /var/lib/scylla/data/tsdb/datapoints-13933bd0a26d11e6bccc000000000000/tsdb-datapoints-ka-3776-Index.db (deleted)
scylla    4065 scylla  103r   REG   8,17     982542     0 268435965 /var/lib/scylla/data/tsdb/datapoints-13933bd0a26d11e6bccc000000000000/tsdb-datapoints-ka-3907-Index.db (deleted)
scylla    4065 scylla  104r   REG   8,17 1547884394     0 268435583 /var/lib/scylla/data/tsdb/datapoints-13933bd0a26d11e6bccc000000000000/tsdb-datapoints-ka-3711-Data.db (deleted)
scylla    4065 scylla  105r   REG   8,17 1547034503     0 268435586 /var/lib/scylla/data/tsdb/datapoints-13933bd0a26d11e6bccc000000000000/tsdb-datapoints-ka-3449-Data.db (deleted)
scylla    4065 scylla  106r   REG   8,17    5715336     0 268435590 /var/lib/scylla/data/tsdb/datapoints-13933bd0a26d11e6bccc000000000000/tsdb-datapoints-ka-3449-Index.db (deleted)
scylla    4065 scylla  107r   REG   8,17    5715336     0 268435584 /var/lib/scylla/data/tsdb/datapoints-13933bd0a26d11e6bccc000000000000/tsdb-datapoints-ka-3711-Index.db (deleted)
```

**Comment by raphaelsc** [comment] 2016-11-15 04:58
On Mon, Nov 14, 2016 at 10:16 AM, Shlomi Livne <notifications@github.com>
wrote:

> Assigned #1840 <https://github.com/scylladb/scylla/issues/1840> to
> @raphaelsc <https://github.com/raphaelsc>.
>
It's probably due to compaction holding reference for all uncompacting
sstables until done. A fix would be to explicitly close deleted sstables
which are no longer in the sstable set, even though their object are still
alive. @avikivity?

**Comment by slivne** [comment] 2016-11-15 10:28
I was able to reproduce this on a single node with size tiered (so its not related to DTCS)

There are no compactions running - we have a bug we need to find out why we are not closing the file handles

To reproduce
  1. ccm create scylla-1 --scylla --vnodes -n 1 --install-dir=
  1. ccm start
  1. ccm node1 stress write n=100000 -col "size=FIXED(1024) n=FIXED(5)" -rate threads=2
  1. ccm node1 nodetool compact
  1. wait for it to end 
  1.  ccm node1 nodetool compactionstats
  1.  lsof | grep keyspace

```
shlomi@localhost~/.ccm/scylla-1/node1/data/keyspace1/standard1-557cfca0ab1b11e693fc000000000000$ lsof | grep keyspace
lsof: WARNING: can't stat() fuse.gvfsd-fuse file system /run/user/42/gvfs
      Output information may be incomplete.
bash      3539       shlomi  cwd       DIR              253,2     20480    4064978 /home/shlomi/.ccm/scylla-1/node1/data/keyspace1/standard1-557cfca0ab1b11e693fc000000000000
scylla    7675       shlomi    8r      REG              253,2  99608702    4064632 /home/shlomi/.ccm/scylla-1/node1/data/keyspace1/standard1-557cfca0ab1b11e693fc000000000000/keyspace1-standard1-ka-69-Data.db (deleted)
scylla    7675       shlomi    9r      REG              253,2 931102307    4064493 /home/shlomi/.ccm/scylla-1/node1/data/keyspace1/standard1-557cfca0ab1b11e693fc000000000000/keyspace1-standard1-ka-86-Data.db
scylla    7675       shlomi   13r      REG              253,2   4271928    4064631 /home/shlomi/.ccm/scylla-1/node1/data/keyspace1/standard1-557cfca0ab1b11e693fc000000000000/keyspace1-standard1-ka-86-Index.db
scylla    7675       shlomi   16r      REG              253,2  99619164    4064982 /home/shlomi/.ccm/scylla-1/node1/data/keyspace1/standard1-557cfca0ab1b11e693fc000000000000/keyspace1-standard1-ka-9-Data.db (deleted)
scylla    7675       shlomi   23r      REG              253,2 408195854    4064883 /home/shlomi/.ccm/scylla-1/node1/data/keyspace1/standard1-557cfca0ab1b11e693fc000000000000/keyspace1-standard1-ka-81-Data.db
scylla    7675       shlomi   27r      REG              253,2   1872816    4064888 /home/shlomi/.ccm/scylla-1/node1/data/keyspace1/standard1-557cfca0ab1b11e693fc000000000000/keyspace1-standard1-ka-81-Index.db
scylla    7675       shlomi   28r      REG              253,2       528    4064887 /home/shlomi/.ccm/scylla-1/node1/data/system/schema_keyspaces-b0f2235744583cdb9631c43e59ce3676/system-schema_keyspaces-ka-8-Data.db
scylla    7675       shlomi   29r      REG              253,2        70    4064896 /home/shlomi/.ccm/scylla-1/node1/data/system/schema_keyspaces-b0f2235744583cdb9631c43e59ce3676/system-schema_keyspaces-ka-8-Index.db
scylla    7675       shlomi   30r      REG              253,2 224101271    4064488 /home/shlomi/.ccm/scylla-1/node1/data/keyspace1/standard1-557cfca0ab1b11e693fc000000000000/keyspace1-standard1-ka-85-Data.db (deleted)
scylla    7675       shlomi   38r      REG              253,2   1028184    4064496 /home/shlomi/.ccm/scylla-1/node1/data/keyspace1/standard1-557cfca0ab1b11e693fc000000000000/keyspace1-standard1-ka-85-Index.db (deleted)
scylla    7675       shlomi   42r      REG              253,2    457008    4064889 /home/shlomi/.ccm/scylla-1/node1/data/keyspace1/standard1-557cfca0ab1b11e693fc000000000000/keyspace1-standard1-ka-69-Index.db (deleted)
scylla    7675       shlomi   74r      REG              253,2    457056    4064983 /home/shlomi/.ccm/scylla-1/node1/data/keyspace1/standard1-557cfca0ab1b11e693fc000000000000/keyspace1-standard1-ka-9-Index.db (deleted)
scylla    7675       shlomi   77r      REG              253,2 199196480    4077003 /home/shlomi/.ccm/scylla-1/node1/data/keyspace1/standard1-557cfca0ab1b11e693fc000000000000/keyspace1-standard1-ka-76-Data.db (deleted)
scylla    7675       shlomi   88r      REG              253,2    913920    4077005 /home/shlomi/.ccm/scylla-1/node1/data/keyspace1/standard1-557cfca0ab1b11e693fc000000000000/keyspace1-standard1-ka-76-Index.db (deleted)
scylla    7675       shlomi  115r      REG              253,2  99472696    4064972 /home/shlomi/.ccm/scylla-1/node1/data/keyspace1/standard1-557cfca0ab1b11e693fc000000000000/keyspace1-standard1-ka-35-Data.db (deleted)
scylla    7675       shlomi  116r      REG              253,2    456384    4064981 /home/shlomi/.ccm/scylla-1/node1/data/keyspace1/standard1-557cfca0ab1b11e693fc000000000000/keyspace1-standard1-ka-35-Index.db (deleted)
scylla    7675 7679  shlomi    8r      REG              253,2  99608702    4064632 /home/shlomi/.ccm/scylla-1/node1/data/keyspace1/standard1-557cfca0ab1b11e693fc000000000000/keyspace1-standard1-ka-69-Data.db (deleted)
scylla    7675 7679  shlomi    9r      REG              253,2 931102307    4064493 /home/shlomi/.ccm/scylla-1/node1/data/keyspace1/standard1-557cfca0ab1b11e693fc000000000000/keyspace1-standard1-ka-86-Data.db
scylla    7675 7679  shlomi   13r      REG              253,2   4271928    4064631 /home/shlomi/.ccm/scylla-1/node1/data/keyspace1/standard1-557cfca0ab1b11e693fc000000000000/keyspace1-standard1-ka-86-Index.db
scylla    7675 7679  shlomi   16r      REG              253,2  99619164    4064982 /home/shlomi/.ccm/scylla-1/node1/data/keyspace1/standard1-557cfca0ab1b11e693fc000000000000/keyspace1-standard1-ka-9-Data.db (deleted)
scylla    7675 7679  shlomi   23r      REG              253,2 408195854    4064883 /home/shlomi/.ccm/scylla-1/node1/data/keyspace1/standard1-557cfca0ab1b11e693fc000000000000/keyspace1-standard1-ka-81-Data.db
scylla    7675 7679  shlomi   27r      REG              253,2   1872816    4064888 /home/shlomi/.ccm/scylla-1/node1/data/keyspace1/standard1-557cfca0ab1b11e693fc000000000000/keyspace1-standard1-ka-81-Index.db
scylla    7675 7679  shlomi   28r      REG              253,2       528    4064887 /home/shlomi/.ccm/scylla-1/node1/data/system/schema_keyspaces-b0f2235744583cdb9631c43e59ce3676/system-schema_keyspaces-ka-8-Data.db
scylla    7675 7679  shlomi   29r      REG              253,2        70    4064896 /home/shlomi/.ccm/scylla-1/node1/data/system/schema_keyspaces-b0f2235744583cdb9631c43e59ce3676/system-schema_keyspaces-ka-8-Index.db
scylla    7675 7679  shlomi   30r      REG              253,2 224101271    4064488 /home/shlomi/.ccm/scylla-1/node1/data/keyspace1/standard1-557cfca0ab1b11e693fc000000000000/keyspace1-standard1-ka-85-Data.db (deleted)
scylla    7675 7679  shlomi   38r      REG              253,2   1028184    4064496 /home/shlomi/.ccm/scylla-1/node1/data/keyspace1/standard1-557cfca0ab1b11e693fc000000000000/keyspace1-standard1-ka-85-Index.db (deleted)
scylla    7675 7679  shlomi   42r      REG              253,2    457008    4064889 /home/shlomi/.ccm/scylla-1/node1/data/keyspace1/standard1-557cfca0ab1b11e693fc000000000000/keyspace1-standard1-ka-69-Index.db (deleted)
scylla    7675 7679  shlomi   74r      REG              253,2    457056    4064983 /home/shlomi/.ccm/scylla-1/node1/data/keyspace1/standard1-557cfca0ab1b11e693fc000000000000/keyspace1-standard1-ka-9-Index.db (deleted)
scylla    7675 7679  shlomi   77r      REG              253,2 199196480    4077003 /home/shlomi/.ccm/scylla-1/node1/data/keyspace1/standard1-557cfca0ab1b11e693fc000000000000/keyspace1-standard1-ka-76-Data.db (deleted)
scylla    7675 7679  shlomi   88r      REG              253,2    913920    4077005 /home/shlomi/.ccm/scylla-1/node1/data/keyspace1/standard1-557cfca0ab1b11e693fc000000000000/keyspace1-standard1-ka-76-Index.db (deleted)
scylla    7675 7679  shlomi  115r      REG              253,2  99472696    4064972 /home/shlomi/.ccm/scylla-1/node1/data/keyspace1/standard1-557cfca0ab1b11e693fc000000000000/keyspace1-standard1-ka-35-Data.db (deleted)
scylla    7675 7679  shlomi  116r      REG              253,2    456384    4064981 /home/shlomi/.ccm/scylla-1/node1/data/keyspace1/standard1-557cfca0ab1b11e693fc000000000000/keyspace1-standard1-ka-35-Index.db (deleted)
lsof      8527       shlomi  cwd       DIR              253,2     20480    4064978 /home/shlomi/.ccm/scylla-1/node1/data/keyspace1/standard1-557cfca0ab1b11e693fc000000000000
grep      8528       shlomi  cwd       DIR              253,2     20480    4064978 /home/shlomi/.ccm/scylla-1/node1/data/keyspace1/standard1-557cfca0ab1b11e693fc000000000000
lsof      8529       shlomi  cwd       DIR              253,2     20480    4064978 /home/shlomi/.ccm/scylla-1/node1/data/keyspace1/standard1-557cfca0ab1b11e693fc000000000000
```

if I check the logs for some files "ka-35" I can see that it was compacted

```
shlomi@localhost~/.ccm/scylla-1/node1/data/keyspace1/standard1-557cfca0ab1b11e693fc000000000000$ grep "ka-35" ~/.ccm/scylla-1/node1/logs/system.log
INFO  2016-11-15 12:09:47,590 [shard 0] compaction - Compacted 4 sstables to [/home/shlomi/.ccm/scylla-1/node1/data/keyspace1/standard1-557cfca0ab1b11e693fc000000000000/keyspace1-standard1-ka-35-Data.db:level=0, ]. 99472696 bytes to 99472696 (~100% of original) in 25277ms = 3.753MB/s. ~19840 total partitions merged to 19016.
INFO  2016-11-15 12:12:57,846 [shard 0] compaction - Compacting [/home/shlomi/.ccm/scylla-1/node1/data/keyspace1/standard1-557cfca0ab1b11e693fc000000000000/keyspace1-standard1-ka-9-Data.db:level=0, /home/shlomi/.ccm/scylla-1/node1/data/keyspace1/standard1-557cfca0ab1b11e693fc000000000000/keyspace1-standard1-ka-18-Data.db:level=0, /home/shlomi/.ccm/scylla-1/node1/data/keyspace1/standard1-557cfca0ab1b11e693fc000000000000/keyspace1-standard1-ka-29-Data.db:level=0, /home/shlomi/.ccm/scylla-1/node1/data/keyspace1/standard1-557cfca0ab1b11e693fc000000000000/keyspace1-standard1-ka-35-Data.db:level=0, /home/shlomi/.ccm/scylla-1/node1/data/keyspace1/standard1-557cfca0ab1b11e693fc000000000000/keyspace1-standard1-ka-40-Data.db:level=0, /home/shlomi/.ccm/scylla-1/node1/data/keyspace1/standard1-557cfca0ab1b11e693fc000000000000/keyspace1-standard1-ka-52-Data.db:level=0, /home/shlomi/.ccm/scylla-1/node1/data/keyspace1/standard1-557cfca0ab1b11e693fc000000000000/keyspace1-standard1-ka-62-Data.db:level=0, /home/shlomi/.ccm/scylla-1/node1/data/keyspace1/standard1-557cfca0ab1b11e693fc000000000000/keyspace1-standard1-ka-69-Data.db:level=0, /home/shlomi/.ccm/scylla-1/node1/data/keyspace1/standard1-557cfca0ab1b11e693fc000000000000/keyspace1-standard1-ka-76-Data.db:level=0, /home/shlomi/.ccm/scylla-1/node1/data/keyspace1/standard1-557cfca0ab1b11e693fc000000000000/keyspace1-standard1-ka-85-Data.db:level=0, ]
```

the full log is attached
[system.log.txt](https://github.com/scylladb/scylla/files/591643/system.log.txt)


```
shlomi@localhost~/.ccm/scylla-1/node1/data/keyspace1/standard1-557cfca0ab1b11e693fc000000000000$ ls -lstra
total 1314816
     4 drwx------ 2 shlomi shlomi      4096 Nov 15 12:07 upload
     4 drwx------ 3 shlomi shlomi      4096 Nov 15 12:07 ..
     4 -rw-r--r-- 1 shlomi shlomi        79 Nov 15 12:12 keyspace1-standard1-ka-81-TOC.txt
     4 -rw-r--r-- 1 shlomi shlomi        79 Nov 15 12:12 keyspace1-standard1-ka-86-TOC.txt
  1832 -rw-r--r-- 1 shlomi shlomi   1872816 Nov 15 12:13 keyspace1-standard1-ka-81-Index.db
398636 -rw-r--r-- 1 shlomi shlomi 408195854 Nov 15 12:13 keyspace1-standard1-ka-81-Data.db
     4 -rw-r--r-- 1 shlomi shlomi         9 Nov 15 12:13 keyspace1-standard1-ka-81-Digest.sha1
    28 -rw-r--r-- 1 shlomi shlomi     24920 Nov 15 12:13 keyspace1-standard1-ka-81-CRC.db
    16 -rw-r--r-- 1 shlomi shlomi     13472 Nov 15 12:13 keyspace1-standard1-ka-81-Summary.db
   264 -rw-r--r-- 1 shlomi shlomi    268976 Nov 15 12:13 keyspace1-standard1-ka-81-Filter.db
     8 -rw-r--r-- 1 shlomi shlomi      4466 Nov 15 12:13 keyspace1-standard1-ka-81-Statistics.db
  4172 -rw-r--r-- 1 shlomi shlomi   4271928 Nov 15 12:14 keyspace1-standard1-ka-86-Index.db
909284 -rw-r--r-- 1 shlomi shlomi 931102307 Nov 15 12:14 keyspace1-standard1-ka-86-Data.db
     4 -rw-r--r-- 1 shlomi shlomi        10 Nov 15 12:14 keyspace1-standard1-ka-86-Digest.sha1
    56 -rw-r--r-- 1 shlomi shlomi     56836 Nov 15 12:14 keyspace1-standard1-ka-86-CRC.db
    32 -rw-r--r-- 1 shlomi shlomi     30654 Nov 15 12:14 keyspace1-standard1-ka-86-Summary.db
   436 -rw-r--r-- 1 shlomi shlomi    442576 Nov 15 12:14 keyspace1-standard1-ka-86-Filter.db
     8 -rw-r--r-- 1 shlomi shlomi      4486 Nov 15 12:14 keyspace1-standard1-ka-86-Statistics.db
    20 drwx------ 3 shlomi shlomi     20480 Nov 15 12:14 .
```

**Comment by slivne** [comment] 2016-11-15 10:36
please note that nodetool compact is also not providing the expected outcome it should be a single sstable and I ended up with two -

could it be that nodetool compact should wait/abort on going compactions and then start running - it seems that I had more then one compaction running and as of that some files were not included in the "larger" set that nodetool compact executed.

**Comment by mdevan** [comment] 2016-11-15 13:47
`compact_sstables()` creates a `compacting_sstable_writer` object, which in turn creates a `sstable_writer` object whose constructor calls `sstable::create_data()`. This method opens the Index and Data files. Are they cleaned up anywhere?

(Just reading the code, couldn't try it out, sorry.)

**Comment by raphaelsc** [comment] 2016-11-15 16:27
@mdevan, yes, when the sstable object gets destroyed.

**Comment by raphaelsc** [comment] 2016-11-15 21:54
My theory is:
1) column family has 10 sstables
2) regular compaction runs for sstables 0-3
3) major compaction runs in parallel, and it will hold a reference for all sstables, i.e. 0-9.
4) regular compaction finishes and deletes sstables 0-3

look that major compaction holds reference for sstables 0-3, and therefore, their index and data files cannot be closed. I think we need to fix major compaction. It needs to go through compaction manager and that's discussed here https://github.com/scylladb/scylla/issues/1156

**Comment by raphaelsc** [comment] 2016-11-15 21:58
I came up with this theory because '/data/scylla_data2/data/keyspace1/standard1-c453eb60ab7b11e69d64000000000000/keyspace1-standard1-ka-7-Index.db (deleted)' disappeared after major compaction completed.

I think we may have the same problem when running more than one regular compaction in parallel. As I said, regular compaction holds reference for *all* sstables not being compacted. That's for calculation of max purgeable timestamp.

**Comment by raphaelsc** [comment] 2016-11-15 22:22
Confirmed my theory:

Regular compaction is running,  no lsof entry with (deleted).
Major compaction starts, and no lsof entry with (deleted).
Regular compaction finishes, there are lsof entries with (deleted). The entries match sstables compacted by regular compaction.
Major compaction finishes, and again no lsof entry with (deleted).

I'll cook a patch to make major compaction go through compaction manager, and we'll also need a patch for compaction to leak reference of sstables compacted in parallel. That can be done by refreshing uncompacted sstables.

**Comment by slivne** [comment] 2016-11-16 09:16
Raphael - please note that at least in my case I verified that major
compaction ended and there was no other compaction running and I had file
handles held for deleted sstables.

So at least in my run this
*Major compaction finishes, and again no lsof entry with (deleted).*

did not hold

even after major compaction ended file handles of deleted files were held.


Please note that if we are moving majot compaction to the compaction
manager - we may need to aboort/stop ongoing compactions to make sure that
the major compaction starts running.


On Wed, Nov 16, 2016 at 12:22 AM, Raphael Carvalho <notifications@github.com

**Comment by raphaelsc** [comment] 2016-11-16 13:40
"Raphael - please note that at least in my case I verified that major
compaction ended and there was no other compaction running and I had file
handles held for deleted sstables."

how did you verify it? as major compaction doesn't go through compaction manager, we currently cannot see it via 'nodetool compactionstats'
It's odd that we cannot easily differentiate major compaction from regular compaction in the log. There's an issue for that.

**Comment by slivne** [comment] 2016-11-16 13:42
I assumed I could see it in the counters / in the logs.

e.g. I had a log of a compaction starting with many sstables and verified
that compaction ended.

**Comment by raphaelsc** [comment] 2016-11-16 13:44
@slivne you can see it in the log, but not via nodetool. Let me check the full log to see if there was an ongoing compaction by the time we compacted ka-35

**Comment by raphaelsc** [comment] 2016-11-16 14:06
On Wed, Nov 16, 2016 at 11:43 AM, Shlomi Livne <notifications@github.com>
wrote:

> I assumed I could see it in the counters / in the logs.
>
> e.g. I had a log of a compaction starting with many sstables and verified
> that compaction ended.
>

If you issued lsof after all compaction in the log ended, then we indeed
have another problem. We also have the ones I described above.

**Comment by avikivity** [comment] 2016-11-16 14:09
Looks like the bug is minor, there's window in time where the sstables are half-deleted but then it's cleaned up.  @raphaelsc I agree major compaction should go through compaction manager, waiting for all other compactions to complete before it starts.

**Comment by slivne** [comment] 2016-11-16 15:08
So I think the bigger issues is the one I reported - try to reproduce
locally I gave the complete sequence.

Lets fix this one first.

the nodetool compact not going through compaction manager is an issue but
its not as critical in my view

**Closed** 2016-11-17 15:46 UTC
Labels: bug, User Request
