### ISSUE TITLE
Startup failed: std::runtime_error (Could not find tokens for 10.0.179.211 to replace)`

### ISSUE THREAD

**Issue by amoskong** [scylladb/scylla#6648] opened 2020-06-15 09:20 UTC
*Installation details*
Scylla version (or git commit hash): 4.1.rc2-0.20200609.c6ee86b512f
Cluster size: 6
OS (RHEL/CentOS/Ubuntu/AWS AMI): ami-09310b5117d81331a (eu-west-1)

### Living cluster: 
- https://eu-west-1.console.aws.amazon.com/ec2/v2/home?region=eu-west-1#Instances:search=db1685a6;sort=tag:Name

### Description

In restart_then_repair_node nemesis, the target node (longevity-tls-50gb-4d-4-1-db-node-db1685a6-4) failed to restart.

`2020-06-11T06:15:55+00:00  longevity-tls-50gb-4d-4-1-db-node-db1685a6-4 !ERR     | scylla: [shard 0] init - Startup failed: std::runtime_error (Could not find tokens for 10.0.179.211 to replace)`

### Test Info
- test id: db1685a6-ef05-4b26-9e1b-5feaf3a874b6
- job: https://jenkins.scylladb.com/view/scylla-4.1/job/scylla-4.1/job/longevity/job/longevity-50gb-4days/5/

### longevity configuration yaml
- https://github.com/scylladb/scylla-cluster-tests/blob/branch-4.1/test-cases/longevity/longevity-50GB-4days-authorization-and-tls-ssl.yaml

### Workloads

```
prepare_write_cmd: ["cassandra-stress write cl=QUORUM n=100000000 -schema 'replication(factor=3) compaction(strategy=SizeTieredCompactionStrategy)' -port jmx=6868 -mode cql3 native  -rate threads=500 -pop seq=1..100000000"]

stress_cmd: ["cassandra-stress mixed cl=QUORUM duration=5760m -schema 'replication(factor=3) compaction(strategy=SizeTieredCompactionStrategy)' -port jmx=6868 -mode cql3 native  -rate threads=20 -pop seq=1..100000000 -log interval=5",
             "cassandra-stress user profile=/tmp/cs_mv_profile.yaml ops'(insert=3,read1=1,read2=1,read3=1)' cl=QUORUM duration=5760m -port jmx=6868 -mode cql3 native -rate threads=10",
             "cassandra-stress write cl=QUORUM duration=5760m -schema 'replication(factor=3) compression=LZ4Compressor compaction(strategy=SizeTieredCompactionStrategy)' -port jmx=6868 -mode cql3 native compression=lz4 -rate threads=50 -pop seq=1..100000000 -log interval=5",
             "cassandra-stress write cl=QUORUM duration=5760m -schema 'replication(factor=3) compression=ZstdCompressor compaction(strategy=SizeTieredCompactionStrategy)' -port jmx=6868 -mode cql3 native compression=none -rate threads=50 -pop seq=1..100000000 -log interval=5",
             "cassandra-stress write cl=QUORUM duration=5760m -schema 'replication(factor=3) compression=SnappyCompressor compaction(strategy=SizeTieredCompactionStrategy)' -port jmx=6868 -mode cql3 native compression=snappy -rate threads=50 -pop seq=1..100000000 -log interval=5",
             "cassandra-stress write cl=QUORUM duration=5760m -schema 'replication(factor=3) compression=DeflateCompressor compaction(strategy=SizeTieredCompactionStrategy)' -port jmx=6868 -mode cql3 native compression=none -rate threads=50 -pop seq=1..100000000 -log interval=5"]

stress_read_cmd: ["cassandra-stress read cl=QUORUM duration=5760m -port jmx=6868 -mode cql3 native  -rate threads=50 -pop seq=1..100000000 -log interval=5",
                  "cassandra-stress read cl=QUORUM duration=5760m -schema 'replication(factor=3) compression=LZ4Compressor compaction(strategy=SizeTieredCompactionStrategy)' -port jmx=6868 -mode cql3 native compression=lz4 -rate threads=20 -pop seq=1..100000000 -log interval=5",
                  "cassandra-stress read cl=QUORUM duration=5760m -schema 'replication(factor=3) compression=ZstdCompressor compaction(strategy=SizeTieredCompactionStrategy)' -port jmx=6868 -mode cql3 native compression=none -rate threads=20 -pop seq=1..100000000 -log interval=5",
                  "cassandra-stress read cl=QUORUM duration=5760m -schema 'replication(factor=3) compression=SnappyCompressor compaction(strategy=SizeTieredCompactionStrategy)' -port jmx=6868 -mode cql3 native compression=snappy -rate threads=20 -pop seq=1..100000000 -log interval=5",
                  "cassandra-stress read cl=QUORUM duration=5760m -schema 'replication(factor=3) compression=DeflateCompressor compaction(strategy=SizeTieredCompactionStrategy)' -port jmx=6868 -mode cql3 native compression=none -rate threads=20 -pop seq=1..100000000 -log interval=5"]
```

/CC @asias @roydahan @slivne

**Comment by amoskong** [comment] 2020-06-15 10:47
### Nemesis info

```
06-11 00:43:53,371 >>>>>>>>>>>>>Started random_disrupt_method network_reject_thrift
06-11 00:44:54,829 <<<<<<<<<<<<<Finished random_disrupt_method network_reject_thrift
06-11 00:58:46,260 >>>>>>>>>>>>>Started random_disrupt_method add_drop_column
06-11 01:08:49,699 <<<<<<<<<<<<<Finished random_disrupt_method add_drop_column
06-11 01:23:55,119 >>>>>>>>>>>>>Started random_disrupt_method grow_shrink_cluster
06-11 01:46:43,083 <<<<<<<<<<<<<Finished random_disrupt_method grow_shrink_cluster
06-11 02:04:38,642 >>>>>>>>>>>>>Started random_disrupt_method decommission_streaming_err
06-11 02:44:42,772 <<<<<<<<<<<<<Finished random_disrupt_method decommission_streaming_err
06-11 03:03:25,018 >>>>>>>>>>>>>Started random_disrupt_method restart_then_repair_node
06-11 03:51:48,773 <<<<<<<<<<<<<Finished random_disrupt_method restart_then_repair_node
06-11 04:09:20,365 >>>>>>>>>>>>>Started random_disrupt_method rebuild_streaming_err
06-11 04:34:49,871 >>>>>>>>>>>>>Started random_disrupt_method destroy_data_then_rebuild
06-11 05:17:29,691 <<<<<<<<<<<<<Finished random_disrupt_method destroy_data_then_rebuild
06-11 05:35:42,393 >>>>>>>>>>>>>Started random_disrupt_method delete_10_full_partitions
06-11 05:50:06,110 >>>>>>>>>>>>>Started random_disrupt_method modify_table
06-11 05:52:06,425 <<<<<<<<<<<<<Finished random_disrupt_method modify_table
06-11 06:10:36,876 >>>>>>>>>>>>>Started random_disrupt_method restart_then_repair_node

### db-node-4 failed to restart
2020-06-11T06:15:55+00:00 longevity-tls-50gb-4d-4-1-db-node-db1685a6-4 !ERR \
 | scylla: [shard 0] init - Startup failed: std::runtime_error (Could not find tokens for 10.0.179.211 to replace)

06-11 14:26:36,936 >>>>>>>>>>>>>Started random_disrupt_method destroy_data_then_rebuild
06-11 14:39:23,135 <<<<<<<<<<<<<Finished random_disrupt_method destroy_data_then_rebuild
06-11 14:45:46,227 >>>>>>>>>>>>>Started random_disrupt_method mgmt_backup
06-11 14:52:44,723 >>>>>>>>>>>>>Started random_disrupt_method toggle_table_ics
06-11 14:54:43,996 >>>>>>>>>>>>>Started random_disrupt_method validate_hh_short_downtime
06-11 15:09:05,965 >>>>>>>>>>>>>Started random_disrupt_method mgmt_repair_cli
06-11 15:16:20,233 >>>>>>>>>>>>>Started random_disrupt_method major_compaction
06-11 15:24:21,056 <<<<<<<<<<<<<Finished random_disrupt_method major_compaction
06-11 15:31:04,239 >>>>>>>>>>>>>Started random_disrupt_method no_corrupt_repair
06-11 15:38:37,964 >>>>>>>>>>>>>Started random_disrupt_method major_compaction
06-11 15:44:45,647 <<<<<<<<<<<<<Finished random_disrupt_method major_compaction
06-11 15:51:26,370 >>>>>>>>>>>>>Started random_disrupt_method mgmt_repair_cli
06-11 15:58:34,358 >>>>>>>>>>>>>Started random_disrupt_method network_reject_thrift
06-11 16:00:35,471 <<<<<<<<<<<<<Finished random_disrupt_method network_reject_thrift
06-11 16:07:17,619 >>>>>>>>>>>>>Started random_disrupt_method add_drop_column
06-11 16:17:31,688 <<<<<<<<<<<<<Finished random_disrupt_method add_drop_column
06-11 16:24:11,683 >>>>>>>>>>>>>Started random_disrupt_method snapshot_operations
06-11 16:24:58,239 <<<<<<<<<<<<<Finished random_disrupt_method snapshot_operations
06-11 16:31:38,297 >>>>>>>>>>>>>Started random_disrupt_method snapshot_operations
06-11 16:32:05,786 <<<<<<<<<<<<<Finished random_disrupt_method snapshot_operations
06-11 16:38:46,192 >>>>>>>>>>>>>Started random_disrupt_method nodetool_enospc
06-11 16:54:06,189 <<<<<<<<<<<<<Finished random_disrupt_method nodetool_enospc
06-11 17:00:36,394 >>>>>>>>>>>>>Started random_disrupt_method stop_wait_start_scylla_server
06-11 17:08:07,762 <<<<<<<<<<<<<Finished random_disrupt_method stop_wait_start_scylla_server
06-11 17:14:55,973 >>>>>>>>>>>>>Started random_disrupt_method nodetool_decommission
06-11 17:37:37,751 >>>>>>>>>>>>>Started random_disrupt_method mgmt_backup
06-11 17:45:17,456 >>>>>>>>>>>>>Started random_disrupt_method nodetool_decommission
06-11 17:52:27,678 >>>>>>>>>>>>>Started random_disrupt_method snapshot_operations
06-11 17:52:47,808 <<<<<<<<<<<<<Finished random_disrupt_method snapshot_operations
06-11 17:59:48,758 >>>>>>>>>>>>>Started random_disrupt_method stop_wait_start_scylla_server
06-11 18:07:25,102 <<<<<<<<<<<<<Finished random_disrupt_method stop_wait_start_scylla_server
06-11 18:14:27,773 >>>>>>>>>>>>>Started random_disrupt_method delete_by_rows_range
06-11 18:16:37,828 >>>>>>>>>>>>>Started random_disrupt_method abort_repair
06-11 18:24:13,126 >>>>>>>>>>>>>Started random_disrupt_method hot_reloading_internode_certificate
06-11 18:32:17,459 >>>>>>>>>>>>>Started random_disrupt_method snapshot_operations
06-11 18:32:37,689 <<<<<<<<<<<<<Finished random_disrupt_method snapshot_operations
06-11 18:39:46,742 >>>>>>>>>>>>>Started random_disrupt_method add_drop_column
06-11 18:50:14,212 <<<<<<<<<<<<<Finished random_disrupt_method add_drop_column
06-11 18:57:31,852 >>>>>>>>>>>>>Started random_disrupt_method major_compaction
06-11 19:05:01,827 <<<<<<<<<<<<<Finished random_disrupt_method major_compaction
06-11 19:12:16,841 >>>>>>>>>>>>>Started random_disrupt_method hot_reloading_internode_certificate
06-11 19:20:25,499 >>>>>>>>>>>>>Started random_disrupt_method add_drop_column
06-11 19:30:53,269 <<<<<<<<<<<<<Finished random_disrupt_method add_drop_column
06-11 19:38:07,391 >>>>>>>>>>>>>Started random_disrupt_method grow_shrink_cluster
06-12 14:01:14,189 >>>>>>>>>>>>>Started random_disrupt_method nodetool_cleanup
06-12 14:09:28,504 >>>>>>>>>>>>>Started random_disrupt_method truncate
06-12 14:19:37,687 >>>>>>>>>>>>>Started random_disrupt_method network_start_stop_interface
06-12 14:22:31,550 >>>>>>>>>>>>>Started random_disrupt_method snapshot_operations
06-12 14:23:10,872 <<<<<<<<<<<<<Finished random_disrupt_method snapshot_operations
06-12 14:31:06,008 >>>>>>>>>>>>>Started random_disrupt_method validate_hh_short_downtime
06-12 14:42:40,221 >>>>>>>>>>>>>Started random_disrupt_method repair_streaming_err
```

**Comment by asias** [comment] 2020-06-16 01:21
I think the issue is already fixed in mater:

```
commit dddde335123169f8f81d299b38bae64c41c1adcd
Author: Asias He <asias@scylladb.com>
Date:   Wed Jun 3 09:07:20 2020 +0800

    gossip: Do not send shutdown message when a node is in unknown status
    
    When a replacing node is in early boot up and is not in HIBERNATE sate
    yet, if the node is killed by a user, the node will wrongly send a
    shutdown message to other nodes. This is because UNKNOWN is not in
    SILENT_SHUTDOWN_STATES, so in gossiper::do_stop_gossiping, the node will
    send shutdown message. Other nodes in the cluster will call
    storage_service::handle_state_normal for this node, since NORMAL and
    SHUTDOWN status share the same status handler. As a result, other nodes
    will incorrectly think the node is part of the cluster and the replace
    operation is finished.
    
    Such problem was seen in replace_node_no_hibernate_state_test dtest:
    
       n1, n2 are in the cluster
       n2 is dead
       n3 is started to replace n2, but n3 is killed in the middle
       n3 announces SHUTDOWN status wrongly
       n1 runs storage_service::handle_state_normal for n3
       n1 get tokens for n3 which is empty, because n3 hasn't gossip tokens yet
       n1 skips update normal tokens for n3,  but think n3 has replaced n2
       n4 starts to replace n2
       n4 checks the tokens for n2 in storage_service::join_token_ring (Cannot
          replace token {} which does not exist!) or
          storage_service::prepare_replacement_info (Cannot replace_address {}
          because it doesn't exist in gossip)
    
    To fix, we add UNKNOWN into SILENT_SHUTDOWN_STATES and avoid sending
    shutdown message.
    
    Tests: replace_address_test.py:TestReplaceAddress.replace_node_no_hibernate_state_test
    Fixes: #6436
```

Logs from node4. Node4 sent SHUTDOWN message which caused the issue.


```
Boot 1: 
2020-06-11T06:13:44+00:00  longevity-tls-50gb-4d-4-1-db-node-db1685a6-4 !INFO    | scylla: Scylla version 4.1.rc2-0.20200609.c6ee86b512f with build-id a9aa409a848cafe8899df2500e9f05588f147465 starting ...

62075 2020-06-11T06:14:11+00:00  longevity-tls-50gb-4d-4-1-db-node-db1685a6-4 !INFO    | scylla: [shard 0] storage_service - JOINING: waiting for ring information
62076 2020-06-11T06:14:11+00:00  longevity-tls-50gb-4d-4-1-db-node-db1685a6-4 !INFO    | scylla: [shard 0] storage_service - JOINING: schema complete, ready to bootstrap
62077 2020-06-11T06:14:11+00:00  longevity-tls-50gb-4d-4-1-db-node-db1685a6-4 !INFO    | scylla: [shard 0] storage_service - JOINING: waiting for pending range calculation
62078 2020-06-11T06:14:11+00:00  longevity-tls-50gb-4d-4-1-db-node-db1685a6-4 !INFO    | scylla: [shard 0] storage_service - JOINING: calculation complete, ready to bootstrap
62079 2020-06-11T06:14:11+00:00  longevity-tls-50gb-4d-4-1-db-node-db1685a6-4 !INFO    | scylla: [shard 0] storage_service - Checking bootstrapping/leaving nodes: ok
62080 2020-06-11T06:14:11+00:00  longevity-tls-50gb-4d-4-1-db-node-db1685a6-4 !INFO    | scylla: [shard 0] init - Shutting down gossiping
62081 2020-06-11T06:14:11+00:00  longevity-tls-50gb-4d-4-1-db-node-db1685a6-4 !INFO    | scylla: [shard 0] gossip - My status = UNKNOWN
62082 2020-06-11T06:14:11+00:00  longevity-tls-50gb-4d-4-1-db-node-db1685a6-4 !INFO    | scylla: [shard 0] gossip - Announcing shutdown


Boot 2: tried to replace a node

2020-06-11T06:15:51+00:00  longevity-tls-50gb-4d-4-1-db-node-db1685a6-4 !INFO    | scylla: Scylla version 4.1.rc2-0.20200609.c6ee86b512f with build-id a9aa409a848cafe8899df2500e9f05588f147465 starting ...

62243 2020-06-11T06:15:52+00:00  longevity-tls-50gb-4d-4-1-db-node-db1685a6-4 !INFO    | scylla: [shard 0] storage_service - Gathering node replacement information for 10.0.179.211
```

**Comment by asias** [comment] 2020-06-16 01:24
Backport  to 4.1 requested.

**Comment by bhalevy** [comment] 2020-06-22 05:39
@asias 2ee321d88e40caa011a3342a5657bfb51f945bb0 was already backported to 4.1.
It is not included in the version this issues was opened with (c6ee86b512f) though.
Let's close the issue and reopen if hit again.

**Closed by bhalevy** 2020-06-22 05:39 UTC
Labels: bug
