### ISSUE TITLE
Scylla couldn't started on i3.16xlarge and i3.8xlarge aws instances

### ISSUE THREAD

**Issue by aleksbykov** [scylladb/scylla#6899] opened 2020-07-22 06:44 UTC
*Installation details*
Scylla version (or git commit hash): Scylla version 4.2.rc1-0.20200719.bd713959ce1 with build-id 16232bd4f02d443afe6bff5b7d3c26a753605cd1
Cluster size:1
OS (RHEL/CentOS/Ubuntu/AWS AMI): ami-0ecb2678651e45875
instance types: i3.16xlarge, i3.8xlarge

During artifacts Jobs for instances type i3.16xlarge, i3.8xlarge, scylla could n't be started
log records
```
:15:44 artifacts-ami-jenkins-db-node-cbeb5286-1 scylla_prepare[2382]: Setting limit 4096 in /sys/class/net/eth0/queues/rx-2/rps_flow_cnt
Jul 22 06:15:44 artifacts-ami-jenkins-db-node-cbeb5286-1 scylla_prepare[2382]: Setting limit 4096 in /sys/class/net/eth0/queues/rx-0/rps_flow_cnt
Jul 22 06:15:44 artifacts-ami-jenkins-db-node-cbeb5286-1 scylla_prepare[2382]: Trying to enable ntuple filtering HW offload for eth0...not supported
Jul 22 06:15:44 artifacts-ami-jenkins-db-node-cbeb5286-1 scylla_prepare[2382]: Setting mask 00030003 in /sys/class/net/eth0/queues/tx-6/xps_cpus
Jul 22 06:15:44 artifacts-ami-jenkins-db-node-cbeb5286-1 scylla_prepare[2382]: Setting mask 000c000c in /sys/class/net/eth0/queues/tx-4/xps_cpus
Jul 22 06:15:44 artifacts-ami-jenkins-db-node-cbeb5286-1 scylla_prepare[2382]: Setting mask 00300030 in /sys/class/net/eth0/queues/tx-2/xps_cpus
Jul 22 06:15:44 artifacts-ami-jenkins-db-node-cbeb5286-1 scylla_prepare[2382]: Setting mask 00c000c0 in /sys/class/net/eth0/queues/tx-0/xps_cpus
Jul 22 06:15:44 artifacts-ami-jenkins-db-node-cbeb5286-1 scylla_prepare[2382]: Setting mask 03000300 in /sys/class/net/eth0/queues/tx-7/xps_cpus
Jul 22 06:15:44 artifacts-ami-jenkins-db-node-cbeb5286-1 scylla_prepare[2382]: Setting mask 0c000c00 in /sys/class/net/eth0/queues/tx-5/xps_cpus
Jul 22 06:15:44 artifacts-ami-jenkins-db-node-cbeb5286-1 scylla_prepare[2382]: Setting mask 30003000 in /sys/class/net/eth0/queues/tx-3/xps_cpus
Jul 22 06:15:44 artifacts-ami-jenkins-db-node-cbeb5286-1 scylla_prepare[2382]: Setting mask c000c000 in /sys/class/net/eth0/queues/tx-1/xps_cpus
Jul 22 06:15:44 artifacts-ami-jenkins-db-node-cbeb5286-1 scylla_prepare[2382]: Writing '4096' to /proc/sys/net/core/somaxconn
Jul 22 06:15:44 artifacts-ami-jenkins-db-node-cbeb5286-1 scylla_prepare[2382]: Writing '4096' to /proc/sys/net/ipv4/tcp_max_syn_backlog
Jul 22 06:15:45 artifacts-ami-jenkins-db-node-cbeb5286-1 scylla[2515]: Scylla version 4.2.rc1-0.20200719.bd713959ce1 with build-id 16232bd4f02d443afe6bff5b7d3c26a753605cd1 starting ...
Jul 22 06:15:45 artifacts-ami-jenkins-db-node-cbeb5286-1 scylla[2515]: command used: "/usr/bin/scylla --blocked-reactor-notify-ms 500 --abort-on-lsa-bad-alloc 1 --abort-on-seastar-bad-alloc --abort-on-internal-error 1 --abort-on-ebadf 1 --enable-sstable-key-validation 1 --log-to-syslog 1 --log-to-stdout 0 --default-log-level info --network-stack posix --io-properties-file=/etc/scylla.d/io_properties.yaml --cpuset 1-15,17-31 --lock-memory=1"
Jul 22 06:15:45 artifacts-ami-jenkins-db-node-cbeb5286-1 scylla[2515]: parsed command line options: [blocked-reactor-notify-ms: 500, abort-on-lsa-bad-alloc: 1, abort-on-seastar-bad-alloc, abort-on-internal-error: 1, abort-on-ebadf: 1, enable-sstable-key-validation: 1, log-to-syslog: 1, log-to-stdout: 0, default-log-level: info, network-stack: posix, io-properties-file: /etc/scylla.d/io_properties.yaml, cpuset: 1-15,17-31, lock-memory: 1]
Jul 22 06:15:48 artifacts-ami-jenkins-db-node-cbeb5286-1 scylla[2515]:  [shard 0] init - installing SIGHUP handler
Jul 22 06:15:48 artifacts-ami-jenkins-db-node-cbeb5286-1 scylla[2515]:  [shard 0] init - Scylla version 4.2.rc1-0.20200719.bd713959ce1 with build-id 16232bd4f02d443afe6bff5b7d3c26a753605cd1 starting ...
Jul 22 06:15:48 artifacts-ami-jenkins-db-node-cbeb5286-1 scylla[2515]:  [shard 0] init - starting prometheus API server
Jul 22 06:15:48 artifacts-ami-jenkins-db-node-cbeb5286-1 scylla[2515]:  [shard 0] init - starting tokens manager
Jul 22 06:15:48 artifacts-ami-jenkins-db-node-cbeb5286-1 scylla[2515]:  [shard 0] init - starting migration manager notifier
Jul 22 06:15:48 artifacts-ami-jenkins-db-node-cbeb5286-1 scylla[2515]:  [shard 0] init - creating tracing
Jul 22 06:15:48 artifacts-ami-jenkins-db-node-cbeb5286-1 scylla[2515]:  [shard 0] init - creating snitch
Jul 22 06:15:48 artifacts-ami-jenkins-db-node-cbeb5286-1 scylla[2515]:  [shard 0] snitch_logger - Ec2Snitch using region: us-east, zone: 1b.
Jul 22 06:15:48 artifacts-ami-jenkins-db-node-cbeb5286-1 scylla[2515]:  [shard 0] init - determining DNS name
Jul 22 06:15:48 artifacts-ami-jenkins-db-node-cbeb5286-1 scylla[2515]:  [shard 0] init - starting API server
Jul 22 06:15:48 artifacts-ami-jenkins-db-node-cbeb5286-1 scylla[2515]:  [shard 0] init - Scylla API server listening on 127.0.0.1:10000 ...
Jul 22 06:15:48 artifacts-ami-jenkins-db-node-cbeb5286-1 scylla[2515]:  [shard 0] init - Shutting down migration manager notifier
Jul 22 06:15:48 artifacts-ami-jenkins-db-node-cbeb5286-1 scylla[2515]:  [shard 0] init - Shutting down migration manager notifier was successful
Jul 22 06:15:48 artifacts-ami-jenkins-db-node-cbeb5286-1 scylla[2515]:  [shard 0] init - Shutting down prometheus API server
Jul 22 06:16:58 artifacts-ami-jenkins-db-node-cbeb5286-1 systemd[1]: scylla-server.service: main process exited, code=exited, status=1/FAILURE
Jul 22 06:16:59 artifacts-ami-jenkins-db-node-cbeb5286-1 systemd[1]: Failed to start Scylla Server.
Jul 22 06:16:59 artifacts-ami-jenkins-db-node-cbeb5286-1 systemd[1]: Dependency failed for Scylla JMX.
Jul 22 06:16:59 artifacts-ami-jenkins-db-node-cbeb5286-1 systemd[1]: Job scylla-jmx.service/start failed with result 'dependency'.
Jul 22 06:16:59 artifacts-ami-jenkins-db-node-cbeb5286-1 systemd[1]: Unit scylla-server.service entered failed state.
Jul 22 06:16:59 artifacts-ami-jenkins-db-node-cbeb5286-1 systemd[1]: scylla-server.service failed.
```

DB log: https://cloudius-jenkins-test.s3.amazonaws.com/cbeb5286-4eea-4870-ab52-1b85ca9f2117/20200722_061734/db-cluster-cbeb5286.zip

**Comment by roydahan** [comment] 2020-07-23 06:59
Do you see in journalctl or messages what is the root cause of it?

**Comment by slivne** [comment] 2020-07-23 09:19
lets try to reproduce this, outside of jenkins

**Comment by slivne** [comment] 2020-07-23 11:13
@haaawk need someone in your tream to try and do initial analysis
Use the AMI provided and try to boot scylla (open logs to find out why its not starting).

**Comment by aleksbykov** [comment] 2020-07-23 14:55
It seems that nodes could not started due to #6813 
I run several times instances i3.16xlarge and i3.8xlarge manually with with same ami, and each time scylla was not started due to 
std::runtime_error (random_device: rdseed failed).

**Comment by slivne** [comment] 2020-07-23 15:09
Thanks

We should have the fix over the weekend :)

**Comment by avikivity** [comment] 2020-07-26 09:19
Closing as duplicate of #6813.

**Closed by avikivity** 2020-07-26 09:19 UTC
Labels: AWS, bug
