### ISSUE TITLE
No prepared statement with ID found when using RUST and CDRS via prepared statement

### ISSUE THREAD

**Issue by ghost** [scylladb/scylla#5936] opened 2020-03-02 17:26 UTC
*Installation details*
Scylla version (or git commit hash): 3.0.6-0.20190503.bf68fae01
Cluster size: 3
OS (RHEL/CentOS/Ubuntu/AWS AMI): CentOS

Getting the following error when executing a prepared statement in Rust via CDRS lib:

    No prepared statement with ID {any id} found.

That's somehow similar what's described on these email thread:

https://groups.google.com/forum/#!topic/scylladb-users/PGsaty8eB2s

Although, in my case, there's no authentication involved.

Is there any kind of fix planned on this matter?

**Comment by gnumoreno** [comment] 2020-03-02 18:17
@bruno-barin-ifood in the same discussion apparently Go had a problem in the driver.

`https://github.com/gocql/gocql/issues/1252`

Is there a chance it is the rust cdrs? 

Anyway, I'm trying to get a dev to take a look asap.

**Comment by slivne** [comment] 2020-03-03 10:32
I assume this is the library https://github.com/AlexPikalov/cdrs

@bruno-barin-ifood can you please provide a tcpdump / wireshark capture of the traffic (port 9042 - should be enough) while disabling compression https://github.com/AlexPikalov/cdrs/blob/e9ec8594f087b0601f7bd911d68b416277822d99/documentation/cdrs-session.md#data-compression

This will help us understand what the issue is - if its something on the application (driver) / scylla end.

We may need another iteration with scylla logs not a must

**Comment by bruno-barin-ifood** [comment] 2020-03-03 14:23
Hi @slivne, it happens that you are the guy who responded to the mail thread I've mentioned earlier :)!
Isn't this just a matter to increase the mentioned cache?
I will try to load attaching a tcpdump and post the results here.

**Comment by bruno-barin-ifood** [comment] 2020-03-03 21:40
Just made a test and increasing the property `permissions_cache_max_entries` to 1_000_000 and restarting the cluster the error disappeared. I find strange to have to increase the cache to a high amount in order to see this problem to cease. Should the driver handle such scenarios like a cache miss? To explain a bit more, I'm trying to fetch around 1 million messages from Apache Kafka and persist those messages to Scylla. I would expect to perform a single prepared statement and only varying the values. Would my assumption be correct?

**Comment by bruno-barin-ifood** [comment] 2020-03-05 16:46
@slivne 
Here you go:

```13:41:11.122611 IP 10.254.14.165.51010 > 10.111.20.19.9042: Flags [P.], seq 489021:489030, ack 171346, win 2963, options [nop,nop,TS val 2081799760 ecr 525019658], length 9
13:41:11.126899 IP 10.111.20.19.9042 > 10.254.14.165.51010: Flags [P.], seq 171346:171607, ack 489030, win 213, options [nop,nop,TS val 525019683 ecr 2081799760], length 261
13:41:11.126969 IP 10.254.14.165.51010 > 10.111.20.19.9042: Flags [P.], seq 489030:490057, ack 171607, win 2972, options [nop,nop,TS val 2081799764 ecr 525019683], length 1027
13:41:11.131428 IP 10.111.20.19.9042 > 10.254.14.165.51010: Flags [P.], seq 171607:171709, ack 490057, win 213, options [nop,nop,TS val 525019687 ecr 2081799764], length 102
13:41:11.149644 IP 10.254.14.165.51010 > 10.111.20.19.9042: Flags [P.], seq 490057:490066, ack 171709, win 2972, options [nop,nop,TS val 2081799787 ecr 525019687], length 9
13:41:11.154005 IP 10.111.20.19.9042 > 10.254.14.165.51010: Flags [P.], seq 171709:171970, ack 490066, win 213, options [nop,nop,TS val 525019710 ecr 2081799787], length 261
13:41:11.154095 IP 10.254.14.165.51010 > 10.111.20.19.9042: Flags [P.], seq 490066:491093, ack 171970, win 2980, options [nop,nop,TS val 2081799791 ecr 525019710], length 1027
13:41:11.158887 IP 10.111.20.19.9042 > 10.254.14.165.51010: Flags [P.], seq 171970:172072, ack 491093, win 213, options [nop,nop,TS val 525019714 ecr 2081799791], length 102
13:41:11.178800 IP 10.254.14.165.51010 > 10.111.20.19.9042: Flags [P.], seq 491093:491102, ack 172072, win 2980, options [nop,nop,TS val 2081799816 ecr 525019714], length 9
13:41:11.183599 IP 10.111.20.19.9042 > 10.254.14.165.51010: Flags [P.], seq 172072:172333, ack 491102, win 213, options [nop,nop,TS val 525019739 ecr 2081799816], length 261
13:41:11.183863 IP 10.254.14.165.51010 > 10.111.20.19.9042: Flags [P.], seq 491102:492129, ack 172333, win 2989, options [nop,nop,TS val 2081799821 ecr 525019739], length 1027
13:41:11.188562 IP 10.111.20.19.9042 > 10.254.14.165.51010: Flags [P.], seq 172333:172435, ack 492129, win 213, options [nop,nop,TS val 525019744 ecr 2081799821], length 102
13:41:11.208129 IP 10.254.14.165.51010 > 10.111.20.19.9042: Flags [P.], seq 492129:492138, ack 172435, win 2989, options [nop,nop,TS val 2081799845 ecr 525019744], length 9
13:41:11.212823 IP 10.111.20.19.9042 > 10.254.14.165.51010: Flags [P.], seq 172435:172696, ack 492138, win 213, options [nop,nop,TS val 525019768 ecr 2081799845], length 261
13:41:11.213122 IP 10.254.14.165.51010 > 10.111.20.19.9042: Flags [P.], seq 492138:493165, ack 172696, win 2997, options [nop,nop,TS val 2081799850 ecr 525019768], length 1027
13:41:11.217817 IP 10.111.20.19.9042 > 10.254.14.165.51010: Flags [P.], seq 172696:172798, ack 493165, win 213, options [nop,nop,TS val 525019774 ecr 2081799850], length 102
13:41:11.237284 IP 10.254.14.165.51010 > 10.111.20.19.9042: Flags [P.], seq 493165:493174, ack 172798, win 2997, options [nop,nop,TS val 2081799874 ecr 525019774], length 9
13:41:11.241796 IP 10.111.20.19.9042 > 10.254.14.165.51010: Flags [P.], seq 172798:173059, ack 493174, win 213, options [nop,nop,TS val 525019798 ecr 2081799874], length 261
13:41:11.241893 IP 10.254.14.165.51010 > 10.111.20.19.9042: Flags [P.], seq 493174:494201, ack 173059, win 3005, options [nop,nop,TS val 2081799879 ecr 525019798], length 1027
13:41:11.246777 IP 10.111.20.19.9042 > 10.254.14.165.51010: Flags [P.], seq 173059:173161, ack 494201, win 213, options [nop,nop,TS val 525019802 ecr 2081799879], length 102
13:41:11.267084 IP 10.254.14.165.51010 > 10.111.20.19.9042: Flags [P.], seq 494201:494210, ack 173161, win 3005, options [nop,nop,TS val 2081799904 ecr 525019802], length 9
13:41:11.271842 IP 10.111.20.19.9042 > 10.254.14.165.51010: Flags [P.], seq 173161:173422, ack 494210, win 213, options [nop,nop,TS val 525019827 ecr 2081799904], length 261
13:41:11.272180 IP 10.254.14.165.51010 > 10.111.20.19.9042: Flags [P.], seq 494210:495237, ack 173422, win 3014, options [nop,nop,TS val 2081799909 ecr 525019827], length 1027
13:41:11.276997 IP 10.111.20.19.9042 > 10.254.14.165.51010: Flags [P.], seq 173422:173524, ack 495237, win 213, options [nop,nop,TS val 525019833 ecr 2081799909], length 102
13:41:11.296293 IP 10.254.14.165.51010 > 10.111.20.19.9042: Flags [P.], seq 495237:495246, ack 173524, win 3014, options [nop,nop,TS val 2081799934 ecr 525019833], length 9
13:41:11.300838 IP 10.111.20.19.9042 > 10.254.14.165.51010: Flags [P.], seq 173524:173785, ack 495246, win 213, options [nop,nop,TS val 525019856 ecr 2081799934], length 261
13:41:11.301139 IP 10.254.14.165.51010 > 10.111.20.19.9042: Flags [P.], seq 495246:496273, ack 173785, win 3022, options [nop,nop,TS val 2081799938 ecr 525019856], length 1027
13:41:11.305862 IP 10.111.20.19.9042 > 10.254.14.165.51010: Flags [P.], seq 173785:173887, ack 496273, win 213, options [nop,nop,TS val 525019861 ecr 2081799938], length 102
13:41:11.324961 IP 10.254.14.165.51010 > 10.111.20.19.9042: Flags [P.], seq 496273:496282, ack 173887, win 3022, options [nop,nop,TS val 2081799962 ecr 525019861], length 9
13:41:11.329233 IP 10.111.20.19.9042 > 10.254.14.165.51010: Flags [P.], seq 173887:174148, ack 496282, win 213, options [nop,nop,TS val 525019885 ecr 2081799962], length 261
```

**Comment by bruno-barin-ifood** [comment] 2020-03-09 11:06
@slivne Any news on this?

**Comment by slivne** [comment] 2020-03-09 11:15
can you please attach the tcpdump / wireshark capture so I can analyze it

**Comment by bruno-barin-ifood** [comment] 2020-03-09 12:43
The dump is pasted on the previous message

**Comment by slivne** [comment] 2020-03-09 13:08
I need the raw packets themself

**Comment by avikivity** [comment] 2020-03-09 13:35
I think two things are happening:
1. The rust driver is not re-preparing statements for which it gets this message. It's the driver's responsibility to re-prepare, since if a node goes down, it loses all prepared statements.
2. The application is generating a large amount of prepared statements. This usually happens when the statement undergoes formatting on the client side and some parameter is embedded in it, instead of using bind parameters.

**Comment by slivne** [comment] 2020-03-09 13:38
That maybe the case, we did see this in the past when a comment was
embedded inside a prepared statement - and that caused an issue.

It would really help to get a tcpdump of such traffic so we can provide
input on why this happens.

**Comment by gnumoreno** [comment] 2020-03-09 17:25
@bruno-barin-ifood can you please provide the tcpdump raw packages?

**Comment by bruno-barin-ifood** [comment] 2020-03-10 10:55
Sure, below you have a sample:

```07:53:22.865774 IP 10.254.14.135.37928 > 10.111.20.19.9042: Flags [P.], seq 416158:416966, ack 45646, win 501, options [nop,nop,TS val 700375685 ecr 936151332], length 808
	0x0000:  4500 035c b25e 4000 4006 4d37 0afe 0e87  E..\.^@.@.M7....
	0x0010:  0a6f 1413 9428 2352 c5a9 139b c04a e60f  .o...(#R.....J..
	0x0020:  8018 01f5 2890 0000 0101 080a 29be e285  ....(.......)...
	0x0030:  37cc 8924 6e69 6e67 5469 6d65 223a 2231  7..$ningTime":"1
	0x0040:  3937 302d 3031 2d30 3154 3033 3a30 303a  970-01-01T03:00:
	0x0050:  3030 5a22 2c22 636c 6f73 696e 6754 696d  00Z","closingTim
	0x0060:  6522 3a22 3139 3730 2d30 312d 3032 5430  e":"1970-01-02T0
	0x0070:  323a 3539 3a35 395a 227d 2c7b 2264 6179  2:59:59Z"},{"day
	0x0080:  4f66 5765 656b 223a 2257 4544 4e45 5344  OfWeek":"WEDNESD
	0x0090:  4159 222c 226f 7065 6e69 6e67 5469 6d65  AY","openingTime
	0x00a0:  223a 2231 3937 302d 3031 2d30 3154 3033  ":"1970-01-01T03
	0x00b0:  3a30 303a 3030 5a22 2c22 636c 6f73 696e  :00:00Z","closin
	0x00c0:  6754 696d 6522 3a22 3139 3730 2d30 312d  gTime":"1970-01-
	0x00d0:  3032 5430 323a 3539 3a35 395a 227d 2c7b  02T02:59:59Z"},{
	0x00e0:  2264 6179 4f66 5765 656b 223a 2254 4855  "dayOfWeek":"THU
	0x00f0:  5253 4441 5922 2c22 6f70 656e 696e 6754  RSDAY","openingT
	0x0100:  696d 6522 3a22 3139 3730 2d30 312d 3031  ime":"1970-01-01
	0x0110:  5430 333a 3030 3a30 305a 222c 2263 6c6f  T03:00:00Z","clo
	0x0120:  7369 6e67 5469 6d65 223a 2231 3937 302d  singTime":"1970-
	0x0130:  3031 2d30 3254 3032 3a35 393a 3539 5a22  01-02T02:59:59Z"
	0x0140:  7d2c 7b22 6461 794f 6657 6565 6b22 3a22  },{"dayOfWeek":"
	0x0150:  4652 4944 4159 222c 226f 7065 6e69 6e67  FRIDAY","opening
	0x0160:  5469 6d65 223a 2231 3937 302d 3031 2d30  Time":"1970-01-0
	0x0170:  3154 3033 3a30 303a 3030 5a22 2c22 636c  1T03:00:00Z","cl
	0x0180:  6f73 696e 6754 696d 6522 3a22 3139 3730  osingTime":"1970
	0x0190:  2d30 312d 3032 5430 323a 3539 3a35 395a  -01-02T02:59:59Z
	0x01a0:  227d 2c7b 2264 6179 4f66 5765 656b 223a  "},{"dayOfWeek":
	0x01b0:  2253 4154 5552 4441 5922 2c22 6f70 656e  "SATURDAY","open
	0x01c0:  696e 6754 696d 6522 3a22 3139 3730 2d30  ingTime":"1970-0
	0x01d0:  312d 3031 5430 333a 3030 3a30 305a 222c  1-01T03:00:00Z",
	0x01e0:  2263 6c6f 7369 6e67 5469 6d65 223a 2231  "closingTime":"1
	0x01f0:  3937 302d 3031 2d30 3254 3032 3a35 393a  970-01-02T02:59:
	0x0200:  3539 5a22 7d2c 7b22 6461 794f 6657 6565  59Z"},{"dayOfWee
	0x0210:  6b22 3a22 5355 4e44 4159 222c 226f 7065  k":"SUNDAY","ope
	0x0220:  6e69 6e67 5469 6d65 223a 2231 3937 302d  ningTime":"1970-
	0x0230:  3031 2d30 3154 3033 3a30 303a 3030 5a22  01-01T03:00:00Z"
	0x0240:  2c22 636c 6f73 696e 6754 696d 6522 3a22  ,"closingTime":"
	0x0250:  3139 3730 2d30 312d 3032 5430 323a 3539  1970-01-02T02:59
	0x0260:  3a35 395a 227d 5d2c 2274 6f74 616c 223a  :59Z"}],"total":
	0x0270:  3134 3935 307d 5d2c 2261 6363 6f75 6e74  14950}],"account
	0x0280:  4964 223a 6e75 6c6c 2c22 6372 6561 7465  Id":null,"create
	0x0290:  6441 7422 3a22 3230 3230 2d30 332d 3130  dAt":"2020-03-10
	0x02a0:  5431 303a 3436 3a33 322e 3133 3636 3138  T10:46:32.136618
	0x02b0:  5a22 2c22 7465 6e61 6e74 4964 223a 2249  Z","tenantId":"I
	0x02c0:  464f 222c 2264 656c 6976 6572 7922 3a6e  FO","delivery":n
	0x02d0:  756c 6c2c 2273 6368 6564 756c 6522 3a6e  ull,"schedule":n
	0x02e0:  756c 6c2c 2275 7064 6174 6564 4174 223a  ull,"updatedAt":
	0x02f0:  6e75 6c6c 2c22 7374 6174 7573 223a 224f  null,"status":"O
	0x0300:  5045 4e22 2c22 7375 6254 6f74 616c 223a  PEN","subTotal":
	0x0310:  3134 3935 302c 2264 656c 6976 6572 7946  14950,"deliveryF
	0x0320:  6565 223a 302c 2274 6f74 616c 223a 3134  ee":0,"total":14
	0x0330:  3935 307d 0006 7374 6174 7573 0000 0004  950}..status....
	0x0340:  4f50 454e 0002 6964 0000 0010 25df d75c  OPEN..id....%..\
	0x0350:  9a64 4f8c af22 d90a 545b 7828            .dO.."..T[x(
07:53:22.955188 IP 10.111.20.19.9042 > 10.254.14.135.37928: Flags [.], ack 416158, win 213, options [nop,nop,TS val 936151375 ecr 700375580], length 0
	0x0000:  4500 0034 39d5 4000 3f06 c9e8 0a6f 1413  E..49.@.?....o..
	0x0010:  0afe 0e87 2352 9428 c04a e60f c5a9 139b  ....#R.(.J......
	0x0020:  8010 00d5 39d1 0000 0101 080a 37cc 894f  ....9.......7..O
	0x0030:  29be e21c                                )...
07:53:22.955219 IP 10.111.20.19.9042 > 10.254.14.135.37928: Flags [P.], seq 45646:45748, ack 416966, win 213, options [nop,nop,TS val 936151375 ecr 700375580], length 102
	0x0000:  4500 009a 39d6 4000 3f06 c981 0a6f 1413  E...9.@.?....o..
	0x0010:  0afe 0e87 2352 9428 c04a e60f c5a9 16c3  ....#R.(.J......
	0x0020:  8018 00d5 04cd 0000 0101 080a 37cc 894f  ............7..O
	0x0030:  29be e21c 8400 91e4 0000 0000 5d00 0025  )...........]..%
	0x0040:  0000 454e 6f20 7072 6570 6172 6564 2073  ..ENo.prepared.s
	0x0050:  7461 7465 6d65 6e74 2077 6974 6820 4944  tatement.with.ID
	0x0060:  2031 6533 3165 3831 6235 6639 3063 3939  .1e31e81b5f90c99
	0x0070:  3134 6433 6131 6431 6365 3661 3761 6130  14d3a1d1ce6a7aa0
	0x0080:  3420 666f 756e 642e 0010 1e31 e81b 5f90  4.found....1.._.
	0x0090:  c991 4d3a 1d1c e6a7 aa04                 ..M:......
07:53:22.965254 IP 10.111.20.19.9042 > 10.254.14.135.37928: Flags [.], ack 416966, win 213, options [nop,nop,TS val 936151541 ecr 700375685,nop,nop,sack 1 {416158:416966}], length 0
	0x0000:  4500 0040 39d7 4000 3f06 c9da 0a6f 1413  E..@9.@.?....o..
	0x0010:  0afe 0e87 2352 9428 c04a e675 c5a9 16c3  ....#R.(.J.u....
	0x0020:  b010 00d5 496b 0000 0101 080a 37cc 89f5  ....Ik......7...
	0x0030:  29be e285 0101 050a c5a9 139b c5a9 16c3  )...............
07:53:23.001705 IP 10.254.14.135.37928 > 10.111.20.19.9042: Flags [.], ack 45748, win 501, options [nop,nop,TS val 700375821 ecr 936151375], length 0
	0x0000:  4500 0034 b25f 4000 4006 505e 0afe 0e87  E..4._@.@.P^....
	0x0010:  0a6f 1413 9428 2352 c5a9 16c3 c04a e675  .o...(#R.....J.u
	0x0020:  8010 01f5 3432 0000 0101 080a 29be e30d  ....42......)...
	0x0030:  37cc 894f                                7..O
07:53:23.172951 IP 10.111.20.19.9042 > 10.254.14.135.37928: Flags [P.], seq 45646:45748, ack 416966, win 213, options [nop,nop,TS val 936151681 ecr 700375685], length 102
	0x0000:  4500 009a 39d8 4000 3f06 c97f 0a6f 1413  E...9.@.?....o..
	0x0010:  0afe 0e87 2352 9428 c04a e60f c5a9 16c3  ....#R.(.J......
	0x0020:  8018 00d5 0332 0000 0101 080a 37cc 8a81  .....2......7...
	0x0030:  29be e285 8400 91e4 0000 0000 5d00 0025  )...........]..%
	0x0040:  0000 454e 6f20 7072 6570 6172 6564 2073  ..ENo.prepared.s
	0x0050:  7461 7465 6d65 6e74 2077 6974 6820 4944  tatement.with.ID
	0x0060:  2031 6533 3165 3831 6235 6639 3063 3939  .1e31e81b5f90c99
	0x0070:  3134 6433 6131 6431 6365 3661 3761 6130  14d3a1d1ce6a7aa0
	0x0080:  3420 666f 756e 642e 0010 1e31 e81b 5f90  4.found....1.._.
	0x0090:  c991 4d3a 1d1c e6a7 aa04                 ..M:......
07:53:23.172971 IP 10.254.14.135.37928 > 10.111.20.19.9042: Flags [.], ack 45748, win 501, options [nop,nop,TS val 700375993 ecr 936151681,nop,nop,sack 1 {45646:45748}], length 0
	0x0000:  4500 0040 b260 4000 4006 5051 0afe 0e87  E..@.`@.@.PQ....
	0x0010:  0a6f 1413 9428 2352 c5a9 16c3 c04a e675  .o...(#R.....J.u
	0x0020:  b010 01f5 af21 0000 0101 080a 29be e3b9  .....!......)...
	0x0030:  37cc 8a81 0101 050a c04a e60f c04a e675  7........J...J.u
07:53:23.380977 IP 10.254.14.135.37928 > 10.111.20.19.9042: Flags [P.], seq 416966:416975, ack 45748, win 501, options [nop,nop,TS val 700376201 ecr 936151681], length 9
	0x0000:  4500 003d b261 4000 4006 5053 0afe 0e87  E..=.a@.@.PS....
	0x0010:  0a6f 1413 9428 2352 c5a9 16c3 c04a e675  .o...(#R.....J.u
	0x0020:  8018 01f5 6076 0000 0101 080a 29be e489  ....`v......)...
	0x0030:  37cc 8a81 0400 c7fc 0500 0000 00         7............
07:53:23.396377 IP 10.111.20.19.9042 > 10.254.14.135.37928: Flags [.], ack 416975, win 213, options [nop,nop,TS val 936151985 ecr 700376201], length 0
	0x0000:  4500 0034 39d9 4000 3f06 c9e4 0a6f 1413  E..49.@.?....o..
	0x0010:  0afe 0e87 2352 9428 c04a e675 c5a9 16cc  ....#R.(.J.u....
	0x0020:  8010 00d5 316b 0000 0101 080a 37cc 8bb1  ....1k......7...
	0x0030:  29be e489                                )...
07:53:23.396408 IP 10.111.20.19.9042 > 10.254.14.135.37928: Flags [P.], seq 45748:46009, ack 416975, win 213, options [nop,nop,TS val 936151985 ecr 700376201], length 261
	0x0000:  4500 0139 39da 4000 3f06 c8de 0a6f 1413  E..99.@.?....o..
	0x0010:  0afe 0e87 2352 9428 c04a e675 c5a9 16cc  ....#R.(.J.u....
	0x0020:  8018 00d5 d07d 0000 0101 080a 37cc 8bb1  .....}......7...
	0x0030:  29be e489 8400 c7fc 0600 0000 fc00 0700  )...............
	0x0040:  0b43 4f4d 5052 4553 5349 4f4e 0002 0003  .COMPRESSION....
	0x0050:  6c7a 3400 0673 6e61 7070 7900 0b43 514c  lz4..snappy..CQL
	0x0060:  5f56 4552 5349 4f4e 0001 0005 332e 332e  _VERSION....3.3.
	0x0070:  3100 1053 4359 4c4c 415f 4e52 5f53 4841  1..SCYLLA_NR_SHA
	0x0080:  5244 5300 0100 0233 3400 1253 4359 4c4c  RDS....34..SCYLL
	0x0090:  415f 5041 5254 4954 494f 4e45 5200 0100  A_PARTITIONER...
	0x00a0:  2b6f 7267 2e61 7061 6368 652e 6361 7373  +org.apache.cass
	0x00b0:  616e 6472 612e 6468 742e 4d75 726d 7572  andra.dht.Murmur
	0x00c0:  3350 6172 7469 7469 6f6e 6572 000c 5343  3Partitioner..SC
	0x00d0:  594c 4c41 5f53 4841 5244 0001 0002 3134  YLLA_SHARD....14
	0x00e0:  0019 5343 594c 4c41 5f53 4841 5244 494e  ..SCYLLA_SHARDIN
	0x00f0:  475f 414c 474f 5249 5448 4d00 0100 1862  G_ALGORITHM....b
	0x0100:  6961 7365 642d 746f 6b65 6e2d 726f 756e  iased-token-roun
	0x0110:  642d 726f 6269 6e00 1a53 4359 4c4c 415f  d-robin..SCYLLA_
	0x0120:  5348 4152 4449 4e47 5f49 474e 4f52 455f  SHARDING_IGNORE_
	0x0130:  4d53 4200 0100 0231 32                   MSB....12
07:53:23.396428 IP 10.254.14.135.37928 > 10.111.20.19.9042: Flags [.], ack 46009, win 501, options [nop,nop,TS val 700376216 ecr 936151985], length 0
	0x0000:  4500 0034 b262 4000 4006 505b 0afe 0e87  E..4.b@.@.P[....
	0x0010:  0a6f 1413 9428 2352 c5a9 16cc c04a e77a  .o...(#R.....J.z
	0x0020:  8010 01f5 2f37 0000 0101 080a 29be e498  ..../7......)...
	0x0030:  37cc 8bb1                                7...
```

**Comment by avikivity** [comment] 2020-03-10 10:57
We need it in binary .pcap format.

**Comment by bruno-barin-ifood** [comment] 2020-03-10 11:09
[traffic.txt](https://github.com/scylladb/scylla/files/4312004/traffic.txt)

Please rename it to pcap extension as Github does not support that format for file upload.

**Comment by avikivity** [comment] 2020-03-11 17:13
It looks like a driver bug. The driver keeps sending statements and ignores the error. The correct response is to re-prepare the statement, but the driver makes no attempt to do so.

**Comment by bruno-barin-ifood** [comment] 2020-03-12 16:24
I've filled a ticket for the rust driver:

https://github.com/AlexPikalov/cdrs/issues/318

Indeed seems to be a problem with the driver

**Comment by psarna** [comment] 2021-08-16 07:33
The issue in the driver was closed, so I'm closing this one too. We also have https://github.com/scylladb/scylla-rust-driver now, and it does not have this problem

**Closed by psarna** 2021-08-16 07:33 UTC
