### ISSUE TITLE
replace_with_repair failed during terminate_and_replace_node nemesis

### ISSUE THREAD

**Issue by fgelcer** [scylladb/scylla#6182] opened 2020-04-12 19:03 UTC
running version ```4.0.rc0-0.20200405.511773d4662```
```
Scylla version 4.0.rc0-0.20200405.511773d4662 with build-id de88161d63d02e10ad1b3f2a761cb15aee71d8c9
```

nemesis run to terminate node-2:
```
longevity-tls-1tb-7d-4-0-db-node-bbc128f5-2 [54.76.112.9 | 10.0.56.93]
```

and replaces it with with node-7:
```
longevity-tls-1tb-7d-4-0-db-node-bbc128f5-7 [52.51.234.138 | 10.0.97.178]
```

after running repair for a while:
```
repair - repair id 1 to sync data for keyspace=system_traces, status=started
```

here the message when it fails:
```
Startup failed: std::runtime_error ({shard 0: std::runtime_error (repair 1 on shard 0 failed to do checksum for 163 sub ranges), shard 1: std::runtime_error (repair 1 on shard 1 failed to do checksum for 163 sub ranges), shard 2: std::runtime_error (repair 1 on shard 2 failed to do checksum for 163 sub ranges), shard 3: std::runtime_error (repair 1 on shard 3 failed to do checksum for 163 sub ranges), shard 4: std::runtime_error (repair 1 on shard 4 failed to do checksum for 163 sub ranges), shard 5: std::runtime_error (repair 1 on shard 5 failed to do checksum for 163 sub ranges), shard 6: std::runtime_error (repair 1 on shard 6 failed to do checksum for 163 sub ranges), shard 7: std::runtime_error (repair 1 on shard 7 failed to do checksum for 163 sub ranges), shard 8: std::runtime_error (repair 1 on shard 8 failed to do checksum for 163 sub ranges), shard 9: std::runtime_error (repair 1 on shard 9 failed to do checksum for 163 sub ranges), shard 10: std::runtime_error (repair 1 on shard 10 failed to do checksum for 163 sub ranges), shard 11: std::runtime_error (repair 1 on shard 11 failed to do checksum for 163 sub ranges), shard 12: std::runtime_error (repair 1 on shard 12 failed to do checksum for 163 sub ranges), shard 13: std::runtime_error (repair 1 on shard 13 failed to do checksum for 163 sub ranges)})
```

here the logs can be found:
```
+--------------------------------------------------------------------------------------------------------------------------------------------+
|                                      Collected logs by test-id: bbc128f5-0097-4db4-9327-d46c7d8e73a2                                       |
+-------------+------------------------------------------------------------------------------------------------------------------------------+
| Cluster set | Link                                                                                                                         |
+-------------+------------------------------------------------------------------------------------------------------------------------------+
| db-cluster  | https://cloudius-jenkins-test.s3.amazonaws.com/bbc128f5-0097-4db4-9327-d46c7d8e73a2/20200412_105848/db-cluster-bbc128f5.zip  |
| monitor-set | https://cloudius-jenkins-test.s3.amazonaws.com/bbc128f5-0097-4db4-9327-d46c7d8e73a2/20200412_105848/monitor-set-bbc128f5.zip |
| loader-set  | None                                                                                                                         |
| sct-runner  | https://cloudius-jenkins-test.s3.amazonaws.com/bbc128f5-0097-4db4-9327-d46c7d8e73a2/20200412_105848/sct-runner-bbc128f5.zip  |
+-------------+------------------------------------------------------------------------------------------------------------------------------+
```

**Comment by fgelcer** [comment] 2020-04-12 19:27
@slivne , this is the issue we found during the 1TB longevity on 4.0

**Comment by roydahan** [comment] 2020-04-12 19:44
The repair didn't run for a while, it failed immediately.
All the messages for all the ranges are from the same time.

**Comment by slivne** [comment] 2020-04-13 15:17
failed - it could be related to auto_bootstrap: false, QA are not sure

**Comment by asias** [comment] 2020-04-14 05:52
db-cluster-bbc128f5.zip is 3.8GB in size. it took 30 minutes to download the log at ~3MB/s.  Is it possible to zip and upload the scylla db log separately in sct?

**Comment by fgelcer** [comment] 2020-04-14 06:05
> db-cluster-bbc128f5.zip is 3.8GB in size. it took 30 minutes to download the log at ~3MB/s. Is it possible to zip and upload the scylla db log separately in sct?

that's actually a good idea.
@aleksbykov / @bentsi ?

**Comment by asias** [comment] 2020-04-14 06:33
> > db-cluster-bbc128f5.zip is 3.8GB in size. it took 30 minutes to download the log at ~3MB/s. Is it possible to zip and upload the scylla db log separately in sct?
> 
> that's actually a good idea.
> @aleksbykov / @bentsi ?

The download failed in the middle, so I need to do it again ;(

We can also use better compression like xz instead zip to reduce the size further.

**Comment by asias** [comment] 2020-04-15 07:36
The replace operation failed because node3 is not alive. 

```
5554 2020-04-11T18:22:41+00:00  longevity-tls-1tb-7d-4-0-db-node-bbc128f5-7 !WARNING | scylla: [shard 6] repair - Repair 512 out of 516 ranges, id=1, shard=6, keyspace=system_traces, table={events, node_slow_log_time_idx, sessions,      node_slow_log, sessions_time_idx}, range=(9082781706294754991, 9097748169532748665], peers={10.0.232.236}, live_peers={}, status=skipped
5555 2020-04-11T18:22:41+00:00  longevity-tls-1tb-7d-4-0-db-node-bbc128f5-7 !WARNING | scylla: [shard 6] repair - Repair 516 out of 516 ranges, id=1, shard=6, keyspace=system_traces, table={events, node_slow_log_time_idx, sessions,      node_slow_log, sessions_time_idx}, range=(9183480562362632769, 9187618707688297286], peers={10.0.232.236}, live_peers={}, status=skipped
5556 2020-04-11T18:22:41+00:00  longevity-tls-1tb-7d-4-0-db-node-bbc128f5-7 !WARNING | scylla: [shard 0] gossip - No local state or state is in silent shutdown, not announcing shutdown
5557 2020-04-11T18:22:41+00:00  longevity-tls-1tb-7d-4-0-db-node-bbc128f5-7 !ERR     | scylla: [shard 0] init - Startup failed: std::runtime_error ({shard 0: std::runtime_error (repair 1 on shard 0 failed to do checksum for 163 sub      ranges), shard 1: std::runtime_error (repair 1 on shard 1 failed to do checksum for 163 sub ranges), shard 2: std::runtime_error (repair 1 on shard 2 failed to do checksum for 163 sub ranges), shard 3: std::runtime_error (rep     air 1 on shard 3 failed to do checksum for 163 sub ranges), shard 4: std::runtime_error (repair 1 on shard 4 failed to do checksum for 163 sub ranges), shard 5: std::runtime_error (repair 1 on shard 5 failed to do checksum for      163 sub ranges), shard 6: std::runtime_error (repair 1 on shard 6 failed to do checksum for 163 sub ranges), shard 7: std::runtime_error (repair 1 on shard 7 failed to do checksum for 163 sub ranges), shard 8: std::runtime_er     ror (repair 1 on shard 8 failed to do checksum for 163 sub ranges), shard 9: std::runtime_error (repair 1 on shard 9 failed to do checksum for 163 sub ranges), shard 10: std::runtime_error (repair 1 on shard 10 failed to do ch     ecksum for 163 sub ranges), shard 11: std::runtime_error (repair 1 on shard 11 failed to do checksum for 163 sub ranges), shard 12: std::runtime_error (repair 1 on shard 12 failed to do checksum for 163 sub ranges), shard 13:      std::runtime_error (repair 1 on shard 13 failed to do checksum for 163 sub ranges)})
```

Node 7 see node3 is down:
 
```
[asias@hjpc2 issue.6182]$ cat 7|grep 10.0.232.236|grep -v repair
2020-04-11T18:21:26+00:00  longevity-tls-1tb-7d-4-0-db-node-bbc128f5-7 !INFO    | scylla: [shard 0] rpc - client 10.0.232.236:7001: fail to connect: Connection refused
2020-04-11T18:21:26+00:00  longevity-tls-1tb-7d-4-0-db-node-bbc128f5-7 !WARNING | scylla: [shard 0] gossip - Fail to send EchoMessage to 10.0.232.236: seastar::rpc::closed_error (connection is closed)
2020-04-11T18:21:26+00:00  longevity-tls-1tb-7d-4-0-db-node-bbc128f5-7 !INFO    | scylla: [shard 0] gossip - InetAddress 10.0.232.236 is now DOWN, status = shutdown
2020-04-11T18:21:27+00:00  longevity-tls-1tb-7d-4-0-db-node-bbc128f5-7 !INFO    | scylla: [shard 0] rpc - client 10.0.232.236:7001: fail to connect: Connection refused
2020-04-11T18:21:34+00:00  longevity-tls-1tb-7d-4-0-db-node-bbc128f5-7 !INFO    | scylla: [shard 0] rpc - client 10.0.232.236:7001: fail to connect: Connection refused
2020-04-11T18:21:36+00:00  longevity-tls-1tb-7d-4-0-db-node-bbc128f5-7 !INFO    | scylla: [shard 0] rpc - client 10.0.232.236:7001: fail to connect: Connection refused
2020-04-11T18:21:38+00:00  longevity-tls-1tb-7d-4-0-db-node-bbc128f5-7 !WARNING | scylla: [shard 0] migration_task - Can't send migration request: node 10.0.232.236 is down.
2020-04-11T18:21:38+00:00  longevity-tls-1tb-7d-4-0-db-node-bbc128f5-7 !WARNING | scylla: [shard 0] migration_task - Can't send migration request: node 10.0.232.236 is down.
2020-04-11T18:21:39+00:00  longevity-tls-1tb-7d-4-0-db-node-bbc128f5-7 !INFO    | scylla: [shard 0] rpc - client 10.0.232.236:7001: fail to connect: Connection refused
2020-04-11T18:21:49+00:00  longevity-tls-1tb-7d-4-0-db-node-bbc128f5-7 !INFO    | scylla: [shard 0] rpc - client 10.0.232.236:7001: fail to connect: Connection refused
2020-04-11T18:21:50+00:00  longevity-tls-1tb-7d-4-0-db-node-bbc128f5-7 !INFO    | scylla: [shard 0] rpc - client 10.0.232.236:7001: fail to connect: Connection refused
2020-04-11T18:21:55+00:00  longevity-tls-1tb-7d-4-0-db-node-bbc128f5-7 !INFO    | scylla: [shard 0] rpc - client 10.0.232.236:7001: fail to connect: Connection refused
2020-04-11T18:21:57+00:00  longevity-tls-1tb-7d-4-0-db-node-bbc128f5-7 !INFO    | scylla: [shard 0] rpc - client 10.0.232.236:7001: fail to connect: Connection refused
2020-04-11T18:22:00+00:00  longevity-tls-1tb-7d-4-0-db-node-bbc128f5-7 !INFO    | scylla: [shard 0] rpc - client 10.0.232.236:7001: fail to connect: Connection refused
2020-04-11T18:22:02+00:00  longevity-tls-1tb-7d-4-0-db-node-bbc128f5-7 !INFO    | scylla: [shard 0] rpc - client 10.0.232.236:7001: fail to connect: Connection refused
2020-04-11T18:22:06+00:00  longevity-tls-1tb-7d-4-0-db-node-bbc128f5-7 !INFO    | scylla: [shard 0] rpc - client 10.0.232.236:7001: fail to connect: Connection refused
2020-04-11T18:22:09+00:00  longevity-tls-1tb-7d-4-0-db-node-bbc128f5-7 !INFO    | scylla: [shard 0] rpc - client 10.0.232.236:7001: fail to connect: Connection refused
2020-04-11T18:22:11+00:00  longevity-tls-1tb-7d-4-0-db-node-bbc128f5-7 !INFO    | scylla: [shard 0] rpc - client 10.0.232.236:7001: fail to connect: Connection refused
2020-04-11T18:22:16+00:00  longevity-tls-1tb-7d-4-0-db-node-bbc128f5-7 !INFO    | scylla: [shard 0] rpc - client 10.0.232.236:7001: fail to connect: Connection refused
2020-04-11T18:22:17+00:00  longevity-tls-1tb-7d-4-0-db-node-bbc128f5-7 !INFO    | scylla: [shard 0] rpc - client 10.0.232.236:7001: fail to connect: Connection refused
2020-04-11T18:22:18+00:00  longevity-tls-1tb-7d-4-0-db-node-bbc128f5-7 !INFO    | scylla: [shard 0] rpc - client 10.0.232.236:7001: fail to connect: Connection refused
2020-04-11T18:22:19+00:00  longevity-tls-1tb-7d-4-0-db-node-bbc128f5-7 !INFO    | scylla: [shard 0] rpc - client 10.0.232.236:7001: fail to connect: Connection refused
2020-04-11T18:22:22+00:00  longevity-tls-1tb-7d-4-0-db-node-bbc128f5-7 !INFO    | scylla: [shard 0] rpc - client 10.0.232.236:7001: fail to connect: Connection refused
2020-04-11T18:22:29+00:00  longevity-tls-1tb-7d-4-0-db-node-bbc128f5-7 !INFO    | scylla: [shard 0] rpc - client 10.0.232.236:7001: fail to connect: Connection refused
2020-04-11T18:22:39+00:00  longevity-tls-1tb-7d-4-0-db-node-bbc128f5-7 !INFO    | scylla: [shard 0] gossip - Known endpoints=[10.0.56.93, 10.0.232.236, 10.0.147.29, 10.0.4.221, 10.0.97.178], current_seeds={10.0.4.221}, seeds_from_config={10.0.4.221}, seen_any_seed=1
```

Before the replace operation, node3 were overwhelmed by the view update failure. 
```
272568 2020-04-11T17:11:33+00:00  longevity-tls-1tb-7d-4-0-db-node-bbc128f5-3 !WARNING | scylla: [shard 3] seastar - Exceptional future ignored: exceptions::mutation_write_timeout_exception (Operation timed out for mview.users_by_f       irst_name - received only 0 responses from 1 CL=ANY.), backtrace:   0x331aecd#012  0x2e31b67#012  0x1d6fb94#012  0x2e7b840#012  0x2e7ba4f#012  0x2eb39f5#012  0x2ec201c#012  0x2e4d70d#012  /opt/scylladb/libreloc/libpthread.so       .0+0x94e1#012  /opt/scylladb/libreloc/libc.so.6+0x1016d2
272569 2020-04-11T17:11:33+00:00  longevity-tls-1tb-7d-4-0-db-node-bbc128f5-3 !ERR     | scylla: [shard 0] view - Error applying view update to 10.0.56.93: exceptions::mutation_write_timeout_exception (Operation timed out for mview       .users_by_last_name - received only 0 responses from 1 CL=ANY.)
272570 2020-04-11T17:11:33+00:00  longevity-tls-1tb-7d-4-0-db-node-bbc128f5-3 !WARNING | scylla: [shard 0] seastar - Exceptional future ignored: exceptions::mutation_write_timeout_exception (Operation timed out for mview.users_by_l       ast_name - received only 0 responses from 1 CL=ANY.), backtrace:   0x331aecd#012  0x2e31b67#012  0x1d6fb94#012  0x2e7b840#012  0x2e7ba4f#012  0x2eb39f5#012  0x2e195f7#012  0x2e1a72e#012  0xd006b7#012  /opt/scylladb/libreloc/       libc.so.6+0x271a2#012  0xc1c02d
272571 2020-04-11T17:11:33+00:00  longevity-tls-1tb-7d-4-0-db-node-bbc128f5-3 !ERR     | scylla: [shard 4] view - Error applying view update to 10.0.56.93: exceptions::mutation_write_timeout_exception (Operation timed out for mview       .users_by_first_name - received only 0 responses from 1 CL=ANY.)
272572 2020-04-11T17:11:33+00:00  longevity-tls-1tb-7d-4-0-db-node-bbc128f5-3 !WARNING | scylla: [shard 4] seastar - Exceptional future ignored: exceptions::mutation_write_timeout_exception (Operation timed out for mview.users_by_f       irst_name - received only 0 responses from 1 CL=ANY.), backtrace:   0x331aecd#012  0x2e31b67#012  0x1d6fb94#012  0x2e7b840#012  0x2e7ba4f#012  0x2eb39f5#012  0x2ec201c#012  0x2e4d70d#012  /opt/scylladb/libreloc/libpthread.so       .0+0x94e1#012  /opt/scylladb/libreloc/libc.so.6+0x1016d2
272573 2020-04-11T17:11:33+00:00  longevity-tls-1tb-7d-4-0-db-node-bbc128f5-3 !ERR     | scylla: [shard 9] view - Error applying view update to 10.0.56.93: exceptions::mutation_write_timeout_exception (Operation timed out for mview       .users_by_last_name - received only 0 responses from 1 CL=ANY.)
```

No log on node 3 during the replacing operation:

```
2228 2020-04-11T17:21:51+00:00  longevity-tls-1tb-7d-4-0-db-node-bbc128f5-3 !INFO    | scylla: [shard 0] rpc - client 10.0.56.93:7001: fail to connect: No route to host
42229 2020-04-11T17:21:58+00:00  longevity-tls-1tb-7d-4-0-db-node-bbc128f5-3 !INFO    | scylla: [shard 0] rpc - client 10.0.56.93:7001: fail to connect: No route to host
42230 2020-04-11T17:22:07+00:00  longevity-tls-1tb-7d-4-0-db-node-bbc128f5-3 !INFO    | scylla: [shard 0] rpc - client 10.0.56.93:7001: fail to connect: No route to host
42231 2020-04-11T17:22:15+00:00  longevity-tls-1tb-7d-4-0-db-node-bbc128f5-3 !INFO    | scylla: [shard 0] rpc - client 10.0.56.93:7001: fail to connect: No route to host
42232 2020-04-11T17:22:18+00:00  longevity-tls-1tb-7d-4-0-db-node-bbc128f5-3 !INFO    | scylla: [shard 0] rpc - client 10.0.56.93:7001: fail to connect: No route to host
42233 2020-04-11T17:22:27+00:00  longevity-tls-1tb-7d-4-0-db-node-bbc128f5-3 !INFO    | scylla: [shard 0] rpc - client 10.0.56.93:7001: fail to connect: No route to host
42234 2020-04-11T17:22:35+00:00  longevity-tls-1tb-7d-4-0-db-node-bbc128f5-3 !INFO    | scylla: [shard 0] rpc - client 10.0.56.93:7001: fail to connect: No route to host
42235 2020-04-11T17:22:38+00:00  longevity-tls-1tb-7d-4-0-db-node-bbc128f5-3 !INFO    | scylla: [shard 0] rpc - client 10.0.56.93:7001: fail to connect: No route to host
42236 2020-04-11T17:22:48+00:00  longevity-tls-1tb-7d-4-0-db-node-bbc128f5-3 !INFO    | scylla: [shard 0] rpc - client 10.0.56.93:7001: fail to connect: No route to host
42237 2020-04-11T17:23:00+00:00  longevity-tls-1tb-7d-4-0-db-node-bbc128f5-3 !INFO    | scylla: [shard 0] rpc - client 10.0.56.93:7001: fail to connect: No route to host
42238 2020-04-11T17:23:09+00:00  longevity-tls-1tb-7d-4-0-db-node-bbc128f5-3 !INFO    | scylla: [shard 0] rpc - client 10.0.56.93:7001: fail to connect: No route to host
42239 2020-04-11T17:23:12+00:00  longevity-tls-1tb-7d-4-0-db-node-bbc128f5-3 !INFO    | scylla: [shard 0] rpc - client 10.0.56.93:7001: fail to connect: No route to host
42240 2020-04-11T17:23:15+00:00  longevity-tls-1tb-7d-4-0-db-node-bbc128f5-3 !INFO    | scylla: [shard 0] rpc - client 10.0.56.93:7001: fail to connect: No route to host
42241 2020-04-11T17:23:25+00:00  longevity-tls-1tb-7d-4-0-db-node-bbc128f5-3 !INFO    | scylla: [shard 0] rpc - client 10.0.56.93:7001: fail to connect: No route to host
42242 2020-04-11T17:23:28+00:00  longevity-tls-1tb-7d-4-0-db-node-bbc128f5-3 !INFO    | scylla: [shard 0] rpc - client 10.0.56.93:7001: fail to connect: No route to host
42243 2020-04-11T22:25:19+00:00  longevity-tls-1tb-7d-4-0-db-node-bbc128f5-3 !INFO    | scylla: [shard 0] storage_service - DRAINING: starting drain process
42244 2020-04-11T22:25:19+00:00  longevity-tls-1tb-7d-4-0-db-node-bbc128f5-3 !INFO    | scylla: [shard 0] gossip - gossip is already stopped
42245 2020-04-11T22:25:36+00:00  longevity-tls-1tb-7d-4-0-db-node-bbc128f5-3 !INFO    | scylla: [shard 0] migration_manager - stopping migration service
42246 2020-04-11T22:25:36+00:00  longevity-tls-1tb-7d-4-0-db-node-bbc128f5-3 !INFO    | scylla: [shard 1] migration_manager - stopping migration service
42247 2020-04-11T22:25:36+00:00  longevity-tls-1tb-7d-4-0-db-node-bbc128f5-3 !INFO    | scylla: [shard 5] migration_manager - stopping migration service
42248 2020-04-11T22:25:36+00:00  longevity-tls-1tb-7d-4-0-db-node-bbc128f5-3 !INFO    | scylla: [shard 9] migration_manager - stopping migration service
42249 2020-04-11T22:25:36+00:00  longevity-tls-1tb-7d-4-0-db-node-bbc128f5-3 !INFO    | scylla: [shard 2] migration_manager - stopping migration service
42250 2020-04-11T22:25:36+00:00  longevity-tls-1tb-7d-4-0-db-node-bbc128f5-3 !INFO    | scylla: [shard 8] migration_manager - stopping migration service
42251 2020-04-11T22:25:36+00:00  longevity-tls-1tb-7d-4-0-db-node-bbc128f5-3 !INFO    | scylla: [shard 4] migration_manager - stopping migration service
42252 2020-04-11T22:25:36+00:00  longevity-tls-1tb-7d-4-0-db-node-bbc128f5-3 !INFO    | scylla: [shard 6] migration_manager - stopping migration service
42253 2020-04-11T22:25:36+00:00  longevity-tls-1tb-7d-4-0-db-node-bbc128f5-3 !INFO    | scylla: [shard 10] migration_manager - stopping migration service
42254 2020-04-11T22:25:36+00:00  longevity-tls-1tb-7d-4-0-db-node-bbc128f5-3 !INFO    | scylla: [shard 3] migration_manager - stopping migration service
42255 2020-04-11T22:25:36+00:00  longevity-tls-1tb-7d-4-0-db-node-bbc128f5-3 !INFO    | scylla: [shard 12] migration_manager - stopping migration service
42256 2020-04-11T22:25:36+00:00  longevity-tls-1tb-7d-4-0-db-node-bbc128f5-3 !INFO    | scylla: [shard 13] migration_manager - stopping migration service
42257 2020-04-11T22:25:36+00:00  longevity-tls-1tb-7d-4-0-db-node-bbc128f5-3 !INFO    | scylla: [shard 11] migration_manager - stopping migration service
42258 2020-04-11T22:25:36+00:00  longevity-tls-1tb-7d-4-0-db-node-bbc128f5-3 !INFO    | scylla: [shard 7] migration_manager - stopping migration service
42259 2020-04-11T22:25:36+00:00  longevity-tls-1tb-7d-4-0-db-node-bbc128f5-3 !INFO    | scylla: [shard 0] storage_service - DRAINED:
42260 2020-04-11T22:25:38+00:00  longevity-tls-1tb-7d-4-0-db-node-bbc128f5-3 !INFO    | scylla: [shard 0] init - Signal received; shutting down
42261 2020-04-11T22:25:38+00:00  longevity-tls-1tb-7d-4-0-db-node-bbc128f5-3 !INFO    | scylla: [shard 0] init - Shutting down redis service
42262 2020-04-11T22:25:38+00:00  longevity-tls-1tb-7d-4-0-db-node-bbc128f5-3 !INFO    | scylla: [shard 0] init - Shutting down redis service was successful
42263 2020-04-11T22:25:38+00:00  longevity-tls-1tb-7d-4-0-db-node-bbc128f5-3 !INFO    | scylla: [shard 0] init - Shutting down view builder
42264 2020-04-11T22:25:38+00:00  longevity-tls-1tb-7d-4-0-db-node-bbc128f5-3 !INFO    | scylla: [shard 0] view - Stopping view builder
42265 2020-04-11T22:25:38+00:00  longevity-tls-1tb-7d-4-0-db-node-bbc128f5-3 !INFO    | scylla: [shard 1] view - Stopping view builder
42266 2020-04-11T22:25:38+00:00  longevity-tls-1tb-7d-4-0-db-node-bbc128f5-3 !INFO    | scylla: [shard 13] view - Stopping view builder
42267 2020-04-11T22:25:38+00:00  longevity-tls-1tb-7d-4-0-db-node-bbc128f5-3 !INFO    | scylla: [shard 2] view - Stopping view builder
42268 2020-04-11T22:25:38+00:00  longevity-tls-1tb-7d-4-0-db-node-bbc128f5-3 !INFO    | scylla: [shard 9] view - Stopping view builder
42269 2020-04-11T22:25:38+00:00  longevity-tls-1tb-7d-4-0-db-node-bbc128f5-3 !INFO    | scylla: [shard 8] view - Stopping view builder
42270 2020-04-11T22:25:38+00:00  longevity-tls-1tb-7d-4-0-db-node-bbc128f5-3 !INFO    | scylla: [shard 5] view - Stopping view builder
42271 2020-04-11T22:25:38+00:00  longevity-tls-1tb-7d-4-0-db-node-bbc128f5-3 !INFO    | scylla: [shard 12] view - Stopping view builder
42272 2020-04-11T22:25:38+00:00  longevity-tls-1tb-7d-4-0-db-node-bbc128f5-3 !INFO    | scylla: [shard 6] view - Stopping view builder
42273 2020-04-11T22:25:38+00:00  longevity-tls-1tb-7d-4-0-db-node-bbc128f5-3 !INFO    | scylla: [shard 10] view - Stopping view builder
42274 2020-04-11T22:25:38+00:00  longevity-tls-1tb-7d-4-0-db-node-bbc128f5-3 !INFO    | scylla: [shard 7] view - Stopping view builder
42275 2020-04-11T22:25:38+00:00  longevity-tls-1tb-7d-4-0-db-node-bbc128f5-3 !INFO    | scylla: [shard 3] view - Stopping view builder
42276 2020-04-11T22:25:38+00:00  longevity-tls-1tb-7d-4-0-db-node-bbc128f5-3 !INFO    | scylla: [shard 11] view - Stopping view builder
42277 2020-04-11T22:25:38+00:00  longevity-tls-1tb-7d-4-0-db-node-bbc128f5-3 !INFO    | scylla: [shard 4] view - Stopping view builder
42278 2020-04-11T22:25:38+00:00  longevity-tls-1tb-7d-4-0-db-node-bbc128f5-3 !INFO    | scylla: [shard 0] init - Shutting down view builder was successful
```

**Comment by slivne** [comment] 2020-04-15 19:49
@fgelcer did we hit this with auto_bootstrap=false or not ?

@asias whats the next step, this is blocking 4.0

**Comment by asias** [comment] 2020-04-16 01:04
We need to understand why node3 keep sending view updates to 10.0.56.93 which is marked as DOWN already. We need mv experts to have a look.  This seems to cause node3 being unresponsive and being marked as down by the replacing node, which in turn failed the replace operation. 

```
272568 2020-04-11T17:11:33+00:00  longevity-tls-1tb-7d-4-0-db-node-bbc128f5-3 !WARNING | scylla: [shard 3] seastar - Exceptional future ignored: exceptions::mutation_write_timeout_exception (Operation timed out for mview.users_by_f       irst_name - received only 0 responses from 1 CL=ANY.), backtrace:   0x331aecd#012  0x2e31b67#012  0x1d6fb94#012  0x2e7b840#012  0x2e7ba4f#012  0x2eb39f5#012  0x2ec201c#012  0x2e4d70d#012  /opt/scylladb/libreloc/libpthread.so       .0+0x94e1#012  /opt/scylladb/libreloc/libc.so.6+0x1016d2
272569 2020-04-11T17:11:33+00:00  longevity-tls-1tb-7d-4-0-db-node-bbc128f5-3 !ERR     | scylla: [shard 0] view - Error applying view update to 10.0.56.93: exceptions::mutation_write_timeout_exception (Operation timed out for mview       .users_by_last_name - received only 0 responses from 1 CL=ANY.)
```

**Comment by slivne** [comment] 2020-04-16 15:45
@eliransin - Asias has a question about MV sending updated after the node is marked as DOWN (it may also be HH I guess).

Can you have someone loo at this.

**Comment by eliransin** [comment] 2020-04-19 07:03
@psarna can you please try to answer @asias question? https://github.com/scylladb/scylla/issues/6182#issuecomment-614354894

**Comment by psarna** [comment] 2020-04-19 08:23
@asias it doesn't seem particularly weird, since generating view updates is asynchronous - the view builder might have been in the middle of processing view updates when the node was announced as DOWN, so it still tried to send some updates to the endpoint, but failed. It shouldn't cause the node to be unresponsive at all though - view update generation has low parallelism and is throttled...
I'll download and browse the logs, but  I think that the MV failures are just another symptom of this problem (whatever it is), not a root cause.

**Comment by fgelcer** [comment] 2020-04-19 08:26
> @fgelcer did we hit this with auto_bootstrap=false or not ?

yes, we are still not able to run the setup with auto_bootstrap=true... I sent a patch last week, but it still didn't fix it, and I will try with another patch that I want to send today.

> 
> @asias whats the next step, this is blocking 4.0

**Comment by fgelcer** [comment] 2020-04-19 13:19
> > @fgelcer did we hit this with auto_bootstrap=false or not ?
> 
> yes, we are still not able to run the setup with auto_bootstrap=true... I sent a patch last week, but it still didn't fix it, and I will try with another patch that I want to send today.
> 
> > @asias whats the next step, this is blocking 4.0

@slivne / @asias , to make our side clear about auto_bootstrap (we have cleared it today during our QA meeting):
we start the cluster (in this test) with 4 nodes, and all of them are set with auto_bootstrap: false.

every node that joins the cluster afterwards (either terminate and replace, or decommission) are set with auto_bootstrap: true.

**Comment by fgelcer** [comment] 2020-04-28 12:40
i'm seeing something very similar when running on longevity-large-collections job, test_id=d643b9a8-78ac-48e4-b80c-0c268c03f802:
```
2020-04-27T04:09:32+00:00  longevity-large-collections-12h-4-0-db-node-d643b9a8-5 !INFO    | scylla: [shard 1] repair - Got error in row level repair: seastar::rpc::closed_error (connection is closed)
2020-04-27T04:09:32+00:00  longevity-large-collections-12h-4-0-db-node-d643b9a8-5 !INFO    | scylla: [shard 12] repair - Got error in row level repair: seastar::rpc::closed_error (connection is closed)
2020-04-27T04:09:33+00:00  longevity-large-collections-12h-4-0-db-node-d643b9a8-5 !WARNING | scylla: [shard 11] seastar - Exceptional future ignored: seastar::rpc::closed_error (connection is closed), backtrace:   0x3315d9d#012  0x2e2bfc7#012  0xc61cd6#012  0x253d6f2#012  0x253f210#012  0x254289c#012  0x2544696#012  0x31365bc
2020-04-27T04:09:33+00:00  longevity-large-collections-12h-4-0-db-node-d643b9a8-5 !INFO    | scylla: [shard 11] repair - Got error in row level repair: seastar::rpc::stream_closed (rpc stream was closed by peer)
2020-04-27T04:09:37+00:00  longevity-large-collections-12h-4-0-db-node-d643b9a8-5 !INFO    | scylla: [shard 11] repair - Got error in row level repair: seastar::rpc::stream_closed (rpc stream was closed by peer)
```

now, i see at some point that we lost communication with node-3:
```
2020-04-27T04:09:35+00:00  longevity-large-collections-12h-4-0-db-node-d643b9a8-5 !INFO    | scylla: [shard 0] gossip - InetAddress 10.0.39.45 is now DOWN, status = shutdown
2020-04-27T04:09:37+00:00  longevity-large-collections-12h-4-0-db-node-d643b9a8-5 !INFO    | scylla: [shard 11] rpc - client 10.0.39.45:7000: fail to connect: Connection refused
2020-04-27T04:09:37+00:00  longevity-large-collections-12h-4-0-db-node-d643b9a8-5 !INFO    | scylla: [shard 11] repair - Got error in row level repair: seastar::rpc::closed_error (connection is closed)
2020-04-27T04:09:37+00:00  longevity-large-collections-12h-4-0-db-node-d643b9a8-5 !INFO    | scylla: [shard 11] rpc - client 10.0.39.45:7000: fail to connect: Connection refused
```

from node-3 log:
```
2020-04-27T04:09:32+00:00  longevity-large-collections-12h-4-0-db-node-d643b9a8-3 !WARNING | scylla: [shard 2] storage_service - Shutting down communications due to I/O errors until operator intervention
2020-04-27T04:09:32+00:00  longevity-large-collections-12h-4-0-db-node-d643b9a8-3 !WARNING | scylla: [shard 2] storage_service - Disk error: std::system_error (error system:28, No space left on device)
2020-04-27T04:09:32+00:00  longevity-large-collections-12h-4-0-db-node-d643b9a8-3 !INFO    | scylla: [shard 0] storage_service - Stop transport: starts
2020-04-27T04:09:32+00:00  longevity-large-collections-12h-4-0-db-node-d643b9a8-3 !INFO    | scylla: [shard 0] storage_service - Thrift server stopped
```

This "No space left on device" sounds very strange to me. No ENOSPC nemesis in this execution.
There is no monitor data collected from this build, hence i have no way to confirm what happened.

logs:
https://cloudius-jenkins-test.s3.amazonaws.com/d643b9a8-78ac-48e4-b80c-0c268c03f802/20200427_074743/db-cluster-d643b9a8.zip
https://cloudius-jenkins-test.s3.amazonaws.com/d643b9a8-78ac-48e4-b80c-0c268c03f802/20200427_074743/sct-runner-d643b9a8.zip

**Comment by slivne** [comment] 2020-04-30 15:24
- @asias lets go back to this one - not that you solved the stuck repairs issues.

- @fgelcer lets check if this reproduced on 4.0.rc3

**Comment by fgelcer** [comment] 2020-05-05 14:49
> * @asias lets go back to this one - now that you solved the stuck repairs issues.
> * @fgelcer lets check if this reproduced on 4.0.rc3

it was related to repair based operations, no?

on `4.0.rc3-0.20200501.eee4c00e29` we have `terminate and replace` succeeded twice:
```
< t:2020-05-04 19:01:50,547 f:sct_events.py   l:886  c:sdcm.sct_events      p:INFO  > 2020-05-04 19:01:50.535: (DisruptionEvent Severity.NORMAL): type=start name=TerminateAndReplaceNode node=Node longevity-tls-1tb-7d-longevit-db-node-3e6cca86-4 [34.248.62.236 | 10.0.140.213] (seed: False) duration=None
< t:2020-05-05 04:31:23,753 f:sct_events.py   l:886  c:sdcm.sct_events      p:INFO  > 2020-05-05 04:31:23.741: (DisruptionEvent Severity.NORMAL): type=end name=TerminateAndReplaceNode node=Node longevity-tls-1tb-7d-longevit-db-node-3e6cca86-4 [34.248.62.236 | 10.0.140.213] (seed: False) duration=34173
< t:2020-05-05 05:06:13,675 f:sct_events.py   l:886  c:sdcm.sct_events      p:INFO  > 2020-05-05 05:06:13.663: (DisruptionEvent Severity.NORMAL): type=start name=TerminateAndReplaceNode node=Node longevity-tls-1tb-7d-longevit-db-node-3e6cca86-3 [34.245.135.207 | 10.0.142.195] (seed: False) duration=None
< t:2020-05-05 14:32:15,909 f:sct_events.py   l:886  c:sdcm.sct_events      p:INFO  > 2020-05-05 14:32:15.898: (DisruptionEvent Severity.NORMAL): type=end name=TerminateAndReplaceNode node=Node longevity-tls-1tb-7d-longevit-db-node-3e6cca86-3 [34.245.135.207 | 10.0.142.195] (seed: False) duration=33963
```

**Comment by slivne** [comment] 2020-05-24 09:46
closing this issue if we hit this in 4.1 (that has repair-vased-operations enabled) - please create a new issue

**Closed by slivne** 2020-05-24 09:46 UTC
Labels: bug, high, repair-based-operations
