### ISSUE TITLE
Seeting default Replication Strategy to NetworkTopologyStrategy

### ISSUE THREAD

**Issue by gcarmin** [scylladb/scylla#9526] opened 2021-10-27 08:50 UTC
In Scylla the default Replication Strategy is `simplestrategy`. 
This does not comply with our recommendation to always use `NetworkTopologyStrategy`, as this is suitable for multi-AZ/Multi-DC environment.
This should be apply to ALL user data KS's and to  `system_distributed`, `system_traces` and `system_auth`  system KS's.

**Comment by eliransin** [comment] 2021-11-16 12:25
@nyh can you remind me why haven't we done this already?
I remember a long debate but I don't remember what came out of it, do you?

**Comment by nyh** [comment] 2021-11-16 14:23
@tzach @gcarmin @eliransin  I think this is a duplicate of #8892.
Please consider if we should close this issue as a duplicate or if there's something missing from 8892?

@eliransin as to why this never happened - this is what is so frustrating about the "safe mode" work - it's so easy to bikeshed, that nothing ever makes progress :-(

**Comment by nyh** [comment] 2021-11-16 14:33
@gcarmin also, going back to the original premise of your issue, that 

> In Scylla the default Replication Strategy is `simplestrategy`.

This isn't actually true for user-created tables. There is **no** default replication strategy for user-created keyspaces. When you create a keyspace, you must specify its replication strategy explicitly.

The point of issue #8892 was that because there is no default, people copy bad examples from the Web - so what that issues proposes is that we should add a default, and let people use it instead of explicitly specifying the (wrong) replication strategy.

However, you are right that system tables do have a default:

> This should be apply to ALL user data KS's and to `system_distributed`, `system_traces` and `system_auth` system KS's.

This is issue #8582

So I'm closing this issue as a duplicate of #8892 and #8582. If you want this done, please prioritize those issues.

**Closed by nyh** 2021-11-16 14:33 UTC
