### ISSUE TITLE
scylla3.1-rc2 docker fails to start

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#4704] opened 2019-07-14 11:50 UTC
Scylla version (or git commit hash): 3.1.rc2

```
docker run --name some-scylla3-31rc2 -d scylladb/scylla:3.1.0.rc2 --smp 1 --memory 750M --overprovisioned 1
```

```
2019-07-14 11:43:54,348 INFO spawned: 'scylla-jmx' with pid 41
2019-07-14 11:43:54,352 INFO spawned: 'scylla' with pid 42
2019-07-14 11:43:54,353 INFO success: node-exporter entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2019-07-14 11:43:54,354 INFO success: sshd entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2019-07-14 11:43:54,359 INFO spawned: 'scylla-housekeeping' with pid 43
2019-07-14 11:43:54,369 INFO exited: scylla-jmx (exit status 127; not expected)
2019-07-14 11:43:54,373 INFO exited: scylla (exit status 127; not expected)
2019-07-14 11:43:54,377 INFO exited: scylla-housekeeping (exit status 127; not expected)
2019-07-14 11:43:56,382 INFO spawned: 'scylla-jmx' with pid 44
2019-07-14 11:43:56,386 INFO spawned: 'scylla' with pid 45
2019-07-14 11:43:56,392 INFO spawned: 'scylla-housekeeping' with pid 46
2019-07-14 11:43:56,403 INFO exited: scylla-jmx (exit status 127; not expected)
2019-07-14 11:43:56,405 INFO exited: scylla (exit status 127; not expected)
2019-07-14 11:43:56,409 INFO exited: scylla-housekeeping (exit status 127; not expected)
2019-07-14 11:43:59,415 INFO spawned: 'scylla-jmx' with pid 47
2019-07-14 11:43:59,420 INFO spawned: 'scylla' with pid 48
2019-07-14 11:43:59,427 INFO spawned: 'scylla-housekeeping' with pid 49
2019-07-14 11:43:59,435 INFO exited: scylla-jmx (exit status 127; not expected)
2019-07-14 11:43:59,443 INFO gave up: scylla-jmx entered FATAL state, too many start retries too quickly
2019-07-14 11:43:59,446 INFO exited: scylla (exit status 127; not expected)
2019-07-14 11:43:59,447 INFO gave up: scylla entered FATAL state, too many start retries too quickly
2019-07-14 11:43:59,449 INFO exited: scylla-housekeeping (exit status 127; not expected)
2019-07-14 11:44:00,450 INFO gave up: scylla-housekeeping entered FATAL state, too many start retries too quickly
```

scylla3.1.0.rc1 works fine

**Comment by hagitsegev** [comment] 2019-07-16 08:21
Docker test also failed:
https://jenkins.scylladb.com/job/scylla-3.1/job/docker-test/label=muninn/3/console

**Comment by penberg** [comment] 2019-07-16 09:01
Looks like `supervisord` lacks permission to launch the services:

```
supervisor: couldn't exec /scylla-jmx-service.sh: EACCES
```

Likely suspect is commit 43bb290705e6b0ea7b248d692fc74f11189d2f75, which updates `supervisord` to run the services as `scylla` user, yet the scripts are readable only by `root`:

```
[root@4e06235b9af2 /]# ls -lh scylla-jmx-service.sh 
-rwx------. 1 root root 106 Jun 19 15:37 scylla-jmx-service.sh
```

/cc @syuu1228

**Comment by slivne** [comment] 2019-07-30 10:37
@syuu1228 ping

**Comment by penberg** [comment] 2019-08-13 12:28
Duplicate of https://github.com/scylladb/scylla/issues/4823

**Closed by penberg** 2019-08-13 12:28 UTC
Labels: Docker, bug, high
