### ISSUE TITLE
Cannot stop and restart scylla AMI

### ISSUE THREAD

**Issue by gleb-cloudius** [scylladb/scylla#364] opened 2015-09-17 09:14 UTC
After restart /data cannot be mounted so boot fails.

**Comment by syuu1228** [comment] 2015-09-28 13:48
I think saw this (only once) after fixing #302, but I'm keep trying to reproduce this from yesterday, it just worked fine, unable to reproduce.

**Comment by syuu1228** [comment] 2015-11-18 07:36
Tried again, doesn't seems reproducible.

**Comment by slivne** [comment] 2015-11-18 07:48
did you use ephermal drives ?

**Comment by syuu1228** [comment] 2015-11-18 07:50
Ah, it was EBS. Maybe related with ephemeral?

**Comment by syuu1228** [comment] 2015-11-18 07:54
Wait, ephemeral disk should erase beyond restart doesn't it?
What should we do for them? Construct RAID0 and format on every boot?
I didn't thinking about it when I wrote RAID initialize script, only tested
with EBS at that time.

**Comment by gleb-cloudius** [comment] 2015-11-18 07:55
On Tue, Nov 17, 2015 at 11:50:32PM -0800, Takuya ASADA wrote:
> Ah, it was EBS. Maybe related with ephemeral?
> 
There is no maybe about it.

--
			Gleb.

**Comment by syuu1228** [comment] 2015-11-18 13:40
On Cassandra AMI which is generated by ComboAMI, it looks disabling EBS entirely, so both root disk and extra disks for RAID are ephemeral. Therefore they won't able to shutdown instance. Only reboot or terminate are allowed. Then this problem won't happen for them. Should we do same way?

**Comment by gleb-cloudius** [comment] 2015-11-18 13:43
On Wed, Nov 18, 2015 at 05:40:22AM -0800, Takuya ASADA wrote:
> On Cassandra AMI which is generated by ComboAMI, it looks disabling EBS entirely, so both root disk and extra disks for RAID are ephemeral. Therefore they won't able to shutdown instance. Only reboot or terminate are allowed. Then this problem won't happen for them. Should we do same way?
> 
It will be absolutely impossible to do development on such AMI. We will
have to have separate development AMI then.

--
			Gleb.

**Comment by syuu1228** [comment] 2015-11-18 13:46
Or we can re-initialize disks on every boot, if extra disks seems ephemeral.

**Comment by gleb-cloudius** [comment] 2015-11-18 13:49
On Wed, Nov 18, 2015 at 05:46:35AM -0800, Takuya ASADA wrote:
> Or we can re-initialize disks on every boot, if extra disks seems ephemeral.
> 
Yes, but what happens if such node tries to reconnect to a cluster it
was part of before stopping? system table is gone, will it be able to
resync it?

--
			Gleb.

**Comment by slivne** [comment] 2015-11-18 13:52
So gleb what is your suggestion then ?

if you are using ephermal drives for storage what can we do ?

**Comment by syuu1228** [comment] 2015-11-18 13:56
On Wed, Nov 18, 2015 at 10:49 PM, Gleb Natapov <notifications@github.com>
wrote:

> On Wed, Nov 18, 2015 at 05:46:35AM -0800, Takuya ASADA wrote:
> > Or we can re-initialize disks on every boot, if extra disks seems
> ephemeral.
> >
> Yes, but what happens if such node tries to reconnect to a cluster it
> was part of before stopping? system table is gone, will it be able to
> resync it?


well, backup it on root disk when shutdown, restore on startup?

**Comment by gleb-cloudius** [comment] 2015-11-18 13:58
On Wed, Nov 18, 2015 at 05:52:33AM -0800, slivne wrote:
> So gleb what is your suggestion then ?
> 
> if you are using ephermal drives for storage what can we do ?
> 
For AMI to be suitable for development restoring raid is good enough.
That what I do now with AMI I built to myself (I do it manually on first
start). We need to verify/consider if this suitable for production AMIs. 
May be two sets of AMIs is inevitable.

--
			Gleb.

**Comment by slivne** [comment] 2015-11-18 14:15
We can not really backup everything on shutdown - its not feasible.

In addition on starting the node again the ips may be different unless we
allocate ips - so the system table ips and info of peers and even
configuration in scylla.yaml will be incorrect - Gleb what do you do to
cope with this ?

I am not sure we really should be able to start a stopped node on AWS that
is using the AMI.

There is a way to replace a node in the cluster (that support changing the
ip) - yet I think this is not really what we want todo in this case.

I think we should split - have a developer backup/restore script that can
be based on whatever Gleb is doing now, and I think we should rather not
allow booting back an instance created with the AMI unless it was initially
started with a flag that will allow this for development

**Comment by syuu1228** [comment] 2015-11-18 17:29
So we split to two AMI, user AMI probably need extra metadeta on AMI
building not to use EBS, what should we do for developer AMI?
Run backup / restore script automatically on shutdown / boot?
Or developer responsible to run it manually

**Comment by slivne** [comment] 2015-11-18 20:50
Lets have a single ami and the user can start it with additional flag of
--development that we can get from the metadata

With regards to what todo - we need some inputs from Gleb.

**Comment by syuu1228** [comment] 2015-11-19 07:11
Single AMI but prevent EBS & stop/restart by default? I think which means
we allow to use EBS which needed for developers,in that way how can you
detect stop/restart? Maybe write some data to somewhere to detect
stop/restart on next bootup?

**Comment by slivne** [comment] 2015-11-19 08:37
The user can use EBS / Ephermal - what ever he chooses, your idea to use a
file is good - we can use to mark that a "backup" has been done to allow a
stop/start incase its needed.

@gleb-cloudius

we need info as to what you want todo after a stop and start
- how do you handle the cahnge in ips
- what do you backup/restore when to start the nde backup.

Lets flush out the details first before you start impl anything.

**Comment by glommer** [comment] 2015-11-20 14:10
I think whoever is using an ephemeral device understand the meaning of the word "ephemeral", right?

That you will lose your data in the node has to be part of the assumption of running ephemeral, and should be done only under situations in which that can be handled gracefully by the cluster (RF>1, so we can fetch data from other nodes)

The biggest problem here is not what happens to data, but that the machine can't be booted again because the raid device does not exist.

Adding the "nofail" switch to fstab makes the machine bootable, but starts pointing scylla to the boot EBS, because the RAID cannot be reassembled - since the new drives will just have standard ext3/4 filesystems, and not a RAID signature:

dadm: looking for devices for /dev/md0
mdadm: No super block found on /dev/xvdb (Expected magic a92b4efc, got 00000401)
mdadm: no RAID superblock on /dev/xvdb
mdadm: No super block found on /dev/xvdc (Expected magic a92b4efc, got 00000401)
mdadm: no RAID superblock on /dev/xvdc

What we really have to do here, is have a systemd service that runs before the data mount phase and assembles the RAID. Let's not worry about backup-before-stop. How do you do that in a machine that crashed anyway?

Long term we will have to have an EBS solution, and that is how people that want their data preserved should run.

**Comment by slivne** [comment] 2015-11-20 15:46
Thanks gleb

How do you handle the change in ips

**Comment by glommer** [comment] 2015-11-20 15:49
The private IP doesn't change for a stop / start cycle. So you handle it by
not referring to the VM by their public IPs

**Comment by slivne** [comment] 2015-11-20 15:50
Sorry,

Thanks glauber

Gleb,Glauber how donyou handle tge change of ip address

**Comment by gleb-cloudius** [comment] 2015-11-20 21:59
On Fri, Nov 20, 2015 at 07:50:19AM -0800, slivne wrote:
> Sorry,
> 
> Thanks glauber
> 
> Gleb,Glauber how donyou handle tge change of ip address
You keep ignoring us saying that private IPs do not change.

--
			Gleb.

**Comment by slivne** [comment] 2015-11-22 07:26
Gleb, Glauber - thanks - the private ip does not change, you are right - I
missed that - I even tested it yesterday in a single DC.

**Closed** 2015-11-24 08:46 UTC
Labels: bug
