### ISSUE TITLE
scylla crashes on latest master AMI with the error message "registering metrics twice for metrics: reactor_io_queue_requests"

### ISSUE THREAD

**Issue by syuu1228** [scylladb/scylla#3727] opened 2018-08-27 11:42 UTC
On latest AMI "scylla_2018-08-26T23-57-31Z (ami-0ed6c58f77af5b56e)" running with i3.4xlarge, scylla crashes following error:
```
Aug 27 11:37:35 ip-172-16-99-144.ec2.internal scylla[5498]: terminate called after throwing an instance of 'std::runtime_error'
Aug 27 11:37:35 ip-172-16-99-144.ec2.internal scylla[5498]: terminate called recursively
Aug 27 11:37:35 ip-172-16-99-144.ec2.internal scylla[5498]: what():  registering metrics twice for metrics: reactor_io_queue_requests
Aug 27 11:37:35 ip-172-16-99-144.ec2.internal scylla[5498]: terminate called recursively
Aug 27 11:37:35 ip-172-16-99-144.ec2.internal scylla[5498]: terminate called recursively
Aug 27 11:37:35 ip-172-16-99-144.ec2.internal scylla[5498]: terminate called recursively
Aug 27 11:37:35 ip-172-16-99-144.ec2.internal scylla[5498]: terminate called recursively
Aug 27 11:37:35 ip-172-16-99-144.ec2.internal scylla[5498]: terminate called recursively
Aug 27 11:37:35 ip-172-16-99-144.ec2.internal scylla[5498]: Aborting on shard 12.
Aug 27 11:37:35 ip-172-16-99-144.ec2.internal scylla[5498]: Backtrace:
Aug 27 11:37:35 ip-172-16-99-144.ec2.internal scylla[5498]: 0x0000000000698e92
Aug 27 11:37:35 ip-172-16-99-144.ec2.internal scylla[5498]: 0x00000000005b073c
Aug 27 11:37:35 ip-172-16-99-144.ec2.internal scylla[5498]: 0x00000000005b09e5
Aug 27 11:37:35 ip-172-16-99-144.ec2.internal scylla[5498]: 0x00000000005b0a93
Aug 27 11:37:35 ip-172-16-99-144.ec2.internal scylla[5498]: /lib64/libpthread.so.0+0x000000000000f6cf
Aug 27 11:37:35 ip-172-16-99-144.ec2.internal scylla[5498]: /lib64/libc.so.6+0x0000000000036276
Aug 27 11:37:35 ip-172-16-99-144.ec2.internal scylla[5498]: /lib64/libc.so.6+0x0000000000037967
Aug 27 11:37:35 ip-172-16-99-144.ec2.internal scylla[5498]: /opt/scylladb/lib64/libstdc++.so.6+0x000000000009253c
Aug 27 11:37:35 ip-172-16-99-144.ec2.internal scylla[5498]: /opt/scylladb/lib64/libstdc++.so.6+0x0000000000090165
Aug 27 11:37:35 ip-172-16-99-144.ec2.internal scylla[5498]: /opt/scylladb/lib64/libstdc++.so.6+0x000000000008f068
Aug 27 11:37:35 ip-172-16-99-144.ec2.internal scylla[5498]: /opt/scylladb/lib64/libstdc++.so.6+0x000000000008fa57
Aug 27 11:37:35 ip-172-16-99-144.ec2.internal scylla[5498]: /opt/scylladb/lib64/libgcc_s.so.1+0x000000000000ff42
Aug 27 11:37:35 ip-172-16-99-144.ec2.internal scylla[5498]: /opt/scylladb/lib64/libgcc_s.so.1+0x000000000001076d
Aug 27 11:37:35 ip-172-16-99-144.ec2.internal scylla[5498]: 0x000000000066584a
Aug 27 11:37:35 ip-172-16-99-144.ec2.internal scylla[5498]: 0x000000000074764d
Aug 27 11:37:35 ip-172-16-99-144.ec2.internal scylla[5498]: /lib64/libpthread.so.0+0x0000000000007e24
Aug 27 11:37:35 ip-172-16-99-144.ec2.internal scylla[5498]: /lib64/libc.so.6+0x00000000000febac
Aug 27 11:37:35 ip-172-16-99-144.ec2.internal scylla[5498]: terminate called recursively
Aug 27 11:37:35 ip-172-16-99-144.ec2.internal scylla[5498]: terminate called recursively
Aug 27 11:37:35 ip-172-16-99-144.ec2.internal scylla[5498]: terminate called recursively
Aug 27 11:37:38 ip-172-16-99-144.ec2.internal systemd-coredump[5541]: Removed old coredump core.scylla.996.ef7f74125fc149439aecd11ff250ad16.5339.1535369639000000.
Aug 27 11:37:41 ip-172-16-99-144.ec2.internal systemd-coredump[5465]: Process 5423 (scylla) of user 996 dumped core.
                                                                      #8  0x000000000066584b _ZZN7seastar3smp9configureEN5boost15program_options13variables_mapEENKUlvE1_clEv (scylla)
                                                                      #9  0x000000000074764e _ZNKSt8functionIFvvEEclEv (scylla)
                                                                      #1  0x00000000006281c6 _ZN7seastar9file_desc4readEPvm (scylla)
                                                                      #1  0x00000000006281c6 _ZN7seastar9file_desc4readEPvm (scylla)
                                                                      #1  0x00000000006281c6 _ZN7seastar9file_desc4readEPvm (scylla)
                                                                      #1  0x00000000006281c6 _ZN7seastar9file_desc4readEPvm (scylla)
                                                                      #1  0x00000000006281c6 _ZN7seastar9file_desc4readEPvm (scylla)
                                                                      #1  0x00000000006281c6 _ZN7seastar9file_desc4readEPvm (scylla)
                                                                      #1  0x0000000000592bed _ZN7seastar11thread_pool4workENS_13basic_sstringIcjLj15ELb1EEE (scylla)
                                                                      #2  0x00000000005b0092 operator() (scylla)
                                                                      #3  0x000000000074764e _ZNKSt8functionIFvvEEclEv (scylla)
                                                                      #1  0x00000000006281c6 _ZN7seastar9file_desc4readEPvm (scylla)
                                                                      #1  0x00000000006281c6 _ZN7seastar9file_desc4readEPvm (scylla)
                                                                      #1  0x00000000006281c6 _ZN7seastar9file_desc4readEPvm (scylla)
                                                                      #1  0x0000000000592bed _ZN7seastar11thread_pool4workENS_13basic_sstringIcjLj15ELb1EEE (scylla)
                                                                      #2  0x00000000005b0092 operator() (scylla)
                                                                      #3  0x000000000074764e _ZNKSt8functionIFvvEEclEv (scylla)
                                                                      #1  0x0000000000592bed _ZN7seastar11thread_pool4workENS_13basic_sstringIcjLj15ELb1EEE (scylla)
                                                                      #2  0x00000000005b0092 operator() (scylla)
                                                                      #3  0x000000000074764e _ZNKSt8functionIFvvEEclEv (scylla)
                                                                      #1  0x0000000000592bed _ZN7seastar11thread_pool4workENS_13basic_sstringIcjLj15ELb1EEE (scylla)
                                                                      #2  0x00000000005b0092 operator() (scylla)
                                                                      #3  0x000000000074764e _ZNKSt8functionIFvvEEclEv (scylla)
                                                                      #9  0x000000000066584b _ZZN7seastar3smp9configureEN5boost15program_options13variables_mapEENKUlvE1_clEv (scylla)
                                                                      #10 0x000000000074764e _ZNKSt8functionIFvvEEclEv (scylla)
                                                                      #8  0x0000000000689d95 _ZN7seastar4util8spinlockD2Ev (scylla)
                                                                      #12 0x000000000058bc7e _start (scylla)
                                                                      #1  0x00000000006281c6 _ZN7seastar9file_desc4readEPvm (scylla)
                                                                      #1  0x00000000006281c6 _ZN7seastar9file_desc4readEPvm (scylla)
                                                                      #1  0x00000000006281c6 _ZN7seastar9file_desc4readEPvm (scylla)
                                                                      #1  0x0000000000592bed _ZN7seastar11thread_pool4workENS_13basic_sstringIcjLj15ELb1EEE (scylla)
                                                                      #2  0x00000000005b0092 operator() (scylla)
                                                                      #3  0x000000000074764e _ZNKSt8functionIFvvEEclEv (scylla)
                                                                      #1  0x0000000000592bed _ZN7seastar11thread_pool4workENS_13basic_sstringIcjLj15ELb1EEE (scylla)
                                                                      #2  0x00000000005b0092 operator() (scylla)
                                                                      #3  0x000000000074764e _ZNKSt8functionIFvvEEclEv (scylla)
                                                                      #1  0x0000000000592bed _ZN7seastar11thread_pool4workENS_13basic_sstringIcjLj15ELb1EEE (scylla)
                                                                      #2  0x00000000005b0092 operator() (scylla)
                                                                      #3  0x000000000074764e _ZNKSt8functionIFvvEEclEv (scylla)
                                                                      #9  0x000000000066584b _ZZN7seastar3smp9configureEN5boost15program_options13variables_mapEENKUlvE1_clEv (scylla)
                                                                      #10 0x000000000074764e _ZNKSt8functionIFvvEEclEv (scylla)
                                                                      #1  0x0000000000592bed _ZN7seastar11thread_pool4workENS_13basic_sstringIcjLj15ELb1EEE (scylla)
                                                                      #2  0x00000000005b0092 operator() (scylla)
                                                                      #3  0x000000000074764e _ZNKSt8functionIFvvEEclEv (scylla)
                                                                      #9  0x000000000066584b _ZZN7seastar3smp9configureEN5boost15program_options13variables_mapEENKUlvE1_clEv (scylla)
                                                                      #10 0x000000000074764e _ZNKSt8functionIFvvEEclEv (scylla)
                                                                      #9  0x000000000066584b _ZZN7seastar3smp9configureEN5boost15program_options13variables_mapEENKUlvE1_clEv (scylla)
                                                                      #10 0x000000000074764e _ZNKSt8functionIFvvEEclEv (scylla)
                                                                      #9  0x000000000066584b _ZZN7seastar3smp9configureEN5boost15program_options13variables_mapEENKUlvE1_clEv (scylla)
                                                                      #10 0x000000000074764e _ZNKSt8functionIFvvEEclEv (scylla)
                                                                      #1  0x0000000000592bed _ZN7seastar11thread_pool4workENS_13basic_sstringIcjLj15ELb1EEE (scylla)
                                                                      #2  0x00000000005b0092 operator() (scylla)
                                                                      #3  0x000000000074764e _ZNKSt8functionIFvvEEclEv (scylla)
                                                                      #1  0x0000000000592bed _ZN7seastar11thread_pool4workENS_13basic_sstringIcjLj15ELb1EEE (scylla)
                                                                      #2  0x00000000005b0092 operator() (scylla)
                                                                      #3  0x000000000074764e _ZNKSt8functionIFvvEEclEv (scylla)
                                                                      #1  0x00000000006281c6 _ZN7seastar9file_desc4readEPvm (scylla)
                                                                      #9  0x000000000066584b _ZZN7seastar3smp9configureEN5boost15program_options13variables_mapEENKUlvE1_clEv (scylla)
                                                                      #10 0x000000000074764e _ZNKSt8functionIFvvEEclEv (scylla)
                                                                      #1  0x0000000000592bed _ZN7seastar11thread_pool4workENS_13basic_sstringIcjLj15ELb1EEE (scylla)
                                                                      #2  0x00000000005b0092 operator() (scylla)
                                                                      #3  0x000000000074764e _ZNKSt8functionIFvvEEclEv (scylla)
                                                                      #1  0x0000000000592bed _ZN7seastar11thread_pool4workENS_13basic_sstringIcjLj15ELb1EEE (scylla)
                                                                      #2  0x00000000005b0092 operator() (scylla)
                                                                      #3  0x000000000074764e _ZNKSt8functionIFvvEEclEv (scylla)
                                                                      #9  0x000000000066584b _ZZN7seastar3smp9configureEN5boost15program_options13variables_mapEENKUlvE1_clEv (scylla)
                                                                      #10 0x000000000074764e _ZNKSt8functionIFvvEEclEv (scylla)
                                                                      #9  0x000000000066584b _ZZN7seastar3smp9configureEN5boost15program_options13variables_mapEENKUlvE1_clEv (scylla)
                                                                      #10 0x000000000074764e _ZNKSt8functionIFvvEEclEv (scylla)
                                                                      #9  0x000000000066584b _ZZN7seastar3smp9configureEN5boost15program_options13variables_mapEENKUlvE1_clEv (scylla)
                                                                      #10 0x000000000074764e _ZNKSt8functionIFvvEEclEv (scylla)
                                                                      #9  0x000000000066584b _ZZN7seastar3smp9configureEN5boost15program_options13variables_mapEENKUlvE1_clEv (scylla)
                                                                      #10 0x000000000074764e _ZNKSt8functionIFvvEEclEv (scylla)
                                                                      #1  0x0000000000592bed _ZN7seastar11thread_pool4workENS_13basic_sstringIcjLj15ELb1EEE (scylla)
                                                                      #2  0x00000000005b0092 operator() (scylla)
                                                                      #3  0x000000000074764e _ZNKSt8functionIFvvEEclEv (scylla)
                                                                      #9  0x000000000066584b _ZZN7seastar3smp9configureEN5boost15program_options13variables_mapEENKUlvE1_clEv (scylla)
                                                                      #10 0x000000000074764e _ZNKSt8functionIFvvEEclEv (scylla)
                                                                      #1  0x00000000006281c6 _ZN7seastar9file_desc4readEPvm (scylla)
                                                                      #1  0x0000000000592bed _ZN7seastar11thread_pool4workENS_13basic_sstringIcjLj15ELb1EEE (scylla)
                                                                      #2  0x00000000005b0092 operator() (scylla)
                                                                      #3  0x000000000074764e _ZNKSt8functionIFvvEEclEv (scylla)
                                                                      #9  0x000000000066584b _ZZN7seastar3smp9configureEN5boost15program_options13variables_mapEENKUlvE1_clEv (scylla)
                                                                      #10 0x000000000074764e _ZNKSt8functionIFvvEEclEv (scylla)
```

**Comment by tgrabiec** [comment] 2018-08-27 12:04
Duplicate of https://github.com/scylladb/scylla/issues/3718

**Closed by tgrabiec** 2018-08-27 12:04 UTC
