### ISSUE TITLE
reactor stalled for 1802 ms after node restarted - while service is starting

### ISSUE THREAD

**Issue by fgelcer** [scylladb/scylla#6192] opened 2020-04-13 19:42 UTC
Installation details
Scylla version (or git commit hash): 4.0.rc0-0.20200405.511773d4662 with build-id de88161d63d02e10ad1b3f2a761cb15aee71d8c9
Cluster size: 4 DB nodes
OS (RHEL/CentOS/Ubuntu/AWS AMI): ami-02ffbefa17e58c217

job running is 1TB 7 days longevity.

node that experienced issue is node-3

```
0x0000000002ed97f2
0x0000000002e7f34b
0x0000000002e7f872
0x0000000002e7fba7
0x00007f2cb0248b1f
0x00007f2cb093bc7b
/opt/scylladb/libreloc/libgmp.so.10+0x000000000001fe3c
/opt/scylladb/libreloc/libgmp.so.10+0x000000000001e02d
/opt/scylladb/libreloc/libgmp.so.10+0x0000000000021e7d
/opt/scylladb/libreloc/libhogweed.so.5+0x000000000000ae9c
/opt/scylladb/libreloc/libhogweed.so.5+0x000000000000f9eb
0x00007f2cb0b1761e
/opt/scylladb/libreloc/libgnutls.so.30+0x000000000004c668
0x000000000322a1c6
0x0000000001f3f3c0
0x00000000024145fa
0x0000000002e7b840
0x0000000002e7ba4f
0x0000000002eb39f5
0x0000000002ec201c
0x0000000002e4d70d
/opt/scylladb/libreloc/libpthread.so.0+0x00000000000094e1
/opt/scylladb/libreloc/libc.so.6+0x00000000001016d2
```

decoded:
```
void seastar::backtrace<seastar::backtrace_buffer::append_backtrace()::{lambda(seastar::frame)#1}>(seastar::backtrace_buffer::append_backtrace()::{lambda(seastar::frame)#1}&&) at /usr/include/fmt/format.h:1158
seastar::backtrace_buffer::append_backtrace() at /usr/include/fmt/format.h:1158
 (inlined by) print_with_backtrace at ./build/release/seastar/./seastar/src/core/reactor.cc:755
seastar::internal::cpu_stall_detector::generate_trace() at /usr/include/fmt/format.h:1158
seastar::internal::cpu_stall_detector::maybe_report() at /usr/include/fmt/format.h:1158
 (inlined by) seastar::internal::cpu_stall_detector::on_signal() at ./build/release/seastar/./seastar/src/core/reactor.cc:1062
 (inlined by) seastar::reactor::block_notifier(int) at ./build/release/seastar/./seastar/src/core/reactor.cc:1185
?? ??:0
?? ??:0
?? ??:0
seastar::tls::dh_params::impl::impl(seastar::tls::dh_params::level) at /usr/include/fmt/format.h:1158
 (inlined by) std::_MakeUniq<seastar::tls::dh_params::impl>::__single_object std::make_unique<seastar::tls::dh_params::impl, seastar::tls::dh_params::level&>(seastar::tls::dh_params::level&) at /usr/include/c++/9/bits/unique_ptr.h:849
 (inlined by) seastar::tls::dh_params::dh_params(seastar::tls::dh_params::level) at ./build/release/seastar/./seastar/src/net/tls.cc:179
 (inlined by) seastar::tls::credentials_builder::build_server_credentials() const at ./build/release/seastar/./seastar/src/net/tls.cc:540
netw::messaging_service::messaging_service(gms::inet_address, unsigned short, netw::messaging_service::encrypt_what, netw::messaging_service::compress_what, netw::messaging_service::tcp_nodelay_what, unsigned short, std::shared_ptr<seastar::tls::credentials_builder>, netw::messaging_service::memory_config, netw::messaging_service::scheduling_config, bool, bool) at /usr/include/c++/9/bits/stl_vector.h:1756
seastar::shared_ptr<netw::messaging_service> seastar::shared_ptr_make_helper<netw::messaging_service, true>::make<gms::inet_address const&, unsigned short&, netw::messaging_service::encrypt_what&, netw::messaging_service::compress_what&, netw::messaging_service::tcp_nodelay_what&, unsigned short&, std::shared_ptr<seastar::tls::credentials_builder>&, netw::messaging_service::memory_config&, netw::messaging_service::scheduling_config&, bool&, bool&>(gms::inet_address const&, unsigned short&, netw::messaging_service::encrypt_what&, netw::messaging_service::compress_what&, netw::messaging_service::tcp_nodelay_what&, unsigned short&, std::shared_ptr<seastar::tls::credentials_builder>&, netw::messaging_service::memory_config&, netw::messaging_service::scheduling_config&, bool&, bool&) at /usr/include/boost/program_options/variables_map.hpp:146
 (inlined by) seastar::shared_ptr<netw::messaging_service> seastar::make_shared<netw::messaging_service, gms::inet_address const&, unsigned short&, netw::messaging_service::encrypt_what&, netw::messaging_service::compress_what&, netw::messaging_service::tcp_nodelay_what&, unsigned short&, std::shared_ptr<seastar::tls::credentials_builder>&, netw::messaging_service::memory_config&, netw::messaging_service::scheduling_config&, bool&, bool&>(gms::inet_address const&, unsigned short&, netw::messaging_service::encrypt_what&, netw::messaging_service::compress_what&, netw::messaging_service::tcp_nodelay_what&, unsigned short&, std::shared_ptr<seastar::tls::credentials_builder>&, netw::messaging_service::memory_config&, netw::messaging_service::scheduling_config&, bool&, bool&) at ././seastar/include/seastar/core/shared_ptr.hh:647
 (inlined by) seastar::shared_ptr<netw::messaging_service> seastar::sharded<netw::messaging_service>::create_local_service<gms::inet_address const&, unsigned short&, netw::messaging_service::encrypt_what&, netw::messaging_service::compress_what&, netw::messaging_service::tcp_nodelay_what&, unsigned short&, std::shared_ptr<seastar::tls::credentials_builder>&, netw::messaging_service::memory_config&, netw::messaging_service::scheduling_config&, bool&, bool&>(gms::inet_address const&, unsigned short&, netw::messaging_service::encrypt_what&, netw::messaging_service::compress_what&, netw::messaging_service::tcp_nodelay_what&, unsigned short&, std::shared_ptr<seastar::tls::credentials_builder>&, netw::messaging_service::memory_config&, netw::messaging_service::scheduling_config&, bool&, bool&) at ././seastar/include/seastar/core/sharded.hh:478
 (inlined by) seastar::future<> seastar::sharded<netw::messaging_service>::start<gms::inet_address const&, unsigned short&, netw::messaging_service::encrypt_what&, netw::messaging_service::compress_what&, netw::messaging_service::tcp_nodelay_what&, unsigned short&, std::shared_ptr<seastar::tls::credentials_builder>&, netw::messaging_service::memory_config&, netw::messaging_service::scheduling_config&, bool&, bool&>(gms::inet_address const&, unsigned short&, netw::messaging_service::encrypt_what&, netw::messaging_service::compress_what&, netw::messaging_service::tcp_nodelay_what&, unsigned short&, std::shared_ptr<seastar::tls::credentials_builder>&, netw::messaging_service::memory_config&, netw::messaging_service::scheduling_config&, bool&, bool&)::{lambda(unsigned int)#1}::operator()(unsigned int)::{lambda()#1}::operator()()::{lambda(gms::inet_address const&, unsigned short&, netw::messaging_service::encrypt_what&, netw::messaging_service::compress_what&, netw::messaging_service::tcp_nodelay_what&, unsigned short&, std::shared_ptr<seastar::tls::credentials_builder>&, netw::messaging_service::memory_config&, netw::messaging_service::scheduling_config&, bool&, bool&)#1}::operator()(gms::inet_address const&, unsigned short&, netw::messaging_service::encrypt_what&, netw::messaging_service::compress_what&, netw::messaging_service::tcp_nodelay_what&, unsigned short&, std::shared_ptr<seastar::tls::credentials_builder>&, netw::messaging_service::memory_config&, netw::messaging_service::scheduling_config&, bool&, bool&) const at ././seastar/include/seastar/core/sharded.hh:543
 (inlined by) seastar::apply_helper<seastar::future<> seastar::sharded<netw::messaging_service>::start<gms::inet_address const&, unsigned short&, netw::messaging_service::encrypt_what&, netw::messaging_service::compress_what&, netw::messaging_service::tcp_nodelay_what&, unsigned short&, std::shared_ptr<seastar::tls::credentials_builder>&, netw::messaging_service::memory_config&, netw::messaging_service::scheduling_config&, bool&, bool&>(gms::inet_address const&, unsigned short&, netw::messaging_service::encrypt_what&, netw::messaging_service::compress_what&, netw::messaging_service::tcp_nodelay_what&, unsigned short&, std::shared_ptr<seastar::tls::credentials_builder>&, netw::messaging_service::memory_config&, netw::messaging_service::scheduling_config&, bool&, bool&)::{lambda(unsigned int)#1}::operator()(unsigned int)::{lambda()#1}::operator()()::{lambda(gms::inet_address const&, unsigned short&, netw::messaging_service::encrypt_what&, netw::messaging_service::compress_what&, netw::messaging_service::tcp_nodelay_what&, unsigned short&, std::shared_ptr<seastar::tls::credentials_builder>&, netw::messaging_service::memory_config&, netw::messaging_service::scheduling_config&, bool&, bool&)#1}, std::tuple<gms::inet_address, unsigned short, netw::messaging_service::encrypt_what, netw::messaging_service::compress_what, netw::messaging_service::tcp_nodelay_what, unsigned short, std::shared_ptr<seastar::tls::credentials_builder>, netw::messaging_service::memory_config, netw::messaging_service::scheduling_config, bool, bool>&, std::integer_sequence<unsigned long, 0ul, 1ul, 2ul, 3ul, 4ul, 5ul, 6ul, 7ul, 8ul, 9ul, 10ul> >::apply({lambda()#1}&&, seastar::future<> seastar::sharded<netw::messaging_service>::start<gms::inet_address const&, unsigned short&, netw::messaging_service::encrypt_what&, netw::messaging_service::compress_what&, netw::messaging_service::tcp_nodelay_what&, unsigned short&, std::shared_ptr<seastar::tls::credentials_builder>&, netw::messaging_service::memory_config&, netw::messaging_service::scheduling_config&, bool&, bool&>(gms::inet_address const&, unsigned short&, netw::messaging_service::encrypt_what&, netw::messaging_service::compress_what&, netw::messaging_service::tcp_nodelay_what&, unsigned short&, std::shared_ptr<seastar::tls::credentials_builder>&, netw::messaging_service::memory_config&, netw::messaging_service::scheduling_config&, bool&, bool&)::{lambda(unsigned int)#1}::operator()(unsigned int)::{lambda()#1}::operator()()::{lambda(gms::inet_address const&, unsigned short&, netw::messaging_service::encrypt_what&, netw::messaging_service::compress_what&, netw::messaging_service::tcp_nodelay_what&, unsigned short&, std::shared_ptr<seastar::tls::credentials_builder>&, netw::messaging_service::memory_config&, netw::messaging_service::scheduling_config&, bool&, bool&)#1}) at ././seastar/include/seastar/core/apply.hh:36
 (inlined by) auto seastar::apply<seastar::future<> seastar::sharded<netw::messaging_service>::start<gms::inet_address const&, unsigned short&, netw::messaging_service::encrypt_what&, netw::messaging_service::compress_what&, netw::messaging_service::tcp_nodelay_what&, unsigned short&, std::shared_ptr<seastar::tls::credentials_builder>&, netw::messaging_service::memory_config&, netw::messaging_service::scheduling_config&, bool&, bool&>(gms::inet_address const&, unsigned short&, netw::messaging_service::encrypt_what&, netw::messaging_service::compress_what&, netw::messaging_service::tcp_nodelay_what&, unsigned short&, std::shared_ptr<seastar::tls::credentials_builder>&, netw::messaging_service::memory_config&, netw::messaging_service::scheduling_config&, bool&, bool&)::{lambda(unsigned int)#1}::operator()(unsigned int)::{lambda()#1}::operator()()::{lambda(gms::inet_address const&, unsigned short&, netw::messaging_service::encrypt_what&, netw::messaging_service::compress_what&, netw::messaging_service::tcp_nodelay_what&, unsigned short&, std::shared_ptr<seastar::tls::credentials_builder>&, netw::messaging_service::memory_config&, netw::messaging_service::scheduling_config&, bool&, bool&)#1}, gms::inet_address, unsigned short, netw::messaging_service::encrypt_what, netw::messaging_service::compress_what, netw::messaging_service::tcp_nodelay_what, unsigned short, std::shared_ptr<seastar::tls::credentials_builder>, netw::messaging_service::memory_config, netw::messaging_service::scheduling_config, bool, bool>(seastar::future<> seastar::sharded<netw::messaging_service>::start<gms::inet_address const&, unsigned short&, netw::messaging_service::encrypt_what&, netw::messaging_service::compress_what&, netw::messaging_service::tcp_nodelay_what&, unsigned short&, std::shared_ptr<seastar::tls::credentials_builder>&, netw::messaging_service::memory_config&, netw::messaging_service::scheduling_config&, bool&, bool&>(gms::inet_address const&, unsigned short&, netw::messaging_service::encrypt_what&, netw::messaging_service::compress_what&, netw::messaging_service::tcp_nodelay_what&, unsigned short&, std::shared_ptr<seastar::tls::credentials_builder>&, netw::messaging_service::memory_config&, netw::messaging_service::scheduling_config&, bool&, bool&)::{lambda(unsigned int)#1}::operator()(unsigned int)::{lambda()#1}::operator()()::{lambda(gms::inet_address const&, unsigned short&, netw::messaging_service::encrypt_what&, netw::messaging_service::compress_what&, netw::messaging_service::tcp_nodelay_what&, unsigned short&, std::shared_ptr<seastar::tls::credentials_builder>&, netw::messaging_service::memory_config&, netw::messaging_service::scheduling_config&, bool&, bool&)#1}&&, std::tuple<gms::inet_address, unsigned short, netw::messaging_service::encrypt_what, netw::messaging_service::compress_what, netw::messaging_service::tcp_nodelay_what, unsigned short, std::shared_ptr<seastar::tls::credentials_builder>, netw::messaging_service::memory_config, netw::messaging_service::scheduling_config, bool, bool>&) at ././seastar/include/seastar/core/apply.hh:51
 (inlined by) seastar::future<> seastar::sharded<netw::messaging_service>::start<gms::inet_address const&, unsigned short&, netw::messaging_service::encrypt_what&, netw::messaging_service::compress_what&, netw::messaging_service::tcp_nodelay_what&, unsigned short&, std::shared_ptr<seastar::tls::credentials_builder>&, netw::messaging_service::memory_config&, netw::messaging_service::scheduling_config&, bool&, bool&>(gms::inet_address const&, unsigned short&, netw::messaging_service::encrypt_what&, netw::messaging_service::compress_what&, netw::messaging_service::tcp_nodelay_what&, unsigned short&, std::shared_ptr<seastar::tls::credentials_builder>&, netw::messaging_service::memory_config&, netw::messaging_service::scheduling_config&, bool&, bool&)::{lambda(unsigned int)#1}::operator()(unsigned int)::{lambda()#1}::operator()() at ././seastar/include/seastar/core/sharded.hh:542
 (inlined by) seastar::future<> seastar::do_void_futurize_helper<void>::apply<seastar::future<> seastar::sharded<netw::messaging_service>::start<gms::inet_address const&, unsigned short&, netw::messaging_service::encrypt_what&, netw::messaging_service::compress_what&, netw::messaging_service::tcp_nodelay_what&, unsigned short&, std::shared_ptr<seastar::tls::credentials_builder>&, netw::messaging_service::memory_config&, netw::messaging_service::scheduling_config&, bool&, bool&>(gms::inet_address const&, unsigned short&, netw::messaging_service::encrypt_what&, netw::messaging_service::compress_what&, netw::messaging_service::tcp_nodelay_what&, unsigned short&, std::shared_ptr<seastar::tls::credentials_builder>&, netw::messaging_service::memory_config&, netw::messaging_service::scheduling_config&, bool&, bool&)::{lambda(unsigned int)#1}::operator()(unsigned int)::{lambda()#1}&>(seastar::future<> seastar::sharded<netw::messaging_service>::start<gms::inet_address const&, unsigned short&, netw::messaging_service::encrypt_what&, netw::messaging_service::compress_what&, netw::messaging_service::tcp_nodelay_what&, unsigned short&, std::shared_ptr<seastar::tls::credentials_builder>&, netw::messaging_service::memory_config&, netw::messaging_service::scheduling_config&, bool&, bool&>(gms::inet_address const&, unsigned short&, netw::messaging_service::encrypt_what&, netw::messaging_service::compress_what&, netw::messaging_service::tcp_nodelay_what&, unsigned short&, std::shared_ptr<seastar::tls::credentials_builder>&, netw::messaging_service::memory_config&, netw::messaging_service::scheduling_config&, bool&, bool&)::{lambda(unsigned int)#1}::operator()(unsigned int)::{lambda()#1}&) at ././seastar/include/seastar/core/future.hh:1608
 (inlined by) seastar::future<> seastar::futurize<void>::apply<seastar::future<> seastar::sharded<netw::messaging_service>::start<gms::inet_address const&, unsigned short&, netw::messaging_service::encrypt_what&, netw::messaging_service::compress_what&, netw::messaging_service::tcp_nodelay_what&, unsigned short&, std::shared_ptr<seastar::tls::credentials_builder>&, netw::messaging_service::memory_config&, netw::messaging_service::scheduling_config&, bool&, bool&>(gms::inet_address const&, unsigned short&, netw::messaging_service::encrypt_what&, netw::messaging_service::compress_what&, netw::messaging_service::tcp_nodelay_what&, unsigned short&, std::shared_ptr<seastar::tls::credentials_builder>&, netw::messaging_service::memory_config&, netw::messaging_service::scheduling_config&, bool&, bool&)::{lambda(unsigned int)#1}::operator()(unsigned int)::{lambda()#1}&>(seastar::future<> seastar::sharded<netw::messaging_service>::start<gms::inet_address const&, unsigned short&, netw::messaging_service::encrypt_what&, netw::messaging_service::compress_what&, netw::messaging_service::tcp_nodelay_what&, unsigned short&, std::shared_ptr<seastar::tls::credentials_builder>&, netw::messaging_service::memory_config&, netw::messaging_service::scheduling_config&, bool&, bool&>(gms::inet_address const&, unsigned short&, netw::messaging_service::encrypt_what&, netw::messaging_service::compress_what&, netw::messaging_service::tcp_nodelay_what&, unsigned short&, std::shared_ptr<seastar::tls::credentials_builder>&, netw::messaging_service::memory_config&, netw::messaging_service::scheduling_config&, bool&, bool&)::{lambda(unsigned int)#1}::operator()(unsigned int)::{lambda()#1}&) at ././seastar/include/seastar/core/future.hh:1657
 (inlined by) seastar::smp_message_queue::async_work_item<seastar::future<> seastar::sharded<netw::messaging_service>::start<gms::inet_address const&, unsigned short&, netw::messaging_service::encrypt_what&, netw::messaging_service::compress_what&, netw::messaging_service::tcp_nodelay_what&, unsigned short&, std::shared_ptr<seastar::tls::credentials_builder>&, netw::messaging_service::memory_config&, netw::messaging_service::scheduling_config&, bool&, bool&>(gms::inet_address const&, unsigned short&, netw::messaging_service::encrypt_what&, netw::messaging_service::compress_what&, netw::messaging_service::tcp_nodelay_what&, unsigned short&, std::shared_ptr<seastar::tls::credentials_builder>&, netw::messaging_service::memory_config&, netw::messaging_service::scheduling_config&, bool&, bool&)::{lambda(unsigned int)#1}::operator()(unsigned int)::{lambda()#1}>::run_and_dispose() at ././seastar/include/seastar/core/smp.hh:215
seastar::reactor::run_tasks(seastar::reactor::task_queue&) at /usr/include/fmt/format.h:1158
seastar::reactor::run_some_tasks() at /usr/include/fmt/format.h:1158
seastar::reactor::run_some_tasks() at /usr/include/fmt/format.h:1158
 (inlined by) seastar::reactor::run() at ./build/release/seastar/./seastar/src/core/reactor.cc:2693
seastar::smp::configure(boost::program_options::variables_map, seastar::reactor_config)::{lambda()#3}::operator()() const at /usr/include/fmt/format.h:1158
std::function<void ()>::operator()() const at /usr/include/c++/9/bits/std_function.h:690
 (inlined by) seastar::posix_thread::start_routine(void*) at ./build/release/seastar/./seastar/src/core/posix.cc:52
```

full logs can be found here:
```
+--------------------------------------------------------------------------------------------------------------------------------------------+
|                                      Collected logs by test-id: bbc128f5-0097-4db4-9327-d46c7d8e73a2                                       |
+-------------+------------------------------------------------------------------------------------------------------------------------------+
| Cluster set | Link                                                                                                                         |
+-------------+------------------------------------------------------------------------------------------------------------------------------+
| db-cluster  | https://cloudius-jenkins-test.s3.amazonaws.com/bbc128f5-0097-4db4-9327-d46c7d8e73a2/20200412_105848/db-cluster-bbc128f5.zip  |
| monitor-set | https://cloudius-jenkins-test.s3.amazonaws.com/bbc128f5-0097-4db4-9327-d46c7d8e73a2/20200412_105848/monitor-set-bbc128f5.zip |
| loader-set  | None                                                                                                                         |
| sct-runner  | https://cloudius-jenkins-test.s3.amazonaws.com/bbc128f5-0097-4db4-9327-d46c7d8e73a2/20200412_105848/sct-runner-bbc128f5.zip  |
+-------------+------------------------------------------------------------------------------------------------------------------------------+
```

**Comment by fgelcer** [comment] 2020-04-13 19:42
could be related to #6188, #6189, #6190 or #6191

**Comment by slivne** [comment] 2020-05-25 23:38
we do have some stalls during boot - pushing this out to later releases

**Comment by avikivity** [comment] 2020-05-27 05:35
/cc @elcallio 

```c++
    impl(level lvl)
            : impl() {
        auto bits = gnutls_sec_param_to_pk_bits(GNUTLS_PK_DH, to_gnutls_level(lvl));
        gtls_chk(gnutls_dh_params_generate2(*this, bits));
    }
```

These to look like they could take a long time. The only solution I can see is to offload it to an alien thread.


btw, the manual says:
>        It is no longer recommended for applications to generate parameters.
>        See the "Parameter generation" section in the manual.

**Comment by avikivity** [comment] 2020-07-19 07:37
Duplicate of #6191

**Closed by avikivity** 2020-07-19 07:37 UTC
