### ISSUE TITLE
Scylla stuck during `systemctl stop scylla-server.service` (while running TerminateAndRemoveNodeMonkey)

### ISSUE THREAD

**Issue by fruch** [scylladb/scylla#8191] opened 2021-03-01 10:20 UTC
*Installation details*
Scylla version (or git commit hash): 4.5.dev-0.20210216.2f3b265da with build-id 6a7412abfaf73ef877a8e6ae22759227e89cac13 (ami-0208ab84477ace351)
Cluster size: 6 (i3.4xlarge)
OS (RHEL/CentOS/Ubuntu/AWS AMI): ami-0208ab84477ace351

# Summary
During `TerminateAndRemoveNodeMonkey` as part of `longevity-50gb-3days` weekly run on master
While calling `systemctl stop scylla-server.service` (on `longevity-tls-50gb-3d-master-db-node-147194be-4`) scylla get stuck, and last seen log is from the hints_manager being stopped

```
2021-02-26T14:04:15+00:00  longevity-tls-50gb-3d-master-db-node-147194be-4 !NOTICE  | sudo: scyllaadm : TTY=unknown ; PWD=/home/scyllaadm ; USER=root ; COMMAND=/bin/systemctl stop scylla-server.service
...
2021-02-26T14:04:15+00:00  longevity-tls-50gb-3d-master-db-node-147194be-4 !INFO    | systemd: Stopping Scylla Server...
2021-02-26T14:04:15+00:00  longevity-tls-50gb-3d-master-db-node-147194be-4 !INFO    | scylla: [shard 0] compaction_manager - Asked to stop
...
2021-02-26T14:04:26+00:00  longevity-tls-50gb-3d-master-db-node-147194be-4 !INFO    | scylla: [shard 13] hints_manager - Stopped
2021-02-26T14:04:26+00:00  longevity-tls-50gb-3d-master-db-node-147194be-4 !INFO    | scylla: [shard 6] hints_manager - Stopped
2021-02-26T14:04:26+00:00  longevity-tls-50gb-3d-master-db-node-147194be-4 !INFO    | scylla: [shard 9] hints_manager - Stopped
2021-02-26T14:04:27+00:00  longevity-tls-50gb-3d-master-db-node-147194be-4 !INFO    | scylla: [shard 4] hints_manager - Stopped
```

## Logs

* **db-cluster** - https://cloudius-jenkins-test.s3.amazonaws.com/147194be-61d9-456d-b7f4-2631e84617a9/20210301_065832/db-cluster-147194be.zip
* **loader-set** - https://cloudius-jenkins-test.s3.amazonaws.com/147194be-61d9-456d-b7f4-2631e84617a9/20210301_065832/loader-set-147194be.zip
* **monitor-set** - https://cloudius-jenkins-test.s3.amazonaws.com/147194be-61d9-456d-b7f4-2631e84617a9/20210301_065832/monitor-set-147194be.zip
* **sct-runner** - https://cloudius-jenkins-test.s3.amazonaws.com/147194be-61d9-456d-b7f4-2631e84617a9/20210301_065832/sct-runner-147194be.zip

**Comment by fruch** [comment] 2021-03-01 10:34
seems like it happened also during the weekly `longevity-200gb-48h#104` 
but while running `sudo systemctl restart scylla-server.service` time outed after 10mins

## Logs
* **db-cluster** - https://cloudius-jenkins-test.s3.amazonaws.com/ad480eeb-4248-4276-b93a-c88ef24cf6f9/20210228_051940/db-cluster-ad480eeb.zip
* **loader-set** - https://cloudius-jenkins-test.s3.amazonaws.com/ad480eeb-4248-4276-b93a-c88ef24cf6f9/20210228_051940/loader-set-ad480eeb.zip
* **monitor-set** - https://cloudius-jenkins-test.s3.amazonaws.com/ad480eeb-4248-4276-b93a-c88ef24cf6f9/20210228_051940/monitor-set-ad480eeb.zip
* **sct-runner** - https://cloudius-jenkins-test.s3.amazonaws.com/ad480eeb-4248-4276-b93a-c88ef24cf6f9/20210228_051940/sct-runner-ad480eeb.zip
* Restore Monitor Stack command: $ hydra investigate show-monitor ad480eeb-4248-4276-b93a-c88ef24cf6f9
* Show all stored logs command: $ hydra investigate show-logs ad480eeb-4248-4276-b93a-c88ef24cf6f9

downloading logs now to verify it's the same

**Comment by slivne** [comment] 2021-03-01 15:47
can we get a stuck node ?

**Comment by fruch** [comment] 2021-03-01 16:15
> can we get a stuck node ?

one, systemd seem to timeout after 15min, regardless (i.e. in `sudo systemctl restart scylla-server.service` example at least)

we might be able to run the 48h case only with `StopStartMonkey`, but it might be deepened on other nemesis taking place before.

**Comment by fruch** [comment] 2021-03-01 16:20
> > can we get a stuck node ?
> 
> one, systemd seem to timeout after 15min, regardless (i.e. in `sudo systemctl restart scylla-server.service` example at least)
> 
> we might be able to run the 48h case only with `StopStartMonkey`, but it might be deepened on other nemesis taking place before.

trying it here:
https://jenkins.scylladb.com/view/master/job/scylla-master/job/reproducers/job/8191_repoducer/1/

**Comment by fruch** [comment] 2021-03-02 07:11
@slivne @bhalevy 
It reproduced after ~3h, and it's currently stuck:
`longevity-200gb-48h-verify-limited--db-node-bef564a2-4 [13.49.69.246 | 10.0.1.181]`

the cluster is all yours.

but again, systemd is wiping the evidence and forcefully killing the process:
```
Mar 01 19:21:06 longevity-200gb-48h-verify-limited--db-node-bef564a2-4 systemd[1]: Stopping Scylla Server...
...
Mar 01 19:36:06 longevity-200gb-48h-verify-limited--db-node-bef564a2-4 systemd[1]: scylla-server.service stop-sigterm timed out. Killing.
Mar 01 19:37:04 longevity-200gb-48h-verify-limited--db-node-bef564a2-4 systemd[1]: scylla-server.service: main process exited, code=killed, status=9/KILL
Mar 01 19:37:04 longevity-200gb-48h-verify-limited--db-node-bef564a2-4 systemd[1]: Stopped Scylla Server.
Mar 01 19:37:04 longevity-200gb-48h-verify-limited--db-node-bef564a2-4 systemd[1]: Unit scylla-server.service entered failed state.
Mar 01 19:37:04 longevity-200gb-48h-verify-limited--db-node-bef564a2-4 systemd[1]: scylla-server.service failed.
```

**Comment by bhalevy** [comment] 2021-03-02 07:50
@xemul please look into this

**Comment by xemul** [comment] 2021-03-02 07:54
I believe this is duplicate of #8079 -- the suspect be8c359 is there, the node stucks on shutting down the hints manager.

**Comment by slivne** [comment] 2021-03-02 10:20
@xemul strange the version referenced above 2f3b265da does include the patch be8c359 you pointed to

**Comment by xemul** [comment] 2021-03-02 10:25
@slivne , yes, the patch be8c359 is the one that seems to cause hints manager stop to hang and it's present in scyllas from both bugs, this and that

**Comment by slivne** [comment] 2021-03-02 11:00
Hm ... when we shutdown we will flush memtables - this is not supposed to increase commitlog usage - its supposed actually to clear the commitlogs.

**Comment by fruch** [comment] 2021-03-02 12:00
@elcallio so the cluster with the reproducer isn't needed ? (I'm going to terminate it)

**Comment by elcallio** [comment] 2021-03-09 12:17
If this is a hanging hints manager, it should be addressed by added53b7d614280695d5468c08f401d6833cbab

**Comment by roydahan** [comment] 2021-03-12 02:36
I have this node where it reproduced if someone needs it: 13.49.78.133.

**Comment by slivne** [comment] 2021-03-16 12:19
@elcallio can you please check if this is the issue

**Comment by roydahan** [comment] 2021-03-17 00:06
It seems that I faced this issue in 4.4.rc3-0.20210304.c2d924757 as part of longevirt-counters-multidc-test.

During an ENOSPC nemesis, after node-4 was filled and hit the expected "storage I/O error", the nemesis clear the space and restarting the service by: "sudo systemctl restart scylla-server.service".
However, in this case the node failed to stop in expected time with the same behaviour as described above:

```
2021-03-10 22:38:28  Running command "sudo systemctl restart scylla-server.service"...

2021-03-10T22:38:28+00:00  systemd: Stopping Scylla Server...

021-03-10T22:38:31+00:00   scylla: [shard 5] hints_manager - Stopped
2021-03-10T22:38:31+00:00  scylla: [shard 4] hints_manager - Stopped
2021-03-10T22:38:31+00:00  scylla: [shard 7] hints_manager - Stopped
2021-03-10T22:38:31+00:00  scylla: [shard 6] hints_manager - Stopped
2021-03-10T22:38:31+00:00  scylla: [shard 0] hints_manager - Stopped
2021-03-10T22:38:31+00:00  scylla: [shard 1] hints_manager - Stopped
```
This is the last message from scylla until:
```
021-03-10T22:54:26+00:00   systemd: scylla-server.service: main process exited, code=killed, status=9/KILL
2021-03-10T22:54:26+00:00 systemd: Stopped Scylla Server.
2021-03-10T22:54:26+00:00 systemd: Unit scylla-server.service entered failed state.
2021-03-10T22:54:26+00:00 systemd: scylla-server.service failed.

```

Logs available in:
db-cluster - https://cloudius-jenkins-test.s3.amazonaws.com/6be1383c-4391-4e14-ad9f-48dc17120baa/20210310_230053/db-cluster-6be1383c.zip
loader-set - https://cloudius-jenkins-test.s3.amazonaws.com/6be1383c-4391-4e14-ad9f-48dc17120baa/20210310_230053/loader-set-6be1383c.zip
monitor-set - https://cloudius-jenkins-test.s3.amazonaws.com/6be1383c-4391-4e14-ad9f-48dc17120baa/20210310_230053/monitor-set-6be1383c.zip
sct-runner - https://cloudius-jenkins-test.s3.amazonaws.com/6be1383c-4391-4e14-ad9f-48dc17120baa/20210310_230053/sct-runner-6be1383c.zip

**Comment by bhalevy** [comment] 2021-03-17 08:13
Looks like https://github.com/scylladb/scylla/issues/8079
@elcallio / @xemul is 4.4 exposed?

**Comment by bhalevy** [comment] 2021-03-21 16:12
Duplicate of #8079

**Closed by bhalevy** 2021-03-21 16:12 UTC
Labels: bug
