### ISSUE TITLE
nodetool info return a negative load value

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#688] opened 2015-12-22 10:58 UTC
tested 'nodetool info' with scylla 0.13.2
note the negative load value 
```
ID                     : 37b3d89b-fca2-42b7-a15c-d3237a3f2bcc
Gossip active          : true
Thrift active          : false
Native Transport active: true
Load                   : -1990250115 bytes
Generation No          : 1450772353
Uptime (seconds)       : 529
Heap Memory (MB)       : 466.32 / 1710.50
Off Heap Memory (MB)   : 35.75
Data Center            : datacenter1
Rack                   : rack1
Exceptions             : 0
Key Cache              : entries 0, size 0 bytes, capacity 0 bytes, 0 hits, 0 requests, 0.000 recent hit rate, 0 save period in seconds
Row Cache              : entries 10, size 10 bytes, capacity 1.82 MB, 57 hits, 95 requests, 0.604 recent hit rate, 0 save period in seconds
Counter Cache          : entries 0, size 0 bytes, capacity 0 bytes, 0 hits, 0 requests, 0.000 recent hit rate, 0 save period in seconds
Token                  : (invoke with -T/--tokens to see all 256 tokens)
```

**Comment by tzach** [comment] 2016-01-11 15:46
@amnonh is this fixed?

**Comment by amnonh** [comment] 2016-01-12 07:04
not tested yet

**Comment by slivne** [comment] 2016-02-18 01:18
tested on 0.18 does not reproduce 

fixed by 
commit 0aa105c9cf95fb6310c5f556ebdd5cf2db6ad1b6
Merge: f0b2767 7190508
Author: Pekka Enberg <penberg@scylladb.com>
Date:   Wed Dec 30 10:21:55 2015 +0200

    Merge "load report a negative value" from Amnon
    
    "This series solve an issue with the load broadcaster that reports negative
     values due to an integer wrap around.  While fixing this issue an additional
     change was made so that the load_map would return doubles and not formatted
     string.  This is a better API, safer and better documented."

**Closed by slivne** 2016-02-18 01:18 UTC
Labels: bug, high, nodetool
