### ISSUE TITLE
Reactor stalled for 40  ms in put_row_diff_handler() during decommission

### ISSUE THREAD

**Issue by fgelcer** [scylladb/scylla#7136] opened 2020-08-27 11:18 UTC
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash): Scylla version 666.development-0.20200824.9636a3399 with build-id 81092cc5b8be6e33160d7abf197499a3e00f6306
Cluster size: 3
OS (RHEL/CentOS/Ubuntu/AWS AMI): ami-04ec7a3ece2712d76 (on us-east-1)

stall happened during decommission:

```
void seastar::backtrace<seastar::backtrace_buffer::append_backtrace()::{lambda(seastar::frame)#1}>(seastar::backtrace_buffer::append_backtrace()::{lambda(seastar::frame)#1}&&) at reactor.cc:?
seastar::print_with_backtrace(seastar::backtrace_buffer&) at reactor.cc:?
 (inlined by) print_with_backtrace at /jenkins/workspace/scylla-master/next/scylla/seastar/src/core/reactor.cc:752
seastar::internal::cpu_stall_detector::generate_trace() at reactor.cc:?
seastar::reactor::block_notifier(int) at reactor.cc:?
 (inlined by) seastar::internal::cpu_stall_detector::on_signal() at /jenkins/workspace/scylla-master/next/scylla/seastar/src/core/reactor.cc:1061
 (inlined by) seastar::reactor::block_notifier(int) at /jenkins/workspace/scylla-master/next/scylla/seastar/src/core/reactor.cc:1184
?? ??:0
std::__cxx11::_List_base<partition_key_and_mutation_fragments, std::allocator<partition_key_and_mutation_fragments> >::_M_clear() at messaging_service.cc:?
 (inlined by) std::__cxx11::_List_base<frozen_mutation_fragment, std::allocator<frozen_mutation_fragment> >::~_List_base() at /usr/include/c++/10/bits/stl_list.h:499
 (inlined by) std::__cxx11::list<frozen_mutation_fragment, std::allocator<frozen_mutation_fragment> >::~list() at /usr/include/c++/10/bits/stl_list.h:827
 (inlined by) partition_key_and_mutation_fragments::~partition_key_and_mutation_fragments() at /jenkins/workspace/scylla-master/next/scylla/./repair/repair.hh:402
 (inlined by) void std::destroy_at<partition_key_and_mutation_fragments>(partition_key_and_mutation_fragments*) at /usr/include/c++/10/bits/stl_construct.h:88
 (inlined by) void std::allocator_traits<std::allocator<std::_List_node<partition_key_and_mutation_fragments> > >::destroy<partition_key_and_mutation_fragments>(std::allocator<std::_List_node<partition_key_and_mutation_fragments> >&, partition_key_and_mutation_fragments*) at /usr/include/c++/10/bits/alloc_traits.h:533
 (inlined by) std::__cxx11::_List_base<partition_key_and_mutation_fragments, std::allocator<partition_key_and_mutation_fragments> >::_M_clear() at /usr/include/c++/10/bits/list.tcc:77
std::__cxx11::_List_base<partition_key_and_mutation_fragments, std::allocator<partition_key_and_mutation_fragments> >::~_List_base() at /usr/include/c++/10/bits/stl_list.h:499
 (inlined by) std::__cxx11::list<partition_key_and_mutation_fragments, std::allocator<partition_key_and_mutation_fragments> >::~list() at /usr/include/c++/10/bits/stl_list.h:827
 (inlined by) repair_meta::put_row_diff_handler(std::__cxx11::list<partition_key_and_mutation_fragments, std::allocator<partition_key_and_mutation_fragments> >, gms::inet_address)::{lambda()#1}::operator()() at /jenkins/workspace/scylla-master/next/scylla/repair/row_level.cc:1876
 (inlined by) seastar::future<> seastar::futurize<seastar::future<> >::invoke<repair_meta::put_row_diff_handler(std::__cxx11::list<partition_key_and_mutation_fragments, std::allocator<partition_key_and_mutation_fragments> >, gms::inet_address)::{lambda()#1}>(repair_meta::put_row_diff_handler(std::__cxx11::list<partition_key_and_mutation_fragments, std::allocator<partition_key_and_mutation_fragments> >, gms::inet_address)::{lambda()#1}&&) at /jenkins/workspace/scylla-master/next/scylla/seastar/include/seastar/core/future.hh:2038
 (inlined by) auto seastar::futurize_invoke<repair_meta::put_row_diff_handler(std::__cxx11::list<partition_key_and_mutation_fragments, std::allocator<partition_key_and_mutation_fragments> >, gms::inet_address)::{lambda()#1}>(repair_meta::put_row_diff_handler(std::__cxx11::list<partition_key_and_mutation_fragments, std::allocator<partition_key_and_mutation_fragments> >, gms::inet_address)::{lambda()#1}&&) at /jenkins/workspace/scylla-master/next/scylla/seastar/include/seastar/core/future.hh:2122
 (inlined by) auto seastar::internal::invoke_func_with_gate<repair_meta::put_row_diff_handler(std::__cxx11::list<partition_key_and_mutation_fragments, std::allocator<partition_key_and_mutation_fragments> >, gms::inet_address)::{lambda()#1}>(seastar::gate&, repair_meta::put_row_diff_handler(std::__cxx11::list<partition_key_and_mutation_fragments, std::allocator<partition_key_and_mutation_fragments> >, gms::inet_address)::{lambda()#1}&&) at /jenkins/workspace/scylla-master/next/scylla/seastar/include/seastar/core/gate.hh:126
 (inlined by) auto seastar::with_gate<repair_meta::put_row_diff_handler(std::__cxx11::list<partition_key_and_mutation_fragments, std::allocator<partition_key_and_mutation_fragments> >, gms::inet_address)::{lambda()#1}>(seastar::gate&, repair_meta::put_row_diff_handler(std::__cxx11::list<partition_key_and_mutation_fragments, std::allocator<partition_key_and_mutation_fragments> >, gms::inet_address)::{lambda()#1}&&) at /jenkins/workspace/scylla-master/next/scylla/seastar/include/seastar/core/gate.hh:144
 (inlined by) repair_meta::put_row_diff_handler(std::__cxx11::list<partition_key_and_mutation_fragments, std::allocator<partition_key_and_mutation_fragments> >, gms::inet_address) at /jenkins/workspace/scylla-master/next/scylla/repair/row_level.cc:1877
operator() at /jenkins/workspace/scylla-master/next/scylla/repair/row_level.cc:1956
 (inlined by) invoke<repair_put_row_diff_with_rpc_stream_process_op(gms::inet_address, uint32_t, uint32_t, seastar::rpc::sink<repair_stream_cmd>, seastar::rpc::source<repair_row_on_wire_with_cmd>, bool&, repair_rows_on_wire&, std::optional<std::tuple<repair_row_on_wire_with_cmd> >)::<lambda()>&> at /jenkins/workspace/scylla-master/next/scylla/seastar/include/seastar/core/future.hh:2038
 (inlined by) submit_to<repair_put_row_diff_with_rpc_stream_process_op(gms::inet_address, uint32_t, uint32_t, seastar::rpc::sink<repair_stream_cmd>, seastar::rpc::source<repair_row_on_wire_with_cmd>, bool&, repair_rows_on_wire&, std::optional<std::tuple<repair_row_on_wire_with_cmd> >)::<lambda()> > at /jenkins/workspace/scylla-master/next/scylla/seastar/include/seastar/core/smp.hh:334
 (inlined by) submit_to<repair_put_row_diff_with_rpc_stream_process_op(gms::inet_address, uint32_t, uint32_t, seastar::rpc::sink<repair_stream_cmd>, seastar::rpc::source<repair_row_on_wire_with_cmd>, bool&, repair_rows_on_wire&, std::optional<std::tuple<repair_row_on_wire_with_cmd> >)::<lambda()> > at /jenkins/workspace/scylla-master/next/scylla/seastar/include/seastar/core/smp.hh:361
 (inlined by) repair_put_row_diff_with_rpc_stream_process_op at /jenkins/workspace/scylla-master/next/scylla/repair/row_level.cc:1960
 (inlined by) operator() at /jenkins/workspace/scylla-master/next/scylla/repair/row_level.cc:2063
 (inlined by) __invoke_impl<seastar::future<seastar::bool_class<seastar::stop_iteration_tag> >, repair_put_row_diff_with_rpc_stream_handler(gms::inet_address, uint32_t, uint32_t, seastar::rpc::sink<repair_stream_cmd>, seastar::rpc::source<repair_row_on_wire_with_cmd>)::<lambda(bool&, repair_rows_on_wire&)> mutable::<lambda()> mutable::<lambda(std::optional<std::tuple<repair_row_on_wire_with_cmd> >)>, std::optional<std::tuple<repair_row_on_wire_with_cmd> > > at /usr/include/c++/10/bits/invoke.h:60
__invoke<repair_put_row_diff_with_rpc_stream_handler(gms::inet_address, uint32_t, uint32_t, seastar::rpc::sink<repair_stream_cmd>, seastar::rpc::source<repair_row_on_wire_with_cmd>)::<lambda(bool&, repair_rows_on_wire&)> mutable::<lambda()> mutable::<lambda(std::optional<std::tuple<repair_row_on_wire_with_cmd> >)>, std::optional<std::tuple<repair_row_on_wire_with_cmd> > > at /usr/include/c++/10/bits/invoke.h:96
 (inlined by) __apply_impl<repair_put_row_diff_with_rpc_stream_handler(gms::inet_address, uint32_t, uint32_t, seastar::rpc::sink<repair_stream_cmd>, seastar::rpc::source<repair_row_on_wire_with_cmd>)::<lambda(bool&, repair_rows_on_wire&)> mutable::<lambda()> mutable::<lambda(std::optional<std::tuple<repair_row_on_wire_with_cmd> >)>, std::tuple<std::optional<std::tuple<repair_row_on_wire_with_cmd> > >, 0> at /usr/include/c++/10/tuple:1724
 (inlined by) apply<repair_put_row_diff_with_rpc_stream_handler(gms::inet_address, uint32_t, uint32_t, seastar::rpc::sink<repair_stream_cmd>, seastar::rpc::source<repair_row_on_wire_with_cmd>)::<lambda(bool&, repair_rows_on_wire&)> mutable::<lambda()> mutable::<lambda(std::optional<std::tuple<repair_row_on_wire_with_cmd> >)>, std::tuple<std::optional<std::tuple<repair_row_on_wire_with_cmd> > > > at /usr/include/c++/10/tuple:1736
 (inlined by) apply<repair_put_row_diff_with_rpc_stream_handler(gms::inet_address, uint32_t, uint32_t, seastar::rpc::sink<repair_stream_cmd>, seastar::rpc::source<repair_row_on_wire_with_cmd>)::<lambda(bool&, repair_rows_on_wire&)> mutable::<lambda()> mutable::<lambda(std::optional<std::tuple<repair_row_on_wire_with_cmd> >)>, std::optional<std::tuple<repair_row_on_wire_with_cmd> > > at /jenkins/workspace/scylla-master/next/scylla/seastar/include/seastar/core/future.hh:2021
 (inlined by) then_impl<repair_put_row_diff_with_rpc_stream_handler(gms::inet_address, uint32_t, uint32_t, seastar::rpc::sink<repair_stream_cmd>, seastar::rpc::source<repair_row_on_wire_with_cmd>)::<lambda(bool&, repair_rows_on_wire&)> mutable::<lambda()> mutable::<lambda(std::optional<std::tuple<repair_row_on_wire_with_cmd> >)> > at /jenkins/workspace/scylla-master/next/scylla/seastar/include/seastar/core/future.hh:1563
 (inlined by) run<repair_put_row_diff_with_rpc_stream_handler(gms::inet_address, uint32_t, uint32_t, seastar::rpc::sink<repair_stream_cmd>, seastar::rpc::source<repair_row_on_wire_with_cmd>)::<lambda(bool&, repair_rows_on_wire&)> mutable::<lambda()> mutable::<lambda(std::optional<std::tuple<repair_row_on_wire_with_cmd> >)> > at /jenkins/workspace/scylla-master/next/scylla/seastar/include/seastar/core/future.hh:1210
 (inlined by) then<repair_put_row_diff_with_rpc_stream_handler(gms::inet_address, uint32_t, uint32_t, seastar::rpc::sink<repair_stream_cmd>, seastar::rpc::source<repair_row_on_wire_with_cmd>)::<lambda(bool&, repair_rows_on_wire&)> mutable::<lambda()> mutable::<lambda(std::optional<std::tuple<repair_row_on_wire_with_cmd> >)> > at /jenkins/workspace/scylla-master/next/scylla/seastar/include/seastar/core/future.hh:1486
 (inlined by) operator() at /jenkins/workspace/scylla-master/next/scylla/repair/row_level.cc:2072
 (inlined by) invoke<repair_put_row_diff_with_rpc_stream_handler(gms::inet_address, uint32_t, uint32_t, seastar::rpc::sink<repair_stream_cmd>, seastar::rpc::source<repair_row_on_wire_with_cmd>)::<lambda(bool&, repair_rows_on_wire&)> mutable::<lambda()>&> at /jenkins/workspace/scylla-master/next/scylla/seastar/include/seastar/core/future.hh:2038
 (inlined by) futurize_invoke<repair_put_row_diff_with_rpc_stream_handler(gms::inet_address, uint32_t, uint32_t, seastar::rpc::sink<repair_stream_cmd>, seastar::rpc::source<repair_row_on_wire_with_cmd>)::<lambda(bool&, repair_rows_on_wire&)> mutable::<lambda()>&> at /jenkins/workspace/scylla-master/next/scylla/seastar/include/seastar/core/future.hh:2122
 (inlined by) run_and_dispose at /jenkins/workspace/scylla-master/next/scylla/seastar/include/seastar/core/loop.hh:73
seastar::reactor::run_tasks(seastar::reactor::task_queue&) at reactor.cc:?
seastar::reactor::run_some_tasks() [clone .part.0] at reactor.cc:?
seastar::reactor::run() at reactor.cc:?
 (inlined by) seastar::reactor::run() at /jenkins/workspace/scylla-master/next/scylla/seastar/src/core/reactor.cc:2764
operator() at /jenkins/workspace/scylla-master/next/scylla/seastar/src/core/reactor.cc:3939
std::function<void ()>::operator()() const at /usr/include/c++/10/bits/basic_string.h:323
 (inlined by) seastar::posix_thread::start_routine(void*) at /jenkins/workspace/scylla-master/next/scylla/seastar/src/core/posix.cc:60
```

**Comment by avikivity** [comment] 2020-08-27 11:41
Closing as duplicate of #7115.

**Comment by avikivity** [comment] 2020-08-27 11:41
(it's really apply_rows_on_follower()).

**Closed by avikivity** 2020-08-27 11:41 UTC
Labels: latency

**Comment by fgelcer** [comment] 2020-08-27 12:32
> (it's really apply_rows_on_follower()).

i didn't find this function name in that backtrace though

**Comment by avikivity** [comment] 2020-08-27 12:35
The backtrace hid it somehow. Here's the function:

```c++
    // RPC handler
    future<> put_row_diff_handler(repair_rows_on_wire rows, gms::inet_address from) {
        return with_gate(_gate, [this, rows = std::move(rows)] () mutable {
            return apply_rows_on_follower(std::move(rows));
        });
    }
```

**Comment by fgelcer** [comment] 2020-08-27 12:48
> The backtrace hid it somehow. Here's the function:
> 
> ```c++
>     // RPC handler
>     future<> put_row_diff_handler(repair_rows_on_wire rows, gms::inet_address from) {
>         return with_gate(_gate, [this, rows = std::move(rows)] () mutable {
>             return apply_rows_on_follower(std::move(rows));
>         });
>     }
> ```

thank you.. i will keep also the `put_row_diff_handler` as part of my filters

**Comment by fgelcer** [comment] 2020-09-07 11:56
haven't seen this stall in the latest run.
