### ISSUE TITLE
Nodetool status report wrong load

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#1592] opened 2016-08-17 06:32 UTC
Scylla version (or git commit hash): 1.2.3
Cluster size: 5
OS (RHEL/CentOS/Ubuntu/AWS AMI): CentOS 7.2

User report wrong values of Load value in nodetool status
Value appear to be much higher than expected. The value returns to it real(?) value after restart
See Load for node x.x.x.x below

```
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address         Load       Tokens  Owns    Host ID                               Rack
UN  x.x.x.x  51.33 GB   256     ?       b80d5d38-f42e-4c31-939d-cd7088f8775d  RAC2
UL  x.x.x.x  51.37 GB   256     ?       8fd8c903-5b9b-4e8a-82d4-9c00531cc4bc  RAC2
UN  x.x.x.x   1.34 GB    256     ?       df1247ea-e9fc-49c6-8250-07b3822736b8  RAC2
UN  x.x.x.x   2.81 GB    256     ?       b44406e4-69a7-416c-95a5-ca487cc6978f  RAC2

systemctl restart scylla-server

atacenter: INTERNAP
====================
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address         Load       Tokens  Owns    Host ID                               Rack
UN  x.x.x.x  51.33 GB   256     ?       b80d5d38-f42e-4c31-939d-cd7088f8775d  RAC2
UN  x.x.x.x  1.73 GB    256     ?       8fd8c903-5b9b-4e8a-82d4-9c00531cc4bc  RAC2
UN  x.x.x.x   1.34 GB    256     ?       df1247ea-e9fc-49c6-8250-07b3822736b8  RAC2
UN  x.x.x.x   2.81 GB    256     ?       b44406e4-69a7-416c-95a5-ca487cc6978f  RAC2
```

**Comment by asias** [comment] 2016-08-17 06:38
what is the scylla data directory size on disk?

**Comment by scottsauff** [comment] 2016-08-17 15:58
I'm seeing anomolous Load readings also:
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address     Load       Tokens  Owns    Host ID                               Rack
UN  10.9.67.17  2.04 TB    256     ?       988ae9c7-bf83-458e-bdf2-0582603d7316  rack1
UN  10.9.67.16  2.04 TB    256     ?       73ecaeca-aa84-47d8-9a9f-15f4b3023462  rack1

[root@san-dev-dbcassandra-3 data]# du -sm *
813970	ra                 <=    the only key space in use
2	system
0	system_traces

actual disk space usage is 794 GB while the load is stated to be 2 TB.

**Comment by duarten** [comment] 2016-09-01 11:55
So far I haven't been able to repro the problem.

**Comment by slivne** [comment] 2017-03-05 13:55
@asias can you please provide someinfo on how you were able to reproduce this on the lab machine - we will try to redo what you did and then debug that.

**Comment by duarten** [comment] 2017-03-05 14:46
This was reproduced? What version, to check if it contains d53f96e?

**Comment by nirmaayan** [comment] 2017-03-05 15:20
https://github.com/scylladb/scylla-enterprise/issues/88

**Comment by asias** [comment] 2017-03-06 02:26
No. It does not contain  d53f96e. I saw this a few weeks ago with c314047b6c6e39a6d0a7d22408798ea7d292abc5.

**Comment by slivne** [comment] 2017-03-06 10:39
@asias - was there resharding in all cases - if there are not shared sstables this should not happen. - do you recall how you populated the data so we can try this again

**Comment by asias** [comment] 2017-03-06 11:13
IIRC, I saw mismatched size even before the whole resharding thing from
Avi. I can search for the profile used to generate sstables.

On Mar 6, 2017 18:39, "Shlomi Livne" <notifications@github.com> wrote:

@asias <https://github.com/asias> - was there resharding in all cases - if
there are not shared sstables this should not happen. - do you recall how
you populated the data so we can try this again

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/scylladb/scylla/issues/1592#issuecomment-284361102>,
or mute
the thread

**Comment by duarten** [comment] 2017-03-06 11:25
I thought we always did resharding when importing sstables from C* or changing the number of shards?

**Comment by tzach** [comment] 2017-04-23 11:23
@duarten any update on this issue?

**Comment by duarten** [comment] 2017-04-23 11:42
@tzach No, it's still not clear to me if there's still an issue after d53f96e was merged.

**Comment by gleb-cloudius** [comment] 2017-05-21 08:07
@duarte I was loading 1.7 (which contains d53f96e) cluster with data overnight an encountered this issue. Nodetool says:

```
UN  10.0.4.131  4.34 TB    16           ?       6e554930-eff6-439f-b2b0-e5f7939fc750  rack1
UN  10.0.4.132  7.7 TB     16           ?       309733f4-edd6-44f8-b401-a8ebc943b1e4  rack1
DN  10.0.4.133  2.87 TB    256          ?       3ea61f01-0547-401a-ae53-f69f0eaf0574  rack1
```

but df reports:
10.0.4.131 1.9T
10.0.4.132 1.4T
10.0.4.133 1.6T

Note that 10.0.4.133 is dead because it ran out of disk space, but I doubt this is relevant for the bug

**Comment by duarten** [comment] 2017-05-21 16:38
@gleb-cloudius Dang. All you did was upload data? Do you have any trace of what compactions happened?

**Comment by gleb-cloudius** [comment] 2017-05-22 08:16
On Sun, May 21, 2017 at 09:38:43AM -0700, Duarte Nunes wrote:
> @gleb-cloudius Dang. All you did was upload data? Do you have any trace of what compactions happened?
> 
This was not a fresh cluster. It had some populated tables. I added one
more and uploaded data with c-s and user profile and while running
"nodetool status" noticed that reported sized are much large than the
disk.

--
			Gleb.

**Closed** 2017-05-28 07:38 UTC
Labels: bug, User Request, UX
