### ISSUE TITLE
The restapi major compaction request stucked for 30 minutes and don't get response from scylla.

### ISSUE THREAD

**Issue by aleksbykov** [scylladb/scylla#10485] opened 2022-05-04 12:10 UTC
## Installation details

Kernel Version: 5.13.0-1021-aws
Scylla version (or git commit hash): `2022.1~rc3-20220406.5cc3b678c` with build-id `48dfae0735cd8efc4ae2f5c777beaee2a1e89f4a`
Cluster size: 6 nodes (i3.4xlarge)

Scylla Nodes used in this run:
- longevity-cdc-3d-400gb-2022-1-db-node-87d4d86d-9 (54.246.175.205 | 10.0.2.124) (shards: 14)
- longevity-cdc-3d-400gb-2022-1-db-node-87d4d86d-8 (54.246.249.118 | 10.0.1.221) (shards: 14)
- longevity-cdc-3d-400gb-2022-1-db-node-87d4d86d-7 (18.202.56.125 | 10.0.2.201) (shards: 14)
- longevity-cdc-3d-400gb-2022-1-db-node-87d4d86d-6 (54.171.197.212 | 10.0.0.183) (shards: 14)
- longevity-cdc-3d-400gb-2022-1-db-node-87d4d86d-5 (54.171.80.190 | 10.0.2.197) (shards: 14)
- longevity-cdc-3d-400gb-2022-1-db-node-87d4d86d-4 (63.33.189.25 | 10.0.1.179) (shards: 14)
- longevity-cdc-3d-400gb-2022-1-db-node-87d4d86d-3 (34.245.184.131 | 10.0.0.237) (shards: 14)
- longevity-cdc-3d-400gb-2022-1-db-node-87d4d86d-2 (34.254.180.122 | 10.0.3.44) (shards: 14)
- longevity-cdc-3d-400gb-2022-1-db-node-87d4d86d-1 (34.245.1.48 | 10.0.0.104) (shards: 14)

OS / Image: `ami-071c70d20f0fdbb2c` (aws: eu-west-1)

Test: `longevity-cdc-3d-400gb-test`
Test id: `87d4d86d-7e51-4072-a066-cd2cf4633f8a`
Test name: `enterprise-2022.1/longevity/longevity-cdc-3d-400gb-test`
Test config file(s):

- [longevity-cdc-3d-400gb.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/f8f7bf6e6c2cad0b24fc1268fcee4e0155aa9514/test-cases/longevity/longevity-cdc-3d-400gb.yaml)

## Issue description

test is running with enabled cdc. It configured the keyspace with 4 tables with configured cdc features: detla, preimage + delta, postimage + delta, preimage+postimage+delta.
The payload is generated with c-s commands. In addition, the standard c-s's keyspaces table configured keyspace1.standard1 

The nemesis 'start_stop_compaction' trigger major compaction via rest api and then stop it with nodetool stop COMPACTION command.

The nemesis triggered user-requested compaction for keyspace keyspace1.standard1 using curl command on node6:
```
< t:2022-04-29 17:34:30,446 f:remote_base.py  l:520  c:RemoteLibSSH2CmdRunner p:DEBUG > Running command "curl -v -X POST "http://localhost:10000/storage_service/keyspace_compaction/keyspace1?cf=standard1""...
```
compaction was started:
```
2022-04-29T17:34:35+00:00 longevity-cdc-3d-400gb-2022-1-db-node-87d4d86d-6 !    INFO |  [shard 0] compaction_manager - User initiated compaction started on behalf of keyspace1.standard1
2022-04-29T17:34:35+00:00 longevity-cdc-3d-400gb-2022-1-db-node-87d4d86d-6 !    INFO |  [shard 0] compaction - [Compact keyspace1.standard1 a2f8bf70-c7e2-11ec-a30b-cea7b01e275b] Compacting [/var/lib/scylla/data/keyspace1/standard1-3c5402f0c7cb11ec9cde0da9d3c6dbe5/md-266-big-Data.db:level=0:origin=compaction]
2022-04-29T17:34:35+00:00 longevity-cdc-3d-400gb-2022-1-db-node-87d4d86d-6 !    INFO |  [shard 10] compaction - [Compact keyspace1.standard1 a3145dc0-c7e2-11ec-85bd-ceaab01e275b] Compacting [/var/lib/scylla/data/keyspace1/standard1-3c5402f0c7cb11ec9cde0da9d3c6dbe5/md-276-big-Data.db:level=0:origin=compaction]
2022-04-29T17:34:35+00:00 longevity-cdc-3d-400gb-2022-1-db-node-87d4d86d-6 !    INFO | Accepted publickey for scyllaadm from 10.0.3.158 port 47548 ssh2: RSA SHA256:1YmYWh7roz4Y3FSY7N8CetmQNlK/K5FeBPITC8KF0u8
2022-04-29T17:34:35+00:00 longevity-cdc-3d-400gb-2022-1-db-node-87d4d86d-6 !    INFO | pam_unix(sshd:session): session opened for user scyllaadm by (uid=0)
2022-04-29T17:34:35+00:00 longevity-cdc-3d-400gb-2022-1-db-node-87d4d86d-6 !    INFO | New session 115 of user scyllaadm.
2022-04-29T17:34:35+00:00 longevity-cdc-3d-400gb-2022-1-db-node-87d4d86d-6 !    INFO | Started Session 115 of user scyllaadm.
2022-04-29T17:34:36+00:00 longevity-cdc-3d-400gb-2022-1-db-node-87d4d86d-6 !    INFO |  [shard 6] compaction - [Compact keyspace1.standard1 a38f8130-c7e2-11ec-8bfe-cea9b01e275b] Compacting [/var/lib/scylla/data/keyspace1/standard1-3c5402f0c7cb11ec9cde0da9d3c6dbe5/md-104-big-Data.db:level=0:origin=compaction]
2022-04-29T17:34:36+00:00 longevity-cdc-3d-400gb-2022-1-db-node-87d4d86d-6 !    INFO |  [shard 11] compaction - [Compact keyspace1.standard1 a21cb750-c7e2-11ec-bd90-ceaeb01e275b] Compacted 1 sstables to [/var/lib/scylla/data/keyspace1/standard1-3c5402f0c7cb11ec9cde0da9d3c6dbe5/md-277-big-Data.db:level=0]. 9MB to 9MB (~99% of original) in 2189ms = 4MB/s. ~35712 total partitions merged to 35698.
2022-04-29T17:34:36+00:00 longevity-cdc-3d-400gb-2022-1-db-node-87d4d86d-6 !    INFO |  [shard 9] compaction - [Compact keyspace1.standard1 a241a470-c7e2-11ec-a186-ceacb01e275b] Compacted 1 sstables to [/var/lib/scylla/data/keyspace1/standard1-3c5402f0c7cb11ec9cde0da9d3c6dbe5/md-289-big-Data.db:level=0]. 9MB to 9MB (~99% of original) in 2206ms = 4MB/s. ~35840 total partitions merged to 35740.
2022-04-29T17:34:36+00:00 longevity-cdc-3d-400gb-2022-1-db-node-87d4d86d-6 !    INFO |  [shard 7] compaction - [Compact keyspace1.standard1 a3e54250-c7e2-11ec-a3a5-cea5b01e275b] Compacting [/var/lib/scylla/data/keyspace1/standard1-3c5402f0c7cb11ec9cde0da9d3c6dbe5/md-273-big-Data.db:level=0:origin=compaction]
2022-04-29T17:34:37+00:00 longevity-cdc-3d-400gb-2022-1-db-node-87d4d86d-6 !    INFO |  [shard 1] compaction - [Compact keyspace1.standard1 a43250e0-c7e2-11ec-99a8-ceabb01e275b] Compacting [/var/lib/scylla/data/keyspace1/standard1-3c5402f0c7cb11ec9cde0da9d3c6dbe5/md-239-big-Data.db:level=0:origin=compaction]
2022-04-29T17:34:37+00:00 longevity-cdc-3d-400gb-2022-1-db-node-87d4d86d-6 !    INFO |  [shard 0] compaction - [Compact keyspace1.standard1 a2f8bf70-c7e2-11ec-a30b-cea7b01e275b] Compacted 1 sstables to [/var/lib/scylla/data/keyspace1/standard1-3c5402f0c7cb11ec9cde0da9d3c6dbe5/md-280-big-Data.db:level=0]. 9MB to 9MB (~99% of original) in 2348ms = 3MB/s. ~35712 total partitions merged to 35586.
2022-04-29T17:34:38+00:00 longevity-cdc-3d-400gb-2022-1-db-node-87d4d86d-6 !    INFO |  [shard 10] compaction - [Compact keyspace1.standard1 a3145dc0-c7e2-11ec-85bd-ceaab01e275b] Compacted 1 sstables to [/var/lib/scylla/data/keyspace1/standard1-3c5402f0c7cb11ec9cde0da9d3c6dbe5/md-290-big-Data.db:level=0]. 9MB to 9MB (~99% of original) in 2760ms = 3MB/s. ~35584 total partitions merged to 35522.
2022-04-29T17:34:38+00:00 longevity-cdc-3d-400gb-2022-1-db-node-87d4d86d-6 !    INFO |  [shard 3] compaction - [Compact keyspace1.standard1 a16686b0-c7e2-11ec-9f2b-ceafb01e275b] Compacted 2 sstables to [/var/lib/scylla/data/keyspace1/standard1-3c5402f0c7cb11ec9cde0da9d3c6dbe5/md-17755-big-Data.db:level=0]. 8MB to 9MB (~103% of original) in 5841ms = 1MB/s. ~35584 total partitions merged to 35536.
2022-04-29T17:34:38+00:00 longevity-cdc-3d-400gb-2022-1-db-node-87d4d86d-6 !    INFO |  [shard 10] compaction - [Compact cdc_test.test_table_postimage 87023d50-c7e2-11ec-85bd-ceaab01e275b] Compacted 3 sstables to [/var/lib/scylla/data/cdc_test/test_table_postimage-1f626a10c57d11ec9aaddae6ffe58642/md-44796-big-Data.db:level=0]. 416MB to 168MB (~40% of original) in 50520ms = 3MB/s. ~97664 total partitions merged to 38646.
2022-04-29T17:34:38+00:00 longevity-cdc-3d-400gb-2022-1-db-node-87d4d86d-6 !    INFO |  [shard 10] compaction - [Compact cdc_test.test_table_scylla_cdc_log a5362c50-c7e2-11ec-85bd-ceaab01e275b] Compacting [/var/lib/scylla/data/cdc_test/test_table_scylla_cdc_log-1ac5d780c57d11eca324dadcffe58642/md-137252-big-Data.db:level=0:origin=compaction,/var/lib/scylla/data/cdc_test/test_table_scylla_cdc_log-1ac5d780c57d11eca324dadcffe58642/md-137196-big-Data.db:level=0:origin=compaction,/var/lib/scylla/data/cdc_test/test_table_scylla_cdc_log-1ac5d780c57d11eca324dadcffe58642/md-137294-big-Data.db:level=0:origin=compaction]
2022-04-29T17:34:39+00:00 longevity-cdc-3d-400gb-2022-1-db-node-87d4d86d-6 !    INFO |  [shard 6] compaction - [Compact keyspace1.standard1 a38f8130-c7e2-11ec-8bfe-cea9b01e275b] Compacted 1 sstables to [/var/lib/scylla/data/keyspace1/standard1-3c5402f0c7cb11ec9cde0da9d3c6dbe5/md-272-big-Data.db:level=0]. 9MB to 9MB (~99% of original) in 2759ms = 3MB/s. ~35584 total partitions merged to 35534.
2022-04-29T17:34:39+00:00 longevity-cdc-3d-400gb-2022-1-db-node-87d4d86d-6 !    INFO |  [shard 10] compaction - [Compact cdc_test.test_table_scylla_cdc_log a5362c50-c7e2-11ec-85bd-ceaab01e275b] Compacted 3 sstables to []. 945MB to 0 bytes (~0% of original) in 4ms = 0 bytes/s. ~2304 total partitions merged to 0.
2022-04-29T17:34:39+00:00 longevity-cdc-3d-400gb-2022-1-db-node-87d4d86d-6 !    INFO |  [shard 1] compaction - [Compact keyspace1.standard1 a43250e0-c7e2-11ec-99a8-ceabb01e275b] Compacted 1 sstables to [/var/lib/scylla/data/keyspace1/standard1-3c5402f0c7cb11ec9cde0da9d3c6dbe5/md-267-big-Data.db:level=0]. 9MB to 9MB (~99% of original) in 2071ms = 4MB/s. ~35712 total partitions merged to 35691.
2022-04-29T17:34:40+00:00 longevity-cdc-3d-400gb-2022-1-db-node-87d4d86d-6 !    INFO |  [shard 13] compaction - [Compact keyspace1.standard1 a244ffd0-c7e2-11ec-8da9-ceb0b01e275b] Compacted 1 sstables to [/var/lib/scylla/data/keyspace1/standard1-3c5402f0c7cb11ec9cde0da9d3c6dbe5/md-279-big-Data.db:level=0]. 9MB to 9MB (~98% of original) in 5519ms = 1MB/s. ~35712 total partitions merged to 35695.
2022-04-29T17:34:40+00:00 longevity-cdc-3d-400gb-2022-1-db-node-87d4d86d-6 !    INFO |  [shard 7] compaction - [Compact keyspace1.standard1 a3e54250-c7e2-11ec-a3a5-cea5b01e275b] Compacted 1 sstables to [/var/lib/scylla/data/keyspace1/standard1-3c5402f0c7cb11ec9cde0da9d3c6dbe5/md-287-big-Data.db:level=0]. 9MB to 9MB (~99% of original) in 3476ms = 2MB/s. ~35968 total partitions merged to 35909.
```

in several seconds after detecting that compaction is started, using nodetool, request was sent to stop compaction:
```
< t:2022-04-29 17:34:35,577 f:compaction_ops.py l:62   c:root                 p:INFO  > Stopping major compaction with <nodetool stop>
< t:2022-04-29 17:34:35,577 f:compaction_ops.py l:85   c:root                 p:INFO  > Stopping compaction with nodetool stop COMPACTION
< t:2022-04-29 17:34:35,578 f:remote_base.py  l:520  c:RemoteLibSSH2CmdRunner p:DEBUG > Running command "/usr/bin/nodetool  stop COMPACTION "...
< t:2022-04-29 17:34:35,615 f:db_log_reader.py l:113  c:sdcm.db_log_reader   p:DEBUG > 022-04-29T17:34:35+00:00 longevity-cdc-3d-400gb-2022-1-db-node-87d4d86d-6 !    INFO |  [shard 0] compaction_manager - User initiated compaction started on behalf of keyspace1.standard1
< t:2022-04-29 17:35:01,067 f:base.py         l:142  c:RemoteLibSSH2CmdRunner p:DEBUG > Command "/usr/bin/nodetool  stop COMPACTION " finished with status 0
< t:2022-04-29 17:35:01,067 f:cluster.py      l:2628 c:sdcm.cluster_aws     p:DEBUG > Node longevity-cdc-3d-400gb-2022-1-db-node-87d4d86d-6 [54.171.197.212 | 10.0.0.183] (seed: False): Command '/usr/bin/nodetool  stop COMPACTION ' duration -> 25.488694713043515 s
```
according to log running compactions are going to be stopped:
```
2022-04-29T17:34:40+00:00 longevity-cdc-3d-400gb-2022-1-db-node-87d4d86d-6 !    INFO |  [shard 3] compaction_manager - Stopping 2 tasks for 2 ongoing compactions for type=Compact due to user request
2022-04-29T17:34:40+00:00 longevity-cdc-3d-400gb-2022-1-db-node-87d4d86d-6 !    INFO |  [shard 11] compaction_manager - Stopping 1 tasks for 1 ongoing compactions for type=Compact due to user request
2022-04-29T17:34:40+00:00 longevity-cdc-3d-400gb-2022-1-db-node-87d4d86d-6 !    INFO |  [shard 13] compaction_manager - Stopping 1 tasks for 1 ongoing compactions for type=Compact due to user request
2022-04-29T17:34:40+00:00 longevity-cdc-3d-400gb-2022-1-db-node-87d4d86d-6 !    INFO |  [shard 10] compaction_manager - Stopping 1 tasks for 1 ongoing compactions for type=Compact due to user request
2022-04-29T17:34:40+00:00 longevity-cdc-3d-400gb-2022-1-db-node-87d4d86d-6 !    INFO |  [shard 6] compaction_manager - Stopping 2 tasks for 2 ongoing compactions for type=Compact due to user request
2022-04-29T17:34:40+00:00 longevity-cdc-3d-400gb-2022-1-db-node-87d4d86d-6 !    INFO |  [shard 2] compaction_manager - Stopping 1 tasks for 1 ongoing compactions for type=Compact due to user request
2022-04-29T17:34:40+00:00 longevity-cdc-3d-400gb-2022-1-db-node-87d4d86d-6 !    INFO |  [shard 8] compaction_manager - Stopping 1 tasks for 1 ongoing compactions for type=Compact due to user request
2022-04-29T17:34:40+00:00 longevity-cdc-3d-400gb-2022-1-db-node-87d4d86d-6 !    INFO |  [shard 0] compaction_manager - Stopping 3 tasks for 3 ongoing compactions for type=Compact due to user request
2022-04-29T17:34:40+00:00 longevity-cdc-3d-400gb-2022-1-db-node-87d4d86d-6 !    INFO |  [shard 9] compaction_manager - Stopping 1 tasks for 1 ongoing compactions for type=Compact due to user request
2022-04-29T17:34:40+00:00 longevity-cdc-3d-400gb-2022-1-db-node-87d4d86d-6 !    INFO |  [shard 7] compaction_manager - Stopping 2 tasks for 2 ongoing compactions for type=Compact due to user request
2022-04-29T17:34:40+00:00 longevity-cdc-3d-400gb-2022-1-db-node-87d4d86d-6 !    INFO |  [shard 1] compaction_manager - Stopping 1 tasks for 1 ongoing compactions for type=Compact due to user request
2022-04-29T17:34:40+00:00 longevity-cdc-3d-400gb-2022-1-db-node-87d4d86d-6 !    INFO |  [shard 4] compaction_manager - Stopping 2 tasks for 2 ongoing compactions for type=Compact due to user request
2022-04-29T17:34:40+00:00 longevity-cdc-3d-400gb-2022-1-db-node-87d4d86d-6 !    INFO |  [shard 5] compaction_manager - Stopping 1 tasks for 2 ongoing compactions for type=Compact due to user request
2022-04-29T17:34:40+00:00 longevity-cdc-3d-400gb-2022-1-db-node-87d4d86d-6 !    INFO |  [shard 12] compaction_manager - Stopping 1 tasks for 1 ongoing compactions for type=Compact due to user request
```
But also the other compaction (not user triggered) are going to be stopped:
```
2022-04-29T17:34:40+00:00 longevity-cdc-3d-400gb-2022-1-db-node-87d4d86d-6 !    INFO |  [shard 0] compaction_manager - compaction info: Compaction for cdc_test/test_table_postimage was stopped due to: user request: stopping
2022-04-29T17:34:40+00:00 longevity-cdc-3d-400gb-2022-1-db-node-87d4d86d-6 !    INFO |  [shard 9] compaction_manager - compaction info: Compaction for cdc_test/test_table was stopped due to: user request: stopping
2022-04-29T17:34:40+00:00 longevity-cdc-3d-400gb-2022-1-db-node-87d4d86d-6 !    INFO |  [shard 9] compaction - [Compact cdc_test.test_table a6184ef0-c7e2-11ec-a186-ceacb01e275b] Compacting [/var/lib/scylla/data/cdc_test/test_table-1ac58960c57d11eca324dadcffe58642/md-83827-big-Data.db:level=0:origin=memtable,/var/lib/scylla/data/cdc_test/test_table-1ac58960c57d11eca324dadcffe58642/md-83715-big-Data.db:level=0:origin=compaction,/var/lib/scylla/data/cdc_test/test_table-1ac58960c57d11eca324dadcffe58642/md-83743-big-Data.db:level=0:origin=memtable,/var/lib/scylla/data/cdc_test/test_table-1ac58960c57d11eca324dadcffe58642/md-83729-big-Data.db:level=0:origin=memtable,/var/lib/scylla/data/cdc_test/test_table-1ac58960c57d11eca324dadcffe58642/md-83813-big-Data.db:level=0:origin=compaction]
2022-04-29T17:34:40+00:00 longevity-cdc-3d-400gb-2022-1-db-node-87d4d86d-6 !    INFO |  [shard 2] compaction_manager - compaction info: Compaction for cdc_test/test_table was stopped due to: user request: stopping
2022-04-29T17:34:40+00:00 longevity-cdc-3d-400gb-2022-1-db-node-87d4d86d-6 !    INFO |  [shard 6] compaction_manager - compaction info: Compaction for cdc_test/test_table was stopped due to: user request: stopping
2022-04-29T17:34:40+00:00 longevity-cdc-3d-400gb-2022-1-db-node-87d4d86d-6 !    INFO |  [shard 6] compaction_manager - compaction info: Compaction for cdc_test/test_table_preimage was stopped due to: user request: stopping
```

The nemesis failed, because curl command with rest api major compaction request finished only after 30 minutes
```
< t:2022-04-29 18:06:55,193 f:base.py         l:140  c:RemoteLibSSH2CmdRunner p:DEBUG > STDERR:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
< t:2022-04-29 18:06:55,193 f:base.py         l:140  c:RemoteLibSSH2CmdRunner p:DEBUG >                                  Dload  Upload   Total   Spent    Left  Speed
< t:2022-04-29 18:06:55,193 f:base.py         l:140  c:RemoteLibSSH2CmdRunner p:DEBUG > 
< t:2022-04-29 18:06:55,193 f:base.py         l:140  c:RemoteLibSSH2CmdRunner p:DEBUG >   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 127.0.0.1:10000...
< t:2022-04-29 18:06:55,193 f:base.py         l:140  c:RemoteLibSSH2CmdRunner p:DEBUG > * TCP_NODELAY set
< t:2022-04-29 18:06:55,193 f:base.py         l:140  c:RemoteLibSSH2CmdRunner p:DEBUG > * Connected to localhost (127.0.0.1) port 10000 (#0)
< t:2022-04-29 18:06:55,193 f:base.py         l:140  c:RemoteLibSSH2CmdRunner p:DEBUG > > POST /storage_service/keyspace_compaction/keyspace1?cf=standard1 HTTP/1.1
< t:2022-04-29 18:06:55,193 f:base.py         l:140  c:RemoteLibSSH2CmdRunner p:DEBUG > > Host: localhost:10000
< t:2022-04-29 18:06:55,193 f:base.py         l:140  c:RemoteLibSSH2CmdRunner p:DEBUG > > User-Agent: curl/7.68.0
< t:2022-04-29 18:06:55,193 f:base.py         l:140  c:RemoteLibSSH2CmdRunner p:DEBUG > > Accept: */*
< t:2022-04-29 18:06:55,193 f:base.py         l:140  c:RemoteLibSSH2CmdRunner p:DEBUG > > 
< t:2022-04-29 18:06:55,193 f:base.py         l:142  c:RemoteLibSSH2CmdRunner p:DEBUG > Command "curl -v -X POST "http://localhost:10000/storage_service/keyspace_compaction/keyspace1?cf=standard1"" finished with status 0

```

the command didn't get any answer from scylla rest api.

Monitoring node: http://34.244.126.116:3000/d/manager-2-6/longevity-cdc-3d-400gb-test-scylla-per-server-metrics-nemesis-master?orgId=1&from=1650968331137&to=1651283077079

- Restore Monitor Stack command: `$ hydra investigate show-monitor 87d4d86d-7e51-4072-a066-cd2cf4633f8a`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=87d4d86d-7e51-4072-a066-cd2cf4633f8a)
- Show all stored logs command: `$ hydra investigate show-logs 87d4d86d-7e51-4072-a066-cd2cf4633f8a`

## Logs:
- **db-cluster-87d4d86d.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/87d4d86d-7e51-4072-a066-cd2cf4633f8a/20220429_203259/db-cluster-87d4d86d.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/87d4d86d-7e51-4072-a066-cd2cf4633f8a/20220429_203259/db-cluster-87d4d86d.tar.gz)
- **monitor-set-87d4d86d.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/87d4d86d-7e51-4072-a066-cd2cf4633f8a/20220429_203259/monitor-set-87d4d86d.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/87d4d86d-7e51-4072-a066-cd2cf4633f8a/20220429_203259/monitor-set-87d4d86d.tar.gz)
- **loader-set-87d4d86d.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/87d4d86d-7e51-4072-a066-cd2cf4633f8a/20220429_203259/loader-set-87d4d86d.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/87d4d86d-7e51-4072-a066-cd2cf4633f8a/20220429_203259/loader-set-87d4d86d.tar.gz)
- **normal-87d4d86d.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/87d4d86d-7e51-4072-a066-cd2cf4633f8a/20220429_203259/normal-87d4d86d.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/87d4d86d-7e51-4072-a066-cd2cf4633f8a/20220429_203259/normal-87d4d86d.log.tar.gz)
- **summary-87d4d86d.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/87d4d86d-7e51-4072-a066-cd2cf4633f8a/20220429_203259/summary-87d4d86d.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/87d4d86d-7e51-4072-a066-cd2cf4633f8a/20220429_203259/summary-87d4d86d.log.tar.gz)
- **events-87d4d86d.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/87d4d86d-7e51-4072-a066-cd2cf4633f8a/20220429_203259/events-87d4d86d.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/87d4d86d-7e51-4072-a066-cd2cf4633f8a/20220429_203259/events-87d4d86d.log.tar.gz)
- **output-87d4d86d.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/87d4d86d-7e51-4072-a066-cd2cf4633f8a/20220429_203259/output-87d4d86d.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/87d4d86d-7e51-4072-a066-cd2cf4633f8a/20220429_203259/output-87d4d86d.log.tar.gz)
- **debug-87d4d86d.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/87d4d86d-7e51-4072-a066-cd2cf4633f8a/20220429_203259/debug-87d4d86d.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/87d4d86d-7e51-4072-a066-cd2cf4633f8a/20220429_203259/debug-87d4d86d.log.tar.gz)
- **sct-87d4d86d.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/87d4d86d-7e51-4072-a066-cd2cf4633f8a/20220429_203259/sct-87d4d86d.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/87d4d86d-7e51-4072-a066-cd2cf4633f8a/20220429_203259/sct-87d4d86d.log.tar.gz)
- **error-87d4d86d.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/87d4d86d-7e51-4072-a066-cd2cf4633f8a/20220429_203259/error-87d4d86d.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/87d4d86d-7e51-4072-a066-cd2cf4633f8a/20220429_203259/error-87d4d86d.log.tar.gz)
- **critical-87d4d86d.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/87d4d86d-7e51-4072-a066-cd2cf4633f8a/20220429_203259/critical-87d4d86d.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/87d4d86d-7e51-4072-a066-cd2cf4633f8a/20220429_203259/critical-87d4d86d.log.tar.gz)
- **raw_events-87d4d86d.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/87d4d86d-7e51-4072-a066-cd2cf4633f8a/20220429_203259/raw_events-87d4d86d.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/87d4d86d-7e51-4072-a066-cd2cf4633f8a/20220429_203259/raw_events-87d4d86d.log.tar.gz)
- **warning-87d4d86d.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/87d4d86d-7e51-4072-a066-cd2cf4633f8a/20220429_203259/warning-87d4d86d.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/87d4d86d-7e51-4072-a066-cd2cf4633f8a/20220429_203259/warning-87d4d86d.log.tar.gz)
- **email_data-87d4d86d.json.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/87d4d86d-7e51-4072-a066-cd2cf4633f8a/20220429_203259/email_data-87d4d86d.json.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/87d4d86d-7e51-4072-a066-cd2cf4633f8a/20220429_203259/email_data-87d4d86d.json.tar.gz)
- **argus-87d4d86d.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/87d4d86d-7e51-4072-a066-cd2cf4633f8a/20220429_203259/argus-87d4d86d.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/87d4d86d-7e51-4072-a066-cd2cf4633f8a/20220429_203259/argus-87d4d86d.log.tar.gz)
- **left_processes-87d4d86d.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/87d4d86d-7e51-4072-a066-cd2cf4633f8a/20220429_203259/left_processes-87d4d86d.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/87d4d86d-7e51-4072-a066-cd2cf4633f8a/20220429_203259/left_processes-87d4d86d.log.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/enterprise-2022.1/job/longevity/job/longevity-cdc-3d-400gb-test/2/)

**Comment by slivne** [comment] 2022-05-11 10:32
@bhalevy is this a change you did to actually wait for the compactions to end - do we abort them or wait for them to settle down

30 minutes for abort seems long

**Comment by slivne** [comment] 2022-05-11 11:37
30 minutes to wait for compaction to end also seems very long - something may not be working correctly

**Comment by bhalevy** [comment] 2022-05-11 12:40
@aleksbykov 

`nodetool stop COMPACTION` will stop compaction on all keyspaces and tables.

Don't you want to stop compaction only on `keyspace1.standard1`?

**Comment by aleksbykov** [comment] 2022-05-12 04:11
> @aleksbykov
> 
> `nodetool stop COMPACTION` will stop compaction on all keyspaces and tables.
> 
> Don't you want to stop compaction only on `keyspace1.standard1`?

yes,  the idea was to start the major compaction for specific table and then stop it.

**Comment by bhalevy** [comment] 2022-05-12 04:53
> > @aleksbykov
> > `nodetool stop COMPACTION` will stop compaction on all keyspaces and tables.
> > Don't you want to stop compaction only on `keyspace1.standard1`?
> 
> yes, the idea was to start the major compaction for specific table and then stop it.

The it looks like you need to use "nodetool stop COMPACTION keyspace1" to stop it only for this keyspace.
Not that it explains why it wasn't stop :)

**Comment by aleksbykov** [comment] 2022-05-12 05:44
@bhalevy if you run major compaction for single keyspace, then why major compactions started for all keyspaces?

**Comment by bhalevy** [comment] 2022-05-12 06:15
> @bhalevy if you run major compaction for single keyspace, then why major compactions started for all keyspaces?

What makes you think that?

Note that both major and regular compaction use the same compaction type (`COMPACTION` over the api or just `Compact` internally as printed in the logs)

**Comment by aleksbykov** [comment] 2022-05-12 11:23
I see in logs that after  nodetool stop compactio was executed,  several messages that compaction for cdc_test.* was requested to stop

**Comment by bhalevy** [comment] 2022-05-12 11:33
> I see in logs that after nodetool stop compactio was executed, several messages that compaction for cdc_test.* was requested to stop

I believe these are regular compactions stopped by the unrestricted `nodetool stop COMPACTION`.
The reason for that is that major and regular compactions use the same compaction type so they are indistinguishable for stopping purposes.

**Comment by aleksbykov** [comment] 2022-05-12 11:34
So better to run stop compaction for specific keyspace and/or table?

**Comment by bhalevy** [comment] 2022-05-12 11:48
You can specify either the keyspace or the keyspace and table.
It shouldn't matter since there is only one table in the keyspace.
Maybe specifying both is safest in case we ever use more tables in this keyspace in the future.

**Comment by raphaelsc** [comment] 2022-05-12 14:43
> > > @aleksbykov
> > > `nodetool stop COMPACTION` will stop compaction on all keyspaces and tables.
> > > Don't you want to stop compaction only on `keyspace1.standard1`?
> > 
> > 
> > yes, the idea was to start the major compaction for specific table and then stop it.
> 
> The it looks like you need to use "nodetool stop COMPACTION keyspace1" to stop it only for this keyspace. Not that it explains why it wasn't stopped :)

I think nodetool stop only supports type and compaction uuuid. 

We should probably extend it to use stop_keyspace_compaction API if keyspace and/or table were passed as param.

**Comment by bhalevy** [comment] 2022-05-12 17:33
Yikes, I'm afraid you're right, based on https://docs.scylladb.com/operating-scylla/nodetool-commands/stop/

**Comment by raphaelsc** [comment] 2022-05-15 16:19
The problem is that

1) semaphore isn't abortable (in that version), so major task waiting on semaphore has to acquire it first before having a chance to run

2) we're only stopping running major tasks and excluding the ones waiting for a chance to run. 

Therefore, pending major tasks can run to completion once they get permission to run

master has #2 fixed, but can have this improved by using abortable semaphore variant

for branch 2022 and 5.0, we'll need to proceed with a fix similar to 07fba4ab5d24385. and given that semaphore isn't abortable in that version, we'll probably have to make custom jobs use another semaphore as off-strategy may hold semaphore used by major until completion.

**Comment by bhalevy** [comment] 2022-06-12 14:46
@raphaelsc can we close this issue with #10581?

**Comment by raphaelsc** [comment] 2022-06-12 17:34
> @raphaelsc can we close this issue with #10581?

I think so. now pending major compaction will be aborted as soon as it receives abortion signal. thanks

**Closed by raphaelsc** 2022-06-12 17:34 UTC
Labels: compaction

**Comment by bhalevy** [comment] 2022-06-14 06:36
seastar in branch-5.0 doesn't have scylladb/seastar@b1caeb8d8cb12c27776d8dfad3ed3682c5c8ac3e so this fix can't be backported at this time.
