### ISSUE TITLE
The deleted data still exists in the "*-Data.db" file

### ISSUE THREAD

**Issue by hunter7727** [scylladb/scylla#8374] opened 2021-03-30 06:21 UTC
First i insert some data to  scylla. 
Next i delete any data from the scylla.
Then i can't find this deleted data by cql. but when i use nodetool snapshot and SSTabledump command to dump all of the data.I can find this deleted data from "-Data.db" file and this deleted data haven't the mark of tombstone.

**Comment by raphaelsc** [comment] 2021-04-01 22:10
@hunter7727 if deleted data isn't returned via cql, the data is either in commitlog or in another sstable. try nodetool flush and find the deletion marker in any of the existing ssts. i am closing this issue as it's not a bug at all. scylla provides the correct behavior.

**Closed by raphaelsc** 2021-04-01 22:10 UTC

**Comment by nyh** [comment] 2021-04-04 18:45
A short note that might explain to @hunter7727 what's going on:

Scylla stores data using the LSM ("log structured merge tree") architecture: New data is stored in memory (a so-called "memtable") and periodically the current memtable is flushed to a **new** file containing sorted partitions (a so-called "sstable" - sorted string table). The files are immutable - they never change after first being created. Modifications are always written to a new file - not to old files. We do often need to **compact** multiple sstables together (the reason and the details are explained for example in this blog post: https://www.scylladb.com/2018/01/17/compaction-series-space-amplification/), but until such compaction happens you can have old and new versions of the same row in two separate sstables. 

This is exactly what you saw: one sstable contained the original data, and a **different** sstable contains the deletion marker (called a "tombstone") for the same row, with a newer timestamp. When you read this row in CQL, Scylla finds the data in both sstables, notices that the deletion has a newer timestamp than the old data - and decides that the data has been deleted and returns nothing.

So all of this is completely by design, and there appears to be no bug here.
