### ISSUE TITLE
"Greater than" on secondary index does not work but works on underlying MV

### ISSUE THREAD

**Issue by gnumoreno** [scylladb/scylla#6055] opened 2020-03-21 21:22 UTC
*Installation details*
Scylla version (or git commit hash): 3.3.0-202003200707
Cluster size: 1 node
OS (RHEL/CentOS/Ubuntu/AWS AMI):

```
CREATE TABLE IF NOT EXISTS pandemic.covid_world_deaths_by_country_date (
    state text,
    country text,
    latitude float,
    longitude float,
    date date,
    deaths int,
    PRIMARY KEY (country, date))
WITH CLUSTERING ORDER BY (date desc);
CREATE INDEX ON pandemic.covid_world_deaths_by_country_date ((country),deaths);
```
Querying the base table does not work
```
cqlsh> select * from pandemic.covid_world_deaths_by_country_date where country = 'Brazil' and deaths > 1;
InvalidRequest: Error from server: code=2200 [Invalid query] message="Cannot execute this query as it might involve data filtering and thus may have unpredictable performance. If you want to execute this query despite the performance unpredictability, use ALLOW FILTERING"
```
Querying the Index underlying MV works
```
cqlsh> select * from pandemic.covid_world_deaths_by_country_date_deaths_idx_index where country = 'Brazil' and deaths > 1;

 country | deaths | date
---------+--------+------------
  Brazil |      3 | 2020-03-18
  Brazil |      6 | 2020-03-19
  Brazil |     11 | 2020-03-20
```

Related to #5823 ?

### Docker Reproducer
NOTE: gtihub does not let me attach .sh files so renamed to .txt
[db_setup.txt](https://github.com/scylladb/scylla/files/4364105/db_setup.txt)
[docker_setup.txt](https://github.com/scylladb/scylla/files/4364106/docker_setup.txt)

```
mv docker_setup.txt docker_setup.sh
mv db_setup.txt db_setup.sh
chmod +x docker_setup.sh
./docker_setup.sh
select * from pandemic.covid_world_deaths_by_country_date where country = 'Brazil' and deaths > 1;
select * from pandemic.covid_world_deaths_by_country_date_deaths_idx_index where country = 'Brazil' and deaths > 1;
```

PS.: Pardon my horrible programming.
@psarna

**Comment by psarna** [comment] 2020-03-22 07:11
It's a duplicate of https://github.com/scylladb/scylla/issues/5547 - I'll close this one to avoid confusion.

**Closed by psarna** 2020-03-22 07:11 UTC
