### ISSUE TITLE
coredump during terminate and replace nemesis

### ISSUE THREAD

**Issue by yarongilor** [scylladb/scylla#5061] opened 2019-09-19 07:16 UTC
Installation details
Scylla version (or git commit hash): 3.1.0.rc7-0.20190915.024d1563a
Cluster size: 6
OS (RHEL/CentOS/Ubuntu/AWS AMI): ami-0a01b94dffe4bcc0d

scenario: 50GB longevity - during terminate and replace nemesis of one node, there was a core dump on another node.

failure scenario and error:
```
$ grep -v 'ChaosMonkey on target' sct.log | grep -i 'found coredump\|Set current_disruption\|segmentation\|<<<<<<<<<\|p:ERROR > Traceback'
< t:2019-09-16 15:10:47,592 f:nemesis.py      l:338  c:sdcm.nemesis         p:DEBUG > sdcm.nemesis.ChaosMonkey: Set current_disruption -> MajorCompaction Node longevity-tls-50gb-4d-3-1-db-node-5979c9a0-3 [52.213.136.181 | 10.0.69.237] (seed: False)
< t:2019-09-16 15:14:34,039 f:nemesis.py      l:595  c:sdcm.nemesis         p:INFO  > sdcm.nemesis.ChaosMonkey: <<<<<<<<<<<<<Finished random_disrupt_method major_compaction
< t:2019-09-16 15:24:25,389 f:nemesis.py      l:338  c:sdcm.nemesis         p:DEBUG > sdcm.nemesis.ChaosMonkey: Set current_disruption -> CorruptThenRebuild Node longevity-tls-50gb-4d-3-1-db-node-5979c9a0-4 [34.240.105.72 | 10.0.159.212] (seed: False)
< t:2019-09-16 15:27:22,397 f:nemesis.py      l:595  c:sdcm.nemesis         p:INFO  > sdcm.nemesis.ChaosMonkey: <<<<<<<<<<<<<Finished random_disrupt_method destroy_data_then_rebuild
< t:2019-09-16 15:33:04,114 f:nemesis.py      l:338  c:sdcm.nemesis         p:DEBUG > sdcm.nemesis.ChaosMonkey: Set current_disruption -> HardRebootNode Node longevity-tls-50gb-4d-3-1-db-node-5979c9a0-2 [52.215.86.169 | 10.0.188.94] (seed: False)
< t:2019-09-16 15:36:28,320 f:nemesis.py      l:595  c:sdcm.nemesis         p:INFO  > sdcm.nemesis.ChaosMonkey: <<<<<<<<<<<<<Finished random_disrupt_method hard_reboot_node
< t:2019-09-16 15:46:42,551 f:nemesis.py      l:338  c:sdcm.nemesis         p:DEBUG > sdcm.nemesis.ChaosMonkey: Set current_disruption -> TruncateMonkey Node longevity-tls-50gb-4d-3-1-db-node-5979c9a0-4 [34.240.105.72 | 10.0.159.212] (seed: False)
< t:2019-09-16 15:48:11,538 f:nemesis.py      l:595  c:sdcm.nemesis         p:INFO  > sdcm.nemesis.ChaosMonkey: <<<<<<<<<<<<<Finished random_disrupt_method truncate
< t:2019-09-16 16:03:53,536 f:nemesis.py      l:338  c:sdcm.nemesis         p:DEBUG > sdcm.nemesis.ChaosMonkey: Set current_disruption -> StopWaitStartService Node longevity-tls-50gb-4d-3-1-db-node-5979c9a0-2 [52.215.86.169 | 10.0.188.94] (seed: False)
< t:2019-09-16 16:10:09,154 f:nemesis.py      l:595  c:sdcm.nemesis         p:INFO  > sdcm.nemesis.ChaosMonkey: <<<<<<<<<<<<<Finished random_disrupt_method stop_wait_start_scylla_server
< t:2019-09-16 16:26:43,970 f:nemesis.py      l:338  c:sdcm.nemesis         p:DEBUG > sdcm.nemesis.ChaosMonkey: Set current_disruption -> StopStartService Node longevity-tls-50gb-4d-3-1-db-node-5979c9a0-5 [34.244.194.166 | 10.0.63.76] (seed: False)
< t:2019-09-16 16:28:12,008 f:nemesis.py      l:595  c:sdcm.nemesis         p:INFO  > sdcm.nemesis.ChaosMonkey: <<<<<<<<<<<<<Finished random_disrupt_method stop_start_scylla_server
< t:2019-09-16 16:45:27,866 f:nemesis.py      l:338  c:sdcm.nemesis         p:DEBUG > sdcm.nemesis.ChaosMonkey: Set current_disruption -> SnapshotOperations
< t:2019-09-16 16:47:35,672 f:nemesis.py      l:595  c:sdcm.nemesis         p:INFO  > sdcm.nemesis.ChaosMonkey: <<<<<<<<<<<<<Finished random_disrupt_method snapshot_operations
< t:2019-09-16 17:04:41,135 f:nemesis.py      l:338  c:sdcm.nemesis         p:DEBUG > sdcm.nemesis.ChaosMonkey: Set current_disruption -> StopStartService Node longevity-tls-50gb-4d-3-1-db-node-5979c9a0-2 [52.215.86.169 | 10.0.188.94] (seed: False)
< t:2019-09-16 17:06:08,498 f:nemesis.py      l:595  c:sdcm.nemesis         p:INFO  > sdcm.nemesis.ChaosMonkey: <<<<<<<<<<<<<Finished random_disrupt_method stop_start_scylla_server
< t:2019-09-16 17:23:30,725 f:nemesis.py      l:338  c:sdcm.nemesis         p:DEBUG > sdcm.nemesis.ChaosMonkey: Set current_disruption -> RestartThenRepairNode Node longevity-tls-50gb-4d-3-1-db-node-5979c9a0-5 [34.244.194.166 | 10.0.63.76] (seed: False)
< t:2019-09-16 18:17:58,268 f:nemesis.py      l:595  c:sdcm.nemesis         p:INFO  > sdcm.nemesis.ChaosMonkey: <<<<<<<<<<<<<Finished random_disrupt_method restart_then_repair_node
< t:2019-09-16 18:35:27,271 f:nemesis.py      l:338  c:sdcm.nemesis         p:DEBUG > sdcm.nemesis.ChaosMonkey: Set current_disruption -> HardRebootNode Node longevity-tls-50gb-4d-3-1-db-node-5979c9a0-4 [34.240.105.72 | 10.0.159.212] (seed: False)
< t:2019-09-16 18:39:05,460 f:nemesis.py      l:595  c:sdcm.nemesis         p:INFO  > sdcm.nemesis.ChaosMonkey: <<<<<<<<<<<<<Finished random_disrupt_method hard_reboot_node
< t:2019-09-16 18:56:16,458 f:nemesis.py      l:338  c:sdcm.nemesis         p:DEBUG > sdcm.nemesis.ChaosMonkey: Set current_disruption -> Drainer Node longevity-tls-50gb-4d-3-1-db-node-5979c9a0-4 [34.240.105.72 | 10.0.159.212] (seed: False)
< t:2019-09-16 19:03:13,773 f:nemesis.py      l:595  c:sdcm.nemesis         p:INFO  > sdcm.nemesis.ChaosMonkey: <<<<<<<<<<<<<Finished random_disrupt_method nodetool_drain
< t:2019-09-16 19:20:29,904 f:nemesis.py      l:338  c:sdcm.nemesis         p:DEBUG > sdcm.nemesis.ChaosMonkey: Set current_disruption -> Refresh keyspace1.standard1 on longevity-tls-50gb-4d-3-1-db-node-5979c9a0-6
< t:2019-09-16 19:23:32,913 f:nemesis.py      l:595  c:sdcm.nemesis         p:INFO  > sdcm.nemesis.ChaosMonkey: <<<<<<<<<<<<<Finished random_disrupt_method nodetool_refresh
< t:2019-09-16 19:40:54,459 f:nemesis.py      l:338  c:sdcm.nemesis         p:DEBUG > sdcm.nemesis.ChaosMonkey: Set current_disruption -> MultipleHardRebootNode Node longevity-tls-50gb-4d-3-1-db-node-5979c9a0-5 [34.249.239.65 | 10.0.63.76] (seed: False)
< t:2019-09-16 19:43:53,658 f:nemesis.py      l:338  c:sdcm.nemesis         p:DEBUG > sdcm.nemesis.ChaosMonkey: Set current_disruption -> MultipleHardRebootNode Node longevity-tls-50gb-4d-3-1-db-node-5979c9a0-5 [34.249.239.65 | 10.0.63.76] (seed: False)
< t:2019-09-16 19:46:47,657 f:nemesis.py      l:338  c:sdcm.nemesis         p:DEBUG > sdcm.nemesis.ChaosMonkey: Set current_disruption -> MultipleHardRebootNode Node longevity-tls-50gb-4d-3-1-db-node-5979c9a0-5 [34.249.239.65 | 10.0.63.76] (seed: False)
< t:2019-09-16 19:49:58,182 f:nemesis.py      l:338  c:sdcm.nemesis         p:DEBUG > sdcm.nemesis.ChaosMonkey: Set current_disruption -> MultipleHardRebootNode Node longevity-tls-50gb-4d-3-1-db-node-5979c9a0-5 [34.249.239.65 | 10.0.63.76] (seed: False)
< t:2019-09-16 19:52:26,328 f:nemesis.py      l:338  c:sdcm.nemesis         p:DEBUG > sdcm.nemesis.ChaosMonkey: Set current_disruption -> MultipleHardRebootNode Node longevity-tls-50gb-4d-3-1-db-node-5979c9a0-5 [34.249.239.65 | 10.0.63.76] (seed: False)
< t:2019-09-16 19:56:34,122 f:nemesis.py      l:338  c:sdcm.nemesis         p:DEBUG > sdcm.nemesis.ChaosMonkey: Set current_disruption -> MultipleHardRebootNode Node longevity-tls-50gb-4d-3-1-db-node-5979c9a0-5 [34.249.239.65 | 10.0.63.76] (seed: False)
< t:2019-09-16 19:59:50,992 f:nemesis.py      l:338  c:sdcm.nemesis         p:DEBUG > sdcm.nemesis.ChaosMonkey: Set current_disruption -> MultipleHardRebootNode Node longevity-tls-50gb-4d-3-1-db-node-5979c9a0-5 [34.249.239.65 | 10.0.63.76] (seed: False)
< t:2019-09-16 20:03:08,620 f:nemesis.py      l:595  c:sdcm.nemesis         p:INFO  > sdcm.nemesis.ChaosMonkey: <<<<<<<<<<<<<Finished random_disrupt_method multiple_hard_reboot_node
< t:2019-09-16 20:20:27,436 f:nemesis.py      l:338  c:sdcm.nemesis         p:DEBUG > sdcm.nemesis.ChaosMonkey: Set current_disruption -> SoftRebootNode Node longevity-tls-50gb-4d-3-1-db-node-5979c9a0-4 [34.240.105.72 | 10.0.159.212] (seed: False)
< t:2019-09-16 20:23:57,758 f:nemesis.py      l:595  c:sdcm.nemesis         p:INFO  > sdcm.nemesis.ChaosMonkey: <<<<<<<<<<<<<Finished random_disrupt_method soft_reboot_node
< t:2019-09-16 20:41:29,318 f:nemesis.py      l:595  c:sdcm.nemesis         p:INFO  > sdcm.nemesis.ChaosMonkey: <<<<<<<<<<<<<Finished random_disrupt_method nodetool_enospc
< t:2019-09-16 20:58:51,638 f:nemesis.py      l:338  c:sdcm.nemesis         p:DEBUG > sdcm.nemesis.ChaosMonkey: Set current_disruption -> Drainer Node longevity-tls-50gb-4d-3-1-db-node-5979c9a0-4 [34.240.105.72 | 10.0.159.212] (seed: False)
< t:2019-09-16 21:05:29,987 f:nemesis.py      l:595  c:sdcm.nemesis         p:INFO  > sdcm.nemesis.ChaosMonkey: <<<<<<<<<<<<<Finished random_disrupt_method nodetool_drain
< t:2019-09-16 21:22:26,326 f:nemesis.py      l:338  c:sdcm.nemesis         p:DEBUG > sdcm.nemesis.ChaosMonkey: Set current_disruption -> Refresh keyspace1.standard1 on longevity-tls-50gb-4d-3-1-db-node-5979c9a0-3
< t:2019-09-16 21:23:49,807 f:nemesis.py      l:595  c:sdcm.nemesis         p:INFO  > sdcm.nemesis.ChaosMonkey: <<<<<<<<<<<<<Finished random_disrupt_method nodetool_refresh
< t:2019-09-16 21:41:09,529 f:nemesis.py      l:338  c:sdcm.nemesis         p:DEBUG > sdcm.nemesis.ChaosMonkey: Set current_disruption -> SnapshotOperations
< t:2019-09-16 21:44:24,670 f:nemesis.py      l:595  c:sdcm.nemesis         p:INFO  > sdcm.nemesis.ChaosMonkey: <<<<<<<<<<<<<Finished random_disrupt_method snapshot_operations
< t:2019-09-16 22:01:37,394 f:nemesis.py      l:338  c:sdcm.nemesis         p:DEBUG > sdcm.nemesis.ChaosMonkey: Set current_disruption -> CorruptThenRebuild Node longevity-tls-50gb-4d-3-1-db-node-5979c9a0-6 [52.214.107.136 | 10.0.42.134] (seed: False)
< t:2019-09-16 22:49:59,386 f:nemesis.py      l:595  c:sdcm.nemesis         p:INFO  > sdcm.nemesis.ChaosMonkey: <<<<<<<<<<<<<Finished random_disrupt_method destroy_data_then_rebuild
< t:2019-09-16 23:07:32,586 f:nemesis.py      l:338  c:sdcm.nemesis         p:DEBUG > sdcm.nemesis.ChaosMonkey: Set current_disruption -> StopStartService Node longevity-tls-50gb-4d-3-1-db-node-5979c9a0-6 [52.214.107.136 | 10.0.42.134] (seed: False)
< t:2019-09-16 23:09:04,928 f:nemesis.py      l:595  c:sdcm.nemesis         p:INFO  > sdcm.nemesis.ChaosMonkey: <<<<<<<<<<<<<Finished random_disrupt_method stop_start_scylla_server
< t:2019-09-16 23:26:42,512 f:nemesis.py      l:338  c:sdcm.nemesis         p:DEBUG > sdcm.nemesis.ChaosMonkey: Set current_disruption -> ShowTopPartitions
< t:2019-09-16 23:28:37,797 f:nemesis.py      l:595  c:sdcm.nemesis         p:INFO  > sdcm.nemesis.ChaosMonkey: <<<<<<<<<<<<<Finished random_disrupt_method show_toppartitions
< t:2019-09-16 23:46:04,883 f:nemesis.py      l:338  c:sdcm.nemesis         p:DEBUG > sdcm.nemesis.ChaosMonkey: Set current_disruption -> StopWaitStartService Node longevity-tls-50gb-4d-3-1-db-node-5979c9a0-4 [34.240.105.72 | 10.0.159.212] (seed: False)
< t:2019-09-16 23:52:47,580 f:nemesis.py      l:595  c:sdcm.nemesis         p:INFO  > sdcm.nemesis.ChaosMonkey: <<<<<<<<<<<<<Finished random_disrupt_method stop_wait_start_scylla_server
< t:2019-09-17 00:10:44,778 f:nemesis.py      l:338  c:sdcm.nemesis         p:DEBUG > sdcm.nemesis.ChaosMonkey: Set current_disruption -> MajorCompaction Node longevity-tls-50gb-4d-3-1-db-node-5979c9a0-3 [52.213.136.181 | 10.0.69.237] (seed: False)
< t:2019-09-17 00:54:58,298 f:nemesis.py      l:595  c:sdcm.nemesis         p:INFO  > sdcm.nemesis.ChaosMonkey: <<<<<<<<<<<<<Finished random_disrupt_method major_compaction
< t:2019-09-17 01:12:30,780 f:nemesis.py      l:338  c:sdcm.nemesis         p:DEBUG > sdcm.nemesis.ChaosMonkey: Set current_disruption -> TruncateMonkey Node longevity-tls-50gb-4d-3-1-db-node-5979c9a0-2 [52.215.86.169 | 10.0.188.94] (seed: False)
< t:2019-09-17 01:13:39,716 f:nemesis.py      l:1071 c:sdcm.nemesis         p:ERROR > Traceback (most recent call last):
< t:2019-09-17 01:30:45,752 f:nemesis.py      l:338  c:sdcm.nemesis         p:DEBUG > sdcm.nemesis.ChaosMonkey: Set current_disruption -> RestartThenRepairNode Node longevity-tls-50gb-4d-3-1-db-node-5979c9a0-3 [52.213.136.181 | 10.0.69.237] (seed: False)
< t:2019-09-17 03:07:00,343 f:nemesis.py      l:595  c:sdcm.nemesis         p:INFO  > sdcm.nemesis.ChaosMonkey: <<<<<<<<<<<<<Finished random_disrupt_method restart_then_repair_node
< t:2019-09-17 03:24:32,591 f:nemesis.py      l:338  c:sdcm.nemesis         p:DEBUG > sdcm.nemesis.ChaosMonkey: Set current_disruption -> NoCorruptRepair Node longevity-tls-50gb-4d-3-1-db-node-5979c9a0-3 [34.247.162.93 | 10.0.69.237] (seed: False)
< t:2019-09-17 04:31:46,450 f:nemesis.py      l:595  c:sdcm.nemesis         p:INFO  > sdcm.nemesis.ChaosMonkey: <<<<<<<<<<<<<Finished random_disrupt_method no_corrupt_repair
< t:2019-09-17 04:48:51,306 f:nemesis.py      l:338  c:sdcm.nemesis         p:DEBUG > sdcm.nemesis.ChaosMonkey: Set current_disruption -> RestartThenRepairNode Node longevity-tls-50gb-4d-3-1-db-node-5979c9a0-5 [34.249.239.65 | 10.0.63.76] (seed: False)
< t:2019-09-17 06:39:52,621 f:nemesis.py      l:595  c:sdcm.nemesis         p:INFO  > sdcm.nemesis.ChaosMonkey: <<<<<<<<<<<<<Finished random_disrupt_method restart_then_repair_node
< t:2019-09-17 06:57:48,999 f:nemesis.py      l:338  c:sdcm.nemesis         p:DEBUG > sdcm.nemesis.ChaosMonkey: Set current_disruption -> CorruptThenRepair Node longevity-tls-50gb-4d-3-1-db-node-5979c9a0-5 [34.248.223.143 | 10.0.63.76] (seed: False)
< t:2019-09-17 08:41:54,842 f:nemesis.py      l:595  c:sdcm.nemesis         p:INFO  > sdcm.nemesis.ChaosMonkey: <<<<<<<<<<<<<Finished random_disrupt_method destroy_data_then_repair
< t:2019-09-17 08:59:56,451 f:nemesis.py      l:338  c:sdcm.nemesis         p:DEBUG > sdcm.nemesis.ChaosMonkey: Set current_disruption -> Drainer Node longevity-tls-50gb-4d-3-1-db-node-5979c9a0-2 [52.215.86.169 | 10.0.188.94] (seed: False)
< t:2019-09-17 09:05:36,128 f:nemesis.py      l:595  c:sdcm.nemesis         p:INFO  > sdcm.nemesis.ChaosMonkey: <<<<<<<<<<<<<Finished random_disrupt_method nodetool_drain
< t:2019-09-17 09:24:28,727 f:nemesis.py      l:338  c:sdcm.nemesis         p:DEBUG > sdcm.nemesis.ChaosMonkey: Set current_disruption -> NodetoolCleanupMonkey Node longevity-tls-50gb-4d-3-1-db-node-5979c9a0-1 [54.154.21.39 | 10.0.169.31] (seed: True)
< t:2019-09-17 11:10:13,166 f:nemesis.py      l:338  c:sdcm.nemesis         p:DEBUG > sdcm.nemesis.ChaosMonkey: Set current_disruption -> NodetoolCleanupMonkey Node longevity-tls-50gb-4d-3-1-db-node-5979c9a0-2 [52.215.86.169 | 10.0.188.94] (seed: False)
< t:2019-09-17 14:21:37,638 f:nemesis.py      l:1071 c:sdcm.nemesis         p:ERROR > Traceback (most recent call last):
< t:2019-09-17 14:39:55,846 f:nemesis.py      l:338  c:sdcm.nemesis         p:DEBUG > sdcm.nemesis.ChaosMonkey: Set current_disruption -> ValidateHintedHandoffShortDowntime
< t:2019-09-17 14:43:56,706 f:nemesis.py      l:1071 c:sdcm.nemesis         p:ERROR > Traceback (most recent call last):
< t:2019-09-17 15:02:02,552 f:nemesis.py      l:338  c:sdcm.nemesis         p:DEBUG > sdcm.nemesis.ChaosMonkey: Set current_disruption -> ShowTopPartitions
< t:2019-09-17 15:04:29,990 f:nemesis.py      l:1071 c:sdcm.nemesis         p:ERROR > Traceback (most recent call last):
< t:2019-09-17 15:22:51,063 f:nemesis.py      l:338  c:sdcm.nemesis         p:DEBUG > sdcm.nemesis.ChaosMonkey: Set current_disruption -> SoftRebootNode Node longevity-tls-50gb-4d-3-1-db-node-5979c9a0-5 [34.248.223.143 | 10.0.63.76] (seed: False)
< t:2019-09-17 16:24:36,211 f:nemesis.py      l:1071 c:sdcm.nemesis         p:ERROR > Traceback (most recent call last):
< t:2019-09-17 16:42:46,891 f:nemesis.py      l:338  c:sdcm.nemesis         p:DEBUG > sdcm.nemesis.ChaosMonkey: Set current_disruption -> TruncateMonkey Node longevity-tls-50gb-4d-3-1-db-node-5979c9a0-5 [34.248.223.143 | 10.0.63.76] (seed: False)
< t:2019-09-17 16:44:12,313 f:nemesis.py      l:1071 c:sdcm.nemesis         p:ERROR > Traceback (most recent call last):
< t:2019-09-17 17:02:19,591 f:nemesis.py      l:338  c:sdcm.nemesis         p:DEBUG > sdcm.nemesis.ChaosMonkey: Set current_disruption -> MajorCompaction Node longevity-tls-50gb-4d-3-1-db-node-5979c9a0-6 [52.214.107.136 | 10.0.42.134] (seed: False)
< t:2019-09-17 22:48:38,894 f:nemesis.py      l:595  c:sdcm.nemesis         p:INFO  > sdcm.nemesis.ChaosMonkey: <<<<<<<<<<<<<Finished random_disrupt_method major_compaction
< t:2019-09-17 23:07:23,903 f:nemesis.py      l:338  c:sdcm.nemesis         p:DEBUG > sdcm.nemesis.ChaosMonkey: Set current_disruption -> CorruptThenRepair Node longevity-tls-50gb-4d-3-1-db-node-5979c9a0-4 [34.240.105.72 | 10.0.159.212] (seed: False)
< t:2019-09-18 02:55:23,098 f:nemesis.py      l:595  c:sdcm.nemesis         p:INFO  > sdcm.nemesis.ChaosMonkey: <<<<<<<<<<<<<Finished random_disrupt_method destroy_data_then_repair
< t:2019-09-18 03:15:02,621 f:nemesis.py      l:595  c:sdcm.nemesis         p:INFO  > sdcm.nemesis.ChaosMonkey: <<<<<<<<<<<<<Finished random_disrupt_method nodetool_enospc
< t:2019-09-18 03:34:41,668 f:nemesis.py      l:595  c:sdcm.nemesis         p:INFO  > sdcm.nemesis.ChaosMonkey: <<<<<<<<<<<<<Finished random_disrupt_method nodetool_enospc
< t:2019-09-18 03:53:38,492 f:nemesis.py      l:338  c:sdcm.nemesis         p:DEBUG > sdcm.nemesis.ChaosMonkey: Set current_disruption -> ModifyTablePropertiesDclocalReadRepairChance Node longevity-tls-50gb-4d-3-1-db-node-5979c9a0-5 [34.248.223.143 | 10.0.63.76] (seed: False)
< t:2019-09-18 03:54:08,948 f:nemesis.py      l:595  c:sdcm.nemesis         p:INFO  > sdcm.nemesis.ChaosMonkey: <<<<<<<<<<<<<Finished random_disrupt_method modify_table
< t:2019-09-18 04:13:20,674 f:nemesis.py      l:338  c:sdcm.nemesis         p:DEBUG > sdcm.nemesis.ChaosMonkey: Set current_disruption -> TruncateMonkey Node longevity-tls-50gb-4d-3-1-db-node-5979c9a0-3 [34.247.162.93 | 10.0.69.237] (seed: False)
< t:2019-09-18 04:15:29,804 f:nemesis.py      l:1071 c:sdcm.nemesis         p:ERROR > Traceback (most recent call last):
< t:2019-09-18 04:35:06,021 f:nemesis.py      l:338  c:sdcm.nemesis         p:DEBUG > sdcm.nemesis.ChaosMonkey: Set current_disruption -> ModifyTablePropertiesCompaction Node longevity-tls-50gb-4d-3-1-db-node-5979c9a0-5 [34.248.223.143 | 10.0.63.76] (seed: False)
< t:2019-09-18 04:35:34,818 f:nemesis.py      l:595  c:sdcm.nemesis         p:INFO  > sdcm.nemesis.ChaosMonkey: <<<<<<<<<<<<<Finished random_disrupt_method modify_table
< t:2019-09-18 04:54:58,207 f:nemesis.py      l:338  c:sdcm.nemesis         p:DEBUG > sdcm.nemesis.ChaosMonkey: Set current_disruption -> TerminateAndReplaceNode Node longevity-tls-50gb-4d-3-1-db-node-5979c9a0-4 [34.240.105.72 | 10.0.159.212] (seed: False)
< t:2019-09-18 06:40:22,124 f:cluster.py      l:833  c:sdcm.cluster         p:DEBUG > Node longevity-tls-50gb-4d-3-1-db-node-5979c9a0-6 [52.214.107.136 | 10.0.42.134] (seed: False): Found coredump file: /var/lib/systemd/coredump/core.scylla.996.fda02d2cfd394d57ad5130894d4813bc.64535.1568788699000000
< t:2019-09-18 06:45:46,572 f:nemesis.py      l:1071 c:sdcm.nemesis         p:ERROR > Traceback (most recent call last):
```
logs:
coredump - 
https://storage.cloud.google.com/upload.scylladb.com/core.scylla.996.fda02d2cfd394d57ad5130894d4813bc.64535.1568788699000000/core.scylla.996.fda02d2cfd394d57ad5130894d4813bc.64535.1568788699000000.gz

sct log -
scratch.scylladb.com/issues/sct_13_03_18_09_2019.log.gz

**Comment by yarongilor** [comment] 2019-09-19 10:12
unfortunately the coredump was not uploaded and not exist on node anymore

**Comment by bhalevy** [comment] 2019-09-19 10:26
> Scylla version (or git commit hash): 3.1

@yarongilor please be more specific about the version

> unfortunately the coredump was not uploaded and not exist on node anymore

Hmm, is there a backtrace in the node log that you can decode?
Otherwise, there's nothing much we can do with this issue.

**Comment by yarongilor** [comment] 2019-09-19 11:32
the information i could find is this:
```
backtrace= PID: 64535 (scylla)
UID: 996 (scylla)
GID: 1001 (scylla)
Signal: 11 (SEGV)
Timestamp: Wed 2019-09-18 06:38:19 UTC (2min 1s ago)
Command Line: /usr/bin/scylla --blocked-reactor-notify-ms 500 --abort-on-lsa-bad-alloc 1 --abort-on-seastar-bad-alloc --log-to-syslog 1 --log-to-stdout 0 --default-log-level info --network-stack posix --io-properties-file=/etc/scylla.d/io_properties.yaml --cpuset 1-7,9-15
Executable: /opt/scylladb/libexec/scylla
Control Group: /
Boot ID: fda02d2cfd394d57ad5130894d4813bc
Machine ID: df877a200226bc47d06f26dae0736ec9
Hostname: ip-10-0-42-134.eu-west-1.compute.internal
Coredump: /var/lib/systemd/coredump/core.scylla.996.fda02d2cfd394d57ad5130894d4813bc.64535.1568788699000000
Message: Process 64535 (scylla) of user 996 dumped core.

Stack trace of thread 64548:
#0 0x0000000004028dd4 _ZN7seastar6memory10small_pool8allocateEv (scylla)
#1 0x0000006400000032 n/a (n/a)
```

**Comment by nyh** [comment] 2019-09-19 12:40
This, a SIGSEGV deep inside the memory allocation code, seems superficially similar to #4973. I don't know if the causes are related though....

**Comment by bhalevy** [comment] 2019-09-23 12:13
marking all possible memory corruptions as showstoppers...

**Comment by eliransin** [comment] 2019-09-23 15:41
The core is inaccessible:
tried:
1. 
```
https://storage.cloud.google.com/upload.scylladb.com/core.scylla.996.fda02d2cfd394d57ad5130894d4813bc.64535.1568788699000000/core.scylla.996.fda02d2cfd394d57ad5130894d4813bc.64535.1568788699000000.gz
```
No such object ... - in browser

2. 
```
gsutil cp gs://upload.scylladb.com/core.scylla.996.fda02d2cfd394d57ad5130894d4813bc.64535.1568788699000000/core.scylla.996.fda02d2cfd394d57ad5130894d4813bc.64535.1568788699000000.gz .
```
got: 
```
CommandException: No URLs matched: gs://upload.scylladb.com/core.scylla.996.fda02d2cfd394d57ad5130894d4813bc.64535.1568788699000000/core.scylla.996.fda02d2cfd394d57ad5130894d4813bc.64535.1568788699000000.gz
```

@yarongilor how do I access the core?

**Comment by eliransin** [comment] 2019-09-23 15:42
@yarongilor I just saw that there is no core.

**Comment by eliransin** [comment] 2019-09-23 15:49
From the printout it is the exact same line as #4973:
```
1117	    _free = _free->next;
   0x0000000004028dd4 <+164>:	mov    (%rax),%rdx
```
If there is no core I suggest to close it since we can't get much more out of it except for going through each line of the log.

**Comment by yarongilor** [comment] 2019-09-23 20:21
according to this above comment, the coredump was lost: 
https://github.com/scylladb/scylla/issues/5061#issuecomment-533064382

yet, it may be reproduced here:
https://github.com/scylladb/scylla/issues/5086

**Comment by slivne** [comment] 2019-09-25 11:00
since there is no core closing

**Closed by slivne** 2019-09-25 11:00 UTC
Labels: bug, high, showstopper
