### ISSUE TITLE
coredump: seastar::append_challenged_posix_file_impl::~append_challenged_posix_file_impl(): Assertion `_closing_state == state::closed' failed.

### ISSUE THREAD

**Issue by amoskong** [scylladb/scylla#5325] opened 2019-11-21 12:14 UTC
*Installation details*
Scylla version (or git commit hash): 3.2.rc1-0.20191119.8c1474c039
Cluster size: 6
OS (RHEL/CentOS/Ubuntu/AWS AMI):
- ami-0d768d9761df102b4 (eu-west-1)
- i3.4xlarge

### Description:
- In longevity-10gb-3h of 3.2, coredump occurred in enpsc nemesis.
- The target node touchs enpsc error, then the node started automatically. coredump occurred in start

### Coredump files:
- the target node kept restarted many times, and there is no coredump file generated actually. Sct didn't find, I also didn't find manually.

### Test job:
- https://jenkins.scylladb.com/job/scylla-staging/job/amos/job/longevity-10gb-3h-3.2/16/

### Living cluster: 
- https://eu-west-1.console.aws.amazon.com/ec2/home?region=eu-west-1#Instances:search=15007c74;sort=instanceId
- longevity-10gb-3h-replace--db-node-15007c74-1 [34.244.200.74 | 10.0.127.196]
- longevity-10gb-3h-replace--db-node-15007c74-2 [34.242.63.227 | 10.0.8.233]
- longevity-10gb-3h-replace--db-node-15007c74-3 [34.247.195.54 | 10.0.177.109]
- longevity-10gb-3h-replace--db-node-15007c74-4 [34.246.194.108 | 10.0.114.78]
- longevity-10gb-3h-replace--db-node-15007c74-5 [34.242.18.26 | 10.0.6.128]
- longevity-10gb-3h-replace--db-node-15007c74-6 [34.254.183.21 | 10.0.237.237]

###  The relevant log messages with time stamps of the issue

```
### Touch enospc during running ...

11-21 11:31:22 ip-10-0-237-237 scylla[3515]:  [shard 2] storage_service - Shutting down communications due to I/O errors until operator intervention
11-21 11:31:22 ip-10-0-237-237 systemd[1]: scylla-server.service: main process exited, code=killed, status=6/ABRT
11-21 11:31:22 ip-10-0-237-237 systemd[1]: Unit scylla-server.service entered failed state.
11-21 11:31:22 ip-10-0-237-237 systemd[1]: scylla-server.service failed.
11-21 11:31:22 ip-10-0-237-237 systemd[1]: scylla-server.service holdoff time over, scheduling restart.
11-21 11:31:23 ip-10-0-237-237 systemd[1]: Stopped Scylla Server.

### Restarted automitically

11-21 11:31:24 ip-10-0-237-237 scylla[6896]: Scylla version 3.2.rc1-0.20191119.8c1474c039 starting ...
11-21 11:31:24 ip-10-0-237-237 scylla[6896]: command used: "/usr/bin/scylla --blocked-reactor-notify-ms 500 --abort-on-lsa-bad-alloc 1 --abort-on-seastar-bad-alloc --log-to-syslog 1 --
11-21 11:31:24 ip-10-0-237-237 scylla[6896]: parsed command line options: [blocked-reactor-notify-ms: 500, abort-on-lsa-bad-alloc: 1, abort-on-seastar-bad-alloc, log-to-syslog: 1, log-
11-21 11:31:24 ip-10-0-237-237 scylla[6896]:  [shard 0] init - installing SIGHUP handler
11-21 11:31:24 ip-10-0-237-237 scylla[6896]:  [shard 0] init - Scylla version 3.2.rc1-0.20191119.8c1474c039 starting.
11-21 11:31:24 ip-10-0-237-237 scylla[6896]:  [shard 0] init - starting prometheus API server
11-21 11:31:24 ip-10-0-237-237 scylla[6896]:  [shard 0] init - creating tracing
11-21 11:31:24 ip-10-0-237-237 scylla[6896]:  [shard 0] init - creating snitch
11-21 11:31:24 ip-10-0-237-237 scylla[6896]:  [shard 0] snitch_logger - Ec2Snitch using region: eu-west, zone: 1a.
11-21 11:31:24 ip-10-0-237-237 scylla[6896]:  [shard 0] init - determining DNS name
11-21 11:31:24 ip-10-0-237-237 scylla[6896]:  [shard 0] init - starting API server
11-21 11:31:24 ip-10-0-237-237 scylla[6896]:  [shard 0] init - Scylla API server listening on 127.0.0.1:10000 ...
11-21 11:31:24 ip-10-0-237-237 scylla[6896]:  [shard 0] init - initializing storage service
11-21 11:31:24 ip-10-0-237-237 scylla[6896]:  [shard 0] init - starting per-shard database core
11-21 11:31:24 ip-10-0-237-237 scylla[6896]:  [shard 0] init - creating data directories
11-21 11:31:24 ip-10-0-237-237 scylla[6896]:  [shard 0] init - creating commitlog directory
11-21 11:31:24 ip-10-0-237-237 scylla[6896]:  [shard 0] init - creating hints directories
11-21 11:31:24 ip-10-0-237-237 scylla[6896]:  [shard 0] init - verifying directories
11-21 11:31:24 ip-10-0-237-237 scylla[6896]:  [shard 0] storage_service - Shutting down communications due to I/O errors until operator intervention
11-21 11:31:24 ip-10-0-237-237 scylla[6896]:  [shard 0] storage_service - Commitlog error: std::system_error (error system:28, No space left on device)

### Coredump occurred

11-21 11:31:24 ip-10-0-237-237 scylla[6896]: scylla: /data/jenkins/workspace/scylla-3.2/build/scylla/seastar/src/core/file.cc:515: virtual seastar::append_challenged_posix_file_impl::~append_challenged_posix_file_impl(): Assertion `_closing_state == state::closed' failed.
11-21 11:31:24 ip-10-0-237-237 scylla[6896]: Aborting on shard 0.
11-21 11:31:24 ip-10-0-237-237 scylla[6896]: Backtrace:
11-21 11:31:24 ip-10-0-237-237 scylla[6896]: 0x0000000002aa6a92
11-21 11:31:24 ip-10-0-237-237 scylla[6896]: 0x0000000002a2143b
11-21 11:31:24 ip-10-0-237-237 scylla[6896]: 0x0000000002a21735
11-21 11:31:24 ip-10-0-237-237 scylla[6896]: 0x0000000002a217d0
11-21 11:31:24 ip-10-0-237-237 scylla[6896]: 0x00007f0fc045fe7f
11-21 11:31:24 ip-10-0-237-237 scylla[6896]: /opt/scylladb/libreloc/libc.so.6+0x0000000000037e74
11-21 11:31:24 ip-10-0-237-237 scylla[6896]: /opt/scylladb/libreloc/libc.so.6+0x0000000000022894
11-21 11:31:24 ip-10-0-237-237 scylla[6896]: /opt/scylladb/libreloc/libc.so.6+0x0000000000022768
11-21 11:31:24 ip-10-0-237-237 scylla[6896]: /opt/scylladb/libreloc/libc.so.6+0x0000000000030565
11-21 11:31:24 ip-10-0-237-237 scylla[6896]: 0x00000000029adcaf
11-21 11:31:24 ip-10-0-237-237 scylla[6896]: 0x0000000000a39df8
11-21 11:31:24 ip-10-0-237-237 scylla[6896]: 0x00000000017a1cdd
11-21 11:31:24 ip-10-0-237-237 scylla[6896]: 0x0000000002a1db71
11-21 11:31:24 ip-10-0-237-237 scylla[6896]: 0x0000000002a1dd7f
11-21 11:31:24 ip-10-0-237-237 scylla[6896]: 0x0000000002a8608d
11-21 11:31:24 ip-10-0-237-237 scylla[6896]: 0x00000000029cac2c
11-21 11:31:24 ip-10-0-237-237 scylla[6896]: 0x00000000029cb8fe
11-21 11:31:24 ip-10-0-237-237 scylla[6896]: 0x0000000000792781
11-21 11:31:24 ip-10-0-237-237 scylla[6896]: /opt/scylladb/libreloc/libc.so.6+0x0000000000023f32
11-21 11:31:24 ip-10-0-237-237 scylla[6896]: 0x00000000007e10dd

11-21 11:31:24 ip-10-0-237-237 scylla[6896]:  [shard 0] storage_service - Stop transport: starts
11-21 11:31:24 ip-10-0-237-237 scylla[6896]:  [shard 0] storage_service - Stop transport: shutdown rpc and cql server done
11-21 11:31:24 ip-10-0-237-237 scylla[6896]:  [shard 0] gossip - gossip is already stopped
11-21 11:31:24 ip-10-0-237-237 scylla[6896]:  [shard 0] storage_service - Stop transport: stop_gossiping done
11-21 11:31:24 ip-10-0-237-237 scylla[6896]:  [shard 0] storage_service - messaging_service stopped
11-21 11:31:24 ip-10-0-237-237 scylla[6896]:  [shard 0] storage_service - Stop transport: shutdown messaging_service done
11-21 11:31:24 ip-10-0-237-237 scylla[6896]:  [shard 0] storage_service - stream_manager stopped
11-21 11:31:24 ip-10-0-237-237 scylla[6896]:  [shard 0] storage_service - Stop transport: shutdown stream_manager done
11-21 11:31:24 ip-10-0-237-237 scylla[6896]:  [shard 0] storage_service - Stop transport: auth shutdown
11-21 11:31:24 ip-10-0-237-237 scylla[6896]:  [shard 0] storage_service - Stop transport: done
11-21 11:31:24 ip-10-0-237-237 systemd-coredump[6924]: Process 6896 (scylla) of user 996 dumped core.
```

### all Nemesis before issue occurred:

- 11-21 11:31:03,933 > sdcm.nemesis.ChaosMonkey: >>>>>>>>>>>>>Started random_disrupt_method nodetool_enospc
- 11-21 11:33:28,034 > sdcm.nemesis.ChaosMonkey: <<<<<<<<<<<<<Finished random_disrupt_method nodetool_enospc

### SCT YAML:
- https://github.com/scylladb/scylla-cluster-tests/blob/master/test-cases/longevity/longevity-10gb-3h.yaml

### The probability of this issue during the run (or multiple runs):
only occurred once

**Comment by amoskong** [comment] 2019-11-21 12:22
- Full Logs
    - https://storage.cloud.google.com/upload.scylladb.com/amos/scylla_issue_5325_long_3h.tar.gz?authuser=0
- Monitor Metrics:  None
- Live snapshot from Grafana
    - https://snapshot.raintank.io/dashboard/snapshot/OFyat59w08s2SDo952ZEu3bxDgWIfyLg
- Link to the monitor if still exist
    - http://34.249.132.108:3000/d/1kbYavxZk/scylla-per-server-metrics-nemesis-3-2?orgId=1&refresh=30s

**Comment by amoskong** [comment] 2019-11-21 12:41
Related issues:
- https://github.com/scylladb/scylla/issues/5215
- https://github.com/scylladb/scylla/issues/4877

**Comment by fruch** [comment] 2019-11-21 12:53
BTW the coredump probably failed to be saved, cause it doesn't have space for it

**Comment by bhalevy** [comment] 2019-11-21 13:27
Looks like a duplicate of #4877 
@espindola has a patch on the ML: `commitlog: make sure a file is closed`

**Comment by espindola** [comment] 2019-11-21 16:38
The patch was just added to next: f27d03b41f148b23c8bc8c246077d393793062cc

**Comment by amoskong** [comment] 2019-11-21 22:33
> BTW the coredump probably failed to be saved, cause it doesn't have space for it

@fruch you are right! I will create a trello ticket to trace this issue.

**Comment by slivne** [comment] 2019-12-02 11:42
duplicate of #4877

**Closed by slivne** 2019-12-02 11:42 UTC
Labels: bug, longevity
