### ISSUE TITLE
How to limit scyllaDB RAM/Memory usage?

### ISSUE THREAD

**Issue by kokizzu** [scylladb/scylla#2396] opened 2017-05-18 09:05 UTC
*Installation details*
Scylla version (or git commit hash): 1.7RC
Cluster size: 1
OS (RHEL/CentOS/Ubuntu/AWS AMI): Ubuntu 64-bit

*Hardware details (for performance issues)*          Delete if unneeded
Platform (physical/VM/cloud instance type/docker): physical (laptop)
Hardware: sockets=1 cores=4 hyperthreading=8 memory=32GB 
Disks: SSD 1

ScyllaDB memory usage are too high, it tooks 24GB alone, making all my other applications unstable (redis, postgresql, intellij, google chrome, etc), how to limit it's memory usage to 8/12/16 GB similar like in docker switch?
![image](https://cloud.githubusercontent.com/assets/1061610/26194707/7cb863dc-3be3-11e7-8773-d84d47db18a6.png)

**Comment by kokizzu** [comment] 2017-05-18 09:20
There's some files, but none of them set the max memory usage: `/etc/init|default/scylla-server` and `/etc/init/scylla-server.conf` also one in `/lib/systemd/system/scylla-server.conf`

```
sudo sed -i 's|/usr/bin/scylla $SCYLLA_ARGS|/usr/bin/scylla -m 8G $SCYLLA_ARGS|g' /lib/systemd/system/scylla-server.service
sudo systemctl daemon-reload
sudo systemctl restart scylla-server
```

**Comment by nyh** [comment] 2017-05-18 09:23
Hi @kokizzu, this is not a bug but a question, next time please ask it on the scylladb mailing list instead of here, and please close this issue (sadly I can't do it myself). But anyway, since you asked here, I'll answer here:

scylladb is designed to use all the memory you can give it and put it to good use, most notably to cache data. By default, it takes all the memory on your system leaving behind some small percentage for the system's kernel and background daemons to use; The assumption is that most users will not want to run additional servers on the same machine (doing that was very common in the previous decade, but became less popular with virtualization and growing workloads).

But nevertheless, if you want to give scylla less memory than it chose to use by default, it's easy - there is a "-m" command line parameter. For example, "-m8G" will give it 8 gigabytes. Easy.

Another thing to note is that by default Scylla will also use all your CPUs. If scylla's load is very low, it will sleep some of the time and let other applications to run, but if the load is not very low, Scylla will attempt to run all the time, on all cpus. If there are other servers wishing to run, this will cause context switches and bad latency. In that case, it may also make sense to give Scylla only some of the CPUs you have, and give the other server a few of the CPUs. This is done with the "-c" option, e.g., "-c6" to give Scylla only 6 of the 8 hyperthreads.

**Closed** 2017-05-18 09:24 UTC
