### ISSUE TITLE
Could not retrieve CDC streams with timestamp

### ISSUE THREAD

**Issue by asias** [scylladb/scylla#6009] opened 2020-03-12 03:15 UTC
I saw this with scylla master 0cb71827684480cd9b5466633cb4165d6012cd03

```
WARN  2020-03-12 08:49:08,953 [shard 0] cdc - Could not retrieve CDC streams with timestamp 2020/03/11 08:18:40: seastar::internal::backtraced<marshal_exception> (marshaling error: read_simple_exactly - size mism
atch (expected 8, got 17) Backtrace:   0x1a8b2c9
  0x590366
  0x5904a8
  0xb54c2f
  0xb342e3
  0xb3527f
  0xb34554
  0xb34d78
  0xb342a3
  0xd17c1b
  0xd18ff1
  0x1943690
  0x1950ad5
  0x1969fc3
  0x19113f9
  0x19117f8
  0x43df68
  /lib64/libc.so.6+0x271a2
  0x425b3d
). Will retry again.
```

**Comment by gleb-cloudius** [comment] 2020-03-12 05:07
Me too!

--
			Gleb.

**Comment by haaawk** [comment] 2020-03-12 06:47
Could you give more context, please? When did this happen? In tests? During some topology changes? If yes then what was the change?

**Comment by asias** [comment] 2020-03-12 06:52
It happened when I reboot a 3 node cluster I created yesterday. No topology changes. The cluster is probably created with commit 27b36beb4abd856d0b5ac4826b5ad7b82a798ec6, but I am not sure.

Data inserted with:

```
cassandra-stress write cl=ALL n=200200300 -schema 'replication(factor=3) compaction(strategy=LeveledCompactionStrategy)' -port jmx=6868 -mode cql3 native -rate threads=200 -col 'size=FIXED(1024) n=FIXED(1)' -    pop seq=1..200200300 -log interval=15
```

**Comment by haaawk** [comment] 2020-03-12 06:59
It is interesting. Are all your nodes using the same version of Scylla? It looks like a timestamp deserialization has failed because the input was longer than expected.

**Comment by asias** [comment] 2020-03-12 07:12
Yesterday: All 3 nodes run with 27b36be.
Today: All 3 nodes run with 0cb7182. CDC error was seen.

**Comment by gleb-cloudius** [comment] 2020-03-12 08:01
I see it with one node cluster.

--
			Gleb.

**Comment by gleb-cloudius** [comment] 2020-03-12 08:06
On Thu, Mar 12, 2020 at 10:01:04AM +0200, Gleb Natapov wrote:
> I see it with one node cluster.
> 
The cluster was "upgraded" though. Was first booted with an older
version.

--
			Gleb.

**Comment by kbr-** [comment] 2020-03-12 12:30
Yes, there was a backward incompatible change:
https://github.com/scylladb/scylla/commit/968177da049a455edd8b8b6856698c277635f3f1
I assume you had the experimental flag on?

czw., 12 mar 2020, 09:06 użytkownik Gleb Natapov <notifications@github.com>
napisał:

**Comment by kbr-** [comment] 2020-03-12 12:32
Related PR: https://github.com/scylladb/scylla/pull/5972


czw., 12 mar 2020, 13:29 użytkownik Kamil Braun <kamilgbraun@gmail.com>
napisał:

**Comment by kbr-** [comment] 2020-03-12 12:41
Anyway, if you don't want to start a new cluster, delete all sstables for
cdc_description and cdc_topology_description in the system_distributed
keyspace, then restart.

czw., 12 mar 2020, 13:32 użytkownik Kamil Braun <kamilgbraun@gmail.com>
napisał:

**Comment by kbr-** [comment] 2020-03-12 12:54
Also delete sstables for system.cdc_local on every node before restarting
or you will be flooded with warnings "cannot retrieve cdc generation" and
won't be able to use cdc.

czw., 12 mar 2020, 13:41 użytkownik Kamil Braun <kamilgbraun@gmail.com>
napisał:

**Comment by gleb-cloudius** [comment] 2020-03-12 13:24
After doing all that I cannot boot the node. It shuts down itself after
printing "cdc - Generation of CDC streams failed to create streams for
some (vnode, shard) pair. This can lead to worse performance."

--
			Gleb.

**Comment by gleb-cloudius** [comment] 2020-03-12 13:28
After I removed everything under /var/lib/scylla the node boots again
and prints the same message, so the shutdown was not related to the
message directly but definitely related to the procedure.

--
			Gleb.

**Comment by kbr-** [comment] 2020-03-13 12:17
> After I removed everything under /var/lib/scylla the node boots again
and prints the same message, so the shutdown was not related to the
message directly but definitely related to the procedure.

I reproduced the problem by compiling https://github.com/scylladb/scylla/commit/d1db1982113e331c9ca092cfa2454ec78b942f33, running scylla, then compiling https://github.com/scylladb/scylla/commit/968177da049a455edd8b8b6856698c277635f3f1, and running again.

Indeed deleting these sstables doesn't help because Scylla still tries to use the old schema to serialize the data. Other sstables have to be removed too like system.columns, but I'm not sure if it's possible to just remove a subset of these tables and get Scylla working again. It's easiest to just create a new cluster as you did by removing everything.

In any case, I think we can close this issue because the problem arises by upgrading through a backward-incompatible change. This was intentional - there was no release (and there won't be) which uses the old `system_distributed.cdc_{topology_}description` schema.

**Comment by haaawk** [comment] 2020-03-13 20:49
Closing as the behavior is expected

**Closed by haaawk** 2020-03-13 20:49 UTC
Labels: CDC, bug, high
