### ISSUE TITLE
std::_Nested_exception happened during Drop keyspace with MV/SI after shapshot created

### ISSUE THREAD

**Issue by aleksbykov** [scylladb/scylla#5686] opened 2020-01-31 04:19 UTC
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash):666.development-0.20200123.e1b22b6a4c5

Issue reproduced with dtest and on ami

Drop keyspace with base table and MV/SLI/SI after snapshot creation, cause an error in scylla db log
```
db-node-412e2791-2 scylla[5070]:  [shard 1] table - Failed writing schema file in snapshot in /var/lib/scylla/data/ks/cf_mv-5cbcf330436b11ea8650000000000003/snapshots/1580443038626-cf_mv with exception std::_Nested_exception<no_such_column_family> (Can't find a column family with UUID 49c79640-436b-11ea-8650-000000000003): std::out_of_range (_Map_base::at)
db-node-412e2791-2 scylla[5070]:  [shard 3] table - Failed writing schema file in snapshot in /var/lib/scylla/data/ks/cf_mv1-67a54ef0436b11ea8650000000000003/snapshots/1580443038626-cf_mv1 with exception std::_Nested_exception<no_such_column_family> (Can't find a column family with UUID 49c79640-436b-11ea-8650-000000000003): std::out_of_range (_Map_base::at)
```

Steps to reproduce:
1. Create keyspace, Create table, creat MV for this table
```
create keyspace ks with replication={'class':'SimpleStrategy', 'replication_factor': 1} ;
create table ks.cf (key int primary key, val text, val1 text);
create CREATE MATERIALIZED VIEW cf_mv AS SELECT * FROM ks.cf WHERE val IS NOT NULL PRIMARY KEY (val, key)

insert into ks.cf (key, val, val1) value (1, '1', '1');
insert into ks.cf (key, val, val1) value (1, '2', '2');
```

2. run nodetool flush ks
3. run nodetool snapshot ks
4. run cqlsh -e 'drop keyspace ks

Error appeared in log. 

same happened and for Secondary indexes (global and Local)

**Comment by slivne** [comment] 2020-02-04 21:22
@amnonh - you are handling something related to snapshot / drop keyspace - does this ring a bell ? is it a known issue (if so please link this to the other issue)

**Comment by nyh** [comment] 2020-02-05 06:29
@slivne yes, Amnon is handling this issue exactly, and already proposed a PR https://github.com/scylladb/scylla/pull/5713 - but now there's a discussion maybe the proper solution should be different. This PR doesn't refer to any issue (@amnonh, it should) so I don't know if there's already another open issue for it.

**Comment by amnonh** [comment] 2020-02-05 07:24
Same as #5614

**Comment by bhalevy** [comment] 2020-02-12 07:23
Closing as duplicate of #5614

**Closed by bhalevy** 2020-02-12 07:23 UTC
Labels: bug
