### ISSUE TITLE
auth_test failed: nodetool: Scylla API server HTTP GET to URL '/storage_service/natural_endpoints/system_auth' failed: std::_Nested_exception<no_such_column_family> (Can't find a column family users in keyspace system_auth): std::out_of_range ()

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#5880] opened 2020-02-23 10:57 UTC
Seen since scylla version 6c7aa1823826817b38268871a0633a818cd98495
(passing in 06c16108df13476be61ffef868b50a11a42a4a4d)

The following dtests consistently fail:
https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/395/testReport/auth_test/TestAuth/dropping_keyspace_system_auth_2_nodes_test/
https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/395/testReport/auth_test/TestAuth/kill_the_node_with_the_auth_info_test/
https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/395/testReport/auth_test/TestAuth/kill_all_nodes_with_the_auth_info_except_one_test/
https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/395/testReport/auth_test/TestAuth/kill_one_of_the_nodes_with_the_auth_info_test/
```
Error Message
Nodetool command '/jenkins/workspace/scylla-master/dtest-release/scylla/.ccm/scylla-repository/6c7aa1823826817b38268871a0633a818cd98495/scylla-tools-java/bin/nodetool -h 127.0.81.1 -p 7181 getendpoints system_auth users cassandra' failed; exit status: 1; stdout: nodetool: Scylla API server HTTP GET to URL '/storage_service/natural_endpoints/system_auth' failed: std::_Nested_exception<no_such_column_family> (Can't find a column family users in keyspace system_auth): std::out_of_range ()
See 'nodetool help' or 'nodetool help <command>'.
Stacktrace
Traceback (most recent call last):
  File "/usr/lib64/python3.7/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/usr/lib64/python3.7/unittest/case.py", line 645, in run
    testMethod()
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/auth_test.py", line 1241, in dropping_keyspace_system_auth_2_nodes_test
    out, err = node1.nodetool("getendpoints system_auth users cassandra")
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-ccm/ccmlib/node.py", line 737, in nodetool
    raise NodetoolError(" ".join(args), exit_status, stdout, stderr)
ccmlib.node.NodetoolError: Nodetool command '/jenkins/workspace/scylla-master/dtest-release/scylla/.ccm/scylla-repository/6c7aa1823826817b38268871a0633a818cd98495/scylla-tools-java/bin/nodetool -h 127.0.81.1 -p 7181 getendpoints system_auth users cassandra' failed; exit status: 1; stdout: nodetool: Scylla API server HTTP GET to URL '/storage_service/natural_endpoints/system_auth' failed: std::_Nested_exception<no_such_column_family> (Can't find a column family users in keyspace system_auth): std::out_of_range ()
See 'nodetool help' or 'nodetool help <command>'.
```

**Comment by bhalevy** [comment] 2020-02-23 10:58
@haaawk it looks like your changes merged in 6c7aa1823826817b38268871a0633a818cd98495 caused this regression.  Can you please look into it?

**Comment by bhalevy** [comment] 2020-02-23 10:59
To reproduce, try:
```
NOSE_PROCESSES=1 SCYLLA_EXT_OPTS="--smp 2 --memory 1024M" CASSANDRA_DIR=<path>/scylla/build/dev nosetests -s -v --process-timeout=1800 auth_test:TestAuth.dropping_keyspace_system_auth_2_nodes_test
```

**Comment by haaawk** [comment] 2020-02-25 11:38
@bhalevy I reverted https://github.com/scylladb/scylla/commit/6c7aa1823826817b38268871a0633a818cd98495 and the test keeps failing. I think there's little chance my change is related because it does not change any behavior. Everything still uses global partitioner.

**Comment by eliransin** [comment] 2020-02-27 07:24
Found the bug. We indeed don't have a **users** table anymore - it is called **roles** :)
Will open a dtest issue and fix it. I will close this once I am referencing it from dtest.

**Comment by eliransin** [comment] 2020-02-27 07:41
closing since it is not a bug in Scylla .

**Comment by eliransin** [comment] 2020-03-03 08:31
The change that caused the test to fail is: 499e330ff9eff484199e33236b94f9a79a4c0367
In this change the partitioner is no longer global, so when trying to get the specific table partitioner we find out it doesn't exist. Before this change we returned the right endpoint but this is because the individual table didn't matter for determining the endpoint so scylla didn't fail the query even though the table didn't exist.

**Closed by eliransin** 2020-03-03 08:31 UTC
Labels: bug, dtest
