### ISSUE TITLE
When local address is used for replace-address and as a seeder scylla fails to connect to the seeder 

### ISSUE THREAD

**Issue by vladzcloudius** [scylladb/scylla#1183] opened 2016-04-13 10:51 UTC
## Installation details
Scylla version (or git commit hash): 1.0.1
Cluster size: 1 
OS (RHEL/CentOS/Ubuntu/AWS AMI): CentOS Linux release 7.2.1511 (Core)

## Hardware details (for performance issues)
Platform (physical/VM/cloud instance type/docker): physical (n0.sahara.cloudius-systems.com)
Hardware: sockets=2 cores=18 hyperthreading=2 per core memory=128GB

## Description
For some reason `/etc/sysconfig/scylla-server` had the following line:
```
# scylla arguments (for posix mode)
SCYLLA_ARGS="--log-to-syslog 1 --log-to-stdout 0 --default-log-level info --collectd-address=127.0.0.1:25826 --collectd=1 --collectd-poll-period 60000 --network-stack posix --num-io-queues 32 --max-io-requests 128 --replace-address 10.0.4.131"
```
Used configuration file: [scylla.yaml](https://github.com/scylladb/scylla/files/216869/scylla.yaml.txt)

10.0.4.131 is an IP address of a local network interface:
```
# ifconfig
eno1: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 10.0.0.131  netmask 255.255.255.0  broadcast 10.0.0.255
        inet6 fe80::1618:77ff:fe43:1f1a  prefixlen 64  scopeid 0x20<link>
        ether 14:18:77:43:1f:1a  txqueuelen 1000  (Ethernet)
        RX packets 332453  bytes 40641686 (38.7 MiB)
        RX errors 0  dropped 54  overruns 0  frame 0
        TX packets 40512  bytes 12933849 (12.3 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
        device interrupt 75

enp4s0f0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 10.0.4.131  netmask 255.255.255.0  broadcast 10.0.4.255
        inet6 fe80::a236:9fff:fe56:265c  prefixlen 64  scopeid 0x20<link>
        ether a0:36:9f:56:26:5c  txqueuelen 1000  (Ethernet)
        RX packets 315377  bytes 805049789 (767.7 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 286832  bytes 59621453 (56.8 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 0  (Local Loopback)
        RX packets 633579  bytes 329995248 (314.7 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 633579  bytes 329995248 (314.7 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```

# Steps to reproduce
1. `rm -rf /var/var/lib/scylla/data/* /lib/scylla/commitlog/*`
2. systemctl start scylla-server
3. systemctl start scylla-jmx
4. nodetool status

The output is:
```
# nodetool  status
nodetool: Scylla API server HTTP GET to URL '/storage_service/ownership/' failed: runtime error: No nodes present in the cluster. Has this node finished starting up?
See 'nodetool help' or 'nodetool help <command>'.
```
In the log we see:
```
Apr 13 06:30:52 n0 scylla[19681]: [shard 0] storage_service - Loading persisted ring state
Apr 13 06:30:52 n0 scylla[19681]: [shard 0] storage_service - Gathering node replacement information for 10.0.4.131
Apr 13 06:30:53 n0 scylla[19681]: [shard 0] gossip - Connect seeds again ... (1 seconds passed)
Apr 13 06:30:54 n0 scylla[19681]: [shard 0] gossip - Connect seeds again ... (2 seconds passed)
Apr 13 06:30:55 n0 scylla[19681]: [shard 0] gossip - Connect seeds again ... (3 seconds passed)
Apr 13 06:30:56 n0 scylla[19681]: [shard 0] gossip - Connect seeds again ... (4 seconds passed)
Apr 13 06:30:57 n0 scylla[19681]: [shard 0] gossip - Connect seeds again ... (5 seconds passed)
Apr 13 06:30:58 n0 scylla[19681]: [shard 0] gossip - Connect seeds again ... (6 seconds passed)
Apr 13 06:30:59 n0 scylla[19681]: [shard 0] gossip - Connect seeds again ... (7 seconds passed)
Apr 13 06:31:00 n0 scylla[19681]: [shard 0] gossip - Connect seeds again ... (8 seconds passed)
Apr 13 06:31:01 n0 scylla[19681]: [shard 0] gossip - Connect seeds again ... (9 seconds passed)
Apr 13 06:31:02 n0 scylla[19681]: [shard 0] gossip - Connect seeds again ... (10 seconds passed)
Apr 13 06:31:03 n0 scylla[19681]: [shard 0] gossip - Connect seeds again ... (11 seconds passed)
Apr 13 06:31:04 n0 scylla[19681]: [shard 0] gossip - Connect seeds again ... (12 seconds passed)
Apr 13 06:31:05 n0 scylla[19681]: [shard 0] gossip - Connect seeds again ... (13 seconds passed)
Apr 13 06:31:06 n0 scylla[19681]: [shard 0] gossip - Connect seeds again ... (14 seconds passed)
Apr 13 06:31:07 n0 scylla[19681]: [shard 0] gossip - Connect seeds again ... (15 seconds passed)
Apr 13 06:31:08 n0 scylla[19681]: [shard 0] gossip - Connect seeds again ... (16 seconds passed)
Apr 13 06:31:09 n0 scylla[19681]: [shard 0] gossip - Connect seeds again ... (17 seconds passed)
Apr 13 06:31:10 n0 scylla[19681]: [shard 0] gossip - Connect seeds again ... (18 seconds passed)
Apr 13 06:31:11 n0 scylla[19681]: [shard 0] gossip - Connect seeds again ... (19 seconds passed)
Apr 13 06:31:12 n0 scylla[19681]: [shard 0] gossip - Connect seeds again ... (20 seconds passed)
Apr 13 06:31:13 n0 scylla[19681]: [shard 0] gossip - Connect seeds again ... (21 seconds passed)
Apr 13 06:31:14 n0 scylla[19681]: [shard 0] gossip - Connect seeds again ... (22 seconds passed)
Apr 13 06:31:15 n0 scylla[19681]: [shard 0] gossip - Connect seeds again ... (23 seconds passed)
Apr 13 06:31:16 n0 scylla[19681]: [shard 0] gossip - Connect seeds again ... (24 seconds passed)
...
```

**Comment by vladzcloudius** [comment] 2016-04-13 11:01
This configuration makes little sense since the Node that was given a `replace-address` parameter is going to ask a seeder about the `host ID` of the original Node and if it itself is the only seeder then it's not clear how this situation is supposed to be resolved.

I think this configuration should be treated as an invalid configuration and `scylla` should gracefully fail in this case with an appropriate error message.

**Comment by tzach** [comment] 2016-04-18 11:12
@vladzcloudius which two address did you switch between?
Can you please explain the use case?

**Comment by asias** [comment] 2016-04-20 08:36
@slivne please assign it to me.

**Comment by vladzcloudius** [comment] 2016-04-20 08:44
@tzach - The use case is a "strange configuration" by a user that is neither prevented nor forbidden right. We have to make our mind up and fix the code correspondingly.

**Comment by asias** [comment] 2016-04-20 08:55
When a node starts, there must be at least one seed node is up. In this case, there is no running seed node. This is a configuration error. 

We can add check in storage_service::prepare_replacement_info to detect this config error and report to user.

**Comment by vladzcloudius** [comment] 2016-04-20 08:57
On 04/20/2016 11:55 AM, Asias He wrote:
>
> When a node starts, there must be at least one seed node is up. In 
> this case, there is no running seed node. This is a configuration error.
>
> We can add check in storage_service::prepare_replacement_info to 
> detect this config error and report to user.
>

@asias +1

**Comment by asias** [comment] 2016-04-20 09:23
The following patch should catch the config error.

```
diff --git a/service/storage_service.cc b/service/storage_service.cc
index 160e33a..c41190b 100644
--- a/service/storage_service.cc
+++ b/service/storage_service.cc
@@ -1321,6 +1321,10 @@ future<std::unordered_set<token>> storage_service::prepare_replacement_info() {

     // if (!MessagingService.instance().isListening())
     //     MessagingService.instance().listen(FBUtilities.getLocalAddress());
+    auto seeds = gms::get_local_gossiper().get_seeds();
+    if (seeds.size() == 1 && seeds.count(replace_address)) {
+        throw std::runtime_error(sprint("Cannot replace_address %s because no seed node is up", replace_address));
+    }

     // make magic happen
     return gms::get_local_gossiper().do_shadow_round().then([this, replace_address] {
```

**Comment by vladzcloudius** [comment] 2016-04-20 10:49
On 04/20/2016 12:23 PM, Asias He wrote:
>
> The following patch should catch the config error.
>
> |diff --git a/service/storage_service.cc b/service/storage_service.cc 
> index 160e33a..c41190b 100644 --- a/service/storage_service.cc +++ 
> b/service/storage_service.cc @@ -1321,6 +1321,10 @@ 
> future<std::unordered_set<token>> 
> storage_service::prepare_replacement_info() { // if 
> (!MessagingService.instance().isListening()) // 
> MessagingService.instance().listen(FBUtilities.getLocalAddress()); + 
> auto seeds = gms::get_local_gossiper().get_seeds(); + if (seeds.size() 
> == 1 && seeds.count(replace_address)) { + throw 
> std::runtime_error(sprint("Cannot replace_address %s because no seed 
> node is up", replace_address)); + } // make magic happen return 
> gms::get_local_gossiper().do_shadow_round().then([this, 
> replace_address] { |
>
> —
>

@asias Looks good

**Comment by tzach** [comment] 2016-05-04 12:39
@asias did you sent a patch?

**Comment by asias** [comment] 2016-05-04 13:14
Not yet. The issue is of very low priority.

On Wed, May 4, 2016 at 8:39 PM, Tzach Livyatan <notifications@github.com>
wrote:

> @asias <https://github.com/asias> did you sent a patch?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/scylladb/scylla/issues/1183#issuecomment-216850138>
>



-- 
Asias

**Closed** 2016-05-25 11:42 UTC
