### ISSUE TITLE
scylla install on OEL: fail to install depended python-urllib3

### ISSUE THREAD

**Issue by amoskong** [scylladb/scylla#2850] opened 2017-09-28 10:09 UTC
*Installation details*
Scylla version (or git commit hash): 2.0.rc5-0.20170927.43d785a.el7.centos
Cluster size: 1
OS (RHEL/CentOS/Ubuntu/AWS AMI): OEL7.4

*Description*
Try to install scylla by our [unstable repo](http://downloads.scylladb.com.s3.amazonaws.com/rpm/unstable/centos/branch-2.0/28/scylla-oel.repo), the scylla packages were actually installed, but one depended package (python-urllib3) didn't successfully installed. Sure, it's used by scylla code.

It should not a scylla issue, but we need to solve it.

Full log: [urllib3.err.txt](https://github.com/scylladb/scylla/files/1340420/urllib3.err.txt)

```
07:58:34,086 process | Running '/bin/yum -y install scylla'
...
07:58:54,504 process | [stdout]   Installing : python-six-1.9.0-2.el7.noarch                              17/33 
07:58:54,504 process | [stdout]   Installing : python-urllib3-1.10.2-3.el7.noarch                         18/33 
07:58:54,504 process | [stdout] error: unpacking of archive failed on file /usr/lib/python2.7/site-packages/urllib3/packages/ssl_match_hostname: cpio: rename
07:58:54,505 process | [stderr] Error unpacking rpm package python-urllib3-1.10.2-3.el7.noarch
07:58:54,553 process | [stdout]   Installing : python-requests-2.6.0-1.el7_1.noarch                       19/33 
07:58:54,553 process | [stdout] error: python-urllib3-1.10.2-3.el7.noarch: install failed
...
07:58:58,057 process | [stdout] Failed:
07:58:58,057 process | [stdout]   python-urllib3.noarch 0:1.10.2-3.el7                                          
07:58:58,057 process | [stdout]
07:58:58,057 process | [stdout] Complete!
[root@localhost ~]# echo $?
1
```

@amnonh @syuu1228

**Comment by amoskong** [comment] 2017-09-28 10:14
1. Jenkins job log: [link](http://jenkins.cloudius-systems.com:8080/job/scylla-2.0-oel7.4-rpm-test/label=muninn/5/artifact/latest/job.log)

2. I can still reproduce this issue with clean vm.

```
[root@localhost ~]# yum install python-urllib3
...
Running transaction  
  Installing : python-six-1.9.0-2.el7.noarch                                                                               1/2
  Installing : python-urllib3-1.10.2-3.el7.noarch                                                                          2/2
Error unpacking rpm package python-urllib3-1.10.2-3.el7.noarch
error: unpacking of archive failed on file /usr/lib/python2.7/site-packages/urllib3/packages/ssl_match_hostname: cpio: rename
  Verifying  : python-six-1.9.0-2.el7.noarch                                                                               1/2
  Verifying  : python-urllib3-1.10.2-3.el7.noarch                                                                          2/2

Dependency Installed:
  python-six.noarch 0:1.9.0-2.el7

Failed:
  python-urllib3.noarch 0:1.10.2-3.el7

Complete!

[root@localhost ~]# echo $?
1
```

**Comment by amoskong** [comment] 2017-09-28 11:48
The problem is similar with https://github.com/requests/requests/issues/2430
In my test, the python-urllib3 is conflict with the package is already installed via pip.

```
[root@localhost ~]# pip list|grep urllib3
urllib3 (1.22)
[root@localhost ~]# sudo pip uninstall urllib3
....
Proceed (y/n)? y
  Successfully uninstalled urllib3-1.22

Then I can successfully install `python-urllib3` package by yum.
```

**Comment by amoskong** [comment] 2017-11-09 18:18
@amnonh So we will just leave the problem to user? it's truly not a scylla-housekeeping issue.

If so let's close this issue

@slivne

**Comment by amoskong** [comment] 2017-11-15 14:19
@syuu1228 In my test env (OEL), the urllib3 was installed by default (at least it's not installed by me manually).  I can uninstall it by pip, I guess it's installed by pip, right?

**Comment by slivne** [comment] 2017-11-26 11:30
@amoskong / @syuu1228 any update

**Comment by amoskong** [comment] 2017-11-26 15:27
No update in my side. @syuu1228 do you need more test or info from me?

**Comment by devendor** [comment] 2018-06-13 12:57
This seems to be some sort of cpio unpack error due to the package including a symbolic link to a directory and/or how cpio handles directory symlinks.  The workaround below seems to accomplish the packagers intention.

rpm -ivv --excludepath=/usr/lib/python2.7/site-packages/urllib3/packages/ssl_match_hostname python-urllib3-1.10.2-5.el7.noarch.rpm

then
cd /usr/lib/python2.7/site-packages/urllib3/packages/
ln -s ../../backports/ssl_match_hostname 

An alternate package might switch to creating the ssl_match_hostname directory and linking to the files directly since cpio / rpm seems to work past that without issue.

**Comment by syuu1228** [comment] 2018-06-13 14:50
I still guessing this is not our packaging problem since it’s not conflicted with scylla\* package, but I try to reproduce it now.

**Comment by syuu1228** [comment] 2018-06-13 20:08
I just tried to reproduce the problem on OEL that running on AWS EC2 (ami-0c9c8d77, able to find on AWS marketplace), I didn't see any error, install finished just finely.
Here is log: https://gist.github.com/syuu1228/3f70ad82c562631c1518b1babaffd866

I still thinking it's environment dependent problem, not all OEL has the issue.
And in fact scylla-2.0-oel7.4-rpm-test is succeed now.

**Comment by avikivity** [comment] 2018-06-14 14:56
Since it doesn't reproduce for two people, closing. Please re-open if the problem still happens.

**Closed by avikivity** 2018-06-14 14:56 UTC
