### ISSUE TITLE
Materialized view rows not being written, seems "stuck"

### ISSUE THREAD

**Issue by veramine** [scylladb/scylla#3116] opened 2018-01-04 00:20 UTC
Installation details
Scylla version 2.0.2
Cluster size: 1
OS: AWS AMI ami-9509d3ed
Hardware: i3.large

Repro steps:

- Boot AWS VM
- Edit scylla.conf, uncomment experimental: true
- cqlsh -f schema.txt 
- Restart either the entire VM or just the databsae (sudo systemctl restart scylla-server)
- Insert row in base table programatically (not with cqlsh)

Expected result: Row appears in MV
Actual result: No row in MV

Dropping the MV's, recreating them, and then updating or inserting the base table row seems to temporarily resolve the issue.  However, the database eventually gets back into this same state again.  In one of our clusters, it ran fine for weeks.  We were spinning up several others this week and consistently hit the issue every time at installation time.  It seems worse right after a server reboot or scylla restart.  At initial startup with an initial schema it seems to almost always get into this state.  But if you cannot reproduce it please let us know.  We also have a VMWare snapshot with database in this state.  

Sometimes we see this kind of error message in the journal log indicating that Scylla "Can't find a column family with UUID...." around the same time as when we hit the issue.  I'm not sure if this is related or not:

Jan 03 21:59:28 ip-172-31-3-13 scylla[12086]:  [shard 0] database - Skipping: veraminetest. Exception occurred when loading system table views: Can't find a column family with UUID 0efc8230-f0d1-11e7-af31-000000000001

We cannot hit this issue when inserting rows with cqlsh from the command line.  We have only been able to hit it when inserting programatically.  We typically use the gocql library to interact with the database.  I've attached a simple repro.go file that you can compile to perform the initial insert.  I've also uploaded a linux binary at to upload.scylladb.com/29B77DFA-5F2C-4B92-A503-22639025B748/repro.  

[schema.txt](https://github.com/scylladb/scylla/files/1602094/schema.txt)

[repro.txt](https://github.com/scylladb/scylla/files/1602096/repro.txt)

**Comment by glommer** [comment] 2018-01-04 00:22
@duarten seems this isn't really fixed

**Comment by duarten** [comment] 2018-01-04 16:01
Maybe the updates are arriving while the schema is still being loaded, and the base table is not yet linked with its materialized views.

**Comment by veramine** [comment] 2018-01-04 16:30
Yes that might help explain the high rate of this condition after the initial scheme load.  Can you think of any way a materialized view could get “unlinked” after it has been working for days or weeks at a time?  

One other piece of information - it is usually EVERY materialized view that stops being written to.  (We use a bunch of them..) Are there any materialized view “kill switch” conditions  that we might be inadvertently triggering?  For example, one of the base tables with several MVs gets a lot of updates and those updates come from several different daemons potentially simultaneously.  I saw a patch set yesterday that made me think about that as a potential issue.  If there are cases where MV writes are turned off or unlinked, is there any way to trigger a schema reload operation to re-link and re-sync the base table and view relationships?

Thanks a lot!

**Comment by duarten** [comment] 2018-01-04 16:55
They will be "unlinked" on scylla restart, while we don't load both base and view tables.

There's no killswitch. The only thing that can be done by the user is to except delay writes for a bit after a restart (if this is indeed the problem).

**Comment by nyh** [comment] 2018-01-04 16:55
@veramine this may be is a silly question, but did you reboot your servers when the problem happened? 
@duarten I think there may be two issues here:
1. It seems we are loading the "views" system table and while doing so, some of the view tables it tries to find do not exist. Do we have any idea how this could happen? Maybe some problem in schema distribution, or its order? So it seems some of the nodes are not aware of the view tables they are supposed to be holding.
2. The base table is failing to write the view update to the view replica, but we don't have a local batch log so the update get lost - and apparently this is not even logged. We should at least log it, I think? Of course a batch log - or a repair feature - is the better long-term solution.

**Comment by duarten** [comment] 2018-01-04 16:59
@nyh We should find all the views, it might just take a while to link all of them to the base tables. As for logging, not sure if that can do us much good; we should look into leveraging the hinted handoff stuff.

**Comment by nyh** [comment] 2018-01-04 17:04
@duarten if I understood @veramine correctly, his problem wasn't temporary for a few seconds during the boot - rather Scylla got to a "state" where view updates were failing - perhaps because the view replicas didn't know about the view tables they were supposed to have. Maybe we have a bug in that area.
On the other hand, I don't understand how "programmatic" vs "cql" makes a difference here. @duarten maybe you can look at @veramine's reproducing information he attached above and see if you can reproduce it too.

**Comment by duarten** [comment] 2018-01-04 17:07
The only difference between "programmatic" vs "cql" is that one if much faster than the other, hence my suspicion of it happening during boot. If it enters such a state after boot, then it can only be that the nodes are partitioned. I don't have cycles to look extensively into this now.

**Comment by veramine** [comment] 2018-01-04 17:14
Sorry for the confusion, and thanks for looking into this.  

The server reboot and "programmatic" vs cqlsh is related to triggering the state.  Once in the state, no MV writes ever happen again ever.  So it's not just a temporary state, it is a permanent one.  And once in the state, neither programmatic nor cqlsh writes to the base table are propagated to the views.  

If it would be helpful, I would be happy to start up a small AWS VM and get it into this state and give you ssh credentials so you could see it in action..  (Glauber, if you are reading this, no you cannot use the VM for bitcoin mining..)

**Comment by duarten** [comment] 2018-01-04 19:15
I see, then it's definitely some bug, probably related to loading the schema tables. Will investigate asap.

**Comment by veramine** [comment] 2018-01-04 19:21
Great, thanks Duarte.  I was just doing some more testing this morning and had an easier time reproducing the issue after a VM restart (not just scylla-server service restart).

**Comment by veramine** [comment] 2018-01-04 19:48
On this particular instance, that column family UUID corresponds to the base_table_id for the very first row in the system_schema.views table:

```
cqlsh:veraminetest> select * from system_schema.views where keyspace_name = 'veraminetest' limit 1;

 keyspace_name | view_name              | base_table_id                        | base_table_name | bloom_filter_fp_chance | caching                                      | comment | compaction                                | compression                                                               | crc_check_chance | dclocal_read_repair_chance | default_time_to_live | extensions | gc_grace_seconds | id                                   | include_all_columns | max_index_interval | memtable_flush_period_in_ms | min_index_interval | read_repair_chance | speculative_retry | where_clause
---------------+------------------------+--------------------------------------+-----------------+------------------------+----------------------------------------------+---------+-------------------------------------------+---------------------------------------------------------------------------+------------------+----------------------------+----------------------+------------+------------------+--------------------------------------+---------------------+--------------------+-----------------------------+--------------------+--------------------+-------------------+-------------------------------------------------------------------------------------------------------
  veraminetest | action_status_actionex | ea98bb90-f182-11e7-853e-000000000001 |   action_status |                   0.01 | {'keys': 'ALL', 'rows_per_partition': 'ALL'} |         | {'class': 'SizeTieredCompactionStrategy'} | {'sstable_compression': 'org.apache.cassandra.io.compress.LZ4Compressor'} |                1 |                        0.1 |                    0 |           {} |           864000 | 253ffdd0-f183-11e7-bd46-000000000001 |                True |               2048 |                           0 |                128 |                  0 |    99.0PERCENTILE | customerguid IS NOT null AND systemguid IS NOT null AND actionid IS NOT null AND actionex IS NOT null

cqlsh:veraminetest> select * from system_schema.tables where keyspace_name = 'veraminetest' and table_name = 'action_status';

 keyspace_name | table_name    | bloom_filter_fp_chance | caching                                      | comment | compaction                                | compression                                                               | crc_check_chance | dclocal_read_repair_chance | default_time_to_live | extensions | flags        | gc_grace_seconds | id                                   | max_index_interval | memtable_flush_period_in_ms | min_index_interval | read_repair_chance | speculative_retry
---------------+---------------+------------------------+----------------------------------------------+---------+-------------------------------------------+---------------------------------------------------------------------------+------------------+----------------------------+----------------------+------------+--------------+------------------+--------------------------------------+--------------------+-----------------------------+--------------------+--------------------+-------------------
  veraminetest | action_status |                   0.01 | {'keys': 'ALL', 'rows_per_partition': 'ALL'} |         | {'class': 'SizeTieredCompactionStrategy'} | {'sstable_compression': 'org.apache.cassandra.io.compress.LZ4Compressor'} |                1 |                        0.1 |                    0 |           {} | {'compound'} |           864000 | ea98bb90-f182-11e7-853e-000000000001 |               2048 |                           0 |                128 |                  0 |    99.0PERCENTILE

```

**Comment by duarten** [comment] 2018-03-24 01:05
I think this was fixed by 3df6777b9b8e36013fe2599cd93fd44d3a47a494. I can't repro with master.

@veramine I've noticed you moved to 2.1; have you encountered this issue since?

**Comment by veramine** [comment] 2018-03-26 21:35
We have not encountered this issue since moving to 2.1.

**Comment by duarten** [comment] 2018-03-26 22:14
Thanks! Closing.

**Closed by duarten** 2018-03-26 22:14 UTC
Labels: bug, materialized-views
