### ISSUE TITLE
possible write latency degradation - test_latency_write

### ISSUE THREAD

**Issue by roydahan** [scylladb/scylla#6377] opened 2020-05-05 19:59 UTC
*Installation details*
Scylla version (or git commit hash): See below
Cluster size: 3
OS (RHEL/CentOS/Ubuntu/AWS AMI): AWS AMI

During test_latency_write (100% writes on pre-populated 1TB dataset) we started seeing some spikes of p99th latency.
(Prior to this suspected degradation, p99th latency didn't spike above 5 ms).

<img width="796" alt="Screen Shot 2020-05-05 at 22 41 21" src="https://user-images.githubusercontent.com/20959584/81108827-dd6fb600-8f21-11ea-9507-22e77c840519.png">

vs

<img width="726" alt="Screen Shot 2020-05-05 at 22 42 27" src="https://user-images.githubusercontent.com/20959584/81108858-e82a4b00-8f21-11ea-8107-391ae17307a8.png">

Here are some Grafana screenshots from these dates:
Still good:
16.2 : https://snapshot.raintank.io/dashboard/snapshot/BwGlWaiolTOodQkNNGSTfzahPWnAsclY?orgId=2
23.2: https://snapshot.raintank.io/dashboard/snapshot/20MaVkNEPofKSNSoMonT4vNNevWhUbNl?orgId=2
16.3: https://snapshot.raintank.io/dashboard/snapshot/kzgO0OlvjxIjiz17WiorzFtn5bj7cqrD?orgId=2
20.3: https://snapshot.raintank.io/dashboard/snapshot/s0PZH8Lyzj7QLb1J1gUTvWbn9mueDkia?orgId=2

"Spikey" behaviour started:
3.4: https://snapshot.raintank.io/dashboard/snapshot/KvgpwcjDcHilREVDLsqxO3Hr3jWBWONf?orgId=2&from=1585889618119&to=1585891412217
10.4: https://snapshot.raintank.io/dashboard/snapshot/EUDXOFX0fqv8VrdNABZSEqTF3OzvXs5T?orgId=2
17.4: https://snapshot.raintank.io/dashboard/snapshot/qyJ0gp46RnfelS3tVT4avADonDQny7mK?orgId=2
24.4: https://snapshot.raintank.io/dashboard/snapshot/jqmyE0SGmmXAirD1bRCDxJn4869s93cr?orgId=2
1.5: https://snapshot.raintank.io/dashboard/snapshot/uyD6F3oMjWiFjJVEoP7100crfBYvW6x5?orgId=2

I narrowed down the dates as much as I can with the available AMIs:
Last known good version: 666.development. 20200325. 9fee712d62 (ami-0ff0d10d392b499a5)
First AMI I could spot the issue: 666.development. 20200401. dee0b68347 (ami-0a5a2f8bfe904aed3)

**These tests have stall detector set to 4ms**
In the versions we have the spikes, I can see reactor stalls of 5 to 12 ms.
The good versions don't have reactor stalls.

This is the the reactor stall decoded from 1.5 version:
```
[centos@ip-172-16-99-73 ~]$ addr2line -Cpfie /usr/lib/debug/.build-id/20/f7dd44e77bc28b793a0e4b720a4f88103aba3f.debug


?? ??:0
?? ??:0
0x0000000002e39712
0x0000000002de1584
0x0000000002de1ab2
0x0000000002de1de7
0x00007fb5a02ebb1f
0x0000000000f10cad
0x0000000000fb0ea9
0x0000000000fb1128
0x0000000000fb55a7
0x0000000002d9a148
0x0000000002d9ab10
0x0000000002d9e5af
0x00000000011f222d
0x0000000001153e2f
0x000000000128eb4e
0x000000000132a640
0x0000000001348609
0x0000000001348986
0x000000000309d47c

void seastar::backtrace<seastar::backtrace_buffer::append_backtrace()::{lambda(seastar::frame)#1}>(seastar::backtrace_buffer::append_backtrace()::{lambda(seastar::frame)#1}&&) at /usr/include/fmt/format.h:1158
seastar::backtrace_buffer::append_backtrace() at /usr/include/fmt/format.h:1158
 (inlined by) print_with_backtrace at ./build/release/seastar/./seastar/src/core/reactor.cc:762
seastar::internal::cpu_stall_detector::generate_trace() at /usr/include/fmt/format.h:1158
seastar::internal::cpu_stall_detector::maybe_report() at /usr/include/fmt/format.h:1158
 (inlined by) seastar::internal::cpu_stall_detector::on_signal() at ./build/release/seastar/./seastar/src/core/reactor.cc:1071
 (inlined by) seastar::reactor::block_notifier(int) at ./build/release/seastar/./seastar/src/core/reactor.cc:1194
?? ??:0
boost::intrusive::default_rbtree_node_traits_impl<void*>::get_right(boost::intrusive::rbtree_node<void*>* const&) at /usr/include/fmt/format.h:1158
 (inlined by) boost::intrusive::bstree_algorithms<boost::intrusive::rbtree_node_traits<void*, false> >::swap_tree(boost::intrusive::rbtree_node<void*>*, boost::intrusive::rbtree_node<void*>*) at /usr/include/boost/intrusive/bstree_algorithms.hpp:703
 (inlined by) boost::intrusive::bstree_impl<boost::intrusive::mhtraits<range_tombstone, boost::intrusive::set_member_hook<boost::intrusive::link_mode<(boost::intrusive::link_mode_type)2>, void, void, void>, &range_tombstone::_link>, void, range_tombstone::compare, unsigned long, false, (boost::intrusive::algo_types)5, void>::swap(boost::intrusive::bstree_impl<boost::intrusive::mhtraits<range_tombstone, boost::intrusive::set_member_hook<boost::intrusive::link_mode<(boost::intrusive::link_mode_type)2>, void, void, void>, &range_tombstone::_link>, void, range_tombstone::compare, unsigned long, false, (boost::intrusive::algo_types)5, void>&) at /usr/include/boost/intrusive/bstree.hpp:980
 (inlined by) boost::intrusive::bstree_impl<boost::intrusive::mhtraits<range_tombstone, boost::intrusive::set_member_hook<boost::intrusive::link_mode<(boost::intrusive::link_mode_type)2>, void, void, void>, &range_tombstone::_link>, void, range_tombstone::compare, unsigned long, false, (boost::intrusive::algo_types)5, void>::bstree_impl(boost::intrusive::bstree_impl<boost::intrusive::mhtraits<range_tombstone, boost::intrusive::set_member_hook<boost::intrusive::link_mode<(boost::intrusive::link_mode_type)2>, void, void, void>, &range_tombstone::_link>, void, range_tombstone::compare, unsigned long, false, (boost::intrusive::algo_types)5, void>&&) at /usr/include/boost/intrusive/bstree.hpp:740
 (inlined by) boost::intrusive::set_impl<boost::intrusive::mhtraits<range_tombstone, boost::intrusive::set_member_hook<boost::intrusive::link_mode<(boost::intrusive::link_mode_type)2>, void, void, void>, &range_tombstone::_link>, void, range_tombstone::compare, unsigned long, false, void>::set_impl(boost::intrusive::set_impl<boost::intrusive::mhtraits<range_tombstone, boost::intrusive::set_member_hook<boost::intrusive::link_mode<(boost::intrusive::link_mode_type)2>, void, void, void>, &range_tombstone::_link>, void, range_tombstone::compare, unsigned long, false, void>&&) at /usr/include/boost/intrusive/set.hpp:111
 (inlined by) boost::intrusive::set<range_tombstone, boost::intrusive::member_hook<range_tombstone, boost::intrusive::set_member_hook<boost::intrusive::link_mode<(boost::intrusive::link_mode_type)2>, void, void, void>, &range_tombstone::_link>, boost::intrusive::compare<range_tombstone::compare>, boost::intrusive::constant_time_size<false>, void, void, void>::set(boost::intrusive::set<range_tombstone, boost::intrusive::member_hook<range_tombstone, boost::intrusive::set_member_hook<boost::intrusive::link_mode<(boost::intrusive::link_mode_type)2>, void, void, void>, &range_tombstone::_link>, boost::intrusive::compare<range_tombstone::compare>, boost::intrusive::constant_time_size<false>, void, void, void>&&) at /usr/include/boost/intrusive/set.hpp:544
 (inlined by) range_tombstone_list::range_tombstone_list(range_tombstone_list&&) at ./range_tombstone_list.hh:105
 (inlined by) mutation_partition::mutation_partition(mutation_partition&&) at ./mutation_partition.hh:1247
 (inlined by) partition_version::partition_version(partition_version&&) at ./partition_version.cc:52
 (inlined by) standard_migrator<partition_version>::migrate(void*, void*, unsigned long) const at ././utils/allocation_strategy.hh:75
logalloc::region_impl::migrate_segment(logalloc::segment*, logalloc::segment_descriptor&, logalloc::segment*, logalloc::segment_descriptor&) at /usr/include/fmt/format.h:1158
 (inlined by) logalloc::segment_pool::migrate_segment(logalloc::segment*, logalloc::segment*) at ./utils/logalloc.cc:2060
logalloc::segment_pool::reclaim_segments(unsigned long) at /usr/include/fmt/format.h:1158
logalloc::tracker::impl::reclaim(unsigned long) at /usr/include/fmt/format.h:1158
 (inlined by) logalloc::tracker::reclaim(unsigned long) at ./utils/logalloc.cc:418
 (inlined by) logalloc::tracker::reclaim(seastar::memory::reclaimer::request) at ./utils/logalloc.cc:1679
 (inlined by) operator() at ./utils/logalloc.cc:411
 (inlined by) _M_invoke at /usr/include/c++/9/bits/std_function.h:285
std::function<seastar::memory::reclaiming_result (seastar::memory::reclaimer::request)>::operator()(seastar::memory::reclaimer::request) const at /usr/include/c++/9/ostream:221
 (inlined by) seastar::memory::reclaimer::do_reclaim(unsigned long) at ./build/release/seastar/./seastar/include/seastar/core/memory.hh:129
 (inlined by) seastar::memory::cpu_pages::run_reclaimers(seastar::memory::reclaimer_scope, unsigned long) at ./build/release/seastar/./seastar/src/core/memory.cc:1034
seastar::memory::cpu_pages::maybe_reclaim() at /usr/include/c++/9/ostream:221
 (inlined by) seastar::memory::cpu_pages::maybe_reclaim() at ./build/release/seastar/./seastar/src/core/memory.cc:613
 (inlined by) seastar::memory::cpu_pages::allocate_large_and_trim(unsigned int) at ./build/release/seastar/./seastar/src/core/memory.cc:656
seastar::memory::cpu_pages::allocate_large(unsigned int) at /usr/include/c++/9/ostream:221
 (inlined by) seastar::memory::allocate_large(unsigned long) at ./build/release/seastar/./seastar/src/core/memory.cc:1216
 (inlined by) seastar::memory::allocate(unsigned long) at ./build/release/seastar/./seastar/src/core/memory.cc:1268
 (inlined by) malloc at ./build/release/seastar/./seastar/src/core/memory.cc:1504
utils::chunked_vector<unsigned int, 131072ul>::make_room(unsigned long) at sstables.cc:?
 (inlined by) utils::chunked_vector<unsigned int, 131072ul>::make_room(unsigned long) at ././utils/chunked_vector.hh:380
sstables::seal_summary(sstables::summary_ka&, std::optional<sstables::key>&&, std::optional<sstables::key>&&, sstables::index_sampling_state const&) at sstables.cc:?
 (inlined by) utils::chunked_vector<unsigned int, 131072ul>::do_reserve_for_push_back() at ././utils/chunked_vector.hh:396
 (inlined by) utils::chunked_vector<unsigned int, 131072ul>::reserve_for_push_back() at ././utils/chunked_vector.hh:61
 (inlined by) utils::chunked_vector<unsigned int, 131072ul>::push_back(unsigned int&&) at ././utils/chunked_vector.hh:122
 (inlined by) sstables::seal_summary(sstables::summary_ka&, std::optional<sstables::key>&&, std::optional<sstables::key>&&, sstables::index_sampling_state const&) at ./sstables/sstables.cc:1832
sstables::mc::writer::consume_end_of_stream() at ././sstables/types.hh:261
sstables::compaction::finish_new_sstable(sstables::compaction_writer*) at /usr/include/fmt/format.h:1158
 (inlined by) sstables::regular_compaction::stop_sstable_writer(sstables::compaction_writer*) at ./sstables/compaction.cc:821
sstables::compacting_sstable_writer::consume_end_of_partition() at ./sstables/compaction.cc:676
 (inlined by) sstables::compacting_sstable_writer::consume_end_of_stream() at ./sstables/compaction.cc:672
 (inlined by) auto compact_mutation_state<(emit_only_live_rows)0, (compact_for_sstables)1>::consume_end_of_stream<sstables::compacting_sstable_writer, noop_compacted_fragments_consumer>(sstables::compacting_sstable_writer&, noop_compacted_fragments_consumer&) at ././mutation_compactor.hh:424
 (inlined by) compact_mutation<(emit_only_live_rows)0, (compact_for_sstables)1, sstables::compacting_sstable_writer, noop_compacted_fragments_consumer>::consume_end_of_stream() at ././mutation_compactor.hh:539
 (inlined by) stable_flattened_mutations_consumer<compact_for_compaction<sstables::compacting_sstable_writer, noop_compacted_fragments_consumer> >::consume_end_of_stream() at ././mutation_reader.hh:350
 (inlined by) auto flat_mutation_reader::impl::consume_in_thread<stable_flattened_mutations_consumer<compact_for_compaction<sstables::compacting_sstable_writer, noop_compacted_fragments_consumer> >, flat_mutation_reader::filter>(stable_flattened_mutations_consumer<compact_for_compaction<sstables::compacting_sstable_writer, noop_compacted_fragments_consumer> >, flat_mutation_reader::filter, std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >) at ././flat_mutation_reader.hh:281
 (inlined by) auto flat_mutation_reader::consume_in_thread<stable_flattened_mutations_consumer<compact_for_compaction<sstables::compacting_sstable_writer, noop_compacted_fragments_consumer> >, flat_mutation_reader::filter>(stable_flattened_mutations_consumer<compact_for_compaction<sstables::compacting_sstable_writer, noop_compacted_fragments_consumer> >, flat_mutation_reader::filter, std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >) at ././flat_mutation_reader.hh:400
 (inlined by) seastar::future<> sstables::compaction::setup<noop_compacted_fragments_consumer>(noop_compacted_fragments_consumer)::{lambda(flat_mutation_reader)#1}::operator()(flat_mutation_reader)::{lambda()#1}::operator()() at ./sstables/compaction.cc:543
seastar::apply_helper<seastar::future<> sstables::compaction::setup<noop_compacted_fragments_consumer>(noop_compacted_fragments_consumer)::{lambda(flat_mutation_reader)#1}::operator()(flat_mutation_reader)::{lambda()#1}, std::tuple<>&&, std::integer_sequence<unsigned long> >::apply({lambda(flat_mutation_reader)#1}&&, std::tuple) at ././seastar/include/seastar/core/apply.hh:36
 (inlined by) auto seastar::apply<seastar::future<> sstables::compaction::setup<noop_compacted_fragments_consumer>(noop_compacted_fragments_consumer)::{lambda(flat_mutation_reader)#1}::operator()(flat_mutation_reader)::{lambda()#1}>(seastar::future<> sstables::compaction::setup<noop_compacted_fragments_consumer>(noop_compacted_fragments_consumer)::{lambda(flat_mutation_reader)#1}::operator()(flat_mutation_reader)::{lambda()#1}&&, std::tuple<>&&) at ././seastar/include/seastar/core/apply.hh:44
 (inlined by) seastar::future<> seastar::futurize<void>::apply<seastar::future<> sstables::compaction::setup<noop_compacted_fragments_consumer>(noop_compacted_fragments_consumer)::{lambda(flat_mutation_reader)#1}::operator()(flat_mutation_reader)::{lambda()#1}>(seastar::future<> sstables::compaction::setup<noop_compacted_fragments_consumer>(noop_compacted_fragments_consumer)::{lambda(flat_mutation_reader)#1}::operator()(flat_mutation_reader)::{lambda()#1}&&, std::tuple<>&&) at ././seastar/include/seastar/core/future.hh:1647
 (inlined by) _ZZZN7seastar5asyncIZZN8sstables10compaction5setupI33noop_compacted_fragments_consumerEENS_6futureIJEEET_ENUl20flat_mutation_readerE_clES8_EUlvE_JEEENS_8futurizeINSt9result_ofIFNSt5decayIS7_E4typeEDpNSD_IT0_E4typeEEE4typeEE4typeENS_17thread_attributesEOS7_DpOSG_ENUlRZNS0_ISA_JEEESO_SP_SQ_SS_E4workE_clESU_ENKUlvE_clEv at ././seastar/include/seastar/core/thread.hh:253
 (inlined by) _ZN7seastar20noncopyable_functionIFvvEE17direct_vtable_forIZZNS_5asyncIZZN8sstables10compaction5setupI33noop_compacted_fragments_consumerEENS_6futureIJEEET_ENUl20flat_mutation_readerE_clESC_EUlvE_JEEENS_8futurizeINSt9result_ofIFNSt5decayISB_E4typeEDpNSH_IT0_E4typeEEE4typeEE4typeENS_17thread_attributesEOSB_DpOSK_ENUlRZNS4_ISE_JEEESS_ST_SU_SW_E4workE_clESY_EUlvE_E4callEPKS2_ at ././seastar/include/seastar/util/noncopyable_function.hh:101
seastar::noncopyable_function<void ()>::operator()() const at ./build/release/seastar/./seastar/include/seastar/util/noncopyable_function.hh:184
 (inlined by) seastar::thread_context::main() at ./build/release/seastar/./seastar/src/core/thread.cc:286
?? ??:0

```

Reactor stalls during the test:
```
< t:2020-05-01 04:59:33,138 f:cluster.py      l:1371 c:sdcm.cluster         p:DEBUG > 2020-05-01T04:59:31+00:00  perf-regression-latency-perf-v8-db-node-2854ab4a-3 !INFO    | scylla: Reactor stalled for 5 ms on shard 4.
< t:2020-05-01 04:59:33,158 f:sct_events.py   l:780  c:sdcm.sct_events      p:INFO  > 2020-05-01T04:59:31+00:00  perf-regression-latency-perf-v8-db-node-2854ab4a-3 !INFO    | scylla: Reactor stalled for 5 ms on shard 4.
< t:2020-05-01 05:02:03,225 f:cluster.py      l:1371 c:sdcm.cluster         p:DEBUG > 2020-05-01T05:01:59+00:00  perf-regression-latency-perf-v8-db-node-2854ab4a-3 !INFO    | scylla: Reactor stalled for 5 ms on shard 12.
< t:2020-05-01 05:02:03,242 f:sct_events.py   l:780  c:sdcm.sct_events      p:INFO  > 2020-05-01T05:01:59+00:00  perf-regression-latency-perf-v8-db-node-2854ab4a-3 !INFO    | scylla: Reactor stalled for 5 ms on shard 12.
< t:2020-05-01 05:15:03,560 f:cluster.py      l:1371 c:sdcm.cluster         p:DEBUG > 2020-05-01T05:14:52+00:00  perf-regression-latency-perf-v8-db-node-2854ab4a-3 !INFO    | scylla: Reactor stalled for 11 ms on shard 2.
< t:2020-05-01 05:15:03,578 f:sct_events.py   l:780  c:sdcm.sct_events      p:INFO  > 2020-05-01T05:14:52+00:00  perf-regression-latency-perf-v8-db-node-2854ab4a-3 !INFO    | scylla: Reactor stalled for 11 ms on shard 2.
< t:2020-05-01 05:17:09,831 f:cluster.py      l:1371 c:sdcm.cluster         p:DEBUG > 2020-05-01T05:17:06+00:00  perf-regression-latency-perf-v8-db-node-2854ab4a-1 !INFO    | scylla: Reactor stalled for 11 ms on shard 5.
< t:2020-05-01 05:17:09,846 f:sct_events.py   l:780  c:sdcm.sct_events      p:INFO  > 2020-05-01T05:17:06+00:00  perf-regression-latency-perf-v8-db-node-2854ab4a-1 !INFO    | scylla: Reactor stalled for 11 ms on shard 5.
< t:2020-05-01 05:20:39,968 f:cluster.py      l:1371 c:sdcm.cluster         p:DEBUG > 2020-05-01T05:20:35+00:00  perf-regression-latency-perf-v8-db-node-2854ab4a-1 !INFO    | scylla: Reactor stalled for 11 ms on shard 2.
< t:2020-05-01 05:20:39,985 f:sct_events.py   l:780  c:sdcm.sct_events      p:INFO  > 2020-05-01T05:20:35+00:00  perf-regression-latency-perf-v8-db-node-2854ab4a-1 !INFO    | scylla: Reactor stalled for 11 ms on shard 2.
< t:2020-05-01 05:20:54,987 f:cluster.py      l:1371 c:sdcm.cluster         p:DEBUG > 2020-05-01T05:20:43+00:00  perf-regression-latency-perf-v8-db-node-2854ab4a-1 !INFO    | scylla: Reactor stalled for 12 ms on shard 2.
< t:2020-05-01 05:20:54,992 f:cluster.py      l:1371 c:sdcm.cluster         p:DEBUG > 2020-05-01T05:20:43+00:00  perf-regression-latency-perf-v8-db-node-2854ab4a-1 !INFO    | scylla: Reactor stalled for 12 ms on shard 2.
< t:2020-05-01 05:20:54,997 f:cluster.py      l:1371 c:sdcm.cluster         p:DEBUG > 2020-05-01T05:20:43+00:00  perf-regression-latency-perf-v8-db-node-2854ab4a-1 !INFO    | scylla: Reactor stalled for 11 ms on shard 2.
< t:2020-05-01 05:20:55,018 f:sct_events.py   l:780  c:sdcm.sct_events      p:INFO  > 2020-05-01T05:20:43+00:00  perf-regression-latency-perf-v8-db-node-2854ab4a-1 !INFO    | scylla: Reactor stalled for 12 ms on shard 2.
< t:2020-05-01 05:20:55,030 f:sct_events.py   l:780  c:sdcm.sct_events      p:INFO  > 2020-05-01T05:20:43+00:00  perf-regression-latency-perf-v8-db-node-2854ab4a-1 !INFO    | scylla: Reactor stalled for 12 ms on shard 2.
< t:2020-05-01 05:20:55,042 f:sct_events.py   l:780  c:sdcm.sct_events      p:INFO  > 2020-05-01T05:20:43+00:00  perf-regression-latency-perf-v8-db-node-2854ab4a-1 !INFO    | scylla: Reactor stalled for 11 ms on shard 2.
< t:2020-05-01 05:21:18,778 f:cluster.py      l:1371 c:sdcm.cluster         p:DEBUG > 2020-05-01T05:21:16+00:00  perf-regression-latency-perf-v8-db-node-2854ab4a-3 !INFO    | scylla: Reactor stalled for 12 ms on shard 3.
< t:2020-05-01 05:21:18,794 f:sct_events.py   l:780  c:sdcm.sct_events      p:INFO  > 2020-05-01T05:21:16+00:00  perf-regression-latency-perf-v8-db-node-2854ab4a-3 !INFO    | scylla: Reactor stalled for 12 ms on shard 3.
```

**Comment by roydahan** [comment] 2020-05-05 20:02
In case it helps, here is a list of commits between the the good and suspected build:

```
*   dee0b6834 - Merge 'Separate sharding and partitioning logic' from Piotr J (5 weeks ago) <Avi Kivity>
|\
| * c44f019ee - dummy_sharder: rename dummy_sharding_info.* to dummy_sharder.* (5 weeks ago) <Piotr Jastrzebski>
| * e72696a8e - sharding_info: rename the class to sharder (5 weeks ago) <Piotr Jastrzebski>
| * 2e850421a - i_partitioner:remove embeded sharding_info (5 weeks ago) <Piotr Jastrzebski>
| * b46b35c55 - i_partitioner: remove unused get_sharding_info (5 weeks ago) <Piotr Jastrzebski>
| * 92cdc2112 - schema: remove incorrect comment (5 weeks ago) <Piotr Jastrzebski>
| * 7bd2b8d73 - schema: make it possible to set sharding_info per schema (5 weeks ago) <Piotr Jastrzebski>
| * 79adee2fa - i_partitioner: remove unused shard_count (5 weeks ago) <Piotr Jastrzebski>
| * db3d7df89 - multishard_writer: stop calling i_partitioner::shard_count (5 weeks ago) <Piotr Jastrzebski>
| * b7834634e - i_partitioner: remove sharding_ignore_msb (5 weeks ago) <Piotr Jastrzebski>
| * fb89841cc - partitioner_test: test ranges and sharding_infos (5 weeks ago) <Piotr Jastrzebski>
| * 2aaa33d02 - i_partitioner: remove unused split_ranges_to_shards (5 weeks ago) <Piotr Jastrzebski>
| * bdb7e8904 - i_partitioner: remove unused shard_of function (5 weeks ago) <Piotr Jastrzebski>
| * 14ad96573 - sstable-utils: use sharding_info::shard_of (5 weeks ago) <Piotr Jastrzebski>
| * dc2e06031 - create_token_range_from_keys: use sharding info for shard_of (5 weeks ago) <Piotr Jastrzebski>
| * c50f7f814 - multishard_mutation_query_test: use sharding info for shard_of (5 weeks ago) <Piotr Jastrzebski>
| * 8aabba604 - distribute_reader_and_consume_on_shards: use sharding_info::shard_of (5 weeks ago) <Piotr Jastrzebski>
| * d8ac8fd6e - multishard_mutation_query: use sharding_info::shard_of (5 weeks ago) <Piotr Jastrzebski>
| * 88364b6c3 - dht::shard_of: use schema::get_sharding_info (5 weeks ago) <Piotr Jastrzebski>
| * 8b6be9031 - i_partitioner: remove unused token_for_next_shard (5 weeks ago) <Piotr Jastrzebski>
| * 8a6c37735 - split_range_to_single_shard: use sharding info instead of partitioner (5 weeks ago) <Piotr Jastrzebski>
| * c5d088747 - schema_builder: remove unused with_partitioner_for_tests_only (5 weeks ago) <Piotr Jastrzebski>
| * 41591f15d - tests: rename dummy_partitioner.* to dummy_sharding_info.* (5 weeks ago) <Piotr Jastrzebski>
| * 031f589db - multishard_combining_reader: use token_for_next_shard from sharding info not partitioner (5 weeks ago) <Piotr Jastrzebski>
| * 274a04564 - partitioner_test: use token_for_next_shard from sharding info not partitioner (5 weeks ago) <Piotr Jastrzebski>
| * a3262a2cb - repair: depend only on sharding logic not on partitioner (5 weeks ago) <Piotr Jastrzebski>
| * dffa9fc88 - dht: remove unimplemented split_range_to_single_shard (5 weeks ago) <Piotr Jastrzebski>
| * 94ff653b9 - selective_token_range_sharder: replace i_partitioner with sharding_info (5 weeks ago) <Piotr Jastrzebski>
| * ecff322fd - ring_position_range_vector_sharder: replace i_partitioner with sharding_info (5 weeks ago) <Piotr Jastrzebski>
| * 8a4c1be12 - ring_position_range_sharder: replace i_partitioner with sharding_info (5 weeks ago) <Piotr Jastrzebski>
| * 52fe24131 - dht: remove unused ring_position_exponential_sharder (5 weeks ago) <Piotr Jastrzebski>
| * 8d81a2498 - schema: add get_sharding_info (5 weeks ago) <Piotr Jastrzebski>
| * ca07f8e84 - partitioner: extract sharding fields to a class (5 weeks ago) <Piotr Jastrzebski>
* | 4a3b98fac - utils: error injection fix deadline test timeout (5 weeks ago) <Alejo Sanchez>
* | e5a2ba32b - utils: error injection allocate string for remote invoke (5 weeks ago) <Alejo Sanchez>
* | fe6cecb26 - alternator-test: comment out an error-path test that doesn't work on newer boto3 (5 weeks ago) <Nadav Har'El>
* | db7cebd66 - alternator-test: skip one test in test_tag.py if botocore is too old (5 weeks ago) <Nadav Har'El>
* | 8a408ac5a - lwt: remove entries from system.paxos table after successful learn stage (5 weeks ago) <Gleb Natapov>
* |   f2b091967 - Merge "migration_manager: Make sync_schema return error when node is down" from Asias (5 weeks ago) <Tomasz Grabiec>
|\ \
| * | ef64f5215 - migration_manager: Do not swallow exception in migration_task::run_may_throw (5 weeks ago) <Asias He>
| * | 7ba821cbc - migration_manager: Make sync_schema return error when node is down (6 weeks ago) <Asias He>
|  /
* | b3db6f5b0 - lwt: rename "in_progress_ballot" cell to "promise" in system.paxos table (5 weeks ago) <Gleb Natapov>
* | fba6db4a4 - Update seastar submodule (5 weeks ago) <Avi Kivity>
* | 68750b777 - priority_manager: deinline constructor (5 weeks ago) <Avi Kivity>
|/
* 3159ad448 - Update seastar submodule (5 weeks ago) <Avi Kivity>
* 0d224210b - database: apply_in_memory(): don't look-up the column-family twice (6 weeks ago) <Botond Dénes>
* 743b529c2 - gossip: Add an option to force gossip generation (6 weeks ago) <Asias He>
* c5795e819 - everywhere: Replace engine().cpu_id() with this_shard_id() (6 weeks ago) <Rafael Ávila de Espíndola>
*   c639a5ec6 - merge: fix two CDC bugs with preimage/postimage (6 weeks ago) <Nadav Har'El>
|\
| * 532a8634c - cdc::log: Only generate pre/post-image when enabled (6 weeks ago) <Calle Wilund>
| * 881ebe192 - cdc::log: Handle non-atomic column assignments broken into two (6 weeks ago) <Calle Wilund>
* cb26de89a - tests: port Cassandra CQL tests to cql repl (6 weeks ago) <Alejo Sanchez>
* febcced4f - utils: error injection with timeout/deadline (6 weeks ago) <Alejo Sanchez>
* 6bcc46b08 - cql3: add missing error message context to query processor (6 weeks ago) <Piotr Sarna>
* 1178ac556 - test: move config to heap in sstable_resharding_test (6 weeks ago) <Piotr Sarna>
* 5ef9dbfa8 - test: move config to heap in schema_registry_test (6 weeks ago) <Piotr Sarna>
* a0f025f4c - sstable: LA format is the default, so ignore "LA_SSTABLE" feature flag (6 weeks ago) <Nadav Har'El>
* 91aba4011 - sstable: default to LA format instead of KA format (6 weeks ago) <Nadav Har'El>
* eca0ac577 - everywhere: Update for deprecated apply functions (6 weeks ago) <Rafael Ávila de Espíndola>
* 088660680 - Update seastar submodule (6 weeks ago) <Avi Kivity>
* 0418a74fa - querier: consume_page(): resolve FIXME related to non-movable consumer (6 weeks ago) <Botond Dénes>
*   a31428346 - Merge "Minor cleanups to cql3 code regarding shared_ptr's" from Pavel S (6 weeks ago) <Avi Kivity>
|\
| * adc6a98b5 - cql3: return raw::parsed_statement as unique_ptr (6 weeks ago) <Pavel Solodovnikov>
| * df1d687fc - cql3: de-pointerize arguments to some of CQL grammar rules and definitions. (6 weeks ago) <Pavel Solodovnikov>
| * 279b52f27 - cql3: make abstract_marker::make_in_receiver accept cref to column_specification (6 weeks ago) <Pavel Solodovnikov>
* 9fee712d6 - db::commitlog: Don't write trailing zero block unless needed (6 weeks ago) <Calle Wilund>
```

**Comment by avikivity** [comment] 2020-05-05 20:10
Only 9fee712d6 looks vaguely related.

**Comment by avikivity** [comment] 2020-05-05 20:11
@roydahan we can bisect within those commits, I can give you rpms to test.

**Comment by avikivity** [comment] 2020-05-05 20:12
The stall you reported is not wonderful, but not terrible either. It happens when we complete an sstable, which is a rare event. Easy to fix too.

**Comment by avikivity** [comment] 2020-05-13 06:05
@roydahan any news here?

**Comment by roydahan** [comment] 2020-05-13 10:57
@avikivity sorry, but how is it pending on me? what did I miss?

**Comment by bhalevy** [comment] 2020-06-22 05:53
@xemul can you try to bisect the commits range mentioned above and pinpoint the commit that caused this regression.  Now, even if changing the row cache to b+tree, let's shoot for a simpler fix for backporting to 4.0 (#6378) and 4.1.

**Comment by bhalevy** [comment] 2020-06-23 14:38
Could this be caused by https://github.com/scylladb/scylla/issues/5857?

**Comment by bhalevy** [comment] 2020-06-23 14:39
> Could this be caused by #5857?

Sorry, the respective fix is included in the version in this issue

**Comment by xemul** [comment] 2020-06-26 13:04
For the record. Re-run on commit dee0b68, ami-0ff0d10d392b499a5 [logs](https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/pavel/job/pavel-byo-sct/9/console)

**Comment by xemul** [comment] 2020-06-27 06:30
9fee712 (ami-0ff0d10d392b499a5) [logs](https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/pavel/job/pavel-byo-sct/10/consoleFull)

**Comment by xemul** [comment] 2020-07-01 16:53
While the bisect is running, I've noticed that commit

```
commit 3159ad4484b26f424d9a4657c58f678d76db70d4
Author: Avi Kivity <avi@scylladb.com>
Date:   Sun Mar 29 15:37:45 2020 +0300

    Update seastar submodule
    
    * seastar c7b6b84e5...06a8c8f6e (12):
      > scheduling_group_specific: remove inclusion of reactor.hh
      > future: Delete void_futurize_helper
      > future: Delete unused do_void_futurize_helper instantiation
      > core: remove io_queue queued requests metric
      > future: Add assert to set_urgent_state
      > future: Add a comment to set_urgent_state
      > future: Use placement new instead of operator= in set_urgent_state
      > file: use correct io_queue in dup()d files
      > io_queue: fix miscalculation of sizes when I/O queue is not configured.
      > merge: Add log levels to RPC loggers
      > reactor: Replace a call to cpu_id with this_shard_id()
      > reactor: Drop a few redundant calls to engine()
```

causes reproducible though small (~1.5%) degradation in `perf/perf_sstable --mode write` -- the result drops from 260k partitions to 256k partitions per second.

**Comment by bhalevy** [comment] 2020-07-02 06:38
Cc @espindola ^^^

**Comment by bhalevy** [comment] 2020-07-07 14:31
Let's bisect the seastar update to pinpoint the exact seastar patch that caused the small degradation in perormance.
Otherwise, it seems like the latency spikes could have caused by environment issues (aged NVMe drives?)
Ideally, we should run the system performance tests on totally predictable hardware, like large ram drives.

**Comment by xemul** [comment] 2020-07-07 14:32
commit 41591f15d [logs](https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/pavel/job/pavel-byo-sct/12/consoleFull)

```
'latency_write_99': {
        'max': 56049.69536153379,
         'min': 4094.709272700059,
         'avg': 9315.807700311145,
         'stdev': 3756.6503753375264}
}
```

**Comment by avikivity** [comment] 2020-07-07 16:27
RAM drives are predicatable, but don't have the same latency characteristics.

**Comment by avikivity** [comment] 2020-07-07 16:33
@xemul how are you differentiating between good and bad? for example https://github.com/scylladb/scylla/issues/6377#issuecomment-650506024 has 10ms average 99th percentile latency.

**Comment by avikivity** [comment] 2020-07-07 17:02
I looked at 9fee712d6285db8a4b0f8b8115cc750d12c49d7e..dee0b6834738778921fc582b5a90484a214ef56f again and couldn't find anything that could remotely trigger it.

**Comment by xemul** [comment] 2020-07-09 07:47
@avikivity , I picked this from issue description 

> Last known good version: 666.development. 20200325. 9fee712 (ami-0ff0d10d392b499a5)
> First AMI I could spot the issue: 666.development. 20200401. dee0b68 (ami-0a5a2f8bfe904aed3)

then tested 9feee712, dee0b68 (and one commit in the middle just to have the 3rd point) to compare them to each other. Marks "good" and "bad" are expectations about the former being good and the latter being bad. Apparently this expectation failed.

**Comment by slivne** [comment] 2020-10-25 10:55
We attempted to search for this possible regression and failed - the row cache has changed (and it showed a huge improvement in latecy - and removing stalls) - closing this issue

**Closed by slivne** 2020-10-25 10:55 UTC
