### ISSUE TITLE
Add 'CACHE BYPASS' qualifier to write statements

### ISSUE THREAD

**Issue by vladzcloudius** [scylladb/scylla#5284] opened 2019-11-15 01:52 UTC
*Installation details*
Scylla version: 3.1

*Description*
We need a 'CACHE BYPASS' qualifier for write statements in order to be able to prevent cache population in a write flow similarly how we allow preventing it in the read flow.

Examples when this may be useful:
  * 'Scanning write': when the whole table is being updated in a sweep (some statistics column for example).
  * When the whole table is being sequentially written and it triggers the "time series" heuristics however user doesn't want it to be triggered.

**Comment by slivne** [comment] 2019-11-17 11:07
duplicate of #5015

**Closed by slivne** 2019-11-17 11:07 UTC
