### ISSUE TITLE
Cluster nodes erroneously marking other nodes as DOWN by gossip

### ISSUE THREAD

**Issue by svetob** [scylladb/scylla#2014] opened 2017-01-16 12:45 UTC
*Installation details*
Scylla version (or git commit hash): 1.5
Cluster size: 9 nodes
OS (RHEL/CentOS/Ubuntu/AWS AMI): CentOS

*Hardware details (for performance issues)*
Platform (physical/VM/cloud instance type/docker): AWS m4.2xlarge
Disks: 1x 1500GB gp2 EBS per node

*Details*
We have been running a scale-test on a 9-node scylla cluster. N=3, quorum=QUORUM. After a few days of indexing at roughly 80K DPS, writes have started failing with "Not enough replicas available for query at consistency QUORUM (2 required but only 1 alive)" due to some nodes being erroneously marked as down by gossip.

`nodetool status` on seed node 001 shows:
```
Datacenter: datacenter1
=======================
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address        Load       Tokens  Owns    Host ID                               Rack
UN  10.14.102.191  782.56 GB  256     ?       879f1521-73d9-41d1-abcd-6fb287317c6b  rack1
UN  10.14.103.28   802.61 GB  256     ?       1021dab7-3004-44d2-9c45-ccffe11f5d20  rack1
UN  10.14.101.204  808.73 GB  256     ?       95b03c51-6959-47e5-86f3-48f0e421f23c  rack1
UN  10.14.102.29   820.59 GB  256     ?       ffe01892-f776-49f3-b254-94bf918ea022  rack1
UN  10.14.103.56   838.25 GB  256     ?       0cf484f6-d2e2-42f1-8720-d29e37dd61ef  rack1
DN  10.14.101.6    797.48 GB  256     ?       887486ab-405a-4f45-9fb0-697c5f5b5a9c  rack1
UN  10.14.102.228  749.84 GB  256     ?       6512be89-047d-4af7-aa53-b254ba18a552  rack1
DN  10.14.103.131  655.44 GB  256     ?       c7d5e1e9-d5aa-4d5d-be78-7c72eff5ef6b  rack1
UN  10.14.101.227  743.35 GB  256     ?       1eb5af2d-efb9-4510-b72c-85bc0c19489c  rack1
```

On node 009 (10.14.103.131), which was marked as DN, the response is:
```
Datacenter: datacenter1
=======================
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address        Load       Tokens  Owns    Host ID                               Rack
DN  10.14.102.191  782.56 GB  256     ?       879f1521-73d9-41d1-abcd-6fb287317c6b  rack1
DN  10.14.103.28   802.61 GB  256     ?       1021dab7-3004-44d2-9c45-ccffe11f5d20  rack1
DN  10.14.101.204  808.73 GB  256     ?       95b03c51-6959-47e5-86f3-48f0e421f23c  rack1
DN  10.14.102.29   820.59 GB  256     ?       ffe01892-f776-49f3-b254-94bf918ea022  rack1
DN  10.14.103.56   838.25 GB  256     ?       0cf484f6-d2e2-42f1-8720-d29e37dd61ef  rack1
DN  10.14.101.6    797.48 GB  256     ?       887486ab-405a-4f45-9fb0-697c5f5b5a9c  rack1
DN  10.14.102.228  749.84 GB  256     ?       6512be89-047d-4af7-aa53-b254ba18a552  rack1
UN  10.14.103.131  655.44 GB  256     ?       c7d5e1e9-d5aa-4d5d-be78-7c72eff5ef6b  rack1
DN  10.14.101.227  743.35 GB  256     ?       1eb5af2d-efb9-4510-b72c-85bc0c19489c  rack1
```

Logs on 009 are showing that nodes are getting marked as DOWN, after which EchoMessage repeatedly fails with timeout:
```
Jan 15 20:32:23 ip-10-14-103-131.hamsterscale scylla[26873]:  [shard 0] gossip - InetAddress 10.14.101.6 is now DOWN, status = NORMAL
Jan 15 20:32:31 ip-10-14-103-131.hamsterscale scylla[26873]:  [shard 0] gossip - Fail to send EchoMessage to 10.14.101.6:0: rpc::timeout_error (rpc call timed out)
Jan 15 20:32:32 ip-10-14-103-131.hamsterscale scylla[26873]:  [shard 0] gossip - Fail to send EchoMessage to 10.14.101.6:0: rpc::timeout_error (rpc call timed out)
Jan 15 20:32:38 ip-10-14-103-131.hamsterscale scylla[26873]:  [shard 0] gossip - Fail to send EchoMessage to 10.14.101.6:0: rpc::timeout_error (rpc call timed out)
Jan 15 20:32:41 ip-10-14-103-131.hamsterscale scylla[26873]:  [shard 0] gossip - Fail to send EchoMessage to 10.14.101.6:0: rpc::timeout_error (rpc call timed out)
Jan 15 20:32:46 ip-10-14-103-131.hamsterscale scylla[26873]:  [shard 0] gossip - Fail to send EchoMessage to 10.14.101.6:0: rpc::timeout_error (rpc call timed out)
Jan 15 20:32:53 ip-10-14-103-131.hamsterscale scylla[26873]:  [shard 0] gossip - Fail to send EchoMessage to 10.14.101.6:0: rpc::timeout_error (rpc call timed out)
Jan 15 20:33:03 ip-10-14-103-131.hamsterscale scylla[26873]:  [shard 0] gossip - Fail to send EchoMessage to 10.14.101.6:0: rpc::timeout_error (rpc call timed out)
Jan 15 20:33:09 ip-10-14-103-131.hamsterscale scylla[26873]:  [shard 0] gossip - Fail to send 

...

Jan 15 20:37:03 ip-10-14-103-131.hamsterscale scylla[26873]:  [shard 0] gossip - Fail to send EchoMessage to 10.14.101.6:0: rpc::timeout_error (rpc call timed out)
Jan 15 20:38:03 ip-10-14-103-131.hamsterscale scylla[26873]:  [shard 0] gossip - Fail to send EchoMessage to 10.14.101.6:0: rpc::timeout_error (rpc call timed out)
Jan 15 20:39:04 ip-10-14-103-131.hamsterscale scylla[26873]:  [shard 0] gossip - Fail to send EchoMessage to 10.14.101.6:0: rpc::timeout_error (rpc call timed out)
Jan 15 20:40:03 ip-10-14-103-131.hamsterscale scylla[26873]:  [shard 0] gossip - Fail to send EchoMessage to 10.14.101.6:0: rpc::timeout_error (rpc call timed out)
Jan 15 20:41:03 ip-10-14-103-131.hamsterscale scylla[26873]:  [shard 0] gossip - Fail to send EchoMessage to 10.14.101.6:0: rpc::timeout_error (rpc call timed out)
Jan 15 23:38:45 ip-10-14-103-131.hamsterscale scylla[26873]:  [shard 0] gossip - InetAddress 10.14.102.29 is now DOWN, status = NORMAL
Jan 15 23:38:49 ip-10-14-103-131.hamsterscale scylla[26873]:  [shard 0] gossip - Fail to send EchoMessage to 10.14.102.29:0: rpc::timeout_error (rpc call timed out)
Jan 15 23:38:50 ip-10-14-103-131.hamsterscale scylla[26873]:  [shard 0] gossip - Fail to send EchoMessage to 10.14.102.29:0: rpc::timeout_error (rpc call timed out)
Jan 15 23:38:53 ip-10-14-103-131.hamsterscale scylla[26873]:  [shard 0] gossip - Fail to send EchoMessage to 10.14.102.29:0: rpc::timeout_error (rpc call timed out)
Jan 15 23:38:59 ip-10-14-103-131.hamsterscale scylla[26873]:  [shard 0] gossip - Fail to send EchoMessage to 10.14.102.29:0: rpc::timeout_error (rpc call timed out)
Jan 15 23:39:02 ip-10-14-103-131.hamsterscale scylla[26873]:  [shard 0] gossip - Fail to send EchoMessage to 10.14.102.29:0: rpc::timeout_error (rpc call timed out)
Jan 15 23:39:07 ip-10-14-103-131.hamsterscale scylla[26873]:  [shard 0] gossip - Fail to send EchoMessage to 10.14.102.29:0: rpc::timeout_error (rpc call timed out)
Jan 15 23:39:11 ip-10-14-103-131.hamsterscale scylla[26873]:  [shard 0] gossip - Fail to send EchoMessage to 10.14.102.29:0: rpc::timeout_error (rpc call timed out)

...

an 16 04:34:35 ip-10-14-103-131.hamsterscale scylla[26873]:  [shard 0] gossip - Fail to send EchoMessage to 10.14.102.29:0: rpc::timeout_error (rpc call timed out)
Jan 16 04:34:40 ip-10-14-103-131.hamsterscale scylla[26873]:  [shard 0] gossip - Fail to send EchoMessage to 10.14.102.29:0: rpc::timeout_error (rpc call timed out)
Jan 16 04:34:45 ip-10-14-103-131.hamsterscale scylla[26873]:  [shard 0] gossip - Fail to send EchoMessage to 10.14.102.29:0: rpc::timeout_error (rpc call timed out)
Jan 16 04:34:47 ip-10-14-103-131.hamsterscale scylla[26873]:  [shard 0] gossip - Fail to send EchoMessage to 10.14.102.29:0: rpc::timeout_error (rpc call timed out)
Jan 16 04:35:04 ip-10-14-103-131.hamsterscale scylla[26873]:  [shard 0] gossip - InetAddress 10.14.103.56 is now DOWN, status = NORMAL
Jan 16 04:35:05 ip-10-14-103-131.hamsterscale scylla[26873]:  [shard 0] gossip - InetAddress 10.14.102.228 is now DOWN, status = NORMAL
Jan 16 04:35:05 ip-10-14-103-131.hamsterscale scylla[26873]:  [shard 0] gossip - InetAddress 10.14.103.28 is now DOWN, status = NORMAL
Jan 16 04:35:06 ip-10-14-103-131.hamsterscale scylla[26873]:  [shard 0] gossip - InetAddress 10.14.103.28 is now UP, status = NORMAL
Jan 16 04:35:07 ip-10-14-103-131.hamsterscale scylla[26873]:  [shard 0] gossip - do_gossip_to_live_member: Favor newly added node 10.14.103.28
Jan 16 04:35:08 ip-10-14-103-131.hamsterscale scylla[26873]:  [shard 0] gossip - Fail to send EchoMessage to 10.14.102.29:0: rpc::timeout_error (rpc call timed out)
Jan 16 04:35:08 ip-10-14-103-131.hamsterscale scylla[26873]:  [shard 0] gossip - Fail to send EchoMessage to 10.14.102.29:0: rpc::timeout_error (rpc call timed out)
Jan 16 04:35:09 ip-10-14-103-131.hamsterscale scylla[26873]:  [shard 0] gossip - Fail to send EchoMessage to 10.14.102.228:0: rpc::timeout_error (rpc call timed out)
Jan 16 04:35:09 ip-10-14-103-131.hamsterscale scylla[26873]:  [shard 0] gossip - Fail to send EchoMessage to 10.14.103.56:0: rpc::timeout_error (rpc call timed out)
Jan 16 04:35:11 ip-10-14-103-131.hamsterscale scylla[26873]:  [shard 0] gossip - Fail to send EchoMessage to 10.14.102.228:0: rpc::timeout_error (rpc call timed out)
Jan 16 04:35:11 ip-10-14-103-131.hamsterscale scylla[26873]:  [shard 0] gossip - Fail to send EchoMessage to 10.14.102.228:0: rpc::timeout_error (rpc call timed out)
Jan 16 04:35:11 ip-10-14-103-131.hamsterscale scylla[26873]:  [shard 0] gossip - Fail to send EchoMessage to 10.14.102.228:0: rpc::timeout_error (rpc call timed out)
Jan 16 04:35:11 ip-10-14-103-131.hamsterscale scylla[26873]:  [shard 0] gossip - Fail to send EchoMessage to 10.14.102.29:0: rpc::timeout_error (rpc call timed out)
Jan 16 04:35:12 ip-10-14-103-131.hamsterscale scylla[26873]:  [shard 0] gossip - Fail to send EchoMessage to 10.14.103.56:0: rpc::timeout_error (rpc call timed out)
Jan 16 04:35:12 ip-10-14-103-131.hamsterscale scylla[26873]:  [shard 0] gossip - Fail to send EchoMessage to 10.14.102.228:0: rpc::timeout_error (rpc call timed out)
Jan 16 04:35:14 ip-10-14-103-131.hamsterscale scylla[26873]:  [shard 0] gossip - Fail to send EchoMessage to 10.14.103.56:0: rpc::timeout_error (rpc call timed out)
Jan 16 04:35:14 ip-10-14-103-131.hamsterscale scylla[26873]:  [shard 0] gossip - Fail to send EchoMessage to 10.14.103.56:0: rpc::timeout_error (rpc call timed out)
Jan 16 04:35:14 ip-10-14-103-131.hamsterscale scylla[26873]:  [shard 0] gossip - Fail to send EchoMessage to 10.14.103.56:0: rpc::timeout_error (rpc call timed out)
Jan 16 04:35:14 ip-10-14-103-131.hamsterscale scylla[26873]:  [shard 0] gossip - Fail to send EchoMessage to 10.14.102.228:0: rpc::timeout_error (rpc call timed out)
Jan 16 04:35:15 ip-10-14-103-131.hamsterscale scylla[26873]:  [shard 0] gossip - Fail to send EchoMessage to 10.14.102.29:0: rpc::timeout_error (rpc call timed out)
Jan 16 04:35:15 ip-10-14-103-131.hamsterscale scylla[26873]:  [shard 0] gossip - Fail to send EchoMessage to 10.14.103.56:0: rpc::timeout_error (rpc call timed out)
Jan 16 04:35:15 ip-10-14-103-131.hamsterscale scylla[26873]:  [shard 0] gossip - Fail to send EchoMessage to 10.14.102.228:0: rpc::timeout_error (rpc call timed out)
```

After `sudo service scylla-server restart` on 009 (which prints a segfault to the logs during shutdown, but then starts up OK) we get from `nodetool status`:
```
Datacenter: datacenter1
=======================
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address        Load       Tokens  Owns    Host ID                               Rack
UN  10.14.102.191  782.56 GB  256     ?       879f1521-73d9-41d1-abcd-6fb287317c6b  rack1
UN  10.14.103.28   802.61 GB  256     ?       1021dab7-3004-44d2-9c45-ccffe11f5d20  rack1
DN  10.14.101.204  808.73 GB  256     ?       95b03c51-6959-47e5-86f3-48f0e421f23c  rack1
DN  10.14.102.29   820.59 GB  256     ?       ffe01892-f776-49f3-b254-94bf918ea022  rack1
UN  10.14.103.56   838.25 GB  256     ?       0cf484f6-d2e2-42f1-8720-d29e37dd61ef  rack1
DN  10.14.101.6    797.48 GB  256     ?       887486ab-405a-4f45-9fb0-697c5f5b5a9c  rack1
UN  10.14.102.228  749.84 GB  256     ?       6512be89-047d-4af7-aa53-b254ba18a552  rack1
UN  10.14.103.131  655.44 GB  256     ?       c7d5e1e9-d5aa-4d5d-be78-7c72eff5ef6b  rack1
DN  10.14.101.227  743.35 GB  256     ?       1eb5af2d-efb9-4510-b72c-85bc0c19489c  rack1
```

Better but still only halfway there. Logs are still complaining about EchoMessages for some of the nodes:
```
Jan 16 12:30:49 ip-10-14-103-131.hamsterscale scylla[11168]:  [shard 0] gossip - Fail to send EchoMessage to 10.14.102.29:0: rpc::timeout_error (rpc call timed out)
Jan 16 12:30:49 ip-10-14-103-131.hamsterscale scylla[11168]:  [shard 0] gossip - Fail to send EchoMessage to 10.14.101.227:0: rpc::timeout_error (rpc call timed out)
Jan 16 12:30:50 ip-10-14-103-131.hamsterscale scylla[11168]:  [shard 0] gossip - Fail to send EchoMessage to 10.14.101.204:0: rpc::timeout_error (rpc call timed out)
Jan 16 12:30:50 ip-10-14-103-131.hamsterscale scylla[11168]:  [shard 0] gossip - Fail to send EchoMessage to 10.14.102.29:0: rpc::timeout_error (rpc call timed out)
Jan 16 12:30:50 ip-10-14-103-131.hamsterscale scylla[11168]:  [shard 0] gossip - Fail to send EchoMessage to 10.14.101.227:0: rpc::timeout_error (rpc call timed out)
Jan 16 12:30:51 ip-10-14-103-131.hamsterscale scylla[11168]:  [shard 0] gossip - Fail to send EchoMessage to 10.14.102.29:0: rpc::timeout_error (rpc call timed out)
Jan 16 12:30:52 ip-10-14-103-131.hamsterscale scylla[11168]:  [shard 0] gossip - Fail to send EchoMessage to 10.14.101.227:0: rpc::timeout_error (rpc call timed out)
Jan 16 12:30:54 ip-10-14-103-131.hamsterscale scylla[11168]:  [shard 0] gossip - Fail to send EchoMessage to 10.14.101.204:0: rpc::timeout_error (rpc call timed out)
Jan 16 12:30:54 ip-10-14-103-131.hamsterscale scylla[11168]:  [shard 0] gossip - Fail to send EchoMessage to 10.14.101.204:0: rpc::timeout_error (rpc call timed out)
```

and seed node 001 finds the node to be available:
```
Datacenter: datacenter1
=======================
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address        Load       Tokens  Owns    Host ID                               Rack
UN  10.14.102.191  782.56 GB  256     ?       879f1521-73d9-41d1-abcd-6fb287317c6b  rack1
UN  10.14.103.28   802.61 GB  256     ?       1021dab7-3004-44d2-9c45-ccffe11f5d20  rack1
UN  10.14.101.204  808.73 GB  256     ?       95b03c51-6959-47e5-86f3-48f0e421f23c  rack1
UN  10.14.102.29   820.59 GB  256     ?       ffe01892-f776-49f3-b254-94bf918ea022  rack1
UN  10.14.103.56   838.25 GB  256     ?       0cf484f6-d2e2-42f1-8720-d29e37dd61ef  rack1
DN  10.14.101.6    797.48 GB  256     ?       887486ab-405a-4f45-9fb0-697c5f5b5a9c  rack1
UN  10.14.102.228  749.84 GB  256     ?       6512be89-047d-4af7-aa53-b254ba18a552  rack1
UN  10.14.103.131  655.44 GB  256     ?       c7d5e1e9-d5aa-4d5d-be78-7c72eff5ef6b  rack1
UN  10.14.101.227  743.35 GB  256     ?       1eb5af2d-efb9-4510-b72c-85bc0c19489c  rack1
```

We are seeing similar status and behaviour on most nodes. Each node has similar issues with telling which nodes are UP or DOWN, and shows similar EchoMessage logs.

Finally, ping and curl on IP's currently marked DN works fine, so it seems not to be an actual network issue.

**Comment by penberg** [comment] 2017-01-16 14:15
Looks similar to #1996.

/cc @gleb-cloudius @asias

**Comment by gleb-cloudius** [comment] 2017-01-23 08:41
I see that in issue #2014 you report that the node 10.14.101.6 has
memory issues. Is this happen simultaneously? It may be that 10.14.101.6
fail to process gossiper messages from 10.14.103.131 due to not
having enough memory, but that's just a theory.

--
			Gleb.

**Comment by svetob** [comment] 2017-01-23 22:01
This was happening before and after node 10.14.101.6 encountered memory issues, and most nodes in the cluster seemed to be affected by it.

**Comment by gleb-cloudius** [comment] 2017-01-24 09:12
m4.2xlarge is listed as having "High" networking bandwidth, but I did not find anything official about how "high" is it (unofficially it is around 1Gbps) and if it is guarantied to stay the same. When you have connectivity problem can you check what is your bandwidth usage?

**Comment by tzach** [comment] 2017-02-08 11:49
@slivne

**Comment by glommer** [comment] 2017-02-08 15:03
We need to come up with a reproducer for this. I am almost certain that this is a load issue that would happen when the gossip messages find themselves behind a storm of continuations - could even be fixed by the avalanche patches recently merged.

**Comment by avikivity** [comment] 2020-08-05 16:23
Stale, closing.

**Closed by avikivity** 2020-08-05 16:23 UTC
Labels: User Request, bug, stability
