### ISSUE TITLE
Add support for a compaction of one of more user defined SSTables

### ISSUE THREAD

**Issue by vladzcloudius** [scylladb/scylla#5927] opened 2020-02-28 21:08 UTC
*Installation details*
HEAD: 4e95b67501c33e3f9ea0b1d2cfbd428a640e494a

*Description*
Add support for compacting one or more user defined SSTable similar to Cassandra as described here:
https://docs.datastax.com/en/dse/5.1/dse-admin/datastax_enterprise/tools/nodetool/toolsCompact.html

This is particularly helpful when one needs to get rid of the expired data but the compactition strategy doesn't do it in the best way for some reason.

**Comment by vladzcloudius** [comment] 2020-02-28 21:09
@glommer @raphaelsc FYI

**Comment by glommer** [comment] 2020-02-28 21:11
This makes sense to have insofar as Cassandra has it.
(To be honest I don't quite like the option).

It's an easy project to do so I am marking this as entry level if anyone is looking for a way to start contributing.

**Comment by raphaelsc** [comment] 2020-02-28 21:19
On Fri, Feb 28, 2020 at 6:08 PM vladzcloudius <notifications@github.com>
wrote:

> *Installation details*
> HEAD: 4e95b67
> <https://github.com/scylladb/scylla/commit/4e95b67501c33e3f9ea0b1d2cfbd428a640e494a>
>
> *Description*
> Add support for compacting one or more user defined SSTable similar to
> Cassandra as described here:
>
> https://docs.datastax.com/en/dse/5.1/dse-admin/datastax_enterprise/tools/nodetool/toolsCompact.html
>
> This is particularly helpful when one needs to get rid of the expired data
> but the compactition strategy doesn't do it in the best way for some reason.
>

Duplicate of #4907

**Comment by slivne** [comment] 2020-03-01 10:32
duplicate - transferred the labels

**Closed by slivne** 2020-03-01 10:32 UTC
Labels: Field-Tier2, cassandra 3.x compatibility, compaction, n00b
