### ISSUE TITLE
Feature check failed in rollback from 2.0 to 1.7.5

### ISSUE THREAD

**Issue by amoskong** [scylladb/scylla#2827] opened 2017-09-20 13:25 UTC
*Installation details*
Scylla version (or git commit hash): `scylla-2.0.rc5-0.20170917.0b49cfc.el7.centos.x86_64.rpm` 
 ->`scylla-1.7.5-0.20170918.760af56.el7.centos.x86_64`
Cluster size: 3
OS (RHEL/CentOS/Ubuntu/AWS AMI): CentOS7

*Description*
Rolling upgrade 3 nodes from `scylla-1.7.5-0.20170918.760af56.el7.centos.x86_64` to `scylla-2.0.rc5-0.20170917.0b49cfc.el7.centos.x86_64.rpm` 

`Downgraded node`: {CORRECT_COUNTER_ORDER, COUNTERS, LARGE_PARTITIONS, MATERIALIZED_VIEWS, RANGE_TOMBSTONES}
`Other nodes`: {CORRECT_COUNTER_ORDER, COUNTERS, `INDEXES`, LARGE_PARTITIONS, MATERIALIZED_VIEWS, RANGE_TOMBSTONES, `SCHEMA_TABLES_V3`})

*More details*
[feature_check_failed_in_rollback.txt](https://github.com/scylladb/scylla/files/1317856/feature_check_failed_in_rollback.txt)

```
Sep 20 12:22:21 gce-refresh-1-7-amos2-db-node-d416cce1-0-1 systemd[1]: Started Scylla Server.
Sep 20 12:22:21 gce-refresh-1-7-amos2-db-node-d416cce1-0-1 scylla[4485]:  [shard 0] storage_service - Loading persisted ring state
Sep 20 12:22:21 gce-refresh-1-7-amos2-db-node-d416cce1-0-1 scylla[4485]:  [shard 0] storage_service - load_peer_features: peer_features size=2
Sep 20 12:22:21 gce-refresh-1-7-amos2-db-node-d416cce1-0-1 scylla[4485]:  [shard 0] storage_service - load_peer_features: peer=10.240.0.19, supported_features=RANGE_TOMBSTONES,LARGE_PARTITIONS,COUNTERS,CORRECT_COUNTER_ORDER,SCHEMA_TABLES_V3,MATERIALIZED_VIEWS,INDEXES
Sep 20 12:22:21 gce-refresh-1-7-amos2-db-node-d416cce1-0-1 scylla[4485]:  [shard 0] storage_service - load_peer_features: peer=10.240.0.37, supported_features=RANGE_TOMBSTONES,LARGE_PARTITIONS,COUNTERS,CORRECT_COUNTER_ORDER,SCHEMA_TABLES_V3,MATERIALIZED_VIEWS,INDEXES
Sep 20 12:22:21 gce-refresh-1-7-amos2-db-node-d416cce1-0-1 scylla[4485]:  [shard 0] storage_service - Checking remote features with system table, since this node is the only seed node
Sep 20 12:22:21 gce-refresh-1-7-amos2-db-node-d416cce1-0-1 scylla[4485]:  [shard 0] seastar - Exiting on unhandled exception: std::runtime_error (Feature check failed. This node can not join the cluster because it does not understand the feature. Local node 10.240.0.4 features = {CORRECT_COUNTER_ORDER, COUNTERS, LARGE_PARTITIONS, MATERIALIZED_VIEWS, RANGE_TOMBSTONES}, Remote common_features = {CORRECT_COUNTER_ORDER, COUNTERS, INDEXES, LARGE_PARTITIONS, MATERIALIZED_VIEWS, RANGE_TOMBSTONES, SCHEMA_TABLES_V3})
```

@pdziepak

**Comment by amoskong** [comment] 2017-09-20 13:26
Upgrade and rollback guide/reference doc:
http://docs.scylladb.com/upgrade/upgrade-guide-from-1.7-to-2.0-rpm/

**Comment by tgrabiec** [comment] 2017-09-20 14:58
I think you will need to restore the `system.peers` table on each node from the state right before the upgrade to 2.0.

**Comment by slivne** [comment] 2017-09-20 20:50
@amoskong in the procedure we have
https://github.com/scylladb/scylla-docs/blob/master/upgrade/upgrade-guide-from-1.7-to-2.0-rpm.rst
its clear that you need to restore system tables / system_schema - from the snapshot prior to the upgrade did you do that ?

**Comment by amoskong** [comment] 2017-09-21 00:00
I didn't the restore as the guide mentioned.

The real reason is that I'm try to downgrade scylla when the whole cluster is upgraded from 1.7.5 to 2.0.rc5, it's not allowed.

```
Apply this procedure if an upgrade from 1.7 to 2.0 failed before completing on all nodes. 
```

I just tested to rollback the upgraded nodes (some nodes weren't upgraded), it succeeded.

**Comment by slivne** [comment] 2017-09-25 07:51
closing this is not a bug.

If a user hits this he did not restore the system tables

**Closed by slivne** 2017-09-25 07:51 UTC
Labels: invalid

**Comment by slivne** [comment] 2017-09-25 08:12
- downgrade is not supported
