### ISSUE TITLE
RFE: Support for arithmetic functions 

### ISSUE THREAD

**Issue by dyasny** [scylladb/scylla#5824] opened 2020-02-17 15:36 UTC
This is a request to implement arithmetic functions inside CQL, to match https://issues.apache.org/jira/browse/CASSANDRA-11935

**Comment by ManManson** [comment] 2020-02-17 18:17
Looks like a duplicate of https://github.com/scylladb/scylla/issues/2693.

**Comment by tzach** [comment] 2020-02-17 18:47
> Looks like a duplicate of #2693.

Indeed

**Closed by tzach** 2020-02-17 18:47 UTC
Labels: CQL, cassandra 4.x compatibility, duplicate, enhancement
