### ISSUE TITLE
Several kinds of failures during repair of large dataset

### ISSUE THREAD

**Issue by roydahan** [scylladb/scylla#2413] opened 2017-05-24 17:52 UTC
*Installation details*
Scylla version (or git commit hash): 1.7.0
Cluster size: 4 nodes
OS (RHEL/CentOS/Ubuntu/AWS AMI): AWS AMI

During a longevity-1TB test, while doing a CorruptThenRepair nemesis, several kinds of failures were detected during the entire process.
In this issue I'll describe the chronological order of events and some analysis that I've done.
We may want later to split this issue into several different issues and fix them separately.

Starting point: 4 nodes cluster that has already run about 24 hours with c-s load (pretty low load).

--  Address       Load       Tokens       Owns    Host ID                               Rack
UN  172.30.0.142  1.24 TB    256          ?       8cc0c8d4-7174-4038-8c45-34e7f9b1701e  rack1
UN  172.30.0.15   817.52 GB  256          ?       43305892-d3e6-4b4d-9767-127df1e687e7  rack1
UN  172.30.0.183  1.63 TB    256          ?       144282e7-9be9-4590-9ae3-40b1b2a20c78  rack1
UN  172.30.0.129  898.24 GB  256          ?       316cadb0-1665-4466-86ad-63b318adb168  rack1

Timeline of events:
06:17:30 - A CorruptThenRepair nemesis started and deleted 3 sets of sstables (each with several GB size) - on host 172.30.0.15
06:17:55 - node was restarted as part of the nemesis (172.30.0.15)
06:19:31 - **repair** on this node (172.30.0.15) **started**.
Checksum phase started and ran for several hours.
10:34:40 - **First issue detected** - bad_alloc during checksum phase:

warning|  [shard 0] repair - Failed sync of range (7314401766674809469, 7314403037745711291]: std::bad_alloc (std::bad_alloc)
warning|  [shard 0] repair - Failed sync of range (8996312509972711372, 8996313584984122590]: std::bad_alloc (std::bad_alloc)
... (many more)

After and analysis with Nadav, we think it's caused due to a (becoming) huge vector we are trying to allocate in the memory to hold the list of ranges.
Issue #2412 will handle this failure.

10:47:26 - Starting to get many Checksum failed errors for those ranges:
warning|  [shard 0] repair - Checksum or sync of partial range failed

11:26:25 - Checksum  phase has finished and streaming plan is created:

```
[shard 0] stream_session - [Stream #f4682b60-4048-11e7-b9c3-000000000004] Executing streaming plan for repair-in-1
[shard 0] stream_session - [Stream #f4682b60-4048-11e7-b9c3-000000000004] Starting streaming to 172.30.0.129
[shard 0] stream_session - [Stream #f4682b60-4048-11e7-b9c3-000000000004] Beginning stream session with 172.30.0.129
[shard 0] stream_session - [Stream #f4682b60-4048-11e7-b9c3-000000000004] Starting streaming to 172.30.0.142
 [shard 0] stream_session - [Stream #f4682b60-4048-11e7-b9c3-000000000004] Beginning stream session with 172.30.0.142
 [shard 0] stream_session - [Stream #f4682b60-4048-11e7-b9c3-000000000004] Starting streaming to 172.30.0.183
[shard 0] stream_session - [Stream #f4682b60-4048-11e7-b9c3-000000000004] Beginning stream session with 172.30.0.183
```

**Second issue** - 
From some reason immediately after the streaming started, node 172.30.0.15 think that others nodes are down for several seconds and other nodes thinks this node is down:

Node 172.30.0.15:
```
May 24 11:26:47 ip-172-30-0-15 scylla[63671]:  [shard 0] gossip - InetAddress 172.30.0.129 is now DOWN, status = NORMAL
May 24 11:26:47 ip-172-30-0-15 scylla[63671]:  [shard 0] rpc - client 172.30.0.129: client connection dropped: connection is closed
May 24 11:26:47 ip-172-30-0-15 scylla[63671]:  [shard 0] gossip - InetAddress 172.30.0.183 is now DOWN, status = NORMAL
May 24 11:26:47 ip-172-30-0-15 scylla[63671]:  [shard 0] messaging_service - Retry verb=15 to 172.30.0.129:0, retry=10: rpc::closed_error (connection is closed)
May 24 11:26:47 ip-172-30-0-15 scylla[63671]:  [shard 0] messaging_service - Retry verb=15 to 172.30.0.183:0, retry=10: rpc::closed_error (connection is closed)
May 24 11:26:47 ip-172-30-0-15 scylla[63671]:  [shard 0] gossip - InetAddress 172.30.0.129 is now UP, status = NORMAL
May 24 11:26:47 ip-172-30-0-15 scylla[63671]:  [shard 0] gossip - InetAddress 172.30.0.183 is now UP, status = NORMAL
May 24 11:26:47 ip-172-30-0-15 scylla[63671]:  [shard 0] rpc - client 172.30.0.129: unexpected eof on a server while reading data: expected 1211 got 1148
May 24 11:26:48 ip-172-30-0-15 scylla[63671]:  [shard 0] gossip - do_gossip_to_live_member: Favor newly added node 172.30.0.129
May 24 11:26:49 ip-172-30-0-15 scylla[63671]:  [shard 0] gossip - do_gossip_to_live_member: Favor newly added node 172.30.0.183
```

Node 172.30.0.183:

```
May 24 11:26:43 ip-172-30-0-183 scylla[80789]:  [shard 0] gossip - InetAddress 172.30.0.15 is now DOWN, status = NORMAL
May 24 11:26:47 ip-172-30-0-183 scylla[80789]:  [shard 0] gossip - InetAddress 172.30.0.15 is now UP, status = NORMAL
May 24 11:26:48 ip-172-30-0-183 scylla[80789]:  [shard 0] gossip - do_gossip_to_live_member: Favor newly added node 172.30.0.15
May 24 11:27:24 ip-172-30-0-183 scylla[80789]:  [shard 5] compaction - Compacting [/var/lib/scylla/data/keyspace1/standard1-cae887003fb011e78ad9000000000003/keyspace1-standard1-ka-16021-Data.db:level=0, /var/lib/scylla/data/keyspace1/standard1-cae887003fb011e78ad9
May 24 11:27:48 ip-172-30-0-183 scylla[80789]:  [shard 3] compaction - Compacting [/var/lib/scylla/data/keyspace1/standard1-cae887003fb011e78ad9000000000003/keyspace1-standard1-ka-15977-Data.db:level=0, /var/lib/scylla/data/keyspace1/standard1-cae887003fb011e78ad9
May 24 11:27:49 ip-172-30-0-183 scylla[80789]:  [shard 2] compaction - Compacting [/var/lib/scylla/data/keyspace1/standard1-cae887003fb011e78ad9000000000003/keyspace1-standard1-ka-15948-Data.db:level=0, /var/lib/scylla/data/keyspace1/standard1-cae887003fb011e78ad9
May 24 11:27:49 ip-172-30-0-183 scylla[80789]:  [shard 6] compaction - Compacting [/var/lib/scylla/data/keyspace1/standard1-cae887003fb011e78ad9000000000003/keyspace1-standard1-ka-16008-Data.db:level=0, /var/lib/scylla/data/keyspace1/standard1-cae887003fb011e78ad9
May 24 11:27:52 ip-172-30-0-183 scylla[80789]:  [shard 4] compaction - Compacting [/var/lib/scylla/data/keyspace1/standard1-cae887003fb011e78ad9000000000003/keyspace1-standard1-ka-16006-Data.db:level=0, /var/lib/scylla/data/keyspace1/standard1-cae887003fb011e78ad9
May 24 11:27:53 ip-172-30-0-183 scylla[80789]:  [shard 0] gossip - InetAddress 172.30.0.129 is now DOWN, status = NORMAL
May 24 11:27:58 ip-172-30-0-183 scylla[80789]:  [shard 0] gossip - InetAddress 172.30.0.129 is now UP, status = NORMAL
May 24 11:27:59 ip-172-30-0-183 scylla[80789]:  [shard 0] gossip - do_gossip_to_live_member: Favor newly added node 172.30.0.129

```

Node 172.30.0.142:
```
May 24 11:26:43 ip-172-30-0-142 scylla[55282]:  [shard 0] gossip - InetAddress 172.30.0.15 is now DOWN, status = NORMAL
May 24 11:26:47 ip-172-30-0-142 scylla[55282]:  [shard 0] gossip - InetAddress 172.30.0.15 is now UP, status = NORMAL
May 24 11:26:48 ip-172-30-0-142 scylla[55282]:  [shard 0] gossip - do_gossip_to_live_member: Favor newly added node 172.30.0.15
May 24 11:26:59 ip-172-30-0-142 scylla[55282]:  [shard 8] compaction - Compacting [/var/lib/scylla/data/keyspace1/standard1-cae887003fb011e78ad9000000000003/keyspace1-standard1-ka-8870-Data.db:level=0, /var/lib/scylla/data/keyspace1/standard1-cae887003fb011e78ad90
May 24 11:27:04 ip-172-30-0-142 scylla[55282]:  [shard 4] compaction - Compacting [/var/lib/scylla/data/keyspace1/standard1-cae887003fb011e78ad9000000000003/keyspace1-standard1-ka-8768-Data.db:level=0, /var/lib/scylla/data/keyspace1/standard1-cae887003fb011e78ad90
May 24 11:27:11 ip-172-30-0-142 scylla[55282]:  [shard 12] compaction - Compacted 4 sstables to [/var/lib/scylla/data/keyspace1/standard1-cae887003fb011e78ad9000000000003/keyspace1-standard1-ka-9000-Data.db:level=0, ]. 2667273287 bytes to 2667273287 (~100% of orig
May 24 11:27:17 ip-172-30-0-142 scylla[55282]:  [shard 11] compaction - Compacted 4 sstables to [/var/lib/scylla/data/keyspace1/standard1-cae887003fb011e78ad9000000000003/keyspace1-standard1-ka-8971-Data.db:level=0, ]. 2667272244 bytes to 2667272244 (~100% of orig
May 24 11:27:27 ip-172-30-0-142 scylla[55282]:  [shard 2] compaction - Compacted 4 sstables to [/var/lib/scylla/data/keyspace1/standard1-cae887003fb011e78ad9000000000003/keyspace1-standard1-ka-8864-Data.db:level=0, ]. 2667272244 bytes to 2667272244 (~100% of origi
May 24 11:27:28 ip-172-30-0-142 scylla[55282]:  [shard 0] compaction - Compacted 4 sstables to [/var/lib/scylla/data/keyspace1/standard1-cae887003fb011e78ad9000000000003/keyspace1-standard1-ka-8890-Data.db:level=0, ]. 2667270158 bytes to 2667270158 (~100% of origi
May 24 11:27:43 ip-172-30-0-142 scylla[55282]:  [shard 8] compaction - Compacted 4 sstables to [/var/lib/scylla/data/keyspace1/standard1-cae887003fb011e78ad9000000000003/keyspace1-standard1-ka-8884-Data.db:level=0, ]. 2667272244 bytes to 2667272244 (~100% of origi
May 24 11:27:52 ip-172-30-0-142 scylla[55282]:  [shard 0] gossip - InetAddress 172.30.0.129 is now DOWN, status = NORMAL
May 24 11:27:54 ip-172-30-0-142 scylla[55282]:  [shard 4] compaction - Compacted 4 sstables to [/var/lib/scylla/data/keyspace1/standard1-cae887003fb011e78ad9000000000003/keyspace1-standard1-ka-8810-Data.db:level=0, ]. 2667273287 bytes to 2667273287 (~100% of origi
May 24 11:27:57 ip-172-30-0-142 scylla[55282]:  [shard 0] gossip - InetAddress 172.30.0.129 is now UP, status = NORMAL
May 24 11:27:58 ip-172-30-0-142 scylla[55282]:  [shard 0] gossip - do_gossip_to_live_member: Favor newly added node 172.30.0.129
```

Node 172.30.0.129:
```
May 24 11:26:43 ip-172-30-0-129 scylla[3351]:  [shard 0] gossip - InetAddress 172.30.0.15 is now DOWN, status = NORMAL
May 24 11:26:47 ip-172-30-0-129 scylla[3351]:  [shard 0] rpc - client 172.30.0.15: server connection dropped: connection is closed
May 24 11:26:47 ip-172-30-0-129 scylla[3351]:  [shard 0] gossip - InetAddress 172.30.0.15 is now UP, status = NORMAL
May 24 11:26:47 ip-172-30-0-129 scylla[3351]:  [shard 0] gossip - do_gossip_to_live_member: Favor newly added node 172.30.0.15
May 24 11:27:29 ip-172-30-0-129 scylla[3351]:  [shard 8] stream_session - [Stream #f4682b60-4048-11e7-b9c3-000000000004] Creating new streaming plan for repair-in-1, with 172.30.0.15
May 24 11:27:32 ip-172-30-0-129 scylla[3351]:  [shard 8] stream_session - [Stream #f4682b60-4048-11e7-b9c3-000000000004] Prepare completed with 172.30.0.15. Receiving 0, sending 1
```

Then, it seems like there were some retries but only to one of the nodes (172.30.0.129) and streaming write strated only from this node:

```
2017-05-24 11:26:47,521 remote           L0197 DEBUG| [52.90.35.117] [stdout] May 24 11:26:47 info   |  [shard 0] messaging_service - Retry verb=15 to 172.30.0.129:0, retry=10: rpc::closed_error (connection is closed)
2017-05-24 11:26:47,566 remote           L0197 DEBUG| [52.90.35.117] [stdout] May 24 11:26:47 info   |  [shard 0] messaging_service - Retry verb=15 to 172.30.0.183:0, retry=10: rpc::closed_error (connection is closed)
2017-05-24 11:27:32,539 remote           L0197 DEBUG| [52.90.35.117] [stdout] May 24 11:27:32 info   |  [shard 0] messaging_service - Retry verb=15 to 172.30.0.129:0, retry=9: OK
2017-05-24 11:27:52,575 remote           L0197 DEBUG| [52.90.35.117] [stdout] May 24 11:27:52 info   |  [shard 0] messaging_service - Retry verb=16 to 172.30.0.129:0, retry=10: rpc::closed_error (connection is closed)
2017-05-24 11:28:38,547 remote           L0197 DEBUG| [52.90.35.117] [stdout] May 24 11:28:38 info   |  [shard 0] messaging_service - Retry verb=16 to 172.30.0.129:0, retry=9: OK
2017-05-24 11:36:25,086 remote           L0197 DEBUG| [52.90.35.117] [stdout] May 24 11:36:25 info   |  [shard 0] messaging_service - Retry verb=15 to 172.30.0.142:0, retry=10: timeout in 600 seconds
2017-05-24 11:37:20,046 remote           L0197 DEBUG| [52.90.35.117] [stdout] May 24 11:37:20 info   |  [shard 0] messaging_service - Retry verb=15 to 172.30.0.183:0, retry=9: timeout in 600 seconds
```

12:03:33 - Eventually the streaming from node 172.30.0.129 finished.
```
May 24 12:03:33 ip-172-30-0-15 scylla[63671]:  [shard 0] stream_session - [Stream #f4682b60-4048-11e7-b9c3-000000000004] Session with 172.30.0.129 is complete, state=COMPLETE
May 24 12:03:33 ip-172-30-0-15 scylla[63671]:  [shard 0] stream_session - [Stream #f4682b60-4048-11e7-b9c3-000000000004] bytes_sent = 0, bytes_received = 413508484066, tx_bandwidth = 0.000 MiB/s, rx_bandwidth = 176.985 MiB/s
May 24 12:03:33 ip-172-30-0-15 scylla[63671]:  [shard 0] stream_session - [Stream #f4682b60-4048-11e7-b9c3-000000000004] Stream failed for streaming plan repair-in-1, peers={172.30.0.129, 172.30.0.142, 172.30.0.183}
May 24 12:03:33 ip-172-30-0-15 scylla[63671]:  [shard 0] repair - repair's stream failed: streaming::stream_exception (Stream failed)
May 24 12:03:33 ip-172-30-0-15 scylla[63671]:  [shard 0] repair - repair 1 failed - streaming::stream_exception (Stream failed)
```

But 30 seconds later (related or not), a segmentation fault happened on the sender node (172.30.0.129) and a coredump was issued.

```
May 24 12:04:02 ip-172-30-0-129 scylla[3351]: Segmentation fault on shard 8.
May 24 12:04:02 ip-172-30-0-129 scylla[3351]: Backtrace:
May 24 12:04:02 ip-172-30-0-129 scylla[3351]: 0x00000000004e05fa
May 24 12:04:02 ip-172-30-0-129 scylla[3351]: 0x00000000004e06a3
May 24 12:04:02 ip-172-30-0-129 scylla[3351]: 0x00007f81e5be50ff
May 24 12:04:02 ip-172-30-0-129 scylla[3351]: 0x00000000014aad61
May 24 12:04:02 ip-172-30-0-129 scylla[3351]: 0x00000000014acaab
May 24 12:04:02 ip-172-30-0-129 scylla[3351]: 0x00000000004e206f
May 24 12:04:02 ip-172-30-0-129 scylla[3351]: 0x0000000000531bc2
May 24 12:04:02 ip-172-30-0-129 scylla[3351]: 0x0000000000533400
May 24 12:04:02 ip-172-30-0-129 scylla[3351]: 0x000000000058ed2d
May 24 12:04:02 ip-172-30-0-129 scylla[3351]: 0x00007f81e5bdddc4
May 24 12:04:02 ip-172-30-0-129 scylla[3351]: 0x00007f81e590acec
```

Coredump available in:
scylladb-users-upload.s3.amazonaws.com/core.scylla.994.7264054b8a084c8e9749ab73ada67e3a.3351.1495627442000000.gz/core.scylla.994.7264054b8a084c8e9749ab73ada67e3a.3351.1495627442000000.gz.aa 

(aa to ah)

**Comment by nyh** [comment] 2017-05-25 12:25
There's a lot of data above, there may be several different issues here:
1. Why we failed some allocations (bad_alloc). I think this is #2412, and we didn't really run out of memory, it's a large allocation issue.
2. Why, despite all nodes being up all the time, we got down/up flips in the gossip. Is it possible that high streaming activity is delaying gossip so much that it times out?
3. Why streaming to one node (.129) was successful (although parts of it failed because of the bad_alloc), but streaming with two other nodes simply did not start - the message message started to stream failed 10 times. I don't in the log an explanation why it failed. It says something strange about the connection being closed which I don't understand (or who closed it or why). One wild guess I have is that creating this very long message also failed with bad_alloc, but we don't see any proof for that in the log - is it possible that an exception is causing the message to fail, but is not logged? Could it be that the gossip flipping (the previous item) is causing the messages to fail? 
4. Why the only node to which we successfully streamed (.129) crashed with segfault 30 seconds after the streaming completed. On the one hand this is a many-hour test so 30 seconds doesn't appear to be a coincidence, but on the other hand, what happened during these 30 seconds? The backtrace and core file in Roy's comment above can help figure this out.
5. Why we had a single case of "rpc - client 172.30.0.129: unexpected eof on a server while reading data: expected 1211 got 1148", and is it part of one of the previous issues, or yet another bug?

**Comment by nyh** [comment] 2017-05-29 13:16
Todaywe (me, @roydahan, @gleb-cloudius) made some progress understanding these different failure modes:

1. We thought that streaming is failing to start to some nodes. However, this "start" actually means sending the very long list of ranges to stream to the remote node, in one huge RPC message. In issue #2428 @gleb-cloudius noticed that if the message is larger than some limit, the send will silently timeout because the receiver silently ignores it. This explains point 3 above, but also point 4: If running out of contiguous memory makes us unable to continue enlarging the message we send to a particular node, we'll see bad_alloc messages but this node will receive a smaller message and will be able to do work. If we did not have enough bad_alloc, we build a very large message, and fail to send it at all.

2. The up/down flips in gossip may (we don't have proof for this though) be caused by handling a huge message in one continuation, and missing the gossip timeout.

3. It appears that in addition to the contiguous allocation problem, we also have a problem of completely running out of memory on shard 0 (but not on any other shard), which is the shard which holds all the lists of checksums etc. When that happens we run into issue https://github.com/scylladb/seastar/issues/84 - and can abort() causing a core dump. I still can't explain though why it seems this only happened 30 seconds after streaming failed. Note that `do_streaming()` (repair/repair.cc) only starts sp_out() if sp_in() - so after sp_in failed, we shouldn't have even tried sp_out, so I don't know how to explain that 30 second delay.

**Comment by slivne** [comment] 2018-01-03 15:52
we will rerun this test on 2.1 and check if the issue(s) remain - many of the associated items have been fixed and as such this may have been resolved

**Comment by tzach** [comment] 2018-02-18 11:27
Longevity of +1TB is successful on 2.1

**Closed by tzach** 2018-02-18 11:27 UTC
Labels: bug
