### ISSUE TITLE
Different behavior between scylla 3.0 and master in materialized views load

### ISSUE THREAD

**Issue by eliransin** [scylladb/scylla#4623] opened 2019-06-30 08:07 UTC
We ran the same test (2 materialized views with hinted hand off turned off) and experienced different behavior that we can't account for.
Similarities: 
1. both runs achieved similar throughput and latency, ~4K ops/s.
2. although mv backpressure is the target of the test, it didn't seam to make a difference,
it seams that the real limiter in bot runs was the background writes queue size (which 
forces all writes to become foreground writes).

Differences:
1.  layency:
-- scylla 3.0 version had 99 percentile latency of between 500ms-1s with peeks in 1.5 sec
-- master version had 99 percentile of between 300ms-800ms with peeks in 900ms

2. Foreground writes:
-- scylla 3.0 had its foreground writes queue skyrocket with ~6k in the queue. This is still unexplained and doesn't add up with a simple concurrency calculation we did (taking into account the throughput).
-- master has foreground queue that fits the calculations (~270).
3. Timeouts:
-- scylla 3.0 has timeouts (in the server, not the client) , it measures in a few tens of timeouts per second.
-- master has no timeouts at all.

An explanation is needed for the difference in behavior, IMO especially the foreground writes queue. Then after matching the behavior to the correct one we need to answer the question, are the correct results acceptable.

**Comment by eliransin** [comment] 2019-06-30 08:12
@nyh @slivne this is the issue I opened to the backpressure testing, need your help to see it is clear enough so we can continue handling this.

**Comment by nyh** [comment] 2019-06-30 08:57
@eliransin yes, I think your description is clear enough - thanks for doing the tests and summarizing these results. What is less clear is why this happens :-(

**Comment by slivne** [comment] 2019-07-02 12:49
Ok read this through

1. I hope you have the metrics so we can show gleb when he is back and ask
for advice

2. Its bad ... e.g. 2019.1.X is based on 3.0 and its clear its broken - so
we will need to fix it.

3. One way to find when it started to mess up is todo a bisect a big one
between the AMI's we have collected and then figure out the range that may
have the fix - but lets keep this after we talk with gleb.

**Comment by slivne** [comment] 2019-07-07 09:09
@gleb-cloudius we will need your help / input here

**Comment by eliransin** [comment] 2019-07-07 10:18
@slivne 
>1. I hope you have the metrics so we can show gleb when he is back and ask
>for advice

I kept the monitors :)

**Comment by gleb-cloudius** [comment] 2019-07-14 07:28
On Tue, Jul 02, 2019 at 05:49:22AM -0700, Shlomi Livne wrote:
> 3. One way to find when it started to mess up is todo a bisect a big one
> between the AMI's we have collected and then figure out the range that may
> have the fix - but lets keep this after we talk with gleb.
> 
Gleb is not an expert on materialized code view. Nadav is. I have no
idea what changed between 3.0 and master in that area. Probably delay
calculation function was finally fixed.

--
			Gleb.

**Comment by slivne** [comment] 2019-07-14 07:33
On Sun, Jul 14, 2019 at 10:28 AM Gleb Natapov <notifications@github.com>
wrote:

> On Tue, Jul 02, 2019 at 05:49:22AM -0700, Shlomi Livne wrote:
> > 3. One way to find when it started to mess up is todo a bisect a big one
> > between the AMI's we have collected and then figure out the range that
> may
> > have the fix - but lets keep this after we talk with gleb.
> >
> Gleb is not an expert on materialized code view. Nadav is. I have no
> idea what changed between 3.0 and master in that area. Probably delay
> calculation function was finally fixed.
>

So you are back and as an expert we will share the monitorings with you and
would like to get your insights on what may be happening (we may be
overlooking 1-2 items that you know).

**Comment by gleb-cloudius** [comment] 2019-07-14 07:49
On Sun, Jul 14, 2019 at 12:33:35AM -0700, Shlomi Livne wrote:
> On Sun, Jul 14, 2019 at 10:28 AM Gleb Natapov <notifications@github.com>
> wrote:
> 
> > On Tue, Jul 02, 2019 at 05:49:22AM -0700, Shlomi Livne wrote:
> > > 3. One way to find when it started to mess up is todo a bisect a big one
> > > between the AMI's we have collected and then figure out the range that
> > may
> > > have the fix - but lets keep this after we talk with gleb.
> > >
> > Gleb is not an expert on materialized code view. Nadav is. I have no
> > idea what changed between 3.0 and master in that area. Probably delay
> > calculation function was finally fixed.
> >
> 
> So you are back and as an expert we will share the monitorings with you and
> would like to get your insights on what may be happening (we may be
> overlooking 1-2 items that you know).
> 
I am not an expert in MV code. In fact backpressure there was
implemented not in a way I proposed. I suggest MV expert actually
debugging the code because the problem is easily reproducible. One thing
I would check though before spending time on that is if reverting of
591d2968cc5fafa1618ed9f2779b3007ec7c0a8c makes master behave similarly
to 3.0.




--
			Gleb.

**Comment by eliransin** [comment] 2019-07-23 07:32
> I would check though before spending time on that is if reverting of
591d296 makes master behave similarly

It seams that @gleb-cloudius was spot on :+1: 
Is there a risk in backporting it to 3.0? 
@slivne  Should we?

![image](https://user-images.githubusercontent.com/22260843/61691747-e4339080-ad34-11e9-91a0-3aca9deb4e22.png)

**Comment by eliransin** [comment] 2019-08-15 07:35
@slivne do you want to backport to 3.0?

**Comment by slivne** [comment] 2019-08-15 08:09
Avi's patch is not part of 3.1.0 , it will be included in 3.2.

**Closed by slivne** 2019-08-15 08:09 UTC
Labels: bug, materialized-views
