### ISSUE TITLE
Node stuck in decommission for over 24 hours (50gb-4days)

### ISSUE THREAD

**Issue by ShlomiBalalis** [scylladb/scylla#5450] opened 2019-12-10 10:48 UTC
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [x] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash):`3.2.rc2-0.20191207.2ff26d11608`
Cluster size:6
OS (RHEL/CentOS/Ubuntu/AWS AMI):`ami-0466376b07e8f1ea4` (eu-west-1)
Instance type: i3.4xlarge

Node list:
```
Node longevity-tls-50gb-4d-3-2-db-node-728bd291-1 [54.154.216.84 | 10.0.64.25]
Node longevity-tls-50gb-4d-3-2-db-node-728bd291-2 [34.244.236.214 | 10.0.122.49]
Node longevity-tls-50gb-4d-3-2-db-node-728bd291-3 [34.243.248.218 | 10.0.228.195]
Node longevity-tls-50gb-4d-3-2-db-node-728bd291-4 [3.248.217.150 | 10.0.233.116]
Node longevity-tls-50gb-4d-3-2-db-node-728bd291-5 [34.245.131.65 | 10.0.188.71] 
Node longevity-tls-50gb-4d-3-2-db-node-728bd291-6 [34.254.188.25 | 10.0.103.41]
Node longevity-tls-50gb-4d-3-2-db-node-728bd291-7 [34.250.170.131 | 10.0.15.186]
```
At `2019-12-09 01:11:51,617`, A nodetool decommission nemesis started with the target node being node no.5. According to node 5's log, it indeed started the decommissioning process:
`2019-12-09T01:12:43+00:00  ip-10-0-188-71 !INFO    | scylla: [shard 0] storage_service - LEAVING: streaming hints to other nodes`
Afterwards, the node started streaming its information, but it never actually decommissioned from the cluster, for over 24 hours. **As of now the decommission still has not ended**

Test logs can be found here: scratch.scylladb.com/shlomibalalis/1210_50gb_logs.zip

Test id: 728bd291-4d9d-44c4-805b-bf55c303842c
Grafana snapshot: https://snapshot.raintank.io/dashboard/snapshot/3eqU12yOXkv5DKGqgvfm5wPgQ3ZN7Rmd
Test yaml: https://github.com/scylladb/scylla-cluster-tests/blob/branch-3.2/test-cases/longevity/longevity-50GB-4days-authorization-and-tls-ssl.yaml

**Comment by asias** [comment] 2019-12-11 03:13
@ShlomiBalalis How did you check and conclude the node never never actually decommissioned from the cluster? The log from node5 suggests the decommission was successful.

```
256377 2019-12-09T03:17:18+00:00  ip-10-0-188-71 !INFO    | scylla: [shard 0] range_streamer - Unbootstrap with 10.0.228.195 for keyspace=system_auth succeeded, took 10.264 seconds
256378 2019-12-09T03:17:18+00:00  ip-10-0-188-71 !INFO    | scylla: [shard 0] range_streamer - Unbootstrap succeeded, took 7475 seconds, nr_ranges_remaining=0
256379 2019-12-09T03:17:18+00:00  ip-10-0-188-71 !INFO    | scylla: [shard 0] storage_service - stream_ranges successful
256380 2019-12-09T03:17:18+00:00  ip-10-0-188-71 !INFO    | scylla: [shard 0] gossip - Node 10.0.188.71 will be removed from gossip at [2019-12-12 03:17:18]: (expire = 1576120638344, now = 1575861438354, diff = 259199 seconds)
256381 2019-12-09T03:17:18+00:00  ip-10-0-188-71 !INFO    | scylla: [shard 0] storage_service - Removing tokens {5766509113747438635, -319742877929320796, -3001498779408466083, -3478201722422282068, 3382615669793485341, 4237168044745102816, -363797780270079162, 2963757601415198552,        -4707631910527174247, -7785637616241691954, 8489529152680998961, -6363057644613890483, -2207627839425898162, 4798450774145601522, 8614174661746715587, 8897528778010618715, 5060958081300740766, -7705054519325817835, 6611297725416354431, -4523026659789677764, -192387575481824       402, -6125357599115696608, 1298825441172580886, -3001511926406239349, 1877164437369520156, -6690477121545774893, -1329052684732883442, -224942988708641191, -3188427831796286501, 2128927754660118647, 8592959631472761252, -1729772388753918437, -6224399031513851774, 19776405095       92886455, -3288460095133500849, 2243180007930329804, -5816292890161763220, 5377850717171407230, 1410989557344679874, 6551180032938772778, -3308220481615524356, -5039978835838754671, -7783040059823587778, -3163296445748452583, 583562870506697845, 3733832554884209652, 30093261       007308781, 2539206249488084218, -8516415360133831958, -3993812453723289876, -8969602058633117520, 6301823262638452766, 8087933242705084112, 3824601046731742464, -739352154851120121, 8318340754624532759, -3747307448059697462, 1766791059547765567, -7955641730075757763, -367368       8957108394565, 5955780376159466105, -6244050153172826641, -8668870531912514042, -6177019358234038065, -4293653594543505535, 1893766028927516590, -1867324948925575896, -4217572498250082241, -8355417487387606666, 4948999811637080446, -2794984651738136425, 6457231608320254014,        -1432332838492935733, -7496500360715023661, 8524404830624910401, -1769625251188034177, -2827458142117672170, -242012544237884920, -6408715106282815023, -809431088310559974, -4834348756794959223, -6219926969195233028, 2637795504190838898, 8727243859164785467, 5491620643987324       622, 7282253756080864313, -8458652079778048109, -9132519955699459170, -7243596714241296781, 3929856041908491197, 86336362299837601, -3773930320417233876, 5033769076283749068, -1434624580108996832, 6716225039941447641, -5119693878711468524, 4343832742971785640, 67465077598812       38247, -4754424349808081494, 1161915413136494639, -8121010023944161311, 3836757623739325687, 5089068842904720901, 340501381819709409, 5143387912641271259, 4427587474716895319, 6453462182379901850, -5226285935587828170, 2718779374083770042, -608086329240991298, 76621761530260       77527, 3301966627433700498, -2595302075199277403, -9053450895995561306, 1682399589623323676, 6622425278189321867, 3650735413547864427, 1780664951865221925, -6732516139441179081, -8371955654667241004, -5447465221445076531, 4762713819669959484, 7296779545783367416, -7680211100       203762111, -62751125037984752, -6834994362844502623, -2711140498074163826, 3013518418902432203, -5287910247810821416, 4386571160962273739, 1733113154276599813, -1219146963789828175, 7607440171846549043, 1080406621117801281, 4600379396329197480, 3118586693209776686, -28844875       09898608751, 1809843117831930669, -2396846782284389193, -1514022033434683809, 1109098504934415446, -1463066320925328298, 6429659003887327932, 5684300788488650086, -4693217771520739873, -1283701654198631990, 7963041005164805057, 6968894396263235868, -6534643978799332103, 2744       99701310589258, -5504601420931065309, 798902142699183789, -6735974873605976211, 6594798423599935293, 4241168631929233612, 938975136105176835, 2389781160046278199, -3123025842936183859, -3505856767250098367, 5185380445741869809, -2184336859118902433, 224825307831586139, -1821       393824831407401, 8961210440765213116, -3531082980475435406, -785488055998484884, -2967698427956454369, -1111194106743816542, 3205511275211228676, 3469719729145313612, 5899018462379963856, 8701780536119431792, -7150100879638299091, -3929914745980605510, -3783492918742484427,        9221258883524021089, 8882066328067983355, -3467275927316890788, 8400157401570682738, 4965984259575871332, -2141297947832510597, -2129572088548317837, 930021800838479620, 385707591365911900, 4757699356719391557, 273846901975352253, 6154924621579734381, -1544985979173207781, 2       694254899581510231, -2649595331980382701, 4139309253731484692, 5751648341891756615, 2304057395873197443, 361454447103404086, 7268199192402796612, 2813462540212310932, 5866039237791213452, -363020226191026028, -3788631505071752107, -566135062509097596, -7430679993669150300, -       3640111445335906108, 524041356367409399, 3951498557917637424, -5388492084431514771, 8896968928937488909, -4175786889703149765, -165758700860521853, 5537646739141526589, -4927304881584092147, 1474913975697998654, 960006960967968481, 7175663339894850759, 4491429461265308888, 3       933285752604666032, 7326066585728059160, -2297116541263384312, 6465100395728106321, -7479796595380457587, -5376737901763830588, -6734900893596860516, 466873313744720343, -4052662369308358949, -8516553901830573153, -7633357334752418543, -9040350322886281572, -5309281143667671       297, -1689147248649328972, -5048239252166735129, 3095175115719841836, 2278077072831252671, -4233165024442673070, 3034599694258171886, -2159976780071320678, 8356441477881446322, -8952280532580705589, 1559735248510638030, 2072971557280626980, 5141709973899721138, 8114707591154       590140, -4959592067709311524, -8263694057923586114, 4465171953897377241, -7331529403822969144, 2634925215215186916, -2805605044361571604, 8934988571167299004, -3721541602330495159, -1459338257991184561, 2792618368234103332, -1767140934616333950, 6677479888306062867, -5242160       901040014365, 7417669649939189515, 4620580520771741955, -3463387265708869899} for 10.0.188.71
256382 2019-12-09T03:17:18+00:00  ip-10-0-188-71 !INFO    | scylla: [shard 0] storage_service - Announcing that I have left the ring for 30000ms
256383 2019-12-09T03:17:48+00:00  ip-10-0-188-71 !INFO    | scylla: [shard 0] storage_service - DECOMMISSIONING: unbootstrap done
256384 2019-12-09T03:17:48+00:00  ip-10-0-188-71 !INFO    | scylla: [shard 0] storage_service - Thrift server stopped
256385 2019-12-09T03:17:48+00:00  ip-10-0-188-71 !INFO    | scylla: [shard 0] storage_service - CQL server stopped
256386 2019-12-09T03:17:48+00:00  ip-10-0-188-71 !INFO    | scylla: [shard 0] storage_service - DECOMMISSIONING: shutdown rpc and cql server done
256387 2019-12-09T03:17:48+00:00  ip-10-0-188-71 !INFO    | scylla: [shard 0] storage_service - DECOMMISSIONING: stop batchlog_manager done
256388 2019-12-09T03:17:48+00:00  ip-10-0-188-71 !INFO    | scylla: [shard 0] gossip - My status = LEFT
256389 2019-12-09T03:17:48+00:00  ip-10-0-188-71 !WARNING | scylla: [shard 0] gossip - No local state or state is in silent shutdown, not announcing shutdown
256390 2019-12-09T03:17:48+00:00  ip-10-0-188-71 !INFO    | scylla: [shard 0] gossip - Disable and wait for gossip loop started
256391 2019-12-09T03:17:48+00:00  ip-10-0-188-71 !INFO    | scylla: [shard 0] gossip - Disable and wait for gossip loop finished
256392 2019-12-09T03:17:48+00:00  ip-10-0-188-71 !INFO    | scylla: [shard 0] gossip - Gossip is now stopped
256393 2019-12-09T03:17:48+00:00  ip-10-0-188-71 !INFO    | scylla: [shard 0] storage_service - DECOMMISSIONING: stop_gossiping done
```


Log from other node, e.g., node2 also confirmed the decommission:
```
162608 2019-12-09T03:17:18+00:00  ip-10-0-122-49 !INFO    | scylla: [shard 0] gossip - Node 10.0.188.71 will be removed from gossip at [2019-12-12 03:17:18]: (expire = 1576120638344, now = 1575861438532, diff = 259199 seconds)
162609 2019-12-09T03:17:18+00:00  ip-10-0-122-49 !INFO    | scylla: [shard 0] storage_service - Removing tokens {5766509113747438635, -319742877929320796, -3001498779408466083, -3478201722422282068, 3382615669793485341, 4237168044745102816, -363797780270079162, 2963757601415198552,        -4707631910527174247, -7785637616241691954, 8489529152680998961, -6363057644613890483, -2207627839425898162, 4798450774145601522, 8614174661746715587, 8897528778010618715, 5060958081300740766, -7705054519325817835, 6611297725416354431, -4523026659789677764, -192387575481824       402, -6125357599115696608, 1298825441172580886, -3001511926406239349, 1877164437369520156, -6690477121545774893, -1329052684732883442, -224942988708641191, -3188427831796286501, 2128927754660118647, 8592959631472761252, -1729772388753918437, -6224399031513851774, 19776405095       92886455, -3288460095133500849, 2243180007930329804, -5816292890161763220, 5377850717171407230, 1410989557344679874, 6551180032938772778, -3308220481615524356, -5039978835838754671, -7783040059823587778, -3163296445748452583, 583562870506697845, 3733832554884209652, 30093261       007308781, 2539206249488084218, -8516415360133831958, -3993812453723289876, -8969602058633117520, 6301823262638452766, 8087933242705084112, 3824601046731742464, -739352154851120121, 8318340754624532759, -3747307448059697462, 1766791059547765567, -7955641730075757763, -367368       8957108394565, 5955780376159466105, -6244050153172826641, -8668870531912514042, -6177019358234038065, -4293653594543505535, 1893766028927516590, -1867324948925575896, -4217572498250082241, -8355417487387606666, 4948999811637080446, -2794984651738136425, 6457231608320254014,        -1432332838492935733, -7496500360715023661, 8524404830624910401, -1769625251188034177, -2827458142117672170, -242012544237884920, -6408715106282815023, -809431088310559974, -4834348756794959223, -6219926969195233028, 2637795504190838898, 8727243859164785467, 5491620643987324       622, 7282253756080864313, -8458652079778048109, -9132519955699459170, -7243596714241296781, 3929856041908491197, 86336362299837601, -3773930320417233876, 5033769076283749068, -1434624580108996832, 6716225039941447641, -5119693878711468524, 4343832742971785640, 67465077598812       38247, -4754424349808081494, 1161915413136494639, -8121010023944161311, 3836757623739325687, 5089068842904720901, 340501381819709409, 5143387912641271259, 4427587474716895319, 6453462182379901850, -5226285935587828170, 2718779374083770042, -608086329240991298, 76621761530260       77527, 3301966627433700498, -2595302075199277403, -9053450895995561306, 1682399589623323676, 6622425278189321867, 3650735413547864427, 1780664951865221925, -6732516139441179081, -8371955654667241004, -5447465221445076531, 4762713819669959484, 7296779545783367416, -7680211100       203762111, -62751125037984752, -6834994362844502623, -2711140498074163826, 3013518418902432203, -5287910247810821416, 4386571160962273739, 1733113154276599813, -1219146963789828175, 7607440171846549043, 1080406621117801281, 4600379396329197480, 3118586693209776686, -28844875       09898608751, 1809843117831930669, -2396846782284389193, -1514022033434683809, 1109098504934415446, -1463066320925328298, 6429659003887327932, 5684300788488650086, -4693217771520739873, -1283701654198631990, 7963041005164805057, 6968894396263235868, -6534643978799332103, 2744       99701310589258, -5504601420931065309, 798902142699183789, -6735974873605976211, 6594798423599935293, 4241168631929233612, 938975136105176835, 2389781160046278199, -3123025842936183859, -3505856767250098367, 5185380445741869809, -2184336859118902433, 224825307831586139, -1821       393824831407401, 8961210440765213116, -3531082980475435406, -785488055998484884, -2967698427956454369, -1111194106743816542, 3205511275211228676, 3469719729145313612, 5899018462379963856, 8701780536119431792, -7150100879638299091, -3929914745980605510, -3783492918742484427,        9221258883524021089, 8882066328067983355, -3467275927316890788, 8400157401570682738, 4965984259575871332, -2141297947832510597, -2129572088548317837, 930021800838479620, 385707591365911900, 4757699356719391557, 273846901975352253, 6154924621579734381, -1544985979173207781, 2       694254899581510231, -2649595331980382701, 4139309253731484692, 5751648341891756615, 2304057395873197443, 361454447103404086, 7268199192402796612, 2813462540212310932, 5866039237791213452, -363020226191026028, -3788631505071752107, -566135062509097596, -7430679993669150300, -       3640111445335906108, 524041356367409399, 3951498557917637424, -5388492084431514771, 8896968928937488909, -4175786889703149765, -165758700860521853, 5537646739141526589, -4927304881584092147, 1474913975697998654, 960006960967968481, 7175663339894850759, 4491429461265308888, 3       933285752604666032, 7326066585728059160, -2297116541263384312, 6465100395728106321, -7479796595380457587, -5376737901763830588, -6734900893596860516, 466873313744720343, -4052662369308358949, -8516553901830573153, -7633357334752418543, -9040350322886281572, -5309281143667671       297, -1689147248649328972, -5048239252166735129, 3095175115719841836, 2278077072831252671, -4233165024442673070, 3034599694258171886, -2159976780071320678, 8356441477881446322, -8952280532580705589, 1559735248510638030, 2072971557280626980, 5141709973899721138, 8114707591154       590140, -4959592067709311524, -8263694057923586114, 4465171953897377241, -7331529403822969144, 2634925215215186916, -2805605044361571604, 8934988571167299004, -3721541602330495159, -1459338257991184561, 2792618368234103332, -1767140934616333950, 6677479888306062867, -5242160       901040014365, 7417669649939189515, 4620580520771741955, -3463387265708869899} for 10.0.188.71
162611 2019-12-09T03:18:41+00:00  ip-10-0-122-49 !INFO    | scylla: [shard 0] gossip - InetAddress 10.0.188.71 is now DOWN, status = LEFT

```

**Comment by ShlomiBalalis** [comment] 2019-12-11 10:26
@asias You're right, it's seems that the problem is on the nodetool side. It seems that the decommission itself was successful, but the nodetool decommission command never ended until `2019-12-10 18:31:43,743` when it ended with with exit code -1 (I see no stderr to explain the failure)

**Comment by slivne** [comment] 2019-12-11 11:36
@asias can you find why nodetool returned an error although decomission seems to have succeeded

**Comment by asias** [comment] 2019-12-12 01:27
OK. I know what is going on. We stuck at stopping messaging_service! We saw the log at line 2432 but we never saw log of line 2434.

@bhalevy, IIRC, you are working on this area. 

```
2431             gms::stop_gossiping().get();
2432             slogger.info("DECOMMISSIONING: stop_gossiping done");
2433             ss.do_stop_ms().get();
2434             slogger.info("DECOMMISSIONING: stop messaging_service done");
2435             // StageManager.shutdownNow();
2436             db::system_keyspace::set_bootstrap_state(db::system_keyspace::bootstrap_state::DECOMMISSIONED).get();
2437             slogger.info("DECOMMISSIONING: set_bootstrap_state done");
2438             ss.set_mode(mode::DECOMMISSIONED, true);
2439             slogger.info("DECOMMISSIONING: done");
2440             // let op be responsible for killing the process
```

**Comment by bhalevy** [comment] 2019-12-12 09:28
> @bhalevy, IIRC, you are working on this area.

@xemul is working on this area now

**Comment by slivne** [comment] 2019-12-12 09:35
@Benny Halevy <bhalevy@scylladb.com> / @Avi Kivity <avi@scylladb.com> - are
we going to backport the shutdown boot/shutdow changes to 3.2 - the issue
is on 3.2 - if we have a half backed solution in 3.2 maybe the correct
solution is to revert it.

**Comment by slivne** [comment] 2019-12-15 11:47
QA have run multiple tests with decommission

Currently 3 out of 3 runs have passed - we will continue to run and update.

**Comment by bhalevy** [comment] 2019-12-29 08:42
ping @roydahan is this issue still open or can be close since it cannot be reproduced?

**Comment by roydahan** [comment] 2019-12-29 09:11
I don’t think we have a clear answer.
@ShlomiBalalis please rerun the decommissioning only test and make sure the test is not “stuck” on cleanup.
We saw that cleanup phase can take a long time.

**Comment by ShlomiBalalis** [comment] 2020-01-01 13:54
In the rerun, two of the decommission command failed:
In the first failure, it seems that there was no issue when stopping the messaging service. In fact, from the node's log it's seems that the decommission was successful:
```
2019-12-31T15:33:04+00:00  ip-10-0-229-73 !INFO    | scylla: [shard 0] storage_service - DECOMMISSIONING: starts
2019-12-31T15:33:35+00:00  ip-10-0-229-73 !INFO    | scylla: [shard 0] storage_service - DECOMMISSIONING: unbootstrap starts
2019-12-31T16:42:00+00:00  ip-10-0-229-73 !INFO    | scylla: [shard 0] storage_service - DECOMMISSIONING: unbootstrap done
2019-12-31T16:42:00+00:00  ip-10-0-229-73 !INFO    | scylla: [shard 0] storage_service - DECOMMISSIONING: shutdown rpc and cql server done
2019-12-31T16:42:00+00:00  ip-10-0-229-73 !INFO    | scylla: [shard 0] storage_service - DECOMMISSIONING: stop batchlog_manager done
2019-12-31T16:42:00+00:00  ip-10-0-229-73 !INFO    | scylla: [shard 0] storage_service - DECOMMISSIONING: stop_gossiping done
2019-12-31T16:42:00+00:00  ip-10-0-229-73 !INFO    | scylla: [shard 0] storage_service - DECOMMISSIONING: stop messaging_service done
2019-12-31T16:42:00+00:00  ip-10-0-229-73 !INFO    | scylla: [shard 0] storage_service - DECOMMISSIONING: set_bootstrap_state done
2019-12-31T16:42:00+00:00  ip-10-0-229-73 !INFO    | scylla: [shard 0] storage_service - DECOMMISSIONED:
2019-12-31T16:42:00+00:00  ip-10-0-229-73 !INFO    | scylla: [shard 0] storage_service - DECOMMISSIONING: done
```
But, the command still failed with error code -1 and no stderr:
```
2019-12-31 16:32:06,193
Traceback (most recent call last):
  File "/sct/sdcm/nemesis.py", line 1179, in wrapper
    result = method(*args, **kwargs)
  File "/sct/sdcm/nemesis.py", line 1313, in disrupt
    self.disrupt_nodetool_decommission()
  File "/sct/sdcm/nemesis.py", line 426, in disrupt_nodetool_decommission
    self.target_node.run_nodetool("decommission")
  File "/sct/sdcm/cluster.py", line 2194, in run_nodetool
    result = self.remoter.run(cmd, ignore_status=ignore_status, verbose=verbose)
  File "/sct/sdcm/remote.py", line 254, in run
    result = _run()
  File "/sct/sdcm/utils/common.py", line 88, in inner
    return func(*args, **kwargs)
  File "/sct/sdcm/remote.py", line 241, in _run
    watchers=watchers, timeout=timeout)
  File "<decorator-gen-3>", line 2, in run
  File "/usr/lib/python2.7/site-packages/fabric/connection.py", line 30, in opens
    return method(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/fabric/connection.py", line 721, in run
    return self._run(self._remote_runner(), command, **kwargs)
  File "/usr/lib/python2.7/site-packages/invoke/context.py", line 101, in _run
    return runner.run(command, **kwargs)
  File "/usr/lib/python2.7/site-packages/invoke/runners.py", line 291, in run
    return self._run_body(command, **kwargs)
  File "/usr/lib/python2.7/site-packages/invoke/runners.py", line 442, in _run_body
    raise UnexpectedExit(result)
UnexpectedExit: Encountered a bad command exit code!

Command: 'nodetool -u cassandra -pw cassandra  decommission '

Exit code: -1

Stdout:



Stderr:



```

In the later failure, it looks like the messaging service issue occurs again. The node containted only the following messages:
```
2019-12-31T17:03:09+00:00  ip-10-0-102-93 !INFO    | scylla: [shard 0] storage_service - DECOMMISSIONING: starts
2019-12-31T17:03:40+00:00  ip-10-0-102-93 !INFO    | scylla: [shard 0] storage_service - DECOMMISSIONING: unbootstrap starts
2019-12-31T18:54:27+00:00  ip-10-0-102-93 !INFO    | scylla: [shard 0] storage_service - DECOMMISSIONING: unbootstrap done
2019-12-31T18:54:27+00:00  ip-10-0-102-93 !INFO    | scylla: [shard 0] storage_service - DECOMMISSIONING: shutdown rpc and cql server done
2019-12-31T18:54:27+00:00  ip-10-0-102-93 !INFO    | scylla: [shard 0] storage_service - DECOMMISSIONING: stop batchlog_manager done
2019-12-31T18:54:27+00:00  ip-10-0-102-93 !INFO    | scylla: [shard 0] storage_service - DECOMMISSIONING: stop_gossiping done
```

Afterwards, the decommission command failed again:
```
Traceback (most recent call last):
  File "/sct/sdcm/nemesis.py", line 1179, in wrapper
    result = method(*args, **kwargs)
  File "/sct/sdcm/nemesis.py", line 1313, in disrupt
    self.disrupt_nodetool_decommission()
  File "/sct/sdcm/nemesis.py", line 426, in disrupt_nodetool_decommission
    self.target_node.run_nodetool("decommission")
  File "/sct/sdcm/cluster.py", line 2194, in run_nodetool
    result = self.remoter.run(cmd, ignore_status=ignore_status, verbose=verbose)
  File "/sct/sdcm/remote.py", line 254, in run
    result = _run()
  File "/sct/sdcm/utils/common.py", line 88, in inner
    return func(*args, **kwargs)
  File "/sct/sdcm/remote.py", line 241, in _run
    watchers=watchers, timeout=timeout)
  File "<decorator-gen-3>", line 2, in run
  File "/usr/lib/python2.7/site-packages/fabric/connection.py", line 30, in opens
    return method(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/fabric/connection.py", line 721, in run
    return self._run(self._remote_runner(), command, **kwargs)
  File "/usr/lib/python2.7/site-packages/invoke/context.py", line 101, in _run
    return runner.run(command, **kwargs)
  File "/usr/lib/python2.7/site-packages/invoke/runners.py", line 291, in run
    return self._run_body(command, **kwargs)
  File "/usr/lib/python2.7/site-packages/invoke/runners.py", line 442, in _run_body
    raise UnexpectedExit(result)
UnexpectedExit: Encountered a bad command exit code!

Command: 'nodetool -u cassandra -pw cassandra  decommission '

Exit code: -1

Stdout:



Stderr:



```

So it seems that the decommission was again stuck in the process of stopping the messaging_service, and issue reoccurred

Scylla version (or git commit hash):3.2.rc3-0.20191215.39b17be5620
Cluster size:6
OS (RHEL/CentOS/Ubuntu/AWS AMI):ami-0cab4c6eceb3249ac (eu-west-1)
Instance type: i3.4xlarge

node list:
```
longevity-tls-50gb-4d-branch3--db-node-1026e3a4-1 [34.242.185.185 | 10.0.103.88] 
longevity-tls-50gb-4d-branch3--db-node-1026e3a4-2 [63.32.91.135 | 10.0.103.201]
longevity-tls-50gb-4d-branch3--db-node-1026e3a4-3 [52.31.113.165 | 10.0.229.73]
longevity-tls-50gb-4d-branch3--db-node-1026e3a4-4 [54.171.150.181 | 10.0.118.166]
longevity-tls-50gb-4d-branch3--db-node-1026e3a4-5 [34.253.200.215 | 10.0.45.9]
longevity-tls-50gb-4d-branch3--db-node-1026e3a4-6 [54.171.6.191 | 10.0.121.126]
longevity-tls-50gb-4d-branch3--db-node-1026e3a4-7 [34.244.36.49 | 10.0.102.93]
longevity-tls-50gb-4d-branch3--db-node-1026e3a4-8 [34.245.144.216 | 10.0.176.122]
longevity-tls-50gb-4d-branch3--db-node-1026e3a4-9 [34.254.89.201 | 10.0.22.148]
```
db logs: https://cloudius-jenkins-test.s3.amazonaws.com/1026e3a4-c92c-4824-b76c-5372a5d4a16c/20200101_045144/db-cluster-1026e3a4.zip
monitor metrics: https://cloudius-jenkins-test.s3.amazonaws.com/1026e3a4-c92c-4824-b76c-5372a5d4a16c/20200101_045144/monitor-set-1026e3a4.zip
monitor: http://63.35.202.172:3000/

**Comment by roydahan** [comment] 2020-01-07 12:29
@slivne / @bhalevy / @xemul the cluster is still up, does anyone need it?
If not we will terminate it.

**Comment by ShlomiBalalis** [comment] 2020-01-07 12:32
@xemul Do you need the new cluster? I'd like to kill the instances if possible

**Comment by xemul** [comment] 2020-01-07 12:33
If it can wait till tomorrow, I'd look at it. If there's a reproducer
(afaiu there is one), then you can destroy it.

Thanks!

вт, 7 янв. 2020 г., 15:29 Roy Dahan <notifications@github.com>:

**Comment by avikivity** [comment] 2020-01-07 12:43
So, the cluster was kept alive for 6 days?

**Comment by roydahan** [comment] 2020-01-07 23:23
Yes :(

**Comment by xemul** [comment] 2020-01-08 10:01
@roydahan , in case you haven't yet killed the cluster. Can you generate a coredump from the stuck scylla instance? I only need the coredump.

**Comment by xemul** [comment] 2020-01-09 12:56
The core is lost :(
1. echo coredumpfile > /proc/sys/kernel/core_pattern
2. ulimit -c unlimited
3. kill -QUIT <pid-of-scylla>
the process is dead, but no core files out there.

**Comment by slivne** [comment] 2020-01-09 13:03
@Shlomi Balalis <balalis@scylladb.com> / @Roy Dahan <roy@scylladb.com>
lets reproduce this again and get Pavel access when that happens.

**Comment by slivne** [comment] 2020-01-09 15:06
@Pavel Emelyanov <xemul@scylladb.com> please note the ami that is used on
AWS is setup to record coredumps - there is no need to mess with the
settings (the coredump is written to a disk that has enough disk space ...
etc.).

you can send a sigabrt and you will get a coredump

**Comment by xemul** [comment] 2020-01-09 15:10
@slivne , ok, will try with existing setup. Last time I did it the core was truncated by abrtd, this experience made me nervous this time when I got to this node.

**Comment by slivne** [comment] 2020-01-09 16:29
On Thu, Jan 9, 2020 at 5:10 PM Pavel Emelyanov <notifications@github.com>
wrote:

> @slivne <https://github.com/slivne> , ok, will try with existing setup.
> Last time I did it the core was truncated by abrtd, this experience made me
> nervous this time when I got to this node.
>
I can understand why it doesn't work - on centos we force users to remove
it (so we work around that).

cat dist/redhat/scylla.spec.mustache | grep abrt
Conflicts:      abrt

**Comment by ShlomiBalalis** [comment] 2020-01-13 08:17
@slivne @xemul It seems that the issue can't be reproduced

**Comment by xemul** [comment] 2020-01-13 08:23
If it can be of any help.

Last time I tried to get cores from cluster I noticed, that 3 or 4 nodes (out of 9) were not accessible via the network (I tried to ssh on them with connection-timeout error, and when I got to the 7th for coredump ping on local addresses didn't received pongs). The 7th node was stuck shutting down messaging service, which includes shutting down RPC-s, if in turn this implies receiving any ACKs from the peers, then the cause of the hang is networking.

**Comment by slivne** [comment] 2020-02-09 11:16
closing this issue - since we had a lot of work on shutdown - if this reproduces open a new issue

**Closed by slivne** 2020-02-09 11:16 UTC
Labels: bug, longevity

**Comment by ShlomiBalalis** [comment] 2020-03-15 15:47
@slivne I was to recreate the issue with version `666.development-0.20200128.b06b34478ed`, is it relevant to the issue?

**Comment by slivne** [comment] 2020-03-15 17:55
Version 20200128 is ~1.5 month old we had a lot of updates since then - you can kill the env.
