### ISSUE TITLE
scylla_ami_setup: data disk isn't detected

### ISSUE THREAD

**Issue by amoskong** [scylladb/scylla#3682] opened 2018-08-09 23:25 UTC
*Installation details*
Scylla version (or git commit hash): 2.3.rc1-0.20180809.e4d6577ef
Cluster size: 1
OS (RHEL/CentOS/Ubuntu/AWS AMI): scylla_2018-08-09T13-18-17Z (ami-0093efe46c277ee4f)
AWS instance type: c4.large

* Description
I created an instance with latest 2.3 AMI, the scylla-server isn't started. In scylla-ami-setup log, the second disk isn't detected.

When I try to setup by executing `sudo scylla_setup`, the disk can be detected, it's mounted correctly. Then the scylla-server can be started correctly.

```
Aug 09 22:42:28 ip-172-30-0-155.ec2.internal scylla_ami_setup[1282]: Waiting for cloud-init to finish...
Aug 09 22:42:28 ip-172-30-0-155.ec2.internal scylla_ami_setup[1282]: [INFO] No userdata found. Starting 1 node clusters, by default.
Aug 09 22:42:28 ip-172-30-0-155.ec2.internal scylla_ami_setup[1282]: [INFO] Using instance type: c4.large
Aug 09 22:42:28 ip-172-30-0-155.ec2.internal scylla_ami_setup[1282]: [INFO] meta-data:instance-type: c4.large
Aug 09 22:42:28 ip-172-30-0-155.ec2.internal scylla_ami_setup[1282]: [INFO] meta-data:local-ipv4: 172.30.0.155
Aug 09 22:42:28 ip-172-30-0-155.ec2.internal scylla_ami_setup[1282]: [INFO] meta-data:public-hostname: ec2-34-201-250-49.compute-1.amazonaws.com
Aug 09 22:42:28 ip-172-30-0-155.ec2.internal scylla_ami_setup[1282]: [INFO] meta-data:ami-launch-index: 0
Aug 09 22:42:28 ip-172-30-0-155.ec2.internal scylla_ami_setup[1282]: [INFO] meta-data:reservation-id: r-0aac52816875efdcd
Aug 09 22:42:28 ip-172-30-0-155.ec2.internal scylla_ami_setup[1282]: [INFO] Using cluster name: Test Cluster - No AMI Parameters
Aug 09 22:42:28 ip-172-30-0-155.ec2.internal scylla_ami_setup[1282]: [INFO] Using cluster size: 1
Aug 09 22:42:28 ip-172-30-0-155.ec2.internal scylla_ami_setup[1282]: [INFO] Using seed indexes: [0, 1, 1]
Aug 09 22:42:28 ip-172-30-0-155.ec2.internal scylla_ami_setup[1282]: [INFO] Reflector loop...
Aug 09 22:42:28 ip-172-30-0-155.ec2.internal scylla_ami_setup[1282]: [INFO] 08/09/18-22:42:28 Reflector: Received 1 of 1 responses from: [u'172.30.0.155']
Aug 09 22:42:28 ip-172-30-0-155.ec2.internal scylla_ami_setup[1282]: [INFO] scylla.yaml configured.
Aug 09 22:42:28 ip-172-30-0-155.ec2.internal scylla_ami_setup[1282]: No disks found
Aug 09 22:42:28 ip-172-30-0-155.ec2.internal systemd[1]: Reloading.
Aug 09 22:42:28 ip-172-30-0-155.ec2.internal scylla_ami_setup[1282]: kernel.core_pattern = |/usr/lib/systemd/systemd-coredump %p %u %g %s %t %e"
Aug 09 22:42:28 ip-172-30-0-155.ec2.internal systemd[1]: Started Scylla AMI Setup.
Aug 09 22:42:28 ip-172-30-0-155.ec2.internal systemd[1]: Starting Scylla Server...
Aug 09 22:42:29 ip-172-30-0-155.ec2.internal scylla_prepare[1560]: ERROR: Bad configuration mode (sq_split) and cpu-mask value (0x00000003): this results in a zero-mask for compute. You
r system can't be tuned until the issue is fixed.
Aug 09 22:42:29 ip-172-30-0-155.ec2.internal systemd[1]: Stopping irqbalance daemon...
Aug 09 22:42:29 ip-172-30-0-155.ec2.internal systemd[1]: Started irqbalance daemon.
Aug 09 22:42:29 ip-172-30-0-155.ec2.internal systemd[1]: Starting irqbalance daemon...
Aug 09 22:42:29 ip-172-30-0-155.ec2.internal scylla_prepare[1560]: Saving the original irqbalance configuration is in /etc/sysconfig/irqbalance.scylla.orig
Aug 09 22:42:29 ip-172-30-0-155.ec2.internal scylla_prepare[1560]: Restarting irqbalance: going to ban the following IRQ numbers: 63, 64 ...
Aug 09 22:42:29 ip-172-30-0-155.ec2.internal scylla_prepare[1560]: Restarting irqbalance via systemctl...
Aug 09 22:42:29 ip-172-30-0-155.ec2.internal scylla_prepare[1560]: Setting a physical interface eth0...
Aug 09 22:42:29 ip-172-30-0-155.ec2.internal scylla_prepare[1560]: Distributing all IRQs
Aug 09 22:42:29 ip-172-30-0-155.ec2.internal scylla_prepare[1560]: Setting mask 00000001 in /proc/irq/63/smp_affinity
Aug 09 22:42:29 ip-172-30-0-155.ec2.internal scylla_prepare[1560]: Setting mask 00000002 in /proc/irq/64/smp_affinity
Aug 09 22:42:29 ip-172-30-0-155.ec2.internal scylla_prepare[1560]: Setting mask 00000003 in /sys/class/net/eth0/queues/rx-1/rps_cpus
Aug 09 22:42:29 ip-172-30-0-155.ec2.internal scylla_prepare[1560]: Setting mask 00000003 in /sys/class/net/eth0/queues/rx-0/rps_cpus
Aug 09 22:42:29 ip-172-30-0-155.ec2.internal scylla_prepare[1560]: Setting net.core.rps_sock_flow_entries to 32768
Aug 09 22:42:29 ip-172-30-0-155.ec2.internal scylla_prepare[1560]: Setting limit 16384 in /sys/class/net/eth0/queues/rx-1/rps_flow_cnt
Aug 09 22:42:29 ip-172-30-0-155.ec2.internal scylla_prepare[1560]: Setting limit 16384 in /sys/class/net/eth0/queues/rx-0/rps_flow_cnt
Aug 09 22:42:29 ip-172-30-0-155.ec2.internal scylla_prepare[1560]: Trying to enable ntuple filtering HW offload for eth0...not supported
Aug 09 22:42:29 ip-172-30-0-155.ec2.internal scylla_prepare[1560]: Setting mask 00000001 in /sys/class/net/eth0/queues/tx-0/xps_cpus
Aug 09 22:42:29 ip-172-30-0-155.ec2.internal scylla_prepare[1560]: Setting mask 00000002 in /sys/class/net/eth0/queues/tx-1/xps_cpus
Aug 09 22:42:29 ip-172-30-0-155.ec2.internal scylla_prepare[1560]: Writing '4096' to /proc/sys/net/core/somaxconn
Aug 09 22:42:29 ip-172-30-0-155.ec2.internal scylla_prepare[1560]: Writing '4096' to /proc/sys/net/ipv4/tcp_max_syn_backlog
Aug 09 22:42:29 ip-172-30-0-155.ec2.internal scylla_prepare[1560]: tuning /sys/devices/vbd-768/block/xvda/xvda1
Aug 09 22:42:29 ip-172-30-0-155.ec2.internal scylla_prepare[1560]: tuning /sys/devices/vbd-768/block/xvda
Aug 09 22:42:29 ip-172-30-0-155.ec2.internal scylla_prepare[1560]: tuning: /sys/devices/vbd-768/block/xvda/queue/scheduler noop
Aug 09 22:42:29 ip-172-30-0-155.ec2.internal scylla_prepare[1560]: tuning: /sys/devices/vbd-768/block/xvda/queue/nomerges 2
Aug 09 22:42:29 ip-172-30-0-155.ec2.internal scylla_prepare[1560]: tuning /sys/devices/vbd-768/block/xvda/xvda1
Aug 09 22:42:29 ip-172-30-0-155.ec2.internal scylla[1596]: Scylla version 2.3.rc1-0.20180809.e4d6577ef starting ...
Aug 09 22:42:29 ip-172-30-0-155.ec2.internal scylla[1596]:  [shard 0] snitch_logger - Ec2Snitch using region: us-east, zone: 1b.
Aug 09 22:42:29 ip-172-30-0-155.ec2.internal scylla[1596]:  [shard 0] init - Scylla API server listening on 127.0.0.1:10000 ...
Aug 09 22:42:30 ip-172-30-0-155.ec2.internal scylla[1596]:  [shard 0] database - Row: max_vector_size: 32, internal_count: 5
Aug 09 22:42:30 ip-172-30-0-155.ec2.internal scylla[1596]:  [shard 1] database - Row: max_vector_size: 32, internal_count: 5
Aug 09 22:42:30 ip-172-30-0-155.ec2.internal scylla[1596]:  [shard 0] init - I/O Scheduler is not properly configured! This is a non-supported setup, and performance is expected to be unpredictably bad.
                                                            Reason found: none of --max-io-requests, --io-properties and --io-properties-file are set.
                                                           To properly configure the I/O Scheduler, run the scylla_io_setup utility shipped with Scylla.
                                                           To ignore this, see the developer_mode configuration option.
Aug 09 22:42:30 ip-172-30-0-155.ec2.internal scylla[1596]:  [shard 0] seastar - Exiting on unhandled exception: std::runtime_error (Bad I/O Scheduler configuration)
Aug 09 22:42:30 ip-172-30-0-155.ec2.internal scylla[1596]:  [shard 0] compaction_manager - Asked to stop
Aug 09 22:42:30 ip-172-30-0-155.ec2.internal scylla[1596]:  [shard 0] compaction_manager - Stopped
Aug 09 22:42:30 ip-172-30-0-155.ec2.internal scylla[1596]:  [shard 1] compaction_manager - Asked to stop
Aug 09 22:42:30 ip-172-30-0-155.ec2.internal scylla[1596]:  [shard 1] compaction_manager - Stopped
Aug 09 22:42:30 ip-172-30-0-155.ec2.internal systemd[1]: scylla-server.service: main process exited, code=exited, status=1/FAILURE
Aug 09 22:42:30 ip-172-30-0-155.ec2.internal systemd[1]: Failed to start Scylla Server.
```

```
[centos@ip-172-30-0-155 ~]$ sudo fdisk -l

Disk /dev/xvda: 10.7 GB, 10737418240 bytes, 20971520 sectors
Units = sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disk label type: dos
Disk identifier: 0x000b0301

    Device Boot      Start         End      Blocks   Id  System
/dev/xvda1   *        2048    20971486    10484719+  83  Linux

Disk /dev/xvdb: 8589 MB, 8589934592 bytes, 16777216 sectors
Units = sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
```

```
# sudo scylla_setup
...

Do you want to setup RAID0 and XFS?
It is recommended to use RAID0 and XFS for Scylla data. If you select yes, you will be prompted to choose the unmounted disks to use for Scylla data. Selected disks are formatted as part of the process.
Yes - choose a disk/disks to format and setup for RAID0 and XFS. No - skip this step.
[YES/no]
Are you sure you want to setup RAID0 and XFS?
If you choose Yes, the selected drive will be reformated, erasing all existing data in the process.
[YES/no]
Please select unmounted disks from the following list: ['/dev/xvdb']
type 'cancel' to cancel RAID/XFS setup.
type 'done' to finish selection. Selected: []
>  /dev/xvdb
Creating XFS volume for scylla using 1 disk(s): /dev/xvdb
meta-data=/dev/xvdb              isize=512    agcount=4, agsize=524288 blks
         =                       sectsz=512   attr=2, projid32bit=1
         =                       crc=1        finobt=0, sparse=0
data     =                       bsize=4096   blocks=2097152, imaxpct=25
         =                       sunit=0      swidth=0 blks
naming   =version 2              bsize=4096   ascii-ci=0 ftype=1
log      =internal log           bsize=4096   blocks=2560, version=2
         =                       sectsz=512   sunit=0 blks, lazy-count=1
realtime =none                   extsz=4096   blocks=0, rtextents=0
Do you want to enable coredumps?
Yes - sets up coredump to allow a post-mortem analysis of the Scylla state just prior to a crash. No - skips this step.
[YES/no]
```

**Comment by syuu1228** [comment] 2018-08-11 00:57
@amoskong I think this is not happening accidentally, @glommer change default role of EBS as unused for a reason.
https://github.com/scylladb/scylla-ami/commit/e0b35dc1fac57fcf1cc027ccd91693a29fbcc7ae

**Comment by glommer** [comment] 2018-08-11 02:52
Most of our users were attaching EBS devices for i3 instances, that were not intended for use with Scylla.
(to take a backup, or something like that).

The defaults were causing the i3 AMIs to try to use those disks and creating more pain that remedies.
We should, for our tests, manually set the things we need .

**Comment by syuu1228** [comment] 2018-08-11 05:16
@amoskong so I think this issue can close.
Note that on your test you can specify ebs role by userdata: https://github.com/scylladb/scylla-ami/blob/master/ds2_configure.py#L179

**Comment by tzach** [comment] 2018-08-12 07:39
Closing, a feature not a bug.
Still, we need to document this, letting the user know what they need to do to attach EBS correctly to AMI.
@glommer  @amoskong can you suggest wording for this?

**Closed by tzach** 2018-08-12 07:39 UTC

**Comment by amoskong** [comment] 2018-08-13 07:31
I know this feature now, thanks.

Doc suggestion:
EBS devices won't be used for Scylla data by default on i3 instances, you can enable it by ec2-user-data:  `--ebs-role data`

**Comment by glommer** [comment] 2018-08-13 15:04
That's a bad wording, @amoskong , although it's better than nothing.

`-ebs-role data` will add the EBS device as the data directory, but maybe that's not what the user wants whey they want to "use" the EBS device.

We should provide a full explanation about what the possible values of `-ebs-role` and `-ephemeral-role`
