### ISSUE TITLE
nodetool error logs

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#732] opened 2015-12-30 09:41 UTC
I see the following print to screen when running `nodetool status`
Other than that, the command do works. 
I do not see it on other servers with the same version (0.13.2)

```
$ nodetool status
09:38:30,273 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-tools.xml]
09:38:30,273 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback.groovy]
09:38:30,273 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]
09:38:30,276 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback.xml] at [file:/tmp/tmp.6T246IVl90/logback.xml]
09:38:30,488 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - debug attribute not set
09:38:30,496 |-INFO in ReconfigureOnChangeFilter{invocationCounter=0} - Will scan for changes in [[/tmp/tmp.6T246IVl90/logback.xml]] every 60 seconds. 
09:38:30,496 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - Adding ReconfigureOnChangeFilter as a turbo filter
09:38:30,511 |-INFO in ch.qos.logback.classic.joran.action.JMXConfiguratorAction - begin
09:38:30,700 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.rolling.RollingFileAppender]
09:38:30,709 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [FILE]
09:38:30,806 |-INFO in ch.qos.logback.core.rolling.FixedWindowRollingPolicy@5c072e3f - Will use zip compression
09:38:30,892 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
09:38:30,949 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[FILE] - Active log file name: cassandra.logdir_IS_UNDEFINED/system.log
09:38:30,949 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[FILE] - File property is set to [cassandra.logdir_IS_UNDEFINED/system.log]
09:38:30,950 |-ERROR in ch.qos.logback.core.rolling.RollingFileAppender[FILE] - Failed to create parent directories for [/var/lib/scylla/cassandra.logdir_IS_UNDEFINED/system.log]
09:38:30,952 |-ERROR in ch.qos.logback.core.rolling.RollingFileAppender[FILE] - openFile(cassandra.logdir_IS_UNDEFINED/system.log,true) call failed. java.io.FileNotFoundException: cassandra.logdir_IS_UNDEFINED/system.log (No such file or directory)
    at java.io.FileNotFoundException: cassandra.logdir_IS_UNDEFINED/system.log (No such file or directory)
    at  at java.io.FileOutputStream.open0(Native Method)
    at  at java.io.FileOutputStream.open(FileOutputStream.java:270)
    at  at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
    at  at ch.qos.logback.core.recovery.ResilientFileOutputStream.<init>(ResilientFileOutputStream.java:28)
    at  at ch.qos.logback.core.FileAppender.openFile(FileAppender.java:150)
    at  at ch.qos.logback.core.FileAppender.start(FileAppender.java:108)
    at  at ch.qos.logback.core.rolling.RollingFileAppender.start(RollingFileAppender.java:86)
    at  at ch.qos.logback.core.joran.action.AppenderAction.end(AppenderAction.java:96)
    at  at ch.qos.logback.core.joran.spi.Interpreter.callEndAction(Interpreter.java:317)
    at  at ch.qos.logback.core.joran.spi.Interpreter.endElement(Interpreter.java:196)
    at  at ch.qos.logback.core.joran.spi.Interpreter.endElement(Interpreter.java:182)
    at  at ch.qos.logback.core.joran.spi.EventPlayer.play(EventPlayer.java:62)
    at  at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:149)
    at  at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:135)
    at  at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:99)
    at  at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:49)
    at  at ch.qos.logback.classic.util.ContextInitializer.configureByResource(ContextInitializer.java:75)
    at  at ch.qos.logback.classic.util.ContextInitializer.autoConfig(ContextInitializer.java:150)
    at  at org.slf4j.impl.StaticLoggerBinder.init(StaticLoggerBinder.java:85)
    at  at org.slf4j.impl.StaticLoggerBinder.<clinit>(StaticLoggerBinder.java:55)
    at  at org.slf4j.LoggerFactory.bind(LoggerFactory.java:128)
    at  at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:107)
    at  at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:295)
    at  at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:269)
    at  at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:281)
    at  at org.apache.cassandra.utils.FBUtilities.<clinit>(FBUtilities.java:67)
    at  at org.apache.cassandra.tools.NodeTool.printHistory(NodeTool.java:233)
    at  at org.apache.cassandra.tools.NodeTool.main(NodeTool.java:201)
09:38:30,952 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
09:38:30,959 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [STDOUT]
09:38:30,961 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
09:38:30,962 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to INFO
09:38:30,962 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [FILE] to Logger[ROOT]
09:38:30,963 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [STDOUT] to Logger[ROOT]
09:38:30,963 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [com.thinkaurelius.thrift] to ERROR
09:38:30,963 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
09:38:30,964 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@149494d8 - Registering current configuration as safe fallback point
```

**Comment by slivne** [comment] 2015-12-30 09:43
Can you check you are running nodetool status from a directory you have
write permission

**Comment by slivne** [comment] 2015-12-30 09:44
The same errors happen with cassandra-stress when its runned in a directory
you do not have write permissions to.

**Comment by tzach** [comment] 2015-12-30 10:04
Aha!
Good catch. This was indeed the issue.
What is the reason? does this tool write locally?

**Comment by nyh** [comment] 2015-12-30 10:24
Yes, this @#!#ing tool write a log file in "cassandra.logdir_IS_UNDEFINED/system.log" in the current directory. How stupid is that....
Now I have a dozen of these silly directories all over my home directory :-)

**Comment by tzach** [comment] 2015-12-30 10:54
Annoying indeed.
The right place for this issue is nodetool upstream.

**Comment by slivne** [comment] 2015-12-30 11:02
Need to validate that the log creation issue happens with cassandra as well
not only for scylla-tools - we may be missing something.

**Comment by tzach** [comment] 2015-12-30 11:55
The nodetool take his log4j properties from somewhere.
Maybe we should include it.

**Comment by slivne** [comment] 2016-02-18 11:19
duplicate of #702

**Closed** 2017-01-19 11:20 UTC
Labels: bug, nodetool, UX
