### ISSUE TITLE
nodetool describering return null tokens

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#685] opened 2015-12-22 09:36 UTC
nodetool describering return empty token values on Scylla

Cassandra
```
nodetool describering keyspace1
Schema Version:a49b80fb-839c-3ea0-ad1a-8782f38b8e44
TokenRange: 
	TokenRange(start_token:-2609958176230819975, end_token:-2572502286874901652, endpoints:[127.0.0.1], rpc_endpoints:[127.0.0.1], endpoint_details:[EndpointDetails(host:127.0.0.1, datacenter:datacenter1, rack:rack1)])
	TokenRange(start_token:7604915292861497320, end_token:7615943204065541931, endpoints:[127.0.0.1], rpc_endpoints:[127.0.0.1], endpoint_details:[EndpointDetails(host:127.0.0.1, datacenter:datacenter1, rack:rack1)])
	TokenRange(start_token:5709922470988319821, end_token:5843231238195603455, endpoints:[127.0.0.1], rpc_endpoints:[127.0.0.1], endpoint_details:[EndpointDetails(host:127.0.0.1, datacenter:datacenter1, rack:rack1)])
...
```

Scylla
```
 nodetool describering keyspace1
Schema Version:a622bc53-3f54-3416-bfd2-538086a57eb0
TokenRange: 
	{"end_token":"","start_token":"","endpoint_details":[{"datacenter":"datacenter1","host":"127.0.0.1","rack":"rack1"}],"endpoints":["127.0.0.1"],"rpc_endpoints":["127.0.0.1"]}
	{"end_token":"","start_token":"","endpoint_details":[{"datacenter":"datacenter1","host":"127.0.0.1","rack":"rack1"}],"endpoints":["127.0.0.1"],"rpc_endpoints":["127.0.0.1"]}
	{"end_token":"","start_token":"","endpoint_details":[{"datacenter":"datacenter1","host":"127.0.0.1","rack":"rack1"}],"endpoints":["127.0.0.1"],"rpc_endpoints":["127.0.0.1"]}
	{"end_token":"","start_token":"","endpoint_details":[{"datacenter":"datacenter1","host":"127.0.0.1","rack":"rack1"}],"endpoints":
...
```

**Comment by slivne** [comment] 2015-12-22 13:33
duplicate of #681

**Closed by slivne** 2015-12-22 13:33 UTC
Labels: bug, nodetool
