### ISSUE TITLE
database - failed to write sstable and scylladb instance crashed in AWS ScyllaDB 2.0.0 AMI while batch insert only

### ISSUE THREAD

**Issue by ban4785** [scylladb/scylla#3132] opened 2018-01-18 01:11 UTC
Installation details
Scylla version (or git commit hash): 2.0.0
Cluster size: 3
OS (RHEL/CentOS/Ubuntu/AWS AMI): AWS ScyllaDB 2.0.0 - ami

Hardware details (for performance issues) Delete if unneeded
Platform (physical/VM/cloud instance type/docker): AWS VM i3.8xlarge
Hardware: sockets= cores= hyperthreading= memory=32vcore, 244G Memory
Disks: (SSD/HDD, count) : SSD 4*1900 Raid0

i was loading 10Tera data with 300,000 TPS in AWS Infra
same schema, same java batch client  #3100 case, **without read clients**.
but same proxy error occured when 800G loaded.

1. nodetool cfstats info
Keyspace: sems
        Read Count: 0
        Read Latency: NaN ms.
        Write Count: 17994314084
        Write Latency: 6.346263295556246E-6 ms.
        Pending Flushes: 16
                Table: sems_data
                SSTable count: 287
                SSTables in each level: [276/4]
                Space used (live): 535933691210
                Space used (total): 537308909913
                Space used by snapshots (total): 0
                Off heap memory used (total): 4749150926
                SSTable Compression Ratio: 0.121413
                Number of keys (estimate): 22264819
                Memtable cell count: 934320
                Memtable data size: 2980440397
                Memtable off heap memory used: 4567597056
                Memtable switch count: 22438
                Local read count: 0
                Local read latency: NaN ms
                Local write count: 17994412360
                Local write latency: 0.006 ms
                Pending flushes: 16
                Bloom filter false positives: 0
                Bloom filter false ratio: 0.00000
                Bloom filter space used: 4989232
                Bloom filter off heap memory used: 5898432
                Index summary off heap memory used: 175655438
                Compression metadata off heap memory used: 0
                Compacted partition minimum bytes: 311
                Compacted partition maximum bytes: 943127
                Compacted partition mean bytes: 217658
                Average live cells per slice (last five minutes): 0.0
                Maximum live cells per slice (last five minutes): 0
                Average tombstones per slice (last five minutes): 0.0
                Maximum tombstones per slice (last five minutes): 0

2. systemctl log :
_Jan 17 10:54:01 ip-172-30-0-82 scylla: [shard 0] database - failed to write sstable /var/lib/scylla/data/sems/sems_data-01afd8c0fb2611e7b064000000000004/sems-sems_data-ka-11520-Data.db: std::bad_alloc (std::bad_alloc)
Jan 17 10:54:01 ip-172-30-0-82 scylla: [shard 12] storage_proxy - exception during mutation write to 172.31.31.112: std::bad_alloc (std::bad_alloc)
Jan 17 10:54:01 ip-172-30-0-82 scylla: [shard 15] storage_proxy - Failed to apply mutation from 172.31.31.32#14: std::bad_alloc (std::bad_alloc)
Jan 17 10:54:01 ip-172-30-0-82 scylla: [shard 15] storage_proxy - Failed to apply mutation from 172.31.31.32#14: std::bad_alloc (std::bad_alloc)
Jan 17 10:54:01 ip-172-30-0-82 scylla: [shard 12] storage_proxy - exception during mutation write to 172.31.31.112: std::bad_alloc (std::bad_alloc)
Jan 17 10:54:01 ip-172-30-0-82 scylla: [shard 12] storage_proxy - exception during mutation write to 172.31.31.112: std::bad_alloc (std::bad_alloc)
Jan 17 10:54:01 ip-172-30-0-82 scylla: [shard 12] storage_proxy - exception during mutation write to 172.31.31.112: std::bad_alloc (std::bad_alloc)
Jan 17 10:54:01 ip-172-30-0-82 scylla: [shard 12] storage_proxy - exception during mutation write to 172.31.31.112: std::bad_alloc (std::bad_alloc)
Jan 17 10:54:01 ip-172-30-0-82 scylla: [shard 15] storage_proxy - Failed to apply mutation from 172.31.31.32#14: std::bad_alloc (std::bad_alloc)
Jan 17 10:54:01 ip-172-30-0-82 scylla: [shard 0] database - failed to write sstable /var/lib/scylla/data/sems/sems_data-01afd8c0fb2611e7b064000000000004/sems-sems_data-ka-11552-Data.db: std::bad_alloc (std::bad_alloc)
Jan 17 10:54:06 ip-172-30-0-82 scylla: [shard 6] compaction - Compacted 4 sstables to [/var/lib/scylla/data/sems/sems_data-01afd8c0fb2611e7b064000000000004/sems-sems_data-ka-15222-Data.db:level=0, ]. 342472018 bytes to 313892726 (~91% of original) in 147426ms = 2.03MB/s. ~249328 total partitions merged to 62331.
Jan 17 10:54:11 ip-172-30-0-82 scylla: [shard 7] compaction - Compacted 4 sstables to [/var/lib/scylla/data/sems/sems_data-01afd8c0fb2611e7b064000000000004/sems-sems_data-ka-15111-Data.db:level=0, ]. 896641780 bytes to 866940192 (~96% of original) in 710741ms = 1.16MB/s. ~290866 total partitions merged to 102816.
Jan 17 10:54:11 ip-172-30-0-82 scylla: [shard 7] compaction - Compacting [/var/lib/scylla/data/sems/sems_data-01afd8c0fb2611e7b064000000000004/sems-sems_data-ka-15319-Data.db:level=0, /var/lib/scylla/data/sems/sems_data-01afd8c0fb2611e7b064000000000004/sems-sems_data-ka-15239-Data.db:level=0, /var/lib/scylla/data/sems/sems_data-01afd8c0fb2611e7b064000000000004/sems-sems_data-ka-15223-Data.db:level=0, /var/lib/scylla/data/sems/sems_data-01afd8c0fb2611e7b064000000000004/sems-sems_data-ka-15191-Data.db:level=0, /var/lib/scylla/data/sems/sems_data-01afd8c0fb2611e7b064000000000004/sems-sems_data-ka-15207-Data.db:level=0, /var/lib/scylla/data/sems/sems_data-01afd8c0fb2611e7b064000000000004/sems-sems_data-ka-15111-Data.db:level=0, ]
Jan 17 10:54:11 ip-172-30-0-82 scylla: [shard 0] database - failed to write sstable /var/lib/scylla/data/sems/sems_data-01afd8c0fb2611e7b064000000000004/sems-sems_data-ka-11568-Data.db: std::bad_alloc (std::bad_alloc)
Jan 17 10:54:11 ip-172-30-0-82 scylla: [shard 0] database - failed to write sstable /var/lib/scylla/data/sems/sems_data-01afd8c0fb2611e7b064000000000004/sems-sems_data-ka-11584-Data.db: std::bad_alloc (std::bad_alloc)
Jan 17 10:54:15 ip-172-30-0-82 scylla: [shard 11] compaction - Compacting [/var/lib/scylla/data/sems/sems_data-01afd8c0fb2611e7b064000000000004/sems-sems_data-ka-15275-Data.db:level=0, /var/lib/scylla/data/sems/sems_data-01afd8c0fb2611e7b064000000000004/sems-sems_data-ka-15259-Data.db:level=0, /var/lib/scylla/data/sems/sems_data-01afd8c0fb2611e7b064000000000004/sems-sems_data-ka-15243-Data.db:level=0, /var/lib/scylla/data/sems/sems_data-01afd8c0fb2611e7b064000000000004/sems-sems_data-ka-15211-Data.db:level=0, ]
Jan 17 10:54:21 ip-172-30-0-82 scylla: [shard 0] database - failed to write sstable /var/lib/scylla/data/sems/sems_data-01afd8c0fb2611e7b064000000000004/sems-sems_data-ka-11600-Data.db: std::bad_alloc (std::bad_alloc)
Jan 17 10:54:21 ip-172-30-0-82 scylla: [shard 0] database - failed to write sstable /var/lib/scylla/data/sems/sems_data-01afd8c0fb2611e7b064000000000004/sems-sems_data-ka-11616-Data.db: std::bad_alloc (std::bad_alloc)_

3. monitoring info
![2](https://user-images.githubusercontent.com/20348151/35075477-887d3b2a-fc36-11e7-9ed1-3af05f38b890.png)

**Comment by slivne** [comment] 2018-01-25 11:25
@ban4785 if you can share additional info we will try and reproduce (also in #3100)

**Comment by slivne** [comment] 2018-02-11 11:30
@ban4785 ping

**Comment by slivne** [comment] 2018-05-03 09:32
closing this issue since there is no additional information

**Closed by slivne** 2018-05-03 09:32 UTC
