### ISSUE TITLE
scylla goes down when running truncate

### ISSUE THREAD

**Issue by infordb** [scylladb/scylla#2226] opened 2017-03-28 01:57 UTC
*Installation details*
Scylla version (or git commit hash):scylla-server-1.6.2-20170310.d41ba3b.el7.centos.x86_64

Sometimes when I run the truncate command, scylla goes down.

/var/log/messages

Mar 28 10:36:05 fomstap04 scylla: [shard 6] schema_tables - Creating test.test id=e8024eb0-1356-11e7-aee7-000000000002 version=ac1ab861-1d7f-345a-89e5-3cd348623620
Mar 28 10:36:05 fomstap04 scylla: [shard 6] database - Schema version changed to ea1158fe-1eaa-31fe-b764-6cfafe88264b
Mar 28 10:39:35 fomstap04 scylla: [shard 5] schema_tables - Altering test.test id=e8024eb0-1356-11e7-aee7-000000000002 version=827a158c-3d51-3c62-a73c-8e3cddf07bf8
Mar 28 10:39:35 fomstap04 scylla: [shard 5] query_processor - Column definitions for test.test changed, invalidating related prepared statements
Mar 28 10:39:35 fomstap04 scylla: [shard 0] query_processor - Column definitions for test.test changed, invalidating related prepared statements
Mar 28 10:39:35 fomstap04 scylla: [shard 1] query_processor - Column definitions for test.test changed, invalidating related prepared statements
Mar 28 10:39:35 fomstap04 scylla: [shard 2] query_processor - Column definitions for test.test changed, invalidating related prepared statements
Mar 28 10:39:35 fomstap04 scylla: [shard 4] query_processor - Column definitions for test.test changed, invalidating related prepared statements
Mar 28 10:39:35 fomstap04 scylla: [shard 3] query_processor - Column definitions for test.test changed, invalidating related prepared statements
Mar 28 10:39:35 fomstap04 scylla: [shard 7] query_processor - Column definitions for test.test changed, invalidating related prepared statements
Mar 28 10:39:35 fomstap04 scylla: [shard 6] query_processor - Column definitions for test.test changed, invalidating related prepared statements
Mar 28 10:39:35 fomstap04 scylla: [shard 5] database - Schema version changed to dcce1d80-9165-365a-aac6-773890e73f2e
Mar 28 10:45:31 fomstap04 scylla: [shard 7] storage_service - Shutting down communications due to I/O errors until operator intervention
Mar 28 10:45:31 fomstap04 scylla: [shard 0] storage_service - Stop transport: starts
Mar 28 10:45:31 fomstap04 scylla: [shard 0] gossip - My status = NORMAL
Mar 28 10:45:31 fomstap04 scylla: [shard 0] gossip - Announcing shutdown
Mar 28 10:45:31 fomstap04 scylla: [shard 0] storage_service - Node 10.240.29.80 state jump to normal
Mar 28 10:45:33 fomstap04 scylla: [shard 0] storage_service - Stop transport: stop_gossiping done
Mar 28 10:45:33 fomstap04 scylla: [shard 0] storage_service - Thrift server stopped
Mar 28 10:45:33 fomstap04 scylla: [shard 0] storage_service - CQL server stopped
Mar 28 10:45:33 fomstap04 scylla: [shard 0] storage_service - Stop transport: shutdown rpc and cql server done
Mar 28 10:45:33 fomstap04 scylla: [shard 0] storage_service - messaging_service stopped
Mar 28 10:45:33 fomstap04 scylla: [shard 0] storage_service - Stop transport: shutdown messaging_service done
Mar 28 10:45:33 fomstap04 scylla: [shard 0] storage_service - stream_manager stopped
Mar 28 10:45:33 fomstap04 scylla: [shard 0] storage_service - Stop transport: shutdown stream_manager done
Mar 28 10:45:33 fomstap04 scylla: [shard 0] storage_service - Stop transport: auth shutdown
Mar 28 10:45:33 fomstap04 scylla: [shard 0] storage_service - Stop transport: done

**Comment by infordb** [comment] 2017-03-28 02:11
after running sstable2json file owner of Summary.db was changed to root
Why it has changed
Even so, It is problem that scylla goes down...



[root@fomstap04 test-e8024eb0135611e7aee7000000000002]# nodetool flush test
[root@fomstap04 test-e8024eb0135611e7aee7000000000002]# ll
total 40
drwx------. 5 scylla scylla   81 Mar 28 11:01 snapshots
-rw-r--r--. 1 scylla scylla   66 Mar 28 11:07 test-test-ka-15-CompressionInfo.db
-rw-r--r--. 1 scylla scylla   63 Mar 28 11:07 test-test-ka-15-Data.db
-rw-r--r--. 1 scylla scylla   10 Mar 28 11:07 test-test-ka-15-Digest.sha1
-rw-r--r--. 1 scylla scylla   16 Mar 28 11:07 test-test-ka-15-Filter.db
-rw-r--r--. 1 scylla scylla   15 Mar 28 11:07 test-test-ka-15-Index.db
-rw-r--r--. 1 scylla scylla   38 Mar 28 11:07 test-test-ka-15-Scylla.db
-rw-r--r--. 1 scylla scylla 4462 Mar 28 11:07 test-test-ka-15-Statistics.db
-rw-r--r--. 1 scylla scylla   47 Mar 28 11:07 test-test-ka-15-Summary.db
-rw-r--r--. 1 scylla scylla  101 Mar 28 11:07 test-test-ka-15-TOC.txt
drwx------. 2 scylla scylla    6 Mar 28 10:36 upload
[root@fomstap04 test-e8024eb0135611e7aee7000000000002]# sstable2json test-test-ka-15-Data.db
[
{"key": "1",
 "cells": [["","",1490666800191272],
           ["name",1490666815,1490666815371862,"d"]]}
]
[root@fomstap04 test-e8024eb0135611e7aee7000000000002]# ll
total 40
drwx------. 5 scylla scylla   81 Mar 28 11:01 snapshots
-rw-r--r--. 1 scylla scylla   66 Mar 28 11:07 test-test-ka-15-CompressionInfo.db
-rw-r--r--. 1 scylla scylla   63 Mar 28 11:07 test-test-ka-15-Data.db
-rw-r--r--. 1 scylla scylla   10 Mar 28 11:07 test-test-ka-15-Digest.sha1
-rw-r--r--. 1 scylla scylla   16 Mar 28 11:07 test-test-ka-15-Filter.db
-rw-r--r--. 1 scylla scylla   15 Mar 28 11:07 test-test-ka-15-Index.db
-rw-r--r--. 1 scylla scylla   38 Mar 28 11:07 test-test-ka-15-Scylla.db
-rw-r--r--. 1 scylla scylla 4462 Mar 28 11:07 test-test-ka-15-Statistics.db
**-rw-r--r--. 1 root   root     71 Mar 28 11:07 test-test-ka-15-Summary.db**
-rw-r--r--. 1 scylla scylla  101 Mar 28 11:07 test-test-ka-15-TOC.txt
drwx------. 2 scylla scylla    6 Mar 28 10:36 upload

**Comment by penberg** [comment] 2017-03-28 06:54
AFAICT, Scylla decides to bring down the node because it interprets `EPERM` as an "I/O error", which it is not.

/cc @avikivity @tgrabiec

**Comment by slivne** [comment] 2017-03-30 11:08
@infordb so the problem is not related to truncate but rather to sstable2json changing owners ?

**Comment by infordb** [comment] 2017-04-02 23:33
@slivne you are right , but, I think that  scylla should not go down with this minor problem

**Comment by tzach** [comment] 2017-04-03 05:55
@infordb not been able to access SSTable is not a minor issue. I agree we can do better in some cases, but IMHO this is not one of them. I'm closing this issue for now, and we should open a new enhancement request for more granular IO error handling.

**Closed by tzach** 2017-04-03 05:55 UTC

**Comment by slivne** [comment] 2017-04-03 05:58
scylladb/scylla-tools-java#26
