### ISSUE TITLE
patchelf breaks build-id in core files

### ISSUE THREAD

**Issue by espindola** [scylladb/scylla#5429] opened 2019-12-05 20:35 UTC
The LOAD segments and build-id section of a freshly linked scylla binaries look like this:

```
  Type           Offset   VirtAddr           PhysAddr           FileSiz  MemSiz   Flg Align
  LOAD           0x000000 0x0000000000400000 0x0000000000400000 0x32b0ab0 0x32b0ab0 R E 0x1000
  LOAD           0x32b0cc0 0x00000000036b1cc0 0x00000000036b1cc0 0x00ac18 0x043648 RW  0x1000
  [ 4] .note.gnu.build-id NOTE            00000000004002b8 0002b8 000024 00   A  0   0  4

```

After patchelf is done with it, it looks like

```
 Type           Offset   VirtAddr           PhysAddr           FileSiz  MemSiz   Flg Align
  LOAD           0x000000 0x00000000003ff000 0x00000000003ff000 0x001000 0x001000 RW  0x1000
  LOAD           0x001000 0x0000000000400000 0x0000000000400000 0x32b0ab0 0x32b0ab0 R E 0x1000
  LOAD           0x32b1cc0 0x00000000036b1cc0 0x00000000036b1cc0 0x00ac18 0x043648 RW  0x1000
  [ 4] .note.gnu.build-id NOTE            00000000004002b8 0012b8 000024 00   A  0   0  4
```

Note how before patchelf the buildid is in the PT_LOAD that starts at 0, but after patchelf there is a new PT_LOAD and the buildid is in the PT_LOAD that starts at offset 0x001000.

That is a problem, because the kernel will not write it to the core file. From linux's binfmt_elf.c:

```
        /*                                                                                                                                                                                            
         * If this looks like the beginning of a DSO or executable mapping,                                                                                                                           
         * check for an ELF header.  If we find one, dump the first page to                                                                                                                           
         * aid in determining what was mapped here.                                                                                                                                                   
         */
        if (FILTER(ELF_HEADERS) &&
```

**Comment by espindola** [comment] 2019-12-05 20:37
One way to solve this is to link with -Wl,-dynamic-linker /some/very/long/dummy/path. Patchelf only needs to add a new PT_LOAD if the new path is larger than the old one.

But can we avoid patchelf completely? Can we run scylla inside a chroot or privileged container?

**Comment by avikivity** [comment] 2019-12-05 20:52
I guess we could have a helper program that creates a mount namespace, bind-mounts all the data directories, bind-mounts all the binary and library directories in the same place as the fedora bins/libs, enters the namespace and execs scylla. That helper could ve statically linked.

Chroot is also possible, but we'd need to create lots of bind mounts anyway we may as well use a namespace.

It's also possible to use systemd-nspawn. But I like the helper because it does the minmal thing and leaves no footprint, it's just a regular procress and we only create a mount namespace for it, nothing else.

**Comment by avikivity** [comment] 2019-12-05 20:55
It may even be a shell script with unshare(1) (except we may break the script when we start bind-mounting in /usr/lib64)

**Comment by espindola** [comment] 2019-12-05 23:52
I am taking a look at what the mount namespace helper would look like. BTW, how would you find out the data directory? Parse the scylla config?

**Comment by espindola** [comment] 2019-12-06 04:20
This can start scylla for me. All paths are hardcoded and it assumes that libreloc has been renamed to lib64 and ld-linux-x86-64.so.2 is a symbolic link to ld.so.

[run-in-ns.c.txt](https://github.com/scylladb/scylla/files/3930383/run-in-ns.c.txt)

**Comment by bhalevy** [comment] 2019-12-06 06:39
> I guess we could have a helper program that creates a mount namespace, bind-mounts all the data directories, bind-mounts all the binary and library directories in the same place as the fedora bins/libs, enters the namespace and execs scylla. That helper could ve statically linked.
> 
> Chroot is also possible, but we'd need to create lots of bind mounts anyway we may as well use a namespace.
> 
> It's also possible to use systemd-nspawn. But I like the helper because it does the minmal thing and leaves no footprint, it's just a regular procress and we only create a mount namespace for it, nothing else.

That means user must have su privileges, right? Is this a reasonable requirement?

**Comment by denesb** [comment] 2019-12-06 07:58
Could this be the cause of https://github.com/scylladb/scylla/issues/4983?

**Comment by avikivity** [comment] 2019-12-06 11:41
We could have a suid helper but @bhalevy is right, we also want to run without root permissions at all.

Maybe we can have both methods, preferring the suid/capability helper but falling back to the current method.

Another option is to binary-edit the executable so that patchelf won't corrupt it.

**Comment by avikivity** [comment] 2019-12-06 11:42
Closimg as duplicate of #4983

**Closed by avikivity** 2019-12-06 11:42 UTC

**Comment by avikivity** [comment] 2019-12-06 11:44
@espindola why anything more than unshare(CLONE_NEWNS)?

**Comment by avikivity** [comment] 2019-12-06 13:25
This explains how to do it unprivileged: https://kinvolk.io/blog/2018/04/towards-unprivileged-container-builds/. First you unshare the user namespace, becoming root, then you can unshare the mount namespace.

**Comment by espindola** [comment] 2019-12-06 16:43
Botond Dénes <notifications@github.com> writes:

> Could this be the cause of https://github.com/scylladb/scylla/issues/4983?

It almost certainly is the root cause.

Cheers,
Rafael

**Comment by espindola** [comment] 2019-12-06 16:45
It can be done without root. The .c file I uploaded as a proof of
concept doesn't need root.

**Comment by espindola** [comment] 2019-12-06 16:48
> @espindola why anything more than unshare(CLONE_NEWNS)?

mounting /sys.

Looking at the podman source I see that they bind mount it when using
host network. I will update to do that (and make it a real patch).

**Comment by avikivity** [comment] 2019-12-06 16:52
If I may pre-review the patch, I suggest making all the mounts parameters. The scylla shell script thunk can supply them.

Also, start with the host / as the container /, so we don't need to care about which directories the scylla binary needs.

**Comment by avikivity** [comment] 2019-12-06 16:54
One more thing: it needs to work on CentOS 7 kernels, and we need to know what's the oldest CentOS kernel we support, so we can put a Requires clause in our package. It doesn't need to be done immediately, but we'll need it to commit.

**Comment by espindola** [comment] 2019-12-06 18:10
Avi Kivity <notifications@github.com> writes:

> If I may pre-review the patch, I suggest making all the mounts parameters. The scylla shell script thunk can supply them.
>
> Also, start with the host / as the container /, so we don't need to care about which directories the scylla binary needs.

That is an interesting idea.

We could use overlayfs to use our ld.so, but I am afraid it might break
regular tools.

What I think I will try is

* Link scylla with
  -Wl,--dynamic-linker=/opt/scylla/lib64/ld-linux-x86-64.so.2
* Start the container with the host / as the container /
* bind mount whatever directory we are installed in to /opt/scylla

But this reminds me of something I am sure was proposed before, but I
can't find it

* Link scylla with  -Wl,--dynamic-linker ../libreloc/ld-linux-x86-64.so.2
* Use a shell script to start scylla from the right directory.

The last bit is needed because the kernel looks PT_INTERP relative to
cwd.

This avoids the need for changing any namespaces.

Cheers,
Rafael

**Comment by avikivity** [comment] 2019-12-08 14:41
Maybe it can be as simple as replacing our existing thunk with

    unshare -Urm bash -c "mount --bind /path/to/one-library.so /usr/lib64/one-library.so && ... && exec /path/to/real-scylla "$@"

**Comment by avikivity** [comment] 2019-12-08 14:46
One downside is that it doesn't work within docker. I don't know why. But maybe we can fall back on the old method in that case.

**Comment by avikivity** [comment] 2019-12-08 14:48
> Avi Kivity <notifications@github.com> writes:
> If I may pre-review the patch, I suggest making all the mounts parameters. The scylla shell script thunk can supply them. Also, start with the host / as the container /, so we don't need to care about which directories the scylla binary needs.
> That is an interesting idea. We could use overlayfs to use our ld.so, but I am afraid it might break regular tools. What I think I will try is * Link scylla with -Wl,--dynamic-linker=/opt/scylla/lib64/ld-linux-x86-64.so.2 * Start the container with the host / as the container / * bind mount whatever directory we are installed in to /opt/scylla But this reminds me of something I am sure was proposed before, but I can't find it * Link scylla with -Wl,--dynamic-linker ../libreloc/ld-linux-x86-64.so.2 * Use a shell script to start scylla from the right directory. The last bit is needed because the kernel looks PT_INTERP relative to cwd. This avoids the need for changing any namespaces. Cheers, Rafael

Doesn't the link trick require that we change $CWD? That's find for deployed scylla (which is always accessed via a thunk) but not for developer scylla (which is usually executed directly).

**Comment by avikivity** [comment] 2019-12-08 14:56
> One downside is that it doesn't work within docker. I don't know why. But maybe we can fall back on the old method in that case.

Because of https://github.com/opencontainers/runc/issues/1658#issuecomment-345981847
