### ISSUE TITLE
script scylla-housekeeping with "localhost" being hardcoded as default endpoint even when default interface is not "lo"

### ISSUE THREAD

**Issue by julienlau** [scylladb/scylla#3077] opened 2017-12-19 11:22 UTC
*Installation details*
Scylla version (or git commit hash): 2.0.2
Cluster size: 4 VMS
OS (RHEL/CentOS/Ubuntu/AWS AMI): centos

*Hardware details (for performance issues)*          Delete if unneeded
Platform (physical/VM/cloud instance type/docker): azure
Hardware: sockets= cores= hyperthreading= memory=
Disks: (SSD/HDD, count)

Something is wrong with the script scylla-housekeeping with "localhost" being hardcoded as default endpoint even when default interface is not "lo".
Dec 19 11:04:54 CAS-01-SCUS scylla-housekeeping[1237]: ValueError: No JSON object could be decoded
Dec 19 11:04:54 CAS-01-SCUS scylla-housekeeping[1237]: raise ValueError("No JSON object could be decoded")
Dec 19 11:04:54 CAS-01-SCUS scylla-housekeeping[1237]: File "/usr/lib64/python2.7/json/decoder.py", line 384, in raw_decode
Dec 19 11:04:54 CAS-01-SCUS scylla-housekeeping[1237]: obj, end = self.raw_decode(s, idx=_w(s, 0).end())
Dec 19 11:04:54 CAS-01-SCUS scylla-housekeeping[1237]: File "/usr/lib64/python2.7/json/decoder.py", line 366, in decode
Dec 19 11:04:54 CAS-01-SCUS scylla-housekeeping[1237]: return _default_decoder.decode(s)
Dec 19 11:04:54 CAS-01-SCUS scylla-housekeeping[1237]: File "/usr/lib64/python2.7/json/__init__.py", line 338, in loads
Dec 19 11:04:54 CAS-01-SCUS scylla-housekeeping[1237]: return json.loads(data)
Dec 19 11:04:54 CAS-01-SCUS scylla-housekeeping[1237]: File "/usr/lib/scylla/scylla-housekeeping", line 62, in get_json_from_url
Dec 19 11:04:54 CAS-01-SCUS scylla-housekeeping[1237]: return get_json_from_url("http://localhost:10000" + path)
Dec 19 11:04:54 CAS-01-SCUS scylla-housekeeping[1237]: File "/usr/lib/scylla/scylla-housekeeping", line 65, in get_api
Dec 19 11:04:54 CAS-01-SCUS scylla-housekeeping[1237]: current_version = sanitize_version(get_api('/storage_service/scylla_release_version'))
Dec 19 11:04:54 CAS-01-SCUS scylla-housekeeping[1237]: File "/usr/lib/scylla/scylla-housekeeping", line 104, in check_version
Dec 19 11:04:54 CAS-01-SCUS scylla-housekeeping[1237]: args.func(args)
Dec 19 11:04:54 CAS-01-SCUS scylla-housekeeping[1237]: File "/usr/lib/scylla/scylla-housekeeping", line 164, in <module>
Dec 19 11:04:54 CAS-01-SCUS scylla-housekeeping[1237]: Traceback (most recent call last):

--------------------

[coretech@CAS-01-SCUS]> wget http://10.223.1.7:10000/storage_service/scylla_release_version
--2017-12-19 11:17:54--  http://10.223.1.7:10000/storage_service/scylla_release_version
Connecting to 10.223.1.7:10000... connected.
HTTP request sent, awaiting response... 200 OK
Length: 26 [text/plain]
Saving to: ‘scylla_release_version’

100%[=========================================================================================================================================================================>] 26          --.-K/s   in 0s      

2017-12-19 11:17:54 (6.53 MB/s) - ‘scylla_release_version’ saved [26/26]

~/
[coretech@CAS-01-SCUS]> wget http://localhost:10000/storage_service/scylla_release_version
--2017-12-19 11:18:07--  http://localhost:10000/storage_service/scylla_release_version
Resolving localhost (localhost)... ::1, 127.0.0.1
Connecting to localhost (localhost)|::1|:10000... failed: Connection refused.
Connecting to localhost (localhost)|127.0.0.1|:10000... failed: Connection refused.
~/

-------------------------------------------

~/
[coretech@CAS-01-SCUS]> ifconfig
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 10.223.1.7  netmask 255.255.255.0  broadcast 10.223.1.255
        inet6 fe80::20d:3aff:fe74:98d6  prefixlen 64  scopeid 0x20<link>
        ether 00:0d:3a:74:98:d6  txqueuelen 1000  (Ethernet)
        RX packets 21011  bytes 5281136 (5.0 MiB)
        RX errors 0  dropped 3  overruns 0  frame 0
        TX packets 22802  bytes 33222524 (31.6 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1  (Local Loopback)
        RX packets 45974  bytes 42644736 (40.6 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 45974  bytes 42644736 (40.6 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

**Comment by tzach** [comment] 2017-12-19 13:33
@amnonh ?

**Comment by amnonh** [comment] 2017-12-19 13:58
what is the scenario that the API is not open to localhost?

On Tue, Dec 19, 2017 at 1:22 PM, Julien Laurenceau <notifications@github.com

**Comment by julienlau** [comment] 2017-12-19 14:04
My cluster is configured on interface eth0 and not lo

grep -e interface -e ip -e address /etc/scylla/scylla.yaml | grep -v '^#' 
    # multiple nodes!
          # seeds is actually a comma-delimited list of addresses.
          # Ex: "<ip1>,<ip2>,<ip3>"
listen_address: 10.223.1.7
endpoint_snitch: GossipingPropertyFileSnitch
rpc_address: 10.223.1.7
rpc_interface_prefer_ipv6: false
api_address: 10.223.1.7
broadcast_rpc_address: 10.223.1.7
listen_interface: eth0
listen_interface_prefer_ipv6: false
    # cipher_suites: [TLS_RSA_WITH_AES_128_CBC_SHA,TLS_RSA_WITH_AES_256_CBC_SHA,TLS_DHE_RSA_WITH_AES_128_CBC_SHA,TLS_DHE_RSA_WITH_AES_256_CBC_SHA,TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA,TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA]
prometheus_address: 10.223.1.7

**Comment by amnonh** [comment] 2017-12-19 14:20
but typically the api listening address should be set to local regardless

On Tue, Dec 19, 2017 at 4:05 PM, Julien Laurenceau <notifications@github.com

**Comment by amnonh** [comment] 2017-12-24 13:56
Duplicate of #2332

**Closed** 2017-12-31 10:38 UTC
Labels: bug, duplicate
