### ISSUE TITLE
Node Removed From Scylla Weeks Ago Still In `nodetool gossipinfo` Output

### ISSUE THREAD

**Issue by KaranKamath** [scylladb/scylla#4214] opened 2019-02-12 09:52 UTC
*Installation details*
Scylla version (or git commit hash): Originally 2.2.1, upgraded to 2.3.2 and then 3.0.1
Cluster size: 4 (5 with ghost node)
OS (RHEL/CentOS/Ubuntu/AWS AMI): Linux ip-10-10-58-92 4.4.0-112-generic #135~14.04.1-Ubuntu SMP Tue Jan 23 20:41:48 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

*Issue*
On upgrading a 4 node cluster to 3.0.1, we noticed that creating MVs failed with: `InvalidRequest: Error from server: code=2200 [Invalid query] message="Can't create materialized views until the whole cluster has been upgraded"`

On following up with the Scylla team on Slack, we discovered that while `describecluster` and `status` showed 4 nodes, `nodetool gossipinfo` had 5 nodes in the cluster. This cluster had some nodes recycled a few weeks ago. Most were decommissioned, some were removed with removenode. It is not clear which was applied to the ghost node, and the physical hardware for it has been released. From Feb 1st (12 days ago), there is this message in the logs of the remaining nodes:

```[shard 0] gossip - Node 10.10.1.216 will be removed from gossip at [48501255-02-20 17:25:16]: (expire = 1530489613195516626, now = 1548991090804, diff = 1530488064204425 seconds)```

This seems wrong (not the 3 day default, but instead a huge delta before removal).

In the short term, we also need a way of forcing this node out.

**Comment by asias** [comment] 2019-02-12 10:06
Is it possible during the time the decommission happens the system time of the nodes are messed up?

**Comment by KaranKamath** [comment] 2019-02-12 10:25
Don't see any evidence of that right now, although I don't have logs from the time of removal. The system time on the 4 nodes right now look fine.

**Comment by KaranKamath** [comment] 2019-02-13 06:11
Following recommendations from the Scylla team, I shut down all the nodes, removed the dead node DNS from the seed list, and then started all the servers. This solved the issue as the ghost node was not in the system.peers table for any of the nodes. (We had to make the cluster unavailable while this was in progress.)

**Comment by asias** [comment] 2019-02-13 08:28
Can you collect the expire log on all the node: ```[shard 0] gossip - Node 10.10.1.216 will be removed from gossip at .... ```

**Comment by asias** [comment] 2019-02-19 02:18
[shard 0] gossip - Node 10.10.1.216 will be removed from gossip at [48501255-02-20 17:25:16]: (expire = 1530489613195516626, now = 1548991090804, diff = 1530488064204425 seconds)


The expire time above looks wrong. The correct one looks like:

INFO  2019-02-19 10:02:38,816 [shard 0] gossip - Node 127.0.0.3 will be removed from gossip at [2019-02-22 10:02:38]: (expire = 1550800958352, now = 1550541758810, diff = 259199 seconds)


In commit a36141843aaf50982b2ab9c888ded3f45d41c962, scylla switched to the lowres clock. This commit is in 2.2.1 release. So we won't have mixed expire time with std::chrono::system_clock and seastar::lowres_system_clock. 

commit a36141843aaf50982b2ab9c888ded3f45d41c962
Author: Asias He <asias@scylladb.com>
Date:   Tue Aug 29 09:57:54 2017 +0800

    gossip: Switch to seastar::lowres_system_clock
    
    The newly added lowres_system_clock is good enough for gossip
    resolution. Switch to use it.
    
    Message-Id: <fe0e7a9ef1ea0caffaa8364afe5c78b6988613bf.1503971833.git.asias@scylladb.com>

One theory we have the wrong expire time is we have bug with the lowres clock. 

Also, It is not a wrap around issue, i.e. now  > expire.

**Comment by slivne** [comment] 2019-03-26 09:04
@asias ping

**Comment by tzach** [comment] 2019-06-24 07:29
@asias ?

**Comment by asias** [comment] 2019-06-24 07:36
As I mentioned in the last comment, there is an issue in the timestamp from user's log. I could not reproduce this issue so far. 

```
[shard 0] gossip - Node 10.10.1.216 will be removed from gossip at [48501255-02-20 17:25:16]: (expire = 1530489613195516626, now = 1548991090804, diff = 1530488064204425 seconds)

The expire time above looks wrong. The correct one looks like:

INFO 2019-02-19 10:02:38,816 [shard 0] gossip - Node 127.0.0.3 will be removed from gossip at [2019-02-22 10:02:38]: (expire = 1550800958352, now = 1550541758810, diff = 259199 seconds)
```

**Comment by slivne** [comment] 2021-03-29 06:35
could not reproduce - closing

**Comment by slivne** [comment] 2021-03-29 06:36
could not reproduce - closing

**Closed by slivne** 2021-03-29 06:35 UTC
Labels: bug
