### ISSUE TITLE
Scylla can't recover from ENOSPC automatically

### ISSUE THREAD

**Issue by amoskong** [scylladb/scylla#2464] opened 2017-06-10 16:36 UTC
*Installation details*
Scylla version (or git commit hash): 1.7.1-0.20170606.562102c
Cluster size: 2
OS (RHEL/CentOS/Ubuntu/AWS AMI): GCE CentOS7

*Description:*
Create  a GCE scylla cluster, and start 4 c-s workloads on two loaders.
Wait about 10 mins then try to cost rest space on /var/lib/scylla storage by `sudo dd if=/dev/zero of=/var/lib/scylla/occupy_rest_space`
When the space is full, wait 30s, then release space by delete occupy_rest_space file.

*Result:*
Scylla server didn't recover automatically after space was released.
Restart finally recovers scylla-server.

*Configure:*
- 2 * db_nodes (n1-highmem-16)
- 2 * loaders (n1-standard-2)
- 1 * monitor (n1-standard-1)

*C-S cmdline*
- totally has 4 c-s executions on two loaders:
- cassandra-stress write no-warmup cl=QUORUM duration=30m -schema keyspace=keyspace1 'replication(factor=2)' -port jmx=6868 -mode cql3 native -rate threads=100 -errors ignore -pop seq=1..10000000 -node 10.240.0.60

*Log*
```
2017-06-10 14:46:24,053 nemesis          L0243 DEBUG| sdcm.nemesis.EnospcAllNodesMonkey: Cost rest space on /var/lib/scylla/ by `sudo dd if=/dev/zero of=/var/lib/scylla/occupy_rest_space`
2017-06-10 15:21:39,324 remote           L0197 DEBUG| [104.196.12.98] [stdout] 334941900800 bytes (335 GB) copied, 2114.89 s, 158 MB/s

### Space is full

2017-06-10 15:21:40,008 remote           L0197 DEBUG| [104.196.12.98] [stdout] Jun 10 15:21:39 warning|  [shard 10] storage_service - Shutting down communications due to I/O errors until operator intervention
2017-06-10 15:21:40,009 remote           L0197 DEBUG| [104.196.12.98] [stdout] Jun 10 15:21:39 info   |  [shard 0] storage_service - Stop transport: starts
2017-06-10 15:21:40,013 remote           L0197 DEBUG| [104.196.12.98] [stdout] Jun 10 15:21:39 info   |  [shard 0] gossip - My status = NORMAL
2017-06-10 15:21:40,014 remote           L0197 DEBUG| [104.196.12.98] [stdout] Jun 10 15:21:39 info   |  [shard 0] gossip - Announcing shutdown

### ^^^ sth shutdown

2017-06-10 15:21:40,018 remote           L0197 DEBUG| [104.196.12.98] [stdout] Jun 10 15:21:39 info   |  [shard 0] storage_service - Node 10.240.0.60 state jump to normal
2017-06-10 15:21:40,037 remote           L0197 DEBUG| [104.196.12.98] [stdout] Jun 10 15:21:39 warning|  [shard 10] commitlog - Exception in segment reservation: storage_io_error (Storage I/O error: 28: No space left on device)
2017-06-10 15:21:40,040 remote           L0197 DEBUG| [104.196.12.98] [stdout] Jun 10 15:21:39 err    |  [shard 10] commitlog - Failed to persist commits to disk for CommitLog-1-180143985094834719.log: storage_io_error (Storage I/O error: 28: No space left on device)
2017-06-10 15:21:40,045 remote           L0197 DEBUG| [104.196.12.98] [stdout] Jun 10 15:21:39 err    |  [shard 5] sstable - Could not create SSTable component /var/lib/scylla/data/system/peers-37f71aca7dc2383ba70672528af04d4f/system-peers-ka-37-TOC.txt.tmp. Found exception: storage_io_error (Storage I/O error: 28: No space left on device)
2017-06-10 15:21:40,047 remote           L0197 DEBUG| [104.196.12.98] [stdout] Jun 10 15:21:39 err    |  [shard 5] database - failed to write sstable /var/lib/scylla/data/system/peers-37f71aca7dc2383ba70672528af04d4f/system-peers-ka-37-Data.db: storage_io_error (Storage I/O error: 28: No space left on device)
2017-06-10 15:21:40,049 remote           L0197 DEBUG| [104.196.12.98] [stdout] Jun 10 15:21:39 err    |  [shard 13] sstable - Could not create SSTable component /var/lib/scylla/data/system/peers-37f71aca7dc2383ba70672528af04d4f/system-peers-ka-45-TOC.txt.tmp. Found exception: storage_io_error (Storage I/O error: 28: No space left on device)
2017-06-10 15:21:40,049 remote           L0197 DEBUG| [104.196.12.98] [stdout] Jun 10 15:21:39 err    |  [shard 13] database - failed to write sstable /var/lib/scylla/data/system/peers-37f71aca7dc2383ba70672528af04d4f/system-peers-ka-45-Data.db: storage_io_error (Storage I/O error: 28: No space left on device) 
2017-06-10 15:21:40,169 remote           L0197 DEBUG| [104.196.12.98] [stdout] Jun 10 15:21:39 warning|  [shard 0] sstable - Unable to delete /var/lib/scylla/data/system/peers-37f71aca7dc2383ba70672528af04d4f/system-peers-ka-37-TOC.txt because it doesn't exist. 
2017-06-10 15:21:40,169 remote           L0197 DEBUG| [104.196.12.98] [stdout] Jun 10 15:21:39 warning|  [shard 0] sstable - Unable to delete /var/lib/scylla/data/system/peers-37f71aca7dc2383ba70672528af04d4f/system-peers-ka-45-TOC.txt because it doesn't exist. 
2017-06-10 15:21:40,170 remote           L0197 DEBUG| [104.196.12.98] [stdout] Jun 10 15:21:39 warning|  [shard 10] seastar - Exceptional future ignored: storage_io_error (Storage I/O error: 28: No space left on device), backtrace: 0x4ecc83, 0x4ecce1, 0x10807b1, 0x10811a4, 0x4e20f9, 0x531c42, 0x533480, 0x58edad, 0x7fc19d1bbdc4, 0x7fc19ceea76c 
2017-06-10 15:21:40,170 remote           L0197 DEBUG| [104.196.12.98] [stdout] Jun 10 15:21:40 err    |  [shard 10] commitlog - Failed to persist commits to disk for CommitLog-1-180143985094834719.log: storage_io_error (Storage I/O error: 28: No space left on device) 
2017-06-10 15:21:40,170 remote           L0197 DEBUG| [104.196.12.98] [stdout] Jun 10 15:21:40 warning|  [shard 10] seastar - Exceptional future ignored: storage_io_error (Storage I/O error: 28: No space left on device), backtrace: 0x4ecc83, 0x4ecce1, 0x10807b1, 0x10811a4, 0x4e20f9, 0x531c42, 0x533480, 0x58edad, 0x7fc19d1bbdc4, 0x7fc19ceea76c 
2017-06-10 15:21:40,171 remote           L0197 DEBUG| [104.196.12.98] [stdout] Jun 10 15:21:40 warning|  [shard 10] commitlog - Exception in segment reservation: storage_io_error (Storage I/O error: 28: No space left on device) 
.....
.....
2017-06-10 15:23:43,375 remote           L0197 DEBUG| [104.196.12.98] [stdout] Jun 10 15:23:43 warning|  [shard 8] commitlog - Exception in segment reservation: storage_io_error (Storage I/O error: 28: No space left on device)
2017-06-10 15:23:50,259 remote           L0197 DEBUG| [35.190.130.121] [stdout] Jun 10 15:23:50 info   |  [shard 0] gossip - InetAddress 10.240.0.60 is now DOWN, status = shutdown

### Gossip is down

2017-06-10 15:23:52,261 remote           L0197 DEBUG| [104.196.12.98] [stdout] Jun 10 15:23:52 info   |  [shard 0] storage_service - Stop transport: stop_gossiping done
2017-06-10 15:23:52,261 remote           L0197 DEBUG| [104.196.12.98] [stdout] Jun 10 15:23:52 info   |  [shard 0] storage_service - Thrift server stopped
2017-06-10 15:23:52,262 remote           L0197 DEBUG| [104.196.12.98] [stdout] Jun 10 15:23:52 info   |  [shard 0] storage_service - CQL server stopped
2017-06-10 15:23:52,263 remote           L0197 DEBUG| [104.196.12.98] [stdout] Jun 10 15:23:52 info   |  [shard 0] storage_service - Stop transport: shutdown rpc and cql server done
2017-06-10 15:23:52,264 remote           L0197 DEBUG| [104.196.12.98] [stdout] Jun 10 15:23:52 info   |  [shard 0] storage_service - messaging_service stopped
2017-06-10 15:23:52,264 remote           L0197 DEBUG| [104.196.12.98] [stdout] Jun 10 15:23:52 info   |  [shard 0] storage_service - Stop transport: shutdown messaging_service done
2017-06-10 15:23:52,265 remote           L0197 DEBUG| [104.196.12.98] [stdout] Jun 10 15:23:52 info   |  [shard 0] storage_service - stream_manager stopped
2017-06-10 15:23:52,266 remote           L0197 DEBUG| [104.196.12.98] [stdout] Jun 10 15:23:52 info   |  [shard 0] storage_service - Stop transport: shutdown stream_manager done
2017-06-10 15:23:52,267 remote           L0197 DEBUG| [104.196.12.98] [stdout] Jun 10 15:23:52 info   |  [shard 0] storage_service - Stop transport: auth shutdown
2017-06-10 15:23:52,268 remote           L0197 DEBUG| [104.196.12.98] [stdout] Jun 10 15:23:52 info   |  [shard 0] storage_service - Stop transport: done

### transport is stop

 [scylla-test@gce-enospc-1-7-scylla-db-node-3399892b-1 ~]$ service scylla-server status
 Redirecting to /bin/systemctl status  scylla-server.service
 ● scylla-server.service - Scylla Server
    Loaded: loaded (/usr/lib/systemd/system/scylla-server.service; enabled; vendor preset: disabled)
    Active: active (running) since Sat 2017-06-10 14:23:36 UTC; 1h 2min ago
   Process: 855 ExecStartPre=/usr/lib/scylla/scylla_prepare (code=exited, status=0/SUCCESS)
  Main PID: 1029 (scylla)
    Status: "serving"
    CGroup: /system.slice/scylla-server.service
            └─1029 /usr/bin/scylla --log-to-syslog 1 --log-to-stdout 0 --default-log-level info --collectd-address=127.0.0.1:25826 --...

### scylla-server service still is active (running) status, Actually not active


2017-06-10 15:23:52,429 remote           L0197 DEBUG| [35.190.130.121] [stdout] Jun 10 15:23:52 info   |  [shard 0] rpc - client 10.240.0.60: fail to connect: Connection refused
.....
.....
.....
2017-06-10 15:29:38,051 remote           L0197 DEBUG| [35.190.130.121] [stdout] Jun 10 15:29:37 info   |  [shard 0] rpc - client 10.240.0.60: fail to connect: Connection refused

### try to recover scylla by restart


2017-06-10 15:29:38,205 remote           L0197 DEBUG| [104.196.12.98] [stdout] Jun 10 15:29:38 info   |  [shard 0] storage_service - Drain on shutdown: flush column_families done
2017-06-10 15:29:38,208 remote           L0197 DEBUG| [104.196.12.98] [stdout] Jun 10 15:29:38 info   |  [shard 0] storage_service - Drain on shutdown: shutdown commitlog done
2017-06-10 15:29:38,210 remote           L0197 DEBUG| [104.196.12.98] [stdout] Jun 10 15:29:38 info   |  [shard 0] storage_service - Drain on shutdown: done
2017-06-10 15:29:38,210 remote           L0197 DEBUG| [104.196.12.98] [stdout] Jun 10 15:29:38 info   |  [shard 0] repair - Starting shutdown of repair
2017-06-10 15:29:38,211 remote           L0197 DEBUG| [104.196.12.98] [stdout] Jun 10 15:29:38 info   |  [shard 0] repair - Completed shutdown of repair
2017-06-10 15:29:38,212 remote           L0197 DEBUG| [104.196.12.98] [stdout] Jun 10 15:29:38 info   |  [shard 0] compaction_manager - Asked to stop
2017-06-10 15:29:38,212 remote           L0197 DEBUG| [104.196.12.98] [stdout] Jun 10 15:29:38 info   |  [shard 4] compaction_manager - Asked to stop
2017-06-10 15:29:38,213 remote           L0197 DEBUG| [104.196.12.98] [stdout] Jun 10 15:29:38 info   |  [shard 3] compaction_manager - Asked to stop
2017-06-10 15:29:38,217 remote           L0197 DEBUG| [104.196.12.98] [stdout] Jun 10 15:29:38 info   |  [shard 5] compaction_manager - Asked to stop
Start ... scylla ...

```

**Comment by amoskong** [comment] 2017-06-10 16:41
![fireshot capture 62 - grafana - scylla per server metrics 1 _ - http___35 196 3 244_3000_dashboard](https://user-images.githubusercontent.com/309708/27004604-4bd62ab6-4e3e-11e7-8874-53fa36f5e524.png)

**Comment by avikivity** [comment] 2017-06-10 20:27
That's by design. I don't think we want Scylla restarting after a serious event like running out of space.

It should be possible to restore service via a nodetool command, though.

**Comment by amoskong** [comment] 2017-06-10 23:27
Some subtasks are stop in ENOSPC, is it possible to just restart those subtasks when disk has free space?  not restart the scylla-server service.

When QEMU-KVM VM touches a ENOSPC error, it will paused to avoid to read/write storage. It's automatically resume when free space is added.

**Comment by amoskong** [comment] 2017-06-11 02:53
In another test, when all SPACE is taken by dd, and all c-s processes in loaders exited.
But I didn't see any error from all db nodes.

Configure:
- 3 * db_nodes (n1-highmem-16)
- 4 * loaders (n1-standard-2)
- 1 * monitor (n1-standard-1)

C-S cmdline:
- totally has 8 c-s executions on 4 loaders:
- cassandra-stress write no-warmup cl=QUORUM duration=600m -schema keyspace=keyspace1 'replication(factor=3)' -port jmx=6868 -mode cql3 native -rate threads=100 -errors ignore -pop seq=1..10000000 -node node1_ip

**Comment by avikivity** [comment] 2017-06-11 08:59
> Some subtasks are stop in ENOSPC, is it possible to just restart those subtasks when disk has free space? not restart the scylla-server service.

It is possible, just not implemented. I think it's a good idea, but not critical.

> When QEMU-KVM VM touches a ENOSPC error, it will paused to avoid to read/write storage. It's automatically resume when free space is added.

That is dangerous. The administrator may want to perform additional changes while adding storage, it's best to wait for a green light instead of resuming automatically and interfering.

An example reason is that the admin is moving the files to a different volume and then wants to mount the new volume over the old one. In this case starting before the final step causes data loss.

**Comment by avikivity** [comment] 2017-06-11 09:00
> In another test, when all SPACE is taken by dd, and all c-s processes in loaders exited.
But I didn't see any error from all db nodes.

What was the problem here?

**Comment by amoskong** [comment] 2017-06-14 01:22
c-s raising error is fine, but it should not exit.  I'm doing more test for enospc, will update results later.

**Comment by slivne** [comment] 2018-01-21 11:49
@amoskong I am closing this - we will not recover service once there is space - if there is still an issue please open one

**Closed by slivne** 2018-01-21 11:49 UTC
