### ISSUE TITLE
seastar reactor iocb pool underflow and crash after ENOSPC

### ISSUE THREAD

**Issue by roydahan** [scylladb/scylla#5443] opened 2019-12-09 14:11 UTC
*Installation details*
Scylla version (or git commit hash): 3.2.rc2-0.20191208.2ff26d11608
Cluster size: 6
OS (RHEL/CentOS/Ubuntu/AWS AMI): ami-04d02956870bdc491
Detected by: longevity-3h-10gb
Test ID: 0dcc3c0f-5b16-4307-95f3-0a3ae0c2791c

Decoded Backtrace:
```
[centos@ip-172-30-0-252 bin]$ addr2line -Cpfie /usr/lib/debug/opt/scylladb/libexec/scylla-3.2.rc2-0.20191208.2ff26d11608.el7.x86_64.debug

?? ??:0

?? ??:0
0x0000000002ac4432
0x0000000002a3eb0b
0x0000000002a3ee05
0x0000000002a3eea0
0x00007fb7222e2e7f
/libreloc/libc.so.6+0x0000000000037e74
/libreloc/libc.so.6+0x0000000000022894
/libreloc/libc.so.6+0x0000000000022768
/libreloc/libc.so.6+0x0000000000030565
0x0000000002a3a67e
0x0000000002a8b2d8
0x00000000029c79f2
0x0000000002a76334
0x0000000002a76a95
0x0000000002a3b241
0x0000000002a3b44f
0x0000000002aa3945
0x00000000029e803c
0x00000000029e8d2e
0x00000000007938a1
/libreloc/libc.so.6+0x0000000000023f32
0x00000000007e21fdvoid seastar::backtrace<seastar::backtrace_buffer::append_backtrace()::{lambda(seastar::frame)#1}>(seastar::backtrace_buffer::append_backtrace()::{lambda(seastar::frame)#1}&&) at /usr/include/c++/9/ext/new_allocator.h:105
seastar::backtrace_buffer::append_backtrace() at /usr/include/c++/9/ext/new_allocator.h:105
 (inlined by) print_with_backtrace at /data/jenkins/workspace/scylla-3.2/build/scylla/seastar/src/core/reactor.cc:701
seastar::print_with_backtrace(char const*) at /usr/include/c++/9/ext/new_allocator.h:105
sigabrt_action at /usr/include/c++/9/ext/new_allocator.h:105
 (inlined by) operator() at /data/jenkins/workspace/scylla-3.2/build/scylla/seastar/src/core/reactor.cc:3360
 (inlined by) _FUN at /data/jenkins/workspace/scylla-3.2/build/scylla/seastar/src/core/reactor.cc:3356
?? ??:0
?? ??:0
?? ??:0
?? ??:0
?? ??:0
boost::container::vector<seastar::internal::linux_abi::iocb*, boost::container::dtl::static_storage_allocator<seastar::internal::linux_abi::iocb*, 1024ul>, void>::back() at /usr/include/c++/9/ext/new_allocator.h:105
 (inlined by) std::stack<seastar::internal::linux_abi::iocb*, boost::container::static_vector<seastar::internal::linux_abi::iocb*, 1024ul> >::top() at /usr/include/c++/9/bits/stl_stack.h:209
 (inlined by) seastar::reactor::submit_io(seastar::io_desc*, seastar::noncopyable_function<void (seastar::internal::linux_abi::iocb&)>) at /data/jenkins/workspace/scylla-3.2/build/scylla/seastar/src/core/reactor.cc:1404
seastar::reactor::fdatasync(int) at /usr/include/c++/9/ext/new_allocator.h:105
seastar::posix_file_impl::flush() at /data/jenkins/workspace/scylla-3.2/build/scylla/seastar/include/seastar/core/future.hh:944
seastar::file::flush() at /usr/include/c++/9/ext/new_allocator.h:105
 (inlined by) operator() at /data/jenkins/workspace/scylla-3.2/build/scylla/seastar/src/core/reactor.cc:3976
 (inlined by) do_with<seastar::file, seastar::sync_directory(seastar::sstring)::<lambda(seastar::file)>::<lambda(seastar::file&)> > at /data/jenkins/workspace/scylla-3.2/build/scylla/seastar/include/seastar/core/do_with.hh:94
 (inlined by) operator() at /data/jenkins/workspace/scylla-3.2/build/scylla/seastar/src/core/reactor.cc:3979
 (inlined by) apply at /data/jenkins/workspace/scylla-3.2/build/scylla/seastar/include/seastar/core/apply.hh:36
 (inlined by) apply<seastar::sync_directory(seastar::sstring)::<lambda(seastar::file)>, seastar::file> at /data/jenkins/workspace/scylla-3.2/build/scylla/seastar/include/seastar/core/apply.hh:44
 (inlined by) apply<seastar::sync_directory(seastar::sstring)::<lambda(seastar::file)>, seastar::file> at /data/jenkins/workspace/scylla-3.2/build/scylla/seastar/include/seastar/core/future.hh:1537
operator() at /usr/include/c++/9/ext/new_allocator.h:105
 (inlined by) run_and_dispose at /data/jenkins/workspace/scylla-3.2/build/scylla/seastar/include/seastar/core/future.hh:424
seastar::reactor::run_tasks(seastar::reactor::task_queue&) at /usr/include/c++/9/ext/new_allocator.h:105
seastar::reactor::run_some_tasks() at /usr/include/c++/9/ext/new_allocator.h:105
seastar::reactor::run_some_tasks() at /usr/include/c++/9/ext/new_allocator.h:105
 (inlined by) seastar::reactor::run() at /data/jenkins/workspace/scylla-3.2/build/scylla/seastar/src/core/reactor.cc:2644
seastar::app_template::run_deprecated(int, char**, std::function<void ()>&&) at /data/jenkins/workspace/scylla-3.2/build/scylla/seastar/include/seastar/core/future.hh:944
seastar::app_template::run(int, char**, std::function<seastar::future<int> ()>&&) at /data/jenkins/workspace/scylla-3.2/build/scylla/seastar/include/seastar/core/future.hh:944
main at crtstuff.c:?
?? ??:0

_start at ??:?
```

coredump:
```
corefile_url=
https://storage.cloud.google.com/upload.scylladb.com/core.scylla.996.8c1f6e6372fc4a908bee28edbb2b4f85.39178.1575883567000000/core.scylla.996.8c1f6e6372fc4a908bee28edbb2b4f85.39178.1575883567000000.gz
backtrace=           PID: 39178 (scylla)
           UID: 996 (scylla)
           GID: 1001 (scylla)
        Signal: 6 (ABRT)
     Timestamp: Mon 2019-12-09 09:26:07 UTC (2min 7s ago)
  Command Line: /usr/bin/scylla --blocked-reactor-notify-ms 500 --abort-on-lsa-bad-alloc 1 --abort-on-seastar-bad-alloc --abort-on-internal-error 1 --log-to-syslog 1 --log-to-stdout 0 --default-log-level info --network-stack posix --io-properties-file=/etc/scylla.d/io_properties.yaml --cpuset 1-7,9-15
    Executable: /opt/scylladb/libexec/scylla
 Control Group: /scylla.slice/scylla-server.slice/scylla-server.service
          Unit: scylla-server.service
         Slice: scylla-server.slice
       Boot ID: 8c1f6e6372fc4a908bee28edbb2b4f85
    Machine ID: df877a200226bc47d06f26dae0736ec9
      Hostname: ip-172-30-0-252.ec2.internal
      Coredump: /var/lib/systemd/coredump/core.scylla.996.8c1f6e6372fc4a908bee28edbb2b4f85.39178.1575883567000000
       Message: Process 39178 (scylla) of user 996 dumped core.
                
                Stack trace of thread 39178:
                #0  0x00007fb7218fee75 raise (libc.so.6)
                #1  0x00007fb7218e995e abort (libc.so.6)
                #2  0x00007fb7218e9769 __assert_fail_base.cold (libc.so.6)
                #3  0x00007fb7218f7566 __assert_fail (libc.so.6)
                #4  0x0000000002a3a67f _ZN5boost9container6vectorIPN7seastar8internal9linux_abi4iocbENS0_3dtl24static_storage_allocatorIS6_Lm1024EEEvE4backEv (scylla)
                #5  0x0000000002a8b2d9 _ZN7seastar7reactor9fdatasyncEi (scylla)
                #6  0x00000000029c79f3 _ZN7seastar15posix_file_impl5flushEv (scylla)
                #7  0x0000000002a76335 _ZN7seastar4file5flushEv (scylla)
                #8  0x0000000002a76a96 operator() (scylla)
                #9  0x0000000002a3b242 _ZN7seastar7reactor9run_tasksERNS0_10task_queueE (scylla)
                #10 0x0000000002a3b450 _ZN7seastar7reactor14run_some_tasksEv (scylla)
                #11 0x0000000002aa3946 _ZN7seastar7reactor14run_some_tasksEv (scylla)
                #12 0x00000000029e803d _ZN7seastar12app_template14run_deprecatedEiPPcOSt8functionIFvvEE (scylla)
                #13 0x00000000029e8d2f _ZN7seastar12app_template3runEiPPcOSt8functionIFNS_6futureIJiEEEvEE (scylla)
                #14 0x00000000007938a2 main (scylla)
                #15 0x00007fb7218eaf33 __libc_start_main (libc.so.6)
                #16 0x00000000007e21fe _start (scylla)
                
                Stack trace of thread 39205:
                #0  0x00007fb7222e1bec read (libpthread.so.0)
                #1  0x0000000002e7b8c6 _ZN7seastar11thread_pool4workENS_13basic_sstringIcjLj15ELb1EEE (scylla)
                #2  0x0000000002e7bbb2 operator() (scylla)
                #3  0x0000000002a1dd9e _ZNKSt8functionIFvvEEclEv (scylla)
                #4  0x00007fb7222d85a2 start_thread (libpthread.so.0)
                #5  0x00007fb7219c2303 __clone (libc.so.6)
                
                Stack trace of thread 39190:
                #0  0x00007fb721a2633c __memmove_avx_unaligned_erms (libc.so.6)
                #1  0x0000000000eeb83a _ZN8sstables17mp_row_consumer_m23consume_partition_startENS_8key_viewENS_13deletion_timeE (scylla)
                #2  0x0000000000ee2271 _ZN8sstables27data_consume_rows_context_m16do_process_stateERN7seastar16temporary_bufferIcEE (scylla)
                #3  0x0000000000ee407b _ZN7seastar6repeatIZNS_12input_streamIcE7consumeISt17reference_wrapperIN8sstables27data_consume_rows_context_mEEEENS_6futureIJEEEOT_EUlvE_EES9_SA_ (scylla)
                #4  0x0000000000f1a210 _ZZZN8sstables23sstable_mutation_readerINS_27data_consume_rows_context_mENS_17mp_row_consumer_mEE11fill_bufferENSt6chrono10time_pointIN7seastar12lowres_clockENS4_8durationIlSt5ratioILl1ELl1000EEEEEEENKUlvE1_clEvENKUlvE0_clEv (scylla)
                #5  0x0000000000f20860 _ZN7seastar8do_untilIZN8sstables23sstable_mutation_readerINS1_27data_consume_rows_context_mENS1_17mp_row_consumer_mEE11fill_bufferENSt6chrono10time_pointINS_12lowres_clockENS6_8durationIlSt5ratioILl1ELl1000EEEEEEEUlvE1_ZNS5_11fill_bufferESD_EUlvE0_EENS_6futureIJEEET0_T_ (scylla)
                #6  0x0000000000f21ad5 _ZN8sstables23sstable_mutation_readerINS_27data_consume_rows_context_mENS_17mp_row_consumer_mEE11fill_bufferENSt6chrono10time_pointIN7seastar12lowres_clockENS4_8durationIlSt5ratioILl1ELl1000EEEEEE (scylla)
                #7  0x0000000000cae8b7 _ZN22mutation_reader_merger11prepare_oneENSt6chrono10time_pointIN7seastar12lowres_clockENS0_8durationIlSt5ratioILl1ELl1000EEEEEENS_29reader_and_last_fragment_kindENS2_10bool_classINS_20reader_galloping_tagEEE (scylla)
                #8  0x0000000000caf95e _ZN22mutation_reader_merger12prepare_nextENSt6chrono10time_pointIN7seastar12lowres_clockENS0_8durationIlSt5ratioILl1ELl1000EEEEEE (scylla)
                #9  0x0000000000cb12be _ZN22mutation_reader_mergerclENSt6chrono10time_pointIN7seastar12lowres_clockENS0_8durationIlSt5ratioILl1ELl1000EEEEEE (scylla)
                #10 0x0000000000cb34f1 _ZN7seastar8futurizeINS_6futureIJNS_10bool_classINS_18stop_iteration_tagEEEEEEE5applyIRZN24combined_mutation_reader11fill_bufferENSt6chrono10time_pointINS_12lowres_clockENS9_8durationIlSt5ratioILl1ELl1000EEEEEEEUlvE_JEEES5_OT_DpOT0_ (scylla)
                #11 0x0000000000cb3c01 _ZN24combined_mutation_reader11fill_bufferENSt6chrono10time_pointIN7seastar12lowres_clockENS0_8durationIlSt5ratioILl1ELl1000EEEEEE (scylla)
                #12 0x0000000000f4fa11 _ZN20flat_mutation_reader4impl26consume_pausable_in_threadISt17reference_wrapperINS0_16consumer_adapterI35stable_flattened_mutations_consumerI22compact_for_compactionIN8sstables25compacting_sstable_writerE33
```

*download_instructions*:
gsutil cp gs://upload.scylladb.com/core.scylla.996.8c1f6e6372fc4a908bee28edbb2b4f85.39178.1575883567000000/core.scylla.996.8c1f6e6372fc4a908bee28edbb2b4f85.39178.1575883567000000.gz .
gunzip /var/lib/systemd/coredump/core.scylla.996.8c1f6e6372fc4a908bee28edbb2b4f85.39178.1575883567000000.gz

*Restore Monitor Stack command:* 
$ hydra investigate show-monitor 0dcc3c0f-5b16-4307-95f3-0a3ae0c2791c
*Show all stored logs command:* 
$ hydra investigate show-logs 0dcc3c0f-5b16-4307-95f3-0a3ae0c2791c

**Comment by roydahan** [comment] 2019-12-09 14:12
@bhalevy this is new on 3.2, maybe we didn't completely solve the original issue as part of #4877

**Comment by fruch** [comment] 2019-12-09 17:26
Maybe  #4877 fix wasn't backported to 3.2 ?

**Comment by bhalevy** [comment] 2019-12-09 17:26
@roydahan It looks nothing like #4877
@avikivity it looks like `reactor::submit_io` ran out of `_free_iocbs`, no?

**Comment by avikivity** [comment] 2019-12-10 14:03
Patch: https://groups.google.com/d/msg/seastar-dev/Oj-QgDLReL4/s4y41uLGAgAJ

**Comment by avikivity** [comment] 2019-12-10 14:04
This is a regression due to a bug in aio fsync, a new seastar feature.

**Comment by slivne** [comment] 2019-12-12 10:23
we have seen issues like this in 3.1 as well - once the fix is merged lets consider backporting to 3.1

**Comment by avikivity** [comment] 2019-12-12 10:25
3.1 doesn't have this code.

**Comment by avikivity** [comment] 2019-12-12 10:26
@slivne no need to add the Backport candidate label, Jenkins does this automatically.

**Closed** 2019-12-12 11:24 UTC
Labels: Backport candidate, longevity, showstopper

**Comment by avikivity** [comment] 2019-12-24 16:07
Already backported.
