### ISSUE TITLE
Add backpressure mechanism for memtable flush

### ISSUE THREAD

**Issue by raphaelsc** [scylladb/scylla#10308] opened 2022-03-31 12:33 UTC
Flush generation rate can be higher than compaction rate. Therefore, compaction falls behind significantly, possibly leading to thousands of files in a table, possibly resulting in an OOM. To prevent this from happening, let's apply a back pressure to memtable flush, such that we'll slow down flush, allowing compaction to keep up.

**Comment by raphaelsc** [comment] 2022-03-31 12:34
@bhalevy FYI

**Comment by bhalevy** [comment] 2022-03-31 12:42
Cc @mikolajsieluzycki. Let's add this to your queue

**Comment by vladzcloudius** [comment] 2022-03-31 14:25
I don't understand how this all may be possible.
The write rate into system_schema tables is almost zero (especially compared to regular data tables) and the amount of data in these tables is tiny as well.
So, the definition of the problem makes little sense to me.

I have a feeling that this proposal suggests a fix for a symptom instead of fixing a root cause.

@bhalevy @raphaelsc

**Comment by raphaelsc** [comment] 2022-03-31 14:45
> I don't understand how this all may be possible. The write rate into system_schema tables is almost zero (especially compared to regular data tables) and the amount of data in these tables is tiny as well. So, the definition of the problem makes little sense to me.
> 
> I have a feeling that this proposal suggests a fix for a symptom instead of fixing a root cause.
> 
> @bhalevy @raphaelsc

Backpressure is not for fixing the root cause. It's a defensive action, to when flush rate is bigger than compaction rate. So we'll prevent # of files from growing to the sky and then having an OOM.  We're not adding this and forgetting about all the rest. If there's a problem in schema disagreement, that causes schema tables to be flush very frequently in a short time time, that must be fixed. If there's an inefficiency in compaction layer like https://github.com/scylladb/scylla/commit/52302c3238ce11b36439d7e7330e5642e04e8eb1 (I think that may be causing some of the trouble), then it must be fixed too.

This proposal is not a panacea, or fixes for the root causes, but it's a mechanism for increasing resiliency.

**Comment by raphaelsc** [comment] 2022-03-31 14:52
> @vladzcloudius
> 
> > The write rate into system_schema tables is almost zero (especially compared to regular data tables) and the amount of data in these tables is tiny as well.
> 
> It seems like due to a bug in schema agreement these were created at a high rate.
> 
> #4076 was supposed to apply the backpressure if compaction doesn't keep up with the rate of generating new tables, but in the system_schema case, since the sstables are tiny, the concern is that just increasing compaction shares won't be enough, and we need to apply backpressure on flushing.
> 
> That said, I'm not sure why that should be restricted to system_schema rather being a generic backpressure mechanism in any table.

The restriction was suggested by Avi for simplicity, as a generic backpressure mechanism takes more effort (not just a hard stop on flushes), but we can pivot this issue to a generic solution.

For a complete solution, we'll have to fix https://github.com/scylladb/scylla/issues/4076. There's a flush_controller that perhaps can be used to slow down flush. With compaction speeding up, and flush slowing down, backlog will eventually drop to zero.

**Comment by vladzcloudius** [comment] 2022-03-31 18:04
> That said, I'm not sure why that should be restricted to system_schema rather being a generic backpressure mechanism in any table.

If this idea makes sense then it makes sense in general and not only for system_xxx - I agree.

Preventing a memtable flush would mean a corresponding memtable can potentially continue growing and eventually causing OOM due to that. I have a feeling that the condition for this backpressure should be more complex than in an opening message.

If you flush too often - you'll OOM due to too many files.
If you don't flush for too long - you'll OOM due to memtable growing too big.

Working in a collaboration with a 'memtable flush contoller' indeed sounds like a good direction.

**Comment by denesb** [comment] 2022-04-08 12:27
AFAIK memtables can consume a fixed % of the shard's memory, once that is filled, writes to them will be blocked until some memory is freed. We have to make sure these blocked writes can time out.
One more thing to consider is blocked flushes on system tables. Compaction can write to system tables during its operation (`large_*` tables, `compaction_history`). If we block writes to those, we might create a deadlock: we can't write to memtables because compaction doesn't make progress, and compaction is blocked because it can't write to memtables.

**Comment by raphaelsc** [comment] 2022-04-09 02:52
> AFAIK memtables can consume a fixed % of the shard's memory, once that is filled, writes to them will be blocked until some memory is freed. We have to make sure these blocked writes can time out. One more thing to consider is blocked flushes on system tables. Compaction can write to system tables during its operation (`large_*` tables, `compaction_history`). If we block writes to those, we might create a deadlock: we can't write to memtables because compaction doesn't make progress, and compaction is blocked because it can't write to memtables.

Good points.

**Comment by tgrabiec** [comment] 2022-04-27 10:51
Duplicate of https://github.com/scylladb/scylla/issues/4116 ?

**Closed** 2022-04-27 10:58 UTC
Labels: backpressure
