### ISSUE TITLE
repeat "gossip - Fail to send EchoMessage" after unexpected eof on a server while reading data: expected 579 got 517

### ISSUE THREAD

**Issue by ban4785** [scylladb/scylla#1996] opened 2017-01-05 02:17 UTC
*Installation details*
Scylla version (or git commit hash): 1.4.1
Cluster size: 3 node
OS (RHEL/CentOS/Ubuntu/AWS AMI): CentOs 7.2

*Hardware details (for performance issues)*          Delete if unneeded
Platform (physical/VM/cloud instance type/docker): physical
Hardware: sockets= cores= hyperthreading= memory : 10G Network=48cores=yes=192G
Disks: (SSD/HDD, count) : 2SSD(raid 0)

i got title message while write only load test(consistency one).
![eofmetric](https://cloud.githubusercontent.com/assets/20348151/21666174/72a213c0-d333-11e6-8711-dc06a14ec756.png) -> Grafana metric

time line
14:50 -> load start
15:41 -> eof message
15:41 ~  -> repeat Fail to send EchoMessage per sec
17:10 -> load end
17:13 -> end of Fail to send EchoMessage

is there any reason echo message ends after loading?

/var/log/messages
Jan  4 15:40:31 dbtest02 scylla: [shard 0] gossip - InetAddress 70.60.31.134 is now DOWN, status = NORMAL
Jan  4 15:40:33 dbtest02 scylla: [shard 0] gossip - InetAddress 70.60.31.134 is now UP, status = NORMAL
Jan  4 15:40:34 dbtest02 scylla: [shard 0] gossip - do_gossip_to_live_member: Favor newly added node 70.60.31.134
Jan  4 15:41:33 dbtest02 scylla: [shard 0] gossip - InetAddress 70.60.31.134 is now DOWN, status = NORMAL
Jan  4 15:41:33 dbtest02 scylla: [shard 0] gossip - InetAddress 70.60.31.132 is now DOWN, status = NORMAL
Jan  4 15:41:34 dbtest02 scylla: [shard 0] gossip - InetAddress 70.60.31.134 is now UP, status = NORMAL
Jan  4 15:41:34 dbtest02 scylla: [shard 0] gossip - InetAddress 70.60.31.134 is now UP, status = NORMAL
Jan  4 15:41:34 dbtest02 scylla: [shard 0] gossip - InetAddress 70.60.31.134 is now UP, status = NORMAL
Jan  4 15:41:34 dbtest02 scylla: [shard 0] gossip - InetAddress 70.60.31.134 is now UP, status = NORMAL
Jan  4 15:41:34 dbtest02 scylla: [shard 0] gossip - InetAddress 70.60.31.134 is now UP, status = NORMAL
Jan  4 15:41:34 dbtest02 scylla: [shard 0] gossip - InetAddress 70.60.31.134 is now UP, status = NORMAL
Jan  4 15:41:34 dbtest02 scylla: [shard 0] gossip - InetAddress 70.60.31.134 is now UP, status = NORMAL

> Jan  4 15:41:34 dbtest02 scylla: [shard 0] rpc - client 70.60.31.132: unexpected eof on a server while reading data: expected 579 got 517

Jan  4 15:41:35 dbtest02 scylla: [shard 0] gossip - do_gossip_to_live_member: Favor newly added node 70.60.31.134
Jan  4 15:41:37 dbtest02 scylla: [shard 0] gossip - Fail to send EchoMessage to 70.60.31.132:0: rpc::timeout_error (rpc call timed out)
Jan  4 15:41:37 dbtest02 scylla: [shard 0] gossip - Fail to send EchoMessage to 70.60.31.132:0: rpc::timeout_error (rpc call timed out)
Jan  4 15:41:37 dbtest02 scylla: [shard 0] gossip - Fail to send EchoMessage to 70.60.31.132:0: rpc::timeout_error (rpc call timed out)
Jan  4 15:41:37 dbtest02 scylla: [shard 0] gossip - Fail to send EchoMessage to 70.60.31.132:0: rpc::timeout_error (rpc call timed out)
Jan  4 15:41:37 dbtest02 scylla: [shard 0] gossip - Fail to send EchoMessage to 70.60.31.132:0: rpc::timeout_error (rpc call timed out)
Jan  4 15:41:37 dbtest02 scylla: [shard 0] gossip - Fail to send EchoMessage to 70.60.31.132:0: rpc::timeout_error (rpc call timed out)

....

Jan  4 17:13:12 dbtest02 scylla: [shard 0] gossip - Fail to send EchoMessage to 70.60.31.132:0: rpc::timeout_error (rpc call timed out)
Jan  4 17:13:13 dbtest02 scylla: [shard 0] gossip - Fail to send EchoMessage to 70.60.31.132:0: rpc::timeout_error (rpc call timed out)
Jan  4 17:13:13 dbtest02 scylla: [shard 7] rpc - client 70.60.31.134: server connection dropped: read: Connection reset by peer
Jan  4 17:13:14 dbtest02 scylla: [shard 4] rpc - client 70.60.31.134: server connection dropped: read: Connection reset by peer
Jan  4 17:13:14 dbtest02 scylla: [shard 0] gossip - InetAddress 70.60.31.132 is now UP, status = NORMAL
Jan  4 17:13:14 dbtest02 scylla: [shard 0] gossip - InetAddress 70.60.31.132 is now UP, status = NORMAL
Jan  4 17:13:14 dbtest02 scylla: [shard 0] gossip - InetAddress 70.60.31.132 is now UP, status = NORMAL
-> echo message end after wirte load end time

**Comment by gleb-cloudius** [comment] 2017-01-05 08:24
Is replication factor 3? It looks like networking cannot keep up
and at some point (at 15:41) one node (dbtest02) lose connectivity
to another (70.60.31.132) and as a result stop replicating there which
reduces demand on networking and you can see it in the graphs that at
15:41 networking metrics are going down and amount of background writes
is going down too.

The question is why 10G networking cannot keep up. The bandwidth is
pretty low even before 15:41. Do you have iptables loaded? Firewall may
reduce network performance even when not used.

--
			Gleb.

**Comment by infordb** [comment] 2017-01-05 10:04
@gleb-cloudius 

1. iptables unloaded on all nodes

[root@dbtest02 ~]# systemctl status iptables.service
● iptables.service
   Loaded: not-found (Reason: No such file or directory)
   Active: inactive (dead)

2. Bandwidth test results are sufficient with iperf

[root@dbtest02 ~]# iperf -c 70.60.31.132 -t 60
------------------------------------------------------------
Client connecting to 70.60.31.132, TCP port 5001
TCP window size: 85.0 KByte (default)
------------------------------------------------------------
[  3] local 70.60.31.133 port 27236 connected with 70.60.31.132 port 5001
[ ID] Interval       Transfer     Bandwidth
[  3]  0.0-60.0 sec  61.2 GBytes  8.76 Gbits/sec

and I don't know why total requests and reactor graph heavily fluctuated ??

**Comment by gleb-cloudius** [comment] 2017-01-05 10:29
iperf uses much large packets, may be Linux has problem handling all the
networking interrupts. Are NIC interrupts distributed between cores?
What output of "cat /proc/interrupts" says?

--
			Gleb.

**Comment by ban4785** [comment] 2017-01-06 07:50
scylladb use -> cpu 0,1,2,3,12,13,14,15
scylladb use -> network dev :  enp130s0f0
local 70.60.31.132 /proc/interrupts info file
[interruptinfo.zip](https://github.com/scylladb/scylla/files/689238/interruptinfo.zip)

same case 
![samecase](https://cloud.githubusercontent.com/assets/20348151/21711096/3313bd82-d430-11e6-8cf4-34c855582356.png)

**Comment by gleb-cloudius** [comment] 2017-01-06 11:27
Can you also provide /proc/cpuinfo? What do you mean by "same case"?
Graphs looks very different. It looks like the load was very bursty.

--
			Gleb.

**Comment by ban4785** [comment] 2017-01-09 01:41
i mean same business program in same nodes(3node 3replication)
added file is 48core hyperthreading server(3server same spec)
[cpuinfo.txt](https://github.com/scylladb/scylla/files/692589/cpuinfo.txt)

**Comment by gleb-cloudius** [comment] 2017-01-09 10:40
According to /proc/interrupts some cpus that run ScyllaDB also handle
networking interrupts (cpus 12,13,14,15). Since you have enough free
cores can you move Scylla to cores that do not handle networking
interrupts?

--
			Gleb.

**Comment by infordb** [comment] 2017-01-09 15:12
@gleb-cloudius 
If the total number of cores is 8 and all can be  assigned to scylla
Is it a good idea to allocate only 7 cores to the scylla except for one core for network processing ?

**Comment by gleb-cloudius** [comment] 2017-01-10 07:53
On Mon, Jan 09, 2017 at 07:12:34AM -0800, Junghyun Park wrote:
> @gleb-cloudius 
> If the total number of cores is 8 and all can be  assigned to scylla
> Is it a good idea to allocate only 7 cores to the scylla except for one core for network processing ?
> 
Yes, that what we do on AWS instances. Unless you have a NIC with 8
queues, then it may be better to redistribute HW interrupts between all
cores equally.

--
			Gleb.

**Comment by slivne** [comment] 2017-01-10 11:24
@infordb , @ban4785 I am at lost here.

The machine 24 physical cores and 48 hyperthreads - why are you limiting scylla to run on 8 ?
Are you running on this machine somthing else - an application as well ?

If you are running an application as well - then please note that you need to analyze if the blame for networking/disk issues are related to the additional deployed application and what it does (an easy way to "debug" this is to remove the application from the host - just for testing - and see if you still face the same issues). Please also note that scylla_setup tunning for networking / disk assumes that scylla is the only application running on the host.

With regards to @gleb-cloudius answer - if the machine has 8/16 physical cores we use one core for interrupts and run scylla on the rest in AWS because of the limited # of queues - yet it does not seem relevant to the machine you have at hand in this issue.

**Comment by infordb** [comment] 2017-01-20 02:50
We limited resources to meet customer requirements
and we run scylla only on this machine..

**Comment by slivne** [comment] 2017-12-03 11:28
Closing this issue - if this reproduces on newer releases please reopen with the version number.

**Closed by slivne** 2017-12-03 11:28 UTC
