### ISSUE TITLE
scylla fails with sigabrt

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla#735] opened 2015-12-30 17:00 UTC
using

[fedora@ip-172-31-45-250 ~]$ rpm -qa | grep scylla | grep -i develop
scylla-server-development-20151229.ebebaa5.fc22.x86_64
scylla-server-debuginfo-development-20151229.ebebaa5.fc22.x86_64

```
.
.

Dec 30 15:43:32 ip-172-31-45-250 scylla_run[7690]: Starting listening for CQL clients on 0.0.0.0:9042...
.
.

Dec 30 15:43:36 ip-172-31-45-250 scylla[7707]:  [shard 0] gossip - Node 172.31.46.10 has restarted, now UP
Dec 30 15:43:36 ip-172-31-45-250 scylla[7707]:  [shard 0] gossip - InetAddress 172.31.46.10 is now UP
Dec 30 15:43:36 ip-172-31-45-250 scylla[7707]:  [shard 0] storage_service - Node 172.31.46.10 state jump to normal
Dec 30 15:43:36 ip-172-31-45-250 scylla[7707]:  [shard 0] gossip - Node 172.31.46.11 has restarted, now UP
Dec 30 15:43:36 ip-172-31-45-250 scylla[7707]:  [shard 0] gossip - InetAddress 172.31.46.11 is now UP
Dec 30 15:43:36 ip-172-31-45-250 scylla[7707]:  [shard 0] storage_service - Node 172.31.46.11 state jump to normal
Dec 30 15:43:36 ip-172-31-45-250 scylla[7707]:  [shard 0] gossip - Node 172.31.46.12 has restarted, now UP
Dec 30 15:43:36 ip-172-31-45-250 scylla[7707]:  [shard 0] gossip - InetAddress 172.31.46.12 is now UP
Dec 30 15:43:36 ip-172-31-45-250 scylla[7707]:  [shard 0] storage_service - Node 172.31.46.12 state jump to normal
Dec 30 15:43:36 ip-172-31-45-250 scylla[7707]:  [shard 0] gossip - Node 172.31.46.13 has restarted, now UP
Dec 30 15:43:36 ip-172-31-45-250 scylla[7707]:  [shard 0] gossip - InetAddress 172.31.46.13 is now UP
Dec 30 15:43:36 ip-172-31-45-250 scylla[7707]:  [shard 0] storage_service - Node 172.31.46.13 state jump to normal
Dec 30 15:43:36 ip-172-31-45-250 scylla[7707]:  [shard 0] storage_service - Node 172.31.46.9 state jump to normal
Dec 30 15:43:36 ip-172-31-45-250 scylla[7707]:  [shard 0] storage_service - Node 172.31.46.9 state jump to normal
Dec 30 15:43:36 ip-172-31-45-250 scylla[7707]:  [shard 1] compaction - Compacted 4 sstables to [/var/lib/scylla/data/system/peers-37f71aca7dc2383ba70672528af04d4f/system-peers-ka-289-Data.db:level=0, ]. 73207 by
Dec 30 15:43:36 ip-172-31-45-250 scylla[7707]:  [shard 0] gossip - Node 172.31.46.14 has restarted, now UP
Dec 30 15:43:36 ip-172-31-45-250 scylla[7707]:  [shard 0] gossip - Node 172.31.46.15 has restarted, now UP
Dec 30 15:43:36 ip-172-31-45-250 scylla[7707]:  [shard 0] gossip - InetAddress 172.31.46.14 is now UP
Dec 30 15:43:36 ip-172-31-45-250 scylla[7707]:  [shard 0] storage_service - Node 172.31.46.14 state jump to normal
Dec 30 15:43:36 ip-172-31-45-250 scylla[7707]:  [shard 0] gossip - InetAddress 172.31.46.15 is now UP
Dec 30 15:43:36 ip-172-31-45-250 scylla[7707]:  [shard 0] storage_service - Node 172.31.46.15 state jump to normal
Dec 30 15:43:36 ip-172-31-45-250 scylla[7707]:  [shard 0] gossip - InetAddress 172.31.46.15 is now UP
Dec 30 15:43:36 ip-172-31-45-250 scylla[7707]:  [shard 0] gossip - Node 172.31.46.16 has restarted, now UP
Dec 30 15:43:36 ip-172-31-45-250 scylla[7707]:  [shard 0] gossip - InetAddress 172.31.46.16 is now UP
Dec 30 15:43:36 ip-172-31-45-250 scylla[7707]:  [shard 0] storage_service - Node 172.31.46.16 state jump to normal
Dec 30 15:43:36 ip-172-31-45-250 scylla[7707]:  [shard 2] compaction - Compacting [/var/lib/scylla/data/system/peers-37f71aca7dc2383ba70672528af04d4f/system-peers-ka-282-Data.db:level=0, /var/lib/scylla/data/sys
Dec 30 15:43:37 ip-172-31-45-250 scylla[7707]:  [shard 1] compaction - Compacting [/var/lib/scylla/data/system/peers-37f71aca7dc2383ba70672528af04d4f/system-peers-ka-289-Data.db:level=0, /var/lib/scylla/data/sys
Dec 30 15:43:37 ip-172-31-45-250 scylla[7707]:  [shard 0] storage_service - Node 172.31.46.9 state jump to normal
Dec 30 15:43:37 ip-172-31-45-250 scylla[7707]:  [shard 2] compaction - Compacted 4 sstables to [/var/lib/scylla/data/system/peers-37f71aca7dc2383ba70672528af04d4f/system-peers-ka-310-Data.db:level=0, ]. 73458 by
Dec 30 15:43:37 ip-172-31-45-250 scylla[7707]:  [shard 2] compaction - Compacting [/var/lib/scylla/data/system/peers-37f71aca7dc2383ba70672528af04d4f/system-peers-ka-298-Data.db:level=0, /var/lib/scylla/data/sys
Dec 30 15:43:37 ip-172-31-45-250 scylla-jmx[7691]: getDroppedMessages()
Dec 30 15:43:37 ip-172-31-45-250 scylla-jmx[7691]: Dec 30, 2015 3:43:37 PM org.apache.cassandra.net.MessagingService log
Dec 30 15:43:37 ip-172-31-45-250 scylla-jmx[7691]: INFO:  getDroppedMessages()
Dec 30 15:43:37 ip-172-31-45-250 scylla[7707]:  [shard 1] compaction - Compacted 4 sstables to [/var/lib/scylla/data/system/peers-37f71aca7dc2383ba70672528af04d4f/system-peers-ka-325-Data.db:level=0, ]. 61266 by
Dec 30 15:43:37 ip-172-31-45-250 scylla[7707]:  [shard 1] compaction - Compacting [/var/lib/scylla/data/system/peers-37f71aca7dc2383ba70672528af04d4f/system-peers-ka-305-Data.db:level=0, /var/lib/scylla/data/sys
Dec 30 15:43:37 ip-172-31-45-250 scylla[7707]:  [shard 2] compaction - Compacted 4 sstables to [/var/lib/scylla/data/system/peers-37f71aca7dc2383ba70672528af04d4f/system-peers-ka-326-Data.db:level=0, ]. 73288 by
Dec 30 15:43:37 ip-172-31-45-250 scylla[7707]:  [shard 2] compaction - Compacting [/var/lib/scylla/data/system/peers-37f71aca7dc2383ba70672528af04d4f/system-peers-ka-314-Data.db:level=0, /var/lib/scylla/data/sys
Dec 30 15:43:37 ip-172-31-45-250 scylla[7707]:  [shard 1] compaction - Compacted 6 sstables to [/var/lib/scylla/data/system/peers-37f71aca7dc2383ba70672528af04d4f/system-peers-ka-329-Data.db:level=0, ]. 85109 by
Dec 30 15:43:37 ip-172-31-45-250 scylla[7707]:  [shard 2] compaction - Compacted 4 sstables to [/var/lib/scylla/data/system/peers-37f71aca7dc2383ba70672528af04d4f/system-peers-ka-330-Data.db:level=0, ]. 96958 by
Dec 30 15:43:37 ip-172-31-45-250 scylla[7707]:  [shard 1] gossip - unknown endpoint 172.31.46.16
Dec 30 15:43:37 ip-172-31-45-250 scylla[7707]:  [shard 1] gossip - unknown endpoint 172.31.46.7
Dec 30 15:43:37 ip-172-31-45-250 scylla[7707]:  [shard 2] gossip - unknown endpoint 172.31.46.6
Dec 30 15:43:37 ip-172-31-45-250 scylla[7707]:  [shard 2] gossip - unknown endpoint 172.31.46.2
Dec 30 15:43:37 ip-172-31-45-250 scylla[7707]:  [shard 2] gossip - unknown endpoint 172.31.46.11
Dec 30 15:43:37 ip-172-31-45-250 scylla[7707]:  [shard 2] gossip - unknown endpoint 172.31.46.15
Dec 30 15:43:37 ip-172-31-45-250 scylla[7707]:  [shard 1] gossip - unknown endpoint 172.31.45.245
Dec 30 15:43:37 ip-172-31-45-250 scylla[7707]:  [shard 1] gossip - unknown endpoint 172.31.46.2
Dec 30 15:43:37 ip-172-31-45-250 scylla[7707]:  [shard 2] gossip - unknown endpoint 172.31.46.15
Dec 30 15:43:37 ip-172-31-45-250 scylla[7707]:  [shard 2] gossip - unknown endpoint 172.31.45.247
Dec 30 15:43:37 ip-172-31-45-250 scylla[7707]:  [shard 1] gossip - unknown endpoint 172.31.46.15
Dec 30 15:43:37 ip-172-31-45-250 scylla[7707]:  [shard 1] gossip - unknown endpoint 172.31.45.247
Dec 30 15:43:37 ip-172-31-45-250 scylla[7707]:  [shard 1] gossip - unknown endpoint 172.31.46.0
Dec 30 15:43:37 ip-172-31-45-250 scylla[7707]:  [shard 1] gossip - unknown endpoint 172.31.45.251
Dec 30 15:43:37 ip-172-31-45-250 scylla[7707]:  [shard 2] gossip - unknown endpoint 172.31.46.9
Dec 30 15:43:37 ip-172-31-45-250 scylla[7707]:  [shard 2] gossip - unknown endpoint 172.31.46.0
Dec 30 15:43:37 ip-172-31-45-250 scylla[7707]:  [shard 2] gossip - unknown endpoint 172.31.45.249
Dec 30 15:43:37 ip-172-31-45-250 scylla[7707]:  [shard 2] gossip - unknown endpoint 172.31.46.9
Dec 30 15:43:37 ip-172-31-45-250 scylla[7707]:  [shard 1] gossip - unknown endpoint 172.31.46.2
Dec 30 15:43:37 ip-172-31-45-250 scylla[7707]:  [shard 1] gossip - unknown endpoint 172.31.45.247
Dec 30 15:43:37 ip-172-31-45-250 scylla[7707]:  [shard 2] gossip - unknown endpoint 172.31.46.2
Dec 30 15:43:37 ip-172-31-45-250 scylla[7707]:  [shard 2] gossip - unknown endpoint 172.31.45.252
Dec 30 15:43:37 ip-172-31-45-250 scylla[7707]:  [shard 1] gossip - unknown endpoint 172.31.46.7
Dec 30 15:43:37 ip-172-31-45-250 scylla[7707]:  [shard 1] gossip - unknown endpoint 172.31.46.10
Dec 30 15:43:37 ip-172-31-45-250 scylla[7707]:  [shard 2] gossip - unknown endpoint 172.31.46.0
Dec 30 15:43:37 ip-172-31-45-250 scylla[7707]:  [shard 2] gossip - unknown endpoint 172.31.45.255
Dec 30 15:43:37 ip-172-31-45-250 scylla[7707]:  [shard 2] gossip - unknown endpoint 172.31.46.9
Dec 30 15:43:37 ip-172-31-45-250 scylla[7707]:  [shard 1] gossip - unknown endpoint 172.31.46.6
Dec 30 15:43:37 ip-172-31-45-250 scylla[7707]:  [shard 1] gossip - unknown endpoint 172.31.45.246
Dec 30 15:43:37 ip-172-31-45-250 scylla[7707]:  [shard 2] gossip - unknown endpoint 172.31.46.6
Dec 30 15:43:37 ip-172-31-45-250 scylla[7707]:  [shard 2] gossip - unknown endpoint 172.31.45.254
Dec 30 15:43:37 ip-172-31-45-250 scylla[7707]:  [shard 1] gossip - unknown endpoint 172.31.46.15
Dec 30 15:43:37 ip-172-31-45-250 scylla[7707]:  [shard 2] gossip - unknown endpoint 172.31.46.0
Dec 30 15:43:37 ip-172-31-45-250 scylla[7707]:  [shard 1] gossip - unknown endpoint 172.31.46.11
Dec 30 15:43:37 ip-172-31-45-250 scylla[7707]:  [shard 2] gossip - unknown endpoint 172.31.46.13
Dec 30 15:43:37 ip-172-31-45-250 scylla[7707]:  [shard 2] gossip - unknown endpoint 172.31.45.243
Dec 30 15:43:37 ip-172-31-45-250 scylla[7707]:  [shard 2] gossip - unknown endpoint 172.31.46.14
Dec 30 15:43:37 ip-172-31-45-250 scylla[7707]:  [shard 1] gossip - unknown endpoint 172.31.46.11
Dec 30 15:43:37 ip-172-31-45-250 scylla[7707]:  [shard 1] gossip - unknown endpoint 172.31.46.13
Dec 30 15:43:37 ip-172-31-45-250 scylla[7707]:  [shard 3] gossip - unknown endpoint 172.31.46.14
Dec 30 15:43:37 ip-172-31-45-250 scylla[7707]:  [shard 3] gossip - unknown endpoint 172.31.46.11
Dec 30 15:43:37 ip-172-31-45-250 scylla[7707]:  [shard 1] gossip - unknown endpoint 172.31.45.246
Dec 30 15:43:37 ip-172-31-45-250 scylla[7707]:  [shard 1] gossip - unknown endpoint 172.31.46.16
Dec 30 15:43:37 ip-172-31-45-250 scylla[7707]:  [shard 0] compaction - Compacting [/var/lib/scylla/data/system/peers-37f71aca7dc2383ba70672528af04d4f/system-peers-ka-304-Data.db:level=0, /var/lib/scylla/data/sys
Dec 30 15:43:37 ip-172-31-45-250 scylla[7707]:  [shard 2] gossip - unknown endpoint 172.31.45.249
Dec 30 15:43:37 ip-172-31-45-250 scylla[7707]:  [shard 2] gossip - unknown endpoint 172.31.45.251
Dec 30 15:43:37 ip-172-31-45-250 scylla[7707]:  [shard 3] gossip - unknown endpoint 172.31.45.244
Dec 30 15:43:37 ip-172-31-45-250 scylla[7707]:  [shard 3] gossip - unknown endpoint 172.31.46.5
Dec 30 15:43:37 ip-172-31-45-250 scylla[7707]:  [shard 1] gossip - unknown endpoint 172.31.46.1
Dec 30 15:43:37 ip-172-31-45-250 scylla[7707]:  [shard 1] gossip - unknown endpoint 172.31.46.5
Dec 30 15:43:37 ip-172-31-45-250 scylla[7707]:  [shard 1] gossip - unknown endpoint 172.31.46.3
Dec 30 15:43:37 ip-172-31-45-250 scylla[7707]:  [shard 1] gossip - unknown endpoint 172.31.45.254
Dec 30 15:43:37 ip-172-31-45-250 scylla[7707]:  [shard 1] gossip - unknown endpoint 172.31.46.15
Dec 30 15:43:37 ip-172-31-45-250 scylla[7707]:  [shard 1] gossip - unknown endpoint 172.31.45.247
Dec 30 15:43:37 ip-172-31-45-250 scylla[7707]:  [shard 1] gossip - unknown endpoint 172.31.45.249
Dec 30 15:43:37 ip-172-31-45-250 scylla[7707]:  [shard 1] gossip - unknown endpoint 172.31.45.246
Dec 30 15:43:37 ip-172-31-45-250 scylla[7707]:  [shard 3] gossip - unknown endpoint 172.31.46.1
Dec 30 15:43:37 ip-172-31-45-250 scylla[7707]:  [shard 3] gossip - unknown endpoint 172.31.46.7
Dec 30 15:43:37 ip-172-31-45-250 scylla[7707]:  [shard 1] gossip - unknown endpoint 172.31.46.6
Dec 30 15:43:37 ip-172-31-45-250 scylla[7707]:  [shard 1] gossip - unknown endpoint 172.31.46.14
Dec 30 15:43:37 ip-172-31-45-250 scylla[7707]:  [shard 1] gossip - unknown endpoint 172.31.45.247
Dec 30 15:43:37 ip-172-31-45-250 scylla[7707]:  [shard 1] gossip - unknown endpoint 172.31.46.8
Dec 30 15:43:37 ip-172-31-45-250 scylla[7707]:  [shard 1] gossip - unknown endpoint 172.31.46.16
Dec 30 15:43:37 ip-172-31-45-250 scylla[7707]:  [shard 1] gossip - unknown endpoint 172.31.46.7
Dec 30 15:43:37 ip-172-31-45-250 scylla[7707]:  [shard 3] gossip - unknown endpoint 172.31.45.253
Dec 30 15:43:37 ip-172-31-45-250 scylla[7707]:  [shard 3] gossip - unknown endpoint 172.31.45.246
Dec 30 15:43:37 ip-172-31-45-250 scylla[7707]:  [shard 2] gossip - unknown endpoint 172.31.45.245
Dec 30 15:43:37 ip-172-31-45-250 scylla[7707]:  [shard 2] gossip - unknown endpoint 172.31.46.12
Dec 30 15:43:37 ip-172-31-45-250 scylla[7707]:  [shard 2] gossip - unknown endpoint 172.31.46.15
Dec 30 15:43:37 ip-172-31-45-250 scylla[7707]:  [shard 2] gossip - unknown endpoint 172.31.46.6
Dec 30 15:43:37 ip-172-31-45-250 scylla[7707]:  [shard 2] gossip - unknown endpoint 172.31.46.6
Dec 30 15:43:37 ip-172-31-45-250 scylla[7707]:  [shard 2] gossip - unknown endpoint 172.31.46.11
Dec 30 15:43:37 ip-172-31-45-250 scylla[7707]:  [shard 2] gossip - unknown endpoint 172.31.45.249
Dec 30 15:43:37 ip-172-31-45-250 scylla[7707]:  [shard 2] gossip - unknown endpoint 172.31.45.248
Dec 30 15:43:37 ip-172-31-45-250 scylla[7707]:  [shard 2] gossip - unknown endpoint 172.31.45.243
Dec 30 15:43:37 ip-172-31-45-250 scylla[7707]:  [shard 2] gossip - unknown endpoint 172.31.45.251
Dec 30 15:43:37 ip-172-31-45-250 scylla[7707]:  [shard 2] gossip - unknown endpoint 172.31.45.249
Dec 30 15:43:37 ip-172-31-45-250 scylla_run[7690]: scylla: /builddir/build/BUILD/scylla-server-development/seastar/core/future.hh:689: void future<T>::schedule(Func&&) [with Func = future<T>::then_wrapped(Func&&
Dec 30 15:43:37 ip-172-31-45-250 audit[7727]: <audit-1701> auid=4294967295 uid=995 gid=1001 ses=4294967295 subj=system_u:system_r:unconfined_service_t:s0 pid=7727 comm="scylla" exe="/usr/bin/scylla" sig=6
Dec 30 15:43:37 ip-172-31-45-250 sudo[7690]: pam_unix(sudo:session): session closed for user scylla
```

**Comment by penberg** [comment] 2016-01-05 09:14
@slivne There's unfortunately not a lot of information in this bug report to work with. What steps are needed to reproduce this? Are you able to capture more information from a core dump?

The assertion seems to be this:

```
    template <typename Func>
    void schedule(Func&& func) {
        if (state()->available()) {
            ::schedule(std::make_unique<continuation<Func, T...>>(std::move(func), std::move(*state())));
        } else {
            assert(_promise);
            _promise->schedule(std::move(func));
            _promise->_future = nullptr;
            _promise = nullptr;
        }
    }
```

So we have a future that's not available yet there's no promise attached to it. @avikivity, any ideas how that can happen?

**Comment by slivne** [comment] 2016-01-05 09:26
True ... shame on me ... this is the same machine that did not have
coredumps enabled (that triggered that issue to be openned).

I'll try to reproduce with 0.14 and add info

**Comment by tgrabiec** [comment] 2016-01-05 09:29
@penberg Maybe `then()` is called on the same future twice?

**Comment by slivne** [comment] 2016-01-06 20:13
Once #757 is fixed I / noam can try and see if this reproduces

**Comment by avikivity** [comment] 2016-01-11 09:23
Is a core dump available?

**Comment by slivne** [comment] 2016-01-12 08:18
There was no core available

I tried to reproduce this with 0.15 and am not able todo so (I have a load running for more then 24 hours and it did not happen).

Should I close this - or is there something we can do with the current info ?

**Comment by avikivity** [comment] 2016-01-12 08:22
Let's close it, if it reappears we can always reopen.

**Closed** 2016-01-12 08:24 UTC
Labels: bug, showstopper
