### ISSUE TITLE
write requests may never complete if a bootstrapping node is killed before it reached a NORMAL state

### ISSUE THREAD

**Issue by vladzcloudius** [scylladb/scylla#965] opened 2016-03-01 13:19 UTC
The issue has been discovered by a jepsen test that runs a cassandra-stress and bootstraps nodes at the same time. The original issue is issue #909. This one is opened for tracking a relevant storage_proxy fix.

**Comment by slivne** [comment] 2016-03-06 10:21
created a dtest to test this with CL=ONE - it is not added o regression till this is fixed to run

export CASSANDRA_DIR=~/scylla/build/release; pkill -9 scylla; pkill -9 java; rm -Rf core.*; KEEP_TEST_DIR=true  REUSE_CLUSTER=false DEBUG=true PRINT_DEBUG=true nosetests -v -s update_cluster_layout_tests.py:TestUpdateClusterLayout.simple_kill_new_node_while_bootstrapping_with_parallel_writes_test

**Comment by slivne** [comment] 2016-03-07 15:24
using commit f59415b3c6ebdd8f85b72f5658767ac676493845

the test above fails

export CASSANDRA_DIR=~/scylla/build/release; pkill -9 scylla; pkill -9 java; rm -Rf core.*; KEEP_TEST_DIR=true REUSE_CLUSTER=false DEBUG=true PRINT_DEBUG=true nosetests -v -s update_cluster_layout_tests.py:TestUpdateClusterLayout.simple_kill_new_node_while_bootstrapping_with_parallel_writes_test

this test does pass on cassandra - so we still have an issue to resolve - maybe a different one - yet please check this out

```
shlomi@localhost~/urchin-dtest (master)$ export CASSANDRA_DIR=~/cassandra; pkill -9 scylla; pkill -9 java; rm -Rf core.*; KEEP_TEST_DIR=true REUSE_CLUSTER=false DEBUG=true PRINT_DEBUG=true nosetests -v -s update_cluster_layout_tests.py:TestUpdateClusterLayout.simple_kill_new_node_while_bootstrapping_with_parallel_writes_test
simple_kill_new_node_while_bootstrapping_with_parallel_writes_test (update_cluster_layout_tests.TestUpdateClusterLayout) ... cluster ccm directory: /home/shlomi/.dtest/dtest-g11XS4
Inserting more data to make streaming process longer...
.
.

Start Node 4
Stop Node 4
ok

----------------------------------------------------------------------
Ran 1 test in 151.291s

OK
```

with scylla

```
shlomi@localhost~/urchin-dtest (master)$ export CASSANDRA_DIR=~/scylla/build/release; pkill -9 scylla; pkill -9 java; rm -Rf core.*; KEEP_TEST_DIR=true REUSE_CLUSTER=false DEBUG=true PRINT_DEBUG=true nosetests -v -s update_cluster_layout_tests.py:TestUpdateClusterLayout.simple_kill_new_node_while_bootstrapping_with_parallel_writes_test
simple_kill_new_node_while_bootstrapping_with_parallel_writes_test (update_cluster_layout_tests.TestUpdateClusterLayout) ... cluster ccm directory: /home/shlomi/.dtest/dtest-gc35OQ
Inserting more data to make streaming process longer...
.
.
.
Start Node 4
Stop Node 4
Retrying write after timeout. Attempt #0
Retrying write after timeout. Attempt #0
.
.
.
Retrying write after timeout. Attempt #1
Retrying write after timeout. Attempt #1
Retrying request after UE. Attempt #2
Retrying write after timeout. Attempt #1
Retrying write after timeout. Attempt #1
Retrying write after timeout. Attempt #1
Retrying write after timeout. Attempt #1
Retrying write after timeout. Attempt #1
Retrying request after UE. Attempt #2
Retrying request after UE. Attempt #3
Retrying request after UE. Attempt #2
Retrying request after UE. Attempt #2
Retrying request after UE. Attempt #2
Retrying request after UE. Attempt #2
Retrying request after UE. Attempt #2
Retrying request after UE. Attempt #3
Retrying write after timeout. Attempt #1
Retrying request after UE. Attempt #4
Retrying write after timeout. Attempt #1
Retrying write after timeout. Attempt #1
Retrying write after timeout. Attempt #1
Retrying write after timeout. Attempt #1
Retrying write after timeout. Attempt #1
Retrying write after timeout. Attempt #1
Retrying write after timeout. Attempt #1
Retrying write after timeout. Attempt #1
Retrying write after timeout. Attempt #1
Retrying request after UE. Attempt #3
Retrying request after UE. Attempt #3
Retrying request after UE. Attempt #3
Retrying request after UE. Attempt #3
Retrying request after UE. Attempt #3
Retrying write after timeout. Attempt #1
Retrying request after UE. Attempt #4
Retrying request after UE. Attempt #2
Retrying write after timeout. Attempt #1
Retrying write after timeout. Attempt #1
Retrying request after UE. Attempt #4
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 813, in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.7/threading.py", line 766, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/shlomi/urchin-dtest/update_cluster_layout_tests.py", line 398, in run
    insert_c1c2(session, keys=range(2000, 4000), consistency=ConsistencyLevel.ONE)
  File "/home/shlomi/urchin-dtest/tools.py", line 40, in insert_c1c2
    execute_concurrent_with_args(session, statement, [['k{}'.format(k)] for k in keys])
  File "cassandra/concurrent.py", line 220, in cassandra.concurrent.execute_concurrent_with_args (cassandra/concurrent.c:5904)
    return execute_concurrent(session, zip(cycle((statement,)), parameters), *args, **kwargs)
  File "cassandra/concurrent.py", line 88, in cassandra.concurrent.execute_concurrent (cassandra/concurrent.c:1453)
    return executor.execute(concurrency, raise_on_first_error)
  File "cassandra/concurrent.py", line 185, in cassandra.concurrent.ConcurrentExecutorListResults.execute (cassandra/concurrent.c:4829)
    return super(ConcurrentExecutorListResults, self).execute(concurrency, fail_fast)
  File "cassandra/concurrent.py", line 111, in cassandra.concurrent._ConcurrentExecutor.execute (cassandra/concurrent.c:2118)
    return self._results()
  File "cassandra/concurrent.py", line 199, in cassandra.concurrent.ConcurrentExecutorListResults._results (cassandra/concurrent.c:5597)
    with self._condition:
  File "cassandra/concurrent.py", line 203, in cassandra.concurrent.ConcurrentExecutorListResults._results (cassandra/concurrent.c:5529)
    self._raise(self._exception)
  File "cassandra/concurrent.py", line 151, in cassandra.concurrent._ConcurrentExecutor._raise (cassandra/concurrent.c:3527)
    raise exc
Unavailable: code=1000 [Unavailable exception] message="Cannot achieve consistency level for cl ONE. Requires 1, alive 1" info={'required_replicas': 1, 'alive_replicas': 1, 'consistency': 'ONE'}

Retrying request after UE. Attempt #2
Retrying request after UE. Attempt #2
Retrying request after UE. Attempt #2
Retrying request after UE. Attempt #2
Retrying request after UE. Attempt #2
Retrying request after UE. Attempt #2
Retrying request after UE. Attempt #2
Retrying request after UE. Attempt #2
Retrying request after UE. Attempt #4
Retrying request after UE. Attempt #2
Retrying request after UE. Attempt #3
Retrying request after UE. Attempt #4
Retrying request after UE. Attempt #4
.
.
.

```

**Comment by slivne** [comment] 2016-03-07 15:25
@gleb-cloudius please check this out - if it is not related to this issue lets create a new one to track it - the test it self was written to verify that this issue is resolved.

**Comment by gleb-cloudius** [comment] 2016-03-07 15:38
On Mon, Mar 07, 2016 at 07:25:35AM -0800, slivne wrote:
> @gleb-cloudius please check this out - if it is not related to this issue lets create a new one to track it - the test it self was written to verify that this issue is resolved. 
>
The way the test is written it should not pass. With rf=1 and dead
bootstrapping node insertion _should fail_, the only different between
us and cassandra is that we will fail with insufficient node and they
with timeout.

--
			Gleb.

**Comment by slivne** [comment] 2016-03-07 15:42
Well they pass and we fail ...

**Comment by gleb-cloudius** [comment] 2016-03-07 15:51
On Mon, Mar 07, 2016 at 05:47:22PM +0200, Gleb Natapov wrote:
> On Mon, Mar 07, 2016 at 07:42:27AM -0800, slivne wrote:
> > Well they pass and we fail ...
> > 
> They fail and we pass since the test has to fail.
> 
Unless insert_c1c2() returns even if insertion ended with exception in
which case the test should have ended indeed.

--
			Gleb.

**Comment by gleb-cloudius** [comment] 2016-03-07 16:30
On Mon, Mar 07, 2016 at 05:51:34PM +0200, Gleb Natapov wrote:
> On Mon, Mar 07, 2016 at 05:47:22PM +0200, Gleb Natapov wrote:
> > On Mon, Mar 07, 2016 at 07:42:27AM -0800, slivne wrote:
> > > Well they pass and we fail ...
> > > 
> > They fail and we pass since the test has to fail.
> > 
> Unless insert_c1c2() returns even if insertion ended with exception in
> which case the test should have ended indeed.
When I run similar steps manually, I do get exception, but not the one I
expect. I will check. Another thing is that after killing bootstrapping
node live nodes forget about it after a minute or so and workload works
normally. Not sure if it is how it should be.

--
			Gleb.

**Comment by gleb-cloudius** [comment] 2016-03-07 16:56
On Mon, Mar 07, 2016 at 06:30:17PM +0200, Gleb Natapov wrote:
> On Mon, Mar 07, 2016 at 05:51:34PM +0200, Gleb Natapov wrote:
> > On Mon, Mar 07, 2016 at 05:47:22PM +0200, Gleb Natapov wrote:
> > > On Mon, Mar 07, 2016 at 07:42:27AM -0800, slivne wrote:
> > > > Well they pass and we fail ...
> > > > 
> > > They fail and we pass since the test has to fail.
> > > 
> > Unless insert_c1c2() returns even if insertion ended with exception in
> > which case the test should have ended indeed.
> When I run similar steps manually, I do get exception, but not the one I
> expect. I will check.
Checked and that is fine. I expected Unavailable exception, but got
Timeout. It turns out that after killing bootstraping node it is
reported as alive for awhile and during this time Timeout happens, after
it is started to be reported as dead Unavailable started to be thrown.

From my manual testing everything works as expected.

--
			Gleb.

**Comment by slivne** [comment] 2016-03-08 09:28
As allways @gleb-cloudius is right and test is "bad"

We have found that dtest sets up a retry policy and that is retrying (and printing) the retries.

There s a difference between Scylla and C* in which Scylla will return Unavailable immidiatly when there are not enough nodes to write to while in C* it will return this only after a timeout (@gleb-cloudius - did I capture this correctly).

I will fix the test and verify that we are getting what we expect and then close the issue.

**Comment by gleb-cloudius** [comment] 2016-03-08 09:37
On Tue, Mar 08, 2016 at 01:28:46AM -0800, slivne wrote:
> As allways @gleb-cloudius is right and test is "bad"
> 
> We have found that dtest sets up a retry policy and that is retrying (and printing) the retries.
> 
> There s a difference between Scylla and C* in which Scylla will return Unavailable immidiatly when there are not enough nodes to write to while in C* it will return this only after a timeout (@gleb-cloudius - did I capture this correctly).
> 
Yes, this is correct.

> I will fix the test and verify that we are getting what we expect and then close the issue.
> 

--
			Gleb.

**Closed** 2016-03-17 16:35 UTC
Labels: bug, showstopper
