### ISSUE TITLE
scylla and scylla-kernel-conf packages aren't installed in scylla-ami: ami-19a6e679

### ISSUE THREAD

**Issue by kongove** [scylladb/scylla#1572] opened 2016-08-11 08:17 UTC
*Installation details*
Scylla version (or git commit hash): 1.2.3-20160731.e9b7352.el7.centos.x86_64
Cluster size: 4
OS (RHEL/CentOS/Ubuntu/AWS AMI): Scylla-ami: ami-19a6e679, CentOS

In my upgrade jenkins job, the case tried to update 6 packages, but two packages aren't updated.
I would improve my test to check if all packages exist and install the missing ones.
But it should be a 'bug' for AMI generate code.

Details:

```
[54.183.217.214] [stdout] Package(s) scylla available, but not installed.
[54.183.217.214] [stdout] Package(s) scylla-kernel-conf available, but not installed.
```

```
# sudo yum update scylla scylla-server scylla-jmx scylla-tools scylla-conf scylla-kernel-conf -y
[54.183.217.214] [stdout] Package(s) scylla available, but not installed.
[54.183.217.214] [stdout] Package(s) scylla-kernel-conf available, but not installed.
[54.183.217.214] [stdout] Resolving Dependencies
[54.183.217.214] [stdout] --> Running transaction check
[54.183.217.214] [stdout] ---> Package scylla-conf.x86_64 0:1.2.3-20160731.e9b7352.el7.centos will be updated
[54.183.217.214] [stdout] ---> Package scylla-conf.x86_64 0:1.3.rc2-20160729.23c340b.el7.centos will be an update
[54.183.217.214] [stdout] ---> Package scylla-jmx.noarch 0:1.2.3-20160731.ce0f696.el7.centos will be updated
[54.183.217.214] [stdout] ---> Package scylla-jmx.noarch 0:1.3.rc2-20160729.e87c771.el7.centos will be an update
[54.183.217.214] [stdout] ---> Package scylla-server.x86_64 0:1.2.3-20160731.e9b7352.el7.centos will be updated
[54.183.217.214] [stdout] ---> Package scylla-server.x86_64 0:1.3.rc2-20160729.23c340b.el7.centos will be an update
[54.183.217.214] [stdout] --> Processing Dependency: /usr/bin/python3 for package: scylla-server-1.3.rc2-20160729.23c340b.el7.centos.x86_64
[54.183.217.214] [stdout] ---> Package scylla-tools.noarch 0:1.2.3-20160731.d26e9da.el7.centos will be updated
[54.183.217.214] [stdout] ---> Package scylla-tools.noarch 0:1.3.rc2-20160729.472d2da.el7.centos will be an update
[54.183.217.214] [stdout] --> Running transaction check
[54.183.217.214] [stdout] ---> Package python34.x86_64 0:3.4.3-5.el7 will be installed
[54.183.217.214] [stdout] --> Finished Dependency Resolution
[54.183.217.214] [stdout] 
[54.183.217.214] [stdout] Dependencies Resolved
[54.183.217.214] [stdout] 
[54.183.217.214] [stdout] ================================================================================
[54.183.217.214] [stdout]  Package       Arch   Version                              Repository      Size
[54.183.217.214] [stdout] ================================================================================
[54.183.217.214] [stdout] Updating:
[54.183.217.214] [stdout]  scylla-conf   x86_64 1.3.rc2-20160729.23c340b.el7.centos  scylla          16 k
[54.183.217.214] [stdout]  scylla-jmx    noarch 1.3.rc2-20160729.e87c771.el7.centos  scylla-generic 6.1 M
[54.183.217.214] [stdout]  scylla-server x86_64 1.3.rc2-20160729.23c340b.el7.centos  scylla         8.9 M
[54.183.217.214] [stdout]  scylla-tools  noarch 1.3.rc2-20160729.472d2da.el7.centos  scylla-generic  18 M
[54.183.217.214] [stdout] Installing for dependencies:
[54.183.217.214] [stdout]  python34      x86_64 3.4.3-5.el7                          epel            50 k
[54.183.217.214] [stdout] 
[54.183.217.214] [stdout] Transaction Summary
[54.183.217.214] [stdout] ================================================================================
[54.183.217.214] [stdout] Install             ( 1 Dependent package)
[54.183.217.214] [stdout] Upgrade  4 Packages
```

**Comment by slivne** [comment] 2016-08-11 09:43
duplicate of #1414 

should be fixed in 1.3

@kongove  can you but a 1.3 ami and check it has scylla, scylla-kernel-conf and debug installed

**Comment by kongove** [comment] 2016-08-15 09:45
I installed a new instance with scylla_2016-08-15T04-11-47Z (ami-45811a52), which is got from Jenkins job/scylla-1.3-ami/11

Result: scylla-kernel-conf was installed by default, but scylla wasn't.

```
[centos@ip-10-140-220-198 ~]$ rpm -qa|grep scylla
scylla-boost-thread-1.58.0-11.el7.centos.x86_64
scylla-boost-date-time-1.58.0-11.el7.centos.x86_64
scylla-jmx-1.3.rc3-20160815.ad895c2.el7.centos.noarch
scylla-boost-system-1.58.0-11.el7.centos.x86_64
scylla-boost-filesystem-1.58.0-11.el7.centos.x86_64
scylla-boost-program-options-1.58.0-11.el7.centos.x86_64
scylla-server-1.3.rc3-20160815.b2e6a52.el7.centos.x86_64
scylla-tools-1.3.rc3-20160815.e7494d3.el7.centos.noarch
scylla-kernel-conf-1.3.rc3-20160815.b2e6a52.el7.centos.x86_64
scylla-env-1.0-1.el7.centos.noarch
scylla-conf-1.3.rc3-20160815.b2e6a52.el7.centos.x86_64
scylla-boost-test-1.58.0-11.el7.centos.x86_64
scylla-debuginfo-1.3.rc3-20160815.b2e6a52.el7.centos.x86_64
[centos@ip-10-140-220-198 ~]$ sudo yum install scylla
...
Installing:
 scylla           x86_64           1.3.rc2-20160729.23c340b.el7.centos             scylla           2.1 k
```

**Comment by slivne** [comment] 2016-08-15 10:08
The ami passed testing - so can you please add your env info which instance
type

I tried c3.xlarge

[centos@ip-10-69-5-217 ~]$ rpm -qa | grep scylla
scylla-boost-thread-1.58.0-11.el7.centos.x86_64
scylla-boost-date-time-1.58.0-11.el7.centos.x86_64
scylla-jmx-1.3.rc3-20160815.ad895c2.el7.centos.noarch
scylla-boost-system-1.58.0-11.el7.centos.x86_64
scylla-boost-filesystem-1.58.0-11.el7.centos.x86_64
scylla-boost-program-options-1.58.0-11.el7.centos.x86_64
scylla-server-1.3.rc3-20160815.b2e6a52.el7.centos.x86_64
scylla-tools-1.3.rc3-20160815.e7494d3.el7.centos.noarch
scylla-kernel-conf-1.3.rc3-20160815.b2e6a52.el7.centos.x86_64
scylla-env-1.0-1.el7.centos.noarch
scylla-conf-1.3.rc3-20160815.b2e6a52.el7.centos.x86_64
scylla-boost-test-1.58.0-11.el7.centos.x86_64
scylla-debuginfo-1.3.rc3-20160815.b2e6a52.el7.centos.x86_64
[centos@ip-10-69-5-217 ~]$

and it works

**Comment by kongove** [comment] 2016-08-17 02:02
I used c3.large

On 8/15/16, Shlomi Livne <notifications@github.com> wrote:
> The ami passed testing - so can you please add your env info which instance
> type
>
> I tried c3.xlarge
>
> [centos@ip-10-69-5-217 ~]$ rpm -qa | grep scylla
> scylla-boost-thread-1.58.0-11.el7.centos.x86_64
> scylla-boost-date-time-1.58.0-11.el7.centos.x86_64
> scylla-jmx-1.3.rc3-20160815.ad895c2.el7.centos.noarch
> scylla-boost-system-1.58.0-11.el7.centos.x86_64
> scylla-boost-filesystem-1.58.0-11.el7.centos.x86_64
> scylla-boost-program-options-1.58.0-11.el7.centos.x86_64
> scylla-server-1.3.rc3-20160815.b2e6a52.el7.centos.x86_64
> scylla-tools-1.3.rc3-20160815.e7494d3.el7.centos.noarch
> scylla-kernel-conf-1.3.rc3-20160815.b2e6a52.el7.centos.x86_64
> scylla-env-1.0-1.el7.centos.noarch
> scylla-conf-1.3.rc3-20160815.b2e6a52.el7.centos.x86_64
> scylla-boost-test-1.58.0-11.el7.centos.x86_64
> scylla-debuginfo-1.3.rc3-20160815.b2e6a52.el7.centos.x86_64

^^^

There is no scylla-1.3-rc3-.... package.

> [centos@ip-10-69-5-217 ~]$
>
> and it works

**Comment by slivne** [comment] 2016-08-20 21:53
@syuu1228 can you have a look - are we not installing all the packages ?

**Comment by syuu1228** [comment] 2016-08-23 18:43
Posted "dist/ami: install scylla metapackage on AMI" to fix missing scylla metapackage.
We don't have issue with scylla-kernel-conf package, so let's close this issue.

**Closed** 2016-08-24 09:55 UTC
Labels: bug
