### ISSUE TITLE
weird read timeout exception

### ISSUE THREAD

**Issue by zhiguoxu** [scylladb/scylla#2826] opened 2017-09-20 13:11 UTC
Installation details
Scylla version (or git commit hash):1.7
Cluster size:1
OS (RHEL/CentOS/Ubuntu/AWS AMI):centos7.3

I have come across a very weird problem. When I set a query statement to:
"statement.setConsistencyLevel(ConsistencyLevel.ONE);"
and execute this query, the exception report: 
ReadTimeoutException: Cassandra timeout during read query at consistency ONE (3 responses were required but only 2 replica responded) at ...........
Why I set ONE consistency but scylladb need 3 response?

**Comment by tgrabiec** [comment] 2017-09-20 13:48
Duplicate of https://github.com/scylladb/scylla/issues/2823

**Closed by tgrabiec** 2017-09-20 13:48 UTC
