### ISSUE TITLE
scylla_setup fails in non-interactive mode

### ISSUE THREAD

**Issue by cogitaria-admin** [scylladb/scylla#7395] opened 2020-10-12 05:03 UTC
*Installation details*

Scylla version (or git commit hash): 4.1

Cluster size:
OS (RHEL/CentOS/Ubuntu/AWS AMI): 1

I ran scylla_setup in interactive mode on the first node of a multi-node cluster.  On completion I received this message:

```
ScyllaDB setup finished.
scylla_setup accepts command line arguments as well! For easily provisioning in a similar environment than this, type:

    scylla_setup --no-raid-setup --no-enable-service --no-ntp-setup \
                 --no-coredump-setup --no-sysconfig-setup \
                 --no-version-check --no-cpuscaling-setup
```
The suggested command **fails** with a usage message every time. There is no indication what is wrong or missing.  Just to reiterate, the failing command is the one suggested by scylla_setup itself, following interactive installation. 

```
usage: scylla_setup [-h] (--disks DISKS | --no-raid-setup) [--nic NIC]
                    [--ntp-domain NTP_DOMAIN] [--ami] [--setup-nic-and-disks]
                    [--developer-mode] [--no-ec2-check] [--no-kernel-check]
                    [--no-verify-package] [--no-enable-service]
                    ... MORE DETAILS ...
```

**Comment by syuu1228** [comment] 2020-11-30 10:30
I'm not able to reproduce the error on 4.1.0, 4.1.9 and 4.4-dev.
However, I found another pattern that could not run:
```
ScyllaDB setup finished.
scylla_setup accepts command line arguments as well! For easily provisioning in a similar environment than this, type:

    scylla_setup --no-raid-setup --no-verify-package --io-setup

Also, to avoid the time-consuming I/O tuning you can add --no-io-setup and copy the contents of /etc/scylla.d/io*
Only do that if you are moving the files into machines with the exact same hardware
```
This is because --io-setup expects one argument, but the message doesn't include it.
I guess original issue has similar problem but I don't find what it is.

**Comment by syuu1228** [comment] 2020-11-30 13:07
Okay I found the reason of this.
scylla_setup requires to set --nic even --no-sysconfig-setup, but when we skipping sysconfig_setup we don't specify NIC, so suggesting argument and actual behavior doesn't matches.

see: https://github.com/scylladb/scylla/blob/master/dist/common/scripts/scylla_setup#L295

io_setup issue is another bug, I'll create new issue.

**Comment by syuu1228** [comment] 2020-11-30 15:25
Previous comment was wrong, so deleted it

**Comment by syuu1228** [comment] 2020-11-30 23:04
I also found that NIC selection does not applied to the command suggestion.
Like this:
```
Do you want to enable Network Interface Card (NIC) and disk(s) optimization?
Yes - optimize the NIC queue and disks settings. Selecting Yes greatly improves performance. No - skip this step.
[yes/NO]yes
Please select a NIC from the following list:
['virbr0-nic', 'docker0', 'virbr0', 'eno1']
> eno1

(skip lines)

ScyllaDB setup finished.
scylla_setup accepts command line arguments as well! For easily provisioning in a similar environment than this, type:

    scylla_setup --no-raid-setup --no-verify-package --io-setup 1

Also, to avoid the time-consuming I/O tuning you can add --no-io-setup and copy the contents of /etc/scylla.d/io*
Only do that if you are moving the files into machines with the exact same hardware
```

**Comment by syuu1228** [comment] 2020-12-04 20:48
I found more case input does not applied to the command suggestion, --swap-directory and --swap-size are missing.
Like this:
```
No swap is configured, it is highly recommended to setup swap on Scylla node.
Do you want to configure swapfile?
Answer yes to setup swapfile to Scylla, Answer no to do nothing.
[YES/no]
Do you want to create swapfile on root directory?
Anser yes to create swapfile on /, no to choose swap directory.
[YES/no]no
Please input swapfile directory:
> /home
Do you want to auto configure swap size?
Anser yes to auto configure, no to manually configure swap size.
[YES/no]no
Please input swap size in GB:
> 16
16384+0 records in
16384+0 records out
17179869184 bytes (17 GB, 16 GiB) copied, 5.16659 s, 3.3 GB/s
Setting up swapspace version 1, size = 16 GiB (17179865088 bytes)
no label, UUID=bd512c16-047b-4d98-a73a-193b76b613f9
Created symlink /etc/systemd/system/multi-user.target.wants/home-swapfile.swap → /etc/systemd/system/home-swapfile.swap.
ScyllaDB setup finished.
scylla_setup accepts command line arguments as well! For easily provisioning in a similar environment than this, type:

    scylla_setup --no-raid-setup --no-kernel-check --no-verify-package \
                 --no-enable-service --no-selinux-setup --no-ntp-setup \
                 --no-coredump-setup --no-sysconfig-setup --io-setup 0 \
                 --no-node-exporter --no-cpuscaling-setup \
                 --no-fstrim-setup --no-memory-setup

```

**Comment by slivne** [comment] 2021-01-19 21:25
closing this issue - we have improved failure messages and indication of whats the issue is

**Closed by slivne** 2021-01-19 21:25 UTC
Labels: UX, User Request, bug, onboarding
