### ISSUE TITLE
CDC c-s workload got stuck with WriteTimeoutException

### ISSUE THREAD

**Issue by amoskong** [scylladb/scylla#5904] opened 2020-02-26 10:12 UTC
*Installation details*
Scylla version (or git commit hash): 666.development-0.20200224.25a763a187a
Cluster size: 6
OS (RHEL/CentOS/Ubuntu/AWS AMI): ami-075546eca3f85ea74

### Test configuration:

instance_type_db: i3.4xlarge  * 6
instance_type_loader: c5.xlarge  * 2
n_db_nodes: 6
n_loaders: 2
ami_id_loader: ami-08488048283fc2ad2

nemesis_class_name: ChaosMonkey

test_id: 4ee0a8d6-cec7-4c87-9d7c-943d8fae748f
Job: https://jenkins.scylladb.com/job/scylla-staging/job/amos/job/longevity-cdc-100gb-4h/4/

##### C-S used in loader

```
$ rpm -qa |grep scylla
scylla-enterprise-tools-core-2019.1.4-20191218.c752b991ea.el7.noarch
scylla-enterprise-conf-2019.1.4-0.20191218.b59e92dbd.el7.x86_64
scylla-enterprise-tools-2019.1.4-20191218.c752b991ea.el7.noarch
```

### Workload load:

cassandra-stress user no-warmup profile=/tmp/cdc_profile.yaml ops'(insert=2,read1=1,update_number=1,update_name=1)' cl=QUORUM duration=240m -port jmx=6868 -mode cql3 native -rate threads=200 -node 10.0.46.134

### Problem

Cassandra-stress raised some WriteTimeoutException and got stuck after executed 3 mins.

java.io.IOException: Operation x10 on key(s) xxxx
Error executing: (WriteTimeoutException): Cassandra timeout during UNLOGGED_BATCH write query at consistency QUORUM (2 replica were required but only 0 acknowledged the write)

### Additional test

It still got stuck if I reduced the c-s threads from 200 to 50.
It won't stuck if I reduced the c-s threads from 200 to 20.

### C-S User Profile: cdc_profile.yaml  
[cdc_profile.yaml.txt](https://github.com/scylladb/scylla/files/4254857/cdc_profile.yaml.txt)

```
| keyspace: cdc_test
| 
| keyspace_definition: |
| 
|   CREATE KEYSPACE cdc_test WITH replication = {'class': 'SimpleStrategy', 'replication_factor': '3'}  AND durable_writes = true;
| 
| table: test_table
| 
| table_definition: |
| 
|   CREATE TABLE cdc_test.test_table (
|     pkid text PRIMARY KEY,
|     name text,
|     number int,
|     starttime timestamp,
|     weight decimal,
|     users list<text>,
|   ) WITH bloom_filter_fp_chance = 0.01
|     AND cdc = {'enabled': true, 'preimage': true, 'ttl': 600}
|     AND caching = {'keys': 'ALL', 'rows_per_partition': 'ALL'}
|     AND comment = 'Request for unit level UIs'
|     AND compaction = {'class': 'SizeTieredCompactionStrategy'}
|     AND compression = {'sstable_compression': 'org.apache.cassandra.io.compress.LZ4Compressor'}
|     AND crc_check_chance = 1.0
|     AND dclocal_read_repair_chance = 0.1
|     AND default_time_to_live = 0
|     AND gc_grace_seconds = 864000
|     AND max_index_interval = 2048
|     AND memtable_flush_period_in_ms = 0
|     AND min_index_interval = 128
|     AND read_repair_chance = 0.0
|     AND speculative_retry = '99.0PERCENTILE';
| 
| columnspec:
|   - name: pkid
|     population: exp(1..10000000)
| 
| insert:
|   partitions: fixed(1)
|   batchtype: UNLOGGED
| 
| queries:
|   read1:
|     cql: select * from cdc_test.test_table where pkid = ?
|     fields: samerow
|   update_name:
|     cql: update cdc_test.test_table set name = ? where pkid = ?
|     fields: samerow
|   update_number:
|     cql: update cdc_test.test_table set number = ? where pkid = ?
|     fields: samerow
```

@slivne @roydahan @haaawk @aleksbykov

**Comment by slivne** [comment] 2020-03-01 11:10
where is the monitor ?

what features of CDC did you select - I can't find if you are using modify / pre_image ?

**Comment by haaawk** [comment] 2020-03-02 08:01
This is with preimage @slivne -> `AND cdc = {'enabled': true, 'preimage': true, 'ttl': 600}`

**Comment by haaawk** [comment] 2020-03-02 08:03
I'm wondering whether this is a problem at all. If it works with 20 client threads and starts throwing WriteTimeoutException with more client threads then it may just be that more threads overload the cluster. @amoskong Could you please disable preimage and check what number of client threads you can reach then? preimage is pretty heavy operation so I wouldn't be surprised that the load has to be significantly decreased when preimage is enabled.

**Comment by amoskong** [comment] 2020-03-02 09:21
> I'm wondering whether this is a problem at all. If it works with 20 client threads and starts throwing WriteTimeoutException with more client threads then it may just be that more threads overload the cluster. @amoskong Could you please disable preimage and check what number of client threads you can reach then? preimage is pretty heavy operation so I wouldn't be surprised that the load has to be significantly decreased when preimage is enabled.

I also touched WriteTimeoutException when preimage is disabled.

In my manual testing, the 20 threads workload executed longer time, but it also failed with WriteTimeoutException.

I just started a job with threads=20, and pre-image: false.  Let's see if the problem occurs.

**Comment by amoskong** [comment] 2020-03-03 06:00
#### Workload with `threads=20` ,  `cdc = {'enabled': true, 'preimage': false, 'ttl': 600}`

`cassandra-stress user no-warmup profile=/tmp/cdc_profile.yaml ops'(insert=2,read1=1,update_number=1,update_name=1)' cl=QUORUM duration=240m -port jmx=6868 -mode cql3 native -rate threads=20 -node 10.0.107.9`

The workload failed (stuck) for IOException after executed `1 hour`.
We can also see many stall (about 1800+ms), not too big.

![image](https://user-images.githubusercontent.com/309708/75746940-a977e900-5d56-11ea-908e-55c41158cecd.png)

Test id: 373fb462-0b68-4a45-8372-f2e90e6eb55d
db logs: https://cloudius-jenkins-test.s3.amazonaws.com/373fb462-0b68-4a45-8372-f2e90e6eb55d/20200302_141613/db-cluster-373fb462.zip 
grafana: https://cloudius-jenkins-test.s3.amazonaws.com/373fb462-0b68-4a45-8372-f2e90e6eb55d/20200302_140931/grafana-screenshot-overview-20200302_141021-longevity-cdc-100gb-4h-cdc-long-monitor-node-373fb462-1.png
Restore Monitor Stack command: $ hydra investigate show-monitor 373fb462-0b68-4a45-8372-f2e90e6eb55d
Show all stored logs command: $ hydra investigate show-logs 373fb462-0b68-4a45-8372-f2e90e6eb55d

**Comment by kbr-** [comment] 2020-03-04 12:08
I noticed that the test creates huge lists of text:
```
|     users list<text>,
```
my hypothesis is that these lists grow bigger and bigger without any limit on their size, and Scylla's job at managing them gets harder and harder without limit. Eventually Scylla gives up. See this reactor stall:
```
< t:2020-03-02 10:07:26,153 f:sct_events.py   l:718  c:sdcm.sct_events      p:INFO  > 2020-03-02T10:07:11+00:00  longevity-cdc-100gb-4h-cdc-long-db-node-373fb462-5 !INFO    | scylla: Reactor stalled for 650 ms on shard 8.
< t:2020-03-02 10:07:26,153 f:sct_events.py   l:718  c:sdcm.sct_events      p:INFO  > 
< t:2020-03-02 10:07:26,153 f:sct_events.py   l:718  c:sdcm.sct_events      p:INFO  > void seastar::backtrace<seastar::backtrace_buffer::append_backtrace()::{lambda(seastar::frame)#1}>(seastar::backtrace_buffer::append_backtrace()::{lambda(seastar::frame)#1}&&) at /usr/include/fmt/format.h:1158
< t:2020-03-02 10:07:26,153 f:sct_events.py   l:718  c:sdcm.sct_events      p:INFO  > seastar::backtrace_buffer::append_backtrace() at /usr/include/fmt/format.h:1158
< t:2020-03-02 10:07:26,153 f:sct_events.py   l:718  c:sdcm.sct_events      p:INFO  >  (inlined by) print_with_backtrace at ./build/release/seastar/./seastar/src/core/reactor.cc:731
< t:2020-03-02 10:07:26,153 f:sct_events.py   l:718  c:sdcm.sct_events      p:INFO  > seastar::internal::cpu_stall_detector::generate_trace() at /usr/include/fmt/format.h:1158
< t:2020-03-02 10:07:26,153 f:sct_events.py   l:718  c:sdcm.sct_events      p:INFO  > seastar::internal::cpu_stall_detector::maybe_report() at /usr/include/fmt/format.h:1158
< t:2020-03-02 10:07:26,153 f:sct_events.py   l:718  c:sdcm.sct_events      p:INFO  >  (inlined by) seastar::internal::cpu_stall_detector::on_signal() at ./build/release/seastar/./seastar/src/core/reactor.cc:1038
< t:2020-03-02 10:07:26,153 f:sct_events.py   l:718  c:sdcm.sct_events      p:INFO  >  (inlined by) seastar::reactor::block_notifier(int) at ./build/release/seastar/./seastar/src/core/reactor.cc:1161
< t:2020-03-02 10:07:26,153 f:sct_events.py   l:718  c:sdcm.sct_events      p:INFO  > ?? ??:0
< t:2020-03-02 10:07:26,153 f:sct_events.py   l:718  c:sdcm.sct_events      p:INFO  > utils::linearizing_input_stream<data::basic_value_view<(mutable_view)0>, marshal_exception>::remove_current_prefix(unsigned long) at /usr/include/fmt/format.h:1158
< t:2020-03-02 10:07:26,153 f:sct_events.py   l:718  c:sdcm.sct_events      p:INFO  >  (inlined by) utils::linearizing_input_stream<data::basic_value_view<(mutable_view)0>, marshal_exception>::do_read(unsigned long) at ././utils/linearizing_input_stream.hh:77
< t:2020-03-02 10:07:26,153 f:sct_events.py   l:718  c:sdcm.sct_events      p:INFO  >  (inlined by) utils::linearizing_input_stream<data::basic_value_view<(mutable_view)0>, marshal_exception>::read(unsigned long) at ././utils/linearizing_input_stream.hh:110
< t:2020-03-02 10:07:26,153 f:sct_events.py   l:718  c:sdcm.sct_events      p:INFO  >  (inlined by) operator() at ./collection_mutation.cc:457
< t:2020-03-02 10:07:26,153 f:sct_events.py   l:718  c:sdcm.sct_events      p:INFO  >  (inlined by) deserialize_collection_mutation<deserialize_collection_mutation(const abstract_type&, collection_mutation_input_stream&)::<lambda(const collection_type_impl&)>::<lambda(collection_mutation_input_stream&)> > at ./collection_mutation.cc:439
< t:2020-03-02 10:07:26,153 f:sct_events.py   l:718  c:sdcm.sct_events      p:INFO  >  (inlined by) operator() at ./collection_mutation.cc:459
< t:2020-03-02 10:07:26,153 f:sct_events.py   l:718  c:sdcm.sct_events      p:INFO  > std::invoke_result<seastar::internal::variant_visitor<deserialize_collection_mutation(abstract_type const&, utils::linearizing_input_stream<data::basic_value_view<(mutable_view)0>, marshal_exception>&)::{lambda(collection_type_impl const&)#1}, deserialize_collection_mutation(abstract_type const&, utils::linearizing_input_stream<data::basic_value_view<(mutable_view)0>, marshal_exception>&)::{lambda(user_type_impl const&)#2}, deserialize_collection_mutation(abstract_type const&, utils::linearizing_input_stream<data::basic_value_view<(mutable_view)0>, marshal_exception>&)::{lambda(abstract_type const&)#3}>, ascii_type_impl const&>::type visit<seastar::internal::variant_visitor<deserialize_collection_mutation(abstract_type const&, utils::linearizing_input_stream<data::basic_value_view<(mutable_view)0>, marshal_exception>&)::{lambda(collection_type_impl const&)#1}, deserialize_collection_mutation(abstract_type const&, utils::linearizing_input_stream<data::basic_value_view<(mutable_view)0>, marshal_exception>&)::{lambda(user_type_impl const&)#2}, deserialize_collection_mutation(abstract_type const&, utils::linearizing_input_stream<data::basic_value_view<(mutable_view)0>, marshal_exception>&)::{lambda(abstract_type const&)#3}> >(abstract_type const&, deserialize_collection_mutation(abstract_type const&, utils::linearizing_input_stream<data::basic_value_view<(mutable_view)0>, marshal_exception>&)::{lambda(abstract_type const&)#3}&&) at /usr/include/fmt/format.h:1158
< t:2020-03-02 10:07:26,153 f:sct_events.py   l:718  c:sdcm.sct_events      p:INFO  > deserialize_collection_mutation(abstract_type const&, utils::linearizing_input_stream<data::basic_value_view<(mutable_view)0>, marshal_exception>&) at /usr/include/fmt/format.h:1158
< t:2020-03-02 10:07:26,153 f:sct_events.py   l:718  c:sdcm.sct_events      p:INFO  >  (inlined by) with_deserialized<merge(const abstract_type&, collection_mutation_view, collection_mutation_view)::<lambda(collection_mutation_view_description)> > at ././collection_mutation.hh:101
< t:2020-03-02 10:07:26,153 f:sct_events.py   l:718  c:sdcm.sct_events      p:INFO  >  (inlined by) merge(abstract_type const&, collection_mutation_view, collection_mutation_view) at ./collection_mutation.cc:374
< t:2020-03-02 10:07:26,153 f:sct_events.py   l:718  c:sdcm.sct_events      p:INFO  > apply_monotonically(column_definition const&, cell_and_hash&, atomic_cell_or_collection&, seastar::optimized_optional<cell_hash>) at /usr/include/boost/intrusive/pointer_plus_bits.hpp:89
< t:2020-03-02 10:07:26,153 f:sct_events.py   l:718  c:sdcm.sct_events      p:INFO  > row::apply_monotonically(column_definition const&, atomic_cell_or_collection&&, seastar::optimized_optional<cell_hash>) at /usr/include/boost/intrusive/pointer_plus_bits.hpp:89
< t:2020-03-02 10:07:26,153 f:sct_events.py   l:718  c:sdcm.sct_events      p:INFO  > row::apply(column_definition const&, atomic_cell_or_collection const&, seastar::optimized_optional<cell_hash>) at /usr/include/boost/intrusive/pointer_plus_bits.hpp:89
< t:2020-03-02 10:07:26,153 f:sct_events.py   l:718  c:sdcm.sct_events      p:INFO  >  (inlined by) operator() at ./mutation_partition.cc:1695
< t:2020-03-02 10:07:26,153 f:sct_events.py   l:718  c:sdcm.sct_events      p:INFO  >  (inlined by) maybe_invoke_with_hash<row::apply(const schema&, column_kind, const row&)::<lambda(column_id, const cell_and_hash&)>, const cell_and_hash> at ./mutation_partition.hh:253
< t:2020-03-02 10:07:26,153 f:sct_events.py   l:718  c:sdcm.sct_events      p:INFO  >  (inlined by) for_each_cell<row::apply(const schema&, column_kind, const row&)::<lambda(column_id, const cell_and_hash&)> > at ./mutation_partition.hh:280
< t:2020-03-02 10:07:26,153 f:sct_events.py   l:718  c:sdcm.sct_events      p:INFO  >  (inlined by) row::apply(schema const&, column_kind, row const&) at ./mutation_partition.cc:1694
< t:2020-03-02 10:07:26,153 f:sct_events.py   l:718  c:sdcm.sct_events      p:INFO  > clustering_row::apply(schema const&, rows_entry const&) at ./mutation_fragment.hh:110
< t:2020-03-02 10:07:26,153 f:sct_events.py   l:718  c:sdcm.sct_events      p:INFO  >  (inlined by) partition_snapshot_flat_reader<partition_snapshot_reader_dummy_accounter>::lsa_partition_reader::next_row(nonwrapping_range<clustering_key_prefix> const&, std::optional<position_in_partition> const&, range_tombstone_stream&)::{lambda()#1}::operator()() const at ./partition_snapshot_reader.hh:189
```

It takes 650 ms just to deserialize this collection.

@amoskong 

could you try running a similar test but with CDC disabled? This might be unrelated to CDC.

Do we have longevity tests which similarly create such huge collections?

By the way, the problem might be easier to reproduce if we run those inserts/updates against a single partition key.

**Comment by elcallio** [comment] 2020-03-04 12:39
Stating the obvious, but: If there is a huge (non-frozen) list used with preimage on, then you will get progressively longer processing time for each write (touching/including preimage for that column). That is obviously the same weakness you would see if just doing client query of said row, but in a write-only benchmark it would suddenly introduce progressively more expensive reads.

**Comment by kbr-** [comment] 2020-03-04 13:11
This test was run on a version before non-atomic columns were handled, but I don't know if the preimage was not already being queried for such columns.

Also the latest run was without preimage and it also got stuck after some time. I'm wondering if it's due to the reads made by the test:
```
| queries:
|   read1:
|     cql: select * from cdc_test.test_table where pkid = ?
|     fields: samerow
```

**Comment by elcallio** [comment] 2020-03-04 13:28
It would be queried but not written to the actual preimage I think (the code would see the column was in the mutation and include it in the query, but transform would skip because non-atomic) - I think...

**Comment by elcallio** [comment] 2020-03-04 13:30
Yes.

**Comment by haaawk** [comment] 2020-03-05 07:22
Any news on this @amoskong? Did you manage to check whether the test keeps running without getting stuck when CDC is disabled?

**Comment by amoskong** [comment] 2020-03-05 08:04
> Any news on this @amoskong? Did you manage to check whether the test keeps running without getting stuck when CDC is disabled?

The new job is still running, I will update you when it finishes.

**Comment by amoskong** [comment] 2020-03-05 10:54
> > Any news on this @amoskong? Did you manage to check whether the test keeps running without getting stuck when CDC is disabled?
> 
> The new job is still running, I will update you when it finishes.

@kbr- The problem is reproduced without enabling CDC.

`cdc = {'enabled': false, 'preimage': false}`


I didn't found a way to limit the number of list item. If it still fails with small size, I will remove list from the cdc longevity profile.

```
    users list<int>,
    names list<text>,


  - name: users
    size: fixed(2)
    population: uniform(1..1000)  => it limited the size of each item in the list, all items are smaller than 1000.

  - name: names
    size: fixed(2)  => this limited the size of each item in the list
    population: uniform(1..2)  => seems no effect, the list item number is random

```

**Comment by haaawk** [comment] 2020-03-05 10:56
That's great news :D. Removing list from the test, temporarily until we find a way to limit it's size, is a good idea @amoskong

**Comment by kbr-** [comment] 2020-03-06 07:58
@amoskong 

It's good that we test collections in cdc longevity, but `list` is maybe not the best choice. You could use `map` or `set` because if you put the same key twice into a `map`/`set`, the second write will overwrite the first one.

I'd go for `map` because it's more general than `set`.

Remember though that you'll need to limit the distribution of  map keys somehow in the yaml (similarly to how you limit the distribution of partition keys using `population: exp(1..10000000)`), so the map doesn't grow without limit.

**Comment by amoskong** [comment] 2020-03-06 09:02
> @amoskong
> 
> It's good that we test collections in cdc longevity, but `list` is maybe not the best choice. You could use `map` or `set` because if you put the same key twice into a `map`/`set`, the second write will overwrite the first one.
> 
> I'd go for `map` because it's more general than `set`.

Unfortunately Cassandra-Stress doesn't support map type, it will be ignored in creating table, and fail in querying.

Cassandra-Stress error: `java.lang.UnsupportedOperationException: Because of this name: map_column if you removed it from the yaml and are still seeing this, make sure to drop table`

> Remember though that you'll need to limit the distribution of map keys somehow in the yaml (similarly to how you limit the distribution of partition keys using `population: exp(1..10000000)`), so the map doesn't grow without limit.


The population parameter didn't limited the items number of list.
For set<text>,  `size` parameter limits both the length of each item in the set, and the items number of the set.  The population also doesn't limit anything.

For set<int>, size limits the items number of the set, population limits the size of int number.

I will replace list with set.

**Comment by kbr-** [comment] 2020-03-06 09:23
> The population parameter didn't limited the items number of list.

That's because if you insert the same element twice into a list, it will just append it to the list twice. It won't overwrite. So you could keep inserting e.g. `0` into a list and it will grow unbounded.

If you keep inserting `0` into a `set<int>`, the set will always have one element.

> For set, size parameter limits both the length of each item in the set, and the items number of the set. The population also doesn't limit anything.

I don't think that the size parameter works differently for sets. The size parameter only limits the length of each item, same as it did with lists. However, by limiting lengths of items, you limit the number of possible different items, thus you limit the size of the set, which is bounded by the number of possible different items.
But correct me if I'm wrong.

However, if I'm right, be careful when you're using `text`. `text` is a sequence of bytes, right? Which means that each character in `text` can have `256` different values. Which means that for `text`s of length `4`, there are `256^4 = 4294967296` possible different values, and we won't handle such big sets (it would require a long time to randomly generate all these different values, but with longevity I guess there will be a lot of different values generated over time...)

To be safe I would use integers from some relatively small interval.

**Comment by amoskong** [comment] 2020-03-06 10:04
I'm running another longevity only with limited set.
https://jenkins.scylladb.com/job/scylla-master/job/longevity/job/longevity-cdc-100gb-4h/4/console

**Comment by amoskong** [comment] 2020-03-06 19:38
> I'm running another longevity only with limited set.
> https://jenkins.scylladb.com/job/scylla-master/job/longevity/job/longevity-cdc-100gb-4h/4/console

https://jenkins.scylladb.com/job/scylla-master/job/longevity/job/longevity-cdc-100gb-4h/4/
This job PASSed.

```
    nums_set set<int>,
    names_set set<text>,

----

columnspec:
  - name: pkid
    population: exp(1..10000000)

  - name: nums_set
    size: fixed(5)
    population: exp(1..5)

  - name: names_set
    size: fixed(5)
    population: exp(1..5)
```

**Comment by haaawk** [comment] 2020-03-06 20:28
Hooray - closing the issue.

**Closed by haaawk** 2020-03-06 20:28 UTC
Labels: CDC, performance
