### ISSUE TITLE
Aws Ami install with t3a.medium fails.

### ISSUE THREAD

**Issue by ktjd123** [scylladb/scylla#8501] opened 2021-04-17 06:26 UTC
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [x] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash): 4.4.1
Cluster size: t3a.medium
OS (RHEL/CentOS/Ubuntu/AWS AMI): Ami (https://console.aws.amazon.com/ec2/v2/home?region=ap-northeast-2#LaunchInstanceWizard:ami=ami-0877b8cfa7ad62c24)

i3.large install successes.

**Comment by tzach** [comment] 2021-04-18 05:57
Can you please share the log?
Scylla AMI has a list of instance types it optimized for out of the box (like i3, i3en), but you can use it with other instance types if you run scylla_setup.

**Comment by ktjd123** [comment] 2021-04-18 09:40
@tzach Thank you for reply

```bash

   _____            _ _       _____  ____
  / ____|          | | |     |  __ \|  _ \
 | (___   ___ _   _| | | __ _| |  | | |_) |
  \___ \ / __| | | | | |/ _` | |  | |  _ <
  ____) | (__| |_| | | | (_| | |__| | |_) |
 |_____/ \___|\__, |_|_|\__,_|_____/|____/
               __/ |
              |___/

Version:
       4.4.1-0.20210406.00da6b5e9
Nodetool:
	nodetool help
CQL Shell:
	cqlsh
More documentation available at:
	http://www.scylladb.com/doc/
By default, Scylla sends certain information about this node to a data collection server. For information, see http://www.scylladb.com/privacy/

    t3a is not eligible for optimized automatic tuning!
To continue startup ScyllaDB on this instance, run 'sudo scylla_io_setup' then 'systemctl start scylla-server'.
For a list of optimized instance types and more EC2 instructions see 'http://www.scylladb.com/doc/getting-started-amazon/'"

[scyllaadm@ip-172-31-14-224 ~]$ sudo scylla_io_setup
tuning /sys/devices/pci0000:00/0000:00:04.0/nvme/nvme0/nvme0n1/nvme0n1p1
tuning /sys/devices/pci0000:00/0000:00:04.0/nvme/nvme0/nvme0n1
tuning: /sys/devices/pci0000:00/0000:00:04.0/nvme/nvme0/nvme0n1/queue/nomerges 2
tuning /sys/devices/pci0000:00/0000:00:04.0/nvme/nvme0/nvme0n1/nvme0n1p1
tuning /sys/devices/pci0000:00/0000:00:04.0/nvme/nvme0/nvme0n1/nvme0n1p1
tuning /sys/devices/pci0000:00/0000:00:04.0/nvme/nvme0/nvme0n1/nvme0n1p1
INFO  2021-04-18 09:32:41,932 [shard 0] iotune - /var/lib/scylla/view_hints passed sanity checks
INFO  2021-04-18 09:32:41,932 [shard 0] iotune - Disk parameters: max_iodepth=31 disks_per_array=1 minimum_io_size=512
Starting Evaluation. This may take a while...
Measuring sequential write bandwidth: 129 MB/s
Measuring sequential read bandwidth: 128 MB/s
Measuring random write IOPS: 3232 IOPS
Measuring random read IOPS: 2999 IOPS
Writing result to /etc/scylla.d/io_properties.yaml
Writing result to /etc/scylla.d/io.conf
[scyllaadm@ip-172-31-14-224 ~]$ systemctl start scylla-server
==== AUTHENTICATING FOR org.freedesktop.systemd1.manage-units ===
Authentication is required to manage system services or units.
Authenticating as: root
Password:
[scyllaadm@ip-172-31-14-224 ~]$
[scyllaadm@ip-172-31-14-224 ~]$ sudo systemctl start scylla-server
A dependency job for scylla-server.service failed. See 'journalctl -xe' for details.
[scyllaadm@ip-172-31-14-224 ~]$ journalctl -xe
 4월 18 09:37:16 ip-172-31-14-224.ap-northeast-2.compute.internal scylla_image_setup[1296]: Setting default listen_address=172.31.14.224
 4월 18 09:37:16 ip-172-31-14-224.ap-northeast-2.compute.internal scylla_image_setup[1296]: 2021-04-18 09:37:16,809 - [scylla_configure] - INFO - Setting default broadcast_rpc_address=172.31.14.224
 4월 18 09:37:16 ip-172-31-14-224.ap-northeast-2.compute.internal scylla_image_setup[1296]: Setting default broadcast_rpc_address=172.31.14.224
 4월 18 09:37:16 ip-172-31-14-224.ap-northeast-2.compute.internal scylla_image_setup[1296]: 2021-04-18 09:37:16,809 - [scylla_configure] - INFO - Setting default rpc_address=0.0.0.0
 4월 18 09:37:16 ip-172-31-14-224.ap-northeast-2.compute.internal scylla_image_setup[1296]: Setting default rpc_address=0.0.0.0
 4월 18 09:37:16 ip-172-31-14-224.ap-northeast-2.compute.internal scylla_image_setup[1296]: 2021-04-18 09:37:16,809 - [scylla_configure] - INFO - Setting default seed_provider=[{'class_name': 'org.apache.cassan
 4월 18 09:37:16 ip-172-31-14-224.ap-northeast-2.compute.internal scylla_image_setup[1296]: Setting default seed_provider=[{'class_name': 'org.apache.cassandra.locator.SimpleSeedProvider', 'parameters': [{'seed
 4월 18 09:37:16 ip-172-31-14-224.ap-northeast-2.compute.internal scylla_image_setup[1296]: 2021-04-18 09:37:16,809 - [scylla_configure] - INFO - Setting default endpoint_snitch=Ec2Snitch
 4월 18 09:37:16 ip-172-31-14-224.ap-northeast-2.compute.internal scylla_image_setup[1296]: Setting default endpoint_snitch=Ec2Snitch
 4월 18 09:37:16 ip-172-31-14-224.ap-northeast-2.compute.internal scylla_image_setup[1296]: 2021-04-18 09:37:16,809 - [scylla_configure] - INFO - Saving /etc/scylla/scylla.yaml
 4월 18 09:37:16 ip-172-31-14-224.ap-northeast-2.compute.internal scylla_image_setup[1296]: Saving /etc/scylla/scylla.yaml
 4월 18 09:37:17 ip-172-31-14-224.ap-northeast-2.compute.internal scylla_image_setup[1296]: is not found
 4월 18 09:37:17 ip-172-31-14-224.ap-northeast-2.compute.internal scylla_image_setup[1296]: Traceback (most recent call last):
 4월 18 09:37:17 ip-172-31-14-224.ap-northeast-2.compute.internal scylla_image_setup[1296]: File "/opt/scylladb/scylla-machine-image/libexec/scylla_create_devices", line 76, in <module>
 4월 18 09:37:17 ip-172-31-14-224.ap-northeast-2.compute.internal scylla_image_setup[1296]: create_raid(disk_devices)
 4월 18 09:37:17 ip-172-31-14-224.ap-northeast-2.compute.internal scylla_image_setup[1296]: File "/opt/scylladb/scylla-machine-image/libexec/scylla_create_devices", line 33, in create_raid
 4월 18 09:37:17 ip-172-31-14-224.ap-northeast-2.compute.internal scylla_image_setup[1296]: run(["/opt/scylladb/scripts/scylla_raid_setup", "--raiddev", "/dev/md0", "--disks", ",".join(devices),
 4월 18 09:37:17 ip-172-31-14-224.ap-northeast-2.compute.internal scylla_image_setup[1296]: File "/opt/scylladb/python3/lib64/python3.9/subprocess.py", line 524, in run
 4월 18 09:37:17 ip-172-31-14-224.ap-northeast-2.compute.internal scylla_image_setup[1296]: raise CalledProcessError(retcode, process.args,
 4월 18 09:37:17 ip-172-31-14-224.ap-northeast-2.compute.internal scylla_image_setup[1296]: subprocess.CalledProcessError: Command '['/opt/scylladb/scripts/scylla_raid_setup', '--raiddev', '/dev/md0', '--disks'
 4월 18 09:37:17 ip-172-31-14-224.ap-northeast-2.compute.internal scylla_image_setup[1296]: 2021-04-18 09:37:17,111 - [scylla_configure] - ERROR - Failed to create devices: Command '/opt/scylladb/scylla-machine
 4월 18 09:37:17 ip-172-31-14-224.ap-northeast-2.compute.internal scylla_image_setup[1296]: Failed to create devices: Command '/opt/scylladb/scylla-machine-image/scylla_create_devices ' returned non-zero exit s
 4월 18 09:37:17 ip-172-31-14-224.ap-northeast-2.compute.internal scylla_image_setup[1296]: Traceback (most recent call last):
 4월 18 09:37:17 ip-172-31-14-224.ap-northeast-2.compute.internal scylla_image_setup[1296]: File "/opt/scylladb/scylla-machine-image/libexec/scylla_image_setup", line 26, in <module>
 4월 18 09:37:17 ip-172-31-14-224.ap-northeast-2.compute.internal scylla_image_setup[1296]: run('/opt/scylladb/scylla-machine-image/scylla_configure.py', shell=True, check=True)
 4월 18 09:37:17 ip-172-31-14-224.ap-northeast-2.compute.internal scylla_image_setup[1296]: File "/opt/scylladb/python3/lib64/python3.9/subprocess.py", line 524, in run
 4월 18 09:37:17 ip-172-31-14-224.ap-northeast-2.compute.internal scylla_image_setup[1296]: raise CalledProcessError(retcode, process.args,
 4월 18 09:37:17 ip-172-31-14-224.ap-northeast-2.compute.internal scylla_image_setup[1296]: subprocess.CalledProcessError: Command '/opt/scylladb/scylla-machine-image/scylla_configure.py' returned non-zero exit
 4월 18 09:37:17 ip-172-31-14-224.ap-northeast-2.compute.internal systemd[1]: scylla-image-setup.service: main process exited, code=exited, status=1/FAILURE
 4월 18 09:37:17 ip-172-31-14-224.ap-northeast-2.compute.internal systemd[1]: Failed to start Scylla Cloud Image Setup service.
-- Subject: Unit scylla-image-setup.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit scylla-image-setup.service has failed.
--
-- The result is failed.
 4월 18 09:37:17 ip-172-31-14-224.ap-northeast-2.compute.internal systemd[1]: Dependency failed for Scylla Server.
-- Subject: Unit scylla-server.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit scylla-server.service has failed.
--
-- The result is dependency.
 4월 18 09:37:17 ip-172-31-14-224.ap-northeast-2.compute.internal systemd[1]: Dependency failed for Scylla JMX.
-- Subject: Unit scylla-jmx.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit scylla-jmx.service has failed.
--
-- The result is dependency.
 4월 18 09:37:17 ip-172-31-14-224.ap-northeast-2.compute.internal systemd[1]: Job scylla-jmx.service/start failed with result 'dependency'.
 4월 18 09:37:17 ip-172-31-14-224.ap-northeast-2.compute.internal systemd[1]: Dependency failed for Run Scylla Housekeeping daily mode.
-- Subject: Unit scylla-housekeeping-daily.timer has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit scylla-housekeeping-daily.timer has failed.
--
-- The result is dependency.
 4월 18 09:37:17 ip-172-31-14-224.ap-northeast-2.compute.internal sudo[1325]: pam_unix(sudo:session): session closed for user root
 4월 18 09:37:17 ip-172-31-14-224.ap-northeast-2.compute.internal systemd[1]: Job scylla-housekeeping-daily.timer/start failed with result 'dependency'.
 4월 18 09:37:17 ip-172-31-14-224.ap-northeast-2.compute.internal polkitd[1295]: Unregistered Authentication Agent for unix-process:1327:39301 (system bus name :1.23, object path /org/freedesktop/PolicyKit1/Aut
 4월 18 09:37:17 ip-172-31-14-224.ap-northeast-2.compute.internal systemd[1]: Dependency failed for Run Scylla Housekeeping restart mode.
-- Subject: Unit scylla-housekeeping-restart.timer has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit scylla-housekeeping-restart.timer has failed.
--
-- The result is dependency.
 4월 18 09:37:17 ip-172-31-14-224.ap-northeast-2.compute.internal systemd[1]: Job scylla-housekeeping-restart.timer/start failed with result 'dependency'.
 4월 18 09:37:17 ip-172-31-14-224.ap-northeast-2.compute.internal systemd[1]: Job scylla-server.service/start failed with result 'dependency'.
 4월 18 09:37:17 ip-172-31-14-224.ap-northeast-2.compute.internal systemd[1]: Unit scylla-image-setup.service entered failed state.
 4월 18 09:37:17 ip-172-31-14-224.ap-northeast-2.compute.internal systemd[1]: scylla-image-setup.service failed.

[scyllaadm@ip-172-31-14-224 ~]$
```

I added log for it.

**Comment by ktjd123** [comment] 2021-04-18 09:42
I think if this is expected and not optimized for this instance, I think it would be hard for starter to start with broken script. 😭

**Comment by tzach** [comment] 2021-04-18 10:07
Issue reproduced

**Comment by tzach** [comment] 2021-04-18 10:08
@syuu1228 can you please take a look

**Comment by yaronkaikov** [comment] 2021-04-20 09:27
Looks like it doesn't recognize the disks
```
subprocess.CalledProcessError: Command '['/opt/scylladb/scripts/scylla_raid_setup', '--raiddev', '/dev/md0', '--disks', '', '--root', '/var/lib/scylla', '--volume-role', 'all', '--update-fstab']' returned non-zero exit status 1.
```
@ktjd123 Can you share the output of `fdisl -l` ?

**Comment by tzach** [comment] 2021-04-20 09:30
@yaronkaikov you can try it yourself, it reproduce for me on the first try on  t3a.medium

**Comment by yaronkaikov** [comment] 2021-04-20 09:48
@tzach Looking into it

**Comment by syuu1228** [comment] 2021-04-21 06:53
Isn't it same issue with https://github.com/scylladb/scylla-machine-image/issues/111#issuecomment-805083342 ?

**Comment by yaronkaikov** [comment] 2021-04-21 06:57
According to https://www.scylladb.com/download/?platform=aws#open-source section #4 - we must have more then one volume attached to instance
When creating the image with another volume it's working

**Comment by syuu1228** [comment] 2021-04-21 06:58
Yes, and t3a.medium does not attached any additional disks by default, so it fails.

**Comment by syuu1228** [comment] 2021-04-21 07:01
And I recently merged PR that avoids python traceback and print better error message to journal log, when data disks not found:
https://github.com/scylladb/scylla-machine-image/pull/115

**Comment by tzach** [comment] 2021-04-21 07:43
@syuu1228 in this case, can we replace 
"t3a is not eligible for optimized automatic tuning! To continue startup ScyllaDB on this instance, run 'sudo scylla_io_setup' then 'systemctl start scylla-server'."

with something like "t3a is not eligible for optimized automatic tuning! 
To continue startup ScyllaDB on this instance, you need to attach an additional disk, then run 'sudo scylla_io_setup' then 'systemctl start scylla-server'."

**Comment by ktjd123** [comment] 2021-04-22 05:50
Oops I didn't see that the instance needs additional storage. Tho adding more info to error would be great!

**Closed** 2021-05-19 08:14 UTC
Labels: AWS, UX, onboarding
