### ISSUE TITLE
Stuck on "Waiting for Scylla to start",  using M1 mac and Docker

### ISSUE THREAD

**Issue by SpruceGoose429** [scylladb/scylla#9691] opened 2021-11-26 15:28 UTC
Running `yarn localsetup` never completes, and continually prints "Waiting for Scylla to start".

System:
macOS Montery (version 12.0)
MacBook Pro (16-inch, 2021)
Chip: Apple M1 Pro
Memory 16 GB

I tried a few versions in my Docerfile.  Here are the current contents...
`FROM scylladb/scylla:4.6.dev-0.20210801.3089558f8
COPY scylla.yaml /etc/scylla/scylla.yaml`

And some lines from `docker logs web-scylla-1`...
`john@Johns-MBP web % docker logs web-scylla-1
running: (['/opt/scylladb/scripts/scylla_dev_mode_setup', '--developer-mode', '1'],)
running: (['/opt/scylladb/scripts/scylla_io_setup'],)
2021-11-24 21:54:17,420 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
2021-11-24 21:54:17,423 INFO Included extra file "/etc/supervisord.conf.d/node-exporter.conf" during parsing
2021-11-24 21:54:17,423 INFO Included extra file "/etc/supervisord.conf.d/rsyslog.conf" during parsing
2021-11-24 21:54:17,423 INFO Included extra file "/etc/supervisord.conf.d/scylla-housekeeping.conf" during parsing
2021-11-24 21:54:17,423 INFO Included extra file "/etc/supervisord.conf.d/scylla-jmx.conf" during parsing
2021-11-24 21:54:17,423 INFO Included extra file "/etc/supervisord.conf.d/scylla-server.conf" during parsing
2021-11-24 21:54:17,423 INFO Included extra file "/etc/supervisord.conf.d/sshd-server.conf" during parsing
2021-11-24 21:54:17,550 INFO RPC interface 'supervisor' initialized
2021-11-24 21:54:17,550 CRIT Server 'inet_http_server' running without any HTTP authentication checking
2021-11-24 21:54:17,551 INFO supervisord started with pid 76
2021-11-24 21:54:18,562 INFO spawned: 'scylla' with pid 85
2021-11-24 21:54:18,570 INFO spawned: 'scylla-housekeeping' with pid 87
2021-11-24 21:54:18,575 INFO spawned: 'sshd' with pid 89
2021-11-24 21:54:18,578 INFO spawned: 'scylla-jmx' with pid 91
2021-11-24 21:54:18,581 INFO spawned: 'rsyslog' with pid 93
2021-11-24 21:54:18,584 INFO spawned: 'node-exporter' with pid 94
Error during class init for object 'rsyslog runtime' - failing...
rsyslogd initializiation failed - global classes could not be initialized.
Did you do a "make install"?
Suggested action: run rsyslogd with -d -n options to see what exactly fails.
rsyslogd: run failed with error 1 (see rsyslog.h or try http://www.rsyslog.com/e/-1 to learn what that number means)
2021-11-24 21:54:18,661 INFO exited: rsyslog (exit status 1; not expected)
Generating public/private ed25519 key pair.
Your identification has been saved in /etc/ssh/ssh_host_ed25519_key.
Your public key has been saved in /etc/ssh/ssh_host_ed25519_key.pub.`
-some more lines here-
`Could not load host key: /etc/ssh/ssh_host_ecdsa_key
Connecting to http://localhost:10000
Starting the JMX server
2021-11-24 21:54:22,846 INFO spawned: 'rsyslog' with pid 174
Error during class init for object 'rsyslog runtime' - failing...
rsyslogd initializiation failed - global classes could not be initialized.
Did you do a "make install"?
Suggested action: run rsyslogd with -d -n options to see what exactly fails.
rsyslogd: run failed with error 1 (see rsyslog.h or try http://www.rsyslog.com/e/-1 to learn what that number means)
2021-11-24 21:54:22,891 INFO exited: rsyslog (exit status 1; not expected)
JMX is enabled to receive remote connections on port: 7199
Traceback (most recent call last):
  File "/opt/scylladb/scripts/libexec/scylla-housekeeping", line 197, in <module>
    args.func(args)
  File "/opt/scylladb/scripts/libexec/scylla-housekeeping", line 123, in check_version
    current_version = sanitize_version(get_api('/storage_service/scylla_release_version'))
  File "/opt/scylladb/scripts/libexec/scylla-housekeeping", line 82, in get_api
    return get_json_from_url("http://" + api_address + path)
  File "/opt/scylladb/scripts/libexec/scylla-housekeeping", line 77, in get_json_from_url
    raise RuntimeError(f'Failed to get "{path}" due to the following error: {retval}')
RuntimeError: Failed to get "http://localhost:10000/storage_service/scylla_release_version" due to the following error: <urlopen error [Errno 99] Cannot assign requested address>
2021-11-24 21:54:26,795 INFO spawned: 'rsyslog' with pid 213
Error during class init for object 'rsyslog runtime' - failing...
rsyslogd initializiation failed - global classes could not be initialized.
Did you do a "make install"?
Suggested action: run rsyslogd with -d -n options to see what exactly fails.
rsyslogd: run failed with error 1 (see rsyslog.h or try http://www.rsyslog.com/e/-1 to learn what that number means)
2021-11-24 21:54:26,967 INFO exited: rsyslog (exit status 1; not expected)
2021-11-24 21:54:26,975 INFO gave up: rsyslog entered FATAL state, too many start retries too quickly
2021-11-24 21:54:28,079 INFO exited: scylla (terminated by SIGKILL; not expected)
2021-11-24 21:54:29,103 INFO spawned: 'scylla' with pid 216
2021-11-24 21:54:30,108 INFO success: scylla entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2021-11-24 21:54:36,119 INFO exited: scylla (terminated by SIGKILL; not expected)
2021-11-24 21:54:37,153 INFO spawned: 'scylla' with pid 249
2021-11-24 21:54:38,162 INFO success: scylla entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2021-11-24 21:54:43,940 INFO exited: scylla (terminated by SIGKILL; not expected)`

**Comment by cjbottaro** [comment] 2021-11-26 18:08
That image starts up for me, but segfaults on certain CQL statements...
```
Segmentation fault on shard 2.
Backtrace:
  0x2622a23
  0x264e7c3
  linux-vdso.so.1+0x79b
  0x140ce3f
  0x140d207
  0x16e93df
  0x26329c3
  0x2633a6b
  0x264ed17
  0x260f9ff
  /opt/scylladb/libreloc/libpthread.so.0+0x8007
  /opt/scylladb/libreloc/libc.so.6+0xda59b
2021-11-26 18:02:54,399 INFO exited: scylla (terminated by SIGSEGV; not expected)
2021-11-26 18:02:55,407 INFO spawned: 'scylla' with pid 1789
```

I'm on M1 Max.

**Comment by slivne** [comment] 2021-11-30 13:00
@SpruceGoose429 / @cjbottaro - this is a duplicate of #8642 - yaron provided a reference for an image you can use

**Comment by slivne** [comment] 2022-01-14 20:30
@SpruceGoose429 / @cjbottaro  - closing this issue - if you still have problems on M1 - please post and we can reopen and help (we have people internally running on Mac M1 and it works for them)

**Closed by slivne** 2022-01-14 20:30 UTC
Labels: User Request, arm
