### ISSUE TITLE
sstableloader to support 2.2 sstable format

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#1300] opened 2016-05-31 07:53 UTC
Migrating from Cassandra 2.2.x to Scylla will be easier with sstableloader reading the source tables disk format.

This is not the same, and should be easier, than #616 which require Scylla itself to support the format.

**Comment by elcallio** [comment] 2016-06-15 13:20
If I read the changes in format "la" (2.2.0), the only change is removal of ksname and cfname from the sstable file name, so in essence, we'd need to copy/backport the ssstable descriptor parsing code from 2.2, either into our origin, or into a parallel class. Probably not very hard. 

Either upgrading the whole java-tools to 2.2 or backporting descriptor parsing into our tree will also keep sstable2json etc working with 2.2 tables.

**Comment by slivne** [comment] 2016-06-16 11:34
@elcallio  Pekka - has done an analysis of delta for CQL v 3.3.1 ... among others there are additional types (https://github.com/scylladb/scylla/issues/1284) - doesn't that mean that we need to extend the code more then what you have listed

**Comment by elcallio** [comment] 2016-06-19 11:38
Sorry, I read the issue literally. ☺
If I understand pekkas summary, it is mainly new types added. However, that
will require the type support for those, in both cql driver, and origin
Cfmetadata parse and children. I.e probably at least an update of cql
grammar and support types.
Den 16 jun 2016 13:34 skrev "Shlomi Livne" <notifications@github.com>:

**Comment by elcallio** [comment] 2016-06-20 09:26
Checking on source changes in Origin tree, the Java part of added CQL types is probably fairly easy to cherry-pick from their tree. The cqlsh support however is not. There seem to be a _lot_ of changes between our version and where the new types came into origin 2.x tree, so this does not apply cleanly. Nor does there seem to be any one or two easy patches before to cherry-pick. :-P
This however seems to be fairly closely tied to us supporting these types internally as well? Are we doing a cqlsh backport?

**Comment by avikivity** [comment] 2016-06-20 09:57
We could rebase/merge latest 2.2 into scylla-tools-java, could we not?

**Comment by elcallio** [comment] 2016-06-20 10:49
That was my initial suggestion also, but @slivne expressed some concerns about JMX/nodetool compatibility 2.1/2.2. I still think solving any JMX interface issues is way simpler than trying to cherry-pick real code changes though. Just trying to motivate it (above).

**Comment by slivne** [comment] 2016-06-20 11:33
@amnonh - what would it take to move to nodetool of 2.2

**Comment by amnonh** [comment] 2016-06-20 13:42
it's not just the nodetool
we need to move the jmx.It's hard to tell without going over each of the
changes they made,
I guess a few days assuming there is nothing fundamentally different

**Comment by penberg** [comment] 2016-06-20 19:54
@amnonh Few days, eh? Probably more than that, but completely agreed that it's not *that* massive a change.

**Comment by amnonh** [comment] 2016-06-21 07:42
On Mon, Jun 20, 2016 at 10:54 PM, Pekka Enberg <notifications@github.com>
wrote:

> @amnonh <https://github.com/amnonh> Few days, eh? Probably more than
> that, but completely agreed that it's not *that* massive a change.
>
It's hard to tell without actually going over all the MBean and see what
they changed in each of them.

**Comment by elcallio** [comment] 2016-07-11 11:03
I went through the MBean changes between origin between 2.1 and 2.2 (though somewhat cursory). They seem pretty benign, mainly a bunch of previously deprecated methods dropped + some new stuff, that mainly seem to be cosmetic changes. 
Afaict, it should be fairly easy to adapt our MBeans in scylla-jmx to conform to both interfaces (2.1 + 2.2) (if need be). 
Imho, updating the scylla-tools tree is the best option to handle the cql changes.

**Comment by slivne** [comment] 2016-11-06 11:16
in review

**Comment by penberg** [comment] 2017-01-20 06:17
@slivne I think we should have closed this issue, but kept https://github.com/scylladb/scylla/issues/616 open.

**Comment by roydahan** [comment] 2017-01-22 10:11
I'm working (finalizing my work) to add the necessary tests to our dtest regression.
If you want, I can close this one when we merge it.

**Comment by penberg** [comment] 2017-01-22 11:18
@roydahan 👍

**Closed** 2017-02-12 12:24 UTC
Labels: enhancement
