### ISSUE TITLE
Failed decoding result column "dropped_time" (system_schema.dropped_columns table) of type timestamp: date value out of range

### ISSUE THREAD

**Issue by juliayakovlev** [scylladb/scylla#7186] opened 2020-09-07 09:38 UTC
Installation details
Scylla version (or git commit hash): 666.development-0.20200905.df3ea2443
Cluster size: 3 nodes
OS (RHEL/CentOS/Ubuntu/AWS AMI): ami-09e3eb65dbf3aba6e

There is the problem to run select from ```system_schema.dropped_columns``` because of wrong timestamp value in the ```dropped_time``` column.

When I connected to the node and run this query manually using cqlsh I got DataOverFlowWarning:
![Screenshot from 2020-09-06 16-17-57](https://user-images.githubusercontent.com/34435448/92373053-726c0100-f106-11ea-8b8f-eb12e1cab441.png)

But when I ran this query again - no warning was received.

When select is running from test (via python driver) using ```session.execute```,  get failure ```cassandra.DriverException: Failed decoding result column "dropped_time" of type timestamp: date value out of range```:

```
< t:2020-09-06 15:59:01,661 f:common.py       l:1080 c:utils                p:DEBUG > Executing CQL 'SELECT * FROM system_schema.dropped_columns LIMIT 1'...
< t:2020-09-06 15:59:01,663 f:libevreactor.py l:361  c:cassandra.connection p:ERROR > Error decoding response from Cassandra. ver(3); flags(0000); stream(11); op(8); offset(9); len(318); buffer: b'\x83\x00\x00\x0b\x08\x00\x00\x01>\x00\x0
0\x00\x02\x00\x00\x00\x00\x00\x00\x00\x05\x00\rsystem_schema\x00\x0fdropped_columns\x00\rkeyspace_name\x00\r\x00\rsystem_schema\x00\x0fdropped_columns\x00\ntable_name\x00\r\x00\rsystem_schema\x00\x0fdropped_columns\x00\x0bcolumn_name\x00
\r\x00\rsystem_schema\x00\x0fdropped_columns\x00\x0cdropped_time\x00\x0b\x00\rsystem_schema\x00\x0fdropped_columns\x00\x04type\x00\r\x00\x00\x00\x01\x00\x00\x00\x06system\x00\x00\x00\x05local\x00\x00\x00\x1dscylla_cpu_sharding_algorithm\
x00\x00\x00\x08\x00\x05\xae\xa6\xbe\x07\xe3\xcf\x00\x00\x00\x04text' < t:2020-09-06 15:59:01,663 f:libevreactor.py l:361  c:cassandra.connection p:ERROR > Error decoding response from Cassandra. ver(3); flags(0000); stream(11); op(8); of
fset(9); len(318); buffer: b'\x83\x00\x00\x0b\x08\x00\x00\x01>\x00\x00\x00\x02\x00\x00\x00\x00\x00\x00\x00\x05\x00\rsystem_schema\x00\x0fdropped_columns\x00\rkeyspace_name\x00\r\x00\rsystem_schema\x00\x0fdropped_columns\x00\ntable_name\x
00\r\x00\rsystem_schema\x00\x0fdropped_columns\x00\x0bcolumn_name\x00\r\x00\rsystem_schema\x00\x0fdropped_columns\x00\x0cdropped_time\x00\x0b\x00\rsystem_schema\x00\x0fdropped_columns\x00\x04type\x00\r\x00\x00\x00\x01\x00\x00\x00\x06syst
em\x00\x00\x00\x05local\x00\x00\x00\x1dscylla_cpu_sharding_algorithm\x00\x00\x00\x08\x00\x05\xae\xa6\xbe\x07\xe3\xcf\x00\x00\x00\x04text'
< t:2020-09-06 15:59:01,663 f:libevreactor.py l:361  c:cassandra.connection p:ERROR > Traceback (most recent call last):
< t:2020-09-06 15:59:01,663 f:libevreactor.py l:361  c:cassandra.connection p:ERROR >   File "cassandra/obj_parser.pyx", line 72, in cassandra.obj_parser.TupleRowParser.unpack_row
< t:2020-09-06 15:59:01,663 f:libevreactor.py l:361  c:cassandra.connection p:ERROR >   File "cassandra/deserializers.pxd", line 41, in cassandra.deserializers.from_binary
< t:2020-09-06 15:59:01,663 f:libevreactor.py l:361  c:cassandra.connection p:ERROR >   File "cassandra/deserializers.pyx", line 143, in cassandra.deserializers.DesDateType.deserialize
< t:2020-09-06 15:59:01,663 f:libevreactor.py l:361  c:cassandra.connection p:ERROR >   File "cassandra/cython_utils.pyx", line 62, in cassandra.cython_utils.datetime_from_timestamp
< t:2020-09-06 15:59:01,663 f:libevreactor.py l:361  c:cassandra.connection p:ERROR > OverflowError: date value out of range
< t:2020-09-06 15:59:01,663 f:libevreactor.py l:361  c:cassandra.connection p:ERROR > 
< t:2020-09-06 15:59:01,663 f:libevreactor.py l:361  c:cassandra.connection p:ERROR > During handling of the above exception, another exception occurred:
< t:2020-09-06 15:59:01,663 f:libevreactor.py l:361  c:cassandra.connection p:ERROR > 
< t:2020-09-06 15:59:01,663 f:libevreactor.py l:361  c:cassandra.connection p:ERROR > Traceback (most recent call last):
< t:2020-09-06 15:59:01,663 f:libevreactor.py l:361  c:cassandra.connection p:ERROR >   File "cassandra/row_parser.pyx", line 38, in cassandra.row_parser.make_recv_results_rows.recv_results_rows
< t:2020-09-06 15:59:01,663 f:libevreactor.py l:361  c:cassandra.connection p:ERROR >   File "cassandra/obj_parser.pyx", line 31, in cassandra.obj_parser.ListParser.parse_rows
< t:2020-09-06 15:59:01,663 f:libevreactor.py l:361  c:cassandra.connection p:ERROR >   File "cassandra/obj_parser.pyx", line 74, in cassandra.obj_parser.TupleRowParser.unpack_row
< t:2020-09-06 15:59:01,663 f:libevreactor.py l:361  c:cassandra.connection p:ERROR > cassandra.DriverException: Failed decoding result column "dropped_time" of type timestamp: date value out of range
< t:2020-09-06 15:59:01,663 f:libevreactor.py l:361  c:cassandra.connection p:ERROR > 
< t:2020-09-06 15:59:01,663 f:libevreactor.py l:361  c:cassandra.connection p:ERROR > During handling of the above exception, another exception occurred:
< t:2020-09-06 15:59:01,663 f:libevreactor.py l:361  c:cassandra.connection p:ERROR > 
< t:2020-09-06 15:59:01,663 f:libevreactor.py l:361  c:cassandra.connection p:ERROR > Traceback (most recent call last):
< t:2020-09-06 15:59:01,663 f:libevreactor.py l:361  c:cassandra.connection p:ERROR >   File "cassandra/obj_parser.pyx", line 72, in cassandra.obj_parser.TupleRowParser.unpack_row
< t:2020-09-06 15:59:01,663 f:libevreactor.py l:361  c:cassandra.connection p:ERROR >   File "cassandra/deserializers.pxd", line 41, in cassandra.deserializers.from_binary
< t:2020-09-06 15:59:01,663 f:libevreactor.py l:361  c:cassandra.connection p:ERROR >   File "cassandra/deserializers.pyx", line 143, in cassandra.deserializers.DesDateType.deserialize
< t:2020-09-06 15:59:01,663 f:libevreactor.py l:361  c:cassandra.connection p:ERROR >   File "cassandra/cython_utils.pyx", line 62, in cassandra.cython_utils.datetime_from_timestamp
< t:2020-09-06 15:59:01,663 f:libevreactor.py l:361  c:cassandra.connection p:ERROR > OverflowError: date value out of range
< t:2020-09-06 15:59:01,663 f:libevreactor.py l:361  c:cassandra.connection p:ERROR > 
< t:2020-09-06 15:59:01,663 f:libevreactor.py l:361  c:cassandra.connection p:ERROR > During handling of the above exception, another exception occurred:
< t:2020-09-06 15:59:01,663 f:libevreactor.py l:361  c:cassandra.connection p:ERROR > 
< t:2020-09-06 15:59:01,663 f:libevreactor.py l:361  c:cassandra.connection p:ERROR > Traceback (most recent call last):
< t:2020-09-06 15:59:01,663 f:libevreactor.py l:361  c:cassandra.connection p:ERROR >   File "cassandra/connection.py", line 1074, in cassandra.connection.Connection.process_msg
< t:2020-09-06 15:59:01,663 f:libevreactor.py l:361  c:cassandra.connection p:ERROR >   File "cassandra/protocol.py", line 1189, in cassandra.protocol._ProtocolHandler.decode_message
< t:2020-09-06 15:59:01,663 f:libevreactor.py l:361  c:cassandra.connection p:ERROR >   File "cassandra/protocol.py", line 740, in cassandra.protocol.ResultMessage.recv_body
< t:2020-09-06 15:59:01,663 f:libevreactor.py l:361  c:cassandra.connection p:ERROR >   File "cassandra/protocol.py", line 726, in cassandra.protocol.ResultMessage.recv
< t:2020-09-06 15:59:01,663 f:libevreactor.py l:361  c:cassandra.connection p:ERROR >   File "cassandra/row_parser.pyx", line 46, in cassandra.row_parser.make_recv_results_rows.recv_results_rows
< t:2020-09-06 15:59:01,663 f:libevreactor.py l:361  c:cassandra.connection p:ERROR >   File "cassandra/obj_parser.pyx", line 57, in cassandra.obj_parser.TupleRowParser.unpack_row
< t:2020-09-06 15:59:01,663 f:libevreactor.py l:361  c:cassandra.connection p:ERROR >   File "cassandra/obj_parser.pyx", line 74, in cassandra.obj_parser.TupleRowParser.unpack_row
< t:2020-09-06 15:59:01,663 f:libevreactor.py l:361  c:cassandra.connection p:ERROR > cassandra.DriverException: Failed decoding result column "dropped_time" of type timestamp: date value out of range
```

Recreated every run

**Comment by bhalevy** [comment] 2020-09-08 08:57
It's a dupilcate of https://github.com/scylladb/scylla/issues/7175

**Comment by bhalevy** [comment] 2020-09-08 08:59
I wonder why you started seeing it only now.
Does it not happen with 4.2?

**Comment by bhalevy** [comment] 2020-09-08 09:06
Sorry, closed by mistake.  Although #7175 is the root cause, let's make sure there wasn't some other patch that exposed it at this level.

**Comment by juliayakovlev** [comment] 2020-09-08 09:34
> I wonder why you started seeing it only now.
> Does it not happen with 4.2?

I didn't check 4.2. Maybe @aleksbykov  has seen it?

**Comment by aleksbykov** [comment] 2020-09-08 09:40
@juliayakovlev @bhalevy Didn't get see such error. But will take closer look with rc4

**Comment by roydahan** [comment] 2020-09-08 16:32
@juliayakovlev what test detected this issue?

**Comment by juliayakovlev** [comment] 2020-09-09 06:59
> @juliayakovlev what test detected this issue?

I got it in the my staging longevity-10gb-3h.yaml test, when worked on SnapshotOperation nemesis task.

**Comment by bhalevy** [comment] 2020-09-09 11:37
I reproduced this with Scylla version 4.1.6-0.20200831.6d9ff622d
This is not a regression.
```
/local/home/bhalevy/dev/scylla-tools-java/bin/cqlsh.py:398: DateOverFlowWarning: Some timestamps are larger than Python datetime can represent. Timestamps are displayed in milliseconds from epoch.

 keyspace_name | table_name | column_name                   | dropped_time     | type
---------------+------------+-------------------------------+------------------+------
        system |      local | scylla_cpu_sharding_algorithm | 1599651354784157 | text
        system |      local |             scylla_msb_ignore | 1599651354784159 |  int
        system |      local |              scylla_nr_shards | 1599651354784159 |  int
```

**Comment by slivne** [comment] 2020-09-13 09:06
closing and adding  comment in #7175 that this needs to be tested as well

**Closed by slivne** 2020-09-13 09:06 UTC
