### ISSUE TITLE
scylla_setup failing with dependency errors

### ISSUE THREAD

**Issue by kolasani83** [scylladb/scylla#7153] opened 2020-08-31 17:17 UTC
Iam trying to install scylla 4.1.4 on ubuntu 16 server which has no access to internet.
So i down loaded scylla packages on system with internet access and installing them with dpkg -i *

openjdk-8-jre-headless_8u265-b01-0ubuntu2~16.04_amd64.deb
apt-transport-https_1.2.32ubuntu0.1_amd64.deb
ca-certificates-java_20160321ubuntu1_all.deb
libxtst6.deb
libxi6.deb
libfontconfig1_2.11.94-0ubuntu1.1_amd64.deb
libpcsclite1_1.8.14-1ubuntu1.16.04.1_amd64.deb
libxrender1.deb
ntp.deb
ntpdate.deb

scylla-manager-client_2.1.0-0.20200707.c650b46d-0ubuntu1~xenial_amd64.deb
scylla-manager-agent_2.1.0-0.20200707.c650b46d-0ubuntu1~xenial_amd64.deb
scylla-jmx_4.1.4-20200809.d2dd8d027ce-1_all.deb
scylla-python3_3.7.7-0.20200809.76f4bc4c6f0-1_amd64.deb
scylla-kernel-conf_4.1.4-0.20200809.76f4bc4c6f0-1_amd64.deb
scylla-conf_4.1.4-0.20200809.76f4bc4c6f0-1_amd64.deb
scylla-server_4.1.4-0.20200809.76f4bc4c6f0-1_amd64.deb
scylla_4.1.4-0.20200809.76f4bc4c6f0-1_amd64.deb
scylla-tools-core_4.1.4-20200809.4492e12926d-1_all.deb
scylla-tools_4.1.4-20200809.4492e12926d-1_all.deb

when i ran scylla_setup iam getting below error.

root@ip-10-23-198-218:/tmp/openjdk_package# scylla_setup --no-raid-setup --no-enable-service  --no-sysconfig-setup
This EC2 instance is optimized for Scylla.
WARN  2020-08-31 17:03:37,763 [shard 0] iotune - Available space on filesystem at /var/tmp/mnt: 124 MB: is less than recommended: 10 GB
INFO  2020-08-31 17:03:37,763 [shard 0] iotune - /var/tmp/mnt passed sanity checks
This is a supported kernel version.
You current Scylla release is 4.1.4 while the latest patch release is 4.1.5, update for the latest bug fixes and improvements
Reading package lists... Done
Building dependency tree
Reading state information... Done
ntp is already the newest version (1:4.2.8p4+dfsg-3ubuntu5.10).
ntpdate is already the newest version (1:4.2.8p4+dfsg-3ubuntu5.10).
You might want to run 'apt-get -f install' to correct these:
The following packages have unmet dependencies:
 libfontconfig1 : Depends: fontconfig-config (= 2.11.94-0ubuntu1.1) but it is not going to be installed
 libxtst6 : Depends: x11-common but it is not going to be installed
E: Unmet dependencies. Try 'apt-get -f install' with no packages (or specify a solution).
Traceback (most recent call last):
  File "/opt/scylladb/scripts/libexec/scylla_ntp_setup", line 45, in <module>
    run('apt-get install -y ntp ntpdate')
  File "/opt/scylladb/scripts/scylla_util.py", line 340, in run
    return subprocess.check_call(cmd, shell=shell, stdout=stdout, stderr=stderr, env=scylla_env)
  File "/opt/scylladb/python3/lib64/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['apt-get', 'install', '-y', 'ntp', 'ntpdate']' returned non-zero exit status 100.
NTP setup failed.

**Comment by pidiaquez** [comment] 2020-08-31 21:37
Hi 
      Please double check ntp package got installed when you issued the dpkg -i *

`apt list | grep installed | grep -i ntp`

if the ntp packages are already installed you can try passing to **--no-ntp-setup**

`scylla_setup --no-raid-setup --no-enable-service --no-sysconfig-setup  --no-ntp-setup`

Thanks

**Comment by kolasani83** [comment] 2020-08-31 22:55
apt list | grep installed | grep -i ntp

ntp/now 1:4.2.8p4+dfsg-3ubuntu5.10 amd64 [installed,local]
ntpdate/now 1:4.2.8p4+dfsg-3ubuntu5.10 amd64 [installed,local]

Now iam getting this error.
 scylla_setup --no-raid-setup --no-enable-service --no-sysconfig-setup --no-ntp-setup
This EC2 instance is optimized for Scylla.
WARN  2020-08-31 22:54:22,735 [shard 0] iotune - Available space on filesystem at /var/tmp/mnt: 124 MB: is less than recommended: 10 GB
INFO  2020-08-31 22:54:22,735 [shard 0] iotune - /var/tmp/mnt passed sanity checks
This is a supported kernel version.
You current Scylla release is 4.1.4 while the latest patch release is 4.1.5, update for the latest bug fixes and improvements
Reading package lists... Done
Building dependency tree
Reading state information... Done
You might want to run 'apt-get -f install' to correct these:
The following packages have unmet dependencies:
 apport : Conflicts: core-dump-handler
 libfontconfig1 : Depends: fontconfig-config (= 2.11.94-0ubuntu1.1) but it is not going to be installed
 libxtst6 : Depends: x11-common but it is not going to be installed
 systemd-coredump : Depends: libdw1 (>= 0.158) but it is not going to be installed
                    Conflicts: core-dump-handler
E: Unmet dependencies. Try 'apt-get -f install' with no packages (or specify a solution).
Traceback (most recent call last):
  File "/opt/scylladb/scripts/libexec/scylla_coredump_setup", line 49, in <module>
    run('apt-get install -y systemd-coredump')
  File "/opt/scylladb/scripts/scylla_util.py", line 340, in run
    return subprocess.check_call(cmd, shell=shell, stdout=stdout, stderr=stderr, env=scylla_env)
  File "/opt/scylladb/python3/lib64/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['apt-get', 'install', '-y', 'systemd-coredump']' returned non-zero exit status 100.
coredump setup failed.

**Comment by pidiaquez** [comment] 2020-09-01 00:02
Hi 

    As a workaround to succeed on the install , ( with the disadvantage of having coredump disabled )  

you can add the parameter   **--no-coredump-setup** to scylla_setup

like this:

`scylla_setup --no-raid-setup --no-enable-service --no-sysconfig-setup --no-ntp-setup --no-coredump-setup `

else you need to identify the .deb package associated with **libdw1** on ubuntu 16 , and install that one first ( dpkg -i )

Thanks

Pablo

**Comment by kolasani83** [comment] 2020-09-01 02:21
Even after installing libdw1 package, i got the below error. Now i can bypass CPU scaling governor check too. So it may be successful. But do we have any pre defined list of packages that scylla depends so we can install them before configuring scylla.




root@ip-10-23-239-246:/tmp/openjdk_package# apt --installed list | grep -i libdw1

libdw1/now 0.165-3ubuntu1.2 amd64 [installed,local]

The following packages have unmet dependencies:
 cpufrequtils : Depends: libcpufreq0 (>= 006) but it is not going to be installed
 libdw1 : Depends: libelf1 (= 0.165-3ubuntu1.2) but 0.165-3ubuntu1.1 is to be installed
 libfontconfig1 : Depends: fontconfig-config (= 2.11.94-0ubuntu1.1) but it is not going to be installed
 libxtst6 : Depends: x11-common but it is not going to be installed
E: Unmet dependencies. Try 'apt-get -f install' with no packages (or specify a solution).
Traceback (most recent call last):
  File "/opt/scylladb/scripts/libexec/scylla_cpuscaling_setup", line 36, in <module>
    run('apt-get install -y cpufrequtils')
  File "/opt/scylladb/scripts/scylla_util.py", line 340, in run
    return subprocess.check_call(cmd, shell=shell, stdout=stdout, stderr=stderr, env=scylla_env)
  File "/opt/scylladb/python3/lib64/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['apt-get', 'install', '-y', 'cpufrequtils']' returned non-zero exit status 100.

**Comment by pidiaquez** [comment] 2020-09-01 05:20
Hi 

    for skipping the cpu scaling governor,  add  **--no-cpuscaling-setup**

Thanks

**Comment by slivne** [comment] 2020-09-06 09:50
@amoskong / @penberg - lets verify this with the offlineinstaller part of 4.3 - aside of scylla and java what else needs to be installed and provided so scylla installation will succeed.

**Comment by amoskong** [comment] 2020-09-07 02:27
Currently the offline (root & nonroot) install can success by skipping some setup, the openjdk8 is the only necessary dependency. If we/users don't want to skip any setup step, then it's a problem.

```
Necessary:
- Openjdk 8 / openjdk 11

Optional:
- Ntp / ntpdate
  - Workaround: skip ntp install/setup by `--no-ntp-setup`
- Node_exporter:  issue #2190
  - Workaround: skip ntp install/setup by `--no-node-exporter`
- Systemd-coredump
  - Workaround: skip coredump setup by `--no-coredump-setup`
- Cpufrequtils / cpupowerutils
  - Workaround: skip cpuscaling setup by `--no-cpuscaling-setup`
- Xfsprogs
  - Workaround: skip raid setup by `--no-raid-setup`, skip kernel check by `--no-kernel-check`
- Mdadm
  - Workaround: skip raid setup by `--no-raid-setup`
- libhugetlbfs-bin/ Hugepages
  - Can’t skip, I will report a new issue
```

**Comment by amoskong** [comment] 2020-09-07 04:23
Failed to build v237, v239 on CentOS8, but successfully built latest master of systemd (https://github.com/systemd/systemd/commit/6743a1caf4037f03dc51a1277855018e4ab61957).
Then I can see scylla logs by `journalctl --user  -u scylla-server -f`

[scylla-test@artifacts-centos8-jenkins-db-node-4f555251-0-1 build]$ systemd-run --version
systemd 246 (246-561-g6743a1c)
+PAM +AUDIT +SELINUX +IMA -APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 -ZSTD +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=unified

### Build steps:

```
git clone https://github.com/systemd/systemd
sudo dnf builddep systemd
cd systemd/
meson build 
cd build/
sudo meson install
```

**Comment by penberg** [comment] 2020-09-07 06:48
Perhaps `scylla_setup` needs an `--offline` flag as I suggested in a related bug https://github.com/scylladb/scylla/issues/7182.

@amoskong that `systemd` comment looks unrelated -- did you comment on the wrong ticket?

**Comment by avikivity** [comment] 2020-09-07 08:50
@syuu1228 I think `scylla_ntp_setup` should check if ntp is already installed first.

**Comment by syuu1228** [comment] 2020-09-07 09:05
@avikivity okay

**Comment by syuu1228** [comment] 2020-09-07 09:22
@avikivity Created a PR for it https://github.com/scylladb/scylla/pull/7185

**Comment by syuu1228** [comment] 2020-09-07 10:28
> Currently the offline (root & nonroot) install can success by skipping some setup, the openjdk8 is the only necessary dependency. If we/users don't want to skip any setup step, then it's a problem.
> 
> ```
> Necessary:
> - Openjdk 8 / openjdk 11
> 
> Optional:
> - Ntp / ntpdate
>   - Workaround: skip ntp install/setup by `--no-ntp-setup`
> - Node_exporter:  issue #2190
>   - Workaround: skip ntp install/setup by `--no-node-exporter`
> - Systemd-coredump
>   - Workaround: skip coredump setup by `--no-coredump-setup`
> - Cpufrequtils / cpupowerutils
>   - Workaround: skip cpuscaling setup by `--no-cpuscaling-setup`
> - Xfsprogs
>   - Workaround: skip raid setup by `--no-raid-setup`, skip kernel check by `--no-kernel-check`
> - Mdadm
>   - Workaround: skip raid setup by `--no-raid-setup`
> - libhugetlbfs-bin/ Hugepages
>   - Can’t skip, I will report a new issue
> ```

I think we need to add if-else prior to install packages like this (aborting current process by sys.exit(1) is okay because it should be subprocess of scylla_setup, errors can be handled by scylla_setup:
```
if is_offline():
    print(f"{pkg} does not found. Cannnot proceed the setup")
    sys.exit(1)
```
Or it can be wrapper function:
```
def install_package(pkg):
    if is_offline():
        print(f"{pkg} does not found. Cannnot proceed the setup")
        sys.exit(1)
    elif is_redhat_variant():
        run(f'yum install -y {pkg}')
```

I'll work on that.

**Comment by kolasani83** [comment] 2020-09-08 17:02
After Bypassing all the above checks, iam able to install scylla successfully. But nodetool is failing  now.

   scylla_setup --no-raid-setup --no-enable-service --no-sysconfig-setup --no-ntp-setup --no-coredump-setup --no-cpuscaling-setup

nodetool status
grep: /tmp/tmp.S5WW81DCiN/jvm-clients.options: No such file or directory
grep: /tmp/tmp.S5WW81DCiN/jvm8-clients.options: No such file or directory
16:56:55.926 [main] DEBUG i.n.u.i.l.InternalLoggerFactory - Using SLF4J as the default logging framework
16:56:55.931 [main] DEBUG i.n.u.i.InternalThreadLocalMap - -Dio.netty.threadLocalMap.stringBuilder.initialSize: 1024
16:56:55.933 [main] DEBUG i.n.u.i.InternalThreadLocalMap - -Dio.netty.threadLocalMap.stringBuilder.maxSize: 4096



At high level i can see below packages are missing from Internet enabled server to other offline server
 fontconfig-config
    fonts-dejavu-core
    x11-common
    fonts-dejavu-core
when i tried to install those packages, its going  in infinite loop with all other dependent packages missing.

**Comment by penberg** [comment] 2020-09-21 11:08
@syuu1228 I see https://github.com/scylladb/scylla/pull/7224 is now in master as 12ca7f7aceae0e68aef361c3a904e983c8b185cd. What other pull requests are needed to close this issue?

**Comment by penberg** [comment] 2020-10-05 10:13
@syuu1228 Confirmed that we can now close this issue as https://github.com/scylladb/scylla/commit/12ca7f7aceae0e68aef361c3a904e983c8b185cd is merged.

**Closed by penberg** 2020-10-05 10:13 UTC
Labels: offlineinstaller
