### ISSUE TITLE
Conviction threshold failure detector causes nodes in the cluster to flap up/down

### ISSUE THREAD

**Issue by dyasny** [scylladb/scylla#5677] opened 2020-01-30 03:30 UTC
*Installation details*
Scylla version (or git commit hash): 3.2.1-e3e301906
Cluster size: 3
OS (RHEL/CentOS/Ubuntu/AWS AMI): Gentoo

How to reproduce:

Node comes up without any data, and fails to join the cluster.
To work around that we only the system tables files, so it wouldn't bootstrap/do a node replace
The failure detector fires up causing nodes to flap up and down in a loop, hurting the whole cluster

**Comment by dyasny** [comment] 2020-01-30 03:31
@vladzcloudius @glommer @eyalgutkind this is another of the 3.2.1-gentoo bugs

**Comment by vladzcloudius** [comment] 2020-01-30 14:36
@dyasny Please, add more info: 
 * scylla.yaml from all nodes.
 * scylla logs from the node in question when it fails to join with `gossip` logger set to `trace`.

From what I remember from that debugging session it was likely related to having TLS encryption enabled, which was probably making heartbeat longer to arrive arrive.

@asias FYI

**Comment by dyasny** [comment] 2020-01-30 15:21
@vladzcloudius this is a customer issue, I can't submit their specific data in the open. Since this is 3.2.1 it should be reproducible by the QA, I provided the steps to reproduce

**Comment by eliransin** [comment] 2020-02-02 18:07
@roydahan is the description enough to try and reproduce this?
@dyasny just from @vladzcloudius comment I get the feeling we will need some more information :)

**Comment by roydahan** [comment] 2020-02-02 19:52
Not really, unless it's related specifically to Gentoo and if so, I don't think it's officially supported.

**Comment by asias** [comment] 2020-02-03 01:32
> How to reproduce:
> 
> Node comes up without any data, and fails to join the cluster.
> To work around that we only the system tables files, so it wouldn't bootstrap/do a node replace

I am not sure what was the procedure above. 

Did you mean start a complete new node to bootstrap but the bootstrap failed? What did you do with the "system table files" trick?

> The failure detector fires up causing nodes to flap up and down in a loop, hurting the whole cluster

We need to understand why the bootstrap failed first, e.g., as vlad mentioned TLS encryption issue.

**Comment by slivne** [comment] 2020-02-03 07:39
@dyasny / @vladzcloudius please provide logs to allow the people that wrote the code to have a look at what was the issue in the cluster. Its good todo analysis - but it does not remove the need to provide all information.

**Comment by dyasny** [comment] 2020-02-03 13:57
@slivne I'm asking for these logs since we ran into the issue, but the customer is busy taking things into production and hasn't been able to provide them yet. I'll post them as soon as I have them

**Comment by dyasny** [comment] 2020-02-20 16:58
Logs are in 9346b97a-6dfe-41a2-994e-234e00c98c42
Timeframe: Jan 28 14:34:21 and Jan 28 21:50:58

**Comment by pidiaquez** [comment] 2020-02-21 18:31
[9346b97a-6dfe-41a2-994e-234e00c98c42_scy-st-1-p1.scylla.log-20200129.gz](https://github.com/scylladb/scylla/files/4237472/9346b97a-6dfe-41a2-994e-234e00c98c42_scy-st-1-p1.scylla.log-20200129.gz)
[9346b97a-6dfe-41a2-994e-234e00c98c42_scy-st-1-p2.scylla.log-20200129.gz](https://github.com/scylladb/scylla/files/4237484/9346b97a-6dfe-41a2-994e-234e00c98c42_scy-st-1-p2.scylla.log-20200129.gz)

Attached the log files

**Comment by slivne** [comment] 2020-03-28 19:57
@asias please have a look at the logs and see if you can figure out whats going on

**Comment by asias** [comment] 2020-03-30 08:08
I need answer I asked: https://github.com/scylladb/scylla/issues/5677#issuecomment-581203485

```
Node comes up without any data, and fails to join the cluster.
To work around that we only the system tables files, so it wouldn't bootstrap/do a node replace
The failure detector fires up causing nodes to flap up and down in a loop, hurting the whole cluster
```

It is not clear to me what was performed. 

p1:
```
Jan 28 15:42:20 scy-st-1-p1 scylla:  [shard 0] gossip - InetAddress 10.6.18.12 is now DOWN, status = shutdown
Jan 28 16:06:46 scy-st-1-p1 scylla:  [shard 0] gossip - InetAddress 10.6.18.13 is now DOWN, status = shutdown
Jan 28 20:05:59 scy-st-1-p1 scylla:  [shard 0] gossip - InetAddress 10.6.18.12 is now DOWN, status = NORMAL
Jan 28 20:06:04 scy-st-1-p1 scylla:  [shard 0] gossip - InetAddress 10.6.18.13 is now DOWN, status = NORMAL
Jan 28 20:06:34 scy-st-1-p1 scylla:  [shard 0] gossip - InetAddress 10.6.18.13 is now DOWN, status = NORMAL
Jan 28 20:31:31 scy-st-1-p1 scylla:  [shard 0] gossip - InetAddress 10.6.18.12 is now DOWN, status = NORMAL
Jan 28 20:31:32 scy-st-1-p1 scylla:  [shard 0] gossip - InetAddress 10.6.18.13 is now DOWN, status = NORMAL
Jan 28 20:32:14 scy-st-1-p1 scylla:  [shard 0] gossip - InetAddress 10.6.18.13 is now DOWN, status = NORMAL
Jan 28 20:35:56 scy-st-1-p1 scylla:  [shard 0] gossip - InetAddress 10.6.18.12 is now DOWN, status = NORMAL
Jan 28 20:36:16 scy-st-1-p1 scylla:  [shard 0] gossip - InetAddress 10.6.18.13 is now DOWN, status = NORMAL
Jan 28 20:36:50 scy-st-1-p1 scylla:  [shard 0] gossip - InetAddress 10.6.18.13 is now DOWN, status = NORMAL
Jan 28 20:37:21 scy-st-1-p1 scylla:  [shard 0] gossip - InetAddress 10.6.18.12 is now DOWN, status = NORMAL
Jan 28 20:41:33 scy-st-1-p1 scylla:  [shard 0] gossip - InetAddress 10.6.18.12 is now DOWN, status = NORMAL
Jan 28 20:42:04 scy-st-1-p1 scylla:  [shard 0] gossip - InetAddress 10.6.18.12 is now DOWN, status = NORMAL
Jan 28 21:02:01 scy-st-1-p1 scylla:  [shard 0] gossip - InetAddress 10.6.18.13 is now DOWN, status = NORMAL
Jan 28 21:02:04 scy-st-1-p1 scylla:  [shard 0] gossip - InetAddress 10.6.18.12 is now DOWN, status = NORMAL
Jan 28 21:23:33 scy-st-1-p1 scylla:  [shard 0] gossip - InetAddress 10.6.18.12 is now DOWN, status = NORMAL
Jan 28 21:23:47 scy-st-1-p1 scylla:  [shard 0] gossip - InetAddress 10.6.18.13 is now DOWN, status = NORMAL
Jan 28 21:24:17 scy-st-1-p1 scylla:  [shard 0] gossip - InetAddress 10.6.18.12 is now DOWN, status = NORMAL
Jan 28 21:24:43 scy-st-1-p1 scylla:  [shard 0] gossip - InetAddress 10.6.18.13 is now DOWN, status = NORMAL
Jan 28 21:25:12 scy-st-1-p1 scylla:  [shard 0] gossip - InetAddress 10.6.18.12 is now DOWN, status = NORMAL
Jan 28 21:25:39 scy-st-1-p1 scylla:  [shard 0] gossip - InetAddress 10.6.18.13 is now DOWN, status = NORMAL
Jan 28 21:32:06 scy-st-1-p1 scylla:  [shard 0] gossip - InetAddress 10.6.18.13 is now DOWN, status = shutdown
Jan 28 21:32:16 scy-st-1-p1 scylla:  [shard 0] gossip - InetAddress 10.6.18.12 is now DOWN, status = shutdown
```

p2

```
Jan 28 14:34:21 scy-st-1-p2 scylla:  [shard 0] gossip - InetAddress 10.6.18.11 is now DOWN, status = shutdown
Jan 28 16:06:46 scy-st-1-p2 scylla:  [shard 0] gossip - InetAddress 10.6.18.13 is now DOWN, status = shutdown
Jan 28 20:06:01 scy-st-1-p2 scylla:  [shard 0] gossip - InetAddress 10.6.18.11 is now DOWN, status = NORMAL
Jan 28 20:06:16 scy-st-1-p2 scylla:  [shard 0] gossip - InetAddress 10.6.18.13 is now DOWN, status = NORMAL
Jan 28 20:31:29 scy-st-1-p2 scylla:  [shard 0] gossip - InetAddress 10.6.18.11 is now DOWN, status = NORMAL
Jan 28 20:31:34 scy-st-1-p2 scylla:  [shard 0] gossip - InetAddress 10.6.18.13 is now DOWN, status = NORMAL
Jan 28 20:32:20 scy-st-1-p2 scylla:  [shard 0] gossip - InetAddress 10.6.18.11 is now DOWN, status = NORMAL
Jan 28 20:32:33 scy-st-1-p2 scylla:  [shard 0] gossip - InetAddress 10.6.18.13 is now DOWN, status = NORMAL
Jan 28 20:35:54 scy-st-1-p2 scylla:  [shard 0] gossip - InetAddress 10.6.18.11 is now DOWN, status = NORMAL
Jan 28 20:35:59 scy-st-1-p2 scylla:  [shard 0] gossip - InetAddress 10.6.18.13 is now DOWN, status = NORMAL
Jan 28 20:37:17 scy-st-1-p2 scylla:  [shard 0] gossip - InetAddress 10.6.18.13 is now DOWN, status = NORMAL
Jan 28 20:50:03 scy-st-1-p2 scylla:  [shard 0] gossip - InetAddress 10.6.18.13 is now DOWN, status = NORMAL
Jan 28 20:51:09 scy-st-1-p2 scylla:  [shard 0] gossip - InetAddress 10.6.18.13 is now DOWN, status = NORMAL
Jan 28 21:02:07 scy-st-1-p2 scylla:  [shard 0] gossip - InetAddress 10.6.18.13 is now DOWN, status = NORMAL
Jan 28 21:23:34 scy-st-1-p2 scylla:  [shard 0] gossip - InetAddress 10.6.18.11 is now DOWN, status = NORMAL
Jan 28 21:23:35 scy-st-1-p2 scylla:  [shard 0] gossip - InetAddress 10.6.18.13 is now DOWN, status = NORMAL
Jan 28 21:24:07 scy-st-1-p2 scylla:  [shard 0] gossip - InetAddress 10.6.18.13 is now DOWN, status = NORMAL
Jan 28 21:25:11 scy-st-1-p2 scylla:  [shard 0] gossip - InetAddress 10.6.18.11 is now DOWN, status = NORMAL
Jan 28 21:25:15 scy-st-1-p2 scylla:  [shard 0] gossip - InetAddress 10.6.18.13 is now DOWN, status = NORMAL
Jan 28 21:26:12 scy-st-1-p2 scylla:  [shard 0] gossip - InetAddress 10.6.18.13 is now DOWN, status = NORMAL
Jan 28 21:32:06 scy-st-1-p2 scylla:  [shard 0] gossip - InetAddress 10.6.18.13 is now DOWN, status = shutdown
Jan 28 21:43:59 scy-st-1-p2 scylla:  [shard 0] gossip - InetAddress 10.6.18.13 is now DOWN, status = shutdown
Jan 28 21:50:58 scy-st-1-p2 scylla:  [shard 0] gossip - InetAddress 10.6.18.11 is now DOWN, status = shutdown
```

p3
```
Jan 28 14:34:21 scy-st-1-p3 scylla:  [shard 0] gossip - InetAddress 10.6.18.11 is now DOWN, status = shutdown
Jan 28 15:42:20 scy-st-1-p3 scylla:  [shard 0] gossip - InetAddress 10.6.18.12 is now DOWN, status = shutdown
Jan 28 20:05:59 scy-st-1-p3 scylla:  [shard 0] gossip - InetAddress 10.6.18.11 is now DOWN, status = NORMAL
Jan 28 20:06:13 scy-st-1-p3 scylla:  [shard 0] gossip - InetAddress 10.6.18.12 is now DOWN, status = NORMAL
Jan 28 20:06:28 scy-st-1-p3 scylla:  [shard 0] gossip - InetAddress 10.6.18.11 is now DOWN, status = NORMAL
Jan 28 20:31:29 scy-st-1-p3 scylla:  [shard 0] gossip - InetAddress 10.6.18.12 is now DOWN, status = NORMAL
Jan 28 20:31:29 scy-st-1-p3 scylla:  [shard 0] gossip - InetAddress 10.6.18.11 is now DOWN, status = NORMAL
Jan 28 20:35:54 scy-st-1-p3 scylla:  [shard 0] gossip - InetAddress 10.6.18.12 is now DOWN, status = NORMAL
Jan 28 20:36:13 scy-st-1-p3 scylla:  [shard 0] gossip - InetAddress 10.6.18.11 is now DOWN, status = NORMAL
Jan 28 20:36:37 scy-st-1-p3 scylla:  [shard 0] gossip - InetAddress 10.6.18.12 is now DOWN, status = NORMAL
Jan 28 20:37:06 scy-st-1-p3 scylla:  [shard 0] gossip - InetAddress 10.6.18.11 is now DOWN, status = NORMAL
Jan 28 20:37:13 scy-st-1-p3 scylla:  [shard 0] gossip - InetAddress 10.6.18.12 is now DOWN, status = NORMAL
Jan 28 20:37:55 scy-st-1-p3 scylla:  [shard 0] gossip - InetAddress 10.6.18.11 is now DOWN, status = NORMAL
Jan 28 20:39:33 scy-st-1-p3 scylla:  [shard 0] gossip - InetAddress 10.6.18.11 is now DOWN, status = NORMAL
Jan 28 20:43:40 scy-st-1-p3 scylla:  [shard 0] gossip - InetAddress 10.6.18.12 is now DOWN, status = NORMAL
Jan 28 20:44:14 scy-st-1-p3 scylla:  [shard 0] gossip - InetAddress 10.6.18.12 is now DOWN, status = NORMAL
Jan 28 20:46:01 scy-st-1-p3 scylla:  [shard 0] gossip - InetAddress 10.6.18.12 is now DOWN, status = NORMAL
Jan 28 20:51:05 scy-st-1-p3 scylla:  [shard 0] gossip - InetAddress 10.6.18.12 is now DOWN, status = NORMAL
Jan 28 20:52:29 scy-st-1-p3 scylla:  [shard 0] gossip - InetAddress 10.6.18.12 is now DOWN, status = NORMAL
Jan 28 21:01:57 scy-st-1-p3 scylla:  [shard 0] gossip - InetAddress 10.6.18.11 is now DOWN, status = NORMAL
Jan 28 21:23:34 scy-st-1-p3 scylla:  [shard 0] gossip - InetAddress 10.6.18.12 is now DOWN, status = NORMAL
Jan 28 21:23:45 scy-st-1-p3 scylla:  [shard 0] gossip - InetAddress 10.6.18.11 is now DOWN, status = NORMAL
Jan 28 21:24:22 scy-st-1-p3 scylla:  [shard 0] gossip - InetAddress 10.6.18.12 is now DOWN, status = NORMAL
Jan 28 21:25:11 scy-st-1-p3 scylla:  [shard 0] gossip - InetAddress 10.6.18.12 is now DOWN, status = NORMAL
Jan 28 21:25:35 scy-st-1-p3 scylla:  [shard 0] gossip - InetAddress 10.6.18.11 is now DOWN, status = NORMAL
Jan 28 21:25:44 scy-st-1-p3 scylla:  [shard 0] gossip - InetAddress 10.6.18.12 is now DOWN, status = NORMAL
Jan 28 21:50:58 scy-st-1-p3 scylla:  [shard 0] gossip - InetAddress 10.6.18.11 is now DOWN, status = shutdown
```

Gossip marked node down at different time points. What was the problem? It could be the network is not stable during that time. I see a lot of rpc timeout and connection closed error. 

```
Jan 28 20:49:58 scy-st-1-p1 scylla:  [shard 0] gossip - Fail to send EchoMessage to 10.6.18.13: seastar::rpc::timeout_error (rpc call timed out)
Jan 28 20:59:47 scy-st-1-p1 scylla:  [shard 0] gossip - Fail to send EchoMessage to 10.6.18.12: seastar::rpc::closed_error (connection is closed)
Jan 28 20:59:47 scy-st-1-p1 scylla:  [shard 0] gossip - Fail to send EchoMessage to 10.6.18.13: seastar::rpc::timeout_error (rpc call timed out)
```

**Comment by asias** [comment] 2020-03-30 08:17
They ran TLS between nodes. 

I saw: 

```Jan 28 21:02:04 scy-st-1-p1 scylla:  [shard 27] rpc - client 10.6.18.12:7001: client connection dropped: The TLS connection was non-properly terminated.
Jan 28 21:58:49 scy-st-1-p1 scylla:  [shard 0] rpc - client 10.6.18.12:50274: server connection dropped: The TLS connection was non-properly terminated.
Jan 28 16:28:09 scy-st-1-p2 scylla:  [shard 0] rpc - client 10.6.18.13:7001: client connection dropped: The TLS connection was non-properly terminated.
Jan 28 20:44:14 scy-st-1-p2 scylla:  [shard 20] rpc - client 10.6.18.13:61504: server connection dropped: The TLS connection was non-properly terminated.
Jan 28 20:44:14 scy-st-1-p2 scylla:  [shard 25] rpc - client 10.6.18.13:56417: server connection dropped: The TLS connection was non-properly terminated.
Jan 28 21:02:07 scy-st-1-p2 scylla:  [shard 23] rpc - client 10.6.18.13:7001: client connection dropped: The TLS connection was non-properly terminated.
Jan 28 21:24:31 scy-st-1-p2 scylla:  [shard 26] rpc - client 10.6.18.13:65462: server connection dropped: The TLS connection was non-properly terminated.
Jan 28 21:24:32 scy-st-1-p2 scylla:  [shard 9] rpc - client 10.6.18.13:54615: server connection dropped: The TLS connection was non-properly terminated.
Jan 28 21:25:18 scy-st-1-p2 scylla:  [shard 37] rpc - client 10.6.18.13:61825: server connection dropped: The TLS connection was non-properly terminated.
Jan 28 21:25:37 scy-st-1-p2 scylla:  [shard 5] rpc - client 10.6.18.13:49291: server connection dropped: The TLS connection was non-properly terminated.
Jan 28 21:25:37 scy-st-1-p2 scylla:  [shard 29] rpc - client 10.6.18.13:55927: server connection dropped: The TLS connection was non-properly terminated.
Jan 28 21:25:37 scy-st-1-p2 scylla:  [shard 18] rpc - client 10.6.18.13:49304: server connection dropped: The TLS connection was non-properly terminated.
Jan 28 21:25:37 scy-st-1-p2 scylla:  [shard 35] rpc - client 10.6.18.13:55097: server connection dropped: The TLS connection was non-properly terminated.
Jan 28 21:25:37 scy-st-1-p2 scylla:  [shard 16] rpc - client 10.6.18.13:51848: server connection dropped: The TLS connection was non-properly terminated.
Jan 28 21:25:37 scy-st-1-p2 scylla:  [shard 17] rpc - client 10.6.18.13:54851: server connection dropped: The TLS connection was non-properly terminated.
Jan 28 21:25:42 scy-st-1-p2 scylla:  [shard 11] rpc - client 10.6.18.13:61799: server connection dropped: The TLS connection was non-properly terminated.
Jan 28 21:26:01 scy-st-1-p2 scylla:  [shard 1] rpc - client 10.6.18.13:58141: server connection dropped: The TLS connection was non-properly terminated.
Jan 28 21:26:05 scy-st-1-p2 scylla:  [shard 10] rpc - client 10.6.18.13:64040: server connection dropped: The TLS connection was non-properly terminated.
Jan 28 21:26:12 scy-st-1-p2 scylla:  [shard 8] rpc - client 10.6.18.13:7001: client connection dropped: The TLS connection was non-properly terminated.
Jan 28 21:26:13 scy-st-1-p2 scylla:  [shard 34] rpc - client 10.6.18.13:59542: server connection dropped: The TLS connection was non-properly terminated.
Jan 28 21:26:13 scy-st-1-p2 scylla:  [shard 22] rpc - client 10.6.18.13:61468: server connection dropped: The TLS connection was non-properly terminated.
Jan 28 21:26:28 scy-st-1-p2 scylla:  [shard 17] rpc - client 10.6.18.13:63895: server connection dropped: The TLS connection was non-properly terminated.
Jan 28 21:26:33 scy-st-1-p2 scylla:  [shard 11] rpc - client 10.6.18.13:62787: server connection dropped: The TLS connection was non-properly terminated.
Jan 28 21:26:33 scy-st-1-p2 scylla:  [shard 28] rpc - client 10.6.18.13:50150: server connection dropped: The TLS connection was non-properly terminated.
Jan 28 21:26:33 scy-st-1-p2 scylla:  [shard 27] rpc - client 10.6.18.13:57217: server connection dropped: The TLS connection was non-properly terminated.
Jan 28 21:26:34 scy-st-1-p2 scylla:  [shard 2] rpc - client 10.6.18.13:58180: server connection dropped: The TLS connection was non-properly terminated.
Jan 28 21:58:49 scy-st-1-p2 scylla:  [shard 0] rpc - client 10.6.18.11:7001: client connection dropped: The TLS connection was non-properly terminated.
Jan 28 16:28:09 scy-st-1-p3 scylla:  [shard 0] rpc - client 10.6.18.12:64638: server connection dropped: The TLS connection was non-properly terminated.
Jan 28 20:37:06 scy-st-1-p3 scylla:  [shard 23] rpc - client 10.6.18.11:7001: client connection dropped: The TLS connection was non-properly terminated.
Jan 28 20:44:14 scy-st-1-p3 scylla:  [shard 20] rpc - client 10.6.18.12:7001: client connection dropped: The TLS connection was non-properly terminated.
Jan 28 20:44:14 scy-st-1-p3 scylla:  [shard 25] rpc - client 10.6.18.12:7001: client connection dropped: The TLS connection was non-properly terminated.
Jan 28 21:02:07 scy-st-1-p3 scylla:  [shard 23] rpc - client 10.6.18.12:56339: server connection dropped: The TLS connection was non-properly terminated.
```

The version 3.2.1-e3e301906 did not contain the tls fix

```
 Update seastar submodule

* seastar f54084c08f...a0bdc6cd85 (1):
  > tls: Fix race and stale memory use in delayed shutdown
```

**Comment by dyasny** [comment] 2020-03-30 13:56
> Did you mean start a complete new node to bootstrap but the bootstrap failed? What did you do with the "system table files" trick?

A node was failing to start up, it was working in this cluster before. After looking at the logs, we decided it would be easiest to simple wipe the data and commitlog dirs and do a dead node replacement with this node again, same IP. That did not work, so in order to force it to join back in, we only took it's old system tables files, and pushed them in, to work around the failing bootstrap.

**Comment by asias** [comment] 2020-03-31 00:19
> > Did you mean start a complete new node to bootstrap but the bootstrap failed? What did you do with the "system table files" trick?
> 
> A node was failing to start up, it was working in this cluster before. After looking at the logs, we decided it would be easiest to simple wipe the data and commitlog dirs and do a dead node replacement with this node again, same IP. That did not work, so in order to force it to join back in, we only took it's old system tables files, and pushed them in, to work around the failing bootstrap.

OK. I see. Do you still have the log when bootstrap failed? I guess it is due to node is being marked down while streaming. Anyway, we need the tls fix "tls: Fix race and stale memory use in delayed shutdown" for the user. 

Please me know if  the issue persists after the upgrade with a scylla version that contains the tls fix.

**Comment by dyasny** [comment] 2020-03-31 13:31
@asias which OSS version contains the TLS fix?

**Comment by asias** [comment] 2020-03-31 13:55
You can easily check git log.

git log origin/branch-3.3
git log origin/branch-3.2
git log origin/branch-3.1

3.3 has the fix at least. 

The patch name is "tls: Fix race and stale memory use in delayed shutdown".

**Comment by slivne** [comment] 2020-04-07 04:28
@dyasny please update the issue if this happens when the user uses a newer version, Asias referenced a bug we had with tls that was probably the root cause for the issue.

I am closing this issue for now.

**Closed by slivne** 2020-04-07 04:28 UTC
Labels: User Request, bug, gossip
