### ISSUE TITLE
/usr/lib/systemd/system/scylla-helper.slice: Unknown lvalue 'IOAccounting' in section 'Slice'

### ISSUE THREAD

**Issue by asias** [scylladb/scylla#8989] opened 2021-07-08 08:01 UTC
I saw the following warning in SCT test using a centos7 based ami.

```
  31 2021-07-08T05:06:34+00:00  longevity-100gb-4h-rbno-db-node-8a8e16a6-1 !INFO    | scylla_image_setup: Install  1 Package (+1 Dependent package)
  32 2021-07-08T05:06:34+00:00  longevity-100gb-4h-rbno-db-node-8a8e16a6-1 !INFO    | scylla_image_setup: Total download size: 480 k
  33 2021-07-08T05:06:34+00:00  longevity-100gb-4h-rbno-db-node-8a8e16a6-1 !INFO    | scylla_image_setup: Installed size: 1.0 M
  34 2021-07-08T05:06:34+00:00  longevity-100gb-4h-rbno-db-node-8a8e16a6-1 !INFO    | scylla_image_setup: Downloading packages:
  35 2021-07-08T05:06:34+00:00  longevity-100gb-4h-rbno-db-node-8a8e16a6-1 !INFO    | scylla_image_setup: --------------------------------------------------------------------------------
  36 2021-07-08T05:06:34+00:00  longevity-100gb-4h-rbno-db-node-8a8e16a6-1 !INFO    | scylla_image_setup: Total                                              5.9 MB/s | 480 kB  00:00
  37 2021-07-08T05:06:34+00:00  longevity-100gb-4h-rbno-db-node-8a8e16a6-1 !INFO    | scylla_image_setup: Running transaction check
  38 2021-07-08T05:06:34+00:00  longevity-100gb-4h-rbno-db-node-8a8e16a6-1 !INFO    | scylla_image_setup: Running transaction test
  39 2021-07-08T05:06:35+00:00  longevity-100gb-4h-rbno-db-node-8a8e16a6-1 !INFO    | scylla_image_setup: Transaction test succeeded
  40 2021-07-08T05:06:35+00:00  longevity-100gb-4h-rbno-db-node-8a8e16a6-1 !INFO    | scylla_image_setup: Running transaction
  41 2021-07-08T05:06:35+00:00  longevity-100gb-4h-rbno-db-node-8a8e16a6-1 !INFO    | yum[1394]: Installed: libreport-filesystem-2.1.11-53.el7.centos.x86_64
  42 2021-07-08T05:06:35+00:00  longevity-100gb-4h-rbno-db-node-8a8e16a6-1 !INFO    | scylla_image_setup: Installing : libreport-filesystem-2.1.11-53.el7.centos.x86_64             1/2
  43 2021-07-08T05:06:35+00:00  longevity-100gb-4h-rbno-db-node-8a8e16a6-1 !INFO    | systemd: Reloading.
  44 2021-07-08T05:06:35+00:00  longevity-100gb-4h-rbno-db-node-8a8e16a6-1 !WARNING | systemd: [/usr/lib/systemd/system/scylla-helper.slice:7] Unknown lvalue 'IOAccounting' in section 'Slice'
  45 2021-07-08T05:06:35+00:00  longevity-100gb-4h-rbno-db-node-8a8e16a6-1 !WARNING | systemd: [/usr/lib/systemd/system/scylla-helper.slice:10] Unknown lvalue 'CPUWeight' in section 'Slice'
  46 2021-07-08T05:06:35+00:00  longevity-100gb-4h-rbno-db-node-8a8e16a6-1 !WARNING | systemd: [/usr/lib/systemd/system/scylla-helper.slice:11] Unknown lvalue 'IOWeight' in section 'Slice'
  47 2021-07-08T05:06:35+00:00  longevity-100gb-4h-rbno-db-node-8a8e16a6-1 !WARNING | systemd: [/usr/lib/systemd/system/scylla-helper.slice:14] Unknown lvalue 'MemoryHigh' in section 'Slice'
  48 2021-07-08T05:06:35+00:00  longevity-100gb-4h-rbno-db-node-8a8e16a6-1 !WARNING | systemd: [/usr/lib/systemd/system/scylla-helper.slice:17] Unknown lvalue 'MemoryMax' in section 'Slice'
  49 2021-07-08T05:06:35+00:00  longevity-100gb-4h-rbno-db-node-8a8e16a6-1 !ERR     | systemd: [/usr/lib/systemd/system/scylla-helper.slice:22] Memory limit '5%' invalid. Ignoring.
  50 2021-07-08T05:06:35+00:00  longevity-100gb-4h-rbno-db-node-8a8e16a6-1 !WARNING | systemd: [/etc/systemd/system/scylla-helper.slice.d/memory.conf:2] Unknown lvalue 'MemoryHigh' in section 'Slice'
  51 2021-07-08T05:06:35+00:00  longevity-100gb-4h-rbno-db-node-8a8e16a6-1 !WARNING | systemd: [/etc/systemd/system/scylla-helper.slice.d/memory.conf:3] Unknown lvalue 'MemoryMax' in section 'Slice'
  52 2021-07-08T05:06:35+00:00  longevity-100gb-4h-rbno-db-node-8a8e16a6-1 !WARNING | systemd: [/usr/lib/systemd/system/scylla-server.slice:7] Unknown lvalue 'IOAccounting' in section 'Slice'
  53 2021-07-08T05:06:35+00:00  longevity-100gb-4h-rbno-db-node-8a8e16a6-1 !WARNING | systemd: [/usr/lib/systemd/system/scylla-server.slice:14] Unknown lvalue 'IOWeight' in section 'Slice'
  54 2021-07-08T05:06:35+00:00  longevity-100gb-4h-rbno-db-node-8a8e16a6-1 !WARNING | systemd: [/usr/lib/systemd/system/scylla-server.slice:16] Unknown lvalue 'MemorySwapMax' in section 'Slice'
  55 2021-07-08T05:06:35+00:00  longevity-100gb-4h-rbno-db-node-8a8e16a6-1 !WARNING | systemd: [/usr/lib/systemd/system/scylla-server.slice:18] Unknown lvalue 'CPUWeight' in section 'Slice'
```

Job:

https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/RBNO/job/repair-based-operation/job/longevity-100gb-4h-ReplaceNode-test/28/

More logs:

```
13:34:04  +--------------------------------------------------------------------------------------------------------------------------------------------+
13:34:04  |                                      Collected logs by test-id: 8a8e16a6-3386-42a1-bf54-c57aee10290a                                       |
13:34:04  +-------------+------------------------------------------------------------------------------------------------------------------------------+
13:34:04  | Cluster set | Link                                                                                                                         |
13:34:04  +-------------+------------------------------------------------------------------------------------------------------------------------------+
13:34:04  | db-cluster  | https://cloudius-jenkins-test.s3.amazonaws.com/8a8e16a6-3386-42a1-bf54-c57aee10290a/20210708_053122/db-cluster-8a8e16a6.zip  |
13:34:04  | monitor-set | https://cloudius-jenkins-test.s3.amazonaws.com/8a8e16a6-3386-42a1-bf54-c57aee10290a/20210708_053122/monitor-set-8a8e16a6.zip |
13:34:04  | loader-set  | https://cloudius-jenkins-test.s3.amazonaws.com/8a8e16a6-3386-42a1-bf54-c57aee10290a/20210708_053122/loader-set-8a8e16a6.zip  |
13:34:04  | sct-runner  | https://cloudius-jenkins-test.s3.amazonaws.com/8a8e16a6-3386-42a1-bf54-c57aee10290a/20210708_053122/sct-runner-8a8e16a6.zip  |
13:34:04  +-------------+------------------------------------------------------------------------------------------------------------------------------+
```

AMI:

```

https://jenkins.scylladb.com/view/master/job/scylla-master/job/ami/726/artifact/00-Build.txt

git@github.com:scylladb/scylla.git-sha: 373fa3fa07d366ea5a8632f0ddffae6f226f64c3
jenkins-job-number: 649
jenkins-job-path: scylla-master/build
reloc-pack-url: downloads.scylladb.com/unstable/scylla/master/relocatable/2021-06-23T10:53:35Z/
rpm-deb-pack-url: downloads.scylladb.com/unstable/scylla/master/build-packages/2021-06-23T10:53:35Z/
scylla-aarch64-BuildID[sha1]: b9846babf0052511ace66d5f4f46201cfcf5e2b8
scylla-debug-aarch64-BuildID[sha1]: 84620c6f88b0cbe592b6a9b8c75330983a7a5798
scylla-debug-x86_64-BuildID[sha1]: 67447a4b72918c0c5c22cb79769720d4628f2e8f
scylla-product: scylla
scylla-release: 0.20210623.373fa3fa0
scylla-version: 4.6.dev
scylla-x86_64-BuildID[sha1]: cb5a3e389de53f720c33ee3ccfd9097f2b08fe4d
timestamp: 2021-06-23T10:53:35Z
unified-pack-url: downloads.scylladb.com/unstable/scylla/master/relocatable/2021-06-23T10:53:35Z/scylla-unified-package-4.6.dev.0.20210623.373fa3fa0.tar.gz
url-id: 2021-06-23T10:53:35Z
centos-rpm-url: downloads.scylladb.com/unstable/scylla/master/rpm/centos/2021-06-23T10:53:35Z/
centos-rpm-repo-url: downloads.scylladb.com/unstable/scylla/master/rpm/centos/2021-06-23T10:53:35Z/scylla.repo
centos-rpm-debug-repo-url: downloads.scylladb.com/unstable/scylla/master/rpm/centos/2021-06-23T10:53:35Z/scylla-debug.repo
scylla-ami-id: ami-09067877cc92a836f
ami-base-os: centos:7
```

**Comment by avikivity** [comment] 2021-07-08 08:39
Duplicate of #7361. We decided to tolerate the error, over time CentOS 7 will be phased out. Newer systemd versions have this directive.

**Closed by avikivity** 2021-07-08 08:39 UTC
