### ISSUE TITLE
Scylla failed to start with coredump after upgrade from 4.5.2 to 4.7.dev

### ISSUE THREAD

**Issue by juliayakovlev** [scylladb/scylla#9750] opened 2021-12-07 08:22 UTC
*Installation details*
Scylla version (or git commit hash): 4.5.2-0.20211114.26aca7b9f
Cluster size: 4 nodes (n1-highmem-8)
OS (RHEL/CentOS/Ubuntu/AWS AMI):  http://downloads.scylladb.com/unstable/scylla/master/rpm/centos/2021-11-28T03:59:37Z/scylla.repo
Backend: gce: eu-west-1
Kernel version: 3.10.0-1160.45.1.el7.x86_64
Test-id: d1d622df-1507-4adc-818d-fc972106ed30

Scylla failed to start after upgrade from `4.5.2-0.20211114.26aca7b9f` to `4.7.dev-0.20211128.44f4ea38c` with coredump.

```
t:2021-12-07 03:04:10,607 f:upgrade_test.py l:574  c:UpgradeTest          p:INFO  > Upgrade Node rolling-upgrade-master-centos-db-node-d1d622df-0-4 begin
```

Trying to start Scylla:
```
Dec 07 03:15:44 rolling-upgrade-master-centos-db-node-d1d622df-0-4 systemd[1]: Starting Scylla Server...
Dec 07 03:15:45 rolling-upgrade-master-centos-db-node-d1d622df-0-4 scylla[30407]: Scylla version 4.7.dev-0.20211128.44f4ea38c with build-id ce2f8485c84f459e654f38aa0029eb9d763e453a starting ...
Dec 07 03:15:45 rolling-upgrade-master-centos-db-node-d1d622df-0-4 scylla[30407]: command used: "/usr/bin/scylla --blocked-reactor-notify-ms 500 --abort-on-lsa-bad-alloc 1 --abort-on-seastar-bad-alloc --abort-on
-internal-error 1 --log-to-syslog 1 --log-to-stdout 0 --default-log-level info --network-stack posix --num-io-queues=8 --io-properties-file=/etc/scylla.d/io_properties.yaml --lock-memory=1"
Dec 07 03:15:45 rolling-upgrade-master-centos-db-node-d1d622df-0-4 scylla[30407]: parsed command line options: [blocked-reactor-notify-ms, (positional) 500, abort-on-lsa-bad-alloc: 1, abort-on-seastar-bad-alloc,
 abort-on-internal-error: 1, log-to-syslog, (positional) 1, log-to-stdout, (positional) 0, default-log-level, (positional) info, network-stack, (positional) posix, num-io-queues: 8, io-properties-file: /etc/scyl
la.d/io_properties.yaml, lock-memory: 1]
```

During schema merge `seastar::timed_out_error` got when applying view update:
```
Dec 07 03:16:06 rolling-upgrade-master-centos-db-node-d1d622df-0-4 scylla[30407]:  [shard 0] migration_manager - Schema merge with 10.142.0.139:0 completed
Dec 07 03:16:06 rolling-upgrade-master-centos-db-node-d1d622df-0-4 scylla[30407]:  [shard 0] migration_manager - Pulling schema from 10.142.0.139:0
Dec 07 03:16:07 rolling-upgrade-master-centos-db-node-d1d622df-0-4 scylla[30407]:  [shard 0] storage_service - fail to update schema_version for 10.142.0.139: exceptions::mutation_write_timeout_exception (Operation timed out for system.peers - received only 0 responses from 1 CL=ONE.)
Dec 07 03:16:07 rolling-upgrade-master-centos-db-node-d1d622df-0-4 scylla[30407]:  [shard 7] view - Error applying view update to 10.142.0.151 (view: ks1.table1_mv_0, base token: -2378317057810845763, view token: 8544763129517010552): seastar::timed_out_error (timedout)
Dec 07 03:16:07 rolling-upgrade-master-centos-db-node-d1d622df-0-4 scylla[30407]:  [shard 0] migration_manager - Requesting schema pull from 10.142.0.139:0
Dec 07 03:16:07 rolling-upgrade-master-centos-db-node-d1d622df-0-4 scylla[30407]:  [shard 2] view - Error applying view update to 10.142.0.151 (view: ks1.table1_col6_idx_index, base token: 7108347972595825431, view token: 8904944850069965096): seastar::timed_out_error (timedout)
Dec 07 03:16:07 rolling-upgrade-master-centos-db-node-d1d622df-0-4 scylla[30407]:  [shard 1] view - Error applying view update to 10.142.0.151 (view: ks1.table1_col0_idx_index, base token: -3300229270569795175, view token: 5144285816893990382): seastar::timed_out_error (timedout)
```

And the got segmentation fault:
```

Dec 07 03:17:38 rolling-upgrade-master-centos-db-node-d1d622df-0-4 scylla[30407]:  [shard 0] migration_manager - Update table 'system_distributed.service_levels' From org.apache.cassandra.config.CFMetaData@0x600008aeb500[cfId=b8c556bd-212d-37ad-9484-690c73a5994b,ksName=system_distributed,cfName=service_levels,cfType=Standard,comparator=org.apache.cassandra.db.marshal.CompositeType(org.apache.cassandra.db.marshal.UTF8Type),comment=,readRepairChance=0,dcLocalReadRepairChance=0,gcGraceSeconds=864000,keyValidator=org.apache.cassandra.db.marshal.UTF8Type,minCompactionThreshold=4,maxCompactionThreshold=32,columnMetadata=[ColumnDefinition{name=service_level, type=org.apache.cassandra.db.marshal.UTF8Type, kind=PARTITION_KEY, componentIndex=0, droppedAt=-9223372036854775808}],compactionStrategyClass=class org.apache.cassandra.db.compaction.SizeTieredCompactionStrategy,compactionStrategyOptions={enabled=true},compressionParameters={sstable_compression=org.apache.cassandra.io.compress.LZ4Compressor},bloomFilterFpChance=0.01,memtableFlushPeriod=0,caching={"keys":"ALL","rows_per_partition":"ALL"},cdc={},defaultTimeToLive=0,minIndexInterval=128,maxIndexInterval=2048,speculativeRetry=99.0PERCENTILE,triggers=[],isDense=false,version=08d009cd-6bd2-3be7-8d96-48fea7669507,droppedColumns={},collections={},indices={}] To org.apache.cassandra.config.CFMetaData@0x600008aeb880[cfId=b8c556bd-212d-37ad-9484-690c73a5994b,ksName=system_distributed,cfName=service_levels,cfType=Standard,comparator=org.apache.cassandra.db.marshal.CompositeType(org.apache.cassandra.db.marshal.UTF8Type),comment=,readRepairChance=0,dcLocalReadRepairChance=0,gcGraceSeconds=864000,keyValidator=org.apache.cassandra.db.marshal.UTF8Type,minCompactionThreshold=4,maxCompactionThreshold=32,columnMetadata=[ColumnDefinition{name=service_level, type=org.apache.cassandra.db.marshal.UTF8Type, kind=PARTITION_KEY, componentIndex=0, droppedAt=-9223372036854775808}, ColumnDefinition{name=timeout, type=org.apache.cassandra.db.marshal.DurationType, kind=REGULAR, componentIndex=null, droppedAt=-9223372036854775808}, ColumnDefinition{name=workload_type, type=org.apache.cassandra.db.marshal.UTF8Type, kind=REGULAR, componentIndex=null, droppedAt=-9223372036854775808}],compactionStrategyClass=class org.apache.cassandra.db.compaction.SizeTieredCompactionStrategy,compactionStrategyOptions={enabled=true},compressionParameters={sstable_compression=org.apache.cassandra.io.compress.LZ4Compressor},bloomFilterFpChance=0.01,memtableFlushPeriod=0,caching={"keys":"ALL","rows_per_partition":"ALL"},cdc={},defaultTimeToLive=0,minIndexInterval=128,maxIndexInterval=2048,speculativeRetry=99.0PERCENTILE,triggers=[],isDense=false,version=3ad9f770-570c-11ec-90d5-d7eb2c532b7a,droppedColumns={},collections={},indices={}]

Dec 07 03:17:38 rolling-upgrade-master-centos-db-node-d1d622df-0-4 scylla[30407]: Segmentation fault on shard 1.
Dec 07 03:17:38 rolling-upgrade-master-centos-db-node-d1d622df-0-4 scylla[30407]: Backtrace:
0x3e072b8
0x3e380a6
0x448b211
0x7feb9a8b3a1f
0x26f4b9f
0x3e19c84
0x3e1b077
0x3e386a5
0x3df22ba
/opt/scylladb/libreloc/libpthread.so.0+0x9298
/opt/scylladb/libreloc/libc.so.6+0x100352

Dec 07 03:19:12 rolling-upgrade-master-centos-db-node-d1d622df-0-4 systemd[1]: scylla-server.service: main process exited, code=killed, status=11/SEGV
Dec 07 03:19:12 rolling-upgrade-master-centos-db-node-d1d622df-0-4 systemd[1]: Unit scylla-server.service entered failed state.
Dec 07 03:19:12 rolling-upgrade-master-centos-db-node-d1d622df-0-4 systemd[1]: scylla-server.service failed.
Dec 07 03:19:12 rolling-upgrade-master-centos-db-node-d1d622df-0-4 systemd[1]: scylla-server.service holdoff time over, scheduling restart.
Dec 07 03:19:12 rolling-upgrade-master-centos-db-node-d1d622df-0-4 systemd[1]: Stopping Scylla JMX...

Dec 07 03:19:12 rolling-upgrade-master-centos-db-node-d1d622df-0-4 systemd[1]: scylla-jmx.service failed.
Dec 07 03:19:12 rolling-upgrade-master-centos-db-node-d1d622df-0-4 systemd[1]: Stopped Scylla Server.
Dec 07 03:19:12 rolling-upgrade-master-centos-db-node-d1d622df-0-4 systemd[1]: Starting Scylla Server...
Dec 07 03:19:12 rolling-upgrade-master-centos-db-node-d1d622df-0-4 scylla[31374]: Scylla version 4.7.dev-0.20211128.44f4ea38c with build-id ce2f8485c84f459e654f38aa0029eb9d763e453a starting ...
```

and coredump:
```
           PID: 30407 (scylla)
           UID: 997 (scylla)
           GID: 1002 (scylla)
        Signal: 11 (SEGV)
     Timestamp: Tue 2021-12-07 03:17:38 UTC (21min ago)
  Command Line: /usr/bin/scylla --blocked-reactor-notify-ms 500 --abort-on-lsa-bad-alloc 1 --abort-on-seastar-bad-alloc --abort-on-internal-error 1 --log-to-syslog 1 --log-to-stdout 0 --default-log-level info --network-stack posix --num-io-queues=8 --io-properties-file=/etc/scylla.d/io_properties.yaml --lock-memory=1
    Executable: /opt/scylladb/libexec/scylla
 Control Group: /scylla.slice/scylla-server.slice/scylla-server.service
          Unit: scylla-server.service
         Slice: scylla-server.slice
       Boot ID: c19ab4c11efe497e85f033de19fe74b1
    Machine ID: 88aa80e2d70d217740cc1f42c4c2688e
      Hostname: rolling-upgrade-master-centos-db-node-d1d622df-0-4
       Message: Process 30407 (scylla) of user 997 dumped core.
                
                Stack trace of thread 30408:
                #0  0x00000000026f4ba0 _ZN2db9commitlog15segment_manager11new_segmentEv.resume (scylla)
                #1  0x0000000003e19c85 _ZN7seastar7reactor14run_some_tasksEv (scylla)
                #2  0x0000000003e1b078 _ZN7seastar7reactor6do_runEv (scylla)
                #3  0x0000000003e386a6 _ZNSt17_Function_handlerIFvvEZN7seastar3smp9configureEN5boost15program_options13variables_mapENS1_14reactor_configEE4$_99E9_M_invokeERKSt9_Any_data (scylla)
                #4  0x0000000003df22bb _ZN7seastar12posix_thread13start_routineEPv (scylla)
                #5  0x00007feb9a8a9299 start_thread (libpthread.so.0)
                #6  0x00007feb99dbb353 __clone (libc.so.6)
                
                Stack trace of thread 30415:
                #0  0x00007feb9a8b294c read (libpthread.so.0)
                #1  0x0000000003e5c385 _ZN7seastar11thread_pool4workENS_13basic_sstringIcjLj15ELb1EEE (scylla)
                #2  0x0000000003e5c6f0 _ZNSt17_Function_handlerIFvvEZN7seastar11thread_poolC1EPNS1_7reactorENS1_13basic_sstringIcjLj15ELb1EEEE3$_0E9_M_invokeERKSt9_Any_data (scylla)
                #3  0x0000000003df22bb _ZN7seastar12posix_thread13start_routineEPv (scylla)
                #4  0x00007feb9a8a9299 start_thread (libpthread.so.0)
                #5  0x00007feb99dbb353 __clone (libc.so.6)
                
                Stack trace of thread 30417:
                #0  0x00007feb9a8b294c read (libpthread.so.0)
                #1  0x0000000003e5c385 _ZN7seastar11thread_pool4workENS_13basic_sstringIcjLj15ELb1EEE (scylla)
                #2  0x0000000003e5c6f0 _ZNSt17_Function_handlerIFvvEZN7seastar11thread_poolC1EPNS1_7reactorENS1_13basic_sstringIcjLj15ELb1EEEE3$_0E9_M_invokeERKSt9_Any_data (scylla)
                #3  0x0000000003df22bb _ZN7seastar12posix_thread13start_routineEPv (scylla)
                #4  0x00007feb9a8a9299 start_thread (libpthread.so.0)
                #5  0x00007feb99dbb353 __clone (libc.so.6)
                
                Stack trace of thread 30420:
                #0  0x00007feb99db05bf __poll (libc.so.6)
                #1  0x0000000003e5ed36 _ZN7seastar21reactor_backend_epoll26task_quota_timer_thread_fnEv (scylla)
                #2  0x00007feb99f7ec84 execute_native_thread_routine (libstdc++.so.6)
                #3  0x00007feb9a8a9299 start_thread (libpthread.so.0)
                #4  0x00007feb99dbb353 __clone (libc.so.6)
                
                Stack trace of thread 30429:
                #0  0x00007feb9a8b294c read (libpthread.so.0)
                #1  0x0000000003e5c385 _ZN7seastar11thread_pool4workENS_13basic_sstringIcjLj15ELb1EEE (scylla)
                #2  0x0000000003e5c6f0 _ZNSt17_Function_handlerIFvvEZN7seastar11thread_poolC1EPNS1_7reactorENS1_13basic_sstringIcjLj15ELb1EEEE3$_0E9_M_invokeERKSt9_Any_data (scylla)
                #3  0x0000000003df22bb _ZN7seastar12posix_thread13start_routineEPv (scylla)
                #4  0x00007feb9a8a9299 start_thread (libpthread.so.0)
                #5  0x00007feb99dbb353 __clone (libc.so.6)
                
                Stack trace of thread 30421:
                #0  0x00007feb9a8b294c read (libpthread.so.0)
                #1  0x0000000003e5c385 _ZN7seastar11thread_pool4workENS_13basic_sstringIcjLj15ELb1EEE (scylla)
                #2  0x0000000003e5c6f0 _ZNSt17_Function_handlerIFvvEZN7seastar11thread_poolC1EPNS1_7reactorENS1_13basic_sstringIcjLj15ELb1EEEE3$_0E9_M_invokeERKSt9_Any_data (scylla)
                #3  0x0000000003df22bb _ZN7seastar12posix_thread13start_routineEPv (scylla)
                #4  0x00007feb9a8a9299 start_thread (libpthread.so.0)
                #5  0x00007feb99dbb353 __clone (libc.so.6)
                
                Stack trace of thread 30416:
                #0  0x00007feb99db05bf __poll (libc.so.6)
                #1  0x0000000003e5ed36 _ZN7seastar21reactor_backend_epoll26task_quota_timer_thread_fnEv (scylla)
                #2  0x00007feb99f7ec84 execute_native_thread_routine (libstdc++.so.6)
                #3  0x00007feb9a8a9299 start_thread (libpthread.so.0)
                #4  0x00007feb99dbb353 __clone (libc.so.6)
                
                Stack trace of thread 30422:
                #0  0x00007feb9a8b294c read (libpthread.so.0)
                #1  0x0000000003e5c385 _ZN7seastar11thread_pool4workENS_13basic_sstringIcjLj15ELb1EEE (scylla)
                #2  0x0000000003e5c6f0 _ZNSt17_Function_handlerIFvvEZN7seastar11thread_poolC1EPNS1_7reactorENS1_13basic_sstringIcjLj15ELb1EEEE3$_0E9_M_invokeERKSt9_Any_data (scylla)
                #3  0x0000000003df22bb _ZN7seastar12posix_thread13start_routineEPv (scylla)
                #4  0x00007feb9a8a9299 start_thread (libpthread.so.0)
                #5  0x00007feb99dbb353 __clone (libc.so.6)
                
                Stack trace of thread 30419:
                #0  0x00007feb99db05bf __poll (libc.so.6)
                #1  0x0000000003e5ed36 _ZN7seastar21reactor_backend_epoll26task_quota_timer_thread_fnEv (scylla)
                #2  0x00007feb99f7ec84 execute_native_thread_ro
```

Then tried to start again and got segmentation fault and coredump:
```
Dec 07 03:21:24 rolling-upgrade-master-centos-db-node-d1d622df-0-4 scylla[31374]: Segmentation fault on shard 0.
Dec 07 03:21:24 rolling-upgrade-master-centos-db-node-d1d622df-0-4 scylla[31374]: Backtrace:
0x3e072b8
0x3e380a6
0x448b211
0x7fd630635a1f
0x2ac0cc3
0x21cf82d
0x21d88a3
0x21dc46e
0x21da888
0x1e1af12
0x1e158c5
0x1eb6287
0x1eb62cc
0x1e920a4
0x3dcf6a5
0x3e19c84
0x3e1b077
0x3e1a2bc
0x3dc3b4e
0x3dc2ec6
0xf50a5e
/opt/scylladb/libreloc/libc.so.6+0x27b74
0xf4dbad
```

```
           PID: 31374 (scylla)
           UID: 997 (scylla)
           GID: 1002 (scylla)
        Signal: 11 (SEGV)
     Timestamp: Tue 2021-12-07 03:21:24 UTC (18min ago)
  Command Line: /usr/bin/scylla --blocked-reactor-notify-ms 500 --abort-on-lsa-bad-alloc 1 --abort-on-seastar-bad-alloc --abort-on-internal-error 1 --log-to-syslog 1 --log-to-stdout 0 --default-log-level info --network-stack posix --num-io-queues=8 --io-properties-file=/etc/scylla.d/io_properties.yaml --lock-memory=1
    Executable: /opt/scylladb/libexec/scylla
 Control Group: /scylla.slice/scylla-server.slice/scylla-server.service
          Unit: scylla-server.service
         Slice: scylla-server.slice
       Boot ID: c19ab4c11efe497e85f033de19fe74b1
    Machine ID: 88aa80e2d70d217740cc1f42c4c2688e
      Hostname: rolling-upgrade-master-centos-db-node-d1d622df-0-4
      Coredump: /var/lib/systemd/coredump/core.scylla.997.c19ab4c11efe497e85f033de19fe74b1.31374.1638847284000000
       Message: Process 31374 (scylla) of user 997 dumped core.
                
                Stack trace of thread 31374:
                #0  0x0000000002ac0cc4 _ZNK7locator25effective_replication_map49get_natural_endpoints_without_node_being_replacedERKN3dht5tokenE (scylla)
                #1  0x00000000021cf82e _ZN7service13storage_proxy36query_partition_key_range_concurrentENSt6chrono10time_pointIN7seastar12lowres_clockENS1_8durationIlSt5ratioILl1ELl1000EEEEEEOSt6vectorINS3_11foreign_ptrINS3_13lw_shared_ptrIN5query6resultEEEEESaISG_EENSC_INSD_12read_commandEEEN2db17consistency_levelEONS_32query_ranges_to_vnodes_generatorEiN7tracing15trace_state_ptrEmjSt13unordered_mapI20nonwrapping_intervalIN3dht5tokenEESA_IN5utils4UUIDESaISY_EESt4hashISW_ESt8equal_toISW_ESaISt4pairIKSW_S10_EEE14service_permit (scylla)
                #2  0x00000000021d88a4 _ZN7service13storage_proxy25query_partition_key_rangeEN7seastar13lw_shared_ptrIN5query12read_commandEEESt6vectorI20nonwrapping_intervalIN3dht13ring_positionEESaISA_EEN2db17consistency_levelENS0_25coordinator_query_optionsE (scylla)
                #3  0x00000000021dc46f _ZN7service13storage_proxy8do_queryEN7seastar13lw_shared_ptrIK6schemaEENS2_IN5query12read_commandEEEOSt6vectorI20nonwrapping_intervalIN3dht13ring_positionEESaISD_EEN2db17consistency_levelENS0_25coordinator_query_optionsE (scylla)
                #4  0x00000000021da889 _ZN7service13storage_proxy5queryEN7seastar13lw_shared_ptrIK6schemaEENS2_IN5query12read_commandEEEOSt6vectorI20nonwrapping_intervalIN3dht13ring_positionEESaISD_EEN2db17consistency_levelENS0_25coordinator_query_optionsE (scylla)
                #5  0x0000000001e1af13 _ZNK4cql310statements16select_statement7executeERN7service13storage_proxyEN7seastar13lw_shared_ptrIN5query12read_commandEEEOSt6vectorI20nonwrapping_intervalIN3dht13ring_positionEESaISE_EERNS2_11query_stateERKNS_13query_optionsENSt6chrono10time_pointI8gc_clockNSN_8durationIlSt5ratioILl1ELl1EEEEEE (scylla)
                #6  0x0000000001e158c6 _ZNK4cql310statements16select_statement10do_executeERN7service13storage_proxyERNS2_11query_stateERKNS_13query_optionsE (scylla)
                #7  0x0000000001eb6288 _ZN7seastar20noncopyable_functionIFNS_6futureINS_10shared_ptrIN13cql_transport8messages14result_messageEEEEEPKN4cql310statements16select_statementERN7service13storage_proxyERNSD_11query_stateERKNS8_13query_optionsEEE17direct_vtable_forISt7_Mem_fnIMSA_KFS7_SF_SH_SK_EEE4callEPKSM_SC_SF_SH_SK_ (scylla)
                #8  0x0000000001eb62cd _ZN7seastar20noncopyable_functionIFNS_6futureINS_10shared_ptrIN13cql_transport8messages14result_messageEEEEEPKN4cql310statements16select_statementERN7service13storage_proxyERNSD_11query_stateERKNS8_13query_optionsEEE17direct_vtable_forIZNS_35inheriting_concrete_execution_stageIS7_JSC_SF_SH_SK_EE20make_stage_for_groupENS_16scheduling_groupEEUlSC_SF_SH_SK_E_E4callEPKSM_SC_SF_SH_SK_ (scylla)
                #9  0x0000000001e920a5 _ZN7seastar24concrete_execution_stageINS_6futureINS_10shared_ptrIN13cql_transport8messages14result_messageEEEEEJPKN4cql310statements16select_statementERN7service13storage_proxyERNSD_11query_stateERKNS8_13query_optionsEEE8do_flushEv (scylla)
                #10 0x0000000003dcf6a6 _ZN7seastar11lambda_taskIZNS_15execution_stage5flushEvE3$_1E15run_and_disposeEv (scylla)
                #11 0x0000000003e19c85 _ZN7seastar7reactor14run_some_tasksEv (scylla)
                #12 0x0000000003e1b078 _ZN7seastar7reactor6do_runEv (scylla)
                #13 0x0000000003e1a2bd _ZN7seastar7reactor3runEv (scylla)
                #14 0x0000000003dc3b4f _ZN7seastar12app_template14run_deprecatedEiPPcOSt8functionIFvvEE (scylla)
                #15 0x0000000003dc2ec7 _ZN7seastar12app_template3runEiPPcOSt8functionIFNS_6futureIiEEvEE (scylla)
                #16 0x0000000000f50a5f main (scylla)
                #17 0x00007fd62fa64b75 __libc_start_main (libc.so.6)
                #18 0x0000000000f4dbae _start (scylla)
                
                Stack trace of thread 31419:
                #0  0x00007fd63063494c read (libpthread.so.0)
                #1  0x0000000003e5c385 _ZN7seastar11thread_pool4workENS_13basic_sstringIcjLj15ELb1EEE (scylla)
                #2  0x0000000003e5c6f0 _ZNSt17_Function_handlerIFvvEZN7seastar11thread_poolC1EPNS1_7reactorENS1_13basic_sstringIcjLj15ELb1EEEE3$_0E9_M_invokeERKSt9_Any_data (scylla)
                #3  0x0000000003df22bb _ZN7seastar12posix_thread13start_routineEPv (scylla)
                #4  0x00007fd63062b299 start_thread (libpthread.so.0)
                #5  0x00007fd6
```

download_instructions:
```
gsutil cp gs://upload.scylladb.com/core.scylla.997.c19ab4c11efe497e85f033de19fe74b1.31374.1638847284000000/core.scylla.997.c19ab4c11efe497e85f033de19fe74b1.31374.1638847284000000.gz .
gunzip /var/lib/systemd/coredump/core.scylla.997.c19ab4c11efe497e85f033de19fe74b1.31374.1638847284000000.gz
```

Job: https://jenkins.scylladb.com/job/scylla-master/job/rolling-upgrade/job/rolling-upgrade-centos7-test/205/

Logs:
db-cluster  | https://cloudius-jenkins-test.s3.amazonaws.com/d1d622df-1507-4adc-818d-fc972106ed30/20211207_033902/db-cluster-d1d622df.tar.gz 

sct-runner  | https://cloudius-jenkins-test.s3.amazonaws.com/d1d622df-1507-4adc-818d-fc972106ed30/20211207_033902/sct-runner-d1d622df.tar.gz

**Comment by slivne** [comment] 2021-12-07 12:00
@bhalevy I think you did a change in this area - not sure it went in

**Comment by bhalevy** [comment] 2021-12-08 17:20
The first segfault is https://github.com/scylladb/scylla/issues/9152:
Cc @elcallio 
```
Dec 07 03:17:38 rolling-upgrade-master-centos-db-node-d1d622df-0-4 scylla[30407]: Backtrace:
0x3e072b8
0x3e380a6
0x448b211
0x7feb9a8b3a1f
0x26f4b9f
0x3e19c84
0x3e1b077
0x3e386a5
0x3df22ba
/opt/scylladb/libreloc/libpthread.so.0+0x9298
/opt/scylladb/libreloc/libc.so.6+0x100352
```

Decoded:
```
[Backtrace #0]
void seastar::backtrace(seastar::backtrace_buffer::append_backtrace()::{lambda(seastar::frame)#1}&&) at ./build/release/seastar/./seastar/include/seastar/util/backtrace.hh:59
 (inlined by) seastar::backtrace_buffer::append_backtrace() at ./build/release/seastar/./seastar/src/core/reactor.cc:760
 (inlined by) seastar::print_with_backtrace(seastar::backtrace_buffer&, bool) at ./build/release/seastar/./seastar/src/core/reactor.cc:790
seastar::print_with_backtrace(char const*, bool) at ./build/release/seastar/./seastar/src/core/reactor.cc:802
 (inlined by) seastar::sigsegv_action() at ./build/release/seastar/./seastar/src/core/reactor.cc:3716
 (inlined by) operator() at ./build/release/seastar/./seastar/src/core/reactor.cc:3702
 (inlined by) __invoke at ./build/release/seastar/./seastar/src/core/reactor.cc:3698
wasmtime_runtime::traphandlers::unix::trap_handler at wasmtime_runtime.9xv9ixev-cgu.15:?
?? ??:0
std::__atomic_base::load(std::memory_order) const at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/atomic_base.h:481
 (inlined by) seastar::lowres_clock_impl::steady_now() at ././seastar/include/seastar/core/lowres_clock.hh:61
 (inlined by) seastar::lowres_clock::now() at ././seastar/include/seastar/core/lowres_clock.hh:119
 (inlined by) db::commitlog::segment::reset_sync_time() at ./db/commitlog/commitlog.cc:651
 (inlined by) db::commitlog::segment_manager::new_segment() at ./db/commitlog/commitlog.cc:1634
seastar::reactor::run_tasks(seastar::reactor::task_queue&) at ./build/release/seastar/./seastar/src/core/reactor.cc:2378
 (inlined by) seastar::reactor::run_some_tasks() at ./build/release/seastar/./seastar/src/core/reactor.cc:2787
seastar::reactor::do_run() at ./build/release/seastar/./seastar/src/core/reactor.cc:2956
operator() at ./build/release/seastar/./seastar/src/core/reactor.cc:4171
 (inlined by) void std::__invoke_impl(std::__invoke_other, seastar::smp::configure(boost::program_options::variables_map, seastar::reactor_config)::$_99&) at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/invoke.h:61
 (inlined by) std::enable_if, void>::type std::__invoke_r(seastar::smp::configure(boost::program_options::variables_map, seastar::reactor_config)::$_99&) at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/invoke.h:111
 (inlined by) std::_Function_handler::_M_invoke(std::_Any_data const&) at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/std_function.h:291
std::function::operator()() const at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/std_function.h:560
 (inlined by) seastar::posix_thread::start_routine(void*) at ./build/release/seastar/./seastar/src/core/posix.cc:60
```

**Comment by bhalevy** [comment] 2021-12-08 17:23
The second backtrace is a dup of https://github.com/scylladb/scylla/issues/9684 which is already fixed in master change cf528d7

**Comment by bhalevy** [comment] 2021-12-09 18:09
@elcallio please confirm https://github.com/scylladb/scylla/issues/9750#issuecomment-989013396
and if so, we can close this issue as a duplicate of #9152

**Comment by elcallio** [comment] 2022-01-10 12:09
Yes, looks like a duplicate.

**Comment by bhalevy** [comment] 2022-01-16 17:46
@slivne can we please close this issue as duplicate of #9152?

**Closed** 2022-02-03 12:17 UTC
Labels: master/high
