### ISSUE TITLE
CDC: compaction failing continuously on seed node during cleanup keyspaces after decommission on another node

### ISSUE THREAD

**Issue by enaydanov** [scylladb/scylla#7590] opened 2020-11-11 13:28 UTC
*Installation details*

Scylla version (or git commit hash): 4.3.rc1-0.20201110.a8e372bf9 with build-id f868ccb821d87eb55b943ad771349ac58df19ad6
Cluster size: 6
Instance type: i3.4xlarge
OS (RHEL/CentOS/Ubuntu/AWS AMI): ami-0bfd1285501f5d639 (eu-north-1)

SCT test id: 4e19f694-11d2-4eb7-bfd6-2251fca7ac53
Job link: https://jenkins.scylladb.com/view/scylla-4.3/job/scylla-4.3/job/longevity/job/longevity-cdc-100gb-4h-test/7
Test name:
Test config: https://github.com/scylladb/scylla-cluster-tests/blob/branch-4.3/test-cases/longevity/longevity-cdc-100gb-4h.yaml
DB logs: https://cloudius-jenkins-test.s3.amazonaws.com/4e19f694-11d2-4eb7-bfd6-2251fca7ac53/20201110_222957/db-cluster-4e19f694.zip
Target node for decommision was: 10.0.1.88
Failures on seed node: 10.0.2.67

![image](https://user-images.githubusercontent.com/63434/98816863-de971800-245b-11eb-8beb-3ae352e10ead.png)

![image](https://user-images.githubusercontent.com/63434/98816914-ef478e00-245b-11eb-85d9-02dd4cb3e1e4.png)

Significant amount (400+) of same backtraces:

```
(DatabaseLogEvent Severity.ERROR): type=BACKTRACE regex=backtrace line_number=32617 node=Node longevity-cdc-100gb-4h-4-3-db-node-4e19f694-1 [13.53.123.179 | 10.0.2.67] (seed: True)
2020-11-10T19:42:11+00:00  longevity-cdc-100gb-4h-4-3-db-node-4e19f694-1 !ERR     | scylla: [shard 11] compaction_manager - compaction failed: seastar::nested_exception: seastar::internal::backtraced (bad_function_call Backtrace:    0x2fb7e0d#012   0x2fb8060#012   0x2fb84c9#012   0xf69b9d#012   0xf69c9e#012   0x10f1d5e#012   0x10f1d88#012   0x134341d#012   0x1344773#012   0x1345013#012   0x2df744c#012   --------#012   N7seastar12continuationINS_8internal22promise_base_with_typeIvEEZNS_5asyncIZZN8sstables10compaction5setupI33noop_compacted_fragments_consumerEENS_6futureIvEET_ENUl20flat_mutation_readerE_clESC_EUlvE_JEEENS_8futurizeINSt9result_ofIFNSt5decayISB_E4typeEDpNSH_IT0_E4typeEEE4typeEE4typeENS_17thread_attributesEOSB_DpOSK_EUlvE0_ZNSA_14then_impl_nrvoISX_SA_EET0_SU_EUlOS3_RSX_ONS_12future_stateINS1_9monostateEEEE_vEE#012   --------#012   N7seastar12continuationINS_8internal22promise_base_with_typeIvEENS_6futureIvE12finally_bodyIZNS_5asyncIZZN8sstables10compaction5setupI33noop_compacted_fragments_consumerEES5_T_ENUl20flat_mutation_readerE_clESD_EUlvE_JEEENS_8futurizeINSt9result_ofIFNSt5decayISC_E4typeEDpNSI_IT0_E4typeEEE4typeEE4typeENS_17thread_attributesEOSC_DpOSL_EUlvE1_Lb0EEEZNS5_17then_wrapped_nrvoIS5_SZ_EENSG_ISC_E4typeEOT0_EUlOS3_RSZ_ONS_12future_stateINS1_9monostateEEEE_vEE#012) (while cleaning up after seastar::broken_promise (broken promise)): retrying
backtrace > at /usr/include/c++/10/bits/basic_string.h:323
 (inlined by) seastar::current_backtrace_tasklocal() at ./build/release/seastar/./seastar/src/util/backtrace.cc:86
seastar::current_tasktrace() at /usr/include/c++/10/bits/basic_string.h:323
seastar::current_backtrace() at /usr/include/c++/10/bits/basic_string.h:323
seastar::internal::backtraced::backtraced&>(seastar::internal::backtraced&) at row_cache.cc:?
std::__exception_ptr::exception_ptr seastar::make_backtraced_exception_ptr() at row_cache.cc:?
 (inlined by) std::__exception_ptr::exception_ptr seastar::make_backtraced_exception_ptr() at ././seastar/include/seastar/util/backtrace.hh:211
void seastar::throw_with_backtrace() at ./mutation_reader.cc:1334
queue_reader::next_partition() at ./mutation_reader.cc:1334
void flat_mutation_reader::impl::consume_pausable_in_thread > > >, flat_mutation_reader::filter>(std::reference_wrapper > > >, flat_mutation_reader::filter, std::chrono::time_point > >) at ././flat_mutation_reader.hh:190
auto flat_mutation_reader::impl::consume_in_thread >, flat_mutation_reader::filter>(stable_flattened_mutations_consumer >, flat_mutation_reader::filter, std::chrono::time_point > >) at ././flat_mutation_reader.hh:273
 (inlined by) auto flat_mutation_reader::consume_in_thread >, flat_mutation_reader::filter>(stable_flattened_mutations_consumer >, flat_mutation_reader::filter, std::chrono::time_point > >) at ././flat_mutation_reader.hh:383
 (inlined by) seastar::future sstables::compaction::setup(noop_compacted_fragments_consumer)::{lambda(flat_mutation_reader)#1}::operator()(flat_mutation_reader)::{lambda()#1}::operator()() at ./sstables/compaction.cc:612
void std::__invoke_impl sstables::compaction::setup(noop_compacted_fragments_consumer)::{lambda(flat_mutation_reader)#1}::operator()(flat_mutation_reader)::{lambda()#1}>(std::__invoke_other, seastar::future sstables::compaction::setup(noop_compacted_fragments_consumer)::{lambda(flat_mutation_reader)#1}::operator()(flat_mutation_reader)::{lambda()#1}&&) at /usr/include/c++/10/bits/invoke.h:60
 (inlined by) std::__invoke_result sstables::compaction::setup(noop_compacted_fragments_consumer)::{lambda(flat_mutation_reader)#1}::operator()(flat_mutation_reader)::{lambda()#1}>::type std::__invoke sstables::compaction::setup(noop_compacted_fragments_consumer)::{lambda(flat_mutation_reader)#1}::operator()(flat_mutation_reader)::{lambda()#1}>(seastar::future sstables::compaction::setup(noop_compacted_fragments_consumer)::{lambda(flat_mutation_reader)#1}::operator()(flat_mutation_reader)::{lambda()#1}&&, (seastar::future sstables::compaction::setup(noop_compacted_fragments_consumer)::{lambda(flat_mutation_reader)#1}::operator()(flat_mutation_reader)::{lambda()#1}&&)...) at /usr/include/c++/10/bits/invoke.h:95
 (inlined by) _ZSt12__apply_implIZZN8sstables10compaction5setupI33noop_compacted_fragments_consumerEEN7seastar6futureIvEET_ENUl20flat_mutation_readerE_clES8_EUlvE_St5tupleIJEEJEEDcOS7_OT0_St16integer_sequenceImJXspT1_EEE at /usr/include/c++/10/tuple:1723
 (inlined by) _ZSt5applyIZZN8sstables10compaction5setupI33noop_compacted_fragments_consumerEEN7seastar6futureIvEET_ENUl20flat_mutation_readerE_clES8_EUlvE_St5tupleIJEEEDcOS7_OT0_ at /usr/include/c++/10/tuple:1734
 (inlined by) seastar::future seastar::futurize::apply sstables::compaction::setup(noop_compacted_fragments_consumer)::{lambda(flat_mutation_reader)#1}::operator()(flat_mutation_reader)::{lambda()#1}>(seastar::future sstables::compaction::setup(noop_compacted_fragments_consumer)::{lambda(flat_mutation_reader)#1}::operator()(flat_mutation_reader)::{lambda()#1}&&, std::tuple<>&&) at ././seastar/include/seastar/core/future.hh:2099
 (inlined by) seastar::futurize sstables::compaction::setup(noop_compacted_fragments_consumer)::{lambda(flat_mutation_reader)#1}::operator()(flat_mutation_reader)::{lambda()#1}>::type ()>::type>::type seastar::async sstables::compaction::setup(noop_compacted_fragments_consumer)::{lambda(flat_mutation_reader)#1}::operator()(flat_mutation_reader)::{lambda()#1}>(seastar::thread_attributes, seastar::future sstables::compaction::setup(noop_compacted_fragments_consumer)::{lambda(flat_mutation_reader)#1}::operator()(flat_mutation_reader)::{lambda()#1}&&, (std::decay sstables::compaction::setup(noop_compacted_fragments_consumer)::{lambda(flat_mutation_reader)#1}::operator()(flat_mutation_reader)::{lambda()#1}>&&)...)::{lambda()#1}::operator()() const at ././seastar/include/seastar/core/thread.hh:258
 (inlined by) seastar::noncopyable_function::direct_vtable_for sstables::compaction::setup(noop_compacted_fragments_consumer)::{lambda(flat_mutation_reader)#1}::operator()(flat_mutation_reader)::{lambda()#1}>::type ()>::type>::type seastar::async sstables::compaction::setup(noop_compacted_fragments_consumer)::{lambda(flat_mutation_reader)#1}::operator()(flat_mutation_reader)::{lambda()#1}>(seastar::thread_attributes, seastar::future sstables::compaction::setup(noop_compacted_fragments_consumer)::{lambda(flat_mutation_reader)#1}::operator()(flat_mutation_reader)::{lambda()#1}&&, (std::decay sstables::compaction::setup(noop_compacted_fragments_consumer)::{lambda(flat_mutation_reader)#1}::operator()(flat_mutation_reader)::{lambda()#1}>&&)...)::{lambda()#1}>::call(seastar::noncopyable_function const*) at ././seastar/include/seastar/util/noncopyable_function.hh:116
seastar::noncopyable_function::operator()() const at /usr/include/c++/10/bits/basic_string.h:323
 (inlined by) seastar::thread_context::main() at ./build/release/seastar/./seastar/src/core/thread.cc:297
```

```
$ hydra investigate show-monitor 4e19f694-11d2-4eb7-bfd6-2251fca7ac53
```

**Comment by roydahan** [comment] 2020-11-11 13:56
@slivne who can take a look on this?

**Comment by raphaelsc** [comment] 2020-11-11 14:49
> @slivne who can take a look on this?

Is this a regression?

**Comment by haaawk** [comment] 2020-11-11 15:11
At the first sight on backtrace, seems like a problem with a flat mutation reader for cache during compaction.

**Comment by raphaelsc** [comment] 2020-11-11 17:41
this problem can be reproduced by enabling cdc, writing to the original table which cdc was enabled at, then running cleanup.

**Comment by raphaelsc** [comment] 2020-11-11 19:13
queue_reader:
    virtual void next_partition() override {
        throw_with_backtrace<std::bad_function_call>();
    }

so cleanup seems to fail when skipping to next partition in queue_reader

queue_reader is used for data segregation for TWCS. 

@denesb could it be a bad interaction between timestamp_based_splitting_mutation_writer and cleanup compaction (which forces reader to advance to next partition when filtering)?

**Comment by raphaelsc** [comment] 2020-11-11 19:28
turns out that's the root cause. with segregator, cleanup compaction is unable to skip to next partition.

**Comment by raphaelsc** [comment] 2020-11-11 19:32
@denesb is there any reason we don't compact data first before feeding them to the consumers in the interposer? if tombstones and data shadowed by tombstones falls into different consumers, then we missed the opportunity to compact data. should we invert the order? is there any reason why each consumer in the interposer compact its own data separately?

**Comment by raphaelsc** [comment] 2020-11-11 20:42
dismiss my last comment

**Comment by raphaelsc** [comment] 2020-11-11 20:45
the fix for this issue is about moving the partition filtering to producer side only, right now we may skip to next partition in the consumer if data segregation is enabled, which is definitely wrong.

**Comment by raphaelsc** [comment] 2020-11-11 21:06
cooking a patch...

**Comment by raphaelsc** [comment] 2020-11-11 22:14
regression started here 55a8b6e3c9

**Comment by raphaelsc** [comment] 2020-11-11 22:17
patch sent to scylladb-dev ml as "compaction: Make sure a partition is filtered out only by producer"

**Comment by slivne** [comment] 2020-11-12 10:13
@raphaelsc without CDC how can we reproduce this - can you please provide a scenario (simple one) so we can try and validate old versions have this as well - and if needed add a dtest for this / check why current dtests do not have issues.

**Comment by raphaelsc** [comment] 2020-11-12 14:33
> @raphaelsc without CDC how can we reproduce this - can you please provide a scenario (simple one) so we can try and validate old versions have this as well - and if needed add a dtest for this / check why current dtests do not have issues.

@slivne 

I think we can reproduce it like this:
1) start #1 node
2) write partitions spanning multiple windows with USING TIMESTAMP  (to trigger interposer), to a table with 1-min-window TWCS.
3) start #2 node, wait for its bootstrap completion
4) flush and cleanup #1 node

I'll come up with a dtest.

**Closed** 2020-11-12 19:52 UTC
Labels: Backport 4.1, backport 4.2, backport 4.3, bug, compaction

**Comment by slivne** [comment] 2020-11-15 12:25
@avikivity please backport to 4.3

**Comment by slivne** [comment] 2020-11-18 12:17
@avikivity ping

**Comment by avikivity** [comment] 2020-11-19 12:09
Backported to 4.1, 4.2, 4.3.
