### ISSUE TITLE
seastar/src/core/file.cc:515: virtual seastar::append_challenged_posix_file_impl::~append_challenged_posix_file_impl(): Assertion `_closing_state == state::closed' failed.

### ISSUE THREAD

**Issue by gleb-cloudius** [scylladb/scylla#5657] opened 2020-01-28 08:28 UTC
*Installation details*
Scylla version (or git commit hash): e1b22b6a4c56b4f1d0adf65d1a11db4bcb51fe7d

When I/O error happens (in my case `Storage I/O error: 24: filesystem error: open failed: Too many open files`) node crashed with an assertion `seastar/src/core/file.cc:515: virtual seastar::append_challenged_posix_file_impl::~append_challenged_posix_file_impl(): Assertion `_closing_state == state::closed' failed.`

**Comment by espindola** [comment] 2020-01-28 16:20
Do you have a core dump?

**Comment by slivne** [comment] 2020-03-16 21:56
@espindola / @gleb-cloudius is this resolved / is there a core - if we can't do anything with this info please close

**Comment by espindola** [comment] 2020-03-16 22:24
I do need a core or instructions on how to reproduce this.

**Comment by slivne** [comment] 2020-03-28 19:53
@gleb-cloudius closing this if you hit it again please provide a core / instructions on how to reproduce this

**Closed by slivne** 2020-03-28 19:53 UTC

**Comment by avikivity** [comment] 2020-09-21 14:59
@bhalevy you added the backport candidate label, but what should be backported?

**Comment by bhalevy** [comment] 2020-09-21 15:57
> @bhalevy you added the backport candidate label, but what should be backported?

Looks like 35892e4557c6833f4698ddacbe2116e52662c308 is in all active open source branches so no backport required.
