### ISSUE TITLE
swagger-ui does not work

### ISSUE THREAD

**Issue by asias** [scylladb/scylla#10700] opened 2022-05-31 07:21 UTC
scylla: dc5c9321fee9e307c3e95c3882564b0053614a98

1) Start scylla with   --api-ui-dir 
scylla --api-ui-dir  /home/asias/scylladb/swagger-ui/dist

2) Access ui from browser 
http://127.0.0.1:10000/ui/

![image](https://user-images.githubusercontent.com/320076/171115549-7caa6aa8-683d-49d9-a889-a0ee9e3bf382.png)

The rest ui does not work properly.

**Comment by asias** [comment] 2022-06-22 01:33
@amnonh Ping. Any ideas? This sounds like a regression.

**Comment by amnonh** [comment] 2022-06-22 05:49
I just compile and run scylla on my local machine (using dbuild) and the swagger-ui worked as expected.
It looks like some of the files are missing in your directory,
can you make sure the ```swagger-ui``` submodule is uptodate?
i.e.:
```
git submodule sync  swagger-ui
git submodule update --init --recursive  swagger-ui
```

**Comment by asias** [comment] 2022-06-22 06:13
This is what I have before I run the submodule cmd:

[swagger.ui.txt](https://github.com/scylladb/scylla/files/8954852/swagger.ui.txt)

The submodule cmd does not change anything.

So I do not think I miss any swagger-ui file. 

I do not run inside dbuild. I run scylla after I install it using the tarball. Maybe we do not package the ui files correctly?

**Comment by amnonh** [comment] 2022-06-22 06:21
if you are taking it from a tarball then it might not be packaged correctly, swagger files should be under swagger-ui/dist/
```
$ ls swagger-ui/dist/
css  fonts  images  index.html  lang  lib  o2c.html  swagger-ui.js  swagger-ui.min.js
```

**Comment by asias** [comment] 2022-06-22 06:24
```
$ tree /home/asias/scylladb/swagger-ui/dist/ 
/home/asias/scylladb/swagger-ui/dist/
├── css
│   ├── print.css
│   ├── reset.css
│   ├── screen.css
│   ├── style.css
│   └── typography.css
├── fonts
│   ├── DroidSans-Bold.ttf
│   └── DroidSans.ttf
├── images
│   ├── collapse.gif
│   ├── expand.gif
│   ├── explorer_icons.png
│   ├── favicon-16x16.png
│   ├── favicon-32x32.png
│   ├── favicon.ico
│   ├── logo_small.png
│   ├── pet_store_api.png
│   ├── throbber.gif
│   └── wordnik_api.png
├── index.html
├── lang
│   ├── ca.js
│   ├── el.js
│   ├── en.js
│   ├── es.js
│   ├── fr.js
│   ├── geo.js
│   ├── it.js
│   ├── ja.js
│   ├── ko-kr.js
│   ├── pl.js
│   ├── pt.js
│   ├── ru.js
│   ├── translator.js
│   ├── tr.js
│   └── zh-cn.js
├── lib
│   ├── backbone-min.js
│   ├── es5-shim.js
│   ├── handlebars-4.0.5.js
│   ├── highlight.9.1.0.pack_extended.js
│   ├── highlight.9.1.0.pack.js
│   ├── jquery-1.8.0.min.js
│   ├── jquery.ba-bbq.min.js
│   ├── jquery.slideto.min.js
│   ├── jquery.wiggle.min.js
│   ├── jsoneditor.min.js
│   ├── js-yaml.min.js
│   ├── lodash.min.js
│   ├── marked.js
│   ├── object-assign-pollyfill.js
│   ├── sanitize-html.min.js
│   └── swagger-oauth.js
├── o2c.html
├── swagger-ui.js
└── swagger-ui.min.js

5 directories, 52 files

```

**Comment by amnonh** [comment] 2022-06-22 09:29
Issue was solved by adding a trailing ```/``` which was missing, I think we can close this

**Comment by asias** [comment] 2022-06-22 14:00
It is very easy for users to miss the trailing "/". I think we should fix scylla to allow it work with or without the trailing "/".

**Comment by amnonh** [comment] 2022-06-22 14:16
alternatively, it could be a seastar issue with the right description and fix it when registering a directory reader

**Comment by asias** [comment] 2022-06-24 02:12
> alternatively, it could be a seastar issue with the right description and fix it when registering a directory reader

I do not mind which way to fix. Let's close it when one of them is merged.

**Closed** 2022-06-27 06:32 UTC

**Comment by avikivity** [comment] 2022-07-03 11:33
Not a regression, and minor, so not backporting.
