### ISSUE TITLE
scylla_setup: RAID is created even when only one disk is selected

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#2674] opened 2017-08-06 06:43 UTC
*Installation details*
Scylla version (or git commit hash): 2.0

Currently, scylla_setup install RAID0, even when only one disk is selected, both in the interactive and command line parameters versions.

**Comment by glommer** [comment] 2017-08-06 06:50
On Sun, Aug 6, 2017 at 2:43 AM, Tzach Livyatan <notifications@github.com>
wrote:

> *Installation details*
> Scylla version (or git commit hash): 2.0
>
> Currently, scylla_setup install RAID0, even when only one disk is
> selected, both in the interactive and command line parameters versions.
>

And what is the problem with that? This is by design as far as I know, so
we can have some consistency.

**Comment by avikivity** [comment] 2020-08-05 16:24
@syuu1228 I think this was fixed?

**Comment by glommer** [comment] 2020-08-06 02:30
This should be fixed by 32896422233722b316063266960a3d91e70adc5b, with the option to override it through the command line.

**Comment by avikivity** [comment] 2020-08-06 08:46
I seen a ghost

**Closed by avikivity** 2020-08-06 08:46 UTC
Labels: bug
