### ISSUE TITLE
Coredump during multiple node hard reboot (MV-SI test)

### ISSUE THREAD

**Issue by juliayakovlev** [scylladb/scylla#4912] opened 2019-08-27 16:00 UTC
*Installation details*
Scylla version (or git commit hash): 3.1.0.rc4-0.20190826.e4a39ed31
Cluster size: 5 nodes
OS (RHEL/CentOS/Ubuntu/AWS AMI): ami-0ececa5cacea302a8

Scenario similar to #4866 
Cordump during MV-SI longevity test.
Segmentation fault was received during multiple node hard reboot.
 When rebooting was started 3th time, another node got coredump:

```
[centos@ip-10-0-12-59 ~]$ addr2line -Cpife /usr/lib/debug/opt/scylladb/libexec/scylla-3.1.0.rc4-0.20190826.e4a39ed31.el7.x86_64.debug
0x00000000041808b2
0x000000000406d935
0x000000000406dc35
0x000000000406dc83
0x00007f42ec11002f
0x00006090091207ff
```

Decoded:
```
void seastar::backtrace<seastar::backtrace_buffer::append_backtrace()::{lambda(seastar::frame)#1}>(seastar::backtrace_buffer::append_backtrace()::{lambda(seastar::frame)#1}&&) at /usr/include/boost/program_options/variables_map.hpp:146
seastar::backtrace_buffer::append_backtrace() at /usr/include/boost/program_options/variables_map.hpp:146
 (inlined by) print_with_backtrace at /jenkins/workspace/scylla-3.1/relocatable-pkg/scylla/seastar/build/release/../../src/core/reactor.cc:1104
seastar::print_with_backtrace(char const*) at /usr/include/boost/program_options/variables_map.hpp:146
sigsegv_action at /usr/include/boost/program_options/variables_map.hpp:146
 (inlined by) operator() at /jenkins/workspace/scylla-3.1/relocatable-pkg/scylla/seastar/build/release/../../src/core/reactor.cc:5012
 (inlined by) _FUN at /jenkins/workspace/scylla-3.1/relocatable-pkg/scylla/seastar/build/release/../../src/core/reactor.cc:5008
```

Coredump:
```
           PID: 2360 (scylla)
           UID: 996 (scylla)
           GID: 1001 (scylla)
        Signal: 11 (SEGV)
     Timestamp: Tue 2019-08-27 14:20:06 UTC (1h 29min ago)
  Command Line: /usr/bin/scylla --blocked-reactor-notify-ms 500 --abort-on-lsa-bad-alloc 1 --abort-on-seastar-bad-alloc --log-to-syslog 1 --log-to-stdout 0 --default-log-level info --network-stack posix --io-properties-file=/etc/scylla.d
    Executable: /opt/scylladb/libexec/scylla
 Control Group: /
       Boot ID: d1cd65d3aaeb4bceaea0724a34ea4daf
    Machine ID: df877a200226bc47d06f26dae0736ec9
      Hostname: ip-10-0-12-59.eu-west-1.compute.internal
       Message: Process 2360 (scylla) of user 996 dumped core.
                
                Stack trace of thread 2372:
                #0  0x0000000000000000 n/a (n/a)
```
Full coredump info was uploaded to 
```upload.scylladb.com/core.scylla.996.d1cd65d3aaeb4bceaea0724a34ea4daf.2360.1566915606000000.gz```

Job log: ```https://cloudius-jenkins-test.s3.amazonaws.com/ad118a96-b1c6-4023-bccc-614871d1e570/job_log.zip```

**Comment by avikivity** [comment] 2019-08-27 16:50
I'm looking at it.

**Comment by avikivity** [comment] 2019-08-27 16:51
@hagitsegev where can I find the rpms or relocatable package for this version?

**Comment by bentsi** [comment] 2019-08-27 16:56
https://jenkins.scylladb.com/view/scylla-3.1/job/scylla-3.1/job/relocatable-pkg/123/artifact/

**Comment by avikivity** [comment] 2019-08-27 19:26
The core dump is not fully uploaded.

**Comment by juliayakovlev** [comment] 2019-08-29 08:19
@avikivity  The coredump reproduced and uploaded to ```upload.scylladb.com/core.scylla.996.734f423cf9384cbc9284c1d343649884.2314.1567008482000/core.scylla.996.734f423cf9384cbc9284c1d343649884.2314.1567008482000000```

Cluster is alive now if you need it.

Relevant part from the log:
[coredump_7612.log](https://github.com/scylladb/scylla/files/3554540/coredump_7612.log)

**Comment by bentsi** [comment] 2019-08-29 08:28
```
 963795 < t:2019-08-28 16:08:10,241 f:cluster.py      l:1186 c:sdcm.cluster         p:DEBUG > 019-08-28T16:07:56+00:00  ip-10-0-65-140 !INFO    | scylla: [shard 13] compaction - Compacted 2 sstables to [/var/lib/scylla/data/mview/users-5
 963795 90c5860c98711e9b953000000000003/mc-5081-big-Data.db:level=0, ]. 717611348 bytes to 619815673 (~86% of original) in 5846ms = 101.11MB/s. ~67840 total partitions merged to 58493.
 963796 
 963797 < t:2019-08-28 16:08:10,241 f:cluster.py      l:1186 c:sdcm.cluster         p:DEBUG > 2019-08-28T16:07:56+00:00  ip-10-0-65-140 !INFO    | scylla: [shard 11] compaction - Compacted 2 sstables to [/var/lib/scylla/data/mview/users-
 963797 590c5860c98711e9b953000000000003/mc-5065-big-Data.db:level=0, ]. 714813816 bytes to 616553196 (~86% of original) in 6451ms = 91.15MB/s. ~67584 total partitions merged to 58185.
 963798 
 963799 < t:2019-08-28 16:08:10,242 f:cluster.py      l:1186 c:sdcm.cluster         p:DEBUG > 2019-08-28T16:07:56+00:00  ip-10-0-65-140 !INFO    | scylla: [shard 11] compaction - Compacting [/var/lib/scylla/data/mview/users-590c5860c9871
 963799 1e9b953000000000003/mc-5065-big-Data.db:level=0, /var/lib/scylla/data/mview/users-590c5860c98711e9b953000000000003/mc-5023-big-Data.db:level=0, ]
 963800 
 963801 < t:2019-08-28 16:08:10,242 f:cluster.py      l:1186 c:sdcm.cluster         p:DEBUG > 2019-08-28T16:08:00+00:00  ip-10-0-65-140 !INFO    | scylla: [shard 0] compaction - Compacted 2 sstables to [/var/lib/scylla/data/mview/users-5
 963801 90c5860c98711e9b953000000000003/mc-5124-big-Data.db:level=0, ]. 1303023396 bytes to 1012214356 (~77% of original) in 9817ms = 98.33MB/s. ~123136 total partitions merged to 95506.
 963802 
 963803 < t:2019-08-28 16:08:10,242 f:cluster.py      l:1186 c:sdcm.cluster         p:DEBUG > 2019-08-28T16:08:02+00:00  ip-10-0-65-140 !INFO    | scylla: [shard 0] storage_service - Node 10.0.169.163 state jump to normal
 963804 
 963805 < t:2019-08-28 16:08:10,242 f:cluster.py      l:1186 c:sdcm.cluster         p:DEBUG > 2019-08-28T16:08:02+00:00  ip-10-0-65-140 !INFO    | scylla: [shard 3] compaction - Compacting [/var/lib/scylla/data/system/peers-37f71aca7dc23
 963805 83ba70672528af04d4f/mc-143-big-Data.db:level=0, /var/lib/scylla/data/system/peers-37f71aca7dc2383ba70672528af04d4f/mc-129-big-Data.db:level=0, ]
 963806 
 963807 < t:2019-08-28 16:08:10,242 f:cluster.py      l:1186 c:sdcm.cluster         p:DEBUG > 2019-08-28T16:08:02+00:00  ip-10-0-65-140 !INFO    | scylla: Segmentation fault on shard 10.
 963808 
 963809 < t:2019-08-28 16:08:10,242 f:cluster.py      l:1186 c:sdcm.cluster         p:DEBUG > 2019-08-28T16:08:02+00:00  ip-10-0-65-140 !INFO    | scylla: Backtrace:
 963810 
 963811 < t:2019-08-28 16:08:10,242 f:cluster.py      l:1186 c:sdcm.cluster         p:DEBUG > 2019-08-28T16:08:02+00:00  ip-10-0-65-140 !INFO    | scylla: 0x00000000041808b2
 963812 
 963813 < t:2019-08-28 16:08:10,243 f:cluster.py      l:1186 c:sdcm.cluster         p:DEBUG > 2019-08-28T16:08:02+00:00  ip-10-0-65-140 !INFO    | scylla: 0x000000000406d935
 963814 
 963815 < t:2019-08-28 16:08:10,243 f:cluster.py      l:1186 c:sdcm.cluster         p:DEBUG > 2019-08-28T16:08:02+00:00  ip-10-0-65-140 !INFO    | scylla: 0x000000000406dc35
 963816 
 963817 < t:2019-08-28 16:08:10,243 f:cluster.py      l:1186 c:sdcm.cluster         p:DEBUG > 2019-08-28T16:08:02+00:00  ip-10-0-65-140 !INFO    | scylla: 0x000000000406dc83
 963818 
 963819 < t:2019-08-28 16:08:10,243 f:cluster.py      l:1186 c:sdcm.cluster         p:DEBUG > 2019-08-28T16:08:02+00:00  ip-10-0-65-140 !INFO    | scylla: 0x00007f01c97d402f
 963820 
 963821 < t:2019-08-28 16:08:10,243 f:cluster.py      l:1186 c:sdcm.cluster         p:DEBUG > 2019-08-28T16:08:02+00:00  ip-10-0-65-140 !INFO    | scylla: [shard 3] compaction - Compacted 2 sstables to [/var/lib/scylla/data/system/peers-
 963821 37f71aca7dc2383ba70672528af04d4f/mc-157-big-Data.db:level=0, ]. 22233 bytes to 11275 (~50% of original) in 62ms = 0.17MB/s. ~256 total partitions merged to 1.
 963822 
 963823 < t:2019-08-28 16:08:10,243 f:cluster.py      l:1186 c:sdcm.cluster         p:DEBUG > 2019-08-28T16:08:02+00:00  ip-10-0-65-140 !INFO    | kernel: reactor-10[2324]: segfault at 0 ip 0000000000000000 sp 000060a00b7bfeb8 error 14 i
 963823 n scylla[3ff000+1000]
 963824 
 963825 < t:2019-08-28 16:08:10,243 f:cluster.py      l:1186 c:sdcm.cluster         p:DEBUG > 2019-08-28T16:08:02+00:00  ip-10-0-65-140 !INFO    | kernel: Code: Bad RIP value.
 963826 
 963827 < t:2019-08-28 16:08:10,243 f:cluster.py      l:1186 c:sdcm.cluster         p:DEBUG > 2019-08-28T16:08:06+00:00  ip-10-0-65-140 !NOTICE  | sudo:  centos : TTY=unknown ; PWD=/home/centos ; USER=root ; COMMAND=/bin/coredumpctl --no
 963827 -pager --no-legend
 963828 
 963829 < t:2019-08-28 16:08:10,243 f:cluster.py      l:1186 c:sdcm.cluster         p:DEBUG > 2019-08-28T16:08:06+00:00  ip-10-0-65-140 !INFO    | sudo: pam_unix(sudo:session): session opened for user root by (uid=0)
 963830 
 963831 < t:2019-08-28 16:08:10,243 f:cluster.py      l:1186 c:sdcm.cluster         p:DEBUG > 2019-08-28T16:08:06+00:00  ip-10-0-65-140 !INFO    | sudo: pam_unix(sudo:session): session closed for user root
```

**Comment by bentsi** [comment] 2019-08-29 09:01
Download instructions:
`gsutil cp gs://upload.scylladb.com/core.scylla.996.734f423cf9384cbc9284c1d343649884.2314.1567008482000/core.scylla.996.734f423cf9384cbc9284c1d343649884.2314.1567008482000000 .`

**Comment by avikivity** [comment] 2019-08-29 11:59
Change your upload to add some uuid in front to avoid name clashes.

**Comment by avikivity** [comment] 2019-08-29 12:00
@juliayakovlev I don't need the cluster, just the core.

**Comment by slivne** [comment] 2019-09-01 07:51
@avikivity did you have a look at the uploaded core file ?

**Comment by avikivity** [comment] 2019-09-01 10:17
This looks like a duplicate of #4866, but the fix is already in.

**Comment by avikivity** [comment] 2019-09-01 10:18
```
   │3631        void storage_proxy::on_down(const gms::inet_address& endpoint) {                                                                                                                                      │
   │3632            assert(thread::running_in_thread());                                                                                                                                                              │
   │3633            auto it = _view_update_handlers_list->begin();                                                                                                                                                    │
   │3634            while (it != _view_update_handlers_list->end()) {                                                                                                                                                 │
  >│3635                auto guard = it->shared_from_this();                                                                                                                                                          │
   │3636                if (it->get_targets().count(endpoint) > 0) {                                                                                                                                                  │
   │3637                    it->timeout_cb();                                                                                                                                                                         │
   │3638                }                                                                                                                                                                                             │
   │3639                ++it;                                                                                                                                                                                         │
   │3640                seastar::thread::yield();                                                                                                                                                                     │
   │3641            }                                                                                                                                                                                                 │
   │3642        };                                                                                                                                                                                                    │
   │3643             
```

**Comment by juliayakovlev** [comment] 2019-09-01 10:39
@avikivity 
I ran this test because the  #4866 was fixed and expected that the fix is in. 
#4866 was found on 3.1.0.rc3.
This coredump happened on 3.1.0.rc4. Should the fix be in the 3.1.0.rc4?

**Comment by avikivity** [comment] 2019-09-01 11:25
I think the problem is that after yield() was called, the timeout (or perhaps something else) caused *it to be removed, and now it points at a freed object.

**Comment by avikivity** [comment] 2019-09-01 11:26
@juliayakovlev the fix is in, but was not good enough

**Comment by avikivity** [comment] 2019-09-01 16:04
Please see ami-093c99515247077f1 for an ami with the fix (eu-west-1).

**Comment by juliayakovlev** [comment] 2019-09-02 09:21
Issue is not reproduced with ami-093c99515247077f1

**Comment by slivne** [comment] 2019-09-02 09:24
@avikivity did you send the patch ?

**Comment by juliayakovlev** [comment] 2019-09-02 09:31
> Please see ami-093c99515247077f1 for an ami with the fix (eu-west-1).

I ran with this one

**Comment by avikivity** [comment] 2019-09-02 15:07
@slivne yes I did

**Closed** 2019-09-05 06:34 UTC
Labels: Backport candidate, high
