### ISSUE TITLE
Segmentation fault in multiple nodes at the same time(hinted handoff related)

### ISSUE THREAD

**Issue by r4fek** [scylladb/scylla#6086] opened 2020-03-26 07:43 UTC
*Installation details*
Scylla version (or git commit hash): latest 3.2.3
Cluster size: 29
OS (RHEL/CentOS/Ubuntu/AWS AMI): Debian Stretch

I upgraded yesterday from 3.1 to 3.2.3 and reenabled hinted handoff. Unfortunately my nodes started to restart after some time. In logs I could see this:

```
mar 26 04:17:25 lati-dbs1 scylla[47108]:  [shard 1] storage_proxy - Exception when communicating with 10.195.15.220: std::bad_alloc (std::bad_alloc)
mar 26 04:17:25 lati-dbs1 scylla[47108]:  [shard 1] storage_proxy - exception during mutation write to 10.195.15.220: std::bad_alloc (std::bad_alloc)
mar 26 04:17:25 lati-dbs1 scylla[47108]:  [shard 6] storage_proxy - Exception when communicating with 10.195.15.220: std::bad_alloc (std::bad_alloc)
mar 26 04:17:25 lati-dbs1 scylla[47108]:  [shard 6] query_processor - failed to cache the entry
mar 26 04:17:25 lati-dbs1 scylla[47108]:  [shard 6] query_processor - failed to cache the entry
mar 26 04:17:25 lati-dbs1 scylla[47108]:  [shard 5] storage_proxy - Exception when communicating with 10.195.15.220: std::bad_alloc (std::bad_alloc)
mar 26 04:17:26 lati-dbs1 scylla[47108]:  [shard 5] storage_proxy - Exception when communicating with 10.195.15.220: std::bad_alloc (std::bad_alloc)
mar 26 04:17:26 lati-dbs1 scylla[47108]:  [shard 25] storage_proxy - Exception when communicating with 10.195.15.220: std::bad_alloc (std::bad_alloc)
mar 26 04:17:26 lati-dbs1 scylla[47108]:  [shard 1] storage_proxy - Exception when communicating with 10.195.15.220: std::bad_alloc (std::bad_alloc)
mar 26 04:17:26 lati-dbs1 scylla[47108]:  [shard 8] storage_proxy - Exception when communicating with 10.195.15.220: std::bad_alloc (std::bad_alloc)
mar 26 04:17:26 lati-dbs1 scylla[47108]:  [shard 5] storage_proxy - Exception when communicating with 10.195.15.220: std::bad_alloc (std::bad_alloc)
mar 26 04:17:26 lati-dbs1 scylla[47108]:  [shard 5] storage_proxy - Exception when communicating with 10.195.15.220: std::bad_alloc (std::bad_alloc)
mar 26 04:17:26 lati-dbs1 scylla[47108]:  [shard 1] storage_proxy - Exception when communicating with 10.195.15.220: std::bad_alloc (std::bad_alloc)
mar 26 04:17:26 lati-dbs1 scylla[47108]: Segmentation fault on shard 6.
mar 26 04:17:26 lati-dbs1 scylla[47108]: Backtrace:
mar 26 04:17:26 lati-dbs1 scylla[47108]:   0x0000000002addb42
mar 26 04:17:26 lati-dbs1 scylla[47108]:   0x0000000002a5673b
mar 26 04:17:26 lati-dbs1 scylla[47108]:   0x0000000002a56a35
mar 26 04:17:26 lati-dbs1 scylla[47108]:   0x0000000002a56a80
mar 26 04:17:26 lati-dbs1 scylla[47108]:   0x00007f1634bf4e7f
mar 26 04:17:26 lati-dbs1 scylla[47108]:   0x00000000018b36f3
mar 26 04:17:26 lati-dbs1 scylla[47108]:   0x00000000018b4ea1
mar 26 04:17:26 lati-dbs1 scylla[47108]:   0x00000000018b597e
mar 26 04:17:26 lati-dbs1 scylla[47108]:   0x00000000007e0673
mar 26 04:22:29 lati-dbs1 systemd[1]: scylla-server.service: Main process exited, code=killed, status=11/SEGV
mar 26 04:22:29 lati-dbs1 systemd[1]: scylla-server.service: Unit entered failed state.
mar 26 04:22:29 lati-dbs1 systemd[1]: scylla-server.service: Failed with result 'signal'.
```

Decoded backtrace:

```
Sync::production root@lati-dbs1:~# seastar-addr2line -e /usr/lib/debug/.build-id/18/6045664da749e2c77b109834b4e13e8dd60f28.debug -f backtrace.txt
/usr/lib/debug/.build-id/18/6045664da749e2c77b109834b4e13e8dd60f28.debug: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /opt/scylladb/libreloc/ld.so, for GNU/Linux 3.2.0, BuildID[sha1]=186045664da749e2c77b109834b4e13e8dd60f28, not stripped

mar 26 04:17:26 lati-dbs1 scylla[47108]: Backtrace:
mar 26 04:17:26 lati-dbs1 scylla[47108]:
[Backtrace #0]

void seastar::backtrace<seastar::backtrace_buffer::append_backtrace()::{lambda(seastar::frame)#1}>(seastar::backtrace_buffer::append_backtrace()::{lambda(seastar::frame)#1}&&) at /usr/include/c++/9/ext/new_allocator.h:105
seastar::backtrace_buffer::append_backtrace() at /usr/include/c++/9/ext/new_allocator.h:105
 (inlined by) print_with_backtrace at /jenkins/workspace/scylla-3.2/build/scylla/seastar/src/core/reactor.cc:731
seastar::print_with_backtrace(char const*) at /usr/include/c++/9/ext/new_allocator.h:105
sigsegv_action at /usr/include/c++/9/ext/new_allocator.h:105
 (inlined by) operator() at /jenkins/workspace/scylla-3.2/build/scylla/seastar/src/core/reactor.cc:3390
 (inlined by) _FUN at /jenkins/workspace/scylla-3.2/build/scylla/seastar/src/core/reactor.cc:3386
?? ??:0
db::hints::manager::end_point_hints_manager::sender::send_one_file(seastar::basic_sstring<char, unsigned int, 15u, true> const&) at /jenkins/workspace/scylla-3.2/build/scylla/./concrete_types.hh:194
db::hints::manager::end_point_hints_manager::sender::send_hints_maybe() at /jenkins/workspace/scylla-3.2/build/scylla/./concrete_types.hh:194
operator() at /jenkins/workspace/scylla-3.2/build/scylla/./concrete_types.hh:194
 (inlined by) apply at /jenkins/workspace/scylla-3.2/build/scylla/seastar/include/seastar/core/apply.hh:36
 (inlined by) apply<db::hints::manager::end_point_hints_manager::sender::start()::<lambda()> > at /jenkins/workspace/scylla-3.2/build/scylla/seastar/include/seastar/core/apply.hh:44
 (inlined by) apply_tuple<db::hints::manager::end_point_hints_manager::sender::start()::<lambda()> > at /jenkins/workspace/scylla-3.2/build/scylla/seastar/include/seastar/core/future.hh:1491
 (inlined by) apply<db::hints::manager::end_point_hints_manager::sender::start()::<lambda()> > at /jenkins/workspace/scylla-3.2/build/scylla/seastar/include/seastar/core/future.hh:1525
 (inlined by) operator() at /jenkins/workspace/scylla-3.2/build/scylla/seastar/include/seastar/core/thread.hh:265
 (inlined by) call at /jenkins/workspace/scylla-3.2/build/scylla/seastar/include/seastar/util/noncopyable_function.hh:99
seastar::noncopyable_function<void ()>::operator()() const at /jenkins/workspace/scylla-3.2/build/scylla/seastar/include/seastar/util/noncopyable_function.hh:182
 (inlined by) seastar::thread_context::main() at /jenkins/workspace/scylla-3.2/build/scylla/seastar/src/core/thread.cc:277
```

I reported similar issue in the past (https://github.com/scylladb/scylla/issues/4843) but it was closed yesterday.

For now I'm disabling hinted handoff in production.

**Comment by haaawk** [comment] 2020-03-26 08:10
Bactrace points to somewhere in [manager::end_point_hints_manager::sender::send_one_file](https://github.com/scylladb/scylla/blob/scylla-3.2.3/db/hints/manager.cc#L736)

This is the most recent change in this method:
```
commit e4b8f52237dee8aa776f3cfb0c1b3f8d7912d306
Author: Rafael Ávila de Espíndola <espindola@scylladb.com>
Date:   Tue Jan 28 09:28:47 2020 -0800

    commitlog: Simplify the return of read_log_file
    
    This function really just wants to signal it is done, so return a
    future<>.
    
    Signed-off-by: Rafael Ávila de Espíndola <espindola@scylladb.com>
    Message-Id: <20200128172847.31513-1-espindola@scylladb.com>

diff --git a/db/hints/manager.cc b/db/hints/manager.cc
index d39ce16c2..bd6659be6 100644
--- a/db/hints/manager.cc
+++ b/db/hints/manager.cc
@@ -744,7 +744,7 @@ bool manager::end_point_hints_manager::sender::send_one_file(const sstring& fnam
     lw_shared_ptr<send_one_file_ctx> ctx_ptr = make_lw_shared<send_one_file_ctx>(_last_schema_ver_to_column_mapping);
 
     try {
-        auto s = commitlog::read_log_file(fname, manager::FILENAME_PREFIX, service::get_local_streaming_read_priority(), [this, secs_since_file_mod, &fname, ctx_ptr] (commitlog::buffer_and_replay_position buf_rp) mutable {
+        commitlog::read_log_file(fname, manager::FILENAME_PREFIX, service::get_local_streaming_read_priority(), [this, secs_since_file_mod, &fname, ctx_ptr] (commitlog::buffer_and_replay_position buf_rp) mutable {
             auto&& [buf, rp] = buf_rp;
             // Check that we can still send the next hint. Don't try to send it if the destination host
             // is DOWN or if we have already failed to send some of the previous hints.
@@ -761,9 +761,7 @@ bool manager::end_point_hints_manager::sender::send_one_file(const sstring& fnam
             return flush_maybe().finally([this, ctx_ptr, buf = std::move(buf), rp, secs_since_file_mod, &fname] () mutable {
                 return send_one_hint(std::move(ctx_ptr), std::move(buf), rp, secs_since_file_mod, fname);
             });
-        }, _last_not_complete_rp.pos, &_db.extensions()).get0();
-
-        s->done().get();
+        }, _last_not_complete_rp.pos, &_db.extensions()).get();
     } catch (db::commitlog::segment_error& ex) {
         manager_logger.error("{}: {}. Dropping...", fname, ex.what());
         ctx_ptr->state.remove(send_state::segment_replay_failed);
```

@espindola could you have a look please?

**Comment by haaawk** [comment] 2020-03-26 08:21
@espindola has removed `s->done().get();` and now it seems we don't wait for commitlog::read_log_file. Here's the full change -> https://github.com/scylladb/scylla/commit/e4b8f52237dee8aa776f3cfb0c1b3f8d7912d306

The change makes commitlog::read_log_file return future<> instead of std::unique_ptr<subscription<buffer_and_replay_position>> but it's still a future and we probably should still wait for it to finish.

**Comment by haaawk** [comment] 2020-03-26 08:32
ok it seems that this change is not even in 3.2.3 after all. Sorry @espindola

**Comment by psarna** [comment] 2020-03-26 08:33
@r4fek do you have a core file to upload and share? It looks like OOM, so it would be helpful to investigate the coredump and see what was the internal memory usage in Scylla.

**Comment by haaawk** [comment] 2020-03-26 08:34
> @r4fek do you have a core file to upload and share? It looks like OOM, so it would be helpful to investigate the coredump and see what was the internal memory usage in Scylla.

The core wasn't created.

**Comment by r4fek** [comment] 2020-03-26 08:35
I don't see any indication of OOM in logs (dmesg).

**Comment by psarna** [comment] 2020-03-26 08:53
@r4fek I mean internal Scylla out-of-memory - since I see that both issues mention `std::bad_alloc` happening multiple times before the failure. It seems that there may be a problem with hinted handoff when memory is scarce, but I don't have a clear idea what's wrong yet.

**Comment by espindola** [comment] 2020-03-26 16:05
> Bactrace points to somewhere in [manager::end_point_hints_manager::sender::send_one_file](https://github.com/scylladb/scylla/blob/scylla-3.2.3/db/hints/manager.cc#L736)
> 
> This is the most recent change in this function:
> 
> ```
> commit e4b8f52237dee8aa776f3cfb0c1b3f8d7912d306
> Author: Rafael Ávila de Espíndola <espindola@scylladb.com>
> Date:   Tue Jan 28 09:28:47 2020 -0800

That change is on master, the issue is on 3.2.3, which as far as I can tell doesn't include that patch. Am I missing something?

**Comment by haaawk** [comment] 2020-03-26 16:08
> > Bactrace points to somewhere in [manager::end_point_hints_manager::sender::send_one_file](https://github.com/scylladb/scylla/blob/scylla-3.2.3/db/hints/manager.cc#L736)
> > This is the most recent change in this function:
> > ```
> > commit e4b8f52237dee8aa776f3cfb0c1b3f8d7912d306
> > Author: Rafael Ávila de Espíndola <espindola@scylladb.com>
> > Date:   Tue Jan 28 09:28:47 2020 -0800
> > ```
> 
> That change is on master, the issue is on 3.2.3, which as far as I can tell doesn't include that patch. Am I missing something?

Yes. See my other comment -> https://github.com/scylladb/scylla/issues/6086#issuecomment-604297690

**Comment by bhalevy** [comment] 2020-03-26 18:34
Duplicate of https://github.com/scylladb/scylla/issues/4728?

**Comment by slivne** [comment] 2020-04-15 21:30
@haaawk / @piodul was this fixed ?

**Comment by haaawk** [comment] 2020-04-16 05:01
Not sure. @piodul?

**Comment by piodul** [comment] 2020-04-16 07:26
@slivne @haaawk No, it's not fixed.

I don't know yet what is the root cause of the segfault. I did not have any luck in reproducing it yet.
It's hard to conclude what is the root cause from the backtrace alone, because the assembly from the function that segfaulted is highly inlined and hard to read.

**Comment by haaawk** [comment] 2020-05-05 13:41
It seems that the problem was in commitlog and seastar/stream.hh.
`subscription` was keeping a [raw pointer](https://github.com/scylladb/seastar/blob/seastar-19.06.0/include/seastar/core/stream.hh#L107) to a `stream` and it was unconditionally used in [`subscription::done()`](https://github.com/scylladb/seastar/blob/seastar-19.06.0/include/seastar/core/stream.hh#L236) but between the creation of `subscription` and the call to `subscription::done()` the `stream` can be destroyed and that [will null out](https://github.com/scylladb/seastar/blob/seastar-19.06.0/include/seastar/core/stream.hh#L132) the pointer in `subscription`.
Creation of `subscription` in commitlog -> https://github.com/scylladb/scylla/blob/scylla-3.2.3/db/commitlog/commitlog.cc#L2089
Call two `subscription::done()` in hinted-handoff manager -> https://github.com/scylladb/scylla/blob/scylla-3.2.3/db/hints/manager.cc#L761
Place when `stream` is destroyed -> https://github.com/scylladb/scylla/blob/scylla-3.2.3/db/commitlog/commitlog.cc#L2096
If `read_file` fails fast with an exception (like bad_alloc), the `stream` can be destroyed before `subscription::done()` is called. We (@piodul and I) reproduced the problem by returning an exceptional future from read_file.

The problem was fixed by @espindola  in seastar in here by moving `_done` future from `stream` to `subscription` which means no more going through a pointer to a `stream`-> https://github.com/scylladb/seastar/commit/a9827df9613ac941c298d9a97bd14fa8dd4b5c80#diff-485645ee4da6cbdb17d9c77f05fe540a

There was also a related issue of subscription lifetime fixed by @elcallio -> https://github.com/scylladb/scylla/issues/6265

On master, everything works fine. When we inject exception we see error logs but the database keeps working as expected.

**Closed by haaawk** 2020-05-05 13:41 UTC
Labels: User Request, bug, hinted-handoff, stability

**Comment by haaawk** [comment] 2020-05-05 13:47
@slivne Do we want to backport those fixes? They seem to be quite small so it might be worth backporting to 3.2.3. Definitely to 3.3 in my opinion.

**Comment by slivne** [comment] 2020-05-05 13:55
3.2 is going to be EOL soon - so I guess not.

4.0 is about to go out and those fixes are not part of it

4.0 is missing Calle's fix (it does have espindola's fix).

**Comment by avikivity** [comment] 2020-11-29 13:01
No patch attached to the issue, removing backport candidate label. @haaawk please advise if something does need a backport.
