### ISSUE TITLE
Scylla starts even though scylla_io_setup has not been run

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylla#1091] opened 2016-03-24 15:24 UTC
## Installation details
Scylla version (or git commit hash): 1.0-rc1
Cluster size: 1
OS (RHEL/CentOS/Ubuntu/AWS AMI): Ubuntu

Scylla starts even though scylla_io_setup has not been run.

**Comment by slivne** [comment] 2016-03-24 19:37
@avikivity  is there additional info on how to reproduce ? or any ubuntu 14.04 (with kernel upgraded) without --developer-mode set will reproduce this ?

**Comment by syuu1228** [comment] 2016-03-25 10:39
@avikivity @slivne After implemented https://github.com/scylladb/scylla/issues/1065, we able to run scylla without running iotune.
Should we prevent it? I think it can be implement on scylla_prepare.

**Comment by syuu1228** [comment] 2016-03-25 11:28
Seems https://github.com/scylladb/scylla/commit/e750a943000716939bba71c565414eed8b917c68 solve  the problem?

**Comment by syuu1228** [comment] 2016-04-04 20:00
Please close this, since latest master can cause error when io parameters not assigned.

**Closed** 2016-04-08 08:28 UTC
Labels: bug, high, onboarding
