### ISSUE TITLE
Fully support streaming mutation fragments in reversed order

### ISSUE THREAD

**Issue by pdziepak** [scylladb/scylla#1413] opened 2016-06-30 10:19 UTC
Currently, if there is a query that asks for clustering rows in reversed order streamed mutations are rebuilt and then streamed again in reversed order in `consume_flattened()`. This is wasteful, since it requires reading all rows in the specified range regardless of the row limit.

The solution is to make all producers able to stream mutation fragments in the reversed order. This may also require intermediate stages like `merge_mutations()` support that.

**Comment by slivne** [comment] 2016-11-06 11:03
lets test what happens on a large partition - will we run out of memory / timeout in such queries ?

**Comment by tgrabiec** [comment] 2016-11-07 12:10
@slivne The effects will vary depending on partition size, number of rows actually returned in the query, current concurrency in the system. Can lead to poor performance, cache eviction, OOM. The issue is that memory overhead is O(partition size) instead of O(1), and computational overhead is O(partition size) instead of O(query result size).

**Comment by avikivity** [comment] 2017-11-16 11:03
With the current file format, we can improve things, but it will always remain O(partition size). We will just experience the problems on larger partitions.

A new file format should consider reverse iteration as a requirement (not hard with a btree).

**Comment by ehsannm** [comment] 2020-11-10 06:40
We hit this problem in production too, do you have an ETA to fix this issue ? Creating another MV just for reverse order is wasteful in our case :(.

**Comment by avikivity** [comment] 2020-11-10 08:08
> With the current file format, we can improve things, but it will always remain O(partition size). We will just experience the problems on larger partitions.
> 
> A new file format should consider reverse iteration as a requirement (not hard with a btree).

mx format can support more efficient reverse scans. See the `prev_unfiltered_size` field. We'll likely also need a page cache since the input is no longer a byte stream.

**Comment by dorlaor** [comment] 2021-06-22 00:51
For the record, we had another request for it just now. @slivne

**Comment by haaawk** [comment] 2021-06-22 07:34
There's an intern starting July who will be working on this.

**Comment by bhalevy** [comment] 2021-08-03 10:09
(Moving the verbiage from #9130 here before closing it)

This is an umbrella issue for improving reverse queries efficiency.

# Introduction
CQL supports the notion of reversed queries. These are queries where the clustering key ORDER BY clause specifies an order that is reversed to the one specified in the table creation clause.

Currently, Scylla supports reversed queries very inefficiently. It reads the entire data set requested (ignoring paging), reverses it in memory, and emits the first page. This can consume large amounts of memory, and if multiple pages are required, has quadratic performance in the number of pages.

The sstable format and cache/memtable data structures have everything needed for efficient reverse traversal, so it’s just a matter of wiring it.

# Motivation, goals and non-goals
## Motivation
Customers having reverse queries with a large datasets.
## Goals
- O(page) memory use
- Non-quadratic performance
- No reactor stalls
## Non-Goals
- Match the performance of forward queries
- Multi-partition reverse scans

Changes are planned in the following areas:
1. SSTable reader (Note: we probably only need to implement single-partition reversed reads.)
2. Other flat_mutation_readers
3. Cache
4. Memtable
5. Front-end

See [Supporting reversed queries efficiently](https://docs.google.com/document/d/192XATwnsv_VHc76AsEZmVkMgVh0I33OzYCFn3LQDT5o/edit) for more details.

Subordinate issues will be opened per-area/isolated task.

**Comment by avikivity** [comment] 2022-02-20 12:13
I think this is done. @haaawk is there anything remaining?

**Comment by haaawk** [comment] 2022-02-21 08:59
No. Everything should be there already.

**Closed by haaawk** 2022-02-21 08:59 UTC
Labels: performance, large partitions, bad_alloc
