### ISSUE TITLE
Scylla failed to start: Startup failed: std::runtime_error (Exception while populating keyspace 'system_distributed' with column family 'cdc_streams_descriptions_v2'

### ISSUE THREAD

**Issue by aleksbykov** [scylladb/scylla#10143] opened 2022-02-28 12:33 UTC
*Installation details*
Kernel version: `5.11.0-1028-aws`
Scylla version (or git commit hash): `5.1.dev-0.20220225.680195564de7 with build-id ddb50a4cec4995f08be48bff703067d207209192`
Cluster size: 5 nodes (i3.2xlarge)
Scylla running with shards number (live nodes):
   longevity-large-partitions-3h-maste-db-node-437af8b9-1 (54.154.152.82 | 10.0.3.247): 7 shards
   longevity-large-partitions-3h-maste-db-node-437af8b9-2 (52.213.168.184 | 10.0.0.132): 4 shards
   longevity-large-partitions-3h-maste-db-node-437af8b9-3 (34.248.102.250 | 10.0.0.38): 5 shards
   longevity-large-partitions-3h-maste-db-node-437af8b9-4 (3.248.196.249 | 10.0.0.69): 7 shards
   longevity-large-partitions-3h-maste-db-node-437af8b9-7 (52.48.213.30 | 10.0.0.201): 6 shards
Scylla running with shards number (terminated nodes):
   longevity-large-partitions-3h-maste-db-node-437af8b9-6 (34.241.156.143 | 10.0.3.83): 7 shards
   longevity-large-partitions-3h-maste-db-node-437af8b9-5 (54.246.186.126 | 10.0.0.64): 6 shards
OS (RHEL/CentOS/Ubuntu/AWS AMI): `ami-068c5f920fa103552` (aws: eu-west-1)

Test: `longevity-large-partition-asymmetric-cluster-3h`
Test name: `longevity_large_partition_test.LargePartitionLongevityTest.test_large_partition_longevity`
Test config file(s):
- [longevity-large-partition-3h.yaml]([https://github.com/scylladb/scylla-cluster-tests/blob/69afe9561bf2be30175f2fa598fd64d7aef6d3fb/test-cases/longevity/longevity-large-partition-3h.yaml](https://www.google.com/url?q=https://github.com/scylladb/scylla-cluster-tests/blob/69afe9561bf2be30175f2fa598fd64d7aef6d3fb/test-cases/longevity/longevity-large-partition-3h.yaml&source=gmail-html&ust=1646137045438000&usg=AOvVaw3MdZcZoEeCxdrLXveGKr9M))
- [db-nodes-shards-random.yaml]([https://github.com/scylladb/scylla-cluster-tests/blob/2926d94990e9b7c2aa8ad098c1685cf4a2a26543/configurations/db-nodes-shards-random.yaml](https://www.google.com/url?q=https://github.com/scylladb/scylla-cluster-tests/blob/2926d94990e9b7c2aa8ad098c1685cf4a2a26543/configurations/db-nodes-shards-random.yaml&source=gmail-html&ust=1646137045438000&usg=AOvVaw0nTAYl7Z1pmXxLO6WVv-93))

**Issue description**

====================================
Latest nemesis 'DestroyDataThenRebuild' stop scylla, then destroy several files for tables and then start scylla and run rebuild.
After that start scylla and rebuild

after files were removed:
```
2022-02-27T06:26:53+00:00 longevity-large-partitions-3h-maste-db-node-437af8b9-7 !  NOTICE | scyllaadm : TTY=unknown ; PWD=/home/scyllaadm ; USER=root ; COMMAND=/usr/bin/rm -f /var/lib/scylla/data/keyspace_new_dc/standard1-b1248920978c11ec973d0cb4f508f858/me-2723-big-CompressionInfo.db /var/lib/scylla/data/keyspace_new_dc/standard1-b1248920978c11ec973d0cb4f508f858/me-2723-big-Data.db /var/lib/scylla/data/keyspace_new_dc/standard1-b1248920978c11ec973d0cb4f508f858/me-2723-big-Digest.crc32 /var/lib/scylla/data/keyspace_new_dc/standard1-b1248920978c11ec973d0cb4f508f858/me-2723-big-Filter.db /var/lib/scylla/data/keyspace_new_dc/standard1-b1248920978c11ec973d0cb4f508f858/me-2723-big-Index.db /var/lib/scylla/data/keyspace_new_dc/standard1-b1248920978c11ec973d0cb4f508f858/me-2723-big-Scylla.db /var/lib/scylla/data/keyspace_new_dc/standard1-b1248920978c11ec973d0cb4f508f858/me-2723-big-Statistics.db /var/lib/scylla/data/keyspace_new_dc/standard1-b1248920978c11ec973d0cb4f508f858/me-2723-big-Summary.db
2022-02-27T06:26:53+00:00 longevity-large-partitions-3h-maste-db-node-437af8b9-7 !  NOTICE | scyllaadm : (command continued) /var/lib/scylla/data/keyspace_new_dc/standard1-b1248920978c11ec973d0cb4f508f858/me-2723-big-TOC.txt
```
scylla was going to be started, but next errors cause start failing.
```
2022-02-27T06:26:55+00:00 longevity-large-partitions-3h-maste-db-node-437af8b9-7 !    INFO |  [shard 0] database - Populating Keyspace scylla_bench
2022-02-27T06:26:55+00:00 longevity-large-partitions-3h-maste-db-node-437af8b9-7 !    INFO |  [shard 0] database - Keyspace scylla_bench: Reading CF test_counters id=62f36ef0-9788-11ec-929f-0cb8f508f858 version=a0ccfd87-454b-34ff-9d5d-49cc14c20731
2022-02-27T06:26:55+00:00 longevity-large-partitions-3h-maste-db-node-437af8b9-7 !    INFO |  [shard 0] database - Keyspace scylla_bench: Reading CF test id=52bb0f20-9788-11ec-9ee3-0138628db47f version=48cca53d-10af-3569-b7f1-f8a6b53c9d9a
2022-02-27T06:26:55+00:00 longevity-large-partitions-3h-maste-db-node-437af8b9-7 !    INFO |  [shard 0] database - Populating Keyspace keyspace_new_dc
2022-02-27T06:26:55+00:00 longevity-large-partitions-3h-maste-db-node-437af8b9-7 !    INFO |  [shard 0] database - Keyspace keyspace_new_dc: Reading CF standard1 id=b1248920-978c-11ec-973d-0cb4f508f858 version=6fbff01a-ee4f-3c58-a016-6d6b75c8124a
2022-02-27T06:26:55+00:00 longevity-large-partitions-3h-maste-db-node-437af8b9-7 !     ERR |  [shard 0] database - Exception while populating keyspace 'system_auth' with column family 'roles' from file '/var/lib/scylla/data/system_auth/roles-5bc52802de2535edaeab188eecebb090': std::runtime_error (Refusing to load a foreign SSTable: host id mismatch. Load foreign SSTables via the upload dir instead.)
2022-02-27T06:26:55+00:00 longevity-large-partitions-3h-maste-db-node-437af8b9-7 !     ERR |  [shard 0] database - Exception while populating keyspace 'system_distributed' with column family 'cdc_streams_descriptions_v2' from file '/var/lib/scylla/data/system_distributed/cdc_streams_descriptions_v2-0bf73fd765b236b085e5658131d5df36': std::runtime_error (Refusing to load a foreign SSTable: host id mismatch. Load foreign SSTables via the upload dir instead.)
2022-02-27T06:26:55+00:00 longevity-large-partitions-3h-maste-db-node-437af8b9-7 !     ERR |  [shard 0] database - Exception while populating keyspace 'keyspace_new_dc' with column family 'standard1' from file '/var/lib/scylla/data/keyspace_new_dc/standard1-b1248920978c11ec973d0cb4f508f858': std::runtime_error (Refusing to load a foreign SSTable: host id mismatch. Load foreign SSTables via the upload dir instead.)
2022-02-27T06:26:55+00:00 longevity-large-partitions-3h-maste-db-node-437af8b9-7 !     ERR |  [shard 0] database - Exception while populating keyspace 'scylla_bench' with column family 'test' from file '/var/lib/scylla/data/scylla_bench/test-52bb0f20978811ec9ee30138628db47f': std::runtime_error (Refusing to load a foreign SSTable: host id mismatch. Load foreign SSTables via the upload dir instead.)
2022-02-27T06:26:55+00:00 longevity-large-partitions-3h-maste-db-node-437af8b9-7 !     ERR |  [shard 0] database - Exception while populating keyspace 'system_distributed_everywhere' with column family 'cdc_generation_descriptions_v2' from file '/var/lib/scylla/data/system_distributed_everywhere/cdc_generation_descriptions_v2-234d2227dd633d37ac5fc013e2ea9e6e': std::runtime_error (Refusing to load a foreign SSTable: host id mismatch. Load foreign SSTables via the upload dir instead.)


2022-02-27T06:26:55+00:00 longevity-large-partitions-3h-maste-db-node-437af8b9-7 !     ERR |  [shard 0] init - Startup failed: std::runtime_error (Exception while populating keyspace 'system_distributed' with column family 'cdc_streams_descriptions_v2' from file '/var/lib/scylla/data/system_distributed/cdc_streams_descriptions_v2-0bf73fd765b236b085e5658131d5df36': std::runtime_error (Refusing to load a foreign SSTable: host id mismatch. Load foreign SSTables via the upload dir instead.))
```

CDC wasn't enabled on any table.

====================================

Restore Monitor Stack command: `$ hydra investigate show-monitor 437af8b9-2e67-4f14-8b68-38a30e77f82f`
Restore monitor on AWS instance using [Jenkins job]([https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?sct_branch=master&test_id=437af8b9-2e67-4f14-8b68-38a30e77f82f](https://www.google.com/url?q=https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?sct_branch%3Dmaster%26test_id%3D437af8b9-2e67-4f14-8b68-38a30e77f82f&source=gmail-html&ust=1646137045438000&usg=AOvVaw2XOJyWPrc6qYCJNaRdI_rO))
Show all stored logs command: `$ hydra investigate show-logs 437af8b9-2e67-4f14-8b68-38a30e77f82f`

Test id: `437af8b9-2e67-4f14-8b68-38a30e77f82f`

Logs:
grafana - [[https://cloudius-jenkins-test.s3.amazonaws.com/437af8b9-2e67-4f14-8b68-38a30e77f82f/20220227_063656/grafana-screenshot-longevity-large-partition-asymmetric-cluster-3h-scylla-per-server-metrics-nemesis-20220227_063841-longevity-large-partitions-3h-maste-monitor-node-437af8b9-1.png](https://cloudius-jenkins-test.s3.amazonaws.com/437af8b9-2e67-4f14-8b68-38a30e77f82f/20220227_063656/grafana-screenshot-longevity-large-partition-asymmetric-cluster-3h-scylla-per-server-metrics-nemesis-20220227_063841-longevity-large-partitions-3h-maste-monitor-node-437af8b9-1.png)](https://www.google.com/url?q=https://cloudius-jenkins-test.s3.amazonaws.com/437af8b9-2e67-4f14-8b68-38a30e77f82f/20220227_063656/grafana-screenshot-longevity-large-partition-asymmetric-cluster-3h-scylla-per-server-metrics-nemesis-20220227_063841-longevity-large-partitions-3h-maste-monitor-node-437af8b9-1.png%255D(https://cloudius-jenkins-test.s3.amazonaws.com/437af8b9-2e67-4f14-8b68-38a30e77f82f/20220227_063656/grafana-screenshot-longevity-large-partition-asymmetric-cluster-3h-scylla-per-server-metrics-nemesis-20220227_063841-longevity-large-partitions-3h-maste-monitor-node-437af8b9-1.png)&source=gmail-html&ust=1646137045438000&usg=AOvVaw0JtxvdldMuwmYgMGQRekbg)
grafana - [[https://cloudius-jenkins-test.s3.amazonaws.com/437af8b9-2e67-4f14-8b68-38a30e77f82f/20220227_063656/grafana-screenshot-overview-20220227_063657-longevity-large-partitions-3h-maste-monitor-node-437af8b9-1.png](https://cloudius-jenkins-test.s3.amazonaws.com/437af8b9-2e67-4f14-8b68-38a30e77f82f/20220227_063656/grafana-screenshot-overview-20220227_063657-longevity-large-partitions-3h-maste-monitor-node-437af8b9-1.png)](https://www.google.com/url?q=https://cloudius-jenkins-test.s3.amazonaws.com/437af8b9-2e67-4f14-8b68-38a30e77f82f/20220227_063656/grafana-screenshot-overview-20220227_063657-longevity-large-partitions-3h-maste-monitor-node-437af8b9-1.png%255D(https://cloudius-jenkins-test.s3.amazonaws.com/437af8b9-2e67-4f14-8b68-38a30e77f82f/20220227_063656/grafana-screenshot-overview-20220227_063657-longevity-large-partitions-3h-maste-monitor-node-437af8b9-1.png)&source=gmail-html&ust=1646137045438000&usg=AOvVaw01IB1aHgZ6cTeQUuxasD9H)
db-cluster - [[https://cloudius-jenkins-test.s3.amazonaws.com/437af8b9-2e67-4f14-8b68-38a30e77f82f/20220227_065032/db-cluster-437af8b9.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/437af8b9-2e67-4f14-8b68-38a30e77f82f/20220227_065032/db-cluster-437af8b9.tar.gz)](https://www.google.com/url?q=https://cloudius-jenkins-test.s3.amazonaws.com/437af8b9-2e67-4f14-8b68-38a30e77f82f/20220227_065032/db-cluster-437af8b9.tar.gz%255D(https://cloudius-jenkins-test.s3.amazonaws.com/437af8b9-2e67-4f14-8b68-38a30e77f82f/20220227_065032/db-cluster-437af8b9.tar.gz)&source=gmail-html&ust=1646137045438000&usg=AOvVaw2sLIny912qI9saOgHOIBrx)
loader-set - [[https://cloudius-jenkins-test.s3.amazonaws.com/437af8b9-2e67-4f14-8b68-38a30e77f82f/20220227_065032/loader-set-437af8b9.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/437af8b9-2e67-4f14-8b68-38a30e77f82f/20220227_065032/loader-set-437af8b9.tar.gz)](https://www.google.com/url?q=https://cloudius-jenkins-test.s3.amazonaws.com/437af8b9-2e67-4f14-8b68-38a30e77f82f/20220227_065032/loader-set-437af8b9.tar.gz%255D(https://cloudius-jenkins-test.s3.amazonaws.com/437af8b9-2e67-4f14-8b68-38a30e77f82f/20220227_065032/loader-set-437af8b9.tar.gz)&source=gmail-html&ust=1646137045438000&usg=AOvVaw1_xVydZBMH0ajU_ssJcbj7)
monitor-set - [[https://cloudius-jenkins-test.s3.amazonaws.com/437af8b9-2e67-4f14-8b68-38a30e77f82f/20220227_065032/monitor-set-437af8b9.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/437af8b9-2e67-4f14-8b68-38a30e77f82f/20220227_065032/monitor-set-437af8b9.tar.gz)](https://www.google.com/url?q=https://cloudius-jenkins-test.s3.amazonaws.com/437af8b9-2e67-4f14-8b68-38a30e77f82f/20220227_065032/monitor-set-437af8b9.tar.gz%255D(https://cloudius-jenkins-test.s3.amazonaws.com/437af8b9-2e67-4f14-8b68-38a30e77f82f/20220227_065032/monitor-set-437af8b9.tar.gz)&source=gmail-html&ust=1646137045438000&usg=AOvVaw2kP4rppm2jH7PscOCELLMu)
sct - [[https://cloudius-jenkins-test.s3.amazonaws.com/437af8b9-2e67-4f14-8b68-38a30e77f82f/20220227_065032/sct-runner-437af8b9.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/437af8b9-2e67-4f14-8b68-38a30e77f82f/20220227_065032/sct-runner-437af8b9.tar.gz)](https://www.google.com/url?q=https://cloudius-jenkins-test.s3.amazonaws.com/437af8b9-2e67-4f14-8b68-38a30e77f82f/20220227_065032/sct-runner-437af8b9.tar.gz%255D(https://cloudius-jenkins-test.s3.amazonaws.com/437af8b9-2e67-4f14-8b68-38a30e77f82f/20220227_065032/sct-runner-437af8b9.tar.gz)&source=gmail-html&ust=1646137045439000&usg=AOvVaw2J8sLSM0NfZL5IMnNMrbRJ)

[Jenkins job URL]([https://jenkins.scylladb.com/job/scylla-master/job/longevity/job/longevity-large-partition-asymmetric-cluster-3h/63/](https://www.google.com/url?q=https://jenkins.scylladb.com/job/scylla-master/job/longevity/job/longevity-large-partition-asymmetric-cluster-3h/63/&source=gmail-html&ust=1646137045439000&usg=AOvVaw0Q9T0MvL1CenKReZ1jZfUr))

**Comment by kbr-** [comment] 2022-03-07 10:28
@cmm since you made a great presentation about the new sstable format, now you're gonna face the consequences (i.e.  people start asking questions) :P

Apparently this test removed a bunch of sstables, and when it tried to restart Scylla, the process threw a bunch of "SStable host id mismatch" exceptions.

If I understand correctly, this means that some system.local sstable which stored the host ID was removed, Scylla regenerated it on restart, and then when it tried to load its old sstables, it failed.

So the way to fix that would be:
1. change the test so it doesn't remove the sstable storing the host ID,
2. or, if the test removes this sstable, then move all other sstables to upload/ subdirectories of their corresponding directories before restarting

On the other hand, during the presentation you said that for now we only warn if the host ID mismatches, we don't abort. But here we clearly see that the node aborted startup. Is that a bug?

What do you think?

**Comment by cmm** [comment] 2022-03-07 10:47
@kbr- the patch that changes the exception to warning was merged last Thursday, so this issue seems to predate it

**Comment by kbr-** [comment] 2022-03-07 11:08
> @kbr- the patch that changes the exception to warning was merged last Thursday, so this issue seems to predate it

Ok, thanks! @aleksbykov can you check if the abort is still reproducing?

I'm still wondering though, what the long term fix should be (do we want to allow host ID mismatch in the end?)

**Comment by cmm** [comment] 2022-03-07 11:19
> I'm still wondering though, what the long term fix should be (do we want to allow host ID mismatch in the end?)

(it feels like I discover a new interesting host-ID-related behavior every day, probably because I do)
that is indeed the question.  I evidently lack the big picture view here, hopefully @bhalevy and/or @slivne have one

**Comment by aleksbykov** [comment] 2022-03-16 10:51
Issue was not reproduced with latest master

**Comment by kbr-** [comment] 2022-03-16 10:53
In that case I'm closing it. Please repoen if it reproduces.

**Closed by kbr-** 2022-03-16 10:53 UTC
Labels: bug, high, CDC
