### ISSUE TITLE
Consider compacting partition on the fly

### ISSUE THREAD

**Issue by duarten** [scylladb/scylla#2208] opened 2017-03-23 14:06 UTC
*Installation details*
Scylla version (or git commit hash): master

To decrease partition size in memory, we should consider compacting it on the fly, namely, using the current tombstones to remove dead cells.

**Comment by tgrabiec** [comment] 2017-03-23 14:29
Duplicate of https://github.com/scylladb/scylla/issues/652 ?

**Comment by duarten** [comment] 2017-03-23 14:42
Dang, I have to get better at searching for issues before creating them.

**Closed** 2017-03-23 14:42 UTC
