### ISSUE TITLE
Scylla failed to restart: Exiting on unhandled exception: exceptions::read_timeout_exception

### ISSUE THREAD

**Issue by zhiguoxu** [scylladb/scylla#3043] opened 2017-12-03 09:17 UTC
*Installation details*
Scylla version (or git commit hash): 1.6.4
Cluster size: 8
OS (RHEL/CentOS/Ubuntu/AWS AMI): CentOS 7.3

*Hardware details (for performance issues)*
Platform physical
Hardware: sockets=2 cores=20 hyperthreading=2 memory=100G
Disks: SSD

Scylla failed to restart, yielding an timeout exception when reading the system.peers. Is this the old version（1.6.4）problem？

[shard 0] seastar - Exiting on unhandled exception: exceptions::read_timeout_exception (Operation timed out for system.peers - received only 0 responses from 1 CL=ONE.

**Comment by gleb-cloudius** [comment] 2017-12-03 09:20
On Sun, Dec 03, 2017 at 09:17:25AM +0000, zhiguoxu wrote:
> [shard 0] seastar - Exiting on unhandled exception: exceptions::read_timeout_exception (Operation timed out for system.peers - received only 0 responses from 1 CL=ONE.
> 
Can you provide entire log from restart till the error.

--
			Gleb.

**Comment by slivne** [comment] 2018-01-25 10:25
closing the issue - @zhiguoxu  if there is additional info please post and we can reopen

**Closed by slivne** 2018-01-25 10:25 UTC

**Comment by nyh** [comment] 2018-07-16 12:03
For future searchers, I want to point out that this was a duplicate of #2462.
