### ISSUE TITLE
Scylla startup Script.

### ISSUE THREAD

**Issue by Saikumarn78** [scylladb/scylla#5469] opened 2019-12-12 12:11 UTC
Hi,

Can we have a feature, to control the Scylla service script? 

How do control or tell Scylla not to start its service if it down for a given threshold time? Assume that a node is removed from the cluster as the node is not reachable and at some point of time the node would be rebooted to make it functional and during this period all the configurations are intact with Scylla the node would join back into the cluster :-) and we need to have a control on the startup script to control.

**Comment by Saikumarn78** [comment] 2019-12-12 12:20
I am uploading the service script wapper I made for Cassandra and it can handle the seed bootstrap too.

**Comment by Saikumarn78** [comment] 2019-12-12 12:24
[cassandra.gz](https://github.com/scylladb/scylla/files/3955679/cassandra.gz)

**Comment by tarzanek** [comment] 2019-12-12 14:52
it would make sense to add something like this service - to stop booting scylla automatically if it was down for > X hours (e.g. a day?) - so if HW failure occurs

(so add it to https://github.com/scylladb/scylla/tree/master/dist/common ?)

**Comment by avikivity** [comment] 2019-12-15 14:11
You can use `systemctl disable scylla-server` to disable automatic startup.

**Comment by tarzanek** [comment] 2019-12-16 11:53
I think the problem here is disconnect of dev/deploy teams and day to day devops teams
@Saikumarn78 lacks ssh to the deployed boxes once they are out in the wild, so you still want to have them start scylla when restarted e.g. for security patching, etc. , but you don't want the node join automatically if it goes down for few days of hw maintainance and it will be replaced by another node ... so having control of good behaviour even without having ssh is the goal here

the other option is if you go and remove node we would blacklist it so that IP would never be able to join ...

**Comment by dyasny** [comment] 2020-01-23 16:43
Added an RFE for systemd to support this sort of thing natively, please feel free to +1 it https://github.com/systemd/systemd/issues/14644

**Comment by vladzcloudius** [comment] 2020-02-22 00:23
> I think the problem here is disconnect of dev/deploy teams and day to day devops teams
> @Saikumarn78 lacks ssh to the deployed boxes once they are out in the wild, so you still want to have them start scylla when restarted e.g. for security patching, etc. , but you don't want the node join automatically if it goes down for few days of hw maintainance and it will be replaced by another node ... so having control of good behaviour even without having ssh is the goal here
> 
> the other option is if you go and remove node we would blacklist it so that IP would never be able to join ...

@dyasny I agree with @avikivity - the root cause of this issue is Scylla auto-starting itself and as such we should eliminate the root cause.

There are a lot of reasons NOT `enable` scylla-server service: what if the disk crashed, kernel panicked and machine restarted? 
It's likely that node will try to join exactly as described in the issue description.

IMO, our default systemd service configuration (including on AMI) should be `disabled` - this simply makes much more sense in the field.

@tzach  What do you think?

@dyasny As for the "security patching example": if there is a security patching then this means that there IS some communication with the box.

I can't imagine how DevOp could leave the box inaccessible after deployment.

**Comment by tarzanek** [comment] 2020-02-22 08:02
Well that's the dilemma , let the service auto start (for any security patching), or leave it disabled and require manual or semi-automatic (some "smart" script) to start it after some sanity check

**Comment by vladzcloudius** [comment] 2020-02-24 19:34
> Well that's the dilemma , let the service auto start (for any security patching), or leave it disabled and require manual or semi-automatic (some "smart" script) to start it after some sanity check

If it's about having an extra line in the patching script vs the possibility of creating a havoc in the cluster than I think it's pretty obvious what's preferable.

**Comment by eliransin** [comment] 2021-05-04 13:47
@vladzcloudius, @tarzanek  reading this issue, I see that the only open question remains is if @tzach agrees to change our production images to have scylla disabled by default, right?
What other loose ends are there it this issue?

**Comment by tarzanek** [comment] 2021-05-05 10:32
nope, it's about having different behaviours for start of service based on certain conditions
I think the fix for this lies in systemd lands (e.g. a verify/sanity script that will have logic if to allow service to start upon boot of node or not)

**Comment by eliransin** [comment] 2021-05-25 11:18
After reading https://www.freedesktop.org/software/systemd/man/systemd.service.html I believe that it is pretty easy to change the 
Scylla unit to start or not start conditionally. Specifically https://www.freedesktop.org/software/systemd/man/systemd.service.html#ExecCondition=
@Saikumarn78 have you looked into this option? (and in general the options provided by systemd)

**Comment by dyasny** [comment] 2021-05-25 15:17
@eliransin I checked these options and we worked a solution out, but I really wish https://github.com/systemd/systemd/issues/14644 was addressed

**Comment by eliransin** [comment] 2021-05-26 08:42
@dyasny maybe I failed to understand but the means to achieve this are already in systemd.
Specifically they have:
1. https://www.freedesktop.org/software/systemd/man/systemd.service.html#ExecStopPost= - which can record when and **how** the process was stopped.
2. https://www.freedesktop.org/software/systemd/man/systemd.service.html#ExecCondition= - to evaluate what you just asked for
3. and unit type `notify` which can (with a one liner Scylla change) ,  https://www.freedesktop.org/software/systemd/man/systemd.service.html#ExecStartPre= with emphasis on ExecStartPost to record the last time Scylla was successfully started.

This will leave only the corner case of a complete system crash or systemd crash which can be identified by the presence of a startup time without the presence of a termination time.

Why is it so important to have it as a specific feature? (IMHO it sounds too specific to be implemented as part of systemd)

**Comment by dyasny** [comment] 2021-05-26 13:40
I don't remember the exact details, and we did indeed find a workaround, but it wasn't an elegant solution. 

The fact that systemd's maintainer accepted the RFE pretty much shows it makes sense and isn't present in the current implementation. 

How you go about getting it resolved is up to you of course :)

**Comment by eliransin** [comment] 2021-05-27 13:09
As @dyasny mentioned, a solution was figured out using the existing systemd mechanisms. At best this should be handled further at the systemd level through  systemd/systemd#14644. Besides this, I believe that the feature list I enumerated in https://github.com/scylladb/scylla/issues/5469#issuecomment-848585550 and some very basic scripting are enough to implement this functionality and some more elaborate functionalities if needed. I also validated and Scylla is already a unit of type `notify` and that it actually notifies it's readiness. So the one-liner change I mentioned in bullet 3 in https://github.com/scylladb/scylla/issues/5469#issuecomment-848585550 is not needed. What all of this means is that all of the changes should be done only in scylla's service file (and some auxiliary written scripts).
I believe the issue is resolved from Scylla's side. @Saikumarn78 I am closing the issue as I believe that it is resolved, please feel free to reopen or contact me directly if you think the information provided is wrong,lacking or if you would like some more information about how should the functionality you are after could be implemented.

**Closed by eliransin** 2021-05-27 13:09 UTC
Labels: enhancement
