### ISSUE TITLE
dist: scylla-python3 should be separated repository

### ISSUE THREAD

**Issue by syuu1228** [scylladb/scylla#6751] opened 2020-07-02 15:39 UTC
Except scylla-python3, each scylla package has its own git repository, same package script filename, same build directory structure.
To put python3 thing on scylla repo, we created 'python3' directory on multiple locations, made '-python3' suffixed files, dig deeper build directory not to conflict scylla-server package build.
We should move all scylla-python3 related files to new repository, scylla-python3.
Since we recently added scylla-jmx and scylla-tools as git submodule, we can move scylla-python3 to another submodule, too.

Here's RFC version of scylla-python3 repo, with latest next code:
https://github.com/syuu1228/scylla-python3

After moved it to new repo, we can drop these scripts:
```
[syuu@monster scylla.3]$ git status
On branch next
Your branch is up to date with 'origin/next'.

Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
	deleted:    dist/debian/python3/build_deb.sh
	deleted:    dist/debian/python3/changelog.template
	deleted:    dist/debian/python3/control.template
	deleted:    dist/debian/python3/debian/compat
	deleted:    dist/debian/python3/debian/copyright
	deleted:    dist/debian/python3/debian/rules
	deleted:    dist/debian/python3/debian_files_gen.py
	deleted:    dist/redhat/python3/build_rpm.sh
	deleted:    dist/redhat/python3/python.spec
	deleted:    python3/install.sh
	deleted:    reloc/python3/build_deb.sh
	deleted:    reloc/python3/build_reloc.sh
	deleted:    reloc/python3/build_rpm.sh
	deleted:    scripts/create-relocatable-package-python3.py
```

**Comment by avikivity** [comment] 2020-07-05 15:22
Agree it should be in a separate repository.

**Comment by avikivity** [comment] 2020-07-05 15:23
@syuu1228 please add a LICENSE file (can be Apache 2), and transfer it to my account. I'll transfer it to the scylladb org.

**Comment by syuu1228** [comment] 2020-07-08 13:38
@avikivity Added LICENSE and sent transfer request to you

**Comment by avikivity** [comment] 2020-07-08 14:05
Transferred.

**Comment by avikivity** [comment] 2020-07-17 05:50
The move hasn't been completed.

**Closed** 2020-08-18 18:36 UTC
Labels: Backport candidate

**Comment by avikivity** [comment] 2020-08-27 08:25
Not a bug, not backporting.
