### ISSUE TITLE
NoHostAvailable system_distributed_everywhere.cdc_generation_descriptions_v2

### ISSUE THREAD

**Issue by asias** [scylladb/scylla#8533] opened 2021-04-22 08:19 UTC
Start one node in the clsuter
Do query after the node is up
```
cqlsh> CONSISTENCY ONE 
Consistency level set to ONE.
cqlsh> SELECT  * from system_distributed_everywhere.cdc_generation_descriptions_v2 ;
NoHostAvailable: 
```

Commit:

https://github.com/asias/scylla/tree/cdc_everywhere_v2

**Comment by kbr-** [comment] 2021-04-22 09:23
What build? Some special node config parameters? How is Scylla started? I can't reproduce.

**Comment by asias** [comment] 2021-04-22 10:50
> What build? Some special node config parameters? How is Scylla started? I can't reproduce.

https://github.com/asias/scylla/tree/cdc_everywhere_v2. No special config.

**Comment by kbr-** [comment] 2021-04-22 11:27
I think we can continue on #8536 and close this issue.

**Closed** 2021-04-22 11:44 UTC
