### ISSUE TITLE
Nodetool  toppartitions fails with coredump when runs on table with materialized views

### ISSUE THREAD

**Issue by juliayakovlev** [scylladb/scylla#4893] opened 2019-08-26 11:11 UTC
*Installation details*
Scylla version (or git commit hash): 3.1.0.rc3-0.20190727.bebfd7b26
Cluster size: 3 nodes
OS (RHEL/CentOS/Ubuntu/AWS AMI): ami-0e90f1a90d8bb3a4e

Nodetool  toppartitions fails when runs on materialized view with weird error:

```
[centos@ip-172-30-0-51 ~]$ nodetool  toppartitions mview users_by_last_name 1556 -s 320 -k 19 -a reads
error: org.glassfish.json.JsonLocationImpl
-- StackTrace --
java.io.NotSerializableException: org.glassfish.json.JsonLocationImpl
at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1184)
at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
at java.io.ObjectOutputStream.defaultWriteObject(ObjectOutputStream.java:441)
at java.lang.Throwable.writeObject(Throwable.java:1014)
at sun.reflect.GeneratedMethodAccessor28.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1140)
at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1496)
at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
at java.io.ObjectOutputStream.defaultWriteObject(ObjectOutputStream.java:441)
at java.lang.Throwable.writeObject(Throwable.java:1014)
at sun.reflect.GeneratedMethodAccessor28.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1140)
at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1496)
at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:396)
at sun.rmi.transport.Transport$1.run(Transport.java:200)
at sun.rmi.transport.Transport$1.run(Transport.java:197)
at java.security.AccessController.doPrivileged(Native Method)
at sun.rmi.transport.Transport.serviceCall(Transport.java:196)
at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:573)
at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:834)
at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:688)
at java.security.AccessController.doPrivileged(Native Method)
at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:687)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
```

Segmentation fault on the node:
```
0x0000000004175d22
0x0000000004062fa5
0x00000000040632a5
0x00000000040632f3
0x00007f54ca7a402f
0x00000000023ea161
0x00000000023afe9e
0x00000000023b31d2
0x0000000004060491
0x000000000406068e
0x000000000414235d
0x000000000416c9cb
0x000000000402e78d
/opt/scylladb/bin/../libreloc/libpthread.so.0+0x000000000000858d
/opt/scylladb/bin/../libreloc/libc.so.6+0x00000000000fd6a2
```
Decoded:
```
void seastar::backtrace<seastar::backtrace_buffer::append_backtrace()::{lambda(seastar::frame)#1}>(seastar::backtrace_buffer::append_backtrace()::{lambda(seastar::frame)#1}&&) at /usr/include/boost/program_options/variables_map.hpp:146
seastar::backtrace_buffer::append_backtrace() at /usr/include/boost/program_options/variables_map.hpp:146
 (inlined by) print_with_backtrace at /jenkins/workspace/scylla-3.1/relocatable-pkg/scylla/seastar/build/release/../../src/core/reactor.cc:1104
seastar::print_with_backtrace(char const*) at /usr/include/boost/program_options/variables_map.hpp:146
sigsegv_action at /usr/include/boost/program_options/variables_map.hpp:146
 (inlined by) operator() at /jenkins/workspace/scylla-3.1/relocatable-pkg/scylla/seastar/build/release/../../src/core/reactor.cc:5007
 (inlined by) _FUN at /jenkins/workspace/scylla-3.1/relocatable-pkg/scylla/seastar/build/release/../../src/core/reactor.cc:5003
?? ??:0
std::__detail::_Mod_range_hashing::operator()(unsigned long, unsigned long) const at /jenkins/workspace/scylla-3.1/relocatable-pkg/scylla/seastar/include/seastar/core/future.hh:768
 (inlined by) std::__detail::_Hash_code_base<db::toppartitons_item_key, std::pair<db::toppartitons_item_key const, std::_List_iterator<seastar::lw_shared_ptr<utils::space_saving_top_k<db::toppartitons_item_key, db::toppartitons_item_key::hash, db::toppartitons_item_key::comp>::counter> > >, std::__detail::_Select1st, db::toppartitons_item_key::hash, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, true>::_M_bucket_index(db::toppartitons_item_key const&, unsigned long, unsigned long) const at /usr/include/c++/8/bits/hashtable_policy.h:1392
 (inlined by) std::_Hashtable<db::toppartitons_item_key, std::pair<db::toppartitons_item_key const, std::_List_iterator<seastar::lw_shared_ptr<utils::space_saving_top_k<db::toppartitons_item_key, db::toppartitons_item_key::hash, db::toppartitons_item_key::comp>::counter> > >, std::allocator<std::pair<db::toppartitons_item_key const, std::_List_iterator<seastar::lw_shared_ptr<utils::space_saving_top_k<db::toppartitons_item_key, db::toppartitons_item_key::hash, db::toppartitons_item_key::comp>::counter> > > >, std::__detail::_Select1st, db::toppartitons_item_key::comp, db::toppartitons_item_key::hash, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, false, true> >::_M_bucket_index(db::toppartitons_item_key const&, unsigned long) const at /usr/include/c++/8/bits/hashtable.h:643
 (inlined by) std::_Hashtable<db::toppartitons_item_key, std::pair<db::toppartitons_item_key const, std::_List_iterator<seastar::lw_shared_ptr<utils::space_saving_top_k<db::toppartitons_item_key, db::toppartitons_item_key::hash, db::toppartitons_item_key::comp>::counter> > >, std::allocator<std::pair<db::toppartitons_item_key const, std::_List_iterator<seastar::lw_shared_ptr<utils::space_saving_top_k<db::toppartitons_item_key, db::toppartitons_item_key::hash, db::toppartitons_item_key::comp>::counter> > > >, std::__detail::_Select1st, db::toppartitons_item_key::comp, db::toppartitons_item_key::hash, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, false, true> >::find(db::toppartitons_item_key const&) at /usr/include/c++/8/bits/hashtable.h:1440
 (inlined by) std::unordered_map<db::toppartitons_item_key, std::_List_iterator<seastar::lw_shared_ptr<utils::space_saving_top_k<db::toppartitons_item_key, db::toppartitons_item_key::hash, db::toppartitons_item_key::comp>::counter> >, db::toppartitons_item_key::hash, db::toppartitons_item_key::comp, std::allocator<std::pair<db::toppartitons_item_key const, std::_List_iterator<seastar::lw_shared_ptr<utils::space_saving_top_k<db::toppartitons_item_key, db::toppartitons_item_key::hash, db::toppartitons_item_key::comp>::counter> > > > >::find(db::toppartitons_item_key const&) at /usr/include/c++/8/bits/unordered_map.h:921
 (inlined by) utils::space_saving_top_k<db::toppartitons_item_key, db::toppartitons_item_key::hash, db::toppartitons_item_key::comp>::append_return_all(db::toppartitons_item_key, unsigned int, unsigned int) at /jenkins/workspace/scylla-3.1/relocatable-pkg/scylla/./utils/top_k.hh:150
utils::space_saving_top_k<db::toppartitons_item_key, db::toppartitons_item_key::hash, db::toppartitons_item_key::comp>::append(db::toppartitons_item_key, unsigned int, unsigned int) at /jenkins/workspace/scylla-3.1/relocatable-pkg/scylla/seastar/include/seastar/core/future.hh:768
 (inlined by) operator() at /jenkins/workspace/scylla-3.1/relocatable-pkg/scylla/db/data_listeners.cc:88
 (inlined by) operator() at /jenkins/workspace/scylla-3.1/relocatable-pkg/scylla/./mutation_reader.hh:109
 (inlined by) apply at /jenkins/workspace/scylla-3.1/relocatable-pkg/scylla/seastar/include/seastar/core/apply.hh:35
 (inlined by) apply<filtering_reader<MutationFilter>::fill_buffer(seastar::lowres_clock::time_point) [with MutationFilter = db::toppartitions_data_listener::on_read(const schema_ptr&, const partition_range&, const query::partition_slice&, flat_mutation_reader&&)::<lambda(const dht::decorated_key&)>]::<lambda()>::<lambda()> > at /jenkins/workspace/scylla-3.1/relocatable-pkg/scylla/seastar/include/seastar/core/apply.hh:43
 (inlined by) apply_tuple<filtering_reader<MutationFilter>::fill_buffer(seastar::lowres_clock::time_point) [with MutationFilter = db::toppartitions_data_listener::on_read(const schema_ptr&, const partition_range&, const query::partition_slice&, flat_mutation_reader&&)::<lambda(const dht::decorated_key&)>]::<lambda()>::<lambda()> > at /jenkins/workspace/scylla-3.1/relocatable-pkg/scylla/seastar/include/seastar/core/future.hh:1346
apply<filtering_reader<MutationFilter>::fill_buffer(seastar::lowres_clock::time_point) [with MutationFilter = db::toppartitions_data_listener::on_read(const schema_ptr&, const partition_range&, const query::partition_slice&, flat_mutation_reader&&)::<lambda(const dht::decorated_key&)>]::<lambda()>::<lambda()> > at /jenkins/workspace/scylla-3.1/relocatable-pkg/scylla/seastar/include/seastar/core/future.hh:768
 (inlined by) operator()<seastar::future_state<> > at /jenkins/workspace/scylla-3.1/relocatable-pkg/scylla/seastar/include/seastar/core/future.hh:950
 (inlined by) run_and_dispose at /jenkins/workspace/scylla-3.1/relocatable-pkg/scylla/seastar/include/seastar/core/future.hh:377
seastar::reactor::run_tasks(seastar::reactor::task_queue&) at /usr/include/boost/program_options/variables_map.hpp:146
seastar::reactor::run_some_tasks() at /usr/include/boost/program_options/variables_map.hpp:146
seastar::reactor::run_some_tasks() at /usr/include/boost/program_options/variables_map.hpp:146
 (inlined by) seastar::reactor::run() at /jenkins/workspace/scylla-3.1/relocatable-pkg/scylla/seastar/build/release/../../src/core/reactor.cc:4238
seastar::smp::configure(boost::program_options::variables_map, seastar::reactor_config)::{lambda()#3}::operator()() const at /usr/include/boost/program_options/variables_map.hpp:146
std::function<void ()>::operator()() const at /usr/include/c++/8/bits/std_function.h:687
 (inlined by) seastar::posix_thread::start_routine(void*) at /jenkins/workspace/scylla-3.1/relocatable-pkg/scylla/seastar/build/release/../../src/core/posix.cc:52
?? ??:0
?? ??:0
```

Coredump:
```
[centos@ip-172-30-0-51 ~]$ coredumpctl info 3039
           PID: 3039 (scylla)
           UID: 996 (scylla)
           GID: 1001 (scylla)
        Signal: 11 (SEGV)
     Timestamp: Mon 2019-08-26 11:42:34 UTC (23min ago)
  Command Line: /usr/bin/scylla /opt/scylladb/bin/../libexec/scylla.bin --blocked-reactor-notify-ms 500 --abort-on-lsa-bad-alloc 1 --abort-on-seastar-bad-alloc --log-to-syslog 1 --log-to-stdout 0 --default-log-level info --network-stack 
    Executable: /opt/scylladb/libreloc/ld.so
 Control Group: /
       Boot ID: 06853c6457c949b789926654cbd72b13
    Machine ID: df877a200226bc47d06f26dae0736ec9
      Hostname: ip-172-30-0-51.ec2.internal
       Message: Process 3039 (scylla) of user 996 dumped core.
                
                Stack trace of thread 3046:
                #0  0x00000000023ea162 _ZNKSt10_HashtableIN2db21toppartitons_item_keyESt4pairIKS1_St14_List_iteratorIN7seastar13lw_shared_ptrIN5utils18space_saving_top_kIS1_NS1_4hashENS1_4compEE7counterEEEEESaISF_ENSt8__detail10_Select1s
```

Coredump uploaded to ```upload.scylladb.com/core.scylla.996.06853c6457c949b789926654cbd72b13.3039.1566819754000000.gz```

Actually I am not sure when happened segmentation fault.
When I found Json failure on toppartition on MV, I run this command manually from the node. And after that run toppartition on regular table:
```
nodetool  toppartitions mview users 8728 -s 193 -k 13 -a reads
```
mview.users is table with two MVs.
By journalctl, segmentation fault happened in this time:
```
Aug 26 11:42:25 ip-172-30-0-51.ec2.internal scylla.bin[3039]:  [shard 0] api - toppartitions query: name=mview:users duration=8728 list_size= capacity=193
Aug 26 11:42:34 ip-172-30-0-51.ec2.internal scylla[3039]: Segmentation fault on shard 3.
Aug 26 11:42:34 ip-172-30-0-51.ec2.internal scylla[3039]: Backtrace:
Aug 26 11:42:34 ip-172-30-0-51.ec2.internal scylla[3039]: 0x0000000004175d22
Aug 26 11:42:34 ip-172-30-0-51.ec2.internal scylla[3039]: 0x0000000004062fa5
Aug 26 11:42:34 ip-172-30-0-51.ec2.internal scylla[3039]: 0x00000000040632a5
Aug 26 11:42:34 ip-172-30-0-51.ec2.internal scylla[3039]: 0x00000000040632f3
Aug 26 11:42:34 ip-172-30-0-51.ec2.internal scylla[3039]: 0x00007f54ca7a402f
Aug 26 11:42:34 ip-172-30-0-51.ec2.internal scylla[3039]: 0x00000000023ea161
Aug 26 11:42:34 ip-172-30-0-51.ec2.internal scylla[3039]: 0x00000000023afe9e
Aug 26 11:42:34 ip-172-30-0-51.ec2.internal scylla[3039]: 0x00000000023b31d2
Aug 26 11:42:34 ip-172-30-0-51.ec2.internal scylla[3039]: 0x0000000004060491
Aug 26 11:42:34 ip-172-30-0-51.ec2.internal scylla[3039]: 0x000000000406068e
Aug 26 11:42:34 ip-172-30-0-51.ec2.internal scylla[3039]: 0x000000000414235d
Aug 26 11:42:34 ip-172-30-0-51.ec2.internal scylla[3039]: 0x000000000416c9cb
Aug 26 11:42:34 ip-172-30-0-51.ec2.internal scylla[3039]: 0x000000000402e78d
Aug 26 11:42:34 ip-172-30-0-51.ec2.internal scylla[3039]: /opt/scylladb/bin/../libreloc/libpthread.so.0+0x000000000000858d
Aug 26 11:42:34 ip-172-30-0-51.ec2.internal scylla[3039]: /opt/scylladb/bin/../libreloc/libc.so.6+0x00000000000fd6a2
```

**Comment by amnonh** [comment] 2019-08-26 11:13
@juliayakovlev Can you add the steps you did to reproduce it?

**Comment by juliayakovlev** [comment] 2019-08-26 11:18
Create tablespace
```
CREATE KEYSPACE mview WITH replication = {'class': 'SimpleStrategy', 'replication_factor': 3};
```

Create table
```
CREATE TABLE users (
    username text,
    first_name text,
    last_name text,
    password text,
    email text,
    last_access timeuuid,
    PRIMARY KEY(username)
  );
```

Create MV:
```
CREATE MATERIALIZED VIEW mview.users_by_last_name AS SELECT * FROM mview.users WHERE last_name IS NOT NULL and username IS NOT NULL PRIMARY KEY (last_name, username);
```

Run nodetool:
```
nodetool  toppartitions mview users_by_last_name 1556 -s 320 -k 19 -a reads
```

**Comment by amnonh** [comment] 2019-08-26 11:37
Just tried to reproduce it locally with 3 nodes cluster running master, and it didn't reproduce.
$ ./bin/nodetool toppartitions mview users_by_last_name 1556 -s 320 -k 19 -a reads
READS Sampler:
  Cardinality: ~0 (320 capacity)
  Top 19 partitions:
	Nothing recorded during sampling period...


Is there anything else that was in your environment?

**Comment by avikivity** [comment] 2019-08-26 12:29
Duplicate of #4661

**Closed by avikivity** 2019-08-26 12:29 UTC

**Comment by juliayakovlev** [comment] 2019-08-26 12:47
> Just tried to reproduce it locally with 3 nodes cluster running master, and it didn't reproduce.
> `$ ./bin/nodetool toppartitions mview users_by_last_name 1556 -s 320 -k 19 -a reads`
> READS Sampler:
> Cardinality: ~0 (320 capacity)
> Top 19 partitions:
> Nothing recorded during sampling period...
> 
> Is there anything else that was in your environment?

@amnonh  Please, do it on my instance
