### ISSUE TITLE
Error with message : direct_failure_detector - unexpected exception when pinging 3 should not be treated as error

### ISSUE THREAD

**Issue by aleksbykov** [scylladb/scylla#10639] opened 2022-05-23 11:11 UTC
scylla-release: 0.20220523.6a3494442e6e
scylla-version: 5.1.dev

Dtest tests **test_replace_address.py** marked as failed because during teardown were found next errors:
```
WARN  2022-05-23 10:31:43,772 [shard 1] gossip - failure_detector_loop: Send echo to node 127.0.4.3, status = failed: seastar::rpc::closed_error (connection is closed)
WARN  2022-05-23 10:31:45,773 [shard 1] gossip - failure_detector_loop: Send echo to node 127.0.4.3, status = failed: seastar::rpc::closed_error (connection is closed)
INFO  2022-05-23 10:31:45,773 [shard 1] gossip - failure_detector_loop: Mark node 127.0.4.3 as DOWN
INFO  2022-05-23 10:31:45,773 [shard 0] gossip - InetAddress 127.0.4.3 is now DOWN, status = NORMAL
INFO  2022-05-23 10:32:17,119 [shard 0] raft_group_registry - marking address 127.0.4.4 as alive for raft groups
INFO  2022-05-23 10:32:18,116 [shard 0] gossip - InetAddress 127.0.4.4 is now UP, status = UNKNOWN
INFO  2022-05-23 10:33:47,339 [shard 0] storage_service - replace[84fb7c3e-49f7-4d14-a809-b0e19aa8a5c6]: Added replacing_node=127.0.4.4 to replace existing_node=127.0.4.3, coordinator=127.0.4.4
INFO  2022-05-23 10:33:47,339 [shard 0] token_metadata - Added node 127.0.4.4 as pending replacing endpoint which replaces existing node 127.0.4.3
ERROR 2022-05-23 10:33:47,413 [shard 1] direct_failure_detector - unexpected exception when pinging 3: seastar::rpc::remote_verb_error (Not ready to respond gossip echo message)
ERROR 2022-05-23 10:33:47,512 [shard 1] direct_failure_detector - unexpected exception when pinging 3: seastar::rpc::remote_verb_error (Not ready to respond gossip echo message)
INFO  2022-05-23 10:33:47,523 [shard 0] stream_session - [Stream #d4130531-da83-11ec-80dc-42fdff9d8b44] Executing streaming plan for Replace-keyspace1-index-0 with peers=127.0.4.4, slave
INFO  2022-05-23 10:33:47,524 [shard 0] stream_session - [Stream #d4130531-da83-11ec-80dc-42fdff9d8b44] Start sending ks=keyspace1, cf=standard1, estimated_partitions=0, with new rpc streaming
INFO  2022-05-23 10:33:47,524 [shard 1] stream_session - [Stream #d4130531-da83-11ec-80dc-42fdff9d8b44] Start sending ks=keyspace1, cf=standard1, estimated_partitions=0, with new rpc streaming
ERROR 2022-05-23 10:33:47,613 [shard 1] direct_failure_detector - unexpected exception when pinging 3: seastar::rpc::remote_verb_error (Not ready to respond gossip echo message)
INFO  2022-05-23 10:33:47,613 [shard 0] stream_session - [Stream #d4130531-da83-11ec-80dc-42fdff9d8b44] Streaming plan for Replace-keyspace1-index-0 succeeded, peers={127.0.4.4}, tx=265 KiB, 2950.07 KiB/s, rx=0 KiB, 0.00 KiB/s
INFO  2022-05-23 10:33:47,613 [shard 0] stream_session - [Stream #d420c0d0-da83-11ec-80dc-42fdff9d8b44] Executing streaming plan for Replace-keyspace1-index-1 with peers=127.0.4.4, slave
INFO  2022-05-23 10:33:47,614 [shard 0] stream_session - [Stream #d420c0d0-da83-11ec-80dc-42fdff9d8b44] Start sending ks=keyspace1, cf=standard1, estimated_partitions=0, with new rpc streaming
INFO  2022-05-23 10:33:47,614 [shard 1] stream_session - [Stream #d420c0d0-da83-11ec-80dc-42fdff9d8b44] Start sending ks=keyspace1, cf=standard1, estimated_partitions=0, with new rpc streaming
INFO  2022-05-23 10:33:47,695 [shard 0] stream_session - [Stream #d420c0d0-da83-11ec-80dc-42fdff9d8b44] Streaming plan for Replace-keyspace1-index-1 succeeded, peers={127.0.4.4}, tx=241 KiB, 2974.85 KiB/s, rx=0 KiB, 0.00 KiB/s
INFO  2022-05-23 10:33:47,695 [shard 0] stream_session - [Stream #d42d43f0-da83-11ec-80dc-42fdff9d8b44] Executing streaming plan for Replace-keyspace1-index-2 with peers=127.0.4.4, slave
INFO  2022-05-23 10:33:47,695 [shard 0] stream_session - [Stream #d42d43f0-da83-11ec-80dc-42fdff9d8b44] Start sending ks=keyspace1, cf=standard1, estimated_partitions=0, with new rpc streaming
INFO  2022-05-23 10:33:47,695 [shard 1] stream_session - [Stream #d42d43f0-da83-11ec-80dc-42fdff9d8b44] Start sending ks=keyspace1, cf=standard1, estimated_partitions=0, with new rpc streaming
ERROR 2022-05-23 10:33:47,712 [shard 1] direct_failure_detector - unexpected exception when pinging 3: seastar::rpc::remote_verb_error (Not ready to respond gossip echo message)
ERROR 2022-05-23 10:33:47,813 [shard 1] direct_failure_detector - unexpected exception when pinging 3: seastar::rpc::remote_verb_error (Not ready to respond gossip echo message)
INFO  2022-05-23 10:33:47,820 [shard 0] stream_session - [Stream #d42d43f0-da83-11ec-80dc-42fdff9d8b44] Streaming plan for Replace-keyspace1-index-2 succeeded, peers={127.0.4.4}, tx=351 KiB, 2797.39 KiB/s, rx=0 KiB, 0.00 KiB/s
I
```
all logs could be found here: https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/abykov/job/Dtest/job/dtest-byo-raft-single/6/

the error happened during node remove.

**Comment by kbr-** [comment] 2022-05-23 11:18
We should probably change

``````
future<bool> gossiper::direct_fd_pinger::ping(direct_failure_detector::pinger::endpoint_id id, abort_source& as) {
    try {
        co_await _gossiper._messaging.send_gossip_echo(netw::msg_addr(co_await get_address(id)), _generation_number, as);
    } catch (seastar::rpc::closed_error&) {
        co_return false;
    }
    co_return true;
}
```

to something like
```cpp
future<bool> gossiper::direct_fd_pinger::ping(direct_failure_detector::pinger::endpoint_id id, abort_source& as) {
    try {
        co_await _gossiper._messaging.send_gossip_echo(netw::msg_addr(co_await get_address(id)), _generation_number, as);
    } catch (seastar::rpc::closed_error&) {
        co_return false;
    } catch (seastar::rpc::remote_verb_error& e) {
        if (std::string_view{e.what()}.starts_with("Not ready")) {
            co_return false;
        }
        throw;
    }
    co_return true;
}
```

**Comment by kbr-** [comment] 2022-05-27 15:15
After all it turns out the error should not appear at all, and it seems it was caused by a heisenbug resulting from not initializing a variable :)

**Comment by kbr-** [comment] 2022-05-30 16:47
@aleksbykov latest master (78f81171ba84394eea74043d63614ed6f007173f) contains a bunch of fixes for Raft, including a fix for this one (hopefully). Please rerun these tests with 78f81171ba84394eea74043d63614ed6f007173f or later and see if this happens again.

**Comment by aleksbykov** [comment] 2022-05-30 16:55
@kbr- ok, will check

**Comment by aleksbykov** [comment] 2022-06-06 06:10
Issue could be closed. 
With Scylla: 5.1.dev-0.20220603.72f629c2b6e8 error message is not triggered.

**Comment by kbr-** [comment] 2022-06-06 08:40
Thanks Aleks!
Closing the issue.

**Closed by kbr-** 2022-06-06 08:40 UTC
Labels: raft
