### ISSUE TITLE
Cannot build scylla on Ubuntu 15.10

### ISSUE THREAD

**Issue by thedrow** [scylladb/scylla#572] opened 2015-11-17 16:59 UTC
After installing all the dependencies like so:
```bash
curl -L http://debian.datastax.com/debian/repo_key | sudo apt-key add -
sudo sh -c 'echo "deb http://debian.datastax.com/community/ stable main" >> /etc/apt/sources.list.d/datastax.list'
sudo apt-get update && sudo apt-get install libyaml-cpp-dev liblz4-dev zlib1g-dev libsnappy-dev libthrift-dev antlr3 thrift-compiler
```
After executing ninja I get the following:
```
ninja build/release/scylla -j2
[2/196] CXX build/release/gen/cassandra_types.o
FAILED: g++ -MMD -MT build/release/gen/cassandra_types.o -MF build/release/gen/cassandra_types.o.d -std=gnu++1y -g  -Wall -Werror -fvisibility=hidden -pthread -I/home/omer/Documents/Projects/scylla/seastar -I/home/omer/Documents/Projects/scylla/seastar/build/release/gen  -march=nehalem    -O2 -I/usr/include/jsoncpp -Wno-maybe-uninitialized  -I. -I build/release/gen -I seastar -I seastar/build/release/gen -c -o build/release/gen/cassandra_types.o build/release/gen/cassandra_types.cpp
In file included from build/release/gen/cassandra_types.h:11:0,
                 from build/release/gen/cassandra_types.cpp:7:
/usr/include/thrift/TApplicationException.h:23:20: fatal error: Thrift.h: No such file or directory
compilation terminated.
[2/196] CXX build/release/gen/cassandra_constants.o
FAILED: g++ -MMD -MT build/release/gen/cassandra_constants.o -MF build/release/gen/cassandra_constants.o.d -std=gnu++1y -g  -Wall -Werror -fvisibility=hidden -pthread -I/home/omer/Documents/Projects/scylla/seastar -I/home/omer/Documents/Projects/scylla/seastar/build/release/gen  -march=nehalem    -O2 -I/usr/include/jsoncpp -Wno-maybe-uninitialized  -I. -I build/release/gen -I seastar -I seastar/build/release/gen -c -o build/release/gen/cassandra_constants.o build/release/gen/cassandra_constants.cpp
In file included from build/release/gen/cassandra_types.h:11:0,
                 from build/release/gen/cassandra_constants.h:10,
                 from build/release/gen/cassandra_constants.cpp:7:
/usr/include/thrift/TApplicationException.h:23:20: fatal error: Thrift.h: No such file or directory
compilation terminated.
ninja: build stopped: subcommand failed.
```
It seems that your build does not take LD_PATH and CP_INCLUDE_PATH correctly or something similar because Thrift.h is located at ```/usr/include/thrift/```.
In any case, the dependencies above are required to build scylla on Ubuntu and we should document them once we'll get this resolved.

**Comment by avikivity** [comment] 2015-11-17 17:09
Is there a Thrift.h on your system? Where is it? Is there a pkgconfig file
for Thrift?

**Comment by nyh** [comment] 2015-11-17 17:11
Maybe Thrift.h comes from a separate package? Maybe libthrift-dev?
(Just a guess, I don't have Ubuntu to test this on).

**Comment by slivne** [comment] 2015-11-17 18:40
We build thrift on our own and use a specific version i think its 0.9.1.
You can find the details under dist/ubuntu or debian

**Comment by thedrow** [comment] 2015-11-18 08:12
@avikivity I guess there is no pkg-config for that package.
@nyh correct.
@slivne any reason why I can't use the one from the Cassandra ppa?

**Comment by thedrow** [comment] 2015-11-18 09:57
When running ./build_dependency.sh I get the following error:
```cp: cannot stat ‘dist/ubuntu/dep/antlr3-tool-3.5.2/*’: No such file or directory```
It seems that the script must be run from the root directory but I don't think that there's a reason to do so. At the very least, the README file should mention that.

**Comment by thedrow** [comment] 2015-11-18 09:59
Note that depending on a specific version of boost will make it extremely hard to build scylla on versions later than 14.04.
It should be easier to specify a minimum supported version.
I edited the ./build_dependency.sh script to require libboost-dev which currently is on 1.58.

**Comment by thedrow** [comment] 2015-11-18 10:02
I ended up with ```
Errors were encountered while processing:
 build/antlr3-tool_3.5.2-ubuntu1_all.deb
```
Since they are already installed with sudo apt-get...

**Comment by avikivity** [comment] 2015-11-18 10:03
We build on boost >= 1.55

**Comment by thedrow** [comment] 2015-11-18 10:04
The script specifies build 1.55 explicitly.

**Comment by thedrow** [comment] 2015-11-18 10:06
Note that libaio-dev and libcrypto++-dev are also required.
So the following dependencies are required on Ubuntu:
```
curl -L http://debian.datastax.com/debian/repo_key | sudo apt-key add -
sudo sh -c 'echo "deb http://debian.datastax.com/community/ stable main" >> /etc/apt/sources.list.d/datastax.list'
sudo apt-get update && sudo apt-get install libyaml-cpp-dev liblz4-dev zlib1g-dev libsnappy-dev libthrift-dev antlr3 thrift-compiler libaio-dev libcrypto++-dev
```

**Comment by avikivity** [comment] 2015-11-18 10:06
The script is for Ubuntu 14.04 and needs to be updated for later releases.

**Comment by thedrow** [comment] 2015-11-18 10:08
What I'm saying is that there's no reason to do so. You can just run apt-cache show libboost-dev, grep the version and parse it.

**Comment by thedrow** [comment] 2015-11-18 10:09
Note that regal is also required.
So the following dependencies are required on Ubuntu:
```bash
curl -L http://debian.datastax.com/debian/repo_key | sudo apt-key add -
sudo sh -c 'echo "deb http://debian.datastax.com/community/ stable main" >> /etc/apt/sources.list.d/datastax.list'
sudo apt-get update && sudo apt-get install libyaml-cpp-dev liblz4-dev zlib1g-dev libsnappy-dev libthrift-dev antlr3 thrift-compiler libaio-dev libcrypto++-dev regal
```

**Comment by avikivity** [comment] 2015-11-18 10:44
@syuu1228

**Comment by thedrow** [comment] 2015-11-18 13:02
Note that libboost-thread-dev is also required.
So the following dependencies are required on Ubuntu:
```bash
curl -L http://debian.datastax.com/debian/repo_key | sudo apt-key add -
sudo sh -c 'echo "deb http://debian.datastax.com/community/ stable main" >> /etc/apt/sources.list.d/datastax.list'
sudo apt-get update && sudo apt-get install libyaml-cpp-dev liblz4-dev zlib1g-dev libsnappy-dev libthrift-dev antlr3 thrift-compiler libaio-dev libcrypto++-dev regal libboost-dev libboost-thread-dev
```

**Comment by thedrow** [comment] 2015-11-18 15:15
I was finally able to compile this on Ubuntu 15.10.
Let's turn this into actionable items:
- [ ] Document how to compile from source on Ubuntu
- [ ] Allow to install any boost version above 1.55
- [ ] Allow to install thrift from the Cassandra PPA

Anything else?

**Comment by syuu1228** [comment] 2015-11-18 18:01
I found dist/ubuntu/build_deb.sh does not work on 15.10 due to some package
version issues (boost, and also some packages). send fix shortly
2015/11/19 0:15 "Omer Katz" <notifications@github.com>:

**Comment by syuu1228** [comment] 2015-11-19 09:24
@thedrow 15.10 support now merged, please try dist/ubuntu/build_deb.sh on latest master.

**Comment by thedrow** [comment] 2015-11-19 09:50
I'll give it a shot today.
In any case, I don't see a way to compile scylla with the thrift package from the Cassandra ppa.
Is there a reason why that shouldn't be possible?

**Comment by thedrow** [comment] 2015-11-19 09:59
Also for some reason you're downloading Antlr instead of using the one at the Ubuntu repo. Does scylla need a newer one?

**Comment by syuu1228** [comment] 2015-11-19 10:09
On Thu, Nov 19, 2015 at 6:59 PM, Omer Katz <notifications@github.com> wrote:

> Also for some reason you're downloading Antlr instead of using the one at
> the Ubuntu repo. Does scylla need a newer one?
>
You don't have it on 14.04 LTS.
If 15.10 have it, and scylla able to build with distribution version of
antlr3, when can skip building.

**Comment by thedrow** [comment] 2015-11-19 10:10
We do have it on 15.10.

**Comment by thedrow** [comment] 2015-11-19 10:10
Looks like the new script works.

**Comment by syuu1228** [comment] 2015-11-19 11:19
Confirmed on ubuntu package database on web. Seems we can replace with
distribution package.

**Comment by mxk1235** [comment] 2015-11-24 06:53
Where do you install regal from?  I am on ec2 ubuntu 14.04.

```
~/scylla $ sudo apt-get install regal
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package regal
```

**Comment by slivne** [comment] 2015-12-15 13:04
@thedrow closing this as you reported you can build

**Closed by slivne** 2015-12-15 13:04 UTC

**Comment by thedrow** [comment] 2015-12-15 13:35
Have you guys documented how to compile this on Ubuntu machines at the very least?

**Comment by taidung86** [comment] 2016-01-28 03:01
Hi guys

I have built Scylla db on ubuntu 15.10 and get errors

ninja build/release/scylla -j2
[2/204] CXX build/release/gen/cassandra_types.o
FAILED: g++ -MMD -MT build/release/gen/cassandra_types.o -MF build/release/gen/cassandra_types.o.d -std=gnu++1y -g  -Wall -Werror -fvisibility=hidden -pthread -I/home/vtk-tails/Documents/Project/IMDB/Framework/Scylladb/git/scylla/seastar -I/home/vtk-tails/Documents/Project/IMDB/Framework/Scylladb/git/scylla/seastar/build/release/gen  -march=nehalem  -DHAVE_HWLOC -DHAVE_NUMA  -O2 -I/usr/include/jsoncpp  -Wno-maybe-uninitialized -DHAVE_LIBSYSTEMD=1 -I. -I build/release/gen -I seastar -I seastar/build/release/gen -c -o build/release/gen/cassandra_types.o build/release/gen/cassandra_types.cpp
In file included from build/release/gen/cassandra_types.h:11:0,
                 from build/release/gen/cassandra_types.cpp:7:
/usr/include/thrift/TApplicationException.h:23:20: fatal error: Thrift.h: No such file or directory
compilation terminated.
[2/204] CXX build/release/gen/cassandra_constants.o
FAILED: g++ -MMD -MT build/release/gen/cassandra_constants.o -MF build/release/gen/cassandra_constants.o.d -std=gnu++1y -g  -Wall -Werror -fvisibility=hidden -pthread -I/home/vtk-tails/Documents/Project/IMDB/Framework/Scylladb/git/scylla/seastar -I/home/vtk-tails/Documents/Project/IMDB/Framework/Scylladb/git/scylla/seastar/build/release/gen  -march=nehalem  -DHAVE_HWLOC -DHAVE_NUMA  -O2 -I/usr/include/jsoncpp  -Wno-maybe-uninitialized -DHAVE_LIBSYSTEMD=1 -I. -I build/release/gen -I seastar -I seastar/build/release/gen -c -o build/release/gen/cassandra_constants.o build/release/gen/cassandra_constants.cpp
In file included from build/release/gen/cassandra_types.h:11:0,
                 from build/release/gen/cassandra_constants.h:10,
                 from build/release/gen/cassandra_constants.cpp:7:
/usr/include/thrift/TApplicationException.h:23:20: fatal error: Thrift.h: No such file or directory
compilation terminated.
ninja: build stopped: subcommand failed

Please help me

**Comment by kongove** [comment] 2016-04-28 03:51
Get and install libthrift-dev_0.9.1_amd64.deb, libthrift0_0.9.1_amd64.deb from [1].
Or compile by yourself reference to [2].

[1] https://github.com/n0n0x/thrift-deb/releases
[2] https://github.com/apache/thrift

**Comment by avikivity** [comment] 2016-04-28 08:51
I filed https://bugs.launchpad.net/ubuntu/+source/thrift-compiler/+bug/1576101, hopegfully we'll get out-of-the-box support for this.
