### ISSUE TITLE
Repair should expose it's progress

### ISSUE THREAD

**Issue by amnonh** [scylladb/scylla#6733] opened 2020-06-30 07:44 UTC
The repair has traces for its progress, it should expose metrics as well

**Comment by slivne** [comment] 2020-07-02 07:41
Repairs run via manager provide progress. 

this is a duplicate of https://github.com/scylladb/scylla/issues/1244

**Closed by slivne** 2020-07-02 07:41 UTC

**Comment by avikivity** [comment] 2020-08-27 08:26
Not a bug, not backporting.

**Comment by avikivity** [comment] 2020-11-29 13:20
Looks like the bug was reused, but the previous backport decision holds.
