### ISSUE TITLE
i2.xlarge: coredump in start scylla-server

### ISSUE THREAD

**Issue by amoskong** [scylladb/scylla#5360] opened 2019-11-27 10:10 UTC
*Installation details*
Scylla version (or git commit hash): 666.development-0.20191126.4160b3630d
Cluster size: 1
OS (RHEL/CentOS/Ubuntu/AWS AMI): 
- scylla_2019-11-27T07-26-21Z (ami-0bcf61ab6b989903d)
- us-east-1

```
[centos@ip-172-10-4-100 ~]$ scylla --log-to-syslog 1 --log-to-stdout 1 --default-log-level trace --network-stack posix --io-properties-file=/etc/scylla.d/io_properties.yaml --cpuset 0-3
Scylla version 666.development-0.20191126.4160b3630d starting ...
command used: "/usr/bin/scylla --log-to-syslog 1 --log-to-stdout 1 --default-log-level trace --network-stack posix --io-properties-file=/etc/scylla.d/io_properties.yaml --cpuset 0-3"
parsed command line options: [log-to-syslog: 1, log-to-stdout: 1, default-log-level: trace, network-stack: posix, io-properties-file: /etc/scylla.d/io_properties.yaml, cpuset: 0-3]
DEBUG 2019-11-27 10:00:40,766 seastar - smp::count: 4
DEBUG 2019-11-27 10:00:40,766 seastar - latency_goal: 0.00075
DEBUG 2019-11-27 10:00:40,772 seastar - dev_io_queues: 1
DEBUG 2019-11-27 10:00:40,772 seastar - dev_id: 51728 mountpoint: /var/lib/scylla
DEBUG 2019-11-27 10:00:40,772 seastar - num_io_queues: 1
DEBUG 2019-11-27 10:00:40,799 [shard 0] seastar - generate_config dev_id: 0
DEBUG 2019-11-27 10:00:40,800 [shard 0] seastar - generate_config dev_id: 51728
Floating point exception (core dumped)
[centos@ip-172-10-4-100 ~]$ echo $?
136
[centos@ip-172-10-4-100 ~]$ scylla --version
666.development-0.20191126.4160b3630d
```

```
           PID: 5134 (scylla)
           UID: 1000 (centos)
           GID: 1000 (centos)
        Signal: 8 (FPE)
     Timestamp: Wed 2019-11-27 10:00:40 UTC (2min 40s ago)
  Command Line: /usr/bin/scylla --log-to-syslog 1 --log-to-stdout 1 --default-log-level trace --network-stack posix --io-properties-file=/etc/scylla.d/io_properties.yaml --cpuset 0-3
    Executable: /opt/scylladb/libexec/scylla
 Control Group: /user.slice/user-1000.slice/session-2.scope
          Unit: session-2.scope
         Slice: user-1000.slice
       Session: 2
     Owner UID: 1000 (centos)
       Boot ID: 1d27b3079a7b45a398bf9de29bdc20aa
    Machine ID: df877a200226bc47d06f26dae0736ec9
      Hostname: ip-172-10-4-100.ec2.internal
      Coredump: /var/lib/systemd/coredump/core.scylla.1000.1d27b3079a7b45a398bf9de29bdc20aa.5134.1574848840000000
       Message: Process 5134 (scylla) of user 1000 dumped core.
                
                Stack trace of thread 5134:
                #0  0x0000000002b5dae6 _ZNK7seastar18disk_config_params15generate_configEm (scylla)
                #1  0x0000000002b8b623 _ZN7seastar3smp9configureEN5boost15program_options13variables_mapENS_14reactor_configE (scylla)
                #2  0x0000000002ab8fc1 _ZN7seastar12app_template14run_deprecatedEiPPcOSt8functionIFvvEE (scylla)
                #3  0x0000000002aba3df _ZN7seastar12app_template3runEiPPcOSt8functionIFNS_6futureIJiEEEvEE (scylla)
                #4  0x00000000007a9008 main (scylla)
                #5  0x00007f0999c5f1a3 __libc_start_main (libc.so.6)
                #6  0x00000000007f8c5e _start (scylla)
                
                Stack trace of thread 5135:
                #0  0x00007f0999e12fd6 _Unwind_IteratePhdrCallback (libgcc_s.so.1)
                #1  0x0000000002abc38c dl_iterate_phdr (scylla)
                #2  0x00007f0999e14175 _Unwind_Find_FDE (libgcc_s.so.1)
                #3  0x00007f0999e10843 uw_frame_state_for (libgcc_s.so.1)
                #4  0x00007f0999e11a50 uw_init_context_1 (libgcc_s.so.1)
                #5  0x00007f0999e1278c _Unwind_Backtrace (libgcc_s.so.1)
                #6  0x00007f0999d46ba6 __backtrace (libc.so.6)
                #7  0x0000000002b0a68e backtrace<seastar::internal::cpu_stall_detector::cpu_stall_detector(seastar::reactor*, seastar::internal::cpu_stall_detector_config)::<lambda(seastar::frame)> > (scylla)
                #8  0x0000000002b83a74 _ZSt11make_uniqueIN7seastar8internal18cpu_stall_detectorEJPNS0_7reactorEEENSt9_MakeUniqIT_E15__single_objectEDpOT0_ (scylla)
                #9  0x0000000002b841c6 _ZN7seastar3smp16allocate_reactorEjNS_24reactor_backend_selectorENS_14reactor_configE (scylla)
                #10 0x0000000002b8867a _ZZN7seastar3smp9configureEN5boost15program_options13variables_mapENS_14reactor_configEENKUlvE1_clEv (scylla)
                #11 0x0000000002aef25e _ZNKSt8functionIFvvEEclEv (scylla)
                #12 0x00007f099a69d4e2 start_thread (libpthread.so.0)
                #13 0x00007f0999d39643 __clone (libc.so.6)
                
                Stack trace of thread 5138:
                #0  0x00007f099a6a787c read (libpthread.so.0)
                #1  0x0000000002f4e066 _ZN7seastar11thread_pool4workENS_13basic_sstringIcjLj15ELb1EEE (scylla)
                #2  0x0000000002f4e352 operator() (scylla)
                #3  0x0000000002aef25e _ZNKSt8functionIFvvEEclEv (scylla)
                #4  0x00007f099a69d4e2 start_thread (libpthread.so.0)
                #5  0x00007f0999d39643 __clone (libc.so.6)
                
                Stack trace of thread 5136:
                #0  0x0000000002ad8f8e _ZN7seastar6memory9cpu_pages9grow_spanERjS2_j (scylla)
                #1  0x0000000002ada5fa _ZN7seastar6memory9cpu_pages9do_resizeEmSt8functionIFSt10unique_ptrIA_cNS_12mmap_deleterEESt8optionalIPvEmEE (scylla)
                #2  0x0000000002ada6db _ZN7seastar6memory9cpu_pages6resizeEmSt8functionIFSt10unique_ptrIA_cNS_12mmap_deleterEESt8optionalIPvEmEE (scylla)
                #3  0x0000000002add474 _ZN7seastar6memory9configureESt6vectorINS_8resource6memoryESaIS3_EEbSt8optionalINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEE (scylla)
                #4  0x0000000002b88592 _ZZN7seastar3smp9configureEN5boost15program_options13variables_mapENS_14reactor_configEENKUlvE1_clEv (scylla)
                #5  0x0000000002aef25e _ZNKSt8functionIFvvEEclEv (scylla)
                #6  0x00007f099a69d4e2 start_thread (libpthread.so.0)
                #7  0x00007f0999d39643 __clone (libc.so.6)
                
                Stack trace of thread 5137:
                #0  0x0000000002ad8f8e _ZN7seastar6memory9cpu_pages9grow_spanERjS2_j (scylla)
                #1  0x0000000002ada5fa _ZN7seastar6memory9cpu_pages9do_resizeEmSt8functionIFSt10unique_ptrIA_cNS_12mmap_deleterEESt8optionalIPvEmEE (scylla)
                #2  0x0000000002ada6db _ZN7seastar6memory9cpu_pages6resizeEmSt8functionIFSt10unique_ptrIA_cNS_12mmap_deleterEESt8optionalIPvEmEE (scylla)
                #3  0x0000000002add474 _ZN7seastar6memory9configureESt6vectorINS_8resource6memoryESaIS3_EEbSt8optionalINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEE (scylla)
                #4  0x0000000002b88592 _ZZN7seastar3smp9configureEN5boost15program_options13variables_mapENS_14reactor_configEENKUlvE1_clEv (scylla)
                #5  0x0000000002aef25e _ZNKSt8functionIFvvEEclEv (scylla)
                #6  0x00007f099a69d4e2 start_thread (libpthread.so.0)
                #7  0x00007f0999d39643 __clone (libc.so.6)
```

**Comment by amoskong** [comment] 2019-11-27 10:17
The coredump file is uploaded to GCE storage:
https://console.cloud.google.com/storage/browser/_details/upload.scylladb.com/amos/scylla_issue_5360/core.scylla.1000.1d27b3079a7b45a398bf9de29bdc20aa.5134.1574848840000000.tar.gz
(size: 29M)

**Comment by amoskong** [comment] 2019-11-27 10:43
Failed to load the coredump with scylla gdb:

```
[centos@ip-172-10-4-100 coredump]$ /opt/scylladb/bin/gdb /opt/scylladb/libexec/scylla ./core.scylla.1000.1d27b3079a7b45a398bf9de29bdc20aa.5134.1574848840000000
GNU gdb (GDB) Red Hat Enterprise Linux 7.10.1-30.el7.centos
Copyright (C) 2015 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /opt/scylladb/libexec/scylla...Reading symbols from /usr/lib/debug/opt/scylladb/libexec/scylla-666.development-0.20191126.4160b3630d.el7.x86_64.debug...done.
done.
[New LWP 5134]
[New LWP 5135]
[New LWP 5138]
[New LWP 5136]
[New LWP 5137]
BFD: BFD (GNU Binutils) 2.25.51 internal error, aborting at ../../bfd/elf64-x86-64.c line 5770 in elf_x86_64_get_plt_sym_val

BFD: Please report this bug.

[centos@ip-172-10-4-100 coredump]$ echo $?
1
[centos@ip-172-10-4-100 coredump]$ rpm -qa|grep scylla
scylla-python3-3.7.5-0.20191127.4160b3630d.el7.x86_64
scylla-server-666.development-0.20191126.4160b3630d.el7.x86_64
scylla-666.development-0.20191126.4160b3630d.el7.x86_64
scylla-gdb-7.10.1-30.el7.centos.x86_64
scylla-jmx-666.development-20191127.d8c47603d9.noarch
scylla-env-1.1-1.el7.noarch
scylla-conf-666.development-0.20191126.4160b3630d.el7.x86_64
scylla-kernel-conf-666.development-0.20191126.4160b3630d.el7.x86_64
scylla-tools-666.development-20191127.35906df2a0.noarch
scylla-debuginfo-666.development-0.20191126.4160b3630d.el7.x86_64
scylla-tools-core-666.development-20191127.35906df2a0.noarch
scylla-ami-666.development-20191127.15bb0a7.fc27.noarch
```

**Comment by amoskong** [comment] 2019-11-27 11:06
```
[centos@ip-172-10-4-100 ~]$ /opt/scylladb/bin/gdb --args /opt/scylladb/libexec/scylla --log-to-syslog 1 --log-to-stdout 1 --default-log-level trace --network-stack posix --io-properties-file=/etc/scylla.d/io_properties.yaml --cpuset 0-3
GNU gdb (GDB) Red Hat Enterprise Linux 7.10.1-30.el7.centos
Copyright (C) 2015 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /opt/scylladb/libexec/scylla...Reading symbols from /usr/lib/debug/opt/scylladb/libexec/scylla-666.development-0.20191126.4160b3630d.el7.x86_64.debug...done.
done.
(gdb) r
Starting program: /opt/scylladb/libexec/scylla --log-to-syslog 1 --log-to-stdout 1 --default-log-level trace --network-stack posix --io-properties-file=/etc/scylla.d/io_properties.yaml --cpuset 0-3
BFD: BFD (GNU Binutils) 2.25.51 internal error, aborting at ../../bfd/elf64-x86-64.c line 5770 in elf_x86_64_get_plt_sym_val

BFD: Please report this bug.

[centos@ip-172-10-4-100 ~]$ echo $?
1
```

**Comment by slivne** [comment] 2019-11-28 10:52
@amoskong is this reproducible - if so can you provide instructions

**Comment by amoskong** [comment] 2019-11-28 12:25
The AMI I used to reproduce this issue , contained some issue in scylla setup script.
I have a script to workaround those issues:  [workaround-scylla-setup-issues.sh.txt](https://github.com/scylladb/scylla/files/3901594/workaround-scylla-setup-issues.sh.txt)

----

A SIMPLE way to reproduce this issue is use the latest good AMI (which passed the ami-test).
- ami-01148a97875c49739
- https://jenkins.scylladb.com/job/scylla-master/job/ami-test/78/
- test log: https://jenkins.scylladb.com/job/scylla-master/job/ami-test/78/artifact/latest/job.log

Just create an instance (i2.xlarge) with ami-01148a97875c49739, wait a while, login to the instance, you will find the coredump.

I didn't reproduce this problem with i3.xlarge.

**Comment by xemul** [comment] 2019-11-28 12:41
Where can I find the scylla binary itself? @amoskong

**Comment by xemul** [comment] 2019-11-28 12:44
And the config file used.

**Comment by amoskong** [comment] 2019-11-28 12:47
> Where can I find the scylla binary itself?

/opt/scylladb/libexec/scylla

> And the config file used.

/etc/scylla/scylla.yaml

**Comment by xemul** [comment] 2019-11-28 12:52
No other way rather than run the instance from ami again and get it?

**Comment by roydahan** [comment] 2019-11-28 12:56
@amoskong why are you testing with i2?

**Comment by amoskong** [comment] 2019-11-28 13:03
> @amoskong why are you testing with i2?

When I reproduce another scylla setup issue. I created an instance manually, wrongly choose i2.

**Comment by roydahan** [comment] 2019-11-28 13:40
If the issue is only with i2, the priority for fixing it is low or even none.
We do not support this instance type anymore.

**Comment by xemul** [comment] 2019-12-02 10:07
@amoskong , any chance to get the io_properties.yaml file from your test-run?

**Comment by amoskong** [comment] 2019-12-03 04:50
> io_properties

I did't find it from the log, but I can reproduce this issue by an new instance.
and provide the configuration & living instance.

**Comment by amoskong** [comment] 2019-12-03 04:53
> > io_properties
> 
> I did't find it from the log, but I can reproduce this issue by an new instance.
> and provide the configuration & living instance.

```
[centos@ip-172-10-247-218 scylla.d]$ cat io_properties.yaml 
disks:
- mountpoint: /var/lib/scylla
  read_bandwidth: 0
  read_iops: 0
  write_bandwidth: 0
  write_iops: 0
[centos@ip-172-10-247-218 scylla.d]$ cat io.conf 
SEASTAR_IO="--io-properties-file=/etc/scylla.d/io_properties.yaml"
[centos@ip-172-10-247-218 scylla.d]$ cat cpuset.conf 
# DO NO EDIT
# This file should be automatically configure by scylla_cpuset_setup
#
# CPUSET="--cpuset 0 --smp 1"
CPUSET="--cpuset 0-3 "
```

### Scylla AMI Setup Log:

```
Dec 03 04:50:20 ip-172-10-247-218.ec2.internal systemd[1]: Starting Scylla AMI Setup...
-- Subject: Unit scylla-ami-setup.service has begun start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit scylla-ami-setup.service has begun starting up.
Dec 03 04:50:35 ip-172-10-247-218.ec2.internal scylla_ami_setup[2087]: Waiting for cloud-init to finish...
Dec 03 04:50:35 ip-172-10-247-218.ec2.internal scylla_ami_setup[2087]: [INFO] No userdata found. Starting 1 node clusters, by default.
Dec 03 04:50:35 ip-172-10-247-218.ec2.internal scylla_ami_setup[2087]: [INFO] Using instance type: i2.xlarge
Dec 03 04:50:35 ip-172-10-247-218.ec2.internal scylla_ami_setup[2087]: [INFO] meta-data:instance-type: i2.xlarge
Dec 03 04:50:35 ip-172-10-247-218.ec2.internal scylla_ami_setup[2087]: [INFO] meta-data:local-ipv4: 172.10.247.218
Dec 03 04:50:35 ip-172-10-247-218.ec2.internal scylla_ami_setup[2087]: [INFO] meta-data:public-hostname: ec2-34-201-219-8.compute-1.amazonaws.com
Dec 03 04:50:35 ip-172-10-247-218.ec2.internal scylla_ami_setup[2087]: [INFO] meta-data:ami-launch-index: 0
Dec 03 04:50:35 ip-172-10-247-218.ec2.internal scylla_ami_setup[2087]: [INFO] meta-data:reservation-id: r-0c324b26f8868f962
Dec 03 04:50:35 ip-172-10-247-218.ec2.internal scylla_ami_setup[2087]: [INFO] Using cluster name: Test Cluster - No AMI Parameters
Dec 03 04:50:35 ip-172-10-247-218.ec2.internal scylla_ami_setup[2087]: [INFO] Using cluster size: 1
Dec 03 04:50:35 ip-172-10-247-218.ec2.internal scylla_ami_setup[2087]: [INFO] Using seed indexes: [0, 1, 1]
Dec 03 04:50:35 ip-172-10-247-218.ec2.internal scylla_ami_setup[2087]: [INFO] Reflector loop...
Dec 03 04:50:35 ip-172-10-247-218.ec2.internal scylla_ami_setup[2087]: [INFO] 12/03/19-04:50:35 Reflector: Received 1 of 1 responses from: [u'172.10.247.218']
Dec 03 04:50:35 ip-172-10-247-218.ec2.internal scylla_ami_setup[2087]: [INFO] scylla.yaml configured.
Dec 03 04:51:56 ip-172-10-247-218.ec2.internal scylla_ami_setup[2087]: meta-data=/dev/xvdg              isize=512    agcount=4, agsize=48838198 blks
Dec 03 04:51:56 ip-172-10-247-218.ec2.internal scylla_ami_setup[2087]: =                       sectsz=4096  attr=2, projid32bit=1
Dec 03 04:51:56 ip-172-10-247-218.ec2.internal scylla_ami_setup[2087]: =                       crc=1        finobt=0, sparse=0
Dec 03 04:51:56 ip-172-10-247-218.ec2.internal scylla_ami_setup[2087]: data     =                       bsize=4096   blocks=195352790, imaxpct=25
Dec 03 04:51:56 ip-172-10-247-218.ec2.internal scylla_ami_setup[2087]: =                       sunit=0      swidth=0 blks
Dec 03 04:51:56 ip-172-10-247-218.ec2.internal scylla_ami_setup[2087]: naming   =version 2              bsize=4096   ascii-ci=0 ftype=1
Dec 03 04:51:56 ip-172-10-247-218.ec2.internal scylla_ami_setup[2087]: log      =internal log           bsize=4096   blocks=95387, version=2
Dec 03 04:51:56 ip-172-10-247-218.ec2.internal scylla_ami_setup[2087]: =                       sectsz=4096  sunit=1 blks, lazy-count=1
Dec 03 04:51:56 ip-172-10-247-218.ec2.internal scylla_ami_setup[2087]: realtime =none                   extsz=4096   blocks=0, rtextents=0
Dec 03 04:51:56 ip-172-10-247-218.ec2.internal scylla_ami_setup[2087]: Creating XFS volume for scylla using 1 disk(s): /dev/xvdg
Dec 03 04:51:56 ip-172-10-247-218.ec2.internal scylla_ami_setup[2087]: [INFO] RAID Array containing ['xvdg'] not found. Creating...
Dec 03 04:51:59 ip-172-10-247-218.ec2.internal scylla_ami_setup[2087]: kernel.core_pattern = |/usr/lib/systemd/systemd-coredump %p %u %g %s %t %e"
Dec 03 04:51:59 ip-172-10-247-218.ec2.internal systemd[1]: Started Scylla AMI Setup.
```

```
[centos@ip-172-10-247-218 scylla.d]$ df
Filesystem     1K-blocks     Used Available Use% Mounted on
devtmpfs        15650924        0  15650924   0% /dev
tmpfs           15678456        0  15678456   0% /dev/shm
tmpfs           15678456    16820  15661636   1% /run
tmpfs           15678456        0  15678456   0% /sys/fs/cgroup
/dev/xvda1      10474240  3157008   7317232  31% /
tmpfs            3135692        0   3135692   0% /run/user/1000
/dev/xvdg      781029612 39824244 741205368   6% /var/lib/scylla
```

**Comment by amoskong** [comment] 2019-12-03 04:59
> > io_properties
> 
> I did't find it from the log, but I can reproduce this issue by an new instance.
> and provide the configuration & living instance.

I had send you an email about the instance ip, key.
Please ping me when you don't need it, then I can delete it.

**Comment by xemul** [comment] 2019-12-03 07:01
That's the crash reason:

      read_bandwidth: 0
      read_iops: 0
      write_bandwidth: 0
      write_iops: 0

the seastar's generate_config divides on these values w/o any checks. I'll fix the seastar to handle this nicely, but @amoskong , I would say there's also a problem with the dist/common/scripts/scylla_io_setup script. The disk_properties dict assigns "$const * nr_disks" value in many places, and nr_disks is the amount of the "ephemeral" entries in scylla_util.py _disks[], which can be zero, I guess, resulting in 0-s in config as we see now.

**Comment by xemul** [comment] 2019-12-03 13:37
@amoskong , I don't need the instance, you can remove it.

**Comment by amoskong** [comment] 2019-12-04 06:16
> @amoskong , I don't need the instance, you can remove it.

Deleted, thanks.

BTW, do we need to change scylla_io_setup to not generate invalid configuration?

/CC @syuu1228

**Comment by xemul** [comment] 2019-12-04 07:02
> BTW, do we need to change scylla_io_setup to not generate invalid configuration?

I believe we should, Avi had just merged the patch that makes seastar exit with error in case it meets zeroes in the mentioned parameters.

**Closed** 2019-12-07 07:31 UTC
Labels: Backport candidate

**Comment by avikivity** [comment] 2020-02-16 15:17
Backported to 3.2, 3.1 (3.3 already safe).
