### ISSUE TITLE
ubuntu 16 apt install  release NOT found

### ISSUE THREAD

**Issue by zhshw** [scylladb/scylla#1991] opened 2017-01-04 03:58 UTC
*Installation details*

Ubuntu 16.04
Stable release 1.5 (recommended)

sudo wget -O /etc/apt/sources.list.d/scylla.list http://downloads.scylladb.com/deb/ubuntu/scylla-1.5-xenial.list
sudo apt update

Err:7 http://s3.amazonaws.com/downloads.scylladb.com/deb/ubuntu xenial Release
  404  Not Found
Reading package lists... Done
E: The repository 'http://s3.amazonaws.com/downloads.scylladb.com/deb/ubuntu xenial Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.

**Comment by tzach** [comment] 2017-01-04 09:04
@zhshw I just retested on Ubuntu 16 server and it works fine for me.

You should ignore the following warning after `sudo apt update`
```
W: The repository 'http://s3.amazonaws.com/downloads.scylladb.com/deb/ubuntu xenial Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```
Its a known issue we need to fix. Running `sudo apt-get install scylla` works for me.

Maybe you have a networking issue (firewall?) stopping you from downloading file from s3?

**Comment by tzach** [comment] 2017-01-09 20:53
@syuu1228 @slivne ping

**Comment by slivne** [comment] 2017-01-10 10:49
@zhshw  I tried to run it as well of hosts located in asia and it works ... so we are not able to reproduce this :(

can you please try the following:

```
wget https://s3.amazonaws.com/downloads.scylladb.com/deb/ubuntu/scylla-1.5-xenial.list
```

this is a different manner to access the http://downloads.scylladb.com.s3.amazonaws.com/deb/ubuntu/scylla-1.5-xenial.list file

does that work for you ? if not its an access issue.

if it does not work - then we can try to update the repo file and use the downloads.scylladb.com url instead of the s3 one, that is

your current scylla-1.5-xenial.list has:
```
deb  [arch=amd64] http://s3.amazonaws.com/downloads.scylladb.com/deb/ubuntu xenial scylladb-1.5/multiverse
```

you can try and change that to:
```
deb  [arch=amd64] http://downloads.scylladb.com/deb/ubuntu xenial scylladb-1.5/multiverse
```

**Comment by zhshw** [comment] 2017-01-12 04:00
Still the same error

W: The repository 'http://downloads.scylladb.com/deb/ubuntu xenial Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by syuu1228** [comment] 2017-01-12 04:19
@zhshw You are right, it's secure apt issue.
I think following commands works for you:
```
sudo apt-get update --allow-unauthenticated
sudo apt-get install scylla --allow-unauthenticated
```

Sorry for inconvenience.

**Comment by laxmi-narayan-nitdgp** [comment] 2017-04-18 01:58
issue is still present with 

 http://s3.amazonaws.com/downloads.scylladb.com/deb/ubuntu xenial/scylladb-1.6/multiverse

**Comment by tzach** [comment] 2017-08-02 07:52
@syuu1228 is the fix for this is #848 or something else?

Till this is solved, I update http://www.scylladb.com/download/ubuntu-16-04/ to include 
```
sudo apt-get update --allow-unauthenticated
sudo apt-get install scylla --allow-unauthenticated
```

**Comment by syuu1228** [comment] 2017-08-02 08:07
@tzach We cannot install Scylla with "apt" command until we move to signed repo, so it's #848.

**Comment by avikivity** [comment] 2017-08-02 08:33
@syuu1228 even if we add [trusted=yes] do the list file?

**Comment by tzach** [comment] 2017-11-14 10:46
Duplication of #848

**Closed by tzach** 2017-11-14 10:46 UTC
Labels: duplicate, high, onboarding, ubuntu
