### ISSUE TITLE
scylla_io_setup returning huge read IOPs

### ISSUE THREAD

**Issue by KamalKang** [scylladb/scylla#4024] opened 2018-12-25 20:18 UTC
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash):
Cluster size:
OS (RHEL/CentOS/Ubuntu/AWS AMI):

*Hardware details (for performance issues)*          Delete if unneeded
Platform (physical/VM/cloud instance type/docker):
Hardware: sockets= cores= hyperthreading= memory=
Disks: (SSD/HDD, count)

**Comment by bhalevy** [comment] 2019-01-01 19:37
9223372036854775808 == 0x8000000000000000 can result from dividing by zero in iotune io_worker::get_io_rates and I'll add an exception in this case, though this might not be the root cause. FWIW, the request issuers use dma_{read,write} respectively and I don't see why an exception there would be intercepted and ignored.

**Comment by glommer** [comment] 2019-01-10 22:38
@bhalevy wasn't this fixed?

**Comment by bhalevy** [comment] 2019-01-13 12:13
@glommer I suspect that the uninitialized members that were fixed 02372fc6cdfa42575c5a9123b0854213c2431d02 could have been the culprit.

**Comment by avikivity** [comment] 2019-01-13 12:39
but those were only a problem for the write bandwidth

**Comment by bhalevy** [comment] 2019-01-13 12:48
Not only.  Also in write_random_data and read_random_data.

**Comment by avikivity** [comment] 2019-01-13 12:53
There, io_rates is value-initialized, which causes its members to be zero-initialized.

**Comment by slivne** [comment] 2019-06-20 09:34
@bhalevy is this fixed now :)

**Comment by bhalevy** [comment] 2019-06-23 14:03
> @bhalevy is this fixed now :)

@slivne I don't think we really got to the bottom of it, so I can't say for sure it's fixed. However, it was never reproduced so I think we can close it and reopen if it's ever encountered again.

**Comment by tzach** [comment] 2019-06-24 07:31
Closing, until we have new evidence

**Closed by tzach** 2019-06-24 07:31 UTC
Labels: GCE, onboarding
