### ISSUE TITLE
exception during mutation write to <node_ip>: std::bad_alloc (std::bad_alloc)

### ISSUE THREAD

**Issue by dkropachev** [scylladb/scylla#5497] opened 2019-12-18 12:56 UTC
Scylla version (or git commit hash): scylla-3.2.rc3-0.20191215.39b17be5620.el7.x86_64
Jenkins job: https://jenkins.scylladb.com/view/scylla-3.2/job/scylla-3.2/view/scylla-3.2-test/job/longevity/job/longevity-multi-keyspaces-60h/2/
test_name: 'longevity_test.LongevityTest.test_custom_time'
test_config: 'test-cases/longevity/longevity-multi-keyspaces.yaml'
Cluster size: 10
OS (RHEL/CentOS/Ubuntu/AWS AMI): (AWS region=eu-west-1) jenkins-scylla-3.2-ami-test-24-24 (ami-0cab4c6eceb3249ac)
Graphana snapshot: https://snapshot.raintank.io/dashboard/snapshot/QHdBrD3r2ccVYOAJnskFTaWF4YZKqwmU

sct log:
`
(DatabaseLogEvent Severity.CRITICAL): type=DATABASE_ERROR regex=Exception  line_number=875962 node=Node longevity-1000-keyspaces-3-2-db-node-71b42f6e-4 [54.77.228.234 | 10.0.196.191] (seed: False)
2019-12-18T06:05:40+00:00  ip-10-0-196-191 !ERR     | scylla: [shard 1] storage_proxy - exception during mutation write to 10.0.196.191: std::bad_alloc (std::bad_alloc)
`

db logs:
`
Dec 18 05:23:48 ip-10-0-196-191 scylla: [shard 0] compaction - Resharded 1 sstables to [/var/lib/scylla/data/keyspace3/standard1-b1844460204111eaa31500000000000c/mc-1252-big-Data.db:level=0, /var/lib/scylla/data/keyspace3/standard1-b1844460204111eaa31500000000000c/mc-1253-big-Data.db:level=0, /var/lib/scylla/data/keyspace3/standard1-b1844460204111eaa31500000000000c/mc-1284-big-Data.db:level=0, /var/lib/scylla/data/keyspace3/standard1-b1844460204111eaa31500000000000c/mc-1285-big-Data.db:level=0, /var/lib/scylla/data/keyspace3/standard1-b1844460204111eaa31500000000000c/mc-1316-big-Data.db:level=0, /var/lib/scylla/data/keyspace3/standard1-b1844460204111eaa31500000000000c/mc-1287-big-Data.db:level=0, /var/lib/scylla/data/keyspace3/standard1-b1844460204111eaa31500000000000c/mc-1348-big-Data.db:level=0, /var/lib/scylla/data/keyspace3/standard1-b1844460204111eaa31500000000000c/mc-1349-big-Data.db:level=0, ]. 22292051 bytes to 26935913 (~120% of original) in 1113ms = 23.08MB/s. ~85632 total partitions merged to 85524.
Dec 18 05:23:48 ip-10-0-196-191 scylla: [shard 9] compaction - Resharding [/var/lib/scylla/data/keyspace347/standard1-c93cc880205e11eaac0400000000000e/mc-600-big-Data.db:level=0, ]
Dec 18 05:23:48 ip-10-0-196-191 scylla: [shard 1] compaction - Resharding [/var/lib/scylla/data/keyspace347/standard1-c93cc880205e11eaac0400000000000e/mc-715-big-Data.db:level=0, ]
Dec 18 05:23:48 ip-10-0-196-191 scylla: [shard 3] compaction - Resharding [/var/lib/scylla/data/keyspace347/standard1-c93cc880205e11eaac0400000000000e/mc-636-big-Data.db:level=0, ]
Dec 18 05:23:48 ip-10-0-196-191 scylla: [shard 0] compaction - Resharding [/var/lib/scylla/data/keyspace347/standard1-c93cc880205e11eaac0400000000000e/mc-719-big-Data.db:level=0, ]
Dec 18 05:23:48 ip-10-0-196-191 scylla: [shard 25] compaction - Resharding [/var/lib/scylla/data/keyspace347/standard1-c93cc880205e11eaac0400000000000e/mc-665-big-Data.db:level=0, ]
Dec 18 05:23:48 ip-10-0-196-191 scylla: [shard 17] compaction - Resharding [/var/lib/scylla/data/keyspace347/standard1-c93cc880205e11eaac0400000000000e/mc-613-big-Data.db:level=0, ]
Dec 18 05:23:48 ip-10-0-196-191 scylla: [shard 5] compaction - Resharding [/var/lib/scylla/data/keyspace347/standard1-c93cc880205e11eaac0400000000000e/mc-651-big-Data.db:level=0, ]
Dec 18 05:23:48 ip-10-0-196-191 scylla: [shard 26] compaction - Resharding [/var/lib/scylla/data/keyspace347/standard1-c93cc880205e11eaac0400000000000e/mc-656-big-Data.db:level=0, ]
Dec 18 05:23:48 ip-10-0-196-191 scylla: [shard 28] compaction - Resharding [/var/lib/scylla/data/keyspace347/standard1-c93cc880205e11eaac0400000000000e/mc-671-big-Data.db:level=0, ]
Dec 18 05:23:48 ip-10-0-196-191 scylla: [shard 12] compaction - Resharding [/var/lib/scylla/data/keyspace347/standard1-c93cc880205e11eaac0400000000000e/mc-723-big-Data.db:level=0, ]
Dec 18 05:23:48 ip-10-0-196-191 scylla: [shard 18] compaction - Resharding [/var/lib/scylla/data/keyspace347/standard1-c93cc880205e11eaac0400000000000e/mc-707-big-Data.db:level=0, ]
Dec 18 05:23:48 ip-10-0-196-191 scylla: [shard 23] compaction - Resharding [/var/lib/scylla/data/keyspace347/standard1-c93cc880205e11eaac0400000000000e/mc-650-big-Data.db:level=0, ]
Dec 18 05:23:48 ip-10-0-196-191 scylla: [shard 20] compaction - Resharding [/var/lib/scylla/data/keyspace347/standard1-c93cc880205e11eaac0400000000000e/mc-702-big-Data.db:level=0, ]
Dec 18 05:23:48 ip-10-0-196-191 scylla: [shard 27] compaction - Resharding [/var/lib/scylla/data/keyspace347/standard1-c93cc880205e11eaac0400000000000e/mc-609-big-Data.db:level=0, ]
Dec 18 05:23:48 ip-10-0-196-191 scylla: [shard 16] compaction - Resharding [/var/lib/scylla/data/keyspace347/standard1-c93cc880205e11eaac0400000000000e/mc-661-big-Data.db:level=0, ]
Dec 18 05:23:48 ip-10-0-196-191 scylla: [shard 29] compaction - Resharding [/var/lib/scylla/data/keyspace347/standard1-c93cc880205e11eaac0400000000000e/mc-718-big-Data.db:level=0, ]
Dec 18 05:23:48 ip-10-0-196-191 scylla: [shard 2] compaction - Resharding [/var/lib/scylla/data/keyspace347/standard1-c93cc880205e11eaac0400000000000e/mc-640-big-Data.db:level=0, ]
Dec 18 05:23:48 ip-10-0-196-191 scylla: [shard 8] compaction - Resharding [/var/lib/scylla/data/keyspace347/standard1-c93cc880205e11eaac0400000000000e/mc-714-big-Data.db:level=0, ]
Dec 18 05:23:48 ip-10-0-196-191 scylla: [shard 19] compaction - Resharding [/var/lib/scylla/data/keyspace347/standard1-c93cc880205e11eaac0400000000000e/mc-634-big-Data.db:level=0, ]
Dec 18 05:23:48 ip-10-0-196-191 scylla: [shard 24] compaction - Resharding [/var/lib/scylla/data/keyspace347/standard1-c93cc880205e11eaac0400000000000e/mc-618-big-Data.db:level=0, ]
Dec 18 05:23:48 ip-10-0-196-191 scylla: [shard 15] compaction - Resharding [/var/lib/scylla/data/keyspace347/standard1-c93cc880205e11eaac0400000000000e/mc-614-big-Data.db:level=0, ]
Dec 18 05:23:48 ip-10-0-196-191 scylla: [shard 6] compaction - Resharding [/var/lib/scylla/data/keyspace347/standard1-c93cc880205e11eaac0400000000000e/mc-698-big-Data.db:level=0, ]
Dec 18 05:23:48 ip-10-0-196-191 scylla: [shard 10] compaction - Resharding [/var/lib/scylla/data/keyspace347/standard1-c93cc880205e11eaac0400000000000e/mc-717-big-Data.db:level=0, ]
Dec 18 05:23:48 ip-10-0-196-191 scylla: [shard 21] compaction - Resharding [/var/lib/scylla/data/keyspace347/standard1-c93cc880205e11eaac0400000000000e/mc-736-big-Data.db:level=0, ]
Dec 18 05:23:48 ip-10-0-196-191 scylla: [shard 7] compaction - Resharding [/var/lib/scylla/data/keyspace347/standard1-c93cc880205e11eaac0400000000000e/mc-622-big-Data.db:level=0, ]
Dec 18 05:23:48 ip-10-0-196-191 scylla: [shard 14] compaction - Resharding [/var/lib/scylla/data/keyspace347/standard1-c93cc880205e11eaac0400000000000e/mc-799-big-Data.db:level=0, ]
Dec 18 05:23:48 ip-10-0-196-191 scylla: [shard 13] compaction - Resharding [/var/lib/scylla/data/keyspace347/standard1-c93cc880205e11eaac0400000000000e/mc-705-big-Data.db:level=0, ]
Dec 18 05:23:48 ip-10-0-196-191 scylla: [shard 4] compaction - Resharding [/var/lib/scylla/data/keyspace347/standard1-c93cc880205e11eaac0400000000000e/mc-692-big-Data.db:level=0, ]
Dec 18 05:23:48 ip-10-0-196-191 scylla: [shard 11] compaction - Resharding [/var/lib/scylla/data/keyspace347/standard1-c93cc880205e11eaac0400000000000e/mc-623-big-Data.db:level=0, ]
Dec 18 05:23:48 ip-10-0-196-191 scylla: [shard 22] compaction - Resharding [/var/lib/scylla/data/keyspace347/standard1-c93cc880205e11eaac0400000000000e/mc-697-big-Data.db:level=0, ]
Dec 18 05:23:49 ip-10-0-196-191 scylla: [shard 8] storage_proxy - exception during mutation write to 10.0.196.191: std::bad_alloc (std::bad_alloc)
Dec 18 05:23:49 ip-10-0-196-191 scylla: [shard 20] storage_proxy - Failed to apply mutation from 10.0.26.64#20: std::bad_alloc (std::bad_alloc)
Dec 18 05:23:49 ip-10-0-196-191 scylla: [shard 16] storage_proxy - Failed to apply mutation from 10.0.176.133#16: std::bad_alloc (std::bad_alloc)
Dec 18 05:23:49 ip-10-0-196-191 scylla: [shard 24] storage_proxy - Failed to apply mutation from 10.0.176.133#24: std::bad_alloc (std::bad_alloc)
Dec 18 05:23:49 ip-10-0-196-191 scylla: [shard 23] storage_proxy - Failed to apply mutation from 10.0.26.64#23: std::bad_alloc (std::bad_alloc)
`

**Comment by roydahan** [comment] 2019-12-18 13:17
probably a dup of https://github.com/scylladb/scylla/issues/4951

**Comment by slivne** [comment] 2019-12-19 11:54
so is this the same scenario as in #4951 ?

**Comment by roydahan** [comment] 2019-12-19 12:36
> so is this the same scenario as in #4951 ?

Yes

**Comment by bhalevy** [comment] 2019-12-26 11:48
Duplicate of #4951

**Closed by bhalevy** 2019-12-26 11:48 UTC
Labels: longevity
