### ISSUE TITLE
scylla_io_setup does not work

### ISSUE THREAD

**Issue by liurenjie1024** [scylladb/scylla#1232] opened 2016-05-04 01:15 UTC
## Installation details
Scylla version (or git commit hash): 1.0.2-20160423.60307f6.el7.centos
Cluster size: 2
OS (RHEL/CentOS/Ubuntu/AWS AMI): CentOS Linux release 7.0.1406 (Core)

## Hardware details (for performance issues)
Platform (physical/VM/cloud instance type/docker):physical
Hardware: sockets=2 cores=24 hyperthreading= 24 memory=128G
Disks: (SSD/HDD, count) HDD, 1

I run scylla_io_setup and nothing happens: no coredump, no changes in /etc/scylla.d/io.conf, no output in console.

I've disabled developer mode and nothing changes.

**Comment by penberg** [comment] 2016-05-04 05:47
Ping @glommer @syuu1228

**Comment by syuu1228** [comment] 2016-05-04 08:51
I'm not able to reproduce the issue on CentOS7 instance with scylla-server-1.0.2...

**Comment by penberg** [comment] 2016-05-04 08:53
I suspect it's either https://github.com/scylladb/seastar/issues/115 or https://github.com/scylladb/seastar/issues/129 but it's odd that there's no core dump. @liurenjie1024, can you try running ``iotune`` manually?

**Comment by syuu1228** [comment] 2016-05-04 09:30
It coredumps, but I still can see permission denied error correctly, not silently failed.

```
[centos@ip-172-30-0-159 ~]$ /usr/lib/scylla/scylla_io_setup 
terminate called after throwing an instance of 'std::system_error'
  what():  open: Permission denied
/usr/lib/scylla/scylla_io_setup: line 80: 17158 Aborted                 (core dumped) iotune --evaluation-directory /var/lib/scylla --format envfile --options-file /etc/scylla.d/io.conf $CPUSET
/var/lib/scylla did not pass validation tests, it may not be on XFS and/or has limited disk space.
This is a non-supported setup, and performance is expected to be very bad.
For better performance, placing your data on XFS-formatted directories is required.
 To override this error, see the developer_mode configuration option.
[centos@ip-172-30-0-159 ~]$ iotune
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::program_options::required_option> >'
  what():  the option '--evaluation-directory' is required but missing
Aborted (core dumped)
[centos@ip-172-30-0-159 ~]$ iotune --evaluation-directory /var/lib/scylla/
terminate called after throwing an instance of 'std::system_error'
  what():  open: Permission denied
Aborted (core dumped)
```

**Comment by dorlaor** [comment] 2016-05-04 10:35
@syuu1228 you got a core since it needs root permission (at least for the default path).

I run it on my desktop (HDD) and got this:

sudo  build/release/apps/iotune/iotune --evaluation-directory /tmp/xfs --format envfile --options-file io.conf 
Generating evaluation file sized 10GB... stopped early due to disk space issues. Will continue but accuracy may suffer.
9.94373GB written in 20 seconds
Refining search for maximum. So far, 18692 IOPS
Maximum throughput: 18692 IOPS
Recommended --max-io-requests: 153
terminate called after throwing an instance of 'boost::filesystem::filesystem_error'
  what():  boost::filesystem::create_directory: No such file or directory
Aborted

It means it did work (minus the last issue which may just be the config file location)

**Comment by liurenjie1024** [comment] 2016-05-06 03:27
@penberg I've run iotune --evaluation-directory /var/lib --format envfile --options-file /tmp/io.conf and got the following message:
`File system on /var/lib is not qualified for seastar AIO; see http://docs.scylladb.com/kb/kb-fs-not-qualified-aio/ for details`

I've checked the page and I think this is caused by linux version. The kernel version is 3.10.0, which is older than required.

**Comment by dorlaor** [comment] 2016-05-06 05:49
Are you using XFS on this directory plus rhel/centos 7.2?

**Comment by liurenjie1024** [comment] 2016-05-06 06:46
@dorlaor Yes it xfs, but centos version is 7.0

**Comment by dorlaor** [comment] 2016-05-06 06:53
That's the issue, xfs had a performance bug which was fixed in 7,2

**Comment by tzach** [comment] 2016-05-06 07:49
The problem is users does not get any feedback from scylla_io_setup, which mask iotune errors

**Comment by eyalgutkind** [comment] 2016-05-10 00:36
Based on the above, executing scylla_io_setup stalls for few minutes and eventually exited as follow:
Is it due to the disk space issue or something else...

Generating evaluation file sized 10GB... stopped early due to disk space issues. Will continue but accuracy may suffer.
6.54053GB written in 78 seconds
Refining search for maximum. So far, 3616 IOPS
Maximum throughput: 3616 IOPS
IOtune timed out before it could finish. An estimate will be provided but accuracy may suffer
Recommended --max-io-requests: 315
Written the above values to /etc/scylla.d/io.conf

**Comment by tzach** [comment] 2016-06-07 09:14
@glommer any update on this issue?

**Comment by glommer** [comment] 2016-06-07 13:07
On Tue, Jun 7, 2016 at 5:14 AM, Tzach Livyatan <notifications@github.com>
wrote:

> @glommer <https://github.com/glommer> any update on this issue?
>

Not from my side, but from what I can see, iotune itself seems to be
working as expected.

**Comment by tzach** [comment] 2016-06-21 08:47
I'm closing this issue, as scylla_io_setup did report the right error.

**Closed by tzach** 2016-06-21 08:47 UTC
Labels: bug, high, onboarding
