### ISSUE TITLE
Scylla 4.1 install on Debian 10 fails with "scylla : Depends: scylla-jmx but it is not going to be instal"

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#6865] opened 2020-07-16 18:16 UTC
*Installation details*
Scylla version (or git commit hash): 4.1
Cluster size: 1
OS (RHEL/CentOS/Ubuntu/AWS AMI): Debian 10

Following the instructions on https://www.scylladb.com/download/?platform=debian-10&version=scylla-4.1
I get the following error
```
sudo apt-get install scylla
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:
The following packages have unmet dependencies:
 scylla : Depends: scylla-jmx but it is not going to be instal
```

**Comment by tzach** [comment] 2020-07-16 18:24
@syuu1228 this seems very similar to https://github.com/scylladb/scylla/issues/2914

**Comment by avikivity** [comment] 2020-07-17 05:47
Duplicate of https://github.com/scylladb/scylla-jmx/issues/110

**Closed by avikivity** 2020-07-17 05:47 UTC
