### ISSUE TITLE
heat_weighted_load_balancing_cl_TWO_test failed: std::runtime_error (sstable inactive read queue overloaded)

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#4377] opened 2019-03-30 20:06 UTC
scylla version 98cb7d145bf11fc9526dc3fc7fe3e246bbb9bcf6

Seen in [dtest-release/72/testReport/heat_weighted_load_balancing/HeatWeightedLB/heat_weighted_load_balancing_cl_TWO_test](http://jenkins.cloudius-systems.com:8080/view/master/job/scylla-master/job/dtest-release/72/testReport/heat_weighted_load_balancing/HeatWeightedLB/heat_weighted_load_balancing_cl_TWO_test/):
```
Unexpected error in node1 node log: ['ERROR 2019-03-30 00:34:36,770 [shard 1] storage_proxy - Exception when communicating with 127.0.74.2: std::runtime_error (sstable inactive read queue overloaded)
```

node logs weren't kept due to scylladb/scylla-dtest#924

**Comment by bhalevy** [comment] 2019-03-30 20:08
Similar issue seen in [dtest-release/72/testReport/resharding_test/ReshardingTest_nodes4_with_SizeTieredCompactionStrategy/resharding_by_smp_decrease_test](http://jenkins.cloudius-systems.com:8080/view/master/job/scylla-master/job/dtest-release/72/testReport/resharding_test/ReshardingTest_nodes4_with_SizeTieredCompactionStrategy/resharding_by_smp_decrease_test/)

**Comment by bhalevy** [comment] 2019-04-02 11:08
Seen on multiple nodes in [dtest-release/75/testReport/resharding_test/ReshardingTest_nodes4_with_SizeTieredCompactionStrategy/resharding_by_smp_decrease_test](http://jenkins.cloudius-systems.com:8080/view/master/job/scylla-master/job/dtest-release/75/testReport/resharding_test/ReshardingTest_nodes4_with_SizeTieredCompactionStrategy/resharding_by_smp_decrease_test/):
```
Stacktrace
  File "/usr/lib64/python2.7/unittest/case.py", line 396, in run
    self.tearDown()
  File "/jenkins/workspace/scylla-master/dtest-release@2/scylla-dtest/dtest.py", line 725, in tearDown
    raise AssertionError('Unexpected error in %s node log: %s' % (node.name, errors))

Unexpected error in node1 node log: ['ERROR 2019-03-31 22:01:12,893 [shard 0] storage_proxy - Exception when communicating with 127.0.34.1: std::runtime_error (sstable inactive read queue overloaded)
```

[node1.log](http://jenkins.cloudius-systems.com:8080/view/master/job/scylla-master/job/dtest-release/75/artifact/logs-release.2/1554069680404_resharding_test.ReshardingTest_nodes4_with_SizeTieredCompactionStrategy.resharding_by_smp_decrease_test/node1.log):
```
INFO  2019-03-31 22:00:55,809 [shard 0] storage_service - Thrift server listening on 127.0.34.1:9160 ...
INFO  2019-03-31 22:00:55,809 [shard 0] init - Scylla version 666.development-0.20190331.77a0d5c5d initialization completed.
ERROR 2019-03-31 22:01:12,893 [shard 0] storage_proxy - Exception when communicating with 127.0.34.1: std::runtime_error (sstable inactive read queue overloaded)
```

@denesb care to look into this?

**Comment by denesb** [comment] 2019-04-02 14:29
These errors usually mean that the disk is overloaded and can't keep up with the read request rate. In this particular case it appears the reads are coming so fast that the read queue is filled before the semaphore timeout can kick in. Do these tests use `cassandra_stress` to produce a read load?

**Comment by bhalevy** [comment] 2019-04-02 14:58
> Do these tests use `cassandra_stress` to produce a read load?

Yes, they do.

**Comment by denesb** [comment] 2019-04-02 15:31
This is fragile. A load that was light yesterday can be unbearably heavy today due to the unpredictable load on the build machines.

**Comment by bhalevy** [comment] 2019-04-02 16:19
We're seeing this more frequently recently for some reason.  I wonder if anything changed on the scylla side to explain this.

**Comment by denesb** [comment] 2019-04-03 12:02
@bhalevy nothing comes to mind (if memory serves, the last patches to related areas were merged in January). This can also be caused by environment change, e.g. more heavily loaded build machines.

**Comment by bhalevy** [comment] 2019-04-03 12:23
dtest-release runs alone on monster/godzilla so there shouldn't be any background load on these machines

**Closed** 2019-04-11 08:01 UTC
Labels: dtest
