### ISSUE TITLE
Node went into endless reshape after other node was updated, rolled back and updated once again

### ISSUE THREAD

**Issue by dkropachev** [scylladb/scylla#9569] opened 2021-11-01 20:49 UTC
We have rolling upgrade test procedure, it is done in such a way that time to time it can run update procedure on one node twice.
And it is exactly what happened.
node-4 was updated
node-2 was updated
node-2 was rolled back to prior version
node-2 was updated again

right after node-2 was updated second time node-4 started eating 100% of CPU and throwing following log lines endlessly:

```
2021-10-29T08:48:44+00:00  ip-10-0-1-86 !INFO    | scylla:  [shard 6] compaction - [Reshape ks1.table1_scylla_cdc_log 4a18c9a0-388f-11ec-aa05-83b01a152ad0] Reshaped 1 sstables to [/var/lib/scylla/data/ks1/table1_scylla_cdc_log-bf6c0180386d11ec90a6cf4aa173f529/md-66718-big-Data.db:level=0]. 41MB to 41MB (~100% of original) in 1081ms = 38MB/s. ~1813376 total partitions merged to 1539880.
2021-10-29T08:48:44+00:00  ip-10-0-1-86 !INFO    | scylla:  [shard 6] compaction - [Reshape ks1.table1_scylla_cdc_log 4a18c9a0-388f-11ec-aa05-83b01a152ad0] Reshaping [/var/lib/scylla/data/ks1/table1_scylla_cdc_log-bf6c0180386d11ec90a6cf4aa173f529/md-66718-big-Data.db:level=0:origin=reshape]
2021-10-29T08:48:44+00:00  ip-10-0-1-86 !INFO    | scylla:  [shard 0] compaction - [Reshape ks1.table1_scylla_cdc_log 49e02d70-388f-11ec-b0ec-83af1a152ad0] Reshaped 1 sstables to [/var/lib/scylla/data/ks1/table1_scylla_cdc_log-bf6c0180386d11ec90a6cf4aa173f529/md-66120-big-Data.db:level=0]. 42MB to 42MB (~100% of original) in 1086ms = 38MB/s. ~1802752 total partitions merged to 1519800.
2021-10-29T08:48:44+00:00  ip-10-0-1-86 !INFO    | scylla:  [shard 0] compaction - [Reshape ks1.table1_scylla_cdc_log 49e02d70-388f-11ec-b0ec-83af1a152ad0] Reshaping [/var/lib/scylla/data/ks1/table1_scylla_cdc_log-bf6c0180386d11ec90a6cf4aa173f529/md-66120-big-Data.db:level=0:origin=reshape]
```

*Installation details*
Initial scylla version (or git commit hash): 4.5.1-0.20211024.4c0eac049 with build-id e0df888020bbfef43aee10264ff14c85581609f7 (ami-0b7f3aefada916c13)
Target scylla version (or git commit hash): http://downloads.scylladb.com/unstable/scylla/master/deb/unified/2021-10-29T01%3A01%3A05Z/
Cluster size: 4
OS (RHEL/CentOS/Ubuntu/AWS AMI): AWS

*Logs*
db-cluster  | https://cloudius-jenkins-test.s3.amazonaws.com/f196f67a-0051-4c5d-9583-885b0d08e597/20211029_085109/db-cluster-f196f67a.tar.gz  |
monitor-set | https://cloudius-jenkins-test.s3.amazonaws.com/f196f67a-0051-4c5d-9583-885b0d08e597/20211029_085109/monitor-set-f196f67a.tar.gz |
loader-set  | https://cloudius-jenkins-test.s3.amazonaws.com/f196f67a-0051-4c5d-9583-885b0d08e597/20211029_085109/loader-set-f196f67a.tar.gz  |
sct-runner  | https://cloudius-jenkins-test.s3.amazonaws.com/f196f67a-0051-4c5d-9583-885b0d08e597/20211029_085109/sct-runner-f196f67a.tar.gz

**Comment by dkropachev** [comment] 2021-11-02 09:15
The turquoise line is node-4 

![Screenshot from 2021-11-01 23-04-56](https://user-images.githubusercontent.com/40304587/139818691-bf01d3d1-6129-49e0-9ebc-125883012ed9.png)

**Comment by slivne** [comment] 2021-11-03 12:20
@raphaelsc  according to qa a node is stuck following reshape at reshape - can you please check

**Comment by raphaelsc** [comment] 2021-11-09 00:30
sha1 is 3c0a48ac38c5d142c942699ed53558cb528fea2e, looks like a regression in master which is already fixed. @dkropachev please retry this test (picking latest master for target version instead) and tell me if the problem is gone.

**Comment by raphaelsc** [comment] 2021-11-26 19:53
@dkropachev ping

**Comment by raphaelsc** [comment] 2021-11-26 19:54
closed accidentally, reopened.

**Comment by dkropachev** [comment] 2021-11-26 20:41
Test passed on multiple builds after the fix

**Comment by raphaelsc** [comment] 2021-11-26 22:21
Great. so closing this issue. thanks for the confirmation, @dkropachev

**Closed** 2021-11-26 22:21 UTC
Labels: bug, compaction, master/high
