### ISSUE TITLE
scylla-jmx is wrongly moved to /usr/lib/scylla.old/

### ISSUE THREAD

**Issue by amoskong** [scylladb/scylla#4585] opened 2019-06-21 04:05 UTC
*Installation details*
Scylla version (or git commit hash): scylla 666.development-0.20190620.8672eddff-1
Cluster size: 1
OS (RHEL/CentOS/Ubuntu/AWS AMI): Ubuntu 18.04

I think it's an regression bug introduced by https://github.com/scylladb/scylla/commit/f582a759ee3

```
scylla-test@amos-ubuntu18:/usr/lib$ dpkg -l |grep scylla
ii  scylla                         666.development-0.20190620.8672eddff-1      amd64        Scylla database metapackage
ii  scylla-conf                    666.development-0.20190620.8672eddff-1      amd64        Scylla database main configuration file
ii  scylla-jmx                     666.development-20190620.512638e-1          all          Scylla JMX server binaries
ii  scylla-kernel-conf             666.development-0.20190620.8672eddff-1      amd64        Scylla kernel tuning configuration
ii  scylla-python3                 3.7.2-0.20190620.8672eddff-1                amd64        A standalone python3 interpreter that can be moved around different Linux machines
ii  scylla-server                  666.development-0.20190620.8672eddff-1      amd64        Scylla database server binaries
ii  scylla-tools                   666.development-20190620.9dc9cb5a39-1       all          Scylla database tools
ii  scylla-tools-core              666.development-20190620.9dc9cb5a39-1       all          Scylla database tools core files

```

```
scylla-test@amos-ubuntu18:/usr/lib$ sudo systemctl status scylla-server
● scylla-server.service - Scylla Server
   Loaded: loaded (/lib/systemd/system/scylla-server.service; enabled; vendor preset: enabled)
   Active: active (running) since Fri 2019-06-21 03:54:28 UTC; 28s ago
  Process: 13344 ExecStopPost=/opt/scylladb/scripts/scylla_stop (code=exited, status=0/SUCCESS)
  Process: 13351 ExecStartPre=/opt/scylladb/scripts/scylla_prepare (code=exited, status=0/SUCCESS)
 Main PID: 13368 (scylla)
   Status: "serving"
    Tasks: 3 (limit: 4401)
   CGroup: /system.slice/scylla-server.service
           └─13368 /usr/bin/scylla /opt/scylladb/bin/../libexec/scylla.bin --log-to-syslog 1 --log-to-stdout 0 --default-log-level info 

```

* Description: scylla-jmx was installed to wrong directory (/usr/lib/scylla.old), it's a clean environment.

```
scylla-test@amos-ubuntu18:/usr/lib$ sudo systemctl status scylla-server
● scylla-server.service - Scylla Server
   Loaded: loaded (/lib/systemd/system/scylla-server.service; enabled; vendor preset: enabled)
   Active: active (running) since Fri 2019-06-21 03:54:28 UTC; 28s ago
  Process: 13344 ExecStopPost=/opt/scylladb/scripts/scylla_stop (code=exited, status=0/SUCCESS)
  Process: 13351 ExecStartPre=/opt/scylladb/scripts/scylla_prepare (code=exited, status=0/SUCCESS)
 Main PID: 13368 (scylla)
   Status: "serving"
    Tasks: 3 (limit: 4401)
   CGroup: /system.slice/scylla-server.service
           └─13368 /usr/bin/scylla /opt/scylladb/bin/../libexec/scylla.bin --log-to-syslog 1 --log-to-stdout 0 --default-log-level info -



scylla-test@amos-ubuntu18:/usr/lib$ sudo systemctl status scylla-jmx 
● scylla-jmx.service - Scylla JMX
   Loaded: loaded (/lib/systemd/system/scylla-jmx.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Fri 2019-06-21 03:54:28 UTC; 16s ago
  Process: 13379 ExecStart=/usr/lib/scylla/jmx/scylla-jmx $SCYLLA_JMX_PORT $SCYLLA_API_PORT $SCYLLA_API_ADDR $SCYLLA_JMX_ADDR $SCYLLA_JMX
 Main PID: 13379 (code=exited, status=203/EXEC)

Jun 21 03:54:28 amos-ubuntu18 systemd[1]: Started Scylla JMX.
Jun 21 03:54:28 amos-ubuntu18 systemd[1]: scylla-jmx.service: Main process exited, code=exited, status=203/EXEC
Jun 21 03:54:28 amos-ubuntu18 systemd[1]: scylla-jmx.service: Failed with result 'exit-code'.
```

```
scylla-test@amos-ubuntu18:/usr/lib$ sudo find .|grep scylla
scylla-test@amos-ubuntu18:/usr/lib$ sudo apt-get install scylla
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages were automatically installed and are no longer required:
  apport-symptoms grub-pc-bin python3-apport python3-httplib2 python3-problem-report python3-requests-unixsocket python3-systemd
Use 'sudo apt autoremove' to remove them.
The following additional packages will be installed:
  scylla-conf scylla-jmx scylla-kernel-conf scylla-python3 scylla-server scylla-tools scylla-tools-core
The following NEW packages will be installed:
  scylla scylla-conf scylla-jmx scylla-kernel-conf scylla-python3 scylla-server scylla-tools scylla-tools-core
0 upgraded, 8 newly installed, 0 to remove and 17 not upgraded.
Need to get 0 B/87.0 MB of archives.
After this operation, 276 MB of additional disk space will be used.
Do you want to continue? [Y/n] y
Selecting previously unselected package scylla-conf.
(Reading database ... 62798 files and directories currently installed.)
Preparing to unpack .../0-scylla-conf_666.development-0.20190620.8672eddff-1_amd64.deb ...
Unpacking scylla-conf (666.development-0.20190620.8672eddff-1) ...
Selecting previously unselected package scylla-python3.
Preparing to unpack .../1-scylla-python3_3.7.2-0.20190620.8672eddff-1_amd64.deb ...
Unpacking scylla-python3 (3.7.2-0.20190620.8672eddff-1) ...
Selecting previously unselected package scylla-server.
Preparing to unpack .../2-scylla-server_666.development-0.20190620.8672eddff-1_amd64.deb ...
Unpacking scylla-server (666.development-0.20190620.8672eddff-1) ...
Selecting previously unselected package scylla-jmx.
Preparing to unpack .../3-scylla-jmx_666.development-20190620.512638e-1_all.deb ...
Unpacking scylla-jmx (666.development-20190620.512638e-1) ...
Selecting previously unselected package scylla-tools-core.
Preparing to unpack .../4-scylla-tools-core_666.development-20190620.9dc9cb5a39-1_all.deb ...
Unpacking scylla-tools-core (666.development-20190620.9dc9cb5a39-1) ...
Selecting previously unselected package scylla-tools.
Preparing to unpack .../5-scylla-tools_666.development-20190620.9dc9cb5a39-1_all.deb ...
Unpacking scylla-tools (666.development-20190620.9dc9cb5a39-1) ...
Selecting previously unselected package scylla-kernel-conf.
Preparing to unpack .../6-scylla-kernel-conf_666.development-0.20190620.8672eddff-1_amd64.deb ...
Unpacking scylla-kernel-conf (666.development-0.20190620.8672eddff-1) ...
Selecting previously unselected package scylla.
Preparing to unpack .../7-scylla_666.development-0.20190620.8672eddff-1_amd64.deb ...
Unpacking scylla (666.development-0.20190620.8672eddff-1) ...
Processing triggers for ureadahead (0.100.0-21) ...
Setting up scylla-conf (666.development-0.20190620.8672eddff-1) ...
Setting up scylla-python3 (3.7.2-0.20190620.8672eddff-1) ...
Setting up scylla-server (666.development-0.20190620.8672eddff-1) ...
scylla:x:112:116::/var/lib/scylla:/usr/sbin/nologin
scylla:x:116:
Setting up scylla-kernel-conf (666.development-0.20190620.8672eddff-1) ...
kernel.sched_tunable_scaling = 0
kernel.sched_min_granularity_ns = 500000
kernel.sched_wakeup_granularity_ns = 450000
kernel.sched_latency_ns = 1000000
kernel.sched_autogroup_enabled = 0
kernel.numa_balancing = 0
fs.aio-max-nr = 1048576
Setting up scylla-jmx (666.development-20190620.512638e-1) ...
Setting up scylla-tools-core (666.development-20190620.9dc9cb5a39-1) ...
Setting up scylla-tools (666.development-20190620.9dc9cb5a39-1) ...
Setting up scylla (666.development-0.20190620.8672eddff-1) ...
scylla-test@amos-ubuntu18:/usr/lib$ ls |grep scylla
scylla
scylla.old
scylla-test@amos-ubuntu18:/usr/lib$ find .|grep jmx
./jvm/java-11-openjdk-amd64/conf/management/jmxremote.access
./jvm/java-8-openjdk-amd64/jre/lib/management/jmxremote.password
./jvm/java-8-openjdk-amd64/jre/lib/management/jmxremote.access
./scylla.old/jmx
./scylla.old/jmx/scylla-jmx
./scylla.old/jmx/symlinks
./scylla.old/jmx/symlinks/scylla-jmx
./scylla.old/jmx/scylla-jmx-1.0.jar
```

@syuu1228

**Comment by amoskong** [comment] 2019-06-21 05:00
```
scylla-test@amos-ubuntu18:/usr/lib$ ls -l |grep scylla
lrwxrwxrwx  1 root root     21 Jun 21 04:55 scylla -> /opt/scylladb/scripts
drwxr-xr-x  3 root root   4096 Jun 21 04:55 scylla.old
```

**Comment by slivne** [comment] 2019-06-27 10:08
seems related to #4611 

@avikivity can you provide your view on this - do we need #4611 to release 3.1

**Comment by syuu1228** [comment] 2019-06-28 12:44
Sent "[PATCH scylla 1/2] dist: move /usr/lib/scylla symlink to scylla-compat package" to fix the issue.
@slivne This is not related with 3.1, only master

**Comment by syuu1228** [comment] 2019-06-28 12:46
@slivne both #4585 and #4611 is caused by f582a759ee3, but another issue.
Also #4605 is caused by f582a759ee3.

**Comment by slivne** [comment] 2019-07-08 07:31
based on @syuu1228 input moving this to 3.2

**Comment by amoskong** [comment] 2019-07-08 07:47
Scylla 3.1 artifact-test jobs are all blue:
- http://jenkins.scylladb.com/job/scylla-3.1/job/centos-rpm-test/
- http://jenkins.scylladb.com/job/scylla-3.1/job/ubuntu-deb-18.04-test/
- http://jenkins.scylladb.com/job/scylla-3.1/job/ubuntu-deb-16.04-test/
- http://jenkins.scylladb.com/job/scylla-3.1/job/debian-deb-9-test/

Scylla-3.1 AMI-test: only one instance type failed for env issue (the others work well)
- http://jenkins.scylladb.com/job/scylla-3.1/job/ami-test/

So this problem doesn't effect 3.1

**Comment by eliransin** [comment] 2019-07-10 10:05
I think this is fixed by https://github.com/scylladb/scylla-jmx/commit/f73da49f6218bea09b18d115f623bab2386a13fc ?
@amoskong @syuu1228 ?

**Comment by amoskong** [comment] 2019-07-10 10:13
Do we need to move /usr/lib/scylla/scylla-ami/
to /opt/scylladb/scylla-ami?  @syuu1228 <https://github.com/syuu1228>

**Comment by syuu1228** [comment] 2019-07-10 10:55
@eliransin I think we also need "[PATCH scylla 1/2] dist: move /usr/lib/scylla symlink to scylla-compat package" that I mentioned earlier, the patch still not merged yet.
Without the patch, new jmx package does not have problem since we moved files under /opt/scylladb/jmx on https://github.com/scylladb/scylla-jmx/commit/f73da49f6218bea09b18d115f623bab2386a13fc, but you will see warning message when yum command will remove old jmx package, because scylla-server moves /usr/lib/scylla to /usr/lib/scylla.old before removing old jmx package.

**Comment by syuu1228** [comment] 2019-07-10 10:56
@amoskong You are right, will send fix soon.

**Comment by eliransin** [comment] 2019-07-10 12:03
Thanks @syuu1228 and @amoskong

**Comment by syuu1228** [comment] 2019-07-10 15:22
Patch for AMI sent: [PATCH scylla-ami] dist: merge /usr/lib/scylla to /opt/scylladb

**Comment by bancron** [comment] 2019-10-25 21:12
Hi, I am running into this issue building a deb package from source at https://github.com/scylladb/scylla/commit/8bffb800e19b63be6bb4bc9e9fd90c64f754d023.

Has scylladb/scylla-jmx@f73da49 been patched into this repo yet?

**Closed** 2019-12-30 19:33 UTC
Labels: Backport candidate, onboarding, ubuntu

**Comment by avikivity** [comment] 2020-05-07 15:13
Already backported.
