### ISSUE TITLE
nodetool netstats lies about repair status

### ISSUE THREAD

**Issue by gleb-cloudius** [scylladb/scylla#1868] opened 2016-11-21 12:22 UTC
*Installation details*
Scylla version (or git commit hash): branch-1.4.1

nodetool netstats reports that file is sent/received immediately after streaming starts. It is impossible to monitor how it progress.

```
$ nodetool netstats

Mode: NORMAL
repair-out 2602ff70-afde-11e6-b552-000000000002
    /X.X.X.147
        Sending 1 files, 0 bytes total. Already sent 1 files, 6647515120 bytes total
            txnofile 6647515120/6647515120 bytes(100%) sent to idx:0/X.X.X.147
    /10.10.122.109
        Sending 1 files, 0 bytes total. Already sent 1 files, 6648327810 bytes total
            txnofile 6648327810/6648327810 bytes(100%) sent to idx:0/X.X.X.109
Read Repair Statistics:
Attempted: 275
Mismatch (Blocking): 221887
Mismatch (Background): 0
Pool Name                    Active   Pending      Completed
Commands                        n/a         2       98856256
Responses                       n/a         0        9661301

$ grep stream_session syslog
[shard 0] stream_session - [Stream #2602ff71-afde-11e6-b552-000000000002] Executing streaming plan for repair-in
[shard 0] stream_session - [Stream #2602ff71-afde-11e6-b552-000000000002] Starting streaming to X.X.X.147
[shard 0] stream_session - [Stream #2602ff71-afde-11e6-b552-000000000002] Beginning stream session with X.X.X.147
[shard 0] stream_session - [Stream #2602ff71-afde-11e6-b552-000000000002] Starting streaming to X.X.X.109
[shard 0] stream_session - [Stream #2602ff71-afde-11e6-b552-000000000002] Beginning stream session with X.X.X.109
[shard 0] stream_session - [Stream #2602ff71-afde-11e6-b552-000000000002] Prepare completed with X.X.X.147. Receiving 1, sending 0
[shard 0] stream_session - [Stream #2602ff71-afde-11e6-b552-000000000002] Prepare completed with X.X.X.109. Receiving 1, sending 0
[shard 0] stream_session - [Stream #2602ff71-afde-11e6-b552-000000000002] Session with X.X.X.109 is complete, state=COMPLETE
[shard 0] stream_session - [Stream #2602ff71-afde-11e6-b552-000000000002] Session with X.X.X.147 is complete, state=COMPLETE
[shard 0] stream_session - [Stream #2602ff71-afde-11e6-b552-000000000002] bytes_sent = 0, bytes_received = 32488019875
[shard 0] stream_session - [Stream #2602ff71-afde-11e6-b552-000000000002] All sessions completed, peers={X.X.X.147, X.X.X.109}
[shard 0] stream_session - [Stream #2602ff70-afde-11e6-b552-000000000002] Executing streaming plan for repair-out
[shard 0] stream_session - [Stream #2602ff70-afde-11e6-b552-000000000002] Starting streaming to X.X.X.147
[shard 0] stream_session - [Stream #2602ff70-afde-11e6-b552-000000000002] Beginning stream session with X.X.X.147
[shard 0] stream_session - [Stream #2602ff70-afde-11e6-b552-000000000002] Starting streaming to X.X.X.109
[shard 0] stream_session - [Stream #2602ff70-afde-11e6-b552-000000000002] Beginning stream session with X.X.X.109
[shard 0] stream_session - [Stream #2602ff70-afde-11e6-b552-000000000002] Prepare completed with X.X.X.109. Receiving 0, sending 1
[shard 0] stream_session - [Stream #2602ff70-afde-11e6-b552-000000000002] Prepare completed with X.X.X.147. Receiving 0, sending 1
```

**Comment by slivne** [comment] 2016-11-24 13:25
duplicate of #1244

**Closed by slivne** 2016-11-24 13:25 UTC
Labels: duplicate
