### ISSUE TITLE
oversized allocation: 1610612736 bytes

### ISSUE THREAD

**Issue by lustefaniak** [scylladb/scylla#4103] opened 2019-01-18 08:29 UTC
*Installation details*
Scylla version (or git commit hash): 2.3.1-0.20181021.336c77166
Cluster size: 3
OS (RHEL/CentOS/Ubuntu/AWS AMI): Ubuntu deb package

```
Jan 17 17:34:25 scylla-chronicle-p-1 scylla: message repeated 4 times: [  [shard 0] seastar_memory - oversized allocation: 1610612736 bytes, please report: at   0x7a34d8#012  0x731249#012  0x736a56#012  0x736fa4#012  0x25adbd1#012  0x25ad53f#012  0x1d4b2a6#012  0x1d5eeec#012  0x1d60697#012  0x1d2e2fe#012  0x1e65827#012  0x1e391e2#012  0x1e39a7e#012  0x252b216#012  0x1cbc8d8#012  0x1cbe7d3#012  0x1cbff3b#012  0x1cea889#012  0x1cea544#012  0x1cefc1d#012  0x6ea19c#012  0x587696#012  0x587851#012  0x652737#012  0x785340#012  0x5159b8#012  /lib/x86_64-linux-gnu/libc.so.6+0x2082f#012  0x581ce8]  scylla-chronicle-p-1
Jan 17 17:34:21 scylla-chronicle-p-1 scylla:  [shard 0] seastar_memory - oversized allocation: 1610612736 bytes, please report: at   0x7a34d8#012  0x731249#012  0x736a56#012  0x736fa4#012  0x25adbd1#012  0x25ad53f#012  0x1d4b2a6#012  0x1d5eeec#012  0x1d60697#012  0x1d2e2fe#012  0x1e65827#012  0x1e391e2#012  0x1e39a7e#012  0x252b216#012  0x1cbc8d8#012  0x1cbe7d3#012  0x1cbff3b#012  0x1cea889#012  0x1cea544#012  0x1cefc1d#012  0x6ea19c#012  0x587696#012  0x587851#012  0x652737#012  0x785340#012  0x5159b8#012  /lib/x86_64-linux-gnu/libc.so.6+0x2082f#012  0x581ce8  scylla-chronicle-p-1
Jan 17 17:34:18 scylla-chronicle-p-1 scylla:  [shard 0] seastar_memory - oversized allocation: 1610612736 bytes, please report: at   0x7a34d8#012  0x731249#012  0x736a56#012  0x736fa4#012  0x25adbd1#012  0x25ad53f#012  0x1d4b2a6#012  0x1d5eeec#012  0x1d60697#012  0x1d2e2fe#012  0x1e65827#012  0x1e391e2#012  0x1e39a7e#012  0x252b216#012  0x1cbc8d8#012  0x1cbe7d3#012  0x1cbff3b#012  0x1cea889#012  0x1cea544#012  0x1cefc1d#012  0x6ea19c#012  0x587696#012  0x587851#012  0x652737#012  0x785340#012  0x5159b8#012  /lib/x86_64-linux-gnu/libc.so.6+0x2082f#012  0x581ce8  scylla-chronicle-p-1
Jan 17 17:33:35 scylla-chronicle-p-2 scylla:  [shard 3] seastar_memory - oversized allocation: 805306368 bytes, please report: at   0x7a34d8#012  0x731249#012  0x736a56#012  0x736fa4#012  0x25adbd1#012  0x25ad53f#012  0x1d4b2a6#012  0x1d5eeec#012  0x1d60697#012  0x1d2e2fe#012  0x1e65827#012  0x1e391e2#012  0x1e39a7e#012  0x252b216#012  0x1cbc8d8#012  0x1cbe7d3#012  0x1cbff3b#012  0x1cea889#012  0x1cea544#012  0x1cefc1d#012  0x6ea19c#012  0x587696#012  0x587851#012  0x652737#012  0x6742b2#012  0x72fc5d#012  /lib/x86_64-linux-gnu/libpthread.so.0+0x76b9#012  /lib/x86_64-linux-gnu/libc.so.6+0x10741c  scylla-chronicle-p-2
Jan 17 17:04:54 scylla-chronicle-p-3 scylla:  [shard 7] seastar_memory - oversized allocation: 402653184 bytes, please report: at   0x7a34d8#012  0x731249#012  0x736a56#012  0x736fa4#012  0x25adbd1#012  0x25ad53f#012  0x1d4b2a6#012  0x1d5eeec#012  0x1d60697#012  0x1d2e2fe#012  0x1e65827#012  0x1e391e2#012  0x1e39a7e#012  0x252b216#012  0x1cbc8d8#012  0x1cbe7d3#012  0x1cbff3b#012  0x1cea889#012  0x1cea544#012  0x1cefc1d#012  0x6ea19c#012  0x587696#012  0x587851#012  0x652737#012  0x6742b2#012  0x72fc5d#012  /lib/x86_64-linux-gnu/libpthread.so.0+0x76b9#012  /lib/x86_64-linux-gnu/libc.so.6+0x10741c  scylla-chronicle-p-3
A  scylla-chronicle-p-2 Jan 17 16:52:43 scylla-chronicle-p-2 scylla:  [shard 3] seastar_memory - oversized allocation: 402653184 bytes, please report: at   0x7a34d8#012  0x731249#012  0x736a56#012  0x736fa4#012  0x25adbd1#012  0x25ad53f#012  0x1d4b2a6#012  0x1d5eeec#012  0x1d60697#012  0x1d2e2fe#012  0x1e65827#012  0x1e391e2#012  0x1e39a7e#012  0x252b216#012  0x1cbc8d8#012  0x1cbe7d3#012  0x1cbff3b#012  0x1cea889#012  0x1cea544#012  0x1cefc1d#012  0x6ea19c#012  0x587696#012  0x587851#012  0x652737#012  0x6742b2#012  0x72fc5d#012  /lib/x86_64-linux-gnu/libpthread.so.0+0x76b9#012  /lib/x86_64-linux-gnu/libc.so.6+0x10741c  scylla-chronicle-p-2
Jan 17 16:49:41 scylla-chronicle-p-3 scylla:  [shard 7] seastar_memory - oversized allocation: 201326592 bytes, please report: at   0x7a34d8#012  0x731249#012  0x736a56#012  0x736fa4#012  0x25adbd1#012  0x25ad53f#012  0x1d4b2a6#012  0x1d5eeec#012  0x1d60697#012  0x1d2e2fe#012  0x1e65827#012  0x1e391e2#012  0x1e39a7e#012  0x252b216#012  0x1cbc8d8#012  0x1cbe7d3#012  0x1cbff3b#012  0x1cea889#012  0x1cea544#012  0x1cefc1d#012  0x6ea19c#012  0x587696#012  0x587851#012  0x652737#012  0x6742b2#012  0x72fc5d#012  /lib/x86_64-linux-gnu/libpthread.so.0+0x76b9#012  /lib/x86_64-linux-gnu/libc.so.6+0x10741c  scylla-chronicle-p-3
Jan 17 16:41:58 scylla-chronicle-p-3 scylla:  [shard 7] seastar_memory - oversized allocation: 100663296 bytes, please report: at   0x7a34d8#012  0x731249#012  0x736a56#012  0x736fa4#012  0x25adbd1#012  0x25ad53f#012  0x1d4b2a6#012  0x1d5eeec#012  0x1d60697#012  0x1d2e2fe#012  0x1e65827#012  0x1e391e2#012  0x1e39a7e#012  0x252b216#012  0x1cbc8d8#012  0x1cbe7d3#012  0x1cbff3b#012  0x1cea889#012  0x1cea544#012  0x1cefc1d#012  0x6ea19c#012  0x587696#012  0x587851#012  0x652737#012  0x6742b2#012  0x72fc5d#012  /lib/x86_64-linux-gnu/libpthread.so.0+0x76b9#012  /lib/x86_64-linux-gnu/libc.so.6+0x10741c  scylla-chronicle-p-3
Jan 17 16:38:01 scylla-chronicle-p-3 scylla:  [shard 7] seastar_memory - oversized allocation: 50331648 bytes, please report: at   0x7a34d8#012  0x731249#012  0x736a56#012  0x736fa4#012  0x25adbd1#012  0x25ad53f#012  0x1d4b2a6#012  0x1d5eeec#012  0x1d60697#012  0x1d2e2fe#012  0x1e65827#012  0x1e391e2#012  0x1e39a7e#012  0x252b216#012  0x1cbc8d8#012  0x1cbe7d3#012  0x1cbff3b#012  0x1cea889#012  0x1cea544#012  0x1cefc1d#012  0x6ea19c#012  0x587696#012  0x587851#012  0x652737#012  0x6742b2#012  0x72fc5d#012  /lib/x86_64-linux-gnu/libpthread.so.0+0x76b9#012  /lib/x86_64-linux-gnu/libc.so.6+0x10741c  scylla-chronicle-p-3
Jan 17 16:37:35 scylla-chronicle-p-2 scylla:  [shard 3] seastar_memory - oversized allocation: 201326592 bytes, please report: at   0x7a34d8#012  0x731249#012  0x736a56#012  0x736fa4#012  0x25adbd1#012  0x25ad53f#012  0x1d4b2a6#012  0x1d5eeec#012  0x1d60697#012  0x1d2e2fe#012  0x1e65827#012  0x1e391e2#012  0x1e39a7e#012  0x252b216#012  0x1cbc8d8#012  0x1cbe7d3#012  0x1cbff3b#012  0x1cea889#012  0x1cea544#012  0x1cefc1d#012  0x6ea19c#012  0x587696#012  0x587851#012  0x652737#012  0x6742b2#012  0x72fc5d#012  /lib/x86_64-linux-gnu/libpthread.so.0+0x76b9#012  /lib/x86_64-linux-gnu/libc.so.6+0x10741c  scylla-chronicle-p-2
Jan 17 16:36:03 scylla-chronicle-p-3 scylla:  [shard 7] seastar_memory - oversized allocation: 25165824 bytes, please report: at   0x7a34d8#012  0x731249#012  0x736a56#012  0x736fa4#012  0x25adbd1#012  0x25ad53f#012  0x1d4b2a6#012  0x1d5eeec#012  0x1d60697#012  0x1d2e2fe#012  0x1e65827#012  0x1e391e2#012  0x1e39a7e#012  0x252b216#012  0x1cbc8d8#012  0x1cbe7d3#012  0x1cbff3b#012  0x1cea889#012  0x1cea544#012  0x1cefc1d#012  0x6ea19c#012  0x587696#012  0x587851#012  0x652737#012  0x6742b2#012  0x72fc5d#012  /lib/x86_64-linux-gnu/libpthread.so.0+0x76b9#012  /lib/x86_64-linux-gnu/libc.so.6+0x10741c  scylla-chronicle-p-3
Jan 17 16:35:01 scylla-chronicle-p-3 scylla:  [shard 7] seastar_memory - oversized allocation: 12582912 bytes, please report: at   0x7a34d8#012  0x731249#012  0x736a56#012  0x736fa4#012  0x25adbd1#012  0x25ad53f#012  0x1d4b2a6#012  0x1d5eeec#012  0x1d60697#012  0x1d2e2fe#012  0x1e65827#012  0x1e391e2#012  0x1e39a7e#012  0x252b216#012  0x1cbc8d8#012  0x1cbe7d3#012  0x1cbff3b#012  0x1cea889#012  0x1cea544#012  0x1cefc1d#012  0x6ea19c#012  0x587696#012  0x587851#012  0x652737#012  0x6742b2#012  0x72fc5d#012  /lib/x86_64-linux-gnu/libpthread.so.0+0x76b9#012  /lib/x86_64-linux-gnu/libc.so.6+0x10741c  scylla-chronicle-p-3
Jan 17 16:34:35 scylla-chronicle-p-3 scylla:  [shard 7] seastar_memory - oversized allocation: 6291456 bytes, please report: at   0x7a34d8#012  0x731249#012  0x736a56#012  0x736fa4#012  0x25adbd1#012  0x25ad53f#012  0x1d4b2a6#012  0x1d5eeec#012  0x1d60697#012  0x1d2e2fe#012  0x1e65827#012  0x1e391e2#012  0x1e39a7e#012  0x252b216#012  0x1cbc8d8#012  0x1cbe7d3#012  0x1cbff3b#012  0x1cea889#012  0x1cea544#012  0x1cefc1d#012  0x6ea19c#012  0x587696#012  0x587851#012  0x652737#012  0x6742b2#012  0x72fc5d#012  /lib/x86_64-linux-gnu/libpthread.so.0+0x76b9#012  /lib/x86_64-linux-gnu/libc.so.6+0x10741c  scylla-chronicle-p-3
Jan 17 16:34:25 scylla-chronicle-p-3 scylla:  [shard 7] seastar_memory - oversized allocation: 3145728 bytes, please report: at   0x7a34d8#012  0x731249#012  0x736a56#012  0x736fa4#012  0x25adbd1#012  0x25ad53f#012  0x1d4b2a6#012  0x1d5eeec#012  0x1d60697#012  0x1d2e2fe#012  0x1e65827#012  0x1e391e2#012  0x1e39a7e#012  0x252b216#012  0x1cbc8d8#012  0x1cbe7d3#012  0x1cbff3b#012  0x1cea889#012  0x1cea544#012  0x1cefc1d#012  0x6ea19c#012  0x587696#012  0x587851#012  0x652737#012  0x6742b2#012  0x72fc5d#012  /lib/x86_64-linux-gnu/libpthread.so.0+0x76b9#012  /lib/x86_64-linux-gnu/libc.so.6+0x10741c  scylla-chronicle-p-3
Jan 17 16:34:18 scylla-chronicle-p-3 scylla:  [shard 7] seastar_memory - oversized allocation: 1572864 bytes, please report: at   0x7a34d8#012  0x731249#012  0x736a56#012  0x736fa4#012  0x25adbd1#012  0x25ad53f#012  0x1d4b2a6#012  0x1d5eeec#012  0x1d60697#012  0x1d2e2fe#012  0x1e65827#012  0x1e391e2#012  0x1e39a7e#012  0x252b216#012  0x1cbc8d8#012  0x1cbe7d3#012  0x1cbff3b#012  0x1cea889#012  0x1cea544#012  0x1cefc1d#012  0x6ea19c#012  0x587696#012  0x587851#012  0x652737#012  0x6742b2#012  0x72fc5d#012  /lib/x86_64-linux-gnu/libpthread.so.0+0x76b9#012  /lib/x86_64-linux-gnu/libc.so.6+0x10741c  scylla-chronicle-p-3
```

```
addr2line -fCipe /usr/lib/debug/.build-id/./2c/7fd25f60e5c0bbedc66d6fddeaa86741cd9eec.debug 0x7a34d8#012  0x731249#012  0x736a56#012  0x736fa4#012  0x25adbd1#012  0x25ad53f#012  0x1d4b2a6#012  0x1d5eeec#012  0x1d60697#012  0x1d2e2fe#012  0x1e65827#012  0x1e391e2#012  0x1e39a7e#012  0x252b216#012  0x1cbc8d8#012  0x1cbe7d3#012  0x1cbff3b#012  0x1cea889#012  0x1cea544#012  0x1cefc1d#012  0x6ea19c#012  0x587696#012  0x587851#012  0x652737#012  0x6742b2#012  0x72fc5d#012  /lib/x86_64-linux-gnu/libpthread.so.0+0x76b9#012  /lib/x86_64-linux-gnu/libc.so.6+0x10741c

seastar::current_backtrace() at crtstuff.c:?
seastar::memory::cpu_pages::warn_large_allocation(unsigned long) at crtstuff.c:?
seastar::memory::allocate(unsigned long) at crtstuff.c:?
operator new(unsigned long) at ??:?
void std::vector<std::vector<signed char, std::allocator<signed char> >, std::allocator<std::vector<signed char, std::allocator<signed char> > > >::_M_realloc_insert<signed char const*, signed char const*>(__gnu_cxx::__normal_iterator<std::vector<signed char, std::allocator<signed char> >*, std::vector<std::vector<signed char, std::allocator<signed char> >, std::allocator<std::vector<signed char, std::allocator<signed char> > > > >, signed char const*&&, signed char const*&&) at ??:?
cql3::query_options::make_temporary(cql3::raw_value) const at crtstuff.c:?
cql3::terminal::bind_and_get(cql3::query_options const&) at crtstuff.c:?
cql3::maps::delayed_value::bind(cql3::query_options const&) at crtstuff.c:?
cql3::maps::literal::prepare(database&, seastar::basic_sstring<char, unsigned int, 15u, true> const&, seastar::shared_ptr<cql3::column_specification>) at crtstuff.c:?
cql3::operation::set_value::prepare(database&, seastar::basic_sstring<char, unsigned int, 15u, true> const&, column_definition const&) at crtstuff.c:?
cql3::statements::raw::insert_statement::prepare_internal(database&, seastar::lw_shared_ptr<schema const>, seastar::shared_ptr<cql3::variable_specifications>, std::unique_ptr<cql3::attributes, std::default_delete<cql3::attributes> >, cql3::cql_stats&) at crtstuff.c:?
cql3::statements::raw::modification_statement::prepare(database&, seastar::shared_ptr<cql3::variable_specifications>, cql3::cql_stats&) at crtstuff.c:?
cql3::statements::raw::modification_statement::prepare(database&, cql3::cql_stats&) at crtstuff.c:?
cql3::query_processor::get_statement(std::experimental::fundamentals_v1::basic_string_view<char, std::char_traits<char> > const&, service::client_state const&) at crtstuff.c:?
cql_transport::cql_server::connection::process_batch(unsigned short, std::experimental::fundamentals_v1::basic_string_view<signed char, std::char_traits<signed char> >, service::client_state) at crtstuff.c:?
cql_transport::cql_server::connection::process_request_one(std::experimental::fundamentals_v1::basic_string_view<signed char, std::char_traits<signed char> >, unsigned char, unsigned short, service::client_state, cql_transport::cql_server::connection::tracing_request_type)::{lambda()#1}::operator()() at server.cc:?
cql_transport::cql_server::connection::process_request_one(std::experimental::fundamentals_v1::basic_string_view<signed char, std::char_traits<signed char> >, unsigned char, unsigned short, service::client_state, cql_transport::cql_server::connection::tracing_request_type) at crtstuff.c:?
seastar::noncopyable_function<seastar::future<cql_transport::cql_server::connection::processing_result> (cql_transport::cql_server::connection*, std::experimental::fundamentals_v1::basic_string_view<signed char, std::char_traits<signed char> >, unsigned char, unsigned short, service::client_state, cql_transport::cql_server::connection::tracing_request_type)>::direct_vtable_for<std::_Mem_fn<seastar::future<cql_transport::cql_server::connection::processing_result> (cql_transport::cql_server::connection::*)(std::experimental::fundamentals_v1::basic_string_view<signed char, std::char_traits<signed char> >, unsigned char, unsigned short, service::client_state, cql_transport::cql_server::connection::tracing_request_type)> >::call(seastar::noncopyable_function<seastar::future<cql_transport::cql_server::connection::processing_result> (cql_transport::cql_server::connection*, std::experimental::fundamentals_v1::basic_string_view<signed char, std::char_traits<signed char> >, unsigned char, unsigned short, service::client_state, cql_transport::cql_server::connection::tracing_request_type)> const*, cql_transport::cql_server::connection*, std::experimental::fundamentals_v1::basic_string_view<signed char, std::char_traits<signed char> >, unsigned char, unsigned short, service::client_state, cql_transport::cql_server::connection::tracing_request_type) at crtstuff.c:?
seastar::noncopyable_function<seastar::future<cql_transport::cql_server::connection::processing_result> (cql_transport::cql_server::connection*, std::experimental::fundamentals_v1::basic_string_view<signed char, std::char_traits<signed char> >, unsigned char, unsigned short, service::client_state, cql_transport::cql_server::connection::tracing_request_type)>::direct_vtable_for<seastar::inheriting_concrete_execution_stage<seastar::future<cql_transport::cql_server::connection::processing_result>, cql_transport::cql_server::connection*, std::experimental::fundamentals_v1::basic_string_view<signed char, std::char_traits<signed char> >, unsigned char, unsigned short, service::client_state, cql_transport::cql_server::connection::tracing_request_type>::make_stage_for_group(seastar::scheduling_group)::{lambda(cql_transport::cql_server::connection*, std::experimental::fundamentals_v1::basic_string_view<signed char, std::char_traits<signed char> >, unsigned char, unsigned short, service::client_state, cql_transport::cql_server::connection::tracing_request_type)#1}>::call(seastar::noncopyable_function<seastar::future<cql_transport::cql_server::connection::processing_result> (cql_transport::cql_server::connection*, std::experimental::fundamentals_v1::basic_string_view<signed char, std::char_traits<signed char> >, unsigned char, unsigned short, service::client_state, cql_transport::cql_server::connection::tracing_request_type)> const*, cql_transport::cql_server::connection*, std::experimental::fundamentals_v1::basic_string_view<signed char, std::char_traits<signed char> >, unsigned char, unsigned short, service::client_state, cql_transport::cql_server::connection::tracing_request_type) at crtstuff.c:?
seastar::concrete_execution_stage<seastar::future<cql_transport::cql_server::connection::processing_result>, cql_transport::cql_server::connection*, std::experimental::fundamentals_v1::basic_string_view<signed char, std::char_traits<signed char> >, unsigned char, unsigned short, service::client_state, cql_transport::cql_server::connection::tracing_request_type>::do_flush() at crtstuff.c:?
seastar::lambda_task<seastar::execution_stage::flush()::{lambda()#1}>::run_and_dispose() at execution_stage.cc:?
seastar::reactor::run_tasks(seastar::reactor::task_queue&) at crtstuff.c:?
seastar::reactor::run_some_tasks() [clone .part.2728] at reactor.cc:?
seastar::reactor::run() at crtstuff.c:?
seastar::smp::configure(boost::program_options::variables_map)::{lambda()#3}::operator()() const at reactor.cc:?
seastar::posix_thread::start_routine(void*) at crtstuff.c:?
```

**Comment by avikivity** [comment] 2019-01-18 08:34
That's 1.6GB, beating the existing record by a wide margin.

It looks like you're inserting a map value. Can you give more details? Is it possible you're inserting a map that is 1.6GB in size? It seems very unlikely, so please provide as many details as you can.

**Comment by avikivity** [comment] 2019-01-18 08:35
That number is 0x6000'0000, which likely came from somewhere else.

**Comment by lustefaniak** [comment] 2019-01-18 08:50
It is very unlikely we are inserting 1.6GB map. Inserting (migrating) script was using 4gb of memory on JVM and was doing 4 threads in parallel with multiple(whole hour) rows at the same time - 1.6GB maps wouldn't probably even fit in memory in that script.

**Comment by avikivity** [comment] 2019-01-18 08:50
1572864 == 0x18'0000

Maybe there's a bug around those nested maps. Using a frozen map as a key to the outer frozen map is quite unique.

@roydahan do we have tests that are similar?

@lustefaniak out of curiousity, can you share the logic behind that map?

Also, be aware that maps above a few megabytes in size will perform very poorly.

**Comment by avikivity** [comment] 2019-01-18 08:51
@lustefaniak yes, it's likely a scylla bug.

**Comment by lustefaniak** [comment] 2019-01-18 08:57
We are inserting them in batches, their size is usually:
```
[shard 3] BatchStatement - Batch of prepared statements for overlaps.by_respondent is of size 306097, exceeding specified WARN threshold of 262144 by 43953.
```

**Comment by lustefaniak** [comment] 2019-01-18 08:58
It stores some attributes group and their count:  keys in outer map are map with attribute name and its value, key of outer map is how many of such attributes we recorded for `(id1, hour, id2)`

**Comment by avikivity** [comment] 2019-01-18 16:56
I managed to insert such a type in a simple test, so it's not something trivial.

**Comment by avikivity** [comment] 2019-01-18 17:19
What about the inner map? if the total size of an inner map (key + values + some small overhead per entry) exceeds 64k, that violates the expectation that map keys are smaller than 64k.

**Comment by lustefaniak** [comment] 2019-01-18 17:21
Oh, didn't know about that about the limit, I will check it. I think it should be smaller.

**Comment by avikivity** [comment] 2019-01-18 17:22
Actually, that 64k restriction was lifted, I was able to insert and retrieve records with inner maps that are hundreds of kilobytes. What driver and driver version are you using?

**Comment by lustefaniak** [comment] 2019-01-18 17:26
We use everywhere `com.datastax.cassandra:cassandra-driver-core:3.6.0`

**Comment by slivne** [comment] 2019-01-27 11:38
@lustefaniak can you upload a core / sstables related to this and we will try to reproduce on our end.

**Comment by lustefaniak** [comment] 2019-01-29 13:51
I will try to create a reproducer script from our initial import, I will use a similar distribution of map keys as in true dataset and I will check if I get those problems again. Unfortunately, I can't share original files.

**Comment by slivne** [comment] 2019-07-08 08:27
@lustefaniak there was no update from you - closing the issue, if you can share some additional info please post and we can reopen

**Closed by slivne** 2019-07-08 08:27 UTC
Labels: User Request, bug
