### ISSUE TITLE
scylla-debuginfo doesn't include the file to decode backtrace

### ISSUE THREAD

**Issue by roydahan** [scylladb/scylla#5484] opened 2019-12-16 16:09 UTC
Scylla version (or git commit hash): 666.development-0.20191211.761b19cee58
OS (RHEL/CentOS/Ubuntu/AWS AMI):  AWS (ami-0ce8d67386d22b828 eu-west-1)

Installed rpms:
```
[centos@ip-10-0-170-88 ~]$ rpm -qa | grep scylla
scylla-conf-666.development-0.20191211.761b19cee58.el7.x86_64
scylla-server-666.development-0.20191211.761b19cee58.el7.x86_64
scylla-666.development-0.20191211.761b19cee58.el7.x86_64
scylla-jmx-666.development-20191211.31e6bcf9bed.noarch
scylla-python3-3.7.5-0.20191211.761b19cee58.el7.x86_64
scylla-kernel-conf-666.development-0.20191211.761b19cee58.el7.x86_64
scylla-tools-666.development-20191211.35906df2a0d.noarch
scylla-debuginfo-666.development-0.20191211.761b19cee58.el7.x86_64
scylla-tools-core-666.development-20191211.35906df2a0d.noarch
scylla-ami-666.development-20191212.a0f9200a6a5.fc27.noarch
```

libexec dir:
```
[centos@ip-10-0-170-88 ~]$ ls /usr/lib/debug/opt/scylladb/libexec/
iotune-666.development-0.20191211.761b19cee58.el7.x86_64.debug
```

Files of debuginfo:
```
[centos@ip-10-0-170-88 ~]$ rpm -ql scylla-debuginfo | xargs ls -ldh
drwxr-xr-x. 5 root root   92 Dec 12 02:21 /usr/lib/debug
drwxr-xr-x. 9 root root   76 Dec 12 02:21 /usr/lib/debug/.build-id
drwxr-xr-x. 2 root root  104 Dec 12 02:21 /usr/lib/debug/.build-id/2d
lrwxrwxrwx. 1 root root   60 Dec 12 02:21 /usr/lib/debug/.build-id/2d/70675988b341fbcf150bd687e209154e1f7806 -> ../../../.build-id/2d/70675988b341fbcf150bd687e209154e1f7806
lrwxrwxrwx. 1 root root  117 Dec 12 02:21 /usr/lib/debug/.build-id/2d/70675988b341fbcf150bd687e209154e1f7806.debug -> ../../../../../usr/lib/debug/opt/scylladb/libreloc/libdl.so.2-666.development-0.20191211.761b19cee58.el7.x86_64.debug
drwxr-xr-x. 2 root root  202 Dec 12 02:21 /usr/lib/debug/.build-id/2e
lrwxrwxrwx. 1 root root   60 Dec 12 02:21 /usr/lib/debug/.build-id/2e/6b213b18caff80085d99e10796f3be31dcf598 -> ../../../.build-id/2e/6b213b18caff80085d99e10796f3be31dcf598
lrwxrwxrwx. 1 root root  112 Dec 12 02:21 /usr/lib/debug/.build-id/2e/6b213b18caff80085d99e10796f3be31dcf598.debug -> ../../../../../usr/lib/debug/opt/scylladb/libreloc/ld.so-666.development-0.20191211.761b19cee58.el7.x86_64.debug
lrwxrwxrwx. 1 root root   60 Dec 12 02:21 /usr/lib/debug/.build-id/2e/fae4f70bd47c9c917c0c6f3f7138c2f1afb49f -> ../../../.build-id/2e/fae4f70bd47c9c917c0c6f3f7138c2f1afb49f
lrwxrwxrwx. 1 root root  116 Dec 12 02:21 /usr/lib/debug/.build-id/2e/fae4f70bd47c9c917c0c6f3f7138c2f1afb49f.debug -> ../../../../../usr/lib/debug/opt/scylladb/libreloc/libc.so.6-666.development-0.20191211.761b19cee58.el7.x86_64.debug
drwxr-xr-x. 2 root root  104 Dec 12 02:21 /usr/lib/debug/.build-id/57
lrwxrwxrwx. 1 root root   60 Dec 12 02:21 /usr/lib/debug/.build-id/57/8e6635f7bb48f5aa21972a5712a3f4352e5d66 -> ../../../.build-id/57/8e6635f7bb48f5aa21972a5712a3f4352e5d66
lrwxrwxrwx. 1 root root  116 Dec 12 02:21 /usr/lib/debug/.build-id/57/8e6635f7bb48f5aa21972a5712a3f4352e5d66.debug -> ../../../../../usr/lib/debug/opt/scylladb/libreloc/libm.so.6-666.development-0.20191211.761b19cee58.el7.x86_64.debug
drwxr-xr-x. 2 root root  104 Dec 12 02:21 /usr/lib/debug/.build-id/87
lrwxrwxrwx. 1 root root   60 Dec 12 02:21 /usr/lib/debug/.build-id/87/b5c6fbd5c38dcae55157aa8bc2660cc29d2951 -> ../../../.build-id/87/b5c6fbd5c38dcae55157aa8bc2660cc29d2951
lrwxrwxrwx. 1 root root  112 Dec 12 02:21 /usr/lib/debug/.build-id/87/b5c6fbd5c38dcae55157aa8bc2660cc29d2951.debug -> ../../../../../usr/lib/debug/opt/scylladb/libexec/iotune-666.development-0.20191211.761b19cee58.el7.x86_64.debug
drwxr-xr-x. 2 root root  104 Dec 12 02:21 /usr/lib/debug/.build-id/8d
lrwxrwxrwx. 1 root root   60 Dec 12 02:21 /usr/lib/debug/.build-id/8d/c13dd196ce8c55fccfa1be2f300566deca1b6c -> ../../../.build-id/8d/c13dd196ce8c55fccfa1be2f300566deca1b6c
lrwxrwxrwx. 1 root root  122 Dec 12 02:21 /usr/lib/debug/.build-id/8d/c13dd196ce8c55fccfa1be2f300566deca1b6c.debug -> ../../../../../usr/lib/debug/opt/scylladb/libreloc/libpthread.so.0-666.development-0.20191211.761b19cee58.el7.x86_64.debug
drwxr-xr-x. 2 root root  104 Dec 12 02:21 /usr/lib/debug/.build-id/b0
lrwxrwxrwx. 1 root root   60 Dec 12 02:21 /usr/lib/debug/.build-id/b0/32d1ad5d70b8ef07bbba3228b6840b93216861 -> ../../../.build-id/b0/32d1ad5d70b8ef07bbba3228b6840b93216861
lrwxrwxrwx. 1 root root  124 Dec 12 02:21 /usr/lib/debug/.build-id/b0/32d1ad5d70b8ef07bbba3228b6840b93216861.debug -> ../../../../../usr/lib/debug/opt/scylladb/libreloc/libthread_db.so.1-666.development-0.20191211.761b19cee58.el7.x86_64.debug
drwxr-xr-x. 2 root root  104 Dec 12 02:21 /usr/lib/debug/.build-id/ff
lrwxrwxrwx. 1 root root   60 Dec 12 02:21 /usr/lib/debug/.build-id/ff/e88a332feba0cd078c4f60ae621308e977793d -> ../../../.build-id/ff/e88a332feba0cd078c4f60ae621308e977793d
lrwxrwxrwx. 1 root root  117 Dec 12 02:21 /usr/lib/debug/.build-id/ff/e88a332feba0cd078c4f60ae621308e977793d.debug -> ../../../../../usr/lib/debug/opt/scylladb/libreloc/librt.so.1-666.development-0.20191211.761b19cee58.el7.x86_64.debug
drwxr-xr-x. 3 root root   22 Dec 12 02:21 /usr/lib/debug/opt
drwxr-xr-x. 4 root root   37 Dec 12 02:22 /usr/lib/debug/opt/scylladb
drwxr-xr-x. 2 root root   76 Dec 12 02:22 /usr/lib/debug/opt/scylladb/libexec
-r--r--r--. 1 root root 190M Dec 11 23:52 /usr/lib/debug/opt/scylladb/libexec/iotune-666.development-0.20191211.761b19cee58.el7.x86_64.debug
drwxr-xr-x. 2 root root 4.0K Dec 12 02:22 /usr/lib/debug/opt/scylladb/libreloc
-r--r--r--. 1 root root  79K Dec 11 23:52 /usr/lib/debug/opt/scylladb/libreloc/ld.so-666.development-0.20191211.761b19cee58.el7.x86_64.debug
-r--r--r--. 1 root root 1.3M Dec 11 23:52 /usr/lib/debug/opt/scylladb/libreloc/libc.so.6-666.development-0.20191211.761b19cee58.el7.x86_64.debug
-r--r--r--. 1 root root  16K Dec 11 23:52 /usr/lib/debug/opt/scylladb/libreloc/libdl.so.2-666.development-0.20191211.761b19cee58.el7.x86_64.debug
-r--r--r--. 1 root root 595K Dec 11 23:52 /usr/lib/debug/opt/scylladb/libreloc/libm.so.6-666.development-0.20191211.761b19cee58.el7.x86_64.debug
-r--r--r--. 1 root root 209K Dec 11 23:52 /usr/lib/debug/opt/scylladb/libreloc/libpthread.so.0-666.development-0.20191211.761b19cee58.el7.x86_64.debug
-r--r--r--. 1 root root  38K Dec 11 23:52 /usr/lib/debug/opt/scylladb/libreloc/librt.so.1-666.development-0.20191211.761b19cee58.el7.x86_64.debug
-r--r--r--. 1 root root  39K Dec 11 23:52 /usr/lib/debug/opt/scylladb/libreloc/libthread_db.so.1-666.development-0.20191211.761b19cee58.el7.x86_64.debug
```

**Comment by roydahan** [comment] 2019-12-17 08:33
@penberg Is it something for your team?

**Comment by avikivity** [comment] 2019-12-17 12:51
@slivne bisected the packages sizes and saw the problem is between 28355af134f and 91d3f2afceb.

The only obvious candidate is 1cd17887fa65138f799b97273b64762e51332c28, but as far as I can tell it is correct. I inspected the generated build.ninja and it uses link.release as its build rule.

reloc/build_reloc.sh doesn't pass --debuginfo 0

@espindola any ideas?

**Comment by avikivity** [comment] 2019-12-17 13:08
I think it's a jenkins script bug:

```
11:17:19  [Pipeline] echo
11:17:19  Building. debugFlag: |false|, skipHeavyOperations: |false|, buildRelocPackage: |true|,
11:17:19  [Pipeline] echo
11:17:19  scyllaRelocS3Path: |next|, makeMode: ||, withArtifacts: ||, userRequestedParam: ||
11:17:19  [Pipeline] echo
11:17:19  scyllaSha: |f7d69b042820dbbe617a1febec510e4b3f6f4b5e| jmxSha: |771cf6ea50618c7a0679dd172b35b15b16b6d916| toolsJavaSha: |771cf6ea50618c7a0679dd172b35b15b16b6d916|
11:17:20  [Pipeline] echo
11:17:20  Running with no debug info
```

**Comment by avikivity** [comment] 2019-12-17 13:17
Closing, since this is likely a problem with the jenkins scripts.

**Closed by avikivity** 2019-12-17 13:17 UTC
Labels: bug
